### ISSUE TITLE
Reports that users will need

### ISSUE THREAD

**Issue by jamesefhawkins** [PostHog/posthog#1]
# Initial product design

This is not split into MVP versus regular product. It's a list of common requirements we'll face in the first few months, and was based on going through our own implementation of Mixpanel.

## Terminology

"Action" - this is an important Event. This should be a user taking a postive action, like a form submit, creating a Facebook post, giving feedback in Hiberly.

## Who is using my app a lot?

* I need to be able to see a list of users next to how many actions they have taken.
* I need to be able to see these actions categorised - the total volume isn't relevant. I need to be able to see:
  * I need to be able to categorise some Event types into Actions, ie "gave feedback", "page visits" or "created retrospective" in Hiberly, and to see the action volumes within each of these action categories by user. (I wonder if we could do quite a lot of this automatically).
  * I want to be able to see if a user's activity has been recent.
  * I want to know why certain users with high volume of usage are using it so much.
    *This means knowing as much as possible about who they are and where they came from, and all the data they have given if they have made a user profile.

## Who has used my app recently?

* I need to be able to see a list of Actions in order of recency, with the User visible.

## Is my app getting more popular or are people quitting?

* I need to be able to see the Actions over time.
  * For example, I need to be able to see Daily Active / Monthly Active users

## Are people coming back to my app? Do they like it?

* I need to be able to visualise Actions over time.
* I need to be able to segment the above by User, so I can work out which users are coming back.
* I need to be able to see a standard retention table for event -> event (Heap and Mixpanel both look almost identical here):

## Someone took a very important action, like signed up or started paying us, how come?

* I need to be able to see for everyone that lands on the website, which pages they follow and which actions they take.
  * If they exited and did not convert, I need to be able to see this journey too (it's going to be most people!)
  * I need to easily be able to segment by the kind of person this is. For example to see the journey for Users, or the journey for Paying Users. We need to be able to create audience segments to do this.
* I need to capture any other url parameters automatically.
  * I will usually use UTM tags for this information.

## Where am I losing people in the signup flow?

* I need to be able to list out the key actions to achieve the goal I have (ie a paying customer or a signup)
* I need to be able to visualise the percentage drop off at each of these stages.
* I need to be able to see the trend in this graph over time to see if optimisations
  * I would love to be able to map experiments or pull requests to this graph so I don't have to dig through other tools to work out what changed.

## Which parts of my online marketing are the most effective? NOT IN MVP

* I need to see the ROI of my marketing spend.
  * I need to be able to segment this by flexible combinations of UTM tags.

**Comment by jamesefhawkins** [comment]
We've done this except for the spend, which we are moving away from for now.

**Comment by yakkomajuri** [comment]
@posthog-bot please add @bla for ideas

**Comment by yakkomajuri** [comment]
@posthog-bot please add @Bla for idea
