### ISSUE TITLE
Forever redirect when running posthog behind NGINX proxy

### ISSUE THREAD

**Issue by rberrelleza** [PostHog/posthog#100]
I was trying to run posthog on Kubernetes, behind NGINX ingress controller but I'm getting a redirect loop. From Django's docs it seems like you might be missing the `SECURE_PROXY_SSL_HEADER` setting.

**Comment by hgezim** [comment]
Can you please add this to the docs? @rberrelleza?

TLS is mentioned a couple times here: https://posthog.com/docs/deployment/deploy-aws but it doesn't mention that if you're using a load balaner to redirect traffic you need to set `IS_BEHIND_PROXY`.
