### ISSUE TITLE
Better default sort order on the Actions screen (or save last set sort order)

### ISSUE THREAD

**Issue by jackiegreenfield** [PostHog/posthog#10017]
## Is your feature request related to a problem?

I often go to the actions page to see the latest actions that I or a team member has created. Each time, I have to click the "Created" column twice since by default, actions are ordered by creator and the first click on created date shows me the oldest first. 

## Describe the solution you'd like
Either show the newest by default (which I feel would make sense for most people), or save the ordering that someone last left the page in. 

## Describe alternatives you've considered
Continue to click twice each time. (well, three times since I have to click on Data Management > Actions). It's a 'paper cut' kind of thing - not a big deal, but annoying to do over and over again. 

## Additional context
Actions often take a few minutes to make it into our Posthog screens after I create them with the toolbar in our app, which is one reason I'm often checking this screen. It's also useful to see what other actions team members are making.

**Comment by clarkus** [comment]
Agree this would be a good change. We're working on this area of the product in our upcoming sprint, so I've incorporated [these changes](https://www.figma.com/file/gQBj9YnNgD8YW4nBwCVLZf/PostHog-App?node-id=10788%3A48581) into that scope of work. 

![data management - events](https://user-images.githubusercontent.com/254612/170532655-9c56f9ea-e9e2-4231-bb84-7f7468528c9f.png)
