### ISSUE TITLE
Clicking a column header asks me if I want to leave the page

### ISSUE THREAD

**Issue by corywatilo** [PostHog/posthog#10023]
In an unsaved insight, clicking a column header (to sort by that column) asks me if I want to leave the page.

As a user, I want to be able to run a query and manipulate the presentation of the results without having to first save the insight.
 
![2022-05-26 15 35 56](https://user-images.githubusercontent.com/154479/170563958-cbeba4e3-6757-4cab-a22b-01cc0641cda4.gif)

**Comment by clarkus** [comment]
I thought this was resolved in https://github.com/PostHog/posthog/pull/9625. Anyway definitely related. Also mentioned in this [slack thread](https://posthog.slack.com/archives/C02LR7352SG/p1652739083744229).

**Comment by corywatilo** [comment]
Worth noting: after clicking Cancel, the sorting _does_ apply

**Comment by corywatilo** [comment]
This bug appears to have gotten worse. Previously I would get the JS prompt but the sorting option would apply. Now I get the prompt but no sorting happens at all.

![2022-06-14 14 03 05](https://user-images.githubusercontent.com/154479/173658479-87a3588a-c2d3-4d2b-994a-74f26c881305.gif)

**Comment by pauldambra** [comment]
@benjackwhite (in case the reopening hasn't notified you) - could this be the keaunloader change in #10268? (lazily not checking myself :))

**Comment by corywatilo** [comment]
This is _still_ happening for me.

![2022-08-10 21 08 24](https://user-images.githubusercontent.com/154479/184048417-8925a1d1-5198-4ac1-a5b4-24b9a8b3800f.gif)
