### ISSUE TITLE
Recordings don't render a scroll that doesn't happen on the body.

### ISSUE THREAD

**Issue by isaiahdahl** [PostHog/posthog#10021]
## Bug description

Our site is an Ionic Angular app. One of the things that happens in an ionic app is the scroll doesn't happen on the body, it happens in their own `<ion-content>` element. 

I believe that because the scroll on the website doesn't happen on the body, none of the scrolling is captured by the recording. So the recording only looks right when the user is at the top of the page. 

## How to reproduce

1. Do a screen recording where scrolling happens not on the body. [Production Example: PraiseCharts](https://www.praisecharts.com)
2. Scroll around.
3. See that the recording doesn't show your scrolling. 

## Environment

- [x] PostHog Cloud
- [ ] self-hosted PostHog (ClickHouse-based), version/commit: _please provide_
- [ ] self-hosted PostHog (Postgres-based, legacy), version/commit: _please provide_

**Comment by sneko** [comment]
@isaiahdahl had this issue in the past while using Sentry when tracking fatal errors.

I guess it comes from https://github.com/rrweb-io/rrweb that records the DOM changes. Better to post there I guess?

**Comment by pauldambra** [comment]
The default version of rrweb is now rrweb2. Feel free to re-open if this is still happening for you!
