### ISSUE TITLE
Loading session recordings on cloud is slow

### ISSUE THREAD

**Issue by macobo** [PostHog/posthog#10051]
## In what situation are you experiencing subpar performance?

Loading session recordings on posthog Cloud is currently slow

## How to reproduce

1. Go to sessions page
2. (optional) Open network panel
3. Open a session
4. Wait 30 seconds for it to load
5. (optional) See requests for `app.posthog.com/api/projects/{project_id}/session_recordings/{id}` and `app.posthog.com/api/projects/{project_id}/session_recordings/{id}/snapshots` take over 30 seconds

## Environment

- [x] PostHog Cloud
- [ ] self-hosted PostHog, version/commit: _please provide_

## Additional context

cc infra: @fuziontech  @guidoiaquinti @hazzadous I believe we migrated session recordings onto a new disk recently. Do we know if this slowness is related?

Graph for clickhouse query timing for one of these endpoints: https://metrics.posthog.com/d/vo7oCVZ7z/clickhouse-queries-by-endpoint?orgId=1&from=1651301339976&to=1653893339976&viewPanel=3262

**Comment by hazzadous** [comment]
Haven't looked into this, but also around this time is a ClickHouse update. I know there was some work around disk policies to get this to work but I don't know the details. @fuziontech any lightbulbs?

**Comment by daibhin** [comment]
Session recording data is no longer stored in ClickHouse
