### ISSUE TITLE
Postgres and Clickhouse person properties out of sync

### ISSUE THREAD

**Issue by tiina303** [PostHog/posthog#10058]
## Bug description

1. https://posthogusers.slack.com/archives/C01GLBKHKQT/p1648073716827669?thread_ts=1647438695.856059&cid=C01GLBKHKQT
2. https://posthogusers.slack.com/archives/C01GLBKHKQT/p1648074992030689?thread_ts=1646028520.033109&cid=C01GLBKHKQT
3. https://posthogusers.slack.com/archives/C01GLBKHKQT/p1647530321217139

> We have two databases: Postgres (source of truth for person properties) & Clickhouse (used for queries; person properties are sent as a blob on any changes, so queries can be faster in only one DB).
When we process person properties we write them to both, but for ClickHouse writing path we currently have a race condition and two events coming in at the same time might mean the second event's changes with all the previous properties only get recorded in ClickHouse. However note that in Postgres we have all the values and when there's a new person property update the blob will be updated in ClickHouse too.

Processing in order will help: https://github.com/PostHog/posthog/issues/9181 but there can be other reasons we run into this.

Use versions in ClickHouse for collapsing would fix this, but given the move to persons on events this will not be relevant in the future. Created the issue so it's easier to refer to and we can close once not relevant anymore.

## How to reproduce

1. Send two events at the same time against the same person (it's a race condition so hard to repro).

## Environment

- [x] PostHog Cloud
- [x] self-hosted PostHog (ClickHouse-based), version/commit: _please provide_
- [x] self-hosted PostHog (Postgres-based, legacy), version/commit: _please provide_

**Comment by tiina303** [comment]
See not solved issues in https://github.com/PostHog/posthog/pull/10135

**Comment by guidoiaquinti** [comment]
I might miss something obvious, but I don’t think we will ever address the overall issue of keeping two datastore systems in sync without implementing something like 2 phase commits (and we shouldn’t do that!). 

With the little understanding I have about the product, would something like 👇 work? 

* we calculate the property change in a single authoritative place

* this _single place_ will use some sort of partitioning (or locking) to work around the data race issue

* once the data is calculated, we persist it to a single datastore (PostgreSQL) and we make that change propagate to any downstream subscribers (a-la, change data capture pipeline)

**PRO**
* the lag can be easily measured and should be limited by the replication factor
* it will likely not require any new components 
* we will leverage systems that we already know (PostgreSQL, Kafka, ClickHouse)

**CONS**
* we might need to create a runbook on how to rebuild/refeed the ClickHouse table in case of issues (something like: full table scan & get `$LAST_TRANSACTION_ID`, push all the rows to ClickHouse till `$LAST_TRANSACTION_ID`, ask ClickHouse to resume pulling from Kafka from `$LAST_TRANSACTION_ID`)


Edit: as suggested by @macobo I'm moving the conversation to https://github.com/PostHog/posthog/issues/10239
