### ISSUE TITLE
Heroku/docker installations install dev requirements.

### ISSUE THREAD

**Issue by timgl** [PostHog/posthog#1005]
**Is your feature request related to a problem? Please describe.**

When installing a production environment, we also install all the dev requirements in package.json, including cypress. This means going from 0 to Heroku instance up and running takes a lot longer than it should

**Describe the solution you'd like**

Don't install dev requiremnts.

**Describe alternatives you've considered**

**Additional context**

***Thank*** you for your feature request - we love each and every one!

**Comment by mariusandra** [comment]
In Heroku, we need the dev dependencies to compile the bundles... or am I missing something?

**Comment by timgl** [comment]
Hm in that case those shouldn't be dev dependencies right?

**Comment by mariusandra** [comment]
Hm... I've always thought of it as:
dependencies - stuff your built app depends on
devDependencies - stuff you need to develop your app

**Comment by timgl** [comment]
Yes so Heroku should only install the stuff needed to build, but not things like cypress

**Comment by mariusandra** [comment]
Um, yes, those all go under `devDependencies`. I should have been more explicit:

- dependencies - stuff your built app depends on (react, redux, antd, etc)
- devDependencies - stuff you need to develop/build your app (webpack, webpack-dev-server, style-loader, cypress, etc)

I will add that this `devDependencies` vs `dependencies` separation makes most sense for "nodejs apps", where all `dependencies` of a package you include are also automatically installed when you run "npm install"... and a bit less for "webpack apps", where the end result is a folder of compiled assets.

Still, I've seen people use this separation even in webpack apps... and according to that, all dev tooling should be in `devDependencies`. 

I totally get your point though. Installing cypress (which probably also installs chrome?) is a bit of an overkill when you are not using it. I'm just not sure what the solution is... :).

**Comment by 14MR** [comment]
Probably this can be solved via two options:
1. Create separate `requirements-dev.txt`
2. Using [poetry](https://python-poetry.org/)

**Comment by Twixes** [comment]
This seems solved with `requirements-dev`.
