### ISSUE TITLE
Allow properties set on anonymous users

### ISSUE THREAD

**Issue by timgl** [PostHog/posthog#1006]
Our backend allows you to set properties on anonymous users, however posthog-js won't send anything if you haven't called `identify`.

**Comment by timgl** [comment]
Done

**Comment by calvinwoo** [comment]
Is this still the intended behavior? The docs indicate that calling `identify` is required: https://posthog.com/docs/libraries/js#sending-user-information

Edit:
Tested this just now and it works without `identify`, so the docs are probably out of date.

**Comment by mariusandra** [comment]
Good remark! I made a PR to remove the note from the docs: https://github.com/PostHog/posthog.com/pull/1594
