### ISSUE TITLE
Funnel Property Filters & Breakdown on first/last touch

### ISSUE THREAD

**Issue by marcushyett-ph** [PostHog/posthog#10060]
### Scenarios

**Sign Up -> Add to Cart -> Checkout** 

- I want to break this down by unique IDs of products (Last Touch)
    - Problem: Sign up does not have the unique ID of a product
    - Solution: Filter on the property from the final event
- I want to break down by the source of the traffic where a user came from (First Touch)
    - Problem: Only is the only event where we have referring urls
    - Solution: Filter on the property from the first event
- I want to filter to a specific product being added to cart (Step X touch, or any step touch)
    - Problem: Signup or Checkout will not necessarily have this ID
    - Solution:
         - Filter by specific step (e.g. Add to Cart)
          - Filter by any step (e.g. Sign Up OR Add to Cart OR Checkout)
- I want to filter to users who were in country X during every step within the funnel (All)

**Problem 1: Step specific person property filters**
Solution: We get this for free, with persons on events, you can filter by user properties on a specific step, but we should inform users of  the change, global filters should filter across all step

**Problem 2: Breakdowns**
Solution: Support First Touch, Last Touch, Step(s) N with breakdown

**Open questions**
* How do we design for this without confusing users?

**Comment by marcushyett-ph** [comment]
cc: @neilkakkar @neilkakkar @EDsCODE @macobo

**Comment by neilkakkar** [comment]
For UI/UX work of problem 1, have spawned a new issue #10151
