### ISSUE TITLE
mmdbcdn.posthog.net is providing a stale version of the GeoLite DB

### ISSUE THREAD

**Issue by joetrollo** [PostHog/posthog#10084]
## Bug description

The CDN that the plugin server downloads the GeoLite DB from is returning a version of the database from April 12th, which is 49 days old. The plugin server considers anything older than 45 days old to be stale, and so continuously re-downloads the DB. (This in turn causes the plugin server to crash for me, but that is a separate issue.)

## How to reproduce

`curl -v https://mmdbcdn.posthog.net/` and notice that the `Content-Disposition` header has `filename="GeoLite2-City-2022-04-12.mmdb"`. The most recent of the DB I downloaded from MaxMind is from May 27th, just 4 days old.

## Environment

- [ ] PostHog Cloud
- [X] self-hosted PostHog (ClickHouse-based), version/commit: release-1.36.0
- [ ] self-hosted PostHog (Postgres-based, legacy), version/commit: _please provide_

## Additional context

I'm not sure if this is the correct repo to file this issue in, so I apologize if it should be somewhere else.

Some information about the crash that got me noticing this in the first place: the plugin pods in my instance have been crash-looping quite a lot, and the last thing in the logs is always:

```
2022-05-31T17:15:48.486Z [info] (MAIN) ⏳ Downloading GeoLite2 database from PostHog servers... [/home/posthog/code/plugin-server/dist/main/services/mmdb.js:47] logId=01811b1d-d386-0000-4f85-b894706b2611
2022-05-31T17:15:50.759Z [info] (MAIN) ✅ Downloaded GeoLite2-City-2022-04-12.mmdb of 23.2 MB [/home/posthog/code/plugin-server/dist/main/services/mmdb.js:52] logId=01811b1d-dc67-0000-34bc-e9209f5741b2
error Command failed with signal "SIGKILL".
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

This leads me to believe the issue is [somewhere here](https://github.com/PostHog/posthog/blob/272dab8528bc15b161a7c4865d3aae4a5d11add5/plugin-server/src/main/services/mmdb.ts#L72-L89), after the log on line 69 but before the one on line 89. Unfortunately, I don't see any relevant exceptions in Sentry. I do notice that the `posthog_pluginattachment` table does _not_ get a new row after the pod crashes, which perhaps points to an issue with the `INSERT` but I'm not confident.

**Comment by Twixes** [comment]
Hi! Thanks for flagging this. This service is hosted on Heroku and was impacted by recent issues with Heroku's GitHub integration that prevented it from redeploying for a while… Just fixed this and now it's serving a fresh MMDB again.

**Comment by joetrollo** [comment]
Thank you for the quick fix! I see my plugin servers downloading the new version, ~but am still encountering the crash I mentioned so I'll open another ticket.~ nevermind, the other issue was my mistake

**Comment by Twixes** [comment]
Are you still experiencing it @suraj-mandal? I don't see any issue on our end.
