### ISSUE TITLE
Migrate from Heroku Kafka to MSK

### ISSUE THREAD

**Issue by yakkomajuri** [PostHog/posthog#10083]
Quick dump of a checklist for now:

**Required tasks**

- [x] Create MSK cluster
- [x] Create appropriate security group and add to brokers
- [x] Check that plugin tasks can connect
- [x] Check that Django can connect
- [x] Check that CH can connect
- [x] Create topics (related: #10080)
- [x] Fine tune Kafka settings on MSK according to our needs
- [x] Set up a new pair of Kafka + MV tables for each existing pair, writing to the same tables but connecting to the MSK cluster
- [x] Run 2 plugin services, each connecting to one Kafka cluster: https://github.com/PostHog/posthog/pull/10104
- [x] Flip the Django task to produce to MSK: https://github.com/PostHog/posthog/pull/10103

**Follow ups**

- [x] Get metrics on Grafana
- [ ] Start dumping messages to S3 (via e.g. kafka connect)
- [ ] Reduce retention on topics 
- [ ] Document the MSK setup

**Comment by yakkomajuri** [comment]
Django connection to MSK

- Make sure our producers and consumers have the right config 
- Set KAFKA_SECURITY_PROTOCOL to `SSL` on the ECS task
- Create a new secret for KAFKA_URL and update the task definition

**Comment by yakkomajuri** [comment]
## Notes

- CH3 is connected to MSK, all other nodes are connected to Heroku Kafka
    - Approach used: delete all Kafka + MV tables, update node Kafka config manually, restart server, create all tables again
- Topics were created via the admin client with the following definition:

```
[
    NewTopic(
        name="conversion_events_buffer",
        num_partitions=128,
        replication_factor=3,
        topic_configs={"retention.ms": 24 * 60 * 60 * 1000},
    ),
    NewTopic(
        name="events_plugin_ingestion",
        num_partitions=64,
        replication_factor=3,
        topic_configs={"retention.ms": 3 * 24 * 60 * 60 * 1000},
    ),
    NewTopic(
        name="healthcheck", num_partitions=64, replication_factor=3, topic_configs={"retention.ms": 24 * 60 * 60 * 1000}
    ),
    NewTopic(
        name="plugin_log_entries",
        num_partitions=64,
        replication_factor=3,
        topic_configs={"retention.ms": 24 * 60 * 60 * 1000},
    ),
    NewTopic(
        name="clickhouse_groups",
        num_partitions=32,
        replication_factor=3,
        topic_configs={"retention.ms": 24 * 60 * 60 * 1000},
    ),
    NewTopic(
        name="clickhouse_person",
        num_partitions=32,
        replication_factor=3,
        topic_configs={"retention.ms": 24 * 60 * 60 * 1000},
    ),
    NewTopic(
        name="clickhouse_person_distinct_id",
        num_partitions=32,
        replication_factor=3,
        topic_configs={"retention.ms": 24 * 60 * 60 * 1000},
    ),
    NewTopic(
        name="clickhouse_session_recording_events",
        num_partitions=32,
        replication_factor=3,
        topic_configs={"retention.ms": 24 * 60 * 60 * 1000},
    ),
    NewTopic(
        name="events_dead_letter_queue",
        num_partitions=32,
        replication_factor=3,
        topic_configs={"retention.ms": 24 * 60 * 60 * 1000},
    ),
]
```

**Comment by Twixes** [comment]
Isn't this done now?
