### ISSUE TITLE
"Configuration error" warning routinely appears

### ISSUE THREAD

**Issue by prawnsalad** [PostHog/posthog#1010]
**Describe the bug**
Very often as I'm browsing stats I see in red a "Configuration Error" warning in the top right of the UI. Clicking it shows a warning dialog that includes "We can't seem to reach your worker".

**To Reproduce**
1. 
2. 
3. 

**Expected behavior**
Not to show an error

**Screenshots**

**Hosted or self hosted?:**
Self hosted, 1.8.0

**Additional context**
I have a feeling it may be due to performance issues? This instance tracks ~745k events daily. Although system load is nowhere to be a concern.

**Comment by jb33k** [comment]
I'm having this issue now with 1.12.0 with "official" docker-compose setup. I don't see any errors in docker logs, so no idea what's going on. If I restart the docker `web` service, the error disappears.

**Comment by yakkomajuri** [comment]
I'm reopening this. @jb33k reported this issue, a user on Slack did as well, and I've encountered it on my personal PostHog instance.

**Comment by yakkomajuri** [comment]
Closing in favor of #1523
