### ISSUE TITLE
Allow collapsing side nav sections

### ISSUE THREAD

**Issue by macobo** [PostHog/posthog#10114]
## Is your feature request related to a problem?

This scroll bar is quite ugly

![image](https://user-images.githubusercontent.com/148820/171610583-fec57f46-ffad-42b2-97ca-e142b21024cd.png)

## Describe the solution you'd like

Allow collapsing different sections on the side nav and remember that decision

## Describe alternatives you've considered

Allow hiding individual elements on the navbar behind a burger-like menu

## Additional context

cc @clarkus @lottiecoxon for app design thinking.

**Comment by clarkus** [comment]
I think this could be a more common scenario longer time depending on how Apps are integrated to the sidebar, but given the standard list of project navigation features (everything you have minus the apps section and the web performance feature, which is somewhat of an app) this navigation should fit in our most common viewport sizes without scrolling. The addition of headers to the nav sections also exacerbates the problem a bit... dropping those or finding other ways to aggregating could help mitigate the risk of this happening. 

I'll keep an eye on this one, but not sure we need to solve for it right now. I do think we should consider this as part of the apps work.
