### ISSUE TITLE
Show the current version in the web UI

### ISSUE THREAD

**Issue by prawnsalad** [PostHog/posthog#1011]
**Is your feature request related to a problem? Please describe.**
When reporting bugs or feature enhancements, I often forget what version I am running after a drink.

**Describe the solution you'd like**
Display the current version in the UI under an about dialog or at least in a "You are currently running..." message in the "PostHog up-to-date" dialog.

**Describe alternatives you've considered**

**Additional context**

***Thank*** you for your feature request - we love each and every one!

**Comment by timgl** [comment]
love it! PR raised
