### ISSUE TITLE
Enrich posthog-node captured events with feature flag states

### ISSUE THREAD

**Issue by kefranabg** [PostHog/posthog#10112]
## Is your feature request related to a problem?

It seems that captured events from server libraries (posthog-node for instance) does not contain user feature flag states properties, like it does with client libraries ($active_feature_flags or $feature/my-feature-name).

## Describe the solution you'd like

Enrich by default captured events from posthog-node with feature flag state properties

**Comment by jurajmajerik** [comment]
Hey @kefranabg, we now support this when the local evaluation is enabled. More here: https://posthog.com/docs/experiments/adding-experiment-code#step-2-server-side-only-add-the-feature-flag-to-your-events
