### ISSUE TITLE
Wild card event in event selectors

### ISSUE THREAD

**Issue by guillaume-chech** [PostHog/posthog#10125]
## Is your feature request related to a problem?

We’re coming from Mixpanel and this Any Event wild card is very handy in multiple situation :
Computing WAU/MAU and compare app vs web since Web and App event are not necessarily the same
Checking App Version release % 
Not having to maintain a long action list , especially when new app versions introduce new events.

## Describe the solution you'd like
We'd like to be able to use a wildcard event in the event selector that would select any event. 

<img width="698" alt="Screenshot 2022-06-02 at 17 55 40" src="https://user-images.githubusercontent.com/24913696/171672310-9728dcfd-031d-4869-b7a4-5843c5abc83e.png">

## Describe alternatives you've considered

We've considered building an action that would contain all events but that would require to add any new event to it, which is not really something that scales well.

**Comment by clarkus** [comment]
Related: https://github.com/PostHog/posthog/issues/4332
