### ISSUE TITLE
Cohort filtering shows Enter value input for is (not) set filters

### ISSUE THREAD

**Issue by macobo** [PostHog/posthog#10131]
## Bug description

"Enter value" input should be hidden for is_set/is_not_set filters

![image](https://user-images.githubusercontent.com/148820/171817062-38c0ed88-7a1c-44cd-9c5e-0bcc7650551c.png)

## How to reproduce

1. Go to cohorts
2. Edit a cohort
3. Set $property is not set
4. See "enter value" input

## Environment

- [x] PostHog Cloud
- [ ] self-hosted PostHog (ClickHouse-based), version/commit: _please provide_
- [ ] self-hosted PostHog (Postgres-based, legacy), version/commit: _please provide_

## Additional context

cc @EDsCODE @neilkakkar @alexkim205

**Comment by alexkim205** [comment]
https://github.com/PostHog/posthog/pull/10331
