### ISSUE TITLE
Persist custom column settings (per user)

### ISSUE THREAD

**Issue by marcushyett-ph** [PostHog/posthog#10143]
## Is your feature request related to a problem?

When I set custom columns in the live events tables and then leave PostHog these custom columns are not present when I come back

## Describe the solution you'd like
I would like my personal custom columns to be consistent every time I use the live events table

## Describe alternatives you've considered
Setting custom columns every time I use live events, takes quite a while

**Comment by mariusandra** [comment]
Related: https://github.com/PostHog/posthog/issues/10138

**Comment by clarkus** [comment]
Should this also extend to some filter settings? As an example, if I want to change the default sorting for a list view, should that persist? Are there any other filter options that might be applicable?

**Comment by kappa90** [comment]
This is how Notion does it for filters / sorting:

![image](https://user-images.githubusercontent.com/7335343/172568525-50bb8888-a8aa-4d73-856b-e6be9f8b9a9e.png)

If a new setting has been added, but not saved as a default, a small orange dot appears next to the unsaved setting, and there's a button to `Save for everyone`.

The current UX makes it a bit difficult to distinguish between a `Save` and `Save for everyone`. Maybe we can default to store the configuration for the team when hitting `Save`?

**Comment by clarkus** [comment]
This issue and the related issue https://github.com/PostHog/posthog/issues/10138 overlap quite a bit. The core difference is the scope of the changes being persisted. I think we have more to consider when saving the configuration for all users. 

In the case of live events, we use a modal to facilitate the configuration. In this modal we have a "reset to default" action. The scenario for applying a configuration for all users is a lot like saving a new default. It makes sense that a user might want to customize columns for themselves, or change them temporarily for a specific scenario they're trying to understand. Which users should be able to set the defaults for a table for the rest of the project? When do those defaults override what a user has already set?

Here's a [quick idea](https://www.figma.com/file/gQBj9YnNgD8YW4nBwCVLZf/PostHog-App?node-id=11161%3A49783):

This stacks the column configuration lists to make it easier to drag and drop to reorder items. The biggest change is for admin users (or any user with rights to set project defaults) - a checkbox that will set the configuration as the default for all users. 

When a column is selected, it moves up into the "visible columns" section. From there a user could drag and drop to change the column order. Once satisfied with the changes, the user optionally set as the default for all project members. When a user hits save without setting the checkbox, it would only apply those changes for that user. Any changes made would persist across sessions. 

<img width="550" alt="Screen Shot 2022-06-08 at 2 06 44 PM" src="https://user-images.githubusercontent.com/254612/172717175-a80469e3-d806-4b56-a7fe-97136eacd708.png">

Thoughts on this approach? It would let a user customize the columns for themselves, but also enable admin users to set project level defaults.

**Comment by kappa90** [comment]
Makes sense. The only thing I'm not convinced about is vertically stacking the two lists. I imagine somebody could start selecting twenty columns and it could get a bit difficult to scroll and drag and drop, considering it would be two different scrollbars one of top of the other, while keeping them stacked horizontally like it is right now makes it somewhat easier?

![image](https://user-images.githubusercontent.com/7335343/172802136-a0a9fd59-55ce-4276-9288-b966c4afb671.png)

I'm working on it right now, I'll test both configurations (horizontal - vertical).

**Comment by clarkus** [comment]
> Makes sense. The only thing I'm not convinced about is vertically stacking the two lists. I imagine somebody could start selecting twenty columns and it could get a bit difficult to scroll and drag and drop, considering it would be two different scrollbars one of top of the other, while keeping them stacked horizontally like it is right now makes it somewhat easier?

It's a single list with groups for each section. So you'd only be seeing a single scroll bar. If the item is checked, it's in the visible group and can be reordered to adjust the sequence of columns. If unchecked, it uses the default sort order for the group of available columns. Not critical, but it would make this modal a bit more robust in terms of width and viewport sizes.

**Comment by mariusandra** [comment]
Unfortunately that won't work. We could (and do) have thousands of events in the first list. Needing to scroll to the end of that to see your selected list is not that practical. Plus the way the sorting would affect all lists and interfere with the ordering is going to be messy... :)
