### ISSUE TITLE
Funnel Property Filters usage is confusing

### ISSUE THREAD

**Issue by neilkakkar** [PostHog/posthog#10151]
## Bug description

On a funnel:

<img width="480" alt="image" src="https://user-images.githubusercontent.com/7115141/172193167-61aee00d-2333-4e64-b497-d8fdf64786d4.png">

We have two places to filter things: On the step, and in the filter group.

These mean different things, but it's not quite clear when seeing this filter for the first time.

For example, consider the event property called `important`, and events like so:

| event | properties | person |
| ---- | ---- | ---- |
| sign up | - | 'Neo' |
| paid | `{important: true}` | 'Neo' |
| sign up | - | 'Matrix' |
| paid | `{important: false}` | 'Matrix' |

When you filter step 1 by important=true, you get an empty funnel.
When you filter step 2 by important=true, you get a funnel with one person (the first person, i.e Neo)

When you have a global filter group for important=true, you get an empty funnel as well, because it removes all events without the property, so what remains is:

| event | properties | person |
| ---- | ---- | ---- |
| paid | `{important: true}` | 'Neo' |

---

With person-on-events, this changes further to apply to person properties as well. **This is 

What's a good way to get this information across?

(cc: @lottiecoxon @clarkus )

**Comment by clarkus** [comment]
Historically, the filters that are distinct from the query steps are applied to all steps. Some people refer to them internally as "global" filters. It's just a way to specify a filter for every graph series / step without having to apply them manually on each step. Inline filters are always specific to that step or series, and don't apply to other steps. So the main difference is scope. 

The related issue specifically mentions property attribution - is that part of the problem to explore here, too? It might be valuable to get a quick working session together to figure out next steps and clarify goals. If I'm understanding this correctly, inline step filters would automatically be scoped to that step. Global filters and breakdowns are where property attribution becomes more of a concern. Thoughts?

**Comment by neilkakkar** [comment]
> So the main difference is scope.
Agree!

I realise now that I didn't finish the last line in the above^. Apologies. This isn't so much to do with attribution, but another incoming breaking change.

Person properties will be point in time, instead of global, like they are right now.

So, earlier, there was no difference between a global or step person property filter. This is changing to be the exact same semantics as for event properties: The person property filter is valid on the step only if the property exists at that time.

This makes the scope difference even more stark, as people think of person properties as a property of the person, not the event.

---

>  It might be valuable to get a quick working session together to figure out next steps and clarify goals.

Happy to!
