### ISSUE TITLE
Bug: Several official apps not 'Managed by PostHog'

### ISSUE THREAD

**Issue by joethreepwood** [PostHog/posthog#10167]
## Bug description

I might be wrong on this, but I always thought 'Managed by PostHog' meant that we maintain the app. I'd also assume that we manage any official apps, since we made them. As a design nit though, if this is incorrect then the actual meaning of this tag is never explained in the product (same with Community vs. Official). It's a tiny issue, but tagging @clarkus and @lottiecoxon  just for reference. 

The heartbeat app, which is definitely an official app made by @Twixes @tiina303 and @marcushyett-ph isn't listed as 'Managed by PostHog' in the in-product app library. This seems like a mistake. 

Other official apps not 'Managed by PostHog':

- Heartbeat
- Replicator
- Hello World

## How to reproduce

1.
2.
3.

## Environment

- [ ] PostHog Cloud
- [ ] self-hosted PostHog (ClickHouse-based), version/commit: _please provide_
- [ ] self-hosted PostHog (Postgres-based, legacy), version/commit: _please provide_

**Comment by Twixes** [comment]
Just to clarify, "Managed by PostHog" means that the app is available to all Cloud users, so it has to be at least approved by us– but not necessarily built or maintained by us.

**Comment by joethreepwood** [comment]
Thanks @Twixes -- In that case, I think that probably needs to be clearer. There's currently no way to find out who is responsible for maintaining any of the apps. 

Should I assume that we maintain the Official apps, while Community ones are maintained by the community?

**Comment by marcushyett-ph** [comment]
Should I assume that we maintain the Official apps, while Community ones are maintained by the community?

This feels like a logical assumption - but I think I didn't necessarily stick to this logic when adding plugins to: https://github.com/PostHog/integrations-repository/blob/main/plugins.json

I can take a look through a little later in the week and try and make what we currently have accurate to that definition.

**Comment by tiina303** [comment]
I propose we change "Managed by PostHog" & "Official apps" to "Verified by PostHog" for 2 reasons:

1. Like mentioned earlier it enables the plugin on cloud, but on self-hosted the goal here is to know which plugins you can trust vs which one's it could be a good idea to read the code first.
2. let's not discourage folks to put up fixes for the plugins that are "official" or "managed by posthog" (though getting lots of PRs to review some of which bad quality could be problematic)
