### ISSUE TITLE
Document `onSnapshot` going away when releasing recordings-on-s3

### ISSUE THREAD

**Issue by macobo** [PostHog/posthog#10168]
## Is your feature request related to a problem?

A side-effect of plugin server being split into two is that _on cloud_ currently onSnapshot plugin events aren't being called.

## Describe the solution you'd like

Deprecate onSnapshot. This was mainly used to back up recording data to a different storage and wasn't used on cloud. Note that this overlaps with #2142.

Once #2142 is removed mention onSnapshot removal in release notes.

## Additional context

cc @pauldambra @yakkomajuri

**Comment by yakkomajuri** [comment]
Additional note that no plugins on Cloud were using `onSnapshot` anyway

**Comment by yakkomajuri** [comment]
https://github.com/PostHog/posthog.com/pull/3543
