### ISSUE TITLE
We fire off way too many queries in insights

### ISSUE THREAD

**Issue by timgl** [PostHog/posthog#10185]
## In what situation are you experiencing subpar performance?

As a high volume user, every time I click "Add filter group", "add filter", "add graph series", or I look at a dashboard, we fire off a bunch of queries which are still running by the time I am running the query I _actually_ want to see, which might cause my queries to fail.

## How to reproduce

1. Click click "Add filter group", "add filter", "add graph series" or visit a dashboard, watch lots of queries happen
2.
3.

## Environment

- [ ] PostHog Cloud
- [ ] self-hosted PostHog, version/commit: _please provide_

**Comment by EDsCODE** [comment]
Remove repeat query when filter is added: https://github.com/PostHog/posthog/pull/10223

Some follow on steps:
- Remove repeat query when a new series is added
- Handle each trend series separately so that an entire new query isn't dispatched after every single change
     - This solution has a few gotchas
          - Formulas
          - How to invalidate cache per series. The difference in calculation times between them could be large
- Continue #9353

**Comment by clarkus** [comment]
Noticed some regressions related to this change. The core problem in the latest workflow is that we’re not prompting to pick an event, just appending the empty step. Ideally we’d show the taxonomic filter immediately with the event input focused. Right now you have to click to add, then click again to begin selecting, then click again to select. We can remove that click to trigger the taxonomic picker if we just trigger it immediately on step add. The placeholder value for the empty step is also inaccurate - we're not prompting a user to pick a filter, but to select an event. More context in [slack](https://posthog.slack.com/archives/C02E3BKC78F/p1655828456086049)

**Comment by EDsCODE** [comment]
Good points. Will add
