### ISSUE TITLE
New Cohort button capitalization

### ISSUE THREAD

**Issue by DannyBen** [PostHog/posthog#1018]
The "new cohort" button seems to be the only button not properly capitalized.

Other similar buttons - such as **New Funnel** are capitalized.

**Screenshots**

![image](https://user-images.githubusercontent.com/2405099/84673243-1d1eba00-af32-11ea-84cb-b480f98ee362.png)

**Hosted or self hosted?:**

- Self-hosted, using the Heroku one click install
- Version 1.8.0

**Comment by EDsCODE** [comment]
Thanks for noting this! Should be closed by #1019
