### ISSUE TITLE
Public stats page

### ISSUE THREAD

**Issue by kasbah** [PostHog/posthog#1020]
**Is your feature request related to a problem? Please describe.**

We are an open source website run by volunteers (https://kitspace.org). We'd like to make our page views and other anonymous stats public. 

**Describe the solution you'd like**

A public page where people can see how many visitors there are, maybe a graph over time, what pages are the most popular, maybe also what countries and screen sizes etc.

**Describe alternatives you've considered**
- [simpleanalytics.com](https://simpleanalytics.com/simpleanalytics.com) (great UI but too expensive, not self-hostable)
- https://goatcounter.com (the UI is too busy)
- https://www.privalytics.io (signups are closed? code is on github but not set up for self-hosting, no docs at all)

**Comment by timgl** [comment]
I love this idea! We already have a TV mode in the dashboard, so we could use that combined with a token (stored against the Dashboard model) to have a publicly available link.

**Comment by kasbah** [comment]
Sound great, haven't had a chance to look at the TV mode so maybe this already does this, but one important aspect is to not have any personally identifiable info in this view, since it's going to be public.

**Comment by timgl** [comment]
At the moment you need to be logged in to use the TV mode so that won't work.

In terms of PPI, we'll only open up the exact data required to show the dashboard, so as long as you're not putting email addresses in a table in the dashboard, it shouldn't be a problem!

@EDsCODE Something to think about with the caching stuff you're working on, this seems related.

**Comment by kasbah** [comment]
Yes, no, I meant like IP address, location etc. of site visitors shouldn't be shown in the stats page.

**Comment by timgl** [comment]
Yep totally, it's up to you what you put in the dashboard :)

**Comment by timgl** [comment]
@kasbah Have you had a chance to try shared dashboards out yet? Any feedback for us?

**Comment by kasbah** [comment]
Not yet, I needed a solution quickly and used [Plausible for Kitspace](https://plausible.io/kitspace.org/) which I am quite happy with. When I want to expand the analytics data we collect I'll give Posthog another go.
