### ISSUE TITLE
Use `version` column for collapsing clickhouse `persons` table

### ISSUE THREAD

**Issue by macobo** [PostHog/posthog#10208]
## Is your feature request related to a problem?

For https://github.com/PostHog/posthog/issues/10058
In https://github.com/PostHog/posthog/pull/10117, @tiina303 exposed the version column to clickhouse `persons` table.

Using this for collapsing instead of `_timestamp` should help solve issues with user creation/update races which _timestamp cannot handle.

## Describe the solution you'd like

We need to handle deletions (done in https://github.com/PostHog/posthog/pull/10207)
Currently there's a bunch of 0 versions there as we haven't been setting the version historically.  This would lead to incorrect collapsing if we just swap out the engine. This is true for both cloud and self-hosted. Since we need to think of the latter we need an async migration here.

## Additional context

cc @Twixes @yakkomajuri

**Comment by tiina303** [comment]
updated the description

**Comment by tiina303** [comment]
Proposed plan (from brainstorming with @macobo):
1. verify that all code works fine with versions (e.g. https://github.com/PostHog/posthog/pull/10207#discussion_r893455054)
2. switch to version collapsing for new installs (have _version [here](https://github.com/PostHog/posthog/blob/26435cb70d5def0fa4c007d10dbdff0da09b7875/ee/clickhouse/sql/person.py#L31), note though it's used in the 0004 migration, so would need to keep that one as using _timestamp)
3. async migration for existing installs

The async migration:
1. create a new table with the right engine
2. start reading from kafka to both tables (can we do that, e.g. different consumer group)?
4. write all persons from postgres to the new table
5. swap the new and old tables
6. stop the special consumer
7. nuke the old table

**Comment by macobo** [comment]
The plan outlined ^ has some issues:

> 2. start reading from kafka to both tables (can we do that, e.g. different consumer group)?

> 5. stop the special consumer

If you use a different consumer group name and then later nuke it then you can end up with missed messages in the new table if original consumer is ahead.

I'll look into if we can solve this by using multiple mv tables instead.

> 3. write all persons from postgres to the new table

A more efficient approach would likely be to:
- Start ingesting into the new table along with the old
- Copy all persons from original table
- Copy over from pg those people with version < version in pg

There's an annoying gotcha here in that versions start out at zero, which causes problems with making this resumable.

> 4. swap the new and old tables

This is more of a nitpick, but renaming tables with attached mv/kafka tables is prone to fail. We should rename the main table and drop/create new kafka/mv tables.

## Other gotchas
### Making this resumable

The slow part of this migration will be copying persons, which may take days-weeks. We'll need to do something clever with the task and progress reporting to avoid restarting everything every time there's a deploy.

Example idea. In a loop:
- we grab min(uuid) from ch which needs copying >= uuid saved in redis
- Update a batch of persons with uuid >= min(uuid)
- Save the uuid into redis

This takes advantage of uuids being ever-incrementing. Progress reporting can then make use of this same process.


### Optimize

We probably want to issue an OPTIMIZE TABLE FINAL at the very end to force collapsing of data. This isn't strictly needed, but makes querying more efficient.

### Cloud considerations

Not sure whether replication lag can cause us issues on our cloud setup, but it might be wise to set up this async migration to hit a single, stable clickhouse host.

**Comment by macobo** [comment]
Note: Picking up building the async migration. However we should fix other version-related bugs before merging that (e.g. https://github.com/PostHog/posthog/issues/10236)

**Comment by tiina303** [comment]
> 1. verify that all code works fine with versions

reviewed all the code and we should be good after Karl's already approved PRs land, specifically we only use `generateKafkaPersonUpdateMessage` to generate message to the person queue & there are 3 locations for that:
1. create - Karl's PR will make sure we always write the version to be 0 (could have been null before)
2. update - this one writes versions already
3. delete - create or update could write afterwards, but using version +100 here (Karl's PR) makes us safe for late arriving messages. We only delete persons, when we merge them, so this person should be deleted forever (we wouldn't handle recreations well & we don't reuse uuids so this is all fine too)

**Comment by macobo** [comment]
This has been rolled out on cloud, but:
1. The migration is gated for self-hosted users.
2. INSERT INTO failed on cloud after successfully finishing (?)
3. Backfill did not properly start as part of the async migration, so existing data is still out of sync.

These issues need to be resolved before we can close this issue.

**Comment by tiina303** [comment]
Should we revert https://github.com/PostHog/posthog/pull/10403 given how the version collapsing would not do the right thing if we have many of `version=0`?

**Comment by macobo** [comment]
I don't think so but we can discuss next week.

**Comment by macobo** [comment]
This is more or less done - the backfill is in a stuck position on cloud, but this will be released along with 1.38.0 and new data coming in is fixed.
