### ISSUE TITLE
Feature Request: View filters on shared insights

### ISSUE THREAD

**Issue by joethreepwood** [PostHog/posthog#10211]
## Is your feature request related to a problem?

Users want to share insights with others. At least some of those shares will be to validate an insight is correctly setup and at least some of the those users who receive a shared insight will want to validate what they are looking at. 

Example: I just shared [this insight](https://posthog.slack.com/archives/C01RJ7T212S/p1654770263334669) and I wasn't 100% sure it meant what I thought it did. I was hoping others would take a peek. @andyvan-ph  didn't think it was configured correctly (because he can't see the filters), until he'd read the description (which most people don't add). 

Making sure an insight is setup correctly means looking at the filters. But currently, if I send a saved insight to someone, they can't see the filters without hitting `Edit`. But I may not want them to do that and its an extra, fiddly process for them.

## Describe the solution you'd like

A way to see the filters applied to a series, without having to edit the insight.

Off-hand idea: Floating this in the detailed results, or making it an option when viewing the legend.

**Comment by clarkus** [comment]
It doesn't exist on the insight detail yet, but insight cards on dashboards and list views have a "view details" option that will show a read-only translation of the insight definition. It's a bit buried but it is there outside an editing context.
