### ISSUE TITLE
Don't show blank description text when not editable

### ISSUE THREAD

**Issue by corywatilo** [PostHog/posthog#10218]
In the [Data management](https://app.posthog.com/data-management/events) section, it lists out "_Add a description for this property_" when there's no description, but it's not editable, so it doesn't really make sense to show that string of text there.

<img width="887" alt="image" src="https://user-images.githubusercontent.com/154479/172905250-1c231ce2-a881-4de0-915d-34b221878e12.png">

**Comment by clarkus** [comment]
Per [design](https://www.figma.com/file/gQBj9YnNgD8YW4nBwCVLZf/PostHog-App?node-id=10788%3A48581), it's supposed to say "_There is no description for this property_". There isn't inline editing here, so agree it should be changed.

**Comment by alexkim205** [comment]
We changed the copy recently from "There is no description for this property" to "Add a description for this property" to incentivize people to use the new data management feature more. However, agreed that it doesnt make sense to have the latter if the user cannot edit this (in the case they dont have an ee license). Would it make sense to show "There is no description for this property" if the description isn't editable?

**Comment by clarkus** [comment]
This feels like somewhat of an upsell case. If users can't edit descriptions, there might not be much value in showing them. If we're trying to move folks over to a more capable license that supports editing of subscriptions, I think a more purposeful and clear upsell state would be more effective. All that said, I think a value of "there is no description for this property" is going to work best for most cases. Showing affordance for editing (depending on context) is another way to incentivize folks to edit (inline edit icons, edit buttons, etc). We're also using hover cards that have clear edit actions now - that might be a place to incentivize edits.
