### ISSUE TITLE
Make it easier to create new insights (that aren't trends)

### ISSUE THREAD

**Issue by corywatilo** [PostHog/posthog#10219]
Knowing PostHog has 6 different insight modules (trends, funnels, retention, paths, stickiness, lifecycle), I was confused when I clicked the `+` button in the nav to create a new insight, then had trouble locating how to create a new funnel. (The tab bar feels non-obvious/sort of buried within the trends view?)

Maybe the same dropdown off the `+` button would be helpful, like exists in the `/insights` page on the right side?

<img width="632" alt="image" src="https://user-images.githubusercontent.com/154479/172906031-123abeaf-6ea1-4bbf-86c4-aa59d9d53d0f.png">

**Comment by clarkus** [comment]
I don't think this is actually resolved. The issue @corywatilo described was more about having the intermediate choice of insight type when creating an insight via the add action in the project navigation. The core fix would be hanging that same select menu off the plus icon / add action in the project navigation.
