### ISSUE TITLE
Clean up task for authorized domains / urls

### ISSUE THREAD

**Issue by clarkus** [PostHog/posthog#10229]
## Is your feature request related to a problem?

We show the list of authorized domains / URLs places currently:

- Project settings under the header "Authorized URLs"
- Toolbar settings (this is the only thing on this page) under the header "Toolbar"

The project settings contain extra context to set context and help a user understand the feature and how to use it. This content is missing from the toolbar settings page entirely. 

This area of settings is redundant with the toolbar settings, but each are still presented in different ways with different context and action labels. 

**Toolbar settings**
<img width="978" alt="Screen Shot 2022-06-09 at 3 43 50 PM" src="https://user-images.githubusercontent.com/254612/172957442-08194b3f-b009-4a15-9a67-2f07dcdfed4e.png">

**Project settings**
<img width="956" alt="Screen Shot 2022-06-09 at 3 44 01 PM" src="https://user-images.githubusercontent.com/254612/172957493-4bf9c7a8-0d2a-4fce-907c-9e75f78376c2.png">

## Describe the solution you'd like

- Do we need both of these areas? Can we consolidate into a single spot to managed authorized domains? These settings also affect recordings, so you could argue that consolidating into settings would be the more useful place. The benefit of the "toolbar" navigation item is discoverability. While this is good, I'm not sure it's worth replicating the feature in two places. If we are going to keep both positions, we should align the page content and button labels so users will trust this is working the same way in both spots. 

## Describe alternatives you've considered

Nothing yet

## Additional context

Related issues:
- https://github.com/PostHog/posthog/issues/9046
- https://github.com/PostHog/posthog/issues/10114

**Comment by liyiy** [comment]
I think this is a good idea! There's also another spot where adding authorized domain occurs which is when you go to create a new action and if you do "inspect an element on your site" (this is maybe broken rn?). We'll probably also want to get rid of the Toolbar configuration option on the side menu options since setting up authorized domains seems to be the only thing it's there for?

**Comment by clarkus** [comment]
@corywatilo filed an issue for the action-related interface at https://github.com/PostHog/posthog/issues/10260.

**Comment by clarkus** [comment]
I think we should drop the toolbar configuration unless there's a problem it's solving separate from the project settings. I will ask around and see if there is any reason to keep it.

**Comment by mariusandra** [comment]
> The benefit of the "toolbar" navigation item is discoverability. While this is good, I'm not sure it's worth replicating the feature in two places.

Discoverability is one, but not the only reason why we put the button in the sidebar. The initial plan was to launch the toolbar automatically when you visit your own site, but that's practically not possible/feasible (issues around third party cookies).

Thus, you need to click a "launch" button next to a domain you want to open it on. It's not intuitive to do that under settings.

**Comment by clarkus** [comment]
> Thus, you need to click a "launch" button next to a domain you want to open it on. It's not intuitive to do that under settings.

Makes sense. I don't think replicating the feature is worth it. I'll work on another solution that can solve for the specific problem of discoverability and launching a contextual toolbar based on the domain. Thanks for the context!

**Comment by clarkus** [comment]
Other notable areas of overlap:
- Organization settings for authentication domains
- Session recordings

**Comment by rcmarron** [comment]
A bit of related context on the recordings side:
* Users often write in about only getting recordings on a specific page, and more often than not it's because they added an authorized URL, and didn't realize it would impact recordings. I think splitting the setting into 2 would make sense for this case - "Authorized Domains for Recordings" and "Authorized URLS for Toolbar".
* Not all users realize that `www.example.com` is a different domain from `example.com` or `app.example.com`. As a result, they add the first one to the list and are confused when the other domains don't work. We support domain wildcarding, but it's kind of confusing.
* For recordings specifically, the setting is actually "Authorized Domains" even though it says "Authorized URLs". We parse out the domain, and only use that. This is not conveyed to customers very well.

**Comment by clarkus** [comment]
What about suggested domains? Are those only applicable to the toolbar, or should they show up for recordings, too?

**Comment by clarkus** [comment]
I have an updated solution for this in [figma](https://www.figma.com/file/gQBj9YnNgD8YW4nBwCVLZf/PostHog-App?node-id=11466%3A49743). This covers a lot of changes to project settings, but only a portion are really in scope for this issue. This solution is composed of three prominent changes:

- Separate the concepts of authorized domains/urls for recordings and the toolbar. They work in different ways and are covering different use cases. Tactically this means we'll introduce a separate section for recording domains "authorized domains for recordings". Domains in this context are not able to be launched in the toolbar. Basically what @rcmarron said. 
- Move the toolbar settings from the project settings to a dedicated toolbar settings page. This already exists. We're just removing the redundant portions of the project settings.
- Add a menu for quickly launching the authorized toolbar URLs. This would work much like the pinned dashboard menu we have today. 

<img width="541" alt="Screen Shot 2022-06-17 at 12 50 39 PM" src="https://user-images.githubusercontent.com/254612/174392423-a27f1e81-7110-4d0e-81ba-d85bc11986a9.png">

The rest of the changes shown are a reorganization of all our project settings into meaningful groups. This portion is not quite ready for work, but feel free to leave feedback if you have any. 

Thoughts on the three prominent changes described above?

**Comment by pauldambra** [comment]
I love the toolbar launcher so much I added it :)

**Comment by pauldambra** [comment]
other than removing that this is in two places it's 99% done
