### ISSUE TITLE
Follow up for caching functionality

### ISSUE THREAD

**Issue by EDsCODE** [PostHog/posthog#1022]
- [x] Right now when the worker starts refreshing process for dashboard items, it will clear out the previous key and begin the refresh. For long running queries this causes the infinite spinner to occur and then fail to return within 30 seconds (like the errors we had previously)
- [x] When users update a dashboard item, the previous cached item stays within the refresh queue even though it's never used again

- [ ] When users are creating an item to add to the dashboard, we should transfer the cached results to the dashboard cache or start the calculation process early rather than loading when a user visits the dashboard page

**Describe the solution you'd like**
1. Don't delete until the refresh returns
2. One solution is to track the last access on this item and when the worker is updating, if it's been over some amount of time, clear the cached item
3. make the transfer

***Thank*** you for your feature request - we love each and every one!

**Comment by Twixes** [comment]
Closing due to staleness.
