### ISSUE TITLE
Incorrect column alignment on cohorts table

### ISSUE THREAD

**Issue by clarkus** [PostHog/posthog#10228]
## Bug description

The cohorts table contains a "users in cohort" column that contains numeric values. The column is left-aligned which makes comparing values very difficult. 

The column should be right aligned to make it easier to compare numeric values.  

## How to reproduce

1. Go to cohorts
2. Note the table column "users in cohort" is left aligned

**Comment by jaysoni-ash42** [comment]
@clarkus  is this issue still active? i want to
 work on this issue.
