### ISSUE TITLE
Persons are deleted incorrectly in person endpoint

### ISSUE THREAD

**Issue by macobo** [PostHog/posthog#10236]
## Bug description

In https://github.com/PostHog/posthog/pull/10117, @tiina303 added a version column to clickhouse person table. 

This column is not properly used when deleting persons in in persons API endpoint, check the code.

## How to reproduce

1.
2.
3.

## Environment

- [x] PostHog Cloud
- [ ] self-hosted PostHog (ClickHouse-based), version/commit: _please provide_
- [ ] self-hosted PostHog (Postgres-based, legacy), version/commit: _please provide_

## Additional context

Related: https://github.com/PostHog/posthog/issues/10208

This should probably be handled in plugin-server. How? Idk!

**Comment by yakkomajuri** [comment]
An extra component to this task:

https://github.com/PostHog/posthog/issues/10479
