### ISSUE TITLE
Integrity issue - PostgreSQL and ClickHouse out of sync

### ISSUE THREAD

**Issue by guidoiaquinti** [PostHog/posthog#10239]
## Bug description

PostHog uses two main databases: 

* PostgreSQL  

* ClickHouse

Some functionalities of PostHog rely on having a subset of data in sync between the two (e.g. person properties). We currently try to archive this by double writing to the two datastores directly in the app. Unfortunately, the datasets are far from being in sync as we use nothing like 2 phase commits that would rollback a transaction entirely if one of the write operation fails.

This data drift is creating issues at the application level and in the overall data integrity. I’m creating this issue to keep track of proposals to address the problem.

## Environment

- [X] PostHog Cloud

- [X] self-hosted PostHog (ClickHouse-based), version/commit: _please provide_

- [X] self-hosted PostHog (Postgres-based, legacy), version/commit: _please provide_

## Additional context

* https://github.com/PostHog/posthog/issues/10058

**Comment by guidoiaquinti** [comment]
My proposal is to implement a [Change Data Capture](https://rockset.com/blog/change-data-capture-what-it-is-and-how-to-use-it/#:~:text=What%20Is%20Change%20Data%20Capture,the%20systems%20stay%20in%20sync.) process (see as example the section _A Common CDC Architecture with Debezium_)

**Comment by tiina303** [comment]
This was potentially the cause of https://posthog.slack.com/archives/C0374DA782U/p1658758589681689
