### ISSUE TITLE
Expose and use `groups.version` column in clickhouse

### ISSUE THREAD

**Issue by macobo** [PostHog/posthog#10248]
## Is your feature request related to a problem?

In https://github.com/PostHog/posthog/pull/10117, @tiina303 exposed the version column to clickhouse persons table.

We have the same column for groups and we're keeping it in sync in postgres, but are not doing so for groups. Why not - who knows.

## Describe the solution you'd like

See https://github.com/PostHog/posthog/issues/10208

## Describe alternatives you've considered

Having more diverging code paths.

## Additional context

Related/possibly part of https://github.com/PostHog/posthog/issues/10208

We should really also keep groups in mind when planning these ingestion changes. :sweat_smile: 

cc @tiina303 @Twixes

**Comment by tiina303** [comment]
💯  just wanted to do persons first

**Comment by macobo** [comment]
Note we should be keeping these in sync _including_ planning for and migrating them together. Otherwise we just double our risk and work efforts.
