### ISSUE TITLE
Person Modal shows incorrect data when two filters on the same event is used

### ISSUE THREAD

**Issue by marcushyett-ph** [PostHog/posthog#10256]
## Bug description

When you create a trend with two lines, one of which is say $pageview with a filter of browser = chrome and the other is ALSO $pageview but a different filter.

If you click on any the line you get the same users in the persons modal, even if you switch the trend line toggle in the modal.

## How to reproduce

1. Create a new trend
2. Add a $pageview trendline, and another $pageview trendline with a subfilter
3. Click on any of the lines
4. Open the persons modal and switch between the trend lines in the persons modal

## Environment

- [x] PostHog Cloud
- [ ] self-hosted PostHog (ClickHouse-based), version/commit: _please provide_
- [ ] self-hosted PostHog (Postgres-based, legacy), version/commit: _please provide_

**Comment by EDsCODE** [comment]
In progress: https://github.com/PostHog/posthog/pull/10289
