### ISSUE TITLE
Stupid idea for sparking joy

### ISSUE THREAD

**Issue by corywatilo** [PostHog/posthog#10266]
Right now if a query is taking a while, the message updates and we see a different hog. This is great! But......

It could be fun to make the hog more contextual to the situation: Example, we know it's taking a while, so we could make the animation infer: "Hmm, this is taking longer than expected. We've brought in some additional resources." ← Where there's 2 or 3 more hogs, possibly bodybuilders. Or a couple utility trucks that show up, holding spindles of cables.

<img width="889" alt="image" src="https://user-images.githubusercontent.com/154479/173250938-a2dbfa91-8e1a-4398-80b2-bb3e235a55f3.png">

**Comment by lottiecoxon** [comment]
I love this - will add it to my background (yet great) to do list

**Comment by jaysoni-ash42** [comment]
@lottiecoxon  i want to work on this issue? is there a new design for the implementation?

**Comment by lottiecoxon** [comment]
@jaysoni-ash42 Hey! Unfortunately I haven't gotten round to prioritising this yet but when I do I will remember to loop you in!
