### ISSUE TITLE
Enhancement idea for trying to view a saved insight while signed in to a different account

### ISSUE THREAD

**Issue by corywatilo** [PostHog/posthog#10265]
Far from a main use case, but a nice quality of life enhancement...

## Problem

When you have access to multiple PostHog accounts, and click a link to view an insight for a _different_ account than the one you're currently signed into, here's what you see:

<img width="1600" alt="image" src="https://user-images.githubusercontent.com/154479/173250605-1b8657fb-5bba-4ea0-86f6-5ee1a3c70c1a.png">

1. "Insight not found"
2. Endless skeleton

## Possible solution

It might be nice to have a message display (in place of the "not found" toast) that says:

"Blah blah we couldn't find this insight. If you need to sign into a different account, [Sign out](#) and sign in with a different account.

**Comment by clarkus** [comment]
I think we just need an empty state. Not sure how forthcoming we can be with where the target insight resides. This might be a case for exposing project IDs in URLs to make it easier to link to stuff.
