### ISSUE TITLE
Buttons in "Create new action" modal getting clipped

### ISSUE THREAD

**Issue by corywatilo** [PostHog/posthog#10260]
Bonus points: the size of the search button up against a different size Add button could use some love

<img width="558" alt="image" src="https://user-images.githubusercontent.com/154479/173195699-bc09f94f-62d9-40c5-bd57-23cfe3e5f565.png">

**Comment by clarkus** [comment]
The same core issue is affecting authorized domain interfaces. https://github.com/PostHog/posthog/issues/9046

**Comment by charlesinto** [comment]
Hi @clarkus @corywatilo,  I tried to replicate this issue but it appears that there is already a change in UI

Before
<img width="603" alt="Screenshot 2022-08-30 at 13 42 58" src="https://user-images.githubusercontent.com/26615085/187439706-d14dcb6e-44b0-4949-9aaa-6fae73c6c7a5.png">

Current
<img width="567" alt="Screenshot 2022-08-30 at 13 44 22" src="https://user-images.githubusercontent.com/26615085/187439809-4330d81f-d6fd-461d-b6be-1cf181d24b6f.png">

**Comment by clarkus** [comment]
Confirmed this is still an issue for longer, more complex URLs. 

<img width="696" alt="Screen Shot 2022-08-30 at 11 25 23 AM" src="https://user-images.githubusercontent.com/254612/187514456-5ca50184-374f-4d39-b85b-5692c6b272b3.png">
