### ISSUE TITLE
Bug: Correlation Analysis details not closing UI element

### ISSUE THREAD

**Issue by joethreepwood** [PostHog/posthog#10275]
## Bug description

Then I click for detail on a correlation analysis result, this is what I see: 

<img width="1530" alt="Screenshot 2022-06-13 at 14 04 17" src="https://user-images.githubusercontent.com/84011561/173360233-4f00a952-6bba-4647-8d4e-9184497ce01a.png">

Blacking out the background and creating a pop-up I can understand, but leaving the 'View correlation details' box popped up and in-focus seems like a mistake. 

## How to reproduce

1.
2.
3.

## Environment

- [ ] PostHog Cloud
- [ ] self-hosted PostHog (ClickHouse-based), version/commit: _please provide_
- [ ] self-hosted PostHog (Postgres-based, legacy), version/commit: _please provide_

**Comment by clarkus** [comment]
This is definitely deviating from our other overlay patterns. The overlay should be semi-transparent, and the modal should be aligned to other modal instances. Here's a [redraw](https://www.figma.com/file/A9XRxeDm3ceikbenfTBGZl/Insights%2C-Dashboards%2C-%26-Project-Home?node-id=19%3A6867) that aligns the content to other modal examples. I removed the footer as it always adds up to 100%, so didn't feel like it was adding much. 

![correlation modal](https://user-images.githubusercontent.com/254612/186027951-ef7ea7b0-0985-4e5f-a44e-e468cb2dd080.png)

**Comment by AsiwajuDev** [comment]
@clarkus I picked up this issue and tried recreating the issue but no luck yet. Can you help by sharing the steps to recreate it?

**Comment by neilkakkar** [comment]
Go to a funnel -> add events -> scroll down to correlation table -> click three dots at the rightmost end of the table -> click 'view correlation details' -> see the above happen.

**Comment by AsiwajuDev** [comment]
@clarkus how do I get to locate a funnel

**Comment by neilkakkar** [comment]
Insights -> funnels

<img width="742" alt="image" src="https://user-images.githubusercontent.com/7115141/187221582-77fe4d43-c7fd-47b4-aeaf-121a0f19930a.png">

**Comment by AsiwajuDev** [comment]
@neilkakkar The experience is different for me on my side.
![Screenshot 2022-08-30 at 11 14 46](https://user-images.githubusercontent.com/17790578/187411728-a147efbb-8c30-4c54-bd5f-8f95ed33e996.png)

I see this on the insight page. I open one of the items, I have to click edit on the inner page and then navigate to the funnel tab but I do not see correlation table option

**Comment by neilkakkar** [comment]
Hey @AsiwajuDev , my bad, didn't realise this was an enterprise feature 😅 . I'd recommend switching to another issue. Something labelled good first issue is ideal: https://github.com/PostHog/posthog/issues?q=is%3Aopen+is%3Aissue+label%3A%22good+first+issue%22
