### ISSUE TITLE
Weird behavior when toggling funnel breakdown

### ISSUE THREAD

**Issue by corywatilo** [PostHog/posthog#10284]
When unchecking an item to breakdown a funnel, I'd expect to see the 3 (remaining) selected breakdowns to continue to show. Instead all columns for steps 2 and 3 disappear entirely.

![2022-06-13 11 19 42](https://user-images.githubusercontent.com/154479/173409345-24d729aa-ab33-4c33-8461-254084b7262c.gif)

**Comment by EDsCODE** [comment]
Weird. Do you have an exact link? I tried repro-ing locally and it works as expected

**Comment by corywatilo** [comment]
Yep, I just invited you to the account and [here's the above funnel](https://app.posthog.com/insights/gj0bQrGO). (Happens on both saved funnels in that account, actually.)
