### ISSUE TITLE
Bug: First/Last Seen not loading on properties

### ISSUE THREAD

**Issue by joethreepwood** [PostHog/posthog#10408]
## Bug description

Me: "Is this worth a bug report?"
Yakko: "Probably."

<img width="910" alt="Screenshot 2022-06-22 at 10 51 03" src="https://user-images.githubusercontent.com/84011561/174999983-5937739a-88f7-4ea1-aaf5-8fb9e10a8995.png">

No first/last seen data loading into property window, even though there are plenty of people attached to this property. 

## How to reproduce

1. Persons
2. Filter, JoinedAt
3. Profit!

## Environment

- [ ] PostHog Cloud
- [ ] self-hosted PostHog (ClickHouse-based), version/commit: _please provide_
- [ ] self-hosted PostHog (Postgres-based, legacy), version/commit: _please provide_

**Comment by pauldambra** [comment]
@joethreepwood short term I'm going to say that https://github.com/PostHog/posthog/pull/11677 closes this issue. Because we were showing fields we don't actually calculate as if they were missing

Longer term we should calculate them for properties too but let's not be misleading for now :)
