### ISSUE TITLE
First time event tracker app is generating undue load

### ISSUE THREAD

**Issue by macobo** [PostHog/posthog#10405]
## Is your feature request related to a problem?

From https://metabase.posthog.net/question/344-most-time-consuming-postgres-queries, it is visible that `storageSet` is one of the most time-consuming operations plugin-server does. It dwarfs e.g. fetching and updating persons 2x - this is too much.

This [query](https://metabase.posthog.net/question#eyJkYXRhc2V0X3F1ZXJ5Ijp7InR5cGUiOiJuYXRpdmUiLCJuYXRpdmUiOnsicXVlcnkiOiItLSBzZWxlY3QgY291bnQoKikgZnJvbSBwb3N0aG9nX3BsdWdpbnN0b3JhZ2Vcbi0tIHNlbGVjdCBwZ190b3RhbF9yZWxhdGlvbl9zaXplKCdwb3N0aG9nX3BsdWdpbnN0b3JhZ2UnKVxuXG53aXRoIHRvcF9wbHVnaW5zIGFzIChcbiAgICBzZWxlY3QgcGx1Z2luX2lkLCBjb3VudCgqKSBhcyByb3dzIGZyb20gcG9zdGhvZ19wbHVnaW5zdG9yYWdlIFxuICAgIGxlZnQgam9pbiBwb3N0aG9nX3BsdWdpbmNvbmZpZyBPTiAocG9zdGhvZ19wbHVnaW5jb25maWcuaWQgPSBwb3N0aG9nX3BsdWdpbnN0b3JhZ2UucGx1Z2luX2NvbmZpZ19pZClcbiAgICBncm91cCBieSBwbHVnaW5faWRcbiAgICBvcmRlciBieSByb3dzIGRlc2NcbilcbnNlbGVjdCAqIGZyb20gdG9wX3BsdWdpbnNcbmxlZnQgam9pbiBwb3N0aG9nX3BsdWdpbiBPTiAodG9wX3BsdWdpbnMucGx1Z2luX2lkID0gcG9zdGhvZ19wbHVnaW4uaWQpIiwidGVtcGxhdGUtdGFncyI6e319LCJkYXRhYmFzZSI6M30sImRpc3BsYXkiOiJ0YWJsZSIsInZpc3VhbGl6YXRpb25fc2V0dGluZ3MiOnt9fQ==) shows how many rows have been added per plugin - this probably correlates with this timing.

The two plugins that stand out are:
- First Time Event Tracker - https://github.com/PostHog/first-time-event-tracker
- First Event Today - https://github.com/PostHog/first-event-today

## Describe the solution you'd like

Spend less time in `storageSet` in these trackers.

## Additional context

Note that first time event tracker seems to be doing sets _every single event_ to create pseudo-session tracking.

The session tracking isn't being advertised in the plugin, doesn't use config.eventsToTrack and needs to update last seen timestamp every event. Not sure on the context of this @yakkomajuri and @marcushyett-ph but that seems like exactly that's the problem.

The functionality was added in https://github.com/PostHog/first-time-event-tracker/pull/2 but the pull request has no context on the why.

**Comment by macobo** [comment]
The functionality added in https://github.com/PostHog/first-time-event-tracker/pull/2 isn't being used at all by any user queries (ran this on cloud):

```python
ed = list(EventDefinition.objects.filter(name='session_started'))
[x for x in ed if x.query_usage_30_day]
=> []

pd = list(PropertyDefinition.objects.filter(name="is_first_event_in_session"))
[x for x in pd if x.query_usage_30_day]
=> []
```

Given this I feel safe reverting the change and upgrading cloud. https://github.com/PostHog/first-time-event-tracker/pull/6

Note that the mainline functionality of the plugin (is this the first event) is unaffected by the revert - it's only `session_started` and `is_first_event_in_session` behavior that's causing us issues and those are not documented under the plugin.

cc @marcushyett-ph and @yakkomajuri unless you have objections I'll revert + update the plugin on cloud later today.

**Comment by yakkomajuri** [comment]
Particularly given the impact (and also the investigation), let's revert.

Better to see if someone complains about this missing than keep incurring this cost.

**Comment by marcushyett-ph** [comment]
Yep lets scrap it for now but ensure we document it somewhere.

**Comment by neilkakkar** [comment]
This is actually being used by a few customers I came across in support hero, and I think the reason it doesn't show up in your query is because for the customer I'm thinking about, they have another plugin right after which camel cases all names, so the event being used in their insights is `SessionStarted` 

This change would destroy their workflow, so would be nice to warn people about this incoming change!

**Comment by yakkomajuri** [comment]
We can add a config option to disable this by default and enable this for that specific customer for now as we figure things out

**Comment by neilkakkar** [comment]
Sure that works. Will send details in slack

**Comment by macobo** [comment]
If we're disrupting the customers anyways, could we create a new plugin and improve the behavior from ground up (e.g. using a cache)?

This behavior does not belong in that plugin anyways.
