### ISSUE TITLE
Paginate people modal

### ISSUE THREAD

**Issue by EDsCODE** [PostHog/posthog#1041]
**Is your feature request related to a problem? Please describe.**
When you click on a datapoint on trends graph to see list of people, if there are over 100 results, you only get 100 and can't see the rest

**Describe the solution you'd like**
Paginate the data so you can scroll to more than 100 users

**Describe alternatives you've considered**
Show all but this is too slow and overwhelming to frontend

**Additional context**

***Thank*** you for your feature request - we love each and every one!

**Comment by timgl** [comment]
Done
