### ISSUE TITLE
Feature Request: Count of items in a filtered list

### ISSUE THREAD

**Issue by joethreepwood** [PostHog/posthog#10410]
## Is your feature request related to a problem?

It would be really handy to have a count of how many items there are in a list when filtering. This would be especially handy if I'm trying to figure out whether I can export a list straight from PostHog, or if I need to export via the API (because the number of entries is over 10,000). 

Example: I want a list of people who opted in to email, so I can then decide how I want to segment that list down for G2 review targeting. Creating a filter (`email_opt_in = true`) gives me a list of users. At the top of the page I have no information of how many Persons are in this filtered list. 

I can scroll to the bottom of the page, to see there are 100 people on the first page. But I have no idea how many pages there are. 

<img width="1155" alt="Screenshot 2022-06-22 at 11 28 23" src="https://user-images.githubusercontent.com/84011561/175007685-5425255a-d769-4d61-b42f-9086c2d7a242.png">

I can export this list, but the warning text of this prompt appears no matter the size of my list and is ambiguous in helping me decide if my list is over 10,000 users or not. 

<img width="506" alt="Screenshot 2022-06-22 at 11 28 57" src="https://user-images.githubusercontent.com/84011561/175007828-408a5c08-e78e-4b53-80dd-1b091149e820.png">

## Describe the solution you'd like

Either:

1. A count at the top of the page which shows how many entries are in a filtered list. 
2. An indication at the bottom of the table which tells me how many pages there are in this table. 
3. A better export warning prompt which tells me how many entries are in a list (`This list contains 10,001 users. To export more than 10,000 users, please use the API.`)

## Additional context

Tagging @clarkus and @lottiecoxon as it's a UI issue in part.

**Comment by clarkus** [comment]
I think this is a solid improvement. I think there might be technical constraints, but the general pattern I've been pushing for tables is to show the current result count per page, as well as the total result size. When filters are applied, the total result size should decrease, but the number of items per page would remain constant. 

<img width="310" alt="Screen Shot 2022-06-22 at 12 12 58 PM" src="https://user-images.githubusercontent.com/254612/175118651-0eee15fe-017a-4249-a2c3-e35de12d6b6b.png">

Tactically the things to communicate are:
- Results per page
- Total results in the set
- Limitations around exporting and how to recover
  - If the total result set is larger than our export limit, indicate this prominently on the button and don't wait to reveal it until the user tries to export. 
  - Give easy, approachable ways to recover. For example, add filters to reduce your set, only export the first 10,000 items and drop the rest, link to docs on how to export the API, a support link to engage with us to help the user recover. 

Additional considerations:
- Find ways to increase the limit for exporting via the web interface
- Allow for long-running export tasks that prompt a user to download once complete
