### ISSUE TITLE
Make retention cohort tables exportable

### ISSUE THREAD

**Issue by clarkus** [PostHog/posthog#10424]
## Is your feature request related to a problem?
Very similar to the persons modal we display for funnels, it'd be great to be able to use the data shown in the retention cohort persons table. We could make it exportable or able to populate a new static cohort to extend the value of the feature. 

## Describe the solution you'd like
- Make the table exportable in CSV format
- Add a utility action for creating a new cohort from the list of persons in the table

## Describe alternatives you've considered
- None at this time

## Additional context

- [Slack thread](https://posthog.slack.com/archives/C01F31E9PRD/p1655908093526789)

**Comment by marcushyett-ph** [comment]
Thanks for creating this - I've also linked this ticket on the [spreadsheet for places we need to enable exporting](https://docs.google.com/spreadsheets/d/11MmoGzCK1aX5DSswMDFAeDYWbzst0ANP43fHny6_1Ws/edit#gid=0)

**Comment by pauldambra** [comment]
I think this is fixed in #10607 

![2022-07-23 18 39 40](https://user-images.githubusercontent.com/984817/180616634-6b317776-adbb-4b6d-8b8d-281ab00379bb.gif)
