### ISSUE TITLE
Invite modal's UI is oddly huge and a bit misaligned

### ISSUE THREAD

**Issue by Twixes** [PostHog/posthog#10427]
## Bug description

Looks like the invite modal got reworked. I was a bit surprised to see this in the app:

<img width="699" alt="Screen Shot 2022-06-22 at 18 10 58" src="https://user-images.githubusercontent.com/4550621/175081237-e75e6763-f520-46f9-b175-c3f1648df4a8.png">

There are a few UI issues:
- ~~close button is not right-aligned fully~~
- "Invite team members" and "Invite others to Playground" seem pretty duplicated
- Name/email inputs have huge paddings
- "Name (optional)" inputs are misaligned and don't fill the width
- "Add email address" button is huge too
- Minor: the thick dashed border style isn't really something we use in the main UI, AFAIK it's mostly intended for "bridge" pages

CC @liyiy

**Comment by liyiy** [comment]
@Twixes This was implemented based on the designs from the mocks https://www.figma.com/file/gQBj9YnNgD8YW4nBwCVLZf/PostHog-App?node-id=10379%3A42616

I could clean up some of the alignment but for the most part the header text, bigger paddings, dashed borders, etc. aren't really bugs as they were part of the mock designs. Feel free to discuss with @clarkus 😄

**Comment by jaysoni-ash42** [comment]
@Twixes  is this issue still active. Can i work on this issue?

**Comment by mariusandra** [comment]
The invite menu is currently looking like this:

![image](https://user-images.githubusercontent.com/53387/177274820-4a6913ca-1f66-4732-a759-b780fcecdcf8.png)

Whereas this is the design:

![image](https://user-images.githubusercontent.com/53387/177275355-28bba18d-d066-41ab-b896-efbe9dff99a4.png)

I'm not certain if there are any changes to that design that are planned, but @jaysoni-ash42 feel free to give it a go for implementing the difference between what's implemented and what's designed. Make sure to include screenshots when you submit a PR. :)

We're using our home built UI framework called "Lemon UI" for most of the elements. Here's some basic documentation about it: https://storybook.posthog.net/?path=/story/lemon-ui-overview--page

**Comment by clarkus** [comment]
I don't think this is ready for work yet. In the onboarding portion of the product, we are using some styles that bridge the aesthetics from posthog.com into the product. I'm still working on realigning modals to be consistent everywhere. Worth noting that the invite modal comes in a few forms depending on how things are set up. If email isn't configured, you get a different experience.

**Comment by clarkus** [comment]
I've adjusted the [modal components](https://www.figma.com/file/Y9G24U4r04nEjIDGIEGuKI/PostHog-Design-System-One?node-id=2877%3A4784) to balance some of the aesthetic changes in onboarding with the more utilitarian styles used elsewhere in the product. This translates to a little extra padding, slightly different hierarchy regarding descriptions, and a move away from full-bleed dividers. 

<img width="481" alt="Frame 9078" src="https://user-images.githubusercontent.com/254612/177850006-e721eb36-d7fd-4c0e-8540-f7aa2f5e4a2c.png">

<img width="481" alt="Frame 9079" src="https://user-images.githubusercontent.com/254612/177850003-ca7d7352-b685-4cd8-8118-1702181c5a7d.png">
