### ISSUE TITLE
In what cases do we need feature flag overrides?

### ISSUE THREAD

**Issue by neilkakkar** [PostHog/posthog#10445]
## Problem

When getting feature flags in a `/decide` request, we always check the featureFlagOverrides table if there are any overrides for this person's feature flags.

This is suboptimal, majorly because these overrides are keyed to `users` of PostHog, and not just `persons` visiting a site on which PostHog is enabled.

This is a small(?) slowdown on every `/decide` request for every client.

As far as I can tell, the only place that's using overrides is the toolbar. Are there any other places using these overrides?

Thus, I propose, that whenever the toolbar is loaded, we send an extra parameter alongside to tell `/decide` to give us overrides. Returning overrides in any other case seems meaningless.

To take it to another extreme, if the overrides matter only when the toolbar is loaded, why not just keep them on the client side, and get rid of server side overrides completely?

## Additional context

cc: @rcmarron @marcushyett-ph @mariusandra @macobo  if I'm missing something here.

**Comment by macobo** [comment]
Some technical context (and no product :P):

> As far as I can tell, the only place that's using overrides is the toolbar. Are there any other places using these overrides?

As far as I know this was added for the purpose of only the toolbar.

> This is a small(?) slowdown on every /decide request for every client.

Not so small. We needed to put in hours of optimization work into this and there's still this issue in the backlog. https://github.com/PostHog/posthog/issues/7182

Before we scale a lot we need to speed this up.

**Comment by mariusandra** [comment]
The initial idea was that server side libraries would also benefit from knowing about overrides. Otherwise for example the e-mail sent by the backend (using posthog-ruby) won't match the CTA you showed the user (using posthog-js).

**Comment by neilkakkar** [comment]
That makes sense, sounds like a valid use case!

We're leaning towards not supporting this use case for now. Do you / anyone else feel strongly about keeping server side overrides?

They've been [causing some pain](https://posthog.slack.com/archives/C0185UNBSJZ/p1656591277727529), and aren't [used by many teams](https://metabase.posthog.net/question#eyJkYXRhc2V0X3F1ZXJ5Ijp7InR5cGUiOiJxdWVyeSIsInF1ZXJ5Ijp7InNvdXJjZS10YWJsZSI6NDEzLCJhZ2dyZWdhdGlvbiI6W1siY291bnQiXV0sImJyZWFrb3V0IjpbWyJmaWVsZCIsNDMxNixudWxsXV19LCJkYXRhYmFzZSI6M30sImRpc3BsYXkiOiJ0YWJsZSIsInZpc3VhbGl6YXRpb25fc2V0dGluZ3MiOnt9fQ==).

We're not fully getting rid of them, but making them client side: https://github.com/PostHog/posthog/pull/10592

**Comment by mariusandra** [comment]
Yeet away! If I'd know of the limitation (client side only -- and it's clearly written) when developing my app, I'd work around this. 👍
