### ISSUE TITLE
Pie charts added to a dashboard don't render properly in Safari

### ISSUE THREAD

**Issue by sjmadsen** [PostHog/posthog#1045]
**Describe the bug**
When a pie chart is added to a dashboard, it doesn't render properly on Safari. The middle number is clipped at the top and the pie wedges are missing entirely.

**To Reproduce**
1. Create a trend and use the pie visualization.
2. Add it to a dashboard.

**Expected behavior**
As in Chrome, the pie chart should render on a dashboard.

**Screenshots**
![image](https://user-images.githubusercontent.com/57522/84948470-c93edd00-b0b9-11ea-97c4-548277ea8e3c.png)

**Hosted or self hosted?:**
- self-hosted
- 1.8.0

**Additional context**

**Comment by timgl** [comment]
@sjmadsen Thanks for raising this and for your patience. This is now merged into master and will be included in the next release!
