### ISSUE TITLE
Race condition with cache updates after person deletion 

### ISSUE THREAD

**Issue by yakkomajuri** [PostHog/posthog#10479]
There's a TODO in the code to delete a person from cache when it's deleted from the DB.

On the surface this seems easy to fix, but upon digging a bit more, there's a larger problem we need to solve.

Consider what currently happens if we clear the cache and delete the row from the DB.

1. We look the data up from the cache, nothing
2. We look the data up from the DB, nothing
3. We return undefined
4. We don't add person data to the event

Now, if an event is going through the pipeline and the person doesn't exist, we'll create one. Thus, when deleting a person, if events keep being sent to the person's distinct ID, a new person will be created. 

There is however a race condition where the event is already in the pipeline by the time the person gets deleted. This is very small probability and probably something we can punt on for now. However, I wonder about what the implications are of having these "loose" events not attached to a person. In the past this would have never been a thing, but with persons moving to be in the event, this could be problematic.

Just documenting for now.

**Comment by macobo** [comment]
I think we probably shouldn't be deleting rows from postgres we are currently - instead we should mark them as is_deleted and trim the data in e.g. a cronjob. :)

This way we also handle deleting identically in clickhouse and postgres.

**Comment by yakkomajuri** [comment]
That would not fix this particular problem, but either way is a valid point.

A problem with that though is that users want immediate feedback on deletion. Or do you propose we actually add a `is_deleted` column to Postgres persons that we use when querying?

Else the UI would need to query both CH and Postgres (unless we pull the trigger on only querying CH)

**Comment by tiina303** [comment]
Let's punt on this for now, the probability of this is low and the user can always send a new delete request.
