### ISSUE TITLE
Allow breaking down on person properties

### ISSUE THREAD

**Issue by timgl** [PostHog/posthog#1050]
**Describe the bug**

At the moment, you can select a user property to break down on, but it doesn't do anything.

**To Reproduce**
1. Go to trends
2. Select a person property under breakdown
3. It only shows 'other'

**Expected behavior**

It should correctly break down.

**Screenshots**

**Hosted or self hosted?:**
- both

**Additional context**

**Comment by EDsCODE** [comment]
For me, I can't even get user properties to show up on the break down dropdown

**Comment by timgl** [comment]
They're in there, just not as a separate category

**Comment by EDsCODE** [comment]
Oh I see them on the app.posthog instance. Are you working on this ticket or was the a self-assign just automatic?

**Comment by timgl** [comment]
I wasn't working on it right now so if you fancy it go ahead!

**Comment by EDsCODE** [comment]
Looked into this a bit more. To solve we just need to add some logic to handle person specific properties by annotating filtered_events with person_properties. However, to clarify, which person properties are you referring to in the breakdown? There might be some stale properties like 'email' which appear to be person properties, but from our components, it looks like breakdown filter isn't displaying any person properties at all

propertyfilter.js
<img width="1021" alt="Screen Shot 2020-06-22 at 1 16 53 PM" src="https://user-images.githubusercontent.com/13127476/85316605-ffe67000-b48a-11ea-81b4-249f8cc56d77.png">

breakdownfilter.js
<img width="980" alt="Screen Shot 2020-06-22 at 1 17 01 PM" src="https://user-images.githubusercontent.com/13127476/85316608-01179d00-b48b-11ea-8692-d654dcf9006a.png">

**Comment by corbt** [comment]
I just came here to see what the status was; ecstatic that it's being worked on!

I don't know how properties are modeled on the Posthog side, but the properties I'm interested in breaking down on are ones that I set when I call `client.identify`. Eg. in our Ruby code we identify users with the following API call:

```ruby
client.identify(
  distinct_id: user.uuid,
  properties: {
    certified: user.tagged?('certified'),
    country: user.country,
    email_pref: user.email_pref,
    how_heard: user.how_heard,
    signup_week: user.created_at.at_beginning_of_week.strftime('%b %-d, %Y'),
  }
)
```

I'd like to be able to see graphs broken down by the `certified`, `country`, `signup_week`, etc. properties.

**Comment by timgl** [comment]
Done!

**Comment by corbt** [comment]
🎉 will this make it into this Wednesday's release?

**Comment by timgl** [comment]
We're still playing around with our release schedule -- we might be releasing a bit later this week, but this feature will definitely be in the next one!
