### ISSUE TITLE
Replace "Today" with "Last 24 Hours" and "Yesterday" with "Last 48 Hours"

### ISSUE THREAD

**Issue by corbt** [PostHog/posthog#1052]
**Is your feature request related to a problem? Please describe.**

When I view a trend graph, I can set the time window to "Today" or "Yesterday", but if I'm just a few hours into the current day "Today" doesn't give me much historical context, and "Yesterday" doesn't give me the most up-to-date data. "Last Week" does what I want, but is a much larger timespan that makes it hard to distinguish the latest data.

**Describe the solution you'd like**

In the time window picker for a trend graph, replace "Today" with "Last 24 Hours" and "Yesterday" with "Last 48 Hours". These would work similarly to the "Last Week" and "Last Two Weeks" selectors (as in they'd be sliding windows), just with a shorter duration.

**Describe alternatives you've considered**

Allowing users to pick a time range more granularly (down to the hour) would also solve my problem, or allowing me to pick a custom time that doesn't end at midnight. However, these solutions are less ideal because if I save a graph with a custom time window to the dashboard it doesn't stay up to date with the latest data. 

Thanks!

**Comment by timgl** [comment]
Thanks for writing this up!

**Comment by corbt** [comment]
Wow, incredible turn-around time on this @mariusandra ! Love this team! 👊

**Comment by mariusandra** [comment]
You can thank @timgl, I just reviewed his work :). 
In any case thanks for bringing this issue to our attention!
