### ISSUE TITLE
Missing events when capturing using the HTTP API manually

### ISSUE THREAD

**Issue by Xyz3R** [PostHog/posthog#10527]
## Bug description

When tracking events via manual API requests, only the event that matches the test event in the [documentation](https://posthog.com/docs/api/post-only-endpoints) is tracked. The request returns a 200 OK, but 3 out of 4 events in are dismissed and never appear in the live events view. The response body to my batch capture request is:
  
  

```
HTTP/1.1 200 OK
Date: Tue, 28 Jun 2022 09:47:39 GMT
Content-Type: application/json
Content-Length: 13
Connection: keep-alive
Server: gunicorn
X-Frame-Options: DENY
X-Content-Type-Options: nosniff
Referrer-Policy: same-origin

{
  "status": 1
}
```
  
  

Frontend itself is probably not affected, but this is how the live events view looks. My expectation would be for the other events from the request to also show up in the live view, as none have an explicit timestamp set.
<img width="1498" alt="image" src="https://user-images.githubusercontent.com/10122569/176148710-0197c8ab-2081-42c9-826e-0a28e86c14ab.png">

## How to reproduce

I am using this curl request to test. Please note that you will have to replace the api key in the payload as it is redacted out.
I am using the public API key, as all I am trying to achieve is tracking events.

```
curl -X POST --location "https://app.posthog.com/batch/" \
    -H "Content-Type: application/json" \
    -d "{
          \"api_key\": \"<<INSERT PUBLIC API KEY HERE>>\",
          \"batch\": [
            {
              \"event\": \"NotTracked1\",
              \"properties\": {
                \"distinctId\": \"5BqnQpWkjqWVNzmoheHy8vScFo2ADTWm1\",
                \"data\": {
                  \"userAgent\": \"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/102.0.0.0 Safari/537.36\"
                }
              }
            },
            {
              \"event\": \"NotTracked2\",
              \"properties\": {
                \"distinctId\": \"5BqnQpWkjqWVNzmoheHy8vScFo2ADTWm2\",
                \"data\": {}
              }
            },
            {
              \"event\": \"NotTracked3\",
              \"properties\": {
                \"distinctId\": \"5BqnQpWkjqWVNzmoheHy8vScFo2ADTWm3\",
                \"data\": {
                  \"path\": [
                    \"#document\",
                    \"html\",
                    \"body.theme-light.sl-theme-light\",
                    \"app-root#app-root.ng-tns-c179-0\",
                    \"app-inject-css-properties.ng-tns-c179-0.ng-star-inserted\",
                    \"div.inject-colors.theme-light.language-de\",
                    \"div.relative.h-full.grid.grid-rows-[auto_auto_1fr].overflow-hidden.ng-star-inserted\",
                    \"div.overflow-auto.ng-tns-c179-0\",
                    \"app-authentication.ng-star-inserted\",
                    \"app-authentication-dialog-view\",
                    \"app-inject-css-properties\",
                    \"div.inject-colors.theme-light.language-de\",
                    \"div.page.ng-star-inserted\",
                    \"div.container\",
                    \"div.content\",
                    \"app-forms-container\",
                    \"app-login-form\",
                    \"form.ng-untouched.ng-pristine.ng-valid.ng-star-inserted\",
                    \"app-input-field\",
                    \"div.input-wrapper\",
                    \"div.input\",
                    \"input.ng-untouched.ng-pristine.ng-valid\"
                  ],
                  \"target\": \"input.ng-untouched.ng-pristine.ng-valid\",
                  \"eventType\": \"click\"
                }
              }
            },
            {
              \"event\": \"ThisWorks\",
              \"properties\": {
                \"distinct_id\": \"[your users' distinct id]4\",
                \"key1\": \"value1\",
                \"key2\": \"value2\"
              },
              \"timestamp\": \"[optional timestamp in ISO 8601 format]\"
            }
          ]
        }"
```

## Environment

- [ x] PostHog Cloud
- [ ] self-hosted PostHog (ClickHouse-based), version/commit: _please provide_
- [ ] self-hosted PostHog (Postgres-based, legacy), version/commit: _please provide_

## Additional context

I am using the /batch API to migrate an existing set of events into Posthog. Those are around 17.000 events, capture over the span of a week. My plan is to do some transformations (e.g. transform pageview events into posthog native pageview events) on the data and then batch send them to posthog in chunks of ~500 events. 

I read in the doc that the Posthog team likes to be informed before bigger data migrations. However, given the small size of this I decided against this. Let me know if you think otherwise, then I'll get in contact with them.

**Comment by tiina303** [comment]
Not tracked 1 and 2 worked fine for me. I also double checked that we don't have any events in the dead letter queue from your team. Could you try again or confirm that your project id is 10064 that you were trying to send them to and I can try to send the ones that didn't get tracked.

**Comment by Xyz3R** [comment]
In the meantime I set up my own Posthog instance in a k8s cluster and got it to work.

This was a dead simple case of being blind for your own mistakes:
The property `distinct_id` is called `distinctId` instead of `distinct_id` in the broken events, thus causing them to be dropped (as stated in your documentation).

Mystery solved.


Still tyvm for looking into this!
