### ISSUE TITLE
Cohort summary in popups not showing for breakdown

### ISSUE THREAD

**Issue by alexkim205** [PostHog/posthog#10539]
## Bug description

https://user-images.githubusercontent.com/13460330/176205661-941aeb1e-4e46-4133-ae8d-b2e15509d768.mov

## How to reproduce

1. Go to insights
2. Apply breakdown filter
3. Hover over cohort in taxonomic filter

## Environment

- [ ] PostHog Cloud
- [ ] self-hosted PostHog (ClickHouse-based), version/commit: _please provide_
- [ ] self-hosted PostHog (Postgres-based, legacy), version/commit: _please provide_

**Comment by EDsCODE** [comment]
Fixed: https://github.com/PostHog/posthog/pull/9921
