### ISSUE TITLE
Funnel refreshes no longer save the data & dropout counts are wrong

### ISSUE THREAD

**Issue by dknowles-vsk** [PostHog/posthog#10543]
## Bug description
In 1.37.0 refreshing a funnel no longer updates the dropout counts correctly and the new data is not retained across browser refreshes.

https://user-images.githubusercontent.com/74929925/176237708-11008d92-de7e-4ec7-91f2-cac1df58e1a5.mp4

## How to reproduce
1. Create a funnel
2. Change the action on which it relies
3. Refresh the funnel data
4. Check the number of users who dropped out (dialog vs popup)
5. Refresh the page

## Environment
self-hosted PostHog (ClickHouse-based), version/commit: 1.37.0

**Comment by rcmarron** [comment]
Thanks for reporting this @dknowles-vsk!

I think this is related to caching and there are 2 things happening here:
1. We aren't invalidating the result cache when the underlying action changes. We should add the action steps into the hash key for the cache
2. We aren't force refreshing when loading the person modal if the related insight has been refreshed
