### ISSUE TITLE
New Action via "Inspect element on your site" has a broken url

### ISSUE THREAD

**Issue by adnansorg** [PostHog/posthog#1055]
When the site opens, the file `/static/editor.js` is loaded via `localhost:8234`

ex: `http://localhost:8234/static/editor.js?_ts=1592557925991`

**To Reproduce**
1. Create New Action via `Insepct element on your site`
2. Page loads but the `editor.js` is loaded via `localhost:8234`

**Expected behavior**
Need to see the UI to create actions via elements.

**Screenshots**
n/a

**Hosted or self hosted?:**
- self-hosted
- 1.9.0

**Additional context**
n/a

**Comment by timgl** [comment]
Are you running PostHog locally? Or have you set the `DEBUG` env variable?

**Comment by adnansorg** [comment]
```
IS_BEHIND_PROXY: "true"
DEBUG: 0
TEST: 0
```
It's currently behind an nginx proxy with the following variables.

**Comment by timgl** [comment]
I think setting DEBUG: 0 might still parse to True because #1009 isn't merged yet. Could you try removing DEBUG and TEST?

**Comment by adnansorg** [comment]
That was it. Thank you. Closing
