### ISSUE TITLE
Public shared dashboard stops working after a few hours

### ISSUE THREAD

**Issue by scleriot** [PostHog/posthog#10559]
## Bug description

After some time, a publicly shared dashboard stops working with the following message:
![image](https://user-images.githubusercontent.com/733474/176429613-e2850b92-6cad-4577-9fe1-16d2ed7fe805.png)
 
Here is the browser console errors:
![image](https://user-images.githubusercontent.com/733474/176429529-e33dc5da-a8db-4d87-b65e-ad89cac15849.png)

## How to reproduce

1. Create a dashboard and share it publicly 
2. Open it in a private session, it works
3. Wait for about 4 hours
4. Open the dashboard still in a private session (so you are not logged) and you get this error on all graphs

If the public dashboard link is opened in a browser session where I am logged in Posthog, it works and the dashboard in private session starts working again

## Environment

- [x] PostHog Cloud
- [ ] self-hosted PostHog (ClickHouse-based), version/commit: _please provide_
- [ ] self-hosted PostHog (Postgres-based, legacy), version/commit: _please provide_

**Comment by tiina303** [comment]
@Twixes though it did seem to work for me, maybe it's fixed?

**Comment by mariusandra** [comment]
@scleriot is this still happening?
