### ISSUE TITLE
Ability to show 2 decimals on percentages

### ISSUE THREAD

**Issue by scottfoubister** [PostHog/posthog#10573]
## Is your feature request related to a problem?
When we are looking at funnels that have a similar conversion rate, it's hard to differentiate between similar values because they are all displayed with 1 decimal.

For example, both 12.58% and 12.63% would be displayed as 12.6%.

Right now, the only way to see it is to divide the 2 numbers (e.g. in a calculator app) to see what the 2-decimal value is.

Thanks for considering this enhancement!

## Describe the solution you'd like
Having the ability to see percentages with 2 decimals of precision. Some possible solutions:
- Show 2 decimals places on hover.
- Have a setting somewhere that allows showing all percentages to either 1 decimal or 2 decimals.

Would be great to see this added precision on both the dashboard view and the detail view.

## Describe alternatives you've considered
- Manually dividing the numbers to see the values to 2 decimals. This is slower and doesn't allow seeing the values at a glance of the dashboard. This is what we currently do.
- CSV export and building an external dashboard. Haven't tried this as we want to keep it simple and have it all in Posthog.

**Comment by gracebir** [comment]
@scottfoubister , can you attach a loom video to this issue please?

**Comment by gracebir** [comment]
or steps that can helps us reproduce the issue

**Comment by clarkus** [comment]
I don't think we need more documentation to unblock work on this issue. The core improvement is a change in the precision of values shown in the product. I feel like a two decimal precision would be a good change for all percentage values shown across the product.

**Comment by gracebir** [comment]
@clarkus ,I have understood it actually
