### ISSUE TITLE
User properties table malformed

### ISSUE THREAD

**Issue by corywatilo** [PostHog/posthog#10595]
There seems to be an issue with some nesting when viewing a user's properties.

[Here's the example](https://app.posthog.com/person/N7Hrg8v2aHjjGBYI11faajWxX5yW0QW5uLOBSCgF7wE) shown below

<img width="1399" alt="image" src="https://user-images.githubusercontent.com/154479/176814921-e8829667-feb5-40e7-bc87-56840c2983ca.png">

**Comment by mariusandra** [comment]
It's "correct" in that all "key" columns are horizontally left-aligned & vertically middle-aligned. The fix is to top-align all the columns. 

It's also not a CSS oneliner (`vertical-align: top`) since there will be some spacing inconsistencies when you compare properties that are tables or properties that are values.

Should definitely be fixed :)

**Comment by clarkus** [comment]
Is there any reason we wouldn't use nested tables for this scenario? In other similar scenarios, we use a table within a table to ensure that headers are shown and that each value is clearly labeled and understandable. As an example, data management does this for showing properties seen with an event.

**Comment by mariusandra** [comment]
The columns are always `key` and `value`, so sub-tables might look very repetitive. I might give it a try as part of support later, but I'm afraid it's going to look visually messy... 🤔

**Comment by clarkus** [comment]
OK let me know if you want support on that. I was looking at this a bit yesterday and the vertical alignment will help a ton, but I also feel like the table row borders are a factor. This isn't a case handled in the lemon table components we have now, so I'm happy to draw some ideas for that if you think it's a good use of time.

**Comment by mariusandra** [comment]
Here are some attempts at improving these tables without a lot of changes to the markup:

@clarkus are any of those worth implementing? 


0. How it is now
![localhost_8000_events_eventFilter=package json (5)](https://user-images.githubusercontent.com/53387/186688666-f8de1f82-f494-4aa7-9d9a-d9633858d0e3.png)

1. Borders around tables
![localhost_8000_events_eventFilter=package json](https://user-images.githubusercontent.com/53387/186688106-2af47313-f701-4bfe-9e3d-eb54666ce450.png)

2. Borders around tables, header on subtables
![localhost_8000_events_eventFilter=package json (4)](https://user-images.githubusercontent.com/53387/186688468-b03e3846-5a8f-4557-aa1f-60a1d319ee4f.png)

4. Borders and header on tables
![localhost_8000_events_eventFilter=package json (3)](https://user-images.githubusercontent.com/53387/186688326-9fc31afb-c0ef-4a12-809d-35082465a46a.png)

I tried vertically top-aligning keys columns, but not sure if that improves anything:

5. Top aligned headerful table
![localhost_8000_events_eventFilter=package json (6)](https://user-images.githubusercontent.com/53387/186690130-d36863f9-83ff-48be-994c-7e1291f6d1ab.png)

6. Top aligned headerless table
![localhost_8000_events_eventFilter=package json (7)](https://user-images.githubusercontent.com/53387/186690425-5728c285-3ca4-44c6-94d3-fecbddb01305.png)

**Comment by clarkus** [comment]
@mariusandra I think top-aligning the property key is worth trying. The other thing that makes this harder to scan is that amount of horizontal space between the key and the value. I've been working through some similar patterns for other more compact views. I did a quick redraw to illustrate what I'm trying to describe. 

Generally what I'm proposing is:
- Size the key column to be just wide enough to contain the largest string value in this column.
- That will give most of the space in the table to the values, and in the case of nested key:value pairs, lots of space to show all that detail
- Top-align the key to line up with the first value, or the first nested key:value sets. 
- I've also been using monospace fonts for the nested sets 

<img width="1015" alt="Screen Shot 2022-08-25 at 10 45 45 AM" src="https://user-images.githubusercontent.com/254612/186733934-c2cd8db0-bc16-4347-b51a-60c167b64b60.png">

https://www.figma.com/file/rnaKSVMfWTcpX4cmDbvWsi/Data-Management-%26-Live-Events?node-id=13%3A1947

Thoughts?

**Comment by Twixes** [comment]
Seems like this can be improved mostly just by setting the horizontal padding for leftmost/rightmost columns to zero in those embedded tables.
