### ISSUE TITLE
editor.js trying to loading over http instead of https

### ISSUE THREAD

**Issue by sundarv85** [PostHog/posthog#1060]
When we try to define an action from the posthog into our website, we are seeing the below error in browser console and the editor.js is not shown

`array.js:8 Mixed Content: The page at 'https://www.myapp.com/users/1/sites' was loaded over HTTPS, but requested an insecure script 'http://posthog.myapp-ops.com/static/editor.js?_ts=1592587899688'. This request has been blocked; the content must be served over HTTPS.`

We are using docker setup of Posthog. Infront of Posthog, we have nginx with SSL termination. We saw infinite loop of SSL redirect, we have set the `DISABLE_SECURE_SSL_REDIRECT=1` environment variable in docker compose.

**Hosted or self hosted?:**
- self-hosted
- latest release (1.9.0)

**Comment by timgl** [comment]
Have you set IS_BEHIND_PROXY?

**Comment by sundarv85** [comment]
Thanks, that was one of the issues. We also fixed some issues on our nginx setup as well - and now it it is working.
