### ISSUE TITLE
Improved compression options for `properties` column

### ISSUE THREAD

**Issue by macobo** [PostHog/posthog#10616]
## Background

We store event data in clickhouse for queries. The largest column in the events table is `properties` - a json-encoded string column containing all user-passed event properties. This issue explores how we could improve that storage and there-by speed up I/O-bound queries.

By default, clickhouse compresses all data with the LZ4 algorithm. This is a cheap compression algorithm, but might not be ideal for all queries. In our usecase we're storing a lot bigger data in clickhouse than is usual for common use-cases, so some tuning is natural.

One area where LZ4 is especially lacking is storing [person properties on events](https://github.com/PostHog/posthog/issues/10561), where the resulting compression ratio would have caused a lot of overhead.

Long-term we should use the new `Object('json')` data type to store these properties which would compress a lot better, but the feature [is not yet production-ready](https://github.com/PostHog/posthog/issues/10506#issuecomment-1169888587).

### Success criteria

We're looking for a compression scheme which would:
1. Speed up uncached queries significantly
2. Reduce required storage
3. Would not add excessive CPU overhead during ingestion or queries

### Dataset 1: 100M properties

I created a test dataset of 100M properties stored in a table and checking various compression codecs against it. The dataset is 166.42GB uncompressed and should be represenative of data we're seeing in practice.

Each column has improvement over LZ4 in parenthesis (>1 is improvement, <1 signifies degraded performance).

| Compression | size on disk | optimize duration | optimize CPU time | query duration (no cache) | query CPU time (no cache) | query duration | query CPU time |
| --- | --- | --- | --- | --- | --- | --- | --- |
| LZ4 (baseline) | 25.64 GiB (1.0x) | 444881ms (1.0x) | 264813ms (1.0x) | 206924ms (1.0x) | 79966ms (1.0x) | 8978ms (1.0x) | 70976ms (1.0x) |
| ZSTD(1) | 12.25 GiB (2.09x) | 347728ms (1.28x) | 243711ms (1.09x) | 96755ms (2.14x) | 87465ms (0.91x) | 10894ms (0.82x) | 86291ms (0.82x) |
| ZSTD(2) | 11.48 GiB (2.23x) | 307275ms (1.45x) | 259537ms (1.02x) | 90564ms (2.28x) | 88506ms (0.9x) | 10850ms (0.83x) | 85550ms (0.83x) |
| ZSTD(3) | 10.89 GiB (2.35x) | 328978ms (1.35x) | 287627ms (0.92x) | 85390ms (2.42x) | 87437ms (0.91x) | 10509ms (0.85x) | 83329ms (0.85x) |
| ZSTD(4) | 10.88 GiB (2.36x) | 332881ms (1.34x) | 295525ms (0.9x) | 85132ms (2.43x) | 90811ms (0.88x) | 10577ms (0.85x) | 83840ms (0.85x) |
| ZSTD(5) | 9.69 GiB (2.65x) | 507521ms (0.88x) | 478359ms (0.55x) | 75533ms (2.74x) | 82307ms (0.97x) | 9536ms (0.94x) | 75730ms (0.94x) |
| ZSTD(6) | 9.36 GiB (2.74x) | 586124ms (0.76x) | 583027ms (0.45x) | 72729ms (2.85x) | 77809ms (1.03x) | 9476ms (0.95x) | 74767ms (0.95x) |
| ZSTD(7) | 9.13 GiB (2.81x) | 649911ms (0.68x) | 647240ms (0.41x) | 70843ms (2.92x) | 76485ms (1.05x) | 9053ms (0.99x) | 71642ms (0.99x) |
| ZSTD(8) | 9.01 GiB (2.85x) | 753308ms (0.59x) | 750914ms (0.35x) | 69764ms (2.97x) | 73427ms (1.09x) | 8830ms (1.02x) | 69719ms (1.02x) |
| ZSTD(9) | 9.01 GiB (2.85x) | 859532ms (0.52x) | 857731ms (0.31x) | 69824ms (2.96x) | 73774ms (1.08x) | 9113ms (0.99x) | 72234ms (0.98x) |
| ZSTD(11) | 8.82 GiB (2.91x) | 1220685ms (0.36x) | 1219220ms (0.22x) | 68178ms (3.04x) | 73570ms (1.09x) | 8614ms (1.04x) | 68287ms (1.04x) |
| ZSTD(13) | 8.87 GiB (2.89x) | 3006105ms (0.15x) | 3005012ms (0.09x) | 68559ms (3.02x) | 71575ms (1.12x) | 8558ms (1.05x) | 67631ms (1.05x) |
| LZ4HC(9) | 17.24 GiB (1.49x) | 1538902ms (0.29x) | 1536092ms (0.17x) | 137395ms (1.51x) | 61679ms (1.3x) | 7377ms (1.22x) | 58474ms (1.21x) |
| LZ4HC(4) | 17.56 GiB (1.46x) | 843012ms (0.53x) | 795095ms (0.33x) | 140047ms (1.48x) | 63342ms (1.26x) | 7427ms (1.21x) | 58750ms (1.21x) |

<details><summary>More details on results / methodology</summary>

The scripts for this experiment and raw results can be found here: https://gist.github.com/macobo/8a354ac7900a4a286826d054595e4689

This approach was copied from https://kb.altinity.com/altinity-kb-schema-design/codecs/codecs-speed/

Quick explanation on what the columns signify:

**optimize** - before every test `OPTIMIZE TABLE test_codec_speed FINAL` was run. This actually modifies the data in table to use the new codec, and helps measure the cost of reading and writing the whole dataset. Results here signify how much ingestion would be affected by the new compression schema

**cpu time** - this signifies how much time was spent on all cpus during this query (not counting I/O). See [here](https://github.com/ClickHouse/ClickHouse/blob/36af27b7c0abefcb8265d5f13d333dced80fe0d5/src/Common/ProfileEvents.cpp#L209) for a clickhouse-side explanation

**query** - `SELECT max(properties) FROM test_codec_speed` was run. This requires reading the whole dataset, showing both I/O and decompression speed with very little other overhead.

**no cache** We generally recommend running clickhouse with a lot of extra memory for OS page cache. The page cache speeds up reading data repeatedly from disks, which helps speed up queries by not needing to read the data from disk. The page cache is why we sometimes see queries be really slow and on a rerun complete instantly as on subsequent queries the data is read much faster. In the data above, queries were run with both no page cache and with the data pre-read into memory to get a sense for how we'd behave in both cases. We should care more for no-cache behavior than cached behavior when doing capacity planning.

The machine was a r6i.4xlarge with 1TB of storage.
</details>

<details><summary>Click to see results on a smaller dataset</summary>

This dataset only had 30M rows. Not mentioning it top-level since it reveals no new interesting information.

| Compression | size on disk | optimize duration | optimize CPU time | query duration (no cache) | query CPU time (no cache) | query duration | query CPU time |
| --- | --- | --- | --- | --- | --- | --- | --- |
| LZ4 | 9.70 GiB (1.0x) | 104238ms (1.0x) | 102952ms (1.0x) | 69387ms (1.0x) | 30075ms (1.0x) | 3979ms (1.0x) | 30653ms (1.0x) |
| ZSTD(1) | 4.20 GiB (2.31x) | 92685ms (1.12x) | 89633ms (1.15x) | 23658ms (2.93x) | 37469ms (0.8x) | 4482ms (0.89x) | 34764ms (0.88x) |
| ZSTD(2) | 3.88 GiB (2.5x) | 94694ms (1.1x) | 92563ms (1.11x) | 25096ms (2.76x) | 33883ms (0.89x) | 4280ms (0.93x) | 33151ms (0.92x) |
| ZSTD(3) | 3.65 GiB (2.66x) | 101550ms (1.03x) | 99817ms (1.03x) | 27532ms (2.52x) | 32469ms (0.93x) | 4207ms (0.95x) | 32323ms (0.95x) |
| ZSTD(4) | 3.65 GiB (2.66x) | 102965ms (1.01x) | 100368ms (1.03x) | 26949ms (2.57x) | 32239ms (0.93x) | 4100ms (0.97x) | 31967ms (0.96x) |
| ZSTD(5) | 3.24 GiB (2.99x) | 164926ms (0.63x) | 163464ms (0.63x) | 22384ms (3.1x) | 29484ms (1.02x) | 4154ms (0.96x) | 32329ms (0.95x) |
| ZSTD(6) | 3.13 GiB (3.1x) | 202615ms (0.51x) | 201320ms (0.51x) | 21940ms (3.16x) | 30147ms (1.0x) | 4076ms (0.98x) | 31454ms (0.97x) |
| ZSTD(7) | 3.07 GiB (3.16x) | 218907ms (0.48x) | 217713ms (0.47x) | 21546ms (3.22x) | 29040ms (1.04x) | 3632ms (1.1x) | 28033ms (1.09x) |
| ZSTD(8) | 3.03 GiB (3.2x) | 270125ms (0.39x) | 269246ms (0.38x) | 21901ms (3.17x) | 30500ms (0.99x) | 3903ms (1.02x) | 30287ms (1.01x) |
| ZSTD(9) | 3.03 GiB (3.2x) | 300319ms (0.35x) | 299418ms (0.34x) | 21943ms (3.16x) | 30528ms (0.99x) | 4018ms (0.99x) | 30086ms (1.02x) |
| ZSTD(11) | 2.98 GiB (3.26x) | 402172ms (0.26x) | 401352ms (0.26x) | 22043ms (3.15x) | 29904ms (1.01x) | 3588ms (1.11x) | 27632ms (1.11x) |
| ZSTD(13) | 2.99 GiB (3.24x) | 1083108ms (0.1x) | 1082603ms (0.1x) | 22100ms (3.14x) | 28119ms (1.07x) | 3571ms (1.11x) | 27753ms (1.1x) |
| LZ4HC(9) | 6.26 GiB (1.55x) | 543807ms (0.19x) | 542569ms (0.19x) | 48965ms (1.42x) | 25244ms (1.19x) | 3397ms (1.17x) | 26256ms (1.17x) |
| LZ4HC(4) | 6.36 GiB (1.53x) | 300497ms (0.35x) | 298634ms (0.34x) | 49731ms (1.4x) | 26820ms (1.12x) | 3302ms (1.21x) | 25430ms (1.21x) |

</details>

### Dataset 2: persons-on-events

As part of [person properties on events planning](https://github.com/PostHog/posthog/issues/10561), a few compression schemes were compared for
person properties storage.

| column | codec | on_disk | compressed | uncompressed | compression ratio | improvement |
| --- | --- | --- | --- | --- | --- | --- |
| person_properties         | LZ4      | 65.92 GiB | 65.92 GiB  | 280.54 GiB   |               4.3 |           1 |
| person_properties_LZ4HC   | LZ4HC(0) | 55.38 GiB | 55.38 GiB  | 280.54 GiB   |               5.1 |         1.2 |
| person_properties_LZ4HC_4 | LZ4HC(4) | 55.85 GiB | 55.85 GiB  | 280.54 GiB   |                 5 |         1.2 |
| person_properties_ZSTD    | ZSTD(1)  | 13.98 GiB | 13.98 GiB  | 280.54 GiB   |              20.1 |         4.7 |
| person_properties_ZSTD_3  | ZSTD(3)  | 12.45 GiB | 12.45 GiB  | 280.54 GiB   |              22.5 |         5.3 |
| person_properties_ZSTD_7  | ZSTD(7)  | 11.48 GiB | 11.48 GiB  | 280.54 GiB   |              24.4 |         5.7 |
| properties                | LZ4      | 32.61 GiB | 32.61 GiB  | 431.96 GiB   |              13.2 |           1 |
| properties_LZ4HC          | LZ4HC(0) | 23.29 GiB | 23.29 GiB  | 431.96 GiB   |              18.5 |         1.4 |
| properties_LZ4HC_4        | LZ4HC(4) | 23.69 GiB | 23.69 GiB  | 431.96 GiB   |              18.2 |         1.4 |
| properties_ZSTD           | ZSTD(1)  | 14.53 GiB | 14.53 GiB  | 431.96 GiB   |              29.7 |         2.2 |
| properties_ZSTD_3         | ZSTD(3)  | 13.76 GiB | 13.76 GiB  | 431.96 GiB   |              31.4 |         2.4 |
| properties_ZSTD_7         | ZSTD(7)  | 11.68 GiB | 11.68 GiB  | 431.96 GiB   |                37 |         2.8 |

## Conclusions

I would suggest we switch to ZSTD(3), as it seems the best at balancing upsides/downsides. Summarizing the data above:

- Upside: Compression for `properties` would improve ~2.4x, for `person_properties` it would improve ~5.7x.
- Upside: This in turn materializes into ~2.4x speed wins when querying the column with no page cache (common). This is especially relevant on cloud, where we're considering switching to EBS soon with its slower storage.
- Upside: Ingestion performance would improve thanks to a combination of less data to write and low compression level.
- Downside: We would however receive a 8% extra CPU load during ingestion. This should be insignificant compared to queries. Note that this did not replicate on the smaller dataset.
- Downside: 8%/17% overhead in CPU load when querying data without page cache and with cache respectively.
- Downside: Up to 17% slower read speed when page cache is being hit. Note that the effect in practice should be lower since we'd be bottlenecked on deserializing JSON.

Read more on this compression scheme here: https://facebook.github.io/zstd/

### How to move to new compression scheme

This does not require an async migration. Instead, we can:
1. Change the compression codec on the existing table, which would apply it going forward.
2. Optionally suggest users run `OPTIMIZE TABLE sharded_events FINAL` to get the full benefit of the new compression scheme everywhere and run this on cloud.

## Additional context

cc @fuziontech who has skin in the game
cc @EDsCODE @yakkomajuri @guidoiaquinti @hazzadous in no particular order

**Comment by guidoiaquinti** [comment]
Nice and detailed analysis as usual @macobo. This is something I’ve also briefly investigated while crunching some data for the _"ClickHouse on EBS"_ project to decouple storage and compute on PostHog Cloud. I’ve also ended up in the same conclusion regarding ZSTD (between level 2 and 5). 

I’m overall 👍 to move forward with your proposal but I have a couple of operational questions about how to roll this out (happy to move the conversation to another issue/thread if you think it is not relevant to the proposal):

- do you suggest running the `OPTIMIZE` node by node? (drain node, run optimize, undrain node)
- is there a way to throttle the `OPTIMIZE` to limit the CPU usage?
- is there a way to pause the `OPTIMIZE` in case of issues?

Thank you! 🙇

**Comment by macobo** [comment]
> do you suggest running the OPTIMIZE node by node? (drain node, run optimize, undrain node)

No. We only need to run OPTIMIZE once per shard and let replication do the rest.

As for the procedure - this should be OK to do on a weekend on cloud due to the much lower load on posthog. 

Note we can also optimize partition by partition as well if this becomes problematic.

> is there a way to throttle the OPTIMIZE to limit the CPU usage?

There doesn't seem to be

> is there a way to pause the OPTIMIZE in case of issues?

`SYSTEM STOP MERGES` will stop a running optimize, followed by a `SYSTEM START MERGES`.

**Comment by yakkomajuri** [comment]
Thanks for the analysis!

Based on this, I'm happy to move forward with it. 

Wondering if there's a benefit in being careful and doing it in parts - move e.g. properties on the person table first and see how that does, before doing events.

Nevertheless - this is the way to go and happy that a normal migration will do the trick here (with the OPTIMIZE caveat)

**Comment by macobo** [comment]
> Wondering if there's a benefit in being careful and doing it in parts - move e.g. properties on the person table first and see how that does, before doing events.

This wouldn't make sense - we wouldn't see any significant performance gains from moving the persons table over as those queries are bottlenecked by JOINs not reading the columns. It would also be really hard to get any worthwhile read on performance out of doing this partially on the events table - I've done all the analysis already above.

----

Note just waiting for @fuziontech's stamp on this as we discussed the CPU overhead trade-off with him.

**Comment by marcushyett-ph** [comment]
Nice one, great findings.

**Comment by fuziontech** [comment]
@macobo if you ever write an analytical book I will be the first in line to buy it. I love your write-ups.

The main thing that this impacts from my perspective is when we are moving to new instances paying a bit more attention to right sizing the instance type and the number of vcpus. Other than that, this looks like a pretty solid win over the current configs and like @guidoiaquinti mentioned could even allow us to use cheaper EBS storage (maybe st1?) That would be an amazing follow on study is comparing ZSTD encoded sharded_events on `gp3` vs `st1`.

I love the `OPTIMIZE` plan, let's just do it partition by partition when it comes to it just to scope it a little. The most important partitions to do will be old ones because they will almost never hit page cache. We could even have a progressively more aggressive compression as data gets old? Would be an interesting lever to have for data life cycling. 

Consider this a 👍 from me!

🚢 it
