### ISSUE TITLE
Posthog calls get blocked by ad blockers

### ISSUE THREAD

**Issue by kefranabg** [PostHog/posthog#10626]
## Bug description

We noticed that Posthog requests were blocked by some ad blockers. We experienced this issue with the following ad blockers:

- Brave Shield
- uBlock Origin

We faced that issue in our local & production env.

![image (7)](https://user-images.githubusercontent.com/9840435/177161830-4235672e-bf1a-472b-919d-4caa71c52056.png)

When disabling the AdBlocker, everything goes well.

## Environment

- [x] PostHog Cloud
- [ ] self-hosted PostHog (ClickHouse-based), version/commit: _please provide_
- [ ] self-hosted PostHog (Postgres-based, legacy), version/commit: _please provide_

**Comment by timgl** [comment]
Thanks for reporting, we're aware of this. There's nothing we can do directly, but you can [deploy a proxy](https://posthog.com/docs/cloud/proxy) or self-host posthog to fix this issue.
