### ISSUE TITLE
Cohort analysis

### ISSUE THREAD

**Issue by timgl** [PostHog/posthog#1063]
**Is your feature request related to a problem? Please describe.**

I want to be able to work out if I'm improving my product over time and that my customers are sticking around.

**Describe the solution you'd like**
![image](https://user-images.githubusercontent.com/1727427/85265564-bf7af800-b472-11ea-834e-484a3a2aa218.png)

We already have the concept of "Stickiness," which is basically one of those rows at one point in time. The simplest MVP solution would just be to call that API endpoint for each of the rows with dates going further back in time.

**Describe alternatives you've considered**

Filtering stickiness manually.

**Additional context**

***Thank*** you for your feature request - we love each and every one!

**Comment by macobo** [comment]
> We already have the concept of "Stickiness," which is basically one of those rows at one point in time.

I tested this out - it doesn't seem quite the case.

Say the case is this: You have 1 user who does (at least) 1 pageview per day for the past 11 days.

You'd expect the retention table to be filled with 100% in every (fillable) cell.

However for stickiness, the current trends endpoint for the same user would return 10 zeroes followed by 1. This represents on how many days out of the whole time period the user was active. The results of this are really dependent on the time range being selected.

This has some weird artefacts which can be seen on the screenshots below:

![Screenshot from 2020-06-22 15-49-31](https://user-images.githubusercontent.com/148820/85289398-10edac00-b4a0-11ea-9197-0e1a0563cd86.png)
![Screenshot from 2020-06-22 15-49-41](https://user-images.githubusercontent.com/148820/85289408-14813300-b4a0-11ea-9339-de650f1c99c8.png)

The result of the query depends on the time range being selected in a way that makes it not suitable for this feature.

In the screenshots I had one user **A** who was active for 5 days and then after a pause for 3 days and one **B** who was active for 11 days. 
- In the first screenshot only **A** is visible w/ 5 days of activity (even though A was also active during that period.
- In the second screenshot **A** is shown to have been around for 8 days, **B** for 11

----

I tested this out using a fake dataset generated by something like the following script:

```js
const PostHog = require('posthog-node')
const moment = require('moment')
const { range } = require('lodash')

const client = new PostHog(
  'QYEs6UIACi8lJuhnHs0Tm3kud6A89PKY0hIVYeX6GYk',
  {host: 'http://0.0.0.0:8000'}
)

const id = process.argv[2]

const hours = range(0, 100).concat(range(200, 240))

hours.forEach((i) => {
  client.capture({
    distinctId: `2020-06-22::${id}`,
    timestamp: moment().subtract(i, 'hours').toDate(),
    event: '$fakepageview2',
  })
})

```
 
----

**Comment by macobo** [comment]
> We already have the concept of "Stickiness," which is basically one of those rows at one point in time.

I tested this out - it doesn't seem quite the case.

Say the case is this: You have 1 user who does (at least) 1 pageview per day for the past 11 days.

You'd expect the retention table to be filled with 100% in every (fillable) cell.

However for stickiness, the current trends endpoint for the same user would return 10 zeroes followed by 1. This represents on how many days out of the whole time period the user was active. The results of this are really dependent on the time range being selected.

This has some weird artefacts which can be seen on the screenshots below:

![Screenshot from 2020-06-22 15-49-31](https://user-images.githubusercontent.com/148820/85289398-10edac00-b4a0-11ea-9197-0e1a0563cd86.png)
![Screenshot from 2020-06-22 15-49-41](https://user-images.githubusercontent.com/148820/85289408-14813300-b4a0-11ea-9339-de650f1c99c8.png)

The result of the query depends on the time range being selected in a way that makes it not suitable for this feature.

In the screenshots I had one user **A** who was active for 5 days and then after a pause for 3 days and one **B** who was active for 11 days. 
- In the first screenshot only **A** is visible w/ 5 days of activity (even though A was also active during that period.
- In the second screenshot **A** is shown to have been around for 8 days, **B** for 11

----

I tested this out using a fake dataset generated by something like the following script:

```js
const PostHog = require('posthog-node')
const moment = require('moment')
const { range } = require('lodash')

const client = new PostHog(
  'QYEs6UIACi8lJuhnHs0Tm3kud6A89PKY0hIVYeX6GYk',
  {host: 'http://0.0.0.0:8000'}
)

const id = process.argv[2]

const hours = range(0, 100).concat(range(200, 240))

hours.forEach((i) => {
  client.capture({
    distinctId: `2020-06-22::${id}`,
    timestamp: moment().subtract(i, 'hours').toDate(),
    event: '$fakepageview2',
  })
})

```
 
----

@timgl Not 100% sure what to make of this - is this how Trends/stickiness is supposed to work? As-is I don't think data from that endpoint can be used here, but I might be missing something.

**Comment by timgl** [comment]
Yep good find. In Mixpanel this would be the difference between "N-Day retention" and "Unbounded retention". The former is what we currently have, the latter would be what you describe.

Mixpanel has both in there and you can switch between them:
![image](https://user-images.githubusercontent.com/1727427/85291574-f36a1380-b49a-11ea-97d6-b471e0ffc832.png)

You should be able to create the table using current "N-Day retention", but if you think unbounded is crucial to getting this done I'd definitely encourage adding that, I don't think it'll be that difficult to change that query.

**Comment by macobo** [comment]
Thanks for clarification, https://help.mixpanel.com/hc/en-us/articles/360001370146-Build-a-Retention-Report- is also a good resource regarding N-day vs unbounded retention.

So for the following dataset (from above):
- User A who was active every day for 5 days, 3 days pause and then active again for 3 days 
- User B who was active every day for 11 days

Wouldn't the expected N-days retention graph for past 2 weeks be the following?

- day 1, 2 users
- day 2, 2 users
...
- day 5, 2 users
- day 6, 1 user
- day 7, 1 user
- day 8, 1 user
- day 9, 2 users
- day 10, 2 users
- day 11, 2 users

That's my understanding at least based on https://amplitude.com/blog/2016/08/11/3-ways-measure-user-retention

This seems not constructable from the stickiness graphs listed above, but I might be missing something obvious.

**Comment by timgl** [comment]
Ah yep you're absolutely right, I had mis-remembered how the stickiness endpoint worked (despite my own explanation in the tooltip!)

I think a new "action" under the events endpoint is the right way to go here to get all the data for unbound retention in one call. From what I understand the working would be:
For each day
 - get all users that had their first action on that day, then work out for each subsequent day how many users still performed that event

I think that's right? This might be a job for lateral joins (see funnels) but I'm not worried about performance right now.

**Comment by macobo** [comment]
Thanks! I will look into tackling this from that angle. :bow:

**Comment by macobo** [comment]
Hello @timgl 

I've pushed my current progress up at https://github.com/macobo/posthog/pull/new/retention-analytics

There's quite a few open topics I'd like to discuss though regarding:

- Semantics of retention. N-day vs unbounded, the "first action" logic you outlined above
- Naming: I think `retention` makes more sense over `cohort analysis`
- Query building - discussing the approach taken, currently my query (knowingly) ignores team_id and person_id vs distinct_id.
- Should we do a separate summary row as shown on the sceenshot?
- Formatting the table
- Testing on real data

Would you be up for a call?

**Comment by macobo** [comment]
Had a face-to-face with Tim.

Most of the discussion revolved around the definition of retention.

Decided to go with the following now, gather feedback, iterate:
1. N-day retention
2. User is counted in _all_ buckets they were present in.
3. No summary row

So for 3, if user **A** did events on days 1-5 and 9-11, they would be "counted" on all of these dates/on every row.

There were a couple reasons to go with this:
- It seemed like the same definition amplitude and mixpanel are using
- Posthog cannot guarantee we know the first date user did $thing - for example, user might have started using app before posthog snippet was installed.

We also decided to call the feature retention.

**Comment by timgl** [comment]
Done
