### ISSUE TITLE
Sprint 1.38.0 2/2 - July 11 to July 22

### ISSUE THREAD

**Issue by marcushyett-ph** [PostHog/posthog#10649]
# Global Sprint Planning

## Retro: Status of Outcomes from Previous Sprint

1. Top priority is to methodically and stepwise ship to 100% on EKS infrastructure @hazzadous @fuziontech
    * why? Six month plan, convert our infra (Status: 100% of non-events endpoints is 🚀 )
2. Audit and improve Postgres monitoring and alerting @guidoiaquinti + someone TBD (Status: In a much better place now - still a ton to do (evergreen issue) but for now not worried about PG for the next sprint. PG bouncer is a different story 😉)
    * why? A lot of pain recently (i.e. tablecache issues), get ahead of some categstorphic fires, find out what might haunt us in the next few months
4. Write the async migration to backfill persons on events (and potentially JSON object data type) @macobo  (@yakkomajuri status: first iteration of async migration will be fully written up by Friday. Slight setback was unexpected holiday.)
   * why? Unlock high scale query, last infra bit we need to work on
6. https://github.com/PostHog/posthog/issues/10421 @yakkomajuri  (Status: great progress - 5/8 goals completed in full, 2 more were started. We never set a hard goal here but the target was always to accomplish 4-6 of these, with the greater focus on data integrity.)
   * why? data integrity is critical for our customers to be successful
7. Nail Exports - Episode 2 - Attack of the Exports - Subscriptions - Slack (finishing) @benjackwhite, CSV - standardise export method and make as many things exportable as possible @pauldambra, Embeds / Sharing @mariusandra (Status: embeds/sharing done, but not sure we'll hit the 20 users goal, CSV still being worked on)
   * why? exports is bread and butter missing functionality, and will drive discovery of posthog and useage from exsisting customers
9. Nail session analysis (Breakdowns/property math operations/funnels) @rcmarron (Status: Mostly done behind a feature flag. Should be complete at end of sprint)
   * why? because our customers really want to understand the duration of sessions for customer engagemnt and we've had a lot of feedback since we removed sessions insight
11. Server side library support for mult-variate feature flags and groups (stretch mobile SDKs) @liyiy (Status: All server libraries have a PR)
    * why? A lot of customers can't use features like experiments or groups because they libraries they use don't support it

## Support hero this sprint

Week 1: @EDsCODE 
Week 2: @hazzadous 

## Plan: Proposed Goals for Next Sprint 

Each goal should have a single owner. Owner can only be an engineer.

1. Kick off the persons on events async migration on Cloud and get a self-hosted team to run it (@yakkomajuri)
    - Why: Unlock high scale querying
2. (P0) PGBouncer clean shutdown and connection drain on helm chart upgrade / deployments, (P0) 5% -> 50% -> 100% of events on EKS by end of sprint (Ambitious), (P1) EU deployment planning, (P1) First part data collection (proxy, DNS, something) @fuziontech 
3. Complete S3 Backed Session Recordings (@rcmarron)
   - Why: Longer session retention
4. Client Library support for Feature flags, sessions & groups (Android, iOS) @alexkim205 
   - Why: Increase surface area for these features in most used libraries
5. Build Expo compatible reactive native library @benjackwhite 
   - Why: 1/3 of Web events come from react native, we don't support expo
6. Onboarding prompts @kappa90 
   - Why: Increasing activation beyond the ingestion part of onboarding

# Team sprint planning

For your team sprint planning copy this template into a comment below for each team.

```
Team ___

## Retro

<!-- Talk about what went well, what didn't go well and any actions to improve next time -->

- 

## Hang over items from previous sprint

<!-- For each item, decide to re-prioritise (and add below) or deprioritise -->

- Item 1. prioritised/deprioritise

## Planning

<!-- Each item should have a single owner. Owner can only be an engineer. -->

### High priority

-

### Bugs

-

### Low priority / side quests

-

```

**Comment by mariusandra** [comment]
Team App East

## Retro

- Paul: fighting celery. ⚔️  Horrible. Still alive.
- Ben: nice side of the stick. Felt very grateful for Paul to be in the weeds. More topics that aren't fully released. Still doing them this week (we're in Wednesday the week after)
- Marius: support, not too busy... no Captain it's Wednesday. 
- Emanuele: not working today 🚚 
- Lottie: away 😷 👨‍⚕️ 
- Marcus: a lot of interviews 🕴️ 

## Hang over items from previous sprint

Exports
- CSV still under development
- Embeds/shares/subscriptions being released as we speak

## Planning

- Onboarding tutorials @kappa90 (support by @pauldambra)
- React native library @benjackwhite (support by @mariusandra)

Sidequest:
- Fix annotation scrolling

**Comment by yakkomajuri** [comment]
# Ingestion team

## Goal

Kick off the persons on events async migration on Cloud and get a self-hosted team to run it.
Owner: @yakkomajuri 
Why: Unlock high scale querying

## Retro

@yakkomajuri 

- Happy with the progress, had some fun shipping activity log
- A bit hard to prioritize at first from the superlist, even though it was ordered
- I struggled to get reviews - Paul helped out a lot with activity log but otherwise I kept having to ping people and got blocked a little bit

@macobo 

- It fell under the sun of planning for persons-on-events. Some highlights
    - Huge kudos to jams for providing me with an test instance and data
    - Huge blow that json datatype in ch is unusable currently - documented a ton of issues
    - space concerns were another drawback - pretty happy compression helped
    - Got to write and learn a lot more about benchmarking throughout it, which was good.
- Personally, I was burned out by the second week due to non-work reasons and after I got my cast off took the last 3 days off to learn to walk again. This put some extra burden on Yakko - thanks for handling it!

**Comment by fuziontech** [comment]
Team Infra

## Retro

- @hazzadous - It's been a blur of a sprint. A whirlwind. Treading on toes not knowing who broke what. Enjoyed looking at the Gitlab stuff (channel). PGBouncer - still having issues with draining connections.
- @fuziontech - Too much noise in sentry and in PD. We are going to miss important signal. We are wasting money on Sentry with garbage.

## Hang over items from previous sprint

- None 🥳 

## Planning

### High priority

- (P0) PGBouncer clean shutdown and connection drain on helm chart upgrade / deployments.
- (P0) 5% -> 50% -> 100% of events on EKS by end of sprint (Ambitious)
- (P1) EU deployment planning
- (P1) First part data collection (proxy, DNS, something)

### Low priority / side quests

- GiST on PG or some solution to speed up Person search

**Comment by EDsCODE** [comment]
Team West

## Sprint Priorities

- S3 backed session recordings @rcmarron 
   - Why: Longer session retention and long term health for infrastructure

- Client library support for feature flags, sessions, and groups @alexkim205 
   - Why: Increase surface area of access for feature flags, sessions, and groups
