### ISSUE TITLE
Send is_anonymous from libraries

### ISSUE THREAD

**Issue by tiina303** [PostHog/posthog#10659]
There are various reasons why it would be useful to know if the user is anonymous, e.g. sending events to the buffer (persons on events) or not. Mobile libraries currently don't provide an easy way to determine if the user is anonymous or not and with posthog-js we look at device ID (a random uuid) matching distinct_id.

**Comment by xvello** [comment]
Closing as we removed the buffer and IIRC we don't use that field anymore. @tiina303 feel free to reopen if still relevant.

**Comment by tiina303** [comment]
@robbie-c  actually implemented something that gives us this info in posthog-js.
