### ISSUE TITLE
503 Service Temporarily Unavailable

### ISSUE THREAD

**Issue by SvenAlHamad** [PostHog/posthog#1065]
**Describe the bug**

We're testing the service internally, there is no load on it at all. The service seems to work for like 10-15 minutes and then goes down for 5 minutes. The same pattern keeps repeating throughout the day. 

Reviewing the stack and the monitoring components, on the ELB (Posth-Publi) I can see it registers the 5xx errors. Under the target group, I can see a constant line of unhealthy hosts: 
![image](https://user-images.githubusercontent.com/3808420/85298159-a470ae00-b49b-11ea-9034-bb20aaeaeb10.png)

**To Reproduce**
1. Install the service using the AWS Cloudformation template
2. Test the service for a few minutes until it goes down

**Expected behavior**
It shouldn't go down. 

**Screenshots**
![image](https://user-images.githubusercontent.com/3808420/85297422-a25a1f80-b49a-11ea-9da8-150225d23c37.png)

**Hosted or self hosted?:**
- self-hosted
- version: 1.9.0

**Comment by timgl** [comment]
Thanks for raising this (and big fans of Webiny!) In the ELB health-check, could you try changing the endpoint to `/health/` with trailing slash? Or alternatively allow 302 as 'healthy'

cc @fuziontech you had this issue the other day, did you come up with a better solution?

**Comment by SvenAlHamad** [comment]
Thanks @timgl for the quick reply -  We're actually looking to implement this into Webiny. The product seems to have everything we need, great job on that front. I know these initial bits with deployments can take time until they're polished out, we had similar problems on our end with Webiny :) 

I'll try the `health check` fix. I'm spinning up a new stack at the moment. Will report back shortly.

**Comment by fuziontech** [comment]
Spinning up a new stack should fix this. The cloudformation configs in s3
have been updated to hit the /_health/ endpoint which should convince the
ELB that the nodes are healthy, before they were hitting /_health and
getting redirected which was not 'healthy' to the ELB.

Restarting the stack is one of the easiest ways to fix this problem, but
you will lose data if you let the RDS instance get killed. I think the
easiest way to fix this without risking RDS is to update the health
endpoint in posthog to be `/_health` and `/_health/` so we don't redirect
and then have ECS / Cloudformation users update their installations with
the fix.

**Comment by SvenAlHamad** [comment]
Thanks @fuziontech  - I've just double-checked the CF template, but it's still pointing to `/_health. (cache?) 
https://deployments-posthog.s3-us-west-2.amazonaws.com/cloudformation/ecs/fargate/posthog.yaml

![image](https://user-images.githubusercontent.com/3808420/85302035-8ce7f400-b4a0-11ea-8e25-792dcf01a49a.png)

**Comment by fuziontech** [comment]
Woops.
https://github.com/PostHog/deployment/blob/master/aws/cloudformation/ecs/posthog.yaml#L411

Must have missed uploading that file to s3. One sec.

**Comment by SvenAlHamad** [comment]
Thanks! It seems to be working now (I manually uploaded the new template). 

I'll keep an eye on it during the day. I'll close the ticket for now. 

Looking forward to playing around with the system.

**Comment by fuziontech** [comment]
Just made sure the new version is deployed to s3. I need to automate this for the future.
