### ISSUE TITLE
Get AARRR into a dashboard for app.posthog.com

### ISSUE THREAD

**Issue by jamesefhawkins** [PostHog/posthog#1066]
We should track AARRR in one place so we can focus our growth engineering on improving these metrics. This is what we will need to raise a much larger round later in our life, but we need to start measuring these metrics now, and over the next few months, we need to start experimenting with them. 

## Acquisition

- We track sign ups already
- Our funnel functionality could provide this in a dashboard

Todo: create a signup funnel

## Activation

- The most important thing is that users start sending events
- Our funnel functionality could provide this in a dashboard

Todo: we need "received first event" as a custom event we could track

## Retention

- We currently track DAUs as a proxy for this + signups
- We need a better way of working out who comes back 

Todo: create a definitive graph for this

## Referral

- Sign ups through the platform to other users
- Initially, this would just be inside of the companies we deal with

Todo: create a graph of users signed up where they're not the first user in an account

## Revenue

- We need to build a payment flow of some sort first, then should track (i) overall revenue (ii) drop off in this funnel

Todo: put a payment flow in

**Comment by Twixes** [comment]
It seems we do have this dashboard.
