### ISSUE TITLE
Add prompt about losing form changes when editing an action

### ISSUE THREAD

**Issue by corywatilo** [PostHog/posthog#10677]
I added a tag to this action:

<img width="1388" alt="image" src="https://user-images.githubusercontent.com/154479/177860361-969bf93d-09d0-4608-8831-259f10d2ec8d.png">

But it's unclear if I need to click the save button - especially since there's no save button visible in the viewport on my 13" MBP.

I decided to click back to Data Management, assuming I'd get a prompt about losing changes if the tag hadn't already been saved automatically. To my horror, no such prompt appeared and I lost my tag. RIP.

This is especially inconsistent since the title/subtitle are both saved _outside_ of the event definition form. I had expected the same behavior with tags.

### Suggestions

- An additional save button (up next to Delete) might be nice, at least appearing when there are changes made to the form
- Figure out a way to move the save button up the page a bit
- Definitely: a JS dialog when trying to leave a form while in a dirty state

**Comment by clarkus** [comment]
This is the read view - descriptive attributes like the name, description, and tags (things that don't change the actually definition of the event) are available outside of edit views. This aligns to the same workflow we use for insights and other editable stuff. Note some older features don't have distinct read / edit views, and not all contain tags. 

Any change to a descriptive attribute should be reinforced by showing a toast notification when the attribute is successfully changed. The intent is to make things easily classifiable without requiring a user go through the full workflow for editing.
