### ISSUE TITLE
Better Activation (email)

### ISSUE THREAD

**Issue by EDsCODE** [PostHog/posthog#1067]
**Is your feature request related to a problem? Please describe.**
Improve user activation by automating follow-up emails

**Describe the solution you'd like**
If a user has dropped out of posthog before sending a single even, follow-up within 2-3 days and remind them to set it up/offer demo/guide them through the process

**Describe alternatives you've considered**
don't do it

**Additional context**

***Thank*** you for your feature request - we love each and every one!

**Comment by EDsCODE** [comment]
**Current Plan:**

Currently I've been implementing a management command that can be easily run using the [heroku scheduler](https://devcenter.heroku.com/articles/scheduler). This would be the most lightweight option as I would just setup some logic for sending a follow-up email if a team hasn't sent any events over some interval of time. The scheduler would then run `python manage.py follow_up_email` every few days or so. 

Opening the floor to other suggestions! @fuziontech @timgl (tagging because you guys had a few ideas on the call)

**Comment by Twixes** [comment]
Done.
