### ISSUE TITLE
Weird UX around enabling apps

### ISSUE THREAD

**Issue by corywatilo** [PostHog/posthog#10683]
When toggling on an app, there's a tooltip/dialog that confirms you want to enable it. At this point, I assume it's going to make it live.

But wait... this doesn't actually enable anything! Because after confirming, it opens a side pane with more options.

![2022-07-07 17 11 23](https://user-images.githubusercontent.com/154479/177872351-c73fc0a7-3f0c-41fd-a6f8-33792ce6476e.gif)

I propose killing the confirmation tooltip/dialog since it seems to be an unnecessary step that doesn't _actually_ do anything.

P.S. Verbiage in the tooltip/dialog references plugins, for which there is now a [PR](https://github.com/PostHog/posthog/pull/10682).

**Comment by yakkomajuri** [comment]
Yeah very annoying indeed - keeps bugging me too. 

Have had it in the backlog for a while to get rid of it - will do so when I get the chance
