### ISSUE TITLE
Email service for cohorts

### ISSUE THREAD

**Issue by EDsCODE** [PostHog/posthog#1068]
**Is your feature request related to a problem? Please describe.**
I want to be able to run a campaign that targets a cohort. If I'm using posthog to analyze metrics and notice that a cohort is lagging and could use focused messaging campaigns, it would be nice to run a campaign directly from posthog. 

**Describe the solution you'd like**
An email integration that would allow me to coordinate emails to cohorts from posthog

**Describe alternatives you've considered**

**Additional context**
This is a iceboxed ticket as there's not that much heavy usage on cohorts that would warrant such a feature

***Thank*** you for your feature request - we love each and every one!

**Comment by paolodamico** [comment]
While I think this could be useful, the idea seems pretty old. Should we close it for now? @EDsCODE
