### ISSUE TITLE
Sessions View Filtering with Tables & Charts 

### ISSUE THREAD

**Issue by PaoloC68** [PostHog/posthog#1069]
**Is your feature request related to a problem? Please describe.**
Currently the Sessions can be only filtered by day and cannot have other filtering parameters.
What I will find helpful is a way to perform search that expressed in human language should be:
This week sessions that had www.example.com/home.html as start point and had at least one event "checkout cart" and lasted at least 10 minutes. This should be available both as a total in charts for an overview and as a table to explore details of the relevant sessions

**Describe the solution you'd like**
The "Sessions" tab in the Trends section will then look practically like the "Actions & Events" one. The filters will also very much look alike, one could be able to filter sessions that contain a certain event. The filtering will also be possible over the values shown in the current session view. At the end a User should be able to get a chart based on the sum of the # of sessions 
as from a certain set of filters. This sum could be also shown as a breakdown.
When the user selects the table view the same data shown in the current session view will be exposed with the same capability of inline opening the events and actions that compose the single session.
The current "Average Session Length" will remain and gain the filtering capability, for example I could have a chart of the Average Session Length of sessions that contain a certain action or event. A breakdown of session length by event or action is also helpful.
The "Distribution of Session Length" instead makes sense as a breakdown parameter.

**Describe alternatives you've considered**
The alternative will be simply adding the filters in the current sessions view and allow them to be saved but I think that this will make the app less intuitive and consistent. All the saved tables and charts will so live in the same place.

**Thank you!**

**Comment by EDsCODE** [comment]
Thank you @PaoloC68 for keeping active on all the session related features of Posthog! I had opened #979 to remind myself to hash out the sessions functionality like you are saying here. These thoughts and details really help. Will try to get to these ASAP!

**Comment by paolodamico** [comment]
WE no longer have a sessions page, so closing.
