### ISSUE TITLE
Bug related to dashboards and Slack subscriptions feature

### ISSUE THREAD

**Issue by andyvan-ph** [PostHog/posthog#10709]
When subscribed to a dashboard, I thought it was just pulling insights at random – see [marketing Slack](https://posthog.slack.com/archives/C01FHN8DNN6/p1657526118317399) for an example.

But on close inspection, something else is happening.

This is the first insight it pulls into Slack:

<img width="592" alt="Screenshot 2022-07-11 at 09 22 16" src="https://user-images.githubusercontent.com/92976667/178220696-e4edf056-aa24-4624-ae29-6a3c3cb8d151.png">

However, this is my view of the dashboard, which features two completely different insights at the top. In my head, these are the insights I'd expect to see in the Slack subscription first.

![Screenshot 2022-07-11 at 09 23 55](https://user-images.githubusercontent.com/92976667/178220961-608329ce-8e64-4abe-a504-5e4bad606fba.png)

However, watch what happens when I reduce the width of the browser window on the dashboard...

https://user-images.githubusercontent.com/92976667/178221221-8d12cd12-9965-4784-a75c-e8f77aa2a97a.mov

The insight that's at the top of my side-by-side view is way down at the bottom, and the insights appear in the same order as they do in the Slack subscription.

I'm guessing this is a quirk around how we save / handle dashboard layouts? Either way, I imagine it's something other people will get confused by / find annoying.

**Comment by benjackwhite** [comment]
@marcushyett-ph if you remember we discussed exactly this and the fact that using the small layout us perhaps misleading as most people view and configure dashboards in the widescreen layout. 

This would be a super quick fix to make to use the widescreen layout instead (left to right priority) and my gut tells me this would be more expected.
