### ISSUE TITLE
New date filter option: "Since..."

### ISSUE THREAD

**Issue by corywatilo** [PostHog/posthog#10727]
## Is your feature request related to a problem?

I'd like to be able to save a query starting on a given date through _now_. I don't see a way to do this aside from manually editing my query to include the latest day.

<img width="478" alt="image" src="https://user-images.githubusercontent.com/154479/178460876-7f26b996-e69f-4fcc-b5e4-8fb74fb9aba3.png">

## Describe the solution you'd like

A filter option for "Since" or "After..." would do the trick.

H3ap has an option called, "Date to now" which is a little more clear since it's obvious it infers including the first set date.

<img width="450" alt="image" src="https://user-images.githubusercontent.com/154479/178461106-6e1ea59a-1d27-4fdb-bb1f-b68d8f584b22.png">

**Comment by kappa90** [comment]
As per the recent changes (#10462), we now have today as the default date when selecting `Custom fixed date range`.

Maybe the option is just not clear enough?

<img width="449" alt="image" src="https://user-images.githubusercontent.com/7335343/179509694-78fc4dbd-d47d-4b9a-ae56-be70b2160bdf.png">

**Comment by corywatilo** [comment]
The issue is I want the end date to _always_ be the _current date_ in a saved insight.

As far as I can tell, I'd have to update the saved insight every day to include the latest date, unless I'm just missing something here?

**Comment by kappa90** [comment]
I see what you mean now, it's a rolling date range that is set to a specific date 👌 

Let me try to add that option!

**Comment by clarkus** [comment]
The closest option we have to this is the year to date relative preset. In this case it's implied it's the first day of the year through the current date. This new option is basically a mixed mode where the range is relative but with a fixed starting date. @corywatilo do you have any sense of how critical it is for a user to browse for a date? Would it be acceptable to just enter a date manually? 

Here's a quick illustration to demonstrate a potential workflow - pick the "date to now" option and the user is shown a calendar picker biased towards picking a single date. The tricky bit here is that it's very much the same workflow as picking a fixed time range, just with a relative / rolling end date. How critical is it to represent the full range of time given that the end date is relative?

<img width="582" alt="Screen Shot 2022-07-19 at 12 33 18 PM" src="https://user-images.githubusercontent.com/254612/179833533-aad6a212-2149-49e1-b74c-aece23763eef.png">

**Comment by corywatilo** [comment]
No strong preference but I _think_ the use case is "I want to analyze a recent change and how it's performed since being implemented, thus the date picker defaulting to the current month seems the most elegant:

![2022-07-19 16 17 40](https://user-images.githubusercontent.com/154479/179840602-fe94801c-0a01-4b95-9624-1fa2de04c782.gif)

**Comment by mariusandra** [comment]
I worked on the date filter to resolve https://github.com/PostHog/posthog/issues/9664 and would like to implement this as well. With "date to now", "last X [unit]" and "date range", we have all possible date ranges selectable.

@clarkus is [what's in this comment](https://github.com/PostHog/posthog/issues/10727#issuecomment-1189476056) the latest design? Is there anything missing from the rest of the calendar, or is the interaction perfect as it is? Should I add/remove any of the other options? I'd gladly finish off whatever discrepancies remain between the implementation and the design.

**Comment by mariusandra** [comment]
Also, is [this](https://www.figma.com/file/PA3RZmpBykvBW1du69Kk0A/Prototypes?node-id=848%3A2344) the last look for the custom fixed period option?

<img width="826" alt="image" src="https://user-images.githubusercontent.com/53387/186949061-b0c1d586-6b0f-4493-8db4-6bd74a9af9cf.png">

I'd be happy to improve this as well next week. Just want to make sure I don't build the wrong thing :).
