### ISSUE TITLE
Dashboard event selectors with CSS class

### ISSUE THREAD

**Issue by rksm** [PostHog/posthog#1072]
Related to https://github.com/PostHog/posthog/issues/963 but since related code exists this seems to be a bug.

**Describe the bug**
I’m trying to create an “action from event”. I have a click event and the posthog dashboards reports markup like

```
<div id="app">
    <div class="titlebar">
        <div>
            <div class="button">
...
```

The suggested selector in that case is [id="app"] > div > div > div . This seems pretty ambiguous. Reading the selector matching code it looks like css class selector syntax is sort of supported. However, when I change the selector to [id="app"] > div > div > div.button and press “Save action” the (formerly auto detected) events disappear.

**To Reproduce**

**Expected behavior**
Filter events correctly based on CSS class.

https://github.com/PostHog/posthog/blob/1.9.0/posthog/models/event.py#L62 seems to deal with CSS class selectors so I would expect this to work.

**Screenshots**
![posthog-filter](https://user-images.githubusercontent.com/467450/85415195-51ffc200-b56d-11ea-9f5f-4b713327e82d.gif)

**Hosted or self hosted?:**
- self-hosted
- (if self-hosted) what version?
1.9.0, AWS ECS

**Additional context**

**Comment by paolodamico** [comment]
We now prioritize custom attributes that you've set in project settings.
