### ISSUE TITLE
Add keyboard shortcut to toggle toolbar

### ISSUE THREAD

**Issue by camerondeleone** [PostHog/posthog#10763]
## Is your feature request related to a problem?

The toolbar is amazing. But it can also be very annoying, and 99% of the time I'm on our site, I'm not trying to use the toolbar.

## Describe the solution you'd like

1. Option to have it show _or_ hide by default
2. keyboard (or some other mechanism) shortcut to toggle show/hide

## Describe alternatives you've considered

Close it. every. single. time

**Comment by camerondeleone** [comment]
Leaving this here since I think it would have to be a per-user config set in the product UI (eg on the toolbar page), but feel free to move if that feels more appropriate

**Comment by clarkus** [comment]
> The toolbar is amazing. But it can also be very annoying, and 99% of the time I'm on our site, I'm not trying to use the toolbar.

To clarify, you're saying it's frustrating to have to deal with the toolbar being shown when you're not needing to use it? It's in the way and you have move it / close it so it doesn't obstruct the underlying website/product. So you're wanting an easier mechanism for hiding/showing it, and possibly a less intrusive display when it's active? Is that accurate?
