### ISSUE TITLE
wildcard domain not working for my site (iFrame)

### ISSUE THREAD

**Issue by kovilsingh** [PostHog/posthog#10767]
## Bug description

I am trying to add a wildcard domain https://*.onbookee.com as an authorised URL but I am getting an error of 'invalid domain'.

How to reproduce

1.Add the above URL to authorised URL.

Environment

-  PostHog Cloud

**Comment by mariusandra** [comment]
cc @pauldambra

**Comment by pauldambra** [comment]
I've confirmed this is fixed for me in PostHog cloud @kovilsingh. Thanks for letting us know!

**Comment by kovilsingh** [comment]
thanks @pauldambra and team posthog for a quick resolution on this!! it has been fixed, I have been able to add my wildcard domain.
