### ISSUE TITLE
E-Mail-Logins are case-sensitive

### ISSUE THREAD

**Issue by bhelm** [PostHog/posthog#10773]
## Bug description
After wondering why i can't login and can't use the "forgot password" function, i pinned it down to the Login-E-Mail to be case-sensitive in the Posthog backend.

This is counter-intuitive, as most systems thread user logins as case-insensitive. Having a case-sensitive login name requires the user to remember the casing. For E-Mail-Addresses, this is especially unexpected as E-Mails are also [processed in a case-insensitive](https://stackoverflow.com/a/9808332/1863432) manner. 
I also see no advantage in having case-sensitive E-Mail-Logins.

**Signing in with correct casing works**
![image](https://user-images.githubusercontent.com/769791/178775860-8ef988d7-7012-4583-bc6c-cd01840f7775.png)
![image](https://user-images.githubusercontent.com/769791/178776030-55cedc2f-b021-4d0e-820f-31a51643022e.png)

**with different casing, it does not work**
![image](https://user-images.githubusercontent.com/769791/178775901-f67b64ee-5a47-4b5e-afce-36a9f58de1b4.png)
![image](https://user-images.githubusercontent.com/769791/178776771-5be91256-8164-458a-9473-5f6e5aae7c98.png)

## How to reproduce
Try to sign in with a different casing than you used for registering

## Environment

- PostHog Cloud

Thank You

**Comment by thetarunkochar** [comment]
Hey Bernd,

I have resolved the issue and raised a PR #12005  for the same.

https://github.com/PostHog/posthog/pull/12005

Feedback would be appreciated.

Thanks
