### ISSUE TITLE
No matching events for action defined with Toolbar

### ISSUE THREAD

**Issue by corywatilo** [PostHog/posthog#10796]
## Bug description

I'm trying to define an action with the Toolbar but when saving the action with the DOM element PostHog suggests, it returns no matching events.

<img width="424" alt="image" src="https://user-images.githubusercontent.com/154479/178999254-b7cee944-d4c9-4953-b43e-0b5cc7c6cbdf.png">

<img width="672" alt="image" src="https://user-images.githubusercontent.com/154479/178999300-b2509e24-1789-403e-8978-a0b21c68bfb8.png">

<img width="1387" alt="image" src="https://user-images.githubusercontent.com/154479/178999324-6d01a4f1-ca51-45f6-889f-841432914140.png">

I thought it might be a delay with ingestion, but it's been ~12 hours since I originally tried this, so I'm thinking it's not that...

## How to reproduce

1. Visit posthog.com with Toolbar
2. Select one of the slick-slider tabs on the homepage and create an action
3. Visit Data Management for the defined action and notice how it doesn't match any events

(It's using `nth-child` for the specific `<li>` so it _should_ be matching at least based on that...)

**Comment by benjackwhite** [comment]
I've had a couple of customer support queries that might be the same issue. They click "Create Action from this event" and end up with no results. I wonder if we are not using the value correctly?
