### ISSUE TITLE
Tracing / Observability

### ISSUE THREAD

**Issue by weyert** [PostHog/posthog#10793]
I was playing around with Posthog as part of preparation work for a talk I am doing about OpenSLO, OpenFeature and OpenTelemetry and I was wondering if PH would be open to a contribution that adds supports for tracing?

I would like to suggest to use the standard for named Opentelemetry (opentelemetry.io) and it comes with Django instrumentation and Kafka (or auto-instrumentation), see:
https://github.com/open-telemetry/opentelemetry-python-contrib/tree/main/instrumentation/opentelemetry-instrumentation-django
The standard is backed  by major players such as built-in support in .NET Core (Microsoft), support by Google, and Amazon.

In theory it would support sending traces to wide variety of vendors, e.g. Google Trace, AWS XRay, Jaeger, Datadog etc. For this you could use `otel-collector` to offer most flexibility which can be a sidecar in  Kubernetes and then PH app would send it traces/metrics/logs via the OTLP protocol to the collector  which then export them accordingly, e.g. this is the list of supported exporters for collector:
https://opentelemetry.io/registry/?component=exporter&language=collector

for Python itself:
https://opentelemetry.io/registry/?component=exporter&language=python

Would you be open to this?

You might wonder why tracing, it can  be pretty useful when debugging things, see also: https://incident.io/blog/tracing

**Comment by guidoiaquinti** [comment]
Yes sure, we appreciate contributions!

**Comment by pauldambra** [comment]
🤣 Came here to tag @guidoiaquinti but he was already here
