### ISSUE TITLE
Enhancement: Feature Flag table doesn't wrap content or tags

### ISSUE THREAD

**Issue by joethreepwood** [PostHog/posthog#10813]
## Is your feature request related to a problem?

Even on a 4k screen, the tags for the first FF in this table are being trimmed off. Presumably if there was a third or fourth entry, it wouldn't be visible.

<img width="2478" alt="Screenshot 2022-07-15 at 10 24 04" src="https://user-images.githubusercontent.com/84011561/179195116-986f4b71-96f0-4fc9-97e6-bdb3731ea7a8.png">

## Describe the solution you'd like

Probably best if it wraps the content.

**Comment by pauldambra** [comment]
This behaviour has changed since report

![2022-08-24 08 26 40](https://user-images.githubusercontent.com/984817/186357406-1afc1788-3a86-44f7-9ff0-1a7497a24945.gif)
