### ISSUE TITLE
Broken plugins

### ISSUE THREAD

**Issue by yakkomajuri** [PostHog/posthog#10821]
List of plugins with some sort of issue:

**[Customer.io](https://github.com/PostHog/customerio-plugin)**

We worked on this one a lot but customers are still reporting issues. Need to investigate.

UPDATE: Known issues addressed

**[PagerDuty](https://github.com/PostHog/posthog-pagerduty-plugin)**

Completely broken after we implemented short insight IDs

UPDATE: Hidden away on Cloud

**Comment by joethreepwood** [comment]
It sounds like it's worth moving at least PagerDuty down off the site for a bit?

**Comment by yakkomajuri** [comment]
I've hidden the PagerDuty plugin on Cloud and addressed the customer.io plugin issues

**Comment by joethreepwood** [comment]
Ok, good to know. If you can ping me or update here when it's restored, I'll put it back on the site etc.

**Comment by pjhul** [comment]
PagerDuty plugin is now back up and running. Closing this as it seems both apps are working for the time being.
