### ISSUE TITLE
Heatmaps not showing clicks on some PostHog homepage elements

### ISSUE THREAD

**Issue by andyvan-ph** [PostHog/posthog#10838]
## Bug description

Some elements of the PostHog homepage don't register clicks on Heatmap, particularly the 'Try PostHog' and 'Book a Demo' buttons. See below:

![Screenshot 2022-07-18 at 09 25 17](https://user-images.githubusercontent.com/92976667/179473762-03286fae-e964-426e-9b4f-6083cbdcfc87.png)

## How to reproduce

1. Open PostHog.com
2. Load toolbar
3. Click on Heatmap

## Environment

- [x] PostHog Cloud
- [ ] self-hosted PostHog (ClickHouse-based), version/commit: _please provide_
- [ ] self-hosted PostHog (Postgres-based, legacy), version/commit: _please provide_

## Additional context

I created Actions for these buttons to confirm they are being tracked in the product

**Comment by pauldambra** [comment]
API response can be found here: https://posthog.slack.com/archives/C02E3BKC78F/p1658133510110109?thread_ts=1658132775.558639&cid=C02E3BKC78F

The console has lots of empty element errors when loading the heatmap

![Screenshot 2022-07-18 at 09 37 17](https://user-images.githubusercontent.com/984817/179474613-18f256fd-9f90-4ec9-a91a-eeb05fb1784e.png)

**Comment by jwei98** [comment]
Hello! We just started using Posthog Cloud, and are running into a similar issue trying to use Heatmaps (some elements do not show up on the heatmap). Same console errors as well. Any advice / resolution?

Update: Only seems to happen when using toolbar in production. When using against localhost, heatmap correctly shows elements

**Comment by NorhanMostafa94** [comment]
any updates about this issue, it happens on both production and localhost too

**Comment by pauldambra** [comment]
👋 @jwei98 @NorhanMostafa94 the heatmap doesn't show all clicks.

It loads the top 100 elements but they may nest so doesn't necessarily highlight 100 elements on the page. 

Do you think that covers your issues?

**Comment by NorhanMostafa94** [comment]
@pauldambra Thanks for response, but sometimes it doesn't count correctly and all time it returns "Found empty selector"

**Comment by pauldambra** [comment]
Hey @NorhanMostafa94 👋 

Is the site publicly visible? Do you use PostHog cloud or self-hosted?

In case it helps me investigate: how do you know it isn't counting correctly?

**Comment by pauldambra** [comment]
See Zendesk ticket https://posthoghelp.zendesk.com/agent/tickets/1502 (moved to PostHog: https://us.posthog.com/project/2/support/tickets/5052) for a great reproduction of this issue

In that case the login button has a href to something like `https://mydomain.io/login/-aUUID` the selector for the href includes the URL and so can never match any more than one click. I.e. will only match a click if the UUID for the logged in user is in the results from the API

If there are more cases where there are very unique elements and we include that in the selector then we'll have the same problem.

**Comment by pauldambra** [comment]
@andyvan-ph with the change to not link by URL and to let you load more is this still happening for you?

@NorhanMostafa94 we released some changes this week that might resolve this for you, would be interesting to hear if it does. (or not!)

**Comment by andyvan-ph** [comment]
Still seeing some page elements you'd expect to see clicks not showing any. Also doesn't seem to registering clicks on lots of stuff around the blog. Not sure if that's the same problem, or a different one, though! :(

**Comment by pauldambra** [comment]
> Not sure if that's the same problem, or a different one, though! :(

There's definitely more than one problem 😅

**Comment by andyvan-ph** [comment]
@pauldambra Can I close this? Just having a spring clean of my open issues! 😅

**Comment by pauldambra** [comment]
Yep, it should show more than it did in the past but we know why.
