### ISSUE TITLE
[Recordings] Get console logs out of beta

### ISSUE THREAD

**Issue by rcmarron** [PostHog/posthog#10832]
## Is your feature request related to a problem?

We have a beta console log feature today, but it needs a bit of work to get it out of beta.

## Describe the solution you'd like

* Support log formatting features (support more of the [logs api](https://developer.mozilla.org/en-US/docs/Web/API/console#examples))
    * Objects (multiple)
    * Styling
    * String substitutions
* Indicate the play position in console logs, similar to events.
* Today’s list only supports 150 log events (because it doesn't do virtualization to support variable line height). It should support more.
* Indicate which window/tab a console log is coming from. Allow users to filter to only a specific window
* Show logs before the entire recording is loaded (this is hard because of different windows buffering in a non-linear way...)
* Settings for turning console logs on/off
* Search console logs
* Filter by log/warning/error
* A story for sanitizing PII from logs
* Show console logs on the seek bar if it's the open tab

**Comment by clarkus** [comment]
> Show console logs on the seek bar if it's the open tab

Should this be all logs or just those matching the filter criteria? If we're seeking parity with the event viewer, we'd only show those that match some filter conditions.
