### ISSUE TITLE
Toast issue in Toolbar

### ISSUE THREAD

**Issue by corywatilo** [PostHog/posthog#10846]
After saving actions, it looks like a toast notification shows up, but it's hard to read. And sometimes doesn't ever go away.

<img width="1511" alt="image" src="https://user-images.githubusercontent.com/154479/179528927-48f3e211-e987-4c35-af2d-7ec658de7eff.png">

## Repro

Define a couple actions in a row using the Inspect tool

**Comment by pauldambra** [comment]
<img width="579" alt="Screenshot 2022-08-24 at 20 55 57" src="https://user-images.githubusercontent.com/984817/186512279-ebd734f4-50fd-418d-88a5-a977d19f3112.png">

current theory: css variables assigned to :root are not available to the toolbar in its shadow root

**Comment by pauldambra** [comment]
Hmmm.. toolbar.css opens

```
@charset "UTF-8";:root {
    --toastify-color-light: #fff;
    --toastify-color-dark: #121212;
```


the missing new line might be the fault there

**Comment by pauldambra** [comment]
built CSS for toolbar declares root variables twice... once from `/* node_modules/react-toastify/dist/ReactToastify.css */` and once from `/* frontend/src/styles/global.scss */`
