### ISSUE TITLE
Feature request: Install URL for each app

### ISSUE THREAD

**Issue by pjhul** [PostHog/posthog#10858]
## Problem
I'm currently working on updating our apps documentation, and as it is right now, if a user finds an app on our website and then wants to install it on PostHog, the process is quite cumbersome. 

Currently, we instruct the user to:
1. Navigate to https://app.posthog.com
2. Click on the apps tab
3. _Search_ for the specific app they were just viewing
4. Install and configure that app

This requires a huge amount of user effort and leaves numerous points where they can drop off along the way.

## Requested solution
Create a route within the dashboard that's specific to each app. Something along the lines of `/project/apps/:app_name` or `/project/apps/:app_id`, which brings open the slide-over for that specific app when a user navigates there. 

This would allow us to then create an 'Install now' CTA for each app on the website that would take a user directly to the app they were viewing,  which would be amazing!

**Comment by neilkakkar** [comment]
I implemented something like this for the universal search bar, have a play around with that:

https://app.posthog.com/project/apps?tab=installed&name=Release%20Tracker

It's not fully where you want it to be, simply because apps don't have their own pages because it hasn't yet made sense to have them.

**Comment by pjhul** [comment]
Got it, thanks! That will still make a big difference in the meantime. I'll close this issue since this solves my problem for now, but definitely +1 on eventually giving each app it's own page, I think from the UX side that would be awesome!
