### ISSUE TITLE
Apps: Improving the alert emails we send

### ISSUE THREAD

**Issue by joethreepwood** [PostHog/posthog#10904]
## Is your feature request related to a problem?

I'm not a big fan of the emails we send for app errors. Things I'd like to improve:

- Design is very basic
- Subject line is very long and will be clipped
- Soften the tone to make it clearer for non-engineer users (like me)
- Give users a better secondary CTA which sends them to the docs for a specific app

Currently they look like this. 
<img width="922" alt="Screenshot 2022-07-20 at 17 31 21" src="https://user-images.githubusercontent.com/84011561/180035153-88f0667d-4e3b-460b-afd8-c7dfd8829023.png">

## Describe the solution you'd like

I think the following text is a step in the right direction, though there may be variations needed. 

```
SUBJECT: [Alert] Calendly Event Enricher has been disabled

That isn't supposed to happen...

We've automatically disabled the [Calendly Event Enricher] app on your [PostHog App + Website] project because the `setupPlugin` function encountered the following error:

`Error: Unable to access ZenDesk API's for posthoghelp`

If this is the first time you've seen the error, check the logs and re-enable the app from the Apps section of your project. If it persists, please [check the Calendly Event Enricher docs] for more help. 

BUTTON: Go to Apps
```

I'd love to also update the design to closer match our marketing emails, with centralized H1 and potentially a hedgehog image to make it look better. I'd also hope that we can direct users to the the specific app they need to re-enable, as well as the specific app docs via the CTAs.

## Additional context

Tagging @Twixes - who I believe worked on building out these original emails?

Also, I'm doing an issue because it feels the most effective effort to impact ration but I'd love to know how if it would have been possible to PR this myself in the future. I wasn't able to see this copy to edit in the repo.

**Comment by joethreepwood** [comment]
@Twixes Just following up on this, as I have a moment. Is there anywhere I can see a full list of the emails we send through the app? I'd love to take them away and come back with some straight copy improvements.

**Comment by Twixes** [comment]
You can find the templates in https://github.com/PostHog/posthog/tree/master/posthog/templates/email. @joethreepwood

**Comment by joethreepwood** [comment]
Closing as I'll now make the changes directly. 

![horatio-csi](https://user-images.githubusercontent.com/84011561/184663796-b710f17a-5090-42a4-a9ad-3e47218a701c.gif)
