### ISSUE TITLE
Wrong protocol in session recording

### ISSUE THREAD

**Issue by jandolezal71** [PostHog/posthog#10903]
## Bug description

I have self hosted Posthog 1.37.1 and activated session recording. Sessions are recorded and when i'll click on some session i will get an error, because request to `/api/projects/1/session_recordings/{id}/snapshots/?offset=20&limit=20` will fail, because my posthog domain is on HTTPS but this request is to HTTP, i don't know why.

These are my envs:
```
SITE_URL=https://mydomain.com
INGESTION_SITE_URL=https://mydomain.com
DISABLE_SECURE_SSL_REDIRECT=true
SECURE_COOKIES=true
```

I access posthog on https://mydomain.com , but request to get session recording `/api/projects/1/session_recordings/{id}/snapshots/` will return http protocol in `next` key. Why? What can i override to put same protocol as web?

![image](https://user-images.githubusercontent.com/46811197/180020301-e6283c3a-eca0-43e9-8e1b-ebe2d179934c.png)
![image](https://user-images.githubusercontent.com/46811197/180020422-faf13254-ac33-48f3-ae74-3cc70bfa0e8e.png)
![image](https://user-images.githubusercontent.com/46811197/180020652-abf25111-6cb9-4f48-85f6-3d8ad529742f.png)

## Environment

- [ ] PostHog Cloud
- [x] self-hosted PostHog (ClickHouse-based), version/commit: `1.37.1`
- [ ] self-hosted PostHog (Postgres-based, legacy), version/commit: _please provide_

**Comment by jandolezal71** [comment]
Sometimes `snapshots` request returns `next: null` and in this case everything works as expected.

![image](https://user-images.githubusercontent.com/46811197/180168250-417f1521-1e1b-4139-bef9-def5f95361b4.png)

**Comment by benjackwhite** [comment]
This does like a more generic bug in that `next` urls are not taking into consideration the configured `SITE_URL` . Should be fixable...

**Comment by pauldambra** [comment]
This is so old I'll assume it's fixed. Sorry you didn't get a response sooner. Do let us know if you're still having issues
