### ISSUE TITLE
Dashboard not tracking DAUs

### ISSUE THREAD

**Issue by topherPedersen** [PostHog/posthog#1091]
**Describe the bug**

The PostHog Analytics Default Dashboard is not tracking daily active users.

**To Reproduce**
1.  Use the React-Native library to track manually defined events.
2.  Disable auto-capture (as this can cause the app to crash in certain circumstances)
3.  Make sure to manually define some actions
4. Use the app
5. Log in to the Dashboard, confirm no daily active users listed

**Expected behavior**

The DAU count in the default should display at least one active user if you are opening the app yourself and performing actions.

**Screenshots**

![NoDAU](https://user-images.githubusercontent.com/12384786/85664329-bc088c00-b67f-11ea-801c-87dc4c1c350d.png)

**Hosted or self hosted?:**
- hosted/self-hosted
- (if self-hosted) what version?

Using the hosted product

**Additional context**

I'm currently using the React-Native library and tracking events manually because the auto-capture feature isn't compatible with a critical third party SDK I'm using in my app (auto-capture crashes the app when it's enabled and I attempt to use the unrelated third party SDK). The core functionality appears to be working, but dashboard is broken and isn't displaying any active users even though at least one should be showing up.

**Comment by timgl** [comment]
Thanks for raising this! I bet the reason is because for that "DAU" dashboard item we track `$pageviews`, which obviously don't exist when you integrate with the app. If you click on "Daily Active Users", you should be able to change `$pageview` into `$screen`, at which point this should work.

There are a couple of other places where we assume `$pageview` gets sent. We should make sure that we handle the case where people only sent mobile event properly.

**Comment by topherPedersen** [comment]
Thanks Tim! Your solution worked great

**Comment by mariusandra** [comment]
@topherPedersen thanks for raising this issue! I do have a question regarding one thing you said: "Disable auto-capture (as this can cause the app to crash in certain circumstances)". 

Are these crashes due to the way your app works... or are they something that seems to be broken in the library? In any case having the library crash your app is definitely something we want to avoid. Can you shine some light on the crashes and is there anything we can do to fix them?

**Comment by topherPedersen** [comment]
Marius,

I'm using Plaid so users can link their bank accounts to my React-Native
app. So whenever a user clicks on the "link bank account" button in my app,
which fires up the Plaid SDK, the app crashes. The simple fix for me was to
disable all of the auto-capture stuff and just track everything manually
which isn't a problem for me. Since Apple's App Review board rejected my
app, I am only developing for Android at the moment. So I don't know if
this is an issue on iOS or not. The library taps into native Android code,
so I'm assuming that's where things are probably breaking.

In my MainApplication.java file I import the following libraries:

// Import Plaid Link React-Native SDK
// (Allows users to link their bank accounts via the Plaid API)
import com.plaid.PlaidPackage;
import com.plaid.link.Plaid;

And then a little further down into the MainApplication.java file I add the
packages manually:

        @Override
        protected List<ReactPackage> getPackages() {
          @SuppressWarnings("UnnecessaryLocalVariable")
          List<ReactPackage> packages = new PackageList(this).getPackages();
          // Packages that cannot be autolinked yet can be added manually
here, for example:
          // packages.add(new MyReactNativePackage());

          // Add Plaid Link Package
          packages.add(new PlaidPackage());

          return packages;
        }

From a user's perspective I don't necessarily care about the auto-capture
stuff. It's sort of just a nice to have, and not all that important. It
only took me an afternoon to get PostHog up and running, installed in my
app, and pushed out to the Google Play Store.

I would however like to be able to track Weekly Active Users and Monthly
Active Users. I would put that ahead of the auto-capture stuff.

Anyway, really happy with PostHog and glad you guys are working on it! If
you need to use me as a guinea pig for anything React-Native related, feel
free to email anytime.

Best regards,

Chris Pedersen
chrispedatx@gmail.com
chris@topherpedersen.com
(469) 261-0727

**Comment by topherPedersen** [comment]
Forgot to include... Maybe the Plaid SDK is crashing things on purpose
because they don't want developers stealing people's credentials? It could
be a security measure?

**Comment by topherPedersen** [comment]
Wait and another thing... I used Heap.io in the past and that did not cause
the app to crash when using auto-capture and the Plaid SDK, so it's not a
security measure. Not sure

**Comment by topherPedersen** [comment]
*so maybe it's not a security measure

**Comment by topherPedersen** [comment]
Ugh sorry! Okay so I used heap.io with a different unrelated project that
did not use Plaid. Sorry for all the noise.

**Comment by timgl** [comment]
@mariusandra Is there anything left to do here? Is it worth checking this in combination with Plaid or should we just add a warning to the docs?

**Comment by Twixes** [comment]
I'll close this, but obviously if you have any issues or feedback, we'd love to hear from you @topherPedersen
