### ISSUE TITLE
Scrolling issue with toolbar

### ISSUE THREAD

**Issue by jamesefhawkins** [PostHog/posthog#1093]
**Describe the bug**
![Screenshot 2020-06-25 at 14 19 06](https://user-images.githubusercontent.com/47497682/85727426-e7768f80-b6ee-11ea-9c60-eb5138486e43.png)

**To Reproduce**
1. Scroll to bottom of posthog.com
2. Scroll back up
3. Toolbar looks weird

**Expected behavior**

The overlays shouldn't get stuck in a weird position

**Screenshots**
Attached

@mariusandra FYI

**Comment by mariusandra** [comment]
Should be fixed in #1095
