### ISSUE TITLE
Layout issue with docked toolbar

### ISSUE THREAD

**Issue by jamesefhawkins** [PostHog/posthog#1094]
**Describe the bug**
![Screenshot 2020-06-25 at 14 23 00](https://user-images.githubusercontent.com/47497682/85728041-74214d80-b6ef-11ea-9bfc-c04771b658e3.png)
![Screenshot 2020-06-25 at 14 23 06](https://user-images.githubusercontent.com/47497682/85728059-771c3e00-b6ef-11ea-90c3-455ddec7a22d.png)

**To Reproduce**
1. Go to posthog.com
2. Open toolbar docked
3. scroll to the right

**Expected behavior**
It should appear next to the main page

**Screenshots**

Attached

**Hosted or self hosted?:**
- hosted/self-hosted
- (if self-hosted) what version?

**Additional context**

fyi @mariusandra

**Comment by mariusandra** [comment]
This should also be fixed with #1095
