### ISSUE TITLE
Funnel insights not saving correctly

### ISSUE THREAD

**Issue by andyvan-ph** [PostHog/posthog#10965]
## Bug description

Whenever I try to create a Funnel insight, the filters I apply to the first step don't save correctly. See video:

https://user-images.githubusercontent.com/92976667/180964372-c819206b-887a-4406-80a6-7c5c0094fe02.mov

## How to reproduce

1. Create a funnel insight
2. Add a filter to step 1 and add a step 2, click save
3. Click edit and check if filter on step 1 is present

## Environment

- [x] PostHog Cloud
- [ ] self-hosted PostHog (ClickHouse-based), version/commit: _please provide_
- [ ] self-hosted PostHog (Postgres-based, legacy), version/commit: _please provide_

**Comment by andyvan-ph** [comment]
Update: Logging in and out again seemed to fix this, but the product was otherwise working fine so not sure it was a timeout situation. Worth invesitgating further.

**Comment by mikob** [comment]
Having this same issue when making an experiment. The filter for the first pageview wasn't saving: 
![image](https://user-images.githubusercontent.com/492864/190022519-7a02de25-d41a-4d4a-afca-141bd73e73b2.png)

I logged out and back in as @andyvan-ph suggested and it seems to be saving now, except not in the experiment goal summary (doesn't show path name in conversion goal step 1):
![image](https://user-images.githubusercontent.com/492864/190022630-0fe37ae7-6d1f-46f7-9d1b-08afdbf5387d.png)
