### ISSUE TITLE
Add 'is not set' to property operators

### ISSUE THREAD

**Issue by timgl** [PostHog/posthog#1097]
**Is your feature request related to a problem? Please describe.**

I want to know if a property is not set (instead of set)

**Describe the solution you'd like**

Add 'is not set' to property operators

**Describe alternatives you've considered**

-

**Additional context**

***Thank*** you for your feature request - we love each and every one!

**Comment by Twixes** [comment]
Picking this one up.

**Comment by timgl** [comment]
Done!
