### ISSUE TITLE
Universal filtering pattern for data tables and other list types

### ISSUE THREAD

**Issue by clarkus** [PostHog/posthog#11017]
## Is your feature request related to a problem?

Our product is made up of a few archetypical page types - one of these is a list view. Most often these views are using data table or card-style components to summarize each item in the list. The attributes that describe each item in the list are used for sorting and filtering the list to make specific items easier to find. Currently our sorting and filtering patterns are inconsistent. The goal of this issue is to make those filters consistent for all list types. 

## Describe the solution you'd like

A reusable filtering pattern for list views. This pattern would prioritize the most valuable / frequently used attribute filters for each list view. There are going to be some filters that are sufficiently complex that they won't scale to be displayed prominently above a list view. These filters are still valuable, so they should be included via some secondary interface that provides the space necessary to complete the filters when they're needed.

These filters are closely related to export and configuration options, so they should be placed adjacent to those controls. As part of this solution we could also standardize the placement of export and configuration controls. 

## Describe alternatives you've considered

I feel like we've implemented all the alternatives at this point - ad hoc filtering patterns mostly focused on fuzzy keyword searching. 

## Additional context

@joethreepwood described this well in https://github.com/PostHog/posthog/issues/10988 but the problem applies more broadly. The solution would need to be adjusted for each list. As an example, we could prioritize filtering a project membership table by roles, an insight list by types, or an experiment list by status. 

This concept recently came up during projects for recordings and data management. Here are some example assets from recordings (not in production yet) that illustrate prominent filters along with secondary filters in a modal. 

The recordings list can be filtered quickly using event matching, time ranges, and recording duration. Secondarily, a user can use more complex filters to match complex event filters, cohorts, or person properties. 

![Recordings list - biased towards binging](https://user-images.githubusercontent.com/254612/181299115-1d373ffc-acab-4287-8b03-c4c060ef6ea6.png)

![list](https://user-images.githubusercontent.com/254612/181299159-deccad54-9a9b-4355-8151-8a64e65bf0ba.png)

**Comment by macobo** [comment]
Related: https://github.com/PostHog/posthog/issues/7963

IMO a key point we're missing right now is being able to "pivot" from one view to another while retaining filters in a sane way.
