### ISSUE TITLE
Selecting and deselecting filters in Events is buggy

### ISSUE THREAD

**Issue by benjackwhite** [PostHog/posthog#11014]
## Bug description

Sometimes when you select a filter, then deselect it and select a different one, the deselected filter reappears. You can even get into a state where the deselected filter is no longer selectable...

Load a page with filters e.g. [here](https://app.posthog.com/events?properties=%5B%7B%22key%22%3A%22%24lib%22%2C%22value%22%3A%5B%22js%22%5D%2C%22operator%22%3A%22exact%22%2C%22type%22%3A%22event%22%7D%5D)

https://user-images.githubusercontent.com/2536520/181296885-4b4a2569-eb84-4fc9-ad3a-6af86f97dcda.mov

## How to reproduce

1. Go to /Events
3. Select a property value to add it to the filters
4. **Reload the page**
5. Remove that filter
6. Select a different filter
7. 🐛 - The old filter might have reappeared
8. Remove all of them
9. 🐛 - Adding a different one might not work

## Environment
- [x] PostHog Cloud (Tested on app. and playground.
- [ ] self-hosted PostHog (ClickHouse-based), version/commit: _please provide_
- [ ] self-hosted PostHog (Postgres-based, legacy), version/commit: _please provide_

**Comment by seunexplicit** [comment]
Hi @benjackwhite is this issue still valid? havn't been able to reproduce the issue following the outlined steps

**Comment by benjackwhite** [comment]
[](url)
