### ISSUE TITLE
Paths: Add path cleaning rule dialogue overflows the screen and is inaccesible

### ISSUE THREAD

**Issue by pjhul** [PostHog/posthog#11032]
## Bug description

When trying to add Path cleaning rules directly to a paths insight, the dialogue boxes overflows off the bottom of the screen and can't be accessed. 

![Screenshot_20220728_113139](https://user-images.githubusercontent.com/39424187/181612263-3da8e6d8-ff98-47ba-a4a9-0c8b88615dde.png)

## Environment

- [x] PostHog Cloud
- [ ] self-hosted PostHog (ClickHouse-based), version/commit: _please provide_
- [ ] self-hosted PostHog (Postgres-based, legacy), version/commit: _please provide_

**Comment by anjola-adeuyi** [comment]
Hi @pjhul, can you please provide steps to reproduce this issue

**Comment by anjola-adeuyi** [comment]
Hi, @pjhul is this issue still valid? I am interested in resolving it but I can't seem to find how this particular issue can be reproduced, **would be grateful if you help outline the steps required to get to the** `Add path cleaning rule dialogue` **from the dashboard.**

**Comment by pjhul** [comment]
Hey @anjola-adeuyi, apologies for the delay. It looks like this component has been updated and this issue has been resolved now. Thanks for checking up on this though :raised_hands:
