### ISSUE TITLE
iFrame dashboard emit internal height for seamless embedding

### ISSUE THREAD

**Issue by alexcroox** [PostHog/posthog#11058]
## Is your feature request related to a problem?

I'd like to show an iFrame of my PostHog public dashboard url.

I'd like to not have 2 scrollbars on my website.

I'd like the iFrame to dynamically be the right height of the dashboard so there is no iFrame scrolling required

## Describe the solution you'd like

If the dashboard public url page could emit it's height (and again when it changes due to resizing) to the parent then the parent could take care of setting the right iFrame height

e.g
```
const documentHeight = Math.max(body.scrollHeight, body.offsetHeight, html.clientHeight, html.scrollHeight, html.offsetHeight)

window.top.postMessage('height', documentHeight)
```

**Comment by benjackwhite** [comment]
Great suggestion! PR is up which should solve this including width resizing of the parent window
Once we get it in, let me know if it worked for you 🙌

**Comment by alexcroox** [comment]
Fantastic, thank you so much!

**Comment by benjackwhite** [comment]
For anyone who finds this in the future - how to do this is documented here 
https://posthog.com/tutorials/how-to-embed-shared-dashboard#expanding-the-iframe-to-match-the-height-of-the-dashboard

**Comment by alexcroox** [comment]
@benjackwhite I can see the height is being emitted now thank you, however it seems there is a permanent scrollbar within the iframe content that I cannot override.

The dashboard has an html class `"export-type-embed"` which is applying `overflow-y: auto`. This is creating a permanent sidebar, even if I adjust the emitted height to add 200 extra pixels, the scrollbar remains.

Here is a screenshot with and without that style removed to show the effect, notice the scrollbar dissapears without it:

`With:`
![Screenshot 2022-08-01 at 12 34 55](https://user-images.githubusercontent.com/1065835/182139907-4ab43860-6374-46b6-9a46-7c1531f8ab77.png)

`Without:`
![Screenshot 2022-08-01 at 12 35 03](https://user-images.githubusercontent.com/1065835/182140576-b6a3f184-0cdf-4038-8a5a-d374d45b5b1a.png)

**Comment by benjackwhite** [comment]
Hmmmm this might be harder to change as we can't disable the overflow as we can't guarantee that the parent embedded is actually tall enough. Do you have this embed somewhere public where I can take a look and see if there's an alternate solution?

**Comment by alexcroox** [comment]
Actually I think it might be the `.dashboard { margin-top: 1rem; }`

Are you able to reproduce this? If you aren't seeing this I'll try get a codesandbox going later tonight when I get a chance

**Comment by alexcroox** [comment]
No double scrollbar today, looks like someone removed the `.dashboard { margin-top: 1rem; }` rule, thanks! 👍
