### ISSUE TITLE
Publicly shared dashboards/insights are not loading (white screen shown instead)

### ISSUE THREAD

**Issue by TobiasIgnatzek** [PostHog/posthog#11082]
## Bug description
When accessing publicly shared dashboards and/or individual insights the charts don't load and a white screen is shown. 
It seems to be an issue with loading the actual charts. 

Insights and dashboards load in incognito mode though. The bug appears in browsers sessions in which the actual Posthog web app was accessed.

Screenshot from console:
<img width="1918" alt="Screenshot 2022-08-02 at 10 13 38" src="https://user-images.githubusercontent.com/52070588/182326812-d252ec67-1c11-4410-afa3-64bf0594edea.png">

## How to reproduce

1. Share dashboard / insight publicly
2. Copy the public dashboard link and try to access the dashboard/insight in the same browser (window)

## Environment

- [x] PostHog Cloud
- [ ] self-hosted PostHog, version/commit: please provide

**Comment by benjackwhite** [comment]
The js load error to me looks like the browser is loading a previous version's javascript files. This would also explain why it works incognito (incognito usually uses a different browser cache).

Does this still persist after a while? Can you try clearing your browser cache for app.posthog.com and see if that fixes it?

Happy to leave this open if it is repeatable, otherwise I would just chalk it up to typical cache-busting randomness

**Comment by tobiasignatzek** [comment]
Hi, thanks for your reply.

I cleared the browser cache and refreshed the dashboard page without any effect unfortunately.

**Comment by pauldambra** [comment]
I can recreate by doing

1) log in to posthog
2) share a dashboard
3) can view that dashboard directly in posthog
4) visit share link by opening a new tab -> blank page
5) visit share link in incognito window -> works
6) log out of posthog in original window
7) visit share link in original window -> works

----

8) log back in to posthog in original window
9) refresh shared dashboard -> works

My first guess is something to do with the auth token... from the two sessions (session A: logged in, and session B: share link)

**Comment by pauldambra** [comment]
I've just re-checked and can't repro' any more 🤯
