### ISSUE TITLE
Allow filtering of retention table

### ISSUE THREAD

**Issue by timgl** [PostHog/posthog#1108]
**Is your feature request related to a problem? Please describe.**

I want to be able to filter the retention table.

**Describe the solution you'd like**

Add a <PropertyFilter> component to the retention table and make sure the API allows you to pass ?properties in the backend.

**Describe alternatives you've considered**

-

**Additional context**

***Thank*** you for your feature request - we love each and every one!

**Comment by Kacppian** [comment]
Can I pick this up?

**Comment by timgl** [comment]
Please do!
