### ISSUE TITLE
Team east Sprint 1.39 insights backlog

### ISSUE THREAD

**Issue by timgl** [PostHog/posthog#11106]
One of the goals for team east is visualisations. Here's a list of some low hanging fruit.

- [ ] Custom time legends (see [artboard](https://www.figma.com/file/HwUmk7WqccLkGgNNGAs4zN/Art-board?node-id=4934%3A29109))
  - [ ] TODO: Engineer investigate how much of this is possible (how hard it will be)
- [x] Retention table styling update (see [artboard](https://www.figma.com/file/HwUmk7WqccLkGgNNGAs4zN/Art-board?node-id=4934%3A29109))
- [x] Pie chart styling update  (see [artboard](https://www.figma.com/file/HwUmk7WqccLkGgNNGAs4zN/Art-board?node-id=4934%3A29109))
- [x] https://github.com/PostHog/posthog/issues/6172
- [ ] https://github.com/PostHog/posthog/issues/11276
- [ ] #10226
- [x] Annotations still duck (behind the scroll edge)

**Comment by clarkus** [comment]
@lottiecoxon This work is being considered for the upcoming sprint. Can you move the art boards that are being considered into the posthog app project in figma just so it's easy to find the work for hand off? I've also asked team east to look at some of the proposals to squeeze last round feedback before we try to implement things. It'd also be good to call out via comments or github issues the key things to address in each improvement... there are just a ton of ideas so calling out the important bits will help us have a high quality hand off for building. 🌟 🌟 🌟

**Comment by Twixes** [comment]
Prioritizing this elsewhere now.
