### ISSUE TITLE
Sprint 1.39.0 1/2 - 8 Aug to 19 Aug

### ISSUE THREAD

**Issue by timgl** [PostHog/posthog#11104]
# Global Sprint Planning

## 3 things that might take us down

1. Rate limit API requests. We're emailing people now. @rcmarron 
2. Session recordings taking us down. Let's cap # recordings/day @rcmarron 
3. Same problem, but events @kappa90 

## Retro: Status of Outcomes from Previous Sprint

1. Kick off the persons on events async migration on Cloud and get a self-hosted team to run it @macobo Status: 99% done on self-hosted, cloud-specific clickhouse issue blocking a few million events from being migrated
2. Targeting a 'no rush' 100% - If we identify opportunities to improve the EKS stack we will before switching over @hazzadous - Made a little of progress, events still not on EKS
4. Continue supporting our paying on prem customers (big companies & co) @fuziontech - We have a solid strategy on how to deal with this in future
6. EU Deployment plan (Project docs) @guidoiaquinti - Deprioritised to focus on other stuff
8. S3 Session Recording @rcmarron. Status: Considering a big pivot on this project. Moving to an s3 backed merge table. Looking promising and 50x simpler - still needs more validation. Huge + is that there’s no new services to maintain/scale. If we don’t go this route, the existing approach is functionally working, but it needs more work for scalability - would leak into the next sprint.
1. Feature flag @neilkakkar Local evaluation of feature flags on server libraries (Python,Go,Ruby,Node,PHP): https://github.com/PostHog/posthog/issues/7115. Status: Decided to focus on getting one library perfect vs speed running. 3 down, 2 to go. 
1. Data Management Finalization + Recordings data management https://github.com/PostHog/posthog/issues/10892 @alexkim205. Status: wrapped data management, recordings still in progress. Stuff pushed to next week
1.  We will have agreed on and tested the tooling and architecture of the design system. @benjackwhite 
  - A lot of tooling work done - new scss utilities work, eslint rules to push us toward the right solution, beginning of work on refined Storybook approach 

## Support hero this sprint

Week 1: Alex
Week 2: Ben

## Plan: Proposed Goals for Next Sprint 

Each goal should have a single owner. Owner can only be an engineer.

1. s3 backed recordings @rcmarron 
why: Make sure we can retain sessions + not blow up clickhouse
2. turbo mode wrap up @neilkakkar 
why: immediate evaluation of feature flags rather than waiting for /decide
3. Session Recordings Experience enhancement — Event list @alexkim205 
why: Better/more fine grained experience, more parity with events
4. Person on events rollout @EDsCODE 
why: make our much queries faster
5. Switch over events to EKS and set ECS to 0 - @guidoiaquinti 
why: infrastructure parity between self hosted and cloud
6. "Right to be forgotten" tooling - make deleting person/groups/teams data easy @macobo
Why: GDPR compliance is one of our strengths (for self-hosted) and person-on-events is closing completion - we need proper tooling to make sure we can delete data still without killing performance.
7. Implement "fundamental" Design System components @benjackwhite 
why: design system will help us move faster
8. Low hanging fruit for visualisations https://github.com/PostHog/posthog/issues/11106 @Twixes 
why: Small fixes around visualisations will improve retention

# Team sprint planning

For your team sprint planning copy this template into a comment below for each team.

```
Team ___

## Retro

<!-- Talk about what went well, what didn't go well and any actions to improve next time -->

- 

## Hang over items from previous sprint

<!-- For each item, decide to re-prioritise (and add below) or deprioritise -->

- Item 1. prioritised/deprioritise

## Planning

<!-- Each item should have a single owner. Owner can only be an engineer. -->

### High priority

-

### Bugs

-

### Low priority / side quests

-

```

**Comment by macobo** [comment]
# Team Ingestion
## Goal

"Right to be forgotten" tooling - make deleting person/groups/teams data easy @macobo 
Why: GDPR compliance is one of our strengths (for self-hosted) and person-on-events is closing completion - we need proper tooling to make sure we can delete data still without killing performance.

**Notes**

-Yakko and Tiina are off for 1/2 of the sprint, Karl off 2 days in the first week

**Comment by benjackwhite** [comment]
# Team East

## Retro

- @benjackwhite - Investing the time in Design System refactoring is worthwhile. Discussion around the Design System is stressful. Async is hard.
- @lottiecoxon - Hard communication not having someone "nearby" to sync with. Trying to find work on Design System but tricky to figure out what to work on without stepping on toes. Feels like could be more efficient. Possibly lack of communication / structured plan. Delegating between people could have been clearer. Needs clearer ownership.
- @Twixes - Support hero directly after vacation is kind of difficult. Lots to catch up with with team goals etc.
- @pauldambra - All the improvements to Observabillity paid off to actually indicate if changes were effective. Feels like talked to people more which is good and helpful. Good habit of putting zoom links in public channels.
- (@benjackwhite on behalf of @kappa90) - Quite a lot on his plate but isn't necessarily nailing any individual thing. Potentially may make sense in the future to separate Team East goal and Growth goal. Nonetheless, knowledge sharing and live pairing on problems was super valuable.

## Hang over items from previous sprint

- Design System work

## Planning
### High priority

- **Goal 1:** Implement "fundamental" Design System components
- **Goal 2:** Low hanging fruit [visualisation improvements](https://github.com/PostHog/posthog/issues/11106)

### Bugs
- 

### Low priority / side quests
- Deployment of new Demo work
- In-app prompts - getting them working / observing the outcomes

**Comment by EDsCODE** [comment]
# Team West

## Retro



- 

## Hang over items from previous sprint

- s3 backed recordings
- turbo mode wrap up

## Planning
### High priority

- **Goal 1:** Session Recordings Experience enhancement — Event list
- **Goal 2:** Person on events rollout
