### ISSUE TITLE
Ability to have multiple configurations for a single plugin

### ISSUE THREAD

**Issue by lsmith77** [PostHog/posthog#11116]
## Is your feature request related to a problem?

f.e. the release tracker plugin might be useful to be used with multiple repositories attached. currently this is not supported.

one option is to make the plugin capable of configuring multiple repositories (f.e. https://github.com/PostHog/github-release-tracking-plugin/pull/10) but it would be nice to just be able to have multiple configurations for a specific plugin.

## Describe the solution you'd like

Ability to define multiple separate configurations for a single plugin.

## Describe alternatives you've considered

A pattern to make it easy for plugin authors to configure multiple configurations even if then the plugin needs to add explicit support for multiple configurations.

In the above PR I made the repo a comma separated list, but this is not very readable and error prone so ideally there would be a better way for plugins to collect a list with dynamic length in the configuration UI:
<img width="381" alt="image" src="https://user-images.githubusercontent.com/300279/182637917-935802c8-10ee-41f2-87b9-3537f5662fa6.png">

## Additional context

This is a meta need for plugin authors. For example I am planning to write a plugin that will create additional events for array elements inside another event:
https://github.com/PostHog/posthog/issues/11095

However, I might have multiple different arrays that require different configuration.

**Comment by macobo** [comment]
cc @yakkomajuri 

I think this is mostly blocked by UX

**Comment by yakkomajuri** [comment]
Hmm not really. 

As @lsmith77 pointed out one way is to handle this in the plugin code, but ideally we'd refactor things so one team can have multiple plugin configs (PluginConfig model) per plugin. This is not the end of the world but non-trivial
