### ISSUE TITLE
Fix brand colours on app

### ISSUE THREAD

**Issue by jamesefhawkins** [PostHog/posthog#1113]
We're currently swapping out the color scheme on posthog.com.

As part of this process, we'll define a palette.

When this is done, we should then make sure the app matches!

**Comment by Kacppian** [comment]
Can I pick this up?

**Comment by timgl** [comment]
@Kacppian Appreciate the enthusiasm! We don't actually know what the brand colours are yet but we'll put it in here once we do!

**Comment by Kacppian** [comment]
Makes sense, I'll wait for the colors :)

**Comment by jamesefhawkins** [comment]
Closed because #1275 has more detail!
