### ISSUE TITLE
"Add match group to existing action"

### ISSUE THREAD

**Issue by corywatilo** [PostHog/posthog#11138]
## Is your feature request related to a problem?

I have an established action, but the DOM structure where the action is being tracked recently changed. Since I don't want to lose the action's historical data, I want to add another DOM element to an existing action (as a match group).

## Describe the solution you'd like

This can be done in the Data Management section, but it would be far more elegant to create it using the Toolbar.

An option to add a new match group to the Inspect tool should do the trick. (Not great design, but added a button as an example...) After this screen, there'd be a search field to find the existing action I want to add the match group to.

<img width="499" alt="image" src="https://user-images.githubusercontent.com/154479/182827933-04e2efc1-ce0a-45ce-9953-5a96b94c8b63.png">

**Comment by clarkus** [comment]
This is a really interesting use case. Should the previous matching criteria for the action no longer apply? Are we replacing that old criteria, adding another capture case, or something else I'm not thinking of? Do we need any way to indicate which criteria were used for the match when viewing the corresponding data?

**Comment by corywatilo** [comment]
Actually this is an interesting question: if I remove the old selector, does it remove the data from appearing for that action, or will it stay there since it was already recorded? (I had assumed if I removed the old selector, that the data would no longer match.)

For this particular use case, I want to retain historical data while capturing new data, so I don't actually care if it's indicated.
