### ISSUE TITLE
Property Pills stack vertically in ActivityLog Sentence Lists

### ISSUE THREAD

**Issue by pauldambra** [PostHog/posthog#11131]
### viewed in feature flag

![Screenshot 2022-08-04 at 09 56 42](https://user-images.githubusercontent.com/984817/182807077-8a4d1bf0-8ba6-439d-bd74-dfb841eea2f6.png)

### viewed in history tab

![Screenshot 2022-08-04 at 09 53 56](https://user-images.githubusercontent.com/984817/182806462-9d2d4e60-3afe-47e3-a013-010d2382fb53.png)

When a change in the activity log has more than one property pill they stack vertically. They should stack horizontally. Ideally separated by commas using the `SentenceList` component.

## How to reproduce

* change a filter with more than one property in a feature flag
* view the activity log

## Environment

- [x] PostHog Cloud
- [x] self-hosted PostHog, version/commit: please provide

**Comment by gfratmct** [comment]
@pauldambra Hi, is the issue available to work on?

**Comment by pauldambra** [comment]
I'd missed the updates to #11263 . There are a couple of nits I'd like to address there but that is otherwise a fix to this. 

Thanks for the offer of help @xjabr 🙌 . There are other PRs in `good-first-issue` that you can look at 🥇
