### ISSUE TITLE
Feature: Event property filters for cohort creation

### ISSUE THREAD

**Issue by joethreepwood** [PostHog/posthog#11142]
## Is your feature request related to a problem?

Currently, you can't use filters when creating a cohort directly. So, for example, if I want to create a cohort of our FOSS users then this isn't possible through PostHog. I'd need to use the `organization` event and filter by the `product` property (`product = open source`) on it. That's not possible using the cohort tool, because I can't use filters -- only events, person properties, etc. Not event properties. 

<img width="1128" alt="Screenshot 2022-08-04 at 12 11 18" src="https://user-images.githubusercontent.com/84011561/182833273-b59365b0-7542-48b8-8883-cdec0d9543f2.png">

Feels like this massively limits the potential of creating cohorts directly,

## Describe the solution you'd like

Filters available for cohort creation. 

## Describe alternatives you've considered

One way that was suggested to overcome this was to create an insight looking at the event property, then click the datapoint in the insight and create a cohort from there. 

<img width="661" alt="Screenshot 2022-08-04 at 12 20 49" src="https://user-images.githubusercontent.com/84011561/182834939-965b612d-cf00-4625-b07b-d938064ee3a4.png">

However, even if you choose to group the data by week or month, clicking a data point and creating a cohort from there only creates a cohort based on the _day_, So, I end up with a cohort of 20ish people, rather than 1,200ish people.

**Comment by deleted-user-179803281019** [comment]
Any updates on this?

**Comment by juancferrer** [comment]
Would love to have this feature as well.
We have users with many "subscriptions".

I want to create a cohort for users that have the `subscription created` event, with the event property labeled `zipcode` with value being `90210`.

Let me know if there's any alternative way of doing the above.

**Comment by neilkakkar** [comment]
Hey @juancferrer you can do this today by creating an action (Data management -> action -> new) and then using the action in the cohort

**Comment by juancferrer** [comment]
@neilkakkar Thanks for the quick reply  
I tried your suggestion, and it worked as expected.  I was able to create a cohort for users that have an event + event property.   As you suggested, the key was to create a new "action".

As an aside, it turns out that a cohort with "behavioral" filters (actions?) can NOT be used in AB tests / experiments, so we're still researching on how to do that.

**Comment by neilkakkar** [comment]
Indeed. The best way around that for now is to create a property for your person that is set when that event happens, and then use that property in the flag/experiment.
