### ISSUE TITLE
Column sorting icon isn't intuitive

### ISSUE THREAD

**Issue by corywatilo** [PostHog/posthog#11146]
The icon at the top right of the table ("Total sum") has a caret which leads me to believe this table is sorted by that column (which it isn't - it's actually a dropdown to modify the _data_ in the column).

<img width="1350" alt="image" src="https://user-images.githubusercontent.com/154479/182843799-c09f824d-e596-4a97-841d-2169813bc45d.png">

## There are a few things going on here:

1. It's actually triggered on hover, but the menu is slightly delayed. 9/10 times, I click the button to change sorting before I realize it's a dropdown, then end up activating an option I didn't intend to.
2. The 3 bars/hamburger icon is _actually_ the sorting option (but it doesn't look like a button), and there _is_ a tooltip for this when you hover the 3 bars, but it appears over the dropdown instead, which is a different button
    <img width="388" alt="image" src="https://user-images.githubusercontent.com/154479/182844612-979826b2-ea65-4eca-87ab-f656234bb9ad.png">

## Suggestions

- [ ] Reserve the chevron/caret icon for indicating a sort direction, and use that icon for triggering it (vs bars)
- [ ] Encapsulate the "Total sum" column header (1px border?) to make it look like its own dropdown inside the table header
- [ ] Split the tooltips, add a more accurate tooltip for the option that lets you change the data being represented in the column
- [ ] Any reason we wouldn't default to sort descending? Seems like what I'm always looking for...

**Comment by clarkus** [comment]
Agree that the affordance for sorting is pretty confusing. In the recent table designs, I've been using the sort indicator patterns shown [here](https://www.figma.com/file/Y9G24U4r04nEjIDGIEGuKI/PostHog-Design-System-One?node-id=3139%3A1215). In some cases I've used a active-tab-like underline to reinforce which column is being used to sort the table (not shown in figma).

<img width="933" alt="Screen Shot 2022-08-04 at 8 24 19 AM" src="https://user-images.githubusercontent.com/254612/182885449-c72d5ec8-6a5e-47dd-9ffd-b5b98ebb2127.png">

We've been moving to column configuration options for tables recently. There are still a few places where this hasn't been applied, but ideally we'd give the users some control external to the table to configure what columns are shown, the order they're shown, and some controls for formatting or units.
