### ISSUE TITLE
Persons property filter bug

### ISSUE THREAD

**Issue by liyiy** [PostHog/posthog#11156]
## Bug description

Using `email != null` as a specific example
if you filter for email where it's not null it'll still return null emails for user properties

Go to an insight -> filter with a person property -> results aren't accurate

## How to reproduce

1.
2.
3.

## Environment

- [ ] PostHog Cloud
- [ ] self-hosted PostHog, version/commit: please provide

**Comment by neilkakkar** [comment]
Elaborate what's wrong with the results? 🤔

**Comment by liyiy** [comment]
if you filter for email where it's not null it'll still return null emails for user properties

**Comment by pauldambra** [comment]
🤔 hmmm, #11168 _should_ only have affected display, not results. 

I'm being slow and not understanding though. Can we make an example insight?

**Comment by neilkakkar** [comment]
Eh, nope, I misread your PR, my bad! 🙈

**Comment by anna-rusk** [comment]
I think this is fixed! Basically we had set our internal test users as users with a certain property as null but some of these users were still making it into funnels when we had the filter out internal test users flag on

**Comment by liyiy** [comment]
That's great to hear then!
