### ISSUE TITLE
column configurator background disappears when dragging

### ISSUE THREAD

**Issue by pauldambra** [PostHog/posthog#11167]
When dragging to reorder rows in the column configuration modal the background disappears while being dragged

![2022-08-05 11 48 33](https://user-images.githubusercontent.com/984817/183062355-a5494c0b-eeac-4009-94ff-77275a167c51.gif)

Spotted while reviewing https://github.com/PostHog/posthog/pull/11093 but not introduced in that

## Reproduction steps

* visit the live events page
* click configure columns
* grab a row by its drag handle
* see its background disappear

![2022-08-17 10 42 24](https://user-images.githubusercontent.com/984817/185087779-bbd03fa1-af2e-4232-ab39-69959664501b.gif)

**Comment by LuisChiej** [comment]
Hello @pauldambra, I'm new to the repo, Please could you list out the steps to reproduce the bug above

Thank you

**Comment by LuisChiej** [comment]
Hello @pauldambra, Still waiting on a response here

Thank you

**Comment by pauldambra** [comment]
Updated description @LuisChiej

**Comment by LuisChiej** [comment]
> Updated description @LuisChiej

Thank you

**Comment by neilkakkar** [comment]
@LuisChiej I notice you're active on quite a few issues, but I don't see any PRs 👀 . Are you getting stuck somewhere?

**Comment by LuisChiej** [comment]
@neilkakkar, Not currently stuck, Just still working on them
