### ISSUE TITLE
Input Focus doesn't include the side icon

### ISSUE THREAD

**Issue by pauldambra** [PostHog/posthog#11166]
## Bug description

![Screenshot 2022-08-05 at 11 38 24](https://user-images.githubusercontent.com/984817/183060568-11ce0b86-5d2e-4a95-92ea-0ebdb8a043ce.png)

focus state on an input with side icon doesn't include the icon which looks odd

Spotted while reviewing https://github.com/PostHog/posthog/pull/11093 but not introduced in that

**Comment by benjackwhite** [comment]
More specifically we should ditch this in favour of a LemonInput with a Search Icon

**Comment by mariusandra** [comment]
I think this has been ditched?
