### ISSUE TITLE
Cloud login page has unexpected text

### ISSUE THREAD

**Issue by corywatilo** [PostHog/posthog#11187]
## Bug description

"True" is showing next to the login button:

```
<div class="helper-links cloud">
True
<a href="/reset" data-attr="forgot-password" class="rhs">
  Forgot your password?
</a>
</div>
```

<img width="649" alt="image" src="https://user-images.githubusercontent.com/154479/183457520-03ead335-7fd5-41d9-9abe-6423abdd082a.png">

**Comment by liyiy** [comment]
fixed
