### ISSUE TITLE
"Host" and "Path name" event properties are not set for some events.

### ISSUE THREAD

**Issue by scottypickering** [PostHog/posthog#1119]
**Describe the bug**
The "host" and "path name" properties are only set for auto-capture events resulting from clicks. Manually sent events, $pageview, $pageleave, and $identify events do not have the "host" or "path name" properties set, however, they _do_ have the current URL property set.

**To Reproduce**
1. Deploy Posthog on Heroku.
2. Integrate with web application using `npm install --save posthog-js`.
3. Capture both auto-capture and manual events.
4. Attempt to sort events by "host" or "path name".

**Expected behavior**
All events would have the "host" and "path name" properties set.

**Hosted or self hosted?:**
- self-hosted v1.9.0

**Comment by mariusandra** [comment]
Hi @scottypickering!

Thank you for raising this! We in fact fixed it about a week ago, but haven't released a new version of posthog-js yet for several reasons. A new version with the fix will come out either tomorrow or Wednesday. 

Thank you for your patience! :) 

This is the PR that fixed this: https://github.com/PostHog/posthog-js/pull/47

**Comment by scottypickering** [comment]
Great, thank you!
