### ISSUE TITLE
/people - expanding user properties is confusing

### ISSUE THREAD

**Issue by jamesefhawkins** [PostHog/posthog#112]
**Describe the bug**
It's not a bug, but expanding the user properties on the /people page is confusing.

![Screenshot 2020-02-17 at 14 27 50](https://user-images.githubusercontent.com/47497682/74689931-f4f49980-5191-11ea-8f74-659442b8e38e.png)

**To Reproduce**
1. Go to /people
2. Click on a row displaying a user
3. The row will expand, but it won't show anything

**Expected behavior**
* The row should expand, so it's obvious that this *could* do something.
* It should just the user properties if applicable OR it should say "we have no other properties for this user".

**Desktop (please complete the following information):**
 - OS: OS X
 - Browser Chrome

**Comment by timgl** [comment]
Closed with #114
