### ISSUE TITLE
CSV Export fails

### ISSUE THREAD

**Issue by duncanmcclean** [PostHog/posthog#11204]
## Bug description

We're running into an issue where when we try to export our insights, we almost instantly get an error saying the import has failed.

![image](https://user-images.githubusercontent.com/19637309/183639263-92f6e19b-4392-456e-8878-bc8ffcd8cc5e.png)

I'm guessing this is a bug in PostHog. Is there any way we can workaround this - our data is a bit useless in PostHog if we can't export it?

## How to reproduce

1. Go to a dashboard
2. For one of the insights, click the three dots, then click 'Export -> CSV'
3. You'll then get the 'Export failed' error message

You also get it if you go into an insight, select the 'Linear' chart type, then attempt to export as a CSV. Same issue.

## Environment

- [x] PostHog Cloud
- [ ] self-hosted PostHog, version/commit: please provide

## Additional context

Project ID: `6642`

**Comment by pauldambra** [comment]
Can see this error surface here https://sentry.io/organizations/posthog2/issues/3428846531/?project=1899813&query=is%3Aunresolved

Frustratingly there have been 115 in the last 30 days but not (noticed) alert

**Comment by pauldambra** [comment]
Error is `invalid url {blah} No schema supplied. Perhaps you meant http://{blah}`

The exported asset then doesn't have either local content or a path to exported content in object storage. So export has failed

**Comment by duncanmcclean** [comment]
@pauldambra So I'm right in assuming this is a PostHog bug, yes, and not something we're doing incorrectly?

**Comment by pauldambra** [comment]
@duncanmcclean yep, weirdly it works for me logged in as PostHog staff and logged in to my personal account. 

So, I'm just trying to puzzle through if the exception is hiding a different error. At least two teams affected I'll link PRs here as I figure out what to change

**Comment by duncanmcclean** [comment]
No worries - I'll update my client. I appreciate the speedy replies!

**Comment by pauldambra** [comment]
So #11206 means the export doesn't immediately fail for you. But does still fail :/

The wrong kind of progress 🤣

**Comment by pauldambra** [comment]
Hey @duncanmcclean this should be working for you now.

The first time I tried it timed out (we've some work queued to improve experience when the CSV export takes longer than the timeout we apply) but the second time it exported fine.

I'll leave this open until you've had a chance to test and confirm.

Thanks for reporting this! Not only is it good to squash the bug but it was a really fun problem to figure out :)

**Comment by duncanmcclean** [comment]
Looks good for me - just waiting on my client to confirm! Thanks for fixing this so quickly!

**Comment by pauldambra** [comment]
I'll close this (to keep my GitHub queue clean 🤖) but do re-open or ping me on the community slack if you need to follow-up!

And thanks again. I'd never have spotted that bug with local testing 🙌

**Comment by andresguerreroalvarez** [comment]
Hi, I'm having this exact problem - my csv files are not exporting and I get the "Export failed" message. ¿What can I do?
