### ISSUE TITLE
Speed up `createPerson` in plugin-server

### ISSUE THREAD

**Issue by macobo** [PostHog/posthog#11218]
## Problem description

`db.createPerson` is an operation we call very frequently, so speedups to that function translate to cheaper and more efficient pipeline overall.

## Opportunity

When calling this function, we currently:
1. Create a transaction
2. INSERT INTO posthog_person, reading the result
3. Generate kafka messages for person row
4. For every distinct_id passed (1-2) do a `INSERT INTO posthog_persondistinctid`
5. For every distinct_id passed (1-2) generate kafka messages
6. COMMIT

We communicate with postgres 4-5 times throughout (1, 2, 4, 5). 

node-pg supports sending multiple queries in a single 'query' ([1](https://stackoverflow.com/questions/35625360/execute-multiple-queries-in-a-single-statement-using-postgres-and-node-js), [2](https://github.com/brianc/node-postgres/issues/83), [3](https://github.com/brianc/node-postgres/issues/1717)). While this may have some limitations ([4](https://github.com/brianc/node-postgres/issues/1190#issuecomment-619557934)), we could leverage this to cut all of this down to a single communication with postgres.

The tricky parts are:
- Avoiding code drift for posthog_persondistinctid code.
- Testing, working out limitations of this approach

## Additional context

Not certain this is worth it due to the limitations and trade-offs but documenting stray thoughts on our hot path.

cc @yakkomajuri @tiina303 from team ingestion

**Comment by tiina303** [comment]
@bretthoerner  shipped this
