### ISSUE TITLE
Make JS snippet more prominent in onboarding flow

### ISSUE THREAD

**Issue by timgl** [PostHog/posthog#1121]
**Is your feature request related to a problem? Please describe.**

I noticed this, and yesterday @fuziontech got a report from someone that mentioned they couldn't find a way to integrate their website as they weren't using NPM and got confused when they clicked on Javascript.

**Describe the solution you'd like**

I suggest if you select 'web' on the first step, it shows you the snippet first, then gives you to option to also integrate with another library/language using that list.

**Describe alternatives you've considered**

Navigate through another backend language.

**Additional context**

cc @EDsCODE 

***Thank*** you for your feature request - we love each and every one!

**Comment by yakkomajuri** [comment]
First time user here. Indeed, I was a little confused as to why all those buttons were there if clicking all of them gave me the same page (except for Pure JS).
