### ISSUE TITLE
Filter retention table by action/event

### ISSUE THREAD

**Issue by jamesefhawkins** [PostHog/posthog#1122]
**Is your feature request related to a problem? Please describe.**

We a shiny retention table now. 

However, it shows just "visits", whereas I want to know for users of our app what this table would look like.

**Describe the solution you'd like**

The ability to add filters in order that we could show it for our own app usage.

**Describe alternatives you've considered**

The stickiness graph in our own app could give me this data in a more aggregated view.

**Comment by EDsCODE** [comment]
watching #1205 instead
