### ISSUE TITLE
Person delete action should use a destructive button component

### ISSUE THREAD

**Issue by clarkus** [PostHog/posthog#11239]
## Bug description

It is now possible to delete persons from a project. However the button that prompts this action doesn't indicate that it's destructive. We should communicate the destructive nature of the action via a secondary button that uses the destructive red palette options. Secondary to this, we should use a dialog component to force a user decision on whether the action should be completed or not - given its destructive nature and no ability to undo, doublechecking that the user wants to delete the person is a good thing. 

## How to reproduce

1. Go to a person detail view
2. Note that the delete button lacks typical affordance for destructive actions

## Additional context

- [Figma documentation for buttons](https://www.figma.com/file/Y9G24U4r04nEjIDGIEGuKI/PostHog-Design-System-One?node-id=3143%3A5147)

<img width="856" alt="Screen Shot 2022-08-10 at 2 05 22 PM" src="https://user-images.githubusercontent.com/254612/184019974-204c67d2-370c-4409-8a9f-f050db6e250b.png">

- [Figma documentation for dialogs](https://www.figma.com/file/Y9G24U4r04nEjIDGIEGuKI/PostHog-Design-System-One?node-id=3141%3A3814)

**Comment by LuisChiej** [comment]
@clarkus,
I require more context to fully understand how to replicate the issue and fix it

**Comment by clarkus** [comment]
Thanks for offering to fix, @LuisChiej. I just confirmed this issue was actually resolved in https://github.com/PostHog/posthog/pull/11242. Thanks again.
