### ISSUE TITLE
Break down Table "Chart" by day

### ISSUE THREAD

**Issue by mariusandra** [PostHog/posthog#1124]
I ended up looking at with this view:

![image](https://user-images.githubusercontent.com/53387/86125013-474cac00-badc-11ea-9bc9-fa80ac79e6e4.png)

I'd like to see the data per day, so I could copy/paste to excel and calculate percentages. However it's not broken down per day.

Alternatively, I need to open the line chart and then rewrite all the numbers from there to get this data.

**Comment by paolodamico** [comment]
@mariusandra is this still an issue?

**Comment by mariusandra** [comment]
Not for me. Can be closed for now and we'll see if anyone requests it again.
