### ISSUE TITLE
Plugins failed to load (PostgreSQL and Redshift Export Plugin)

### ISSUE THREAD

**Issue by tholor** [PostHog/posthog#11248]
## Bug description
We are running a self-hosted posthog instance for a couple of months already. Now, we'd like to export some data to postgres or redshift, but struggle with setting up the exporter plugins. 
For both plugins (postgresql and redshift exporter), we get the following error message after enabling the plugin: 

```
...
2022-08-11 11:07:21.244 UTC | SYSTEM | ERROR | Plugin failed to load (instance ID 01819094-79a9-0000-7af7-XXXXX). Retrying in 12 s.
-- | -- | -- | --
2022-08-11 11:07:21.243 UTC | SYSTEM | ERROR | Script execution timed out after promise waited for 30 seconds
...
``` 
My first thought was on a connection problem, but I verified that the postgres instance (RDS) is reachable from the public and the user has the permissions mentioned [here](https://github.com/PostHog/postgres-plugin). 

As the same error message is also occurring in both plugins (postgres and redshift), I am now wondering if the error message could actually indicate any other problem (e.g. the plugin really not loading before any connection attempt is made). Is there anything I can do to track this down further? Would a connection or permission issue result in this error message or something else? Any help appreciated :)

## How to reproduce

1. Create RDS instance as described in readme here (or redshift)
2. Set up user
3. Configure Postgres exporter plugin in posthog
4. Enable it & check logs

## Environment

- [ ] PostHog Cloud
- [x] self-hosted PostHog, version/commit: 1.33.0, fe82d214b66041c0a6e6026351a93da52e153163, Plugin server 1.10.5

**Comment by benjackwhite** [comment]
Looks to me still like a connection problem. Have you verified that you are able to talk to RDS _from where PostHog is running_ ? AWS does all sorts of clever routing things so even if made public it might not be accessible if the security groups are not configured correctly.

If you are running in Kubernetes you could exec into a pod, and try to connect to postgres with the CLI

**Comment by tholor** [comment]
Thanks, it was indeed still a connection problem stemming from the AWS ACL configuration of our posthog instance.
