### ISSUE TITLE
Async migrations proceeded even when an operation fails

### ISSUE THREAD

**Issue by joetrollo** [PostHog/posthog#11283]
## Bug description

I just upgraded from 1.37 to 1.38 and tried to run the new async migration `0005_person_replacing_by_version.py`. As the migration progressed, it encountered an out-of-memory error in ClickHouse when running `INSERT INTO posthog.tmp_person_0005_person_replacing_by_version SELECT * FROM person`. However, instead of aborting and rolling back the migration, it proceeded with the remaining operations and marked the migration complete, which also disabled my ability to rollback through the async migration UI.

Because this insert failed, we're now "missing" over 4M rows from our `person` table in ClickHouse (the original table had 6.8M rows, but the new table only has the 2.7M rows that it copied over from PostgreSQL). I say "missing" because the data is still in the backup table that the migration made, and because it's unclear if these additional rows are meaningful or if only the 2.7M that were in PostgreSQL matter. It's also unclear how to properly recover this data from the backup table (if necessary).

## How to reproduce

This may be difficult to reproduce, as the initial out-of-memory issue was transient. I'm filing this issue now but am working to reproduce this reliably in a modified hobby deployment. If I'm successful, I'll update this issue with concrete steps to reproduce.

## Environment

- [ ] PostHog Cloud
- [X] self-hosted PostHog, version/commit: 1.38.0

## Additional context

The out-of-memory error (probably) isn't directly related to this `INSERT` query—the table was only 6.8M rows/1.4GB in size and should have completed just fine in isolation. It failed because another person on my team was actively using ClickHouse and managed to nearly fill up its memory—an unfortunately common occurrence given that we've collected over 1B events in just the last 10 weeks.

**Comment by macobo** [comment]
That's a bug alright - we expected that INSERT to be failing loud and clear. Checking on if I'm able to reproduce this on our end and make this fail in a loud way.

If you have query logging turned on in your cluster, what is the exact error logged in `system.query_log` table in ClickHouse?

> It's also unclear how to properly recover this data from the backup table (if necessary).

I think the easiest way to go about this is to "force" a rollback. Based on the above, it seems you're quite comfortable accessing the underlying infra, so what you can do is:

0. Confirm that the async migration is marked as completed in the UI
1. Manually update the db to mark the async migration as failed
2. Rollback via UI
3. Start again

For step 1, you can:
- Open a python shell via kubectl. Example command: `kubectl exec --stdin --tty $(kubectl get pods -n posthog -l role=web -o jsonpath="{.items[].metadata.name}") -n posthog -- python manage.py shell_plus`
- Update the async migration:
```python
am = AsyncMigration.objects.get(name="0005_person_replacing_by_version")
am.status = 3
am.save()
```

**Comment by joetrollo** [comment]
Thanks for the guidance @macobo. Here's the exception in our query log:

```
Code: 241. DB::Exception: Memory limit (total) exceeded: would use 52.23 GiB (attempt to allocate chunk of 134217728 bytes), maximum: 52.20 GiB: (while reading column properties): (while reading from part /var/lib/clickhouse/data/posthog/person/all_652100_682448_149_779839/ from mark 0 with max_rows_to_read = 196608): While executing MergeTreeThread. (MEMORY_LIMIT_EXCEEDED) (version 21.11.11.1 (official build))
0. DB::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int, bool) @ 0x9b7f194 in /usr/bin/clickhouse
1. DB::Exception::Exception<char const*, char const*, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, long&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >(int, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, char const*&&, char const*&&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >&&, long&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >&&) @ 0x9b95289 in /usr/bin/clickhouse
2. MemoryTracker::allocImpl(long, bool) @ 0x9b94c03 in /usr/bin/clickhouse
3. MemoryTracker::allocImpl(long, bool) @ 0x9b949d0 in /usr/bin/clickhouse
4. MemoryTracker::allocImpl(long, bool) @ 0x9b949d0 in /usr/bin/clickhouse
5. MemoryTracker::allocImpl(long, bool) @ 0x9b949d0 in /usr/bin/clickhouse
6. Allocator<false, false>::realloc(void*, unsigned long, unsigned long, unsigned long) @ 0x9bcfebf in /usr/bin/clickhouse
7. void DB::PODArrayBase<1ul, 4096ul, Allocator<false, false>, 15ul, 16ul>::resize<>(unsigned long) @ 0x9bd5b49 in /usr/bin/clickhouse
8. ? @ 0x11dafb1a in /usr/bin/clickhouse
9. DB::ISerialization::deserializeBinaryBulkWithMultipleStreams(COW<DB::IColumn>::immutable_ptr<DB::IColumn>&, unsigned long, DB::ISerialization::DeserializeBinaryBulkSettings&, std::__1::shared_ptr<DB::ISerialization::DeserializeBinaryBulkState>&, std::__1::unordered_map<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, COW<DB::IColumn>::immutable_ptr<DB::IColumn>, std::__1::hash<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, std::__1::equal_to<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, std::__1::allocator<std::__1::pair<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const, COW<DB::IColumn>::immutable_ptr<DB::IColumn> > > >*) const @ 0x11d792b5 in /usr/bin/clickhouse
10. DB::MergeTreeReaderWide::readData(DB::NameAndTypePair const&, COW<DB::IColumn>::immutable_ptr<DB::IColumn>&, unsigned long, bool, unsigned long, unsigned long, std::__1::unordered_map<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, COW<DB::IColumn>::immutable_ptr<DB::IColumn>, std::__1::hash<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, std::__1::equal_to<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, std::__1::allocator<std::__1::pair<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const, COW<DB::IColumn>::immutable_ptr<DB::IColumn> > > >&, bool) @ 0x12f2e742 in /usr/bin/clickhouse
11. DB::MergeTreeReaderWide::readRows(unsigned long, unsigned long, bool, unsigned long, std::__1::vector<COW<DB::IColumn>::immutable_ptr<DB::IColumn>, std::__1::allocator<COW<DB::IColumn>::immutable_ptr<DB::IColumn> > >&) @ 0x12f2d519 in /usr/bin/clickhouse
12. DB::MergeTreeRangeReader::DelayedStream::finalize(std::__1::vector<COW<DB::IColumn>::immutable_ptr<DB::IColumn>, std::__1::allocator<COW<DB::IColumn>::immutable_ptr<DB::IColumn> > >&) @ 0x13468bce in /usr/bin/clickhouse
13. DB::MergeTreeRangeReader::startReadingChain(unsigned long, std::__1::deque<DB::MarkRange, std::__1::allocator<DB::MarkRange> >&) @ 0x1346d540 in /usr/bin/clickhouse
14. DB::MergeTreeRangeReader::read(unsigned long, std::__1::deque<DB::MarkRange, std::__1::allocator<DB::MarkRange> >&) @ 0x1346bd35 in /usr/bin/clickhouse
15. DB::MergeTreeBaseSelectProcessor::readFromPartImpl() @ 0x134643ba in /usr/bin/clickhouse
16. DB::MergeTreeBaseSelectProcessor::readFromPart() @ 0x1346560d in /usr/bin/clickhouse
17. DB::MergeTreeBaseSelectProcessor::generate() @ 0x13463cab in /usr/bin/clickhouse
18. DB::ISource::tryGenerate() @ 0x131bf415 in /usr/bin/clickhouse
19. DB::ISource::work() @ 0x131befda in /usr/bin/clickhouse
20. DB::SourceWithProgress::work() @ 0x133d6862 in /usr/bin/clickhouse
21. ? @ 0x131dabbb in /usr/bin/clickhouse
22. DB::PipelineExecutor::executeStepImpl(unsigned long, unsigned long, std::__1::atomic<bool>*) @ 0x131d6b71 in /usr/bin/clickhouse
23. ? @ 0x131dcb45 in /usr/bin/clickhouse
24. ThreadPoolImpl<std::__1::thread>::worker(std::__1::__list_iterator<std::__1::thread, void*>) @ 0x9bc1217 in /usr/bin/clickhouse
25. ? @ 0x9bc4c1d in /usr/bin/clickhouse
26. start_thread @ 0x9609 in /usr/lib/x86_64-linux-gnu/libpthread-2.31.so
27. __clone @ 0x122293 in /usr/lib/x86_64-linux-gnu/libc-2.31.so
```

Because our PostHog instance has been running like this for a few days now, is it safe to rollback the migration? There will be rows in the current `person` table that won't exist in the backup table that gets restored. Perhaps an "insert if not exists" type query to copy the missing data into the new table would be the safest?

**Comment by macobo** [comment]
You can insert data from the old backup table to the new one via

```sql
INSERT INTO person
SELECT *
FROM person_backup_0005_person_replacing_by_version
SETTINGS optimize_on_insert=0,
  max_block_size=50000,
  max_insert_block_size=50000,
  max_threads=20,
  max_insert_threads=20,
  max_execution_time=10000000,
  send_timeout=10000000,
  receive_timeout=10000000
```

The settings are copied from the original migration to make sure it doesn't time out.

Clickhouse and our queries will handle the duplicate rows introduced so no worry about that. You can also issue a `OPTIMIZE TABLE person FINAL` afterwards which will free up some space and (in a minor way) speed up queries.

Happy to run through this face-to-face as well. Email me at karl at posthog.com if you're interested with some times you're available, I'm in UTC+3.
