### ISSUE TITLE
Toolbar beta program feedback

### ISSUE THREAD

**Issue by mariusandra** [PostHog/posthog#1129]
**Doesn't Open?** If the toolbar doesn't open for any reason, click "Launch Toolbar" and select your site. Then play around with it and add a comment below with your OS/Browser/MothersMaidenName and share your impressions so far!

----

We want to know if we are on the right track!

This issue is here to discuss any problems discovered during the toolbar beta program. Please just reply with any questions/comments/feedback/etc you might have! 

You can follow the progress of development in the Toolbar Project here: https://github.com/PostHog/posthog/projects/7

## Enabling the new toolbar

To enable the new toolbar, turn on this toggle under `/setup`

![image](https://user-images.githubusercontent.com/53387/86230718-bfc17480-bb91-11ea-837d-f675c0169901.png)

## Starting the new toolbar

To start the new toolbar, just visit your site that's tracked by PostHog. Make sure you're either using the snippet (copied from `/setup`) or the latest `posthog-js` npm package.

The toolbar should open automatically if you're logged in to posthog and prompt you to authenticate.

![image](https://user-images.githubusercontent.com/53387/86231021-2e063700-bb92-11ea-900b-9347b4f10ec8.png)

## Using the toolbar

Once you authorize yourself, the toolbar is ready to use! Click the buttons and the numbers that open up to interact with it.

![image](https://user-images.githubusercontent.com/53387/86231107-4d04c900-bb92-11ea-8048-4e8c0755680a.png)

## Feedback!

There are still [multiple broken things](https://github.com/PostHog/posthog/projects/7) in the toolbar. In case you discover something new or broken, please raise your voice and let us know!

Thank you!! :)

**Comment by corbt** [comment]
Just tried enabling the toolbar in our Posthog installation. We're on Posthog 1.10.1, our Posthog host is "https://phog.ycombinator.com", and our production site is at https://www.startupschool.org.

No toolbar shows up when I visit our site, but I am getting a weird error that makes it look like Posthog is trying to load the toolbar JS from a localhost URL?

![Screen Shot 2020-07-08 at 7 21 20 PM](https://user-images.githubusercontent.com/176426/86989880-36411200-c150-11ea-8fce-21b868dfc4cc.png)

**Comment by SuperKruse** [comment]
I cannot get sign in to work, i can sign in without any problems, and the `csrftoken` is there as well.
We use posthog as a module and initialize posthog after dom load.

My guess is it have something to do with when the toolbar looks for the token (right after dom loaded, but before posthog is initialized?)

Maybe a little related to https://github.com/PostHog/posthog-js/issues/66

**Comment by filipkis** [comment]
Hello, nice "little" feature. Looks promising. 

I could get the hog to appear on the page (I enabled it in the app and then just navigated to my domain), but after I click on it I'm thrown into the authorisation page, then I click Authorise which takes me back to my page, but nothing changes. Clicking on the hog again, shows the authorisation page again. And so on.

I'm on Chrome  83.0.4103.97 and I did this in incognito, so there shouldn't be any plugins there.

![image](https://user-images.githubusercontent.com/254631/87161210-7923f680-c2c4-11ea-8b3a-009864ea144b.png)

**Comment by mariusandra** [comment]
@filipkis Glad to hear that it works now!

@corbt That error should only appear if the env `DEBUG=1` is set. We use this URL when developing (for webpack dev server)... and that's now enabled with that flag. Could this be what's happening?

In case you or anyone else wants to run posthog with `DEBUG=1` in production (not recommended), then there's a fix in the `master` branch and in 1.11 (due Wednesday), which lets you set the env `JS_URL=https://your.app.url`. This will specify what host the toolbar will load its code from.

@SuperKruse Thank you for raising this! I will look at it as soon as I can!

**Comment by corbt** [comment]
@mariusandra good catch -- yes, looks like we'd never turned off `DEBUG=1`. Turning that off fixed the issue I reported.

However, I'm now running into the same problem that @filipkis reported above. The hog shows up when I visit www.startupschool.org, and I can mouse over and click "Click here to authenticate". It takes me to the authorization page, but just like @filipkis reported when I click the "Authorize" button I'm taken back to my domain but the button still just says "Click here to authenticate".

I'm on Posthog 1.10.1.

**Comment by mariusandra** [comment]
@corbt The end result was that PostHog and MixPanel JS don't play nicely together. The fix for this is also in master and will come out with the next release. Filip was using the cloud version, which is running master... Thus it works now for him.

**Comment by mariusandra** [comment]
@SuperKruse it's possible `1.3.2` could fix the issue you're having. Could you report back if that's the case?

**Comment by jamesefhawkins** [comment]
@mariusandra another piece of feedback - I feel like I'm getting asked to reauthenticate a lot. Is that perhaps because we're consinstently upgrading PostHog thus it kicks me out each time?

**Comment by SuperKruse** [comment]
> @SuperKruse it's possible `1.3.2` could fix the issue you're having. Could you report back if that's the case?

Unfortunately not, it still doesn't register I signed in.

**Comment by mariusandra** [comment]
Hi @SuperKruse, here are a few more things to try:

- First, can you confirm that the site on which you want to use the toolbar is present in the "Permitted Domains/URLs" list under `/setup`? In PostHog 1.12+ this list will also be behind a "Launch Toolbar" button.

![image](https://user-images.githubusercontent.com/53387/88560530-8a903100-d02e-11ea-9a68-56df27f881a9.png)


- Can you open your site and inspect the cookies of the XHR network request sent to `your.posthog.instance/decide`. What does it show? It should have the "secure" and "httponly" flags ticked and "SameSite=None"

![image](https://user-images.githubusercontent.com/53387/88560165-13f33380-d02e-11ea-9588-f2d87930310b.png)

**Comment by mariusandra** [comment]
@jamesefhawkins 

> @mariusandra another piece of feedback - I feel like I'm getting asked to reauthenticate a lot. Is that perhaps because we're consinstently upgrading PostHog thus it kicks me out each time?

We were storing the auth token inside window.sessionStorage, which is basically "per-tab". The situation is made more complex by the fact that when you "authenticate" somewhere, it logs you out of all other authenticated toobars.

This will be solved once https://github.com/PostHog/posthog-js/pull/73 is merged. We will need to add an "unauthenticate" option as well.

**Comment by SuperKruse** [comment]
Hey @mariusandra

The site is under "Permitted Domains/URLs" and i can see the posthog button as well:
![image](https://user-images.githubusercontent.com/12446111/90232699-5a61d400-de1d-11ea-86ff-219f12d1303e.png)


The first request to `your.posthog.instance/decide` look like this:
![image](https://user-images.githubusercontent.com/12446111/90234022-4a4af400-de1f-11ea-81ec-2efbd74988cc.png)
 SameSite is Lax. Manually setting it to None doesn't help.

This is how it looks when i click auth
![image](https://user-images.githubusercontent.com/12446111/90233053-cf350e00-de1d-11ea-985a-07d19e90b301.png)

Our page is a react app and we use the npm library. Posthog is first initialized after everything else is loaded.

**Comment by mariusandra** [comment]
Hi @SuperKruse , thanks for getting back!

It's still quite hard to understand what's happening for you. You originally wrote:

> I cannot get sign in to work, i can sign in without any problems, and the csrftoken is there as well.

Which is a bit contradictory.

Could you describe exactly what works and what doesn't? 

As far as I understand: you are using posthog on your own hosted instance... and you can use posthog fine, just the toolbar does not work? It shows up, but clicking "authorize" does nothing. Is this correct?

After authorizing, what happens? Do you get redirected to a new page and click a button? What is the second screenshot from? 

Perhaps a screencast or a quick call would be easiest to resolve this issue. Feel free to write to marius@posthog.com in case you'd prefer not to share all details in the open.

Also, we just released [version 1.13.0](https://posthog.com/blog/the-posthog-array-1-13-0) of PostHog, which includes a new setting for [securing your cookies](https://posthog.com/docs/deployment/securing-posthog#secure-cookies). In case your posthog is running behind HTTPS, all is good. If not, you might need to adjust the setting.

**Comment by Twixes** [comment]
Hey all! With the Toolbar out of beta, I think we can close this.
