### ISSUE TITLE
Custom Skeleton Loaders

### ISSUE THREAD

**Issue by lottiecoxon** [PostHog/posthog#11294]
## Introducing PostHogs very own custom loaders 

Moving away from [Ant Design's skeleton loader ](https://ant.design/components/skeleton/) we want to create a custom skeleton loader for our product. This will level up the user experience and create a more polished look to the dashboard. 
Currently with Ant Design, the skeleton loader is basic and universal - while this has worked well for the time being, it would be better to have loaders that represent the product more accurately. 

## Describe the solution you'd like

A new table skeleton loader default as well as 6 unique insight loaders that represent the different insights we provide. This is accompanied by color work as well as gradient size and timings- I would like to test this before shipping so may need some help from engineering in this department.

![Spinners](https://user-images.githubusercontent.com/65415371/184623481-65fb050f-1c53-4997-bf20-039de715f0f6.png)

## Describe alternatives you've considered

- Custom table skeleton loaders for different layouts- overall this would be too much effort and not gain us that much.

![Group 9063](https://user-images.githubusercontent.com/65415371/184623099-a59ae1f9-257d-4a70-bcda-df52f5c5f746.png)
![Group 9102](https://user-images.githubusercontent.com/65415371/184623109-62c06c1f-f21c-4195-80e8-34317f11dc77.png)

- More artistic and conceptual insight loaders - we soon realised that this was misleading having loaders that didn't closely represent what was inside the app. (example below)
![Group 9078](https://user-images.githubusercontent.com/65415371/184623044-2c58ce24-1ac7-4309-99b7-42a01308e8ea.png)

## Additional context
- [Ant Design](https://ant.design/components/skeleton/)
- [Figma](https://www.figma.com/file/Y9G24U4r04nEjIDGIEGuKI/PostHog-Design-System-One?node-id=2028%3A808)

**Comment by pauldambra** [comment]
for context

## time skeletons are visible for

90th percentile dashboard loading time: https://app.posthog.com/insights/7kneM83F
99th percentile dashboard loading time: https://app.posthog.com/insights/4iiCgU47

## time insight card loaders are visible for

90th percentile insight card refresh time: https://app.posthog.com/insights/vBsx3iUQ
99th percentile insight card refresh time: https://app.posthog.com/insights/iooDNhAg

and all in one place https://app.posthog.com/dashboard/49075

**Comment by LuisChiej** [comment]
As regards this, Are we looking at **moving away completely from** [Ant Design's skeleton loader ](https://ant.design/components/skeleton/) for a fully-fledged custom skeleton loader component for 6 unique insight and table skeleton, **or do we just want to make the Ant Design skeleton loader more polished and customized to properly represent your product on loading state?**

@clarkus, @lottiecoxon, @pauldambra
