### ISSUE TITLE
Show last active feature flags for a given Person or Group

### ISSUE THREAD

**Issue by benjackwhite** [PostHog/posthog#11327]
## Is your feature request related to a problem?

To aid with understanding and debugging, users would like the ability to easily see the last active feature flags for a Person. At the moment the only way of doing this is to look into the Person's events, expand the latest relevant client event and figure it out there.

## Describe the solution you'd like

A section as part of or below the Person's properties or a separate Tab showing the latest active feature flags (and maybe a link to that flag.

An indicator to say "these values are based on the latest event sent with feature flags active.

## Describe alternatives you've considered
-

## Additional context

[Relevant slack discussion ](https://posthog.slack.com/archives/C03JJKLEC8L/p1660663036050589)

**Comment by macobo** [comment]
What does "last active" mean in this context? Why not just evaluate what flags would be "currently" active instead of needing to go through events (which might be very old)?

Also don't forget about groups.

**Comment by neilkakkar** [comment]
I like the idea of currently active feature flags that show up on detail pages for persons / groups. We do it with recordings/cohorts/ related groups; I see no reason not to include active feature flags too.

**Comment by clarkus** [comment]
There are design assets for this at https://www.figma.com/file/XklcUpnAb8UYXJxVSZFNeI/Cohorts%2C-Persons-%26-Groups?node-id=5%3A2029.

**Comment by LuisChiej** [comment]
> There are design assets for this at https://www.figma.com/file/XklcUpnAb8UYXJxVSZFNeI/Cohorts%2C-Persons-%26-Groups?node-id=5%3A2029.

@clarkus, @neilkakkar , I cannot access the figma link

**Comment by clarkus** [comment]
> > There are design assets for this at https://www.figma.com/file/XklcUpnAb8UYXJxVSZFNeI/Cohorts%2C-Persons-%26-Groups?node-id=5%3A2029.
> 
> @clarkus, @neilkakkar , I cannot access the figma link

The link should work now.
