### ISSUE TITLE
Icon position regression - Web performance

### ISSUE THREAD

**Issue by clarkus** [PostHog/posthog#11337]
## Bug description

Icons should be center aligned vertically and horizontally within a 24px square container. 

<img width="312" alt="Screen Shot 2022-08-16 at 3 35 29 PM" src="https://user-images.githubusercontent.com/254612/184997075-897370f7-a2f3-4699-8455-59bc6f150ae5.png">

## How to reproduce

1. Go to web performance
2. Observe icon placement

## Environment

- [x] PostHog Cloud
- [ ] self-hosted PostHog, version/commit: please provide

**Comment by LuisChiej** [comment]
@clarkus, I'm new to the repo, Could you provide a more descriptive approach to reproduce

**Comment by LuisChiej** [comment]
Hello @clarkus, I still need clarification on this end, Thank you

**Comment by neilkakkar** [comment]
Hey @LuisChiej , could you please be more specific about what's not clear?

Notice in the above screenshot how the icon is not in the center. It's in the web-performance tab, https://app.posthog.com/web-performance, which you can enable locally by creating the `hackathon-apm` flag.

**Comment by LuisChiej** [comment]
Okay, thank you @neilkakkar

**Comment by LuisChiej** [comment]
@neilkakkar, Please how do I create a `hackathon-apm` flag

**Comment by neilkakkar** [comment]
on your local -> go to feature flags -> create flag -> name it `hackathon-apm`

**Comment by pauldambra** [comment]
@LuisChiej I was going to pick this up. But I can help you if you need any pointers...

I noticed on another issue you suggested you were working on multiple PRs. Better to finish a small number than to start many :)

**Comment by LuisChiej** [comment]
@pauldambra, this and quite a few others are almost done and ready to push
