### ISSUE TITLE
insight to measure intensity of usage by period

### ISSUE THREAD

**Issue by camerondeleone** [PostHog/posthog#11345]
## Is your feature request related to a problem?

Currently, the WAU aggregation gives us engagement, but there's no way to measure intensity of usage. WAU aggregation gives users who've done X event at least 1x in the trailing 7 days, but there is no way to break that down into buckets by the number of users who did it 2, 5, 10, 100x. 

## Describe the solution you'd like

There are a number of ways this could be implemented, but one would be a custom breakdown option for 'Weekly Active' that shows one series for each bin, with bins representing users who performed X event (1, 10, 50, 100...) times in the trailing 7 day window. Ideally bins are customizable but auto-created.

## Describe alternatives you've considered

It's possible to get this for the current (week, month, etc) by creating cohorts of users who have done X event Y times in the last Z periods, but if I want to look over many weeks/months, the cohort no longer represents the count of users who did X event Y times on a given past date, it represents the users who did X event Y times in the last Z days looking back from today, so we aren't measuring the total count of users including those who churned out of doing it, we're filtering by that same cohort that did it in the current period, and looking at their past activity. 

There are a few other views that almost get at this, such as historical conversion funnel or a modified retention view, but neither is exactly right.

**Comment by camerondeleone** [comment]
Discussed with @timgl in slack — the conclusion is that to address this, we should build advanced cohort type functionality (did event x times in trailing x day period, completed sequence...) into trend filters

https://posthog.slack.com/archives/C02E3BKC78F/p1660672383304609

**Comment by timgl** [comment]
I think the right solution to the problem is #11348 so I'll close this one
