### ISSUE TITLE
Behavioral filtering within insights

### ISSUE THREAD

**Issue by timgl** [PostHog/posthog#11348]
## Is your feature request related to a problem?

I want to be able to do cohort style behavioral queries, but over time. This way I can answer questions such "show me a count of users who have done Insight Analyzed at least 5 times on that day, over time". This shows intensity of usage, and would be the right solution to #11345

## Describe the solution you'd like

Within an insight, clicking on "+ Add filter", I'd want an option to have a behavioral filter like with cohorts:
<img width="288" alt="image" src="https://user-images.githubusercontent.com/1727427/185112789-f1f30027-98d7-4177-aa28-bff46be8a9a6.png">

The difference would be that we'd replace this:
<img width="413" alt="image" src="https://user-images.githubusercontent.com/1727427/185112850-8b26833b-a6c7-4ffe-9cce-97cda6be2e79.png">

with: "in each week", with optionally "trailing 7 days/weeks average".

[See this (internal) thread for an example and more context](https://posthog.slack.com/archives/C02E3BKC78F/p1660736887913629?thread_ts=1660672383.304609&cid=C02E3BKC78F)

## Describe alternatives you've considered

There isn't a great one right now in PostHog. The industry standard does have above.

## Additional context

@clarkus @neilkakkar @EDsCODE @camerondeleone

**Comment by macobo** [comment]
Duplicate of https://github.com/PostHog/posthog/issues/2594, related https://github.com/PostHog/posthog/issues/7963

**Comment by timgl** [comment]
Closing in favour of https://github.com/PostHog/posthog/issues/2594
