### ISSUE TITLE
Imprints for currently changing data

### ISSUE THREAD

**Issue by EDsCODE** [PostHog/posthog#1137]
**Is your feature request related to a problem? Please describe.**
I like to see exact differences/change in my analytics. I dont always remember the numbers when I view a metric a few times a day that's constantly changing

**Describe the solution you'd like**
I'd like to have a marker/notice that shows me the number/values that the metric was at the last time I viewed. For example if I look at a pie chart and the number is 600 and in an hour it becomes 700, it'd be nice to have a reminder that last viewed at (timestamp) : 600

**Describe alternatives you've considered**
Snapshot function where you can freeze an assortment of data for reference

**Additional context**
This feature makes sense for metrics that aren't time series based. So pie charts and tables would be a good place to start. The last datapoint on trend charts would also be nice

***Thank*** you for your feature request - we love each and every one!

**Comment by EDsCODE** [comment]
Additional Thoughts:
I come back to the dashboard and don't want to bother looking through each datapoint on a graph and remembering how it was compared to my last viewing. This applies to many of the stats that appear throughout posthog. When I use the toolbar/toolbutton I find really useful information however I'm rarely inclined to return to use it until maybe a few days/a week later because I won't be able to discern any notable difference. 

I think it'd be very powerful for Posthog to have a system that tracks all the differences even beyond just the few mentioned above. I would be very inclined to return to Posthog frequently if everytime I return, the app tells me what I missed and what's changed. Then I would use the toolbar a few times a day and get to witness the heatmap change. Even if it's a subtle change ("2 new users clicked get started", "The latest day on your dashboard 'click rate' has increased by 50") I would have a stronger reason to return.

**Comment by mariusandra** [comment]
Additional thought here: the toolbar heatmap could not only show the count, but the change in the count over time, e.g. a line graph for a rolling 7 day window.

**Comment by jamesefhawkins** [comment]
I think alerting is maybe the right way to think about this.

For some metrics, if there is an trend graph with a line, I could see this being redundant on logging in - a trend graph illustrates in front of you what the change is. However, if you could set up alerts, you then wouldn’t even need to log in at all or you could log in and see the three new users who did something important

I can see a couple of use cases, which could all be webhooks one day:

- a user signed up
- a key metric changed by a certain percent or preset amount

Keep the ideas coming!!

**Comment by paolodamico** [comment]
We've talked about this in terms of improving engagement but unsure if we want to move forward with this. @Twixes ?

**Comment by EDsCODE** [comment]
@marcushyett-ph

**Comment by Twixes** [comment]
I think we've determined we'll do this in the medium term.
