### ISSUE TITLE
Hobby deployment get stuck in the last stage (way more than 10 minutes)

### ISSUE THREAD

**Issue by adrianwix** [PostHog/posthog#11387]
## Bug description

My hobby deployment is getting stuck at the end of the script. (It has like 20 minutes there or more)

![image](https://user-images.githubusercontent.com/37629556/185598639-715e7e26-8d98-411a-b7bc-66011dad842f.png)

EDIT 1: It may be the firewall of the lightsails instance
![image](https://user-images.githubusercontent.com/37629556/185600428-9c31df78-520a-441f-86f4-585c7d9597ac.png)

![image](https://user-images.githubusercontent.com/37629556/185599595-e87f3d60-d5dd-4689-b2e9-d6b0238a05fe.png)

EDIT 2: Caddy logs
![image](https://user-images.githubusercontent.com/37629556/185610155-5109020c-46e4-4472-9991-49be50f1b682.png)

## How to reproduce

1. Run /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/posthog/posthog/HEAD/bin/deploy-hobby)" 
2. Select the latest-release option (this was done on 19/08/2022 at 11:00 am CEST)
3. Add a Sentry DNS
4. Add the URL where posthog will be available

## Environment

- [ ] PostHog Cloud
- [x] self-hosted PostHog, version/commit: latest-release 19/08/2022 at 11:00 am CEST

**Comment by adrianwix** [comment]
Honestly not sure which proxy it is. Is it something coming from Hobby deployment or related to AWS?

I am using AWS Lightsails instance to run the hobby deployment (Ubuntu 20.04)

**Comment by adrianwix** [comment]
EDIT 3: 
![image](https://user-images.githubusercontent.com/37629556/185611740-fba2fbe9-2371-414e-843a-55c40e6f826d.png)

The script is still stuck but the website is accessible in the browser. Even with HTTPS.

**Comment by adrianwix** [comment]
EDIT 3:
The script is still stuck even if the frontend is running with HTTPS. 
![image](https://user-images.githubusercontent.com/37629556/185612720-db7eb652-7332-47bb-baf1-a17381bd5667.png)

**Comment by adrianwix** [comment]
The problematic line is: 
![image](https://user-images.githubusercontent.com/37629556/185651636-4cf20511-5f29-4db2-b8ac-18cd626b2e56.png)

**Comment by timgl** [comment]
@adrianwix You can safely ignore that message in this case, given PostHog is up

@fuziontech worth seeing if you can fix?
