### ISSUE TITLE
(intermediate value))?.trim is not a function

### ISSUE THREAD

**Issue by ElementaryMyDearWatson1** [PostHog/posthog#11390]
Hello, we cannot access any of our recordings or user profiles pages due to the following error: 
An error has occurred
TypeError (ID c6a0bbcdbe744d16b6fd0f5fefae2868)
((intermediate value)(intermediate value)(intermediate value) || (intermediate value))?.trim is not a function
We've registered this event for analysis, but feel free to contact us directly too.

https://prnt.sc/OplJahDFaYb-

## How to reproduce

1. Log into posthog on our account
2. Access either "Recordings" or "Persons & Groups"
3. The page explodes 

## Environment

- [x] PostHog Cloud
- [ ] self-hosted PostHog, version/commit: please provide

## Additional context
This is stopping us from using the tool at all for our use-cases

**Comment by benjackwhite** [comment]
Ooh that's nasty. I'll take a look!

**Comment by benjackwhite** [comment]
@ElementaryMyDearWatson1 - could you email me with your account details at `hey@posthog.com`?

**Comment by ElementaryMyDearWatson1** [comment]
@benjackwhite done! Thanks
