### ISSUE TITLE
Filter by Event Type seems not working

### ISSUE THREAD

**Issue by lksv** [PostHog/posthog#1139]
**Describe the bug**
Filter by "Event Type" seems not working in Evnets view as well as in Action definition.

**To Reproduce**
1. Go to events page on app.posthog.com
2. Filter based on `Event Type` and try  `equal` or `contains`. As value set `submit`.
3. You will see no events match the filter.

If you set filter to `$type is not set` then you will see all events (even the "submitted form" events).
The same behavior is within creating/editing Action when add filter with `$type`.

**Expected behavior**
I am able to filter events based on event type e.g. 'click', 'submit', 'change'.

**Screenshots**
![posthog1](https://user-images.githubusercontent.com/1152494/86391235-bf140580-bc99-11ea-9037-76f2d2fdda5c.png)
![posthog2](https://user-images.githubusercontent.com/1152494/86391253-c89d6d80-bc99-11ea-9b62-f08f83739aaa.png)
![posthog3](https://user-images.githubusercontent.com/1152494/86391257-caffc780-bc99-11ea-8b56-6deeaa732358.png)

**Hosted or self hosted?:**
On app.posthog.com

**Additional context**

Together with #274 I am not able to distinguish submitting form from input (checkbox) field change which blocks me to create Action.

**Usability hint**
It is a little bit confusing for me, that in select box is "Event Type" and then it's showing as "$type" (and in code it's `$event_type`). Aslo "Evnet Type" [help suggest 'click', 'submit', 'change'](https://github.com/PostHog/posthog/blob/master/frontend/src/lib/components/PropertyKeyInfo.js#L135) but on Event page (in the events list) I see "submitted form", "clicked input", etc.

**Comment by timgl** [comment]
Thanks for raising this! When I try filering by "Event Type" it shows `$event_type` after filtering, which gives the correct results:
![image](https://user-images.githubusercontent.com/1727427/86588038-2d531380-bf8b-11ea-91ed-f94e1efc39e2.png)

I'm not sure why it flips it to `$type` in your case. I can't find any instances of `$type` in our code either. Did you manually sent an event with $type maybe? Could you screenshot the moment you select 'Event Type' from the dropdown?

**Comment by lksv** [comment]
Attaching animated gif recorded on https://app.posthog.com/action/868

![posthog-event_type](https://user-images.githubusercontent.com/1152494/86593283-3517b580-bf95-11ea-9c4e-0f00472bc7cf.gif)
