### ISSUE TITLE
Insight keyword filter - empty state doesn't match context

### ISSUE THREAD

**Issue by clarkus** [PostHog/posthog#11400]
## Bug description

When you filter the list of insishts such that there aren't any matching results, the empty state shown doesn't really align to the context. The header is accurate to this context, but the rest of the empty state content is more targeted towards creation. 

<img width="1144" alt="Screen Shot 2022-08-19 at 11 22 52 AM" src="https://user-images.githubusercontent.com/254612/185683369-7620a181-afa4-4388-b1e3-5123e2151456.png">

Ideally this empty state would guide the user on how to find what they're looking for, not push them to create something new. The insight count should also reflect that there are no matching insights, not that there are "no insights yet". 

An example of content that would be more targeted in this scenario:

```
Header: No insights matched your search for "[keyword]"
Description: Refine your keyword search, or try using other filters such as type, last modified, created or by. 
```

## How to reproduce

1. Go to insights
2. Filter the list on a non-matching keyword
3. Observe the empty state content 

## Environment

- [x] PostHog Cloud
- [ ] self-hosted PostHog, version/commit: please provide

**Comment by Nike682631** [comment]
@clarkus  is this issue available to work on?

**Comment by clarkus** [comment]
> @clarkus is this issue available to work on?

Yes. If you'd like to work on it, feel free to assign it to yourself and get started. Thanks!

**Comment by Nike682631** [comment]
@clarkus  I think you would need to assign me as I don't have access rights to assign it to myself

**Comment by mariusandra** [comment]
@Nike682631 we don't assign issues (even if we may have in the past). If you want to work on something, just work on it, and submit a PR.
