### ISSUE TITLE
AsyncMigrations do not report errors due to `execute_on_each_shard` 

### ISSUE THREAD

**Issue by macobo** [PostHog/posthog#11408]
## Bug description

A failing async migration (0006) got marked as complete on cloud.

## How to reproduce

```python
from posthog.async_migrations.utils import *
from posthog.client import sync_execute

sync_execute("SELECT foo") # Fails
execute_on_each_shard("SELECT foo") # Succeeds
```

This happens for both `CLICKHOUSE_ALLOW_PER_SHARD_EXECUTION` and without it.

## Environment

- [x] PostHog Cloud
- [ ] self-hosted PostHog, version/commit: please provide

**Comment by hazzadous** [comment]
Maybe linked? https://github.com/PostHog/posthog/issues/11283
