### ISSUE TITLE
disable session not working

### ISSUE THREAD

**Issue by fring-12** [PostHog/posthog#11410]
## Disable session not working properly

hello, I am using posthog for record a particular route in my website. on page load I am using:

```
posthog.init(posthogSecretKey, {
      api_host: posthogApiHost,
      disable_session_recording: false,
    });
```
    
and when the component is unmounted I am using using:
    
```
    posthog.init(posthogSecretKey, {
      api_host: posthogApiHost,
      disable_session_recording: true,
    });
```
    
but it seems its not working properly. the session recording is not disabled for other page.  Am i missing something?

**Comment by timgl** [comment]
Do you have a single page app? If so, you need to call either
`posthog.sessionRecording.stopRecording()` or `posthog.sessionRecording.startRecordingIfEnabled()` in between page changes for it to work.
