### ISSUE TITLE
Loads dashboard without user session

### ISSUE THREAD

**Issue by hameedhub** [PostHog/posthog#11429]
## Bug description
The application dashboard loads without active user session, even when I logged out, i get page not found error
*Please describe.*  
After spinningup all the required process with docker, and starting with ./bin/start on the terminal the application loads on http://localhost:8234 display the home page but renders error.
*If this affects the front-end, screenshots would be of great help.*  

<img width="1680" alt="Screenshot 2022-08-23 at 10 59 18 AM" src="https://user-images.githubusercontent.com/46590803/186132139-c9ce6a8a-66dc-4bc7-ab56-21f3dd3da962.png">

## How to reproduce

1. follow the instruction doc instruction https://posthog.com/handbook/engineering/developing-locally
 for mac OS
## Environment

- [ ] PostHog Cloud
- [x] self-hosted PostHog, version/commit: please provide

**Comment by hameedhub** [comment]
@clarkus

**Comment by timgl** [comment]
Hi! You need to go to http://127.0.0.1:8000/, not :8234
