### ISSUE TITLE
SMTPServerDisconnected

### ISSUE THREAD

**Issue by adrianwix** [PostHog/posthog#11438]
## Bug description

*Please describe.*  
I am trying to setup Posthog emails for a hobby instance with no luck.

I see the following errors in Sentry

```sh
SMTPServerDisconnected: Connection unexpectedly closed
  File "posthog/email.py", line 99, in _send_email
    connection.open()
  File "django/core/mail/backends/smtp.py", line 62, in open
    self.connection = self.connection_class(self.host, self.port, **connection_params)
  File "smtplib.py", line 255, in __init__
    (code, msg) = self.connect(host, port)
  File "smtplib.py", line 341, in connect
    (code, msg) = self.getreply()
  File "smtplib.py", line 403, in getreply
    raise SMTPServerDisconnected("Connection unexpectedly closed")
```

## How to reproduce

1. Setup AWS SES
2. Try to invite someone or change a value in the Posthog instance settings

## Environment

- [ ] PostHog Cloud
- [x] self-hosted PostHog, version/commit: 912e258e12f923596a66f9898a41a367b5a8fc0f

## Additional context

My current setup is hosting on AWS Lightsails, using AWS SES for SMTP, and a Posthog hobby instance

In order to test if the problem was with AWS I setup a test script to send an email with nodemailer and it worked

```js
"use strict";
const nodemailer = require("nodemailer");

// async..await is not allowed in global scope, must use a wrapper
async function main() {
    // create reusable transporter object using the default SMTP transport
    let transporter = nodemailer.createTransport({
        host: "email-smtp.eu-central-1.amazonaws.com",
        port: 465,
        secure: true, // true for 465, false for other ports
        auth: {
            user: 'XXXXXXXXXXXXXXXXXXXXXXX',
            pass: 'YYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYY',
        },
    });

    // send mail with defined transport object
    let info = await transporter.sendMail({
        from: '"Max Mustermann 👻" <xxxx@aaaaaa.com>', // sender address
        to: "xxxx@aaaaaa.com", // list of receivers
        subject: "Hello ✔", // Subject line
        text: "Hello world?", // plain text body
        html: "<b>Hello world?</b>", // html body
    });

    console.log("Message sent: %s", info.messageId);
    // Message sent: <b658f8ca-6296-ccf4-8306-87d57a0b4321@example.com>

    // Preview only available when sending through an Ethereal account
    console.log("Preview URL: %s", nodemailer.getTestMessageUrl(info));
    // Preview URL: https://ethereal.email/message/WaQKMgKddxQDoou...
}

main().catch(console.error);
```

I also tried to run the following command to see if I could connect with the SMTP server from the instance

```sh
telnet email-smtp.eu-central-1.amazonaws.com 465
Trying 52.29.77.225...
Connected to email-smtp.eu-central-1.amazonaws.com.
```

**Comment by timgl** [comment]
Hi, have you read https://posthog.com/docs/self-host/configure/email ?

I suspect you need to set `EMAIL_USE_TLS` to `1`

**Comment by adrianwix** [comment]
Yes, I read it. I am using Instance Settings. So maybe it is not properly recognizing it.

![image](https://user-images.githubusercontent.com/37629556/186245477-ad741e5c-653a-4e40-b9e3-a6ef2955cd73.png)

**Comment by adrianwix** [comment]
Yes, I read it. I am using Instance Settings so maybe it is not recognizing it

![image](https://user-images.githubusercontent.com/37629556/186357702-f89bf852-f4c4-4324-b225-85091a8a2156.png)

**Comment by timgl** [comment]
Hm, have you tried using SSL instead of TLS?

**Comment by adrianwix** [comment]
SSL worked somehow. It is strange since the [AWS SES documentation](https://docs.aws.amazon.com/ses/latest/dg/send-email-smtp.html#:~:text=Client%20software%20that%20can%20communicate%20using%20Transport%20Layer%20Security%20(TLS).) asks for a TLS client. Maybe I got the whole thing wrong.

Sidenote: In the intance settings it should not be possible to select SSL and TLS both at the same time
![image](https://user-images.githubusercontent.com/37629556/186362603-d7a2bd5b-9bd0-4b9f-b818-04ad8027228e.png)

Thanks for the help!
