### ISSUE TITLE
Pie chart styling update 

### ISSUE THREAD

**Issue by lottiecoxon** [PostHog/posthog#11433]
### Before 

Currently (in my humble opinion) we employ a pretty chunky pie chart for displaying data. There is quite a lot of negative space which could be better used to enhance the presentation of data. 

![Screenshot 2022-07-15 at 14 31 1](https://user-images.githubusercontent.com/65415371/186126214-005c6d3c-f91c-4450-835e-324424974b7c.png)

### Inspiration 

After some research into the world of pie and wheel charts I soon discovered that we don't need to live in a world full of clunky pies. 

![Screenshot 2022-07-12 at 15 30](https://user-images.githubusercontent.com/65415371/186126641-a8d4facb-dfca-4f83-84d0-35de88d0a378.png)

Looking online at examples of what other companies had experimented with I came across this example. Its bright colours paired with the thin stroke and wide base creates a modern and fresh approach to a basic chart type.

### After 

Taking inspiration from my research I created this, a thin stroke wheel chart, with interactive hover states and more information shown within the insight box itself. 

Here you see our wheel chart to the left with a large number total underneath, then to the right we have the title of the wheel chart along with the smaller text description, below these titles is a list of answers, their names and the correlating number linked to that option.

![fake trend chart](https://user-images.githubusercontent.com/65415371/186153055-f4972866-d0dc-4380-9ab4-064247d93c9f.png)

When hovered over the stroke should go from 20px to 28px to show which answer you are hovering over, while at the same time the correlating answer to the right will highlight with a blue background. 

![fake trend chart 2](https://user-images.githubusercontent.com/65415371/186153045-04a6834c-f62b-41ff-86ca-6ff1370e34e1.png)

 Ideally these check boxes would be interactive to help with distinguishing answers when there are a lot of variables to compare, while still seeing the other faded unchecked variables at the same time. 

![fake trend chart-1](https://user-images.githubusercontent.com/65415371/186153052-a362d45c-8829-4529-9a0e-0afbfe636bcc.png)

Here you can see an example of when the user may have multiple options to interact with, the right hand table is scrollable so you can still select only a select few answers to compare. 

![large trend chart](https://user-images.githubusercontent.com/65415371/186156730-43898041-a2c0-45d8-a0ba-95bb2532f8f6.png)

**Comment by pauldambra** [comment]
Are these in figma for comments and detail?

One piece of feedback in #11368 was about visibility of the values. So I love that they're present here. Could they be even more prominent? In the yes/no example I can see 124 responses very prominently but 67 yes, 57 no is probably the important information... 

Or in a simple case like this maybe we guide someone that a table might be better than a pie chart 🤔

**Comment by lottiecoxon** [comment]
@pauldambra I have tagged you on Figma  in a comment to find the exact space but also here is [the link ](https://www.figma.com/file/HwUmk7WqccLkGgNNGAs4zN/Art-board?node-id=6591%3A46744)

**Comment by lottiecoxon** [comment]
## out of the box idea alert 🚨 

After Pauls feedback I got thinking how can we better show the division of the pie chart data, and not just the overall total. Here is a division box (not a very creative name) where we see how the overall total is broken down. The divided numbers are paired with a colour signifier above them to show which part of the pie chart they represent. Then to the right we have the labeled variables with bolder and more prominent numbers. 

Below I have examples of how this would work for smaller and larger divisions and how the division box would cope with different quantities of data. 

### Small example

![pie chart experiment 5 b](https://user-images.githubusercontent.com/65415371/186412979-3a9f6474-2512-4a35-bca6-56378b5f1442.png)

### Larger example 1:

Here the box is full but not overflowing 

![pie chart experiment 05](https://user-images.githubusercontent.com/65415371/186411581-8b0d02a9-be7f-4da0-820d-9a1ddbe2aed5.png)

### Large example 2 

Here the division box has too many pieces of data to show at once so we adopt a sideways scrollable box that uses the same scroll indicators as our other tables.

![pie chart experiment 5 c](https://user-images.githubusercontent.com/65415371/186411573-039cdf75-98dd-4e4a-a810-145c2b9608b9.png)

**Comment by lottiecoxon** [comment]
it would be interesting to see the majority of use cases with pie charts and if they are used for a lot of different variables or just a few?

**Comment by clarkus** [comment]
related https://github.com/PostHog/posthog/issues/4403#issuecomment-850708181

**Comment by pauldambra** [comment]
We did a bunch of work around this... I'm guessing it can be closed (feel free to re-open if not 😊)
