### ISSUE TITLE
ResourceWarning on `posthog.capture()`

### ISSUE THREAD

**Issue by elongl** [PostHog/posthog#11458]
## Bug description

I'm getting this unwanted warning coming from your library whenever I run `posthog.capture()`.

```py
sys:1: ResourceWarning: unclosed <ssl.SSLSocket fd=9, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('10.0.0.46', 56584), raddr=('34.202.126.243', 443)>
```

I've also attempted to silence it using the code below but it didn't work, it seems that `posthog` or one of its libraries override this.
```py
import warnings
warnings.filterwarnings(action="ignore", message="unclosed", category=ResourceWarning)
```

I've also muted the `posthog` logger which didn't have any affect.
```py
logging.getLogger('posthog').disabled = True
```

This is really important for me to fix as all my users are getting this error and it confuses them.

*Please describe.*  
*If this affects the front-end, screenshots would be of great help.*  

## How to reproduce

1. Just call `posthog.capture()`.

## Environment

- [x] PostHog Cloud
- [ ] self-hosted PostHog, version/commit: please provide

**Comment by neilkakkar** [comment]
Closing in favour of https://github.com/PostHog/posthog-python/issues/73
