### ISSUE TITLE
Dismissible banners continue to show after page reloads

### ISSUE THREAD

**Issue by clarkus** [PostHog/posthog#11475]
## Bug description

Dismissible banners reappear after being dismissed.

https://user-images.githubusercontent.com/254612/186477576-c5142a53-1753-435a-9c17-d4b204fb59c9.mov

## How to reproduce

1. Find a page with a dismissible banner on it (see data management)
2. Dismiss the banner
3. Reload the page
4. Note that the banner persists

## Environment

- [ ] PostHog Cloud
- [ ] self-hosted PostHog, version/commit: please provide

## Additional context

- [Internal slack thread ](https://posthog.slack.com/archives/C034XD440RK/p1661359590678229)

**Comment by Nike682631** [comment]
@clarkus  is this issue available to work on?

**Comment by clarkus** [comment]
> @clarkus is this issue available to work on?

Yes. If you'd like to work on it, feel free to assign it to yourself and get started. Thanks!

**Comment by Nike682631** [comment]
I would probably need you to assign it to me. I don't have enough access rights for it.

**Comment by Twixes** [comment]
This particular case is gone now. I agree we should be more mindful of this in the future.
