### ISSUE TITLE
UX - Label graph lines

### ISSUE THREAD

**Issue by wundo** [PostHog/posthog#1148]
I think it would be a great UX improvement allowing the user to label the Graph lines. 

When you are filtering the same action more than once and filtering by a property it's really hard to know which line is what.

**Comment by EDsCODE** [comment]
Thanks for the suggestions! Are you thinking of a by default visible legend that labels each line?

**Comment by wundo** [comment]
I don't mind the hover as it's now, but I'd like to have a way to identify which line is what.

**Comment by mariusandra** [comment]
I agree with @wundo that it's really hard to know which line is what when you're filtering trends by the same action/event, with variations in the properties. For example DAUs vs total $pageviews:

![screencast 2020-07-07 14-16-23](https://user-images.githubusercontent.com/53387/86780008-876fd980-c05c-11ea-99fb-32bfdf0b70c8.gif)

While the option to rename would be a nice addon, I think a better solution is to have sensible defaults. In this case it should show "$pageview (DAU)" and "$pageview (Total)" in the tooltip. 

An approach would be to check if there are any two identical labels... and if so, add details from the filter to both until they differ.

**Comment by wundo** [comment]
@mariusandra even in they are not exactly the same, the user might get confused:

For instance, I'm filtering by **different fields** here:

![confusing-labels](https://user-images.githubusercontent.com/113942/86917889-40d1bc00-c0fc-11ea-9907-88479a17054e.gif)

Impossible to know which is which

**Comment by Twixes** [comment]
We're now showing properties much more clearly!

**Comment by paesku** [comment]
@Twixes 
labels might already be improved but I still miss some more information. Some of the filters are reflected in the label, I'd like to give each serie it's own custom label:

<img width="1105" alt="labels" src="https://user-images.githubusercontent.com/3726371/123865864-b1d13b80-d92c-11eb-9a50-c0d8b4a8a75e.png">

**Comment by wundo** [comment]
I totally agree with @paesku , would mind re-opening it?

**Comment by mariusandra** [comment]
Hey all, I guess the issue was closed because [this](https://github.com/PostHog/posthog/issues/4156) is now implemented, yet just released to ~20% of users.

![image](https://user-images.githubusercontent.com/53387/123925829-93e6f380-d98b-11eb-8abe-0bc6b4392972.png)

@paolodamico thoughts on releasing this to everyone?

**Comment by paolodamico** [comment]
While I do think the new tooltips experience will make this significantly better I agree with @wundo & @paesku that we should allow custom labeling of each series. Two main reasons for this: a) a custom label can potentially provide a lot more value that whatever we can create automatically, b) there are edge cases that complicate custom labels (for example today I ran into the issue of using formulas). I think it's worth building this. _FYI, our new mockups, both for nailing funnels & new querying experience already includes a consideration for this._

Re releasing the new tooltips & legend table to everyone, yeah I think it makes sense. Will release to everyone on cloud today, but will wait to release to self-hosted until the next release as I think I got a few improvements in after the latest release.

**Comment by clarkus** [comment]
This is taken from the work supporting https://github.com/PostHog/posthog/issues/3408. In the revised design for query building, there is affordance for a rename action. Clicking that action would trigger a modal that represents the current property name with an option for providing a new name value. Once submitted, both values are shown in the builder, but only the renamed value is shown in the corresponding visualization. This is shown specific to funnels. Other insight types would have different label values based on their corresponding labels. Please let me know if you have any feedback on these proposed changes. 

![Edit Insight](https://user-images.githubusercontent.com/254612/127387112-71afa1bb-77da-4aaf-b24d-99f36bfe4935.png)
![Rename Query Step](https://user-images.githubusercontent.com/254612/127387114-5365ff23-ae62-4e83-b647-7fcf37df58b6.png)

**Comment by paolodamico** [comment]
This is indeed something we want to implement but keeping #5207 instead to track this.
