### ISSUE TITLE
bug: insight/trend: event selector non-responsive

### ISSUE THREAD

**Issue by camerondeleone** [PostHog/posthog#11498]
## Bug description

I'm not sure how to get into this state but it's happened a few times in the last couple days. I don't see any 404 in network except gravatar, so pretty sure this is a UI/frontend issue exclusively. 

https://user-images.githubusercontent.com/56287180/186677137-ab500b65-c84e-4297-9c83-82990ef52c3b.mov

## How to reproduce

1. ??
2.
3.

## Environment

- [ ] PostHog Cloud
- [ ] self-hosted PostHog, version/commit: please provide

**Comment by mariusandra** [comment]
@camerondeleone still a thing? 🤔

**Comment by camerondeleone** [comment]
@mariusandra I hadn't seen it in a few days, but I did run into it again today. [This](https://app.posthog.com/recordings?filters=%7B%22actions%22%3A%5B%5D%2C%22events%22%3A%5B%7B%22id%22%3A%22cohort%20updated%22%2C%22type%22%3A%22events%22%2C%22order%22%3A0%2C%22name%22%3A%22cohort%20updated%22%7D%5D%2C%22properties%22%3A%5B%7B%22key%22%3A%22email%22%2C%22value%22%3A%5B%22cameron%40posthog.com%22%5D%2C%22operator%22%3A%22exact%22%2C%22type%22%3A%22person%22%7D%5D%2C%22date_from%22%3A%222022-08-17%22%2C%22date_to%22%3Anull%2C%22offset%22%3A0%2C%22session_recording_duration%22%3A%7B%22type%22%3A%22recording%22%2C%22key%22%3A%22duration%22%2C%22value%22%3A60%2C%22operator%22%3A%22gt%22%7D%7D#sessionRecordingId=1831845626323b4-0e21df45f0637f-1b525635-13c680-183184562641572) session recording captured it, if you navigate to where I'm on an insight at around 1:54 until the end, trying to change the event from `pageview` to something else, but unable.
