### ISSUE TITLE
Data Management view contains an undefined icon component and leads to an infinite loading state

### ISSUE THREAD

**Issue by h2xd** [PostHog/posthog#11508]
## Bug description

The [Data Management](https://app.posthog.com/data-management/events) view is blocked by an undefined icon component (`<UnverifiedEvent />`). This leads to an infinite loading state.

![image](https://user-images.githubusercontent.com/19648055/186870718-2d12e03d-f7a0-4fa0-afd2-2666e553c4f5.png)

## How to reproduce

1. Open PostHog
2. Click on [Data Management](https://app.posthog.com/data-management/events)
3. Reload page
4. Should show loading state
5. Should `console.error` the following state `Uncaught (in promise) ReferenceError: UnverifiedEvent is not defined
    at EventDefinitionsTable.tsx:51:16`

## Environment

- [x] PostHog Cloud
- [ ] self-hosted PostHog, version/commit: please provide

**Comment by pauldambra** [comment]
Hey @h2xd, thanks for the detailed report 🙌 

I just raised https://github.com/PostHog/posthog/pull/11509 which fixes this.

Next step is to figure out how this made it through CI 😵‍💫

**Comment by h2xd** [comment]
Thank you very much @pauldambra for your quick response and fix! 🥇
