### ISSUE TITLE
Dropdowns look different

### ISSUE THREAD

**Issue by mariusandra** [PostHog/posthog#11514]
## Bug description

Casually clicking around on a random page, I'm left wondering why some dropdowns have a blue border and some don't.

![2022-08-26 12 14 01](https://user-images.githubusercontent.com/53387/186882426-7422bcc9-a50e-4d9b-849f-0817af693b53.gif)

Is this how it should be?

## Environment

- [ ] PostHog Cloud
- [ ] self-hosted PostHog, version/commit: please provide

**Comment by Twixes** [comment]
This is intended in that those with a blue border are "actionable" (mostly menus, e.g. it seems the "Launch Toolbar" one lacks it) and those with a gray border are more "informational". I don't think this is documented though. CC @clarkus

**Comment by clarkus** [comment]
Blue borders are for menus that are tied to inputs or forms - they're extending that focus style from the corresponding input to the menu used to complete it. The cases for non-blue borders are when the contents are purely navigational - they're not acting as input so much as they are navigation from one context to another. That said, if it's easier to just have one style menu, we can drop the blue border treatment and use our default border gray everywhere.

**Comment by mariusandra** [comment]
Understood. Though, subjectively, when I browse the interface and find two similar menus (e.g. projects & dashboards), where one has a border and one doesn't, the app feels... inconsistent, which is a fancy word for broken. Thus I'd be in favor of unifying them, no matter which direction that takes. I'd even put the blue border around more things...

**Comment by clarkus** [comment]
Sure let's consolidate to a single border style and focus it more towards that active-blue treatment. I'll update the design system docs, but generally we should be OK to use this everywhere.

**Comment by Twixes** [comment]
Resolved in PostHog 3000.
