### ISSUE TITLE
Toolbar feature flag multivariate contrast

### ISSUE THREAD

**Issue by mariusandra** [PostHog/posthog#11513]
## Bug description

Moving to strong primary colors changed this:

<img width="473" alt="image" src="https://user-images.githubusercontent.com/53387/186881664-3e3e8ed0-895d-400d-a2f9-45ecd7a7aef2.png">

We should remove the background color from the selected multivariate option. We can use a blue left border to indicate selection, or just keep it bold.

## Environment

- [ ] PostHog Cloud
- [ ] self-hosted PostHog, version/commit: please provide

**Comment by anjola-adeuyi** [comment]
Hi @mariusandra, I am interested in resolving this issue but I can't seem to find how the `feature flag UI` is triggered or where it's located in the dashboard. Could you please help me with a guide on how to reproduce this issue, many thanks.

<img width="525" alt="Screenshot 2022-08-29 at 17 27 44" src="https://user-images.githubusercontent.com/57623705/187249086-d4832a0f-4be5-4e42-9798-1c74f685abd5.png">

**Comment by mariusandra** [comment]
Hey @anjola-adeuyi . This UI is in the toolbar, which opens when you click "Launch Toolbar" from the sidebar.

**Comment by anjola-adeuyi** [comment]
@mariusandra Thanks for the guide, 
I just re-started the app and followed your direction, 
The screenshot below shows where I've gotten so far on finding the `Feature Flag UI` through the `Launch Toolbar` on the sidebar, **Please how do I go further from here?**

<img width="1787" alt="Screenshot 2022-08-30 at 13 05 29" src="https://user-images.githubusercontent.com/57623705/187432239-fbbe74cd-c9ad-4dc5-bb07-7d9659f67ef2.png">

**Comment by clarkus** [comment]
The feature flag list should be updated to use our highlight-blue used in other menu contexts. Not sure what the variable name is, but it equates to the hex value #E8EDFF. Menu examples are available at https://www.figma.com/file/Y9G24U4r04nEjIDGIEGuKI/PostHog-Design-System-One?node-id=3141%3A1234.

**Comment by anjola-adeuyi** [comment]
@clarkus This works, the design seems minimal and professional for highlighted or hovering states on the menu. The last blocker I need some bit of assistance is in trying to reproduce or get the feature flag list to pop up on my dashboard as well so I can implement the fix, I've explored all the steps above probably a short video illustration or gif would help, Many thanks. cc: @clarkus @mariusandra

**Comment by mariusandra** [comment]
Thanks @clarkus
@anjola-adeuyi add `http://localhost:8000` as an authorized URL and launch the toolbar on it. It should just show up on your posthog dev instance then.

**Comment by anjola-adeuyi** [comment]
@mariusandra I just followed your direction and this is what shows up after the last step, so I did a recording probably it would be easier for you to understand me and advise me accordingly on the last step of reproducing the `toolbar-feature-flag` popping up on mine as well, many thanks. 

https://www.loom.com/share/b6de064eb8164adf913190bf20ee1fa9

**Comment by mariusandra** [comment]
As you can see on the zoom, the toolbar shows up:
<img width="2607" alt="Screenshot 2022-08-31 at 12 20 10" src="https://user-images.githubusercontent.com/53387/187656798-a27921e3-9e80-4115-ba34-a3e6e2fb78f6.png">

**Comment by anjola-adeuyi** [comment]
Yea @mariusandra... I finally got you right, It's now showing. 
kindly view my screenshot below as I currently have just one feature-flag of `control-one` to toggle

<img width="583" alt="Screenshot 2022-08-31 at 12 13 09" src="https://user-images.githubusercontent.com/57623705/187665833-665e94ab-a7e9-44e8-88b8-e9e392bf0c55.png">

while your screenshot had about seven (7) feature flags to toggle, how can I access the seven toggles like yours? cc: @mariusandra 

<img alt="image" width="473" src="https://user-images.githubusercontent.com/53387/186881664-3e3e8ed0-895d-400d-a2f9-45ecd7a7aef2.png">

**Comment by mariusandra** [comment]
That shows up when you use a multivariate feature flag:

<img width="1626" alt="image" src="https://user-images.githubusercontent.com/53387/187668666-30db9a14-5835-4218-a84a-f63936dd5f61.png">

... which as I remember now, is unfortunately a PostHog Enterprise feature. That's why you probably didn't find it. My apologies for not realising this sooner. 

The EE features are a lot more complex to set up under development, so perhaps it's easier to find some other "[good first issue](https://github.com/PostHog/posthog/issues?q=is%3Aopen+is%3Aissue+label%3A%22good+first+issue%22)" to work on instead.

However, if you're up for it, there's a way around it this time. You can edit the `filters` column in the `posthog_featureflag` table for your flag to contain this JSON:

```json
{"groups": [{"properties": [], "rollout_percentage": null}], "multivariate": {"variants": [{"key": "control", "rollout_percentage": 50}, {"key": "test", "rollout_percentage": 50}]}}
```

That should get some groups showing in the interface.

I won't be able to guide you through editing a column in a database table however, as that should be table stakes for any software developer and not the best use of our time. :)

**Comment by anjola-adeuyi** [comment]
> That shows up when you use a multivariate feature flag:
> 
> <img alt="image" width="1626" src="https://user-images.githubusercontent.com/53387/187668666-30db9a14-5835-4218-a84a-f63936dd5f61.png">
> 
> ... which as I remember now, is unfortunately a PostHog Enterprise feature. That's why you probably didn't find it. My apologies for not realising this sooner.
> 
> The EE features are a lot more complex to set up under development, so perhaps it's easier to find some other "[good first issue](https://github.com/PostHog/posthog/issues?q=is%3Aopen+is%3Aissue+label%3A%22good+first+issue%22)" to work on instead.
> 
> However, if you're up for it, there's a way around it this time. You can edit the `filters` column in the `posthog_featureflag` table for your flag to contain this JSON:
> 
> ```json
> {"groups": [{"properties": [], "rollout_percentage": null}], "multivariate": {"variants": [{"key": "control", "rollout_percentage": 50}, {"key": "test", "rollout_percentage": 50}]}}
> ```
> 
> That should get some groups showing in the interface.
> 
> I won't be able to guide you through editing a column in a database table however, as that should be table stakes for any software developer and not the best use of our time. :)

That's understandable, was nice exploring this particular issue till this moment, I'd definitely choose to find some other "[good first issue](https://github.com/PostHog/posthog/issues?q=is%3Aopen+is%3Aissue+label%3A%22good+first+issue%22)" to work on instead. Once again Many thanks @mariusandra

**Comment by neilkakkar** [comment]
@anjola-adeuyi obviously completely upto you, but I'd recommend sticking with this one, you're almost there :) - just one manual db change, and you'll be in a good place to put up a PR.

**Comment by anjola-adeuyi** [comment]
@mariusandra @clarkus @neilkakkar I really appreciate the leads and encouragement. I've gone through this particular issue again and I've been able to successfully reproduce the issue as well as manually change the db for the `filters` column as suggested and **I should be pushing a PR very soon for its fix as well.**
