### ISSUE TITLE
(same title as posted question on PostHog Questions) Session ID Event Association Delay

### ISSUE THREAD

**Issue by huckleberryCalfinn** [PostHog/posthog#11522]
## Bug description

(Question Post Title) Session ID Event Association Delay

Hello, It seems session events that have occurred within the past few days consistently are without session_id and then acquire one a few days later. Ideally, we'd like to get session information as close to real-time as possible. My question is (1)is by observation indeed correct that session_id's take a few days to get assigned to a session? and (2) is there a way to expedite the process of associating events with a session_id to something closer to a daily or real-time time frame? Thank you very much (PostHog is awesome)!

## How to reproduce
1. go to Posthog.com and log in
2. got to live events
3. observe session id column is empty for recent events, but not for events occurring 3ish days ago

## Environment

- [x ] PostHog Cloud
- [ ] self-hosted PostHog, version/commit: please provide

## Additional context

Thank you!

**Comment by rcmarron** [comment]
Hey @huckleberryCalfinn, the `session_id` is added to the event in the client library as soon as the event is created. Can you share which client libraries you're using? I'm wondering if the older events were sent with one and the newer events were sent with another? Of note, right now, only `posthog-js > 1.16.1` supports `session_ids`. You can read a bit more here: https://posthog.com/manual/sessions#session-analysis

**Comment by calvin-witt** [comment]
thanks @rcmarron ! i think this may indeed be the issue. it looks to me like we are using ("posthog-js": "1.13.13"). ill verify this and circle back with confirmation. thank you!

**Comment by calvin-witt** [comment]
hi @rcmarron - just circling back to confirm that upgrading posthog-js version fixed the issue and the session_ids are now flowing again. thank you so much for your help!!
