### ISSUE TITLE
Discouraging from using word "posthog" as sub-domain when deploying self-hosted instance

### ISSUE THREAD

**Issue by kappa90** [PostHog/posthog#11533]
## Is your feature request related to a problem?

We have [a large number of organizations using `posthog` within their self-hosted subdomain](https://metabase.posthog.net/question/416-self-hosted-organizations-using-posthog-in-their-subdomain)

This could potentially be a problem if their subdomain is picked up by adblockers.

I just pushed a [PR to add a disclaimer in the documentation](https://github.com/PostHog/posthog.com/pull/4081), but it would be interesting to know if we could discourage this directly during a Helm chart deployment. 

## Describe the solution you'd like

During chart deployment, we display a warning if the subdomain includes the word `posthog` or combinations of it.
OR
We stop the deployment entirely if that happens (drastic, up for discussion).

More words that should be potentially discouraged: `tracking`, `tracker`, `metrics`, `analytics`

## Describe alternatives you've considered
Changes to the docs - already on their way.

**Comment by guidoiaquinti** [comment]
👋  @kappa90 

> During chart deployment, we display a warning if the subdomain includes the word posthog or combinations of it.

I don't think we can easily display a warning via Helm, only hard failing. I'm 👍 to implement this but I'll wait for @hazzadous and @ellie to chime in.

**Comment by kappa90** [comment]
Added more words that should be potentially discouraged

**Comment by kappa90** [comment]
We decided not to do this, blocking a deployment is too much.
