### ISSUE TITLE
Loading state for Recordings looks off

### ISSUE THREAD

**Issue by benjackwhite** [PostHog/posthog#11542]
## Bug description

When the Recordings page first loads it looks a bit off. 
I think this is amplified when you first visit it as the Skeleton recording view doesn't show which makes everything look more buggy than it actually is. 

## How to reproduce

1. Click on Dashboards (or anywhere not Recordings
2. Click on Recordings from the sidebar
3. See this:

<img width="1510" alt="Screenshot 2022-08-30 at 09 06 55" src="https://user-images.githubusercontent.com/2536520/187384746-2e1f20ab-1a8e-480e-83fd-1a59fb057330.png">

## Environment

- [x] PostHog Cloud
- [ ] self-hosted PostHog, version/commit: please provide

**Comment by CodeDrivesUs** [comment]
@benjackwhite , I want to work on this Issue but I can't reproduce it because everything looks fine from me 
https://www.loom.com/share/5d480cc7a2684b4e9434547e54133e24

**Comment by CodeDrivesUs** [comment]
@benjackwhite, I am waiting for your response for me to continue

**Comment by benjackwhite** [comment]
@CodeDrivesUs this is a beta feature in testing so best left to one of the Posthog team to look at. Thanks.
