### ISSUE TITLE
Request: Enable/Disable series

### ISSUE THREAD

**Issue by joethreepwood** [PostHog/posthog#11547]
## Is your feature request related to a problem?

Sometimes you have an insight with a lot of series. Sometimes you want to compare them one by one. Sometimes you don't want to have to click through all these Xs, either here or in the detailed results below. 

<img width="156" alt="Screenshot 2022-08-30 at 13 30 35" src="https://user-images.githubusercontent.com/84011561/187437040-9cadf6a3-f734-4b04-a110-d44cf2c50f75.png">

## Describe the solution you'd like

Sometimes, you want there to be a Select/Deselect All button. Sometimes you think it'd look great here:

<img width="138" alt="Screenshot 2022-08-30 at 13 31 26" src="https://user-images.githubusercontent.com/84011561/187437208-2caac83b-399e-49f0-bb3e-063b927e5258.png">

**Comment by Arun-chaitanya** [comment]
I guess this is done
