### ISSUE TITLE
Make "new version available" less threatening

### ISSUE THREAD

**Issue by timgl** [PostHog/posthog#1154]
**Is your feature request related to a problem? Please describe.**

I got some reports from users that thought something was wrong with their PostHog installation because of this message, as it's in red and has a error triangle.

**Describe the solution you'd like**

Make the warning more subtle by making it black and removing the icon (or make it something less error-y).

**Describe alternatives you've considered**

**Additional context**

***Thank*** you for your feature request - we love each and every one!

**Comment by yakkomajuri** [comment]
Could also be yellow? More like a warning over an error? Although new versions do come out quite regularly so maybe black is indeed the way to go
