### ISSUE TITLE
Onboarding flow seems to have very long buttons

### ISSUE THREAD

**Issue by neilkakkar** [PostHog/posthog#11545]
## Bug description

![2022-08-30 12 40 16](https://user-images.githubusercontent.com/7115141/187427793-6383a1bb-27bb-474e-9332-b8fcd60521bb.gif)

*Please describe.*  
*If this affects the front-end, screenshots would be of great help.*  

## How to reproduce

1.
2.
3.

## Environment

- [ ] PostHog Cloud
- [ ] self-hosted PostHog, version/commit: please provide

**Comment by AsiwajuDev** [comment]
@neilkakkar I picked this issue and started work on it but I'm trying to understand fully what needs to be done as the view I have is different from what was shared in the open issue
<img width="1678" alt="Screenshot 2022-08-30 at 15 54 43" src="https://user-images.githubusercontent.com/17790578/187470061-9b77bf81-1119-485f-8a8d-7c246551239c.png">

**Comment by clarkus** [comment]
This looks like a recent regression. Generally we just need to set a maximum width on the contents for each onboarding step.
