### ISSUE TITLE
Trouble selecting secondary metric

### ISSUE THREAD

**Issue by corywatilo** [PostHog/posthog#11553]
## Bug description

There are a few issues in setting a secondary metric for an experiment:

- [x] Trying to set a filter (Conversion funnel → Pageview → Filter) shows two event selector popups

    <img width="1260" alt="image" src="https://user-images.githubusercontent.com/154479/187474177-97777696-ecf1-4bf6-b5ae-369e07796acc.png">

    **[Video demo](https://www.loom.com/share/63334ce44c734e709afc29c04db3b8f5)** of ☝️ 

    - [ ] Related: With the event selector dialog open, clicking Esc inaccurately closes the entire secondary metric pane, rather than closing the event selector

- [x] I'm trying to set a secondary metric as a conversion funnel, but after setting a filter on the first step, it wipes out the option to add a second step in the funnel.

    <img width="685" alt="image" src="https://user-images.githubusercontent.com/154479/187475853-613527b1-1c23-4559-9c5b-efd295387fde.png">

    - More confusion: The primary conversion funnel uses numbers (1) and (2), but the secondary metric shows (A), which doesn't seem to make sense in the context of setting up a _conversion funnel_

- [x] After selecting a secondary metric, it doesn't show me if it's a trend or a conversion funnel, and there's no way to edit it

    <img width="689" alt="image" src="https://user-images.githubusercontent.com/154479/187475227-06ae0226-e3a0-4dbf-9e52-53b42c7f99d9.png">

**Comment by benjackwhite** [comment]
Related https://github.com/PostHog/posthog/issues/9996
