### ISSUE TITLE
All Events section will not load

### ISSUE THREAD

**Issue by avorio** [PostHog/posthog#1155]
**Describe the bug**

When I go to my PostHog's instance by accessing its root URL, I'm presented with the Trends page on the right, but the _Events > All Events_ tab selected on the left. Well, that doesn't make sense. But also, if I click on the _All Events_ menu item to see them, the page stays put and nothing changes. The URL bar already displays `/events`. If I try accessing that route directly, it won't get past the spinning loading icon.

**To Reproduce**

1. Go to the root URL for PostHog, see above.
2. Go to the /events URL, see above.

**Expected behavior**

Each section should present its own contents and the All Events section should not spin forever.

**Screenshots**

![Group](https://user-images.githubusercontent.com/649020/86636896-381da080-bfab-11ea-98e7-de4e6a3a45d2.png)

**Hosted or self hosted?:**
- hosted
- (if self-hosted) what version? 1.10.1

**Comment by timgl** [comment]
Hey @avorio, thanks for raising! are there any errors in your developer tools console log? Can you try hard-refreshing this page (cmd+shift+r)?

**Comment by avorio** [comment]
Hi @timgl!

Ah-ha! Yes, there are:

![Group2](https://user-images.githubusercontent.com/649020/86637973-dbbb8080-bfac-11ea-82a8-8c1769398fb0.png)

I just found out what's going on. The Chrome extension _uBlock Origin_ is blocking all things PostHog. It's blocking PostHog on the actual website where I'm using it as well ... so only certain events will be collected. Weird.

What are the plans for this? Any thoughts? It's only a matter of time until browser extensions start blocking products like PostHog, no? The more widely adopted it is, the more likely it is that it'll get blocked.

**Comment by timgl** [comment]
@avorio Ah, do you have something like `analytics` or `track` in the (sub)domain where you're hosting PostHog? If you rename that to something less conspicuous it should work (and keep avoiding ad blockers for all of your users as well!)

**Comment by avorio** [comment]
> @avorio Ah, do you have something like `analytics` or `track` in the (sub)domain where you're hosting PostHog? If you rename that to something less conspicuous it should work (and keep avoiding ad blockers for all of your users as well!)

That's a fabulous idea. Thank you.

What's the best way to rename that domain without breaking things, from the PostHog's perspective?

**Comment by timgl** [comment]
> What's the best way to rename that domain without breaking things, from the PostHog's perspective?

Nothing should break if you chance the domain name, just make sure you change the snippet as well! We'll make sure to add a warning about this.
