### ISSUE TITLE
Automatic materialisation of columns is not working

### ISSUE THREAD

**Issue by neilkakkar** [PostHog/posthog#11557]
## Bug description

Materialising columns cron seems to be broken (on Cloud) atleast.

1. The last time any column was materialised was 2 months ago (June 22): [See third query](https://metabase.posthog.net/question#eyJkYXRhc2V0X3F1ZXJ5Ijp7InR5cGUiOiJuYXRpdmUiLCJuYXRpdmUiOnsicXVlcnkiOiJcbi8qIFRpbWluZyBjaGVja3MgKi9cbi0tIFNFTEVDVCBjb3VudCgxKVxuU0VMRUNUXG4gICAgcXVlcnlfZHVyYXRpb25fbXMsXG4gICAgZXZlbnRfdGltZSxcbiAgICByZWFkX3Jvd3MsXG4gICAgcmVhZF9ieXRlcyBhcyByZWFkX3NpemUsXG4gICAgcmVzdWx0X3Jvd3MsXG4gICAgcmVzdWx0X2J5dGVzIGFzIHJlc3VsdF9zaXplLFxuICAgIG1lbW9yeV91c2FnZSBhcyBtZW1vcnksXG4gICAgcXVlcnlcbkZST00gc3lzdGVtLnF1ZXJ5X2xvZ1xuV0hFUkVcbiAgICBxdWVyeSBOT1QgTElLRSAnJXF1ZXJ5X2xvZyUnXG4gICAgQU5EIHF1ZXJ5IExJS0UgJyVsb2NhbF9ldmFsdWF0aW9uJSdcbiAgICBBTkQgdHlwZSA9ICdRdWVyeUZpbmlzaCdcbiAgICBBTkQgcXVlcnlfZHVyYXRpb25fbXMgPiAyMDBcbiAgICBBTkQgZXZlbnRfdGltZSA-ICcyMDIyLTA4LTAxJ1xuLS0gT1JERVIgQlkgcXVlcnlfZHVyYXRpb25fbXMgZGVzY1xuTElNSVQgMTBcblxuXG5TRUxFQ1RcbiAgICAgICAgICAgIHF1ZXJ5X2R1cmF0aW9uX21zLFxuICAgICAgICAgICAgcXVlcnlfc3RhcnRfdGltZSxcbiAgICAgICAgICAgIHF1ZXJ5XG4gICAgICAgIEZST00gc3lzdGVtLnF1ZXJ5X2xvZ1xuICAgICAgICBXSEVSRVxuICAgICAgICAgICAgcXVlcnkgTk9UIExJS0UgJyVxdWVyeV9sb2clJ1xuICAgICAgICAgICAgLS0gQU5EIHF1ZXJ5IExJS0UgJyUvKiUnXG4gICAgICAgICAgICBBTkQgcXVlcnkgTElLRSAnJS8qIHJlcXVlc3Q6JSdcbiAgICAgICAgICAgIC0tIEFORCAocXVlcnkgTElLRSAnLyogdXNlcl9pZDolJyBPUiBxdWVyeSBMSUtFICcvKiByZXF1ZXN0OiUnKVxuXG4gICAgICAgICAgICBBTkQgcXVlcnkgTk9UIExJS0UgJyVJTlNFUlQlJ1xuICAgICAgICAtLSAgIEFORCBxdWVyeSBOT1QgTElLRSAnJWNlbGVyeSUnXG4gICAgICAgICAgICBBTkQgdHlwZSA9ICdRdWVyeUZpbmlzaCdcbiAgICAgICAgICAgIEFORCBxdWVyeV9zdGFydF90aW1lID4gbm93KCkgLSB0b0ludGVydmFsSG91cigxNjgpXG4gICAgICAgICAgICBBTkQgcXVlcnlfZHVyYXRpb25fbXMgPiAzMDAwXG4gICAgICAgIE9SREVSIEJZIHF1ZXJ5X2R1cmF0aW9uX21zIGRlc2M7IiwidGVtcGxhdGUtdGFncyI6e319LCJkYXRhYmFzZSI6Mn0sImRpc3BsYXkiOiJ0YWJsZSIsImRpc3BsYXlJc0xvY2tlZCI6dHJ1ZSwidmlzdWFsaXphdGlvbl9zZXR0aW5ncyI6eyJ0YWJsZS5waXZvdF9jb2x1bW4iOiJyZXN1bHRfcm93cyIsInRhYmxlLmNlbGxfY29sdW1uIjoicXVlcnlfZHVyYXRpb25fbXMifSwib3JpZ2luYWxfY2FyZF9pZCI6MTMwfQ==)
2. Since last week, the analyze query has completely broken, [because the annotation has changed](https://github.com/PostHog/posthog/blob/master/ee/clickhouse/materialized_columns/analyze.py#L126). (context: https://github.com/PostHog/posthog/pull/11485 )
3. It works perfectly fine on local dev. (After I fixed https://github.com/PostHog/posthog/issues/11538 and ran the command)
4. [Checking the logs](https://grafana.us-east-1.prod.posthog.dev/explore?orgId=1&left=%7B%22datasource%22:%22Loki%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%7Bapp%3D%5C%22posthog%5C%22%7D%20%7C%3D%20%60clickhouse_mark_all_materialized%60%22,%22editorMode%22:%22builder%22,%22queryType%22:%22range%22%7D%5D,%22range%22:%7B%22from%22:%221661551200000%22,%22to%22:%221661554800000%22%7D%7D), it doesn't seem like the materialisation cron task is running at all. 
    6.  But the default values seem to not be overridden at all.
5. Even if (2) weren't an issue, the pressing problem is that it doesn't seem like `_analyze` is ever called:
```
SELECT
            query_duration_ms,
            query_start_time,
            query
        FROM system.query_log
        WHERE
            query ilike '%AND query_start_time > now() - toIntervalHour(%'
          AND query NOT ILIKE '%metabase%'
            AND type = 'QueryFinish'
            AND query_start_time > now() - toIntervalHour(168)
     --       AND query_duration_ms > 30
        ORDER BY query_duration_ms desc;
```
6. A separate issue: The query annotations aren't working properly. `api/feature_flags/local_evaluation` should result in literally 0 CH queries, but there seems to be some race condition here which updates queries with the wrong request data. [See first link](https://metabase.posthog.net/question#eyJkYXRhc2V0X3F1ZXJ5Ijp7InR5cGUiOiJuYXRpdmUiLCJuYXRpdmUiOnsicXVlcnkiOiJcbi8qIFRpbWluZyBjaGVja3MgKi9cbi0tIFNFTEVDVCBjb3VudCgxKVxuU0VMRUNUXG4gICAgcXVlcnlfZHVyYXRpb25fbXMsXG4gICAgZXZlbnRfdGltZSxcbiAgICByZWFkX3Jvd3MsXG4gICAgcmVhZF9ieXRlcyBhcyByZWFkX3NpemUsXG4gICAgcmVzdWx0X3Jvd3MsXG4gICAgcmVzdWx0X2J5dGVzIGFzIHJlc3VsdF9zaXplLFxuICAgIG1lbW9yeV91c2FnZSBhcyBtZW1vcnksXG4gICAgcXVlcnlcbkZST00gc3lzdGVtLnF1ZXJ5X2xvZ1xuV0hFUkVcbiAgICBxdWVyeSBOT1QgTElLRSAnJXF1ZXJ5X2xvZyUnXG4gICAgQU5EIHF1ZXJ5IExJS0UgJyVsb2NhbF9ldmFsdWF0aW9uJSdcbiAgICBBTkQgdHlwZSA9ICdRdWVyeUZpbmlzaCdcbiAgICBBTkQgcXVlcnlfZHVyYXRpb25fbXMgPiAyMDBcbiAgICBBTkQgZXZlbnRfdGltZSA-ICcyMDIyLTA4LTAxJ1xuLS0gT1JERVIgQlkgcXVlcnlfZHVyYXRpb25fbXMgZGVzY1xuTElNSVQgMTBcblxuXG5TRUxFQ1RcbiAgICAgICAgICAgIHF1ZXJ5X2R1cmF0aW9uX21zLFxuICAgICAgICAgICAgcXVlcnlfc3RhcnRfdGltZSxcbiAgICAgICAgICAgIHF1ZXJ5XG4gICAgICAgIEZST00gc3lzdGVtLnF1ZXJ5X2xvZ1xuICAgICAgICBXSEVSRVxuICAgICAgICAgICAgcXVlcnkgTk9UIExJS0UgJyVxdWVyeV9sb2clJ1xuICAgICAgICAgICAgLS0gQU5EIHF1ZXJ5IExJS0UgJyUvKiUnXG4gICAgICAgICAgICBBTkQgcXVlcnkgTElLRSAnJS8qIHJlcXVlc3Q6JSdcbiAgICAgICAgICAgIC0tIEFORCAocXVlcnkgTElLRSAnLyogdXNlcl9pZDolJyBPUiBxdWVyeSBMSUtFICcvKiByZXF1ZXN0OiUnKVxuXG4gICAgICAgICAgICBBTkQgcXVlcnkgTk9UIExJS0UgJyVJTlNFUlQlJ1xuICAgICAgICAtLSAgIEFORCBxdWVyeSBOT1QgTElLRSAnJWNlbGVyeSUnXG4gICAgICAgICAgICBBTkQgdHlwZSA9ICdRdWVyeUZpbmlzaCdcbiAgICAgICAgICAgIEFORCBxdWVyeV9zdGFydF90aW1lID4gbm93KCkgLSB0b0ludGVydmFsSG91cigxNjgpXG4gICAgICAgICAgICBBTkQgcXVlcnlfZHVyYXRpb25fbXMgPiAzMDAwXG4gICAgICAgIE9SREVSIEJZIHF1ZXJ5X2R1cmF0aW9uX21zIGRlc2M7IiwidGVtcGxhdGUtdGFncyI6e319LCJkYXRhYmFzZSI6Mn0sImRpc3BsYXkiOiJ0YWJsZSIsImRpc3BsYXlJc0xvY2tlZCI6dHJ1ZSwidmlzdWFsaXphdGlvbl9zZXR0aW5ncyI6eyJ0YWJsZS5waXZvdF9jb2x1bW4iOiJyZXN1bHRfcm93cyIsInRhYmxlLmNlbGxfY29sdW1uIjoicXVlcnlfZHVyYXRpb25fbXMifSwib3JpZ2luYWxfY2FyZF9pZCI6MTMwfQ==).

## Action items

1. [ ] Confirm if the materialize command works or not on Cloud (3)
2. [x] Confirm if the relevant env vars are set on Cloud: `MATERIALIZED_COLUMNS_ENABLED`, `COMPUTE_MATERIALIZED_COLUMNS_ENABLED`, `MATERIALIZE_COLUMNS_SCHEDULE_CRON` .
3. [x] Then figure out why analyze is never called.

**Comment by neilkakkar** [comment]
cc: @EDsCODE draft PR with some fixes: https://github.com/PostHog/posthog/pull/11558

**Comment by EDsCODE** [comment]
I believe (4) is looking at logs that are related to the main app service which wouldn't be handling celery tasks

**Comment by neilkakkar** [comment]
Hmm, but if you look for other celery tasks that have been received, it shows up in those logs. Try `redis_celery_queue_depth` or `heartbeat`

**Comment by EDsCODE** [comment]
ah i see. well, looks like neither of the get_crontab dependent tasks are running

**Comment by neilkakkar** [comment]
Exactly

**Comment by EDsCODE** [comment]
Seems like the stoppage of the tasks could coincide with the changing of infra?

**Comment by pauldambra** [comment]
Fly-by while watching hey duggy with #4

the constance values in the DB are fun :)

You need two settings on for that task to run

```
    if get_instance_setting("MATERIALIZED_COLUMNS_ENABLED") and get_instance_setting(
        "COMPUTE_MATERIALIZED_COLUMNS_ENABLED"
    ):
        return True
```

They're not set to the same value and they're not visible in the settings page :/

<img width="552" alt="Screenshot 2022-08-30 at 19 18 38" src="https://user-images.githubusercontent.com/984817/187513348-f538fb77-90a7-430c-b96d-b7ff726ae001.png">

Can we guess what those values are? Email is set like this

<img width="1037" alt="Screenshot 2022-08-30 at 19 18 23" src="https://user-images.githubusercontent.com/984817/187513337-bbfd24cd-3b52-4345-8420-e27cc3de2340.png">

And look like this in the DB

<img width="560" alt="Screenshot 2022-08-30 at 19 18 31" src="https://user-images.githubusercontent.com/984817/187513342-e7c96f3f-b272-419e-be4e-d0bcb6227c16.png">

So, my guess is that `COMPUTE_MATERIALIZED_COLUMNS_ENABLED` needs turning on

(may be teaching you to suck eggs but I was intrigued :))

**Comment by neilkakkar** [comment]
Hey @pauldambra , this is lovely :) - I should've realised I don't need to go to prod to see the values ugh

FFS

<img width="678" alt="image" src="https://user-images.githubusercontent.com/7115141/187514803-ad1848ae-4350-45a5-a3fb-dcf133d7c1f0.png">

**Comment by neilkakkar** [comment]
And I suspect this got borked here somehow: https://github.com/PostHog/posthog/blob/master/posthog/async_migrations/migrations/0002_events_sample_by.py#L138

**Comment by pauldambra** [comment]
#TIL the raw_value column needs less sleuthing 🤣

**Comment by EDsCODE** [comment]
🚀

**Comment by EDsCODE** [comment]
These values are also on django admin

**Comment by EDsCODE** [comment]
Ok, so

1. Once we adjust `COMPUTE_MATERIALIZED_COLUMNS_ENABLED = true`, the materialization should work
2. https://github.com/PostHog/posthog/pull/11558 Should fix the changes that make _analyze ineffective. I've added a test that should prevent further regressions when sync_execute changes the comment signature.

TODO:
- [ ] better logging to show what is being materialized and when

**Comment by neilkakkar** [comment]
What still remains to be fixed is the incorrect mapping from request to query

**Comment by EDsCODE** [comment]
> What still remains to be fixed is the incorrect mapping from request to query

Is this (6)?
