### ISSUE TITLE
Include more context in Slack notifications

### ISSUE THREAD

**Issue by avorio** [PostHog/posthog#1156]
**Is your feature request related to a problem? Please describe.**

Currently, Slack notifications only include action name, link, and user identification.

**Describe the solution you'd like**

I'd like to include certain attributes of events, so that the notification is much more useful to my Slack users. Those attributes are set on the actual site being tracked and are dynamic values.

**Describe alternatives you've considered**

Posting those events from the product to Slack, without PostHog.

**Additional context**

This builds on #105 and #460.

**Comment by timgl** [comment]
@avorio Thanks for raising! Are there any specific properties you'll want?

**Comment by wundo** [comment]
@timgl I think we could tokenize the slack message, creating different tokens for each property.

Which would allow us to do something like:
- `Action [action:name] triggered by user [user:id] `
- `User [user:id] just signed up with plan [action:plan]`
- `User [user:id] (plan: [user:plan]) created a new ticket [action:ticket_id] - [action:ticket_subject]`

**Comment by timgl** [comment]
I think that's a really cool idea!

**Comment by avorio** [comment]
> I think we could tokenize the slack message, creating different tokens for each property.

That's exactly what I thought. Thanks for further spec'ing it, @wundo. This would allow me to address the latter part of the solution proposed — i.e., "those attributes are set on the actual site being tracked and are dynamic values".
