### ISSUE TITLE
Event's "last updated" column label appears mislabeled

### ISSUE THREAD

**Issue by corywatilo** [PostHog/posthog#11617]
In the event list view, it shows _Last updated_ which would infer the _definition_ was updated.

<img width="1377" alt="image" src="https://user-images.githubusercontent.com/154479/187985039-9739efdc-378c-4cc6-a49c-61e2d91139f1.png">

Turns out, I believe this just means it was _Last seen_ X time ago.

<img width="284" alt="image" src="https://user-images.githubusercontent.com/154479/187985070-678fbd77-7dfb-4817-a549-da9add9a7cf4.png">

List view table header column seems like it should be updated to reflect this.

Edit - the column should also be right-aligned.

**Comment by AsiwajuDev** [comment]
Hello @clarkus, can I be assigned this ticket? Also, I will require more context on the issue towards recreating it easily on my end

**Comment by AsiwajuDev** [comment]
Hello @clarkus @corywatilo, can I be assigned this ticket? Also, I will require more context on the issue towards recreating it easily on my end

**Comment by mariusandra** [comment]
@AsiwajuDev we don't assign tickets (even if we have in the past)... just work on it and submit a PR with a fix. 

With regards to context, the initial issue does give enough context for myself or any other PostHog team member to start the investigation into what's broken and how to fix it. Perhaps the missing piece is that this is all under a page called "Data Management".

**Comment by Twixes** [comment]
I believe this has been solved in some iteration of this UI:
<img width="123" alt="Screenshot 2022-12-07 at 09 53 40" src="https://user-images.githubusercontent.com/4550621/206133057-7db75080-1cd7-4974-8b97-ed8689cc3735.png">
