### ISSUE TITLE
More flexibility in choosing the order of columns in insights

### ISSUE THREAD

**Issue by lsmith77** [PostHog/posthog#11628]
## Is your feature request related to a problem?

For insights across a longer time span it requires a lot of scrolling to the right to see the total column.

## Describe the solution you'd like

Ability to move (or duplicate) the total sum column as one of the first columns.

## Describe alternatives you've considered

Ability to collapse (by default) the individual months in the table.

**Comment by mariusandra** [comment]
Great idea! Hopefully this will do the trick: https://github.com/PostHog/posthog/pull/11658
