### ISSUE TITLE
Allow copying event & insight definitions / feature flags / experiment configurations between projects

### ISSUE THREAD

**Issue by pauldambra** [PostHog/posthog#11638]
## Is your feature request related to a problem?

In this support ticket https://posthoghelp.zendesk.com/agent/tickets/434 it appears that a user has configured an event using the toolbar in project A but the project receiving traffic is project B

If you have several projects "dev", "staging", and "production". You would have to manually configure custom events in each environment separately.

## Describe the solution you'd like

To copy custom event definitions between projects

## Describe alternatives you've considered

Letting people carry on doing this by hand

**Comment by weyert** [comment]
I would second this request for the feature flags

**Comment by neilkakkar** [comment]
interesting idea, makes sense.

**Comment by echojojo** [comment]
It'd be awsome. We're facing the same struggle of defining everything three times which is very time intensive. Copying event definitions over would be extremly awesome already. Being able to copy experiements over would be the non plus ultra!

Love the tool btw!
