### ISSUE TITLE
Pricing improvements

### ISSUE THREAD

**Issue by paolodamico** [PostHog/posthog#1163]
## Overview
Introducing a proposal for an updated pricing page following the new website guidelines (check out the design [here](https://www.figma.com/file/pFMjtem7m96npT1SpCSfm3/PostHog-Pricing?node-id=7%3A69)), providing more information to potential users.
- Clear pricing & benefits
- Connect the pricing plan for startups
- Difference (trade-offs) between cloud version and self-managed
- Frequently asked questions (predecessor https://github.com/PostHog/posthog/issues/217)

## Proposing the following changes
- Change the name from "SaaS / Hosted" to "Cloud". The hypothesis is that this makes it more clear to users that PostHog hosts and manages everything, and works just like any other cloud service to which they are used.
- For the Growth plan add email support. The rationale is that as we're already charging these users, they might need help with anything from billing issues, to general support. As this is the cloud version, we shouldn't expect support that requires complex engineering resources (as with the self-managed version).

### Frequently asked questions
1. **What happens when I reach the maximum number of events in my plan?** We’ll let you know when you’re close to the maximum number of events and prompt you to upgrade to a different plan. We won’t stop collecting events but we might limit your ability to consult your data or run analytics until the next billing period. 
1. **Is there a free trial on paid plans?** You can get a 30-day free trial on our Growth plan. Our Enterprise plan does not offer a free trial because it has the same features as the Growth plan.
1. **What happens after the data retention period elapses?** On the cloud plans, any event or user data stored for more than the retention period may be permanently deleted from our systems. On the self-managed plans, you control your data retention and what happens to your data afterwards.

## Tracking success
Ultimately the goal of the pricing page is to acquire more users that become fully activated. Therefore I'm proposing that we measure the success with these two metrics,
- Conversion rate from visiting pricing page to activated user ["activated" to be defined]. Ideally this should be increasing over time until we reach the diminishing returns threshold. 
- Absolute number of activated users that signed up from the pricing page.

### Things to test / improve
- We'll definitely have to improve the FAQs as we start getting more feedback from users. There's probably an opportunity in the sorting as well. The FAQs are in a collapsible card to be able to track what questions interest prospective users more.
- [Test] showing all the plan benefits instead of "Everything in X, plus"
- [Test] Adding/referencing a full feature chart/table (as all plans have all the same features at this point my hypothesis is that this will not make a significant difference)
- [Test] Adding key differentiators against competitors (e.g. affordable at scale, first-party tracking, straightforward integration [auto-capture])

## What is not covered by this issue
This issue is about better communicating the current plans and pricing strategy. Perhaps in the future the specific plans and pricing strategy could be revisited.

**Please comment with your thoughts on the proposed changes.**

**Comment by jamesefhawkins** [comment]
Agree with all the above.

Particularly keen we focus on getting the actual payment flow in, of course, but more transparency is always better with an engineering / self serve strategy.

**Comment by paolodamico** [comment]
Definitely! It's important to start focusing on the entire activation flow to make sure users get to the core value prop quickly. These improvements would hopefully help get users a step closer to entering this activation flow.

**Comment by timgl** [comment]
I think this is great! Happy to rename to Cloud (does make more sense!) and happy with the other changes too. Let's get this out and iterate from there

**Comment by paolodamico** [comment]
Internal note: We should consider moving the information on this [features page](https://posthog.com/product-features) to a features comparison section on the [new pricing page](https://github.com/PostHog/posthog.com/pull/177)

**Comment by paolodamico** [comment]
Closing this issue now as https://github.com/PostHog/posthog.com/pull/177 has been merged
