### ISSUE TITLE
Last updated on dashboard is slow to update

### ISSUE THREAD

**Issue by andrewm4894** [PostHog/posthog#11635]
## Bug description

When i update all charts on a dashboard the "Last Updated" thingy does not itself actually update. Often i refresh all charts - jump around and maybe end up back and original dashboard where last updated might still say 3 days ago - even though i just updated it. I get confused then and just press to update again (im not sure then if i can trust that the actual charts are based on the updated data i just did - i think they are). This can then be slow if im needlessly updating a dash with like 20 charts. 

![image](https://user-images.githubusercontent.com/2178292/188128079-262f6cc3-7539-4608-bda1-69949ada78fe.png)

## How to reproduce

1. go to a medium sized dashboard you use regulalry
2. update it
3. see if the last updated changes

## Environment

- [X] PostHog Cloud
- [ ] self-hosted PostHog, version/commit: please provide

**Comment by andrewm4894** [comment]
is a video for this in here: https://netdata-cloud.slack.com/archives/C01F31E9PRD/p1662118102496489

**Comment by pauldambra** [comment]
I think this probably overlaps with #10263. I'll try and address them both in the next two weeks
