### ISSUE TITLE
Notification System

### ISSUE THREAD

**Issue by EDsCODE** [PostHog/posthog#1169]
**Is your feature request related to a problem? Please describe.**
For features that will create a more social experience such as #1120, we will require a notification/inbox system so users can stay up to date with activity.

**Describe the solution you'd like**
An inbox/notif feed that prompts you when you visit posthog, showing you what's new or who's responded to your comments

**Describe alternatives you've considered**
n/a

**Additional context**

***Thank*** you for your feature request - we love each and every one!

**Comment by Twixes** [comment]
A use case that would be handy (based on user feedback): notifications when a plugin get disabled due to errors occurring.

**Comment by EDsCODE** [comment]
@posthog-bot Please summarize this

**Comment by EDsCODE** [comment]
@posthog-bot please summarize this

**Comment by pauldambra** [comment]
we now have this
