### ISSUE TITLE
Event tags + created by do not appear in Data Management table

### ISSUE THREAD

**Issue by HelloAlexPan** [PostHog/posthog#11703]
## Bug description

In `/data-management/events`, `tags` and `created by` for calculated events do not appear in the user table.

![image](https://user-images.githubusercontent.com/53453555/188871362-3df5ee27-46c4-4a86-969a-78300f5f4292.png)

Steps to reproduce:
1. Identify event using the Posthog Toolbar
2. Add tags to the events I identified
3. Navigate to Data Management within posthog 
4. Click `Type` dropdown
5. Click Calculated events

N.b. No console errors + Adblock turned off

**Expected result:**
See Tags and Created By in the event table

**Actual result**
Tags and Created by in event table all render null.
## Environment

- [x] PostHog Cloud
- [ ] self-hosted PostHog, version/commit: please provide

**Comment by yakkomajuri** [comment]
Hey @HelloAlexPan! Are there any tags though? And these were probably auto created by us?

**Comment by HelloAlexPan** [comment]
@yakkomajuri  Yep these events are tagged. These are custom events / not created by Posthog

**Comment by yakkomajuri** [comment]
cc @alexkim205

**Comment by pauldambra** [comment]
tags definitely show now :)
