### ISSUE TITLE
'load more breakdown values' disappears when saving insight

### ISSUE THREAD

**Issue by camerondeleone** [PostHog/posthog#11727]
## Bug description

Create a trend insight (any display mode) and add a breakdown with a lot of values (eg email). When you create the insight, you can show more breakdown values, but once you save, the option to 'load more breakdown values' disappears (even if you click back in to edit)

## How to reproduce

1.
2.
3.

## Environment

- [x] PostHog Cloud
- [ ] self-hosted PostHog, version/commit: please provide

**Comment by camerondeleone** [comment]
cc @neilkakkar - the issue isn't the table, it's that the option disappears once saved, and doesn't reappear on edit

**Comment by EDsCODE** [comment]
Note: this is possibly a bit involved because it would require some sort of caching beyond the simple result caching we do. The "next" URL is lost when the insight is saved which is why the prompt to click for more doesn't appear
