### ISSUE TITLE
Can't upgrade to the latest version Hobby

### ISSUE THREAD

**Issue by adrianwix** [PostHog/posthog#11732]
## Bug description

Script to upgrade does not work at all. I think is a bash script issue. I sadly lack the bash scripting knowledge to fix it. I do have an .env file with POSTHOG_SECRET and DOMAIN. it was created automatically when installing posthog

![image](https://user-images.githubusercontent.com/37629556/189134198-907b0152-1596-469f-bbe4-5f494382868a.png)

![image](https://user-images.githubusercontent.com/37629556/189134293-5c766d0d-fa70-4a51-b867-e41b7850311e.png)

## How to reproduce

1. Run /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/posthog/posthog/HEAD/bin/upgrade-hobby)"

## Environment

- [ ] PostHog Cloud
- [x] self-hosted PostHog, version/commit: 912e258e12f923596a66f9898a41a367b5a8fc0f

**Comment by adrianwix** [comment]
OK I found out the issue. The problem was that there was a commented env variable 
```sh
POSTHOG_SECRET=ABCDE
# SENTRY_DNS=XXXXXXXXXXXXX
DOMAIN=abc.def.com
```

Sidenote: I realized a typo here https://github.com/PostHog/posthog/blob/master/bin/upgrade-hobby#L33

I will close the issue and leave it up to you to find out how to improve the way the script obtains the env variables

**Comment by yakkomajuri** [comment]
Beat me to it - thanks for sharing the fix!
