### ISSUE TITLE
Cohorts with just person property filters still use joins

### ISSUE THREAD

**Issue by timgl** [PostHog/posthog#11739]
## In what situation are you experiencing subpar performance?

When creating an insight filtered by a cohort that only has person property filters we still do a join with the cohort table in clickhouse, which is much slower than just applying those property filters directly.

This causes a ton of timeouts for one of our customers.

## How to reproduce

1.
2.
3.

## Environment

- [ ] PostHog Cloud
- [ ] self-hosted PostHog, version/commit: _please provide_

**Comment by neilkakkar** [comment]
This is by design: it's the only way possible now to filter on current user properties vs point in time properties.
