### ISSUE TITLE
Session Duration Analytics Not loading

### ISSUE THREAD

**Issue by Aymonholth** [PostHog/posthog#11743]
## Bug description

*Please describe.*  

I’ve had a look through [this help docs](https://posthog.com/manual/sessions) and can see that I need to select a property aggregator  and then ‘Session Duration’. Unfortunately, I don’t seem to have that option, and instead it just defaults to ‘Time’. Any idea what may be occurring in this scenario? I got in touch with the Posthog team (Yakko) via Slack and they could confirm that this could be reproduced on their end.

<img width="985" alt="Screen Shot 2022-09-09 at 3 34 56 am" src="https://user-images.githubusercontent.com/92565089/189188609-941013eb-cd1d-4530-869f-6ae0b31599db.png">
<img width="968" alt="Screen Shot 2022-09-09 at 3 35 10 am" src="https://user-images.githubusercontent.com/92565089/189188740-b09cc923-b8d4-4023-a05d-ca25afc8880f.png">

## How to reproduce

1. Create a new insight
2. Select Pageview, select a property aggregator (e.g. 95th percentile) and then click on 'Time'
3. Attempt to search for Session Duration, you'll notice that it doesn't appear

## Environment

- [ x] PostHog Cloud
- [ ] self-hosted PostHog, version/commit: please provide

## Additional context
Even though Time is auto-selected as that last property, I noticed that if I actually tried to search for 'Time', nothing would appear. Likely related to the Session Duration bug.

**Comment by yakkomajuri** [comment]
cc @rcmarron

**Comment by rcmarron** [comment]
Hey @Aymonholth, from those screen shots it looks like you're on an older self-hosted version of posthog. Can you check which version you're on (should be shown in the drop down in the upper right of the app). Session analysis was added in [version 1.38.0](https://posthog.com/blog/the-posthog-array-1-38-0)
