### ISSUE TITLE
Reset scroll position when recording is selected

### ISSUE THREAD

**Issue by clarkus** [PostHog/posthog#11750]
## Is your feature request related to a problem?

This is specific to the in-progress recordings work. In the /recordings playlist view, both the list and recordings and the player are pretty tall. The issue is when selecting a recording towards the bottom of the list, the player is almost fully out of the viewport. 

Most of the player component that communicates the current recording and the position in time is outside the viewport.

## Describe the solution you'd like

I think we could adjust the heights of these components to be a bit more aligned to common viewport dimensions. In addition, we should adjust the vertical offset / scroll position to the top of the player. This would put the content in the ideal position for viewing the playback, controls and logs, and other info. 

## Describe alternatives you've considered

Could leave it as is, but it'll cause a lot of "pogo-sticking" scrolling. Navigating to the next recording, or trying to find a recording far removed from your current place in the list will be tedious to navigate.

**Comment by rcmarron** [comment]
I definitely agree! I had played with the heights a good bit, but the issue I was hitting is that the player on the right can't get too much smaller without the event list seeming useless. 

What do you mean by "we should adjust the vertical offset / scroll position to the top of the player"? I had been thinking about the idea of the scolls being independent, but I think it starts to be a bit funny. Might be easier to just chat through the solution here in our standup tomorrow?

**Comment by clarkus** [comment]
Sounds good. It's easier to observe than it is to describe.

**Comment by daibhin** [comment]
Closing this one out because we now have a much different / more configurable replay UI where you can collapse the list or change the stacking of the inspector
