### ISSUE TITLE
docker compose up error mounting config.xml

### ISSUE THREAD

**Issue by AllanJard** [PostHog/posthog#11769]
## Bug description

I'm trying to install Posthog self hosted on an Ubuntu 22.04 machine. I already have docker on the machine and I don't want to run it as root, so rather than running the [hobby deploy script](https://github.com/PostHog/posthog/blob/master/bin/deploy-hobby) directly, I've been working through it manually (other docker containers working fine, so I don't think it is a docker install issue).

Basically I clone into posthog, update the variables in the template docker compose file, move it to `docker-compose.yml` and run `docker compose up -d`. It appears to all go fine until:

```
Error response from daemon: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: error during container init: error mounting "/home/allan/posthog/posthog/docker/clickhouse/config.xml" to rootfs at "/etc/clickhouse-server/config.xml": mount /home/allan/posthog/posthog/docker/clickhouse/config.xml:/etc/clickhouse-server/config.xml (via /proc/self/fd/6), flags: 0x5000: not a directory: unknown: Are you trying to mount a directory onto a file (or vice-versa)? Check if the specified host path exists and is the expected type
```

I checked and the file is there. Actually, it was created as a directory which I thought was odd. It was also created by `root` (my user has the `docker` group, but not `wheel`/`sudo`). I tried changing it to an empty file; same error message. Direct changing the owner, same error message.

Any idea what is going wrong?

## Environment

- [ ] PostHog Cloud
- [X] self-hosted PostHog: Latest commit at the time of writing: d4508ed47a0f9531a99c8b0394591322ae411019

**Comment by guidoiaquinti** [comment]
👋 Hi @AllanJard, the problem you are experiencing is due to a Docker issue/volume misconfiguration. It doesn't seems to be an issue with PostHog itself or a PostHog supported setup. Did you try to mount the directory instead of the file? 

I'm closing this issue, feel free to reply with more info and I'll be happy to help.

**Comment by AllanJard** [comment]
Thanks for your reply!

1. `git clone https://github.com/PostHog/posthog.git`
2. `cd posthog`
3. Create a Caddy file based on https://github.com/PostHog/posthog/blob/master/bin/deploy-hobby#L81-L86
4. Create compose scripts: https://github.com/PostHog/posthog/blob/master/bin/deploy-hobby#L97-L129
5. Use docker-compose.hobby.yml and fill in the variables
6. `mv docker-compose.hobby.yml docker-compose.yml`
7. `docker compose up -d`
8. The error about config.xml not being able to be mounted is given

The file exists though:

```
allan@kepler:~/posthog$ ls -l docker/clickhouse/
total 72
-rw-rw-r-- 1 allan allan 57801 Sep 12 09:44 config.xml
drwxrwxr-x 2 allan allan  4096 Sep 12 09:44 docker-entrypoint-initdb.d
-rw-rw-r-- 1 allan allan  6326 Sep 12 09:44 users.xml
```

If you have any suggestions for what I can try, they'd be very welcome. I'm at a total loss at the moment.

**Comment by guidoiaquinti** [comment]
Can you please try using: 

```
    clickhouse:
        #
        # Note: please keep the default version in sync across
        #       `posthog` and the `charts-clickhouse` repos
        #
        image: ${CLICKHOUSE_SERVER_IMAGE:-clickhouse/clickhouse-server:22.3}
        restart: on-failure
        depends_on:
            - kafka
            - zookeeper
        volumes:
            - ./posthog/posthog/idl:/idl
            - ./posthog/docker/clickhouse:/etc/clickhouse-server
            - clickhouse-data:/var/lib/clickhouse
```
as your definition for the ClickHouse service in docker-compose as suggested in my previous comment? I've tested it locally and it seems to be working. On which CPU architecture are you running this?

**Comment by AllanJard** [comment]
That appears to have done it! Thank you :)

I don't actually see that suggestion from before - apologies. Is it worth changing the docker-compose.hobby.yml file in the repo to match that? At the moment [there are three lines](https://github.com/PostHog/posthog/blob/master/docker-compose.hobby.yml#L35-L37) which reference specific files, rather than the single one (second last line in your suggestion)?

**Comment by guidoiaquinti** [comment]
> That appears to have done it! Thank you :)

🙌 

> Is it worth changing the docker-compose.hobby.yml file in the repo to match that? At the moment [there are three lines](https://github.com/PostHog/posthog/blob/master/docker-compose.hobby.yml#L35-L37) which reference specific files, rather than the single one (second last line in your suggestion)?

Yes we can do that. Can you please make a PR?

> I don't actually see that suggestion from before - apologies. 

see quote from above👇 
> Did you try to mount the directory instead of the file?

**Comment by AllanJard** [comment]
Sorry - I hadn't cottoned on there. Obvious in retrospect!

I've created https://github.com/PostHog/posthog/pull/11778 with the change.

Huge thanks for your help.
