### ISSUE TITLE
event selector for calculated events styling off

### ISSUE THREAD

**Issue by camerondeleone** [PostHog/posthog#11773]
## Bug description

taxonimic list item is wrapping and pushing the icon onto a newline

<img width="489" alt="image" src="https://user-images.githubusercontent.com/56287180/189633098-9764c096-b500-4d01-bf6e-3a2fbe7a0965.png">

## How to reproduce

1.
2.
3.

## Environment

- [x] PostHog Cloud
- [ ] self-hosted PostHog, version/commit: please provide

**Comment by benjackwhite** [comment]
Ah looks like introduced this.
