### ISSUE TITLE
Lifecycle broken for persons on events

### ISSUE THREAD

**Issue by timgl** [PostHog/posthog#11789]
## Bug description

With persons on events, the lifecycle query says there are no new users until the week of 20th June, when there are many 
![image](https://user-images.githubusercontent.com/1727427/189717551-440bdbb5-638a-4f5e-9d95-54209b432207.png)

## How to reproduce

1. Create lifecycle insight far enough back
2.
3.

## Environment

- [ ] PostHog Cloud
- [ ] self-hosted PostHog, version/commit: please provide

**Comment by EDsCODE** [comment]
A whole bunch of persons didn’t get their person_created_at column properly migrated so it’s defaulting to a 1970 creation date which is skewing the lifecycle query results since it's attempting to use the new column

@neilkakkar Think we should flag lifecycle separately for this reason?

**Comment by neilkakkar** [comment]
Damn. Yeah, makes sense.

Do you know if the same happens on self-hosted?
