### ISSUE TITLE
Freeze 'Series column' on detailed results table

### ISSUE THREAD

**Issue by andyvan-ph** [PostHog/posthog#11800]
## Is your feature request related to a problem?

When viewing the detailed results table on an insight, scrolling right to see the most recent results means I can't see the 'Series' column for each value. See video:

https://user-images.githubusercontent.com/92976667/189872493-8a7ff752-d677-4ed5-9299-8bd652284fdf.mov

## Describe the solution you'd like

Freeze the 'Series' so it's always visible when scrolling right

## Describe alternatives you've considered

Alternatively, you could show the series name and mousing over the data value. Arguably, we should do both.

## Additional context

n/a

**Comment by Arun-chaitanya** [comment]
@andyvan-ph I am picking this up.

**Comment by Arun-chaitanya** [comment]
@Twixes I was trying to pass `sticky: true` in the (Series) column. But I don't think the sticky prop works in Lemon Table right?
Can you confirm this for me. I tried opening the storybook, and there was no mention of `sticky` property either. 
<img width="1440" alt="Screenshot 2023-07-25 at 7 00 08 PM" src="https://github.com/PostHog/posthog/assets/44457256/4f76a995-a0ae-4f5f-a446-464e95560b98">
<img width="1440" alt="Screenshot 2023-07-25 at 6 57 12 PM" src="https://github.com/PostHog/posthog/assets/44457256/a97c5c62-66c2-4f8b-8d33-77f59cf94caa">

**Comment by Arun-chaitanya** [comment]
@andyvan-ph solved this bug in PR https://github.com/PostHog/posthog/pull/16758. @Twixes added sticky feature to the LemonTable. Would love for you to review the PR.

**Comment by Arun-chaitanya** [comment]
@Twixes I messed with previous PR, so opening a new one (https://github.com/PostHog/posthog/pull/16825)
