### ISSUE TITLE
API Paginated feature flag list

### ISSUE THREAD

**Issue by EDsCODE** [PostHog/posthog#11808]
## Is your feature request related to a problem?

*Please describe.*

## Describe the solution you'd like
- paginate the list of feature flags on the backend

## Describe alternatives you've considered
- keep the frontend pagination

## Additional context
- not a high volume of feature flags at the moment but future proofing would require api based pagination

**Comment by mariusandra** [comment]
Paginated API list views are such a common pattern throughout the app, that we could benefit from having a shared abstraction between e.g. feature flags, insights, annotations, etc. This could take the shape of a `paginatedLoader()` kea [logic builder](https://keajs.org/docs/meta/kea#logic-builders), which would automatically keep track of the pagination counts, next URLs, etc.
