### ISSUE TITLE
Window ID doesn't match filter

### ISSUE THREAD

**Issue by clarkus** [PostHog/posthog#11811]
## Bug description

We recently introduced window/context filtering for session recordings. I feel like this was working previously but might have recently broken somewhere. 

<img width="313" alt="Screen Shot 2022-09-13 at 11 06 14 AM" src="https://user-images.githubusercontent.com/254612/189978946-27eecc0b-6e9f-40a8-b1b6-f2843caae98f.png">

## How to reproduce

1. Find a recording with multiple window contexts
2. Expand the event log and set the window filter to a specific context
3. Note that the corresponding list of events doesn't update

## Environment

- [ ] PostHog Cloud
- [ ] self-hosted PostHog, version/commit: please provide

**Comment by victorgbaye** [comment]
Hi @clarkus could you give a better description on how to reproduce the issue.(a loom video will be perfect or a full screen screenshot).

**Comment by clarkus** [comment]
> Hi @clarkus could you give a better description on how to reproduce the issue.(a loom video will be perfect or a full screen screenshot).

Thanks for asking @victorgbaye but this is for an internal project that isn't released yet. I think it would be best if a PostHog engineer owned this one.
