### ISSUE TITLE
Login Page is not Loading

### ISSUE THREAD

**Issue by jordanbotnot** [PostHog/posthog#11832]
## Bug description

I have tried logging into Posthog, but every time I hit login I get timed out. I tried different browsers and still the same issue. 

*Please describe.*  
*If this affects the front-end, screenshots would be of great help.*  

https://user-images.githubusercontent.com/93391393/190412983-e3d3ab87-7967-444b-b00f-19ad81c00fb0.mov

## How to reproduce

1.
2.
3.

## Environment

- [ ] PostHog Cloud
- [ ] self-hosted PostHog, version/commit: please provide

**Comment by guidoiaquinti** [comment]
👋 Hey @jordanbotnot this is unfortunate. Can you please confirm if this issue also happens with:

* an incognito window
* a different internet connection
* a different browser

Thank you! 🙇

**Comment by jordanbotnot** [comment]
The new internet connection worked! Thank you!
