### ISSUE TITLE
Indicate users email on hover

### ISSUE THREAD

**Issue by joesaunderson** [PostHog/posthog#11836]
## Is your feature request related to a problem?

When looking at users in PostHog, you show an avatar and name. We have multiple people with the same name, it's impossible to differentiate. "Which Jonathan was it?"

<img width="161" alt="image" src="https://user-images.githubusercontent.com/11272509/190437308-f1c36186-9866-409b-b9ca-449e037d60b1.png">

## Describe the solution you'd like

On hover of the avatar / name - show the users email - which will be unique.

## Describe alternatives you've considered

Asking every Jonathan?

**Comment by clarkus** [comment]
I think this is a good idea. In the meantime we do offer configuration options in settings that allow you to customize the property used to identify a person. I'm not sure if it's feasible for your case, but you could swap to email as the primary identifier when it's available. 

<img width="955" alt="Screen Shot 2022-09-15 at 9 36 01 AM" src="https://user-images.githubusercontent.com/254612/190459252-6cdc0f19-5ce8-4579-8044-b277674c0922.png">

**Comment by joesaunderson** [comment]
Hey @clarkus - these are internal users. I don't think this setting applies to them. I.e I wanted to find out who created a cohort, and couldn't as we have two Jonathans!

**Comment by clarkus** [comment]
Makes sense! Thanks for clarifying.
