### ISSUE TITLE
ability to store event filters

### ISSUE THREAD

**Issue by lsmith77** [PostHog/posthog#11838]
## Is your feature request related to a problem?

we are using posthog even data for machine learning data collection. we have events that indicate false positives and others that indicate true positives. our data scientist would like to persist the relevant event type, filters and relevant columns for later use. note they would then always make only minor edits to the saved queries to extract the relevant information they are looking for in that moment. 

## Describe the solution you'd like

ability to save event filters for later reuse.

**Comment by mariusandra** [comment]
Hey @lsmith77 , would "calculated events", which were previously called "actions" (and will soon be renamed again, possibly back to "actions") solve this issue? 

If not, can you walk me through where would we put this in the interface?

I'd imagine you would use saved filters something like this:

<img width="900" alt="image" src="https://user-images.githubusercontent.com/53387/190662579-0c600bdf-e6f9-4aae-948b-879e45acd067.png">

(not a real screenshot)

... but how to save, edit and delete these filters? 🤔 
I also wonder if saved filters could reference other saved filters?

**Comment by lsmith77** [comment]
these screenshots are coming from “insights”? at any rate the key thing is that we don’t want to aggregate in this use case but export specific events.

**Comment by mariusandra** [comment]
These screenshots are just mockups, but indeed from insights.

So you're saying the question is about saving filters on the live events table page, and the "export" button on that page?

**Comment by MarconLP** [comment]
related issue: https://github.com/PostHog/posthog/issues/2895

**Comment by Twixes** [comment]
Hey Lukas! We made it possible to save event views as insights since you opened this issue, so these can now be persisted - including for exports.
