### ISSUE TITLE
Toolbar Launch does not work if target page changes url hash params

### ISSUE THREAD

**Issue by hazzadous** [PostHog/posthog#11831]
## Bug description

Many websites will perform an HTTP redirect or Js side location update when hitting e.g. the root page. To handle the enabling of the toolbar, we are passing a url hash, via a redirect from app.posthog.com, which we then look for in the posthog-js init code. If there is a redirect before this init code has a chance to run, then we do not see the toolbar launch.

This could be handled on the website side, ensuring that the init code is run before redirect, or the hash is maintained across redirect but this would complicate the app side and ideally we shouldn't expect people to have to change their app to use the toolbar.

## How to reproduce

1. setup or use a page that redirects/changes the url before posthog-js init method runs
2. use this page as the launch url
3. Click launch in the app.posthog.com ui

## Environment

- [x] PostHog Cloud
- [x] self-hosted PostHog, version/commit: please provide

**Comment by pauldambra** [comment]
It may be related to https://github.com/PostHog/posthog/issues/9100

At the least, we should document that the toolbar launch needs PosthogJS and the URL hash to load. 

Relaxing that requirement might be possible but is tricky too...

**Comment by hazzadous** [comment]
> It may be related to https://github.com/PostHog/posthog/issues/9100

Yes possibly, feel free to close as a duplicate
