### ISSUE TITLE
ability to mark properties as important

### ISSUE THREAD

**Issue by lsmith77** [PostHog/posthog#11839]
## Is your feature request related to a problem?

events tend to have a lot of properties but not all are equally important.

## Describe the solution you'd like

in the data management it would be useful to mark properties as important. these properties should be listed first in all places:
* in the data management section
* in the event view

**Comment by clarkus** [comment]
Interesting idea! We have a similar "verified" concept for events. What impact would you expect important properties to have on the other parts of the product? I could see us promoting those properties over others, but did you have anything else in mind?

**Comment by lsmith77** [comment]
so when viewing event details, I would expect these properties to appear on the top and/or have bold names. similarly when configuring a filter I would hope for the same.

**Comment by lsmith77** [comment]
maybe this marking of “important” can also be implicit based on which properties have been documented?
