### ISSUE TITLE
ability to document properties across events

### ISSUE THREAD

**Issue by lsmith77** [PostHog/posthog#11840]
## Is your feature request related to a problem?

there is a lot of overlap between events in terms of properties

## Describe the solution you'd like

ability to document such properties only once for all events

**Comment by mariusandra** [comment]
We already have the "event properties" page under data management, which lets you add custom descriptions for properties, which are shared between events. Is there something missing from this?

**Comment by lsmith77** [comment]
Ah maybe I misunderstood something here. I was under the impression that if I have a property that I use for multiple events, I would need to document that property for each event.

But based on your response I didn’t test this properly. Which however in turn means that I need to take care to always use property names across events for conceptionally the same things.
