### ISSUE TITLE
Baseline behaviour in funnel breakdowns is very confusing

### ISSUE THREAD

**Issue by neilkakkar** [PostHog/posthog#11848]
## Bug description

*Please describe.*  
*If this affects the front-end, screenshots would be of great help.*  

When creating a breakdown funnel, we always add a 'baseline' row, which is the sum of all _current_ breakdown values.

This gets very confusing ( [see here](https://posthog.slack.com/archives/C03P1U69R6U/p1663317798528539), [or here](https://posthog.slack.com/archives/C02E3BKC78F/p1661891058125149), and also came up in a few user interviews.)

Whenever we're dealing with a feature flag or experiment breakdown, the baseline makes no sense, and is in turn confusing: Is baseline the experiment baseline? (no, it's not).

Same for multiple breakdown values (more than 25): The baseline is the sum of current values, it's not even the original conversion rate.

I suppose the original usecase for the baseline was to compare no-breakdown & breakdown conversion rates, but maybe there's a better way to represent this, than calling it 'baseline'?

I propose getting rid of it, or atleast renaming it to something that makes more sense, which implies its the 'total', not the baseline.

**Comment by liyiy** [comment]
I think we should rename it first before deleting it. Users are definitely getting confused by the name of it because once you tell them that's like the "total" of things they immediately get it

**Comment by neilkakkar** [comment]
The question is, is having the total there useful?

**Comment by liyiy** [comment]
> The question is, is having the total there useful?

I think once you get rid of it there will be people requesting to see the "sum/total" comparison of things but we could probably just easily experiment with this ! I'm definitely in favor of having less than more
