### ISSUE TITLE
PW are being displayed as usernames on PostHog

### ISSUE THREAD

**Issue by skachid** [PostHog/posthog#11845]
## Bug description

I was invited by a colleague to join PostHog and I was asked to sign-up, entering my email and password. Below is a screenshot of what this looks like:
![1968](https://user-images.githubusercontent.com/102870161/190498943-a27d65d3-e207-437e-8705-fabfa21a9797.jpg)

I entered my login details, and the administrator was notified of my login. Only, it showed my password as my username to them (blacked out for security, obvs):
<img width="644" alt="Screen Shot 2022-09-15 at 3 48 02 PM" src="https://user-images.githubusercontent.com/102870161/190499085-6bc92574-4856-4b80-b2ff-9eeae642b80a.png">

## How to reproduce

1. Send an invite to a user
2. Have them join and create an account
3. When admin is notified, the PW will show up

**Comment by benjackwhite** [comment]
Having a look a this now. @skachid Can you confirm that when you logged in, that your Display Name was **not** your password? Investigating the code so far I can only see the possibility that your password got entered in the "First Name" field (possibly by an over-eager browser auto-completion?).

Did you login and subsequently change your Display Name at https://app.posthog.com/me/settings ? If so then I am pretty sure this is what happened.

To be clear - we **never** store passwords in plain text so the only thing that I can think of that happened is that your password somehow landed in that "First Name" field...
