### ISSUE TITLE
Optional steps in funnel visualization

### ISSUE THREAD

**Issue by pwanning** [PostHog/posthog#11841]
## Is your feature request related to a problem?

We are building a guided selling application with ~30 steps. Nine of them are optional/conditional, depending on selections the user has made. 

For example:
A - Any other drivers?
Yes → A1 - Please name them (optional)
No → Next step

B Are you currently insured?
Yes → B1 What is your current insurance provider?
No → Next question

Using “sequential step order” i can’t measure the optional steps.

## Describe the solution you'd like

It would be great if i could configurate a step as optional. In the funnel graph it could marked as sub/special step.

## Describe alternatives you've considered

We have too many of optional steps to build separate funnels.

**Comment by Twixes** [comment]
Hi @pwanning! Will close this ticket in favor of #17313 – stay tuned
