### ISSUE TITLE
Persons on events backfill did not work correctly

### ISSUE THREAD

**Issue by yakkomajuri** [PostHog/posthog#11850]
## Problem

Through releasing persons on events for various teams, @neilkakkar and @EDsCODE spotted inconsistencies with the backfill data.

Upon digging we all found out that while all the person IDs that _could_ be backfilled (meaning there were corresponding `person_distinct_id` rows) were backfilled. This is what originally led us to call this done.

However, we also found out that the vast majority of `person_created_at`, `person_properties`, `groupX_created_at`, etc were not backfilled at all.

For instance, only ~10% of rows in the backfill actually got a value for `person_created_at`.

We're 95% confident that the issue here is that since ClickHouse is column-oriented, updates are not done as we're used to. 

In Postgres, for example, columns in a row are stored together, meaning updates to columns in a row also happen in one go.

In ClickHouse, columns in a row are stored separately, meaning that something like:

```sql
ALTER TABLE example
UPDATE foo = 1, bar = 2
WHERE foo != 1
```

Is effectively:

```sql
UPDATE foo = 1
WHERE foo != 1

UPDATE  bar = 2
WHERE foo != 1
```

Meaning that if the value of `foo` for a given row changes before the update to `bar`, the update to `bar` might not be executed.

In our case, this manifested because our backfill updated multiple columns based on `person_id` being empty. But it also updated `person_id` to a non-empty value.

```sql
ALTER TABLE sharded_events
UPDATE
    person_id = dictGet(...),
    person_created_at = dictGet(...),
    ...
WHERE
    person_id = toUUIDOrZero('')
```

<details>
<summary><b>Further context</b></summary>

<br />

Note that we spoke with Altinity and they confirmed this hypothesis. However, both they and I were unable to reproduce this with static updates i.e. without using dictionaries. Altinity ran a tiny test for this, but I actually tried this with a "static update" over a clone of a 80gb production table, indicating to me that scale alone isn't the problem, but scale might exacerbate other issues (see below).

My suspicion is that the additional lookups and latency added by dictionaries causes column updates to happen more out of sync. This is supported by the fact that our self-hosted users had less inconsistencies  n the data than us. 

I'd love to dig deeper into how ClickHouse processes these mutations under the hood, but for now those are my guesses.

</details> 

## Solution

Following investigation (see collapsed section below), I shipped https://github.com/PostHog/posthog/pull/11833, upgraded the playground, ran the migration, and confirmed it fixed all the data inconsistencies, confirming the hypothesis.

Now we must decide how to proceed in light of this. 

Our options are:

1. Keep a lookup table of events that need to be updated and use that in the WHERE clause
2. Run two mutations - one backfilling all but one column (used in the WHERE clause), and the second backfilling the remaining column
3. Running a timestamp-based backfill i.e. all events before date X
4. Just run the backfill on all the data
5. Run the backfill on all the data but with the UPDATE expressions being e.g. `person_id = if(empty(person_id), dictGet(...), person_id)`

The key thing to keep in mind here are the self-hosted users. We're able to determine exactly when we turned on persons on events on Cloud, so can run a targeted backfill to save resources. #11833 already adds one mechanism for doing the migration over a range only. 

However, the problem is more tricky for self-hosted users. Thus, I'm an advocate for just running a full backfill for self-hosted users. It will greatly simplify things for us. However, I don't feel _too_ strongly and would be happy to consider other options. Note that the backfill doesn't take very long actually.

(happy to offer further context on the viability of options 1 through 5 on request)

## Additional work

I think a key piece that we should ship with this is a post-check that confirms the migration ran successfully i.e. actually checks the data. I'll take this on.

A tiny thing I also would like to do is allow string inputs for async migration parameters (UI currently only allows for number inputs).

<details>
<summary><h2>Investigation details</h2></summary>

<br />

Internal thread: https://posthog.slack.com/archives/C0374DA782U/p1663011135259659

Upon noticing the issue, I did the following:

- Tested the dictionary setups on Cloud, confirming they returned the right data
- Tested various static updates where I updated a row's column that flipped the WHERE clause, unable to reproduce
- Ran out of time testing an update with dictionary lookups, inconclusive
- Ran the migration on the playground, confirming it didn't backfill all the data
- Asked self-hosted users for data, confirming the backfill also didn't work fully

</details>

**Comment by yakkomajuri** [comment]
Another follow-up:

How are we going to ensure users that already ran the migration run it again? 

We could:

- Release 0007 and make 0006 a no-op
- Update 0006 and contact teams individually to update their DB (need to look at metrics of who has already run this - hopefully only those we told to run it?)
- Write a Postgres migration to mark 0006 as not completed and send out a message

Just some loose thoughts for now

**Comment by macobo** [comment]
Thanks for digging. Some initial thoughts without going too deep:

To keep things operationally simple, let's do the same thing we've done before: create a new async migration and make the old one a noop.

As to the where clause, I'd suggest setting it to `WHERE 1=1` on self-hosted. Not sure on the impact on cloud but we can basically do anything that works (and doesn't rewrite _everything_) on it.

**Comment by tiina303** [comment]
+1 to doing the simplest thing (4. Just run the backfill on all the data) and what we've done in the past (new async migration and making old one a noop).
