### ISSUE TITLE
Recordings should limit / throttle / something if excesive mutations are observed

### ISSUE THREAD

**Issue by benjackwhite** [PostHog/posthog#11862]
## Is your feature request related to a problem?

A few things can occur regarding MutationObserver if it is polyfilled with a non-native implementation or if it is called too frequently due to something like SVG animations.

* SVG animations like Lottie etc can make recordings go wild. Ideally we cleverly detect this and debounce things.
* Issue likely due to MutationObserver being patches to https://github.com/PostHog/posthog/issues/11194

## Describe the solution you'd like

* Detect if MutationObserver is polyfilled and at least display a warning to the console. Perhaps have an option to disable polyfilled observers if we know it performs so poorly (e.g. `recordWithNonNativeMutationObserver=false`) 
* We could look at debouncing the observer. If too many events come in to rrweb, we pause the recording and once finished call for a full snapshot _or_ run through the changes in a batch?

## Describe alternatives you've considered
* Open to other ideas

**Comment by pauldambra** [comment]
this is done

**Comment by edwinvrgs** [comment]
I'm seeing this in my recordings today:
<img width="852" alt="image" src="https://github.com/user-attachments/assets/1d50f4fb-e7c8-4f1a-b830-d7b14c664d7c" />

Is this isn't fixed?

**Comment by pauldambra** [comment]
Hey @edwinvrgs, that's this feature working as intended. This recording captured an a node that had mutations higher than our rate limit and was throttled.

Think of it as reducing the frame-rate of the animation *but only in the recording not for your users*

**Comment by edwinvrgs** [comment]
Thank you @pauldambra. I'm asking because in the recording I cannot see the page that contains the animations, it just shows black until the user navigates to another screen. I thought this was somehow avoiding the screen from being recorded. Is there any other place I need to look to fix that issue with the recording?

**Comment by pauldambra** [comment]
Can you open a support ticket in-app and share the link to the recording? 🙏

**Comment by edwinvrgs** [comment]
Sure, will do it. Thank you.

**Comment by rarestoma** [comment]
Hi @pauldambra,

I can see the same "Too many mutations" thing in my recordings
<img width="404" alt="Image" src="https://github.com/user-attachments/assets/f567195a-43cc-4b82-9ab5-0bc5cb38c8a9" />

Does this affect the recording in any way, or is it just a warning?

Thank you

**Comment by pauldambra** [comment]
Yep, just a warning. We'll have "cut the frame rate" of an SVG animation of something similar to protect ingestion. So you might notice playback of an animation (or something similar that makes lots of changes to the DOM) look jerky but it won't be jerky for users, just in playback

**Comment by sandercoffee** [comment]
nice to have some special class like do-not-record on elements like this?
