### ISSUE TITLE
Show more accurate duration for Recordings

### ISSUE THREAD

**Issue by benjackwhite** [PostHog/posthog#11865]
## Problem

Currently duration is derived based on timestamps related to the collection of snapshot data. With [this PR ](https://github.com/PostHog/posthog/pull/11799) we will have extracted the most valuable info from the snapshot data and we can therefore derive much more accurate start/end timestamps as well as other info such as:

- [ ] Browser sizes
- [ ] Number of X event (clicks, scroll etc.)
- [ ] First timestamp of event and last timestamp

This way we can display more accurate duration info as well as some other helpful at-a-glance info

**Comment by pauldambra** [comment]
we don't capture browser sizes in this way (although likely will for any heatmaps improvements) but we base duration on the replay events table which is based on the rrweb event timestamps
