### ISSUE TITLE
Flickering graphs on hover on dashboards

### ISSUE THREAD

**Issue by macobo** [PostHog/posthog#11879]
## Bug description

Multiple users reported in slack:
> I have noticed some graphs flicking both inside the App and embedded through an iframe.

## How to reproduce

https://user-images.githubusercontent.com/148820/191182605-2a2aede1-4bea-4567-8a44-2ed7209e3a1b.mp4

## Environment

- [x] PostHog Cloud
- [ ] self-hosted PostHog, version/commit: please provide

## Additional context

cc @mariusandra for bug bashing

Potentially related: https://github.com/PostHog/posthog/issues/11878

**Comment by macobo** [comment]
Managed to repro when reproducing a different error, when resizing my window in funnels

https://user-images.githubusercontent.com/148820/191243193-7279360a-7651-49f6-a29b-5762485a0186.mp4

**Comment by jramiresbrito** [comment]
up?
