### ISSUE TITLE
Integrate with Metabase

### ISSUE THREAD

**Issue by wundo** [PostHog/posthog#1188]
It would be great to have an easy way of exporting data from Posthog to Metabase 😄

**Comment by timgl** [comment]
If you're self-hosting, this should be super easy, just plug in your postgres database URL! I'm not super familiar with Metabase so is there a different path you're thinking about?

**Comment by paolodamico** [comment]
Depending on our roadmap plans for a query builder or direct SQL queries (like Heroku data clips), it might make sense to add a simple reference on our docs to [Metabase's DB integration instructions](https://www.metabase.com/docs/latest/operations-guide/configuring-application-database.html) in case users want to make more complex queries. Might also be worth mentioning that depending on the customer's infrastructure and load, using a replica might be better. Thoughts @yakkomajuri?

**Comment by yakkomajuri** [comment]
I think this could be beneficial, but we just need to see where to put it. Cause it can't really be called an "integration" for us, even though Metabase integrates with Postgres and we use Postgres

**Comment by Twixes** [comment]
This is indeed available, on the database level (connecting Metabase to Postgres/ClickHouse). As for enhancing PostHog itself though, we're looking into making it powerful with solutions like #1244 or #3548.

**Comment by yakkomajuri** [comment]
Not only available but documented too! 

https://posthog.com/docs/tutorials/1-minute/integrate-with-metabase

**Comment by jordn** [comment]
> Not only available but documented too!
> 
> https://posthog.com/docs/tutorials/1-minute/integrate-with-metabase

is this still true? broken link now

**Comment by Rush** [comment]
Is it still possible?

**Comment by timgl** [comment]
If you're self hosting PostHog you can. If you're using Cloud, you can now [use SQL directly](https://posthog.com/docs/hogql)
