### ISSUE TITLE
Incorrect result for a trend unique users query in table

### ISSUE THREAD

**Issue by macobo** [PostHog/posthog#11886]
## Bug description

User mentioned that numbers inbetween funnels and unique user count in trends table don't match up.

Example:
![image](https://user-images.githubusercontent.com/148820/191231048-c2adc13b-95b4-4db0-9957-e0a2a906365e.png)
![image](https://user-images.githubusercontent.com/148820/191231089-f3d10e29-8621-41bf-9a26-2e14506ebc37.png)
![image](https://user-images.githubusercontent.com/148820/191231103-db2455a6-0443-4468-a505-1c841759fe06.png)
![image](https://user-images.githubusercontent.com/148820/191231125-fad28ec7-00dc-4a21-9718-c3e9acdd4167.png)

I verified this on our account: The for a pageview -> pageview count funnel the number in step 0 does not match up with trends result and is higher than what metabase would report as expected.

## How to reproduce

1. Open trends, select unique users
2. Note down total from table down
3. Open funnels, do a pageview -> pageview funnel
4. Note down total there

2 and 4 don't match

[Metabase query](https://metabase.posthog.net/question#eyJkYXRhc2V0X3F1ZXJ5Ijp7InR5cGUiOiJuYXRpdmUiLCJuYXRpdmUiOnsicXVlcnkiOiJzZWxlY3QgY291bnQoKSBmcm9tIGV2ZW50cyAiLCJ0ZW1wbGF0ZS10YWdzIjp7fX0sImRhdGFiYXNlIjo0fSwiZGlzcGxheSI6InRhYmxlIiwidmlzdWFsaXphdGlvbl9zZXR0aW5ncyI6e319) for an example expected result run on our team

## Environment

- [x] PostHog Cloud
- [ ] self-hosted PostHog, version/commit: please provide

## Additional context

cc @EDsCODE @neilkakkar 

Came up during support hero.

Related issue seems to be that the date range filter is odd - it's filtering via `timestamp >= toTimezone(toDateTime(toStartOfDay(toDateTime('2022-09-13 07:00:00')), 'US/Pacific'), 'UTC') AND timestamp <= toDateTime('2022-09-20 23:59:59')`

I think the problem is that the table underneath sums each day up and reports the result, while funnel reports total number of unique users for whole period. If so, we should fix the table.

**Comment by EDsCODE** [comment]
> I think the problem is that the table underneath sums each day up and reports the result, while funnel reports total number of unique users for whole period. If so, we should fix the table.

Agreed. Will change this

`timestamp >= toTimezone(toDateTime(toStartOfDay(toDateTime('2022-09-13 07:00:00')), 'US/Pacific'), 'UTC') AND timestamp <= toDateTime('2022-09-20 23:59:59')`

There's a few things going wrong here. The start and end time should both be 7:00 because US/Pacific based. The rounding logic in the first clause clamps the timestamp to 00:00:00 which should not happen but it's because toStartOfDay behaves differently compared to the other truncating functions

**Comment by EDsCODE** [comment]
Working through the timestamp issues.

Consideration on the table total unique reporting. Ideally, we want to get these results without running more separate queries

**Comment by macobo** [comment]
I think removing the summary table column conditionally for now would be the right thing to be doing. E.g. only show it for totals and sums, but not for avg, formulas etc.
