### ISSUE TITLE
Dashboard throwing error, won't load for multiple users

### ISSUE THREAD

**Issue by andyvan-ph** [PostHog/posthog#11896]
## Bug description

For some reason [this dashboard](https://app.posthog.com/dashboard/49928) (and only that dashboard) is throwing an error and won't load.

![Screenshot 2022-09-20 at 15 17 10](https://user-images.githubusercontent.com/92976667/191283288-191816de-5e44-4a01-b212-aa457144de82.png)

## How to reproduce

1. Click link
2. Make sad face

## Environment

- [x] PostHog Cloud
- [ ] self-hosted PostHog, version/commit: please provide

## Additional context

Duplicating the dashboard doesn't fix the problem. The duplicate breaks as well.

**Comment by mariusandra** [comment]
Annoyingly, the error is different and more informative locally when developing:

<img width="1206" alt="image" src="https://user-images.githubusercontent.com/53387/191292656-55a89bd4-43a2-4f04-ad68-dcfa87a84b06.png">

I patched [this discrepancy](https://github.com/keajs/kea/commit/2776cece2cbd6bca1af1ad303ae6f3ef43411c27) in kea.
