### ISSUE TITLE
Session recording: Going from experiments to a session recording

### ISSUE THREAD

**Issue by lharries** [PostHog/posthog#11893]
Em has recently completed an experiment about billing: https://posthog.slack.com/archives/C01RJ7T212S/p1663668012914219

As a product manager/engineer I'd like a way to view the session recordings that show the differences between the branches of the experiment. (The meta point is better integration of session recordings and experiments)

Dream scenario: it shows the exact moments where the feature flags makes the change up to the point of conversion (Although I realize this might be too tricky) Could potentially fire an event when the feature flag is used to help identify this moment?

cc @benjackwhite

**Comment by benjackwhite** [comment]
This is sort of doable already 😅 If you take [Em's recent experiement](https://app.posthog.com/experiments/565) for example you can click on the various funnel steps drop-off or success and then you get the persons who went through it with recordings that you can play. 

The "Dream Scenario" of course isn't covered but would be interesting to think about how we could get closer to it

**Comment by macobo** [comment]
Related: https://github.com/PostHog/posthog/issues/7963

Meta: Please use labels for tickets to make organizing them easier :bow:

**Comment by lharries** [comment]
Closing this issue as it's already possible to do and otherwise a too broad issue
