### ISSUE TITLE
Separate labels for documentation / marketing site enhancments 

### ISSUE THREAD

**Issue by wundo** [PostHog/posthog#1189]
I think it would be great to have a label "docs" and "marketing" or something like.
So we can separate issues related with documentation and the posthog marketing website from the code/product issues.

**Comment by mariusandra** [comment]
Hey, any specific issues that caught your eye?

We try to keep the issues related to the website on the [posthog.com repository](https://github.com/PostHog/posthog.com/issues).

**Comment by wundo** [comment]
Hi @mariusandra from the top of my head:
- #1163 
- #1175 
- #1151

**Comment by mariusandra** [comment]
I transferred them to the `posthog.com` issues: 

- #1163 --> https://github.com/PostHog/posthog.com/issues/192
- #1175 --> https://github.com/PostHog/posthog.com/issues/190
- #1151 --> https://github.com/PostHog/posthog.com/issues/191
