### ISSUE TITLE
Product insights: All formulas are resulting in an error

### ISSUE THREAD

**Issue by lharries** [PostHog/posthog#11895]
The bar chart shows normally however when I enter a formula the query errors.

See the following video for steps to reproduce: https://share.cleanshot.com/gYbA6F

Link to the insight: https://app.posthog.com/insights/eswxiLCU/edit

**Comment by lharries** [comment]
cc @mariusandra

**Comment by EDsCODE** [comment]
Added a fix. Still needs a test. The original cause is inconclusive atm. More details in the ticket
