### ISSUE TITLE
/people search seems to be broken

### ISSUE THREAD

**Issue by jamesefhawkins** [PostHog/posthog#119]
***Thank*** you for reporting bugs - we appreciate every single bug report.

**Describe the bug**
The search on /people doesn't seem to do anything.

**To Reproduce**
1. Go to /people
2. Enter a search
3. Nothing happens

**Expected behavior**
It should run the search as you type.

**Screenshots**
![Screenshot 2020-02-18 at 09 17 22](https://user-images.githubusercontent.com/47497682/74760738-b31a3080-522f-11ea-956c-53d29330ba8e.png)

**Comment by timgl** [comment]
Fixed
