### ISSUE TITLE
The "Add payment method" page could use some design love

### ISSUE THREAD

**Issue by lharries** [PostHog/posthog#11948]
The ["Add payment method"](https://app.posthog.com/ingestion/billing) shows up during onboarding as shown below.

I think there's potential to use design to help get them excited about all the cool features we have & reduce worries about the cost and surprise bills

<img width="862" alt="Screenshot Ingestion wizard • PostHog (Google Chrome) 2022-09-23 at 08 40@2x" src="https://user-images.githubusercontent.com/22766134/191913052-c75b5644-1362-4bbb-b2dc-faaf09423756.png">

**Comment by lharries** [comment]
cc @kappa90 and @corywatilo

**Comment by benjackwhite** [comment]
Yeah this was an experiment to see if it had good conversion (which it did! 🥳 ) but now that we are going to have the new pricing plans I would love to expand this to actually be a little bit more like the [new pricing page proposal](https://github.com/PostHog/product-internal/issues/355) where you can directly choose your plans and subscribe. With our new BillingService idea we could even have this for self-hosted (I think).

**Comment by kappa90** [comment]
This was very much an experiment and a placeholder to get cards activated while we switch to the new billing strategy, so it didn't really make sense to spend more time on a design that would be changed a few weeks after.

I agree, we should align to the new pricing page proposal!

**Comment by lharries** [comment]
Makes sense! Awesome that we had such good results and fully agree with moving fast with less design for the v0.1 :)
