### ISSUE TITLE
Quickly view session recordings for the steps in a funnel

### ISSUE THREAD

**Issue by lharries** [PostHog/posthog#11942]
## Is your feature request related to a problem?

I've created a funnel which has a sudden change:
<img width="981" alt="Screenshot Feature flag creation funnel • Insights • PostHog (Google Chrome) 2022-09-22 at 22 19@2x" src="https://user-images.githubusercontent.com/22766134/191853095-974ce31f-34ff-4ecb-8ffd-df412352e5fd.png">

I'd like to view some of the session recordings before and after this change. And there doesn't seem to be an easy way to do this?

## Describe the solution you'd like

Currently when I click on the funnel it shows me a cohort of the people:
<img width="710" alt="Screenshot Feature flag creation funnel • Insights • PostHog (Google Chrome) 2022-09-22 at 22 21@2x" src="https://user-images.githubusercontent.com/22766134/191853473-32004992-dcc2-4803-9a60-24784442f1d0.png">

It would be great if there was also a tab where it showed the session recordings for that date. There could be a dropdown such that you can change which step in the funnel you want to look at for that user?

## Describe alternatives you've considered

Going into the Session Recording page and filtering to the cohort I've created and then selecting the event

#### *Thank you* for your feature request – we love each and every one!

cc @benjackwhite

**Comment by benjackwhite** [comment]
Yeah this was brought as an idea elsewhere as well. We should definitely do this but there's a bit of a technical trickiness as we are filtering for the persons and then adding in the sessions for those people. But it's definitely possible

**Comment by lharries** [comment]
@benjackwhite great. Also this feature is available in Funnels and so there might be code re-use options
![Screenshot Cameron DeLeone's Zoom Meeting - Zoom  (Google Chrome) 2022-09-26 at 18 28@2x](https://user-images.githubusercontent.com/22766134/192331089-651b147c-07f6-404b-b074-8a81dbcd6e0a.png)

Here's extra context if you want to see how Cameron explains it: https://posthog.slack.com/archives/C01MGUHFH6G/p1664193712332529?thread_ts=1664190697.138099&cid=C01MGUHFH6G

cc @mariusandra - another good example of stuff we can unify across the app

**Comment by lharries** [comment]
@benjackwhite and @mariusandra - I spoke to Tim and we might already have this for most views, it's just that the session recordings were too old and so they weren't available. However this doesn't seem to be the case on the graphs I've tried

**Comment by neilkakkar** [comment]
Yep, the problem here is that the TTL for session recordings currently is 3 weeks only, so any place you click on that's older than 3 weeks will not show recordings 😬 .The 'dip' in your chart seems to be > 1 month old.

 This is one big reason why the S3 storage migration would be huge, since it will allow us to extend storage quite a bit.
