### ISSUE TITLE
Not able to use session duration minute or hour filter

### ISSUE THREAD

**Issue by ivanagas** [PostHog/posthog#11957]
## Bug description

When filtering sessions by session duration, trying to filter by minute or hour causes the value to go null, break styling. Re-selecting seconds causes all options to be selected. 

![image](https://user-images.githubusercontent.com/34755028/192037039-0b1c418c-2a47-4546-9a81-7424e536b013.png)
![image](https://user-images.githubusercontent.com/34755028/192037292-b4c811e3-b08a-4aad-b6dd-3f1863b3ac15.png)

## How to reproduce

1. Create insight
2. Add filter to event of session duration
3. Try to set session duration time unit to minutes or hours.

## Environment

- [x] PostHog Cloud
- [ ] self-hosted PostHog, version/commit: please provide

## Additional context

Also effects filter groups.

**Comment by mariusandra** [comment]
This got fixed in https://github.com/PostHog/posthog/pull/11958 it seems
