### ISSUE TITLE
Total count (sum) on tabular data showing as 0

### ISSUE THREAD

**Issue by matt-mg** [PostHog/posthog#11965]
## Bug description

All tabular data referring to page view when summed is showing as 0.  This was fine a few days ago, but for the last couple of days, it has been broken.

## How to reproduce

1. Create an insight with pageview even and show as total count.
2. View as chart type: table

## Environment

**- [ X ] PostHog Cloud**
- [ ] self-hosted PostHog, version/commit: please provide

## Additional context

I've added screenshots:

1. Shows dashboard
![1](https://user-images.githubusercontent.com/67703374/192283755-b6e1007f-9f4b-473c-b8b1-b81b523818b5.gif)

2. Show query and tabular data
![2](https://user-images.githubusercontent.com/67703374/192283758-bccb985f-fc14-41ea-bb26-5b74cbe9f560.gif)

3. To prove there are values, changed to chart type: graph so you can see the values
![3](https://user-images.githubusercontent.com/67703374/192283762-3cc0043f-722a-4909-8db6-ee7fe18f2b9f.gif)

**Comment by duncanmcclean** [comment]
Was just about to come here and report the same thing!
