### ISSUE TITLE
Finalise Recordings Playlist work for release

### ISSUE THREAD

**Issue by benjackwhite** [PostHog/posthog#11968]
We have some final work todo to get Recordings Playlist out

## Describe the solution you'd like
- [ ] Add setting for console logs to allow people to opt in or not https://github.com/PostHog/posthog/pull/12007
- [ ] Filtering events https://github.com/PostHog/posthog/pull/11990
- [ ] Fuzzy searching for events https://github.com/PostHog/posthog/pull/11990
- [ ] Use EditorPanels style collapsible filters for Playlist filtering
- [ ] Fuzzy searching for console logs (non-blocking)

**Comment by alexkim205** [comment]
All of this has been addressed
