### ISSUE TITLE
Opportunities to improve recording performance

### ISSUE THREAD

**Issue by rcmarron** [PostHog/posthog#11998]
This issue is meant to capture some ideas for how we could improve session recording performance:

#### Use time-range limited queries more

In [this PR](https://github.com/PostHog/posthog/pull/11877), we added a time range to the query that selected data for a single recording. This seems to speed up the query for recording data by ~2-4x.

Right now, we're only using this new time-limiting clause in when the recording is viewed on the playlist. We should expand this optimization to everywhere a recording can be viewed.

#### Cache CH response

To improve initial playback speed, data from a recording is paged down to the client. However, this requires us to do a CH query on each individual request. By caching the recording data from the first request, the later requests could simply reference the cache and avoid querying CH again.

#### Move to `event_summary` for metadata calculation

We did work to start capturing the `event_summary` as uncompressed data and materialize this out of the `snapshot_data` column. We should start using this new column for the metadata query that's needed before playback starts.

#### Move decompression to the client

The story around decompression/compression in recordings is a bit of a mess. Today, we:
1. Receive data in a compressed form from the client
2. Decompress it to process it, and then recompress it before storing it in CH
3. When querying it from CH, we decompress it to process it again (mainly for the metadata calculation)
4. Then, we compress the entire payload before sending it down to the client (via Django)
5. Then, we decompress it on the client before playback

We the new `event_summary` column, we should be able to skip the decompression/recompression that happens in steps 3 + 4, and simply pass the compressed data from CH down to the client. This will speed things up.

#### Materialized view

When querying CH for recordings, we aggregate across many `session_recording_event` rows. Clickhouse has 2 features [Aggregating Merge trees](https://clickhouse.com/docs/en/engines/table-engines/mergetree-family/aggregatingmergetree/) and materialized views that may allow this aggregation to be done in advance - so it isn't happening at query time.

Note: @hazzadous had played with this over the summer and while we didn't look too extensively, the initial tests seemed promising.

#### Limit date range

Today, we query the entire date range that the user requested for the list query (e.g. last 21 days) - even though the page of data the customer is requesting is probably contained in the past day alone.

There's a good optimization to be made in attempting to fill a page of data with a more limited time range and only querying the full time range if needed.

#### Person on recordings

Today, we join the persons table on recordings to get persons data (e.g. the name of the user being recorded). We recently did a bunch of work on the events table to remove the need for this join. We could do the same on recordings.

cc @benjackwhite @alexkim205 @fuziontech @hazzadous - this is a follow up to our chat this morning. Wanted to make sure these ideas were captured.

**Comment by pauldambra** [comment]
The majority of this is done now...
