### ISSUE TITLE
Expose apps statistics to users

### ISSUE THREAD

**Issue by macobo** [PostHog/posthog#12009]
## Is your feature request related to a problem?

- I (as a user) don't know whether a plugin is reliable or not
- I have no way to track data export progress

## Describe the solution you'd like

Page per app where depending on the type we'd show time-series graphs for
- Events processed/failed (processEvent)
- `onEvent` calls (success, fail)
- runEveryX calls (success fail)
- Stats per job triggered
- Stats for exports (e.g. progress tracking with indicators what dates have been exported, exported/failed ratios)
- Last errors logged

See https://github.com/PostHog/posthog/issues/11749 for some other ideas

Additional constraints:
- We'd want the data collection part to be relatively efficient (e.g. emitting an event per processEvent or onEvent would be too much)

Open questions:
- How important are _exact_ results here on successes?

## Describe alternatives you've considered

Users skim through logs.

## Additional context

cc @yakkomajuri I know you've thought about this a lot. Mind pitching in with ideas, for example on design or metrics to track

**Comment by yakkomajuri** [comment]
We spoke on Slack about this, a few key points:

- Suggested metrics to start: success, success on retry, failure (group by error), and maybe plugin execution time
- No custom metrics yet (something to consider in the future)
- Consider a tab to track a running historical export for v2
- Metric accuracy: OK to not aim for 100% given in-memory aggregation and server crashes. We just need to put a bit of thinking into how we display things in the UI to not give a feeling of certainty. We'd also flush failure metrics more often. 

Follow up: are we still thinking of using events for this or setting up a separate table?

**Comment by macobo** [comment]
Some other relevant resources:
- https://segment.com/docs/connections/event-delivery/
- https://www.rudderstack.com/docs/user-guides/administrators-guide/monitoring-and-metrics/

>Follow up: are we still thinking of using events for this or setting up a separate table?

Not sure, leaning towards separate table. Separate table means we'll need to re-invent graphing and schema setup work, into events means leakage into insights, billing, persons, and $every_new_feature and is inefficient for storage in clickhouse.

Open question to @lharries around billing: what do you make of making this an 'enterprise' feature at the start and if needed later loosening the restrictions on this? Seems like a good fit for that.

**Comment by yakkomajuri** [comment]
As mentioned on Slack I'm a +1 to gating this as an enterprise feature to start off. We can always go the other way and open this up but gating after something's offered to all is a much trickier thing.

RE separate table - I think that makes sense. Avoids a lot of extra logic that comes with using events: logic to circumvent parts of ingestion, logic to hide these events from insights, logic for billing, etc, etc. Also allows us to set up schemas that make more sense rather than fitting this to the events schema

**Comment by lharries** [comment]
**Enterprise vs scale**
I'll dive into more details around enterprise vs scale and get back to you with more info (likely next week as I'm still at the offsite this week)

**App statistics also for ingestion**
@macobo something I'd consider when building this is how can we also use these statistics for **ingestion** (from client/server side libraries to our clickhouse) and expose these metrics to the user. This has the advantage of increasing user trust around the reliability of Posthog. I see it as quite likely we'd move to separate named sources and so the user could then have different graphs for each and be able to easily debug specific sources e.g. if server-side events stop firing

We can see the Clickhouse destination as effectively one type of "data export". Might well be out of scope for this feature but good to keep in mind if we think it's valuable.

**Setting up a separate table?**
- Additional thing to consider: If we have a separate table this could potentially be a separate system in future to the Kafka/Clickhouse database and so help with monitoring events to that
- Although all the free insights + filtering logic we get with using Events is promising too
- I'll leave you both to make this decision

**Comment by macobo** [comment]
> @macobo something I'd consider when building this is how can we also use these statistics for ingestion (from client/server side libraries to our clickhouse) and expose these metrics to the user. 

I'd say this is a different problem fundamentally. Even if the technical data gathering side of it is similar the UX for exposing this would need to undergo some iteration.

I think this is best visited once we have some more bearing on the road to CDP.

----

I worked with data exports recently and have now more input on how to improve the experience around them:
1. All the plans discussed above are still valid - we should go for a success metric based approach for an overall overview of the plugin.
2. UX-wise, I'd suggest creating a tabbed page for metrics for a given app installation. Tab 1: Overall stats, Tab 2: Exports
3. Exports tab lists past and running exports, clearly indicating if an export is ongoing.
      - An exports stats page would show: export date range, overall progress, events exported, retries, errors. Also a date-by-date breakdown of progress.
      - Could also allow cancelling running exports on this page https://github.com/PostHog/posthog/issues/12043

This should improve the exports experience significantly as it's currently kind of hard to be confident it's doing the right thing.

Depending on how our plans shape up with CDP, I can see this page becoming the baseline for everything plugin-related, with tabs for stats, configuration, logs, activity logs and more. Not actioning this the coming project though.

**Comment by lharries** [comment]
> Open question to @lharries around billing: what do you make of making this an 'enterprise' feature at the start and if needed later loosening the restrictions on this? Seems like a good fit for that.

Overall proposal: this should be a scale feature rather than enterprise. In summary, this is a feature that will be highly valuable to all companies using the data export apps rather than just selecting just for those on the enterprise plan.

Reasoning:

- Free vs paid.
    - Proposal: It should be paid.
    - Reasoning:
        - This is a major feature and “**All new major features will be paid only by default”** ([source](https://posthog.com/handbook/product/paid-features#when-should-a-feature-be-paid-or-free)).
        - More broadly, we’ve not yet decided which aspects of the pipeline product will be free/open source.
- Scale vs enterprise
    - Proposal: It should be on the scale plan rather than enterprise.
    - Reasoning:
        - Enterprise features should be focused on differentiating the largest companies that can pay the most from the rest of the market.
        - App statistics seems like a core feature to drive user trust in the product and help with debugging. If we don’t offer it as part of the scale plan we are likely to have significant debugging requests when things go wrong or customers churning from not being able to fix problems with their data exports.
        - Enterprise features should be focused on C-Level, improving compliance and improving security (such as advanced permissions) ([source](https://posthog.com/handbook/growth/strategy#product)). App statistics is not a security/C-level focused product. It could be used argued that it has a compliance use case but there are likely other more core compliance features within the CDP that we can later develop such as helping with the right to be forgotten/role based access/advanced permissions.
        - To be competitive with the market: other companies (e.g segment), provide it in their paid plan (not paywalled to enterprise). However, some like Rudderstack do not.
      - Potential reasons again:
        - This is a highly valuable feature that can be used to upsell to enterprise.
          - However - upsell to enterprise seems less of a company focus and can already be done via the core permissions/compliance features

@yakkomajuri, @tiina303, @macobo let me know if you have any questions on this

Karl - once you feel you have the context, as you are the lead on this feature do you want to make the final decision?

**Comment by tiina303** [comment]
pricing idea: pricing based limiting the number of apps (or limiting it to a number (e.g. 1) of  apps, where you can see the metrics - this would potentially upsell scale for currently free folks)

per app tracking consider:
+ setupPlugin success/failure
+ how much time it take to run (helps us find the bad guys who are stalling threads)
+ what's the delay for exports (e.g. at an average I'd see my events in BigQuery after 1h from arriving to PostHog API, because we batch)

**Comment by macobo** [comment]
@lharries makes sense to me!

@tiina303 
> pricing idea: pricing based limiting the number of apps (or limiting it to a number (e.g. 1) of apps, where you can see the metrics - this would potentially upsell scale for currently free folks)

Not sure what this extra complication achieves, but I assume it's upsell related? If so, let's discuss this as we're working on the feature gating/upselling side of this feature.

**Comment by lharries** [comment]
@macobo you raised a good point: "do we want to still show the pages when user doesn't have the right plan and direct them to pay if so?"

Find my recommendation on this. Let me know if you have any questions and then up to you to make the final decision and move forward

Options:
- Don’t paywall this feature for free users until we’ve decided the exact pricing for the pipeline product
    - Pros:
        - Least engineering work
    - Cons:
        - Missing a valuable opportunity to upsell users to the scale plan
- Paywall this feature with a clear upsell
    - Pros:
        - Valuable opportunity to upsell users to the scale plan
    - Cons:
        - Might lead to frustration - their app is already not working and now they need to pay/enter their credit card to be able to fix it
    - Potential variants:
        - Only store historical data and summary metrics for the cloud version, not the self-hosted
        - Don’t allow them to access the page and instead have an upsell variant

Recommended action: **Paywall this feature with a clear upsell - showing the summary metrics for both cloud and self-hosted**

- Suggestions parts of the solution:
    - Show the summary metrics (events processed, events processed on retry, failed events) to give a high-level sense that their app is working or not working
    - Store the historic data and instantly reveal the historic information when they upsell
    - Do this for for both cloud and self-hosted. Reasons:
        - The summary metrics are highly important for reliability and confidence in the apps
        - (Luke's hunch) We are more likely to gain more users from an effective upsell, being able to show the summary metrics, and instantly reveal the historic data - than the self-hosted users we would lose who would directly access the app statistics table with a tool like Grafana
          - We can find other ways to paywall/upsell the pipelines product beyond just app statistics and so we shouldn’t be too concerned about abuse of this via Grafana
    - Include screenshots or a demo video explaining the feature (Karl could record a short loom - see the retool demo video on the homepage for an example: [https://retool.com/](https://retool.com/). This would help demonstrate the power of the tool)
- Suggested out of scope for this paywall:
    - Allow free users to test this feature for X days
    - Allow app statistics for a limited number of apps

Potential reasons against this recommendation:
- We haven’t yet decided how we want to paywall and upsell the overall pipeline product e.g. limit by number of apps and so it’s not worth doing additional work to paywall app statistics for now
    - However, it’s highly likely we’ll allow some sort of free app usage with the pipeline product and therefore this paywall of app statistics would continue to be used

Very rough mockup of what this paywall might look like:
<img width="782" alt="image" src="https://user-images.githubusercontent.com/22766134/197770867-cb106d0b-799e-48fd-abe2-5b19c1e33bde.png">

**Comment by lharries** [comment]
@kappa90 as this is upsell related would be great to get your input if you have the time

**Comment by tiina303** [comment]
I would like to call out my earlier proposal:

> pricing idea: pricing based limiting the number of apps (or limiting it to a number (e.g. 1) of apps, where you can see the metrics - this would potentially upsell scale for currently free folks)

pros:
1. support-hero will have an easier time helping folks (as I can link them to things they can see) + there will be less questions as they can solve their problems themselves
1. if users are already frustrated a paywall could increase churning probability
1. it's easier engineering wise to restrict number of apps compared to various features around apps like this one
1. this is tied to our actual load / help demands / value - the more apps someone uses the more load and the more problems they have ; more apps also means they are getting more out of PostHog

cons:
1. Missing an opportunity to upsell users to the scale plan

In general I'm a fan of the idea of limiting things one can do (only N apps, only M transformations, only S sources, only D destinations) rather than visibility into what's happening

**Comment by lharries** [comment]
Great point, I'll discuss with Karl when he's back but I think this makes the most sense

**Comment by macobo** [comment]
Discussed this with @lharries  face-to-face:

1. We won't be putting any focus into paywalling _yet_ - rather we'll revisit this as part of the pipeline rethinking. Potential RFC to tackle this: https://github.com/PostHog/product-internal/pull/367
2. After this release:
    1. On cloud: app metrics data is gathered for everyone, but UI is only shown for scale anv above
    2. On self-hosted: app metrics data is gathered and shown only for scale and above

## On self-hosted users

Note on why we aren't capturing this data on self-hosted for free users: This increases the minimum size of a posthog instance. Kafka will be processing a lot more information as well as memory, cpu usage in plugin-server increases as a result of this feature, meaning that for free users they'd need to $$$ more for a feature they couldn't access and isn't critical in the beginning.

We _could_ hide it behind a toggle but that's a bad idea - we want the initial setup experience to be as smooth as possible.

## On this ticket

Closing out this ticket for now given the feature is live and so is all the work outlined in this ticket, except paywalling which will be handled separately.
