### ISSUE TITLE
Paths wildcard grouping regex option

### ISSUE THREAD

**Issue by liyiy** [PostHog/posthog#12018]
## Is your feature request related to a problem?

*Please describe.*

The paths wildcard option only allows for wildcard matching.

## Describe the solution you'd like

Allow for wildcards to be defined more granularly by allowing regex

**Comment by neilkakkar** [comment]
We do allow these, it's called the 'Path cleaning rules', which applies before any wildcard matching happens

**Comment by liyiy** [comment]
OK then it's confusing UX wise hahaha

**Comment by neilkakkar** [comment]
100% 😅
