### ISSUE TITLE
Toast error: Timeout waiting for app 13 to reload

### ISSUE THREAD

**Issue by macobo** [PostHog/posthog#12024]
## Bug description

Was playing with apps today. Received this error.

![image](https://user-images.githubusercontent.com/148820/192976945-cedfc8c0-3929-4429-a078-e9621f03fae3.png)

## How to reproduce

Unclear. This seems to occur even after reloads

## Environment

- [x] PostHog Cloud
- [ ] self-hosted PostHog, version/commit: please provide

## Additional context

cc @yakkomajuri

**Comment by mariusandra** [comment]
Context: I think this happens only when the plugin server is not running. We poll any installed app to see if there's a frontend component. When the app is not reloaded after a certain time, we show this error.

**Comment by macobo** [comment]
Note this was occurring on posthog cloud and plugin-server was definitely running :)
