### ISSUE TITLE
Prometheus metrics support

### ISSUE THREAD

**Issue by FUSAKLA** [PostHog/posthog#1203]
### Is your feature request related to a problem? Please describe
I'd like to observe/alert on the PostHog status but it seems there are no application metrics provided?

### Describe the solution you'd like
It would be great to support for example Prometheus metrics or at least statsd.
Actually the official helm chart suggests that PostHog should support statsd since it allows to depoy Prometheus statsd-exporter but I do not see any option to enable sending of those metrics to it.

**Comment by timgl** [comment]
@FUSAKLA We have statsd now, though it isn't documented yet!

**Comment by FUSAKLA** [comment]
I'm already running it in production with a statsd_exporter, great job! :+1:
