### ISSUE TITLE
Retention table improvements

### ISSUE THREAD

**Issue by timgl** [PostHog/posthog#1205]
### Is your feature request related to a problem? Please describe

I’d love to be able to (1) choose which event counts as activity and (2) choose the relevant period (eg. we care about weekly retention more than daily retention).

I've also noticed that the retention table doesn't actually load for me on app and crashes when it times out.

### Describe the solution you'd like

1. Allow users to choose the event that counts as retention
2. Allow filtering of both the interval and the period
3. Make sure the query is optimised

### Describe alternatives you've considered

-

### Additional context

cc @EDsCODE as you're looking at retention table

**Comment by EDsCODE** [comment]
oh yeah huh my retention on app errors out too

**Comment by EDsCODE** [comment]
1. #1234 
2. #1230 
3. #1214 (merged)

breakdown people onclick: #1202 

@timgl  All the above are implemented but theyll have several merge conflicts so whenever you get the chance, I'd suggest we review and merge one at a time in an agreed order so i can fix the merge conflicts
The best Order IMO is in the order they were created 1202 -> 1230 -> 1234. So I can make the adjustments to each as necessary

**Comment by timgl** [comment]
@EDsCODE Will review those now!
