### ISSUE TITLE
Indicate keyboard is likely open for mobile session recordings

### ISSUE THREAD

**Issue by benjackwhite** [PostHog/posthog#12054]
## Is your feature request related to a problem?

Session Recordings of a mobile webview (like safari, cordova) can look odd when the keyboard is opened and closed. We could ideally indicate the keyboard is open.

## Describe the solution you'd like

* For recordings where we know it is a mobile OS with a small screen, we could detect when the screen size changes and if the width is the same as before then we could show a keyboard placeholder to make it clear what happened (using the true height from the previous full window.
  - There could be all sorts of edge cases here like resizable windows on iPad, split screen vertical apps on android...

## Describe alternatives you've considered
🤷

**Comment by marandaneto** [comment]
https://github.com/PostHog/posthog/blob/fd440429a3e9317a082b03e92a3fc785c5ff5741/ee/frontend/mobile-replay/mobile.types.ts#L349-L374
