### ISSUE TITLE
Let the number visualisation of the trend insights visualise formula results

### ISSUE THREAD

**Issue by jensroelsN5** [PostHog/posthog#12069]
## Is your feature request related to a problem?

I want to calculate a Conversion Rate for the website and visualize this.
I have created the CR by using the trends report and taking two series (A and B) with a formula (B/A)

## Describe the solution you'd like

To have the number visualization show the result of the formula.

**Comment by Twixes** [comment]
Hey, this is now possible on PostHog Cloud and will land in PostHog 1.41!
