### ISSUE TITLE
Export failed! error message when trying to Export data from Posthog

### ISSUE THREAD

**Issue by oliversohohouse** [PostHog/posthog#12066]
## Bug description

I work at Soho House. I am unable to export any of my posthog reports. When I try to export the data to csv, I am presented with an "Export failed!" error message. I've tried this on multiple reports, and it happens on all of them, which leads me to believe it's a config issue. This is blocking the Product team from understanding engagement, so please prioritise. 

## How to reproduce

1. Create an insight 
2. Funnel 
3. Input some data to generate an insight 
4. Select ...
5. Select export 
6. See error message 

![image](https://user-images.githubusercontent.com/114688282/193532690-c5530ab1-40c5-4e57-acc2-6729164f2e78.png)

Report available here: https://posthog.infra.sohohousedigital.com/shared/HOlMQkszL2dq7UKIYfTR0mSGoe32EA

## Environment

- [ ] Production 
- [ ] I'm not sure of the environment settings. But I'm sure you can check. Our project is https://posthog.infra.sohohousedigital.com
- [ ] self-hosted PostHog, version/commit: please provide

## Additional context

This is blocking the Product team from understanding engagement, so please prioritise.

**Comment by pauldambra** [comment]
Hey @oliversohohouse 👋 

I've just confirmed that I can export from funnels (and paths as in your screenshot). So I _think_ it's something to investigate based on your setup or data (which doesn't rule out this is a bug that isn't showing up in PostHog cloud)

I think you're running a self-hosted version. Can you confirm what version you're running and how it is deployed?

It would also be great to see what is being logged. The log messages for CSV exports all contain the text "csv_exporter"

The export times out after 60 seconds. From looking at the screenshot I _think_ the failure is coming before that.

We try to capture an event to posthog when the export fails. Do you have `export failed` events showing? You'd see them https://posthog.infra.sohohousedigital.com/events?eventFilter=export%20failed
