### ISSUE TITLE
Firefox not registering Events

### ISSUE THREAD

**Issue by ungless** [PostHog/posthog#1207]
### Bug description
With Firefox (78.0.2-1), events (e.g. `$pageview`) are not triggered. No POST request is made when these events are triggered.

### How to reproduce

1. Run local instance of PostHog (e.g. /demo) 
2. Open in Firefox
3. Visit /demo

### Expected behavior
POST request should be made.

### Screenshots

![image](https://user-images.githubusercontent.com/8397061/87416883-47ae7200-c5c7-11ea-94ee-ba6c10c06fe9.png)

### Environment

- PostHog cloud or self-managed? self-managed (dev environment)
- PostHog version/commit (1.10.1)

**Comment by mariusandra** [comment]
Hi, I just tried locally (FF 78.0.1) and my events were registered:

![image](https://user-images.githubusercontent.com/53387/87531451-046d0580-c692-11ea-85e6-038b61da0016.png)
![image](https://user-images.githubusercontent.com/53387/87531538-21a1d400-c692-11ea-86fe-10e4a1938838.png)

Could it be that you had authorized the toolbar? When that's done we stop tracking pageviews for the session.

**Comment by ungless** [comment]
I unauthorized the toolbar and it still persists. Could be a FF on Linux problem. 
FF is also spitting:
```
Cookie “ph_vLik7N78mFAdhkQaZXfd18aN3InKoDBHCrJigvGhl-U_posthog” will be soon rejected because it has the “sameSite” attribute set to “none” or an invalid value, without the “secure” attribute. To know more about the “sameSite“ attribute, read https://developer.mozilla.org/docs/Web/HTTP/Headers/Set-Cookie/SameSite array.js:4:10682
```
I'll look into it anyway.

**Comment by masonhensley** [comment]
I'm also getting related errors in firefox (below) on one of my tracked sites.

Context: https://hacks.mozilla.org/2020/08/changes-to-samesite-cookie-behavior/

```
Cookie “_myapp_platform_session” will be soon rejected because it has the “sameSite” attribute set to “none” or an invalid value, without the “secure” attribute. To know more about the “sameSite“ attribute, read https://developer.mozilla.org/docs/Web/HTTP/Headers/Set-Cookie/SameSite sign_in

Cookie “ph_6c-pFvKa2paurnFP_Cn5RnHn_VbYq-H55JpO2_audlo_posthog” will be soon rejected because it has the “sameSite” attribute set to “none” or an invalid value, without the “secure” attribute. To know more about the “sameSite“ attribute, read https://developer.mozilla.org/docs/Web/HTTP/Headers/Set-Cookie/SameSite 8 array.js:4:10682

Cookie “__ph_opt_in_out_6c-pFvKa2paurnFP_Cn5RnHn_VbYq-H55JpO2_audlo” will be soon rejected because it has the “sameSite” attribute set to “none” or an invalid value, without the “secure” attribute. To know more about the “sameSite“ attribute, read https://developer.mozilla.org/docs/Web/HTTP/Headers/Set-Cookie/SameSite array.js:4:10682

Cookie “ph_6c-pFvKa2paurnFP_Cn5RnHn_VbYq-H55JpO2_audlo_posthog” will be soon rejected because it has the “sameSite” attribute set to “none” or an invalid value, without the “secure” attribute. To know more about the “sameSite“ attribute, read https://developer.mozilla.org/docs/Web/HTTP/Headers/Set-Cookie/SameSite 3 array.js:4:10682
```

**Comment by ungless** [comment]
@masonhensley Is your PostHog instance recording events?

I'll write up a separate issue for the `sameSite` changes since they AFAIK this issue was present before Firefox changed `sameSite` behavior.

**Comment by mariusandra** [comment]
Indeed, this warning should be fixed ([posthog-js](https://github.com/PostHog/posthog-js) is setting a cookie in a bad way), but it's a warning and not an error.

**Comment by ungless** [comment]
Weirdly, after upgrading Firefox to 79.0-1 events are registering for me. I think this issue is good to close, and `sameSite` discussion can be moved to https://github.com/PostHog/posthog-js/issues/76.

**Comment by timgl** [comment]
Is it related to [this firefox announcement](https://blog.mozilla.org/blog/2020/08/04/latest-firefox-rolls-out-enhanced-tracking-protection-2-0-blocking-redirect-trackers-by-default/) maybe?

**Comment by masonhensley** [comment]
@ungless - sorry, missed the notifications. Yes, it was recording. 

It looks like it's more of a warning of future potential errors than a functional error right now

**Comment by RylanSchaeffer** [comment]
I'm getting the exact same message as @masonhensley on Firefox 100.0.2. What is the solution?
