### ISSUE TITLE
Sprint Growth - Oct 3 to Oct 25

### ISSUE THREAD

**Issue by jamesefhawkins** [PostHog/posthog#12083]
nb assuming we time the sprints for this from one 30 min meeting like this to the next in person

## Retro

* [Removed b2c discount form](https://github.com/PostHog/posthog.com/pull/4312) (instead made it a 'call us') so we don't take people out of flow
* Community roadmap "backend" exists
* We [made proxy instructions more obvious](https://github.com/PostHog/posthog.com/pull/4333) in the getting started guide

### High priority

- Applying b2c discount to every b2c or b2b2c customer _proactively_ (@jamesefhawkins)
- Help website and docs team ship community roadmap (so people can opt into new things easily) @jamesefhawkins 
- Ask CS team to share [why track your marketing website](https://posthog.com/blog/posthog-marketing) with teams that don't currently do this (@simfish85 this could be a simple win to increase volumes - [this is the list of customers](https://metabase.posthog.net/question#eyJkYXRhc2V0X3F1ZXJ5Ijp7InR5cGUiOiJuYXRpdmUiLCJuYXRpdmUiOnsicXVlcnkiOiJcblxuc2VsZWN0IGNvdW50KDEpIGZyb20gKFxuXG53aXRoIHRyYWNrc19tYXJrZXRpbmdfd2Vic2l0ZSBhcyAoXG4gICAgICAgIHNlbGVjdCBkaXN0aW5jdCB0ZWFtX2lkIGZyb20gZXZlbnRzIHdoZXJlIFxuICAgICAgICB0aW1lc3RhbXAgPiAnMjAyMi0wOC0yNCcgYW5kXG4gICAgICAgIGNvdW50U3Vic3RyaW5ncyhKU09ORXh0cmFjdFN0cmluZyhwcm9wZXJ0aWVzLCAnJGhvc3QnKSwgJy4nKSA9IDEgYW5kXG4gICAgICAgIGVuZHNXaXRoKEpTT05FeHRyYWN0U3RyaW5nKHByb3BlcnRpZXMsICckY3VycmVudF91cmwnKSwgJy8nKSBhbmRcbiAgICAgICAgZXZlbnQgPSAnJHBhZ2V2aWV3JyApICxcbiAgICAgICB0cmFja3NfYXBwIGFzIChcbiAgICAgICAgc2VsZWN0IGRpc3RpbmN0IHRlYW1faWQgZnJvbSBldmVudHMgd2hlcmUgXG4gICAgICAgIHRpbWVzdGFtcCA-ICcyMDIyLTA4LTI0JyBhbmRcbiAgICAgICAgY291bnRTdWJzdHJpbmdzKEpTT05FeHRyYWN0U3RyaW5nKHByb3BlcnRpZXMsICckaG9zdCcpLCAnLicpID4gMSBhbmRcbiAgICAgICAgZXZlbnQgPSAnJHBhZ2V2aWV3JyApIFxuc2VsZWN0IHRlYW1faWRcbmZyb20gZXZlbnRzXG4gd2hlcmUgdGVhbV9pZCBpbiB0cmFja3NfYXBwIGFuZCB0ZWFtX2lkIG5vdCBpbiB0cmFja3NfbWFya2V0aW5nX3dlYnNpdGVcbmdyb3VwIGJ5IHRlYW1faWRcblxuKSIsInRlbXBsYXRlLXRhZ3MiOnt9fSwiZGF0YWJhc2UiOjJ9LCJkaXNwbGF5IjoidGFibGUiLCJ2aXN1YWxpemF0aW9uX3NldHRpbmdzIjp7fX0=) that don't do this at the moment) 
- @jamesefhawkins to discuss EU pricing on website with @corywatilo (20% more expensive - as a bolt on like the enterprise features is the conclusion for now)

**Comment by kappa90** [comment]
Additional topics:
- https://github.com/PostHog/company-internal/issues/853
- Cloud EU pricing, same or higher? Who has ownership of this?

**Comment by jamesefhawkins** [comment]
# Em

Support hero next week

## Retro

- Good position to deploy end of week in testing a new billing service on EU cloud
  - Now 1 central service for cloud _and_ self hosted
  - Old ones self hosted need to upgrade (or stay?)
  - New docs for CS on how to handle stuff. Discounts / special pricing / multiple products now possible.

(revenue.posthog.com?)

## Todo

- Improve usage report (into 1 thing) @kappa90 
- Deploy onto EU cloud this week with Ellie @kappa90 
- Migrate existing customers on cloud @kappa90 
- Confirm if we can get the new billing system to cope with EU cloud _OR_ ensure website makes it obvious to us so we can manually change them @kappa90 
- @lharries to make sure launch happens on the right day
- Let's not do this meeting again!

**Comment by simfish85** [comment]
On pricing I’m 100% against differentiated pricing for EU Cloud. It risks annoying our existing customers who are migrating, and our cloud and self hosted options are priced the same, why complicate it for another cloud deployment? IMO we will have better revenue growth by pricing fairly across all regions and deployment types.

**Comment by jamesefhawkins** [comment]
> why complicate it for another cloud deployment

It costs 20% more (literally every AWS service in the EU is marked up by this much) + we have to maintain it all 

I'd treat as a bolt on, just a second thing to slide on/off like this:

<img width="341" alt="Screenshot 2022-10-04 at 22 18 40" src="https://user-images.githubusercontent.com/47497682/193931598-6fcd5b2b-4bd7-49c5-b54f-f2aa48108be6.png">

A revenue boost _isn't_ the primary motivator - it's more to land top of funnel growth _but_ it'll be annoying to just take a 20% margin hit especially if existing cloud customers migrate to it. I'd almost prefer to increase our US pricing (but then perhaps _increase_ our B2C discount) so we don't take a hit - what do you think?

**Comment by simfish85** [comment]
> It costs 20% more (literally every AWS service in the EU is marked up by this much) + we have to maintain it all

Any idea what our current and target operating margins are on US Cloud?

> I'd treat as a bolt on, just a second thing to slide on/off like this:

This just adds extra complexity to what is already quite a few choices.  Enterprise features are also not the same kind of thing as deployment region so I don't agree with making it an additional option.

> I'd almost prefer to increase our US pricing (but then perhaps increase our B2C discount) so we don't take a hit

This would be a better approach - suggest 5-10% across the board to preserve our pricing parity between all deployment options.  When we come to do this again as we scale up (for APJ, or on a different Cloud provider as some larger customers won't use cloud services based on AWS as they are a competitor) then we want to keep things simple for customers and for ourselves.

**Comment by andyvan-ph** [comment]
A couple of thoughts on this:

1. If it's on the table, I'm strongly in favour of increasing all pricing to ensure pricing parity between EU and US Cloud. I think having a large disparity will confuse / annoy both existing and potential customers. As we saw with the pricing page changes earlier this year, having big differences between Cloud and self-host pricing just led to lower conversion.

2. If we're dead set on a 20% increase, I'd advocate a few different approaches: a completely separate pricing page / signup flow for PostHog Cloud EU. The current pricing page would remain the same and we'd just add a link pushing people to a separate EU Cloud page if that's what they need. This would eliminate the dissonance of people comparing US Cloud and EU Cloud, and also communicate we view them as someone separate products.

**Comment by jamesefhawkins** [comment]
Reading the above - I think the MVP is to launch _without_ different pricing.

We can then make all pricing a bit more expensive later for _EU_ and _US_ (or indeed create a nice calculator that isn't confusing...!) if it's popular and dramatically increases costs.

One tactic I'd avoid as a result @joethreepwood is doing the in-app banner as it's not super appealing to encourage users to migrate from US to EU unless they've explicitly asked
