### ISSUE TITLE
Group analytics looks locked, when not, before group events ingested

### ISSUE THREAD

**Issue by jamesefhawkins** [PostHog/posthog#12080]
## Bug description

Group analytics looks locked even if a card has been entered. i think it only goes if the first group event is entered

## How to reproduce

1. create new account
2. put card in
3. group events look locked (if you go to Events then filter at top right on Groups)

## Environment

- [ ] PostHog Cloud
- [ ] self-hosted PostHog, version/commit: please provide

**Comment by EDsCODE** [comment]
Can you add images here? Not sure which group events you're looking at

**Comment by lanthias** [comment]
Here's a screenshot which might be helpful.

<img width="1588" alt="image" src="https://user-images.githubusercontent.com/3541695/194103900-32128b27-697c-442b-863f-225e5529c553.png">

FWIW, I also can't do things like add descriptions to events (not sure if it's related, but I couldn't find any breakdown in pricing which would cause this)

<img width="675" alt="image" src="https://user-images.githubusercontent.com/3541695/194104059-c5507bf5-c355-41ff-bed7-b05e4f343fa0.png">

**Comment by lharries** [comment]
I just tried to reproduce it but it seems to be fixed. Closing this issue but let me know if you see it again
<img width="1249" alt="Screenshot PostHog (Google Chrome) 2022-12-13 at 15 22@2x" src="https://user-images.githubusercontent.com/22766134/207373219-b8ad75fb-dfff-4d67-b8c0-4c5962488424.png">
