### ISSUE TITLE
Network requests for Recordings

### ISSUE THREAD

**Issue by benjackwhite** [PostHog/posthog#12096]
## Is your feature request related to a problem?

[Nicely described by someone in posthog-users slack (thanks!) ](https://posthogusers.slack.com/archives/C01GLBKHKQT/p1664894769845589?thread_ts=1664813680.706589&cid=C01GLBKHKQT) which explains the job-to-be-done well:

> for one, it will enable our support and dev teams to get a holistic understanding of a user’s session and quickly identify next steps. As an example we had a user complaint about an action not working on the UI - support reviewed their session recording and confirmed that the action was failing but our UI printed a generic error message. They escalated and the dev team replicated network calls to see what is being returned - they found our backend service had a bug in completing the action for that specific scenario. Our backend service is returning descriptive error messages but we don’t always print them to the user. So being able to see a network trace makes the debugging process significantly more efficient.

## Describe the solution you'd like

Similar to our testing with web-performance and console log recording, we would have a new tab for network requests showing a simplified version of what comes into the network panel. Not sure how much of this is exposed to JS in a non-intrusive way. We would then hook into rrweb with a custom plugin to add these as custom events and display them client side.

We could start minimal and collect only:
* URL, method, status, request time, response time

## Additional context

* Important to not collect sensitive data here so we should start minimal and overly-cautious and expand as we learn.
* We already looked at something similar as an alpha experimental feature ([see js here](https://github.com/PostHog/posthog-js/blob/master/src/apm.ts))

**Comment by Hoss3770** [comment]
I would also love to see this feature 
For my it is a deal breaker. 
Other platforms like logrocket for example do it very well.
I would also add filtering the sessions by request and maybe errors.

**Comment by Twixes** [comment]
+1 from a [user on Slack](https://posthogusers.slack.com/archives/C01GLBKHKQT/p1668187386015979).
