### ISSUE TITLE
[HELP] PostHog self-hosted 500 internal server errors

### ISSUE THREAD

**Issue by robliv** [PostHog/posthog#12105]
## Bug description
Have deployed self-hosted PostHog helm charts on EKS, using external AWS Redis, Postgres, MSK Kafka.

Able to connect to PostHog, register, sign in, browse the project. 

Not able to see any data in live events even though it was recorded.
Browser console shows status 500 internal server errors on first load of any PostHog page. See image below.

Also occasionally getting frontend toast error notifications:
1. Load repository on reducer Repository failed: A server error occurred.
2. There was a problem fetching your events: undefined

Looking for tips on how to debug this issue. Could it be postgres or kafka related? Cert related? Something with ingress, or PostHog itself? 

## How to reproduce

1. Deploy PostHog Helm charts with AWS Redis, Postgres, Kafka
2. Connect, log in, see error

## Environment

- [ ] PostHog Cloud
- [ X ] self-hosted PostHog, version/commit: please provide: posthog-clickhouse 27.1.3

## Additional context
MSK Kafka 3.2.0 2 brokers, using plaintext auth for brokers and zookeeper
RDS Aurora postgres 13.4
ElastiCache Redis 6.2.6
EKS 1.22
Using NGINX ingress controller, Route53 DNS.

Not seeing any related errors in these pods - posthog-worker, posthog-web, posthog-plugins, posthog-events. All pods work fine.
Seeing some cert issues in posthog-certmanager, likely unrelated:

`Could not determine issuer for ingress due to bad annotations: failed to determine issuer name to be used for ingress resource`

Seeing chi-posthog errors, also possibly unrelated:
`<Error> void DB::StorageKafka::threadFunc(size_t): Code: 242. DB::Exception: Table is in readonly mode (zookeeper path: /clickhouse/tables/noshard/posthog.person). (TABLE_IS_READ_ONLY)`

![image](https://user-images.githubusercontent.com/46368581/194036799-7a9cbaf4-8253-4007-a24a-00e9517b2561.png)

![image](https://user-images.githubusercontent.com/46368581/194037319-838d94c6-1a48-4cde-b9e3-1e8ee1dd3d92.png)

**Comment by robliv** [comment]
I managed to fix the issue where live events are missing. It was related to the chi-posthog errors I mentioned. Had to update externalZookeeper values for clickhouse helm chart.

The main issue is still there and 500 errors for plugins repository are still showing up. Not sure if it causes any functionality issues though.

**Comment by tiina303** [comment]
Table in TABLE_IS_READ_ONLY looks related to https://github.com/PostHog/posthog/issues/12312

**Comment by guidoiaquinti** [comment]
> Had to update externalZookeeper values for clickhouse helm chart.

Can you please share your initial and your current `values.yaml` (redacting any private information it might contain)? 

I'm asking to verify if you migrated from internal to external Zookeeper as you can't do that safely without performing a data migration. This is why you might see CH complaining for tables in RO mode.

**Comment by robliv** [comment]
Posting in case someone else down the line gets these issues. 

Initially the RO table issue was solved by fixing Clickhouse externalZookeeper values in the `values.yaml` file. They need to be set in two places in the file. Clickhouse values and Zookeeper values.

Afterwards I managed to trigger the read-only tables error again by re-creating our MSK Kafka cluster. Was a pain to debug this and I finally found that the Clickhouse pod had some metadata sql files that still referred to the obsolete zookeeper server hostnames. Fixed that, but it didn't help, so I used Clickhouse client to connect to Clickhouse tables and searched for the old hostname, found it in many tables. I'm sure this was the reason, but wasn't sure about a good way to fix it, so since this was just a dev instance I nuked all the posthog and clickouse data and started from scratch with the new config.

Then I kept working on fixing second issue which was SSL error with the plugins repository (500 internal server errror).
Was very difficult to debug it but I found that needed to add our company CA certs bundle to the certifi Python module in the Posthog docker image. (/usr/local/lib/python3.8/site-packages/certifi/cacert.pem)

**Comment by guidoiaquinti** [comment]
Glad you’ve solved the issue @robliv 🎉 ! I have a few follow-up questions for you:

> Initially the RO table issue was solved by fixing Clickhouse externalZookeeper values in the values.yaml file. They need to be set in two places in the file. Clickhouse values and Zookeeper values.

This depends on your configuration and what do you want to archive. Here are some (hopefully) clarifying points: 

* If you want to use an external Zookeeper for Kafka, you can do that by providing the override `kafka.externalZookeeper. servers` (as per the upstream chart dependency `bitnami/kafka`).

* If you want to use an external Zookeeper for ClickHouse, you can do that by providing the override `clickhouse.externalZookeeper.servers` (as per our chart configuration).

Note: if you want to move from a Zookeeper installation to another, you can’t simply change your infrastructure config as ZK is a stateful service and data doesn’t automagically get copied.  

> Afterwards I managed to trigger the read-only tables error again by re-creating our MSK Kafka cluster. Was a pain to debug this and I finally found that the Clickhouse pod had some metadata sql files that still referred to the obsolete zookeeper server hostnames. Fixed that, but it didn’t help, so I used Clickhouse client to connect to Clickhouse tables and searched for the old hostname, found it in many tables. I’m sure this was the reason, but wasn’t sure about a good way to fix it, so since this was just a dev instance I nuked all the posthog and clickouse data and started from scratch with the new config.

This is correct, and that’s more or less what I’ve explained in the note above. ClickHouse tables rely on Kafka topics (and their metadata) to get populated. We can’t destroy and recreate Kafka without performing some steps to bring over (at least) some metadata.

> Then I kept working on fixing second issue which was SSL error with the plugins repository (500 internal server errror).
> Was very difficult to debug it but I found that needed to add our company CA certs bundle to the certifi Python module in the Posthog docker image. (/usr/local/lib/python3.8/site-packages/certifi/cacert.pem)

This looks an environment specific issue but if you think that’s a PostHog bug open another issue and we’ll be happy to look!

Thank you! 🙇

**Comment by robliv** [comment]
Thank you for the clarification @guidoiaquinti ! And yes, these issues were mostly environement specific and caused by my own lack of knowledge regarding how these technologies work and interact.

The PostHog docs could be improved a bit because when deciding to re-create the MSK Kafka instance ( and causing the issue with RO tables the second time) I relied on this doc which to me seemed to hint that wiping all Kafka data should not be an issue: https://posthog.com/docs/runbook/disaster-recovery

**Comment by guidoiaquinti** [comment]
Thank you for the feedback @robliv ! 

I've opened a PR to update the doc page. Feedback is welcome 👍 

I'm going to close this issue as ✅
