### ISSUE TITLE
Breakdown on Session Duration Insights are broken

### ISSUE THREAD

**Issue by janhenriklambrechts** [PostHog/posthog#12109]
### Query
- Insights Page
- Trends Tab
-  `Autocapture` + `Average` + `Session Duration` query
- Any *Breakdown*

### Expected Behavior
Query succeeds and I get my data in a graph

### Actual Behavior
Get a `There was an error completing this query`-error. 
I retried multiple times and with many different Breakdown properties and it will not work.
However, without a breakdown it performs as expected.

## How to reproduce

1. Go to Insights Page
2. Go to Trends Tab
3. Query for `Autocapture` + `Average` + `Session Duration` query
4. Add any *Breakdown* property

## Environment

- [x] PostHog Cloud
- [ ] self-hosted PostHog, version/commit: please provide

## Additional context

Screenshot:

(In the screenshot you will  see a filter on `UTM Source`, removing this filter will still end up with an error) 

![Screenshot 2022-10-05 at 15 52 12](https://user-images.githubusercontent.com/31068156/194093739-8739992d-0db1-47ab-bcf5-93dd9bab5cbd.png)

**Comment by EDsCODE** [comment]
HI! Thank you for submitting this bug. Are you on cloud?

**Comment by janhenriklambrechts** [comment]
Yes, on Cloud!

**Comment by EDsCODE** [comment]
Do you mind sharing the email of the account where you're seeing this (I can find the trace more easily in sentry!). Our community slack is here https://posthog.com/slack

**Comment by janhenriklambrechts** [comment]
@EDsCODE Sure, I sent you a Slack DM.
