### ISSUE TITLE
Different results for "Last 7/14/x days" in Trends and Funnel

### ISSUE THREAD

**Issue by pwanning** [PostHog/posthog#12104]
## Bug description
We've experiencing different results comparing total numbers for "Last 7 days" in "Trends" and "Funnel":

## How to reproduce
- I am switching visualizations between Trends and Funnel in an insight (same configuration (unique users, filters, ...))
- When i look at a specific date with "Custom fixe time period" (or "Yesterday"/"Last 24 hours"), i always get the exact same result in both visualizations
- But when i switch to "Last 7 days" (or 14 ...)  i get different results (~10-15% more in "Trends")
- It looks like the "Last 7 days" results in "Funnel" is accurate (adding the results of the last 7 days)

Screencast:  https://www.loom.com/share/b9b56cc83e2e4798bf8a2436789b9f72

## Environment

- [x] PostHog Cloud
- [ ] self-hosted PostHog, version/commit: please provide

**Comment by EDsCODE** [comment]
Hi @pwanning!
Thanks for bringing this up. I took a look and it seems like we're doing some inconsistent rounding. On trends we're rounding to the start of the interval but on funnels we're taking the exact timestamps of "last X days". There's a time handling rework in progress that should touch on this issue: https://github.com/PostHog/posthog/pull/11935

**Comment by pwanning** [comment]
Just re-checked it - this issue seems to be resolved. Thanks!
