### ISSUE TITLE
API returns a server error when calling the group endpoint 

### ISSUE THREAD

**Issue by rez1khan** [PostHog/posthog#12131]
## Bug description

I am getting a server error when I am calling the group API end-point.  

<img width="1007" alt="image" src="https://user-images.githubusercontent.com/95234072/194401070-aa5093ca-76a9-4882-9f7c-74c8912a05b0.png">

I have tried all the endpoints. I have access to the group feature because I ugpraded to a paying account. The UI is showing all the associated groups for me. 

<img width="1169" alt="image" src="https://user-images.githubusercontent.com/95234072/194401204-415dcd1b-1cbf-4de5-b1cd-0386913deb55.png">

Thanks for your help! 

## How to reproduce

1.
2.
3.

## Environment

- [ ] PostHog Cloud
- [ ] self-hosted PostHog, version/commit: please provide

**Comment by EDsCODE** [comment]
This endpoint requires group_type_index atm. Addressed here: https://github.com/PostHog/posthog/pull/12116

**Comment by timgl** [comment]
Made clear with above PR.
