### ISSUE TITLE
Table on events page shows all events

### ISSUE THREAD

**Issue by williamhc** [PostHog/posthog#12146]
## Bug description
When going to a given events page, I expect the table below to only show instances of that event, but it's pulling in everything.
<img width="829" alt="CleanShot 2022-10-07 at 09 00 58@2x" src="https://user-images.githubusercontent.com/1755752/194559912-66387e1a-ba1d-46b1-9c9d-6e11d0d66681.png">

## How to reproduce

1. navigate to https://app.posthog.com/data-management/events/0181d5bf-314f-0000-893f-dff202001a5a?eventFilter=
2. scroll down
3. expect to see only Model Previewed events, but see a bunch of different events too

## Environment

- [x] PostHog Cloud
- [ ] self-hosted PostHog, version/commit: please provide

## Additional context
https://posthogusers.slack.com/archives/C01GLBKHKQT/p1665084603554879

**Comment by timgl** [comment]
Fixed with linked PR
