### ISSUE TITLE
Question: Use Posthog to monitor web app(s) deployed on-premise?

### ISSUE THREAD

**Issue by rudasn** [PostHog/posthog#1215]
(Please let me know if there's another channel to raise this question. Thanks)

We have a webapp that we deploy to clients on their on-premise servers. The app is the same for all clients, with the exception of not always all of them being on the same version. Also, since it's on-premise, the app is served over http and from a local IP (eg. 192.168.x.x).

We'd like to gather product usage statistics throughout all installations into a single place. Is that possible?

More specifically, we'd like for each installation to send its own stats and, at the receiving end, be able to segment the data by client (not just session/user), but also get an overall view of the data. 

The questions we'd like to answer right now revolve around feature usage (how often is feature X used, how is it actually used, etc).

Very cool project, thanks!

**Comment by mariusandra** [comment]
Hi @rudasn , this sounds possible!

As long as your app instances have access to your posthog instance, everything should work fine.

When you include [posthog-js](https://posthog.com/docs/integrations/js-integration/) on your page (either via npm or through the snippet), you can call `posthog.people.set({email: 'john@gmail.com', teamId: 4})` to set properties on the user. One of these could be the client or installation ID that you need later to segment the users.

**Comment by rudasn** [comment]
Thanks @mariusandra . I'll check it out.

**Comment by timgl** [comment]
Closing this as it isn't an open issue, but please let us know if you have any more questions! Our [user slack is here](https://join.slack.com/t/posthogusers/shared_invite/enQtOTY0MzU5NjAwMDY3LTc2MWQ0OTZlNjhkODk3ZDI3NDVjMDE1YjgxY2I4ZjI4MzJhZmVmNjJkN2NmMGJmMzc2N2U3Yjc3ZjI5NGFlZDQ)!
