### ISSUE TITLE
Improve query speed and reliability of recordings for events

### ISSUE THREAD

**Issue by benjackwhite** [PostHog/posthog#12168]
## Is your feature request related to a problem?

We reverted the change that adds matched recordings to the event list as the performance was much worse. Now it is simply a button that always shows if `$session_id` is present leading to a "not found" view if there is no related recording.

## Describe the solution you'd like

To improve on this we could
1. Load the sessions separately either with a given list of IDs or the events query itself
2. Check if the session exists when the dropdown button is clicked

If we have the `events_summary` work added then querying for an individual session should be much faster (currently it is slow as it parses the snapshot data in full.

## Additional context

[Internal PostHog Slack thread](https://posthog.slack.com/archives/C03PB072FMJ/p1665402878390719?thread_ts=1665398529.751709&cid=C03PB072FMJ)

**Comment by ilyalasy** [comment]
Hey, it is not very clear for me: how is it possible to map a posthog event to a recording (rrweb) action without `matched_recordings` field?
