### ISSUE TITLE
Display if a recording is watched on the Recordings page

### ISSUE THREAD

**Issue by eraldoforgoli** [PostHog/posthog#12209]
## Is your feature request related to a problem?

I see that the recordings page is updated with a new UI/UX. The last version had a way to identify if the user had already watched the recording or not (the play icon was blue when a recording was not watched, and gray when watched).

## Describe the solution you'd like

I'd like a way for me to understand if a recording is watched or not. Adding an icon or tag to identify if a recording is watched or not works fine. 

## Describe alternatives you've considered

I tried using the filters, but that's too confusing IMO. I should be able to see if a recording is watched or not right away.

#### *Thank you* for your feature request – we love each and every one!

**Comment by benjackwhite** [comment]
@eraldoforgoli Thanks for the suggestion. This was already in the works but I bumped it up. Should have an indicator as well as some other improvements coming in the next days 💪

**Comment by eraldoforgoli** [comment]
> @eraldoforgoli Thanks for the suggestion. This was already in the works but I bumped it up. Should have an indicator as well as some other improvements coming in the next days 💪

@benjackwhite thanks, really appreciate how fast you tackled this one 💯 Keep up the good work 🙌
