### ISSUE TITLE
Feature flags platform: Flutter

### ISSUE THREAD

**Issue by lharries** [PostHog/posthog#12222]
The Experimentation Team is currently considering adding feature flag capabilities to[ the Posthog Flutter client-side library](https://posthog.com/docs/integrate/client/flutter). 

🗂 **Considered goals**
- [ ] Add feature flag support to Flutter

These goals are being considered by [the Experimentation Team](https://posthog.com/handbook/small-teams/experimentation) and we'd love to hear user feedback, as well as ideas for stretch goals or implementation.

**If you like this idea, please leave a 👍 or ❤️ reaction on this post to vote for it -- your votes and feedback help us prioritize what to work on next!**

**Comment by joethreepwood** [comment]
I've updated the issue above to use a simple CTA template as we add this to `/roadmap`

**Comment by marandaneto** [comment]
There's some [support](https://github.com/PostHog/posthog-flutter/blob/78762f463f1cbae3906858c32277f1cf5b0b4bd4/lib/src/posthog.dart#L102-L108) but it's missing some methods eg https://github.com/PostHog/posthog-flutter/issues/38

**Comment by marandaneto** [comment]
https://github.com/PostHog/posthog-flutter should have all the methods for feature flags (SDK v4)
