### ISSUE TITLE
Feature flags platform: iOS

### ISSUE THREAD

**Issue by lharries** [PostHog/posthog#12224]
Add feature flag capabilities to the Posthog iOS client-side library

**Comment by lharries** [comment]
The client side library is live but the docs still need updating as mentioned here: https://github.com/PostHog/posthog.com/pull/4085

**Comment by pjhul** [comment]
@lharries I believe this is complete? Looks like the docs update went through in https://github.com/PostHog/posthog.com/pull/4430

**Comment by lharries** [comment]
I believe so! cc @liyiy / @EDsCODE 

Android should be soon to follow
