### ISSUE TITLE
Is it possible to run the frontend in a standalone way

### ISSUE THREAD

**Issue by vmutafov** [PostHog/posthog#12236]
Hi! I'm trying to run a modified version of the Posthog frontend and have successfully run Posthog using the Hobby deployment scripts. However, this solution is really heavy for my use case so I'm wondering if it is possible to run the frontend alone on my machine and make it connect to the cloud-hosted Posthog API?

Thanks in advance!

**Comment by benjackwhite** [comment]
It isn't really possible as the frontend is partly rendered by the backend. What is your use case here?

**Comment by vmutafov** [comment]
@benjackwhite my use case is to strip some of the functionalities from the posthog-foss repository and add some custom pages. There are no changes that I have to make in the backend so in theory running only the frontend would be enough for me. 
The main reason to try to run only the frontend is that running the whole stack on DigitalOcean quickly becomes costly. I'm open to other options if there is a way to some sort of white-label the Posthog but I haven't seen anything on this topic.

**Comment by benjackwhite** [comment]
I think this use case isn't something we want to / can support for security reasons to say the least.

Can you elaborate anymore on the goal of whitelabelling / custom pages? We have a concept of Apps that we are working actively on to allow people to expand PostHog with extra functions. Conversely if you are doing this for an internal product, you could simply build your own frontend and talk to our API using a personal API Key that would be able to access all projects you have access to.

Or is this a use case where you want to sell PostHog as part of your platform offering (B2B2C?) - if so this would be a good thing to discuss with our customer success team.
