### ISSUE TITLE
Billing page breaks if payment method is removed

### ISSUE THREAD

**Issue by corywatilo** [PostHog/posthog#12238]
## Bug description

I wanted to remove my card from PostHog, so I canceled the subscription and deleted the card from stripe.

Now when trying to visit the billing page, there's a 500 error and nothing loads.

<img width="1389" alt="image" src="https://user-images.githubusercontent.com/154479/195666915-c9e43916-e58f-4a4c-af4e-2f9459731b0a.png">

## Error

```
if self.plan.is_metered_billing or self.plan.key == "startup":
```

[Stack trace](https://sentry.io/organizations/posthog/issues/3167325799/?project=1899813&query=is%3Aunresolved+user.email%3Acory%40foliohd.com&statsPeriod=14d)

## How to reproduce

1. Visit the [Billing](https://app.posthog.com/organization/billing) page
2. Click to manage subscription
3. Cancel subscription (in Stripe)
4. Remove card
5. Click back to return to PostHog

## Environment

PostHog Cloud

**Comment by benjackwhite** [comment]
I encountered this as well. Depending on how far we go with billing-v2, this may be fixed simply by focusing on the rollout. If it takes too long though we should check this out

**Comment by corywatilo** [comment]
[Related ticket](https://posthoghelp.zendesk.com/agent/tickets/700)
