### ISSUE TITLE
Two frontend tests for rendering plugin activity logs pass or fail depending on the developer's timezone

### ISSUE THREAD

**Issue by zackelan** [PostHog/posthog#12243]
## Bug description

https://github.com/PostHog/posthog/blob/master/frontend/src/lib/components/ActivityLog/activityLogLogic.plugin.test.tsx#L146

The "can handle exports finishing" and "can handle exports failing" tests fail, but only if the user's timezone is a negative UTC offset (such as in the US).

## How to reproduce

1. run `env TZ=UTC yarn test lib/components/ActivityLog/activityLogLogic.plugin.test.tsx` - it succeeds
2. run `env TZ=Europe/Moscow yarn test lib/components/ActivityLog/activityLogLogic.plugin.test.tsx` - it succeeds
3. run `env TZ=US/Pacific yarn test lib/components/ActivityLog/activityLogLogic.plugin.test.tsx` - it fails, despite no code changes

The failure messages are:

```
Expected element to have text content:
      Finished exporting historical events between 2021-10-29 and 2021-11-04 (inclusive).
    Received:
      Finished exporting historical events between 2021-10-28 and 2021-11-03 (inclusive).
```

```
Expected element to have text content:
      Fatal error exporting historical events between 2021-10-29 and 2021-11-04 (inclusive). Check logs for more details.
    Received:
      Fatal error exporting historical events between 2021-10-28 and 2021-11-03 (inclusive). Check logs for more details.
```

What's happening is that those two tests use a canned input date with a UTC timezone specified, and then assert on a rendered output message. The output message contains dates based on the local timezone, and `2021-10-29T00:00:00.000Z` is 2021-10-28 when in a timezone with a negative UTC offset (anywhere west of Greenwich and east of the international date line).

**Comment by zackelan** [comment]
@macobo - looks like you added this test last week. if you can point me in the right direction I'd be happy to fix this, or feel free to grab it yourself if that's easier.

**Comment by pauldambra** [comment]
This https://github.com/PostHog/posthog/pull/12245 fixes it... although it's quite a hammer to crack a nut since it locks the timezone to UTC for the tests. 

e.g. `env TZ=US/Pacific yarn test lib/components/ActivityLog/activityLogLogic.plugin.test.tsx` passes even though maybe it should fail

**Comment by neilkakkar** [comment]
You could set `process.env` only when it's not already set :)
