### ISSUE TITLE
Put docs directly in the product

### ISSUE THREAD

**Issue by timgl** [PostHog/posthog#12269]
## Is your feature request related to a problem?

1. I want to read docs to understand what the difference is between Stickiness and Retention for example
2. It's jarring to be sent from the product to the website.

## Describe the solution you'd like

For each insight, product and anywhere else we link to docs, instead of opening the website, it opens the docs in a drawer on the right. We can pull the markdown from github automatically and render it in a nice way.

## Additional context

cc @pjhul @corywatilo

**Comment by corywatilo** [comment]
It would be worth mocking this experience up.

Here's a semi-related concept (from Iceland Hackathon) for including a link to the product manual on relevant pages:

<img width="510" alt="image" src="https://user-images.githubusercontent.com/154479/195920451-54a5c140-adbd-41ee-a2a5-8e316a57fde3.png">

Would open you to the right chapter, depending on the page in the app you're on:

<img width="1635" alt="image" src="https://user-images.githubusercontent.com/154479/195920530-5366c9f0-f437-4d42-877e-e843ee665c24.png">
