### ISSUE TITLE
Multiple renameable formulas

### ISSUE THREAD

**Issue by benjackwhite** [PostHog/posthog#12286]
## Is your feature request related to a problem?

I'd like to be able to create multiple "formula" series. In addition to be able to name them something useful (the formula itself is not useful as a name)

## Describe the solution you'd like

Similar to being able to add multiple series / variables, have the same sort of controls for a standard series but for the formula (add forumla, delete, edit name)

## Additional context
Related bug https://github.com/PostHog/posthog/issues/9478

**Comment by lharries** [comment]
Came up as a request from another ICP customer today

**Comment by Twixes** [comment]
Closing as duplicate of #5196.
