### ISSUE TITLE
Remove the Toolbar "Dock" mode?

### ISSUE THREAD

**Issue by mariusandra** [PostHog/posthog#1229]
The Toolbar has two modes:

1. Button
![2020-07-16 14 59 25](https://user-images.githubusercontent.com/53387/87673506-f8a63f80-c774-11ea-94a6-848c293d64d7.gif)

2. Dock
![2020-07-16 14 59 59](https://user-images.githubusercontent.com/53387/87673580-11aef080-c775-11ea-8942-449584c75d9b.gif)

The original tasks and discussions revolving the toolbar centered around a docked version. The button mode was added later. 

Now after using the button mode several times, I haven't once felt the need to open the dock. I know that it's still broken and could be fixed, yet I find myself wondering if we shouldn't just completely eliminate the dock mode?

What do you all think? Does a mode that zooms the page out to ~70% and puts a sidebar next to that make sense? Would you use it?

The dock mode has several (unsolvable or hard to solve) issues. Thus we must offer the button mode as an alternative anyway. It should be possible to do everything that can be done in dock mode also in button mode.

Other issues with keeping the dock:
- We have to maintain 2 separate ways of doing the same thing. This complexity adds up
- There will be websites that will be broken in dock mode due to CSS limitations (no `position: fixed` possible anymore if we zoom the `body` out using CSS transform) and we'll have to fix them one by one
- I'm still not sure what's a good placement of buttons/actions/etc on the dock

Thus I propose to remove the dock and just keep the button mode. 

Any thoughts or objections?

**Comment by lottiecoxon** [comment]
I vote no dock as you can use the toolbar without it - but obviously I am not a coder so maybe gather others opinions

**Comment by fuziontech** [comment]
I totally agree. I wish we could get a perfectly working dock, with no bugs, working for free along with the button. My only worry about getting rid of the dock entirely is if we want to start surfacing really dense data in this mode side by side with the page. The thing that I worry about most there is Feature Flag testing and A/B Testing results. I would be worried that we put ourselves into a corner and would have to bring the dock back if we can't develop a way to show the results using the Button effectively.

**Comment by jamesefhawkins** [comment]
> The thing that I worry about most there is Feature Flag testing and A/B Testing results. I would be worried that we put ourselves into a corner and would have to bring the dock back if we can't develop a way to show the results using the Button effectively.

We already have a stats pop up
![Screenshot 2020-07-18 at 15 44 37](https://user-images.githubusercontent.com/47497682/87855051-b5cb9f80-c90d-11ea-9d87-d020cffb9593.png)
 
I'd suggest it'd be a lot simpler to put dense info into this box in future if we want to do this as the CSS will be much simpler, then ditch dock mode for the reasons Marius states above. Arguably this pop up is a better way to not lose the screen real estate that the extra borders around the dock create anyway, if it can be draggable and resizable so it doesn't get in the way of key parts of the underlying page.

**Comment by mariusandra** [comment]
Hi! Reading the comments from all of you, I take it I can move forward with removing the dock view and focus all the effort on the button?

Closing this issue. Feel free to comment/reopen in case of disagreements.
