### ISSUE TITLE
Package calls are slow

### ISSUE THREAD

**Issue by EDsCODE** [PostHog/posthog#1233]
### Bug description
It seems that the calls we make in our libraries for array.js and the new /decide endpoint are heavy

![image](https://user-images.githubusercontent.com/13127476/87707408-0d7fd480-c76f-11ea-8425-45b01b08d1b6.png)

### Environment

- PostHog cloud or self-managed?
- PostHog version/commit

**Comment by timgl** [comment]
I just installed cloudflare to try and remedy at least array.js (serve over cdn) but haven’t seen if it helped or not

**Comment by alex-ketch** [comment]
@timgl Will keep you posted, but right now it seems worse 😅

![Screenshot 2020-07-16 at 18 22 17](https://user-images.githubusercontent.com/1646307/87728776-c48d4780-c791-11ea-8ddd-770320d40f18.png)

**Comment by timgl** [comment]
@alex-ketch Are you seeing the below in the array.js headers? They should be served via Cloudflare DNS and be fairly quick

![image](https://user-images.githubusercontent.com/1727427/87792040-97996d00-c843-11ea-9f12-ac272c052898.png)

**Comment by alex-ketch** [comment]
Hi @timgl, I did some poking around and seems it might have something to do with the geography.
The screenshots above were taken from Pingdom page speed checks running from their European servers.

I checked and the cache headers are present but the calls were still relatively slow.
Here are the latest results I have:

**European Servers**
![Screenshot 2020-07-17 at 10 18 09@2x](https://user-images.githubusercontent.com/1646307/87796837-e6c9a880-c817-11ea-81b4-d57dcb27ca8f.png)

![Screenshot 2020-07-17 at 10 19 32@2x](https://user-images.githubusercontent.com/1646307/87796848-eb8e5c80-c817-11ea-9c55-598b04fa649f.png)

However I just added the same checks from Eastern US location and the response times were much lower.

**US East**
![Screenshot 2020-07-17 at 10 20 15@2x](https://user-images.githubusercontent.com/1646307/87796924-095bc180-c818-11ea-812d-a54f79bc10f1.png)

To compare, I ran a free test on Dareboost which runs from Paris and the results seemed to align with the Pingdom ones. [Results are here](https://www.dareboost.com/en/report/a_25f11b6e0a0612f3fae590b79?reportIds=a_25f11b6e0a0612f3fae590b79), but not sure for how long.

<img width="1680" alt="Screenshot 2020-07-17 at 10 35 51@2x" src="https://user-images.githubusercontent.com/1646307/87798097-92bfc380-c819-11ea-9127-859e47a1a6ba.png">

---

Thanks for looking into this, and let me know if I can help provide more data points.
🙇
