### ISSUE TITLE
Interlinking recordings and analytics

### ISSUE THREAD

**Issue by joethreepwood** [PostHog/posthog#12348]
The Session Recording Team is considering improving the way we link analytics results and session recordings in PostHog, so that it is easier to go from one to another and discover meaningful insights. This is part of work which is documented on [their megaissue](https://github.com/PostHog/product-internal/issues/354). 

We believe this would be valuable because Session Recording is a powerful way to go from a quantitative analysis to a qualitative analysis - e.g. 'I can see how many people did X, now I want to see how they did X'. 

We already surface some Recordings via the PersonsModal but there is so much more we could do to surface relevant recordings and indicate what a user is potentially missing out on by having it disabled.

🗂 **Considered Goals**
- [ ] Find relevant recordings and show at a higher level for other features (Flags, Experiments, Insights, Dashboards)
- [ ] Improve the Recordings modal to explore the related feature better in an easily shareable way
- [ ] Make it friction-less to enable Recordings for the feature area if it is not already

These goals are being considered by [the Session Recording Team](https://posthog.com/handbook/small-teams/session-recording) and we'd love to hear user feedback, as well as ideas for stretch goals or implementation. Please add to this issue!

**If you like this idea, please leave a 👍 or ❤️ reaction on this post to vote for it -- your votes and feedback help us prioritize what to work on next!**

**Comment by azan-n** [comment]
Would this affect #12620?
