### ISSUE TITLE
Session recording playlists

### ISSUE THREAD

**Issue by joethreepwood** [PostHog/posthog#12347]
The Session Recording Team is considering adding playlist functionality to PostHog, as documented on [their megaissue](https://github.com/PostHog/product-internal/issues/354).

It's now easier than ever to find interesting recordings, but it is hard to revisit recordings which you've previously watched. You can bookmark the page, but that's unintuitive. So, we want to enable users to save recordings into playlists. 

Dynamic recordings would automatically add matching recordings to a playlist, especially useful for researching on-going behaviours and issues. 

Static playlists would be manually curated, and especially useful for researching a specific issue from the past. 

🗂 **Considered Goals - Dynamic playlists**
- [ ] Change the current Recordings page to be like the "new insight" view, where you can filter and search around but also have the option to save as a dynamic playlist
- [ ] These should be shareable by url and allow for extra metadata such as a title, description and notes
- [ ] Add tabbed view like other products to see "new recordings", "recent filters", "saved playlists"

🗂 **Considered Goals - Static Playlists**
- [ ] For every recording have a button for adding to a static playlist - can default to a "favorites" playlist with the ability to choose other ones to add it to

These goals are being considered by [the Session Recording Team](https://posthog.com/handbook/small-teams/session-recording) and we'd love to hear user feedback, as well as ideas for stretch goals or implementation. Please add to this issue!

**If you like this idea, please leave a 👍 or ❤️ reaction on this post to vote for it -- your votes and feedback help us prioritize what to work on next!**

**Comment by neilkakkar** [comment]
Calling out because this isn't explicit in either of the two issues (but I guess you've already thought of this):

These playlists imply that the usual recording TTL doesn't hold for recordings in static playlists, i.e. we can only delete them after they're removed from the playlist?

That can get tricky infra wise 😅

**Comment by adrianbinzaru** [comment]
Would be great to have an "auto-play" option as well. This is the only reason why we're still using FullStory for our session recordings now. We've got a big TV in our product room and we've got FullStory just playing on it all day , and we constantly spot times when users are getting stuck or confused - it's super valuable .

**Comment by joethreepwood** [comment]
Hi all! Happy to announce that playlists launched in a recent update. I'm closing this issue as a result, but please do share any feedback you have about session recordings in PostHog via [our Slack channel](posthog.com/slack) or by opening an issue.  Thanks!
