### ISSUE TITLE
Self-hosted SQL access

### ISSUE THREAD

**Issue by joethreepwood** [PostHog/posthog#12352]
To fully support our technical users on self-hosted deployments, we need to allow them to ask any sort of question about their data that might not be fit for an interface. For this reason, we're working on a feature to allow direct SQL access to PostHog data, so that users may query it directly. 

🗂 **Considered goals**
- [ ] Enable direct SQL access to data, through PostHog

[The Experimentation Team](https://posthog.com/handbook/small-teams/experimentation) is currently working on this feature as part of [their quarterly goals](https://posthog.com/handbook/small-teams/experimentation#objective-launch-direct-sql-querying-beta). We'd love to hear user feedback, as well as ideas for stretch goals or implementation.

> Please note we have a separate issue for [SQL access on PostHog Cloud](https://github.com/PostHog/posthog/issues/13128).

**If you like this idea, please leave a 👍 or ❤️ reaction on this post to vote for it -- your votes and feedback help us prioritize what to work on next!**

**Comment by toger5** [comment]
This would be really helpful and immediately provide a lot of value.
(There are already a couple of blockers because of the limited query capabilities)
Feature wise it of course would be very welcome to be able to visualize the result of the sql query on the Posthog Dashboard.
But I guess that Is the plan anyways?

**Comment by toger5** [comment]
Here is the exact sort of issue I am trying to solve:
N participants with clients that send posthog events participate in one event. I want to track this event as one event but right now I have T = N-(not opted in users) events in posthog. I need to join those T events and generate some parameters out of it. 
 - how long was the overall event ( last leave ts - first join ts)
 - how many users participated
...
(there is no server that can track the event its all peer to peer)
(Pls let me know if this is already somehow possible!)

**Comment by joethreepwood** [comment]
I've updated this issue to reflect that we will first focus on SQL access for self-hosted deployments. 

[We've created a separate issue for PostHog Cloud SQL access. ](https://github.com/PostHog/posthog/issues/13128)

**Comment by danielthedifficult** [comment]
Love this idea!

Question: Would you be allowing only SELECT-style statements, or modification/deletion of data as well?

I recently had an issue where I had to connect directly to the ClickHouse db and make some modifications to historical data that got ingested improperly. I would have loved to do this using a 'first party' solution.
