### ISSUE TITLE
Insights with a group by sometimes resulting in a NaN

### ISSUE THREAD

**Issue by lharries** [PostHog/posthog#12354]
## Bug description

When doing an insight and grouping by more than a day it sometimes results in a NaN showing in either the table below or when hovering over the insight

## How to reproduce

You can see it at this insight: https://app.posthog.com/insights/iULRRRFR

<img width="586" alt="Screenshot feature flag updated unique users   feature flag created unique users by person's clearbit__person__employment__role • Insights • PostHog (Google Chrome) 2022-10-19 at 14 28@2x" src="https://user-images.githubusercontent.com/22766134/196774536-c40f1fee-d672-4bae-a4af-3ac8e8772317.png">

## Environment

- [x] PostHog Cloud
- [ ] self-hosted PostHog, version/commit: please provide

cc @PostHog/team-product-analytics

**Comment by lharries** [comment]
These are likely the same problem: https://github.com/PostHog/posthog/issues/8101 https://github.com/PostHog/posthog/issues/11076

**Comment by andyvan-ph** [comment]
Adding to this issue as I think I'm experiencing a similar problem and can add something additional insight.

All examples below are from [this insight](https://app.posthog.com/insights/0iTHPtsx) – look at how the numbers for the week commencing October 16 fluctuate as the date range changes...

**1. Date range = Year to date:** Oct 16 is around 1,100, which is about where I'd expect it to be.

![Screenshot 2022-10-24 at 11 55 37](https://user-images.githubusercontent.com/92976667/197510850-835cec1f-0523-400e-af72-2e99d88f02b6.png)

2. **Date range = Last 180 days:** Oct 16 now reads less than 600

![Screenshot 2022-10-24 at 11 57 48](https://user-images.githubusercontent.com/92976667/197511175-1223a5bd-1125-4f35-bbc2-a0866b6c6a79.png)

3. **Date range = Last 90 days:** Oct 16 is now below 1,000 still, but below where it "should be"

![Screenshot 2022-10-24 at 12 00 25](https://user-images.githubusercontent.com/92976667/197511487-24172997-98d5-4e5e-85fa-bdffb8ea83c4.png)

4. **Date range = Last 30 days:** Oct 16 is now between 800 and 600

![Screenshot 2022-10-24 at 12 01 17](https://user-images.githubusercontent.com/92976667/197511677-b4836a4e-ec76-4c7c-a84b-bf4bdf2bc3af.png)

**Comment by lharries** [comment]
@Twixes I think this is still happening? https://posthogusers.slack.com/archives/C01GLBKHKQT/p1667387637207009 + I saw it recently too

**Comment by Twixes** [comment]
Hmm, I see, though _those_ NaNs are caused by a different problem. I'll take a look at the issue that user seeing.

**Comment by lharries** [comment]
Another example of a NaN: https://posthogusers.slack.com/archives/C01GLBKHKQT/p1667387637207009
