### ISSUE TITLE
ability to alias a historical field name for use in insight breakdowns

### ISSUE THREAD

**Issue by lsmith77** [PostHog/posthog#12365]
## Is your feature request related to a problem?

We have a historical field name and we would like to be able to use either the new or old field name inside an insight breakdown.

## Describe the solution you'd like

Ability to alias fields in the data management.

## Describe alternatives you've considered

Ability to use a COALESCE like function in breakdowns.

## Additional context

https://posthogusers.slack.com/archives/C01GLBKHKQT/p1666268082823329

**Comment by lsmith77** [comment]
Ability to use funtions on breakdown fields would obviously be the more generic solution and would f.e. also allow stripping off a language prefix from a path like `/en/foo/bar` vs. `/de/foo/bar`

https://posthogusers.slack.com/archives/C01GLBKHKQT/p1667209739721439

<img width="187" alt="image" src="https://user-images.githubusercontent.com/300279/202181728-742e2f0f-4ec2-464f-b4e5-719e6e62ba63.png">

**Comment by lsmith77** [comment]
@tiina303 should the ability to apply functions for the `/en/foo/bar` vs. `/de/foo/bar` case be a separate ticket?

**Comment by tiina303** [comment]
it's useful to have it in this ticket

**Comment by lsmith77** [comment]
Seems like this is now supported https://posthog.com/changelog/2023#breakdowns-now-editable-with-hogql

`coalesce(properties.some_properties, properties.some_renamed_property)`
