### ISSUE TITLE
See Users & Recordings linked to feature flags

### ISSUE THREAD

**Issue by joethreepwood** [PostHog/posthog#12360]
The Experimentation Team is currently considering working on two issues related to feature flags, so that those who use feature flags can more easily get information on the users attached to a particular feature flag, and gather more information on those users' experience.

🗂  **Considered goals**
- [ ] Provide a way to list users who are exposed to a flag and provide a way to quickly create cohorts around such users
- [ ] Provide a way to see session recordings related to a feature flag

These goals are being considered by [the Experimentation Team](https://posthog.com/handbook/small-teams/experimentation) and we'd love to hear user feedback, as well as ideas for stretch goals or implementation. Please add to this issue!

**If you like this idea, please leave a 👍 or ❤️ reaction on this post to vote for it -- your votes and feedback help us prioritize what to work on next!**

**Comment by bjarnewilhelm** [comment]
https://github.com/PostHog/posthog/issues/2764#issuecomment-1316816660
