### ISSUE TITLE
Insights not recognizing action deletion

### ISSUE THREAD

**Issue by ungless** [PostHog/posthog#1236]
### Bug description
After deleting an action, if it is part of a funnel it will remain in the funnel configuration.
When editing a funnel subsequently, frontend rendering breaks when trying to modify the (deleted) action.

### How to reproduce

1. Create a funnel with actions A and B
2. Delete action A from the Actions page
3. Return to the funnel and try to modify action A.

### Expected behavior
IMO the action should be removed from the funnel's list of actions.
Also given that we're storing deleted actions anyway, a list of "deleted" actions might be a good idea so users can restore previously deleted actions.

### Screenshots
Before action is deleted.
![image](https://user-images.githubusercontent.com/8397061/87776238-5db66f80-c81f-11ea-9195-3380a2a7a35b.png)

After action is deleted (remains in list)
![image](https://user-images.githubusercontent.com/8397061/87776254-6149f680-c81f-11ea-8c18-6834f7dabbe7.png)

Clicking on it leads to blank page.

### Environment

- PostHog cloud or self-managed? self-managed
- PostHog version/commit latest

**Comment by Twixes** [comment]
This is actually still a thing

**Comment by paolodamico** [comment]
Plus it also affects all insights. An idea is to show the number of insights/dashboards that use an action in the action page so you have context before deleting.
