### ISSUE TITLE
Change order of funnel steps simply

### ISSUE THREAD

**Issue by MaxTheMonster** [PostHog/posthog#1237]
### Is your feature request related to a problem? Please describe
Once actions/steps are added to the funnel, their order can't be changed.

### Describe the solution you'd like
Drag the actions to change the order.

### Describe alternatives you've considered
To change the order it's also possible to change the selected actions or deleted subsequent actions.

Alternatively maybe it's just obvious when making the funnel to make the step order logical, but I feel this feature should still exist to save some headache.

**Comment by EDsCODE** [comment]
~@mariusandra @timgl to add a package or to not add a package? https://github.com/react-dnd/react-dnd/~ can use react-grid-layout

**Comment by EDsCODE** [comment]
closing and refer back to #936
