### ISSUE TITLE
Github App not updating properly

### ISSUE THREAD

**Issue by lharries** [PostHog/posthog#12373]
## Bug description

I've added updates to the Posthog feedback app which haven't been propagated, however the app says it's up to date. This is important to fix the CSS of the Feedback widget app https://github.com/PostHog/feedback-app/issues/6

## How to reproduce

1. I added the console log `console.log('Posthog - latest feedback widget')` to the inject script of the app (code [here](https://github.com/PostHog/feedback-app/blob/main/site.ts))
2. I click "Check app for updates" next to "Apps to update" on the "Apps" page
3. I click "Update" next to the "Feedback widget"
4. I refresh the page
5. The console log line won't run

## Environment

- [x] PostHog Cloud
- [ ] self-hosted PostHog, version/commit: please provide

## Additional context

Marius was doing additional work to improve apps however he's not sure why the apps are not updating properly

**Comment by mariusandra** [comment]
Confirmed that it's a bug I've been experiencing as well, especially on cloud. Locally most apps tended to reach "eventual consistency". Talked briefly with @yakkomajuri and he thinks it might have something to do with how we split plugin servers now based on capability (e.g. separate instances that run scheduled tasks), but I haven't had the chance to dig further.
