### ISSUE TITLE
Sort is not working correctly : Data management  >Events > 30 days volume 

### ISSUE THREAD

**Issue by o1lab** [PostHog/posthog#12391]
## How to reproduce

1. Go to `Data Management`
2. `Events` tab
3.  Click `30 day volume` to sort in descending order.

Observe that sort is only limited to paginated information (50 events) and not the entire set of events in 30-day volume.

The right behaviour is to sort all events by descending. And reload the table!

**Comment by haseebnaseem** [comment]
Is this up for grabs ? Would like to contribute.

**Comment by ksgokul2501** [comment]
This should be closed

**Comment by Twixes** [comment]
Yes, this has since been fixed.
