### ISSUE TITLE
Prevent accidental rollout of feature flags

### ISSUE THREAD

**Issue by lharries** [PostHog/posthog#12410]
Two problems we've identified:
1. If the cohort is blank it will default to 100% rollout
2. As shown below, if the email is blank it will default to 100% rollout

![Image](https://user-images.githubusercontent.com/22766134/197618549-8f2381d1-f5f8-442d-88b5-a9c104ff714a.png)

Slightly unrelated but I think we should calculate before what % and number of their users fit the conditions. Could ask them to confirm this on each change?

**Comment by liyiy** [comment]
> I think we should calculate before what % and number of their users fit the conditions.

Do you mean display something that shows more details about their users selection?

> Could ask them to confirm this on each change?

That seems a bit burdensome on each change, maybe if they leave the value empty (unintended action), just prevent feature flag save until they either intentionally delete that filter or enter a value?

**Comment by neilkakkar** [comment]
Oh, interesting, love the idea of showing how many users this would impact. Not the most straightforward, since we really want this to be quick, but should be doable 👀

**Comment by neilkakkar** [comment]
Fixed by #13719
