### ISSUE TITLE
improve UX for range selector

### ISSUE THREAD

**Issue by lsmith77** [PostHog/posthog#12421]
## Is your feature request related to a problem?

When selecting a range (f.e. when doing a historical export with the Replicator plugin) it is not clear to the user that it is indeed a range and not a starting point. Also when selecting a range over several months it is error prone.

<img width="456" alt="image" src="https://user-images.githubusercontent.com/300279/197766845-5ff48d4b-ddf2-4548-b6db-598b9aa661b3.png">

## Describe the solution you'd like

Show the start and end point selected above the calendar so that it remains visible even when clicking through different months. Also show that both a start *AND* end date are needed.

Potentially also confirm the selection.

Also offer a way to quickly select a year.

## Additional context

https://posthogusers.slack.com/archives/C01GLBKHKQT/p1666698696136699?thread_ts=1665753325.224729&cid=C01GLBKHKQT

**Comment by caxco93** [comment]
It seems that #12765 has indeed closed this issue. Should we go ahead and close as completed? @thmsobrmlr
