### ISSUE TITLE
Ensure we are including all events in org reports

### ISSUE THREAD

**Issue by benjackwhite** [PostHog/posthog#12447]
## Bug description

@tiina303 mentioned that some counts may be missed based on the range querying we are doing for usage_reports.

We should validate this and update the queries to be fully inclusive of the intended range

## Environment

- [x] PostHog Cloud
- [ ] self-hosted PostHog, version/commit: please provide

**Comment by tiina303** [comment]
context from 9 months ago https://posthog.slack.com/archives/C02E3BKC78F/p1642536981065600?thread_ts=1642525180.064100&cid=C02E3BKC78F
