### ISSUE TITLE
Missing app logo

### ISSUE THREAD

**Issue by joethreepwood** [PostHog/posthog#12468]
## Bug description

The Laudspeaker app has a logo in it's repo, but no app in the product. 
 
<img width="960" alt="Screenshot 2022-10-27 at 11 27 07" src="https://user-images.githubusercontent.com/84011561/198261038-1413c224-6ab5-4ade-ac6c-3b03bb40a5e3.png">

Tagging @kappa90 as I believe he added this app in.

## How to reproduce

1.
2.
3.

## Environment

- [ ] PostHog Cloud
- [ ] self-hosted PostHog, version/commit: please provide

**Comment by abheek9** [comment]
Happy to provide a logo, here do you need svg/png? what dimensions?

**Comment by kappa90** [comment]
The logo seems to be there, not sure why it's not picked up. Any idea @yakkomajuri?

**Comment by mariusandra** [comment]
Logos only work on the `main` branch. This one uses `master`

🤙

**Comment by kappa90** [comment]
Crazy, opened a `main` branch and that fixed it
