### ISSUE TITLE
Not sure where to put annotations

### ISSUE THREAD

**Issue by jamesefhawkins** [PostHog/posthog#1247]
### Is your feature request related to a problem? Please describe

As a user: 

I recently merged a new homepage for posthog.com, and I wanted to note that this is quite a significant change that could affect conversion rates, using our annotations feature.

However, I didn't have a pre-made dashboard that felt appropriate to tag this onto

I also wasn't sure if this annotation would be visible on other dashboards we make in future that are also going to be affected by this change.

### Describe the solution you'd like

An annotations log page, where you can CRUD new annotations.

### Describe alternatives you've considered

Create a homepage visits trends page, save to a dashboard and tag appropriately.

**Comment by EDsCODE** [comment]
I agree. I took this out of scope of the other PRs but definitely shouldve logged this add on
