### ISSUE TITLE
Stripe-js seems to block PostHog

### ISSUE THREAD

**Issue by timgl** [PostHog/posthog#1249]
### Bug description

I had a client with stripe-js on a couple of pages. On those pages PostHog errored.

### How to reproduce

1. Install stripe-js checkout forms
2. Install posthog
3. See error message

### Expected behavior

It should still work

### Environment

- PostHog cloud or self-managed?
- PostHog version/commit

**Comment by Twixes** [comment]
For posterity, I tried reproducing this with [Twixes/posthog-stripe-test](https://github.com/Twixes/posthog-stripe-test) and saw no errors. More data needed to verify that the problem wasn't just a fluke.

**Comment by Twixes** [comment]
Looks like just a fluke.
