### ISSUE TITLE
Cant create a person

### ISSUE THREAD

**Issue by ddimitrioglo** [PostHog/posthog#12507]
## Bug description

Can't create a person via API

```
Request: 

curl -H 'Content-Type: application/json'  -H "Authorization: Bearer xxx" \
    https://app.posthog.com/api/projects/888/persons/ \
	-d '{"name":"My name"}'
	
Response: 
{“type”:“server_error”,“code”:“error”,“detail”:“A server error occurred.“,”attr”:null} 

```

## Environment

- [x] PostHog Cloud (US)

**Comment by timgl** [comment]
Hm I think we need to be clearer in the docs that you shouldn't use the API for this. The best way of 'creating users' is to use the identify functions in any of our libraries: https://posthog.com/docs/integrate/identifying-users

**Comment by ddimitrioglo** [comment]
what exactly `posthog.identify('my_user_12345')` calls so we can call that directly?

**Comment by timgl** [comment]
https://posthog.com/docs/api/post-only-endpoints#single-event
the event is `$identify`, then you want to do something like
```
"properties": {
  "$set": { "prop1": "val1"}
}
```
