### ISSUE TITLE
503 error "Error from cloudfront" on PostHog CLOUD when sending events

### ISSUE THREAD

**Issue by DNA-PC** [PostHog/posthog#12517]
## Bug description

PostHog doesn't receive any events anymore, since this morning.
I noticed the issue about 2h ago, thought it was my setup, but can replicate the issue on all our apps, across multiple accounts.

## How to reproduce

![image](https://user-images.githubusercontent.com/107790761/198877218-f0ea7469-167c-4819-a97e-1cebf3b42c0e.png)

## Environment

- [x] PostHog Cloud

## Additional context

All our snippet code integration are broken and showing the same error.

**Comment by DNA-PC** [comment]
Note that we use the EU cloud.

**Comment by DNA-PC** [comment]
The US cloud doesn't seem affected
![image](https://user-images.githubusercontent.com/107790761/198877327-be88a6b6-d298-4ad3-afc4-b0c72cbe1c93.png)

**Comment by ellie** [comment]
Hey! Thank you for reporting this 🙏 

Unfortunately we had an outage yesterday, which would have caused the 503 you saw here! The issue was resolved shortly afterwards, and we have improved our monitoring so that the same issue doesn't happen again in the future.
