### ISSUE TITLE
Automatically increase the date range if interval is changed

### ISSUE THREAD

**Issue by timgl** [PostHog/posthog#1251]
### Is your feature request related to a problem? Please describe

When I change the interval from daily to weekly but the date range is 'last 7 days' it'll only show me one datapoint. Each time I have to change the date range manually. This should be automatic.

### Describe the solution you'd like

If the date range hasn't manually been changed yet, automatically increase the date range to an appropriate one:
Minute -> Today
Hourly -> Today
Daily -> Don't do anything!
Weekly -> Last 30 days
Monthly -> Last 90 days

### Describe alternatives you've considered

Manually change the date range

**Comment by samcaspus** [comment]
I think I have a solution for this will make a pull request soon :smile:
