### ISSUE TITLE
UTM_ properties should always be detected as a string

### ISSUE THREAD

**Issue by pauldambra** [PostHog/posthog#12529]
## Bug description

NOTE: this issue is complete, aside from `And fix any detected as not strings.`

See this community slack thread: https://posthogusers.slack.com/archives/C01GLBKHKQT/p1666985093165389

If the first value sent as e.g. `utm_content` is `utm_content=21546` then we will detect utm_content as a number.

This causes at least one bug. https://github.com/PostHog/posthog/issues/12513 

We should detect all `utm_$foo` properties as strings. And fix any detected as not strings.

On cloud about 5% of instances of utm_x have been detected as numeric

## Environment

- [X] PostHog Cloud
- [X] self-hosted PostHog, version/commit: please provide

**Comment by hazzadous** [comment]
Leaving this open to resolve the historical misinterpretations
