### ISSUE TITLE
Y-axis unit blocks screen

### ISSUE THREAD

**Issue by timgl** [PostHog/posthog#12539]
## Bug description

Sometimes the Y-axis randomly opens for me and then blocks the screen which is super frustrating. The y-axis dropdown is the only one that does this.
<img width="1144" alt="image" src="https://user-images.githubusercontent.com/1727427/199070208-9efe4f86-6818-4712-99ec-2eeada7eee4d.png">

## How to reproduce

1. Click on the y-axis
2. Try exiting it by clicking anywhere else on the screen
3. Get a `confirm()` box which blocks everything.
4. One way of getting out of this is pressing the escape key. Weirdly, if you press the escape key again the box opens again. Feels like a listener gone rogue.

## Environment

- [ ] PostHog Cloud
- [ ] self-hosted PostHog, version/commit: please provide

## Additional context
@Twixes

**Comment by pauldambra** [comment]
fixed in #12536
