### ISSUE TITLE
Joining Linode's One-Click marketplace

### ISSUE THREAD

**Issue by ungless** [PostHog/posthog#1254]
- [x] Write Linode StackScript (auto-deploy script) for PostHog. (https://github.com/PostHog/deployment/pull/11)

- [x] Request to become a Linode partner at https://www.linode.com/marketplace/app-partners/

- [ ] Prepare assets according to https://github.com/linode/Marketplace-Apps

- [ ] Get partnership approved by Linode.

- [ ] Submit assets to Linode for approval 

- [ ] Write documentation for one-click Linode deployment

- [ ] Test it!

**Comment by wundo** [comment]
Hi @MaxTheMonster I think this is in the wrong repo :)

**Comment by ungless** [comment]
@wundo we have other similar tasks in this repo. (cf. https://github.com/PostHog/posthog/issues/905) so that we can organise them into a shared roadmap, rather than keeping this in `/deployment`, which is I think what you were wondering. :+1:

**Comment by yakkomajuri** [comment]
I'm quite sure this is done. https://posthog.com/docs/deployment/deploy-linode

**Comment by Twixes** [comment]
Linode deployment is described, but unfortunately [we aren't on Linode Marketplace just yet](https://www.linode.com/marketplace/search/?appq=posthog).

**Comment by Twixes** [comment]
As we're keeping the number of deployments steady, we won't be doing Linode Marketplace.

**Comment by yakkomajuri** [comment]
Should we get rid of Linode altogether? Docs + StackScript on PostHog/deployment?

**Comment by timgl** [comment]
Yes for sure.
