### ISSUE TITLE
Migrate tool dashboards/insights/cohorts/actions etc

### ISSUE THREAD

**Issue by timgl** [PostHog/posthog#12550]
I'm planning on writing a migration tool that people can run themselves to migrate 'metadata' from one posthog account to another

Stuff we'll migrate, in this order
- All projects (including key?)
- Insights
- Dashboards
- Feature flags
- Experiments
- Actions
- Cohorts (except static cohorts?)
- Annotations

Stuff we won't migrate
- Events/properties. This means customers will first need to run the migrator 3000
- User, as we can't create those easily via the API. Customers will need to get people to sign up before running this, otherwise the owners for everything will be the first user.

The tool should probably save "state" so we can re-run without duplicating.

FYI I'm actively working on this right now

**Comment by pauldambra** [comment]
Could this overlap with https://github.com/PostHog/posthog/issues/11638 and allow copying between projects 🤔

**Comment by pauldambra** [comment]
To throw more scope into the bag... if "saving state" could save to a text file then folk could diff/version control their config

**Comment by pauldambra** [comment]
e.g. https://posthogusers.slack.com/archives/C01GLBKHKQT/p1667396105426119?thread_ts=1667299467.068709&cid=C01GLBKHKQT

**Comment by timgl** [comment]
> Could this overlap with https://github.com/PostHog/posthog/issues/11638 and allow copying between projects 🤔

Yep should be relatively easy to add this functionality to the script, though won't be native in the app

> To throw more scope into the bag... if "saving state" could save to a text file then folk could diff/version control their config

This could be a terraform module I guess? Definitely a different problem with a different solution than this I think
