### ISSUE TITLE
Developing locally url down

### ISSUE THREAD

**Issue by gabinwilliams** [PostHog/posthog#12561]
## Bug description

When hitting https://posthog.com/docs/contribute/developing-locally the user gets stuck in a redirect loop.

## How to reproduce

1. Visit the URL in a browser.

## Environment

N/A

## Additional context
The URL has been down for around 3 days with the same redirect loop problem.

**Comment by gabinwilliams** [comment]
@timgl  Think you can have someone look into this?  I'm super excited to start investing time on some issues, but need the docs to get posthog running locally first!

**Comment by fuziontech** [comment]
Hey @gabinwilliams! Sorry about the broken link here. I'll fix it in just a second. In the mean time you can find the docs you are looking for here:
https://posthog.com/handbook/engineering/developing-locally

**Comment by fuziontech** [comment]
ah something else to note here the original URL you were looking for was off by just a bit:
It is:
https://posthog.com/docs/contributing/developing-locally
not:
https://posthog.com/docs/contribute/developing-locally

**Comment by fuziontech** [comment]
Closing this out for now. Let me know if you see any other broken links 💔

**Comment by gabinwilliams** [comment]
Thanks so much @fuziontech  I really appreciate it!
