### ISSUE TITLE
Heroku deploy issue

### ISSUE THREAD

**Issue by jamesefhawkins** [PostHog/posthog#126]
**Describe the bug**
On deploying on Heroku, I can login, but then it goes to a blank screen.

**To Reproduce**
1. Deploy to Heroku 
2. Create an account
3. Sign in -> a blank page appears

**Screenshots**

<img width="1657" alt="Screenshot 2020-02-18 at 22 18 14" src="https://user-images.githubusercontent.com/47497682/74807381-2c9c3800-529d-11ea-8933-3d12ca1a07b3.png">

**Desktop (please complete the following information):**
 - Browser: Chrome/Safari

**Comment by timgl** [comment]
This was fixed.
