### ISSUE TITLE
changing distinct ID

### ISSUE THREAD

**Issue by lsmith77** [PostHog/posthog#12600]
### Status Quo
We are using Posthog to collect analytics on our dashboard (i.e. where customers configure their personal profile, manager their teams, view their analytics etc.) using the Posthog JavaScript integration. Login is required here, so we use the "dashboard ID" as the distinct ID.

We are also using Posthog in our browser extension (our core product, i.e. the dashboard is the complement to our browser extension). There we currently are generating our own "browser ID" which we use as the distinct ID. This was done as a privacy measure, since we do not associate the "dashboard ID" to customers, i.e. we could therefore not by default relate the engagement collected within the browser extension to any specific customer.

We do associate events from the browser extension to a specific team ID (i.e. a Posthog group ID), so that we can do team level analytics.

### Introducing personal / team analytics

Now we want to start showing customers their personal and team engagement analytics on the dashboard. For this we wanted to have the flexibility to choose if we make these opt-in or opt-out features. That is we in general want the flexibility for customers to say "I don't want personal analytics, but I do want team analytics" or any permutations of these preferences.

For team analytics that seems easy enough to do, we just do not associate the events with the team if customers chooses that they don't want to be included in the team analytics.

For the personal analytics it gets trickier. My initial idea was just to use `alias` to alias the "browser ID" to the "dashboard ID" if customers choose to opt into personal analytics. But from my reading of the [ingestion pipeline](https://posthog.com/docs/how-posthog-works/ingestion-pipeline), aliasing should be used as a one time thing and not a continuous process, where events would be sent to one person but associated with another person via an alias.

So it seems to me like when a user opts into personal analytics we would in that moment alias their "browser ID" with their "dashboard ID" and from then on the browser extension will use the "dashboard ID" for all events. This would then be non-reversable.

### Migration plan

Now in parallel we want to migrate from US to EU hosting. Also we have learned a lot about Posthog in the last 12 months and our events have gone through some iterations. There is this urge in me to start fresh that might be misguided.

So if we do start fresh, we could use the replicator to replicate all events to our old US posthog based instance for 3-6 months, so that we still maintain a longer window into our retention charts. Does that make sense?

However the bigger concern is that for those customers that did choose to opt-in to personal analytics, we do not want to cause havoc on our retention charts. If we do manage to implement the `alias` from "browser ID" to "dashboard ID", then I guess those charts should be fine, right? But if we don't alias, then I guess it would look like new users appearing while old users seemingly stopped even if they didn't, correct?

## Describe the solution you'd like

Advice on the following questions:
* If our understanding of aliasing is correct, ie. it should not be doine continously and rather as a one time way to merge persons.
* Does starting fresh make sense or should we rather adopt a mindset of living with messy event data (related to this would be amazing to have some way to [alias property and/or have a COALESCE function](https://github.com/PostHog/posthog/issues/12365) useable in different places, especially breakdowns)
* If we do migrate the data immediately from US to EU (ie. moving our old data), do these replicated events get charged like normal events? ie. if we move 20M events, do we have to pay for 20M events?

## Additional context

* https://posthogusers.slack.com/archives/C01GLBKHKQT/p1665481284734419
* https://posthogusers.slack.com/archives/C01GLBKHKQT/p1667473817149419
* https://posthogusers.slack.com/archives/C01GLBKHKQT/p1665481287162159

**Comment by tiina303** [comment]
Hi,

> If we do migrate the data immediately from US to EU (ie. moving our old data), do these replicated events get charged like normal events? ie. if we move 20M events, do we have to pay for 20M events?

All events that are historical +1 month old currently aren't billed, anything in this month would be billed.

More context from slack:
> ok so a browser ID is like a (anonymous)  session ID and dashboard ID is like a logged in user ID
>  a user has 1 "dashboard ID" and one or many "browser IDs"
> browser ID is more like a device ID

Based on this I would say you want to identify/alias the browser ID to dashboard ID (and that should be done once). You're correct that this applies to events after the merge. You can stop aliasing and use split IDs to reverse this, but again would apply to events afterwards.

> Does starting fresh make sense or should we rather adopt a mindset of living with messy event data (related to this would be amazing to have some way to https://github.com/PostHog/posthog/issues/12365 useable in different places, especially breakdowns)

In what sense is your current data messy? You can split IDs or use alias calls to fix it up?

**Comment by lsmith77** [comment]
@tiina303 regarding the messy .. f.e. we have renamed some properties which can lead to weird situations when we use breakdowns, because the value would then be `null` on some historical data. then again, I guess we would then just need to filter (we do have a version property in every event that could be used for this purpose).

**Comment by tiina303** [comment]
It's hard for me to advise here without having the full context, when you're migrating to another instance you could export the data out, manipulate it and send it to PostHog. I suspect it's not worth the effort though over just simply using Replicator plugin to migrate directly.

**Comment by lsmith77** [comment]
yeah .. thank you.

**Comment by lsmith77** [comment]
@tiina303 sorry got another question.

so our plan is to:
* setup the replicator to send events from the US to the EU instance
* release a new version of our browser extension
  * this will then send data directly to the EU instance (instead of the US instance) using the `dashboard ID` (instead of than the `browser ID`)
  * alias the `browser ID` to the `dashboard ID` on the EU instance once

The main motivation for the replicating the events and aliasing would be our retention charts. So my question is: does aliasing with the above approach ensure that our retention charts do not suddenly see users with the `browser ID` drop off once they get aliased because old events will not be re-written?

**Comment by tiina303** [comment]
> So my question is: does aliasing with the above approach ensure that our retention charts do not suddenly see users with the browser ID drop off once they get aliased because old events will not be re-written?

If you do the alias first and you merge the `dashboardID` into `browserID` (`alias(browserID, dashboardID)`), then the events will be tied to the same user, because this will make dashboard ID use the person_id that browserId has been using. This assumes that `dashboardID` person currently either doesn't exist or hasn't been merged with anyone yet.

**Comment by lsmith77** [comment]
@tiina303 

> You can stop aliasing and use split IDs to reverse this, but again would apply to events afterwards.

what is the API call for this?

could not find anything my browsing nor by searching for `split`

<img width="733" alt="image" src="https://user-images.githubusercontent.com/300279/202183486-7a32c572-8fed-42eb-ac68-6a9a92994e3e.png">

**Comment by tiina303** [comment]
Split IDs you can see the button right corner of the persons page. I recommend using the button there or you can check what call we make from there. The API is https://posthog.com/docs/api/persons#post-api-projects-project_id-persons-id-split
