### ISSUE TITLE
Feature Request: Filter session recordings of internal users

### ISSUE THREAD

**Issue by joethreepwood** [PostHog/posthog#12620]
## Is your feature request related to a problem?

We can filter all internal and test users out of insights with a simple button press. 

<img width="560" alt="Screenshot 2022-11-03 at 21 07 30" src="https://user-images.githubusercontent.com/84011561/199834347-dcb346d7-095b-403f-9af3-7d85f52782dc.png">

But to do this with session recordings? You need to create a manual filter. 

<img width="371" alt="Screenshot 2022-11-03 at 21 05 35" src="https://user-images.githubusercontent.com/84011561/199834309-e600d279-7585-4395-b7f5-092f50da0358.png">

## Describe the solution you'd like

Duplicate the insight internal user filter into session recordings, so I don't need to keep watching what my colleagues have been doing in PostHog all day. 

## Describe alternatives you've considered

Some sort of saved, automatic cohort? 

## Additional context

Discovered while working on a new session recording tutorial for a hackathon project. Because apparently it's a black hole in our tutorial coverage.

**Comment by dongumayagay** [comment]
is there an update regarding this feature request? i stumble upon many question in community regarding this

**Comment by daibhin** [comment]
Hey @dongumayagay, we're planning some work to improve the filtering of session replays next week. We hope to include some changes that will help with this

**Comment by dongumayagay** [comment]
@daibhin happy to hear that. this is indeed is a much needed feature and i hope this will be included

**Comment by daibhin** [comment]
This has been rolled out thanks to @pauldambra in https://github.com/PostHog/posthog/pull/16723
