### ISSUE TITLE
Missing upsell prompt for dashboard text cards

### ISSUE THREAD

**Issue by Twixes** [PostHog/posthog#12645]
## Bug description

I was super confused why I can't add text cards to a dashboard locally… turns out that's a paid feature, which is not communicated in the product, and I happened not to have a license. This is suboptimal in two cases:
1. User is not aware we've built text cards – it's very unlikely they'll learn about this feature
2. User is aware we've built text cards, but for some reason doesn't currently have a subscription – they'll be confused why the feature's suddenly gone with the wind (like me)

**Comment by pauldambra** [comment]
quick run at this #12729
