### ISSUE TITLE
 check alias usage 

### ISSUE THREAD

**Issue by navi86** [PostHog/posthog#12651]
## Problem description
I am trying to upgrade to new version of posthog 1.41.
Documentations shows
https://posthog.com/blog/the-posthog-array-1-41-0#1410-update-guide-for-selfhosted-users
that I need to check alias usage before upgrade, however there is no information how I can do it. Can you provide information how is it possible to do ? 

P.S. looks like new version of posthog has this feature https://github.com/PostHog/posthog/pull/12255, but how to do it before upgrade ?

## Environment
- [x ] self-hosted PostHog, version/commit: 1.40.0, self-hosted

**Comment by hazzadous** [comment]
I'm not completely au fait with the alias changes, but does the link from that array post help at all: https://posthog.com/docs/integrate/identifying-users#considerations ?

**Comment by navi86** [comment]
@hazzadous 
thanks for the link, this link actually I saw, however, there are only information about what will happen:
```
If we encounter an $identify or $create_alias event with one of the above problems, the following will happen:

- We process the event normally (it will be ingested and show up in the UI)
- We refuse to merge users and an ingestion warning will be logged (see [ingestion warnings](https://posthog.com/manual/data-management#ingestion-warnings) for more details).
- The event will be only be tied to user behind the first passed distinct_id

```
how can I understand that do I have such issue or not ?

**Comment by hazzadous** [comment]
@navi86 I've asked someone that knows about these things in a little more depth than I do, hopefully they will put up their thoughts, otherwise I'll look through the literature and figure out what's going on.

**Comment by tiina303** [comment]
Unfortunately you can't check ingestion warnings before upgrading. Here's what you can do:
1. if you're not making `alias` calls you're good to upgrade
2. if you're making alias calls, then check which order you're providing the arguments, it should be `alias(user-id, anon-session-id)`. You can look at the alias events also in the app and make sure that the `distinct_id` is the user-id you're using for identified users and `alias` looks like an anonymous session id.

After you upgrade I'd recommend checking ingestion warnings to make sure everything was addressed properly, if not you can consider downgrading if fixing the alias usage would require more time.

**Comment by klamas1** [comment]
How can I downgrade if I have already done 0007_persons_and_groups_on_events_backfill ?

**Comment by tiina303** [comment]
> How can I downgrade if I have already done 0007_persons_and_groups_on_events_backfill ?

It's fine to downgrade to 1.40.1 if that migration is completed. To downgrade: specify the posthog app version in your chart / hobby: https://github.com/PostHog/charts-clickhouse/blob/main/charts/posthog/values.yaml#L17 in this case you'd want to set it to `release-1.40.1` & run helm upgrade
