### ISSUE TITLE
visualize difference between string values and null/None

### ISSUE THREAD

**Issue by lsmith77** [PostHog/posthog#12669]
## Is your feature request related to a problem?

F.e in this breakdown insight there is no way to differentiate visually if `None` and `null` are strings or if they represent the value is missing or set to javscript null

<img width="157" alt="image" src="https://user-images.githubusercontent.com/300279/200519509-38583b20-ac76-4ce6-bb10-98ef7a5cd79a.png">

## Describe the solution you'd like

Use a different color and bold/underline for non string values

## Describe alternatives you've considered

Some hover effect that clarifies if the value is a string or nit

**Comment by lsmith77** [comment]
BTW also it would be nice to be in a position to fold `null` and `None` into one value inside breakdowns, but this relates a bit to [this](https://github.com/PostHog/posthog/issues/12365) existing issue

**Comment by smartdev09** [comment]
@lsmith77 can i work on this issue?

**Comment by lsmith77** [comment]
> @lsmith77 can i work on this issue?

absolutely!

**Comment by smartdev09** [comment]
Thank you

**Comment by Narcos101** [comment]
Hey @UsmanDev09 are you still working on this issue?

**Comment by psavan1655** [comment]
Hey @hazzadous I see no one is actively working on this issue. So i would like to work on this issue. As it is a simple one to start contributing with PostHog.
Thanks

**Comment by mariusandra** [comment]
The reason this issue wasn't done is because it's not that simple.  It'll be fixed once we roll out HogQL and the new Event Explorer.

https://github.com/PostHog/posthog/pull/15244
https://github.com/PostHog/posthog/pull/15519

**Comment by hazzadous** [comment]
Ah sorry @psavan1655 I missed the mention. Thanks for picking up the slack @mariusandra ❤️
