### ISSUE TITLE
Deep linking recordings into projects

### ISSUE THREAD

**Issue by fuziontech** [PostHog/posthog#12662]
# Problem 

Some organizations have many more than one **project**  that they have configured inside of Posthog. This means that things break when someone links a recording and the user's last project selected is something other than the project that belongs to the linked recording.

This can happen in a few cases:
- User A wants to share a recording with User B
- User A is looking at sentry and sees an exception with a linked recording, but is in the wrong project
- User A gets bugged about an issue in slack with no other context and tries to view the recording and has to hunt which project it belongs to.

We have deep linking for Insights and Dashboards, why not recordings too since those seem to have a really great story of integrations with products like Sentry?

(Feedback was collected from a paying User here in SF)

**Comment by lharries** [comment]
@fuziontech I think this issue occurs for several parts of Posthog (Session Recordings, Feature Flags, Apps etc.).

Could we have the project name always being in the URL? e.g.
- `https://app.posthog.com/feature_flags/4970` -> `https://app.posthog.com/production-project/feature_flags/4970` (my preference as it's more readable)

Alternatively we could use this project ID but this would be less readable

**Comment by lharries** [comment]
@benjackwhite would be great to consider this for your work on sharing recordings - ideally with a solution that also works for features flags + apps such as my suggestion above

**Comment by benjackwhite** [comment]
Yeah this isn't really Recordings related but rather a PostHog wide problem. I think we could tackle it but it would require a bit of a cross-team effort I think

**Comment by timgl** [comment]
We already support this for feature flags, dashboards etc with this auto switching: https://github.com/PostHog/posthog/blob/master/posthog/middleware.py#L94

For session recordings we probably will need to add the project id in the URL as it's just a filter without an ID

**Comment by daibhin** [comment]
This should be solved for now that we have project based routing across the app: https://github.com/PostHog/posthog/pull/13474
