### ISSUE TITLE
Separate query logic from APIs

### ISSUE THREAD

**Issue by timgl** [PostHog/posthog#1268]
## Is your feature request related to a problem?

We do a lot of our analytics in API viewsets etc. This is a bad place for it, for a couple of reasons:
- These API files are huge and a big mess
- There's analytics stuff in events.py, actions.py, retention.py, funnels.py etc, but it's hard to mix and match or add new capabilities
- Tests run very slowly because they have to go through Django rest framework

## Describe the solution you'd like

Separate the query generation and serialisation from APIs and Models

## Additional context

I'm going to do a quick spike for this to see what people think of a potential solution. This fits in with the work Eric's doing in #1250

**Comment by timgl** [comment]
cc @EDsCODE

**Comment by Twixes** [comment]
This is largely done (had to be to implement ClickHouse).
