### ISSUE TITLE
Group values in breakdowns on insights

### ISSUE THREAD

**Issue by lsmith77** [PostHog/posthog#12698]
## Is your feature request related to a problem?

I would like to group certain breakdown values together, f.e. `None` and `null` in the below example but it could also be useful for arbitrary strings like `plan_freemium`, `plan_team_freemium`:
<img width="157" alt="image" src="https://user-images.githubusercontent.com/300279/200519509-38583b20-ac76-4ce6-bb10-98ef7a5cd79a.png">

## Describe the solution you'd like

When defining a breakdown the ability to optionally set a mapping table to make values to other values.

## Additional context

* https://github.com/PostHog/posthog/issues/12669
* https://github.com/PostHog/posthog/issues/12365

**Comment by hazzadous** [comment]
@lsmith77 I've assigned to the appropriate person(?) so they'll be able to triage accordingly for if it's a candidate for an upcoming sprint 🙏

**Comment by lsmith77** [comment]
I guess this is now possible via HogQL
https://posthog.com/changelog/2023#breakdowns-now-editable-with-hogql
