### ISSUE TITLE
Two step funnel trend graph

### ISSUE THREAD

**Issue by dwenaus** [PostHog/posthog#1269]
## Is your feature request related to a problem?

We want to see how an important conversion metric trends over time. 

## Describe the solution you'd like

Screenshot from our mixpanel dashboard:

![image](https://user-images.githubusercontent.com/393655/88313122-e58cf580-ccc7-11ea-8728-3397366b57a2.png)

**Comment by paolodamico** [comment]
Strong +1 from [user feedback](https://posthog.slack.com/archives/C011L071P8U/p1609922039001600).

Also requested by another user a day ago.
