### ISSUE TITLE
Maximum call stack size exceeded.

### ISSUE THREAD

**Issue by kritop** [PostHog/posthog#12695]
## Bug description

we see a 2000-3000 RangeErrors per day in our bugsnag frontend tracking.
![Screenshot 2022-11-09 at 14 33 06](https://user-images.githubusercontent.com/2034466/200843546-6b39712f-5007-4275-a1c7-5233e52a8218.png)

all browsers, os and devices seem to be similarly affected

## How to reproduce

not sure.

## Environment

- [x] PostHog Cloud
- [ ] self-hosted PostHog, version/commit: please provide

**Comment by hazzadous** [comment]
Not ideal! So we can prioritise, is this causing PostHog to hard fail?
