### ISSUE TITLE
PostHog session recording only captures first section on the page of about 8 sections revealed on scrolled.

### ISSUE THREAD

**Issue by Forison** [PostHog/posthog#12690]
## Viewport Scrolling is not captured by PostHog session recording

*Please describe.*  

We are currently having issues with PostHog session recording. The recording occurs on a SPA. The page has about 8 sections, each section becomes visible after the user clicks a button and the viewport is scrolled automatically (via react-scroll, version 1.8.2) so that the new section is at the top of the page. what happens currently now is that the application works fine but the recording only points to the first section of the page whilst the remaining sections are not recorded. Looks like the recording does not capture the automatic scrolling. On the hand events are emitted which shows clearly that the user is going through the flow, but the video can't capture the subsequent sections.
   
## How to reproduce

There about eight sections revealed on scroll
1. User clicks `enter button` inside the first section to auto-scroll to the next section, session recording captures the first section.

2. Session recording gets stack on the very first section whilst user actually goes through the flow

## Environment

- [ ] PostHog Cloud

## Additional context
![stuckOnThisScreen](https://user-images.githubusercontent.com/29695661/200872548-64655f87-352a-4951-89ff-3d2a119a1c2b.png)

**Comment by Forison** [comment]
Hello @benjackwhite,
Please can you provide me with update about this issue?
Thank you
regards @Forison

**Comment by hazzadous** [comment]
Hi @Forison 

I suspect this is an issue with the underlying recording library we are using, rrweb. If it's at all possible it would be good to try to reproduce this purely with rrweb and see if the problem still persists. And if so, we can make a request to the upstream to resolve the issue there.

What do you think @benjackwhite ?

**Comment by Forison** [comment]
Hello @benjackwhite and @hazzadous 
Please kindly let us know how we can help from our side, it will also be nice if you let us know how this issue is prioritize because it is super critical for our business.
Thanks 
regards Addo

**Comment by Forison** [comment]
hello @benjackwhite and @hazzadous 
We have been able to repoduced the issue using rrweb, No issues were found. Can you please check from your end?
regards
@Forison

**Comment by hazzadous** [comment]
@Forison ah so rrweb manages to capture the scroll mutations?

It's possible that the latest rrweb version includes a fix for the scrolling capture. @benjackwhite do you have any insights here?

**Comment by Forison** [comment]
@hazzadous yes, it works fine, it recorded all section of the page as expected

**Comment by aleksander-tatskiy** [comment]
@hazzadous @benjackwhite  Looks like they have fix for scroll https://github.com/rrweb-io/rrweb/pull/1029

**Comment by benjackwhite** [comment]
@Forison can you provide us with something to help us debug further like a link to the recording and a link to the page that doesn't seem to be recorded properly?

Can I ask what version of rrweb you used to test it with where everything seemed to work correctly?

**Comment by aleksander-tatskiy** [comment]
@benjackwhite probably the latest version `rrweb@2.0.0-alpha.4`

**Comment by benjackwhite** [comment]
> @hazzadous @benjackwhite Looks like they have fix for scroll [rrweb-io/rrweb#1029](https://github.com/rrweb-io/rrweb/pull/1029)

Nice find! That is likely the fix. We decided not to use the alpha version of rrweb as it has a lot of _other_ issues that are still being ironed out but sadly until that is released it seems all the fixes are only going to be available there...

Normally we like to live on the edge but here we took a more cautious approach. I'm going to investigate if we can have some way of "opting-in" to the latest versions as I feel for some cases like this the alpha version is already better than the existing one.

**Comment by aleksander-tatskiy** [comment]
> > @hazzadous @benjackwhite Looks like they have fix for scroll [rrweb-io/rrweb#1029](https://github.com/rrweb-io/rrweb/pull/1029)
> 
> Nice find! That is likely the fix. We decided not to use the alpha version of rrweb as it has a lot of _other_ issues that are still being ironed out but sadly until that is released it seems all the fixes are only going to be available there...
> 
> Normally we like to live on the edge but here we took a more cautious approach. I'm going to investigate if we can have some way of "opting-in" to the latest versions as I feel for some cases like this the alpha version is already better than the existing one.

Thank you @benjackwhite . For sure, I understand your concerns about alpha version. But currently we are blocked in providing the best level of support for our customers without this feature. Is there a way that you can ask rrweb team to backport this fix to older stable version of `rrweb` you are using?

**Comment by Forison** [comment]
Hello @hazzadous and @benjackwhite
Please is there any update in relation to the issue?
Thanks

**Comment by mohammadameer** [comment]
@Forison were you able to fix this ? facing the same issue, only the main scroll is recorded, our UI is built on div scrolling so we see the user just clicking and scrolling on the first page


https://user-images.githubusercontent.com/35637666/209288292-c493d8e8-e159-43f6-a680-a7fc8c8cbee4.mov

@hazzadous @benjackwhite

**Comment by hazzadous** [comment]
@Forison @mohammadameer I suspect this isn't too high on the list of team session recordings priority list, but if you spot a new release of [rrweb](https://github.com/rrweb-io/rrweb/releases) then shout. I think that's the most likely outcome, but @benjackwhite will have more context.

**Comment by pauldambra** [comment]
The default version is now rrweb 2
