### ISSUE TITLE
Benchmark `join_algorithm` query setting

### ISSUE THREAD

**Issue by macobo** [PostHog/posthog#12691]
In clickhouse joins and subqueries are problematic and load the dataset into memory. See more details in https://posthog.com/handbook/engineering/clickhouse/data-storage#weak-join-support

Experiment with [join_algorithm](https://clickhouse.com/docs/en/operations/settings/settings/#settings-join_algorithm) setting which might reduce memory usage in some scenarios.

See also: https://www.tinybird.co/clickhouse/knowledge-base/join-algorithm

**Comment by macobo** [comment]
Note: Probably depends on upgrading clickhouse to 22.8 first - the options on 22.3 are limited!

**Comment by yakkomajuri** [comment]
Done! #14084 

We'll be moving to `direct,parallel_hash` as the default
