### ISSUE TITLE
Demo data option during onboarding

### ISSUE THREAD

**Issue by timgl** [PostHog/posthog#12703]
## Is your feature request related to a problem?

Some people aren't comfortable or can't ingest real data into posthog cloud right away. This means they can't evaluate PostHog properly. @Twixes put a bunch of work in creating a separate demo instance, but that was buggy as it was another instance to maintain

## Describe the solution you'd like

During onboarding, give users the option to create another team with the demo data so they can have a poke around.

## Additional context

The code for the demo [lives in posthog/demo](https://github.com/PostHog/posthog/tree/master/posthog/demo)
We have a bunch of old code for the /demo path that we should simultaneously get rid of.
The new team should have is_demo set.
Need to make sure we don't accidentally charge for any events for this team.

**Comment by Twixes** [comment]
It'd be great to remove the old demo data generation code (`DataGenerator` subclasses). The annoying thing is that Cypress tests and property definition Python tests rely on it, so those dependencies need to be dropped first.

**Comment by raquelmsmith** [comment]
> It'd be great to remove the old demo data generation code (DataGenerator subclasses)

@Twixes I haven't really started digging into this, but if we remove the demo data generation code, how would the demo data be generated? Or are you saying it should be refactored in some way? Can you explain a bit more?

**Comment by raquelmsmith** [comment]
Making progress on this. Remaining to-dos listed here: https://github.com/PostHog/posthog/pull/12877
