### ISSUE TITLE
Create Github Action to run Performance test against PRs

### ISSUE THREAD

**Issue by fuziontech** [PostHog/posthog#1271]
Once we have a good story for how we will be performance testing Posthog #1270 we will want to build a way to automatically run the benchmark against changes made to the events pipeline.

The goal with this, as the title suggests, is to build a Github Action to automatically benchmark and record improvements and regressions in performance for PRs made that impact the events pipeline. As a first pass I think it would be ok to run this for all PRs but eventually it would be nice to be smart enough to detect whether the events pipe was touched and run the benchmark if it was.

**Comment by paolodamico** [comment]
We now do performance tests on queries, so closing.
