### ISSUE TITLE
Feature request: Improved saving of lifecycle insights

### ISSUE THREAD

**Issue by joethreepwood** [PostHog/posthog#12728]
## Is your feature request related to a problem?

If I create a lifecycle insight, by default it shows me all four statuses: New, Returning, Resurrecting and Dormant. But what if I want to only view some of these, on a dashboard or regularly used insight? I can't. Saving an insight where only Returning users are visible overwrites the toggle and restores all four statuses. 

So, if I save this to a dashboard: 

<img width="880" alt="Screenshot 2022-11-10 at 14 08 27" src="https://user-images.githubusercontent.com/84011561/201113259-e28ec52b-9b7f-4962-8ed2-f718169d980c.png">

I still see this on the dashboard:

<img width="878" alt="Screenshot 2022-11-10 at 14 09 35" src="https://user-images.githubusercontent.com/84011561/201113550-ef9d4833-4dbe-410b-8a6a-df0acf59a633.png">

## Describe the solution you'd like

Toggle are saved as part of the insight.

**Comment by benjackwhite** [comment]
Customer mentioned this as well

**Comment by pauldambra** [comment]
closed in #14547
