### ISSUE TITLE
Several Postgres tables use integer IDs and we will eventually turn into a 🎃 (overflow)

### ISSUE THREAD

**Issue by fuziontech** [PostHog/posthog#12721]
Hello friends - I am once again asking you to help me rid our codebase of integer IDs. Each and every one of these (not really, just the big ones) will overflow one day and cause us tremendous pain.

Luckily there are plenty of ways to mitigate this without downtime and moving towards a much better primary key:
https://buildkite.com/blog/avoiding-integer-overflows-with-zero-downtime

Several tables for us are using Integer IDs as Primary Keys ( a bad idea ™️ ) and are not immediately in trouble, but eventually will be in trouble. The following tables are the most at risk with 5% - 40% utilization of integer space.
| Table | Utilization of integer space | Status |
| -- | -- | -- |
| posthog_events | 61.89% | dead |
| posthog_persondistinctid | 39.61% | increasing |
| posthog_person | 35.73% |  increasing |
| posthog_pluginstorage | 14.35% |  increasing |
| posthog_eventproperty | 10.15% |  increasing |
| posthog_action_events | 8.73% | dead? |

https://docs.google.com/spreadsheets/d/1mkCkZaC5qMlJ4zri6bJqzLpeG6kFKJjpS26V9AR0Wlk/edit?usp=sharing

**Comment by tiina303** [comment]
Note that someone self-hosting might be utilising the integer space to an even larger degree and hence run into problems before we do in cloud.

**Comment by fuziontech** [comment]
Closing as we have completed this migration as part of our migration to Aurora on AWS
