### ISSUE TITLE
Searching has:email on Users returns multiple of the same users

### ISSUE THREAD

**Issue by timgl** [PostHog/posthog#1273]
## Bug description

If you search has:email on Users it returns multiple of the same users. I think this is because the searching that I added.

## Expected behavior

It should only show each user once.

## How to reproduce

1. Go to users
2. Search `has:email`
3. See some users appear multiple times

## Environment

- PostHog cloud or self-managed?
- PostHog version/commit

**Comment by EDsCODE** [comment]
I took a look at what data was returned and it seems like there's actually separate instances of people with the same email. For example, if you search marius.andra@gmail.com you will find a dozens instances of him with 1 distinct id. Each instance just has an identify call and a subsequent authenticate toolbar action. Some of them are copies but not all

**Comment by mariusandra** [comment]
Hi! That was caused by a bug in the toolbar instrumentation and will be fixed once this is in: https://github.com/PostHog/posthog/pull/1322
The problem might have been there before these toolbar actions though. Most likely the diagnosis will be the same: distinct users, but same e-mail.

**Comment by timgl** [comment]
Fixed
