### ISSUE TITLE
Nail historical import

### ISSUE THREAD

**Issue by camerondeleone** [PostHog/posthog#12743]
## Is your feature request related to a problem?

I’m not sure who owns ‘importing historical data’ as our current posture puts this heavily on the sdks (owned by team-product-analytics), but it has obvious ramifications for #team-pipeline as well, and ultimately should live with them once apps handle this. 

We are starting to see more high volume customers looking to migrate from competitors or warehouses, and in one case we've even agreed to handle a bespoke import from bigquery. 

## Describe the solution you'd like

This is more of a placeholder since I don't have a specific opinion on what the solution should look like or who should do the work.

In the mean time, putting some work into some more polished import scripts (with retry logic/error handling, etc) would help us onboard customers. It would also help us clear up expectations on what rate data should be sent at, etc. 

## Describe alternatives you've considered

Offer to do the import ourselves where that makes sense, or just refer people to their own scripts with the sdks

## Additional context

A couple of channels where this is being discussed (internal):

- https://posthog.slack.com/archives/C0486JC56H3/p1668027531119229 (ask Cameron for an invite, channel is private)
- https://posthog.slack.com/archives/C046KH1MXHD/p1667055368454619

**Comment by Twixes** [comment]
I think the Pipeline team have got this.
