### ISSUE TITLE
Match the app branding to the website

### ISSUE THREAD

**Issue by jamesefhawkins** [PostHog/posthog#1275]
## Is your feature request related to a problem?

We are improving posthog.com's design at the moment, and the app itself should match!  This will help things feel professional which has the end result of more usage from more teams around the world.

## Describe the solution you'd like

We have a [design in figma](https://www.figma.com/file/OnHvvxuR0ip6vc5vyUms2u/Website-layout-padding-out?node-id=538%3A2) that contains:

- [ ] App sidebar color palette change
- [ ]  Font change
- [ ]  App background color change
- [ ]  Graphs with more rounded corners
- [ ]  Removal of shadows around the graphs
  * These should remain on dragging the dashboard areas around (it's a really nice effect)
- [ ] Graph background color palette change
  * we'd need to swap out the options given by the dashboard currently to (white on orange, white on yellow, white on blue, or orange on white, yellow on white or blue on white)
  * the path's page would still look reasonable given it's a variety of shades of blue. Perhaps the 100% opacity blue should be swapped to the same blue in the posthog logo though, and the red drop off should remain (as it's distinctly bad and orange != bad)
- [ ]  Button change (elements are more rounded, font is different, icons are different)
  * I'd suggest we do NOT change the icons themselves just yet.
  * Our buttons are the moment are generally blue with white text. I'd swap this to the new shade of blue with white text.
  * The buttons, inputs and selects should have a rounder radius perhaps (to match the top right of the figma 'Dashboard' page)?
  * Our selects are currently grey with dark text. I'd suggest these become the "new" graph in the sidebar with text that matches the dark colour in the sidebar
- [ ] logo change to colored version (we can try this then revert to dark version if it's distracting)

## Describe alternatives you've considered

Not doing this, which looks a little odd!

**Comment by jamesefhawkins** [comment]
@timgl I think the above is perhaps quite straightforward having thought about the detail...

**Comment by Twixes** [comment]
Since we're going for a bit of a stylized look, unlike, say, GitHub's minimalism, could we change our UI font from system to some more specific sans-serif? Nothing fancy, just something with slightly more character and very readable that would match headlines' Gosha Sans. Unless we want to blend in with with the system look?

**Comment by jamesefhawkins** [comment]
> Since we're going for a bit of a stylized look, unlike, say, GitHub's minimalism, could we change our UI font from system to some more specific sans-serif? Nothing fancy, just something with slightly more character and very readable that would match headlines' Gosha Sans. Unless we want to blend in with with the system look?

We had [Ty Wilkins](http://tywilkins.com/), the person that did the logo, have a look into this - see [what he suggested](https://www.figma.com/file/8iM3Damgbl4PyHq6x8JJbu/PostHog-Branding?node-id=0%3A1). What do you think?

**Comment by Twixes** [comment]
So Ty proposed Helvetica Neue.

I think [Söhne](https://klim.co.nz/retail-fonts/soehne/) would fit us a bit better – it's essentially still Helvetica Neue, but more open. As a matter of fact used by Stripe for UI.

If we really wanted to stick to Helvetica, then the new [Helvetica Now](https://www.monotype.com/fonts/helvetica-now) is more suited for digital than Neue from 1982.

We could also go for something more geometric: [Harmonia Sans](https://www.fonts.com/font/monotype/harmonia-sans) is a strong contender.

Here are some samples:

![Soehne](https://user-images.githubusercontent.com/4550621/88659159-e44b3680-d0d4-11ea-8162-2b50d9c56030.png)
-
![Helvetica Neue](https://user-images.githubusercontent.com/4550621/88659157-e1e8dc80-d0d4-11ea-9b4e-555eaa38ca7b.png)
-
![Harmonia Sans](https://user-images.githubusercontent.com/4550621/88659162-e614fa00-d0d4-11ea-81d6-6d629c4bd3a2.png)

**Comment by mariusandra** [comment]
I'd definitely need to have a look at them on the live site to have a better opinion.

- "Helvetica Now" looks good, but it seems expensive. Not sure if the hassle of managing licenses is worth it.
- "Harmonia Sans" seems nice for headlines... but in my subjective opinion the overly round "a" looks strange at a smaller size. It's a bit too close to a "O" and impedes readability:
![image](https://user-images.githubusercontent.com/53387/89169857-1bab5e80-d57f-11ea-9f21-d5200ea1dc73.png)

**Comment by Twixes** [comment]
Helvetica Now isn't cheap, but not super expensive. I like Söhne most, but this one definitely costs a lot, and we don't have Stripe-level resources. Also, agreed, a circular "a" may not be ideally readable.

**Comment by lottiecoxon** [comment]
I would say Söhne and Helvetica Neue are very very similar - bar Söhne being a tad more condensed, giving it a little more height and making the 'O' closer to the Gosha Sans Font family. If the cost is dramatically more I vote we stick with Ty's decision and save the money as in my opinion the difference is minor

**Comment by Twixes** [comment]
Now costs exactly as much as Neue, so I vote for that one out of the two.

**Comment by lottiecoxon** [comment]
![now vs new](https://user-images.githubusercontent.com/65415371/89311030-61465500-d66d-11ea-85aa-d8c8072fd477.jpg)

I vote Helvetica now also - feels like it has more personality. But I would like to see it in use on the website before purchasing

**Comment by Twixes** [comment]
Just one note: Micro is specifically for teeny tiny sizes, we'd probably need Text Regular, Text Regular Italic, Text Bold, and Text Bold Italic (for regular copy), and *maybe* Text Medium (for floating toolbar parts) plus Display Regular (for headlines – *maybe* also Display Italic and/or Display Bold?).

Sadly only Display Black has a [free sample](https://hello.monotype.com/Helvetica-Now-Download.html).

**Comment by mariusandra** [comment]
Yeah, Söhne seems to be going into the hundreds of thousands of dollars range for unlimited usage on all platforms... and I'd take a few more engineers over a marginally better font :D 

Helvetica Now's pricing is a bit weird. I can't figure out how much we'd pay for it to not run into problems in the future.

I'd personally just not overthink it and add something [like this](https://css-tricks.com/snippets/css/better-helvetica/) to the CSS and be done with it:

```css
body {
   font-family: "HelveticaNeue-Light", "Helvetica Neue Light", "Helvetica Neue", Helvetica, Arial, "Lucida Grande", sans-serif; 
   font-weight: 300;
}
```

**Comment by Twixes** [comment]
Pricing may be a bit weird overall as our software is destined to run on other people's (who don't have the same font licenses) behalf as well, and making sure this is covered may be tricky. To be honest I'm not sure if our current Gosha Sans license allows this, though the app doesn't include it (so far) and this is probably more of a question for @jamesefhawkins.

**Comment by jamesefhawkins** [comment]
> I'm not sure if our current Gosha Sans license allows this

I emailed to check, and so I'd get a response in writing, but tbh our use case is unusual. That does mean we have them saying their happy in this case.

**Comment by paolodamico** [comment]
Think we can now close this? The app has been mostly updated to the new designs. Perhaps the only missing piece is adding Gosha Sans for the page's titles. I'm just unsure if we can directly include it in the repo directly (because the font is copyrighted and we're using MIT), maybe we need to include a license for the font? POV @piemets?

**Comment by charlescook-ph** [comment]
> Think we can now close this? The app has been mostly updated to the new designs. Perhaps the only missing piece is adding Gosha Sans for the page's titles. I'm just unsure if we can directly include it in the repo directly (because the font is copyrighted and we're using MIT), maybe we need to include a license for the font? POV @piemets?

The Gosha people did email back a long time ago to say that use case was fine, so we're ok.

**Comment by paolodamico** [comment]
App now has Gosha Sans for titles like we planned as of #3300
