### ISSUE TITLE
BigQuery app: Handle `Request Entity Too Large` errors properly

### ISSUE THREAD

**Issue by macobo** [PostHog/posthog#12756]
## Bug description

I was diagnosing success of historical exports. One error that stood out as a common error cause was `Request Entity Too Large` error. [metabase](https://metabase.posthog.net/question/485-historical-exports-analysis)

This error currently gets retried until the export fails. We should probably instead automatically split the payload.

This would remove our most common error causing exports to fail.

## Environment

- [x] PostHog Cloud
- [ ] self-hosted PostHog, version/commit: please provide

## Additional context

cc @yakkomajuri @hazzadous @tiina303

**Comment by tiina303** [comment]
The app is deprecated in favor of BigQuery batch exports
