### ISSUE TITLE
Session Feed timestamps wrong

### ISSUE THREAD

**Issue by EDsCODE** [PostHog/posthog#1277]
## Bug description
When you load more session, the timestamps are -4 off (which makes me think it has to do with mixup between local and unix)

*Please describe.*  
*If this affects the front-end, screenshots would be of great help.*  

## Expected behavior

Time should be consistent and continuous

## How to reproduce

1. Go to sessions list
2. Click the previous day
3. Click load more
The timestamps will be discontinuous by the difference between GMT-0 and your local timezone

## Environment

- PostHog cloud or self-managed?
- PostHog version/commit

**Comment by timgl** [comment]
Closed
