### ISSUE TITLE
[EPIC] New analytics views

### ISSUE THREAD

**Issue by timgl** [PostHog/posthog#1279]
There are a couple of analytics views/functionalities that we don't yet have.

- [ ] User Composition
I want to be able to select a Person property and show the breakdown of that property in a pie chart

- [ ] Engagement matrix
I want to be able to select a couple of events/actions, and understand, from all users that were active in that time period a) what percentage of those did that event and b) how many times on average a user did that event.
<img width="400" alt="" src="https://user-images.githubusercontent.com/1727427/88530443-adf0b700-d001-11ea-8c19-0c3d5d9485bf.png">

- [ ] "Compass" / "Signal"

I want to be able to answer "How does performing action Y predict a user coming back a week later", ie is there a positive correlation. [Mixp@anel docs](https://help.mixpanel.com/hc/en-us/articles/115004567503-Signal-Report-Basics).

- [ ] Impact analysis

I want to be able to answer "How does performing action Y impact action Z".
<img width="400" alt="" src="https://user-images.githubusercontent.com/1727427/88531994-1345a780-d004-11ea-9bf5-8f8a7fa91c6e.png">

- [ ] Revenue LTV

We'd need to be able to capture `revenue` events with a `$revenue` property to be able to do this.

- [ ] Personas

Some kind of user clustering functionality?

<img width="400" alt="" src="https://user-images.githubusercontent.com/5864173/118990569-01494280-b951-11eb-9c99-b9e305d6fb75.png">

- [X] Ratio of DAUs over MAUs

- [x] Lifecycle #1209

**Comment by jamesefhawkins** [comment]
> Some kind of user clustering functionality?

 It's not high priority - what's the difference between personas versus the cohorts we already have?

**Comment by timgl** [comment]
@jamesefhawkins that functionality can automatically group certain types of users in clusters based on behaviour etc. It's fairly advanced and don't think worth investing in now

**Comment by masonhensley** [comment]
@timgl - regarding the revenue.

Yes, as something you could specify (purchased $50)... but it might be powerful to just tag a user/team's stripe_customer_id and hot link that over to stripe. Getting into revenue analytics, it's going to be wonky without historical data unless your only concerned with MRR/ transaction data.

**Comment by paolodamico** [comment]
### User clustering
> @jamesefhawkins that functionality can automatically group certain types of users in clusters based on behaviour etc. It's fairly advanced and don't think worth investing in now

For context, this has also come up in a [customer call](https://posthog.slack.com/archives/C01B23A14RY/p1600672745000500). 

### Engagement matrix
I believe #1690 is strongly related to this. I would potentially work on #1690 first as it can provide the basis for the engagement matrix discussed here.

### Compass & Impact analysis
I would make sure we add notes/warnings here based on the sample size to avoid confusion.

### DAU/MAU ratio
We already have from user feedback that our navigation / discoverability is becoming a bit complex, I would just add the note here to review the UX of this as not to overwhelm users that don't have a use for it.

**Comment by paolodamico** [comment]
From customer feedback, related to the **Engagement matrix**, aside from being able to see the average count of events per  user, a breakdown by properties of cohorts would be very helpful, to try to answer questions like (based on Hogflix model):
- Which users have played a movie X or more times.
- How many movies played per-user on average per day/week/month?
- Do different cohorts play more movies?

**Comment by paolodamico** [comment]
I think this has evolved into other individual issues, so closing.
