### ISSUE TITLE
Monthly active users metric wrong when using Number as chart type

### ISSUE THREAD

**Issue by YoannBuch** [PostHog/posthog#12800]
## Bug description

Monthly Active Users metric seems wrong when choosing "# Number" as chart type.

Number: 
![image](https://user-images.githubusercontent.com/513669/201980874-be7d9c0d-5c9c-4c1e-955c-ea4143c84061.png)

Line chart: 
![image](https://user-images.githubusercontent.com/513669/201980986-b17af929-84e5-4f6a-b7f8-23b7ac8bedbc.png)

**490 != 70**

## How to reproduce

1. Create a new insight using any event and the "Monthly active users" metric
2. Date range = This month + Grouped by = Day
3. Choose chart type as Number => remember value
4. Change chart type as Linear => check last data point

=> the 2 values do not match
=> in other words there's a diff between a total aggregation and an aggregation per bucket of time ?

## Environment

- [x] PostHog Cloud

**Comment by timgl** [comment]
The number shows the total unique users over that period. If you want it only for the current day you should set date range to "today". Hope that helps!

**Comment by Twixes** [comment]
I believe @YoannBuch is correct, as this is "Monthly active users" and not "Unique users". The former is a trailing count, so the number for an aggregated insight (i.e. not a time series, like Number or Pie chart) should be about the same as the number at the beginning of the selected time period in the time-series version (in our rendition of MAU/WAU).

**Comment by YoannBuch** [comment]
Thanks for the quick replies!

> should be about the same as the number at the beginning of the selected time period in the time-series version

Should it be the beginning or the end?

As a user, in the above example, I would expect it to be **the end** = 70: so far in the current month we're at 70.

But as I'm writing this I realize that what I am looking for (the MAU for the current month) can be simply answered with the metric "Unique users" since I'm selecting "This month" :man_facepalming:

**Comment by Twixes** [comment]
We've just updated our querying engine to support this combination of options properly @YoannBuch. Specifically, when using the Number display mode (or other non-time-series ones), we now calculate MAU/WAU for the end of the selected time range (which is usually the current point in time, except when using a fixed date range).

**Comment by YoannBuch** [comment]
This is great @Twixes ! Thanks a lot of the quick turnaround :heart:
