### ISSUE TITLE
Feature flag not working with local evaluation

### ISSUE THREAD

**Issue by morgante** [PostHog/posthog#12810]
## Bug description

I am using `posthog-node` and attempting to do local evaluation for feature flags. However, it seems to *always* return `unknown` even for flags that are rolled out to 100% of users.

## How to reproduce

1. Add a flag and set it to 100% of users
2. Call the flag from the node.js API
```
const myFlag = posthog.getFeatureFlag(user.id, "MY_FLAG", {
      onlyEvaluateLocally: true,
      personProperties: {},
      groupProperties: {},
    });
// myFlag is undefined
```
3. This returns unknown, even though the UI shows the flag as 100% rolled out and inspection of the internal state shows it to be present.

Contents of `posthog.featureFlagsPoller.featureFlags`:
```
{
      id: 5185,
      name: '',
      key: 'MY_FLAG',
      filters: {
        groups: [ { properties: [], rollout_percentage: null } ],
        multivariate: null,
        aggregation_group_type_index: null
      },
      deleted: false,
      active: true,
      ensure_experience_continuity: false
    }
```

## Environment

- [x] PostHog Cloud

**Comment by timgl** [comment]
@neilkakkar

**Comment by neilkakkar** [comment]
Hey @morgante , there's 2 issues with your code:

1. `getFeatureFlag` is async & returns a promise, so you need to `await` it.
2. The method signature takes in the flag key first, and distinct ID second, so it needs to be `getFeatureFlag("MY_FLAG", user.id`

Let me know if you still face issues.

**Comment by morgante** [comment]
Edit: thanks for the help, I was looking at the outdated docs.

**Comment by neilkakkar** [comment]
Cool, glad it worked :)

Could you please tell me how you reached the outdated docs? @morgante . Asking if there's anything we can fix that prevents others from going down this route.

**Comment by morgante** [comment]
I think I got there from Google, but don't really recall.
