### ISSUE TITLE
Feature Request: Paths for events, actions, filters

### ISSUE THREAD

**Issue by joethreepwood** [PostHog/posthog#12837]
## Is your feature request related to a problem?

@charlescook-ph recently did [an analysis of mobile conversions](https://posthog.slack.com/archives/C01FHN8DNN6/p1668683311897649). I wanted to look at paths for these users (based on an action we have, and a filter looking at UTMs) and compare it to normal users. That currently doesn't seem possible. 

The specific result I want to get to is a comparison of the following paths:

- A path that starts with the action `Marketing: Cloud Conversion` where `UTM source` equals `bing``reddit` `quora` `google` `twitter` etc
- A path that starts with the above _and_ ends with the action `User signed up (comprehensive)` 
- A path for all _other_ users which ends in `User signed up (comprehensive)` and _doesn't_ start with the above

The problem is that it's currently impossible to create paths based around actions or even comparable events to create this insight. 

Comparing paths is also a pain, but that's another problem. 

## Describe the solution you'd like

Paths which have a comparable insight builder to other insights, e.g. trends. 

## Describe alternatives you've considered

🤷 

## Additional context

@neilkakkar says this would be super hard, so I'm not holding my breath :) 

#### *Thank you* for your feature request – we love each and every one!

No, thank _you_.

**Comment by billmetangmo** [comment]
I have the same need.
