### ISSUE TITLE
Allow paths and retention table to become dashboard items

### ISSUE THREAD

**Issue by EDsCODE** [PostHog/posthog#1283]
## Is your feature request related to a problem?
pending #1265 you will be able to see retention table and paths alongside funnels/trends but you can't create a dashboard item of them

## Describe the solution you'd like
Implement ability to create dashboard item of retention tables nad paths viz

## Describe alternatives you've considered
Don't allow

## Additional context
This relies on optimized handling of retention and path queries

**Comment by Twixes** [comment]
This can now be done.
