### ISSUE TITLE
Compare to previous time on stickiness jumps to trends

### ISSUE THREAD

**Issue by ivanagas** [PostHog/posthog#12876]
## Bug description

On stickiness graph, clicking compare to previous time, jumps to trends 

https://www.loom.com/share/72c7ff4b50f84fb3ac1115457a40e1dd

## How to reproduce

1. Create stickiness insight
2. Click compare to previous time period

## Environment

- [x] PostHog Cloud
- [ ] self-hosted PostHog, version/commit: please provide

**Comment by neilkakkar** [comment]
cc: @mariusandra looks related to insight filter breakup
