### ISSUE TITLE
Webhook sends notifications on actions that don't meet the filter.

### ISSUE THREAD

**Issue by elongl** [PostHog/posthog#12893]
## Bug description

We have an action that is defined on an event and has two filters.
1. X event property is set.
2. X event != null.

The action is defined to _Post to webhook when this action is triggered_.

The bug is that PostHog wrongfully sends notification when the action is not triggered.
I thing this happens because only **one of the filters match but not both**.
Needless to say that the filters are defined with an AND operator.
In addition to that, I don't see any events under the _Matching events_ section below within the action's page.

Could you please make the webhook trigger only when the action is matched on both filters?
Thanks a lot.

## Environment

- [x] PostHog Cloud
- [ ] self-hosted PostHog, version/commit: please provide

**Comment by neilkakkar** [comment]
Hey Elon, mind sharing a link to the action that's problematic?

**Comment by elongl** [comment]
@neilkakkar Not sure if action IDs are global to all accounts, but here's mine - https://app.posthog.com/data-management/actions/20804.

**Comment by neilkakkar** [comment]
The issue seems to be with the null exact match:

In Clickhouse matching:
```
(   has(['null'], replaceRegexpAll(JSONExtractRaw(properties, 'env__elementary_hosted_account_id'), '^"|"$', ''))
```

In plugin server matching:

the `"null"` string != `null`, hence the webhook firing incorrectly.

**Comment by elongl** [comment]
How could I fix it?
Is there anything I can do on my end to resolve this?

Also, is there a way to filter on nested objects?
I have to flat my event properties using an extension to allow myself to filter on them.

**Comment by neilkakkar** [comment]
It's a bug on our end, I'm working on a fix right now :)
