### ISSUE TITLE
Remove "optimize_move_to_prewhere" setting everywhere

### ISSUE THREAD

**Issue by macobo** [PostHog/posthog#12902]
PREWHERE is a clever trick for ClickHouse to speed up querying. Read more about it in the clickhouse manual: https://posthog.com/handbook/engineering/clickhouse/data-storage

We have it disabled for a bug fix, which hurts performance significantly on _all_ queries. We should remove this setting or only enable it in certain conditions.

Fixing this might require upgrading clickhouse.

See [this slack thread](https://posthog.slack.com/archives/C034XD440RK/p1660808979621639) and [this PR](https://github.com/PostHog/posthog/pull/10848) for context on the bug causing us to enable this setting.

**Comment by neilkakkar** [comment]
Query to test when we're on the 'right' CH version to remove this setting everywhere: https://metabase.posthog.net/question/385-move-to-prewhere-failure-in-clickhouse-22-3

**Comment by macobo** [comment]
Additional context: https://github.com/ClickHouse/ClickHouse/issues/36279

**Comment by macobo** [comment]
Minimal-ish repro locally:

Run this: `python manage.py materialize_columns --property "distinct_id"`

```sql
SELECT e.timestamp as timestamp,
    e."mat_distinct_id" as "mat_distinct_id",
    e."mat_email" as "mat_email"
FROM events e
INNER JOIN (
    SELECT distinct_id,
            argMax(person_id, version) as person_id
        FROM person_distinct_id2
        WHERE team_id = 2
        GROUP BY distinct_id
    HAVING argMax(is_deleted, version) = 0
    ) AS pdi
ON e.distinct_id = pdi.distinct_id
WHERE team_id = 2
    AND event = '$pageview'
    AND (NOT ("mat_distinct_id" ILIKE '%posthog.com%'))
    AND (NOT ("mat_email" ILIKE '%posthog.com%'))
SETTINGS allow_experimental_window_functions = 1, optimize_move_to_prewhere = 1
FORMAT Null
```
Error:
```
Code: 44. DB::Exception: Received from localhost:9000. DB::Exception: Argument at index 1 for function ilike must be constant: while executing 'FUNCTION ilike(mat_distinct_id : 11, '%posthog.com%' : 4) -> ilike(mat_distinct_id, '%posthog.com%') UInt8 : 13'. (ILLEGAL_COLUMN)
```

The problem seems to be the shared `'%posthog.com%'` value.

Verified that the problem is fixed in ClickHouse 22.8 - we should fix by upgrading.

**Comment by macobo** [comment]
Incidentally benchmarked this in production: this setting sped up a sample of queries for largest 10 US clients approximately 25%, p95 query duration improved 55%.

**Comment by macobo** [comment]
22.8 is now live on cloud :raised_hands:
