### ISSUE TITLE
Updating dashboard filters or date ranges never hits the cache

### ISSUE THREAD

**Issue by macobo** [PostHog/posthog#12901]
When updating filters or date ranges on a dashboard we never try to hit the cache, always doing a full reload.

On one hand, it ensures that users get a "consistent" looking dataset that's fresher than the one they had before.

On the other, refreshing 10+ dashboard tiles is always going to be slow.

What should we do here product-wise?

**Comment by pauldambra** [comment]
I think it's reasonable to cache the dashboards.

The users can manually refresh if they desire

If we're concerned that we're caching for too long then we could have a shorter cache so someone flicking between a set of caches in  one session benefits
