### ISSUE TITLE
Separate identified users from anonymous users in /people

### ISSUE THREAD

**Issue by timgl** [PostHog/posthog#1292]
## Is your feature request related to a problem?

Currently our /people page is a very confusing list of both anonymous users with ugly UUIDs and logged in users.

## Describe the solution you'd like

I want 2 tabs (or some other solution!) where
1. users that are logged in (you can recognise them likely because they either have properties set, or because they have distinct IDs that don't look like UUIDs) and
2. anonymous users

## Describe alternatives you've considered

Manually see the difference between the two

**Comment by dynamoh** [comment]
@timgl can I work on this issue can you assign me this issue. I would love to work on it.

**Comment by yakkomajuri** [comment]
Hey @dynamoh, thanks for the interest! We do have a PR for this open already #1382 - but if this is an issue you want to help out with, you can help by reviewing it

**Comment by yakkomajuri** [comment]
Assigning myself as I should have done when I put out the PR weeks ago.
