### ISSUE TITLE
Bar chart does not correctly show percentages

### ISSUE THREAD

**Issue by StefanSilicon** [PostHog/posthog#12952]
## Bug description

*Please describe.*  
The `Value -> Bar chart` visualization does not provide useful percentage displays when the X-Axis unit is set to `Percent (0-100)`. Compared to this, the `Value -> Pie chart` shows proper percentages in relation to the full series.

![image](https://user-images.githubusercontent.com/114995641/203828887-f62cd65e-a3b5-4d0b-8946-fa582bd59ebb.png)
_Bar chart visualization_

![image](https://user-images.githubusercontent.com/114995641/203829138-db75673d-63ec-469d-88b7-567310785394.png)
_Same data, pie chart visualization_

## How to reproduce

1. Create new insight with a breakdown by a property  _(ensure breakdown segments have values of more than `100`)_
2. Set visualization to `Value -> Bar chart`
3. Set X-Axis mapping to `Percent (0-100)`
4. Observe values on single bars exceeding `100%`

## Environment

- [X] PostHog Cloud
- [X] self-hosted PostHog, version/commit: please provide

## Additional context
Originally reported on [slack](https://posthogusers.slack.com/archives/C01GLBKHKQT/p1669209655171939)

**Comment by mariusandra** [comment]
Hey @StefanSilicon, the axis mapping just changes the display of the value, in this case adding `%` symbol. 

Just today we were talking about adding an actual "percentage mode" to the visualizations, starting with the [just released area charts](https://github.com/PostHog/posthog/pull/12869), so watch this space.
