### ISSUE TITLE
[Query refactor] cache every query automatically

### ISSUE THREAD

**Issue by timgl** [PostHog/posthog#1295]
## Is your feature request related to a problem?

When navigating between different chart types the results load pretty slow. However for most of those charts having day-old data would be absolutely fine.

## Describe the solution you'd like

We should at least cache queries without any filters automatically for each team for 24 hours.

## Describe alternatives you've considered

Wait a long time

**Comment by EDsCODE** [comment]
I think this applies differently depending on the size of the product. If a user is using posthog for their product that has 100 users, realtime data makes much more sense. We could make it clear a user that they're retrieving stale data and give ability to force a refresh like on the dashboard.

**Comment by timgl** [comment]
I think it's fine to default to every 15 minutes for now, we can then make it configurable (maybe even automatically) later.

I suggest having a "last refreshed at X" with a refresh button on the charts so users aren't surprised.

**Comment by timgl** [comment]
To add to this: if we're doing this insights endpoint we should also offload doing the query to workers so we can poll for results. This way we can have queries that take longer than 30 seconds to run

**Comment by mariusandra** [comment]
To add even more: 

Is there any easy way to replace polling with [websockets](https://channels.readthedocs.io/en/latest/)? Both for this and for the live actions/events pages?

-- 

Slightly related (can post a new issue if needed later):

I ran into an annoying problem when coding [insights](https://github.com/mariusandra/insights). With bigger databases the queries would sometimes time out. 

While that's normal and to be expected, sometimes when running such such a long query, I would change the filter and thus trigger a new query. The old query would keep running in the background, hogging up the server. Running a few of them at the same time could lock up the entire database.

I needed some way to do query cancellation, but didn't get that far yet. With HTTP requests, query cancellation *could* be relatively easy, as in theory there exists a direct link between the pending or cancelled request and the postgres query... and cancelling the request could trigger the query to be abandoned as well.

However with websockets and with polling, this direct link breaks down and query cancellation needs to be handled manually. Probably by passing a UUID with the "start query" event and then sending a relevant cancellation event when the frontend agrees to discard the old query for whatever reason (changed filter, leaving page, etc).

**Comment by MrSaints** [comment]
Apologies for bumping a pretty old issue but totally agree with:

> I ran into an annoying problem when coding insights. With bigger databases the queries would sometimes time out.

If my understanding is correct, most of the insights are executed in foreground, and this can block the server, essentially taking it offline. For this reason, we've actually opted to serve a separate web deployment / service purely for ingestion.

I'm wondering if this can be moved to background or as already mentioned, have a way to cancel the query?

**Comment by mariusandra** [comment]
AFAIK all queries are now cached. As for query cancellation, alluded to [in this comment](https://github.com/PostHog/posthog/issues/1295#issuecomment-669835420), I made a separate issue to track this: https://github.com/PostHog/posthog/issues/4756
