### ISSUE TITLE
ClickHouse: Upgrade to latest LTS (22.8)

### ISSUE THREAD

**Issue by macobo** [PostHog/posthog#12967]
## Is your feature request related to a problem?

22.8 fixes https://github.com/PostHog/posthog/issues/12902 - measurably improving query performance

## Describe the solution you'd like

Upgrade to 22.8 on EU and US Cloud as well as in the chart default.

Upgrading requires:
- [x] Passing backend, E2E tests running against 22.8
- [x] Passing plugin-server tests
- [x] Increase supported version range, make `optimize_move_to_prewhere` default on on 22.8, off otherwise.
- [x] Create a PR for updating service_requirements.py
- [x] Updating playground, verifying behavior everything works
- [ ] ... additional steps done by infra team

Open questions:
- What versions will we support after starting to support 22.8. Shall we drop everything before 22.3?
- What version(s) shall we run PR tests on? 22.8 only?

## Additional context

cc @neilkakkar about the original issue, @pauldambra since this is performance-related work and @ellie as the person I'll be bothering on the infra side once above TODOs are done.

Previous upgrade ticket: https://github.com/PostHog/posthog/issues/7028

**Comment by pauldambra** [comment]
Agree we should run the fewest supported versions of clickhouse we can

Maybe run tests against 22.3 daily so we find out about problems but don't slow every PR

**Comment by macobo** [comment]
ClickHouse 22.8 is now extensively tested and we should be ready to roll it out on EU/US cloud. @ellie mind if I pass the buck to #team-infrastructure here?

To roll out 22.8:
- Merge https://github.com/PostHog/posthog/pull/12966 
- (Possibly on EU Cloud) Upgrade clickhouse.image.tag manually in values.yaml

Longer-term:
- Update default clickhouse image version with the next release. Note that this is a breaking change as CURRENT_VERSION does not support 22.8

Notes on how this was tested:
- All our tests (backend, e2e, plugin-server) passed on both 22.3 and 22.8
- I deployed 22.8 to playground (with `SKIP_SERVICE_VERSION_REQUIREMENTS` set), checked ingestion, plugins and all of insights/live events

**Comment by fuziontech** [comment]
I can help on US side since it’s still pretty bespoke

**Comment by ellie** [comment]
I've got this scheduled here: https://github.com/PostHog/posthog-cloud-infra/issues/842

Will be sorting it next sprint!

But would appreciate the help on US @fuziontech!
