### ISSUE TITLE
"We're unable to play this recording"

### ISSUE THREAD

**Issue by Vadorequest** [PostHog/posthog#12971]
## Bug description

*Please describe.*  

I cannot read some recordings, some of them works but others don't.
It's the first time I've noticed this.

![image](https://user-images.githubusercontent.com/3807458/204049892-145aadcb-b9b6-4078-b24b-7a3ef7f0fd31.png)

## Environment

- [x] PostHog Cloud

**Comment by alexkim205** [comment]
Hey @Vadorequest could you please send us a link to a session recording that is showing this error to help us troubleshoot? Thank you.

**Comment by Vadorequest** [comment]
@alexkim205 Here are a few:
- (4h ago) https://eu.posthog.com/recordings/recent?filters=%7B%22session_recording_duration%22%3A%7B%22type%22%3A%22recording%22%2C%22key%22%3A%22duration%22%2C%22value%22%3A60%2C%22operator%22%3A%22gt%22%7D%2C%22properties%22%3A%5B%5D%2C%22events%22%3A%5B%5D%2C%22actions%22%3A%5B%5D%2C%22date_from%22%3A%222022-11-07%22%7D#sessionRecordingId=184be7e7a25102-0ac497f39646c58-c525427-100200-184be7e7a2613e
- (7h ago) https://eu.posthog.com/recordings/recent?filters=%7B%22session_recording_duration%22%3A%7B%22type%22%3A%22recording%22%2C%22key%22%3A%22duration%22%2C%22value%22%3A60%2C%22operator%22%3A%22gt%22%7D%2C%22properties%22%3A%5B%5D%2C%22events%22%3A%5B%5D%2C%22actions%22%3A%5B%5D%2C%22date_from%22%3A%222022-11-07%22%7D#sessionRecordingId=184bdcf2fb2217-0c0f1a60a688ed8-c525427-100200-184bdcf2fb323e

The issue isn't gone, it's still ongoing.

**Comment by luchfilip** [comment]
same for me: https://app.posthog.com/recordings/recent?filters=%7B%22session_recording_duration%22%3A%7B%22type%22%3A%22recording%22%2C%22key%22%3A%22duration%22%2C%22value%22%3A60%2C%22operator%22%3A%22gt%22%7D%2C%22properties%22%3A%5B%5D%2C%22events%22%3A%5B%5D%2C%22actions%22%3A%5B%5D%2C%22date_from%22%3A%222022-11-27%22%7D#sessionRecordingId=1852a985a0d1299-0555b4e8b8bd338-1702397c-c0000-1852a985a0e314d

**Comment by daibhin** [comment]
We have improved the playback of replay considerably since this ticket was first reported. I am going to close it but feel free to reopen a new issue if any of the previous issues are still happening for your account
