### ISSUE TITLE
WAU/MAU don't work with aggregated Trends display modes

### ISSUE THREAD

**Issue by Twixes** [PostHog/posthog#12986]
## Bug description

When calculating Trends results with an aggregated (e.g. single output, like big number) display type, WAU/MAU don't work. This is because we have an `ACTIVE_USERS_SQL` query for time series display types, but we don't have a version of this for aggregated display types. (See ZEN-1043.)

## How to reproduce

1. Create an insight with a single WAU or MAU series.
2. Switch display type to "Number".
3. Open the "Debug ClickHouse queries" modal from the command palette.
4. See `COUNT(*)` instead of `COUNT(DISTINCT person_id)`.

**Comment by alexkim205** [comment]
Bumping priority of this issue with https://posthoghelp.zendesk.com/agent/tickets/1058. (moved to PostHog: https://us.posthog.com/project/2/support/tickets/3975) A few others have mentioned it as well in Slack

**Comment by mertdeveci5** [comment]
hey guys - is this issue fixed on your end? We still have the wrong numbers on WAU and DAU calcs

**Comment by Twixes** [comment]
Hey @mertdeveci5! We are working on this, the fix should be live within a day.

**Comment by Twixes** [comment]
We've just updated our querying engine to support this combination of options properly @mertdeveci5! Specifically, when using the Number display mode (or other non-time-series ones), we now calculate MAU/WAU for the end of the selected time range (which is usually the current point in time, except when using a fixed date range).
