### ISSUE TITLE
[Consolidate charts] improvements

### ISSUE THREAD

**Issue by timgl** [PostHog/posthog#1299]
Consolidated charts have been merged. Here are a couple of improvement points

- [x] Carry over property filters  (PR: #1302) 
- [ ] carry over Entities when you switch chart type
- [x] Would be great to do the "every time you change a chart it saves as a dashboard item" thing. This way we'll have history, we can have short urls, you can save charts and give them names without having to store them against a dashboard
- [x] Funnels should just be like any other chart type (rather than having to create a new one). Storing them as dashboard items will allow you to go look them up again.
- [x] #1283 

(Feel free to add more to this list)

**Comment by EDsCODE** [comment]
Do you think for history of charts it should be recorded on a per user basis or per team basis?

**Comment by timgl** [comment]
Users for sure!

**Comment by EDsCODE** [comment]
nearly all addressed. if carrying entities is still wanted we should open as separate issues. debatable that's it needed
