### ISSUE TITLE
More accurate session recording session durations

### ISSUE THREAD

**Issue by alexkim205** [PostHog/posthog#13044]
## Bug description

Session recording durations can be artificially inflated a user waits a long period of time before revisiting a page in the same session. Take this case for example:

- entered the site - Pageview
- left the site after 30 seconds - Pageleave
- entered the site after 30 seconds - Pageview
- left the site after 30 seconds - Pageleave

Session duration for this is: 30 + 30 + 30 = 90 seconds.
Actual user session: 30 + 30 = 60 seconds.

Today we calculate session durations from the difference between the first and last event seen in a given session, however we'd want to only include periods of time where the user is actively on a page.

## How to reproduce

1. Setup session recordings
2. Recreate above scenario
3. Observe that calculated recording duration is longer

## Environment

- [x] PostHog Cloud
- [x] self-hosted PostHog, version/commit: please provide

## Additional context

https://posthogusers.slack.com/archives/C01GLBKHKQT/p1668780500293839

**Comment by Aashish-Upadhyay-101** [comment]
hi, I want to work on this issue. Is this available?
if yes, can you please give a more details like where to look for solution, in which place of the code do I have to work in and stuffs like that. I'm intermediate in open source and need little assists.

**Comment by Aashish-Upadhyay-101** [comment]
@tiina303

**Comment by alexkim205** [comment]
Hey @Aashish-Upadhyay-101 really appreciate you volunteering to fix this! 

This bug is a bit complex since it deals with various parts of our system (client side posthog-js, clickhouse, etc.) and instead I would recommend starting out with issues that are labeled with the `good first issue` tag (https://github.com/PostHog/posthog/issues?q=is%3Aopen+label%3A%22good+first+issue%22+sort%3Aupdated-desc) to get familiar with our codebase.

**Comment by Aashish-Upadhyay-101** [comment]
okay then i will try some beginner friendly issues

**Comment by daibhin** [comment]
Filtering now supports active / inactive durations

<img width="753" alt="Screenshot 2024-02-13 at 14 48 55" src="https://github.com/PostHog/posthog/assets/6685876/0879b4ba-1dd7-4c38-b63c-5e841064d6e7">
