### ISSUE TITLE
Live events UI

### ISSUE THREAD

**Issue by yakkomajuri** [PostHog/posthog#13042]
We're building out a feature called "live events", which will essentially power what is now the "Live events" tab.

The idea behind this feature is to give users immediate feedback about them having sent events, to make onboarding and debugging easier.

Essentially, rather than only show events in the live events table that have been fully processed, we'll show events that are currently being processed as well.

This will take the time for events to show up on the table from up to 2 minutes down to a few seconds.

There are a few caveats though:

- The event may change while it's being processed
- The event may be dropped during the processing pipeline (e.g. by a plugin that deliberately drops events)
- We already highlight new events briefly in yellow on the live events table 

As such, we need a way to communicate to users that the event they're seeing is not ready yet, and may even disappear, without being too intrusive, since all events will probably go through this state.

Here's an example of what that looks like with just adding some shading for events in flight:

https://user-images.githubusercontent.com/38760734/204845221-7f1012b3-5175-47ba-b7cd-f0288399bfc3.mov

Also, we'll likely need a tooltip or some permanent message explaining what this means, given it's not as intuitive as the shading we use for newly-polled events.

Would love some thoughts on what this should look like!

cc @corywatilo 

-------

WIP PR: #13019

**Comment by corywatilo** [comment]
I put a few ways to call out events that are being processed in this wire. Is this helpful?

<img width="1661" alt="image" src="https://user-images.githubusercontent.com/154479/204952373-153c7f6c-a911-4ee6-b076-40ca5fe18059.png">

**Comment by yakkomajuri** [comment]
Thanks @corywatilo! will try some of this out
