### ISSUE TITLE
Bug: Cohorts randomly refreshing

### ISSUE THREAD

**Issue by joethreepwood** [PostHog/posthog#13045]
## Bug description

When I look at Cohorts, it keeps refreshing every few seconds. 

![2022-11-30 16 58 38](https://user-images.githubusercontent.com/84011561/204864131-03dc281f-6a9e-4279-a477-5ff991a54298.gif)

## How to reproduce

1. Go to cohorts.
2.
3.

## Environment

- [ ] PostHog Cloud
- [ ] self-hosted PostHog, version/commit: please provide

## Additional context

🤷

**Comment by EDsCODE** [comment]
Resolved for now. There was a faulty cohort
