### ISSUE TITLE
Dashboard layouts are buggy

### ISSUE THREAD

**Issue by alexkim205** [PostHog/posthog#13078]
## Bug description

Several users have reported buggy dashboard layouts. 

- [ ] Dashboard layouts aren't persisted when saved
- [ ] Dashboard layouts change randomly
- [ ] Duplicates/edits mess up formating.

## How to reproduce

I haven't been able to reproduce it locally or in cloud, but it seems like it's a widespread issue.

## Environment

- [x] PostHog Cloud
- [x] self-hosted PostHog, version/commit: please provide

## Additional context

https://posthoghelp.zendesk.com/agent/tickets/1081
https://posthoghelp.zendesk.com/agent/tickets/1061
https://posthoghelp.zendesk.com/agent/tickets/1115

**Comment by pauldambra** [comment]
see #13117

**Comment by pauldambra** [comment]
@andyvan-ph have you noticed this in recent days? 

Hard to reproduce so hard to know if I fixed it 😊

**Comment by andyvan-ph** [comment]
I haven't done much in dashboards this week. Will keep an eye out.

**Comment by pauldambra** [comment]
this is potentially any edit to an insight causing the problem

see https://github.com/PostHog/posthog/pull/13256

**Comment by pauldambra** [comment]
I believe this is fixed now, I'll close this and we can re-open if we need to
