### ISSUE TITLE
Posthog script hangs and blocks page load when used with Osano

### ISSUE THREAD

**Issue by hunterchristian** [PostHog/posthog#13073]
## Bug description

*Please describe.*  
*If this affects the front-end, screenshots would be of great help.*  

Hi team! We're attempting to initiate Posthog on our site (https://academy.metacrafters.io) and are seeing the script block the page load. We've removed the script for the time being, so you won't see it on our production site. I'm testing by loading the Posthog script via Tampermonkey for now.

Posthog loads just fine in our sandbox environment and locally. We're unsure of what could be causing the script to hang in our production environment, but suspect that it could be an interaction between Osano and Posthog. This is confusing though, since we also load Osano in our sandbox environment and haven't seen any issues.

## How to reproduce

1. Navigate to https://academy.metacrafters.io
2. Load our Posthog init script via Tampermonkey (api key redacted):
```
!function(t,e){var o,n,p,r;e.__SV||(window.posthog=e,e._i=[],e.init=function(i,s,a){function g(t,e){var o=e.split(".");2==o.length&&(t=t[o[0]],e=o[1]),t[e]=function(){t.push([e].concat(Array.prototype.slice.call(arguments,0)))}}(p=t.createElement("script")).type="text/javascript",p.async=!0,p.src=s.api_host+"/static/array.js",(r=t.getElementsByTagName("script")[0]).parentNode.insertBefore(p,r);var u=e;for(void 0!==a?u=e[a]=[]:a="posthog",u.people=u.people||[],u.toString=function(t){var e="posthog";return"posthog"!==a&&(e+="."+a),t||(e+=" (stub)"),e},u.people.toString=function(){return u.toString(1)+".people (stub)"},o="capture identify alias people.set people.set_once set_config register register_once unregister opt_out_capturing has_opted_out_capturing opt_in_capturing reset isFeatureEnabled onFeatureFlags".split(" "),n=0;n<o.length;n++)g(u,o[n]);e._i.push([i,s,a])},e.__SV=1)}(document,window.posthog||[]);
    posthog.init('API_KEY',{api_host:'https://app.posthog.com'})
```
3. Refresh the page and observe that the script blocks the interactivity of the page.

## Environment

- [X] PostHog Cloud
- [ ] self-hosted PostHog, version/commit: please provide

**Comment by alexkim205** [comment]
@hunterchristian Thanks for the bug report. I believe it had to do something with the PostHog recorder script being stuck in an infinite loop. Turning record sessions off from the PostHog web app seemed to fix the bug. It seems to be working on your end now (since you can now see a recording of me interacting with your website without it freezing up https://app.posthog.com/recordings/184cedb383c1ed-06c55e9d94859b-18525635-16a7f0-184cedb383d2b05). Please let me know if works on your end now.

**Comment by hunterchristian** [comment]
Thanks so much for your help @alexkim205 !

I was so excited to see your recording, since Posthog is going to be a huge productivity win for our product team.

Do I need to update anything on my end? I'm noticing that the site still hangs when I load the Posthog script via Tampermonkey with recordings enabled.

**Comment by hunterchristian** [comment]
Hey team! Is there anything that I can do I my end to take advantage of the bug fix? We're still seeing the behavior where the page load hangs on recorder.js.

**Comment by benjackwhite** [comment]
I just tried to take a deeper look here.
Recordings take advantage of the `MutationObserver` which listens for all changes on the DOM to record events and send them to us.

It seems like Osano is somehow listening to what is going on and making some sort of change which is what is causing the infinite loop.
1. PostHog recorder notices a mutation
2. Osano somehow reacts to that fact and (possilby) make a mutation
3. PostHog recorder notices a mutation
4. Infinite loop...

I'm not super familiar with how Osano works but it's definitely something in there...

I found this out by running 
```
(new MutationObserver(console.log)).observe(document, {
      attributes: true,
      attributeOldValue: true,
      characterData: true,
      characterDataOldValue: true,
      childList: true,
      subtree: true,
    });
```

Then loading PostHog using the PostHog bookmarklet (from Project Settings) with recordings enabled. Then I an infinite loop of mutation events triggered by the Osano CMP window (whatever that is).

Without more knowledge of what Osano is doing it's hard to say what can be done here unfortunately. I couldn't find any of their source code to look into further

**Comment by benjackwhite** [comment]
Just figured out what this is! Whenever we capture a mutation we modify a cookie which is used to store the active session info. This seems to be picked up by the Osano and for some reason Osano modifies their DOM elements which triggers a mutation and hence the loop...

This code can be added on your website in the console and it demonstrates the issue
```
(new MutationObserver(console.log)).observe(document, {
      attributes: true,
      attributeOldValue: true,
      characterData: true,
      characterDataOldValue: true,
      childList: true,
      subtree: true,
    });

let inject = document.createElement("script");
inject.src = "https://cdn.jsdelivr.net/npm/rrweb@1.1.3/dist/rrweb.min.js";
document.getElementsByTagName("head")[0].appendChild(inject);

inject.onload = function() {
  let events = [];
  let stopFn = rrweb.record({
    emit(event) {
      console.log("Mutation recorded!");
      if (events.length > 100) {
        // stop after 100 events to exist the infinite loop
        stopFn();
        console.log("Stopping!")
      }
      document.cookie = "events=" + JSON.stringify(events);
      events.push(event);
    },
  });
};
```

Unfortunately, I'm not sure what the solution is here. Recordings won't work well at all without cookies but if Osano is going to needlessly make DOM changes whenever any cookie changes.

One can run posthog with a different persistence approach that utilises localstorage as much as possible over cookies. This might be a good thing to try.

@hunterchristian Can you try initialising posthog with`persistence: "localStorage+cookie"` as [documented here](https://posthog.com/docs/integrate/client/js#persistence). I think that _could_ solve things.

**Comment by hunterchristian** [comment]
Thanks for the response @benjackwhite !

I tried initializing Posthog with `persistence: "localStorage+cookie"` as shown below, but we're still seeing the page hang :/

```
!function(t,e){var o,n,p,r;e.__SV||(window.posthog=e,e._i=[],e.init=function(i,s,a){function g(t,e){var o=e.split(".");2==o.length&&(t=t[o[0]],e=o[1]),t[e]=function(){t.push([e].concat(Array.prototype.slice.call(arguments,0)))}}(p=t.createElement("script")).type="text/javascript",p.async=!0,p.src=s.api_host+"/static/array.js",(r=t.getElementsByTagName("script")[0]).parentNode.insertBefore(p,r);var u=e;for(void 0!==a?u=e[a]=[]:a="posthog",u.people=u.people||[],u.toString=function(t){var e="posthog";return"posthog"!==a&&(e+="."+a),t||(e+=" (stub)"),e},u.people.toString=function(){return u.toString(1)+".people (stub)"},o="capture identify alias people.set people.set_once set_config register register_once unregister opt_out_capturing has_opted_out_capturing opt_in_capturing reset isFeatureEnabled onFeatureFlags".split(" "),n=0;n<o.length;n++)g(u,o[n]);e._i.push([i,s,a])},e.__SV=1)}(document,window.posthog||[]);
    posthog.init('API_KEY',{api_host:'https://app.posthog.com', persistence: "localStorage+cookie"})
```

**Comment by benjackwhite** [comment]
Hmmm in which case we might have to look again for an alternative. I can't guarantee this will be done anytime soon however as it's a very specific problem for this Osano tool and we have a lot of other priorities atm. 

For future reference to myself, we will have to see if it is possible to detect tools like this and somehow ignore their events (possibly not possible) or at least suppress them somehow.

**Comment by hunterchristian** [comment]
From a fellow engineer with a lot of priorities, I definitely understand.

I gave Smartlook a shot and it seems like their recording script finds a way to execute with Osano present if that helps at all.

**Comment by benjackwhite** [comment]
I verified this with another customer that Osano is an issue. Going to try and look into a fix now as this might affect other tools like this that do hacky things with cookies...

**Comment by benjackwhite** [comment]
@hunterchristian I have a fix up for posthog-js which _should_ fix this for Osano and any other tool that naively performs UI changes on reaction to cookies changing (even if the content doesn't change...).

Once that PR is merged and then the SDK update for Posthog Cloud, you should be able to test the fix.

**Comment by benjackwhite** [comment]
Closing this as it should be solved. Feel free to reopen if there are still issues
