### ISSUE TITLE
PostHog Cloud SQL access

### ISSUE THREAD

**Issue by joethreepwood** [PostHog/posthog#13128]
To fully support our technical users on PostHog Cloud, we need to allow them to ask any sort of question about their data that might not be fit for an interface. For this reason, we're working on a feature to allow direct SQL access to PostHog data, so that users may query it directly.

🗂 Considered goals

- Enable direct SQL access to data, through PostHog for PostHog Cloud

> Please note we have a separate issue for [SQL access on self-hosted deployments](https://github.com/PostHog/posthog/issues/12352).

[The Experimentation Team](https://posthog.com/handbook/small-teams/experimentation) will be leading this work. We'd love to hear user feedback, as well as ideas for stretch goals or implementation.

If you like this idea, please leave a 👍 or ❤️ reaction on this post to vote for it -- your votes and feedback help us prioritize what to work on next!

**Comment by jamesefhawkins** [comment]
We're making great progress here.

[This issue](https://github.com/PostHog/meta/issues/81) explains the todo list and a bunch of relevant PRs for those who are interested!

**Comment by jamesefhawkins** [comment]
this is available through [HogQL](https://posthog.com/docs/hogql), so I'm closing this out :)
