### ISSUE TITLE
PostHog in a year design work

### ISSUE THREAD

**Issue by lottiecoxon** [PostHog/posthog#13137]
Design work for the [PostHog in a year project ](https://github.com/PostHog/product-internal/pull/392)

### Context

7 Badges to describe our users based on their year in PostHog

- Popcorn muncher ( session recordings)
- Deep diver (insights)
- Flag raiser (feature flags)
- Scientist (experiments)
- Curator (dashboards)
- Champion (all 3 - feature flags, sessions, insights)
- Hedgehog ( just general exploration in the app)

**Comment by lottiecoxon** [comment]
## Inspiration 
Spotify wrapped

<img width="622" alt="Screenshot 2022-12-06 at 10 43 09" src="https://user-images.githubusercontent.com/65415371/205949769-c5590aff-2ad3-4ebc-935f-1d3f0ef596ab.png">

## Drafts:

### First draft 

- too large 
- too many badges and clickable moments
- running before we can walk 
- but a good start + fun exploration of names

![dashboards v2 - global range](https://user-images.githubusercontent.com/65415371/205950517-bd8fb150-e83d-4d0d-bb68-2940c6018051.png)

### Second draft 

- all fits into one screen/pop up
- adding in stats (but could be confusing to implement)
- with shareable options

![Frame 9574](https://user-images.githubusercontent.com/65415371/205951079-2a3a8eea-650d-4fae-a202-e4f6f743c5c6.png)

### Third draft - open graph 

- Basing the pop up on the open graph modal
- Label added 
- One highlighted statistic 
- A Year in review label 
- debating between two colour-ways, a lighter more on brand version and a darker more colourful (bold) version. 

![sessions](https://user-images.githubusercontent.com/65415371/205952178-fc6dc59f-fb65-41e7-8ab3-d6216d2d3f2f.png)


![sessions (1)](https://user-images.githubusercontent.com/65415371/205952168-e470cdfb-5225-4c97-b309-cf45aa548624.png)

### Third draft - pop up 

![sessions (1)](https://user-images.githubusercontent.com/65415371/205953878-3ea4a383-506f-42ce-87df-6cf84a4135b8.png)

## Categories

![Frame 9596](https://user-images.githubusercontent.com/65415371/205954582-5349c547-f822-47d3-be0b-5b1b43d3f965.png)

**Comment by joethreepwood** [comment]
Not sure if you're looking for feedback here @lottiecoxon, but second draft is my favourite for appearing in-app. Not a super strong opinion though.

**Comment by Twixes** [comment]
This looks super cool. Quick feedback from a glance:
1. We should probably use a neutral flag instead of the EU one 😅 (might be just a draft thing though)
2. I'd suggest the UI of My Year in PostHog to be full-page overlay (with a back button), instead of embedded as a page, since the regular navigation UI kind of takes away from the effect. (Probably why Spotify has always kept Wrapped as a separate page and now it's a Stories-type experience on mobile)
3. The plain "Hedgehog" badge is so sad. 😂 It's like "you're the most basic user we have".

**Comment by neilkakkar** [comment]
I second Joe (weakly) & Michael (strongly)! Very cool Lottie :D 

For the "basic" hedgehog badge, I'd propose an alternate idea where we're _somewhat_ digging at them vs giving them a basic award.

The core idea: Hedgehogs hibernate in the winter! So, it's the "Hibernation" badge!

With text something like: "Did you know that Hedgehog's hibernate from October to March? Sounds like you've been hibernating too."

^but a lot more funny/punchier.

**Comment by neilkakkar** [comment]
Also relevant google search:

> A hibernating hedgehog will be completely rolled up into a tight ball with no face visible.

**Comment by pauldambra** [comment]
> "you're the most basic user we have".

Well, that's the copy nailed 🤣

**Comment by lottiecoxon** [comment]
1. EU flag was totally a place holder for when I could minus the stars (all good there)
2. Happy to do a full page take over 
3. The plain hedgehog is indeed very sad - I do like @neilkakkar idea for the hibernator but maybe that is a little too far...?

My question is if we did do a full page take over wouldn't we need a little more data ?

**Comment by joethreepwood** [comment]
> 3. The plain hedgehog is indeed very sad - I do like @neilkakkar idea for the hibernator but maybe that is a little too far...?

We could change it to astronaut? "Because there are no small steps when it comes to your data."

**Comment by jamesefhawkins** [comment]
no more presents until next year
