### ISSUE TITLE
Feature flag support for Strings

### ISSUE THREAD

**Issue by MarkLyck** [PostHog/posthog#13144]
## Is your feature request related to a problem?

I'm trying to migrate from LaunchDarkly but the current limitations with feature flags in PostHog is making that very difficult. The biggest of which is being unable to have a feature flag as a `String` or `JSON` 

I have tried the Multivariate flags which allows a feature flag to be a "key", but that "key" is very limited. For example I'm not able to put a URL as a key because it violates some special key requirements.

Same issue with stringified JSON

## Describe the solution you'd like

Allow multivariate feature flags (or any type of feature flag) that can hold a value such as a String.

## Describe alternatives you've considered

Alternatively make a new feature flag type that can hold a value, similar to how FlagSmith does it.

**Comment by weyert** [comment]
Yeah, this would be great to have

**Comment by mariusandra** [comment]
I'm really not sure why we have these requirements.

I mean... I even had to hack around this to [store JSON as base64 encoded multivariate keys](https://github.com/PostHog/notification-bar-app/blob/f258ee29f67ae97aa76b972d2c4210e173fa5548/frontend.tsx#L119) just to get around this ridiculous limitation :D.

I don't think there will be much friction to merge something like that if someone comes up with a PR... 🤔

**Comment by weyert** [comment]
@mariusandra  Do you have any tips, which changes would be necessary to accomplish this?

**Comment by neilkakkar** [comment]
There's no limitation on the backend @weyert , the API accepts any strings, so would mean going into the form and removing the condition here: https://github.com/PostHog/posthog/blob/master/frontend/src/scenes/feature-flags/featureFlagLogic.ts#L185 & then testing it works well.

This should work pretty well for basic strings. We're planning a bigger chunk of work for Q1 to allow arbitrary JSON payloads

**Comment by wallinslax** [comment]
I think it is a good practice to keep feature flag as toggle for simplicity.
Instead, treating string flag as structuralized feature flags might be a good direction.

For example:

instead of
```
if color == 'yellow':
  # do task 1
elif color == 'green':
  # do task 2
elif color == 'red':
  # do task 3
```
we can do
```
color = 'yellow'
isRed, isGreen = getFlags(color)
if isRed and isGreen:
  # do task 1
elif isGreen:
  # do task 2
elif isRed:
  # do task 3

```

**Comment by EDsCODE** [comment]
Hey all! The first iteration of this has been released and is currently in beta with posthog-js/posthog-node support. Payloads are configurable for both boolean flags and multivariate flags. 

Please send me an email at eric@posthog.com with your Posthog Cloud email if you want to give it a try!

**Comment by neilkakkar** [comment]
This is now available for general availability now
