### ISSUE TITLE
Mark feature flag as temporary or permanent

### ISSUE THREAD

**Issue by MarkLyck** [PostHog/posthog#13146]
## Is your feature request related to a problem?

I'm trying to migrate from LaunchDarkly to PostHog.

One feature I'm missing is the ability to mark a feature flag as "temporary" or "permanent", to make cleanup and management of flags much easier.

## Describe the solution you'd like

Ability to Mark flags as temporary when you intend to remove them after releasing a feature. This lets you find and scrub those flags with ease.  

Ability to Mark flags as permanent when keeping them in your code long-term. Use them for operational things like disabling non-essential features during a spike in traffic.

**Comment by benjackwhite** [comment]
Thought about this before. could be good to have a generic "label" with some sensible defaults like `[experiment, devtool, rollout]` or something. That way users can decide what labels are most useful to their workflows.

**Comment by weyert** [comment]
There is a different ticket to add a end date to a feature flag I think this might over lap with this one

**Comment by liyiy** [comment]
I'm sure there's more we can even do here to make it as convenient as possible to remove and clean up flags but for now you should be able to tag your feature flags as "temporary" or "permanent" 😄
