### ISSUE TITLE
Stickiness doesn't seem to work for individual events

### ISSUE THREAD

**Issue by timgl** [PostHog/posthog#1314]
## Bug description

Filtering by a specific event only gives results for the first day ([INTERNAL LINK](https://app.posthog.com/insights?interval=day&actions=%5B%5D&events=%5B%7B%22id%22%3A%22Toolbar%20Button%20Mode%22%2C%22name%22%3A%22Toolbar%20Button%20Mode%22%2C%22type%22%3A%22events%22%2C%22order%22%3A0%7D%5D&new_entity=%5B%5D&shown_as=Stickiness&date_from=-30d&properties=%5B%5D))

## Expected behavior

Stickiness should work over multiple days.

## How to reproduce

1. Go to insights
2. Select an event
3. Only the first day has results

## Environment

- PostHog cloud or self-managed?
 Both
- PostHog version/commit
1.12.0

**Comment by mariusandra** [comment]
This should be fixed by #1322. I was mistakenly just setting the `email` property of the user, hoping that would link up unique distinct ids. It doesn't. I now set the proper `user.distinct_id`.
