### ISSUE TITLE
Retention insight appears too large in dashboard

### ISSUE THREAD

**Issue by pjhul** [PostHog/posthog#13148]
## Bug description

In [this dashboard](https://app.posthog.com/dashboard/56335) I just created, I noticed that one of the retention insights I embedded ends up taking up too much space. At first, I tried resizing the insight, which worked for a period of time, but once I returned to the dashboard later it seems that the issue showed up again.

<img width="1261" alt="Screen Shot 2022-12-05 at 12 29 33 PM" src="https://user-images.githubusercontent.com/39424187/205736996-059c1529-620a-4f43-a870-2897f87f811b.png">

This _may_ have something to do with needing to accommodate the larger size taken up for insights with larger number of cohorts? (This example only has 5 cohorts, and for larger numbers there's much less wasted space)

## How to reproduce

1. Create a dashboard
2. Add a retention insight

## Environment

- [x] PostHog Cloud
- [ ] self-hosted PostHog, version/commit: please provide

## Additional context

cc: @pauldambra as the dashboard maestro 🧙 

#### *Thank you* for your bug report – we love squashing them!

**Comment by pauldambra** [comment]
Hmmm, tricky... the default size is larger because the default retention chart is large.

It's even worse because the chart is centered in the space 🤔
