### ISSUE TITLE
Sprint 1.43.0 2/2 - Dec 12 to Jan 6

### ISSUE THREAD

**Issue by timgl** [PostHog/posthog#13166]
# Global Sprint Planning

## 3 things that might take us down

1. Rate limiting and limits on pagination
2. 
3.

## Retro: Status of Outcomes from Previous Sprint

1. migrate billing v1 users to v2 (important) @kappa90 > done by end of week
1. continue working on onboarding improvements (design, better tracking, add more ingestion options) @raquelmsmith < did not touch this because of billing page, hopefully done this week
1. Recording (Comments) / Notes @benjackwhite > ditched this in favour of static playlists
1. "Static" Playlist items long term storage @alexkim205 > Coming along, impacted by support hero
1. Data exploration: First steps live + drill down views (@mariusandra and @thmsobrmlr ) > done and on track
1. Data integrity: persons on events + user experience component (@macobo & @Twixes) > Didn't need to touch this so focussed on performance instead. Components will go into next sprint.
1. Performance: hit fewer queries from the dashboard, caching, query cancellation @pauldambra > Deploying at the moment.   
1. Analyze and root cause issue impacting potentially 3% of events with events having the incorrect person attributed to the event. Confirm that scope and reach of this issue and find root cause. @tiina303 > we have a plan to re-enable it for people who aren't impacted. Continue into next sprint for the rest
1. Permissions beta testing & UI Polishing @liyiy > Done, great feedback from customers, gathering more users for testing
1. https://github.com/PostHog/product-internal/issues/386 fixing @EDsCODE > Fixed some of these, then changed it to fixing backing tables behind cohorts.
1. We have improved monitoring this sprint, but are yet to improve our alerting @guidoiaquinti > A bit, not complete. Carrying over
1. Productionize internal metabase + shift to Tailscale internally @ellie > Testing tailscale now so basically finished. 

## Retro: What can we do better next sprint?

1. More mindful to set aside for firefighting
2. Having two engineers in the same team on support hero
3. Pricing changes: Raquel or Em should work directly with Cory on these

## Support hero this sprint

Week 1: Tim
Week 2: Neil
Week 3: Karl
Week 4: James G

## Plan: Proposed Goals for Next Sprint 

Each goal should have a single owner. Owner can only be an engineer.

1. Data exploration: insights in the new system @thmsobrmlr & @mariusandra (tables cont, insights help)
why? prerequisite for posthog 3000
1. Yeet AntD from all insights-related components, building a few replacements @Twixes
why? To do 3000 we'll need to customize most components + removing cruft
1. Performance: @macobo create new tooling for benchmarking and exposing pain, validate moonshot alternative schema (posthog with no sharding). https://posthog.slack.com/archives/C0368RPHLQH/p1670363579097329 for more context
why? dashboards are slow, p95 is 40 seconds for big customers
1. Web Performance - @pauldambra Paul & Ben fun time in Lisbon. Data Exploration in, Web Performance out.
why? Lots of requests for network requests
1. Make growth team happy running experiments: https://github.com/PostHog/posthog/issues/10426 > @neilkakkar 
why? if they're happy others will be happy
https://github.com/PostHog/posthog/issues/13147 fixing > @EDsCODE 
Why? Cohort usability bugs had several issues that could use reconciling cohort backing tables (Static user deletion, cohort by groups)
1. persons-on-events @hazzadous
why? really impacts performance
2. snowflake re-enabling @fuziontech
why? exports should fail gracefully on historical exports
1. performance on capture @xvello
why? because we're spending a lot on compute
1. data integrity problems for priority customers @tiina303
why? we want customers to trust our data
1. "Pinned recordings" to S3 finalisation @alexkim205
why? - remaining thing to make playlists "feature complete"
1. Network logs alpha @benjackwhite
why? - highly requested engineering-focused feature. Take advantage of Paul's brain in Lisbon
1. Infra hero, see [the board](https://github.com/orgs/PostHog/projects/72/) for work planned @ellie
why? Lots of ongoing stuff
1. Look deeper into AWS costs and find low-hanging fruits to reduce the cost @danielxnj
why? Our costs have been increasing and can't increase at the rate as it's been going now
1. Have the plan to spin up a new automated ClickHouse cluster on the US AWS account, and replicate to it @danielxnj
why? Make sure everything is infra as code and so we're not paying for cross account traffic
1. Improve new billing page further to recover lost conversion rate @raquelmsmith
why? because conversion dipped a lot
1. Support work to be able to launch new pricing with PostHog Lite / Scale / Enterprise @kappa90
why? So we can iterate on our pricing

# Team sprint planning

For your team sprint planning copy this template into a comment below for each team.

```
Team ___

## Retro

<!-- Talk about what went well, what didn't go well and any actions to improve next time -->

- 

## Hang over items from previous sprint

<!-- For each item, decide to re-prioritise (and add below) or deprioritise -->

- Item 1. prioritised/deprioritise

## Planning

<!-- Each item should have a single owner. Owner can only be an engineer. -->

### High priority

-

### Bugs

-

### Low priority / side quests

-

```

**Comment by mariusandra** [comment]
## Team Product Analytcs

Retro

- Data exploration: First steps live + drill down views (@mariusandra and @thmsobrmlr )
why? users find it hard to explore data
--> **first steps live, drilldowns in progress**

- Data integrity: persons on events + user experience component (@macobo & @Twixes )
why? Data integrity is # 1 priority
--> pitched in with #team-pipeline at the start, they have it covered now. UX is in works by michael.

- Performance: hit fewer queries from the dashboard, caching, query cancellation @pauldambra
why? p95 of large customer performance is 18 seconds
--> Reduced load from dashboards significantly, property filters are faster, caching improvements will go live soon, query cancellation also nearing completion. On the way also fixing a bunch of bugs with dashboards. :)

----
@pauldambra in Lisbon with Ben at week 1

Possible rollover:
- Pivot tables

Sprint goals
- Data exploration: insights in the new system @thmsobrmlr & @mariusandra (tables cont, insights help)
- Yeet AntD from all insights-related components, building a few replacements @Twixes 
- Performance: @macobo create new tooling for benchmarking and exposing pain, validate moonshot alternative schema (posthog with no sharding). https://posthog.slack.com/archives/C0368RPHLQH/p1670363579097329 for more context
- Web Performance - @pauldambra Paul & Ben fun time in Lisbon. Data Exploration in, Web Performance out.

**Comment by EDsCODE** [comment]
Team Experimentation
---

Hang over items from previous sprint
- usability bugs https://github.com/PostHog/product-internal/issues/386

Planning
---

1. Experiments UX https://github.com/PostHog/posthog/issues/10426
2. [Cohort table revamp](https://github.com/PostHog/posthog/issues/13147) fixing
Why? Cohort usability bugs had several issues that could use reconciling cohort backing tables (Static user deletion, cohort by groups)

**Comment by fuziontech** [comment]
# Team Pipeline

## Availability

- jams is out first week and early next week
- tiina off second week


## Retro

Tiina
- Great to have Xavier on the team (someone I can work with in person + more hands) & onboarding seems to be going well
feeling overwhelmed with juggling too many things, prioritizing onboarding & persons-on-events, which was the right decision imho, but feeling bad about not having gotten back to our priority customers with their data problems, oh yes fires too...

Xavier:
- Onboarding was very smooth, deployed to prod on my first day, I feel like I’ve been around more than a month already. Great to have Tiina close, and everyone has been very responsive
- Great dev experience, let’s keep it that way 💪
- Observing conflicting efforts, which confuses me when I try to understand the target. Example: conflicting views on scope of the capture endpoint: 12802 (removing team_id resolution at capture) versus 13019 (live events) and 13174 (posthog_event_seen_for_team)

Jams:
- Fires! Helping out a number of customers like zipari with their setup in an effort to get them to be more in line with a standard deployment
- Got caught up with a few other irons in the fire from Yakko time
- Still a ton to do and so little time.

Harry
- Please to get the distributed scheduler jobs in
- Sad that we still have KafkaTables, but very happy with [Xavier Vello](mailto:xavier@posthog.com) s input on this :star:
- Looking forward to getting person on events out. Loving the detail that Tiina has put in
- Excited to go through details on Friday

Luke
- feel like persons-on-events has been messy, Tiina's done a good job leading that

## Hang over items from previous sprint

- P0 - Person on event
- P0 - Snowflake investigation ❄️ 

## Planning
- persons-on-events @hazzadous 
  - live events - could be shipped this week
  - buffer changes - easy
  - enabling it for teams with <0.05% & anyone asking
- snowflake re-enabling @fuziontech 
  - single export shouldn't be able to kill everything
- performance on capture @xvello 
- data integrity problems for priority customers @tiina303

**Comment by benjackwhite** [comment]
# Team ~Support Hero~ Recordings

## Retro

Both devs on support-hero was not ideal...

## Hang over items from previous sprint

- Recordings notes - de-prioed due to feedback on playlists
- Static playlist item saving to S3 - ongoing

## Planning

1. "Pinned recordings" to S3 finalisation @alexkim205 
why? - remaining thing to make playlists "feature complete"
2. Network logs alpha @benjackwhite 
why? - highly requested engineering-focused feature. Take advantage of Paul's brain in Lisbon


### High priority

-

### Bugs

-

### Low priority / side quests

-

**Comment by ellie** [comment]
# 🚀 Team Infrastructure 🚀 

## Retro

@danielxnj: The sprint went well; we managed to finalize what we planned, and I also started getting some exposure to the support issues.
@ellie: Overall the sprint went OK, had some time to focus and get things sorted which was nice. Looking forward to seeing how/if infra hero works out next sprint

### Infra hero
We will be having a support rotation on our team for who handles supporting other teams or customers. Please ask for help in #support-infrastructure!

Our current plan for work is listed here: https://github.com/orgs/PostHog/projects/72/

## Planning

- Infra hero @ellie
  - see the board for work planned

- Look deeper into AWS costs and find low-hanging fruits to reduce the cost @danielxnj
- Have the plan to spin up a new automated ClickHouse cluster on the US AWS account, and replicate to it @danielxnj
- Build an ARM image for PostHog @guidoiaquinti

**Comment by kappa90** [comment]
# Team Growth

## Retro
- Finalizing migration to v2 for cloud users
- 2 experiments running well (secondary onboarding, new billing page)
- New onboarding with demo env unreleased as buggy, working on it
- Released customer.io integration compatible with in-app prompts

## Hang over items from previous sprint
- Release onboarding v2 with new demo
- Release new pricing change with PostHog Lite / Scale / Enterprise

## Planning
- Release onboarding v2 with new demo

### High priority
- Improve new billing page further to recover lost conversion rate @raquelmsmith 
- Support work to be able to launch new pricing with PostHog Lite / Scale / Enterprise @kappa90
