### ISSUE TITLE
Feature Flag Environments to make testing easier

### ISSUE THREAD

**Issue by neilkakkar** [PostHog/posthog#13160]
## Is your feature request related to a problem?

*Please describe.*

When using feature flags, I'd love to have a test environment, so I can test everything works without polluting my prod feature flags.

## Describe the solution you'd like

Have an option to choose the environment, and sync feature flag definitions between different environments.

## Describe alternatives you've considered

Create multiple flags / projects and test them separately, and hope the same changes can reflect in the main prod project

#### *Thank you* for your feature request – we love each and every one!

> [This feature is on our roadmap. ](posthog.com/roadmap)If you like this idea, please leave a 👍 or ❤️ reaction on this post to vote for it -- your votes and feedback help us prioritize what to work on next!

**Comment by weyert** [comment]
This would be brilliant! Lot's hedgehog emojis

**Comment by joesaunderson** [comment]
Massive +1 for this

**Comment by dbartholomae** [comment]
I think that this is the only missing feature for us to be able to move to PostHog Feature Flags

**Comment by richardeinhorn** [comment]
manually keeping feature flags in sync across different envs is tedious and prone to errors - would love to be able to either keep them on 'auto-sync' or 'push feature flags' from dev -> prod projects in PostHog

**Comment by mikahFSmusic** [comment]
We're beginning to use Posthog for a lot of our analytics work -- we'd like to move our entire feature flagging system to posthog but would need to be able to sync flags between projects first. Echoing @richardeinhorn, syncing the flags has proven to be very frustrating so far. We'd love this feature as soon as it's ready!

**Comment by jurajmajerik** [comment]
@weyert @joesaunderson @dbartholomae @richardeinhorn @mikahFSmusic 

I’m thrilled to share we’re rolling out multi-project feature flags this week! If you’d like to be among the first users to try them out, please drop me an email at juraj (at) posthog com - I’ll enable the feature for you right away. Looking forward to your feedback!

**Comment by lsmith77** [comment]
awesome. we have moved our staging env to another org, since there is not yet a way to limit events by project and we had some bugs in staging builds generate millions of events.

so from our point of view it would be better to have a way to export/import. in part because we also want to have different settings between staging and production.

f.e. we currently have a feature flag to ask the user for a sales call. in production we might want to trigger this after 50 actions .. in staging we might want to trigger it after 5.

**Comment by neilkakkar** [comment]
this is now ready for everyone! :)

**Comment by kbberker** [comment]
@neilkakkar - can you please share how we can access this feature? 

I can't find anywhere in the docs on how to achieve this. I found this issue from this tutorial page [How to setup PostHog for multiple environments (development, staging, production)](https://posthog.com/tutorials/multiple-environments), which still suggests it's not ready.

[Also this question page](https://posthog.com/questions/enhance-how-feature-flags-are-shared-between-projects) also seems to suggest that multiple project feature flags aren't ready yet. 

This would be a great feature to have, as others have already stated!

**Comment by neilkakkar** [comment]
Hey @kbberker , here are the docs: https://posthog.com/docs/feature-flags/multi-project-feature-flags - I'll update the questions too!

**Comment by neilkakkar** [comment]
The first link is correct since an overall environments system isn't ready yet, but there is something for flags now

**Comment by kbberker** [comment]
Thanks so much for the quick reply and the docs link! Totally missed that link on the feature flags doc page!
