### ISSUE TITLE
Ingestion / connect product step of onboarding shows outdated instructions for React Native

### ISSUE THREAD

**Issue by dansimau** [PostHog/posthog#13173]
## Bug description

I just signed up with a new account and selected my app as React Native. It gave me these instructions, which turned out to be wrong:

<img width="1393" alt="Screenshot 2022-12-06 at 23 38 40" src="https://user-images.githubusercontent.com/203031/206039337-b5b71077-e30f-494a-9d29-71e3793e0d28.png">

I found the correct instructions here:
https://posthog.com/docs/integrate/client/react-native

**Comment by benjackwhite** [comment]
Ah great catch! I'll set up a fix..
