### ISSUE TITLE
Error when creating a new experiment after creating an insight

### ISSUE THREAD

**Issue by annikaschmid** [PostHog/posthog#13180]
## Bug description

*Please describe.*  
Sometimes there is a bug/error when you try to create a new experiment. @Cameron and @Luke Harries have been experiencing this as well. This looks pretty bad.

Error message: `We've registered this event for analysis (ID c0b78dbb4fea4caeb747d90e41417b95), but feel free to contact us directly too.`

## How to reproduce

1. Create and save an insight
2. Navigate to Experiments
3. Click “New Experiment”
4. Error appears

## Environment

- [x] PostHog Cloud
- [ ] self-hosted PostHog, version/commit: please provide

## Additional context

![Screenshot 2022-12-07 at 11 38 54](https://user-images.githubusercontent.com/14750837/206170072-95f8e36a-70aa-413c-a4c2-85ae73611934.png)

**Comment by neilkakkar** [comment]
This should be fixed now!
