### ISSUE TITLE
Recording notes (annotations)

### ISSUE THREAD

**Issue by benjackwhite** [PostHog/posthog#13184]
## Is your feature request related to a problem?

When working with recordings it's often helpful to add notes to them for future reference, sharing with the team and to remember which recordings were of interest when you return.

## Describe the solution you'd like

Allow the addition of notes to a recording. This could be a free text field that allows some simple markdown-esque notes with the ability to add links to specific points in the recording.

Perhaps when you start editing the note it will prefill with a link to the current timestamp to help future users get to the point of interest.

In addition I'd like to see all recordings that have notes, perhaps in it's own tab or via filters. That way it is easy to skim through all the notes being added by my team.

## Describe alternatives you've considered

**Comments**
Allow commenting at specific points on the seekbar area. Not sure if this is as good an idea as it feels much more complex whilst also harder to skim read content.

#### *Thank you* for your feature request – we love each and every one!

> [This feature is on our roadmap. ](posthog.com/roadmap)If you like this idea, please leave a 👍 or ❤️ reaction on this post to vote for it -- your votes and feedback help us prioritize what to work on next!

**Comment by annikaschmid** [comment]
I think to start with, we should support the following functionality:

1. Add a new comment (every comment should be attached to a timestamp I think, or we should have the same checkbox we have for sharing a link, all other comments are 'attached' to 00:00)
2. Being able to view comments on a recording at the relevant time stamp
3. View all comments, can be done in a new tab like Ben proposed. I also want to see which recording this comment belongs to (link) and who has created the comment

**Nice to have's**
1. Respond to a comment
2. Share a comment via link
3. Tag comments

Maybe something like the annotations UI is a good starting point: https://app.posthog.com/annotations

**Comment by pauldambra** [comment]
this is in notebooks now
