### ISSUE TITLE
Weird recording of iframe screen

### ISSUE THREAD

**Issue by Aagam-Pragma** [PostHog/posthog#13189]
There is an iframe embedded in a website and while there is no recording of that particular person's movements or clicks and it doesn't also show any kind of UI design. I mean the css part is also not reflected only the base HTML is shown on the screen. 

## How to reproduce
1. Embed an iframe in any website
2. Inject posthog in it and start screen recording option in it

This is a how the login page looks in recording without any kind of css and movements inside of that iframe cannot be seen. We can see only cursor moving in the video and no other screen changes happen though the contents of iframe change

![Screenshot from 2022-12-07 20-12-21](https://user-images.githubusercontent.com/120033175/206211201-528e684d-6524-45cb-ba72-8b6a1c98ddc2.png)

**Comment by benjackwhite** [comment]
Hard to say what is going on here without some more context. Do you have a link to the recording you can share with me (if you are on cloud) and I can take a deeper look.

Iframes in general are hard to record due to browser security limitations but if you have injected it in the iframe I imagine it _could_ work...

**Comment by Aagam-Pragma** [comment]
I do have a few posthog links. Posting them here

1. [https://app.posthog.com/events#sessionRecordingId=184ed51ed15c6-0f4df7551d7ce7-713f2312-61830-184ed51ed16278](url)
2. [https://app.posthog.com/person/9353941816#activeTab=events&sessionRecordingId=184ed4e9e8520-0ca476e489237f-56697d58-46500-184ed4e9e861ad](url)

**Comment by Sagie501** [comment]
> Hard to say what is going on here without some more context. Do you have a link to the recording you can share with me (if you are on cloud) and I can take a deeper look.
> 
> Iframes in general are hard to record due to browser security limitations but if you have injected it in the iframe I imagine it _could_ work...

What do you mean by "inject it in the iframe"? Inject what?
I'm also having some issues with recording my iframe - in my case it doesn't show the iframe just blank space instead. The iframe source is on the same domain as the main site. There are several frames on the recording that I'm able to see the iframe content and then it disappears.

**Comment by Aagam-Pragma** [comment]
@Sagie501 I mean add the posthog script in your iframe and just an FYI my iframe source has a different domain than website domain. So when I look at the recording the cursor/user movements are not recorded and neither is my screen recorded as expected.

**Comment by pauldambra** [comment]
closing as out-dated. feel free to re-open if need be. 

we have up-to-date iframe recording docs here https://posthog.com/docs/session-replay/iframes
