### ISSUE TITLE
'first seen' column in /people isn't correct

### ISSUE THREAD

**Issue by jamesefhawkins** [PostHog/posthog#132]
**Describe the bug**

The first and last seen column were originally working, but currently seem to display no difference in time, at least for certain users.

**To Reproduce**
1. Go to /people
2. Look at the 'first scene' column
3. Click into some users - repeat users will have come from "first sce

**Expected behavior**
First seen should track since the user first logged into the system, not when they most recently accessed it.

**Screenshots**

![Screenshot 2020-02-19 at 17 44 42](https://user-images.githubusercontent.com/47497682/74892983-0da2b200-5340-11ea-85a0-e059cbaf228f.png)

Some of these users have event history going back days, when you click into their profile.

**Desktop (please complete the following information):**
 - OS: OS X
 - Browser Chrome

**Comment by timgl** [comment]
I've deleted this column for now as it's hard to make this work correctly
