### ISSUE TITLE
Autocapture action insights not working

### ISSUE THREAD

**Issue by ajsharp** [PostHog/posthog#13254]
## Bug description

Actions created from an autocapture event appear to be broken -- they do not capture future events that occur and should match. When I try to build an insights chart from them, no data shows up. However, if I build an insights chart from the autocapture event directly, data does show up.

Note: posthog js snippet is being included via google tag manager.

Here's an example of an action created from an event, which does not work:

![CleanShot 2022-12-10 at 14 56 56@2x](https://user-images.githubusercontent.com/12774/206878464-ff0e778e-d244-4739-a19d-be6a466705de.png)

An insight created from that action, no events matching:

<img width="1197" alt="CleanShot 2022-12-10 at 14 58 25@2x" src="https://user-images.githubusercontent.com/12774/206878486-35407003-7257-4212-9400-74bf5753e024.png">

Creating an insight from the raw autocapture events, same filtering, works:

![CleanShot 2022-12-10 at 15 00 13@2x](https://user-images.githubusercontent.com/12774/206878535-96df07dd-87f8-4a88-8097-c4d1ab119bb2.png)

## How to reproduce

1. Create an action from an autocapture event, such as clicking a button
2. Create an insight from that action
3. Insight does not have any actions in it

## Environment

- [x] PostHog Cloud

## Additional context

I have a loom video I can share privately that shows the issue.

**Comment by timgl** [comment]
Hey Alex, Sorry for the late response here.

It's annoyingly subtle, but in the action you used "`" rather than "'" in Let's, hence this didn't match. I suggest using the PostHog toolbar instead to create actions as it'll be more accurate.

**Comment by ajsharp** [comment]
Thanks @timgl. Unfortunately I don't think this is an issue with the apostraphe -- I'm seeing this on normal insights created directly from the events feed for clicks that don't have apostraphes

**Comment by pauldambra** [comment]
Hey @ajsharp, I just created an action that I think is setup the same way and I could track past events, and new ones I caused.

Can you send a link to the action so I can take a look? You can mail paul@posthog.com or [join our community slack](https://posthog.com/slack) and send in a DM there, thanks 🙌

**Comment by mariusandra** [comment]
Just to add, I do see a different apostrophe in the manual search (it's tilted)

![](https://user-images.githubusercontent.com/12774/206878535-96df07dd-87f8-4a88-8097-c4d1ab119bb2.png)

versus in the action:

![](https://user-images.githubusercontent.com/12774/206878464-ff0e778e-d244-4739-a19d-be6a466705de.png)

Just to sanity check, @ajsharp you accounted for this?

If so, the next thing I'd try is to find the event in the live events table, and click "create action from event" next to it:

<img width="395" alt="image" src="https://user-images.githubusercontent.com/53387/208998306-35af41ee-2818-4891-b57e-6bde06eccec2.png">

**Comment by pauldambra** [comment]
This was dealt with in internal slack
