### ISSUE TITLE
[POS-27] Re-enable apps after temporary unavailability

### ISSUE THREAD

**Issue by lharries** [PostHog/posthog#13265]
## Is your feature request related to a problem?

When an app experiences a fatal error it turns off and sends them an email. Sometimes this happens correctly - such as when there's an invalid config. However, it often turns off the app when it shouldn't e.g. there was a network unavailability. This causes loss of data to the downstream apps.

For PostHog to be a core part of customers data infrastructure, we need apps to be more resilient.

![](https://uploads.linear.app/b3c87ff7-d6a5-406d-8eeb-47fb425230e0/7d156a71-d949-4ec2-8d17-5f26146455e1/3d485027-963a-42e1-aa98-17d1196e2d32)

## Describe the solution you'd like

Apps should be much more robust. They should only in extreme circumstances entirely turn off.

This might include exponential backoff retries.

(Nice to have but less important) if an app does entirely turn off it should be far more noisy than 1 email.

(The exact solution is up to the engineers)

Related Issue: [https://github.com/PostHog/posthog/issues/10696](https://github.com/PostHog/posthog/issues/10696)

#### *Thank you* for your feature request – we love each and every one!

<sub>From [SyncLinear.com](https://synclinear.com) | [POS-27](https://linear.app/posthog/issue/POS-27/re-enable-apps-after-temporary-unavailability)</sub>

**Comment by Twixes** [comment]
Idea: Instead of exposing `fetch()` directly, we could only be exposing a wrapper that'd retry n times IF the request failed with a non-4xx error.
