### ISSUE TITLE
Cumulative is broken

### ISSUE THREAD

**Issue by timgl** [PostHog/posthog#1327]
## Bug description

Selecting cumulative doesn't work a lot of the time (but does sometimes work?)

## Expected behavior

Switching between linear and cumulative should always work

## How to reproduce

1. Go to Insights
2. Select cumulative
3. 

## Environment

- PostHog cloud or self-managed?
- PostHog version/commit

## Additional context

It does seem to do the correct API call, but then doesn't load the data into the frontend.

**Comment by timgl** [comment]
Update: It's got something to do with caching, basically we don't include the display in the list of results.

**Comment by mariusandra** [comment]
Could https://github.com/PostHog/posthog/pull/1305 fix this?

**Comment by timgl** [comment]
Yep, but need to make some changes. Working on this right now
