### ISSUE TITLE
feat: allow a separate configurable export url

### ISSUE THREAD

**Issue by pauldambra** [PostHog/posthog#13293]
## Is your feature request related to a problem?

When we run an export from the worker pods it is dependant on the SITE_URL. 

That environment variable is used for more than one purpose and needs to be publicly addressable. But for exports we could allow an internal address as the traffic can travel from the worker pod to the web pod.

## Describe the solution you'd like

Allow an EXPORT_URL environment variable which defaults to SITE_URL when not present

**Comment by Twixes** [comment]
I don't think we'll invest in this, given that it's a self-hosted oriented tweak.
