### ISSUE TITLE
sync app settings between projects 

### ISSUE THREAD

**Issue by lsmith77** [PostHog/posthog#13292]
## Is your feature request related to a problem?

We have a dev project and a prod project. We usually test out app settings on the dev project. Right now we then need to copy paste the settings.

## Describe the solution you'd like

Ability to sync app settings from another project.

## Describe alternatives you've considered

Ability to export and re-import app settings

## Additional context

I think there are also similar requests for insights but I only found https://github.com/PostHog/posthog/issues/10635

**Comment by timgl** [comment]
It's not a full solution, but you could use https://github.com/PostHog/posthog-migrate-meta for this.

**Comment by lsmith77** [comment]
interesting .. this could indeed be a cool way to keep two instances in sync. however this would also then mean any new config would would have to be done on dev (f.e. insights currently don't get created on dev). also I guess this isn't available as an app for cloud.

but in that spirit .. turning this into an app and making it possible to configure what to sync (apps, insights, documentation etc) would be amazing!

**Comment by Twixes** [comment]
This will be solved by [project environments](https://github.com/PostHog/meta/pull/176)!

**Comment by lsmith77** [comment]
nice. are the docs deployed already?

**Comment by Twixes** [comment]
The docs aren't there yet, but there is an RFC summarizing the feature: https://github.com/PostHog/meta/blob/main/requests-for-comments/2024-01-23-project-environments.md#summarizing-requirements
As for this issue, I'll close it in favor of the more comprehensive #13418 – that's where I'll include the current status of implementation/rollout.
