### ISSUE TITLE
Benchmark no-sharding (tenant-based sharding)

### ISSUE THREAD

**Issue by macobo** [PostHog/posthog#13317]
## Thesis

We have noticed that a lot of insights queries end up streaming excessive amount of data between shards. 

Example queries that are problematic: trend volume (https://github.com/PostHog/posthog/issues/13315) and everything related to funnels.

Hypothesis: By removing sharding/storing 2x the amount of data on a single node, we'll remove data streaming overhead and thereby get comparable or better performance on average than with sharding.

## Methodology

This was tested in production against a single production node.

<details><summary>Click here to see schema setup in prod</summary>

This SQL was run on a single node on all shards 
```sql
  CREATE TABLE karl_sharded_events_noshard_20221213 AS sharded_events
  ENGINE = ReplicatedReplacingMergeTree('/clickhouse/prod/tables/noshard/posthog.karl_sharded_events_noshard_20221213', '{replica}-{shard}', _timestamp)
  PARTITION BY toYYYYMM(timestamp)
  ORDER BY (team_id, toDate(timestamp), event, cityHash64(distinct_id), cityHash64(uuid))
  SAMPLE BY cityHash64(distinct_id)
  SETTINGS storage_policy = 'hot_to_cold', index_granularity = 8192

ALTER TABLE karl_sharded_events_noshard_20221213 ATTACH PARTITION '202210' FROM sharded_events
ALTER TABLE karl_sharded_events_noshard_20221213 ATTACH PARTITION '202211' FROM sharded_events
ALTER TABLE karl_sharded_events_noshard_20221213 ATTACH PARTITION '202212' FROM sharded_events
```

Once replication was complete (monitored system.replication_log), the new table contained data from both shards in that table
</details>

Script: https://github.com/PostHog/scratchpad/blob/main/karl/2022-12-14-benchmark-script.py

This script was run with the following configuration:
- shared: person-on-events was on, sampling 500 insights on dashboards for top 10 US clients, using a fixed time range of 70 days for each insight.
- baseline - sharded run: run queries as normal
- non-sharded run: events table name was replaced with `karl_sharded_events_noshard_20221213`

## Results

| | total query time | p95 query time |  error rate | rate of slow queries (>5s) | total amount of data streamed from replicas |
| --- | --- | --- | --- | --- | --- |
| baseline | 171 minutes | 127s | 3% | 24% | 739.14 GiB |
| no-sharding | 324 minutes | 369s | 4% | 24% | 0 KiB | 

[Metabase](https://metabase.posthog.net/question/526-analyzing-benchmark-run-results-2022-12-13)

**Conclusion**: While removing sharding did fix the data streaming problems, it ended up slowing down queries. There isn't evidence that it's worth tackling this idea at least for now.

**Confounding factors**: I did not control for page cache, but similar benchmarks on a smaller scale showed similar results.

## Additional context

cc @ellie @xvello @fuziontech @pauldambra @mariusandra  who have been asking about this benchmark.

This also raises the priority of https://github.com/PostHog/posthog/issues/12909 and fixing the problematic queries in other ways.

**Comment by neilkakkar** [comment]
Had a donut with Karl:

The initial hypothesis was that data streamed across shards is a limiting constraint that's causing queries to slow down.

However, the data seems to suggest that the limiting constraint is CPU (filtering) or disk I/O.

My guess was that the 2x time is because of CPU constraints: With sharded data, we effectively get 2x the threads (because there are 2x the physical cores) for processing, which leads to faster processing of data. Is this correct, or are the physical cores determined per cluster, with all shards in the same cluster?

If the former, does it make sense to have 2x resources for the non-sharded version when running these benchmarks?

Karl suggested that the limiting constraint is disk I/O instead. That is, we fully saturate reading from disk speed & multiple shards allow us to read more things in parallel, as there are more disks to read from.

**Comment by macobo** [comment]
> If the former, does it make sense to have 2x resources for the non-sharded version when running these benchmarks?

Probably from a science aspect, but not from what I was going for here.

I was hoping to find something that will increase query speed ~50% or more for similar spend which this benchmark neatly invalidates. It might still be that there's a win in the 10-20% area here, but will deprioritize looking into this for now.
