### ISSUE TITLE
STRICT_CACHING_TEAMS doesn't work if actions (or cohorts?) get refreshed

### ISSUE THREAD

**Issue by timgl** [PostHog/posthog#13312]
## Bug description

`STRICT_CACHING_TEAMS` won't refresh historical data on an insight if you update an action (and perhaps cohorts?), so the data  is wrong.

## How to reproduce

1. Set `STRICT_CACHING_TEAMS` to your team id
2. Save an insight with an action
3. Update the action to something else
4. The data won't have changed, except for today's data

## Environment

- [ ] PostHog Cloud
- [ ] self-hosted PostHog, version/commit: please provide

**Comment by EDsCODE** [comment]
Related link https://github.com/PostHog/posthog/issues/8133
