### ISSUE TITLE
[POS-28] Search isn't working when I have slow internet

### ISSUE THREAD

**Issue by lharries** [PostHog/posthog#13331]
## Bug description

The search is not letting me click on the user. I suspect it's because my internet is slow?

## How to reproduce

1. Throttle your internet
2. Search for someone e.g. {firstname}@posthog.com
3. Click on the person
4. It seems to not take you to the person

![Screenshot Persons   Groups • PostHog (Google Chrome) 2022-12-14 at 15 03](https://user-images.githubusercontent.com/22766134/207631578-25c1081f-b213-4ddd-90c9-c0a5a7ac556f.gif)

## Environment

- [x] PostHog Cloud
- [ ] self-hosted PostHog, version/commit: please provide

## Additional context

I haven't checked if this is fully reproducible.

#### *Thank you* for your bug report – we love squashing them!

<sub>[POS-28](https://linear.app/posthog/issue/POS-28/search-isnt-working-when-i-have-slow-internet)</sub>

**Comment by simfish85** [comment]
+1 on this - I have fast Internet and search is still broken.  See the start of this [recording](https://app.posthog.com/recordings/1851a3c51e117b7-0e4c09b6268eef-17525635-384000-1851a3c51e21ea0)

**Comment by lharries** [comment]
This was fixed here: https://github.com/PostHog/posthog/pull/13386
