### ISSUE TITLE
400 Bad Request on Get when trying to add more Graph Series into a Trend 

### ISSUE THREAD

**Issue by CristhianMotoche** [PostHog/posthog#13338]
## Bug description

I created a Trend with many Graph Series that look like this:

![image](https://user-images.githubusercontent.com/8370088/207716382-a4fa07a3-abd2-4eaf-a199-d64bc7c5a80d.png)

Unfortunately, I get an error when I try to add a new series after that.

I took a look at the Web Console and I noticed I got this 400 Bad Request:
<img width="282" alt="image" src="https://user-images.githubusercontent.com/8370088/207717318-3ccbc316-34f1-439e-953c-bac6cf585590.png">

I assume this is because the GET request has a huge payload:
```
GET | https://app.posthog.com/api/projects/13164/insights/trend/?insight=TRENDS&events=[{"id":"createHangout","math":"total","name":"createHangout","type":"events","order":0,"properties":[{"key":"category","type":"event","value":["acf808ce-1111-2222-3333-1234a1ae4556"],"operator":"exact"}],"custom_name":"Kayaking"},...
```

## How to reproduce

1. Create a Trend with a Graph Series that has a filter
2. Copy the Graph Series many times (try up to 50)

## Environment

- [x] PostHog Cloud
- [ ] self-hosted PostHog, version/commit: please provide

## Additional context

I think it could be related to this issue: https://github.com/PostHog/posthog/issues/4554

**Comment by pauldambra** [comment]
Hi @CristhianMotoche 

That limit is currently the maximum that gunicorn (which we depend on) allows https://docs.gunicorn.org/en/stable/settings.html#limit-request-line

So, currently this is working as designed. I wonder if we could turn this into a feature request though 😊 

Can you explain why you need so many series? I wonder if we could convert to fewer series broken down by some value...

**Comment by CristhianMotoche** [comment]
Hey @pauldambra Thanks for the very quick response. We have several categories (~45) and I need to create a Bars chart counting how many events where created for every category. I found Trends to be the best option for this but I see there is a reasonable limitation.

> So, currently this is working as designed. I wonder if we could turn this into a feature request though 😊

Makes sense! I can leave this open in case someone else also requests something like this. Otherwise, we can close it.

> I wonder if we could convert to fewer series broken down by some value...

Yes, I thought about that same workaround. I just have to confirm how we are we going to group the categories (e.g. by groups of 10, by groups of categories, etc.). Thanks!
