### ISSUE TITLE
Update Amazon AMI to install latest Posthog instance on boot

### ISSUE THREAD

**Issue by fuziontech** [PostHog/posthog#1339]
Currently we bake the version into the image when we create it. This makes it difficult to upgrade and difficult to coordinate releases with the release processes that every cloud provider has.

Instead, we should grab the most recent version of posthog on boot and do any upgrades and migrations that are necessary. That way the image ages well and upgrades for clients are as simple as rebooting the instance.

**Comment by Twixes** [comment]
Is this still relevant?

**Comment by paolodamico** [comment]
We no longer support this deployment type.
