### ISSUE TITLE
Dashboards on Persons/Groups

### ISSUE THREAD

**Issue by lharries** [PostHog/posthog#13419]
## Is your feature request related to a problem?

As discussed with @pauldambra today:

As a user, I'd like to quickly see insights and session recordings for a particular person/group from the persons/groups page.

Currently, I do this by repeatedly going to a dashboard and editing the filter.

<img width="718" alt="Screenshot Feature usage by company • Dashboards • PostHog (Google Chrome) 2022-12-19 at 21 36@2x" src="https://user-images.githubusercontent.com/22766134/208516674-7243f2fe-3429-4d88-8494-b40d6105e5c9.png">

This is particularly useful for looking at stats ahead of customer interviews. And likely also useful for non-ICP use cases (such as CS/Sales) - however this should be prioritized lower.

## Describe the solution you'd like

- [ ] From a person/group page either have a one-click button to a dashboard (filtered by that person or group), or embed the dashboard on the persons/group page within a tab.

Persons is likely more important than groups.

From speaking to Paul we already have lots of the functionality and could use a similar flow to when you set a home dashboard.

## Describe alternatives you've considered

1. Not do this
2. Embed widgets directly on the persons/groups page, but without using the dashboard wrapper

**Comment by mariusandra** [comment]
Some extra context: our existing property filters don't support filtering by `person_id`. Adding this would take some effort, which will be overridden by work on adding [HogQL expression support into every filter](https://github.com/PostHog/posthog/pull/13264).

We should already support filtering by group properties on all insights and dashboards, but somehow this is not enabled in the dashboard's filter. Might be a quick win. Then it's just a matter of linking to the dashboard with the right filters.

**Comment by pauldambra** [comment]
superseded by #16028
