### ISSUE TITLE
Iframe content doesn't show in recordings

### ISSUE THREAD

**Issue by raziele** [PostHog/posthog#13411]
## Bug description
Hi! 

We have a webapp embedded into our website as an Iframe. 

For some reason, the content of the embedded frame doesn't show in our recordings:
![SCR-20221219-pen](https://user-images.githubusercontent.com/2432693/208484215-34882b78-6bea-4d05-b2fd-5d4d8eead492.png)

[example recording](https://app.posthog.com/recordings/1852b5edcc3b02-0c91b360578a9b-17525635-384000-1852b5edcc490b
)

To compare, we were able to record the same Iframe with FullStory with no issues. Here's an example screenshot:
![SCR-20221219-p4u](https://user-images.githubusercontent.com/2432693/208484139-646c273b-a14d-4e68-b23d-ebfc27cfdc8d.png)

## Environment

- [x] PostHog Cloud
- [ ] self-hosted PostHog, version/commit: please provide

**Comment by dfrho** [comment]
Same issue here. Here's how FS addresses in their public-facing documentation. Not sure how the capture script handles 'owned and operated' iframes out of the box.

https://help.fullstory.com/hc/en-us/articles/360020622514-Can-FullStory-capture-content-that-is-presented-in-iframes-#h_01F1G32T05WMNM8TRR1TFDFP2Z

**Comment by marandaneto** [comment]
@raziele sorry for the long delay.
Did you check https://posthog.com/docs/session-replay/iframes#recording-cross-origin-iframes ?
Or was it same origin?

**Comment by raziele** [comment]
Hi @marandaneto it was the same origin. 
A lot has happened since then; now the iframes are shown, however they are viewed many times as their own "tab" or "screen", which effectively causes a jitter effect that makes it hard to watch recordings.
However, this specific issue is resolved.

**Comment by marandaneto** [comment]
feel free to raise a new issue/reach out to customer support about this other problem, thanks.
