### ISSUE TITLE
Changing property type doesn't update in the UI

### ISSUE THREAD

**Issue by rfguri** [PostHog/posthog#13428]
We've created a custom event, initially sending a property with property type string. Once we change it to a number, it does not update in the ui.

To solve it, we had to change it to another property name.

It would be convenient that when changing the property type, it also updates in the ui.

**Comment by neilkakkar** [comment]
Hey @rfguri , the way to do this is to go to Data Management -> Property -> Edit -> Change type.

It doesn't automatically change types once it's set, but you can manually override this if the type changes later on.

**Comment by rfguri** [comment]
Awesome! I didn't know about that, thanks! 🙏 

_Suggestion: Adding a small disclaimer in the docs when creating properties would be helpful (since I couldn't find out by myself in the docs)._

**Comment by neilkakkar** [comment]
Makes sense, will do! Thanks!

**Comment by neilkakkar** [comment]
curious: Where did you first look in the docs? That seems like the best place to add it.

**Comment by rfguri** [comment]
I think the best place is here: https://posthog.com/manual/events

It's where I first look since it has all the details for properties and all :)

**Comment by neilkakkar** [comment]
Ah, it says so in this section already: https://posthog.com/manual/events#event-filtering

**Comment by rfguri** [comment]
I think it would be better cached if moved just below the https://posthog.com/manual/events#event-properties and adding an ⚠️ emoji or something to catch attention.

In any case, something you guys may consider - but as you said, it's already there.
