### ISSUE TITLE
Indicate in a recording if there are domains tracked with recordings disabled

### ISSUE THREAD

**Issue by benjackwhite** [PostHog/posthog#13426]
## Is your feature request related to a problem?

We give users the ability to only enable recordings on certain domains. The downside of this is, they often forget they have done this which leads to confusion when recordings don't show, especially when recordings have a blank part in the middle of the session for example when you go from `mysite.com` to `auth.mysite.com` and back.

### Idea 1
As we are likely to be tracking events with the same SessionID, we could indicate what is happening in the Player by showing a warning like 
* `Events captured for domain X but Recordings are not enabled for this domain` if the domain is disabled
* `Events captured for domain X but no recording captured. It is possible that recordings were disabled for this domain at the time` if the domain is enabled.

### Idea 2
In addition to showing recordings that we _do_ have, we could also show "phantom" recordings where we have SessionId info from the filtered events. This could be shown only if the list is empty for example and when clicking explains why there is no recording (domain not enabled etc.)

## Describe alternatives you've considered

* Not doing this as it is too much effort for an edge case scenario

**Comment by pauldambra** [comment]
we have a banner warning for this
