### ISSUE TITLE
Network Recording: Capture network request and response info

### ISSUE THREAD

**Issue by benjackwhite** [PostHog/posthog#13450]
## Is your feature request related to a problem?

Our Network Recording feature captures responseStatus via the PerformanceObserver API **but** this is [barely supported across browsers currently](https://developer.mozilla.org/en-US/docs/Web/API/PerformanceResourceTiming/responseStatus#browser_compatibility) and the API will likely always be limited to not collect request and response params. 

## Describe the solution you'd like

In addition to using the standard PerformanceObserver API, we could experiment with wrapping the network request codes such as Fetch or xmlhttprequest. We should be super careful here of course as we would be monkey-patching other peoples critical code

There is already a [proposed extension](https://github.com/rrweb-io/rrweb/pull/1105) for the recorder that we could help get across the line

**Comment by djkgamc** [comment]
FullStory does this, was used to it

**Comment by marandaneto** [comment]
@pauldambra should we close this?

**Comment by pauldambra** [comment]
this is now out for everyone, it isn't enabled by default but you can enable it in recording config
