### ISSUE TITLE
Use a feature flag to decide if Recordings are enabled

### ISSUE THREAD

**Issue by benjackwhite** [PostHog/posthog#13454]
## Is your feature request related to a problem?

We have been advising people how they can control their recordings usage with more granularity and we recommend in the docs, starting recordings disabled in the client and then manually enabling, for example in reaction to a feature flag. 

Why don't we just offer this as a built in functionality?

## Describe the solution you'd like

As an extension to enabling recordings, allow the user to create or choose a feature flag to link the enablement to. 

We can then implement this in the decide endpoint with one extra lookup - get the flags and the configured recordings setting - if the recording is linked to a flag, return true only if the user is in that flag. 

## Describe alternatives you've considered

Leaving it as a manual effort for the user to implement. 

#### *Thank you* for your feature request – we love each and every one!

**Comment by neilkakkar** [comment]
Makes sense to me.

Flyby comment that there would be no extra lookups if we save this configuration in the right place, like on the team, (which is a worthy optimisation to make for `/decide`, which is very sensitive to perf impact)
