### ISSUE TITLE
Can't breakdown more than one property

### ISSUE THREAD

**Issue by rfguri** [PostHog/posthog#13464]
We want to breakdown by multiple properties set on a custom event, but UI only allows one to be set.

**Comment by neilkakkar** [comment]
Hey @rfguri , this request makes sense.

I'll close it as a duplicate of https://github.com/PostHog/posthog/issues/938 though

**Comment by rfguri** [comment]
Do you know an approximate ETA? I've seen the [#938](https://github.com/PostHog/posthog/issues/938) has been open since Nov

**Comment by neilkakkar** [comment]
As far as I know, at best Q2 2023

**Comment by mariusandra** [comment]
There is a [draft pr](https://github.com/PostHog/posthog/pull/13264) out that adds this support via hogql expressions, and should land in Q1
