### ISSUE TITLE
"Compare Previous" can't be unselected

### ISSUE THREAD

**Issue by mariusandra** [PostHog/posthog#1347]
## Bug description

![2020-08-04 14 33 33](https://user-images.githubusercontent.com/53387/89294273-8fbd3380-d65f-11ea-9f9d-a3d4fe89ccac.gif)

## How to reproduce:
- Selecting "compare previous" on `/insights` adds a line with the previous week's data
- Unselecting it, I expect the line to be removed, but it's not

**Comment by EDsCODE** [comment]
Working on it here #1337!
