### ISSUE TITLE
Trends: cumulative "unique group X" reports incorrect results

### ISSUE THREAD

**Issue by macobo** [PostHog/posthog#13486]
## Bug description

Locally, with a single project:

![image](https://user-images.githubusercontent.com/148820/209679082-3803c8d4-a913-4d80-a648-bb5699255d6a.png)

This result should be 1 instead

## How to reproduce

1. Go to trends
2. Select unique groups
3. Select cumulative line graph
4. See wrong results

## Environment

- [x] PostHog Cloud
- [ ] self-hosted PostHog, version/commit: please provide

## Additional context

Came up during fixing https://github.com/PostHog/posthog/issues/13315

**Comment by neilkakkar** [comment]
https://github.com/PostHog/posthog/blob/master/posthog/queries/trends/total_volume.py#L108

**Comment by macobo** [comment]
Note: Please don't pick this task as I already have a patch. I stumbled upon this fixing another issue and documented it just to make sure it will get fixed and to ease a review.
