### ISSUE TITLE
Sidebar second level menu UX on mobile could be improved

### ISSUE THREAD

**Issue by mariusandra** [PostHog/posthog#1349]
## Bug description

![2020-08-04 15 12 12](https://user-images.githubusercontent.com/53387/89297971-fb55cf80-d664-11ea-829a-1e5ca073a1f4.gif)

## Expected behavior

I'm on my phone and want to load "actions". I open the sidebar and, knowing it's under "Events" I click on "Events". The sidebar then disappears and the events page happens.

I think it would be better if when the sidebar is in "mobile mode", the links to expand ("events", "people", etc) just expand the sidebar instead of opening the page and closing it. I can then click "All Events" or "All Users" if I really wanted to go to the first item in the expanded menu.

**Comment by Twixes** [comment]
That sidebar is going away now and the new one is simplified so that this is not a problem.
