### ISSUE TITLE
Sprint 1.44.0 1/2 - Jan 9 to Jan 20

### ISSUE THREAD

**Issue by timgl** [PostHog/posthog#13533]
# Global Sprint Planning

## 3 things that might take us down

1. https://github.com/PostHog/posthog/issues/13534
2.
3.

## Retro: Status of Outcomes from Previous Sprint

1. Data exploration: insights in the new system @thmsobrmlr & @mariusandra (tables cont, insights help) > There is one, we need to do the others to tbc. Tables is released internally.
1. Yeet AntD from all insights-related components, building a few replacements @Twixes > Deprioritised in favour of person properties timeline, will work on it this sprint.
1. Performance: @macobo create new tooling for benchmarking and exposing pain, validate moonshot alternative schema (posthog with no sharding). https://posthog.slack.com/archives/C0368RPHLQH/p1670363579097329 for more context > Done(ish), always more stuff to do
1. Web Performance - @pauldambra Paul & Ben fun time in Lisbon. Data Exploration in, Web Performance out. > Released for our team, will roll out to other teams
1. Make growth team happy running experiments: https://github.com/PostHog/posthog/issues/10426 @neilkakkar > Raquel is 11/10 happy so done.
1. https://github.com/PostHog/posthog/issues/13147 fixing @EDsCODE > Did some cleanup tasks, but didn't get to the ideal state. Table this so we don't get stalled on the current feature flag stuff.
1. persons-on-events @hazzadous - **Done**: implementation to resolve pending issues in review **Todo**: implement solution for onboarding/debugging events in realtime. Review increase of buffer. Backfill person_id i.e. run migration 0007 again. 
3. snowflake re-enabling @fuziontech > not done, going to take a bit longer. We have good ideas on how to do this.
1. performance on capture @xvello > Investigation, adding instrumentation. No quick wins. Closed for now, going to discuss options as a team next week.
1. data integrity problems for priority customers @tiina303 > Done except for someone's prod instance.
1. "Pinned recordings" to S3 finalisation @alexkim205 > Very close. Part 1 is merged, s3 persistance stuff is very close.
1. Network logs alpha @benjackwhite > Alpha will be done, more follow up for internal testing
1. Infra hero, see [the board](https://github.com/orgs/PostHog/projects/72/) for work planned @ellie > First infra hero, went well. Finished most of the tickets. Clickhouse 22.8 almost complete.
1. Look deeper into AWS costs and find low-hanging fruits to reduce the cost @danielxnj > Investigated, some low hanging fruit. Hoping to roll out a change with impact by end of week.
1. Have the plan to spin up a new automated ClickHouse cluster on the US AWS account, and replicate to it @danielxnj > no progress, also part of our OKRs this quarter
1. Improve new billing page further to recover lost conversion rate @raquelmsmith > Done for now, hooking it up to billing performance. 
1. Support work to be able to launch new pricing with PostHog Lite / Scale / Enterprise @kappa90 > Still a WIP, main focus for next sprint.

## Retro: What can we do better next sprint?

1. Holiday: we had year in review. We could plan this better.
2. Holiday: infra was super stable, no pages during key days
4.
5.
6.

## Support hero this sprint

Week 1: Karl
Week 2: Paul

## Plan: Proposed Goals for Next Sprint 

Each goal should have a single owner. Owner can only be an engineer.

1. Data Exploration - get events table live to real users. Get pivot tables out for internal testing. Finish the last insight types. @mariusandra
Why? Leftover from last time, blocker for PH3000, people want to explore data in ways we don't support.
1. Break down PostHog 3000 into next steps, and solve prerequisites (antd). @Twixes
Why? PostHog 3000 is our Q1 OKR, and required to nail slick mode. To create an interface better suited for power users.
1. Performance: Property definitions, filters and data types @macobo
Why? Event property definitions load slow, and person property definitions lack type information (e.g. string vs datetime), making some queries impossible for a few users.
1. Internally test and then finish up Unified Network panel to gradually rollout to customers @alexkim205
why? - This rework brings lots of 3000-esque improvements and is a pre-cursor to Performance panel
1. iOS Recording groundwork - project setup, working example recording to file @benjackwhite
why? - Get a head start on our hardest goal and answer the unknown questions
1. Hook up pricing pages to billing service for faster pricing iterations @kappa90 
why? So we can show different pricing to different cohorts and have faster pricing iteration
1. @ellie: Productionize US postgres replica, explore cutting over to it
why? Unify infrastructure
1. @ellie: Work with @kappa90 to improve scheduled billing jobs
why? Allow billing to run scheduled task with more visibililty/reliability
1. @danielxnj: NAT gateway per AZ, saves $$$
why? save $$
1. @danielxnj: Clickhouse backups in S3 to save $$$
why? Save $$
1. Feature Flag resiliency https://github.com/PostHog/meta/pull/74/files @neilkakkar
why? If our DB is down, feature flags still return something
1. JSON Flags, allow users to configure flag responses https://github.com/PostHog/posthog/issues/13144 @EDsCODE
why? People want to use feature flags for more things. Requested a lot.
1. Offsite @fuziontech 
why? Make sure we carry momentum from offsite. 

# Team sprint planning

For your team sprint planning copy this template into a comment below for each team.

```
Team ___

## Retro

<!-- Talk about what went well, what didn't go well and any actions to improve next time -->

- 

## Hang over items from previous sprint

<!-- For each item, decide to re-prioritise (and add below) or deprioritise -->

- Item 1. prioritised/deprioritise

## Planning

<!-- Each item should have a single owner. Owner can only be an engineer. -->

### High priority

-

### Bugs

-

### Low priority / side quests

-

```

**Comment by mariusandra** [comment]
# Team Product Analytics

Support hero first week: @macobo 
Support hero second week: @pauldambra 

## Retro

1. Data exploration: insights in the new system @thmsobrmlr & @mariusandra (tables cont, insights help)
   - Still in progress
1. Yeet AntD from all insights-related components, building a few replacements @Twixes
   - Still in progress
1. Performance: @macobo create new tooling for benchmarking and exposing pain, validate moonshot alternative schema (posthog with no sharding). https://posthog.slack.com/archives/C0368RPHLQH/p1670363579097329 for more context
   - Doneish. Benchmarking done. Moonshot alternative schema confirmed to not work. Trends are fasters. Dashboards are faster. We have 2 CH clusters in productions. Cache gets hit 70% -> 95% (huge for p95)
1. Web Performance - @pauldambra Paul & Ben fun time in Lisbon. Data Exploration in, Web Performance out.
   - Still in progress. Might get done this week.

## Planning

- Data Exploration - get events table live to real users. Get pivot tables out for internal testing. Finish the last insight types. @mariusandra
   - Why? Leftover from last time, blocker for PH3000, people want to explore data in ways we don't support.
- Break down PostHog 3000 into next steps, and solve prerequisites (antd). @Twixes 
   - Why? PostHog 3000 is our Q1 OKR, and required to nail slick mode. To create an interface better suited for power users.
- Performance: Property definitions, filters and data types @macobo 
   - Why? Event property definitions load slow, and person property definitions lack type information (e.g. string vs datetime), making some queries impossible for a few users.

**Comment by benjackwhite** [comment]
# Team rick@keepit.cool ... ings

## Retro

Christmas!
 

## Hang over items from previous sprint

* **"Pinned recordings" to S3 finalisation** - 1 more day needed
* **Network logs alpha** - Final PR about to go out and then will be tested internally.

## Planning

### High priority

- Internally test and then finish up **Unified Network panel** to gradually rollout to customers @alexkim205 
why? - This rework brings lots of 3000-esque improvements and is a pre-cursor to Performance panel
- **iOS Recording groundwork** - project setup, working example recording to file @benjackwhite 
why? - Get a head start on our hardest goal and answer the unknown questions

### Bugs
-

### Low priority / side quests

- https://github.com/PostHog/posthog/issues/13184 @alexkim205 
- Encourage PostHog team to try out Network recordings "alpha" so we can generate feedback for next sprint.
- Analyze data usage for PerfEvents in Clickhouse

**Comment by kappa90** [comment]
# Team Growth

## Retro
- Em, support hero, worked on rate limiting organizations based on billing limits & refactor available features
- Raquel, worked on billing page pricing table, demo data stuff, updated pricing on website

## Hang over items from previous sprint
- Refactor `available_features` coming from billing service, to populate pricing page both in product and on website

- Item 1. prioritised/deprioritise

## Planning
- Hook up pricing pages to billing service for faster pricing iterations
- Complete rate limiting PRs

### High priority
- Hook up pricing pages to billing service for faster pricing iterations

### Bugs
- Flickering billing alerts
- Some orgs don't have billing data correctly registered when capturing events

### Low priority / side quests
- Complete rate limiting PRs
- Finalize demo data
- Verifying email addresses on signup
- Migrate high paying customers to billing v2

**Comment by ellie** [comment]
# 🚀 Infrastructure Team 🚀

### Infra hero: @guidoiaquinti 

## Planning

- @ellie: Productionize US postgres replica, explore cutting over to it
- @ellie: Work with @kappa90 to improve scheduled billing jobs
- @danielxnj: NAT gateway per AZ, saves $$$
- @danielxnj: Clickhouse backups in S3 to save $$$

**Comment by EDsCODE** [comment]
Team Experimentation
---

Retro
---
- Cohort Revamp: Cleanup task is ready. Further refactoring is tabled for now so the new objectives can be pursued 
- Make growth team happy running experiments: Mostly happy, last PR is going in


Planning
---

1. Feature Flag resiliency https://github.com/PostHog/meta/pull/74/files @neilkakkar 
2. JSON Flags https://github.com/PostHog/posthog/issues/13144 @EDsCODE

**Comment by fuziontech** [comment]
# 🚰 Team Pipeline🚰 

## Retro

- Overall still feeling a bit like we are firefighting and reacting more than we should, but feeling a little bit better. Our goal should be to really work on being more proactive than reactive.

## Hang over items from previous sprint

- Person on events follow up work
  - https://github.com/orgs/PostHog/projects/74/views/1?visibleFields=%5B%22Title%22%2C%22Assignees%22%2C%22Status%22%5D
- Plugin/Snowflake export work
  - https://github.com/orgs/PostHog/projects/76/views/1

## Planning

### High priority

-  **Week 1** => 🇫🇷 🥖 Offsite 🥖 🇫🇷 
-  **Week 2** => Follow ups from Hackathon and Offsite tasks!

**Comment by mariusandra** [comment]
# Team Product Analytics next sprint

(will be moved)

## Retro

- Data Exploration - get events table live to real users. Get pivot tables out for internal testing. Finish the last insight types. @mariusandra Why? Leftover from last time, blocker for PH3000, people want to explore data in ways we don't support. --> Good progress.
- Break down PostHog 3000 into next steps, and solve prerequisites (antd). @Twixes Why? PostHog 3000 is our Q1 OKR, and required to nail slick mode. To create an interface better suited for power users. --> Work continues. Loads of ants.
- Performance: Property definitions, filters and data types @macobo Why? Event property definitions load slow, and person property definitions lack type information (e.g. string vs datetime), making some queries impossible for a few users. --> Karl on support & ill, will partially carry over into "slick filters"

## New goals

- Data exploration tiles (events tables) on dashboards
- Slick filters (including property types)
- PostHog 3000 prerequisites: antd yeeting

Sidequests:
- Systematically audit queries
- Person drilldown view
- Other sources of data in live events view (switch to recordings)

**Comment by benjackwhite** [comment]
# Team SessiOS Recordings

## Retro

- @benjackwhite Felt like we are less "shipping" than before - good to keep an eye on it.
- @alexkim205 Agrees with rolling out Inspector panel speed, Performance is a little more careful regarding ingestion. 

## Hang over items from previous sprint

- Internally test and then finish up Unified Network panel to gradually rollout to customers 
(Will be out by end of sprint)

## Planning

### High priority

- Rollout Network panel to some beta users @alexkim205 
why? We have been running it successfully internally last sprint and the final touches are there so lets get it out.

- Turn on Recordings by default @alexkim205 
why? Huge number of customers we are missing out on as they don't realise it isn't on by default.

- Mobile Session Recordings published (alpha)
why? Makes sense to test what we have ASAP with real apps (e.g. PostHoger's apps)


### Bugs
-

### Low priority / side quests

- Network release todo
  - Look into TTL on CH table

- Ingestion rate limiting @benjackwhite @kappa90 See [issue](https://github.com/PostHog/product-internal/issues/427)

**Comment by kappa90** [comment]
# Team Growth 🌱 (next generation)

## Retro
- We created a biweekly pairing session, which is extremely helpful
- Achieved a new Plans API together
- Finished migrating billing v1
- Pricing principles & pricing experiments RFCs
- Deprecated self-hosted billing on the billing service
- Fixed flickering billing warnings and Quick Start button

## Hang over items from previous sprint
- Verify email addresses @raquelmsmith
- Rate limiting (we decided to drop the current approach and restart together with pipeline and recordings folks) @kappa90
- Hook up billing tables to plans API (in-product one will be done by end of current sprint) @raquelmsmith 
- Deprecate the license server @kappa90 

## Planning

### High priority
- Hook up pricing page to billing server @raquelmsmith (outstanding)
- Rate limiting with special guest @benjackwhite & @kappa90 
- Defaulting users into a paid plan on signup @kappa90

### Bugs
- Nope

### Low priority / side quests
- Verify email addresses @raquelmsmith
- Billing emails @kappa90 
- Improve onboarding flow to explain better session recordings and autocapture @raquelmsmith
