### ISSUE TITLE
Default primary key is an IntegerField, which is not large enough

### ISSUE THREAD

**Issue by raquelmsmith** [PostHog/posthog#13534]
## Bug description

**Summary:** Our tables use an IntegerField as the default primary key, and (if I can trust the recently created rows in metabase) we're 43% of the way through available rows on the `Person` table and 50% of the way through available rows on the `PersonDistinctId` table.

**Detail:** 

I came across this while working on the demo data project, which was using a calculated `id` that was failing to insert with the error `psycopg2.errors.NumericValueOutOfRange: integer out of range`.

Django has an AutoField for all models that don't specify a primary key. https://docs.djangoproject.com/en/4.1/ref/settings/#std-setting-DEFAULT_AUTO_FIELD

This is set in `/posthog/settings/data_stores.py` on line 13: https://github.com/PostHog/posthog/blob/cb44dd25294d88a5592cd8604ea732badffc4294/posthog/settings/data_stores.py#L13

On both the `Person` and `PersonDistinctId` tables, we do not set the primary key to another field, so it automatically uses an `id` field, which is by default set to `AutoField`, which is a postgres `IntegerField`. The problem is that IntegerFields only take ints up to `2147483647`. Django does support a BigAutoField: https://docs.djangoproject.com/en/4.1/ref/models/fields/#bigautofield

However, simply migrating to that will touch every single row, which seems treacherous. If we simply change the primary key on those tables to the UUID, then it removes the ID field, which will likely cause its own host of problems.

## How to reproduce

1. Try to insert a person with an `id` grater than `2147483647`. 

## Environment

- [ ] PostHog Cloud
- [ ] self-hosted PostHog, version/commit: please provide

**Comment by timgl** [comment]
I think there's two options here

## do int -> bigint

This isn't that straightforward as doing this as a normal migration will lock the table (which would be bad). There's a workaround of creating a separate column, backfilling it and then switching the columns ([example](http://zemanta.github.io/2021/08/25/column-migration-from-int-to-bigint-in-postgresql/)).

## Use UUIDs everywhere

I think the best way to do this would be to switch everything over to UUIDs, though this isn't super straightforward either. The advantage is it'll mean we only use one type of id, we stop leaking (some) usage information and it'll make things easier in the future.

A loose list of things that would need to happen

- [ ] Start writing person_uuid to PersonDistinctId and CohortPeople
- [ ] Backfill person_uuid to PersonDistinctId and CohortPeople
- [ ] Make sure we use UUIDs everywhere
- [ ] Concurrently create a unique index on uuid on persons
- [ ] Drop or NULL the column

**Comment by tiina303** [comment]
https://github.com/PostHog/posthog/issues/12721
