### ISSUE TITLE
March 23 offsite merch

### ISSUE THREAD

**Issue by lottiecoxon** [PostHog/posthog#13541]
### Trying to get ahead this year with the all company offsite merch for Aruba. (+ what a fun way to start the year) 

I have a few ideas to get the ball rolling - all including our favourite pixelated in-app hedgehog. Think beach influence pixel art - easy to embroider and cool to look at 😎 

A few ideas below: 

- T-shirts
- Towels 
- Caps
- maybe a tote bag 

(Need to confirm with People and Ops ( @postgrace  + @charlescook-ph ) on budget for this )

DEADLINE- aiming to have this done by the end of Jan at the latest

**Comment by lottiecoxon** [comment]
![Image](https://user-images.githubusercontent.com/65415371/210337316-9a833442-4b3e-4baf-a137-958e530f49f1.png)

**Comment by liyiy** [comment]
beach flip flops :D

**Comment by postgrace** [comment]
My faves are towels and totes. I'd also suggest a bucket hat as an option over a cap!

From last time, it would be awesome if we could steer more towards one-size fits all stuff like these vs clothing as it's quite a hassle to collect sizes and then have to build individual packs for people based on what size they require.

@lottiecoxon last time we budgeted $150 per person.
