### ISSUE TITLE
Replace Redis with Kafka for events queue

### ISSUE THREAD

**Issue by fuziontech** [PostHog/posthog#1356]
From incident:
https://manage.statuspage.io/pages/1ll2gn427qjl/incidents/nss00rcggb00

In the event that there is a spike in traffic if we are flushing in flight events to disk we have a lot longer of a runway to spin up events processing workers without the risk of dropping events.

**Comment by Twixes** [comment]
I don't believe this is relevant now. We're using Kafka in EE though not for queuing, and it's significantly more cumbersome to run than Redis, so we won't be using it in the FOSS edition.
