### ISSUE TITLE
SECRET_KEY generation is a manual process and often skipped

### ISSUE THREAD

**Issue by yakkomajuri** [PostHog/posthog#1358]
## Is your feature request related to a problem?

*Please describe.*

The `SECRET_KEY`env variable used by the server is set to a placeholder on the `docker-compose` file and must be changed manually to ensure security. Since this is a manual process that is poorly documented, this step is sometimes skipped, which is a problem.

## Describe the solution you'd like

Automatic key generation and storage. 

## Describe alternatives you've considered

I'm planning on submitting a WIP PR and hope to spark some discussion about the alternatives on how to do this automatically.

Otherwise, if we decide to stay with the manual process, I need to go ahead and make sure this is documented well.

**Comment by mariusandra** [comment]
There's a technical gotcha here. The secret key is used to encrypt the session cookies... and whenever the server gets a new one, you're automatically logged out.

This is not that bad if you have just one server, but if you have two and there's a 50% chance with each request what server will process it (e.g. random or round-robin load balancing), you'll get logged out every other link you click. That just won't work.

Thus the secret key should be set before the docker containers starts.

**Comment by paolodamico** [comment]
I believe this can be closed @yakkomajuri ?
