### ISSUE TITLE
Action & Event selection dropdown doesn't make sense

### ISSUE THREAD

**Issue by mariusandra** [PostHog/posthog#1360]
## Bug description

This dropdown doesn't make sense:

![2020-08-05 13 50 44](https://user-images.githubusercontent.com/53387/89409985-3ae2f100-d723-11ea-85ae-52b198f206cb.gif)

There are two tabs inside this dropdown... that open more dropdowns.

Also the "actions" list contains a list of "events"... that are not "events":

![image](https://user-images.githubusercontent.com/53387/89410124-7382ca80-d723-11ea-9b02-fd979f007a9a.png)

This is all confusing and doesn't spark much joy.

Also, 50% of the time I start searching for the event or action that I'm looking for in the wrong tab.

## Expected behavior

We could simplify this to just one box that opens with a shared list of events and actions.

**Comment by Twixes** [comment]
This component has been replaced with a much more sensible one.
