### ISSUE TITLE
posthog.com down.... ERR_ADDRESS_INVALID

### ISSUE THREAD

**Issue by KrunchMuffin** [PostHog/posthog#13603]
This site can’t be reached
The webpage at https://posthog.com/ might be temporarily down or it may have moved permanently to a new web address.
ERR_ADDRESS_INVALID

**Comment by guidoiaquinti** [comment]
👋 Hey @KrunchMuffin, thank you for your report! From which network are you connecting? Can you please try again using another ISP? From our telemetry DNS resolution is working correctly so it should be a local issue with your provider.

**Comment by KrunchMuffin** [comment]
My apologies. I have PiHole running and I didn't see it getting blocked in the logs. I even when I turned it off to check. Fixed it now.

**Comment by guidoiaquinti** [comment]
No problem, glad you fixed the issue!
