### ISSUE TITLE
Randomize record IDs

### ISSUE THREAD

**Issue by Twixes** [PostHog/posthog#1361]
## Is your feature request related to a problem?

Currently our record IDs are mostly autoincremented integers, meaning it can be checked how many users or teams we've got, how many events there are etc.

## Describe the solution you'd like

IDs should be random (optionally also time-based). This can take the form of random 32 bytes (as is the case already with distinct IDs for example), UUID-4s or something like [Twitter snowflake IDs](https://developer.twitter.com/en/docs/basics/twitter-ids). The switch should be relatively straightforward, as none of these options would cause collisions with older IDs.

**Comment by timgl** [comment]
We already have a distinct_id field that we fill with a random token for our own tracking. We could use that in the (few?) places we use user ids

**Comment by Twixes** [comment]
Since overall IDs should be public, just not tied to the number of records, I think it'd be cleanest to migrate from `int` to `varchar` and use current `distinct_id`s generation for all IDs. Could even turn down the number of bytes to 24 or 16, as the current 2^(32*8) possibilities is mind-bogglingly collision-proof.

**Comment by paolodamico** [comment]
Agreed, I would suggest only using the logical PK for database stuff and always use another ID as @Twixes described for any API interactions. We could create an abstract model that introduces this ID and all the other models inherit from. I've done in some projects before, happy to provide some gist if it's helpful.

**Comment by paolodamico** [comment]
I think we have a clear path to do this, we just haven't implemented everywhere. Should we close this @Twixes ?

**Comment by Twixes** [comment]
I would say no, because for a lot of collections (even new ones, such as Experiments) this is still an issue and we _don't_ have a path.

**Comment by Twixes** [comment]
Looks like we're likely not going to follow through with this, or if we will, this issue will not be needed.
