### ISSUE TITLE
Snowflake Export - TypeError preventing export

### ISSUE THREAD

**Issue by huckleberryCalfinn** [PostHog/posthog#13626]
## Bug description

*Please describe.*  
Hi. We have noticed that, as of 12/15/2022, our Snowflake connector app seems to be malfunctioning. We are seeing a TypeError that seems to be preventing the connector from updating our Snowflake database. Please note the screenshots for additional context, and thank you very much for your help.

*If this affects the front-end, screenshots would be of great help.*  
![image](https://user-images.githubusercontent.com/54969896/211635119-d5ce139f-0386-4900-ac8e-ee321d507940.png)
![image](https://user-images.githubusercontent.com/54969896/211635172-b93996f1-5ebf-4d2e-b17c-c4d9190a4512.png)

## How to reproduce

1. Go to Browse Apps
2. Snowflake Export
3. observe errors in attempted exports (shown in screenshot)

## Environment

- [ ] PostHog Cloud
- [x ] self-hosted PostHog, version/commit: "posthog-js": "^1.22.18",

Thank you very much!

**Comment by macobo** [comment]
cc @fuziontech who has been looking at the snowflake app recently.

**Comment by calvin-witt** [comment]
thank you very much - your help is greatly appreciated!

**Comment by calvin-witt** [comment]
hi @macobo @fuziontech - just wanted to check in and see if there might be any progress here. thank you again!

**Comment by xvello** [comment]
Hello @huckleberryCalfinn, this issue is caused by https://github.com/snowflakedb/snowflake-connector-nodejs/issues/349, and we didn't manage to work around it. We are closely monitoring the state of the upstream issue and will release an updated app as soon as the fix is released.

**Comment by yevgenypats** [comment]
Hey folks! Sorry for the drop-in here. I opened this [issue](https://github.com/PostHog/posthog-go/issues/17) and I think it can help solve this issue as well and reduce burden on maintaining a Snowflake connector while only focusing on PostHog APIs and also enabling users to sync PostHog data to any other DBs (BigQuery, S3, Athena) without any additional code. I'd love to help with an initial CloudQuery/PostHog source plugin if this is something interesting.

**Comment by xvello** [comment]
Hello @huckleberryCalfinn, I pushed a commit to the snowflake app that uses the workaround they documented, while we wait for a release with the fix.
Feel free to update your app and report here if the issue persists!

**Comment by calvin-witt** [comment]
@xvello thank you team! The snowflake app seems to be working again - thank you again for all you help!
