### ISSUE TITLE
Exports frequently fail due to polling limits

### ISSUE THREAD

**Issue by macobo** [PostHog/posthog#13638]
## In what situation are you experiencing subpar performance?

We've had [user reports](https://posthoghelp.zendesk.com/agent/tickets/1428) that exports keep failing due to user timeouts.

I've witnessed this myself trying to export csv data from user modals in funnels.

We should dig into this and figure out what's going wrong and make sure we have appropriate metrics in place.

## Environment

- [x] PostHog Cloud
- [ ] self-hosted PostHog, version/commit: _please provide_

## Additional context

cc @benjackwhite as feature starter

**Comment by pauldambra** [comment]
There are some metrics here https://metrics.posthog.net/d/jMdv69qnk/exports?orgId=1&from=now-7d&to=now

We do see CSV exports "succeeding" in Celery long after the UI has reported the export has failed.

**Comment by Twixes** [comment]
Solved, now that we have an Exports side panel in the UI.
