### ISSUE TITLE
Problematic CloudFormation setup

### ISSUE THREAD

**Issue by Twixes** [PostHog/posthog#1364]
## Bug description

We've had a user tell us in a call that the [CloudFormation template from docs](https://posthog.com/docs/deployment/deploy-aws#cloudformation-install-recommended) – which is our recommended way of deploying PostHog on AWS – wasn't working for them. We aren't sure what issue popped up exactly, but if there is one, trying to repeat that setup should reveal it.

## Expected behavior

CloudFormation setup should result in a working PostHog instance.

## How to reproduce

1. Try creating a PostHog instance from the template in docs.
2. ???
3. No profit.

## Environment

- AWS
- PostHog CloudFormation template

**Comment by Twixes** [comment]
Could you please take a look at this some time? @fuziontech

**Comment by ungless** [comment]
I went through a CloudFormation deployment the other day actually. The main problem was with the docs not reflecting the UI in the aws console.

I think that aws recently redesigned it but I could be missing something.

Other than that, I managed to get it running so I'm not sure what's up.

**Comment by nullablebool** [comment]
I just tried and setup seemed to work within AWS. I navigated to the "Outputs" tab and saw the "ExternalUrl" property. Launching this loads the setup_admin; hitting submit throws a 403 (CSRF verification failed. Request aborted).

This is the first issue I found after looking into a solution. I'm looking to enable TLS on the load balancer and use my own domain so I'm sure I'll figure it out shortly. Just wanted to give my 2 cents.

**Comment by mariusandra** [comment]
Hi @nullablebool , I think the latest docker image (accidentally?) contains some "unreleased" features, that will make it into PostHog 1.13.0 later this week. Thus they're a bit undocumented.

One of the bigger changes regarding setup in the new version is that we have to be explicit regarding the security of the cookies.

There's a new env variable `SECURE_COOKIES` that defaults to `True` in production (and `False` in development). If you're deploying without HTTPS, you'll need to manually set it to `False`. 

I hope this helps!

**Comment by nullablebool** [comment]
@mariusandra Thank you! Appreciate the prompt follow up. I was able to get it working for SSL but this was insightful; thanks again.
