### ISSUE TITLE
PostHog no longer ingesting data

### ISSUE THREAD

**Issue by filipecatraia** [PostHog/posthog#13668]
## Bug description

Hey, I've been really enjoying PostHog, but for a few weeks it's not been ingesting data. Sadly I only saw the issue today, so we've lost quite a bit of data. All good, it's self-hosted and I know the risks.

The profile dropdown shows an exclamation mark with “Potential system issue”, but doesn't actually say what the issue is. I see `Plugin server alive` is now “No”, though everything else seems good. We have space, all Docker instances are running, etc.

## Environment

- [ ] PostHog Cloud
- [x] self-hosted PostHog, version/commit: `dc3e1ed9e3e52b05368706080cf38aa0215ba0ad`

## Additional context

I've installed PostHog on Debian using the installation script. All Docker containers have been running fine, with multi-week uptimes. However, since December 5th, there's no data ingestion.

Some info:

- `Plugin server version` is “unknown”
- `asynchronous_metric_log` in Clickhouse has ballooned to 800 million rows, possibly that's okay? Should it be dumping these rows elsewhere?
- There's plenty of RAM and disk space for all containers

Let me know what I can provide to help diagnose the issue. Thanks a lot!

(I'd consider moving to PostHog Cloud and not manage the infrastructure, but sadly it's too expensive for us.)

**Comment by guidoiaquinti** [comment]
👋 Hey @filipecatraia , looks like you are running PostHog open-source via `docker-compose` and not `k8s`?

* can you please share more info about your setup
* can you please share the `plugin-server` logs

Thank you 🙇

**Comment by ellie** [comment]
> (I'd consider moving to PostHog Cloud and not manage the infrastructure, but sadly it's too expensive for us.)

I'd also like to add that we have discounts for both B2C and non-profits, so this might be something we can help you out with!

**Comment by ghost** [comment]
I've restarted the server, and then PostHog, and the problem seems fixed for now. Also added the plugin to monitor failed ingestion. Hopefully this won't happen again 🤞 

@ellie Sadly we're neither, we're a B2B EdTech young startup :) But thanks!
