### ISSUE TITLE
Dashboards stuck in narrow single-column view

### ISSUE THREAD

**Issue by andyvan-ph** [PostHog/posthog#13675]
## Bug description

Dashboards aren't scaling to the width of the browser, instead remaining stuck in a very narrow single-column view. Mac OS + Chrome. See video:

https://user-images.githubusercontent.com/92976667/212068726-35f084c4-25a4-411c-ac6c-6302afab2d4d.mov

## How to reproduce

1. Open any dashboard
2. Expand browser width
3.

## Environment

- [x] PostHog Cloud
- [ ] self-hosted PostHog, version/commit: please provide

## Additional context

n/a

**Comment by mariusandra** [comment]
Fix here: https://github.com/PostHog/posthog/pull/13679
