### ISSUE TITLE
Bug: Recording interface obscures tooltips

### ISSUE THREAD

**Issue by joethreepwood** [PostHog/posthog#13673]
## Bug description

Some of the tooltips on events on the recording seekbar overrun the space and get obscured. E.g.

<img width="529" alt="Screenshot 2023-01-12 at 11 15 36" src="https://user-images.githubusercontent.com/84011561/212052997-5f747bcc-164a-4413-83a0-8e49f8bb340f.png">

## How to reproduce

1. Find and event with a long tooltip 
2. https://app.posthog.com/recordings/1859b8b5a3322b6-04e90a057f5acc-17525635-384000-1859b8b5a34246b
3.

## Environment

- [ ] PostHog Cloud
- [ ] self-hosted PostHog, version/commit: please provide

**Comment by pauldambra** [comment]
i believe this is fixed now
