### ISSUE TITLE
Cookies rejected on new deploy with docker

### ISSUE THREAD

**Issue by robov** [PostHog/posthog#1369]
I just pulled the latest posthog and wanted to deploy it on my server. Filling the account details was fine, however I cannot login. Developers console shows why... 

A cookie associated with a cross-site resource at http://posthog.com/ was set without the `SameSite` attribute. It has been blocked, as Chrome now only delivers cookies with cross-site requests if they are set with `SameSite=None` and `Secure`. You can review cookies in developer tools under Application>Storage>Cookies and see more details

**Comment by timgl** [comment]
Hi, I think these might be unrelated as that warning is [for posthog-js](https://github.com/PostHog/posthog-js/issues/76). 

Are you getting any errors in your logs? What actually happens when you login?

**Comment by yormy** [comment]
When I login I am redirect back to the cleared login screen

**Comment by timgl** [comment]
@yormy We think you might be running PostHog with the environment variable `DEBUG` turned on. Would you mind checking if that's the case?

**Comment by timgl** [comment]
Also will close this as a duplicate of #1376 but feel free to respond to this or in that issue

**Comment by timgl** [comment]
@yormy @robov just following up, we found the bug and fixed it in 1.12.1. Let me know if you have any other questions
