### ISSUE TITLE
Bug when trying to create a dahsboard by filling all inputs (optional and mandatory)

### ISSUE THREAD

**Issue by Abdelilah-MOULIDA** [PostHog/posthog#13707]
## Bug description

*Please describe.*  
*If this affects the front-end, screenshots would be of great help.*  

When I try to create a dashboard, if I fill the description PostHog doesn't create the dashboard, but if I don't fill it PostHog creates the dashboard.
When I create the dashboard without the description and I try to add it afterwards, postHog tells me that to add it I have to be in premium plan.

https://user-images.githubusercontent.com/33268490/212322865-119ba439-79b2-47ab-88ce-aafe99fb4b23.mov

*If you are on PostHog Cloud it would be really valuable if you can share any links where the problem occurs. This speeds up our ability to troubleshoot tremendously.* 

## How to reproduce

1. New dashboard
2. Fill in all inputs: Name, Description and template.
3. Create

## Environment

- [X] PostHog Cloud
- [ ] self-hosted PostHog, version/commit: please provide

**Comment by pauldambra** [comment]
Thanks for reporting this @Abdelilah-MOULIDA. We've released the fix for this. Feel free to reopen or comment here if it's still not right for you!
