### ISSUE TITLE
Allow 100% stacked area/bar chart

### ISSUE THREAD

**Issue by pauldambra** [PostHog/posthog#13728]
## Is your feature request related to a problem?

Sometimes you want to see your data  stacked to a percentage rather than absolute values

## Describe the solution you'd like

Use this chartjs plugin https://github.com/y-takey/chartjs-plugin-stacked100 (currently untested by us)

## Describe alternatives you've considered

Calculate totals and percentages ourselves and manually implement the chart alternative

## Additional context

customer request here https://posthogusers.slack.com/archives/C01GLBKHKQT/p1673866757328599

**Comment by mariusandra** [comment]
I think manually calculating and displaying percentages ourselves is the way to go. We'd likely want a "percentage mode" also on area charts for example... and more dependencies equals always more maintenance mess.

**Comment by Arun-chaitanya** [comment]
Can I pick this up @pauldambra? I have understood the feature and I can build it. If I have understood it clearly, there will be a new chart type (Stack Chart - Random name for now) under (**Total Value**) category

**Comment by pauldambra** [comment]
Hey @Arun-chaitanya PRs always welcome

I think it fits under time series as it's a type of time series bar chart

<img width="237" alt="Screenshot 2023-07-19 at 08 28 05" src="https://github.com/PostHog/posthog/assets/984817/16f03067-9ef4-49e1-995c-e0ce5c0253d3">

I'm not sure if it's better as a new type in that time series  section called "100 Stacked Bar" or as an option as config on a bar chart

So this top area 

<img width="1219" alt="Screenshot 2023-07-19 at 08 32 02" src="https://github.com/PostHog/posthog/assets/984817/a4dbcabb-79fd-4fc2-b5f4-fd728fcbcbe1">

would have an option "100% stacked"

My preference would be that second option and it's probably a smaller change too.

This is a larger change because it touches multiple chart types but you may be able to see a little of how we'd make the change here https://github.com/PostHog/posthog/pull/14337

**Comment by Arun-chaitanya** [comment]
@pauldambra Thanks for clarifying. I totally understand most of it now.
But can you clarify 
"it's probably a smaller change too.
This is a larger change because it touches multiple chart types but you may be able to see a little of how we'd make the change here https://github.com/PostHog/posthog/pull/14337"
In the first sentence you said it is a small change and next said it is a larger change. I got confused here 😅.

**Comment by pauldambra** [comment]
Ah, sorry. Poor writing on my part 😊 

# smaller change

It's a smaller change to add a config option to existing bar chart type, than to add a new bar chart type (I think)

# larger change

The linked PR is a larger change than I think this would need to be #14337 because it touches multiple chart types. However, it's also a little out-of-date as @thmsobrmlr has done lots of amazing work updating our insights

----

If I was approaching this I would probably 

1. use something like js fiddle to validate I can create this kind of bar chart using chart.js and config similar to or the same as in PostHog
2. change the posthog bar chart to accept a prop that switches it into that mode
3. add a check box to the UI that sets that prop and stores it in the query/filter so that the user's choice is saved with the insight

(there's sure to be more than one way to approach this though)

**Comment by Arun-chaitanya** [comment]
Got you @pauldambra. Can you assign the task to me? The task is clear to me now.

**Comment by pauldambra** [comment]
Feel free to keep the conversation going here, or to open a PR very early if you want feedback as you go. @Arun-chaitanya

**Comment by pauldambra** [comment]
Hey @Arun-chaitanya 

We don't traditionally assign issues to external folk. I've assigned it to myself so I don't forget about this. Have fun coding!

**Comment by Arun-chaitanya** [comment]
Got it @pauldambra . No issues.

**Comment by Arun-chaitanya** [comment]
@pauldambra here is the PR. https://github.com/PostHog/posthog/pull/16699 for the issue

**Comment by Arun-chaitanya** [comment]
Everything is fixed, but there is one minor issue(Not a blocker) from Chartjs library, i.e. when we calculate datalabels using [README.md, How to use datalabels plugin](https://github.com/y-takey/chartjs-plugin-stacked100#how-to-use-datalabels-plugin), we are facing a TypeError as you can see below screenshots. For now I have registered this issue in the chartjs github issues and suppressed ts-ignore in the codebase.
![image](https://github.com/PostHog/posthog/assets/44457256/4f5d2c48-606d-4178-84bb-e94bf914e5e4)
