### ISSUE TITLE
Can't use toolbar on two sites at the same time

### ISSUE THREAD

**Issue by mariusandra** [PostHog/posthog#1373]
## Bug description

I'm trying to use the toolbar on "app.mysite.com" and "www.mysite.com", but most constantly reauthenticate.

## Expected behavior

It should stay logged in on both sites.

## How to reproduce

1. Open the toolbar on app.mysite.com, authenticate, do stuff
2. Open www.mysite.com, see the toolbar, click on it to authenticate and do stuff
3. Go back to app.mysite.com, try to use the toolbar, but get taken to the authentication screen.
4. Go back to www.mysite.com, try to use the toolbar, but get taken to the authentication screen.
5. Go back to app.mysite.com, try to use the toolbar, but get taken to the authentication screen.
6. Go back to www.mysite.com, try to use the toolbar, but get taken to the authentication screen.
7. Go back to app.mysite.com, try to use the toolbar, but get taken to the authentication screen.
8. Go back to www.mysite.com, try to use the toolbar, but get taken to the authentication screen.
9. Go back to app.mysite.com, try to use the toolbar, but get taken to the authentication screen.
10. Go back to www.mysite.com, try to use the toolbar, but get taken to the authentication screen.

## Additional context

Came out in a customer interview

**Comment by Twixes** [comment]
Considering that now the toolbar is only shown when explicitly launched from "Launch Toolbar" in the app, I suspect we don't need to resolve this.
