### ISSUE TITLE
Suggestion: Rename "Insights" to "Product analytics"

### ISSUE THREAD

**Issue by corywatilo** [PostHog/posthog#13742]
PostHog has top-level nav items for Insights, Recordings, Feature flags, and Experiments.

3/4 of these map to products PostHog talks about on posthog.com. One of these is an outlier, and a holdover from a previous era.

Proposing "Insights" is renamed to "Product analytics".

As someone who knows PostHog all too well, I legit had trouble finding how to run a new product analytics chart/graph because of the labeling.

(You could also argue data from other categories are insights too.)

**Comment by mariusandra** [comment]
Trying it out for size:

<img width="1180" alt="image" src="https://user-images.githubusercontent.com/53387/212854022-a6f2ed69-9ab6-42e6-aefc-8b28a016ca09.png">
