### ISSUE TITLE
Unable to login after upgrade chrome to 84

### ISSUE THREAD

**Issue by Doflatango** [PostHog/posthog#1376]
## Bug description
Unable to login after upgrade chrome to 84.
Server does not output any error logs, by chrome print some messages in dev tools may related to this issue.

It's able to login in Firefox and Microsoft Edge.

## Additional context
chrome dev tools:
> A cookie associated with a cross-site resource at http://posthog.com/ was set without the `SameSite` attribute. It has been blocked, as Chrome now only delivers cookies with cross-site requests if they are set with `SameSite=None` and `Secure`. You can review cookies in developer tools under Application>Storage>Cookies and see more details at https://www.chromestatus.com/feature/5088147346030592 and https://www.chromestatus.com/feature/5633521622188032.

**Comment by timgl** [comment]
@Doflatango Hm very strange. We don't think it's related to that error message.

How have you deployed posthog? Is it a custom subdomain? Do you have SSL running?

**Comment by Doflatango** [comment]
Hi @timgl , this issue just happened in newly version chrome, because i'm now using Firefox(mobile) and Microsoft Edge(pc), both of them are able to login.

**Comment by timgl** [comment]
Okay, thanks for the update! Would you mind telling me 
- How have you deployed posthog?
- Is it a custom subdomain?
- Do you have SSL running?

Also could you check on the first request under the "cookies" tab whether the "sessionid" cookie has "secure" set?

**Comment by Doflatango** [comment]
> How have you deployed posthog?
Docker Swarm

>Is it a custom subdomain?
Yes.

>Do you have SSL running?
Yes.

>Also could you check on the first request under the "cookies" tab whether the "sessionid" cookie has "secure" set?
No.

![cookies](https://user-images.githubusercontent.com/3091033/89557464-7249be80-d845-11ea-951a-a5e58da54698.PNG)

**Comment by timgl** [comment]
Are you running with the `DEBUG` environment variable turned on by any chance?

Also are you running behind an nginx proxy?

**Comment by mariusandra** [comment]
Also, what do you see if on that tab you click "show filtered out request cookies".
We're trying to locate on `sessionid` cookie.. which might show up if you tick that checkbox. 
It's possible that the "Secure" flag is incorrectly set on it.

**Comment by Doflatango** [comment]
> Are you running with the DEBUG environment variable turned on by any chance?
No.

> Also are you running behind an nginx proxy?
Yes, behind traefik but not nginx.

@mariusandra Here is the capture after click login button.
![cookies](https://user-images.githubusercontent.com/3091033/89560283-5ba56680-d849-11ea-81a7-ae970d04cb27.PNG)

**Comment by mariusandra** [comment]
@Doflatango this obviously needs a better fix from our side, but I think you can get it working if you set the env variable `LOCAL_HTTPS=True`

**Comment by mariusandra** [comment]
To add to the previous comment, you should set [these two variables](https://github.com/PostHog/posthog/blob/1.12.0/posthog/settings.py#L73) like so:

```
DISABLE_SECURE_SSL_REDIRECT=False
LOCAL_HTTPS=True
```

The django setting `SESSION_COOKIE_SECURE = False` should be set to `True` and there's a mixup in the code with the variables.

**Comment by fuziontech** [comment]
Hey @Doflatango!

The fix (#1384)  is in master and the build for `latest` is complete on Docker Hub if you want to use the `latest` tagged docker container.

Release 1.12.1 was just cut as well and should be available soon on Docker Hub if you want to pin a version. I'll post again here once I see it available on Docker Hub.

**Comment by Doflatango** [comment]
@mariusandra @fuziontech Thanks!
I will upgrade to 1.12.1 after 1.12.1 available on Docker Hub.

**Comment by timgl** [comment]
Done, 1.12.1 is available :)
