### ISSUE TITLE
Retention definition & measurement 

### ISSUE THREAD

**Issue by paolodamico** [PostHog/posthog#1377]
Retention is the key metric that will let us know how PostHog is providing value over time, it'll also help us inform how and where we could potentially improve the product to provide more value. The first step is defining the metric that makes sense for PostHog.

>**Note**: This will be an iterative process, and it's likely that we'll have to change the metric as the product and our users evolve.

To define the retention metric that makes sense, we need to consider two components:
- **Frequency**. What is the natural time period that we expect our users to use PostHog? _We can answer this by considering what problem we're trying to solve (and for whom), and how often they experience that problem._
- **Core action**. What is the action that best indicates that we're driving value for our users?

The idea would be to establish some initial hypotheses, and then do some analyses on our historial data to try to validate them or disprove them, so please any insight that you may have would be super helpful!

In terms of ongoing measuring, I believe we'll need #1230 and #1344 to be completed before we'll be able to do this directly in PostHog. Given this and the quantitative analyses validation part, @timgl what do you think about creating a temporary replica DB and using Metabase to do this?

**Comment by timgl** [comment]
As per discussion on slack, we'll try to get #1230 and #1344 in as soon as possible so we can continue dogfooding

**Comment by paolodamico** [comment]
Conversation moved elsewhere, follow-up available on project, https://github.com/orgs/PostHog/projects/6
