### ISSUE TITLE
Ingestion code changes to emit to kafka on merges for short and long term `person` overrides

### ISSUE THREAD

**Issue by fuziontech** [PostHog/posthog#13776]

**Comment by fuziontech** [comment]
@hazzadous to write down what is blocking us here (constraints)

**Comment by hazzadous** [comment]
The main issue here is the `CHECK CONSTRAINT` we were expecting to save us from chains appearing in the mappings for person overrides isn't applied at commit and check constraints are not deferrable. Even if they were I believe that it would not be able to peek at other db changes so does not fix all race conditions.

Rather we should simply add a foreign key constraint to the persons table `uuid` column. Ideally we'd want a unique index on (team_id, uuid) but we don't have that. So we should add that, then add a foreign key to that, then when we delete persons from that table that will render rows still referencing this in the overrides as integrity errors.

If we go with soft deletes on persons table, then we'll want to change the reference to be to (team_id, uuid, is_deleted) thereby allowing soft deletes on this table as well as invalidating the foreign key references.
