### ISSUE TITLE
enhancement: Title in Password change form is ambiguous

### ISSUE THREAD

**Issue by iprithvitharun** [PostHog/posthog#13792]
The second title "Password" in the form would be clearer if it specifically mentions that it is a new password. Users could mistake it for re-entering the current password again. As it is, the title is open to more than one interpretation.

This also warrants a change in the related in-line error message.

<img width="683" alt="Screenshot 2023-01-18 at 11 25 29 PM" src="https://user-images.githubusercontent.com/58725708/213258111-b63d0a87-8703-461c-9fc7-ebb809accf87.png">

**Comment by pauldambra** [comment]
Thanks for the contribution @iprithvitharun
