### ISSUE TITLE
Sprint 1.44.0 2/2 - Jan 23 to Feb 3

### ISSUE THREAD

**Issue by lharries** [PostHog/posthog#13791]
# Global Sprint Planning

## 3 things that might take us down

1. Rate limits, had an issue with local evaluation of feature flags being hit. Team experimentation picking it up
2. Santize sub queries. Marius/Yakko on it
3. Recordings table is growing. Short-term fix can be make the tables bigger. Need to find a longer-term fix too. Team infra will pick up short-term fix next sprint as part of infra hero. Ben will evaluate a longer-term fix
4. Keys not having enough values. @fuziontech will review the urgency.

## Retro: Status of Outcomes from Previous Sprint

1. Data Exploration - get events table live to real users. Get pivot tables out for internal testing. Finish the last insight types. @mariusandra Why? Leftover from last time, blocker for PH3000, people want to explore data in ways we don't support. --> Good progress. Events table tested with real users.
1. Break down PostHog 3000 into next steps, and solve prerequisites (antd). @Twixes Why? PostHog 3000 is our Q1 OKR, and required to nail slick mode. To create an interface better suited for power users. --> Work continues. Loads of ants.
1. Performance: Property definitions, filters and data types @macobo Why? Event property definitions load slow, and person property definitions lack type information (e.g. string vs datetime), making some queries impossible for a few users. --> Karl on support & ill, now making progress, will partially carry over into "slick filters"
1. Internally test and then finish up Unified Network panel to gradually rollout to customers @alexkim205
why? - This rework brings lots of 3000-esque improvements and is a pre-cursor to Performance panel.
    - Decided on what it will look like. Now in the process of launching it
1. iOS Recording groundwork - project setup, working example recording to file @benjackwhite
why? - Get a head start on our hardest goal and answer the unknown questions
    - Ground work is done ✅ 
1. Hook up pricing pages to billing service for faster pricing iterations @kappa90 
why? So we can show different pricing to different cohorts and have faster pricing iteration
    - YAML method done and works for in-product. Website integrating rolling over
1. @ellie: Productionize US postgres replica, explore cutting over to it
why? Unify infrastructure
    - Spent time hiring instead - offer out! Will do next week
1. @ellie: Work with @kappa90 to improve scheduled billing jobs
why? Allow billing to run scheduled task with more visibililty/reliability
    - Spent time hiring instead - offer out! Will do next week
1. @danielxnj: NAT gateway per AZ, saves $$$
why? save $$
    - Done ✅ 
1. @danielxnj: Clickhouse backups in S3 to save $$$
why? Save $$
    - Still ongoing work, tricker than expected
1. Feature Flag resiliency https://github.com/PostHog/meta/pull/74/files @neilkakkar
why? If our DB is down, feature flags still return something
    - It's live but haven't tested it yet. Need to update client libraries in the next sprint.
1. JSON Flags, allow users to configure flag responses https://github.com/PostHog/posthog/issues/13144 @EDsCODE
why? People want to use feature flags for more things. Requested a lot.
    - Backend completed, finishing up the frontend now
1. Offsite @fuziontech 
why? Make sure we carry momentum from offsite. 
    - Came up with many PoE solutions and executing on it now

## Retro: What can we do better next sprint?

1.
2.
3.
4.
5.

## Support hero this sprint

Week 1: Paul H
Week 2: James G

## Plan: Proposed Goals for Next Sprint 

Each goal should have a single owner. Owner can only be an engineer.

1. Hook up pricing page to billing server @raquelmsmith (outstanding)
1. Rate limiting when customers are beyond payment limits with special guest @benjackwhite & @kappa90
1. Defaulting users into a paid plan on signup @kappa90
1. Data exploration: tiles on dashboards @pauldambra
    - Why? Last big piece in https://github.com/PostHog/meta/issues/81 to tie the unified vision together.
1. Data exploration: slick filters @mariusandra
    - Why? HogQL is powerful and soon https://github.com/PostHog/posthog/pull/13264. Make the HogQL editor slick.
1. PostHog 3000 prerequisites: continue yeeting ants @Twixes
    - Why? Q1 OKR. Also: we ship about 800kb of CSS. About 500kb of that is antd. Not slick.
1. Rate Limiting all API endpoints ([slack thread](https://posthog.slack.com/archives/C04JV0WRUBG/p1673864803243759)) @neilkakkar 
1. All other client and server libraries for resiliency and JSON payload @EDsCODE 
1. @guidoiaquinti: Finish up ARM usage, scale up the usage and make sure nothing breaks.
1. @ellie: Continuing working on postgres! Didn't quite go to plan last time
1. PoE “Person Overrides” ingestion shipped and queries enabled for team 2
    - why: Query Performance while maintaining Data Quality
1. Rollout Network panel to some beta users @alexkim205
    - why? We have been running it successfully internally last sprint and the final touches are there so lets get it out.
1. Turn on Recordings by default @alexkim205
    - why? Huge number of customers we are missing out on as they don't realise it isn't on by default.
1. Mobile Session Recordings published (alpha)
    - why? Makes sense to test what we have ASAP with real apps (e.g. PostHoger's apps)

**Comment by kappa90** [comment]
# Team Growth 🌱

## Retro
- We created a biweekly pairing session, which is extremely helpful
- Achieved a new Plans API together
- Finished migrating billing v1
- Pricing principles & pricing experiments RFCs
- Deprecated self-hosted billing on the billing service
- Fixed flickering billing warnings and Quick Start button

## Hang over items from previous sprint
- Verify email addresses @raquelmsmith
- Rate limiting (we decided to drop the current approach and restart together with pipeline and recordings folks) @kappa90
- Hook up billing tables to plans API (in-product one will be done by end of current sprint) @raquelmsmith 
- Deprecate the license server @kappa90 

## Planning

### High priority
- Hook up pricing page to billing server @raquelmsmith (outstanding)
- Rate limiting with special guest @benjackwhite & @kappa90 
- Defaulting users into a paid plan on signup @kappa90

### Bugs
- Nope

### Low priority / side quests
- Verify email addresses @raquelmsmith
- Billing emails @kappa90 
- Improve onboarding flow to explain better session recordings and autocapture @raquelmsmith

**Comment by mariusandra** [comment]
# Team Product Analytics next sprint

(~will be~was moved)

## Retro

- Data Exploration - get events table live to real users. Get pivot tables out for internal testing. Finish the last insight types. @mariusandra Why? Leftover from last time, blocker for PH3000, people want to explore data in ways we don't support. --> Good progress. Events table tested with real users.
- Break down PostHog 3000 into next steps, and solve prerequisites (antd). @Twixes Why? PostHog 3000 is our Q1 OKR, and required to nail slick mode. To create an interface better suited for power users. --> Work continues. Loads of ants.
- Performance: Property definitions, filters and data types @macobo Why? Event property definitions load slow, and person property definitions lack type information (e.g. string vs datetime), making some queries impossible for a few users. --> Karl on support & ill, now making progress, will partially carry over into "slick filters"

## New goals

- Data exploration: tiles on dashboards @pauldambra 
  *Why? Last big piece in [data exploration](https://github.com/PostHog/meta/issues/81) to tie the unified vision together.*

- Data exploration: slick filters @mariusandra 
  *Why? HogQL is powerful and soon [in every filter](https://github.com/PostHog/posthog/pull/13264). Make the HogQL editor slick.*

- PostHog 3000 prerequisites: continue yeeting ants @Twixes 
  *Why? Q1 OKR. Also: we ship about 800kb of CSS. About 500kb of that is antd. Not slick.*

Sidequests:
- Systematically audit queries @yakkomajuri 
- Pivot tables (possibly cont from this week) @mariusandra 
- Expand insight person drilldown views
- Other sources of data in live events view (switch to recordings)

**Comment by EDsCODE** [comment]
**Retro:**

- Feature Flag Resiliency @neilkakkar 
     - Decide updated
- Feature Flag Payloads @EDsCODE 
     - Decide endpoint updated
     - JS Lite implemented
     - Frontend in progress/ready for merge?
- UX @liyiy 
     - Tags
     - Rollout default https://github.com/PostHog/posthog/pull/13719#issuecomment-1386171465

Planning:
- Rate Limiting ([slack thread](https://posthog.slack.com/archives/C04JV0WRUBG/p1673864803243759))
- All other client and server libraries for resiliency and JSON payload

**Comment by ellie** [comment]
# 🚀 Infrastructure Team 🚀

Infra hero: @danielxnj 

## Retro
Sad that Guido will be leaving us, but happy that we've (potentially) filled the role fast

## Planning

@guidoiaquinti: Finish up ARM usage, scale up the usage and make sure nothing breaks.
@ellie: Continuing working on postgres! Didn't quite go to plan last time

**Comment by tiina303** [comment]
#  Team pipeline🚰 

## Retro
Goal was: Offsite why? Make sure we carry momentum from offsite.

Jams - Offsite was a ton of fun and very intense. We got quite a bit done. We even did some fire fighting. We laughed. We cried. We bonded.
Tiina - Offsite was very productive and intense. Happy that we have a plan for PoE
Tomas - Offsite was a great introduction to how Team Plumbers works. Also helped me dig into some complicated topics like PoE.
Xavier - Proof that it’s good to be in the same room from time to time.

## Sprint planning

Luigi: @xvello 

PoE “Person Overrides” ingestion shipped and queries enabled for team 2
why: Query Performance while maintaining Data Quality

Fallback is to focus on Squash logic if queries get held up

**Comment by benjackwhite** [comment]
# Team SessiOS Recordings

## Retro

- @benjackwhite Felt like we are less "shipping" than before - good to keep an eye on it.
- @alexkim205 Agrees with rolling out Inspector panel speed, Performance is a little more careful regarding ingestion. 

## Hang over items from previous sprint

- Internally test and then finish up Unified Network panel to gradually rollout to customers 
(Will be out by end of sprint)

## Planning

### High priority

- Rollout Network panel to some beta users @alexkim205 
why? We have been running it successfully internally last sprint and the final touches are there so lets get it out.

- Turn on Recordings by default @alexkim205 
why? Huge number of customers we are missing out on as they don't realise it isn't on by default.

- Mobile Session Recordings published (alpha)
why? Makes sense to test what we have ASAP with real apps (e.g. PostHoger's apps)


### Bugs
-

### Low priority / side quests

- Network release todo
  - Look into TTL on CH table

- Ingestion rate limiting @benjackwhite @kappa90 See [issue](https://github.com/PostHog/product-internal/issues/427)
