### ISSUE TITLE
(recordings): Allow filtering by recording properties like click count

### ISSUE THREAD

**Issue by benjackwhite** [PostHog/posthog#13803]
## Is your feature request related to a problem?

All of our current filtering of recordings is based on the related events which is pretty powerful but misses out on some of the other interesting elements that are unique to a recording such as:

* Click count
* Keyboard press count
* Console log error / warn

We should expose those as filterable properties to allow people to do things like "Show me recordings on page X where the user clicked at least once".

## Describe the solution you'd like

Addition to the Filtering area to allow filtering on these Recording-only properties.

## Additional context

There was also a request for **sorting** based on these properties. This may end up being pretty difficult from a technical perspective as our storage is optimised for chronology but would be interesting to see the use cases here.

**Comment by Samrose-Ahmed** [comment]
I would like this because it lets me quickly view more relevant recordings, and skip over recordings with few interactions.
