### ISSUE TITLE
Allow targeting feature flags based on distinct ids

### ISSUE THREAD

**Issue by janpieterz** [PostHog/posthog#13808]
## Is your feature request related to a problem?

I am testing some feature flags and playing around, seems I can't target feature flags on distinct ids and have to add people to a cohort.

## Describe the solution you'd like

It would be great to add a person to a feature flag condition via their distinct id, instead of any other property **but** distinct id.

## Describe alternatives you've considered

Cohort based, adding the data again as an extra property, static based (but no way to just use UI so now we need to manage a CSV file)

#### *Thank you* for your feature request – we love each and every one!

You're welcome! I tried filing this as a question on the /questions page but the login there gave me some issues.

**Comment by jurajmajerik** [comment]
Hey @janpieterz, this is now possible!

**Comment by janpieterz** [comment]
Awesome, thanks @jurajmajerik
