### ISSUE TITLE
Wrong PostHog-Recording-URL displayed in Sentry

### ISSUE THREAD

**Issue by chantter** [PostHog/posthog#13822]
## Bug description

I integrated PostHog with Sentry and I get the wrong URL for `PostHog-Recording-URL` in Sentry. 

<img width="569" alt="Screenshot 2023-01-19 at 15 40 55" src="https://user-images.githubusercontent.com/63065780/213471323-d1b54905-fc9e-4e38-ba6c-85e5caa1cd83.png">

Current
```https://eu.posthog.com/recordings/#sessionRecordingId=<ID>```

Expected
```https://eu.posthog.com/home#sessionRecordingId=<ID>```

Is the issue on your side or I should write to Sentry?

## How to reproduce

1. Integrate PostHog with Sentry
2. Every issue in Sentry should contain broken link

## Environment

- [x] PostHog Cloud
- [ ] self-hosted PostHog, version/commit: please provide

**Comment by benjackwhite** [comment]
Indeed an issue our side. [PR here](https://github.com/PostHog/posthog-js/pull/507) to update the JS to the correct URL and I'll see about adding a fix to back support the old URLs
