### ISSUE TITLE
Automated/scheduled rollouts of feature flags

### ISSUE THREAD

**Issue by annikaschmid** [PostHog/posthog#13842]
With automated rollouts, you will be able to roll out a feature flag gradually based on a pre-defined schedule.

Features considered:
- Automatically roll out a flag on a specified date
- Automatically roll out a flag over a specified time frame

[The Experimentation Team](https://posthog.com/handbook/small-teams/experimentation) will be leading this work. We'd love to hear user feedback, as well as ideas for stretch goals or implementation.

If you like this idea, please leave a 👍 or ❤️ reaction on this post to vote for it -- your votes and feedback help us prioritize what to work on next!

**Comment by annikaschmid** [comment]
Since this feature is part of our Q1 OKRs, I have created an issue for it and will add it to our public roadmap.

**Comment by jurajmajerik** [comment]
We'll be releasing this feature soon! If you'd like to be included in the early testing group, please email me at juraj @ posthog .com.

**Comment by jurajmajerik** [comment]
Hey everyone, this has been released! More here: https://posthog.com/docs/feature-flags/scheduled-flag-changes
