### ISSUE TITLE
Funnel groups modal search doesn't work correctly

### ISSUE THREAD

**Issue by yakkomajuri** [PostHog/posthog#13853]
Searching by group name on the funnel modal for converted/dropped off groups yields incorrect results in cases where the search term is not present in the person's properties. We don't actually search for group names anywhere.

------

From Slack:

> I’ve gotten to the bottom of this bug.
> We search based on an email property, and that matches on the first event because it was performed by someone with the email containing <search> . It doesn’t match on the second event because billing subscription activated is an event that uses the Stripe ID, and has no email or other info besides the group link.
> It then matches on the dropped off because we check if the conversion happened and if it didn’t we mark as having dropped off.
> 
> Unfortunately, this is not an easy fix. I even suspect this was punted in the past.
> 
> The placeholder on the search says “Search for persons” i.e. it explicitly leaves out groups. Searching for groups is easy if we have group properties on events for everyone but extremely tricky otherwise so need to establish that first.

https://posthog.slack.com/archives/C0368RPHLQH/p1673546003909909

**Comment by thmsobrmlr** [comment]
Closing, as I think this was resolved by the associated PR.
