### ISSUE TITLE
Review

### ISSUE THREAD

**Issue by Ricrl** [PostHog/posthog#13869]
## In what situation are you experiencing subpar performance?

*Please describe.*

## How to reproduce

1.
2.
3.

## Environment

- [ ] PostHog Cloud
- [ ] self-hosted PostHog, version/commit: _please provide_

#### *Thank you* for your performance issue report – we want PostHog to go supersonic!

**Comment by Twixes** [comment]
Hey @Ricrl! This looks like an issue created accidentally, so I'm going to close it. If you do want to report a performance problem however, please update the message with info – we'll then reopen this issue.
