### ISSUE TITLE
Cookie blocked by chrome

### ISSUE THREAD

**Issue by yormy** [PostHog/posthog#1391]
I just pulled your latest version and ran the docker install
I could create an account, but I could not login (after providing the credentials the screen is cleared)
This is probably related to your cookie setting (We had the same issues on our platforms recently)
Logging in with firefox works...

Chrome reports:

Indicate whether to send a cookie in a cross-site request by specifying its SameSite attribute
Because a cookie's SameSite attribute was not set or is invalid, it defaults to SameSite=Lax, which prevents the cookie from being sent in a cross-site request. This behavior protects user data from accidentally leaking to third parties and cross-site request forgery.

Resolve this issue by updating the attributes of the cookie:
Specify SameSite=None and Secure if the cookie should be sent in cross-site requests. This enables third-party use.
Specify SameSite=Strict or SameSite=Lax if the cookie should not be sent in cross-site requests

**Comment by timgl** [comment]
Similar to your other ticket, this could be related to having DEBUG turned on or incorrectly set up the proxy. Let me know if that's helpful :)

**Comment by mariusandra** [comment]
I think this is an issue with `posthog-js` that was solved in 1.3.8. The latest "posthog" is on a lower version of JS, but the version that will be released this week should contain this fix.

**Comment by yormy** [comment]
Hmm... if it is my setup... why would it then work without problems in firefox
The cookies that posthog are set are null which could be the issue with the newer chrome versions

**Comment by timgl** [comment]
@yormy Because Chrome recently made secure mandatory. We correctly set the tokens, as long as you're not running the `DEBUG` variable and you're running the latest version of PostHog

**Comment by yormy** [comment]
Apparently I am still running 1.12 instead of 1.12.1.. .thanks

**Comment by mariusandra** [comment]
I guess this is solved by upgrading to `1.12.1`? @yormy feel free to reopen if there's still some issue remaining.
