### ISSUE TITLE
Mixed contents ?

### ISSUE THREAD

**Issue by yormy** [PostHog/posthog#1392]
my posthog is running on a ssl domain
my site is running on a ssl domain

yet I get the following when I want to load the toolbar for element selection
Blocked loading mixed active content “http://posthog.example.it/static/toolbar.js?_ts=1597060202369

**Comment by timgl** [comment]
You are likely either running with the `DEBUG` variable turned on, or running behind a proxy with incorrect configuration. Please see [running behind proxy](https://posthog.com/docs/deployment/running-behind-proxy) for more info.

Let me know if that helped!

**Comment by mariusandra** [comment]
This should also get easier once PR #1387 is merged. 

In [one commit](https://github.com/PostHog/posthog/pull/1387/commits/0861e5f8715abb4f7cca01af35da5caf62bab637#diff-401475f113483ddad55997242d67afedL100) I removed the "apiURL" variable from the `editorParams` hash given by /api/user... and instead take directly the URL that the JS library is initialised with.

The server used to return the URL with http:// only under certain conditions.

**Comment by yormy** [comment]
@timgl : Awesome work you created here... really love it

**Comment by timgl** [comment]
I think this is closed now, let me know if you run into any other issues!
