### ISSUE TITLE
Queries on Dashboards

### ISSUE THREAD

**Issue by pauldambra** [PostHog/posthog#13927]
A place to hold the to-do list for adding queries to dashboards

## Describe the solution you'd like

In order to make migration for Filter to Query easier we want to add a JSON column to the Insight Model that can hold a query

Insight stops meaning "something with filters that draws a graph or table" and starts meaning "something saved that queries your data"

consequences:
 * migration from filter to query is straight-forward to roll backwards and forwards
 * a bunch of behaviour remains in place for free
    * e.g. layout, moving between dashboards, naming, renaming, descriptions, tags, and more 
 * anything that wants to be both a query and be on a dashboard (without extra code) needs to be a query saved to an insight model
 * ???
 
Can be done without backend querying:

 - [x] if we're writing JSON to the DB can we avoid writing messy JSON (e.g. https://github.com/supabase/pg_jsonschema#try-it-out)
 - [x] is it better to validate the schema at the API layer than in the DB (or do we do both?)
 - [x] if we have JSON schema for a query can we generate the TS types from that
 - [x] or since we have TS types can we generate the JSON schema from that
 - [x] how can we keep TS code that converts filter <-> query in sync with python code that does the same
 - [x] UI to save and name a query (partly #14027 )
 - [x] AddToDashboardModal needs to handle insights and queries
 - [x] saved insights page should (initially) not show insights that have no filter
 - [x] DashboardTiles need to know how to draw DataTable query / Insight from Query not filter (https://github.com/PostHog/posthog/pull/13980)
 - [x] export to CSV works for datatable query? (https://github.com/PostHog/posthog/pull/13997)
 - [x] dashboard templates needs to be able to handle query tiles
 - [ ] don't show edit chrome if no edit permissions
 - [x] don't show edit chrome in insight view mode
 - [x] don't show edit chrome in dashboard view mode
 - [x] replace inline editor button with an "open in insight editor button" see https://github.com/PostHog/posthog/pull/14709
 - [ ] add data table tab? is that different to sql tab?

Not strictly to do with dashboards
- [x] allow text based editing of insight tabs see https://github.com/PostHog/posthog/pull/14709#issuecomment-1466155855

 Needs backend querying:
 - [x] sharing dashboards with queries on them
 - [x] export to image works for query tiles?
 - [ ] merging dashboard filters and tile queries
 - [ ] convert dashboard filters to dashboard queries
 - [x] generate cache key for query based insights
 - [ ] merge dashboard filters onto tiles
 - [ ] query on the backend so insight caching can work with them

**Comment by pauldambra** [comment]
@thmsobrmlr wasn't sure where to brain dump from our conversation. I thought this was as good a place as any :)

**Comment by mariusandra** [comment]
Nice list! We already generate a json schema from the typescript types and use it to power the query editor. The next step is to generate some python to receive and validate this directly on the backend...

**Comment by pauldambra** [comment]
We're already using json schema in python so we'll stick with that and not add DB validation 

(context: https://posthog.slack.com/archives/C0368RPHLQH/p1674830329341779)

**Comment by pauldambra** [comment]
working on shared/exported insights/dashboards will require 1 of 2 things

1) the front-end being able to make API calls when shared/exported
    - this would be new for us, although we are signed JWT based so is achievable
    
2) the back-end knowing how to handle queries
    - and we probably need to do this regardless of if we do 1. So, let's spike 2 first
    
A shared/exported (exported from here-on-in) insight doesn't query the data, it loads any results from the cache.

Our cache only knows how to load filter-based insights. Thankfully after the last round of caching changes there's one place to get that data `fetch_cached_insight_result` in `fetch_from_cache.py`. So, if we can get query results into the cache everything will just work™️ 

In order to do that we need to 

1) generate cache keys for query based insights

When we switched to the new insight cache we effectively busted the cache for all insights and it was fine. So, we can let a cache key for a query not match a cache key for the same insight's filter. 👨‍🍳 👌 

2) have dashboard date range affect query results

This needs the query to be moved into the backend so we can use the schema to know where to push the data

3) have dashboard filters affect the query results

This needs the query to be moved to the backend, and a way to convert and combine filters into queries

This won't always make sense. If I have a persons table on the dashboard and the filter is for an event property. What should happen? 

The first step is probably to let the query based tile not be affected by the filter - and make this clear to the user

All dashboard filters should be convertable to insight query filters since they're the same control. So we need to add a query field to dashboards and migrate to it as we have/are with insights. 

4) updating the cache should prefer query over filter when present, and should store those results against a cache key

This needs the query to be moved to the backend

**Comment by mariusandra** [comment]
> the front-end being able to make API calls when shared/exported

Let's not make shared exports make API calls.

- Which user would virtually be making them?
- How do we even share a token privately yet publicly?
- Do we want the API user to change the insight timerange? What about other filters?
- Which API endpoints should we enable/disable? 
- What about rate limiting? Throttling? Caching?

There are too many problems that will receive half-implemented workaround and cause us a lot of sadness long term. Let's not make our lives harder by choice 😄.

> Have dashboard filters affect the query results. This needs the query to be moved to the backend, and a way to convert and combine filters into queries. This won't always make sense. If I have a persons table on the dashboard and the filter is for an event property. What should happen?

We can punt on this, and only have the query affect the insights for now. Later on we can introduce custom filter and variables, which will let users control this themselves.

The "what happens to event properties?" question is something that we should also figure out for the "universal search" data table.

**Comment by thmsobrmlr** [comment]
Closing this as we have query based dashboard tiles now.
