### ISSUE TITLE
Create FOSS repository

### ISSUE THREAD

**Issue by timgl** [PostHog/posthog#1394]
## Is your feature request related to a problem?

With #1390 we introduce an "ee" folder that is copyrighted. However you are able to remove this repository easily so you are running complete open source software.

## Describe the solution you'd like

To make this option obvious, we should create a posthog-foss repository that automatically syncs over all commits to master and copies them into this repository, but removes the ee folder

## Describe alternatives you've considered

Doing this manually, this would be tedious.

## Additional context

This is exactly how GitLab has it set up

**Comment by timgl** [comment]
@ungless Thoughts? Might be something fun to pick up at some point, I assume it'll involve GitHub actions.

**Comment by timgl** [comment]
Update: repository created: https://github.com/PostHog/posthog-foss.

Also created automatic docker images https://hub.docker.com/r/posthog/posthog-foss

All we need is a script/action to push all new commits from this repo on master into the posthog-foss repo and remove the ee folder

**Comment by ungless** [comment]
I'll starting having a look at this.

**Comment by ungless** [comment]
Here's my current implementation plan:

- [x] Write GH action to sync commits on cron excluding `ee/`
- [x] Create branch 'sync' in posthog/posthog-foss, and add this workflow
- [x] Test

**Comment by timgl** [comment]
Also just realised, is there a way of syncing up tags as well so we can automatically tag releases?

**Comment by ungless** [comment]
Yep the action I've written so far takes care of that.

**Comment by timgl** [comment]
Legend

**Comment by ungless** [comment]
Resolved on `sync` branch at https://github.com/PostHog/posthog-foss
