### ISSUE TITLE
Move EE frontend code to ee folder

### ISSUE THREAD

**Issue by timgl** [PostHog/posthog#1395]
## Is your feature request related to a problem?

Once #1390 is merged we should be able to have frontend code in that folder too, without breaking the build if that folder is missing.

## Describe the solution you'd like

Automatically import any scenes(?) from the ee folder if that folder exists, ignore if not.

## Describe alternatives you've considered

Have all frontend code in the rest of the repo

## Additional context

@mariusandra Thoughts on how to actually do this with webpack/es modules?

**Comment by paolodamico** [comment]
Based on the discussion here https://github.com/PostHog/company-internal/issues/131 I believe we're no longer doing this.
