### ISSUE TITLE
Password reset token is always expired

### ISSUE THREAD

**Issue by FUSAKLA** [PostHog/posthog#1398]
## Bug description
If trying to reset the user password it always ends up with message `This password reset link has expired. Please request a new one.` This happens right after resetting the password.

## Expected behavior
Show me the form to set the new password.

## How to reproduce

1. Reset the passwrod
2. Click the link in received email

## Environment
Self managed PH running in Kubernetes/Docker using official docker images in version 0.12.0

## Additional context
Neither `PASSWORD_RESET_TIMEOUT_DAYS` or `PASSWORD_RESET_TIMEOUT` settings affects this behavior.
Looking at the link in the email it looks like `https://foo.bar/accounts/reset/MQ/5iy-xxxxxxxxxxx/`. Reading the Django code the first part of the token (last part of the path) should be number of days since 2001 encoded using base36 (since Django 3.1 this actually changes to number of seconds but PH 0.12.0 uses Django 3.0.7). Decoding the `5iy` gives `7162` and the current number of days is also `7162` so the issue is not caused by actually expired token. 

Looking at the Django code the function [`check_token`](https://github.com/django/django/blob/44da7abda848f05caaed74f6a749038c87dedfda/django/contrib/auth/tokens.py#L23) it verifies also the token. 

So inspecting what actually happens:
1. Going to the link with the browser console on
1. Got response `302 Found` and in the response `location` header i see `/accounts/reset/MQ/set-password/`.
1. Get redirected to the `https://foo.bar/accounts/reset/MQ/set-password/` and I get the message `This password reset link has expired`.

I do not think this redirect is OK even though I'm not completely sure how it happens, but I suspect that than the string `set-password` in the URL path is checked as a token end evaluated as invalid and thus I get the message.

**Comment by Algogator** [comment]
Hey @FUSAKLA is this still an issue?
And is your mail server setup locally?

**Comment by FUSAKLA** [comment]
Hi, yes we have our own mail server, but I suppose the mail server is not the issue.
As described the email came OK as expected and the link seems to be correct also (valid first part of hash and with timestamp etc) but then something weird happens with the redirects. 

Are you able to reproduce it on your setup or should I look for something related to our setup?

**Comment by Algogator** [comment]
@FUSAKLA I did a fresh install on my system today with the default setup (docker-compose) and it works just fine. 
What does your Kubernetes cluster look like currently? If you have any logs to share that would help immensely too!

Edit: Also reading through the code I doubt that Django is reading "set-password" as the token (https://github.com/django/django/blob/4f61810751751b8c5070ce038ea57e949650e9e3/django/contrib/auth/views.py)

**Comment by FUSAKLA** [comment]
Trying it now, it works just fine. Weird :thinking: 
Maybe it was some forgotten cookie issue? Who knows.. 

Sorry for the false alarm, I'm closing this since even I cannot reproduce it anymore :tada:
