### ISSUE TITLE
README dashboard screenshot link is broken

### ISSUE THREAD

**Issue by ungless** [PostHog/posthog#1399]
## Bug description

- Clicking on `PostHog dashboard screenshot` goes to a blank page.

link:
![image](https://user-images.githubusercontent.com/8397061/89887336-fabdbb80-dbc5-11ea-92b2-66c13ff0f90f.png)

blank page:
![image](https://user-images.githubusercontent.com/8397061/89887253-d9f56600-dbc5-11ea-80a0-5d617884e78a.png)

## Expected behavior

- should go to image

**Comment by yakkomajuri** [comment]
Yeah I need to get on this #1353

**Comment by ungless** [comment]
Closing as part of existing issue referenced above.
