### ISSUE TITLE
Pre HN/big launch

### ISSUE THREAD

**Issue by timgl** [PostHog/posthog#14]
**App functionality**

- [x] Add alias functionality

**Website**
- [x] Obvious divide between hosted PostHog.com and self-hosted
- [x] Self-serve sign up to PostHog.com (really just a link to /signup)
- [ ] (maybe?) At least 10 self-serve customers so we know flow is working (Ellie / Ian)
- [ ] FAQ with every objection HN commenters gave to other self-hosted stuff (Mattermost, Piwick)

**License**
- [x] Finalize license choice (BSL / Open core / Other)
- [ ] Documentation on how to contribute to the project

**Libraries**
- [x] Open source our tracking library, ideally with references to mixpanel removed (except license)
  - [ ] (maybe?) work out a way of tracking without cookies so we don't have to comply with donottrack etc
  - [x] #20 Trim down/rationalise information sent from browser enhancement
- [x] (maybe?) Python library
- [ ] (maybe?) Ruby library

**Self deployment**

- [ ] At least one self-hosted user
- [ ] (maybe?) Some way of doing updates easily as there will be a ton of feature building
- [x] Docker package
- [x] Make secret-key an environment variable
- [x] Documentation on how to self-host
- [x] (maybe?) Some way of restricting sign-ups to email/something else
- [x] (maybe?) deploy to heroku button
- [x] Create screen to create super user first time a user logs in

**Comment by timgl** [comment]
cc @jamesefhawkins  just edit the description to add more stuff

**Comment by jamesefhawkins** [comment]
"Some way of restricting sign-ups to email/something else" - what do you mean by this?
