### ISSUE TITLE
Funnel insight should not use hidden interval

### ISSUE THREAD

**Issue by thmsobrmlr** [PostHog/posthog#14017]
## Bug description

The funnel insight uses a hidden interval that was set in one of the other insight types, which leads to unexpected results.

## How to reproduce

1. Create a new funnel, by adding a second funnel step e.g. Autocapture on the funnel insight page. Note the results.
    <img width="459" alt="Screenshot 2023-01-31 at 13 04 58" src="https://user-images.githubusercontent.com/1851359/215755141-e7043950-e44e-4e3f-8c63-05878ef134ec.png">
2. Navigate to the trends insight and set the interval (grouped by...) to "hourly"
3. Navigate back to the funnels insight and note that the results have changed, but the interval is not visible
    <img width="476" alt="Screenshot 2023-01-31 at 13 06 44" src="https://user-images.githubusercontent.com/1851359/215755505-5ee22f02-737b-45f3-accb-9afc57495cdd.png">

## Additional context

- The issue came up in this community slack thread https://posthogusers.slack.com/archives/C01GLBKHKQT/p1675160338520659
- We actually do use and expose intervals for the historical trends funnel

**Comment by Twixes** [comment]
Is this perhaps just a matter of caching, or does the SQL actually differ?

**Comment by thmsobrmlr** [comment]
Imo it’s just a frontend issue, where we‘re sending an api param that we don’t show.
