### ISSUE TITLE
Event Explorer gives There was an error completing this query

### ISSUE THREAD

**Issue by weyert** [PostHog/posthog#14036]
## Bug description

The Event Explore stopped working an throws the error  Error completing this query due to a 500 error being returned from the `/query`-endpoint.

## How to reproduce

1. Navigate https://app.posthog.com/events
2. See the error `There was an error completing this query`

## Environment

- [x] PostHog Cloud
- [ ] self-hosted PostHog, version/commit: please provide

## Additional context

The `/query`-endpoint fails with a internal server error with the following
response:

```json
{"type":"server_error","code":"error","detail":"A server error occurred.","attr":null,"error_event_id":"3d2b5519fbf24ba6b551ee29e64f2716"}
```

```json
{
    "type": "server_error",
    "code": "error",
    "detail": "A server error occurred.",
    "attr": null,
    "error_event_id": "c2daa27ac88e49edbc75a00644aa0d4b"
}
```

**Comment by fuziontech** [comment]
Some extra context here: I had @weyert run his failing query a few times and it seems to align with this sentry exception:
`CHQueryErrorUnknownIdentifier /api/projects/{parent_lookup_team_id}/query/`
https://sentry.io/organizations/posthog/issues/3908049721/?query=is%3Aunresolved&referrer=issue-stream

**Comment by weyert** [comment]
I did create two new projects today. Not sure if that could cause a problem.

**Comment by fuziontech** [comment]
No I don't think it's that. It looks like whatever query you are running we are having a hard time building the CH query on the backend. Do you happen to have the filters handy and are they something you can share?

**Comment by weyert** [comment]
I don't know if queries of other projects cause trouble but my newly project that I created earlier today is showing the error. And I haven't been able to define a filter on the Events Explorer page yet. The data management page does show a few event names so it did ingest some events?

But yeah, it appears to happen to all my projects at the moment. I did play in a other project with Insights and the BigQuery Exporter plugin. But I haven't done  much exciting in this Test 1 project yet besides sending events via `posthog-js` and `posthog-node`.

![CleanShot 2023-02-01 at 02 11 51@2x](https://user-images.githubusercontent.com/7049/215928376-fc95d37f-c9ea-4c95-bc38-62c730df50b3.png)

**Comment by fuziontech** [comment]
Tagging @mariusandra just in case he hasn't seen this yet

**Comment by mariusandra** [comment]
Saw it, even tagged you on a quick fix: https://github.com/PostHog/posthog/pull/14039 - but merging has been blocked all day 🤷. Help pls 😅

**Comment by weyert** [comment]
The events are still getting ingested, right?

**Comment by fuziontech** [comment]
Yes! Events are all good. We just had to pause ingestion in order to move our massive primary database's cloud provider. All of the backed up events are flowing through the system now and should be flooding in over the next few hours.

**Comment by weyert** [comment]
Happy to hear that!

I also just noticed that the Export button appears to be working but display events does not. Pretty weird.

**Comment by weyert** [comment]
I was able to talk with @mariusandra and he disabled some flag which makes it work again so that's nice :)

**Comment by mariusandra** [comment]
Hey all, so I disabled the data exploration feature flag. We'll get it back next week after some bigger changes. This means that you won't be able to use HogQL/formulas in the "live events" page right now. If you still want to, open https://app.posthog.com/query/ and choose e.g. the "TotalEventsTable" to make more interesting queries.

**Comment by weyert** [comment]
Thanks again @mariusandra! I have admit I didn’t know what HogQL was until yesterday.

**Comment by Twixes** [comment]
I think this is no longer an issue, but please ping if anything comes up!
