### ISSUE TITLE
Add reminder re secret key to the terminal message with docker

### ISSUE THREAD

**Issue by jamesefhawkins** [PostHog/posthog#1404]
## Is your feature request related to a problem?

When using Docker Compose, the docker-compose.yml file should be updated with the secret key unique to people's instance. 

## Describe the solution you'd like

I'd suggest this is somehow automated OR at least we put a message into the system or the terminal if the placeholder secret key is being used in production.

## Describe alternatives you've considered

People could read the docs.

**Comment by yakkomajuri** [comment]
Reminder + system exit on placeholder key is now done. #1426
