### ISSUE TITLE
No Await with capture or any other method ?

### ISSUE THREAD

**Issue by robinbdru** [PostHog/posthog#14044]
Hey PostHog community,

I just started using PostHog with Node JS, it feels weird not using the library with the async/await syntax.

For example with the capture method :

```javascript
posthog.capture({distinctId: "id-124", event: "test-event"});
```

## Describe the solution you'd like

Couldn't we use something like Supabase instead:

```javascript
const {event, error} = await posthog.capture({distinctId: "id-124", event: "test-event"});
```
=> Unless I have absolutely no understanding of how PostHog works, which is very likely, it would allow us to get the answer to a promise and know what's going on.

## Describe alternatives you've considered

Nothing at the moment.

## Additional context

Using it with Serverless AWS Lambda.

**Comment by benjackwhite** [comment]
PostHogs's client SDKs are all designed to queue and batch requests in the background to optimise API calls and network time. For lambda environments (or also when shutting down a standard Node.js app) we provide a method `.shutdownAsync` which can be awaited and ensures the queued events are all flushed to the API.

So it's like
```js
export const handler() {

 posthog.capture({
      distinctId: 'distinct id',
      event: 'thing happened'
  })

 posthog.capture({
      distinctId: 'distinct id',
      event: 'other thing happened'
  })

  // So far 2 events are queued but not sent

  // Calling shutdown, flushed the queue but batched into 1 API call for max efficiency
  await posthog.shutdownAsync() 
}

```

**Comment by benjackwhite** [comment]
The key thing here is that _typically_ application code doesn't need PostHog to have finished sending the result to continue so the SDK is designed to be as non-blocking as possible.

**Comment by pauldambra** [comment]
@pjhul @benjackwhite seems this FaaS use-case question gets asked a lot.... we should have a section in the node-js docs covering this (if we don't already 🙈 )

**Comment by robinbdru** [comment]
It makes sense, thank you very much @benjackwhite .

Sorry @pauldambra , I searched a lot in the docs, event with cmd+f and not found anything.

Nonetheless, your docs is awesome and I loved the onboarding process.

<img width="937" alt="SCR-20230201-fui" src="https://user-images.githubusercontent.com/54135856/216017616-48dc86a4-2a4b-4b78-a191-bc59d297b2f4.png">

**Comment by pauldambra** [comment]
It occurred to me that @benjackwhite had already done the hard work of understanding and describing this, so I could go for the glory of opening the PR and making it look like I understand it 🤣 

https://github.com/PostHog/posthog.com/pull/5190

**Comment by robinbdru** [comment]
I apologise, I'm not a native English speaker, I don't know if your messages are humour or irony. 

I didn't mean to imply that the documentation was badly written or anything, being a great beginner I probably misunderstood.

I promise I'll make the effort to read everything thoroughly before posting an issue. PostHog looks amazing to use and I look forward to mastering it. @benjackwhite  @pauldambra

**Comment by benjackwhite** [comment]
No need to apologize at all! The method I mentioned isn't actually in the docs so this is a great issue because it highlights the gaps we have :D Definitely humour coming from our direction - we are always super grateful of issues like this 🙌

**Comment by pauldambra** [comment]
>I apologise, I'm not a native English speaker, I don't know if your messages are humour or irony.
> I didn't mean to imply that the documentation was badly written or anything, being a great beginner I probably misunderstood.

Ah, so sorry! it was humour. And not a complaint about you or this issue at all!

Several other people have found the same behaviour in the SDK confusing. And I was happy to have the opportunity to improve the documentation (which we're very proud of). In a not clear way I was also thanking @benjackwhite for his great answer to you which I could simply copy into a PR.

Thank you again 🙏
