### ISSUE TITLE
Upgrade to RRWeb 2

### ISSUE THREAD

**Issue by benjackwhite** [PostHog/posthog#14053]
## Is your feature request related to a problem?

RRWeb 2 is still in alpha but for many customers it appears that it would already provide an improved experience thanks to the number of bugfixes and improvements only found in that version

## Describe the solution you'd like

If we implement https://github.com/PostHog/posthog-js/issues/523 then we can create multiple exported bundles of the rrweb recorder, and allow the frontend to load the appropriate recorder, depending on some config (probably client side for now).

We could simplify the logic in [posthog](https://github.com/posthog/posthog) as we would simply be copying the dist from posthog-js. 

## Additional context

Related issues that are blocked due to rrweb version:
- https://github.com/PostHog/posthog-js/issues/517
- https://github.com/PostHog/posthog-js/issues/514
- https://github.com/PostHog/posthog/issues/12690
- https://github.com/PostHog/posthog/issues/13255
- https://github.com/PostHog/posthog/issues/10021

## Remaining tasks
- [x] Setup posthog.com page detailing Recorder V2, how to opt in and what to expect @benjackwhite 
- [x] Turn on Recorder V2 for new projects @benjackwhite
- [ ] Email campaign for existing Recording users on V1
- [ ] Rollout by "force" for all customers with clear indication of how they can rollback if they encounter issues

**Comment by pauldambra** [comment]
We have upgraded to rrweb 2
