### ISSUE TITLE
Queries are over-eagerly joining `person` table

### ISSUE THREAD

**Issue by macobo** [PostHog/posthog#14061]
## In what situation are you experiencing subpar performance?

Joining too many tables can have a negative effect on performance as:
1. JOINs in ClickHouse are expensive
2. Due to triggering https://github.com/ClickHouse/ClickHouse/issues/45895 we stop doing aggregation on shards but instead send data over to the coordinator

## How to reproduce

1. Create a static cohort
2. Go to trends, query filtering by that cohort, visualization type number
4. Check the SQL

## Environment

- [x] PostHog Cloud
- [ ] self-hosted PostHog, version/commit: _please provide_

## Additional context

The fundamental problem comes from `PersonQuery#is_used` being used inproperly as it is used to indicate `person` table needs to be joined in many scenarios where only `person_dictinct_id2` table needs to be included.

This _might_ become moot with person-on-events.

cc @yakkomajuri

**Comment by Twixes** [comment]
I think this is largely solved.
