### ISSUE TITLE
Event capturing bug

### ISSUE THREAD

**Issue by paolodamico** [PostHog/posthog#1407]
## Bug description

While exploring the onboarding/setup funnel, I found what seems to be a bug capturing events (perhaps it's an API request issue). When I send this request, the events don't get saved (checked directly on the database).

```
POST <host>/capture
```

```json
{
    "api_key": "API_KEY_HERE",
    "event": "Purchase item",
    "properties": {
        "distinct_id": "845555992929291"
    }
}
```

## Expected behavior
- Events should be correctly saved to the database. If on the onboarding flow, continue the user and complete the onboarding.
- If the request is malformed or an invalid API key is sent, I should not receive a 200 status code. _There seems to be an issue with the request and therefore the event is not saved_, however **if I add a random non-existent key as the API key (e.g. `invalid`), I still get a 200 and a 1 in the response.**  

## Reproduction environment
- Tested using the one-line Docker deploy.
```bash
doker run -t -i --rm --publish 8000:8000 -v postgres:/var/lib/postgresql posthog/posthog:preview
```
- Tested on the cloud version with the same result (please reach out privately if you want to know the account's email address).

**Comment by paolodamico** [comment]
@timgl let me know if you want me to deep dive on this and try to fix it, I can work on this tomorrow/Thu.

**Comment by Twixes** [comment]
Hm, I tried reproducing and seems like a malformed `timestamp` causes a quiet failure, but didn't experience any unexpected behavior other than that.

**Comment by paolodamico** [comment]
> Hm, I tried reproducing and seems like a malformed `timestamp` causes a quiet failure, but didn't experience any unexpected behavior other than that.

Would not sending a `timestamp` also cause this quiet failure?

**Comment by Twixes** [comment]
No, that seems to work as expected, at least to me. Maybe there's something else at play here.

**Comment by paolodamico** [comment]
Deep diving on this. FYI reported on [Slack Users](https://posthogusers.slack.com/archives/CT7HXDEG3/p1596190521296800) too.
