### ISSUE TITLE
Improving performance of recordings list query

### ISSUE THREAD

**Issue by EDsCODE** [PostHog/posthog#14072]
I was using recordings and wanted to go faster. Took a look at queries

### Current query at a glance:

One big query that joins two subqueries together. 
- The first subquery is on the `events` table. This table has the raw event data like `$pageview` and event_properties. 
- The second subquery is on the `session_recording_events` table. This table has metadata related to sessions which are identified by `session_id`

The outer query joins the two queries on distinct_id. _After joining, it will do another filter that groups together session data by looking for session_id that exists from `events` and matches the `session_recording_events` session_id OR if the session_id is empty, collect events that fall within the start and end time of the `session_recording_events` session_id_

### The experiment I ran:
I add an assumption that events relevant to sessions will always have a session_id. This removes the final filtering described above. As a result we can push down any grouping and filtering to the subqueries and make them _smaller_ which will improve the performance of the JOIN.

1. The events subquery can now be responsible for doing the event filtering and grouping together the match counts that were happening at the outer query previously
2. Can remove the outer query group by
3. Tested to make sure the result sets are exactly the same which somewhat reinforces the assumption that I'm making to achieve these queries!

____

### Results:
I tested on a default "latest 20 recordings" on our US Posthog Cloud instance.

1. Notice memory usage is cut in half
2. Query time is reduced anywhere from 50-70%

**Caution: I did not do a deep dive to verify how feasible this assumption is nor test edge cases where we would miscount other recordings but from various result set comparisons that seem to match up pretty well it seemed useful to post this!

**Before**
[Query before changes](https://metabase.posthog.net/question/620-slow-recordings-list-query-that-filters-on-events-and-persons)
[Performance result query](https://metabase.posthog.net/question/623-stats-slow-recordings-list-query-that-filters-on-events-and-persons)
<img width="600" alt="Screen Shot 2023-02-02 at 7 57 55 PM" src="https://user-images.githubusercontent.com/13127476/216485584-8175c59e-39e8-4dc4-bd6e-7362161689b4.png">

**After**
[Query after changes](https://metabase.posthog.net/question/621-fast-recordings-list-query-that-filters-on-events-and-persons) 
[Performance result query](https://metabase.posthog.net/question/622-stats-fast-recordings-list-query-that-filters-on-events-and-persons) 
<img width="600" alt="Screen Shot 2023-02-02 at 7 55 43 PM" src="https://user-images.githubusercontent.com/13127476/216485324-706d9d1d-9912-4876-829c-6c33ee5fefa5.png">

CC recordings team and people who I know like to look at queries @benjackwhite @alexkim205 @macobo @neilkakkar @yakkomajuri

**Comment by macobo** [comment]
Related: https://github.com/PostHog/posthog/issues/12493

I don't think it's worth investing into this right now as sessions schema (all-in-one-table) is messed up and will need to be resolved quite soon due to storage/retention requirements.

**Comment by pauldambra** [comment]
I'll close this now we've moved onto querying a new table
