### ISSUE TITLE
RFC: Improved setup experience

### ISSUE THREAD

**Issue by paolodamico** [PostHog/posthog#1408]
This issue introduces a proposal for a new and redesigned setup experience (both for cloud and hosted versions). This issue is introduced to request for comments before implementing.

> **Feature Goal**: Improve the setup experience to successfully sign up more users.

The new implementation is detailed on this [Figma](https://www.figma.com/file/gtW3o3VKYvf04ws8cZM3Nr/PostHog-Onboarding?node-id=0%3A1). The file specifies which screens would belong to the cloud, hosted and both versions, as well as the screens it would replace for easy reference. When reviewing please:
- Review the comments on the file as they may contain additional information related to the functionality behaviour.
- The user path/flow can be seen on the Prototype section of the Figma.
- If you have feedback related to the design or specific visual elements please comment directly on Figma, comment on this issue otherwise.

### Key elements
The new design introduces the following benefits:
- Specifically-designed setup for cloud and hosted versions.
- More clarity during experience (e.g. only show Swift or Objective-C code, explain this is just the first event source but they can add more later).
- Incentivize adding libraries with autocapture to speed up the process and see benefits quicker.
- On the cloud version, pre-flight check to make sure the infrastructure is fully set-up and ready (mental separation of concerns with event capturing and team setup).
- On the cloud version, provide an option for quick explore, and leave the team setup process at the end (better mindset as a reward has been received),  and provide more information as to why the team setup is necessary.
- Increase discoverability of E2E event capturing with native, web and server/backend support.
- Capture extra metadata on the type of user and company for better segmenting and optimizations. 
- Quick start for users just trying to test locally. **This will also help us remove noise from testing installs from our metrics.**

## Additional information
- We need to figure out https://github.com/PostHog/posthog/issues/1407 before deploying this new onboarding flow.
- Any buttons/actions need to introduce a unique identifier to be able to track down the activation funnel.
- We won't be able to measure the holistic impact on retention until https://github.com/PostHog/posthog/issues/1377, but in the meantime we'll be able to measure the direct impact in the setup funnel.

**Comment by mariusandra** [comment]
Even if there is a bit of feedback in Firma (I added some as well), this looks like a great improvement over the current onboarding flow!

**Comment by ungless** [comment]
Looks awesome! One thing I was thinking was that the use of box shadows is a little inconsistent. For example the platform choice page uses solid coloured backgrounds with no shadows, but the frameworks page does.

I think that obvious borders or backgrounds make links / call-to-actions easier to see, especially on bad / small screens. Thoughts?

**Comment by paolodamico** [comment]
Thank you all for all your comments! I've updated the Figma file based on all your feedback and will start implementation soon. If anything else comes up feel free to comment here or on Figma!

**Comment by paolodamico** [comment]
As this was intended only for discussion, closing the issue.
