### ISSUE TITLE
Formula mode not working - Posthog Cloud

### ISSUE THREAD

**Issue by daniloxvalle** [PostHog/posthog#14092]
## Bug description

Formula mode is not working, it shows an error: "There was an error completing this query"

## How to reproduce

1.Create a new insight
2.Select Trends
3.Create a Serie
4.Click Enable formula mode
5.Add a variable(series) name in formula field

## Environment

- [ X] PostHog Cloud
- [ ] self-hosted PostHog, version/commit: please provide

## Additional context

![image](https://user-images.githubusercontent.com/40468199/216987456-17dad7c6-96a3-43c3-b081-93953c83dbdc.png)

**Comment by neilkakkar** [comment]
Quick flyby @daniloxvalle , your variables in the above are `A`, `B`, `C`, and `D`, not `P`. Might be the reason why. Agree that error isn't very helpful to debug here

**Comment by daniloxvalle** [comment]
Makes total sense @neilkakkar I though I should give a name for the variables. Thanks a lot, it's working now. We can close the issue or use it for design improvement, maybe improve the error. Thanks, BR.
