### ISSUE TITLE
Aggregate statistics for pages with similar URLs on the toolbar

### ISSUE THREAD

**Issue by mariusandra** [PostHog/posthog#1411]
## Is your feature request related to a problem?

Sort of.

## Describe the solution you'd like

I'd like to see URLs such as:

https://app.posthog.com/funnels/1
https://app.posthog.com/funnels/2
https://app.posthog.com/funnels/3

... grouped together when using the heatmap, so I would see events from all funnels on the same page:

Possibly I could add some hints and edit the URL to:

`https://app.posthog.com/funnels/:id`

... to make it work.

## Describe alternatives you've considered

Load all my thousands of pages separately and using excel add all the clicks together to form a better picture on what's happening.

## Additional context

- Several customers with dynamic pages have requested this for the toolbar.
- Related: #1147

**Comment by jereze** [comment]
Hi,

A big +1 for this request.

For example, I'd like to aggregate on the Toolbox for the heatmap and actions preview all following matching events:

`http://{customer_id}.ourcompany.com/project/{userprojectid}/action1`

myself being on one particular URL of this type.

For now, the Toolbox is not really usable for us.

**Comment by mariusandra** [comment]
Closed with https://github.com/PostHog/posthog/pull/9306
