### ISSUE TITLE
Smart refreshing for insights and dashboards

### ISSUE THREAD

**Issue by yakkomajuri** [PostHog/posthog#14143]
We haven't put too much work into refreshing insights and dashboards.

Essentially the only thing we've done is added a frontend guard preventing people from clicking "Refresh" on an insight more than once within 3 minutes.

However, there are a lot of things missing on this front:

- Dashboards can be refreshed at will
- Dashboards can be set to auto refresh every minute (!!)
- API requests with `refresh=true` are not guarded
- Most graphs don't need to be refreshed every 3 minutes. The only potential reasons for doing this are: a) debugging and testing i.e. I want to see events coming in b) live following of special events (e.g. front page HN, ProductHunt launch)

Ok, so we can make refreshing smarter. But why?

Well, our current approach makes it so that people can (on purpose and accidentally) abuse our API and create unnecessary load for us with little benefit to customers. Realistically, nobody needs 1m auto-refresh dashboards.

Thus, I'm proposing we think about this more methodically. Some initial action points:

- [x] Refresh freeze for dashboards as well
- [x] Backend guard for `refresh=true`, perhaps with overriding allowed by admins
- [x] Changing dashboard auto-refresh options
- [ ] Dynamically deciding on refresh "freezes" based on valid heuristics e.g. graph range, graph interval, query execution time

I have a good sense of initial action points, but would love to get some thoughts from the product side as well. This is a point where our interests are not aligned with customers - customers don't care about load to our system, ideally they just want data as fresh as we can provide it. We on the other hand actually would rather provide the most "stale" data the customers will tolerate. Thus, we just need to find a good line in between - ultimately I think there's a good bit of low-hanging fruit work that should have negligible customer impact and we can just do, but any thoughts @lharries?

**Comment by pauldambra** [comment]
see https://github.com/PostHog/posthog/pull/14134 for a quick fix on auto refresh options

**Comment by yakkomajuri** [comment]
@pauldambra fantastic, that already covers some action items!

**Comment by pauldambra** [comment]
@benjackwhite and I dumped thoughts on background refresh here when it was fresh in our heads a while ago https://github.com/PostHog/product-internal/pull/333

**Comment by yakkomajuri** [comment]
An example of the conflict between user wants and our needs:

https://github.com/PostHog/posthog/pull/14134#pullrequestreview-1289322414

**Comment by yakkomajuri** [comment]
Note that one thing to consider is the authoritarian "users can't trigger refreshes, we know what's best for them". Curious as to what other companies in the space do. 

I think the main issue with going down this route is that we'll probably anger people used to this feature. Beyond that, I don't actually think this is such a bad idea.

**Comment by yakkomajuri** [comment]
Curious to see how query volumes change after shipping both #14134 and #14150

**Comment by yakkomajuri** [comment]
Ok, here's what I'll be working on tomorrow (this was going to be a PR but I'm wrapping up so putting my thoughts here so @lharries has them before I'm up):

- `refresh=true` will become a "request", not an "order"
- Having received a `refresh=true` request, we'll decide if we should refresh or not. Here's a rough initial heuristic I've come up with (later on we might optimize this further, including adding in things like accounting for query execution time):
    - Hourly, 1d: Refresh every 3min (keeping as is)
    - Hourly, 1d+: Refresh every 10min
    - Everything else: Every 15min
- We'll then return two new fields in the API response: 
    - `refreshed` (boolean): determines whether we actually "fulfilled the request" and refreshed the insight
    - `next_allowed_refresh` (datetime): when this insight can be refreshed again, useful both for those that were and weren't refreshed
- On the insights UI, we'll use `next_allowed_refresh` to guide the Refresh button being disabled or not
- On the dashboards UI, when you refresh a dashboard, we'll denote which insights were refreshed and which weren't. We'll then provide a message like: "we didn't refresh this insight because it was already refreshed 5 minutes ago"

**Comment by Twixes** [comment]
We already have the `is_cached` field, doesn't that do the same as `refreshed`?

**Comment by yakkomajuri** [comment]
Yeah didn't update here but I realized this along the way :D

**Comment by lharries** [comment]
I think there’s three main questions:

- What should the UX be? (API and UI)
- For how long should we return a cache value instead of the most up to date value?
- How long should we keep stuff in the cache for?

Here’s some research on what the other players are doing: [https://docs.google.com/document/d/19J6jZYXYlWnxlPY_WRest7fL-sOizkAEc9zKwR9bS3A/edit#heading=h.teu4zpiv98db](https://docs.google.com/document/d/19J6jZYXYlWnxlPY_WRest7fL-sOizkAEc9zKwR9bS3A/edit#heading=h.teu4zpiv98db)

I’ve watched a few session recordings for why people are refreshing:

- [Dashboards](https://app.posthog.com/insights/3I4mwvQG) - hard to tell why exactly they are refreshing. I’m guessing it’s a mainly:
    - The current dashboard is a few hours out of date (seems to be the most common from the ones I watched)
    - Wanting to see the latest data e.g. post-launch etc
    - And could potentially also be:
        - Think the data is wrong and so are refreshing to see if something is different
- Insights
    - Number of times this is clicked seems to have climbed quite a bit recently
      <img width="534" alt="Screenshot Weekly plan  6 Feb 2023 (Notion) 2023-02-09 at 15 24@2x" src="https://user-images.githubusercontent.com/22766134/217856049-224430a3-d8bf-4be7-8042-95a196311b69.png">

        
    - Main reasons from watching session recordings:
        - Going from an insight on an dashboard to the insight and then the insight it out of date (as it was when the dashboard updated)
        - During setup and seeing events come in
    - And could potentially be
        - Think the data is wrong and so are refreshing to see if something is different

My suggestions:

- What should the UX be?
    - UI
        - Insights
            - When loading an insight with the data in the cache, start with loading the data from the cache assuming it’s up to date enough (and **potentially start a job to update the cache to make it quicker if they then hit refresh - 8.13% of the time**)
            - Refresh button
                - Keep as is - The button should be disabled when they can’t refresh with a tool tip message about needing to wait 3 minutes (as is)
                - When they click refresh should it ever just return data from the cache?
                    - My vote would be no, it should be an actual refresh - because it looks like this is often used for setup. However, we might want some sort of note here that it takes a few minutes for the data to load
            - **Suggestion: Change “Computed a while ago” on insights to be more specific**
        - Dashboard
            - (Opinion) Autorefresh - **change to every 30 mins or 60 mins**? I don’t see a need for the times inbetween, makes it a bit simpler.
    - API requests from a third party
        - In contrast to the UI, where I think if you hit refresh it should actually refresh the data. **I agree with Yakko that it should be a request rather than an order.**
        - **I think we should make it so that “refresh=true” is only respected when used from the UI - NOT for external use.**
- For how long should we return a cache value instead of the most up to date value?
    - **If they have an end date which is not today we can always return the cached value as it won’t have got out of date**
        - Caveat - If they do an import of an event older than a day should we invalidate the cache?
    - **Is there a way for us to cache only some of the data?** e.g. if doing a trend over the last 3 months, we only actually need to refresh today rather than the all the other days (unless they do a historical backfill in which case we’d want to invalidate the caches)?
        - Likely out of scope for this work but seems potentially high ROI
    - **I’d expand on Yakkos:**
        - Hourly, 1d: Refresh every 3min (keeping as is)
        - Hourly, 1d+: Refresh every 10min
        - **Don’t let hourly view be longer than 7 days (see info below under extra)**
        - Daily, weekly, monthly see [here](https://docs.google.com/document/d/19J6jZYXYlWnxlPY_WRest7fL-sOizkAEc9zKwR9bS3A/edit#heading=h.n29nokws8ka4) for more suggestions - up to you Yakko the exact numbers you want to do
    - This caches will mainly be used for when they open the UI, API queries, or dashboard autorefresh
- How long should we keep stuff in the cache for?
    - This is more driven from the engineering side. Quick thoughts - do we have the data for this that we can use to optimize the number of time? Can default to something in the doc or be smarter about this.

Extra but potentially high impact:
- **Depending on the load, we should likely put stricter limits for the max date range of our hourly and daily queries. e.g. [here](https://docs.google.com/document/d/19J6jZYXYlWnxlPY_WRest7fL-sOizkAEc9zKwR9bS3A/edit#heading=h.f0756rgn6zvq)]**

**Comment by yakkomajuri** [comment]
Thanks for this @lharries! It goes beyond the scope of refreshing a bit and into other caching questions, as well as some points I had raised in #13715.

A few replies and some further thoughts from my side:

> Dashboard autorefresh: change to every 30 mins or 60 mins

Agreed

> I think we should make it so that “refresh=true” is only respected when used from the UI - NOT for external use.

This is not really possible, or rather near impossible in general + something that doesn't couple with our system. We don't (and I'd argue shouldn't at this stage/ever) differentiate between requests that come from the UI vs elsewhere. It's a rabbit hole we don't want to go down. _However_, what I had in mind and what I built on #14178 is _effectively_ this. The backend guards against "early refreshes", but the UI makes sure you can't request a refresh if it's not time. Thus, it guarantees (as far as guarantees exist with keeping things in sync in software) that we will send an updated result when the UI allows the user to ask for it.

> Is there a way for us to cache only some of the data?

Thought about this before - not something to think about now maybe but definitely a project to consider in the medium term. Could be very high impact but tricky to get right.

> If they have an end date which is not today we can always return the cached value as it won’t have got out of date

This is easy to do 99% right but harder to handle the edge cases (historical events, as you pointed out). Something to think on, because the 1% of edge cases could lead to distrust if not handled correctly.

> Depending on the load, we should likely put stricter limits for the max date range of our hourly and daily queries.

Totally agree. #13715

------

However, having started working on all this - I'd like to make a bold suggestion (bold for us but not so bold overall I think).

Let's completely get rid of user-triggered refreshes altogether. Essentially, users will always want to click “refresh” even when they don’t need to. I instinctively press it if I open a graph and it says “computed 2 hours ago” even though it’s a 180d graph broken by week. Something to explore for the future. I think we can actually do a better job for our customers while reducing load for us (win-win) by doing this.

Right now, when a user opens an insight, if it's very old, we just show them "Computed a while ago". There's absolutely no reason why I wouldn't want to refresh an insight that indicates to me that it's stale. So instead of showing them when it was computed and letting them "decide", let's just refresh it for them if we feel it got stale. 

By doing away with the button, we can work on providing appropriate refresh intervals and just handle things in the background without customers having to worry. From my understanding, this is what our competitors do (as @lharries showed in the doc above) and intuitively it's how I think a system like this should be built. 

I think we should communicate the constraints clearly (certainly in docs and maybe in the UI), and then do the work for the user. My guess is that we'll end up with fewer refreshes **and** provide a better user experience by simply refreshing graphs automatically more often (which we'll be able to do as we'll reduce the number of unnecessary "impulse refreshes" incentivized by the button being right there).

Thoughts?

**Comment by yakkomajuri** [comment]
Note that the above doesn't need to block the ongoing work with #14178

**Comment by lharries** [comment]
We discussed this briefly in the standup, but overall I'm pretty against removing the refresh button. As watching the session recordings most of the refreshes seemed valid and it feels (intuition rather than data) like removing the refresh would cause quite a bit of frustration. If we did want to remove it I don't think we are there yet in terms of the eager updating on the clients behalf - and working on this first would likely increase the load.

I think moving it behind the "..." is a good intermediate along with increasing the minimum time delay for much heavier queries. 

If there's other low-hanging fruit that we can do instead (e.g. removing the ability to do hourly for over a week view) I'd be keen to do that first. But if you strongly think this will help we could try putting the change behind a feature flag and seeing how it feels?

> From my understanding, this is what our competitors do (as @lharries showed in the doc above) and intuitively it's how I think a system like this should be built

In both the competitors researched you can hit the refresh button. Mixpanel is explicit that it returns the refreshed data. Amplitude keeps the refresh button but it's ambigious from the docs whether it actually updates the data or returns a cached button

**Comment by Twixes** [comment]
We've done a ton of work on more smarter and more powerful refreshing logic recently, I think it's time to close this!
