### ISSUE TITLE
Support to delete screen recordings

### ISSUE THREAD

**Issue by Christian-aman-insurely** [PostHog/posthog#14142]
## Is your feature request related to a problem?

We need to be able to delete screen recordings. The issue is if we have somewhere missed to mask some sensitive information we need to be able to delete the recording. From what i can find there is no way of doing this. Preferably it would be possible to do this from the UI.

## Describe the solution you'd like

Delete button in the UI for screen recordings

## Describe alternatives you've considered

Not use screen recordings

**Comment by benjackwhite** [comment]
We don't currently have a way to delete recordings manually but they are automatically deleted after the default retention time of around 3 weeks. 

It should be somewhat trivial to add a deletion mode that "masks" the data so it is not retrievable. The underlying data would only be purged once the TTL is reached. Would this satisfy what you are looking for?

**Comment by ghost** [comment]
Thanks for a quick response! 

Unfortunately it does not. We would need it to be completely deleted. 

Just curious, how come you cant delete a recording?

**Comment by benjackwhite** [comment]
Deleting in individual cases like this is an expensive operation. With the kind of data loads that we deal with the only scalable approach is to "mask" the data and then eventually it will get purged by more scalable batch operations. 

It is not that the data will not be deleted, only that it won't be deleted immediately. Imagine it like "moving to the trash" which eventually will get thrown out.

**Comment by ghost** [comment]
So the i guess you have some kind of CRON job that deletes recordings every day? Could a possible middle ground be that the "masked" files are flagged for the next delete?

**Comment by benjackwhite** [comment]
We released this recently exactly as described. We are also working on an alternative ingestion flow that will store the raw data in S3 which will allow us to do hard deletes "properly". This is still a while away but just FYI.

**Comment by ghost** [comment]
@benjackwhite Okay, thanks for the update!
