### ISSUE TITLE
Improve communication on build when running locally with Docker

### ISSUE THREAD

**Issue by paolodamico** [PostHog/posthog#1417]
## Bug description

I simply cloned the repo and ran the following command (as specified in the [Developing Locally](https://posthog.com/docs/developing-locally) guide) and got the error shown on the screenshot. Might be an issue with the `bin/docker-dev` script.

```bash
docker-compose -f docker-compose.dev.yml up
```

<img width="500" alt="screenshot" src="https://user-images.githubusercontent.com/5864173/90058554-7cd1e100-dca7-11ea-9ed3-d819257a2cb9.png">

## Expected behavior

App should run correctly on `http://localhost:8000` and open the initial setup screen.

## Environment

- Development version on Docker, latest commit (2585e9507416efd758c46b02b2bd5cc489175788)
- Running on macOS Catalina with Docker Desktop 2.3.0.4

**Comment by Twixes** [comment]
There's no screenshot!

**Comment by paolodamico** [comment]
> There's no screenshot!

I knew I was forgetting something, thanks for pointing that out! Updated above.

**Comment by Twixes** [comment]
How long did you wait for it to build? It might take a minute or two.

**Comment by paolodamico** [comment]
About 10 minutes, I re-checked the logs and seems like Yarn got stuck on the 3/4 step [Linking dependencies]. I re-installed Yarn, made sure `yarn install` succeeded outside of Docker and tried again. Seems like it may have been an issue with the network. I'm proposing https://github.com/PostHog/posthog.com/pull/313 to improve communication in our guide so that it doesn't cause issues with potential contributors and changing this issue to **suggest that we run the build process synchronously or in a way that better communicates the status of the build.** (The logs can be a bit confusing because the Django server says it's ready while the front-end hasn't been compiled yet).

FYI doesn't seem to be a relevant issue when running with virtualenv as you run `yarn install` (the command that seems to take more time) individually.

**Comment by paolodamico** [comment]
Closing this as this process has evolved quite a lot and this doesn't seem to be a cause for confusion anymore.
