### ISSUE TITLE
Custom date range selector broken

### ISSUE THREAD

**Issue by corywatilo** [PostHog/posthog#14179]
## Bug description

Changing the custom date range doesn't do anything. No console errors.

![2023-02-09 14 17 12](https://user-images.githubusercontent.com/154479/217915411-2969c318-e87f-4d8f-bb5c-fdbced24b567.gif)

Verified in a non-PostHog account, so appears to be a real bug.

**Comment by yakkomajuri** [comment]
It's perhaps poor UX - but you need to set the value and then click it. I also think we should automatically switch to that if you edit that value

**Comment by Twixes** [comment]
Gonna take a look at this, removing the Ant `Input` from the component anyway.
