### ISSUE TITLE
Annotation grouping displays misleading date

### ISSUE THREAD

**Issue by EDsCODE** [PostHog/posthog#1419]
## Bug description

*Please describe.*  
Annotations that are grouped on an interval should have a specific denotation as to what day they mark

*If this affects the front-end, screenshots would be of great help.*  
For example, this date should be marked as the 29th but it's grouped into the week of the 26th
<img width="359" alt="Screen Shot 2020-08-12 at 10 05 24 PM" src="https://user-images.githubusercontent.com/13127476/90086274-13be8d80-dce8-11ea-8fca-455efa042c9f.png">

## Expected behavior
Should have an extra note that says what date it's marking

## How to reproduce

1. Make an annotation that doesn't fall on the beginning of the interval
2. Change the interval to be more broad (weekly)
3. The annotation will be mismarked

**Comment by Twixes** [comment]
Fixed.
