### ISSUE TITLE
Upgrading 1.21.1

### ISSUE THREAD

**Issue by yormy** [PostHog/posthog#1420]
I tried upgrading to 1.21.1 but I still see 1.12 in my version
```
 docker-compose pull web
 docker rm posthog_web -f
 docker-compose up -d web
```

Something I noticed is that on docker hub the latest release is :  2585e95
When I go to that commit in github i see in the changelog : Bump version 1.12.0 (#1301)
When I shell into the web container, I cannot see the changelog so I cannot verify what version is in the container.
But I assume that docker-hub still has 1.12 and not 1.12.1

**Comment by Twixes** [comment]
Sorry for that mismatch! VERSION was left on 1.12.0 in settings.py, bumped it properly now. We're just about to release 1.13.0 though, so that'll be the Docker image to watch out for.

**Comment by yormy** [comment]
Cool...
Can you ping here when the new docker image is live ?

**Comment by Twixes** [comment]
Sure!

**Comment by Twixes** [comment]
Sorry for being late, but it's out! 😄  Release notes here: https://posthog.com/blog/the-posthog-array-1-13-0/
