### ISSUE TITLE
Automatically add flag information on server-side library events when possible

### ISSUE THREAD

**Issue by neilkakkar** [PostHog/posthog#14270]
## Is your feature request related to a problem?

Now that we have local evaluation, we can add flag information to server-side events for flags that can be evaluated locally automatically.

This introduces no delays in capture, and also allows us to offset _some_ work from users.

*Please describe.*

**Comment by EDsCODE** [comment]
What information are you referring to

**Comment by neilkakkar** [comment]
information = flag evaluation values. Right now, all events coming from server side libraries need to manually add which all flags are active. But they don't have to. (as long as there's a personal API key)
