### ISSUE TITLE
Can't create an action that triggers on form submit

### ISSUE THREAD

**Issue by timgl** [PostHog/posthog#1431]
## Bug description

We capture form submissions automatically, but then don't allow you to create actions that trigger because of this .

## Expected behavior

It should correctly filter the autocapture action by a property that is `$type=submit`

## How to reproduce

1. Submit a form
2. Create action from that event
3. 

## Environment

- PostHog cloud or self-managed?
- PostHog version/commit

**Comment by mariusandra** [comment]
The commit says "Partly fixes" and github closed this issue because of that. I guess there's more to do? Reopening just in case.

**Comment by timgl** [comment]
Yep that's right, thanks!
