### ISSUE TITLE
Lightweigth capture 4/4: progressively rollout

### ISSUE THREAD

**Issue by xvello** [PostHog/posthog#14329]
Add a couple of teams to `LIGHTWEIGHT_CAPTURE_ENDPOINT_ENABLED_TOKENS` as a canary, then switch all teams with a `*` value.

**Comment by neilkakkar** [comment]
Fwiw, you can use feature flags for this, which will give this to you automatically.

It wouldn't affect ingestion speed if you use local evaluation, which ensures things remain extremely fast.

**Comment by xvello** [comment]
Heya @neilkakkar , thanks for the idea! While I would love us to start using feature flags in plugin-server, our target for capture is to remove as many deps as possible, to make it as dumb and boring as possible, and allows us to focus on the other parts of the pipeline. Adding FF now would not go in the right direction.

**Comment by neilkakkar** [comment]
Makes a lot of sense!

**Comment by xvello** [comment]
Deployed on all three regions!
