### ISSUE TITLE
Lightweigth capture 1/4: always resolve team_id at p-s and compare result

### ISSUE THREAD

**Issue by xvello** [PostHog/posthog#14327]
Let's start doing it as soon as possible to build trust on the performance and accuracy of the resolution code in plugin-server.

- [ ] Always hit postgres for resolution, even if `team_id` is found in the event
- [ ] If `team_id` is found in the event, compare the lookup result, and increment a prometheus metric with ok/error status. Log differences if found, and keep the value from capture
- [ ] Let's review the caching logic doesn't get into edge cases when tokens are rotated.

## Why now?

This has been identified as something not to port in a rewrite of capture. Regardless of whether capture v2 plans move forward in Q1, this will help with:

- making sure we don't DLQ & timeout when PG is unhealthy
- allowing infra to have a less stressful PG upgrade (version 11 goes EOL in October)
- scaling down posthog-events, as the team resolution is a 20%-ish part of the endpoint latency

**Comment by neilkakkar** [comment]
whether it's at the django or plugin-server level, for flags we already have a token->team cache in redis, which is somewhat battle-tested. You can re-use this too for the prom metric and then decide if it's good enough to switch :)

**Comment by xvello** [comment]
- if plugin-server-ingestion has lag while a user rotates their token, in-flights events will be dropped  -> update documentation
- invalidated tokens will stay up for up to 2 minutes (the plugin-server caching TTL), we could later on add faster invalidation (django sents a kakfa message to p-s), but out of scope for now.

-> Update doc to reflect these two behaviours.
