### ISSUE TITLE
Quick funnels

### ISSUE THREAD

**Issue by paolodamico** [PostHog/posthog#1433]
## Describe the solution you'd like
I would like to be able to create funnels without having to save them (for quick views/calculations). You may just want to see how the funnel changes when you add/remove filters and this would require you to overwrite your existing funnel.

## Describe alternatives you've considered
Create multiple funnels, but it causes confusion and may lead to a bunch of useless/distracting funnels for other team members.

**Comment by Twixes** [comment]
Implemented!
