### ISSUE TITLE
The HTMLElementsDisplay truncates the element chain without telling you

### ISSUE THREAD

**Issue by pauldambra** [PostHog/posthog#14347]
When you view an autocapture event's elements in the HTMLElementsDisplay it only shows 10 levels of the elements chain. Which can make you think that the autocapture event doesn't capture the other parts of the chain (when it does)
*Please describe.*

## Describe the solution you'd like

* allow more than 10 elements to be visible in the `HTMLElementsDisplay`
* or maybe indicate that there’s indeed more (“+5 levels hidden”)

## Additional context

Would be good to solve this _after_ https://github.com/PostHog/posthog/pull/14194 since that refactors this component substantially

**Comment by stefanhoth** [comment]
One other idea could be to chose a simplified "one line" representation for the upper levels, e.g. how Chrome dev tools does at the footer of the tree navigation.

**Comment by ksgokul2501** [comment]
Has this been resolved?

**Comment by nizarmah** [comment]
If I'm not mistaken, it seems like `HTMLElementsDisplay` already allows more than 10 elements to be visible

https://github.com/PostHog/posthog/blob/b041ecf274db05d4d152a4794544f0ba0a82fd94/frontend/src/lib/components/HTMLElementsDisplay/HTMLElementsDisplay.tsx#L124

I can work on this, I just need to familiarize with what's behind the scenes in that case 🤓

**Comment by nizarmah** [comment]
I can work on this! :D

<details>
<summary>Update log</summary>

<details>
<summary>Jun 17, 2023</summary>

Sorry for the lack of updates, been a hectic week.

Took a closer look this time and found the culprit.

https://github.com/PostHog/posthog/blob/764a2058129ec467a17d59336963689d68ace3d0/frontend/src/lib/components/HTMLElementsDisplay/htmlElementsDisplayLogic.ts#L21-L24
</details>

<details>
<summary>Jun 10, 2023</summary>

It seems like only 10 elements are being received.

https://github.com/PostHog/posthog/blob/b041ecf274db05d4d152a4794544f0ba0a82fd94/frontend/src/lib/components/HTMLElementsDisplay/HTMLElementsDisplay.tsx#L52-L65

Just need to figure out what's happening behind the scenes 🤓 
</details>
</details>

**Comment by nizarmah** [comment]
Alright, I've created a pull request mentioned above.
Video demo of the changes can be found on https://github.com/PostHog/posthog/pull/16126#issue-1762519448

It's in draft form because I still need
1. Confirmation on which solution to go for
    1. show as many lines as possible, https://github.com/PostHog/posthog/issues/14347#issue-1593836021
    2. indicate there are hidden levels, https://github.com/PostHog/posthog/issues/14347#issue-1593836021
    3. one line representation similar, https://github.com/PostHog/posthog/issues/14347#issuecomment-1438846879
2. Better design, if applicable (prototype of _1.iii_ is still rough)
3. PR still needs some work, aside from the previous 2 points
