### ISSUE TITLE
Make GeoIP handling for server side & client side events more seamless

### ISSUE THREAD

**Issue by neilkakkar** [PostHog/posthog#14351]
## Is your feature request related to a problem?

*Please describe.*
I have a user in France, but when I send a backend event, I end up updating their country to USA, where my servers are. Big sad :/

## Describe the solution you'd like

Have a special property on events, which if present, means no geoIP information is added, which is set on by default for all server libs. Update the geoIP plugin to respect this property.

Giving this control to users via the events they send is a lot more flexible than doing this on a plugin, which has complicated restrictions to get the same thing and not as flexible.

## Describe alternatives you've considered

Right now, people have to go through multiple hoops, like adding the Advanced GeoIP plugin to discard geoIP information based on the library it is coming from.

**Comment by pauldambra** [comment]
In case I'm not misunderstanding....

>If you'd like this app to skip over an event and not add the above properties, set property $geoip_disable to true on that event.

from https://posthog.com/docs/apps/geoip-enrichment#:~:text=If%20you%27d%20like%20this%20app%20to%20skip%20over%20an%20event%20and%20not%20add%20the%20above%20properties%2C%20set%20property%20%24geoip_disable%20to%20true%20on%20that%20event.

So, we can already instruct to discard and "_just_" need to turn this on by default for server libs?

**Comment by neilkakkar** [comment]
ohhh daaamn, okay nice, ~~half~~ 10%  the work is done 😂

**Comment by paolodamico** [comment]
this is super helpful to know @pauldambra!

**Comment by neilkakkar** [comment]
cc: @liyiy

**Comment by neilkakkar** [comment]
This is now fixed :)

**Comment by neilkakkar** [comment]
Python and node only, but go, php still missing it: https://github.com/PostHog/posthog/issues/18005
