### ISSUE TITLE
Dynamic cohorts stopped updating

### ISSUE THREAD

**Issue by oritamuz** [PostHog/posthog#14356]
## Bug description
Starting 2/20 at around 2pm ET dynamic cohorts stopped updating. 

*Please describe.*  
*If this affects the front-end, screenshots would be of great help.*  

*If you are on PostHog Cloud it would be really valuable if you can share any links where the problem occurs. This speeds up our ability to troubleshoot tremendously.* 

## How to reproduce

1.go into any cohort that was created prior to 2/20
2.you will see that the most recent person in the cohort was added on 2/20 around 2pm ET. And that each cohort was last calculated around that time as well. See screenshot in the comment below. 
3.this will also impact reports that are relying on cohorts. 

## Environment

- [x] PostHog Cloud US, project ID: [please provide from https://app.posthog.com/project/settings#project-id]
- [ ] PostHog Cloud EU, project ID: [please provide from https://eu.posthog.com/project/settings#project-id]
- [ ] PostHog Hobby self-hosted with `docker compose`, version/commit: [please provide]
- [ ] PostHog self-hosted with Kubernetes (deprecated, see ["Sunsetting Kubernetes support"](https://posthog.com/blog/sunsetting-helm-support-posthog)), version/commit: [please provide]

#### *Thank you* for your bug report – we love squashing them!

**Comment by oritamuz** [comment]
![image](https://user-images.githubusercontent.com/25931067/220499853-fb0d321e-5f1f-4610-a265-f21c5c55b40a.jpeg)

**Comment by raquelmsmith** [comment]
Hey @oritamuz - can you provide your project ID and cohort that has stopped updating?

**Comment by renanwolf** [comment]
Same problem here. I started using PostHog this week in a production environment and none of my dynamic cohorts are updating automatically. They update only when re-saved.

PostHog Cloud US.
Project ID: 29849

**Comment by luc-vocab** [comment]
Experiencing the same issue here, i'm on the posthog cloud trial (US datacenter), project id: 26705 cohort id: 44419
seems the only way to get it to update is to edit the cohort and save.
