### ISSUE TITLE
Allow setting conversion window limit in seconds

### ISSUE THREAD

**Issue by DavidLloydTN** [PostHog/posthog#14380]
## Is your feature request related to a problem?

We would like to create an insight that identifies users returning to the same page very quickly. So far the best option I have identified to do this is to create a three step funnel with a conversion window limit. However the minimum window limit currently supported is one minute, and we are looking to capture behaviours that happen in seconds.

## Describe the solution you'd like

Allow setting a conversion window limit in seconds.

## Describe alternatives you've considered

Setting fractional values of minutes does not appear to work. Maybe a different insight model could solve the problem above?

## Additional context

N/A

**Comment by raquelmsmith** [comment]
Should be good to go with this @DavidLloydTN!

**Comment by DavidLloydTN** [comment]
> Should be good to go with this @DavidLloydTN!

Thanks @raquelmsmith! Will be happy to make use of this.
