### ISSUE TITLE
Autocapture not capturing button label if the label is contained within a span

### ISSUE THREAD

**Issue by madjam002** [PostHog/posthog#14387]
## Bug description

Given the following markup:

```
<button type="button" class="bp4-button"><span class="bp4-button-text">Click to wiggle</span></button>
```

If the user clicks on the button element outside of the label, Posthog will capture a `clicked button` event but won't have any information about the label of the button. If the user clicks exactly on the label within the button, Posthog will capture a `clicked span with text "Click to wiggle"` event.

Perhaps both should be a `clicked button` event with the label, or at the very least clicking outside of the span should include the button label?

See https://blueprintjs.com/docs/#core/components/button for an example of these button elements.

## Environment

- [X] PostHog Hobby self-hosted with `docker compose`, version/commit: 1.43.0

**Comment by raquelmsmith** [comment]
Hey @madjam002 - thanks for reporting this, we will look into a fix.
