### ISSUE TITLE
1 line docker preview gives blank page

### ISSUE THREAD

**Issue by jamesefhawkins** [PostHog/posthog#144]
**Describe the bug**

I used the 1 line Docker preview.

It installed, but then took me to a blank page.

There is an error in the console.

**To Reproduce**
1. Go to readme
2. Run the 1 line docker preview command

Sidenote: if I go to create a new account and run it in incognito, Django throws an error.

**Expected behavior**
The app should load on the setup page.

**Screenshots**

**This shows when I used it most recently. Is that perhaps because I've run it locally before and needed to delete cookies?**

![Screenshot 2020-02-20 at 01 33 52](https://user-images.githubusercontent.com/47497682/74920721-79593f00-5381-11ea-969e-bf8384fdf941.png)

**This shows the error on running it locally, then "creating" a new account:**

![Screenshot 2020-02-20 at 01 36 01](https://user-images.githubusercontent.com/47497682/74920756-85dd9780-5381-11ea-8754-2e19c37519cc.png)

**Desktop (please complete the following information):**
 - OS: osx
 - Browser chrome

**Additional context**
We can remove this preview if we need more time to work on this.

**Comment by timgl** [comment]
Yep, this is a problem because you've run the command before. I think it's fine to leave in readme for now, will work out a way of properly fixing this later.

**Comment by timgl** [comment]
Fixed!
