### ISSUE TITLE
[PagerDuty] Alerting on 500 and statsd

### ISSUE THREAD

**Issue by timgl** [PostHog/posthog#1446]
## Is your feature request related to a problem?

We need stronger alerting

## Describe the solution you'd like

Alert on increase in 500 and certain statsd

**Comment by ungless** [comment]
Grafana now triggers an alert in PagerDuty when the number of 500 response codes exceeds 30.

Not sure if this is the ideal value, but it seems sensible since spikes in activity never exceed 20 as it stands, so 30 responses would be unusual.

**Comment by ungless** [comment]
Ideally we would like
- Endpoint analysis on 5xx responses passed through to PagerDuty
- Additional alerting on response time thresholds, for example.

Feel free anyone to pick this up.

**Comment by Twixes** [comment]
Done.
