### ISSUE TITLE
Infinite event generation for PostHog tracking PostHog

### ISSUE THREAD

**Issue by yakkomajuri** [PostHog/posthog#1447]
## Bug description

*Please describe.*  
*If this affects the front-end, screenshots would be of great help.*  

PostHog captures clicks to the "There are x new events. Click here to load them" button, which essentially can create an "infinite event generator".

![](https://github.com/yakkomajuri/img-store/blob/master/infinite-gen.png?raw=true)

## Expected behavior

Clicking the button without generating a new event which generates a button, etc.

## How to reproduce

1. Go to app.posthog.com
2. Go to events
3. Click the button to load new events

## Environment

- PostHog cloud or self-managed?
- PostHog version/commit

app.posthog.com

## Additional context

Should be a matter of setting a `ph-no-capture` class on that button, unless there are any objections...

And even though the problem is on app, this change should go here I believe

**Comment by Twixes** [comment]
That's fascinating. 😄  Made a PR for this #1449.

**Comment by yakkomajuri** [comment]
Great! I was about to and got caught up with another issue

**Comment by yakkomajuri** [comment]
Solved by #1449
