### ISSUE TITLE
feature flag mismatch cohorts rules

### ISSUE THREAD

**Issue by yangluoshen** [PostHog/posthog#14497]
## Bug description
**I create a cohort (named test2)with rule `tenant_id less than 100000000` successfully, and I can see there are 22 persons matched.**

![image](https://user-images.githubusercontent.com/5471004/222393757-8c0f1e22-c1df-4c5c-a0e4-6c23cd90a848.png)

**Then I create a feature flag(feat-test-cohorts), associate with the cohort.**

![image](https://user-images.githubusercontent.com/5471004/222395397-705043a2-c708-4a4f-b651-b71750e5f51e.png)

**Finally, I checked feature flag, it return false(but true is expected).**

_**As a comparison**_

**I create a cohort(named test3) with rule `tenant_id equals 3426`**
![image](https://user-images.githubusercontent.com/5471004/222396117-ab36bfc1-3432-4985-b22e-4988e2f95e3b.png)

**then associate with the same feature flage above**

![image](https://user-images.githubusercontent.com/5471004/222396643-14633316-becd-4907-8d67-0a0efd01c0ff.png)
 

**Finally, I checked feature flag, it return true.**

I can not figure out why example1 would return false, should I trust the result(matching person) that were showed in cohort view?

## How to reproduce

see the bug description above

## Environment

- [x] PostHog Cloud US, project ID: 21628
- [ ] PostHog Cloud EU, project ID: [please provide from https://eu.posthog.com/project/settings#project-id]
- [ ] PostHog Hobby self-hosted with `docker compose`, version/commit: [please provide]
- [ ] PostHog self-hosted with Kubernetes (deprecated, see ["Sunsetting Kubernetes support"](https://posthog.com/blog/sunsetting-helm-support-posthog)), version/commit: [please provide]

**Comment by neilkakkar** [comment]
Thanks for the bug report Yangluo!

Looks like this is because the tenantID is being coerced as string. I'm looking into a fix.

---

For the team:

The problem is that "30" < "100" is false in postgres when doing string comparisons.

I think when saving a flag, we should query property types and coerce string to numbers when the property type is numeric. This way, we don't have to guess at query time, which has a lot more severe restrictions on speed.

Alternatively, we could try and case it if possible and then compare, but this leads to annoying edge cases where we guess wrongly (ex: casing "1.2" to a number when it's a version string). It's a lot worse I think than relying on the data management type inference which users can control to tell us explicitly what the property type should be.

Thoughts?

**Comment by neilkakkar** [comment]
Hmm, or instead of automagic, we can make it explicit, where on a flag, you can choose between numeric and string properties.

**Comment by neilkakkar** [comment]
Actually, another way around this is to replicate just what the cohort calculation does, which is, whenever we're dealing with `<`, `>`, or `<=`, `>=`, operators, always convert to a number. And in this case, it defaults to false if the stored property is not coercable to number.

Actually, this might be the best approach 🤔

**Comment by mariusandra** [comment]
We do also know the type of the property (this is now tracked for both event and person properties), so we could also use that 🤔.

**Comment by yangluoshen** [comment]
> Hmm, or instead of automagic, we can make it explicit, where on a flag, you can choose between numeric and string properties.

Thanks for your response! @neilkakkar 

But tenantID in our system is a type of uint64, so it would lose precision if choose numberic in javascript.

**Comment by neilkakkar** [comment]
Hey @yangluoshen 👋 , for now, you can make this work by changing 10000000 to 9999999 (i.e. subtract 1), while we look into a more long term fix.

**Comment by yangluoshen** [comment]
> Hey @yangluoshen wave , for now, you can make this work by changing 10000000 to 9999999 (i.e. subtract 1), while we look into a more long term fix.

Hey @neilkakkar, I use `matches regex` to solve this problem.

![image](https://user-images.githubusercontent.com/5471004/223041272-801f2b84-9ef0-4391-a31f-4e54450f8255.png)

Thanks for your inspiration, looking forward to a more long term fix ;D
