### ISSUE TITLE
Typo in "Configure" recordings modal

### ISSUE THREAD

**Issue by sankalpdomore** [PostHog/posthog#14494]
## Bug description

Typo for wildcard here in "Configure" recordings modal

![Screenshot -2023-03-02-001562](https://user-images.githubusercontent.com/18334593/222362097-3ff8206b-38ba-4788-a0bb-c97850664d23.png)

## How to reproduce

1. Go to recordings page
2. Open "Configure recordings" modal from top right "Configure" CTA
3. See typo under `Authorized domains for recordings` section

**Comment by NorhanMostafa94** [comment]
wildcard not working with me, I have a site with subdomain but it doesn't record anything
