### ISSUE TITLE
Importing metrics treats a string field as numeric

### ISSUE THREAD

**Issue by amansanghvi** [PostHog/posthog#14492]
## Bug description

I have an event type and its treating the field as numeric when its clearly a string. This is stopping us from breaking down the even by this field. I'm not too sure how this is the case - potentially, because some events are in the format "0x0000000..."? Is there a way to fix this?

<img width="1222" alt="Screen Shot 2023-03-02 at 12 29 05 pm" src="https://user-images.githubusercontent.com/18136832/222308234-e171417f-34d1-4412-b510-08623d72a8bf.png">

**Comment by pauldambra** [comment]
Hey,

You can set the property type in the data management section

https://user-images.githubusercontent.com/984817/222373440-daa696a9-cf62-4e58-99b3-73f8be41f822.mp4

**Comment by pauldambra** [comment]
@amansanghvi I'll close this issue but feel free to re-open if you need to

**Comment by amansanghvi** [comment]
Yes, thanks for responding. We could not find the option as we did not have a premium account, in case anyone else has the same problem.

**Comment by pauldambra** [comment]
Hey @amansanghvi,

That was a frustrating dead-end we'd accidentally built into the product for people there. I've moved editing property type to be accessible to everyone. It's deploying at the moment so you should have access in the next ten minutes

Thanks for highlighting this 🙌
