### ISSUE TITLE
'Start sending events to PostHog' notice won't disappear

### ISSUE THREAD

**Issue by jamesefhawkins** [PostHog/posthog#145]
**Describe the bug**
Running on heroku at https://young-anchorage-28666.herokuapp.com

I have created events by interacting with https://young-anchorage-28666.herokuapp.com/demo

These events are visible in the events view.

When I go to 'Actions' - I just get "start sending events to PostHog" notice, as if it doesn't realise there were actions.

**Expected behavior**
For the notice to disappear so I can create an action with the PostHog toolbar.

**Screenshots**
Events visible:

![Screenshot 2020-02-20 at 01 50 39](https://user-images.githubusercontent.com/47497682/74922226-bfaf9d80-5383-11ea-9a96-7a079a62223c.png)

Notice still there:

![Screenshot 2020-02-20 at 01 51 16](https://user-images.githubusercontent.com/47497682/74922312-dce46c00-5383-11ea-9146-4a7d012593de.png)

**Desktop (please complete the following information):**
 - OS: osx
 - Browser chrome

**Comment by timgl** [comment]
Fixed!
