### ISSUE TITLE
UI of dropdown in Cohort is messed up

### ISSUE THREAD

**Issue by wwchen** [PostHog/posthog#14517]
## Bug description
<img width="672" alt="image" src="https://user-images.githubusercontent.com/344958/222497653-44f099ae-27b2-48d9-85a7-41f4be2f08ba.png">

*Please describe.*  
*If this affects the front-end, screenshots would be of great help.*  

*If you are on PostHog Cloud it would be really valuable if you can share any links where the problem occurs. This speeds up our ability to troubleshoot tremendously.* 

## How to reproduce

1. https://app.posthog.com/cohorts/new
2. click on "completed event" dropdown in the first matching criteria
3.

## Environment

- [x] PostHog Cloud US, project ID: [please provide from https://app.posthog.com/project/settings#project-id]
- [ ] PostHog Cloud EU, project ID: [please provide from https://eu.posthog.com/project/settings#project-id]
- [ ] PostHog Hobby self-hosted with `docker compose`, version/commit: [please provide]
- [ ] PostHog self-hosted with Kubernetes (deprecated, see ["Sunsetting Kubernetes support"](https://posthog.com/blog/sunsetting-helm-support-posthog)), version/commit: [please provide]

**Comment by mariusandra** [comment]
I think this regression was caused by the extra nesting of `Popover__content` added here: https://github.com/PostHog/posthog/pull/14248 🤔
