### ISSUE TITLE
Identify groups linked in captured events, even if it doesn't exist

### ISSUE THREAD

**Issue by baptisteArno** [PostHog/posthog#14553]
## Is your feature request related to a problem?

I'm implementing an event "ingestor" using the Node.js SDK. It processes the data and send it to posthog. It looks like this:

```ts
events.forEach(async (event) => {
  if (event.name === "User created") {
    client.identify({
      distinctId: event.userId,
      properties: event.data,
    });
  }
  if (event.name === 'Workspace created' || event.name === 'Subscription updated')
    client.groupIdentify({
      groupType: "workspace",
      groupKey: event.workspaceId,
      properties: event.data,
    });
  const groups: { workspace?: string } = {};
  if ("workspaceId" in event) groups["workspace"] = event.workspaceId;
  client.capture({
    distinctId: event.userId,
    event: event.name,
    properties: event.data,
    groups,
  });
});
```

The issue here is that if I'm shipping this code in an existing app, workspaces will already be created and so it won't be able to identify it correctly in Posthog.

## Describe the solution you'd like

In an ideal world, this piece of code:

```ts
client.capture({
    distinctId: event.userId,
    event: event.name,
    properties: event.data,
    groups: {workspace: 'unique-id'},
  });
```

Would still identify the workspace even if it doesn't exist.

It works like this for persons. Why not for groups as well?

## Describe alternatives you've considered

I could fix that by identifying it for every new event. But that's really not optimal.

**Comment by neilkakkar** [comment]
Hey @baptisteArno , the solution you describe is exactly how it works today. The only difference being that if you don't groupIdentify, that group has no known **properties**, so it doesn't show up in the `Groups` tab, however all aggregations on this group would work as expected.

**Comment by baptisteArno** [comment]
Ok, that's good to know then, thank you!
