### ISSUE TITLE
Rescaling Funnels in Dashboards "breaks" them

### ISSUE THREAD

**Issue by yakkomajuri** [PostHog/posthog#1455]
## Bug description

*Please describe.*  
*If this affects the front-end, screenshots would be of great help.*  

If I rescale the HogFlix demo funnel, for instance, the funnel illustration does not reach into the final step, even though there are users who reached it.

**Normal:**
![](https://github.com/yakkomajuri/img-store/blob/master/funnel1.png?raw=true)

**Rescaled:**
![](https://github.com/yakkomajuri/img-store/blob/master/funnel2.png?raw=true)

## Expected behavior

Rescale correctly.

## How to reproduce

1. Open PostHog
2. Add a Funnel to a Dashboard
3. Rescale it

## Environment

All.

**Comment by Twixes** [comment]
Some context: I think it used to rescale, but that turned out to be very straining with SVG, so it's only rendered once now.

**Comment by paolodamico** [comment]
We're completely changing the UI of funnels, so I think this will be a moot point. Feel free to reopen if you disagree.
