### ISSUE TITLE
Enable Canvas support for Recordings

### ISSUE THREAD

**Issue by benjackwhite** [PostHog/posthog#14555]
## Is your feature request related to a problem?

Summary issue for:
Closes https://github.com/PostHog/posthog/issues/13888
Closes https://github.com/PostHog/posthog/issues/2798

With RRweb2 we can [enable Canvas support](https://github.com/rrweb-io/rrweb/blob/master/docs/recipes/canvas.md) but it comes with a downside - to playback it seems that the iframe replaying the browser ends up with `<iframe sandbox="allow-scripts allow-same-origin" />` ([see code here](https://github.com/rrweb-io/rrweb/blob/502d15df9f7f43b3408ccfbb3f14c4bb007883c4/packages/rrweb/src/replay/index.ts#L571))

## Describe the solution you'd like

We should investigate what this means in terms of risk. 
* If this is limited to RRWeb doing things back and forth in the iframe then one could argue this is tolerable. 
* If it means the customer's JS is able to run within PostHog, then is it "safe" in the sense that their JS would be able to run in their PostHog account (i.e. unable to affect anyone else)
* If it means any 3rd party JS could run within PostHog then this feels a lot less safe...

**At the very least** we should document the outcome to a FAQ section for Recordings so that we don't 

## Describe alternatives you've considered

We could potentially detect use of canvas playback and offer a way for them to open the recording in a different context that wouldn't expose tokens etc. to the parent running it perhaps.

There is also some sort of webrtc implementation to stream the canvas but that seems targeted at live-streaming, not cold playback.

## Additional context

https://github.com/rrweb-io/rrweb/blob/master/docs/recipes/canvas.md
https://github.com/PostHog/posthog-js/pull/562/files

**Comment by mariusandra** [comment]
Does this mean that the "correct" solution is to record the WebRTC stream in our backend (hello media encoding servers) and then play it back during playback? 🙈

**Comment by benjackwhite** [comment]
Maybe? It definitely seems more geared towards live-streaming between browsers (think Teamviewer support) than offline playback. 

I'm wondering if there is a way we can do this with nested iframes 🤔

**Comment by mano233** [comment]
> 或许？与离线播放相比，它似乎更适合浏览器之间的实时流式传输（想想 Teamviewer 支持）。
> 
> 我想知道是否有一种方法可以使用嵌套的 iframe 来做到这一点🤔

I think using canvas snapshot would avoid the security issue

**Comment by mano233** [comment]
> Maybe? It definitely seems more geared towards live-streaming between browsers (think Teamviewer support) than offline playback.
> 
> I'm wondering if there is a way we can do this with nested iframes 🤔

I think that using canvas snapshot can avoid security issues.(use S3)

**Comment by edweip3** [comment]
Can you at least enable recording but disable playback? That way we can still use the API to fetch the recording and playback locally.

**Comment by Vadman97** [comment]
Shameless plug here, if you are interested in another tool for session recordings that does support `<canvas>` and WebGL, check out https://www.highlight.io/docs/getting-started/client-sdk/replay-configuration/canvas

**Comment by kylewhitaker** [comment]
Hey @benjackwhite thanks for answering [my question on Posthog about this](https://posthog.com/questions/record-canvas-elements)! Have y'all considered [Alternatively enable image snapshot recording of Canvas at a maximum of 15 frames per second](https://github.com/rrweb-io/rrweb/blob/master/docs/recipes/canvas.md)? On the surface, it seems like it would solve the security woes, but I'm sure it's no small lift to store, retrieve, and replay these images in line with the rest of replay. Wdyt? How can I help? I'm an engineer at [DataGPT](https://datagpt.com/) and we rely heavily on canvas in our UI application where we're using Posthog's session replay, so this is a blindspot for us on Posthog's platform!

**Comment by benjackwhite** [comment]
@kylewhitaker  I don't think its that simple I'm afraid. 

Just set up a branch to validate this here: https://github.com/PostHog/posthog-js/tree/feat/canvas
The capture works but the playback doesn't without making the iframe insecure (which exposes us to potential dangerous scripts). 

I'd love to have a quick win here but there doesn't seem to be one without diving deeper into rrweb and making some changes. Very ready to be corrected though!

**Comment by benjackwhite** [comment]
Did some further digging to see if enabling with those options and modifying rrweb to not set "allow-scripts" on the iframe works - but nope! So I think the current implementation just wont work without that iframe setting (which is the issue).

**Comment by Jaxkr** [comment]
Would love to see this feature!

**Comment by Jaxkr** [comment]
Hey @benjackwhite and @pauldambra, sorry to bother but I noticed this feature was referenced in your [most recent completed sprint](https://github.com/PostHog/posthog/issues/18807#issuecomment-1822511167). What was the fate of it? Is it a hangover issue?

**Comment by pauldambra** [comment]
Ah @Jaxkr that was a different canvas issue... we're planning for the next few months tomorrow... let's see what that brings

**Comment by kylewhitaker** [comment]
@daibhin n00b here, how might I "reach out via support" to get the preview?

**Comment by daibhin** [comment]
Canvas support is now live for all. It is opt-out by default (as there is no way to mask PII) so you will need to enable it from the [Replay settings within the PostHog app](https://us.posthog.com/replay/recent#panel=settings)

**Comment by kylewhitaker** [comment]
@daibhin We've been seeing Canvas recordings for the past week now. Really thrilled about this feature add, thank you!
