### ISSUE TITLE
Clicking an app link when not logged in takes you to the home page after you log in

### ISSUE THREAD

**Issue by charlescook-ph** [PostHog/posthog#14565]
## Bug description

I often click on links straight to a dashboard or insight that I access frequently (e.g. bookmarks). If I've been logged out of the app, I'll be shown the login screen and prompted to log in again which is fine. 

However, after logging in, I'm then sent to my home view in the app rather than the link I originally clicked on. 

## How to reproduce

1. Sign out of the PostHog app
2. Try to visit a link that requires you to be logged into PostHog
3. Go through the login flow

## Environment

- [x] PostHog Cloud US, project ID: 2
- [ ] PostHog Cloud EU, project ID: [please provide from https://eu.posthog.com/project/settings#project-id]
- [ ] PostHog Hobby self-hosted with `docker compose`, version/commit: [please provide]
- [ ] PostHog self-hosted with Kubernetes (deprecated, see ["Sunsetting Kubernetes support"](https://posthog.com/blog/sunsetting-helm-support-posthog)), version/commit: [please provide]

**Comment by Twixes** [comment]
That's weird! I can't reproduce the problem. Can you share a screen recording privately?

**Comment by charlescook-ph** [comment]
Quick summary of screenshare I just did with @Twixes - it only happens if you go to login - _type in your username_ and then click the 'Sign in with Google button' that appears because sign in with Google is enforced. 

(if you go to login and then immediately hit the 'sign in with Google' button at the bottom, this doesn't happen).
