### ISSUE TITLE
Last X (quarters) doesn't work as expected in insights

### ISSUE THREAD

**Issue by jamesefhawkins** [PostHog/posthog#14585]
## How to reproduce

1. go to [an insight](https://app.posthog.com/insights/-XmLO32n)
2. change date range to <img width="278" alt="Screenshot 2023-03-07 at 10 11 32" src="https://user-images.githubusercontent.com/47497682/223391541-cc519615-30fc-4b46-bbc9-6967e8db6926.png">
3. click the 'in the last' text to select the date range
4. it hasn't updated with the 'quarters' appropriately
<img width="245" alt="Screenshot 2023-03-07 at 10 12 02" src="https://user-images.githubusercontent.com/47497682/223391668-c08b0ccb-864c-4f8d-ba17-3aa790854d45.png">

## Environment

- [x] PostHog Cloud US, project ID: [please provide from https://app.posthog.com/project/settings#project-id]
- [ ] PostHog Cloud EU, project ID: [please provide from https://eu.posthog.com/project/settings#project-id]
- [ ] PostHog Hobby self-hosted with `docker compose`, version/commit: [please provide]
- [ ] PostHog self-hosted with Kubernetes (deprecated, see ["Sunsetting Kubernetes support"](https://posthog.com/blog/sunsetting-helm-support-posthog)), version/commit: [please provide]

**Comment by yakkomajuri** [comment]
Tried this out - all the other options work except for "quarters"
