### ISSUE TITLE
remove trailing spaces in the selector box

### ISSUE THREAD

**Issue by Algogator** [PostHog/posthog#1458]
## Bug description

*Please describe.*  
*If this affects the front-end, screenshots would be of great help.*  

Trailing spaces in the selector box are not removed automatically and can mess up the event results when saving an action

## How to reproduce

1. Create a new action with any selector
2. put in a couple of spaces at the end of the line in the selector input box
3. 

## Environment

- Self-managed?
- PostHog version/commit

**Comment by J0** [comment]
Hi,

Can I take this?
