### ISSUE TITLE
Screen Recordings Bug

### ISSUE THREAD

**Issue by christophostertag** [PostHog/posthog#14599]
## Bug description

*Please describe.*  
*If this affects the front-end, screenshots would be of great help.*  

*If you are on PostHog Cloud it would be really valuable if you can share any links where the problem occurs. This speeds up our ability to troubleshoot tremendously.* 

## How to reproduce

1.
2.
3.

## Environment

- [ ] PostHog Cloud US, project ID: [please provide from https://app.posthog.com/project/settings#project-id]
- [x] PostHog Cloud EU, project ID: 3087
- [ ] PostHog Hobby self-hosted with `docker compose`, version/commit: [please provide]
- [ ] PostHog self-hosted with Kubernetes (deprecated, see ["Sunsetting Kubernetes support"](https://posthog.com/blog/sunsetting-helm-support-posthog)), version/commit: [please provide]

#### *Thank you* for your bug report – we love squashing them!
https://www.loom.com/share/fc2c14a41a424460a982fc1098205688

**Comment by benjackwhite** [comment]
Thanks for reporting this. Should have a fix up soon to avoid this situation in the future.
