### ISSUE TITLE
Allow multiple teams + switching between teams

### ISSUE THREAD

**Issue by timgl** [PostHog/posthog#1461]
## Is your feature request related to a problem?

I want to be able to belong to multiple teams and switch between those as a user

## Describe the solution you'd like

- In the frontend (top right seems a logical place) I want a dropdown where i can switch between teams that I am a part of.
- In the backend, the user should have a `current_team` PK that links to whatever team the user currently selects
- Update the `team` property on the user model to return the `current_team`
- If `current_team` is null, just grab the first team

**Comment by Twixes** [comment]
Done in #1540.
