### ISSUE TITLE
Allow disabling of sharing link in settings

### ISSUE THREAD

**Issue by timgl** [PostHog/posthog#1465]
## Is your feature request related to a problem?

I want to be able to disable the sharing link for extra security

## Describe the solution you'd like

A toggle to disable the sharing link in the sharing modal

## Describe alternatives you've considered

-

**Comment by Twixes** [comment]
A slightly friendlier solution may be just a "Regenerate invite" button, which'd replace the team's current `signup_token` with a new one (possibly less work to implement on the frontend too).

**Comment by Twixes** [comment]
On the backend, this would be best as an `@action(methods=["POST"], detail=False)` on an `/api/team/` endpoint. The endpoint itself could be very basic, it'd just serve as a logical place for an action on the Team model.

**Comment by J0** [comment]
Hey @timgl @Twixes,

Can I take up this issue? Not sure if the pairing offer in the README still holds but if it does I'd love to schedule a pairing session to start on this issue and get familiar with this codebase.

Thanks
Joel

**Comment by timgl** [comment]
@J0 For sure! Feel free to [schedule some time in my calendar](https://calendly.com/timgl/30min?month=2020-08)

**Comment by J0** [comment]
Done. Looking forward to building this feature! :)

**Comment by fuziontech** [comment]
This as an env var could be nice too. Would make disabling in other infrastructures where access to the DB is not easy

**Comment by Twixes** [comment]
Hmm, are there situations where a PATCH request to Django is insufficient? @fuziontech
