### ISSUE TITLE
Bug: Clicking breakdown tooltip opens new tab

### ISSUE THREAD

**Issue by joethreepwood** [PostHog/posthog#14654]
## Bug description

As per title. Click the breakdown tooltip and we open a new, blank insight in a new tab. Dunno why. 

![New Recording Mar 09 2023 0120 PM](https://user-images.githubusercontent.com/84011561/224035816-f6465348-8c8a-4a6b-b627-631234e5a1f0.gif)

I'm not lying, see?

## How to reproduce

1.
2.
3.

## Environment

- [ ] PostHog Cloud US, project ID: [please provide from https://app.posthog.com/project/settings#project-id]
- [ ] PostHog Cloud EU, project ID: [please provide from https://eu.posthog.com/project/settings#project-id]
- [ ] PostHog Hobby self-hosted with `docker compose`, version/commit: [please provide]
- [ ] PostHog self-hosted with Kubernetes (deprecated, see ["Sunsetting Kubernetes support"](https://posthog.com/blog/sunsetting-helm-support-posthog)), version/commit: [please provide]

**Comment by Twixes** [comment]
Looks like this was introduced in https://github.com/PostHog/posthog/pull/14628/files#diff-1b47bf083ce78a9ed78bb027fb3a2f605d391773891b20822ad9aa3bcc23ccabR38. CC @yakkomajuri If there is `info` but not `infoLink` on a field, there's still a link on the info icon, except it just opens the _current page_ in a new tab.
