### ISSUE TITLE
Clicks not captured on elements inside Shadow DOM

### ISSUE THREAD

**Issue by FreakyDug** [PostHog/posthog#1469]
## Bug description

We use web components in our product, so some parts of the page are inside various Shadow DOMs attached to those components. We do not seem to be getting any click events recorded for anything under those shadow roots.

## Expected behavior

We would expect elements inside the shadow DOM to record clicks like other elements.

## How to reproduce

1. Enable Posthog on an application that users webcomponents that use shadow DOM
2. Click on an element within a shadow DOM
3. No event is recorded in posthog

## Environment

- Self managed
- Version 1.12.0

**Comment by Twixes** [comment]
Happy to report that events under shadow roots will now be captured thanks to PostHog/posthog-js#80. That should land in the nearest release.
