### ISSUE TITLE
Add an ability to swicth projects via the URL

### ISSUE THREAD

**Issue by AndyDalton** [PostHog/posthog#14711]
## Is your feature request related to a problem?

No. I was advised by support to raise this as possible functionality, but it poses no problem, just a nice to have.

## Describe the solution you'd like

In our internal applications it would save time if we could link out to certain pages in the Posthog site. For example, we identify users, so it would be good to have a link out to search for that user id, such as https://eu.posthog.com/person/b922425f-1b69-4b64-abd2-59689ebde5df.  This saves our users having to copy the id and know where to search.

If our user is not signed in, it will follow through after login with the return URL (i.e., https://eu.posthog.com/login?next=/person/b922425f-1b69-4b64-abd2-59689ebde5df). This works fine, but only if the correct project is selected.  It would be really handy if we could carry across the target team id in the URL, so it could switch to the correct project before following the link.

Either
https://eu.posthog.com/person/b922425f-1b69-4b64-abd2-59689ebde5df&team=3011

Or via an interstitial page
https://eu.posthog.com/team?id=3011&next=/person/b922425f-1b69-4b64-abd2-59689ebde5df

## Describe alternatives you've considered

Possibly setting the team for the user via the API before redirecting (via set_current_team on the users API). However, this would mean bringing knowledge of the authentication into our app, which we would rather avoid.

## Additional context

N/A

**Comment by mariusandra** [comment]
We need to pick this up again: https://github.com/PostHog/posthog/pull/13474

**Comment by benjackwhite** [comment]
haha you got there first :D

**Comment by timgl** [comment]
Closing as duplicate ^
