### ISSUE TITLE
Gravatar profile picture

### ISSUE THREAD

**Issue by Twixes** [PostHog/posthog#1474]
## Is your feature request related to a problem?

We could make the app's UI a bit more "human" by putting a user's profile picture in the top right.

## Describe the solution you'd like

A pretty simple solution would be pulling in the [gravatar](https://en.gravatar.com) linked to the user's email address.

## Describe alternatives you've considered

We could add pictures uploaded by users to PostHog, but that'd be significantly more effort and doesn't seem worth it at the moment.

## Additional context

Noticed today that Docker Hub does this, but I've definitely seen lots of other services do it as well before.

**Comment by mariusandra** [comment]
There might be some issues with sending personal data to third parties, even if the email is hashed (md5?) in the url...

**Comment by Twixes** [comment]
Hm, I don't think there would be any personal data involved. MD5 may not be completely collision-proof, but it still is practically irreversible.

**Comment by paolodamico** [comment]
You mean adding the profile picture for PostHog users or for the tracked end-users (`Person`)? I would also consider doing something like this for [placeholders](https://evergreen.segment.com/components/avatar) when a profile picture is not available, or even consider it as a primary implementation.

**Comment by Twixes** [comment]
I was rather thinking about PostHog users. Though persons is a possibility as well.
