### ISSUE TITLE
Sprint March 20 to April 14

### ISSUE THREAD

**Issue by timgl** [PostHog/posthog#14745]
# Global Sprint Planning

## 3 things that might take us down

1.
2.
3.

## Retro: What can we do better next sprint?

1.
2.
3.
4.
5.

## Support hero this sprint

Week 1: 
Week 2:

# Team sprint planning

For your team sprint planning copy this template into a comment below for each team.

```
Team ___

## Retro

<!-- Grab the high and low priority items from last time and add whether that item was completed or not -->

- 

## Hang over items from previous sprint

<!-- For each item, decide to re-prioritise (and add below) or deprioritise -->

- Item 1. prioritised/deprioritise

## OKR

1. OKR, status (red/yellow/green) and action points if yellow/red


### High priority

-

### Low priority / side quests

-

```

**Comment by mariusandra** [comment]
Team product analytics priorities for this short one-week sprint.

@Twixes support hero
@thmsobrmlr on vacation
@macobo not here
@pauldambra on vacation week of apr 3rd to 7th
### Team sprint planning

Priorities for @pauldambra, @yakkomajuri and @mariusandra

- Performance - persons on events v2 @yakkomajuri 
Why? PoEv2 is necessary for high volume clients. The ball is in our court now.

- HogQL - [keep wrapping it up](https://github.com/PostHog/meta/issues/81) @mariusandra @pauldambra 
Why? Users 😍 SQL queries. There will be odds and ends to clean up.


### Retro

- Data exploration - wrapping up funnels. Almost ready for an internal release, target this week.
- PostHog 3000 - insight list in new style, hopeful for end of week.
- Performance - very happy with sampling (in beta). Was hard to get reviewers.
- HogQL - releasing to beta users still this week
- Karl context passover - going good: clickhouse talk + manual improvements. Warehouse benchmarks.

**Comment by neilkakkar** [comment]
If I'm not reading the dates wrong, it's still a 2 week sprint spread over 3 weeks (one week + offsite + one week)

**Comment by pauldambra** [comment]
> a 2 week sprint spread over 3 weeks (one week + offsite + one week)

This gets my vote as the consistent pattern! We'd get to visit nearly 20 countries a year

**Comment by mariusandra** [comment]
@neilkakkar you're right. The dates are for 3 weeks. 

People working that week in this team will be Michael, Thomas and me, so we'll do a combination of:
- Hackathon followup
- Customer issues we neglected during the offsite that moved from yellow to red
- More PostHog 3000, HogQL and Data Exploration.
- Whatever we decided for Q2

I'm really unable to foresee a better (more detailed) plan, which won't be wildly ignored when April rolls around.

**Comment by neilkakkar** [comment]
## Team We-are-not-sure-of-our-name-yet-so-we're-Experimenting

Planning:

1. Winding up things that fell through the cracks during Q1 & KTLO
Why? So we can hit the ground running in Q2 without baggage, and ensure follow ups on things that have fallen through the cracks


Sub-goals:
- Feature flags UI code examples windup + user interviews - @liyiy 
- Payload docs - @liyiy 
- Resiliency wrap up @neilkakkar 
- flags when impersonating @neilkakkar 
- Recordings on flags intent: @EDsCODE 

And more:
Server-side libs: $geoip_disable by default, automatic flags on all events when possible.
Ignore geoIP computed properties when computing flags using server-side libs

## Retro

#### Make the experience of creating a feature flag in PostHog slicker @liyiy

Rest of UI suggestions left in the [figma](https://www.figma.com/file/HOLxXjBZ2HKYIFFtgBftbt/Feature-Flags-UI-2.0?node-id=202%3A2366&t=N0d5XUw0wvc7DGRR-1) -> Mostly sorted, will do some user validation next sprint before general release.

#### Eliminate the biggest reasons product engineers would choose a competitor over PostHog Feature Flags @neilkakkar

Cohort Local Evaluation in Node and Python -> Sorted
Resiliency updates -> Not sorted, carrying on

#### Analysis of feature flags using recordings @EDsCODE 

Finish optimizing recordings list query -> PR out
Figuring out how to filter more accurately for recording associated with flag
