### ISSUE TITLE
Launching an experiment reset feature flag rollout to 100%

### ISSUE THREAD

**Issue by Lior539** [PostHog/posthog#14817]
## Bug description

I'm trying to run an experiment using 20% of my users. I set the feature flag rollout percentage to 20, but when I press "Launch" on the experiment, it changes this back to 100% (the default). 

### Repro steps:
1. Setup new experiment
2. Go to feature flag, change rollout to 20%
3. Go back to experiment, press launch

### Expected behaviour:
Rollout percentage stays at 20%

### Actual:
Rollout percentage changed to 100%

*Please describe.*  
*If this affects the front-end, screenshots would be of great help.*  

*If you are on PostHog Cloud it would be really valuable if you can share any links where the problem occurs. This speeds up our ability to troubleshoot tremendously.* 

## Additional context
Screenshot for clarity 
<img width="678" alt="Screenshot 2023-03-19 at 13 00 07" src="https://user-images.githubusercontent.com/7090054/226176884-1dea662f-7ab1-4e64-ab2c-8c0754f863f1.png">

**Comment by neilkakkar** [comment]
Looking into this @Lior539 . For now, you can get around this by launching and then changing the flag rollout back to 20%

**Comment by neilkakkar** [comment]
Hmm, I can't reproduce, would you mind trying the repro steps again @Lior539  and confirm if it indeed bugs out?
