### ISSUE TITLE
Minor bug with OPT_OUT_CAPTURE

### ISSUE THREAD

**Issue by paolodamico** [PostHog/posthog#1482]
## Bug description

It seems like with `OPT_OUT_CAPTURE = True` we're still sending the events: ["user logged in" L47](https://github.com/PostHog/posthog/blob/master/posthog/urls.py#L47), ["$identify" L97](https://github.com/PostHog/posthog/blob/master/posthog/urls.py#L97), ["user signed up" L96](https://github.com/PostHog/posthog/blob/master/posthog/urls.py#L96).

Sample user: `YQJ4T_WhhSVRs5ycfBoWUF5YIeHRVPN0fDQW1U5edws` (only these events are stored for the user).

## Expected behavior
- When `OPT_OUT_CAPTURE = True` these events should not be sent.

## How to reproduce

1. Download and launch a local test copy of the repo.
2. Set `OPT_OUT_CAPTURE = 1` before opening the project. 
3. Sign up with a test account, log out and then log in. Events will be visible on PostHog.

## Environment

- PostHog cloud or self-managed? **Applies to self-managed.**
- PostHog version/commit. **Master.**

## Additional context
No additional context.

**Comment by Twixes** [comment]
This should be as simple as just adding condition `if not settings.OPT_OUT_CAPTURE:` to these `posthoganalytics` method calls, shouldn't it?

**Comment by paolodamico** [comment]
> This should be as simple as just adding condition `if not settings.OPT_OUT_CAPTURE:` to these `posthoganalytics` method calls, shouldn't it?

Yes exactly, I'm doing that. I just want to make sure that we were seeing these users-events due to this and not some other issue on the cloud version.

**Comment by Twixes** [comment]
Hm, looks like this
<img width="556" alt="Screenshot 2020-08-22 at 00 03 02" src="https://user-images.githubusercontent.com/4550621/90939035-e0c47a00-e40a-11ea-903d-c4fb719f0daf.png">
should've been making additional checks redundant. So this may be more of an issue with https://github.com/PostHog/posthog-python.

**Comment by paolodamico** [comment]
Oh, might be something else altogether, because there's also some evidence to suggest that these might be cloud users, and this wouldn't make sense.

**Comment by Twixes** [comment]
Ah, right, so the alternative is that these users should have *more* events logged, as they are on `app.posthog.com`?

**Comment by paolodamico** [comment]
Exactly, if they are `app.posthog.com` they should have browser events logged too, at least `$pageview`

**Comment by Twixes** [comment]
How are we doing on this front now?

**Comment by paolodamico** [comment]
Haven't seen anything that suggests this is still a problem. Will close and we can always reopen if this changes.
