### ISSUE TITLE
stat /compose/temporal-django-worker: no such file or directory: unknown on installation

### ISSUE THREAD

**Issue by fibis** [PostHog/posthog#14865]
## Bug description

I am trying a clean installation with the provided installation script. I am running the script with all default parameters. When I come to the step that all containers are starting, the following error message occurs:

> Error response from daemon: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: exec: "/compose/temporal-django-worker": stat /compose/temporal-django-worker: no such file or directory: unknown

## How to reproduce

1. Running the installation script via `/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/posthog/posthog/HEAD/bin/deploy-hobby)"`
2. Use default for the `latest-release` and insert a domain
3. Wait for the creation of the containers and the message "Starting the stack!" after that, the error message will be thrown.

## Environment

- [ ] PostHog Cloud US, project ID: [please provide from https://app.posthog.com/project/settings#project-id]
- [ ] PostHog Cloud EU, project ID: [please provide from https://eu.posthog.com/project/settings#project-id]
- [x] PostHog Hobby self-hosted with `docker compose`, version/commit: latest-release
- [ ] PostHog self-hosted with Kubernetes (deprecated, see ["Sunsetting Kubernetes support"](https://posthog.com/blog/sunsetting-helm-support-posthog)), version/commit: [please provide]

## Additional context
I think this error is related to this commit: https://github.com/PostHog/posthog/commit/0223d7ab868676d4562425ec1d3778cbd715b9a0

**Comment by fionnfuchs** [comment]
I am also encountering this error. 
I think the `docker-compose.hobby.yml` which is used as the `docker-compose.yml` for the self-hosted deployment is not correct. Looking at the `docker-compose.dev-full.yml` I think what is happening is that the wrong directory is mounted as a volume.

I have been able to get one step further I think. In the docker compose file I changed the config for the temporal django worker service to the following (be sure to replace <your-domain-here> accordingly):

```
temporal-django-worker:
        working_dir: /app/posthog
        extends:
            file: docker-compose.base.yml
            service: temporal-django-worker
        volumes:
            - ./posthog:/app/posthog
        image: posthog/posthog:latest-release
        environment:
            SENTRY_DSN: 'https://public@sentry.example.com/1'
            SITE_URL: https://<your-domain-here>
```

Starting the temporal-django-worker service with `docker-compose up temporal-django-worker`, it now finds the executable temporal-django-worker, but now complains that the module `django_otp` is missing. 

**Below are my attempts of fixing this - might want ignore the stuff below as it lead to nothing**

```
posthog-temporal-django-worker-1  | 2023-03-22 19:35.24 [warning  ] ['️Environment variable DEBUG is set - PostHog is running in DEVELOPMENT MODE!', 'Be sure to unset DEBUG if this is supposed to be a PRODUCTION ENVIRONMENT!']
posthog-temporal-django-worker-1  | Traceback (most recent call last):
posthog-temporal-django-worker-1  |   File "manage.py", line 21, in <module>
posthog-temporal-django-worker-1  |     main()
posthog-temporal-django-worker-1  |   File "manage.py", line 17, in main
posthog-temporal-django-worker-1  |     execute_from_command_line(sys.argv)
posthog-temporal-django-worker-1  |   File "/python-runtime/django/core/management/__init__.py", line 419, in execute_from_command_line
posthog-temporal-django-worker-1  |     utility.execute()
posthog-temporal-django-worker-1  |   File "/python-runtime/django/core/management/__init__.py", line 395, in execute
posthog-temporal-django-worker-1  |     django.setup()
posthog-temporal-django-worker-1  |   File "/python-runtime/django/__init__.py", line 24, in setup
posthog-temporal-django-worker-1  |     apps.populate(settings.INSTALLED_APPS)
posthog-temporal-django-worker-1  |   File "/python-runtime/django/apps/registry.py", line 91, in populate
posthog-temporal-django-worker-1  |     app_config = AppConfig.create(entry)
posthog-temporal-django-worker-1  |   File "/python-runtime/django/apps/config.py", line 224, in create
posthog-temporal-django-worker-1  |     import_module(entry)
posthog-temporal-django-worker-1  |   File "/usr/local/lib/python3.8/importlib/__init__.py", line 127, in import_module
posthog-temporal-django-worker-1  |     return _bootstrap._gcd_import(name[level:], package, level)
posthog-temporal-django-worker-1  |   File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
posthog-temporal-django-worker-1  |   File "<frozen importlib._bootstrap>", line 991, in _find_and_load
posthog-temporal-django-worker-1  |   File "<frozen importlib._bootstrap>", line 973, in _find_and_load_unlocked
posthog-temporal-django-worker-1  | ModuleNotFoundError: No module named 'django_otp'
```

I then went into the container and installed the module django-otp there manually. Now another module is not found:

```
Traceback (most recent call last):
  File "manage.py", line 21, in <module>
    main()
  File "manage.py", line 17, in main
    execute_from_command_line(sys.argv)
  File "/python-runtime/django/core/management/__init__.py", line 419, in execute_from_command_line
    utility.execute()
  File "/python-runtime/django/core/management/__init__.py", line 395, in execute
    django.setup()
  File "/python-runtime/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/python-runtime/django/apps/registry.py", line 91, in populate
    app_config = AppConfig.create(entry)
  File "/python-runtime/django/apps/config.py", line 224, in create
    import_module(entry)
  File "/usr/local/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 973, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'two_factor'
```

This module I cannot install as I don't know where its coming from.

Additionally the container that is running python 3.8 but the code in this repo is using features of python 3.10 as far as I can see.

**Comment by fibis** [comment]
Maybe a problem could also be, that the images with the tag latest-release, so version 1.43.0 are used, but the pulled repo and also the templates for the docker-compose files, are the latest version from the master. They should use the latest tag from the repository.

**Comment by jlieow** [comment]
Facing a similar issue. Specifying previous versions with that command does not resolve the issue.

**Comment by andregerbaulet** [comment]
I had the exact same issue. The docker compose file in the posthog repo which was updated a few days ago is incorrectly configured, I think.

My solution was to create a `setup.sh` file with the content from "https://raw.githubusercontent.com/posthog/posthog/HEAD/bin/deploy-hobby" instead of running it directly, and then add a line to `git checkout` to an older commit of the posthog repo.

```
[...]
git clone https://github.com/PostHog/posthog.git &> /dev/null || true
cd posthog
git pull
# Add the line below to checkout to an older commit
git checkout 6dc2bb475cb528f0e51d2857f997c8e00ee1201d
cd ..
[...]
```

It then worked by running `/bin/bash setup.sh` using the latest-release version, except that I had to manually change the kafka image version directly in the docker-compose.base.yml file, but your mileage may vary.

The commit I used is from about a month ago.

Hope this works for you too.

**Comment by pavitrakumar78** [comment]
Same issue. With the older version, I'm having trouble with trusted proxy settings. Even after setting `TRUST_ALL_PROXIES=True`, I still see logs saying I have not configured any trusted proxies. 

Edit: In addition to the proxy issue, I'm also have DB issues:
`Launchpad failure! error: relation "posthog_action" does not exist` 

Any ideas on how to debug/fix this?

**Comment by huksley** [comment]
I have the same issue! Frustrating.

**Comment by jlieow** [comment]
@andregerbaulet thank you! This works perfectly!

**Comment by pavitrakumar78** [comment]
@andregerbaulet are there any additional steps to this? I tried and still get the same `relation "posthog_action" does not exist` issue. FWIW, after compose (fails due to caddy), I remove caddy from the compose file and restart the containers and this is a fresh install - not an upgrade. 

Any suggestions?

**Comment by tomasfarias** [comment]
Hey all :wave: 

We are testing out [Temporal](https://temporal.io/) in the PostHog stack to support new features and we wanted it to be available in hobby deployments too.

Unfortunately, the hobby deployment script was missing a snippet of code to start-up the Temporal worker. This was causing the `stat /compose/temporal-django-worker: no such file or directory` error reported.

I was able to reproduce the issue and fix it by including the missing snippet. I'll be merging a PR with the changes ASAP (see #14908). After the changes are merged, you should not see this issue anymore when following the same steps detailed in the "How to Reproduce" OP.

Moving forward, we'll be reviewing our hobby deployment testing pipeline as this should have been caught by our automated checks.

Apologies for the inconveniences and thanks for the detailed error reports :bow:

**Comment by pavitrakumar78** [comment]
@tomasfarias Thank you for the fix!

I'm still having plugin server issue with the new script:

```
posthog_install_new-worker-1                  | ⌛️ Waiting 2 seconds before restarting...
posthog_install_new-worker-1                  | yarn run v1.22.17
posthog_install_new-worker-1                  | $ BASE_DIR=.. node dist/index.js
posthog_install_new-worker-1                  | [MAIN] 15:29:02 ⚡ @posthog/plugin-server v1.10.5
posthog_install_new-worker-1                  | [MAIN] 15:29:02 ℹ️ 4 workers, 10 tasks per worker
posthog_install_new-worker-1                  | [MAIN] 15:29:02 ℹ️ Connecting to all services:
posthog_install_new-worker-1                  | [MAIN] 15:29:02 🤔 Postgresql
posthog_install_new-worker-1                  | [MAIN] 15:29:03 👍 Postgresql
posthog_install_new-worker-1                  | [MAIN] 15:29:03 🤔 Redis
posthog_install_new-worker-1                  | [MAIN] 15:29:03 👍 Redis
posthog_install_new-worker-1                  | [MAIN] 15:29:03 ✅ Connected to Redis!
posthog_install_new-worker-1                  | [MAIN] 15:29:03 💥 Launchpad failure! error: relation "posthog_action" does not exist
posthog_install_new-worker-1                  |     at Parser.parseErrorMessage (/home/posthog/code/plugin-server/node_modules/pg-protocol/dist/parser.js:287:98)
posthog_install_new-worker-1                  |     at Parser.handlePacket (/home/posthog/code/plugin-server/node_modules/pg-protocol/dist/parser.js:126:29)
posthog_install_new-worker-1                  |     at Parser.parse (/home/posthog/code/plugin-server/node_modules/pg-protocol/dist/parser.js:39:38)
posthog_install_new-worker-1                  |     at Socket.<anonymous> (/home/posthog/code/plugin-server/node_modules/pg-protocol/dist/index.js:11:42)
posthog_install_new-worker-1                  |     at Socket.emit (events.js:400:28)
posthog_install_new-worker-1                  |     at Socket.emit (domain.js:475:12)
posthog_install_new-worker-1                  |     at addChunk (internal/streams/readable.js:293:12)
posthog_install_new-worker-1                  |     at readableAddChunk (internal/streams/readable.js:267:9)
posthog_install_new-worker-1                  |     at Socket.Readable.push (internal/streams/readable.js:206:10)
posthog_install_new-worker-1                  |     at TCP.onStreamRead (internal/stream_base_commons.js:188:23) {
posthog_install_new-worker-1                  |   length: 113,
posthog_install_new-worker-1                  |   severity: 'ERROR',
posthog_install_new-worker-1                  |   code: '42P01',
posthog_install_new-worker-1                  |   detail: undefined,
posthog_install_new-worker-1                  |   hint: undefined,
posthog_install_new-worker-1                  |   position: '48',
posthog_install_new-worker-1                  |   internalPosition: undefined,
posthog_install_new-worker-1                  |   internalQuery: undefined,
posthog_install_new-worker-1                  |   where: undefined,
posthog_install_new-worker-1                  |   schema: undefined,
posthog_install_new-worker-1                  |   table: undefined,
posthog_install_new-worker-1                  |   column: undefined,
posthog_install_new-worker-1                  |   dataType: undefined,
posthog_install_new-worker-1                  |   constraint: undefined,
posthog_install_new-worker-1                  |   file: 'parse_relation.c',
posthog_install_new-worker-1                  |   line: '1191',
posthog_install_new-worker-1                  |   routine: 'parserOpenTable'
posthog_install_new-worker-1                  | }
posthog_install_new-worker-1                  | [MAIN] 15:29:03 💤  Shutting down gracefully...
posthog_install_new-worker-1                  | [MAIN] 15:29:03 👋 Over and out!
posthog_install_new-worker-1                  | error Command failed with exit code 1.
posthog_install_new-worker-1                  | info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
posthog_install_new-worker-1                  | 💥 Plugin server crashed!
posthog_install_new-worker-1                  | ⌛️ Waiting 2 seconds before restarting...
```

Can you please help with this?

I've opened a new issue here: https://github.com/PostHog/posthog/issues/14910

**Comment by deepaksathya** [comment]
> I had the exact same issue. The docker compose file in the posthog repo which was updated a few days ago is incorrectly configured, I think.
> 
> My solution was to create a `setup.sh` file with the content from "https://raw.githubusercontent.com/posthog/posthog/HEAD/bin/deploy-hobby" instead of running it directly, and then add a line to `git checkout` to an older commit of the posthog repo.
> 
> ```
> [...]
> git clone https://github.com/PostHog/posthog.git &> /dev/null || true
> cd posthog
> git pull
> # Add the line below to checkout to an older commit
> git checkout 6dc2bb475cb528f0e51d2857f997c8e00ee1201d
> cd ..
> [...]
> ```
> 
> It then worked by running `/bin/bash setup.sh` using the latest-release version, except that I had to manually change the kafka image version directly in the docker-compose.base.yml file, but your mileage may vary.
> 
> The commit I used is from about a month ago.
> 
> Hope this works for you too.

Hi,
Thanks, the solution worked for me. But I then saw the changed docker-compose.yml that was generated post git checkout of the older commit doesn't have the 4 temporal services:
1.  temporal
2.  temporal-admin-tools
3. temporal-ui
4. temporal-django-worker
So what is the purpose of the above 4 services, are they optional? Application is now working without these 4 services.

**Comment by tomasfarias** [comment]
If you are running the default `latest-release` version, that `docker-compose.yml` doesn't include the Temporal services as they had not been added by the time the `latest-release` version was released.

You can check out the `latest-release` tag, which corresponds to [v1.43.0](https://github.com/PostHog/posthog/tree/1.43.0), to confirm that the [`docker-compose.hobby.yml`](https://github.com/PostHog/posthog/blob/1.43.0/docker-compose.hobby.yml) doesn't have the services yet.

If you chose the `latest` version that would include the Temporal services. However, they are still being tested, so even if you were to disable them, they are not critical to the application.

Hope this answers your question.

**Comment by madjam002** [comment]
I know docker compose setups are community supported only but it would be very helpful though if Posthog could provide some additional clarification on whether we can expect any further numbered releases or updates to the latest-release tag.

The only update I could find is here - https://posthog.com/blog/sunsetting-helm-support-posthog#:~:text=Finally%2C%20there%20will,back%20where%20necessary.

Which implies that there will no longer be any numbered releases to Posthog, and that the main branch is where stable updates are released from now on?

**Comment by tomasfarias** [comment]
> Which implies that there will no longer be any numbered releases to Posthog, and that the main branch is where stable updates are released from now on?

Precisely. Thanks for raising this up, as this means that the `deploy-hobby` script should be `latest` by default instead of `latest-release`. I'll check with the team just to be sure and push out a change.

**Comment by vikram-ray** [comment]
I tried one more approach to install Posthog and it worked. 

Instead of going back to the previous commit, we can use default script - `/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/posthog/posthog/HEAD/bin/deploy-hobby)"
` and during installation, it asks for posthog version. 

We can type [release-1.43.0](https://hub.docker.com/layers/posthog/posthog/release-1.43.0/images/sha256-3a50334c8c8fe75df7055f55085214198e359bc0b70adacd1f0b936a778f5b7c?context=explore) and it works just fine. Later we can upgrade it.

**Comment by fibis** [comment]
After the implemented fix (#14956), it was possible to install Post Hog.

**Comment by HamzaMateen** [comment]
Thanks @vikram-ray 
Yours is the simplest solution that solved the problem like a breeze.

**Comment by iltafah** [comment]
> I tried one more approach to install Posthog and it worked.
> 
> Instead of going back to the previous commit, we can use default script - `/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/posthog/posthog/HEAD/bin/deploy-hobby)" ` and during installation, it asks for posthog version.
> 
> We can type [release-1.43.0](https://hub.docker.com/layers/posthog/posthog/release-1.43.0/images/sha256-3a50334c8c8fe75df7055f55085214198e359bc0b70adacd1f0b936a778f5b7c?context=explore) and it works just fine. Later we can upgrade it.

That's did it, I think the best solution in those cases whenever trying to install a new tool locally is to install the last stable release, never ever work with the latest version unless there is reason for that.
