### ISSUE TITLE
Updating Series filter not persisting

### ISSUE THREAD

**Issue by joepavitt** [PostHog/posthog#14863]
## Bug description

Trying to update a filter property (Current URL) for a series in a trend graph. I change it, upon changing, and saving, when refreshing, it reverts back to the old version. This happens for any of the series in this insight.

Insight in Question: https://eu.posthog.com/insights/8s7gXHxn/edit

https://user-images.githubusercontent.com/99246719/226957591-f9d13129-8442-4d8b-a96b-3c29c72562ef.mov

## How to reproduce

1. Go to an existing Trend Insight
2. Update a filter for a Series
3. Save
4. Refresh - note that the change reverts

## Environment

- [x] PostHog Cloud EU, project ID: 2209

**Comment by joepavitt** [comment]
I have also noticed that PostHog Eu is being particularly temperamental today, having to refresh the Dashboard a lot as keep getting errors, and slow response, so not sure if that's also a factor?

**Comment by pauldambra** [comment]
Hey, @joepavitt 👋  it looks like you type in the box and then click on the white area to the right.

The filters don't update on blur. You have to press enter or select the "specify: x" below it.

(It's super frustrating for us and something we're aiming to change)

**Comment by joepavitt** [comment]
It certainly is frustrating, and is still requiring a couple of <enter> presses in order for it to stick. The click for the "Specify" does work consistently though - thanks.

**Comment by Twixes** [comment]
This is now solved, as we've switched to a homegrown input component. :)
