### ISSUE TITLE
Issues with recordings sessions and server errors are hindering our ability to analyze user behavior.

### ISSUE THREAD

**Issue by Artiom8888** [PostHog/posthog#14889]
Dear PostHog Support Team,

We are writing to report an issue that we've been experiencing with viewing recording sessions on your platform. Specifically, we've noticed that the some recorded video is unsuitable for viewing and analysis due to the following reasons:

1. When viewing the video recording of the session, we've noticed that the initial recording of one of the tabs of our application does not disappear, but instead is superimposed on the recording of other application tabs. This makes it difficult for us to analyze the user's journey and behavior accurately.

![image](https://user-images.githubusercontent.com/47413720/227474432-de23af01-d931-4ab4-a120-d4a70bc85067.png)

https://app.posthog.com/recordings/recent?filters=%7B%22session_recording_duration%22%3A%7B%22operator%22%3A%22gt%22%2C%22value%22%3A1%2C%22type%22%3A%22recording%22%2C%22key%22%3A%22duration%22%7D%2C%22properties%22%3A%5B%5D%2C%22events%22%3A%5B%5D%2C%22actions%22%3A%5B%5D%2C%22date_from%22%3A%22-21d%22%7D#sessionRecordingId=18710116ec616b-06dcb84fa88087-16462c6c-ff000-18710116ec747a

Recordings Settings: 
![Screenshot at 2023-03-24 10-52-57](https://user-images.githubusercontent.com/47413720/227471471-dbb5e933-2e64-44b7-ae72-0b26ed017d08.png)

NPM package: "posthog-js": "^1.51.5"

Environment:
- [ ] PostHog Cloud US, project ID: 6644

2. In addition to the above issue, we've also encountered instances where some of the records cannot be viewed, and an error message is displayed: 
"Failed to load events: A server error occurred." 
This has been a significant hindrance to our analysis efforts.
![Screenshot at 2023-03-23 23-05-00](https://user-images.githubusercontent.com/47413720/227469208-243e2895-a526-462a-886b-99f26ec1945d.png)

![Screenshot at 2023-03-23 23-02-13](https://user-images.githubusercontent.com/47413720/227469113-64357991-99c3-4971-acd3-bee809e4e201.png)
https://app.posthog.com/recordings/recent?filters=%7B%22session_recording_duration%22%3A%7B%22operator%22%3A%22gt%22%2C%22value%22%3A1%2C%22type%22%3A%22recording%22%2C%22key%22%3A%22duration%22%7D%2C%22properties%22%3A%5B%5D%2C%22events%22%3A%5B%5D%2C%22actions%22%3A%5B%5D%2C%22date_from%22%3A%22-21d%22%7D#sessionRecordingId=187101b068b838-0eb679a1c1532b-16462c6c-1fa400-187101b068c97e
       
We understand the importance of session recording and analysis for improving user experience, and we appreciate the efforts of the PostHog team to provide a robust and reliable platform for these purposes. We would appreciate any assistance you can provide to help us resolve these issues and ensure that our analysis efforts are not hindered.

Thank you for your attention to this matter.

Best Regards,
Artiom Romarniuc

**Comment by benjackwhite** [comment]
Hello. Thanks for the report. Can you perhaps share some extra info to help us debug:

1. What are you expecting to see (perhaps do a quick screen recording of your application)
2. What that looks like as a recording
3. If possible a link to the page in question that we can look at to try and see what is going wrong.

As I don't know your web app it is hard to say what is "wrong" without that context - hope that makes sense.

**Comment by Artiom8888** [comment]
Hello,

Thank you for getting back to us. We appreciate your prompt response.

1. **We are expecting to see the behavior shown in this screen recording:**

https://user-images.githubusercontent.com/47413720/227495882-b1524a17-a074-4b46-8b54-a35bfdc3f5ba.mp4

2. **However, some recordings are not working correctly, and we are seeing the issue of overlapping tabs, as shown in these recordings:**

https://user-images.githubusercontent.com/47413720/227496105-5c38f960-c7db-444e-99c7-d1cbbda114c5.mp4

https://user-images.githubusercontent.com/47413720/227496167-be1670be-3e2e-4ef5-a816-49eaf557a76c.mp4

3. **We have also included links to the pages in question that we are experiencing issues with:**

https://app.posthog.com/recordings/recent?filters=%7B%22session_recording_duration%22%3A%7B%22operator%22%3A%22gt%22%2C%22value%22%3A1%2C%22type%22%3A%22recording%22%2C%22key%22%3A%22duration%22%7D%2C%22properties%22%3A%5B%5D%2C%22events%22%3A%5B%5D%2C%22actions%22%3A%5B%5D%2C%22date_from%22%3A%22-21d%22%7D#sessionRecordingId=18710116ec616b-06dcb84fa88087-16462c6c-ff000-18710116ec747a

https://app.posthog.com/recordings/recent?filters=%7B%22session_recording_duration%22%3A%7B%22operator%22%3A%22gt%22%2C%22value%22%3A1%2C%22type%22%3A%22recording%22%2C%22key%22%3A%22duration%22%7D%2C%22properties%22%3A%5B%5D%2C%22events%22%3A%5B%5D%2C%22actions%22%3A%5B%5D%2C%22date_from%22%3A%22-21d%22%7D#sessionRecordingId=187101b068b838-0eb679a1c1532b-16462c6c-1fa400-187101b068c97e


Thank you for your attention to this matter. We look forward to hearing back from you soon.

Best regards,
Artiom Romarniuc

**Comment by Artiom8888** [comment]
Dear Posthog Support Team,

I am writing to report two more issues I have encountered when viewing recordings in Posthog.

Firstly, when playing the recording available at the following link: [https://app.posthog.com/person/5ed0df3f84083c0c12ed31ad?filters=%7B%22session_record[…]5D%2C%22actions%22%3A%5B%5D%2C%22date_from%22%3A%22-21d%22%7D](https://app.posthog.com/person/5ed0df3f84083c0c12ed31ad?filters=%7B%22session_recording_duration%22%3A%7B%22type%22%3A%22recording%22%2C%22key%22%3A%22duration%22%2C%22value%22%3A60%2C%22operator%22%3A%22gt%22%7D%2C%22properties%22%3A%5B%5D%2C%22events%22%3A%5B%5D%2C%22actions%22%3A%5B%5D%2C%22date_from%22%3A%22-21d%22%7D#activeTab=sessionRecordings&sessionRecordingId=187289c0a4c7fa-08c137e64ef7fc-16462c6c-ff000-187289c0a4d820), a white screen is displayed while events continue to run. Although I have managed to watch the video at times by going through other tabs and then returning to it, the white screen issue persists.

Secondly, when viewing the recording available at the following link: [https://app.posthog.com/person/5ed0df3f84083c0c12ed31ad?filters=%7B%22session_record[…]5D%2C%22actions%22%3A%5B%5D%2C%22date_from%22%3A%22-21d%22%7D](https://app.posthog.com/person/5ed0df3f84083c0c12ed31ad?filters=%7B%22session_recording_duration%22%3A%7B%22type%22%3A%22recording%22%2C%22key%22%3A%22duration%22%2C%22value%22%3A60%2C%22operator%22%3A%22gt%22%7D%2C%22properties%22%3A%5B%5D%2C%22events%22%3A%5B%5D%2C%22actions%22%3A%5B%5D%2C%22date_from%22%3A%22-21d%22%7D#activeTab=sessionRecordings&sessionRecordingId=187287db8124a0-0348eca062253f-16462c6c-ff000-187287db813823), the "Experts" tab appears not to load, but in reality, the loader does not work for a long time, and the "Experts" tab eventually loads. This error in the video recording misleads us when analyzing our clients' records.

I would appreciate it if you could investigate these issues and resolve them as they affect the quality of our analysis.

Thank you for your attention to this matter.

Best regards,
Romarniuc Artiom

**Comment by pauldambra** [comment]
We've changed recordings so much since this was logged I'm going to close it, sorry you didn't have a response sooner. If you're still experiencing issues do let us know.
