### ISSUE TITLE
Bug: Feature flag cohort exclusion not working as expected

### ISSUE THREAD

**Issue by lharries** [PostHog/posthog#14895]
(not urgent from my side, prioritize as you want)

When I have the following cohort I'd expect to not be in the feature flag:
<https://app.posthog.com/feature_flags/8734>

However I still see the notebook button. (If I turn off the flag then the notebook button is removed however)

This error persists when I'm in incognito too

Let me know if you'd prefer these at github issues etc. in future

[Slack Message](https://posthog.slack.com/archives/C046D7C654H/p1679664842446459?thread_ts=1679664842.446459&cid=C046D7C654H)

![image](https://user-images.githubusercontent.com/22766134/227539111-00ee48c6-e6d3-47e4-8a96-647ede76d062.png)

**Comment by neilkakkar** [comment]
Refresh? It's disabled for you based on what I'm seeing; and replicating suggests the same for me 🤔 .
