### ISSUE TITLE
Coloured series in query summary

### ISSUE THREAD

**Issue by thmsobrmlr** [PostHog/posthog#14912]
## Is your feature request related to a problem?

> Hey PostHog team: here’s a quick UX suggestion.
When editing a series, PostHog indicates each series with a coloured letter (A), (B), etc., which is super handy to determine what is what on the chart.

- https://posthog.slack.com/archives/C04R96TUZDE/p1679681620736459 (no further context here)

## Describe the solution you'd like

It would be nice if this colour coding would persist in the “Query summary” view that is shown when you click the “Show details” button on a chart shown in a dashboard.

<img width="686" alt="Screenshot 2023-03-24 at 18 09 07" src="https://user-images.githubusercontent.com/1851359/228327454-8918560a-8be7-46a7-b20a-1a0c66e3da5f.png">
<img width="661" alt="Screenshot 2023-03-24 at 18 09 32" src="https://user-images.githubusercontent.com/1851359/228327459-4d4a50d6-9b78-42e9-b934-7789c5092cc7.png">

**Comment by Powell-v2** [comment]
Hey there, I could take this on next week if no one else is already working on it : )

**Comment by thmsobrmlr** [comment]
Hey @Powell-v2! It looks like there's already a PR for this (see above your comment). I'll have a look at that later today. Probably best to pick another issue from https://github.com/PostHog/posthog/labels/good%20first%20issue

**Comment by Powell-v2** [comment]
I see. Sure thing, thanks for letting me know!

**Comment by thmsobrmlr** [comment]
Solved in https://github.com/PostHog/posthog/pull/17102. Thanks @ReeceGao !
