### ISSUE TITLE
Celery preflight check fail with latest version + NGINX proxy

### ISSUE THREAD

**Issue by pavitrakumar78** [PostHog/posthog#14925]
## Bug description

I'm trying to run a clean install of posthog on a subdomain: posthog.mywebsite.com.

What works:
1. Clean installation as per instructions in this post: https://github.com/PostHog/posthog/issues/14910#issuecomment-1488958867

What does not work:
1. Celery pre-check fails when launching the posthog subdomain website.

## How to reproduce

1. Clone the PostHog repo: git clone https://github.com/PostHog/posthog posthog
2. Edit the posthog/docker-compose.base.yml file: add TRUST_ALL_PROXIES='true' to the worker environment right after IS_BEHIND_PROXY='true' in the service spec.
3. Edit the posthog/docker-compose.hobby.yml file: get rid of the Caddy service
4. Edit the posthog/docker-compose.hobby.yml file: expose ports 8000:8000 in web service. 
5. Install Nginx and configure a server 
6. Run deploy-hobby for the latest PostHog version.

## Environment

- [x] PostHog Hobby self-hosted with `docker compose`, version/commit: [please provide]

## Additional context

All the docker container starts normally.

Logs from worker:
![image](https://user-images.githubusercontent.com/5354407/228642647-c9cfa687-9e09-49f0-bb36-9b070456f8cc.png)

Specific to celery:
![image](https://user-images.githubusercontent.com/5354407/228642669-5557b457-435f-4167-b913-a099efc41533.png)

When viewing website:
https://user-images.githubusercontent.com/5354407/228639753-583af0e1-1806-4d84-981f-163d9f0bb53e.png

I've tried restarting using `docker-compose restart` - still the same issue. 

Any suggestions I can try?

**Comment by tomasfarias** [comment]
Celery can be a bit flaky, we notice it sometimes in dev environments. Have you tried restarting the worker service a few times? Just to try an easy solution: `docker-compose restart worker`

"The group is rebalancing" error logs are normal: It's part of the normal Kafka workflow to rebalance every once in a while. `kafkajs` handles that as a temporary error/warning, so it's safe to ignore.

**Comment by pavitrakumar78** [comment]
Yep - got it. Had to restart it 3-4 times and wait.
Thank you for all the help!

**Comment by funnelcloudservices** [comment]
#Just to try an easy solution: docker-compose restart worker
This needs to be in the FAQ or documentation.  I tried six or seven builds from scratch thinking I was doing something wrong.
