### ISSUE TITLE
Automatically create user & use posthog-production for heroku test envs

### ISSUE THREAD

**Issue by timgl** [PostHog/posthog#1495]
## Is your feature request related to a problem?

- [x] I want to test our production env when using the review envs
- [x] I don't want to have to create a user

## Describe the solution you'd like

- [x] Run test deployments using a production environment.
- [x] Automatically create a new user, load in user data, skip the setup.

**Comment by Twixes** [comment]
So automatic user creation is now functioning, but it's still a DEBUG environment. To do: instead of DEBUG run a production-like setup.

**Comment by Twixes** [comment]
We aren't running PostHog Cloud in review at the moment, but that's a separate thing in my opinion. Otherwise all good.
