### ISSUE TITLE
2FA token field should not be type=number

### ISSUE THREAD

**Issue by hmnd** [PostHog/posthog#14955]
## Bug description
The 2FA input field currently has type=number on it, so stepper arrows are shown next to it. This is not intuitive for a 2FA code that will always consist of random digits.

![image](https://user-images.githubusercontent.com/12853597/229328658-27063df5-f84a-4483-b63b-931be0ab72ac.png)

## How to reproduce

1. Set up 2FA on an account
2. Login in

## Environment

- [x] PostHog Cloud US, project ID: [please provide from https://app.posthog.com/project/settings#project-id]
- [ ] PostHog Cloud EU, project ID: [please provide from https://eu.posthog.com/project/settings#project-id]
- [ ] PostHog Hobby self-hosted with `docker compose`, version/commit: [please provide]
- [ ] PostHog self-hosted with Kubernetes (deprecated, see ["Sunsetting Kubernetes support"](https://posthog.com/blog/sunsetting-helm-support-posthog)), version/commit: [please provide]

**Comment by ghost** [comment]
I don't think its a bug.

**Comment by hmnd** [comment]
@iSatVeerSingh `<input type="number">` should only be used when the expected value is truly _a number_ and not just a set of characters that are numerical. For non-number numerical values such as a 2FA token, _[inputmode="numeric" along with a pattern](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/number#accessibility)_ should be used instead.

**Comment by Twixes** [comment]
That absolutely is a very good point @hmnd, it's now resolved.
