### ISSUE TITLE
Scaling of space too high ( >25 GB growth in 5 days )

### ISSUE THREAD

**Issue by pavitrakumar78** [PostHog/posthog#14965]
## In what situation are you experiencing subpar performance?

A fast increase in usage of storage. 
`docker system df -v` returns the following:

![image](https://user-images.githubusercontent.com/5354407/229587916-0b6f3d80-bd30-49f7-83fd-f866e530d6e6.png)

I'm not sure if this is expected since I barely have ~100k events since I set up the self-hosted solution.

from `/instance/status`:
![image](https://user-images.githubusercontent.com/5354407/229588335-5e31fef0-e4c8-4f3c-a39d-d0ad5a010259.png)

![image](https://user-images.githubusercontent.com/5354407/229588368-5324814c-b01a-4d03-a806-8ddccfa86aa9.png)

What is causing this rapid increase in the usage of space? How can I reduce this?

## How to reproduce

1. Same steps as in the introduction for installing the self-hosted version
2. No additional setups/settings 

## Environment

- [x] self-hosted PostHog, version/commit: latest

**Comment by liyiy** [comment]
Hi there! Thanks for the bug report. Just a heads up that we're sunsetting support for self hosted deploys, check out this article here https://posthog.com/blog/sunsetting-helm-support-posthog

**Comment by pavitrakumar78** [comment]
@liyiy 
> Sunsetting **Kubernetes** support for PostHog
> This decision doesn't impact open source users on Docker Compose deployments (also known as the "hobby" deployment).

Am I missing something?

**Comment by frankh** [comment]
Looks like most of the space is being taken up by zookeeper snapshots - if you set the `ZOO_AUTOPURGE_PURGEINTERVAL=12` environment variable on the zookeeper pod that should keep it under control. We should probably add this as a default to the docker-compose too

**Comment by pavitrakumar78** [comment]
@frankh Thank you for the suggestion! I will try this and report back.

**Comment by pavitrakumar78** [comment]
@frankh It has been 8 hrs + and I still don't see any change in the size. Is there any way to check if the purge has been done?

![image](https://user-images.githubusercontent.com/5354407/230374247-e0c6581b-d53b-477e-99f0-8883f51c6b55.png)

![image](https://user-images.githubusercontent.com/5354407/230348566-f28c1233-6aca-488c-b724-88b3e874a050.png)


![image](https://user-images.githubusercontent.com/5354407/230348594-54ebc260-a3d5-4597-826c-9cae4a9e7e99.png)


![image](https://user-images.githubusercontent.com/5354407/230348777-23f9cebc-e4fe-4ae6-bdc6-71f4f562ce35.png)

**Comment by frankh** [comment]
You should be able to force the cleanup by running `docker exec miscdataservices-zookeeper-1 ./bin/zkCleanup.sh -n 3`

If that doesn't work, it might be worth just nuking the volume, 

```
docker rm -f miscdataservices-zookeeper-1
docker volume rm miscdataservices_zookeeper-datalog
```

then re starting the docker-compose.

I do find it very strange that it's managed to use 26GB though, afaik no real data is stored in zookeeper, if storage re-fills up at the same rate something weird must be happening

**Comment by pavitrakumar78** [comment]
> You should be able to force the cleanup by running docker exec miscdataservices-zookeeper-1 ./bin/zkCleanup.sh -n 3

This worked. I'm just adding this to the crontab for now.

> I do find it very strange that it's managed to use 26GB though, afaik no real data is stored in zookeeper, if storage re-fills up at the same rate something weird must be happening

If there is anything I can provide access to like the instance or logs please let me know.

Here's the size growth trend over the last 1 week:
![image](https://user-images.githubusercontent.com/5354407/230426683-c8ca3ee6-739a-4c77-a3e6-c7d40c90a491.png)

After executing clean up command:

![image](https://user-images.githubusercontent.com/5354407/230427077-83b1c769-c340-4597-8721-9c4a72ea50fb.png)


Kafka instance at 30gb+ is normal? I thought only increase I should be seeing is clickhouse and postgres.

Edit: I'm still not seeing the free space available to use after the clear command. I see that the size has reduced in docker df command, but it's still not available to the OS.

**Comment by pavitrakumar78** [comment]
(Sorry for the double post)

I tried deleting the zookeeper vol based on your suggestion, but now it somehow broke kafka I think...
![image](https://user-images.githubusercontent.com/5354407/230433415-d731eaed-17eb-4d0d-b517-d3d90a3908ac.png)

Not able to launch instance website anymore 

Edit:

`docker-compose restart` exits without errors, when website is visited I get a bad gateway error
`docker-compose up` works 

~~How can we fix this so I can run with just docker-compose restart?~~

All ok after restarting a couple of times. 

Finally I just want to understand if the kafka container size ~38GB now is normal?

**Comment by pavitrakumar78** [comment]
Update after almost 7 weeks of usage:

![image](https://github.com/PostHog/posthog/assets/5354407/a792fc3d-b51f-4daf-bda4-802ddaedc396)

Total disk usage now at ~120 GB+ 

![image](https://github.com/PostHog/posthog/assets/5354407/e03f4029-26eb-4c2d-a235-3b88c80d48bc)

![image](https://github.com/PostHog/posthog/assets/5354407/40aef19a-1486-49d4-a9c2-8e91bfb58dab)

Few questions:
1. Is this growth normal?
2. `sharded_session_recording_events` is at ~45 GB right now - this is related to `RECORDINGS_TTL_WEEKS` - correct? and this should stay constant if the no.of recordings per 3 weeks is also fixed right? i.e there should not be a growth there as recordings sessions get deleted every 3 weeks (am I understanding this correctly?)
3. Are recordings part of `miscdataservices-kafka-1` container?
4. `miscdataservices_clickhouse-data`  contains the normal non-recording data that is expected to grow over time - correct?


Any help/clarification on these would be really appreciated!

**Comment by pavitrakumar78** [comment]
Solved. 
need to edit kafka's settings in the kafka container to restrict the log files. 
`vim server.properties`
modify the log.retention.ms or log.retention.bytes
