### ISSUE TITLE
persist showing legend on pie charts

### ISSUE THREAD

**Issue by jamesefhawkins** [PostHog/posthog#14964]
## Bug description

*Please describe.*  
*If this affects the front-end, screenshots would be of great help.*  

If I choose 'show legend' here then save insight, it should continue to show legend.

<img width="213" alt="Screenshot 2023-04-03 at 18 50 38" src="https://user-images.githubusercontent.com/47497682/229588003-3f973c7f-f6af-41d8-ba0a-435b850b50ac.png">

*If you are on PostHog Cloud it would be really valuable if you can share any links where the problem occurs. This speeds up our ability to troubleshoot tremendously.* 

## How to reproduce

1. create pie chart
2. click show legend
3. save and refresh
4. legend is gone

## Environment

- [x] PostHog Cloud US, project ID: [please provide from https://app.posthog.com/project/settings#project-id]
- [ ] PostHog Cloud EU, project ID: [please provide from https://eu.posthog.com/project/settings#project-id]
- [ ] PostHog Hobby self-hosted with `docker compose`, version/commit: [please provide]
- [ ] PostHog self-hosted with Kubernetes (deprecated, see ["Sunsetting Kubernetes support"](https://posthog.com/blog/sunsetting-helm-support-posthog)), version/commit: [please provide]

**Comment by Twixes** [comment]
This is done now.
