### ISSUE TITLE
Make it easier to compare a specific week day, month of the year with a previous instance

### ISSUE THREAD

**Issue by lsmith77** [PostHog/posthog#14991]
## Is your feature request related to a problem?

Currently it is possible to `Compare to previous time period`, ie. I can compare Tuesday to Monday, November to October etc.

<img width="216" alt="image" src="https://user-images.githubusercontent.com/300279/230138762-5756a125-712e-456d-931f-92b7d2f21a6f.png">

However there are also cases where I want to compare Tuesday to last weeks Tuesday etc.

## Describe the solution you'd like

Add a way to choose the exact time period to compare with.

Change the checkbox `Compare to previous time period` to `Compare to previous` + Dropdown.

In the dropdown list (for a day aggregation) `yesterday`, `last week`, `last month`, `last year`.

## Describe alternatives you've considered

Change the checkbox `Compare to previous time period` to `Compare to previous` + Dropdown. In the dropdown list `time period`, `XYZ` .. I am not sure what XYZ should be .. maybe `instance` ?

## Additional context

https://posthogusers.slack.com/archives/C01GLBKHKQT/p1680521720404399

**Comment by xolf** [comment]
@mariusandra let me ask an awful question from developer perspective: Is there an ETA for this?

Currently this keeps us from moving our own InfluxDB + Grafana stack to PostHog.

**Comment by mariusandra** [comment]
Hey @xolf ... "Q1" is the most accuracy I can give at the moment sadly. I'm not sure if that's good enough 🙃 

You can follow along as we tick off the checkboxes in this meta issue: https://github.com/PostHog/meta/issues/130

Our [team's focus for next sprint](https://github.com/PostHog/posthog/issues/19804#issuecomment-1895401054) is to get these new queries out to actual users... and we can start adding the new features after that.

However, if you need one-off analysis, you can also enable the "Business Intelligence" feature preview today, which lets you chart any SQL query in PostHog. It's a bit more work to set up, but you can already get the data if you want.
