### ISSUE TITLE
New to posthog. Is the data queryable?

### ISSUE THREAD

**Issue by steven4354** [PostHog/posthog#15004]
## Is your feature request related to a problem?

Hi, I'm new to posthog and I was wondering if the data is queryable in posthog? Where is the data stored on posthog?

Thank you

*Please describe.*

**Comment by steven4354** [comment]
I see the docker uses postgres, are all the user clicks, search and items auto stored in postgres?

**Comment by Twixes** [comment]
Hi Steven! PostHog data is stored in ClickHouse, an analytics database management system (not Postgres, as it's slow for analytics purposes). Most of our features query this data at their core. As for direct querying, we'll soon be offering SQL access as well. Hope this helps.
By the way, https://posthog.com/questions is usually the place for questions like this one (GitHub is primarily for bugs and feature requests), so I'll close the issue.
