### ISSUE TITLE
Sprint April 17 to April 28

### ISSUE THREAD

**Issue by timgl** [PostHog/posthog#15043]
# Global Sprint Planning

## 3 things that might take us down

1. Not being able to scale clickhouse or kafka
2. We're at the limit of how many session recordings we can process (sprint goal for pipeline)
3. security of hogql (doing a pen test this week)

## Retro: What can we do better next sprint?

1. A lot of ambiguity on what we're working on
2. Persons on Events v2 doesn't have a clear owner. Some ambiguity on how the intra team collaboration here works

## Support hero this sprint

Week 1: Tim Glaser
Week 2:

# Team sprint planning

For your team sprint planning copy this template into a comment below for each team.

```
# Team ___

## Retro

<!-- Grab the high and low priority items from last time and add whether that item was completed or not -->

- 

## Hang over items from previous sprint

<!-- For each item, decide to re-prioritise (and add below) or deprioritise -->

- Item 1. prioritised/deprioritise

## OKR

1. OKR, status (red/yellow/green) and action points if yellow/red


### High priority

-

### Low priority / side quests

-

```

**Comment by Twixes** [comment]
Team Product Analytics

## Retro

- Persons on Events v2: Most insight types ready, some Trends quirks left.
   This sprint communication between teams (primarily Product Analytics and Pipeline) has slowed things down a bit. Yakko to take broader ownership over shipping PoE v2.
- HogQL is in beta!

## Hang over items from previous sprint

Nothing in particular.

## OKR

_Gonna skip goal status as it's the first sprint of the quarter._

### High priority

- Persons on Events v2 ready for rollout (all insight types ready, communication shipped, decision on backfill made) @yakkomajuri 
- PostHog 3000 insight editor rolled out internally @Twixes (with @thmsobrmlr)

### Low priority / side quests

- HogQL improvements @mariusandra
- Fully releasing insights based on the Data Exploration API (refer to https://github.com/PostHog/meta/issues/84) @thmsobrmlr

**Comment by raquelmsmith** [comment]
# Team Growth

## Retro



- Billing by products
  - This has taken longer than anticipated, came down to the wire with em leaving. Not much to change here though.

## Hang over items from previous sprint

- N/A

## OKR

1. Put all products on equal footing 🟡 
    - Billing by products 🟢 
    - Changing onboarding to feel less analytics-focused ⚪  
2. Product-specific onboarding ⚪ 
    - Tooling and frameworks ⚪ 


### High priority

- Responding to issues with the new billing-by-products launch @raquelmsmith @charlottemcginn 
- Move usage reports to Temporal @charlottemcginn (with support from @fuziontech)
- Make platform features more understandable/visible in billing-by-products UI @raquelmsmith 
- Demo data generation OOM fix @charlottemcginn 

### Low priority / side quests

- Maybe? Max AI / support request via chat interface @raquelmsmith (if we want that interface instead of @tiina303's form)

**Comment by neilkakkar** [comment]
## Team Feature Success

### Retro

Winding up things that fell through the cracks during Q1 & KTLO

Sub-goals:

Feature flags UI code examples windup - @liyiy  
Payload docs - @liyiy
Resiliency wrap up @neilkakkar
flags when impersonating @neilkakkar
Recordings on flags intent: @EDsCODE

All sorted except resiliency, we're waiting for a pgbouncer read-replica from infra to continue on this.

Stretch:
Server-side libs: $geoip_disable by default, automatic flags on all events when possible. - currently ongoing, @liyiy is working on this
Ignore geoIP computed properties when computing flags using server-side libs

---



### Sprint goals

1. Release Beta management to 5 happy users - [Eric Duong](mailto:eric@posthog.com)
Why? Closing loops from hackathon. Gauge user interest in features.

Stretch:
2. Dashboard templates on feature flag tab - [Neil Kakkar](mailto:neil@posthog.com)

**Comment by tiina303** [comment]
# Team Pipeline

## Goals

1. Ingestion PoE columns always properly set @tiina303 
  - we currently see empty personIDs and I suspect person or group properties might be not set properly too
  - co-working with Yakko to get the query side out fully for anyone on PoEv1
  - squash job running in prod
2. ClickHouse Infa side watering @fuziontech 
  - US scale-up + read-only users + test recovery
  - potentially don't want to have 8 shards
  - @lharries  will hook HogQL up with the read-only user from here
  - will collaborate with infra here
3. session recordings scalability @xvello  with @hazzadous 
  - autoscaling on kafka lag with KEDA
  - Switch the kafka producer & consumer to librdkafka
  - We’re doing this work on the recordings consumer first, but this work should be transferable to analytics too
repartition
4. batch exports to S3 @tomasfarias with @lharries 
  - for frontend (stretch doing the event streaming UI too when the backend is ready)

**Comment by benjackwhite** [comment]
# Team ~Recordings~ Monitoring

## Retro



- Sickness, holiday and support hero 😓 

## Hang over items from previous sprint



- New ingestion flow...

## OKR

1. OKR, status (red/yellow/green) and action points if yellow/red


### High priority

- Get new recording ingestion flow up and running @benjackwhite 
- Scope out Notebooks, Errors, Automation...

### Low priority / side quests

- Enable the new rrweb version for new teams
- Rename team to "Monitoring" and product to "Replay"

**Comment by danielxnj** [comment]
# Team Infra

## Retro



- Holidays
- Dev env now private
- Communication to set Header for reverse proxy was sent to customers
- Finalized SOC2

## Hang over items from previous sprint




## OKR

1. OKR, status (red/yellow/green) and action points if yellow/red
- Switch over Postgres
- Cloud Cost reduction
- CLichouse migration

### High priority

- Switchover Postgres from EC2 instance to Aurora Cluster
- Enable Cloudfront in US Production
- Infra Hero @danielxnj
