### ISSUE TITLE
Snowflake connector

### ISSUE THREAD

**Issue by timgl** [PostHog/posthog#1505]
## Is your feature request related to a problem?

I want to be able to push my data from PostHog into Snowflake.

## Describe the solution you'd like

A connector/integration that can push my data to my Snowflake instance

## Describe alternatives you've considered

-

**Comment by yakkomajuri** [comment]
Just had a call with someone else asking for this

**Comment by paolodamico** [comment]
Another paying user just asked for this

**Comment by timgl** [comment]
Closing in favour of https://github.com/PostHog/plugin-repository/issues/13
