### ISSUE TITLE
how to get minimal Posthog footprint - to only capture events

### ISSUE THREAD

**Issue by anisg** [PostHog/posthog#15068]
Developing a Chrome extension, I need only to use Posthog to capture events. Bundle of Posthog is 100kb by default which is a bit too much. How can I reduce the bundle size?

**Comment by benjackwhite** [comment]
We have https://github.com/posthog/posthog-js-lite which is potentially more lightweight. 

Alternatively if you are _really_ just capturing events and not taking advantage of any of the other functions, then you can always just make your own API calls.
