### ISSUE TITLE
Highlight unique PostHog features

### ISSUE THREAD

**Issue by Rihem-taboubi** [PostHog/posthog#15072]
## Is your feature request related to a problem?

*Please describe.*

## Describe the solution you'd like
PostHog offers  a lot of  features that are different from other analytical platforms

## Describe alternatives you've considered
Highlighting them will make the website more clear for the target users

**Comment by benjackwhite** [comment]
Hello 👋  thanks for creating an issue but we need much more detail than this. I'm going to close but feel free to re-open with more context if you have it.
