### ISSUE TITLE
Bug: Typo in Cohort operators

### ISSUE THREAD

**Issue by joethreepwood** [PostHog/posthog#15096]
## Bug description
<img width="433" alt="Screenshot 2023-04-14 at 14 52 46" src="https://user-images.githubusercontent.com/84011561/232063302-b8bfeddc-cc8a-4419-8f4b-98f9ff2e3699.png">

The most minor of typos, but `contain` needs an `s` at the end to be consistent and to parse well. 

Had a look, but it wasn't immediately obvious how/where to fix this. 

## How to reproduce

1.
2.
3.

## Environment

- [ ] PostHog Cloud US, project ID: [please provide from https://app.posthog.com/project/settings#project-id]
- [ ] PostHog Cloud EU, project ID: [please provide from https://eu.posthog.com/project/settings#project-id]
- [ ] PostHog Hobby self-hosted with `docker compose`, version/commit: [please provide]
- [ ] PostHog self-hosted with Kubernetes (deprecated, see ["Sunsetting Kubernetes support"](https://posthog.com/blog/sunsetting-helm-support-posthog)), version/commit: [please provide]

**Comment by haszankauna** [comment]
hello @joethreepwood  can I please be assigned this task?

**Comment by joethreepwood** [comment]
Sure - contributions welcome!
