### ISSUE TITLE
Allow filtering of recordings based on console logs

### ISSUE THREAD

**Issue by benjackwhite** [PostHog/posthog#15103]
## Is your feature request related to a problem?

It would be great to filter recordings based the content of console logs in the recording

## Describe the solution you'd like

Additional filters for example to choose logs and filter on their 
* log level
* log content

We could extract the simple log data into the `events_summary` column (if we haven't already) and then query on it there.

## Describe alternatives you've considered

Much bigger scope but... move console logs into their own storage location... That way we could query on them _in general_ and not just for Recordings 🤔 . This might be waaaayyy out of scope but would be pretty cool as a standalone product area.

**Comment by pauldambra** [comment]
You can now filter by log level, but not (yet) by content...
