### ISSUE TITLE
Add timestamp to "View recording" link in the event explorer

### ISSUE THREAD

**Issue by lharries** [PostHog/posthog#15111]
Clicking view a recording on an event doesn't add the timestamp link which is often useful for jumping to the relevant place in long recordings

Example: debugging and wanting to jump to a specific place of a session recording. You create a table of events of interesting actions, and then want to jump to the recording of one of them

**Comment by lharries** [comment]
<img width="577" alt="Screenshot Threads - PostHog - 20 new items - Slack (Slack) 2023-04-17 at 14 55@2x" src="https://user-images.githubusercontent.com/22766134/232505492-ff46206d-0637-4219-8c5d-7d1d60cb4282.png">

**Comment by lharries** [comment]
@benjackwhite unclear to me why "Better would be to add support for specifying an absolute timestamp when opening a recording so that it starts from their instead of the relative time" would be better

**Comment by benjackwhite** [comment]
It's the same thing, its just that instead of having to encode the position into every captured event e.g. "session_recording_time: 20", we can just do `/session-recordings/:id?timestamp={event.timestamp}` and then do that calculation at playback time.

**Comment by lharries** [comment]
Got you! Does event.timestamp work already?
