### ISSUE TITLE
HogQL - toTimezone function errors out 

### ISSUE THREAD

**Issue by benjackwhite** [PostHog/posthog#15122]
## Bug description

1. `toTimezone` vs `toTimeZone` in Clickhouse. Did we purposefully choose the lowercase version?
2. When I use it I get the following Sentry error https://posthog.sentry.io/issues/4103759071/?project=1899813&referrer=slack

Query that triggers this:

```
 select count(distinct session_id),
          toStartOfDay (toTimezone (timestamp, 'utc')) as date
     from session_recording_events
    where timestamp > now() - interval 21 day
 group by date
 order by date desc
    limit 100
```

Without the `toTimezone` call it works fine. With it it causes [this Sentry error](https://posthog.sentry.io/issues/4103759071/?project=1899813&referrer=slack)

## How to reproduce

1. [Run that query in PostHog](https://app.posthog.com/debug#q=%7B%0A%20%20%22kind%22%3A%20%22DataTableNode%22%2C%0A%20%20%22full%22%3A%20true%2C%0A%20%20%22source%22%3A%20%7B%0A%20%20%20%20%22kind%22%3A%20%22HogQLQuery%22%2C%0A%20%20%20%20%22query%22%3A%20%22%20%20%20select%20count(distinct%20session_id)%2C%5Cn%20%20%20%20%20%20%20%20%20%20toStartOfDay%20(toTimezone%20(timestamp%2C%20'utc'))%20as%20date%5Cn%20%20%20%20%20from%20session_recording_events%5Cn%20%20%20%20where%20timestamp%20%3E%20now()%20-%20interval%2021%20day%5Cn%20group%20by%20date%5Cn%20order%20by%20date%20desc%5Cn%20%20%20%20limit%20100%22%0A%20%20%7D%0A%7D)
2. Watch it fail

## Environment

- [ ] PostHog Cloud US, project ID: [please provide from https://app.posthog.com/project/settings#project-id]
- [ ] PostHog Cloud EU, project ID: [please provide from https://eu.posthog.com/project/settings#project-id]
- [ ] PostHog Hobby self-hosted with `docker compose`, version/commit: [please provide]
- [ ] PostHog self-hosted with Kubernetes (deprecated, see ["Sunsetting Kubernetes support"](https://posthog.com/blog/sunsetting-helm-support-posthog)), version/commit: [please provide]

**Comment by mariusandra** [comment]
Blimey. In this case swapping `'utc'` with `'UTC'` will fix it. The error comes from ClickHouse not knowing _that_ timezone in lowercase. I still haven't looked at exposing _server errors_ to users (sounds like a bad idea), so I wonder how to fix this 🤔 .
