### ISSUE TITLE
Event Explorer new feature has messed up my events

### ISSUE THREAD

**Issue by yevgoldin** [PostHog/posthog#15143]
## Bug description

The new Event Explorer has blown away my previous saved columns and events that are showing up are not in the correct order and there are a lot of random duplicates. This seems to be specific to the Event Explorer feature as my other coworker are still seeing Live Events and no issues on their end

Links to examples:
- [Events for user](https://app.posthog.com/events#q=%7B%22kind%22%3A%22DataTableNode%22%2C%22full%22%3Atrue%2C%22source%22%3A%7B%22kind%22%3A%22EventsQuery%22%2C%22select%22%3A%5B%22*%22%2C%22event%22%2C%22person%22%2C%22coalesce(properties.%24current_url%2C%20properties.%24screen_name)%20--%20Url%20%2F%20Screen%22%2C%22properties.%24lib%22%2C%22timestamp%22%5D%2C%22orderBy%22%3A%5B%22timestamp%20DESC%22%5D%2C%22after%22%3A%22-24h%22%2C%22limit%22%3A100%2C%22properties%22%3A%5B%7B%22key%22%3A%22uid%22%2C%22value%22%3A%5B%229ZSfr32sMIQJgqcSlSGsL3eLThh1%22%5D%2C%22operator%22%3A%22exact%22%2C%22type%22%3A%22event%22%7D%5D%7D%2C%22propertiesViaUrl%22%3Atrue%2C%22showSavedQueries%22%3Atrue%7D)

## How to reproduce

1. Go to our stage project event explorer page
2. View that there is no way of saving columns in the table view (previously saved columns are also gone when Live Events were working)
3. Filter the events by UID = [9ZSfr32sMIQJgqcSlSGsL3eLThh1]

<img width="863" alt="image" src="https://user-images.githubusercontent.com/109628732/232895529-49e26947-27a5-4c74-a190-ddec70768317.png">

![image](https://user-images.githubusercontent.com/109628732/232895982-6a0f64f4-d2ff-476a-af64-2862dfbf0369.png)

## Environment

- [13798] PostHog Cloud US, project ID

**Comment by yevgoldin** [comment]
![image](https://user-images.githubusercontent.com/109628732/232895900-0f1ac271-82f0-4234-a3fe-e593183128e8.png)

**Comment by neilkakkar** [comment]
Hey @yevgoldin this should be fixed now by https://github.com/PostHog/posthog/pull/15144 - let us know if you still face it
