### ISSUE TITLE
Stop capturing events on debug instances

### ISSUE THREAD

**Issue by paolodamico** [PostHog/posthog#1518]
When `DEBUG = 1` stop sending events to PostHog (via `posthoganalytics`) as to remove noise from test installations. Perhaps we can just send a boot / install event with a property that indicates if it's running on debug to track the number of test installations.

CC @yakkomajuri

**Comment by yakkomajuri** [comment]
Yeah I would generally be for this as well, unless there's something I'm missing. It's nice to know someone deployed in DEBUG mode (i.e. hey new contributor!), but otherwise that just bloats the db with noise.

**Comment by Twixes** [comment]
I made a solution that should work, except on completely clean-slate instances that haven't gone through setup yet. Take a look at the PR.

**Comment by paolodamico** [comment]
Re-opening this as development instances are still sending frontend events to app.posthog.com, JS analytics should be disabled too.

**Comment by Twixes** [comment]
That's a simple enough change #1539.
