### ISSUE TITLE
Request: URL for modals

### ISSUE THREAD

**Issue by joethreepwood** [PostHog/posthog#15234]
## Is your feature request related to a problem?

We can now[ link to a specific part of PostHog from an external source](https://github.com/PostHog/posthog/issues/15114), regardless of domain. 

However we can't link to modals, such as the dashboard template library, or the 'Report a bug' modal because [they don't have defined URLs](https://posthog.slack.com/archives/C0351B1DMUY/p1682433541053899?thread_ts=1682358380.873149&cid=C0351B1DMUY). 

It would be very helpful if these two modals in particular would have a defined URL, so that we can update the site and blog content to direct to them. In particular for support, so we'd keep support focused in the right place. 

## Describe the solution you'd like

URLs for the dashboard template modal, and the support modal. 

## Describe alternatives you've considered

Not having them. 

## Additional context

https://posthog.slack.com/archives/C0351B1DMUY/p1682358380873149

**Comment by raquelmsmith** [comment]
cc @tiina303

**Comment by benjackwhite** [comment]
We can link to _some_ of them like the Subscriptions modal (a la https://app.posthog.com/dashboard/26089/subscriptions ) but it requires extra logic. Not an impossible task but just something that has to be done per-use case.

**Comment by joethreepwood** [comment]
Would it be possible to do the dashboard template modal too? That's one we can add links to in onboarding emails, in blog content -- because it has the integration wizard and a basic feature, it's a great starting point to offer new users.
