### ISSUE TITLE
Configuration Error: requires a background worker but everything seems to be OK

### ISSUE THREAD

**Issue by adamschoenemann** [PostHog/posthog#1523]
## Bug description
This shows up after I upgraded and restarted posthog web docker container.

![image](https://user-images.githubusercontent.com/2095226/91435953-7aef4c80-e867-11ea-9cbd-375b7edfbb82.png)

Everything seems to be working fine though and I see no errors in the logs; the redis instance is also chugging along.

Also: the "see the documentation" link is incorrect.

## Expected behavior

I expect it not to be there.

## How to reproduce

1. Start the docker containers with `docker-compose up -d`
2. Stop the posthog web container with `docker-compose stop web`
3. Start it again with `docker-compose start web`

## Environment

- Self-managed posthog
- posthog:latest docker container with image id 8f88964b86b1

### docker-compose.yml
```
version: '3'

services:
    db:
        image: postgres:alpine
        container_name: posthog_db
        environment:
            POSTGRES_USER: posthog
            POSTGRES_DB: posthog
            POSTGRES_PASSWORD: posthog
    redis:
        image: 'redis:alpine'
        container_name: posthog_redis
    web:
        image: posthog/posthog:latest
        container_name: posthog_web
        ports:
            - '8000:8000'
            - '80:8000'
        environment:
            IS_DOCKER: 'true'
            DATABASE_URL: 'postgres://posthog:posthog@db:5432/posthog'
            REDIS_URL: 'redis://redis:6379/'
            SECRET_KEY: '<redacted>'
            IS_BEHIND_PROXY: 'true'
            DEBUG: 'false'
            DISABLE_SECURE_SSL_REDIRECT: 1
        depends_on:
            - db
            - redis
        links:
            - db:db
            - redis:redis
```

### nginx configuration snippet
```
    location / { 
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header Host $http_host;
        proxy_redirect off;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_pass http://127.0.0.1:8000;

        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Scheme $scheme;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_cache_bypass $http_upgrade;
    }  
```

**Comment by yakkomajuri** [comment]
Yeah this has been complained about before... It appeared we thought it was fixed but it isn't. I'll close #1010 in favor of this to bump it up the list.

**Comment by fitzn** [comment]
I'm hitting this, too, on a completely fresh install. The web and redis containers are up and logs look normal.

**Comment by edmundmunday** [comment]
Also seeing this error.

**Comment by timgl** [comment]
This is fixed!
