### ISSUE TITLE
Bug: Showing "Leaving insight?" modal when saving funnel insight

### ISSUE THREAD

**Issue by andyvan-ph** [PostHog/posthog#15235]
## Bug description

On [this insight](https://app.posthog.com/insights/BiPSyWDE), pressing 'Save' shows me the 'Discard insight?' warning message.

If I click OK, the insight still saves. See below screen recording:

https://user-images.githubusercontent.com/92976667/234332974-6918fb3f-1235-44fc-ac04-e6473d2573ff.mov

Link to session recording: https://app.posthog.com/recordings/187b79a283050-05024d6da93b5a-1d525634-4b9600-187b79a28311d81?t=23969

## How to reproduce

1. Edit above insight
2. Click save

## Environment

- [x] PostHog Cloud US, project ID: [please provide from https://app.posthog.com/project/settings#project-id]
- [ ] PostHog Cloud EU, project ID: [please provide from https://eu.posthog.com/project/settings#project-id]
- [ ] PostHog Hobby self-hosted with `docker compose`, version/commit: [please provide]
- [ ] PostHog self-hosted with Kubernetes (deprecated, see ["Sunsetting Kubernetes support"](https://posthog.com/blog/sunsetting-helm-support-posthog)), version/commit: [please provide]

**Comment by mariusandra** [comment]
Fixed with https://github.com/PostHog/posthog/pull/15250 ?

**Comment by thmsobrmlr** [comment]
Yes, just verified this is not triggering the confirmation. Thanks @andyvan-ph @mariusandra !
