### ISSUE TITLE
Allow to add "AND" operations on events when creating an action

### ISSUE THREAD

**Issue by rousan** [PostHog/posthog#1528]
## Is your feature request related to a problem?
Right now, when I am describing an action by some sequenced events, it's applying the "OR" operation on those events, but that should be "AND" operation. An example: If I want to know how many users have bought a product after sign up, we can define an action as below:

"**Submit the Sign up form**" AND "**Visit the Products page**" AND "**Checkout a product**"

So, here, "AND" operation is very much applicable instead of "OR".

## Describe the solution you'd like
PostHog should provide an option to select between "OR" and "AND".

## Describe alternatives you've considered
No workarounds, Please let me know if there is any other way to do that.

**Comment by Twixes** [comment]
Hi! You can in fact use cohort filters in actions, so you can set up cohorts "Users that signed up" and "Users that visited the Products page", and add these as filters in a "Checkout a product" action. Surely not the _smoothest_ flow, but sounds like it should do the job you described. (more comprehensive action definition is definitely something we'd like to do though)

**Comment by Twixes** [comment]
This issue is superseded by #1777 and definitely on our radar!
