### ISSUE TITLE
Minor UI improvements

### ISSUE THREAD

**Issue by paolodamico** [PostHog/posthog#1529]
A couple of random UI improvement suggestions,

- Add the date bar to the first group of elements too. When you have older users (like 17 days ago), it's a bit more difficult to do the math mentally on when the event actually happened.

<img width="600" alt="" src="https://user-images.githubusercontent.com/5864173/91612933-16ee8600-e944-11ea-91e0-b9cc4c85fa22.png">

- Make these elements look more like clickable buttons, at first sight they can be lost due to a small contrast ratio with the background
<img width="600" alt="" src="https://user-images.githubusercontent.com/5864173/91612974-2d94dd00-e944-11ea-9520-b07232406f58.png">

**Comment by yakkomajuri** [comment]
Agree with #2, but not with #1. I get your point regarding the bar and agree with the spirit, but imo it doesn't look nice on a table when the first row after the header is not an actual data row.

**Comment by paolodamico** [comment]
Closing this as this has been addressed.
