### ISSUE TITLE
Irregular behavior by filtering out internal and test users.

### ISSUE THREAD

**Issue by jmotz** [PostHog/posthog#15338]
## Bug description

We are experiencing irregular behavior when filtering out internal and test users.
Posthog appears to filter out users that do not meet the set internal and test user criteria.

RE: Ticket (2625). 
@yakkomajuri @mariusandra 

## How to reproduce

**Example insight:**
https://app.posthog.com/insights/PEwC207V

**When Filter out internal and test users is ON**

- Shows 0 users
- Despite un-identified users
- Users that do contain internal and test users properties

**Filter out internal and test users:**
https://app.posthog.com/project/settings

email ∉ ourdomain.com
Host ∉ localhost
isDemo ∉ true (Custom accounts property)

## Environment

- PostHog Cloud US, project ID: [12713]

**Filter out internal and test users is ON**
![Screenshot 2023-05-02 at 3 21 24 PM](https://user-images.githubusercontent.com/6488325/235764762-2b118f09-a474-4c45-9455-02b5283d4ae7.png)

**Filter out internal and test users is OFF**
![Screenshot 2023-05-02 at 3 21 45 PM](https://user-images.githubusercontent.com/6488325/235764835-5541fc49-68ef-4f55-a4b9-3f1f55c6787e.png)

**Comment by yakkomajuri** [comment]
Hey @jmotz ! This is fixed now
