### ISSUE TITLE
Configurable columns in the person/events table

### ISSUE THREAD

**Issue by timgl** [PostHog/posthog#1534]
## Is your feature request related to a problem?

We can display any property in the events/person tables. it'd be nice for users to be able to pick which columns we display themselves.

## Describe the solution you'd like

I want to have a super simple interface (in a modal) that allows me to pick which columns should be shown. We have two types of things we can show here. Some are a little special (like the name of the event that does some special stuff) and then just plain property keys. We should be able to have any of these selectable.

**Comment by thedeveloperr** [comment]
@timgl I am interested in this one can I work on this ?

**Comment by timgl** [comment]
@thedeveloperr Go for it! I haven't specced this out in a huge amount of detail so feel free to drop some ideas in here if you want feedback :)

**Comment by thedeveloperr** [comment]
I will first take a look how the table currently is being populated and then give few ideas.

**Comment by thedeveloperr** [comment]
@timgl 
Please elaborate these two lines of the of the solution description mentioned above with an example.

>  Some are a little special (like the name of the event that does some special stuff) and then just plain property keys. We should be able to have any of these selectable.

**Comment by Twixes** [comment]
Hi! Properties starting with a `$` are PostHog's special ones (like  `$browser`, which is displayed `Browser`). Here they are: https://github.com/PostHog/posthog/blob/5bce20abe41f01ddabaaa01c70388a200bbe7884/frontend/src/lib/components/PropertyKeyInfo.js#L5-L150
Other properties are just displayed as is.

**Comment by thedeveloperr** [comment]
@timgl @Twixes So I am thinking of creating a model in database for creating and saving different different columns config with one marked as default. So a person can from drop down choose different config of columns to show. How is that approach ?

**Comment by timgl** [comment]
@thedeveloperr Given there is a 1:1 relationship with a user for this, it might make sense to just store this as a JSONField against the User model? So you have a `person_table_config` and `events_table_config` field. What do you think?

**Comment by thedeveloperr** [comment]
I wanted to use JSONfield only for the new model. I was thinking of different table in case in future different user in an org. want to share the same config. something like that. But yes we can start with this and later migrate.

**Comment by timgl** [comment]
@thedeveloperr Hey, any progress on this? :)

**Comment by thedeveloperr** [comment]
Yes. I am working on frontend first. I am new kea so taking some time.
Basically I am thinking of a modal that will open which will have all the
custom event columns user can have with a checkbox along side it. I am
reading on frontend if this data is there somewhere or if I will have to
get it from server.

**Comment by timgl** [comment]
Awesome! Most of the columns should be returned from the backend so you should be able to select from those

**Comment by yakkomajuri** [comment]
@eikooc

**Comment by thedeveloperr** [comment]
Hi I had a doubt. User Api right now is not using DRF. Can I follow the same pattern for backend right now 
? and change it later to DRF in a separate refactor. Also apologies for delay I was on bed rest due cervical issues. I am actively working on this now.

**Comment by Twixes** [comment]
Hey, we'll soon have `/api/user` implemented in DRF as well (#2111), but for now follow the current style.

**Comment by yakkomajuri** [comment]
Hey @thedeveloperr hope you're doing ok now! No need to apologize.

**Comment by pauldambra** [comment]
@mariusandra @clarkus 

Just working on this and it feels weird that the events table settings are in the URL but the table config is stored in the backend

If I get the page "just right" and then send the URL to someone to show them they won't get the same view of the data

It feels to me like the table config should be in the URL...

🤔 ??

**Comment by mariusandra** [comment]
The other side isn't too nice either: every time someone sends you an URL, your personal table config gets overridden. 

What makes sense to me is to:
- Indeed, persist the visible columns of the table in the url. 
- Add a "save column layout as default" button somewhere
   - This will persist whatever is selected in the URL into the user
   - The button would show only if there's something to save, `savedColumns !== visibleColumns`.
- The user's saved or default columns would be used if visiting the events page directly, e.g. via `/events`

**Comment by pauldambra** [comment]
@mariusandra chatting with @clarkus it is much simpler for someone using the UI if we only save to the URL

That also matches the experience of interacting with the rest of the page

Are we missing a reason to also save to the user?

**Comment by mariusandra** [comment]
You're right, let's simplify this down to the essential feature that makes sense, and remove a lot of unnecessary complexity by removing this user persistence layer. 

Worse case for the user: you'll use browser bookmarks if you want to "persist" a table configuration.
Best case for the user: nobody is confused as to why different users have a different experience on the page. Easier to manage, support, etc.

**Comment by pauldambra** [comment]
#6308 currently runs like this

![table-column-config](https://user-images.githubusercontent.com/984817/136996705-db73cf06-70be-403d-8c6a-a9285ddaa605.gif)

**Comment by pauldambra** [comment]
Released in 1.29.0

Need to monitor and then remove the feature flag. Leaving this open as my prompt to not forget to tidy up the feature flag

**Comment by pauldambra** [comment]
Feature flag was only released to staff

Released to beta users on 8th Nov

**Comment by pauldambra** [comment]
flag was removed in https://github.com/PostHog/posthog/pull/7233

**Comment by pauldambra** [comment]
deleted feature flag
