### ISSUE TITLE
Add debugging mode to editor to show what events you're triggering

### ISSUE THREAD

**Issue by timgl** [PostHog/posthog#154]
**Is your feature request related to a problem? Please describe.**
It's hard to debug what events are being sent from the network tab because it's base64.

**Describe the solution you'd like**
If you have your own app open with the editor, show a list of all events you're sending in real time.

**Describe alternatives you've considered**
Using the network tab to debug

**Additional context**

I think it'd also be great to have a button within PostHog (sidebar?) that sends you straight to your own website with the editor open.

**Comment by Twixes** [comment]
I think this may be… not so relevant anymore?
