### ISSUE TITLE
Allow creation and management of multiple teams

### ISSUE THREAD

**Issue by timgl** [PostHog/posthog#1540]
## Is your feature request related to a problem?

When #1468 gets merged in I want to be able to create and manage multiple entities

## Describe the solution you'd like

We probably need to move to an Organisation -> Team model, where everyone is a member of an organisation and an organisation has multiple Teams that users can switch between. For some inspiration, see [how sentry do it](https://github.com/getsentry/sentry/blob/096b355d931fad5a175d3fb06da7ed6ee0f0074a/src/sentry/models/organization.py) (note, they use 'projects' for what we call teams)

- Create Organization model (and have a specific "through" model for an OrganizationMember, as we'll want to add things like 'roles' to that relationship in the future)
- Migration that creates organisation for each Team and moves all the team members.

*If license/plan enabled, should live in ee*
- Under the switcher dropdown, show a "manage teams" option
- Allow creation of new projects

## Describe alternatives you've considered

-

## Additional context

This is a much requested features

**Comment by paolodamico** [comment]
I actually think an Organization -> Project abstraction might be more intuitive. I think a more common use case is wanting to segment different app scopes than teams (e.g. having a landing website project and a web app project). 

Also maybe this should be an enterprise / paid plan feature ?

**Comment by Twixes** [comment]
I kind of agree that describing this as Projects would be better (though no change in mechanics really). It could also make sense to have this be a Growth and above plan feature. @timgl What do you think about this?
