### ISSUE TITLE
Retry-After header missing from rate limited / throttled requests

### ISSUE THREAD

**Issue by yakkomajuri** [PostHog/posthog#15411]
Django Rest Framework's docs on their throttling says that if the `wait` method is implemented, a `Retry-After` header will be added to the response. We do implement the method, but don't get the header.

I suspect some middleware somewhere is removing that header. Tried to fix in a few ways but with no success.

**Comment by yakkomajuri** [comment]
https://posthoghelp.zendesk.com/agent/tickets/2741 (moved to PostHog: https://us.posthog.com/project/2/support/tickets/6047)

**Comment by pauldambra** [comment]
Ah ha! DRF exceptions hog https://github.com/PostHog/drf-exceptions-hog/pull/39
