### ISSUE TITLE
Hide unnecessary URL controls when editing a pageview action

### ISSUE THREAD

**Issue by Twixes** [PostHog/posthog#1544]
## Is your feature request related to a problem?

Extra URL controls are unnecessarily shown when editing a pageview action and not using URL.
<img width="494" alt="Screen Shot 2020-09-01 at 17 02 34" src="https://user-images.githubusercontent.com/4550621/91869609-656a9000-ec76-11ea-989e-145285a78458.png">

## Describe the solution you'd like

Hide controls when they're irrelevant (area inside red outline).

**Comment by afarbman** [comment]
I would like to try and fix this.

**Comment by Twixes** [comment]
Hi @afarbman! You are very much welcome, make a pull request when done and I'll be happy to review it.

**Comment by afarbman** [comment]
@Twixes , I assume the change should be for the frontend element as well
