### ISSUE TITLE
Pre-built integrations with popular software

### ISSUE THREAD

**Issue by jamesefhawkins** [PostHog/posthog#1545]
From Harry Waye!

>I'm looking at integrating HubSpot data into [my startup] and was wondering if you've got any history with that.
>Namely it would be AMAZING to pull things like number of active customers, churn, new customers without having calculate ourselves but it doesn't look like you can pull data via the API from the HubSpot Reports. If you happen to know anything about it would be most helpful (I fear we'll need to do some horrible calculations which will be brittle and vary from customer to customer)

* Lots of people use the same platforms over and over:
  * Shopify
  * SalesForce
  * Hubspot
  * MailChimp
  * Stripe
  * Webflow
* Could we have some pre-built integrations and dashboards based on one-click integrations for these?

**Comment by jamesefhawkins** [comment]
A further idea is that we could offer a very cool extension, like this but applied to many of the above:

https://orbit.love/blog/open-sourcing-our-chrome-extension/

* Salesforce: view user profile in PostHog
* Hubspot: view user profile in PostHog

and so on.

Or to even offer the ability inside your own app if you view a user profile, to be able to map from that to the PostHog record.

**Comment by paolodamico** [comment]
We now have a ton of cool plugins that accomplish this.
