### ISSUE TITLE
The plugins service starts and reports an error

### ISSUE THREAD

**Issue by mano233** [PostHog/posthog#15464]
## Bug description
pr：[#15295](https://github.com/PostHog/posthog/pull/15295)

logs:
```
{"level":"error","time":1683706736790,"pid":54,"hostname":"34f1518b13ad","error":"Error: EACCES: permission denied, mkdir '.tmp/sessions/session-buffer-files'\n    at mkdirSync (node:fs:1396:3)\n    at SessionRecordingBlobIngester.start (/code/plugin-server/dist/main/ingestion-queues/session-recording/session-recordings-blob-consumer.js:157:33)\n    at startPluginsServer (/code/plugin-server/dist/main/pluginsServer.js:298:28)","msg":"[MAIN] 💥 Launchpad failure!"}
```

because the container is started as the `posthog` user
```
root@9a7c3d54bdae:/code# ps -aux
USER       PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
posthog      1  0.0  0.0   4300   624 ?        Ss   08:57   0:00 ./bin/plugin-server --no-restart-loop
root        44  0.0  0.0   6036  2240 pts/0    Ss   09:04   0:00 bash
root       434  0.0  0.0   8632  1572 pts/0    R+   09:08   0:00 ps -aux
```

## Environment

- [ ] PostHog Cloud US, project ID: [please provide from https://app.posthog.com/project/settings#project-id]
- [ ] PostHog Cloud EU, project ID: [please provide from https://eu.posthog.com/project/settings#project-id]
- [x] PostHog Hobby self-hosted with `docker compose`, version/commit: [please provide]
- [ ] PostHog self-hosted with Kubernetes (deprecated, see ["Sunsetting Kubernetes support"](https://posthog.com/blog/sunsetting-helm-support-posthog)), version/commit: [please provide]

**Comment by h1manshu98** [comment]
Is this issue fixed or do you have any workaround @mano233 ?

**Comment by h1manshu98** [comment]
I got this solution and it works, instead of doing all tasks by `plugins` , we can do those works separately by `pluginsAsync` `pluginsIngestion` `pluginsAnalyticsIngestion` `pluginsJobs` `pluginsScheduler`

```yaml
plugins:
  enabled: false

pluginsAsync:
  enabled: true

pluginsIngestion:
  enabled: true

pluginsAnalyticsIngestion:
  enabled: false

pluginsJobs:
  enabled: true

pluginsScheduler:
  enabled: true
```

**Comment by mano233** [comment]
> Is this issue fixed or do you have any workaround @mano233 ?

A very violent way was used:
```
    plugins:
        *privileged: true*
        *user: root*
        extends:
            file: docker-compose.base.yml
            service: plugins
        ....
```

**Comment by mano233** [comment]
> I got this solution and it works, instead of doing all tasks by `plugins` , we can do those works separately by `pluginsAsync` `pluginsIngestion` `pluginsAnalyticsIngestion` `pluginsJobs` `pluginsScheduler`
> 
> ```yaml
> plugins:
>   enabled: false
> 
> pluginsAsync:
>   enabled: true
> 
> pluginsIngestion:
>   enabled: true
> 
> pluginsAnalyticsIngestion:
>   enabled: true
> 
> pluginsJobs:
>   enabled: true
> 
> pluginsScheduler:
>   enabled: true
> ```

The main problem is the permissions of the folder 
https://github.com/PostHog/posthog/blob/c83a5dd842a22a2bef19bbbbc116b13d4f6a538e/plugin-server/src/main/ingestion-queues/session-recording/session-recordings-blob-consumer.ts#L172
There is no guarantee that 'rm' or 'mkdir' will be available here

**Comment by h1manshu98** [comment]
Okay, I was assuming that you are working with microservice architecture (kuberentes/helmchart)

**Comment by mano233** [comment]
> 

In fact no kuberentes are used.
look at this

https://github.com/PostHog/posthog/blob/b9da58d7a7dab6a8757b38779f2f2f2cef093cf2/production.Dockerfile#L161

**Comment by mano233** [comment]
> Okay, I was assuming that you are working with microservice architecture (kuberentes/helmchart)

> 

In fact no kuberentes are used.
look at this

https://github.com/PostHog/posthog/blob/b9da58d7a7dab6a8757b38779f2f2f2cef093cf2/production.Dockerfile#L161

**Comment by pauldambra** [comment]
i believe this can be closed, feel free to re-open if not
