### ISSUE TITLE
Found `debugger` on production

### ISSUE THREAD

**Issue by vishaltps** [PostHog/posthog#15488]
## Bug description

I know lately Posthog has had lots of bugs, However, I never expected you will add a debugger in your prod build.

## How to reproduce

1. Go to the recordings
2. Click on filters (It will go to the getSessions function) where it will stop the further execution because of debugger

## Environment

- [x] PostHog Cloud EU, project ID: [please provide from https://eu.posthog.com/project/settings#project-id]

## Additional context

<img width="1728" alt="Screenshot 2023-05-11 at 11 43 46" src="https://github.com/PostHog/posthog/assets/16555538/811377f1-4d0e-402a-9353-572e7e51bb82">

**Comment by pauldambra** [comment]
resolved in https://github.com/PostHog/posthog/pull/15487
