### ISSUE TITLE
Toolbar can't override control variant

### ISSUE THREAD

**Issue by hansottowirtz** [PostHog/posthog#15481]
## Bug description

When using the toolbar to select the "control" variant, it is not overridden but the actual flag is passed.

## How to reproduce

1. Create an experiment, make sure the user has a variant that's not "control"
2. Use the toolbar to select "control"
3. `onFeatureFlags` is called with the variant assigned to the user (not "control")

## Environment

/

## Additional context

The feature flags are bootstrapped on `posthog.init`, but I'm not sure if that is relevant.

**Comment by oleast** [comment]
We're having the same problem with events triggered from `addFeatureFlagHandler`. The variant will never be `control` even when flipping between a `control` and `test` variant.

We're trying to set up an override that works with locally computed feature flags on the back-end. The only missing piece is to get the correct flags from the toolbar.

**Comment by neilkakkar** [comment]
I'd recommend using variant overrides inside the UI itself - these are made on our backend, are a lot more stable, and work everywhere, irrespective of the toolbar.

**Comment by neilkakkar** [comment]
This should be fixed now!
