### ISSUE TITLE
Can't add new actions

### ISSUE THREAD

**Issue by Krisseck** [PostHog/posthog#155]
Problem is simple, I cannot add new actions at all, the "Save action" button does nothing.

I checked the ajax request it does, it makes a POST request to `/api/action`, but it returns a 403 error with message `{"detail":"No token"}`. Not sure what token it is referring to, but that request at least has `csrftoken` in the cookies.

Tested with latest Firefox and Chromium, same issue. Using the posthog/posthog:preview docker image, fresh installation.

**To Reproduce**
1. Start posthog/posthog:preview docker image
2. Do the setup
3. Populate with some events
4. Click "Add action"
5. Fill the form fields
6. Press "Save action"

**Expected behavior**
Action should be saved and visually presented to the user. Or even a error message would be nice :)

**Desktop (please complete the following information):**
 - OS: Linux
 - Browser: Latest Chromium and Firefox

**Comment by timgl** [comment]
Hey, thanks so much for filing a bug report! I'm struggling to reproduce this. Are you getting this issue within PostHog itself, or is it the editor (where you get taken to your own site by clicking the green 
![image](https://user-images.githubusercontent.com/1727427/75008636-6a2fcb00-542d-11ea-965f-19b8afcbb83b.png) button)?

If the latter, which site are you sending yourself to?

In either case, could you send a screenshot of your network tab?

Thanks!

**Comment by Krisseck** [comment]
Hey, just tested it, it's both, inside Posthog and in the editor.

Here's some screenshots, sorry for blurring out some stuff, hope they help!

![Screenshot_20200221_091154](https://user-images.githubusercontent.com/471887/75012481-b6f5bf00-548a-11ea-846b-244be8253a16.png)
![Screenshot_20200221_091220](https://user-images.githubusercontent.com/471887/75012483-b826ec00-548a-11ea-88a0-98fbfaab48be.png)
![Screenshot_20200221_091257](https://user-images.githubusercontent.com/471887/75012484-b8bf8280-548a-11ea-94cc-95df6ea8346c.png)

**Comment by timgl** [comment]
Are you running PostHog behind a proxy by any chance? If so, do you have an environment variable `IS_BEHIND_PROXY` set?

I think we may have missed a setting that I'll merge in now ^, which I think should fix an issue with the `build_absolute_uri` function in Django.

**Comment by Krisseck** [comment]
Sorry, still not working. This is getting strange 😅

So I tried pulling the newest image and restarting the container. No difference.

Then I removed all containers and volumes, and started a completely fresh install, ran the setup process and... still, no difference. Still won't let me save.

Was wondering is it something in my Nginx config, here is what I am using. Do you see anything wrong with it?

```
 location / {
          proxy_pass http://127.0.0.1:8000/;
          proxy_http_version 1.1;
          proxy_set_header Upgrade $http_upgrade;
          proxy_set_header Connection 'upgrade';
          proxy_set_header Host $host;
          proxy_cache_bypass $http_upgrade;
        }
```

I have the `IS_BEHIND_PROXY` set:

```
root@posthog:~# docker exec posthog bash -c 'echo "$IS_BEHIND_PROXY"'
true
```

**Comment by timgl** [comment]
@Krisseck This _is_ getting strange! Can you check whether on the request you're sending the Origin headers?

**Comment by Krisseck** [comment]
Progress! I just manually went to http://127.0.0.1:8000, and the action totally works. So the issue is most likely something to do with nginx or proxy headers on the app.

**Comment by Krisseck** [comment]
@timgl Yeah, the request has Origin header and it points to the Nginx url, not 127.0.0.1

**Comment by timgl** [comment]
@Krisseck I'm looking at this article: https://stackoverflow.com/questions/58044582/localhost-in-build-absolute-uri-for-django-with-nginx

It suggests the nginx file should look something like this:
```
location / {
    ...
    proxy_set_header X-Forwarded-Host $host:$server_port;
    proxy_set_header X-Forwarded-Server $host;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    ...
    proxy_pass http://upstream:port;
}    ```

**Comment by Krisseck** [comment]
Alright, I got it working! Here is the config I needed to put in nginx:

```
location / {
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header Host $http_host;
        proxy_redirect off;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_pass http://127.0.0.1:8000;
    }
```
Looks like it needs all those 5 proxy settings set, otherwise won't work properly.

**Comment by timgl** [comment]
@Krisseck Amazing, glad you got it working :-). [I've updated the docs](https://github.com/PostHog/posthog/wiki/Running-behind-a-proxy) and created an error message that is much more useful than 'No token'.

Thanks!
