### ISSUE TITLE
DAU/MAU ratio

### ISSUE THREAD

**Issue by SuperKruse** [PostHog/posthog#1550]
We would like to track user engagement, for that they would like to use DAU/WAU/MAU.

## Describe the solution you'd like
Either show just the numbers (like google analytics) or a chart over time like everything else.

![image](https://user-images.githubusercontent.com/12446111/91987810-cfdf0700-ed2e-11ea-918b-c8deffabe33b.png)
From google analytics

It would be nice to have the
DAU/MAU-ratio
DAU/WAU-ratio
WAU/MAU-ratio

**Comment by paolodamico** [comment]
Will be addressed in #1279

**Comment by timgl** [comment]
We have part one of this which is Formulas, we just need #3638
