### ISSUE TITLE
`first team event ingested` event sent multiple times

### ISSUE THREAD

**Issue by paolodamico** [PostHog/posthog#1552]
## Bug description
- See screenshot below (it's likely being processed in 3 workers at the same time).

![sc](https://user-images.githubusercontent.com/5864173/92016443-f6457800-ed17-11ea-9b7f-959a3306850e.png)

## Expected behavior
- We should receive the event only once.

## How to reproduce

1. View a user of recent creation with this event ([example](https://app.posthog.com/person/5fabb7b9-a36c-4419-af97-eea75960b2e4)) 

## Environment

- Cloud from PR #1508

**Comment by macobo** [comment]
Actually, this isn't affected by cronjobs. Oops.
