### ISSUE TITLE
Signup: Start asking people what they are signing up for

### ISSUE THREAD

**Issue by raquelmsmith** [PostHog/posthog#15531]
As we become more multi-product, we need to understand _why_ people are signing up (which products they are primarily interested in) so that we can tailor their experience and help us track activation in the correct products after signup intent.

There are a couple ways we can go about this:

1) signaling based on which pages they've viewed prior to signup
    - This is nice because  it doesn't require them to answer questions, but is going to be very prone to inaccuracies.
2) asking the person on signup what they are signing up for
    - this is very explicit and might have the benefit of improving signup conversion rates - when you ask someone what they are there for, you're cementing in their brain that you DO offer the thing they are looking for, so they are more inclined to continue.
3) other ideas??

We discussed in our last growth review that doing no.2 would be a good place to start. Basic things that need to happen here are:

- Modify the signup form to include a question that asks why they are signing up
- Collect that info and store it on the org - prob don't need to store it in the db, but just as a property on the org in PostHog

**Comment by ClaireCyberBear** [comment]
For 2.) It should be as simple and hassle free as possible for the user. It can lead to a bad impression if it's too burdensome.

**Comment by Jacob-Hollis** [comment]
For option 2, you could consider either a input based field (probably the simplest option) or a selection of multiple pre-defined options. If you're collecting the data, the pre-defined option might be easier to categorize, run metrics on, etc. However, you won't get the "pure" answers you'll get with input based data (this data can probably still be categorized, although it would need to be parsed for keywords and the like).

**Comment by rsensenig** [comment]
I recommend setting up testing for two different types of registrations to see what results in the highest conversion rates:
(1) Have pre-defined options next to checkboxes - this way the user can select multiple options, and clearly see all the products that are available. I suggest this question being asked on a 2nd page after initial sign-up to reduce friction.
(2) Instead of asking this question during the registration process, send a welcome email after the user signs up that encourages the user to log in. When they log in, have a pop-up window that asks what they're most interested in.

I don't recommend using an input based field as this can lead to inaccurate data and confusion in understanding user preferences due to user error, inconsistency, or vagueness. Also, a lack of standardization can make it challenging to categorize and analyze the data effectively. Additionally, an input based field results in a higher cognitive load to come up with and type in specific product names.

If you do use an input based field, it can be helpful to combine an input-based field with other techniques, such as providing autocomplete suggestions, offering predefined categories, or including additional instructions.

**Comment by hecwon** [comment]
Just spitballing but if y'all have any insights on typical products used by groups that can be categorized, you can suggest accordingly after asking them to describe themselves with those categorizations.

![image](https://github.com/PostHog/posthog/assets/107065950/37f040f2-04bf-4fce-88cd-48e426ac4335)

**Comment by mzchen14** [comment]
* I like the idea of predefined selection buttons which gives users a visual spread of the products offered and also the opportunity to select more than one area of interest. 
* +1 to the idea of of adding it after the sign up page to decrease potential friction, maybe not even part of the sign up process at all but part of onboarding. 
* May be a good step on the welcome screen / pages and then the user's selections can also be used to append docs / demos to the quick start guide that follows. This may be a good way to keep users engaged with what they came for. 
* Iterating off of idea # 1, perhaps tracking time spent per product overview tab can also be helpful for these metrics. I'd imagine users may visit all tabs but invest the most time reading through the details of their area of interest.

**Comment by joethreepwood** [comment]
Based on previously asking users where they heard about us via an open text box, we can predict that if this field is optional we'll get only 10% of users submitting a response. The only real way to counter this is to make it a required field, which is ++intrusion. Either way, the more fields and complexity we add to the sign-up flow, the greater the impact on sign-up conversion will be. We want it to be as effortless as possible. 

Another way to approach this in a way would be to ask the same question through an in-app prompt X days _after_ the user has signed up and begun using the product. This would enable us to still get the same information (we're tracking usage anyway and could still segment based off the information), and arguably the information would be better as we'd be focusing more accurately on successful users (vs. people who may complete sign-up and then immediately churn). 

Additional advantages would be that we can deploy this much faster using the in-app prompts system, minimize impact on the sign-up flow, and potentially make the question repeat (or be more controllable) so as to get a higher response rate.

**Comment by andyvan-ph** [comment]
> Either way, the more fields and complexity we add to the sign-up flow, the greater the impact on sign-up conversion will be. We want it to be as effortless as possible.

For context, we currently have two optional and two mandatory fields on the 2nd step atm.

<img width="436" alt="Screenshot 2023-05-18 at 10 49 42" src="https://github.com/PostHog/posthog/assets/92976667/c47fb7d8-5b9f-44c6-89d7-4bc18fcd3959">

This is something to test, but if we end up adding something, maybe we move it later in the onboarding at a point the user is more committed? Could move the two optional fields here with it.

**Comment by OakesekAo** [comment]
Is there an existing a/b sign up and onboarding already? It may be a large investment, but a possible route to streamline it. 

In the mean time, maybe just a text box for <500 char to describe what they are hoping to solve. 

I'm blind on what is offered already, but possibly a high touch option and scheduling a call if the price point is right to gather this info/feedback.

**Comment by kirso** [comment]
2. only introduces cognitive load with an existing field. Given user passes the first step of the form (already invested & qualified), its easier to introduce a second step and give an option to select the product the user is interested in with explanation that it will help to provide a better service. This way there is less fields in step 1 but you still get the intent in step 2. Also if after testing this reduces conversion by X% -> you can justify it by the metric you can define for this improvement such as converted from trial to paid and have conversion as a guardrail.

IMO if you need to answer the qualitative `why` -> it will never be as clear based on data compared to say discovery with the user on the call.

If its about the quantitative `what` product users intend to use, you'll get that data anyways if the intent translates to usage.

**Comment by raquelmsmith** [comment]
We'll actually gather this info based on what they decide to onboard into in the new product-specific onboarding flows.
