### ISSUE TITLE
`pip install xmlsec` broken after `libxmlsec1` updated to v=1.3.0

### ISSUE THREAD

**Issue by taimingl** [PostHog/posthog#15541]
## Bug description
When following the instructions [here](https://posthog.com/handbook/engineering/developing-locally) to deploy PostHog locally, I wasn't able to install one of the required python libraries, `xmlsec`, particularly pip wasn't able to build the wheel.

Online search suggested that `libxmlsec1` was updated to 1.3.0 on 4/12/23, and this latest version does not work with pip install. There is a temporary workaround that reverts `libxmlsec1` back to `1.2.37`, which eventually allowed me to `pip install xmlsec` and deploy PostHog locally. Please see more details about the workaround [here](https://github.com/xmlsec/python-xmlsec/issues/254#issuecomment-1511135314 )

## How to reproduce
Follow the instructions [here](https://posthog.com/handbook/engineering/developing-locally) to deploy PostHog locally:
1. brew install libxml2 libxmlsec1 pkg-config (libxmlsec1 defaults to 1.3.0 now)
2. create a virtual env with python3.10
3. pip install xmlsec==1.3.13 (one of the required libraries in requirements.txt)

## Environment

- [ ] PostHog Cloud US, project ID: [please provide from https://app.posthog.com/project/settings#project-id]
- [ ] PostHog Cloud EU, project ID: [please provide from https://eu.posthog.com/project/settings#project-id]
- [x] PostHog Hobby self-hosted with `docker compose`, version/commit: main branch @ e962afa
- [ ] PostHog self-hosted with Kubernetes (deprecated, see ["Sunsetting Kubernetes support"](https://posthog.com/blog/sunsetting-helm-support-posthog)), version/commit: [please provide]

## Additional context
My machine is macOS x86.
I don't think there's anything for PostHog team to fix at this time besides maybe inserting a note about the issue and the workaround on the `Deploying locally` page just like many other existing notes, which were super helpful in my experiment.

**Comment by iSatVeerSingh** [comment]
Same issue here. Please help as soon as possible

**Comment by Robokishan** [comment]
Just in case somebody looking for alternative incase of to avoid hacking on brew, use conda-forge for setting up posthog on mac
and steps

1. `conda create --name posthog python=3.10 `
2. `conda activate posthog`
3. `conda install libxmlsec1==1.2.37 pkg-config`
4. pip install -r requirements.txt

This work like a charm!
