### ISSUE TITLE
Cohort creation via api caused all cohorts to go missing from filters/dashboards everywhere in UI

### ISSUE THREAD

**Issue by jetaggart** [PostHog/posthog#15556]
## Bug description
All cohorts have gone missing from UI

I created a cohort via the api with a fairly large number of ids going against distinct_id. It created successfully and I can see it, and other cohorts in api, but now all of my cohorts have gone missing in the UI. I can't see any cohorts in the cohorts dashboard nor breakdowns or anywhere. Previous cohorts attached to insights have lost their information but still seem to associate correctly:

<img width="617" alt="Screenshot 2023-05-15 at 11 39 56 AM" src="https://github.com/PostHog/posthog/assets/161737/da1f8004-b0e3-43ef-9fae-0bf9148382ad">

## How to reproduce
Created a new csv via this python script, with a fairly large number of ids (70k+):

```python
import requests
import pandas as pd

POSTHOG_API_KEY = 'REDACTED'
PROJECT_ID = 'REDACTED'
COHORT_NAME = 'REDACTED'
CSV_FILE_PATH = 'REDACTED'

df = pd.read_csv(CSV_FILE_PATH)
cohort_data = {
    'name': COHORT_NAME,
    'is_static': False,
    'filters': {
        'properties': [
            {
                'key': 'distinct_id',
                'operator': 'in',
                'value': df['id'].tolist() // this has a lot of ids, 70k+
            }
        ]
    }
}

response = requests.post(
    f'https://app.posthog.com/api/projects/{PROJECT_ID}/cohorts/',
    headers={'Authorization': f'Bearer {POSTHOG_API_KEY}'},
    json=cohort_data
)

if response.status_code == 201:
    print('Cohort created successfully!')
else:
    print(f'Error creating cohort: {response.text}')
```
## Environment

- [x] PostHog Cloud US, project ID: 22107

**Comment by neilkakkar** [comment]
Hey @jetaggart , it seems like the cohort you generated has an incorrect schema definition which is causing this. If you delete it, you should be fine.

For the correct schema definition, check the API request when you create a cohort from the UI to figure out how to generate the cohort filters.

**Comment by neilkakkar** [comment]
I'll add validation to prevent this kind of cohort from being created

**Comment by jetaggart** [comment]
Phew, that fixed it. Thank you!

p.s. is there a way to filter on a list of distinct_ids dynamically? Would that be a feature request?

**Comment by neilkakkar** [comment]
Aye! It's on our roadmap - not possible yet to filter on distinct IDs. Best alternative for now is to create a person property called `distinct_id` which has the relevant distinct ID, and filter on that.

**Comment by jetaggart** [comment]
Ah awesome okay thank you.

**Comment by mariusandra** [comment]
> Aye! It's on our roadmap - not possible yet to filter on distinct IDs. Best alternative for now is to create a person property called `distinct_id` which has the relevant distinct ID, and filter on that.

@neilkakkar what about using a HogQL filter like `distinct_id = 'whatever'` 🤔

**Comment by jetaggart** [comment]
I don't think you can use hogql for a cohort. That would be sweet though!
