### ISSUE TITLE
Serverless analytics

### ISSUE THREAD

**Issue by jamesefhawkins** [PostHog/posthog#1556]
Interesting idea from a comment on our original hacker news launch:

> A feature request (or perhaps an architectural direction) would be if you could accommodate the backend behind graphql instead of Django+MySql, there's a potential for it go full Serverless (frontend and backend) with JAM-stack frameworks like redwood.js [1] (backed by apollo-graphql) or using Cloudflare Workers [2].

Curious, I emailed this person to ask why:

> The advantage is for developers (probably a disadvantage for PostHog?) who have to self-host it whilst at the same time not deal with DevOps or SRE.

> I was thinking: Why can't I add a javascript to my website / app and point it to a Cloudflare Workers forwarding metrics to KV / Lambda at Edge forwarding metrics to DynamoDB or Aurora endpoint and be done with it.

> I guess you'd be almost encroaching on the supabase.io territory with that.

# How could this work?

We already grab events and user profiles etc. Those would be powerful and easy to grab and send to a DynamoDB endpoint.

I could also see this being used to get event data into their warehouse too - Redshift or whatever.

Perhaps we could augment this data, also sending metrics for:

* Unique users
* Pageviews
* Retention
(basically, anything that can be worked out without our UX being used)

There could be some config in the JS snippet to do this.

# Pros

* No need for users to host an app at all. You could literally just run npm in your terminal to install it - incredibly low friction. That could help adoption.
* It'd be helpful for users that just want event / user data and aren't as fussed with the UX for now.
* This gets us closer to being something you can just chuck into a new app.
* We could more easily be included in open source libraries etc.

# Cons

* Confusing? A bit close to being a data pipeline whereas our nice UX is a big part of our value.

**Comment by ignoramous** [comment]
> This issue hasn't seen activity in two years

It didn't have to (:
