### ISSUE TITLE
Cross-Origin request blocked 

### ISSUE THREAD

**Issue by allan-simon** [PostHog/posthog#156]
***Thank*** you for reporting bugs - we appreciate every single bug report.

**Describe the bug**
When I open my website on which I have added posthog I got in the console.

```
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://test-posthog-can-be-deleted.herokuapp.com/decide/?verbose=1&version=1&lib=web&token=2YDOR7kQNZaLH21DBomsrzQZIkLTk8obdJE1u-ZnXUA&ip=1&_=1582290473421 . (Reason: CORS header ‘Access-Control-Allow-Origin’ does not match ‘https://test-posthog-can-be-deleted.herokuapp.com’).
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://test-posthog-can-be-deleted.herokuapp.com/e/?ip=1&_=1582290473425. (Reason: CORS header ‘Access-Control-Allow-Origin’ missing).
```

**To Reproduce**

1. go on the mainpage of your website where you have integrated posthog
2. check the console

nothing else required

**Desktop (please complete the following information):**
 - OS: Linux
 - Browser  Firefox
 - Version 73

I've installed posthog with the "launch with heroku" button

**Comment by allan-simon** [comment]
and I think that's the reason why I can't see any action arriving on the dashboard :(

**Comment by timgl** [comment]
Salut Allan! I've fixed this. We were using the Referer header (for some reason!) to set the Origin header, rather than the Origin. I think you may have had a setting that blocks referrers in Firefox, which is why we hadn't noticed this before.

Thanks for creating the issue :)

**Comment by timgl** [comment]
P.S. You'll probably need to re-deploy your Heroku instance for the change to take effect.

**Comment by allan-simon** [comment]
@timgl  Bonjour Tim ;-)  ok I will redeploy in some hours and I will tell you if it's fixed,  awesome how fast you fixed it !
