### ISSUE TITLE
Add toolbar to regular navigation and change what we call it

### ISSUE THREAD

**Issue by jamesefhawkins** [PostHog/posthog#1560]
## Is your feature request related to a problem?

Lots of users miss the toolbar entirely / get confused with the overlap between it and /actions.

## Describe the solution you'd like

* Add 'heatmaps' to the left hand nav. This should launch the toolbar with heatmaps switched on.
* Is there any reason in the /actions page we allow people to create actins *not* from the toolbar? Is that just adding confusion. Perhaps the editing of actions in this page is also confusing - would it be better to take users to the toolbar with that action open rather than URLs like https://app.posthog.com/action/1329, with complex looking editing.

## Describe alternatives you've considered

* Do nothing.

**Comment by paolodamico** [comment]
Partially addressed on #2238 and superseded by #2349.
