### ISSUE TITLE
Make cookieless analytics possible

### ISSUE THREAD

**Issue by aaukt** [PostHog/posthog#1571]
## Is your feature request related to a problem?

Current legislation in the EU around setting Cookies/Tracking forces site owners to show a cookie-banner if they  use cookies.
Several analytics plattforms exist that already have the option to disable cookies and/or use different methods of identifying users (GA, Matomo, Fathom, ...)

## Describe the solution you'd like

Similar to GA and their option to disable cookie storage (https://developers.google.com/analytics/devguides/collection/analyticsjs/cookies-user-id#disabling_cookies) i would really like the option to disable cookies in posthog.
Ideally you would then be able to set a client id in posthog.init()

` posthog.init('[your-token]', {api_host: 'https://[your-instance]', clientId: 'CLIENT_ID'})`

The clientId could either be created in the backend or by fingerprinting the browser or any other method.

## Describe alternatives you've considered

-

**Comment by timgl** [comment]
I've created a PR in posthog-js that adds this option. However, GDPR still won't technically allow you to do any fingerprinting (based on IP or browser), but we can leave that up to you to work out!

**Comment by aaukt** [comment]
Wow that was fast!

So with this added i would call 
`posthog.init('[your-token]', {
    api_host: 'https://[your-instance]',
    persistence: 'disabled',
    loaded: function(posthog) { posthog.identify('MY_GENERATED_ID'); }
})`

correct?

Our main goal was trialing posthog for our product where we only have logged-in users and for that the cookie would be superflous (and we didn't want to make a cookie-banner just for that, when the rest of the site only uses a neccessary session cookie).
I know fingerprinting would technically fall under GDPR/Cookie-law, and if we wouldn't need retention stats we could just use a hash based on the session cookie.
But it's cool that we now could think about replacing GA also on the public facing site with posthog.

**Comment by timgl** [comment]
Yep that will work! yeah that use-case makes sense, if your users are logged in it obviously is fine to identify them. Will update this ticket once it's in!

**Comment by rikkit** [comment]
The cookieless option would be great - from my (admittedly, probably limited) understanding, it would enable the use of PostHog in GDPR jurisdictions without explicit consent for analytics **IF** the identifier sent to PostHog was not personally identifiable - this would be the case if a new identifier was created on every page load.

**Comment by boldtrn** [comment]
Just a note for anyone reading this now: I tried setting persistence disabled and still cookies were used, if you set `persistence: 'memory'`, then no cookies will be stored with PR 82.
