### ISSUE TITLE
[EPIC] Improve quality of data coming in

### ISSUE THREAD

**Issue by timgl** [PostHog/posthog#1573]
## Is your feature request related to a problem?

As a user we have a ton of data coming in, but sometimes that data isn't consistent or of good quality

## Describe the solution you'd like

- I want an overview of the volume of data coming in from different sources and how those change over time (am i getting more/less data from python compared to frontend for example)
- I want warnings if I'm sending the same property with different types (int and string for example)
- I want warnings if certain events suddenly stop being sent at all or if volume drops

**Comment by paolodamico** [comment]
Something along the lines of [Segment Protocols](https://segment.com/product/protocols/) would be pretty cool.
