### ISSUE TITLE
Improve core action tracking

### ISSUE THREAD

**Issue by paolodamico** [PostHog/posthog#1575]
There are some core actions we should now track server-side to improve data consistency (e.g. creating vs. updating), be more explicit in how we measure, and especially make sure we're getting the right data from self-hosted instances. We should start sending the following events,

- "action created", "action updated", "action deleted" (include obfuscated information about the match groups used, and Slack config).
- "dashboard created", "dashboard updated", "dashboard deleted" (include information on pinned, shared, number of dashboard items, and type of dashboard items).
- "feature flag created", "feature flag updated", "feature flag deleted" (include filter information & roll-out percentage)
- "cohort created", "cohort updated", "cohort deleted", "cohort exported" (include obfuscated match group info)
- "funnel created", "funnel updated", "funnel deleted"
- "annotation created", "annotation updated", "annotation deleted"
- "team member deleted"

This issue is in addition to #1509.

**Comment by jamesefhawkins** [comment]
* "annotation viewed"
* "X events received" or some sort of count of volume?
* Something to illustrate if it's loading correctly? ie do we have people doing 500 events/sec on a tiny Heroku instance that isn't coping with the load? Perhaps that could wait until James G's suggestion is built

**Comment by paolodamico** [comment]
>     * "annotation viewed"
- I believe this would be a client-side event, right? Or am I missing something?

>     * "X events received" or some sort of count of volume?
- 100%, addressed on #1509
>     * Something to illustrate if it's loading correctly? ie do we have people doing 500 events/sec on a tiny Heroku instance that isn't coping with the load? Perhaps that could wait until James G's suggestion is built
- @fuziontech any recommendations for this? Perhaps we could add some metric on this on #1509

**Comment by Twixes** [comment]
Annotations are loaded from `/api/annotation/`, so could capture there as well (I suppose there isn't a significant number of using that endpoint outside the app, but obviously if we want 100% app only, then that's client-side).

**Comment by paolodamico** [comment]
> Annotations are loaded from `/api/annotation/`, so could capture there as well (I suppose there isn't a significant number of using that endpoint outside the app, but obviously if we want 100% app only, then that's client-side).

But wouldn't the annotations be loaded from the backend even if the user doesn't see them? For instance when the user opens a dashboard but not actually opening any annotation?

**Comment by Twixes** [comment]
Ah, yes, they're loaded all in one request, so that wouldn't really reflect usage.
