### ISSUE TITLE
Heatmaps timeframe

### ISSUE THREAD

**Issue by paolodamico** [PostHog/posthog#1577]
##  Describe the solution you'd like

I would like to be able to select a different time frame for the heatmap (like we do for insights).

![heatmap](https://user-images.githubusercontent.com/5864173/92240529-62dc8600-ee82-11ea-8739-e24564fed37e.png)

## Describe alternatives you've considered
Trying to obtain similar information with insights charts.

**Comment by mariusandra** [comment]
We actually have a heatmap timeframe now!

Just one PR was needed to fix a bug I just now found: https://github.com/PostHog/posthog/pull/4739

Closing this issue.
