### ISSUE TITLE
SMTP 500 Error When Using Amazon SES

### ISSUE THREAD

**Issue by shogunpurple** [PostHog/posthog#1578]
## Bug description

*Please describe.*  
I am trying to set up SMTP integration with my self-hosted posthog instance in AWS. I believe I have configured it correctly, but I'm getting a 500 error from the server when trying to reset my password.

## Expected behavior
I should receive a password reset email.

## How to reproduce
- Configure an Amazon SES verified email address (the following describes what AWS says the SMTP settings should look like
![Screenshot 2020-09-04 at 17 33 54](https://user-images.githubusercontent.com/11256663/92263623-d0190700-eed4-11ea-8d38-0d76d4c57352.png)
- Configure posthog environment variables in ECS to look like the following
![image](https://user-images.githubusercontent.com/11256663/92263502-a2cc5900-eed4-11ea-80fa-cccca6867d0a.png)
- Try to send email from forgot password page
- This is the result
![Screenshot 2020-09-04 at 17 27 29](https://user-images.githubusercontent.com/11256663/92263143-128e1400-eed4-11ea-917c-20e2f18f061b.png)

## Environment
- Self-managed
- 1.13.0 

## Additional context
- I could not see any logs in cloudwatch apart from the initial server startup/migration logs, so I'm not sure how to debug this 500 error. How can I see the error log?

**Comment by timgl** [comment]
That's very strange! We tend to recommend signing up for a free [sentry](https://sentry.io) account and passing the sentry dsn as `SENTRY_DSN` variable. Then you should be able to see the error!

If you quickly want to change passwords, you can also run `python manage.py changepassword [email]` to replace it in the command line.

**Comment by shogunpurple** [comment]
Thank you - I set up sentry and when the error came through I realised that I had to verify the **to** email address that I was trying to send to in SES. Forgot you can't just verify the from address. 

We are big fans of posthog at our startup - keep up the good work on an awesome product :)

Thanks again for the help.
