### ISSUE TITLE
Dashboard Filters Cleared When Changing Date Range

### ISSUE THREAD

**Issue by meikitanious** [PostHog/posthog#15798]
## Bug description

Filters at the dashboard level are cleared when a user selects a new date range. 

This only happens when the dashboard is initially loaded. Once the filters are cleared, new filters can be added and they will not be cleared when changing the date until you exit out and re-enter. This also does not happen when initially creating the dasboard.

[Link to screen recording here.](https://drive.google.com/file/d/1WfklnwmprjzXyW4o58XU015Ms9GlDDk4/view).

[Link to dashboard with issue on Posthog Cloud](https://app.posthog.com/dashboard/76593).

## How to reproduce

1. Open the dashboard link I sent
2. Try changing the date range 

If there isn't an active filter on the dashboard; add one, exit the Posthog session, then repeat the steps.

## Environment

PostHog Cloud US, project ID: 25202

## Additional context
We know a temporary solution is to set filters at the insight level. However, this is not ideal for the following reasons:

1. It creates redundant insights (most of these insight reports are reusable)
2. It creates more maintenance in managing all the different filters for a single dashboard.

**Comment by yakkomajuri** [comment]
Fix on the way!

https://github.com/PostHog/posthog/pull/15821
