### ISSUE TITLE
One app's `setupPlugin` thowing an exception kills plugin-server

### ISSUE THREAD

**Issue by xvello** [PostHog/posthog#15942]
## Bug description

Exceptions thrown by `setupPlugin` are not properly caught and bubble up to the `uncaughtException` event handler, triggering a shutdown.
Expected behaviour is that the call is retried then disables the app. That's the behaviour that happens when the function rejects its promise.

[Other app callbacks](https://github.com/PostHog/posthog/blob/4cd5447f0eb9ebcf549d4122f718324df4733a0f/plugin-server/src/worker/tasks.ts#L14C2-L25) are wrapped in the `runPluginTask` helper that probably handles these. The code path to `setupPlugin` does not, and could use the same error handling logic.

## How to reproduce

1. Setup an app so that `setupPlugin` throws an exception instead of rejecting the promise (can reproduce with the Postgres app, if `?ssl=off` is added to the DB URL
2. Enable the app and have event go through for the app
3. The [`uncaughtException` event handler](https://github.com/PostHog/posthog/blob/bece269c32509cd207bfa1809cd3eb2834b86a0c/plugin-server/src/main/pluginsServer.ts#L187-L205) is called and kills the process, bypassing [the try/catch logic](https://github.com/PostHog/posthog/blob/135072a98cd1fb4ba3e1d6a2cef3b8caca505f9f/plugin-server/src/worker/vm/lazy.ts#L251) in `_setupPlugin`

## Environment

- [ ] PostHog Cloud US, project ID: [please provide from https://app.posthog.com/project/settings#project-id]
- [ ] PostHog Cloud EU, project ID: [please provide from https://eu.posthog.com/project/settings#project-id]
- [ ] PostHog Hobby self-hosted with `docker compose`, version/commit: [please provide]
- [ ] PostHog self-hosted with Kubernetes (deprecated, see ["Sunsetting Kubernetes support"](https://posthog.com/blog/sunsetting-helm-support-posthog)), version/commit: [please provide]

**Comment by xvello** [comment]
Disabling the `uncaughtException` handler gets the `setupPlugin` call to timeout and the app disabled:

![image](https://github.com/PostHog/posthog/assets/6241083/79d51fa3-4ce8-4116-80cd-b78733568b9b)

This means that the overall retry/disable flow is working, but that the exception does not properly propagate to it. VM2 issues I assume?

**Comment by hazzadous** [comment]
@xvello can you provide the `setupPlugin` definition you are using here?

**Comment by xvello** [comment]
> @xvello can you provide the `setupPlugin` definition you are using here?

I can reproduce with the https://github.com/PostHog/postgres-plugin app: set it up with a valid database URL to a Neon/RDS instance, and add `?ssl=off` at the end of that URL to trigger a runtime error [at this line of the pg lib](https://github.com/brianc/node-postgres/blob/master/packages/pg/lib/connection.js#L90). Paul opened [a PR to try/catch around the connect call](https://github.com/PostHog/postgres-plugin/pull/9/files) but it still fails in my devenv.

I'm trying to get a simple reproduction case, but the example app below does not take down the plugin-server: the same exception is caught and disables the app with the following log line:

>  ⚠️ Failed to load plugin exception testing ID 4 (organization ID 0188961f-ec93-0000-e55e-2d00231a51de). SetupPluginError: setupPlugin failed with TypeError: Cannot use 'in' operator to search for 'bar' in null for plugin exception testing ID 4 (organization ID 0188961f-ec93-0000-e55e-2d00231a51de). Disabled the app!

```js
import { Plugin, PluginMeta, PluginEvent } from '@posthog/plugin-scaffold'

export const setupPlugin = async (meta) => {
    const foo = null
    'bar' in foo
    throw new Error('fail setup')
}

export async function exportEvents(events: PluginEvent[], meta) {
    throw new Error('fail export')
}
```

Looks like the PG client is making something that gets this exception to escape the typical exception handling flow.

**Comment by xvello** [comment]
Adding more debug logs, I can confirm that:

- [processUnhandledException](https://github.com/PostHog/posthog/blob/4cd5447f0eb9ebcf549d4122f718324df4733a0f/plugin-server/src/worker/worker.ts#L98) is properly triggered, but does not bubble up the app error: seems like it cannot find the right pluginconfig ID in the stack  ->  we fail on the timeout guard instead of the exception, making debugging difficult
- [the main event listener](https://github.com/PostHog/posthog/blob/bece269c32509cd207bfa1809cd3eb2834b86a0c/plugin-server/src/main/pluginsServer.ts#L187-L205) is triggered and exits the process. The comments on it indicate it's been added to catch graphile errors. We should investigate a way to either:
  - catch it on a more focussed scope (not the whole process)
  - alternatively, don't exit here, but fail a liveness probe if the graphile worker is in an unhealthy state

**Comment by hazzadous** [comment]
Argh. Yeah so my preference would be that we implement and use liveness probes as this should hopefully give a more definitive signal that something isn't working. I was adding that [here](https://github.com/PostHog/posthog/pull/15491) although lost some steam.

Re. not bubbling up, it's just not in the call stack rather within an event handler so that makes sense.

I'll revisit the liveness checks but fall back to more focussed scope if that proves fiddly. But first I need to reproduce in a simple way 😱

**Comment by xvello** [comment]
PG and SF plugins have been deprecated in favor of batch exports, reducing. The underlying issue about unhanded exceptions bubbling up still exists, but we're shrinking down the likelihood of a repeat by reducing the amount of libs exposed to apps and auditing the rest. Eventually, we'll want to switch app runtimes to completely remove this, but it'll be tracked elsewhere.
