### ISSUE TITLE
HogQL insight works with Dashboard filters

### ISSUE THREAD

**Issue by timgl** [PostHog/posthog#15999]
## Is your feature request related to a problem?

If I add a filter to a dashboard, or change the timeline,  I want my HogQL insight to be filtered by that filter too.

## Describe the solution you'd like

HogQL queries get filtered down. Either more explicitly by defining it:

```sql
SELECT * FROM events WHERE {event_filters}
```

or maybe just automagically?

**Comment by mariusandra** [comment]
The first step towards this was done here: https://github.com/PostHog/posthog/pull/15973

Regarding automagically, I'd love this to work, but our internal discussion concluded that this may be too tricky. E.g. subqueries to answer questions like "was this the first time the user performed $event" might have a longer time range than the "last 30 days" range the answers are calculated for.

Thus we'll at least need an opt out, such as `SETTINGS ignore_dashboard_filteres=true` at the end of the HogQL query.

However my vote goes for:
1. Add the same row of filters (24h timerange + property filter) that are on dashboards into the SQL insight editing view.
2. Add `AND {event_filters}` as part of the default query when you open the SQL insight tab. This would teach people about this feature, and how to make their custom insights "dashboard compatible".
3. Update the `HogQLQuery` node to take an optional `{ event_filters: { properties, date_from, date_to } }` parameter

**Comment by ithinkwong** [comment]
Potential related Issues / PRs:

- [feat(hogql): add to dashboard filters](https://github.com/PostHog/posthog/pull/15562): This pull request addresses a similar issue where users wanted to filter by SQL on the dashboard. The changes made in this pull request add the missing HogQL filter, which allows users to filter the results of the graphs. This could be helpful in understanding how to implement the desired feature of filtering HogQL insights based on dashboard filters.

This message was generated by AI from www.triagetickets.com

**Comment by putriapriandi** [comment]
for HogQL Table,  I have already input it into the dashboard, but I cannot use the filters General available in the dashboard. Even though I have written the query as WHERE {filters}.

**Comment by Twixes** [comment]
HI @putriapriandi, that doesn't sound right! Can you link to the insight here, so that we can investigate? (No worries, only us at PostHog will be able to do anything with this link)

**Comment by Twixes** [comment]
Closing as I believe all insights should now work (let us know if that's not the case!)

**Comment by abrambailey** [comment]
Hi, I'm trying to do this and not sure how. {filters} and {event_filters} both unresolved when querying hog-managed mysql db.

**Comment by joumanam** [comment]
same issue here! 
@abrambailey did you find any solution?

**Comment by hervenivon** [comment]
For those stumbling upon here. It is now feasible. You can create variables and request them.

<img width="598" height="437" alt="Image" src="https://github.com/user-attachments/assets/88f93ea4-efe3-478f-b7f7-3ea8a4b2b41f" />
