### ISSUE TITLE
Breakdown trends view by minute/hour/day/week

### ISSUE THREAD

**Issue by timgl** [PostHog/posthog#16]
At the moment it's only broken down by day.

Should be a fairly simple change as the API supports this with some small tweaks.

**Comment by jamesefhawkins** [comment]
To clarify, this applies to https://app.posthog.com/actions/trends.

At the moment, they are grouped into the days. 

It'd be nice to see hourly trends, for example.

**Comment by eLRuLL** [comment]
I see there is already support down to the minute:
<img src="https://user-images.githubusercontent.com/1459486/80212219-b7324800-85fc-11ea-976d-539f66c8de13.png" width="400" />

Is there more things to do on this issue or maybe this is related to a different problem?

**Comment by timgl** [comment]
Yep this is already done
