### ISSUE TITLE
Sentry full of posthog errors from _createForOfIteratorHelper(posthog-js/dist/es)

### ISSUE THREAD

**Issue by Kameecoding** [PostHog/posthog#16008]
## Bug description

*Please describe.*  
*If this affects the front-end, screenshots would be of great help.*  

For 3 months now  (exact date: Mar 28, 2023 16:03:05 CEST) we have thousands of errors recorded in our Sentry instance.

I have examined our codebase around this time and we had no changes that should/could cause this so this might be some issue with a posthog release 

```
TypeError
undefined is not an object (evaluating 't[Symbol.iterator]')

...
271  function _createForOfIteratorHelper(o, allowArrayLike) {
272    var it = typeof Symbol !== "undefined" && o[Symbol.iterator] || o["@@iterator"];
 
...
  
 
```

 If it helps i can screenshot the whole stacktrace

## How to reproduce

1. can't help with this, happens all over our site https://joszaki.hu

## Environment

- [ ] PostHog Cloud US, project ID: [please provide from https://app.posthog.com/project/settings#project-id]
- [x] PostHog Cloud EU, project ID: 1497
- [ ] PostHog Hobby self-hosted with `docker compose`, version/commit: [please provide]
- [ ] PostHog self-hosted with Kubernetes (deprecated, see ["Sunsetting Kubernetes support"](https://posthog.com/blog/sunsetting-helm-support-posthog)), version/commit: [please provide]

**Comment by pauldambra** [comment]
Hey @Kameecoding, 

The full stack trace would be great. 

Could you include what version of posthog-js you are using?

What do the Sentry tags show about the error? Is it a specific browser for example?

**Comment by pauldambra** [comment]
Ah, I can see on the site that you're on version 1.45.1 which is pretty far behind. Current version is 1.67.1

https://github.com/PostHog/posthog-js/blob/master/CHANGELOG.md

I'd recommend you update at last one of the 1.6x.x releases was to deal with reported bugs in older versions of safari for example

**Comment by Kameecoding** [comment]
thank you, it seems the version upgrade has helped
