### ISSUE TITLE
HogQL breakdown expressions should be editable

### ISSUE THREAD

**Issue by thmsobrmlr** [PostHog/posthog#16071]
## Is your feature request related to a problem?

When writing a HogQL query, I should be able to click it again to edit what I have already wrote rather than having to click "x" and to start over.

<img width="224" alt="Screenshot 2023-06-15 at 12 01 47" src="https://github.com/PostHog/posthog/assets/1851359/b43ee1c2-5bd0-4a2e-bbd5-5d8bf284159b">

## Additional context

https://posthoghelp.zendesk.com/agent/tickets/3602

**Comment by MarconLP** [comment]
Has been fixed in https://github.com/PostHog/posthog/pull/17126
