### ISSUE TITLE
Long HogQL expressions for breakdowns break layout

### ISSUE THREAD

**Issue by thmsobrmlr** [PostHog/posthog#16070]
## Bug description

Long HogQL expressions for breakdowns break the layout.

<img width="1131" alt="Screenshot 2023-06-15 at 11 50 21" src="https://github.com/PostHog/posthog/assets/1851359/b69db49d-0e91-41cb-9373-b48591dd95f7">

## How to reproduce

1. Add a HogQL expression as breakdown for a funnel or trends insights
2. See that the layout breaks, especially for funnels with three series where you can't click the "x" to remove the breakdown

Example:
```
ifNull(null, ifNull(null, ifNull(null, ifNull(null, ifNull(null, ifNull(null, ifNull(null, ifNull(null, ifNull(null, ifNull(null, ifNull(null, ifNull(null, ifNull(null, ifNull(null, ifNull(null, ifNull(null, ifNull(null, '')))))))))))))))))
```

## Additional context

https://posthoghelp.zendesk.com/agent/tickets/3584

**Comment by MarconLP** [comment]
Has been fixed in https://github.com/PostHog/posthog/pull/17126
