### ISSUE TITLE
Erroring insights should display error message instead of empty state

### ISSUE THREAD

**Issue by thmsobrmlr** [PostHog/posthog#16091]
## Bug description

Backend errors are swallowed by the funnel insight and an empty state is displayed instead

## How to reproduce

1. Open a funnel insight
2. Throw an exception on the backend funnels endpoint
3. Observe that an empty state is displayed instead of the error

## Additional context

This is likely a data exploration issue, where the legacy code path is in conflict with the error state from `dataNodeLogic`.

**Comment by Twixes** [comment]
This should now be the case everywhere.
