### ISSUE TITLE
Invite team members via email

### ISSUE THREAD

**Issue by paolodamico** [PostHog/posthog#1611]
## Is your feature request related to a problem?
#1562 introduces creating invites for a specific email address (team member), however the invite link needs to be shared offline.

## Describe the solution you'd like

I would like us to automatically send an invite email to the recipient (if the instance has email capabilities enabled) instead of showing the invite link to the inviting user. We would still show the invite link if the instance has no email capabilities.

## Implementation details
- Send an email (preferred HTML design below but plain text is fine) to the new user with a link to create their account.

![screenshot](https://user-images.githubusercontent.com/5864173/93870289-e68cd400-fcc4-11ea-9d8c-086e05fc5c51.png)

- If the user is joining with a link that was sent directly to their email address, the email address would already be pre-filled in the signup form.
- We would also track in the "user signed up" event how the user signed up (direct email or shared invite link)

**Please remember to add tests!**

## Describe alternatives you've considered
Do nothing.

## Additional context
Doing this will also bring the following benefits:
- Better follow-up to users that are invited but do not sign up.
- Enable fast inviting through G-Suite directory sync (and/or other similar integrations).
- Improve our process for internal referrals.
- We indirectly validate the email address of the invited users.
- Set role/permissions before an account is created.

**Comment by Twixes** [comment]
This is something I plan to do with the new organization structure, to make that flexible and allowing for a use case like this (an `OrganizationInvite` model/table instead of `Organization.signup_token`).

**Comment by paolodamico** [comment]
Updated description to reflect changes from #1562.
