### ISSUE TITLE
Sprint June 26 to July 7

### ISSUE THREAD

**Issue by mariusandra** [PostHog/posthog#16168]
# Global Sprint Planning

## 3 things that might take us down

1. Prod US kafka is getting hot, peak hours getting peakier. Upscaling tomorrow morning.
2. Launching data warehouse this week to some select beta users. Potential network saturation or big queries.
3. Big customer updating 3m properties/day. EU clickhouse might not be keeping up
4. Deprecating posthog-cloud. Tomorrow dev will run, then will add to prod on friday.

## Retro: What can we do better next sprint?

1. 
2.
3.
5.
6.

# Team sprint planning

For your team sprint planning copy this template into a comment below for each team.

```
# Team ___

**Support hero:** ___

## Retro

<!-- Grab the high and low priority items from last time and add whether that item was completed or not -->

- 

## Hang over items from previous sprint

<!-- For each item, decide to re-prioritise (and add below) or deprioritise -->

- Item 1. prioritised/deprioritise

## OKR

1. OKR, status (red/yellow/green) and action points if yellow/red


### High priority

-

### Low priority / side quests

-

```

**Comment by mariusandra** [comment]
# Team Product Analytics

**Support hero:** @Twixes and @thmsobrmlr 

Marius is off the 2nd week of the sprint.

## Retro

- Marius: support's been heavy again. Deep issues to dig in to, but managing.
- Thomas: support and still ongoing data exploration
- Michael: finally shipped new stuff with 3000 navigation. Just 2 steps away from releasing this to us. Also dug into HogQL. Looked into support issues.
- Yakko: bunch of multi-front CH stuff. HouseWatch !!! 

## Hang over items from previous sprint

- HogQL post-beta [shortlist](https://github.com/PostHog/meta/issues/81) & PoEv2 [next steps](https://github.com/PostHog/meta/issues/81) @mariusandra 
- Proper `null` support and materialized columns @thmsobrmlr  ([slack thread](https://posthog.slack.com/archives/C0368RPHLQH/p1685047495690929), [older context](https://github.com/PostHog/posthog/pull/14185#discussion_r1112932704)) 

## OKRs Q2

- 🔴 Objective 1: PostHog 3000 Hacker News launch is a wild success
- 🟡 Objective 2: Make PostHog performance frustration free for our 10 largest customers
- ✅ Objective 3: HogQL

### OKRs Q3

- Check them out: https://github.com/PostHog/posthog.com/pull/6157/files

### High priority

- Continue with [HogQL improvements](https://github.com/PostHog/meta/issues/81) & PoEv2 & support tickets @mariusandra 
- Continue with [Data Exploration](https://github.com/PostHog/meta/issues/84) and support tickets @thmsobrmlr 
- Continue with [PostHog 3000 navigation TODOs](https://github.com/PostHog/posthog/issues/18090) and support tickets @Twixes 


### Low priority / side quests

- Custom SQL columns
- [Rewrite HogQL in rust](https://chat.openai.com/share/e2b9b106-b7ba-4f1b-b5fb-fd7d9e16c10a)

**Comment by benjackwhite** [comment]
# Next sprint - Team Notebooks 

**Support hero:** @pauldambra, then @benjackwhite 

## Retro
(Will do this in person next week!)

## Hang over items from previous sprint

- Newer simplified blob ingestion flow using new infra (kafka + redis) ✅
  - Possibly by end of week this is up and running fully (so far looks very very good) 
- Notebooks 
  - inline editing of insights and queries ✅
  - recording notes controls ❌
  - list of mini-bugs ✅

## Goals
* Goal 1 : Finish the 80:20 of session recording 🟡
  * Realistically we need separate infra to do this right (Kafka + redis) and removal of chunking logic.
* Goal 2 : Notebooks MVP 🟢

### High priority
- Strong alignment on Q3 goals and onboarding @benjackwhite @pauldambra 
- Notebooks, notebooks, notebooks - (based on Q3 outcomes)

### Low priority / side quests
- Monitor rollout of S3 ingestion

**Comment by raquelmsmith** [comment]
# "Team" Growth

**Support hero:** Me

## Retro


- [x] Remove the old billing UI
- [x] Decide on new pricing and migrate existing/prior customers who are on old pricing.
  - Make an announcement
  - In progress, will make announcement next week
- [x] ~Experiment: Directly ask people what they are signing up for in the signup form https://github.com/PostHog/posthog/issues/15531~
  - ~Will also give us data about who we should be tracking for activation into the products~
  - I can't think of a good place to put this and have just decided to work on product-specific onboarding instead
- [ ] Mock up a product-specific onboarding flow for eg. Feature flags or Experiments
  - In progress

## OKR

1. We can easily run experiments on pricing 🔴 
    - Won't get to this this quarter.
2. Each paid product is positioned as a first-class citizen within our onboarding and upgrade flows 🟡 
    - I think I can make good progress toward this by the end of the quarter. We’re now in a good spot to do this since the switch to separate upgrades per product is done.
    - Planning issue: https://github.com/PostHog/posthog/issues/15651

## This sprint
### High priority
- [ ] Launch feature flags pricing
- [x] Decide on new pricing and migrate existing/prior customers who are on old pricing.
  - [x] Make an announcement
  - Finish this
- [ ] Mock up a product-specific onboarding flow for eg. Feature flags or Experiments
  - And start working on it
- [x] CS requests:
  - [x] Handle new startup credits situation
  - [x] Make Enterprise trials a thing 


### Low priority / side quests

- [ ] Create modal for prompting to upgrade to addons when sub-ing to a main product
- [ ] Improve modal for upgrading to paid features
  - Let them subscribe in the modal
  - Tell them which product they need

**Comment by neilkakkar** [comment]
# Team Feature Success

**Support hero:** @liyiy  


## Retro

1. Polish & make ready for general availability all 4 new features we've built (flag autocapture, early access, surveys, dashboard templates) -> everyone owns their feature polishing
    1. Flag autocapture: @neilkakkar been OOO more than expected, not enough progress
    2. Early access: @EDsCODE : Good to go as beta, but no growth & usage work since Eric has switched teams & priorities
    3. Surveys: @liyiy - this is going to be a big chunk of work, will be a Q3 focus, so not polished enough for general availability. Beta released though, and some early feedback incorporated.
    4. Dashboard templates: @EDsCODE : Good to go as beta, but no growth & usage work since Eric has switched teams & priorities

## Hang over items from previous sprint

Flag autocapture documentation + growth/usage/gathering feedback
Growth/usage/gathering feedback for early access & dashboard templates

## OKRs

1. 🟡 Make it easier for engineers to analyze the success of a feature
2. 🟢 Launch pricing for feature flags

### High priority

1. Survey customising appearances & emoji / nps rating survey type: @liyiy 
2. High priority experiments fixes: @neilkakkar - a.k.a make $big_customer and future small customers happy.

### Low priority / side quests

Flag autocapture: @neilkakkar 
Cohort bugs from support: @liyiy

**Comment by timgl** [comment]
# Team pipeline + infrastructure

**Support hero:** Frank for infra, Harry/Tomás for pipeline

## Retro



- Bit frustrating yesterday that on call was OOO yesterday
- Tiina: Runbook and dashboards for E2E ingestion lag is in a good place now
- Xavier: Really appreciate having the standups combined with infrastructure

## Hang over items from previous sprint



- Observability: Scale VictoriaMetrics and Grafana. @ellie
- Great dashboards for alerts for ingestion @tiina303 
- Splitting out helm chart @ellie
- One app taking everything down @hazzadous
- Updates data integrity @tiina303

## OKR

1. OKR, status (red/yellow/green) and action points if yellow/red


### High priority

- Investigate OOMs/tune RDKafka/Lazy setup for plugins @xvello 
- Kill prometheus @ellie
- Splitting out helm chart: have plugin-server deploys separated from the main app @danielxnj 
- Exports: shipping retries and backfills. Get Snowflake up to par. Maybe try to identify big users to move over @hazzadous
- Great dashboards for alerts for ingestion @tiina303 

### Low priority / side quests

- Updates data integrity @tiina303

**Comment by timgl** [comment]
# Team Data Warehouse
**Support hero:** ___

## Retro



- 

## Hang over items from previous sprint



- Item 1. prioritised/deprioritise

## OKR

1. OKR, status (red/yellow/green) and action points if yellow/red


### High priority

Keep the lights on
- Fix topology of EU clickhouse, either set up a couple of bigger nodes

Data warehouse
- Push out what Tim had demo'd earlier this week. 
- https://github.com/orgs/PostHog/projects/84/views/6

### Low priority / side quests

-
