### ISSUE TITLE
CI Speed

### ISSUE THREAD

**Issue by pauldambra** [PostHog/posthog#16213]
# CI speed

# Problem

CI takes a long time which is at best frustrating and at worst leads to higher WIP and larger changes both of which can cause problems.

## What am I ignoring

- docker image build time - there’s some other work looking at this
- number of GitHub action runners - increasing this would reduce queuing time but would be at least $500 a month
- size of GitHub action runners - increasing this can help but their running costs are super high and we burn through our credit in days
- self-hosted GitHub runners - let’s avoid managing more infrastructure if we can
- other CI environments - other people are looking at this e.g. https://github.com/PostHog/posthog/pull/15980
- reduce number of tests  - this could be a short term win but potentially removes useful tests, and the number of tests will continue to grow, so we end up back in the same place

## backend tests

[https://github.com/PostHog/posthog/actions/workflows/ci-backend.yml](https://github.com/PostHog/posthog/actions/workflows/ci-backend.yml)

## why slow?

- split into 5 chunks
- each takes 4-14 minutes ish
- we run a double matrix so each is run for the 4 combinations of EE or FOSS and PoE on vs off
- that’s a third of our runners per PR

## what could we do?

without reducing the number of tests or size of the matrix we run we have to focus on the speed of the tests

## Cypress

[https://github.com/PostHog/posthog/actions/workflows/ci-e2e.yml](https://github.com/PostHog/posthog/actions/workflows/ci-e2e.yml)

<img width="991" alt="Screenshot_2023-06-21_at_21 32 43" src="https://github.com/PostHog/posthog/assets/984817/dd660155-e46d-4d3e-85b3-f904752ef508">

- 23m overall
    - 3 or 4 minutes prep
    - then 10 chunks that take 20 minutes each
        - this is slower than when run locally

## what could we do?

- 
- move to playwright?
- investigate why they are so slow on CI
- ???

## Storybook

[https://github.com/PostHog/posthog/actions/workflows/storybook-chromatic.yml](https://github.com/PostHog/posthog/actions/workflows/storybook-chromatic.yml)

- publish to chromatic 6m
- 4 instances of visual regression tests 13 minutes each
    - 4m30 to build storybook
    - 5 minutes to run the tests

## what could we do?

- not build storybook every time
- increase speed of run?

reduce time spent building story book would save 7 minutes [https://github.com/PostHog/posthog/pull/16185](https://github.com/PostHog/posthog/pull/16185) (couple of tricky new flakes to resolve)

**Comment by mariusandra** [comment]
I welcome any initiative to improve our tests in any way! Even if just removing the docker compose logs when python fails ;).

> we run a double matrix so each is run for the 4 combinations of EE or FOSS and PoE on vs off

The EE an FOSS tests are totally separate. There might be _few_ EE ones that also include FOSS tests due to various reasons (e.g `class EEFunnelsTest(FOSSFunnelsTest)`), but that shouldn't be a widespread issue.

**Comment by pauldambra** [comment]
> The EE an FOSS tests are totally separate.

<img width="702" alt="Screenshot 2023-06-22 at 22 12 24" src="https://github.com/PostHog/posthog/assets/984817/04b4c3d2-2243-4114-8f5e-6b897974da97">

As far as the matrix goes they're not any faster or slower though. So we use 20 runners for 4-12 minutes. Run three PRs and that's every runner locked up

**Comment by pauldambra** [comment]
FYI @daibhin

**Comment by Twixes** [comment]
Will proactively close, but feel free to reopen if there's still something left you think is worth doing!
