### ISSUE TITLE
Quick dragging of Toolbar causes inadvertent selection in Safari

### ISSUE THREAD

**Issue by Twixes** [PostHog/posthog#1624]
## Bug description

As in the title, fast dragging causes some sort of content selection to kick in, resulting in weird flashes. Rather minor issue, _only_ happens in Safari, but maybe there's a fix. Demonstration:

![Drag](https://user-images.githubusercontent.com/4550621/92656494-714bf700-f2f3-11ea-9f22-b98a1bf5756e.gif)

Framerate got slashed here, but the issue should be visible.

## Expected behavior

Dragging without flashes.

## How to reproduce

1. Open a Toolbar-enabled site in Safari.
2. Drag the Toolbar around quickly.
3. Experience blue flashes.

## Environment

- PostHog 1.14

**Comment by pauldambra** [comment]
accidentally fixed at some point
