### ISSUE TITLE
Change icon for filtering session replays

### ISSUE THREAD

**Issue by corywatilo** [PostHog/posthog#16268]
Can we update the icon for filtering ~recordings~ replays to the standard filter icon instead of a search icon? It would make way more sense than search since you're in fact filtering and not actually searching. =]

<img width="986" alt="image" src="https://github.com/PostHog/posthog/assets/154479/1982567a-de01-40f4-a370-36c2b0ca8dec">

**Comment by benjackwhite** [comment]
We got indications that people didn't understand that was for filtering hence we changed it. We could change it back but the 3000 UI also will have a search icon when we move it there 🤔 ?

**Comment by pauldambra** [comment]
this was done...
