### ISSUE TITLE
Navigating away from a saved HogQL insight causes an error

### ISSUE THREAD

**Issue by thmsobrmlr** [PostHog/posthog#16281]
## Bug description

Navigating away from a saved HogQL insight causes an error

## How to reproduce

1. Go to the new insights scene, select SQL and save the insight
2. Navigate to another insight kind by clicking on the respective tab e.g. "Lifecycle"
3. Observe the following error

<img width="1215" alt="Screenshot 2023-06-28 at 11 58 13" src="https://github.com/PostHog/posthog/assets/1851359/039e6815-dd49-44ff-9b43-d19a24687107">

Might be related: https://posthog.slack.com/archives/C045L1VEG87/p1683718168101839

**Comment by MarconLP** [comment]
+1 https://posthoghelp.zendesk.com/agent/tickets/6412 (moved to PostHog: https://us.posthog.com/project/2/support/tickets/8802)
Also happening when switching from `custom` insights
