### ISSUE TITLE
Not supported for Angular 

### ISSUE THREAD

**Issue by danieldeepak1212** [PostHog/posthog#16298]
Configuring a posthog 
posthog is installed as a npm package ---> npm i posthog-js
added needed imports and code base for event tracking as mentioned in docs 
when try to run the server -- ng serve 

Error:
Cannot find module 'types' or its corresponding type declarations.
1 import { SurveyCallback as SurveyCallback$1 } from 'types';

![image](https://github.com/PostHog/posthog/assets/131849707/20f558ec-8c02-48d0-a78e-1447e7e1ef25)

I tried to install types but failed --- npm i --save-dev @types/posthog-js

**Comment by neilkakkar** [comment]
Hey @danieldeepak1212 this should be fixed in the latest version!
