### ISSUE TITLE
Surveys Megaissue

### ISSUE THREAD

**Issue by liyiy** [PostHog/posthog#16374]
### High priority (ordered by priority)

- [x] Visualise quantitative data
- [x] Radio button / multiple choice question types
- [x] Exclude users from targeting who have already seen a survey
- [x] 'Thank you' toast after responding
- [x] Calculate Net Promoter Score
- [x] Tests on surveys app repo
- [x] Multiple questions
- [x] Polish UI based on Cory's wireframes: https://github.com/PostHog/posthog/issues/16018
- [ ] https://github.com/PostHog/posthog/issues/17038
- [x] Templates
- [x] Surveys as a new product on the website (add to the onboarding flow)
- [x] Surveys in app onboarding flow

### Quick wins do complete alongside sprint goals

- [x] Restarting a survey
- [ ] Usability: Make it clearer you can’t add a behavioural cohort, update error message to say surveys, not flags
- [ ] Usability: Make it clearer how targeting by flag works
- [x] Usability: Make it clear that URL filter means contains
- [ ] Usability: Make selector flag clearer, on actions we have more text and a link to the docs
- [x] Product intro for surveys  (done, but we should get art from Lottie and link to the docs)
- [x] Help users debug why their survey is not showing, e.g. detect site app setup, popup shown etc
- [x] Remove “powered by PostHog” for paying users

### Nice-to-have's, side quests for sprints

- [ ] Exporting data
- [ ] Slack notifications
- [ ] Hit web hook after successfully completing survey (in this case to incentivise users for completing)
- [x] Support regex for page url contains
- [ ] Bug report question type: Includes session ID, connection to screen recording they also have in PostHog, sends Slack notification
- [ ] Surveys for mobile
- [x] Cory + Eli site app styling 2.0 + Define design for survey popup in a global place
- [ ] qualitative data exposure on ff/experiments/feature success -> make this part of feature success

### Useful but complex, work on other high-priority issues first

- [ ] branching logic, e.g. depending on rating scale, show different set up follow up questions
- [ ] behaviour-based targeting

### Won't do for now

- [ ] Schedule for surveys, e.g. sending it every 6 months ”set it and forget it”
- [x] Position survey in different spots
- [ ] Product tours, highlight what’s new survey type
- [ ] Handle popups from multiple vendors, e.g. what happens if you have PostHog and Intercom set up?
- [ ] Multi-language support
- [ ] Survey hierarchy, e.g. if the user is eligible for multiple, which one should he get
- [ ] Full-screen surveys

Link to original RFC: https://github.com/PostHog/product-internal/pull/483
Link to original issue: https://github.com/PostHog/posthog/issues/15375

PROJECT BOARD LINK: https://github.com/orgs/PostHog/projects/87

**Comment by annikaschmid** [comment]
Feedback from @pauldambra: 

I stopped a survey in the EU but I expected to be able to start it again :see_no_evil:
Would be great to be able to duplicate it or restart it :chart_with_upwards_trend:

the URL was pre-filled when I made a new version  of it.
Useful in this instance but probably incorrect

(and then the tiniest of nits - when I clicked save both the save and the cancel buttons showed a loading spinner - very nitty but my brain had already shifted into feedback mode so :shrug:)

Original convo: https://posthog.slack.com/archives/C034XD440RK/p1688721246388589

**Comment by annikaschmid** [comment]
@liyiy A couple of weeks ago, I made a list with UX improvements from my own testing. Could you go over it and tick off what is done / we won't do / what is on your list, so that we can close the issue? Thanks! https://github.com/PostHog/posthog/issues/16018

**Comment by raquelmsmith** [comment]
A user shared in the [community slack](https://posthogusers.slack.com/archives/C01GLBKHKQT/p1688751528980129?thread_ts=1688742701.388439&cid=C01GLBKHKQT):

> Ok! I think event based targeting is pretty fundamental for surveys. For example, we want to be able to target people who have searched three times on our website for something. So being able to say, if someone has done this thing x number of times, show a survey. Common use case--if a customer is doing something a bunch of times, you might want to know why.

**Comment by joethreepwood** [comment]
I'm keeping an eye (and commenting here to get further updates) but would also be good to align some content with this as we go so we can do some more marketing support. Would love to get some sneak peeks, changelogs, twitter threads and tutorials out as this feature firms up. I think it's a really, really strong differentiator and want to support it as much as I can.

**Comment by annikaschmid** [comment]
Link to Cory's wireframes: https://github.com/PostHog/posthog/issues/16018
