### ISSUE TITLE
Sprint July 10 to July 21

### ISSUE THREAD

**Issue by thmsobrmlr** [PostHog/posthog#16382]
# Global Sprint Planning

## 3 things that might take us down

1. Clickhouse knowledge
2. Incidents across EU and US

## Retro: What can we do better next sprint?

1. 
2.
3.
4.
5.

# Team sprint planning

For your team sprint planning copy this template into a comment below for each team.

```
# Team ___

**Support hero:** ___

## Retro

<!-- Grab the high and low priority items from last time and add whether that item was completed or not -->

- 

## Hang over items from previous sprint

<!-- For each item, decide to re-prioritise (and add below) or deprioritise -->

- Item 1. prioritised/deprioritise

## OKR

1. OKR, status (red/yellow/green) and action points if yellow/red


### High priority

-

### Low priority / side quests

-

```

**Comment by thmsobrmlr** [comment]
# Team Product Analytics

**Support hero:** @mariusandra

Michael is off 12-14th

## Retro

- Marius: A lot of PR watering. Action matching HogQL bytecode (almost?) ready.
- Michael: Continued progress on [PostHog 3000 navigation](https://github.com/PostHog/posthog/issues/18090) and support tickets.
- Thomas: Continued progress on [Data Exploration](https://github.com/PostHog/meta/issues/84) and support tickets

## Hang over items from previous sprint

- HogQL post-beta [shortlist](https://github.com/PostHog/meta/issues/81) & PoEv2 [next steps](https://github.com/PostHog/meta/issues/81) @mariusandra 
- (Proper `null` support and materialized columns @thmsobrmlr  ([slack thread](https://posthog.slack.com/archives/C0368RPHLQH/p1685047495690929), [older context](https://github.com/PostHog/posthog/pull/14185#discussion_r1112932704)))

## OKR

See [details here](https://github.com/PostHog/posthog.com/blob/7d03ec6b5a47a8ec39a9fa3c1fecc0830abe5de7/contents/handbook/small-teams/product-analytics/objectives.mdx).

- 🔵 Objective 1: Port all our insights over to HogQL.
- 🔵 Objective 2: Sleeker insight editor UI

### High priority

- Continue with https://github.com/PostHog/posthog/issues/18090 @Twixes 
- Continue with https://github.com/PostHog/meta/issues/84 and fixes for outstanding issues

### Low priority / side quests

- Get to the bottom of a backend-side caching / query calculation issue where users see empty results @thmsobrmlr

**Comment by pauldambra** [comment]
# Next sprint - Team Noteblobs 

**Support hero:** @pauldambra, then @pauldambra 
(we're switching to a two week rotation aligned with sprint so one person is always on support + sidequests while the others focus)

## Retro
* we met in Cambridge, we laughed, we drank, we pizza'd

## Hang over items from previous sprint

- ✅ Strong alignment on Q3 goals and onboarding
   - https://github.com/PostHog/posthog/issues/16287 
- ♻️ Notebooks, notebooks, notebooks - (based on Q3 outcomes)
   - added conflict detection, nicer links, and storybook testing as an amuse bouche
- 🪣 Monitor rollout of S3 ingestion
   - up to 100% of traffic in EU and US
   - monitoring realtime playback with PostHog team 

## Goals

 * 🎯 Goal 1 : Notebooks on ProductHunt 🟢
 * 🎯 Goal 2 : Next 5 great things for Replay 🟢

### High priority
- notebooks recording transcription mode @daibhin (with @benjackwhite)
- session recording user interviews @pauldambra and @daibhin 

(Ben is currently travelling to a Serbian rave) 

### Low priority / side quests
- blob playback on for all teams @pauldambra

**Comment by neilkakkar** [comment]
# Team Feature Success

**Support hero:** @liyiy  then @neilkakkar 


## Retro

1. Survey customising appearances & emoji / nps rating survey type: @liyiy  -> mostly sorted, chose interview survey type over emoji/nps
2. High priority experiments fixes: @neilkakkar - a.k.a make $big_customer and future small customers happy. -> Did a bit of priority juggling, got the most high priority experiment fixes sorted, while also working on moving decide to the read replica, because I realised decide read replica testing might take a bit longer, so front loaded it.


## Hang over items from previous sprint


## OKRs

1. 🟡 Make it easier for engineers to analyze the success of a feature (shall continue in Q3!)
2. 🔴 Launch pricing for feature flags (we'll launch in July, waiting for comms with existing big customers).

### High priority

1. General release of surveys +  emoji / nps rating survey type: @liyiy 
2. Remaining experiments fixes + decide on read replica: @neilkakkar

### Low priority / side quests

**Comment by timgl** [comment]
# Team Pipeline

**Support hero:** Tiina + Xavier
Xavier vacation first week, Tiina vacation second week + week after
Harry leaving second week

## Retro



- Investigate OOMs/tune RDKafka/Lazy setup for plugins @xvello > RDKafka is rolled back, need to investigate more. OOMs solved by throwing more memory at it. Shipped separate recording capture.
- Exports: shipping retries and backfills. Get Snowflake up to par. Maybe try to identify big users to move over @hazzadous > Shipped retries. We've got a backfill set up. Snowflake, need to tighten up retries etc but we're broadly in a good place.
- Great dashboards for alerts for ingestion @tiina303 > They exist. Worked on a lot incident follow ups, proactively making. 
- Luigi fairly busy

## Hang over items from previous sprint



- 

## OKR

- Defining limits on what users can send us
- Dodgy apps
  - Finish exports so we can deprecate export apps
  - Remove processing apps
- Figure out next 2 year architecture for pipeline
  - Figure out what our service levels should be

### High priority

- get inserted_at column out, best-effort deduplication, making exports discoverable, deprecate old apps @tomasfarias 
- Incident follow ups: break out onEvent/webhooks into separate consumers. Separate consumer for historical imports. Dashboard runbook follow ups @tiina303 

### Low priority / side quests

-

**Comment by raquelmsmith** [comment]
# "Team" Growth

**Support hero:** Me

I will be out the second week, July 17-21. Anyone want to volunteer to help with billing support?

## Retro
- [x] Decide on new pricing for product analytics and migrate existing/prior customers who are on old pricing.
  - [x] Make an announcement
- [ ] Mock up a product-specific onboarding flow for eg. Feature flags or Experiments
- CS requests:
  - [x] Handle new startup credits situation
  - [x] Make Enterprise trials a thing 
    - Should be done by end of week

## OKR

1. Starting to use and paying for new products feels frictionless
    - Status: 🟡 
    - Reasoning: We swung too far from plans (where there was only one upgrade to do) to individual product upgrades, so now starting to use an additional product feels unnecessarily friction-ful. We want to keep the benefits of the latter but the simplicity of the former.
    - [ ] KR: We have separate onboarding for each product
    - [ ] KR: People don’t have to “upgrade” to different products, they just turn it on or start using it in some way.
2. Customers can pay a reasonable price for the value they’re receiving
    - Status: 🟡 
    - Reasoning: We're charging too much for some products (eg product analytics) and too little for others (eg feature flags).
    - [ ] KR: Billing limits -> billing alerts
    - [x] KR: Make sure rollout of new product analytics pricing goes well
      - Mostly done
    - [ ] KR: Feature Flags pricing is launched, as well as Data Warehouse and CDP, if they are ready for launch

## This sprint
### High priority
- [ ] Get feature flags pricing ready for launch
- [ ] Mock up & start work on better upgrade flow for each product
- [x] CS: Get startup plan info into pocus https://github.com/PostHog/company-internal/issues/1060

### Low priority / side quests

- [ ] Mock up a product-specific onboarding flow for eg. Feature flags or Experiments

**Comment by EDsCODE** [comment]
# Team Data Warehouse

## Retro



- pushed out MVP
- Worked through rough edges around columns and table errors
- James: fighting fires, clickhouse cleanup

### High priority

Data warehouse
- Make joins work (this week)
- Internal use + 5 happy users for data warehouse
- MVP for person/group modeling

**Comment by ellie** [comment]
# Team Infra

## Retro
- Daniel: a lot of incident distractions but helm chart progress!
- Frank: 3 days on one incident, another one last week I don’t remember
- Ellie: Nice to see progress on the charts repo!

## Goals
- Overall goal: work on chart splitting issues! @ellie @danielxnj @frankh 
- Recovering data from CH @frankh 
- Spike upgrading postgres @danielxnj 
- Alerting wrap up (almost done) @ellie 
- Start moving terraform deployments over @ellie
