### ISSUE TITLE
Saving a funnel shows a blank page

### ISSUE THREAD

**Issue by corywatilo** [PostHog/posthog#16409]
## Bug description

After saving a new funnel, it shows "No matching events" even though it _does_ match data. After refreshing the page, the insight works.

<img width="1426" alt="image" src="https://github.com/PostHog/posthog/assets/154479/ee1b19ed-4147-4cfe-aac1-489cf77b22ba">

<img width="1387" alt="image" src="https://github.com/PostHog/posthog/assets/154479/5e0c9b82-95b1-4020-b3ad-177694f698dc">

## How to reproduce

1. Create a new funnel
2. Add a few events and give it a name
3. Hit save

(There are no console errors.)

![2023-07-06 12 21 07](https://github.com/PostHog/posthog/assets/154479/56f27c14-4dd6-4ee4-a402-f4c757a95c92)

**Comment by Arun-chaitanya** [comment]
@corywatilo I think it is working fine now. Seems like some one fixed it.

**Comment by thmsobrmlr** [comment]
Yep, this one is fixed as well. Thanks for the bump @Arun-chaitanya 🙌
