### ISSUE TITLE
Run insight query automatically on load (if it hasn't been refreshed in a while)

### ISSUE THREAD

**Issue by corywatilo** [PostHog/posthog#16408]
Problem: I loaded a saved insight and it appeared as if the data tracking was off as I expected to see a much higher count of users going through the funnel. (When I set it up 1 week ago, there were already 2 "conversions", meaning it appeared no data had been tracked since then.

<img width="1407" alt="image" src="https://github.com/PostHog/posthog/assets/154479/bd9e115a-b53d-4b0d-bd2c-5d363c1fb35b">

Then I noticed... "Computed 7 days ago" and no button to refresh it manually. I remember a conversation about trying to downplay the refresh button, but it seems like in a case like this (where the insight hasn't been recalculated in >X days), it should be done automatically when the insight is loaded.

Then after refreshing manually, the updated _computed at_ date says "Computed a while ago" which should really say "Just now

<img width="1387" alt="image" src="https://github.com/PostHog/posthog/assets/154479/6b44f4e8-1a54-4223-9ff8-f3e938701a6e">

## Requests

- [ ] Auto refresh an insight if it hasn't been calculated in >X hours days (24 hours?)
- [ ] Fix label when an insight is refreshed

**Comment by Twixes** [comment]
Yep, we're working on improving this (CC @thmsobrmlr)

**Comment by anirudhpillai** [comment]
This is fixed with #23978 now we issue an async refresh whenever an insight is viewed and the results are stale.
