### ISSUE TITLE
Retention filtering is broken

### ISSUE THREAD

**Issue by timgl** [PostHog/posthog#1642]
## Bug description

![image](https://user-images.githubusercontent.com/1727427/92770723-8596ff00-f39a-11ea-9b28-0e629ba7b857.png)

Trying to add filters/actions in retention is broken, probably some race condition

## Expected behavior

Should work, maybe using a calculate button like on funnels

## How to reproduce

1. Try adding filters or selecting a different action
2. 
3. 

## Environment

- PostHog cloud or self-managed?
- PostHog version/commit

**Comment by paolodamico** [comment]
Closing this as it's fixed on CH.
