### ISSUE TITLE
Add calculate button to Retention

### ISSUE THREAD

**Issue by yakkomajuri** [PostHog/posthog#1643]
## Is your feature request related to a problem?

*Please describe.*

Add a button to calculate retention instead of doing it automatically on a filter update. This will help prevent race conditions with retention queries.

Opening this up because the fix is a little longer than I anticipated so leaving this here as a note to myself to pick it up later when I actually have time or for someone else to pick it up.

## Describe the solution you'd like

Funnels-like 'Calculate' button.

## Describe alternatives you've considered

Leave as is

**Comment by EDsCODE** [comment]
I fixed the race condition with a breakpoint. Feel free to open it up again if you think calculate would be better overall or if it's ok the way it is now!
