### ISSUE TITLE
Sort / search actions

### ISSUE THREAD

**Issue by paolodamico** [PostHog/posthog#1648]
## Is your feature request related to a problem?

A user mentioned having many actions and it being very problematic to open a specific action. Affecting internally too.

## Describe the solution you'd like
I would like to be able to search actions by key, and sort them alphabetically (asc/desc).

## Describe alternatives you've considered
Browsing every page and using the browser's built-in search feature.

**Comment by Twixes** [comment]
Possible with the reworked Actions page.
