### ISSUE TITLE
Users displayed on clicking trend data point are incorrect

### ISSUE THREAD

**Issue by jamesefhawkins** [PostHog/posthog#1649]
## Bug description

Visit our internal app: 
https://app.posthog.com/insights?events=%5B%7B%22id%22%3A%22user%20signed%20up%22%2C%22math%22%3Anull%2C%22name%22%3A%22%24pageview%22%2C%22type%22%3A%22events%22%2C%22order%22%3A0%2C%22properties%22%3A%5B%7B%22key%22%3A%22is_first_user%22%2C%22type%22%3A%22event%22%2C%22value%22%3A%22true%22%2C%22operator%22%3Anull%7D%5D%2C%22math_property%22%3Anull%7D%2C%7B%22id%22%3A%22user%20signed%20up%22%2C%22math%22%3Anull%2C%22name%22%3A%22user%20signed%20up%22%2C%22type%22%3A%22events%22%2C%22order%22%3A1%2C%22properties%22%3A%5B%7B%22key%22%3A%22is_first_user%22%2C%22type%22%3A%22event%22%2C%22value%22%3A%22false%22%2C%22operator%22%3Anull%7D%5D%2C%22math_property%22%3Anull%7D%5D&interval=week&breakdown=%5B71%5D&date_from=-90d&breakdown_type=cohort#fromItem=589&fromItemName=First%20users%20vs%20invited%20users%20sign%20up&fromDashboard=267

* Click a data point: 

![Screenshot 2020-09-12 at 08 25 43](https://user-images.githubusercontent.com/47497682/92990139-8da58a80-f4d1-11ea-870b-d3c4d77538a1.png)

* Notice how on clicking this datapoint, the user number in this list is different

![Screenshot 2020-09-12 at 08 25 14](https://user-images.githubusercontent.com/47497682/92990134-7e264180-f4d1-11ea-95d4-fb024d439ce5.png)

* Also, data points from the two different lines repeatedly show the same list of users.

## Expected behavior

* Clicking a data point where it says ie 30 users, should show a list of 30 users.

**Comment by TechMastering1** [comment]
Fixed

**Comment by Twixes** [comment]
Not quite sure what you mean @TechMastering1?

**Comment by paolodamico** [comment]
Another case of this, hope this offers additional details to understand what's going on (all references here are from [this graph](https://app.posthog.com/insights?events=%5B%7B%22id%22%3A%22%24feature_flag_called%22%2C%22name%22%3A%22%24feature_flag_called%22%2C%22type%22%3A%22events%22%2C%22math%22%3A%22dau%22%7D%5D&breakdown=%24feature_flag_response&breakdown_type=event&display=ActionsLineGraph&interval=week&date_from=-90d&properties=%5B%7B%22key%22%3A%22%24feature_flag%22%2C%22value%22%3A%22actions-ux-201012%22%7D%2C%7B%22key%22%3A%22id%22%2C%22value%22%3A71%2C%22type%22%3A%22cohort%22%7D%5D)),

### Mismatch of users.
What's interesting here is that the 57 users that appear on the list of users, seems to match the numbers without applying the Real users cohort.
**Graph view:** 
    <img width="770" alt="graph" src="https://user-images.githubusercontent.com/5864173/100811188-a43bed80-33ff-11eb-82e9-8d76b050e406.png">
**Users view:**
    <img width="696" alt="users" src="https://user-images.githubusercontent.com/5864173/100811231-bd449e80-33ff-11eb-9be6-8d1d74b41ddb.png">

### Another case
Strangely contradicting the above, here's a case where the number does not match even without the users cohort.

**Graph view:** 
<img width="343" alt="" src="https://user-images.githubusercontent.com/5864173/100811539-760add80-3400-11eb-9b13-b5c8dd4e49b3.png">

**Users view:**
<img width="691" alt="" src="https://user-images.githubusercontent.com/5864173/100811543-786d3780-3400-11eb-879b-f9c44bb9a131.png">

**Without cohorts filter:**
<img width="1008" alt="" src="https://user-images.githubusercontent.com/5864173/100811562-8622bd00-3400-11eb-9f07-a299813977ae.png">

**Comment by paolodamico** [comment]
@EDsCODE seems like we have some of these instances happening, definitely think it would be worth prioritizing soon

**Comment by EDsCODE** [comment]
Any latest examples of this?

**Comment by paolodamico** [comment]
@EDsCODE I believe we can close this?
