### ISSUE TITLE
Deprecate feedback + user interview apps

### ISSUE THREAD

**Issue by liyiy** [PostHog/posthog#16495]
With the addition of [surveys](https://posthog.com/docs/surveys/manual), we should now be able to deprecate the existing feedback and user interview apps because:

1) Surveys offers the same solutions as a feature
2) There's no one maintaining those existing apps

We will be removing the apps completely **by Friday, July 14th** in order to give users some time to adjust.

TODO list:

- [x] Make the apps local so no additional users can enable it
- [x] Deprecate posthog.com docs for it
- [x] Send an email to existing users currently using the apps about the deprecation
     _This is an example of what I sent to the community slack:_ 

:trumpet: :exclamation: Hi folks! A heads up that the PostHog team will be deprecating our [feedback](https://github.com/PostHog/feedback-app) + [user interview](https://github.com/posthog/user-interview-app) apps by the end of this week as we’ve released a [new Surveys feature](https://posthog.com/docs/surveys/manual) that can handle both (and more).
- [ ] Remove app.posthog code that references it

**Comment by liyiy** [comment]
@joethreepwood

**Comment by joethreepwood** [comment]
@ivanagas @Lior539 Feels like, if we're deprecating the docs and the replacement will require some work from users then we should have tutorials from users covering how to achieve parity with Surveys.

I've deprecated the docs, or otherwise have PRs in motion for the rest. 

I'll spin up an email now for approval

**Comment by neilkakkar** [comment]
>  and the replacement will require some work from users

The only extra work for users now will be to create the survey to do what they want

**Comment by joethreepwood** [comment]
> > and the replacement will require some work from users
> 
> The only extra work for users now will be to create the survey to do what they want

Sure, but we'll have to guide them through that. May be a bit complex with an interview scheduler replacement? There's no way I can see with the current surveys beta to have anything other than a text field, for example. So I'm not sure how one would build something like this: 

<img width="487" alt="example" src="https://github.com/PostHog/posthog/assets/84011561/d5bab3d3-24bf-40d1-bdb6-565a8b8fd972">

**Comment by joethreepwood** [comment]
Wait, I stand corrected. I just missed the drop down button 🤣

**Comment by joethreepwood** [comment]
<img width="862" alt="Screenshot 2023-07-11 at 20 05 55" src="https://github.com/PostHog/posthog/assets/84011561/c5e5203d-4826-41f4-b2de-c295685da9fb">

Cohort all set up, so I can get an approval on this @neilkakkar and @liyiy then we should be ready to send tomorrow morning.

**Comment by liyiy** [comment]
looks good! thanks joe! 🚀

**Comment by joethreepwood** [comment]
This is now scheduled to send at 3PM today, BST.
