### ISSUE TITLE
Dial down analytics in JS

### ISSUE THREAD

**Issue by Tannergoods** [PostHog/posthog#165]
@timgl request from @nathanlawrence 

"The #1 interest I would have here would be in the ability to REALLY dial down all analytics to nothing, then slowly build up only the tiny things my team needed piece by piece. It looks like we could certainly do that ourselves with the API, but doing that in JS would be amazing."

Think there is something we can expand on here.

**Comment by timgl** [comment]
This is why we created the concept of 'Actions' in the first place. It means you can just capture everything without thinking about it. Then, when you want to know whether users are doing a certain thing, you can just create an action, suddenly making that data visible throughout PostHog.

Does that capture the use-case, or am I missing something?

**Comment by jamesefhawkins** [comment]
The verdict was that it's precisely the reverse - the reason for this request is from a user privacy perspective, it'd be nice to have the option not to autocapture everything all the time through the snippet. 

There is a viable workaround by using `posthog.capture` at this current time.

I'd suggest given the priority on some fundamental analytics (ie paths) capabilities, this is lower on the priority list. This will eventually become important. I could see very high event volume users needing it to reduce "wasted data" captured if the hosting is a challenge.

**Comment by timgl** [comment]
That makes sense -- I misunderstood. I think the actual solution to this is:

- Let users turn off autocapture
- They can then _just_ use `posthog.capture` to capture random events in the frontend.

I think if I build the ability to turn off autocapture, that would solve @NathanLawrence's usecase?

**Comment by glebcha** [comment]
I need nearly the same - ability to setup which events I want to capture and the list of elements to track without autocapture. The idea is to fine tune us client library.

**Comment by urbanc** [comment]
Anything new about that?

**Comment by urbanc** [comment]
My quick solution, for now, it's just to add a class to HTML body tag: `<body class="ph-no-capture">`. 
More info about `ph-no-capture class` [https://posthog.com/docs/integrations/js-integration#ignorecensure-elements](https://posthog.com/docs/integrations/js-integration#ignorecensure-elements).

You can still send custom events with `posthog.capture()` when you trigger it manually from JS.

**Comment by urbanc** [comment]
Autocapture can be disabled at init with a config option `autocapture`. 
Example:
```
posthog.init('sTMFPsFhdP1Ssg', {api_host: 'https://app.posthog.com', autocapture: false})
```

You might be interested in `capture_pageview` option.

For more config options check https://github.com/PostHog/posthog-js/blob/8b618e0b8e4f3a4767acf56387cf835e5cd251eb/src/module.d.ts#L519

**Comment by Twixes** [comment]
Right! Explanation for config options [here](https://github.com/PostHog/posthog-js/blob/8b618e0b8e4f3a4767acf56387cf835e5cd251eb/src/module.d.ts#L236-L324). This should allow some fine tuning. Say if you had something more specific in mind.
