### ISSUE TITLE
Support custom webhook

### ISSUE THREAD

**Issue by tuan3w** [PostHog/posthog#1650]
## Is your feature request related to a problem?
Thanks team for creating this useful product.  We previously developed our own tracking system. We use logs to make recommendation. Recently, we  intend to switch to posthog, because it provide more intuitive UI for us. However, we still want to access logging data to make recommendation.  I wonder  a bout solution to either forward logging from posthog to our service or access log from posthog backend.

**Comment by timgl** [comment]
@tuan3w Hey Tuan, we offer this as a service in our "Enterprise Package". Feel free to [contact us](mailto:sales@posthog.com) to enable this :)

**Comment by tuan3w** [comment]
Thanks for your information :).
