### ISSUE TITLE
Freshpaint.io integration

### ISSUE THREAD

**Issue by jjeremycai** [PostHog/posthog#1651]
## Describe the solution you'd like
Would love an integration with Freshpaint.io, which is an event tracking system similar to Segment. 

## Additional context
We considered several options and found Freshpaint the best for bootstrapped startups.

**Comment by timgl** [comment]
@jjeremycai Hey Jeremy, Freshpaint does something quite similar to us in terms of autocapture. Is there anything you're missing from the PostHog integration that you can get with Freshpaint?

I've also had a look at their docs but it doesn't look like there's a way for us to create an integration with them, so you'd have to ask them to integrate us :). Happy to help where I can!

**Comment by jjeremycai** [comment]
Hey @timgl ! Unlike PostHog, they capture and feed data to separate places (i.e. feed "FB Pixel Fired" to Facebook so we can better retarget). 

> I've also had a look at their docs but it doesn't look like there's a way for us to create an integration with them, so you'd have to ask them to integrate us :). Happy to help where I can!

I just pinged them to see if they'd be open to adding Posthog as an analytics destination

**Comment by timgl** [comment]
Yep I think that makes a lot of sense!

> I just pinged them to see if they'd be open to adding Posthog as an analytics destination

Great, let me know what they come back with. We've integrated with Sentry before so the integration shouldn't be too hard

**Comment by aantn** [comment]
I'm also interested in this.

**Comment by paolodamico** [comment]
We now have support for other data sources through plugins. @yakkomajuri where do we want to go from here?
