### ISSUE TITLE
[Session Recording] Network Requests never, console logs only sometimes collected

### ISSUE THREAD

**Issue by dbartholomae** [PostHog/posthog#16520]
## Bug description

We have both for Network Requests and Console logs enabled to collect them in the settings. None of our session recordings actually contain network requests, and some don't contain console logs either.

## How to reproduce

Look at a recording in our account.

## Environment

- [ ] PostHog Cloud US, project ID: [please provide from https://app.posthog.com/project/settings#project-id]
- [X] PostHog Cloud EU, project ID: 3703
- [ ] PostHog Hobby self-hosted with `docker compose`, version/commit: [please provide]
- [ ] PostHog self-hosted with Kubernetes (deprecated, see ["Sunsetting Kubernetes support"](https://posthog.com/blog/sunsetting-helm-support-posthog)), version/commit: [please provide]

## Additional context

We use Recorder V2

**Comment by pauldambra** [comment]
I replied in the internal bug report you raised, thanks
