### ISSUE TITLE
Hire Juraj Majerik as a Fullstack Engineer

### ISSUE THREAD

**Issue by jurajmajerik** [PostHog/posthog#16541]
**[https://posthog.jurajmajerik.com/](https://posthog.jurajmajerik.com/)**

## Is your feature request related to a problem?
PostHog is looking for a Fullstack Engineer, and I am looking for a job. Therefore, I'd like to propose hiring me.

Here's a preview of how hiring me could be reflected on your website: [https://posthog.jurajmajerik.com/](https://posthog.jurajmajerik.com/)

Something more about my work: [https://newsletter.pragmaticengineer.com/p/an-educational-side-project](https://newsletter.pragmaticengineer.com/p/an-educational-side-project)

## Describe the solution you'd like
Hiring me! I love building cool products and can definitely help you build yours. Besides that, I love your approach to collaboration and transparency and would truly enjoy working with you.

## Describe alternatives you've considered
I reached out to two members of the team on Linkedin and Twitter, but haven't heard back. Since PostHog loves Github, I decided to try reaching out here.

## Additional context
I'm available for interviews immediately and can start on the job in mid-September.

**Comment by couaphang** [comment]
@jurajmajerik let's chat! Please feel free to email me at coua@posthog.com :smile:
