### ISSUE TITLE
Make variant override conditions clearer for feature flags

### ISSUE THREAD

**Issue by neilkakkar** [PostHog/posthog#16587]
## Is your feature request related to a problem?

It's not obvious when creating a flag, that variant overrides will trump the variant distribution.

For example, in this case, everyone will get `b` even though the variant distribution is 100% to `a`:

<img width="1242" alt="image" src="https://github.com/PostHog/posthog/assets/7115141/5768be50-fca5-4061-bace-b71a38568ab1">

(on page: https://app.posthog.com/feature_flags/new )

*Please describe.*

## Describe the solution you'd like

When variant overrides exist, we should make this clearer.

Further, when more than one override exists, we should have a notification about ordering: The earlier release condition override trumps any override in following sets.

**Comment by nategrift** [comment]
@neilkakkar Thoughts on the wording of the informational banner I added in my PR? I am less versed in the way feature flag overrides are processed. Thanks!

**Comment by nategrift** [comment]
This is good to close by an admin as it is completed! 🙂
