### ISSUE TITLE
Default dashboard(s)

### ISSUE THREAD

**Issue by paolodamico** [PostHog/posthog#1659]
## Is your feature request related to a problem?

From several customer conversations (2009) we learnt that it's not always clear all the analyses you can do with PostHog and/or how to do them. Further, there's some expectation from some users on having a default setup for most common use cases (similar to what GA does).

## Describe the solution you'd like
I would like to have a default dashboard created on every new account. This default dashboard can change depending on the type of product the customer uses (e.g. web app, mobile app, e-commerce website, blog, ...). Once we have a default dashboard (or a couple of them), we can use these configurations as templates to create new dashboards (as @timgl pointed out, with the introduction of #1562, users may want to create a dashboard from a template for new projects).

We can use [this document](https://docs.google.com/spreadsheets/d/1q9NcOOjm7WUQGFS8xX6bVIy-dsrvG-kL7StlGpTzaVk/edit) to brainstorm and design the first dashboards.

## Describe alternatives you've considered

Create a guide in our docs (although a lot of users want just to jump right in).

**Comment by jamesefhawkins** [comment]
A few more ideas...

# Website

* Repeat visitors - stickiness of pageviews over time
* Revenue attribution - weekly revenue broken out by traffic source

# App (General)

* All time sign ups - cumulative over all time of unique users
* It'd be nice to show feature usage, but that'd need to be a 'placeholder' dashboard of trends page broken out by event type
* Wasn't sure what this is: ![Screenshot 2020-09-21 at 11 31 48](https://user-images.githubusercontent.com/47497682/93757080-0b6a4400-fbfe-11ea-85a9-dd50f783d369.png)
* Repeat visitors - stickiness of pageviews over time

# App (Subscription)

* Paid users by source

**Comment by paolodamico** [comment]
Thanks for the feedback @jamesefhawkins! Doc updated accordingly. The graph you asked about is a cohort retention graph, but that won't be part of the MVP (#1694) as we don't support it yet.

**Comment by Twixes** [comment]
I think this has evolved enough to be closed – app Home, dashboard templates et al.
