### ISSUE TITLE
Feature: Surveys targeted to events

### ISSUE THREAD

**Issue by joethreepwood** [PostHog/posthog#16681]
## Is your feature request related to a problem?

Sometimes there's a desire to send a survey to someone _when_ they do something, rather than based on a property or a feature flag; to trigger a survey based on an event. 

This is currently blocking to https://github.com/PostHog/meta/issues/120 but other examples include:

- I want to send to a survey when someone churns (example above), or leaves a beta
- I want to send a survey when someone completes a purchase
- I want to send a survey when someone finishes a customer service experience
- I want to send a survey when someone presses a button marked 'Feedback'
- I want to send a survey when someone signs up, or renews
- I want to send a survey when someone uses a feature for the first time

Currently this doesn't seem to be possible for surveys, which can only target based on properties or cohorts, with flags as a variable. 

## Describe the solution you'd like

Event-based targeting for surveys. An immediate survey trigger is definitely the most desirable, but potentially it could have other formats?

When [Event] is completed
When [Event] is completed + [X] Days/Hours
When [Event] AND [Event] are completed
When [Event] AND [Event] are completed + [X] Days/Hours

**Comment by benjackwhite** [comment]
If we do this. Then we do [this](https://github.com/PostHog/product-internal/blob/main/requests-for-comments/2023-04-11-automation-v1.md).

**Comment by kiran-4444** [comment]
I'd like to work on this, may be a part of it initially (like sending surveys to people who opted out of beta). Can I go ahead with this?
