### ISSUE TITLE
Capture front end errors

### ISSUE THREAD

**Issue by jamesefhawkins** [PostHog/posthog#1673]
## Is your feature request related to a problem?

I just had a user call with a potentially interesting dev-focussed use case. I want to understand what happened when a front end error was triggered by a user doing something.

## Describe the solution you'd like

We specifically want to see what a user was doing when an error occurred so the customer support team can talk with engineering and get back to the user with a solution without having to ask for console logs etc.

This means:
* Ability to capture errors / network requests
* Ability to watch a recording of that session (ie #149 ) would be ideal but not critical as we provide logs of events already
* For this particular user, it _must_ work with Segment's integration (which is why they won't use logrocket)

Even better:

* Ability to see the PRs versus errors over time on a dashboard
* Ability to create a GitHub issue with the error data in

## Describe alternatives you've considered

?

**Comment by macobo** [comment]
This is interesting. My 2c

> Ability to see the PRs versus errors over time on a dashboard

This sort of gets into the domain of sentry/bugsnag/other error tracking tools or e.g. datadog.

One cool thing we could do here to integrate with these is to link into posthog from these tools to get at the user/session recording:

A recipe for doing this:
1. Implement #149
2. Hook into sentry/bugsnag on errors (can be done by e.g. hooking into `beforeSend` for bugsnag: https://docs.bugsnag.com/platforms/javascript/configuration-options/) 
    1. Provide e.g. `analytics_id` or `analytics_user_link` or `analytics_session_link` to bugsnag
    2. Send an event to posthog that an error occurred

This way other tools can deal with error tracking/management but link into posthog for it's strength: tracking and user/cohort analysis.

**Comment by Twixes** [comment]
We now have a Sentry integration for JS. Sentry does a much better job at error capture than we'll ever will (it's their whole job) and we get the relevant information into PostHog as well, so this seems like the optimal solution.

**Comment by jamesefhawkins** [comment]
For anyone reading... We have now built:

- [session recording](https://posthog.com/docs/user-guides/recordings)
- we are _actively looking_ for a beta user for our error recording - we can track console logs whilst a session is being used. Please message hey @ posthog dot com if this could be you!
<img width="1111" alt="Screenshot 2022-03-17 at 14 12 00" src="https://user-images.githubusercontent.com/47497682/158825956-77979ee6-5248-4f70-8a0c-71cc35e73ee2.png">

(this doesnt' work with segment unless you also add our js snippet to your header)

**Comment by PatrickBilic** [comment]
Hey @posthog.com :)
