### ISSUE TITLE
Regex in Heatmaps

### ISSUE THREAD

**Issue by meikitanious** [PostHog/posthog#16764]
## Problem

Heatmaps only allow wildcards makes it difficult for pages with active query parameters (e.g. filters on eCommerce product category pages). Let's say, for example, I wanted to view a heatmap for users who filtered by a shop page for widgets that cost at least $50:

`example.com/shop/?category=widgets&priceMin=50`

The order of these query strings isn't always going to be consistent. Using wildcards can capture unwanted data and exclude necessary data. Example:

`example.com/shop/?*category=widgets*priceMin=50`

Would not match valid queries such as:

`example.com/shop/?priceMin=50&category=widgets`
`example.com/shop/?category=widgets&priceMin=50&utm_source=github`

But would match invalid queries such as:

`example.com/shop/?category=widgets&priceMax=100&priceMin=50`
`example.com/shop/?category=widgets,gadgets&priceMin=50`

## Describe the solution you'd like

Being able to write or select regex logic in the URL section of a heatmap.

**Comment by pauldambra** [comment]
So, we haven't ported this back to the original click maps API, but this is roughly how the new heatmaps API works

We're a subset of `re2` regex syntax now (or at least we will after https://github.com/PostHog/posthog/pull/22381 is deployed)

We do a little validation and transformation to protect ourselves. And we expand `*` to `.+` if it isn't `.*`

but at least for the new heatmap and scollmap most valid re2 regexes will work

sorry this took so long!
