### ISSUE TITLE
Use session_replay_events to calculate `session_duration`

### ISSUE THREAD

**Issue by pauldambra** [PostHog/posthog#16786]
When we analyse insights using session duration we group the events table

```
SELECT
    $session_id, dateDiff('second', min (timestamp), max (timestamp)) as session_duration
FROM
    events
WHERE
    $session_id != ''
  AND team_id = 2
  AND toTimeZone(timestamp
    , 'US/Pacific') >= toDateTime('2023-07-01 00:00:00'
    , 'US/Pacific') - INTERVAL 24 HOUR
  AND toTimeZone(timestamp
    , 'US/Pacific') <= toDateTime('2023-07-26 23:59:59'
    , 'US/Pacific') + INTERVAL 24 HOUR
GROUP BY $session_id
```

but we now have a way smaller table with the same info, it should be faster to query

```
SELECT
    session_id as $session_id, dateDiff('second', min (min_first_timestamp), max (max_last_timestamp)) as session_duration
FROM
    session_replay_events
WHERE
    $session_id != ''
  AND team_id = 2
  AND toTimeZone(min_first_timestamp
    , 'US/Pacific') >= toDateTime('2023-07-01 00:00:00'
    , 'US/Pacific') - INTERVAL 24 HOUR
  AND toTimeZone(max_last_timestamp
    , 'US/Pacific') <= toDateTime('2023-07-26 23:59:59'
    , 'US/Pacific') + INTERVAL 24 HOUR
GROUP BY $session_id
```

Using HouseWatch benchmarking and an example query 

We see

### 7 day date range

<img width="1165" alt="7-days" src="https://github.com/PostHog/posthog/assets/984817/d8008666-2bd2-4a39-8bbc-9f5720f9a656">

### 20 day date range

<img width="1138" alt="20-days" src="https://github.com/PostHog/posthog/assets/984817/7dfd0ed0-e778-49f7-aea6-9d7dd1bb4213">

** way faster ** and not a massive code change.

_but_

For cloud (and any self hosted instance that has been running and upgrading through this period) you could be querying data that isn't in the `session_replay_events` table but is in `events`. So, we'd have to have a check to see if the query can be run in the new table. Which is a bit yucky.

**Comment by pauldambra** [comment]
see https://github.com/PostHog/posthog/pull/16787

**Comment by benjackwhite** [comment]
Isn't this limited by having Session Replay enabled? And more generally an assumption that Replay is running on every page all the time?

Feels like we would potentially need to have a flag that you set from the API to say "base this on Session Replay data" with the caveat that there could be fewer data points but that it will respond faster.

**Comment by pauldambra** [comment]
🤯 ah, yeah, ofc... you can have a session id and no replay :'(

**Comment by pauldambra** [comment]
Too much complexity for a tiny perf gain
