### ISSUE TITLE
static type checking fails in posthog-foss

### ISSUE THREAD

**Issue by ryan-pypestream** [PostHog/posthog#16797]
## Bug description

posthog-foss repository reports 1355 errors when running mypy 

## How to reproduce

1. Open codespace on posthog/posthog-foss
2. Setup virtual environment and install requirements
3.  Run the static checking command from the CI:
mypy -p posthog --exclude bin/migrate_kafka_data.py --exclude posthog/hogql/grammar/HogQLParser.py --exclude gunicorn.config.py 2>&1 | tee mypy.log

## Environment

- [ ] PostHog Cloud US, project ID: [please provide from https://app.posthog.com/project/settings#project-id]
- [ ] PostHog Cloud EU, project ID: [please provide from https://eu.posthog.com/project/settings#project-id]
- [ ] PostHog Hobby self-hosted with `docker compose`, version/commit: [please provide]
- [ ] PostHog self-hosted with Kubernetes (deprecated, see ["Sunsetting Kubernetes support"]
- [X] PostHog Codespaces

## Additional context

[mypy.log](https://github.com/PostHog/posthog/files/12182128/mypy.log)

**Comment by pauldambra** [comment]
Hey @ryan-pypestream can you confirm the version of mypy that you ran with?

The errors in that log look a lot like the ones you see if you try and run with the "wrong" version. We're pretty far behind on mypy version
