### ISSUE TITLE
Replace antd components with Lemon UI

### ISSUE THREAD

**Issue by thmsobrmlr** [PostHog/posthog#16827]
We're migrating away from antd components to our own component library called "Lemon UI".

## More Context

You can find locations that need updating by looking for antd imports in our codebase:

```tsx
import { Button } from 'antd'
```

Please note that not all antd components might have a Lemon UI replacement yet, or not all options might be supported. In this case replacing might not be a "good first issue" any more, but a more complex task.

## Contributors

When you want to work on this PR, don't try to do it all at once. Rather pick out one or a couple of components to replace. When replacing multiple components in a single PR, try to pick a specific product area or page so that changes can easily be reviewed together.

**Comment by Twixes** [comment]
Here's the issue tracking progress: #13624

**Comment by subhajit20** [comment]
@thmsobrmlr  is this still open. would like to work on this.
Could you assign it me ?

**Comment by thmsobrmlr** [comment]
Hey @subhajit20, yes, this is still open. We don't usually assign issues to specific people and you can just start working on it. With granular PRs there should be little chance that someone else is already working on the same thing.

**Comment by anirudh24seven** [comment]
@thmsobrmlr @Twixes It looks to me as if this issue is resolved with #13624.

**Comment by Twixes** [comment]
This is done indeed!
