### ISSUE TITLE
Allow ip to be passed as a capture param

### ISSUE THREAD

**Issue by andrei-datcu** [PostHog/posthog#1684]
## Is your feature request related to a problem?

I'm running a posthog instance behind a http proxy and all the events are captured from a django app running under the same proxy on the same server. So the data flow is something like this:

client -> proxy -> django -> posthog
admin -> proxy -> posthog

## Proposed solutions

a) `$ip` could be checked for in the properties dictionary, here:
https://github.com/PostHog/posthog/blob/0268e88f4fbf93acf48343ad7e2c3f672d4d3ba8/posthog/tasks/process_event.py#L122

b) The posthog integrations could allow custom headers to be set by the caller.
In my case, if I were able to set `X-Forwarded-For` from posthog-python it would be enough to get the right ip

## Workarounds
Passing `$ip` in the parameters currently works as long as `Anonymize client IP data` is flipped in the settings page, though I feel it's rather by chance and it's not the proper way to solve this.

**Comment by timgl** [comment]
@andrei-datcu Sorry for the late response here! I've created a PR that will allow you to just pass the $ip property correctly. Thanks!
