### ISSUE TITLE
Insight: Grouping data by month not happening correctly

### ISSUE THREAD

**Issue by zeketEQ** [PostHog/posthog#1685]
## Bug description
When I try to see how many times an event happens per month the data does not seem to group correctly. If I select "All time" by month and then click on a specific month I see results from other months.

![image](https://user-images.githubusercontent.com/61121781/93653596-72091b00-f9ce-11ea-8758-61d21a612b78.png)

![image](https://user-images.githubusercontent.com/61121781/93653374-813b9900-f9cd-11ea-9fed-531e7d8a09b3.png)

## Expected behavior
I should see counts by the correct months

## How to reproduce

1. Go to "Insights"
2. Change date range to "All time"
3. Change time frame to "Monthly"
4. Click on a specific month on the graph
5. There are events that are not in that month

## Environment

- PostHog self-managed (heorku)
- PostHog 1.14.0

**Comment by timgl** [comment]
@zeketEQ Apologies for the late response! One reason this can happen is because the user has multiple events on multiple days. The 'uniqueness' you get from selecting 'Active Users' is only for each interval. Does that help?

**Comment by zeketEQ** [comment]
@timgl Unfortunately not. I drilled into that same user and every event happened on that one day in June.

**Comment by Twixes** [comment]
We've made a lot of improvements and fixes to our queries this year, so I'll close this – do reopen if still an issue.
