### ISSUE TITLE
Paths don't show initial dropoff

### ISSUE THREAD

**Issue by mariusandra** [PostHog/posthog#1686]
## Bug description

When I select a page in "paths" that only has inbound visits (no page visited after this page), the graph is empty:

![image](https://user-images.githubusercontent.com/53387/93738748-d3a3d200-fbe6-11ea-8b99-59768efebdec.png)

... even though I could select the URL from the list.

## Expected behavior

I should see a path with `N` visits on it and a 100% dropoff.

## How to reproduce

1. Open paths
2. Select some URL that's at the end of any user journey
3. See an empty page with an incorrect error message

## Additional context

Related, the first "path" of any graph only shows visits that go to a second page. This graph only shows the dropoff of users who left after `/demo/1`, but doesn't show the dropoff at the first stage, i.e. the users who left directly after `/demo/`

![image](https://user-images.githubusercontent.com/53387/93738960-6e041580-fbe7-11ea-936d-dde491fc6f53.png)

**Comment by paolodamico** [comment]
The new Paths visualization already addresses this.
