### ISSUE TITLE
FR: Extend dashboard presentation mode

### ISSUE THREAD

**Issue by paolodamico** [PostHog/posthog#1687]
## Is your feature request related to a problem?

A user mentioned having an always-on TV/projector in their office showing a dashboard with key metrics. From this use case we can extend the presentation mode (see below).

![presentation-mode](https://user-images.githubusercontent.com/5864173/93859218-42e7f780-fcb5-11ea-8b75-7a043a7166ce.png)

## Describe the solution you'd like

Presentation mode should introduce the following functionality,
1. Auto-refreshes all the dashboards on an interval (~30 seconds).
~1. Adds a general “last refreshed” label.~
~1. Hides action buttons (i.e. refresh, details button) on graphs.~
~1. Disables graph dragging/dropping.~

## Describe alternatives you've considered
Using a browser extension/add-on to auto-refresh on certain intervals.

## Additional context
No additional context.

**Comment by Twixes** [comment]
We do already have a fullscreen mode sort of intended for this use case, but it isn't so robust yet.

**Comment by paolodamico** [comment]
> We do already have a fullscreen mode sort of intended for this use case, but it isn't so robust yet.

Right! Updated issue accordingly.

**Comment by DimitrisMazarakis** [comment]
Hello! Can I take this issue?

**Comment by paolodamico** [comment]
Hey @DimitrisMazarakis! Go for it! I've updated the issue because some stuff has already been addressed. Please also be mindful that the UI & components has changed from the screenshot above, so worth considering. Happy hacking!

**Comment by DimitrisMazarakis** [comment]
Thank you very much @paolodamico! I have a question, the function which auto-refreshes all the dashboards every 30 seconds shouldn't also be existed in the non full screen? Becauseyou have to refresh each dashboard manually. And something that I noticed is that you can't scroll to see more dashboards when you are on full screen mode.

**Comment by paolodamico** [comment]
Hmmm well I'm a bit hesitant to have it in normal mode, data may change as you're looking at it, which could be confusing. We would also be adding a ton more load on the infrastructure that might not be needed. Now that we talked about this, I think even on fullscreen mode it's worth updating every 1 or 2 minutes, rather than 30 secs.

Good point that you brought up! If you're up for it, we should also fix so that you can scroll on full screen mode.

**Comment by DimitrisMazarakis** [comment]
Okay, I understand what you are saying.  I will set it to update every 1 or 2 minutes only when you are on full screen mode. I will also try to fix the scroll issue :)

**Comment by paolodamico** [comment]
Sounds good! Let me know if you run into any issues

**Comment by DimitrisMazarakis** [comment]
Hey @paolodamico ! Sorry that I haven't fixed the issue yet but I was very busy with the university. I wanted to show you the interface that I have created for the auto-refresh function. Do you think that I should change something? Are the intervals enough and in a good range? Also is there an icon for stop operation because as you can see I put the delete icon which doesn't fit so good.
![screen_1](https://user-images.githubusercontent.com/56391437/121926126-4f7e1580-cd46-11eb-9ee4-071845607de6.png)
![screen_2](https://user-images.githubusercontent.com/56391437/121926141-53119c80-cd46-11eb-885f-9803e74767a6.png)

**Comment by paolodamico** [comment]
Hey @DimitrisMazarakis! No worries at all, totally understand! We appreciate the contribution. So taking a bit of an step back, I'm thinking we could simplify this a bit further. How about just defaulting to something reasonable (like 2 minutes) and just adding a toggle that allows you to turn it on or off.

As a side note I was also thinking it's worth making sure that while we're refreshing the dashboards, we don't remove the currently loaded dashboards from view (i.e. we don't show the loading spinner instead of the actual graph when auto-refreshing), so the page doesn't constantly bounce, or introduce any slowness.

**Comment by DimitrisMazarakis** [comment]
@paolodamico Got it! I will try to make the changes and create the pull request as soon as I can. Thanks for the help!

**Comment by paolodamico** [comment]
Sounds good @DimitrisMazarakis! Let us know if we can help and the thanks once more.

**Comment by paolodamico** [comment]
#4773 implemented the last part of this issue, closing
