### ISSUE TITLE
Sprint August 7th to August 18th

### ISSUE THREAD

**Issue by benjackwhite** [PostHog/posthog#16881]
# Global Sprint Planning

## 3 things that might take us down

1.
2.
3.

## Retro: What can we do better next sprint?

1.
2.
3.
4.
5.

# Team sprint planning

For your team sprint planning copy this template into a comment below for each team.

```
# Team ___

**Support hero:** ___

## Retro

<!-- Grab the high and low priority items from last time and add whether that item was completed or not -->

- 

## Hang over items from previous sprint

<!-- For each item, decide to re-prioritise (and add below) or deprioritise -->

- Item 1. prioritised/deprioritise

## OKR

1. OKR, status (red/yellow/green) and action points if yellow/red


### High priority

-

### Low priority / side quests

-

```

**Comment by benjackwhite** [comment]
# Team Monitoring 

**Support hero:** @daibhin 

## Retro

## Hang over items from previous sprint

🟡 Insights on Notebooks properly @benjackwhite  
  - Focused on 3000-ifying the UX which should aid getting Insights in properly
🟡 Filtering / Searching UX for recordings @pauldambra @daibhin @annikaschmid 
  - Carrying over but we have an Experiment up and coming for the "quick filters"
  - Paul's work fixing and improving the filters is in (e.g. excluding internal users filters)
🟢 Recording transcription followup @daibhin 
  - Jumping back and forth from annotations works
🟢 rollout of blob ingester
  - Just need pipeline team help to get autoscaling working and then we're ready to roll out next week

## Goals

 * 🎯 Goal 1 : Notebooks on ProductHunt 🟢
 * 🎯 Goal 2 : Next 5 great things for Replay 🟢
    - 🥳 Filtering and searching UX
    - 🤔 "Deep dive" e.g. Funnels -> list -> recording
    - 🤔 Clips
    - 🤔 Mobile replay

### High priority
- Notebooks floating editor to configure Widgets - @daibhin 
- Intelligent search for notebooks - (e.g. Show me Notebooks containing this recording) - @pauldambra 
- Helping Pipeline team get Exports UI out the door - @benjackwhite 

### Low priority / side quests
- Monitor rollout of blob ingester with help from Pipeline @benjackwhite 
- Create, edit, save any Query from within a Notebook - @benjackwhite

**Comment by tiina303** [comment]
# Team Pipeline 🚰 

**Support hero:** @tiina303 (both weeks, so others can work on ship & I can work with @jamesefhawkins to make things better)

## Retro



- @tiina303  vacation was great, starting the first day back with an incident not so much
- @tomasfarias & @xvello  feeling understaffed, especially with support and around apps & lots of exceptions requests

### High priority

Exports:
- new exports frontend to spark joy - owned by the imported frontend pro @benjackwhite 
- Snowflake legacy app uninstalled @tomasfarias 
- PG exports available for beta testers @tomasfarias

Other:
- pluginStorage to separate PG instance (why: stop taking down the app) @xvello 
- Helping replay team with Blob ingestion @xvello

**Comment by EDsCODE** [comment]
# Team Data Warehouse

## Retro

**Infra**
- [x] Automate backups on EU and US
  - Automated in a script. Will be moving that into Housewatch this sprint.
- [x] Clickhouse Copier EU -> CH.cloud for testing
  - Clickhouse copier is terrible, but was able to test restoring backups from EU on CH.cloud
- [x] Discus ClickPipes to consume data from Kafka for CH.cloud with CH.cloud
  - ClickPipes will be coming to EU in the next week or so. Will follow up this sprint.

**Product**

- Release MVP for person/group modeling (🟡 In progress and internal use should be close to possible by EOW)
- Internal use + 5 happy users for data warehouse. (🟡 Focused on 1st item more than this. There is an org that self activated)



### High priority

**Product**
- sanitize credentials from sentry
- UI for showing table relationships and modeled entities
- Brainstorm methods to scale. Current iteration won't scale

**Infra**
- [ ] Integrate backup script into HouseWatch app with interface and schedule
- [ ] Benchmark ClickHouse.cloud - Data is now fully available in EU from EU
- [ ] Discus Issues with CH team on Tuesday of next week
- [ ] Setup ClickPipes or Vector to EU

**Comment by ellie** [comment]
# Team Infrastructure

**Support hero:** @frankh 

## Retro

- Last week was nice and quiet!
- Postgres is struggling, lots of incidents
- Managed OK-ish with just two people on the team


### High priority

- Postgres schema fixes and drift correction US, EU @ellie 
- pgbouncer splitting for ingestion @danielxnj 
- configure aurora postgres so we can logically replicate @ellie 
- continue splitting chart, goal to kill charts repo @frankh 

### Low priority / side quests

- Google SSO on OpenVPN (tailscale DNS needs work still) @danielxnj

**Comment by Twixes** [comment]
# Team Product Analytics

**Support heroes:** @Twixes, then @mariusandra 

## Retro

- we planned to spend this sprint on properly solving issues reported by customers, and mostly did, but there's still a backlog (e.g. we've found that background dashboard refreshes don't keep up and need to be rearchitected as stale data is being shown)
- unusually high load in terms of external contributor PRs, some useful stuff though

## OKR

- 🔴 Port all our insights over to HogQL.
   - Delayed due to support.
- 🔴 Sleeker insight editor UI
   - Not started.

### High priority

- Recordings and apps in the 3000 sidebar.
- Onboarding Robbie!

**Comment by raquelmsmith** [comment]
# "Team" Growth

**Support hero:** Me

## Retro


- [x] Launch feature flags pricing
- [ ] Mock up a product-specific onboarding flow for eg. Feature flags or Experiments
  - In progress

## OKR

1. Starting to use and paying for new products feels frictionless
  - 🟡 Starting work on this.
  - [ ] KR: We have separate onboarding for each product
  - [ ] KR: People don’t have to “upgrade” to different products, they just turn it on or start using it in some way.
3. Customers can pay a reasonable price for the value they’re receiving
  - 🟢 Done! Unless Data Warehouse or CDP become ready for launch.
  - [x] KR: Make sure rollout of new product analytics pricing goes well
  - [x] KR: Feature Flags pricing is launched, as well as Data Warehouse and CDP, if they are ready for launch

## This sprint
### High priority
- [ ] Mock up a product-specific onboarding flow for eg. Feature flags or Experiments
  - And start working on it
- [ ] Figure out why usage reports are still flaky

### Low priority / side quests

**Comment by neilkakkar** [comment]
# Team Feature Success

**Support hero:** @neilkakkar 


## Retro


1. Surveys: Multiple choice survey option + controlling targeting for users who've seen surveys - @liyiy -> Multiple choice will be done, but controlling targeting deferred to next sprint
2. Make feature flag dashboard templates and flag autocapture ready for general availability - @neilkakkar -> 🔴 No progress -> couple of incidents that took higher priority, plus scaling up local evaluation endpoint, & some interviews :$ -> will continue in next sprint


## Hang over items from previous sprint

controlling targeting for users who've seen surveys

---

## OKRs

1. Make it easier for engineers to analyze the success of a feature
2. Build out an excellent user feedback product

### High priority

1. Surveys: Controlling targeting for users who've seen surveys + data display for ratings/mcq surveys - @liyiy
2. Make feature flag dashboard templates and flag autocapture ready for general availability - @neilkakkar 

### Low priority / side quests
