### ISSUE TITLE
Replay blob ingestion remaining tasks

### ISSUE THREAD

**Issue by benjackwhite** [PostHog/posthog#16887]
## Remaining tasks

Replay ingestion to S3 is nearly ready to go with some remaining tracks that I'm tracking here:

- [x] Ensure autoscaling is soft enough as to not over-adjust during redeploys @pauldambra 
- [x] Swap replay events to be ingested via the blob ingester
- [x] Turn on blob replay playback for more teams, gradually rolling out to everyone
- [ ] Tune the kafka consumption to try and get more out of each consumer
- [ ] how much can we flush/sync/commit on shutdown
- [ ] how much can we flush/sync/commit on rebalance

**Comment by pauldambra** [comment]
let's assume done and we'll revisit periodically
