### ISSUE TITLE
Paths API request made twice when opening page

### ISSUE THREAD

**Issue by mariusandra** [PostHog/posthog#1691]
## Bug description

Clicking from "insights -> trends"  to "insights -> user paths" makes a double HTTP request to fetch the paths.

![2020-09-21 09 28 30](https://user-images.githubusercontent.com/53387/93741529-e28d8300-fbec-11ea-9ab3-9098a9492dc8.gif)

Since this is a rather heavy query, this can cause problems.

Reloading the page while on "user paths" does just one query.

**Comment by yakkomajuri** [comment]
Can't reproduce with demo data

<img width="1440" alt="Screenshot 2020-10-18 at 11 21 54" src="https://user-images.githubusercontent.com/38760734/96364783-3334c500-1134-11eb-9a1a-21aa2a333957.png">

**Comment by mariusandra** [comment]
This got fixed when I converted the paths page to typescript when also working on the paths clickhouse query.

**Comment by yakkomajuri** [comment]
Got it!
