### ISSUE TITLE
Bug with webbooks custom messages

### ISSUE THREAD

**Issue by paolodamico** [PostHog/posthog#1692]
## Bug description

Reported initially by a user. There’s a bug in which the app doesn’t revert back to the default message for a webhook after clearing a custom message, causing the webhook to send an empty message.

![screenshot](https://user-images.githubusercontent.com/5864173/93744438-bc1a1880-fbe9-11ea-92ec-83a8141a5bcc.jpg)

## Expected behavior

Saving an empty custom message should revert back to the default message.

## How to reproduce

1. Set up a custom message for the Slack webhook (and save).
1. Clear the custom message and save.
1. Trigger the webhook. 

## Environment

- Reproduced on self-managed latest version.

## Additional context
May cause significant confusion as some users make use of the webhook as a regular health check.

**Comment by jonathanlloyd** [comment]
Hi!
I've had a go at fixing this in: https://github.com/PostHog/posthog/pull/1859
Happy Hacktoberfest! :jack_o_lantern:

**Comment by paolodamico** [comment]
Fixed on #1892
