### ISSUE TITLE
Duplicate dynamic cohorts

### ISSUE THREAD

**Issue by neilkakkar** [PostHog/posthog#16935]
## Is your feature request related to a problem?

From a user:

Ability to duplicate a dynamic cohort to make setting up similar cohorts easier. Not a major pain point, but I thought perhaps a nice quality of life improvement.

**Comment by SauravChittal** [comment]
Could I try to tackle this issue?

**Comment by neilkakkar** [comment]
@SauravChittal you don't have to ask, go ahead :)

**Comment by jasonyavorsky** [comment]
This can now be closed :)

**Comment by neilkakkar** [comment]
:)
