### ISSUE TITLE
People cohort not refreshing results

### ISSUE THREAD

**Issue by SvenAlHamad** [PostHog/posthog#1693]
## Bug description

Under the People > Cohorts we have created several cohorts. However, the results don't seem to be refreshing automatically. The only way to refresh the results for us at the moment is to save the cohort again. 

![image](https://user-images.githubusercontent.com/3808420/93752266-53856880-fbf6-11ea-8846-d416c811d9f7.png)

## Expected behavior

The results should refresh automatically every 15 minutes.

## How to reproduce

1. Create a new cohort.
2. Wait for more than 15 minutes.
3. Check if the "last calculation" filed has updated. 

## Environment

- Running Posthog `1.14.0` (self-managed). Posthog is installed via CloudFormation template. 

## Additional context
In Posthog we have a "configuration error" warning:
![image](https://user-images.githubusercontent.com/3808420/93752509-aced9780-fbf6-11ea-8729-f2ea64461950.png)

However, I've double-checked the container environment variables and the REDIS_URL is correctly set. Also, the Redis container status is green and available and all the metrics seem to be in order. 

Under the cluster logs, the only message that I was able to find was this, not sure if it's relevant:

```
2020-09-18 13:12:58/usr/local/lib/python3.8/site-packages/django/db/models/fields/__init__.py:1365: RuntimeWarning: DateTimeField DashboardItem.last_refresh received a naive datetime (2020-09-18 12:12:58.621475) while time zone support is active.
/usr/local/lib/python3.8/site-packages/django/db/models/fields/__init__.py:1365: RuntimeWarning: DateTimeField DashboardItem.last_refresh received a naive datetime (2020-09-18 12:12:58.621475) while time zone support is active.
2020-09-18 13:12:58/usr/local/lib/python3.8/site-packages/django/db/models/fields/__init__.py:1365: RuntimeWarning: DateTimeField DashboardItem.last_refresh received a naive datetime (2020-09-18 12:12:58.423036) while time zone support is active.
/usr/local/lib/python3.8/site-packages/django/db/models/fields/__init__.py:1365: RuntimeWarning: DateTimeField DashboardItem.last_refresh received a naive datetime (2020-09-18 12:12:58.423036) while time zone support is active.
2020-09-18 13:12:58warnings.warn("DateTimeField %s received a naive datetime (%s)"
```

**Comment by timgl** [comment]
@SvenAlHamad Hey Sven, sorry for the late reply here. I suspect the reason is that your database gets flooded whenever we do the cohort updates. What kind of server size is your database on, and how many events do you have roughly? Thanks!

**Comment by SvenAlHamad** [comment]
@timgl I've checked the database, we're not exceeding the number of connections, CPU or storage limits. It's a `db.t3.micro` we're running at the moment. In the DB logs, there we no errors reported in the last 3 days. 

In terms of a number of events, In the last 20mins, we had about 200 events.

Inside the Posthog we have about 15 cohorts ranging from 1 user to 4000 users, but none of the cohorts gets refreshed.

**Comment by Twixes** [comment]
We've made some changes to the system since this reported, so I'll close. But please reopen if still experiencing this.
