### ISSUE TITLE
Unable to git commit due to a package being not able to run

### ISSUE THREAD

**Issue by ebrahim95** [PostHog/posthog#16953]
## Bug description

Hello everyone,

I have error  that specifically happens when run I storybook visual regression tests. As soon as I git commit the updated snapshot, the error appears. The issue I am working on is #16826.

Below is the command line:

```

git commit -m "chore(debt): updated  snapshot through storybook"
✔ Preparing...
⚠ Running tasks...
  ↓ No staged files match *.{json,yaml,yml,css,scss} [SKIPPED]
  ↓ No staged files match (!(plugin-server)/**).{js,jsx,mjs,ts,tsx} [SKIPPED]
  ↓ No staged files match (plugin-server/**).{js,jsx,mjs,ts,tsx} [SKIPPED]
  ↓ No staged files match !(posthog/hogql/grammar/*)*.{py,pyi} [SKIPPED]
  ❯ Running tasks for *.png
    ✖ optipng -clobber -o4 -strip all [ENOENT]
↓ Skipped because of errors from tasks. [SKIPPED]
✔ Reverting to original state because of errors...
✔ Cleaning up... 

✖ optipng -clobber -o4 -strip all failed without output (ENOENT).
 ERR_PNPM_RECURSIVE_EXEC_FIRST_FAIL  Command "lint-staged" not found

Did you mean "pnpm lint-staged"?
husky - pre-commit hook exited with code 1 (error)
```

## How to reproduce

1.  Delete the style tag, then add the height attribute to the className, in this case for: 
`frontend/src/lib/components/Cards/TextCard/TextCard.stories.tsx`
2. After run the visual regression test:
`sudo pnpm test:visual-regression:stories frontend/src/lib/components/Cards/TextCard/TextCard.stories.tsx --url http://localhost:6006`
3. Git add and  commit the new snapshot.

## Environment

- [X ] PostHog Hobby self-hosted with `docker compose`, version/commit: [18147bf](https://github.com/ebrahim95/posthog/commit/18147bf266422d5ab7dc914724682130c622ad9b)

## Additional context

Using Kubuntu with bash shell. 
Thank You,
Ebrahim Haji

**Comment by nategrift** [comment]
Hey Ebrahim, thanks for providing more details. I do remember this from when I started contributing. It had to do with a missing linux dependency `optipng`. It was a while ago, but I believe I fixed it with `sudo apt-get install optipng` as you are on linux (or `brew install optipng` if your on mac). Let me know if that fixes it! 😄

**Comment by ebrahim95** [comment]
It worked, Appreciate the help.

**Comment by nategrift** [comment]
Awesome! Glad it worked.

**Comment by mariusandra** [comment]
Oh... we could definitely use a few lines about this on https://posthog.com/handbook/engineering/developing-locally ;)
