### ISSUE TITLE
HogQL query overflowing // hiding the "X" to remove the query

### ISSUE THREAD

**Issue by MarconLP** [PostHog/posthog#16964]
## Bug description

HogQL query overflowing // hiding the "X" to remove the query
![Screenshot 2023-08-09 at 17 19 38](https://github.com/PostHog/posthog/assets/13001502/bb69713d-3bc5-4090-acbf-9cdd73761fb4)

## How to reproduce

1. Create an insight.
2. Add a long HogQL query into the breakdown field.
3. Try to remove the query.

## Environment

tickets:
https://posthoghelp.zendesk.com/agent/tickets/4633
https://posthoghelp.zendesk.com/agent/tickets/4941

## Additional context

the problem is also on the "trends" insight

**Comment by thmsobrmlr** [comment]
This was fixed in https://github.com/PostHog/posthog/pull/17126
