### ISSUE TITLE
A/B tests

### ISSUE THREAD

**Issue by jamesefhawkins** [PostHog/posthog#1697]
Should we change the title of this to something more like "make URL level A/B tests easier"?

You *can* do A/B tests with feature flags, and more ( this came out of a chat that @yakkomajuri and I had on a [PR for a feature flags tutorial](https://github.com/PostHog/posthog.com/pull/438#pullrequestreview-493432969))

It is possible to improve the feature flags UX to make a/b testing more intuitive. For example, with Google Analytics, you can create two different URLs, both with their snippet in the header. Then you can direct traffic at a URL level to one page or the other. That isn't trivial with our current set up.

**Comment by paolodamico** [comment]
Superseded by #3431
