### ISSUE TITLE
Feature Request: Support comma separated values in cohort filters

### ISSUE THREAD

**Issue by joethreepwood** [PostHog/posthog#16975]
## Is your feature request related to a problem?

A few times recently I've had to create some big, complex cohorts. These are usually around the Org_ID property, where I'll have a long list of 100+ Org_IDs and I need to create a cohort that hits all users with that matching Org_ID -- usually so I can export that list and take it into Customer.io to create an email campaign. 

The problem is that there's no easy way to add these Org_IDs in bulk. I have to copy and paste them, one by one, from a spreadsheet into the cohort builder. 

https://github.com/PostHog/posthog/assets/84011561/59657ff5-d137-485d-8049-17488bce351a

☝️ This, basically. But x100. 

As we get more users and do more email comms, this issue will only grow. And is likely impacting users too. 

## Describe the solution you'd like

It would be divine if the cohort builder supported comma separated values. That is, I could format my list of org_ids so that each value was separated by a comma (or pipe, or whatever) and I could paste the entire list in at once, and PostHog would just immediately recognise them all as discrete values. Currently, if do this it interprets everything I paste in as _one_ value. 

## Describe alternatives you've considered

HogQL cohort builder. But that wouldn't help me personally as HogQL is a foreign land.

**Comment by nategrift** [comment]
Oh this looks fun, I'd love to add this enhancement to PostHog!

**Comment by joethreepwood** [comment]
That'd be amazing, thank you @nategrift

**Comment by nategrift** [comment]
Hey @joethreepwood, I am having a hard time reproducing what you described. This enhancement seems to already exist. When I paste a list, separated by commas, it correctly puts them into unique values. Is there something I should be doing differently that pastes them in as one value together? 



https://github.com/PostHog/posthog/assets/69441127/fcc14e5b-68f9-4eea-9f30-c5f4bc42fa26

**Comment by joethreepwood** [comment]
Huh.

Just tested myself and it worked as described, but I 100% have tried this before unsuccessfully in the past. Something/someone must have fixed it somewhere, so we can close this for now. 

Thanks for taking a look though @nategrift <3

**Comment by raquelmsmith** [comment]
This is still broken. The values DO paste in properly 🙌 buttttttt then they aren't actually used to calculate the cohort 👎

**Comment by akashkiran-s** [comment]
> This is still broken. The values DO paste in properly 🙌 buttttttt then they aren't actually used to calculate the cohort 👎

Looking into this, I found a peculiarity. If you change the criteria and press reload btn, the result is for the old criteria. If you save then you get the correct result. I don't know if this is a bug or feature @raquelmsmith @joethreepwood. using Aug-18-2023 master branch to verify this locally

**Comment by raquelmsmith** [comment]
Hm, I did save and still did not get the correct result. Are you sure?

**Comment by akashkiran-s** [comment]
Pretty sure based on the behavior on my old branch. 
I wanted to test and confirm it on the latest master branch but I am facing an issue with the ingestion of the events.  I have attached a screenshot of the error when starting the server. Any pointers to rectify this?


<img width="1437" alt="Screenshot 2023-08-31 at 10 35 37 PM" src="https://github.com/PostHog/posthog/assets/87519262/1b30c750-d323-496e-a423-12d4569e830b">

<img width="1423" alt="Screenshot 2023-08-31 at 10 38 05 PM" src="https://github.com/PostHog/posthog/assets/87519262/139efd9d-604a-4886-9464-e8f1b9ed1ad2">
