### ISSUE TITLE
Add tooltip to "auto-refresh" explaining they will only refresh when opened in a browser.

### ISSUE THREAD

**Issue by MarconLP** [PostHog/posthog#16983]
## Is your feature request related to a problem?

![Screenshot 2023-08-10 at 16 05 26](https://github.com/PostHog/posthog/assets/13001502/3389a9bc-5950-4e44-b7e7-31d95f331ddc)
This option is confusing and could make people think it will refresh regardless of when the insight is opened in a browser or not.

## Describe the solution you'd like

Add a tooltip that says: "Auto-refresh will only work while this tab is open"

**Comment by thmsobrmlr** [comment]
Solved in the mentioned PR.
