### ISSUE TITLE
enabling Object storage (minio) in hobby deployment

### ISSUE THREAD

**Issue by 3rfun0** [PostHog/posthog#17006]
## Bug description

I have deployed posthog using docker-compose (hobby deployment), although it deployed minio container in the instance setting it shows "Object Storage enabled" is set to no. I have also tried adding these env bellow in the bin/deploy-hobby

OBJECT_STORAGE_ENABLED=True
OBJECT_STORAGE_ENDPOINT=opt-object_storage-1:9000
OBJECT_STORAGE_BUCKET=posthog

but it's still not enabled.

## How to reproduce

1. deploying hobby deployment

## Environment

- ubuntu 20.04
- Docker version 24.0.5
- post latest (1.43.0)

**Comment by feedanal** [comment]
Have you been able to resolve this?

**Comment by pauldambra** [comment]
(closed as it is from a long time ago - feel free to re-open)
