### ISSUE TITLE
Posthog toolbar does not respect proxy domain

### ISSUE THREAD

**Issue by pmomot** [PostHog/posthog#17018]
## Bug description

Changing `api_host` key to a reverse proxy address in posthog js init does not have any influence on a toolbar. As a result toolbar generates a lot of noisy failed requests for the users with adblockers on.

## How to reproduce

1. init posthog with the proxy domain specified in the `api_host` property
2. deploy an app with the posthog to your dev/prod env
3. observe most of the calls going to the proxy domain, but the toolbar-related calls still point to the `app.posthog.com`

The endpoints are:
```
- https://app.posthog.com/e/?
- https://app.posthog.com/decide/?v=2
```

![Screenshot 2023-08-14 at 14 46 28](https://github.com/PostHog/posthog/assets/6470115/862448b5-f6d6-45f7-8151-cb361e60719c)
![Screenshot 2023-08-14 at 14 47 50](https://github.com/PostHog/posthog/assets/6470115/5ed6b445-d356-4523-b27a-b2a159a4b00e)

## Environment

- [x] PostHog Cloud EU, project ID: 2754

**Comment by benjackwhite** [comment]
As far as I am aware, these requests will not be seen by _your_ users as the Toolbar is only running for yourself when you enable it. Your own adblocker might block some requests but in that sense it shouldn't matter.

The request are limited telemetry for us to understand how our users are using the toolbar. They aren't _your_ events from your app as far as I'm aware.

Does this makes sense or is there something else that you think might be going on here? (Feel to re-open the issue if thats the case)
