### ISSUE TITLE
How to migrate data from old PostHog server to new PostHog server?

### ISSUE THREAD

**Issue by rousan** [PostHog/posthog#1702]
## Bug description

I couldn't find any docs on data migration from one PostHog server to another. Let's say, I have deployed PostHog in one EC2 instance through Docker, but later, I want to redeploy the server in another EC2 instance without losing any data.
So, how do I transfer my old PostHog data to new one?

I am using Docker to deploy PostHog(the self-hosted version).

**Comment by rousan** [comment]
> ## Bug description
> I couldn't find any docs on data migration from one PostHog server to another. Let's say, I have deployed PostHog in one EC2 instance through Docker, but later, I want to redeploy the server in another EC2 instance without losing any data.
> So, how do I transfer my old PostHog data to new one?
> 
> I am using Docker to deploy PostHog(on-premise version).

**Comment by Twixes** [comment]
Hi! This isn't so much a bug as rather a feature that's not explicitly supported. Basically, PostHog data migration is Postgres data migration, there isn't really more to it. I believe you should be able achieve this manually by SSHing into the EC2 instance, dumping your Postgres database, sending that dump to the other server, and applying the dumped database in Postgres on the redeployed instance.

**Comment by paolodamico** [comment]
For the Postgres data migration you can also try [AWS DMS](https://aws.amazon.com/dms/)

**Comment by rousan** [comment]
Got it. Thanks for the quick response.

**Comment by evoxmusic** [comment]
Hi, I migrated our self hosted PostHog instance to PostHog cloud. I shared my experience and provided a migration script. Hope it helps you https://hub.qovery.com/guides/engineering/how-to-migrate-posthog-self-hosted-to-posthog-cloud/

**Comment by yakkomajuri** [comment]
Other relevant resources include:

- [Migrate from Postgres to ClickHouse](https://posthog.com/docs/self-host/migrate-from-postgres-to-clickhouse)
- [Migrator3000 Plugin](https://github.com/PostHog/posthog-plugin-migrator3000#readme)
