### ISSUE TITLE
Surveys UI UX issues

### ISSUE THREAD

**Issue by liyiy** [PostHog/posthog#17038]
- [x] Bug: https://github.com/PostHog/posthog/issues/17037
- [x] Black background color surveys need some work
- [x] In survey creation, User properties matching "Match by" is in odd space to the right 
- [x] Templating UI https://github.com/PostHog/posthog/issues/16018#issuecomment-1624362200

**Comment by joethreepwood** [comment]
- [x] Pressing 'Enter' in any of the color customization fields immediately saves the insight and takes you out of Edit mode

**Comment by joethreepwood** [comment]
- [ ] Deleting the default `0` in the 'Roll out to' field immediately defaults the answer to `100` (IMHO it should remain empty and default to 0 if no figure is entered)

**Comment by annikaschmid** [comment]
- [x] Another colour contrast issue: In the default colour scheme, the hover colour is very light, which makes it hard to see what is selected. This applies only for the actual site app, the preview is different. Those two should also work the same way. See the screenshot for the difference

- [x] Again for NPS, when you have single digit values and double digit values, the double digit field is wider than the single digit field. This should be the same

- [x] In the preview and the live survey popup, the 'x' to close is different. Adjust the one in the preview, which is currently the letter x

**Comment by annikaschmid** [comment]
![Screenshot 2023-08-16 at 10 13 45](https://github.com/PostHog/posthog/assets/14750837/e2b9039e-d390-497d-9c88-11b358078301)
![Screenshot 2023-08-16 at 10 12 29](https://github.com/PostHog/posthog/assets/14750837/0c058050-3431-441a-a08d-4f73ce19602b)

**Comment by annikaschmid** [comment]
Maybe: Set a min-width for the site app. If the text is very short, it looks quite bad, and can be hard to spot, especially on a big monitor. I know most users have longer text, But I think I would prefer if we have a fixed width for the popup

<img width="222" alt="Screenshot 2023-08-17 at 14 39 39" src="https://github.com/PostHog/posthog/assets/14750837/50e05989-e11a-40ce-84e6-68b8f77d12a8">

**Comment by annikaschmid** [comment]
- [x] In the attached screenshot, the spacing isn't ideal. I can't tell what it is, whether the content in general is too close together, or there is not enough spacing at the bottom compared at the top, but the whole thing looks quite dense and bottom-heavy. Can we try out adding more whitespace?

<img width="264" alt="Screenshot 2023-08-17 at 15 12 07" src="https://github.com/PostHog/posthog/assets/14750837/c8906bfa-0942-40ac-9e88-abe8363b5b66">

**Comment by annikaschmid** [comment]
- [x] The surveys screen is not responsive, when I am on a narrow screen, the preview is cut off. Other pages, like feature flags, behave differently. [Here](https://app.posthog.com/replay/0189fad3-9f6f-7d78-bc25-a2c39b3cbed9) is a recording of a user where you can observe it

**Comment by annikaschmid** [comment]
- [x] Can we please make the open text box the same width as the max-width for the text, and make sure they align? The text box is currently shorter in width than the text, which means sometimes they don't left-align, and that doesn't look good. I can provide a screenshot if needed

**Comment by annikaschmid** [comment]
- [x] For link surveys, question description and link should be arranged the other way around, to match how it shows up in the interview popup

- [x] I would like to be able to do paragraph breaks and bold text in the question, similar to how the original interview popup looked (looks better). Maybe the most flexible is to add markdown support? cc @corywatilo Maybe one for you, as you are considering working on the site app

<img width="862" alt="Screenshot 2023-08-31 at 11 28 49" src="https://github.com/PostHog/posthog/assets/14750837/46c6775a-ff9d-490a-a116-112bc788ceab">
<img width="353" alt="Screenshot 2023-08-31 at 11 31 24" src="https://github.com/PostHog/posthog/assets/14750837/9a44b9b2-47ac-4ba4-9ce1-aa07ab1de6b5">

<img width="875" alt="Screenshot 2023-08-31 at 11 30 11" src="https://github.com/PostHog/posthog/assets/14750837/76713499-22f2-43d0-a07e-1259a7f9cc79">

**Comment by annikaschmid** [comment]
From Slack: Site app in 'dark mode' doesn't look good: https://posthog.slack.com/archives/C034XD440RK/p1691583675158699

**Comment by annikaschmid** [comment]
https://github.com/PostHog/posthog/issues/17146

**Comment by annikaschmid** [comment]
Preview vs live version: We say "undefined" in the live version when no bound names are set

<img width="362" alt="Screenshot 2023-09-07 at 09 44 22" src="https://github.com/PostHog/posthog/assets/14750837/e750fe3a-1d66-403d-a8f9-f90a43b1fa73">

**Comment by annikaschmid** [comment]
Some feedback from Cory here he would like to get done before surveys go live: https://github.com/PostHog/posthog.com/pull/6580#issuecomment-1698409810

**Comment by corywatilo** [comment]
In addition to above, I've been thinking through the survey results pages. Originally we had talked about sticking to existing components to show results, but if you don't mind roping in @smallbrownbike, we may be able to shoot a little higher. Here are a couple examples.

_Note: Both wires are in the PostHog 3000 skin, so just ignore the parts that aren't relevant._

## 1-10 rating results

Adds

- Grouped bar chart with breakdown of results of showing the form
- A custom UI to visually represent the 1-10 scale, showing volume of responses for each
- Idea: Clicking on a segment of results would show the lightbox with users who chose that option

<img width="1347" alt="image" src="https://github.com/PostHog/posthog/assets/154479/7e3bbb2a-2153-484f-b64a-ecf1c34f8504">

## Freeform text results

- Masonry-style blocks with quotes and links to users

<img width="1311" alt="image" src="https://github.com/PostHog/posthog/assets/154479/80498104-dece-4cc7-8ed3-74d8c896c583">

---

These are just two examples (though 1-5 works the same as 1-10) - wouldn't be hard to do the rest with minimal new design components, but would really help make the results easier to consume!

One thought: are there any considerations for if these result cards get dragged into a notebook?

**Comment by liyiy** [comment]
> Grouped bar chart with breakdown of results of showing the form

I like this and we should go with it 💯 
There's just one more stat which is: `users who have started filling out the form but eventually dropped off`, which I assume can just be another section on that bar?

> A custom UI to visually represent the 1-10 scale, showing volume of responses for each

I think hogql insight does an okay job of this right now, and it has some convenient features connected to it, like seeing the persons modal of who submitted a score of `10`, so I'd be happy to punt on a new implementation for rating surveys

However hogql doesn't handle multiple choice question results very well, so this is the best we've got, we could improve this for sure 👀 

<img width="1167" alt="Screen Shot 2023-09-23 at 7 59 06 AM" src="https://github.com/PostHog/posthog/assets/25164963/de041d50-24bc-4d64-a713-4e68213140f1">

> Masonry-style blocks with quotes and links to users

I think having a "time" value could still be helpful here to provide a bit of structure/insight into how the responses flow in, and then allowing an optional free form mode for users to group responses themselves if they want to

**Comment by corywatilo** [comment]
I made some updates to above and now have wires for all survey types. Most notable global changes:

- Each question shows the type just above the question name
- The table breakdown uses the `th` to display the question name
- Added an "Abandoned" segment in the bar chart summary, showing people who started filling out the survey but didn't complete it

## 1-10 rating

![image](https://github.com/PostHog/posthog/assets/154479/9263764c-d56e-4a6e-bfe3-47800458e59c)

## Single choice / radio

![image](https://github.com/PostHog/posthog/assets/154479/73a1b64b-c05d-43cb-9a0d-1efec50b2538)

## Link

I didn't mock this, but it's essentially the same as the single choice pie chart, just showing "Clicked link" / "Didn't click link".

## Multi-select

In the table breakdown, multiple selections from the same person are separate by comma in the same column

![image](https://github.com/PostHog/posthog/assets/154479/7385f072-e644-421b-9de8-722f9a8df4b4)

## Freeform text

_I moved these results from the "Breakdown" section to the _Results_ section and it now lists the question type like others._

![image](https://github.com/PostHog/posthog/assets/154479/e2feed7b-6373-4fb6-aedd-999889b42c49)

## Multiple questions

![image](https://github.com/PostHog/posthog/assets/154479/255d0eb0-2e78-41ed-9af5-af561b2f8933)

In above, note how each question just stacks. (Red outlines below show each individual question and how they stack.)

In the breakdown, each question is in its own column.

![image](https://github.com/PostHog/posthog/assets/154479/f0684fa8-13a4-4f90-993c-dde539591994)

**Comment by jurajmajerik** [comment]
Regarding the _**abandoned**_ state in the stacked bar - we currently don't have an event that captures this, so that needs to be added first.

Quoting @neilkakkar:
> I think this makes sense only in multiple steps surveys, where we should start sending an event if they answered at least one question, and compute abandonment if they did not send the survey in the end.
