### ISSUE TITLE
Sprint August 21st - September 1st

### ISSUE THREAD

**Issue by mariusandra** [PostHog/posthog#17046]
# Global Sprint Planning

## 3 things that might take us down

1.  Nothing
2.
3.

## Retro: What can we do better next sprint?

1. NOTHING
2.
3.
4.
5.

# Team sprint planning

For your team sprint planning copy this template into a comment below for each team.

```
# Team ___

**Support hero:** ___

## Retro

<!-- Grab the high and low priority items from last time and add whether that item was completed or not -->

- 

## Hang over items from previous sprint

<!-- For each item, decide to re-prioritise (and add below) or deprioritise -->

- Item 1. prioritised/deprioritise

## OKR

1. OKR, status (red/yellow/green) and action points if yellow/red


### High priority

-

### Low priority / side quests

-

```

**Comment by mariusandra** [comment]
# Team Product Analytics

**Support hero:** 
- First week: Robbie, Marius & Marcus
- Second week: Thomas & Marcus (& week after)

## Retro

- Recordings and apps in the 3000 sidebar.
  - No time spent on this. Bugs got in the way.
- Onboarding Robbie!
  - 2/3 of the company showed up!

- Unsure of the exact workflow with Marcus
  - More sure now?
  - Look at the "elevated" queue.
- Help so far is pretty nice!
- Wedding was nice

## Hang over items from previous sprint

- Recordings and apps in the 3000 sidebar.
- HogQL?

## OKR

- 🟡  Port all our insights over to HogQL.
   - Started with lifecycle
- 🔴 Sleeker insight editor UI
   - Not started.

### High priority

- Web analytics: bounce & scroll rate @robbie-c (with @Twixes)
- HogQL: type system & continuing insights @mariusandra 
- Smart insight refresh @thmsobrmlr 
- PostHog 3000 - sleeker insight editor UI @Twixes 

### Low priority / side quests

-

**Comment by annikaschmid** [comment]
# Team ~David and Annika~ Monitoring

**Support hero:** @pauldambra 

## Retro

## Hang over items from previous sprint

🟢 Notebooks floating editor to configure Widgets - @daibhin
- Good for now, come back to it when we need more settings

🟢 Intelligent search for notebooks - (e.g. Show me Notebooks containing this recording) - @pauldambra
- PR is out, should be done by the end of the week 

🟢 Helping Pipeline team get Exports UI out the door - @benjackwhite
- Will be done by the end of the week

## Goals

🎯 Goal 1 : Notebooks on ProductHunt 🟢
🎯 Goal 2 : Next 5 great things for Replay 🟢
🥳 Filtering and searching UX
🤔 "Deep dive" e.g. Funnels -> list -> recording
🤔 Clips
🤔 Mobile replay


### High priority

_(Ben will be ~75% away this sprint)_

- Create, edit, save any Query from within a Notebook - @daibhin, @benjackwhite 
- Notebook sharing - @pauldambra 

### Low priority / side quests

- Wrap up / polish playlist filtering @daibhin 
- Monitor rollout of blob ingester with help from Pipeline @benjackwhite
- Think about Manoel's onboarding @benjackwhite, @annikaschmid

**Comment by EDsCODE** [comment]
# Team Data Warehouse

### Retro

**Product**
- [ ] sanitize credentials from sentry
- [x] UI for showing table relationships and modeled entities
- [ ] Brainstorm methods to scale. Current iteration won't scale

**Infra**
- [x] Integrate backup script into HouseWatch app with interface and schedule
- [x] Benchmark ClickHouse.cloud - Data is now fully available in EU from EU
- [x] Discus Issues with CH team on Tuesday of next week
- [ ] ~~Setup ClickPipes or Vector to EU~~

### High priority

**Product**
*Eric off first week

- [ ] ship internal MVP of data modeling + integrate with insights/filtering
- [ ] Work with anyone internally who is doing data analysis and get internal experience up to speed

Leftover:
- [ ] sanitize credentials from sentry
- [ ] Brainstorm methods to scale. Current iteration won't scale

**Infra**

- [ ] Continue working with CH org to enable deal-breaking features that are missing 
- [ ] Continue to tune CH.cloud to see if we can hit performance thresholds
- [ ] Integrate scheduling backups into HouseWatch

**Comment by raquelmsmith** [comment]
# Growth

**Support hero:** Me

## Retro


- [x] Figure out why usage reports are still flaky - seemed to have fixed themselves so 🤷‍♀️ 
- [x] Mock up a product-specific onboarding flow for eg. Feature flags or Experiments
- [x] Sync distinct IDs with billing - will be done this week
- [x] If sub'd to an old plan, allow downgrade - will be done this week
- [x] Fix SAML docs and values in-app 

## OKR

1. Starting to use and paying for new products feels frictionless
  - 🟡 In progress!
  - [ ] KR: We have separate onboarding for each product
  - [ ] KR: People don’t have to “upgrade” to different products, they just turn it on or start using it in some way.
3. Customers can pay a reasonable price for the value they’re receiving
  - 🟢 Done! Unless Data Warehouse or CDP become ready for launch.
  - [x] KR: Make sure rollout of new product analytics pricing goes well
  - [x] KR: Feature Flags pricing is launched, as well as Data Warehouse and CDP, if they are ready for launch

## This sprint
### High priority
- [ ] Build out new onboarding and upgrade flows
  - [x] Products page
  - [x] Product intro page
  - [ ] SDK selection component
- [x] Redirect users to EU during aurora upgrade

### Low priority / side quests
- [x] Prevent deleting customers from django admin https://github.com/PostHog/billing/pull/336
- [x] Change language/design of performance prompt https://github.com/PostHog/posthog/pull/17124

**Comment by neilkakkar** [comment]
# Team Feature Success

**Support hero:** @liyiy  

## Retro

1. Surveys: Controlling targeting for users who've seen surveys + data display for ratings/mcq surveys - @liyiy -> both will be done by Fri!
2. Make feature flag dashboard templates and flag autocapture ready for general availability - @neilkakkar  --> flag autocapture will be ready to go, decided to punt on dashboard templates & consume this into notebook templates


## Hang over items from previous sprint

Dashboard templates improvements


---

## OKRs

1. Make it easier for engineers to analyze the success of a feature
2. Build out an excellent user feedback product

### High priority

1. Surveys: [Polish UI](https://github.com/PostHog/posthog/issues/17038),  'Thank you' toast after responding, whitelabeling, Calculate Net Promoter Score, think about pricing - @liyiy
2. Build out MVP for notebook templates for feature success flow - @neilkakkar 

### Low priority / side quests

**Comment by ellie** [comment]
# Team Infrastructure

**Support hero:** @danielxnj 

### High priority

- configure aurora postgres so we can logically replicate @ellie 
- postgres upgrade scheduling + action @danielxnj 
- victoriametrics enterprise setup @ellie 
- infra resource tagging by product @frankh 

### Low priority / side quests

- Google SSO on OpenVPN @frankh

**Comment by tiina303** [comment]
# Team Pipeline

**Support hero:** Xavier/Tomas, Tiina

## Retro



- @benjackwhite - so excited about pipeline: Batch export UI is rolling out 🥳 
- @xvello - primary oncall - still too many things breaking 🔥 🧨  so not as much progress on PG
- @tomasfarias - great sprint
- @tiina303 - great to have Marcus, mostly handling support in Zendesk, so I was able to work on apps
- @MarconLP 

## Hang over items from previous sprint



- reworking apps page to show exports somewhere
- blob ingestion, but made progress there within session recordings team
- pg destination may slip

## OKR

1. 🔴 Define and enforce limits on what users can send us - Owner @xvello 
2. 🟢 Deprecate and improve apps
    - 🟢 Finish batch exports so we can deprecate export apps - Owner @tomasfarias
    - 🟡 Remove all processing apps - Owner @tiina303
    	-> New users can't install dangerous apps, will focus on onEvent / other apps ; we're going to keep stateless processEvent apps
3. Figure out the pipeline architecture for the next 2 years - Owner @timgl

### High priority

1. PG, Redshift - migration email sent @tomasfarias 
2. BigQuery @tomasfarias 
3. PG continued @xvello 
   1. pluginStorage to separate PG instance (why: stop taking down the app) & 
   2. readOnly for team/token/action
4. Plan out the future for onEvent apps and review existing ones @tiina303

**Comment by XavierVelo** [comment]
HelloI've received email regarding this GH project, I've never participated in. I think there's some kind of mistake, there is another guy with similar nick:&nbsp;https://github.com/xvello &amp; here's me mine https://github.com/XavierVelo. Please make correction.T.Od: "Tiina Turban" ***@***.***&gt;Do: "PostHog/posthog" ***@***.***&gt;; Wysłane: 17:00 Środa 2023-08-16Temat: Re: [PostHog/posthog] Sprint August 21st - September 1st (Issue #17046)

Team Pipeline
Support hero: Xavier/Tomas, Tiina
Retro


@benjackwhite - so excited about pipeline: Batch export UI is rolling out 🥳
@xvello - primary oncall - still too many things breaking 🔥 🧨  so not as much progress on PG
@tomasfarias - great sprint
@tiina303 - great to have Marcus, mostly handling support in Zendesk
@MarconLP

Hang over items from previous sprint


reworking apps page to show exports somewhere
blob ingestion, but made progress there within session recordings team
pg destination may slip

OKR


OKR, status (red/yellow/green) and action points if yellow/red


🔴 Define and enforce limits on what users can send us - Owner @XavierVelo


Deprecate and improve apps



Finish batch exports so we can deprecate export apps - Owner @tomasfarias
🟡 Remove all processing apps - Owner @tiina303

New users can't install dangerous apps, will focus on onEvent / other apps




Figure out the pipeline architecture for the next 2 years - Owner @timgl

High priority

PG, Redshift - migration email sent @tomasfarias
BigQuery @tomasfarias
PG continued @xvello


pluginStorage to separate PG instance (why: stop taking down the app) &amp;
readOnly for team/token/action


Plan out the future for onEvent apps and review existing ones @tiina303

Low priority / side quests
