### ISSUE TITLE
Omniscience powers for PostHog staff on PostHog Cloud

### ISSUE THREAD

**Issue by Twixes** [PostHog/posthog#1705]
## Is your feature request related to a problem?

Users quite often send us links to PostHog views where they're seeing some data that isn't right, in the form " https://app.posthog.com/person/<some_id>". That does not give us any edge though, as such a URL only works for users logged into a specific team.

## Describe the solution you'd like

It'd be pretty useful if (with user permission) we could peek into such a page and see the problem. Unfortunately that'd require rebuilding our URL scheme to include team and maybe also organization, Amplitude-style.

## Describe alternatives you've considered

Going into the database each time to extract the same data.

**Comment by paolodamico** [comment]
I would definitely add an **extra explicit** allow access switch on the settings page. I would even do something similar to what Zendesk does in which granting permission can only be done for a pre-defined amount of time.

**Comment by Twixes** [comment]
Yep, absolutely, consent is important. Fun idea (not the easiest way to go about this): a popup "PostHog staff requests visibility into your account for support" with "Allow for 1 hour" and "Disallow" answers.

**Comment by paolodamico** [comment]
Already possible.
