### ISSUE TITLE
The word "false" appears in the notification when adding a member to a project

### ISSUE THREAD

**Issue by edhgoose** [PostHog/posthog#17050]
## Bug description

When adding a member to a page, the notification includes the word "false" unexpectedly.

Everything else works fine.

## How to reproduce

1. Visit project settings for a project, e.g. https://eu.posthog.com/project/settings
2. Add a member to the project
3. Observe the member is added, but the word false appears in the notification

<img width="431" alt="CleanShot 2023-08-16 at 10 03 50@2x" src="https://github.com/PostHog/posthog/assets/1108173/a7312957-5658-466b-b5be-e5a1719f2879">

## Environment

- [x] PostHog Cloud EU, project ID: 3310

**Comment by Arun-chaitanya** [comment]
Fixed this @edhgoose
