### ISSUE TITLE
Next.js App Router docs specify non-existent `getData()` function

### ISSUE THREAD

**Issue by t3dotgg** [PostHog/posthog#17084]
The docs for Next.js specify that you should fire analytics events "using the Next.js `getData()` function", which is not a Next.js thing

https://posthog.com/docs/libraries/next-js#:~:text=using%20the%20Next.js%20getData()%20function

**Comment by benjackwhite** [comment]
This should really be on submitted at https://github.com/PostHog/posthog.com/issues. @ivanagas I believe you wrote the post originally so probably know what was intended here?

**Comment by neilkakkar** [comment]
cc: @ivanagas was this supposed to be `getServerSideProps` ?

**Comment by ivanagas** [comment]
Fix is here: https://github.com/PostHog/posthog.com/pull/6541

It's just a plain server-side function, based on Next.js docs at the time, I thought it specifically needed to be named `getData()` 😅

**Comment by t3dotgg** [comment]
> Fix is here: [PostHog/posthog.com#6541](https://github.com/PostHog/posthog.com/pull/6541)
> 
> It's just a plain server-side function, based on Next.js docs at the time, I thought it specifically needed to be named `getData()` 😅

Quality change, thank you!
