### ISSUE TITLE
Better sorting for paths

### ISSUE THREAD

**Issue by mariusandra** [PostHog/posthog#1709]
It seems that the way paths are ordered depends on the order of the input nodes. We should be smarter and sort the data beforehand to avoid things like this:

![image](https://user-images.githubusercontent.com/53387/94147472-9bfe8980-fe75-11ea-94ad-5fa9170e4099.png)

The lowest `/demo` -> `/demo/1` in the second column could be moved to the top of the second column.

That's still a mild example. Some other cases can look much worse, especially when there are only a few items in the list:

![image](https://user-images.githubusercontent.com/53387/94147746-00214d80-fe76-11ea-92db-7e42294f3413.png)

**Additional context**

This came up with work on https://github.com/PostHog/posthog/pull/1657

**Comment by Twixes** [comment]
This seems better with the new query.
