### ISSUE TITLE
Event explorer: 'yesterday' selection broken

### ISSUE THREAD

**Issue by MarconLP** [PostHog/posthog#17094]
## Bug description

When viewing `yesterday` events in the event explorer, no events are being shown.
<img width="1164" alt="Screenshot 2023-08-18 at 16 19 03@2x" src="https://github.com/PostHog/posthog/assets/13001502/75094062-d541-468c-b1d6-8690690fc71b">

## How to reproduce

1. Open the event explorer
2. make sure there are events that are over 24 hours old
2. Filter for `yesterday`
3. See "There are no matching events for this query"

## Environment

- [X] PostHog Cloud US, project ID: [please provide from https://app.posthog.com/project/settings#project-id]
- [X] PostHog Cloud EU, project ID: [please provide from https://eu.posthog.com/project/settings#project-id]
- [ ] PostHog Hobby self-hosted with `docker compose`, version/commit: [please provide]
- [ ] PostHog self-hosted with Kubernetes (deprecated, see ["Sunsetting Kubernetes support"](https://posthog.com/blog/sunsetting-helm-support-posthog)), version/commit: [please provide]

## Additional context

related ticket: https://posthoghelp.zendesk.com/agent/tickets/5171

**Comment by MarconLP** [comment]
seems like all queries with a “before” are broken

**Comment by Twixes** [comment]
Resolved by #16965.
