### ISSUE TITLE
User paths

### ISSUE THREAD

**Issue by jamesefhawkins** [PostHog/posthog#171]
**Is your feature request related to a problem? Please describe.**
I am a developer that wants to work on features that make a difference.

A simplified example for many newer projects is "if someone comes into my app, do they go somewhere weird then leave". If in this case I know as a developer, I need to either improve the "somewhere weird" page OR I need to stop them going there in the first place. That will mean my work actual helps users stay in the application.

**Describe the solution you'd like**
I want to be able to visualise a **flow** diagram:

Initial landing page -> next page(s) -> next page(s) -> next page(s) -> etc. It should perhaps go 5 items deep, then is expandable further optionally.

The list of 'next page(s)', should be a list of **every** page people then go to, with the size of the box based on the percentage that follow that path. It should show the percentage and the actual volume.

* It'd be nice to do this as a series of ANY action, not just URL visits. That'd make it more powerful than anything else available.
* It'd be awesome to be able to hover over the step of the flow diagram to see the actual users that followed a particular path. That'd mean you could then answer "and WHICH users followed this path', to lead to a deeper understanding
* Nice to have for now: I need to be able to segment the above flow by user properties (specifically, by UTM tag)
* If the volume of "next page(s)" is very big - as users could go into hundreds of different directions, then we need to limit how many are visible so the diagram doesn't become unwieldy, then offer a click to expand button vertically (see google analytics for a nice way to do this)

**Describe alternatives you've considered**
Very complex SQL would be the only way.

**Additional context**
Google Analytics does a great job of this, but lacks the ability to view the actual users and it lacks the ability to create a series of actions/events - it is only page view based.

**Comment by allan-simon** [comment]
The SQL query does not necessarily needs to be complex, I think here that's the same kind of problematic as with doing a pivot table ,  doing it in SQL is quite complex , but if your sql only gives raw data (i.e 3 columns ,  x , y , value ) and you let your view layer handle the representation, the problem becomes pretty simple.

More specifically, you can certainly modelize this like a linked list,  where each event has a `previous_event_id` ? and you let your view build the graph.
