### ISSUE TITLE
Normalize paths options does not work when breaking down by "current url"

### ISSUE THREAD

**Issue by MarconLP** [PostHog/posthog#17119]
## Bug description

The `Normalize paths` option does not work
![Screenshot 2023-08-21 at 12 34 25@2x](https://github.com/PostHog/posthog/assets/13001502/27720f56-582f-4060-b184-32b72a2b37c3)
example insight: https://app.posthog.com/insights/jhWt17fZ

## How to reproduce

1. Create an insight
2. Break down by `Current URL`
3. Enable `Normalize paths` option
4. No change in the results

## Environment

- [X] PostHog Cloud US, project ID: https://posthoghelp.zendesk.com/agent/tickets/5207
- [ ] PostHog Cloud EU, project ID: [please provide from https://eu.posthog.com/project/settings#project-id]
- [ ] PostHog Hobby self-hosted with `docker compose`, version/commit: [please provide]
- [ ] PostHog self-hosted with Kubernetes (deprecated, see ["Sunsetting Kubernetes support"](https://posthog.com/blog/sunsetting-helm-support-posthog)), version/commit: [please provide]

## Additional context

related ticket: https://posthoghelp.zendesk.com/agent/tickets/5207

**Comment by Twixes** [comment]
I believe the problem is that path normalization works, but differently than might be expected here. It only removes trailing slashes, question marks, and hashes, but doesn't actually cut out params if there are some. I think these should be two different normalization modes, to satisfy all use cases and maintain backwards compatibility.

**Comment by SamKomesarook** [comment]
Upping this. The fact that we have users navigating with route params makes the `normalize paths` option useless.

**Comment by mariusandra** [comment]
Hey, you can break down by a HogQL expression, with a [function from here](https://posthog.com/docs/hogql/clickhouse-functions#urls) (or [from the clickhouse docs here](https://clickhouse.com/docs/en/sql-reference/functions/url-functions)) to do whatever you want with the URL before displaying it.

**Comment by SamKomesarook** [comment]
@mariusandra Thanks for that, however it would still be good to have the paths normalised with a toggle, as we don't really want to add a breakdown to affect the insight in our dashboards.

**Comment by SamKomesarook** [comment]
@mariusandra @Twixes @MarconLP any update on this?

**Comment by mariusandra** [comment]
We don't have updates on this.

**Comment by MarconLP** [comment]
A current workaround for this is to use a HogQL breakdown like this: `cutQueryStringAndFragment(properties.$current_url)`

**Comment by MarconLP** [comment]
+1 https://posthoghelp.zendesk.com/agent/tickets/7594 (moved to PostHog: https://us.posthog.com/project/2/support/tickets/10569)
