### ISSUE TITLE
Add an intuitive way back to the dashboard after editing an insight

### ISSUE THREAD

**Issue by MarconLP** [PostHog/posthog#17149]
## Is your feature request related to a problem?

When viewing a dashboard -> editing an insight -> saving. There is no get way to get back to the dashboard view

## Describe the solution you'd like

there is already an alert with a link back to the insights. (maybe link to the previous dashboard depending on the context)

## Additional context

related ticket: https://posthoghelp.zendesk.com/agent/tickets/5250

**Comment by Twixes** [comment]
I believe this is a duplicate of #12016
