### ISSUE TITLE
Create sense of how popular surveys are from the overview page (ux tweak)

### ISSUE THREAD

**Issue by jamesefhawkins** [PostHog/posthog#17146]
## Is your feature request related to a problem?

I was curious what we've asked users and what we've learned from surveys, so I looked at the surveys page.

However, I can't tell which surveys have generated a bunch of responses.
<img width="1740" alt="Screenshot 2023-08-22 at 14 15 08" src="https://github.com/PostHog/posthog/assets/47497682/d06141fa-a144-414f-9799-da5c9f523eff">

## Describe the solution you'd like

A column that shows the response number in the above overview.

## Describe alternatives you've considered

Click into each one

**Comment by jasonyavorsky** [comment]
Howdy, I was taking a look at this issue as a `good first issue` and it looks like perhaps it's already implemented. On the list of surveys I see a `responses` column. Let me know if there's something more to be done and I'd be happy to take a look, otherwise this can maybe be closed.

**Comment by neilkakkar** [comment]
That's right, this is good to close, thanks @jyavorska !
