### ISSUE TITLE
How to capture page view manually through API?

### ISSUE THREAD

**Issue by rousan** [PostHog/posthog#1716]
## Bug description

There is an API (`.capture()`) to capture events, but is there any API to capture a page view through API like `.page(pagePath`)? I need this for using PostHog in a react app, PostHog does not capture URL changes through `react-router`.

## Expected behavior

There should an API to capture a page view manually through API.

**Comment by mariusandra** [comment]
Hi @rousan 

You can use 

```js
posthog.capture('$pageview');
```

See more [here](https://posthog.com/docs/integrations/js-integration#one-page-apps-and-page-views).
