### ISSUE TITLE
Can't add code snippet for "Other" backend language Option

### ISSUE THREAD

**Issue by Instrumedley** [PostHog/posthog#17180]
## Bug description

Hi guys, I'm a developer and I'd love to try out your product. My project is in Kotlin with Spring Boot.
I created an account on https://eu.posthog.com/ and I'm already stuck on the "Add code snippet" step which is the very first one 🫤

When selecting "Other" as option for Backend it just brings me back to the start. No way to move forward.
I attached a screen record of the issue.

How can I proceed to try the product?

## Environment

- [X] PostHog Cloud US, project ID: [please provide from https://app.posthog.com/project/settings#project-id]
- [ ] PostHog Cloud EU, project ID: [please provide from https://eu.posthog.com/project/settings#project-id]
- [ ] PostHog Hobby self-hosted with `docker compose`, version/commit: [please provide]
- [ ] PostHog self-hosted with Kubernetes (deprecated, see ["Sunsetting Kubernetes support"](https://posthog.com/blog/sunsetting-helm-support-posthog)), version/commit: [please provide]

https://github.com/PostHog/posthog/assets/1420617/b2b735ce-e4e8-4b19-95e0-10105edf5336

**Comment by raquelmsmith** [comment]
Thanks for raising this @Instrumedley, will look into a fix. 

In the meantime you can get the code snippets you need from our [SDK docs](https://posthog.com/docs/libraries). 

To get through the onboarding just select "web" and then "continue" and it'll take you to a page to listen for events - it'll verify event receipt regardless of which SDK you use to send them. (if you want to skip through further just click the "continue without verifying" button)

**Comment by raquelmsmith** [comment]
This exact flow no longer exists 👍
