### ISSUE TITLE
Provide non interactive Posthog setup, for instance via manage.py subcommand

### ISSUE THREAD

**Issue by stephane-klein** [PostHog/posthog#1719]
Hi,

I integrate Posthog (with Posthog docker image) in my development environment.

I need to setup Posthog via script.

For the previous Posthog version, I used this script:

```
import sys
import requests

client = requests.session()

url = 'http://127.0.0.1:8000/setup_admin'

client.get(url)
if 'csrftoken' in client.cookies:
    csrftoken = client.cookies['csrftoken']
else:
    csrftoken = client.cookies['csrf']

r = client.post(
    url,
    data={
        'email': 'admin@example.com',
        'password': 'password',
        'company_name': 'Example',
        'emailOptIn': 'off',
        'name': 'admin',
        'csrfmiddlewaretoken': csrftoken
    },
    headers=dict(Referer=url)
)
```

This script didn't work because Posthog now provide `/preflight` page:

<img width="400" src="https://user-images.githubusercontent.com/54498080/94268444-750b8a80-ff3d-11ea-8b07-2e8962f8c183.png">

What do you think to provide a `manage.py` subcommand to setup Posthog via cli?

Best regards,
Stéphane

**Comment by Twixes** [comment]
Hi Stéphane! Do you mean setting up just an account to develop and test PostHog, or setting up a production analytics instance?

**Comment by stephane-klein** [comment]
> Do you mean setting up just an account to develop and test PostHog, or setting up a production analytics instance?

@Twixes For development environment on my laptop.

This is my current solution.

I took my inspiration on [`posthog/management/commands/setup_review.py`](https://github.com/PostHog/posthog/blob/master/posthog/management/commands/setup_review.py) to implement:

```
# In setup_admin.py
from posthog.models import User

organization, team, user = User.objects.bootstrap(
    company_name="Example",
    email="admin@example.com",
    password="password",
    first_name="John Doe",
    team_fields={
        "name": "Example",
        "completed_snippet_onboarding": True,
        "event_names": ["$pageview", "$autocapture"],
        "event_properties": ["$current_url", "$browser", "$os"],
    }
)
```

Next I execute:

```
$ docker-compose exec -T web ./manage.py shell < scripts/setup_admin.py
```

**Comment by Twixes** [comment]
That's something we actually do provide already! It's command `manage.py setup_review` and it gives you a test account with email `test@posthog.com` and password `pass`, with some demo data.

**Comment by Twixes** [comment]
I don't quite understand the difference between your solution and `setup_review`, could you clarify?

**Comment by stephane-klein** [comment]
> That's something we actually do provide already! 

@Twixes I can change email, password, project name…

**Comment by Twixes** [comment]
So you mean `setup_review` with custom settings?

**Comment by stephane-klein** [comment]
> So you mean setup_review with custom settings?

Yes and if possible, one `manage.py` subcommand to get first Team API Key value 🙏

**Comment by Twixes** [comment]
I've added a command for API keys, but I encourage you to have a go at enhancing `setup_review` (now more aptly `setup_dev`) the way you see fit yourself. :) We're open-source and open to community contributions.

**Comment by Twixes** [comment]
Please do that on branch `dev-commands` (that is pull request #1720)!
