### ISSUE TITLE
Action selector,  can't use attribute selector

### ISSUE THREAD

**Issue by allan-simon** [PostHog/posthog#172]
If I set an action with a class attribute `.something` , it works correctly

however if i create an action with `[data-tracking-class="check-view-button-yes"]` , it does not. (I've tripled check with `document.querySelectorAll('[data-tracking-class="check-view-button-yes"]')` that I got result.

This is a pity, that we historically be using the `data-tracking-id`  and `data-tracking-class` attributes in our code, for the purpose of avoiding the next developers to break action tracking while refactoring css/javascript

**Comment by timgl** [comment]
@allan-simon Thanks Allan, that should be fixed now. We basically had to implement our own queryselector parser in the Django ORM so I'd expect some more issues to crop up. Just let us know :-)
