### ISSUE TITLE
Person preview pop up disappears off screen

### ISSUE THREAD

**Issue by liyiy** [PostHog/posthog#17213]
## Bug description

*Please describe.*  
*If this affects the front-end, screenshots would be of great help.*  

Go to a survey with persons -> click on person -> person preview shows up but out of display

![Screenshot 2023-09-03 at 17 56 13@2x](https://github.com/PostHog/posthog/assets/13001502/2295cca8-ff42-4d59-bb4a-0285bdebaadd)

*If you are on PostHog Cloud it would be really valuable if you can share any links where the problem occurs. This speeds up our ability to troubleshoot tremendously.* 

## How to reproduce

1.
2.
3.

## Environment

- [ ] PostHog Cloud US, project ID: [please provide from https://app.posthog.com/project/settings#project-id]
- [ ] PostHog Cloud EU, project ID: [please provide from https://eu.posthog.com/project/settings#project-id]
- [ ] PostHog Hobby self-hosted with `docker compose`, version/commit: [please provide]
- [ ] PostHog self-hosted with Kubernetes (deprecated, see ["Sunsetting Kubernetes support"](https://posthog.com/blog/sunsetting-helm-support-posthog)), version/commit: [please provide]

**Comment by dmarticus** [comment]
lol I fixed this forever ago: https://github.com/PostHog/posthog/pull/24298
