### ISSUE TITLE
Sprint September 4th - September 15th

### ISSUE THREAD

**Issue by mariusandra** [PostHog/posthog#17246]
# Global Sprint Planning

## 3 things that might take us down

1.
2.
3.

# Team sprint planning

For your team sprint planning copy this template into a comment below for each team.

```
# Team ___

**Support hero:** ___

## Retro

<!-- Grab the high and low priority items from last time and add whether that item was completed or not -->

- 

## Hang over items from previous sprint

<!-- For each item, decide to re-prioritise (and add below) or deprioritise -->

- Item 1. prioritised/deprioritise

## OKR

1. OKR, status (red/yellow/green) and action points if yellow/red


### High priority

-

### Low priority / side quests

-

```

**Comment by mariusandra** [comment]
# Team Product Analytics

**Support hero:** 
- First week: Thomas & Marcus
- Second week: Marius & Marcus (& week after)

- Michael off for the entire sprint

## Retro

- Web analytics: bounce & scroll rate @robbie-c (with @Twixes)
  -  It depends. Collecting data, but not showing it. Will use HogQL for displaying.
- HogQL: type system & continuing insights @mariusandra
  - Type system: minimal progress, but progressing.
- Smart insight refresh @thmsobrmlr
  - Not yet smart. PR open. Strange query_log test failures.
- PostHog 3000 - sleeker insight editor UI @Twixes
  - Sleek visual regression tests.
  - Security is top notch as well
  - Choose between having a weekend or two weekends: Monday and Sunday 😍 

## Hang over items from previous sprint

- Insight lifecycle query.
- HogQL type system.
- Sleeker insight editor UI


## OKR

- 🟡  Port all our insights over to HogQL.
   - Started with lifecycle
- 🔴 Sleeker insight editor UI
   - Not started (see above)

### High priority

- Web analytics: wrap up lifecycle insight, add bounce rate insight @robbie-c
- Start porting over the insights to HogQL @thmsobrmlr 
- Look into performance @mariusandra 
- Sangria @Twixes 

### Low priority / side quests

- HogQL: continuing adding typing support @mariusandra

**Comment by pauldambra** [comment]
# Team M-ore people-onitoring

**Support hero:** @benjackwhite  

## Retro

## Hang over items from previous sprint

_(Ben was ~75% away this sprint)_

* 🟢  Create, edit, save any Query from within a Notebook - @daibhin, @benjackwhite 
    * will need a little bit of follow-up/polish but we shipped improvements
* 🔴  Notebook sharing - @pauldambra 
    * I was all blobby and support all of the time
* 🟢  Wrap up / polish playlist filtering @daibhin 
* 🟡  Monitor rollout of blob ingester with help from Pipeline @benjackwhite
    - we're on 2% traffic, scaling is smoother, working on moving ingestion completely to new pipeline so that lag isn't as affecting for users

## Goals

🎯 Goal 1 : Notebooks on ProductHunt 🟢
🎯 Goal 2 : Next 5 great things for Replay 🟢
🥳 Filtering and searching UX => 🟡 done a lot here but more to do
🤔 "Deep dive" e.g. Funnels -> list -> recording => 🟡 we might get to this
🤔 Clips => 🟡 we might get to this
🤔 Mobile replay => 🔴 Manoel enables this in Q4

### High priority

🎓 onboarding Manoel in week 1 🎉 

* blobby to 100% - @pauldambra and @benjackwhite 
* insights experience in notebooks - @daibhin 
* notebooks polish polish polish - all
    * how do we know we're finished - @annikaschmid enjoys working with it

### Low priority / side quests

* ~~carry-over notebooks sharing - @pauldambra~~
* support feature success in notebooks usage - @daibhin 
* intelligent search across title and content - @pauldambra

**Comment by EDsCODE** [comment]
# Team Data Warehouse

### Retro

**Product**
*Eric off first week

- [x] ship internal MVP of data modeling + integrate with insights/filtering
- [ ] Work with anyone internally who is doing data analysis and get internal experience up to speed


**Infra**
- [x] Continue working with CH org to enable deal-breaking features that are missing 
- [x] Continue to tune CH.cloud to see if we can hit performance thresholds
- [x] Integrate scheduling backups into HouseWatch

### High priority

**Product**
- [ ] Work with anyone internally who is doing data analysis and get internal experience up to speed
     - [ ] common query paths (how to easily handle joins on json data)
     - [ ] support JSON s3 type

Leftover:
- [ ] sanitize credentials from sentry
- [ ] Brainstorm methods to scale. Current iteration won't scale

**Infra**

- [ ] Wrap up HouseWatch deployments for EU / US 
- [ ] Test backups made by HouseWatch
- [ ] Setup incremental backup functionality on HouseWatch
- [ ] Make decision on CH.cloud vs hosted CH

**Comment by fuziontech** [comment]
# Team Data Warehouse

### Retro

**Product**
- [ ] sanitize credentials from sentry
- [x] UI for showing table relationships and modeled entities
- [ ] Brainstorm methods to scale. Current iteration won't scale

**Infra**
- [x] Continue working with CH org to enable deal-breaking features that are missing 
- [x] Continue to tune CH.cloud to see if we can hit performance thresholds
- [x] Integrate scheduling backups into HouseWatch

### High priority

**Product**
*Eric off first week

- [ ] ship internal MVP of data modeling + integrate with insights/filtering
- [ ] Work with anyone internally who is doing data analysis and get internal experience up to speed

Leftover:
- [ ] sanitize credentials from sentry
- [ ] Brainstorm methods to scale. Current iteration won't scale

**Infra**

- [ ] Wrap up HouseWatch deployments for EU / US 
- [ ] Test backups made by HouseWatch
- [ ] Setup incremental backup functionality on HouseWatch
- [ ] Make decision on CH.cloud vs hosted CH

**Comment by raquelmsmith** [comment]
# Growth & Data
(I'm adopting Stuti while she's with us)

**Support hero:** Me

## Retro


- [x] Build out new onboarding and upgrade flows
  - [x] Products page
  - [x] Product intro page
  - [x] SDK selection component
    - In progress, hopefully done by Friday for at least one product (have to add all the snippets per product)
- [x] Redirect users to EU during aurora upgrade
- [x] Prevent deleting customers from django admin https://github.com/PostHog/billing/pull/336
- [x] Change language/design of performance prompt https://github.com/PostHog/posthog/pull/17124
- [x] Credit customers who were charged for duplicate events https://github.com/PostHog/billing/pull/338

## OKR

1. Starting to use and paying for new products feels frictionless
  - 🟡 In progress!
  - [ ] KR: We have separate onboarding for each product
  - [ ] KR: People don’t have to “upgrade” to different products, they just turn it on or start using it in some way.
3. Customers can pay a reasonable price for the value they’re receiving
  - 🟢 Done! Unless Data Warehouse or CDP become ready for launch.
  - [x] KR: Make sure rollout of new product analytics pricing goes well
  - [x] KR: Feature Flags pricing is launched, as well as Data Warehouse and CDP, if they are ready for launch

## This sprint
### High priority
- [ ] Continue with onboarding flows @raquelmsmith 
- [ ] Change MRR per product reporting to be calculated based on usage, not invoices @raquelmsmith 
- [x] Understand where most performance issues are happening @stuti90 
- [ ] Start understanding what our real activation metric should be @stuti90 

### Low priority / side quests

**Comment by ellie** [comment]
# Team Infrastructure

**Support hero:** @ellie

## Retro




- [ ] configure aurora postgres so we can logically replicate @ellie 
- [x] postgres upgrade scheduling + action @danielxnj 
- [x] victoriametrics enterprise setup @ellie 
- [x] infra resource tagging by product @frankh

### This sprint
- Get a mvp of capture-rs up and running @ellie 
- Fix current terraform drifts @danielxnj 
- Start splitting the state into smaller pieces organized by modules, to reduce the risk of corruption and speed up deployments @danielxnj 
- switch fully to karpenter in EU (hoping will reduce costs at least 10%) @frankh 
- finish up exit nodes and rotate VPN stuff (delete old VPN, get github actions using tailscale exit nodes, we have SSO VPN for backup access) @frankh 
- figure out our docker mirror suddenly costing $3k/month or replace it @frankh

**Comment by neilkakkar** [comment]
# Team Feature Success

**Support hero:** @liyiy then @neilkakkar 

Off days: Neil 3 days, Li 1 day
Annika on monitoring onboarding

## Retro

1. Surveys: [Polish UI](https://github.com/PostHog/posthog/issues/17038),  'Thank you' toast after responding, whitelabeling, Calculate Net Promoter Score, think about pricing - @liyiy -> whitelabeling is done, basic thank you message, and some UI polishing is done. NPS will rollover.
2. ~~Build out MVP for notebook templates~~ for feature success flow - @neilkakkar - well, turns out there's much to do here. Have broken things down here: https://github.com/PostHog/posthog/issues/17134

## Hang over items from previous sprint

---

## OKRs

1. Make it easier for engineers to analyze the success of a feature
2. Build out an excellent user feedback product

### High priority

1. Surveys: Calculate NPS, multiple questions, tests - @liyiy 
2. Continue building out components for notebook templates for flags here: https://github.com/PostHog/posthog/issues/17134 - @neilkakkar 

### Low priority / side quests

**Comment by tiina303** [comment]
# Team Pipeline

**Support hero:** @MarconLP  effectively

## Retro



- @tomasfarias - went well, glad to have had time to implement the missing features needed for S3
- @xvello - pg connections scale-up helped ingestion be happier, good that we understood that we're PG bound.
- @tiina303 -  happy to finally have figured out the burning fire of onevent and webhooks ... elements parsing

## OKR

1. 🔴 Define and enforce limits on what users can send us - Owner @xvello 
2. 🟢 Deprecate and improve apps
    - 🟢 Finish batch exports so we can deprecate export apps - Owner @tomasfarias
    - 🟡 Remove all processing apps - Owner @tiina303
    	-> this has changed: we're keeping stateless apps, good progress and plan here for all the apps
3. 🟠  Figure out the pipeline architecture for the next 2 years - Owner @timgl
   - we have some stuff, but we don't have everything and export / webhook side is the focus atm

### High priority

- no-one needs to use advanced GeoIP app anymore @bretthoerner 
- skip elements parsing for everyone we can @tiina303 
- start using PG read replica & dedicated Redis in plugin-server @xvello 
- Finish S3 migrations & ship BigQuery @tomasfarias
