### ISSUE TITLE
Bug: Cohorts don't return correct result if you paste in comma separated values

### ISSUE THREAD

**Issue by joethreepwood** [PostHog/posthog#17242]
## Bug description

Context: https://posthog.slack.com/archives/C05PEM6A3Q9/p1693328936882429

@raquelmsmith and I had a list of 85 Org_Ids. If you paste them into the cohort field all as one, it recognises them...but doesn't return the correct result. You have to paste them in one by one, despite https://github.com/PostHog/posthog/issues/16975

Clearly a big bug, leading to incorrect cohorts. 

## How to reproduce

1. Get a big list of org_Ids (see here)
2. Paste them into the cohort
3. Get a bad result

## Environment

- [ ] PostHog Cloud US, project ID: [please provide from https://app.posthog.com/project/settings#project-id]
- [ ] PostHog Cloud EU, project ID: [please provide from https://eu.posthog.com/project/settings#project-id]
- [ ] PostHog Hobby self-hosted with `docker compose`, version/commit: [please provide]
- [ ] PostHog self-hosted with Kubernetes (deprecated, see ["Sunsetting Kubernetes support"](https://posthog.com/blog/sunsetting-helm-support-posthog)), version/commit: [please provide]

**Comment by neilkakkar** [comment]
This is now fixed! :) - let me know if you still face issues Joe
