### ISSUE TITLE
Using formula in trend insight results in query error

### ISSUE THREAD

**Issue by ryan-pypestream** [PostHog/posthog#17258]
## Bug description

When adding a formula to a trend insight, the result is "There was an error completing this query"

## How to reproduce

1. Create new trend insight
2. Keep default variable "Pageview" 
3. Click "Enable Formula Mode"
4. Enter "PAGEVIEW" in formula text box

Result: "There was an error completing this query"

![FormulaErrorOnTrendInsight](https://github.com/PostHog/posthog/assets/106977715/16bb69a1-94c6-4bbb-9943-128207758d7a)

## Environment

- [X] Codespaces on posthog-foss repository, commit 3891467d14c7dd5e22b865f7aa42d664c418bbdc
- [ ] PostHog Cloud US, project ID: [please provide from https://app.posthog.com/project/settings#project-id]
- [ ] PostHog Cloud EU, project ID: [please provide from https://eu.posthog.com/project/settings#project-id]
- [ ] PostHog Hobby self-hosted with `docker compose`, version/commit: [please provide]
- [ ] PostHog self-hosted with Kubernetes (deprecated, see ["Sunsetting Kubernetes support"](https://posthog.com/blog/sunsetting-helm-support-posthog)), version/commit: [please provide]

**Comment by MarconLP** [comment]
Hi Ryan, the formula mode requires you to enter a variable like A, B, or C. You can see the assigned variable next to that event.
![Screenshot 2023-08-31 at 10 01 44@2x](https://github.com/PostHog/posthog/assets/13001502/c4c7740a-dec3-4438-ba4a-0de715d8e7ff)

**Comment by ryan-pypestream** [comment]
Thanks! I'm so glad this is just my own misunderstanding and not a bug!
