### ISSUE TITLE
Cohorts property id filter copy and pasting values bug

### ISSUE THREAD

**Issue by liyiy** [PostHog/posthog#17254]
## Bug description

*Please describe.*  
*If this affects the front-end, screenshots would be of great help.*  

ex: We want to create a cohort based on certain organization IDs. When we copy and paste that list into the property filter in cohort creation, the values paste properly in the field, but the cohort persons return based on the first ID only.

https://posthoghelp.zendesk.com/agent/tickets/5430

*If you are on PostHog Cloud it would be really valuable if you can share any links where the problem occurs. This speeds up our ability to troubleshoot tremendously.* 

## How to reproduce

1.
2.
3.

## Environment

- [ ] PostHog Cloud US, project ID: [please provide from https://app.posthog.com/project/settings#project-id]
- [ ] PostHog Cloud EU, project ID: [please provide from https://eu.posthog.com/project/settings#project-id]
- [ ] PostHog Hobby self-hosted with `docker compose`, version/commit: [please provide]
- [ ] PostHog self-hosted with Kubernetes (deprecated, see ["Sunsetting Kubernetes support"](https://posthog.com/blog/sunsetting-helm-support-posthog)), version/commit: [please provide]

**Comment by raquelmsmith** [comment]
Ha duplicate of https://github.com/PostHog/posthog/issues/17242 and https://github.com/PostHog/posthog/issues/16975

**Comment by lawalbolaji** [comment]
@raquelmsmith It looks like the UI isn't handling the paste properly - it assumes everything separated by a comma is a unique value so `1234, 5678, 9123` becomes `"1234", " 5678",  " 9123"`.

That's why it seems like only the first value is respected. I've submitted a pr that should fix this, https://github.com/PostHog/posthog/pull/17303
