### ISSUE TITLE
This projects needs a bot for triaging PRs

### ISSUE THREAD

**Issue by zimmski** [PostHog/posthog#17312]
## Bug description

Adding this as a bug issue because this seems to be a bigger problem with this project.

PostHog says it is open source, in fact it is a value proposition of the company, but the project is missing on a great value addition of that fact and a core part of being open source: contributions outside of the core team. I know that https://github.com/PostHog/posthog/pull/17113 is not that important to the majority of users (still, does not compile and an easy fix) but this is not the only PR: https://github.com/PostHog/posthog/pulls?q=is%3Apr+is%3Aopen+label%3Astale that went stale. The project is losing potentially days worth of work. My project management heart is screaming :broken_heart: 

My suggestion is to add a bot (rule) to "triage" issues and especially PRs, and then define people of the core-team to actually do the triaging. I can tell from personal experience that this is the fastest way to get external work into the project. Which in turn also helps move the project along much faster and creates a bigger community.

I can understand dropping open source projects for time reasons, but as far as i understand being "open source" is part of the core values of PostHogs value proposition. If you let contributions die, you let your community die. Also, you are not open source then, your source is open: big difference. So triaging, reviewing and taking care of contributors (e.g. better documentation on development) is a small price to pay. Much smaller than onboarding new people, and it scales much better with the resources of the company.

**Comment by pauldambra** [comment]
Hey @zimmski thanks for this... we actually have a bot for triaging PRs 😊 

Most of the stale PRs you linked are from our team members not open contributors. We use PRs to communicate, to sketch out ideas, as testing grounds - we're not necessarily aiming to have every PR merged.

Being open source remains a core part of what we are. Regardless of where we could better at that (everyone is a work in progress 📈)

**Comment by pauldambra** [comment]
Because we're open you can see our merged PR count here https://app.posthog.com/shared/cXOeTCiTAvX7UJ3uL2NMh9XEIJZHQQ
