### ISSUE TITLE
Duplicate google login buttons show when forced SSO login

### ISSUE THREAD

**Issue by raquelmsmith** [PostHog/posthog#17324]
https://posthogusers.slack.com/archives/C019E06QDG8/p1681196054780059

![image](https://github.com/PostHog/posthog/assets/18598166/dee113f2-1acb-4d51-b24b-5f3c21a53d74)

**Comment by maxbelm** [comment]
Hi @raquelmsmith I'm happy to take on this issue!

**Comment by maxbelm** [comment]
Please let me know if any of the assumptions made in the PR are incorrect, happy to adjust the work as needed!

**Comment by raquelmsmith** [comment]
Ah, thank you! This was a very poorly fleshed-out issue but your assumptions are correct 😄
