### ISSUE TITLE
Rating surveys on the 10 point scale should start at 0

### ISSUE THREAD

**Issue by liyiy** [PostHog/posthog#17381]
## Bug description

NPS surveys are on a 0-10 point scale. We should update the site app and posthog app to reflect this.

## How to reproduce

1.
2.
3.

## Environment

- [ ] PostHog Cloud US, project ID: [please provide from https://app.posthog.com/project/settings#project-id]
- [ ] PostHog Cloud EU, project ID: [please provide from https://eu.posthog.com/project/settings#project-id]
- [ ] PostHog Hobby self-hosted with `docker compose`, version/commit: [please provide]
- [ ] PostHog self-hosted with Kubernetes (deprecated, see ["Sunsetting Kubernetes support"](https://posthog.com/blog/sunsetting-helm-support-posthog)), version/commit: [please provide]

**Comment by neilkakkar** [comment]
fixed now :)
