### ISSUE TITLE
Consolidate and write Tests for SQL queries

### ISSUE THREAD

**Issue by EDsCODE** [PostHog/posthog#1739]
We've written a lot of queries that get the job done. Some of them are very specific.

We should parameterize the queries more so that they can be reused more. 

We should also have unit tests to make sure the queries do what we expect. For example, the query building in `ee/clickhouse/models/action.py` are untested right now

**Comment by macobo** [comment]
Note: The query string building might be a good usecase to introduce approval testing (also known as characterization testing, snapshot testing, golden master testing).

Potential libraries: https://github.com/approvals/ApprovalTests.Python, https://pypi.org/project/pytest-snapshot/

(This is less so for testing query results)
