### ISSUE TITLE
Screen recordings stop unexpectedly

### ISSUE THREAD

**Issue by bengo-samplead** [PostHog/posthog#17399]
## Bug description

When watching a screen recording, the video suddenly stops at an unexpected time, the next recording timer starts, and the player jumps to the next video, even though the current video hasn't finished and contains multiple events.

## How to reproduce

Watch a screen recording. It doesn't occur consistently, and the exact timing when the video stops is unclear.

## Environment

Production, Project ID 34190

**Comment by benjackwhite** [comment]
Hey this is pretty impossible to debug from a github issue perspective. Could you open an in-app support request with links to relevant recordings so that a team member can have a look and see what exactly is going on with your setup? Thanks!
