### ISSUE TITLE
Elements Chain is wrong way round 

### ISSUE THREAD

**Issue by Tannergoods** [PostHog/posthog#174]
Elements Chain is the wrong way round

1. Go to 'actions'
2. Click on an action and go to elements
3. See error

**Expected behavior**
Body should be the other way around

![Posthog](https://user-images.githubusercontent.com/60791437/75100580-5185f900-5584-11ea-90d3-f6a1fe5b5cc3.png)

 - MacOS
 - Chrome

**Comment by timgl** [comment]
Fixed!
