### ISSUE TITLE
How can I select which event properties to include in the response from the `/events` endpoint?

### ISSUE THREAD

**Issue by FatehAK** [PostHog/posthog#17409]
Hey, I'm trying to use the `/events` PostHog endpoint to retrieve some relevant event data for a user to display on my custom dashboard. I was able to filter by the user and the corresponding event name using the `distinct_id` and `event` query parameters like this:

`https://app.posthog.com/api/projects/35247/events/?distinct_id=buyer@test.com&event=product_impression`

However, this returns a large list of properties for every event in the response, making the payload size very large. Is it possible to select which event properties to return?

I can see a `select` query parameter documented on [Swagger](https://app.posthog.com/api/schema/swagger-ui/#/events/events_list), but I'm unsure of how to use it.

Ideally, I'd like to do something like this:

`https://app.posthog.com/api/projects/35247/events/?distinct_id=buyer@test.com&event=product_impression&select=["event.properties.productName", "event.properties.itemId"]`

Is it possible to do this with the `/events` API, or do you have any suggestions on how to achieve this?

**Comment by MarconLP** [comment]
question has been answered in our community forum
