### ISSUE TITLE
Restructure/fix the property storage on events

### ISSUE THREAD

**Issue by EDsCODE** [PostHog/posthog#1743]
RIght now, the properties that get stored onto the events_properties_view have have an extra set of quotes around. 

This exists because the method that we use in the materialized table that splits out event properties can't extract string directly. We extractraw in order to accomodate numbers otherwise any number property would have been dropped

**Comment by mariusandra** [comment]
If/when this gets adapted, this line should be updated:

https://github.com/PostHog/posthog/blob/379518e28519f6a624c8b85cad5579bbc61854ca/ee/clickhouse/views/events.py#L72
