### ISSUE TITLE
Surprisingly, the map of China does not include Taiwan and the South China Sea

### ISSUE THREAD

**Issue by mano233** [PostHog/posthog#17433]
![img_v2_1ca5711e-f5df-4954-bbfb-322933c8172g](https://github.com/PostHog/posthog/assets/29190675/ffeeb75a-e8be-437e-83d2-e33a8e9f9f62)

**Comment by pauldambra** [comment]
We used this map from wiki commons https://commons.wikimedia.org/wiki/File:BlankMap-World.svg any edits would need to be addressed there

**Comment by mano233** [comment]
> We used this map from wiki commons https://commons.wikimedia.org/wiki/File:BlankMap-World.svg any edits would need to be addressed there

The problem is the highlighted part of the map
