### ISSUE TITLE
Surveys > Missing option to change choices font colour

### ISSUE THREAD

**Issue by martinibach** [PostHog/posthog#17441]
## Bug description

*Please describe.*  
*If this affects the front-end, screenshots would be of great help.*  

- I want to create a survey with a black background, which suits our design better
- I want to use multiple choices as answers for the user 
- User can't read choices because font color is black like background
- I can't change the font color to another color code as I can with question, description and background

![image](https://github.com/PostHog/posthog/assets/90472049/84c3cc61-e119-45a6-ac9c-95ee05dbeb30)

*If you are on PostHog Cloud it would be really valuable if you can share any links where the problem occurs. This speeds up our ability to troubleshoot tremendously.* 

https://app.posthog.com/surveys/new

## How to reproduce

1. Create a survey https://app.posthog.com/surveys/new
2. Choose Multiple choice select 
3. Set background to black
4. Add choices with text

## Environment

- [x] PostHog Cloud US, project ID: [please provide from https://app.posthog.com/project/settings#project-id]
- [ ] PostHog Cloud EU, project ID: [please provide from https://eu.posthog.com/project/settings#project-id]
- [ ] PostHog Hobby self-hosted with `docker compose`, version/commit: [please provide]
- [ ] PostHog self-hosted with Kubernetes (deprecated, see ["Sunsetting Kubernetes support"](https://posthog.com/blog/sunsetting-helm-support-posthog)), version/commit: [please provide]

**Comment by liyiy** [comment]
Font colors should auto contrast now!
