### ISSUE TITLE
Instance settings page is unavailable on self-hosted

### ISSUE THREAD

**Issue by antoinefink** [PostHog/posthog#17458]
## Bug description
Clicking on the "Instance settings" link in the menu only leads to the System overview, not the settings:
![Screenshot 2023-09-15 at 08 48 54](https://github.com/PostHog/posthog/assets/2157992/79a3d7af-8d95-4a12-b138-c9b8cbc11800)

And visiting /instance/status/configuration (as suggested in the documentation: https://posthog.com/docs/self-host/configure/instance-settings) leads to a 404:
![Screenshot 2023-09-15 at 08 42 05](https://github.com/PostHog/posthog/assets/2157992/95ee4f5e-ba3b-4e11-b99a-2bfc1d480bfc)

## Environment
- [x] PostHog Hobby self-hosted with `docker compose`, version/commit: 491960d

Thank you 🙏

**Comment by benjackwhite** [comment]
Thanks for reporting! PRs coming up
