### ISSUE TITLE
No more tagged release ?

### ISSUE THREAD

**Issue by allan-simon** [PostHog/posthog#17457]
## Is your feature request related to a problem?

There hasn't been a release for nearly half a year while there used to be one every month  is it a change in policy (switch to continuous deployment ?)

I know you're providing less official support now for self-hosted posthog and as a business owner I perfectly understand it. I just want to know can we expect new release in the future ? Or can we have a clear statement that it will no more be the case and people self-hosting should use master branch to their own peril (which is fine)

Thanks a lot for the tool you've provided and this great contribution to opensource

## Describe the solution you'd like

A clear  statement on release plan

**Comment by timgl** [comment]
Hey Allen, we outlined this in our [Sunsetting Kubernetes support](https://posthog.com/blog/sunsetting-helm-support-posthog#whats-next) blog. There are no more tagged releases, instead we build a docker image for every commit to the master branch. Hope that helps!
