### ISSUE TITLE
Surveys URL field can handle wildcards/regex

### ISSUE THREAD

**Issue by liyiy** [PostHog/posthog#17472]
## Is your feature request related to a problem?

In survey creation, we're restricted to a "url contains" option. Allow that field to handle wildcards or regex

**Comment by captain-Akshay** [comment]
i can work on adding the regex to the url contains field assign it to me!

**Comment by Bonitis** [comment]
Hello! I noticed that in posthog-js, the check for match on the url is using `window.location.href.indexOf()`. Would this be solved by handling wildcards, regex, and partial urls within that matching function, then updating the label and placeholder on the url field? Or were you thinking that this would be an explicit option the user would choose, and that setting would be part of the survey conditions?

**Comment by liyiy** [comment]
Hey Bonitis!

You are correct, the url matching is evaluated in `posthog-js`. You would need to update and write a test for it there, and then just update the label and placeholder on the url field so that users can easily figure that out. 

I think it would be nice to support the scenario where it only evaluates as regex if the user puts in regex, otherwise it continues to do the "contains" match, because most likely not everyone will want to use regex~ 😃

**Comment by Bonitis** [comment]
@liyiy I opened a PR for this change in posthog-js, but had some questions / looking for feedback. What is the typical process for tagging in a reviewer? Is that handled by the posthog team or should I tag you on the PR?

**Comment by liyiy** [comment]
Feel free to tag me on the PR! :)

For future issues too, feel free to always tag the person that wrote the issue for a review on the PR 👍

**Comment by neilkakkar** [comment]
this is done now :)

**Comment by liyiy** [comment]
GOOD JOB EVERYONE!!! 🥳
