### ISSUE TITLE
Add "other" open ended option for multiple choice surveys

### ISSUE THREAD

**Issue by liyiy** [PostHog/posthog#17471]

**Comment by kiran-4444** [comment]
Can I work on this issue? Been looking at the repo for last two days and I'm excited to contribute to this amazing project. I'm very familiar with API development and drf. But I'm not really sure if this is a backend issue or frontend's. I'd like some pointers in either case.

**Comment by liyiy** [comment]
Hey Kiran,

There's a couple of big merge changes coming in soon so I would recommend waiting until Monday to pick this up if you're still interested! 

This would involve updating the surveys app code in `posthog-js` and in `posthog` app too. It'll mostly be a frontend issue, and some thinking will be required on how to best incorporate the "other - open ended" format into the saved response

**Comment by kiran-4444** [comment]
> waiting until Monday

Sure :)

**Comment by kiran-4444** [comment]
Hey, I'm still interested in taking this up. Can you explain me the task in detail?
