### ISSUE TITLE
Redux DevTools are causing slowdowns

### ISSUE THREAD

**Issue by MarconLP** [PostHog/posthog#17482]
## Bug description

It seems that Redux DevTools are causing the slowdown, perhaps because the developer version of Redux is being distributed in production, or some subset is being included for production debugging. 

## How to reproduce
1. Using Firefox, ensure [Redux DevTools](https://addons.mozilla.org/en-US/firefox/addon/reduxdevtools/) installed (I'm sure this happens on any browser, but I have not yet tested)
2. Open the PostHog app normally, note that it works perfectly well
3. Open dev tools (F12 or r-click -> Inspect) and then open the Redux tab to initialize the tool
4. Refresh PostHog and try to click around, noting how sluggish the app has become

## Additional context

related ticket: https://posthoghelp.zendesk.com/agent/tickets/5822

**Comment by Twixes** [comment]
Maybe something with Kea @mariusandra?

**Comment by mariusandra** [comment]
Unlikely to be kea per se, but likely we're dispatching actions with non-jsonable content somewhere that's causing issues when devtools inspect it. Things like self-references or large objects (e.g. `window`) that shouldn't be there in the first place.

**Comment by mariusandra** [comment]
If this is happening on your site, then it's likely it only happens when the toolbar is enabled, not when you're just using posthog-js to track events.

**Comment by speedy250** [comment]
As the original reporter of this bug, I will clarify that this issue occurs for me when visiting app.posthog.com

If redux dev tools extension is enabled, then the site will become unusable.

Here's a video to illustrate; look for yellow circles around the mouse to show click actions. I move the mouse around after clicking to show I'm waiting on the site.

https://github.com/PostHog/posthog/assets/3361507/7a48a3a9-981c-4aee-852d-4eaf20b5895f

**Comment by pauldambra** [comment]
I guess it's this https://github.com/reduxjs/redux-devtools/issues/437

**Comment by pauldambra** [comment]
and there's a proposed fix in an approved by unmerged PR from 2019 🤯 so I guess if we want to fix this it needs to be in posthog :)

**Comment by MarconLP** [comment]
+1 https://posthoghelp.zendesk.com/agent/tickets/17162 (moved to PostHog: https://us.posthog.com/project/2/support/tickets/19390)

**Comment by MarconLP** [comment]
+1 https://posthoghelp.zendesk.com/agent/tickets/17233 (moved to PostHog: https://us.posthog.com/project/2/support/tickets/19405)

**Comment by pauldambra** [comment]
+1 https://posthoghelp.zendesk.com/agent/tickets/17344 (moved to PostHog: https://us.posthog.com/project/2/support/tickets/19326)

**Comment by abigailbramble** [comment]
+1 https://posthoghelp.zendesk.com/agent/tickets/17383 (moved to PostHog: https://us.posthog.com/project/2/support/tickets/19701)
+1 https://posthoghelp.zendesk.com/agent/tickets/17206 (moved to PostHog: https://us.posthog.com/project/2/support/tickets/19678)
+1 https://posthoghelp.zendesk.com/agent/tickets/17311 (moved to PostHog: https://us.posthog.com/project/2/support/tickets/21844)
+1 https://posthoghelp.zendesk.com/agent/tickets/17351 (moved to PostHog: https://us.posthog.com/project/2/support/tickets/19327)
+1 https://posthoghelp.zendesk.com/agent/tickets/17271 (moved to PostHog: https://us.posthog.com/project/2/support/tickets/19318)
+1 https://posthoghelp.zendesk.com/agent/tickets/17353 (moved to PostHog: https://us.posthog.com/project/2/support/tickets/19328)

**Comment by pauldambra** [comment]
should be fixed by https://github.com/PostHog/posthog/pull/24611

so we can't use redux dev tools when debugging posthog in dev but that's a trade-off that's worth it to avoid this
