### ISSUE TITLE
HIPAA Compliance

### ISSUE THREAD

**Issue by annikaschmid** [PostHog/posthog#17504]
PostHog is certified as SOC 2 Type 1 compliant since April 2023. We are currently evaluating the priority of achieving HIPAA compliance.

If HIPAA compliance is a requirement or should-have for you to use PostHog, please leave a comment or a 👍 / ❤️ reaction on this post to vote for it -- your votes and feedback help us prioritize what to work on next!

**Comment by victorbordo** [comment]
Does this mean the self-hosting [guidance](https://posthog.com/docs/privacy) will change and a BAA will be made available for using Posthog Cloud?

> No. We believe self-hosting is the best solution for HIPAA compliance. Read our documentation for more on [how to self-host PostHog](https://posthog.com/docs/self-host).

**Comment by simfish85** [comment]
@victorbordo yes - BAA's will now be offered as part of our Enterprise plan on PostHog cloud.  Those interested should get in touch with us at sales@posthog.com
