### ISSUE TITLE
Dashboards color schemes

### ISSUE THREAD

**Issue by paolodamico** [PostHog/posthog#1763]
When working on the designs for #1659, @lottiecoxon helped us create different color scheme proposals for the main dashboards 🙌 ([full design here](https://www.figma.com/file/gtW3o3VKYvf04ws8cZM3Nr/PH-Retention-optimisations?node-id=492%3A0)). Opening this issue to discuss the different proposals. 

### Current color scheme
![image](https://user-images.githubusercontent.com/5864173/94660050-1bb8a800-02fd-11eb-8101-4639b00737a0.png)

### Proposal 1 
![image](https://user-images.githubusercontent.com/5864173/94660192-486cbf80-02fd-11eb-86ca-c77ee3a1232e.png)

### Proposal 2
![image](https://user-images.githubusercontent.com/5864173/94660203-4c004680-02fd-11eb-9963-b619e1413cfe.png)

### Proposal 3
![image](https://user-images.githubusercontent.com/5864173/94660227-515d9100-02fd-11eb-9b91-8c9d507b2caf.png)

### Proposal 4
![image](https://user-images.githubusercontent.com/5864173/94660240-54588180-02fd-11eb-8d52-8675937b4c40.png)

**Comment by Twixes** [comment]
1 matches our website most, but it doesn't have much variety. Besides that option, I think the current one is pretty good.

**Comment by mariusandra** [comment]
Something to keep in mind is that the dashboard color is currently set by choosing the "color":

![image](https://user-images.githubusercontent.com/53387/94663855-74427200-030a-11eb-9621-4b39bca9f862.png)

We have people using the dashboard who have selected a specific color for their dashboards. If we do update the color scheme to for example #4, what will happen to all the people who chose "green"?

Also, we should keep black no matter what.

**Comment by lottiecoxon** [comment]
## Moving this forward 

Would it be possible to limit the selection of colours our users can choose? For instance we keep the original colours but then add on some more (website similar) options. Therefore we don't take away colours from current users but give new users the option for some continuity with the branding? 

I want to get this in motion asap

## Options 

### 1. Leave colours as they are 

### 2. Leave original colours and add in some extra options 

### 3. Make the colours unlimited to user they can choose whatever they like

**Comment by mariusandra** [comment]
Hey! Comments for the options:
1. Done!
2. Sounds good to me. We could tweak the original ones to be more in line with the palette, yet green should remain green..ish.
3. I'd advocate against this. It's not just choosing a colour for the background, but also choosing colours for the lines and/or pie chart segments. Even though these are currently generated algorithmically from the background colour, it's best to limit the list of colours available to not make them too hideous.

**Comment by lottiecoxon** [comment]
I started with the colours on the features page to start working from. Our colour scheme is bold and as it currently stands quite limited, I fear that these colours will be too loud. 

<img width="285" alt="Screenshot 2020-10-12 at 09 47 50" src="https://user-images.githubusercontent.com/65415371/95732199-097d2900-0c70-11eb-8b4f-09e192ece83b.png">

But thanks to @embishh I have access to 'accessible colours' which is pretty nifty. I have created a bunch of colour combinations for the dashboard/website in general. 

<img width="753" alt="Screenshot 2020-10-12 at 12 07 10" src="https://user-images.githubusercontent.com/65415371/95744804-79e17580-0c83-11eb-844b-baec1217a49f.png">

**Comment by lottiecoxon** [comment]
If anyone wants to have a go!

https://accessible-colors.com

**Comment by lottiecoxon** [comment]
We still need to add icons but this is what I have so far

<img width="704" alt="Screenshot 2020-10-12 at 13 23 11" src="https://user-images.githubusercontent.com/65415371/95751430-23c5ff80-0c8e-11eb-813a-0b13391a789e.png">

**Comment by embishh** [comment]
Loving the color palette

**Comment by lottiecoxon** [comment]
I will make up some icons today and show progress asap - does anyone have any other feedback for the dashboard so far?

**Comment by paolodamico** [comment]
My 2c:

**Color related**
- While I love the contrast of the profile picture placeholder with the blue background in the top nav bar, I get the impression we're  _spending color_ there, hindering our ability to use the blue or other dark color to emphasize another element in the page. It also gives me the impression that this might bring more attention to the top bar when using it will be not as regular.
- Related to the above, the orange update indicator no longer feels as an action item requiring attention (though I like the color).
- I like the yellow and orange **colors** used in the actions tutorial section, however using them in those elements feels a bit saturated, I would either not add color on those, or use the same one.
- For the "active" state in the sidebar, I think (unsure) the gold from the profile picture might look better, but I like the current color too.

**Random thoughts**
- The sidebar seems to wide, one of the advantages of the large icons is that we can make the sidebar narrower so the screen space can be used by the actual page elements. Particularly relevant for insights & dashboards.
- Very personal preference (feel free to disregard), I'm not a fan of the large rounding and we don't use it (currently) anywhere within the app (we mostly use 2px).

**Comment by paolodamico** [comment]
Would like to revisit this as a lot of our design language has changed. We got some feedback from a user too that we offer too few colors for the dashboards. I also think it might be worth considering to do color accents in a way that doesn't interfere with the body of the chart as a single chart can have multiple series in multiple different colors (i.e. if we can always keep the main chart body white)

**Comment by corywatilo** [comment]
@lottiecoxon Maybe we can find some colors from the new marketing styles that we can bring over into the options?

**Comment by lottiecoxon** [comment]
did some colour collecting, these are shades found on our new web designs
![Colour collecting for dashboards](https://user-images.githubusercontent.com/65415371/119011110-a03f6000-b98c-11eb-9a29-0b035fbfd60a.png)

**Comment by lottiecoxon** [comment]
the grey I threw in just for some extra options

**Comment by lottiecoxon** [comment]
RIGHT - made some serious developments with colours for graphs- 16 colours, colour blind friendly for the main three types (Prot. Deut. and Trit.) See here for the [walkthrough on Figma](https://www.figma.com/proto/ZQzZ1EEc0dcvxfv4iYQ77N/Styleguide?page-id=15%3A50&node-id=25%3A0&viewport=68%2C1015%2C0.22304026782512665&scaling=min-zoom) - feel free to leave any feedback or comments !!

**Comment by lottiecoxon** [comment]
![Screenshot 2021-05-26 at 14 45 29](https://user-images.githubusercontent.com/65415371/119670727-09155500-be31-11eb-9b60-fce2c0150ced.png)

For those who don't want to read through the Figma file, this is the Collection of the 16 colours, followed by three versions that show how those with different colourblindness perceive them.

**Comment by corywatilo** [comment]
For clarification, are the latest ones at the very bottom of the Figma file?

Separately, one improvement would be to put the _most different_ colors next to each other. (Not all graphs will use all colors - in many cases, just a few.) So it would make more sense to go red -> blue -> yellow vs maroon > red > pink. More variation with adjacent colors would be 👌🏻.

**Comment by paolodamico** [comment]
Thanks for the input here @lottiecoxon! Can we get your input on a few points? @corywatilo please weigh in too

1. These are the colors we would use both for dashboard backgrounds and for graph series, or only for dashboards? i.e. if a single graph has multiple lines, we would graph each line with each of the different colors.
2. If we're using these colors for graph series, what would be the ordering for the colors? I assume we'll want to mix them to maximize distinction (e.g. if the graph only has 3 lines, we would maybe want to do for instance an orange, green and purple).
3. Related to the above, what would be the default color?
4. Should we consider having an accessibility option where we have a separate set of colors optimized for color-blind people? I'm thinking we could potentially optimize for each group of users to provide each with the best experience.
5. Can we see a test with these colors in the new graphs UI ?
6. I think we need to change the way we accent color in dashboards. Changing the whole background color makes it incredibly complex to properly support having multiple series in a single graph. It'll also make it harder to introduce a dark mode. Thoughts / ideas?
<img width="300" alt="" src="https://user-images.githubusercontent.com/5864173/119905326-e3f01780-bf00-11eb-81f0-f4067b4eedf9.png">

**Comment by lottiecoxon** [comment]
In response to your 6 questions 

1. Personally, I think we should use the colours as accents instead of backgrounds. Bouncing off the mock up @corywatilo  made last week or so (image below)  I think that having a wash of colour for the graphs or even the header could be a good way to go. Happy to mock this up today to show roughly what I mean. 

![119531838-5242a780-bd52-11eb-81b1-47efcb652781](https://user-images.githubusercontent.com/65415371/120459064-be935b80-c38f-11eb-928a-7504beddc1db.png)

2. For colour ordering I can make a few collections from the colours above for this exact issue - and then if the user wants to personalise the colour choices they can?

3. For the default colour I would say the orange 

4. AH now this is a great shout, we could have a colour blind button in the top corner (a bit like we have a dark mode/lightmode button) I love this idea personally - not only because it shows we cater for disabilities but also normalises it for the everyday user. 

5. yes - will work on this today 

6. I agree, I think the blocks of bright colour is distracting and overkill (covered this issue in answer no.1)

**Comment by paolodamico** [comment]
Thanks @lottiecoxon 🙌🙌🙌! Not only for the responses but for your help with this, aligned and will wait for your input!

Only outstanding question is for 1) I actually didn't explain it clearly. I meant to ask if the colors should be used only for a) dashboard accents [as suggested on 6], or if we should use them too to b) represent different series in a single graph (example below from current version).

<img width="700" alt="" src="https://user-images.githubusercontent.com/5864173/120499747-27210f00-c375-11eb-82bb-930f9dd9b2a5.png">

**Comment by paolodamico** [comment]
@clarkus I think it's worth finally tackling this once and for all, thoughts?

**Comment by clarkus** [comment]
> @clarkus I think it's worth finally tackling this once and for all, thoughts?

Happy to work on this. I would like to see some success criteria here - I am not 100% clear what the goal is.

**Comment by mariusandra** [comment]
Having implemented the original colors, I feel the urge to reply.

> Happy to work on this. I would like to see some success criteria here - I am not 100% clear what the goal is.

You're asking the right question! I've seen this issue come and go over the last year, and this has always been super subjective and inconclusive. Let's not do anything without a clear goal.

And to repeat, two things that I consider important.

1. Let's not change ~~anything~~ much for users who have selected any of the current colors. It'd be really weird if my blue and green dashboards suddenly turned yellow. No problem to tune the green color a bit, but the existing colors should remain in the list of options.

2. Nobody has complained about dashboard colors being off or wrong or bad or ..., as far as I can tell. I'm not sure what are we actually "fixing" here other than "it would be nice if I could use the logo colors here... brand unity and whatnot", which is 🤷 in this case, in my opinion.

**Comment by paolodamico** [comment]
Thanks for challenging this. Here’s the problems I see with dashboards colors (and agreed, if these are not problems worth fixing let’s close this once and for all).

**From user feedback**
* Colored graphs with multiple series are really hard to read.
    * In addition, the color structure inside is not color-blind friendly.
* Offer more color options to better categorize graphs.

**My own POV**
* A more cohesive visual experience. Use colors that fit better with our new design language (without changing them too much, agreed).

**Comment by clarkus** [comment]
> Thanks for challenging this. Here’s the problems I see with dashboards colors (and agreed, if these are not problems worth fixing let’s close this once and for all).
> 
> **From user feedback**
> 
> * Colored graphs with multiple series are really hard to read.
>   
>   * In addition, the color structure inside is not color-blind friendly.
> * Offer more color options to better categorize graphs.
> 
> **My own POV**
> 
> * A more cohesive visual experience. Use colors that fit better with our new design language (without changing them too much, agreed).

I think based on that problem area, https://github.com/PostHog/posthog/issues/4076 is a better target for resolving specific accessibility issues with graph series colors. This is a fundamental shortcoming for all insight charts regardless of context. 

For dashboard colors, I'd ask what problem we're solving there. Is it to easily differentiate charts? Is it just to make a dashboard feel like it's more your own? I think there are [other things](https://github.com/PostHog/posthog/issues/6712) about dashboards that we don't fully understand yet, so we might benefit from more research to better set the problems we can solve there.

**Comment by paolodamico** [comment]
Well to the point about the problem, I do see this as a problem (not just in terms of accessibility), but for instance I find it quite hard to understand this ([real example](https://app.posthog.com/dashboard/12081)) graph at all.

<img width="590" alt="" src="https://user-images.githubusercontent.com/5864173/144681361-b8856490-c010-4dc3-a775-b498672b88f3.png">

In terms of what colors are used for / what problem are they solving. These existed before I joined so perhaps @mariusandra has better context, but I've heard from users that a) they use them to signal distinct categorizations of data (e.g. information  from unique users vs. total volume, or marketing vs. product, ...) and b) make things look more personalized (just user preference).

It's really hard to come up with multiple colors for dashboards + colors for series, ... so in the past I made the suggestion that we update the designs so the dashboard color is just an accent and not the background, and we can keep the same series colors on dashboards and insights (will also make things more intuitive when moving between insights and dashboards).
 
Happy to chat about this on our standup if it makes sense.

**Comment by clarkus** [comment]
> Well to the point about the problem, I do see this as a problem (not just in terms of accessibility), but for instance I find it quite hard to understand this (real example) graph at all.

Yup this is my main point - there is a lot more than color to solving the problem of making dashboard charts easier to use. Legends, tooltips, descriptions, etc all lend towards making those chart easier to grok. Colors are part of it, or at least contrast, but I feel like there's more to the problem here.

**Comment by paolodamico** [comment]
Agreed! I've opened a new issue then to make dashboards great, #7517.

**Comment by mariusandra** [comment]
One more point. We currently have two sets of colors.

- Dashboards with a white background: these get a [predefined list of colors](https://github.com/PostHog/posthog/blob/c42af0fee768856f898fdebdc8e8b045c184d506/frontend/src/lib/colors.ts#L2-L19). 
- Dashboards with any other background: these get a [calculated set of colors](https://github.com/PostHog/posthog/blob/c42af0fee768856f898fdebdc8e8b045c184d506/frontend/src/lib/colors.ts#L50-L72) based on the background color. 

The idea here is to create some kind of function that can spit out a "doesn't look too bad" list of colors automatically for any background, instead of handpicking ~20 colors for each background. I'd suggest keeping this approach, and perhaps tuning the function, if the line colors need to be improved.

**Comment by gustavoloureirodosreis** [comment]
How do you even change a dashboard background color right now? Seems absent on the product... I've looked into every single menu.

**Comment by Twixes** [comment]
Hey @gustavoloureirodosreis! You can set a dashboard tile's color, which shows up as a ribbon. We don't support full tile colors anymore – unfortunately the complexity in maintaining good contrast and visual cohesion was huge.
<img width="358" alt="Tile color" src="https://user-images.githubusercontent.com/4550621/200579955-0fe54419-20cf-433c-b20e-a55b5a958ce6.png">

**Comment by gustavoloureirodosreis** [comment]
Yeah, I saw it... what about simply having a dark theme overall? That would already be an 80/20 situation.

**Comment by Twixes** [comment]
That's definitely on the to-do list, though we don't have plans to implement dark mode in the near term.

**Comment by gustavoloureirodosreis** [comment]
Where's the to-do list?

**Comment by Twixes** [comment]
Well, this item wasn't documented before, so thanks for opening #12678. :smile: In general, this is our to-do list: https://github.com/PostHog/posthog/issues. It has 1.3k items, so prioritization is a challenge.

**Comment by gustavoloureirodosreis** [comment]
Can I help with this? I can create a PR about it
