### ISSUE TITLE
Person List

### ISSUE THREAD

**Issue by EDsCODE** [PostHog/posthog#1764]
Pagination and making sure identified users are updated/propogating

**Comment by timgl** [comment]
Sort of parked as we're still using Postgres anyway

**Comment by charlescook-ph** [comment]
I'm having the issue where if I filter for just 'identified' users, that filter doesn't stay active when I click to page 2 etc. - I assume this is the same thing, but just double checking!

**Comment by paolodamico** [comment]
@piemets would you mind sharing a screenshot? trying to determine if you're on the new version of the persons page

**Comment by charlescook-ph** [comment]
![Screenshot 2020-12-08 at 16 05 42](https://user-images.githubusercontent.com/70321811/101508210-49f6db80-396f-11eb-9005-36308ed7c402.png)

(This is on page 2)

**Comment by Twixes** [comment]
Done according to https://github.com/PostHog/posthog/projects/8.
