### ISSUE TITLE
Ideas for default survey templates

### ISSUE THREAD

**Issue by liyiy** [PostHog/posthog#17654]
What are the top 5 survey templates we could set up as an example to users?

Reminder surveys has these types:
1. open ended text
2. link
3. rating with emoji/numbers
4. single/multiple choice
*5. multiple questions (any combo of the above)

Templates to look something _potentially like _this__

![image](https://github.com/PostHog/posthog/assets/25164963/f44c255e-583d-4dd4-890f-0c406c786938)

cc @joethreepwood @annikaschmid @Lior539

**Comment by neilkakkar** [comment]
Rating survey, followed by an open question "Why did you give us that rating?"

**Comment by neilkakkar** [comment]
Open ended text, "What did you think about feature X?" - followed by "Thanks! If you'd like to give us more information, book a user interview"

**Comment by joethreepwood** [comment]
Probably want one question for each type, right? 

1. **Open-ended text:** Neil's suggestion
2. **Link:** Would you be interested in participating in a customer interview? (Calendly link)
3. **Emoji:** CSAT survey: How satisfied are you with this product?
4. **Numbers:** NPS survey: How likely are you recommend this product to a friend?
5. **Single/Multiple choice:** How did you first find out about this product? Search/Referral/Online advert/Offline advert/Social media/Other (specify)

For a multiple question one we probably want a set of generic questions related to PMF?

**Comment by joethreepwood** [comment]
Alternative approach is to just hit all the obvious questions types: NPS, CES, CSAT, Superhuman
