### ISSUE TITLE
SupportModal: Uploading images is not possible while unauthenticated

### ISSUE THREAD

**Issue by MarconLP** [PostHog/posthog#17653]
## Bug description

SupportModal: Uploading images is not possible while unauthenticated
![Screenshot 2023-09-27 at 16 24 01](https://github.com/PostHog/posthog/assets/13001502/0ab1837c-61c1-4b02-a144-dc8a27f0b5c7)

## How to reproduce

1. Open incognito window
2. Visit https://eu.posthog.com/home#supportModal=feedback%3A
3. Try to upload a video

## Additional context

related ticket: https://posthoghelp.zendesk.com/agent/tickets/6082

**Comment by pauldambra** [comment]
Ah, I think the bug here is that we offer it as an option... we definitely don't want an unauthenticated upload API 🤣

**Comment by MarconLP** [comment]
> Ah, I think the bug here is that we offer it as an option... we definitely don't want an unauthenticated upload API 🤣

Why does the support modal allow unauthenticated tickets at all? Most unauthenticated questions seemed to be more suited for community questions.

**Comment by pauldambra** [comment]
I bet it's so you can request support during the login/registration flow 

So, I guess we want to have some combination of:

* not offer the upload option
* say "log in to upload screenshots" instead of offering the option
* give a nicer message if that upload fails
