### ISSUE TITLE
Keep buffering and polling for real-time replay data

### ISSUE THREAD

**Issue by benjackwhite** [PostHog/posthog#17669]
## Is your feature request related to a problem?

Currently, once we buffer to the "end", we just "stop" and throw an error if the player tries to go past the buffered time. Depending on the state of ingestion, the latest info might still be being processed, so it would be better to...

## Describe the solution you'd like

1. Indicate that this is the case
2. Poll for the snapshots for new data (maybe up until a max timeout)

## Additional context

[Related ticket](https://posthoghelp.zendesk.com/agent/tickets/6109)

**Comment by daibhin** [comment]
We now poll for realtime data! https://github.com/PostHog/posthog/pull/20019
