### ISSUE TITLE
Posthog doesn't play well with Partytown

### ISSUE THREAD

**Issue by reuseman** [PostHog/posthog#17750]
## Bug description
I am using the HTML code snippet to enable posthog on my website made with Astro.js. I enabled even Partytown to enhance the performances. With auto-capture on, there are several problems.

On loading, there is this issue and most of the time recordings are just blank:
```
recorder-v2.js?v=1.81.3:20 TypeError: undefined is not iterable (cannot read property Symbol(Symbol.iterator))
    at Function.from (<anonymous>)
    at Z.doc (recorder-v2.js?v=1.81.3:5:16856)
    at Z (recorder-v2.js?v=1.81.3:5:19014)
    at K (recorder-v2.js?v=1.81.3:5:20715)
    at K (recorder-v2.js?v=1.81.3:5:23655)
    at K (recorder-v2.js?v=1.81.3:5:23655)
    at K (recorder-v2.js?v=1.81.3:5:23655)
    at t.mirror (recorder-v2.js?v=1.81.3:20:7975)
    at ut (recorder-v2.js?v=1.81.3:20:8791)
    at ke (recorder-v2.js?v=1.81.3:20:11529)
```

If a button is pressed:
```
array.js:3 PostHog error: Implementation error. Please turn on debug and contact support@posthog.com.
critical @ array.js:3
eval @ array.js:3
n @ array.js:3
(anonymous) @ partytown-ww-sw.js?v=0.8.1:1781
receiveMessageFromSandboxToWorker @ partytown-ww-sw.js?v=0.8.1:1786
array.js:3 PostHog error: TypeError: Right-hand side of 'instanceof' is not an object
    at Object._captureEvent (array.js:3:21420)
    at Object.eval [as _captureEvent] (array.js:3:7538)
    at WorkerBase.n (array.js:3:24048)
    at partytown-ww-sw.js?v=0.8.1:1781:59
    at receiveMessageFromSandboxToWorker (partytown-ww-sw.js?v=0.8.1:1786:19)
critical @ array.js:3
eval @ array.js:3
n @ array.js:3
(anonymous) @ partytown-ww-sw.js?v=0.8.1:1781
receiveMessageFromSandboxToWorker @ partytown-ww-sw.js?v=0.8.1:1786
```

## How to reproduce

1. Use the code snippet in the HTML to use PostHog and with [Partytown](https://partytown.builder.io/astro)
2. Enable auto-capture
3. Land on the website and press some buttons.

## Environment
- [x] PostHog Cloud US, project ID: 36747

**Comment by pauldambra** [comment]
Hey, partytown moves scripts into a web worker and poshog-js doesn't support being run in a web worker. So, you can't use posthog-js with partytown

**Comment by gajus** [comment]
@pauldambra Can we please re-open this to track as a requirement?

Performance is becoming a big topic for Contra and we are moving all tracking to Partytown.

Posthog is the only non-compatible extension at the moment.

**Comment by rptrainor** [comment]
Agreed, could we get some insight into how we can best use Partytown with Posthog?

**Comment by MarconLP** [comment]
+1 https://posthoghelp.zendesk.com/agent/tickets/13525 (moved to PostHog: https://us.posthog.com/project/2/support/tickets/16078)

**Comment by pauldambra** [comment]
@MarconLP rrweb doesn't support being run in a web worker so PostHog can't support partytown. 

the approach party town takes simply can't be suuported by every library and PostHog is one of those

**Comment by gajus** [comment]
> @MarconLP rrweb doesn't support being run in a web worker so PostHog can't support partytown.
> 
> the approach party town takes simply can't be suuported by every library and PostHog is one of those

That's not the problem though.

rrweb and posthog are separate packages.

I would expect that I can run posthog in partytown without rrweb, and I would expect that (far less important) I am able to run rrweb outside of partytown without the need to load the entire posthog library.

**Comment by gajus** [comment]
I fully understand that the current implementation of PostHog cannot be run in a webworker.

What I am asking is to leave this issue open as a feature request to:

1. Separate rrweb from the core of posthog SDK, i.e. allow to load it independently
2. Make it possible to run posthog client in webworker (now that rrweb is not part of it)
3. Make it possible to run rrweb without loading all of the posthog logic, i.e. provide a lite version of posthog just for the purpose of loading it in the main thread, when needed.

**Comment by ricky11** [comment]
> > [@MarconLP](https://github.com/MarconLP) rrweb doesn't support being run in a web worker so PostHog can't support partytown.
> > the approach party town takes simply can't be suuported by every library and PostHog is one of those
> 
> That's not the problem though.
> 
> rrweb and posthog are separate packages.
> 
> I would expect that I can run posthog in partytown without rrweb, and I would expect that (far less important) I am able to run rrweb outside of partytown without the need to load the entire posthog library.

But posthog.js relies or the open source rrweb package, posthog session recording is well,  almost nothing without it.

**Comment by ricky11** [comment]
Not sure if this helps, i have not implemented it; however since we've installed posthog our web vitals score has gone from A to D, which is a concern.

https://posthog.com/tutorials/web-worker
