### ISSUE TITLE
Changing time range does nothing to Trend Stickiness chart

### ISSUE THREAD

**Issue by yakkomajuri** [PostHog/posthog#1778]
## Bug description

*Please describe.*  
*If this affects the front-end, screenshots would be of great help.*  

Trend Stickiness simply doesn't work on different time ranges:

<img width="1440" alt="Screenshot 2020-09-30 at 17 21 52" src="https://user-images.githubusercontent.com/38760734/94718659-90add100-0341-11eb-942f-08a3b852e305.png">

## Expected behavior

It should work :D

## How to reproduce

1. Go to Trends
2. Show as Stickiness
3. Change the time range

## Environment

- PostHog cloud or self-managed?
- PostHog version/commit

**Comment by yakkomajuri** [comment]
@eikooc

**Comment by eikooc** [comment]
Hi, I still see errors with this functionality. It can now change up to weeks, but still doesn't display the monthly version.

![image](https://user-images.githubusercontent.com/1305015/106862549-92a8e780-66c7-11eb-9c13-9cf99fd3fef3.png)
![image](https://user-images.githubusercontent.com/1305015/106862590-9d637c80-66c7-11eb-8dd8-32130a4f9914.png)

**Comment by eikooc** [comment]
Another thing I noticed, which I don't know fits better in a new issue or not. Changing between "Total Volume" and "Active Users" in this view does not change the numbers shown. Is this intended?
