### ISSUE TITLE
Code analytics - stack trace popular functions and parameters

### ISSUE THREAD

**Issue by jamesefhawkins** [PostHog/posthog#178]
Many codebases have a magical 100 line function that seems to be powering a lot of stuff, but no one really knows which other functions are calling it a lot, or what the parameters are that pass through it.

Tracking which functions are being called, and WHY, plus the parameters through them, is helpful to understand how to refactor code.

**Describe the solution you'd like**
* As a developer, I want to be able to see each function's usage information
  * How many times the function was called
  * The parameters passed through the function

So it's easier to get a sense of redundant code.

We currently can pass all of the above to PostHog, but it's not easy to view this information at a function level in the UX.

  * The stack trace each time the function was called, including the parameters

So it's easier to get a sense of how functions are interacting in practice, not just in theory.

  * (potentially) the actual users that caused those functions to be called in the first place.

So it's easier to get context. Ah, it turns out this kind of user calls these functions a lot, which is generating a ton of hosting cost, or it explains why the system is slow for them, etc.

## Capturing the data

Associating it to the actual user like this would be pretty powerful:

![function_stack_trace](https://user-images.githubusercontent.com/47497682/75121294-8f982100-5647-11ea-8a23-7b9f42698ddd.jpg)

### /code/

We could add a /code URL to the PostHog app.

This could display a table:

| Function | Path | Call Count |
| - | - | - |
| Update_user | /models.py | 1,322 |

You could create a filter on that table to show functions by user. That'd tell you who which function actually impacts. The filter could just work based on the event properties that are captured.

You could, in the longer term, visualise the entire code base from the repo and use colours to represent the call counts, with circles for each file inside circles for each folder, etc.

#### /code/example_function_name

On clicking each row of the table, it should then show a page for that specific function that then shows the full range of parameters passed and their frequencies.

**Update_user parameters**
| Parameter | Value | Count |
| - | - | - | 
| id | 23 | 28 |
| name | James | 3 |

This could also then have the same filter by the event properties, such as by user or device or whatever, if they are available.

### CLI

Being able to call the /code/ and the /code/example_function_name tables from within the CLI would be a really nice way for developers to grab this info without having to go to the UI.

**Describe alternatives you've considered**

You can currently send a function being called as an event, but we believe there is a world of potential to make the UX stronger, so this is a more obvious use case.

**Help Wanted**
@timgl  (or anyone reading), would love feedback on this.  I'm not quite sure how in the UX to display the stack traces versus just the counts.

**Comment by jamesefhawkins** [comment]
From a user:

> Man, you know what would be amazing if you could do it - if you can start doing anticipations of user journeys based on previously observed ones, and then because you have the resulting stack traces and services called, start to anticipate the various functions/services being called...  avoid cold function spin ups and that sort of thing. you might be able to drastically improve performance and conversion/ engagement stats

**Comment by jamesefhawkins** [comment]
From another user:

> What I'd do (and would probably be more useful) is to put together a library of controls (or web components made with stencil or svelte) that the user can embed into their own infrastructure - that would ease integration with PostHog because most of the time people want to have a unified dashboard to see things on, and not have to integrate multiple dashboards with different look and feel 
and protect all of them with authentication mechanisms



> Building the main used feature-set should be the focus here, because PostHog is just starting. For more complex scenarios, I'd think of a light plugin system that can work in conjunction with PostHog to allow users to implement more complex scenarios and avoid polluting the codebase with things that are used only by a minority of users/integrators

> To give you an example of what I meant with `analytics components/widget library`: https://github.com/searchkit/searchkit these guys are doing the same thing for search.

> For the record, I think this is also something for PostHog 2.0 or even PostHog 3.0 but it would allow users to use components (that would manage their state/api calls to the PostHog server by themselves) and style them themselves if they wanted (so these things could exist alongside the default dashboard)

**Comment by Tannergoods** [comment]
Requested by: https://app.hubspot.com/contacts/6958578/contact/31801/
