### ISSUE TITLE
Early Access Management issues

### ISSUE THREAD

**Issue by neilkakkar** [PostHog/posthog#17841]
## Bug description

1. Early access management says its in beta on the page but not the sidebar (I get that there probably isn't room).
2. It is slightly jarring for the button to be "New public beta" as there is no mention of beta elsewhere
3. The empty state button is "Create feature" which it is inconsistent with the public beta button (but I think it's better).

**Comment by kiran-4444** [comment]
I'd like to work on this. If I understand this correctly, I guess you want that "New public beta" to be same as "Create feature" or the other way around? Also, I observed that "cancel" button isn't working on "New Feature Release" page and I guess we can add that too to this issue.

**Comment by neilkakkar** [comment]
correct, 'create feature' is good 👍
