### ISSUE TITLE
Switching between action and event for entity filtering doesn't show options

### ISSUE THREAD

**Issue by EDsCODE** [PostHog/posthog#1784]
## Bug description

*Please describe.*  
When you switch from actions to events or events to actions when you're trying to add an entity, the list doesn't appear

*If this affects the front-end, screenshots would be of great help.*  

## Expected behavior
The list of events/actions should appear

## How to reproduce

1. Go to trends page
2. Try to add an entity
3. Switch from the selected group to the other group (events -> actions, or actions -> events)

## Environment

- PostHog cloud or self-managed? App.posthog
- PostHog version/commit

**Comment by yakkomajuri** [comment]
Closing in favor of #1909
