### ISSUE TITLE
Reduce logic dependency on "unit" tests

### ISSUE THREAD

**Issue by EDsCODE** [PostHog/posthog#1786]
## Is your feature request related to a problem?

*Please describe.*
Our backend tests should be scoped down so that they don't have several dependent segments of logic that could cause everything to break together.

For example, in unit tests related to cohorts, we shouldn't be calling `cohort.calculate_people()` and instead use the ORM to add people to the cohort manually.

## Describe the solution you'd like
Remove as much logic in a unit test as possible if it isn't meant to be tested in the unit test

## Describe alternatives you've considered
Don't remove

**Comment by macobo** [comment]
Would using [pytest](https://docs.pytest.org/en/latest/) over unittest be of use here? 

It has great support for creating file and test-specific fixtures. We could remove `Cohort.calculate_people` that way (make it into a fixture), cleaning up the code by moving test-only code out of the models. As the next step, we could then make newer fixtures for specific usecases based on the file/feature.
