### ISSUE TITLE
Base preview on dev.Dockerfile?

### ISSUE THREAD

**Issue by tino** [PostHog/posthog#1799]
## Is your feature request related to a problem?

I wanted to get started locally. I checked the docs. As I didn't want to have to build the containers locally ([as described here](https://posthog.com/docs/deployment/deploy-docker#generic-docker-installation-tutorial)), I thought I could use the `preview` image. Then I had a hard time getting the toolbar to work, as that doesn't serve the toolbar.js file! (And this isn't easily spotted in the console either.)

## Describe the solution you'd like

I would suggest putting everything in one `preview` container and extending the oneliner so that it opens the right ports and you can run the full functionality without having to clone & build stuff!

**Comment by Twixes** [comment]
Hey! This is not relevant anymore, as the `preview` container has stopped being viable and has been removed.
