### ISSUE TITLE
Alerts when conversion rate drops below a certain threshold

### ISSUE THREAD

**Issue by MarconLP** [PostHog/posthog#18008]
## Is your feature request related to a problem?

I want to get notified when a conversion rate of a funnel drops below a certain threshold.

## Additional context

https://posthog.com/questions/how-to-monitor-conversion-rates-and-set-up-alert-in-slack

**Comment by jannesblobel** [comment]
+1

**Comment by ipropper** [comment]
+1

**Comment by webjunkie** [comment]
Closing as duplicate of #14331
