### ISSUE TITLE
Add the ability to copy a Feature Flag or Experiment to another environment

### ISSUE THREAD

**Issue by jurajmajerik** [PostHog/posthog#18027]
## Is your feature request related to a problem?

From a customer:

>  I don't see a way to copy a feature flag or experiment to another environment, but that would be very helpful.

## Additional context

Internal ticket: https://posthoghelp.zendesk.com/agent/tickets/6547

**Comment by neilkakkar** [comment]
duplicate of https://github.com/PostHog/posthog/issues/13160 :)
