### ISSUE TITLE
Uninstall button is visible through the app drawer

### ISSUE THREAD

**Issue by MarconLP** [PostHog/posthog#18029]
## Bug description

![2023-10-17 at 09 03 02@2x](https://github.com/PostHog/posthog/assets/13001502/02024b09-95ca-4d8a-bfd7-7679b8a74f0a)

**Comment by Justicea83** [comment]
Can you add more context. Like the reproducible steps and all?

**Comment by Justicea83** [comment]
Made a PR with a completely unrelated failing cypress test, can someone be assigned to take review? @raquelmsmith
