### ISSUE TITLE
Improve feature flags model [UX]

### ISSUE THREAD

**Issue by paolodamico** [PostHog/posthog#1807]
## Details
Currently, the feature flags model have a `name` and `key` attributes (see screenshot below), however based on how the keys are used (e.g. `billing-page`, `alt-subscription-button`) it'd be more intuitive to use the `key` more as a name, and the name as a description (allowing for more details).

![image](https://user-images.githubusercontent.com/5864173/95013099-d1edfb80-0635-11eb-9f75-0eb4241eb645.png)

We can therefore do the following improvements:
- [ ] Change `name` to `description` (can be implemented only as a change on the UI, no need to change the entire model).
- [ ] Description should now no longer be required.
- [ ] Invert order of `name` & `key` (in columns and form).
- [ ] Convert the description text field to a multi-line text field.
- [ ] Add placeholder information to the inputs (e.g. `new-signup-page` & "When on, the redesigned sign up page will be shown")
- [ ] Add an info icon next to the key title (see image below) with a tooltip containing more information explaining what they key is, the format, and particularly mention the consequences of changing it.
<img width="320" src="https://user-images.githubusercontent.com/5864173/95013261-13cb7180-0637-11eb-9327-43e3edf34ba1.png">

**Comment by siddharajmane** [comment]
Hi, can you assign me this!! I am willing to contribute.

**Comment by Twixes** [comment]
Sure, this is yours @siddhu890

**Comment by siddharajmane** [comment]
Hey, can you help me where the template resides on the project repository?

**Comment by Twixes** [comment]
It's [FeatureFlags.js](https://github.com/PostHog/posthog/blob/93aebb9e7bac9150bd91607c8fba4708342ea4f1/frontend/src/scenes/experiments/FeatureFlags.js).

**Comment by timgl** [comment]
@siddhu890 Any progress on this so far?

**Comment by paolodamico** [comment]
Adding to this. It isn't clear that you don't need to specify a roll-out percentage (i.e. 100% roll-out = not checking the roll-out box). We need better language and UX here (e.g. "Would you like to roll-out this flag only to a percentage of users?")
