### ISSUE TITLE
Disable /preflight on deployed instances

### ISSUE THREAD

**Issue by paolodamico** [PostHog/posthog#1808]
Currently our `preflight/` endpoint is accessible at any time, even after the instance has already been correctly deployed. We should remove these routes after the app has been deployed (i.e. at least one user has been created in the instance), to avoid potentially leaking some information about the instance's setup (as we add more functionality to this page). To accomplish this,
- The `_preflight/` route should be disabled altogether.
- The `preflight` route should redirect to the route location (`/`) on the frontend.

**Comment by Twixes** [comment]
I think it'd actually be OK if `/_preflight` was available all the time, as it's not sensitive data. In fact we have endpoints `/_health` and `/_stats` as well, which don't differ much, so maybe it'd make sense to merge these three "underscore" endpoints into one `/_status` that'd contain relevant instance status information?

**Comment by J0** [comment]
Hi, 

Can I take this issue as well?

**Comment by J0** [comment]
Looks like there's a PR filed so I guess not D: Will look for other issues then.

**Comment by samcaspus** [comment]
hey @J0  sorry i though as no pr was made, no one was working on it. my bad

**Comment by J0** [comment]
@samcaspus No worries! The end goal should be to resolve the issue -- doesn't matter who solves it-- so it's great that you've filed a PR :) I'll look for other issues.
