### ISSUE TITLE
Change messaging around statistical significance after expected number of participants

### ISSUE THREAD

**Issue by corywatilo** [PostHog/posthog#18084]
<img width="1281" alt="image" src="https://github.com/PostHog/posthog/assets/154479/cdfc5510-cd76-4b57-97dc-0ff54a845762">

The message saying "Your results are not statistically significant" appears after the suggested number of participants _and_ a moderate difference in conversion rate between a control and a test.

Suggesting we change the messaging around this to assure people that it's safe to end the test.

cc @neilkakkar

**Comment by jurajmajerik** [comment]
The new banners should provide more clarity here - closing the issue.
