### ISSUE TITLE
No space left on device

### ISSUE THREAD

**Issue by Charuru** [PostHog/posthog#1809]
## Bug description
My installation isn't working, when I ssh into the server and try to bring it back up I see this:

root@posthog-nyc3-01:~# docker-compose up -d
Failed to write all bytes for _yaml.so
fwrite: No space left on device

How do I fix this issue? What could be taking up the space?

## How to reproduce

1. 
2. 
3. 

## Environment

- PostHog cloud or self-managed?
- PostHog version/commit

**Comment by Twixes** [comment]
Hi! This looks like less of a PostHog issue and much more of a Docker one. Since Docker installs its own OSes for its machines, it uses quite a bit of space. Add to that increasing database size and you can get an installation that's too large for a server that's on the smaller side. What are your server specs though?

**Comment by Charuru** [comment]
Thanks, I'm using a DO with 2 VPUs, 4GB RAM and 80GB of Disk. I've been using the server with posthog for a month and have restarted once already. Do I just increase the size of disk? How do I check how large the postgres installation is?

**Comment by Twixes** [comment]
You should be able to check PostHog's in-container DB size with command
```bash
docker exec posthog_db psql -U posthog -W posthog -c "SELECT pg_size_pretty(pg_database_size('posthog'));"
```

**Comment by Charuru** [comment]
Thanks I see  

pg_size_pretty
----------------
 67 GB
(1 row)

Is this a concern? It's pretty close to my limit. Should I be limiting data? Are there settings in posthog for that?

**Comment by Twixes** [comment]
That's a lot for an 80 GB disk. Could you share the major offenders (tables) as well? That'd help determine how to alleviate this. Run command:
```bash
docker exec posthog_db psql -U posthog -W posthog -c 'SELECT relname as "table", pg_size_pretty(pg_total_relation_size(relid)) AS "size" FROM pg_catalog.pg_statio_user_tables ORDER BY pg_total_relation_size(relid) DESC LIMIT 5;'
```

**Comment by Charuru** [comment]
Thanks for showing the commands. 

         table         |  size
-----------------------+---------
 posthog_event         | 51 GB
 posthog_element       | 14 GB
 posthog_action_events | 1281 MB
 posthog_elementgroup  | 975 MB
 posthog_person        | 118 MB
(5 rows)

**Comment by Twixes** [comment]
Thanks! Alright, so the best course of action would be to increase storage size, because that's too many events for such a small disk (best if you can increase size in place, otherwise you'll have to do some migrating). You can also of course purge old events, though that data may be valuable.

**Comment by Charuru** [comment]
Thanks, so this all looks normal and not something like out of control logs? What's the best way to purge old events, is there a way to do it in posthog?

**Comment by yakkomajuri** [comment]
Hey @Charuru! This page might offer some insight:

[PostHog Docs - Deleting Bulk Data](https://posthog.com/docs/configuring-posthog/deleting-data)

**Comment by Charuru** [comment]
@yakkomajuri thanks, is there a solution if I don't want to have to do this all the time or should I just give up and get some bigger HDs.

**Comment by Charuru** [comment]
Also guessing a lot of my data will be from autocapture, how do I turn that off?

**Comment by yakkomajuri** [comment]
Hey @Charuru! Well you should probably increase your disk capacity. Turning off autocapture will help, but only for future events. That will reduce the flow of events, but if you're already at the limit, it won't really help.

Nevertheless, we do have [documentation on disabling autocapture](https://posthog.com/docs/integrations/js-integration#config).
