### ISSUE TITLE
Redis worker at 100% memory, posthog fails to process data

### ISSUE THREAD

**Issue by rksm** [PostHog/posthog#1811]
## Bug description

Hello,

we’ve been running an AWS / Fargate posthog instance with the [default config](https://github.com/PostHog/deployment/blob/master/aws/cloudformation/ecs/posthog.yaml) for a while. We’ve medium usage, maybe 50 incoming POSTs of event data / minute. We observed multiple times that the redis worker memory usage spikes to 100%. Subsequently, the the dashboard loads but the data requests return 5xx errors. Event POSTs fail as well. Restarting the redis node helps for a few days.

![Screen Shot 2020-10-05 at 7 39 15 PM](https://user-images.githubusercontent.com/467450/95121504-6a2bd380-074f-11eb-9e9d-9468f8cfa6d6.png)

## How to reproduce

This happens every couple of days by simply leaving the default install running.

## Environment

- PostHog self-managed
- PostHog 1.14.0

**Comment by timgl** [comment]
Hey there, sorry for the late response here. You're volume is likely too high for the standard setup, so you'll need to increase the size of your instance!

**Comment by rksm** [comment]
Alright, we'll try that. Thank you!

**Comment by Rcjuk** [comment]
When we say 'increase the size of your instance!' what do we mean here? I've only starting noticing this issue myself recently, never ran into this before upgrading.

**Comment by timgl** [comment]
@Rcjuk In general upgrading memory, cpu etc should help. However if this only happened because you've upgraded that is a little bit more worrying. What version did you upgrade from? Also could you post a screenshot of your Status page (Under settings in the sidebar)

**Comment by mariusandra** [comment]
@timgl this mojght be related and I don't have to dig into this today, but while working on the plugins, I noticed the redis instance on the Heroku preview app had over 100k keys stored, despite being what I would consider a rather minimal setup. 

![Screenshot_20201021-154438](https://user-images.githubusercontent.com/53387/96728415-62f20000-13b4-11eb-9bb5-9d3532e8f7c6.jpg)

Those keys seem to have had an expiry date, as they have dropped off until now. What might have caused them, I can't say.

**Comment by Rcjuk** [comment]
<img width="994" alt="Screenshot 2020-10-21 at 14 48 19" src="https://user-images.githubusercontent.com/1845743/96728897-7731ff00-13ac-11eb-9ced-f27d9f233eea.png">

Before these spikes started I don't recall having any issues with Redis at all. I bumped Redis to a bugger instance but it just kept going up.

The version it started happening from was 1.14.0 I believe.

<img width="532" alt="Screenshot 2020-10-21 at 14 57 24" src="https://user-images.githubusercontent.com/1845743/96730093-c462a080-13ad-11eb-95b8-b816a37adf6e.png">

**Comment by timgl** [comment]
Yeah a bigger redis instance won't help as it will just increase the problem the workers have to deal with. What kind of hardware is your instance on currently? And how are you deployed (AWS/Heroku etc?)?

**Comment by Rcjuk** [comment]
<img width="586" alt="Screenshot 2020-10-21 at 15 03 47" src="https://user-images.githubusercontent.com/1845743/96730954-a184bc00-13ae-11eb-8a4c-c0ff34fc976a.png">

Fargate 2x the above. Just bumped up to four but I suspect the events are stuck in Redis and not being processed?

Maybe the table needs partitioning but not quite sure how to run the partition scripts within the context of Fargate.

**Comment by timgl** [comment]
It could also be database constrained, so might be worth checking if that is under strain. If the database and workers have ample capacity they should start clearing down the redis queue.

In the meantime we'll see if we can find anything that indicates why this is suddenly happening after upgrade

**Comment by Rcjuk** [comment]
Database seems to be normal. Nothing standing out in the metrics. 👍

Just looks like the events are stuck in Redis.

**Comment by Rcjuk** [comment]
<img width="477" alt="Screenshot 2020-10-26 at 17 15 42" src="https://user-images.githubusercontent.com/1845743/97205099-e34aa380-17ae-11eb-8f6a-0dfa8d2123b3.png">

I upgraded to the new version and I still get this. Any idea how to troubleshoot this? 

Events stuck in Redis.

**Comment by Rcjuk** [comment]
```2020-10-26 17:21:29 UTC:172.31.27.161(42776):posthog@posthog:[14281]:STATEMENT: INSERT INTO "posthog_elementgroup" ("team_id", "hash") VALUES (1, 'a90b8e1f4d2e263a66c1057068aaa8d3') RETURNING "posthog_elementgroup"."id"
2020-10-26 17:21:29 UTC:172.31.27.161(42778):posthog@posthog:[14282]:ERROR: duplicate key value violates unique constraint "unique hash for each team"
2020-10-26 17:21:29 UTC:172.31.27.161(42778):posthog@posthog:[14282]:DETAIL: Key (team_id, hash)=(1, b06e192b111d8ee9a5f43c97b126ef77) already exists.
2020-10-26 17:21:29 UTC:172.31.27.161(42778):posthog@posthog:[14282]:STATEMENT: INSERT INTO "posthog_elementgroup" ("team_id", "hash") VALUES (1, 'b06e192b111d8ee9a5f43c97b126ef77') RETURNING "posthog_elementgroup"."id"
2020-10-26 17:21:29 UTC:172.31.27.161(42780):posthog@posthog:[14283]:ERROR: duplicate key value violates unique constraint "unique hash for each team"```

**Comment by timgl** [comment]
One thing that's worth trying is setting `ASYNC_EVENT_ACTION_MAPPING=True` as an environment variable. That will calculate actions async rather than on every event insert.

**Comment by Rcjuk** [comment]
Thanks. Did try that but not much difference :( 

<img width="922" alt="Screenshot 2020-10-28 at 17 17 51" src="https://user-images.githubusercontent.com/1845743/97472230-8501fa00-1941-11eb-9424-685a9c0ed303.png">

**Comment by timgl** [comment]
Sorry just to clarify, is the only issue you're having that there are a lot of items in Redis? Or are other parts of the system not working?

The number of items in redis going up doesn't necessarily mean events are getting stuck. Are you seeing events coming in reasonably instantly on the /events page for example?

(Also apologies for the slightly annoying process of debugging over github!)

**Comment by mariusandra** [comment]
Hey, playing around on one heroku instance today I also noticed an ever increasing redis key count, even though events were processed fairly quickly. I realised that almost all of the "stuck" events were of type `SUCCESS`, leading me to believe that these are acknowledgements to the caller that the task completed, which could be waited for, similar to the example below:

```python
from celery import Celery

app = Celery('tasks',
    broker='amqp://',
    backend='amqp://'
)

@app.task
def add(x, y):
    return x + y

if __name__ == '__main__':
    result = add.apply_async((1, 2), serializer='json')
    print(result.get())  # wait for the result
```

I'll have a look at this in more depth tomorrow...

**Comment by Rcjuk** [comment]
> Sorry just to clarify, is the only issue you're having that there are a lot of items in Redis? Or are other parts of the system not working?
> 
> The number of items in redis going up doesn't necessarily mean events are getting stuck. Are you seeing events coming in reasonably instantly on the /events page for example?
> 
> (Also apologies for the slightly annoying process of debugging over github!)

No problem!

Sorry yes, barely anything new is coming into the raw events tab. I'm lagging a few days behind. I've tried upping the amount of workers also but doesn't seem to be doing anything.

**Comment by Rcjuk** [comment]
<img width="954" alt="Screenshot 2020-10-28 at 20 01 12" src="https://user-images.githubusercontent.com/1845743/97490141-5b080200-1958-11eb-860b-6e197c215279.png">

We hit a 100% and then this happened....

<img width="922" alt="Screenshot 2020-10-28 at 20 01 50" src="https://user-images.githubusercontent.com/1845743/97490192-6c510e80-1958-11eb-8d83-c18fc22aec3f.png">

Interesting

**Comment by mariusandra** [comment]
Hey @Rcjuk , is this still an issue in PostHog 1.16?

We [found and plugged](https://github.com/PostHog/posthog/pull/2102) some redis leaks before that release.

**Comment by Rcjuk** [comment]
The short answer is yes!

<img width="900" alt="Screenshot 2020-11-23 at 14 17 52" src="https://user-images.githubusercontent.com/1845743/99972644-af0ad880-2d96-11eb-9760-a3627f6fc00d.png">

I've not has much time to look into it but I'm on the latest version. Probably lost connection I guess?

**Comment by mariusandra** [comment]
Hi @Rcjuk I'm now slightly confused. Looking at your chart everything seems to be fine? It's flat at 15 keys. 

This is what Redis looks like for posthog running `app.posthog.com`, which is quite a busy installation:

![image](https://user-images.githubusercontent.com/53387/100209547-4d6b7b00-2f0a-11eb-975a-d825d8fa5d27.png)

It oscillates between 20-30 keys.

**Comment by Rcjuk** [comment]
<img width="1219" alt="Screenshot 2020-11-26 at 13 49 35" src="https://user-images.githubusercontent.com/1845743/100358546-3900ae80-2fee-11eb-9d13-c5e7dfd191d4.png">

It doesn't seem like it is connected is what I was getting at.

**Comment by Rcjuk** [comment]
```[2020-11-26 14:08:03,367: CRITICAL/MainProcess] beat raised exception <class 'redis.exceptions.ResponseError'>: ResponseError("Command # 1 (ZREM redbeat::schedule redbeat:debug) of pipeline caused error: OOM command not allowed when used memory > 'maxmemory'.")```

I think it's Redis memory now.

**Comment by timgl** [comment]
@Rcjuk Hm are you sure you're on the latest version here? 4GB should definitely be enough and you don't have crazy volume yet

**Comment by Rcjuk** [comment]
Yep. I've rebooted Redis and the service and it's now working again. 

I will keep an eye on it but it looks like the memory is hitting 100%, the service then loses connection and I have to reboot both Redis and then the service to get it to work again.

**Comment by timgl** [comment]
It looks to me like you'll need to increase the size of your worker instance, as your workers can't keep up with the number of events coming in. What kind of instance are you on now?
