### ISSUE TITLE
subscribe functionality not working

### ISSUE THREAD

**Issue by eriksobolt** [PostHog/posthog#18189]
## Bug description

I have setup slack integration. And when I want to create a new subscription this is not possible. I get the following pop up
![image](https://github.com/PostHog/posthog/assets/81301541/d52778b2-f467-4793-b9f7-35afeea4368d)

proof of setup
![image](https://github.com/PostHog/posthog/assets/81301541/86996bfd-6cfb-43f7-9dfa-ba81ab2ba82f)

I would expect this to work according to the docs:
![image](https://github.com/PostHog/posthog/assets/81301541/8ada628b-8122-46d8-b81e-257a6b25c50b)

## Environment

- [x] PostHog Cloud US, project ID: [please provide from https://app.posthog.com/project/settings#project-id]
- [x] PostHog Cloud EU, project ID: [please provide from https://eu.posthog.com/project/settings#project-id]
- [x] PostHog Hobby self-hosted with `docker compose`, version/commit: 1015e498e
- [x] PostHog self-hosted with Kubernetes (deprecated, see ["Sunsetting Kubernetes support"](https://posthog.com/blog/sunsetting-helm-support-posthog)), version/commit: [please provide]

**Comment by MarconLP** [comment]
I am going to assume that you are on the free or open-source plan. As you can see on the [Subscription doc page](https://posthog.com/docs/product-analytics/subscriptions), that plan does not include access to the feature.
![2023-10-26 at 09 38 38@2x](https://github.com/PostHog/posthog/assets/13001502/62370a3c-6dec-4e85-abf5-2dbe08fcaa70)

**Comment by eriksobolt** [comment]
a sorry, I missed that. Was confused with the open-source vs self-serve plans. Makes sense the slack integration is on the docs then. My bad, thanks
