### ISSUE TITLE
Surveys: allow custom text for the "Next" and "Close" buttons

### ISSUE THREAD

**Issue by jurajmajerik** [PostHog/posthog#18197]
## Is your feature request related to a problem?
From a German-speaking customer:
> Translation is not possible on the Next and Close button.

## Describe the solution you'd like
Add the ability to add custom text for these buttons.

## Additional context
Internal ticket: https://posthoghelp.zendesk.com/agent/tickets/6746

**Comment by liyiy** [comment]
Each question has its own customizable button text now! 😄
