### ISSUE TITLE
Create account error on developing locally

### ISSUE THREAD

**Issue by jamesefhawkins** [PostHog/posthog#1822]
## Bug description

* I ran through the instructions for [local development
](https://posthog.com/docs/developing-locally)
* Everything loaded and ran correctly
* I went to http://localhost:8000/signup to create an account
* I got this error:

<img width="1024" alt="Screenshot 2020-10-08 at 09 57 14" src="https://user-images.githubusercontent.com/47497682/95431127-0242dc00-094d-11eb-8981-53fd93e0e2e7.png">

## Expected behavior

I'd have expected an account to get created.

## Environment

- PostHog running locally
- Current revision: e7a944ea.

**Comment by paolodamico** [comment]
Can't replicate, can you replicate and take a screenshot of the failed HTTP request in the JS console?

**Comment by paolodamico** [comment]
Can't replicate, can you replicate and take a screenshot of the failed HTTP request in the JS console pls?

**Comment by timgl** [comment]
We think the reason for this was James tried to create an account, didn’t have the right password but apparently an account was already created

**Comment by paolodamico** [comment]
Got it, closing this then. I'll be adding a PR to capture these specific error events too regardless (see [thread](https://posthog.slack.com/archives/C018RGRS10S/p1602486169005700))
