### ISSUE TITLE
Surveys: user property date/calendar filter with time toggle bug

### ISSUE THREAD

**Issue by liyiy** [PostHog/posthog#18236]
## Bug description

1. Create an existing survey
2. Edit the existing survey
3. Add user targeting for it, choose a property that has a date type on it
4. Toggle the include time, it seems to be causing the survey to update automatically 

![image](https://github.com/PostHog/posthog/assets/25164963/5d88d182-5be4-418f-b5d2-b934cee3eca3)

*If this affects the front-end, screenshots would be of great help.*  

*If you are on PostHog Cloud it would be really valuable if you can share any links where the problem occurs. This speeds up our ability to troubleshoot tremendously.* 

## How to reproduce

1.
6.
7.

## Environment

- [ ] PostHog Cloud US, project ID: [please provide from https://app.posthog.com/project/settings#project-id]
- [ ] PostHog Cloud EU, project ID: [please provide from https://eu.posthog.com/project/settings#project-id]
- [ ] PostHog Hobby self-hosted with `docker compose`, version/commit: [please provide]
- [ ] PostHog self-hosted with Kubernetes (deprecated, see ["Sunsetting Kubernetes support"](https://posthog.com/blog/sunsetting-helm-support-posthog)), version/commit: [please provide]

**Comment by Justicea83** [comment]
@Twixes can you review this? Sorry for mentioning your name.
Do we have steps I have to follow for calling on reviewers?
