### ISSUE TITLE
RFC: Feature Flag environments

### ISSUE THREAD

**Issue by jurajmajerik** [PostHog/posthog#18267]
_For more context, see the earlier [RFC Feature flag environments](https://github.com/PostHog/product-internal/blob/main/requests-for-comments/2022-12-08-feature-flag-environments.md#221115---rfc-feature-flag-environments) from @annikaschmid. I'm offering slightly different solutions; otherwise, I'm largely just building on her work here._

# The problem
Users find it difficult to work with Feature Flags across environments. To use a flag in a different environments, they must copy it and all its configuration manually.

_Note we currently don't have the concept of environments, but our users use projects as their environments._

# Design

### Pros
- Our users already use projects as environments and copy their flags manually. This solution would free them from manual work (prone to errors).
- Easiest to implement

### Cons
- Projects are semantically different from environments, which may not align with the needs of larger clients with multiple apps (projects).

### Pros
- Cleaner separation between projects and environments.
- Ability to roll out environment to other parts of the app incrementally and as needed.

### Cons
- May introduce confusion by having environments for Feature Flags but not other features like Surveys.

### Pros
- Cleanest separation of concerns, respects the distinction between projects and environments.

### Cons
- Most complex to implement
- Introduces another layer of complexity where it might not be needed (e.g. dashboards).

# The recommendation
I recommend implementing **Option a) Add the ability to _copy_ or _move_ a feature flag to another project.** This is the quickest win which addresses the users' requirements from the [RFC user feedback](https://github.com/PostHog/product-internal/blob/main/requests-for-comments/2022-12-08-feature-flag-environments.md#user-feedback).

## Changes
We need to distinguish between the _main project ID and the _additional project ID. Every feature flag should have its main project ID set. The additional IDs are optional. We should allow users to both:
- Change the main project ID
- Set additional project ID(s)

### Model
When a user copies the flag into another project, populate the optional _additional_projects_ field with the additional project ID.
```
FeatureFlagType {
    ...
    additional_projects?: [project_id_2, project_id_3]
}
```

When a user _moves_ the flag to another environment, update the main project ID of the flag record.

### UI
Add a multi-select dropdown to the Feature Flag edit form:

<img width="1189" alt="Screenshot 2023-10-30 at 15 48 47" src="https://github.com/PostHog/posthog/assets/22996112/9cdd556e-17f8-4afa-8e89-f6f70f487045">

_Note that when using the selector, you have the option to assign an environment as the main environment. The main environment, which corresponds to the main project ID, cannot be removed. If a user wishes to remove a feature flag from the current main environment, they will need to assign another environment as the new main environment._

## Other considerations
- The `decide` endpoint must respond correctly based on the environment. One option is to pass the environment parameter, or otherwise default to the main project ID.

**Comment by neilkakkar** [comment]
hey @jurajmajerik - could you make this as a PR instead to `posthog/meta` ? Hard to comment on lines in RFCs otherwise
