### ISSUE TITLE
Multiple domains tracked separately in one account.

### ISSUE THREAD

**Issue by jamesefhawkins** [PostHog/posthog#183]
**Is your feature request related to a problem? Please describe.**

From a user:
>  As I do have quite a few side projects, I don't want to create a user per project.

Note that we already support multiple domains tracked "end to end", ie posthog.com and app.posthog.com we track internally through just having the url in the setup as posthog.com but with the snippet present on both.

**Describe the solution you'd like**
I think the easiest way to approach this would be:

1 - on the setup page, be able to add multiple URLs
2 - when you create an action, being able to then choose which URL it applies to

**Describe alternatives you've considered**
You could segment all of the dashboards by the url as a property, although "domain" isn't a standard event property.

**Additional context**

**Comment by timgl** [comment]
To do this:
- Turn the 'app_url' field into a `ArrayField(models.CharField())` and make sure that within the migration .py file those get transferred correctly.
- Update the `user` endpoint (posthog/api/user.py) to handle setting an array
- In https://github.com/PostHog/posthog/blob/master/frontend/src/Actions.js#L19 there's a `SetURLModal` function that already allows you to set a single URL. We can update that to set and select from a list of URLs

**Comment by mariusandra** [comment]
Hi @timgl, wouldn't it be better to call the field `app_urls` instead? Otherwise it's pretty easy to make a mistake and guess from the name that it's a regular string and not a list.

**Comment by timgl** [comment]
This is done

**Comment by Tannergoods** [comment]
For reference requested by:
https://app.hubspot.com/contacts/6958578/contact/33901/
https://app.hubspot.com/contacts/6958578/contact/30651
https://app.hubspot.com/contacts/6958578/contact/30351
