### ISSUE TITLE
Track library adoption

### ISSUE THREAD

**Issue by pauldambra** [PostHog/posthog#18381]
We want to track library adoption across all teams (because very meta we want to use posthog data to track posthog adoption)

In order to track adoption we need to look at

- count of events
- for all teams
- over a reasonable period of time
- broken down by library
- and library version

However a query like

```
select
    mat_$lib as library,
    JSONExtractRaw(properties, '$lib_version') as version,
    count() as c
from events
where timestamp >= now() - interval 60 day and timestamp <= now()
--and library in ('posthog-android', 'posthog-flutter', 'posthog-ios', 'posthog-react-native')
group by library, version
order by c DESC
```

times out...

because we _can't_ make use of the `order by` key on the events table. By not filtering for team or event we will always have poor or impossible performance on this query since we simply have to load all of the data in the time range. this only gets worse as posthog grows 🚀

# What could we do?

### 1. make lots of smaller queries and add them together

We could query every day for every team in Celery and post those values to PostHog as individual events

`posthog.capture('$library_adoption', {team: x, library: y, library_version: z, count: n})`

then we could use posthog to query adoption

| pros                                                                     | cons                                           |
| ------------------------------------------------------------------------ | ---------------------------------------------- |
| it keeps us dogfooding                                                   | its something new to manage                    |
| lets us use the offline cluster for querying a quick query for each team | load on the offline cluster grows with posthog |

### 2. materialize the $library_version property

we could materialize the $library_version property on the events table

| pros                                                                     | cons                                           |
| ------------------------------------------------------------------------ | ---------------------------------------------- |
| not really anything new to manage                                                  | materialization on the events table has been tricky in the past                    |
|  | we're still querying events table so won't be able to query full time range without sampling |

### 3. materialize a new table from events

We could materialize a new table from events just for counting library adoption. 

roughly it could have

- team_id
- day
- library
- library_version
- (optionally) event 
- count

and materialize into that from the events table

| pros                                                                     | cons                                           |
| ------------------------------------------------------------------------ | ---------------------------------------------- |
| we can query this table without sampling                                 | we have to manage a new table                  |
| it should be super fast to query because it would only have a limited number of rows per day per team | events table takes heavy write load, we don't know much about materialization performance |
| by including team id we can expose these counts to HogQL ||

**Comment by pauldambra** [comment]
@marandaneto brain dumped here

@fuziontech would love to slide this into your subconscious - of course first response might be "I have no context what is going on here?" 🤣

**Comment by marandaneto** [comment]
Option 1. feels like a workaround, and also adds more overhead to ingestion and clickhouse itself (more events).

Option 2. would work but I'd need to better understand what "materialization on the events table has been tricky in the past" means and why we still can't query a full-time range (still too slow/timeout? - back to the original problem again).

Option 3. We probably don't need `team_id` and `event` since the number of rows is very limited, we also don't need to investigate the event itself, just the sum per day/week/monthly or something like that.

To consider is that in the future we might need to track the adoption of specific features, eg, events that contain a certain property (let's call it `event.library_version >= 2.0.0 & event.properties['eventOrigin'] = 'httpInterceptor'` - just a naive example), the solution would be to just materialize such property instead of another new materialized table only for that, so Option 2. over 3. is still preferred due to flexibility.

Thanks for writing it up @pauldambra 
@fuziontech would love to hear your thoughts.

**Comment by pauldambra** [comment]
> why we still can't query a full-time range (still too slow/timeout? - back to the original problem again).
exactly that

>  in the future we might need to track the adoption of specific features, eg, events that contain a certain property
benefit of a materialized table is we can drop the entire table and recreate it, so we have the same flexibility without the problem that if we want all team queries we're never going to have good performance on the events table

> We probably don't need team_id and event since the number of rows is very limited,
I was imagining -> "hey posthog team what's the tool you use to track adoption?" -> "you can already do this with HogQL" so add in team id, 

and then event, yep, my spidey sense said that's the next question I can imagine where we'd want to count something. so I marked it optional cos I'm trying to guess where the ball will go and run to that spot

**Comment by marandaneto** [comment]
That makes sense, let's see what @fuziontech says, but happy if that has the same level of flexibility then :D

**Comment by pauldambra** [comment]
I think it would be something like

```
CREATE TABLE library_adoption
(
    `team_id` Int64,
    `day` Date,
    `library` LowCardinality(String),
    `library_version` LowCardinality(String),
    `event` String,
    count Int64
)
ENGINE = SummingMergeTree
ORDER BY (day, team_id, library, event);

CREATE MATERIALIZED VIEW library_adoption_mv TO library_adoption AS
SELECT
    team_id,
    toStartOfDay(timestamp) as day,
    JSONExtractRaw(properties, '$lib') as library,
    JSONExtractRaw(properties, '$lib_version') as library_version,
    event,
    count(*) AS count
FROM events
GROUP BY
    team_id,
    day,
    library,
    library_version,
    event;
```

**Comment by pauldambra** [comment]
Chatted "in person"...

Because of benefit of existing tooling and PostHog itself being built around the events table, let's first materialize a column and only add more if it still isn't fast enough

**Comment by marandaneto** [comment]
That sounds good, can we pair up on this? would like to learn how to do that.
Will events with `$lib_version` already ingested be part of the materialized column or would that work only for new events? (both are fine, just curious).

**Comment by marandaneto** [comment]
`$lib_version` is now indexed on US Cloud

**Comment by pauldambra** [comment]
currently 

```
select
    mat_$lib as library,
    mat_$lib_version as version,
    count() as c
from events
where timestamp >= now() - interval 1 day and timestamp <= now()
--and library in ('posthog-android', 'posthog-flutter', 'posthog-ios', 'posthog-react-native')
group by library, version
order by c DESC`
```

times out so this is worse than before 🤣 

I guess it's some kind of ClickHouse faking the data is available while it backfills magic but will keep this open to track what the performance of the query is when backfill is completed

**Comment by marandaneto** [comment]
I was about to reopen the issue as well, just tried out and could not get more than 6 days comparison :(
yeah, can try tomorrow.

**Comment by pauldambra** [comment]
```
select
    mat_$lib as library,
    mat_$lib_version as version,
    count() as c
from events
where timestamp >= now() - interval 60 day and timestamp <= now()
--and library in ('posthog-android', 'posthog-flutter', 'posthog-ios', 'posthog-react-native')
group by library, version
order by c DESC
```

does complete on metabase US now @marandaneto 

we could make a dashboard there?

this is something we could include in a mobile dashboard template in PostHog too!

**Comment by marandaneto** [comment]
@pauldambra we already have one http://metabase-prod-us/dashboard/48-sdk-adoption

but the query I used is still not ideal for a longer period, its definitely better than before.
