### ISSUE TITLE
Show Draft Experiments in Toolbar

### ISSUE THREAD

**Issue by iamnafets** [PostHog/posthog#18405]
## Is your feature request related to a problem?

Draft experiments are not currently shown as options in the Posthog toolbar, making it hard for developers to confirm their experiment is functioning correctly.

## Describe the solution you'd like

Draft experiments should be shown in the toolbar under the "Feature Flags" section. Override functionality should work as expected so developers can be sure that the flag is working properly.

## Describe alternatives you've considered

Currently, I need to launch the experiment, then use the tool bar to confirm, then reset the experiment. I'm not 100% sure this is even accurate. It doesn't appear to distort the expertiment data on the experiment page but it corrupts the Feature Flag insights since the flag might be deployed before the functionality is verified.

**Comment by neilkakkar** [comment]
cc: @liyiy - showing disabled flags in the toolbar should fix this case too

**Comment by neilkakkar** [comment]
@iamnafets this should be fixed now, let me know if not 👀
