### ISSUE TITLE
Unable to clone posthog repo

### ISSUE THREAD

**Issue by hanifpakeer** [PostHog/posthog#18407]
## Bug description

When we try to pull the latest master, it provides me the following error.

![image](https://github.com/PostHog/posthog/assets/45149630/4f8abf84-bc28-4a47-b63a-3867bd6eb3f8)

**Comment by pauldambra** [comment]
hopefully fixed by https://github.com/PostHog/posthog/pull/18436

I think this is a Windows specific error so I've not really any way to test it but removing the `:` from the path should be enough
