### ISSUE TITLE
Link to edit cohort

### ISSUE THREAD

**Issue by timgl** [PostHog/posthog#1842]
## Is your feature request related to a problem?

When I'm filtering a view by cohort, I probably want to see how this cohort is made and I might want to edit it

![image](https://user-images.githubusercontent.com/1727427/95779968-5cd09500-0ccb-11eb-8b1f-8824b7ebfe8c.png)

## Describe the solution you'd like

- When filtering something by a cohort, show a link (using the <Link> component) to that Cohort

## Describe alternatives you've considered

Manually navigating to the right cohort.

**Comment by Karolina-Bogacka** [comment]
hi, I've read the guidelines; can I take care of the issue?

**Comment by timgl** [comment]
For sure 👍

**Comment by timgl** [comment]
This issue is still up for grabs if anyone wants it!

**Comment by taratip** [comment]
@timgl can I work on this issue?

**Comment by yakkomajuri** [comment]
@taratip go for it!

**Comment by taratip** [comment]
Hi, just want to understand the requirement. When clicking on filtered cohort, instead of showing PropertyFilter, it should show link to that cohort, is that correct?

**Comment by timgl** [comment]
No it should still show the propertyfilter. It's just that when you open that popup, right under "Property | Cohort" (in the screenshot), there should be a link to the cohort itself so you can edit it. Ideally opening in a new tab too.

**Comment by taratip** [comment]
ok

**Comment by girlProg** [comment]
Hello, I'm guessing @taratip isn't on this any more? I'd like to make a PR for it after some styling.
![Screenshot 2020-12-07 at 02 42 54](https://user-images.githubusercontent.com/3257699/101300531-33009e00-3836-11eb-9af9-3d0ae94d4db8.png)

**Comment by Twixes** [comment]
Hey @girlProg, sure, have a go at it!

**Comment by paolodamico** [comment]
Closed via #2694
