### ISSUE TITLE
Show survey only if user has interacted with the app

### ISSUE THREAD

**Issue by liyiy** [PostHog/posthog#18434]
## Is your feature request related to a problem?

*Please describe.*

**Comment by neilkakkar** [comment]
I think once we have event based targeting, targeting based on autocapture events should work here? Or did you have something else in mind?

**Comment by liyiy** [comment]
Allowing for an "any" event interaction would be nice here

**Comment by liyiy** [comment]
"has done any action" or ultimately "has done at least x actions or has been on site for at least y time"

**Comment by marandaneto** [comment]
possible via "user sends events", "user perform actions", etc
