### ISSUE TITLE
fatal error when cloning repository in local

### ISSUE THREAD

**Issue by SeifESlimene** [PostHog/posthog#18432]
`$ git clone https://github.com/PostHog/posthog.git`

Cloning into 'posthog'...
remote: Enumerating objects: 254426, done.
remote: Counting objects: 100% (19336/19336), done.
remote: Compressing objects: 100% (2427/2427), done.
remote: Total 254426 (delta 18093), reused 17529 (delta 16901), pack-reused 235090
Receiving objects: 100% (254426/254426), 442.39 MiB | 1024.00 KiB/s, done.
Resolving deltas: 100% (194212/194212), done.
fatal: cannot create directory at 'frontend/src/mocks/fixtures/api/projects/:team_id': Invalid argument
warning: Clone succeeded, but checkout failed.
You can inspect what was checked out with 'git status'
and retry with 'git restore --source=HEAD :/'

What is the issue?

**Comment by pauldambra** [comment]
hopefully fixed by https://github.com/PostHog/posthog/pull/18436

I think this is a Windows specific error so I've not really any way to test it but removing the `:` from the path should be enough

**Comment by SeifESlimene** [comment]
> hopefully fixed by #18436
> 
> I think this is a Windows specific error so I've not really any way to test it but removing the `:` from the path should be enough
> 
> Actually looking at your output maybe it's an http clone vs ssh clone problem

Actually I'm using:

Distributor ID: Ubuntu
Description: Ubuntu 22.04.3 LTS
Release:	22.04
Codename: jammy
Kernal version: 6.2.0-36-generic

**Comment by pauldambra** [comment]
Yep, I'm guessing it was a http vs ssh clone issue.

There was another report that was on Windows and I jumped to conclusion... I used to work on windows and it would often get upset about node modules paths 🙈
