### ISSUE TITLE
Bug: Monthly trends graph last X days

### ISSUE THREAD

**Issue by paolodamico** [PostHog/posthog#1843]
## Bug description

When creating a MAUs graph with a last X days timeframe, the MAUs of the current month are counted on the data point for the last month. See screenshots below.

- Screenshot from Oct 5, MAUs between Oct 1 - Oct 5 counted on Sep data point. Oct data point not showing.
![image](https://user-images.githubusercontent.com/5864173/95827931-a43f3b80-0d34-11eb-941a-469d609d54bd.png)

- Screenshot from Oct 13, MAUs between Oct 1 - Oct 13 counted on Sep data point. Oct data point not showing.
![image](https://user-images.githubusercontent.com/5864173/95828124-d81a6100-0d34-11eb-942a-e8fc799baa27.png)

## Expected behavior
Current month's data point should be shown (counting the MAUs for that month), and the last month's data point should not be a dotted line (as it's already over).

## How to reproduce

1. Go to Trends
2. Select a monthly interval and last 90 days period.

## Environment

- PostHog cloud; latest version.

## Additional context

Reported by a user.

**Comment by EDsCODE** [comment]
Not fixed with CH as the queries work the same way so go for the fix!

**Comment by macobo** [comment]
Not 100% sure I followed the bug correctly, but this might have been fixed? 

![image](https://user-images.githubusercontent.com/148820/128676249-5ed97f7c-59d5-4274-ae85-c44caaaef016.png)

The query: https://app.posthog.com/insights?insight=TRENDS&display=ActionsLineGraph&actions=%5B%5D&events=%5B%7B%22id%22%3A%22%24pageview%22%2C%22name%22%3A%22%24pageview%22%2C%22type%22%3A%22events%22%2C%22order%22%3A0%2C%22math%22%3A%22dau%22%7D%5D&properties=%5B%5D&filter_test_accounts=true&new_entity=%5B%5D&date_from=-90d&interval=month

**Comment by paolodamico** [comment]
Indeed I think this has been fixed, closing! Wow has the UI of the app changed
