### ISSUE TITLE
Paths don't follow users if they change distinct_id

### ISSUE THREAD

**Issue by timgl** [PostHog/posthog#185]
**Describe the bug**
Within paths there's a 

**To Reproduce**
1. Go to `posthog/api/test/test_paths.py`
2. give one of the users 2 IDs
3. change one of their events to the other id
4. Watch tests fail

**Expected behavior**
Paths should follow users even if they change ID

**Additional context**
Choose not to fix this while building the Paths functionality as my guess is that paths are most useful for websites (not apps) so there shouldn't be a lot of cross-distinct-id-activity.

**Comment by mariusandra** [comment]
I believe https://github.com/PostHog/posthog/pull/1657 closes this when it lands in master (https://github.com/PostHog/posthog/pull/1657/commits/33e3ab1568963f541b37b40b26667f066f23fa91)
