### ISSUE TITLE
Permanently deleting a feature flag also deletes the associated experiment

### ISSUE THREAD

**Issue by liyiy** [PostHog/posthog#18500]
## Bug description

*Please describe.*  

Experiment flag deletion cascades, so when a feature flag is actually deleted ("deleted" and then recreated with the same name), the experiment is also deleted with it.

We don't want that to happen and a completed experiment should be able to exist without a flag?

*If you are on PostHog Cloud it would be really valuable if you can share any links where the problem occurs. This speeds up our ability to troubleshoot tremendously.* 

## How to reproduce

1.
2.
3.

## Environment

- [ ] PostHog Cloud US, project ID: [please provide from https://app.posthog.com/project/settings#project-id]
- [ ] PostHog Cloud EU, project ID: [please provide from https://eu.posthog.com/project/settings#project-id]
- [ ] PostHog Hobby self-hosted with `docker compose`, version/commit: [please provide]
- [ ] PostHog self-hosted with Kubernetes (deprecated, see ["Sunsetting Kubernetes support"](https://posthog.com/blog/sunsetting-helm-support-posthog)), version/commit: [please provide]

**Comment by neilkakkar** [comment]
This is fixed now - #18543
