### ISSUE TITLE
npm package: Store posthog as a global variable

### ISSUE THREAD

**Issue by MarconLP** [PostHog/posthog#18511]
## Is your feature request related to a problem?

When trying to debug client websites that are not using the snippet, I am unable to access posthog through the console. Which is making debugging hard.

## Describe the solution you'd like

A way to access posthog through the config. Solutions:
1. When a window var like `POSTHOG_DEBUG` is set, we could log out posthog as a variable.
2. A button in the toolbar that will log out posthog as a variable.
3. log out posthog as a variable when toolbar is being loaded.

## Additional context

https://posthog.slack.com/archives/C04MZFDA5KK/p1699535586640289

**Comment by pauldambra** [comment]
there's now at least one way to do this https://github.com/PostHog/posthog-js/pull/1108
