### ISSUE TITLE
Running into error while trying to run DEBUG=1 ./bin/migrate

### ISSUE THREAD

**Issue by arunfancraze** [PostHog/posthog#18561]
## Bug description

Hi, I bought a new Mac M1 and I tried following all the steps mentioned in https://posthog.com/handbook/engineering/developing-locally and was successfully able to complete all of them. But when I try to run DEBUG=1 ./bin/migrate, I get the following error. I have pasted the error in Notion. [https://checker-drug-d0e.notion.site/Posthog-Error-dd4d1cd6db2c4fd3bcbebd1b9b9d0820](https://posthog.com/handbook/engineering/developing-locally) I copy-pasted the error in ChatGPT and Bard and the answer from both was that This error indicates that the Django application is trying to connect to a PostgreSQL database using a role (user) named "posthog," but that role doesn't exist in your PostgreSQL database.
Note: I had a chat with Niel about the error and he suggested clearing all the docker containers and rerun, but that didn't work.

*Please describe.*  
*If this affects the front-end, screenshots would be of great help.*  

*If you are on PostHog Cloud it would be really valuable if you can share any links where the problem occurs. This speeds up our ability to troubleshoot tremendously.* 

## How to reproduce

1.
2.
3.

## Environment

- [ ] PostHog Cloud US, project ID: [please provide from https://app.posthog.com/settings/project-details#variables]
- [ ] PostHog Cloud EU, project ID: [please provide from https://eu.posthog.com/settings/project-details#variables]
- [ ] PostHog Hobby self-hosted with `docker compose`, version/commit: [please provide]
- [ ] PostHog self-hosted with Kubernetes (deprecated, see ["Sunsetting Kubernetes support"](https://posthog.com/blog/sunsetting-helm-support-posthog)), version/commit: [please provide]

**Comment by arunfancraze** [comment]
> Hey @Arun-chaitanya, might be best to move this to a separate issue, as it's a bit off topic here. Nevertheless, how are you running Docker on the M1? Do you use Docker Desktop / OrbStack / something else? What do the logs for the container say= I could imagine that this is caused by a separate Postgres instance running via Postgres.app, Homebrew, or something else.
> 
> Edit: Maybe check the output of lsof -i tcp:5432

Reply: @thmsobrmlr I am using Docker Desktop to run docker on my M1.

I ran` lsof -i tcp:5432` while my posthog-required docker containers are running, the commmand me following output.

```
arunchaitanya@Aruns-MacBook-Air ~ % lsof -i tcp:5432
COMMAND     PID          USER   FD   TYPE             DEVICE SIZE/OFF NODE NAME
postgres   1729 arunchaitanya    7u  IPv6 0xf212ae56e8b48d73      0t0  TCP localhost:postgresql (LISTEN)
postgres   1729 arunchaitanya    8u  IPv4 0xf212ae56ef463c13      0t0  TCP localhost:postgresql (LISTEN)
com.docke 42609 arunchaitanya  186u  IPv6 0xf212ae56e8b2f573      0t0  TCP *:postgresql (LISTEN)
```

**Comment by thmsobrmlr** [comment]
> ```
> arunchaitanya@Aruns-MacBook-Air ~ % lsof -i tcp:5432
> COMMAND     PID          USER   FD   TYPE             DEVICE SIZE/OFF NODE NAME
> postgres   1729 arunchaitanya    7u  IPv6 0xf212ae56e8b48d73      0t0  TCP localhost:postgresql (LISTEN)
> postgres   1729 arunchaitanya    8u  IPv4 0xf212ae56ef463c13      0t0  TCP localhost:postgresql (LISTEN)
> com.docke 42609 arunchaitanya  186u  IPv6 0xf212ae56e8b2f573      0t0  TCP *:postgresql (LISTEN)
> ```

The issue here is that you are running two Postgres instances on the same port. You need to shut down the non docker one. `sudo kill -9 1729` might do the job, but you should generally stop the thing that's running it.

**Comment by arunfancraze** [comment]
I got it @thmsobrmlr. But I am not running anything related which requires Postgres or which is running Postgres in the background. In fact, I am trying to restart and still see two PIDs. But I will try to kill the instance and check. Thanks.

**Comment by arunfancraze** [comment]
@thmsobrmlr the problem I am facing is that, even though I am killing a PID, it is again getting restarted
```
arunchaitanya@Aruns-MacBook-Air ~ % lsof -i tcp:5432
COMMAND     PID          USER   FD   TYPE             DEVICE SIZE/OFF NODE NAME
com.docke 43891 arunchaitanya  169u  IPv6 0xf212ae56e8b52573      0t0  TCP *:postgresql (LISTEN)
postgres  45356 arunchaitanya    7u  IPv6 0xf212ae56e8b31573      0t0  TCP localhost:postgresql (LISTEN)
postgres  45356 arunchaitanya    8u  IPv4 0xf212ae56ee9574f3      0t0  TCP localhost:postgresql (LISTEN)
arunchaitanya@Aruns-MacBook-Air ~ % sudo kill -9 45356
arunchaitanya@Aruns-MacBook-Air ~ % lsof -i tcp:5432  
COMMAND     PID          USER   FD   TYPE             DEVICE SIZE/OFF NODE NAME
com.docke 43891 arunchaitanya  169u  IPv6 0xf212ae56e8b52573      0t0  TCP *:postgresql (LISTEN)
postgres  45418 arunchaitanya    7u  IPv6 0xf212ae56e8b5dd73      0t0  TCP localhost:postgresql (LISTEN)
postgres  45418 arunchaitanya    8u  IPv4 0xf212ae56ec0434f3      0t0  TCP localhost:postgresql (LISTEN)
arunchaitanya@Aruns-MacBook-Air ~ % sudo kill -9 45418
arunchaitanya@Aruns-MacBook-Air ~ % lsof -i tcp:5432  
COMMAND     PID          USER   FD   TYPE             DEVICE SIZE/OFF NODE NAME
com.docke 43891 arunchaitanya  169u  IPv6 0xf212ae56e8b52573      0t0  TCP *:postgresql (LISTEN)
postgres  45496 arunchaitanya    7u  IPv6 0xf212ae56e8b2f573      0t0  TCP localhost:postgresql (LISTEN)
postgres  45496 arunchaitanya    8u  IPv4 0xf212ae56ec029713      0t0  TCP localhost:postgresql (LISTEN)
arunchaitanya@Aruns-MacBook-Air ~ % 
```

**Comment by thmsobrmlr** [comment]
Maybe try `ps auxwww | grep postgres` to find it. `pg_ctl -D /usr/local/var/postgres stop` or `brew services stop postgresql`?

**Comment by Arun-chaitanya** [comment]
I will try to figure this out and get back if I face any further issues after solving this.

**Comment by thmsobrmlr** [comment]
Good luck and let me know how it goes.

**Comment by Arun-chaitanya** [comment]
> Maybe try `ps auxwww | grep postgres` to find it. `pg_ctl -D /usr/local/var/postgres stop` or `brew services stop postgresql`?
> 

Sure I will try this

**Comment by arunfancraze** [comment]
@thmsobrmlr amazing. The above solution worked. Thanks a ton!

**Comment by anirudh24seven** [comment]
Adding this comment for posterity. I ran into a similar issue and I switched to `postgres` user with:

```
sudo su - postgres
```

to then stop the postgres service (instead of killing the process as a preference):
```
/Library/PostgreSQL/14/bin/pg_ctl -D /Library/PostgreSQL/14/data stop
```

after which I was able to run the migration command.
