### ISSUE TITLE
Typo in upgrade email

### ISSUE THREAD

**Issue by corywatilo** [PostHog/posthog#18626]
>We'd like to welcome you and to PostHog.

"and" doesn't quite fit here.

Also maybe worth considering changing the line entirely since they've likely already been around (and welcomed).

<img width="611" alt="image" src="https://github.com/PostHog/posthog/assets/154479/b71ae5da-9745-4178-b0e8-a4e9671346ae">

cc @joethreepwood @raquelmsmith

**Comment by raquelmsmith** [comment]
Hm, it's supposed to use the customer name: `We'd like to welcome you and <strong>{{ customer_name }}</strong> to PostHog.` But looks like we din't include it in the vars, whoops. I can just remove.. anything else we should put in here?

**Comment by joethreepwood** [comment]
No need to cover any of the usability stuff right now as that's handled by the marketing onboarding flow, but there's potential to merge them in the future if valuable?
