### ISSUE TITLE
Command palette shortcut clashes with chrome on win/linux

### ISSUE THREAD

**Issue by macobo** [PostHog/posthog#1866]
## Bug description

In chrome on windows and linux, ctrl + k also starts search in the address bar.

See https://support.google.com/chrome/answer/157179?co=GENIE.Platform%3DDesktop&hl=en&oco=0 under address bar shortcuts

## Expected behavior

Different/non-clashing shortcut is used or avoid triggering browser search feature.

## How to reproduce

1. Use chrome/chromium on linux
2. Ctrl + k
3. 
![Screenshot from 2020-10-14 10-45-04](https://user-images.githubusercontent.com/148820/95958830-614f9780-0e0a-11eb-94c9-b1443a5bd705.png)

## Environment

- All
- DEBUG at 38135ba73ad9c00e0181b60ea725d36ff52e76b5

**Comment by Twixes** [comment]
Hmm, how about Ctrl Shift P (like VS Code)?

**Comment by macobo** [comment]
That opens print dialog for me, but e.g. in github when writing comments they somehow prevent it.

I think there's a way to avoid the default behavior - maybe stopPropagation, preventDefault, ...?

**Comment by mariusandra** [comment]
That opens private browsing in Firefox.

CMD+K also opens the "search box" in Firefox. It used to be a separate field, but is now merged into the searchbox.

![2020-10-14 09 52 11](https://user-images.githubusercontent.com/53387/95959611-fea6cd80-0e02-11eb-94fe-c75652802f9c.gif)

**Comment by macobo** [comment]
Potential fix which works for me: 

```
--- a/frontend/src/lib/components/CommandPalette/index.tsx
+++ b/frontend/src/lib/components/CommandPalette/index.tsx
@@ -35,6 +35,7 @@ export function CommandPalette(): JSX.Element | null {
             // Lastly hide palette
             else hidePalette()
         } else if (event.key === 'k' && (event.ctrlKey || event.metaKey)) {
+            event.preventDefault()
             togglePalette()
         }
     })
```
