### ISSUE TITLE
Bug: Cmd+click opens new tab twice

### ISSUE THREAD

**Issue by paolodamico** [PostHog/posthog#1869]
## Bug description

See screen recording below.

![image](https://user-images.githubusercontent.com/5864173/95962648-efc21a00-0e06-11eb-94ff-c91e47218688.gif)

## Expected behavior

New tab should only open once.

## How to reproduce

1. Cmd+click on any link in the app.

## Environment

- Could & self-hosted f71e011a86e63c498f82fae5c1dc6d81ac663990

## Additional context
No additional context.

**Comment by macobo** [comment]
Note: Weirdly enough, does not seem to occur on my linux + chromium setup.

**Comment by paolodamico** [comment]
> Note: Weirdly enough, does not seem to occur on my linux + chromium setup.

Interesting, was able to replicate on Chrome & Firefox (macOS)

**Comment by mariusandra** [comment]
I could replicate this on FireFox and Safari, but not on Chrome (macOS).

Fix in #1890

**Comment by macobo** [comment]
Closing this since I assume this is now fixed?
