### ISSUE TITLE
"Load more events not working"

### ISSUE THREAD

**Issue by Tannergoods** [PostHog/posthog#187]
***Thank*** you for reporting bugs - we appreciate every single bug report.

**Describe the bug**
When I load more events for an action I have set up - it repeats the list and doesn't extend it 

**To Reproduce**

1. Go to and action (in this case "user signed up - event"
2. Click on 'more events'
3. See error - the events have just repeated themselves

**Expected behavior**
Old events should load 

**Screenshots**
<img width="1066" alt="Posthog" src="https://user-images.githubusercontent.com/60791437/75208516-c4cc6e00-5730-11ea-8bb8-b491285b7655.png">

**Desktop (please complete the following information):**
 - MacOS
 - Browser chrome

**Comment by jamesefhawkins** [comment]
Are you confident there are more events that have taken place? The "more events" button doesn't ever disappear (which itself might be the right solution here - just make the button go away when there is nothing more to display)

**Comment by timgl** [comment]
@Tannergoods I've fixed and pushed to app. Can you check in about 10 minutes if it works?

**Comment by Tannergoods** [comment]
@timgl perfect this is fixed
