### ISSUE TITLE
The person detail page is broken

### ISSUE THREAD

**Issue by MarconLP** [PostHog/posthog#18719]
## Bug description

The person detail page is broken
![2023-11-17 at 17 28 47@2x](https://github.com/PostHog/posthog/assets/13001502/c632fcac-eab2-41fa-806f-5c6e6c8186d3)

## How to reproduce

1. Visit https://app.posthog.com/person/f25Z9nQKAdrMsvrDP1Hz9NwsKcG5cLi23Tw2NXArFZW

**Comment by Davies-Owen** [comment]
We're running into this on our cloud-hosted instance as well. I'm able to reproduce it on Chrome, Firefox and Safari.

**Comment by jonasi** [comment]
I believe this is the cause or related
https://github.com/PostHog/posthog/pull/18662#issuecomment-1816816645

**Comment by daibhin** [comment]
Thanks for reporting. We have since shipped a fix: https://github.com/PostHog/posthog/pull/18716
