### ISSUE TITLE
Chore: Show console logs and network perf toggled ON by default

### ISSUE THREAD

**Issue by corywatilo** [PostHog/posthog#18749]
(Super tiny nit but...)

When toggling on session recording, it also toggles on console logs and network performance. (This makes sense, as you should be opted in to the full suite by default rather than forcing users to manually enable.)

Given this, the default state for the console logs and perf buttons should be _enabled_ (and grayed out). This way, only the thing you're toggling (enabling _record user sessions_) is changing when you click it, and you can already expect to get the subsequent featured that are already toggled on.

![2023-11-20 07 39 44](https://github.com/PostHog/posthog/assets/154479/e385434c-6ef3-4c18-97b5-06caed524a1b)

**Comment by namit-chandwani** [comment]
Hi @corywatilo @pauldambra @marandaneto, I've created a PR which can close this issue.
Have tested the changes locally and included a screen recording of the same in the PR description for reference.

Request you to review the PR whenever free

- PR Link: https://github.com/PostHog/posthog/pull/23900

TIA
