### ISSUE TITLE
Page content hides on render and can't be scrolled to view

### ISSUE THREAD

**Issue by phukon** [PostHog/posthog#18799]
## Bug description

Content hides on route `/onboarding/session_replay?step=sdks`

![Inkedbug_LI](https://github.com/PostHog/posthog/assets/60285613/53b951c7-18d7-4ccf-8e8a-7f61ccc480dd)

Can't view the content unless the page is zoomed out to at least 50%.

![ergfrefefgregreghrehghdrhjddascewrc24e23 ](https://github.com/PostHog/posthog/assets/60285613/8974c032-1fdd-4399-ae07-a5aab0a76a88)

This bug plagues mobile screens as well. Content hidden and scrolling not possible.

![Screenshot 2023-11-21 194001](https://github.com/PostHog/posthog/assets/60285613/b32ca7e3-8fbc-4f16-96db-49d032bdb23d)

*Please describe.*  
*If this affects the front-end, screenshots would be of great help.*  

*If you are on PostHog Cloud it would be really valuable if you can share any links where the problem occurs. This speeds up our ability to troubleshoot tremendously.* 

## How to reproduce

1. Sign up on PostHog
2. Choose a product
3. Click on any framework tab to render content

## Additional info

- Google chrome Version 119.0.6045.160 (Windows) (64-bit)
- Screen res: ‎1920 x 1080

</body>
</html>

## Environment

- [ ] PostHog Cloud US, project ID: [please provide from https://app.posthog.com/settings/project-details#variables]
- [ ] PostHog Cloud EU, project ID: [please provide from https://eu.posthog.com/settings/project-details#variables]
- [ ] PostHog Hobby self-hosted with `docker compose`, version/commit: [please provide]
- [ ] PostHog self-hosted with Kubernetes (deprecated, see ["Sunsetting Kubernetes support"](https://posthog.com/blog/sunsetting-helm-support-posthog)), version/commit: [please provide]

**Comment by raquelmsmith** [comment]
Hm, thanks for letting us know, taking a look

**Comment by phukon** [comment]
I made a minor change in the SCSS file pertaining to this UI issue. Can I make a PR?
