### ISSUE TITLE
Cannot Enable Object Storage

### ISSUE THREAD

**Issue by noobd3veloper** [PostHog/posthog#18836]
I've set up the posthog self hosted via docker (hobby deployment).

I set the following variable in docker-compose.base.yml

<img width="803" alt="image" src="https://github.com/PostHog/posthog/assets/26892245/68ba0187-f812-4792-a0f3-98c125c19b6b">

under plugin service.

Still in front end it is showing no.

<img width="575" alt="image" src="https://github.com/PostHog/posthog/assets/26892245/0fbfedfe-1ce0-437b-9c33-e3c310dd6d78">

**Comment by benjackwhite** [comment]
That env needs to be present on all containers as it is used not just by the plugin-server but also by the web app for example for playback

**Comment by noobd3veloper** [comment]
Hello @benjackwhite , I already added to all images ing docker-compose.yml. still same result. Can you provide me a sample docker-compose.yml to check if i've missed something. thanks
