### ISSUE TITLE
Share feedback in command palette is confusing

### ISSUE THREAD

**Issue by paolodamico** [PostHog/posthog#1884]
## Is your feature request related to a problem?

The share feedback custom command has confusing UX.

- It's hard to understand that you're supposed to type the message on the command input to send it (@EDsCODE had this issue too).

![image](https://user-images.githubusercontent.com/5864173/96002424-624bed80-0e39-11eb-928d-3f33c929cc2b.png)

- I don't think it's great to have the extra email option, we're just potentially adding strain to users without any huge additional value.
- We're inherently predisposing users to writing short feedback. We want them to be as verbose and provide as much context as possible.

In addition, there seems to be some weird behavior with the way command results are shown (see screenshot below). I would expect that typing share would show share feedback as the first result.
![image](https://user-images.githubusercontent.com/5864173/96001771-b2768000-0e38-11eb-9c5b-6f385513f441.png)

## Describe the solution you'd like

I think the following UX would work better:
- After selecting the share feedback command you get the two options (send a message & schedule a call). You must select one.
- If you select the send a message option, we open another screen where the text input is large and multi-lined (add a button to send or Cmd + Enter to send).

## Describe alternatives you've considered
Keep the current UX?

## Additional context
The feature was shipped before having time for a feedback round.

**Comment by Twixes** [comment]
Sure, _ad_:
1. Agreed that it's not super clear with those 2 additional options. Can make "Send Message Directly to PostHog" a subcommand maybe?
2. We can remove the email option, added it just because it was the original "Share Feedback" command.
3. That behavior is the result of always putting global results last. Its to promote context-dependent commands. We could make the global scope equal to all others if the UX pros outweigh the cons here.

**Comment by paolodamico** [comment]
1. Agreed!
1. Random idea, how about replacing it with submit an issue on Github? If we do move forward with this, we might even go a step further and allow them to create the issue directly from the command palette.
1. The ideal UX would be to weight the score of the fuzzy match, so context-dependent commands have a higher priority, but if a match score is considerably higher for a global command, show that first. Might be an over optimization for now.

**Comment by jamesefhawkins** [comment]
> * It's hard to understand that you're supposed to type the message on the command input to send it (@EDsCODE had this issue too).

As a user, I also had this issue.
