### ISSUE TITLE
Simplify AWS CloudFormation deployment instructions

### ISSUE THREAD

**Issue by macobo** [PostHog/posthog#1889]
## Is your feature request related to a problem?

The current [AWS cloudformation documentation](https://posthog.com/docs/deployment/deploy-aws#cloudformation-install-recommended) is quite wordy, making setting things up intimidating and take far too long.

## Describe the solution you'd like

The best-in-class solution and documentation for setting up ECS clusters with CloudFormation is https://github.com/buildkite/elastic-ci-stack-for-aws.

It has:
- Clickable deploy button
- AWS CLI instructions for install + upgrading based on a local config file
- Repo with a issue tracker and relevant config -> easy for users to make improvements

~~Ideally we'd also create a repo, link to documentation from there and automatically deploy relevant config changes to S3 on merge.~~ This already exists at https://github.com/PostHog/deployment.

## Describe alternatives you've considered

Keep current solution.

**Comment by ahtik** [comment]
@macobo Yesterday I also created https://github.com/PostHog/posthog/issues/1887 about a potential option for more experimental AWS deployments :)

For more production grade solutions Terraform is often used, having also Azure and GCP support and makes it easy to maintain.  

I have used the Terraform scripts and applying them with CLI but there's also a "Cloud" offering to manage these deployments in a more controlled fashion.

**Comment by macobo** [comment]
Luckily the two issues are complementary, rather than in competition. :)

I'm generally a huge fan of CloudFormation - it worked beautifully for both setting up and managing buildkite long-term within my last org without needing to introduce a lot of new tooling.

**Comment by yakkomajuri** [comment]
I'm all for simplifying our deployment processes. We've also had quite a few users complain about CloudFormation instances. 

[Metabase](https://github.com/metabase/metabase) for example credits part of their success to their ease of deployment. Definitely something we should try to smoothen out as much as possible.

**Comment by macobo** [comment]
Most of this has been improved, one specific suggestion under https://github.com/PostHog/posthog.com/issues/528
