### ISSUE TITLE
Feature Flags and Cohorts Table UX suggestion

### ISSUE THREAD

**Issue by mariusandra** [PostHog/posthog#1902]
## Is your feature request related to a problem?

Some easy to fix UX issues with tables in the system.

## Describe the solution you'd like

- With more than 10 rows the Feature Flags gets a useless pagination. Could we replace it with an endless load more button with a count and set the default to at least 2 screen heights" so 50+ items?
![image](https://user-images.githubusercontent.com/53387/96229602-74dc3900-0f97-11eb-9d06-44460e6153a9.png)

- You can't sort by the columns on the cohorts/feature flags page. Probably elsewhere as well. I tried to quickly scan by name to find something on both pages, but the lists were sorted by created_at. (Which wasn't obvious on the feature flags because of the pagination)

## Describe alternatives you've considered

- CMD+F

## Additional context

- This treatment should be given to all the other tables in the system, so ideally this logic should be extracted into something you can easily plug into any used antd table.

**Comment by Twixes** [comment]
Seems addressed.
