### ISSUE TITLE
Auto-capture of buttons not capturing button text

### ISSUE THREAD

**Issue by lillichoung** [PostHog/posthog#19068]
## Bug description

Button text not captured in autocapture. Might be because button has other children as well

## How to reproduce

Create a button component which takes icon in as props and renders them as the button children

```
    <button
      title={text}
      onClick={props.onClick}
      {...props}
    >
      {iconLeft}
      {text}
      {iconRight}
    </button>
```

Clicking the button auto-captures log as "clicked button".
When inspecting the elements, button children appears empty:

<img width="1208" alt="Screenshot 2023-12-04 at 4 01 15 PM" src="https://github.com/PostHog/posthog/assets/35208156/507c6d27-faf4-4a4e-aacc-95bd15dbb1d0">

## Environment

- [X] PostHog Cloud US, project ID: 6771

**Comment by pauldambra** [comment]
Hey @lillichoung, 

is the site public for us to look at? Can you share what the rendered HTML looks like? 

Thanks

P

**Comment by lillichoung** [comment]
Yes its https://www.shibuya.xyz/about here! The button is the CTA "Apply to become a partner". Thanks!

**Comment by pauldambra** [comment]
Hmmm, I can see that clicking e.g. the careers link in the header captures correctly.

I notice that the CSS classes for the button has `\r\n` new lines in

```
<button title="Apply to become a partner" class="flex items-center justify-center whitespace-nowrap rounded font-bold transition-all
      bg-grayscale-300 bg-opacity-10 backdrop-blur-md text-grayscale-300 hover:bg-opacity-20 
      px-8 py-6 text-lg-button 
      w-full sm:w-auto">Apply to become a partner</button>
```

that shouldn't be a problem but does stand out for me....

We'll check if this is a bug in posthog-js

**Comment by pauldambra** [comment]
(in the meanwhile, would be interesting to see if this works if you're able to remove the new lines from the class lists)

**Comment by pauldambra** [comment]
We've released 1.93.5 of posthog-js which I'd like to see if it fixes this issue for you. Looks like you have posthog bundled in with your site so would need to update and re-deploy?

**Comment by lillichoung** [comment]
Hmm, unfortunately it seems the logs appear the same, with the empty button element :( Updated posthog-js.

**Comment by pauldambra** [comment]
One thing I notice that might be throwing us off is that you have a `<button>` nested inside an `<a>`.  Pedantically you shouldn't nest an `a` in a `button` or vice versa https://w3c.github.io/html-reference/button.button.html#button.button-constraints

I think we should handle it or at least warn you if we can't - but it may well start working if you had only an `<a>`

**Comment by pauldambra** [comment]
Yep, that's what is throwing us off.

When an element is clicked we check if it has text directly itself. If it doesn't have text directly itself (which it doesn't here) we look through its children and get text from spans.

It'd be a pretty significant change to start getting all child text. So, my recommendation here is that you wrap the button content in a span. Or don't have an anchor with a nested button.

To test this I manually edited the page and added a span and we captured the text

<img width="1199" alt="Screenshot 2023-12-05 at 20 39 07" src="https://github.com/PostHog/posthog/assets/984817/73efed96-c0fa-476a-bd61-22dab097e485">

**Comment by lillichoung** [comment]
So I got rid of the button within an anchor tag, so its just an anchor tag with text and an icon as children... still hitting the same issue. Will try span next 

```
<div class="flex flex-auto flex-col overflow-hidden font-rules text-white text-grayscale-300">

    <main>

        <section class="flex h-[calc(100vh-132px)] min-h-[calc(800px-132px)] flex-col justify-center px-8 lg:px-16">

            <div class="-mt-[132px] flex flex-col items-start justify-center gap-4">

                <a class="w-full hover:underline sm:w-auto" href="mailto:partnerships@shibuya.xyz">

                    <div class="ease-in transform transition-all duration-500 delay-1000 opacity-100 translate-y-0">

                        <>

                            <>

                                <>

                                    <button></button>

                                </>

                            </>

                        </>

                    </div>

                </a>

            </div>

        </section>

    </main>

</div>
```

**Comment by lillichoung** [comment]
Indeed, it worked when I removed the newlines! Thank you for your support

![Screenshot 2023-12-07 at 2 43 31 PM](https://github.com/PostHog/posthog/assets/35208156/9a3abc72-a539-4b4a-a4ab-7371bfcd6d0d)

**Comment by pauldambra** [comment]
Excellent news! Thanks for sticking with us!
