### ISSUE TITLE
Actions aren't appearing when you try to view them in dropdown

### ISSUE THREAD

**Issue by EDsCODE** [PostHog/posthog#1909]
## Bug description

*Please describe.*  
If you try to add an entity and start on the raw events dropdown, clicking on actions will show nothing
*If this affects the front-end, screenshots would be of great help.*  
<img width="423" alt="Screen Shot 2020-10-16 at 4 05 29 PM" src="https://user-images.githubusercontent.com/13127476/96268637-48282180-0f97-11eb-886c-6245c7a74baf.png">

## Expected behavior
Actions should be loaded
## How to reproduce

1. Go to insights page /trends. Make sure there's already an entity added that's an event (the default $pageview event should be there)
2. Click on $pageview to change the entity
3. Try to change to an action

## Environment

- PostHog cloud or self-managed?
- PostHog version/commit

**Comment by paolodamico** [comment]
Based on #1784 it looks like this was happening before #1841, I'm relieved that we're not breaking new. I'll jump into this ASAP.

**Comment by EDsCODE** [comment]
Any leads?

**Comment by paolodamico** [comment]
@timgl and I tried to reproduce locally without luck, but I do see it happening in prod, will investigate with a different account

**Comment by paolodamico** [comment]
Ok so did some more digging, the bug predates #1755, so fortunately the new version did not break this. Also, the bug only happens on the cloud version (see recording from a freshly deployed self-hosted instance below). As I mentioned before, it also works fine in localhost, so it's hard to fix without being able to replicate. Any ideas maybe @mariusandra ?

![2020-10-23 18 07 58](https://user-images.githubusercontent.com/5864173/97027376-eb120a00-155a-11eb-89bd-dfe568d2ec19.gif)
