### ISSUE TITLE
Add location support

### ISSUE THREAD

**Issue by Voltzz** [PostHog/posthog#191]
**Is your feature request related to a problem? Please describe.**
My home page views don't show city & country

**Describe the solution you'd like**
Show city & country for my home page views

**Describe alternatives you've considered**
Tried not to be a creep but it didn't work, I really want location

**Additional context**
City is important, not just country. But I'm ok with no geo coordinates and terrain mapping.

**Comment by jamesefhawkins** [comment]
Thanks! This is something we want to do for all versions of PostHog.

Todo: find a suitable API integration (or alternative technique) to produce this for low cost. We could enable nice geo-based graphs in the dashboards too.

**Comment by SherinBloemendaal** [comment]
Is this still going to be implemented?

**Comment by jamesefhawkins** [comment]
Yes it is! We're about to release the beta version of Plugins, which in its first phase will let you modify events as they come in... and one of the first example plugins combines event data with geoip data to do exactly this! I'll make sure we tag this issue when they're live.

This is likely to be next week, but I do not want to guarantee it as it's a big piece of functionality :)

**Comment by mariusandra** [comment]
This is now possible in all self hosted posthog instances

https://posthog.com/docs/plugins/maxmind

**Comment by mariusandra** [comment]
This is possible in self-hosted instances and we're working on making this happen for cloud as well, once we enable plugin support there. Closing the issue to trim the list.
