### ISSUE TITLE
Broken responsive nested navigation

### ISSUE THREAD

**Issue by yakkomajuri** [PostHog/posthog#1910]
## Bug description

*Please describe.*  
*If this affects the front-end, screenshots would be of great help.*  

<img width="797" alt="Screenshot 2020-10-16 at 17 37 08" src="https://user-images.githubusercontent.com/38760734/96284969-3e71de80-0fd6-11eb-82d4-46c5480ca2b2.png">

## Expected behavior

Hide the nested menu.

## How to reproduce

1. Visit PostHog and make your screen smaller
2. 
3. 

## Environment

- PostHog cloud or self-managed?
- PostHog version/commit

**Comment by yakkomajuri** [comment]
This now _appears_ fixed for me on `master` although not on app yet.

**Comment by yakkomajuri** [comment]
Wondering though about the tone of the nested sidebar. I remember someone mentioning it should be consistent with the rest of the sidebar. Making it a little darker wouldn't be bad either though.

## Current
<img width="700" alt="Screenshot 2020-10-19 at 13 06 34" src="https://user-images.githubusercontent.com/38760734/96448895-f20fe400-120b-11eb-8a7e-e6ceb608cc4f.png">

## Same as sidebar
<img width="1440" alt="Screenshot 2020-10-19 at 13 02 09" src="https://user-images.githubusercontent.com/38760734/96448991-179ced80-120c-11eb-83c1-10ebfe55400c.png">

## Darker
<img width="1440" alt="Screenshot 2020-10-19 at 13 03 43" src="https://user-images.githubusercontent.com/38760734/96448840-df95aa80-120b-11eb-84d7-8852bbe9131c.png">

I know the sidebar is changing soon (@paolodamico) but this would be a one-line change. Thoughts?

**Comment by Twixes** [comment]
I think it was me, and I'd say the darker version looks pretty good (maybe just slightly less dark?)

**Comment by EDsCODE** [comment]
new menu
