### ISSUE TITLE
Year in Hog but 2023

### ISSUE THREAD

**Issue by pauldambra** [PostHog/posthog#19128]
Some or all of....

- [x] resurrect the hog #19093 
- [x] add a survey badge
- [x] check the badge boundaries make sense for 2023 data
- [x] add a hashtag like #PostHogUnwrapped (everywhere we can some of the platforms are picky)
- [x] validate open graph images are working
- [x] update page title
- [x] link posthog icon back to posthog.com
- [ ] ~~add a value comparison e.g. "you created X flags (that's the top 25%)"~~
- [x] show more stats on the page
- [ ] flourishes and delicacies

keep @joethreepwood aware so we know when to launch/message/email/market and so on

**Comment by joethreepwood** [comment]
@pauldambra Are we still good to turn this on tomorrow, or do you want more time? I think getting it out on Friday/Monday is probably the latest, but it seems like you only have flourishes left to go! 👏 

The only flourish I think we'd definitely want to add is some sort of highlight or colour pop (or something) on the button to help users notice it.

**Comment by joethreepwood** [comment]
Maybe we just actually invert the hog behind the button, so he starts poking out and then hides? I think he's quite slow to pop out anyway, so that if you just go to click the button you may never see him.

**Comment by pauldambra** [comment]
Yep, I'm happy for this go out when you're ready.

I'll see what I can do with the button but that doesn't need to block us IMHO

**Comment by joethreepwood** [comment]
<img width="494" alt="Screenshot 2023-12-12 at 11 59 58" src="https://github.com/PostHog/posthog/assets/84011561/95eb2fba-e58d-43ad-ad9b-ebc8a1b7bf75">

Great, then I've scheduled the emails for tomorrow lunchtime. We'll obviously need the function to be live for users before that, so let me know if you need me to adjust the times? 

Links point to https://app.posthog.com/year_in_posthog/ and https://eu.posthog.com/year_in_posthog/

**Comment by pauldambra** [comment]
Glad you checked that @joethreepwood 

Those links should end 2023. So https://app.posthog.com/year_in_posthog/2023/ and https://eu.posthog.com/year_in_posthog/2023/

Sorry and thank you!
