### ISSUE TITLE
Local Docker Compose deployment doesn't work

### ISSUE THREAD

**Issue by yakkomajuri** [PostHog/posthog#1912]
## Bug description

*Please describe.*  
*If this affects the front-end, screenshots would be of great help.*  

From a contributor, running Docker Compose locally does not load the frontend. Seems like a webpack issue:

![Screenshot from 2020-10-16 17-18-32](https://user-images.githubusercontent.com/38760734/96285490-f2736980-0fd6-11eb-8283-0364c83732bc.png)

## Expected behavior

Deployment should work

## How to reproduce

Follow these instructions for Docker:

https://posthog.com/docs/developing-locally#using-docker

## Environment

- PostHog cloud or self-managed?
- PostHog version/commit

**Comment by thedeveloperr** [comment]
https://posthogusers.slack.com/archives/C019E06QDG8/p1602945443068000
From this slack message a fix is:

Patching `webpack.config.js` worked
```diff
- const webpackDevServerHost = process.env.WEBPACK_HOT_RELOAD_HOST || '127.0.0.1'
+ const webpackDevServerHost = '0.0.0.0'
```

Wait for the webpack build to finish, watch the logs to be sure.

**Comment by mariusandra** [comment]
I think the correct fix would be to set the default host to `0.0.0.0` instead of `127.0.0.1`, leaving the env option there as well

**Comment by thedeveloperr** [comment]
Yes i am testing that fix too. I will update and create a PR

**Comment by thedeveloperr** [comment]
> I think the correct fix would be to set the default host to `0.0.0.0` instead of `127.0.0.1`, leaving the env option there as well

Leaving the env option didn't work. Setting to 0.0.0.0 only worked. I have not created a PR because I am not sure yet what other unrelated repercussion will this have.

**Comment by mariusandra** [comment]
Hey @thedeveloperr hopefully https://github.com/PostHog/posthog/pull/1921 that just got merged will fix this! Feel free to reopen if that's not the case.

[edit: changed to PR 1921, not 1922]

**Comment by adamb70** [comment]
I think `0.0.0.0` is the correct address for the listener, but trying to connect from the browser to `http://0.0.0.0` does not work in Windows. It's a non-routable address so it should return an error, but Linux is kind enough to correct it to point to the loopback address.

I've made PR #2321 which should point the client side to localhost instead of `0.0.0.0`.
