### ISSUE TITLE
Automatically create Actions for events

### ISSUE THREAD

**Issue by timgl** [PostHog/posthog#192]
**Is your feature request related to a problem? Please describe.**

When I send automatic events using `posthog.capture` I then need to go into PostHog and manually create Actions for all of them.

**Describe the solution you'd like**
I want PostHog to automatically create an Action for each automatic event

**Describe alternatives you've considered**
Manually creating all of them.

**Additional context**
There's 2 challenges here:
- **Naming** Is it confusing to users if lots of actions start appearing? Do we need to preface the name of the action with `Event: [their event]` for example?
- **When to create them**: We probably don't want to add 1-2 more database queries to the `capture` endpoint. We'd need to offload this to a cron job, which we haven't done yet.

**Comment by paolodamico** [comment]
We've moved to a different strategy with custom events, I don't think this makes sense anymore, closing.
