### ISSUE TITLE
Surveys: event based targeting

### ISSUE THREAD

**Issue by liyiy** [PostHog/posthog#19209]
## Is your feature request related to a problem?

*Please describe.*

## Describe the solution you'd like

I would like to be able to show a survey based on an event instead of just user properties

## Additional context
 2024 Q1 goal

**Comment by ConnorDoyle** [comment]
+1, have been getting complaints from users about this

**Comment by dreamid27** [comment]
Any update on this ?

**Comment by vhulchenko-iohk** [comment]
Also, would like to know updates on this one.

**Comment by neilkakkar** [comment]
dupe: https://github.com/PostHog/posthog/issues/16681 

This is on our list to prioritise shortly, it should be coming soon :)

**Comment by TiWgnr** [comment]
any update? would love to use this right away

**Comment by 100kristine** [comment]
+1 for this! I am obsessed with surveys, they are very helpful

**Comment by neilkakkar** [comment]
@TiWgnr @100kristine we'll release a beta as soon as next week :) - so you should be getting this very soon

**Comment by lSelectral** [comment]
This would be fire 🔥

**Comment by jeffpoulton** [comment]
This will be huge for us. Can't wait to try it out.

**Comment by tlabetup** [comment]
Any news @neilkakkar ? :)

**Comment by neilkakkar** [comment]
It's out in early beta! :) @Phanatic once you're ready can you add the people here to the beta?^

**Comment by tlabetup** [comment]
Awesome @neilkakkar ! Is it available on both us and eu? :)

**Comment by nityaoberoi** [comment]
hi @neilkakkar @Phanatic - would you please be able to add my account to the beta as well? Thank you!

**Comment by Phanatic** [comment]
Hello everyone, this feature is now released to all Paid plans on PostHog. 
This should allow you to activate surveys based on user sending us events in a browser session. 
You should see a new option "User sends events" in the Targeting section of your survey. 

![image](https://github.com/PostHog/posthog/assets/82819/f2c14d9f-c395-4c99-9874-f5282a50c011)

**Comment by tlabetup** [comment]
That's awesome thanks!!

**Comment by neilkakkar** [comment]
Very shortly (next week) we'll be releasing the feature to delay survey popups, which pairs nicely with this feature :) 

Would love to hear any feedback from everyone on this feature! We're still working on it, and next up will be adding actions and filters on events to targeting as well.

**Comment by andrewchester1** [comment]
@Phanatic I am looking to implement the "User sends events" feature for custom surveys. I am not seeing an option for "User sends events" in the Targeting section of my survey(I'll attach a screen shot). Let me know if I am missing something, thanks for the help
![Screenshot 2024-06-20 162837](https://github.com/PostHog/posthog/assets/49591047/ce9b4aa3-a0af-4a66-b20c-693f07818e7f)
!

**Comment by BrianMacZag** [comment]
I would like to get included in this beta we're a new org that's about to convert to a paid organization. Can someone reach out to me to turn this on for my organization?

**Comment by Phanatic** [comment]
Hi @BrianMacZag this feature is enabled for all paid organizations. Once you convert to paid, this feature should be available to you instantly.

**Comment by andrewchester1** [comment]
> Hi @BrianMacZag this feature is enabled for all paid organizations. Once you convert to paid, this feature should be available to you instantly.

I am on a paid plan, but I am still not seeing this feature

**Comment by andrewchester1** [comment]
> I would like to get included in this beta we're a new org that's about to convert to a paid organization. Can someone reach out to me to turn this on for my organization?

@BrianMacZag Are you on the Paid Plan? I am on a paid plan, but I am still not seeing this feature after 2 weeks. Just wondering if you are having the same issue?

**Comment by lSelectral** [comment]
@BrianMacZag @andrewchester1 
I am on a organization with paid plan and I can see it.
Did you check your organizations billing section?
