### ISSUE TITLE
Screen recording shows white screen

### ISSUE THREAD

**Issue by nosovk** [PostHog/posthog#19319]
## Bug description

*Please describe.*  
We try to add session recording to https://spark.casino/ We added Posthog to GTM and make configuration to write all sessions.
Unfortunately, all visits to main page recorded like white screen:
https://youtu.be/bSPgPqHUbPQ

## How to reproduce

1. Currently, we can reproduce it only at main page of https://spark.casino
2. If session starts from other page - everything shown correctly
3. If user moves from child page to root - video also goes blank

## Environment

- [ ] PostHog Cloud US, project ID: [please provide from https://app.posthog.com/settings/project-details#variables]
- [ ] PostHog Cloud EU, project ID: [please provide from https://eu.posthog.com/settings/project-details#variables]
- [x] PostHog Hobby self-hosted with `docker compose`, version/commit: 1.83.2
- [ ] PostHog self-hosted with Kubernetes (deprecated, see ["Sunsetting Kubernetes support"](https://posthog.com/blog/sunsetting-helm-support-posthog)), version/commit: [please provide]

## Additional context
Recordings from other domains work correctly.

**Comment by o-m-chumak** [comment]
Are there any specific error messages or warnings in the browser console when this issue occurs?

**Comment by nosovk** [comment]
nope, no errors in console :(

**Comment by nosovk** [comment]
https://posthog-cat-second.com/shared/GOrNLbtIij5MWnuCcS5sbiJJ78E-uA

**Comment by nosovk** [comment]
Events are logged, autocapture and links. Only video is missing.

**Comment by joshbmarshall** [comment]
Hi, having the same issue here. On a brand new install (just a few hours ago) on Ubuntu 22.04.3 LTS and latest posthog

**Comment by nosovk** [comment]
I wasn't able to find a solution :( no errors in console or any debug info :(

**Comment by marandaneto** [comment]
cc @daibhin not sure if related to Canvas?

I cannot check this out:

> Due to legal reasons we can't accept players residing in the country you are currently in.

**Comment by daibhin** [comment]
This looks to be an issue specific to the customers self-hosted instance.

There was some chatter among community members about similar issues recently: https://posthog.com/questions/session-recordings-cannot-be-played-back

Given the sizeable changes in the product since this was reported I'm going to close this one out unless any customer comes back saying that this is still an issue for them :)
