### ISSUE TITLE
Surveys: scheduled launch and stop

### ISSUE THREAD

**Issue by liyiy** [PostHog/posthog#19339]
## Describe the solution you'd like

We want to be able to schedule changes to a survey, like we do for feature flags.

**Comment by wouter-leistra** [comment]
Especially the ability to start / stop the survey automatically on a given date would be fantastic!

**Comment by wouter-leistra** [comment]
Second wish is to auto restart, our goal would be to have a monthly pulse where the same question is asked monthly. And to track the satisfaction (NPS) per month to see  if things improve or decline. Now it needs to be done manually to recreate a survey and start it on the first of the month, stop it on the last of the month, create new same survey and start it, etc... It is very tedious and I don't like to work on January 1st... 😅

**Comment by marandaneto** [comment]
You can do this with https://posthog.com/docs/surveys/creating-surveys#completion-conditions "Repeat on a schedule"
