### ISSUE TITLE
Weekly report email flood 

### ISSUE THREAD

**Issue by FUSAKLA** [PostHog/posthog#1935]
## Bug description
Hi, I upgraded to 1.15.0 version and experienced flood of weekly report emails cca 140 emails in 2 hours.

## Expected behavior
Get the report once a week

## How to reproduce

1. 10:00 - Upgraded from 0.14.0 to 0.15.0
2. 17:00 - PostHog starts to generate celery tasks for weekly report.
3. 18:00 - Rollback to previous version and cleanup the queue.

## Environment
- Upgrade from 0.14.0 to 0.15.0
- self-managed in kubernetes

## Additional context

Interesting fact is that PH started to create the Celery tasks for weekly report  exactly in `17:00` (`15:00 UTC`).
Not a single one before that time.

![image](https://user-images.githubusercontent.com/6112562/96477657-0fa67300-1237-11eb-991f-4c9e8f4afddc.png)

**Comment by paolodamico** [comment]
Thanks for reporting! We've temporarily disabled these emails with #1934 while we work on a permanent fix. We'll also release a minor version with this change. Apologies for the inconvenience.

**Comment by paolodamico** [comment]
Hi @FUSAKLA this issue is now fixed with #1954, thanks for the patience.

**Comment by FUSAKLA** [comment]
Great, thanks for the quick fix! :+1: :tada:
