### ISSUE TITLE
app -> us migration buglist

### ISSUE THREAD

**Issue by timgl** [PostHog/posthog#19379]
- [x] Sharing insights still uses app.posthog.com
- [x] SITE_URL is still set to app.posthog.com, but not 100% sure what would happen if we change that
- [x] Login with gitlab is broken - I'm not sure which account owns the gitlab application
- [x] Fix regexes in the app that check for things like `(app|eu).posthog.com` (docs side panel for example)

**Comment by MarconLP** [comment]
subscription warning https://posthoghelp.zendesk.com/agent/tickets/8407 (moved to PostHog: https://us.posthog.com/project/2/support/tickets/11078)
