### ISSUE TITLE
Posthog events not being shown after upgrading posthog-node

### ISSUE THREAD

**Issue by hassan-pullflow** [PostHog/posthog#19374]
## Bug description

I recently updated my `posthog-node` version from `1.3.0` to `3.1.3`. I was seeing events on posthog project with `1.3.0 version` but after upgrading it i am not seeing in any events. What can be wrong ? 

## How to reproduce

1. Create project on posthog 
2. install posthog-node version 1.3.0
3. post events > events are shown
4. upgrade to latest version > events are not shown

**Comment by benjackwhite** [comment]
Could you submit an in-app support request instead? With specific configuration, thats typically the fastest way for us to support you.

In the meantime, worth using `posthog.debug()` to see if there are any warnings and re-checking https://posthog.com/docs/libraries/node to see if there is anything obvious that might have changed with your setup.
