### ISSUE TITLE
Improve processing for weekly email report

### ISSUE THREAD

**Issue by paolodamico** [PostHog/posthog#1938]
## Is your feature request related to a problem?

The weekly email report may require a long running async task on large events volumes, which can cause workers to get clogged up.

## Describe the solution you'd like

We should include a version of the report generated with CH queries (if CH is available) to speed up processing and reduce resources consumption.

## Describe alternatives you've considered
Only use Postgres.

**Comment by Twixes** [comment]
Is this still an issue? @paolodamico

**Comment by paolodamico** [comment]
It is still an issue. Not sure when we'll prioritize it, but when we do we'll have to address what's documented here.

**Comment by paolodamico** [comment]
We no longer have a weekly email report.
