### ISSUE TITLE
Improve celery logging

### ISSUE THREAD

**Issue by paolodamico** [PostHog/posthog#1940]
## Is your feature request related to a problem?

Related to the weekly email issue from Oct 19, we need more comprehensive logging to understand what's going on with async tasks.

## Describe the solution you'd like

Add more verbosity to celery logs (including task processing time) + implement an easy and scalable way of consuming and searching through logs for the cloud version.

## Describe alternatives you've considered
Piece stuff together with Grafana.

**Comment by Twixes** [comment]
Is this still relevant @paolodamico?

**Comment by paolodamico** [comment]
Well I still think we need something like LogDNA or Splunk, something we can query easily and quickly, but think we can close for now as at least we have CloudWatch. CC @fuziontech
