### ISSUE TITLE
Surveys: randomize the order of multiple choice answers

### ISSUE THREAD

**Issue by jurajmajerik** [PostHog/posthog#19404]
## Is your feature request related to a problem?
From a user:
> In surveys, add the ability to randomize the order of multiple choice answers. Often times users click the first option which can skew the results.

## Additional context
Internal ticket: https://posthoghelp.zendesk.com/agent/tickets/8431

**Comment by Phanatic** [comment]
Fixed in https://github.com/PostHog/posthog-js/pull/1177
