### ISSUE TITLE
cant access data in tooltip on insight graphs for actions with long names

### ISSUE THREAD

**Issue by susanev** [PostHog/posthog#19460]
hi folks, theres a horizontal scroll bar on these tool tips but i cant get to it to scroll because if i move my mouse it moves to another data point, is there anyway to cut off the end of the action name, and still be able to see the data?

<img width="556" alt="Screenshot 2023-12-20 at 8 59 20 AM" src="https://github.com/PostHog/posthog/assets/5489125/c1324502-26a7-4e90-a1b2-d8951936e433">

thx for considering!!

**Comment by MarconLP** [comment]
closing in favor of this bug report https://github.com/PostHog/posthog/issues/19555
