### ISSUE TITLE
Have separate workers/queue for event ingestion

### ISSUE THREAD

**Issue by macobo** [PostHog/posthog#1949]
## Is your feature request related to a problem?

During https://github.com/PostHog/post-mortem/pull/2, one issue raised was that slow-running jobs can slow down data ingestion, leading to data latency and other problems.

## Describe the solution you'd like

We could run specialized workers (or a separate queue) for event ingestion, and limit the amount of "other" jobs that run in parallel.

## Describe alternatives you've considered

Not make mistakes or have tasks that can fail in spooky ways. 

## Additional context

Note we might be expanding our use of cronjobs in the future: with session recording + plugins(?) also using them.

Also note that we still be bottlenecked by bad jobs with this if they lock up the DB, but it also gives us a good operational knob to turn as issues arise.

**Comment by macobo** [comment]
Relevant documentation: https://docs.celeryproject.org/en/latest/userguide/routing.html#id2

The hardest thing here isn't updating the code but rather updating our deployment(s) in a way where from N workers only a small subset worked on non-ingestion (default) queue.

Also worth mentioning that #1846 will introduce some additional tasks that will be put in the queue - we don't want that blocking our ingestion.

@fuziontech Thoughts? If you're behind me on this, I'll push for it next release.

**Comment by Twixes** [comment]
We've got a definitely specialized plugin/ingestion server now, which does just this. :)
