### ISSUE TITLE
"Invited undefined new team members"

### ISSUE THREAD

**Issue by corywatilo** [PostHog/posthog#19505]
If you don't invite team members, it appears to successfully invite undefined team members

<img width="510" alt="image" src="https://github.com/PostHog/posthog/assets/154479/964a471b-c35a-4af6-8d09-237d527cdd17">

**Comment by corywatilo** [comment]
This toast also doesn't work in dark mode:

<img width="561" alt="image" src="https://github.com/PostHog/posthog/assets/154479/ab626811-c50e-4ef0-ae9c-8621e42dc559">

**Comment by MikeBellika** [comment]
First issue seems fixed by #19954

**Comment by raquelmsmith** [comment]
I just fixed this in https://github.com/PostHog/posthog/pull/19954 (the invite thing, not the dark mode thing)

**Comment by raquelmsmith** [comment]
Oh wait, I fixed it for onboarding, but @corywatilo was this happening outside onboarding?
