### ISSUE TITLE
Hide dashboard dropdown if dashboard count = 0

### ISSUE THREAD

**Issue by corywatilo** [PostHog/posthog#19519]
Dropdown is empty

<img width="753" alt="image" src="https://github.com/PostHog/posthog/assets/154479/c30e1afc-b441-400a-b9e7-b9ee1ec9761e">

**Comment by baristaGeek** [comment]
I'm adding this as a first contribution :) Hope it looks well https://github.com/PostHog/posthog/pull/19530

**Comment by Twixes** [comment]
Solved 👆
