### ISSUE TITLE
Surveys with branching logic

### ISSUE THREAD

**Issue by liyiy** [PostHog/posthog#19516]
## Is your feature request related to a problem?

*Please describe.*

## Describe the solution you'd like

I want to conditionally show parts of my survey depending on the answer that the user selects

**Comment by PrebenAas** [comment]
+1 on this! Working with a survey now, and I want to ask different questions based on answers given.

**Comment by samsklar11** [comment]
+1 on this!

**Comment by jurajmajerik** [comment]
Hey all, this feature is almost ready to go! If you'd like to be among the first ones to test it, please send me an email at juraj (at) posthog com and I'll roll it out for you :)

**Comment by jurajmajerik** [comment]
This has been released! Documentation here: https://posthog.com/docs/surveys/conditional-questions
