### ISSUE TITLE
Retention insight: Show the average retention for each period

### ISSUE THREAD

**Issue by MarconLP** [PostHog/posthog#19543]
## Describe the solution you'd like

Show the average retention for each period:
![2023-12-29 at 08 15 44@2x](https://github.com/PostHog/posthog/assets/13001502/357ad261-c356-4692-9a74-55883bb6ecbf)

## Additional context

https://posthoghelp.zendesk.com/agent/tickets/8690

**Comment by MarconLP** [comment]
+1 https://posthoghelp.zendesk.com/agent/tickets/9105 (moved to PostHog: https://us.posthog.com/project/2/support/tickets/11532)

**Comment by MarconLP** [comment]
+1 https://posthoghelp.zendesk.com/agent/tickets/10494 (moved to PostHog: https://us.posthog.com/project/2/support/tickets/14956)

**Comment by webjunkie** [comment]
Fixed in #19543
