### ISSUE TITLE
posthog.identify does not add attributes

### ISSUE THREAD

**Issue by macobo** [PostHog/posthog#1955]
## Bug description

It seems posthog.identify call is doing nothing on cloud.

## Expected behavior

posthog.identify should update user properties, as per https://posthog.com/docs/integrations/js-integration/

## How to reproduce

1. Go to app.posthog.com, log in
2. Find your person
3. Call `posthog.identify(posthog.get_distinct_id(), { tester: 'attribute' })` and refresh
4. Refresh, see attribute does not show up
5. Call `posthog.people.set({ hello: 'world2' })` 
6. Refresh, see this does save the attribute

## Environment

- PostHog cloud

## Additional context

This started with me investigating why feature flag was not turned on for me => why am I not in cohort => why does my person listing not have an email attribute.

Saw the same behavior locally on master with posthog-js downgraded to 1.5.0.

**Comment by macobo** [comment]
## Debugging 

So looking at `posthog.js` code ([link](https://github.com/PostHog/posthog-js/blob/b2618295d3ae679f91fbfab3eff514141fd90d5d/src/posthog-core.js#L1004-L1048)) for `.identify` it seems adding user properties functionality does not really exist.

We're however using it incorrectly inside our own codebase: https://github.com/PostHog/posthog/blob/f8788287dbb2f74950e71707c24ab58982998b7e/frontend/src/scenes/userLogic.tsx#L98-L100

It seems our documentation at least is correct - neither posthog.js docs nor https://posthog.com/docs/integrations/js-integration#identifying-users mention this capability. 

## Moving forward

I'll fix the bug in our code ASAP.

Since other analytics.js libraries **do not** support passing user properties as part of identify, I think it is not worth adding this as a feature either.

**Comment by mariusandra** [comment]
This *might* be happening in other client libraries. Worth a check.

**Comment by macobo** [comment]
Good idea. 

All other client libraries support setting properties as part of identify calls (though with varying signatures):

- Posthog-IOS allows `properties` as part of `.identify` call: https://github.com/PostHog/posthog-ios/blob/eef50f23c637102f28b4383500388c300129c4c5/PostHog/Classes/PHGPostHog.m#L207-L220
- Posthog-Android allows `properties`: https://github.com/PostHog/posthog-android/blob/2397a4e329ac3da57c75c172fce5ca1c4b3ecaf4/posthog/src/main/java/com/posthog/android/PostHog.java#L324-L393
- Posthog-go allows `properties`: https://github.com/PostHog/posthog-go/blob/0231121f2553045aedc825865b3d0dcc38330417/cmd/cli/main.go#L83-L88
- posthog-node allows `properties`: https://github.com/PostHog/posthog-node/blob/3b786158d3c2bad2a6e6819d87202ea59fba9f03/test.js#L283-L294
- posthog-php seems to allow `properties`: https://github.com/PostHog/posthog-php/blob/6929a7dc392b592441b245a49df57e7133e28caa/bin/posthog#L39-L44
- posthog-python allows `properties`: https://github.com/PostHog/posthog-python/blob/98d2d4cc05234d6d6b3be49c1fb525722035db92/posthog/client.py#L82-L98
- posthog-flutter allows `properties`: https://github.com/PostHog/posthog-flutter/blob/a4343c75c85c0b51fee6b763b8f5d3cffba7bfa7/lib/src/posthog.dart#L20-L30
- posthog-react-native allows `properties`: https://github.com/PostHog/posthog-react-native/blob/f13d82fcfc0eaad88fa1bdcb43d3a51cfc9afa76/core/src/posthog.ts#L229-L240
- posthog-ruby seems to allow `properties`: https://github.com/PostHog/posthog-ruby/blob/a4966242a39aa51d25fbeeaa04f37d60bb95b9d8/lib/posthog/client.rb#L63-L72

Since case I think we should make posthog-js compatible with our other libraries. :) Will open another ticket over at posthog-js and close this once PR gets merged.

One additional bit of complexity: posthog.js exposes two callback arguments, not sure whether they are used.

**Comment by Twixes** [comment]
Should be fixed with PostHog/posthog-js#105.
