### ISSUE TITLE
Feature preview sidepanel doesn't function on on-premise installations

### ISSUE THREAD

**Issue by clrxbl** [PostHog/posthog#19566]
## Bug description

The feature preview sidepanel in the new Posthog UI doesn't seem to function on on-premise installations.

## How to reproduce

1. Open the Feature Previews panel in the side panel
2. Try to enable or disable any feature preview
3. The slider won't change, refreshing it shows that the feature preview is still on the same position.

## Environment

- [ ] PostHog Cloud US, project ID: [please provide from https://app.posthog.com/settings/project-details#variables]
- [ ] PostHog Cloud EU, project ID: [please provide from https://eu.posthog.com/settings/project-details#variables]
- [x] PostHog Hobby self-hosted with `docker compose`, version/commit: https://github.com/PostHog/posthog/commit/a5599561d71d86dd84f78ea9ced060360bb27473
- [ ] PostHog self-hosted with Kubernetes (deprecated, see ["Sunsetting Kubernetes support"](https://posthog.com/blog/sunsetting-helm-support-posthog)), version/commit: [please provide]

## Additional context

Looking at Chrome Dev Tools' Network tab, it seems to be doing a request to app.posthog.com/decide even though I'm self-hosting Posthog. Perhaps this is the issue?

**Comment by benjackwhite** [comment]
I think it might not be possible to support due to some reliance on the cloud product. Could you share any screenshots / console logs you're getting.

Realistically I don't see this getting fixed as the intended use case isn't really self-hosted here.

**Comment by clrxbl** [comment]
> I think it might not be possible to support due to some reliance on the cloud product. Could you share any screenshots / console logs you're getting.
> 
> Realistically I don't see this getting fixed as the intended use case isn't really self-hosted here.

Made a recording to show what's happening
https://github.com/PostHog/posthog/assets/28601081/95ab3278-5063-4fac-98eb-11f0c0786ece

It's making a web request to the following everytime I try to enable a feature preview flag.
![CleanShot 2024-01-02 at 19 16 04@2x](https://github.com/PostHog/posthog/assets/28601081/ff08d7f3-6d61-4978-a895-c11ff7c5a88b)

**Comment by clrxbl** [comment]
Perhaps a workaround would be an environment variable to enable feature flags instance-wide?

**Comment by neilkakkar** [comment]
Indeed, you can add the 'persisted feature flag' setting to enable feature previews on self-hosted instances. The UI setting works just for cloud 👍

**Comment by clrxbl** [comment]
> Indeed, you can add the 'persisted feature flag' setting to enable feature previews on self-hosted instances. The UI setting works just for cloud 👍

Where is this / how can I do so? Not sure if this is documented anywhere since the documentation for self-hosted instances is lacking here and there.

**Comment by neilkakkar** [comment]
My bad! It's an environment variable you can set: https://github.com/PostHog/posthog/blob/master/posthog/settings/feature_flags.py#L7 - PERSISTED_FEATURE_FLAGS is the name
