### ISSUE TITLE
Data export encoding bug

### ISSUE THREAD

**Issue by liyiy** [PostHog/posthog#19580]
## Bug description

*Please describe.*  
*If this affects the front-end, screenshots would be of great help.*  

A user is having trouble exporting survey response data that's in another language besides English to excel. It works in google sheets though.

*If you are on PostHog Cloud it would be really valuable if you can share any links where the problem occurs. This speeds up our ability to troubleshoot tremendously.* 

## How to reproduce

1.
2.
3.

## Environment

- [ ] PostHog Cloud US, project ID: [please provide from https://app.posthog.com/settings/project-details#variables]
- [ ] PostHog Cloud EU, project ID: [please provide from https://eu.posthog.com/settings/project-details#variables]
- [ ] PostHog Hobby self-hosted with `docker compose`, version/commit: [please provide]
- [ ] PostHog self-hosted with Kubernetes (deprecated, see ["Sunsetting Kubernetes support"](https://posthog.com/blog/sunsetting-helm-support-posthog)), version/commit: [please provide]

**Comment by nykolaslima** [comment]
Hello @liyiy , I tested the search with accented texts and also in Chinese, and the data exported via CSV maintained the correct encoding and were displayed correctly. Can you provide more details on how to reproduce this problem?

**Comment by liyiy** [comment]
> Hello @liyiy , I tested the search with accented texts and also in Chinese, and the data exported via CSV maintained the correct encoding and were displayed correctly. Can you provide more details on how to reproduce this problem?

Hey Nykolas! The CSV seems to open correctly in google sheets and some applications, but not excel. Does it open correctly for you there? It could also be a surveys response specific problem, so I would replicate by setting up a survey and then submitting survey responses in other languages and exporting the results data there.

**Comment by nykolaslima** [comment]
I was able to reproduce it @liyiy 

Will open a PR with the fix :)
