### ISSUE TITLE
[Bug] Release size is not calculated anymore after a rollout condition has been saved

### ISSUE THREAD

**Issue by annikaschmid** [PostHog/posthog#19581]
This is applicable to both surveys and flags.

When I first set up a rollout condition %, PostHog calculates the user size for me.

Once I save the flag/survey and make changes to the % afterwards, it only shows me the %, and doesn't calculate the number anymore (see screenshots).

It would be hugely beneficial if the number would still be calculated.

<img width="1309" alt="Screenshot 2024-01-03 at 18 59 01" src="https://github.com/PostHog/posthog/assets/14750837/86c3571b-de97-4d5f-bacb-fb251f671b1d">

<img width="1309" alt="Screenshot 2024-01-03 at 18 56 59" src="https://github.com/PostHog/posthog/assets/14750837/31a11a73-1ce4-49fd-a3bd-24c671eb7141">

Related: https://github.com/PostHog/posthog/issues/18181

**Comment by Phanatic** [comment]
Can't reproduce anymore, please reopen if you see this behavior again.
