### ISSUE TITLE
Rating Survey crashes client-side when using emoji display type

### ISSUE THREAD

**Issue by niclas-g** [PostHog/posthog#19592]
## Bug description

Rating Survey crashes client-side when using emoji display type.
If I switch to display type: Number it works as expected.

![Screenshot 2024-01-04 at 11 18 23](https://github.com/PostHog/posthog/assets/45293037/204ec41b-ecdc-4d70-90b8-add4bfb89a7e)

*If you are on PostHog Cloud it would be really valuable if you can share any links where the problem occurs. This speeds up our ability to troubleshoot tremendously.* 

## How to reproduce

Each time the survey is be rendered,  it crashes. 

## Environment

- [X] PostHog Cloud EU, project ID: 12097

## Additional context

posthog-js 1.96.1

I'm using a CSS selector to trigger the survey: ".demo-exit-survey"

**Comment by niclas-g** [comment]
Ah, I think I've figured it out. 
In the Posthog dashboard, you don't reset the Scale input when switching Display Types, leading to invalid configuration being saved and used in the client-side code. 
When going from Emoji to Number it doesn't crash the JS (but still leads to unexpected behaviour).
![Screenshot 2024-01-04 at 11 52 23](https://github.com/PostHog/posthog/assets/45293037/37d546a6-83fb-45eb-9ba7-ccfc448962b7)
![Screenshot 2024-01-04 at 11 54 47](https://github.com/PostHog/posthog/assets/45293037/ec910349-5292-49d2-bc94-f2845059ac18)
![Screenshot 2024-01-04 at 11 58 07](https://github.com/PostHog/posthog/assets/45293037/891c6829-16ff-4cc2-a887-5fe2dcd019f5)

**Comment by liyiy** [comment]
Hey @niclas-g, thanks for the bug report! This should be fixed soon ^
