### ISSUE TITLE
Rewrite the Funnels Insight in HogQL

### ISSUE THREAD

**Issue by mariusandra** [PostHog/posthog#19638]
## Is your feature request related to a problem?

This is part of the push to [rewrite all insights in HogQL](https://github.com/PostHog/meta/issues/130). I've created separate issues for each insight type, so that users can subscribe here and get notified when it's done.

This issue is about the **Funnels** insight.

## Describe the solution you'd like

I'd like to rewrite the Funnels Insight in HogQL.

- Most product analytics insights are built in a bespoke way in our "legacy" Python codebase. This code produces ClickHouse SQL as its output. It's hard to extend, as every new feature (e.g. group support, multiple breakdowns) needs to be manually added to each insight. It's hard to extend the current system, and there are many bugs and unimplemented edge case features.

- We've built HogQL, which takes care of implementation details, and lets users focus on writing queries. Every platform feature added to HogQL (e.g. group support, new aggregations, etc) will automatically be available in every insight everywhere.

- We're now rewriting our python codebase to output HogQL instead of ClickHouse SQL. This will fix whole classes of bugs, make the system more robust, and allow the end user to directly modify the generated HogQL SQL for further analysis.

- This migration is also a blocker for the removal of a lot of legacy frontend code, which is often causing bugs.

## Additional context

See the latest todo list in the megaissue: https://github.com/PostHog/meta/issues/130

**Comment by GalDayan** [comment]
Looking forward!

**Comment by mariusandra** [comment]
Noting down a [request](https://posthoghelp.zendesk.com/agent/tickets/9173) for a new feature: ability to configure multiple events/steps per step, and see which one triggered. You can already do the configuration with a HogQL expression, but you won't see which clause converted.

**Comment by mariusandra** [comment]
Bug in the current implementation: more than one "all events" after a custom event results in 100% dropoff on the second one.

<img width="1485" alt="image" src="https://github.com/PostHog/posthog/assets/53387/04fea368-147d-42fa-88a3-8ac1635ea212">

**Comment by thmsobrmlr** [comment]
Customer request for follow up: https://github.com/PostHog/posthog/issues/14008

**Comment by mariusandra** [comment]
Closing this since HogQL funnels have launched. Tracking feature requests: https://github.com/PostHog/meta/issues/200
