### ISSUE TITLE
Feature Request: Session replay templates

### ISSUE THREAD

**Issue by joethreepwood** [PostHog/posthog#19680]
One of [my goals this quarter](https://github.com/PostHog/meta/issues/171) is basically to make it easier for users to get started. I've created some best practices to help with that, one of which involves creating template functionality for each product. 

You may be asking: Why does replays need templates?

## Why does replays need templates?

Session replays has perhaps the most busy UI of all our products. Giving users a quick way to access some common queries as templates would help us demonstrate the value of the feature more quickly, and give us something we can link directly to in content. 

No other replay tools I've seen include a template functionality, so this would also be a competitive differentiation. We're open source too, so this is something users could build on and add to. 

Finally, if we have templates working across _all_ features then we potentially become able to link them together in such a way as to make PostHog support many different metric frameworks at once. 

You're probaby thinking: would templates for session replays look like? Glad you asked. 

## What would replay templates look like?

One proposal for replay templates is to create some default playlists for users which are pinned to the top of their playlist list from the start. These would be common playlists which enable them to effortlessly jump straight to things we imagine they'd want to check. 

Initial template proposals:

- Recent sign-ups (users who complete a sign-up event in the last 14 days)
- Recent unsubscribes (users who complete a delete my account event in the last 14 days)
- Rageclicks (users who rageclick in the last 30 days)
- Errors (users who have experienced any `console.error` in their console logs in the last 14 days)
- Beta users (users in a designated beta cohort)

In order to collect the right event there seem to be two possible solutions: 

1. Implement field mapping elsewhere in the product - https://github.com/PostHog/posthog/issues/12021
2. Implement a designation wizard when a template is first clicked, similar to the dashboard template wizard

<img width="975" alt="Screenshot 2024-01-09 at 16 17 53" src="https://github.com/PostHog/posthog/assets/84011561/901a389c-8731-45db-b843-f3fc7c974c42">

## Alternatives and feedback
Both are welcome from @PostHog/team-replay

**Comment by joethreepwood** [comment]
Example of one way this could be useful: We could encourage activation by linking directly to these templates from the onboarding emails. A one-click way to immediately show people rageclickers and new user replays.

**Comment by daibhin** [comment]
One thing to call out here is that we specifically haven't worked on playlists as a team for a short while. At their core playlists are just a collection of saved filters with the added functionality of being able to pin certain recordings. We are curious to learn whether people can replace the "saving" functionality of pinning by adding individual recordings to Notebooks.

The idea of having named queries exactly like you're proposing is something we certainly need to improve for people. The simple filters was the first attempt at making it easier for people to find the sessions they want, I think the next chunk of work will be in helping people find the valuable sessions.

**Comment by joethreepwood** [comment]
Done, by Raquel
