### ISSUE TITLE
Website doesn't load when ProtonVPN. DNS problem

### ISSUE THREAD

**Issue by guillempuche** [PostHog/posthog#19711]
## Bug description

I'm not a user of PostHog. I'm just checking your marketing page.

Brave browser screenshoots:
<img width="1024" alt="imatge" src="https://github.com/PostHog/posthog/assets/3519924/8ce1f760-ecec-4619-afea-d3c8b1f66a3c">

<img width="416" alt="imatge" src="https://github.com/PostHog/posthog/assets/3519924/2ae13207-880a-45e6-9581-5d166be3cdc5">

It's works on my Android phone (it also uses ProtonVPN).

## How to reproduce

1. Connect ProtonVPN https://protonvpn.com/
2. Open http://posthog.com/ in your Macos
3. You see the DNS error

## Environment

- macos 14
- ProtonVPN 4.1.1
- tested on Firefox 121 and Brave 1.61.101 browsers

## Additiona info

Mixpanel marketing website also has a similar error with CDN
<img width="514" alt="imatge" src="https://github.com/PostHog/posthog/assets/3519924/ce19df69-503e-4f21-874a-8894c2d44b86">

```
GET /marketing-site/static/_next/static/chunks/webpack-444ea910bc19d30e.js undefined
Host: cdn.mxpnl.com
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:121.0) Gecko/20100101 Firefox/121.0
Accept: */*
Accept-Language: ca,es-ES;q=0.8,en-US;q=0.5,en;q=0.3
Accept-Encoding: gzip, deflate, br
DNT: 1
Connection: keep-alive
Referer: https://mixpanel.com/
Sec-Fetch-Dest: script
Sec-Fetch-Mode: no-cors
Sec-Fetch-Site: cross-site
```

**Comment by pauldambra** [comment]
Hey @guillempuche that sounds like Brave is blocking posthog.com. Is it possible to check if allow-listing posthog in Brave fixes this for you?

**Comment by guillempuche** [comment]
@pauldambra, I cannot do it on Firefox. Brave has a lot of block features, I don't want to mess around.

I've tried this https://support.mozilla.org/en-US/kb/enhanced-tracking-protection-firefox-desktop on Firefox. There's still the error:
<img width="603" alt="imatge" src="https://github.com/PostHog/posthog/assets/3519924/4510b448-27e4-4d73-9812-8b5b7f565e12">

When I disconnect my VPN, it works.

**Comment by pauldambra** [comment]
Strange that it works on Android with proton but not on Desktop 🤯 

Sounds like the Proton VPN ad blocker functionality is blocking *.posthog.com and not just our ingestion routes. 

Is it possible you have "netshield" active on desktop and not on mobile? https://protonvpn.com/support/netshield/

(thanks for helping me track down the source of this! 🙏)

**Comment by guillempuche** [comment]
You're fast @pauldambra 😎

You're right, the problem was Netshield. All the levels:

- Don’t block. This means that NetShield is not active.
- Block malware only. This prevents your browser from loading resources from domains that host malware, spyware, or other malicious software.
- Block malware, ads, & trackers. This blocks ads and the online trackers that adtech companies use to target you, in addition to blocking malware. This advanced level of protection is on by default when you first enable NetShield.


"Block malware only" works:

![imatge](https://github.com/PostHog/posthog/assets/3519924/213bb1d7-3b9c-4664-b911-a6e3a8b13310)

**Comment by pauldambra** [comment]
I've sent a support request to proton VPN as well. Would be cool for people to have blocking active if they want to but still visit our site :)

**Comment by guillempuche** [comment]
Cool @pauldambra.

Some websites have problems with very restrictive privacy features, easy to check with you, PostHog, and Mixpanel.

ProtonVPN and browsers (Firefox, https://support.mozilla.org/en-US/kb/enhanced-tracking-protection-firefox-desktop). Most issues come from my VPN.
