### ISSUE TITLE
Global `Hide PostHog properties` setting

### ISSUE THREAD

**Issue by MarconLP** [PostHog/posthog#19844]
## Is your feature request related to a problem?

Currently, you need to enable the `Hide PostHog properties` option for every 

## Describe the solution you'd like

A global option to enable the `Hide PostHog properties` setting everywhere.

## Additional context

https://posthoghelp.zendesk.com/agent/tickets/9495

**Comment by benjackwhite** [comment]
Do we think this would suffice as a browser-side saved setting 🤔

**Comment by MarconLP** [comment]
> Do we think this would suffice as a browser-side saved setting 🤔

Yeah, definitely. Doing it once per device shouldn't be too tiresome.

**Comment by mirkea** [comment]
Even if it wouldn't be a global setting, it could be one per view, such as this one
https://drive.google.com/uc?id=12_s7gDrXyWFULk_ShFlQ3X4IcqUHTnq8
