### ISSUE TITLE
Bug: possible to edit a deleted feature flag

### ISSUE THREAD

**Issue by jurajmajerik** [PostHog/posthog#19857]
## Is your feature request related to a problem?
From a user: 
> When trying to restore a deleted feature flag by going into history -> edit feature flag -> save, a toast states that the feature flag has been saved, and it is shown in the feature flag list. But when I try to refresh the feature flag disappears.

The flag appears in the list because of the optimistic UI update.

## Describe the solution you'd like
We should either:
- Add the ability to archive/unarchive flags like we do with Experiments
- Disallow editing a deleted flag - currently can be done via History or even by passing the flag id into the edit flag url

## Additional context
Internal ticket: https://posthoghelp.zendesk.com/agent/tickets/9486

**Comment by neilkakkar** [comment]
hmm, maybe something has changed around this flow, this was the undocumented way to revive dead feature flags till we get a more formal way, so it actually used to set deleted=False when you saved a deleted one. 🤔
