### ISSUE TITLE
Feature flags no longer supporting a decimal percentage in roll out

### ISSUE THREAD

**Issue by lharries** [PostHog/posthog#19888]
## Bug description

We have a large number of users and use a feature flag to control a rollout of session recordings for a small percentage. Recently, the functionality seems to have regressed and the roll outs seem to require an integer number. E.g. it won't allow a roll out to 0.2% of users

![Screenshot enable-session-recording • Feature Flags • PostHog (Google Chrome) 2024-01-21 at 14 19@2x](https://github.com/PostHog/posthog/assets/22766134/3ded8d29-1123-4d1f-96d0-9711fe07da15)

## How to reproduce

1. Create a feature flag and set the roll out percentage to 0.2% in Chrome, it won't allow you

## Environment

- [x] PostHog Cloud EU, project ID: 11870

Thanks! cc @neilkakkar :)

**Comment by neilkakkar** [comment]
Thanks for flagging @lharries , seems like a regression by removing antd, will investigate & fix 👍
