### ISSUE TITLE
Cohorts - AND + improved date selection

### ISSUE THREAD

**Issue by jamesefhawkins** [PostHog/posthog#199]
**Is your feature request related to a problem? Please describe.**
I want to be able to work out which users are coming back.

This means they signed up, then on a different day they ran an action.

**Describe the solution you'd like**
1) In cohorts, we can use OR statements by adding "new groups".

If we could also use AND statements, it would mean I could create a cohort like "User has done 'sign up' from the 1st of February to yesteday, and has done 'visit URL'  today"

2) we would also need to be able to select the date range (not just "in the last X...") to make this possible
 
**Describe alternatives you've considered**
This currently isn't possible through the UI.

The alternative solution would be to focus more on a retention table, but just a basic list of all the raw user data first feels like the right place to start.

**Comment by timgl** [comment]
Can you explain the date range?

In my mind, we could do
- User has action 'sign up' in the last 30 days AND
- User has action 'visit URL' in the last day

The problem with a fixed date range is it is fixed, so you will only ever be tracking users in February, which doesn't seem that useful? I am most likely missing something as Mixpanel also has this feature.

**Comment by jamesefhawkins** [comment]
"In my mind, we could do

User has action 'sign up' in the last 30 days AND
User has action 'visit URL' in the last day"

The challenge with that would be it'd include people who signed up today who obviously also will have visited the url today, so it no longer is a list of returning users.

If we could exclude timeframes (either choosing fixed between dates X and Y (ie "we put feature X into the product on the 9th March, what is the list of people that have signed up since then), or rolling via NOT statements ie "signed up within the last 30 days but NOT within the last day AND visited today", there'd be quite a lot more flexibility for these sorts of questions.

If this is hideously painful to do, it's questionable if we should prioritize it - but I imagine this might be quite straightforward technically and would help improve the cohorts quite significantly.

**Comment by jamesefhawkins** [comment]
Happy to draw an example of how the selection could look - this feels relatively simple in my head but hard to explain

**Comment by timgl** [comment]
That makes sense and technically not very hard in fairness. Yes sketch would be useful!

**Comment by jamesefhawkins** [comment]
No prob. I've self-assigned this and will return it to you when I get to it.

**Comment by Tannergoods** [comment]
Adding this or even fuller Boolean logic including NOT (although this can be mitigated by an AND statement that "does not equal" so might not be necessary) is necessary for full Cohort analysis parity.

For date selection this should allow for date ranges other than day, week or month but allow you to select a date range.

We also are only counting currently for "anytime" a user has performed and action (as well as having a property) to get true parity we also need to be able to select "most recently"  in the instance values change often.

**Comment by paolodamico** [comment]
`AND` logic superseded by #1777.

**Comment by paolodamico** [comment]
Date issue is now addressed with #4349, closing this.
