### ISSUE TITLE
UI nit: Spacing on the support modal seems off

### ISSUE THREAD

**Issue by joethreepwood** [PostHog/posthog#19919]
## Bug description

<img width="507" alt="Screenshot 2024-01-23 at 11 29 01" src="https://github.com/PostHog/posthog/assets/84011561/15157320-adc4-4a0b-960d-a80a608540a2">

Maybe it's just me, but the spacing on the new security definitions link seems a bit off. It's closer to the drop down than the example on the field following it. 

Also feel like it's a bit redundant and could just be a (?) tooltip on the field title, but that's a subjective thing. 

## How to reproduce

1.
2.
3.

## Environment

- [ ] PostHog Cloud US, project ID: [please provide from https://app.posthog.com/settings/project-details#variables]
- [ ] PostHog Cloud EU, project ID: [please provide from https://eu.posthog.com/settings/project-details#variables]
- [ ] PostHog Hobby self-hosted with `docker compose`, version/commit: [please provide]
- [ ] PostHog self-hosted with Kubernetes (deprecated, see ["Sunsetting Kubernetes support"](https://posthog.com/blog/sunsetting-helm-support-posthog)), version/commit: [please provide]

**Comment by MarconLP** [comment]
fixed in our new support modal
![2024-04-11 at 22 48 59@2x](https://github.com/PostHog/posthog/assets/13001502/f6fd7e45-2072-4a9e-a058-40017a85e3b6)
