### ISSUE TITLE
Bug: We have two new What's New buttons that do different things

### ISSUE THREAD

**Issue by joethreepwood** [PostHog/posthog#19948]
## Bug description

We have a button here, called What's New? which goes to the changelog
![screenshot_2024-01-24_at_14 58 15](https://github.com/PostHog/posthog/assets/84011561/f1f07d18-265c-4125-80fd-d60e146e2fa9)

And one here, called What's New? which opens the sidebar tab about 3000. 
![screenshot_2024-01-24_at_14 58 28](https://github.com/PostHog/posthog/assets/84011561/688aff9c-dfa1-44a9-8538-0f0b75f540ae)

Different icons, different targets.

I feel like we can either:

- Retire the 3000 sidetab and direct it to /changelog, so it matches the existing behaviour (easy)
- Remove one of the buttons and redirect the remaining one to point to /changelog (medium)
- Have the changelog open in-app in the sidebar (hard)

Don't have a preference. But two buttons with different behaviours like this is Bad, and we don't need the 3000 sidebar anymore. 

## How to reproduce

1.
2.
3.

## Environment

- [ ] PostHog Cloud US, project ID: [please provide from https://app.posthog.com/settings/project-details#variables]
- [ ] PostHog Cloud EU, project ID: [please provide from https://eu.posthog.com/settings/project-details#variables]
- [ ] PostHog Hobby self-hosted with `docker compose`, version/commit: [please provide]
- [ ] PostHog self-hosted with Kubernetes (deprecated, see ["Sunsetting Kubernetes support"](https://posthog.com/blog/sunsetting-helm-support-posthog)), version/commit: [please provide]

**Comment by Twixes** [comment]
I was also thinking about this, great you're bringing it up. I agree we can say goodbye to the 3000 introduction. And actually "Have the changelog open in-app in the sidebar" is super easy, it'd look like this:

<img width="509" alt="Screenshot 2024-01-24 at 16 47 23" src="https://github.com/PostHog/posthog/assets/4550621/e2ef636f-8b54-4b16-856b-0cab9a626ec6">

**Comment by joethreepwood** [comment]
That'd be awesome!

I think it's a little odd having two very similar menus - the sidebar ... menu, and the profile menu - having the same overall functions. Feature previews and What's New are in both. But if they both have the same result, I think that's a step in the right direction!
