### ISSUE TITLE
Can't use posthog-react-native in a React Native app without Expo 

### ISSUE THREAD

**Issue by micahhauge** [PostHog/posthog#19944]
## Bug description

I can't use the `posthog-react-native` sdk in a react native app that is NOT using expo.
 
After installing the `posthog-react-native` sdk and following the usage instructions [located here](https://posthog.com/docs/libraries/react-native), I get a runtime error indicating that the posthog sdk is attempting to use `expo-file-system`, which I don't have installed since I am not using expo.

<img width="864" alt="image" src="https://github.com/PostHog/posthog/assets/16975119/0617c1ac-3785-4e3d-b9c7-bdc9f304458a">

## How to reproduce

1. Install the dependences as indicated in the [setup guide](https://posthog.com/docs/libraries/react-native).
2. Setup the posthog client and attempt to capture an event.
3. Get the following error:
```
error: Error: Unable to resolve module expo-file-system from /Users/micahhauge/repos/foster-friendly-app/node_modules/posthog-react-native/lib/posthog-react-native/src/optional/OptionalExpoFileSystem.js: expo-file-system could not be found within the project or in these directories:
  node_modules
```

## Environment

- [ ] PostHog Cloud US, project ID: [please provide from https://app.posthog.com/settings/project-details#variables]
- [ ] PostHog Cloud EU, project ID: [please provide from https://eu.posthog.com/settings/project-details#variables]
- [ ] PostHog Hobby self-hosted with `docker compose`, version/commit: [please provide]
- [ ] PostHog self-hosted with Kubernetes (deprecated, see ["Sunsetting Kubernetes support"](https://posthog.com/blog/sunsetting-helm-support-posthog)), version/commit: [please provide]

**Comment by benjackwhite** [comment]
The documentation linked mentions that if not using expo you need to install async storage. 

The SDK will try and load either but if none are available then it fails with a log like you see as we need some sort of peer dependency to store things to disk.

**Comment by micahhauge** [comment]
Hey @benjackwhite! Thank you for your response.

I should have mentioned in my original post that I _have_ additionally installed `@react-native-async-storage/async-storage` and `react-native-device-info` as the docs indicated.

I am specifically running version `1.21.0` of async storage and I have verified that it is present in my `node_modules` directory.

![IMG_1663](https://github.com/PostHog/posthog/assets/16975119/dd9ef0d4-c041-4326-9d12-b5548a742fb3)

**Comment by micahhauge** [comment]
Update: It looks like this PR might address my issue: https://github.com/PostHog/posthog-js-lite/pull/166

I will verify tonight and close this issue if it is resolved 👍🏻

**Comment by micahhauge** [comment]
I have confirmed that https://github.com/PostHog/posthog-js-lite/pull/166 fixes my issue. Thanks guys!
