### ISSUE TITLE
Improvements to retention view

### ISSUE THREAD

**Issue by paolodamico** [PostHog/posthog#1995]
Here is some feedback (bugs & improvements) from the new version of retention using CH.

- [UX] Set default date so that the current period (today, this week, ...) is the last period shown. By default the date is set to last week, but then you see a graph that's very empty (and it could lead you to think at first that something is wrong). You'll almost always want to see as much past periods as possible anyways.
- [UX] I think we need to make the background color differences a bit more steep (my guess is that we're consider the 100% for the math) and this causes almost no difference in brightness for most of the table.
- [UX] For the new users column, maybe use the same formatter we use for emails (i.e. 5k instead of 5839), screen tends to get bloated for 4+ digits.
- [UX] For the dates (at least week & month) I think we could simplify it, and it'll be easier to read too. For week -> "Mar 23" instead of "Sun. 23 Mar", for month "July 2020" instead of "Wed. 1 July".
- [Bug] The header rows always say "Day n" instead of "Week n", "Month n" depending on the filter.

**Comment by jamesefhawkins** [comment]
#2104 is relevant.

And the bug you mention is fixed now!
