### ISSUE TITLE
Date picker jumping around is poor UX

### ISSUE THREAD

**Issue by jamesefhawkins** [PostHog/posthog#19964]
If you want to quickly go through lots of months, the datepicker jumps around in height, making it annoying to click through the months.

<img width="321" alt="Screenshot 2024-01-25 at 12 49 31" src="https://github.com/PostHog/posthog/assets/47497682/1040036d-6755-416c-9f03-dde33a5a9eba">
<img width="318" alt="Screenshot 2024-01-25 at 12 49 39" src="https://github.com/PostHog/posthog/assets/47497682/e174af6e-050f-4af4-bd7e-2ecc987c5121">

We should make this a fixed height

**Comment by adamleithp** [comment]
fixed in [#26932](https://github.com/PostHog/posthog/pull/26932)
