### ISSUE TITLE
Make feature flags toggleable in development/testing environments via toolbar

### ISSUE THREAD

**Issue by macobo** [PostHog/posthog#1996]
## Is your feature request related to a problem?

This idea comes from [this feeback] by customer: https://github.com/PostHog/posthog-js/issues/100#issuecomment-714896659

Specifically:

> PostHog is one of the few (possibly only) things that is unique to our production environment since it does not provide a way to test it without polluting production data. In hindsight, with this knowledge, more care on our end should have been taken before rolling out any updates to the PostHog client. I recommend others do the same.

This is 100% true and rather scary - we're making it hard to test what you write.

Our users need a solution for:
- Testing out feature flags locally w/o needing to use production posthog (due to data pollution, needing to hit production environments)
- Being able to toggle feature flags on-off in development/testing easily without it affecting other tests/developers

## Describe the solution you'd like

1. Add a `development: true` flag to posthog-js configuration
1. We don't ingest data while `development: true`
1. If in development mode, toolbar would have an additional tab: feature flags. 
    - It would list all previously used feature flags and a way to toggle them on-off
    - Toggling features there would only apply changes to your own local environment (via localstorage), not production/other devs
    - Toggling features should give immediate feedback in e.g. a react app
1. Levarage and document the solution used to store local flags and how to use it in feature/integration tests.

In addition, it would be cool if we (similar to stripe) always:
- created a development environment for every project
- switched to that when `development: true`. 
- allowed (optionally) to send data to the development environment via a toggle in the toolbar to allow testing our tracking

I would prefer not to store flags there though since it would mean one dev changing flags affected all others.

## Describe alternatives you've considered

- Promoting `posthog.featureFlags.override(...)` - this seems like a too low-level tool, might lead to surprises
- Documenting how to turn off all tracking in posthog-js in development

## Additional context

Notes:
- this does not address all problems from https://github.com/PostHog/posthog-js/issues/100, other actions required there
- not sure how to make this work for BE flags
- from experience, list of feature flags grows over time and they don't get pruned immediately. We might need a way to "persist" these defaults as well (development env?)
- I think this is immediately applicable to our own workflows -> dogfooding :dog: 

@timgl @paolodamico

**Comment by mariusandra** [comment]
Related and possible additional context in https://github.com/PostHog/posthog/issues/1048

**Comment by timgl** [comment]
The appropriate functions are already implemented in posthog-js:

`posthog.feature_flags.override(['beta-feature'])`  will get rid of all flags and just enable beta-feature
`posthog.feature_flags.override(false)` will go back to posthog-supplied flags

**Comment by macobo** [comment]
@timgl Agreed - the proposed solution would be built on top of this, also mentioned it in the proposal. However I think just documenting it doesn't solve the pain points described above.

**Comment by timgl** [comment]
Oops read over that. yes agree, was just making sure you were aware :)

**Comment by mariusandra** [comment]
This doesn't seem to work for me in localhost. Been trying for ages now to get the session recording flag locally, but so far no luck.

![image](https://user-images.githubusercontent.com/53387/96992458-3829b800-152a-11eb-8f34-86f2da70e450.png)

**Comment by weyert** [comment]
Yes, this would be handy. I am only wondering how I can enable a feature flag for a specific session, e.g. a test running in Cypress, without needing to make separate app users for each test. Imagine having have multiple workers which deal with feature flags, and you want to enable a flag for your VIP user and want to test the different in backend behaviour.

**Comment by paolodamico** [comment]
This is now supported!!

**Comment by LeoDoldan7** [comment]
@paolodamico Is there a link to the docs?

**Comment by dmarticus** [comment]
@LeoDoldan7 I believe [these are the docs](https://posthog.com/docs/feature-flags/testing) you're looking for (scroll down to "Method 3: Use the PostHog toolbar")
