### ISSUE TITLE
Disable opening top-level sidebar menu

### ISSUE THREAD

**Issue by mariusandra** [PostHog/posthog#1998]
## Bug description

This behaviour is ever so slightly frustrating:

![2020-10-23 10 02 35](https://user-images.githubusercontent.com/53387/96972638-0a874380-1517-11eb-940c-8adc813cb3e1.gif)

## Expected behavior

On mobile, with a collapsing sidebar, when I want to visit "sessions" and click "Events" to expand the menu, the sidebar should remain open and the "All Events" page shouldn't open by default.

**Comment by paolodamico** [comment]
Love the creative use of the command palette in the gif.

**Comment by EDsCODE** [comment]
New menu resolves this
