### ISSUE TITLE
Enabling body capture for network requests breaks streaming for event-stream http responses

### ISSUE THREAD

**Issue by dhatawesomedude** [PostHog/posthog#20053]
## Bug description

Enabling body capture for network requests breaks streaming for event-stream http responses.

When you await a fetch promise for a request to a server that returns an event-stream response, it should resolve immediately so you can stream the events.

This bug causes the promise to not resolve until the whole content is downloaded. 

## How to reproduce

1. Enable network monitoring and body capture
2. Run javascript that sends a fetch request to a http endpoint that returns a text/event-stream response
3. The promise doesn't resolve until all of the content is downloaded.

This request doesn't have to be initiated from within code, it can be initiated from the browser console. The result is the same.

## Environment

- [x] PostHog Cloud US, project ID: [please provide from https://app.posthog.com/settings/project-details#variables]
- [ ] PostHog Cloud EU, project ID: [please provide from https://eu.posthog.com/settings/project-details#variables]
- [ ] PostHog Hobby self-hosted with `docker compose`, version/commit: [please provide]
- [ ] PostHog self-hosted with Kubernetes (deprecated, see ["Sunsetting Kubernetes support"](https://posthog.com/blog/sunsetting-helm-support-posthog)), version/commit: [please provide]

## Additional context

-

**Comment by pauldambra** [comment]
Ah, I didn't think GitHub would auto-close this :)

We're just releasing posthog-js 1.103.2 which should fix this. Would love to hear if it works for you @dhatawesomedude !
