### ISSUE TITLE
Rolling window for active user eg. last 30 days

### ISSUE THREAD

**Issue by peterwillemoeskondrup** [PostHog/posthog#2008]
## Is your feature request related to a problem?

To be able to calculate the ratio between daily active user og monthly active users (DAU / MAU), we need to have a rolling window of the last 30 days.

We tried by selecting the data range manually in the date-range-selector, but it still shows

**Comment by peterwillemoeskondrup** [comment]
Discussed online with your developer @EDsCODE

**Comment by yakkomajuri** [comment]
Thanks for documenting this request!

**Comment by timgl** [comment]
Slightly more detail in this newer ticket: #3638
