### ISSUE TITLE
No users shown in insights graph

### ISSUE THREAD

**Issue by peterwillemoeskondrup** [PostHog/posthog#2010]
## Bug description
If you look at the attached screen shot, you can see that the number of users is 0 ... based on the graph it should be more than 0.
![Screenshot 2020-10-23 at 11 46 54](https://user-images.githubusercontent.com/58939342/97005429-be4ff980-153e-11eb-80f4-30cfc65fb22f.png)

## How to reproduce

1. 
2. 
3. 

## Environment

- PostHog cloud or self-managed?
- PostHog version/commit

**Comment by yakkomajuri** [comment]
Thanks for reporting this! I was about to do so myself

**Comment by Twixes** [comment]
I can't reproduce this on master – on all Trends combinations that I've tried, individual users were matching the graph. Is there something I may be missing?
