### ISSUE TITLE
Survey Support for React Native

### ISSUE THREAD

**Issue by singleston** [PostHog/posthog#20107]
## Is your feature request related to a problem?

We have limited flexibility on survey functionality in our app, we are dependent on pushing responses into posthog via the API

## Describe the solution you'd like

We'd like to be able to build surveys without going through the engineering backlog, with the ability to target to different cohorts (screens, interactions, feature flags etc)

## Describe alternatives you've considered

Building our own internal tool and posting the responses back into posthog

**Comment by marandaneto** [comment]
dupe https://github.com/PostHog/posthog-js-lite/issues/110
