### ISSUE TITLE
charts "grouped by month" are mislabelled on the x-axis - crucial UX bug

### ISSUE THREAD

**Issue by samuelstroschein** [PostHog/posthog#20137]
## Bug description

The grouped-by-month view in charts is hella confusing. The x-axis shows a date that does not reflect the value on the y-axis.

1. the y-axis shows the number for the END of the month
2. the x-axis reads as "beginning of the month"

![CleanShot 2024-02-05 at 10 23 30@2x](https://github.com/PostHog/posthog/assets/35429197/d78df745-8319-4b78-95fa-d96f18aee357)

### Comparison with daily grouping

Compare the "group by month" view with "group by day". The x-axis labeling aligns with the y-axis values. 

![CleanShot 2024-02-05 at 10 29 20@2x](https://github.com/PostHog/posthog/assets/35429197/998825fa-7406-4214-8310-8f173980f80c)

## How to reproduce

1. Group a chart by month 
2. select "unique events"

### 1. easy fix - remove the "1." from the labelling

- will still confuse readers with "is this the beginning or end of the month"

![CleanShot 2024-02-05 at 10 23 30@2x](https://github.com/PostHog/posthog/assets/35429197/1a0ae6d4-0e02-4b32-86ab-7b0e069655ed)

### 2. correct fix - show end of month

- removes ambiguity from "is that the beginning or end of month"
- harder to implement because months have different end days

![CleanShot 2024-02-05 at 10 23 30@2x](https://github.com/PostHog/posthog/assets/35429197/61226346-7f97-4bcd-87bf-53fc83c75245)

cc @jannesblobel

**Comment by samuelstroschein** [comment]
fyi this bug led to a "omg is posthog buggy" feeling. 

this bug is a recurring problem when communicating metrics with the team. we don't understand why posthog never fixed this bug (we raised it via email). now, i understand everyone is busy. that's why we invested the time into this clear issue with proposals.

**suggestion**

1. release the quickfix now (should take 10 mins?) 
2. implement the correct solution with a follow up update

**Comment by mariusandra** [comment]
Hey there, I guess nobody "fixed" this, as nobody out of all our users got confused so far 🙃.

We'll work on the "quick" fix, but to be clear, your confidently proposed "correct solution" in this case is incorrect, since different users look at different data, and this chart supports many sources. "Average per month" for example would look really bad if shown with a end-of-month date.

In any case, thanks for flagging and we'll see for the "quick" fix.

**Comment by samuelstroschein** [comment]
Thanks for the quick resolution!

> confidently proposed "correct solution" in this case is incorrect, since different users look at different data, and this chart supports many sources, including custom SQL aggregations.

correct me please. the graph is showing a timeseries. the x-axis shows the date. regardless of custom queries. the end of the month date e.g. Feb 29 2024 will always be on the same spot on the x-axis. (By not labeling the spot "correctly" e.g. Feb 29, ambiguity arises what the x-axis is displaying.)
 
>  "Average per month" for example would look really bad if shown with a end-of-month date.

This is precisely why we decided not to use the aggregation function provided by posthog for "monthly active users" :D It can be misleading.

**Comment by mariusandra** [comment]
Ah, forgot to reply to the other question:

> correct me please. the graph is showing a timeseries. the x-axis shows the date. regardless of custom queries. the end of the month date e.g. Feb 29 2024 will always be on the same spot on the x-axis. (By not labeling the spot "correctly" e.g. Feb 29, ambiguity arises what the x-axis is displaying.)

Well, yes, no and maybe. It's not so simple. If we have the first point on the chart, the one that intersects the Y axis, say "31 August", then it'll look confusing, as it'll feel like the data for 1-30 August has been omitted. I can bet you a bowl of lasagne we will get a lot more support requests this way. It might be more "technically" correct, but in my experience that's not the only thing that matters :).

**Comment by mariusandra** [comment]
Haha.. I'd be down for that, yet sadly I have no plans to fly over the pond in the near future (hi from Belgium), and an AB test of this kind is definitely not something we can justify in sprint planning... 😆 

However my years in this industry have taught me that 1) what's clear to you is not clear to everyone, 2) what's not clear for you is definitely guaranteed to not be confusing to someone else, 3) nobody is special

The solution you're proposing might be clearer in the context of a trends line chart, and for sure the "cumulative" trends line chart... but again only for some aggregations, which we'd need to determine in a clever way. You want a solution to your chart, yet as PostHog we have to figure out a solution to all types charts for all users with a huge variance in backgrounds (both technical and not). Aggregating over a full month and only showing one day inherently makes people pause and think, and [we don't want that](https://www.amazon.com/Dont-Make-Think-Revisited-Usability/dp/0321965515). The "year and month" solution is thus the best compromise in my book. (Again, I live in Belgium, we're experts in compromise here 😅)

PS. Looking at the modified screenshot, "_**30**_-Aug-2023" on a chart would for sure confuse me 🙈 😆
