### ISSUE TITLE
Links in table entries should be clickable

### ISSUE THREAD

**Issue by RhysSullivan** [PostHog/posthog#20188]
## Is your feature request related to a problem?

I want to be able to click the links here to visit these pages
![image](https://github.com/PostHog/posthog/assets/39114868/88e30bbb-3793-4f49-83f0-738b57d04be5)

## Describe the solution you'd like

Hovering the link underlines it, clicking it opens in new tab

## Describe alternatives you've considered

- Having a copy button next to the link
- Fetching the link client side to get OG data (i.e name)

## Additional context

If this is wanted as a feature I can open a PR for it

**Comment by aspicer** [comment]
Hi @RhysSullivan,

That sounds like a fantastic addition. We would welcome a PR for that feature!

**Comment by miguelhrocha** [comment]
Hi @aspicer, I would like to work on this 😄

**Comment by aspicer** [comment]
@miguelhrocha thanks, but in this case it already looks like Pety has a working PR in that's just waiting on review from a couple people!

We don't do tickets or assignments in general though, but we welcome PRs!

**Comment by thmsobrmlr** [comment]
Solved in https://github.com/PostHog/posthog/pull/22002
