### ISSUE TITLE
Request: Open product onboarding links in the sidebar

### ISSUE THREAD

**Issue by joethreepwood** [PostHog/posthog#20210]
## Is your feature request related to a problem?

Feels like it may be better for activation if we opened these ‘Learn More’ links in the sidebar and kept users in the app, rather than taking them totally out of the app and into the docs

<img width="1169" alt="Screenshot 2024-02-08 at 16 07 21" src="https://github.com/PostHog/posthog/assets/84011561/2a9ee620-c0a3-4ff2-8219-8ea23cd63d67">

## Describe the solution you'd like

Open the docs as normal, but in the sidebar via something like https://us.posthog.com/project/2#panel=docs:/feature-flags

**Comment by raquelmsmith** [comment]
I think this should have fixed it 👍 https://github.com/PostHog/posthog/pull/20216
