### ISSUE TITLE
SQL query insights: support filters placeholder in CTEs (WITH clauses)

### ISSUE THREAD

**Issue by aseemk** [PostHog/posthog#20252]
## Is your feature request related to a problem?

I want to DRY up a repetitive SQL query insight, and/or make it more modular and understandable, by breaking it up into CTEs (common table expressions), AKA `WITH` clauses.

E.g. here's a repetitive query that has to `arrayJoin(JSONExtractArrayRaw(...))` multiple times to extract properties from objects in a JSON array:

```sql
select JSONExtractString(arrayJoin(JSONExtractArrayRaw(properties.quizResults.answers ?? '[]')), 'text') as question

, sumIf(1,
    JSONExtractString(arrayJoin(JSONExtractArrayRaw(properties.quizResults.answers ?? '[]')), 'answer'
  ) = '2') as '😍'
, sumIf(1,
    JSONExtractString(arrayJoin(JSONExtractArrayRaw(properties.quizResults.answers ?? '[]')), 'answer'
  ) = '1') as '🙂'
, sumIf(1,
    JSONExtractString(arrayJoin(JSONExtractArrayRaw(properties.quizResults.answers ?? '[]')), 'answer'
  ) = '0') as '😐'
, sumIf(1,
    JSONExtractString(arrayJoin(JSONExtractArrayRaw(properties.quizResults.answers ?? '[]')), 'answer'
  ) = '-1') as '🙁'
, sumIf(1,
    JSONExtractString(arrayJoin(JSONExtractArrayRaw(properties.quizResults.answers ?? '[]')), 'answer'
  ) = '-2') as '🤮'

from events
where {filters} -- replaced with global date and property filters
and event = 'Quiz Finished'
and ... -- other filters in practice

group by 1
```

I'm not able to DRY up this query today through other means AFAIK. (E.g. using an `ARRAY JOIN` _clause_ would let me DRY up the `arrayJoin(...)` functions, but that breaks other features my actual query relies on; issue #20250. And these multiple `sumIf(...)`s are needed to achieve a manual 2D table; issue #20251.)

—

So I'd love to at least DRY it up with a CTE:

```sql
with answerEvents as (
  select JSONExtractString(arrayJoin(JSONExtractArrayRaw(properties.quizResults.answers ?? '[]')), 'text') as question
  , JSONExtractString(arrayJoin(JSONExtractArrayRaw(properties.quizResults.answers ?? '[]')), 'answer') as answer

  from events
  where {filters} -- replaced with global date and property filters
  and event = 'Quiz Finished'
  and ... -- other filters in practice
)

select question
, sumIf(1, answer = '2') as '😍'
, sumIf(1, answer = '1') as '🙂'
, sumIf(1, answer = '0') as '😐'
, sumIf(1, answer = '-1') as '🙁'
, sumIf(1, answer = '-2') as '🤮'

from answerEvents
group by 1
```

Unfortunately, this query fails with this error:

```
Placeholders, such as {filters}, are not supported in this context
```

![Screenshot 2024-02-10 at 5 06 54 PM](https://github.com/PostHog/posthog/assets/537838/56586552-ba2f-46a7-b932-5b3210a5b7ca)

—

And if I try moving the `{filters}` to outside the CTE:

```sql
with answerEvents as (
  select JSONExtractString(arrayJoin(JSONExtractArrayRaw(properties.quizResults.answers ?? '[]')), 'text') as question
  , JSONExtractString(arrayJoin(JSONExtractArrayRaw(properties.quizResults.answers ?? '[]')), 'answer') as answer

  from events
  where event = 'Quiz Finished'
)

select question
, sumIf(1, answer = '2') as '😍'
, sumIf(1, answer = '1') as '🙂'
, sumIf(1, answer = '0') as '😐'
, sumIf(1, answer = '-1') as '🙁'
, sumIf(1, answer = '-2') as '🤮'

from answerEvents
where {filters} -- replaced with global date and property filters
group by 1
```

That, too, fails, with a different error:

```
Cannot use 'filters' placeholder in a SELECT clause that does not select from the events table.
```

![Screenshot 2024-02-10 at 5 08 45 PM](https://github.com/PostHog/posthog/assets/537838/f9c1d734-7e05-489e-bfbe-f8613a96f86b)

## Describe the solution you'd like

I'd love to apply `{filters}` to `select ... from events` within a `WITH` clause/CTE also.

## Describe alternatives you've considered

I haven't been able to think of any other alternatives. I'm writing very repetitive queries for now.

## Additional context

Thank you for your consideration!

**Comment by Gilbert09** [comment]
Fix rolled out

**Comment by aseemk** [comment]
Amazing, thank you! I'm in a different headspace now but will come back to this later and let you know if any issues. I love seeing the promptness here — thanks again!
