### ISSUE TITLE
Formula mode is broken

### ISSUE THREAD

**Issue by MarconLP** [PostHog/posthog#20262]
## Bug description

This result with the formula mode B/A should 
![2024-02-11 at 22 36 41@2x](https://github.com/PostHog/posthog/assets/13001502/65c7187b-4948-4fa8-a211-8230add3785c)
![2024-02-12 at 11 40 07@2x](https://github.com/PostHog/posthog/assets/13001502/c746794c-777d-49c8-ba66-339002aa3dee)

## How to reproduce

1. Add 2 chart series (https://us.posthog.com/project/35787/insights/54lxh5cP/edit)
- Pageview
- Pageview with filters (pathname contains /account)
2. Enable formula mode B/A
3. The result should be 1/11 = 0.0909, but is 11?

## Additional context

https://posthoghelp.zendesk.com/agent/tickets/10211

**Comment by Twixes** [comment]
Note: this seems to only be the case for the WIP HogQL-based backend.

**Comment by Twixes** [comment]
Appears that this is no longer a problem!
