### ISSUE TITLE
Session Replay screen suggests to update SDK to an earlier version

### ISSUE THREAD

**Issue by gorohoroh** [PostHog/posthog#20260]
## What happens
Inside the *Session Replay* section, PostHog displays a warning message suggesting to update the PostHog SDK. However, the version that it suggests updating to is older than the currently used version:

> Your PostHog SDK needs updating. The latest version of posthog-js is 1.105.6, but you're using 1.105.7.

<img width="1155" alt="image" src="https://github.com/PostHog/posthog/assets/507264/ce7ccb38-7c32-46b5-81c2-eaebac4ee0ad">

## What I expect to happen instead
I expect PostHog to realize that the currently used SDK version is actually newer than the one it suggests to update to. Upon realizing this, I expect it to stop displaying this warning message.

## Environment
PostHog Cloud US, project ID: 52521

**Comment by pauldambra** [comment]
Ah, the joys of parsing semantic versions 🙈

**Comment by pauldambra** [comment]
Should already be fixed but we cache that value pretty heavily so might take a while 🫠

**Comment by gorohoroh** [comment]
@pauldambra And it's fixed, indeed. Thank you, impressive!
