### ISSUE TITLE
Bug: Feature preview opens on resize

### ISSUE THREAD

**Issue by joethreepwood** [PostHog/posthog#20294]
## Bug description

If you visit the feature previews menu and then close it, it will automatically reopen when you resize the window. 

https://github.com/PostHog/posthog/assets/84011561/2cacfdef-e335-49b8-8f2e-0c0775064126

## How to reproduce

1. Open feature previews
2. Close it
3. Resize window

## Environment

- [ ] PostHog Cloud US, project ID: [please provide from https://app.posthog.com/settings/project-details#variables]
- [ ] PostHog Cloud EU, project ID: [please provide from https://eu.posthog.com/settings/project-details#variables]
- [ ] PostHog Hobby self-hosted with `docker compose`, version/commit: [please provide]
- [ ] PostHog self-hosted with Kubernetes (deprecated, see ["Sunsetting Kubernetes support"](https://posthog.com/blog/sunsetting-helm-support-posthog)), version/commit: [please provide]

**Comment by benjackwhite** [comment]
Gonna solve this in a nice way for all side panel items I think
