### ISSUE TITLE
Timeframe is wrong when breakingdown by cohort

### ISSUE THREAD

**Issue by EDsCODE** [PostHog/posthog#2031]
## Bug description

*Please describe.*  
If you breakdown by a cohort and try to change timeframe, the date intervals are wrong
*If this affects the front-end, screenshots would be of great help.*  

## Expected behavior
The intervals should be as expected and the same as when filtering normally

## How to reproduce

1.  Go to trends
2.  Breakdown by some cohort
3. change interval to weekly

**Comment by jamesefhawkins** [comment]
I just had this too - see https://app.posthog.com/insights?events=%5B%7B%22id%22%3A%22%24pageview%22%2C%22math%22%3A%22dau%22%2C%22name%22%3A%22%24pageview%22%2C%22type%22%3A%22events%22%2C%22order%22%3A0%2C%22properties%22%3A%5B%5D%2C%22math_property%22%3Anull%7D%5D&breakdown=%5B71%5D&breakdown_type=cohort&properties=%5B%5D&date_from=-30d&interval=day and edit the timeframe between daily and weekly, it doesn't change the numbers int eh graph.
