### ISSUE TITLE
Question. How to partition data when running on Fargate

### ISSUE THREAD

**Issue by Rcjuk** [PostHog/posthog#2033]
As we don't have access to the container, how can we execute the command to create the partitions?

**Comment by fuziontech** [comment]
Hey @Rcjuk! The easiest way would be to setup an ec2 instance on the same network as your ECS cluster. On that box I would configure a web docker container w/ env vars to connect to your production setup (database url, redis, secret). You can find the env vars on the config pages for ECS task definition. Once you have that configured I would run the docker container feeding it the commands from [the partitioning guide](https://posthog.com/docs/configuring-posthog/scaling-posthog)

Let me know if you have any questions about that!

**Comment by Rcjuk** [comment]
Yep! I'll do that. Thank you.
