### ISSUE TITLE
Issue while compiling the code in workspace and even locally 

### ISSUE THREAD

**Issue by AmanSal1** [PostHog/posthog#20341]
## Bug description

So I am trying to compile PostHog locally on my VirtualBox, which has an Ubuntu OS. I'm following the steps outlined in the development guide, but when I run the command "docker compose -f docker-compose.dev.yml up", everything compiles correctly except for one thing: the PostHog Temporal UI isn't getting the port. I thought this issue might be due to running it on VirtualBox, so I attempted to do it on CodeSpaces. However, I encountered the same error

## How to reproduce

1.Follow the development guide and after running the command "docker compose -f docker-compose.dev.yml up" error pops up

## Environment

- [ ] PostHog Cloud US, project ID: [please provide from https://app.posthog.com/settings/project-details#variables]
- [ ] PostHog Cloud EU, project ID: [please provide from https://eu.posthog.com/settings/project-details#variables]
- [ ] PostHog Hobby self-hosted with `docker compose`, version/commit: [please provide]
- [ ] PostHog self-hosted with Kubernetes (deprecated, see ["Sunsetting Kubernetes support"](https://posthog.com/blog/sunsetting-helm-support-posthog)), version/commit: [please provide]

## Additional context
Error log on codespaces

![posthog](https://github.com/PostHog/posthog/assets/121633121/f1329fb9-049c-4c91-9e86-61ca952f76ca)

**Comment by mariusandra** [comment]
Feel free to ignore the temporal containers. At present those are only relevant if you're doing batched exports.

**Comment by AmanSal1** [comment]
@mariusandra So should I proceed with the development guide and ignore this error ?  Thanks in advance

**Comment by mariusandra** [comment]
Unless you're planning on doing batched exports locally, yes.

**Comment by AmanSal1** [comment]
@mariusandra Sorry for disturbing you again but I am running posthog on codespaces but I am unable to see the UI at the localhost port 8000 ? 
I have to different terminal running one for docker and other for starting all the services.

**Comment by mariusandra** [comment]
Unfortunately we're not able to provide basic debugging support 🙃
