### ISSUE TITLE
Allow using visitParam* functions in clickhouse

### ISSUE THREAD

**Issue by macobo** [PostHog/posthog#2039]
Currently, the jsons we put into clickhouse contain spaces due to the way json.dumps works:

```
In [20]: json.dumps({ "foo" :1, "2":3 })                                                             
Out[20]: '{"foo": 1, "2": 3}'
```

We could use the more optimized JSON visitParam* functions if we removed these spaces: [reference](https://clickhouse.tech/docs/en/sql-reference/functions/json-functions/)

```
In [21]: json.dumps({ "foo" :1, "2":3 }, separators=(',',':'))                                       
Out[21]: '{"foo":1,"2":3}'
```

This would require re-ingesting a whole bunch of data though.

**Comment by Twixes** [comment]
I don't think this is feasible IF reingesting is a must? @macobo

**Comment by macobo** [comment]
If it's a big enough win we can do _anything_ :muscle:

**Comment by Twixes** [comment]
I ran some benchmarks using [`clickhouse-benchmark`](https://clickhouse.tech/docs/en/operations/utilities/clickhouse-benchmark/) on two test JSON objects: `{"x":2}` and minified https://github.com/PostHog/posthog/blob/master/app.json.

Running tens of thousands of queries, `visitParamExtractRaw` and `JSONExtractRaw` seem to perform… roughly the same. Maybe a 20% speedup, but never nearing even 2x.

Seeing that `JSONExtract*` functions already use the superoptimized (and battle-tested) [`simdjson`](https://github.com/simdjson/simdjson), it seems doubtful to me that this would be a significant win considering that we'd have to reingest ALL of our events and persons for `visitParam*`'s strict requirements. I think reducing the number of JSON extractions overall with materialization (#5523) has much better potential.

**Comment by macobo** [comment]
For measurements though we need to be comparing reading-from-disk flows rather than static strings to get an apples-to-apples comparison

However this is not a priority right now - in the backlog as a note for long-term. :)

**Comment by macobo** [comment]
With materialized columns this is kind of redundant.
