### ISSUE TITLE
🤔 Heatmaps 3000

### ISSUE THREAD

**Issue by pauldambra** [PostHog/posthog#20426]
The replay team is currently considering improving PostHog by extending the data considered for generating our heatmaps

Currently we have _only_ click maps - they're pretty slow to generate, and because they rely on CSS selectors if you change a CSS selector for an element that otherwise remains the same we no longer include it (no bueno)

With session replay we're gathering mouse coordinates and screen dimensions for every session recorded. And with web analytics we're now gathering scroll depth. 

We should use this information to generate true heatmaps.

-----

Other potential inclusions / improvements:

1. **[Proper regex support](https://github.com/PostHog/posthog/issues/16764):** We only allow for wildcards in the URL search bar which does not cover all cases
2. **Person filters:** Right now there is no way to filter heatmaps. It would be good to let customers filter events based on users in certain cohorts / ignore internal users

**Comment by joshreleaf** [comment]
The heatmap feature is excellent but it only shows clicks on elements that are clickable.

Would be great if it also had traditional heatmap functionality, so we can see clicks on non clickable elements too.

Also, would like to see scroll map functionality added.

**Comment by pauldambra** [comment]
we've now added a new heatmap feature. you can enable it at https://us.posthog.com/settings/project#heatmaps

we're also working on an in-app heatmap page... watch this space!

**Comment by pauldambra** [comment]
@joshreleaf the new heatmap includes a scrollmap... would love any feedback if you are able to try it :)

**Comment by marandaneto** [comment]
@pauldambra should we close this issue as completed?
