### ISSUE TITLE
Batch export logs UI: An error has occurred

### ISSUE THREAD

**Issue by MarconLP** [PostHog/posthog#20450]
## Bug description

![2024-02-20 at 13 00 55](https://github.com/PostHog/posthog/assets/13001502/99a29bff-5a19-4305-8d28-e5128261cce6)

## How to reproduce

1. Open a batch export (example: https://us.posthog.com/project/2/batch_exports/018cf79f-a9e5-0001-cd6a-edc4886d939d)
2. Click logs
3. Click edit
4. Click cancel or browser-back

## Additional context

https://posthoghelp.zendesk.com/agent/tickets/10701

**Comment by MarconLP** [comment]
+1 https://github.com/PostHog/posthog/issues/20450

**Comment by tiina303** [comment]
This is a transient error, refreshing helps. I'll be looking into this next sprint.

**Comment by MarconLP** [comment]
+1 https://posthoghelp.zendesk.com/agent/tickets/13152 (moved to PostHog: https://us.posthog.com/project/2/support/tickets/15612)
