### ISSUE TITLE
Our event property search is not smart

### ISSUE THREAD

**Issue by yakkomajuri** [PostHog/posthog#2049]
## Bug description

*Please describe.*  
*If this affects the front-end, screenshots would be of great help.*  

Searching for "URL" gives me "Current URL" but not "Initial Referrer URL" nor "Referrer URL".

<img width="250" alt="Screenshot 2020-10-27 at 13 14 49" src="https://user-images.githubusercontent.com/38760734/97307416-8fe06000-1857-11eb-9f49-8072c1f07372.png">

## Expected behavior

Getting all events that contain "URL"

## How to reproduce

1. Search on the property filter

**Comment by Twixes** [comment]
This seems fixed now.
