### ISSUE TITLE
Insights filters aren't obviously scrollable

### ISSUE THREAD

**Issue by jamesefhawkins** [PostHog/posthog#2050]
I've left this up for clarity - I was confused by the UI!

## Is your feature request related to a problem?

We have way more filters than the UI makes obvious in the insights page.

These include some basic, important use cases like UTM tags.

You can find these filters by searching in the text box, but they don't appear unless you scroll or type something ie:

![Screenshot 2020-10-27 at 13 35 17](https://user-images.githubusercontent.com/47497682/97309033-74765480-1859-11eb-9d24-40912a91bb7e.png)

![Screenshot 2020-10-27 at 13 35 23](https://user-images.githubusercontent.com/47497682/97309078-7e985300-1859-11eb-8b24-7fdb8a548a96.png)

## Describe the solution you'd like

Add something to make it obvious you can scroll the list.

**Comment by Twixes** [comment]
They do appear actually… they're a bit down below that list, which is scrollable – it's just that scrollability is non-obvious on macOS, as the scroll bar is often hidden. Could maybe add a light gradient overlay at the bottom to signal that there's something more there.
Side note: I think the `invalid` label usually means that the issue/PR itself is invalid, as opposed to the reported/fixed behavior. At least that's the use case I mostly have seen.

**Comment by jamesefhawkins** [comment]
Ah, yep - just realized. I agree a small gradient could signal there is more there.

I've fixed the tags and edited the header to be clearer
