### ISSUE TITLE
Add feature flag filters to main table

### ISSUE THREAD

**Issue by timgl** [PostHog/posthog#2057]
## Is your feature request related to a problem?

To understand how a feature flag is built up, I need to click into each individual feature flag

## Describe the solution you'd like

I want to see everything under "Filter by user properties" (but non-clickable and without the "X" and "Add filter" button) and I want to see the percentage of user roll out, all inside the main table

![image](https://user-images.githubusercontent.com/1727427/97368460-4c174600-18ab-11eb-96d9-e561bb1351dc.png)

## Describe alternatives you've considered

Click into each feature flag

**Comment by GalDayan** [comment]
I'll take this issue

**Comment by GalDayan** [comment]
Why do you want the Filters to be non clickable, without "X", and "Add Filters" Button? it actually seems very UX friendly. 
@timgl 
![image](https://user-images.githubusercontent.com/24251369/99138720-4fe0f180-263b-11eb-9e84-0af43b21d994.png)
