### ISSUE TITLE
GeoIP app not populating events.

### ISSUE THREAD

**Issue by MarconLP** [PostHog/posthog#20586]
## Bug description

The GeoIP app is not populating events with GeoIP properties.

Example:
test web app: https://posthog-test-marcus.vercel.app/
connected to this posthog project: https://us.posthog.com/project/35787

## Additional context

https://posthoghelp.zendesk.com/agent/tickets/11013

**Comment by pauldambra** [comment]
flyby that

```
select toStartOfHour(timestamp), count(distinct mat_$geoip_country_code)
from events 
where mat_$geoip_country_code is not null and mat_$geoip_country_code != ''
and timestamp >= now() - interval 14 day
and timestamp <= now()
and team_id = 35787
group by toStartOfHour(timestamp)
```

shows at least one geo ip property on events for that team

and that query without a team_id doesn't show any drop in count of distinct country codes per hour

so hopefully this is a UI or query bug and not a data population bug

**Comment by bretthoerner** [comment]
We had another report where the user thought it was an ingest/plugin issue but their events have geo properties, so it does seem like a query side issue.

**Comment by Rhyce** [comment]
This may have been fixed; I'm not sure if it's propagated to everyone affected yet though. I've checked my analytics, and while the odd event still shows Unknown, most events have countries associated now.

**Comment by vfrolov** [comment]
Also experiencing this. Standard properties like Country for most events are now empty.

<img width="851" alt="Screenshot 2024-02-28 at 11 40 35 PM" src="https://github.com/PostHog/posthog/assets/19354435/60183b8c-aacd-4d8a-96c0-052d2935a2cc">

**Comment by rossanmol** [comment]
Also experiencing this problem, this is causing data loss :(

**Comment by GavPierce** [comment]
Also have this problem. No correct IP addresses are being recorded. Causing Country codes to show as "None"

**Comment by bretthoerner** [comment]
We had a proxy configuration issue that has been resolved, can you all check your new/incoming events out as of ~now?

**Comment by GavPierce** [comment]
Resolved for us!

**Comment by muradbu** [comment]
Came here because I stopped seeing location data in my People as well

**Comment by MarconLP** [comment]
> Came here because I stopped seeing location data in my People as well

We've just resolved a proxy configuration issue. Could you check again?

**Comment by muradbu** [comment]
> > Came here because I stopped seeing location data in my People as well
> 
> We've just resolved a proxy configuration issue. Could you check again?

It works again :)

Thought it was my fault because I did something wrong

**Comment by jtm2012** [comment]
It's working for me, too. Thank you!

**Comment by MarconLP** [comment]
Hey @awais-shafiq, could you [open a ticket through the app](https://us.posthog.com/#panel=support%3Asupport%3A%3Alow)?

**Comment by 1hachem** [comment]
I am having the same problem now

**Comment by alekoako2** [comment]
Im having the same issue. countries are empty
