### ISSUE TITLE
Update clickhouse to 20.8/20.9 to get access to more systems tables

### ISSUE THREAD

**Issue by macobo** [PostHog/posthog#2063]
20.8 had a bunch of awesome features, including:

- `system.text_log` which allows reading the ch log files without needing ssh access - came up when debugging why ch ingestion stopped
- `system.asynchronous_metrics` table which exposes some system stats

cc @fuziontech @EDsCODE

**Comment by Twixes** [comment]
Done according to https://github.com/PostHog/posthog/projects/8.
