### ISSUE TITLE
HogQL functions should ignore casing `COALESCE` vs `coalesce`

### ISSUE THREAD

**Issue by thmsobrmlr** [PostHog/posthog#20668]
## Is your feature request related to a problem?

Currently HogQL functions need to be camelCased, where's ClickHouse doesn't really care.

## Describe the solution you'd like

`COALESCE` should work the same as `coalesce`.

**Comment by nikitaevg** [comment]
Hey @thmsobrmlr 

I want to start contributing to PostHog, I came across this task, it looks very good as a first issue. Is this still needed? Do you mind if I try it?

Regarding the approach, as per the ClickHouse [documentation](https://clickhouse.com/docs/en/sql-reference/syntax#keywords) it does care about case for some functions. I drafted a [PR](https://github.com/PostHog/posthog/pull/21244), could you please take a look, does the approach look good to you? If so, I'll apply the new change to other functions that are case insensitive.

**Comment by thmsobrmlr** [comment]
> Hey @thmsobrmlr
> 
> I want to start contributing to PostHog, I came across this task, it looks very good as a first issue. Is this still needed? Do you mind if I try it?
> 
> Regarding the approach, as per the ClickHouse [documentation](https://clickhouse.com/docs/en/sql-reference/syntax#keywords) it does care about case for some functions. I drafted a [PR](https://github.com/PostHog/posthog/pull/21244), could you please take a look, does the approach look good to you? If so, I'll apply the new change to other functions that are case insensitive.

Hey @nikitaevg, first off sorry for the delay in response - it has been quite busy here. I was finally able to have a look at your PR and it looks very solid. After letting CI loose on it there are [some lint warnings](https://github.com/PostHog/posthog/actions/runs/8555873923/job/23478820686?pr=21244). Nothing else blocking from merging once these are fixed. You can ignore the other failing test, that is a flappy one and probably fixed in master.

**Comment by nikitaevg** [comment]
@thmsobrmlr No worries and thanks for the review

I fixed the lint warnings and made more functions case insensitive, PTAL!

**Comment by thmsobrmlr** [comment]
> @thmsobrmlr No worries and thanks for the review
> 
> I fixed the lint warnings and made more functions case insensitive, PTAL!
> 
> Also, I think it makes sense to perform the same operation with the [aggregations](https://github.com/PostHog/posthog/blob/7cd24453706e8a5fc0a18ebb29af528ed9e8d0c2/posthog/hogql/functions/mapping.py#L577), to make things consistent, WDYT?

Hey @nikitaevg, all looks good to me now and I've merged the PR already this morning. Doing the same thing with aggregations makes sense, yes. 

Thanks for your contribution!

**Comment by thmsobrmlr** [comment]
Tracking the follow up here https://github.com/PostHog/posthog/issues/21469, since I've been asked why some functions care about casing whereas others don't.
