### ISSUE TITLE
service "web" can't be used with `extends` as it declare `depends_on`

### ISSUE THREAD

**Issue by martonivan** [PostHog/posthog#20696]
## Bug description

The self-hosted Posthog cannot be managed by docker-compose-v2 anymore. Since version 2.24.6.
https://github.com/docker/compose/issues/11522

## How to reproduce

1. Upgrade the docker-compose-plugin package to 2.24.6
2. Try to stop/start the stack with `docker compose down/up`

## Environment

- [ ] PostHog Cloud US, project ID: [please provide from https://us.posthog.com/settings/project-details#variables]
- [ ] PostHog Cloud EU, project ID: [please provide from https://eu.posthog.com/settings/project-details#variables]
- [x] PostHog Hobby self-hosted with `docker compose`, version/commit: 1.43.1
- [ ] PostHog self-hosted with Kubernetes (deprecated, see ["Sunsetting Kubernetes support"](https://posthog.com/blog/sunsetting-helm-support-posthog)), version/commit: [please provide]

## Additional context
It works perfectly after downgrading the docker-compose-plugin package on Ubuntu 22.04.

**Comment by vsupalov** [comment]
This issue is resolved with a recent docker compose update (2.27 works for me again), and can be closed.

**Comment by neilkakkar** [comment]
thanks!
