### ISSUE TITLE
Mobile analytics template shows error in dashboard

### ISSUE THREAD

**Issue by ueman** [PostHog/posthog#20690]
## Bug description

I used the mobile dashboard preset and one of the dashboards shows this error message:

<img width="485" alt="Screenshot 2024-03-04 at 16 13 27" src="https://github.com/PostHog/posthog/assets/1270149/5cc97c9d-fc33-4265-9de0-2ba1a81689aa">

It can be found when looking at https://eu.posthog.com/project/7983/dashboard/45564

## How to reproduce

1. Click <kbd>New Dashboard</kbd>
2. Choose <kbd>Mobile Analytics</kbd>
3. Scroll down and see error message

## Environment

- [ ] PostHog Cloud US, project ID: [please provide from https://us.posthog.com/settings/project-details#variables]
- [x] PostHog Cloud EU, project ID: 7983
- [ ] PostHog Hobby self-hosted with `docker compose`, version/commit: [please provide]
- [ ] PostHog self-hosted with Kubernetes (deprecated, see ["Sunsetting Kubernetes support"](https://posthog.com/blog/sunsetting-helm-support-posthog)), version/commit: [please provide]

## Additional context

Maybe it's related to a project with no data in it yet?

**Comment by marandaneto** [comment]
> Illegal type Nullable(String) of argument (condition) of function multiIf. Must be UInt8.: While processing multiIf(replaceRegexpAll(nullIf(nullIf(JSONExtractRaw(properties, '$network_wifi'), ''), 'null'), '^"|"$', ''), 'wi-fi', replaceRegexpAll(nullIf(nullIf(JSONExtractRaw(properties, '$network_bluetooth'), ''), 'null'), '^"|"$', ''), 'bluetooth', replaceRegexpAll(nullIf(nullIf(JSONExtractRaw(properties, '$network_cellular'), ''), 'null'), '^"|"$', ''), 'cellular', 'unknown') AS value.

The stringified error ^
And a fresh project for reproduction https://us.posthog.com/project/57038/insights/TKCZkem0/edit

**Comment by marandaneto** [comment]
@ueman if you recreate the dashboard, it should be `There are no matching events for this query` now.
