### ISSUE TITLE
Request has been blocked by CORS policy: Request header field baggage is not allowed by Access-Control-Allow-Headers in preflight response.

### ISSUE THREAD

**Issue by DishantPal** [PostHog/posthog#20715]
## Bug description

Hi, so we are using selfhosted instance for posthog. Most of our requests are being blocked due to CORS error like below,

```
Access to XMLHttpRequest at 'https://insights.wellnesswag.com/e/?ip=1&_=1709656610891&ver=1.87.6&retry_count=1&&' from origin 'https://wellnesswag.getheally.com' has been blocked by CORS policy: Request header field baggage is not allowed by Access-Control-Allow-Headers in preflight response.
```

So we have integrated the posthog on two sites:
Site where its not working giving CORS error: https://minimal.videovisitmd.com
Site where its working: https://joinminimal.com

Screenshots:
Console Tab: https://img.enacton.com/ShareX/2024/03/Qtz5agQXM6.png
Network Tab: https://img.enacton.com/ShareX/2024/03/pRyKCHyX87.png
Request Info: https://img.enacton.com/ShareX/2024/03/GaVlYu5blc.png

## How to reproduce

1. Visit https://minimal.videovisitmd.com
2. Signup
3. Inspect network tab

## Environment

- [ ] PostHog Hobby self-hosted with `docker compose`, version/commit: -
- [ ] Instance Settings Ref: https://img.enacton.com/ShareX/2024/03/3AtDL7PeGW.png

Thank You.

**Comment by pauldambra** [comment]
Hey @DishantPal,

We don't offer infrastructure support for self-hosted PostHog.

Looking at your screenshots it's sentry headers being added. They have advice here https://docs.sentry.io/platforms/apple/usage/distributed-tracing/dealing-with-cors-issues/

We use Sentry with PostHog, so my guess is there's something in your infrastructure which isn't accepting those headers
