### ISSUE TITLE
Pricing page doesn't load with ad blocker on

### ISSUE THREAD

**Issue by charliegroll** [PostHog/posthog#20712]
## Bug description

I have uBlock Origin turned on, and visiting https://posthog.com/pricing generates a blank page. I've confirmed that turning the ad blocker off allows the page to load fully. 

This seems to be coming from EasyPrivacy via https://easylist.to/

I've confirmed this in Firefox and Arc, both the latest, and both using uBlock Origin.

Here's the rule the ad blocker is following:

![CleanShot 2024-03-05 at 08 19 06@2x](https://github.com/PostHog/posthog/assets/1126370/d539ae25-0e6f-49e1-a086-9096e916c650)

![CleanShot 2024-03-05 at 08 18 19@2x](https://github.com/PostHog/posthog/assets/1126370/760dab0f-db98-44a2-b153-64a0f836a685)

## How to reproduce

1. Install uBlock Origin
2. visit https://posthog.com/pricing
3. Behold!

## Environment

- [x] https://posthog.com

- [ ] PostHog Cloud US, project ID: [please provide from https://us.posthog.com/settings/project-details#variables]
- [ ] PostHog Cloud EU, project ID: [please provide from https://eu.posthog.com/settings/project-details#variables]
- [ ] PostHog Hobby self-hosted with `docker compose`, version/commit: [please provide]
- [ ] PostHog self-hosted with Kubernetes (deprecated, see ["Sunsetting Kubernetes support"](https://posthog.com/blog/sunsetting-helm-support-posthog)), version/commit: [please provide]

## Additional context

Side note - in searching for the source/denylist for this, I found that some js files and their sourcemaps are being indexed by crawlers (source: https://duckduckgo.com/?q=ad+blocker+app.posthog.com/static/array&ia=web):

![CleanShot 2024-03-05 at 08 22 16@2x](https://github.com/PostHog/posthog/assets/1126370/65f6e44c-b91c-4803-9ab4-9077739b55ad)
![CleanShot 2024-03-05 at 08 22 07@2x](https://github.com/PostHog/posthog/assets/1126370/02033828-420c-4876-b949-8e74f845939b)

**Comment by raquelmsmith** [comment]
Thank you for this report, Charlie! We've now taken our own advice and put our own capture endpoints behind a reverse proxy 😄 Can you verify for me that it works for you now with uBlock on?

**Comment by charliegroll** [comment]
Thanks @raquelmsmith! I see it working with uBlock on (now that it's coming from cloudfront). Cheers!

**Comment by raquelmsmith** [comment]
Awesome thanks!
