### ISSUE TITLE
Allow updating dashboard item description

### ISSUE THREAD

**Issue by paolodamico** [PostHog/posthog#2075]
## Is your feature request related to a problem?

#2068 introduces a `description` attribute to dashboard items. It'd be pretty cool if users can edit those descriptions whenever.

## Describe the solution you'd like
Ideally the user could just click on the description and could edit in inline. We would have to show an "Add description" empty state for when there's no description.

## Describe alternatives you've considered
Only static descriptions.

**Comment by paolodamico** [comment]
I'm going to actually reopen this as I don't think #4068 addresses this. With #4068 (and previous PRs) we allow setting and changing dashboard descriptions, however the goal of this issue is allowing users to set/change descriptions on **dashboard items.**

**Comment by paolodamico** [comment]
I believe @liyiy has now addressed this?

**Comment by liyiy** [comment]
> I believe @liyiy has now addressed this?

It's still WIP because the dedicated dashboard insight page isn't set up yet

**Comment by paolodamico** [comment]
We can now edit this!
