### ISSUE TITLE
docker-compose down causes data loss

### ISSUE THREAD

**Issue by hgezim** [PostHog/posthog#2079]
## Bug description

Looks like the production docker-compose file doesn't map a local folder for database data and running `docker-compose down` removes the old installation.

I say this because when I do `docker-compose down` and `docker-compose up` it gives me the preflight screen.

## Expected behavior

`docker-compose down` should not cause data loss.

## How to reproduce

1. `docker-compse up -d`
2. Setup a instance
3. `docker-compose down`

## Environment

- PostHog cloud or self-managed? self-managed
- PostHog version/commit: commit 99e2f2e0d936bad1cb38549e569b80de82a9babf

**Comment by ciocan** [comment]
the same thing happens for docker-compose on the hobby deployment
