### ISSUE TITLE
Sales: PostHog pricing

### ISSUE THREAD

**Issue by jamesefhawkins** [PostHog/posthog#208]
We need to create a  clearer set of prices for PostHog's users (for people that want more than the Community Edition). We've seen evidence of confusion and have had issues with getting companies to use it through a lack of clarity.

# Background

We have focussed so far on growing our open source community and project. Our top priority is to maintain focus on making PostHog the standard thing any developer installs to get analytics on their new projects. That's why it's free.

However, we need to be able to give people starting out with the Free tier a clear view of how much it could eventually cost. That way, we can get users more comfortable with integrating our product deeply into their stack, which is what we need.

# Pricing thoughts

### Usage based pricing

* Traditionally, this reduces barriers to use because it eliminates up-front costs and allows organizations to increase the volume of traffic / events that flow through 
* Enterprise customers typically do not have budgets that work this way, and trying to estimate usage BEFORE having any analytics would create complexity in the sales cycle.
* There are many customers we've spoken with that already want to talk to us specifically because they don't like usage based pricing, based on events. For our self hosted option, a competitive advantage that PostHog has is that 
* For our hosted offering, we would need to at least limit usage because it has a cost associated with it.

### Per user pricing

* This reduces barriers to initial adoption, as a huge organization could easily have just 1 user sign up.
* It is the model used by Mattermost and Gitlab. These are both "team based" products though, where the scenario of ending up with just 1 user and friction to adding more users is less of an issue than it would be for PostHog. We need to think about how to make mass adoption easy for our customers.

### Per active user pricing

* This is how Slack prices. it involves giving everyone access, but only charging for those that use the product. This therefore makes it easy to give out access to more users, as it's zero cost to do so, unless they use it.

### Per feature pricing

* Larger organisations will value features (ie permissioning) that startups or single developers won't care about. Adding more features into a more expensive pricing tier makes it possible to extract this extra value, and keeps us aligned with providing value to all kinds of customers.

### Penetration pricing

We need to become a standard tool for developers as we create the category of open source product analytics. This requires mass adoption at the low end of the market, so we need to make barriers to adoption low.

### Captive pricing

PostHog can leverage captive pricing - if we get deeply embedded and proven in a customer's stack, then we can comfortably charge extra for more features, and the customer will already trust us and will see value in our product generally. We want to be selling based off goodwill, and this is another "inbound" way to sell.

### Prestige pricing

Pricing high to differentiate yourself as the market leader in terms of quality.

This is not an appropriate strategy for PostHog - we need individual developers AND enterprises to use us.

### Free trial pricing

This reduces friction in the sales cycle, enables us to speak to more customers to improve our learning and puts more pressure on the product, which is a good thing in the long run. This is a good strategy for PostHog for Hosted deployments.

For self-hosted, this would also be a good strategy, but we would need to create a way of "upgrading" your codebase to the Growth or Enterprise version to do this, so we should create a ticket.

### Cost plus pricing

This is designed to preserve margins. There is no need to do this for self hosted. For hosted, we would need to limit the event volumes because we will otherwise incur very large hosting bills. We should provide a very limited event volume for free in the lowest tier of hosted, as an easy way for clients to find us and try the software when they are smaller and more price sensitive.

### Value based pricing

This involves having some way of measuring value. A combination of functionality and the number of users is a good way to proxy for value.  We do not believe the volume of events is a good way to do this based on market feedback so far, and in fact could become a key selling point.

# Proposal

* Make the community edition free for unlimited users to capture more usage across more organizations. That will increase our learning and give us more companies that rely on us, which will improve the repos for both of those editions.
* We need to put more functionality into the Growth plan (the first one up). This should still be relatively inexpensive. A/B tests and UTM tags would be much more relevant to companies than tiny teams or developers, so they feel rational to put in without detracting noticeably from our community version. We should just charge per seat, with the theory being that we already have plenty of seats from having first implemented the Community version.
* We will leave the enterprise version to a 'set fee' depending on the level of support needed. Then we will speak to the organisation.

**Comment by jamesefhawkins** [comment]
@timgl and @Tannergoods , I'd appreciate your go / no go and reasoning on this approach please. The website pricing table is in draft mode in the meantime.

**Comment by timgl** [comment]
This sounds great. Only comment is it'll be hard/impossible to put UTM tags in a different plan, as they are just another property. However there are definitely other marketing things we could look at (like spend?).

It'd be good to compile a list of features you see in the Growth/Ultimate plan.

**Comment by Tannergoods** [comment]
I'm a go - agree that we should be compiling the list of features in the Growth plan specifically - I like the draft pricing table, this goes some way to showing this

**Comment by jamesefhawkins** [comment]
Thanks for reading through both. 

# UTM tags

Agreed with your point here @timgl . I think it feels wrong to exclude a certain property as you could just rename in the JS, so let's allow UTM tags throughout.

# Integrations with advertising channel spends 

We could bucket integrations with marketing channels pretty well - a hobbyist developer won't be spending on adwords any significant amount, so that's a great example of a feature that should be charged for.  However, I don't think we should focus on marketing-specific features in the short run either - we should work out how to do the more funky developer stuff really well once we have greater parity with the main 3rd party analtyics tools, first. If that means we end up with a bunch of free and a bunch of enterprise with little between the two, that's ok.


To dos:

- [ ] James to edit feature list 
- [ ] James to send pricing draft page to Tim/Aaron for QA pre-publishing it

**Comment by jamesefhawkins** [comment]
@Tannergoods  could you QA this please:

https://posthog.com/pricing/

It's live but I've not linked to it from the menus yet so it won't get significant traffic.

@timgl 

The pricing sign up flow could be better with some product changes, I've detailed here for future use:

https://github.com/PostHog/posthog/issues/213

With self hosted, I made it free and gave unlimited users as per the above for the free tier. The pricing value of $59/month is something I'd like feedback on.

With hosted, I have removed the price for now until we get more comfortable with what it costs to host. Then we can just put a number in - it's not urgent as hosted isn't our main focus. I also made hosted free for very limited event volumes, just so it's easy for people to start.

**Comment by Tannergoods** [comment]
@jamesefhawkins font size for Custom should be smaller imo.

Contact Sales - this should really be a route to emailing us rather than the sign-up page which doesn't offer any way of actually contacting us? My expectation is everyone will start with free in the first place - if they need the extra features they will expect contact details?

Features - A/B testing should be here - this is a large part of moving from the community edition to a paid plan - we have user roles, engagement scoring and retention tracking as "in development" we can surely do the same here?

**Comment by jamesefhawkins** [comment]
# Font size

Reducing the font size for 'custom' makes it look like a misplaced word versus the actual price. I could put the $ sign in front of it, but that looks ugly. This styling is very painful to manipulate due to how elementor works, so I want to move on for now.

# Contact sales

I realised that not all the 'contact sales' buttons took users to the place I had intended, so perhaps that's why you raised this. I've now updated that.

I have added a /contact/ page in the site's footer with our basic details, but I felt it looks a little "personal website-y" to take users to an email address and could be a flag to enterprise customers. I've put https://posthog.com/sales/ in place with a free message field so it's easy for someone to include what they want to say.

I was basing this on the approach taken by [Slack](https://slack.com/contact-sales) and [GitLab](https://about.gitlab.com/sales/).

That said, GitLab have done a nice job of putting an FAQ on this page to make it more helpful. I added a ticket #217 for this, but I won't prioritise it unless we get a few enquiries through first.

# Features

Thanks for this, I've updated the list quite extensively. Ab testing is on there, as are all the integrations, cohorts and user paths.

**Comment by jamesefhawkins** [comment]
Done
