### ISSUE TITLE
[Sales] Allow custom domain for hosted version

### ISSUE THREAD

**Issue by hgezim** [PostHog/posthog#2080]
I had to install posthog on AWS because I can't use my own domain when I used posthog cloud.

**Comment by paolodamico** [comment]
Hi @hgezim, thanks for the suggestion, we'll definitely explore it. Just to have all the context, what are your main reasons for wanting a custom domain over the default app.posthog.com?

**Comment by hgezim** [comment]
Main reason is I don't want to have potential issue with cross-origin cookies and ad blockers.

**Comment by paolodamico** [comment]
We've decided not to move forward with this and instead suggest self-hosted if there's ad blocker concerns. PostHog doesn't do third-party cookies anyways.
