### ISSUE TITLE
Mobile Replay Kilo Issue #2 🪨

### ISSUE THREAD

**Issue by pauldambra** [PostHog/posthog#20819]
One smaller than Mega is Kilo 🏋️

This issue acts as a tracking place of the to-do list to get Mobile replay ready for release

# getting real user feedback

We already had #19037 that tracked getting to the point we were happy getting real user feedback

now we want to get to the point where we release as an open beta

# Must have

- [x] how to release without charging @pauldambra 
- [x] WEB - add android instructions to `onboarding/session_replay?step=install`  @pauldambra 
- [x] WEB - add replay advert to `onboarding/product_analytics?step=install` for android  @pauldambra 
- [x] WEB - add replay advert to `onboarding/feature_flags?step=install` for android  @pauldambra 
- [x] RENDER - way nicer placeholders (keyboard and image, but we could use other OS actions like open camera too)  @pauldambra 
- [ ] WEB - quick filter for web/mobile replays in playback  @pauldambra 
- [ ] CAPTURE - RENDER - better default image capture/rendering? @marandaneto 
- [ ] CAPTURE - RENDER - better default background capture/rendering? @marandaneto 

# Nice to have

- [x] SDK - separate masking text and masking inputs @marandaneto 
- [x] CAPTURE - RENDER - how do we deal with custom components? @marandaneto @pauldambra  
- [ ] SDK - default to capturing images? @marandaneto 
-  [ ] CI - integration testing - we rely on the fact that we use replay for our websites for quick production feedback but we don't have an app - we can playback a recording in UI testing, pause at a known timestamp, switch to DOM explore, and assert on the state of the DOM 
- [ ] CAPTURE - RENDER - expanded supported components (e.g. calendar, scroll view)
- [x] CAPTURE - better "frame rate" for capture @marandaneto 
- [ ] WEB - authorized "domains" for folk with multiple apps
- [ ] WEB - Adjust the player layout for vertical mobile recordings, thus giving more screen space to events/logs/...
- [ ] CAPTURE - RENDER - WEB - Support custom fonts
- [ ] INGESTION - [prefer top level distinct id](https://github.com/PostHog/posthog/pull/18954)
- [ ] INGESTION - Make `$window_id` optional since it does not make sense for Mobile

# Push into the future

- supporting multiple modes of capture
    - e.g. maybe needed to support jetpack compose
- capture a webview as part of the same recording if posthog replay is installed in the app and the webview

# See also:

 * https://github.com/PostHog/posthog-android/pull/69
 * https://github.com/PostHog/posthog/issues/16792
 * https://github.com/PostHog/posthog/issues/13267
 * https://github.com/PostHog/posthog/issues/13269
 * https://github.com/PostHog/posthog/issues/12344
 * https://github.com/PostHog/posthog/issues/12054
 * https://github.com/PostHog/posthog/issues/16410
 * https://github.com/PostHog/posthog/issues/17803
 * https://github.com/PostHog/product-internal/issues/519

**Comment by pauldambra** [comment]
@marandaneto I started marking us against the items but then realised it was pretty obvious which was who 🙈

**Comment by marandaneto** [comment]
> SDK - separate masking text and masking inputs

You can use the [ph-no-capture](https://posthog.com/docs/session-replay/mobile#recording-specific-configuration)

**Comment by marandaneto** [comment]
>  CAPTURE - RENDER - how do we deal with custom components?

You can use the [drawableConverter](https://github.com/PostHog/posthog-android/blob/main/USAGE.md)

**Comment by marandaneto** [comment]
> SDK - default to capturing images?

The problem here is PII, we know they are images but not what they contain, this will be a bigger problem if we switch to the [screenshot mode](https://posthog.com/docs/session-replay/mobile#screenshot-mode), working on screenshot PII now.

**Comment by marandaneto** [comment]
> CAPTURE - better "frame rate" for capture

There were a few improvements, such as the debouncer with the [debouncerDelayMs](https://posthog.com/docs/session-replay/mobile#recording-specific-configuration) config.

**Comment by marandaneto** [comment]
Closing in favor of
https://github.com/PostHog/posthog/issues/23275
https://github.com/PostHog/posthog/issues/23276
https://github.com/PostHog/posthog/issues/23277
Most of the other tasks were done or not prioritized, for now, we can always go back and decide to raise new issues for the other ones, let's focus on getting Mobile session replay stable and out of GA and improving based on user's feedback first.
