### ISSUE TITLE
Toolbar not loading NextJs

### ISSUE THREAD

**Issue by AarooneyFarr** [PostHog/posthog#20876]
## Bug description

Toolbar not loading for some reason.

*Please describe.*  
*If this affects the front-end, screenshots would be of great help.*  

Pretty new to postHog, so not sure what info would be helpful. The toolbar is not loading on prod or local dev. I am using NextJs with Vercel, and have configured the rewrites as the tutorials show in the docs. I have found an error in the network inspector that may be helpful.

<img width="1482" alt="Screenshot 2024-03-12 at 12 33 35 PM" src="https://github.com/PostHog/posthog/assets/21244790/6914bd63-30be-4209-b2cc-76971c7d7a54">

*If you are on PostHog Cloud it would be really valuable if you can share any links where the problem occurs. This speeds up our ability to troubleshoot tremendously.* 

## How to reproduce

1. Build and deploy NextJs app on Vercel
2. Follow posthog basic install instructions (with reverse-proxy)
3. See bug?

## Environment

- [x] PostHog Cloud US, project ID: [please provide from https://us.posthog.com/settings/project-details#variables]
- [ ] PostHog Cloud EU, project ID: [please provide from https://eu.posthog.com/settings/project-details#variables]
- [ ] PostHog Hobby self-hosted with `docker compose`, version/commit: [please provide]
- [ ] PostHog self-hosted with Kubernetes (deprecated, see ["Sunsetting Kubernetes support"](https://posthog.com/blog/sunsetting-helm-support-posthog)), version/commit: [please provide]

## Additional context

Brand new to posthog I have no idea what you guys need for diagnosing this. Please let me know what other information may be helpful
<img width="688" alt="Screenshot 2024-03-12 at 12 46 15 PM" src="https://github.com/PostHog/posthog/assets/21244790/cab08528-f832-48c9-b461-e8bb98b210a0">

I removed the reverse proxy, and the new 404 looks like this:
<img width="815" alt="Screenshot 2024-03-12 at 12 52 56 PM" src="https://github.com/PostHog/posthog/assets/21244790/a0d68b00-b279-4eec-b8b0-56efc2478000">

After adjusting some of the routing settings and adding the debug flag, I found more error info.
![Screenshot 2024-03-12 at 11 39 55 PM](https://github.com/PostHog/posthog/assets/21244790/ca650ca7-72b9-4892-9e2b-a1a17fde721c)
![Screenshot 2024-03-12 at 11 41 41 PM](https://github.com/PostHog/posthog/assets/21244790/82be3308-14ec-487b-a0d1-3953ad16d887)

# This is working for me now

 _I cannot edit/close this bug, but after banging my head on this all day yesterday to no success, I tried again this morning without changing anything and it worked. I honestly don't know what changed, but if anyone hits similar issues in the future I would be happy to at least describe some of the structure adjustments that I had to make from the default docs tutorial._

**Comment by MarconLP** [comment]
this has been fixed in https://github.com/PostHog/posthog/pull/20892
