### ISSUE TITLE
Session replay onboarding config not saving

### ISSUE THREAD

**Issue by zlwaterfield** [PostHog/posthog#20895]
## Bug description

While working on this PR (https://github.com/PostHog/posthog/pull/20870) I noticed that the session replay onboarding config step was not saving the options (it is working for other products like product analytics).

![Screenshot 2024-03-13 at 9 14 20 AM](https://github.com/PostHog/posthog/assets/6392501/945e9fba-6611-4194-b661-ed0a94006e95)

There is also an issue with the `Minimum session duration (seconds)` select (behind a feature flag). When changing the value it resets the other values.

## How to reproduce

1. Go to https://us.posthog.com/project/{projectId}/onboarding/session_replay?step=configure
2. Toggle one of the options to off.
3. Click next
4. Refresh
5. Go back to step one and see if it save

**Comment by zlwaterfield** [comment]
Ok no problem, I can look at the commit history and try to get to the bottom of it.

**Comment by pauldambra** [comment]
feel free to hassle us if helpful :)

**Comment by zlwaterfield** [comment]
Fixed
