### ISSUE TITLE
App feels broken after a fresh install

### ISSUE THREAD

**Issue by mariusandra** [PostHog/posthog#2091]
## Bug description

There should be more empty states or something:

![2020-10-29 09 07 28](https://user-images.githubusercontent.com/53387/97542001-54b06f00-19c6-11eb-9143-a9eb79a5e466.gif)

**Comment by timgl** [comment]
This is after you've skipped sending your first event presumably?

**Comment by paolodamico** [comment]
Related to this, an interesting but painful [recording](https://app.posthog.com/sessions/play?id=176111a6a17832-0e5ce3d13c84658-3e62694b-fa000-176111a6a18fda), a user going through the sign up process and then trying to find PostHog's value (worth noting they wanted to use session recording & plugins). For me the biggest thing is that it seems we're still having a hard time communicating our value prop right after sign up (as it wasn't prioritized in release 19, might be worth considering as a Hackaton project for 20, or maybe a first task for the growth engineer?), the user literally went through almost every page but didn't actually do any _aha moment_ stuff. Seems like we need significantly better feature onboardings and empty states.

**Comment by paolodamico** [comment]
+1 from [customer feedback](https://docs.google.com/document/d/1gJlsUDrlW7ur8zT5scqRvXZhapm_0JdvKGiw68Iyx9E/edit#heading=h.gha2owsw3eb7) to prioritize this soon

**Comment by EDsCODE** [comment]
various onboarding experiments going on so i will close this
