### ISSUE TITLE
Deleting a group in cohort multiples the OR

### ISSUE THREAD

**Issue by EDsCODE** [PostHog/posthog#2093]
## Bug description

*Please describe.*  
If you have a cohort and want to delete some of the groups to update the cohort, a bunch of ORs are left and it's very glitchy
*If this affects the front-end, screenshots would be of great help.*  
<img width="744" alt="Screen Shot 2020-10-29 at 9 44 37 AM" src="https://user-images.githubusercontent.com/13127476/97545578-9d096600-19a1-11eb-991a-14416ca504d1.png">

## Expected behavior
If you delete a group that's above another, it should just disappear as expected and move the rest of the groups under it up

## How to reproduce

1. Go to a cohort with multiple groups
2. Delete the top most group
3. 

## Environment

- PostHog cloud or self-managed?
- PostHog version/commit

**Comment by yakkomajuri** [comment]
Also every new group creates an `OR` on top as well
