### ISSUE TITLE
Too many distinct_ids

### ISSUE THREAD

**Issue by EDsCODE** [PostHog/posthog#2094]
## Bug description

*Please describe.*  
When a user has a lot of distinct_ids, it could get ugly. 
*If this affects the front-end, screenshots would be of great help.*  
Viewing window at 33% and these are my distinct_ids
<img width="639" alt="Screen Shot 2020-10-29 at 10 06 20 AM" src="https://user-images.githubusercontent.com/13127476/97547717-86b0d980-19a4-11eb-826d-971c9e3faef1.png">

## Expected behavior
Should only show the first 3 distinct ids. If there are more than three, show a link that says "x distinct ids hidden. Click to show." When clicked, it should show all distinct ids.

## How to reproduce

1. Go look at profile for my email
2. 
3. 

## Environment

- PostHog cloud or self-managed?
- PostHog version/commit

**Comment by GalDayan** [comment]
I'll take it
