### ISSUE TITLE
Self-hosted installation: the replay player displays eternal buffering.

### ISSUE THREAD

**Issue by AndrewK98** [PostHog/posthog#20947]
## Bug description
Replays become impossible less than 24 hours after recording. The replay player displays eternal buffering.

## How to reproduce

1. Following https://posthog.com/docs/self-host I am deploying a self host on my Ubuntu 22 server.
2. I'm starting to collect replays from my react application.
3. The replays are recorded and I can go in and watch them.
4. Several hours pass (about 18 in my case), I go to check the replays, and when I select any of them I only see “buffering...”. I don't see any errors inside the containers.
5. If I try to scroll through a recording, I immediately get the error “We cannot play this recording.”

## Environment
- Ubuntu 22
- PostHog Hobby self-hosted with `docker compose`, version/commit: latest (1.43.1)

## Additional context
![image](https://github.com/PostHog/posthog/assets/38350097/7a829fe3-9ff7-4acf-a2f7-1890fff5e0a7)
![image](https://github.com/PostHog/posthog/assets/38350097/987cbfdc-77fd-4ad7-96bc-225c1ea2dcc6)
![image](https://github.com/PostHog/posthog/assets/38350097/30415c16-7a52-4c8c-ab94-a246de8b2178)
![image](https://github.com/PostHog/posthog/assets/38350097/6b851f36-4c67-4750-bd59-c432396cb9f5)

**Comment by victor-yunenko** [comment]
Can confirm, I've been search the internet and found this ticket. And I'm running the 2 days old version from docker.

**Comment by feedanal** [comment]
@pauldambra , any advice on how to enable storage? I've added to `docker-compise.yml`
```yml
    plugins:
        environment:
            OBJECT_STORAGE_ENDPOINT: objectstorage:19000
            OBJECT_STORAGE_ENABLED: true
```

Did not help. Some users left "breadcrumbs" of similar nature (https://posthog.com/questions/session-recordings-cannot-be-played-back) but no clarity. Docs mention nothing (getting used to it), and from the source code it's unobvious where object storage can be enabled from.

**Comment by pauldambra** [comment]
the default config from environment variables is

```
        OBJECT_STORAGE_ENABLED: true,
        OBJECT_STORAGE_ENDPOINT: 'http://localhost:19000',
        OBJECT_STORAGE_REGION: 'us-east-1',
        OBJECT_STORAGE_ACCESS_KEY_ID: 'object_storage_root_user',
        OBJECT_STORAGE_SECRET_ACCESS_KEY: 'object_storage_root_password',
        OBJECT_STORAGE_BUCKET: 'posthog',
```

from https://github.com/PostHog/posthog/blob/c2a5d6162ab9cf36d2c1101817480f4223d1310d/plugin-server/src/config/config.ts#L115-L120

I don't use the self-host image but in local dev run `docker compose -f docker-compose.dev.yml up -d` and with that config replay works as expected

**Comment by feedanal** [comment]
This explains why in self-hosted recordings stop working -- MinIO ports are not exposed on localhost, like they are exposed in dev image:

https://github.com/PostHog/posthog/blob/c72f8dc76b62b969c51df6a4256626947a231df3/docker-compose.dev.yml#L86-L88
