### ISSUE TITLE
[session recording] Inactive periods don't get skipped.

### ISSUE THREAD

**Issue by timgl** [PostHog/posthog#2096]
## Bug description

When playing a session, it doesn't seem to skip inactive period very well, forcing you to click around to find the point at which  the user does something again

## Expected behavior

It should skip inactive periods

## How to reproduce

1. 
2. 
3. 

## Environment

- PostHog cloud or self-managed?
- PostHog version/commit

**Comment by macobo** [comment]
Not something we can do something about immediately as this part is implemented by https://github.com/rrweb-io/rrweb-player / rrweb/Replayer.

However we could dig in a bit and see if we can fix this upstream as this comes up relatively commonly.

**Comment by macobo** [comment]
The new player should indicate inactive periods much nicer which I think solves this issue. Let me know if not!

Note that there might be some fuzzyness there if user is 'inactive' but moves the mouse a tiny bit which is not considered as inactive by rrweb.
