### ISSUE TITLE
Filter selector using "matches regex" or "contains" not working initially

### ISSUE THREAD

**Issue by santidalmasso** [PostHog/posthog#20987]
## Bug description

The filter selector for filtering by URL using "matches regex" or "contains" does not work properly when first selecting the filter. No results are shown because the value is sent as an array instead of a string[].

## How to reproduce

1. Create an Insight for Page count
2. Add a filter for URL using "matches regex" or "contains". Notice no results are returned.
3. Change the filter to "doesn't equal", then change it back to "matches regex". The filter should now return results properly.

https://github.com/PostHog/posthog/assets/36210359/32ca8fb0-917b-4a15-9977-ba29915891ca

## Environment

- [X] PostHog Cloud US, project ID: [22865]
- [ ] PostHog Cloud EU, project ID: [please provide from https://eu.posthog.com/settings/project-details#variables]
- [ ] PostHog Hobby self-hosted with `docker compose`, version/commit: [please provide]
- [ ] PostHog self-hosted with Kubernetes (deprecated, see ["Sunsetting Kubernetes support"](https://posthog.com/blog/sunsetting-helm-support-posthog)), version/commit: [please provide]

**Comment by MarconLP** [comment]
+1 https://posthoghelp.zendesk.com/agent/tickets/11836 (moved to PostHog: https://us.posthog.com/project/2/support/tickets/14027)

**Comment by MarconLP** [comment]
+1 https://posthoghelp.zendesk.com/agent/tickets/11852 (moved to PostHog: https://us.posthog.com/project/2/support/tickets/14032)

**Comment by mortenjust** [comment]
Also seeing this

1. Create a page view report and break it down by path name
2. All path names are broken down
3. Remove the breakdown
4. Add a filter to the Page View event: path name contains [one of the broken down path names from before]

Actual: There are no matching events for this query 
Expected: The same value as the broken down value for that path name

**Comment by MarconLP** [comment]
+1 https://posthoghelp.zendesk.com/agent/tickets/11835 (moved to PostHog: https://us.posthog.com/project/2/support/tickets/14682)

**Comment by benjackwhite** [comment]
Sorry about this! Fix coming up.
