### ISSUE TITLE
Demo data isn't being ingested

### ISSUE THREAD

**Issue by EDsCODE** [PostHog/posthog#2098]
## Bug description

*Please describe.*  
- when running clickhouse locally from docker deployment, it seems like ingestion has stopped working. going to /demo generates the data still but it doesn't end up in the clickhouse table.

Extra notes:
I checked the `clickhouse_events_proto` topic and events show up there but can't seem to find where it breaks

## Expected behavior
Demo data should be ingested

## How to reproduce

1. Deploy fresh docker instance using ee config with clickhouse
2. Go to /demo to populate data

## Environment

- PostHog cloud or self-managed?
- PostHog version/commit

**Comment by fuziontech** [comment]
when running locally are you running it with `KAFKA_ENABLED`?

**Comment by fuziontech** [comment]
upgraded to 20.10.xx
