### ISSUE TITLE
Personless events ingestion

### ISSUE THREAD

**Issue by tiina303** [PostHog/posthog#21000]
This would help 
1. web analytics ingestion to be a lot cheaper
2. users who need to send anonymous backend events without causing problems with sending too many events for a single distinct_id

**Comment by jasondainter** [comment]
I think this related the post I made in the forum today at https://posthog.com/questions/stopping-internal-user-data-not-filtering

Would be great to see this but in the mean time do I understand correct I could just write some logic to filter out the trackers on my side to avoid loading the tracker at all for certain users (localhost, admins etc). Would there be any complications with that?

**Comment by tiina303** [comment]
It's unrelated to your question.
