### ISSUE TITLE
`ReferenceError: FEATURE_FLAGS is not defined` error in the cloud app

### ISSUE THREAD

**Issue by amyc92** [PostHog/posthog#21014]
## Bug description

I created a new account on the free tier and did some testing with the default project. I then deleted the project and created a new one. 

I am now stuck in the onboarding flow for the new project with a `ReferenceError: FEATURE_FLAGS is not defined` error showing on every page 

<img width="1512" alt="Screenshot 2024-03-19 at 16 53 09" src="https://github.com/PostHog/posthog/assets/13842416/e938581a-594a-44fd-9b44-0871aef58122">

## How to reproduce

1. Create new free cloud account
2. Ingest some events/session data into the default project
3. Delete existing project
4. Create new project
5. Click `Product analytics` for the new project

## Environment

- [ ] PostHog Cloud US, project ID: [please provide from https://us.posthog.com/settings/project-details#variables]
- [x] PostHog Cloud EU, project ID: 18467
- [ ] PostHog Hobby self-hosted with `docker compose`, version/commit: [please provide]
- [ ] PostHog self-hosted with Kubernetes (deprecated, see ["Sunsetting Kubernetes support"](https://posthog.com/blog/sunsetting-helm-support-posthog)), version/commit: [please provide]

**Comment by pauldambra** [comment]
Hey @amyc92 

Sorry about that! And thanks for letting us know. Coincidentally we've just merged a fix for this here https://github.com/PostHog/posthog/pull/21010

So things should be working again shortly. It might take another 30 minutes for the deploy to roll out completely

**Comment by amyc92** [comment]
hi @pauldambra, 

great thanks, all seems to be working now!
