### ISSUE TITLE
[Clickhouse] Optimize sessions query

### ISSUE THREAD

**Issue by timgl** [PostHog/posthog#2101]
Right now for a certain large user the session query immediately exits as it would use too much memory: https://sentry.io/organizations/posthog/issues/1948352457/?project=1899813&query=is%3Aunresolved

**Comment by timgl** [comment]
The specific issue is solves but SuprDaily still can't have average session duration etc, so we do need to look into that.

My gut feel is for average duration we can just do some sampling, but for total # of sessions I don't have a good idea yet

**Comment by paolodamico** [comment]
There's no longer a session query.
