### ISSUE TITLE
Sessions still being recorded after opt out

### ISSUE THREAD

**Issue by yakkomajuri** [PostHog/posthog#2103]
## Bug description

*Please describe.*  
*If this affects the front-end, screenshots would be of great help.*  

This is a posthog-js issue but won't really get visibility there, and I'll add it to the bug squashing project.

This is quite bad:

<img width="600" alt="Screenshot 2020-10-29 at 12 05 14" src="https://user-images.githubusercontent.com/38760734/97569163-17a4a680-19df-11eb-8e63-bef2f412913a.png">

## Expected behavior

Sessions shouldn't be recorded for people who opt out of capturing

## How to reproduce

1. Opt out
2. Be recorded

**Comment by macobo** [comment]
@yakkomajuri are you able to reproduce this or https://github.com/PostHog/posthog-js/issues/101 anymore? There are tests in place to at least avoid this.

**Comment by Twixes** [comment]
Is this still the case?
