### ISSUE TITLE
Changing the period in the retention table causes a confusing default date range to get selected

### ISSUE THREAD

**Issue by jamesefhawkins** [PostHog/posthog#2104]
## Bug description

* Load retention view
* Change period from the default 'daily' to 'monthly' (or anything else)
* It then shows ie this month, *next* month, *the month after that*, all of which have no data as they haven't happened yet

![Screenshot 2020-10-29 at 12 06 39](https://user-images.githubusercontent.com/47497682/97571212-a285a100-19df-11eb-9f35-4e5835b28836.png)

## Expected behavior

On changing the period, it should default to this period, and all the periods historically leading up to it at least to fill out the default 11 rows.

**Comment by timgl** [comment]
Yep, the start day should actually be the last day, and when changing the "period" it should automatically be set to that date (or today). Also, while you're at it, changing dates makes all the other filters disappear

**Comment by paolodamico** [comment]
Related to #1995.

**Comment by EDsCODE** [comment]
addressed
