### ISSUE TITLE
Team Replay Q2 2024 Mega Issue 👩‍🎤 

### ISSUE THREAD

**Issue by pauldambra** [PostHog/posthog#21078]
# Team Replay Q2 2024 Mega Issue 👨‍🎤

Previously on the Megaissue: 

* https://github.com/PostHog/posthog/issues/19327
* https://github.com/PostHog/posthog/issues/17803
* https://github.com/PostHog/posthog/issues/16287
* https://github.com/PostHog/product-internal/issues/456 
* https://github.com/PostHog/posthog/issues/13393 
* https://github.com/PostHog/product-internal/issues/354

This is designed to be a focus point to link together what we plan to do, feedback on that plan and progress as we go forward.

It is **not** meant to be discussion about individual features. As soon as the discussion starts a dedicated feature issue should be created, added to the roadmap and discussed there.

internal planning discussion https://docs.google.com/document/d/1KPbzKycidBiPCUwAdzGXO4PhBOe-vDbflULS6z3OKgY/edit#heading=h.tk197aketupu

# 🎯 Goal 1: Quality and Consolidation for Session Replay (web & mobile)

#### Why? 

We've done a lot of investigation and preparation work and we want to capitalize on that

## Mobile replay out of beta for Android/iOS @marandaneto 
- [ ] https://github.com/PostHog/posthog/issues/20819
- [x] Do the usage reporting changes so we count mobile and replay separately
- [X] [Filtering recordings by source](https://github.com/PostHog/posthog/pull/23055)
- [x] Add source to recording viewed and recording analysed events
- [x] add replay prompt to android onboarding
    - [x] and turn that flag on so people see it
- [ ] ??

## Make capture and playback as complete, performant and easy as possible @pauldambra 
- [ ] we have a list of improvements and fixes that we know will help users
    - [ ] [Improve CSS in JS support](https://github.com/PostHog/posthog/issues/18520) @daibhin 
    - [x] https://github.com/PostHog/posthog-js/issues/1065
    - [ ] https://github.com/PostHog/posthog-js/issues/1100
    - [ ] https://github.com/PostHog/posthog-js/issues/1101
- [ ] we want to make som new use-cases possible
    - [ ] https://github.com/PostHog/posthog-js/issues/1099 
    - [ ] this persistent queue would allow
        - [ ] not losing data when large minimum duration is selected
        - [ ] having a rolling buffer and only emitting recordings to the backend on manual trigger
- [ ] we let people capture 24 hour recordings, and we don't aggressively limit overall amount of data ingested per recording
    - [ ]  this means it is possible to ingest very large recordings which we play back poorly because of strain on the browser
    - [ ] it should be possible to play every recording we let you ingest

### Must Do
- [ ] #22054
    - Improves performance & correctness of queries
    - Allows use of NLP filtering being built by Product Analytics
    - Unlocks AND / OR filtering
- [ ] UI simplification
    - Remove duplicate information in sidebar list and video header
    - Work with @corywatilo on 3000-ification
- [ ] Error clustering
    - Productionize background generation tasks
    - Ephemeral playlists

### Should Do
- [ ] Common filters
    - Preset saved filters for the most common actions
- [ ] Queryable network data
- [ ] [Fix memory leaks](https://posthoghelp.zendesk.com/agent/tickets/10318)

### Could Do
- [ ] Static playlists
    - Move "dynamic playlists" to be saved filters 
    - Only allow pinning to playlists
- [ ] Funnel based filtering
    - Watch recordings from one event to another (start playback at event timestamp)
    - Filter based on most common events / funnels. And show their correlated actions
- [ ] Engagement / Frustration scores

# 🎯 Goal 2: Error tracking MVP

Why? PostHog is "The single platform to analyze, test, observe, and deploy new features". Having network timings, network payloads, and console errors in Session Replay is a great developer tool. We want to learn by doing to understand how we could capture and expose even more information here to help people dig into what is happening with their products

- [x] complete the RFC at https://github.com/PostHog/product-internal/pull/589 - @pauldambra 
- [ ] Error tracking running for PostHog team
- [ ] investigate 
	- [ ] querying, 
	- [ ] grouping, 
	- [ ] and stack trace de-mangling

**Comment by pauldambra** [comment]
linked to https://github.com/PostHog/posthog/issues/20999

**Comment by marandaneto** [comment]
Error tracking MVP relates to https://github.com/PostHog/posthog/issues/15691

**Comment by pauldambra** [comment]
it's soon no longer Q2
