### ISSUE TITLE
Broken session replay recordings with SvelteKit app

### ISSUE THREAD

**Issue by captchafree** [PostHog/posthog#21100]
## Bug description

*Please describe.*  
*If this affects the front-end, screenshots would be of great help.*  

When we enable session replay and capture recordings of our SvelteKit app, the styles aren't loaded properly. It seems to only happen when navigating via client side routing, and only on certain pages of our app. Our users see the correct styles - only the recording is broken.

*If you are on PostHog Cloud it would be really valuable if you can share any links where the problem occurs. This speeds up our ability to troubleshoot tremendously.* 

Example of a broken recording: https://us.posthog.com/project/59074/replay/018e5dfc-e278-7d45-a556-649b1a2d6e78

## How to reproduce

1. Enable session replay for a SvelteKit application
2. Load a page, then navigate to a different one via client side routing

## Environment

- [x] PostHog Cloud US, project ID: 59074
- [ ] PostHog Cloud EU, project ID: [please provide from https://eu.posthog.com/settings/project-details#variables]
- [ ] PostHog Hobby self-hosted with `docker compose`, version/commit: [please provide]
- [ ] PostHog self-hosted with Kubernetes (deprecated, see ["Sunsetting Kubernetes support"](https://posthog.com/blog/sunsetting-helm-support-posthog)), version/commit: [please provide]

## Additional context

- SvelteKit app hosted on Vercel
- When session replay is enabled, our Vercel logs are flooded with `404` errors. I can't post the full logs here, but the framework specific part is `_app/immutable/assets/<css_file_name>.css status=404`
- The only posthog code in our app is that outlined in [this post](https://posthog.com/tutorials/svelte-analytics#capturing-pageviews-and-pageleaves)

**Comment by loris007** [comment]
I have the exact same issue, also using SvelteKit, and it only happens after client-side navigation.

In my case, the session recorder tries to load the CSS from the wrong path:
`/analytics/_app/immutable/assets/bubu.css` instead of `/_app/immutable/assets/bubu.css`

`analytics` is the subpath where my main app and the navigation are located, but it's not the app root.

I'm using Express, and as a workaround, I've now added a redirect rule that solves the issue.
```
app.use('/analytics/_app', (req, res) => {
    const newPath = req.originalUrl.replace(/^\/analytics\/_app/, '/_app');
    res.redirect(301, newPath);
});
```

**Comment by marandaneto** [comment]
https://github.com/PostHog/posthog/issues/17985 also SvelteKit but not sure if any related

**Comment by pauldambra** [comment]
we've had a number of CSS capture improvements... i'll close this, but feel free to re-open if it's still happening for you

(i'll definitely ask you to update to latest and share some example recording URLs if you do :))
