### ISSUE TITLE
Dashboard: Export to .png, image is cut off / incomplete

### ISSUE THREAD

**Issue by slshults** [PostHog/posthog#21135]
## Bug description

*Please describe.*  
Exporting the Dashboard to a .png results in an incomplete image, cut off at the bottom:

![export-bwd-analytics-for-webpage](https://github.com/PostHog/posthog/assets/227448/718e5eea-c5b7-493f-bb9d-eac03f9ed06c)

From: https://eu.posthog.com/project/10183/dashboard/40065

## How to reproduce

1. Click `Dashboard` in left sidebar
2. Click on the name of an existing Dashboard
3. Click on the `...` more options icon (to the right of the breadcrumb path and Dashboard name)
4. Click `Export`
5. Click `.png`
6. Download the resulting image
7. View the image, note that it's incomplete at the bottom

## Additional context

https://posthoghelp.zendesk.com/agent/tickets/11974

**Comment by slshults** [comment]
+1 https://posthoghelp.zendesk.com/agent/tickets/12825 (moved to PostHog: https://us.posthog.com/project/2/support/tickets/15498)

**Comment by bronze** [comment]
Same here. Tested on both firefox and chrome, the screenshot comes out cut off.
![export-my-app-dashboard](https://github.com/PostHog/posthog/assets/170220/451a0434-a599-418c-8ce1-3ff14dd5b4d7)
