### ISSUE TITLE
Filters not shown when editting an "insight"

### ISSUE THREAD

**Issue by morganhenry** [PostHog/posthog#21140]
## Bug description

I created a custom insight.

But now when I edit the insight the filter details are not shown.

![image](https://github.com/PostHog/posthog/assets/3432249/91ec812e-7d77-46d4-a40f-3e6bf9c1e386)

This one was created as a "match -Current URL- contains https://dah.dah/dah/" with group by URL.

The "Logged in users" seems to be have been added automatically by the Dashboard option
![image](https://github.com/PostHog/posthog/assets/3432249/68a6dead-b2a8-4534-b1dc-b4f5f1d10e2a)

Our home dashboard:
https://us.posthog.com/project/48104

## How to reproduce

1.  create an insight
2. add it to a dashboard
3. add a dashboard filter "logged in users"
4. edit the insight
5. observe that you can't see the filters you created

## Environment
https://us.posthog.com/project/48104

**Comment by webjunkie** [comment]
We recently improved the dashboard filtering logic. Please check if this addresses your issue. Let us know if there is still something not working for you.
