### ISSUE TITLE
The Posthog website appears to be down

### ISSUE THREAD

**Issue by zakbenney** [PostHog/posthog#21162]
## Bug description

The Posthog website is producing a 'took too long to respond' message.

## How to reproduce

1. I am searching for something in the handbook

**Comment by benjackwhite** [comment]
Doesn't seem to be down (you can even check the status page here which pings the website regularly https://status.posthog.com/) 

Can you check your browser network tab - its possible an over-eager tracking blocker is forcefully blocking our site.

**Comment by zakbenney** [comment]
Apologies for the false alarm! Clearly something wrong with our office IP as everyone was experiencing the same issue!
