### ISSUE TITLE
Library request: integrate with Kotlin

### ISSUE THREAD

**Issue by jamesefhawkins** [PostHog/posthog#212]
**Is your feature request related to a problem? Please describe.**

From a user:

> Could someone do a PR for a Kotlin library?

[Kotlin](https://github.com/JetBrains/kotlin) has ~30K stars and ~350 contributors. It is a popular language for developing Android apps.

By providing a Kotlin library, it'd be very easy for developers using it to track their product usage with PostHog.

**Describe the solution you'd like**
A library similar for Kotlin similar to eg the Go one we have in the [PostHog list](https://github.com/PostHog).

**Describe alternatives you've considered**
Use the [PostHog API](https://github.com/PostHog/posthog/wiki/API).

**Comment by pauldambra** [comment]
We have a Java library now https://github.com/PostHog/posthog-java

While Kotlin is IMHO nicer than Java :) You can [consume posthog-java from a kotlin application. ](https://kotlinlang.org/docs/java-interop.html)

Can we consider this closed @jamesefhawkins? Or does this become an issue to document how to use posthg-java from Kotlin?

**Comment by jamesefhawkins** [comment]
Retro issue bonus!
