### ISSUE TITLE
If funnel is empty, people still appear

### ISSUE THREAD

**Issue by EDsCODE** [PostHog/posthog#2121]
## Bug description

*Please describe.*  
- clickhouse funnel view returns people even if there are no events logged
*If this affects the front-end, screenshots would be of great help.*  

## Expected behavior

people should be empty too

## How to reproduce

1.  go funnels with clickhouse enabled
2.  click on an event that has 0 count

## Environment

- PostHog cloud or self-managed?
- PostHog version/commit

**Comment by macobo** [comment]
@EDsCODE Couldn't find a query to repro this - do you have one?

**Comment by EDsCODE** [comment]
Resolved with new funnel format
