### ISSUE TITLE
Slack subscription on an insight stopped working

### ISSUE THREAD

**Issue by arjunattam** [PostHog/posthog#21247]
## Bug description

I have a subscription that's configured on an insight. This subscription sends a screenshot of the insight to a slack channel once a day. The subscription was working until a few days ago, and we made no changes to Posthog or Slack during this period.

Link to insight: https://us.posthog.com/project/55960/insights/vQsdZ6yo

## Environment

- [x] PostHog Cloud US, project ID: 55960

**Comment by MarconLP** [comment]
+1 https://posthoghelp.zendesk.com/agent/tickets/12208 (moved to PostHog: https://us.posthog.com/project/2/support/tickets/14412)

**Comment by MarconLP** [comment]
+1 https://posthoghelp.zendesk.com/agent/tickets/12296 (moved to PostHog: https://us.posthog.com/project/2/support/tickets/14996)

**Comment by MarconLP** [comment]
The subscriptions should back!

**Comment by arjunattam** [comment]
Thanks, the subscription messages are back, but the screenshot of the insight is off by a bit. ~1/8th of the screenshot is cropped from the bottom

**Comment by MarconLP** [comment]
That issue is currently being tracked here: https://github.com/PostHog/posthog/issues/21414
