### ISSUE TITLE
ActorsModal broken in the lifecycle insight

### ISSUE THREAD

**Issue by MarconLP** [PostHog/posthog#21257]
## Bug description

ActorsModal broken in the lifecycle insight
![2024-04-01 at 18 15 00](https://github.com/PostHog/posthog/assets/13001502/e8a5fd6d-2d5d-49ed-8710-94b16b036029)

## How to reproduce

1. Create a lifecycle insight
2. Click on a segment to try and view the users there
3. See an error

## Additional context

https://posthoghelp.zendesk.com/agent/tickets/12160

**Comment by MarconLP** [comment]
This is an issue with the HogQL version of lifecycles. We'll look into a fix, but we can turn off the flag if it's urgent.

**Comment by sleexyz** [comment]
<img width="1610" alt="image" src="https://github.com/PostHog/posthog/assets/1505617/65f5242b-6854-4220-aeef-cdd2ff4a5894">
Please fix, running into the same issue. Get the issue every time I click "Click to view people"

**Comment by slshults** [comment]
+ 1 https://posthoghelp.zendesk.com/agent/tickets/10539 (moved to PostHog: https://us.posthog.com/project/2/support/tickets/14957)
