### ISSUE TITLE
Full list when showing a breakdown

### ISSUE THREAD

**Issue by zakbenney** [PostHog/posthog#21268]
## Is your feature request related to a problem?

Yes, I am unable to see a full list of values when creating a breakdown. It seems to limit the results by the most popular results during the timeframe I am checking for

## Describe the solution you'd like

I'm looking to see a breakdown of conversion from viewing one of our blog posts to then clicking on the pricing page. At the moment, the breakdown is not showing all the blog posts that I know exist from the period, even though when I specify to see results from the missing example the data is there. I have tried changing the breakdown limit but that doesn't seem to help. When exporting, the issue persists. Basically, I would like to see a full list of results, so that I can compare performance across blog posts.

Any thoughts?

**Comment by MarconLP** [comment]
Hey @zakbenney, by default we will only show the 25 most popular breakdown items. You can increase this limit under the breakdown settings.
![2024-04-08 at 22 35 23@2x](https://github.com/PostHog/posthog/assets/13001502/63c61f10-d3da-4671-977e-11a046dc066d)
