### ISSUE TITLE
Show information about the user/session with the session replay

### ISSUE THREAD

**Issue by macobo** [PostHog/posthog#2127]
## Is your feature request related to a problem?

Currently, session replay looks something like this:

![Screenshot from 2020-10-30 11-41-12](https://user-images.githubusercontent.com/148820/97689849-d8408d80-1aa4-11eb-93b3-367d56191ecc.png)

## Describe the solution you'd like

There's a lot of space here to expose useful information about the user, e.g. their distinct_id, user properties or more.

The open question is what sort of information would be useful to show here? 

## Additional context

If you have ideas, please share them!

cc @mariusandra @paolodamico

**Comment by yakkomajuri** [comment]
Painful view of the website!

**Comment by macobo** [comment]
Input from @ukupat, @andrestaht: It'd be nice to see user name + country + user properties on the session.

Screenshot from livesession:
![Screenshot from 2020-10-30 12-28-50-2](https://user-images.githubusercontent.com/148820/97695572-f1e5d300-1aac-11eb-8126-62c55f1ec1e1.png)

**Comment by yakkomajuri** [comment]
> The open question is what sort of information would be useful to show here?

Browser!

**Comment by mariusandra** [comment]
Here's a screenshot from another service:

<img width="1748" alt="Screenshot 2020-10-30 at 11 56 15" src="https://user-images.githubusercontent.com/53387/97697326-248ccd00-1aa7-11eb-99da-a3da325c0141.png">

I've found it useful to see the browser (with a nice little icon), if the user is mobile or not, the resolution, and the IP address (optionally with a country flag?). In addition to a custom user_id property I also often used the IP address to link sessions in this app with users in the backoffice.

This app also captures the HTTP requests, interactions and console messages and shows them in the sidepanel. Not sure if this is built in to rrweb or not, but in any case this would be cool to have as well, if we're going deep into this.

![image](https://user-images.githubusercontent.com/53387/97697642-9107cc00-1aa7-11eb-8564-1875e03a30ee.png)

**Comment by paolodamico** [comment]
This is pretty cool, I can work on a proposal for this next week based on this and we can discuss from that, if that works.

My raw thoughts are:
- We should definitely have some basic user info (email, name, first seen, ...) and some session info (browser, resolution, OS, device, geolocation, # of pages in the session, session duration).
- It'd be pretty cool to allow users to select certain person properties to show (e.g. some users would probably like to know if the person is paying or not, maybe company, engagement level, ...), but it's key here that we do this in a way that's straightforward to adjust, and not end up with a million
- I think showing the details on the actions (or timeline) can be super powerful provided we can capture data from different sources too (e.g. their backend, payment processors, exceptions handling etc.), however I don't think that just having a click history would be super useful. Maybe this is out of the scope of this issue as it would require a lot more work?

**Comment by paolodamico** [comment]
Closing this as we've already implemented part of this and the rest is documented on #2352
