### ISSUE TITLE
Updated company domain for our emails and now entire team is locked out of our Posthog

### ISSUE THREAD

**Issue by print-VarunSharma** [PostHog/posthog#21281]
## Bug description

We are using the Posthog hosted US instance, and we changed our domain for our company emails which has resulted in the entire team being locked out of posthog. Our old email alias is still active of course too.
For a while this did not affect us until the sign-out time hit and we had to re-authenticate our accounts.

This is a critical business issue as we can't get into our Posthog hog and it looks like we can't access the organization at all.

_Primary account email ve.sharma@adauris.ai_ 

## How to reproduce

1. Change company domain email 
2. Signout of posthog
3. Now locked out/cannot access the account as the email alias is not recognized

## Environment

- [x] PostHog Cloud US, project ID: [please provide from https://us.posthog.com/settings/project-details#variables]
- [ ] PostHog Cloud EU, project ID: [please provide from https://eu.posthog.com/settings/project-details#variables]
- [ ] PostHog Hobby self-hosted with `docker compose`, version/commit: [please provide]
- [ ] PostHog self-hosted with Kubernetes (deprecated, see ["Sunsetting Kubernetes support"](https://posthog.com/blog/sunsetting-helm-support-posthog)), version/commit: [please provide]

**Comment by MarconLP** [comment]
Hey @print-VarunSharma, I wasn't able to find any accounts with that specified email on our US Cloud.

**Comment by raquelmsmith** [comment]
Hi @print-VarunSharma - as this is an account-related question can you please email me (raquel@<thedomainyoudexpect>.com) and we'll get it sorted? Thanks!

**Comment by print-VarunSharma** [comment]
> Hi @print-VarunSharma - as this is an account-related question can you please open a support ticket so we can get this sorted?
> 
> https://us.posthog.com/login?next=%2F#panel=support%3Asupport%3A%3Alow

Yes can do right now! I just submitted the support ticket
