### ISSUE TITLE
Pricing page sign up flow

### ISSUE THREAD

**Issue by jamesefhawkins** [PostHog/posthog#213]
**Is your feature request related to a problem? Please describe.**
There are two main sets of tabs for our conversion flow on the website PostHog.com.

# Self hosted

We have three tiers:

* Free
  * Takes users to the GitHub repo to install the software
* Growth
  * Contact sales button, since we cannot have users self install the Growth repo yet
* Ultimate
  * Contact sales button, since we cannot have users self install the Ultimate repo yet

# Hosted

We have three tiers:

* Free
  * Takes users to app.posthog.com to create an account
* Growth
  * Contact sales button, since we cannot have users self serve the extra features yet
* Ultimate
  * Contact sales button, since we cannot have users self serve the extra features yet

**Describe the solution you'd like**

We should prioritise how this works for Self Hosted teams first.

* Self deploy the paid repo for growth
* Self deploy the paid repo for enterprise

Then we should make it possible for teams to use the hosted version. This should be in the form of a 30 day free trial. Regardless of the tier of trial chosen, we should let users click to upgrade themselves.

* Free, hosted - click to upgrade to ultimate at any time for 30 days
* Growth, hosted - click to upgrade to ultimate at any time for the remainder of the initial trial. If they are already a customer of growth, they should have a click to upgrade to ultimate at any time for a further 30 days.

This requires all the growth and ultimate features being possible to offer on our own hosting.

**Describe alternatives you've considered**
The alternative ('contact sales') then a manual setup is what we are currently doing.

**Comment by timgl** [comment]
Closing for now as we've done a new website, can re-open in that repo if necessary
