### ISSUE TITLE
Filter session recordings by Action(s)

### ISSUE THREAD

**Issue by macobo** [PostHog/posthog#2130]
## Is your feature request related to a problem?

When viewing session recordings, you often want to see recordings where user visited a certain page or clicked a certain button

## Describe the solution you'd like

- Allow filtering session **recordings** by actions.
- Jump to the relevant point in time in the recording
- Provide a shortcut from toolbar to "jump to see sessions who clicked this action".

## Describe alternatives you've considered

Using normal sessions page filters. This works but:
- Does not allow filtering by action
- Requires users to watch through recordings which might not be relevant

## Additional context

Idea stolen from livesession. Thanks for the input @ukupat, @andrestaht

**Comment by mariusandra** [comment]
> Provide a shortcut from toolbar to "jump to see sessions who clicked this action".

💯💯💯

Could also be extended to "clicked this element"

**Comment by Twixes** [comment]
This seems done along with #2595.
