### ISSUE TITLE
HogQL trends insights return only one result for an insight with formula broken down by multiple cohorts

### ISSUE THREAD

**Issue by thmsobrmlr** [PostHog/posthog#21326]
## Bug description

HogQL trends insights return only one result for an insight with formula broken down by multiple cohorts.

## How to reproduce

1. Create a new insight with two series
2. Add a formula e.g. `A + B`
3. Break down by multiple cohorts e.g. "All users" and "Real users"
4. Observe that there is only one result series, whereas legacy insights would return one series per cohort

## Additional context

Example insight: https://us.posthog.com/project/2/insights/zJNkTehz

**Comment by mariusandra** [comment]
After the fix, the first time I load the linked insight I get [this error](https://posthog.sentry.io/issues/5198129706/?referrer=slack&notification_uuid=ed5123fe-5f9b-4e53-a934-06d9f608c9d9&alert_rule_id=1075039&alert_type=issue):

```
'<' not supported between instances of 'int' and 'str'
```

<img width="772" alt="image" src="https://github.com/PostHog/posthog/assets/53387/8d016e31-8cc1-4520-8848-42d36c7a8123">

However on refresh the data shows up.

**Comment by mariusandra** [comment]
fixed
