### ISSUE TITLE
Loading /instance/status fails on self-hosted instance

### ISSUE THREAD

**Issue by macobo** [PostHog/posthog#2135]
## Bug description

I set up a self-hosted instance via AWS cloudformation and updated it recently.

The page /instance/status fails to load for me.

## Expected behavior

Instance status page loads successfully.

## How to reproduce

- Set up a cloudformation instance
- ???
- Visit /instance/status
- See report on 500 error from backend

## Environment

- 1.15.1 (latest docker container)

## Additional context

Not able to provide a lot of useful context here due to https://github.com/PostHog/deployment/issues/32

**Comment by ruslanasa** [comment]
Same issue for me after update to 1.15.1 on AWS using cloudformation

**Comment by Twixes** [comment]
So this only happens with CloudFormation? Can't reproduce with Heroku.
In any case Sentry should be able to capture the exception for analysis, right?

**Comment by macobo** [comment]
Unsure, doesn't happen on app.posthog.com at least.

I don't have sentry set up on my self-hosted instance. :)

I am currently working on a few things to improve our cloudformation setup, once I have access to logs (https://github.com/PostHog/deployment/issues/32) I will have more information to debug this with.
