### ISSUE TITLE
Allow filtering sessions by Actions

### ISSUE THREAD

**Issue by macobo** [PostHog/posthog#2137]
## Is your feature request related to a problem?

Closely related to https://github.com/PostHog/posthog/issues/2130

We don't have a great story for the sessions view (look forward to my future proposal), but when debugging stuff I'd love to look at sessions from people who performed a specific action.

## Describe the solution you'd like

- Be able to filter sessions by "user performed this action"
- Be able to save that query onto a dashboard

**Comment by paolodamico** [comment]
Lmk if you want to sync up to work on the new proposal for this.
