### ISSUE TITLE
Filtered internal emails still get recordings and consumed our quota

### ISSUE THREAD

**Issue by atapiawastaken** [PostHog/posthog#21385]
## Bug description

We filtered out from tracking our emails: restack.io. 
<img width="767" alt="Screenshot 2024-04-07 at 07 45 07" src="https://github.com/PostHog/posthog/assets/2209883/788b5f93-bbe3-4d27-ad46-a2458a0b2325">

But still we are getting recordings that consumed our quota. 
<img width="526" alt="Screenshot 2024-04-07 at 07 46 53" src="https://github.com/PostHog/posthog/assets/2209883/37940875-1227-4a92-a87f-cfc886599a0f">

## How to reproduce

1. Filter out email on the section Settings > Filter out internal and test users
2. Email still shows on recordings and consume our quota

## Environment

- [x] PostHog Cloud US, project ID: 26745
- [ ] PostHog Cloud EU, project ID: [please provide from https://eu.posthog.com/settings/project-details#variables]
- [ ] PostHog Hobby self-hosted with `docker compose`, version/commit: [please provide]
- [ ] PostHog self-hosted with Kubernetes (deprecated, see ["Sunsetting Kubernetes support"](https://posthog.com/blog/sunsetting-helm-support-posthog)), version/commit: [please provide]

**Comment by breart** [comment]
It's literally written:

> Adding filters here does not prevent events or recordings being ingested.

You probably need to use something [like this](https://posthog.com/docs/cdp/filter-out) if you would like to prevent ingesting some events. 

For session recordings, I couldn't find a way to prevent ingesting based on criteria, but [there is a way](https://posthog.com/tutorials/limit-session-recordings#manually-in-your-code) to control when you want to record users via SDK.

**Comment by atapiawastaken** [comment]
thanks!
