### ISSUE TITLE
User property for self-hosted deployment host

### ISSUE THREAD

**Issue by macobo** [PostHog/posthog#2138]
## Is your feature request related to a problem?

As an analytics company, we rely on analytics to drive our product. 

We currently know if users are using cloud or are self-hosted, but it would be great if we also knew what platform they were using. This helps us prioritize issues around different deployments or see if some are performing exceptionally well.

## Describe the solution you'd like

Each user should have a `deployment` user attribute, e.g. as `cloud`, `aws-cloudformation`, `heroku`, etc.

This can be done by passing a env variable to user properties if user did not opt out of capture.

## Describe alternatives you've considered

Measuring "one-click" deploys. However, having both is valuable, even if to see if users finish the deployment.

**Comment by paolodamico** [comment]
We now have this.
