### ISSUE TITLE
Billing page is down

### ISSUE THREAD

**Issue by spector-in-london** [PostHog/posthog#21384]
## Bug description

*Please describe.*  
*If this affects the front-end, screenshots would be of great help.*  

![image](https://github.com/PostHog/posthog/assets/2736922/c4bbea19-65ed-4e95-89a9-3ceb84fddcfe)
 Can't access my biling information

*If you are on PostHog Cloud it would be really valuable if you can share any links where the problem occurs. This speeds up our ability to troubleshoot tremendously.* 

https://eu.posthog.com/organization/billing#panel=support%3Abug%3Abilling%3A

## How to reproduce

1.
2.
3.

## Environment

- [ ] PostHog Cloud US, project ID: [please provide from https://us.posthog.com/settings/project-details#variables]
- [ X] PostHog Cloud EU, project ID: [please provide from https://eu.posthog.com/settings/project-details#variables]
- [ ] PostHog Hobby self-hosted with `docker compose`, version/commit: [please provide]
- [ ] PostHog self-hosted with Kubernetes (deprecated, see ["Sunsetting Kubernetes support"](https://posthog.com/blog/sunsetting-helm-support-posthog)), version/commit: [please provide]

## Additional context

![image](https://github.com/PostHog/posthog/assets/2736922/7e6a0c4f-6580-4009-8fdc-e82154094af2)

**Comment by raquelmsmith** [comment]
Hi Brandon - can you please submit a support ticket from the in-app support/help panel? That'll help us diagnose this issue. Thanks!
