### ISSUE TITLE
Allow graphing no of sessions in insights page

### ISSUE THREAD

**Issue by macobo** [PostHog/posthog#2139]
## Is your feature request related to a problem?

Currently we allow graphing number of pageviews, number of DAUs and so on. We also have some functionality around sessions - it would be great to expose a daily number of sessions.

This can be useful to expose whether users are using the product once or many times a day.

## Describe the solution you'd like

1. Open insights page
2. Select $session from dropdown
3. Profit

## Describe alternatives you've considered

Graphing DAUs is a similar metric, but doesn't capture all of this.

**Comment by Twixes** [comment]
There's now "Unique sessions"
