### ISSUE TITLE
Autosuggest data-* attribute-based selectors over className based selectors

### ISSUE THREAD

**Issue by macobo** [PostHog/posthog#2140]
## Is your feature request related to a problem?

Creating actions requires some technical know-how and is quite involved. 

I've now been in two interviews where the automatically suggested selector were not great:
1. In one, they used inline styling and had dynamically generated class names. They used `data-testid` attributes internally for testing which could be used.
2. In another, `data-test-foobar` was the attribute they were hoping to be used 

## Describe the solution you'd like

If element has unusual data-attributes, suggest those over class-based ones.

We already seem to have a special case for one data-attribute, `data-attr` but we should expand it for other data attributes as well. https://github.com/PostHog/posthog/blob/5729fb5/frontend/src/toolbar/utils.ts#L59-L62

## Additional context

cc @ukupat and @andrestaht

**Comment by tino** [comment]
This would be great. We are using Cypress for testing, and thus have a lot of elements annotated with `data-cy="..."`, also because of 1.

These attributes used to show up but don't do anymore?
In browser:
![image](https://user-images.githubusercontent.com/99524/98534987-a211c380-2285-11eb-9689-8a51d7464889.png)

In Posthog:
![image](https://user-images.githubusercontent.com/99524/98535029-b35ad000-2285-11eb-9ff9-a79cac13ceaf.png)

**Comment by timgl** [comment]
@tino are you self-hosting or on app.posthog.com?

**Comment by tino** [comment]
@timgl Self-hosting

**Comment by timgl** [comment]
@tino The reason for this dat this attribute is on an input element. We try to be really strict around the data we capture from input elements (only name, id and class attributes), as [other companies have messed this up in the past](https://techcrunch.com/2018/02/05/mixpanel-passwords/). If you put the attribute on the div it will be captured. Sorry about that!

**Comment by macobo** [comment]
@mariusandra had a look at adding this to our fork at https://github.com/mariusandra/simmerjs/tree/local-release.

One thing I had questions on was that we're not [following w3c-s specificity ruleset](https://www.w3.org/TR/selectors-3/#specificity) - can you give context on why we dropped that?

**Comment by mariusandra** [comment]
@macobo if I remember correctly, it's because a `data-attr` means something else for us. We consider it similar to a `#id`. Without forcing it into higher priority, the selector matching logic would find something else and potentially ignore the `data-attr`.
