### ISSUE TITLE
When defining actions, show a border around matching elements

### ISSUE THREAD

**Issue by macobo** [PostHog/posthog#2143]
## Is your feature request related to a problem?

Currently when defining actions, you often have to define selectors manually.

With just a "matching element" count it can be hard to know if the selector you entered is the right one.

## Describe the solution you'd like

Show a border similar to what happens when you click "Change element".

**Comment by paolodamico** [comment]
Relevant [customer feedback](https://docs.google.com/document/d/1gJlsUDrlW7ur8zT5scqRvXZhapm_0JdvKGiw68Iyx9E/edit#heading=h.uxf2ltfknjyc) on this autocapture functionality.

**Comment by paolodamico** [comment]
More [customer feedback](https://docs.google.com/document/d/1gJlsUDrlW7ur8zT5scqRvXZhapm_0JdvKGiw68Iyx9E/edit#heading=h.jc9thlt4k0t7) on this, Event ingestion section. No clarity around CSS selectors matching multiple elements. CSS selectors annoying even after understanding how they work.
