### ISSUE TITLE
User Session Recording Results in Error

### ISSUE THREAD

**Issue by dehli** [PostHog/posthog#21447]
## Bug description

Yesterday we started getting an error in our app triggered from Posthog hosted code:

`Cannot read properties of null (reading 'tagName')`

I was able to debug that it's related to user session recordings and disabling them prevents the error from showing more.

I have left it enabled on our dev instance so it can be more easily debugged.

## How to reproduce

1. Visit https://dev.vistaly.com
2. Sign-in with: `cp+posthog@vistaly.com` / `Password123!`
3. Visit https://dev.vistaly.com/w/qewwIlH4Xf1R0cAt7jdOm
4. Delete the card text (by clicking on it and then removing it in editor) and then start interacting in the app
<img width="375" alt="image" src="https://github.com/PostHog/posthog/assets/5856011/21d959aa-4969-460c-bbb5-fe7f0962cd96">

5. See console filled with error messages:
<img width="681" alt="image" src="https://github.com/PostHog/posthog/assets/5856011/73c77ceb-f1ef-444c-9fc3-354e820ad605">

## Environment

- [x] PostHog Cloud US, project ID: 29524

## Additional context

- https://posthog.com/questions/enabling-record-user-sessions-generates-cannot-read-properties-of-null-reading-tag-name

**Comment by daibhin** [comment]
Thank you very much for the reproduction steps @dehli.

It looks like the latest version of our web capture tool ([rrweb](https://github.com/rrweb-io/rrweb)) made the changes causing this issue in a PR that was merged in the latest release: https://github.com/rrweb-io/rrweb/pull/1351. We upgraded to the latest release yesterday, which perfectly lines up with when the error started occurring for you.

I've shipped a fix to their repo: https://github.com/rrweb-io/rrweb/pull/1445 and added a patch to our own repo https://github.com/PostHog/posthog-js/pull/1125

Thanks for reporting this 🙏

**Comment by dehli** [comment]
Thanks @daibhin for the speedy fix! Happy to help 😄 Should I go ahead and close issue or wait until the fix is deployed?

**Comment by daibhin** [comment]
@bookee-sid I just merged the change. I should be live in the next hour or so. It will require that you upgrade your PostHog SDK to the latest version

**Comment by dehli** [comment]
Thanks again @daibhin for the quick fix! Just confirmed that the error is no longer occurring so I will go ahead and close this issue. Have a good one!

**Comment by daibhin** [comment]
Amazing, thanks @dehli for confirming
