### ISSUE TITLE
Reference implementation for sending $pageview events within a SPA (react-router)

### ISSUE THREAD

**Issue by macobo** [PostHog/posthog#2144]
## Is your feature request related to a problem?

Currently, when using single-page apps we encourage users to send $pageview events manually by integrating with their router library.

This confusion came up within a call.

## Describe the solution you'd like

It would be great to have a sample "integration" library with e.g. react-router. We can then link to that integration from within our docs or mention it in customer calls.

## Additional context

https://posthog.com/docs/tutorials/spa

**Comment by yakkomajuri** [comment]
The SPA tracking tutorial is live, although it isn't specific to `react-router`

**Comment by ghost** [comment]
Tracking $pageview events with react-router and hooks should be quite straightforward as per the following snippet. The snippet is a very simple hook that would sit in the render function of each route's parent component, called by `usePageTrack()`. 

```
import { useEffect } from "react";
import { useLocation } from "react-router-dom";
import posthog from "posthog-js";

export default function usePageTrack() {
  const { pathname } = useLocation();
  useEffect(() => {
    posthog.capture("$pageview");
  }, [pathname]);
}
```

**Comment by yakkomajuri** [comment]
@stevenphaedonos thanks for this! I'll add it to the [SPA tutorial](https://posthog.com/docs/tutorials/spa). The focus there was to go over the main concepts so it used VanillaJS but could be worth adding the React snippet for sure

**Comment by muzammil360** [comment]
@macobo, even though the sample has been added to SPA tutorial, the issue still seems to be open. Is there anything you would like in opensource code?

**Comment by neilkakkar** [comment]
I think it's all good, thanks!
