### ISSUE TITLE
Insight Slack subscriptions firing every hour

### ISSUE THREAD

**Issue by deezium** [PostHog/posthog#21450]
## Bug description

We had a subscription for https://us.posthog.com/project/3219/insights/N3sfFpBS#panel=support%3Asupport%3A%3A that used to send a daily Slack message with the insight.  As of Monday, April 8th around 6 AM PST, the alert started firing every hour.

## How to reproduce

1.  Set up a subscription for a daily Slack message
2.  It'll fire properly at the initial expected time but then will fire every hour

## Environment

- [ ] PostHog Cloud US, project ID: 3219

**Comment by timgl** [comment]
@deezium we had reports of this on #21416 but we implemented a fix earlier today. Have you seen this happen in the last couple of hours?

**Comment by deezium** [comment]
@timgl Yah we saw this happen a little over an hour ago: https://capture.dropbox.com/7rV4VWvsttZ6ouNf.

**Comment by timgl** [comment]
Okay I think these will have been fixed, it's likely just a couple of messages that were still queued up. You also at one point had two subscriptions to the same insight, which maybe was the reason why. Either way, I do think it should be fixed now but let me know if that's not the case!
