### ISSUE TITLE
User can vote multiple times in a survey even if it was set to be shown only once for unique user

### ISSUE THREAD

**Issue by patrycjaclariness** [PostHog/posthog#21486]
## Bug Description

One of the users voted multiple times in the survey, even if it was set to be shown only once to unique users.  Is this a bug or Posthog or is there any other reason why it was possible? This makes the outcome of our survey not reliable since almost half of the votes come from the same user.

<img width="1022" alt="Screenshot 2024-04-11 at 09 29 04" src="https://github.com/PostHog/posthog/assets/166694820/ecd40d81-03ad-45d1-a6ef-a95d5de4646c">

https://eu.posthog.com/project/1219/surveys/018d695a-1f04-0000-3615-69cff1f47f27

## How to reproduce

1. Go to the survey in the link
2. Look at the votes, the last votes come from the same user

## Environment

- [ ] PostHog Cloud US, project ID: [please provide from https://us.posthog.com/settings/project-details#variables]
- [X] PostHog Cloud EU, project ID: 1219 [please provide from https://eu.posthog.com/settings/project-details#variables]
- [ ] PostHog Hobby self-hosted with `docker-compose`, version/commit: [please provide]
- [ ] PostHog self-hosted with Kubernetes (deprecated, see ["Sunsetting Kubernetes support"](https://posthog.com/blog/sunsetting-helm-support-posthog)), version/commit: [please provide]

**Comment by neilkakkar** [comment]
Hi @patrycjaclariness this is how you can solve it today: https://posthog.com/docs/surveys/troubleshooting#how-are-users-responding-multiple-times-to-the-same-survey-despite-setting-wait-period - until we make this a more configurable setting unfortunately this is the only way.

**Comment by patrycjaclariness** [comment]
Hi @neilkakkar 
I can only select two users out of this modal and none of them has taken survey multiple times 
<img width="1074" alt="Screenshot 2024-04-11 at 12 18 47" src="https://github.com/PostHog/posthog/assets/166694820/2f3cc37a-58d7-4113-8ca2-2607820f797c">

**Comment by neilkakkar** [comment]
[Sorry you have to do this manually right now - I know its annoying and isn't something you should have to think about!]

Not sure I understand - you're not selecting users here, but looking for the survey responded property for the specific survey - the ID is ID of the survey, not the user. Every user who responds to the survey will get this property :)
