### ISSUE TITLE
Support Clickhouse instead of PostgreSQL

### ISSUE THREAD

**Issue by Slach** [PostHog/posthog#215]
**Is your feature request related to a problem? Please describe.**
When data will grow, we will need more performance for our analytics database 
It always hard switch from OLTP based database to column oriented,

**Describe the solution you'd like**
I propose use https://clickhouse.yandex database instead of PostgreSQL for store and ready analytical data

**Comment by Tannergoods** [comment]
PostHog has already integrated Clickhouse although this is currently within our Ultimate plan as it is there to work with really big volumes, I'll assign @jamesefhawkins to update our documentation today to make this clearer. 

We have some thoughts and ideas on scaling PostHog in our wiki -https://github.com/PostHog/posthog/wiki/Scaling-PostHog that might go some way to maintaining your analytics database performance?
