### ISSUE TITLE
`setup_dev` hangs on heroku apps

### ISSUE THREAD

**Issue by mariusandra** [PostHog/posthog#2150]
## Bug description

The script to setup review apps fails on Heroku:

![2020-10-31 09 06 24](https://user-images.githubusercontent.com/53387/97774591-7130e080-1b59-11eb-8328-0f9b6fceba6a.gif)

As far as I could `print`-debug, the script itself didn't get stuck ([this last line was printed](https://github.com/PostHog/posthog/blob/e1c5828c9ec4520bbbca72e74a765769577851b0/posthog/management/commands/setup_dev.py#L45)), but something after it.

Removing the transaction didn't help.

I'll keep debugging, but if anyone has a gut feeling what might be wrong, please share. @timgl @Twixes 

Otherwise I'm going to have to start binary searching from within the git commits...

## Expected behavior

Review apps should deploy

## How to reproduce

1. Branch off of master and wait for the heroku app to deploy
2. Notice that the worker didn't come up
3. Trace it back to `setup_dev` not hanging

## Environment

Heroku

## Additional context

Shoutout to the Heroku support staff for helping and knowing from this log that the script didn't finish! I didn't know what to look for :)

![image](https://user-images.githubusercontent.com/53387/97774712-5f037200-1b5a-11eb-8596-82134ad0ce75.png)

**Comment by mariusandra** [comment]
After a bunch of deploys to Heroku, I've managed to find the PR that broke things: https://github.com/PostHog/posthog/pull/2068

<img width="1290" alt="Screenshot 2020-10-31 at 13 47 42" src="https://user-images.githubusercontent.com/53387/97781019-d0f2b000-1b88-11eb-9e5b-1c61a139c78c.png">

Now to find out what went wrong.

**Comment by Twixes** [comment]
Seems to work OK for me now, is there still something to fix?

**Comment by mariusandra** [comment]
Can you show where it works? Taking any latest branch's review app on heroku still shows that the worker doesn't start:

<img width="1245" alt="Screenshot 2020-11-05 at 09 56 02" src="https://user-images.githubusercontent.com/53387/98219355-2c3bee00-1f4d-11eb-93c1-d3ebbece0804.png">

And looking at `heroku ps` the `setup_dev` command is running for an hour:

```
$ heroku ps -a posthog-fix-crontab-r2lb57kd0d 
=== run: one-off processes (1)
run.2992 (Hobby): up 2020/11/05 08:48:58 +0100 (~ 1h ago): (/bin/sh -c python\ manage.py\ setup_dev); echo "5b4a7990d3175f06be75870e26bdab3d $?"
```

**Comment by Twixes** [comment]
Yep, no, on second take I agree this doesn't work. Equally baffled why.

**Comment by mariusandra** [comment]
I think I tracked down the issue. Still not 100% sure of the "why" (nor "why now?" nor "why with [this PR](https://github.com/PostHog/posthog/pull/2068)?")... but here's what happens:

PostHog gets stuck behind `posthoganalytics`, which runs a [background thread](https://github.com/PostHog/posthog-python/blob/6e39aa0ceb958fd2565923fb7c4ccc6e982a6ed5/posthog/poller.py#L3) that every 30 seconds [loads feature flags](https://github.com/PostHog/posthog-python/blob/16acf2e278eb52edbe04bfacc72c0c9b4dc2791b/posthog/client.py#L254). 

Annoyingly, it even doesn't even do that, and just throws [this error](https://github.com/PostHog/posthog-python/blob/16acf2e278eb52edbe04bfacc72c0c9b4dc2791b/posthog/client.py#L232) every 30 sec.

![image](https://user-images.githubusercontent.com/53387/99969315-8edd1880-2d9a-11eb-84a8-8ec32e6eed6b.png)

Running `setup_dev` with `OPT_OUT_CAPTURE=1` solves the problem:

![image](https://user-images.githubusercontent.com/53387/99969686-1dea3080-2d9b-11eb-8d93-0137107f2d9c.png)

**Comment by timgl** [comment]
Hm yes that looks like the logic for loading feature flags async is blocking that command from finishing. Have created [a ticket](https://github.com/PostHog/posthog-python/issues/16). Workaround makes sense for now

**Comment by mariusandra** [comment]
Fixed with https://github.com/PostHog/posthog/pull/2475
