### ISSUE TITLE
chart does not work (worked before)

### ISSUE THREAD

**Issue by kajalaiko** [PostHog/posthog#21562]
## Bug description

*Please describe.*
*If this affects the front-end, screenshots would be of great help.*

*If you are on PostHog Cloud it would be really valuable if you can share any links where the problem occurs. This speeds up our ability to troubleshoot tremendously.*

## How to reproduce

1. 
2.
3. 

### Debug info

```shell
Session: https://us.posthog.com/project/sTMFPsFhdP1Ssg/replay/018ee5f0-e994-78ca-8a4b-20396f8b51f8?t=3508 (at https://eu.posthog.com/project/12673/notebooks/cwyCHp9H#panel=support%3Abug%3Aanalytics%3A)
Admin: http://go/adminOrgEU/018c1b09-f073-0000-3d50-eeea53a13a36 (Project: 12673)
Sentry: http://go/sentryEU/12673
```

**Comment by marandaneto** [comment]
Please fill up the issue template with proper description and steps
