### ISSUE TITLE
Toolbar requests Authenticate

### ISSUE THREAD

**Issue by c2ofh** [PostHog/posthog#21566]
## Bug description

We have an angular environment and want to use the Toolbar. 
PostHog is set-up corectly, the Toolbar is showing, but when clicking on action, there is the Message "Authenticate"

When clicking on it, we're getting redirected to https://us.posthog.com/login?next=/authorize_and_redirect/....
But we're on the eu environment. When I choose there "EU" we're getting redireced to an error page "Page not Found. 

## Additional context

An API-Request is made to https://app.posthog.com/api/projects/@current/actions/?temporary_token=**********_******

```json
{
    "type": "authentication_error",
    "code": "authentication_failed",
    "detail": "User doesn't exist",
    "attr": null
}
```

### Debug info

```shell
Session: https://us.posthog.com/project/sTMFPsFhdP1Ssg/replay/018ee660-6734-7864-9dc1-543fedfb18a4?t=257 
Admin: http://go/adminOrgEU/018bae0c-5e51-0000-f750-c447a419ace1 (Project: 11751)
Sentry: http://go/sentryEU/11751
```

**Comment by benjackwhite** [comment]
Hi - can you indicate some more information about your config? 

The redirect will be based on the provided config values where we try and determine the correct region based off your `api_host`.

**Comment by benjackwhite** [comment]
For example if you use anything in `api_host` other than `https://eu.posthog.com` or `https://eu.i.posthog.com` then it won't know which region you are in so you would need to specify the `ui_host` param like so:

```js

posthog.init(KEY, {
  api_host: "https://my-proxy.com",
  ui_host: "https://eu.posthog.com"
})

```

**Comment by c2ofh** [comment]
@benjackwhite thank you very much. I've checked my init and everything seems to be fine.
The region is included. 

```js
posthog.init(environment.posthog.apiKey, {api_host: 'https://eu.posthog.com', ip: false, disable_session_recording: true});
```

**Comment by benjackwhite** [comment]
@c2ofh are you on the latest version of posthog-js? I can't reproduce the issue at all

**Comment by c2ofh** [comment]
@benjackwhite we`re currently using 1.93.6

**Comment by benjackwhite** [comment]
> @benjackwhite we`re currently using 1.93.6

That's from December last year. Since then we have definitely had bug fixes around exactly this issue so I would for sure suggest - upgrade :D

**Comment by c2ofh** [comment]
@benjackwhite we're currently updating typescript to be able to install the new vesion, but this needs a new angular and some other packages. I will close that issue for now and will open it, when it's updated an not working.
