### ISSUE TITLE
Not working canvas recording

### ISSUE THREAD

**Issue by yudinvictor** [PostHog/posthog#21585]
### Bug Description

Hi all, I'm trying to set up session recording so that my canvas element is recorded. I have specified Canvas capture in the settings, but nothing has changed. 

I am using react and PostHogProvider with default options, my canvas has a webgl2 context 

Has anyone experienced this? Maybe I need to pass options somehow else when initialising in the application.

**Comment by marandaneto** [comment]
cc @daibhin

**Comment by daibhin** [comment]
Hi @yudinvictor - happy to look into this for you because it sounds like you're doing everything right. Could you share a link to an affected recording and I can dig in further from there?

**Comment by daibhin** [comment]
Hi @yudinvictor - I haven't heard from you on this issue so I'm going to close it now and assume you made some progress. If things aren't resolved please feel free to reopen this issue and we can pick it back up
