### ISSUE TITLE
Dashboard not found

### ISSUE THREAD

**Issue by aaly00** [PostHog/posthog#21589]
## Bug description

*Please describe.*
![image](https://github.com/PostHog/posthog/assets/11652379/a3e64c49-1362-49b5-9319-94c92c9651ac)

*If you are on PostHog Cloud it would be really valuable if you can share any links where the problem occurs. This speeds up our ability to troubleshoot tremendously.*

We are getting a 500 server error every time we try to access our dashboard. 

### Debug info

```shell
Session: https://us.posthog.com/project/sTMFPsFhdP1Ssg/replay/018ee81d-2aaa-7521-b967-0b416d153bb3?t=309 (at https://us.posthog.com/project/36763/dashboard/151964#panel=support%3Asupport%3A%3A)
Admin: http://go/adminOrgUS/018aaf2c-987f-0000-0b73-52830cefb582 (Project: 36763)
Sentry: http://go/sentryUS/36763
```

**Comment by MarconLP** [comment]
Hey @aaly00, we've fixed the issue and you should be able to load the dashboard now.
