### ISSUE TITLE
There was a problem completing this query

### ISSUE THREAD

**Issue by ryancgoins** [PostHog/posthog#21584]
## Bug description

On a Funnel Insight I'm clicking on the chart to view groups in that segment and receiving the following error "There was a problem completing this query". This only surfaced in the last few weeks, and I've made no changes to the insight. 

This is a link to the funnel where I'm seeing the issue: https://us.posthog.com/project/59383/insights/qlcboWzf

## How to reproduce

1. Navigate to https://us.posthog.com/project/59383/insights/qlcboWzf
2. Click one of the bars in the chart to view the associated groups (organization) 

### Debug info

```shell
Session: https://us.posthog.com/project/sTMFPsFhdP1Ssg/replay/018ee77a-8727-78e4-af45-dcc7ddb2391a?t=545 (at https://us.posthog.com/project/59383/insights/qlcboWzf#panel=support%3Abug%3Aanalytics%3A)
Admin: http://go/adminOrgUS/018e3d78-1f90-0000-a55b-db25750d24b7 (Project: 59383)
Sentry: http://go/sentryUS/59383
```

**Comment by mariusandra** [comment]
Hey @ryancgoins , this should now be fixed! Thanks for reporting!
