### ISSUE TITLE
Feature flags are incorrect on client `identify(...)` call after backend calls `posthog.capture` for the same user

### ISSUE THREAD

**Issue by dfed** [PostHog/posthog#21591]
## Bug description

When a customer logs into our app, our backend calls:
```ts
  const posthog = new PostHogClient(apiKey, {
    flushAt: 1,
    flushInterval: 0,
  });

  posthog.capture({
    distinctId: "usr_...",
    event: "User Signed Up",
    properties: {
      $set: {
        id: "usr_...",
        custom_field: "CUSTOM_FIELD_THAT_AFFECTS_FEATURE_FLAGS",
      },
    },
  });

  await posthog.shutdownAsync();
```

before returning the "auth success" response to the iOS client. As soon as the client receives that auth is successful, the client calls `identify`, which immediately reloads feature flags for the user whose properties were just set by the backend.

This feature flag load does not take into account the `custom_field: "CUSTOM_FIELD_THAT_AFFECTS_FEATURE_FLAGS",` field that was just set on this user, and therefore our feature flags are all returning `false`. Subsequent feature flag reloads do take this field into account.

It seems like there's a race condition on the Posthog backend. Calling `identify` on a client after user properties have been set on the backend should result in a client receiving feature flags that take these user properties into account.

## How to reproduce

1. Call `posthog.capture` with feature-flag-affecting context on backend and wait for the call to complete
2. Call `identify` with the same user ID on the client
-> See that the recently loaded feature flags do not take the context set in `capture` into account

### Debug info

- [x] PostHog Cloud, Debug information: [please copy/paste from https://us.posthog.com/settings/project-details#variables]

Session: https://us.posthog.com/project/sTMFPsFhdP1Ssg/replay/018ee942-23d9-743e-b2c7-23217050e7b7?t=0 
Admin: http://go/adminOrgUS/018d351a-9ff7-0000-eaff-4628875ad045 (Project: 50689)
Sentry: http://go/sentryUS/50689

- [ ] PostHog Hobby self-hosted with `docker compose`, version/commit: we are not self-hosted
- [ ] PostHog self-hosted with Kubernetes (deprecated, see [`Sunsetting Kubernetes support`](https://posthog.com/blog/sunsetting-helm-support-posthog)), version/commit: we are not self-hosted

**Comment by neilkakkar** [comment]
Hi @dfed , thanks for the report! This is indeed the case: property updates from other clients can be delayed, depending on when the update is processed.

To get around this, it's ideal if you can call identify with this property, or call `setPersonPropertiesForFlags()` like here: https://posthog.com/docs/libraries/js#overriding-server-properties

**Comment by NathanDjianMartin** [comment]
Hi @neilkakkar is there a similar function in the Node SDK?

I need to evaluate a feature flag in a backend but the property affecting the feature flag is not yet set on Posthog.
