### ISSUE TITLE
Unable to fetch billing information prevents all page content on dashboard from loading (excluding sidebars)

### ISSUE THREAD

**Issue by bmcbride22** [PostHog/posthog#21593]
## Bug description

*Please describe.*
*If this affects the front-end, screenshots would be of great help.*

*If you are on PostHog Cloud it would be really valuable if you can share any links where the problem occurs. This speeds up our ability to troubleshoot tremendously.*

## How to reproduce

1. Complete onboarding with new Nextjs app
2. Add billing with Wise credit card through stripe dashboard 
3. Page load any of the feature pages

## Additional context

https://github.com/PostHog/posthog/assets/27652758/7e548142-f056-4b0b-9c7e-b96968735d3e
<img width="1416" alt="image" src="https://github.com/PostHog/posthog/assets/27652758/62151a8f-ccba-4837-a775-2be532150e37">

### Debug info

```shell
Session: https://us.posthog.com/project/sTMFPsFhdP1Ssg/replay/018eea13-3dd2-7d96-aa54-f7cbda36aafd?t=793 (at https://us.posthog.com/organization/billing#panel=support%3Abug%3Abilling%3A)
Admin: http://go/adminOrgUS/018ee61a-6484-0000-b11a-5efb9f358113 (Project: 64004)
Sentry: http://go/sentryUS/64004
```

**Comment by zlwaterfield** [comment]
Hey @bmcbride22, I've fixed this for you, and you should now be able to load your billing page. I'm looking into why this occurred; thanks for the bug report.
