### ISSUE TITLE
Unable to connect with redis 

### ISSUE THREAD

**Issue by saileshkush95** [PostHog/posthog#2163]
I'm trying to test this project in my local from source code. every thing is working fine, I'm unable to connect my redis server with post hog.

My redis server is running this address `localhost:6379`.
![Screenshot from 2020-11-02 11-52-12](https://user-images.githubusercontent.com/28560875/97835272-e63f1a00-1d01-11eb-88bd-b773f2ca663b.png)

and here is configurations of evironment variables
![Screenshot from 2020-11-02 11-53-26](https://user-images.githubusercontent.com/28560875/97835345-08d13300-1d02-11eb-8550-5cffa52c539c.png)

and here is redis status screenshot
![Screenshot from 2020-11-02 11-54-24](https://user-images.githubusercontent.com/28560875/97835419-34541d80-1d02-11eb-8b01-29db78f48dc5.png)

**Comment by macobo** [comment]
So that line might indicate both that redis is not working or that the celery worker is not.

Couple of questions to help debug this:

- Are you starting the server locally, without docker?
- Did you use the `./bin/start` command to start the server? Without it the celery worker would not start. 
- Any example logs to show us?

Check out https://posthog.com/docs/developing-locally as well.

**Comment by saileshkush95** [comment]
Yes I'm starting server locally without using docker.
No I didn't use ./bin/start command to start the server 

#########################################

Thank you for your help, when I'm using this `./bin/start` it is working fine. but I've questions how can i deploy this manually. with out using docker. 

#############################################
Here is simple configurations of gunicorn.service  for deploying 

```
server {
    listen 80;
    server_name domain name;

    location = /favicon.ico { access_log off; log_not_found off; }
    location /static/ {
        alias /home/sandeep/Django/posthog/staticfiles/;
    }

    location /media/ {
        root /home/sandeep/Django/posthog;
    }


    location / {
        include proxy_params;
        proxy_pass http://unix:/run/posthog.sock;
    }
}
```
How can i deploy manually?

**Comment by macobo** [comment]
We have this documentation: https://posthog.com/docs/deployment/deploy-source

Does this help?

**Comment by saileshkush95** [comment]
Thank you for your help

**Comment by macobo** [comment]
Great! Let us know if you run into other problems (we also have a slack group) or have any feedback!
