### ISSUE TITLE
Bug with actions count

### ISSUE THREAD

**Issue by paolodamico** [PostHog/posthog#2164]
## Bug description

We use `/api/action/{id}/?include_count=1` to show the number of matches for a specific action, however this count is off. Presumably as CH now does calculations on the fly, this number does not make sense anymore. See below an example.

Action listing shows 30 matches total:
![image](https://user-images.githubusercontent.com/5864173/97838281-c1ce4800-1cd7-11eb-91f0-31910d4e3ba5.png)

Trends graph shows at least one data point well above 30 (at ~80%).
![image](https://user-images.githubusercontent.com/5864173/97838283-c3980b80-1cd7-11eb-8bbb-a65f30e49506.png)

## Expected behavior
This number should compute the number of matches on the fly too and show the right computation.

## How to reproduce

1. Review action 2296 and see "30 matches"

Alternatively, try with a different action (best reproduced with an action with a low number of matches)
1. Open the action from the actions list and note the number of matches.
1. Use the actions on a trends graph and notice the number discrepancy.

## Environment

Cloud.

## Additional context

Reported by a user whom was very off-put by this discrepancy ([details](https://posthog.slack.com/archives/C01C93MSLBU/p1604037306027500))

**Comment by EDsCODE** [comment]
Tested. This was fixed
