### ISSUE TITLE
Problem with lifecycle report

### ISSUE THREAD

**Issue by Tigeneric** [PostHog/posthog#21694]
## Bug description

*Please describe.*
*If this affects the front-end, screenshots would be of great help.*

*If you are on PostHog Cloud it would be really valuable if you can share any links where the problem occurs. This speeds up our ability to troubleshoot tremendously.*

## How to reproduce

1. 
2.
3. 

## Additional context
![image](https://github.com/PostHog/posthog/assets/50767360/51f1bd1e-89d5-4df8-976b-5eb75a5a565c)

### Debug info

```shell
Session: https://us.posthog.com/project/sTMFPsFhdP1Ssg/replay/018efa8a-5b8f-7d00-aed4-ca4f20fd51be?t=8492 (at https://eu.posthog.com/project/12346/insights/bGOEcHyG#panel=support%3Abug%3A%3A)
Admin: http://go/adminOrgEU/018bf6ec-4bda-0000-43c3-95e6c793988b (Project: 12346)
Sentry: http://go/sentryEU/12346
```

**Comment by mariusandra** [comment]
Hey @Tigeneric can you confirm is this is still an issue? We had a bit of a rough patch last few days due to conflicts from two large features rolled out at the same time, but this looks good now from our end. Closing now, but please reopen if the error is still there.
