### ISSUE TITLE
Leaving last organization

### ISSUE THREAD

**Issue by paolodamico** [PostHog/posthog#2169]
## Bug description

#1562 introduces the possibility of removing yourself from an organization (and an admin **removing** you from an organization). This leads to a orphan user that belongs to no organization. This should be fine, however if you log in with a user that has this characteristic (and particularly happens to after you leave the organization yourself), the app just fails to load, showing just a white screen.

## Expected behavior

If I'm logged in as a user that has no organizations I would just see a page saying I have no organizations and therefore cannot interact with PostHog. The page should probably give me 2 CTAs,
1. Permanently delete my account altogether.
1. Creating a new organization.

## How to reproduce

1. Create a test user.
2. Leave all organizations.

## Environment

Cloud and self-hosted.

## Additional context

No additional context.

**Comment by paolodamico** [comment]
Happy to whip up a design if helpful.

**Comment by Twixes** [comment]
I think it should allow to leave the way it does now, but instead of, well, nothing, it should just show a "Create a New Organization" screen (with the only other option being account settings / log out), similar to how Sentry does it.

<img width="1672" alt="Screen Shot 2020-11-02 at 14 37 04" src="https://user-images.githubusercontent.com/4550621/97874296-15ad5100-1d19-11eb-92c2-93ad6bec8765.png">

**Comment by paolodamico** [comment]
Yes that is what I meant. You should also have the option to permanently delete your account.

**Comment by jamesefhawkins** [comment]
Really complex so not a good idea for now, but in case we get around to it in the far-flung future:

Or 'request access to an organization' might be worth doing (then type in organization name), which then alerts the admins through the app (or email). This would then have some privacy requirements (ie as an admin you'd need some way of disabling your org's findability in the settings so people can't start typing to work out who uses posthog unless they're ok with this)
