### ISSUE TITLE
Error W/Product Analytics 

### ISSUE THREAD

**Issue by Chess-Lab-Me** [PostHog/posthog#21691]
## Bug description

Please see attached for the error message that displays. For any chart related to 

NEW, RETURNING, RESURRECTING, & DORMANT Users I get the attached error message

It was working a few days ago without issue 

*Please describe.*
*If this affects the front-end, screenshots would be of great help.*

*If you are on PostHog Cloud it would be really valuable if you can share any links where the problem occurs. This speeds up our ability to troubleshoot tremendously.*

## How to reproduce

1. 
2.
3. 

### Debug info

```shell
Session: https://us.posthog.com/project/sTMFPsFhdP1Ssg/replay/018ef804-f977-7793-a713-309212663adb?t=21 (at https://us.posthog.com/project/61804/insights/t9JJupLx#panel=support%3Abug%3Aanalytics%3A)
Admin: http://go/adminOrgUS/018e94b6-e1aa-0000-c495-32291f715d53 (Project: 61804)
Sentry: http://go/sentryUS/61804
```

**Comment by mariusandra** [comment]
Hey @Chess-Lab-Me can you confirm is this is still an issue? We had a bit of a rough patch last few days due to conflicts from two large features rolled out at the same time, but this looks good now from our end.
