### ISSUE TITLE
Add FAQ to /pricing and /sales

### ISSUE THREAD

**Issue by jamesefhawkins** [PostHog/posthog#217]
**Is your feature request related to a problem? Please describe.**
Add FAQ to the pricing page.

We currently have good docs on the product, but we do little to explain how our pricing works, for example:

* How do you invoice / charge
* What if I add a user midway through the month?
* Do you charge annually or monthly

... and many more.

**Describe the solution you'd like**
An FAQ table as a widget (so no need to maintain it in two places), that we could share under the posthog.com/sales page and under the /pricing table.

**Describe alternatives you've considered**
People can contact us manually to ask questions. This isn't part of the transparency we want to achieve.

**Additional context**
Plenty of other companies do a nice job of this. We should create our own FAQs first, but then should look at what other companies frequently get asked, so we get a good list of questions together.

**Comment by timgl** [comment]
Closing for now as we've done a new website, can re-open in that repo if necessary
