### ISSUE TITLE
Can't paused / update workflow batch export

### ISSUE THREAD

**Issue by williamswgb** [PostHog/posthog#21706]
## Bug description

*Please describe.*
*If this affects the front-end, screenshots would be of great help.*

*If you are on PostHog Cloud it would be really valuable if you can share any links where the problem occurs. This speeds up our ability to troubleshoot tremendously.*

## How to reproduce

1. 
2.
3. 

### Debug info

```shell
Session: https://us.posthog.com/project/sTMFPsFhdP1Ssg/replay/018f0498-d1c1-7685-9a5e-c787e16ff123?t=1837 (at https://us.posthog.com/project/51521/batch_exports)
Admin: http://go/adminOrgUS/018d53fc-2f14-0000-1873-9ad51cca6dd8 (Project: 51521)
Sentry: http://go/sentryUS/51521
```

**Comment by MarconLP** [comment]
Please provide steps to replicate the issue.
