### ISSUE TITLE
Insights not updating and "There was a problem completing this query".

### ISSUE THREAD

**Issue by ahoward2** [PostHog/posthog#21702]
## Bug description

*Please describe.*

For nearly a week now, insights on our dashboards are not updating and some queries are showing "There was a problem with this query". We have not updated anything and these queries have been working ever since.

On one of our dashboards, I can manually refresh, and it will go through "Refreshed x/19..., etc" but will still be stuck on "Last updated 5 days ago."

![Screenshot 2024-04-21 at 1 03 10 PM](https://github.com/PostHog/posthog/assets/29242206/b86eb13e-cf91-4736-b22e-a3eeb0b69b21)

For 8 of the 19 queries on this dashboard that were working previously (we have not touched any of these insights), they are failing with this message.

![Screenshot 2024-04-21 at 1 06 35 PM](https://github.com/PostHog/posthog/assets/29242206/6c45b87b-6e17-4761-b072-f32bf5616208)
 

*If this affects the front-end, screenshots would be of great help.*

*If you are on PostHog Cloud it would be really valuable if you can share any links where the problem occurs. This speeds up our ability to troubleshoot tremendously.*

## How to reproduce

1. 
2.
3. 

### Debug info

```shell
Session: https://us.posthog.com/project/sTMFPsFhdP1Ssg/replay/018f0170-f704-79f0-9b77-e3ce6c6894f2?t=635 (at https://us.posthog.com/project/50928)
Admin: http://go/adminOrgUS/018d3d3f-524f-0000-a314-b5c206136523 (Project: 50928)
Sentry: http://go/sentryUS/50928
```

**Comment by ai-slave** [comment]
Have the same trouble. 

"Error: Query timed out\n    at FM (https://app-static-prod.posthog.com/static/chunk-TSII77MM.js:186:36707)\n    at async qo (https://app-static-prod.posthog.com/static/chunk-TSII77MM.js:186:39983)\n    at async fn (https://app-static-prod.posthog.com/static/chunk-TSII77MM.js:186:52983)\n    at async EM._runFn (https://app-static-prod.posthog.com/static/chunk-TSII77MM.js:186:48402)"

**Comment by ahoward2** [comment]
> Have the same trouble.
> 
> "Error: Query timed out\n at FM ([https://app-static-prod.posthog.com/static/chunk-TSII77MM.js:186:36707)\n](https://app-static-prod.posthog.com/static/chunk-TSII77MM.js:186:36707)%5Cn) at async qo ([https://app-static-prod.posthog.com/static/chunk-TSII77MM.js:186:39983)\n](https://app-static-prod.posthog.com/static/chunk-TSII77MM.js:186:39983)%5Cn) at async fn ([https://app-static-prod.posthog.com/static/chunk-TSII77MM.js:186:52983)\n](https://app-static-prod.posthog.com/static/chunk-TSII77MM.js:186:52983)%5Cn) at async EM._runFn (https://app-static-prod.posthog.com/static/chunk-TSII77MM.js:186:48402)"

+1 have the same console errors ☝️

**Comment by ahoward2** [comment]
Update on this.

Today I go back into our dashboards.

Now many of the dashboards show a message "Dashboard not found".

Subscription Failed for action set scene (scenes.sceneLogic) on logic layout.navigation.Breadcrumbs.breadcrumbsLogic.

![Screenshot 2024-04-23 at 3 17 05 PM](https://github.com/PostHog/posthog/assets/29242206/14549d1b-dfc8-49c2-a653-b3d6e82a2fa3)

**Comment by Twixes** [comment]
Hi folks, apologies for not getting back to you here earlier! We were aware of some issues with loading results, and we've implemented a couple of fixes a few weeks ago. This should not be happening anymore. If anything else pops up, please let us know!
