### ISSUE TITLE
Cannot delete person: `distinct_id=undefined`

### ISSUE THREAD

**Issue by MarconLP** [PostHog/posthog#21739]
## Bug description

![2024-04-22 at 21 52 02@2x](https://github.com/PostHog/posthog/assets/13001502/46a52960-a7aa-42e8-8c40-d254d6d517d6)

## Additional context

https://posthoghelp.zendesk.com/agent/tickets/12743

## Workaround

Try deleting the user from his `/person` page instead.

**Comment by MarconLP** [comment]
Wasn't able to replicate the issue in my local instance.

**Comment by plmapp** [comment]
Have the same issue, cannot delete people from a cohort.

**Comment by MarconLP** [comment]
@jerriclynsjohn Can you try deleting the person from it's individual /person page instead and see if that works?

**Comment by Twixes** [comment]
Hi all, apologies for the time this took – we've just resolve the issue and ensured it will never re-occur.
