### ISSUE TITLE
Video player is buffering

### ISSUE THREAD

**Issue by radulisita** [PostHog/posthog#21751]
## Bug description

Session recordings display on the list, but when I attempt to play any of them a dark screen with the message 'Buffering' is displayed. I tried with changing browsers, but it didn't resolve the issue. Do you think this is a problem on my end or a technical issue with PostHog?!

[Screenshot 2024-04-23 at 13.12.54.png](/1713867184094/Screenshot-2024-04-23-at-13.12.54.png)

### Debug info

```shell
Session: https://us.posthog.com/project/sTMFPsFhdP1Ssg/replay/018f0a6b-be5b-70da-b065-d11c67aab931?t=89 (at https://us.posthog.com/project/65254/replay/recent?simpleFilters=%7B%22events%22%3A%5B%5D%2C%22properties%22%3A%5B%5D%7D&advancedFilters=%7B%22session_recording_duration%22%3A%7B%22type%22%3A%22recording%22%2C%22key%22%3A%22duration%22%2C%22value%22%3A1%2C%22operator%22%3A%22gt%22%7D%2C%22properties%22%3A%5B%5D%2C%22events%22%3A%5B%5D%2C%22actions%22%3A%5B%5D%2C%22date_from%22%3A%22-7d%22%2C%22date_to%22%3Anull%2C%22console_logs%22%3A%5B%5D%2C%22console_search_query%22%3A%22%22%7D&sessionRecordingId=018f0a66-c635-7f5c-874d-5d5439a4a447#panel=support%3Asupport%3A%3A)
Admin: http://go/adminOrgUS/018f09e3-5a1b-0000-0a28-c6ca3e8beca1 (Project: 65254)
Sentry: http://go/sentryUS/65254
```

**Comment by jtilford** [comment]
I'm having this issue as well. I'm new to PostHog. We just started recording sessions this morning on production. Yesterday, I could view recordings created by our tests. Today, session recordings are stuck on buffering, and my webpage hangs and needs to be force-quit.

**Comment by jasonbarry** [comment]
Noticed as well on https://posthog.com/docs/session-replay/installation. First error that gets logged is `Blocked a frame with origin "https://posthog.com" from accessing a frame with origin "https://app.posthog.com". Protocols, domains, and ports must match.`

**Comment by marandaneto** [comment]
Hi, sorry about that, we're currently investigating this issue, thanks.

**Comment by pauldambra** [comment]
Hey @jasonbarry 

The example you shared is us being a little silly. Shared recordings expire after 12 months. And that example recording has expired 🙈 We should definitely have a better error message here!

The other two @jtilford @radulisita would be great to know if this is still happening for you. We seem to have a few issues all at once - clearly @daibhin and I have been cursed. 

We've fixed one and are working through the list

Currently focussed here https://github.com/PostHog/posthog/pull/21888 (but we have already shipped other fixes)

**Comment by pauldambra** [comment]
@jasonbarry I've just merged a change for the recording on the docs page. Thanks for letting us know https://github.com/PostHog/posthog.com/pull/8368

(definitely need a better error state here but at least now folk can see what it looks like)

**Comment by daibhin** [comment]
Hey @jtilford @radulisita we made some [further improvements](https://github.com/PostHog/posthog/pull/21944) to the player today that was causing some customers tabs to freeze (which perhaps manifested as you seeing the Buffering screen for longer than expected).

Now that https://github.com/PostHog/posthog/pull/21888 is also out and looks to have improved things based on our metrics I'm inclined to close this issue unless either of you continue to have problems.

**Comment by pauldambra** [comment]
this still looks like it is/was a (tricky to identify) symptom of other problems interacting with each other. so would be great to hear if it's still happening at all or at a reduced rate...

in progress:

* https://github.com/PostHog/posthog/pull/21958
* switching recordings capture back from ASGI to WSGI

done:

* https://github.com/PostHog/posthog/pull/21888
* https://github.com/PostHog/posthog/pull/21952
* https://github.com/PostHog/posthog/pull/21944

**Comment by jtilford** [comment]
@daibhin @pauldambra I'm able to view all recordings on the dashboard now, thank you.

**Comment by pauldambra** [comment]
I'll close this now - thanks for the prompt here everyone. If anyone does still have problems do open a new issue or report it in app and add some detail
