### ISSUE TITLE
Add delay before showing survey 

### ISSUE THREAD

**Issue by ericawg** [PostHog/posthog#21754]
## Is your feature request related to a problem?

When users sign up to our platform they are immediately prompted with a survey that asks them how happy they are with out product. This is a problem because they have not yet tried out our product. 

## Describe the solution you'd like
Possibility to add a delay. F.ex wait 30 days after user was first identified

### Debug info

```shell
Session: https://us.posthog.com/project/sTMFPsFhdP1Ssg/replay/018f0adb-45f5-76c0-8a06-b10f6863945f?t=39 (at https://eu.posthog.com/project/2337/surveys/018da198-a091-0000-6025-644a5ca99ffd#panel=support%3Asupport%3A%3A)
Admin: http://go/adminOrgEU/018595cc-c001-0000-e4d7-705b58193e6a (Project: 2337)
Sentry: http://go/sentryEU/2337
```

**Comment by neilkakkar** [comment]
Hey @ericawg  for small delays you can follow this tutorial for now: https://posthog.com/tutorials/delayed-survey

For larger delays: https://posthog.com/questions/ability-to-configure-delayed-survey-automatically-without-code . We'll eventually bake this into a no code/config option!

**Comment by annikaschmid** [comment]
@neilkakkar I am assuming this can be closed now?

**Comment by neilkakkar** [comment]
nice yes :) - this feature is baked into survey creation by default now
