### ISSUE TITLE
Export of reports are broken

### ISSUE THREAD

**Issue by ronald-causalens** [PostHog/posthog#21762]
## Bug description

Export of reports is broken, headings are completely wrong, data is mangled. 

For the same weekly report our headings have gone from:
series,custom name,31-Dec-2023,7-Jan-2024,14-Jan-2024,21-Jan-2024,28-Jan-2024.....
to
data.0,data.1,data.2,data.3,data.4,data.5,data.6,data.7,data.8,data.9,data.10,data.11....

data itself appears to have been pivoted, doesn't match the display on the report. 

*If you are on PostHog Cloud it would be really valuable if you can share any links where the problem occurs. This speeds up our ability to troubleshoot tremendously.*

## How to reproduce

1. Run any insight in Product analytics
2. Export to CSV
### Debug info

```shell
Session: https://us.posthog.com/project/sTMFPsFhdP1Ssg/replay/018f0b79-34da-7a9d-9e4e-37c5bf3bf1a8?t=1686 (at https://eu.posthog.com/project/6850/insights/s6E5yEB0#panel=support%3Asupport%3A%3A)
Admin: http://go/adminOrgEU/0189443c-48e9-0000-cf69-62b2a206dbcb (Project: 6850)
Sentry: http://go/sentryEU/6850
```

**Comment by webjunkie** [comment]
@ronald-causalens Thanks for bringing this to our attention. Due to our update of insights to HogQL, this has slipped in and we needed to adjust conditions in our export functions. A fix is on the way!
