### ISSUE TITLE
Product Analytics produces different results for the same query

### ISSUE THREAD

**Issue by nitrag** [PostHog/posthog#21766]
## Bug description

I am confused with the data coming back from my product analytics. I've got two almost/identical Funnels that don't add up. In an act of desperation I change the second Funnel to be idential in query/configuration to the first and - the results are different. The SQL tab shows the same query.

![1](https://github.com/PostHog/posthog/assets/197010/61494a99-ee13-4bb6-b4eb-e6ca441e658a)

![2](https://github.com/PostHog/posthog/assets/197010/f8f986da-ac73-4f87-86b5-133a6da82ec7)

![Screenshot 2024-04-23 at 12 56 32 PM](https://github.com/PostHog/posthog/assets/197010/a5fbf6be-a23b-4c83-ad24-dafd4494823c)

### Debug info

```shell
- [x] PostHog Cloud, Debug information: Session: https://us.posthog.com/project/sTMFPsFhdP1Ssg/replay/018f0bbd-c2d4-79bd-9c06-235202ba4e88?t=1984 
Admin: http://go/adminOrgUS/018e9fb7-0c81-0000-a287-7bd370d2f132 (Project: 62116)
Sentry: http://go/sentryUS/62116
- [ ] PostHog Hobby self-hosted with `docker compose`, version/commit: [please provide]
- [ ] PostHog self-hosted with Kubernetes (deprecated, see [`Sunsetting Kubernetes support`](https://posthog.com/blog/sunsetting-helm-support-posthog)), version/commit: [please provide]
```

**Comment by mariusandra** [comment]
Hey, the "SQL" tab is for writing a new query. You can click "..." --> "Edit SQL directly" on the top to see the SQL behind the funnels. Hopefully the difference will be obvious then. The screenshots do look the same 🤔

**Comment by nitrag** [comment]
Closing until I can more consistently reproduce.
