### ISSUE TITLE
Query failing when trying to get one of the event properties

### ISSUE THREAD

**Issue by grzegorzkrukowski** [PostHog/posthog#21770]
### Bug Description
*If you are on PostHog Cloud it would be really valuable if you can share any links where the problem occurs. This speeds up our ability to troubleshoot tremendously.*

## How to reproduce
1. Create a chart for "App Updated" events based on it's "isAutomaticUpdate" property
2. Check the error appearing on the UI

## Additional context

We are tracking "App Updated" events with "isAutomaticUpdate" properties - you can see it here:
![CleanShot 2024-04-23 at 20 48 28@2x](https://github.com/PostHog/posthog/assets/1301068/ea4a107d-5769-476c-9b4d-dff38ca070c4)

When trying to create a breakdown it shows that all of them have "none" - which is not true as you can see of the previous screenshot:
![CleanShot 2024-04-23 at 20 49 37@2x](https://github.com/PostHog/posthog/assets/1301068/db8d4c5d-7493-4751-9849-a3706b7b786f)

While filtering them by that property, there is an error thrown:
![CleanShot 2024-04-23 at 20 50 37@2x](https://github.com/PostHog/posthog/assets/1301068/16da4e07-3d91-4109-90ab-e1199d90ac29)

### Debug info

```shell
Session: https://us.posthog.com/project/sTMFPsFhdP1Ssg/replay/018f0c1f-9469-742b-876a-c7cbdc64d342?t=2649 (at https://us.posthog.com/project/62292/insights/new?dashboard=160296#panel=support%3Abug%3Aanalytics%3A)
Admin: http://go/adminOrgUS/018d892a-312e-0000-e873-aca164c818a6 (Project: 62292)
Sentry: http://go/sentryUS/62292
```

**Comment by MarconLP** [comment]
We are handling the issue in [this slack thread](https://posthog.slack.com/archives/C06PQEYH4QZ/p1713897457467539).
