### ISSUE TITLE
Unable to load dashboards

### ISSUE THREAD

**Issue by casendler** [PostHog/posthog#21773]
## Bug description

*Please describe.*
*If this affects the front-end, screenshots would be of great help.*

*If you are on PostHog Cloud it would be really valuable if you can share any links where the problem occurs. This speeds up our ability to troubleshoot tremendously.*

## How to reproduce

1. 
2.
3. 

### Debug info

```shell
Session: https://us.posthog.com/project/sTMFPsFhdP1Ssg/replay/018f0c54-c787-7391-a6cd-7fb1c35ed89c?t=264 (at https://us.posthog.com/project/48408/dashboard/135588#panel=support%3Asupport%3A%3A)
Admin: http://go/adminOrgUS/018cd6b7-fc49-0000-af43-ee911dfc4cb7 (Project: 48408)
Sentry: http://go/sentryUS/48408
```

**Comment by MarconLP** [comment]
tracking in https://github.com/PostHog/posthog/issues/21779
