### ISSUE TITLE
Viewing the record in Chrome and Firefox does not work

### ISSUE THREAD

**Issue by keaoner** [PostHog/posthog#21791]
## Bug description

Viewing the record in Chrome and Firefox does not work, We tested it on several computers (PC and Mac) and found that the only browser that worked was Safari.

## How to reproduce

1. Sign in
2. Getting to the recording
3. Trying to launch a recording

### Debug info

```shell
Session: https://us.posthog.com/project/sTMFPsFhdP1Ssg/replay/018f0f10-9bd9-7994-b817-4b4978ba1673?t=1200 (at https://eu.posthog.com/project/12680/events#q=%7B%22kind%22%3A%22DataTableNode%22%2C%22full%22%3Atrue%2C%22source%22%3A%7B%22kind%22%3A%22EventsQuery%22%2C%22select%22%3A%5B%22*%22%2C%22event%22%2C%22person%22%2C%22coalesce(properties.%24current_url%2C%20properties.%24screen_name)%20--%20Url%20%2F%20Screen%22%2C%22properties.%24lib%22%2C%22timestamp%22%5D%2C%22orderBy%22%3A%5B%22timestamp%20DESC%22%5D%2C%22after%22%3A%22-24h%22%2C%22event%22%3A%22doctrine_qa_search_and_response%22%7D%2C%22propertiesViaUrl%22%3Atrue%2C%22showSavedQueries%22%3Atrue%2C%22showPersistentColumnConfigurator%22%3Atrue%7D&panel=support%3Asupport%3A%3A)
Admin: http://go/adminOrgEU/018c1b56-3c59-0000-b95a-46493dfca4c6 (Project: 12680)
Sentry: http://go/sentryEU/12680
```

**Comment by white-gorilla** [comment]
Same for me.

**Comment by pauldambra** [comment]
hey @white-gorilla,

are you in the same org as @keaoner?

I use chrome when developing posthog so I know it's possible to playback in chrome 😊 this will be something specific to the site being recorded (and how it's interacting with PostHog)

**Comment by pauldambra** [comment]
never mind... I can see from our systems you're at the same organisation

**Comment by white-gorilla** [comment]
@pauldambra Thank you.

We tested on Chrome, Chromium, Firefox, without success, but it works with Safari, which is why we didn't understand it.
We haven't done anything in particular to interact with Posthog. It's very strange.
Could this be due to an SDK update, for example?

**Comment by pauldambra** [comment]
Super interesting that it works on Safari and really useful context thank you!

I've got your player open and can see that for some of the recordings browser CPU climbs to 100% and never recovers. My guess is we're hitting some unusual edge-case in re-processing the DOM in your site that we can never escape from.

We did update to the latest version of rrweb in the player recently so there are two threads to pull on here...

@daibhin 👀

**Comment by pauldambra** [comment]
I don't think it'll have an impact here but if you're able to update to the latest version of the SDK to see if that improves things that would be amazing @white-gorilla 

Would be great to at least rule it out!

**Comment by white-gorilla** [comment]
The last 3 records on our site now seem to work under Chrome.

**Comment by pauldambra** [comment]
We're just in the process of rolling back some changes 

* https://github.com/PostHog/posthog/pull/21806
* https://github.com/PostHog/posthog/pull/21816
* https://github.com/PostHog/posthog/pull/21812

There's definitely some pathological cases in the CSS processing that didn't exist before these upgrades.

Thanks for bearing with us!

**Comment by white-gorilla** [comment]
Thank you for all your efforts.

**Comment by pauldambra** [comment]
I think this is resolved now we've rolled back fully. Thanks for reporting!
