### ISSUE TITLE
Assets not loading with production docker image

### ISSUE THREAD

**Issue by mrsweaters** [PostHog/posthog#218]
**Describe the bug**
When loading the dashboard after install (after successfully creating the first user) the dashboard assets don't seem to be loading:

```
Refused to apply style from 'https://example.com/static/src.a2b27638.css' because its MIME type ('text/html') is not a supported stylesheet MIME type, and strict MIME checking is enabled.
Refused to apply style from 'https://example.com/static/src.a2b27638.css' because its MIME type ('text/html') is not a supported stylesheet MIME type, and strict MIME checking is enabled.
(index):1 Refused to execute script from 'https://example.com/static/src.a2b27638.js' because its MIME type ('text/html') is not executable, and strict MIME type checking is enabled.
```

**Expected behavior**
Assets are loaded.

**Additional context**
I had some difficulty getting to this point following the docker installation instructions. I had to manually run the database migrations by sshing into the container. Also, running behind nginx proxy on AWS if that helps.

**Comment by timgl** [comment]
@mrsweaters Thanks for reporting! Within the docker image, are the files in the `/code/posthog/frontend/dist` folder?

**Comment by mrsweaters** [comment]
Ah! No they are not, they are still in the `/code/frontend/dist` folder.

**Comment by timgl** [comment]
@mrsweaters Ah no sorry that was a typo, they should be in `/code/frontend/dist` so that is right.

 Can you try running `python manage.py collectstatic`, see if that helps?

**Comment by mrsweaters** [comment]
That didn't work but did result in this output:
```
You have requested to collect static files at the destination
location as specified in your settings:

    /code/staticfiles

This will overwrite existing files!
Are you sure you want to do this?

Type 'yes' to continue, or 'no' to cancel: yes

184 static files copied to '/code/staticfiles', 572 post-processed.
```

**Comment by timgl** [comment]
And specifically the file `/code/frontend/dist/src.a2b27638.css` does exist in the container?

**Comment by mrsweaters** [comment]
Yes, all the files that are being requested exist in `/code/frontend/dist`

**Comment by timgl** [comment]
What happens if you actually go to `https://example.com/static/src.a2b27638.css` ? Does it just redirect you to the login page?

**Comment by mrsweaters** [comment]
It doesn't actually redirect, but it does load the same html as the page itself. Could this be an issue with the nginx proxy?

```
server {
        listen 80;
        listen [::]:80;

        server_name example.com;

        location / {
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header Host $http_host;
            proxy_redirect off;
            proxy_set_header X-Forwarded-Proto $scheme;
            proxy_pass http://127.0.0.1:8000;
        }
}
```

**Comment by timgl** [comment]
Do you have the `IS_BEHIND_PROXY` environment variable set?

**Comment by timgl** [comment]
(P.S. I merged #219 which adds the migration command to the docker command, so you shouldn't have to manually run the migrate command in the future!)

**Comment by mrsweaters** [comment]
Yes, also `DISABLE_SECURE_SSL_REDIRECT`:

```
root@e6180cfa3e90:/code# echo $DISABLE_SECURE_SSL_REDIRECT
true
root@e6180cfa3e90:/code# echo $IS_BEHIND_PROXY
true
```

**Comment by timgl** [comment]
If you're comfortable, do you want to jump on a quick hangout to try to debug this together? I think I've exhausted what I can debug from afar!

https://meet.google.com/xic-uunt-dyg

**Comment by timgl** [comment]
^ Outcome of that: We couldn't work out exactly what was wrong. The files are all there, Django + Whitenoise seem to be working correctly. @mrsweaters Is going to try writing NGINX routes to use nginx to serve the files for now.

**Comment by mrsweaters** [comment]
This worked!

```
server {
        listen 80;
        listen [::]:80;

        server_name example.com;

        root /home/ubuntu/posthog/staticfiles;

        location /staticfiles {
            try_files $uri $uri/ =404;
        }

        location / {
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header Host $http_host;
            proxy_redirect off;
            proxy_set_header X-Forwarded-Proto $scheme;
            proxy_pass http://127.0.0.1:8000;
        }
}
```

**Comment by timgl** [comment]
@mrsweaters Turns out, this was actually a problem on our side, specifically with the production docker image. That is fixed now, so this should work without the nginx rules (if you pull the docker image again)

**Comment by mrsweaters** [comment]
Will do!

**Comment by mrsweaters** [comment]
I pulled down the latest docker and now I'm getting a 500 error. Will look into it. Not sure what happened.
