### ISSUE TITLE
Webhooks (Slack/Teams) and REST hooks (Zapier) not functioning on Clickhouse

### ISSUE THREAD

**Issue by paolodamico** [PostHog/posthog#2182]
## Bug description

Action-based webhooks are no longer being sent. Presumably, the issue could be due to events no longer being processed on Postgres, as the line that triggers the task seems to be only in the Postgres version, https://github.com/PostHog/posthog/blob/8600f7e80c85eda2f853a1f00d85f4806feda5d8/posthog/models/event.py#L351. Further, the logic for this task relies on Postgres's `Event` model.

## Expected behavior
Webhooks should be sent even if events are processed on Clickhouse. Webhooks should be sent only once even if the same event is processed on Clickhouse and Postgres.

## How to reproduce

1. Trigger an action that generates a webhook, see webhook not arriving.

## Environment

Cloud.

## Additional context

Reported by a user (see [conversation](https://posthog.slack.com/archives/C01C93MSLBU/p1604336748042500)).

**Comment by razor-x** [comment]
We just started getting slack web hooks again from app.posthog.com. However it seems we get double notifications for each event now.

**Comment by EDsCODE** [comment]
addressed. double is being fixed #2340

**Comment by razor-x** [comment]
We stopped getting double events, but now events are either severely delayed or not sent at all.

**Comment by EDsCODE** [comment]
We recently had a outage due to a load issue and the slack implementation was involved. We’re still investigating and working on a reimplementation. Sorry for the spottiness with this feature! I’ll reopen this issue and keep it updated when resolved.

**Comment by paolodamico** [comment]
Reminder to remove warnings from #2568 when this is addressed

**Comment by Twixes** [comment]
For context, this is not just webhooks, but REST hooks (Zapier triggers) as well, crippling the "Action performed" trigger in Zapier.

**Comment by EDsCODE** [comment]
Webhooks has been renabled [here](https://github.com/PostHog/posthog/pull/2664)
