### ISSUE TITLE
TypeError: Cannot read properties of null (reading 'tiles')\n

### ISSUE THREAD

**Issue by dsert1** [PostHog/posthog#21833]
## Bug description

*Please describe.*
*If this affects the front-end, screenshots would be of great help.*

*If you are on PostHog Cloud it would be really valuable if you can share any links where the problem occurs. This speeds up our ability to troubleshoot tremendously.*

## How to reproduce

1. 
2.
3. 

### Debug info

```shell
Session: https://us.posthog.com/project/sTMFPsFhdP1Ssg/replay/018f12b4-9249-7bba-8eab-ef677b3decc5?t=153 (at https://us.posthog.com/project/52815#panel=support%3Abug%3Aanalytics%3A)
Admin: http://go/adminOrgUS/018d7ff5-197a-0000-2809-7a315f228ae0 (Project: 52815)
Sentry: http://go/sentryUS/52815

Upon login
```

**Comment by MarconLP** [comment]
Hey @dsert1, it seems like no default dashboard was set, which caused this issue. I've set one of your dashboards as the default one.
