### ISSUE TITLE
Website suddenly became so slow, that it's impossible to use it

### ISSUE THREAD

**Issue by Bi0max** [PostHog/posthog#21836]
## Bug description
Dear Team,

I've been actively using PostHog for around 3 months now. So far it worked very well.
But around 1-2 weeks ago funnel insights became painfully slow. I am still on a free subscription, so I would assume that I don't really have so many events and queries cannot be so slow because of the amount of data.
It does not happen only for a new funnel, but it happens also for funnels, which I created before and which worked fine before.

There are two problems to be precise:
1. The funnel itself takes many minutes to load.
2. When I try to get the list of people for each step - it takes even longer (more than 10 minutes).
See "How to reproduce" and "Additional Context" for links and screenshot.

I tried different browsers and different internet connections + VPN, but nothing fixed the problem.

## How to reproduce

1. Open https://eu.posthog.com/project/3511/insights/PzrqVSBH
4. Try to open a least of people from any step. Takes more than 10 minutes.
5. When the list finally opened, I wanted to export it, but it's showing "Export starting..." for half an hour already. I think it'll never happen.

## Additional context
Screenshot:
![image](https://github.com/PostHog/posthog/assets/4247432/9522581e-5a8d-4fdd-9d3c-cfa9445c09ec)

### Debug info

```shell
Session: https://us.posthog.com/project/sTMFPsFhdP1Ssg/replay/018f13df-a5c3-75f9-afd2-f1f38f704faa?t=2267 (at https://eu.posthog.com/project/3511/insights/PzrqVSBH/edit#panel=support%3Asupport%3A%3A)
Admin: http://go/adminOrgEU/0186eb34-4099-0000-3a6a-8848647b0fc2 (Project: 3511)
Sentry: http://go/sentryEU/3511
```

**Comment by mariusandra** [comment]
Hey @Bi0max thanks for reporting! 

We rolled out new funnels, and it appears some users are experiencing problems with funnels with a lot of steps plus breakdowns. I've rolled back the flag for you now, and will only re-launch it once they work well again.
