### ISSUE TITLE
I can't edit my experiment.  When I click 'Save as Draft' I get the following error

### ISSUE THREAD

**Issue by JasonRotatingRoom** [PostHog/posthog#21832]
## Bug description

I get this error when trying to edit this experiement https://us.posthog.com/project/64379/experiments/30235

It occurs when clicking 'Save as Draft'
## How to reproduce

1.  go to experiment https://us.posthog.com/project/64379/experiments/30235
2.  Add a second variant
3.  Click 'Continue' and then 'Save as Draft
<img width="426" alt="Screen Shot 2024-04-24 at 7 11 23 PM" src="https://github.com/PostHog/posthog/assets/158104549/07500f08-2cfa-465b-b09d-670e9b745d73">

### Debug info

```shell
Session: https://us.posthog.com/project/sTMFPsFhdP1Ssg/replay/018f125a-fa42-755b-83ee-8afc9954472c?t=398 (at https://us.posthog.com/project/64379/experiments/30235#panel=support%3Asupport%3A%3A)
Admin: http://go/adminOrgUS/018eee61-96c5-0000-22a3-869520d10667 (Project: 64379)
Sentry: http://go/sentryUS/64379
```

**Comment by dmarticus** [comment]
@JasonRotatingRoom, are you still having this issue?  I took a look at it and it looks like this experiment has been deleted.
