### ISSUE TITLE
Supabase connection

### ISSUE THREAD

**Issue by tthuilli** [PostHog/posthog#21875]
## Bug description

Hey guys, I can't link supabase as an external source.
I click on the next button and nothing happens.

I'm trying to link the "facebook" table under "marketing scheme". But I don't understand where to specify 'facebook" table where my dbname is "postgres" (cf supabase connection info). Those info work with every other tool btw so I'm sure they are functionnal.

Screenshot from posthog: 
![CleanShot 2024-04-26 at 12 16 48](https://github.com/PostHog/posthog/assets/11270901/ef2cf467-0e89-4d15-94f5-21874c57a620)

Screenshot from supabase:
![CleanShot 2024-04-26 at 12 17 28](https://github.com/PostHog/posthog/assets/11270901/26dc5ee4-a4e2-4a55-86b7-a0597740a436)

### Debug info

```shell
Session: https://us.posthog.com/project/sTMFPsFhdP1Ssg/replay/018f18d0-1292-71d7-8c3c-b375aabf7f76?t=193 (at https://us.posthog.com/project/54722/data-warehouse/new#panel=support%3Asupport%3A%3A)
Admin: http://go/adminOrgUS/018dc9c3-0bd8-0000-fe80-2914a151ab37 (Project: 54722)
Sentry: http://go/sentryUS/54722
```

**Comment by Gilbert09** [comment]
Hey, late reply, but you can select which tables from the schema you'd like to sync on the next step of connecting the source
