### ISSUE TITLE
tooltips appear underneath insights graph during loading

### ISSUE THREAD

**Issue by jamesefhawkins** [PostHog/posthog#2194]
## Bug description

A small one, but it is a commonly used page:

* Go to insights
* Hover over a dropdown to produce a tooltip
* It appears below the top layer of the graph *whilst* it loads (it's fine once it has loaded)

![Screenshot 2020-11-03 at 13 49 25](https://user-images.githubusercontent.com/47497682/97993096-8157f280-1ddb-11eb-926c-a1cbce0ee965.png)

**Comment by yakkomajuri** [comment]
I believe this is fixed - can you confirm?

**Comment by Twixes** [comment]
Fixed.
