### ISSUE TITLE
Allow total count by breakdown

### ISSUE THREAD

**Issue by timgl** [PostHog/posthog#2197]
## Is your feature request related to a problem?

Say I'm passing through team_id for all of my users. I want to be able to break down by team_id, but then I want a total count of unique teams (for a certain day/filter/time period etc)

## Describe the solution you'd like

When breaking down by a property, I want to be able to tick a box below it that will give me the unique count of the total number of variations (rather than each individual variation)

## Describe alternatives you've considered

Manually count up everything

**Comment by hassy** [comment]
+1 for this. We're using Posthog for product analytics in [Artillery](https://artillery.io). One of the metrics we'd like to track is the number of unique endpoints being tested by Artillery (via a hash of the URL). At the moment we'd have to rely on writing a bit of custom code to query the Posthog API and count those up. It'd be nice to have this built into Posthog itself.

**Comment by pauldambra** [comment]
related https://github.com/PostHog/posthog/issues/1167

we _probably_ need the total available in order to do stacked charts

**Comment by Twixes** [comment]
Now possible by using a HogQL expression in the breakdown (e.g. `countDistinct(person.properties.team_id)`).
