### ISSUE TITLE
Bug report: Legend charts displays event name instead of series custom name

### ISSUE THREAD

**Issue by slshults** [PostHog/posthog#21988]
## Bug description
The chart legend is displaying the event name instead of the custom name given to the series

## How to reproduce
1. Edit an existing insight, or create a new insight
2. Select a chart for the time series
3. Under `Detailed results` click the edit icon and set custom names for one or more series
4. Click the `Options` menu for the chart and tick the box for `Show legend`

![CleanShot 2024-04-30 at 08 55 56@2x](https://github.com/PostHog/posthog/assets/227448/52b6544d-a193-435c-9ec7-b8bd6fa9805b)

## Additional context
From: https://posthoghelp.zendesk.com/agent/tickets/12985

### Debug info

```shell
- [ ] PostHog Cloud, Debug information: [please copy/paste from https://us.posthog.com/settings/project-details#variables]
- [ ] PostHog Hobby self-hosted with `docker compose`, version/commit: [please provide]
- [ ] PostHog self-hosted with Kubernetes (deprecated, see [`Sunsetting Kubernetes support`](https://posthog.com/blog/sunsetting-helm-support-posthog)), version/commit: [please provide]
```

**Comment by mariusandra** [comment]
This got fixed here: https://github.com/PostHog/posthog/pull/21986
