### ISSUE TITLE
Enhance email setup status in the instance status page

### ISSUE THREAD

**Issue by Twixes** [PostHog/posthog#2198]
## Is your feature request related to a problem?

It's difficult to determine whether email sending is configured properly and whether it works.

## Describe the solution you'd like

We have the Instance Status page, which could also contain email configuration details, with a link to a Docs guide on setting this up (PostHog/posthog.com#487). Ideally there'd also be a way to test whether emails are actually sent.

## Describe alternatives you've considered

Praying to the SMPT gods.

## Additional context

User on Slack had trouble with invite emails.

**Comment by Twixes** [comment]
Addressed. Next step should be #496 (eventually).

**Comment by paolodamico** [comment]
Maybe worth keeping this around? I think we should link to the configuration docs from here as the issue suggest. We could also show some of the configuration settings (e.g. HOST, PORT, USERNAME, ...). Finally, maybe we can also have a button to test delivery. Thoughts?

**Comment by Twixes** [comment]
Hm, I see, it's quite simplistic as is. I'll reopen and just change one word in the title then.

**Comment by paolodamico** [comment]
We now support setting email configuration via instance status page and we send a test email whenever email settings are updated.
