### ISSUE TITLE
Subscriptions are broken

### ISSUE THREAD

**Issue by MarconLP** [PostHog/posthog#22085]
## Bug description

![2024-05-21 at 14 49 14@2x](https://github.com/PostHog/posthog/assets/13001502/a74a8ac7-fae6-4e89-a895-08ab36ffab58)

## How to reproduce

1. Create an insight
2. Create a subscription
3. Wait for the subscription to be sent

## Additional context

https://posthoghelp.zendesk.com/agent/tickets/13105

**Comment by MarconLP** [comment]
+1 https://posthoghelp.zendesk.com/agent/tickets/13092 (moved to PostHog: https://us.posthog.com/project/2/support/tickets/15600)

**Comment by MarconLP** [comment]
+1 https://posthoghelp.zendesk.com/agent/tickets/13224 (moved to PostHog: https://us.posthog.com/project/2/support/tickets/15628)

**Comment by MarconLP** [comment]
+1 https://posthoghelp.zendesk.com/agent/tickets/13723 (moved to PostHog: https://us.posthog.com/project/2/support/tickets/16453)

**Comment by benhint** [comment]
We've been getting this since the 16th May. Is it related?
<img width="589" alt="image" src="https://github.com/PostHog/posthog/assets/124672718/05169af9-f56d-4b7f-ad97-10b229336295">

**Comment by MarconLP** [comment]
+1 https://posthog.com/questions/not-getting-insight-in-slack

**Comment by MarconLP** [comment]
+1 https://posthoghelp.zendesk.com/agent/tickets/13961 (moved to PostHog: https://us.posthog.com/project/2/support/tickets/16125)
