### ISSUE TITLE
Bug report: "Click to view persons" modal appears, then disappears without displaying list

### ISSUE THREAD

**Issue by slshults** [PostHog/posthog#22081]
## Bug description

While viewing or editing an insight, after "Click to view persons" on a chart, table, number etc., the persons modal appears, then disappears a few hundred milliseconds later without displaying the list.

In the support ticket that led me to find this bug, the user mentioned an error after clicking the "Save as cohort" button, and that an attempt to export the csv returned only 10k rows. 

## How to reproduce

1. View or edit [this insight](https://eu.posthog.com/project/15566/insights/n7riWbOb) 
2. Hover over the big number and "Click to view persons"
3. See the modal appear
4. See the modal disappear 

## Additional context
From: https://posthoghelp.zendesk.com/agent/tickets/13099

### Debug info

```shell
Session: https://us.posthog.com/project/sTMFPsFhdP1Ssg/replay/018f3fe9-66f2-7f90-b7e9-fc1bba46f7fb?t=193 
Admin: http://go/adminOrgUS/4dc8564d-bd82-1065-2f40-97f7c50f67cf (Project: 2)
Sentry: http://go/sentryUS/2
```

**Comment by slshults** [comment]
+1 https://posthog.slack.com/archives/C04BU5FS2Q7/p1714768287432759

**Comment by spcx86** [comment]
i am willing to take this up. Hope that's okay. will do some primary investigations and will report back in a day or two.

**Comment by slshults** [comment]
@mariusandra I'm able to reproduce this problem in different accounts again.

**Comment by slshults** [comment]
+1 https://posthog.slack.com/archives/C06KJQ2RH1A/p1715026297090679

**Comment by slshults** [comment]
This was issue was fixed by this PR: https://github.com/PostHog/posthog/pull/22118
