### ISSUE TITLE
Recurring surveys & sentiment tracking

### ISSUE THREAD

**Issue by vangelis-b** [PostHog/posthog#22099]
## Is your feature request related to a problem?

Currently, surveys can't be scheduled to repeat, making it difficult to track sentiment changes over time (e.g., NPS). Manually recreating surveys every 6 months is cumbersome and error-prone.

## Describe the solution you'd like

Allow scheduling surveys to recur (e.g., every 6 months) and visualize response changes over time with graphs. This would benefit customer success and product teams.

## Describe alternatives you've considered

One option is to manually create a new survey every 6 months or so and send it to the same user group. However, this is a time-consuming process and it creates a lot of manual work to compare the data between surveys.

## Additional context

It would be great if you could replicate the approach used by [Pendo](https://support.pendo.io/hc/en-us/articles/360033527151-Set-up-an-NPS-survey#h_01HGD0SKYSRB6SNKXBFJ1QG7M7) for this.

![image](https://github.com/PostHog/posthog/assets/29815828/a34086ff-4ea9-4ad3-b245-ba898133e1e9)

### Debug info

```shell
- [ ] PostHog Cloud, Debug information: [please copy/paste from https://us.posthog.com/settings/project-details#variables]
- [ ] PostHog Hobby self-hosted with `docker compose`, version/commit: [please provide]
- [ ] PostHog self-hosted with Kubernetes (deprecated, see [`Sunsetting Kubernetes support`](https://posthog.com/blog/sunsetting-helm-support-posthog)), version/commit: [please provide]
```

**Comment by Phanatic** [comment]
@vangelis-b , I'm working on implementing this feature and would love to show you what I have so far. If you're willing, can you please email me at phani at posthog dot com so we can set something up?

**Comment by marandaneto** [comment]
You can do this with https://posthog.com/docs/surveys/creating-surveys#completion-conditions "Repeat on a schedule"
