### ISSUE TITLE
disable session playback for localhost

### ISSUE THREAD

**Issue by jamesdorfman** [PostHog/posthog#22122]
## Is your feature request related to a problem?

I want to save session playbacks for all users on my website, except for myself.
This is because I don't want to clutter my posthog with all my testing sessions.
I understand that I can just filter out internal users in the posthog dashboard, but this doesn't actually prevent the recordings from being created, and so my own sessions count towards my quota.

I want to trigger a setting which prevents certain users (either by ID or by the URL from where they are accessing the site) from having their sessions recorded.

## Describe the solution you'd like

I want to be able to exclude my website's developers (aka users on localhost) from generating session recordings.

## Describe alternatives you've considered

The only way I can find to do what I want, is to create a feature flag which checks the URL.
However, feature flags aren't available until an event is issued (according to the posthog docs), and I've which means that very short sessions.

In other words, using a feature flag seems to lead my recordings to start only as soon as an event is issued, which means they don't start as soon as the page loads. 

How can I fix this? Do I need to issue an event right on page load, or is there a way to exclude a specific URL from being recorded without using a feature flag?

In summary: feature flag doesn't trigger right on page load -- how do I stop localhost from being recorded right on page load? Thanks! 

### Debug info

```shell
- [x] PostHog Cloud, Debug information: [please copy/paste from https://us.posthog.com/settings/project-details#variables]
- [ ] PostHog Hobby self-hosted with `docker compose`, version/commit: [please provide]
- [ ] PostHog self-hosted with Kubernetes (deprecated, see [`Sunsetting Kubernetes support`](https://posthog.com/blog/sunsetting-helm-support-posthog)), version/commit: [please provide]

Session: https://us.posthog.com/project/sTMFPsFhdP1Ssg/replay/018f4f25-f6c8-7373-b145-954255e88b63?t=36546 
Admin: http://go/adminOrgUS/018dd852-e0d0-0000-bbb6-0fda53870fef (Project: 55170)
Sentry: http://go/sentryUS/55170
```

**Comment by pauldambra** [comment]
Hey, it's not something that's completely built in...

The best way here would either be something like https://posthog.com/docs/session-replay/how-to-control-which-sessions-you-record#with-your-own-code

Or,, when running on localhost you would use a different posthog config and not start recording

**Comment by pauldambra** [comment]
Yep, having slept on it I think the easiest thing is a config something like

```
disable_session_recording: window.location.hostname === 'localhost',
```
