### ISSUE TITLE
Sprint - May 13 to May 24, 2024

### ISSUE THREAD

**Issue by benjackwhite** [PostHog/posthog#22184]
# Global Sprint Planning

## 3 things that might take us down

1. Clickhouse fire rages
2. 
3.

# Team sprint planning

For your team sprint planning copy this template into a comment below for each team.

```
# Team ___

**Support hero:** ___

## Retro

<!-- Grab the high and low priority items from last time and add whether that item was completed or not -->

- 

## Hang over items from previous sprint

<!-- For each item, decide to re-prioritise (and add below) or deprioritise -->

- Item 1. prioritised/deprioritise

## OKR

1. OKR, status (red/yellow/green) and action points if yellow/red


### High priority

-

### Low priority / side quests

-

```

**Comment by benjackwhite** [comment]
# Team Infra

## Hang over items from previous sprint

1. 🟡  SOC2 Audit work came in with a fair amount of follow up work taking a good chunk of @danielxnj 
2. 🟡 Switched gear to try Loki as our central log system to tick the SIEM box @danielxnj 
 - Still a lot of work here to make it performant, get all the logs from different systems in etc.
3. 🟢 Noticed big costs in Cloudwatch logs - investigated where it was coming from and dropped the issuse (halving the cost) @frankh 

1. 🟢 Get Vault UI and roles and accounts setup @danielxnj 
- We will let this take a back seat to focus on other things atm
5. 🟢 New kafka setup (i.e. correct zones and size for migrating over to) @danielxnj 
6. 🔴  Get some or all logs running into SIEM tool @danielxnj 
- Ditched Wazuh as it seemed like a maintenance nightmare
8. 🔴  Documentation for Canary deploys so that people can use them @frankh 
9. 🟢 Capacity planning dashboard with additional alerting @frankh 
10. 🟢 Verify and then document / publicize the IP allow list stuff @benjackwhite
11. 🟢 Rollout security improvement fixes @benjackwhite 
12. 🟡 CDP v1.5 - Webhooks destination filtered by Action @benjackwhite 

## OKR

1. 💪 Deploy with confidence 🟢 
- Finalize our Canary Deploy process 🟡
5. 🚨 Improved alerting and monitoring 🟢 
- SIEM work has made this a priority
6. 🔒 Deeper Security 🟡 
8. 💰 Continued cost control 🟢 

### High priority

1. Look into Loki performance as we will base our SIEM plan on it @frankh 
2. Get as many other log sources into Loki as possible (Kubernetes audit logs, Cloudtrail, SQL/Clickhouse queries, Metabase, HogQL queries) @danielxnj 
3. Get more useful auditing logs out of Django (auth attempts, access logs, HogQL queries) @benjackwhite 
4. Get Metabase setup to tick the audit boxes (auditing, SSO etc.) @frankh @danielxnj 
5. Continue with Soc2 Audit follow up @danielxnj 
6. Fix all remaining High/medium pen test outcomes @benjackwhite 
7. Offsite!

**Comment by EDsCODE** [comment]
# Team Data Shack

### OKR Q2 2024

### Objective

**Release data warehouse to everyone**

* **Key Results:**
    * Integration first experience
         * schemas are reliable
         * modeling of each integration is clear
         * Good automatic roll up views and joins
         * Wizard to onboard people
    * Establish a solid pattern to build integrations
    * Complete data warehouse experience in the rest of the app (insights, feature flags, experiments)

**James as a Service -> Clickhouse as a Service**

* **Key Results:**
    * Better Visibility
         * Regularly testing backups
         * Monitoring/alerting
         * Mutations
         * Moves
    * Management
         * Managing/killing mutations
    * Self Serve
         * Schema design feedback (James non blocking
         * Schema management   
    * Automation
         * Replace/Upgrade replicas
         * Upgrading to 24.04
         * Disk configs 
 
### Retro

**Product**

- [x] @EDsCODE Postgres integration all connection options. Spike of customer requests that really want this working. Solved the immediate bugs here. Did not end up building out connection options.
- [x] @EDsCODE ^shifted focus to resolving issues with joined person property filtering
- [x] @Gilbert09 Schema Validation workflow. Ability to edit schema that's interpreted by clickhouse


**Infra**
- [ ] Fully upgrade CH clusters to 23.12 and fix data discrepancies
- [ ] Deploy CH on EKS cluster against NVME storage
- [ ] Develop plan for CHKeeper migration
- [ ] Delete need to be fixed

### High priority

- offsite

**Product**
- making the UI changes to move sources into pipeline 3000

**Infra**

**Comment by robbie-c** [comment]
# Team Web Analytics

**Support hero:** n/a 

## Retro
High priority
- [x] get session property filters in web analytics rolled out and working for all queries on the page (if not finished this sprint)

Low priority
- [ ] Rolling out the session property filters for all queries, not just on web analytics
- [ ] Ploughing through small feature requests for web analytics

Rolled out web analytics (with Beta tag) to 100%, but I'm not happy with query performance. Based on a hunch, I did a spike of using UUIDv7s (casted to UInt128) for the session id, so far it looks like it's a significant speedup, around 87% on clickhouse cloud, but needs to be tested in a prod-like env. See [WIP RFC](https://github.com/PostHog/product-internal/pull/601)

## Hang over items from previous sprint
* deprioritised behind perf work: Rolling out the session property filters for all queries, not just on web analytics

## OKR

1. Make querying fast enough for large customers
2. Do personless events work where necessary (unknown amount of work)
3. Iterate on customer feedback
4. Product management work

### High priority
- finish this spike on uuidv7s
- if it's worth doing
  - write the SQL for the new sessions table that uses is
  - write and run a proper backfill job
  - switch the hogql sessions table over to the new table
  - make sure docs / sdks make it clear enough that session_ids should be a UUIDv7
- then roll out session properties elsewhere in the app

**Comment by neilkakkar** [comment]
# Team Feature Success

**Support hero:** @neilkakkar     
Days off:
Juraj:  3 days
Neil: 2 days

## Retro

- Surveys branching logic - @jurajmajerik - ❌
    - Focused on a seamless dev environment before working on branching
    - Refactoring survey popup code to make improvements easier
    - MDE for experiments 	
- Make sure Phani's onboarding goes well - @neilkakkar  ✅
- Create dumb feature flags service in rust, write down steps to make it production ready - @neilkakkar ✅ -> https://github.com/PostHog/posthog/issues/22131
- Make repeatedly showing dismissed surveys more ergonomic - https://github.com/PostHog/posthog/issues/17863 - @Phanatic 🟡
- Link survey security vulnerability - @Phanatic ✅


## Hang over items from previous sprint

---

## OKRs

1. Make sure feature flags can handle 10x current scale
2. Polish new experiments UI & collect feedback
3. Add most requested surveys functionality

### High priority

- Offsite hackathon + wrapup - @jurajmajerik  / @neilkakkar
- Surveys popup refactor - @jurajmajerik 
- Make sure Dylan's onboarding goes well - @neilkakkar 
- Implement the RFC for repeatable surveys - https://github.com/PostHog/meta/pull/203 - @Phanatic 

Stretch:
- https://github.com/PostHog/posthog/issues/22131 make some progress on rewrite - @neilkakkar 

### Low priority / side quests / maybe Neil will get to this next year

- Temporal queues for feature success - @neilkakkar 
- Setup instrumentation for flip-flopping problem of experiment significance - @neilkakkar
