### ISSUE TITLE
First Time Retention

### ISSUE THREAD

**Issue by EDsCODE** [PostHog/posthog#2219]
## Is your feature request related to a problem?

*Please describe.*
Provide a way to do first time retention

## Describe the solution you'd like
Be able to select an event that defines the user first appearing and then select the event that should be targeted to determine retention

## Additional context
@paolodamico brought up this point

**Comment by paolodamico** [comment]
For context, this relates to the introduction of different events for this report, one is the retention / core action event which is used to determine if a user was retained at a given period, and the other one is called the cohortizing event in Mixpanel and starting event in Amplitude, it's the event you use to assign users to cohorts. A user is assigned to a cohort if they triggered the cohortizing/starting event within period 0 of the cohort.

A separate topic is whether you have the option to use the cohortizing event not every time when the user triggered it but when the user triggered it **for the first time**. Doing an event for the first time is super helpful (and can be an experience that PostHog does better than alternatives) as it allows you to group users into mutually exclusive and collectively exhausting cohorts, which can help you understand the evolution of cohorts over time and holistically measure PMF.

> For reference, Amplitude / Mixpanel default to whenever the event occurred (i.e. not distinguishing between first use or not), and it's burdensome if you want to do the first time event. According to [this tutorial](https://help.mixpanel.com/hc/en-us/articles/360022537091-Retention-Deep-Dive-Course-#first-time-retention), "first time retention" is not actually the first time the user did an event, it just allows you to use a different cohortizing event, and the suggested way to do first time retention is by using an event that is only triggered once per user (e.g. sign up). Amplitude allows this with a _hacky_ [solution](https://help.amplitude.com/hc/en-us/articles/360040957432#historical-count-definition).

Finally worth mentioning this is what is currently blocking us from properly measuring our own retention.

**Comment by jamesefhawkins** [comment]
This is *very important* for us internally to judge product market fit even if we don't yet have users asking about it.

**Comment by EDsCODE** [comment]
#2325
