### ISSUE TITLE
Retroactively parse $host & $pathname

### ISSUE THREAD

**Issue by paolodamico** [PostHog/posthog#2223]
## Bug description

https://github.com/PostHog/posthog-js/commit/b6a7e8f1090849504ac8e6668eddc0132f4de098 introduced `$host` & `$pathname` PostHog properties to events captured with the web library. However events before Jun 18 don't have these properties properly set. This can be confusing when doing analyses because filters report data incorrectly and as a user you don't have context on when these properties were incorporated.

## Expected behavior

These properties should be present on all web events.

## How to reproduce

1. Look for any `$pageview` from before Jun 18.

## Environment

Both.

## Additional context

Very easy to miss in certain type of analyses where this is just an additional filter, can lead to very misleading conclusions.

**Comment by Twixes** [comment]
The downside of retroactive updating of (nearly) all events is that it's _really_ slow on large Postgres instances, so not sure if this would work well.

**Comment by Twixes** [comment]
This doesn't seem that relevant anymore + there'd be a significant amount of complexity around backfill, so I think we can deprioritize this.
