### ISSUE TITLE
Bug Report: Survey results display problem

### ISSUE THREAD

**Issue by slshults** [PostHog/posthog#22236]
## Bug description

In a survey, for a multiple choice question with a long list of choices, the results are displayed in an unexpected way (all permutations of answers are shown (instead of percentages of the selected choices), and the question results are overlapping other displayed results, making things unreadable:

![018f589a-35d2-0000-b13e-41bc41896fef](https://github.com/PostHog/posthog/assets/227448/08d83e00-1ad8-4070-a2eb-0b23dbb33834)

## How to reproduce

See [this survey](https://us.posthog.com/project/34631/surveys/018c251e-8bec-0000-5738-781499e35560) for an example of how to reproduce this issue.

## Additional context
From: https://posthoghelp.zendesk.com/agent/tickets/13309

### Debug info

```shell
Session: https://us.posthog.com/project/sTMFPsFhdP1Ssg/replay/018f5fd6-d0c5-732b-96c5-29a8bd6bf2ee?t=60 
Admin: http://go/adminOrgUS/0188ecb2-b2e2-0000-9b48-873a05a91443 (Project: 34631)
Sentry: http://go/sentryUS/34631
```

**Comment by jurajmajerik** [comment]
The displaying of permutations in this ticket was caused by incorrect formatting of survey responses (they use the API).

That said, we should still fix the UI overflowing issue.

**Comment by slshults** [comment]
+1 https://posthoghelp.zendesk.com/agent/tickets/17868 (moved to PostHog: https://us.posthog.com/project/2/support/tickets/20368)

![CleanShot 2024-09-10 at 15 29 04@2x](https://github.com/user-attachments/assets/fa9d92cc-53c4-42ce-817a-15e7ca258b7a)
