### ISSUE TITLE
Instance status reports get sent multiple times

### ISSUE THREAD

**Issue by timgl** [PostHog/posthog#2224]
## Bug description

Some instances sent instance status report thousands of times. I bet it's because of Celery retrying or something, as some of the queries are using COUNT(*) and can be very slow. We should use estimated row sizes instead probably.

## Expected behavior

Only sent 1 instance report per team

## How to reproduce

1. 
2. 
3. 

## Environment

- PostHog cloud or self-managed?
- PostHog version/commit

**Comment by paolodamico** [comment]
Related to #1552. I think it has to do with the way we process scheduled events, the same reason why emails got sent a ton of times.

**Comment by macobo** [comment]
Once you see the fix you will :facepalm:
