### ISSUE TITLE
self-hosted: runaway logging eats all disk space

### ISSUE THREAD

**Issue by feedanal** [PostHog/posthog#22250]
### Bug Description

This is part of self-hosted PH disk usage problem, see here for more cases: https://github.com/PostHog/posthog/issues/20101

Currently `plugins` service writes same logging message about 1000 times per second, resulting in __gigabytes__ of logs hourly:

```
{"log":"{\"level\":\"warn\",\"time\":1715351962073,\"pid\":144,\"hostname\":\"f9630160d2cc\",\"logContext\":{\"sessionId\":\"018f62e9-92b0-7efc-b50b-244460279199\",\"partition\":0,\"teamId\":1,\"topic\":\"session_recording_snapshot_item_events\",\"oldestKafkaTimestamp\":null,\"bufferCount\":0,\"referenceTime\":1715351962008,\"referenceTimeHumanReadable\":\"2024-05-10T14:39:22.008+00:00\",\"flushThresholdMs\":600000,\"flushThresholdJitteredMs\":457237.3769210211,\"flushThresholdMemoryMs\":548684.8523052253},\"msg\":\"[MAIN]  [session-manager] buffer has no oldestKafkaTimestamp yet\"}\n","stream":"stdout","time":"2024-05-10T14:39:22.242393767Z"}
```

Originates from: https://github.com/PostHog/posthog/blob/09134daaf77a64d1894a6cafac2a48ee7006a1cd/plugin-server/src/main/ingestion-queues/session-recording/services/session-manager.ts#L257

Needless to say, this is utterly useless and needs adjusting.

If there is no way to set log level (in 10 minutes of googling I could not find any setting or env var responsible), this should be fixed in the code OR by limiting log sizes inside `docker-compose.hobby.yml`:

```yml
        logging:
            options:
                max-size: 10m
```

## How to reproduce

1.  Start Posthog instance
2. Run out of space by lunch.
3. Repeat.

**Comment by feedanal** [comment]
Also, this may be responsible for very heavy CPU usage by `node dist/index.js`. 
Posthog in general is VERY unoptimized resource-wise (which is compensated by great functionality), but issues like this are simply blocking as we promptly ran out of space on a 500gb server, and I can see it happening on a 2tb very soon as well.

**Comment by pauldambra** [comment]
what's interesting here is that we aren't expecting to be in a position where we receive a recording message - which is what causes creation of a session manager, but then have no messages added to that session manager

(clearly you're in that position so it's not unexpected for you 🙈 but I'd love to understand how you are)

**Comment by pauldambra** [comment]
you can see here we create a session manager and then immediately add a message to it

https://github.com/PostHog/posthog/blob/c2a5d6162ab9cf36d2c1101817480f4223d1310d/plugin-server/src/main/ingestion-queues/session-recording/session-recordings-consumer.ts#L307-L328

**Comment by pauldambra** [comment]
Apparently you can set the `LOG_LEVEL` environment variable to control the logs

**Comment by pauldambra** [comment]
So...

we use the pino log library in the plugin server...

https://github.com/PostHog/posthog/blob/37a08e808ca198f2e26916bf9294069f6080819f/plugin-server/README.md?plain=1#L133

with supported values here https://github.com/PostHog/posthog/blob/224a5d5d0c07f880b19dbc02cce2f07b965023c0/plugin-server/src/types.ts#L39-L46

**Comment by pauldambra** [comment]
the default level if not overridden in the environment is info

**Comment by pauldambra** [comment]
I'll close this since it's a call out to an item in https://github.com/PostHog/posthog/issues/20101

and copy my comments above there
