### ISSUE TITLE
Add NOT operators to survey URL targeting rules

### ISSUE THREAD

**Issue by dmarticus** [PostHog/posthog#22281]
## Is your feature request related to a problem?

Not really, just feels like an easy feature to implement that we don't have yet.

<img width="592" alt="image" src="https://github.com/PostHog/posthog/assets/4853149/9f2114aa-1d49-4ac6-8ee5-8e0a8d657197">

## Describe the solution you'd like

Feels like all of these matchers should have an equivalent NOT matcher.  Could be useful for users to filter out fields containing or equal to thinks without writing a RegEx rule.

Obviously, this can be worked around, but it seems like a quality-of-life improvement.

**Comment by shawnlikescode** [comment]
Hi! Can I try to implement this one?

Are you thinking just doesn't contain and doesn't equal or should there also be doesn't match regex?

**Comment by dmarticus** [comment]
Hi @shawnlikescode, thanks for your interest!  I was thinking that we'd implement the following matchers:

- doesn't contain
- doesn't equal
- doesn't match regex

like we do with the User Property targeting

<img width="659" alt="image" src="https://github.com/PostHog/posthog/assets/4853149/7e8cc49e-648b-4df6-82c5-fdd8c4b5eb69">

Happy coding, and I look forward to seeing what you come up with :)

**Comment by shawnlikescode** [comment]
Hey, @dmarticus! Working on this now. I think I understand what's required, but I just want to verify before I get all gung ho and dive in. 

From what I gather, this feature will involve two PRs:

1. In the Posthog repo, I'll add the NOT operator options for the selection input on URL targeting.
2. In the posthog-js repo, I'll update the validations in src/posthog-survey.ts.

Does this sound correct? Thanks!

**Comment by neilkakkar** [comment]
That sounds about right :)

**Comment by dmarticus** [comment]
Closed thanks to @shawnlikescode's community contribution!
