### ISSUE TITLE
Improve /paths: filtering and actions

### ISSUE THREAD

**Issue by jamesefhawkins** [PostHog/posthog#223]
**Is your feature request related to a problem? Please describe.**
It is currently impossible to filter Paths by time, by cohort.

It is also impossible to include actions other than pageviews in a path.

**Describe the solution you'd like**

Make it possible to filter paths by:

* Time (show traffic between set dates, so it is possible to understand if after a change was made to the website if it impacted performance)
* Cohort (show traffic for one or more cohorts only)
* Properties (just X UTM tag, or just company Y)

Less important for now....

* Make it possible to display ANY actions not just pageviews, so it is possible to understand ie how people use a single page application and the series of actions they are usually taking.
  * When the above happens, make it possible to add/remove actions from those which we want to include in the paths

**Describe alternatives you've considered**

There isn't another way to do this yet.

**Comment by timgl** [comment]
I think the interface for this should be the exact same as Action Trends
![image](https://user-images.githubusercontent.com/1727427/76026938-95fa8880-5ee4-11ea-9544-6470f6784d88.png)

Though in this case just have 'Add event property filter' and nothing else (for now!)

**Comment by Twixes** [comment]
Pretty much all possible now.
