### ISSUE TITLE
[Clickhouse] refactor tech debt

### ISSUE THREAD

**Issue by timgl** [PostHog/posthog#2231]
Objective: Make it as easy as possible to add new analytics views and features

- Can we move the Django ORM queries to be SQL as well
- Let's make the property filter functions a bit easier to use/more robust/document them
- Filters should be unified
- More tests for individual users

[Watch full discussion on YouTube](https://www.youtube.com/watch?v=vOr3N08udes&feature=youtu.be)

**Comment by Twixes** [comment]
I think this particular issue can be closed now.
