### ISSUE TITLE
Pull other relevant profile fields from login with google integration

### ISSUE THREAD

**Issue by jamesefhawkins** [PostHog/posthog#2235]
## Is your feature request related to a problem?

When users login with Google, it'd be helpful to get their basic profile metadata (like name) into their user profile. That would make it easier to understand the type of users we're a good fit for.

I *think* we only grab email address at the moment (but may be wrong, please close this if so!)

**Comment by Twixes** [comment]
We do grab the name, is there other specific metadata we could use?

**Comment by paolodamico** [comment]
Per conversation from https://github.com/PostHog/retention/issues/8 it'd be very interesting and helpful if we could (with express consent obviously) automatically send invites to all the team members from the user's organization. We could even fetch the contact list and then allow users to select to which users send invites.

**Comment by Twixes** [comment]
I believe we're already pulling everything we need.
