### ISSUE TITLE
Help other OS communities to find us

### ISSUE THREAD

**Issue by jamesefhawkins** [PostHog/posthog#224]
**Is your feature request related to a problem? Please describe.**
PostHog prides itself on being developer-friendly.

This means every edition should easily integrate with other languages.

We should reach out to a few of these communities to let them see what we're up to.

It is important to work out where is *appropriate* to share it within each of these places... many of them have "show and tell" type sections in their forums/slack.

**Describe the solution you'd like**
- [ ] find the JS community
- [ ] find the node community
- [ ] find the Python community
- [ ] find the Ruby community
- [ ] find the PHP community
- [ ] find the Go community
- [x] find the Django community: #226
- [ ] find the React community

**Describe alternatives you've considered**
We can be sad at not have other communities take advantage of product analytics to build cooler stuff.

**Comment by yakkomajuri** [comment]
As part of a cleanup, we should probably close this as ToF acquisition discussion has evolved to many other places from a year ago.
