### ISSUE TITLE
UI color mismatch

### ISSUE THREAD

**Issue by EDsCODE** [PostHog/posthog#2242]
## Bug description

*Please describe.*  
- new UI should have consistent colors

*If this affects the front-end, screenshots would be of great help.* 
<img width="509" alt="Screen Shot 2020-11-05 at 3 40 49 PM" src="https://user-images.githubusercontent.com/13127476/98255117-10374d00-1f4b-11eb-9d6d-6f0b0309a012.png">

**Comment by paolodamico** [comment]
Thanks for reporting! Fix coming up in #2238.
