### ISSUE TITLE
Large gray bar at the bottom of the /signup page

### ISSUE THREAD

**Issue by Twixes** [PostHog/posthog#2245]
## Bug description

On `/signup`, the bottom of the page below the signup form is a big gray (#f2f2f2) bar.

<img width="1008" alt="Screen Shot 2020-11-05 at 16 42 02" src="https://user-images.githubusercontent.com/4550621/98262487-f6672b80-1f85-11eb-88f6-40c00eebc335.png">

This seems to have been introduced by #2114. – previously `body` background was white by default, now it's this gray.

## Environment

- master

**Comment by paolodamico** [comment]
The reason for the body being gray is so when the app is loading it conveys that there's _something_ going on, perhaps we just need to do `height: 100%` in this page? I'll fix this, thanks for bringing it up!
