### ISSUE TITLE
Heatmaps (click/tap, scrolling, mouse movement, attention maps)

### ISSUE THREAD

**Issue by mayeraaa** [PostHog/posthog#22479]
### Feature request

Hi
Please add the functionality of heatmaps: first of all click/tap and scrolling maps, and secondly mouse movement (hover) and attention maps. This is very useful for analyzing user behavior. Moreover, you already have good working events and session recordings.
Ideally on all clients: web, iOS, android.
References: [hotjar](https://www.hotjar.com/heatmap-analytics/), [mouseflow](https://mouseflow.com/?r=prd-bhms), [fullstory](https://www.fullstory.com/platform/heatmaps/), [smartlook](https://www.smartlook.com/heatmaps/), [heap](https://www.heap.io/platform/heatmaps) and others.

**Comment by pauldambra** [comment]
Hey @mayeraaa 

We very recently added click and scroll maps to the toolbar. If you are using the latest version of the web sdk this all works already. You can enable them here https://us.posthog.com/settings/project#heatmaps or in the posthog-js config

I don't think we have active plans for iOS and Android for heatmaps (but @marandaneto will know)

**Comment by marandaneto** [comment]
So far not planned yet but we are gathering interest in this [issue](https://github.com/PostHog/posthog/issues/19645).
Feel free to upvote the issue and add any input you may have, thanks.

**Comment by pauldambra** [comment]
I hope you enjoy web heatmaps! I'll close this since you can track mobile heatmaps in the other issue :)
