### ISSUE TITLE
Get rid of pandas and numpy

### ISSUE THREAD

**Issue by timgl** [PostHog/posthog#2248]
## Is your feature request related to a problem?

There's only 2 files where we use pandas, but pandas is 49MB and numpy is another 86MB, slowing down builds massively.

## Describe the solution you'd like

Replace pandas with a pure SQL/Python solution in
- posthog/queries/trends.py
- posthog/queries/sessions.py

Both of those have equivalent examples in Clickhouse (ee/clickhouse) that don't use Pandas.

## Describe alternatives you've considered

Continue using Pandas and clogging builds

**Comment by Twixes** [comment]
NumPy and pandas are often hugely faster at crunching numbers than pure Python though, so I'd argue that we could try to do the opposite and utilize them more.

**Comment by timgl** [comment]
Yeah but we don't actually use pandas to crunch numbers, we just use it to put the data we get back from the Django ORM into the right format (ie group together dates by cohort). If we move to using SQL instead of the ORM we should just be able to do this in SQL instead.

**Comment by cpankajr** [comment]
Hi, @timgl  I would like to try it. I had one question:
Do we have to replace pandas based logic with SQL based changes or Is it ok if I replace pandas functions with our custom python functions to get the same results

**Comment by timgl** [comment]
@cpankajr Awesome! I don't have a strong preference between the two, whichever is easier.
