### ISSUE TITLE
Action creation widget posts to insecure URL

### ISSUE THREAD

**Issue by mrsweaters** [PostHog/posthog#225]
**Describe the bug**
When creating a new action via the widget, when I click "Save action" or "Save & new action" it tries to post to `http:` instead of `https:`, which I've blocked with my content security policy.

```
5-c0ed7894b23b1f4a6eda.chunk.js:1 Refused to connect to 'http://example.com/api/action/?include_count=1&temporary_token=token' because it violates the following Content Security Policy directive: "connect-src 'self' https://example.com".
```

**Comment by timgl** [comment]
@mrsweaters Could you give this NGINX config a go?
```
map $http_x_forwarded_proto $thescheme {
     default $scheme;
     https https;
}   
proxy_set_header X-Forwarded-Proto $thescheme;

```

https://serverfault.com/questions/515957/how-to-have-nginx-forward-the-http-x-forwarded-proto-header

**Comment by mrsweaters** [comment]
I couldn't get it to work with the map config, but it works with NGINX's default `$http_x_forwarded_proto` value.

```
location / {
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header Host $http_host;
    proxy_redirect off;
    proxy_set_header X-Forwarded-Proto $http_x_forwarded_proto;
    proxy_pass http://127.0.0.1:8000;
}
```

**Comment by timgl** [comment]
Great, I've updated the Wiki :)
