### ISSUE TITLE
Simplify UX for adding plugins

### ISSUE THREAD

**Issue by mariusandra** [PostHog/posthog#2251]
## Is your feature request related to a problem?

The UX for adding *custom* plugins has inconsistencies:

![image](https://user-images.githubusercontent.com/53387/98291022-c3835e80-1faa-11eb-9c49-6fa47ce4e78b.png)

- You can now also add NPM package urls
- The two boxes are too similar. I've had to do a double take to know where to paste my url more than once.
- We might need more different options in the future (upload a zip?)

## Describe the solution you'd like

- This could be a two step form where you select the method and then get the box to paste the type of URL to.

## Describe alternatives you've considered

- This could also be just one textfield where you can paste local urls and it'll be smart enough to know the difference? Wouldn't work with a zip upload though.

## Additional context

- PR #2204 touches on this
- The default plugins from the repository are still there and easy to install

**Comment by paolodamico** [comment]
This UX is pretty old and we have improved it since, closing.
