### ISSUE TITLE
Make recordings snapshots API stable and public

### ISSUE THREAD

**Issue by marandaneto** [PostHog/posthog#22520]
## Is your feature request related to a problem?

https://posthog.com/docs/api/session-recordings#get-api-projects-project_id-session_recordings-id-snapshots
Yes, the API does not support personal API Key access because it wasn't meant to be public
Relates to https://posthog.com/questions/getting-snapshots-through-api and https://posthoghelp.zendesk.com/agent/tickets/13935
https://posthoghelp.zendesk.com/agent/tickets/13949

## Describe the solution you'd like

Make the snapshots API stable and public
Why not public yet? reason https://github.com/PostHog/posthog/pull/21674#discussion_r1574282001

## Describe alternatives you've considered

Test case https://github.com/PostHog/posthog/pull/21674

### Debug info

```shell
- [ ] PostHog Cloud, Debug information: [please copy/paste from https://us.posthog.com/settings/project-details#variables]
- [ ] PostHog Hobby self-hosted with `docker compose`, version/commit: [please provide]
- [ ] PostHog self-hosted with Kubernetes (deprecated, see [`Sunsetting Kubernetes support`](https://posthog.com/blog/sunsetting-helm-support-posthog)), version/commit: [please provide]
```

**Comment by pauldambra** [comment]
https://github.com/PostHog/posthog/pull/24502
