### ISSUE TITLE
Posthog doesn't work offline since version 1.16

### ISSUE THREAD

**Issue by GalDayan** [PostHog/posthog#2252]
## Bug description
Upgrading to version 1.16 lead to nonworking product. The posthog main page became blank

## Expected behavior
The posthog should work offline

## How to reproduce
1.  Run posthog via docker
2. Visit posthog website, it should work
2.  Turn off your internet
3.  Refresh posthog page, now the page is blank

## Environment
Docker, self hosted

**Comment by Twixes** [comment]
Hm, I don't believe PostHog ever worked offline. Some web apps can work that way, but it doesn't make sense for an analytics platform where the server & database are the engine.

**Comment by mariusandra** [comment]
@Twixes I think this misses the point. The question is about controlled network environments that limit outside requests (e.g. some companies with their firewalls, etc). PostHog should still work even if you're using it internally in such a fashion.

**Comment by Twixes** [comment]
I've tested this and this appears to not be an issue. Sure, loading latest version from our microservice fails, but PostHog works as it should. Though I did run into an issue where webpack-dev-server was not serving well under Docker #2699 (_maybe_ related?)

**Comment by mariusandra** [comment]
Hmm... maybe I'm missing something, but webpack-dev-server shouldn't be relevant when running a production version of posthog?

**Comment by Twixes** [comment]
Yep, don't know, just a wild guess 🤷

**Comment by mariusandra** [comment]
I think the original problem arrived when someone added feature flags to the backend. The posthog-python library has since gotten [better error handling](https://github.com/PostHog/posthog-python/commit/b331c4aae3a9e0e6843ee8ee136dfd589e40da77) and that could have solved the true issue.
