### ISSUE TITLE
Instance status report task reports wrong numbers

### ISSUE THREAD

**Issue by macobo** [PostHog/posthog#2255]
## Bug description

`persons_count_total` and `persons_count_new_in_period` values are calculated not using persons table, but via events table.

https://github.com/PostHog/posthog/blob/master/posthog/tasks/status_report.py#L35-L42

## Expected behavior

The calculation should be correct.

## Additional context

Adding some tests to task soon!

cc @Twixes who worked on this report

**Comment by Twixes** [comment]
Oof, that's a dumb oversight, obvs should be `Person.objects.filter(team_id=team.id)` instead of the straight copypaste `Event.objects.filter(team_id=team.id)`. "Adding some tests to task soon!" – are you working on this? If not, I can put in a fix for this rn.

**Comment by macobo** [comment]
Will fix it myself.
