### ISSUE TITLE
Log scale in graphs

### ISSUE THREAD

**Issue by pauldambra** [PostHog/posthog#22564]
### Feature request

<img width="1403" alt="Screenshot 2024-05-29 at 09 34 49" src="https://github.com/PostHog/posthog/assets/984817/ddcf455e-24c3-4b74-b6e8-7dd880c036c6">

here i've an insight of some timing data, there was a large peak and now the majority of the graph holds useful data but is unreadable

would be cool to be able to switch to a non-linear scale so that I can reduce the impact of that peak

**Comment by Twixes** [comment]
A selector with "Linear", "Log (base 2)", and "Log (base 10)" in chart options would be great.

**Comment by agsti** [comment]
I'm checking this a bit, apparently having a log(10) scale is rather easy. On the other hand having a log(2) implies creating a new "scale" (as per https://stackoverflow.com/questions/51699747/changing-the-base-of-the-logarithmic-scale-in-chart-js) . 

- is log(2) really necessary? I don't think it adds much value and would add significant complexity

**Comment by Twixes** [comment]
Log2 is sometimes nicer for base2 numbers like bytes, but definitely not key. Log10 alone would be great @agsti!
