### ISSUE TITLE
Multi touch zoom crashes the page

### ISSUE THREAD

**Issue by terpimost** [PostHog/posthog#22571]
## Is your feature request related to a problem?
Yes. When I zoom the page with pinch on smartphone webpage it crashes

## Describe the solution you'd like
Make embed script better please, otherwise we have to go to another analytics provider

## Describe alternatives you've considered
Turning off posthog

## Additional context
Here is the video (iPhone 14 Pro, Safari or Chrome)

https://github.com/PostHog/posthog/assets/1903309/fec0f1a2-4121-4b70-83e9-052f079ae926

Guys, I understand that auto capture it is a slippery road :) but it is not acceptable that your script would crash my website.

Also, please fix this:
![image](https://github.com/PostHog/posthog/assets/1903309/d62c0f1d-e0ee-455f-b48e-4a41c357f848)

### Debug info

```shell
Session: https://us.posthog.com/project/sTMFPsFhdP1Ssg/replay/018fc40d-53a6-79f0-bf79-d37bf9457340?t=93 
Admin: http://go/adminOrgUS/017a8ccc-d940-0000-4b8c-fa22dd7e49c2 (Project: 3311)
Sentry: http://go/sentryUS/3311
```

**Comment by benjackwhite** [comment]
Hey. That is a very strange and never heard of before bug! I tried to recreate with safari on our own website and yours and couldn't. Any more context you can give?

**Comment by robbie-c** [comment]
Hi, could you help us with detailed steps to reproduce? I tried to reproduce it on your website and wasn't able to, which means we won't be able to create a fix for this.

First of all: can you confirm that you are still able to trigger this crash? I loaded up [antithesis.com/blog/first_bug](https://antithesis.com/blog/first_bug/) in Safari on my iPhone and followed what you did in the video, and I didn't experience the crash. I also tried it in Chrome on my iPhone and wasnt able to reproduce there either.

After you have been able to reproduce the crash, can you tell us:
* what version of iOS is installed on your phone?
* can you confirm that this is on an iPhone 14 Pro?
* which browsers could you reproduce this in?
* if reproducing in Chrome, what version of Chrome are you using? Is this the regular Chrome app installed from the App Store?
* What version of posthog-js were you using when you could reproduce the crash? What options did you pass to `posthog.init`?

**Comment by terpimost** [comment]
Guys, I'm sorry, posthog auto capture might be a red herring.
I need a bit more time to figure out the actual source of this weird browser crash on pinch to zoom.
For now you can close this ticket. Once I triage it better I get back.

**Comment by terpimost** [comment]
Guys, I figured the problem. I'm very sorry that I thought it is a posthog autocapture problem.
I think it is mobile safari bug, related to applying svg with filters to the background of the page. I didn't do a minimal repro, but the fix was to do this on my page:
```diff
-  background: url("data:image/svg+xml,%3Csvg viewBox='0 0 400 400' xmlns='http://www.w3.org/2000/svg'%3E%3Cfilter id='noiseFilter'%3E%3CfeTurbulence type='fractalNoise' baseFrequency='0.5' numOctaves='2' stitchTiles='stitch'/%3E%3C/filter%3E%3Crect width='100%25' height='100%25' filter='url(%23noiseFilter)'/%3E%3C/svg%3E");
+  background: url('/images/texture.png');

```
