### ISSUE TITLE
[Session recording] clearly show which elements are being censored

### ISSUE THREAD

**Issue by timgl** [PostHog/posthog#2258]
## Is your feature request related to a problem?

We censor certain elements from being recorded for privacy purposes which is great. However, every time I look at a recording I get a mini heart attack thinking the entire interface is broken. 

## Describe the solution you'd like

Would be good to just have a fake 'blurred data' in place of the censored element.

**Comment by GalDayan** [comment]
Guys, it's really nice enhancement. 
I just wondered, how did you recognize elements as "private elements" which you should censor them?
@timgl

**Comment by macobo** [comment]
@GalDayan We're using rrweb under the hood (https://github.com/rrweb-io/rrweb)

There's a guide here: https://github.com/rrweb-io/rrweb/blob/master/guide.md#privacy

I'm planning on making an upstream enhancement to include our own data attr for this.

cc @yakkomajuri

**Comment by yakkomajuri** [comment]
@GalDayan updates on this:

https://github.com/PostHog/posthog-js/pull/112
https://github.com/PostHog/posthog.com/pull/634

**Comment by yakkomajuri** [comment]
@macobo as for the issue itself, the best approach would be a PR upstream with some settings for what to display on censored elements. 

The temp solution on our end could be to pass the list of censored elements on the page with the `$snapshot` event and display that to the user on the player.
