### ISSUE TITLE
bug(surveys): Switching the dropdown from the confirmation message to the question label doesn't update the popup rendering to show that question label

### ISSUE THREAD

**Issue by dmarticus** [PostHog/posthog#22614]
## Bug description

As described in the title, we have an issue where we fail to update the popup survey render in the UI when the user switches from the confirmation section to the question header section.  See the below gif for a visual description of what happens.  NOTE: this only appears to happen when editing an existing survey, not while creating a new one.

![2024-05-31 12 17 32](https://github.com/PostHog/posthog/assets/4853149/9277eb29-6725-427a-baac-35b3ee00a72f)

## How to reproduce

1. Click on an existing survey
2. Before clicking "edit" on the top, navigate to the question dropdown underneath the survey render and select the confirmation message (the rendering should display your confirmation message)
3. Now click "Edit", and the survey should enter editing mode while focused on the confirmation message
4. On that same dropdown, now select the first question in the survey (the rendering _should_ display that question instead, but it doesn't; it just keeps displaying the confirmation message)

## Additional context

Honestly, this doesn't feel super high-priority since the user can still navigate to the questions and edit them, and it's a bit of a edge case.  But it's still obviously a bug whenever they do run into it, and obvious bugs are bad.

**Comment by dmarticus** [comment]
looks like Juraj might have this fixed in his PR already, sweet! ([context](https://posthog.slack.com/archives/C034XD440RK/p1717183267598219))

**Comment by asachan-git** [comment]
@dmarticus , is this issue fixed or still open?

**Comment by dmarticus** [comment]
@asachan-git it's still open!  Sorry for the confusion, I linked to our internal Slack.  @jurajmajerik is fixing this issue in his PR here: https://github.com/PostHog/posthog-js/pull/1214

**Comment by dmarticus** [comment]
Confirmed that Juraj fixed this with https://github.com/PostHog/posthog-js/pull/1214, closing this.
