### ISSUE TITLE
Bug report: Experiment drafts - Adding or renaming test variant results in 400 error

### ISSUE THREAD

**Issue by slshults** [PostHog/posthog#22613]
## Bug description

Trying to add or rename a test variant on a draft experiment results in a 400 error, e.g.:
`PATCH https://us.posthog.com/api/projects/55178/experiments/30222/ 400 (Bad Request)`

![CleanShot 2024-05-31 at 11 19 04@2x](https://github.com/PostHog/posthog/assets/227448/ddde1733-853b-4ecf-b4d5-7b9319a45387)

## How to reproduce

1. Edit a draft experiment (or create and save a draft, then edit)
2. Add a test variant, or rename an existing variant
3. `Continue` button
4. `Save as draft` button

Note error modal in lower right: `Can't update feature_flag_variants on Experiment`

Console shows: `PATCH https://us.posthog.com/api/projects/55178/experiments/30222/ 400 (Bad Request)`

The experiment URL, in the error cited by the user in the support ticket, is for an experiment which no longer exists.  So, for a quick repro, you can use this test experiment on a project of mine: https://us.posthog.com/project/55178/experiments/30222

## Additional context
From: https://posthoghelp.zendesk.com/agent/tickets/14037
To view replay of error (this link should take you to the 10:10 mark, watch from there to see error occur)
https://us.posthog.com/project/2/replay/018fc2b0-9ea1-7981-b33d-59e65006cb8b?t=610

### Debug info

```shell
Session: https://us.posthog.com/project/sTMFPsFhdP1Ssg/replay/018fcfca-d57f-7d89-9180-d763e644b508?t=2160 
Admin: http://go/adminOrgUS/018f9f89-fcac-0000-8b6d-0142b200109b (Project: 70102)
Sentry: http://go/sentryUS/70102
```

**Comment by Phanatic** [comment]
Fixed in https://github.com/PostHog/posthog/pull/23752
