### ISSUE TITLE
Library request: integrate with Elixir

### ISSUE THREAD

**Issue by victorbordo** [PostHog/posthog#227]
**Is your feature request related to a problem? Please describe.**

[Elixir](https://github.com/elixir-lang/elixir) has ~17K stars and ~914 contributors. It's growing in popularity for developing web apps, especially as [Phoenix](https://www.phoenixframework.org/) continues to improve.

By providing a Elixir library, it'd be very easy for developers using it to track their product usage with PostHog.

**Describe the solution you'd like**
A library similar for Elixir similar to eg the Ruby one we have in the [PostHog list](https://github.com/PostHog/posthog/wiki/Integrations).

**Describe alternatives you've considered**
Use the [PostHog API](https://github.com/PostHog/posthog/wiki/API).

**Comment by J0** [comment]
Hey @timgl, 

Can I take this issue?

Hey @victorbordo,

Could I trouble you for a review after I'm done? I'm relatively new to Elixir so an extra pair of eyes would be useful in creating an idiomatic library.

**Comment by timgl** [comment]
@J0 Yes, please go for it!

**Comment by J0** [comment]
Alright, thanks. I started a [repository](https://github.com/J0/posthog-elixir). I'll be slowly making updates there.

**Comment by J0** [comment]
Hey, 

I realise that there's already a properly functioning Elixir community library so I'm going to unassign and leave this as is.

Lmk if anything else Elixir related is needed.

**Comment by Twixes** [comment]
K, that's alright! We haven't seen strong demand for an official Elixir library (it's not very mainstream in the end) so we can table this for now.
