### ISSUE TITLE
Bug report: Lack of visual confirmation when deleting an org creates risk of deleting wrong org

### ISSUE THREAD

**Issue by slshults** [PostHog/posthog#22730]
## Bug description

After deleting an organization, a user with multiple orgs is immediately redirected to the delete screen for *a different org*. There is no visible indication of success or failure. So if I blink, it seems like I'm still looking at same screen and so I just click the button again, possibly deleting an org I don't want to delete.

## How to reproduce

1. Create multiple orgs in a test account
2. Go to `Settings --> Organization --> Danger zone`
3. Go through the steps to delete an org
4. After the last step, note the lack of visual confirmation that the org was deleted, and that you're now on the danger zone page for a totally different org.

(You can also see the problem in action in the session replay linked to from [the support ticket](https://posthoghelp.zendesk.com/agent/tickets/14263), where luckily the delete attempt for the 2nd org failed.)

## Additional context
Expected behavior: 
After an attempt at deleting an org, show a confirmation with success or failure info, and redirect the user to a page other than `/organization-danger-zone` (perhaps to `/settings/organization` instead.)

Bug report from https://posthoghelp.zendesk.com/agent/tickets/14263

### Debug info

```shell
Session: https://us.posthog.com/project/sTMFPsFhdP1Ssg/replay/018fe992-fe15-7e8d-bddf-769105cb8d8e?t=0 
Admin: http://go/adminOrgUS/018a908e-d2b5-0000-9f90-823f444e639f (Project: 36282)
Sentry: http://go/sentryUS/36282
```

**Comment by raquelmsmith** [comment]
Fixed by #22733
