### ISSUE TITLE
PostHog Toolbar makes a request to a different domain to our API domain

### ISSUE THREAD

**Issue by edhgoose** [PostHog/posthog#22777]
## Bug description

When using the PostHog toolbar, it makes a request to eu.posthog.com.

This is different to the domain we have whitelisted, which is our custom domain.

Our Content Security Policy includes a whitelist, which allows our custom domain, but not the eu.posthog.com one.

We'd prefer if our custom domain was used, as it means our internal staff don't need to bypass the Content Security Policy. We also can't easily change the Content Security Policy based on whether the PostHog toolbar is on or not.

## How to reproduce

1. Create a website with a Content Security Policy which does not allow connections to eu.posthog.com, but does to a custom domain.
2. Enable the posthog toolbar.
3. Visit your domain and try to add an action.
4. Observe copious error messages in console when clicking action

![CleanShot 2024-06-06 at 22 53 27@2x](https://github.com/PostHog/posthog/assets/1108173/7154163e-8e59-44ba-a7c5-f030039e38f0)

### Debug info

```shell
- [x] PostHog Cloud, Debug information:
Session: https://us.posthog.com/project/sTMFPsFhdP1Ssg/replay/018fef7e-c43f-7ff9-a337-10a657635447?t=856 
Admin: http://go/adminOrgEU/0186cac5-3ffb-0000-8ba0-eda804838cba (Project: 3310)
Sentry: http://go/sentryEU/3310
- [ ] PostHog Hobby self-hosted with `docker compose`, version/commit: [please provide]
- [ ] PostHog self-hosted with Kubernetes (deprecated, see [`Sunsetting Kubernetes support`](https://posthog.com/blog/sunsetting-helm-support-posthog)), version/commit: [please provide]
```

**Comment by pauldambra** [comment]
Hey @edhgoose 

Do you have any config set for api_host or ui_host in posthog-js?

The toolbar uses the `ui_host` config to determine what API endpoint to call

https://posthog.com/docs/libraries/js#config

**Comment by edhgoose** [comment]
Yes @pauldambra, we have the `ui_host` set to `eu.posthog.com` and `api_host` set to our proxy.

Given the docs say:

> If using a [reverse proxy](https://posthog.com/docs/advanced/proxy) for api_host then this should be the actual PostHog app URL (e.g. https://us.posthog.com/)

Can the toolbar be set to use `api_host` instead? Otherwise, we can't use the proxy without whitelisting the `ui_host` in our content security policy, which I'd prefer - if at all possible - not to do.

If it really isn't possible, then we can, but I figured I'd ask!

**Comment by pauldambra** [comment]
Hey @edhgoose,

unfortunately those API calls from the toolbar and then any loading of the PostHog can't be managed through a reverse proxy (or rather we don't support it :-))

you can use posthog for collection without being allowed through the CSP, but not the toolbar.

Sorry
