### ISSUE TITLE
Experiment UI throws an error when trying to change a variant name

### ISSUE THREAD

**Issue by jurajmajerik** [PostHog/posthog#22790]
## Bug description
In the old experiment UI, variant name input is disabled after the exeriment is created:

![image](https://github.com/PostHog/posthog/assets/22996112/c2b04332-ffdd-47e0-9707-8433222f769d)

In the new UI, it's not disabled, and an error is thrown when trying to edit it:
![image](https://github.com/PostHog/posthog/assets/22996112/95763d0c-575a-4ac4-bcc1-1bed799b7422)

## How to reproduce

1. 
2.
3. 

### Debug info

```shell
- [ ] PostHog Cloud, Debug information: [please copy/paste from https://us.posthog.com/settings/project-details#variables]
- [ ] PostHog Hobby self-hosted with `docker compose`, version/commit: [please provide]
- [ ] PostHog self-hosted with Kubernetes (deprecated, see [`Sunsetting Kubernetes support`](https://posthog.com/blog/sunsetting-helm-support-posthog)), version/commit: [please provide]
```

**Comment by Phanatic** [comment]
Fixed in https://github.com/PostHog/posthog/pull/23752
