### ISSUE TITLE
Docker build missing template error

### ISSUE THREAD

**Issue by mrsweaters** [PostHog/posthog#228]
```
Request Method: | GET
-- | --
http://example.com/login?next=/
3.0.3
TemplateDoesNotExist
layout.html
/usr/local/lib/python3.8/site-packages/django/template/backends/django.py in reraise, line 84
/usr/local/bin/python
3.8.2
['/code',  '/usr/local/bin',  '/usr/local/lib/python38.zip',  '/usr/local/lib/python3.8',  '/usr/local/lib/python3.8/lib-dynload',  '/usr/local/lib/python3.8/site-packages']
Fri, 28 Feb 2020 17:34:23 +0000
```

**Comment by timgl** [comment]
@mrsweaters Can you try re-pulling the repository on your server (and/or removing the "command: gunicorn...." line from your docker-compose.yml file)?

We run python manage.py collectstatic in the entrypoint now, so I think that's why!

**Comment by mrsweaters** [comment]
I pulled down the repo again and rebuilt the docker image and I'm still getting this missing template error.

**Comment by mrsweaters** [comment]
<img width="1374" alt="Screen Shot 2020-02-28 at 9 57 59 AM" src="https://user-images.githubusercontent.com/535897/75573014-d3f13b80-5a10-11ea-8d97-e15e7167f9b0.png">

**Comment by timgl** [comment]
What happens if you manually run `python manage.py collectstatic` in the docker image?

**Comment by timgl** [comment]
Actually that might not help. Does `/code/posthog/frontend/dist/layout.html` exist?

**Comment by mrsweaters** [comment]
Output of python manage.py collectstatic
```
You have requested to collect static files at the destination
location as specified in your settings:

    /code/staticfiles

This will overwrite existing files!
Are you sure you want to do this?

Type 'yes' to continue, or 'no' to cancel: yes

0 static files copied to '/code/staticfiles', 165 unmodified, 372 post-processed.
```
`/code/posthog/frontend/dist/layout.html` does not exist.

**Comment by timgl** [comment]
And `.dockerignore` has the line `!frontend/dist` in it?

**Comment by mrsweaters** [comment]
It does

**Comment by mrsweaters** [comment]
So if I copy the layout.html and index.html files from `frontend` into `posthog/templates` then the 500 error goes away, but, of course the assets aren't loading since it isn't pointing to the compiled assets. Also, just noticed that the assets aren't being compiled as I don't see the style or js bundles anywhere.

**Comment by timgl** [comment]
Sorry about all this faff! Do you want to jump on another hangout? https://meet.google.com/vqw-tqim-hab

**Comment by timgl** [comment]
The issue was our docker-compose file built from source, rather than `posthog/posthog:latest`. Sometimes on local builds NPM install fails. I've updated the docker-compose.yml file.

I also updated the [https://github.com/PostHog/posthog/wiki/Deployment](documentation) to reflect how to use an external postgres database, as that causes confusion.
