### ISSUE TITLE
Rename breakdown property values in rendered graph

### ISSUE THREAD

**Issue by reuben** [PostHog/posthog#22806]
## Is your feature request related to a problem?

Our organization uses English for internal event properties and values, but our customers speak other languages. We share insights and dashboards with our customers, and would like to be able to translate the event property values displayed in our graphs (and in general, translate all content in the resulting graph), to the target language of the customer.

## Describe the solution you'd like

I'd like to be able to rename the generated "virtual" series from the breakdown in the bottom table and have those changes reflected in the rendered graph.

## Describe alternatives you've considered

Re-rendering the graph from scratch using the result data: hard to replicate PostHog experience, requires developer time every time a product owner wants a change to the insight/dashboard.

### Debug info

```shell
- [x] PostHog Cloud, Debug information:

Session: https://us.posthog.com/project/sTMFPsFhdP1Ssg/replay/018ff269-93cb-7bcb-b0d6-69e104b807a4?t=2176 
Admin: http://go/adminOrgEU/018d6453-df8e-0000-01a2-34a37d4f1b6a (Project: 15958)
Sentry: http://go/sentryEU/15958
```

**Comment by MarconLP** [comment]
Hey @reuben, that is already possible using a HogQL breakdown like this:
```
multiIf(
    properties.$os == 'Android', 'android device',
    properties.$os == 'iOS', 'apple devicee', 
    'non mobile device'
)
```

**Comment by reuben** [comment]
@MarconLP Nice, that works for our current needs. Thank you!
