### ISSUE TITLE
Improve PostHog preview experience

### ISSUE THREAD

**Issue by paolodamico** [PostHog/posthog#2282]
## Is your feature request related to a problem?

Sometimes when you just created an account or installed PostHog, you are not able to send data immediately (or for some reason users don't want to send test data, like just doing a cURL), but you still want to test PostHog.

## Describe the solution you'd like

On the screen that shows up if my current project has no current events (where we add the snippet code), I would like to have a button that pre-populates my project with demo data so I can jump right into PostHog.

I would also like to have a clearly visible indicator throughout the app that tells me that I have demo data in my current project and an option to delete all the demo data from there.

## Describe alternatives you've considered

Prompting users to send test events with cURL / Postman or to visit `/demo` to generate test data themselves.

## Additional context

The idea / pain came from watching a [session recording](https://app.posthog.com/sessions?properties=[]&sessionRecordingId=175ab87a93bbc-05771025e1efeb-5b617d69-410a0-175ab87a93c7c).

**Comment by Twixes** [comment]
We'll be solving this with demo.posthog.com instead (issue #6583).
