### ISSUE TITLE
Allow ssh tunnel username for ssh key - Data Warehouse

### ISSUE THREAD

**Issue by mrocheleau** [PostHog/posthog#22820]
## Is your feature request related to a problem?

The SSH Tunnel option in Data Warehouse, when linking an external (PostgreSQL in this case) source doesn't allow specifying a username.  This attempts to ssh in as the "nobody" user, which is not a valid/login-able user.  

## Describe the solution you'd like
Add a field to specify the username on the remote side (the bastion host side) that the key will be checked against for login

## Describe alternatives you've considered
Tried adding <username>@<tunnel IP> but this fails and doesn't make it to the destination system at all.

Enabling the nobody user is not a recommended fix here.  Another alternative would be having a set username PostHog connects with to remote tunnels, letting users know what this is and they can then build that user specifically for this, with the public key set on it.  But it would be easiest if we could simply specify the user.

## Additional context
`auth.log` example of a connection attempt without being able to specify a username (Amazon Linux 2 bastion host in this case):
```
Jun  7 21:27:59 ip-172-40-2-190 sshd[20220]: AuthorizedKeysCommand /usr/share/ec2-instance-connect/eic_run_authorized_keys nobody SHA256:YXCO3aYtKBh1iIRxzozBZoTbE2EhhGxuEivMcC+wY7U failed, status 22
Jun  7 21:27:59 ip-172-40-2-190 sshd[20220]: Connection closed by authenticating user nobody 44.208.188.173 port 22116 [preauth]
```

### Debug info

```shell
- [X] PostHog Cloud, Debug information: [please copy/paste from https://us.posthog.com/settings/project-details#variables]
- [ ] PostHog Hobby self-hosted with `docker compose`, version/commit: [please provide]
- [ ] PostHog self-hosted with Kubernetes (deprecated, see [`Sunsetting Kubernetes support`](https://posthog.com/blog/sunsetting-helm-support-posthog)), version/commit: [please provide]
```

**Comment by Gilbert09** [comment]
@mrocheleau Hey, this was implemented with https://github.com/PostHog/posthog/pull/23030 - let me know if you run into any issues. Thanks!
