### ISSUE TITLE
Toolbar heatmap returns 0 hits

### ISSUE THREAD

**Issue by lottiecoxon** [PostHog/posthog#2283]
For some reason the heatmap is saying '0' when this can't be true right?

<img width="222" alt="Screenshot 2020-11-09 at 09 31 12" src="https://user-images.githubusercontent.com/65415371/98523929-6cadab80-226e-11eb-8b62-3077186d708f.png">

**Comment by jamesefhawkins** [comment]
I am also experiencing this on posthog.com

**Comment by yakkomajuri** [comment]
Thank you for opening the issue @lottiecoxon! I love it!
