### ISSUE TITLE
Sensitive actions require reauth, but send you back to the homepage

### ISSUE THREAD

**Issue by edhgoose** [PostHog/posthog#22839]
### Bug Description

When visiting an area which is sensitive, Posthog asks for reauth. But it sends you back to the dashboard, not to the page you needed auth for.

## How to reproduce

1.  Visit a page like https://eu.posthog.com/organization/settings.
2. Note that Posthog (sometimes) asks you to reauthenticate because it's a sensitive area.
3. Go through the reauthenticate flow
4. Arrive at the dashboard homepage instead of the https://eu.posthog.com/organization/settings page 😢 

## Additional context
It seems that if I've recently authenticated, it doesn't do this.

I am struggling to reproduce it, possibly because I've recently logged in - but I'll keep trying throughout the day.

### Debug info

```shell
- [x] PostHog Cloud, Debug information: [please copy/paste from https://us.posthog.com/settings/project-details#variables]
- [ ] PostHog Hobby self-hosted with `docker compose`, version/commit: [please provide]
- [ ] PostHog self-hosted with Kubernetes (deprecated, see [`Sunsetting Kubernetes support`](https://posthog.com/blog/sunsetting-helm-support-posthog)), version/commit: [please provide]


Session: https://us.posthog.com/project/sTMFPsFhdP1Ssg/replay/0190020e-a837-7367-be44-275f46ec548d?t=10 
Admin: http://go/adminOrgEU/0186cac5-3ffb-0000-8ba0-eda804838cba (Project: 3310)
Sentry: http://go/sentryEU/3310
```

**Comment by benjackwhite** [comment]
Fix coming up - thanks for reporting!
