### ISSUE TITLE
RESTRICT_SIGNUPS throwing an error when set

### ISSUE THREAD

**Issue by DataTables** [PostHog/posthog#2286]
## Bug description

I've installed posthog from source, and set the `RESTRICT_SIGNUPS` environment variable to be `ct-devel-06.com,sprymedia.co.uk,datatables.net. This is resulting in the worker script failing with the following error:

```
7|posthog-worker  | 2020-11-09T17:39:02:   File "/home/vagrant/cloudtables/analytics/posthog/posthog/settings.py", line 46, in get_bool_from_env
7|posthog-worker  | 2020-11-09T17:39:02:     return bool(strtobool(str(value)))
7|posthog-worker  | 2020-11-09T17:39:02:   File "/usr/local/lib/python3.7/distutils/util.py", line 307, in strtobool
7|posthog-worker  | 2020-11-09T17:39:02:     raise ValueError("invalid truth value %r" % (val,))
7|posthog-worker  | 2020-11-09T17:39:02: ValueError: invalid truth value 'ct-devel-06.com,sprymedia.co.uk,datatables.net'
```

Without that environment variable set, it runs successfully.

## Expected behavior

Startup without error.

## How to reproduce

1. Clone posthog (I was using posthog-foss, but I presume the main repo is the same)
2. Start the work with the RESTRICT_SIGNUPS environment variable set
3. Boom

## Environment

- PostHog version/commit: Tried with 1.16.0 tagged and 31822ea7 (current at time of writing)

## Additional context

I'm running posthog with pm2 as the process manager. I don't think that makes any difference here, ut it is the one thing that is outside the scope of your instructions.

**Comment by DataTables** [comment]
Likely related to #1106. I've been using Posthog for a while now and I'm finally getting around to updating - this is a big jump from something like 1.2 I think.

**Comment by timgl** [comment]
@DataTables That's a huge update ha! We've changed the invite process so that you have to create individual invites for each email, making the `RESTRICT_SIGNUPS` env variable redundant, so it's safe to run PostHog without it.

I'll remove it from our settings page as well

**Comment by DataTables** [comment]
Awesome - thanks!

> That's a huge update

That's because you all work ridiculously fast! ;-)

**Comment by timgl** [comment]
👍 

Would love to hear any feedback you have on the upgrade progress or the new features!
