### ISSUE TITLE
Automatically create a 'real users' cohort

### ISSUE THREAD

**Issue by timgl** [PostHog/posthog#2287]
## Is your feature request related to a problem?

Internally we use a "Real users" cohort that filters out our own accounts. The most important filter there is just a "email does not contain @posthog.com"

## Describe the solution you'd like

I'd be pretty easy to, when a user creates a new team, automatically create a cohort that filters out users with the same email domain as the initial user. We probably want to ignore popular emails like gmail.com, hotmail.com, gg.com etc.

It might then also be nice to filter most/all views by this cohort automatically

**Comment by pulmonesxavier** [comment]
I'd like to take a jab at this. I do have a question though. Is creating a new team akin to inviting a new member? Or is there a create team functionality?

**Comment by paolodamico** [comment]
Go for it @pulmonesxavier!

Actually `Team` is the internal (as within the code) name for projects, we haven't been able to change it yet. So when a new project/team is created, if the user who creates it has a company email address (i.e. not one of the common public personal domains), we would create this cohort that excludes users whose email address belongs to that domain. Ideally we would also put this behind a [feature flag](https://posthog.com/docs/features/feature-flags) but that's just the cherry on top.

**Comment by timgl** [comment]
@pulmonesxavier Just checking in. Do you need a hand with this? Happy to help!

**Comment by timgl** [comment]
@pulmonesxavier I'm going to de-assign you but if you change your mind let me know :)

**Comment by macobo** [comment]
IMO solved with the test users filter. :)
