### ISSUE TITLE
Security concerns over use of Django's session keys

### ISSUE THREAD

**Issue by avorio** [PostHog/posthog#2289]
Folks,

In the [documentation on integration with Django sites](https://posthog.com/docs/integrations/python-integration#django), you recommend using Django's `session_key` to identify end-users. Doesn't that raise security concerns over leakage of session keys? Any user in possession of a session key extracted from PostHog's dashboard could impersonate a user on the live site by tweaking a cookie with that session key value, no?

Or ... am I missing something here?

```python
import posthog

def purchase(request):
    # example capture
    posthog.capture(request.session.session_key, 'purchase', ...)
```

**Comment by timgl** [comment]
@avorio Hey, good catch. It was just an example but it should have been `request.user.id`. I've updated that now and should be on the site in a few minutes.

Thanks!
