### ISSUE TITLE
403 Error when creating Action from action page

### ISSUE THREAD

**Issue by mrsweaters** [PostHog/posthog#229]
**Describe the bug**
Creating an action from the action page returns a 403.

**To Reproduce**
1. Go to Actions -> New Action
2. Fill out your action
3. Click "Save action"

Related to https://github.com/PostHog/posthog/issues/155 but I've already implemented the suggested changes there. Other POST requests work fine, like creating a cohort.

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser Chrome
 - Version 80

**Additional context**
Running behind an NGINX proxy with docker image.

**Comment by timgl** [comment]
This is the same issue as #225 as the action endpoint gets the wrong URL (and thus things you should have a temporary token). So I'll close this and pick up #225 now :)
