### ISSUE TITLE
Date Formatting Issue When Fractional Seconds Are Missing

### ISSUE THREAD

**Issue by webjunkie** [PostHog/posthog#22915]
It appears that our date formatting functionality does not handle ISO 8601 date-time strings correctly when fractional seconds are missing. This issue causes inconsistencies in date processing and can lead to errors in various parts of our application.

**Steps to Reproduce:**

1. Provide an ISO 8601 date-time string without fractional seconds, e.g., `"2024-06-12T13:49:32Z"` in an insight result.
2. Attempt to view the formatted date.
3. Observe the behavior and any errors or inconsistencies.

<img width="805" alt="image" src="https://github.com/PostHog/posthog/assets/59713/45201648-c93c-4758-b2b0-ce0f9dbb013c">

**Expected Behavior:**

The date-time string without fractional seconds should be processed and formatted correctly, just like those with fractional seconds, e.g., `"2024-06-12T13:49:31.670000Z"`.

**Actual Behavior:**

Date-time strings without fractional seconds are not handled correctly, leading to formatting issues.

**Example:**

The following date-time strings should both be valid and handled consistently:

- `"2024-06-12T13:49:32Z"` (without fractional seconds)
- `"2024-06-12T13:49:31.670000Z"` (with fractional seconds)

**Additional Information:**

This issue was identified during the looking at insight results where the date-time format varied. The inconsistency in handling these formats suggests a potential bug in the date formatting logic.

**Comment by webjunkie** [comment]
@isAdrisal do you have an example insight for me where this issue appears? The hogql based table insights now are fixed as intended with the PR.

**Comment by isAdrisal** [comment]
@webjunkie a couple examples for you here with both fractional and non-fractional seconds values:
https://us.posthog.com/project/34169/insights/RdW7Du6q
https://us.posthog.com/project/34169/insights/zlOWgomv

<img width="301" alt="Screenshot 2024-06-21 at 17 33 46" src="https://github.com/PostHog/posthog/assets/29012873/cfcfe1be-c1b9-4007-8515-a8f7ca5d63d4">
<img width="249" alt="Screenshot 2024-06-21 at 17 33 42" src="https://github.com/PostHog/posthog/assets/29012873/5b0a9eaa-db4d-4f33-b332-9819079a27a4">
