### ISSUE TITLE
Feature Request: Allow users to see more than one survey "within the last `n` days"

### ISSUE THREAD

**Issue by slshults** [PostHog/posthog#22965]
## Is your feature request related to a problem?

The option "`Don't show to users who saw a survey within the last N days.`", prevents users from seeing any other surveys

## Describe the solution you'd like
An additional option an option for "`Don't show to users who saw THIS survey within the last N days`".

Use case: We want to run an NPS and CES survey side-by-side, but only want to run each per user every 90 days, but independently of each other.  Currently if one shows, the other one would be blocked.

## Additional context
From: https://posthoghelp.zendesk.com/agent/tickets/14655

### Debug info

```shell
Session: https://us.posthog.com/project/sTMFPsFhdP1Ssg/replay/01901347-13a9-756d-8379-f0374126d5d3?t=12 
Admin: http://go/adminOrgEU/0186cac5-3ffb-0000-8ba0-eda804838cba (Project: 3310)
Sentry: http://go/sentryEU/3310
```

**Comment by joesaunderson** [comment]
Context, this would allow us to ditch another tool and fully use PostHog for surveys

**Comment by neilkakkar** [comment]
This is out in beta iirc :) - (@Phanatic can you add Joe to the flag please? - I didn't find this flag, not sure if there's something else remaining here before you want to release this)

**Comment by joesaunderson** [comment]
> This is out in beta iirc :) - (@Phanatic can you add Joe to the flag please? - I didn't find this flag, not sure if there's something else remaining here before you want to release this)

Ah amazing! As usual, you don't disappoint @neilkakkar 👏 look forward to seeing this

**Comment by joesaunderson** [comment]
@neilkakkar @Phanatic, do you know if this will be enabled in the short term future? Would love to start migrating from Gainsight

**Comment by Phanatic** [comment]
@joesaunderson what is your organization name? I can add you to the flag.

**Comment by joesaunderson** [comment]
> @joesaunderson what is your organization name? I can add you to the flag.

"Mention Me", or EU project 3310

**Comment by Phanatic** [comment]
@joesaunderson I went ahead and enabled this feature for everyone. 
You should now see a new section under the "completion conditions" of a survey

![image](https://github.com/PostHog/posthog/assets/82819/e8359c32-860b-4e9d-8e6f-0f8c3003edc7)
