### ISSUE TITLE
Bug Report: `Current URL` `equals` filter problem in funnels

### ISSUE THREAD

**Issue by slshults** [PostHog/posthog#22963]
## Bug description

In a funnel insight with the first query step set as a pageview with a filter for `Current URL` `= equals` `https://www.foo.com/bar`, the results displayed are the same as we'd expect to see with a `contains` filter instead of `equals`:

![CleanShot 2024-06-13 at 11 03 18@2x](https://github.com/PostHog/posthog/assets/227448/350e8ff3-daf2-4b76-b558-0bdf8fe88b90)

## How to reproduce

1. View [this insight](https://us.posthog.com/project/26051/insights/9Qqp7Ap9) in edit mode
or
1. Create an insight with a he first query step set as a pageview with a filter for `Current URL` `= equals` `https://www.foo.com/bar`, where `/bar` also has sub-directories
2. Note that the results show the sub-directory pages, as if `contains` had been used instead of `= equals`

## Additional context

From https://posthoghelp.zendesk.com/agent/tickets/14610

### Debug info

```shell
Session: https://us.posthog.com/project/sTMFPsFhdP1Ssg/replay/019012c8-724b-7c62-93f0-5e4a40bd5388?t=277 
Admin: http://go/adminOrgUS/01874cf3-a73f-0000-9123-c3831ca26383 (Project: 26051)
Sentry: http://go/sentryUS/26051
```

**Comment by webjunkie** [comment]
I've determined that you need to choose the correct attribution type to get the breakdown accordingly.

**Comment by slshults** [comment]
I created a PR to add this info to our funnel docs: https://github.com/PostHog/posthog.com/pull/8756
