### ISSUE TITLE
Cohort using action does not return users

### ISSUE THREAD

**Issue by webjunkie** [PostHog/posthog#22981]
## Bug description

https://posthoghelp.zendesk.com/agent/tickets/14557

## How to reproduce

1. Create action with property filter on all events
2. Use action in cohort
3. See now users match

**Comment by neilkakkar** [comment]
the crux I think is this -> https://github.com/PostHog/posthog/issues/21137 -> action isn't the problem, all events is

**Comment by webjunkie** [comment]
Ah interesting.. looked at this earlier but thought "fail" as in error so that must be an older different bug 🤣 

Closing in favor of #21137
