### ISSUE TITLE
Dashboard crashing again

### ISSUE THREAD

**Issue by isAdrisal** [PostHog/posthog#22996]
## Bug description

https://us.posthog.com/project/34169/dashboard/93091

Dashboard is essentially "frozen", but if you wait for enough minutes eventually some insights will appear but responding to any scroll event on the page takes another X minutes.

Eventually, the page crashes. I wasn't able to get a performance or memory trace out of Chrome because the tab crashes before it can make any progress on saving those profiles.

This is a regression since/after Friday 14th June, as it was working fine before then.

## How to reproduce

1. Load dashboard
2. See it initially load a "skeleton" without any insights
3. Notice that the tab is frozen

## Additional context
<img width="409" alt="Screenshot 2024-06-17 at 10 18 35" src="https://github.com/PostHog/posthog/assets/29012873/560baccd-9c23-4343-b274-7630f12ac7d3">

<img width="903" alt="Screenshot 2024-06-17 at 10 19 33" src="https://github.com/PostHog/posthog/assets/29012873/6f584b4d-2370-49db-be6b-5605e3d61021">

### Debug info

```shell
Session: https://us.posthog.com/project/sTMFPsFhdP1Ssg/replay/01902374-a777-7a5d-a7c8-7001c7046e2d?t=2077 
Admin: http://go/adminOrgUS/018a1aa0-fba1-0000-7c63-3525ad2656c8 (Project: 34169)
Sentry: http://go/sentryUS/34169
```

**Comment by isAdrisal** [comment]
Not sure if this helps or not, but there's a 422MB (uncompressed) download that happens on loading the dashboard which seems... like a lot.

<img width="941" alt="Screenshot 2024-06-17 at 12 44 53" src="https://github.com/PostHog/posthog/assets/29012873/fac2ec0a-2731-4a3e-9075-a11b23cd3654">

**Comment by isAdrisal** [comment]
@webjunkie is it possible this issue is caused by https://github.com/PostHog/posthog/pull/22979?

**Comment by webjunkie** [comment]
@isAdrisal Do you have insights with breakdowns on this dashboard?

We just identified #23008 which might be the culprit here as well.

**Comment by isAdrisal** [comment]
@webjunkie We do, 10 of them. Thanks, I'll comment keep an eye on the linked ticket and comment here if it's resolved once it's merged.

**Comment by isAdrisal** [comment]
@webjunkie That fix (or another one) has resolved this issue. The dashboard is no longer crashing, memory usage looks normal, and there's no longer a 422mb fetch happening on load.

Thanks 🙏
