### ISSUE TITLE
Updating cohort does not refresh people table

### ISSUE THREAD

**Issue by macobo** [PostHog/posthog#2308]
## Bug description

When I'm updating cohorts, a "calculating people" indicator shows up on the right.

After it disappears I still see old people in the table.

## Expected behavior

Table contains new people or an indicatior to reload

## How to reproduce

1. Create cohort
2. Update filter to match no-one
3. Save
4. See people in table

## Environment

Both

**Comment by paolodamico** [comment]
Fixed in #2576.
