### ISSUE TITLE
WIP Make the multi-domain use of the tool simpler to understand

### ISSUE THREAD

**Issue by jamesefhawkins** [PostHog/posthog#231]
**Is your feature request related to a problem? Please describe.**

It is best practise to install PostHog on your website.com AND your application ie app.website.com

This means you can capture all the marketing data and user interaction BEFORE people become users. It means you can understand how to get more users better.

Lots of users have expressed confusion about if we support this, and we do!

**Describe the solution you'd like**

- [x] Add to docs
- [ ] Add to SendEventsOverlay in app

**Describe alternatives you've considered**
TBD

**Comment by wundo** [comment]
Where is this documented in docs? I could not find it :)
