### ISSUE TITLE
Cohorts aren't calculating 

### ISSUE THREAD

**Issue by yakkomajuri** [PostHog/posthog#2310]
## Bug description

*Please describe.*  
*If this affects the front-end, screenshots would be of great help.*  

Cohorts are not calculating. This has been like this for the last hour:

<img width="1191" alt="Screenshot 2020-11-10 at 12 30 58" src="https://user-images.githubusercontent.com/38760734/98674414-aeaf1e00-2350-11eb-83c2-65845db52405.png">

## Expected behavior

Cohort calculates

## How to reproduce

1. Create a cohort
2. 
3. 

## Environment

Cloud

**Comment by macobo** [comment]
This can happen if cohort calculation failed.

There's two unresolved bugs on this in sentry:
https://sentry.io/organizations/posthog/issues/2017344582/?project=1899813&query=is%3Aunresolved+cohort&statsPeriod=14d
https://sentry.io/organizations/posthog/issues/1801378528/?project=1899813&query=is%3Aunresolved+cohort&statsPeriod=14d

**Comment by paolodamico** [comment]
Related / duplicate #1693.
