### ISSUE TITLE
Clicking 'Next' on a Cohort does nothing

### ISSUE THREAD

**Issue by yakkomajuri** [PostHog/posthog#2311]
## Bug description

*Please describe.*  
*If this affects the front-end, screenshots would be of great help.*  

The button to see more users in a cohort doesn't do anything. Seems like pagination isn't working for cohorts.

## Expected behavior

Clicking 'Next' shows more users

## How to reproduce

1. Click 'next' on the Cohorts page
2. 
3. 

## Environment

Cloud

**Comment by EDsCODE** [comment]
outdated. This works now!
