### ISSUE TITLE
"Does not contain" URL matching fails

### ISSUE THREAD

**Issue by yakkomajuri** [PostHog/posthog#2313]
## Bug description

*Please describe.*  
*If this affects the front-end, screenshots would be of great help.*  

Setting a filter for "Current URL does not contain" includes that URL in the data in Trends.

## Expected behavior

Don't include the matching URL.

## How to reproduce

1. Set a filter for current URL does not contain in Trends
2. 
3. 

## Environment

- PostHog cloud or self-managed?
- PostHog version/commit

**Comment by EDsCODE** [comment]
I think this was filtering with a breakdown which should be fixed now! reopen if it still can be reproduced
