### ISSUE TITLE
What is beacon and how do I disable it?

### ISSUE THREAD

**Issue by lilouartz** [PostHog/posthog#23165]
### Feature request

Now when I load my page, I see requests to PostHog Beacon.

Example: https://pillser.com/supplements/calcium-vitamin-d-for-kids-619

Makes a request to: https://pillser.com/posthog/i/v0/e/?ip=1&_=1719006521026&ver=1.140.0&beacon=1

What is this and how do I disable it?

I am being very careful about what data is sent to PostHog, so don't feel comfortable that this was just added without a breaking change.

### Debug info

```shell
- [x] PostHog Cloud, Debug information: [please copy/paste from https://us.posthog.com/settings/project-details#variables]
- [ ] PostHog Hobby self-hosted with `docker compose`, version/commit: [please provide]
- [ ] PostHog self-hosted with Kubernetes (deprecated, see [`Sunsetting Kubernetes support`](https://posthog.com/blog/sunsetting-helm-support-posthog)), version/commit: [please provide]
```

**Comment by pauldambra** [comment]
Hey, 

beacon is not something newly added to posthog, it's a mechanism in posthog-js to try and make sure we send any remaining data when the page is unloading

https://github.com/PostHog/posthog-js/blob/70d167fe67365f30b2ec8a720f31a111a4dfae1b/src/request.ts#L167

so, it's not sending any new data to PostHog, it's just another attempt to send the data you've already configured to be sent

we add `beacon` as an available transport when the browser supports it
