### ISSUE TITLE
Bug Report: `Export current columns` for cohort exports ALL person columns

### ISSUE THREAD

**Issue by slshults** [PostHog/posthog#23166]
## Bug description

When editing a cohort, if you `Export` / `Export current columns` / `CSV`, the resulting file contains all person columns, instead of just the "*current columns*" displayed while editing the cohort.

1. Create, or edit an existing cohort
2. Scroll down to make sure results are being returned 
3. Click the `Export` button
4. Select `Export current columns`
5. Select `CSV`
6. Download the exported file and view it.
7. Note that it contains all the columns, not just 3

![CleanShot 2024-06-21 at 15 33 08@2x](https://github.com/PostHog/posthog/assets/227448/0f9ab90a-70d4-41f2-a9cd-113a287d3905)

Example cohort: https://us.posthog.com/project/46220/cohorts/75452

## Additional context
A currently available work-around is, on step 4 above, select "Edit SQL directly", then on the resulting page, use the `Export` button to `Export current columns`.

Bug report from: https://posthoghelp.zendesk.com/agent/tickets/15005 

### Debug info

```shell
Session: https://us.posthog.com/project/sTMFPsFhdP1Ssg/replay/01903cec-a6aa-7f13-8f26-4df68481dfe7?t=131 
Admin: http://go/adminOrgUS/018c64bd-655c-0000-34a4-4d984a7dbc8f (Project: 46220)
Sentry: http://go/sentryUS/46220
```

**Comment by webjunkie** [comment]
Note that the person columns is a column with the person object. Just our UI display this object as one. The CSV contains it in full however. While technically alright, it's not useful 🫠
