### ISSUE TITLE
Metrics and events alerting

### ISSUE THREAD

**Issue by shvatsky** [PostHog/posthog#23176]
## Is your feature request related to a problem?

Hi folks! It would be great to have a feature of alerting when some of the metrics are decreasing/increasing or when some event's amount is decreasing or becomes 0.

## Describe the solution you'd like

Feature of alerting in form of email message or similar.

## Additional context

Other systems like Amplitude have this opportunity.

**Comment by jannesblobel** [comment]
+10
@shvatsky, thanks for raising this issue. I was just about to suggest it, too. Such a helpful feature.

**Comment by webjunkie** [comment]
Closing as duplicate of #14331
