### ISSUE TITLE
List queries to postgres/clickhouse in API responses on query parameter

### ISSUE THREAD

**Issue by macobo** [PostHog/posthog#2320]
## Is your feature request related to a problem?

We have many amazing bug catchers who are filing many [bugs](https://github.com/PostHog/posthog/issues?q=is%3Aissue+is%3Aopen+label%3Abug), including ones about query results being off.

It would be great to give them the tools to fix (at least partially) the bug themselves. However in case of debugging queries to get to a fix you first need to spend a ton of effort getting your development environment up to speed to be able to reliably log, reproduce and fix queries. We can make this loop shorter.

## Describe the solution you'd like

Add optional parameter `&log_queries` to all API endpoints.

If user is staff then this adds an array to the json response, containing all clickhouse/postgres queries made with a traceback.

This should make it easier to jump into tools like datagrip, see what the query is doing and fixing it.

## Describe alternatives you've considered

- Making it easier to use `heroku run` to jump to production + replay requests with logging from there + edit live code. This would work with ruby, but from my attempts w/ django the tooling is not there.
- Keeping the cycle of bugfixers small 

## Additional context

cc @yakkomajuri @paolodamico  - would this help you guys when filing issues/combating bugs?

Related PR: https://github.com/PostHog/posthog/pull/2302

**Comment by yakkomajuri** [comment]
I think this could be useful yes - hadn't thought of it
