### ISSUE TITLE
One click Salesforce Data Warehouse integration

### ISSUE THREAD

**Issue by camerondeleone** [PostHog/posthog#23208]
## Is your feature request related to a problem?

One click integration for warehouse, to connect top of funnel / web data to sales data to outcome data all within PostHog. It's come up a couple times in the last month from GTM teams and I expect it will only continue.

For starters just standard tables like Leads, Contacts, Accounts, Opportunities would do. 

## Describe the solution you'd like

More context here:  https://posthog.slack.com/archives/C019RAX2XBN/p1719264558482169

**Comment by Gilbert09** [comment]
This has been completed since https://github.com/PostHog/posthog/pull/23212
