### ISSUE TITLE
Customize session window

### ISSUE THREAD

**Issue by Immortalin** [PostHog/posthog#2329]
## Is your feature request related to a problem?

30min of inactivity is unsuitable for mobile applications where the time in between sessions are often much shorter.

## Describe the solution you'd like

Make the window customizable. Amplitude sets it at 5min.

**Comment by yakkomajuri** [comment]
Thanks for the feedback on this!

**Comment by Twixes** [comment]
We have removed that iteration of the sessions feature, but will definitely come back with a more versatile one in the future, taking this feedback into account.
