### ISSUE TITLE
Customize properties view on events table

### ISSUE THREAD

**Issue by yakkomajuri** [PostHog/posthog#2331]
## Is your feature request related to a problem?

*Please describe.*

Based on user feedback.

I want to be able to select what properties get hidden and which should be visible. I also want my custom props at the top. 

## Describe the solution you'd like

Custom props at the top + some config for hiding props.

## Describe alternatives you've considered

Leave as is.

**Comment by paolodamico** [comment]
You can now customize the columns you display in the events table.
