### ISSUE TITLE
Create a custom session recording player

### ISSUE THREAD

**Issue by macobo** [PostHog/posthog#2332]
## Is your feature request related to a problem?

Quite a few session recording issues are not (easily) solvable with the default rrweb-player. https://github.com/PostHog/posthog/issues/2096 https://github.com/PostHog/posthog/issues/2129 https://github.com/PostHog/posthog/issues/2131, maybe https://github.com/PostHog/posthog/issues/2258

## Describe the solution you'd like

Create our own react-based player.

Would need someone more UX-minded to pair on this with.

## Describe alternatives you've considered

Making upstream PRs - but some of the features will be tightly integrated with our product.

**Comment by paolodamico** [comment]
Happy to work on this with you if it makes sense.
