### ISSUE TITLE
Bug Report: Event based survey misfires when event changed

### ISSUE THREAD

**Issue by slshults** [PostHog/posthog#23336]
## Bug description

Event based surveys triggered by previously selected event, after selected event is changed

## How to reproduce

1. Create a survey with the only condition being a specific event set as trigger 
2. Do the event
3. The survey is triggered
4. I change the trigger event for the same survey
5. I refresh the browser page or application
6. The survey is triggered again even though the newly selected event was not done

e.g. https://eu.posthog.com/project/25911/surveys/01905f0a-a3ab-0000-74fc-f06776592812

## Additional context
From: https://posthoghelp.zendesk.com/agent/tickets/15103

### Debug info

```shell
Session: https://us.posthog.com/project/sTMFPsFhdP1Ssg/replay/01905f8e-fd04-7d78-b9d6-4e3613d3555c?t=0 
Admin: http://go/adminOrgEU/018fb953-35c0-0000-704b-5a6a21df7ce8 (Project: 25911)
Sentry: http://go/sentryEU/25911
```

**Comment by Phanatic** [comment]
This bug is fixed in https://github.com/PostHog/posthog-js/pull/1273
