### ISSUE TITLE
Bug Report: Draft Experiment incorrectly says `can edit your variants`

### ISSUE THREAD

**Issue by slshults** [PostHog/posthog#23346]
## Bug description

If you create an experiment, save it as a draft, then go back into edit mode to add, rename, or remove variants, clicking `Save draft` results in error message: `Cant' update feature_flag_variants on Experiment`:

![CleanShot 2024-06-28 at 15 14 00@2x](https://github.com/PostHog/posthog/assets/227448/965ce2a4-3a36-457f-81e7-3e7c6272d697)

That error is unexpected by the user because it conflicts with the info box on draft experiments:
![CleanShot 2024-06-28 at 15 19 09@2x](https://github.com/PostHog/posthog/assets/227448/9ecfcf83-2f7c-4dc3-acab-3c36c5a6cad1)

The variants also cannot be edited on the Feature Flag with the experiment in draft mode:
![CleanShot 2024-06-28 at 15 15 26@2x](https://github.com/PostHog/posthog/assets/227448/0cbce5c3-cc66-404a-bd72-d527e5852167)

## How to reproduce

1. Create an experiment
2. Save it as a draft
3. Edit the draft experiment
4. Edit, add, or remove one or more variants
5. `Save as draft`
6. Note error message in lower-right corner of page

## Additional context
From: https://posthoghelp.zendesk.com/agent/tickets/15183

### Debug info

```shell
Session: https://us.posthog.com/project/sTMFPsFhdP1Ssg/replay/019060d6-26df-7c51-93e9-baaedddc7e6e?t=2021 
Admin: http://go/adminOrgUS/018e0bbc-c53f-0000-645b-2bdad69f5c3e (Project: 56933)
Sentry: http://go/sentryUS/56933
```

**Comment by sumtzehern** [comment]
I am working on this issue

**Comment by balanxiao** [comment]
Hi, I am working on this issue with @sumtzehern. We have issues recreating the bug on the devlopement environment, even though we can see it on the actual webpage. Here are some side by side screenshot differences. 

![image](https://github.com/user-attachments/assets/2933f95b-8618-4110-af79-49cb5b573a2e)

**Comment by sumtzehern** [comment]
Hi @slshults,

I tried to reproduce the bug described but did not encounter the error message: `Can't update feature_flag_variants on Experiment`. I was able to add, remove, or rename variant keys without issues in the experiment. 

https://github.com/user-attachments/assets/5607e303-f79d-44ba-97bd-44a25d66219d

However, I noticed that the add variant key button in feature flags is still uneditable, but the description, Payload and Rollout are editable. Based on my understanding, adding variants to the feature flag requires adding them from experiment. 

Could you please confirm if this is still a bug or if there have been any recent changes? Thank you.

<img width="1164" alt="Screenshot 2024-07-22 at 4 14 48 PM" src="https://github.com/user-attachments/assets/dd9d401f-d3a2-43d7-ae0a-ebbfa7fdc029">

**Comment by danielbachhuber** [comment]
This bug no longer exists because "edit mode" doesn't exist for experiments.
