### ISSUE TITLE
Visualize sessions as a timeline showing page views and actions

### ISSUE THREAD

**Issue by willbenica** [PostHog/posthog#2335]
## Is your feature request related to a problem?

When looking at a session (currently a list of events), it's difficult to understand what the user was trying to do. Having a graph showing a timeline of page views and clicks would help digest a session at a glance. A session recording helps, but doesn't show an overview at once - every recording needs to be watched - to grasp what the user was doing.

## Describe the solution you'd like

_Session Maps_ (as the major events of a session are mapped out):

At least a one dimensional graph showing page views and clicks over time. 
<img width="918" alt="oneDimensionalPageViewsOverTime" src="https://user-images.githubusercontent.com/1443768/98801094-98b56200-2411-11eb-8154-f7aad9f0a6d2.png">
* colours are based on  groups (e.g. landing/home page, search, asset, analytics) -> see #2334 
* bars are pages
* circles are clicks 
The above could then be interpreted as a user has logged in, searched for an asset, viewed the asset, and then did some analytics before logging out.
It's easy to see that the user spent most of their time searching and analysing.

It's also possible to imagine a two-dimensional graph where we can show a bit more detail over time:
![twoDimensionalGraph](https://user-images.githubusercontent.com/1443768/98802031-f9916a00-2412-11eb-9587-721b4f9b7eef.png)
This the same as above, but the Y-axis shows how the search query is specified in the URL:
* `baseURL/search?q=` - default search page
* `baseURL/search?q=&owner=john` - search for all assets where john is the owner
* `baseURL/search?q=posthog` - search for all assets with keyword `posthog`
* `baseURL/search?q=posthog&type=userAnalytics` - search for all assets with keyword `posthog` that are a certain type.

By showing page views as stacks of bars, it's easy to see that the search went in one direction which didn't lead further, and that the user reset and found the asset they were looking for.

## Additional context

* Session maps could be shown on the person page where sessions are listed, providing a quick overview of what that user was doing in the sessions, before drilling down into a specific session and seeing the list of actions, page views and events
* Providing customer support with access to session maps, would help them quickly understand what a user was doing before an support case came in

**Comment by paolodamico** [comment]
Thanks for the suggestion @willbenica, super helpful, very cool idea indeed! We already started discussing potential implementation strategies.

Just to note here from our discussion today @macobo, a consideration for an initial MVP would be to implement this in a way that each different `$pageview` is distinguished by a different background and each click item would show a different type of event (e.g. `click`, custom, `$exception`, ...) by using different colors. This can then be used to understand at a glance how the user interacted with different parts of the site/app, if there are gaps in the session, or large periods of activity.

**Comment by willbenica** [comment]
@paolodamico,
One thing to note, is it might be good to use different icons for different types of events. It helps keeps things accessible for those who are colour blind (speaking from experience).

**Comment by paolodamico** [comment]
Re @willbenica makes total sense, thanks for the suggestion here, we'll definitely consider that!

**Comment by Twixes** [comment]
There's now a useful events timeline in the session recording player. :)
