### ISSUE TITLE
Migrate team signup to React

### ISSUE THREAD

**Issue by paolodamico** [PostHog/posthog#2336]
## Is your feature request related to a problem?

`/signup/{token}` is still a Django view, which means that the UX is not great (e.g. the error messages are shown in a small dark font which are easy to ignore, huge password requirements, etc.)

## Describe the solution you'd like

I'd like this view to implemented in React to follow the general UX of the new org sign up page.

## Describe alternatives you've considered

Keep the current version which is confusing and likely causing a drop in sign ups.

## Additional context

Related to #2259 and reported again [here](https://posthog.slack.com/archives/C015UVBEHCN/p1605012777006900).

**Comment by paolodamico** [comment]
This should also help with an edge case with session recordings in which we lose some snippets of time from login to using the app.

**Comment by timgl** [comment]
Agree on password requirements, i bet we're losing people due to that
