### ISSUE TITLE
UI/UX improvements for persons & cohorts

### ISSUE THREAD

**Issue by paolodamico** [PostHog/posthog#2337]
We've detected a few UX issues with the current implementation of persons & cohorts (#1881, #2311, #1902, ...), they also don't follow our new design standards very well, as such this [new design](https://www.figma.com/file/gQBj9YnNgD8YW4nBwCVLZf/PostHog-App?node-id=215%3A0) introduces a new UI & UX for all the related views.

Worth mentioning, the new design particularly adds emphasis on session recording, as from early customer calls there has been a very positive response to it.

**Cohort view**
![detail](https://user-images.githubusercontent.com/5864173/98822395-b641f600-2428-11eb-98b9-d85e5879ea41.png)

**Comment by jamesefhawkins** [comment]
Thanks for this. A few thoughts:

* The numbers next to the cohort match groups signify an order, but they're an OR statement. I'd suggest removing. Perhaps we could put an 'OR' block across the horizontal rules (in same style as the inline AND you have in this example) with greater vertical spacing to make this clearer? You could then drop the explanatory sentence above.
* This display is clearly nicer. I do wonder if first seen and last seen are the best two columns to show?

**Comment by macobo** [comment]
If we're redesigning this page, let me explode the scope of this. 

I think we should unify Persons and Sessions pages.

### Usecases

There are the following use-cases that pass through those pages page:

1. looking for the source of a bug/issues ('what went wrong, what happened, what did the user see')?
2. looking for how a particular page/functionality is being used -> figure out how to improve it
3. looking for how a particular key client is using the product (are they active, what functionality are they using) -> either before a call or to make new sales
4. analyzing funnels/other graphs then exploring the raw data. E.g. what made these users drop off from the funnel? 
5. looking for users with certain characteristics, then defining a cohort on them

We serve some of them well, while others require jumping back-and-forth or we don't give a good overview (e.g. who is this user? what have they been up to?)

### Proposed solution

Make the persons page a key page where users can:
- See users at a glance, e.g. ordering them by last visit time
  - Showing their key user properties (email, etc) to know who this user is
  - Showing a quick summary of their sessions:
    - how long ago it was
    - what was done in it (e.g. actions, or https://github.com/PostHog/posthog/issues/2335)
    - provide a shortcut to jump to session recording
  - Provide a shortcut to jump to 'more details' for the user (current person page)
- Provide filtering capability as we do in insights
  - 'Show me users who have done X in the last Y'
  - 'Show me users who dropped off in this funnel'
  - 'Show me customers under my care/with a certain user property'
- Allow defining a cohort based on the filtering
- Allow to start a 'session replay session' based on the filter - i.e. I want to see users who dropped out of this funnel, what was their path through the app?
- Provide export capability to get the data out

The drawback of this (obviously) is that there will be a lot of things on one view - will it tick the right boxes or just feel busy?

### Other products

This is not a completely new idea. Inspiration from Heap:

![Screenshot from 2020-11-11 17-29-26](https://user-images.githubusercontent.com/148820/98830795-7a685a00-2443-11eb-9a10-00e862fb3356.png)

Couldn't find a screenshot from Auryc.


See also a related request from a client: https://github.com/PostHog/posthog/issues/2335

**Comment by paolodamico** [comment]
Thanks for the feedback,

### @jamesefhawkins 
- Completely agree with point 1, will address this.
- Re point 2, I wanted to have something that was universal for everyone (as everything is pretty much a custom property), perhaps we should take this opportunity to allow users to select different columns to show. Do you have a suggestion for which other columns to show by default?

### @macobo
Great, great points, thanks for taking the time to think this through, agree with the use cases perspective!
- From my POV I'm thinking we still might need the separate sessions, events & users pages to cover all the use cases you describe in the most intuitive way. e.g. even if we had a non-too-cluttered way of showing the last session overview for each user in the users view, I believe there are use cases that are better served with a centralized sessions page (e.g. if I just want to randomly watch session recordings, seeing sessions of a given day, etc.)
    - A related point of complexity I see arising here is that if for instance you filter by users that "visited pricing page" in the "last 30 days", but the session overview doesn't show the exact relevant session where each user visited the pricing page, it'd be quite confusing (i.e. we couldn't just show an overview of the last session). 
- Completely agree with the options of improving the filtering ( _"Provide filtering capability as we do in insights"_) & adding #2335.
- I believe the data export & creating cohort from filtering features are already considered.

**Comment by paolodamico** [comment]
Thanks to a very productive discussion today with @macobo, I'll be splitting up this issue into separate smaller issues in the spirit of quick improvements (shipping quickly) and simplifying discussion / feedback. New issues will be referenced below.
