### ISSUE TITLE
Deleted Action ID still being referenced on new actions in Live Actions

### ISSUE THREAD

**Issue by mrsweaters** [PostHog/posthog#234]
I would expect these to go back to showing the reason they were recorded in the first place.

**Comment by timgl** [comment]
Good catch, we weren't filtering out deleted actions!

I'm not sure I entirely understand "I would expect these to go back to showing the reason they were recorded in the first place.", would you mind elaborating?

**Comment by mrsweaters** [comment]
For that second part, I think I was moving too fast and confused the "Events" page with the "Live actions" page. I think it's fine as long as the deleted action goes away.

**Comment by timgl** [comment]
Great, will close this for now then :)
