### ISSUE TITLE
Bug Report: Long running insight query blocks all other insights from loading

### ISSUE THREAD

**Issue by skoob13** [PostHog/posthog#23440]
## Bug description

When we open an insight that could potentially load indefinitely, like #22999, after closing the loading insight and opening another insight, the web app doesn't cancel the first query and continues loading the first insight.

## How to reproduce

Easy to reproduce on the insight from this [ticket](https://posthoghelp.zendesk.com/agent/tickets/15371).

1. Open a funnel query with many steps (10+).
2. Click the browser back button.
3. Open an existing trends insight or create a new one.
4. The app continues to load the first insight.

## Expected result

When a user leaves the Insight page, the app should abort the first request so that it stops trying to retrieve data.

### Additional Context

[Support Ticket](https://posthoghelp.zendesk.com/agent/tickets/15410)

**Comment by thmsobrmlr** [comment]
Might be a duplicate https://github.com/PostHog/posthog/issues/21557

**Comment by anirudhpillai** [comment]
Was fixed by disabling 'chaining' for dashboard refresh
#24057
