### ISSUE TITLE
Create an `events` table to store unparsed events from Kafka

### ISSUE THREAD

**Issue by tiina303** [PostHog/posthog#23450]
> Please avoid using `debug` either as a prefix or suffix! 🏄 

This table must store raw events from Kafka, without parsing the payload. Just keep it as it is.

Additional metadata that should be stored as well to allow monitoring properly the Kafka consumption is:

- `offset`
- `partition`
- `timestamp`
- `hostname` of the host consuming the event

Lastly, we need to set it up with a TTL of 14 days, no deduplication engine, and without skipping any malformed events.

Optionally, we can enable the `stream` error mode for Kafka tables and store the `error` and `raw_message` columns as well.

**Comment by fuziontech** [comment]
We need to research how to efficiently keep an s3 table in clickhouse

**Comment by fuziontech** [comment]
This has been resolved - we have this writing to S3 and have a table in Athena to hit this
