### ISSUE TITLE
Clickhouse cohort caching queries containing action are slow

### ISSUE THREAD

**Issue by macobo** [PostHog/posthog#2345]
## Bug description

Currently cohort queries filtering on actions (without a time frame) the following are slow to calculate on clickhouse:

https://files.slack.com/files-pri/TSS5W8YQZ-F01EAJGBWAZ/screenshot_from_2020-11-10_11-41-32.png

Example query can be found in slack: https://posthog.slack.com/archives/C019RAX2XBN/p1605093645000500

We currently refresh these every hour in production.

## Expected behavior

These calculations go fast

## How to reproduce

1. Open production python shell with env variable PRINT_SQL=1: `heroku run -a posthog "cd deploy; PRINT_SQL=1 python manage.py shell_plus"`
1. Find a cohort for a large customer / a lot of people
1. Run cohort.calculate_people, e.g. `Cohort.objects.get(pk=2).calculate_people()`
1. Wait a long time

## Environment

- Cloud 

## Additional context

This calculation is done to cache `cohort.people` inside postgres. The fact we're returning people.ids might be causing some of the slowness. Not sure this is the case though, as even cohorts with 1k people can be slow.

Some ideas:
1. **Store cohort.people cache in clickhouse** - but this runs into issues around deleting data in clickhouse.
2. **Automatically generate materialized views for cohorts** - not sure what the impl looks like, would also slow ingestion down by a lot.
3. **For cohorts with action filters, do a time-based recalculation** - since users can't 'fall out' of this sort of cohort, we can look at events from since last calculation and add new users based on this.

Also noting that clickhouse people table and pg people table primary key being different is slightly painful, leads to more querying if we want to store this in postgres.

Related issue: https://github.com/PostHog/posthog/issues/2306

Currently also unsure how we'll solve actions on clickhouse - the solution there might tie into this.

cc @EDsCODE @fuziontech

**Comment by Twixes** [comment]
Curious if this is still an issue?

**Comment by EDsCODE** [comment]
We've since moved onto a new system so closing this. Query performance is still relevant but can be discussed as part of a separate thread with new context
