### ISSUE TITLE
shared dashboard stopped working

### ISSUE THREAD

**Issue by SuperKruse** [PostHog/posthog#2347]
## Bug description

Shared dashboard no longer works. 

```
TypeError: Cannot read property 'addFeatureFlagsHandler' of undefined
    at Ie.onFeatureFlags (shared_dashboard.js:8)
    at Object.afterMount (shared_dashboard.js:322)
```
## How to reproduce

1. share a dashboard
2. go to link
3. ???
4. success

## Environment

self-managed V 1.16.0

**Comment by timgl** [comment]
Sorry about that! I'll jump on this right away

**Comment by SuperKruse** [comment]
No worries, I'm impressed with you bug fixing speed. 
Thank you!

**Comment by timgl** [comment]
@SuperKruse This is fixed on master. Building the image might take a few minutes if you're using Docker
