### ISSUE TITLE
Bug Report: Pageview series name change not seen in persons modal series menu

### ISSUE THREAD

**Issue by slshults** [PostHog/posthog#23482]
## Bug description

In the modal seen after hovering over a point in a chart and doing `click to view people`, the menu to select the series still shows `$pageview` for each series, instead of the new name.

The name change is seen in the hover modal:
![image](https://github.com/PostHog/posthog/assets/227448/a0112e1c-511f-4564-a143-a61aec4c7e42)

The name change is not seen in the series menu in the persons modal:
![image](https://github.com/PostHog/posthog/assets/227448/dfcd308c-89ce-4f19-aad4-3383dd60ff02)

## How to reproduce
1. Create or view an insight with multiple pageviews as series
2. In edit mode, on the `Detailed results` table below the chart, use the pencil icon to rename each series.
3. Hover over a point on the chart, notice the name changes visible in the modal. Then `click to view people`
4. Notice that the menu for selecting a series stills shows `$pageview` for each

example insight:
https://eu.posthog.com/project/2161/insights/KHIxIcAE

### Debug info

```shell
Admin: http://go/adminOrgEU/0186099a-625a-0000-d96d-c58b13e58985 (Project: 2161)
Sentry: http://go/sentryEU/2161
```

**Comment by balanxiao** [comment]
I am working on this

**Comment by sumtzehern** [comment]
Hi,

I was able to reproduce the bug where the series name changes are visible in the modal but are not updated in the pop-up.

My understanding is that there might be a state management issue or a missing update trigger that causes the pop-up to not reflect the changes made in the modal.

Could anyone provide guidance on which files or components I should start looking into to debug this issue? Specifically, I would appreciate a starting point file that handles the pop-up logic.

Thank you in advance for your help!

**Comment by jannesblobel** [comment]
<3
