### ISSUE TITLE
Discussion: Toolbar renaming

### ISSUE THREAD

**Issue by paolodamico** [PostHog/posthog#2349]
We've tossed around the idea of renaming the toolbar as the current name,
a) does not communicate well what the feature actually does / its benefits, and
b) it's not actually a toolbar.

The goal of this thread is start a discussion on new potential names for this feature.

**Comment by mariusandra** [comment]
Agreed that it's not really a "toolbar" (as in the user interface element with the same name)... and unless you know what it does, it's unintuitive to guess that this is where heatmaps live.

Some brainfarts to get the ball rolling:

- PostHog "Floaty Button Thingie" or "PH FBT" for short.
- PostHog Site Explorer
- PostHog SiteHog
- Inspector Hog
- Urchin
- InlineHog
- RoverHog
- HogScout

Of these I like "Site Explorer" the best, as it literally says what you can do with it.

**Comment by paolodamico** [comment]
I like something around "Inspector" or "Site explorer", the latter I agree with @mariusandra best communicates the functionality.

**Comment by yakkomajuri** [comment]
Sorry had to post...

"Inspector Hog" brought this image to mind:
<img width="400" src="https://user-images.githubusercontent.com/38760734/99085892-ae1cbe80-25c0-11eb-87a5-bce39b43a41e.png" />

**Comment by daibhin** [comment]
Closing this one out because it's not an active topic of discussion within the team right now... and "PostHog Site Explorer" didn't poll well with the ICP focus group
