### ISSUE TITLE
Remove autosave on action edit.

### ISSUE THREAD

**Issue by mrsweaters** [PostHog/posthog#235]
I may make a mistake that erases some of the action, I then have to start over since autosave overwrote my original action.

**Comment by timgl** [comment]
We don't autosave actions necessarily. Is it annoying that when you click on "Save action" you get sent back to PostHog? Are you editing the selectors manually, and is that whats being overwritten?

**Comment by mrsweaters** [comment]
I'm actually not quite sure what I did. I'm not able to reproduce it now. I'm going to chalk this up to user error. 👀

**Comment by timgl** [comment]
👍
