### ISSUE TITLE
Cohorts UI/UX improvements

### ISSUE THREAD

**Issue by paolodamico** [PostHog/posthog#2350]
Derived from the splitting of #2337, this issue covers the proposal and discussion for the improved UI & UX of Cohorts.

- Full design: [Figma](https://www.figma.com/file/gQBj9YnNgD8YW4nBwCVLZf/PostHog-App?node-id=303%3A1298)
- Relevant frames: `cohorts` & `cohorts/detail`.

**Cohort list.**
<img width="1152" alt="cohorts" src="https://user-images.githubusercontent.com/5864173/98949592-d5578b00-24ef-11eb-9a67-af2918e4b754.png">

### Related issues.
Implementing this would address:
- #1881
- #1902 & #2311 as pagination would be replaced with a automatic endless scroll, plus the introduction of search.
- #2308 * depending on how we implement this.

**Comment by macobo** [comment]
In the current design we have separate tabs for All/Identified/Unidentified. The new one mixes these back up. Is that intentional?

**Comment by Twixes** [comment]
This seems addressed in practice since.
