### ISSUE TITLE
Bug Report: Funnel query with many steps throws a timeout

### ISSUE THREAD

**Issue by skoob13** [PostHog/posthog#23522]
## Bug description

Funnel query with 12+ steps sometimes never completes for users because the SQL query is terminated.

## How to reproduce

1. Create a funnel query with many steps (e.g. 14)
2. Query is terminated after a timeout

**Response from the query status endpoint**
```json
{
    "type": "invalid_request",
    "code": "not_found",
    "detail": "Query c36f4d80-6404-44c1-8b08-a303f97cf9bf not found for team",
    "attr": null
}
```

**Exception**
```
Code: 210. DB::NetException: Connection reset by peer, while reading from socket (ip:50148). (NETWORK_ERROR) (version 23.12.5.81 (official build))
```

## Additional context

- [Example Query on Metabase](https://metabase.prod-eu.posthog.dev/question/286-funnels-query-timeout-exception)
- [Ticket 1](https://posthoghelp.zendesk.com/agent/tickets/15410) - 14 steps in the funnel
- [Ticket 2]( https://posthoghelp.zendesk.com/agent/tickets/15371) - 16 steps in the funnel
- [Ticket 3](https://posthoghelp.zendesk.com/agent/tickets/15588)
- [Ticket 4](https://posthoghelp.zendesk.com/agent/tickets/15607)
- [Ticket 5](https://posthoghelp.zendesk.com/agent/tickets/13065)
- [Ticket 6](https://posthoghelp.zendesk.com/agent/tickets/14394)
- [Ticket 7](https://posthoghelp.zendesk.com/agent/tickets/14626)
- [Internal Discussion 1](https://posthog.slack.com/archives/C0368RPHLQH/p1720022726406609)
- [Internal Discussion 2](https://posthog.slack.com/archives/C0368RPHLQH/p1720027169299129)
- [Full SQL query for Ticket 1](https://metabase.prod-eu.posthog.dev/question/287-funnel-timeout)

**Comment by webjunkie** [comment]
+1 https://posthoghelp.zendesk.com/agent/tickets/15970 (moved to PostHog: https://us.posthog.com/project/2/support/tickets/18964)
+1 https://posthoghelp.zendesk.com/agent/tickets/16148 (moved to PostHog: https://us.posthog.com/project/2/support/tickets/18971)

**Comment by slshults** [comment]
+1 https://posthoghelp.zendesk.com/agent/tickets/17333 (moved to PostHog: https://us.posthog.com/project/2/support/tickets/19324)

**Comment by slshults** [comment]
+1 https://posthoghelp.zendesk.com/agent/tickets/17350 (moved to PostHog: https://us.posthog.com/project/2/support/tickets/20186)

**Comment by slshults** [comment]
+1 https://posthoghelp.zendesk.com/agent/tickets/17388 (moved to PostHog: https://us.posthog.com/project/2/support/tickets/19780)

**Comment by abigailbramble** [comment]
+1 https://posthoghelp.zendesk.com/agent/tickets/17444 (moved to PostHog: https://us.posthog.com/project/2/support/tickets/19784)

**Comment by abigailbramble** [comment]
+1 https://posthoghelp.zendesk.com/agent/tickets/18226 (moved to PostHog: https://us.posthog.com/project/2/support/tickets/20583)

**Comment by slshults** [comment]
+1 https://posthoghelp.zendesk.com/agent/tickets/18342 (moved to PostHog: https://us.posthog.com/project/2/support/tickets/20687)

**Comment by darkopia** [comment]
+1 https://posthoghelp.zendesk.com/agent/tickets/18479 (moved to PostHog: https://us.posthog.com/project/2/support/tickets/20337)

**Comment by abigailbramble** [comment]
+1 https://posthoghelp.zendesk.com/agent/tickets/19789 (moved to PostHog: https://us.posthog.com/project/2/support/tickets/22669)
