### ISSUE TITLE
Sessions page UI/UX improvements

### ISSUE THREAD

**Issue by paolodamico** [PostHog/posthog#2352]
Derived from the splitting of #2337, this issue covers the proposal for the new Sessions page proposal.

- Full design: [Figma](https://www.figma.com/file/gQBj9YnNgD8YW4nBwCVLZf/PostHog-App?node-id=329%3A88)
- Relevant frames: `sessions`, `sessions/expanded`, `sessions/filtered` & `sessions/event`

Huge shout-out to @macobo for the ideas on how to provide extra context on sessions to make this feature a lot easier to use, and considerably more helpful.

- Will address #2281 & #1069
- Will partially address #2130 (still missing jumping to a specific point in a session recording).

**Comment by macobo** [comment]
I think this is a step in the right direction. Some questions-thoughts:

- Filtering by cohort/user properties is gonna come in valuable here.
- How will we decide what events to show on the bar? How is it ordered? (great q to ask if we're testing the design)
- Let's add a 'Play all' button which cycles through the recordings.
- Should we allow changing color/icon when opening the event details?

**Comment by timgl** [comment]
The important thing I'm missing here is the feeling of watching these sessions 'live'. The coolest/creepiest thing would be to just have a grid of sessions that are happening live (or close to live), like a stack of security tv cams.

A simpler solution is to just highlight sessions that had events in the last minute or so, and add a flashing red circle to indicate stuff is happening _right now_. 

I think getting that feeling of immediacy will make this feature much stickier and more fun to use.

**Comment by paolodamico** [comment]
Thanks for the feedback @timgl, love the idea of having some immediacy indicator, it can work as an early warning system, plus I agree it might definitely help make the feature more sticky. See below or on Figma.

<img width="605" alt="image" src="https://user-images.githubusercontent.com/5864173/100938834-faba3200-34ba-11eb-9f5a-32d2b23e255f.png">

I think the CCTV idea we should keep as a separate issue, and while I do agree it could be super useful, fun and certainly an interesting product distinction, I do get an uneasy feeling thinking about it.

Let me know your thoughts.

**Comment by paolodamico** [comment]
This has evolved a lot, particularly around #4884 and the improvements we're doing to the playback experience. Closing.
