### ISSUE TITLE
Trends total value tables should be paginateable

### ISSUE THREAD

**Issue by thmsobrmlr** [PostHog/posthog#23554]
https://posthoghelp.zendesk.com/agent/tickets/15364

> Pagination on tables appears to broken.
> 
> Viewing this insight (https://us.posthog.com/project/2/insights/bn1ojimP) shows around 20 entries, but when I exported the data is gave me around 60.
>
> There should be a 'Load more' option on the insight, but it's not appearing.

**Comment by webjunkie** [comment]
That's just the breakdown limit, isn't it? It's higher when you export, so you get more data then.
If you want more in the table, you can increase the breakdown limit.
Or are there other cases where we need pagination in this table?
