### ISSUE TITLE
Bug Report: Exported insight image is cut off

### ISSUE THREAD

**Issue by skoob13** [PostHog/posthog#23573]
## Bug description

Exported image has a fixed size while insights might have a larger width.

![Posthog Screenshot](https://github.com/PostHog/posthog/assets/13541795/225dde33-adc1-44ba-9598-40cc5e55ffbe)

## How to reproduce

1. Create a funnel with five steps
2. Export the insight

## Expected result

The full visualization should be visible.

## Additional context

[Support Ticket](https://posthoghelp.zendesk.com/agent/tickets/15492)
[Support Ticket 2](https://posthoghelp.zendesk.com/agent/tickets/15290)

**Comment by webjunkie** [comment]
I can take a look at that.
