### ISSUE TITLE
"Only match if URL contains" does not work as expected when creating an Action

### ISSUE THREAD

**Issue by mrsweaters** [PostHog/posthog#236]
If I enter `example.com/register` in the "URL contains" input i would expect the results to include those with that url. If I uncheck the filter and save, then I get event matches that contain `example.com/register`. Event if I try `register` nothing gets matched.

**Comment by wundo** [comment]
I'm experiencing the same behaviour

**Comment by jamesefhawkins** [comment]
Thank you for reporting this issue.

"only match if URL contains" is currently an *exact* match type, rather than a "phrase" match. This contradicts the wording and isn't the intended behavior.

**Comment by mrsweaters** [comment]
The interesting thing is that I wasn't even able to get exact match to work correctly. I would copy the url from the event and paste it into the URL match input and it would disappear. I'm not sure how to get anything to match.

**Comment by timgl** [comment]
Fixed! You can now select whether you want the url to contain your input, or exactly match.
![image](https://user-images.githubusercontent.com/1727427/75837697-8101e600-5d7a-11ea-8f51-0cdb9be81906.png)
