### ISSUE TITLE
Replace simmer.js with custom-built solution for element -> selector creation

### ISSUE THREAD

**Issue by macobo** [PostHog/posthog#2362]
## Is your feature request related to a problem?

A important piece of functionality in the toolbar is creating actions via selecting the element and using a automagically generated selector. If the selector is great, users have a really smooth experience. If not great, they might end up with misleading data or need to spend a lot of time manually editing selectors.

In practice some of our users have not been very happy with the results. Example issue, https://github.com/PostHog/posthog/issues/2140, @paolodamico interview notes contain more examples.

Also our fork of simmer.js has already become quite complex and deviated from w3c semantics of specificity.

## Describe the solution you'd like

Generating a good selector from an element hierarchy sounds like a reasonably min-max dynamic programming problem where:
1. The generated selector is as 'simple' as possible (prefer single id-based selector over complex div chains)
1. The generated selector identifies the selected element as uniquely as possible
1. The generated selector proposes selectors in a prioritized order (data-* > id > classes > tagnames > sibling relationships)
1. The generated selector detects autogenerated ids/class names and deprioritizes them
1. The innermost element is always present in the selector, but other selectors in the hierarchy might be or not be depending on the above criteria

## Describe alternatives you've considered

Patching holes in simmer.js - however the behavior currently is a bit unpredictable and the model used is not a great fit for us

## Additional context

cc @mariusandra for extra context.

Having good (complex) examples here would help generate the best algorithms. Will create a PR for capturing this info in the toolbar.

**Comment by mariusandra** [comment]
Hey @macobo, [our fork](https://github.com/PostHog/simmerjs) of simmer has indeed diverged quite a bit from upstream. I [made a PR](https://github.com/gmmorris/simmerjs/pull/19) with a patch in August to add support for Tailwind CSS classes, which have colons `:` inside. The PR was made from my fork's `master`, prompting the later changes to be in the `local-release` branch, but it hadn't been merged yet. I closed that PR, merged all other changes to master and moved the package under the posthog organization. I also gave you access on npm to push new versions of the `@mariusandra/simmerjs` package. 

There is also [this notice](https://www.npmjs.com/package/simmerjs#warning) under the project. Perhaps we should reach out to @gmmorris?

That said, simmer basically does 3-4 of the 5 points above. It also somewhat does dynamic programming to achieve this. It feels a bit more of a tree search though, but this nuance is quite irrelevant :P.

I would personally just extend our simmer and add a custom `data` key or keys that can be configured per-app that will complement our `data-attr` matcher. I imagine some page under project settings, or even in the toolbar, where you can type this in and simmer will then use it to uniquely identify your elements. This could be autosuggested (not autodetected) as well somehow.

For similar reasons to [what Tim mentioned](https://github.com/PostHog/posthog/issues/2140#issuecomment-724584124) I'm a bit afraid of automatically capturing or using data attributes that we haven't whitelisted.

**Comment by macobo** [comment]
> I would personally just extend our simmer and add a custom data key or keys that can be configured per-app that will complement our data-attr matcher.

I did this (will create a PR soon), but the results were less than amazing, prompting this issue. The current algorithm yields results like:

`[data-test-attribute-foo] > *` instead of `[data-test-attribute-foo] > [data-greek-letter="omega"]` or `[data-greek-letter="omega"]`  where element was not unique. 

There are other cases where our auto-detected selector is just bad, but gathering examples here is a bit hard. 

Given the importance of having solid and well-defined behavior here I do think a new library is warranted (since I think the algorithm used in simmerjs will need to be changed significantly).

> add a custom data key or keys that can be configured per-app that will complement our data-attr matcher. I imagine some page under project settings, or even in the toolbar, where you can type this in and simmer will then use it to uniquely identify your elements. This could be autosuggested (not autodetected) as well somehow.

By this suggestion we'd require going through your app with a fine comb and seeing what data attributes you're using to use basic functionality of the toolbar. This makes our onboarding way more complicated than it needs to be.

> For similar reasons to what Tim mentioned I'm a bit afraid of automatically capturing or using data attributes that we haven't whitelisted.

From my reading of posthog-js code we do capture data attributes on non-input elements, but I might be missing things.

**Comment by gmmorris** [comment]
> There is also [this notice](https://www.npmjs.com/package/simmerjs#warning) under the project. Perhaps we should reach out to @gmmorris?

Sorry y'all, while I had intended on picking Simmer up again, too much other work (predominantly my OSS work at Elastic) took over my time again.
I can probably find some time to review a clean PR now, given the pandemic lockdowns etc. 🤦 

Give me a shout if you want to go down that path.

**Comment by mariusandra** [comment]
[This library](https://github.com/fczbkk/css-selector-generator) showed up in my weekly Github Explore newsletter, along with [this comparison](https://github.com/fczbkk/css-selector-generator-benchmark).

There's no simmer in the comparison nor any mention of shadow roots, which we need to support. Still, might be something to check one day.

**Comment by pauldambra** [comment]
see https://github.com/PostHog/posthog/pull/13937

**Comment by pauldambra** [comment]
this was done in #13937
