### ISSUE TITLE
Bug Report: Batch exports - changing date range error 

### ISSUE THREAD

**Issue by slshults** [PostHog/posthog#23623]
## Bug description

When viewing runs of batch exports, trying to change the date range to `Last 30 days` results in: `TypeError: m. created_at.diff is not a function` error (does not occur with smaller date ranges):

![image](https://github.com/PostHog/posthog/assets/227448/06d9a848-4166-42d2-b9a3-2af6de97bcd5)

## How to reproduce

1. In the left sidebar, click `Data Pipeline`
2. Click `PostHog Batch Export`
3. Click the `Runs` tab
4. Toggle off the `Show latest runs` option
5. Set the date range to `Last 30 days` (works correctly for smaller ranges)
6. See error

## Additional context

From: https://posthoghelp.zendesk.com/agent/tickets/15598

### Debug info

```shell
Session: https://us.posthog.com/project/sTMFPsFhdP1Ssg/replay/01909eac-b9b7-7e81-af81-3f1b7e57a2af?t=153 
Admin: http://go/adminOrgEU/018baefd-7a26-0000-e140-a2227e6eb7c3 (Project: 11870)
Sentry: http://go/sentryEU/11870
```

**Comment by tomasfarias** [comment]
This is fixed by https://github.com/PostHog/posthog/pull/23800
