### ISSUE TITLE
Session recording where css had not rendered

### ISSUE THREAD

**Issue by macobo** [PostHog/posthog#2365]
## Bug description

User reported a session recording where css had not rendered.

## Expected behavior

CSS should be rendered in session replays

## Environment

Posthog cloud 

## Additional context

Came up in a customer call, cc @jamding

**Comment by macobo** [comment]
From brief experimentation, it seems this recording is also missing a `FullSnapshot` event, likely the cause of most if not all failing snapshots. Note that some of the full snapshots did succeed later on.

**Comment by macobo** [comment]
This seems also be the case for sessions where a blank page is shown - I will be investigating the cause for this! cc @weyert

**Comment by paolodamico** [comment]
An additional case here in which CSS gets broken after jumping around in the navigation, https://posthogusers.slack.com/archives/CT7HXDEG3/p1605651815461100?thread_ts=1605580772.435800&cid=CT7HXDEG3

**Comment by omertalmi5** [comment]
@macobo  Hey, echarts elements show in recording as blank elements. Is it the same case?
https://www.npmjs.com/package/echarts

**Comment by lharress** [comment]
We're also experiencing this issue. Happy to provide some links on Slack if that will help.

**Comment by benjackwhite** [comment]
Closing due to the age of this issue. The recorder changes frequently and without specific context per-issue, keeping these old issues around doesnt make sense
