### ISSUE TITLE
Bug Report: Dashboards - filtering by `doesn't contain` causes query error

### ISSUE THREAD

**Issue by slshults** [PostHog/posthog#23655]
## Bug description

Using `doesn't contain` filter on `email` or a custom property results in a query error

## How to reproduce
1. Duplicate [this insight](https://us.posthog.com/project/4889/dashboard/191984)
2. Add a filter for `email` `doesn't contain` `xx`
3. Save and apply the filter
4. See the error
(Also occurs with `User_email` `doesn't contain` `xx`)

## Additional context
From: https://posthoghelp.zendesk.com/agent/tickets/15453

### Debug info

```shell
Session: https://us.posthog.com/project/sTMFPsFhdP1Ssg/replay/0190a30d-2e55-75ea-b7d4-67a6d1688af5?t=3916 
Admin: http://go/adminOrgUS/017d06dc-5705-0000-f531-0e30052bb67f (Project: 4889)
Sentry: http://go/sentryUS/4889
```

**Comment by geng0610** [comment]
It looks like this issue is happening again :/ https://github.com/PostHog/posthog/issues/24429
