### ISSUE TITLE
Retention insight should support "On or after" logic

### ISSUE THREAD

**Issue by thmsobrmlr** [PostHog/posthog#23661]
At the moment our retention chart will add a person to week X, if they performed the retention event exactly in week X. It would be useful to also have a toggle where the event can be performed in week X or any of the following weeks. This leads to a more continuous retention graph and is supported by some of our competitors.

See here for a related support ticket: https://posthoghelp.zendesk.com/agent/tickets/15618.

A video explaining the two different options "on" and "on or after": https://www.youtube.com/watch?v=3ucW4aJk0h4&t=330s

**Comment by isAdrisal** [comment]
Hey @webjunkie, thanks for adding this feature!

Perhaps I'm reading the chart incorrectly, but the below screenshot (starting week 1 on the left-most column) is unexpected. We definitely have churn in these weeks where users do not return in future periods, but they're showing as 100% retention.

Have I set this up incorrectly?

<img width="698" alt="Screenshot 2024-08-23 at 21 26 15" src="https://github.com/user-attachments/assets/9ba77669-7675-469c-bd35-da7855ff1827">

Report config:

<img width="800" alt="Screenshot 2024-08-23 at 21 29 41" src="https://github.com/user-attachments/assets/04652d65-5a0c-4227-8b0f-a5de688d4ef2">
