### ISSUE TITLE
Referrer tracking doesn't work correctly

### ISSUE THREAD

**Issue by thmsobrmlr** [PostHog/posthog#23692]
See https://posthoghelp.zendesk.com/agent/tickets/14940 and https://posthog.slack.com/archives/C05LJK1N3CP/p1720719062387739

Root-cause analysis by @robbie-c  https://github.com/PostHog/posthog/issues/23690

**Comment by aspicer** [comment]
Solved - user had introduced a `reset` call in their code. @robbie-c added posthog-js debugging to make this easier to see.
