### ISSUE TITLE
Recordings push down the content of the pages in some cases

### ISSUE THREAD

**Issue by JorienDialog** [PostHog/posthog#23802]
## Bug description

In some of the session recordings the content of the page is pushed down (below the fold). This makes it hard to get insights, since it's not clear were the user moving his/her mouse. See example: https://app.dialog.nl/user/goals?goalId=1142589&c=1079819 

And see screenshot: https://i.imgur.com/DTy0OHX.png

## How to reproduce

1. Login
2. Go to recordings
3. View some of the recordings (for example the one linked above).
4. See that the content shows very low (the read alert should just show at the top > right below the blue navigation on top).

### Debug info

```shell
- [ ] PostHog Cloud, Debug information: [please copy/paste from https://us.posthog.com/settings/project-details#variables or https://eu.posthog.com/settings/project-details#variables]
- [ ] PostHog Hobby self-hosted with `docker compose`, version/commit: [please provide]
- [ ] PostHog self-hosted with Kubernetes (deprecated, see [`Sunsetting Kubernetes support`](https://posthog.com/blog/sunsetting-helm-support-posthog)), version/commit: [please provide]
```

**Comment by pauldambra** [comment]
Hey @JorienDialog 

This type of thing is always a problem with CSS capture from your site. Can you run through the in-app support flow https://us.posthog.com/#panel=support%3Asupport%3A%3Alow%3Atrue to open a ticket?

We'll need to look at your site and recordings specifically

thanks!

**Comment by JorienDialog** [comment]
Thanks for the response. I added it via the in-app support flow.
