### ISSUE TITLE
Show when events happen on session replay progress bar

### ISSUE THREAD

**Issue by macobo** [PostHog/posthog#2384]
## Is your feature request related to a problem?

When viewing sessions I'd like to skip to where the action is. 

## Describe the solution you'd like

Indicate when activity occurs in the progress bar to allow skipping around.

## Describe alternatives you've considered

Using a related feature https://github.com/PostHog/posthog/issues/2129

## Additional context

Thanks @jamding for pointing out this idea.

**Comment by macobo** [comment]
Note: Depends on https://github.com/PostHog/posthog/issues/2332

**Comment by macobo** [comment]
![Screenshot from 2020-12-01 12-32-55](https://user-images.githubusercontent.com/148820/100729422-6b851f80-33d1-11eb-9904-176974971d24.png)
Example from livesession

**Comment by Twixes** [comment]
The new player has this.
