### ISSUE TITLE
Navigation broken between events and actions

### ISSUE THREAD

**Issue by mariusandra** [PostHog/posthog#2393]
## Bug description

- "Actions" won't highlight when clicked the first time
- The title of the page remains "Events"
- The pages open if you click into them from outside any of them, later nothing changes

![2020-11-16 11 54 10](https://user-images.githubusercontent.com/53387/99244600-92a0f600-2802-11eb-8dcd-30f06f3dceb9.gif)

## Expected behavior

Should work consistently.

## How to reproduce

1. Click events or actions
2. Click the other one

## Environment

Master branch

## Additional context

Might also be wise to fix this before the next release. This seems like a pretty front and center bug.

**Comment by paolodamico** [comment]
Thanks for reporting! Seems we missed this because #2238 is behind a feature flag and #2319 considered when the feature flag is off. Will fix ASAP, fortunately #2238 is still behind a feature flag.
