### ISSUE TITLE
When playing sessions in fullscreen, the video controls disappear

### ISSUE THREAD

**Issue by JeppeSchmidt** [PostHog/posthog#2395]
## When playing sessions in fullscreen, the video controls disappear. I can't scroll in the video, go back and forward. 

*Please describe.*  
*If this affects the front-end, screenshots would be of great help.*  

## How to reproduce

1. 
2. 
3. 

## Environment

- PostHog cloud or self-managed?
- PostHog version/commit

**Comment by macobo** [comment]
Thanks for the report! Something to keep in mind as we tackle https://github.com/PostHog/posthog/issues/2332

**Comment by macobo** [comment]
This is now fixed with the new player - let us know if you have any feedback!!
