### ISSUE TITLE
WIP Multiple Users per account

### ISSUE THREAD

**Issue by Tannergoods** [PostHog/posthog#240]
**Is your feature request related to a problem? Please describe.**
I would like to add users to my account / invite teammates to see my data

**Describe the solution you'd like**
At the account level I would like to invite others to see my account data.

**Describe alternatives you've considered**
It is currently possible to create more users through adding /admin/ to the end of the URL and entering django admin.

**Comment by jamesefhawkins** [comment]
Thanks Aaron. This ticket addresses our decision to enable multiple users within the free edition #208. We should scope how this should look.

**Comment by timgl** [comment]
I think the steps are

- [x] Add signup_token field to team and automatically generate one
- [x] Show signup link in the interface
- [x] Add 'create account' view using a signup token, which automatically adds user to that team
- [x] (Optional) Add ticket for displaying team members

Am I missing anything?

**Comment by jamesefhawkins** [comment]
Agreed, thanks Tim.

I made #260 as a ticket for displaying team members, for now we just need the ability to add them, so that also makes sense.
