### ISSUE TITLE
Preview deployments with CH

### ISSUE THREAD

**Issue by paolodamico** [PostHog/posthog#2400]
## Is your feature request related to a problem?

Sometimes the feature you're testing is particularly different between Postgres & CH.

## Describe the solution you'd like

I'd like to have a way to deploy a preview environment that's running on CH, or even be able to actively switch between CH & Postgres in preview deployments.

## Describe alternatives you've considered

For CH stuff, just being able to test locally.

## Additional context

No additional context.

**Comment by Twixes** [comment]
This is now relatively easy with dockerized Kafka/ClickHouse/Zookeper.

**Comment by paolodamico** [comment]
Well the point of this was actually having an automatic deployed environment like we have for every PR through Heroku, so I don't think it's covered. 

However I haven't felt a need for it recently and if no one else has I think it makes sense to keep this closed. Thoughts ?

**Comment by Twixes** [comment]
Ah, as in Heroku review apps. I'm not sure if there's a way to have more than 1 review deployment per PR, but this would definitely be more complicated than the Postgres scheme, as would have to be docker-composed somehow to run ClickHouse and Kafka on Heroku alone. So quite a bit of work. May happen in the future though.
