### ISSUE TITLE
Activate Surveys based on events in the backend

### ISSUE THREAD

**Issue by Phanatic** [PostHog/posthog#24028]
### Problem description 

Currently, the "event based" survey support only works by observing any captured events in the client-side. 
To support Segment and server-sent events, we would like to provide a mechanism in surveys to track when an event is captured by the server, not just the client.

**Comment by EZWrighter** [comment]
Agree with this request.  Would be nice to be able to trigger the client side survey if the user has had the event triggered.

**Comment by marandaneto** [comment]
dupe https://github.com/PostHog/posthog/issues/25433
