### ISSUE TITLE
Add tagging to videos

### ISSUE THREAD

**Issue by GalDayan** [PostHog/posthog#2406]
## Is your feature request related to a problem?
As a UX Manager, I would like to tag a video after watching it, to easy access later.
It will make me more productive, I will be able to use the "Label Tagging" power.

## Describe the solution you'd like
Just like GitHub labels, only for movies.
Maybe later it will be necessary to add tags to every entity (Session, click etc..)

**Comment by paolodamico** [comment]
Hey @GalDayan, thanks for bringing this up! Closing this issue as we already have this in #2132, but the extra context is always very helpful. I do agree with you it might make a lot of sense to consider tagging in a more general sense, we'll definitely keep it in mind as we see how session recording tagging evolves.
