### ISSUE TITLE
Dashboard "Last 7 days" cannot reselect

### ISSUE THREAD

**Issue by boldtrn** [PostHog/posthog#2408]
## Is your feature request related to a problem?

When I click on insights, the default timeframe is "last 7 days". When I change that, to for example today, I cannot select "last 7 days" again. It' not in the list of choices. There is a choice "last week" but for me, last week means the last week, like Mo-Su and not last 7 days.

## Describe the solution you'd like

Have that option available :).

**Comment by timgl** [comment]
"Last week" does do the same as "last 7 days", but agree it's confusing. I've created a PR to address the confusion!

**Comment by boldtrn** [comment]
Thanks for the fast fix!
