### ISSUE TITLE
Access Properties of Autocapture Element in Queries / Breakdown

### ISSUE THREAD

**Issue by boldtrn** [PostHog/posthog#2409]
## Is your feature request related to a problem?

One example what I'd like to do: I want to know which URLs are being clicked most. Therefore I wan to filter autocapture events on links (that possible), but now I want to break them down by href, which seems to be not possible.

## Describe the solution you'd like

It would be great if I could access the properties of the autocapture element.

## Describe alternatives you've considered

An alternative would be track all link clicks as custom events - but that beats the purpose of having autocapture in the first place.

**Comment by GoldinGuy** [comment]
@boldtrn did you ever find a solution to this?

**Comment by boldtrn** [comment]
No, I attached custom events to all relevant Links :)

You might get this to work with the property flatener plugin maybe?
