### ISSUE TITLE
Implement public opt in link is broken

### ISSUE THREAD

**Issue by MattieTK** [PostHog/posthog#24100]
## Bug description
<img width="1218" alt="image" src="https://github.com/user-attachments/assets/8ef3498c-77b2-4910-9bca-6b28b1c4212f">
<img width="645" alt="image" src="https://github.com/user-attachments/assets/368062f3-4b0c-42a5-8a77-b9b778342bcd">

https://eu.posthog.com/project/27328/early_access_features/0191086e-10c2-0000-9fc0-44a78672979b

The early access features UI seems to include a link to /apps/ which I think is deprecated? The link inside the modal to the posthog provided UI doesn't work (as a result?).

## How to reproduce

1. Go to posthog cloud
2. Create a feature flag
3. Create an opt in feature flag
4. Use the opt in feature flag's UI to click through to the Implement Public Opt In button
5. Find that the URL linked in that dialog doesn't work.

### Debug info

```shell
- [x] PostHog Cloud, Debug information: https://eu.posthog.com/project/27328/early_access_features/0191086e-10c2-0000-9fc0-44a78672979b
```

**Comment by benjackwhite** [comment]
Thanks for reporting. Looks like a redirect we missed. I'll get a fix up asap
