### ISSUE TITLE
Bug Report: Clicking on a user ID which has no associated profile can result in 'person not found' page

### ISSUE THREAD

**Issue by abigailbramble** [PostHog/posthog#24114]
## Bug description

When on the activity tab, if there are unidentified events and the user clicks the user ID then the following tooltip is displayed:
<img width="948" alt="image" src="https://github.com/user-attachments/assets/969a538a-4b89-4545-99c5-6773bd726a57">

If that user ID is clicked again, then the user is navigated to the following page:
<img width="703" alt="image" src="https://github.com/user-attachments/assets/0138a628-2b80-4dac-abbb-64312c8c0946">

This seems misleading if users have specifically chosen not to identify all events and are using i.e `person_profile: identified_only`. In this circumstance the person won't have been deleted and the sharing settings won't have changed, as the person will not have been created in the first place. 

Example event (from our internal PostHog instance):
https://us.posthog.com/project/35787/events/019109ae-9162-7252-88ba-7c7159c90ec8/2024-07-31T18%3A45%3A21.637000%2B02%3A00
Example person not found:
https://us.posthog.com/project/35787/person/019109ae-449e-7948-b226-4acad36a616e

## How to reproduce

1. Navigate to activity in PostHog.
2. Locate an unidentified event.
3. Click on the user ID to display the "No profile associated with this ID" tooltip.
4. Click on the user ID again.
5. Observe that you have been navigated to the person not found page. 

Preferably if the event is intentionally unidentified, we wouldn't allow the second click. 

Related ticket:
https://posthoghelp.zendesk.com/agent/tickets/16291

**Comment by ctrl-alter-ego** [comment]
Hi @abigailbramble - just wondering if there's a use case for having a second click at all, and not just when the user is unidentified?

I'm wondering if a second click should be disabled regardless, because a person that exists will be clickable from the top of the tooltip, and it wouldn't necessarily be obvious to users that a second click has different behaviour.

**Comment by ctrl-alter-ego** [comment]
I came back to this and had another think, and the downside to removing the 'twice click' behavior is that some users may be used to it by now.

Instead, I've removed the second click action and <Link> if the person doesn't exist.
