### ISSUE TITLE
The GitLab CI installation fails + future of GitLab CI installation

### ISSUE THREAD

**Issue by nagyv** [PostHog/posthog#2412]
## Bug description

The GitLab CI based Pothog installation is failing. Please, see https://gitlab.com/gitlab-org/cluster-integration/cluster-applications/-/issues/68

Before you'd start actively fixing the issue, we are currently discussing the future of GitLab Managed Apps, and there is a high possibility that our direction will be to only provide installations of GitLab-integrated applications. You can read more about this in [our direction page](https://about.gitlab.com/direction/configure/kubernetes_management/#gitlab-managed-applications), and can follow the discussion in https://gitlab.com/gitlab-org/configure/general/-/issues/97

## How to reproduce

1. 
2. 
3. 

## Environment

- PostHog cloud or self-managed?
- PostHog version/commit

**Comment by yakkomajuri** [comment]
Gave this a 2sec look so I might be saying irrelevant stuff but this seems to be running a very old chart + PostHog version:

```
posthog	1       	Wed Nov 11 17:49:13 2020	FAILED	posthog-1.1.5	1.6.0
```

Chart is now on 1.3.15 and PostHog is on 1.16.0

**Comment by Twixes** [comment]
This is a really stale issue, but feel free to report if there is still a problem.
