### ISSUE TITLE
Add Export to CSV / XLSX to HogSQL Insights

### ISSUE THREAD

**Issue by adam-tracify** [PostHog/posthog#24182]
## Is your feature request related to a problem?

On other insight types it's possible to export to CSV / XLSX 

## Describe the solution you'd like

Add a button to SQL insight tables that allow users to export to CSV / XLSX 

## Describe alternatives you've considered

Copying from the screen is annoying. I didn't investigate if I could hook up the insight to one of your data export tools as that seems overkill for getting simple table info. 

### Debug info

```shell
Location: https://eu.posthog.com/project/6827/data-warehouse
Session: https://us.posthog.com/project/sTMFPsFhdP1Ssg/replay/019121bb-8f55-73d1-8e6e-5db07a47acc0?t=866
Admin: http://go/adminOrgEU/0188523b-f704-0000-e5f9-a04250bcc5ff (project ID 6827)
Sentry: http://go/sentryEU/6827
```

**Comment by MarconLP** [comment]
Hey @adam-tracify, that should already be possible. Could you share a link to an insight where the export option isn't available?
![2024-08-05 at 11 24 57@2x](https://github.com/user-attachments/assets/a9ec91f8-2e64-4c7d-8434-109d64f2c57b)

**Comment by adam-tracify** [comment]
Sure - here you go: https://eu.posthog.com/project/6827/insights/Fld5tSsu

**Comment by adam-tracify** [comment]
Ahh nevermind! I didn't see this in the menu item. I was confused because under other insights you have this button that is not present: 
<img width="351" alt="image" src="https://github.com/user-attachments/assets/5d6848d4-4bf6-481b-aebc-0b31785240d7">

**Comment by MarconLP** [comment]
🙌
