### ISSUE TITLE
Feature previews loading forever

### ISSUE THREAD

**Issue by niels-bosman** [PostHog/posthog#24195]
## Bug description

The feature previews panel just keeps loading.

<img width="505" alt="image" src="https://github.com/user-attachments/assets/d3e2aa66-d9ba-43ad-a95d-bde847b8011b">

### Debug info

```shell
Session: https://us.posthog.com/project/sTMFPsFhdP1Ssg/replay/0191235b-249f-7957-a221-6f18b216e0f0?t=769
Admin: http://go/adminOrgUS/018d9d77-3913-0000-92dc-5714cca1bd65 (project ID 53505)
Sentry: http://go/sentryUS/53505
```

**Comment by slshults** [comment]
This turns out to have been caused by an adblocker addon.
