### ISSUE TITLE
Feature Flag cannot recreate with the same key after deleting

### ISSUE THREAD

**Issue by GalDayan** [PostHog/posthog#2421]
## Bug description
Feature Flag cannot recreate with the same key after deleting 

Steps to reproduce: 

1. create feature flag with key `bla`
2. delete the feature flag
3. try to create again feature flag with `bla` key
4. alert will popup with This key already exists
![image](https://user-images.githubusercontent.com/24251369/99444738-4e5a4680-2925-11eb-822a-5a9397fba965.png)

## Expected behavior
New feature flag will be added

## Environment

self-hosting

**Comment by timgl** [comment]
Thanks for raising this!

Should be an easy fix:
- When we do the check to see whether a key already exists, if it does _but_ that Feature Flag has `deleted=True`, just permanently delete it instead.
