### ISSUE TITLE
StatsD causing errors on Windows 

### ISSUE THREAD

**Issue by adamb70** [PostHog/posthog#2425]
In local development StatsD is raising `OSError: [WinError 10049] The requested address is not valid in its context` when env variable `STATSD_HOST` is not set. This seems to just be a Windows issue as the error suggests, because I can't get it to happen inside Docker.

This is happening because the default empty string of `settings.STATSD_HOST` gets set as the default host of `statsd.Connection`, and the empty string is not a valid host name in Windows.

https://github.com/PostHog/posthog/blob/1357df0c137e36478be19a1b8739dcdba93d2327/posthog/settings.py#L181
https://github.com/PostHog/posthog/blob/1ec12f26e707489e77077be029ddb79ceeefd944/posthog/celery.py#L35

StatsD sets the default `host` value to `'localhost'`, and restoring this default fixes the errors. I can make a PR tomorrow, but just wanted to check on this:
https://github.com/PostHog/posthog/blob/1357df0c137e36478be19a1b8739dcdba93d2327/posthog/settings.py#L217-L219

I can change it to `if os.environ.get("STATSD_HOST", False):`, but it might make more sense as a separate env variable like `STATSD_ENABLED`. My only concern with that is it's probably a breaking change. Are there any better options?

**Comment by macobo** [comment]
Hi @adamb70, thanks for the in-depth report!

We use STATSD_HOST in 3 places in code (settings.py, celery.py and process_event.py). I believe it's safe to refactor this to `os.environ.get("STATSD_HOST")` which will return `None` by default and wrap all 3 in `if STATSD_HOST is not None` :)
