### ISSUE TITLE
Vague error with retention

### ISSUE THREAD

**Issue by jamesefhawkins** [PostHog/posthog#2428]
## Bug description

1. go to retention on our internal login
2. get this error with these settings

![Screenshot 2020-11-18 at 11 14 01](https://user-images.githubusercontent.com/47497682/99523622-3ae3c580-298f-11eb-9d6d-7beb79f5e338.png)

**Comment by adamb70** [comment]
I'm getting the same error too, this is apparently an invalid date format:
https://github.com/PostHog/posthog/blob/b0008f8e9e2760950b99e71732b92b29543999e7/posthog/utils.py#L219

I think the dash may be a typo?

**Comment by adamb70** [comment]
So it's not a typo, but apparently `strftime()` [calls the system library](https://stackoverflow.com/a/10807204/4796605), so `%-d` causes an error on Windows but is fine on Linux. Probably unrelated to the original issue in this case.

**Comment by ruslanasa** [comment]
I'm getting the same error any time I open retention tab on linux system

**Comment by EDsCODE** [comment]
#2578 updated the logic and the above works. Reopen if error persists!
