### ISSUE TITLE
Incorrect Metrics

### ISSUE THREAD

**Issue by iamnafets** [PostHog/posthog#24296]
## Bug description

We have 2 series, one is a subset of the other, so the green line should always be at or below the blue line.
![image](https://github.com/user-attachments/assets/0aafe912-c2bc-4793-b910-6f62597a2a7b)

This graph does not show that:
![image](https://github.com/user-attachments/assets/fdbca91e-a4f1-406c-8513-1f8d0ea556f1)

## How to reproduce
See Insight here: https://us.posthog.com/project/55874/insights/MSAm3lMi/edit

### Debug info

```shell
- [x] PostHog Cloud, Debug information: 
Session: https://us.posthog.com/project/sTMFPsFhdP1Ssg/replay/019137cf-e0b4-7f69-8515-1784d2c41eb6?t=203
Admin: http://go/adminOrgUS/0188c19e-3b1a-0000-6aa1-d006cbca5583 (project ID 55874)
Sentry: http://go/sentryUS/55874
- [ ] PostHog Hobby self-hosted with `docker compose`, version/commit: [please provide]
- [ ] PostHog self-hosted with Kubernetes (deprecated, see [`Sunsetting Kubernetes support`](https://posthog.com/blog/sunsetting-helm-support-posthog)), version/commit: [please provide]
```

**Comment by MarconLP** [comment]
Hey @iamnafets, the problem here is that the blue chart is only tracking `$pageview` events, while the green chart is tracking `All events`. If you configure both charts to track the same events, you'll get the expected result. Let me know if that makes sense.

**Comment by iamnafets** [comment]
Dear god that's embarrassing. Thank you and apologies for the hassle!
