### ISSUE TITLE
Add PostHog to Cloudron

### ISSUE THREAD

**Issue by timgl** [PostHog/posthog#2437]
## Is your feature request related to a problem?

I want to be able to deploy PostHog on [Cloudron](https://cloudron.io).

## Describe the solution you'd like

I spoke to their founder, this is what it would involve:

>Cloudron uses docker behind the scenes, since you already offer images there in various fashions as far as I can tell, this would not be a hard part. However, despite using docker the regular images usually need some tweaking to work, since we have put some restrictions in to ensure reproducible updates/restores and some additional security. Mainly this means that apps run on a read-only filesystem. They can request, as an addon, some writeable volume to be mounted. This brings me to the next point where there is a CloudronManifest.json which contains metadata as well as addon configs. In your case it looks like postgres and redis is required, which are available on Cloudron as well. Also depending on your support for it, Cloudron runs an LDAP server for better user-integration, if that is suitable in your case. Some more info about that is at https://docs.cloudron.io/custom-apps/manifest/

 > Finally we require end-to-end tests for all apps to ensure updates work and are reliable. Those are selenium tests we write for all apps. They look like this https://git.cloudron.io/cloudron/nextcloud-app/-/blob/master/test/test.js

**Comment by nebulade** [comment]
Thanks for creating this. We will help out here once this gets going!

**Comment by paolodamico** [comment]
I believe based on the change to rely on helm charts and consolidate providers we won't continue with this. Feel free to reopen if something changes.
