### ISSUE TITLE
How to migrate data to another database 

### ISSUE THREAD

**Issue by Doflatango** [PostHog/posthog#2438]
I want to migrate my PostHog services to another place,  it's okey to just transfer Postgresql data? or should i transfer Redis too?
I cloud't found any documentations about this.

**Comment by yakkomajuri** [comment]
Hey @Doflatango! Where do you want to transfer it to? 

Also, you don't need to transfer Redis data, that's an in-memory (non-persistent) store that we use as a task queue.

**Comment by Doflatango** [comment]
Another PostgreSQL instance.
> Hey @Doflatango! Where do you want to transfer it to?

Thanks! So, i just need to transfer PostgreSQL data to the new instance, and up a PostHog service?
> Also, you don't need to transfer Redis data, that's an in-memory (non-persistent) store that we use as a task queue.

**Comment by yakkomajuri** [comment]
Essentially yes. How are you deploying though? Directly from source?

**Comment by Doflatango** [comment]
I'm running PostHog with docker swarm for a long time, and the new PostHog service will be deploying  to a new docker swarm too.

**Comment by yakkomajuri** [comment]
Got it. Yeah I mean if you follow the same deployment approach, once you have the Postgres instance up, populating it with the data from the other instance should give you access to your data on the new PostHog deployment.

**Comment by Doflatango** [comment]
@yakkomajuri  Thank you for your help!
