### ISSUE TITLE
Create training videos to improve documentation

### ISSUE THREAD

**Issue by jamesefhawkins** [PostHog/posthog#244]
**Is your feature request related to a problem? Please describe.**
Lots of users find the Actions complicated.

Let's film a few walk through videos to help show people how this works, in addition to the written documentation, as it will take a while to improving that functionality's ease of use.

**Describe the solution you'd like**
A short video clip filmed and linked to from the PostHog wiki in the appropriate place, that explains setting up an action.

**Describe alternatives you've considered**
Keep on confusing people!

**Comment by Tannergoods** [comment]
Done - have also set up a PostHog Youtube channel to keep future tutorials (https://www.youtube.com/channel/UCn4mJ4kK5KVSvozJre645LA)
