### ISSUE TITLE
Better handling of deleted flags

### ISSUE THREAD

**Issue by jurajmajerik** [PostHog/posthog#24454]
## Is your feature request related to a problem?
We currently soft-delete feature flags by setting the `deleted` field to `true`. Such flags:
- can be looked up with an URL
- confusingly may show "Enabled" in the UI
- when requested, still show `Feature flag events` in the usage tab (even though they're not billed)

## Describe the solution you'd like
- some banners/tooltips would solve this easily

### Debug info

```shell
- [ ] PostHog Cloud, Debug information: [please copy/paste from https://us.posthog.com/settings/project-details#variables]
- [ ] PostHog Hobby self-hosted with `docker compose`, version/commit: [please provide]
- [ ] PostHog self-hosted with Kubernetes (deprecated, see [`Sunsetting Kubernetes support`](https://posthog.com/blog/sunsetting-helm-support-posthog)), version/commit: [please provide]
```

**Comment by havenbarnes** [comment]
This issue is mostly addressed by https://github.com/PostHog/posthog/pull/26083, but I plan to post a follow-up PR to address the `deleted flags still show Feature flag events in the usage tab (even though they're not billed)` issue today
