### ISSUE TITLE
Editing Plugins in the App

### ISSUE THREAD

**Issue by mariusandra** [PostHog/posthog#2447]
## Is your feature request related to a problem?

If I want to create or test a simple plugin that just changes a few properties, it's a hassle to publish code on github or npm.

## Describe the solution you'd like

I'd like to click "new plugin" and type in a bunch of JavaScript. Similar to how rudderstack does it:

<img width="1439" alt="Screenshot 2020-11-19 at 11 00 56" src="https://user-images.githubusercontent.com/53387/99783732-19afe000-2b1b-11eb-8317-e8fb29e54564.png">

Or Segment:

![image](https://user-images.githubusercontent.com/53387/99783926-5da2e500-2b1b-11eb-8b15-f0c83056a5e0.png)

![image](https://segment.com/docs/connections/functions/images/editor-test.gif)

## Describe alternatives you've considered

Long release cycle via Github or installing posthog locally and running local plugins.

## Additional context

- This is not hard to achieve. Plugins require one `index.js` to work, which we store in a zip file in postgresql. We can expose some editing functions via the API and make an interface to edit this file, and perhaps some others.
- I'd prohibit editing plugins installed via the repository. Otherwise we'll end up with a wordpress style situation, where once you edit a plugin, you can never update it again since any update would overwrite your changes.

**Comment by mariusandra** [comment]
This is done in https://github.com/PostHog/posthog/pull/2743

![image](https://user-images.githubusercontent.com/53387/101931668-081d9d80-3bda-11eb-809d-7103a9d84926.png)

There's still a lot we can add (in-editor tests, code completion, etc), but seems solid enough for now. Maybe some "funky chicken" placeholder texts and other documentation could be updated still.

**Comment by Twixes** [comment]
The essential functionality is in. For enhancements let's create separate issues, meanwhile I'll close this one.
