### ISSUE TITLE
fetch() broken on August 19: TypeError: failed to execute 'fetch' on 'window': …with a request object that has already been used

### ISSUE THREAD

**Issue by Arsenalist** [PostHog/posthog#24471]
My NextJS app completely stopped functioning as all POST calls using React Toolkit/Query resulted in this error:

`TypeError: failed to execute 'fetch' on 'window': …with a request object that has already been used`

This happened without my introducing any change whatsoever. After 4 hours of debugging and isolating things, I finally took out PostHog and it all started working.

I'm not sure what change was pushed by the PostHog team on August 19, but it had a pretty big bug in it. 

That's pretty much all I can report.  I'm using the JavaScript/React Web SDK.  This only affected React Toolkit (not Axios calls FWIW).
```

**Comment by BharatNischal** [comment]
I am also experiencing same problem after my chrome update

**Comment by thomasgrastein** [comment]
Bumping as we are experiencing the same issue. Our whole admin interface went down and so far the solution is to remove the posthog script.

**Comment by pauldambra** [comment]
Oh no! So sorry everyone

revert here: https://github.com/PostHog/posthog-js/pull/1371

Will merge ASAP and update here when released (should be minutes)

**Comment by pauldambra** [comment]
That's released in posthog-js 1.157.1

I won't close this until i've seen confirmation that resolves the issue for folks

Next job is to figure out how to write a test that would have caught this!

**Comment by AkashHC13** [comment]
@pauldambra How would this affect the older versions of SDK as well?

**Comment by pauldambra** [comment]
@AkashHC13 we lazily load the recorder.js and always load the latest, that's normally fine since it means we can fix things and we're very careful to avoid breaking changes - but in this case the unintended bug was hidden in a fix for a different issue. 

I definitely want to figure out in detail what happened here so I can add a test to prevent a similar change in future!

**Comment by thomasgrastein** [comment]
I've just tried to re-enable and the issue started reoccuring. But this might be some caching on our end, so I'll report back later.

**Comment by AkashHC13** [comment]
@pauldambra Thanks for your answer. How can we avoid this happening in the future from our end, can we have some kind of failsafe mechanism? 
We would like to have stable builds, if something breaks all of a sudden, it's not going to work for us.

**Comment by iamdreo** [comment]
Hi @pauldambra will pre bundling posthog as described here have prevented the problem from this morning https://posthog.com/docs/libraries/js ? as described by @AkashHC13 [here](https://github.com/PostHog/posthog/issues/24471#issuecomment-2298288370)

**Comment by thomasgrastein** [comment]
Still getting version 1.156.1 of posthog-js. I'm guessing it's due to this pipeline not completing: https://github.com/PostHog/posthog/pull/24472

**Comment by pauldambra** [comment]
dangnammit! thanks @thomasgrastein I'll watch that like a hawk and get it through

**Comment by pauldambra** [comment]
@iamdreo @AkashHC13 

Yep if you're using NPM then you can follow the instructions here https://posthog.com/docs/libraries/js#advanced-option---bundle-all-required-extensions

We don't have support for loading a fixed version of posthog via the HTML snippet

**Comment by iamdreo** [comment]
Thank you @pauldambra will use pre-bundling.. are there any caveats to using it like increasing time our application loads and all?

**Comment by pauldambra** [comment]
yep, that's exactly the trade-off. 

in normal use we delay loading as long as possible so that if you're not using a feature you don't stand the cost. in this case it'll depend on how well you bundler can tree-shake usage of posthog, 

we recently added [web vitals autocapture](https://us.posthog.com/settings/project#web-vitals-autocapture), so you could use that to measure it and see impact in prod

**Comment by medicmilos** [comment]
I had the same problem and was able to solve it by following docs -> [bundle all required extensions](https://posthog.com/docs/libraries/js#advanced-option---bundle-all-rekuired-extensions) and updating posthog-js to the latest version.

**Comment by thomasgrastein** [comment]
We're getting the new version now and all seems to be working again!

**Comment by pauldambra** [comment]
Thanks for confirming @thomasgrastein 

And again sorry for the impact here folks...

**Comment by pauldambra** [comment]
For anyone following along I'm working towards our post mortem

The changes in https://github.com/PostHog/posthog-js/pull/1395 mean our CI would have caught this

**Comment by pauldambra** [comment]
i'll add more detail here once the post mortem is finished - it's taking longer than usual since the impact was so severe for folks experiencing the bug I want to be sure I'm not missing a trick
