### ISSUE TITLE
`Window became hidden` and `Window became visible` are not filtered out when checking `Only events matching filters`

### ISSUE THREAD

**Issue by marandaneto** [PostHog/posthog#24477]
## Bug description

If you click on the inspector and check the checkbox "Only events matching filters"

Window became hidden and Window became visible are not filtered out

## How to reproduce

1. Filter recordings by an event or action
2. Click on Only events matching filters
3. Window became hidden and Window became visible events are still listed (if they happened in that recording)

### Debug info

```shell
- [ ] PostHog Cloud, Debug information: [please copy/paste from https://us.posthog.com/settings/project-details#variables or https://eu.posthog.com/settings/project-details#variables]
- [ ] PostHog Hobby self-hosted with `docker compose`, version/commit: [please provide]
- [ ] PostHog self-hosted with Kubernetes (deprecated, see [`Sunsetting Kubernetes support`](https://posthog.com/blog/sunsetting-helm-support-posthog)), version/commit: [please provide]
```

**Comment by pauldambra** [comment]
closed by https://github.com/PostHog/posthog/pull/24488
