### ISSUE TITLE
posthog-js `sanitize_properties` should also apply to `$set_once` properties

### ISSUE THREAD

**Issue by thmsobrmlr** [PostHog/posthog#24498]
posthog-js `sanitize_properties` should also apply to `$set_once` properties.

@MarconLP seems to have dug into this already (see related tickets):
> seems like the sanitize function is only running for supplied properties ([github link](https://github.com/PostHog/posthog-js/blob/017d7652c60048fba22bf297b66aeee818ed2290/src/posthog-core.ts#L961-L964)), but it's ignoring initial set_once properties ([github link](https://github.com/PostHog/posthog-js/blob/017d7652c60048fba22bf297b66aeee818ed2290/src/posthog-core.ts#L972-L982))

Related tickets:
https://posthoghelp.zendesk.com/agent/tickets/16628
https://posthoghelp.zendesk.com/agent/tickets/16580

**Comment by alecmocatta** [comment]
sort of fixed by https://github.com/PostHog/posthog-js/pull/1462
