### ISSUE TITLE
Bug Report: Compare label should have a space in the tooltip

### ISSUE THREAD

**Issue by skoob13** [PostHog/posthog#24509]
## Bug description

The "Previous" and "Current" labels should have a space after a breakdown text in the tooltip:
<img width="217" alt="Screenshot 2024-08-21 at 16 06 01" src="https://github.com/user-attachments/assets/d779f315-f4bb-43b5-ac91-b456454728aa">

## How to reproduce

1. Create a new insight
2. Add a breakdown
3. Compare with a previous period
4. Hover on chart to see the tooltip

**Comment by Itsindigo** [comment]
Hey @skoob13, opened a PR for this :)
