### ISSUE TITLE
web vitals improvements

### ISSUE THREAD

**Issue by pauldambra** [PostHog/posthog#24597]
### Feature request

feedback from @Lior539 

> To keep costs in control it would be great if:
I could set a sampling % e.g. only collect for 10% of users
I could set which metrics I want to capture
e.g. Im only interested in INP. But if enabling autocapture captures for all 6 and each one is captured separately in a different event, I end up capturing 6x more events than I need to

we wait for a little while so if a page emits 6 web vitals metrics we _might_ only capture one event
but since the time until metrics are available varies the best we can say is 1 - 6 events per pageview

on posthog this is working out as around 0.2 events per pageview - mostly because we have client side navigation

but we can definitely

- [x] ~~add sampling it fits really well for something super aggregate like this~~
- [x] choose which metrics to capture - this makes UI harder since we can't guarantee presence but since it's an active choice that should be self-explaining
- [x] ~~choose which URLs to enable capture on (this comes up in replay a lot so it would be interesting to see how it works here)~~

**Comment by Lior539** [comment]
@pauldambra some more feedback:

For INP, we should log the following event properties, as it's helpful for debugging it:

- navigationType
- interactionTime
- interactionType
- inputDelay
- processingDuration
- presentationDelay 

If its helpful, heres how I do it in my personal project. Note that you need the `web-vitals/attribution` dependency:
```
import { onINP } from 'web-vitals/attribution';


    onINP((metric) => {
      posthog.capture('INP', {
        // ... other metris 
        navigationType: metric.navigationType,
        interactionTime: metric.attribution.interactionTime,
        interactionType: metric.attribution.interactionType,
        interactionTarget: metric.attribution.interactionTarget,
        inputDelay: metric.attribution.inputDelay,
        processingDuration: metric.attribution.processingDuration,
        presentationDelay: metric.attribution.presentationDelay,
      });
    });
```

**Comment by pauldambra** [comment]
the more i think about adding sampling to just one thing, the more I think "why not pageleave or autocapture or...." and actually I think the right solution is either to make events cheaper or to add global sampling. 

it makes sense to be separate for replay since you have to sample at the session not event level for that to work, so i'm going to punt the sampling for now here

**Comment by pauldambra** [comment]
i'm going to punt on the URL choice too, since that feels like it should be global instead of duplicated in every extension
