### ISSUE TITLE
Bug: custom name for a total value bar chart appears twice

### ISSUE THREAD

**Issue by abigailbramble** [PostHog/posthog#24699]
## Bug description

If I create a simple insight with just i.e. all pageview events, and select total value bar chart:
<img width="244" alt="image" src="https://github.com/user-attachments/assets/c16dd970-f56f-4a7d-8e1e-b0fc59632ec0">

and rename the series to something custom:

<img width="519" alt="image" src="https://github.com/user-attachments/assets/0ef50497-6164-4c36-bf91-b6c8b40700f3">

the custom name is displayed twice

<img width="1625" alt="image" src="https://github.com/user-attachments/assets/4c7edebf-b431-4f3c-be0f-312650b222da">

## Additional context
https://posthoghelp.zendesk.com/agent/tickets/17437

**Comment by ghoti143** [comment]
Howdy 👋.  I just opened a PR for this issue.  https://github.com/PostHog/posthog/pull/24729

Hope it helps!
