### ISSUE TITLE
Funnel that once worked does not load anymore

### ISSUE THREAD

**Issue by mauricedoepke** [PostHog/posthog#24697]
## Bug description

We have a funnel in the cloud version of PostHog that is unmodified for a year. For some time (at least a couple of days) it does not work anymore. Data ist just not loading. The funnel URL is:
https://eu.posthog.com/project/7119/insights/n9JVItMf

As seen on the Screenshot, this loading just never finishes. We are ingesting a bit more than 1.1 - 1.6 Million events a month so our data is not that large. And only a fraction of events are relevant for this funnel. Also the funnel is limited to the last 14 days as seen on the screenshot. So even without propper indices, posthog needs to crunch mayb 700k events for it.

<img width="755" alt="Screenshot 2024-08-30 at 12 35 17" src="https://github.com/user-attachments/assets/cd6be37e-faec-43bc-8e52-3a8cd67931eb">

When we tried to activate 10% sampling which imo should not be neccessary, this screen came up:
<img width="706" alt="Screenshot 2024-08-30 at 11 43 38" src="https://github.com/user-attachments/assets/47f9d996-6a6f-45ce-87e7-f7252f982152">

This seems to indicate that for some reason posthog is only processing data in the bytes/s or at max kb/s range which seems super slow to me.

We also tried to duplicate the funnel in the hop that the current one is maybe stuck in a bad state. That did not help either.

### Debug info

```shell
Session: https://us.posthog.com/project/sTMFPsFhdP1Ssg/replay/0191a2a6-2347-7891-861e-f8e82964d03d?t=3164
Admin: http://go/adminOrgEU/0189681a-56f9-0000-20df-8cbd7d133820 (project ID 7119)
Sentry: http://go/sentryEU/7119
```

**Comment by MarconLP** [comment]
Unfortunately there is a known issue for funnels with many steps. We're actively working on a fix and you can follow along here: [PostHog/posthog#22999](https://github.com/PostHog/posthog/issues/22999).
 
As a workaround you can decrease the number of steps in the funnel. 
 
Really sorry about this annoyance. Let me know if there's anything else.
