### ISSUE TITLE
Bug: Filtering by internal users cases an error in insights for certain person properties setting

### ISSUE THREAD

**Issue by abigailbramble** [PostHog/posthog#24708]
## Bug description

If I create a simple insight, not filtering out internal and test users, everything works great:
![image](https://github.com/user-attachments/assets/3664877d-54ec-4da0-8e06-bfe9ed1aa899)

This insight is in an internal project here: https://us.posthog.com/project/35787/insights/htRK1gca/edit

When I have my `person properties mode` settings to `use person properties as of running the query` and start filtering out internal test users, it gives me this error:
![image](https://github.com/user-attachments/assets/fbfce156-7f8f-4a76-ba6b-6d5fbd427f83)

## Additional context
It's also affecting a user with a slightly different error again here: https://posthoghelp.zendesk.com/agent/tickets/16910

**Comment by abigailbramble** [comment]
+1 https://posthoghelp.zendesk.com/agent/tickets/17559 (moved to PostHog: https://us.posthog.com/project/2/support/tickets/19437)

**Comment by abigailbramble** [comment]
+1 https://posthoghelp.zendesk.com/agent/tickets/17562 (moved to PostHog: https://us.posthog.com/project/2/support/tickets/20011)

**Comment by abigailbramble** [comment]
+1 https://posthoghelp.zendesk.com/agent/tickets/17566 (moved to PostHog: https://us.posthog.com/project/2/support/tickets/20013)

**Comment by isak102** [comment]
This started happening to me today aswell

**Comment by abigailbramble** [comment]
We believe this is related to a change which is being reverted here: https://github.com/PostHog/posthog/pull/24709

**Comment by abigailbramble** [comment]
+1 https://posthoghelp.zendesk.com/agent/tickets/17545 (moved to PostHog: https://us.posthog.com/project/2/support/tickets/20005)
+1 https://posthoghelp.zendesk.com/agent/tickets/17548 (moved to PostHog: https://us.posthog.com/project/2/support/tickets/20006)
+1 https://posthoghelp.zendesk.com/agent/tickets/17551 (moved to PostHog: https://us.posthog.com/project/2/support/tickets/19884)
+1 https://posthoghelp.zendesk.com/agent/tickets/17555 (moved to PostHog: https://us.posthog.com/project/2/support/tickets/20007)
+1 https://posthoghelp.zendesk.com/agent/tickets/17556 (moved to PostHog: https://us.posthog.com/project/2/support/tickets/19436)
+1 https://posthoghelp.zendesk.com/agent/tickets/17557 (moved to PostHog: https://us.posthog.com/project/2/support/tickets/20008)
+1 https://posthoghelp.zendesk.com/agent/tickets/17558 (moved to PostHog: https://us.posthog.com/project/2/support/tickets/20009)
+1 https://posthoghelp.zendesk.com/agent/tickets/17560 (moved to PostHog: https://us.posthog.com/project/2/support/tickets/19438)
+1 https://posthoghelp.zendesk.com/agent/tickets/17561 (moved to PostHog: https://us.posthog.com/project/2/support/tickets/20010)
+1 https://posthoghelp.zendesk.com/agent/tickets/17565 (moved to PostHog: https://us.posthog.com/project/2/support/tickets/20012)
+1 https://posthoghelp.zendesk.com/agent/tickets/17567 (moved to PostHog: https://us.posthog.com/project/2/support/tickets/20014)
+1 https://posthoghelp.zendesk.com/agent/tickets/17569 (moved to PostHog: https://us.posthog.com/project/2/support/tickets/23445)
+1 https://posthoghelp.zendesk.com/agent/tickets/17571 (moved to PostHog: https://us.posthog.com/project/2/support/tickets/20016)
+1 https://posthoghelp.zendesk.com/agent/tickets/17572 (moved to PostHog: https://us.posthog.com/project/2/support/tickets/20017)
+1 https://posthoghelp.zendesk.com/agent/tickets/17574 (moved to PostHog: https://us.posthog.com/project/2/support/tickets/20018)
+1 https://posthoghelp.zendesk.com/agent/tickets/17576 (moved to PostHog: https://us.posthog.com/project/2/support/tickets/20019)
