### ISSUE TITLE
Test data for development

### ISSUE THREAD

**Issue by a-rodin1** [PostHog/posthog#24743]
Hi there!

I want to try out PostHog features locally. I followed steps from [the handbook](https://posthog.com/handbook/engineering/developing-locally), but the databases are empty and there is nothing to see. Is there a way to fill the databases by test data?

**Comment by Twixes** [comment]
Hi, yes! The `DEBUG=1 ./manage.py generate_demo_data` command is a bit buried in that handbook page, but it's there. That's the way to get test data.
