### ISSUE TITLE
Conditional logic for surveys not displaying

### ISSUE THREAD

**Issue by tonyr-ux** [PostHog/posthog#24786]
## Bug description

Options for questions depending on answer are not appearing
Google Chrome Version 127.0.6533.120 
Mac OS 13.0.1 
<img width="1392" alt="Screenshot 2024-09-04 at 16 00 36" src="https://github.com/user-attachments/assets/31e8786f-2e4e-46d2-bb27-8f421784c661">

## How to reproduce

1. Create a survey using a Likert Scale
2. Create questions for positive and negative responses
3.  On Q1 choose "Specific question based on answer"
4. Nothing appears

### Debug info

```shell
- [ ] PostHog Cloud, Debug information: [please copy/paste from https://us.posthog.com/settings/project-details#variables or https://eu.posthog.com/settings/project-details#variables]
- [ ] PostHog Hobby self-hosted with `docker compose`, version/commit: [please provide]
- [ ] PostHog self-hosted with Kubernetes (deprecated, see [`Sunsetting Kubernetes support`](https://posthog.com/blog/sunsetting-helm-support-posthog)), version/commit: [please provide]
```

**Comment by dmarticus** [comment]
this should be fixed with https://github.com/PostHog/posthog-js/pull/1424
