### ISSUE TITLE
push in JS Snippet list of methods causes issues when trying to call methods prior to array.js being fully loading

### ISSUE THREAD

**Issue by twiggy** [PostHog/posthog#24797]
https://github.com/PostHog/posthog/blame/989dbd9bd5c5c8f0a2c8b2af22134b4fe7fb117b/frontend/src/lib/components/JSSnippet.tsx#L14

```
for (const key of Object.getOwnPropertyNames(posthogPrototype)) {
        if (
            typeof posthogPrototype[key] === 'function' &&
            !key.startsWith('_') &&
            !['constructor', 'toString'].includes(key)
        ) {
            methods.push(key)
        }
```

End up with a snippet like 

```!function(t,e){var o,n,p,r;e.__SV||(window.posthog=e,e._i=[],e.init=function(i,s,a){function g(t,e){var o=e.split(".");2==o.length&&(t=t[o[0]],e=o[1]),t[e]=function(){t.push([e].concat(Array.prototype.slice.call(arguments,0)));}}(p=t.createElement("script")).type="text/javascript",p.async=!0,p.src=s.api_host.replace(".i.posthog.com","-assets.i.posthog.com")+"/static/array.js",(r=t.getElementsByTagName("script")[0]).parentNode.insertBefore(p,r);var u=e;for(void 0!==a?u=e[a]=[]:a="posthog",u.people=u.people||[],u.toString=function(t){var e="posthog";return"posthog"!==a&&(e+="."+a),t||(e+=" (stub)"),e},u.people.toString=function(){return u.toString(1)+".people (stub)"},o="init push capture register register_once register_for_session unregister unregister_for_session getFeatureFlag getFeatureFlagPayload isFeatureEnabled reloadFeatureFlags updateEarlyAccessFeatureEnrollment getEarlyAccessFeatures on onFeatureFlags onSessionId getSurveys getActiveMatchingSurveys renderSurvey canRenderSurvey getNextSurveyStep identify setPersonProperties group resetGroups setPersonPropertiesForFlags resetPersonPropertiesForFlags setGroupPropertiesForFlags resetGroupPropertiesForFlags reset get_distinct_id getGroups get_session_id get_session_replay_url alias set_config startSessionRecording stopSessionRecording sessionRecordingStarted captureException loadToolbar get_property getSessionProperty createPersonProfile opt_in_capturing opt_out_capturing has_opted_in_capturing has_opted_out_capturing clear_opt_in_out_capturing debug".split(" "),n=0;n<o.length;n++)g(u,o[n]);e._i.push([i,s,a])},e.__SV=1)}(document,window.posthog||[]);```

I think the ```push``` method should be excluded along with ```constructor``` and ```toString```. It seems to cause a Maximum call stack size exceeded bug when calling methods like posthog.capture or posthog.identify right after calling posthog.init. Workaround is to use an onload style event.

Please see my comments on #21215  as I thought they where maybe related, but researching how the snippet is generated made me realize they are probably not. Breaks it down a lot more.

Thanks!

**Comment by pauldambra** [comment]
thanks for taking the time to investigate @twiggy 💖
