### ISSUE TITLE
Slack link no longer valid.

### ISSUE THREAD

**Issue by alairock** [PostHog/posthog#248]
**Describe the bug**
In the wiki, the slack invitation link doesn't seem to be working any longer. Would like to join community. Thanks!

**Comment by jamesefhawkins** [comment]
Whoops- gremlins must have downgraded the account used to make the invite.

Could you try [this invite link](https://join.slack.com/t/posthogusers/shared_invite/enQtOTY0MzU5NjAwMDY3LTc2MWQ0OTZlNjhkODk3ZDI3NDVjMDE1YjgxY2I4ZjI4MzJhZmVmNjJkN2NmMGJmMzc2N2U3Yjc3ZjI5NGFlZDQ)?  Readme updated too.

**Comment by jamesefhawkins** [comment]
it looks like you made it into Slack :) I'll close this for now. We'll get to your q first thing in the morning!
