### ISSUE TITLE
Session Replay Overview Tab

### ISSUE THREAD

**Issue by pauldambra** [PostHog/posthog#24849]
### Feature request

When viewing a recording you are often thinking about the session, when you open the inspector we show you events which means you can get all the information you need (so long as you capture it) but you have to know it is there. 

And it means you have to calculate some things yourself... e.g. did property X change value during this session

---

Let's add an overview tab to the inspector panel

This can show things like

* properties on every event
* properties that change during the session
* "Session" properties like referrer, device, activity (can draw on the session table here too)
* ??? calculated web vitals score ??
* other magical things?

**Comment by ricky11** [comment]
Display Referrer for each session recording without diving in to network requests would be helpfull.

**Comment by ricky11** [comment]
Is the Referrer now easily visible?

**Comment by pauldambra** [comment]
Hey @ricky11 

It's still only in the event data... we've closed this in favour of https://github.com/PostHog/posthog/issues/26098 which includes changes like this one...

Just helps us keep clear what's happening 💖
