### ISSUE TITLE
Not able to track events on locally hosted docker app

### ISSUE THREAD

**Issue by Ignatius-Nobel** [PostHog/posthog#24852]
### Bug Description

I was lately trying to track all the events from my locally hosted docker app via the web snippets (HTML) for the development purpose. But, unfortunately no events were being tracked on the posthog dashboard. Is there anything that I must add or change other than pasting the web snippet into my html file. My app is build using the Django framework. Also, I have removed the local host from the filter out users in the settings.

**Comment by pauldambra** [comment]
Hey @Ignatius-Nobel can you clarify what your setup is? 

Are you trying to track a locally running django app to posthog cloud or...?

Do you see any network or console logs?

**Comment by Ignatius-Nobel** [comment]
I was trying to track a locally running django app to posthog cloud. I use
docker desktop to run the app in the local host. I don't see anything
particular in the logs.

**Comment by pauldambra** [comment]
That should work... You can launch the toolbar from posthog and use its debug view to see if any events are being triggered. 
Or attach posthog to the window and in the browser console call `posthog.debug(true)` and it will print every message it sends to the console.

Could you have an adblocker or something getting in the way?

**Comment by Ignatius-Nobel** [comment]
Ok, I'll check it out.

**Comment by Ignatius-Nobel** [comment]
Got it! The ad blocker was the issue. I turned them off, and the events
were getting collected properly. Thank you for the help 😊.
