### ISSUE TITLE
Dashboard not respecting breakdown limit counts

### ISSUE THREAD

**Issue by aspicer** [PostHog/posthog#24894]
https://posthoghelp.zendesk.com/agent/tickets/17996

Dashboard is only showing (default) 25 items even though breakdown limit is set to 1000.

The query that is being generated from the dashboard doesn't have a breakdown limit set.

**Comment by abhi12299** [comment]
@aspicer this is intentional: https://github.com/PostHog/posthog/blob/cced38ccd1d0063d9f086d46480ec105d21cde04/posthog/hogql_queries/insights/trends/trends_query_runner.py#L981-L990

If this behaviour needs to be reverted, I can raise a PR for the same.
