### ISSUE TITLE
WIP Homepage flow is unintuitive

### ISSUE THREAD

**Issue by jamesefhawkins** [PostHog/posthog#249]
# Challenge

* Currently the homepage's main CTA at the top is 'Deploy to Heroku'.
  * This is certainly the quickest way to use PostHog in production. However, this badly serves several groups of users, as it is narrower than what we can offer:
    * Enterprise customers will be taken to the community version of the software. It won't have teh permissions etc needed for them to go live.
    * Developers may want to choose how they deploy - this ignores the options like Docker or compiling it from code.
    * Some people probably want a demo.

At the bottom of the homepage we have 'start now', which takes people to the hosted version.

* We should give more choice at this stage.

# Solution

* We could film a demo of the platform and send it to interested people.
* We could follow a two step approach. If someone want to 'Start Now', we could send them to:
  * Self-Hosted
  * Hosted

**Comment by timgl** [comment]
Closing for now as we've done a new website, can re-open in that repo if necessary
