### ISSUE TITLE
Updating person properties doesn't work on EE

### ISSUE THREAD

**Issue by yakkomajuri** [PostHog/posthog#2492]
## Bug description

*Please describe.*  
*If this affects the front-end, screenshots would be of great help.*  

On the person page, I can't update person properties. The frontend tells me it worked, but it doesn't persist. 

It works on Postgres, so I'm assuming the patch request for person props just isn't implemented in ee.

## Expected behavior

Updating properties should work.

## How to reproduce

1. Visit a person page (on ee)
2. Update a property
3. Refresh the page

## Environment

- PostHog cloud or self-managed?
- PostHog version/commit

**Comment by paolodamico** [comment]
Hey @yakkomajuri, could you share a screenshot here? Trying to determine if you're on the legacy version or the new one (`persons-2353` feature flag)

**Comment by EDsCODE** [comment]
Going to close this as I tested this in dev EE and on app and it works
