### ISSUE TITLE
Show when team members last signed in

### ISSUE THREAD

**Issue by corywatilo** [PostHog/posthog#24969]
## Is your feature request related to a problem?

I'd like to be able to see the last time a team member signed in. Currently it only shows when they joined, which is great, but less useful IMO than seeing if they're still active. (This is useful for auditing contractors.)

<img width="413" alt="image" src="https://github.com/user-attachments/assets/dc003308-f85d-44bf-b731-c4c525a565cd">

**Comment by Shree7676** [comment]
I would like to work on this issue
