### ISSUE TITLE
Copy [feature flag/action/cohort] to other project

### ISSUE THREAD

**Issue by timgl** [PostHog/posthog#2497]
## Is your feature request related to a problem?

I'd like to be able to copy certain things to another project if I have multiple projects set up.

## Describe the solution you'd like

Add another icon in the 'Actions' column of feature flags for example that indicates 'copy'. Make a relatively generic component (like DeleteWithUndo) that will open a popup that allows the user to select a project, and then allows it to copy that object there.

You'll probably need #2485 merged in.

**Comment by weyert** [comment]
Still interested
