### ISSUE TITLE
Clean install on NGINX + SSL causes issues with serving CSS files (JS works)

### ISSUE THREAD

**Issue by pavitrakumar78** [PostHog/posthog#24981]
## Bug description

I'm setting up a new posthog on a new subdomain server (service.mainserver.com) with the latest docker images (as of the date of this post) and after everything is loaded, CSS alone does not load with the error "BLOCKED BY ORB" in dev console. 

Are CSS and JS exposed/served differently in the containers? because JS works just fine.

Here's my NGINX conf based on instructions from https://posthog.com/handbook/engineering/setup-ssl-locally:
Note: I've removed all instances of Caddy from the docker files and the localhost port is mapped: 8042:8000 (default: 8000:8000)

```
upstream backend {
		server 0.0.0.0:8042;
}

server {
        server_name services.mainserver.com;
        rewrite ^(.*) https://services.mainserver.com$1 permanent;
}


server {
        # listen to the standard http port 80
        #listen 80;
        listen 443 ssl;

        server_name services.mainserver.com;

        location = /favicon.ico { access_log off; log_not_found off; }
        location = /robots.txt { return 200 "User-agent: *\nDisallow: /\n"; }
        location / {
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header Host $http_host;
                proxy_redirect off;
                proxy_set_header X-Forwarded-Proto $scheme;
                proxy_pass http://backend;
        }

        location /static/ {
                proxy_pass http://0.0.0.0:8234/static/;
        }

        ssl_certificate /etc/ssl/certs/cloudflare_certificate.pem;
        ssl_certificate_key /etc/ssl/certs/cloudflare_certificate_key.pem;

        error_log /var/log/nginx/error.log debug;
        access_log /var/log/nginx/access.log;
}

```

## How to reproduce

1. Run /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/posthog/posthog/HEAD/bin/deploy-hobby)" to get docker files
2. Remove all instances  of Caddy and re-build docker 
3. Setup nginx as per conf above
4. Set `IS_BEHIND_PROXY` True in dockerfile
5. Launch services.mainserver.com

I'm able to select the launch mode, see all the preflight checks in next page, but it's all in plain HTML. How is it that JS is served correctly but CSS is not? All of this works well if I disable SSL - i.e I see the webpage with CSS rendered properly.

### Debug info

```shell
- [x] PostHog Hobby self-hosted with `docker compose`, version/commit: e46f90dd04
```

**Comment by pauldambra** [comment]
Hey, the "Set up SSL locally" is engineering documentation for developing locally, it's not intended to be used for self-hosted. 

Why have you changed anything? Did it work with the basic install? You should stick to just the instructions here https://posthog.com/docs/self-host

**Comment by pavitrakumar78** [comment]
> Why have you changed anything? Did it work with the basic install? You should stick to just the instructions here

I am following the basic instructions. The only change is my port number (8000 -> 8042). NGINX config is also the same (with or without the extra /static block)

**Comment by pauldambra** [comment]
> Here's my NGINX conf based on instructions from [posthog.com/handbook/engineering/setup-ssl-locally](https://posthog.com/handbook/engineering/setup-ssl-locally):

The basic instructions don't have any of the extra steps you listed :)

so all of this

> Remove all instances of Caddy and re-build docker
> Setup nginx as per conf above
> Set IS_BEHIND_PROXY True in dockerfile
> Launch services.mainserver.com

does it work if you just set it up exactly as here [posthog.com/docs/self-host](https://posthog.com/docs/self-host)

**Comment by pavitrakumar78** [comment]
> does it work if you just set it up exactly as here [posthog.com/docs/self-host](https://posthog.com/docs/self-host)

Just cleared all containers, volumes, images and did exactly as in the post:

![image](https://github.com/user-attachments/assets/46ffbf2a-6115-4094-a8cc-440cfafa0d8c)

Completed 100% without any issues

still, the page can't load CSS alone:

![image](https://github.com/user-attachments/assets/f1ae614a-b35b-4c93-b364-b7a8024e3bb1)

**Comment by pauldambra** [comment]
what location are you being 301d to?

**Comment by pauldambra** [comment]
I upgrade my self-hosted instance Friday and it works fine on a hetzner linux vm

**Comment by pauldambra** [comment]
actually i can see your instance URL in the screenshot

i get css

<img width="1375" alt="Screenshot 2024-09-15 at 20 17 32" src="https://github.com/user-attachments/assets/04d5d75e-f50c-4e44-a69c-4b58a14e9e23">

**Comment by pavitrakumar78** [comment]
> i get css

Maybe it's getting from your cache? 

and can you please delete the screenshot with the URL? I'd prefer to not have it exposed.

**Comment by pavitrakumar78** [comment]
I'm not sure why, but when I use a VPN, it works and CSS renders... 
any reason why just CSS alone would not work when accessed from a normal IP? (never had this issue before with anything I've deployed)

**Comment by pauldambra** [comment]
> Maybe it's getting from your cache?
i checked in incognito

> any reason why just CSS alone would not work when accessed from a normal IP?
none... as I say my self-host instance on hetzner is up-to-date and doesn't have the issue. but since a vpn connection clears the issue it must be a network level thing not a posthog level thing, no?

**Comment by pavitrakumar78** [comment]
ok, thank you
I will check my network settings.
