### ISSUE TITLE
high cpu usage on new created posthog service

### ISSUE THREAD

**Issue by joebnb** [PostHog/posthog#24996]
<img width="709" alt="image" src="https://github.com/user-attachments/assets/7151d6be-bff0-4ec7-ac47-8a20a2139971">
 

<img width="863" alt="image" src="https://github.com/user-attachments/assets/c0fdffff-21f0-436d-a8f4-38b38baf8b06">

in 2u8g virtual Machine, a self hosted posthog server just created consume too much resource,is this normal?

<img width="905" alt="image" src="https://github.com/user-attachments/assets/23a7c835-f83b-43ef-b06c-086668fee0dd">

seems everything are worksfine,but it's seems too heavily

**Comment by joebnb** [comment]
> I'm guessing 2u8g means 2 CPUs and 8GB RAM?
> 
> PostHog is a CPU heavy service - there are a lot of containers running, so I think this is pretty normal.
> 
> From my own experience running on Hetzner - shared CPU needed a higher CPU count than dedicated CPU (in case you are able to choose between those)

it't too heavy,if i set up a standalone elastic search and clickhouse, it wont take so much cpu resource,wish posthog do some  works for this(it's consume 20x resource than matomo，even thought that architecture are quite different with posthog)

**Comment by pauldambra** [comment]
i run it on a 2 (dedicated) CPU 8GB box at hetzner and it runs fine, but it's a stack of applications and can be CPU hungry depending on load
