### ISSUE TITLE
Allow to add feature flags when no events have been saved

### ISSUE THREAD

**Issue by weyert** [PostHog/posthog#2511]
## Bug description

*Please describe.*  
*If this affects the front-end, screenshots would be of great help.*  

## Expected behavior
Currently, you are getting the code snippet page when you haven't added instead I would like to be able to define feature flags even when no events have been ingested yet. See screenshot.

![CleanShot 2020-11-25 at 12 01 14](https://user-images.githubusercontent.com/7049/100225523-40548900-2f16-11eb-9797-7b073cc745d6.png)

## How to reproduce

1. Create New Project
2. Go to Feature Flags
3. Attempt to add a new feature flag
4. Notice you can't add flag due to visual element shown (see above screenshot)

## Environment

- PostHog cloud
- PostHog version: latest version in cloud

## Additional context
I would like to prepare a deployment/release but want to prepare the project by adding the needed feature flags

**Comment by Twixes** [comment]
Fixed.
