### ISSUE TITLE
Allow to open side navigation in hamburger icon on small factor devices

### ISSUE THREAD

**Issue by weyert** [PostHog/posthog#2516]
## Bug description
If the screen size is too small a hamburger menu is shown in top left corner but when you click it the side navigation isn't shown. 

## Expected behavior
Clicking on the hamburger menu icon should open the side navigation

![CleanShot 2020-11-25 at 17 25 50@2x](https://user-images.githubusercontent.com/7049/100263565-92f96980-2f45-11eb-8520-f925cf941cba.png)

## How to reproduce

1.  Open Safari and resize the window two half or third of the screen (see screenshot)
2. Notice the hamburger menu
3. Click on the hamburger menu icon
4. Notice the side navigation doesn't appear

## Environment

- PostHog cloud
- PostHog version: latest

## Additional context
As fallback CMD-K is working to navigate to items

**Comment by paolodamico** [comment]
Thanks for reporting @weyert! This navigation is actually deprecated, the new one is being phased in progressively. Please do let us know if the problem persists in the new navigation. Closing for now.
