### ISSUE TITLE
Enable plugins and session recording after preflight

### ISSUE THREAD

**Issue by mariusandra** [PostHog/posthog#2521]
## Is your feature request related to a problem?

I installed a fresh version of posthog and had "all systems go":

![image](https://user-images.githubusercontent.com/53387/100338209-9ab61e00-2fd8-11eb-9f30-4fe990ea620d.png)

After using my app for a while I realised no sessions were recorded. I had to go to project settings and manually enable session recording. Same for plugins - there's a toggle somewhere that enables them.

## Describe the solution you'd like

I'd like a screen after the preflight check that lets me immediately opt in to beta, experimental or heavy features of PostHog, such as plugins or session recording.

## Describe alternatives you've considered

Somehow being smart enough to know that the features exist and I need to find a checkbox on one of the three settings pages to enable them.

**Comment by Twixes** [comment]
This is done with the new onboarding flow and plugins will be enabled for all with next release.
