### ISSUE TITLE
Feature flag UI is capped at showing/searching up to 300 flags

### ISSUE THREAD

**Issue by cemerick** [PostHog/posthog#25214]
## Bug description

The feature flag UI loads a maximum of 300 flags. Managing more flags than this through the API works just fine, but not having the convenient dashboard UI is pretty inconvenient.

This limit is hardcoded here:

https://github.com/PostHog/posthog/blob/0a3e220be62a87c3ead44903bdbf79245e5ca9ec/frontend/src/scenes/feature-flags/featureFlagsLogic.ts#L52-L55

## How to reproduce

1. Create more than 300 feature flags.
2. Attempt to scroll/page through all of them (you can't), or...
3. Attempt to search for a feature flag that happens to fall on the other side of the 300 `LIMIT` (nothing will be found)

## Additional context

I originally raised this limit in a [community question](https://posthog.com/questions/practical-limits-for-feature-flags).

**Comment by AinampudiSaiSathwika** [comment]
Can i work on this issue?

**Comment by annikaschmid** [comment]
Discussed internally, we'll probably come up with a better solution for this soon. Slack thread for internal context: https://posthog.slack.com/archives/C07Q2U4BH4L/p1729588008710889

@cemerick thanks for raising this issue 🙏

**Comment by havenbarnes** [comment]
Fixed with https://github.com/PostHog/posthog/pull/26041, thanks for raising @cemerick
