### ISSUE TITLE
Funnel and insight history UX improvements

### ISSUE THREAD

**Issue by timgl** [PostHog/posthog#2524]
## Is your feature request related to a problem?

Funnels aren't a great experience at the moment. The list is cluttered, you can't delete funnels, if you save a funnel it creates a new item in the list etc. The same is true for Insights history in general, which [isn't used much](https://app.posthog.com/insights?interval=day&actions=%5B%7B%22id%22%3A2657%2C%22name%22%3A%22clicked%20history%22%2C%22type%22%3A%22actions%22%2C%22order%22%3A0%2C%22math%22%3A%22dau%22%7D%5D&events=%5B%5D&new_entity=%5B%5D&properties=%5B%7B%22key%22%3A%22id%22%2C%22value%22%3A71%2C%22type%22%3A%22cohort%22%7D%5D&date_from=-90d).

## Describe the solution you'd like

- When creating a query you should have the option to explicitly save a query. When making changes, you can 'save' those changes _against_ the same query. 
- Instead of the 'History' button, there should be a tab on Insights that's "saved queries". I like the way Amplitude displays this:
![image](https://user-images.githubusercontent.com/1727427/100346614-69434f80-2fe4-11eb-83d5-0751786bec28.png)
By default, this should just be your own queries with an option to see all queries for the project
- Each query type should have the 'saved queries' box, displayed the same way as above.

## Additional context

Requested by user as 'I want to be able to delete/edit funnels' but I think if we do above we'll have a better product in general.

**Comment by paolodamico** [comment]
I think this has evolved in other discussions. Funnel design is being tackled in #4535 & insight history is changing in favor of saved reports to make it more useful.
