### ISSUE TITLE
Delete all CH event history when deleting projects

### ISSUE THREAD

**Issue by paolodamico** [PostHog/posthog#2525]
## Is your feature request related to a problem?

When a project is deleted, if events are on CH we're currently not deleting them.

## Describe the solution you'd like

I'd like that all events associated to a project get deleted when the project is deleted.

## Describe alternatives you've considered
Not deleting them?

## Additional context
Came up on #2483, relevant to the exact wording we use when deleting a project.

**Comment by paolodamico** [comment]
Very related, we should also delete all events when deleting a person. This has come up from users ([example](https://app.papercups.io/conversations/all/1d7ff777-8cd4-4509-b985-25b824283757)) a few times just this last two days as there seems to be some mistakes in numbers.

Related internal issue: https://github.com/PostHog/product-internal/issues/39

**Comment by Twixes** [comment]
This is the case with `AsyncDeletion` now.
