### ISSUE TITLE
How to test PostHog feature branches, using self-hosted version

### ISSUE THREAD

**Issue by MannyAdumbire** [PostHog/posthog#25262]
Is there a guide for on how to test PRs, using the self-hosted/"hobby" docker version of PostHog?
How can I update my local copy/container of PostHog to the changes from a branch.

The question came up in relation to https://github.com/PostHog/posthog/pull/25174

In attempting to test the PR, I added the `hls-src` attribute on a `<video>` element and used an `.m3u8` HLS video for its value.

Then did the following:

1. pulled the latest changes from [master](https://github.com/PostHog/posthog) branch which contains this merged PR. 
2. ran `docker-compose up --build -d` 
3. "recorded" a couple sessions for replay

The fix didn't seem to be present still in my local PostHog.
I searched(`grep`ed) inside the `web`, `caddy`, `plugins`, `worker` docker containers, but can't find any reference to `hls-src`.
None of this worked.

I asked on PostHog Community as well [https://posthog.com/questions/how-to-use-latest-version-of-posthog-docker](https://posthog.com/questions/how-to-use-latest-version-of-posthog-docker).
The AI answer was not helpful.

What am I missing?

**Comment by pauldambra** [comment]
Hey Manny,

I don't actually know the answer here... 

My guess is that you need to actually build the front end. However, it's not something we support, so we don't have instructions for this.

However, your title says feature branch and your body says `master`

If you only want to update to the latest version on trunk, just use the update script https://posthog.com/docs/self-host#upgrading

**Comment by MannyAdumbire** [comment]
@pauldambra thanks so much for the suggestions.
I did check out the update script, but was able to get by just by pulling the latest changes from posthog git project, recreating the `posthog:posthog` image, then rebuilding the containers which worked!
