### ISSUE TITLE
Bug: Notebook issue adding sessions recording filters 

### ISSUE THREAD

**Issue by darkopia** [PostHog/posthog#25307]
### Bug Description

When adding a new session replay block to a notebook you are not able to apply filters, on existing replay blocks filters do work as intended. 

![image](https://github.com/user-attachments/assets/1ea3c1cc-0b80-4ff7-a730-e767ddb3728d)

## How to reproduce

1. Create a new or edit existing notebook
2. Add session replay block
3. Add filters 
4. See no options on left hand side to add filters

## Recordings block previously added:
![image](https://github.com/user-attachments/assets/0407ec2e-347c-4137-9d81-5641baf2f7c1)

**Comment by gaurav-bhardwaj29** [comment]
Hey, I would like to work on this issue.
