### ISSUE TITLE
Clicking into a trends page from a dashboard changes the view

### ISSUE THREAD

**Issue by jamesefhawkins** [PostHog/posthog#2531]
Not a big deal but a UX annoyance...

## Bug description

On our production app, look at a dashboard

https://app.posthog.com/dashboard/267

Then click into 'unique real sign ups', which is a *pie chart*

You will land on a trends page shown as a line graph instead.

**Comment by EDsCODE** [comment]
this seems to work now (clicking goes to a pie chart)
