### ISSUE TITLE
Feature request: list 'destination project' dropdown alphabetically

### ISSUE THREAD

**Issue by abigailbramble** [PostHog/posthog#25337]
### Feature request

Request to make project dropdown display the projects in alphabetical order:

<img width="643" alt="image" src="https://github.com/user-attachments/assets/f8176377-08e3-4dc1-9ac3-5e1199b595f6">

## Additional context
https://posthoghelp.zendesk.com/agent/tickets/18820

**Comment by Phanatic** [comment]
This is fixed now
