### ISSUE TITLE
Jest path configuration issue

### ISSUE THREAD

**Issue by paolodamico** [PostHog/posthog#2535]
## Bug description

Jest seems to ignore webpack configuration for paths, therefore when running tests with the following import, tests fail.

```typescript
import { lightColors } from 'lib/colors' /* Absolute path: this fails in tests, works at runtime */
```

## Expected behavior

Tests should pass properly.

## How to reproduce

1. Change line 7 on `frontend/src/lib/utils.tsx` to `import { lightColors } from 'lib/colors'`
2. Run tests and see them fail.

## Environment

Development.

## Additional context

Related to #2479.
CC @Twixes

**Comment by weyert** [comment]
you can consider using this utility for typescript: https://github.com/HosseinAgha/tsconfig-paths-jest-mapper

**Comment by Twixes** [comment]
Thanks for the suggestion @weyert! I researched a bit more off your lead, went for a slightly more extensive utility [ts-jest](https://github.com/kulshekhar/ts-jest) in #2558.
