### ISSUE TITLE
Clickhouse container creation is failing in hobby deploy Docker compose

### ISSUE THREAD

**Issue by viswa** [PostHog/posthog#25405]
## Bug Description

While running the hobby deploy docker compose, Clickhouse container creation was failing. Found these in the logs:

```
dpkg: dependency problems prevent configuration of locales:
 libc6:amd64 (2.35-0ubuntu3) breaks locales (<< 2.35) and is installed.
  Version of locales to be configured is 2.31-0ubuntu9.14.

dpkg: error processing package locales (--install):
 dependency problems - leaving unconfigured
Errors were encountered while processing:
 locales
```

It seems, with the changes made at https://github.com/PostHog/posthog/pull/25013, the Clickhouse image  was changed to base Ubuntu from base Alpine and the `init-db.sh` script mapped to the container is attempting to update libc6 from 2.31 to 2.35:

https://github.com/PostHog/posthog/blob/914ef395c85f31c662188268a39df8d883cf7166/docker/clickhouse/docker-entrypoint-initdb.d/init-db.sh#L9-L10

https://github.com/PostHog/posthog/blob/a87b2dd08e758491c05f23bf519cd99fe14bdc5d/docker-compose.hobby.yml#L47-L52

This is likely throwing the error above.

## How to reproduce

1. Follow steps in Self-Host PostHog doc: https://posthog.com/docs/self-host

## Additional context

- Added `ENCRYPTION_SALT_KEYS` environment variable for plugin server creation, ref: https://github.com/PostHog/posthog/issues/25373
- All other containers are created successfully.

### Debug info

PostHog Hobby self-hosted with `docker compose`, version/commit: [798cedaa]

**Comment by aspicer** [comment]
@viswa should be fixed in https://github.com/PostHog/posthog/pull/25407 which I just landed. let me know if it isn't!

**Comment by viswa** [comment]
It's working now with these changes @aspicer. Thanks so much.

**Comment by Kvintus** [comment]
HI @aspicer Could you please also take a look at the referenced issue https://github.com/PostHog/posthog/issues/25373 ?

**Comment by viswa** [comment]
Hey @Kvintus. This PR solves the issue ig: https://github.com/PostHog/posthog/pull/25408. Merged to master some time ago...
