### ISSUE TITLE
Error on creating a new account

### ISSUE THREAD

**Issue by jamesefhawkins** [PostHog/posthog#2541]
## Bug description

I was creating a new account on PostHog cloud in incognito with these credentials:

<img width="304" alt="Screenshot 2020-11-27 at 10 33 58" src="https://user-images.githubusercontent.com/47497682/100439954-14631000-309c-11eb-97af-ee029a66de13.png">

I got this error:

<img width="1476" alt="Screenshot 2020-11-27 at 10 32 45" src="https://user-images.githubusercontent.com/47497682/100439847-f7c6d800-309b-11eb-9fb7-964a51f458f9.png">

## Expected behavior

No error messages on signing up fresh.

**Comment by timgl** [comment]
Problem is the new navigation bar calls system_status, even if you're on app and not a staff user

**Comment by paolodamico** [comment]
I'll fix this with #2545
