### ISSUE TITLE
[session recording] player ux improvements

### ISSUE THREAD

**Issue by timgl** [PostHog/posthog#2548]
Couple of quick things I noticed while playing around

- I'm not sure about opening in new tab. It makes the process of looking at lots of session recordings feel slower than it would be if it was same page/modal. If I want to open in a new tab i can always cmd+click. You can use the backToURL pattern to put a link back to the page you were on.
- When my player is paused and I click a URL on the right I expect my player to start playing again
- There's a weird lag while clicking a URL before the url turns blue
- Would be nice if the 'event timeline' scrolled down if we got to the bottom of the list

cc @macobo

**Comment by paolodamico** [comment]
Re 1. Opening a new was is exactly intended if you want to watch multiple recordings, but I agree it might not be the best experience for everyone / every use case. Definitely worth trying your suggestion, the key here is that when you go back, you land at the exact same position in the sessions table, so you don't lose your place. I'll try this out.

**Comment by macobo** [comment]
Re opening in a new tab: Tested this out.

`backUrl` works technically, but has two problems:
- Sessions get loaded all over again (which can be slow, especially on self-hosted instances)
- If user has pressed 'show more', that state is lost

**Comment by paolodamico** [comment]
Adding a few notes from my own experience:

- Buggy experience.
    - The thing that feels the buggiest to me from the entire experience is the moving the playback cursor, I would even consider just removing it instead of having it if we can't move it around freely. Seems to happen with most recordings, but not all (e.g. might be correlated to recording duration).
    - There was also some cases in which the cursor will just get stuck at some point and then it would continue at some other point. I thought I considered this was in function of high speed playback, but it happens on 1x too ([example recording](https://app.posthog.com/sessions/play?id=1761a06996de4-0652798d99fdd9-326e7901-13c680-1761a06996e780), see jump from 0:09 to 0:19; [another example](https://app.posthog.com/sessions/play?id=1761a8fb5da35-0377898bfe5ca8-18356153-1aeaa0-1761a8fb5dbc7e); [another buggy one](https://app.posthog.com/sessions/play?id=1761a8fb5da35-0377898bfe5ca8-18356153-1aeaa0-1761a8fb5dbc7e))).
    - Here's another case in which the player just froze but the _recording_ actually kept going (notice how the current URL changes) [[source](https://app.posthog.com/sessions/play?id=176111a6a17832-0e5ce3d13c84658-3e62694b-fa000-176111a6a18fda)].
    ![image](https://user-images.githubusercontent.com/5864173/100676236-21972d80-332e-11eb-9129-7c0ea835dfd0.gif)
- It might make sense that the back X seconds button varies depending on a speed factor (e.g. going back 4 seconds if you're at 16x is not really helpful).
- Watched two separate instances of users clicking on the share feedback label on the session recording section of the project settings but we haven't received any feedback on GitHub. Think it might be worth using the command palette's feedback mechanism.

**Comment by mariusandra** [comment]
Regarding UX, mobile shouldn't be an afterthought. Currently the interface is pretty broken on a phone:

![Screenshot_20201201-091118](https://user-images.githubusercontent.com/53387/100717108-ed694e80-33b9-11eb-8d73-545505ff0292.jpg)

Other than the obvious visual issues on the screenshot, it was also not possible to drag the playback cursor.

**Comment by paolodamico** [comment]
This has evolved into other issues. Closing.
