### ISSUE TITLE
sidebar icons in app should do something on hover

### ISSUE THREAD

**Issue by jamesefhawkins** [PostHog/posthog#2553]
## Is your feature request related to a problem?

We have a lovely new sidebar:

<img width="77" alt="Screenshot 2020-11-27 at 15 55 03" src="https://user-images.githubusercontent.com/47497682/100466555-fcee4c00-30c8-11eb-90be-cbadb159598d.png">

The icons don't do anything on hover, whereas everywhere else in app and in posthog.com we generally apply an effect to signify you can click.

## Describe the solution you'd like

For the colour (or an underline) to appear on hover, consistent with the rest of the app.

## Describe alternatives you've considered

Just use it and put aside the slight UX irritation :)

**Comment by samcaspus** [comment]
Hey @jamesefhawkins  I was trying to find this side bar but failed. 
Could you help me out to find this side bar in code. I would like to experiment a bit around it. 
Thanks

**Comment by timgl** [comment]
@samcaspus If you're on a local instance, add a feature flag with the key `navigation-1775` and set the "rollout percentage" to 100%.
