### ISSUE TITLE
Bug: NPS survey type, Issue with Survey Explore Results.

### ISSUE THREAD

**Issue by darkopia** [PostHog/posthog#25554]
## Bug description

When analysing a survey and clicking explore results, on a NPS survey type the embedded NPS insight becomes editable in the surveys screen and this cannot be undone without logging out

<img width="1661" alt="image" src="https://github.com/user-attachments/assets/a34deb9a-98b6-46d4-963b-23367bfc920e">

*If you are on PostHog Cloud it would be really valuable if you can share any links where the problem occurs. This speeds up our ability to troubleshoot tremendously.*

## How to reproduce

1. Have a NPS survey type with results
2. Click explore results on any other survey (or the NPS survey)
3. Navigate back to the NPS survey
4. The embedded insight is now in edit mode

### Debug info

```shell
- [ ] PostHog Cloud, Debug information: [please copy/paste from https://us.posthog.com/settings/project-details#variables or https://eu.posthog.com/settings/project-details#variables]
- [ ] PostHog Hobby self-hosted with `docker compose`, version/commit: [please provide]
- [ ] PostHog self-hosted with Kubernetes (deprecated, see [`Sunsetting Kubernetes support`](https://posthog.com/blog/sunsetting-helm-support-posthog)), version/commit: [please provide]
```

**Comment by Aashw1n** [comment]
Hi @darkopia, @annikaschmid and @Phanatic

Seems like the embedded insight shows up in edit mode if a new insight is whipped up anywhere in the application (+ new insight in product analytics, open as insight in the web analytics section ,and the explore result button in survey results). Video below would demonstrate.


https://github.com/user-attachments/assets/dc0e55d9-e327-4d41-93c2-a642b7a982ba

After going through related code, seems like the `Query` component has a prop `readOnly` that fixes this issue when enabled, without affecting anything else. 

I've opened a PR, and added relevant info.

**Comment by Phanatic** [comment]
This is now fixed, thanks to @Aashw1n
