### ISSUE TITLE
New player's hotkey tooltips are broken

### ISSUE THREAD

**Issue by paolodamico** [PostHog/posthog#2556]
## Bug description

Tooltips introduced in https://github.com/PostHog/posthog-react-rrweb-player/pull/2 are not showing properly (see below), we're probably missing the inclusion of `rc-tooltip`s CSS styles. However, instead of fixing the styling, I think it's worth considering [this comment](https://github.com/PostHog/posthog-react-rrweb-player/pull/2#discussion_r532331173), and using Ant's tooltip component in a way that is not detrimental for posthog-react-rrweb-player standalone.

<img width="1087" alt="" src="https://user-images.githubusercontent.com/5864173/100567252-ad0cb200-328d-11eb-8375-c0e1f317e626.png">

## Expected behavior

Tooltips should show consistently as in the rest of the app.

## How to reproduce

1. Open any session on the new session player.
2. Hover over any of the player's controls.

## Environment

- Cloud, latest version.

**Comment by macobo** [comment]
This was fixed by https://github.com/PostHog/posthog/pull/2550 which was waiting to be merged.
