### ISSUE TITLE
Multi-factor authentication

### ISSUE THREAD

**Issue by Tannergoods** [PostHog/posthog#256]
**Is your feature request related to a problem? Please describe.**
From a user
> I find it not complete enough - 2FA

**Describe the solution you'd like**
When logging into PostHog I would like to have the option to turn on 2FA with two or more pieces of evidence.

**Describe alternatives you've considered**
Using a single password mechanism

**Comment by Tannergoods** [comment]
Requested by: https://app.hubspot.com/contacts/6958578/contact/35601

**Comment by Twixes** [comment]
Superseded by #3600.
