### ISSUE TITLE
RevenueCat integeration

### ISSUE THREAD

**Issue by jacobthecoder** [PostHog/posthog#25607]
### Feature request

Hi there - Please integrate with RevenueCat so subscription events from the Apple App Store, Google Play Store, and Stripe (all via RevenueCat) can write into Posthog. I would also like cohorts to sync bi-directionally between Posthog RevenueCat so that we can run pricing experiments in RevenueCat.

Here's how the integration works between RevenueCat & Amplitude and I'd love to see the same functionality in Posthog: https://www.revenuecat.com/docs/integrations/third-party-integrations/amplitude

Best, Jacob

### Debug info

```shell
- [ ] PostHog Cloud, Debug information: [please copy/paste from https://us.posthog.com/settings/project-details#variables]
- [ ] PostHog Hobby self-hosted with `docker compose`, version/commit: [please provide]
- [ ] PostHog self-hosted with Kubernetes (deprecated, see [`Sunsetting Kubernetes support`](https://posthog.com/blog/sunsetting-helm-support-posthog)), version/commit: [please provide]
```

**Comment by marandaneto** [comment]
@jacobthecoder here we go https://www.revenuecat.com/docs/integrations/third-party-integrations/posthog
