### ISSUE TITLE
Improved filtering on results in trends

### ISSUE THREAD

**Issue by annaszell** [PostHog/posthog#25609]
## Is your feature request related to a problem?
The filtering process on generated trends is slow and inconvenient, requiring users to wait for charts to load before making adjustments. 

<img width="158" alt="Screenshot 2024-10-15 at 9 27 48 PM" src="https://github.com/user-attachments/assets/c2f78b69-7cce-4f07-a549-e67c6b7b8249">

i.e. when clicking these boxes on/off multiple times ☝️  or when changing the time period

## Describe the solution you'd like
Implement a more efficient filtering system that allows users to adjust filters independently of trend generation, possibly by caching results.

## Describe alternatives you've considered
An alternative would be to allow users to preload all data and then filter locally on the client side.

## Additional context
This issue affects the usability of the platform, particularly when dealing with large datasets.

----

If you like this idea, please leave a 👍 or ❤️ reaction on this post to vote for it -- your votes and feedback help us prioritize what to work on next!

**Comment by thmsobrmlr** [comment]
Closing this issue, as this was mostly fixed. I have a todo for looking into debounced query updates / speeding up the insight UI in general.
