### ISSUE TITLE
allow me to set a feature flag rollout distribution to 0

### ISSUE THREAD

**Issue by adamvnovak** [PostHog/posthog#25613]
## Is your feature request related to a problem?

*Please describe.*

## Additional context

why can i only set it to 1? i want to remove this condition entirely but the ui won't let a 0 exist on its own

<img width="607" alt="image" src="https://github.com/user-attachments/assets/d6ba58f3-c916-4b5d-bcc1-6123d12106f2">

### Debug info

```shell
Location: https://us.posthog.com/project/45310/experiments/56897
Session: https://us.posthog.com/project/sTMFPsFhdP1Ssg/replay/019291ee-b05d-7564-9d41-32d399bead1b?t=433
Admin: http://go/adminOrgUS/018af279-c6e3-0000-2629-c13542cd843a (project ID 45310)
Sentry: http://go/sentryUS/45310
```

**Comment by slshults** [comment]
Sorry for the frustration there @adamvnovak , those fields are in need of some adjustments, thanks much for calling this out with a bug report. 

In the meantime, there's an available workaround: You can select the `1`, either with a mouse, or by putting your cursor in the field and selected with `shift+right-arrow` (or `shift+left-arrow`, depending on which side of the character your cursor is on), then you can type the `0`, as seen in the gif below. (You'll need to make sure the percentages add up to a total of 100% to be able to save the changes.)

![CleanShot 2024-10-16 at 12 35 37](https://github.com/user-attachments/assets/43b99e1e-f9d4-419a-b2b9-b42f4d0b01af)
