### ISSUE TITLE
Link from action info to edit action

### ISSUE THREAD

**Issue by timgl** [PostHog/posthog#2564]
## Is your feature request related to a problem?

When selecting a new action, I might want to edit or see all events in that action

## Describe the solution you'd like

A link in this box to `/action/:id`. Either an 'edit' icon next to the name of the action or a small `edit` link in the top right
![image](https://user-images.githubusercontent.com/1727427/100632000-9c5f4900-332c-11eb-9013-765fe0038e38.png)

The code for this lives in ActionFilterDropdown.tsx.

**Comment by BElluu** [comment]
@timgl This issue shouldnt be closed coz of above merge?

**Comment by Twixes** [comment]
Hey @BElluu! That's right, thanks for catching this.
