### ISSUE TITLE
Bug: Initial rendering of session recordings

### ISSUE THREAD

**Issue by paolodamico** [PostHog/posthog#2571]
## Bug description

There's an issue in which sometimes the session recording starts playing but the recording is not scaled properly. See below where at first the viewport seems zoomed out and the entire screen is not actually shown.

![image](https://user-images.githubusercontent.com/5864173/100642387-555a5f00-32fe-11eb-89f9-6f4559705d89.gif)

## Expected behavior

The recording should fit wholly on the screen. If more rendering/processing needs to happen maybe keep loading until this is ready?

## How to reproduce

1. Open a recording and see if the bug happens (seems like an edge case).

## Environment

- Development.

**Comment by macobo** [comment]
Please add a relevant recording under rrweb-player repo if it's your own - we can then use it there to fix it.

**Comment by Twixes** [comment]
This doesn't seem to occur anymore.
