### ISSUE TITLE
Implement brute force guessing blocking

### ISSUE THREAD

**Issue by timgl** [PostHog/posthog#2573]
## Is your feature request related to a problem?

It's possible to brute-force passwords if you're particularly determined

## Describe the solution you'd like

Install `django-axes`: https://django-axes.readthedocs.io/en/latest/2_installation.html

**Comment by nr185091** [comment]
Hey @timgl, I would like to take this issue.

**Comment by nrickles3** [comment]
Hey @timgl, I would like to take this issue.
