### ISSUE TITLE
bug: Hobby Deploy Autocapture is not working

### ISSUE THREAD

**Issue by viswa** [PostHog/posthog#25779]
### Bug Description

After initial install of the hobby deploy version, no events were showing up. After following the steps at #25125, I was able to get these:

![image](https://github.com/user-attachments/assets/2d467b21-8c0d-4cf6-9a84-bcd53a87fe6c)

- Web vitals
- Pageview
- Feature flag called
- Rageclick

But Autocapture events are not displayed. I had enabled autocapture in the project settings, but they are still not showing up. Please let me know if I missed something. Thanks.

### Debug info

```shell
- Follow steps in the hobby deploy with changes mentioned at #25125
```

**Comment by Predhin** [comment]
+1

**Comment by viswa** [comment]
Resolved after upgrading PostHog
