### ISSUE TITLE
Bug: Authorized domains for replay not filtering local and test environments

### ISSUE THREAD

**Issue by benHPostHog** [PostHog/posthog#25771]
## Bug Description

Session replays from localhost and test / staging hosts are still being captured despite not being authorized domains.

![CleanShot 2024-10-23 at 14 43 39](https://github.com/user-attachments/assets/99cf8eca-50ed-47be-94c7-76e173f8ed96)

![CleanShot 2024-10-23 at 14 48 58](https://github.com/user-attachments/assets/3e99bb14-1cbc-45bf-b9d7-b6f864e5fc0b)

(Could the suggestions possibly also be authorized?)

## Additional context

From: https://posthoghelp.zendesk.com/agent/tickets/19667

### Debug info

```shell
Kind: support
Target area: data_management
Report event: http://go/ticketByUUID/1be78333-fd76-4bfb-a75c-9950dbb74dad
Session: https://us.posthog.com/project/sTMFPsFhdP1Ssg/replay/0192b514-a088-73b3-8b23-a33c0e127541?t=2971
Location: https://us.posthog.com/project/90100/replay/home?filters=%7B%22filter_test_accounts%22%3Afalse%2C%22date_from%22%3A%22-3d%22%2C%22date_to%22%3Anull%2C%22filter_group%22%3A%7B%22type%22%3A%22AND%22%2C%22values%22%3A%5B%7B%22type%22%3A%22AND%22%2C%22values%22%3A%5B%5D%7D%5D%7D%2C%22duration%22%3A%5B%7B%22type%22%3A%22recording%22%2C%22key%22%3A%22duration%22%2C%22value%22%3A1%2C%22operator%22%3A%22gt%22%7D%5D%2C%22order%22%3A%22start_time%22%7D&sessionRecordingId=0192b50d-a75a-72b3-a7fc-6f6...
Sentry: http://go/sentryUS/90100
Persons-on-events mode for project: person_id_override_properties_on_events
```

**Comment by pauldambra** [comment]
have asked a follow up question on the zendesk report. i'd be very surprised if this wasn't working for localhost - and the checking code hasn't changed for months :)

**Comment by pauldambra** [comment]
yep, just tested this by pointing my localhost at posthog cloud which has authorized urls set and correctly received a disabled response from decide.

going to close this since i'm 99.99999% certain this is local to the reporter

**Comment by aaronucsd** [comment]
Hi,

  The localhost just call the BE service APIs like `http://localhost:8080/api/v1/batch/batches`. Similar to the stage hosts.

**Comment by aaronucsd** [comment]
For now. I hack it by adding this check on our index.html file. Only include when it's prod urls.
```
    <script>
      if(window.location.href.includes('parasail.io')) {
        !function(t,e){var o,n,p,r;e.__SV||(window.posthog=e,e._i=[],e.init=function(i,s,a){function g(t,e){var o=e.split(".");2==o.length&&(t=t[o[0]],e=o[1]),t[e]=function(){t.push([e].concat(Array.prototype.slice.call(arguments,0)))}}(p=t.createElement("script")).type="text/javascript",p.async=!0,p.src=s.api_host.replace(".i.posthog.com","-assets.i.posthog.com")+"/static/array.js",(r=t.getElementsByTagName("script")[0]).parentNode.insertBefore(p,r);var u=e;for(void 0!==a?u=e[a]=[]:a="posthog",u.people=u.people||[],u.toString=function(t){var e="posthog";return"posthog"!==a&&(e+="."+a),t||(e+=" (stub)"),e},u.people.toString=function(){return u.toString(1)+".people (stub)"},o="init capture register register_once register_for_session unregister unregister_for_session getFeatureFlag getFeatureFlagPayload isFeatureEnabled reloadFeatureFlags updateEarlyAccessFeatureEnrollment getEarlyAccessFeatures on onFeatureFlags onSessionId getSurveys getActiveMatchingSurveys renderSurvey canRenderSurvey getNextSurveyStep identify setPersonProperties group resetGroups setPersonPropertiesForFlags resetPersonPropertiesForFlags setGroupPropertiesForFlags resetGroupPropertiesForFlags reset get_distinct_id getGroups get_session_id get_session_replay_url alias set_config startSessionRecording stopSessionRecording sessionRecordingStarted captureException loadToolbar get_property getSessionProperty createPersonProfile opt_in_capturing opt_out_capturing has_opted_in_capturing has_opted_out_capturing clear_opt_in_out_capturing debug".split(" "),n=0;n<o.length;n++)g(u,o[n]);e._i.push([i,s,a])},e.__SV=1)}(document,window.posthog||[]);
        posthog.init('phc_NevnyJTSWrDxjtmQ7REoPNcjGFSxpQFduaGoqU4zS5N',{api_host:'https://us.i.posthog.com', person_profiles: 'identified_only' // or 'always' to create profiles for anonymous users as well
            })
      }
    </script>
```

**Comment by aaronucsd** [comment]
![Screenshot 2024-10-23 at 1 26 04 PM](https://github.com/user-attachments/assets/2238f81c-321b-4d7a-92d7-f1e89150d68c)

**Comment by aaronucsd** [comment]
Do i need to include some updated posthog script once i added the authorized domains? Cause i only started to add that yesterday morning. But i saw the localhost, etc, even after an hour of updating the authorized domains. Maybe takes time to propagate?

**Comment by aaronucsd** [comment]
I just checked and still see localhost sessions. Unless i use the `Filter out internal and test users`.

![Screenshot 2024-10-23 at 1 40 33 PM](https://github.com/user-attachments/assets/e17ba239-06ef-4a2b-8d3a-bca8e1c0ad31)

**Comment by pauldambra** [comment]
hey... that batch/batches isn't a posthog API, no?

* when posthog boots
* it makes a call to `/decide/`
* `/decide/` checks the origin and referer
* if there are are authorized URLs then it checks against those
* if there is no match then session recording is reported as disabled and won't start

i just checked that is working correctly.

for your case i'd need to see the request and response that your localhost is making to /decide/

**Comment by pauldambra** [comment]
> For now. I hack it by adding this check on our index.html file. Only include when it's prod urls.

that's totally valid if you don't want to run posthog on localhost, but it's not necessary to avoid sending replay from localhost

**Comment by aaronucsd** [comment]
I think having replays for localhost just add unnecessary noise we need to keep filtering out. It's mostly internal tests while developing. Also, does that add to the dashboard data? That would make it very incorrect data for our analytic reports.

**Comment by pauldambra** [comment]
hey... 

if you don't want _any_ data from localhost, then the correct thing to do is not to start PostHog

If you want to run posthog but not receive replays then one of the correct things is to set authorized urls. that requires that your localhost is sending the correct origin/referer to be identified as localhost

--

what's your goal here?

**Comment by aaronucsd** [comment]
My goal is get tracking data and replays for our production website, where our customer has access to. That is on `https://www.saas.parasail.io/` not localhost. Localhost is our development (my laptop) server. I thought one way to filter this is adding the `saas` host /url to the list of  authorized urls. What am i missing here?

**Comment by aaronucsd** [comment]
Just to be clear. Here are the hosts we have.

localhost:* -> local development only
stage/dev1 -> sandbox to test before release to production
/www.saas.parasail.io -> our production box where we want posthog tracking.

**Comment by pauldambra** [comment]
> I thought one way to filter this is adding the saas host /url to the list of authorized urls.

that list of authorized urls is only for session replay, not other tracking data.

if you don't want to track an environment the absolute best way to do it is not to init posthog at all

some people do run posthog in non prod environments so they can test tracking but there's not one place to filter that data

**Comment by aaronucsd** [comment]
I see. I thought Posthog is like Google analytics. So i can track my customer traffic, etc.

**Comment by pauldambra** [comment]
> I see. I thought Posthog is like Google analytics. So i can track my customer traffic, etc.

it is.

i think we might be talking past each other.

----

this initial bug report was that you wanted to init posthog in local host but not record session replays

i guess that's not what you want, but I'm not clear on what you're asking any more, sorry.

what is it that you want to achieve but can't right now?

**Comment by aaronucsd** [comment]
> this initial bug report was that you wanted to init posthog in local host
No. I wanted NOT to init posthog or have posthog do anything with localhosts. This must have been lost in translation from zendesk to github ticket.

Here is my original message.
```

LongOct 22, 2024, 17:24 UTCAdded production urls (www.saas.parasail.io) to authorized hots but the session replay still recording localhost, stage, dev1 etc. Why is that? I can filter for internal and test users but would like it not to record those hosts.
--


Long

Oct 22, 2024, 17:24 UTC

Added production urls ([www.saas.parasail.io](http://www.saas.parasail.io/)) to authorized hots but the session replay still recording localhost, stage, dev1 etc. Why is that? I can filter for internal and test users but would like it not to record those hosts.
```

**Comment by aaronucsd** [comment]
> what is it that you want to achieve but can't right now?

Ok. just two things i want to confirm and acheive.
1) I still seeing stage being recorded for session replay. I assume once i have the code to omit the posthog script injection. This will fix this.

2) I want to know if the dashboard data (attached) is including all the hosts atm, including localhosts, stage? If yes, then those data are not useful for us atm. We need to wait for the fix from 1.

**Comment by pauldambra** [comment]
i still don't follow, sorry.

> I still seeing stage being recorded for session replay. I assume once i have the code to omit the posthog script injection. This will fix this.1. 

yes, if you don't want data from localhost, then stop sending it

if you do want data from localhost and want to investigate why recording is coming through I still need to see the request and response to the /decide/ endpoint, so i can see the origin and referer

> I want to know if the dashboard data (attached) is including all the hosts atm, including localhosts, stage?

there's nothing attached, but, if you're sending data from an environment then we're receiving

**Comment by aaronucsd** [comment]
Sorry. This the dashboard i'm seeing atm.  Does this data include all the hosts? Is there a way to filter like how `Filter out internal and test users` button toggle for session replay for dashboard?
![Screenshot 2024-10-23 at 3 37 11 PM](https://github.com/user-attachments/assets/b48868bb-9742-4047-b496-c8d816eb75ab)

![Screenshot 2024-10-23 at 3 22 00 PM](https://github.com/user-attachments/assets/d8eb868e-c746-42d6-b420-5617e5474dbf)
