### ISSUE TITLE
Session recording playback on new tabs

### ISSUE THREAD

**Issue by paolodamico** [PostHog/posthog#2581]
## Is your feature request related to a problem?

When watching multiple session recordings, you may want to open multiple sessions on different tabs. The problem is that when you do this, all the tabs starting playing the recording as soon as it's loaded, and then it's a bit messy going back (plus opening a lot of tabs seem to have a significant memory impact).

## Describe the solution you'd like

I'd like for tabs to start auto-playing only if I'm focused on the window (and start playing when I focus the window).

## Describe alternatives you've considered

Keep pausing and going back to the beginning of the recording.

**Comment by macobo** [comment]
Note that this may become not relevant if we decide to ditch multiple tabs.

**Comment by paolodamico** [comment]
As discussed in the sync today, we're thinking about keeping both options, in which case we might need to address this specifically, keeping in the backlog for now.

**Comment by macobo** [comment]
Ack - in this case we might want to check/wait for visibility change event in the player.
