### ISSUE TITLE
Allow custom expressions in trends

### ISSUE THREAD

**Issue by macobo** [PostHog/posthog#2584]
## Is your feature request related to a problem?

As part of #2560, I'm using posthog to self-analyze metrics from posthog-js.

One of the metrics to track is `how many requests are in flight when page unloads` - which would be `total_requests - handled_requests`.

In addition it would be great to have access to more operators than sum/min/max/avg. For example 90th percentile, 95th percentile are also relevant for these kind of metrics

## Describe the solution you'd like

Being able to enter custom metrics into the select box.

## Describe alternatives you've considered

Sending more metrics directly from posthog-js.

## Additional context

Quick screenshot of the relevant bit of filters:

![Screenshot from 2020-12-01 10-43-16](https://user-images.githubusercontent.com/148820/100716949-14c41980-33c2-11eb-8547-b7557dca5b5e.png)

**Comment by Twixes** [comment]
Possible on Cloud/EE thanks to #2630 + formulas.
