### ISSUE TITLE
Using `inserted_at` as batch export bound field is vulnerable to distribution lag

### ISSUE THREAD

**Issue by tomasfarias** [PostHog/posthog#25850]
## Bug description

Batch exports use `inserted_at` as the field to determine which events fall under which batch, by looking at the row's `inserted_at` and comparing it to the batch export run bounds. 

However, this value is recorded upon consuming a Kafka record, not when inserting into the events table. When ClickHouse uses a distributed table, the insert is queued and replicated in all nodes, which can take some time if there's network lag. This could cause events to be missed as the `inserted_at` was set before it was written.

We should switch to a more reliable field to determine which events belong into which bounds.

### Debug info

- [ ] PostHog Cloud, Debug information: [please copy/paste from https://us.posthog.com/settings/project-details#variables or https://eu.posthog.com/settings/project-details#variables]
- [ ] PostHog Hobby self-hosted with `docker compose`, version/commit: [please provide]
- [ ] PostHog self-hosted with Kubernetes (deprecated, see [`Sunsetting Kubernetes support`](https://posthog.com/blog/sunsetting-helm-support-posthog)), version/commit: [please provide]

**Comment by timgl** [comment]
Completed
