### ISSUE TITLE
Confusing UX: Removing event/action from trends

### ISSUE THREAD

**Issue by macobo** [PostHog/posthog#2586]
## Is your feature request related to a problem?

![Screenshot from 2020-12-01 10-48-39](https://user-images.githubusercontent.com/148820/100717614-f01c7180-33c2-11eb-931d-f25f6ac8ad41.png)

What does the above X next to "Add filters" do?

My initial thought was "it removes the 'add filters' text". In reality it removes the whole action.

## Describe the solution you'd like

Position the X in a better/clearer place, give it a tooltip.

## Additional context

Accidentally hit the button multiple times even after knowing about it when trying to construct expressions for #2560

**Comment by paolodamico** [comment]
Created a new epic #2760 to rethink the entire experience, think we could close this issue and use only as reference when designing the new experience. Thoughts?

**Comment by macobo** [comment]
Up to you! :+1:
