### ISSUE TITLE
API: Ability to check Organization & Project Access for a Personal API Key

### ISSUE THREAD

**Issue by VladislavSmolyanoy** [PostHog/posthog#25865]
## Is your feature request related to a problem?

With update 1.5.0, SwiftyLaunch users will be able to let SwiftyLaunch also generate new PostHog projects on their behalf. The App will create a new Xcode project as usual, then go to your API, create a new project and add it either to an existing organization or also create a new organization. We will then take the API keys of the newly generated project and pre-fill the .env files with it.

But to do that, we first prompt the user to enter their PostHog Personal API key and once entered, we want to make sure that the api key has all the required permissions, and currently there is no direct way to do so.

## Describe the solution you'd like

An API Endpoint that would return all granted permissions for a personal API key.

Example: **GET** `https://eu.posthog.com/api/keyscopes` with the provided Bearer API Key
Which would return:
```
{
  "label": "API_KEY_LABEL",
  "org_and_proj_access": "ALL",
  "scopes": [
    {
      "project": "write"
    },
    {
      "organization": "write"
    },
    {
      "activity_log": "read"
    },
  ]
}
```
or
```
{
  "label": "API_KEY_LABEL",
  "org_and_proj_access": "ALL",
  "scopes": [
      "project:write",
      "organization:write",
      "activity_log:read"
  ]
}
```

## Describe alternatives you've considered

Now, there is a workaround to check if we have the required access (org:write, and proj:write) is to create a dummy organization (to check for org:write), which will come with a project by default, then delete the project (to check for proj:write) and finally delete the org to clean up.

Not ideal, but it currently works. To minimize stress on your servers we only do this check once: after the api key was entered. But we would also love to be able to check it more often, but constantly writing/deleting orgs and projs sounds like poo.

### Debug info

```shell
- [X] PostHog Cloud, Debug information: [please copy/paste from https://us.posthog.com/settings/project-details#variables]
- [ ] PostHog Hobby self-hosted with `docker compose`, version/commit: [please provide]
- [ ] PostHog self-hosted with Kubernetes (deprecated, see [`Sunsetting Kubernetes support`](https://posthog.com/blog/sunsetting-helm-support-posthog)), version/commit: [please provide]
```

**Comment by zlwaterfield** [comment]
This has been implemented. 

This is undocumented right now but you can use https://us.posthog.com/api/personal_api_keys/@current or https://eu.posthog.com/api/personal_api_keys/@current to get the object of the personal api key being used on the request. You can't create, update or delete them but this should give you the ability to load the scopes.

**Comment by VladislavSmolyanoy** [comment]
Thanks a lot! 

Just to be clear, as it’s undocumented yet: An empty array of scoped_organizations, is equal to "All Access", right?

![CleanShot 2024-11-30 at 13 24 26@2x](https://github.com/user-attachments/assets/1cbac042-d5ab-43da-b3d7-167ddf4064bf)
