### ISSUE TITLE
Custom filters on dashboards

### ISSUE THREAD

**Issue by macobo** [PostHog/posthog#2587]
## Is your feature request related to a problem?

When setting up dashboards I'd like to filter the stats to a certain page/subdomain. 

## Describe the solution you'd like

Allow adding a extra filters for all graphs on a dashboard (e.g. filter by $current_url)

## Describe alternatives you've considered

Updating every graph in dashboard one-by-one and then reverting them back.

## Additional context

Related to https://github.com/PostHog/posthog/issues/780

Datadog has a decent solution for this: https://docs.datadoghq.com/dashboards/template_variables/, which I think we can simplify and use ourselves.

Came up during #2560

**Comment by simfish85** [comment]
This came up in a recent demo - they'd like to filter on person or event properties, e.g. allowing a dashboard to be dynamically changed to show insights for a specific geographic region, organization, segment etc.

**Comment by clarkus** [comment]
It's possible for dashboard filters to override or conflict with those defined at the insight level. How would that be handled? When an insight / dashboard item is in an incompatible state, does it trigger to an empty state? Just feels like there's a good bit of variability depending on the insights used and their existing filters.
