### ISSUE TITLE
Identify being called way too many times on cloud

### ISSUE THREAD

**Issue by yakkomajuri** [PostHog/posthog#2588]
## Bug description

*Please describe.*  
*If this affects the front-end, screenshots would be of great help.*  

See [this user](https://app.posthog.com/person_by_id/34173543) - there are 400 consecutive `$identify` events. 

## Expected behavior

Not this many `$identify` calls.

## Environment

- PostHog cloud

## Additional context

Potentially related to #2552 ? @timgl 

The good news is that I can now do cross-domain attribution.

**Comment by Twixes** [comment]
Is this still an issue?
