### ISSUE TITLE
halloween hedgehog skin

### ISSUE THREAD

**Issue by lottiecoxon** [PostHog/posthog#25895]
Unsure if we can turn this around in a day but... I have made a pumpkin style hedgehog mode skin for halloween

Fall
![Image](https://github.com/user-attachments/assets/5600e960-c4d6-4dc8-953a-76f20e8e15e9)

Walk
![Image](https://github.com/user-attachments/assets/0729e598-441c-4072-85a9-5038241c53c2)

Jump
![Image](https://github.com/user-attachments/assets/155c5168-dc18-4c7e-8354-b68936f08b69)

Wave
![Image](https://github.com/user-attachments/assets/14cb0825-6c65-4d83-88d5-63127b60c7da)

**Comment by benjackwhite** [comment]
YES

**Comment by lottiecoxon** [comment]
Art above if you wanna have a crack at this @benjackwhite 🥇

**Comment by lottiecoxon** [comment]
Whether we got this in the app or not it is now passed halloween so now will close this issue
