### ISSUE TITLE
Sessions page loads without date

### ISSUE THREAD

**Issue by yakkomajuri** [PostHog/posthog#2589]
## Bug description

*Please describe.*  
*If this affects the front-end, screenshots would be of great help.*  

Sessions page loads without a set date (although the table loads correctly):

<img width="261" alt="Screenshot 2020-12-01 at 09 32 34" src="https://user-images.githubusercontent.com/38760734/100722182-3b7d5280-33b8-11eb-983b-6a4bfa0345e2.png">

The problem is that clicking the button to go back a day fails with "Invalid date"

## Expected behavior

Correct date on the date selector

## How to reproduce

1. Go to Sessions (by day) page
2. Look at date

**Comment by mariusandra** [comment]
A bit of extra context: The date is synced with the URL. There should be a "without date" option that keeps the url as is (/sessions, no params), just so we would have a permalink that doesn't change to ?date=... on opening.

The back button is an obvious bug here.

**Comment by macobo** [comment]
This seems to have been fixed, probably by @paolodamico :)
