### ISSUE TITLE
Loading data-heavy tables consistently times out on first load

### ISSUE THREAD

**Issue by yakkomajuri** [PostHog/posthog#2590]
## Bug description

*Please describe.*  
*If this affects the front-end, screenshots would be of great help.*  

See our [content dashboard](https://app.posthog.com/dashboard/1052) for example. The tables with referrers for the docs and blog always fail on first load. Refreshing them does the trick.

It loads correctly when it does load, which is fine - it's just quite annoying from a UX perspective that these tables that I can't build won't load immediately. 

## Expected behavior

Tables load like everything else.

## How to reproduce

1. 
2. 
3. 

## Environment

- PostHog cloud or self-managed?
- PostHog version/commit

**Comment by EDsCODE** [comment]
various things such as clickhouse optimizations and better caching have made this experience better
