### ISSUE TITLE
Improved sessions and session recording filtering

### ISSUE THREAD

**Issue by macobo** [PostHog/posthog#2595]
## Is your feature request related to a problem?

"Sessions" page is the main entry point to session recording. As such we should:
- Make it powerful enough to help users find sessions which are relevant for them (e.g. find sessions from certain cohorts/users who ran into errors/etc)
- Generalize the system to allow jumping from e.g. trends or funnels to sessions (show me users who did sign up that day, show me users who dropped off at this step in the funnel).

Closely related issues:
- Allowing to filter sessions by specific actions: https://github.com/PostHog/posthog/issues/2130
- Adding a more general filtering capabilities https://github.com/PostHog/posthog/issues/2594

## Describe the solution you'd like

Add a filtering system which allows:
1. Filtering by user properties
2. Filtering by events which occur in the session (already partially exists): e.g. show me sessions where $pageview occurred with $current_url = '/foobar/
3. Filtering by cohorts 
4. Filtering by session properties: e.g. show me sessions where there's a recording and the recording is > 3m in length
5. Filtering by users who have done $foo in $timerange (https://github.com/PostHog/posthog/issues/2594)
6. Filtering by date of the session (note that the page is currently structured around this filter, it would become a normal filter then)

Ideally we should be able to reuse the filtering modal/logic from insights.

Next, to make full use of this, we can then add shortcuts to jump from insights to session recordings. Currently clicking on a data point in trends/insights opens a modal with list of users - we could add a "view sessions" button there.

**Comment by paolodamico** [comment]
Another random idea that I thought might be useful is able to filter a random sample of recordings / random ordering (based in the filters you've applied), in case you have a ton of recordings you can do sampling for watching. This may be combined with the option to do random sampling at the recording stage, or just pick one.

**Comment by macobo** [comment]
Discussed this with Paolo.

We'll try to improve this during this sprint, though not 100% sure that no 5 is doable.

Plan for now: Put the new filters behind a feature flag, extend filtering logic from insights with specific logic for session recording

**Comment by EDsCODE** [comment]
Unrelated to the specifics of this ticket but related to more powerful session recording: maybe we can create a sentry integration and some how line up errors with session recordings so that they're very directly connected?

**Comment by paolodamico** [comment]
FYI maybe it's not worth spending time on this right now as we're redoing the filters anyway but it seems like there's a bug with the date filter. If you use a URL with a date param, the date won't be set anyways ([example](https://app.posthog.com/sessions?date=2020-11-30)). The previous and next day also seem to generate invalid dates when used.

**Comment by macobo** [comment]
The date thing is duplicate of https://github.com/PostHog/posthog/issues/2589

Regarding sentry, this issue acts as a superset of this as if sentry integration is turned on we'll track $exception events. You can then turn that into a query.

That said, we probably can go deeper here (either by adding the recording url to sentry or https://github.com/PostHog/posthog/issues/2130) but I'd like to keep this issue focused on adding the basic filtering capability.

**Comment by macobo** [comment]
Quick overview of current state:

- You can filter by user properties everywhere
- You can also now filter by recording duration (if enabled)
- There's a PR for adding capability to filter by action + event properties on Clickhouse
   - With a link from insights page

Next steps after these land:
- Optimize sessions query on postgres https://github.com/PostHog/posthog/issues/2739
- Add filtering by action/event properties capability to postgres as well
- Improve filtering UI/UX. One idea is to steal livesession UI and only display a 'search box': 
![Screenshot from 2020-12-17 23-24-30](https://user-images.githubusercontent.com/148820/102605714-60025a00-412e-11eb-84c8-1386f1048a2c.png)
![Screenshot from 2020-12-17 23-24-49](https://user-images.githubusercontent.com/148820/102605711-5f69c380-412e-11eb-80d9-546396ea43eb.png)
- Create some shortcuts for filters - e.g. jumping to view sessions by cohort, where $rageclicks occurred or where $exceptions occurred.
- Improve date filtering - rather than query by day, make the page order by last month for example.

**Comment by macobo** [comment]
This is now done, will be released with the next release! :)
