### ISSUE TITLE
No error message on creating an account via an invite link for the wrong email

### ISSUE THREAD

**Issue by jamesefhawkins** [PostHog/posthog#2599]
Slight edge case...

## Bug description

* Yakko invited me to the new demo instance with james at posthog email
* I used james+demo at posthog instead
* On submitting form, nothing happens 

## Expected behavior

An error message saying this isn't the expected email address, or - better - some way of requesting an invite to the new email address, which emails the admin users.

## Environment

- PostHog cloud

**Comment by paolodamico** [comment]
Will get fixed with #2336 (planned for release 1.19.0), there's actually a message but it's shown in black text in a place where it gets completely lost with the rest of the page, which is quite unhelpful.

**Comment by Twixes** [comment]
Fixed.
