### ISSUE TITLE
Random UX improvements to session recording player

### ISSUE THREAD

**Issue by paolodamico** [PostHog/posthog#2604]
This issue groups several minor UX improvements that have been discussed in different places:
- Add timestamps to the timeline pages
- Fade away bottom of event timeline list to indicate that there are more items available (following #2453)
- Show additional user information when hovering the user's email address
- Change the active state of the speed indicator to make it more obvious which speed is selected
- Use command palette's feedback bar
- Vary _go back X seconds_ with a speed factor (e.g. going back 4 seconds if you're at 16x is not really helpful)
- Automatically scroll the event timeline when the bottom is reached
- Very long user identifiers overflow the screen
<img width="332" alt="" src="https://user-images.githubusercontent.com/5864173/100937167-37385e80-34b8-11eb-8fe7-08e7a8812a4a.png">

**Comment by Twixes** [comment]
This is pretty much all solved with the new recordings player.
