### ISSUE TITLE
Celery exporter not working with 1.18.0

### ISSUE THREAD

**Issue by FUSAKLA** [PostHog/posthog#2607]
## Bug description

We use https://github.com/zerok/celery-prometheus-exporter to watch over the task queue in the Celery.
After upgrade to 1.18.0 it stopped working.
This was caused by this commit https://github.com/PostHog/posthog/commit/b8d1ba43f47c5987c05f99a7b1cfc2452c1f40b9  adding the `--without-gossip`. Without this flag, the exporter works still fine.

It's not actually a bug even though it used to work. Would you accept adding flag to enable/disable the worker gossip for the `/bin/docker-worker-celery` script?

## Environment
- Self hosted Posthog 1.18.0 instance running in Kubernetes

**Comment by yakkomajuri** [comment]
Best to ask the PR author!

@mariusandra

**Comment by mariusandra** [comment]
Hi @FUSAKLA ! Thank you for reporting the issue! I have put out PR #2621 that should solve this!

**Comment by FUSAKLA** [comment]
Thanks a lot for taking look at it!
