### ISSUE TITLE
Hard to add more than 5/6 steps in funnel

### ISSUE THREAD

**Issue by timgl** [PostHog/posthog#261]
**Describe the bug**
![image](https://user-images.githubusercontent.com/1727427/75724380-1cb82700-5c93-11ea-8627-3cd443f45c5a.png)

Once you get over 5/6 items in the funnel, steps get squished.

**To Reproduce**
1. Go to funnels.
2. Create funnel with 5-6 steps.

**Expected behavior**
It shouldn't get squashed

**Solution**
either give the boxes a minimum width, or just do a vertical list of steps.

**Comment by pedroapfilho** [comment]
I had similar issues in the past, and the solution was to make the X scrollable, we could add a `min-width` to the step box and add the `overflow-x` as `auto` on the container.

What do you guys think?

**Comment by timgl** [comment]
I like it, it's simple. I wonder how we could make it work with the funnel below, in a way it's still obvious that a step above corresponds to that part of the funnel

**Comment by pedroapfilho** [comment]
We can add a flag to the funnel, saying which step it is

**Comment by timgl** [comment]
Fixed
