### ISSUE TITLE
Bug with $feature_flag_called metrics

### ISSUE THREAD

**Issue by paolodamico** [PostHog/posthog#2614]
## Bug description & expected behavior

We seem to have an issue around `$feature_flag_called` as the numbers do not seem to match what we would expect. See [this graph](https://app.posthog.com/insights?events=%5B%7B%22id%22%3A%22%24feature_flag_called%22%2C%22name%22%3A%22%24feature_flag_called%22%2C%22type%22%3A%22events%22%2C%22math%22%3A%22dau%22%7D%5D&breakdown=%24feature_flag_response&breakdown_type=event&display=ActionsLineGraph&interval=week&date_from=-90d&properties=%5B%7B%22key%22%3A%22%24feature_flag%22%2C%22value%22%3A%22actions-ux-201012%22%7D%2C%7B%22key%22%3A%22id%22%2C%22value%22%3A71%2C%22type%22%3A%22cohort%22%7D%5D) for `actions-ux-201012`. A few issues:
- Numbers for active flag seems very, very low (3 active users in a single week seems way off, particularly considering the 50% rollout)
    - We may have an additional bug in which we're not properly generating the _cohorts_ for users with an active/inactive feature flag. For instance for this experiment we always released with a 50% roll out to all users, but the numbers are never close to 50%, but tabling this until we know that we're sure we can trust these numbers.
- Numbers do not match those of the users data points (#1649), unsure which one is right.
- Numbers on week of Oct 18 are 0, but this experiment and feature flag were released on Oct 14 (#1841), and we definitely have activity in this period with the feature flag being active (see [this graph](https://app.posthog.com/insights?actions=%5B%7B%22id%22%3A2745%2C%22name%22%3A%22created%20action%20%5Bno%20toolbar%5D%22%2C%22type%22%3A%22actions%22%2C%22order%22%3A0%2C%22properties%22%3A%5B%7B%22key%22%3A%22%24active_feature_flags%22%2C%22value%22%3A%22actions-ux-201012%22%2C%22operator%22%3A%22icontains%22%2C%22type%22%3A%22event%22%7D%5D%2C%22math%22%3A%22dau%22%7D%2C%7B%22id%22%3A2745%2C%22type%22%3A%22actions%22%2C%22order%22%3A1%2C%22name%22%3A%22created%20action%20%5Bno%20toolbar%5D%22%2C%22properties%22%3A%5B%7B%22key%22%3A%22%24active_feature_flags%22%2C%22value%22%3A%22actions-ux-201012%22%2C%22operator%22%3A%22not_icontains%22%2C%22type%22%3A%22event%22%7D%5D%2C%22math%22%3A%22dau%22%7D%5D&events=%5B%5D&new_entity=%5B%5D&interval=week&date_from=-90d&breakdown=false&breakdown_type&display=ActionsLineGraph&properties=%5B%7B%22key%22%3A%22id%22%2C%22value%22%3A71%2C%22type%22%3A%22cohort%22%7D%5D)).

## Environment

Cloud

## Additional context

No additional context.

**Comment by macobo** [comment]
I think this is coming from how frontend/src/lib/logic/featureFlagLogic.ts works - we don't call isFeatureEnabled in our own codebase but instead load all features into kea and then check them within an object. This bypasses the call we have in `isFeatureEnabled` that creates this event.

**Comment by paolodamico** [comment]
Right, so this would certainly affect the volume numbers. As for active users, the way we set feature flags on kea with `posthog.onFeatureFlags()`, would that trigger the `$feature_flag_called` event?

Regardless I think there's an important trade-off here to consider. We absolutely need to know the number of users in each group (i.e. feature flag true/false) to be able to normalize experiments results. We might then need to either find another way to accomplish this, or call the feature flag every time (or at least each feature flag once). Thoughts?

CC @mariusandra too

**Comment by mariusandra** [comment]
In React, if you call `isFeatureEnabled` on *every* render, there will be way too many `$feature_flag_called` events, as the same flag can potentially be checked multiple times per second. Sending the event once per visit is probably enough.

Here's a PR that uses some JS magic (`Proxy`) to spy on the existing `featureFlags` object and call the capture events when seeing a flag for the first time: https://github.com/PostHog/posthog/pull/2643

**Comment by mariusandra** [comment]
Some stats:

When just opening /insights, the `navigation-1775` flag was requested 6 times. 
![image](https://user-images.githubusercontent.com/53387/101000175-ce0b2680-355d-11eb-8bc9-4f0be6a30b05.png)

**Comment by mariusandra** [comment]
I guess this is resolved after #2643 ?
