### ISSUE TITLE
Sum/Avg/Min/Max of event property is inconvenient to use

### ISSUE THREAD

**Issue by macobo** [PostHog/posthog#2619]
## Bug description

If you have many event properties, using sum/avg/min/max of event property becomes hell to use.

![Peek 2020-12-02 10-27](https://user-images.githubusercontent.com/148820/100847989-2e7c6400-3489-11eb-8250-5f95c9a4fc92.gif)

## Expected behavior

Using a text input with autocomplete/suggestions

## How to reproduce

1. Send an event with 200 numeric properties to posthog
2. Try to analyze it (e.g. sum one of them

## Environment

- Both

## Additional context

Ideally only properties actually only on that event would get suggested - currently all properties are.

Note that ideally we should be able to input any property there - not just whitelisted ones.

Also $-prefixed keys are not included instead of using same logic as events does (using PropertyKeyInfo)

Came up during #2560

**Comment by timgl** [comment]
For future, definitely worth adding the `Good First Issue` label to help people discover
