### ISSUE TITLE
Public API key can send data to other domains

### ISSUE THREAD

**Issue by Tannergoods** [PostHog/posthog#262]
**Describe the bug**
The public API key can allow someone to send events to another domain, possible for bad reasons

**To Reproduce**
1. Copy the api code used on the JS side from a website implementing PostHog
2. Create a test website with the same script, api_host & api key
3. the fake site is displayed in PostHog

**Expected behavior**
Some security to stop this?

**Desktop (please complete the following information):**
 - MacOS
 - Chrome

**Comment by SanketDG** [comment]
I am guessing that there is a small title in the description, what was actually meant was events in PostHog being _sent_ from another domain, thus skewing the data in the dashboards.

A good option seems like to have the idea of "Authorized URLs", and just to filter out any requests that are not coming from these "Authorized URLs"

How to _authorize_ URLs? Well there are a couple of ways to verify the "ownership", which involves some kind of information being put against the domain and then PostHog verifies that.

- DNS TXT record: checks for the `{code}` string present in one of the TXT records on the domain - name.
Meta Tag: checks for the presence of a `<meta name="{prefix}" content="{code}">` tag in the `<head>` part of the domain's home page using either HTTP or HTTPs protocols.
HTML File: checks for the presence of a file named `{code}.html` at the root of the domain's website containing the string `{code}` using either HTTP or HTTPs protocols.

Let me know what do you think @timgl @Tannergoods

**Comment by timgl** [comment]
@SanketDG Great points!

I think the ownership of the domain itself isn't the issue (as you can only put our snippet on the actual domain if you own it). The problem is if you just do a simple CURL request using the API key you can send fake events.

The simplest thing we can do is check whether the Referer is in the team's `app_urls`.

I would love to see real-world examples of this happening though, as I don't think it is very much (yet!)

**Comment by Twixes** [comment]
Can't really prevent this. The entire point is that requests to the capture endpoint can be made form anywhere and there's no way to verify them.
