### ISSUE TITLE
HogQL custom series colors in chart tooltips

### ISSUE THREAD

**Issue by isAdrisal** [PostHog/posthog#26233]
## Bug description

#25909 by @rossgray added the ability to set custom series colours in HogQL visualisations which is great! However, those custom series colours are not reflected in the chart visualisation hover tooltips, which makes referencing the series values by colour difficult.

Screenshot showing the issue:
<img width="82" alt="Screenshot 2024-11-17 at 11 08 05" src="https://github.com/user-attachments/assets/f07fb1e0-7339-4d41-b397-a0cb00b853fb">

## How to reproduce

1. Create a HogQL visualisation
2. Set custom series colours
3. Hover your mouse over the chart and see the mismatched series colours

### Debug info

```shell
- [ ] PostHog Cloud, Debug information: [please copy/paste from https://us.posthog.com/settings/project-details#variables or https://eu.posthog.com/settings/project-details#variables]
- [ ] PostHog Hobby self-hosted with `docker compose`, version/commit: [please provide]
- [ ] PostHog self-hosted with Kubernetes (deprecated, see [`Sunsetting Kubernetes support`](https://posthog.com/blog/sunsetting-helm-support-posthog)), version/commit: [please provide]
```

**Comment by rossgray** [comment]
Thank you @isAdrisal for reporting this. I will take a look 🙂
