### ISSUE TITLE
Allow jumping into insights/trends from event view

### ISSUE THREAD

**Issue by macobo** [PostHog/posthog#2626]
## Is your feature request related to a problem?

I'm analyzing a new event. After seeing it pop up in events view, it would be great to jump straight to insights view with the event selected.

## Describe the solution you'd like

Add a button 'analyze this event' on the right of "create action from this event"

![Screenshot from 2020-12-02 12-52-25](https://user-images.githubusercontent.com/148820/100863473-48c03d00-349d-11eb-9cbe-b14912a738dd.png)

## Describe alternatives you've considered

Manually going to 'insights' and re-selecting the event

## Additional context

Came up during #2560

**Comment by paolodamico** [comment]
For inspiration if someone wants to pick it up, we already do this with feature flags.
