### ISSUE TITLE
Code blocks in Text Dashboard blocks break editing the block

### ISSUE THREAD

**Issue by darkopia** [PostHog/posthog#26285]
## Bug description

*Please describe.*
If text appears as a code block in the text element on a dashboard the lemon code block copy is on top of the 3 dot menu so that element can no longer be edited or deleted.
Example dashboard: https://us.posthog.com/project/35787/dashboard/265770

<img width="632" alt="image" src="https://github.com/user-attachments/assets/a10610ff-076c-4cca-8588-06f3f0a35663">

## How to reproduce

1. Add text block with code block formatting
2. Try and edit text block after creation
3. See copy button blocks menu

### Debug info

```shell
- [ ] PostHog Cloud, Debug information: [please copy/paste from https://us.posthog.com/settings/project-details#variables or https://eu.posthog.com/settings/project-details#variables]
- [ ] PostHog Hobby self-hosted with `docker compose`, version/commit: [please provide]
- [ ] PostHog self-hosted with Kubernetes (deprecated, see [`Sunsetting Kubernetes support`](https://posthog.com/blog/sunsetting-helm-support-posthog)), version/commit: [please provide]
```

**Comment by barronbud** [comment]
@darkopia What's the best way to get my PR reviewed?  It's my first spin at submitting code. 😬
