### ISSUE TITLE
Logout Button

### ISSUE THREAD

**Issue by Tannergoods** [PostHog/posthog#263]
**Is your feature request related to a problem? Please describe.**
I can't logout with a button on PostHog, I need to navigate to app.posthog.com/logout

**Describe the solution you'd like**
At my log in user name I should be able to select a logout button

**Describe alternatives you've considered**
Continue to navigate to app.posthog.com/logout

**Additional context**

![Posthog](https://user-images.githubusercontent.com/60791437/75726087-900f6800-5c96-11ea-8da3-52b1f5d6094a.png)

**Comment by timgl** [comment]
There's already a `/logout` path so should be pretty simple!

**Comment by jay-khatri** [comment]
@Tannergoods @timgl Hi! 

Was a little unsure on how to handle the redirect to `/logout`, as it seems this isn't an expected route on the frontend. Decided to force a page reload when the `/logout` route is visited, but happy to change things if there's another proposal.
