### ISSUE TITLE
UX for creating filters on Insights is unintuitive

### ISSUE THREAD

**Issue by jamesefhawkins** [PostHog/posthog#2631]
## Bug description

You have to click "add filter" twice to add a filter, ie:

Click here:
<img width="292" alt="Screenshot 2020-12-02 at 15 45 41" src="https://user-images.githubusercontent.com/47497682/100895494-8630c480-34b5-11eb-865a-0c8084c536b6.png">

Then you have to click 'add filter' again:
<img width="318" alt="Screenshot 2020-12-02 at 15 45 44" src="https://user-images.githubusercontent.com/47497682/100895497-8761f180-34b5-11eb-9ae8-0e4f1f36b29e.png">

## Expected behavior
 
The first 'add filter' click should pop up with the filters.

**Comment by paolodamico** [comment]
Created a new epic #2760 to rethink the entire experience, think we could close this issue and use only as reference when designing the new experience. Thoughts?

**Comment by samwinslow** [comment]
Closing because #2760 and #4050 contain additional context & we're ready to test some improvements to this experience.
