### ISSUE TITLE
Update dashboard modal is broken on the new UI

### ISSUE THREAD

**Issue by yakkomajuri** [PostHog/posthog#2632]
## Bug description

*Please describe.*  
*If this affects the front-end, screenshots would be of great help.*  

<img width="893" alt="Screenshot 2020-12-02 at 15 38 54" src="https://user-images.githubusercontent.com/38760734/100900205-81224400-34ba-11eb-8abe-7706dfb2a12b.png">

## Expected behavior

Should be a normal modal like before

## How to reproduce

1. Go to a dashboard
2. Click on a panel
3. Change the data
4. Click update dashboard

## Environment

- PostHog cloud or self-managed?
- PostHog version/commit

**Comment by paolodamico** [comment]
Could be stemming from #2606?
