### ISSUE TITLE
[UX] Allow me to copy property values that are an email or URL easily

### ISSUE THREAD

**Issue by hgezim** [PostHog/posthog#2637]
Here's my use case. Since I don't have Zapier integration *cough* *cough* yet, I've been using the Slack events to email my users.

These are my steps:

1. Get Slack message
2. Click on the email and open up the Person page.
3. Copy the email address with great difficulty.
4. Open email app and paste it in.

## Describe the solution you'd like

For fields that have a URL or email, it would be nice to have the link below the field in a link format that I can right click and copy or just click it to visit the customer's URL.

![CleanShot 2020-12-02 at 11 48 44](https://user-images.githubusercontent.com/124675/100918039-34784200-3495-11eb-809d-2565a8cbe898.png)

## Describe alternatives you've considered

See my steps above.

**Comment by manish001in** [comment]
Hey @paolodamico , thinking of picking this up, email sounds perfectly valid for URL do you think we should go for something that checks if a field is URL and provide the copy functionality or specifically find those particular fields and implement the copy functionality for it?

If we go ahead with checking each field for being a match to a URL, the code will run for every single field before showing the copy functionality.

**Comment by paolodamico** [comment]
Hey @manish001in! That's great, thanks for picking this up! I think we can have the copy for all fields, there could be IDs or other relevant texts that would be helpful to copy quickly, and we avoid the extra computation.

**Comment by manish001in** [comment]
Hey @paolodamico , I was going through the code to figure out the changes that are needed. I believe changing ValueDisplay will take care of the situation but I am a little confused in terms of how the code works in case the 'properties' value is an array or an object. 
Would really appreciate if you could give some context around this. An example would be nice as well.

As of now I believe value display element is the only one which needs to change.

**Comment by manish001in** [comment]
Also what parameters do you consider to see if using an external library is the right way to go or should a certain functionality be built inhouse?

**Comment by paolodamico** [comment]
Exactly! So you want to update the `ValueDisplay` component which is a bit tricky. What you'll want to do is when the value is a string and is not being edited, you add the copy icon with the respective logic. You'll probably want to edit line 115 for this. We already have a `CopyToClipboardInline` component so you probably don't need any external libraries.

When the properties passed are an object or array, they'll be "parsed" in the `PropertiesTable` component before a `ValueDisplay` is rendered, so you don't have to worry about that. In the end, you can expect `value` to be `string`, `number`, `null`, `boolean` or `undefined`, but not an array or an object.

Let me know if you have any other questions.

**Comment by manish001in** [comment]
Yep. After reading a bit more of the code I was able to find CopyToClipboardInline, what I dont like is that it causes a copy even if somebody clicks on the value to edit that value. So, I am trying to work a solution with `CopyOutlined` and `copyToClipboard` functionality in util.  
Hopefully will, have a working solution today and then I will raise a PR.
