### ISSUE TITLE
Improve conversion functionality for funnels

### ISSUE THREAD

**Issue by yakkomajuri** [PostHog/posthog#2642]
Spoke to a Mixpanel user yesterday that offered a great deal of good feedback. His comments about funnels were particularly interesting.

We claim feature parity when it comes to funnels, but his feedback indicated otherwise.

Actionable points for achieving parity:

- [ ] Conversion between steps built-in (not by hacking around it with separate funnels)
- [ ] Line graph of conversion over time (#1269)
- [ ] Funnel breakdowns

The second one is especially interesting. I want a nice view of my conversion over time, without having to line up funnels with different time ranges side-by-side on a dashboard. This really is key to visualizing quickly how my conversion changes with the updates to the product. 

Additional comments:

**The underlying data from datapoints isn't too useful when you have massive volumes**

@jamesefhawkins this is a point I think is worth for you to be aware of. We like to mention this in demos (and startups tend to love it) but it doesn't move the needle for users with massive scale. 

----

Wondering even if achieving true parity with funnels should be an epic.

Also tagging @fuziontech if he has anything about funnels that I missed from the call. I'll document the rest of the feedback elsewhere.

**Comment by jamesefhawkins** [comment]
> The underlying data from datapoints isn't too useful when you have massive volumes

I think it's the *form* of what you need here that changes.

Tiny startup? You want to see the 5 users that converted, or didn't.

Big company? I suspect it's about systematising this. You probably want API / export access for marketing purposes. For product purposes, I suspect being able to create cohorts of this stuff may be more useful than a massive list on clicking a data point. Some level of browsability I'd have thought _could_ still be useful but not the primary value.

**Comment by yakkomajuri** [comment]
I almost want to make this a funnels epic. More insights from other product analytics tools:

- [ ] Funnel Step Reordering (which we never merged #1245)
- [ ] Step ordering options: `any order`, `exact order`, `this order`
- [ ] Exclusion steps
- [ ] Fine-tuning conversion criteria
