### ISSUE TITLE
Bug with retention cohorts & filtering

### ISSUE THREAD

**Issue by paolodamico** [PostHog/posthog#2654]
## Bug description & expected behavior

I stumbled across this bug, when doing retention analysis. [Graph 1](https://app.posthog.com/insights?startEntity=%7B%22actions%22%3A%5B%5D%2C%22events%22%3A%5B%7B%22id%22%3A%22%24pageview%22%2C%22type%22%3A%22events%22%2C%22order%22%3A0%2C%22name%22%3A%22%24pageview%22%7D%5D%2C%22new_entity%22%3A%5B%5D%7D&returningEntity=%7B%22events%22%3A%5B%7B%22id%22%3A%22%24pageview%22%2C%22name%22%3A%22%24pageview%22%2C%22type%22%3A%22events%22%7D%5D%7D&retentionType=retention_first_time&selectedDate=2020-12-06%2006%3A00&period=w&display=ActionsTable&properties=%5B%7B%22key%22%3A%22id%22%2C%22value%22%3A71%2C%22type%22%3A%22cohort%22%7D%2C%7B%22key%22%3A%22%24current_url%22%2C%22value%22%3A%22www.posthog.com%22%2C%22operator%22%3A%22not_icontains%22%2C%22type%22%3A%22event%22%7D%2C%7B%22key%22%3A%22%24current_url%22%2C%22value%22%3A%22https%3A%2F%2Fposthog.com%22%2C%22operator%22%3A%22not_icontains%22%2C%22type%22%3A%22event%22%7D%2C%7B%22key%22%3A%22%24current_url%22%2C%22value%22%3A%22localhost%22%2C%22operator%22%3A%22not_icontains%22%2C%22type%22%3A%22event%22%7D%2C%7B%22key%22%3A%22%24current_url%22%2C%22value%22%3A%22127.0.0.1%22%2C%22operator%22%3A%22not_icontains%22%2C%22type%22%3A%22event%22%7D%2C%7B%22key%22%3A%22%24current_url%22%2C%22value%22%3A%220.0.0.1%22%2C%22operator%22%3A%22not_icontains%22%2C%22type%22%3A%22event%22%7D%5D&insight=RETENTION) is the same as [Graph 2](https://app.posthog.com/insights?startEntity=%7B%22actions%22%3A%5B%5D%2C%22events%22%3A%5B%7B%22id%22%3A%22%24pageview%22%2C%22type%22%3A%22events%22%2C%22order%22%3A0%2C%22name%22%3A%22%24pageview%22%7D%5D%2C%22new_entity%22%3A%5B%5D%7D&returningEntity=%7B%22events%22%3A%5B%7B%22id%22%3A%22%24pageview%22%2C%22name%22%3A%22%24pageview%22%2C%22type%22%3A%22events%22%7D%5D%7D&retentionType=retention_first_time&selectedDate=2020-12-06%2006%3A00&period=w&display=ActionsTable&properties=%5B%7B%22key%22%3A%22id%22%2C%22value%22%3A71%2C%22type%22%3A%22cohort%22%7D%2C%7B%22key%22%3A%22%24current_url%22%2C%22value%22%3A%22www.posthog.com%22%2C%22operator%22%3A%22not_icontains%22%2C%22type%22%3A%22event%22%7D%2C%7B%22key%22%3A%22%24current_url%22%2C%22value%22%3A%22https%3A%2F%2Fposthog.com%22%2C%22operator%22%3A%22not_icontains%22%2C%22type%22%3A%22event%22%7D%2C%7B%22key%22%3A%22%24current_url%22%2C%22value%22%3A%22localhost%22%2C%22operator%22%3A%22not_icontains%22%2C%22type%22%3A%22event%22%7D%2C%7B%22key%22%3A%22%24current_url%22%2C%22value%22%3A%22127.0.0.1%22%2C%22operator%22%3A%22not_icontains%22%2C%22type%22%3A%22event%22%7D%2C%7B%22key%22%3A%22%24current_url%22%2C%22value%22%3A%220.0.0.1%22%2C%22operator%22%3A%22not_icontains%22%2C%22type%22%3A%22event%22%7D%2C%7B%22key%22%3A%22%24active_feature_flags%22%2C%22value%22%3A%221694-dashboards%22%2C%22operator%22%3A%22icontains%22%2C%22type%22%3A%22event%22%7D%5D&insight=RETENTION) except that Graph 2 introduces an **extra filter.** However, as you can see from the screenshots below, for the weeks of Oct 24 & Oct 31, the cohort sizes are larger for Graph 2, which doesn't make sense because Graph 2 adds a constraint. At most, Graph 2's cohort sizes should equal Graph 1's.

**Graph 1.**
<img width="524" alt="" src="https://user-images.githubusercontent.com/5864173/101039145-63e48880-3541-11eb-9f26-4a63a2de3557.png">

**Graph 2.**
<img width="536" alt="" src="https://user-images.githubusercontent.com/5864173/101039247-6a730000-3541-11eb-8908-1b1fd130f6d9.png">

## How to reproduce

1. Open the graphs referenced above.

## Environment

Cloud (Clickhouse).

**Comment by EDsCODE** [comment]
This is a really interesting catch. 

I think technically speaking this is possible because what's happening is that when you do first time retention it's trying to calculate the first time a user performed that event with those filters across all time. So the extra users in the graph with more filters happens because those users might actually exist already and were grouped into previous cohorts in graph 1, but then their first event with the new filter is in a later cohort so there ends up being more in those later cohorts. lmk if this makes sense!

Nontechnically speaking, this is very counter intuitive and somehow we need to clarify what we're going for here

**Comment by EDsCODE** [comment]
@paolodamico bump

**Comment by paolodamico** [comment]
Right, the technical part makes total sense. I think we can do a few things to clarify the UX:
- On the RHS panel (where you select first time retention & the filters) we could add a legend that says something like "Filtering for users that did X action with the selected filters, for the first time".
- When hovering on the cohort size we can show a tooltip with the same information (maybe emphasize the filtering part, or even better would be listing the filters in a human-friendly way).
- When opening the persons modal (after clicking a cohort), show the same information in the header of the table.

As for the goal of this query, I think that's still a bit tricky. Basically what I wanted to answer is if users who have that feature flag active (or inactive) retain better; which means I was expecting to have the same retention table, but adding a filter on top for users with the feature flag. If the cohorts are created based on when the user first performed the action while having the feature flag active, then there's the noise of when the feature flag became active for that user, and not a very accurate retention reading. Thoughts?
