### ISSUE TITLE
Insights query returned no data after using custom date ranges and changing time buckets

### ISSUE THREAD

**Issue by macobo** [PostHog/posthog#2661]
## Bug description

Playing with time buckets and date filters can result in broken queries which return no data.

![Screenshot from 2020-12-04 10-49-43](https://user-images.githubusercontent.com/148820/101142561-71237500-361e-11eb-89b5-482ec8a95dfc.png)

## Expected behavior

This query should return data.

## How to reproduce

1. Go to insights, graph $pageview
2. Select a custom date range, e.g. 2nd to 4th december
3. Change time buckets from daily to hourly
4. See query returns no data, time range is set to today.

## Environment

Posthog cloud

## Additional context

Here's the query sent to the server - note the date_from and date_to.

```
insight: TRENDS
display: ActionsLineGraph
events: [{"id":"$pageview","name":"$pageview","type":"events","order":0}]
properties: []
date_to: 2020-12-04
date_from: dStart
interval: hour
```

This came up during #2560

**Comment by EDsCODE** [comment]
can't seem to reproduce will close for now. if it's broken reopen!
