### ISSUE TITLE
Make colors different when graphing 2 different lines

### ISSUE THREAD

**Issue by macobo** [PostHog/posthog#2662]
## Is your feature request related to a problem?

When creating a graph with two actions/events or breakdown generates 2 distinct groups, the colors used always seem to be blue.

Example: 
![Screenshot from 2020-12-04 10-56-22](https://user-images.githubusercontent.com/148820/101143297-5dc4d980-361f-11eb-8e9d-21473b7e6c78.png)

## Describe the solution you'd like

Use distinguishable colors.

## Describe alternatives you've considered

Hovering over things

## Additional context

Came up during #2560

**Comment by paolodamico** [comment]
+1 from customer call this week

**Comment by paolodamico** [comment]
@lottiecoxon might be worth giving some deep thought as to which colors we should use here. From a customer call several weeks ago we also got the feedback that the colors we're using don't have a good enough contrast ratio and are particularly hard to read for color-blind people, and particularly relevant now that you're working on a new palette.

**Comment by paolodamico** [comment]
Related to #1763.

We need to address this soon, check out this example.

<img width="506" alt="" src="https://user-images.githubusercontent.com/5864173/102288199-9f982e80-3f01-11eb-82d6-c3a743a5b753.png">

**Comment by lottiecoxon** [comment]
Hey @paolodamico sorry for the really long delay, I just realised there were a lot of mentions on GitHub that I have missed, so I will get to these all today! 

I found this article online so will work on a colour blind friendly scheme - https://venngage.com/blog/color-blind-friendly-palette/

**Comment by lottiecoxon** [comment]
Here are 4 colour schemes, laid out so you can see the 'normal' colour vision on the top level, and below how these colours are seen by people with the two most common colour blindness types. 

<img width="1440" alt="Colour Blind" src="https://user-images.githubusercontent.com/65415371/104166400-a88dfa00-53f2-11eb-9c23-2a1d16292d40.png">

**Comment by mariusandra** [comment]
Hey, this used to be fine, but something messed it up. 

For some context, we can't just hardcode colors as we'd go crazy with all the different options. We have five different backgrounds (black, white, blue, green, purple) and we need colors on all of them that look good with the background, yet different from each other. Plus we need about 20 unique colors for each of them.

I had created a system to generate any number of relatively unique colors for every background we can throw at it, but this doesn't seem to work anymore. Now every line is just blue. Thus it's a bug that needs to be fixed. I might have a look a bit later today.

**Comment by mariusandra** [comment]
All backgrounds were presumed to be white due to a bug. Now the lines on the colored backgrounds look better, though this probably doesn't fix the initial issue.
https://github.com/PostHog/posthog/pull/2911

**Comment by mariusandra** [comment]
I found a fix for the two blue lines problem as well: https://github.com/PostHog/posthog/pull/2911/commits/4c781df4ee22bd1eb49678ee107ba56b3c1e73b1

Turned out to be a 🤦

**Comment by paolodamico** [comment]
I think the immediate impact has been addressed. However I do think we still need to do a better job setting high-contrast colors, which are also as different from each other as possible. See below a graph with a simple breakdown, the gray ones are very hard to see (and it's definitely not-accessible). I do think this is a matter more on the design side than engineering.

<img width="787" alt="" src="https://user-images.githubusercontent.com/5864173/104732377-c2855080-5702-11eb-9bb0-65c17ff28801.png">

**Comment by Twixes** [comment]
New graphs have this.
