### ISSUE TITLE
Filter persons by properties

### ISSUE THREAD

**Issue by paolodamico** [PostHog/posthog#2668]
## Is your feature request related to a problem?

Currently you can only filter persons on whether they have properties (with `has:property`) or generally on whether **any** property contains the search term. This particularly does not support boolean properties, and it also matches any property.

## Describe the solution you'd like

I'd like to have the option to filter persons by any property same way we do for insights (i.e. selecting a particular property, choosing a filter type [contains, regex, starts with, ...], and setting a lookup value for that specific property).

## Describe alternatives you've considered

Filtering through the insights page and then using the user double click option to see the list of users.

**Comment by Twixes** [comment]
Now possible.
