### ISSUE TITLE
[Survey] Placeholder text of freeform input is not showing

### ISSUE THREAD

**Issue by mathisfo** [PostHog/posthog#26750]
## Bug description

_This happens in the posthog cloud dashboard_

1. If survey is multistepped, the option to set placeholder text for freeform field disappears.
2. If I remove the first question (single-choice-answer) placeholder text option reappears (but the placeholder does not show in production or in the survey preview in the dashboard). Also the input field is bugged (see video)

*If you are on PostHog Cloud it would be really valuable if you can share any links where the problem occurs. This speeds up our ability to troubleshoot tremendously.*
_implementation is authed_

## Additional context

https://github.com/user-attachments/assets/bb4b783c-7de9-4570-a960-d65a677be41f

1. trying to backspace. Once field is empty, old state is set

### Debug info

```shell
Session: https://us.posthog.com/project/sTMFPsFhdP1Ssg/replay/0193ab23-2f94-78eb-a6c3-c8c898321178?t=876
Admin: http://go/adminOrgEU/018ee151-d68a-0000-4bb6-4d3f3e1c2913 (project ID 25166)
Sentry: http://go/sentryEU/25166
```

**Comment by lucasheriques** [comment]
hey @mathisfo! should be fixed with https://github.com/PostHog/posthog/pull/27089

let me know if if happens again!
