### ISSUE TITLE
Interval rounding on trends is abnormal

### ISSUE THREAD

**Issue by EDsCODE** [PostHog/posthog#2675]
## Bug description

*Please describe.*  
- seems like a mirror of the #2650 issue
- the first interval of data has numbers that don't appear when you provide a larger range
*If this affects the front-end, screenshots would be of great help.*  

[The first period in this graph shows abnormally low number of users](https://app.posthog.com/insights?events=%5B%7B%22id%22%3A%22%24pageview%22%2C%22math%22%3A%22dau%22%2C%22name%22%3A%22%24pageview%22%2C%22type%22%3A%22events%22%2C%22order%22%3A0%2C%22properties%22%3A%5B%7B%22key%22%3A%22%24current_url%22%2C%22type%22%3A%22event%22%2C%22value%22%3A%22https%3A%2F%2Fposthog.com%2F%22%2C%22operator%22%3A%22not_icontains%22%7D%2C%7B%22key%22%3A%22%24current_url%22%2C%22type%22%3A%22event%22%2C%22value%22%3A%22https%3A%2F%2Fwww.posthog.com%2F%22%2C%22operator%22%3A%22not_icontains%22%7D%5D%2C%22math_property%22%3Anull%7D%5D&breakdown=%5B71%5D&breakdown_type=cohort&display=ActionsLineGraph&properties=%5B%5D&interval=week&date_from=-90d)

[zoomed out graph doesn't show that number
](https://app.posthog.com/insights?events=%5B%7B%22id%22%3A%22%24pageview%22%2C%22math%22%3A%22dau%22%2C%22name%22%3A%22%24pageview%22%2C%22type%22%3A%22events%22%2C%22order%22%3A0%2C%22properties%22%3A%5B%7B%22key%22%3A%22%24current_url%22%2C%22type%22%3A%22event%22%2C%22value%22%3A%22https%3A%2F%2Fposthog.com%2F%22%2C%22operator%22%3A%22not_icontains%22%7D%2C%7B%22key%22%3A%22%24current_url%22%2C%22type%22%3A%22event%22%2C%22value%22%3A%22https%3A%2F%2Fwww.posthog.com%2F%22%2C%22operator%22%3A%22not_icontains%22%7D%5D%2C%22math_property%22%3Anull%7D%5D&breakdown=%5B71%5D&breakdown_type=cohort&display=ActionsLineGraph&properties=%5B%5D&interval=week&date_from=2020-08-03&date_to=2020-12-04)
## How to reproduce

1. Look at graphs above

## Environment

- PostHog cloud or self-managed? cloud

**Comment by macobo** [comment]
cc @EDsCODE please check this

**Comment by paolodamico** [comment]
If this is leading to data integrity issues (e.g. displaying incorrect results), I think it's worth prioritizing next sprint

**Comment by EDsCODE** [comment]
yup, this is still happening for week intervals

**Comment by hazzadous** [comment]
I can't figure out how to reproduce this. The links are for last 90 days, and then a specific time range, the former is not relevant to the latter now.

There does appear to be an issue with specifying a week interval + an 8 day range over which to plot. See [here for example for 2021-09-13 to 2021-09-20](https://app.posthog.com/insights?insight=TRENDS&events=%5B%7B%22id%22%3A%22%24pageview%22%2C%22math%22%3A%22dau%22%2C%22name%22%3A%22%24pageview%22%2C%22type%22%3A%22events%22%2C%22order%22%3A0%2C%22properties%22%3A%5B%7B%22key%22%3A%22%24current_url%22%2C%22type%22%3A%22event%22%2C%22value%22%3A%22https%3A%2F%2Fposthog.com%2F%22%2C%22operator%22%3A%22not_icontains%22%7D%2C%7B%22key%22%3A%22%24current_url%22%2C%22type%22%3A%22event%22%2C%22value%22%3A%22https%3A%2F%2Fwww.posthog.com%2F%22%2C%22operator%22%3A%22not_icontains%22%7D%5D%2C%22math_property%22%3Anull%7D%5D&breakdown=%5B71%5D&breakdown_type=cohort&display=ActionsLineGraph&properties=%5B%5D&interval=week&date_from=2021-09-13&date_to=2021-09-20) which states 0 for the week of 5th Sep.

Here is with [the complete month included in the date range 2021-09-07 to 2021-09-20](https://app.posthog.com/insights?insight=TRENDS&events=%5B%7B%22id%22%3A%22%24pageview%22%2C%22math%22%3A%22dau%22%2C%22name%22%3A%22%24pageview%22%2C%22type%22%3A%22events%22%2C%22order%22%3A0%2C%22properties%22%3A%5B%7B%22key%22%3A%22%24current_url%22%2C%22type%22%3A%22event%22%2C%22value%22%3A%22https%3A%2F%2Fposthog.com%2F%22%2C%22operator%22%3A%22not_icontains%22%7D%2C%7B%22key%22%3A%22%24current_url%22%2C%22type%22%3A%22event%22%2C%22value%22%3A%22https%3A%2F%2Fwww.posthog.com%2F%22%2C%22operator%22%3A%22not_icontains%22%7D%5D%2C%22math_property%22%3Anull%7D%5D&breakdown=%5B71%5D&breakdown_type=cohort&display=ActionsLineGraph&properties=%5B%5D&interval=week&date_from=2021-09-07&date_to=2021-09-20) i.e. two weeks included.

Also, looking at interval=week and date range being one day i.e. [for just the 7th](https://app.posthog.com/insights?insight=TRENDS&events=%5B%7B%22id%22%3A%22%24pageview%22%2C%22math%22%3A%22dau%22%2C%22name%22%3A%22%24pageview%22%2C%22type%22%3A%22events%22%2C%22order%22%3A0%2C%22properties%22%3A%5B%7B%22key%22%3A%22%24current_url%22%2C%22type%22%3A%22event%22%2C%22value%22%3A%22https%3A%2F%2Fposthog.com%2F%22%2C%22operator%22%3A%22not_icontains%22%7D%2C%7B%22key%22%3A%22%24current_url%22%2C%22type%22%3A%22event%22%2C%22value%22%3A%22https%3A%2F%2Fwww.posthog.com%2F%22%2C%22operator%22%3A%22not_icontains%22%7D%5D%2C%22math_property%22%3Anull%7D%5D&breakdown=%5B71%5D&breakdown_type=cohort&display=ActionsLineGraph&properties=%5B%5D&interval=week&date_from=2021-09-07&date_to=2021-09-07) gives just under 600, but for [the whole week](https://app.posthog.com/insights?insight=TRENDS&events=%5B%7B%22id%22%3A%22%24pageview%22%2C%22math%22%3A%22dau%22%2C%22name%22%3A%22%24pageview%22%2C%22type%22%3A%22events%22%2C%22order%22%3A0%2C%22properties%22%3A%5B%7B%22key%22%3A%22%24current_url%22%2C%22type%22%3A%22event%22%2C%22value%22%3A%22https%3A%2F%2Fposthog.com%2F%22%2C%22operator%22%3A%22not_icontains%22%7D%2C%7B%22key%22%3A%22%24current_url%22%2C%22type%22%3A%22event%22%2C%22value%22%3A%22https%3A%2F%2Fwww.posthog.com%2F%22%2C%22operator%22%3A%22not_icontains%22%7D%5D%2C%22math_property%22%3Anull%7D%5D&breakdown=%5B71%5D&breakdown_type=cohort&display=ActionsLineGraph&properties=%5B%5D&interval=week&date_from=2021-09-05&date_to=2021-09-12) gives just under 1000.

Is this the abnormal behaviour referenced here?
