### ISSUE TITLE
Slow response times

### ISSUE THREAD

**Issue by hsheth2** [PostHog/posthog#2680]
## Bug description

Processing for requests is extremely slow. Some requests take up to 13 seconds to return a response. 
![image](https://user-images.githubusercontent.com/12566801/101266734-ddd26880-371f-11eb-9cd0-c51db5b554ab.png)

I'm running self-hosted within docker on an 8 core machine with ~200gb ram. Posthog's web container is basically consuming 1-2 full cores, which would be fine if it was able to respond to every request reasonably fast. 

Posthog is under reasonably high load. We've been running it for a couple days on this machine, and these are the metrics:
![image](https://user-images.githubusercontent.com/12566801/101266917-66053d80-3721-11eb-81ba-3d1737953f33.png)

## Expected behavior

Ideally it should be responding to clients within 100ms, and do the rest of its processing asynchronously. 

## How to reproduce

1. Run posthog in with docker-compose
2. Place posthog under reasonably high load

## Environment

- PostHog cloud or self-managed? self-managed
- PostHog version/commit - 1.18.0 (via docker hub's latest tag)

## Additional context

It does not seem like a resource constraint issue - the machine has plenty of CPU and memory to spare, and disk/network are not the bottlenecks (iowait and softirq are very low, max 500kb/s traffic on a 300Mb/s ethernet link).

**Comment by timgl** [comment]
Hey @hsheth2, thanks for raising this. We actually do the processing asynchronously but the library we use [is very slow](https://github.com/PostHog/posthog/issues/2560#issuecomment-737891257).  We're working on replacing LZstring with gzip for compression to make this a lot faster, and we're also working on a Go endpoint for ingestion that should be even faster. Hope that helps!

**Comment by hsheth2** [comment]
Looks like the gzip compression in v1.19.0 fixes this. Thanks!
