### ISSUE TITLE
Filtering by numbers seems broken

### ISSUE THREAD

**Issue by mvilling** [PostHog/posthog#2683]
## Bug description

I was trying to filter my events for an action / cohort by a number < X, but every time i try to create the filter i get the following error, even tho the field seems to be detected as a numeric field
<img width="796" alt="Screenshot 2020-12-07 at 10 33 02" src="https://user-images.githubusercontent.com/73826203/101334738-8d225300-3878-11eb-8293-a3f61e2b7f55.png">
<img width="957" alt="Screenshot 2020-12-07 at 10 33 43" src="https://user-images.githubusercontent.com/73826203/101334786-9d3a3280-3878-11eb-8e50-0784444f2f2a.png">

## Expected behavior

I am able to filter number fields by "greater than", "lower than"

## How to reproduce

1. Logg an event with a numeric field 
2. Try to create a filter in action / cohort which filters by the numeric field either by "greater than" or "lower than"
3. See the error in the filter box
4. After saving see that zero events match the filter 

## Environment

- PostHog cloud
- PostHog 1.18.0

**Comment by Twixes** [comment]
Hey! I don't think that's an error, since it appears you haven't put in a value in the input box where the error appears. The value the error refers to is one you need to specify.

**Comment by mvilling** [comment]
@Twixes actually i put a numeric value into that field, even tho i did so the bug still persists for me

**Comment by Twixes** [comment]
Hm, I repeated your steps and didn't experience the issue. A gif of your experience (for example made with [Gifox](https://gifox.io/)) would be tremendously helpful for us!

**Comment by mvilling** [comment]
@Twixes 
![gif](https://user-images.githubusercontent.com/73826203/101341933-1c803400-3882-11eb-9a80-f963426232d4.gif)

my orga: 01762d4b-5b1a-0000-1d2e-c5b1f42ce8c0
projectid: 1117

**Comment by Twixes** [comment]
Thank you! Though unfortunately I'm unable to reproduce this… Not sure what's up.

**Comment by mvilling** [comment]
@Twixes tried it with a fresh installation on premise and its working now. Im happy to close the issue

**Comment by Twixes** [comment]
Great to hear that it's not an issue!
