### ISSUE TITLE
Reduce the noise of the many `null` values in person and event detail views

### ISSUE THREAD

**Issue by daniloc** [PostHog/posthog#26846]
## Is your feature request related to a problem?

`null` values add noise to person and event detail views. I find it makes it hard to find the data I'm looking for when I have to parse all these nothing values and skip them:

<img width="746" alt="Screenshot 2024-12-10 at 1 06 31 PM" src="https://github.com/user-attachments/assets/3a942928-85fb-4ae0-90f5-67b9e17c89e8" />

## Describe the solution you'd like

Some means of grouping set, non-null values so they can be skimmed, without the data being Swiss-cheesed by nulls:

- Section the table, putting all un-set, null values in a section at the bottom
- An extra toggle, like `Hide PostHog properties`, which just hides them (and is checked by default)

**Comment by daniloc** [comment]
Heh: https://github.com/PostHog/posthog/pull/26845

**Comment by rafaeelaudibert** [comment]
Closed by #26845 :)
