### ISSUE TITLE
Give me a filter option for "start with"

### ISSUE THREAD

**Issue by hgezim** [PostHog/posthog#2691]
It's quite annoying having to do this to change my URL:

https://cln.sh/C0EQxQ

The automatically placeholder replacement behavior is the opposite of helpful.

**Comment by paolodamico** [comment]
+1, easier to have a specific filter for this than typing regex queries.

<img width="773" alt="" src="https://user-images.githubusercontent.com/5864173/101524014-03918480-394f-11eb-8998-40ad3d13d2d5.png">
