### ISSUE TITLE
Handle incorrectly formatted payloads on /capture

### ISSUE THREAD

**Issue by paolodamico** [PostHog/posthog#2705]
## Is your feature request related to a problem?

When sending incorrectly formatted payloads (e.g. a text-based string with a `gzip` compression header), the app will fail with a cryptic 500 error and register an unhandled exception.

## Describe the solution you'd like
The app should return a 400 bad request error, with details on why the request failed (i.e. it is incorrectly formatted or the content does not match the compression specified). In addition, this shouldn't be treated as an unhandled exception as it's a client error.

## Describe alternatives you've considered
Keep returning a cryptic 500 error.

## Additional context
Relevant context on #2701

**Comment by macobo** [comment]
> In addition, this shouldn't be treated as an unhandled exception as it's a client error.

We've had bugs in the past in our clients which resulted in them sending us incorrect data. By ignoring the exception here we won't discover these bugs and won't be able to patch them as they would not reach sentry.

I also imagine it will become harder to integrate us for new companies as well - their custom calls would get swallowed without information in the logs.

**Comment by paolodamico** [comment]
100% agreed, I didn't mean we should stop tracking it on Sentry, but rather that it should be handled in a way that a useful response is returned to the client and then the exception can be logged to Sentry in the backend.

Somewhat related, I'm thinking that returning a useful exception to the client will result in the exception being logged to Sentry from the client side, which might be cleaner as it's a client issue. 

Regardless, I think properly returning a verbose and useful response should be a huge improvement here. Thoughts?

**Comment by macobo** [comment]
Sounds good, just wanted to bring out some implicit requirements :)
