### ISSUE TITLE
Editor styles broken if not using bootstrap

### ISSUE THREAD

**Issue by mariusandra** [PostHog/posthog#271]
Hi all, the editor looks sad when clicking "select element on site" and going to an app that does not use bootstrap for styles.

![image](https://user-images.githubusercontent.com/53387/75874833-dab5ef00-5e12-11ea-8a63-05e1b9c3c27c.png)

**Comment by mrsweaters** [comment]
I'm not experiencing the same issue on our site and we don't use bootstrap. Are you using the docker version of Posthog? 
<img width="313" src="https://user-images.githubusercontent.com/535897/75933966-1ca15e00-5e30-11ea-8d81-ab6507bedd8c.png">

**Comment by timgl** [comment]
I think this happens when you're running PostHog locally, and then open the editor in a live app. I don't know if that's solvable, or whether we should just display a warning (like "you're running PostHog locally, that means the editor won't work")

**Comment by timgl** [comment]
I think this is fine now as we're loading bootstrap locally?
