### ISSUE TITLE
React Native Web Support

### ISSUE THREAD

**Issue by agrittiwari** [PostHog/posthog#27105]
## Is your feature request related to a problem?

Yes, We at our company building a cross-platform app, now that web build is going to release on a single codebase, It makes obvious sense to have the activity on web to be sent to Posthog as well.

## Describe the solution you'd like

I'd like to have Posthog provide support to React native web in the same sdk.

## Describe alternatives you've considered
My alternative is to write the plaform based code throught out the codebase, meaning installing 2 posthog libraries for the same codebase, so that one resolves for one product on web and another for android and iOS, which is wonderfully supported.

## Additional context

It is in posthog interest to have the support for reactnative web as well. As more and more apps are going to cross-platform, with expo-router, posthog sdk for react native should be the one stop solution for react-native devs, targeting muliple platforms

**Comment by marandaneto** [comment]
RN web is already supported https://posthog.com/docs/libraries/react-native#react-native-web-and-macos
