### ISSUE TITLE
Separate Lifecycle from Trends

### ISSUE THREAD

**Issue by Twixes** [PostHog/posthog#2712]
## Is your feature request related to a problem?

Lifecycle analytics is much different from Trends. It is specifically based on unique users (as opposed to raw events), can't be presented more than one series at a time, breakdowns don't apply to it and it doesn't make sense to show it as anything other than a bar graph.
Also, discoverability is low currently. I had trouble finding the feature, because the "Shown as" option is not prominent at all.

## Describe the solution you'd like

Lifecycle should have its own Insights tab, with only the relevant options. That would also make it much more prominent.

**Comment by paolodamico** [comment]
+1, it's quite confusing to see it there, plus it doesn't have a ton of discoverability. Think adding it as a separate tab is the right approach for now (might be worth rethinking the tab structure at some point if we keep adding a ton more types of insights, but that's a discussion for another day).

**Comment by Twixes** [comment]
Resolved with #2899.
