### ISSUE TITLE
Bug with setting an HTML selector in actions

### ISSUE THREAD

**Issue by paolodamico** [PostHog/posthog#2718]
## Bug description

Seems like recently something changed that now if you try to set up an HTML selector when creating/updating an action, it won't get saved.

## Expected behavior

Selector should be saved.

## How to reproduce

1. Create an action.
2. Set anything in the HTML selector field and save.
3. Refresh and see the selector gone.

## Environment

Cloud.

## Additional context

Noticed during the review of #2711

**Comment by yakkomajuri** [comment]
#2746 fixes this
