### ISSUE TITLE
Create n8n app for PostHog

### ISSUE THREAD

**Issue by hgezim** [PostHog/posthog#2720]
[n8n](https://n8n.io/) is to Zapier what PostHog is to HotJar.

It seems it's much more capable and more developer friendly than Zapier and they just released a cloud version (https://www.n8n.cloud).

I'd love to be able to work with PostHog and n8n!

**Comment by yakkomajuri** [comment]
Happening:

https://twitter.com/tanay1337/status/1360148200045355008

**Comment by paolodamico** [comment]
Integration is now fully live, https://n8n.io/integrations/n8n-nodes-base.postHog
