### ISSUE TITLE
Bug/UX issue with table views

### ISSUE THREAD

**Issue by paolodamico** [PostHog/posthog#2722]
## Bug description

Think this is more of a UX issue than a bug, when I use the same query (active users) but switch between different timeframes on a table view, the numbers change.

See [query](https://app.posthog.com/insights?actions=%5B%5D&events=%5B%7B%22id%22%3A%22%24pageview%22%2C%22name%22%3A%22%24pageview%22%2C%22type%22%3A%22events%22%2C%22order%22%3A0%2C%22math%22%3A%22dau%22%7D%5D&new_entity=%5B%5D&properties=%5B%7B%22key%22%3A%22%24current_url%22%2C%22value%22%3A%22app.posthog.com%22%2C%22operator%22%3A%22icontains%22%2C%22type%22%3A%22event%22%7D%2C%7B%22key%22%3A%22id%22%2C%22value%22%3A71%2C%22type%22%3A%22cohort%22%7D%5D&display=ActionsTable&date_from=-90d&interval=month).

**Daily**
<img width="1098" alt="" src="https://user-images.githubusercontent.com/5864173/101695153-c5bd5a80-3a39-11eb-8be0-5341db01b037.png">

**Monthly**
<img width="1326" alt="" src="https://user-images.githubusercontent.com/5864173/101695141-c3f39700-3a39-11eb-9344-28a3d57dd0e3.png">

## Expected behavior

The ideal would be that the table view show a row for each timeframe step (e.g. for daily, it would show a list of days) and the relevant count for each row. We would then show the total sum (and maybe even the arithmetic mean) at the bottom.

At the very least I would expect that if we only show one row, it would be the total number of unique users, not the sum of unique users depending on each period.

## How to reproduce

See above.

## Environment

Cloud.

**Comment by EDsCODE** [comment]
Yeah this is very misleading. We should think about how we can reframe some of these metrics. There's now a bunch of analytics that turn on and off various configurations. Often it's only a few filters so it doesn't seem like it warrants a different insight tab but we might need to rethink that as it gets really confusing and prone to implementation errors like above

**Comment by Twixes** [comment]
Interval selector is not available for table viz now.
