### ISSUE TITLE
Allow opening "View graph" from dashboard in a new tab

### ISSUE THREAD

**Issue by macobo** [PostHog/posthog#2725]
## Is your feature request related to a problem?

I want to quickly edit or investigate a lot of the graphs on my dashboard - open some in a new tab. 

ctrl+clicking view graph opens the insights page on the same tab

## Describe the solution you'd like

ctrl+click behaves like everywhere else

## Describe alternatives you've considered

Clicking back many times after changing insights graph

## Additional context

Slight pain since Menu.Item is not a Link.

**Comment by Twixes** [comment]
This was resolved some time ago.
