### ISSUE TITLE
(Pre-) release 1.20.0

### ISSUE THREAD

**Issue by timgl** [PostHog/posthog#2733]
For this planning session, we only have a full week until christmas/new year etc so this might not be a full session. Context to decide what to work on:

- We have customers waiting for things like BigQuery and Snowflake integrations, which will require plugins to work
- We've had a few outages and in general CH performance has been lagging. We have a plan for a lot of this
- It would be good to spend _some_ time this week coming up with ambitious ideas for next year

Eric/Tim:
- Finish backend filter refactor
- Filter typing for frontend
- Consistent backend tests
- Finish insights history
- Good error messages for timeouts (ie push to upgrade instance or contact support)

Marius/Michael:
- Plugins on app
- React native fix
- BigQuery and Snowflake plugins
- Stretch: Some UX improvements for plugins

James
- Parts on the merge-tree
- Migrate stuff off of Heroku
  - Plan for moving of Postgres
- Get the CH tables distributed
- Load balance CH
- Plan for CH tables
- Document all of it in terraform

Paolo
- Instrumentation across the app
- Personas stuff

Support Hero: Karl
- Filters
- Sentry issues and resolving + fixing as appropriate
- https://github.com/PostHog/posthog-js/issues/155 if time

**Comment by macobo** [comment]
A few fun/rewarding things I'm interested in outside the current work:
- https://github.com/PostHog/posthog-js/issues/155 Dropping all the things.
- /s and /e endpoints in go together with benchmarks. From https://github.com/PostHog/posthog/issues/2560 this would increase session recording reliability
- https://github.com/PostHog/deployment/issues/40 is useful for opening up ph for connecting with metabase.

If nothing else improved sessions filtering needs work as well.

**Comment by paolodamico** [comment]
From the last release, I suggest keeping the data instrumentation piece to have more reliable numbers as we work through retention optimization. I'd also like to start working on some retention stuff to identify our key personas that we retain best.

**Comment by Twixes** [comment]
Closing in favor of #2842.
