### ISSUE TITLE
Show data on hover for line graphs.

### ISSUE THREAD

**Issue by tdhartwick** [PostHog/posthog#275]
**Is your feature request related to a problem? Please describe.**
I'm hovering over  a graph on the Dashboard and I'm not seeing the values that are plotted... just the dates.

**Describe the solution you'd like**
When hovering over a data point on a graph, I'd like to see the y-axis value as well.

**Describe alternatives you've considered**
I checked the different settings in the graph output and couldn't find anything.

**Additional context**
Here's a screenshot **I'd expect to see a specific number i.e. 1,733** not just the date :/

![Screen Shot 2020-03-04 at 4 17 16 PM](https://user-images.githubusercontent.com/7873403/75935268-a272d880-5e33-11ea-9bc5-565675cea9dc.png)

**Comment by timgl** [comment]
@tdhartwick Thanks for creating this issue. I was thinking the exact same thing earlier today! That's fixed now :)

**Comment by tdhartwick** [comment]
Thanks @timgl! Keep up the great work!!
