### ISSUE TITLE
Cohorts time filter not working

### ISSUE THREAD

**Issue by yakkomajuri** [PostHog/posthog#2751]
## Bug description

*Please describe.*  
*If this affects the front-end, screenshots would be of great help.*  

Setting a cohort with a time filter e.g. `user performed action in the last 7 days` has no effect.

The above gives the same result as `user performed action in the last month` and `user performed action`. I can assure that for the specific action I was testing those numbers should be different.

## Expected behavior

Time filters should work

## How to reproduce

1. Create a cohort with a time filter
2. Change/remove the filter
3. Nothing changes 

## Environment

- PostHog cloud or self-managed?
- PostHog version/commit

**Comment by EDsCODE** [comment]
#3056 solved this
