### ISSUE TITLE
Pagination in 'identified' tab in persons removes 'identified' filter

### ISSUE THREAD

**Issue by jamesefhawkins** [PostHog/posthog#2752]
## Bug description

* Go to /persons
* Click 'identified'
* Scroll to bottom to look at more identified users
* Click pagination
* You now see non-identified and identified users

## Expected behavior

* On clicking pagination to see the second page of identified users

## Environment

PostHog Cloud

**Comment by paolodamico** [comment]
Relevant issue context, https://github.com/PostHog/posthog/issues/1764#issuecomment-740684999
