### ISSUE TITLE
New persons page CSS issue on small screen widths

### ISSUE THREAD

**Issue by jamesefhawkins** [PostHog/posthog#2753]
## Bug description

<img width="547" alt="Screenshot 2020-12-14 at 16 16 12" src="https://user-images.githubusercontent.com/47497682/102106097-15c86280-3e28-11eb-923b-29b818c3a60b.png">

## Expected behavior

Below a certain width, perhaps the user properties should just go ahead of their event history.

(@paolodamico FYI)

**Comment by paolodamico** [comment]
Thanks for the quick feedback! Will address this as part of the PR I'm working on.

**Comment by Twixes** [comment]
This page now looks much better since it's been redesigned.
