### ISSUE TITLE
Trigger action / plugin after first event triggered

### ISSUE THREAD

**Issue by weyert** [PostHog/posthog#2759]
## Is your feature request related to a problem?

I would like to be able to trigger an action when a first event gets triggered for a user. For example, you might have a wizard that's should only be shown when the user does a specific step, e.g. create a first post. A feature flag could be active for this user as long the first event has not occurred yet.

## Describe the solution you'd like
I would love to be able to say 'when event [Post Created] happens for the first time then do [trigger action/hook]

## Describe alternatives you've considered
I have considered whether plugins might be possible solution for this by watching for the event 'Post Created' to happen and when it occurs query all events for the user and try to filter out for this specific event 'Post Created', if so, do something. Maybe enable a 'Hide Wizard'-feature flag or something.

## Additional context
None

**Comment by mariusandra** [comment]
Could this plugin solve the issue? 

https://github.com/PostHog/first-time-event-tracker

**Comment by weyert** [comment]
Perfect! Thank you 🎉
