### ISSUE TITLE
Suggest interesting sessions

### ISSUE THREAD

**Issue by paolodamico** [PostHog/posthog#2761]
## Is your feature request related to a problem? Alternatives you've considered?

A [user](https://docs.google.com/document/d/1gJlsUDrlW7ur8zT5scqRvXZhapm_0JdvKGiw68Iyx9E/edit#heading=h.uxf2ltfknjyc) suggested adding a pretty cool feature to session recording: suggesting "interesting" session recordings to watch based on some heuristics (e.g. showing sessions were users rage clicked, or for some drops in conversion, etc.)

Another interesting approach would be to create these suggestions using a heuristic based on what the user watched (basically using a basic algorithm of what Youtube does to maximize engagement). We could also consider adding a star-based or thumbs-up/thumbs-down feedback mechanism after watching session recordings to improve the algorithm. 

We could also rely on #2132 to identify certain relevant sessions for users.

**Comment by macobo** [comment]
Question: How is a rage click defined?

If we figure out a good definition, we can add it to posthog-js autocapture and implement this as part of the improved filtering?

**Comment by paolodamico** [comment]
> Question: How is a rage click defined?
Agree with the proposed solution on #2772, think we can continue that conversation there.

**Comment by paolodamico** [comment]
Did a deep dive today on session recording usage because as of last week, we no longer have ~90%+ feature retention of our users in this feature (plus [growth staled](https://app.posthog.com/insights?actions=%5B%7B%22id%22%3A2418%2C%22math%22%3A%22dau%22%2C%22name%22%3A%22User%20viewed%20session%20recording%22%2C%22type%22%3A%22actions%22%2C%22order%22%3A0%2C%22properties%22%3A%5B%5D%2C%22math_property%22%3Anull%7D%2C%7B%22id%22%3A2428%2C%22math%22%3A%22dau%22%2C%22name%22%3A%22Used%20PostHog%22%2C%22type%22%3A%22actions%22%2C%22order%22%3A1%2C%22properties%22%3A%5B%5D%2C%22math_property%22%3Anull%7D%5D&display=ActionsLineGraph&insight=TRENDS&interval=week&date_from=-90d&properties=%5B%7B%22key%22%3A%22id%22%2C%22type%22%3A%22cohort%22%2C%22value%22%3A71%2C%22operator%22%3Anull%7D%5D#fromItem=49924&fromItemName=Session%20recording&fromDashboard=1124) a bit).

Taking the week of Nov 22 (highest usage peak), and analyzing the users that did not come back to the feature for the next 2 weeks, I found the following:
1. 42% of users ended up coming back after 3 weeks. This would suggest that either the use case / problem is not as frequent or we're not driving enough engagement for the feature. Given that most of these users do use the product at least once every week, it suggest that we fall into the second assumption.
2. 37% of users that didn't come back weren't seen at all in PostHog in the last 2-3 weeks. This suggest that the feature is not powerful enough to drive these users back. However, it's worth noting as these users did not come back to PostHog, these may be outside the scope of this particular feature optimization and be a conversation more for general retention.
3. We did see a drop on real users (albeit very few in absolute numbers ~5 users). I've reached out to a couple to try to understand what happened.

**Disclaimer:** Be mindful that absolute numbers are still low.

### Next steps
1. This issue fits perfectly to address this point. We could consider a more basic version of just prompting the user to get back to session recordings once a week, but this doesn't seem quite useful nor drive strong value.
2. Treat as a general retention optimization problem.
3. Individually understand what lead these users to drop session recording usage.

4. We're also waiting on #2794 to understand this through the recurring retention graph perspective.

**Comment by jamesefhawkins** [comment]
In addition to the discussion above, similar to rage clicks, Sentry integration/errors could be a good way of highlighting relevant videos.

**Comment by paolodamico** [comment]
Maybe still relevant to the diagnosis conversations we're having? CC @marcushyett-ph

**Comment by marcushyett-ph** [comment]
100%

**Comment by paolodamico** [comment]
A lot of stuff that we're doing around quant analysis & paths will accomplish this.
