### ISSUE TITLE
Plugin Editor needs a built-in testing tool

### ISSUE THREAD

**Issue by yakkomajuri** [PostHog/posthog#2768]
## Is your feature request related to a problem?

*Please describe.*

## Describe the solution you'd like

To be more useful than frustrating, I think the plugin editor would need a "test" or "dry run" mechanism where it runs a test event by the plugin and shows me the resulting event (scheduled plugins aside). This is what RudderStack does (haven't checked Segment but would assume that much) and it makes building the plugin much easier.

**Comment by Twixes** [comment]
From our planning today, we arrived at the idea of running this locally browser-side. Will require some functionality mocked, some imports polyfilled and maybe something more advanced restricted, but saves us from a lot of server side work on safety, particularly on Cloud.

**Comment by mariusandra** [comment]
The only way this will be usable (vs frustrating because of lack of x, y, and z) is via something like this: https://blog.stackblitz.com/posts/introducing-webcontainers/ . If that's technically feasible I don't know. It might be worth a small investigation though.
