### ISSUE TITLE
Track user feedback

### ISSUE THREAD

**Issue by jamesefhawkins** [PostHog/posthog#2771]
## Is your feature request related to a problem?

We currently capture user feedback in a google doc.

We also get some level of feedback in places like github issues, slack, email and Hubspot.

This means:

* Zero or limited profile or company level data
* No integration with the product, so I can't easily see which key features they are using / not using
* Feedback isn't consolidated across lots of places so I can't see all of it in one place 

## Describe the solution you'd like

We (and thus our users), could be taking a more customer centric approach to our development.  Something like (starting at the bottom, working to the top):

<img width="540" alt="Screenshot 2020-12-15 at 13 03 31" src="https://user-images.githubusercontent.com/47497682/102218494-f0922d80-3ed5-11eb-907f-fb82e492641c.png">

Whereas I suspect this is a little more common:

<img width="570" alt="Screenshot 2020-12-15 at 13 09 38" src="https://user-images.githubusercontent.com/47497682/102219040-d147d000-3ed6-11eb-8825-7dfb2c89fe8d.png">

Something like:

* Enable somewhere to store feedback manually at a user or company level in the product.
* Enable manual editing of user and company properties so I can add labels like Job Title manually whilst I'm on a call.
* Integrations with other tools (GitHub/Slack/Email/Hubspot all feel like there would be other use cases too) should have some way of tagging / connecting up feedback so I can read it all in PostHog.

## Describe alternatives you've considered

The solution we have is ok but it involves a lot of manual work and we probably miss a bunch of insight and make the wrong product decisions.

## Additional context

Pendo has some interesting functionality around this.

It feels like we should validate this on some user calls using the techniques from the Mom Test.

**Comment by paolodamico** [comment]
Great idea on this! Execution sounds tricky, having the insights on a company/user level is quite powerful for customer success and sales (and even some product personas stuff), but it's quite hard to use for feature development (e.g. if I'm working on improving session recording I would want to get all feedback related to session recording). Maybe a solution for this could be registering feedback on a user-level but then being able to add tags inline that can be easily queryable later? (like [Agenda](https://agenda.com/)).

A separate point is that this should be insanely easy to use, very intuitive and geared for power usage. If it takes much time to register feedback, it'll start to backlog and it won't be as useful. For context, after a 30 min call with a user, it takes me anywhere from 7 to 15 minutes to organize and clean up the feedback (plus open or comment on any relevant issues), a big part of this is finding the right issue but that would be outside the scope of this.

Feel a bit concerned we're going too broad by adding this functionality directly on the app. On the other hand, having something that solves for this would be amazing.

**Comment by paolodamico** [comment]
As I'm going right now through customer feedback, I'm thinking that if we don't decide to implement something, we could try using Notion for this. One of the key features we're lacking from Google Docs is being able to link to a specific line to provide more relevant feedback on issues.

**Comment by paolodamico** [comment]
Superseded by #2880, but great context on this issue for it.
