### ISSUE TITLE
Smart/proactive analytics alerts

### ISSUE THREAD

**Issue by paolodamico** [PostHog/posthog#2773]
## Is your feature request related to a problem?

This has been brought up before by a couple of users where they wanted to have certain alerts when something that was not part of regular business occurred on PostHog (e.g. conversion drop fell below certain level or unusually high number of `$exceptions`.

## Describe the solution you'd like

Taking the above one step further we can optimize PostHog to provide smart recommendations for certain insights and then have an inbox or other mechanism for users to review important updates continuously. This will not only drive a lot more value to users but could also help us increase engagement.

## Describe alternatives you've considered

Allowing the user to manually set some threshold notifications (like you do on APMs) and alerting based on changes to those alerts.

**Comment by paolodamico** [comment]
Another relevant point from [user feedback](https://docs.google.com/document/d/1gJlsUDrlW7ur8zT5scqRvXZhapm_0JdvKGiw68Iyx9E/edit#heading=h.ix5nkxvnbdtz), onboarding section.

**Comment by paolodamico** [comment]
Another [user](https://docs.google.com/document/d/1gJlsUDrlW7ur8zT5scqRvXZhapm_0JdvKGiw68Iyx9E/edit#heading=h.jc9thlt4k0t7) mentioned wanting to receive periodic emails with "relevant updates".

**Comment by macobo** [comment]
:thinking: Datadog has this: https://www.datadoghq.com/blog/forecasts-datadog/ and https://www.datadoghq.com/blog/introducing-anomaly-detection-datadog/

So:
1. Decide on key metrics/graphs you want to follow. This might be useful for say weekly email as well.
2. Predict the future (with confidence intervals)
3. Alert if out of bounds.

We could start capturing $exception events always even w/o sentry (just integrating sentry gives extra info). :thinking:

**Comment by paolodamico** [comment]
Another interesting reference from GA, https://support.google.com/analytics/answer/9443595?hl=en

**Comment by paolodamico** [comment]
Another interesting approach to consider here (from a user suggestion) would be to able to define some relevant events/actions where we can get automatic notifications when there's an unusual discrepancy. For example, if I care about my activation funnel conversion, I might get automatically alerted if the funnel drops below a certain threshold in any given day. We could even add some interesting granularity, like "your funnel dropped x% for users in Safari since yesterday".
