### ISSUE TITLE
Improve authorized domains experience

### ISSUE THREAD

**Issue by paolodamico** [PostHog/posthog#2775]
## Is your feature request related to a problem?

From a [customer call](https://docs.google.com/document/d/1gJlsUDrlW7ur8zT5scqRvXZhapm_0JdvKGiw68Iyx9E/edit#heading=h.ix5nkxvnbdtz), the authorized domains experience is confusing. You delete domains and they come back. Expected authorized domains to serve as blocking incoming event traffic from certain sources (e.g. testing environments).

## Describe the solution you'd like

- Make authorized domains clearer. Ideally we would allow a user to granularly enable a domain/URL for each specific feature (toolbar, session recording, event ingestion).
- We should keep a record of deleted domains/URLs (maybe keep a hash), so that if it comes back we can block it and don't show it again.
    - Related to the above, we could allow users to either have the domain but with every feature turned off (like if it was blocked), or removed (as in I don't want to see it again).

## Describe alternatives you've considered

See above.

## Additional context

This is still a concept in progress, feedback/ideas highly welcomed!

**Comment by clarkus** [comment]
This workflow shows up in multiple places in slightly different ways. The toolbar configuration is essentially a standalone authorized urls/domains management interface. If you go to project settings, you can see the same interface with slightly different button labels. Both sections throw errors when you try to remove an authorized URL.

<img width="249" alt="Screen Shot 2022-06-07 at 1 56 45 PM" src="https://user-images.githubusercontent.com/254612/172481364-f6c52b96-1b66-41d8-8478-5da2b2d48859.png">
