### ISSUE TITLE
Add user property $distinct_id

### ISSUE THREAD

**Issue by paolodamico** [PostHog/posthog#2776]
## Is your feature request related to a problem?

If I want to create a cohort based on a determined set of users, I may want to use their distinct IDs to do so.

## Describe the solution you'd like

I'd like to have the option of filtering users by `$distinct_id` in all places where filtering by user property is possible.

## Describe alternatives you've considered

If there's another key user property (e.g. email) this might be possible, but for users that only use anonymized IDs, there is no alternative.

## Additional context

Came from a [customer call](https://docs.google.com/document/d/1gJlsUDrlW7ur8zT5scqRvXZhapm_0JdvKGiw68Iyx9E/edit#heading=h.vzc1suqo002t)

**Comment by paolodamico** [comment]
Requested by [another user](https://posthogusers.slack.com/archives/C01GLBKHKQT/p1608320699017600)

**Comment by paolodamico** [comment]
This has been already addressed.

**Comment by oribenez** [comment]
Same here
