### ISSUE TITLE
Toolbar experience for non-toolbar users

### ISSUE THREAD

**Issue by paolodamico** [PostHog/posthog#2777]
## Is your feature request related to a problem?

There are some cases where users are unable to use the toolbar. The most common one is if you don't have the snippet/JS library (or any front-end events at all). If this is the case, it's a bit distracting/annoying and even concerning to see the floating toolbar prompt come up.

## Describe the solution you'd like

If there are no frontend events which the toolbar can use, do not show the floating thing. We can still keep the menu item as a CTA to take actions for the toolbar to work.

Related to the above, we should show a CTA with clear instructions on how to address enabling the toolbar (i.e. likely adding the snippet or JS library to the frontend, or enabling `$autocapture` if disabled).

## Additional context

Related to [customer call](https://docs.google.com/document/d/1gJlsUDrlW7ur8zT5scqRvXZhapm_0JdvKGiw68Iyx9E/edit#heading=h.vzc1suqo002t)

**Comment by macobo** [comment]
Idea: on clicking `x` for the toolbar, prompt to dismiss it 'forever' (for this user), then say "you can always re-enable it from settings". :) And add a toggle under settings.

**Comment by clarkus** [comment]
Related https://github.com/PostHog/posthog/issues/4268 - There is a toggle for disabling the toolbar here. Would that qualify as a solution here or is the core problem exposing this setting in the context of the toolbar?

**Comment by paolodamico** [comment]
User reported wanting to disable the toolbar for themselves but not for the entire project which wouldn't be covered by this.

**Comment by clarkus** [comment]
> User reported wanting to disable the toolbar for themselves but not for the entire project which wouldn't be covered by this.

So given that, there should be two settings. One to enable the toolbar for the project, but secondarily to enable it for a specific user account?

**Comment by paolodamico** [comment]
So I’m actually not sure that’s the best thing to do, just wanted to put all the context I had forward. Perhaps one option is to have a single project setting but we let you permanently dismiss the toolbar when you click the close button. If you permanently dismissed the toolbar, we give you an option to re-enable it in settings.

**Comment by macobo** [comment]
Idea: "x" on the hedgehog on site. If clicked, asks if to permanently disable, but says you can always re-enable by launching it via app.posthog.com.

**Comment by paolodamico** [comment]
Yup 100%, exactly what I meant. Though if you permanently dismiss it I think it should only apply for your user not your project right ?

**Comment by clarkus** [comment]
Yeah my comment was more about the places where a user can change this in settings. It'd be totally fine to changes those settings or to prompt to change them when interacting with the toolbar. I was mostly thinking about the other case where the toolbar is enabled for the project, but disabled for a user, and a user needed to know how to re-enable the toolbar. A single setting at the project level wouldn't be sufficient for that.

**Comment by paolodamico** [comment]
Well that ends up being connected to what we do with the settings page but indeed we need a separate user-level setting for that. One UX thing that I think makes sense is only showing that extra config if you have permanently disabled the toolbar (i.e. you can only disable by clicking the close button)

**Comment by clarkus** [comment]
Here's an illustration of a possible solution. In this case, on dismiss we prompt the user to disable the toolbar for their User Account. Thoughts?

![Disable toolbar prompt](https://user-images.githubusercontent.com/254612/128071565-e06d96c9-d4cd-46b2-bab6-cd07e627ce81.png)

**Comment by paolodamico** [comment]
Yes, pretty close though I think we need to have 3 buttons: "Cancel", "Dismiss forever" and "Close for this session" (primary) [exact copy to be adjusted]. It might also be worth to have a "Don't ask me again" checkbox for option 3 (primary).

**Comment by clarkus** [comment]
Is the task dismissing the toolbar or disabling it? To me, dismiss means stop showing this, but disable means never show it again (unless I turn it back on in settings). The close action on the toolbar is the "dismiss" portion, and the follow up prompt is the "for how long" portion of the interaction. 

👍 on the "don't ask me again" checkbox. 

<img width="642" alt="Screen Shot 2021-08-05 at 8 39 21 AM" src="https://user-images.githubusercontent.com/254612/128379221-d6d2a6fe-3169-441d-bb78-ab862992e37a.png">

**Comment by paolodamico** [comment]
Yes agreed! Disabling is "permanent", dismissing is temporary (i.e. this session), but you trigger either by clicking on the same close icon button, that's why I was suggesting the 3 buttons. The thing is that once you have the dialog, clicking on cancel to only dismiss temporarily seems confusing, as cancel could simply entail go back and don't actually close the toolbar.

**Comment by clarkus** [comment]
Good catch. We're not letting them cancel out of the dismissal, we're just confirming it. What do you think of these changes?

<img width="636" alt="Screen Shot 2021-08-05 at 1 57 32 PM" src="https://user-images.githubusercontent.com/254612/128420186-c355bf4c-e937-4687-bf4d-d71702ab5cd7.png">

**Comment by paolodamico** [comment]
Love it! One final suggestion if I may. Feels like the primary action should be just dismiss on this session rather than fully disable (is at least something we'd like to encourage I think). Wdyt?

**Comment by clarkus** [comment]
Sure! <img width="956" alt="Screen Shot 2021-08-05 at 2 06 24 PM" src="https://user-images.githubusercontent.com/254612/128421224-17521cc5-e57e-42f6-bfd2-c87ba1b88008.png">

Available in figma at https://www.figma.com/file/9yWtngNb1AIuf6KmXaEPJA/App-doodles?node-id=900%3A140805

**Comment by clarkus** [comment]
Related https://github.com/PostHog/posthog/issues/2370

**Comment by corywatilo** [comment]
My thoughts on _disabling_ vs _dismissing_:

I don't know if we need to disable it, to the extent you have to go back into Settings to re-enable. What seems like a simpler UX is, once you click X to dismiss it, it just doesn't re-appear until you go to the Toolbar and re-launch it on the domain where it was previously dismissed. Then it would stick around until you X it out again.

**Comment by pauldambra** [comment]
> once you click X to dismiss it, it just doesn't re-appear until you go to the Toolbar and re-launch it on the domain where it was previously dismissed.

that's how it works now
