### ISSUE TITLE
Improve UX timezone support

### ISSUE THREAD

**Issue by paolodamico** [PostHog/posthog#2778]
## Is your feature request related to a problem?

When using PostHog, if you're particularly sensitive to specific time of day stuff, there's no clear indication of which timezone is being used. Further, there's some suspicion that we might be mixing timezones in different parts of the app.

## Describe the solution you'd like

Ideally we would allow each user to set their preferred timezone (maybe on the org, project or user level; open to discussion), and then for each time in the app we would do something like Stripe does (see screenshot below). The UTC conversion is relevant for our more technical users who may be using it to compare stuff with other data sources.

<img width="400" alt="" src="https://user-images.githubusercontent.com/5864173/102266813-93e74080-3ede-11eb-8b97-ac3f347658a9.png">

## Describe alternatives you've considered

Just allowing the selection of a timezone for each user and showing datetimes only in that timezone.

## Additional context

- Related to #2676.
- Came from a [customer call](https://docs.google.com/document/d/1gJlsUDrlW7ur8zT5scqRvXZhapm_0JdvKGiw68Iyx9E/edit#heading=h.jc9thlt4k0t7)

**Comment by bwilliams18** [comment]
This would definitely solve #747 being able to control timezone at the org level and then see the dropdown like in stripe would be amazing.

**Comment by paolodamico** [comment]
Here's what I'm thinking we could do for this (**requesting feedback**):
- [ ] Allow users to set a timezone for each project in settings.
- [ ] All graphs (insights, dashboards, etc.) would be loaded using this project timezone.
- [ ] Show an indicator in each query with a reminder on the timezone and config options.

<img width="638" alt="" src="https://user-images.githubusercontent.com/5864173/111355995-2796ed00-8645-11eb-8337-a9aff2c96308.png">


- [ ] For static dates shown anywhere (e.g. person properties, event properties, ...), we show the timezone component with information of the date in the relevant timezones.

<img width="691" alt="" src="https://user-images.githubusercontent.com/5864173/111354659-c884a880-8643-11eb-86d9-35bb3bb5a0bd.png">
