### ISSUE TITLE
Improve custom date range selector

### ISSUE THREAD

**Issue by paolodamico** [PostHog/posthog#2779]
## Is your feature request related to a problem?

Experience with the custom date range selector (see below) is a bit clunky. You need a ton of extra clicks to navigate around.

## Describe the solution you'd like

Have something like Airbnb or your typical airline where the range selector opens automatically and then it lets you select a range more easily (without having to select a start date and and an end date individually).

## Describe alternatives you've considered

Keep the current experience.

## Additional context

Came from [customer call](https://docs.google.com/document/d/1gJlsUDrlW7ur8zT5scqRvXZhapm_0JdvKGiw68Iyx9E/edit#heading=h.jc9thlt4k0t7).

**Comment by EDsCODE** [comment]
+1

**Comment by macobo** [comment]
Note that changing the time bucketing (e.g. hourly) often resets the date range selected, leading to even more clicks.

**Comment by paolodamico** [comment]
Think this is still quite relevant. Tagging @clarkus for ideas here

**Comment by clarkus** [comment]
Still relevant (https://github.com/PostHog/posthog/issues/5173#issuecomment-883976437) as it relates to session filters. #2990 as well. I have some ideas for this. I'll add it into my design queue 👍

**Comment by clarkus** [comment]
Here is a basic pattern for a datepicker that is optimized for ranges. This is a bit separate from the input that would summarize the selected values. I am working on something for that now. Important aspects to the picker below:

- prominent navigation for years and months
- summary of the selected range - this could be the same or a translation of the value shown in the input (design pending)
- Context is highlighted - in the concept below, the current date is highlighted with a gray stroke
- Not represented in the concept below, but disallowed values are disabled or entirely hidden from the calendar component of the picker. 

<img width="352" alt="Screen Shot 2021-07-21 at 3 50 40 PM" src="https://user-images.githubusercontent.com/254612/126569781-ba83f220-0122-46c0-a5b6-fcf0030c8181.png">

**Comment by clarkus** [comment]
I did some research looking for react-based datepicker components we could use for this need. https://github.com/airbnb/react-dates looks fairly complete. The one thing I didn't find support for was quickly navigating years.
