### ISSUE TITLE
Lifecycle tooltip needs updating

### ISSUE THREAD

**Issue by jamesefhawkins** [PostHog/posthog#2782]
## Bug description

The current tooltip only explains stickiness, whereas I wanted to know how the new lifecycle functionality works :)

<img width="401" alt="Screenshot 2020-12-15 at 22 01 24" src="https://user-images.githubusercontent.com/47497682/102278112-26a8cf00-3f21-11eb-8895-abd15f1f6cbf.png">

## Expected behavior

Tool tip to explain lifecycle when lifecycle shown.

**Comment by paolodamico** [comment]
I actually think this should be superseded by #2712, the biggest problem is about discoverability/intuitiveness, though even if we do separate it as suggested on the referenced issue, adding the tooltip with the explanation should absolutely be considered.

**Comment by paolodamico** [comment]
I believe this has been address with `remove-shownas`, can we close?
