### ISSUE TITLE
Command bar navigation fails in very niche cases

### ISSUE THREAD

**Issue by yakkomajuri** [PostHog/posthog#2792]
## Bug description

*Please describe.*  
*If this affects the front-end, screenshots would be of great help.*  

This one is a bit weird and I haven't managed to truly get to the bottom of it just yet (little time spent though). 

On the demo instance, if I navigate manually from anywhere to Insights it works fine, as expected. 

However, if I navigate from Sessions -> Insights via the command bar, PostHog hangs, I get a blank screen, and my computer also starts heating up. 

The console gives me this:

```
RangeError: Maximum call stack size exceeded
    at f (index.js:217)
    at updateLocation (index.js:181)
    at index.esm.js:1112
    at Object.dispatch (index.esm.js:1195)
    at Object.keys.forEach.e.actions.<computed> [as __routerPush] (index.esm.js:287)
    at i.<computed> (index.js:745)
    at index.esm.js:1112
    at Object.dispatch (index.esm.js:1195)
    at Object.keys.forEach.e.actions.<computed> [as setFilters] (index.esm.js:287)
    at Object./insights [as action] (trendsLogic.js:336)
 ```
 
The weird part though is that I can't reproduce it on app, nor locally. 

I'm just a few commits behind master on the demo instance, so could definitely see if there's a chance that could be the issue, otherwise, a bit stuck.

## Expected behavior

Command bar navigation should work.

## How to reproduce

1. Go to the [demo instance](playground.posthog.com)
2. Navigate to sessions
3. Navigate to insights via the command bar

## Environment

- PostHog cloud or self-managed?
- PostHog version/commit

**Comment by Twixes** [comment]
I can't reproduce, so will close.
