### ISSUE TITLE
Bug with CH persons double click on retention table

### ISSUE THREAD

**Issue by paolodamico** [PostHog/posthog#2794]
## Bug description

We have an issue in which the table of users for each cohort does not contain the same number of users as the table reports.

### Example
([Source](https://app.posthog.com/insights?startEntity=%7B%22actions%22%3A%5B%5D%2C%22events%22%3A%5B%7B%22id%22%3A%22user%20signed%20up%22%2C%22type%22%3A%22events%22%2C%22order%22%3A0%2C%22name%22%3A%22user%20signed%20up%22%7D%5D%2C%22new_entity%22%3A%5B%5D%7D&returningEntity=%7B%22events%22%3A%5B%7B%22id%22%3A%22%24pageview%22%2C%22name%22%3A%22%24pageview%22%2C%22type%22%3A%22events%22%7D%5D%7D&retentionType=retention_first_time&date_to=2020-04-05T12%3A59%3A36.001Z&period=w&display=ActionsTable&properties=%5B%7B%22key%22%3A%22id%22%2C%22value%22%3A71%2C%22type%22%3A%22cohort%22%7D%2C%7B%22key%22%3A%22%24current_url%22%2C%22value%22%3A%22www.posthog.com%22%2C%22operator%22%3A%22not_icontains%22%2C%22type%22%3A%22event%22%7D%2C%7B%22key%22%3A%22%24current_url%22%2C%22value%22%3A%22https%3A%2F%2Fposthog.com%22%2C%22operator%22%3A%22not_icontains%22%2C%22type%22%3A%22event%22%7D%2C%7B%22key%22%3A%22%24current_url%22%2C%22value%22%3A%22localhost%22%2C%22operator%22%3A%22not_icontains%22%2C%22type%22%3A%22event%22%7D%2C%7B%22key%22%3A%22%24current_url%22%2C%22value%22%3A%22127.0.0.1%22%2C%22operator%22%3A%22not_icontains%22%2C%22type%22%3A%22event%22%7D%2C%7B%22key%22%3A%22%24current_url%22%2C%22value%22%3A%220.0.0.1%22%2C%22operator%22%3A%22not_icontains%22%2C%22type%22%3A%22event%22%7D%5D&insight=RETENTION))

**Table shows 6 users in cohort:**
<img width="222" alt="" src="https://user-images.githubusercontent.com/5864173/102359528-867d9500-3f76-11eb-8134-50d0adcbd5b8.png">

**Persons list shows a lot more than 6 users in cohort:**
<img width="150" alt="" src="https://user-images.githubusercontent.com/5864173/102359599-9a28fb80-3f76-11eb-9cb8-61b37ddd4d95.png">

## Expected behavior
The persons list and the retention table should match.

## How to reproduce

See description above.

## Environment

Cloud, Clickhouse.

## Additional context

Currently blocking internal personas analysis.

**Comment by paolodamico** [comment]
This seems to be happening in other graphs too. See [example](https://app.posthog.com/insights?events=%5B%7B%22id%22%3A%22%24pageview%22%2C%22name%22%3A%22%24pageview%22%2C%22type%22%3A%22events%22%2C%22math%22%3A%22dau%22%7D%5D&properties=%5B%7B%22key%22%3A%22%24active_feature_flags%22%2C%22operator%22%3A%22icontains%22%2C%22value%22%3A%22persons-2353%22%7D%5D&breakdown_type=event&display=ActionsLineGraph&interval=week&date_from=-90d)

<img width="327" alt="" src="https://user-images.githubusercontent.com/5864173/104774454-54f61600-573c-11eb-915f-28cb4115ca33.png">


<img width="337" alt="" src="https://user-images.githubusercontent.com/5864173/104774457-56274300-573c-11eb-83fc-07afd9ffdb6e.png">

**Comment by EDsCODE** [comment]
#2992 address the problem for the line graph example. Retention issue still open

**Comment by paolodamico** [comment]
I don't know if I discovered another bug or is the same bug manifesting another way. See here the table saying there's 21 users, but then the table contains way more than 21 users (~90).

<img width="396" alt="" src="https://user-images.githubusercontent.com/5864173/107194684-aa96a900-69f0-11eb-954b-b6c985b40fcb.png">


In addition, worth mentioning that I'm experiencing a ton of timeouts when getting the persons list (about 8 or 9 times out of 10).

**Comment by paolodamico** [comment]
There still seems to be a bug here (unsure if it's a one-off thing), but I opened [this graph](https://app.posthog.com/insights?target_entity=%7B%22id%22%3A%22%24pageview%22%2C%22type%22%3A%22events%22%2C%22order%22%3A0%2C%22name%22%3A%22%24pageview%22%7D&returning_entity=%7B%22id%22%3A%22%24pageview%22%2C%22type%22%3A%22events%22%2C%22name%22%3A%22%24pageview%22%7D&period=Week&retention_type=retention_first_time&display=ActionsTable&startEntity=%7B%22actions%22%3A%5B%5D%2C%22events%22%3A%5B%7B%22id%22%3A%22user%20signed%20up%22%2C%22type%22%3A%22events%22%2C%22order%22%3A0%2C%22name%22%3A%22user%20signed%20up%22%7D%5D%2C%22new_entity%22%3A%5B%5D%7D&returningEntity=%7B%22events%22%3A%5B%7B%22id%22%3A%22%24pageview%22%2C%22name%22%3A%22%24pageview%22%2C%22type%22%3A%22events%22%7D%5D%7D&retentionType=retention_first_time&selectedDate=2020-12-06%2006%3A00&properties=%5B%7B%22key%22%3A%22id%22%2C%22value%22%3A71%2C%22type%22%3A%22cohort%22%7D%2C%7B%22key%22%3A%22%24host%22%2C%22value%22%3A%22app.posthog.com%22%2C%22operator%22%3A%22exact%22%2C%22type%22%3A%22event%22%7D%5D&insight=RETENTION) today and got no users,

<img width="800" alt="" src="https://user-images.githubusercontent.com/5864173/107636609-2bfa6f80-6c6d-11eb-973d-fde787c878f1.png">

**Comment by yakkomajuri** [comment]
Still not really working and also essential for my work following up with onboarded users that might be churning. Right now I have no idea who the users are.

**Comment by yakkomajuri** [comment]
Are these the same?

https://github.com/PostHog/posthog/issues/3018

**Comment by EDsCODE** [comment]
Dont think so. Going to revisit this today

**Comment by EDsCODE** [comment]
update on this:
#3331 and #3332 fixes the blank results and overload of results that surpassed counts. 

What's happening now that's still unintuitive is that I'm filtering out people that don't exist in postgres. I think there's a sync issue between postgres and clickhouse where a user doesn't exist at all in postgres but exists in clickhouse. So the query is accounting for users in clickhouse but when I try to compile the list with person details, it can't find the user in postgres. I've opted to omit these missing rows and just return a list of the users that do exist. This will result in a count discrepancy again where sometimes the actual number of rows will be less than the number shown at the top. 

I could match the returned row count with the totals at the top of the modal but then there would be a difference between the table number that's shown in the visualization and the numbers shown in the modal

**Comment by mariusandra** [comment]
Just guessing here, but could there be some issue with running the clickhouse person table `ALTER` queries somewhere?

One possible explanation is that these queries silently failed or were skipped for the python ingestion for a while, but worked with the plugin server ingestion. This also gives a plausible explanation to the outage as the server was just not able to handle this many newly seen alter queries. 

The other option is the plugin server skipped a lot of them when ingesting, especially when clickhouse went down. It possibly wasn't fully down, but just the person queries failed at first.

What's the date range for the faulty data?

**Comment by yakkomajuri** [comment]
@mariusandra I mean the issue was reported back in December - was the plugin server at all in cloud back then?

**Comment by mariusandra** [comment]
Nope, it's only been doing something for the last 2 weeks

**Comment by Twixes** [comment]
I'll close this since it appears the original problem is not relevant anymore. A related but different problem should get its own issue.
