### ISSUE TITLE
v1.19.0 broke custom dashboard

### ISSUE THREAD

**Issue by fitzn** [PostHog/posthog#2813]
## Bug description

I just upgraded from 1.17 (I think) to 1.19 and now my custom Dashboard does not load. The Default dashboard loads, but the custom dashboard says "Error on All Items".
<img width="1137" alt="Screen Shot 2020-12-18 at 12 26 34 AM" src="https://user-images.githubusercontent.com/6731677/102578506-534b1b00-40c8-11eb-97ec-6ae42fd9e04b.png">

It shows no panels, but I previously had 7+ panels.

## Expected behavior
My existing Dashboard loads.

## How to reproduce
Not sure if this is universal or specific to me:
1. Have a custom dashboard
2. Run these commands
```
cd posthog
docker-compose pull web
docker-compose down
docker-compose up -d
```
3. Load the web portal and sign-in

## Environment
I'm running a self-hosted installation where I pull the latest from the posthog git repo and then `docker-compose` to run it as a daemon. This is my git HEAD: `0268e88f4`.

## Additional context
Here are my server logs from the running docker container:
```
10.0.2.43 - - [18/Dec/2020:05:27:40 +0000] "GET /static/dashboard.7bf8786c1339d615bdc4.js HTTP/1.1" 200 0 "https://XXX/dashboard/2" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.88 Safari/537.36"
Internal Server Error: /api/dashboard/2/
Internal Server Error: /api/dashboard/2/
10.0.2.43 - - [18/Dec/2020:05:27:40 +0000] "GET /api/dashboard/2/ HTTP/1.1" 500 86 "https://XXX/dashboard/2" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.88 Safari/537.36"
```

Just saw this error in the logs. No idea if it's related or not:
```
[2020-12-18 05:32:53,579: ERROR/ForkPoolWorker-2] Task posthog.celery.check_cached_items[fd624f13-8183-473c-95ae-7a6375f51b2c] raised unexpected: ValueError('Period m is unsupported.')
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/celery/app/trace.py", line 385, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/celery/app/trace.py", line 650, in __protected_call__
    return self.run(*args, **kwargs)
  File "/code/posthog/celery.py", line 204, in check_cached_items
    update_cached_items()
  File "/code/posthog/tasks/update_cache.py", line 51, in update_cached_items
    filter = get_filter(data=item.filters, team=item.team)
  File "/code/posthog/models/filters/filter.py", line 241, in get_filter
    return RetentionFilter(data={**data, "insight": INSIGHT_RETENTION}, request=request)
  File "/code/posthog/models/filters/retention_filter.py", line 56, in __init__
    tdelta, t1 = RetentionFilter.determine_time_delta(self.total_intervals, self.period)
  File "/code/posthog/models/filters/retention_filter.py", line 98, in determine_time_delta
    raise ValueError(f"Period {period} is unsupported.")
ValueError: Period m is unsupported.
```

**Comment by macobo** [comment]
Some debugging context: Same error in sentry on cloud: https://sentry.io/organizations/posthog/issues/2096727125/?project=1899813&query=is%3Aunresolved

**Comment by macobo** [comment]
Seems something is quite broken here:

```
In [13]: DashboardItem.objects.filter(filters__period__in=['Day', 'Month', 'Week', 'Hour']).count()
SELECT COUNT(*) AS "__count"
  FROM "posthog_dashboarditem"
 WHERE ("posthog_dashboarditem"."filters" -> 'period') IN ('"Day"', '"Month"', '"Week"', '"Hour"')

Execution time: 0.226941s [Database: default]
Out[13]: 332

In [14]: DashboardItem.objects.filter(filters__period__in=['d', 'm', 'h', 'w']).count()
SELECT COUNT(*) AS "__count"
  FROM "posthog_dashboarditem"
 WHERE ("posthog_dashboarditem"."filters" -> 'period') IN ('"d"', '"m"', '"h"', '"w"')

Execution time: 0.194835s [Database: default]
Out[14]: 648
```

Last one containing 'd'/'m'/'h'/'w' was created at 11th, which makes me think https://github.com/PostHog/posthog/pull/2745 broke this (as it touched the 'd' => 'Day' transformation code on FE).

cc @timgl - will try to create a migration to patch this. :)

**Comment by macobo** [comment]
This is now fixed on our end.

@fitzn you can try update the same way as you did previously which should apply the fix.

:bow: Thanks for the through report and keep sending bugs/feedback/ideas our way!

**Comment by fitzn** [comment]
@macobo Thanks for the quick turnaround. The dashboard is working again.
