### ISSUE TITLE
Retention queries are not saved correctly to dashboard

### ISSUE THREAD

**Issue by macobo** [PostHog/posthog#2817]
## Bug description

Client reported that after saving a retention graph to dashboard, the graph is reset to defaults ($pageview -> $pageview)

## Expected behavior

The correct retention graph is shown on dashboard.

## How to reproduce

1. Go to insights -> retention
2. Add retention from two custom events
3. Save to dashboard
4. Visit dashboard
5. See the graph is wrong 

## Environment

- [x] PostHog Cloud
- [ ] self-hosted PostHog, version/commit: _please provide_

## Additional context

![Screenshot from 2020-12-18 13-12-37](https://user-images.githubusercontent.com/148820/102608551-b8d3f180-4132-11eb-949d-3660cd295775.png)

**Comment by u-ashish** [comment]
+1 to this, also noticed on my dashboards

**Comment by timgl** [comment]
Fixed in #2884
