### ISSUE TITLE
Improve bookmarklet experience

### ISSUE THREAD

**Issue by paolodamico** [PostHog/posthog#2823]
## Is your feature request related to a problem?

#2774 introduced the bookmarklet which seems to be a game changer in terms of testing and demoing. The next step seems here to improve the experience around this feature so we can leverage its full potential.

## Describe the solution you'd like

1. Most importantly we need tracking. Ideally we would want to know ~a) when a user adds the bookmarklet to their bookmarks (not sure if this will be possible)~, b) when the user uses the bookmarklet (relevant metadata should be included, e.g to identify if it's being used across different pages, ...).
2. ~We absolutely need to have it in the onboarding experience. We already ask the user if they are using a website, we could then have a CTA to use it (highlighting that this will allow them to temporarily see events coming in instantly). Very strongly related to #2822.~
3. We need to improve the way we show this in the project settings page. I particularly believe we should have the gif in there somewhere (maybe have a collapsible CTA which when you click shows the instructions and gif).
4. Include the bookmarklet gif in the _no event ingestion email_ (https://github.com/PostHog/posthog-production/pull/20).

## Describe alternatives you've considered
We could wait to have more data on this before improving (either qualitative from demo calls or quant [though point 1 is needed], however I do think these are relatively low-effort improvements we could ship to get better insights.

**Comment by paolodamico** [comment]
@macobo from what I was mentioning yesterday in Slack. I think it could be a matter of updating the bookmarklet code to call `posthog.capture` (with the PH Team token, on cloud) to send an event that the bookmarklet was activated. Wdyt?

I would definitely prioritize getting instrumentation here soon (but I'll probably need your help), without these metrics, we have no clue if this is actually helpful or not.

**Comment by macobo** [comment]
One other thing to improve is the development process as we improve the UI (see this comment: https://github.com/PostHog/posthog/pull/2953#issuecomment-760769780) so changing the bookmarklet isn't as annoying.

>  I think it could be a matter of updating the bookmarklet code to call posthog.capture (with the PH Team token, on cloud) to send an event that the bookmarklet was activated. Wdyt?

I don't think it's quite so simple - it's a similar case to toolbar where you might need to embed a different posthog into the snippet.

However we might not need a full snippet here - our capture endpoint should work with a simple GET query -> just do that when the bookmarklet is opened. https://posthog.com/docs/api/post-only-endpoints#sending-events

**Comment by mariusandra** [comment]
When you use the bookmarklet on https://news.ycombinator.com/, the first time you click it nothing visual happens. The console says that CORS prevented the script form running. If I click it again, it says that posthog is already enabled. However no events will be tracked due to the error.

![2021-01-15 16 27 16](https://user-images.githubusercontent.com/53387/104745675-a3141500-574e-11eb-9545-188fe06d3be9.gif)
