### ISSUE TITLE
Website header resizes poorly on 13 inch monitor 

### ISSUE THREAD

**Issue by Tannergoods** [PostHog/posthog#283]
**Describe the bug**
On a 13 inch monitor the PostHog header on our website looks off slightly

**To Reproduce**
Got to PostHog.com, resize to 13 inch monitor full screen, Blog, Contact, Docs and Pricing are on one line and our GithHub repo link is above this 

**Expected behavior**
The header links should broadly fit together, maybe aim for symmetry? 

**Screenshots**
<img width="1246" alt="Pivot_to_PostHog_–_PostHog" src="https://user-images.githubusercontent.com/60791437/76027264-35b81680-5ee5-11ea-87fa-f33a50aac030.png">

**Desktop (please complete the following information):**
 - MacOS
 - chrome

**Comment by timgl** [comment]
Also think the header will look better if it's like `50vh` rather than `100vh`

**Comment by timgl** [comment]
New website, closing
