### ISSUE TITLE
Improve date selection in retention table

### ISSUE THREAD

**Issue by paolodamico** [PostHog/posthog#2831]
## Is your feature request related to a problem?

Currently the retention table is formed based on "current date" which is used as the end date, and the start date gets inferred. We have seen however that this is not very intuitive (our own team has found this a bit confusing).

## Describe the solution you'd like

I'd like us to have a more intuitive date selection process. One option is to simply use the time range component we use in other insights (last X days, custom, ...).

## Describe alternatives you've considered

Here's a Mixpanel screenshot for inspiration.

<img width="350" alt="" src="https://user-images.githubusercontent.com/5864173/102668886-b5e8f900-4152-11eb-8933-7267ac22dd50.png">

## Additional context
We should consider this in the lens of making a reusable component for other time range selections across the app.

**Comment by EDsCODE** [comment]
We're fairly limited right now on how many intervals the query can properly support. Do you think we should use the timerange component but with strict limits?

**Comment by paolodamico** [comment]
Superseded by #4350
