### ISSUE TITLE
Show period in progress in retention table

### ISSUE THREAD

**Issue by paolodamico** [PostHog/posthog#2833]
## Is your feature request related to a problem?

We currently show that a period is in progress in line charts (including the partial retention cohorts graph) by showing the in progress segment with a dotted line. We should do the same in the retention table.

## Describe the solution you'd like

We should clearly show which period is in progress in the retention table. This particularly helps users understand which numbers are still subject to change.

**Comment by EDsCODE** [comment]
#2995
