### ISSUE TITLE
Cohorts on users without email set still includes identified users

### ISSUE THREAD

**Issue by u-ashish** [PostHog/posthog#2835]
## Bug description

If I:
- Have some anonymous users (`email` is not set, and their `distinctID` is the auto-generated one)
- Have some identified users (`email` property is set, and `identify()` is called so their `distinctID` is email)

When:
- One user goes from being anonymous to identified, they now have an `email` set and their `distinctID` has _both_ their `email` and their old auto-generated ID

Then:
- If I try to create a cohort `where email is not set`, users with emails still show up.

### Screenshots

(I changed the email to `realemail@gmail.com`)

<img width="744" alt="Screen Shot 2020-12-22 at 9 04 43 AM" src="https://user-images.githubusercontent.com/14264791/102902555-c5a75c80-4434-11eb-9f96-5148eabe111d.png">

## Expected behavior

In the picture above, `realemail@gmail.com` should not appear. I would expect only anonymous users to show up, not ones that were then later identified / aliased / etc.

## How to reproduce

1. Browse anonymously
2. Log in with and get identified by email so that you have a user who is anonymous then identified
3. Create a cohort in the console where their email property is not set

## Environment

- [X] PostHog Cloud
- [ ] self-hosted PostHog, version/commit: _please provide_

## Additional context

I was doing this to create a cohort of users who were browsing anonymously without ever signing up, so I can understand what true visitors do (i.e. not people that already have accounts but were clicking around without logging in).

ALSO:

Maybe a related question -- does this mean that if someone is browsing anonymously, then registers, and I identify them by their email, that I lose the info about how they were browsing pre-registration? Since it's all aliased?

**Comment by weyert** [comment]
Are you sure it has a property `email` which has a value? From the screenshot it's not clear to me which properties are associated with the distinct id `realemail@gmail.com`. It's not like it checks if your distinct id is a valid email address, it just checks if the user properties has a property with the name `email` and whether is not set or not.

**Comment by u-ashish** [comment]
@weyert yep, here you go, I attached both screenshots properly this time, the first showing the Cohort, and the second showing what I see when I click on that person record. From what I can see, the `email` property is set and has a value.

Let me know if I've misunderstood anything.


### Cohort for visitor where an email address shows up under a cohort where `email is not set`

(Masked email address)

<img width="741" alt="Screen Shot 2020-12-22 at 3 57 33 PM" src="https://user-images.githubusercontent.com/14264791/102936884-a2010800-446e-11eb-8107-973c79435278.png">

### Clicked on `realemail@gmail.com` and I see that the `email` is set, and that the `Distinct ID` fields have both the old ID and the email.

<img width="1426" alt="Screen Shot 2020-12-22 at 4 02 21 PM" src="https://user-images.githubusercontent.com/14264791/102937132-19369c00-446f-11eb-97ae-bc1bfdc646e7.png">

**Comment by weyert** [comment]
Ah yeah, I think you understood it correctly, that's how I would expect it to behave too. How you described it in your initial post. If I only knew how to debug Python/Django code ;)

**Comment by paolodamico** [comment]
We'll definitely investigate this issue, in the meantime, you could try using the `is_identified` property to create your cohort.

**Comment by u-ashish** [comment]
@paolodamico I don't see `is_identified` in the list of properties when creating the filter. But also, looking at the screenshot, the issue was that users with an email also appeared under `Anonymous`, so I presume that they would still appear if `is_identified=FALSE` (which is the same as `Anonymous`?)

**Comment by paolodamico** [comment]
Sorry for the delay here @u-ashish, you're right it does seem like we have a bug on how the is_identified property is set after setting an email. How are you setting the email address of a user? Are you calling identify on the front-end or back-end? Are you calling it right after .init?

Tagging @EDsCODE as you might have more context. FYI I've seen this happen a couple of times with our team.

**Comment by u-ashish** [comment]
@paolodamico The way I do it, I initialize the posthog library when the app (React) starts, and have a separate function wrapping around `posthog.identify()` which I call when someone logs in.

So what happens is:

- App starts, posthog initializes
- Someone logs in
- I set metadata via `posthog.people.set({...})`
- I call `posthog.identify(email)`

**Comment by paolodamico** [comment]
Hey @u-ashish! What information are you sending in `posthog.people.set`, presumably the email? I believe the right approach would be to call `posthog.identify` first to associate the previously anonymous profile with your now logged in user, and then call the `set` method to add their email (see https://posthog.com/docs/integrations/js-integration#complete-signup-pseudocode). I'm not 100% sure if doing it the other way around leads to the same results, do you have more context @mariusandra ?

**Comment by EDsCODE** [comment]
Thanks for the issue @u-ashish. @paolodamico's suggestion in identifying flow is the correct one as you need to identify the user first before you can set the properties. If you call `posthog.identify(email)` it will treat the email as an ID rather than a property field. 

However, the bug that you noted seems to be an issue on our side as even if you identified the user with the email as an ID, it shouldn't still appear in anonymous users. I will take a look!

**Comment by u-ashish** [comment]
@paolodamico @EDsCODE Thanks for catching that... :) Flipped it on my end to the recommended approach.

**Comment by Twixes** [comment]
Hey! We've since removed the built-in distinction between anonymous/identified as it was generally confusing like this. The recommended approach now is to simply rely on properties, for instance `email` – where you can be more confident about the mechanics.
