### ISSUE TITLE
User id containing URL-specific characters breaks admin UI navigation

### ISSUE THREAD

**Issue by funkyOne** [PostHog/posthog#284]
**Describe the bug**
It is possible to identify user with an id that will make impossible to navigate to Person page.

**To Reproduce**
1. In app code call `posthog.identify("user/13");`
2. Generate some app activity to get some events in PostHog
3. Go to PostHog Events UI, find an event from this user and click on person name
4. PostHog will direct you to a non-existent page `https://{host}/person/user/13`

**Expected behavior**
I should be able to propely navigate to this person page 

**Potential solutions**
Either disalow URL-specific characters in user ids.
Or URL-encode user ids when using them in admin UI URLs

**Comment by timgl** [comment]
@funkyOne Thanks for raising this! That's fixed now :)

**Comment by timgl** [comment]
See https://github.com/PostHog/posthog/wiki/Upgrading-PostHog for how to upgrade

**Comment by funkyOne** [comment]
Wow that was a quickest bug fix I have seen in my life. Thanks!
