### ISSUE TITLE
"Custom Actions" are getting captured but not being posted to Webhooks

### ISSUE THREAD

**Issue by ankitherocker** [PostHog/posthog#2840]
## Bug description

We have multiple event & actions defined to be posted on a Webhook. All the $pageview events are being captured & sent but the actions created using AutoCapture are just being captured but not being posted onto webhook.

It is affecting em because I have just 25 $pageview events & 100+ actions using AutoCapture. If it doesn't work, I will have to integrate PostHog into the source code which is a tedious code making my Customer Success team dependent on developers for even a single change.

Below is the screenshot:
<img width="1296" alt="Screenshot 2021-01-02 at 2 45 51 PM" src="https://user-images.githubusercontent.com/965458/103454419-c7f99880-4d09-11eb-8c35-0a788b8e5899.png">

## Expected behavior
Every action that has "Post to webhook when this action is triggered" enabled should post the event.

## How to reproduce

1. Enabled to Webhook for testing. I use http://httpdump.io/.
2. Create a $pageview event that says "Visited SMS Marketing Page" - smsMarketing.php
3. Create an action using AutoCapture for the "Send SMS" button on the same page - smsMarketing.php
4. Enable "Post to webhook when this action is triggered" for both the actions
5. Try triggering both the actions, both of them will be captured by PostHog but only $pageview event will be sent to the webhook

## Environment
- [ 1] PostHog Cloud

## Additional context
Even tried just enabling the AutoCapture button event - Send SMS & disabling $pageview action thinking the clash between the events. Didn't help!

**Comment by yakkomajuri** [comment]
I believe we've fixed this. Please let us know if not @ankitherocker
