### ISSUE TITLE
Property value suggestions not loading (self-hosted)

### ISSUE THREAD

**Issue by timgl** [PostHog/posthog#2847]
## Bug description

On a self-hosted instance with a decent amount of volume, property value suggestions (when you're filtering on a property) isn't loading or times out. It does work if you manually change the query to be the last hour. 

```
If I limit it to 1 hour instead of 1 day it takes about 12 seconds, if i go up to 2 hours it takes 40 seconds.
```

## Expected behavior

Should work

## How to reproduce

1.
2.
3.

## Environment

- [ ] PostHog Cloud
- [x] self-hosted PostHog, version/commit: _please provide_

**Comment by EDsCODE** [comment]
#2844 should limit this better now
