### ISSUE TITLE
Make instance status reports useful

### ISSUE THREAD

**Issue by paolodamico** [PostHog/posthog#2857]
## Is your feature request related to a problem?

Not sure about calling it a bug report or an improvement, but basically we're currently sending the `instance status reports` assigned to a machine ID. The problem is that we do user-based analytics, and that ID can get lost and have little meaning to the way we structure analytics.

## Describe the solution you'd like

I'd like to be able to painlessly answer some questions:
- Which libraries are the events coming from for X user? Is the user/team using web, native, ...?
- How many events is this user receiving every week?
- How many users is this user seeing every week?

We also need to consider how to handle the user having multiple teams/orgs, which make things trickier.

## Describe alternatives you've considered

Use some inaccurate proxies/heuristics to try to get some sense of these numbers.

## Additional context

CC @Twixes, what are your thoughts on this?

**Comment by macobo** [comment]
IMO this is another usecase for https://github.com/PostHog/posthog/issues/2247 - the user you're referring throughout is really a team/company.

**Comment by Twixes** [comment]
Are the reports useful as is currently? @paolodamico Or still need group analytics to improve this?

**Comment by paolodamico** [comment]
As we now send this report for each user in the instance, it's now easier to identify, I think it's fine to close this now.
