### ISSUE TITLE
Static cohorts + upload by CSV

### ISSUE THREAD

**Issue by timgl** [PostHog/posthog#2868]
## Is your feature request related to a problem?

I have a list of user ids (distinct IDs in PostHog) in CSV format that I want to upload as a static cohort so I can track that set of users.

## Describe the solution you'd like

When creating a cohort, give me the option to upload a CSV instead of defining it the normal way. This static cohort should have a label `static` in the list, and should not be automatically updated.

## Describe alternatives you've considered

-

**Comment by paolodamico** [comment]
I think we should also support just pasting the URLs from clipboard (from a spreadsheet or something). For most cases, I think this will be faster and more intuitive. You would probably do CSV when you're importing a ton of users.
