### ISSUE TITLE
Support regex or wildcard selectors for custom events match groups in actions

### ISSUE THREAD

**Issue by paolodamico** [PostHog/posthog#2902]
## Is your feature request related to a problem?

You may have multiple custom events that follow the same structure. It'd be helpful to be able to generate an action for all of those easily and dynamically.

## Describe the solution you'd like

I'd like to be able to create an action with a custom event match group where instead of matching a specific event, I match events that follow a regex pattern (or at least wildcard support).

## Describe alternatives you've considered

Adding all events manually to the action.

## Additional context

Requested by user on [Slack thread](https://posthogusers.slack.com/archives/CT7HXDEG3/p1610144383001700)

**Comment by u-ashish** [comment]
Thanks! Would be immensely useful so I can comfortably change event naming without worrying about losing it in my analysis.

**Comment by paolodamico** [comment]
I believe this is still relevant for generating actions? Something similar came up with a focus customer
