### ISSUE TITLE
Test hotkey support to improve UX

### ISSUE THREAD

**Issue by paolodamico** [PostHog/posthog#2907]
## Is your feature request related to a problem?

Power usage is stronger with keyboard shortcuts, they can become second nature and aid in things getting done faster. I'd like to test the impact of adding some basic keyboard shortcuts to core views.

## Describe the solution you'd like

I'd like us to try adding hotkey support (see below for design) to some key actions and measuring the impact.

**Tabs example**
<img width="357" alt="" src="https://user-images.githubusercontent.com/5864173/104138108-99ae3580-5367-11eb-96f0-fc18c51d7ee3.png">

**Button example**
<img width="800" alt="" src="https://user-images.githubusercontent.com/5864173/104138107-97e47200-5367-11eb-969a-7d6efc4e7712.png">

The experiment can include adding hotkey support for the following:
- Switching between different insights tab (trends, sessions, lifecycle, ...)
- Switching between daily, weekly, monthly timeframes on insights graphs.
- Stretch. Navigating the main navigation bar.

## Describe alternatives you've considered

Increase discoverability / have more guided flows of the command palette and push power usage through it. Though it seems like the best-in-class products on this (e.g. Superhuman) do both.

## Additional context

- This is related to the command palette. This however I believe could have a higher usage (and direct impact) due to its increased discoverability within the regular product flow.
- We need to make sure to put everything a feature flag here to be able to measure the impact of the experiment accurately.

CC @Twixes

**Comment by Twixes** [comment]
I like the idea, though such keyboard button icons look kind of disruptive on UI elements. How about the classic Windows thing, underlined letters? Though then that is much less discoverable.

![Windows](https://mlvkn2cgobrp.i.optimole.com/UN1ds0o-Ci5qw5hH/w:auto/h:auto/q:auto/http://www.chinhdo.com/wp-content/uploads/2008/09/clip-image0015.png)

As for the command palette, I think it'd be cool and rather trivial to have parity between it and these letter controls.

**Comment by paolodamico** [comment]
Definitely, let's do parity! I like the idea of the more obvious approach at list first because it has a ton of discoverability, we could then re-evaluate based on usage. Might implement an MVP of this pretty soon.
