### ISSUE TITLE
Refresh GitHub readme icons

### ISSUE THREAD

**Issue by lottiecoxon** [PostHog/posthog#2910]

**Comment by lottiecoxon** [comment]
<img width="1584" alt="Header" src="https://user-images.githubusercontent.com/65415371/104171556-bba4c800-53fa-11eb-9242-0934605b803f.png">

**Comment by lottiecoxon** [comment]
### Quick Start 
![Group 16](https://user-images.githubusercontent.com/65415371/104304349-2faaa300-54c3-11eb-97ed-9b4f425ec4e8.png)
### Make the Most of PostHog 
![Group 17](https://user-images.githubusercontent.com/65415371/104304353-30433980-54c3-11eb-9d0a-c529bc7f8046.png)
### Features
![Group 18](https://user-images.githubusercontent.com/65415371/104304355-30dbd000-54c3-11eb-8c2d-47b30e6c294a.png)
### Event Autocapture
![Group 20](https://user-images.githubusercontent.com/65415371/104304357-31746680-54c3-11eb-8f84-329e61994b6a.png)
### Philosophy 
![Group 19](https://user-images.githubusercontent.com/65415371/104304356-30dbd000-54c3-11eb-8292-09149914f304.png)
### What's cool about this
![Group 21](https://user-images.githubusercontent.com/65415371/104304360-31746680-54c3-11eb-8958-de4b4534c5dc.png)
### PostHog Cloud
![Group 22](https://user-images.githubusercontent.com/65415371/104304362-320cfd00-54c3-11eb-9bdd-7a2c015cb87e.png)
### Deployment Options
![Group 23](https://user-images.githubusercontent.com/65415371/104304363-320cfd00-54c3-11eb-81fc-cb1ff36759b3.png)
### Production Development 
![Group 24](https://user-images.githubusercontent.com/65415371/104304364-320cfd00-54c3-11eb-95a8-f0ac125e41c0.png)
### Developing Locally 
![Group 25](https://user-images.githubusercontent.com/65415371/104304367-32a59380-54c3-11eb-8a62-43db14137765.png)
### Contributing 
![Group 26](https://user-images.githubusercontent.com/65415371/104304368-32a59380-54c3-11eb-98d9-4f596c66479f.png)
### We're Hiring
![Group 27](https://user-images.githubusercontent.com/65415371/104304371-32a59380-54c3-11eb-970d-d1d1045630cd.png)
### Open Source vs Paid
![Group 28](https://user-images.githubusercontent.com/65415371/104304372-333e2a00-54c3-11eb-8ed6-b394abc27a07.png)
### Contributors 
![Group 29](https://user-images.githubusercontent.com/65415371/104304373-333e2a00-54c3-11eb-87cc-cd08180a1591.png)

**Comment by paolodamico** [comment]
Pretty cool that we're updating these icons here! As a piece of feedback it'd be a lot easier to provide comments on this if each icon was labeled and was smaller (you can change the size by reducing the `width` parameter in the image tags).

Visually love the glasses and the rocket. The person with the coin is a bit harder to understand (maybe it's cause I'm seeing it large, but the person silhouette can get lost).

**Comment by lottiecoxon** [comment]
@paolodamico good feedback ! I will make these smaller asap, the person and the coin is supposed to be opensource and a coin, I will have a rethink for that one

**Comment by jamesefhawkins** [comment]
I think the coin is rational given the use case above.

'Make the most of PostHog' looks a bit too much like the logo for google docs  I think.

It's probably a separate issue, but when [the platform diagram is done](https://github.com/PostHog/posthog.com/issues?q=is%3Aissue+is%3Aopen+diagram), we should probably replace autocapture with the overview.

**Comment by paolodamico** [comment]
Great stuff adding the descriptions, it makes a ton more sense now 🙈 ,
- Cool! Just to clarify, my feedback on the open source vs. paid was not on the concept but on the visual, it just reminded me of the OpenVPN logo and I didn't actually see it as a person at first.
- Maybe the contributors concept would be better suited for plugins?
- Not a fan of the developing locally (seems too maps app), maybe a computer? Or a code terminal ? Just my perspective
