### ISSUE TITLE
Indicate that a query is cached and allow to update query

### ISSUE THREAD

**Issue by timgl** [PostHog/posthog#2931]
## Is your feature request related to a problem?

Right now, most queries are cached and refreshed every few hours or so (on app). As a user, I'd like to see when I'm looking at cached data, and I'd like to have the option to refresh the data if it is cached.

## Describe the solution you'd like

Just like on the dashboard, I'd like to have an indication that I'm looking at a cached result and allow me to press a button to refresh.
![image](https://user-images.githubusercontent.com/1727427/104446845-4f14ff00-559b-11eb-8cd1-824498c3ca0f.png)

**Comment by paolodamico** [comment]
I think we should be even more explicit about this. Maybe show an info (muted color) label at some corner of the graph saying how long ago it was refreshed?

**Comment by Twixes** [comment]
Done for insights.
