### ISSUE TITLE
Slow responses from CDN in China

### ISSUE THREAD

**Issue by paolodamico** [PostHog/posthog#2933]
## In what situation are you experiencing subpar performance?

Reaching PostHog Cloud from China seems to work fairly slow as reported by a user.

## How to reproduce

See [thread](https://posthog.slack.com/archives/C0113360FFV/p1609861449013500) with full details.

## Environment

- [X] PostHog Cloud
- [ ] self-hosted PostHog, version/commit: _please provide_

**Comment by paolodamico** [comment]
+1 from another user on customer support today (Papercups, 0f329aaf-8184-43d6-b087-7c2ed016f4f6). Script takes a long time to load.

**Comment by tiina303** [comment]
+1 from another user ([thread](https://posthogusers.slack.com/archives/G01JXEDAL22/p1631091396180800))

> the frontend js sdk's loading time is so slow in China mainland
