### ISSUE TITLE
Dashboard not updating on 'Update Dashboard' for existing panel

### ISSUE THREAD

**Issue by ricklamers** [PostHog/posthog#2935]
## Bug description

When updating a panel of the dashboard it says it updated the widget but the widget remains unchanged.

*Please describe.*  
*If this affects the front-end, screenshots would be of great help.*  

## Expected behavior
Update the dashboard panel if you've made changes to it and pressed the 'Update Dashboard' button.

![image](https://user-images.githubusercontent.com/1309307/104468419-b8a30680-55b7-11eb-9796-c22b1876a9fd.png)

It still uses the 'pageview' event for calculating retention.

## How to reproduce

1. Press View 'X' on Dashboard widget
2. Make a change
3. Update Dashboard (choose update existing).

Observe no change in the widget.

## Environment

- [ ] PostHog Cloud
- [X] self-hosted PostHog, version/commit: 1.19.0

**Comment by EDsCODE** [comment]
#3039
