### ISSUE TITLE
GitLab Plugins

### ISSUE THREAD

**Issue by mariusandra** [PostHog/posthog#2940]
## Is your feature request related to a problem?

You can currently install plugins from Github and NPM sources, but not GitLab

## Describe the solution you'd like

Copy a GitLab URL to install a plugin

## Describe alternatives you've considered

Using the plugin source editor.

## Additional context

Came from a conversation in the Users' slack

**Comment by FUSAKLA** [comment]
Yes, we have on prem instance of GitLab and would like to install the plugins from it so this would be most welcome! :)
