### ISSUE TITLE
Order tooltip by volume

### ISSUE THREAD

**Issue by timgl** [PostHog/posthog#2942]
## Is your feature request related to a problem?

When I have a chart with multiple lines, I want to know the exact number when I hover over. At the moment we show the tooltip like this:
![image](https://user-images.githubusercontent.com/1727427/104580319-674d5280-565d-11eb-8121-f9d4dc824e2c.png)

However this is the wrong way round, so I have to flip those numbers in my head to interpret the graph

## Describe the solution you'd like

Order the items in the tooltip from largest to smallest number.

## Describe alternatives you've considered

Do the flipping/ordering in my head

**Comment by c3ho** [comment]
Hi, can I take on this issue while #1745 is being investigated?
