### ISSUE TITLE
Don't display running locally message on non-local deployments

### ISSUE THREAD

**Issue by jamesefhawkins** [PostHog/posthog#295]
If users deploy to Heroku, we display a Running Locally? message:

![Screenshot 2020-03-07 at 14 49 26](https://user-images.githubusercontent.com/47497682/76153606-1b1ba400-6083-11ea-89c6-b9fb2bd98569.png)

The 'Running Locally?' text just doesn't need to appear for users who aren't doing this, which we can tell from the URL in many case (ie if URL includes "heroku")

It *does* make sense to leave the link to deployment instructions with Docker or open source, as that is in practise what some users will do for production usage if they are using Heroku to try it out.

**Comment by timgl** [comment]
Fixed
