### ISSUE TITLE
Include community in the product

### ISSUE THREAD

**Issue by jamesefhawkins** [PostHog/posthog#2955]
## Is your feature request related to a problem?

*This may well be the worst idea ever*

We need a big community as a company.

From a user's perspective, this might be a "next gen" way of doing plugins. So instead of seeing plugins in the menu, you see community then within that is plugins, but also links to people's profiles, they can make stuff public etc.

Ok this is super out there.
<img width="248" alt="Screenshot 2021-01-15 at 13 39 06" src="https://user-images.githubusercontent.com/47497682/104733720-0b56fc80-5737-11eb-817d-c02b19bc10f0.png">
<img width="1590" alt="Screenshot 2021-01-15 at 13 39 15" src="https://user-images.githubusercontent.com/47497682/104733739-101bb080-5737-11eb-8fec-7a0eea88f198.png">
<img width="1313" alt="Screenshot 2021-01-15 at 13 41 00" src="https://user-images.githubusercontent.com/47497682/104733912-507b2e80-5737-11eb-8d2c-d33db4292ecf.png">
<img width="1588" alt="Screenshot 2021-01-15 at 13 42 00" src="https://user-images.githubusercontent.com/47497682/104733990-7274b100-5737-11eb-822c-4e9e25132b37.png">

* Lets users build their own following in the analytics world. This means they can treat it as a profile to show case their work. However, product analytics is often private, so that'd have to be plugins that they built. 
 
## Describe the solution you'd like

This might be a crazy idea.

* People who contribute get listed automatically.
* They can connect their github profile (or login through github perhaps), and we pull whatever is public from there.
* They can add ie links to their blog / personal website
* They can follow others
* Something to do with likes on plugins?

Not sure quite how many users we'd need for this to feel good. We're probably getting there though with >100 contributors across every repo, and a bunch of issues raised. Is there a privacy issue with this even if the info is public already?

## Describe alternatives you've considered

Use Slack/GitHub for community.

**Comment by timgl** [comment]
It could be a lot more than just plugins
- dashboard templates (ie 'all you need for a mobile app', 'all you need for a SaaS app')
- Insights (query) templates
- Cohort templates
- User interview templates (when we have that product)

I'm not sure all of these make sense as a separate tab. For example when creating a cohort it'd be cool to just have a list of examples (community or ours) right there.

I think this is something for a little bit further out but could be very cool. Plugins would be an easy place to start.

**Comment by Twixes** [comment]
I don't think product analytics is nearly as plug'n'play or shareable as UX/UI design, making such an idea a worse fit for us than for Figma. For instance insights (and therefore dashboards) or cohorts depend a lot on the specifics on analytics instrumentation and results, which additionally tend to be guarded, rather than happily shared (as opposed to e.g. pretty designs).
Personally I just much more believe in us sticking to a [Segment Catalog](https://segment.com/catalog/)-esque concept.

**Comment by jamesefhawkins** [comment]
> I don't think product analytics is nearly as plug'n'play or shareable as UX/UI design, making such an idea a worse fit for us than for Figma

Makes sense. I like Tim's suggestion for interview templates, but that'd be a subset of a User Notes feature we may one day build. Closing!
