### ISSUE TITLE
Retention dashboard item changes values significantly after refresh of datasource

### ISSUE THREAD

**Issue by fuziontech** [PostHog/posthog#2964]
## Bug description

If you open the AARRR dashboard and refresh the retention dashboard item the values swing pretty drastically across all of the time periods.

If you then hard refresh the page it displays the originally seen data so it looks like maybe the cache is not getting updated on refresh?

## Expected behavior

- It's a bit suspicious that the retention %'s would change so significantly
- I would also expect that after manually refreshing the dash the data would be updated in cache. A refresh should show the updated data

## How to reproduce

1. Open AARRR dash and refresh retention
2. See the change in %'s across the board
3. Repeat 

## Environment

- [x] PostHog Cloud
- [ ] self-hosted PostHog, version/commit: _please provide_

**Comment by EDsCODE** [comment]
#3039 part of the fix

**Comment by EDsCODE** [comment]
I think this is resolved. There was probably a combination of #3039 and caching issues. Can reopen if discovered again
