### ISSUE TITLE
UI Plugins

### ISSUE THREAD

**Issue by macobo** [PostHog/posthog#2965]
## Is your feature request related to a problem?

I want to add more things to posthog that are more specific to what _what my business_ building but might not be useful for everyone else.

This includes things like:
- Being able to take notes on customer interviews https://github.com/PostHog/posthog/issues/2880
- A metabase/looker-in-posthog product which allows querying our own database https://github.com/PostHog/posthog/issues/1244 and https://posthog.slack.com/archives/CSPHFDZH8/p1610744925024100
- Session recording on Android/iOS apps
- Voice-of-customer segments
- Figma/Intercom/etc integration
- Game about driving tractors

Implementing all of these into the main product has a significant maintenance cost - it bloats the codebase, they might not be useful for all users

## Describe the solution you'd like

Allow plugins to extend Posthog visually by adding new icons in the navbar.

Technically, plugins could include a compiled bundle containing a react app we could render into the app.

## Describe alternatives you've considered

Build all the things, allow users to toggle things on and off.

**Comment by mariusandra** [comment]
Thanks for writing this out! This is definitely something we want to add! I've alluded to this as "frontend plugins" multiple times in the [plugins epic](https://github.com/PostHog/posthog/issues/1896#issuecomment-722357290). It also goes in hand-in-hand with the "plugin webhooks" / "api plugins" task, which would allow the UI plugins to store state and/or run more complicated backend operations. For example I can't imagine the "Looker-plugin" to connect to databases if it was just a compiled react component - we need some backend logic there.

There's a lot of cleanup on the core plugin experience still planned for [this release](https://github.com/PostHog/posthog/issues/2948#issuecomment-761000575) and we'll definitely consider tackling UI and API plugins next.

**Comment by macobo** [comment]
Another datapoint: Customer built out a custom clara.io clone to send data to posthog, we've built out our own NPS plugin. Seems like there is a real need here!
