### ISSUE TITLE
Broken property filter

### ISSUE THREAD

**Issue by yakkomajuri** [PostHog/posthog#2971]
## Bug description

*Please describe.*  
*If this affects the front-end, screenshots would be of great help.*  

Property filter does not select correctly (sometimes??)

https://user-images.githubusercontent.com/38760734/104921976-d4702900-5978-11eb-849d-d7034e4a12a5.mov

**EDIT:** Apparently it does indeed set the filter, just doesn't update the UI

## Expected behavior

Clicking something else other than "equals" should work

## How to reproduce

1. Go to create a cohort
2. Try to add a property filter for anything other than "equals"
3. Sometimes (?) it doesn't work

## Environment

- [ ] PostHog Cloud
- [ ] self-hosted PostHog, version/commit: _please provide_

**Comment by yakkomajuri** [comment]
Added you @macobo because you were working on filters?

**Comment by yakkomajuri** [comment]
Now the page disappeared when I refreshed the page and tried to add the filter?

**Comment by EDsCODE** [comment]
@macobo I'll pick this up real quick dw about it!
