### ISSUE TITLE
Can't create cohorts using other cohorts

### ISSUE THREAD

**Issue by yakkomajuri** [PostHog/posthog#2974]
## Bug description

*Please describe.*  
*If this affects the front-end, screenshots would be of great help.*  

Creating a cohort from another cohort doesn't work.

See our ['Join' cohort for context.](https://app.posthog.com/cohorts/400)

## Expected behavior

Creating cohorts from other cohorts should work as that's a prop filter option.

## How to reproduce

1. Try to create a cohort using another as a match group
2.
3.

## Environment

- [ ] PostHog Cloud
- [ ] self-hosted PostHog, version/commit: _please provide_

**Comment by yakkomajuri** [comment]
Interestingly this persists in app for me but works locally

**Comment by yakkomajuri** [comment]
Seems to be a CH issue

**Comment by neilkakkar** [comment]
doesn't seem to be a problem anymore 👀
