### ISSUE TITLE
Scrolling blocked

### ISSUE THREAD

**Issue by yakkomajuri** [PostHog/posthog#2975]
## Bug description

*Please describe.*  
*If this affects the front-end, screenshots would be of great help.*  

At seemingly random times, scrolling just doesn't work.

At a quick glance, it seems this happens when I click on dashboards??

## Expected behavior

Scrolling should always work

## How to reproduce

I'm not actually sure? But it's been happening way too much during demos.

## Environment

- [ ] PostHog Cloud
- [ ] self-hosted PostHog, version/commit: _please provide_

**Comment by paolodamico** [comment]
+1 this has happened to me quite a few times on demos. Usually you're too busy with the call to identify what was going on, so apologies I can't provide better context.

**Comment by paolodamico** [comment]
I don't think this is happening anymore?

**Comment by paolodamico** [comment]
Closing as this doesn't see to be happening anymore. We can always reopen if it happens again.
