### ISSUE TITLE
Loading a retention cohort takes ages

### ISSUE THREAD

**Issue by yakkomajuri** [PostHog/posthog#2976]
## Bug description

*Please describe.*  
*If this affects the front-end, screenshots would be of great help.*  

Clicking on a cohort on the retention table takes insanely long to load (~30s on the retention table I'm working on)

Potentially could go on https://github.com/PostHog/posthog/issues/2877

## Expected behavior

Load faster

## How to reproduce

1. Click on a cohort on the retention table
2.
3.

## Environment

- [ ] PostHog Cloud
- [ ] self-hosted PostHog, version/commit: _please provide_

**Comment by paolodamico** [comment]
+1, though we probably need to fix #2794 first

**Comment by paolodamico** [comment]
I think this has greatly improved since all the ClickHouse optimizations, closing for now.
