### ISSUE TITLE
Clicking on event in Live actions view opens multiple 

### ISSUE THREAD

**Issue by timgl** [PostHog/posthog#298]
***Thank*** you for reporting bugs - we appreciate every single bug report.

**Describe the bug**
clicking on some events in Live Action opens multiple events

**To Reproduce**
1. Go to live actions view
2. Click on an event
3. Multiple open

**Screenshots**
![image](https://user-images.githubusercontent.com/1727427/76155749-4ca56700-60a5-11ea-8966-39c9c0869b16.png)

**Additional context**
I think this is because events can trigger multiple actions. I think we need to do some work making this a bit more logical anyway

**Comment by SanketDG** [comment]
It seems like the click handler for every action is this.

```
this.state.eventSelected == action.id && (
                                    <tr key={action.id + '_open'}>
                                        <td colSpan="4">
                                            <EventDetails
                                                event={action.event}
                                            />
                                        </td>
                                    </tr>
                                ),
```

I am pretty sure this is being naive and I am somehow missing the bigger picture here, but instead of using `action.id` if we just use the index of `tr`, wouldn't that solve the issue of multiple events opening up?

**Comment by timgl** [comment]
Turns out this was because the polling added the same event every time the polling was called.

I've pushed a commit to fix that.
