### ISSUE TITLE
Update dashboard button doesn't update reference

### ISSUE THREAD

**Issue by yakkomajuri** [PostHog/posthog#2980]
## Bug description

*Please describe.*  
*If this affects the front-end, screenshots would be of great help.*  

If I click on a dashboard panel it takes me to Insights with the 'Update dashboard' button. That button opens a modal with the option to either update or create a new panel.

Clicking create new panel doesn't update the 'update dashboard' reference, so if I then click update again, it will update the old panel, not the new one I just created.

## Expected behavior

Update the "most recently used" panel.

## How to reproduce

Described above

## Environment

- [ ] PostHog Cloud
- [ ] self-hosted PostHog, version/commit: _please provide_

**Comment by Twixes** [comment]
Insights now have a different "On dashboard" button instead of "Update dashboard".
