### ISSUE TITLE
Show Cohort name instead of number on table views

### ISSUE THREAD

**Issue by yakkomajuri** [PostHog/posthog#2983]
## Is your feature request related to a problem?

*Please describe.*

I have no idea what these cohort numbers mean when looking at a table.

## Describe the solution you'd like

Use cohort name instead of number on tables (with a cut-off length ofc). This could be instead of or perhaps even in addition to the cohort number.

<img width="866" alt="Screenshot 2021-01-18 at 13 19 26" src="https://user-images.githubusercontent.com/38760734/104940086-050f8d00-5990-11eb-8b74-624e17a0e42a.png">

## Describe alternatives you've considered

Leave as is.

**Comment by thedeveloperr** [comment]
Can I try on this issue @yakkomajuri  ?

**Comment by yakkomajuri** [comment]
Yup @thedeveloperr - go for it!

**Comment by thedeveloperr** [comment]
@yakkomajuri  How to get to this table ? I can't find this screen.

**Comment by timgl** [comment]
@thedeveloperr When you're on insights, click breakdown by, then select a cohort. Then switch to table view.

**Comment by paolodamico** [comment]
While this particular bug is now addressed with #4646, now we have this new bug in which the table shows no values at all. See [example](https://app.posthog.com/insights?insight=TRENDS&events=%5B%7B%22id%22%3A%22%24pageview%22%2C%22name%22%3A%22%24pageview%22%2C%22type%22%3A%22events%22%2C%22order%22%3A0%7D%5D&properties=%5B%5D&filter_test_accounts=false&breakdown=%5B71%2C98%2C%22all%22%5D&breakdown_type=cohort&date_from=-30d&interval=week&display=ActionsTable). CC @alexkim205 

<img width="700" alt="" src="https://user-images.githubusercontent.com/5864173/121575721-b2de0f80-c9f5-11eb-921a-5600f1b70b7d.png">

**Comment by alexkim205** [comment]
Ah that's not what we like to see. 

@thedeveloperr The tables UI has changed somewhat since the bug was issued. Since the ui overhaul is under the scope of my previous PR I'd be happy to take over from here :)

**Comment by alexkim205** [comment]
I can only reproduce the bug sometimes. See [this one](https://app.posthog.com/insights?insight=TRENDS&interval=day&events=%5B%7B%22id%22%3A%22%24pageview%22%2C%22name%22%3A%22%24pageview%22%2C%22type%22%3A%22events%22%2C%22order%22%3A0%7D%5D&filter_test_accounts=false&properties=%5B%5D&display=ActionsTable) where we do see the counts, and [this one](https://app.posthog.com/insights?insight=TRENDS&interval=day&events=%5B%7B%22id%22%3A%22%24pageview%22%2C%22name%22%3A%22%24pageview%22%2C%22type%22%3A%22events%22%2C%22order%22%3A0%7D%5D&properties=%5B%5D&filter_test_accounts=false&breakdown=false&breakdown_type&display=ActionsTable&date_from=-7d) where we don't, same filters same data.

**Comment by mariusandra** [comment]
For what it's worth, neither "this one" shows me the counts :)

Both return this:
![image](https://user-images.githubusercontent.com/53387/121885940-0feb0580-cd15-11eb-86d1-ab481f3f932c.png)

**Comment by alexkim205** [comment]
Huh that's strange, at least now I know its consistently reproducible 😆

**Comment by yakkomajuri** [comment]
Can confirm I've experienced this on Cloud
