### ISSUE TITLE
Release 1.22.0 – 15 February 2021

### ISSUE THREAD

**Issue by timgl** [PostHog/posthog#2985]
Context:
- Automating clickhouse deployments on customers infrastructure + ways of managing
- Polishing/adding tests

Michael/Marius

- JS ingestion for both Postgres & Clickhouse, including opt-in toggle for self-hosted users. Nearing completion in PostHog/plugin-server#34 and PostHog/plugin-server#116, also PostHog/plugin-server#118 , and also sort out ASYNC_EVENT_ACTION_MAPPING
- Michael to be support hero & squashing sentry bugs

James G/Tim
- Python script -> start up AWS cluster & setup clickhouse
- Templatize helm chart
- Spec out #2984

Karl/Eric
- Sentry bug squashing
- Issue backlog squashing
- Slow query reporter
- e2e test for event ingestion
- Investigate cypress mock out
- Typing all the logics
- Backend test coverage
- Better demo data

Paolo
- ~Going back to all running experiments, check results and take next steps (e.g. navigation-1775, persons-2353, 1694-dashboards, ...). (**Partial**)~
- ~More people are signing up for self-serve plans (and we expect this to go even higher with ops#67), revamp this page a bit to at least include plan information.~
- ~Carryover from past release, team signup page revamp #2734~
- Work with @macobo on email stuff #1938 #1983
- Work with @EDsCODE on ad-hoc engagement analysis (PostHog/retention#6). As we do this analysis we may discover it actually make sense to build this as a feature.
- Stretch. Explore/spec churn prediction & prevention #3032

**Comment by Twixes** [comment]
Here's a list:

- Be support hero/emir/sheikh/person?
- Top priority, above all else, is rollout of plugins on Cloud, which we have planned out, but is pending some tests for production confidence
- Some plugin experience improvements (see Marius' list way below)
- Settings revamp (this kind of depends on our decision regarding new sidebar by @paolodamico):
    - [ ]  account email changing (bit of context: https://github.com/PostHog/posthog/issues/1745#issuecomment-762077778)
    - [ ]  account deletion
    - [ ]  organization rename
    - [ ]  organization deletion
    - [x]  look into state after leaving/being removed from organization
    - [x]  project rename

There's also implementing the brand new great PostHog homepage (#921), which I'm VERY excited to work on with @corywatilo and @lottiecoxon, this however will be able to begin around Feb 8 at the earliest (pending overall design decisions and then finalized homepage layout).

**Comment by mariusandra** [comment]
I'd like to integrate a database explorer in the style of [insights](https://github.com/mariusandra/insights) into posthog, so we could take the first steps in removing our reliance on metabase and could start cornering another market. Basically https://github.com/PostHog/posthog/issues/1244

Though practically speaking, I guess there will still be a lot of plugin work to do. Let's see how this sprint goes.

**Comment by mariusandra** [comment]
Good Expo support is another often requested feature we should think about: https://github.com/PostHog/posthog/issues/1174

**Comment by mariusandra** [comment]
As alluded to in #3040, it might be interesting to take a few days and clean up some things re: toolbar, including making it slightly less annoying (adding snap to edges for example)

**Comment by macobo** [comment]
Last release was sort of unstable.

Here's my 2c with some ideas on how to improve:

Improved process for releasing, beta-testers who use a pre-release version.

Performance regression/bug discovery:
- Trying to "know" which queries are troublesome on self-hosted ahead of time is tricky. The second-best thing is to **instrument** and ping back home whenever an endpoint takes >50 seconds with the query being run.
  - Ideally with other instrumentation info, e.g. SQL queries + timing of them?
  - Q: Is it okay to do this on self-hosted users who have not opted out w/ the full URL?

Testing:
- We don't have a true e2e test that checks whether events from $lib actually reach us and are queriable. 
  - Initial proposal: Use bookmarklet as part of E2E tests (together with full web server including workers) to trigger events on e.g. google.com, queries the results in the webpage and check whether actions trigger and session + recordings show up.
- Frontend testing. I think unit tests won't yield too much value w/ kea but integration tests with stubbed API responses might. https://www.npmjs.com/package/@cypress/react would work well here for doing e.g. scene-level testing.
- Every time we fix something: Save broken query urls to a file, run them against cloud + a postgres instance as part of a release test suite.
- Quick production test suite which tries to log in/register an account every now and again - smoke testing whether everything is fine.
- https://github.com/PostHog/posthog/issues/3085 Catching missing team_id filters automatically.

Code quality:
- Enforce js => ts stricter. I've been an offender of this -> help people if they need help doing this.
- Work on kea typegen to resolve open issues with it.

**Comment by EDsCODE** [comment]
General would be good to tackle:
- better frontend testing along the lines of @macobo's idea. Should be a strong testing process like we have for backend where we patch errors and write tests to prevent regressions
- staging/prod environments as part of the setup process (less urgent but could be a nice to have for developer experience) 
- slackbot from previous cycle

Specifically for me:
- [slackbot](https://github.com/PostHog/posthog.com/issues/887)
- organize bug priority (small todo just writing here to remember)
- [PostHog/retention#6](https://github.com/PostHog/retention/issues/6) w/ Paolo as stated below
- new points on #2877 for insight additions/improvements
- can tackle #2247/#3077 if insight tasks don't overwhelm

**Comment by paolodamico** [comment]
Here are my general thoughts for next release:
- +1 on @timgl's #2984. I think it's quite related to #2822 and will definitely help with retention.
- Think it's worth keeping the great work on #2877 to keep polishing the core analytics experience. The user list double click seems to be particularly painful.
- Related to the above #2247/#3077 aggregated analytics by team/company keeps coming up from user's requests and we could definitely use it ourselves.
- +1 on the toolbar revamp. It's being used (see below a small non-deep sample, toolbar is almost as used as session recording (green line) even though this instrumentation is not widespread yet). We already have a bunch of issues around that #2370, #2349, #1530 and a [new snaps-to-edge design](https://www.figma.com/file/gQBj9YnNgD8YW4nBwCVLZf/PostHog-App?node-id=348%3A1).
<img width="422" alt="" src="https://user-images.githubusercontent.com/5864173/106152932-49640f80-617e-11eb-8b5e-e51436c9f793.png">



As for specifically what I'd like to work on next release, I'd like to take it a bit lighter from major features/improvements and focus on: 
- Going back to all running experiments, check results and take next steps (e.g. `navigation-1775`, `persons-2353`, `1694-dashboards`, ...).
- Spend quite a bit of time talking to users and benchmarking other products.
- As data from instrumentation introduced on _Release 20_ starts to come in, deep dive into feature usage to determine a) what features are most used by retained users, b) what features need improving, c) what features are rarely used by retained users.
- More people are signing up for self-serve plans (and we expect this to go even higher with ops#67), revamp this page a bit to at least include plan information.
- Carryover from past release, team signup page revamp  #2734
- Work with @macobo on email stuff #1938 #1983
- Work with @EDsCODE on ad-hoc engagement analysis (https://github.com/PostHog/retention/issues/6). As we do this analysis we may discover it actually make sense to build this as a feature.
- **Stretch.** Explore/spec churn prediction & prevention #3032

**Comment by macobo** [comment]
- Testing/etc improvements mentioned above
- Weekly email improvements are a leftover from last sprintf #1938 #1983 
- Improve toolbar
- Session recording improvements:
  - Make settings changeable from within sessions page
  - Allow sampling recordings/setting only certain cohorts to be recorded, similar to feature flags. https://github.com/PostHog/posthog/issues/2389
  - Look into https://github.com/PostHog/posthog.com/issues/672#issuecomment-769040207
  - Clearly indicate censorship: https://github.com/PostHog/posthog/issues/2258
  - Tagging support + search capability
  - Indicating sessions where errors occurred (even without sentry integration) https://github.com/PostHog/posthog/issues/3005
  - Stretch: Export as gif?
- Moving kafka over to AWS - causing session recording not to work on some sites

**Comment by mariusandra** [comment]
I was quite eager in my previous comments when suggesting:
- database explorer #1244
- expo integration #1174
- toolbar updates ("feature flags" istead of "stats" for example) #3040

While I would be happy to dedicate time to them, plugins (aka The PostHog Application Platform) should still be the bigger priority:

- JS ingestion for both Postgres & Clickhouse, including opt-in toggle for self-hosted users. Nearing completion in https://github.com/PostHog/plugin-server/pull/34 and https://github.com/PostHog/plugin-server/pull/116, also https://github.com/PostHog/plugin-server/issues/118 , and also sort out ASYNC_EVENT_ACTION_MAPPING
- Lazy VMs (aka improve reloads https://github.com/PostHog/plugin-server/issues/59 and improve scheduling https://github.com/PostHog/plugin-server/issues/15) 
- Automatic GeoIP Plugin https://github.com/PostHog/plugin-server/issues/115
- Secret keys https://github.com/PostHog/posthog/issues/3082
- Defence against malicious plugins https://github.com/PostHog/plugin-server/issues/57 (!! this is a big one)
- Odds and ends: https://github.com/PostHog/plugin-server/issues/98 https://github.com/PostHog/plugin-server/issues/47 https://github.com/PostHog/plugin-server/issues/17

You can see the full status on the plugins project here: https://github.com/orgs/PostHog/projects/4

**Comment by macobo** [comment]
Based on the call, focusing on stabilizing:
- Focus on bug-fixing + introducing tooling for avoiding issues long-term https://github.com/PostHog/posthog/issues/2985#issuecomment-766883128
- Finish weekly email work

**Comment by macobo** [comment]
My proposal for todays planning:
 
Pair up me and Eric. Focus:
- Testing improvements + Bug tracking/fixing + stability improvements

My additions:
- Finishing weekly emails from last sprint #1938 #1983
- Look into PostHog/posthog.com#672 (comment)

From Erics list:
- slackbot
- organize bug priority (small todo just writing here to remember)
- PostHog/retention#6 w/ Paolo as stated below
- new points on #2877 for insight additions/improvements
- can tackle #2247/#3077 if insight tasks don't overwhelm

**Comment by Twixes** [comment]
Released.
