### ISSUE TITLE
Fix "See suggestion and save" Cypress test

### ISSUE THREAD

**Issue by Twixes** [PostHog/posthog#2988]
## Bug description

Not sure what is exactly the bug, but this one Cypress test fails ALWAYS, consistently. It's not flaky, either there's an actual underlying issue or somewhere the UI got changed and the test didn't get updated.

<img width="955" alt="Failed testl" src="https://user-images.githubusercontent.com/4550621/105022316-ea015380-5a49-11eb-9a86-41bb1101f038.png">

<img width="751" alt="Failed suite summary" src="https://user-images.githubusercontent.com/4550621/105022325-eb328080-5a49-11eb-9736-7aef8589a2fd.png">

**Comment by EDsCODE** [comment]
#3002
