### ISSUE TITLE
UX improvements for sessions player event timeline

### ISSUE THREAD

**Issue by macobo** [PostHog/posthog#2989]
## Is your feature request related to a problem?

As part of https://github.com/PostHog/posthog/pull/2954, two issues were pointed out:

> I think it's a bit confusing to have the highlighted action at the top of the event timeline, as you tend to think of the timeline as a linear representation of the time flow.

> Colors of the timeline don't match the rest of the app

## Describe the solution you'd like

1. Add timestamps to event timeline (which makes it clear when the event occurred)
2. Update color scheme

**Comment by paolodamico** [comment]
I think this will become relevant as we start to pick up session recording again. CC @clarkus

**Comment by paolodamico** [comment]
Closing in favor of #2384
