### ISSUE TITLE
Event type breakdown for billing purposes

### ISSUE THREAD

**Issue by paolodamico** [PostHog/posthog#2996]
## Is your feature request related to a problem?

Following https://github.com/PostHog/ops/issues/67 & https://github.com/PostHog/product-internal/issues/19 & @Twixes recommendation, if you're looking how to optimize costs, it's helpful to get a breakdown of the types of events you're ingesting every month. 

## Describe the solution you'd like

For every month I'd like to see a breakdown on the number of events for each type of event (e.g. how many autocapture events, custom events, etc)

## Describe alternatives you've considered

Use the events stats page as a proxy (though you can only see the last 30 days, no historic and no numbers by natural billing periods). 

Send to stripe the breakdown on event types and use their own UI to show this information to users. Faster option but not future-proof, as changing event types could lead to quite a few headaches. 

## Additional context

Also related to #2183

#### *Thank you* for your feature request – we love each and every one!

**Comment by Twixes** [comment]
Perfect timing, this is now possible by using a HogQL breakdown on `event` with an "All events" series.
