### ISSUE TITLE
Clicking retention panel on dashboard shows wrong cohort

### ISSUE THREAD

**Issue by yakkomajuri** [PostHog/posthog#2999]
## Bug description

*Please describe.*  
*If this affects the front-end, screenshots would be of great help.*  

Clicking a retention panel cohort on a dashboard shows a cohort of users that are not actually part of the retention table.

Seems like maybe the cohort is cached separately from the table?

## Expected behavior

Show the right cohort.

## How to reproduce

This happened for me on our dashboard called '[Onboardings'](https://app.posthog.com/dashboard/1655)

## Environment

- [ ] PostHog Cloud
- [ ] self-hosted PostHog, version/commit: _please provide_

**Comment by paolodamico** [comment]
Think this is maybe the same issue as in #2794?

**Comment by yakkomajuri** [comment]
Could be? I'm only experiencing this on a dashboard panel, not on the table view (could be chance though)

**Comment by yakkomajuri** [comment]
Yeah I believe this is related to both #2794 and #3018 - also #3162 gets rid of the retention panel modal anyway
