### ISSUE TITLE
Creating actions is confusing

### ISSUE THREAD

**Issue by jamesefhawkins** [PostHog/posthog#30]
# app.posthog.com/actions

<img width="635" alt="Screenshot 2020-02-08 at 15 07 16" src="https://user-images.githubusercontent.com/47497682/74093292-c5a0a700-4a84-11ea-9f28-ff31a7e5b5f2.png">

The 'pop out' way of doing this is a lot more obvious (with the sidebar) since you can see the product you are tracking, is also offering it "in the app" just making it more confusing? Editing them in the app DOES make sense to me though and is nice.

# Sidebar

## Sidebar item 1

You have to put an action name, then you can save the action without even adding a matchgroup. I would suggest the 'save action' and 'save & new action' buttons don't appear unless a match group is added.

## Sidebar - match element

There are three action types you can pick: match element, match event and page view.

* Match Element

- [x]   * This has an event name shown that isn't editable by default. So why even show it? $autocapture doesn't make any sense to me
- [x]   * 'inspect element' is a really important button, yet it's not even capitalised and it needs margin: 10px; or something adding
- [x]   * Under 'inspect element' there are a bunch of text inputs. Would there ever be a time when these should be shown BEFORE the element is clicked with inspect element? If not, they should appear once that is done - else as a user I don't know where to start.
- [x]   * Once I have selected an element, ideally I'd have it populate the link href, the element name, the text, and the selector by default THEN just have one of these pre-selected.
- [x]   * I don't actually know what 'Match url' does. Does it mean this specific element is matched but ONLY on this page, or does it turn it into a page view instead? Clarifying the language would help. 
- [ ] 

## Sidebar - Match Event

- [x] * When I use this for posthog.com's tracking, it doesn't let me actually input any text into the event name so I think there is a bug:

<img width="149" alt="Screenshot 2020-02-08 at 15 10 34" src="https://user-images.githubusercontent.com/47497682/74093401-3a281580-4a86-11ea-8f37-e676f0b538eb.png">

- [x] * I also don't understand how to use this - do I need to just write in an event that matches the name of an event in the javascript? A line of explanation would help (perhaps an 'i' type icon?)
- [x] * Same logic re 'Save action' as above - this shouldn't show unless an action has actually been created - there are otherwise too many buttons on show at once that don't make sense to show yet.

## Sidebar - Page View

- [x] * This shows 'event name' as $pageview, and is non editable. Why even show that? It just looks technical and doesn't help me as a user in any way.
- [x] * Can I put regex or anything into Match url? It sort of feels like I could, but maybe I can't. If this function exists, put an 'i' type icon with some explanation, else don't.

**Comment by timgl** [comment]
All fixed! It's live but would be great to go through another QA
