### ISSUE TITLE
WIP Break down a trend graph into the actual users

### ISSUE THREAD

**Issue by jamesefhawkins** [PostHog/posthog#300]
It'd be nice to click a data point on the trend graphs, to see all the users or actions that made up that data as a table.

**Comment by timgl** [comment]
I think the strategy for this is

**Backend**

Create a new endpoint, much like [trends](https://github.com/PostHog/posthog/blob/master/posthog/api/action.py#L257), but that returns a list of people. `Event.objects.filter_by_action` will already have a person_id, so you can do something like

```python
people_ids = Event.objects.filter_by_action(action).filter(self._filter_events(request)).values('person_id')
people = Person.objects.filter(team=team, id__in=people_ids[0:100])
```

And then use the PersonSerializer to serialize the person.

**Frontend**

Marius, I think this will be mostly up to you. I think it'd be nice that if you click on a data point, it opens a modal with the list of users (hitting the above endpoint, with all the filteres applied + filtered by the specific day). I think you should just be able to re-use the People element for that.

Happy if you think there's a better solution.
