### ISSUE TITLE
Sample session recording

### ISSUE THREAD

**Issue by paolodamico** [PostHog/posthog#3004]
## Is your feature request related to a problem?

Related to #2822. After I've enabled session recording (or just installed PostHog), I would have to wait at least a few minutes to see my first session recording come in.

## Describe the solution you'd like

Maybe for the first 24 hours after enabling session recording, if a recording hasn't come in, show me a sample recording of Hogflix. This way I can see the value of session recording first-hand without having to wait.

## Describe alternatives you've considered

- Wait for a real recording to come in.
- Take the user to Hogflix to generate a recording themselves. More friction, but it might also be a better experience to watch your own recording.

**Comment by macobo** [comment]
We now have at least 1 sample session recording when you sign up in the new onboarding flow.

**Comment by Twixes** [comment]
Is this closable in this case?

**Comment by paolodamico** [comment]
I think it's still worth showing the sample session recording without you having to change to the demo project, so I would still keep this around. Not everyone will have the demo project and it won't be very intuitive to go look for it there.

**Comment by benjackwhite** [comment]
Closing in favour of https://github.com/PostHog/posthog/issues/11772
