### ISSUE TITLE
Allow rolling feature flags out for multiple groups independently

### ISSUE THREAD

**Issue by macobo** [PostHog/posthog#3007]
## Is your feature request related to a problem?

We use feature flags pretty extensively at posthog together with rollout percentages. This helps us see if users convert better after introducing a major new feature.

This is great, but makes it annoying for posthog team - at any given time, some features will be turned off for us, even if we developed it ourselves.

## Describe the solution you'd like

1. Change semantics of filters to be OR rather than AND. That is, if I include 2 cohorts in my filter (Posthog Team + Real users), all of them would receive the feature. Currently only users in both cohorts would.
2. Allow changing rollout percentage per group. E.g. 100% of Posthog Team and 50% of Real users.

## Describe alternatives you've considered

Add multiple feature flags in code

**Comment by yakkomajuri** [comment]
Hmm so we can't do 2, but we can do 1 - you just have to go through a cohort i.e. create a cohort that's an `OR` combination of 2 others.

That is unfortunately broken too though :D #2974

**Comment by weyert** [comment]
This sounds like a great change. Excited about this  :D

**Comment by Twixes** [comment]
Did #3030 resolve this? @macobo
