### ISSUE TITLE
Getting 502 on `/api/insight/trend/` after upgrade to `1.20.0`

### ISSUE THREAD

**Issue by FUSAKLA** [PostHog/posthog#3010]
## Bug description
Getting `NaN` in some  dashboard panels with breakdown using 7d time period after upgrading from `1.19.0` to `1.20.0`.
But not all some panels render just fine but some renders `NaN` and writes flash message `Unexpected exception`.

I see that the request ends up with HTTP status `502` from Nginx in front of my web instances.
I do not see the failed calls in the logs of the web instances at all.

I wanted to check if something changed between those versions that might have caused this?
The only explanation I can think of for now is that all the PostHog web instances are busy(overloaded) and the Nginx would have no upstream to send it to but that should end up with 502. 

## Environment

- [ ] PostHog Cloud
- [x] self-hosted PostHog, version/commit: 1.20.0

Running in Kubernetes using upstream docker images.

**Comment by FUSAKLA** [comment]
Also, I'm seeing lots of errors in the browser console :/
![image](https://user-images.githubusercontent.com/6112562/105202600-73944c80-5b42-11eb-9e3a-c8cc19ea82e7.png)

Those `Change` are spamming there all the time

**Comment by FUSAKLA** [comment]
Ok, slowly narrowing it down, I managed to find a log in the Nginx that PostHog closed the connection prematurely 
```
nginx posthog-external-nginx-12021/01/20 17:30:56 [error] 6#6: *21844 upstream prematurely closed connection while reading response header from upstream, request: "GET /api/insight/trend/?events=%5B%7B%22id%22%3A%22%24pageview%22%2C%22math%22%3Anull%2C%22name%22%3A%22%24pageview%22%2C%22type%22%3A%22events%22%2C%22order%22%3A0%2C%22properties%22%3A%5B%5D%2C%22math_property%22%3Anull%7D%5D&display=ActionsPie&insight=TRENDS&interval=day&breakdown=%24browser&date_from=-7d&breakdown_type=event&from_dashboard=6 HTTP/1.1"
```
This could be caused by some new timeout introduced in the `1.20.0` version possibly by upgrade of some dependencies even?
Or some unhandled exception that would crash the whole processing of the request without responding :thinking:

**Comment by FUSAKLA** [comment]
Hm, I'm completely blind here. The web instances tells me nothing what happened.
Would you accept PR which would set event the `root` logger severity level using the `DJANGO_LOG_LEVEL` ENV variable? 

Here: https://github.com/PostHog/posthog/blob/master/posthog/settings.py#L566

**Comment by timgl** [comment]
Yep we'd definitely accept that PR! I also have no idea what's going on here and we haven't been able to reproduce

**Comment by FUSAKLA** [comment]
Hmm, I see the request fails after approx. 30s
![image](https://user-images.githubusercontent.com/6112562/105210834-da6a3380-5b4b-11eb-96bb-d1f052a38d47.png)

This looks like I'm hitting the Gunicorn 30s limit for request https://docs.gunicorn.org/en/stable/settings.html#timeout

Ok, I'll send that PR and try to increase the timeouts on Gunicorn. Maybe is the 1.20.0 version really just a bit slower, and it was the few seconds which exceeded the timeout.

**Comment by EDsCODE** [comment]
Are these failing requests all from dashboards? If you go to the trends page directly and use the same filters does it load at all?

**Comment by FUSAKLA** [comment]
So not even increasing the Gunicorn timeout is helping... :/

@EDsCODE yes unfortunately even on the trends page directly, if I query shorter time range (1 day instead of 7 days) it's slow but works.

**Comment by EDsCODE** [comment]
Got it, do you know how many events are you in your DB right now? 

I don't recall off the top of my head that we put anything that would significantly change those trend queries but I will take a look and see what it could be

**Comment by FUSAKLA** [comment]
I went through the commits between 1.19 and 1.20 and did not find anything that could be related, but I do not know the codebase that much.

We have currently 32621482 events in the `posthog_event` table. That is over circa 3+ months.
But if I downgrade to 1.19 the queries work just fine even though they take a bit longer but still. So regardless of the databaze size it's somehow connected to the version.

**Comment by FUSAKLA** [comment]
I'm not sure if this was part of the 1.20 release?
https://github.com/PostHog/posthog/pull/2876

**Comment by EDsCODE** [comment]
that should not have been included. I'll do some digging. In any case, with 30mil events in postgres it would probably be best for you to allow us to help you upgrade into using clickhouse as more things will inevitably be timing out!

**Comment by FUSAKLA** [comment]
Well, I'd love to upgrade, but I'm afraid our company won't be willing to pay for the enterprise license, at least for now 
while we are still kind of evaluating the benefits of PostHog. Hopefully will eventually get there :)

**Comment by EDsCODE** [comment]
When you run the trends query, is it much faster if you don't add the breakdown?

**Comment by FUSAKLA** [comment]
Yes, if I try it on last 24h without breakdown it takes 2,5s and with breakdown by Browser it's 19s.

**Comment by lksv** [comment]
Probably table partitioning could bring the postgress speed on the next level. @EDsCODE did you thing about this way of speed up?

**Comment by EDsCODE** [comment]
Definitely a possibility, but I'm more convinced it's a bad commit that is degrading the query since it was working somewhat better in 1.19 than 1.20

**Comment by EDsCODE** [comment]
@FUSAKLA I'm fairly certain i pinpointed the issue. Last month right after we cut the release for 1.19, I was [patching](https://github.com/PostHog/posthog/pull/2785) an aggregated value that wasn't being counted properly. This normally would double the amount of queries needed for a trend graph, but if a breakdown has many values, this would obviously lead to overload of queries. 

I will look into a different way to do this aggregated count without degrading query performance! Thanks for bringing this to our attention

**Comment by FUSAKLA** [comment]
Great :+1: thanks for looking into it!

**Comment by FUSAKLA** [comment]
I upgraded to 1.21.0 yesterday and unfortunately the issue persists for the pie charts (actually did not expect it to be fixed regarding the name of the PR that resolved this). Are there any plans on trying to optimize this more?
Just so I know if we should expect some progress here or try to speed up the DB possibly?

**Comment by timgl** [comment]
@FUSAKLA What kind of volume do you have (you can check by clicking on the green tick in the top bar)? It sounds like you might just need to upgrade your DB instance or even upgrade to Clickhouse.

**Comment by FUSAKLA** [comment]
Hi, the ingest rate is quite big already discussed [above in this issue](https://github.com/PostHog/posthog/issues/3010#issuecomment-763860970) same as [the idea of upgrading](https://github.com/PostHog/posthog/issues/3010#issuecomment-763872186).

Please do not take it anyhow bad, I'm thankful for all the amazing work you are doing on PH! So I really just wanted to make it clear if we should expect any improvements on this or try to resolve it by other means sticking to the free license for now :)

**Comment by timgl** [comment]
understood. I guess your only other option here would be to either get rid of a bunch of data or grab a bigger instance for your DB.

**Comment by FUSAKLA** [comment]
Right, the DB does not seem to be anyhow exhausted from the resources side which is curious.
I tried the partitioning, but that did not help. I'll eventually try to re-partition it to smaller tie windows and by specific events.

Thanks for the info, we will manage somehow.
