### ISSUE TITLE
Create a design system for PostHog

### ISSUE THREAD

**Issue by timgl** [PostHog/posthog#302]
Stub ticket for @pedroapfilho  :-)

**Comment by mariusandra** [comment]
Hi everyone! I think the sooner PostHog gets a design system the better, as less code will need to be rewritten. So I'd like to propose something.

In my last project I finally decided to try [ant.design](https://ant.design/components/button/)... and it has been great ([see a demo of the app](https://demo.insights.sh/), pay attention to the modal, dropdowns, etc... the big table part is custom). I have never felt so productive with a UI library as I do with it. It's fully React-based and rather simple to tweak with css if needed. It has every component you can ever imagine.

I've tried many other UI libraries and never understood why a friend of mine was so into this "antd"... as on the surface it looks just like any of the other ones... until I tried it myself. Everything just works seamlessly together in it... and I've been really productive with it.

So I know it's a random and a bold recommendation, but I would suggest to migrate PostHog over from the css class based bootstrap implementation to antd. It could provide you with a professional-looking UI in a very short time.

**Comment by jamesefhawkins** [comment]
User feedback on the UX: "Nice roadmap. One thing I'm missing (though maybe it goes under parity in some way) is UX. While some of the feature are already quite good, I worry that my product owner will struggle a bit with it. And here, I don't think you need to invent the wheel, there are good examples out there."

**Comment by EDsCODE** [comment]
In process: #531

**Comment by timgl** [comment]
^ per above, closing this in favour of #531
