### ISSUE TITLE
Page is jumpy on first load (new nav)

### ISSUE THREAD

**Issue by yakkomajuri** [PostHog/posthog#3020]
## Bug description

*Please describe.*  
*If this affects the front-end, screenshots would be of great help.*  

Similar to what we had with the website where the page loads in a jumpy manner. 

Sider loads late and pushes the whole rest of the page to the right.

## Expected behavior

Load without jumpiness

## How to reproduce

1.
2.
3.

## Environment

- [ ] PostHog Cloud
- [ ] self-hosted PostHog, version/commit: _please provide_

**Comment by yakkomajuri** [comment]
I guess the reason for this is the feature flag

**Comment by macobo** [comment]
One of the issues was image caching - I added a rule to cloudflare to avoid jumping due to posthog logo in nav:

![2021-02-08_16-11](https://user-images.githubusercontent.com/148820/107230899-4db6e500-6a28-11eb-9791-6321f2133fb8.png)

@yakkomajuri are things better now?

**Comment by yakkomajuri** [comment]
Not really - nav still comes in and pushes everything to the right after the main section has loaded
