### ISSUE TITLE
Saved funnels load more button doesn't work

### ISSUE THREAD

**Issue by EDsCODE** [PostHog/posthog#3021]
## Bug description

*Please describe.*  
- clicking load more on the saved funnels panel when there are more than 5 funnels doesn't show more

*If this affects the front-end, screenshots would be of great help.*  

## Expected behavior
- should show more funnels

## How to reproduce

1. Go to funnel insight
2. click load more (if you have more than 5)

## Additional context
- found this error on a session recording

**Comment by yakkomajuri** [comment]
When/where does this happen or has it been fixed? can't reproduce

**Comment by Twixes** [comment]
Oh right, I fixed this in #3153. ;)
