### ISSUE TITLE
Bug: Toolbar disappears on subdomain

### ISSUE THREAD

**Issue by jamesefhawkins** [PostHog/posthog#303]
**Describe the bug**
If I click from example.com to app.example.com, with 'example.com' as the URL in settings, the toolbar disappears.

This means I can't record actions for app.domain.com

**To Reproduce**
1. Create URL example.com in settings
2. Create new action, and navigate from example.com to app.example.com
3. The tool bar disappears

**Expected behavior**
The toolbar should not disappear

**Additional context**
I am wondering if PR #273 may happen to fix this regardless.

**Comment by mariusandra** [comment]
I guess this issue with the old editor/toolbar has been superseded now? 

If the snippet is installed, the toolbar should work on all domains. If not, it's a bug and that we track separately in #1101
