### ISSUE TITLE
Allow analyzing cohorts (new users, active users, slipping away users)

### ISSUE THREAD

**Issue by macobo** [PostHog/posthog#3032]
## Is your feature request related to a problem?

Every SaaS product has high-impact clients. Once I have defined them as a separate cohort, I want to stay on top of them - know who are new, know who are active and know who are at risk of churning/slipping away.

## Describe the solution you'd like

Under a cohort I have different tabs for:
1. New users
2. Active users (using some unknown criteria)
3. Inactive users (who are at risk of churning)

## Describe alternatives you've considered

Not using posthog for this or digging via retention graphs.

## Additional context

Related tickets https://github.com/PostHog/posthog/issues/3031 https://github.com/PostHog/posthog/issues/2350

Defining active: for web, even something simple as $pageview per day is imo enough to get started - maybe use pageview count as sorting criteria? Ideally this would be the same thing as you're using in retention graphs

This would be really powerful in emails as well - here's some users who might be slipping away. Intercom does a good job with these emails.

**Comment by paolodamico** [comment]
This is something we could definitely use. Of particular interest would be an early warning of retained users at risk of churning. I would be keen on discussing this on the next sprint.

**Comment by macobo** [comment]
Note: Group Analytics has landed since we made this ticket and there's no "cohorts for groups" feature. If we end up solving this it's also worthwhile to consider how an approach that works for B2B users would look like.

cc @EDsCODE

**Comment by macobo** [comment]
Note: Group Analytics has landed since we made this ticket and there's no "cohorts for groups" feature. If we end up solving this it's also worthwhile to consider how an approach that works for B2B users would look like.

Maybe this _isn't_ a cohort flow at all, but rather a third kind of analysis based on persons/groups with the goal of supporting customer support and sales teams?

cc @EDsCODE @marcushyett-ph
