### ISSUE TITLE
Integrate with angulartics2

### ISSUE THREAD

**Issue by timgl** [PostHog/posthog#3046]
## Is your feature request related to a problem?

As a user who users angulartics, I want to be able to send events to PostHog.

## Describe the solution you'd like

Have a look at the current [mixpanel implementation on angulartics2](https://github.com/angulartics/angulartics2/tree/master/src/lib/providers/mixpanel). We should be able to adapt that pretty easily to use PostHog instead.

**Comment by carlosmarin96** [comment]
Hi, I'm new contributing to open source projects. I'd like to contribute. Could I take it?
