### ISSUE TITLE
Need advanced feature for attribute selectors 

### ISSUE THREAD

**Issue by moonrailgun** [PostHog/posthog#3047]
## Is your feature request related to a problem?

Hi, our project need advanced feature about attribute selectors,

just like 
- `a[href*="example"] ` 
- `a[href$=".org"] ` 
- `a[href^="www"]`
- `a[class~="logo"]`

## Describe the solution you'd like

In source code  https://github.com/PostHog/posthog/blob/master/posthog/models/event.py, yours looks like just support simple feature like `a[href="example"] ` , 

But in some case, we would like to find following data like `data-tracker="login-form-submit"` and `data-tracker="login-form-reset"` by only filtering it with`button[data-tracker^="login-form"]`

## Additional context

Just think is any performance problem for SQL? I have no idea about it 

Related link: https://developer.mozilla.org/en-US/docs/Web/CSS/Attribute_selectors

**Comment by paolodamico** [comment]
Thanks for your request @moonrailgun! This would certainly be very helpful. Adding it to our improvements for core analytics EPIC.

**Comment by paolodamico** [comment]
Well I think we've seen this come up every now and again with newer users of the product. Perhaps worth keeping in the backburner.
