### ISSUE TITLE
deleting old session recordings

### ISSUE THREAD

**Issue by bartol** [PostHog/posthog#3059]
## In what situation are you experiencing subpar performance?

is there a way to delete old session recordings or auto-expire after some time because it is taking a lot of space even for low trafic website.

Postgres session recording table size | ~5975164 rows (~5051 MB)

## Environment

- [ ] PostHog Cloud
- [x] self-hosted PostHog, version/commit: 1.20.0

**Comment by yakkomajuri** [comment]
Thanks for opening this up!

cc @macobo

**Comment by macobo** [comment]
This has been added, look forward to next release!

**Comment by mariusa** [comment]
`Automatically delete old session recordings` isn't present at https://app.posthog.com/project/settings

**Comment by neilkakkar** [comment]
Hey @mariusa , on https://app.posthog.com/instance/settings, the `RECORDING_WEEKS_TTL` is the setting you're looking for. By default its set to 3 weeks.

**Comment by mariusa** [comment]
Thanks Neil! Attached is what I see there, with AdBlock disabled
![2022-08-08_20-31](https://user-images.githubusercontent.com/1283842/183478657-f89b2e53-8486-4bb7-9e88-ba33665c6400.png)

I could find the Project & Org settings via UI. is there a way to navigate to 'instance' settings via UI too? Sorry if that's obvious.

**Comment by neilkakkar** [comment]
Ah, the original issue was for self-hosted users. If you're on cloud, then we control this setting, as we manage storage, not you 😅 . It's set to 3 weeks on cloud.

**Comment by mariusa** [comment]
Thanks for clarification! 3 weeks is great.

**Comment by scoobhidu** [comment]
hey @neilkakkar @macobo @mariusa is there a way we can delete just the recordings after a day - i don't want to lose any data / logs other than recordings?
