### ISSUE TITLE
management/commands errors

### ISSUE THREAD

**Issue by sophie200** [PostHog/posthog#3060]
## Bug description
(Import lines)
https://github.com/PostHog/posthog/blob/master/posthog/management/commands/create_bulk_events.py#L21
https://github.com/PostHog/posthog/blob/master/posthog/management/commands/create_bulk_events.py#L22

An ImportError is raised when you run this module because Funnel and FunnelStep have been deleted. There are also some queries that reference these deleted models as well. I was wondering does it matter if this module is updated because it seems like this file hasn't been updated in a while, or are there other reasons that these queries and imports still exist? Thanks.

(Lines of some queries that reference deleted models)
https://github.com/PostHog/posthog/blob/master/posthog/management/commands/create_bulk_events.py#L220
https://github.com/PostHog/posthog/blob/master/posthog/management/commands/create_bulk_events.py#L221

## Environment

self-hosted PostHog, master branch (11/21/2021)

**Comment by yakkomajuri** [comment]
Oh yeah thanks for the heads up on this! We don't really use this command anymore so I'll just go ahead and remove it. In the meanwhile you can use `generate_revenue_data` or take a look at this PR: https://github.com/PostHog/posthog/pull/2629
