### ISSUE TITLE
Support 'formulas' in trends

### ISSUE THREAD

**Issue by yakkomajuri** [PostHog/posthog#3062]
## Is your feature request related to a problem?

*Please describe.*

I'm unable to migrate charts from Mixpanel that use 'formulas' - user-specified mathematical operations between events.

This is important for determining ratios as my key metrics and seeing their evolution over time e.g. `completed_purchase / added_to_cart * 100`

## Describe the solution you'd like

A simple formula tool supporting basic custom mathematical operations.

## Additional context

Reported by a user.

**Comment by yakkomajuri** [comment]
Woop! Very happy to close this

**Comment by timgl** [comment]
Hm yeah there's still some work to be done before we can enable this for everyone but it's documented in #3375

**Comment by yakkomajuri** [comment]
Yeah for sure, but I guess as far as the scope of this issue goes, it is completed.

Although maybe it isn't completed from a user's point of view? Since they don't have it on.
