### ISSUE TITLE
Load More People under retention list of users doesn't work

### ISSUE THREAD

**Issue by jamesefhawkins** [PostHog/posthog#3071]
## How to reproduce

1. Go to our [internal retention dashboard](https://app.posthog.com/dashboard/501)
2. Scroll to bottom
3.Click Load More People
4. Error in console:
<img width="297" alt="Screenshot 2021-01-25 at 11 53 57" src="https://user-images.githubusercontent.com/47497682/105702654-026ae580-5f04-11eb-9a81-3ecafc35cfe6.png">

Either there are no more people in which case the button shouldn't appear, or there are more people and there's a problem retrieving them.

## Environment

- [X] PostHog Cloud
- [ ] self-hosted PostHog, version/commit: _please provide_

**Comment by macobo** [comment]
Seems to have been broken by https://github.com/PostHog/posthog/pull/2669/files
