### ISSUE TITLE
[QA] User creating an action from the toolbar didn't reflect data

### ISSUE THREAD

**Issue by EDsCODE** [PostHog/posthog#3076]
## Bug description

*Please describe.*  
- toolbar heatmap shows a button with a certain amount of clicks but after creating the action, the clicks aren't there
- likely due to mismatch of what the heatmap is inspecting and the actual selector that's saved

## Expected behavior
- should match what the heatmap suggests

## How to reproduce
Haven't been able to yet

**Comment by mariusandra** [comment]
Here it would be great to have a reproducible example. Slight differences in relevant DOM elements can make all the difference in causing the bug.
