### ISSUE TITLE
Unique property aggregator filter

### ISSUE THREAD

**Issue by paolodamico** [PostHog/posthog#3077]
## Is your feature request related to a problem?

As **requested by a user** I may want to group users who have a unique value for a specific property. For example: if I send an account/enterprise company, and I want to know `$pageview`s by unique accounts/companies.

## Describe the solution you'd like

I would like us to add an additional **property** aggregator that is "Unique".

<img width="196" alt="Screenshot 2021-01-25 at 6 19 01 PM" src="https://user-images.githubusercontent.com/5864173/105740808-d8341a80-5f39-11eb-994e-1b94870c6805.png">

## Describe alternatives you've considered

- SQL query?
- Using a proxy based on active users?

## Additional context

- Builds on #2630.
- Closely related to #2247, this might be seen as an initial step or a simplified implementation.

**Comment by samwinslow** [comment]
Is this still active?

**Comment by macobo** [comment]
This seems like group analytics, rather than anything else
