### ISSUE TITLE
Add dynamical changelog/update available

### ISSUE THREAD

**Issue by timgl** [PostHog/posthog#308]
**Is your feature request related to a problem? Please describe.**
At the moment there's no way for people to know whether there's a new update of PostHog, they just need to occasionally remember to update.

**Describe the solution you'd like**
Have a dynamically loaded changelog in the top right of the app, with a change of color if a new update is available.

**Describe alternatives you've considered**
Manually update.

**Solution**

Create a small Flask app that runs under `update.posthog.com` with 2 endpoints
`/changelog` - fetches a markdown/html page with the updates
`/latest_version` - which returns the latest active version.

We can pull both dynamically from the GitHub api.

**Comment by allan-simon** [comment]
note it does not need to be a flask app, run it in a s3 bucket  that serves "changelog.json" (that you configure as a webiste , so you have the nice domain name) ,  and "latest_version.json" , and have this file being uploaded as part of your release process :) 

you divide your cost by 1000 and it's one less system to keep up to date, with no downtime etc.

**Comment by timgl** [comment]
@allan-simon Ah in fairness I did specify this poorly (as I was about to do it myself ;-)) but the reason for the flask app was so we could dynamically load data from GitHub, rather than having to have this as a step in the release process.

I created this, [what do you think?](https://github.com/PostHog/posthog-update/blob/master/app.py)

**Comment by allan-simon** [comment]
I don't deny that it's simple to implement, but then why not having your frontend directly request it ? otherwise to have maintained this kind of  stuff,  having a github action that upload this two information in s3 takes even less lines, but that's only my opinion :)
