### ISSUE TITLE
Stickiness with compare is buggy

### ISSUE THREAD

**Issue by EDsCODE** [PostHog/posthog#3124]
## Bug description

*Please describe.*  
- Using compare option with stickiness gives a really buggy graph. The numbers don't seem to make sense and clicking on datapoints don't give you people

## Expected behavior
- should work

## How to reproduce

1. Go to stickiness insight
2. click compare (it crashes right now)

## Environment

- [ ] PostHog Cloud
- [ ] self-hosted PostHog, version/commit: _please provide_

**Comment by macobo** [comment]
Will https://github.com/PostHog/posthog/pull/3195 fix this? Mind verifying + sending a link to a broken graph if it does not.
