### ISSUE TITLE
Billing threshold alert

### ISSUE THREAD

**Issue by paolodamico** [PostHog/posthog#3127]
## Is your feature request related to a problem?

With the introduction of usage-based pricing (https://github.com/PostHog/posthog.com/pull/900 & https://github.com/PostHog/ops/issues/67), billing will be variable every month. I want to make sure I don't get any crazy surprises on a given month.

## Describe the solution you'd like

I'd like to be able to set a threshold for which I get a notification if I have exceeded. That way I can take prompt actions if needed. See DigitalOcean's example below.

![image](https://user-images.githubusercontent.com/5864173/106260469-bd56f400-6220-11eb-8287-21acfe194f6d.png)

**Comment by samwinslow** [comment]
I'd be keen to work on this and #7083 if we think it's a priority. Support requests come in about this sort of thing quite often.

Cc @paolodamico @kpthatsme

**Comment by paolodamico** [comment]
Think this will start to become more relevant as we do more upsells. I also personally think it's a better suited solution rather than a hard limit because what would we do when the users hit the hard limit? Stop ingesting their events?

**Comment by mariusa** [comment]
>  what would we do when the users hit the hard limit? Stop ingesting their events?

Yes. We set a limit because we have a limited budget.

Looks like there are 2 features: Budget limit (mandatory) and Usage alert (optional; can be seen in Billing page too)
