### ISSUE TITLE
Unintuitive filter "autocomplete"

### ISSUE THREAD

**Issue by yakkomajuri** [PostHog/posthog#3133]
## Is your feature request related to a problem?

*Please describe.*

Our autocompletion (or whatever you want to call it) when typing on filters uses the underlying filter name instead of the display name (or both), which leads to problems like this:

<img width="733" alt="Screenshot 2021-01-29 at 14 24 00" src="https://user-images.githubusercontent.com/38760734/106286601-bab6c780-623d-11eb-89f2-6f317314162b.png">

Typing 'lib' works but 'libr' doesn't since the underlying prop is `$lib`

## Describe the solution you'd like

Smart autocomplete that uses both the display name and underlying name.

## Describe alternatives you've considered

Use the display name instead.

**Comment by samwinslow** [comment]
Fixed by #4091
