### ISSUE TITLE
persons-2353 causing blank screen when looking up user by email

### ISSUE THREAD

**Issue by EDsCODE** [PostHog/posthog#3137]
## Bug description

*Please describe.*  
- if users identify their users using an email (or anything that when turned into a url string will have encoded characters), the urlToAction hook in logics won't trigger when needed
- This is relevant in the changes that are behind feature flag `persons-2353`. 
- I have a person in the person list identified by their email so their email is the distinct id but when I go to the user at `http://localhost:8000/person/john%40doe.com` I get a blank screen because the logic isn't recognizing `john%40doe.com` as a valid :id param in line 123 of personsLogic.ts and no api call is being made. 
- I found that the period is causing the listener to not fire

## Expected behavior
The link should work like before when you click on a person that you want to lookup by email

## How to reproduce

1. Have a regular instance 
2. Identify a user using their email
3. try to click on the user with feature flag `persons-2353` enabled 

## Additional context
I'm guessing there's an easy fix I'm just not sure what urlToAction won't fire with a period in the url. @mariusandra this might be a quick fix for you

**Comment by yakkomajuri** [comment]
Closing #2979 in light of this

**Comment by mariusandra** [comment]
Could the issue be larger than that? E.g. what if there are other symbols like `/` or `🤪` in a distinct id? A wildcard `*` should catch all everything and return it in a `_` 

![image](https://user-images.githubusercontent.com/53387/106398868-90b7fd80-6415-11eb-9518-9253b85120be.png)

**Comment by yakkomajuri** [comment]
Has been solved by #3139
