### ISSUE TITLE
Events vs Actions need to be displayed/explained better

### ISSUE THREAD

**Issue by Tannergoods** [PostHog/posthog#314]
**Is your feature request related to a problem? Please describe.**
A user sent a video of their experience setting up PostHog and it was clear in the video that PostHog looks too rough for easy use without reading all of the documentation really clearly and should be much more intuitive to get started. 
Actions are created as a way to clean up events - it should not take a video to explain this.

**Describe the solution you'd like**
Events should be more prominent (potentially above actions) or the two should be linked in someway so that the user understands Events (both single and multiple) can be sorted into actions

**Describe alternatives you've considered**
More promotion of our training materials? 

**Additional context**
<img width="1433" alt="Posthog" src="https://user-images.githubusercontent.com/60791437/76369013-528e8880-62ef-11ea-9d7b-c19c754f6f19.png">

**Comment by timgl** [comment]
I'm going to solve this like this:

![image](https://user-images.githubusercontent.com/1727427/76382178-15d58800-6315-11ea-86ef-23658b4c54cb.png)

This way, Actions become a subset of Events. This makes sense with the "Actions are a way of cleaning up large volumes of Event data," which makes it a helper tool for Events. This matches the model people have of product analytics software closer.

**Comment by timgl** [comment]
As a related ticket, I think we also need to allow people to filter the Trends page by Events (not just actions). See #318
