### ISSUE TITLE
Support Czar Reflection 1/18 -> 1/29

### ISSUE THREAD

**Issue by EDsCODE** [PostHog/posthog#3140]
Support Czar

**Channels to watch**
- posthog users slack
- papercups messages (some overlap with posthog users)
- github issues
- sentry issues

**Points of reflection:**
- Most issues were easily resolvable as they’re just configuration questions, clarifications about functionality, and small bugs that are resolvable
- Some issues are incredibly hard to debug as there’s very little information of what’s failing and confined to a certain deployment setup that a user decided to use
    - In these cases, I would suggest not doing what I was doing which was asking a chain of clarification questions that would help uncover the problem but sometimes chase away the user as they just didn’t want to keep up
    - However, when a user did keep up with the issue, it helped significantly as the problem was usually resolvable (Ilia helped me uncover this https://github.com/PostHog/posthog/issues/3137 after a week of back and forth trying different things)
    - Not ideal if it takes a lot of time, but for user experience with support it often helped to ask the person who was most familiar with the area where the problem was occurring (sessions -> Karl, infra -> James, etc)
- Anecdotally, the support issues seemed much busier during EU hours as I would have only maybe 3-4 during the day 
- The issues, even if only a handful, definitely eat into your day if you go hunting for small bugs which make it hard to push big pieces of work
- I spent most of the day searching through sentry for quick fixes when there weren’t any active support tickets to deal with
- I think a good extra responsibility for support hero is patching issues from our team when there’s downtime too—fixing up small bugs and paying off some tech debt

**Comment by Twixes** [comment]
Thanks for this. I'll close since this info is more fitting for the handbook and we have PostHog/posthog.com#933 for that it seems.
