### ISSUE TITLE
Explain benefits of the paid feature in the upgrade modal

### ISSUE THREAD

**Issue by Twixes** [PostHog/posthog#3148]
## Is your feature request related to a problem?

Currently the upgrade modal says what the feature is, but it doesn't explain how beneficial it is (e.g. that multiple projects allow you to track multiple product within one organization).

## Describe the solution you'd like

Make it possible to display benefits in some way in the upgrade modal.

## Additional context

Talked with a user who was confused by the upgrade modal due to this.

**Comment by paolodamico** [comment]
For what is worth, I think this will be less important with usage-based pricing as the incentive to upgrade will be a lot more straightforward. You upgrade to get more than the 10k event limit (you only have to pay for what you use), and you get a bunch of premium features (which will be more than just multiple projects). 

To be clear, I think this is definitely worth doing, just adding some context that it may not be as urgent.
