### ISSUE TITLE
When creating Actions, the toolbar is not obvious to use and "new action is confusing"

### ISSUE THREAD

**Issue by Tannergoods** [PostHog/posthog#315]
**Is your feature request related to a problem? Please describe.**
A user sent a video of their experience setting up PostHog when trying to create actions they did not know about the toolbar

**Describe the solution you'd like**
Once a user wants to define an action the would normally select New Action, the toolbar is in fact much easier to use but the toolbar button does not indicate what it does. 

We should redesign the Toolbar button to explain what it does and in fact make it more prominent than the "new action" button
<img width="1166" alt="Posthog" src="https://user-images.githubusercontent.com/60791437/76369133-bdd85a80-62ef-11ea-9d0d-3f23d75df2a7.png">

**Describe alternatives you've considered**
Promote our training material more?

**Comment by timgl** [comment]
![image](https://user-images.githubusercontent.com/1727427/76382434-fc810b80-6315-11ea-8f34-7b422153b687.png)
@Tannergoods @jamesefhawkins How about this? Quite verbose but pretty obvious, and I think there's enough space in that top right corner for it.

**Comment by jamesefhawkins** [comment]
should we even allow the non-toolbar version?

**Comment by timgl** [comment]
Yeah I think so, otherwise hard to create pageview actions

**Comment by timgl** [comment]
After discussion:
- We're going to have 1 button that takes you to the PostHog action edit page.
- From there you can go out to the toolbar on your own site.

**Comment by timgl** [comment]
![image](https://user-images.githubusercontent.com/1727427/76384975-b334ba00-631d-11ea-8d70-8bb5359008ba.png)
![image](https://user-images.githubusercontent.com/1727427/76384982-b8920480-631d-11ea-9c97-036167e06e58.png)

Think this is a lot more obvious now, with clear links to docs
