### ISSUE TITLE
viewing session recordings causing a blank screen

### ISSUE THREAD

**Issue by rikinsk** [PostHog/posthog#3154]
## Bug description

*Please describe.*  
*If this affects the front-end, screenshots would be of great help.*  

attempting to view sessions causes a js runtime error and the page goes blank. Observed in `v1.20.0`

Observed the following logs in dev console:
```
index.modern.js:1 Uncaught Error: Attempted to send event papercups:plan with payload {"plan":null} before iframeRef was ready
    at t.n.send (index.modern.js:1)
    at t.n.handleChatLoaded (index.modern.js:1)
    at n.postMessageHandlers (index.modern.js:1)
    at n (index.modern.js:1)
VM64 react_devtools_backend.js:2430 TypeError: Cannot read property 'includes' of undefined
    at sessionsPlayLogic.ts:155
    at Array.filter (<anonymous>)
    at Object.selectors.session (sessionsPlayLogic.ts:155)
    at index.js:70
    at index.js:30
    at index.js:84
    at Object.session (index.js:30)
    at Object.keys.forEach.e.selectors.<computed> (index.esm.js:940)
    at useSelector.js:29
    at useSelector.js:106
overrideMethod @ VM64 react_devtools_backend.js:2430
react-dom.production.min.js:123 Uncaught TypeError: Cannot read property 'includes' of undefined
    at sessionsPlayLogic.ts:155
    at Array.filter (<anonymous>)
    at Object.selectors.session (sessionsPlayLogic.ts:155)
    at index.js:70
    at index.js:30
    at index.js:84
    at Object.session (index.js:30)
    at Object.keys.forEach.e.selectors.<computed> (index.esm.js:940)
    at useSelector.js:29
    at useSelector.js:106
```

## How to reproduce

Clicking on the view session recording button on the sessions page

Not quite sure if this just for me or effecting everyone.

## Environment

- [ ] PostHog Cloud
- [x] self-hosted PostHog, version/commit:  v1.20.0

**Comment by yakkomajuri** [comment]
Thanks for reporting! @macobo has been actively working on this

**Comment by macobo** [comment]
Hi @rikinsk - the upcoming release should fix this.

**Comment by abarde1** [comment]
Sir, Any updates on this?

**Comment by paolodamico** [comment]
Prioritizing for next sprint. Please see additional context on #5574

**Comment by paolodamico** [comment]
@rcmarron @alexkim205 I believe this has this been addressed? @rikinsk can you confirm too please?

**Comment by rcmarron** [comment]
Yeah, this should be taken care of.
