### ISSUE TITLE
Configure event properties and event/actions

### ISSUE THREAD

**Issue by EDsCODE** [PostHog/posthog#3161]
## Is your feature request related to a problem?
Whenever I try to filter by properties, I get overwhelmed by the number of properties that are stale or irrelevant. There are also repeated properties between events and users that make it confusing

## Describe the solution you'd like
- there should be a configuration page that allows me to hide certain properties and events/actions that are stale or unneeded. This doesn't need to be a hard delete as I might need them or experiment with them later on but they shouldn't be visible by default

## Describe alternatives you've considered
- hard delete. this might just be messy and impractical to go through the tables and delete related events

**Comment by Twixes** [comment]
IMO the nicest solution would be to leave all properties available, but only show the ones used in the last 30 days (according to data used in Events > Events Stats > 30 day volume), sorted by usage volume.

**Comment by Twixes** [comment]
This is kind of done with the recent addition of classifying events as "Stale" (to be rolled out soon).
