### ISSUE TITLE
Race condition in merging users after identify

### ISSUE THREAD

**Issue by macobo** [PostHog/posthog#3190]
## Bug description

Sentry error: https://sentry.io/organizations/posthog/issues/1844372433/?project=1899813&query=is%3Aunresolved+is%3Aunassigned&statsPeriod=14d

```update or delete on table "posthog_person" violates foreign key constraint "posthog_persondistin_person_id_5d655bba_fk_posthog_p" on table "posthog_persondistinctid"
DETAIL:  Key (id)=(44342088) is still referenced from table "posthog_persondistinctid".
```

Stack:
```
posthog/models/person.py in merge_people at line 65

posthog/tasks/process_event.py in _alias at line 65

posthog/tasks/process_event.py in handle_identify_or_alias at line 266

ee/clickhouse/process_event.py in process_event_ee at line 125
```

The problem seems to be extra `posthog_persondistinctid` being added/updated while main one gets deleted. This seems fixable by using transactions.

## Expected behavior

No data races

## Environment

- [x] PostHog Cloud
- [ ]

**Comment by mariusandra** [comment]
This error has moved into the plugin server now, so this can be closed :D

**Comment by macobo** [comment]
:partying_face: :rocket:
