### ISSUE TITLE
Org settings and members button doesn't work

### ISSUE THREAD

**Issue by IgnusG** [PostHog/posthog#3193]
## Bug description

The `org settings and members` button does not appear to be working after the latest update (the button was before in the sidebar I think).

![bug-posthog](https://user-images.githubusercontent.com/6438760/106883840-d1976700-66e0-11eb-876b-1b0a517f1556.gif)

## Expected behavior
The member settings are opened and can be edited.

## How to reproduce

1. Click on Profile Picture
2. Click on Org Settings and members

## Environment

- [X] PostHog Cloud
- [ ] self-hosted PostHog, version/commit: _please provide_

**Comment by macobo** [comment]
Thanks for the fast report! Merged the PR fixing this + improving coverage, expect to see it live soon!
