### ISSUE TITLE
Mobile Version Menu offset too small?

### ISSUE THREAD

**Issue by IgnusG** [PostHog/posthog#3196]
## Bug description

I think the offset on mobile is still set to the narrow icon only menu pre-update. Clicking on the menu does not appear to work either.

![image](https://user-images.githubusercontent.com/6438760/106898580-a7e83b00-66f4-11eb-9977-c4ad08794a64.jpeg)

## Expected behavior
The main view is shifted further to the right and clicks/taps work.

## How to reproduce

1. Open Page on mobile (narrow display?)

## Environment

- [X] PostHog Cloud
- [ ] self-hosted PostHog, version/commit: _please provide_

## Additional context

Version: iOS 14 (Edge Browser)

#### *Thank you* for your bug report – we love squashing them!

**Comment by IgnusG** [comment]
This bug is not critical, just wanted to let you know. 

Btw. You're product is really cool. Customer support is amazing and the future development of Posthog looks really promising.

**Comment by yakkomajuri** [comment]
Thank you for opening this up! There are definitely some optimizations that could be made to our responsiveness
