### ISSUE TITLE
Problems syncing persondistinctid from Postgres?

### ISSUE THREAD

**Issue by timgl** [PostHog/posthog#3215]
## Bug description

Looks like there was an issue when transferring this distinct id -> user pairing from Postgres to Clickhouse:
![image](https://user-images.githubusercontent.com/1727427/107029950-2950d380-67b0-11eb-9523-72efac9cae14.png)
(The correct user does have the later timestamp)

Note the fact that they have the same ID. In Postgres there's only one row and it links to the right user
![image](https://user-images.githubusercontent.com/1727427/107029993-38d01c80-67b0-11eb-9eaa-14ee524414ae.png)
In Postgres the incorrect user doesn't exist, in clickhouse it does.

`1776c2e7b0d245-08b5ffe48ea607-620c571d-2c600-1776c2e7b0e778`

## Expected behavior

Only sync over the correct row from Postgres. We could also do the "get the latest distinct id by timestamp" trick but that would increase complexity a lot.

**Comment by jamesefhawkins** [comment]
@timgl could #3218 be related?

**Comment by mariusandra** [comment]
I think it's not related as #3218 is for sure due to the plugin server ingestion, yet this team is not ingesting via the plugin server.

**Comment by paolodamico** [comment]
Is this still an issue @timgl ?

**Comment by timgl** [comment]
I'm not sure. I think we've spent a lot of time on these kinds of issues recently so I'm assuming this was fixed.
