### ISSUE TITLE
Users appearing persons list, but the link to their profile 404s

### ISSUE THREAD

**Issue by jamesefhawkins** [PostHog/posthog#3218]
## Bug description

* Go to app.posthog.com/persons for our internal deployment
* There are a significant number of users with a much shorter ID
* Clicking on these leads to a 404 page

<img width="345" alt="Screenshot 2021-02-05 at 13 17 25" src="https://user-images.githubusercontent.com/47497682/107038684-c9a8f700-67b4-11eb-93b7-198a78b0ddd9.png">

## Expected behavior

It depends on who these users are - perhaps they shouldn't appear in the filter, or perhaps something else is broken.

## Environment

- [x] PostHog Cloud (internal_

**Comment by mariusandra** [comment]
We're now doing ingestion via the plugin server for ourselves. Perhaps this is something related? CC @Twixes

**Comment by Twixes** [comment]
Hm, possibly, looks like these users are all fine, except that they have no distinct IDs on record. So may be something with `addDistinctId`.

**Comment by mariusandra** [comment]
So [this line](https://github.com/PostHog/plugin-server/blob/48247507cb2033c0c30deaaef958fca9fcd5f5eb/src/ingestion/process-event.ts#L280) was crashing and resulting in funny data for our team. Basically aliasing failed to move distinct ids from one user to another. I'm not yet 100% sure how exactly that results in events like those in the list, but at least the errors are gone now. Will dig in deeper on Monday.

**Comment by mariusandra** [comment]
I've been digging into this a bit and *think* these empty users are simply duplicates that can be discarded (and also not created in the first place).

Opening the [Kea website](https://kea.js.org) incognito a few dozen times I could produce a few of these empty users

![image](https://user-images.githubusercontent.com/53387/107200636-3d871180-69f8-11eb-8df9-2a1625f7e9c4.png)

However they were always created together with another user that has actual data:

![image](https://user-images.githubusercontent.com/53387/107200809-732bfa80-69f8-11eb-86ae-b9601962f9bc.png)

So it must be some edge case timing issue. I'll keep digging further.

**Comment by mariusandra** [comment]
Now that the PR to plugin-server is merged, I think this has been fixed. In the hour since I haven't seen any "person" without an ID. The last one in the list, which was added before the fix is this:

<img width="478" alt="Screenshot 2021-02-09 at 13 22 35" src="https://user-images.githubusercontent.com/53387/107363251-2a4c7280-6ada-11eb-9bff-38bb66a6f763.png">

It's worth keeping this open for a few more hours to make sure it's really fixed.

**Comment by mariusandra** [comment]
I think it's fixed. It's been many hours and I haven't seen such users anymore, whereas before there was one every 10-20 new persons. Now there are none in ~100 new persons.
