### ISSUE TITLE
Show more than 3 steps in User Paths

### ISSUE THREAD

**Issue by straussCS** [PostHog/posthog#3230]
## Is your feature request related to a problem?

We are tracking custom events for a lot of user interactions and we would like to see the most important click paths of the users of our application. 

## Describe the solution you'd like
It would be great if us if Posthoq showed User Paths with more than 3 steps, preferably a configurable number of steps would help us alot.

## Describe alternatives you've considered
- none

## Additional context
- none

**Comment by paolodamico** [comment]
Duplicated of #4933
