### ISSUE TITLE
Crossdomain Toolbar heatmap

### ISSUE THREAD

**Issue by Twixes** [PostHog/posthog#3236]
## Is your feature request related to a problem?

If the same product linked to the same PostHog project is deployed on multiple domains, it's still only possible to see heatmap data from the current domain.

## Describe the solution you'd like

Show heatmap using data from all domains.

## Additional context

Reported as a pain point by a user via chat.

**Comment by mariusandra** [comment]
closed with https://github.com/PostHog/posthog/pull/9306
