### ISSUE TITLE
Open Telemetry?

### ISSUE THREAD

**Issue by murphyke** [PostHog/posthog#3243]
This is just a random hit-and-run comment. I don't even use PostHog although I have an inordinate fondness for PostgreSQL.

In the course of researching logging (as well as metrics and tracing) options, I came across PostHog and ... a whole lot of other stuff. Our architect is interested in using [OpenTelemetry](https://opentelemetry.io/) to represent our observability data since there is increasing amounts of vendor support for it.

I don't know if OpenTelemetry could or should play a role in PostHog, but I thought I would mention it in case it is of interest.

**Comment by weyert** [comment]
@murphyke Yeah, I also have come across OpenTelemetry and its quite nice technology to allow observability of your software. I am not sure how it would integrate with PostHog. I could imagine a pull exporter could be written which that data from PostHog events or its dashboards or alternatively a plugin could be created which forwards cherry picked events on push approach. 

As you might know the metrics or logging specs of OTEL aren't 1.0 yet but the tracing spec is getting really close to 1.0. The goal is halfway this Month (think ~15 feb). 

Personally, I was thinking of using it to somehow get some stats collected through PostHog into Grafana.

**Comment by weyert** [comment]
I am using OpenFeature and its OpenTelemetry hook to achieve it

**Comment by samal-rasmussen** [comment]
Opentelemetry traces with spans is the last thing I am missing with Posthog.
