### ISSUE TITLE
Dashboard funnels loading the same data across all panels

### ISSUE THREAD

**Issue by yakkomajuri** [PostHog/posthog#3268]
## Bug description

*Please describe.*  
*If this affects the front-end, screenshots would be of great help.*  

Here are 3 different funnels in a dashboard:

<img width="1440" alt="Screenshot 2021-02-09 at 16 14 29" src="https://user-images.githubusercontent.com/38760734/107392884-09901700-6af2-11eb-9539-63f075e04851.png">

They all load the same data.

I've also experienced this with retention before.

Reported by a user.

## Expected behavior

Load the right data.

## How to reproduce

1. Add 2 or more different funnels to a dashboard
2.
3.

## Environment

- [ ] PostHog Cloud
- [ ] self-hosted PostHog, version/commit: _please provide_

**Comment by macobo** [comment]
@yakkomajuri can this be closed for now?

**Comment by yakkomajuri** [comment]
Yeah - this is fixed as per the revert
