### ISSUE TITLE
Hourly retention is broken

### ISSUE THREAD

**Issue by yakkomajuri** [PostHog/posthog#3293]
## Bug description

Priority 1 because it's wrong data.

Can't add the image here but a user had values like 300% and 400% on their hourly retention. It also seemed inconsistent in 
other hourly views as well.

## Expected behavior

Retention should have a maximum of 100%

## How to reproduce

1. Use hourly retention - ask Yakko for greater user context
2.
3.

## Environment

- [ ] PostHog Cloud
- [ ] self-hosted PostHog, version/commit: _please provide_

**Comment by EDsCODE** [comment]
#3358 closes
