### ISSUE TITLE
Negative cohort filtering

### ISSUE THREAD

**Issue by timgl** [PostHog/posthog#3298]
## Is your feature request related to a problem?

I've created a cohort of everyone in my team. I now want to use that cohort to exclude those users from a queyr.

## Describe the solution you'd like

I want to be able to set "is not" in this view.
![image](https://user-images.githubusercontent.com/1727427/107612362-60a70080-6c46-11eb-9574-b32a87e2b5f2.png)

**Comment by yakkomajuri** [comment]
Related issues:

https://github.com/PostHog/posthog/issues/2978
https://github.com/PostHog/posthog/issues/2273

**Comment by thedeveloperr** [comment]
@yakkomajuri can I send a PR for it ?

**Comment by yakkomajuri** [comment]
@thedeveloperr of course!

**Comment by timgl** [comment]
@thedeveloperr Did you make any progress on this?

**Comment by thedeveloperr** [comment]
I will send changes for frontend next weekend and hopefully clickhouse changes too. I can contribute during weekends only so it is taking longer.

**Comment by EDsCODE** [comment]
This is doable now in new cohort support https://github.com/PostHog/posthog/pull/10049 https://github.com/PostHog/posthog/pull/9595
