### ISSUE TITLE
User Breakdown 

### ISSUE THREAD

**Issue by Tannergoods** [PostHog/posthog#332]
***Thank*** you for your feature request - we love each and every one :)

**Is your feature request related to a problem? Please describe.**
Cohorts let me see who has used my app in the last 7 days or month but I can't see the breakdown of those users, are they just new or the same users coming back?

**Describe the solution you'd like**
I would like to understand which of my users are new, old or have come back after a period of time of not using the app

**Describe alternatives you've considered**
Checking each user in the cohort will let me know but is time consuming

**Additional context**
Requested by https://app.hubspot.com/contacts/6958578/contact/39151

**Comment by paolodamico** [comment]
This is addressed with the lifecycle chart, closing.
