### ISSUE TITLE
Division formulas not working well

### ISSUE THREAD

**Issue by yakkomajuri** [PostHog/posthog#3321]
## Bug description

`A/B` throws a 500, also with an error message that isn't very helpful:

<img width="1321" alt="Screenshot 2021-02-12 at 09 22 39" src="https://user-images.githubusercontent.com/38760734/107750617-31f75b80-6d14-11eb-85ad-289a0ca8a25c.png">

Managed to reproduce this with various sets of events.

EDIT: Also seems like any invalid formula throws a 500. As a side note we probably need a spec and some docs here.

## Expected behavior

Work.

## How to reproduce

1. Use formulas on app

## Environment

- [x] PostHog Cloud
- [ ] self-hosted PostHog, version/commit: _please provide_

## Additional context

Behind a feature flag

**Comment by yakkomajuri** [comment]
Relevant Sentry error:

https://sentry.io/organizations/posthog/issues/2213689273/?project=1899813&query=is%3Aunresolved

**Comment by timgl** [comment]
Fixed #3323
