### ISSUE TITLE
Developing Locally (using virtualenv) raise error while migrations.

### ISSUE THREAD

**Issue by Skchoudhary** [PostHog/posthog#3333]
## Bug description
When running *DEBUG=1 python3 manage.py migrate* command the Postgres connection raise an error
```
conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
django.db.utils.OperationalError: fe_sendauth: no password supplied
```
*Please describe.*  
The reason for this error is that we are not passing user and password details in the DATABASE_URL at *posthog/settings.py*.
*If this affects the front-end, screenshots would be of great help.*  
No
## Expected behavior
Migrate command should run without raising any error.

## How to reproduce

1. Take the clone of the repo and follow the steps as listed on https://posthog.com/docs/developing-locally
2. While running migrate command with DEBUG=1, will cause this error.

## Environment

- [ ] PostHog Cloud
- [X] self-hosted PostHog, version/commit: _please provide_

## Additional context
One of the way to solve the error is to pass the user and password details in the DATABASE_URL. Will be happy to create a PR for the fix.

**Comment by Twixes** [comment]
Hey! This is in fact intended behavior. If you'd like to provide a password of your own, you need to override environment variable `DATABASE_URL` . The default one in `DEBUG` mode is  just`"postgres://localhost:5432/posthog"`. The format is `"postgres://USERNAME:PASSWORD@HOSTNAME:PORT/DATABASE"`.
