### ISSUE TITLE
Dashboard collaboration / sharing metrics

### ISSUE THREAD

**Issue by paolodamico** [PostHog/posthog#3344]
## Context
Something that has come up with users is a better way to share dashboards with persons outside the product/engineering scope. This can be anything from: sharing metrics with business people or other internal stakeholders, sharing metrics with external stakeholders (e.g. investors, clients, suppliers), sharing point-in-time reports.

This elaborates on our current functionality of sharing dashboards externally.

Problems we're trying to solve:
- Sharing metrics with persons without the team's context. One key issue we have with the way we currently share is that the sharing party has no way of providing context (e.g. if I'm the CEO and I get a link to a bunch of graphs, what am I looking at, what's important to note, ....)
- Creating dashboards is a very siloed process. If I create a dashboard, it's quite hard for others on my team to have all the context on what's the dashboard for, what metrics are in there, how to use it. This leads to either me sharing context somewhere else (which now adds complexity bc it's not easily available, e.g. what happens when a new team member joins), or the dashboards only being helpful to me.
- Creating point-in-time snapshot of metrics. Example: for a meeting, investor report, stakeholder update. Currently the solution is taking a bunch of screenshots.

### The high-level stuff
- **Goal:** Increase collaboration within PostHog (strategic) & increase engagement of core users (core retention). As a secondary effect, this can also help increase internal referrals and spread within a team/org.
- **Assumptions:** Allowing core users to share metrics more easily will increase value for them, and therefore drive engagement within the platform (I might otherwise just find workarounds to do this), this would also make the platform more sticky (more collaboration = more value = less chances of churning).
- **Success metrics:** TBD. Based on the goal, we would clearly expect an increase in engagement and retention. As a proxy metric we would also expect a certain level of usage for this feature set.

## Initial Ideas
- Add some communication/discussion tool (like GitHub issues) that allows team members to discuss the dashboard and its metrics directly on the app. The discussion can then serve as historic context.
- Allowing PDF export and/or printing dashboards (specifically requested by a few users, [example](https://docs.google.com/document/d/1762fbEbFOVZUr24jQ3pFFj91ViY72TWrTgD-JxRJ5Tc/edit#heading=h.j5fxw7pclpda)).
- Allowing to annotate dashboards and dashboard items (i.e. add detailed descriptions for each dashboard and dashboard item). Ideally we would support some rich formatting, tagging team members, ... (like GitHub issues, or a Slack message).
- Point-in-time snapshots. Allow creating a snapshot of this moment, where you can add specific context and information, and then you can share the dashboard for that point in time.
    - We could expand on this and enable email and/or Slack sharing right from PH.
- Add version history with user notes. This can help document changes to a dashboard so that other team members have context on what went on.
    - Making changes to dashboards should be more deliberate to avoid causing confusion.
    - On the implementation side, version control can be generic functionality we add to multiple models (easy support through Django), as this could be useful for stuff like feature flags, actions, cohorts, ...
- Provide more details on the timeframe, filtering, ... for each dashboard item. Allow changing the global timeframe for all items.
- Request dashboards. Instead of email/slack/offline conversations that get lost, create requests right in the app so the entire historical context is preserved.
- Subscribing to email/Slack reports. Allow users to select certain dashboards to receive automatic point-in-time snapshots of the dashboard, based on different periodicity.
- Allow users to _subscribe_ to dashboards (like one subscribes to GH issues). This will help signal which users are interested/invested in which dashboards. Related to version control, you could also get notified about updates to dashboards to which you're subscribed.
- Tagging dashboards. Same context we had for session recordings. Tags can greatly help organize a company's dashboard (e.g. tags by team, environment, product, function, confidentiality, ...).
- Stale dashboards. Develop some heuristics to determine which dashboards are stale. Subscribed users can then get notified about stale dashboards and either update it, remove the stale label, or delete them. This can help remove noise from multiple dashboards which make it overwhelming to check metrics (particularly for new team members).
- Pin dashboards functionality on a per-user basis instead of project-basis.
- Tangential, but fix #2762.

## What others are doing
- Amplitude allows you to add a dashboard description and designate dashboards as "official" (which adds a verified badge next to the title). This is quite powerful for single-source-of-truth stuff.
- Mixpanel, Amplitude & Heap allow you to subscribe for automated weekly email reports (digest) of the dashboard (and even include CSV data).
- Amplitude allows you to comment on a dashboard and stat a discussion (+ tagging team members). You can connect Slack to receive notifications there.
- Amplitude allows you to create public links to dashboards with expiration date & password protection.
     <img width="798" alt="" src="https://user-images.githubusercontent.com/5864173/107984125-dd124a00-6f8c-11eb-988d-a2545f669ba5.png">
     <img width="253" alt="" src="https://user-images.githubusercontent.com/5864173/107984128-dedc0d80-6f8c-11eb-873b-97be9c282db1.png">
- AirTable has a nice way of showing [historic changes](https://support.airtable.com/hc/en-us/articles/203941415-Record-level-revision-history-overview) to records.
     <img width="400" alt="" src="https://user-images.githubusercontent.com/5864173/108246239-d3b4e900-7116-11eb-9ae5-4a337e3d9923.jpg">

## Current State
- This [graph](https://app.posthog.com/insights?insight=TRENDS&display=ActionsLineGraph&events=%5B%7B%22id%22%3A%22%24pageview%22%2C%22name%22%3A%22%24pageview%22%2C%22type%22%3A%22events%22%2C%22order%22%3A0%2C%22properties%22%3A%5B%7B%22key%22%3A%22%24current_url%22%2C%22value%22%3A%22%2Fshared_dashboard%22%2C%22operator%22%3A%22icontains%22%2C%22type%22%3A%22event%22%7D%5D%2C%22math%22%3A%22dau%22%7D%5D&interval=week&date_from=-90d&actions=%5B%7B%22id%22%3A3410%2C%22name%22%3A%22Used%20PostHog%20V2%22%2C%22type%22%3A%22actions%22%2C%22order%22%3A1%2C%22properties%22%3A%5B%7B%22key%22%3A%22id%22%2C%22value%22%3A71%2C%22type%22%3A%22cohort%22%7D%5D%2C%22math%22%3A%22dau%22%7D%5D&new_entity=%5B%5D&properties=%5B%5D) shows how many users view shared dashboards using a shared link. Around 4-8% of WAUs.
- This [proxy metric](https://app.posthog.com/insights?insight=TRENDS&display=ActionsLineGraph&events=%5B%7B%22id%22%3A%22%24pageview%22%2C%22name%22%3A%22%24pageview%22%2C%22type%22%3A%22events%22%2C%22order%22%3A0%2C%22properties%22%3A%5B%7B%22key%22%3A%22%24current_url%22%2C%22value%22%3A%22%2Fshared_dashboard%22%2C%22operator%22%3A%22icontains%22%2C%22type%22%3A%22event%22%7D%5D%2C%22math%22%3A%22dau%22%7D%5D&interval=week&date_from=-90d&actions=%5B%7B%22id%22%3A3410%2C%22name%22%3A%22Used%20PostHog%20V2%22%2C%22type%22%3A%22actions%22%2C%22order%22%3A1%2C%22properties%22%3A%5B%7B%22key%22%3A%22id%22%2C%22value%22%3A71%2C%22type%22%3A%22cohort%22%7D%5D%2C%22math%22%3A%22dau%22%7D%5D&new_entity=%5B%5D&properties=%5B%5D) shows around how many dashboards are shared every week.

**Comment by jamesefhawkins** [comment]
I suspect the metrics really understate usage - I imagine most people share metrics via a screengrab, but we've no way of tending. I do appreciate the fact we checked though!

We've had this precise issue when a new person started this week - our dashboards aren't self-explanatory.

Having #3228 would help, and a short description around the graph + an issue-like discussion would be a cool way to do it.

Teams probably also have to request certain dashboards to be made - I wonder how this works today via email/Slack and having that conversation in the tool would give some interesting context for those understanding them.

**Comment by paolodamico** [comment]
Re @jamesefhawkins, 100% on the metrics. Dashboard requests is quite an interesting feature, it can certainly help to have the conversation in a single place, will add it on the main issue description. One thing worth considering is that this feels like it might not be particularly relevant for our core persona. If you're in a small team, you don't really request dashboards to someone else?

**Comment by paolodamico** [comment]
EDIT: Updated main issue description with what we discussed today on the standup.

**Comment by macobo** [comment]
One additional feature from he@p which might fall under this broad umbrella: Suggested reports & dashboards, sortable by industry.

![2021-02-18_09-21](https://user-images.githubusercontent.com/148820/108319890-bc373800-71ca-11eb-808a-e9ac7aa071d8.png)
![2021-02-18_09-21_1](https://user-images.githubusercontent.com/148820/108319901-be999200-71ca-11eb-99d4-8db14e0e1eb2.png)

**Comment by macobo** [comment]
Related idea: Should all dashboards default to 'visible by all'? Perhaps there should be a concept of personal dashboards and shared dashboards.

For example, I've created custom dashboards to investigate specific issues.

A related thing He@p does is allow categorizing dashboards:

![2021-02-18_09-24](https://user-images.githubusercontent.com/148820/108320170-1a641b00-71cb-11eb-89db-6c2196cac59c.png)

This would make it easier to provide context and make it possible to find the right dashboards relevant for you. Sort of similar to tagging, but having a single category makes for easier UX at the cost of flexibility.

**Comment by macobo** [comment]
Related ticket: https://github.com/PostHog/posthog/issues/3408
