### ISSUE TITLE
Sidebar menu doesn't open nicely on larger dashboards

### ISSUE THREAD

**Issue by jamesefhawkins** [PostHog/posthog#3345]
## Bug description

Not a showstopper, as you can scroll up, but this happens if you hover over the sidebar on a longer page:

<img width="369" alt="Screenshot 2021-02-15 at 22 24 39" src="https://user-images.githubusercontent.com/47497682/107998295-b976f000-6fdc-11eb-9f47-55bdc1aaec75.png">

## Expected behavior

It'd be nicer if the top of the sidebar appeared at the top of the current window, not above it.

**Comment by Twixes** [comment]
Gone with nav redesign.
