### ISSUE TITLE
Weird issues with new demo onboarding

### ISSUE THREAD

**Issue by yakkomajuri** [PostHog/posthog#3348]
## Bug description

Since the new demo onboarding, I've experienced a lot of weird project-related issues on the playground that I've so far failed to reproduce in a screen recording, but they happen very often as I'm using the app.

Essentially, I've now deleted "HogFlix Demo App" 5 times and it keeps coming back. Also, while I was changing the config for one project after having deleted the demo project, the demo project was re-created and suddenly I was changing its config rather than my other project.

## Expected behavior

No cross-over between projects. 

## How to reproduce

1. ??
2. Use the playground and play around with project configs
3.

## Environment

- [ ] PostHog Cloud
- [ ] self-hosted PostHog, version/commit: _please provide_

**Comment by yakkomajuri** [comment]
Maybe @macobo can play around in the playground (sounds fun the way I put it!) so you can see this. A potential related issue here is that I can't get the toolbar to appear there anymore.

**Comment by macobo** [comment]
Can you elaborate on the reproduction steps a bit? Were you deleting projects, organizations, ..? What were you expecting to happen vs what did happen?

**Comment by yakkomajuri** [comment]
Yeah sorry about the vague description here.

But this is the key thing:

> Essentially, I've now deleted "HogFlix Demo App" 5 times and it keeps coming back. 

The demo project just comes back, and I'm constantly flipped back and forth between them.

**Comment by yakkomajuri** [comment]
Just now, I deleted it again, and on the next hard refresh, I appeared back in it, while I was doing some charts on the other project

**Comment by macobo** [comment]
Haven't had a chance to dig into this deeply, but locally this flow works as intended:

1. Sign up, get routed to a demo app
2. Go to project settings
3. Delete project
4. Get prompted to create new project, go through ingestion flow
5. New project is not demo, can use it successfully

**Comment by yakkomajuri** [comment]
@macobo Here's a screen recording I finally managed to get.

HogFlix Demo App was deleted before this recording. Notice as it comes back when I log back in.

The related team also still exists in the DB.

https://user-images.githubusercontent.com/38760734/108190831-5a16fe00-710a-11eb-9240-4f3d0d116026.mov

**Comment by macobo** [comment]
I think Michael deleted the project and it's not showing up anymore.

**Comment by yakkomajuri** [comment]
Fixed. Issue was that a demo project is created each time the user accesses `/demo` and that's the playground URL for the toolbar (i.e. was accessed often)
