### ISSUE TITLE
Trend graph filters not preserved as expected

### ISSUE THREAD

**Issue by corywatilo** [PostHog/posthog#3355]
## Bug description

Changing the date filter, then adjusting the interval filter doesn't preserve the date filter.

## Expected behavior

After setting the date filter, it should be preserved (when possible) when setting other filter parameters.

## How to reproduce

**[Demo](https://www.loom.com/share/4305e7e128994d5cb56197d0fb2cc6f2)**

1. Open a trend graph
2. Change date range to `All time`
3. Change interval to `Monthly`

## Environment

- [X] PostHog Cloud
- [ ] self-hosted PostHog, version/commit: _please provide_

**Comment by macobo** [comment]
This seems fixed
