### ISSUE TITLE
UI bugs on insights (tooltips & annotations)

### ISSUE THREAD

**Issue by paolodamico** [PostHog/posthog#3356]
## Bug description

A few bugs with the UI of certain elements on insights:

- Annotations overlap when there are several of them (initially reported on https://github.com/PostHog/posthog/issues/3175#issuecomment-779792674)
    <img width="1440" alt="" src="https://user-images.githubusercontent.com/38760734/108058345-d1398d00-704b-11eb-80f4-61a3f59af27f.png">
- Annotation elements are added on top of tooltips.
    <img width="223" alt="" src="https://user-images.githubusercontent.com/5864173/108081647-cd4f4000-7036-11eb-9c9b-6773f39f0df7.png">
- Tooltips get cut off at the bottom of the graphs, can't be scrolled, and don't show all the information if there are multiple data points.
    <img width="193" alt="" src="https://user-images.githubusercontent.com/5864173/108081654-cfb19a00-7036-11eb-9431-8ddb6d45f555.png">

## Environment

- [X] PostHog Cloud
- [X] self-hosted PostHog, version/commit: _please provide_

## Additional context
No additional context.

**Comment by Twixes** [comment]
Our UI has changed quite a bit since then, so I think we'll defer to more recent issues on related problems.
