### ISSUE TITLE
Ability to set global properties

### ISSUE THREAD

**Issue by funkyOne** [PostHog/posthog#336]
**Is your feature request related to a problem? Please describe.**
I want to be able to filter and break down actions/events by app version.

**Describe the solution you'd like**
It is currently possible to provide custom properties when logging custom events.
```
posthog.capture('[event-name]', {property1: 'value', property2: 'another value'});
```
But no way to make built-in events contain custom properties. It would be helpful If PostHog allowed to set up the global scope so that all events would include globally configured properties.

Similar to what we can do in Sentry:
```
Sentry.configureScope(function(scope) {
  scope.setTag("appVersion", "1.9.0");
});
```
Or even:
```
Sentry.setTag("appVersion", "1.9.0");
```

**Describe alternatives you've considered**
Nothing comes to mind.

**Comment by timgl** [comment]
I like this a lot!

Do you see this happening once per page-load or once per session? I'm leaning towards page-load as sessions might become confusing (as there are these random properties floating around).

**Comment by funkyOne** [comment]
I probably would expect it to work as if every `posthog.init` was a start with a clean sheet. So once per page-load.

I can imagine there might be a case for per-session way, but it feels that it would complicate things.

**Comment by timgl** [comment]
So turns out we already have this function in the JS library that I forgot about. We use it to store things like initial_referer and UTM tags. [I've documented it here](https://github.com/PostHog/posthog/wiki/JS-integration#super-properties). Annoyingly this does use cookies, but it should help with your use case?

**Comment by timgl** [comment]
i'm going to close this as I think we've solved this? Let me know if not!
