### ISSUE TITLE
Clicking from dashboard to insights doesn't load with the correct timeframe

### ISSUE THREAD

**Issue by jamesefhawkins** [PostHog/posthog#3362]
## Bug description

* Go to our [internal dashboard](https://app.posthog.com/dashboard/501) 
* Click a graph [like this one](https://app.posthog.com/insights?insight=TRENDS&events=%5B%7B%22id%22%3A%22%24pageview%22%2C%22math%22%3A%22dau%22%2C%22name%22%3A%22%24pageview%22%2C%22type%22%3A%22events%22%2C%22order%22%3A0%2C%22properties%22%3A%5B%5D%2C%22math_property%22%3Anull%7D%5D&display=ActionsLineGraph&interval=week&breakdown=%5B71%5D&date_from=2020-09-18T00%3A00%3A00%2B00%3A00&properties=%5B%7B%22key%22%3A%22%24current_url%22%2C%22type%22%3A%22event%22%2C%22value%22%3A%22https%3A%2F%2Fposthog.com%22%2C%22operator%22%3A%22not_icontains%22%7D%5D&breakdown_type=cohort#fromItem=1117&fromItemName=RETENTION%3A%20Real%20users%20WAU&fromDashboard=501) to go to the insights page
* It shows 'last 7 days', when it's showing over a much longer timeframe
<img width="999" alt="Screenshot 2021-02-17 at 13 36 45" src="https://user-images.githubusercontent.com/47497682/108211905-2e554180-7125-11eb-9102-adf0a408838f.png">

## Expected behavior
* The timeframe on the insights page to reflect what the timeframe is

## Environment

- [x] PostHog Cloud

**Comment by Twixes** [comment]
Is still an issue?
