### ISSUE TITLE
Best / Heavy Users

### ISSUE THREAD

**Issue by Tannergoods** [PostHog/posthog#337]
***Thank*** you for your feature request - we love each and every one :)

**Is your feature request related to a problem? Please describe.**
I have DAUs but I don't know who are my heaviest/best users. If I want to optimize for those best users I need to know who they are and what they do. I also won't be able to see this in the aggregate

**Describe the solution you'd like**
I should be able to chart the number of days users perform an event within a week/month. I should be able to do this by cohort and the total user base and as a cumulative % of users and non cumulatively % - I should be able to measure this by a specified time period 

**Describe alternatives you've considered**
This could be done in a fiddly way with cohorts, by deciding the event and then clicking into each user to look through their event history

**Additional context**
Requested by: https://app.hubspot.com/contacts/6958578/contact/39151

**Comment by timgl** [comment]
In terms of implementation, it'll look something like
- backend
  - Get all events for each action
  - For each work out how many unique days each Person has done that action
  - Have labels be '1 day', '2 days', '3 days' (frontend should automatically carry that over
 - frontend
   - Add another section to the Action/Property/Breakdown thing that's something like "Shown as"

**Comment by Tannergoods** [comment]
Yep this works
