### ISSUE TITLE
Posthog web crashing after update

### ISSUE THREAD

**Issue by kappa90** [PostHog/posthog#3373]
## Bug description

I just tried to upgrade posthog to 1.21.0 with the following commands:

`docker pull web`
`docker-compose up -d`

The app is now always crashing on start and in the logs I get a:

`duplicate key value violates unique constraint "django_migrations_pkey"`

## Expected behavior

The app should run.

## How to reproduce

1. Update from 1.20 to 1.21 as described above.

## Environment

- [x] self-hosted PostHog, version/commit: 1.21

**Comment by kappa90** [comment]
I made it work with this command:

`ALTER SEQUENCE django_migrations_id_seq RESTART WITH ${NROWS + 1};`

where ${NROWS} is the number of rows in the django_migrations table.

**Comment by timgl** [comment]
@kappa90 Is it possible migrations were run twice simultaneously?

**Comment by kappa90** [comment]
I only ran the two commands I wrote above, one after another :/
