### ISSUE TITLE
Slightly confusing UX for session filters

### ISSUE THREAD

**Issue by jamesefhawkins** [PostHog/posthog#3384]
## Bug description
<img width="1470" alt="Screenshot 2021-02-18 at 15 38 23" src="https://user-images.githubusercontent.com/47497682/108381121-6a5cd500-71ff-11eb-84c2-de4aaa74dce7.png">

My very first reaction on using this was I found the 'filter sessions by users, actions, events, ...' bar confusing, because it isn't a dropdown and looks like a text search (obviously it's a text search _within_ the dropdown)

## Expected behavior

* An icon on the right of the filter bar to indicate it's a dropdown
* The filter bar to be narrower so it feels more like a dropdown than a text search

ie so it's consistent with our insights filtering, which is what I was looking for as a first reaction:
<img width="157" alt="Screenshot 2021-02-18 at 15 40 38" src="https://user-images.githubusercontent.com/47497682/108381372-a7c16280-71ff-11eb-80ed-2594fe38098a.png">

**Comment by Twixes** [comment]
+1 I also was slightly confused by this before.
