### ISSUE TITLE
Allow filtering on Distinct IDs on user properties

### ISSUE THREAD

**Issue by timgl** [PostHog/posthog#3390]
## Is your feature request related to a problem?

I want to exclude certain users from a cohort, but I don't set any properties for users

## Describe the solution you'd like

I want to be able to filter on distinct ids like normal properties

## Describe alternatives you've considered

Send distinct ids as a property as well

**Comment by macobo** [comment]
This seems to already exist? 
![2021-02-19_17-22](https://user-images.githubusercontent.com/148820/108523858-13c2ca00-72d7-11eb-9c5f-fbe2cda040ad.png)

**Comment by timgl** [comment]
It's for creating cohorts so it needs to be a user property rather than an event property!

**Comment by EDsCODE** [comment]
Should I format the UI/logic so that the different ways of creating a cohort can work together? So a single cohort could be made up of people determine from dynamic property filtering, uploaded from CSVs, and manually selected/added to the cohort or should we keep these separate like it is now?

**Comment by timgl** [comment]
This is done
