### ISSUE TITLE
Multi select property values

### ISSUE THREAD

**Issue by timgl** [PostHog/posthog#3391]
## Is your feature request related to a problem?

I want to be able to quickly filter multiple values without having to create separate match groups (or even different graph series if using trends).

## Describe the solution you'd like

I want to be able to select multiple properties to filter on in an 'or' fashion, something like this:
![image](https://user-images.githubusercontent.com/1727427/108405533-78235200-7221-11eb-9378-9f94e0adcc9d.png)

## Describe alternatives you've considered

Create different match groups or trends which takes a long time.

## Additional context

cc @macobo @EDsCODE for parity project

**Comment by samwinslow** [comment]
As shown here, this is technically possible (the below query will include events where Browser Version == 89 or 90). But the UX is iffy, i.e. it's not very discoverable.

<img width="877" alt="Screen Shot 2021-04-28 at 12 37 17 PM" src="https://user-images.githubusercontent.com/4645779/116440413-79bf5680-a81e-11eb-8d00-cb4ec64ae272.png">

Especially, it's not clear from the tag input empty state that the input supports multiselect:

<img width="435" alt="Screen Shot 2021-04-28 at 12 40 52 PM" src="https://user-images.githubusercontent.com/4645779/116440941-f9e5bc00-a81e-11eb-9aa1-c31fa2871f3e.png">

I'll run with adding checkboxes and "Select All" and perhaps we can test with a feature flag if necessary.

**Comment by macobo** [comment]
Yeah, this ticket is solved, though agreed that the UX could be improved (ideas welcome)! :)
