### ISSUE TITLE
Allow breaking down in funnels

### ISSUE THREAD

**Issue by macobo** [PostHog/posthog#3409]
## Is your feature request related to a problem?

I want to use breakdowns in funnels. 

Some usecases:
- I had a marketing campaign. Was that effective?
- We changed onboarding for a subset of our users. Did that affect our bottom line?
- Comparing different platforms

## Describe the solution you'd like

Enable breakdown in funnels.

If breakdown, users table gets replaced by a table similar to this:

![image](https://user-images.githubusercontent.com/148820/108527307-cea09700-72da-11eb-81e5-f84199900014.png)

Ideally in a separate table

## Describe alternatives you've considered

Separate query per cohort

## Additional context

cc @EDsCODE

**Comment by akbansa** [comment]
👍   for this!

**Comment by EDsCODE** [comment]
Query here: https://metabase.posthog.net/question/83

**Comment by EDsCODE** [comment]
When we breakdown in a funnel, how are we determining the property values that will be shown? For example, if we have a three step funnel $pageview -> user signed up -> purchase broken down by property X, the most popular property values for each event could be different so which property would we break down by?
