### ISSUE TITLE
Hide [Add filters] behind ... dropdown

### ISSUE THREAD

**Issue by macobo** [PostHog/posthog#3411]
## Is your feature request related to a problem?

If you are charting multiple actions/events, a lot of space is taken up by our add filters buttons

![2021-02-19_17-54](https://user-images.githubusercontent.com/148820/108527952-9188d480-72db-11eb-9623-fcaf52e3a387.png)

This makes the UI seem cluttered. (Ignore missing unicode in screenshot, missing a font)

## Describe the solution you'd like

Hide the option to add additional filters behind a ... button

From mixp@nel:

![2021-02-19_17-55](https://user-images.githubusercontent.com/148820/108528087-b5e4b100-72db-11eb-82ff-b77a0e9dbfe4.png)

## Describe alternatives you've considered

Not being annoyed at the UI

## Additional context

cc @EDsCODE

**Comment by Keisay** [comment]
Hello there! What do you think of this [Demo](https://drive.google.com/file/d/1dt8Xv_PvbyTA0SWa7n7bqoZEn44KWMtU/view?usp=sharing) ?

**Comment by timgl** [comment]
Hey Keisay, I think that looks pretty good! Feel free to open a PR

I'm not sure about putting those two icons in buttons. I think they'd be nicer without the border around it.

**Comment by paolodamico** [comment]
While having the filtering items in the dropdown certainly makes for a cleaner UI, I think the UX is not straightforward. I think we might run into some discoverability issue here.

**Comment by Twixes** [comment]
Hidden behind a "funnel" icon.
