### ISSUE TITLE
Cohorts not being recalculated automatically

### ISSUE THREAD

**Issue by paolodamico** [PostHog/posthog#3413]
## Bug description

Cohorts seem to have stopped recalculating automatically on Cloud. See below our cohorts.
    <img width="127" alt="" src="https://user-images.githubusercontent.com/5864173/108535567-160a3180-72a1-11eb-9ee5-acd19635996d.png">

Discovered while working https://github.com/PostHog/retention/issues/12, turns out our Real Users cohort was like 2 months outdated, which means some of our metrics might've been off.

## Expected behavior

Cohorts should be recalculated automatically every ~15 mins I believe, or at least daily?

## How to reproduce

1. Open PostHog and check the outdated cohorts.

## Environment

- [X] PostHog Cloud
- [ ] self-hosted PostHog, version/commit: _please provide_

**Comment by EDsCODE** [comment]
Took a look at the DB and we have a limit where cohorts that error'd more than twice during recalculation will be omitted for the future. It looks like a majority of our cohorts have accumulated errors (from sentry it looks like connection failures/timouts). I've made some adjustments in #3446 and will track any new errors in sentry to see why cohort calculations have been failling

**Comment by paolodamico** [comment]
Thanks for diving into this so quickly @EDsCODE!! For context if it's helpful, after manually pushing a dummy update to the cohort, recalculation worked fine.

**Comment by EDsCODE** [comment]
Np! I think it's fixed for now. I made the bounds more tolerant. Will keep an eye out to see if something else clogs up the tasks
