### ISSUE TITLE
Paths are super slow (/never loads?) even with literally one event

### ISSUE THREAD

**Issue by timgl** [PostHog/posthog#342]
**Describe the bug**
Even on a new environment with one event paths never load.

**To Reproduce**
1. Create new environment
2. go to /demo
3. go to /paths
4. See it doesn't load

**Expected behavior**
It should load

**Comment by Tyler-Churchill** [comment]
Also seeing this on a docker-compose setup with lots of available cpu/ram and no events created. Looks like gunicorn is timing out which I am not sure if its from latency in contacting an external auth service or something more sinister. After the initial timeout it seems to work more responsively

**Comment by timgl** [comment]
Ha, [nothing sinister going on ;-).](https://github.com/PostHog/posthog/blob/master/posthog/api/paths.py) I think it's just a bad SQL query that needs some special casing if there are no follow up events.

**Comment by Tyler-Churchill** [comment]
To clarify sinister I mean a tricky misconfig with gunicorn or a required package or something on my host machine :) Appreciate the responsiveness!

**Comment by timgl** [comment]
@Tyler-Churchill This should be fixed now :)
