### ISSUE TITLE
Release 1.23.0 – 15 March 2021

### ISSUE THREAD

**Issue by paolodamico** [PostHog/posthog#3423]
Priorities
- Plugins: still some stuff to do, obvious prio
- Retention analysis: priority b/c we need to know what our activation metric is, then maybe build into posthog
- VPC: within a week sales we'll be bottlenecked by this. Few more coming down the pipeline. (Billing etc not a prio)
- Dashboard collaboration / sharing metrics: #3344. Prio b/c it'll increase retention

Plugins: Michael/Karl second week
Prio: Get plugins out of beta
- Access control for plugins on the cloud (in progress) - #3328
- Lazy VMs / Improve Reloads / Rolling Restarts - PostHog/plugin-server#59
- GeoIP plugin on cloud - PostHog/plugin-server#115

Retention analysis: Eric/Paolo
- Find users that really retain: PostHog/retention#12

VPC: James G/Tim
- Wrap up backing up for Cloud 
- Terraform scripts done
- Maybe put in license app

Dashboard collab/sharing: Tim/Eric (and Paolo support)
- Spec out highest impact 1-2 features & build it

Support hero: Marius

Notes from the meeting
- In retro we'll talk about 'icing on cake' we got done, also check if we got the prioritization right

**Comment by paolodamico** [comment]
## New Features

The past release I worked with the help of the rest of you on exploring different ideas for what we can build next. I'm still finishing up research on each of the options, but I want to put forward an initial prioritization review based on our new [prioritization strategy](https://posthog.com/handbook/strategy/prioritization), without considering revenue numbers just yet. As I mentioned on the stand-up, I'd love to **pair up with someone** on each of the features we actually prioritize for building, so we can work out together everything from initial wireframes, user research, feature specs, design and actual build.

### Initial Prioritization
1. Churn prediction & prevention: #3032
    - Target role: Non-technical roles + Analysts
    - Target company size: Startup (3) & Scaleup (3.5)
    - Revenue consideration: Likely no direct additional revenue, but would potentially increase retention & engagement, indirectly influencing revenue.
    - Preliminary result: From a strict customer perspective, it's probably a don't build right now. However, adding the additional consideration that this could probably drive our retention up in a substantial way, I would at least like to explore it further.
2. Retention leaderboard**: #2828
    - Target role: Non-technical PMs (more involved technical roles could definitely benefit from this, but based on customer calls, this doesn't seem like a top priority for most technical roles)
    - Target company size: Startup (3) & Scaleup (3.5)
    - Revenue consideration: Likely no direct additional revenue, but would potentially increase retention & engagement, indirectly influencing revenue.
    - Preliminary result: Probably don't build right now. There's one consideration around dogfooding which might change this.
3. Trigger-based workflow: #3357
    - Target role: Technical engineers/PMs.
    - Target company size: Enthusiast (1) & Startup (3) (based too on the assumption that larger companies have already other workflows in place, or more complex requirements that we wouldn't initially address).
    - Revenue consideration: Likely no direct additional revenue, but would potentially increase retention & engagement, indirectly influencing revenue.
    - Preliminary result: Don't build right now (also consider more details on the issue)
4. Data taxonomy**: #3228
    - Target role: Technical engineers/PMs + Analysts.
    - Target company size: Scaleup (3.5) & Enterprise (3) (some startups have expressed interest but seems like the exception).
    - Revenue consideration: Could bring immediate new revenue stream (can be a premium feature, it's also commonly billed separately). Worth noting that while this would mean higher long-term value for customers, by design this feature would probably reduce event usage (eliminating redundancies, malformed events, up to turning off autocapture).
    - Preliminary result: Build
5. Dashboard collaboration / sharing metrics: #3344
    - Target role: Non-technical roles, enterprise procurement.
    - Target company size: Startup (3), Scaleup (3.5) & Enterprise (3).
    - Revenue consideration: Likely no direct additional revenue, but would potentially increase retention & engagement, indirectly influencing revenue.
    - Preliminary result: Build
6. Full A/B testing suite**: #3431
    - Target role: Technical roles.
    - Target company size: Startup (3), Scaleup (3.5) (enterprise likely has their own in-house system or highly complex requirements)
    - Revenue consideration: Could bring immediate new revenue stream (usage would directly generate more usage and hence, revenue), it is also an anchor feature that could stand-alone bring new customers.
    - Preliminary result: Build

> ** = initial ideas are on the issue, but full research is still pending.


In addition to the above, I would like to put forward some stuff that has come up in previous releases in case someone wants to pick it up (definitely keen on collaborating on this too),
* The toolbar is a feature that has a fair amount of usage, almost as much as session recording (around 10% of WAUs), but it has one key advantage too, it creates a very natural loop to get users back to PostHog from outside the product. Think it's now worth working on improving the UI, UX and functionality, #2370, #2349, #1530, [design](https://www.figma.com/file/gQBj9YnNgD8YW4nBwCVLZf/PostHog-App?node-id=348%3A1).
* Email stuff to test re-engagement strategies, #1938 #1983.
* #2247 aggregated analytics by team/company keeps coming up from user's requests and we could definitely use it ourselves (particularly working on https://github.com/PostHog/retention/issues/12).


## Myself
- This release I'd like to pair up with @EDsCODE & @kpthatsme to work on https://github.com/PostHog/retention/issues/12 and really nail down the activation & habit moments, retention breakdowns and engagement understanding. This I believe could be our biggest blocker today for increasing retention, so I would make it my **🔍 Focus** for the sprint. 
- I'd also like to pair up with someone to work on 1 or 2 of the suggested features above, depending on if someone wants to pick up any of the features in this release sprint. 
- I'm happy to work with @kpthatsme on building VPC billing (https://github.com/PostHog/ops/issues/178), but based on our priorities I'd push this to release 24.

**Comment by timgl** [comment]
**Potential list to work on:**
- https://github.com/PostHog/posthog/issues/2866
- #3375

**Comment by macobo** [comment]
Note for planning session: I'll be off next week, Eric and James off the week afterwards + Paolo away for 2 days. 

Perhaps it makes sense to make this sprint slightly longer given that?

**Comment by mariusandra** [comment]
Plugins should get a good development sprint now that the base ingestion is done:

Things to definitely work on:
- Access control for plugins on the cloud (in progress) - https://github.com/PostHog/posthog/issues/3328
- Secret keys in plugins (almost done) - https://github.com/PostHog/posthog/issues/3082
- Deprecate Python ingestion - https://github.com/PostHog/posthog/pull/3485
- Lazy VMs / Improve Reloads / Rolling Restarts - https://github.com/PostHog/plugin-server/issues/59
- Plugin logs - https://github.com/PostHog/plugin-server/issues/72 & https://github.com/PostHog/posthog/pull/3482
- GeoIP plugin on cloud - https://github.com/PostHog/plugin-server/issues/115
- Downsampling plugin - https://github.com/PostHog/posthog/issues/3365
- Misc cleanup - https://github.com/PostHog/plugin-server/issues/156 https://github.com/PostHog/plugin-server/issues/210 https://github.com/PostHog/plugin-server/issues/12 https://github.com/PostHog/plugin-server/issues/219
- Improve BigQuery plugin for EE customer

Is this a priority?
- Do action matching in the plugin server - https://github.com/PostHog/plugin-server/issues/157
- Outgoing webhooks - https://github.com/PostHog/plugin-server/issues/145
- Improve the plugins interface in app

Bigger tasks that we will not get to:
- UI/Frontend plugins - https://github.com/PostHog/posthog/issues/2965
- Incoming webhooks in plugins - https://github.com/PostHog/plugin-server/issues/8
- posthog-js plugins - https://github.com/PostHog/posthog/issues/3504
- Better plugin source editing & testing experience - https://github.com/PostHog/posthog/issues/2768
- TypeScript support - https://github.com/PostHog/plugin-server/issues/221

**Comment by EDsCODE** [comment]
1 week for me

- primarily keen on pairing with Paolo to do more thorough retention analysis. also can work on product planning/prioritization

**Comment by macobo** [comment]
I'm... not sure since I will be off next week.

Some ideas that might make sense to do one of the following:
- Pair up with Paolo, picking up where Eric leaves off
- Pair up with Paolo, start with dashboard collaboration tooling (would roll over for sure) https://github.com/PostHog/posthog/issues/3344
- Take the time to _actually_ work on email/demo data this time #1938 #1983 #3175
- Join plugins team and help with:
  - https://github.com/PostHog/posthog/issues/3504 different kind of plugin to do surveys and/or product announcements seems interesting and fun.
  - Outgoing webhooks and action matching? https://github.com/PostHog/plugin-server/issues/145 https://github.com/PostHog/plugin-server/issues/157

**Comment by Twixes** [comment]
Personal priorities:

- finish access control for plugins on the cloud - issue #3328 / PR #3486
- finish plugin logs implementation (or change approach, feedback needed here) - issue PostHog/plugin-server#72 / PR #3482
- rework GeoIP - issue PostHog/plugin-server#115
- merge enhanced organization settings - PR #3324
- write a light engineering blog post on automating releases with GH Actions

**Comment by paolodamico** [comment]
This has been released, closing.
