### ISSUE TITLE
Plugin-server starts without correctly generated Redis environment variables (since 1.21.0)

### ISSUE THREAD

**Issue by benjackwhite** [PostHog/posthog#3425]
## Bug description

Testing an upgrade from 1.20 to 1.21 with the Plugin Server via Helm / Kubernetes
The plugin-server becomes healthy from Kubernetes point of view but when you look at the UI or the logs it is clear that it is not. It tries to connect to REDIS like so `Error: connect ECONNREFUSED 127.0.0.1:6379` which indicates the REDIS_URL env has not been correctly generated.

Jumping into the diff it seems there used to be a line in the plugin-server executable that generated a `CONFIG` env var including the `REDIS_URL` (made from `POSTHOG_REDIS_HOST` etc.). Since 1.21.0 this seems to be removed.
https://github.com/PostHog/posthog/blob/1.20.0/bin/plugin-server#L7

I assume this may also apply to other env variables but the logged issue is specifically with Redis

## How to reproduce

1. Deploy the helm chart with Plugin Server enabled
2. Observe logs of the plugin-server

## Environment

- [ ] self-hosted PostHog 1.21.0
- [ ] Kubernetes 1.19
- [ ] Helm 3
- [ ] Chart version - 1.4.7

**Comment by mariusandra** [comment]
The chart version `1.4.8` should fix this.
