### ISSUE TITLE
feature request: k8s documentation and improvements 

### ISSUE THREAD

**Issue by Tyler-Churchill** [PostHog/posthog#343]
**Is your feature request related to a problem? Please describe.**
It would be nice to add Kubernetes focused deployment documentation and support

**Describe the solution you'd like**
For the documentation:

- What liveness or ready probes exist? (if any, create if not existing)
- An example deployment and service yaml setup
   - Include examples of configuring gunicorn as well?
   - Include examples of use with HorizontalPodAutoscalers?
- Environment variables of interest. For people who have never worked with Django, the default environment configuration offerings may not be easily known.

**Additional context**
I am currently playing with PostHog in a k8s setup and saw information lacking.  I would be interested in hearing from contributors if they see PostHog being offered as a helm chart in the future, or leaving it open and configurable in its current state with some supporting documentation for use. I am willing to open a PR with findings and documentation for deploying PostHog with k8s

**Comment by timgl** [comment]
@Tyler-Churchill Hey, thanks very much for raising this.

We haven't had much experience deploying with k8s so would really appreciate any information/heml charts etc you could contribute to the community! Let me know what help you need from me to do that :) Happy to do any of the boring formatting of docs if that's helpful.

**Comment by timgl** [comment]
@Tyler-Churchill I added [this example configmap](https://github.com/PostHog/posthog/wiki/Deployment) someone else sent me to the documentation as a start.

**Comment by timgl** [comment]
[We've had helm charts for a while now](https://docs.posthog.com/#/deployment) So closing this :)
