### ISSUE TITLE
Feature Concept: Full A/B testing suite

### ISSUE THREAD

**Issue by paolodamico** [PostHog/posthog#3431]
DISCLAIMER: This is just initial & WIP product discovery.

Shout-out to @weyert and @IgnusG community members for all their help with product discovery of this feature!

## Context

- Creating products is an interative process. No one will have the right answer, and the best outcome will only come from experimentation. This feature is targeted to our mission of increasing the number successful products in the world.
- We also know there's some strong interest for features around this from current users (see referenced issues, threads on Users Slack and even customer calls [[example](https://docs.google.com/document/d/1762fbEbFOVZUr24jQ3pFFj91ViY72TWrTgD-JxRJ5Tc/edit#heading=h.erd5vmuf65al)]).
    - We also now there are some users that use our current feature flags (FF) for application logic and mission-critical functionality (2).
- As we work out how to create full A/B testing functionality, it's important to keep in mind that there are indeed a bunch of users who use FFs for non AB-testing purposes (e.g. phased roll-outs, toggling functionality for paid members, user testing, ...)

### Prioritization notes
- Target role: Technical roles.
- Target company size: Startup (3), Scaleup (3.5) (enterprise likely has their own in-house system or highly complex requirements)
- Revenue consideration: Could bring immediate new revenue stream (usage would directly generate more usage and hence, revenue), it is also an anchor feature that could bring new customers in itself.

## Ideas
- The key feature that needs to be introduced to turn this into a full A/B testing suite is metrics tracking and results analysis. This is however a quite broad and complex topic. Some particularly relevant things mentioned here, but we'll probably need to iterate and optimize this constantly.
    - We need to be able to define metrics (maybe primary and secondaries) we want to track and optimize for. We might be doing an experiment to increase retention, conversion, feature usage, ... We can then show deltas in metrics and even go as far as "declaring a winner". Particularly relevant is #2958 as we can't measure impact on retention today.
    - We need to track sample sizes and make sure samples are representative. This was particularly mentioned by a user who is very heavy on A/B testing. One of the things they love about the product they use is it clearly shows when it's too early to make a decision or even make sense of the experiment. It's quite natural that just after launching an experiment we want to refresh the page every 10s and we might be over-eager to take actions based on those very early not-yet-significant results if the product doesn't help us realize this.
    - Related to the above, most products introduce some concept of confidence (confidence intervals, p-values, ...) to ensure statistical significance.
- Allow complex types for feature flags (e.g. setting numeric values, strings, and even JSON), and allow multiple segmentation groups, i.e. a boolean led you to 1 experiment and 1 control group, with the support of complex values, we can also add support for multiple experiment groups.
    - The above would probably need to be paired up with allowing complex filtering/selection for each group (props, cohorts, even users who have done X action Y times in the last Z days, ...). 
- Keep version history (#3073) for feature flags (As we're already implementing #3334, this could be fairly easy to introduce here too).
- There's a bunch of tools (e.g. Optimizely, FB Analytics, ...) that let you change stuff on the fly, either on the realm of changing your product (copy, colors, images, ...) or changing messaging (e.g. on push notifications, emails, newsletters, ...) without requiring code changes (mostly targeted at non-technical people).
- Some other products also introduced ML models to predict results from an initial set of data to speed up the experimentation process.

### Practical improvements from feature flags
These are some practical improvements that have already been suggested elsewhere. Documenting them here so that whomever picks this up can consider if they make sense / should be prioritized based on the new feature.
- Allow toggling feature flags with toolbar (#1996)
- Show active feature flags for each person (#2827)
- Expiring feature flags (#1903)
- Improve the way we assign users to experimentation groups. As mentioned in our latest experiment results https://github.com/PostHog/retention/issues/15, experiment & control groups almost always end up being disparate in sample size numbers. Related to this, we might still need some data normalization (#1610) to make sure results are comparable (particularly if we allow setting different distribution percentages for each group).

## What others are doing
- Start with this https://github.com/PostHog/posthog/issues/3213#issuecomment-775988748. Contains an overview of Optimizely, ConfigCat & Flaggr by @IgnusG.
- Among other things, Optimizely also offers mutually exclusive experiments which would assert the validity of an experiment where all other variables are controlled. ML-based traffic allocation (assign users to different experiment groups based on how well they're performing on the fly). Documenting, commenting, official reporting, and generally collborating on experiments (like we're considering for dashboards #3334).
    <img width="507" alt="" src="https://user-images.githubusercontent.com/5864173/109194515-1dc54c80-775f-11eb-9425-baa3e1f0d2fe.png">
- VWO is a complete A/B testing suite that also offers other analytics features (e.g. session recording & heatmaps). Some interesting functionality they offer is segmenting based on different user paths/actions, load FFs asynchronously in a way that doesn't affect user experience, segment reports on running experiments (e.g. what does the experiment look like for new vs. returning visitors, or based on traffic source, or membership level, ...), show you a graphic distribution of your results (and a box plot too), repository of experiments & learnings (collaboration).
    <img width="600" alt="" src="https://user-images.githubusercontent.com/5864173/109194623-39c8ee00-775f-11eb-86fb-aaea68636c45.png">
    <img width="524" alt="" src="https://user-images.githubusercontent.com/5864173/109194631-3b92b180-775f-11eb-989c-ff4c1b6a6caa.png">
- Conductrics (which was described by one of our users as the standard for multivariate testing), offers more complex ML models to go beyond the scope of the experiment in question. One particularly cool thing they introduce is decision trees which could help go as far as rethinking key metrics.
    <img alt="" width="200" src="https://user-images.githubusercontent.com/5864173/109170377-560c6100-7746-11eb-80d8-2766e9781de0.png" />
- Firebase, GA & Google Optimize offer basic A/B testing that among other things already mentioned, introduce features to make testing easier, particularly for non-technical users: e.g. split URL testing (moving users to different URLs), visual diagnostics alerts, scheduling experiments.
- Braze offers [multivariate A/B testing](https://www.braze.com/docs/user_guide/intelligence/multivariate_testing) on top of their core feature, messaging. What is particularly interest here is the case of introducing A/B testing on top of another core, which is what we're trying to do.

**Comment by weyert** [comment]
Love to discuss this feature in more detail with anyone at PostHog :)

**Comment by paolodamico** [comment]
Very helpful @weyert, thanks! Will ping you on Slack to discuss.

**Comment by IgnusG** [comment]
Featurehub is another open-source project (self-hosted although hosted version is coming apparently) which offers feature flags (boolean, string, number and JSON) that can be configured with splits and some simple targeting. They appear to aim at not being an analytics engine (I assume) as they integrate with GA (and [others through adapters](https://github.com/featurehub-io/featurehub/issues/318)) for additional tracking.

https://github.com/featurehub-io/featurehub

**Comment by IgnusG** [comment]
Another contender in the feature flag/AB testing department is flipt 

https://flipt.io/
https://github.com/markphelps/flipt

Open Source (self-hosted) with support for variants and target rules.

**Comment by IgnusG** [comment]
Another resource for pure feature flags with variant configurations is [Unlaunch](https://www.unlaunch.io/).

It offers feature flags with different variations:

<details>
<summary>Preview</summary>
<img src="https://user-images.githubusercontent.com/6438760/117583762-51323900-b109-11eb-8465-ebb78c56af18.png"/>
</details>

and different configurations (string only) for each of them:

<details>
<summary>Preview</summary>
<img src="https://user-images.githubusercontent.com/6438760/117583783-64dd9f80-b109-11eb-8d12-c62a68bb124c.png" />
</details>

**Comment by IgnusG** [comment]
Another new service for feature flag management and A/B testing is [Flagsmith](https://flagsmith.com/).

It offers feature flags with segmentation based on users and groups, light-weight analytics and feature configurations which can take txt, json, yml,  toml and xml formats to return based on environment. I don't think it was possible to change these values per segment/user though.

<details>
<summary>Preview</summary>
<img src="https://user-images.githubusercontent.com/6438760/117712222-54462b80-b1d4-11eb-8404-63e33bb0785d.png" alt="Feature List and Creation Page" />
<hr/>
<img src="https://user-images.githubusercontent.com/6438760/117712299-70e26380-b1d4-11eb-9635-6aa6ddd0e41f.png" alt="Value/Config Specification for Flag" />
<hr/>
<img src="https://user-images.githubusercontent.com/6438760/117712382-88b9e780-b1d4-11eb-98b9-d232a8558c69.png" alt="Identity Overrides for Feature Flags" />
</details>

**Comment by alexkreidler** [comment]
Also may be worth looking at [Growthbook](https://github.com/growthbook/growthbook) (AB testing) and [Unleash](https://github.com/Unleash/unleash) (feature flags + AB testing), two open source projects. They each have a list of features and screenshots that may be helpful.

The [Unleash docs](https://docs.getunleash.io/) mention that
> feature toggles are evaluated in a client SDKs which runs as part of your application. This makes toggle evaluations super-fast (we talk nano-seconds), scalable and resilient against network disturbances. In order to achieve this Unleash compromises a small update-delay when you change your toggle configurations until it is fully propagated to your application (in terms of seconds and is configurable).

I'll share two points I took away from researching the above: AB testing and feature gating can
1. get very complex, with many sub-features and implementation details
2. have negative performance impacts (especially if implemented incorrectly) because they are evaluated while each user uses the app

Based on this, you may want to investigate building integrations these projects (and maybe their paid and closed-source competitors) rather than try to build out these features in PostHog itself. But who knows- I may be overestimating the complexity and there might be greater value in having it all in one application.

Thanks for all your work on this great project!

**Comment by marcushyett-ph** [comment]
Adding some more feedback on this from (https://app.hubspot.com/contacts/6958578/company/6406150151):
* Whichever feature is turned on should be consistent for everyone in an organization - so colleagues don't get a totally confusing and different experience (B2B product)
* Would ideally like to understand some statistical significance of changes to validate whether a change is better or worse with some degree of confidence
* We expect our users to understand the nuances of the data - e.g. if there's one big customer and they end up in the test group - they should know to filter them out in the results or take account of them some other way (this is true for any other analysis on PostHog)
* Primary use case is to understand when a feature is underperforming expectations - will launch based on gut feel anyway if results are neutral
* We need to make it easy for  users to do power analysis - figure out how to do A/B testing - we might expect the "data team" to work with individual product teams to help define experiments
* We should be able to define for the experiments this is the goal - this is what we expect to see from the results
* Theres a risk people will wait for a P-value to go over threshold by "peaking" rather than letting the experiment run its course
* Non-data people should be able to get a "good-enough" answer about the outcome of their experiment
* We expect product teams to come to us before making big big decisions using data

**Comment by paolodamico** [comment]
We've shipped Experimentation now which superseded this, closing.
