### ISSUE TITLE
Patch 1.21.0 fixes REDIS_URL but configures password incorrectly

### ISSUE THREAD

**Issue by benjackwhite** [PostHog/posthog#3438]
## Bug description

Since closing of https://github.com/PostHog/posthog/issues/3425 the plugin-server now correctly starts up with a REDIS_URL env populated however, it looks like the format is not one that ioredis expects

At https://github.com/PostHog/posthog/blob/master/bin/plugin-server#L31 the REDIS_URL is formatted:

```
redis://x******@redis-host:6379/
```

... whereas ioredis seems to require the extra colon before the password (this I think is not-standard)...
```
redis://:x******@redis-host:6379/
```

... which leads to...

```
[MAIN] 🔴 Redis error encountered! Trying to reconnect...
 ReplyError: NOAUTH Authentication required.
```

## How to reproduce

1. Configure plugin-server to use a redis with AUTH required
2. Run it locally (bin/plugin-server)

**Comment by mariusandra** [comment]
Our apologies for this regression! I pushed out a fix for it in #3439 and will let you know when there's a new chart to try out.

**Comment by mariusandra** [comment]
You can try deploying the same chart again. I published a new `path-1.21.0` docker image.

**Comment by benjackwhite** [comment]
👍 thanks I will try it out

**Comment by benjackwhite** [comment]
@mariusandra Can confirm on our end that the plugin-server is finally fully up and running now 👍
