### ISSUE TITLE
On charts w/ multiple events, make it clearer which line belongs to which series.

### ISSUE THREAD

**Issue by kpthatsme** [PostHog/posthog#3448]
## Is your feature request related to a problem?

When looking at charts with multiple series, it can be pretty hard to determine which line represents which chart. We can hover over the lines, but that is still a bit confusing as it lists every series and you need to check if the value you're hovering on matches the series data. 

## Describe the solution you'd like

It would be great if there's a color coded legend on the chart that you can quickly glance at to see which color series matches the event on the chart. Ideally we tie this color back to the event listing as well on the lefthand side, so it's very clear which line belongs to which filter.

As a half-step, I think either adding a color next to the event name on the left hand side _or_ the legend would help. From a UX perspective, adding a color to the lefthand side would probably be easier as we don't need to think about how to display event names w/ lots of filters applied in a small space.

## Describe alternatives you've considered

Another simpler solution would be to just alter the behavior to a hovered line only shows its own data & event info.

**Comment by EDsCODE** [comment]
#935 Currently in progress!

**Comment by kpthatsme** [comment]
Woo! Thanks @EDsCODE, will close this.
