### ISSUE TITLE
Change dialogs from hover to click

### ISSUE THREAD

**Issue by JeppeSchmidt** [PostHog/posthog#3453]
I find it so annoying that the dialog closes when I point my mouse outside of it. I by far prefer a click-interaction, so I am sure that the dialog first closes when I want it to close. The hover-interaction demands me to concentrate!

**Comment by paolodamico** [comment]
Thanks for reporting this @JeppeSchmidt, very helpful. Do you have context on some particular instances where this happens? It'll help us address this faster.

**Comment by Twixes** [comment]
I'll close this as it's not really clear what dialogs are problematic, but happy to solve the issue with extra context!
