### ISSUE TITLE
Actions don't happens

### ISSUE THREAD

**Issue by JeppeSchmidt** [PostHog/posthog#3454]
## Bug description
I pretty often experience that I perform an action (duplicate, copy, delete etc.) and it never happens. Sometimes I have to click +5 times before the action happens. 

I suspect it to be casued by bad performance. 

## Expected behavior
I just expect the action to happen the first time :D 

## How to reproduce

1. Perform one of the actions duplicate, copy, delete

## Environment
self-hosted PostHog, version/commit: _please provide_

**Comment by Twixes** [comment]
Hey! What do you mean by duplicate, copy, delete etc? In which part of PostHog does this occur?

**Comment by JeppeSchmidt** [comment]
Hi,

It happens all places. Maybe it is due to bad performance. I can’t say. We host Posthog ourself.

Bedste hilsner,
Jeppe Schmidt Fallesen
Lead UX Designer
+45 28 79 07 97

[signature_260017227]<https://www.capturi.com/?utm_source=email&utm_campaign=email-signatur-website>

Besøg capturi.com<https://www.capturi.com/?utm_source=email&utm_campaign=email-signatur-website> og følg med på Facebook<https://www.facebook.com/Capturi/?utm_source=email&utm_campaign=email-signatur-facebook>, Instagram<https://www.instagram.com/capturi/?utm_source=email&utm_campaign=email-signatur-instagram> og LinkedIn<https://www.linkedin.com/company/capturi/?utm_source=email&utm_campaign=email-signatur-linkedin>
Privatlivspolitik<https://www.capturi.com/privacy-policy?utm_source=email&utm_campaign=email-signatur-privatlivspolitik>

**Comment by Twixes** [comment]
Hm, could you attach a GIF/recording of this happening in PostHog?

**Comment by Twixes** [comment]
I have trouble reproducing this, so I'll close, but happy to investigate if still a problem.
