### ISSUE TITLE
Paths could be prettier with 1 user

### ISSUE THREAD

**Issue by Tannergoods** [PostHog/posthog#346]
***Thank*** you for reporting bugs - we appreciate every single bug report.

**Describe the bug**
Paths don't look good when there is one user

**To Reproduce**
1. Go to a brand new instance of PostHog
2. Navigate through your setup
3. Go to paths
4. See error with one user interacting

**Expected behavior**
I should be able to clearly see the path the user took

**Screenshots**
<img width="1133" alt="Posthog" src="https://user-images.githubusercontent.com/60791437/76574734-61ee0d00-647a-11ea-8895-119b3dcd39dc.png">

**Desktop (please complete the following information):**
 - MacOS
 - chrome

**Comment by jamesefhawkins** [comment]
I’d suggest we either wrap the text or clip the url length and display it in full on hover, as even with multiple users the overlapping text isn’t possible to read.

**Comment by anandvenkat4** [comment]
Team,

As discussed with Tim over email, this issue is fixed and I have raised a PR against this. Please review.
