### ISSUE TITLE
Multi-day date filter in sessions

### ISSUE THREAD

**Issue by macobo** [PostHog/posthog#3471]
## Is your feature request related to a problem?

Currently in sessions you need to select a date to filter by. This can be annoying if searching for a specific session (via filtering)

## Describe the solution you'd like

Have a dropdown instead, with the default being "Last 30 days".

## Additional context

The original reason for this limitation was performance - implementing this should also involve checking whether it continues working in all conditions.

**Comment by paolodamico** [comment]
+1 on this! This is my single biggest pain point too when watching session recordings. Using our default timeframe dropdown should be the best approach here as you mention. Related but not part of this issue, we do need to improve the UX of that filter (as detailed in the relevant issue).

**Comment by macobo** [comment]
Some context on this:

This has two distinct components:
1. Performance - current implementation of this _will_ fail on larger clickhouse and postgres teams due to the amount of data processed. Optimizing this is also tricky, multi-day work at minimum.
1. Design - we need a proper multi-day search filter (dropdown) designed. cc @clarkus 

Given that the solutions arrived at https://github.com/PostHog/posthog/issues/4884 simplify the logic a lot making the performance issues go away, I'd suggest _not_ working on this until then but bundling this into that project.

**Comment by clarkus** [comment]
Related https://github.com/PostHog/posthog/issues/2779

**Comment by paolodamico** [comment]
Based on the resolution for #4884 (https://github.com/PostHog/posthog.com/pull/2028), we can now close this.
