### ISSUE TITLE
"Bucketing" data in trends

### ISSUE THREAD

**Issue by Tannergoods** [PostHog/posthog#348]
***Thank*** you for your feature request - we love each and every one :)

**Is your feature request related to a problem? Please describe.**
When I look at the number of actions a user takes it lists all the values in action trends.

**Describe the solution you'd like**
When creating an Actions Trends graph I would like to be able to visualize for instance <4 times, 5-9 times, 10+ times

**Describe alternatives you've considered**
Export data and plot in a spreadsheet?

**Additional context**
Requested by: https://app.hubspot.com/contacts/6958578/contact/39151

**Comment by timgl** [comment]
This is cool! The slight problem with this is that it's hard to create buckets automatically that make sense.

**K-Means clustering**
One option is doing [K-Means clustering](https://blog.exploratory.io/creating-buckets-or-clusters-for-numeric-column-values-in-exploratory-d04901b32d35). This will create buckets automatically, but they might not be exactly what someone needs.

**Manual buckets**
Manual buckets will mean it's much more configurable, however I think the UX for this will be a nightmare to create/maintain.

@Tannergoods Thoughts? Is it worth getting back to that person to get a feel of what they think?

**Comment by paolodamico** [comment]
@EDsCODE @marcushyett-ph do we want to consider this with the trends overhaul or should we just close this?
