### ISSUE TITLE
Funnel - per user list - more than 100 / sorting

### ISSUE THREAD

**Issue by jereze** [PostHog/posthog#3491]
## Is your feature request related to a problem?

(v1.21.0)

On Insights > Funnels, the "Per user" list has 2 limits:
* limit to 100 users
* users who completed the funnels are first

It does not help me to find users who left the funnel (use case: I'd like to understand why they drop, so I open their activity list and try to understand).

For example: in this case, I have 156 / 172 users who reached the step 2.
I cannot find users who didn't reach step 2.

![image](https://user-images.githubusercontent.com/4386500/109193159-5fbeb480-7798-11eb-9f7e-bfe9b017af90.png)

## Describe the solution you'd like

* Ability to display more than 100 users
* Sort: when clicking on the header in the table, order first by user who did not complete the step.

## Describe alternatives you've considered

* Filtering on less data to find users

## Additional context

Thanks!

**Comment by macobo** [comment]
Thanks for sharing the idea!

One additional option/thought: By clicking on part of the funnel visualization, it would pop up a modal similar to insights/retention listing the users, allowing to create a cohort. :)
