### ISSUE TITLE
Allow extending posthog.js via plugins

### ISSUE THREAD

**Issue by macobo** [PostHog/posthog#3504]
## Is your feature request related to a problem?

There are a lot of features which are useful from a "build a successful company" or product analytics standpoint, but which are niche enough to justify building into core posthog.

Some common ones are ones which interact with the users product in some ways

- User surveys, feedback
- Notifications (e.g. notifying users about updates, etc)
- Opt out tools

It would be great if we could build them out via plugins.

## Describe the solution you'd like

A special type of plugin which, which loads some javascript from a plugin.

So for a survey(monkey) plugin, when a user would visit a site with posthog:
- /decide endpoint gets called
- It returns some extra javascript to execute on the page which creates a survey
- After survey is filled (or ignored) it sends events to posthog.

For posthog users they would need to:
- Go to plugins
- Configure and enable "survey" plugin
- This would include define the criteria of people they're interested in (e.g. via naming a feature flag)
- Later on analyze the results in posthog.

For plugin creators:
- They would define a plugin, by defining the code that would get loaded into posthog.js
- Optionally need to define a parameter which is the user filter criteria (e.g. a feature flag input)

## Describe alternatives you've considered

Build it ourselves

## Additional context

Idea from call with customer today. Curious on your thoughts @mariusandra @jamesefhawkins @Twixes @yakkomajuri

**Comment by mariusandra** [comment]
Interesting idea. An alternative to serving JS inside `/decide` (might make the request huge?) is to do it similar to session recordings --> later on we download the necessary JS from `app.posthog.com/js/:team_id/plugins.js` or something like that.

**Comment by macobo** [comment]
Another idea that came up - cloning https://announcekit.app/ :)
