### ISSUE TITLE
Client error when defining Action trend

### ISSUE THREAD

**Issue by alex-ketch** [PostHog/posthog#351]
**Describe the bug**
Attempting to define 'Action trends' on a new account results in errors, making it impossible(?) to create reports.

**To Reproduce**
1. Go to 'Trends' view
2. See error in console
3. Add an action filter
4. No data graph is presented

**Expected behavior**
1. Go to 'Trends' view
2. Add an action filter
3. See a graph of the results

**Screenshots**

![Kapture 2020-03-13 at 10 04 46](https://user-images.githubusercontent.com/1646307/76628085-93b2b280-6512-11ea-9b26-d7d503cfd92a.gif)

---

![Kapture 2020-03-13 at 9 44 26-314](https://user-images.githubusercontent.com/1646307/76628308-e8562d80-6512-11ea-825c-8aa18640b2e0.png)

---

![Screen Shot 2020-03-13 at 09 31 14](https://user-images.githubusercontent.com/1646307/76626639-e76fcc80-650f-11ea-8e18-9b929c645a71.png)

**Desktop (please complete the following information):**
 - OS: macOS 10.15.3
 - Browser: Safari
 - Version: 13.0.5

**Additional context**

This is on the hosted PostHog instance.

Seems to be due to directly accessing the `id` the last `actions.results` item when the results list is empty (_line 51_).
Not familiar enough with the project to say whether that's a client or backend issue though.

https://github.com/PostHog/posthog/blob/1522c37cc87d409edd8d2fcd363886b7f6bce195/frontend/src/scenes/trends/ActionsGraph.js#L46-L56

**Comment by timgl** [comment]
@alex-ketch Thanks Alex, that is fixed. The reason for this is we normally load in some example actions, but that didn't happen with your account (due to the same issue that caused your token not to be set).

Once you create an action, you should be on your way!
