### ISSUE TITLE
Some teams are not getting any type 2 session recording events

### ISSUE THREAD

**Issue by timgl** [PostHog/posthog#3510]
## Bug description

Team 1810 on app has the following session recording events. Note there are no type 2 events. 
![image](https://user-images.githubusercontent.com/1727427/109349584-7c311e80-7876-11eb-8f97-cf76aca85086.png)

Same reports for team 1377.

See [this internal slack link](https://posthogusers.slack.com/archives/G01JXEDAL22/p1614364403009200?thread_ts=1614305979.000600&cid=G01JXEDAL22) for the rest of the context.

## Expected behavior

Type 2 events (entire dom dumps) should get sent correctly

## How to reproduce

1.
2.
3.

## Environment

- [ ] PostHog Cloud
- [ ] self-hosted PostHog, version/commit: _please provide_

**Comment by mariusandra** [comment]
Probably fixed by https://github.com/PostHog/posthog/pull/3566
