### ISSUE TITLE
Improve graphs/dashboard empty states

### ISSUE THREAD

**Issue by paolodamico** [PostHog/posthog#3514]
## Is your feature request related to a problem?

Currently we have two different empty states for when graphs (in trends and dashboards) have no data. Both of these states are not great (either from a UI or UX standpoint [not very actionable in how to fix]). 

<img width="659" alt="" src="https://user-images.githubusercontent.com/5864173/109405319-4ea2ae80-7924-11eb-94ff-a66cba44dfc9.png">
<img width="659" alt="" src="https://user-images.githubusercontent.com/5864173/109405321-51050880-7924-11eb-86ab-a4e7a3f63cdc.png">

## Describe the solution you'd like

I'd like us to come up with some very useful and visually attractive empty states. Similar to what we did when a query time outs or errors.

## Describe alternatives you've considered

Keep the current messages.

## Additional context

Related to https://github.com/PostHog/posthog/pull/3513

#### *Thank you* for your feature request – we love each and every one!

CC @kpthatsme

**Comment by corywatilo** [comment]
What would you want to see here? Aside from something more visual, probably some text about:

- Common troubleshooting steps
- Instructions on how to track events if `total number of events in instance == 0`?
- Other ideas?

**Comment by corywatilo** [comment]
Pasting this for my own reference of other error states:

![image](https://user-images.githubusercontent.com/154479/109516935-c1bc3a00-7a76-11eb-9582-21bc6ce4ea59.png)

**Comment by paolodamico** [comment]
- Additional common troubleshooting options: extend the search (i.e. remove filters or extend the timeframe).
- If it's action-based, maybe something around checking the action to make sure it's property set up to match the desired events.
- If it's a property aggregate value there might also be something around properties having incorrect types (e.g. numbers formatted as strings), or events not having the correct property.

**Comment by clarkus** [comment]
Closing in favor of https://github.com/PostHog/posthog/issues/3982
