### ISSUE TITLE
Person filters don't reset

### ISSUE THREAD

**Issue by mariusandra** [PostHog/posthog#3524]
## Bug description

- When setting filters on a user, I can't seem to unset them

## How to reproduce

![2021-03-01 17 07 05](https://user-images.githubusercontent.com/53387/109524458-d7e6ec00-7ab0-11eb-9616-3321f233ff84.gif)

## Environment

- [ ] PostHog Cloud
- [x] self-hosted PostHog, latest playground (1.22)

**Comment by ungps** [comment]
This happens when we are having just 1 filter. If we are adding two filters and delete one of them, the events table updates successfully.
