### ISSUE TITLE
When adding a breakdown or filter to an event / chart, only show available properties

### ISSUE THREAD

**Issue by kpthatsme** [PostHog/posthog#3549]
## Is your feature request related to a problem?
When adding a breakdown to a chart or adding a filter to an event, the property list shows what looks to be a list of all properties sent with any event. 

This makes it hard to get to the right filters for the particular event, especially if there are similarly named properties. It's also difficult to know which properties are available on a particular event.

## Describe the solution you'd like
The properties menu dropdown should only show properties that belong to the events specified in the particular chart.

## Describe alternatives you've considered
Taxonomy will definitely help with some of the global confusion but this is more targeted to query time UX.

**Comment by neilkakkar** [comment]
Progress 🚀
