### ISSUE TITLE
Permanently hanging action

### ISSUE THREAD

**Issue by kpthatsme** [PostHog/posthog#3550]
## Bug description

Tried to create an action w/ a few 'insights viewed' events. 

First time, there was a [Sentry error](https://sentry.io/organizations/posthog/issues/2245617126/?referrer=alert_email&environment=production).

I went back to recreate it and it seemed to work, but failed once I added the fourth event to [this action](https://app.posthog.com/action/4911#backTo=Actions&backToURL=%2Fevents%2Factions) – which is permanently hung.

<img width="955" alt="Screen Shot 2021-03-01 at 6 02 00 PM" src="https://user-images.githubusercontent.com/5965891/109585400-51360d00-7ab8-11eb-9b1e-9b2603cc9267.png">

In the console I see a 500 from ```GET https://app.posthog.com/api/action/4911/```

## Expected behavior
- The action would load or show an error message if configured improperly.

## How to reproduce

1. I _think_ it may have to do with adding a match group to 
'insights viewed' w/ filters of insight == RETENTION and same_retention_and_cohortizing_event == true
2.
3.

Adding this to an action seems to do it consistently: 
<img width="802" alt="Screen Shot 2021-03-03 at 6 46 54 PM" src="https://user-images.githubusercontent.com/5965891/109903861-3c40b180-7c51-11eb-8d13-01807b63827a.png">

## Environment

- [x] PostHog Cloud
- [ ] self-hosted PostHog, version/commit: _please provide_

**Comment by Twixes** [comment]
This also happens when trying to view an action that does not exist (or does exist, but not within the current project), say https://app.posthog.com/action/999999999.

**Comment by kpthatsme** [comment]
So one way to reliably repro this is to add the attached to the action.  I'm able to query this event and property fine in a normal chart [
<img width="802" alt="Screen Shot 2021-03-03 at 6 46 54 PM" src="https://user-images.githubusercontent.com/5965891/109903658-e66c0980-7c50-11eb-88a5-015d25e19665.png">
](url)

**Comment by kpthatsme** [comment]
Closing in favor of new ticket I opened https://github.com/PostHog/posthog/issues/4195
