### ISSUE TITLE
It looks like not all text of a long event attribute is being displayed in the UI in the events properties screen

### ISSUE THREAD

**Issue by andrewm4894** [PostHog/posthog#3554]
## Bug description

It looks like not all text of a long event attribute is being displayed in the UI in the events properties screen

If i send an event like this 

```
import posthog
from datetime import datetime
posthog.api_key = '<yourkey>'
posthog.host = '<your posthog>'
posthog.debug = True
# send an event
posthog.capture(
    distinct_id='andy-laptop',
    event='dev',
    timestamp=datetime.now(),
    properties={
        '$current_url': 'dev',
        '$pathname': 'dev',
        '$host': 'dev',
        '$ip': '127.0.0.1',
        'host_collector_modules': '/proc/pressure|alarms||/proc/diskstats|/proc/softirqs|/proc/uptime|systemd|/proc/net/sctp/snmp|/proc/meminfo|||/proc/net/dev|/proc/net/stat/nf_conntrack|/proc/loadavg|ipc|/proc/net/sockstat/this_will_not_be_visible_in_the_ui'
    }
)
```

In the UI i see:

![image](https://user-images.githubusercontent.com/2178292/109654161-c3aaf980-7b59-11eb-9800-b298b38e59fb.png)

So it seems like i cant see the `this_will_not_be_visible_in_the_ui` part of the string - looks like it has been truncated at about 190 characters. 

## Expected behavior

It would be best to just wrap and display all the string text, or at least up to some much higher limit. 

## How to reproduce

1. Send an event like above. 
2. Go to events to look at the "host_collector_modules" attribute of the event you sent.

## Environment

- [ ] PostHog Cloud
- [X ] self-hosted PostHog, version/commit: _please provide_

**Comment by yakkomajuri** [comment]
This should fix it:

https://github.com/PostHog/posthog-js/pull/197

**Comment by andrewm4894** [comment]
Im not quite sure it will - we noticed that less text was visible on the screen than was actually in the span element if you inspect it.

So it was almost like there was a separate UI small issue of not displaying the full text. 

Here is an example of what i mean - you can see the UI seems to be not able to display the full text, its like it should be wrapped or something

![image](https://user-images.githubusercontent.com/2178292/109796338-f0b9e380-7c0f-11eb-91d7-9848f39894cf.png)

**Comment by yakkomajuri** [comment]
Separate UI issue will be fixed by this:

#3560

**Comment by mariusandra** [comment]
The JSON view (#3560) is a workaround to get around this problem. 

The current UI issue comes from the fact that we don't split up really long strings in properties and thus they stretch out the interface and then disappear behind the `overflow: hidden` edge.  The solution is to tokenise the text and add a `<wbr />` in between every 20+ characters and other natural breakpoints (like a dash `"-"`) in a long string, to make it split into the next row as needed.
