### ISSUE TITLE
Extend Plugins to support ML use cases

### ISSUE THREAD

**Issue by andrewm4894** [PostHog/posthog#3567]
## Is your feature request related to a problem?

No, this is more a crazy idea that i think could be awesome if was done right. Decided to share just so it's logged somewhere as probably not the sort of thing that could be tackled in the short to medium term. 

## Describe the solution you'd like

It would be awesome if Posthog came with the ability to in some way have ML based features out of the box (or easily set up via plugins). 

An example use case that springs to mind would be the ability to "turn on" a retention prediction model for all users. So as a new user arrives i could use the ML model (trained offline in batch somewhere based on say the previous 90 days of sessions, all configurable in some way) to predict the probability to that user being a retained user in some sense based on they way they initially came to our site and evolving and updated as we observe their behaviour, 

So for example a user on day 1 might have a score that's maybe not the most accurate but by day 7 we may have observed enough usage behaviour from them to get a pretty good model/score (at least a lot better then just a random guess) of how much we expect them to be retained (or indeed have any sort of outcome or goal that matters to you which you could configure or "enable" predictive ml models for).

So as a business user then i might have a sort of score or grade for each user in terms of likelihood of them to perform certain actions within some time frame that matters to me. This could be made as easy as possible for users so for instance you automatically generate and maintain a cohort of users who are more likely than average to convert into retained user or whatever each goal is. 

As a user then you are no longer trying to guess what types of users might reach certain milestones - posthog has learned and used ml to give you a helping hand in some sense.   

## Describe alternatives you've considered

Usually bigger companies will build this sort of stuff internally and then maybe deploy the model in some way onto their site or in offline batch mode for follow up marketing campaigns etc. 

But a lot of companies and users just don't have the ability or resources to do this properly and seems to me a tool/platform like posthog could have the ability to solve this somewhat or make progress on it and it could be an amazing feature. 

## Additional context

- Not sure if plugins the right approach.
- Where does the model training happen is a big question. 
- How do you define the models and features etc. 
- Would be good to use some open standard like onnx for deploying and portability. 
- Model management and orchestration is a whole big issue. 
- Making predictions and scores available in real time could also be really interesting but would also require a whole prediction layer as well.

**Comment by yakkomajuri** [comment]
Thanks for sharing @andrewm4894 !
