### ISSUE TITLE
Allow 'and' clauses in cohort creation

### ISSUE THREAD

**Issue by kpthatsme** [PostHog/posthog#3572]
## Is your feature request related to a problem?

I want the ability to only look at users who have completed both Action A _and_ Action B.

## Describe the solution you'd like

An `and` clause in addition to the current `or` clause in cohort creation.

## Additional context
Another solution to this kind of problem would be to allow Actions to be part of other Actions, but I think cohorts is a pretty natural way to do this kind of combination.

**Comment by yakkomajuri** [comment]
Current hacky workaround:
- Create a third action that encompasses the two others and use that in the cohort.
