### ISSUE TITLE
Refresh dashboard causing charts to have the same data

### ISSUE THREAD

**Issue by kpthatsme** [PostHog/posthog#3573]
## Bug description
Clicking refresh data on this [dashboard](https://app.posthog.com/dashboard/2256) causes a majority of the retention charts to show the same data.

When clicking the individual refresh buttons on the toggle, the correct data loads. 

## Expected behavior
Refresh dashboard should refresh all the charts individually.

## How to reproduce

1. Load the linked [dashboard](https://app.posthog.com/dashboard/2256) (need to be logged into the PostHog cloud app)
2. Most of the retention charts show the same data 
3. Refresh a couple of individual tiles, the data will update
4. Click refresh dashboard and the state will go back to the replicated images

## Environment

- [x] PostHog Cloud
- [ ] self-hosted PostHog, version/commit: _please provide_

**Comment by mariusandra** [comment]
I think this is fixed. PR https://github.com/PostHog/posthog/pull/4598 made all dashboard items reload at once. Just tested with your linked dash and all was fine. However I think we could still improve the UX and created another issue https://github.com/PostHog/posthog/issues/4752 to track that.
