### ISSUE TITLE
Improve password reset experience for self-hosted

### ISSUE THREAD

**Issue by paolodamico** [PostHog/posthog#3597]
This comes from a user request/feedback. If a self-hosted instance doesn't have SMTP setup, the password reset experience is pretty bad. Can we think of alternatives to make the experience less painful? An alternative option is around what we've already been discussing of making the SMTP setup very simple and get more users to set this up.

**Comment by Twixes** [comment]
Passwords can be changed by instance admins (`User.is_staff`) in the Django admin interface. And of course there's the shell for those with direct instance access.
As for users, I don't think there's really a reliable way other than email, so we should make sure admins are well-guided. We do have this page: https://posthog.com/docs/configuring-posthog/email
What we could do is allow setting up email (plus possibly other instance-wide settings) on the system status page. The relevant issue is #496. See how Metabase does this: https://www.metabase.com/docs/latest/administration-guide/02-setting-up-email.html
