### ISSUE TITLE
Out of the box 2FA support

### ISSUE THREAD

**Issue by paolodamico** [PostHog/posthog#3600]
## Is your feature request related to a problem?

Currently if you want to add 2FA support for PostHog, the only option is through a social authentication provider, yet this is not ideal because a) not everyone has support or wants to use this providers, and b) we don't enforce that users in an org are required to log in using these social auth providers.

Won't dive into the merits of having 2FA here, but it can greatly improve the protection of user data.

## Describe the solution you'd like
I'd like us to offer the option to add 2FA to your account through something straightforward like TOTPs. We should also allow admins/owners to enforce 2FA for all members in an org.

## Describe alternatives you've considered

- Enforce social auth & support other SSO/SAML logins.
- Allow OTPs with other more complex mechanisms (complex in the sense that it'll require extra config on self-hosted instances), e.g. SMS, Duo, Authy, ...

## Additional context
Requested by a user with stronger privacy concerns and/or some compliance requirements.

**Comment by Twixes** [comment]
I suppose this supersedes #256.
It's been a year now!

**Comment by FredrikZeiner** [comment]
Any news? Would also be nice to add support for security keys like the Yubikey.
