### ISSUE TITLE
Segmenting on property at steps in funnel

### ISSUE THREAD

**Issue by fuziontech** [PostHog/posthog#3601]
## Is your feature request related to a problem?

Not a bug, but it would be super educational if we could segment by property at steps in a funnel.

As an example, you have a step in the funnel that is person converts/buys a plan. A dimension that might be interesting to look at is the % share of users who used credit card, paypal, apple pay, other at the final step and represent that in the funnel graph.

**Comment by paolodamico** [comment]
Duplicate of #3409
