### ISSUE TITLE
Fix main nav bar scroll on Windows/Linux

### ISSUE THREAD

**Issue by paolodamico** [PostHog/posthog#3606]
## Bug description

The main nav bar gets added a scroll bar which looks terrible on Windows & Linux. This also causes some jumpiness (nav bar appears to be resized) when scrolling.

## Expected behavior

Nav bar should behave the same as in macOS.

## How to reproduce

1. Open PostHog on Windows o Linux.

## Environment

- [X] PostHog Cloud
- [X] self-hosted PostHog, version/commit: _please provide_

## Additional context
Also reported by a user via email.

**Comment by viveksonar** [comment]
Heres the video of the bug:
https://www.loom.com/share/db3edd67fdeb454699afbeca055fb49b
