### ISSUE TITLE
New person page not able to show all properties of a user

### ISSUE THREAD

**Issue by eikooc** [PostHog/posthog#3615]
## Bug description

*Please describe.*  
*If this affects the front-end, screenshots would be of great help.*  
Nested properties are being cut off, so the value cannot be read.
![error](https://user-images.githubusercontent.com/1305015/110912444-3cf1db80-8314-11eb-93f7-0680460a2bf0.png)

## Expected behavior
Be able to read the properties of a user, even nested ones.

## How to reproduce

1. Send deeply nested properties
2. Go to person page
3. See that you cannot read the properties.

## Environment

- [ ] PostHog Cloud
- [x] self-hosted PostHog, version/commit: _please provide_

**Comment by yakkomajuri** [comment]
Hey @eikooc ! This is definitely something we should look into improving.

However, the [Property Flattener Plugin](https://posthog.com/plugins/property-flattener) could be useful to you

**Comment by Twixes** [comment]
This is solved now.
