### ISSUE TITLE
Release 1.24.0 – 29 March 2021

### ISSUE THREAD

**Issue by timgl** [PostHog/posthog#3622]
- Libraries: feature flags, React Expo support, keeping up to date with analytics. Most popular libraries (not up to date) are node and react-native.
- Plugins
- Tackle a bunch of UI/UX/bugs stuff (@paolodamico to come with a concrete list)
- Session recording chunking/UX (have a list with only recorded sessions for example, default to filter + tooltip)
- VPC

Eric
- Support Hero

Paolo/Tim
- Tackle a bunch of UI/UX/bugs
- Find mobile dev
- Stretch: node and something else (ruby?)

Karl/Michael
- ~~Action mapping~~ Reworked in Python, though in due time we'll need to integrate it into ingestion (plugin server) for maximum performance
- ~~Plugin server core refactor (PostHog/plugin-server#47)~~ Done
- Plugin logs (#3482)
- ~~Instability in ingestion~~ Greatly reduced, should be golden until we introduce a lot of large users or plugins kill us.
- ~~Chunking session recordings~~ 
- ~~Stretch: Session recording~~ Work turned out to be not relevant

Marius/James G
- VPC

**Comment by macobo** [comment]
From discussion w/ Yakko/Marius/Michael: We should also work on action mapping in plugin server this release.

After the current patch release we create a celery task per event to do the action matching. This can lead to redis OOM => data loss, especially for FOSS. We should do the matching in-memory (if possible) in redis instead.

TODO:
- https://github.com/PostHog/posthog/issues/3632
- Session recording UX
- Action mapping live
- Work with Michael on logs
- Plugins ingestion stability

**Comment by paolodamico** [comment]
Here's the list of UI/UX improvements & fixes I'd like to tackle on the next release. The list will probably be a bit fluid throughout the release as we find other things to improve. Please feel free to share feedback on the list, and happy to pair up  if anyone is interested.

- ~Revamp the error experience. When something goes wrong, make sure we show useful error messages, actionable, and with a nice UI. **🔎 Focus**.~
- ~Timezone / time-range experience #2778. **🔎 Focus**.~
- ~Related to #3344, more dashboard UX improvements #3547 (e.g. tagging, description, empty/error states, ...). **🔎 Focus**.~
- ~Improve the feature flags experience #1807. **🔎 Focus**.~
- ~Hotkey support test #2907. **🔎 Focus**.~
- ~New login & signup page #3339. **🔎 Focus**.~
- Will also tackle a bunch of little fixes from @corywatilo's [list](https://www.notion.so/PostHog-app-feedback-da8e96b246a04baf99dc864194977b15)
- Connect documentation & add help hints on insights.
- `SITE_URL` warning, email config & other misconfig warnings. 
- Improve the graphs legends experience.
- Try out #2984

Potential additions:
- Not sure if @EDsCODE and/or @timgl do you want to work together to finish the improvements on #3344? The big outstanding features are version control / history, discussion (commenting), Slack previews and the squared grid layout experience.
- Would love to tackle #2760 (filtering UX), waiting on @corywatilo's input on whether we can do this on the release or leave it for a future one (as it'd be quite a big project).

**Comment by corywatilo** [comment]
@paolodamico I think filtering UX will be an ongoing project. There is some low-hanging fruit (bugs, obvious things we see, things that are reported), and then there will likely be some things that will take longer and should be specifically planned for a sprint (stuff that will require rethinking, wireframes, and maybe even getting feedback from users before implementing).

For the time being, I think the Filtering issues section in my [ongoing list of (unfiled) app UX improvements](https://www.notion.so/watilo/PostHog-app-feedback-da8e96b246a04baf99dc864194977b15) are a good place to start.

Tangentially related: [here's a filtering bug](https://github.com/PostHog/posthog/issues/3355) I ran into that could be added to the near-term list.

**Comment by mariusandra** [comment]
I'll be off the first week. For the second:

- Work on whatever needs to be worked on for the plugin server.
- Alternatively, work on adding feature flags to some integration.
- Alternatively, help with getting VPCs productized in any way I can

**Comment by kpthatsme** [comment]
~~@paolodamico @timgl  this is a bug that would be really helpful to have fixed this sprint https://github.com/PostHog/posthog/issues/3574 it's blocking some of our internal dashboard work and I think a pretty general use case (showing a trends and steps funnel on a dash)~~


fixed https://github.com/PostHog/posthog/pull/3641

**Comment by weyert** [comment]
> * Libraries: feature flags, React Expo support, keeping up to date with analytics. Most popular libraries (not up to date) are node and react-native.

Love to discuss the Node library when you will be working on it :)

**Comment by timgl** [comment]
Retrospective:

Eric
- First week lots of plugin issues
- Second week lots of self hosted issues (lots of memory issues)
- Action recalc

Paolo
- Got through everything by prioritising well
- Spend 90% of my time coding, will balance that more this week

Tim
- Too busy/ill to get programming work done
- Taking myself off the rotation

Karl
- Happy about past two weeks: performance issues & session recording chunking
- Last sprint was getting started with plugins, really ramped up these two weeks

Michael
- Got on well, pretty much everything was done + plugins on cloud now
- shipped geoIP instead of plugin logs

Marius
- "one task and I failed". First week was off. 
- Second week mostly did plugins
- If you're support hero people will keep contacting you specifically
- No VPC: we never really started, felt like plugins blocking were more pressing

James G
- Feel similarly as Marius
- We've been jumping around a ton with VPC but nothing is getting done
- If we hire an SRE there's a ton of ramp-up time with CloudFormation/k8s

**Comment by paolodamico** [comment]
This has been released, closing.
