### ISSUE TITLE
More power to webhook messages

### ISSUE THREAD

**Issue by yakkomajuri** [PostHog/posthog#3628]
## Is your feature request related to a problem?

Funny to open this as we're discussing the value of webhooks but I'd love to be able to access event properties in webhook messages, for example. 

## Describe the solution you'd like

Here's an example message I'd like to have:

```
[action.name]! Invoice for [user.name] with current value of [event.properties.invoice_current_amount] will be created on [event.properties.invoice_date]
```

## Describe alternatives you've considered

Leave as is.

**Comment by Twixes** [comment]
Yes, formatting is a persistent issue. See: #1543. I'll close this issue since the other one has more context.
