### ISSUE TITLE
Dashboard editing (and locking) permissioning

### ISSUE THREAD

**Issue by Twixes** [PostHog/posthog#3636]
## Is your feature request related to a problem?

Currently all dashboards can be edited by all organization members. This poses a risk of people touching dashboards they should leave alone.

## Describe the solution you'd like

 Per-dashboard solution proposed by user on Slack:
> A few options like:
>
> - Locked - only the creator can edit
> - Locked to admins - all admins can edit
> - Open - everyone can edit
>
> Organization Owner then able to edit all (in case a user leaves for example).

**Comment by paolodamico** [comment]
I'm not really sure about the direction of this. In a general sense, I think this introduces more mental burden than the value it provides, we know how to communicate everywhere how these permissions work and introduce complexity to our users on now needing to figure out permissions, and how to manage dashboards. We're also not limiting any functionality based on roles just yet, which could prove confusing. I also think this could hinder collaboration.

I think the introduction of the version control in #3551 will more graciously address when something gets broken down accidentally by another team member.

Thoughts?

**Comment by Twixes** [comment]
I agree that version control is a far more useful idea, so I'll leave this issue open as an extra thing to think about, but let's not tackle it now.

**Comment by camerondeleone** [comment]
Adding a +1 for this feature set, which came up [here](https://app.hubspot.com/contacts/6958578/deal/6941648207/) most recently. I'm not sure if it's a must have, but it certainly will be helpful for getting more users within an org onto the platform. 

The paradigm I've seen used elsewhere for this (eg Airtable) is for the creator of the dashboard to decide whether it is editable by anyone or only them (a 'collaborative' dashboard or a 'personal' dashboard). This can simplify the logic quite a bit over the myriad other possible implementations. (Edit: on second read, this sounds like what the original requester was suggesting)

There is also the question of the visibility of these 'personal' dashboards, which adds another dimension. But the easy solution here is everything still visible to everyone.

**Comment by camerondeleone** [comment]
This functionality was requested by [another customer](https://app.hubspot.com/contacts/6958578/deal/7049184084/). As we continue working with larger enterprise clients, this will become a more common request.

**Comment by paolodamico** [comment]
This seems potentially quite helpful for enterprise (and maybe scale) customers but I think it's worth spending time on thinking the right scope and UX here. Do we want to have different state for dashboards? View/edit permissions per dashboard? Private dashboards that can be shared?

@clarkus @alexkim205 @Twixes I think it's worth having a discussion around the UX here as part of collaboration when we decide to prioritize the related issues.

**Comment by Twixes** [comment]
This has been shipped.
