### ISSUE TITLE
Postgres SELECT queries taking up all server resources

### ISSUE THREAD

**Issue by prawnsalad** [PostHog/posthog#3642]
## In what situation are you experiencing subpar performance?
Almost always, also most likely while the web UI is closed.

There are multiple of these queries running at once which I can only assume is some report being run. It pegs all CPU cores at 100%. As you can see, the query lasts for almost 5 minutes. This impact the web UI by slowing down all other queries being run and in some cases the UI shows an error stating that it is taking too long to show a chart/graph.

~~~
posthog=# explain analyze SELECT json_build_array(jsonb_object_keys(properties)) ->> 0 as key1, count(1) FROM posthog_event WHERE team_id = 1 AND timestamp > '2021-02-10T20:28:44.371576+00:00'::timestamptz group by key1 order by count desc;
                                                                                QUERY PLAN
---------------------------------------------------------------------------------------------------------------------------------------------------------------------------
 Sort  (cost=3022147.39..3027115.30 rows=1987166 width=40) (actual time=288785.930..288785.934 rows=33 loops=1)
   Sort Key: (count(1)) DESC
   Sort Method: quicksort  Memory: 27kB
   ->  GroupAggregate  (cost=2655913.01..2705592.16 rows=1987166 width=40) (actual time=230741.079..288785.823 rows=33 loops=1)
         Group Key: ((json_build_array((jsonb_object_keys(properties))) ->> 0))
         ->  Sort  (cost=2655913.01..2660880.92 rows=1987166 width=32) (actual time=226645.264..274582.864 rows=45162830 loops=1)
               Sort Key: ((json_build_array((jsonb_object_keys(properties))) ->> 0))
               Sort Method: external merge  Disk: 964568kB
               ->  Gather  (cost=1000.00..2352937.78 rows=1987166 width=32) (actual time=524.643..70081.417 rows=45162830 loops=1)
                     Workers Planned: 2
                     Workers Launched: 2
                     ->  Result  (cost=0.00..2153221.18 rows=82798600 width=32) (actual time=660.992..58003.711 rows=15054277 loops=3)
                           ->  ProjectSet  (cost=0.00..704245.68 rows=82798600 width=32) (actual time=660.979..24988.899 rows=15054277 loops=3)
                                 ->  Parallel Seq Scan on posthog_event  (cost=0.00..284042.79 rows=827986 width=890) (actual time=660.965..15529.828 rows=662433 loops=3)
                                       Filter: (("timestamp" > '2021-02-10 20:28:44.371576+00'::timestamp with time zone) AND (team_id = 1))
 Planning Time: 0.226 ms
 JIT:
   Functions: 22
   Options: Inlining true, Optimization true, Expressions true, Deforming true
   Timing: Generation 15.163 ms, Inlining 844.089 ms, Optimization 620.443 ms, Emission 517.282 ms, Total 1996.977 ms
 Execution Time: 288987.025 ms
(21 rows)
~~~

This part looks interesting:
~~~
         ->  Sort  (cost=2655913.01..2660880.92 rows=1987166 width=32) (actual time=226645.264..274582.864 rows=45162830 loops=1)
               Sort Key: ((json_build_array((jsonb_object_keys(properties))) ->> 0))
~~~

It's converting a column from 45,162,830 rows to JSON, then sorting based on that and taking 4.5 minutes to do so. Perhaps adding a new column to cache the `jsonb_object_keys(properties)` on row insert/update will speed this up dramatically as it can then sort on an index.

## How to reproduce

Insert data. Query data.

## Environment

- [ ] PostHog Cloud
- [*] self-hosted PostHog, version/commit: Unknown version, package.json says `0.0.0` and I can't find it in the UI. Installed via docker as of 4 days ago.

**Comment by prawnsalad** [comment]
Adding to this, it's got to the point where my dashboard says `There are no panels on this dashboard.` when I do have some - the server is just obviously too overloaded now.

**Comment by prawnsalad** [comment]
After adding a column to cache the value (if it's even possible to cache... i'm not sure exactly where the query is coming from):

4.8 minutes to 9.3 seconds

~~~
Sort  (cost=571990.56..571991.06 rows=200 width=40) (actual time=9172.252..9252.472 rows=1 loops=1)
  Sort Key: (count(1)) DESC
  Sort Method: quicksort  Memory: 25kB
  ->  Finalize GroupAggregate  (cost=571932.25..571982.92 rows=200 width=40) (actual time=9172.208..9252.422 rows=1 loops=1)
        Group Key: properties_keys
        ->  Gather Merge  (cost=571932.25..571978.92 rows=400 width=40) (actual time=9170.767..9250.974 rows=3 loops=1)
              Workers Planned: 2
              Workers Launched: 2
              ->  Sort  (cost=570932.23..570932.73 rows=200 width=40) (actual time=9144.616..9144.650 rows=1 loops=3)
                    Sort Key: properties_keys
                    Sort Method: quicksort  Memory: 25kB
                    Worker 0:  Sort Method: quicksort  Memory: 25kB
                    Worker 1:  Sort Method: quicksort  Memory: 25kB
                    ->  Partial HashAggregate  (cost=570922.58..570924.58 rows=200 width=40) (actual time=9142.676..9142.703 rows=1 loops=3)
                          Group Key: properties_keys
                          ->  Parallel Seq Scan on posthog_event  (cost=0.00..562559.19 rows=1672679 width=32) (actual time=166.175..6049.678 rows=664878 loops=3)
                                Filter: (("timestamp" > '2021-02-10 20:28:44.371576+00'::timestamp with time zone) AND (team_id = 1))
Planning Time: 4.186 ms
JIT:
  Functions: 30
  Options: Inlining true, Optimization true, Expressions true, Deforming true
  Timing: Generation 3.187 ms, Inlining 139.652 ms, Optimization 173.449 ms, Emission 180.890 ms, Total 497.179 ms
Execution Time: 9387.204 ms
~~~

**Comment by timgl** [comment]
Hey, I think I now what's going on. Can you set the `ASYNC_EVENT_PROPERTY_USAGE` env to `0`? I think that'll stop these queries. It means you lose events and property stats.

**Comment by prawnsalad** [comment]
It's been running for around 30minutes with ASYNC_EVENT_PROPERTY_USAGE=0 and things look much better, I can actually see other queries making use of the CPU now.

The event and property stats page does say that they can be delayed by up to an hour so I assume that the heavy query should only run once every hour? In my case there where 3 instances of the query running every time I checked.

Edit: If it's relevant, this is running on a 4 core machine. Maybe it's running on N-1 cores or something.

**Comment by timgl** [comment]
@prawnsalad Great. We were running this query every minute, now we are running it every hour so you might want to upgrade to the latest commit and try again.

**Comment by prawnsalad** [comment]
Awesome, I've updated and set `ASYNC_EVENT_PROPERTY_USAGE=1` to enable it again. The query running each minute would have overlapped causing them to run multiple at a time which shouldn't be an issue now. Leaving it running over night to see how it is tomorrow morning.

**Comment by prawnsalad** [comment]
@timgl all looking good for me since yesterday and with it enabled. Thanks!
