### ISSUE TITLE
Value Bar Charts with colours set (other than white) should have white Y-Axis text

### ISSUE THREAD

**Issue by Mentioum** [PostHog/posthog#3646]
I believe the y-axis text colour needs to be accounted for when initializing chartjs as currently Bar Value Graphs have poor visibility as show below.

## Good
![image](https://user-images.githubusercontent.com/748170/111087540-0ab1cb00-851a-11eb-90b9-dbe395fe5f85.png)

## OK
![image](https://user-images.githubusercontent.com/748170/111087550-1b624100-851a-11eb-9060-85998471608a.png)

## Bad (green is the same)
![image](https://user-images.githubusercontent.com/748170/111087557-29b05d00-851a-11eb-9e94-ceebdbb3b2e8.png)

**Comment by yakkomajuri** [comment]
Thanks for reporting this! Should be a quick fix.
