### ISSUE TITLE
Toolbar heatmap doesn't show any related actions

### ISSUE THREAD

**Issue by EDsCODE** [PostHog/posthog#3656]
## Bug description

*Please describe.*  
If you use the heatmap on the toolbar, you should see actions related to the element that the heatmap shows but there are none.

*If this affects the front-end, screenshots would be of great help.*  

## Expected behavior
Heatmap should show related actions

## How to reproduce

1. Go to heatmap using toolbar
2. Examine an element you would expect matches an action
3. If you create an action from the toolbar, the heatmap will show the related action but if you refresh it will disappear

**Comment by yakkomajuri** [comment]
Is this on `posthog.com` or have you reproduced elsewhere?

**Comment by mariusandra** [comment]
I guess this is the crux of the bug @EDsCODE was referring to:

![2021-06-15 12 31 31](https://user-images.githubusercontent.com/53387/122038241-b0a0fa00-cdd5-11eb-84bb-3c3ac35f70fb.gif)
