### ISSUE TITLE
Uninformative webhook message for missing properties

### ISSUE THREAD

**Issue by yakkomajuri** [PostHog/posthog#3659]
## Problem Description

Users can choose to fire webhooks on specific actions and specify a message to be sent with it.

This message can access event properties for the event that triggered the action. 

Event properties accessed with `event.properties.desired_prop` will just be substituted with `undefined` if the property doesn't exist and the message will send without issues.

However, when accessing props via `user` (e.g. `user.ip`), we raise a `ValueError` and send a non-helpful message to the webhook. 

See:

https://github.com/PostHog/posthog/blob/316e2a6f4dba8030a2c71098528a28a362f96582/posthog/tasks/webhooks.py#L97

## Desired Solution

If a `user` property doesn't exist, we should:

- [ ] Send it as `undefined` via the webhook like we do with event properties
- [ ] List the errors in the action's page with a timestamp, message, and the event in question

Another approach would be to just get rid of `user` altogether and access everything via the new `event.properties` - but that might break messages for existing users.

Happy for these to be tackled in separate PRs by a new contributor. 

## Related Issue

https://github.com/PostHog/posthog/issues/1543

**Comment by Twixes** [comment]
I think this was solved in #3685.
