### ISSUE TITLE
Funnel Trends blank page: Invalid attempt to spread non-iterable instance

### ISSUE THREAD

**Issue by yakkomajuri** [PostHog/posthog#3667]
## Bug description

First time I tried to use funnel trends:

https://user-images.githubusercontent.com/38760734/111339135-6e014180-866f-11eb-828b-ab4376366d9c.mov

Here's the error:

```
TypeError: Invalid attempt to spread non-iterable instance.
In order to be iterable, non-array objects must have a [Symbol.iterator]() method.
    at e.exports (nonIterableSpread.js:2)
    at e.exports (toConsumableArray.js:10)
    at LineGraph.js:145
    at Array.map (<anonymous>)
    at LineGraph.js:143
    at LineGraph.js:65
```

## Expected behavior

A line graph instead of a blank page.

## How to reproduce

1. Go to funnels
2. Select `user signed up` as the first step and `pageview contains posthog.com/docs` as the second
3. Convert to trend

## Environment

- [ ] PostHog Cloud
- [ ] self-hosted PostHog, version/commit: _please provide_

**Comment by yakkomajuri** [comment]
cc @kpthatsme given you wanted to release this

**Comment by kpthatsme** [comment]
This was fixed in https://github.com/PostHog/posthog/pull/3686, thanks to @EDsCODE!
