### ISSUE TITLE
Too much dancing (Feedback)

### ISSUE THREAD

**Issue by yakkomajuri** [PostHog/posthog#3671]
## Is your feature request related to a problem?

The dance of the dashboards doesn't really feel great to me:

https://user-images.githubusercontent.com/38760734/111346692-609b8580-8676-11eb-956f-55392d05c64c.mov

It's too much movement and it takes up a lot of the screen (so essentially the whole screen feels like it's moving)

## Describe the solution you'd like

Less dancing.

## Describe alternatives you've considered

Keep 'em dancing.

**Comment by paolodamico** [comment]
Thanks for the feedback @yakkomajuri! By less dancing you mean slower animation or shorter distance ?

**Comment by yakkomajuri** [comment]
I personally don't like any wobbling, but I'd think a shorter range of motion would be the bigger thing, followed by a bit of the speed.

**Comment by kpthatsme** [comment]
Just used this today! I love that dashboards are default not in edit mode now.

Similar to yakko I feel like the motion is pretty distracting. I think both a reduction in speed + distance would help. 

A few other thoughts:
- Do we need any animations? Maybe the modal with 'finish editing' is good enough
- If we want to keep an animation– perhaps we do it _once_ when the edit pencil is initially clicked
- I think the intent here was to make it very clear you're in edit mode – maybe changing the cursor is enough of a way to do that (in addition to one of the suggestions above).

**Comment by mariusandra** [comment]
Some old context: this wibbly-wobbly was added mainly to make dashboard changes more apparent on mobile mode. The idea was to replicate the feel of the iOS homescreen, where you long-press to enable edit mode, then things start wiggling and you move them around, and then click "save" to stop. With changes to how editing works, this wobbling might no longer be necessary...

**Comment by macobo** [comment]
I was also quite distracted by it. Another option do the "dance" once (e.g. for 0.3s) and stop afterwards, perhaps even on only the first item. 

The wiggle does bring your attention to the fact that these things are now "more" interactable.

**Comment by paolodamico** [comment]
Thanks everyone for all the feedback! Took a run at the options discussed here.
1. Here's what less travel distance (i.e. less wobbly looks like). #3824
![image](https://user-images.githubusercontent.com/5864173/113070277-1090e880-9177-11eb-8460-71606416a9c0.gif)

2. Tried the option on bouncing a little bit and then staying static, but it seems more confusing.

I would either go with 1) or 3) removing wobbling altogether. Thoughts?

**Comment by Twixes** [comment]
IMO we could do without the wobbling effect, since there's "Dashboard edit mode" floating to indicate this pretty clearly. Maybe we could just edit the instruction from "Tap below when finished" (which is pretty obvious, there are two "Finish editing" buttons) to "Drag items to move them around. Grab sides and corners to resize."?
