### ISSUE TITLE
docker-compose should pin image versions

### ISSUE THREAD

**Issue by prawnsalad** [PostHog/posthog#3676]
## Bug description

When updating the containers in a docker-compose setup the containers can upgrade over major versions and break backwards compat. Eg. I wanted to update the posthog container but ran `docker-compose pull` which changed the postgres instance from version 12 to 13 - which then couldn't start due to the data not being backwards compat.

Pinning image versions such as `postgres:12-alpine` ensures the version will always be compatible. Likewise for any other images in use.

## Expected behavior

Updating images should not jump major versions and break posthog.

## How to reproduce

- Install with docker-compose
- Wait until postgres releases a new `latest` tag major version
- Try to update posthog

## Environment

- [ ] PostHog Cloud
- [x] self-hosted PostHog, version/commit: _please provide_

**Comment by Twixes** [comment]
Thanks for pointing out, pinned from now on!
