### ISSUE TITLE
Add more colours to bar chart

### ISSUE THREAD

**Issue by timgl** [PostHog/posthog#3679]
## Bug description

If you break down by a value that has a lot of options (like screen height for example) some values end up being grey.

![image](https://user-images.githubusercontent.com/1727427/111461421-7c0d9b80-871d-11eb-9ce3-1e441faaf75c.png)

## Expected behavior

We should just have _more_ colours, or can even recycle the current colours.

## How to reproduce

1.
2.
3.

## Environment

- [ ] PostHog Cloud
- [ ] self-hosted PostHog, version/commit: _please provide_

**Comment by swong194** [comment]
Hey! Can I take a stab at this?

**Comment by paolodamico** [comment]
Sure @swong194 go for it! Tagging @corywatilo who can provide more context on the colors to use here.

**Comment by corywatilo** [comment]
Thanks @swong194!

[Colorbrewer 2.0](https://colorbrewer2.org/#type=qualitative&scheme=Paired&n=12) has a solid set of 12 unique colors that should provide good differentiation between each. (Will that be enough?)

It will be good to see what these look like in use. We'd probably want to start with the colors at the top and work our way down (leaving brown at the bottom as a last resort).

![image](https://user-images.githubusercontent.com/154479/112643923-3fc3f480-8e1b-11eb-999e-1bfbca290687.png)

(I'm also open to suggestions about other color sets that would provide us with more options.)

**Comment by kpthatsme** [comment]
I think we're going to want at least 20 colors

[This stack exchange post](https://graphicdesign.stackexchange.com/a/3815) has a bunch of options that look pretty promising. 

Out of those, this [20 color set](https://sashamaps.net/docs/resources/20-colors/) seems straightforward to use (though I don't think we should use white or black). There's also a 26 color set in that post that looks pretty good.

I also came across this [generator](https://medialab.github.io/iwanthue/) – but I think the results are random every time it's run so one of the static sets is probably best for now.
