### ISSUE TITLE
Dashboard refresh doesn't seem to do anything

### ISSUE THREAD

**Issue by kpthatsme** [PostHog/posthog#3690]
## Bug description

Clicking on the 'Refresh' button doesn't seem to do anything on a dashboard.

## Expected behavior

The dashboard would refresh all its charts and would show an updated 'Last updated' time

## How to reproduce

1. Go to a dashboard, such as [this](https://app.posthog.com/dashboard/2596)
2. Click 'Refresh' on the header
3. The 'Last Updated' time stays the same and no data appears to change on the charts

## Environment

- [ ] PostHog Cloud
- [ ] self-hosted PostHog, version/commit: _please provide_

## Additional context

No console errors

**Comment by paolodamico** [comment]
This is actually the problem reported in #3609, it does seem to be a bit more confusing than expected. Local refreshes did seem to work better. Could use some help fixing this, I'll add it to my to do for next week otherwise.
