### ISSUE TITLE
Session replay at 0.5x

### ISSUE THREAD

**Issue by kappa90** [PostHog/posthog#3692]
## Is your feature request related to a problem?

I'm trying to debug a user behavior in the sessions, but the pointer is moving too fast.

## Describe the solution you'd like

Play the session at 0.5x.

**Comment by yakkomajuri** [comment]
Thanks for opening! This makes sense to me.

Relevant repo is https://github.com/PostHog/posthog-react-rrweb-player

But there might be some nuance here

**Comment by yakkomajuri** [comment]
Relevant change should be made to:

https://github.com/PostHog/posthog-react-rrweb-player

**Comment by timgl** [comment]
literally a one line change I think: https://github.com/PostHog/posthog-react-rrweb-player/blob/16d90133e0f4293ae5de0cbffb1a35aa0d990f90/src/index.tsx#L38

**Comment by yakkomajuri** [comment]
Indeed that does seem to be the case - I just wondered about the mechanism we used for setting the speed but yeah I've looked into it now.

So I'll leave this here for a day to see if someone is interested in contributing! (@kappa90 ?)

Otherwise I can do it myself tomorrow.

**Comment by kappa90** [comment]
Sure, can't today but will try to do a pull request by the weekend, if it's not done already. Thanks!
