### ISSUE TITLE
Ability to enrich autocapture with specific rules

### ISSUE THREAD

**Issue by andrewm4894** [PostHog/posthog#3695]
## Is your feature request related to a problem?

Kind of - having to make lots of individual manual actions for specific autocapture events is annoying and takes away a bit from the magic of autocapture.

*Please describe.*

## Describe the solution you'd like

Current situation is i see this:

![image](https://user-images.githubusercontent.com/2178292/111628477-2baf4000-87e8-11eb-8c1f-e0a0a090fc7b.png)

So i have an autocapture event called "clicked button".

But on our most important elements we actually have a `data-testid` attribute that we use as part of our testing suite. 

So currently i can manually make an action that looks for specific string `data-testid="date-picker::click-apply::-start"` somewhere and then call that action "Clicked Apply in Date Picker". But i have dozens or maybe even 100's of such attributes. 

What i really want to to tell PostHog - when you see a click on an element that has a `data-testid` attribute then i want you to decode it as "Clicked <f1> in <f0>" where {f1} = "click-apply".replace('click-','').CamelCase() and {f0}="date-picker".replace('-',' ').CamelCase(). 

## Describe alternatives you've considered

Manually setting action for each of my most important elements and attributes.

Maybe somehow using a plugin to do something here - but not sure how feasible that would be. 

## Additional context

I expect we would likely end up with multiple rules like this, eg. we also have a `data-ga` attribute we use to use for GA custom events via data layer. 

So i would need to maintain and prioritize which rule takes priority over the other etc. 

Ideally then when starting clean you could just define a attribute like `posthog-action` and just simply pass through what it is you want PostHog to call it. e.g. `posthog-text="Clicked Apply In Date Picker"` and just have auto capture use that.

But a more flexible and realistic use case is where i can overlay this layer of logic and understanding on top of autocapture as opposed to having to manually create 100's of actions based on specific strings when the underlying logic of what i'm doing is very similar each time. That would be a really amazing user experience and make autocapture even more magical. .

**Comment by yakkomajuri** [comment]
> Maybe somehow using a plugin to do something here - but not sure how feasible that would be.

Given that the use case is taking an event and doing some processing on it, it does smell like a plugin to me.

**Comment by mariusandra** [comment]
I've created a PR #3761 that's one step in this direction. It would allow you to whitelist `data-*` attributes (even with a wildcard) and when those are seen, they're automatically suggested when creating actions.

That PR doesn't tackle what this issue asks, but the next step would be to also show the whitelisted data-* attributes in the events list somehow.

**Comment by andrewm4894** [comment]
cool - you can see some of the (admittedly fairly crazy) logic we have here: https://github.com/netdata/posthog-netdata-event-processing/blob/main/process_elements.js

I'm hoping to clean this up and refactor over time. 

A lot of it is looking for class attributes anywhere in the elements (with order from posthog being priority). Similar for id, href, and some other more specific ones. 

From all these `el_` properties we then derive some higher level semantic properties and its from those i'd like to create actions from too.

But i think starting with a small idea and building from there (like just the `data-*` attributes) is a better idea then trying to solve all this in one go for sure.
