### ISSUE TITLE
Fully remove Moment.js

### ISSUE THREAD

**Issue by paolodamico** [PostHog/posthog#3696]
## Is your feature request related to a problem?

Builds up on #3490. Fully remove Moment from the bundle (currently both AntD and chart.js depend on it). Probably what needs to happen is a Webpack adjustment.

## Describe the solution you'd like

Moment.js should not be included in PostHog's bundle.

**Comment by timgl** [comment]
I'm 99% this is actually complete, I can't find it in any of the build bundles.
