### ISSUE TITLE
Action HTML Selector not filtering out events with matching 'id' selector

### ISSUE THREAD

**Issue by Mentioum** [PostHog/posthog#3710]
## Bug description

When creating actions based on matching HTML selectors it seems to work just fine for classes but when using `id` it seems to not be matching events which one would expect.

Here is an example of a click event on an `a` tag which has an `id` of `spotify-link` in the detected code element inside PostHog:

![image](https://user-images.githubusercontent.com/748170/111853474-15ea6980-8913-11eb-803c-6b11d0026f96.png)
*I even put the `id` on the `img` as well but it made no difference*

Here is an example of the HTML query selector showing it not detecting any events with the selector `a#spotify-link`:

![image](https://user-images.githubusercontent.com/748170/111853543-50ec9d00-8913-11eb-817f-78d682830958.png)
*I also tried with `#spotify-link` (which should also match I believe)*

## Expected behavior
HTML selectors using `id` should filter out events which have that `id`.

## How to reproduce

1. Put an id on a link.
2. Click the link.
3. Create an action which filters for that HTML selector.
4. Nothing will be filtered out even if I can see the raw event in the event log.

## Environment

- [x] PostHog Cloud
- [ ] self-hosted PostHog, version/commit: _please provide_

## Additional context

I've also tried with just `#spotify-id` which should technically also match but it doesn't find anything either.  It's almost like `id's` are being completely ignored in action filters.  I find this surprising as I cant find any other issues about this and I'd assume this would fall under core usage?

**Comment by wushaobo** [comment]
I think your problem is due to duplicate id for elements, while the id selector should be unique across the whole DOM.

The deeper issue comes from how we use selectors to filter event accurately when the click event starts from any possible sub element of the target button/link/div.  
The answer is Posthog does this magically for you. An attribute like `data-ha="your.selector.name"` on click target provides you a good selector `[data-ha="your.selector.name"]` for action. You don't have to worry about the img/span/div inside that click target.

The custom events captured in js code are absolutely accurate, which depend only on your business logic.

**Comment by Mentioum** [comment]
> I think your problem is due to duplicate id for elements, while the id selector should be unique across the whole DOM.

Thanks @wushaobo  That makes a lot of sense.

If you don't mind could I ask a question about how you think it would be best to track multiple links to the same place.  Would you recommend using classes or does `autocapture` also capture `data-xyz="identifiers"`

The reason I'm trying to avoid using classes is mostly due to because Webflow classes are kind of annoying when you want to add multiple classes to specific items (compound classes) - so I try to avoid using them for anything other than styling.

**Comment by Mentioum** [comment]
Answered my own question here after help from @wushaobo.  Used data attributes and then filtered them using 

```html
<a href="alink" data-ph="spotify">Your Link (or whatever)</a>
```
Then filtered with the HTML selector in Actions
```
[data-ph="spotify"]`
```


Didn't work in the full event list though using the CSS selector as a filter.

**Comment by wushaobo** [comment]
@Mentioum  Sorry for getting back late to you. 
The event list cannot be filtered by either selector or custom event but the properties of event. The action is the right place for filtering / summarizing atom events.
There is another issue of posthog which suggesting to support customize event name in the event list, which now is hard to read.

**Comment by paolodamico** [comment]
Thanks for the help here @wushaobo!

@posthog-bot please add @wushaobo for question.

**Comment by wushaobo** [comment]
Awesome!  Thank you @paolodamico .
