### ISSUE TITLE
Cannot type most notes on Dashboard graphs due to keyboard shortcut hijacking

### ISSUE THREAD

**Issue by Mentioum** [PostHog/posthog#3711]
## Bug description
I appreciate the new keyboard shortcuts on dashboards etc (and I like the indicators on the buttons to get people used to them).  However when filling out notes on graphs the shortcuts hijack typing making it impossible to type notes on the dashboard which contain keyboard shortcut letters.  e.g:
I want to write `Podcast Release: {Guest Name}`
![image](https://user-images.githubusercontent.com/748170/111869474-a9ee1c80-8977-11eb-952f-57b6ac460cfb.png)
But when I hit the `s`
![image](https://user-images.githubusercontent.com/748170/111869535-ede12180-8977-11eb-8953-329b2dd73e92.png)

## Expected behavior
For keyboard shortcuts to be disabled when a text field is focused.

## How to reproduce

1. Make a dashboard with a graph which supports notes
2. Type anything in the note which includes an S or an N or an E

## Environment

- [x] PostHog Cloud
- [ ] self-hosted PostHog, version/commit: _please provide_

## Additional context
There are lots of words with those letters in them XD

**Comment by paolodamico** [comment]
Hey @Mentioum! Our apologies for this, and thank you for the detailed bug report! PR is out with the fix, it should land pretty soon.
