### ISSUE TITLE
Upgrade to 1.23.1 is not available

### ISSUE THREAD

**Issue by avorio** [PostHog/posthog#3722]
I ran a standard upgrade from 1.22 just now using:

```
git clone https://github.com/PostHog/posthog.git
cd posthog
git remote add heroku https://git.heroku.com/[your-heroku-posthog-app-name].git
git push -f heroku master
```

... but the system still says I'm on 1.23.0 and that the newest version is 1.23.**1**.

Was something mis-tagged somewhere?

**Comment by mariusandra** [comment]
Hey, indeed this was mis-tagged. It should be fine once [this](https://github.com/PostHog/posthog/pull/3723) is merged.
