### ISSUE TITLE
Blank page when loading user

### ISSUE THREAD

**Issue by adamb70** [PostHog/posthog#373]
`this.Value` undefined at line 13 when trying to view person details. Not sure what is caused the problem to start happening but it affects all users now.
 https://github.com/PostHog/posthog/blob/2a59b9e6a443d47980c1614ddf5b900a9f08da99/frontend/src/scenes/users/Person.js#L13

![image](https://user-images.githubusercontent.com/11885987/76909466-37012000-68a3-11ea-80d5-ee9f31677e01.png)

**Comment by timgl** [comment]
@adamb70 Sorry about that, I've just pushed a new version that should fix this.

**Comment by adamb70** [comment]
I'm getting a new error now from EventsTable.js that's still stopping the page from loading.

https://github.com/PostHog/posthog/blob/e2f53df75597586d9440cd24bd7b2aca76669f84/frontend/src/scenes/events/EventsTable.js#L61

![image](https://user-images.githubusercontent.com/11885987/76912518-1be6de00-68ac-11ea-969e-ab88866f2b45.png)

**Comment by timgl** [comment]
Hm annoyingly I'm struggling to reproduce this. Could you screenshot the response for `/api/events/` ?

**Comment by adamb70** [comment]
I've started a new heroku instance with that latest version and I can't reproduce the issue now either. Thanks for the speedy fix!
