### ISSUE TITLE
Iteration for hotkeys UI

### ISSUE THREAD

**Issue by paolodamico** [PostHog/posthog#3746]
## Is your feature request related to a problem?
Following #3740 we could consider a different styling for showing hotkey actions.

**Example:** (and [context](https://github.com/PostHog/posthog/pull/3740#discussion_r601626806), [more context](https://github.com/PostHog/posthog/issues/2907#issuecomment-757859765))
![image](https://user-images.githubusercontent.com/5864173/112510427-a6c7a780-8d4e-11eb-8075-ea70a089a9a6.png)

Would like to get as much feedback as possible on this, as it can be quite a subjective topic. Also worth doing an A/B test after the initial test is finalized.

**Comment by paolodamico** [comment]
#3757 toned hotkeys down a bit, curious to hear people's thoughts on whether we should go a step further as proposed above.

**Comment by Twixes** [comment]
Actually I think the approach that is live now is pretty clear and not too intrusive, so I propose closing this.
