### ISSUE TITLE
Re-calculating action events can be a costly operation

### ISSUE THREAD

**Issue by MrSaints** [PostHog/posthog#3753]
## In what situation are you experiencing subpar performance?

Occasionally, we have been experiencing severe slowness in our self-hosted PostHog deployment. Though our database is not under heavy load (<30%), querying it seems to take longer than usual during these periods. When we examined ongoing database sessions during these periods, we noticed quite a few long-running queries, example:

```
DELETE FROM "posthog_action_events" WHERE "action_id" = 24 AND "event_id" IN (
    SELECT id FROM posthog_event
    WHERE "created_at" >= '2021-03-25T15:14:07.772805+00:00' AND "created_at" < '2021-03-26T15:19:07.775406+00:00'
);
```

Source: https://github.com/PostHog/posthog/blob/3f56d53b62b9d7790ec4084fd4385d5a3b46e40f/posthog/models/action.py#L42-L55

We tried running the `SELECT` query separately:

```
SELECT id FROM posthog_event WHERE "created_at" >= '2021-03-25T15:14:07.772805+00:00' AND "created_at" < '2021-03-26T15:19:07.775406+00:00'
```

And noticed it took quite some time to return. When we are under heavy traffic with lots of reads / writes, we noticed this tends to be more problematic / slower.

Running two runs of `EXPLAIN ANALYZE` on the query (during a quiet period) yields:

```
Gather  (cost=1000.00..48418.36 rows=1 width=4) (actual time=2192.715..2575.836 rows=2238 loops=1)
  Workers Planned: 2
  Workers Launched: 2
  ->  Parallel Seq Scan on posthog_event  (cost=0.00..47418.26 rows=1 width=4) (actual time=2189.830..2552.445 rows=746 loops=3)
        Filter: ((created_at >= '2021-03-25 15:14:07.772805+00'::timestamp with time zone) AND (created_at < '2021-03-26 15:19:07.775406+00'::timestamp with time zone))
        Rows Removed by Filter: 86945
Planning Time: 0.329 ms
Execution Time: 2575.988 ms

Gather  (cost=1000.00..48418.36 rows=1 width=4) (actual time=1330.501..1440.659 rows=2238 loops=1)
  Workers Planned: 2
  Workers Launched: 2
  ->  Parallel Seq Scan on posthog_event  (cost=0.00..47418.26 rows=1 width=4) (actual time=1318.467..1422.119 rows=746 loops=3)
        Filter: ((created_at >= '2021-03-25 15:14:07.772805+00'::timestamp with time zone) AND (created_at < '2021-03-26 15:19:07.775406+00'::timestamp with time zone))
        Rows Removed by Filter: 86945
Planning Time: 0.068 ms
Execution Time: 1440.800 ms
```

This seems to suggest that the `created_at` column does not have an index. 

We introduced an index to see if it helps:

```
CREATE INDEX posthog_event_created_at_idx ON public.posthog_event (created_at);
```

And performed `EXPLAIN ANALYZE` again:

```
Index Scan using posthog_event_created_at_idx on posthog_event  (cost=0.42..293.64 rows=1401 width=4) (actual time=0.538..1.790 rows=2238 loops=1)
  Index Cond: ((created_at >= '2021-03-25 15:14:07.772805+00'::timestamp with time zone) AND (created_at < '2021-03-26 15:19:07.775406+00'::timestamp with time zone))
Planning Time: 8.239 ms
Execution Time: 1.901 ms

Index Scan using posthog_event_created_at_idx on posthog_event  (cost=0.42..293.64 rows=1401 width=4) (actual time=0.011..0.924 rows=2238 loops=1)
  Index Cond: ((created_at >= '2021-03-25 15:14:07.772805+00'::timestamp with time zone) AND (created_at < '2021-03-26 15:19:07.775406+00'::timestamp with time zone))
Planning Time: 0.104 ms
Execution Time: 1.035 ms
```

And indeed, it seems to be much quicker.

We could alternatively scale our database up to improve the performance of the parallel sequential scan, but in this case, it seems Postgresql has opted for the index scan when present which seems to suggest that this can be a potential optimisation (though may introduce overhead in other areas, e.g. space).

## How to reproduce

To be honest, we have not been able to reliably reproduce this since it is contingent on high traffic hours, and that is normally the time we want to avoid playing around too much to avoid losing events. Now that we have added the index, we will probably update this issue if we notice any improvements.

## Environment

- [ ] PostHog Cloud
- [x] self-hosted PostHog, version/commit: `posthog/posthog:release-1.23.1`

## Additional context

Running on Kubernetes with Postgresql (managed outside Kubernetes).

We have about 30 actions relying purely on `data-attr`.

**Comment by macobo** [comment]
Thanks for the in-depth analysis. Out of curiosity, how many events/month do you ingest (can see total events rows from /instance/status route)?

**Comment by MrSaints** [comment]
@macobo 

This is a relatively new deployment so this is roughly for the past 3-4 days.

```
Postgres events table size | ~298069 rows (~600 MB)
```

**Comment by MrSaints** [comment]
On a related note, we are seeing hourly spikes in our database. It may not be related to any of this, and we will continue to investigate to find the root cause.

![Screenshot 2021-03-26 at 11 22 57 AM](https://user-images.githubusercontent.com/68859/112624649-d1386400-8e25-11eb-9038-4719c800dc74.png)

**Comment by yakkomajuri** [comment]
Hey @MrSaints thanks for the discussion here and in `posthog-js`! Your issues have quite a lot of good context.

@posthog-bot please add @MrSaints for ideas and userTesting

**Comment by Twixes** [comment]
This should now be alleviated (to a degree) by #3767.

**Comment by Twixes** [comment]
I believe this should mostly be resolved now, as we mostly match events to actions in the plugin server in an optimized way.
