### ISSUE TITLE
Forgot password link goes to the wrong place

### ISSUE THREAD

**Issue by lharress** [PostHog/posthog#3773]
## Bug description

The forgot password link goes to the wrong location for self hosted.

## Expected behaviour

It should link to the forgot password page for the current domain.

## How to reproduce

1. Go to the login page of any self hosted Posthog instance
2. Click forgot password
3. Note the URL is now https://app.posthog.com/accounts/password_reset/

## Environment

- [ ] PostHog Cloud
- [x] self-hosted PostHog, version: 1.23.1

## Additional context

https://github.com/PostHog/posthog/blob/89b71a995909b2d6573df7b1521e53b3d1620909/frontend/src/scenes/authentication/Login.tsx#L95-L97

URL is hard coded.

**Comment by paolodamico** [comment]
Thanks for the detailed report @lharress, fix has been merged and should be included in the next release.

**Comment by lharress** [comment]
Thanks!
