### ISSUE TITLE
Improve the fresh installation experience on self-hosted (pre-onboarding)

### ISSUE THREAD

**Issue by paolodamico** [PostHog/posthog#3783]
Currently when a user fresh installs PostHog, their path is (preflight -> signup -> personalization/ingestion). The problem we have today is that the visuals on these pages don't play very well together (i.e. it doesn't feel like a consistent & progressive experience).

One small thing we could do is swap the signup's UI to the login's UI (sky & mountains) if on self-hosted, which seem to match better the rest of the flow, but the best thing to do would be to optimize the visuals considering the holistic flow. We definitely need to update the UI of preflight in any case.

### Hosted flow

**Preflight**
<img width="400" alt="" src="https://user-images.githubusercontent.com/5864173/112848022-7d639000-905c-11eb-8b25-6de65cf9db67.png">

**Sign up (2 steps)**
This is particularly the step that can introduce quite a bit of confusion. It just feels like you landed on a completely different place. Personally I also think the visuals don't support very strongly the notion of a self-hosted product tool.
<img width="400" alt="" src="https://user-images.githubusercontent.com/5864173/112847965-7177ce00-905c-11eb-83c5-0d7fd45ff942.png">
<img width="400" alt="" src="https://user-images.githubusercontent.com/5864173/112847973-73419180-905c-11eb-9bb1-a152eb66de7a.png">

**Personalization**
<img width="400" alt="" src="https://user-images.githubusercontent.com/5864173/112847908-645adf00-905c-11eb-9b97-8f48061b235d.png">

**Demo**
<img width="400" alt="" src="https://user-images.githubusercontent.com/5864173/112847899-615fee80-905c-11eb-9a25-b9a1a6c2e7ca.png">

### Cloud flow (for reference)

**Website**
<img width="400" alt="" src="https://user-images.githubusercontent.com/5864173/112847418-e991c400-905b-11eb-8231-a5e944d4d80c.png">

**Sign up (2 steps)**
<img width="400" alt="" src="https://user-images.githubusercontent.com/5864173/112847435-edbde180-905b-11eb-9eaa-abbabe632c9a.png">

**Personalization**
<img width="400" alt="" src="https://user-images.githubusercontent.com/5864173/112847908-645adf00-905c-11eb-9b97-8f48061b235d.png">

**Demo**
<img width="400" alt="" src="https://user-images.githubusercontent.com/5864173/112847899-615fee80-905c-11eb-9a25-b9a1a6c2e7ca.png">

**Comment by Twixes** [comment]
I think the signup page is pretty much fine as is UX-wise, but preflight and personalization stand out A LOT from the rest of PostHog because of how plain and unstructured they are (e.g. personalization takes up the whole width of the screen). So these parts will definitely need a rework.

**Comment by kappa90** [comment]
Closing as this is outdated.
