### ISSUE TITLE
Can not edit custom property in action

### ISSUE THREAD

**Issue by mariusandra** [PostHog/posthog#380]
**Describe the bug**
Can not change "custom event > event name" when editing an action.

**To Reproduce**
1. Create a new action with the type "custom event" and either select an event from the "event name" list or leave it empty
2. Edit the action and try to change the custom event.
3. You'll get a 500 error in the ajax call

**Expected behavior**
It should edit the action and save the new custom event type

**Screenshots**
![image](https://user-images.githubusercontent.com/53387/77008253-19e15580-6966-11ea-8c78-f9c77fecfc89.png)

**Desktop:**
macOS Catalina, Chrome 80

**Additional comments:**
Not related... but it would be cool if the list of last events would already show up when creating the new action... instead of only when editing an action. It would provide additional hints to ease creating the new action. Now I just create an empty action and then edit it with the event type that I see from the list of recent events.

**Comment by SanketDG** [comment]
I am trying to take this up and understand how to go about this, but I just can't seem to select from any custom events. I am right now using the docker setup and I am sending events through the demo app which is using the JS integration.

Am I missing something else?

**Comment by timgl** [comment]
Are you sending events using `posthog.capture('random event')`?
