### ISSUE TITLE
Include localhost:3000 as excluded URL by default

### ISSUE THREAD

**Issue by corywatilo** [PostHog/posthog#3800]
## Is your feature request related to a problem?

The default set of excluded URLs miss a common Rails URL: `localhost:3000`

![image](https://user-images.githubusercontent.com/154479/112968127-faa10a80-9119-11eb-9712-a595e9298a93.png)

## Describe the solution you'd like

- [ ] Include another default Rails URL: `localhost:3000`

**Comment by timgl** [comment]
Fixed by above PR
