### ISSUE TITLE
Calling identify straight after init blocked by CORS policy

### ISSUE THREAD

**Issue by adamb70** [PostHog/posthog#383]
On the first visit to a site, calling `posthog.init` immediately followed by `posthog.identify` from JS will result in the `identify` failing due do a CORS policy block.
```js
posthog.init('{{ posthog_settings.KEY }}', {api_host: '{{ posthog_settings.HOST }}'});
posthog.identify('{{ distinct_id }}');
```

![image](https://user-images.githubusercontent.com/11885987/77068579-c95a0e80-69de-11ea-9fc8-2ad20090638f.png)

Subsequent loads in the same session do not encounter this issue, only the first load. I assume it is something to do with the `init` call not fully completing the setup before `identify` is called, as using a small timeout will solve the issue (as will wrapping the whole thing in `$(document).ready()`).

```js
posthog.init('{{ posthog_settings.KEY }}', {api_host: '{{ posthog_settings.HOST }}'});
setTimeout(function () {
	posthog.identify('{{ distinct_id }}')
}, 500);
```

If this is due to some async call in `init` that is not finishing in time it would be great if we could pass a callback function to `init`, or perhaps it could fire an initComplete event, so we can call `identify` when safe.

**Comment by timgl** [comment]
@adamb70 Great find! I've pushed a fix for the race condition and documented how to call .identify within the callback [here](https://github.com/PostHog/posthog/wiki/JS-integration#identifying-users).

You should be able to do this to make it work:

```js
posthog.init('[your api key]', {
    api_host: 'https://posthog.[your-domain].com',
    loaded: function(posthog) { posthog.identify('[user unique id]'); }
});
```
