### ISSUE TITLE
ReplyError: MOVED when working with Elasticache for Redis

### ISSUE THREAD

**Issue by anandsourabh** [PostHog/posthog#3831]
Hi All,

I am trying to get my posthog setup going with AWS Elasticache for Redis.

This is my docker-compose file:

services:
web:
container_name: posthog_web
environment:
IS_DOCKER: 'true'
DATABASE_URL: postgres://user:password@host:port/db
REDIS_URL: rediss://:auth_token@clustercfg.<...>:6379?ssl_cert_reqs=none
SECRET_KEY: 7e12beebe6c46b3f23f46448d89741aa18012c5b9b673f0e2cb5f5bba0f17148
DISABLE_SECURE_SSL_REDIRECT: 'true'
SECURE_COOKIES: 'false'
DEBUG: 'true'
image: posthog/posthog:latest
ports:
- 8000:8000
- 80:8000
volumes:
postgres-data:
version: '3'

[MAIN] 🔒 Scheduler lock acquired!

[MAIN] ✅ Connected to Redis!

[MAIN] 🚀 All systems go.

**(node:54) UnhandledPromiseRejectionWarning: ReplyError: MOVED 2236 xxx-0001-001.xxx6379**
at parseError (/home/posthog/code/plugins/node_modules/redis-parser/lib/parser.js:179:12)
at parseType (/home/posthog/code/plugins/node_modules/redis-parser/lib/parser.js:302:14)

(Use `node --trace-warnings ...` to show where the warning was created)

(node:54) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)

(node:54) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

[___2] 🪗 Decompressed GeoLite2-City-2021-03-23.mmdb.br from 21.9 MB into 63.1 MB

**(node:54) UnhandledPromiseRejectionWarning: ReplyError: MOVED 2236 xxx-0001-001.xxx6379**
at parseError (/home/posthog/code/plugins/node_modules/redis-parser/lib/parser.js:179:12)
at parseType (/home/posthog/code/plugins/node_modules/redis-parser/lib/parser.js:302:14)
(node:54) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)

This keeps going in an infinite loop.

Could someone help with setting this going with AWS Elasticache? I understand that the MOVE error happens when you are trying to get a key that's served by other node in the cluster.

Thanks in Advance!

**Comment by paolodamico** [comment]
Hey @anandsourabh! Sorry that you're running into this issue, let us check internally and get back to you.

**Comment by Twixes** [comment]
Hello @anandsourabh! Looks like you opened discussion #3830 first, so I'll close this and we'll resolve the problem there.
