### ISSUE TITLE
Set IS_DOCKER to true by default in Docker image

### ISSUE THREAD

**Issue by gempain** [PostHog/posthog#3836]
## Is your feature request related to a problem?

Currently, when running Posthog with Docker, we have to set `IS_DOCKER` to `true` in the environment variables. Wouldn't it be possible to set this by default in the [Dockerfile](https://github.com/PostHog/posthog/blob/master/production.Dockerfile) ?

## Describe the solution you'd like

Update the production Dockerfile:

```
ENV IS_DOCKER "true"
```

**Comment by Twixes** [comment]
Hey @gempain! We've looked into this and noticed that `IS_DOCKER` isn't actually used anywhere, so we removed it altogether. :)

**Comment by gempain** [comment]
Aw, okay, that's good to know, thanks a lot !
