### ISSUE TITLE
Automatically capture web vitals

### ISSUE THREAD

**Issue by Tannergoods** [PostHog/posthog#384]
***Thank*** you for your feature request - we love each and every one :)

**Is your feature request related to a problem? Please describe.**
I can get the user event timestamps but there is no easy way to visualize the frontend latencies with that data.

**Describe the solution you'd like**
I would like to have user based latency so that we can track down the time taken to do particular set of actions in a funnel for each user and aggregate over all users. 

Examples of Front end latency can be 
- how long it took to do a http request
- how long it took for a user to complete a series of actions
- latency in loading/rendering a component itself (once a user has interacted)

**Describe alternatives you've considered**
With timestamps I could pull the data out, by user individually

**Comment by timgl** [comment]
I think we could very easily implement an event that uses web vitals to get a bunch of data that could be very useful https://web.dev/vitals/

**Comment by rmhulle** [comment]
A reference would be https://zizzamia.github.io/perfume/ they measure some of webvitals metrics and we can using it as https://vercel.com/docs/analytics do with they apps (it will be a great feature to put at posthog). 

Imagine to be able to understand not just what but how ours users are experiencing. 

At future maybe we'll be able to correlate FCP with a high dropoff of some specific feature. 

Make sense?

**Comment by paolodamico** [comment]
We're test driving this with the APM feature that @pauldambra is working on. As this has evolved elsewhere, closing this.

**Comment by Berhart** [comment]
Hi @paolodamico, any news on this feature?

**Comment by pauldambra** [comment]
We're working on the background to this at the moment

https://github.com/PostHog/posthog-js/pulls?q=is%3Apr+label%3Alisbon-web-performance+is%3Aclosed

and

https://github.com/PostHog/posthog/pulls?q=is%3Aopen+is%3Apr+label%3Alisbon-web-performance

Surfacing part of this information in session recordings is one of the goals for the recordings team in the first three months of 2023
