### ISSUE TITLE
Feature flags with neither rollout % nor filters say they match all users but match none

### ISSUE THREAD

**Issue by Twixes** [PostHog/posthog#3848]
## Bug description

This is what a default feature flag looks like:
<img width="577" alt="empty feature flag" src="https://user-images.githubusercontent.com/4550621/113333154-63f36a00-9322-11eb-8fb0-71b0cd865181.png">
It has no rollout percentage specified, nor filters, so it says "Rolling out to 100% of users". However I've experienced that in fact in this situation the flag is rolled out to *nobody*.

CC @paolodamico 

## Expected behavior

Flag should work the way it says.

## How to reproduce

1. Create a feature flag and leave it as is, supposedly completely rolled out.
2. Try to use it.
3. Discover that the flag is not rolled out.

## Environment

- [x] PostHog Cloud
- [x] self-hosted PostHog, version/commit: master (8f4ae2b)

**Comment by paolodamico** [comment]
Yes, noticed this a few days ago and there's already a PR out for this #3745. Need to make some adjustments before merging.
