### ISSUE TITLE
Path is no longer rendering graph

### ISSUE THREAD

**Issue by mrsweaters** [PostHog/posthog#385]
**Describe the bug**
Path is no longer rendering:
<img width="1438" alt="Screen Shot 2020-03-19 at 2 40 15 PM" src="https://user-images.githubusercontent.com/535897/77117689-c4ea2180-69ef-11ea-8fdd-cca61a40781f.png">

Using Chrome 80.

**Comment by timgl** [comment]
Hm I'm struggling to reproduce this. I think the charAt error might be unrelated. Could you take a screenshot of the network request (specifically the preview)? Thanks!

**Comment by mrsweaters** [comment]
Sorry for the delay!

<img width="1440" alt="Screen Shot 2020-03-26 at 10 00 11 AM" src="https://user-images.githubusercontent.com/535897/77674349-ada7b880-6f48-11ea-939d-eaf8cb8728dd.png">

**Comment by timgl** [comment]
@mrsweaters Managed to completely miss this. We've changed a lot about how we load the Paths in the newer version so I think it should be fixed. Let me know if not!
