### ISSUE TITLE
Redirect for authenticated users is not smooth

### ISSUE THREAD

**Issue by yakkomajuri** [PostHog/posthog#3868]
## Bug description

Going to app.posthog.com gives me the login screen for a significant amount of time before taking me over to `/insights`:

https://user-images.githubusercontent.com/38760734/113567105-7d840280-95fd-11eb-9327-6e07db45c985.mov

## Expected behavior

A lot less flashing, either with better routing, or by adding a loader while we make a decision.

## How to reproduce

1. Go to app.posthog.com
2. Watch it flicker
3.

## Environment

This happens on Cloud, but locally I get a different type of flicker: large logo on white page before scene render. 

- [x] PostHog Cloud
- [ ] self-hosted PostHog, version/commit: _please provide_

**Comment by mariusandra** [comment]
I think https://github.com/PostHog/posthog/pull/3874 fixed it.

**Comment by yakkomajuri** [comment]
Still a thing

**Comment by mariusandra** [comment]
Still not fixed, at least I can reproduce on app...
