### ISSUE TITLE
Funnel conversion rate appears to change, even after the window has closed.

### ISSUE THREAD

**Issue by kpthatsme** [PostHog/posthog#3877]
## Bug description

This morning (Apr 5 21) I ran [this chart ](https://app.posthog.com/insights?insight=FUNNELS&target_entity=%7B%22id%22%3A4912%2C%22math%22%3Anull%2C%22name%22%3Anull%2C%22type%22%3A%22actions%22%2C%22order%22%3Anull%2C%22properties%22%3A%5B%5D%2C%22math_property%22%3Anull%7D&returning_entity=%7B%22id%22%3A5043%2C%22math%22%3Anull%2C%22name%22%3Anull%2C%22type%22%3A%22actions%22%2C%22order%22%3Anull%2C%22properties%22%3A%5B%5D%2C%22math_property%22%3Anull%7D&period=Week&retention_type=retention_first_time&display=ActionsLineGraph&properties=%5B%7B%22key%22%3A%22id%22%2C%22type%22%3A%22cohort%22%2C%22value%22%3A71%2C%22operator%22%3Anull%7D%5D&events=%5B%7B%22id%22%3A%22user%20signed%20up%22%2C%22math%22%3Anull%2C%22name%22%3A%22user%20signed%20up%22%2C%22type%22%3A%22events%22%2C%22order%22%3A0%2C%22properties%22%3A%5B%7B%22key%22%3A%22is_organization_first_user%22%2C%22type%22%3A%22event%22%2C%22value%22%3A%5B%22true%22%5D%2C%22operator%22%3A%22exact%22%7D%5D%2C%22math_property%22%3Anull%7D%2C%7B%22id%22%3A%22first%20team%20event%20ingested%22%2C%22math%22%3Anull%2C%22name%22%3A%22first%20team%20event%20ingested%22%2C%22type%22%3A%22events%22%2C%22order%22%3A1%2C%22properties%22%3A%5B%5D%2C%22math_property%22%3Anull%7D%5D&actions=%5B%7B%22id%22%3A4912%2C%22math%22%3Anull%2C%22name%22%3A%22Discover%20Learning%20-%20core%20analytics%22%2C%22type%22%3A%22actions%22%2C%22order%22%3A2%2C%22properties%22%3A%5B%5D%2C%22math_property%22%3Anull%7D%5D&interval=week&date_from=-90d). 

I saw a value of 11% this morning for the week of Mar 28. 

I reran this query and the value has dropped to 10%. I'm confused to how the conversion rate for week of Mar 28 is able to change given today is April 5th. I believe I've seen this happen with a funnel before. It could be I'm missing something with how we resolve weeks.

## Expected behavior

- When looking at a weekly trends funnel, I'd expect dates in a completed week to have stable conversion rates.

## How to reproduce
1. Run a funnel trends chart, observe value of completed week
2. Rerun the query, observe an updated value for the data point, even though the week was completed
3.
It's a bit tricky since the data stays at the new value once calculated. I also don't know how to repro consistently since it's unclear to me which sets of data is correct (since we can't see the users at each step).
## Environment

- [ ] PostHog Cloud
- [ ] self-hosted PostHog, version/commit: _please provide_

## Additional context

It could just be misinterpreting the UX and somehow the week of Mar 28 isn't completed.

**Comment by paolodamico** [comment]
Seems strongly related to https://github.com/PostHog/product-internal/issues/10

**Comment by EDsCODE** [comment]
I'm guessing it is same underlying issue with queries dependent on cohort. Maybe it's time to add some sort of notice on queries that might change due to cohort recalculation?

**Comment by paolodamico** [comment]
Not 100% sure this is the problem, but if this is it one thing we could do is when showing when a graph was last refreshed, we also take into account when all the cohorts were last refreshed, and show the oldest data from all. We could also automatically trigger a cohort refresh when you click on refresh.

**Comment by kpthatsme** [comment]
Hey @paolodamico I was thinking about this some more, and I think one thing that could help as well is defining a 'conversion window' for funnels. 

This would be a range of time (hours, days, months, weeks) you define when creating your chart, and what it does is say for someone to get through this funnel, they need to go from event A onwards within the conversion window. 

So for example, if we have a weekly funnel with a 7 day conversion window, the last data point isn't 'complete' until 7 days after it entered into the funnel. 

I think that could partially be what's going on here, I feel like we have a bit of a lagging trend to discovering learnings and I wonder if some data points are incomplete even though the overall time window is marked solid. For instance, on May 9, the week of May 2 looks 'complete' but if we had a 5 day conversion window, the week of May 2 wouldn't actually be complete until May 8 + 5 days.

Let me know if you'd prefer I make a separate ticket re: conversion windows instead!
