### ISSUE TITLE
Attempting to insert duplicate person distinct ID records

### ISSUE THREAD

**Issue by paolodamico** [PostHog/posthog#3878]
## Bug description

As originally reported in #3819, a couple of users are seeing this type of errors in their logs, where we try to add insert a person distinct ID record for an ID that already exists instead of using the existing record.

## Expected behavior

If the distinct ID record exists, we should be using the existing record, instead of attempting to insert a new one.

```
ERROR:  duplicate key value violates unique constraint "unique distinct_id for team"
DETAIL:  Key (team_id, distinct_id)=(1, kv1181606272094249) already exists.
STATEMENT:  INSERT INTO posthog_persondistinctid (distinct_id, person_id, team_id) VALUES ($1, $2, $3) RETURNING *
```

## How to reproduce

1. Check the logs for this error?

## Environment

- [ ] PostHog Cloud. **Unverified**
- [X] self-hosted PostHog, version/commit: 1.23.1

**Comment by paolodamico** [comment]
Another user reported this issue but with a different table (see details below). Interestingly, this also came up from a user reporting the same error of PostHog completely freezing and not loading anything until restarted.

```
2021-04-08 06:29:35.614 UTC 146 ERROR: duplicate key value violates unique constraint "unique hash for each team"
2021-04-08 06:29:35.614 UTC 146 DETAIL: Key (team_id, hash)=(1, 4ba1xxxxxxxxx) already exists.
2021-04-08 06:29:35.614 UTC 146 STATEMENT: INSERT INTO posthog_elementgroup (hash, team_id) VALUES ($1, $2) RETURNING *
```

**Comment by VengefulAncient** [comment]
This is happening for us as well. Exactly the same error as the previous comment.

**Comment by timgl** [comment]
I think this error is safe to ignore. The reason we do this is it only takes 1 query to insert an elementgroup instead of 2 (checking to see if it exists, if not then create it). It likely isn't the reason for any other issues.

**Comment by VengefulAncient** [comment]
This might be an edge case but it would be great if this error wasn't spammed in the logs if it's really safe: on GCP, there's a monthly 50 GB free quota for all logs, and each deployment/database writing repeating logs depletes that quota.

Not to mention that it makes spotting actual errors in PG logs much harder. We just had to troubleshoot another Posthog issue and for every query with the actual error, there were ~10-20 queries with this one.
