### ISSUE TITLE
Adjust axes size on graphs that don't use the full range

### ISSUE THREAD

**Issue by jamesefhawkins** [PostHog/posthog#3882]
## Is your feature request related to a problem?

<img width="679" alt="Screenshot 2021-04-06 at 09 19 46" src="https://user-images.githubusercontent.com/47497682/113680912-4a06ae00-96b9-11eb-82a7-ae65a21e6f4f.png">

Graphs like the above are hard to read. I have to hover over each data point to see the conversion rates over time, since there's so much unused space on the graph.

I suspect this will mainly affect conversion rates over time graphs, since these will often have a low percentage out of 100, alas.

## Describe the solution you'd like

The y-axis to adjust to a range closer to the actual range in use by the graph so I can read it more easily.

## Describe alternatives you've considered

Hover over the data points one at a time

**Comment by kpthatsme** [comment]
Addressed in https://github.com/PostHog/posthog/pull/3940
