### ISSUE TITLE
Contributor PRs fail due to cypress

### ISSUE THREAD

**Issue by macobo** [PostHog/posthog#3891]
## Bug description

Some contributor PRs fail due to cypress tests: https://github.com/PostHog/posthog/runs/2286150473

Based on the screenshot, the test database might not be seeded correctly?

This needs a bit of digging to solve.

**Comment by samwinslow** [comment]
I was experiencing the same error `401: Authentication credentials were not provided` on various tests, and I agree the test DB is possibly not seeded correctly.

Also seeing the following. It doesn't happen with every 401 we're seeing in the logs, and some requests to `/decide` are successful. However, missing or misconfigured credentials might have caused it too.
- Request to `/decide` fails
- `TypeError: Cannot read property 'map' of undefined at loadResultsSuccess`

`frontend/src/scenes/trends/trendsLogic.ts:420` seems to be the culprit for the .map error; looks like `loadResultsSuccess` is called even after API call failure. That whole file could be typed better, which I can work on even if it won't resolve all of this.

**Comment by Twixes** [comment]
Resolved the main problem with #3892. As for these errors @samwinslow, they are definitely kind of bad too. Though they don't seem to break crucial functionality. Feel free to open a separate issue around them.
