### ISSUE TITLE
Release 1.25.0 1/2

### ISSUE THREAD

**Issue by timgl** [PostHog/posthog#3895]
Team extensibility
- Map out integrations (what features does each have, which ones need effort?)
- Metrics
- Plugin logs
- export plugins + retrying

Team deployments & infrastructure
- AWS marketplace/VPC PostHog/vpc#28 & Google Marketplace, existing customers
- Stabilize helm charts
- SOC2

Core experience
-  UX improvement (Suggestions but not strict below)
- App Comprehensiveness

Support hero:
Paolo/Tim

**Comment by mariusandra** [comment]
### Team Extensibility

Yakko: 
- Chart our integrations.
- Figure out metrics
- Dive into the plugin server code

Michael: 
- Console.log and errors
- Remove Python ingestion code, add a Celery listener for the old queue into plugin server
- Introducing plugins during onboarding flow #3764

Marius:
- Standard library/contrib code @posthog/plugin-contrib 
- S3 and Snowflake exports, finally
- Retrying exports

**Comment by macobo** [comment]
## Team Deployments&Infrastructure

Notes from yesterday

Priorities:
- AWS marketplace/VPC https://github.com/PostHog/vpc/issues/28 & Google Marketplace, existing customers
- Stabilize helm charts
- Plan for moving postgres/Kafka over to AWS

Karl
- Continue with AWS marketplace work https://github.com/PostHog/vpc/issues/28
- Support existing deployments ad needed

James
- Support Karl
- Stabilize helm charts
- SOC2 compliance
- Work with Google to get marketplace access
- Plan for moving postgres/Kafka over to AWS

**Comment by EDsCODE** [comment]
**Core Analytics**

**Key area: UX improvement (Suggestions but not strict below)**
- [Filter experience](https://github.com/PostHog/posthog/issues/2760) - our filters are cluttered now with all the different options we provide 
- Rethink how we introduce users to insights the first time they come to the page. Currently we’re onboarding users and walking them through ingestion but they’re on their own with queries
- Tooltips and explanations are very adhoc. Maybe there’s a unified way to provide information on these graphs?
- Some analysis can be done on various features (such as the history button) to understand if users are using them and add experiments to enhance usage if needed

**Key area: App Comprehensiveness - functionality that can be added to give a more complete experience**
- Continue Interconnected list on [ticket](https://github.com/PostHog/posthog/issues/3765) (this is pretty hefty and good to focus on)
- Focus/Edit page when you click into an insight that’s saved on dashboard as described in this [thread](https://github.com/PostHog/posthog/issues/3551). This will be foundation for further sharing functionality

**Persistent focus: Maintain data quality
