### ISSUE TITLE
Breakdown not working, seemingly when test filter is applied

### ISSUE THREAD

**Issue by kpthatsme** [PostHog/posthog#3897]
## Bug description
Breakdown seems to not working properly when the test filter switch is toggled on.

## Expected behavior

Expect breakdown by realm to work since the filter @ event level works. Also it seems to work if test users are not excluded.

## How to reproduce

1. Go to this [chart](https://app.posthog.com/insights?insight=TRENDS&display=ActionsLineGraph&actions=%5B%7B%22id%22%3A4912%2C%22name%22%3A%22Discovered%20Learning%22%2C%22type%22%3A%22actions%22%2C%22order%22%3A0%2C%22math%22%3A%22dau%22%7D%5D&events=%5B%5D&filter_test_accounts=true&new_entity=%5B%5D&breakdown=false&breakdown_type&date_from=-30d&interval=week&properties=%5B%7B%22key%22%3A%22realm%22%2C%22value%22%3A%5B%22cloud%22%2C%22hosted%22%5D%2C%22operator%22%3A%22exact%22%2C%22type%22%3A%22person%22%7D%5D) – observe the filter by realm on the events.

2. Go to the same chart, with a [breakdown instead](https://app.posthog.com/insights?insight=TRENDS&display=ActionsLineGraph&actions=%5B%7B%22id%22%3A4912%2C%22name%22%3A%22Discovered%20Learning%22%2C%22type%22%3A%22actions%22%2C%22order%22%3A0%2C%22math%22%3A%22dau%22%7D%5D&events=%5B%5D&filter_test_accounts=true&new_entity=%5B%5D&breakdown=realm&breakdown_type=person&date_from=-30d&interval=week&properties=%5B%5D) -- Observe no data

3. [Disable the test filter, apply the breakdown](https://app.posthog.com/insights?insight=TRENDS&display=ActionsLineGraph&actions=%5B%7B%22id%22%3A4912%2C%22name%22%3A%22Discovered%20Learning%22%2C%22type%22%3A%22actions%22%2C%22order%22%3A0%2C%22math%22%3A%22dau%22%7D%5D&events=%5B%5D&filter_test_accounts=false&new_entity=%5B%5D&breakdown=realm&breakdown_type=person&date_from=-30d&interval=week&properties=%5B%5D) - data seen 
## Environment

- [ ] PostHog Cloud
- [ ] self-hosted PostHog, version/commit: _please provide_

**Comment by samwinslow** [comment]
My recent changes to test user exclusions might have caused this. I'll dig deeper and possibly create new tests for this.

**Comment by kpthatsme** [comment]
Thanks @samwinslow  – when you're digging, @EDsCODE may be a good person to sync up w/ on this (he was the one who pointed out the test filter piece).

**Comment by samwinslow** [comment]
Hey @kpthatsme — so it looks like the query fails when breaking down by `realm` on the User properties, as in your example, but `realm` on Event properties indeed works. (It shows no data until April 4.)

Breakdowns + test users filter together also add a lot of latency. Breaking down this same query by OS took around 15 seconds to compute, but did eventually work.

The payload returned from the request to `/api/insight/trend/?insight=TRENDS&...` looks like `{"result":[],"next":null}` in the failure case. Is this the typical response when there truly is no data available, or does it indicate a problem?

I will see if I can reproduce locally and inspect what the Django queryset or even the underlying Postgres query looks like.

**Comment by kpthatsme** [comment]
@samwinslow thanks for looking into this–

So I tried taking the same chart but applying the filter on each event. So for each event, I added the filter on user property `realm.` [Chart here](https://app.posthog.com/insights?insight=TRENDS&interval=day&display=ActionsLineGraph&actions=%5B%5D&events=%5B%7B%22id%22%3A%22insight%20viewed%22%2C%22name%22%3A%22insight%20viewed%22%2C%22type%22%3A%22events%22%2C%22order%22%3A0%2C%22math%22%3A%22dau%22%2C%22properties%22%3A%5B%7B%22key%22%3A%22realm%22%2C%22value%22%3A%5B%22cloud%22%5D%2C%22operator%22%3A%22exact%22%2C%22type%22%3A%22person%22%7D%5D%7D%2C%7B%22id%22%3A%22insight%20viewed%22%2C%22name%22%3A%22insight%20viewed%22%2C%22type%22%3A%22events%22%2C%22order%22%3A1%2C%22math%22%3A%22dau%22%2C%22properties%22%3A%5B%7B%22key%22%3A%22realm%22%2C%22value%22%3A%5B%22hosted%22%5D%2C%22operator%22%3A%22exact%22%2C%22type%22%3A%22person%22%7D%5D%7D%5D&properties=%5B%5D&filter_test_accounts=true&new_entity=%5B%5D&breakdown=false&breakdown_type) – We see data here, which is what we expect.


Now instead of doing the filters on the events, if we do breakdown using the same, realm user property, we get [no data](https://app.posthog.com/insights?insight=TRENDS&interval=day&display=ActionsLineGraph&actions=%5B%5D&events=%5B%7B%22id%22%3A%22insight%20viewed%22%2C%22name%22%3A%22insight%20viewed%22%2C%22type%22%3A%22events%22%2C%22order%22%3A0%2C%22math%22%3A%22dau%22%2C%22properties%22%3A%5B%5D%7D%2C%7B%22id%22%3A%22insight%20viewed%22%2C%22name%22%3A%22insight%20viewed%22%2C%22type%22%3A%22events%22%2C%22order%22%3A1%2C%22math%22%3A%22dau%22%2C%22properties%22%3A%5B%5D%7D%5D&properties=%5B%5D&filter_test_accounts=true&new_entity=%5B%5D&breakdown=realm&breakdown_type=person).

Without looking at the code, it seems like maybe there's an issue with how breakdown is applying user properties versus filters?

**Comment by samwinslow** [comment]
This seems like a non-frontend and not very urgent issue so I'll unassign myself in order to direct attention elsewhere during this sprint, but happy to revisit later.

**Comment by EDsCODE** [comment]
I made some adjustments to the breakdown query [here](https://github.com/PostHog/posthog/pull/4313) and it looks like the [query works](https://app.posthog.com/insights?insight=TRENDS&display=ActionsLineGraph&actions=%5B%7B%22id%22%3A4912%2C%22name%22%3A%22Discovered%20Learning%22%2C%22type%22%3A%22actions%22%2C%22order%22%3A0%2C%22math%22%3A%22dau%22%7D%5D&events=%5B%5D&filter_test_accounts=true&new_entity=%5B%5D&breakdown=realm&breakdown_type=event&interval=week&properties=%5B%5D&date_from=-14d) Important to note is that I think you were breaking down by user property-realm whereas the event property-realm is more accurate and has data.

There is some sort of issue with the weekly interval roudning because the first interval is always 0 but I'll address this separately
