### ISSUE TITLE
Have ability to add a predicate before unique count on insight

### ISSUE THREAD

**Issue by fuziontech** [PostHog/posthog#3898]
## Is your feature request related to a problem?

Only a business problem.

## Describe the solution you'd like

It would be nice to to able to set a predicate or filter before we do a unique count on insights.

Something along the lines of give me a unique count of users by day that had over 10 event A's that day.

## Describe alternatives you've considered

There is no real alternative as far as I can tell.

**Comment by macobo** [comment]
Related: https://github.com/PostHog/posthog/issues/2594
