### ISSUE TITLE
Show events right away as they stream in

### ISSUE THREAD

**Issue by jeduden** [PostHog/posthog#3899]
## Is your feature request related to a problem?

As a developer, when I test the analytics integration, I have two screens : the app on one screen and the posthog events page on another. In order to check the events after an interaction with the app, I first need to go the screen and click "load new events".

## Describe the solution you'd like

Have a switch to display events right away when they come in. It would be good if the filters are still applied so that the stream is not noisy.

## Describe alternatives you've considered

Manually, clicking ;)

#### *Thank you* for your feature request – we love each and every one!

**Comment by yakkomajuri** [comment]
@posthog-bot please add @jeduden for ideas

**Comment by mariusandra** [comment]
This is now closed with #6033
