### ISSUE TITLE
Get rid of $pageview, $pageleave etc

### ISSUE THREAD

**Issue by timgl** [PostHog/posthog#3901]
## Is your feature request related to a problem?

There's a couple of instances where we show `$pageview` instead of `Pageview`. If you're a developer this looks absolutely fine, but if you're not this is confusing.

## Describe the solution you'd like

Replace all instances (in the frontend) of $pageview, $pageleave, $autocapture, $feature_flag_called with `(posthog logo) Pageview`, in the same way we've done in PropertyKeyInfo.tsx.

**Comment by liyiy** [comment]
Are we replacing all instances where the value is prefixed with the `$`? 

examples not on the list: `$rageclick`, `$identify`

**Comment by EDsCODE** [comment]
$ prefix should be standard events we emit so I think it's safe to change all of the ones with $ that we have to something with posthog logo + label
