### ISSUE TITLE
Add a dropdown to event property filter

### ISSUE THREAD

**Issue by Tannergoods** [PostHog/posthog#391]
***Thank*** you for your feature request - we love each and every one :)

**Is your feature request related to a problem? Please describe.**
When filtering by event property, it is not clear that I can select from a dropdown menu after selecting the the first filter (i.e.  browser, utm tag, device etc). This can lead to a user trying to type the expected filter but get no results if they have a typo or not use the correct case (upper or lower)

**Describe the solution you'd like**
A small arrow denoting the drop down that is already there.

**Describe alternatives you've considered**
None

**Additional context**
<img width="756" alt="Posthog" src="https://user-images.githubusercontent.com/60791437/77165317-f0314700-6aa9-11ea-8376-efccbe3b22bd.png">

<img width="187" alt="Posthog" src="https://user-images.githubusercontent.com/60791437/77165335-fb847280-6aa9-11ea-91f4-75b63c7c486d.png">

<img width="341" alt="Posthog" src="https://user-images.githubusercontent.com/60791437/77165410-1eaf2200-6aaa-11ea-9961-1dcc0afd4846.png">
=

From this video submitted below
https://www.loom.com/share/2e07357fadc54b70bdc39287734a00dd

**Comment by toolmantim** [comment]
❤️
