### ISSUE TITLE
Disambiguate event and user properties that have same name

### ISSUE THREAD

**Issue by samwinslow** [PostHog/posthog#3934]
## Is your feature request related to a problem?

As a new user of PostHog I found it confusing that property names are sometimes shared between Events and Users. `realm`, for instance, appears on both. In the below screenshot, the user has no way of knowing whether `Events.realm` or `Users.realm` is the active one, which is important because the data is different.

<img width="748" alt="Screen Shot 2021-04-09 at 7 33 01 AM" src="https://user-images.githubusercontent.com/4645779/114174202-4ae04f80-9906-11eb-925f-6d9bdaa3bb86.png">

Also, the fact that a property like `is_first_user`, or `firstName`, exists on Event is really confusing. What would the significance of `firstName` on Event be?

## Describe the solution you'd like

1. Close look at whether any duplicate properties can be deleted from Cloud.
2. Grouping property values by subject area; I think Google Analytics does a great job of this (see below)

<img width="411" alt="Screen Shot 2021-04-09 at 7 40 44 AM" src="https://user-images.githubusercontent.com/4645779/114174784-1faa3000-9907-11eb-9d0e-89a4befbd3f2.png">

## Describe alternatives you've considered

- On the blue filter button, add some extra text if the property name happens to occur on both Event and Users. In the original screenshot that button might say `event:realm`. This would be faster to implement but doesn't address the overall information architecture problem.

## Additional context

- Issue #3897 is about query failure on Breakdowns; reproducing the error was confusing because of the duplicate name `realm`.
- Overall goal of core experience to improve property filters UX – @EDsCODE @timgl feel free to weigh in on this proposed solution or present another

**Comment by paolodamico** [comment]
Great stuff @samwinslow! I think it's worth a deeper look in this or next release's cycle. Let me know if you want to brainstorm potential solutions together.

**Comment by samwinslow** [comment]
Using the `SelectBox` component for property names essentially resolved this issue for the main filtering experience, which is still in feature-flagged testing.

We may want to transition Breakdowns to use the new filter UI components, but that should become a separate issue when it happens.
