### ISSUE TITLE
Autofocus property dropdown and value field on "Add filter"

### ISSUE THREAD

**Issue by samwinslow** [PostHog/posthog#3936]
## Is your feature request related to a problem?

Unclear behavior wrt. filters.

## Describe the solution you'd like

Clicking "Add filters" should open the first dropdown. We can eliminate a click by automatically opening the `Property` select:

![image](https://user-images.githubusercontent.com/4645779/114229342-b1d12900-9945-11eb-8fd1-63dea0a1aeff.png)

Automatically show typeahead dropdown (when possible) for fields with values:

![image](https://user-images.githubusercontent.com/4645779/114229479-e3e28b00-9945-11eb-84c7-9b6785da5744.png)
The value field is autofocused, but the dropdown is not activated until the user clicks. It should be activated without needing to click on the field.

## Additional context

From @corywatilo's [Notion doc](https://www.notion.so/PostHog-app-feedback-da8e96b246a04baf99dc864194977b15).

**Comment by paolodamico** [comment]
This could be a good example of PRs over issues ? 🤔
