### ISSUE TITLE
Minor: some property values incorrectly indicated as "parsable as datetime"

### ISSUE THREAD

**Issue by samwinslow** [PostHog/posthog#3937]
## Bug description

The calendar icon and field type == "string parsable as datetime" appears for some properties where it doesn't quite make sense, e.g. hostnames. The inconsistency of seeing a calendar icon next to somethings that's obviously a string is weird.

Perhaps being parsable as datetime is based on the fact that these values include the `:` character?

*If this affects the front-end, screenshots would be of great help.* 

<img width="603" alt="Screen Shot 2021-04-09 at 3 18 03 PM" src="https://user-images.githubusercontent.com/4645779/114230611-5bfd8080-9947-11eb-924e-8e86883232ce.png">
<img width="566" alt="Screen Shot 2021-04-09 at 3 18 19 PM" src="https://user-images.githubusercontent.com/4645779/114230621-5e5fda80-9947-11eb-89f4-64b24be0de34.png">

## Expected behavior

Smarter detection of datetimes.

## How to reproduce

1. Open Events
2. Expand the properties of any given row

## Environment

- [ ] PostHog Cloud
- [ ] self-hosted PostHog, version/commit: _please provide_

**Comment by Twixes** [comment]
Agreed, Day.js (and Moment.js before it as well, they're very similar in this regard) parses so loosely that this is often just confusing. Made #3942 to remove this parsing.
