### ISSUE TITLE
Ingested properties not url decoded

### ISSUE THREAD

**Issue by joesaunderson** [PostHog/posthog#3966]
## Bug description

When using the identify API in `posthog-js`, we are passing some data which could cause malformed URL's i.e. "Men's Fashion". 

If I do not URL encode this, it shows in Posthog as `Men&#039;s Fashion`, if I do URL encode this, it shows in Posthog as `Men%27s%20Fashion`.

## Expected behavior

If the property is URL encoded, I expect this to be decoded on receipt by Posthog.

## How to reproduce

1. Send an identify request similar to below:

```js
const data = {};
data.attributeNonEncoded = "Men's Fashion";
data.attributeEncoded = encodeUri("Men's Fashion");

posthog.identify('user-id', data);
```

2. View the captured data in Posthog

## Environment

- [ ] PostHog Cloud
- [x] self-hosted PostHog, 1.23.1

## Additional context

Not sure if this is actually a bug? Or is this something we are supposed to build plugins for? Either way, it would be good to get some guidance!

**Comment by yakkomajuri** [comment]
Seems like a matter of handling special characters in the relevant places in the UI. This is also seen in shared dashboards, although not on in-product dashboards.

**Comment by mariusandra** [comment]
Hey, where in PostHog does it show? I just tried it myself locally and this is what I see:

![image](https://user-images.githubusercontent.com/53387/114674997-13a7df00-9d08-11eb-8eb9-07520fc74410.png)

... so the data is at least stored correctly, and shown correctly in the user properties box.

**Comment by joesaunderson** [comment]
> Hey, where in PostHog does it show? I just tried it myself locally and this is what I see:
> 
> IMAGE
>
> ... so the data is at least stored correctly, and shown correctly in the user properties box.

Hmm that is odd, I have tried locally too, using the JS console and it works as you suggest. 

I think this might be a side effect of our templating library (Twig 😞) - let me investigate this further!

**Comment by joesaunderson** [comment]
Ah yes, @mariusandra, this is the issue. We use Twig as our templating language and it is doing the escaping for us.

```twig
data.merchantCategoryName = '{{ merchant.category.name }}';
```

Becomes `data.merchantCategoryName = 'Men&#039;s Fashion';`

This is to stop the `'` breaking out of the JS single quotes. Is there a way in PostHog (maybe via a plugin) we can decode all the properties that are passed in?

**Comment by mariusandra** [comment]
You can always write your own wrapper around `posthog.idenfity` that does something like:

```js
function posthogIdentify(user, props = {}) {
    posthog.identify(user, Object.fromEntries(Object.entries(props).map(([key, value]) => [key, decodeURI(value)]))
}
```

There's not really a place in the PostHog JS library you can hook into to do this directly.
