### ISSUE TITLE
Scroll bar on session table

### ISSUE THREAD

**Issue by macobo** [PostHog/posthog#3967]
## Bug description

![image](https://user-images.githubusercontent.com/148820/114536670-fa485980-9c59-11eb-8d62-64e88dffc4e9.png)

## Expected behavior

No scroll bar on linux

## How to reproduce

1. Use linux
2. Go to sessions
3. See scrollbar

## Environment

- [ ] PostHog Cloud
- [ ] self-hosted PostHog, version/commit: _please provide_

## Additional context

Probably added by the resizable table change @samwinslow ?

**Comment by mariusandra** [comment]
If it helps, it's also there on a mac if you use an external mouse
![image](https://user-images.githubusercontent.com/53387/114675686-d1cb6880-9d08-11eb-9462-9c969214e8e5.png)

... or just make scrollbars always visible from settings. 

I've run into this many times. Usually switching from `overflow: scroll` to `overflow: auto` in the right place fixes it.

**Comment by samwinslow** [comment]
Thank you @Twixes. Total non-sequitur, but if you're curious: I did have some fun installing a Ubuntu virtual machine last night.

Getting the static assets to serve properly from the host to the guest (without tying up a port on the host) was a slight challenge - ended up forwarding `127.0.0.1:5432` to `10.0.2.2:5432` with `xinetd` on the guest machine.

The advantage of this was that zero project-level config was required on the host machine and I could compare both side-by-side. Leaving this here in case it is helpful in the future!
 
<img width="1392" alt="Screen Shot 2021-04-14 at 8 54 25 PM" src="https://user-images.githubusercontent.com/4645779/114798680-e557ed00-9d63-11eb-953d-78728a9f184c.png">
