### ISSUE TITLE
Permissioning 

### ISSUE THREAD

**Issue by Tannergoods** [PostHog/posthog#398]
***Thank*** you for your feature request - we love each and every one :)

**Is your feature request related to a problem? Please describe.**
If I have multiple users in an organization I would like to control what they have access to (for example what they could view from a GDPR perspective) 

**Describe the solution you'd like**
Either an ACLs or RBAC system that would give an "administrator" the ability to control PostHog access for an organization.

**Describe alternatives you've considered**
Separate instances potentially

**Additional context**

**Comment by jamesefhawkins** [comment]
This is helpful but should go in non MIT version as it’s one of the key paid features

**Comment by yakkomajuri** [comment]
We do have permissioning now, even if it doesn't allow view-based restrictions yet. Nevertheless, there are other discussions around this
