### ISSUE TITLE
In projects with no events yet, there's awkwardly nothing at all in place of the Insights graph

### ISSUE THREAD

**Issue by Twixes** [PostHog/posthog#3981]
## Bug description

If a project doesn't have events yet, the graph in Insights is simply not rendered, and there's nothing in its place.

![insights](https://user-images.githubusercontent.com/4550621/114721551-51712b80-9d39-11eb-87f0-608b8b47b40c.png)

## Expected behavior

There should be an explanation of the situation or at least something that looks more elegant.

## How to reproduce

1. Open up a PostHog project with no events.
2. Go to Insights.
3. Notice that there's nothing in place of the graph.

## Environment

- [x] PostHog Cloud
- [x] self-hosted PostHog, version 1.24.0

**Comment by mariusandra** [comment]
Could that be related to https://github.com/PostHog/posthog/pull/3866 ? I stumbled upon something very similar. If I opened the app with the insights page open, all would work. If I opened some other page and then clicked to insights, it wouldn't set the default filter ($pageview). I thought it got fixed though 🤔

**Comment by paolodamico** [comment]
For context, I think the problem here is that because the project has no events, it therefore has no event names to set as default. Will definitely take a look soon.

**Comment by Twixes** [comment]
Fixed.
