### ISSUE TITLE
Broken requests to /sessionRecording

### ISSUE THREAD

**Issue by avorio** [PostHog/posthog#3986]
I'm seeing a ton of broken requests to `/sessionRecording` in my app's logs. Those requests are being placed by PostHog for no apparent reason to me. And because that route is not known to the app, it returns a 404 and ends up polluting our logs.

Any reason for these requests? How could we disable them?

I'm running version 1.23.1.

**Comment by paolodamico** [comment]
Hey @avorio, thanks for the issue! This has actually been reported a few times, but we can't seem to find the culprit. Would you mind sharing the payload information from the request and response to the `/decide` endpoint? (triggered when posthog-js is loaded). Also, can you share details of the `/sessionRecording` request? (payload, destination URL [I believe I've seen it not actually go to PostHog's server, but your own server], ...)

**Comment by avorio** [comment]
All I can see at this point is a `POST` request to `sessionRecording` relative to the current URL, e.g.:

```
"POST /my/app/route/sessionRecording?compression=gzip-js&ip=1&_=1234... HTTP/1.0"
```

**Comment by paolodamico** [comment]
Actually closing this in favor of https://github.com/PostHog/posthog-js/issues/183 (duplicated)
