### ISSUE TITLE
Error when upgrading to 1.24.0 on Heroku

### ISSUE THREAD

**Issue by avorio** [PostHog/posthog#3987]
I'm trying to upgrade to 1.24.0 on Heroku but I'm getting the following error:

```
Requested runtime (python-3.8.6) is not available for this stack (heroku-20).
```

We are using Tim's Python buildpack:

https://github.com/timgl/heroku-buildpack-python

... but it looks to be way behind Heroku's own Python buildpack.

Is there a reason for that custom buildpack, or could I safely replace it with Heroku's own?

Ah! I've just triggered the upgrade to `heroku-20` stack to replace the now outdated `heroku-18` one — so that's why I'm seeing this error now as well, I guess. Previously, I got another error when trying to upgrade to 1.24.0: that pip was outdated and couldn't cope with some of the new dependencies. So, I changed one error for another one.

**Comment by Twixes** [comment]
Hey! You can absolutely safely switch to Heroku's buildpack! It's been our default for a few months now (for new deployments).
Thanks for noting the pip issue, we'll keep an eye out for this (though I don't think we've seen it ourselves in our `heroku-18`-based deployments).
