### ISSUE TITLE
Events stream shows actions that have been configured

### ISSUE THREAD

**Issue by Tannergoods** [PostHog/posthog#399]
***Thank*** you for your feature request - we love each and every one :)

**Is your feature request related to a problem? Please describe.**
In the events stream it is difficult to know what Actions have already been created and what I need to configure

<img width="1020" alt="Posthog" src="https://user-images.githubusercontent.com/60791437/77319642-1acc0b80-6d07-11ea-90fd-d3b20afadfb7.png">

The problem is I may think I have configured the right actions but I the events stream should be able to show me if something is missing. 

**Describe the solution you'd like**
The events stream should show if an event is linked to an Action ID, perhaps a way to hover over the event will bring up, or Events with an action are in bold?

**Describe alternatives you've considered**
A user could work this out by looking at "live actions" and compare this with events?

**Comment by timgl** [comment]
This is a tough one.

[We used to have an actions method on an Event](https://github.com/PostHog/posthog/commit/cc1de5839394136849b58ffeac998fd205a3ca6c#diff-3b36a34a38797d4ea54c7f9d17d69ac8L330) that allowed you to get all the actions that matched this event. The annoying thing was it meant we had to keep 2 implementations up to date. That might be worth it (and it'd be quick to put back)

@mariusandra What do you think?
