### ISSUE TITLE
Error adding index during migration on partitioned events table

### ISSUE THREAD

**Issue by FUSAKLA** [PostHog/posthog#3993]
## Bug description
Hi, after upgrade from 1.23.1 to 1.24.0 we see in the migration this error
```
django.db.utils.NotSupportedError: cannot create index on partitioned table "posthog_event" concurrently
``` 

We have the events table partitioned using the inbuilt tool and apparently the migration does not handle that well. 

## Environment
Self-hosted instance running in Kubernetes using upstream docker images

**Comment by mariusandra** [comment]
Hey @FUSAKLA , can you run custom SQL in your cluster? I think the "quick fix" now is to run 

```sql
INSERT INTO django_migrations (app, name, applied) VALUES ('posthog', '0141_events_created_at_index', NOW())
```

This will at least prevent the migration from blocking upgrades.

The index was added to [prevent a full table scan](https://github.com/PostHog/posthog/pull/3767) when recalculating actions from `last_calculated_at` until `NOW`. Things should work without it. We'll try to find a better solution next.
