### ISSUE TITLE
Allow using flag key as the identifier in the API

### ISSUE THREAD

**Issue by weyert** [PostHog/posthog#4000]
## Is your feature request related to a problem?

I am working on some automation scripts which allows to generate / update feature flags, in our case, the feature flags need to have a unique key. Each feature flag has its own file in our repository, which defines some meta information. Currently, you need to use the flag integer identifier to query or update feature flags. 

This requires you need retrieve all the feature flags first to check if a feature flag already exists already when you only have the key of the feature flag. 

## Describe the solution you'd like

I would like to propose the ability to also use the `key`-property alongside the `id`-property to query an existing feature flag. This would allow to easily query a feature flag with a more human-readable value than a numeric `id`-property.
 
## Describe alternatives you've considered

None, besides fetching all feature flags beforehand

## Additional context

I would like to write a module which syncs feature flags used in the code base with the ones defined in PostHog

**Comment by weyert** [comment]
If you think this is an good idea, I am willing to try to write a PR for it

**Comment by paolodamico** [comment]
This would be great @weyert! Thanks for the suggestion, and hopefully a PR? Should be fairly easy with https://github.com/carltongibson/django-filter that we have installed.

**Comment by weyert** [comment]
@paolodamico Sorry, totally missed your comment. Yeah, I will have a shot at it :)
