### ISSUE TITLE
Column resizing is laggy / unresponsive

### ISSUE THREAD

**Issue by paolodamico** [PostHog/posthog#4001]
## Bug description

The column resizing (which is a pretty useful feature) is quite laggy (see recording below), the experience isn't great.

![2021-04-15 08 04 04](https://user-images.githubusercontent.com/5864173/114892232-6e514180-9dc1-11eb-87c3-b02ca502134a.gif)

## Expected behavior

I would expect columns to resize very smoothly. In addition it'd be great if we could add instrumentation for when a user uses this feature so we can later improve it.

## How to reproduce

See recording.

## Environment

- [X] PostHog Cloud. Latest.
- [ ] self-hosted PostHog, version/commit: _please provide_

**Comment by samwinslow** [comment]
@paolodamico I'll look into using `requestAnimationFrame` — though if it requires too much fiddling with Ant Design's Table component, it might make sense to recreate this from scratch, perhaps even with CSS grid instead of an actual table. 😕  The interface provided by Ant is really limited.

**Comment by paolodamico** [comment]
Makes sense! We might be better moving away from Ant's component but may be to big of a refactor to be worth it.

**Comment by samwinslow** [comment]
The existing version was re-rendering every table cell on each resize event, yikes! Now, the header is actually a totally separate div & I'm using some CSS hacks on the antd table columns to change size without re-rendering.

Only thing to figure out now is how to constrain the whole table to parent & enable `overflow: scroll` without messing up the children.

https://user-images.githubusercontent.com/4645779/115039143-2fdd8480-9e9e-11eb-87ed-03f2af9bbaa6.mp4

**Comment by paolodamico** [comment]
Nice deep dive on this @samwinslow ! That definitely explains the lagginess, will take a look at the referenced PR and we can continue the conversation there.
