### ISSUE TITLE
JS_URL env variable is not honoured in production

### ISSUE THREAD

**Issue by lharress** [PostHog/posthog#4009]
## Bug description

Setting `JS_URL` is not honoured in production. Webpack has a hard coded `/static/`

## Expected behavior

Ability to override the publicPath of Webpack

## How to reproduce

1. Set `JS_URL` to a URL of choice and `NODE_ENV` to `production`
2. Build Webpack assets

## Environment

- [ ] PostHog Cloud
- [x] self-hosted PostHog, version/commit: 1.24.0

## Additional context

Looks like it's only used in non-production environments.

https://github.com/PostHog/posthog/blob/f7dfc7f7e24a2f83b7e1fe8dfa168a71522c1e01/webpack.config.js#L73-L78

**Comment by lharress** [comment]
Happy to throw together a PR

```javascript
publicPath:
    process.env.JS_URL
        ? `${process.env.JS_URL}${process.env.JS_URL.endsWith('/') ? '' : '/'}static/`
        : process.env.NODE_ENV === 'production'
        ? '/static/'
        : `http${process.env.LOCAL_HTTPS ? 's' : ''}://${webpackDevServerFrontendAddr}:8234/static/`,
```

**Comment by Twixes** [comment]
Hey, thanks for this @lharress! A PR would be great!

**Comment by lharress** [comment]
Sorry for the delay @Twixes, our Posthog project got a bit side tracked. Here's a PR - https://github.com/PostHog/posthog/pull/4362
