### ISSUE TITLE
WIP Import / data migration (Google Analytics) 

### ISSUE THREAD

**Issue by Tannergoods** [PostHog/posthog#402]
***Thank*** you for your feature request - we love each and every one :)

**Is your feature request related to a problem? Please describe.**
I would like to use PostHog but I have historical data in something like Google Analytics - I'd like to retain that historical data in my PostHog instance

**Describe the solution you'd like**
I would like a way of mapping data from GA to PostHog (perhaps I should create separate issues for migrating data from other alternatives to GA?) then transferring it to my PostHog instance.

**Describe alternatives you've considered**
I can export data from GA, so without mapping I could just import if an import function existed.

**Additional context**
Requested by: 
https://app.hubspot.com/contacts/6958578/contact/38351 
https://app.hubspot.com/contacts/6958578/contact/45302

**Comment by timgl** [comment]
**If you're picking this up as an interview task:**

This task is intentionally left vague. I'll leave it up to you to come up with a proposed minimum viable solution for this. Think of the specific constrains we might encounter (large exports?) and show you've thought about how to mitigate those.

**Comment by manuelfcreis** [comment]
# Integrations on Posthog

It's clear that posthog will benefit from a series of integrations. Google analytics may be the first but there are many other services that could be integrated with Posthog. Therefore I'm going to try an make this workflow as abstract as possible.

Regarding the specific integration: I've been looking into [Google Python Api](https://github.com/googleapis/google-api-python-client) and it seems to be possible to implement. Details are still a bit fuzzy, namely how to securely save the authentication information.

## Issue

This integration seems to have 6 main *tasks*

1. **Initial authentication**
    * Add an integrations sections to the settings page.
    * Each team can have several integrations (in this case GA)
    * You can select which integration to add and the process should be easy to follow
    * We need to securely store this information on the server
    * We need to ensure authentications have the adequate permissions

2. **Mapping data structures (import helper)**
    * Users should be able to select what data to import - This data should be    obtained with authentication if possible
      * Specific users / pages
      * Specific projects
      * Specific start / end-dates
      * Rename specific fields to be Posthog compliant (if needed)
    * Specify other attributes
      * i.e. how often should the server grab new information, Authentication name, should the data have a specific prefix, etc.

3. **Initial import**
    * Run the initial import.
        * This could be done on a worker to ensure that it doesn't impact the main server.
        * Batching the data will also probably be needed.
    * Maybe the user should be able to verify if the data is correct

4. **Editing / Deleting integrations**
    * Have an editing / deleting page for the integration

5. **Recurrent imports**
    * Ensure that continuous imports happen (if requested)

6. **Refresh authentication**
    * It may be needed to refresh the authentication from time to time (specially with Google applications). We need an interface for this.

Imports should probably be done using some sort of jobs queuing system to reduce stress on the main server. Specially if recurrent imports are needed.

## Implementation

I'm going to continue working on step one **Authentication**. I'm thinking of associating each Team with many authentications. These will have several categories with different import mechanisms.

Just wanted to give an update on my thinking @timgl. I'll give a better rundown of each step as I go.

**Comment by timgl** [comment]
I like this a lot and thank you for your thoroughness. However in the spirit of trying to get something small done, how could we cut this scope down into an mvp? For example I don’t think a continious update/authentication is required.

**Comment by manuelfcreis** [comment]
Yes, totally. This is what I would consider a v1 of the feature. I'm working on authentication and afterwards will focus on the import feature. Eventually, if we have the time, we can implement the other tasks.

**Comment by manuelfcreis** [comment]
After talking with @timgl this morning we reached a couple of conclusions:

* The google Analytics API has some implementation issues that could take some time to solve. Namely how to store credentials for each individual instance of posthog.
* The approach now will be to create a CSV parser that is ready to read Google Analytics data. This will be extendable to general CSVs. Then, using the batch API, data will be sent to the server.
* This CSV parser should be accessible first through a script. Eventually a CLI / Web interface will be created, most likely a CLI. The details of the CLI still need to be discussed but it could ease the use of the Posthog api.

I will now start working on the CSV parser.

**Comment by jamesefhawkins** [comment]
This sounds good.

A generalised CSV parser sounds useful anyway - I could see some enterprise customers finding this an easy way to "test out" the system on a subset of data for databases that we don't yet integrate with.

**Comment by Twixes** [comment]
Superseded by #2904.
