### ISSUE TITLE
Lifecycle Toggle Bug

### ISSUE THREAD

**Issue by yakkomajuri** [PostHog/posthog#4035]
Love the new lifecycle toggle!

Found one issue though:

https://user-images.githubusercontent.com/38760734/115281746-dba20100-a138-11eb-9ff9-0d8538d21a50.mov

## Description

Toggling off 'returning' shows no data when there are clearly other sections to show

## How to reproduce

I found this on the playground:

https://playground.posthog.com/insights?insight=LIFECYCLE&properties=%5B%5D&filter_test_accounts=false&interval=day&display=ActionsLineGraph&actions=%5B%5D&events=%5B%7B%22id%22%3A%22%24pageview%22%2C%22name%22%3A%22%24pageview%22%2C%22type%22%3A%22events%22%2C%22order%22%3A0%2C%22math%22%3A%22total%22%7D%5D&shown_as=Lifecycle&compare=false&date_from=-90d

**Comment by paolodamico** [comment]
I believe this has been addressed, can you confirm?

**Comment by Twixes** [comment]
Yup.
