### ISSUE TITLE
Add commas to big numbers on dashboards

### ISSUE THREAD

**Issue by jamesefhawkins** [PostHog/posthog#4044]
## Is your feature request related to a problem?

Numbers like this are hard to read:

<img width="141" alt="Screenshot 2021-04-20 at 16 26 57" src="https://user-images.githubusercontent.com/47497682/115422885-3ac54b80-a1f5-11eb-9a8c-3400012d1d41.png">

## Describe the solution you'd like

Commas added ie 1000000 -> 1,000,000 to the axis of the graph.

## Describe alternatives you've considered

Glasses

**Comment by RiyaNegi** [comment]
Hey, I would like to pick up this issue :)

**Comment by timgl** [comment]
Go for it!

**Comment by buwilliams** [comment]
Picked this up to move it along. It's being resolved by #4231
