### ISSUE TITLE
Dropdowns too narrow

### ISSUE THREAD

**Issue by corywatilo** [PostHog/posthog#4045]
## Bug description

Dropdowns seem to open at the width of the previously selected option.

![image](https://user-images.githubusercontent.com/154479/115425982-199d3480-a1ce-11eb-8592-9d8f05315855.png)

## Expected behavior

It would be ideal to decouple the width of the dropdown from the currently-selected option. The expanded dropdown should ideally be the width of the longest option, with a reasonable max-width for edge cases.

## How to reproduce

1. Choose a short math selector
2. Open the dropdown again

## Environment

PostHog Cloud

**Comment by corywatilo** [comment]
Another example inside event filter (Cohort)

![image](https://user-images.githubusercontent.com/154479/115432485-684dcd00-a1d4-11eb-8034-ccc41910ca94.png)

**Comment by samwinslow** [comment]
Although #4129 was merged which fixed the cohort select width, the issue with math operator select remains. Reopening until that's solved, too.
