### ISSUE TITLE
Move documentation from wiki to our own domain

### ISSUE THREAD

**Issue by timgl** [PostHog/posthog#406]
**Is your feature request related to a problem? Please describe.**

The GitHub wiki isn't very user friendly, easily searchable. We also can't understand what our most visited pages are etc.

**Describe the solution you'd like**

- [ ] Move the docs from the wiki to either a /docs folder in this repo, or a separate repo
- [ ] Use Docsify with [server-side rendering](https://docsify.now.sh/ssr) for SEO
  - [ ] Host it on github pages
  - [ ] Create a `docs.posthog.com` subdomain
- [ ] Update references to the wiki within this repository
- [ ] Remove the content within the wiki and link to the relevant page in the new docs
- [ ] Update link in all of our libraries

**Comment by jamesefhawkins** [comment]
FYI I'm working on this now.

**Comment by timgl** [comment]
Can't wait to see this!!

**Comment by jamesefhawkins** [comment]
I will create two versions:

1 - /company (or something similar) like the GitLab handbook
2 - /docs as above

**Comment by timgl** [comment]
Perfect

**Comment by timgl** [comment]
We're moving again ;)
