### ISSUE TITLE
Refactor `funnel.py` to use sql string rather than hybrid ORM

### ISSUE THREAD

**Issue by buwilliams** [PostHog/posthog#4067]
## In what situation are you experiencing subpar performance?

Understanding `posthog/queries/funnel.py` is more difficult than it needs to be. We have a better practice of using sql strings. This also makes converting between Clickhouse and Postgres easier.

## Environment

- [x] PostHog Cloud
- [x] self-hosted PostHog, version/commit: _please provide_

## Additional context

This is an ongoing effort to refactor queries to make them more maintainable.

This came up during work on #3765 for task `Defining a cohort from people who completed/dropped off in funnel step X`

**Comment by buwilliams** [comment]
Tim and I discussed that refactoring the Postgres side didn't make sense right now because it's not a priority. I'm unable to work on the Clickhouse side at the moment due to env issues.

**Comment by neilkakkar** [comment]
Given focus on ClickHouse, maybe we can close this?

**Comment by Twixes** [comment]
I believe so @neilkakkar.
