### ISSUE TITLE
[README] Slack invite link not working 

### ISSUE THREAD

**Issue by RiyaNegi** [PostHog/posthog#4072]
## Bug description
Slack link in the readme section allows users only from specific domains. I am not sure if it is supposed to be open for everyone or not, but the gmail domain isn't allowed to enter the slack community

The invite is mentioned in this section [Make the Most of PostHog
](https://github.com/PostHog/posthog#make-the-most-of-posthog) 

![Screenshot from 2021-04-22 00-45-46](https://user-images.githubusercontent.com/32849732/115609378-148ed100-a305-11eb-801f-92cc44f5a427.png)

**Comment by timgl** [comment]
Thanks! That's fixed
