### ISSUE TITLE
Looks like set_once is not working as expected

### ISSUE THREAD

**Issue by akbansa** [PostHog/posthog#4082]
## Bug description

`set_once` is not working as expected.

## Expected behavior

`set_once` is expected to be the unique attribute setter against a person.  Like if I am calling `posthog.people.set_once("param", "value")`, then the user identified in this session will have an attribute `param` with value `value`

## How to reproduce

1. Identify a non-exitent person and call `posthog.people.set_once("param", "value1")` on one page (P1)
2. Now, identify person on another page and call `posthog.people.set_once("param", "value1")` on the page (P2)
3. Ideally the value for `param` => P1 but in some of the cases it's P2

## Environment

- [x] PostHog Cloud
- [ ] self-hosted PostHog, version/commit: _please provide_

**Comment by paolodamico** [comment]
Hey @akbansa! How are you setting these properties? Thinking this could potentially be a race condition in which the server receives first the call from P2. Could they be sent in like very close together requests? (as in navigation between P1 & P2 happening too fast)? You're using `posthog-js` right?

Extra context: https://posthogusers.slack.com/archives/G01JXEDAL22/p1619218396003200

Tagging @yakkomajuri as he'll be taking over support in the next weeks

**Comment by akbansa** [comment]
Yes, we're using `posthog-js`.

That's not the case. Going from P1 -> P2 is not very instant!

Sharing a Loom in your slack DM.

**Comment by yakkomajuri** [comment]
We might need to manage expectations here a bit better. There is indeed a potential race condition when using `$set_once`, although I am not yet sure this is indeed what is happening

**Comment by mariusandra** [comment]
I think this should be quite easy to solve if we add one more field to `person`, something like `property_timestamps` that would basically contain the "updated_at" field for every property. We would consult this timestamp when using `set_once` and update the value only if an incoming event has an earlier `timestamp` compared to the existing property's timestamp.

However, while this sounds simple, we might benefit from batching this in with a bunch of other refactors to the persons tables, such as #4242 . 

In addition I'd argue that for tasks such as https://github.com/PostHog/plugin-server/pull/326 we would also benefit from denormalising the person properties json, and making a new `person_property` table, where we could update individual properties without needing to update the entire json object at the same time. This would seriously reduce the chance of overriding data. I'll make a new issue about this soon.
