### ISSUE TITLE
Solve for app load times for teams with huge number of events or properties

### ISSUE THREAD

**Issue by paolodamico** [PostHog/posthog#4087]
This came from an enterprise customer running into issues. Full context on [this thread](https://posthog.slack.com/archives/C01G8S5T08Z/p1619023222035300). #4070 & #4078 already took us a long way towards fixing this, however there are a few outstanding things to consider:

1. We need to update the plugin-server & related ingestion to start storing the event and properties directly in the new models.
2. We need to update the core backend to:
 - Compute event and property volume and usage directly in the new model. 
 - Remove the syncing between the `Team` model and the new models. Both steps (1) & (2) are quite relevant to avoid any strange bugs caused by out-of-sync models. Particularly, as the event names & properties are updated on the plugin server, there's no guarantee that the new models will be up-to-date in near-real-time.
 - Remove any deprecated code.
3. **This step doesn't have to be sequential** (can be done in parallel or even before 1). While the PRs already out do improve things and prevent timeouts a lot better, the app may still take a long time to be fully ready to perform analytics if you have a ton of events or properties. To address this, I came up with two options.

## Step 3 - Option A
- In a nutshell, we cache event names and properties in localStorage (or somewhere else in the client). When the app loads, we only load incremental updates to properties that have been added. This would significantly reduce load times as well as server load.
- This would require changing pagination on the server-side to something deterministic (like [Cursor-based pagination](https://www.django-rest-framework.org/api-guide/pagination/#cursorpagination)) where we sort by some immutable property like the ascending PK (need to confirm if our UUID's implementation would support this ascending sorting well on Postgres, @Twixes)
- We then simply store the last cursor loaded as well as all the data elements in cache/localStorage. When the app loads we ask the API for any events/properties added after the cursor we have last.

**Downsides**
- The client may still slow down significantly by having all these properties and events in memory. Particularly when we start performing operations (chiefly search & sorting).
- This will not handle well if properties/events get removed. We would either have to expire the cache every now and again and reload everything or do some special handling to ask the server which properties/events have been removed that we should get rid of. We could get creative with something similar to Merkel trees here, but seems like an overkill.

## Step 3 - Option B
- In essence, we stop loading all events & properties altogether when the app launches and we load everything on demand. That is, with server-side searching.
- It's likely that for large event/properties volumes, Postgres won't be fast enough to query, and we'd have to implement something with strong indices optimized for this, like Elasticsearch.

**Downsides**
- Browsing properties will be a pain. We could load the most relevant ones (i.e. most used), but if you just want to see the whole list, we will still have to load everything every time you open the app.
- Postgres will likely not work here. Even if performance is fine (which I'm very doubtful), the search engine is not great to handle stuff like fuzzy searching, typos, etc. which leaves us with implementing some other engine that can handle this, which has the downside of being another thing to manage.

**Comment by mariusandra** [comment]
Thanks @paolodamico for all the work in solving this! The customers facing the issues will really be happy when it gets resolved! :)

I'll review the frontend PR https://github.com/PostHog/posthog/pull/4078 next, yet already dropping some thoughts for next steps.

I think we should go with "step 3 option B" and load everything just in time. Right now the event names & properties can be around ~3MB for heavy users, but soon it might be ~30MB. While that's enough for most users to handle, what if it grows again to ~100MB. Unfortunately we must optimise for "the weakest link" here, which is users with a lot of event names/props. 

On the plus side, I think postgres will handle searching and filtering all of this just fine with capacity to spare, even if it does a full scan every time (scoped by team obv). So I really wouldn't worry about it. In my last startup, we replaced elasticsearch with postgres at some point to power the main search engine. It worked out really well. So there will definitely be no need to optimise this any time soon :)

**Comment by mariusandra** [comment]
The PR for the plugin server is here: https://github.com/PostHog/plugin-server/pull/331
It's unfortunately still WIP (haven't fixed the tests). Feel free to poke it if you like, otherwise I'll clean it up latest on Monday.

**Comment by paolodamico** [comment]
Adding some extra context from conversations with @mariusandra. So looks like option B with pure Postgres is the way to go. The current API already supports server-side querying based on `CONTAINS`, however we need to add fuzzy searching support.

Some additional considerations too:
- When the app loads, we should still load the first X events (i.e. first size). If the number of events is <= page size, we can keep everything client-side and avoid extra requests. If not, we switch to server-side querying.
- We should switch to default ordering by query usage & event volume so that the first X events that do get loaded and are available for immediate browsing are the most relevant ones for users.
- In the event/properties stats page we need to add pagination and server-side searching support too.

**Comment by Twixes** [comment]
Just noticed I was mentioned, but yes, `UUIDT` is time-sortable down to millisecond up to the year 10 895 (sorting may not be precisely stable within the latest 1 ms if the IDs are generated in a distributed way, but that's a miniscule concern here).

**Comment by mariusandra** [comment]
We now merged the fix into the plugin server https://github.com/PostHog/plugin-server/pull/331

When that's live, the plugin server will only update the new tables and will 🙈 the old fields on the Team model.

**Comment by paolodamico** [comment]
That's great news @mariusandra! Should we run one final sync between the two, or are we good here?

**Comment by paolodamico** [comment]
Also as post-housekeeping on this (probably worth doing in separate release cycles for self-hosted), I believe we can't delete model attributes yet, but maybe we want to empty the data?

**Comment by mariusandra** [comment]
We don't need to do a sync, but we need to update [this task](https://github.com/PostHog/posthog/blob/61f02aaac751c8ae784480d729974c3aa45cd2df/posthog/celery.py#L92) that runs [this code](https://github.com/PostHog/posthog/blob/2477ce940de5b733134fa3c591ef74125eaacaea/posthog/tasks/calculate_event_property_usage.py#L30), which periodically recalculates all event names and properties. If this would instead update the new models, we could remove the syncing code entirely.

**Comment by paolodamico** [comment]
This is now addressed for teams with a large number of properties or events.
