### ISSUE TITLE
Issue with funnels not getting any data

### ISSUE THREAD

**Issue by paolodamico** [PostHog/posthog#4094]
## Bug description

Please [see this thread](https://posthogusers.slack.com/archives/G01JXEDAL22/p1619218510003600). Seems like funnels are not getting rendered when there seems to be data that should appear.

## Expected behavior

Funnel should render when there's actually data.

## How to reproduce

Please see the linked thread.

## Environment

- [X] PostHog Cloud
- [ ] self-hosted PostHog, version/commit: _please provide_

## Additional context
CC @akbansa, @EDsCODE 
- Maybe will get addressed with @buwilliams's refactor?

**Comment by buwilliams** [comment]
I'll take a look as I work on funnels.

**Comment by morgangallant** [comment]
<img width="1515" alt="Screen Shot 2021-04-26 at 4 55 03 PM" src="https://user-images.githubusercontent.com/8409199/116149523-3d6de800-a6b0-11eb-9448-6c20614dc1f0.png">

Having a seemingly related issue on my self-hosted posthog (on commit 6bea74bb50e50dfececc04b12a6f3951bb766a22), even simple funnels like the one above just don't compute and hang as shown in the screenshot. Is this related to this issue? If so, happy to provide other data points.

**Comment by buwilliams** [comment]
@morgangallant Is the worker process running? Funnels will not return if Celery is down.

**Comment by buwilliams** [comment]
My work on the refactor was paused which blocks this issue for me. @paolodamico the link for more information isn't working. Could you provide any help to reproduce this issue?

**Comment by paolodamico** [comment]
Hey @buwilliams! Just added you to the channel where the referenced link lives. The link contains a screen recording with details on this. Let me know if you need more details.

**Comment by marcushyett-ph** [comment]
@EDsCODE I know we've made a lot of changes to the funnel query now - do we think this is still likely to be an issue?

**Comment by neilkakkar** [comment]
Should be golden!
