### ISSUE TITLE
Two identical looking actions have underlying different configurations

### ISSUE THREAD

**Issue by benjackwhite** [PostHog/posthog#4098]
## Bug description

We have two actions configured (we specifically added the second one to check if the numbers were looking good as we have had a lot of issues relying on actions over the last months). 

**The first action is as so:**

![ui-action1](https://user-images.githubusercontent.com/2536520/116040983-f6aace80-a66c-11eb-8574-811dfabd718d.png)
![json-action1](https://user-images.githubusercontent.com/2536520/116041102-1b9f4180-a66d-11eb-8860-1225e2c0c6a4.png)

**The second action is as below:**

![ui-action2](https://user-images.githubusercontent.com/2536520/116041795-f19a4f00-a66d-11eb-8b92-1eec25f4d35b.png)
![json-action2](https://user-images.githubusercontent.com/2536520/116041135-2528a980-a66d-11eb-8615-ce5aea96c1e5.png)

We caught this as we created an insights panel with both actions and saw different results in the line graphs. Turns out that one action was filtering based on website (catching events from the web) and the other was not (whereby including the same events tracked from our mobile application). We got hinted towards the issue when clicking the insights dropdown and seeing a hint towards the filtering difference

![insights-action1](https://user-images.githubusercontent.com/2536520/116041347-64ef9100-a66d-11eb-88de-c7554c10bbb1.png)
![insights-action2](https://user-images.githubusercontent.com/2536520/116041350-66b95480-a66d-11eb-8083-0e5cf66ce7a6.png)

## Expected **behavior**

The UI for Actions should clearly display that one is filtering based on website domain and the other isn't.

## How to reproduce

Not sure. Although with the provided json it is probably possible to create two actions matching the spec and see that there is no way of differentiating a "website" filtered action from a "non-website" filtered one.

## Environment

- [x] self-hosted PostHog, version/commit: release-1.23.0 via Helm chart on Kubernetes

**Comment by timgl** [comment]
This was fixed in #3902
