### ISSUE TITLE
Dashboards Loading Improvements

### ISSUE THREAD

**Issue by yakkomajuri** [PostHog/posthog#4122]
One of our clients has rightfully pointed out that loading dashboards is rather slow, particularly if you have a lot of panels.

There are things we've been doing to improve this, but there are some other problems I've identified:

- We re-render dashboard panels quite many times, there's probably a way to improve this with smarter logic, props, or using `useMemo` or something
- We mount the annotations logic twice for each dashboard panel. This causes us to also send two requests to `api/annotations/` when we only need one (because the request is triggered by the mounting of the logic)

I was digging into this a bit as support hero but after digging a bit I think it's more like something for Core Experience.

**Comment by paolodamico** [comment]
Highly related to issues experienced by same customer from #4087. Definitely worth focusing on this too. I'll sync with @EDsCODE tomorrow. Happy to pick it up if needed.

**Comment by EDsCODE** [comment]
Yup, currently taking a close look at our network request load on various pages and will start to offer some fixes

**Comment by Twixes** [comment]
Dashboard logic is improved quite a bit now.
