### ISSUE TITLE
Event : 'clicked' , display $el_text

### ISSUE THREAD

**Issue by srbaral** [PostHog/posthog#4128]
## Bug description
For the "clicked" event, rather than saying "clicked", as a I user I wanted to see the value assigned for $etl_text
*Please describe.*  
Events that deal with user clicking the link or a button, the console displays it as a "clicked" only.
As a business user, rather than seeing 100 "clicked" events, I would like to see the value of $el_text.
*If this affects the front-end, screenshots would be of great help.*  

## Expected behavior

See the actual value of the clicked event rather then saying just "clicked"

## How to reproduce

1. Click any button or the link
2. go to the console
3.verify under event and it says "clicked"

## Environment

- [ ] PostHog Cloud
- [ ] self-hosted PostHog, version/commit: _please provide_

**Comment by yakkomajuri** [comment]
We do generally show this value on the UI - can you see in the JSON view if `$el_text` is set?

**Comment by srbaral** [comment]
![Expect Details instead of clicked](https://user-images.githubusercontent.com/83250812/116416633-7e791000-a808-11eb-9e14-23fbcd2e0628.PNG)

**Comment by srbaral** [comment]
User is expecting "Details" . There could be 100 clicks and it's too tedious to go inside the properties and find $el_text

**Comment by srbaral** [comment]
something like clicked (Details) where "( ) will have value of $el_text

**Comment by yakkomajuri** [comment]
Could you paste the event JSON here?

**Comment by srbaral** [comment]
{
    "id": 4720,
    "timestamp": "2021-04-28T13:36:28.218000Z",
    "event": "$autocapture",
    "distinct_id": "['sbaral@i-a-i.com']",
    "properties": {
        "$active_feature_flags": {},
        "$browser": "Chrome",
        "$browser_version": 90,
        "$ce_version": 1,
        "$current_url": "http://localhost:8080/analytics/index/991897",
        "$device_id": "178c737b3e98b8-08e07c0ca83f54-5771031-fa000-178c737b3ea8ee",
        "$device_type": "Desktop",
        "$elements": {
            "0": {
                "classes": {
                    "0": "btn",
                    "1": "btn-sm",
                    "2": "btn-primary"
                },
                "$el_text": "Details",
                "tag_name": "a",
                "nth_child": 1,
                "attr__href": "/analytics/bot/991897",
                "attr__class": "btn btn-sm btn-primary",
                "nth_of_type": 1
            },
            "1": {
                "classes": {
                    "0": "col-xs-8"
                },
                "tag_name": "div",
                "nth_child": 2,
                "attr__class": "col-xs-8",
                "nth_of_type": 2
            },
            "2": {
                "classes": {
                    "0": "row"
                },
                "tag_name": "div",
                "nth_child": 1,
                "attr__class": "row",
                "nth_of_type": 1
            },
            "3": {
                "classes": {
                    "0": "widget-footer"
                },
                "tag_name": "div",
                "nth_child": 2,
                "attr__class": "widget-footer",
                "nth_of_type": 1
            },
            "4": {
                "classes": {
                    "0": "widget-body",
                    "1": "text-center"
                },
                "tag_name": "div",
                "nth_child": 1,
                "attr__class": "widget-body text-center",
                "nth_of_type": 1
            },
            "5": {
                "tag_name": "div",
                "nth_child": 2,
                "attr__role": "content",
                "nth_of_type": 1
            },
            "6": {
                "classes": {
                    "0": "jarviswidget",
                    "1": "jarviswidget-color-minerva"
                },
                "attr__id": "wid-id-bots",
                "tag_name": "div",
                "nth_child": 1,
                "attr__role": "widget",
                "attr__class": "jarviswidget jarviswidget-color-minerva ",
                "nth_of_type": 1,
                "attr__data-widget-sortable": "false",
                "attr__data-widget-editbutton": "false",
                "attr__data-widget-colorbutton": "false",
                "attr__data-widget-deletebutton": "false",
                "attr__data-widget-togglebutton": "false",
                "attr__data-widget-fullscreenbutton": "false"
            },
            "7": {
                "classes": {
                    "0": "col-xs-12",
                    "1": "col-sm-6",
                    "2": "col-md-6",
                    "3": "col-lg-3",
                    "4": "sortable-grid",
                    "5": "ui-sortable"
                },
                "tag_name": "article",
                "nth_child": 3,
                "attr__class": "col-xs-12 col-sm-6 col-md-6 col-lg-3 sortable-grid ui-sortable",
                "nth_of_type": 3
            },
            "8": {
                "classes": {
                    "0": "row"
                },
                "tag_name": "div",
                "nth_child": 3,
                "attr__class": "row",
                "nth_of_type": 3
            },
            "9": {
                "attr__id": "widget-grid",
                "tag_name": "section",
                "nth_child": 4,
                "nth_of_type": 1
            },
            "10": {
                "attr__id": "content",
                "tag_name": "div",
                "nth_child": 7,
                "nth_of_type": 3
            },
            "11": {
                "classes": {
                    "0": "container"
                },
                "tag_name": "div",
                "nth_child": 5,
                "attr__class": "container",
                "nth_of_type": 1
            },
            "12": {
                "tag_name": "r:layoutresources",
                "nth_child": 1,
                "nth_of_type": 1,
                "attr__disposition": "head"
            },
            "13": {
                "classes": {
                    "0": "desktop-detected"
                },
                "tag_name": "body",
                "nth_child": 2,
                "attr__class": "desktop-detected",
                "attr__style": "min-height: 640px;",
                "nth_of_type": 1
            }
        },
        "$elements__0__$el_text": "Details",
        "$elements__0__attr__class": "btn btn-sm btn-primary",
        "$elements__0__attr__href": "/analytics/bot/991897",
        "$elements__0__classes__0": "btn",
        "$elements__0__classes__1": "btn-sm",
        "$elements__0__classes__2": "btn-primary",
        "$elements__0__nth_child": 1,
        "$elements__0__nth_of_type": 1,
        "$elements__0__tag_name": "a",
        "$elements__10__attr__id": "content",
        "$elements__10__nth_child": 7,
        "$elements__10__nth_of_type": 3,
        "$elements__10__tag_name": "div",
        "$elements__11__attr__class": "container",
        "$elements__11__classes__0": "container",
        "$elements__11__nth_child": 5,
        "$elements__11__nth_of_type": 1,
        "$elements__11__tag_name": "div",
        "$elements__12__attr__disposition": "head",
        "$elements__12__nth_child": 1,
        "$elements__12__nth_of_type": 1,
        "$elements__12__tag_name": "r:layoutresources",
        "$elements__13__attr__class": "desktop-detected",
        "$elements__13__attr__style": "min-height: 640px;",
        "$elements__13__classes__0": "desktop-detected",
        "$elements__13__nth_child": 2,
        "$elements__13__nth_of_type": 1,
        "$elements__13__tag_name": "body",
        "$elements__1__attr__class": "col-xs-8",
        "$elements__1__classes__0": "col-xs-8",
        "$elements__1__nth_child": 2,
        "$elements__1__nth_of_type": 2,
        "$elements__1__tag_name": "div",
        "$elements__2__attr__class": "row",
        "$elements__2__classes__0": "row",
        "$elements__2__nth_child": 1,
        "$elements__2__nth_of_type": 1,
        "$elements__2__tag_name": "div",
        "$elements__3__attr__class": "widget-footer",
        "$elements__3__classes__0": "widget-footer",
        "$elements__3__nth_child": 2,
        "$elements__3__nth_of_type": 1,
        "$elements__3__tag_name": "div",
        "$elements__4__attr__class": "widget-body text-center",
        "$elements__4__classes__0": "widget-body",
        "$elements__4__classes__1": "text-center",
        "$elements__4__nth_child": 1,
        "$elements__4__nth_of_type": 1,
        "$elements__4__tag_name": "div",
        "$elements__5__attr__role": "content",
        "$elements__5__nth_child": 2,
        "$elements__5__nth_of_type": 1,
        "$elements__5__tag_name": "div",
        "$elements__6__attr__class": "jarviswidget jarviswidget-color-minerva ",
        "$elements__6__attr__data-widget-colorbutton": "false",
        "$elements__6__attr__data-widget-deletebutton": "false",
        "$elements__6__attr__data-widget-editbutton": "false",
        "$elements__6__attr__data-widget-fullscreenbutton": "false",
        "$elements__6__attr__data-widget-sortable": "false",
        "$elements__6__attr__data-widget-togglebutton": "false",
        "$elements__6__attr__id": "wid-id-bots",
        "$elements__6__attr__role": "widget",
        "$elements__6__classes__0": "jarviswidget",
        "$elements__6__classes__1": "jarviswidget-color-minerva",
        "$elements__6__nth_child": 1,
        "$elements__6__nth_of_type": 1,
        "$elements__6__tag_name": "div",
        "$elements__7__attr__class": "col-xs-12 col-sm-6 col-md-6 col-lg-3 sortable-grid ui-sortable",
        "$elements__7__classes__0": "col-xs-12",
        "$elements__7__classes__1": "col-sm-6",
        "$elements__7__classes__2": "col-md-6",
        "$elements__7__classes__3": "col-lg-3",
        "$elements__7__classes__4": "sortable-grid",
        "$elements__7__classes__5": "ui-sortable",
        "$elements__7__nth_child": 3,
        "$elements__7__nth_of_type": 3,
        "$elements__7__tag_name": "article",
        "$elements__8__attr__class": "row",
        "$elements__8__classes__0": "row",
        "$elements__8__nth_child": 3,
        "$elements__8__nth_of_type": 3,
        "$elements__8__tag_name": "div",
        "$elements__9__attr__id": "widget-grid",
        "$elements__9__nth_child": 4,
        "$elements__9__nth_of_type": 1,
        "$elements__9__tag_name": "section",
        "$event_type": "click",
        "$host": "localhost:8080",
        "$initial_referrer": "$direct",
        "$initial_referring_domain": "$direct",
        "$insert_id": "ci9quq1ounezobhv",
        "$ip": "10.5.65.40",
        "$lib": "web",
        "$lib_version": "1.9.7",
        "$os": "Windows",
        "$pathname": "/analytics/index/991897",
        "$referrer": "http://localhost:8080/analytics/index/991902",
        "$referring_domain": "localhost:8080",
        "$screen_height": 800,
        "$screen_width": 1280,
        "$time": 1619616988.217,
        "$user_id": {
            "0": "sbaral@i-a-i.com"
        },
        "$user_id__0": "sbaral@i-a-i.com",
        "distinct_id": {
            "0": "sbaral@i-a-i.com"
        },
        "distinct_id__0": "sbaral@i-a-i.com",
        "token": "6A7hNbyN4HkKStaGh7CyulFLWmNg"
    }
}
