### ISSUE TITLE
Server side rendering

### ISSUE THREAD

**Issue by Immortalin** [PostHog/posthog#413]
Any plans to implement server side rendering for the main dashboard/editor? Perhaps Next.js?

**Comment by timgl** [comment]
Thanks for raising! I'd be awesome if someone in the community wants to pick this up. Do you have an idea of effort involved in doing this and benefits?

**Comment by jamesefhawkins** [comment]
@Immortalin were you hoping to use this to embed the dashboards into another piece of software?

For example, it'd be cool if PostHog were used to generate a layer of metadata - those dashboard components, cohorts of users, etc, that could be pulled into other software.

**Comment by Twixes** [comment]
Hey! We're quite deeply immersed in client-side React for the app and the benefits of server-side rendering aren't big enough to do such a significant migration, hence I have to close this.
