### ISSUE TITLE
Posthog crashed w/ internal server error and not loading anymore

### ISSUE THREAD

**Issue by hchings** [PostHog/posthog#4136]
## Bug description
After deploying posthog and make sure the events start to flow in, we were able to use posthog for a few minutes.
Then, Posthog crashed with the below error and we couldn't use it anymore:
![image](https://user-images.githubusercontent.com/14718778/116359482-b144e900-a7b3-11eb-9053-4961e2cf98c7.png)

## Environment

- [ ] PostHog Cloud
- [x] self-hosted PostHog, version/commit: _please provide_

## Additional context
- Deploy through Heroku

**Comment by yakkomajuri** [comment]
Hey @hchings are you on the completely free plan?

Also, could you share your Heroku logs?

**Comment by hchings** [comment]
@yakkomajuri  yes to the free plan.
I'm new to Posthog, can you point me to where I can see the logs?

It can work for a while after hard-refresh, but it just crashed again.

**Comment by yakkomajuri** [comment]
Hey @hchings I mean your Heroku logs actually. I think your instance just has very little resources available to it

**Comment by Twixes** [comment]
We've chatter on Slack, it was indeed an issue with resources.
