### ISSUE TITLE
Add date picker and "between" option when filtering by time

### ISSUE THREAD

**Issue by samwinslow** [PostHog/posthog#4146]
## Is your feature request related to a problem?

Unix timestamps are a little gnarly to use in filter comparisons. See here:

<img width="809" alt="Screen Shot 2021-04-28 at 12 46 44 PM" src="https://user-images.githubusercontent.com/4645779/116447251-c35f6f80-a825-11eb-8bc4-32cb08e4d7d6.png">

## Describe the solution you'd like

- `<` / `>` comparisons should still work as the underlying data type is still a number, but show the value as an ISO 8601 string
- Create a new operator "between" that accepts two arguments

## Nice to haves:

- Date picker instead of select

**Comment by samwinslow** [comment]
Tried an approach which blended the text input and date formatting, it seems less feasible than using a date picker.

**Comment by samwinslow** [comment]
Related issues: #4345.

**Comment by paolodamico** [comment]
Scope is almost duplicated with #6619, so keeping that one.
