### ISSUE TITLE
"Permitted Domains/URLs" setting is not saving between page reloads

### ISSUE THREAD

**Issue by MarkBennett** [PostHog/posthog#4149]
## Bug description

The "Permitted Domains/URLs" setting is not saving between page reloads. When I add them they appear momentarily, but after reloading the page or switching screens they're gone.

See "How to reproduce" below for screenshots.

## Expected behavior

I expect the urls to persist between page loads.

## How to reproduce

1. Visit ["Project Settings"](https://app.posthog.com/project/settings)
2. Scroll down to "Permitted Domains/URLs"
3. Confirm that no domains/urls have been added

![Screen Shot 2021-04-28 at 1 03 02 PM](https://user-images.githubusercontent.com/61872/116459221-c6a52c00-a822-11eb-9040-214e5ab7077a.png)

4. Click, "+ Add Url"
5. Add a new url (ie. "www.clhbid.com") then click "Save"
6. Confirm you see "App Urls Successfully Updated"
7. Confirm the new url appears in the list of permitted urls

![Screen Shot 2021-04-28 at 1 02 47 PM](https://user-images.githubusercontent.com/61872/116459279-d6247500-a822-11eb-872b-c92c1717e99a.png)

8. Reload the page (or click the "Toolbar" button)
9. Confirm that it's back to saying that no domains/urls have been added

![Screen Shot 2021-04-28 at 1 02 35 PM](https://user-images.githubusercontent.com/61872/116459346-e9374500-a822-11eb-94d5-82580113d234.png)

## Environment

- [x] PostHog Cloud
- [ ] self-hosted PostHog, version/commit: _please provide_

## Additional context
* Using Chrome Version 90.0.4430.93 (Official Build) (arm64)
* No obvious errors in the console

**Comment by paolodamico** [comment]
Hey @MarkBennett, thanks for reporting! Fix coming
