### ISSUE TITLE
Events aren't updated one experimenting/dev mode locally

### ISSUE THREAD

**Issue by EDsCODE** [PostHog/posthog#4150]
## Bug description

*Please describe.*  
- if you're on the development mode account, new events won't be updated due to the changes related to this thread #4110 
- i believe it's because event updating will mainly rely on plugin

## Expected behavior
- development experience should still keep up with expected behavior

## How to reproduce

1. develop locally using pg backed deployment and select just experimenting as account type
2. try to posthog.capture a new event
3. notice that when you try to filter on it, you can't find it in the event dropdown but if you go to the events table the event is logged correctly

## Environment

- [ ] PostHog Cloud
- [ ] self-hosted PostHog, version/commit: _please provide_

**Comment by Twixes** [comment]
This should be solved now.
