### ISSUE TITLE
Change date format

### ISSUE THREAD

**Issue by corywatilo** [PostHog/posthog#4154]
![image](https://user-images.githubusercontent.com/154479/116482148-8fe70a00-a852-11eb-8988-911635bebb96.png)

Date formats are currently not in US format. Given that our [writing style](https://posthog.com/handbook/company/communication#writing-style) is American English, it would make sense to standardize (hence filed as a bug).

Ideal solution would be to offer a date format option in user preferences - ideal for customers with users in different countries (which would be more of an enhancement).

**Comment by paolodamico** [comment]
To clarify, you mean doing `mm/dd/yyyy` or the format as shown on #4156? Because I think the former could be quite confusing and we would be losing the day name which is quite useful. I particularly like the way you show them in the referenced ticket.

**Comment by corywatilo** [comment]
Correct, just: mon/dd, not dd/month

**Comment by paolodamico** [comment]
@corywatilo what do we want to do for months and weeks? i.e. when the interval represents more than a single day. Think it's worth making this explicit.

**Comment by clarkus** [comment]
@lottiecoxon this issue is related to the chart axis project you've been working on. Would be good to incorporate whatever date format you land on here.
