### ISSUE TITLE
Nested event table lags with high property count

### ISSUE THREAD

**Issue by samwinslow** [PostHog/posthog#4164]
## Bug description

Event property table (nested within Events table) lags when the property count is very high. The below video shows performance with 5000 event properties.

https://user-images.githubusercontent.com/4645779/116577007-1694f900-a8de-11eb-966a-df5c20201735.mp4

Good candidate for switching to virtualized table (see also #4143)

## Environment

- [ ] PostHog Cloud
- [ ] self-hosted PostHog, version/commit: _please provide_

**Comment by EDsCODE** [comment]
Overall, we should push to update all user generated info to support high volume (virtualizing as many lists as possible)
