### ISSUE TITLE
Custom Action - All Unique Users

### ISSUE THREAD

**Issue by Tannergoods** [PostHog/posthog#418]
***Thank*** you for your feature request - we love each and every one :)

**Is your feature request related to a problem? Please describe.**
Funnels help me see what users carry out a series of actions in a row, as it shows unique users repeating those actions it will always start at 100% - I don't know what % of my users are performing step 1 out of all possible users.

**Describe the solution you'd like**
A single custom "action" that is all unique users - I can then add this to step 1 of my funnels to see the % of users (from all available) that follow this set of actions

**Describe alternatives you've considered**
I could push a custom event for unique users - if I had an action where I was confident all of my unique users have done this would also suffice

**Additional context**
Requested on PostHog Users Slack

**Comment by timgl** [comment]
Isn't this kind of the default "pageview" action?

**Comment by Tannergoods** [comment]
This was my suggestion on the channel but there is a chance this doesn't capture all unique users or am I wrong?

**Comment by 0xb0br** [comment]
It is if every pageview is a unique user. But normally I would class a pageview to be somthing a unique user does, therfor one unique user can make multiple page views. Sound right?

**Comment by Tannergoods** [comment]
That is right - but for the purpose of funnels only unique users count once - so although they can make multiple page views they would not affect the % of unique users that progress through a funnel?

**Comment by 0xb0br** [comment]
> for the purpose of funnels only unique users count once

Ok if that is the case then you already have the ability to have unqiue users at the start of a funnel with $pageview.

I'm still breaking the db process with that though. I was thinking $person or $unique, somthing like that would not batter the db process so much.

We can close this issue then? Thank you for your help.

**Comment by Tannergoods** [comment]
https://github.com/PostHog/posthog/issues/410 will remove the need for this issue
