### ISSUE TITLE
Home button isn't consistent on different accounts

### ISSUE THREAD

**Issue by sankalpdomore** [PostHog/posthog#4187]
## Bug description
Noticed a new update on the app when I login. There's a new "Home" section which appears my one account which doesn't have any script logged yet, but on the other account where the script is running on my blog and data is coming in, the "Home" button on left-sidebar doesn't appear. Is that intended?

Tried after clearing cache, still producing the same problem. Checkout the screenshots in the "How to reproduce" section below.

## Expected behavior

The "Home" button should be present on all accounts, I think.

## How to reproduce

- "Home" button appears on account where no script has been added to my site 
![CleanShot 2021-05-01 at 22 15 40@2x](https://user-images.githubusercontent.com/18334593/116789099-d21a8080-aaca-11eb-8826-63b5475792d0.png)

- "Home" button isn't there on account where script has been added
![CleanShot 2021-05-01 at 22 10 03@2x](https://user-images.githubusercontent.com/18334593/116789113-d8a8f800-aaca-11eb-82e4-eea1bade3cd8.png)

## Environment

- [x] PostHog Cloud

**Comment by paolodamico** [comment]
Hi @sankalpdomore! Thanks for reporting. This is expected as the "Home" page is part of an ongoing experiment. Depending on how this goes we hope to be able to release for everyone (with some improvements) in the future.
