### ISSUE TITLE
Release 26-1 Core Experience Team pre-planning

### ISSUE THREAD

**Issue by paolodamico** [PostHog/posthog#4190]
Opening this issue to document and discuss issues as we plan our work for the next release cycle. As we go for priorities for the next release cycle useful to keep in mind two things:
1) Our new metric, https://github.com/PostHog/internal/issues/263 
2) What's the absolute best thing that we could be working on today? Easy to find useful things to build, but what are the most impactful ones?

**Comment by buwilliams** [comment]
I'd balance the question, "best thing" with including the idea that best thing may be what's also helpful for training.

**Comment by paolodamico** [comment]
Yeah that makes sense @buwilliams, I would just make sure we have a strong balance in shipping stuff and doing stuff for learning/training/tech debt.

**Comment by samwinslow** [comment]
Today I'll focus on building the left side (Insights filters, main section) of Option B described in https://github.com/PostHog/posthog/issues/4050. Tomorrow, hopefully will get global filters, breakdowns built as well.

**Comment by paolodamico** [comment]
Some very early thoughts, pending results of this sprint. List is numbered to facilitate discussion, it's **not prioritized**.

1. #3548 (**raw query support**). _Rationale:_ From ~4 weeks in customer support, this seems to be becoming more and more important. There seems to be more cases of users having analytics needs that fall out of the scope of our base features.
2. #2247 (**group analytics**). _Rationale:_  Enables a whole new realm of analytics that better suits certain types of companies, requested multiple times. Strongly in line with feature parity.
3. #3408 (**save reports**). _Rationale:_  Saving graphs will make it easier to share insights, collaborate, and keep coming back easily to get new insights. We know from user feedback this feature is valuable, but with the current UI/UX only about 4-5% of WAUs reach the history page.
    - As a side note, it proved impossible to measure how many times a user has navigated from the history page to an insight. We need better instrumentation here.
4. #4200 (**weekly email report**). _Rationale:_ This was introduced to test our hypothesis to have an out-of-environment engagement loop, help users come back (e.g. getting an email that says you're active users increased by x% will probably prompt you to jump in and understand what's going on).
5. Depending on the progress and results of #4050, we'll need to continue iterating this, plus potentially start including a few other improvements: #4156 (**new UI**), #2760 (**filtering experience**).
6. Still top priority I would bring forward tackling all the **data quality / performance issues** we have on the table.

**Comment by liyiy** [comment]
I'm working on #3551 this week and it'll probably extend into next week

**Comment by buwilliams** [comment]
I'm working on #3149 and expect to finish the coding in the next couple of days but I suspect there will be lingering cases that will need to be handled along with updating the docs. Also, I really want to take a shot at #3548 **raw query support** but I'm limited in the amount of progress I can make there without Clickhouse. I could definitely work the frontend side of that.

**Comment by paolodamico** [comment]
This has served its purpose, closing now.

I've checked with @liyiy and seems we already have the mockups we need for this release.
For the query experience, I think we'll just finish off the current changes and for the next set of changes I'll work out some mockups first.
