### ISSUE TITLE
Deleting projects & orgs timeout error

### ISSUE THREAD

**Issue by paolodamico** [PostHog/posthog#4191]
## Bug description

Deleting a project or an organization can't take a long time. A lot of data needs to be identified and purged. This is further complicated when running Clickhouse as it can take longer. This process can exceed the timeout limit on a request.

## Expected behavior

- We should handle cases where this might take a long time. Probably the best approach would be to execute this async.
- We should communicate very clearly to users what's going on and what to expect. If we do keep this synchronously we should add a note explaining it may take a long time, show a more prominent loading indicator, and extend the timeout period.

## How to reproduce

1. Create a project, add 50k+ events.
2. Try to delete it.

## Environment

- [X] PostHog Cloud. Only replicated on cloud but probably an issue that affects self-hosted too.
- [ ] self-hosted PostHog, version/commit: _please provide_

## Additional context

Reported from a user who couldn't delete a project they had.

**Comment by paolodamico** [comment]
I believe this was an issue with CH and you already addressed @macobo ?

**Comment by macobo** [comment]
Fixing this yeah depends on https://github.com/PostHog/posthog/issues/4242

**Comment by macobo** [comment]
I believe this is fixed with changes @EDsCODE did ages ago: https://github.com/PostHog/posthog/pull/3042
