### ISSUE TITLE
Adding event breaks action editing and viewing

### ISSUE THREAD

**Issue by kpthatsme** [PostHog/posthog#4195]
## Bug description
I added an event (that exists) to an action, and now my action hangs forever.

I added an insight viewed event

w/ filters `insight == RETENTION` and `same_retention_and_cohortizing_event = false` – this appears to have broken my action where it does not load and I cannot edit it.

Cannot reproduce this same behavior locally.

## Expected behavior
- The action loads if the schema is correct.
-  If there's erroneous data it should load and let me edit it.

## How to reproduce

1. Create an action on Posthog cloud, in our main app
2. Add 'insight viewed' with filters `insight == RETENTION` and `same_retention_and_cohortizing_event = false`
3. The action will spin forever

## Environment

- [x] PostHog Cloud
- [ ] self-hosted PostHog, version/commit: _please provide_

## Additional context

[Sentry error](https://sentry.io/organizations/posthog/issues/2378948964/?project=1899813&referrer=slack)

Console errors 
<img width="1607" alt="Screen Shot 2021-05-03 at 5 45 39 PM" src="https://user-images.githubusercontent.com/5965891/116950024-b0d7a280-ac38-11eb-93c8-245390240532.png">
<img width="1167" alt="Screen Shot 2021-05-03 at 5 51 34 PM" src="https://user-images.githubusercontent.com/5965891/116950026-b208cf80-ac38-11eb-96e1-6a8f018f650a.png">

**Comment by kpthatsme** [comment]
@EDsCODE not sure if this is your team or @mariusandra

**Comment by samwinslow** [comment]
Unsure about the cause, but dropping in to link to the Sentry report: https://sentry.io/organizations/posthog/issues/2245617126/

**Comment by timgl** [comment]
Issue seems to be that `vaction_props_4912_1` isn't an array, but then it gets put into a `has()` that requires an array (4th line from the top).

![image](https://user-images.githubusercontent.com/1727427/117020178-7df3e400-acf6-11eb-8754-4c5dabf36be4.png)

haven't been able to reproduce locally. It might be because of an old filter?
