### ISSUE TITLE
Deleted users cannot sign up again

### ISSUE THREAD

**Issue by VengefulAncient** [PostHog/posthog#4196]
## Bug description

Trying to sign up via a new invite for the same email as a previously deleted user does not work.

## Expected behavior

Signup succeeds as usual.

## How to reproduce

1. Invite a user by email
2. Sign up using the created invite
3. Delete the user in web UI (`/organization/members`)
4. Invite the same email again
5. Try to sign up again

## Environment

Self-hosted Posthog v1.4.11 (deployed via Helm chart v.1.22.0).

## Additional context

Browser network console logs a `500` from `/api/signup`.

Posthog web Kubernetes pod logs a very unhelpful `Internal Server Error: /api/signup/<UUID omitted>/`.

Finally, Postgres logs reveal the actual cause of the problem: table `posthog_user` still retains the deleted user's row, which is what apparently prevents re-sign-up with the same email, since upon re-sign-up attempt PG logs the following:
```
ERROR: duplicate key value violates unique constraint "posthog_user_email_af269794_uniq"
DETAIL: Key (email)=(<email omitted>) already exists.
STATEMENT: INSERT INTO "posthog_user" ("password", "last_login", "first_name", "last_name", "is_staff", "is_active", "date_joined", "current_organization_id", "current_team_id", "email", "temporary_token", "distinct_id", "email_opt_in", "anonymize_data", "toolbar_mode") VALUES (<values omitted>) RETURNING "posthog_user"."id"
```

## Workaround

Manually delete the user from `posthog_user` table.

**Comment by Twixes** [comment]
Hey! This is expected behavior – users deleted from organizations are not deleted from the instance. To readd a user, ask them to log in first (their credentials will be the same, it's just that they will have no real access to to the PostHog instance).
