### ISSUE TITLE
Update insights instrumentation

### ISSUE THREAD

**Issue by kpthatsme** [PostHog/posthog#4213]
## Is your feature request related to a problem?

In order to expand the definition of 'discovered learning' we need to proxy 'meaningful usage' across all our insights types.

Currently we're missing event + action filter counts which are important for meaningful usage with stickiness and sessions charts.

## Describe the solution you'd like
Record total count of filters applied on actions and events in a query.

**Comment by paolodamico** [comment]
We now do this in `insight analyzed` & `insight viewed`
