### ISSUE TITLE
Support event ingestion if database goes down

### ISSUE THREAD

**Issue by paolodamico** [PostHog/posthog#4222]
This was reported by a user today who was looking to upgrade / change DB settings that required a restart and downtime.

If the DB goes down, I believe we would stop ingesting data (because we'd be unable to validate the API key in the `/capture` endpoint). Ideally we would have a failsafe to queue the events somewhere (Kafka/Redis) until the DB comes back online.

Alternatively, we could consider storing/caching API keys somewhere else to be able to continue event ingestion even if the DB is down.

**Comment by Twixes** [comment]
I believe we've made this the case with recent work on resiliency and reducing the dependency on Postgres in the critical path.
