### ISSUE TITLE
frontend/e2e testing options

### ISSUE THREAD

**Issue by buwilliams** [PostHog/posthog#4238]
## Developer quality of life feature

Are there better options for frontend/e2e testing? Reasons for consideration:

1. Current e2e tests produce a large set of false positives (errors that aren't errors) since the frontend is constantly changing
2. Our Cypress tests are quite slow, ~20+ minutes for current tests

## Describe the solution you'd like

An ideal solution would have the following properties:
- Tests execute quickly on a developers machine, <5 minutes
- They are reliable. They do not frequently produce false positives.

## Describe alternatives you've considered

- Discard e2e tests altogether
- Determine how to speed up Cypress
- Research latest industry thinking on this subject

## Additional context

This originated in a slack thread from 5/6/2021:

> Buddy: Just diving into e2e tests. So far they are slow and seem to be consistently breaking. Would be good to think through this at some point.
> Eric: Yeah agreed. It’s a pretty open ended problem atm because we’ve tried a few variants to testing frontend but so far none have been super successful imo especially because of how kea ties a lot of overhead into components
> Buddy: It's more than that. The frontend is volatile since it's subject to frequent change. I have yet to see anything beyond unit tests for frontend work on a product in flux. It's a different story if the product is really stable.
> Tim: I’ve just fixed a couple of tests, cypress has a super useful dashboard that shows flaky tests but my preference would be for a small amount of e2e tests combined with unit tests but i am by no means a frontend expert
> Eric: Oh yeah I mean we can’t even unit test that effectively if we wanted to because the components themselves have a bunch of related logics that would need mounting for each unit test
> Buddy: The first principle question is: how does this tool provide value? or what value do I want? In the case of a constantly changing UI, you get far more false failures than you do actually catching errors you care about. So basically, go fix a bunch of errors that aren't really errors. That's a waste.
> Paolo I would also say that the E2E have caught significant bugs in critical flows in the past, so there’s definitely value there

**Comment by kpthatsme** [comment]
IMO we need two critical areas of testing:

1. Backend query correctness. Sets of tests against our query logic for all of our charts. All they do is pass in the same inputs and compare the query results I.e. store the expected JSON, compare with the query response – across various date filters, etc and the result should always be the same.

2. UI tests – basic tests that verify key elements on our interface are working. i.e. you can actually change the date filter and get a response. We don't care about data correctness in these tests, just that the front end interactions are working.

**Comment by buwilliams** [comment]
I agree with the first point but I'm reserved on the second, maybe if they are basic. I lean toward them being more trouble than they are worth.

**Comment by EDsCODE** [comment]
We have a fair amount of tests for #1. There still are edge cases that could make the tests more comprehensive and combinations that could cause the query to be incorrect.

**Comment by fuziontech** [comment]
Turns out frontend testing is really hard. We spent some time on this a while ago and could probably afford to revisit.

https://posthog.com/blog/cypress-end-to-end-tests

There are a few things we can do to immediately speed this up, but if it is true that there are more false positives than regressions being catched maybe it is not worth investing any more time into it.

**Comment by paolodamico** [comment]
I believe the strategy for frontend testing has evolved a lot and this no longer seems relevant, closing.
