### ISSUE TITLE
Release 1.26.0 1/2

### ISSUE THREAD

**Issue by mariusandra** [PostHog/posthog#4257]
### Team Extensibility 

**Hero's journey:**
- Michael: Action event matching in plugin server PostHog/plugin-server#235
- Neil: Capture plugin capabilities https://github.com/PostHog/plugin-server/issues/379
- Yakko: Retries to ~~S3, BigQuery~~ and Rudderstack plugins, ~~create Redshift plugin (with retries)~~ PostHog/plugin-repository#21 PostHog/plugin-repository#15
- Marius: Job queue next steps: retry processEvent PostHog/plugin-server#273 , dead letter queues PostHog/plugin-server#256 , S3 jobs queue PostHog/plugin-server#364 , Kafka data loss PostHog/plugin-server#348

**Two main side-quests**
- ~~Neil: Python library improvements PostHog/posthog-python#24 PostHog/posthog-python#16~~
- ~~Neil: Plugins should not be able to change team_id PostHog/plugin-server#363~~
- ~~Yakko: Disable plugins that crash all the time PostHog/plugin-server#279~~
- ~~Yakko: Info about the job queue onto the instance status page PostHog/plugin-server#365~~
- Michael: "New member joined your organization" email https://github.com/PostHog/posthog/pull/3509
- Michael: Plugins in the onboarding flow https://github.com/PostHog/posthog/issues/3764
- Marius: Get a handle on the errors again.
- Marius: Self-Hosted Github Action Runners https://github.com/PostHog/product-internal/issues/43

### Core Analytics

- [New filtering experience/new UI](https://github.com/PostHog/posthog/issues/4050) - Sam & Paolo
- Data quality issues. Make a decision on [merging users](https://github.com/PostHog/plugin-server/issues/335). Debug funnel [issues](https://github.com/PostHog/product-internal/issues/37)  - Eric
- [Dashboard collaboration](https://github.com/PostHog/posthog/issues/3551) - Li (Paolo product support)
- [Improve environment toggles](https://github.com/PostHog/posthog/pull/4206) (while waiting for new macbook) - Buddy
- [Group analytics](https://github.com/PostHog/posthog/issues/2247) - (Eric & Buddy)
- Feature gap analysis (Paolo)
- Focus customers bug fixes (Paolo & Eric)

### Infra & deployments

- Continue onboarding customers (2ish) 1 for each TZ
- Tiina - Backups for clickhouse
- Karl - Permissions for Clickhouse-operator audit (reduce to only needed)
- James & Karl - Collapsing merge tree for person and person_distinct_id tables
- James - Netdata Performance Issues
- Plan/document how to maintain Clickhouse

**Comment by mariusandra** [comment]
### Team Extensibility 

**Hero's journey:**
- Michael: Action event matching in plugin server PostHog/plugin-server#235
- Neil: Capture plugin capabilities PostHog/plugin-server#165
- Yakko: Retries to BigQuery and Rudderstack plugins, create Redshift plugin (with retries) PostHog/plugin-repository#21 PostHog/plugin-repository#15
- Marius: Job queue next steps: retries for S3 plugin, retry processEvent PostHog/plugin-server#273 , dead letter queues PostHog/plugin-server#256 , S3 jobs queue PostHog/plugin-server#364 , Kafka data loss PostHog/plugin-server#348

**Two main side-quests**
- Neil: Python library improvements PostHog/posthog-python#24 PostHog/posthog-python#16
- Neil: Plugins should not be able to change team_id PostHog/plugin-server#363
- Yakko: Disable plugins that crash all the time PostHog/plugin-server#279
- Yakko: Info about the job queue onto the instance status page PostHog/plugin-server#365
- Michael: "New member joined your organization" email https://github.com/PostHog/posthog/pull/3509
- Michael: Plugins in the onboarding flow https://github.com/PostHog/posthog/issues/3764
- Marius: Get a handle on the errors again.
- Marius: Self-Hosted Github Action Runners https://github.com/PostHog/product-internal/issues/43

**Comment by EDsCODE** [comment]
**Core Analytics**

- [New filtering experience/new UI](https://github.com/PostHog/posthog/issues/4050) - Sam & Paolo
- Data quality issues. Make a decision on [merging users](https://github.com/PostHog/plugin-server/issues/335). Debug funnel [issues](https://github.com/PostHog/product-internal/issues/37)  - Eric
- [Dashboard collaboration](https://github.com/PostHog/posthog/issues/3551) - Li (Paolo product support)
- [Improve environment toggles](https://github.com/PostHog/posthog/pull/4206) (while waiting for new macbook) - Buddy
- [Group analytics](https://github.com/PostHog/posthog/issues/2247) - (Eric & Buddy)
- Feature gap analysis (Paolo)
- Focus customers bug fixes (Paolo & Eric)

**Comment by fuziontech** [comment]
Infra
Retro
- Outage for clickhouse due to queued mutations on `person` table causing degraded performance
- Tiina onboarded 🎉🎉🎉🎉
- AWS Cost audit - Removed a bunch of EBS
- Client Deploys 

Upcoming
- Tiina - Backups for clickhouse
- Karl - Permissions for Clickhouse-operator audit (reduce to only needed)
- James & Karl - Collapsing merge tree for person and person_distinct_id tables
- James - Netdata Performance Issues
- Continue onboarding customers (2ish) 1 for each TZ
![image](https://user-images.githubusercontent.com/391319/117469255-5b3a1900-af0a-11eb-966d-69aa845262c1.png)

**Comment by fuziontech** [comment]
Current state of D & I:
![image](https://user-images.githubusercontent.com/391319/119155924-8a6f8080-ba08-11eb-875b-1b1644f764f4.png)

**Comment by Twixes** [comment]
Sprint over.
