### ISSUE TITLE
PostHog Opt in for emails after deployments

### ISSUE THREAD

**Issue by Tannergoods** [PostHog/posthog#426]
***Thank*** you for your feature request - we love each and every one :)

**Is your feature request related to a problem? Please describe.**
When someone deploys PostHog they must do so with an email address (although we do not verify this). If they self host we would like to notify those users of updates and new features.

**Describe the solution you'd like**
A short opt in for update emails:

"We would like to keep in touch with you about updates, new features and releases, you can easily unsubscribe at anytime."

**Describe alternatives you've considered**
A shorter opt in could be useful - but we should have some form of opt in

**Additional context**

**Comment by timgl** [comment]
Text
"Tick this box to receive security and feature updates via email. You can easily unsubscribe at any time."

This needs to be a tickbox that's turned off by default. Need to pass that through as a variable to the `posthog.capture` call in the backend.
