### ISSUE TITLE
Failing to develop locally

### ISSUE THREAD

**Issue by DimitrisMazarakis** [PostHog/posthog#4270]
## Bug description

I am trying to develop locally but when I type the command ``` DEBUG=1 ./bin/start ``` this is what happens

![fail](https://user-images.githubusercontent.com/56391437/117583925-9eff6f00-b112-11eb-90eb-22e69ea0b390.png)
![fail 2](https://user-images.githubusercontent.com/56391437/117583944-b76f8980-b112-11eb-819c-662c06ec95d7.png)

I have tried both virtualenv and docker way but the result is the same. Also, with the docker way when I type the command  ``` docker-compose -f docker-compose.dev.yml up  ``` this is what shows up at the end and not the ✔ Webpack: Compiled successfully.

![fail4](https://user-images.githubusercontent.com/56391437/117584336-08807d00-b115-11eb-9deb-35a4a5e23ada.png)

## Expected behavior

To succesfully see the app at the http://localhost:8000

## How to reproduce

Follow the steps [here](https://posthog.com/docs/developing-locally)

## Environment

posthog/posthog:latest-release

**Comment by DimitrisMazarakis** [comment]
Does anyone have an idea of what may be the cause of the problem?

**Comment by Twixes** [comment]
Hey! Some diagnostic questions:
1. Related to local `./bin/start`:
Do you have Postgres running locally? For ./bin/start you need it running on port 5432, with no login credentials required, with database `posthog` created.
Also, it looks like you're running Windows, which is why you may see these script errors – we unfortunately don't support Windows, Unix-like systems such as macOS or Linux are recommended.
1. Related to Docker (which runs a Linux VM so should be fine):
How much memory do you allow Docker on your machine?
What logs are there _before_ `posthog_backend_1 exited with code 1`?

**Comment by DimitrisMazarakis** [comment]
Hello and thanks for he response @Twixes !

For the first part I thought I had postgres because I runned ``` pip install postgres ``` but maybe I need to do it with another way.

![postgres](https://user-images.githubusercontent.com/56391437/117631155-9f385280-b184-11eb-92dc-becfe6eaff07.png)
 
So if I understood right in order to run posthog with the command ```.bin/start : ``` I should run with unix-like software right?

And for the docker part I haven't used docker before and I don't know how to check how memory I allow to docker. After googling it I didn't found something specific to check the permitted memory of docker. Can you give me some directions on this part?
Before ``` posthog_backend_1 exited with code 1 ``` there are the logs you see on the screenshot below.

![seeeend](https://user-images.githubusercontent.com/56391437/117631073-8a5bbf00-b184-11eb-9001-ca30d67b9317.png)

**Comment by Twixes** [comment]
Hi! I'll close this since we've since updated our development process and have a reliable guide for it over here: https://posthog.com/docs/contribute/developing-locally. Feel free to post if you ever encounter any issues.
