### ISSUE TITLE
Hotkey function not working for insights page

### ISSUE THREAD

**Issue by DimitrisMazarakis** [PostHog/posthog#4273]
## Bug description

I saw at the code that for the insights page there are hotkeys for each tab to press but when I am on the insights page and I press the letters nothing is happening.

![hotkeysssssssssssss](https://user-images.githubusercontent.com/56391437/117633617-e32c5700-b186-11eb-93d3-c0918c095eb8.png)

## Idea for History button

We could also add the hotkey function for the history button in the insights page

## Expected behavior

When you are at the insights page to you can press for example 'f' and then it will change to the Funnels tab.

## How to reproduce

1. Go to insights page
2. Press 'f' or 'p' or 's' or 'r' or 'k' or 'l' and nothing will change

## Environment

- [ ] Google Chrome

**Comment by Twixes** [comment]
Hey! The hotkeys features is under a feature flag, as visible in the code, which means it's not rolled out completely yet.
Thanks for the History hotkey idea, it's interesting. @paolodamico Thoughts on that, or on rolling hotkeys out more?

**Comment by paolodamico** [comment]
We just rolled out recently to a percentage of users for testing, we'll take a look at results next week to see if we can finish the rollout or adjustments are needed. @DimitrisMazarakis if you want to test out this feature, shoot us a message on Slack with your email and we're happy to add you to the test group.

**Comment by DimitrisMazarakis** [comment]
@paolodamico I would be very happy to test this out! I joined slack community but where should I write this message and with what tag because there many groups? Btw my mail is dimitrismazarakis77@gmail.com

**Comment by paolodamico** [comment]
Cool! I've added you to the test group in the meantime. I saw your PR, thanks for the contribution, will take a look tomorrow or on Monday to see if we can ship that already.

**Comment by DimitrisMazarakis** [comment]
Perfect, thank you @paolodamico! One question, where can I find this test group? Because I have not received an email yet.

**Comment by paolodamico** [comment]
Oh sorry for the confusion, you don't get a notification directly, but rather you'll start seeing the hotkeys feature automatically in your app.

**Comment by DimitrisMazarakis** [comment]
It's okay, I'm new to this project and I don't have previous experience with other open source projects so I don't quite know how things run, but I think I will get used to it. Anyway, I will check the hotkey feature on the weekend!
