### ISSUE TITLE
Display a message on Sessions page if recording is not configured

### ISSUE THREAD

**Issue by samwinslow** [PostHog/posthog#4284]
When a user has not opted into Session Recording and/or has not configured Permitted Domains/URLs in Project Settings, display a notice on the Sessions page with a link to Project Settings.

Below, no sessions with recordings are available because I have not opted in and also have no permitted URLs.

<img width="1322" alt="Screen Shot 2021-05-10 at 11 21 24 AM" src="https://user-images.githubusercontent.com/4645779/117683501-220bde00-b182-11eb-91fb-b9ddf4b41c16.png">

## Additional context

Came up during testing of release 1.25, but doesn't block that release.

**Comment by paolodamico** [comment]
This already exists in the recordings page and some recent work may even make this a moot point. Closing.
