### ISSUE TITLE
Retention users pop up is unclear

### ISSUE THREAD

**Issue by liyiy** [PostHog/posthog#4289]
## Is your feature request related to a problem?

Going to Insights -> Retention -> a box that isn't 0% shows this:

<img width="1035" alt="Screen Shot 2021-05-10 at 10 38 03 AM" src="https://user-images.githubusercontent.com/25164963/117677190-3a78fa00-b17c-11eb-9308-ee1b6dc7844e.png">

## Describe the solution you'd like
- Column name of "user id" or something
- "Close" or "X" button on the top right of the pop up instead of right hand corner
<img width="1284" alt="Screen Shot 2021-05-10 at 11 55 30 AM" src="https://user-images.githubusercontent.com/25164963/117688355-b1b38b80-b186-11eb-8632-01faaff055f1.png">
- Refresh button disappears and never comes back after the first time you click on it unless you change tabs (not sure if this is intentional)
<img width="893" alt="Screen Shot 2021-05-10 at 11 57 33 AM" src="https://user-images.githubusercontent.com/25164963/117688804-21c21180-b187-11eb-9626-b62a50c8eb88.png">

**Comment by abhijitghate** [comment]
created a PR here - https://github.com/PostHog/posthog/pull/4325
Not sure about the `refresh` bit. @liyiy Please have a look
