### ISSUE TITLE
(Email) filters not working on events table

### ISSUE THREAD

**Issue by yakkomajuri** [PostHog/posthog#4292]
## Bug description

User reported `email doesn't contain/equal` filter is not working on their events table. I've confirmed this.

## Expected behavior

Should filter out users.

## How to reproduce

1. Ask Yakko on Slack for private user details
2.
3.

## Environment

- [ ] PostHog Cloud
- [ ] self-hosted PostHog, version/commit: _please provide_

**Comment by Twixes** [comment]
This seems to work now.
