### ISSUE TITLE
Reorganize insight logics

### ISSUE THREAD

**Issue by EDsCODE** [PostHog/posthog#4293]
## Is your feature request related to a problem?

*Please describe.*

As our insights page has grown, we've iterate over and extended the insightLogic x trendLogic several times over where it's now quite confusing. Trendslogic is shared by sessions/stickiness/lifecycle but not by retention and paths and funnels.

## Describe the solution you'd like
Split out the logic so that each insight has its own dedicated logic or unify all of them under a single logic that is easy to work with

## Describe alternatives you've considered
leaving it as is would be more efficient for the short term

## Additional context
this confusion is causing quite a few bugs such as #4282 and the logics are unwieldy

**Comment by timgl** [comment]
Agree. Was talking to @liyiy about this, I'd be nice to have the URLs be the ID (or hash) of the Insight (DashboardItem), that way there's a stronger link between the two

**Comment by Twixes** [comment]
The logics are still (or maybe even more so) due for some refactoring, but now it's @mariusandra who's mostly involved in this, so I'm leaning towards closing this. Also, your point @timgl will be fully realized when #7201 goes in!
