### ISSUE TITLE
PostHog events are not refreshed

### ISSUE THREAD

**Issue by mteterel** [PostHog/posthog#4295]
## Bug description

Recently I implemented new event tracking on our app, but the events are not showing up in PostHog UI. I tried to clear the Redis cache as well as restarting the Docker containers (it worked once) but it doesn't show the new events in the dropdowns.

## Expected behavior

Events should show up in the filters in Insights, Events etc...

## How to reproduce

1. Capture a new event
2. Load Posthog Events page
3. Look in the dropdown

## Environment

- [ ] PostHog Cloud
- [X] self-hosted PostHog, version/commit: 1.24.0 via Docker

## Additional context

None.

**Comment by timgl** [comment]
Hi there. We'd need quite a bit more information to help you debug this issue. If you can, could you share

- The website you're sending events from
- Are you seeing any errors when sending events?
- Are you seeing existing events in the dropdown (ie Pageview) and is data coming in from then
- Do the events show up in the 'Events' page in the sidebar?
- Have you tried hard refreshing the page?

**Comment by id6tm-mteterel** [comment]
> Hi there. We'd need quite a bit more information to help you debug this issue. If you can, could you share
> 
> * The website you're sending events from
> * Are you seeing any errors when sending events?
> * Are you seeing existing events in the dropdown (ie Pageview) and is data coming in from then
> * Do the events show up in the 'Events' page in the sidebar?
> * Have you tried hard refreshing the page?

Hello there !

There is no errors shown when I'm sending events. They appear in the Event list on Posthog UI and they are tracked correctly but I cannot filter them. Events like Pageview and custom events that are previous to the new ones appear correctly as well.

I tried to hard refresh the page and going through a private browsing window but it doesn't change anything. Flushing the Redis database didn't help either.

Thanks for your help !

**Comment by timgl** [comment]
Great thanks!

Are you seeing any errors in your server logs? Is your worker running?

**Comment by id6tm-mteterel** [comment]
No, there is no errors in my Posthog log, everything seems to work fine except for the events filters being outdated. What do you mean by the worker ? I'm running on Docker and all services (web, db, redis) are up and running.

The posthog_eventdefinition table in the DB does not contain the new events either.

**Comment by timgl** [comment]
@mteterel Is there any chance you could give me access to your posthog instance so I can debug? tim@posthog.com

**Comment by Twixes** [comment]
Hey @mteterel, is the issue still there?

**Comment by Twixes** [comment]
I suppose this is no longer a problem.
