### ISSUE TITLE
Minor bugs with querying experience

### ISSUE THREAD

**Issue by paolodamico** [PostHog/posthog#4301]
Some bugs in the querying experience. Related to shipping #4050 (latest PR #4296), but previously existing.

1. ~~There's some strange behavior when switching insights (see how filters are sometimes preserved, when they shouldn't if you're moving to a new insight).~~
![image](https://user-images.githubusercontent.com/5864173/117838291-0dd1ea80-b22f-11eb-9f67-a04a2d8a9ab2.gif)

2. When I navigate with the arrow keyboards, the container doesn't scroll when I'm viewing properties outside the container present in the view.
![image](https://user-images.githubusercontent.com/5864173/117840163-c3ea0400-b230-11eb-903c-cedc5560d2b4.gif)

3. ~~When you have an insight opened from a dashboard and then click on the "Insights" main menu item again to get a fresh insights page, you still see the dashboard item. Fixed by #5502~~

![image](https://user-images.githubusercontent.com/5864173/118018681-f36e3e80-b30c-11eb-8f98-3f74638939c9.gif)

4. ~~Lifecycle chart should only allow you to see Unique users (i.e. math aggregation doesn't make sense).~~ fixed

**Comment by samwinslow** [comment]
Just to gather / share more context around this issue, it looks like none of the filters on the funnels tab are persisted when navigating away. Confirming that this happens on master from before the earliest pr related to #4050 was merged.

The pathname is also suspiciously short considering we rehydrate state from URL query params: `/insights?insight=FUNNELS&filter_test_accounts=true&display=FunnelViz&properties=%5B%5D`.

I wonder why properties is an empty array? (`%5B%5D` = `[]`).

@EDsCODE gave a helpful intro to @buwilliams and I regarding filters, and (if it's okay to speak for both of us) it seemed like we were confused by how the Insights logic is very interconnected across these views. As the feature sets and layouts among these views diverge, as they are starting to do in https://github.com/PostHog/posthog/issues/4050#issuecomment-837729363, I think it'll be more important to separate and simplify.

Perhaps in the process of separating out these views, the solution to this will reveal itself.

**Comment by samwinslow** [comment]
#3355 is probably related.

EDIT: Fat-fingered closing the issue; reopening.

**Comment by paolodamico** [comment]
Adding another one, see updated description

**Comment by mariusandra** [comment]
The first issue is probably solved with https://github.com/PostHog/posthog/pull/4939

**Comment by paolodamico** [comment]
Updated the issue, this is the only bug still outstanding,
> 2. When I navigate with the arrow keyboards, the container doesn't scroll when I'm viewing properties outside the container present in the view.

**Comment by liyiy** [comment]
@paolodamico hmm I don't seem to see this bug anymore, especially on the new property filters, where do you see it still?

**Comment by paolodamico** [comment]
So I actually could only find this in the retention tab and it is indeed due to the fact that we have the old filter. Maybe worth fully clearing the old filter and using the new taxonomic filter everywhere and we can close this. Wdyt?

<img width="859" alt="" src="https://user-images.githubusercontent.com/5864173/128790897-3ab48e26-a36e-40c1-98af-cdbfde392b82.png">

**Comment by alexkim205** [comment]
Looks like this one can be closed out now after #5536 :)
