### ISSUE TITLE
Retention queries w/ cohorts don't complete

### ISSUE THREAD

**Issue by kpthatsme** [PostHog/posthog#4305]
## Bug description

Whenever I try to add a cohort as a filter on a retention chart, the chart doesn't seem to load. 

Takes a while and then comes back with the generic error message. 

## Expected behavior
I'd expect the cohort to be applied as is done across other chart types -or- for the option to not exist if we can't support it.

## How to reproduce

1. Load up a [retention chart](https://app.posthog.com/insights?target_entity=%7B%22id%22%3A%22%24pageview%22%2C%22name%22%3A%22%24pageview%22%2C%22type%22%3A%22events%22%2C%22order%22%3A0%7D&returning_entity=%7B%22id%22%3A5043%2C%22name%22%3A%22App%20Pageview%20-%20Logged%20in%22%2C%22type%22%3A%22actions%22%2C%22order%22%3A0%7D&period=Week&retention_type=retention_recurring&display=ActionsTable&properties=%5B%7B%22key%22%3A%22id%22%2C%22value%22%3A836%2C%22type%22%3A%22cohort%22%7D%5D&insight=RETENTION&total_intervals=11&filter_test_accounts=false)
2. Add a cohort filter
3. Wait...

<img width="1512" alt="Screen Shot 2021-05-11 at 12 29 02 PM" src="https://user-images.githubusercontent.com/5965891/117873362-8ac38b00-b254-11eb-92d7-17f72e839686.png">

## Environment

- [ ] PostHog Cloud
- [ ] self-hosted PostHog, version/commit: _please provide_

**Comment by EDsCODE** [comment]
#4335 could potentially solve this for any cohort query

**Comment by mariusandra** [comment]
I think this ticket belongs in the Core Analytics team. Moved just now.

**Comment by macobo** [comment]
I tried reproducing this to no luck. Things do seem to load. 

cc @kpthatsme - is there a particular cohort that causes this?

**Comment by kpthatsme** [comment]
Hey @macobo - looks like it was the "Used app in 30d" cohort - I just tried it and it loaded (though it did take quite some time). 

Here's the [chart](https://app.posthog.com/insights?target_entity=%7B%22id%22%3A%22%24pageview%22%2C%22name%22%3A%22%24pageview%22%2C%22type%22%3A%22events%22%7D&returning_entity=%7B%22id%22%3A%22%24pageview%22%2C%22type%22%3A%22events%22%2C%22name%22%3A%22%24pageview%22%7D&period=Day&retention_type=retention_first_time&display=ActionsTable&properties=%5B%7B%22key%22%3A%22id%22%2C%22value%22%3A836%2C%22type%22%3A%22cohort%22%7D%5D&filter_test_accounts=true&insight=RETENTION&events=%5B%7B%22id%22%3A%22%24pageview%22%2C%22name%22%3A%22%24pageview%22%2C%22type%22%3A%22events%22%2C%22order%22%3A0%7D%5D&actions=%5B%5D) if you want to see. 

This ticket is from May so it's probably safe to close and re-open if needed! Closing.
