### ISSUE TITLE
Breakdown by attribute property is broken

### ISSUE THREAD

**Issue by buwilliams** [PostHog/posthog#4309]
## Bug description

[Original bug report](https://www.notion.so/PostHog-Issues-f677fedb89a244ed86a82278ca01836f#1c182fef5dc04f4480303be0a42aafa9)

[Video of problem](https://www.loom.com/share/592590b0d7a4489c9ae25996ac9c42df?t=9)

- filtering OUT internal users increases the event count
- filtering OUT internal users increases the event count

## Expected behavior

- Event counts are correct.

## How to reproduce

See video above.

## Environment

- [x] PostHog Cloud
- [ ] self-hosted PostHog, version/commit: _please provide_

## Additional context

Originated from customer via Slack.

**Comment by EDsCODE** [comment]
Need help deciding best way to decide which properties to include on breakdown. Currently, when breaking down given a single event, it's clear that it will be most helpful to find the top X values of the breakdown property requested and then give the breakdown of the event on those values. For example, if the event is $pageview and the breakdown property is 'city', we would breakdown across the top 20 cities where $pageviews have been happening.

However, when provided multiple events (for example: $pageviews and $user_signed_up), the top 20 cities for each event could be different. Do we display this as is? Or is there a better way to decide on these values

**Comment by EDsCODE** [comment]
Will proceed with displaying the top 20 per event as this makes the most sense in displaying relevant numbers

**Comment by macobo** [comment]
@EDsCODE what's the state here? What needs to be done, is there a WIP branch somewhere, should someone else on the team pick it up?

**Comment by EDsCODE** [comment]
I think I was about to pick this up but got hung up on a different sprint and then we hopped into funnels mode. It's open for tackling. Mainly just need to make sure breakdown values are correctly determined per event and that this is clear on the UI. Applicable for funnels too
