### ISSUE TITLE
Dashboards discrete grid - consistent layout

### ISSUE THREAD

**Issue by kpthatsme** [PostHog/posthog#4312]
## Is your feature request related to a problem?

Right now you never know what a dashboard is going to look like when you share it with a teammate, as the ordering depends on the browser size.

## Describe the solution you'd like
- Dashboard items should render in generally the same order, no matter the screen width. There should be reasonable breakpoints for charts. 

## Additional context

I think it's an acceptable trade-off to reduce some of the flexibility we have in the free form resizing if it means more consistent sharing of info.

**Comment by paolodamico** [comment]
100%! Originally reported on #2762 from an internal discussion and customer feedback. We should have a strict grid that handles different screen sizes properly (e.g. allowing stacked columns). Particularly, we need to disable being able to drop dashboards anywhere.
