### ISSUE TITLE
Feature Request > Readonly access

### ISSUE THREAD

**Issue by pascalbe-dev** [PostHog/posthog#4316]
## Is your feature request related to a problem?

We plan to have multiple members, who can visit the Posthog UI. However, we would like to have readonly access only for some of the users. This is currently not possible.

## Describe the solution you'd like
Provide any way to make some users have read only access only. A new role for organization members would totally do the job.

## Describe alternatives you've considered

Alternatively, it might make sense to support viewing Dashboards in Posthog by default without being authenticated at all. 

## Additional context
None :)

**Comment by yakkomajuri** [comment]
> Alternatively, it might make sense to support viewing Dashboards in Posthog by default without being authenticated at all.

Hey! This is actually possible. You just need to create a shared link for the dashboard by clicking 'Send or Share' on the top right

**Comment by pascalbe-dev** [comment]
Oh great, thanks for the information. 
That helps me already. 

However, I would like to keep this issue still open, because a readonly user might help others as well. 

I hope, that's fine :)

**Comment by yakkomajuri** [comment]
Yes, please do - I still find the original request to be useful!

**Comment by paolodamico** [comment]
Hey @pascalbe-dev we now support this for dashboards and their underlying insights, would this solve your use case? Are we okay closing this?

**Comment by pascalbe-dev** [comment]
That's great. Thanks. 
I believe this should solve our use case. I changed team, so I'm no longer directly working with Posthog. I'll tell the other team to try it out. 

I'll close it. We will come back to it, if there are further open questions.
