### ISSUE TITLE
clearer user instructions around regex

### ISSUE THREAD

**Issue by jamiehaywood** [PostHog/posthog#4326]
## Is your feature request related to a problem?

When creating a funnel, it would be great if there were clearer instructions on what type of regex format you use. 
- Do you expect users to include the delimiters? 
- Do you support modifiers? 

## Describe the solution you'd like
In the regex input you could have something that looks similar to regextester.com with what you append and prepend (if you do at all)
![image](https://user-images.githubusercontent.com/26779712/118116912-cbe9a580-b3e2-11eb-9e38-5a5996788325.png)

Another good solution could be a tooltip describing the format, and how to test your regex (a link to regextester or something similar)

## Describe alternatives you've considered
N/A

## Additional context
N/A

**Comment by paolodamico** [comment]
Closed in favor of #4680.
