### ISSUE TITLE
Analytics on total session numbers

### ISSUE THREAD

**Issue by paolodamico** [PostHog/posthog#4328]
## Is your feature request related to a problem?

Currently I can see analytics based on session duration, but having total session information would be quite important too.

## Describe the solution you'd like

I'd like to be able to get information on total session number and session information based on unique users (e.g. number of sessions plotted over time).

## Describe alternatives you've considered

Raw SQL?

## Additional context

- Requested by a user.
- This tends to be more web analytics related; however it's still quite helpful for certain products.

**Comment by paolodamico** [comment]
Related +1 from [a user](https://posthog.slack.com/archives/C01J1GRBH29/p1623742805000600) wanting to create funnels based on sessions instead of users. An interesting approach that could help solve this is with group analytics where we group by some session ID. This would require sending a session ID with events, instead of computing it on the server. Could also help for the analytics described here.

**Comment by jmorvill** [comment]
Hi! We're students at the University of Michigan. We had an assignment to contribute to an open source repository. Here are our contributions for this task. We did some testing on our implementation, but this is our first time contributing to a large-scale project. Thank you!

<img width="809" alt="Screen Shot 2024-04-23 at 2 22 46 PM" src="https://github.com/PostHog/posthog/assets/122138793/43725c48-8cd1-4134-9728-3387708695e6">
