### ISSUE TITLE
Smart graph display

### ISSUE THREAD

**Issue by paolodamico** [PostHog/posthog#4330]
## Is your feature request related to a problem?

Currently we default to line chart display for everything. There are quite a few cases where a different default would be more useful. As a user, I would like to ideally not have to think at all of which display to use.

## Describe the solution you'd like

I'd like us to automatically suggest the best display depending on the type of data being graphed. Example: breakdown with few values would probably look best on a pie chart. This would make for one less thing to worry about when the user 

## Describe alternatives you've considered

Keep relying on manual changes.

## Additional context

Related to feature parity too.

**Comment by marcushyett-ph** [comment]
+1

**Comment by clarkus** [comment]
I think this is going to need to be considered in the context of the insight analysis type being visualized. That said, I could see us addressing this problem a few ways:

- Disallow specific visualization types based on the shape of the underlying data. 
- Suggest the most effective visualization types based on the query
- Automatically select the most effective visualization for the query that was defined. 
- This might also serve as some great support documentation that we can cross-link in the product. "How to pick the best visualization for your data" or something?

Here is a super good article and reference sheet on how to select visualizations: https://medium.com/multiple-views-visualization-research-explained/multiple-views-on-how-to-choose-a-visualization-b3ffc99fcddc

**Comment by marcushyett-ph** [comment]
This is a super neat framework. Thanks for sharing @clarkus 

I guess it also highlights that we have some pretty big gaps in visualization capabilities too.
