### ISSUE TITLE
Introduce "Any event" preset

### ISSUE THREAD

**Issue by paolodamico** [PostHog/posthog#4332]
## Is your feature request related to a problem?

Users coming in from different analytics tools have the expectation of having an "Any event" option. We default to "Pageviews" to serve this use case, however it's clearly not the same, plus particularly not useful if you're not tracking a website or have autocapture off.

## Describe the solution you'd like

I'd like us to have the concept of "Any event" where it matches everything for all insights. We would default to this option.

## Additional context

We have to analyze the technical feasibility of this. Might require some complex query building. CC @EDsCODE @buwilliams for input.

**Comment by Twixes** [comment]
Should be pretty trivial, just replacing `event = '$pageview'` with `event != '$snapshot'` in the `WHERE` clause, right?

**Comment by fuziontech** [comment]
User request from user slack:
>Custom events vs auto events : is there a way to disable $pageview and other events like $pageleave and display only custom events in posthog UI console so that when I make an API call through the end point, I only get custom events on json?

Basically the use case here is to be able to filter for only custom events. Block all events that were automatically generated at query time.

A relatively easy way of doing this could be to add `is_autocapture` or `is_custom_event` field and prewhere on `team_id` and that (would need testing still to make sure that is faster tan normal where)

**Comment by macobo** [comment]
What is the desired behavior of "Any event" though? For example in MixPanel it behaves as a breakdown rather than a filter.

**Comment by macobo** [comment]
^ to the question above. What's the desired behavior?

Also note that this might work as a good default in lifecycle - you really care about the number of users, not the particular event in most cases. Though you might need to exclude system events for that.

**Comment by paolodamico** [comment]
Yeah I think we would just need to extend @Twixes proposal to exclude `$$` events. I think the desired behavior is any event at all, whether PostHog or custom. Motivation came from what Mixp@n3l / @mplitud3 do, seems like an intuitive default and one for which product analytics users are accustomed to.
