### ISSUE TITLE
InsightFilter state mismatch bug on Retention tab

### ISSUE THREAD

**Issue by samwinslow** [PostHog/posthog#4340]
## Bug description

1. Shows `FunnelViz` as dropdown value, which is incorrect
2. Vertical alignment mismatch between the two dropdowns

<img width="549" alt="Screen Shot 2021-05-13 at 2 03 31 PM" src="https://user-images.githubusercontent.com/4645779/118171263-27bf2900-b3f9-11eb-8d2d-930e5323f976.png">

Happened on customer call. Opening the issue so I don't lose track of fixing this.

## Environment

- [x] PostHog Cloud
- [ ] self-hosted PostHog, version/commit: _please provide_

**Comment by paolodamico** [comment]
This is no longer happening, closing.
