### ISSUE TITLE
Allow specifying custom units for y-axis

### ISSUE THREAD

**Issue by macobo** [PostHog/posthog#4344]
## Is your feature request related to a problem?

I want to graph some custom values either using formulas or analytics operators and for it to be clear what unit the graph is using - is it $, %, milliseconds or...? I don't want to be making assumptions.

## Describe the solution you'd like

Allow specifying unit for y-axis

## Describe alternatives you've considered

Adding the unit as a dashboard title

## Additional context

How @mplitude does this:

- You select one operator for all events being analyzed. 
- If you choose e.g. active %, the unit automatically changes to %
- For Formulas they allow you to specify your own custom y-axis title :(9

![image](https://user-images.githubusercontent.com/148820/118178087-34b13c00-b43c-11eb-949a-45680c6055f0.png)

For mixp@nel, they don't support this feature at all and encourage using graph titles.

**Comment by macobo** [comment]
Grafana also solves this, but it allows specifying semantic units. E.g. if you say your data is in unit `milliseconds` it automatically shows `hours` on y-axis if that's the most relevant unit.

**Comment by paolodamico** [comment]
+1 from user request today. Allowing to add `$` to better visualize units.

**Comment by clarkus** [comment]
Is the request here just labeling the axis units, or are we also ensuring the value formatting reflects those units. For example, $ / USD implies specific formatting for values.

**Comment by paolodamico** [comment]
The axis labels mostly. I think formatting would be helpful, but probably not as much.

**Comment by pauldambra** [comment]
You can now choose from a set of formats on all Trends insights

![Screenshot 2022-08-08 at 17 06 01](https://user-images.githubusercontent.com/984817/183462783-6ab707ed-fd18-4b31-8e6e-22cfca0c5f2c.png)
