### ISSUE TITLE
UX: Merging sessions insights into trends

### ISSUE THREAD

**Issue by paolodamico** [PostHog/posthog#4348]
## Context
From a couple of usability tests related to the new querying experience, we found out two things:

1. Most users stay only on trends, funnels & retention (in that order, and validated by [data](https://app.posthog.com/insights?insight=TRENDS&actions=%5B%7B%22id%22%3A4310%2C%22math%22%3A%22total%22%2C%22name%22%3A%22KFA%20-%20Insights%22%2C%22type%22%3A%22actions%22%2C%22order%22%3A0%2C%22properties%22%3A%5B%5D%7D%5D&display=ActionsLineGraph&interval=week&breakdown=insight&date_from=-90d&properties=%5B%7B%22key%22%3A%22id%22%2C%22type%22%3A%22cohort%22%2C%22value%22%3A71%2C%22operator%22%3Anull%7D%5D&breakdown_type=event&events=%5B%5D&new_entity=%5B%5D#fromItem=128780&fromItemName=Insights%20-%20Breakdown&fromDashboard=1124)). 
2. Sessions seems like a basic analytics feature, and in line with the concept of an event/action. All users who performed the test attempted to find the information from trends first.

## Details
Should we drop the sessions tab and instead treat sessions as an event/action?
- This would make some analytics more intuitive (particularly #4328; having session analytics on total numbers).
- Current support for average session length would be covered by property aggregation and the distribution by #4347.

Looking for feedback on this. @EDsCODE @kpthatsme @samwinslow @corywatilo

**Comment by corywatilo** [comment]
Would it hurt to keep Sessions but _also_ make it an option within Trends?

What's confusing right now is that a H3ap (or other) user will look for a `Sessions` option from within Trends. If we support that, we reduce that confusion.

My only other concern is that we also have a top-level nav item labeled _Sessions_. So we have Analysis -> Sessions and also Sessions.

**Comment by EDsCODE** [comment]
Were these users keen on using the sessions insight overall? I think it's important to first figure out if maybe our sessions insight just isn't powerful/useful enough and needs more enhancements.

**Comment by paolodamico** [comment]
Re @corywatilo -> I'm thinking if we do this right in trends, we would need not keep the tab, and this would also avoid the confusion with the top-level "Sessions". I think this also downplays the importance of sessions a bit, because they're after all more useful for web analytics rather than product analytics. Though overall, I have a hunch this would increase session usage overall, just based on the fact that most users stay in that first tab.

Re @EDsCODE, in terms of usage, it's quite similar to retention (see [graph](https://app.posthog.com/insights?insight=TRENDS&actions=%5B%7B%22id%22%3A4310%2C%22math%22%3A%22dau%22%2C%22name%22%3A%22KFA%20-%20Insights%22%2C%22type%22%3A%22actions%22%2C%22order%22%3A0%2C%22properties%22%3A%5B%5D%2C%22math_property%22%3Anull%7D%5D&display=ActionsLineGraph&interval=week&breakdown=insight&date_from=-90d&properties=%5B%7B%22key%22%3A%22id%22%2C%22type%22%3A%22cohort%22%2C%22value%22%3A71%2C%22operator%22%3Anull%7D%5D&breakdown_type=event#fromItem=128780&fromItemName=Insights%20-%20Breakdown&fromDashboard=1124)), though we definitely have some clear shortcomings (e.g. #4328). I do think some basic session analytics will be required, while it's not the main thing for product analytics, it can be quite useful for certain products.

**Comment by samwinslow** [comment]
@EDsCODE It also looks like there is not a significant amount of traffic flow from `app.posthog.com/insights` to `app.posthog.com/insights?insight=SESSIONS` (as measured with User Paths). I would love to verify this with a heatmap test but it isn't loading. By pageviews it looks like Trends, Funnels, and Retention are top three.

**Comment by kpthatsme** [comment]
I definitely agree that Sessions is not a primary type of analysis compared to funnels or trends, and that we're better off investing in feature parity in those areas before prioritizing sessions.

However, I'm not sure if rolling into Trends is the right long-term solution. We might be able to make it work based on today's version of Sessions, but what about the future state? For example if we look at a Sessions type chart in Amplitude, the level of analysis they offer goes pretty deep. I'm not sure if a feature complete version of Sessions would belong under trends.

**Comment by paolodamico** [comment]
Related to this and requested by a user today is the ability to do breakdown operations on sessions. Use case is being able to see sessions analytics "grouped" by a property (in this case company) to understand sessions based on teams rather than on users.
