### ISSUE TITLE
Engagement-based cohorts

### ISSUE THREAD

**Issue by paolodamico** [PostHog/posthog#4349]
## Is your feature request related to a problem?

Currently we can only create property-based, static or very limited action-based cohorts. I may want to create cohorts such as "power users" for users who have performed an event `N` times. A step further would be `N` times in the last `Y` days/weeks/months.

## Describe the solution you'd like

1. I'd like to be able to create cohorts based on events (and not only actions), in case I use custom events.
2. I'd like to be able to specify whatever timeframe I see fit (currently we only support a specific set of options).
3. I'd like to be able to specify the number of times the event should be triggered (currently we default to 1). 

## Describe alternatives you've considered

Attempt to get this information from trends and statically creating short-lived cohorts.

## Additional context

Requested by a user.

**Comment by jamesefhawkins** [comment]
From [a focus user](https://app.hubspot.com/contacts/6958578/deal/3549032247) via DM in slack

> i think being able to build more flexible 'cohorts' could be interesting. At the moment it seems a little limited in terms of what can use do define them.
or maybe its a group of events which is more like a "segment" or something.
basically i could see us applying the same filters on insights again and again and so thinking a cohort/segment would be good to define it one and not have people having to do it multiple times.
e.g. "docker users who we first saw in the last N days who have also claimed a node"
^ so some event properties in there and a dynamic sense of it being based on some time since type logic

> Me: so perhaps being able to create a cohort out of multiple existing cohorts?

> yeah i think that might do the "AND" case
but being able to define a cohort based on an action and some properties those actions might have

**Comment by EDsCODE** [comment]
can implement this depending on success of #4428

**Comment by paolodamico** [comment]
Mockups ready in [Figma](https://www.figma.com/file/gQBj9YnNgD8YW4nBwCVLZf/PostHog-App?node-id=303%3A1298)! **Very open to feedback.** If we implement the changes to the table list too, we would be able to close #2350 as well!


### New dynamic cohort
<img width="1152" alt="new" src="https://user-images.githubusercontent.com/5864173/119895295-776e1c00-bef2-11eb-8ce1-66a1f9cf273e.png">

### New static cohort
<img width="1152" alt="new-static" src="https://user-images.githubusercontent.com/5864173/119895311-7b01a300-bef2-11eb-90fe-59989ccbdae1.png">

### Dynamic cohort (with performed action matching)
<img width="1152" alt="detail" src="https://user-images.githubusercontent.com/5864173/119895328-805eed80-bef2-11eb-9dcb-66da7b31add7.png">

### Dynamic cohort with multiple matching criteria
<img width="1152" alt="multiple" src="https://user-images.githubusercontent.com/5864173/119895346-8523a180-bef2-11eb-9858-c90e21d5cdc7.png">

**Comment by renat-bardeen** [comment]
This is perfect and is exactly what we were looking for. Stellar job with the mochup. Excited for when this lands.

**Comment by EDsCODE** [comment]
Looks good. Building this out

**Comment by renat-bardeen** [comment]
Is there a chance to create a cohort for: 

- returning
- resurrected  
- churned 

Users compared to the previous time period?

This is also a massively helpful metric because it enables you to see behavior that lead users to come back or drop off.

**Comment by paolodamico** [comment]
Re @renat-bardeen are you thinking something static where you take the list of returning/resurrected/churned users in a given week and create a cohort from there or something dynamic depending on the last day/week/month and changes continuously?

**Comment by renat-bardeen** [comment]
https://www.loom.com/share/504a29b4a8374c1aa09af6aa5e02c4c3

**Comment by paolodamico** [comment]
Thanks for sharing @renat-bardeen! I think #2627 should provide an initial approach at least with static cohorts, but definitely having this in a more dynamic way would be super helpful. We actually have that potentially considered in #3366, worth tracking.

**Comment by renatgabitov** [comment]
Gents, is there an approximate timeline for the deployment of this feature?
