### ISSUE TITLE
Difference between funnel trends & funnel steps result across the same time period

### ISSUE THREAD

**Issue by kpthatsme** [PostHog/posthog#4369]
## Bug description

I'm not sure if this is a bug or if there's something with either this funnel query or the underlying data that I'm missing.

Ran this by @EDsCODE once and he agreed something looked off but we haven't come to a definitive example.

## Expected behavior

Look at this funnel, using the [funnel trends view](https://app.posthog.com/insights?insight=FUNNELS&target_entity=%7B%22id%22%3A4912%2C%22type%22%3A%22actions%22%2C%22order%22%3Anull%2C%22name%22%3Anull%2C%22math%22%3Anull%2C%22math_property%22%3Anull%2C%22properties%22%3A%5B%5D%7D&returning_entity=%7B%22id%22%3A3410%2C%22type%22%3A%22actions%22%2C%22order%22%3Anull%2C%22name%22%3Anull%2C%22math%22%3Anull%2C%22math_property%22%3Anull%2C%22properties%22%3A%5B%5D%7D&period=Week&retention_type=retention_first_time&display=ActionsLineGraph&properties=%5B%5D&events=%5B%7B%22id%22%3A%22user%20signed%20up%22%2C%22math%22%3Anull%2C%22name%22%3A%22user%20signed%20up%22%2C%22type%22%3A%22events%22%2C%22order%22%3A0%2C%22properties%22%3A%5B%5D%2C%22math_property%22%3Anull%7D%5D&actions=%5B%7B%22id%22%3A4912%2C%22math%22%3Anull%2C%22name%22%3A%22Discover%20Learning%20-%20core%20analytics%22%2C%22type%22%3A%22actions%22%2C%22order%22%3A1%2C%22properties%22%3A%5B%5D%2C%22math_property%22%3Anull%7D%5D&interval=week&breakdown=product&date_from=-90d&breakdown_type=event&filter_test_accounts=true). 

You can see the last 2 data points, we have pretty low conversion rates.

Now let's look at the same funnel, but as a [Steps of the last 7day](https://app.posthog.com/insights?insight=FUNNELS&target_entity=%7B%22id%22%3A4912%2C%22type%22%3A%22actions%22%2C%22order%22%3Anull%2C%22name%22%3Anull%2C%22math%22%3Anull%2C%22math_property%22%3Anull%2C%22properties%22%3A%5B%5D%7D&returning_entity=%7B%22id%22%3A3410%2C%22type%22%3A%22actions%22%2C%22order%22%3Anull%2C%22name%22%3Anull%2C%22math%22%3Anull%2C%22math_property%22%3Anull%2C%22properties%22%3A%5B%5D%7D&period=Week&retention_type=retention_first_time&display=FunnelViz&properties=%5B%5D&events=%5B%7B%22id%22%3A%22user%20signed%20up%22%2C%22math%22%3Anull%2C%22name%22%3A%22user%20signed%20up%22%2C%22type%22%3A%22events%22%2C%22order%22%3A0%2C%22properties%22%3A%5B%5D%2C%22math_property%22%3Anull%7D%5D&actions=%5B%7B%22id%22%3A4912%2C%22math%22%3Anull%2C%22name%22%3A%22Discover%20Learning%20-%20core%20analytics%22%2C%22type%22%3A%22actions%22%2C%22order%22%3A1%2C%22properties%22%3A%5B%5D%2C%22math_property%22%3Anull%7D%5D&interval=week&breakdown=product&date_from=-7d&breakdown_type=event&filter_test_accounts=true) – you get a much larger conversion rate.

Similarly, looking at the [funnel trends chart over 7 day](https://app.posthog.com/insights?insight=FUNNELS&target_entity=%7B%22id%22%3A4912%2C%22type%22%3A%22actions%22%2C%22order%22%3Anull%2C%22name%22%3Anull%2C%22math%22%3Anull%2C%22math_property%22%3Anull%2C%22properties%22%3A%5B%5D%7D&returning_entity=%7B%22id%22%3A3410%2C%22type%22%3A%22actions%22%2C%22order%22%3Anull%2C%22name%22%3Anull%2C%22math%22%3Anull%2C%22math_property%22%3Anull%2C%22properties%22%3A%5B%5D%7D&period=Week&retention_type=retention_first_time&display=ActionsLineGraph&properties=%5B%5D&events=%5B%7B%22id%22%3A%22user%20signed%20up%22%2C%22math%22%3Anull%2C%22name%22%3A%22user%20signed%20up%22%2C%22type%22%3A%22events%22%2C%22order%22%3A0%2C%22properties%22%3A%5B%5D%2C%22math_property%22%3Anull%7D%5D&actions=%5B%7B%22id%22%3A4912%2C%22math%22%3Anull%2C%22name%22%3A%22Discover%20Learning%20-%20core%20analytics%22%2C%22type%22%3A%22actions%22%2C%22order%22%3A1%2C%22properties%22%3A%5B%5D%2C%22math_property%22%3Anull%7D%5D&interval=week&breakdown=product&date_from=-7d&breakdown_type=event&filter_test_accounts=true) we get similarly different results from the steps over the same time periods.

## How to reproduce

1. View the funnel trends and the funnel steps linked above
2. Observe pretty different conversion rates on the trends chart for each weekly datapoint versus the steps over the same time period

## Environment

- [ ] PostHog Cloud
- [ ] self-hosted PostHog, version/commit: _please provide_

**Comment by timgl** [comment]
@buwilliams weren't you already looking at this?

**Comment by buwilliams** [comment]
Yes, PR is on its way. #4419
