### ISSUE TITLE
/trends url doesn't get updated

### ISSUE THREAD

**Issue by timgl** [PostHog/posthog#437]
***Thank*** you for reporting bugs - we appreciate every single bug report.

**Describe the bug**
When changing any parameters in the /trends view, the url doesn't get updated so I can't send it forward.

**To Reproduce**
1. Go to /trends
2. Change anything
3. URL doesn't update

**Comment by bhavish-agarwal** [comment]
I am not able to reproduce this bug:

On Chrome:
Before:
![image](https://user-images.githubusercontent.com/14195048/78359409-ab8dcb80-75d2-11ea-8ece-882f358df7a1.png)

After adding a filter (Note the url changed):  
![image](https://user-images.githubusercontent.com/14195048/78359494-c9f3c700-75d2-11ea-9db5-18c5af4fd4e8.png)

Same thing observed on Safari. Am I missing something?

**Comment by timgl** [comment]
@bhavish-agarwal You're right, this only seems to happen to me locally. Not sure why, might be something going on with kea-router? @mariusandra 

Definitely lower priority to fix now though.

**Comment by timgl** [comment]
This has been fixed
