### ISSUE TITLE
Plugin for making HTTP requests

### ISSUE THREAD

**Issue by neilkakkar** [PostHog/posthog#4370]
## Is your feature request related to a problem?

We can't create integrations for every service, but we'd still like to support people who use these services along with PostHog. (ex: FreshSales).

## Describe the solution you'd like

A plugin that sends an HTTP request to whatever endpoint, with configurable data.

## Describe alternatives you've considered

Building a plugin integration :(

Not supporting the tail-end

## Additional context

https://posthogusers.slack.com/archives/CT7HXDEG3/p1621265037317800?thread_ts=1621235613.311700&cid=CT7HXDEG3

**Comment by macobo** [comment]
There are some things which make this tricky compared to integrating with everything:

- technically, ensuring slow services don't bottleneck ingestion
- using posthog as a service to ddos others
- needing to be careful so this does not expose our own infra within vpc to attack (services which are accessible from plugin server)

Both of these are more ok on self-hosted, but we need to be careful about them on cloud

That said, nothing is impossible :rocket:

**Comment by mariusandra** [comment]
Agreed with @macobo that making random requests to random locations has security implications on cloud. While [we are working](https://github.com/PostHog/plugin-server/issues/353) to get around the "slow service bottlenecking ingestion" issue, limiting what can be seen within out own VPC is a task we don't want to take on now. It's the same reason we're [stalling with the postgres export plugin](https://github.com/PostHog/plugin-repository/issues/11).

For self hosted, any "config API" we can create to configure your POST endpoint and parameters will be inferior to just writing the same logic in javascript :). And that's kind of the point with plugins -> they should be so simple to use that anyone half-technical could copy/paste one, change some URLs and be up and running.

For the linked thread in slack, we or the user requesting should just build a legit plugin for this service. If it's good enough, we can add it on cloud and then everyone can use it. The more integrations we have, the better.

Thus, closing this for the time being.

**Comment by neilkakkar** [comment]
Fair, that makes sense.

I'm not quite convinced that writing plugins for everything is easier / better, but happy to revisit at a later point, once we've seen how people use plugins.

**Comment by mariusandra** [comment]
Nothing is true in the absolute, so perhaps it's not always easier to write plugins, but for now having more plugins is better in line with our business and security goals :).
