### ISSUE TITLE
Too eager autocomplete - can't type values in for contains filters

### ISSUE THREAD

**Issue by kpthatsme** [PostHog/posthog#4388]
## Bug description

- When setting the Active Feature Flags filter, the property gets set as soon as I type `"`, the only way to set the property is to copy and paste the entire string i.e. ("project-home-exp-5") into the filter

## Expected behavior
- Autocomplete should work as it does for other properties, allowing you to type and pick the match

## How to reproduce

1. Create a chart and set an 'Active Feature Flags' filter - here's an [example](https://app.posthog.com/insights?insight=FUNNELS&interval=day&display=FunnelViz&events=%5B%7B%22id%22%3A%22%24pageview%22%2C%22name%22%3A%22%24pageview%22%2C%22type%22%3A%22events%22%2C%22order%22%3A1%2C%22properties%22%3A%5B%7B%22key%22%3A%22%24active_feature_flags%22%2C%22value%22%3A%22%5C%22project-home-exp-5%5C%22%22%2C%22operator%22%3A%22not_icontains%22%2C%22type%22%3A%22event%22%7D%5D%7D%2C%7B%22id%22%3A%22first%20team%20event%20ingested%22%2C%22name%22%3A%22first%20team%20event%20ingested%22%2C%22type%22%3A%22events%22%2C%22order%22%3A2%2C%22properties%22%3A%5B%5D%7D%5D&properties=%5B%5D&filter_test_accounts=true&actions=%5B%7B%22id%22%3A2671%2C%22name%22%3A%22User%20Signed%20Up%22%2C%22type%22%3A%22actions%22%2C%22order%22%3A0%7D%5D&new_entity=%5B%5D) - select the contains operator and try to type in values 

I should note that it appears I'm currently in the old UI bucket so maybe this is fixed in the new UI.

## Environment

- [ ] PostHog Cloud
- [ ] self-hosted PostHog, version/commit: _please provide_

**Comment by kpthatsme** [comment]
Update – looks like this is something with the contains filter in general.

**Comment by samwinslow** [comment]
PR #4411 fixes this — thanks @EDsCODE!
