### ISSUE TITLE
Make it possible to permanently close the Posthog toolbar

### ISSUE THREAD

**Issue by edhgoose** [PostHog/posthog#4397]
## Is your feature request related to a problem?

I turned on the Posthog toolbar, and found afterwards that the only way to stop it from showing was by logging out of Posthog.

## Describe the solution you'd like

The close button removes the toolbar from the current page, but when I refresh, it comes back. I'd like a way to permanently close it.

## Describe alternatives you've considered

I am not familiar enough with Posthog to know other alternatives I'm afraid.

**Comment by timgl** [comment]
Hey there. You can disable the toolbar for your entire team in the project settings.

Agree though that the close button should be permanent, cc @neilkakkar 
![image](https://user-images.githubusercontent.com/1727427/118792594-17df9300-b898-11eb-9422-5f1ea5f8adf9.png)

**Comment by edhgoose** [comment]
Yea, I was hoping for something a little more temporary. Sometimes I want it on (when I'm doing Posthog-y things) and sometimes I don't (when I'm just doing regular work for instance)

**Comment by neilkakkar** [comment]
Hmm, this is interesting. I'm trying to visualise the workflow here:

Say, you close the toolbar because it's distracting you. Now, when do you expect it to come back, if at all?

Assuming you want it back now: you'd go into Project settings and disable + re-enable the Toolbar?

**Comment by mariusandra** [comment]
One way to get it back after closing is to just click the "Toolbar" link in the sidebar in PostHog, and then select your site.

I think that closing the toolbar for at least a full browser session makes sense.
