### ISSUE TITLE
Missing Filter Properties on UI

### ISSUE THREAD

**Issue by paulsputer** [PostHog/posthog#4398]
## Bug description

When running `docker run -t -i --rm --publish 8000:8000 -v postgres:/var/lib/postgresql posthog/posthog:preview` as per [the one line preview docs](https://posthog.com/docs/deployment/deploy-docker#docker-one-line-preview). Adding a filter on the inisghts page gives the following properties:
![dockerimage](https://user-images.githubusercontent.com/4686906/118787427-bc5ad880-b88a-11eb-93f2-0005b9a821f2.png)

However, when using docker compose either `docker-compose up` or `docker-compose -f docker-compose.e2e.yml` no filter properties are available even though events are being registered:
![fresh-docker-up](https://user-images.githubusercontent.com/4686906/118801406-e0bdb180-b898-11eb-8891-6729d977417e.png)

## Expected behaviour
Running docker-compose command should result in the same core properties as through the preview mode.

## How to reproduce

1.`docker run -t -i --rm --publish 8000:8000 -v postgres:/var/lib/postgresql posthog/posthog:preview`
2. Configure and ping the endpoint to register a $pageview event
3. Open insights tab 'Add Filter' see properties list has items

1. `git clone https://github.com/PostHog/posthog.git`
2. Set `DISABLE_SECURE_SSL_REDIRECT: 1` in `docker-compose.yml` under web/environment
2. `docker-compose up`
2. Configure and ping the endpoint to register a $pageview event
3. Open insights tab 'Add Filter' see properties list is empty

## Environment

- [ ] PostHog Cloud
- [x] self-hosted PostHog, version/commit: #4965b5

**Comment by Twixes** [comment]
Hey Paul! Thank you for the report. As a side note, we don't support or update the `preview` image anymore, sorry for the information in the docs – removed the outdated section.
