### ISSUE TITLE
Make users table on funnel result more useful

### ISSUE THREAD

**Issue by samwinslow** [PostHog/posthog#4402]
## Is your feature request related to a problem?

From user feedback, the table underneath the primary graphic on the funnels insight result is not very useful. While PostHog users like being able to see specific names of people who have completed each step, many find the table to be confusing, especially the blue cell coloring.

Curious to get some design ideas once we decide how to prioritize this. The main areas are:

1. Design of the table (wasted space, should be a virtualized list)
2. No obvious way to export users to CSV
3. No way to see users who _dropped off_ at each funnel step. User mentioned he'd like this for automated messaging/plugin activities, e.g. building a retargeting marketing campaign.

The table in question:

<img width="542" alt="Screen Shot 2021-05-19 at 1 38 15 PM" src="https://user-images.githubusercontent.com/4645779/118859592-66952900-b8a8-11eb-8def-326fa2a6e891.png">

...truncates to some arbitrary number of users with no option to expand:

<img width="527" alt="Screen Shot 2021-05-19 at 1 38 20 PM" src="https://user-images.githubusercontent.com/4645779/118859632-73b21800-b8a8-11eb-90f8-458837a73d59.png">

...which makes 100% and 86% look equivalent, which is misleading.

## Describe the solution you'd like

1. Remove/rethink the blue empty table cells (as they convey the same spatial info as the primary graphic), maybe the list comes up when you click a stage of the primary graphic
2. Export to CSV button
3. Query for users that have dropped off at funnel steps `n+1`, `n+2`, `...` and ability to export

## Describe alternatives you've considered

Just adding CSV button, because the dropoff analysis could be done offline in Excel.

**Comment by paolodamico** [comment]
@corywatilo I think it'd be very helpful if you took an initial stab at this. We would also be able to reuse this visual component for the persons table shown when double clicking any data point on other insight types.

**Comment by paolodamico** [comment]
As the new design we're working on already accounts for this, I think we can close this. Feel free to reopen if you think that'd be best.
