### ISSUE TITLE
New User Not Added to Matching Cohort

### ISSUE THREAD

**Issue by reed-only** [PostHog/posthog#4409]
## Bug description

New users logging in are not being added to cohorts.  We surpassed the 15 minute wait, which did not trigger a refresh.  We resaved the cohort which did not add the new user.

## Expected behavior

A new user should be added to matching cohorts immediately, or at least after the imposed wait of up to 15 minutes.

## How to reproduce

1.  Create a cohort with filter email contains "@yourdomain.com"
2.  New user logs in for the first time matching your email filter
3.  User should get added to the cohort, but does not

## Environment

- [x] PostHog Cloud
- [ ] self-hosted PostHog, version/commit: _please provide_

**Comment by EDsCODE** [comment]
Hi! Thanks for noting this issue. I want to help debug your issue more specifically but will require the email you used to sign up to posthog. Feel free to leave that here or message me on our community [slack](https://posthog.com/slack)

**Comment by EDsCODE** [comment]
Hi @reed-only we've done some updates to our cohort filtering since this issue was opened. The functionality you've referred to seems to work consistently now for our cohorts. Is this still an issue for you?

**Comment by reed-only** [comment]
I've actually been using it the last couple of days and it seems to work
now as expected.  Thanks for the update.

**Comment by Twixes** [comment]
Alright, I'll close this then, but feel free to reopen if this issue reappears!
