### ISSUE TITLE
My company changed email domain and we are locked out of our account

### ISSUE THREAD

**Issue by reed-only** [PostHog/posthog#4413]
## Bug description

I was using Google SSO for login.  I tried to change the email on my account but did not see the option under Account Settings.  So I logged out and tried to log back in with Google SSO using the new email domain and PostHog dumped me into a new organization.  Our other SaaS products handled the cutover seamlessly.

## Expected behavior

Tie out the same underlying Google SSO account after domain change with end result of the user being able to access their previous account + organization.

## How to reproduce

1.  Sign up to PostHog using Google SSO
2.  Change your email domain (this is a long complicated ordeal that I did not do myself)
3.  Log out of PostHog
4.  Log back in with Google SSO using the new domain

## Environment

- [x] PostHog Cloud
- [ ] self-hosted PostHog, version/commit: _please provide_

**Comment by paolodamico** [comment]
**Updated comment**. Hi @reed-only, you're right, we should recognize you're the same user even if your email address changes. I do apologize for the inconvenience here. I can help you get access back to your PostHog Cloud account. Reached out via email.

**Comment by paolodamico** [comment]
Keeping this issue around to document the need to record SSO's provider IDs and use those for identification when an account has been linked instead of just relying on the email address.
