### ISSUE TITLE
Current URL filter automatically closes every letter you type

### ISSUE THREAD

**Issue by cheeseblubber** [PostHog/posthog#4417]
## Bug description

*Please describe.*  
*If this affects the front-end, screenshots would be of great help.*  

## Expected behavior

It should filter when I press enter or pick the right one 

## How to reproduce

1. go to retention page 
2. add a filter
3. start typing a full sentence (It automatically filters on every letter)

## Environment

PostHog Cloud

https://user-images.githubusercontent.com/4218509/118998365-630cab00-b957-11eb-9b81-d69376627232.mov

**Comment by kpthatsme** [comment]
Hey @cheeseblubber thanks for the ticket – this was fixed in https://github.com/PostHog/posthog/pull/4411 and should be working now!
