### ISSUE TITLE
Some session recordings are huge enough to kill the running process during decompression

### ISSUE THREAD

**Issue by neilkakkar** [PostHog/posthog#4439]
## In what situation are you experiencing subpar performance?

In some projects (specifically `team_id=2511`, ref: https://posthogusers.slack.com/archives/G01JXEDAL22/p1621498502008700 ) - the session recording size is an order of magnitude higher than the average*.

There's two ways to go from here, depending on #4438 - if not a one-off / specific to the user, investigate why their recordings are so huge. If this happens for a lot of users, then perhaps worth figuring out a way to fix on our side.

## How to reproduce

1.  Try decompressing `sessionRecordingId=1797fff6ff8ca4-0b988ec6c352ab-33687008-13c680-1797fff6ff9899`

## Environment

- [x] PostHog Cloud
- [ ] self-hosted PostHog, version/commit: _please provide_

## Additional context

*: by average, I mean the average size for PostHog session recordings.

**Comment by neilkakkar** [comment]
cc: @macobo - for this specific user, your hunch was correct, seems like it's a Figma like app, so there's lots of DOM elements moving around: 

<img width="1791" alt="4a26311321ec4584923feb361f0ba638-Screenshot-2021-05-21-at-13 16 29" src="https://user-images.githubusercontent.com/7115141/119129842-5a87a380-ba2f-11eb-9d66-41f2015ccfa2.png">

which would make sense for the recording being huge. Can we give them an option to export this as a video? using maybe something like https://github.com/rrweb-io/rrvideo

**Comment by macobo** [comment]
For reference, the recording here was ~380MB before decompression and their average event size was ~20x compared to app.posthog.com.

This is a ton of data for clients to be sending us in the first place. Perhaps it would be best for them to ignore part of the UI? https://posthog.com/docs/features/session-recording#ignoring-sensitive-elements

Re video - note that tool still works from the database, so you need to do this on the server, which would not work well for this usecase.
