### ISSUE TITLE
"Trends" tab layout seems broken

### ISSUE THREAD

**Issue by sankalpdomore** [PostHog/posthog#4440]
## Bug description

The "Insights" tab seems to run in a single-column layout as opposed to its original two-column layout. Guessing some layout was mistakenly tweaked. 

`Insights` page > `Trends` tab right now:

<img width="1440" alt="CleanShot 2021-05-21 at 16 06 37@2x" src="https://user-images.githubusercontent.com/18334593/119124842-bdd4fe00-ba4e-11eb-8168-30fd63b3ef9e.png">

## Expected behavior

`Funnels` tab right now - this is how Insights tab should also look like

<img width="1440" alt="CleanShot 2021-05-21 at 16 06 48@2x" src="https://user-images.githubusercontent.com/18334593/119124845-bf062b00-ba4e-11eb-94d4-63ec1100e54d.png">

## How to reproduce

1. Go to `Insights` page > `Trends` tab

## Environment

- [x] PostHog Cloud
- [ ] self-hosted PostHog - Didn't check

**Comment by paolodamico** [comment]
Not a bug, but rather part of an experiment we're running for a new querying layout. Two quick takeaways from me:
1. Seems like having two mixed layouts is confusing even if the layout makes sense (funnels).
2. We didn't consider the "You don't have any actions set up ...." CTA which looks weird. I'm thinking we should drop this altogether.

CC @samwinslow thoughts?

**Comment by samwinslow** [comment]
@paolodamico I agree that we should stick to one layout, whether that's horizontal or vertical. And yes, can tweak the empty actions CTA, even if just to move the link onto its own line.

@sankalpdomore Thanks for the feedback here! If you have more thoughts/feedback as you explore the new UI, feel free to open additional issues. We are constantly iterating and will take this into account.

In the meantime, if you're thinking, gosh, I absolutely hate this new layout--we can opt you out of this version.

**Comment by sankalpdomore** [comment]
@samwinslow yeah, I'd like to be opted out. 

This layout pushed my chart down below and I expect to see graphs/numbers first when I open the app vs. looking at filters/controls that resulted in that data. I think users are more tuned to looking at graph/data and taking decisions vs. being control-driven decision makers.

**Comment by samwinslow** [comment]
@sankalpdomore Will do. This is helpful feedback, thanks again!

Would you mind sending me an email from the email account you have registered with us? I'll be able to set up the exclusion that way. You can reach me at:  sam `at` posthog `.` com.

**Comment by sankalpdomore** [comment]
> @sankalpdomore Will do. This is helpful feedback, thanks again!
> 
> Would you mind sending me an email from the email account you have registered with us? I'll be able to set up the exclusion that way. You can reach me at: sam `at` posthog `.` com.

Sent. Thanks for a quick turnaround.
