### ISSUE TITLE
Release 1.26.0 2/2

### ISSUE THREAD

**Issue by macobo** [PostHog/posthog#4446]
Retro for this sprint:
https://docs.google.com/document/d/1w2ozOssCoy3Vgh8UwXbx2A-R4FzSEC1ayyz8YkOfgn0/edit?usp=sharing

**Comment by mariusandra** [comment]
### Team Extensibility

Priorities this sprint:

1. Data lakes. Exports. Imports. All the data. Reliably. Many different services.
2. The deteriorating state of our libraries.
3. Keep the lights on work in the plugin server itself.
4. New developments that unblock a lot of things: installing plugins, action matching.

Tasks sorted by priority for everyone:

Marius:
- Priority 1: ~~[`exportEvents`](https://github.com/PostHog/plugin-server/issues/404)~~ and ["run from the beginning"](https://github.com/PostHog/plugin-server/issues/406)
- Priority 2: PHP [feature flags](https://github.com/PostHog/posthog-php/issues/10) ~~and [PSR-4](https://github.com/PostHog/posthog-php/pull/9), iOS [SPM](https://github.com/PostHog/posthog-ios/issues/13)~~

Michael:
- Priority 2: [Migrate to flutter 2](https://github.com/PostHog/posthog-flutter/pull/10), [world class plugin docs](https://github.com/PostHog/posthog.com/issues/1396).
- Priority 3: ~~[mmdb loading issue](https://github.com/PostHog/plugin-server/issues/391)~~, [plugins health check](https://github.com/PostHog/plugin-server/issues/372)
- Priority 4: [action event matching inside the plugin server](https://github.com/PostHog/plugin-server/issues/235)

Neil:
- Priority 2: ~~[$snapshot events wrongly sent](https://github.com/PostHog/posthog-js/issues/231), [this.rageClicks](https://github.com/PostHog/posthog-js/issues/228), [`/sessionRecording?...`](https://github.com/PostHog/posthog-js/issues/183)~~
- Priority 4: [plugin installation step](https://github.com/PostHog/plugin-server/issues/405)

Yakko:
- Priority 0: rest and enjoy time with your family
- Priority 1: [postgres plugin](https://github.com/PostHog/plugin-repository/issues/11), [retries when punishing plugins that error](https://github.com/PostHog/plugin-server/issues/387), [customer.io buffer](https://github.com/PostHog/customerio-plugin/issues/1), [clean up rudderstack export](https://github.com/PostHog/plugin-repository/issues/15)

**Comment by paolodamico** [comment]
### User Experience Team

Core Experience split for frontend / UX stuff.

- 🚀 Event and properties basic taxonomy. Li.
- Dashboard version control and commenting/collaboration (after taxonomy and pending if something else comes up from focus customers). Li.
- 🚀 New UI for graphs & tooltips. Sam.
- Legends. Sam (Paolo to help with UI/UX).
- Paolo. TBD until we figure out our approach for focus customers.

**Comment by macobo** [comment]
Team infrastructure (my input):

Tiina currently support hero next week, James the week after that (pending to switch with Michael)

Continue onboarding clients.

- Team: Retro platform.sh churning
- Onboard NZN
- Unstick Zipari and Classkick onboarding
- Tiina: continuing with backups. https://github.com/PostHog/vpc/issues/64
- Tiina (stretch): Run migrations on the background https://github.com/PostHog/vpc/issues/89
- Karl: Migrate person_distinct_id to not require `ALTER TABLE DELETE` (Will need help from @EDsCODE or @buwilliams with query updates) https://github.com/PostHog/posthog/issues/4242
- Karl: Internal metrics dashboards for managing clickhouse https://github.com/PostHog/vpc/issues/45 (also involves improving our internal metrics)
- Split ingress for events and app on VPC

**Comment by fuziontech** [comment]
Team infra part deux!

- Retro platform.sh churning
- Split ingress for events and app on VPC
- Onboard NZN
- Unstick Zipari and Classkick onboarding
- Support above listed by Karl
![image](https://user-images.githubusercontent.com/391319/119161333-12a45480-ba0e-11eb-8cb1-c4a404b73ac1.png)

**Comment by EDsCODE** [comment]
Team Core Analytics:

Buddy
(1) Add comments on duplicate persons
Personal email to business email
Common emails that may be filled by different users
(2) Merge master into multiple environments and finish PR
(3) Funnel trends improvement. Extend funnel functionality (Buddy)

Eric
(0) Support Hero + Keeping up with Buddy through queries
(1) New cohort query optimization table
(2) Data duplication continue the conversation + other data integrity issues. Come up with metric to put into grafana

Backburner:
- Build support for complex engagement filters E.g. done X action Y times in Z time frame.
- Group analytics

**Comment by fuziontech** [comment]
Retro for this sprint:
https://docs.google.com/document/d/1w2ozOssCoy3Vgh8UwXbx2A-R4FzSEC1ayyz8YkOfgn0/edit?usp=sharing
