### ISSUE TITLE
Write official PostHog event spec

### ISSUE THREAD

**Issue by mariusandra** [PostHog/posthog#4448]
There are about 101 ways to send events to PostHog, and various libraries implement different ways. Some send a [random `context` object](https://github.com/PostHog/posthog-python/blob/master/posthog/client.py#L164-L171). Some put `$set` in properties, some in the event body. Some send timestamps. Some also `sent_at` fields. Some set a random `message_id`, some a `messageId`, some send nothing. And so on.

Instead of this flexible "legacy" situation, I propose we formalise and document the golden standard "Posthog Event Schema version 2". This way we'll have something to aim towards when cleaning up all the libraries. We'd have to make everything still backwards compatible, but at least we'll have the right way.

**Comment by mariusandra** [comment]
More cases: 
- the posthog-ruby library puts the distinct_id inside properties, and sends a `null` distinct_id in the event body: https://github.com/PostHog/posthog-ruby/blob/master/lib/posthog/field_parser.rb#L66-L68
- the posthog-js library sends a distinct_id in both the event body and properties: https://github.com/PostHog/posthog-js/blob/master/src/posthog-core.js#L838-L857

- Why is `$set` on the top level of a user, but `$increment` inside properties?

**Comment by soccerboymalloy-patriot** [comment]
This would be really helpful for my team! Is this being considered for prioritization?

We're developing an application where we'd like to publish events from our backend, but it's written in C# which means we have to manually create API requests. The only formal documentation I can find is [this page](https://posthog.com/docs/api/post-only-endpoints), which leaves a lot out.
>Some put $set in properties, some in the event body. Some send timestamps. Some also sent_at fields. Some set a random message_id, some a messageId, some send nothing. And so on.

I've been scratching my head over some of these exact fields. I started looking through some of your API code for answers, but logic [like this](https://github.com/PostHog/posthog/blob/master/posthog/api/capture.py#L125-L131), while helpful to see what I _can_ do, doesn't help me feel comfortable about what I _should_ do.

In addition, it's not clear to me what the recommended approach is do simple things like update person properties. Do I make an identify call? I only see an example of that being done via a batch call - can I do a one off identify call by calling the capture endpoint and specifying `"type": "screen"` and `"event": "$identify"` (not that I know what "type" even does/means)? Or should I just use the [person PATCH endpoint](https://posthog.com/docs/api/people)?

I agree that the flexibility and options with the current approach is more scary than helpful for my team. We're going to be doing a lot of trial and error and crossing our fingers to get things working.
