### ISSUE TITLE
Long funnels aren't rendered

### ISSUE THREAD

**Issue by llamallamagirl** [PostHog/posthog#4453]
## In what situation are you experiencing subpar performance?

Due to the nature of my company (telehealth), we have a very long conversion funnel (> 15 steps). I created actions for each event in the funnel, set it up as a funnel, but get the error "Your query took too long to complete." when trying to view it. Also, it does not render on the dashboard, and instead says "This funnel doesn't have any steps."

## How to reproduce

1. Create 15+ of actions
2. Put them in 1 funnel
3. Try to view the funnel

## Environment

PostHog Cloud

**Comment by timgl** [comment]
@llamallamagirl Hey Kristin,  looks like you're hitting the limits of your Postgres database. What kind of volume do you have? (you can see the volume on the Instance Status page (top left, green icon or /instance/status).

There's a couple of suggestions in the error like increasing the size/power of your database instance. LMK if that helps.

We are also offering a free version of our more scalable database but there's a waitlist for it. You can email sales@posthog.com for that.

**Comment by paolodamico** [comment]
We're actively working on improving the performance of funnels in other issues. Closing this to avoid duplication.
