### ISSUE TITLE
Data taxonomy

### ISSUE THREAD

**Issue by jamesefhawkins** [PostHog/posthog#4459]
From me: "if a random engineer/producty person hopped onto your instance of posthog, would they struggle to know what the events mean?"

[From user via DM](https://app.hubspot.com/contacts/6958578/deal/3549032247/): "yeah - i am at the stage where i need to document things and it kills me to think i might end up making a confluence doc or something - was thinking would be cool if i could in some way have the docs be more like part of the code in some way - so ability for the devs to describe each events and add descriptions to event properties etc and then just have a nice sort of data dictionary type thing in posthog in some way."

Note: We consider taxonomy a paid/collaboration type feature

FYI @timgl

**Comment by timgl** [comment]
Closing in favour of #4267 which has a lot more context. we will pick this up this week though
