### ISSUE TITLE
"Unique users" agg not working for Lifecycle screen

### ISSUE THREAD

**Issue by andrewm4894** [PostHog/posthog#4460]
## Bug description

*Please describe.*  
*If this affects the front-end, screenshots would be of great help.*  

It looks like when i select "Unique users" it just defaults to "Total count"

![image](https://user-images.githubusercontent.com/2178292/119371559-79479d80-bcae-11eb-8dc5-8e028812b4c6.png)

## Expected behavior

It should display "Unique users" like in other insights graphs.

## How to reproduce

1. go to insights > lifecycle
2. try to aggregate by "Unique users"

## Environment

- [x] self-hosted PostHog, version/commit: _please provide_

**Comment by paolodamico** [comment]
Hey @andrewm4894! This has actually been fixed, lifecycle should only support unique users, and only loads that by default. @fuziontech / @macobo could we get your help updating their instance?

**Comment by andrewm4894** [comment]
> could we get your help updating their instance?

no major rush on our end.
