### ISSUE TITLE
Filtering / Pagination of /api/event/sessions (UI --> Sessions) drops sessions 

### ISSUE THREAD

**Issue by sdoncho** [PostHog/posthog#4462]
## Bug description
I tried posting a bug already but anyway here I try again: 

I don't know if it's relevant but I have session recordings enabled. Sessions are not properly fetched from the backend when using filters. I know for a fact that there are around ~60 sessions for a specific filter, but on the GUI only 4 are shown. Sometimes I will see sessions dissapearing before my very eyes when I refresh the page. 

The sessions are there in the database and are counted correctly on the Insights page.  Compare the two screenshots:
![image](https://user-images.githubusercontent.com/66218230/119388649-dc472d80-bcca-11eb-9561-de4a92eef741.png)
![image](https://user-images.githubusercontent.com/66218230/119388764-0698eb00-bccb-11eb-8c17-0d4dfa3f2bc2.png)

Furthermore when playing around with the REST API, I figured out the following:
/api/event/sessions/?date_from=2021-05-24&date_to=2021-05-24&distinct_id=&filters=SOME_FILTER
returns 9 results from the 24.05 
while /api/event/sessions/?date_from=2021-05-23&date_to=2021-05-24&distinct_id=&filters=SOME_FILTER
returns 6 results from 24.05 

both results are unpaginated

## Expected behavior

I expect to be able to see the (roughly) the same number of sessions with the same number of unique visitors. Furthermore I expect sessions to not be dissapearing

## How to reproduce

1. Install the latest docker release
2.  Enable session recording
3. Make ~50 sessions from different APIs thorough the day 

## Environment

- [ ] self-hosted PostHog, latest docker image from Repository

**Comment by paolodamico** [comment]
Might be a moot point with #4884
