### ISSUE TITLE
Global filters for test users

### ISSUE THREAD

**Issue by timgl** [PostHog/posthog#447]
**Is your feature request related to a problem? Please describe.**

It's annoying when looking at data (especially if there's not very much) that a lot of it is test data from ourselves.

**Describe the solution you'd like**
I'd be great to filter out Events by any user property. This way data from people who build the product doesn't get mixed in with the rest.

**Additional context**
This might be hard to do globally, but I think it could be worth doing for a couple of the obvious places (paths, events, trends, funnels)

**Comment by Twixes** [comment]
Done in #3492.
