### ISSUE TITLE
Make paths work for Events, not just pageviews

### ISSUE THREAD

**Issue by timgl** [PostHog/posthog#448]
**Is your feature request related to a problem? Please describe.**

It'd be great if paths were generic.

There's 4 types of events we care about in paths
- `$pageview`, deduplicated on `$current_url`
- `$screen`, deduplicated on `$screen`
- `$autocapture`, deduplicated on `elements_hash`
- Anything that doesn't start with `$`, deduplicated on event name

It'd be great to show a combination of all four, or be able to tick on/off each individual category.

(not for this ticket, but worth keeping in mind:) ability to select a 'starting position', like a pageview with certain current_url.

**Comment by EDsCODE** [comment]
One more point to note that I may work into the related PR is that autocapture tags can be really sparsely detailed. "<a> with text "sign up"" could be a label that happens across a sign up flow so without page context a user would be pretty confused what "<a> with text "sign up"" => "<a> with text "sign up"" => "<a> with text "sign up"" event means
