### ISSUE TITLE
Events and Persons page stacks when selected

### ISSUE THREAD

**Issue by DimitrisMazarakis** [PostHog/posthog#4483]
## Bug description

When I select Events or Persons page it's like it stacks and I cannot select another page for 2-5 seconds. I think this happens because it has to load some data to these pages but if you accidentally navigate to events or persons page then you are doomed to stay there until it unstacks. And also the hotkey popup does not disappear while it is stacked.

![Screenshot from 2021-05-25 21-55-42](https://user-images.githubusercontent.com/56391437/119554931-f0ac2880-bda5-11eb-9c69-afe0cfe3faae.png)

![Screenshot from 2021-05-25 21-55-11](https://user-images.githubusercontent.com/56391437/119555027-0c173380-bda6-11eb-8d4f-556ff512662c.png)

## Expected behavior

When you navigate to Events or Persons page you can instantly change to another page without menu lagging.

## How to reproduce

1. Go to events or Persons page from menu or with hotkey (G + E)
2. Then try to click another page through the menu

## Environment

- [ ] PostHog Cloud
- [ ] self-hosted PostHog, version/commit: 1.25.0

**Comment by fuziontech** [comment]
I can't seem to reproduce it on OSX w/ Chrome. @DimitrisMazarakis - what browser & OS are you on?

**Comment by fuziontech** [comment]
Was able to reproduce on OSX w/ Safari. Definitely more pronounced on the `Persons` tab, but also happens with the `Events` tab as well. Will block dock selection until the page is loaded it seems.

**Comment by DimitrisMazarakis** [comment]
@fuziontech I use firefox for browser and ubuntu for OS

**Comment by mariusandra** [comment]
Extra context: 

This has to do with large antd tables rendering really really slow. @alexkim205 has been working on improving this and it seems that the true solution is to move to `react-table` or similar virtualized table library.

Related:
- https://github.com/PostHog/posthog/pull/4727#issuecomment-868877913
- https://github.com/PostHog/posthog/issues/4870

With 6x CPU throttling enabled, it took ~6 seconds to just render the DOM nodes making up the initial table: 

![image](https://user-images.githubusercontent.com/53387/123946273-4e342600-d99f-11eb-9237-263de35d61c9.png)

That plus diffing, slight layout adjustments, etc leads to a really degraded experience for basically anyone not on a M1 chip.

**Comment by paolodamico** [comment]
Fixed either by turbo mode or the new UI
