### ISSUE TITLE
Table display in insights

### ISSUE THREAD

**Issue by paolodamico** [PostHog/posthog#4484]
Our current table display is pretty useless. You only get a total number, which is not particularly helpful.
<img width="700" alt="" src="https://user-images.githubusercontent.com/5864173/119561457-0d227380-bd5a-11eb-8903-822750e06def.png">

While working out all the specific improvements that we need to make this table useful, I realized we already have something pretty solid here. The legends table (see below). What we can actually do here is completely **drop the current custom table** display support and instead **just use the existing legend table** (from line/bar charts), just removing the display checkboxes. This not only makes improving the display table quite easy, but also simplifies maintenance and allows us to focus on improvements that will also positively affect the line/bar charts (which I'll document in a separate issue).

<img width="1235" alt="" src="https://user-images.githubusercontent.com/5864173/119562430-2e379400-bd5b-11eb-970e-710d91c6e792.png">

N.B. We need to bring back support for the interval picker.
Closes #2722

**Comment by samwinslow** [comment]
Awesome! Reduce, reuse, recycle ♻️

**Comment by samwinslow** [comment]
Related: #4402
