### ISSUE TITLE
Toolbar prompt partially obscured by scroll bar

### ISSUE THREAD

**Issue by joethreepwood** [PostHog/posthog#4497]
## Bug description

As a new user, the floating button asking me to authenticate the toolbar is placed in a default position where it is obscured by the toolbar. 

This isn't a bug, but as a new user it also wasn't immediately clear to me what the button is meant to be authenticating. May be worth updating the hover text to something more clear.

## Expected behavior

Expect to hover on the button and get a clear, readable description of the function.

## How to reproduce

1. New Posthog user
2. Not authenticated toolbar yet
3.

## Environment

- [ ] PostHog Cloud
- [x] self-hosted PostHog, version/commit: _please provide_

## Additional context

Screenshot attached
<img width="2560" alt="Screenshot 2021-05-26 at 09 44 56" src="https://user-images.githubusercontent.com/84011561/119631417-ca1ed980-be07-11eb-959b-3e3d959ae815.png">

<img width="2560" alt="Screenshot 2021-05-26 at 09 50 47" src="https://user-images.githubusercontent.com/84011561/119631515-df940380-be07-11eb-8a65-7083697d753a.png">

**Comment by mariusandra** [comment]
This button on app.posthog.com is only visible for the posthog team. Everyone else will see it on their own site (if they're logged in to posthog and have the JS code installed).

**Comment by mariusandra** [comment]
@joethreepwood is this an issue?

**Comment by joethreepwood** [comment]
@mariusandra I think we can close this for now. This is such an old issue that I think it's partly borne out of confusion. 

There's probably a case about making the toolbar a bit more straight forward to use, but nothing specific or replicable here that we can take as a bug...or even an urgent issue. Closing.
