### ISSUE TITLE
Authenticate button creates redirect loop

### ISSUE THREAD

**Issue by joethreepwood** [PostHog/posthog#4498]
## Bug description

Using the floating button to authenticate the toolbar sends you to a page with two buttons. One authenticates the toolbar. The other is floating authenticate button which bought you to this page. You can keep clicking on the authenticate toolbar button to get longer and longer redirects (see screenshot). 

There's also no 'back' or 'not right now' / 'remind me later' button, though this may be intended?

## Expected behavior

I'd expect the floating authenticate button to disappear on the authentication page. 

## How to reproduce

1. New user to posthog
2. Click the floating authenticate button
3. On subsequent page, click it again

## Environment

- [ ] PostHog Cloud
- [x ] self-hosted PostHog, version/commit: _please provide_

## Additional context

See screenshot.
<img width="2560" alt="Screenshot 2021-05-26 at 09 55 01" src="https://user-images.githubusercontent.com/84011561/119632197-7eb8fb00-be08-11eb-930b-c96255678cf4.png">
<img width="2560" alt="Screenshot 2021-05-26 at 09 55 13" src="https://user-images.githubusercontent.com/84011561/119632230-87a9cc80-be08-11eb-8ee2-b0bd4f651793.png">

**Comment by mariusandra** [comment]
For the record we're the only ones seeing the toolbar button on the authentication page. It's the same button that shows up on any other app.posthog.com page for us (we use posthog to posthog posthog, who'd have guessed). Other users not part of our team will not see the button on their authentication page.
