### ISSUE TITLE
Feature flags table formatted wrong on the first load

### ISSUE THREAD

**Issue by joesaunderson** [PostHog/posthog#4500]
## Bug description

The first time I load the feature flags page (with a long description), it displays weirdly. After refreshing, it goes away.

1st Load:
![image](https://user-images.githubusercontent.com/11272509/119671700-e33c8000-be31-11eb-8978-7fee2ea4a60c.png)

Subsequent Load:
![image](https://user-images.githubusercontent.com/11272509/119671844-01a27b80-be32-11eb-8081-c4fe712e9779.png)

*Please describe.*  
*If this affects the front-end, screenshots would be of great help.*  

## Expected behavior

It loads correctly formatted all the time.

## How to reproduce

1. Create a feature flag with a long description
2. Load the feature flag page

## Environment

- [ ] PostHog Cloud
- [x] self-hosted PostHog, version/commit: 1.25.0

## Additional context

None.

**Comment by alexkim205** [comment]
Hey @joesaunderson. Thanks for the bug report! I'm unable to reproduce this specific bug when I navigate to the feature flags page. Is there another page you're navigating from when you see this bug?

This is what I see on the first reload:

<img width="1576" alt="Screen Shot 2021-06-11 at 3 01 06 PM" src="https://user-images.githubusercontent.com/13460330/121752823-dbcdd580-cac5-11eb-95a1-a3b4d52991ed.png">

**Comment by alexkim205** [comment]
The above screenshot kind of exposes another bug where we don't cut off the description if it gets too long, and squishes the other columns in the process. Perhaps we can set a `max-width` here in descriptions and cutoff text if it gets too long. This would also address the OG bug

**Comment by joesaunderson** [comment]
> Hey @joesaunderson. Thanks for the bug report! I'm unable to reproduce this specific bug when I navigate to the feature flags page. Is there another page you're navigating from when you see this bug?
> 
> 
> 
> This is what I see on the first reload:
> 
> 
> 
> <img width="1576" alt="Screen Shot 2021-06-11 at 3 01 06 PM" src="https://user-images.githubusercontent.com/13460330/121752823-dbcdd580-cac5-11eb-95a1-a3b4d52991ed.png">
> 
> 

Hey! Yes, sorry. I didn't make that clear enough. This was occurring when navigating from another page (via the router, rather than the browser reloading). When I fully reload the page, it showed as per the second screenshot.

Looks like your fix will sort it anyhow!

**Comment by alexkim205** [comment]
Thanks for the clarification! Just checked it out and I see what you're seeing. Fix incoming :)
