### ISSUE TITLE
Re-run query when a graphed action's steps changes

### ISSUE THREAD

**Issue by corywatilo** [PostHog/posthog#4506]
## Bug description

When graphing an action, then updating its definition and returning to graph the same event, the query doesn't get re-run automatically. This can make the user think they inaccurately redefined the event, when they just need to click the Refresh button.

![image](https://user-images.githubusercontent.com/154479/119685505-6ac6c680-be13-11eb-8561-bd98b561fe08.png)

## Expected behavior

If any events in the graph have been redefined since the query was run, re-run it.

## How to reproduce

1. Graph an action in Trends
2. Click Events and change its definition
3. Re-visit Trends and graph the event

Graph will show the query has not been run since the event was just redefined

**Comment by paolodamico** [comment]
Not so sure about this one. We don't rerun the query if it's cached (for performance and UX reasons), that's why the label appears. Maybe the label needs to be a bit more obvious?

**Comment by corywatilo** [comment]
Right, but point is, if you change the definition and return, it should probably bust the cache since the data will then be stale, no?

**Comment by paolodamico** [comment]
Well maybe what happened is that the definition you returned to was cached anyways. Did the graph looked awfully wrong or just not updated?

**Comment by mariusandra** [comment]
As we figured out during the planning, the issue mixed up "action" and "event". Busting the cache for an insight that shows the cache seems hard, but doing it on the frontend should be easy (get the cached results, see that the action is not the same anymore, refetch)
