### ISSUE TITLE
In funnels, graphs and persons, please provide ability to exclude users based on filters

### ISSUE THREAD

**Issue by akbansa** [PostHog/posthog#4518]
## Is your feature request related to a problem?

Yes. For example, I want to find no. of users who did an event (A) but didn't do an event (B).

## Describe the solution you'd like
Providing negation filtering can help with the solution.

For example: (`Users who have done` => event A) + (`Users who have not done` => event B)

## Additional context
HEAP used to give us enough filters on this front. We are missing them here. Although, there are most important ones

**Comment by neilkakkar** [comment]
We do have exclusion in funnels now (#5150 ) - but not as a general functionality. Would be cool to think about how to get general functionality sorted!

**Comment by macobo** [comment]
Same request, different issue: https://github.com/PostHog/posthog/issues/2594
