### ISSUE TITLE
When navigate away and back to certain funnels - the funnel breaks

### ISSUE THREAD

**Issue by fuziontech** [PostHog/posthog#4519]
## Bug description

Saved funnels don't seem to be working as expected.

https://www.loom.com/share/cbf26a3f5288408f8032fdec2e719a73

Password is available in papercups conversation:
https://app.papercups.io/conversations/all?cid=084051e1-fd3f-4997-8951-ea7baf298cb2

Or reach out to me for it.

## Expected behavior

The funnel to be in the same state as you left it.

## How to reproduce

From the Loom recording:
1) Create two stage funnel and save it.
2) Navigate away from funnel tab
3) Navigate back
4) Observe a broken 3 stage funnel

## Environment

- [x] PostHog Cloud
- [ ] self-hosted PostHog, version/commit: _please provide_

## Additional context

From Papercups user

**Comment by mariusandra** [comment]
Adding a simpler screencast to show the bug:

![2021-06-30 12 01 22](https://user-images.githubusercontent.com/53387/123941996-014e5080-d99b-11eb-9b7f-47fbe35c73f8.gif)
