### ISSUE TITLE
Enable multiple account users

### ISSUE THREAD

**Issue by jamesefhawkins** [PostHog/posthog#452]
**Is your feature request related to a problem? Please describe.**
For any hosted version (including app.posthog.com) of PostHog, it is not possible for a user to have access to multiple accounts.

This is a popular feature of Google Analytics - often as companies grow, they would want to add agencies or contractors (ie marketing contractors) to their analytics stack.

In PostHog's case, I wanted to add Marius but he already had another account!

**Describe the solution you'd like**
* Users can have access to multiple accounts

**Describe alternatives you've considered**
There is a workaround for this currently, it is possible to create a new email address for each account to which a user requires access.

**Additional context**
This isn't worth working on until someone needs it.

**Comment by macobo** [comment]
@Twixes is this solved now?

**Comment by Twixes** [comment]
It isn't exactly clear to me what "account" means in this case, but if it's allowing an account to be in multiple organizations at the same time, then yes.
