### ISSUE TITLE
Insight event search seems broken

### ISSUE THREAD

**Issue by macobo** [PostHog/posthog#4524]
## Bug description

When trying to search for insights in production the dropdown does not appear and the input seems to appear below the input.

![image](https://user-images.githubusercontent.com/148820/119812768-2c9fd480-bef1-11eb-9328-c674771c7615.png)

## Expected behavior

Search worked normally

## How to reproduce

1. Go to insights
2. Click on event dropdown

## Environment

- [x] PostHog Cloud
- [ ] self-hosted PostHog, version/commit: _please provide_

## Additional context

Using chrome on linux.

**Comment by macobo** [comment]
Also happened on a k8s deploy

**Comment by macobo** [comment]
Not able to reproduce this locally (yet) - seems like frontend/src/lib/components/SelectBox.scss is missing from the compiled css. Seems like an issue with webpack and css bundling, perhaps due to dynamic imports?

**Comment by macobo** [comment]
Fun: If you go to sessions list and then insights, all the css is loaded properly.

Seems like the relevant css is loaded in chunk `frontend/dist/action~cohorts~events~featureFlag~insights.css` (among others), which is not loaded in production for some reason.

**Comment by mariusandra** [comment]
Thanks @macobo this explanation helped hone in on the right solution: https://github.com/PostHog/posthog/pull/4545
