### ISSUE TITLE
Enable removing users from an account

### ISSUE THREAD

**Issue by jamesefhawkins** [PostHog/posthog#453]
**Is your feature request related to a problem? Please describe.**
I can add users, but I cannot edit/remove users over time. For example, if an employee leaves I can't remove their access through the PostHog UX.

**Describe the solution you'd like**
A settings page that let's me see those with access, their roles (although editing those will be a premium feature so is not part of this issue), and the ability to add/remove users' access.

**Describe alternatives you've considered**
This can be run as a django command or through django admin. That wouldn't work for a non technical user.

**Additional context**
Not worth doing this until someone upvotes it!

**Comment by timgl** [comment]
Duplicate of your own ticket #260

**Comment by jamesefhawkins** [comment]
Rookie! Closed it.
