### ISSUE TITLE
Notification for when a customer is about to hit their limit of events

### ISSUE THREAD

**Issue by fuziontech** [PostHog/posthog#4536]
## Is your feature request related to a problem?

Prevent surprise billing.

## Describe the solution you'd like

Have some predefined or settable limit for being alerted when event volumes reach the limit.

## Describe alternatives you've considered

Static and dynamic limits/thresholds. 

## Additional context

Requested by user

**Comment by paolodamico** [comment]
Duplicate of #3127 maybe?
