### ISSUE TITLE
Suggestion: Documentation Button on Toolbar

### ISSUE THREAD

**Issue by joethreepwood** [PostHog/posthog#4553]
## Is your feature request related to a problem?

This is a suggestion borne out of some recent research I've done where our focus customers had either explicitly requested more documentation on certain topics (such as best practices for naming) or had experienced issues when on-boarding non-technical team members into PostHog. 

Some of the content these users would want already exists and some of it doesn't, but discoverability for what documentation we do have is limited in PH and fragments users across multiple channels. That's what the feature request is intended to solve.

## Describe the solution you'd like

I'd suggest adding an item on the toolbar titled 'Help', 'Tutorials', 'Documentation', or similar. On this page we can feature a greater variety and depth of educational content than we currently do, without requiring the user to exit PH.

Clicking this toolbar button would open (in a new window, potentially) the [Tutorials main page](https://posthog.com/docs/tutorials), which can be a content hub for future tutorials. On this main page we can suggest existing channels (Slack, Repo, etc), feature any just-added content and enable users to use the existing search feature to find tutorials they need.

I'd suggest leaving the Papercups integration in place as an additional channel, with the addition of an autoresponse for any first contact, e.g: 'Thanks! We'll get back to you shortly. If you have a product question, don't forget to check our [documentation](https://posthog.com/docs/tutorials) too!'

## Describe alternatives you've considered

Other options could include adding a link to the bottom of each PH page (minimal discoverability) or adding to the 'My Account' drop-down in the top-right. 

Alternatively we could keep this content within the 'Home' tab and instead change the messaging, but this still feels hard to find. When I was looking for a documentation link recently, Home was the last place I looked. 

## Additional context

The existing solution is that the in-PH documentation right now is under the 'Home' tab, located at the bottom of the page, inside two drop-down menus. Other than this, users would have to leave PH and navigate manually to another source.

One of these current menus directs to the tutorials handbook. However it only surfaces a limited number of issues (it doesn't mention the 1-minute tutorials, for example) and links directly to these issues, so users may not know there is additional help content in the handbook. 

The other menu includes links to the repo (not ideal for non-technical users) and the Slack (may be high barrier to entry). The other way users can request assistance is via the Papercups integration, but this requires someone to be available to respond.

**Comment by mariusandra** [comment]
With "Toolbar" do you mean this button?

![image](https://user-images.githubusercontent.com/53387/120303519-3483be00-c2cf-11eb-8a62-426caedbc933.png)

It already has a "help" button that opens https://posthog.com/docs/tutorials/toolbar

**Comment by joethreepwood** [comment]
@mariusandra 

Ah, no. I meant this toolbar -- sorry if that was unclear!

<img width="288" alt="Screenshot 2021-06-01 at 10 58 25" src="https://user-images.githubusercontent.com/84011561/120319739-3fdbe700-c2d9-11eb-8e39-16bcb4c50dce.png">

**Comment by mariusandra** [comment]
Yeah... the "Toolbar" when capitalised is that floating button thingie. :)

There's some issue with your upload (clicked "comment" too fast?) and I can't see the screenshot.

**Comment by joethreepwood** [comment]
Screenshot fixed

**Comment by mariusandra** [comment]
I guess that's the "sidebar" 🤣

**Comment by paolodamico** [comment]
Thanks for raising this @joethreepwood! My thoughts (numbered to facilitate discussion),
1. Agree with your premise, although, I don't think adding a button to the main sidebar is the right move. I think that if you're stuck, you'll Google for answers first or prefer to contact us on Slack/Papercups for a personalized response.
2. I think what we need to do more of is adding better in-product links to specific useful docs (see examples below). That way we do the heavy lifting instead of the users. We also have a general idea of potential friction points already. Finally, we've gotten feedback from usability tests that these have proven quite valuable (particularly the info icons with tooltip information).
   <img width="300" alt="" src="https://user-images.githubusercontent.com/5864173/120367502-c981b980-c2c5-11eb-9b71-369e20b2442c.png">
   <img width="450" alt="" src="https://user-images.githubusercontent.com/5864173/120367510-cab2e680-c2c5-11eb-9468-d48cc7d65685.png">
3. There's also the Home page, which I believe in the latest iteration we're turning into a "resource center" for when you're not sure about something (or new users) which I think could work well for this case. CC @kpthatsme 
4. One additional thing I'm thinking could be helpful is integrating the docs search within the product (maybe on the home page and the command palette).

Thoughts?

**Comment by kpthatsme** [comment]
@joethreepwood great write up! 

Some thoughts from me:
- Agreed with the premise that we have some valuable content that can really help users get spun on. 
- I'm not so sure if I agree with the suggested location – IMO the thing with education content i.e. tutorials is generally they appeal to a small subset of users– For the people who prefer that kind of content, it leads to great results – but I don't think it's the best product-led way to get users onboarded.
  -  To help test this theory, we ran a test on Project Home (https://github.com/PostHog/experiments/issues/5) - we saw relatively low engagement with the tutorials module. Those who did engage with it ended up doing pretty well and discovering learnings at a higher clip. I think this speaks to the _need_ for education but that lack of engagement speaks to the fact this isn't quite the right way to surface it.
 

I think there are 2 major components for in product education:
1. Where are people getting confused and how do we add the right context in those specific areas (i.e. what @paolodamico talked about in terms of knowing the general friction areas and knowledge gaps). An example here would be simple, informative tooltips across the Insights page.

2. Where do we train our users to go when they get stuck? I think we need one _central_ area that folks know to go when they're having problems. Right now it's scattered – we have paper cups, project home, the toolbar button, probably a few others. 

I do think that Paper Cups could be good a home for all of this. It has become common language across the web now that the thing in the bottom right of your page is generally a way to get help. We could bake more self-help into Papercups in itself. It's often how orgs deploy Drift / Intercom.

I think #1 is being answered right now through a lot of the UX work the core team is doing. I'd love to hear folks' thoughts on what we should do for #2.

**Comment by joethreepwood** [comment]
@kpthatsme @paolodamico Great responses, thank you! 

Definitely agree with the point about tooltips, which are invaluable and the idea of integrating the docs search into the product seems a very neat solution. 

I thought Papercups would be a good solution too, but my concern is our ability to make it responsive enough for users given our small team-size, no-meeting days, etc. Right now (10:30 GMT) we have a broad mix of the team online, but Papercups lists Posthog as 'Away at the moment'. 

I'd be interested to know where Papercups help requests currently go and how often we see it used?

I've had a look at Papercups' features and it doesn't seem to support any sort of auto-response, either time-based or based on language. One solution may be to leverage the chat greeting to highlight the Tutorials section or Slack community for times when a response isn't going to be immediate. 

Current greeting text: _"Hi! Send us a message and we'll respond as soon as we can."_

Suggested greeting text: _"Hi! We'll respond to your message as soon as we can. You can also check our [help centre](https://posthog.com/docs/tutorials) or ask [our Slack community](https://posthog.com/slack) if you need assistance."_

**Comment by paolodamico** [comment]
- 100% think it's worth exploring and improving the experience on Papercups as users definitely go there when they're stuck. Perhaps we can do something like allowing them to send a message and while they wait for a response they can search our docs (would like to avoid them having to go through multiple flows/clicks before we let them send a message).
- Happy to try any greeting text you suggest, just bear in mind that for now it looks like we can only do plain text (i.e. no links). Let me know how you wish to proceed here.
- Finally, I've added you to our channel with Papercups so you can discuss functionality with them. I'm sure we can get support for some of this functionality.

**Comment by joethreepwood** [comment]
Sharing here for visibility. 

- Spoke with Alex from PC and they're planning on bringing in auto-response functionality which would hit our needs. 
- I'll get access to PC shortly and update greeting text to address this as a quick fix. We may not be able to include links, so will be something along the lines of: _"Hi! We'll respond as soon as we can. You can also check posthog.com/docs if you need assistance!"_
