### ISSUE TITLE
Add management command to add 1 million events

### ISSUE THREAD

**Issue by timgl** [PostHog/posthog#456]
***Thank*** you for your feature request - we love each and every one :)

**Is your feature request related to a problem? Please describe.**
As a developer it's really hard to know locally if my code scales

**Describe the solution you'd like**
Simple management command that does the same thing as the /demo thing, but with many more events.

**Describe alternatives you've considered**
Creating lots of events manually?

**Comment by jamesefhawkins** [comment]
+ document this - it's a cool feature.

**Comment by bhavish-agarwal** [comment]
I tried using Django's [bulk_create](https://docs.djangoproject.com/en/3.0/ref/models/querysets/#bulk-create) to create a million Event objects and timed it:

```
In [18]: def bulk_create_events():
    ...:     for i in range(100):
    ...:         Event.objects.bulk_create([Event(team=team, event='$bulk_event_for_test') for j in range(10000)])
```

```
In [16]: def time_bulk_event_creation():
    ...:     start_time = time.time()
    ...:     bulk_create_events()
    ...:     print("--- %s seconds ---" % (time.time() - start_time))
    ...:

In [11]: import time

In [19]: time_bulk_event_creation()
--- 128.59356117248535 seconds ---
```

```
In [20]: Event.objects.filter(event='$bulk_event_for_test').count()
Out[20]: 1000000
```

It took little over 2 minutes to create 1 million Event objects.

Let me know if this is within the acceptable time limit? I think for this issue, the main problem is to create  Event objects quickly. Once that is figured out, we can build the /demo like solution easily.

**Comment by timgl** [comment]
Yep I'm less worried about speed, but the big challenge is that I'd like some realistic events.

I'd like it to be exactly the same as in `demo.py`, but 1 million rather than 100 and in a management command, as this is just for developers.

**Comment by bhavish-agarwal** [comment]
Ok, I will create a management command with following arguments:

--team_id: 
--mode: 'delete' or 'create' events
--count: '1M' or '100K' events

like it is in demo.py will tie actions and funnels with these events

For creating people will use the the existing demo_data.json.

**Comment by anoopemacs** [comment]
Just putting it out there as an alternative,
I directly connected to the db tables in postgres using psycopg2.
1m+ insertions take <10 seconds. This is not the django way of doing things though.

**Comment by bhavish-agarwal** [comment]
So I made a change to code to use psycopg2. 1M insertion is still taking ~2 mins.

**Comment by anoopemacs** [comment]
Replace `psycopg2.extras.execute_batch(...)` with `cursor.copy_from(...)`
I built up a StringIO() and copied at once using copy_from to reach < 10 sec

```
    data = StringIO()
    for i in range(0, 1000000):
        data.write("""%s\t%s\t%s\t%s\t%s\n""" % (id0, created_at0, properties0, team0, user0))
    
    data.seek(0)
    cursor.copy_from(data, <insert relevant table name>)
```

**Comment by bhavish-agarwal** [comment]
I ended up writing a StringIterator to be used instead of the csv file to save memory as well.

It is now taking ~ 70 seconds to insert 1M records and ~45 seconds.

**Comment by mariusandra** [comment]
Leaving this here for whoever wants to pick it up.

I just tried running the command and it failed. Some newer changes to posthog with the way funnels are store causes it to fail. It was enough to just comment out the offending code for my usecase, though this should be fixed properly some day.

**Comment by yakkomajuri** [comment]
Demo data generation has significantly improved since this
