### ISSUE TITLE
/api/cohorts keeps getting reloaded too many times

### ISSUE THREAD

**Issue by macobo** [PostHog/posthog#4572]
## Bug description

1. api/cohorts data is reloaded each time user visits insights page, even if the data has been loaded on a previous view
2. See code in https://github.com/PostHog/posthog/blob/loading-and-caching/frontend/src/models/cohortsModel.ts#L56-L62 - while some cohorts are being recalculated, we reload cohorts every 5 seconds.

We don't need that cohorts reloading logic on insights page, only on cohorts page.

## Expected behavior

Load cohorts data once when not on cohorts page.

## How to reproduce

See https://github.com/PostHog/posthog/pull/4571 

## Additional context

Related PR: https://github.com/PostHog/posthog/pull/4571 - in an ideal world cohorts data used in dropdowns would be loaded using that mechanism.

Originating issue: https://github.com/PostHog/posthog/issues/4567

**Comment by mariusandra** [comment]
Cohorts are also now loaded with the app via models #4627
