### ISSUE TITLE
Toolbar heatmap not working

### ISSUE THREAD

**Issue by yakkomajuri** [PostHog/posthog#4575]
## Bug description

This bit me in a demo today after the person asked me to show our heatmap.

Our toolbar's heatmap functionality doesn't seem to be working:

<img width="1438" alt="Screenshot 2021-06-02 at 14 10 05" src="https://user-images.githubusercontent.com/38760734/120523512-5c951f00-c3ac-11eb-8033-79b5d1040cbd.png">

Can reproduce this on app and playground.

## Expected behavior

Work.

## How to reproduce

1. Enable the heatmap on posthog.com
2.
3.

## Environment

- [ ] PostHog Cloud
- [ ] self-hosted PostHog, version/commit: _please provide_

**Comment by mariusandra** [comment]
Confirmed that it doesn't work. Also confirmed that we are $autocapturing events on posthog.com. 
It works well on my kea.js.org account though.

🤔

**Comment by yakkomajuri** [comment]
Confirmed it's actually working on the playground - I guess there just were no events for the heatmap to show on the playground in the last 7 days.

However, I now have a hunch: It's about how the new website's been built, rather than a toolbar problem.

**Comment by yakkomajuri** [comment]
Hmm but it doesn't work on website pages that weren't redesigned either :thinking:

**Comment by yakkomajuri** [comment]
Update: Setting it to "Last 90 days" worked, "Last 30 days" doesn't

**Comment by timgl** [comment]
I've narrowed this down to the Property Flattener plugin. When I disable that, `elements_chain` gets filled again which means heatmaps also work. I'm not 100% sure why this is happening though.

**Comment by yakkomajuri** [comment]
Very odd, because the plugin doesn't remove anything. It keeps the old stuff and adds new props.

<img width="255" alt="Screenshot 2021-06-10 at 13 54 38" src="https://user-images.githubusercontent.com/38760734/121566032-78737300-c9f3-11eb-9837-872537c7695c.png">
<img width="467" alt="Screenshot 2021-06-10 at 13 54 43" src="https://user-images.githubusercontent.com/38760734/121566036-7a3d3680-c9f3-11eb-9ae0-8e475eda4cb7.png">

**Comment by timgl** [comment]
https://github.com/PostHog/plugin-server/blob/84e471c71c778a61cc1787805440ba7e4027f691/src/worker/ingestion/process-event.ts#L382 < this is the line where some $elements related stuff happens.

**Comment by yakkomajuri** [comment]
Just confirmed that it keeps `$elements` intact. It does add a lot of data though so best to ignore autocapture events on that plugin anyway

**Comment by timgl** [comment]
i'll fix it

**Comment by timgl** [comment]
Okay so for some reason doing this fixed it: https://github.com/PostHog/flatten-properties-plugin/pull/1/files

I don't actually understand _why_, but let's close this for now
