### ISSUE TITLE
Dashboard tags w/ grey BG

### ISSUE THREAD

**Issue by kpthatsme** [PostHog/posthog#4578]
## Bug description

Some of our dashboard tags don't show up due to the color scheme mixed w/ our app BG.

## Expected behavior

Dashboard tags are easy to read against the app background.

## How to reproduce

1. Go to [Dashboards](https://app.posthog.com/dashboard) in our app
2. Look at the 'big-5' or 'core-experience' tag

## Environment

- [ ] PostHog Cloud
- [ ] self-hosted PostHog, version/commit: _please provide_

## Additional context
Here's what I'm seeing:
<img width="234" alt="Screen Shot 2021-06-02 at 2 07 36 PM" src="https://user-images.githubusercontent.com/5965891/120552440-1d66ce00-c3ac-11eb-9312-a99d98ad4958.png">

**Comment by ConsciousCoder1** [comment]
Hello. Is this still in need of attention? Thanks

**Comment by paolodamico** [comment]
Hi @ConsciousCoder1! A PR for this is actually out, thanks for the interest! If you want to contribute to PostHog, there's a bunch of [great first issues](https://github.com/PostHog/posthog/labels/good%20first%20issue).
