### ISSUE TITLE
Allow updating existing custom filters in the Sessions page

### ISSUE THREAD

**Issue by Twixes** [PostHog/posthog#4579]
## Is your feature request related to a problem?

Currently saving each change in an existing custom filter creates a new saved custom filters. The old one can then be deleted but… that's ugly.

## Describe the solution you'd like

When a custom filter is selected, it should be possible to just update it.
This will require some changes to the `activeFilter` selector, as it currently works by using the filter data from URL params and going through all known saved filters. Currently the first saved filter that has exactly the same filter data as URL params is deemed the active one. Clever and mostly nice to use, but then when that filter is edited its data obviously no longer is exactly the same as URL params, so `activeFilter` automatically becomes `null`. A bit of a catch-22, would require an `activeFilter` _reducer_ probably.

![save](https://user-images.githubusercontent.com/4550621/120570246-fa720380-c417-11eb-9dbc-581b9a0bcd7d.png)

## Additional context

Noted as a nuisance by a user via Papercups.

**Comment by benjackwhite** [comment]
Pretty certain this can be closed but feel free to reopen with an up-to-date comment if I'm wrong
