### ISSUE TITLE
Release planning 1.27.0 1/2

### ISSUE THREAD

**Issue by timgl** [PostHog/posthog#4582]
Priorities
- Delighting 5 customers

**Comment by timgl** [comment]
# Team extensibility

Priorities
- Snowflake
- Making plugins more accessible
- feature flags

Yakko
- Add support for feature flags to node & react-native
  - https://github.com/PostHog/posthog-node/issues/14
  - https://github.com/PostHog/posthog-react-native/issues/25
- Metrics on event deliverability https://github.com/PostHog/posthog/issues/4577
- Migrate to flutter 2 https://github.com/PostHog/posthog-flutter/pull/10

Michael
- Consume fewer snowflake resources https://github.com/PostHog/snowflake-export-plugin/issues/3
- Console.log slow query warning https://github.com/PostHog/plugin-server/issues/424
- NaN issue with posthog_person https://github.com/PostHog/plugin-server/issues/458
- Last bits of action matching https://github.com/PostHog/plugin-server/issues/459
- Side quest: Sanitize timestamp before plugins https://github.com/PostHog/plugin-server/issues/410

Neil
- Have an amazing experience for submitting new plugins https://github.com/PostHog/plugin-server/issues/461
   -  this will need built in testing https://github.com/PostHog/posthog/issues/2768
   - .. and world class docs https://github.com/PostHog/posthog.com/issues/1396
- finishg adding bq_timestamp https://github.com/PostHog/bigquery-plugin/issues/8

**Comment by mariusandra** [comment]
# Team Core Experience

### Team Priorities
- Delight Big 5 by working on features/improvements based on their feedback and Deployments Team's.
- Seriously improve the perceived quality and stability of the app (from a frontend standpoint).

### 👀 Focus Tasks
- Alex: Various usability bugs, getting to know PostHog #4532 #4570 #4484 #4277 #4554 #4606 #4608
- Li: Taxonomy and event properties #4267
- Marius: Untangle insights and other URL logic #4329 #3868 #4483, cache common API endpoints (property definitions, etc) #4519 #4571 #4572
- Paolo: Tooltips (#4156) & legends (#4492) (engineering scope) & Product/UI/UX (https://github.com/PostHog/product-internal/issues/63, math property aggregator, filters parity, match groups).
- Sam: Convert charts to D3 #4568

### Side Quests
Check out our [project board](https://github.com/orgs/PostHog/projects/9) column "To Do 1.27 1/2".

**Comment by fuziontech** [comment]
# Team Infrastructure and Deploying

### Team Priorities
- Unlock rest of team to deliver and delight big 5 VIPs
- Seriously improve the trust that customers have in our cloud and deployed infrastructures. (speed and reliability)
### 👀 What we will work on
![image](https://user-images.githubusercontent.com/391319/120820708-a2b3c500-c509-11eb-91f0-bcc8bc324e46.png)
[board](https://github.com/orgs/PostHog/projects/10)

**Comment by EDsCODE** [comment]
# Core Analytics

**Buddy**
- Support funnel conversion window (#3877)
- Funnel user property bug (https://github.com/PostHog/product-internal/issues/44)
- View funnel trend people
- Test data from prod for local testing
- Test performance of funnel trend people groupArray() in prod
- Step funnel people pagination (#3491)

**Eric** 
- Support hero 2nd week
- #4625 precalculate actions
- Test/Get cohortpeople table migrated
- Exclusion Filters
     - https://github.com/PostHog/posthog/issues/4518
     - https://github.com/PostHog/posthog/issues/2978
- Breakdown issues
     - https://github.com/PostHog/posthog/issues/3897
     - https://github.com/PostHog/posthog/issues/4309

**Comment by paolodamico** [comment]
Sprint is over, closing
