### ISSUE TITLE
Overflowing funnels

### ISSUE THREAD

**Issue by alexkim205** [PostHog/posthog#4590]
## Bug description

When there're a lot of funnel steps, funnel overflows horizontally, rendering parts of the funnel inaccessible.

![Screen Shot 2021-06-03 at 4 20 32 PM](https://user-images.githubusercontent.com/13460330/120724039-da7a2880-c487-11eb-81ee-e49f66b970e5.png)

## Expected behavior

```
overflow-x: scroll;
```

## How to reproduce

1. Go to Insights -> Funnels
2. Add 10+ steps
3. Observe madness

## Environment

- [ ] PostHog Cloud
- [ ] self-hosted PostHog, version/commit: _please provide_

**Comment by paolodamico** [comment]
Great catch @alexkim205! Probably worth picking up this next sprint

**Comment by mariusandra** [comment]
Great catch indeed. This could also fall under the umbrella of #4568

**Comment by paolodamico** [comment]
As we're redoing the entire funnels experience and working on a design with this mind, think we could close this. Thoughts?

**Comment by mariusandra** [comment]
Indeed, let's put the effort into the future, not into the past :).
