### ISSUE TITLE
$set on event is broken

### ISSUE THREAD

**Issue by paolodamico** [PostHog/posthog#4592]
## Bug description

When running this code, the user property is no longer set. I have a suspicion it could be due to the GeoIP plugin, as the `$set` property on the parsed event only contains GeoIP properties, but couldn't find anything too obvious on the code.

```js
posthog.capture('some event', { $set: { userProperty: 'value' } });
```

## Expected behavior

Our library in theory handles setting user properties using an event (see https://posthog.com/docs/libraries/js#set). I would expect the user property to be set.

## How to reproduce

See code steps in section 1.

## Environment

- [ ] PostHog Cloud
- [X] self-hosted PostHog, version/commit: #4562.

**Comment by mariusandra** [comment]
This should fix it: https://github.com/PostHog/plugin-server/pull/462/files#diff-3a93e65b79a38797a40925bcdd428bb4f713d4eb61820f178318ed5969e40d69
