### ISSUE TITLE
[EPIC] Cloud performance improvements

### ISSUE THREAD

**Issue by fuziontech** [PostHog/posthog#4596]
@kpthatsme mentioned in https://github.com/PostHog/company-internal/issues/296 that there is some room for improvement on the query/insights front.

This is a placeholder for any work that may come up there.

**Comment by macobo** [comment]
We're sort of tackling the same thing here, so maybe this should focus on clickhouse queries&clickhouse speed specifically?

For "perceived slowness" issues like persistent 502 errors and loading too much data https://github.com/PostHog/posthog/pull/4571 are things I'm already tackling and team core experience will also tackle coming sprint.

**Comment by macobo** [comment]
Two easy ones from infra side:
- https://github.com/PostHog/posthog/issues/5244
- https://github.com/PostHog/posthog/issues/5307

**Comment by fuziontech** [comment]
Going to close this ticket for hygiene.
Use this to track performance progress:
https://github.com/PostHog/posthog/labels/performance
