### ISSUE TITLE
Creating one annotation creates two!

### ISSUE THREAD

**Issue by alexkim205** [PostHog/posthog#4608]
## Bug description

When creating an annotation from a line graph, we create two of the same annotations.

https://user-images.githubusercontent.com/13460330/120867778-7fa80600-c547-11eb-8c6a-cd1fa91873d8.mov

## Expected behavior

Create one annotation.

## How to reproduce

1. Go to Insights -> Trends (Line Graph)
2. Create an annotation

## Environment

- [X] PostHog Cloud
- [X] self-hosted PostHog, version/commit: _please provide_

**Comment by EDsCODE** [comment]
🤔

**Comment by alexkim205** [comment]
Whelp, I introduced this bug with #4564. I'm going to patch this in my next PR

**Comment by alexkim205** [comment]
Closed by #4610
