### ISSUE TITLE
Add "does not contain" to /action/

### ISSUE THREAD

**Issue by jamesefhawkins** [PostHog/posthog#461]
**Is your feature request related to a problem? Please describe.**
We current track DAUs based on the following action:

![Screenshot 2020-04-06 at 17 59 43](https://user-images.githubusercontent.com/47497682/78584639-6a92f280-7830-11ea-9761-f36beb596b69.png)

However, some users may visit app.posthog.com then NOT sign up, so we should exclude "exactly matches url https://app.posthog.com", but should include "URL contains app.", as currently this makes the DAUs look artificially high but it makes our retention look artificially worse.

**Describe the solution you'd like**
I want to exclude certain "exact match" URLs from the action definition.

It'd be logical whilst doing this to also enable excluding certain "contains" URLs from the action definition.

The alternative is to make it possible to add a NOT match type instead of where it says OR. That'd be harder I suspect? (although more powerful as it'd then allow excluding every other match time not just pageviews):

![Screenshot 2020-04-06 at 18 02 15](https://user-images.githubusercontent.com/47497682/78584862-cb222f80-7830-11ea-973a-f2529b978ec5.png)

**Describe alternatives you've considered**
I'd have to do the maths manually.

**Additional context**

**Comment by pauldambra** [comment]
You can now filter in groups

<img width="375" alt="Screenshot 2022-08-15 at 13 34 42" src="https://user-images.githubusercontent.com/984817/184635933-34853f49-b19d-40a1-be03-deb517b166f5.png">

Does that close this issue?

**Comment by neilkakkar** [comment]
~~Shoot~~ Close first, ask questions later 😂
