### ISSUE TITLE
Export button on Events and Persons pages errors

### ISSUE THREAD

**Issue by tiina303** [PostHog/posthog#4624]
## Bug description

When trying to export data from the Events (or Persons) page we run into server errors.
<img width="1067" alt="Screen Shot 2021-06-07 at 23 32 33" src="https://user-images.githubusercontent.com/890921/121090391-d41de080-c7e8-11eb-9b4d-df1e941acd96.png">
<img width="1050" alt="Screen Shot 2021-06-07 at 23 48 29" src="https://user-images.githubusercontent.com/890921/121091826-e567ec80-c7ea-11eb-9a84-3c7735a5d5cc.png">

When filtering down to one/few entries, then the export works fine.
The current limit of 100 000 is set here: https://github.com/PostHog/posthog/blob/610a79ca5f518e4c15e368851fe7d1d520119c10/posthog/api/event.py#L99

Related customer report: https://posthogusers.slack.com/archives/CT7HXDEG3/p1623049896143000

## Expected behavior

We default to a small enough number of entries to export by default that it works. 
We could consider providing more different options to export larger amounts of data.

## How to reproduce

1. Go to events page
2. Click on export
3. Wait and observe a 500s error

## Environment

- [x] PostHog Cloud
- [ ] self-hosted PostHog, version/commit: _please provide_

#### *Thank you* for your bug report – we love squashing them!

**Comment by mariusandra** [comment]
This has come up repeatedly this week in support.

**Comment by mariusandra** [comment]
Adding related ideas for when someone works on this:
- In the events table it should be possible to choose what columns/properties your table has (e.g. choose `properties.$geoip_country` if you want). We even have a [column configurator](https://github.com/PostHog/posthog/blob/b0463d693958e673d1e2ea625083edb294e410c1/frontend/src/lib/components/ResizableTable/TableConfig.tsx#L49-L57) we could use.
- This button should then give you an export with the same columns, and/or let you choose what columns to export in a modal.
- It would also let you choose the limit, so you could try with 10k rows if 100k timeouts.
- The tricky part is exporting elements. Right now this csv export is the only place you can get `data-attr` values on events, for example to do [manual breakdown on them](https://github.com/PostHog/posthog/issues/5914). So support for this should remain.
- Perhaps `/api/events` could get a timeout exception in cloudflare? Is that a feature?

**Comment by pauldambra** [comment]
events and persons CSV download works

events is limited to 3500 (until we can notify users of slower export generation)
and persons to 10000
