### ISSUE TITLE
Insights trying to adding a filter crashes

### ISSUE THREAD

**Issue by tiina303** [PostHog/posthog#4626]
## Bug description

Trying to add a filter crashes about every 2nd time after clicking on filters and then add filter.
Related user report with a video: https://posthogusers.slack.com/archives/CT7HXDEG3/p1623119814156600?thread_ts=1623043305.137300&cid=CT7HXDEG3

## Expected behavior

Page loads fine and we can add a filter.

## How to reproduce

1. In the insights tab if we click on the filter icon (1)
2. then "add filter" (2)
3. if it didn't error, click (1) and restart from step 1. (I sometimes needed to do this 3 times, but it repros pretty consistently).

<img width="608" alt="Screen Shot 2021-06-08 at 05 16 19" src="https://user-images.githubusercontent.com/890921/121117683-d13ae400-c818-11eb-8d14-2ec15622fe9c.png">'

## Environment

- [x] PostHog Cloud
- [ ] self-hosted PostHog, version/commit: _please provide_

## Additional context

The errors I saw in developer tools that I believe are related:
<img width="565" alt="Screen Shot 2021-06-08 at 05 09 56" src="https://user-images.githubusercontent.com/890921/121118616-73a79700-c81a-11eb-96b1-61dbbfdc2bcd.png">

**Comment by macobo** [comment]
https://github.com/PostHog/posthog/pull/4617

**Comment by mariusandra** [comment]
@tiina303 can you confirm if it's fixed for you after https://github.com/PostHog/posthog/pull/4617 got merged and then close this issue?

**Comment by tiina303** [comment]
No it's not fixed, I was able to repro it just now on `app.posthog.com` & the error is a bit different:
<img width="401" alt="Screen Shot 2021-06-08 at 14 09 48" src="https://user-images.githubusercontent.com/890921/121182308-3e736700-c863-11eb-9687-ff888a5faf14.png">

cc @samwinslow
