### ISSUE TITLE
distutils is deprecated in Python 3.10 and will be removed by Python 3.12

### ISSUE THREAD

**Issue by tirkarthi** [PostHog/posthog#4629]
## Bug description

strtobool is used in several places where it will cause deprecation warning in Pythin 3.10 and error in Python 3.12 since distutils will be removed in Python 3.12 .

Reference : https://www.python.org/dev/peps/pep-0632/

```
rg distutils                     
posthog/api/annotation.py
1:from distutils.util import strtobool

posthog/api/dashboard.py
2:from distutils.util import strtobool

posthog/api/insight.py
1:from distutils.util import strtobool

posthog/models/filters/mixins/common.py
4:from distutils.util import strtobool

posthog/settings.py
17:from distutils.util import strtobool
```

## Expected behavior

It's a good idea to vendor in the function as it's a short one.

## Environment

- [ ] PostHog Cloud
- [ ] self-hosted PostHog, version/commit: _please provide_

**Comment by Twixes** [comment]
Thank you for bringing this up! Was planning to do this anyway since we used slightly different versions of this function in different repos. Now resolved with #4631.
