### ISSUE TITLE
Heatmaps not working?

### ISSUE THREAD

**Issue by timgl** [PostHog/posthog#4635]
## Bug description

[internal] go to posthog.com, click the toolbar, click heatmap. 0 events being returned from the `api/element/stats` endpoint

## Expected behavior

Heatmap should work

## How to reproduce

1.
2.
3.

## Environment

- [ ] PostHog Cloud
- [ ] self-hosted PostHog, version/commit: _please provide_

**Comment by mariusandra** [comment]
Duplicate of https://github.com/PostHog/posthog/issues/4575 :)
