### ISSUE TITLE
Histogram viz for Sessions distribution

### ISSUE THREAD

**Issue by alexkim205** [PostHog/posthog#4643]
## Is your feature request related to a problem?

Currently, there is no way of visualizing a distribution of sessions as a histogram. The user is only given the option to display a distribution in table format, which is difficult to scan quickly. 

![Screen Shot 2021-06-08 at 11 32 18 AM](https://user-images.githubusercontent.com/13460330/121239238-d5cdbf80-c84d-11eb-85a9-ee7f912cd4d8.png)

## Describe the solution you'd like

A histogram is a standard way of visualizing distribution data. Perhaps we can piggyback on the existing Bar Value Graph that we have enabled for other Insight tabs.

## Describe alternatives you've considered

N/A

## Additional context

Perhaps this could fall under @samwinslow's D3 revamp, but if it's out of scope I'd be happy to pick it up.

**Comment by paolodamico** [comment]
Could potentially be a duplicate of #4347 ? Particularly if we consider getting #4348 in

**Comment by alexkim205** [comment]
Oh awesome thanks for the context--this is totally a duplicate. I'll close this for now and reference it in the tracking ticket
