### ISSUE TITLE
Feature flag `4156-improved-graphs` bug reports

### ISSUE THREAD

**Issue by mariusandra** [PostHog/posthog#4647]
## Bug description

Now that https://github.com/PostHog/posthog/pull/4529 is in behind feature flag `4156-tooltips-legends` (not rolled out), here are some bugs I've found.

The perfect combination is when the list is very long and also quite wide:

![2021-06-08 22 21 03](https://user-images.githubusercontent.com/53387/121252092-e6ab1f00-c8a7-11eb-9a61-d36cf6ccf0f7.gif)

- Problems with wrapping when viewing the rightmost values
- Can't sometimes see the end of the list
- The tooltip covers the entire graph

Limiting the breakdown count might be a option, but who knows what other large combination of data flows by.

## Expected behavior

If I want my lines broken down by URL, I should get my lines broken down by URL, damnit! 😆 

## How to reproduce

1. Enable flag `4156-tooltips-legends`
2. Make a ridiculous graph
3. Laugh

## Environment

- [ ] PostHog Cloud
- [ ] self-hosted PostHog, version/commit: _please provide_

**Comment by paolodamico** [comment]
Thanks @mariusandra! Way ahead of you 😉 #4651 (though still not ready yet)

**Comment by mariusandra** [comment]
Fair point. Moved my gif there and closing this.
