### ISSUE TITLE
Docs link under settings to send custom events gives 404

### ISSUE THREAD

**Issue by tirkarthi** [PostHog/posthog#4661]
## Bug description

"visit PostHog Docs" link under settings -> send custom events gives 404 as it links to https://posthog.com/docs/integrations .

## Expected behavior

I guess the correct link has to be https://posthog.com/docs/libraries

## How to reproduce

1. Go to https://app.posthog.com/project/settings
2. Click "visit PostHog Docs" link under send custom events section
3. Link gives 404

## Environment

- [x] PostHog Cloud
- [ ] self-hosted PostHog, version/commit: _please provide_

**Comment by tirkarthi** [comment]
Similar issue with "You can use this write-only key in any one of our libraries." . It seems other links like integrations/slack resolve to libraries/slack as a redirect though the main page itself.

Probably a redirect needs to be added similar to https://github.com/PostHog/posthog.com/blob/f746db9a21481745d48fd74bea0b774f45c9d015/netlify.toml#L1

or there could be a change to docs here similar to https://github.com/PostHog/posthog.com/pull/1214

Feel free to close this if it's tracked somewhere else. Thanks.

**Comment by joethreepwood** [comment]
Excellent catch, thank you @tirkarthi !
