### ISSUE TITLE
Adding a filter in Sessions page crashes

### ISSUE THREAD

**Issue by tiina303** [PostHog/posthog#4665]
## Bug description

Adding a filter in the sessions page crashes.

## Expected behavior

We don't crash

## How to reproduce

1. On the sessions page try to add a filter (tried to select Browser)
<img width="928" alt="Screen Shot 2021-06-09 at 15 55 27" src="https://user-images.githubusercontent.com/890921/121368293-41418b00-c93b-11eb-8517-f89870a104af.png">
<img width="947" alt="Screen Shot 2021-06-09 at 15 56 01" src="https://user-images.githubusercontent.com/890921/121368305-443c7b80-c93b-11eb-91c9-cd7b021af0be.png">

## Environment

- [x] PostHog Cloud
- [ ] self-hosted PostHog, version/commit: _please provide_

## Additional context

Looks similar to an earlier issue on the insights page https://github.com/PostHog/posthog/issues/4626

**Comment by macobo** [comment]
@samwinslow @tiina303 can this now be closed?
