### ISSUE TITLE
Posthog actions lose icon when there is only one step

### ISSUE THREAD

**Issue by alexkim205** [PostHog/posthog#4669]
## Bug description

Minor UX bug

The PostHog icon disappears whenever there is only one step in the funnel.

https://user-images.githubusercontent.com/13460330/121400300-4804d980-c90c-11eb-8063-e0263340010a.mov

## Expected behavior

PostHog icon should persist regardless of num. of steps.

## How to reproduce

1. Insights > Funnels
2. Add PostHog filter step
3. Add another one

## Environment

- [X] PostHog Cloud
- [X] self-hosted PostHog, version/commit: _please provide_

**Comment by mariusandra** [comment]
The linked PR didn't solve the issue with the icon being squished, just added one more "delete" button. Thus reopening.

**Comment by alexkim205** [comment]
@mariusandra 

I might not be looking in the right places, but I can't seem to find the icon being squished in cloud. Could you share a link/screenshot?

I think we introduced the bug when we removed the delete button, because the inner div wasn't taking up the entire width of the antd row. I figured that it also made sense from a UX perspective to bring back the delete functionality. 

My pr indirectly fixes the issue, but are you looking for a more direct fix here?

**Comment by mariusandra** [comment]
@alexkim205 hmm, you're right. I can't reproduce it anymore :).
