### ISSUE TITLE
Unable to delete organization after confirming organization name

### ISSUE THREAD

**Issue by the-wc** [PostHog/posthog#4677]
## Bug description

*Please describe.*  
*If this affects the front-end, screenshots would be of great help.*  

After you type in your organization name and confirm deletion, the organization is not removed from your organizations' list.

## Expected behavior
Organization should be removed, once you click on Delete <Organization Name> button after you confirm it.

## How to reproduce

1. From home, click on your profile picture to trigger the drop down navigation bar.
2. Click on "Organization Settings"
3. Scroll to section "Danger Zone" and click "Delete <Organization name>"
4. Type in the organization name and click Delete.

## Environment
Firefox v89.0
- [x] PostHog Cloud
- [ ] self-hosted PostHog, version/commit: _please provide_

**Comment by liyiy** [comment]
@Twixes Are we allowed to delete all organizations? The deletion doesn't work if it's the organization you originally signed up with

**Comment by the-wc** [comment]
@liyiy I had that issue with an organization that I had not signed up with too.

**Comment by Twixes** [comment]
This should absolutely be possible. Just tried with a fresh Cloud account and was good. I think this may be an issue with Django signals – before an organization is deleted we make sure all its teams are deleted. And before a _team_ is deleted, we make sure that all its Postgres events and element groups are deleted. Maybe that takes too long sometimes?

**Comment by paolodamico** [comment]
I believe this has been address now, closing.
