### ISSUE TITLE
Breakdown by cohorts is confusing and/or buggy

### ISSUE THREAD

**Issue by paolodamico** [PostHog/posthog#4696]
## Is your feature request related to a problem?

Currently we support breaking down a trend graph by cohorts, but this presents a lot of confusion points:
1. Feature is not easily discoverable and it's use is unclear. It takes a while to understand that you can select multiple cohorts to compare behavior for different cohorts. Is breakdown the right mental model for this?
When you overcome the above, there's some weird behavior,
2. See [example](https://app.posthog.com/insights?insight=TRENDS&display=ActionsLineGraph&events=%5B%7B%22id%22%3A%22%24pageview%22%2C%22name%22%3A%22%24pageview%22%2C%22type%22%3A%22events%22%2C%22order%22%3A0%7D%5D&properties=%5B%5D&filter_test_accounts=true&breakdown=%5B71%2C98%5D&breakdown_type=cohort&date_from=-30d&interval=week) of selecting two cohorts leading to no data. The test accounts filter should exclude "PostHog Team" but not "Real Users".
3. [Removing the test filter](https://app.posthog.com/insights?insight=TRENDS&display=ActionsLineGraph&events=%5B%7B%22id%22%3A%22%24pageview%22%2C%22name%22%3A%22%24pageview%22%2C%22type%22%3A%22events%22%2C%22order%22%3A0%7D%5D&properties=%5B%5D&filter_test_accounts=false&breakdown=%5B71%2C98%5D&breakdown_type=cohort&date_from=-30d&interval=week) leads to numbers matching exactly, which is incorrect. While these cohorts are mutually exclusive, I would expect to see both graphed correctly.
4. Another [example](https://app.posthog.com/insights?insight=TRENDS&display=ActionsLineGraph&events=%5B%7B%22id%22%3A%22%24pageview%22%2C%22name%22%3A%22%24pageview%22%2C%22type%22%3A%22events%22%2C%22order%22%3A0%7D%5D&properties=%5B%5D&filter_test_accounts=true&breakdown=%5B71%2C6%5D&breakdown_type=cohort&date_from=-30d&interval=week) of cohorts just matching data points exactly.
    <img width="591" alt="" src="https://user-images.githubusercontent.com/5864173/121575442-6692cf80-c9f5-11eb-90a4-06dc3313e124.png">
5. We show cohort ID in places instead of the cohort name.

## Describe the solution you'd like

Section above provides expectations of how this could potentially work.

## Describe alternatives you've considered

Removing the ability to breakdown by cohorts?

## Additional context

This is how He@p handles the concept of what on PostHog is "breaking down by cohorts".
<img width="634" alt="" src="https://user-images.githubusercontent.com/5864173/121574989-d5bbf400-c9f4-11eb-8b5b-c77c99f51d22.png">

**Comment by macobo** [comment]
As a bug it's a bit unclear what the desired action here is or if there are multiple bugs rolled into one. 

(Or it might be late and my brain is not functioning)

Can we clarify this ticket a bit?

**Comment by paolodamico** [comment]
Sorry let me clarify. Problem was that when doing breakdowns on a graph, we have the option to do breakdowns by cohorts. Yet, the experience of doing this is not intuitive. Is not clear what "breaking down by a cohort" is actually doing. Until you actually select multiple cohorts you understand what this is for.

All the above being said, @mariusandra did make a great improvement once you've added your first cohort (it says add cohort vs. being a multiselect). Outstanding problem is that it's not obvious that you can compare cohorts by adding a breakdown.

**Comment by macobo** [comment]
Ah nice! Given the current focus of the teams, I think this makes a bit more sense in core-experience backlog given extra design capacity? :)

**Comment by paolodamico** [comment]
Definitely, the bugs scoped to Core Analytics seem to have been fixed now

**Comment by paolodamico** [comment]
This has been improved but I still think we can improve discoverability of the feature. CC @clarkus

**Comment by clarkus** [comment]
Some questions to clarify how this should be working:
- It seems we can only breakdown by one property type at a given time. For example, I can't breakdown by a cohort and a person property simultaneously. 
- Cohorts are the **only** case for a multiple-select workflow in breakdowns. 

Sound accurate, @paolodamico?

**Comment by clarkus** [comment]
Here's a concept that changes "breakdowns" into a "group by" context. When grouping by cohorts, the user is presented with a multiple select. When grouping by any other property type, the user directly selects the property they want to group by. Scenarios in order of appearance: cohorts, persons, events, actions, groups, and lastly a placeholder. These wouldn't coexist, I'm just showing the variants we'd need to support. 

![Group by](https://user-images.githubusercontent.com/254612/144121347-f37570a9-3e59-41ff-a2ec-259f849b4b35.png)

https://www.figma.com/file/gQBj9YnNgD8YW4nBwCVLZf/PostHog-App?node-id=5569%3A33023

**Comment by paolodamico** [comment]
1. Yes, you can only breakdown either by cohorts or by properties.
2. With the work @pauldambra is doing you will be able to add multiple breakdowns.
3. Really like the new design, I think it definitely solves the problem. Only thing I'm unclear is how you would select whether to filter by cohorts, properties, ... in the first place? (i.e. the first dropdown that says "Cohorts")

**Comment by clarkus** [comment]
> 1. Yes, you can only breakdown either by cohorts or by properties.
> 2. With the work @pauldambra is doing you will be able to add multiple breakdowns.
> 3. Really like the new design, I think it definitely solves the problem. Only thing I'm unclear is how you would select whether to filter by cohorts, properties, ... in the first place? (i.e. the first dropdown that says "Cohorts")

Yeah I think we'll need some initial selection to scope the subsequent list of options. I've updated the designs to clarify. 

![Group by](https://user-images.githubusercontent.com/254612/144136609-3a911a7d-bf44-4378-8953-4827bb8d974a.png)

https://www.figma.com/file/gQBj9YnNgD8YW4nBwCVLZf/PostHog-App?node-id=5569%3A33023

**Comment by pauldambra** [comment]
> With the work @pauldambra is doing you will be able to add multiple breakdowns.

Currently there's a single `breakdown_type` so even with multi breakdown (right now) once you have chosen event or cohort etc you can only select another property of the same type

We've started changing the API so that each breakdown property carries it's own type

e.g. 

from `{breakdown: "potato", breakdown_type: "fruit"}`

to `{breakdowns: [{property: "potato", type" fruit"}, {property: "tomato", type" color"}]}`

*but* the underlying query assumes one breakdown_type still. In cutting scope I didn't figure out how to have multiple coexisting types

**Comment by paolodamico** [comment]
The new taxonomic filter and UX for cohort breakdown solves this already 🎉
