### ISSUE TITLE
Playback session recording in Safari not working

### ISSUE THREAD

**Issue by weyert** [PostHog/posthog#4698]
## Bug description

If you try to playback an existing session recording in Safari (Version 14.1.1 (16611.2.7.1.4)) the session player IFRAME won't get correctly loaded due to a script error. Also it appears the page starts to hang and the tab/browser becomes unresponsive. 

## Expected behaviour
Able to playback the session recording in Safari (macOS 11.4 (20F71)) 

## How to reproduce

1. Open Safari on macOS
2. Select an existing session recording (feel free to reach out to get the problematic recording)
3. Notice in dev tools the following error: `Blocked script execution in 'about:blank' because the document's frame is sandboxed and the 'allow-scripts' permission is not set.`

## Environment

- [X] PostHog Cloud
- [ ] self-hosted PostHog, version/commit: _please provide_

## Additional context
None

**Comment by tiina303** [comment]
A bit more info in this thread: https://posthogusers.slack.com/archives/G01JXEDAL22/p1623369596019100
Playing a random session on Safari 14.0.3 worked fine for me.

**Comment by weyert** [comment]
Yes, I am not sure what the problem is but I am getting that error which might be related. I have the same issue in the latest Safari Technology Preview. I will try it out on a different computer to be sure. I can confirm it works fine in Chrome

**Comment by marcushyett-ph** [comment]
@weyert is this now working okay for you in Safari?

**Comment by weyert** [comment]
@marcushyett-ph Looks like it. Not sure what went on previously.
