### ISSUE TITLE
User Paths dropdown UX feels buggy

### ISSUE THREAD

**Issue by samwinslow** [PostHog/posthog#4703]
## Bug description

User Paths needs more than cosmetic fixes — we need to consider reorganizing the architecture of information shown to the user, and also the underlying data structures. It took me hours to understand how I'd even use this feature.

- I thought the app was broken and leaking DOM strings here. We should show HTML element tags with distinct typography.

<img width="550" alt="Screen Shot 2021-06-10 at 4 55 42 PM" src="https://user-images.githubusercontent.com/4645779/121595835-b3ce6b80-ca0c-11eb-9096-fc5a2d52e645.png">

- Why are we separating autocaptured vs. custom events? It seems like we don't do this in other parts of the app.
- We should not refer to URLs as "elements".
- Revise empty-state copy: makes reference to `$pageview` when this may or may not be relevant.

## Expected behavior

Unified menu such as we are now using for property filters elsewhere. Icons to differentiate events, URLs, and DOM elements.

![image](https://user-images.githubusercontent.com/4645779/121596155-1889c600-ca0d-11eb-8693-5921ec497f7b.png)

## How to reproduce

1. Use anything other than the defaults in User Paths, and observe as if you were a first-time user.

## Environment

- [ ] PostHog Cloud
- [ ] self-hosted PostHog, version/commit: _please provide_

**Comment by marcushyett-ph** [comment]
This will likely be valuable for our next milestone

**Comment by paolodamico** [comment]
This has been fixed by the new paths UI.
