### ISSUE TITLE
User Paths graph (Sankey diagram) not rendering correctly in Chrome

### ISSUE THREAD

**Issue by samwinslow** [PostHog/posthog#4704]
## Bug description

Chrome v91:

<img width="868" alt="Screen Shot 2021-06-10 at 5 05 55 PM" src="https://user-images.githubusercontent.com/4645779/121597058-3b68aa00-ca0e-11eb-9b96-5e4d1782633b.png">

Safari (as expected):

<img width="752" alt="Screen Shot 2021-06-10 at 5 06 53 PM" src="https://user-images.githubusercontent.com/4645779/121597072-43284e80-ca0e-11eb-842a-3e300beb5aed.png">

## How to reproduce

1. Checkout `master@fd24056e20b5c76a0056e61f501878216be579fb`
2. Reproducible as far back as release 1.24 — maybe even earlier (trouble building 1.23 on M1 Mac)

## Environment

- [ ] PostHog Cloud
- [ ] self-hosted PostHog, version/commit: `master@fd24056e20b5c76a0056e61f501878216be579fb`

**Comment by mariusandra** [comment]
Works for me 🤔 

![image](https://user-images.githubusercontent.com/53387/121650679-14f05080-ca9a-11eb-9b5a-6499d473db6c.png)

**Comment by marcushyett-ph** [comment]
Is this resolved now? If not we should fix this as part of our next milestone?

**Comment by samwinslow** [comment]
I'll close it out as I am no longer able to reproduce it either. 🤷‍♂️
