### ISSUE TITLE
WIP Boost AWS guidance for deployment and upgrading PostHog

### ISSUE THREAD

**Issue by Tannergoods** [PostHog/posthog#471]
***Thank*** you for your feature request - we love each and every one :)

**Is your feature request related to a problem? Please describe.**
Our deployment docs are well served for Docker and Heroku but lacking in AWS guidance for deployment if a user wanted to host on AWS directly

**Describe the solution you'd like**
Clearer guidance on hosting on AWS or something similar to Heroku deploy like: https://docs.aws.amazon.com/amplify/latest/userguide/one-click.html

**Describe alternatives you've considered**
We can encourage Heroku deployments if easier

**Additional context**
Requested by current users

**Comment by jamesefhawkins** [comment]
I could see 4 simple versions to start with:

- [ ] EC2
- [ ] EC2 w/ separate postgres
- [ ] Lightsail
- [ ] Lightsail w/ separate postgres

And a few more thanks Sanket:

- [ ] AWS Fargate
- [ ] GCP Cloud Run
- [ ] Azure Container Instances

**Comment by SanketDG** [comment]
If you are also looking at other cloud providers, something like "Run a container" as a service, there are also these:

- AWS Fargate
- GCP Cloud Run
- Azure Container Instances

**Comment by jamesefhawkins** [comment]
Agreed @SanketDG. Those all look good - I've edited the list above.

@Tannergoods - Amplify is a Heroku alternative (and would be a cool way for people to deploy into AWS). Was the user specifically suggesting that we offer an Amplify deployment as a simpler way to implement in AWS or that we just document how to set up PostHog in AWS?

**Comment by Tannergoods** [comment]
The user did not specify Amplify the key was for documentation but felt perhaps the two should be linked given the way we document deployment with Heroku

**Comment by BentoumiTech** [comment]
I was trying to set up PostHog on EC2 with ansible, I could share the script once it's done if you are interested.

**Comment by jamesefhawkins** [comment]
100% @BentoumiTech that'd be awesome

**Comment by Twixes** [comment]
I think we've streamlined this somewhat since.
