### ISSUE TITLE
Allow specifying a project (team) when hitting an API endpoint

### ISSUE THREAD

**Issue by yakkomajuri** [PostHog/posthog#4713]
Not sure whether to label this as a bug or feature request.

We infer the project a person is interacting with when an API endpoint is hit. This is perfectly fine when we think of a user as a person interacting with the PostHog UI. However, it is not fine when hitting the API programmatically using personal API keys.

Today, if I hit the API with a personal API key, even if I pass in a project API key, I'll get a response for the last project I looked at in PostHog. This is super problematic for e.g. backend feature flags, where if I suddenly visit a project on the UI, my API call will yield totally different responses (happened to me).

The solution for this particular problem is to add a param to the API to specify the project.

**However**, this got me thinking about how the way we do feature flags in backend libs isn't optimal. I think we could have an endpoint that can be authenticated to with a project API key only and returns only flag key, `is_simple_flag`, and `rollout_percentage`.

Or would `rollout_percentage` be giving away too much?

Ultimately it's a bit weird we ask people to add a personal api key for feature flags, which can access all projects, instead of a project-specific key.

Thoughts? @neilkakkar @timgl @Twixes

**Comment by neilkakkar** [comment]
Interesting, what is the idea behind having a personal API key for feature flags? 
Also, are these flags set per user, or per project?

On a more relevant side note: I see `_get_project_id()` which gets the project ID from the request body, isn't this exactly what should happen? I don't understand how the project can dynamically change when you pass in the `project_id` / Project key and personal key both.

**Comment by yakkomajuri** [comment]
> Interesting, what is the idea behind having a personal API key for feature flags?

If you're using flags client-side (web, mobile), there is only one user the library needs to concern itself with. So it calls `/decide/` passing that user's ID and asks "hey, what flags are on for this user?", it stores it locally, updates this at an interval and that's that.

Server-side though, you have a bunch of distinct ids using the same service (assume infinity for all intents and purposes). That means we can't proactively ask for feature flags, we need to wait for the program to ask if a flag is on for a given user. The simple thing to do here is an API request to PostHog and be done with it. However, what if I want to use feature flags to determine routing of my application, or to serve a different response? Things would get pretty slow because you have to wait for a response from posthog.

The middle-ground solution we came up with was `is_simple_flag`. If a flag has no filters, we can compute it locally without a request, making it much faster. This allows people to use some flags for the use cases mentioned above. Problem is, to get details on any feature flag atm, one needs to be authenticated (rightfully so, this is private data), and to check if a flag is simple and what percentage of users it's rolled out to we need to go through this auth step.

> Also, are these flags set per user, or per project?

Feature flags are specified at a project-level and are on/off at a user level. i.e. `flag-a` on `PostHog App + Website` will be on for User A but not User B. It won't exist for a user on project `Rudder Test`

> On a more relevant side note: I see _get_project_id() 

My proposal here is essentially to use this on the other endpoints as well, as it currently only applies to `decide` and `capture`, which are "public" endpoints that never return sensitive data.

@neilkakkar

**Comment by Twixes** [comment]
Very closely related to #1343.
I once attempted to do exactly this in #2445, but it proved too large of a task to safely pull off all at once, so at the time I only moved what I needed (hence we now have `StructuredViewSetMixin`) in #2616. Haven't seen a direct need for more migrations since then, though it definitely could come in useful.

**Comment by yakkomajuri** [comment]
Here's a proposal for getting rid of personal API keys for feature flags for good (they're annoying, confusing, add overhead to devs, and cause this problem mentioned in the issue): an endpoint that uses the project api key (token) to return the following info about that project's flags:

1. Rollout percentage
2. A hash of their key

This way the endpoint is safe (doesn't reveal info about a company's experiments), and we can find the flag on the libraries by hashing the flag key the user passed in and comparing that.

Thoughts?

**Comment by mariusandra** [comment]
Isn't the token / project API key public? E.g. if you steal if from the posthog-js init call, you'll have access to all feature flags used by a team?

**Comment by mariusandra** [comment]
Sry, just read "hash of their key"  (not just "the key").

For this to work, we need a very strong salt. Just hashing the key with a publicly available algorithm (everyone can see we do `md5(key + " is a hedgehog")`) leads to keys that can be cracked in no time.

**Comment by yakkomajuri** [comment]
Well, ideally we would use something modern like SHA2/SHA3 (instead of MD5) to start with. But yes, a salt should be used too. 

Happy to take other suggestions here though

**Comment by yakkomajuri** [comment]
Side note to self: seems we also don't handle a simple flag being disabled on the libs

**Comment by yakkomajuri** [comment]
Been doing some thinking and a bit of researching here, and considering how we might find a balance between the tradeoffs we have. 

**Tradeoff 1:** Speed of response from `isFeatureEnabled`. The whole reason we have this personal API key system in play is so that we can provide a faster response for flags that are rollout percentage only without having to hit `/decide/`. If we didn't care about speed at all we might as well just hit `/decide/` for everything, scrap the poller and simplify the 300 lines of concurrent Go code into 50. 
**Tradeoff 2:** Security. We don't want client's feature flag data available to the world.

Hashing + salt are a nice way to balance both of these. However, the strength of the salt affects the speed of the response. Hence, a proposal (from someone who isn't a security expert):

1. Endpoint returns **only** simple flags, providing **only** the hash and the rollout percentage. Filtered flags aren't exposed at all.
2. Hash is done using a non-bruteforceable algorithm (e.g. [SHA256](https://crypto.stackexchange.com/questions/1145/how-much-would-it-cost-in-u-s-dollars-to-brute-force-a-256-bit-key-in-a-year/1160#1160), yet)
3. Salt is a random value with a significant but not massive number of possibilities (10000, 100000?): this way, rainbow table attacks are out of the question, and so are plain brute force attacks. What's not out of the table is a smart brute force attack relying on probabilities and reasonable assumptions (like flag keys probably rarely go over 12 chars, they contain valid English words etc), but those become significantly more difficult, and all one would ever get is a flag's key and rollout percentage, nothing else. Mind you keys are actually somewhat public anyway, since they are used client-side too. We can't use standard salting mechanisms because the hash validation will be done in a separate context from the hashing, whereas salts (e.g. for passwords) are normally stored in the database (often alongside the hashed password even), so our libs will actually be performing a brute force on the hash, knowing the key but not the salt.

**Comment by yakkomajuri** [comment]
Another note on the above - one would have a much easier time estimating the rollout percentage of a flag opening 10/100/1000... incognito browser windows and hitting the dev console to see what flags are enabled

**Comment by yakkomajuri** [comment]
Also could be worth adding a note in the UI that feature flag keys are public (they already are), just so people are less incentivized to add any sensitive info in the key, and rather use the description for that

**Comment by yakkomajuri** [comment]
Will make a new issue for api key stuff. The issue described here was fixed in #4764
