### ISSUE TITLE
don't redirect to https on `/_health/`

### ISSUE THREAD

**Issue by kilianc** [PostHog/posthog#4726]
## Bug description

Since TLS is provided by the proxy and not by posthog itself, but posthog redirects all http traffic to https, all healthchecks that are common in orchestration systems will fail. An `http` call to `_health` will respond with a `301` and a An `https` call to `_health` will hang.

## Expected behavior

Do not redirect `http` calls to `_health` to `https`

## How to reproduce

1. Deploy behind a proxy
2. Enable SSL redirect in posthog
3. Set _health as health check on localhost

## Environment

- [ ] PostHog Cloud
- [x] self-hosted PostHog, version/commit: _please provide_

**Comment by Twixes** [comment]
Hey! Have you configured your PostHog instance for running behind a proxy ([PostHog Docs page](https://posthog.com/docs/configuring-posthog/running-behind-proxy)) – `IS_BEHIND_PROXY` et al? That should resolve the issue I suppose

**Comment by kilianc** [comment]
Yes I have, is `IS_BEHIND_PROXY` stopping the redirect? That was not my experience. I had to explicitly set `DISABLE_SECURE_SSL_REDIRECT` to false and handle the redirect at the load balancer level.

**Comment by Twixes** [comment]
Yep, that's exactly the setting that has to be set in addition to `IS_BEHIND_PROXY` to prevent this. Is your issue solved in this case?

**Comment by kilianc** [comment]
I think there might be a misunderstanding here, I think the improvement should be that `/_health/` should not redirect to https. Regardless of the flags since the TLS is handled outside posthog, the health-checks are usually run locally in an orchestrator.
