### ISSUE TITLE
Toggles should give immediate feedback

### ISSUE THREAD

**Issue by yakkomajuri** [PostHog/posthog#4741]
Another tiny UX thing that slowly drives me nuts is how almost none of our toggles give immediate feedback.

Feature flags and session recording toggles wait a bit and then update, and plugin toggle asks for confirmation.

This is not at all what I expect from a toggle. I expect immediate feedback as is the case with toggles on our phones which we use regularly.

## Solution

Immediate feedback on the UI + background processing. For toggles that need confirmations and things, maybe they shouldn't be toggles? Could be buttons?

**Comment by clarkus** [comment]
General rules for when to use a toggle or a checkbox:

- If the result of acting on the component takes immediate effect, it should be a toggle. It's like a light switch. You flip it and it's on. 
- If the result of acting on the component does not take immediate effect, or requires some secondary action to submit the change, it should be a checkbox.
