### ISSUE TITLE
Allow selection of property AND action in cohort builder

### ISSUE THREAD

**Issue by joesaunderson** [PostHog/posthog#4745]
## Is your feature request related to a problem?

We are trying to define a cohort representing daily active (non-internal) users. Currently, the cohort builder only allows selection of `action` or `property`. 

## Describe the solution you'd like

To achieve this, we'd like to be able to select `action = pageview` AND `property = non-internal`.

## Describe alternatives you've considered

Creating a separate pageview event for non-internal users, but this feels like bloat (a separate page view for each cohort we want to track).

## Additional context

Conversation on the PostHog users Slack: https://posthogusers.slack.com/archives/CT7HXDEG3/p1623667100242700

**Comment by paolodamico** [comment]
Hey @joesaunderson! Thanks for reporting this, definitely very helpful. We'll take a look soon at the best way to support this. Supersedes #3572.
