### ISSUE TITLE
Allow rich datapoint view from dashboard

### ISSUE THREAD

**Issue by joesaunderson** [PostHog/posthog#4747]
## Is your feature request related to a problem?

When I use the insights, I can click on a data point and see the list of users who make that point on the graph. When I save this to the dashboard, I cannot click on the datapoint.

## Describe the solution you'd like

Allow clicking on the datapoint from a dashboard.

## Describe alternatives you've considered

Clicking "View graph" and going back to the insights page

## Additional context

N/A

**Comment by paolodamico** [comment]
Hey @joesaunderson! I'm curious why you'd want to click on a data point from a dashboard, as we're treating this as a "presentation" mode, and would assume you click on the insight to get more details (including the person modal)

**Comment by joesaunderson** [comment]
> Hey @joesaunderson! I'm curious why you'd want to click on a data point from a dashboard, as we're treating this as a "presentation" mode, and would assume you click on the insight to get more details (including the person modal)

For me this specific use case was for how we use some of our dashboards.

Say we release a feature, we tend to build a dashboard for it whilst it's in 'beta'.

When looking at this dashboard, it would be good to see who's using the feature - and the person modal is pretty easy... I get I can click into the insight, but it saves an extra click / page. 

And it's not intuitive how to get from a dashboard to the insight (it's in the ... menu).

**Comment by paolodamico** [comment]
Got it! @clarkus one thing I think we should definitely do is improve the UI to make it clear that you can click on the dashboard title to go to the insight.
