### ISSUE TITLE
Back button doesn't work as expected: Cohorts -> Sessions

### ISSUE THREAD

**Issue by corywatilo** [PostHog/posthog#4748]
Super minor, but falls under the realm of _a bunch of little (UX) things add up_...

## Bug description

When being referred to Sessions from the Cohorts tab, the back button doesn't return me to Cohorts. (There seem to be a couple redirects that happen in between.)

*Please describe.*  
*If this affects the front-end, screenshots would be of great help.*  

## Expected behavior

When arriving at _Sessions, filtered down to the query that was passed from the Cohorts tab, allow me to return by clicking the browser's Back button.

## How to reproduce

1. Click the Cohorts tab
2. Click a "Sessions" link under the _Actions_ column
3. Hit the Back button, to try to return to Corhorts

## Environment

- [X] PostHog Cloud 
- [ ] self-hosted PostHog, version/commit: _please provide_

**Comment by mariusandra** [comment]
I think this makes sense to tackle with https://github.com/PostHog/posthog/issues/4329 -- these "back doesn't go back" problems come when the page changes the URL on load... and I've seen them in other places.

**Comment by mariusandra** [comment]
This is now fixed
