### ISSUE TITLE
Implement new math property aggregator

### ISSUE THREAD

**Issue by paolodamico** [PostHog/posthog#4750]
## Is your feature request related to a problem?

In line with the new querying experience revamp, the math property aggregator could use some work to better align with the new components & UI, plus provide a better user experience through clearer interactions.

## Describe the solution you'd like

[Here](https://www.figma.com/file/gQBj9YnNgD8YW4nBwCVLZf/PostHog-App?node-id=2645%3A20884) is the proposed new design.

<img width="1152" alt="" src="https://user-images.githubusercontent.com/5864173/122000915-d915fd80-cdaf-11eb-8d6f-66636a76218a.png">

We would group math aggregators in 4 sections: general or basic (total count, unique users, unique by group [pending]), property aggregation (sum, average, min, max), weekly active (rolling WAUs, MAUs) & distribution aggregation (median, percentiles).

## Describe alternatives you've considered

There's a few additional alternatives in the Figma file with some variations on the interaction design.

## Additional context

Related to #4749.

**Comment by paolodamico** [comment]
Looking for feedback on this @corywatilo @EDsCODE @mariusandra

**Comment by mariusandra** [comment]
Love it. The win95 style underlined letters are also subtle, yet nice. However this means we're either going to have to adopt them a) everywhere, b) in all dropdowns, or c) nowhere. We can't really have two very different approaches here. Happy to punt this reunification to some future date though, as long as we approach is consciously.

**Comment by paolodamico** [comment]
I was thinking we could use this for all dropdowns (option b), **eventually.** The basic hotkey navigation that we have is useful for casual users as well. Navigating the entire interface and particularly this little interactions seems something more for power users, so something more subtle might be the way to go here.

**Comment by mariusandra** [comment]
"Option B, eventually" makes sense!

And if we're on the (off) topic, the hotkeys have an issue with the toolbar: https://github.com/PostHog/posthog/issues/4753 :)
