### ISSUE TITLE
Dashboard reloads don't spark joy

### ISSUE THREAD

**Issue by mariusandra** [PostHog/posthog#4752]
## Bug description

Not really a bug, but annoying UX-wise.

When clicking "reload" to reload a dashboard, the entire screen goes blank with a spinner, that spins until all dashboard items reload in the background. Only then is anything shown to the user.

## Expected behavior

Clicking reload, the screen stays as is and all individual dashboard items get a spinner. Dashboard items that finish earlier can be interacted with immediately.

## How to reproduce

1. Load a heavier dashboard such as this [internal one](https://app.posthog.com/dashboard/2256)
2. Click "reload"
3. Wait
4. Wait
5. Wait
6. Wait
7. Wait
8. Open the devtools console to check for errors
9. See none and give up
10. Oh it loads now

## Environment

- [ ] PostHog Cloud
- [ ] self-hosted PostHog, version/commit: _please provide_

## Additional context

- Most likely introduced by https://github.com/PostHog/posthog/pull/4598
- We [should use progress bars](https://www.nngroup.com/articles/progress-indicators/) or otherwise indicate progress for any loading screen that takes more than 10 seconds. Use count if time can't be estimated. E.g. "Refreshing dashboards items: 4 / 20 [spinner]"

**Comment by paolodamico** [comment]
I would also add that's useful to keep the current view while we're loading the new ones (the old data is still more useful than a loading spinner). We could just show a progress indicator some other way in each item. Think some mockups on this would be helpful?

FYI, related to https://github.com/PostHog/posthog/issues/1687#issuecomment-861165916

**Comment by mariusandra** [comment]
Definitely @paolodamico .

Honestly I don't understand why we removed the "reload" button from individual dashboard items (other than probably bugs?). I feel for my database and don't want it to recalculate all heavy charts when I just want to rageclick the reload button on my sales chart. Users will intuitively grasp this are "reload all" just takes a lot longer.

**Comment by paolodamico** [comment]
Hmmm I'm not entirely sure. Having individual refreshes seemed like an extra feature that introduces another decision (i.e. should I refresh individually or all of them), but I do see your point for heavy dashboards. Maybe what we can do as this evolves is introduce the context menu (see mockup below) and have the individual refresh in there. Users who refresh constantly and have heavy dashboards seem like power users, and it would just be a matter of initial discoverability.

<img width="369" alt="" src="https://user-images.githubusercontent.com/5864173/122039429-f9a57e00-cdd6-11eb-89ea-8ba65995d53c.png">

**Comment by mariusandra** [comment]
I haven't done user testing, so can't convincingly argue for any of the options here. Yet intuitively I think a "refresh all" top-level button together with individual "refresh" buttons, no matter if next to or inside the "..." menu make *some* sense :).

**Comment by alexkim205** [comment]
I'd love to take a stab at this one. I'll try to put out a draft PR by EOD :)

**Comment by paolodamico** [comment]
So for the dashboard refresh I was thinking we could do something like this. CC for feedback & implementation @alexkim205, @corywatilo, @mariusandra 

- We show a general progress bar where you click refresh all so that it's clear that a refresh is happening. This will also help convey progress for heavy dashboards.
- We keep the already loaded dashboard items in the screen.
- We show an attention notice in each dashboard item indicating it's still loading. Important to have the refresh icon animated (spinning) to convey progress.
<img width="1152" alt="" src="https://user-images.githubusercontent.com/5864173/122410605-5c884800-cf84-11eb-81e8-50e012a6d79e.png">

**Comment by alexkim205** [comment]
Great mockup @paolodamico! In your design, are you still thinking there will be individual "refresh buttons"? If so, would these individual refreshes also interface with a progress bar or do you think that it's redundant?

**Comment by paolodamico** [comment]
Think is worth keeping the individual refreshes for now and we can measure if they're actually still in use after this. Definitely not worth interacting with the progress bar on individual refreshes. 


Now I'm giving this progress bar a second thought. Would it be worth to have just a "Refreshed 3 out of 8 dashboards" label instead ?

**Comment by mariusandra** [comment]
If it's a progress bar or a "1 out of 8" is just an implementation detail. I do agree though that plain text might look nicer, especially as we don't really use progress bars anywhere.

For reference, this is how  "check for updates", which is very similar to "reload all", works on the plugins page:

![2021-06-22 09 57 09](https://user-images.githubusercontent.com/53387/122886513-53aac400-d340-11eb-8b12-414521004429.gif)

**Comment by alexkim205** [comment]
Awesome, we can definitely reuse that plugins component for this use case too
