### ISSUE TITLE
Hotkeys interfere with the toolbar

### ISSUE THREAD

**Issue by mariusandra** [PostHog/posthog#4753]
## Bug description

Clicking "S" or "F" in a toolbar text input doesn't add it to the input, but switches the insights tab

![2021-06-15 12 38 59](https://user-images.githubusercontent.com/53387/122039262-c9f67600-cdd6-11eb-8825-2823a10c81db.gif)

## Expected behavior

Text inputs work like they did in 1996

## How to reproduce

1. Open the insights page.
2. Open the toolbar and edit any action.
3. Press "S" or "F" in the textfield.

## Environment

- [ ] PostHog Cloud
- [ ] self-hosted PostHog, version/commit: _please provide_

**Comment by paolodamico** [comment]
Guess this only affect us, but should be an easy fix, so I'll add it to my radar

**Comment by mariusandra** [comment]
This probably only affects us, but other websites might rely on keyboard events and have similar problems. Not sure, but best to just fix. One gotcha: the toolbar is inside a shadow root/dom, which may add its own complexities. Not sure which though :).
