### ISSUE TITLE
Upgrade insights UI

### ISSUE THREAD

**Issue by paolodamico** [PostHog/posthog#4758]
@corywatilo has worked on new visuals for the main graphs in the app (originally part of #4156, split out into this issue). Using this issue to track down implementation of new UI design and any visuals follow up.

![image](https://user-images.githubusercontent.com/154479/116491587-3ab5f300-a868-11eb-8fad-e1bae7247dda.png)

Main differences:

1. Y-axis: Bolded, truncated labels
2. X-axis: Put days of week in a visually differentiated box, shortened month, US format
3. Thicker line on area chart
4. Slight gradient on area chart
5. Vertical line on hover

Depends on https://github.com/PostHog/posthog/issues/4568 (migration to D3)
Related to https://github.com/PostHog/posthog/issues/4535 (funnel new visuals)

**Comment by paolodamico** [comment]
@corywatilo I just realized we're also missing updated visuals for bar charts.

**Comment by paolodamico** [comment]
I actually think this new UI is already implemented even if we didn't move to D3, right @samwinslow ? can't test in production because of the feature flags bug

**Comment by samwinslow** [comment]
Yep! Should be in prod under flag `4156-tooltips-legends`. What's going on with feature flags?

**Comment by paolodamico** [comment]
Nice! Is the light gradient background something we can implement quickly in the current chart.js version before closing this?

This bug is going on, #4937. You can see that the new tooltips and legends table is not released in production because of it. Think it's worth spending some time to fix this as soon as possible.
