### ISSUE TITLE
Allow clicking on user list for overlapping data point

### ISSUE THREAD

**Issue by paolodamico** [PostHog/posthog#4775]
## Is your feature request related to a problem?

Currently if there are two overlapping data points in a graph (i.e. have the same x, y values) I can only see the user list for one of them. 

## Describe the solution you'd like

Here's a new proposed [design](https://www.figma.com/file/gQBj9YnNgD8YW4nBwCVLZf/PostHog-App?node-id=2655%3A0) for the save person modal that allows selecting different data points. It also helps clean up the interface a bit. **Looking for feedback on the design too.**

<img width="1152" alt="" src="https://user-images.githubusercontent.com/5864173/122212961-b7e50800-cea8-11eb-9d84-dcaf1c355d4a.png">

## Describe alternatives you've considered

Cross my fingers that the point I get is the one I'm looking for?

## Additional context

Related to the new tooltips #4156, but problem already existed.

**Comment by paolodamico** [comment]
Related to this, think it's worth considering how we can improve the pagination experience. The current experience of clicking to load more is not great.

**Comment by macobo** [comment]
Note: A lot of refactoring is currently ongoing in the persons modal to make it work for groups - let's avoid nasty merge conflicts and also take groups into account when solving.
