### ISSUE TITLE
Deploying breaking backend and frontend changes breaks functionality

### ISSUE THREAD

**Issue by alexkim205** [PostHog/posthog#4779]
## Bug description

When we merge in a PR that makes a breaking change in how the frontend talks to the backend (i.e., changing API endpoint), there is an edge case where a new frontend request will be directed to an old backend. We can't mitigate this edge case in code.

This edge case has consistently broken the funnels API when deploying a frontend+backend change in the past. Please see #4768 for more information.

It's also unclear what the bake time between backend and frontend merge should be. The frontend change was merged in ~3hrs after the backend changes but still broke things.

|              | Old Backend | New Backend |
|--------------|-------------|-------------|
| Old Frontend | 🎉        |  🎉       |
| New Frontend | 😞       |  🎉       |

## Expected behavior

Old frontend requests <-> Old backend
New frontend requests <-> New backend

## How to reproduce

#4768

## Environment

- [X] PostHog Cloud
- [Doesn't happen here] self-hosted PostHog, version/commit: _please provide_

**Comment by mariusandra** [comment]
As we discussed, I don't buy the explanation of "both ends are not deployed together-enough". Worse case in those instances we might have a few minutes of sentry errors, which then quiet down. In this case we have the full backend part deployed, yet the frontend still can't use the endpoint. 

I'm investigating what could be happening here in https://github.com/PostHog/posthog/pull/4789

**Comment by mariusandra** [comment]
So it was postgres vs clickhouse. https://github.com/PostHog/posthog/pull/4789#issuecomment-863270521

I've fixed the tests that should have run with both, to actually run with both. Seems green, so... 🚢 ?
