### ISSUE TITLE
Allow to define feature flags to be non-public

### ISSUE THREAD

**Issue by weyert** [PostHog/posthog#4781]
## Is your feature request related to a problem?

Currently when you are using feature flags and define them they are always visible in both `posthog-js` and non-client side library while there might be feature flags (such as ops flags, kill switches) which you don't want to have visible on client-side but only to others.

## Describe the solution you'd like

I would like to propose an option are you can define whether it is a 'internal' feature flag or a public feature flag is exposed to public facing libraries, e.g. `posthog-js`. This allows 

## Describe alternatives you've considered

A proxy between cloud posthog and our web application which strips out any non-public feature flags on the `/decide` endpoint (and others).

Alternatively, I could create a `web` and `backend` project for each environment but that makes it difficult to manage the feature flags. 

## Additional context
I would like to avoid leaking feature flags which are backend specific to our web applications

**Comment by yakkomajuri** [comment]
Hey @weyert! I think this is quite valid actually. For now, you could name them something non-revealing though, and leave more information for the description.

**Comment by weyert** [comment]
Cool, glad to hear you like the idea! Yeah, a cryptic name is a good idea didn't think of that. Curious, how other solutions like Launchdarkley handle this.

**Comment by weyert** [comment]
Copying this over from ticket #4849:

> For example, you have data processing jobs which run every few hours which fetches data from third parties. Occasionally the third party might have spike in traffic and ask to temporary postpone our jobs until the high traffic has passed or maybe the third party is having issues.
> 
> For this reason, I would like to use feature flags to temporary stop jobs for doing outgoing requests as its easier then needing to redeploy the service to change environment variables etc.
> 
> The only current problem I am having is that I can't define server-side feature flags that are only accessible for server-side code and don't get exposed on the client-side e.g. web-applications or mobile applications. For this reason, I would like to propose the following as a first iteration to allow this functionality:
> 
> Introduce a second Project API key (potentially prefixed with phs) which only return feature flags tagged/marked for server-side use
> Add a new property to feature flags to define whether they are a server-side only feature flag or not
> Create a default value on this field in the model so it disabled by default
> I think this is a reasonable solution to my problem at hand. I noticed there has been a discussion earlier about scoped personal access tokens but I don't think that would be able to solve the problem and typically it's problematic to use user-specific access tokens e.g. what happens when the user gets disabled or deleted etc?
> 
> I am happy to work on the necessary PRs to introduce this functionality
> 
> In the future I can imagine we could build upon this by for example support depending feature flags, e.g. only enable front-end feature flags when backend feature flag A and B are enabled etc.
>

**Comment by paolodamico** [comment]
I think this could be quite powerful but would like to loop in @neilkakkar for suggestions on the approach. Perhaps if you include your personal API key (which you usually set in backend stuff) we send these _secret_ flags.

**Comment by yakkomajuri** [comment]
Personal API Key is one way to do this for now that'd be compatible with our current approach in the libs.

I'm still an advocate for a secret project token though

**Comment by weyert** [comment]
> Personal API Key is one way to do this for now that'd be compatible with our current approach in the libs.
> 
> I'm still an advocate for a secret project token though

I was thinking of adding a second project token which will be listed on the Project Settings page and then for each Feature Flag you can mark it as 'limited access' (probably needs better wording, lol) and if it's enabled they Feature Flag will only be returned when the backend API received this second  project token. I think I could add a new column to the `Team`-model e.g. `restricted_api_token` and then it gets populated in a similar manner. I can imagine to prefix the actual token so it's easier to distinguise between the two kinds.

I think the clients don't need to be changed for this

@yakkomajuri  What do you think of the above proposal?
