### ISSUE TITLE
Lifecycle insight not saving filters to dashboard

### ISSUE THREAD

**Issue by joesaunderson** [PostHog/posthog#4787]
## Bug description

When creating a lifecycle chart, and adding filters. One/some of the filters are not persisted when saving the chart to a dashboard. This is causing confusion in the dashboard, it is wrongly over-stating as it's not taking the cohort into account.

## Expected behavior

Both filters are persisted, and the dashboard shows the right query.

## How to reproduce

1. Create a lifecycle chart
2. Use the Pageview event
3. Filter by 1 user property AND 1 cohort
4. Save the chart to a dashboard
5. View dashboard
6. Click on "View graph" in dashboard
7. Only the 1 user property filter has persisted

## Environment

- [ ] PostHog Cloud
- [x] self-hosted PostHog, version/commit: 1.26.0

## Additional context

N/A

**Comment by mariusandra** [comment]
Feedback from a user:

> on the lifecycle tab I uncheck "dormant" for example, save to my dashboard, yet my dashboard still displays the dormant data

**Comment by liyiy** [comment]
> Feedback from a user:
> 
> > on the lifecycle tab I uncheck "dormant" for example, save to my dashboard, yet my dashboard still displays the dormant data

Actually this isn't _really_ a bug because we only do the lifecycle toggle filters on the frontend by original design. If we want to save those toggles, we'll need to add those filters to the backend.

**Comment by mariusandra** [comment]
At the end of the day, for the user, it's still a bug: the toggles aren't remembered when you add it to a dashboard.

I don't think we need to change anything in the backend (querying), just the filter should be saved in a way that it's also remembered for the dashboard.

**Comment by liyiy** [comment]
Re-opening so we can also address the lifecycle toggle state issue

**Comment by pauldambra** [comment]
closed in #14547
