### ISSUE TITLE
Display persons throughout insights with user chosen selected property

### ISSUE THREAD

**Issue by EDsCODE** [PostHog/posthog#4795]
## Is your feature request related to a problem?

*Please describe.*
By default, we use emails are distinct_ids to list users on insights (in person modals and funnel list of people). Some users might have a different label for their persons are prefer to use the distinct_id they passed in rather than the email.

## Describe the solution you'd like
We should allow users to switch back and forth between the properties/ids that they would like to see when viewing persons.

## Describe alternatives you've considered
Leave it as is

## Additional context
Important for Captur because they would prefer to see the underlying distinct_ids since they are identifying users in a unique way where emails are shared but distinct_ids that are provided are more important

**Comment by Aashish-Upadhyay-101** [comment]
Hey I want to work on this issue, can you please guide me to the solution?

**Comment by iknlaxmi** [comment]
Hi,I want to work on this issue. can you please assign this to me.

**Comment by mariusandra** [comment]
We don't assign issues. Submit a PR if you have one.

**Comment by namit-chandwani** [comment]
Hey @EDsCODE @Twixes @mariusandra, I've got the Posthog repo up and running on my local system and have been experimenting with its features to get a better grasp of the product.

I'm now eager to dive into a beginner-friendly issue to familiarize myself with the codebase.


Can you please point me towards a good starting point for this particular issue?

**Comment by Twixes** [comment]
Oh, @namit-chandwani, I believe this issue is already solved by the "Person display name" project setting, a feature we released some time ago. You might want to find a different issue.

**Comment by namit-chandwani** [comment]
@Twixes Got it. Thanks for the update, I'll look for another issue to contribute to
