### ISSUE TITLE
Release automation (+ handle no more free automated builds on Docker Hub)

### ISSUE THREAD

**Issue by tiina303** [PostHog/posthog#4799]
Docker Hub Automated Builds (which we use for building release branches) don't work anymore, post: https://www.docker.com/blog/changes-to-docker-hub-autobuilds/

Since we only use these for release builds and we're already pushing dev/latest ourselves already it make sense to just create a Github action for it.

While we do that there are a couple of other manual steps during releases: https://github.com/PostHog/posthog.com/blob/b61e6681e4987988f2d981ff9d77cadd8bdb3d53/contents/handbook/engineering/release-new-version.md. (& the tag needs to get updated in the new charts-clickhouse repo too) & we already have https://github.com/PostHog/posthog/actions/workflows/version-update.yml but it doesn't really work.

**Comment by fuziontech** [comment]
already done!
https://github.com/PostHog/posthog/pull/6469
