### ISSUE TITLE
Session Recording Degraded Playback Experience

### ISSUE THREAD

**Issue by akbansa** [PostHog/posthog#4815]
## Bug description

*Please describe.*  
There are a few bugs in the recordings experience. Here is the list:
- Sometimes while playing video gets stuck and (play head) does not move forward
- The video player is slow, buggy, and crash sometimes
- There is no option of skipping inactivity (FullStory give this) => (this is more like feature request)

## How to reproduce

1.
2.
3.

## Environment

- [X] PostHog Cloud
- [ ] self-hosted PostHog, version/commit: _please provide_

**Comment by marcushyett-ph** [comment]
As we move to focus on "Nailing Diagnostics" this will be key issues to fix

**Comment by paolodamico** [comment]
I think this has improved a lot with all the recent updates to recordings, please feel free to reopen if this is not the case.
