### ISSUE TITLE
Implement new PersonModal for funnels

### ISSUE THREAD

**Issue by paolodamico** [PostHog/posthog#4819]
Part of #4785. Implement the new `PersonModal` as detailed in the [product specs](https://docs.google.com/document/d/1S7fwha7cph-79YaPADfFKHILCnPmBgk4rqaMu-gPZ3g/edit#heading=h.w1yaw9nwtpu). Mockups can be found on [Figma](https://www.figma.com/file/gQBj9YnNgD8YW4nBwCVLZf/PostHog-App?node-id=2668%3A0).

**Comment by paolodamico** [comment]
@mariusandra this is now fully unblocked and ready to be assigned

**Comment by liyiy** [comment]
Updates to the modal like filtering, sessions recording, etc can be worked on but implementing the persons modal for funnels might be blocked until querying can tackle on the backend for it 

@EDsCODE

**Comment by paolodamico** [comment]
Makes total sense. We're tracking the necessary API work in #4818

**Comment by mariusandra** [comment]
For lack of a better place to post this, I seem to be experiencing a bug where I can't save a dropoff as a cohort:

![2021-07-14 16 02 22](https://user-images.githubusercontent.com/53387/125635579-4a711fc4-4b03-47d5-91d1-49f4bce95a9c.gif)

The completed people save fine.

**Comment by mariusandra** [comment]
Also this: https://github.com/PostHog/posthog/pull/5092#commitcomment-53479096

**Comment by paolodamico** [comment]
I think this can be closed now @liyiy ?
