### ISSUE TITLE
Setting and persisting custom names on funnel steps

### ISSUE THREAD

**Issue by paolodamico** [PostHog/posthog#4821]
See [product specs](https://docs.google.com/document/d/1S7fwha7cph-79YaPADfFKHILCnPmBgk4rqaMu-gPZ3g/edit#heading=h.e8h13mge2i46) for details.

@mariusandra ready to assign.

**Comment by clarkus** [comment]
This is specific to funnels, but similar solutions could be applicable to any query step or graph series in an insight. See related issues at https://github.com/PostHog/posthog/issues/5207 and https://github.com/PostHog/posthog/issues/5229. Generally, the common problem case for each insight is setting a meaningful name to use in the visualization.

**Comment by paolodamico** [comment]
Indeed it's something that should work holistically for all insights. As we already have #5207 around, I'll close this.
