### ISSUE TITLE
Breakdown broke my page

### ISSUE THREAD

**Issue by yakkomajuri** [PostHog/posthog#4823]
## Bug description

Doing a breakdown on PostHog Cloud (demo data, breakdown pageviews by referrers) made the page crash. Not React's white screen of death, more like JS event loop blocked and I couldn't click on anything and nothing would load.

## Expected behavior

Breakdown doesn't actually break things.

## How to reproduce

1. Breakdown pageviews by initial referrer on "HogFlix Demo App" project on PostHog Cloud
2.
3.

## Environment

- [ ] PostHog Cloud
- [ ] self-hosted PostHog, version/commit: _please provide_

**Comment by macobo** [comment]
Tried reproducing this but didn't succeed

**Comment by mariusandra** [comment]
I haven't seen it either, even though I tried when this was first reported. Tried a bit now, and to look for an error in sentry, but couldn't get anything... Let's reopen when it happens again.
