### ISSUE TITLE
Toolbar keyboard shortcuts interfere with typing?

### ISSUE THREAD

**Issue by corywatilo** [PostHog/posthog#4833]
## Bug description

After using the toolbar to inspect an element, I tried typing a name, but other things seem to be getting triggered by my keyboard inputs.

![2021-06-21 13 52 21](https://user-images.githubusercontent.com/154479/122806574-7b465180-d298-11eb-969a-22a591e6a9d7.gif)

## Expected behavior

Keyboard hotkeys should be disabled when a text input has focus.

## How to reproduce

1. In our own app, open Toolbar and inspect the Add Filter button on the first step of a funnel:

![image](https://user-images.githubusercontent.com/154479/122806411-46d29580-d298-11eb-8ac8-1d7c77cf4d78.png)

2. Choose _New action_ and type `Clicked`.

The `L` key doesn't type into the box, as do some other letters that follow.

## Environment

- [X] PostHog Cloud

**Comment by mariusandra** [comment]
This issue is like so 6 days old...  https://github.com/PostHog/posthog/issues/4753

🙈 😆
