### ISSUE TITLE
Use different funnel visualization library

### ISSUE THREAD

**Issue by liyiy** [PostHog/posthog#4834]
## Is your feature request related to a problem?

Currently we use [funnel-graph-js](https://github.com/greghub/funnel-graph-js) to render our funnels and it looks great! Unfortunately it's lacking a lot of features like interactional click, hover events, etc and doesn't look like it's been updated in over a year. 

Should we switch to a different solution like [d3-funnels](https://github.com/jakezatecky/d3-funnel)? 
Pros: we can add tooltips and click on things, 
Cons: it's not as pretty out of the box

**Comment by liyiy** [comment]
#4819

**Comment by mariusandra** [comment]
I think the idea is to go more in this kind of direction: https://github.com/PostHog/posthog/issues/4535#issuecomment-862765705 - so just pretty boxes.
