### ISSUE TITLE
Additional graph series duplicate previous entry

### ISSUE THREAD

**Issue by clarkus** [PostHog/posthog#4838]
## Bug description

This might be working as designed, but I wanted to start an issue to help me better understand the intent with this workflow. When adding additional graph series to an insight trend, my subsequent series are duplicates of the previous entry. Is there any reason we would always duplicate the previous entry instead of starting from a default state?

## Expected behavior

As a user, I would expect to have the same creation experience each time when using the same `add graph series` action. If the intent is to duplicate the previous entry, we should clearly label that action and distinguish it from the add new action. 

## How to reproduce

1. Go to any tab within Insights
2. Configure the query with alternate metrics, counts, filters, etc. 
3. Click "add graph series"
4. Note that you duplicated the previous entry instead of starting new.

<img width="1180" alt="Screen Shot 2021-06-21 at 3 58 13 PM" src="https://user-images.githubusercontent.com/254612/122837760-82299000-d2a9-11eb-98ce-6bf1f841528c.png">

**Comment by paolodamico** [comment]
@macobo proposed this change a while ago, the rationale roughly being that you usually want to start off from the previous series and change something rather than starting fresh (you can look for the original PR for the full context). After having this around for some time I have today, this has come in handy a lot of times, but I do agree is confusing. Your proposal of making this more explicit makes sense to me.

**Comment by mariusandra** [comment]
Incoming $0.02: agree that this has proven useful several times, yet was also surprising the first time I tried it. Having the "new filter" open an empty filter would definitely be less surprising, yet comparably usable. 

For most usability at the cost of a more cluttered interface, we could also move the "copying" feature into a new "duplicate" button, perhaps even behind a "..." menu...

Edit: oh, so you already did the "duplicate" (in a slack thread) :D

**Comment by clarkus** [comment]
> Edit: oh, so you already did the "duplicate" (in a slack thread) :D
![Filter Concepts](https://user-images.githubusercontent.com/254612/122952541-e9d7ed80-d332-11eb-8fd3-1e917990ae42.png)

I think these changes could add value for sure. Specifically the ability to duplicate any previous series instead of the most recently completed series. The clear labeling also helps, but I really like that we're able to serve both use cases.
