### ISSUE TITLE
Filter dropdowns open too eagerly

### ISSUE THREAD

**Issue by mariusandra** [PostHog/posthog#4841]
## Bug description

It's great when the dropdown opens when the filter is just added, but it's not great if this happens to an existing filter that's only just revealed:

![2021-06-22 11 08 15](https://user-images.githubusercontent.com/53387/122897375-3d096a80-d34a-11eb-9fac-02726b9f4889.gif)

## Expected behavior

No autocomplete dropdowns should open.

## Environment

- [ ] PostHog Cloud
- [ ] self-hosted PostHog, version/commit: _please provide_

## Additional context

Might be worth waiting for an updated filter design first?

**Comment by paesku** [comment]
With the latest UI, I face the problem, that the filter doesn't show up over other elements:

https://user-images.githubusercontent.com/3726371/125586838-cfc490ce-1cc6-4c68-b9ca-33a7699b6efd.mov

Browsers:
- Firefox
- Chrome

There seems to be an inline style which sets `overflow: hidden;` on some wrapping div:


![styles](https://user-images.githubusercontent.com/3726371/125597207-050738f9-a50a-4ab2-87df-659794550f93.png)

**Comment by paolodamico** [comment]
This has been fixed in the most recent changes.
