### ISSUE TITLE
User properties snapshot in time

### ISSUE THREAD

**Issue by paolodamico** [PostHog/posthog#4854]
## Is your feature request related to a problem?

User properties are static, if I change a user property it can retroactively affect my metrics. Worse, it can lead to completely unexpected results. For instance if I do a list of WAUs who have a `paid_membership = True`, the list will change completely depending on who has that property when I run the analysis.

## Describe the solution you'd like

I'd like us to have a way to filter by user properties in a point in time. One option could be to snapshot the entire set of user properties in each event and use those for analyses. This way I can run analyses depending on what a specific property was at each point in time (like we have for events).

## Additional considerations

The above proposal is not a straightforward. Some things to consider:
1. Currently you can easily overwrite properties as a way to delete data. How would we make sure we can delete PII or other sensitive data everywhere?
2. This would essentially multiply a bunch of repeated data. Could this be a concern? Is there a way to optimize it?

## Additional context

Original discussion where this was brought up [in this Google doc](https://docs.google.com/document/d/1S7fwha7cph-79YaPADfFKHILCnPmBgk4rqaMu-gPZ3g/edit?disco=AAAAMjOcKIg). CC @kpthatsme

**Comment by mariusandra** [comment]
I'm going to play librarian and link to a few related issues: 
- https://github.com/PostHog/posthog/issues/4272 
- https://github.com/PostHog/plugin-server/issues/375
- https://github.com/PostHog/plugin-server/issues/371

**Comment by kpthatsme** [comment]
Thanks for writing this up @paolodamico! 

One important note is we still want to maintain the most recent aspect of user properties when applied to cohorts and it will depend on the query definition which meaning we want to apply.

**Comment by paolodamico** [comment]
This is already being tackled in @macobo's RFC to change how we store person properties.
