### ISSUE TITLE
Math operations not working

### ISSUE THREAD

**Issue by yakkomajuri** [PostHog/posthog#4858]
Math operations not working (with multiple series?)

Getting `NaN`s and `0`s. Shows correctly on my dashboards.

[Link to table](https://app.posthog.com/insights?insight=TRENDS&events=%5B%7B%22id%22%3A%22instance%20status%20report%22%2C%22math%22%3A%22dau%22%2C%22name%22%3A%22instance%20status%20report%22%2C%22type%22%3A%22events%22%2C%22order%22%3A0%2C%22properties%22%3A%5B%7B%22key%22%3A%22teams__1__events_count_by_lib__posthog-python%22%2C%22type%22%3A%22event%22%2C%22value%22%3A%22is_set%22%2C%22operator%22%3A%22is_set%22%7D%5D%2C%22math_property%22%3Anull%7D%2C%7B%22id%22%3A%22instance%20status%20report%22%2C%22math%22%3A%22dau%22%2C%22name%22%3A%22instance%20status%20report%22%2C%22type%22%3A%22events%22%2C%22order%22%3A1%2C%22properties%22%3A%5B%7B%22key%22%3A%22teams__1__events_count_by_lib__web%22%2C%22type%22%3A%22event%22%2C%22value%22%3A%22is_set%22%2C%22operator%22%3A%22is_set%22%7D%5D%2C%22math_property%22%3Anull%7D%2C%7B%22id%22%3A%22instance%20status%20report%22%2C%22math%22%3A%22dau%22%2C%22name%22%3A%22instance%20status%20report%22%2C%22type%22%3A%22events%22%2C%22order%22%3A2%2C%22properties%22%3A%5B%7B%22key%22%3A%22teams__1__events_count_by_lib__posthog-node%22%2C%22type%22%3A%22event%22%2C%22value%22%3A%22is_set%22%2C%22operator%22%3A%22is_set%22%7D%5D%2C%22math_property%22%3Anull%7D%2C%7B%22id%22%3A%22instance%20status%20report%22%2C%22math%22%3A%22dau%22%2C%22name%22%3A%22instance%20status%20report%22%2C%22type%22%3A%22events%22%2C%22order%22%3A3%2C%22properties%22%3A%5B%7B%22key%22%3A%22teams__1__events_count_by_lib__posthog-react-native%22%2C%22type%22%3A%22event%22%2C%22value%22%3A%22is_set%22%2C%22operator%22%3A%22is_set%22%7D%5D%2C%22math_property%22%3Anull%7D%2C%7B%22id%22%3A%22instance%20status%20report%22%2C%22math%22%3A%22dau%22%2C%22name%22%3A%22instance%20status%20report%22%2C%22type%22%3A%22events%22%2C%22order%22%3A4%2C%22properties%22%3A%5B%7B%22key%22%3A%22teams__1__events_count_by_lib__posthog-go%22%2C%22type%22%3A%22event%22%2C%22value%22%3A%22is_set%22%2C%22operator%22%3A%22is_set%22%7D%5D%2C%22math_property%22%3Anull%7D%2C%7B%22id%22%3A%22instance%20status%20report%22%2C%22math%22%3A%22dau%22%2C%22name%22%3A%22instance%20status%20report%22%2C%22type%22%3A%22events%22%2C%22order%22%3A5%2C%22properties%22%3A%5B%7B%22key%22%3A%22teams__1__events_count_by_lib__posthog-php%22%2C%22type%22%3A%22event%22%2C%22value%22%3A%22is_set%22%2C%22operator%22%3A%22is_set%22%7D%5D%2C%22math_property%22%3Anull%7D%2C%7B%22id%22%3A%22instance%20status%20report%22%2C%22math%22%3A%22dau%22%2C%22name%22%3A%22instance%20status%20report%22%2C%22type%22%3A%22events%22%2C%22order%22%3A6%2C%22properties%22%3A%5B%7B%22key%22%3A%22teams__1__events_count_by_lib__posthog-android%22%2C%22type%22%3A%22event%22%2C%22value%22%3A%22is_set%22%2C%22operator%22%3A%22is_set%22%7D%5D%2C%22math_property%22%3Anull%7D%2C%7B%22id%22%3A%22instance%20status%20report%22%2C%22math%22%3A%22dau%22%2C%22name%22%3A%22instance%20status%20report%22%2C%22type%22%3A%22events%22%2C%22order%22%3A7%2C%22properties%22%3A%5B%7B%22key%22%3A%22teams__1__events_count_by_lib__posthog-ios%22%2C%22type%22%3A%22event%22%2C%22value%22%3A%22is_set%22%2C%22operator%22%3A%22is_set%22%7D%5D%2C%22math_property%22%3Anull%7D%2C%7B%22id%22%3A%22instance%20status%20report%22%2C%22math%22%3A%22dau%22%2C%22name%22%3A%22instance%20status%20report%22%2C%22type%22%3A%22events%22%2C%22order%22%3A8%2C%22properties%22%3A%5B%7B%22key%22%3A%22teams__1__events_count_by_lib__posthog-plugin-server%22%2C%22type%22%3A%22event%22%2C%22value%22%3A%22is_set%22%2C%22operator%22%3A%22is_set%22%7D%5D%2C%22math_property%22%3Anull%7D%2C%7B%22id%22%3A%22instance%20status%20report%22%2C%22math%22%3A%22dau%22%2C%22name%22%3A%22instance%20status%20report%22%2C%22type%22%3A%22events%22%2C%22order%22%3A9%2C%22properties%22%3A%5B%7B%22key%22%3A%22teams__1__events_count_by_lib__posthog-ruby%22%2C%22type%22%3A%22event%22%2C%22value%22%3A%22is_set%22%2C%22operator%22%3A%22is_set%22%7D%5D%2C%22math_property%22%3Anull%7D%5D&display=ActionsTable&interval=day&date_from=-30d&funnel_window_days=14&properties=%5B%5D#fromItem=167979&fromItemName=Library%20Usage%20Stats&fromDashboard=3102)

<img width="1227" alt="Screenshot 2021-06-23 at 12 13 13" src="https://user-images.githubusercontent.com/38760734/123123299-1c5e1500-d41d-11eb-95ee-b80c230a4922.png">
<img width="1244" alt="Screenshot 2021-06-23 at 12 14 40" src="https://user-images.githubusercontent.com/38760734/123123545-4adbf000-d41d-11eb-9ea7-647a00620371.png">

**Comment by alexkim205** [comment]
It looks like there's a problem with the data that's being returned where aggregate_count > 0, but counts is 0 which is causing data mismatch. ~This data mismatch bug looks similar to this #4676 PR which might be useful.~ <- Verified that this isn't the issue.

<img width="410" alt="Screen Shot 2021-06-23 at 9 43 34 AM" src="https://user-images.githubusercontent.com/13460330/123136888-4953fd00-d408-11eb-9f50-f4575a59786d.png">


Redirecting to core-analytics team

**Comment by alexkim205** [comment]
Looks like this is happening on all of our insights tables. Bumping up to P0

**Comment by yakkomajuri** [comment]
Any progress here?

**Comment by EDsCODE** [comment]
What is the table operation supposed to do? For example, what's being averaged when you select average on a table operation as opposed to a math operation on the event itself

**Comment by yakkomajuri** [comment]
Got some NaNs for a breakdown viewed as a table today during a demo

**Comment by paolodamico** [comment]
I'm not sure if we're keeping this logic in the frontend or moving it to the backend as suggested, @EDsCODE ?

**Comment by EDsCODE** [comment]
Oh we can do this on backend to get the exact number. To clarify, the operation (average/median) is being performed across the data points in the time range? Should total sum show a deduplicated sum across the time range or a naive sum of all the numbers shown in the trend graph

**Comment by macobo** [comment]
There's a question here around semantics.

Say you are looking at unique users over a 7 day period. In trends graph you would see 10 users per day, 70 in total.

Switching to table view you currently would see the "total sum"  be 35 because some visited on multiple days. 

1. Is this actually what's expected? I would have actually expected to see 70 instead
2. How would you calculate Average and Median for this? Average really can't be 5 per day since 10 people were visiting per day.
3. We don't really communicate what's the interval we're averaging/medianning by - it could be the whole week, one day, one hour, second, ...

**Comment by paolodamico** [comment]
- I think the problem @macobo is referring to is because we're not using the same logic/components in the insights table as in the "Table" view. **We should fully unify**.
- For the special case of unique users, I think we would _ideally_ have two options: simple sum of all active user's cells and total uniques. When I introduced this I opted to simplify initially and only provide the first one, adding a disclaimer for what this number actually represents.
-  I think having these numbers make a lot of sense, users have requested them and even exports to do them offline, though it's hard to measure actual usage. **I would advocate for at least making sure the total works and removing average/median if it's a complex task to figure out**.

**Comment by hazzadous** [comment]
@paolodamico could you point me to a url that has the "Table" view you're referencing. I'm guessing [this is the Insights Table](https://github.com/PostHog/posthog/blob/master/frontend/src/scenes/insights/InsightsTable/InsightsTable.tsx#L34:L34) logic you're referencing

For the total, at least for clickhouse, we're taking the [count of distinct `person_id`s](https://github.com/PostHog/posthog/blob/master/ee/clickhouse/queries/trends/util.py#L31:L31) over the [entire time range](https://github.com/PostHog/posthog/blob/master/ee/clickhouse/sql/trends/volume.py#L5:L5). Do we need the simpler option in this case?

For the average/median numbers, do you know if the requests have specifically specified the functionality they'd want to see? I believe for postgres at least we are currently taking the mean/median of per day datapoints. per day here is implicit and not visible to the user. Perhaps removing average/median is the best option given the ambiguity?

**Comment by paolodamico** [comment]
So just to clarify, for "non-unique users" filters (e.g. total count, sum, ...) we would have simple sum/average/median over all the cells. For the tricky case of unique users I don't have enough context from users but I think what would make sense is giving the count of distinct IDs over the entire range (as you suggested), and avg/median would behave the same as for regular event aggregations (i.e. just average the values of each column). It'll be important to clarify this for unique users in the UI (we already have a component, it's just updating the copy).

Absolutely! Indeed, this is `InsightsTable.tsx`, which also has a nicer UI/UX.
<img width="1340" alt="" src="https://user-images.githubusercontent.com/5864173/136029740-020998af-01b7-4051-93d8-dbc0e3f64ad6.png">


This is what we currently show in the "Table" insight, and is not great to have that discrepancy.
<img width="1335" alt="" src="https://user-images.githubusercontent.com/5864173/136029774-514d7a3a-555f-4598-84b6-cf5e7c622f58.png">
