### ISSUE TITLE
Sessions day list view shows yesterday's sessions.

### ISSUE THREAD

**Issue by alexkim205** [PostHog/posthog#4860]
## Bug description

It's confusing to see yesterday's sessions when you're filtering for today's sessions.

<img width="1095" alt="Screen Shot 2021-06-23 at 9 57 28 AM" src="https://user-images.githubusercontent.com/13460330/123158608-de62f000-d420-11eb-9082-d57dfff5f66b.png">

It looks like this happens because we're querying for all sessions in the day defined by the database's UTC timezone, and not by the user's timezone.

## Expected behavior

Show only that day's sessions, where the day range is defined by the user's chosen timezone.

## How to reproduce

1. Go to Persons > Sessions page
2. Find a day where there is a session that bleeds into today's UTC timezone
3.

## Environment

- [X] PostHog Cloud
- [X] self-hosted PostHog, version/commit: _please provide_

**Comment by marcushyett-ph** [comment]
We should resolve this for our next milestone

**Comment by paolodamico** [comment]
This page is 💥 , so closing
