### ISSUE TITLE
Events table gets two scrollbars on load

### ISSUE THREAD

**Issue by mariusandra** [PostHog/posthog#4870]
## Bug description

When I open the events list, I see this at the end:

![image](https://user-images.githubusercontent.com/53387/123290181-5c062900-d511-11eb-9cc5-5d3919758d33.png)

After a while they disappear. The table is also slightly jumpy while this happens, and the page feels somewhat unresponsive. More precisely, after the table has fully rendered for the first time, if I start scrolling up and down with my mouse, nothing happens and the page is unresponsive... for 2 seconds.

However 2 seconds on a high end intel MBP might be 10 seconds for someone with an underpowered corporate Dell.  

## Expected behavior

No double scrollbars and the page should be as smooth as butter.

## Environment

- [ ] PostHog Cloud
- [ ] self-hosted PostHog, version/commit: _please provide_

**Comment by alexkim205** [comment]
Related to my comment [here](https://github.com/PostHog/posthog/pull/4727#issuecomment-868877913)

**Comment by alexkim205** [comment]
Closing now that new LemonTable is out
