### ISSUE TITLE
Separate HTTP error code for "Estimated query execution time is too long" api requests

### ISSUE THREAD

**Issue by macobo** [PostHog/posthog#4887]
## Is your feature request related to a problem?

When an API query returns a 500, it's often due to clickhouse predicting it's a timeout. However we don't have a good way to distinguish these performance issues from other 500s which indicate a bug in our code.

## Describe the solution you'd like

Return a separate error code for these errors.

Looking at https://en.wikipedia.org/wiki/List_of_HTTP_status_codes we would like to avoid collisions with cloudflare, cloudformation and for it to be a 5xx error.

## Describe alternatives you've considered

Separate backend event instead of messing with error codes. 512 is unassigned, we could use it without any issues.

## Additional context

Will create a quick PR after lunch :)

**Comment by yakkomajuri** [comment]
418? 🍵

**Comment by macobo** [comment]
418 is user-side, ended up going with 512. This is done now :partying_face:

**Comment by yakkomajuri** [comment]
@macobo that was a joke
