### ISSUE TITLE
Update clickhouse version in cloud

### ISSUE THREAD

**Issue by macobo** [PostHog/posthog#4896]
## Is your feature request related to a problem?

This bug is fixed by upgrading clickhouse: https://github.com/PostHog/posthog/issues/4895

Seems like there has been some other nice enhancements as well.

## Describe the solution you'd like

Upgrade the version to latest.

**Comment by neilkakkar** [comment]
Solving this issue also helps core analytics in upgrading queries (use RANGE in window functions), and with easier validation (windowFunnel options)

**Comment by macobo** [comment]
Went ahead and updated us from 21.3.11.5 to 21.6.5.37 on cloud.
