### ISSUE TITLE
Typo in tooltip

### ISSUE THREAD

**Issue by joethreepwood** [PostHog/posthog#4906]
## Bug description

Typo in tooltip for stickiness. See screenshot (circled).

<img width="1217" alt="Screenshot 2021-06-29 at 12 34 38" src="https://user-images.githubusercontent.com/84011561/123790761-9f2c1780-d8d6-11eb-9792-3e5d68e71d9c.png">

## Expected behavior

Correct spelling.

## How to reproduce

1. Hover on 'Stickiness'
2. Read.
3.

## Environment

- [x] PostHog Cloud
- [ ] self-hosted PostHog, version/commit: _please provide_

**Comment by macobo** [comment]
Made a quick PR but feel free to fix yourself in the future - search for the string and use githubs editor to change it :)
