### ISSUE TITLE
Docker containers failing to start

### ISSUE THREAD

**Issue by c0bra** [PostHog/posthog#491]
**Describe the bug**

Both the preview and most recent release docker containers fail to start with the same error: "./bin/docker: line 5: ./bin/docker-server: No such file or directory"

**To Reproduce**

Simply attempt to run the preview per the docs:

    docker run -t -i --rm --publish 8000:8000 -v postgres:/var/lib/postgresql posthog/posthog:preview

**Expected behavior**

Posthog should start

**Additional context**

I'm wondering if this is because https://github.com/PostHog/posthog/blob/master/bin/docker is calling `./bin/docker-server` rather than `./docker`?

**Comment by mariusandra** [comment]
Hi @c0bra , I tried to reproduce the bug locally, but couldn't.

I ran:

```sh
docker pull posthog/posthog:preview # get the latest
docker run -t -i --rm --publish 8000:8000 posthog/posthog:preview
```

and everything booted up.

Same with `posthog/posthog:latest`. I ran:

```sh
docker pull posthog/posthog:latest
docker-compose up
```

with this [docker-compose.yml](https://github.com/PostHog/posthog/blob/master/docker-compose.yml) file that uses the latest posthog image and also boots up postgres and redis.

I didn't get the error you specified.

That said, the error does happen with `posthog/posthog:release-1.0.10.1`!
I thought `posthog/posthog:release-1.0.10.2` was released to fix this, but looking at the [hub](https://hub.docker.com/r/posthog/posthog/tags?page=1&ordering=last_updated) now I don't see it listed. @timgl ?

**Comment by timgl** [comment]
Very strange that `1.0.10.2` wasn't built automatically. That's fixed now.

@c0bra you might have to re-pull `posthog/posthog:preview`. Let us know if that solves the issue?

**Comment by c0bra** [comment]
Yes that seems to be working now. Thanks!
