### ISSUE TITLE
"Create a new project" self-hosted getting started experience feedback

### ISSUE THREAD

**Issue by leggetter** [PostHog/posthog#4912]
Upon getting started with a self-hosted install I wanted to create a new project. I selected the drop-down at the top and selected "Create a new project".

<img width="403" alt="Screen Shot 2021-06-29 at 11 12 24" src="https://user-images.githubusercontent.com/328367/123799033-b28fb080-d8df-11eb-8423-40d7b978af1b.png">

This then took me through a flow to request a license.

https://user-images.githubusercontent.com/328367/123798516-27aeb600-d8df-11eb-873d-826e13e4e224.mp4

After chatting to @marcushyett-ph I realised that there's a banner at the top of the page that has a "Go to setup" CTA that lets me create a new project. I'm a little embarrassed that I didn't notice this 😊 But I'm assuming other people may not see it either or just see it as some sort of success banner.

<img width="1311" alt="Screen Shot 2021-06-29 at 11 12 45" src="https://user-images.githubusercontent.com/328367/123798988-a6a3ee80-d8df-11eb-9e1d-88aa1e23a7f8.png">

Could the top drop-down also let me go through this flow? Could this result in people failing to get started and instead thinking they have to request a license?

## Describe the solution you'd like

Could the top project drop-down be aware of the context of the user: that they have not yet created their first project? And if that's the case then run them through the setup process?

**Comment by paolodamico** [comment]
Hey @leggetter! There's an additional consideration here. When running locally in debug mode (`DEBUG = 1`) you're actually entering a special flow that is currently off for all _real users_. You're entering the `onboarding-2822` experiment (more context in the product-internal repo) which was mostly discarded. Basically in this experiment you get a demo project by default and no real project, you play around with the demo first and then create your real project once you're ready. The current flow for actual users is they get into a real project, and immediately go through the event ingestion flow.

@kpthatsme and I wanted to revisit this initial activation flow to allow users to set up some alternative options on PostHog but haven't gotten around to it. Happy to provide additional context.

**Comment by leggetter** [comment]
@paolodamico Ah, so I followed the [developing locally docs](https://posthog.com/docs/developing-locally) which does indeed set `DEBUG=1`.

I'm assuming that most people follow one of the [deployment guides](https://posthog.com/docs/deployment)?

**Comment by paolodamico** [comment]
Indeed! You only follow the developing locally guide if you're going to contribute to the codebase. Regardless, I'll make a quick PR to avoid this confusion even for developing locally.
