### ISSUE TITLE
Get persons for funnel trends data points

### ISSUE THREAD

**Issue by Twixes** [PostHog/posthog#4918]
## Is your feature request related to a problem?

Trends have this nice feature of being able to click on a data point and seeing persons associated with it. So do funnel steps, just differently presented.
It'd be useful to have this feature in funnel trends too.

## Describe the solution you'd like

<img width="1082" alt="Funnel trends" src="https://user-images.githubusercontent.com/4550621/123827470-edeea700-d900-11eb-8a0e-ba75cde72710.png">

When such a data point in funnel trends is clicked, a list of persons making up this data point should appear. Those who reached `to_step` (making up the numerator of `conversion_rate`) should appear first, while those who dropped off and only reached `from_step` (making up the denominator of `conversion_rate`) should be showed separately.

As this list of persons may be large, the query should only return a limited number of them at once, using efficient pagination.

**Comment by paolodamico** [comment]
This is quite interesting. Particularly being able to see the list of persons who completed the entire funnel vs. some persons who started but dropped at some point, should be quite helpful at an initial understanding of why a number changed. This would probably benefit from a different view than the default person modal.

**Comment by neilkakkar** [comment]
Backend complete, but frontend still to be done.

**Comment by Twixes** [comment]
Frontend done too.
