### ISSUE TITLE
Put Plugins out of beta

### ISSUE THREAD

**Issue by Twixes** [PostHog/posthog#4920]
Plugins have been available as a beta feature for more than half a year now. In this time the feature set, API, and infrastructure all matured _a lot_.

We've been keeping it BETA because that label does give us more flexibility in introducing changes, and customer expectations are lower for something in that stage – breaking changes are more acceptable and so is bad behavior.

However we are now seeing less of the above two than ever, and the downside of these lower expectations is also lower adoption. People are obviously more reluctant to build their business using something marked as unstable.
So for plugins to be more successful as a PostHog feature, we should finally put them out of beta.

**Comment by mariusandra** [comment]
This sparks joy

**Comment by yakkomajuri** [comment]
Anything you both think is needed before this is done?

@Twixes @mariusandra

I'm thinking of doing some frontend updates and getting this done 🚀 🚀

**Comment by Twixes** [comment]
I think we're good to go.

**Comment by yakkomajuri** [comment]
Done on app. Need to merge a PR on `posthog.com`
