### ISSUE TITLE
Sankey Diagram for User Paths is 3 steps deep always (should be variable or redesigned?)

### ISSUE THREAD

**Issue by fuziontech** [PostHog/posthog#4933]
**This was a request from a potential enterprise client.**

![image](https://user-images.githubusercontent.com/391319/123885233-e085ec80-d901-11eb-9b61-29310113e818.png)

The issue is that they have a multi-step product path and 3 steps is not enough to provide any value in seeing how users are using their product. They have specifically asked for many more than 3, but this sounds like it could get less than ideal both from an experience POV and from a query performance POV.

This may require some interface redesigning, prototyping, and iterating to get right.
- At first it seems like a good next step would be maybe add a 2-5 step slider to have more flexibility?
- Next step might be to allow clicking into a step to reset the Sankey diagram to have that as the root node?
- Finally having some way to intuitively traverse the user path would be amazing. It's a really nice feature and right now it feels very rigid.

**Comment by samwinslow** [comment]
Totally agree this needs work. Slightly different data structure, but I freakin' love this clickable treemap diagram: https://observablehq.com/@d3/zoomable-treemap

Some things I like about it:

- clickable (obviously)
- completely hides the other segments/paths when drilling down
- filesystem-like navigation at the top allowing traversal back up the tree

**Comment by mariusandra** [comment]
Increasing the sankey from 3 steps to 5 will require adding a few extra lines to the query and shouldn't be a big problem. (I actually worked on the paths CH query many moons ago).

We could easily enable that if you  click on any of the nodes, it'll set that as the starting point, but I believe this is not what we want. This would set the node as the new starting point and start the calculation from that point. It would not show paths of people who got to that point... plus now 5 steps further. Adding unlimited depth like that will make the query building quite a bit more complex.

Not saying it can't be done, just sharing the context of what might be a quick change and what requires some deeper work.

**Comment by clarkus** [comment]
Showing more steps makes sense. Did the potential client say how many steps they thought they needed? I'm wondering how their use case could be served by funnels, too. This view is great for seeing where the traffic is happening, but once you have that info, you could jump over to funnels to really see what's driving persons through those specific flows. I'm wondering what the jumping off point would be for those users. Interactivity makes a lot of sense. It could be great to take the path they're interested in from User Paths, and preload that into the pageview filters for a funnel.

**Comment by paolodamico** [comment]
I think this is now stale with the work on #5665
