### ISSUE TITLE
Archive feature flags

### ISSUE THREAD

**Issue by paolodamico** [PostHog/posthog#4935]
## Is your feature request related to a problem?

After an experiment or a phased roll-out you want to remove the feature flag to avoid a cluttered list. Particularly you want to see a list of active experiments / rolling out features. Today, your option is to delete the feature flag, but the problem is you might actually want a record of these feature flags. Consider for instance when you're doing some analysis months later and you need to know the context on when and why something was released.

## Describe the solution you'd like

I'd like to have two separate options to archive or delete feature flags. I would also like to be able to toggle a list of archived feature flags, and search for them.

Related, we currently soft delete feature flags, but it actually makes sense to delete them completely if that's what the user wants.

## Describe alternatives you've considered

Keeping the current soft delete only (and maybe add an option to view deleted flags?).

## Additional context

- As all feature flags are currently soft-deleted, when making this transition we could actually turn all of them into archived so users can choose whether to keep them archived or permanently delete them.
- This will become even more relevant when we implement version history to feature flags and support A/B testing.

**Comment by macobo** [comment]
Q: Do we really need two different delete operations? How about renaming delete to archive + having a toggle to show archived? :)

**Comment by paolodamico** [comment]
I do think it's useful to have a permanently delete operation. Sometimes it's a mistake or a test flag and you don't really want it around. It also seems like a pretty standard mental model, deleting and archiving.

**Comment by mariusandra** [comment]
There's one problem with deleting feature flags && self-hosted instances.

Suppose we enable the new UI for you on 1.26. You see and use it and it's great. We release it on cloud and remove the flag  --> everyone's enjoying the new stuff on cloud, but your self-hosted UI is back to the old one.

Archiving flags (removing clutter from the main table), yet leaving them enabled and inlining some `$feature_flag_called` last 30days stats could help bring clarity.

**Comment by paolodamico** [comment]
Oh yeah, one thing I do around that is keep the feature flag around for 8-10 weeks after it's released for everyone, but I think that's a problem more particular to us, not so much for our users. But you do raise an important consideration to keep in mind here, archived feature flags should obviously become inactive immediately and you should be able to reuse the key without any issues.

**Comment by macobo** [comment]
> Oh yeah, one thing I do around that is keep the feature flag around for 8-10 weeks after it's released for everyone

That's not enough to guarantee that everyone has updated. This ticket suggests an alternative approach - https://github.com/PostHog/posthog/issues/2141
