### ISSUE TITLE
Feature flags not released properly

### ISSUE THREAD

**Issue by paolodamico** [PostHog/posthog#4937]
## Bug description

There's a bug when determining active feature flags. See [this feature flag](https://app.posthog.com/feature_flags/743) that should be released to all cloud users, and particularly to all "PostHog Team" members. Yet it appears disabled, at least for @mariusandra and I. This can be quite critical as we're releasing a ton of new features under a feature flag and this could mean it's not being actually released as we expected.

<img width="1334" alt="" src="https://user-images.githubusercontent.com/5864173/123936994-02c94a00-d996-11eb-9237-d0f3d71a29fa.png">

## Expected behavior

Flag should be active for all Cloud users.

## How to reproduce

See reproduction steps above.

## Environment

- [ ] PostHog Cloud
- [ ] self-hosted PostHog, version/commit: _please provide_

**Comment by mariusandra** [comment]
I'm not sure what was the case here, but this works again for me...

**Comment by paolodamico** [comment]
Me neither, but seems to be working fine now, so closing.
