### ISSUE TITLE
Cannot open toolbar on a site

### ISSUE THREAD

**Issue by macobo** [PostHog/posthog#4942]
## Bug description

Client reported not being able to open toolbar on their site. [Thread](https://posthogusers.slack.com/archives/G01JXEDAL22/p1624997163025300)

The error is here:
![image](https://user-images.githubusercontent.com/148820/123949200-f8fe1180-d9aa-11eb-9c4e-efac5c8eff9c.png)

## Expected behavior

Toolbar works

## Environment

- [x] PostHog Cloud
- [ ] self-hosted PostHog, version/commit: _please provide_

**Comment by macobo** [comment]
Cause seems to be dayjs which the toolbar implicitly embedded in frontend/src/toolbar/stats/HeatmapStats.tsx via frontend/src/lib/components/DateFilter/DateFilter.tsx. It seems this site has some global polyfills installed which interfere with dayjs (Array.prototype.clone?).

I think the best solution here is not to use `frontend/src/lib/components/DateFilter/DateFilter.tsx` which is very app-specific but have a smaller, leaner version for toolbar.

**Comment by macobo** [comment]
cc @mariusandra actually seems like we introduced this feature relatively recently. What are your thoughts?

**Comment by samwinslow** [comment]
Might this also be related to E2E test failures where the toolbar is not found in the DOM?

**Comment by macobo** [comment]
Doubt it, this is not a flake but something that happens always for that site

**Comment by gplaycock** [comment]
@macobo The toolbar hedgehog does appear intermittently so it is not always happening
<img width="1132" alt="Screen Shot 2021-07-14 at 7 47 12 PM" src="https://user-images.githubusercontent.com/4688789/125706741-90e18834-88f8-4d99-b4e0-754559919fc0.png">
.  I cannot figure out how to reproduce it though.
