### ISSUE TITLE
multiple cohorts as breakdown have counting-difficulties

### ISSUE THREAD

**Issue by kerstindrazkiewicz** [PostHog/posthog#4945]
## Bug description

*Please describe.*  
*If this affects the front-end, screenshots would be of great help.*  

We created a chart to track cohort user activity. As soon as we add different cohorts to one dashboard, the output becomes the same for each row (with different cohorts). And if we add only one cohort to the chart, the output changes again: btw - we assume the one by one is the correct output. It looks more like the real data

## Expected behavior

If you add more then one cohort into the breakdown, we would like to see the output of each cohort. 

## How to reproduce

1. create a dashboard with different cohorts included which should count unique users
2. add multiple cohorts to the braekdown
3. the table shows for each cohort the same counting

## Environment

- [x] PostHog Cloud app.posthog.com 
- [ ] self-hosted PostHog, version/commit: _please provide_

## Additional context
This is how it looks with multiple cohorts added via breakdown
![image](https://user-images.githubusercontent.com/86724450/123963104-6b262480-d9b2-11eb-8fb0-94a27ab0dc11.png)

This is how it looks only with one cohort added via breakdown
![image](https://user-images.githubusercontent.com/86724450/123963196-84c76c00-d9b2-11eb-88f8-e25b9e3c4829.png)

#### *Thank you* for your bug report – we love squashing them!

Thanks in advance. 😃

**Comment by EDsCODE** [comment]
This doesn't seem to happen anymore if I'm understanding the issue correctly
