### ISSUE TITLE
Allow filtering users by "last seen"

### ISSUE THREAD

**Issue by macobo** [PostHog/posthog#4955]
## Is your feature request related to a problem?

Customer request:

>I am looking for a way to view all users (by workspace) to see who has NOT logged in in the last week

This is a simple way to figure out users who might be "slipping away" - something really useful on the support/success side of product analytics. This is also a feature used heavily in intercom.

We already have a "persons" table - a simpler fix for that usecase is allowing users to filter by when the user did their last event. 

## Describe the solution you'd like

In persons page, allow user to specify e.g. `last_seen:>"2020-05-12"`

## Additional context

Related: https://github.com/PostHog/posthog/issues/2594

**Comment by marcushyett-ph** [comment]
Thanks for sharing - this one is really interesting.

I'm really curious as to what they would do with this list as we might be able to solve the root problem, would it be possible to ask a follow up question?

We had a similar idea shared on a call with a customer yesterday which was around people who've dropped off at some point being able to integrate with CMS or send a bulk email to bring them back to the product.

I'm wondering if we might be able to come up with a deeper solution to help automate a lot of this type re-engagement activity.

**Comment by macobo** [comment]
So this feature that's similar in He@p is users search: 

![image](https://user-images.githubusercontent.com/148820/124115052-ffa58b00-da75-11eb-8a87-48c1e208bbdc.png)

This is a tiny feature that gets us just a tiny bit closer to there.

A CS team could use it to find users at risk of churn. https://www.intercom.com/help/en/articles/426-retain-customers-that-are-slipping-away - though their approach suggests more towards approaching it with cohorts + using advanced filters to define these cohorts.
