### ISSUE TITLE
Add SMTP credentials in UX

### ISSUE THREAD

**Issue by jamesefhawkins** [PostHog/posthog#496]
**Is your feature request related to a problem? Please describe.**
For users to have a password reset, they currently have to set env variables. This isn't user friendly.

**Describe the solution you'd like**
In the settings page of the app, be able to set:

```
EMAIL_HOST
EMAIL_PORT
EMAIL_HOST_USER
EMAIL_HOST_PASSWORD
EMAIL_USE_TLS
EMAIL_USE_SSL
DEFAULT_FROM_EMAIL
```

**Describe alternatives you've considered**
Set environment variables.

**Comment by timgl** [comment]
Hm did you get this as feedback from someone? It feels like if you know what an SMTP server is you know how to set them as env variables?

Also it's though because we don't have instance-wide settings we can save in a database, only team-wide, so it'll get much harder to set these in a logical palce

**Comment by jamesefhawkins** [comment]
This suggestion didn't come from a user, I thought it'd help the UX. I'd suggest I downgrade the priority to 7 to see if anyone upvotes it, then we can get a signal if people are getting stuck here.

I think the best temporary solution is to write in the docs how to do a password reset. It's in the deployment section which makes it hard to find.

In terms of where it should sit, I'd imagine instance level is appropriate. As you say, that's not currently possible.

**Comment by timgl** [comment]
If you don't have SMPT set and you click 'forgot password' we give you these instructions:
![image](https://user-images.githubusercontent.com/1727427/78793351-32afba80-79aa-11ea-9444-8fc045b003d1.png)

**Comment by paolodamico** [comment]
This is now supported with instance settings!
