### ISSUE TITLE
Allow funnel attempt-based (as opposed to person-based) funnel conversion

### ISSUE THREAD

**Issue by Twixes** [PostHog/posthog#4972]
## Is your feature request related to a problem?

Currently our funnel analyses – steps and trends – show conversion rates based on _persons_. That means a person can only count at most once in a period. However in some cases, where a person can try to go through a funnel repeatedly, we'd like to know the conversion rate _for each time that person tries_ – which would be able to include more than one attempt per person per period in results.

## Describe the solution you'd like

A selector allowing to switch between unique user and total count, similar to what we have in trends:
<img width="166" alt="PostHog" src="https://user-images.githubusercontent.com/4550621/124247654-5cf71600-db22-11eb-91f7-fd6b9ae04655.png">

Also see Mixpanel which already have this in funnels (we currently only support "Uniques"):
<img width="288" alt="Mixpanel" src="https://user-images.githubusercontent.com/4550621/124247661-5f597000-db22-11eb-882f-09dc414ce046.png">

## Additional context

Requested by a user on Slack.

**Comment by paolodamico** [comment]
This seems quite powerful but I don't think we've heard much need from this from users yet, so perhaps waiting for some results on the main funnels functionality, wdyt @marcushyett-ph ?

**Comment by marcushyett-ph** [comment]
I think this could be really valuable, but I think right now we should focus more on improving the quality of what we have available, but keep this as an open issue and comment on it when we hear any feedback around this from customers.

**Comment by Twixes** [comment]
Situation reported by a customer, where this seems like the right solution (#6007):
- I have events "open X" and "close X", and a bunch of persons
- Each person can perform multiple sequences of these events
- I would like to see how long does it usually take between the open and close events, and how often the "close" event even happens.
