### ISSUE TITLE
Funnel persons with repeated events

### ISSUE THREAD

**Issue by EDsCODE** [PostHog/posthog#4980]
## Bug description

*Please describe.*  
- when there are repeated events in the funnel steps, the persons api gives incorrect data

example: the third step doesn't return correctly

<img width="621" alt="Screen Shot 2021-07-02 at 9 51 25 AM" src="https://user-images.githubusercontent.com/25164963/124296674-3a67fb80-db28-11eb-8b44-c57e3df9f196.png">

*If this affects the front-end, screenshots would be of great help.*  

## Expected behavior
- the api should return people as expected 

## How to reproduce

1. Define a funnel with multiple steps with at least two sequentially that use the same event/action
2. Click on the later persons link for step or drop off
3.

## Environment

- [ ] PostHog Cloud
- [ ] self-hosted PostHog, version/commit: _please provide_

## Additional context
@liyiy

**Comment by EDsCODE** [comment]
**might be corrupted local demo data because I can't seem to reproduce this issue with backend tests at all

**Comment by liyiy** [comment]
update: There is a mismatch because the new funnel query hasn't been implemented yet, which is why it shows that there's people in the funnel step where there shouldn't be. The funnel persons call is probably the correct one.

**Comment by neilkakkar** [comment]
Think we can close this? Pending migration from `ClickhouseFunnel` -> `ClickhouseFunnelNew` .
