### ISSUE TITLE
Cannot add filter to session action

### ISSUE THREAD

**Issue by alexkim205** [PostHog/posthog#4982]
## Bug description

https://user-images.githubusercontent.com/13460330/124306597-79dc1b00-db1b-11eb-8f85-9dc8b37a786f.mov

## Expected behavior

Events/cohorts/action filter dropdown isn't working.

## How to reproduce

1. Go to Sessions
2. Try to add a filter

## Environment

- [X] PostHog Cloud
- [X] self-hosted PostHog, version/commit: _please provide_

**Comment by marcushyett-ph** [comment]
This one looks a bit frustrating, we should aim to fix as part of our next milestone

**Comment by alexkim205** [comment]
This one seems to have been fixed by @mariusandra's rework of filters! I think it's safe to close this one.
<img width="687" alt="Screen Shot 2021-07-27 at 4 58 12 PM" src="https://user-images.githubusercontent.com/13460330/127242454-a36922b3-65c3-46af-9216-a29f385722bd.png">
