### ISSUE TITLE
Sprint 1.28.0 1/2 Retrospective

### ISSUE THREAD

**Issue by alexkim205** [PostHog/posthog#4984]
## Things to Improve On

- Individuals should contribute to company-wide retro boards so that context is always up-to-date and accurate
	- Maybe team lead can send casual slack msg (or even slack bot can do this) to #team-core-experience asking everyone for a one line update before creating list
- Plan better for sprint planning design
- No separation between epics and issues (esp. for funnels)
	- Hard to keep organized
	- Where do you ask questions?
	- Where and who do you update?
	- Feel like we’re finding out about things, not part of the process
	- Smaller threads for design comments
- Improve discoverability of docs/pages/tutorials/boards/issues as a new hire
	- Learning the ropes in GH -> Tim Glaser and Yakko Majuri 

### @clarkus  
**Items**
- funnels horizontal/vertical layouts
- look into histogram issue
- next steps taxonomy and filtering for charts
- graphs aren't color blind friendly
**Blockers**
- Just need more time

### @samwinslow 
**Items**
- funnels horizontal and vertical bars
- naming of "vertical" and "horizontal" maybe top to bottom or left to right
- filtering stuff and state management in insights graph
	- https://docs.google.com/document/d/1D77-78mEAzn1wdPYGFoC6NvkMm-5dSFt7qCWwJ6_Xdk/edit
**Blockers**
- Kea struggles

### @liyiy 
**Items**
- Got Intel laptop
- Backend wants to replace funnels query
- funnel trends
- connected funnel persons to frontend

**Blockers**
- Clickhouse person data not showing
- Some backend work
- People to review PR

### @corywatilo 
**Items**
- Marketing stuff

**Blockers**
- Nope

### @alexkim205  
**Items**
- Merged deeplink sessions changes
- working with Chris to hash out details of time conversion histogram
- Various bug fixes here and there

**Blockers**
- Nope

**Comment by paolodamico** [comment]
Thanks for detailing this retro in GitHub for the benefit of those of us who weren't there! Should we close this issue now?

**Comment by alexkim205** [comment]
Yup sounds good!
