### ISSUE TITLE
Allow mixing and matching funnel ordering and funnel viz types

### ISSUE THREAD

**Issue by Twixes** [PostHog/posthog#4988]
## Is your feature request related to a problem?

We now possess the ability to run ordered OR unordered funnel analyses.
We can also run queries that return conversion rates for all steps, conversion rates over time, or conversion times bucketed.
_However_ unordered analysis can only be combined with all steps viz. It'd be very useful if _each_ viz type would be able to work with both types of ordering – ordering would then be a simple UI switch in all funnel insights.

## Describe the solution you'd like

Ideally the unordered funnel query would return the results in the same format as the ordered one, in which case the base subquery (`steps_per_person_query`) could be just swapped out as needed in each dependent final query: steps, trends, time to convert. Maybe that is not be the best way – TBD.

One discrepancy that is also currently in the code is that the base funnel query is ordered, while the unordered one builds _on top_ of the base one. Not sure if that's ideal, because it makes it seem like the ordered one is superior/"senior", when in reality they should be on equal footing, and equally swappable.

**Comment by neilkakkar** [comment]
One question: Why do you think the unordered one builds on top of the **ordered** one? (assuming that was a typo?). Every funnel building on top of the base query makes sense to me?

**Comment by Twixes** [comment]
Well, the issue is that the base query IS the ordered query. So when dependent queries get subquery `steps_per_person_query` from the base funnel class, that subquery is ordered. If `steps_per_person_query` was somehow able to build a subquery that would return results in the same format, but of an **unordered** funnel instead of ordered, we'd be able to easily just swap that portion in dependent queries – as opposed to building whole new unordered FunnelTrends and FunnelTimeToConvert.

**Comment by neilkakkar** [comment]
Ah, I see what you mean. So, `_get_steps_per_person_query` in the `base` sets up the ordered bit, while the unordered funnel only uses the `_get_inner_event_query` which is effectively the inner-most part of the query.

And (now) I see why you'd consider the base to be the ordered one, it's because time to convert and trends use this from the `base`. This makes sense, I'll move this up the ordered funnel, so this partition becomes clearer. Good shout.
