### ISSUE TITLE
Get Strict and Unordered Funnels to return appropriate step conversion times

### ISSUE THREAD

**Issue by neilkakkar** [PostHog/posthog#5003]
## Is your feature request related to a problem?

Right now, strict and unordered funnels give appropriate counts, but not the step conversion times. Reach parity with the general ordered funnel.

## Describe the solution you'd like

Strict and Unordered funnels should follow the exact same format as the ordered funnels, so modify the query to return the appropriate values here.

## Additional context

A pre-cursor to https://github.com/PostHog/posthog/issues/4988

**Comment by neilkakkar** [comment]
Finally got unordered step times to work: this is a very weird-ish case, since: the same person can complete the funnel multiple times in different orders, which changes the step conversion time for each step.

Since the specific order in which the user completed the funnel doesn't matter here, I've opted to not include this information in our APIs / query result (this, thankfully, helps keep the result shape same across funnel orders).

However, at the same time, the query _does_ figure out what the next step was, and calculates the step conversion time appropriately.

In the end, what gets returned is the average step conversion time from 1st event to 2nd event, for all users who successfully did two events, irrespective of which specific events these were.

So for example, if User 1 did A->B in 20 seconds; and User 2 did B->C in 40 seconds; and then C-> A in another 40 seconds; and A, B, C are all part of the unordered funnel, the average step time from 1->2 is 30 seconds, the sum of the first two values above. I don't include C->A for User 2, because that's the next step conversion time! (since User 2 did B->C->A)

For another example, consider:
- User 1 did A->B in 20 seconds and B->C in 40 seconds. 
- User 2 did B->C in 10 seconds and C->A in 20 seconds.
- User 2 did A->B in 30 seconds and B->C in 30 seconds.
Then Step 1 conversion time is (20+(10+30)/2)/2 = 20 seconds, and Step 2 conversion time is (40+(20+30)/2)/2 = 32.5 seconds; since both completed their funnels, and user 2 did it twice, so their times gets averaged first.

**Comment by EDsCODE** [comment]
Seems plausible. For correctness of concept I think @kpthatsme might have a better take on any alternatives to calculating the times here
