### ISSUE TITLE
Bug with order column on person->events

### ISSUE THREAD

**Issue by paolodamico** [PostHog/posthog#5009]
## Bug description

We show an order column for each event in the sessions table of the person page. Yet when we filter events in the session, the full original order is not kept. We calculate the order just based on the position in the current view. I’m not sure if we should fix this bug or drop this column. Does someone have any context behind this column?

![image](https://user-images.githubusercontent.com/5864173/124922636-4daf1700-dfbf-11eb-9df2-e7a34d804281.gif)

## Expected behavior

Either drop the column or keep the ordering as if no filters were applied so the column actually provides extra information.

## How to reproduce

1. See recording.

## Environment

- [X] PostHog Cloud
- [X] self-hosted PostHog, version/commit: _please provide_

**Comment by mariusandra** [comment]
I vote for dropping it and regaining space for the rest of the interface. I'm not sure when it's really important to know this is the 32nd event in a session. If someone has a good reason, don't hold back :).

**Comment by macobo** [comment]
Nuke it.

> Does someone have any context behind this column?

I'll refer back to my favorite issue: https://github.com/PostHog/posthog/issues/4884. Short answer to all questions context - no, all of this requires rethinking. :)
