### ISSUE TITLE
New tooltips don't display math operations

### ISSUE THREAD

**Issue by yakkomajuri** [PostHog/posthog#5016]
## Bug description

Old tooltips would tell me what the property and math operation applied to it for a given graph series, but new tooltips do not.

See a plugin metrics example:

### Old 

![](https://user-images.githubusercontent.com/38760734/123292411-67455e80-d4e9-11eb-98dd-37b968b68410.png)

### New
<img width="188" alt="Screenshot 2021-07-06 at 16 04 08" src="https://user-images.githubusercontent.com/38760734/124653912-429ba000-de74-11eb-86b6-824d85f93aac.png">

## Expected behavior

Show me the property and math op.

cc @paolodamico

**Comment by macobo** [comment]
In instance status dashboards the tooltips seem to be there, but inconsistent?

https://user-images.githubusercontent.com/148820/124728081-f4d87380-df17-11eb-9123-076832da6125.mp4

**Comment by paolodamico** [comment]
Thanks for reporting @yakkomajuri! We should be showing all math operations on the tooltips, so definitely a bug. Further, `$$plugin_metrics` should be properly parsed. Can you share either a link to the graph you're referencing or a full screenshot of your query? Trying to reproduce

**Comment by yakkomajuri** [comment]
If you go to the plugins page and click on the little chart icon for any plugin, you should be able to see this
