### ISSUE TITLE
OR properties filtering

### ISSUE THREAD

**Issue by liyiy** [PostHog/posthog#5035]
## Is your feature request related to a problem?

*Please describe.*

Currently our properties filters only allows for ANDs (if I want to add multiple properties they keep stacking on top of each other)

## Describe the solution you'd like

Allow for ORs (adding multiple properties doesn't stack on top of each other)

## Additional context

This came out of work for #4819, specifically for persons modal searching. On clickhouse we are able to re-use the properties param to "search" for a user BUT we're unable to do a search for a user's name OR a user's distinct_id, we can only pick one. 

Example: I want to search for users who have either "xyz" in their names or their distinct_ids

**Comment by clarkus** [comment]
I put some thought into this recently when working on query building. This is in the context of funnels, but could apply to any filtering scenario. We can include a global control for the set of funnel declarations: `match any` or `match all` - this would save us from having to repeat logical operators between steps while still satisfying the main request. 

<img width="857" alt="Screen Shot 2021-07-28 at 11 04 35 AM" src="https://user-images.githubusercontent.com/254612/127373525-8388bfb6-88ac-4082-b85d-d8bb5f00a6f6.png">

**Comment by paolodamico** [comment]
I’m a bit concerned that the “Match” is not clear enough standalone. Match all does communicate well that you’re ANDing all conditions, but match seems ambiguous. Perhaps an option would be to add a tooltip with extra context, but I do feel the “OR” tags are even clearer. What are we trying to accomplish here?

**Comment by clarkus** [comment]
Match all === implicit `AND` between filter rules. Match any === implicit `OR` between filter rules. Unless we plan on supporting logical operators in each rule, this would let us set a mode for the set and save repeating and / or in every row.

**Comment by paolodamico** [comment]
I don't think we plan to support dynamic filtering soon but I think it may be useful to repeat them. Or how about "match any" instead of just "match"

**Comment by clarkus** [comment]
@paolodamico I don't think I'm understanding the question. The goal I'm trying to accomplish is setting a logical operator mode for the set of filters in a single prominent place. Where else would a user change this setting if not in some centralized position? If they're changing it for each declaration, that might be confused with dynamic operators between filters. 

Is this more specific to picking values? Are we wanting to enable "or-ing" for a set of values within a single filter declaration? Maybe some real examples would help me understand the cases we're solving for?

**Comment by paolodamico** [comment]
Okay sorry I didn't clarify well. I'm 100% aligned with the position of the filter (I was only suggesting using "Match any" instead of plain "Match"). In any case the point I was trying to make was to keep the "OR" labels (static labels like we have in cohorts, feature flags, ...) after each filter line, but that might not be needed.

**Comment by clarkus** [comment]
OK I was confused, too, but I think we're aligned now. I have the control using `match any` / `match all`. I don't know if we need to repeat the operators, but it doesn't seem like it does any harm so we could try it.
