### ISSUE TITLE
Small suggestions to improve readability of trends charts w/ multi-series

### ISSUE THREAD

**Issue by kpthatsme** [PostHog/posthog#5052]
## Is your feature request related to a problem?
I'm putting together a dashboard for the marketing team with a multi-series trends chart. The chart is exactly what we need and is super powerful.

The problem is it's pretty tough to read.

When hovering over the tooltips, I don't have enough context from the dashboard view to know what I'm looking at. Clicking into the chart also leads to a bit of a tedious workflow that I think will hurt power users over time and lead to messy dashboards.

## Describe the solution you'd like

Instead of writing it out, I decided to record a short loom walking through the use case and some concrete suggestions:
https://www.loom.com/share/417806be41fb44ce9a57613627323b90

**Comment by paolodamico** [comment]
Would this be solved with better tooltips (#7370) and potentially the legend key within the graph. Curious to hear your thoughts @clarkus

**Comment by clarkus** [comment]
> Would this be solved with better tooltips (#7370) and potentially the legend key within the graph. Curious to hear your thoughts @clarkus

I saw two distinct problems represented here:

1. Tooltips could be improved
    - Better describe the data points for a point in time on the x-axis
    - Better describe a specific data point on the chart
2. Insight queries need to be better described
    - Right now the only way to do this is to go to edit mode and read all the filters line by line. We might benefit from a read-only version of this for the read only view of insights. Generally, we need to succinctly describe the query, its filters, and other parameters that power the insight. Note that this is partially improved with re-namable graph series.

**Comment by paolodamico** [comment]
I think the changes we're targeting with the new insight description card and the new tooltips both currently in progress will solve this, so worth closing. Please reopen if you disagree.
