### ISSUE TITLE
Lingering tooltips

### ISSUE THREAD

**Issue by yakkomajuri** [PostHog/posthog#5061]
## Bug description

New tooltips don't disappear if you hover away via the chart's right edge:

https://user-images.githubusercontent.com/38760734/125440301-0dc2eef2-e953-4bdc-bffd-9b89066eae1f.mov

**Comment by paolodamico** [comment]
Actually @samwinslow, think you may have better context to fix this?

**Comment by samwinslow** [comment]
> Actually @samwinslow, think you may have better context to fix this?

Yep can definitely take a look. It's something going on with the charting library.
