### ISSUE TITLE
SSO domain whitelist & automatic signup

### ISSUE THREAD

**Issue by paolodamico** [PostHog/posthog#5065]
## Is your feature request related to a problem?

If my company has 100+ employees, inviting all of them to PostHog would be too time consuming. 

## Describe the solution you'd like

As I've already provisioned them on Google/GitHub/GitLab, I would like to enable any user who has an account in a whitelisted domain to sign up on their own and join the existing organization (instead of a new one being created).

## Describe alternatives you've considered

- Syncing the G-Suite directory and automatically creating accounts?
- Uploading a CSV list?

## Additional context

Need to consider special cases of doing this in cloud vs. on self-hosted.

**Comment by macobo** [comment]
> Need to consider special cases of doing this in cloud vs. on self-hosted.

I'd solve this in the lazy way for self-hosted only by adding a new environment variable: `SOCIAL_AUTH_DEFAULT_ORGANIZATION_ID` seems like a good 80/20
