### ISSUE TITLE
Cryptic error message when using an invalid selector

### ISSUE THREAD

**Issue by paolodamico** [PostHog/posthog#5066]
## Bug description

If I create an action with an invalid selector, I get a cryptic error message that doesn't tell me what the problem is or how to fix it.

<img width="385" alt="" src="https://user-images.githubusercontent.com/5864173/125134026-52adbc80-e0cc-11eb-9f28-8952b92a9ad9.png">

## Expected behavior

I would expect to see a very friendly message, telling me what the exact problem is and how to fix it. UX wise I may actually want to see this next to the input that requires fixing as opposed to the toast? 

## How to reproduce

1. Create an action with an invalid selector (today for example: `[data-attr="i am invalid today"]`).

## Environment

- [X] PostHog Cloud
- [X] self-hosted PostHog, version/commit: _please provide_

**Comment by macobo** [comment]
Kind of related: https://github.com/PostHog/posthog/issues/4680
