### ISSUE TITLE
Polyfill Object.fromEntries

### ISSUE THREAD

**Issue by mariusandra** [PostHog/posthog#5071]
## Is your feature request related to a problem?

Issue https://github.com/PostHog/posthog/pull/4999 implemented a polyfill for `Object.fromEntries` for Safari 12 and below, however it's not really a polyfill, but a workaround.

We should implement a real polyfill.

## Describe the solution you'd like

The `Object` JS class should contain a function called `fromEntries`.

We **can not guarantee** that every developer working on this codebase in the future knows to do:

```js
import fromEntries from 'object.fromentries'
const newObject = fromEntries(Object.entries(...).map(...))
```

## Additional context

[core-js](https://github.com/zloirock/core-js) is the polyfill used by every JS project out there (either directly or via some babel mechanism). We should do the same and then revert #4999.

**Comment by lharress** [comment]
I could take a stab at this one, I've spent a decent chunk of time with Babel. A quick glance looks like half of it is already set up. Might just be a matter of tweaking some settings.

Is there a list of browsers that Posthog wants to support?
