### ISSUE TITLE
Allow creating Cohorts out of Persons in a Funnel Step

### ISSUE THREAD

**Issue by neilkakkar** [PostHog/posthog#5075]
## Is your feature request related to a problem?

Given a funnel, I've discovered something interesting. I've gotten a list of people belonging at this funnel step. Now, I want to do further analysis on this group of people and what they've been doing.

Allow me to quickly create a Cohort from the Persons Modal in funnels.

## Additional context

This becomes an excellent use case for https://github.com/PostHog/posthog/issues/5074

**Comment by marcushyett-ph** [comment]
Love this idea @neilkakkar. @mariusandra @paolodamico is this already on our radar?

**Comment by mariusandra** [comment]
Definitely on the radar, but not planned for this sprint. @EDsCODE is probably more knowledgeable on how hard this would be to implement.

**Comment by clarkus** [comment]
We definitely have this action in the designs for the person modal. I think it's mostly down to feasibility and implementation at this point?
<img width="451" alt="Screen Shot 2021-07-12 at 8 03 05 AM" src="https://user-images.githubusercontent.com/254612/125310892-d7c0ed80-e2e7-11eb-8beb-2ee686bfcc80.png">

**Comment by marcushyett-ph** [comment]
Aha, @liyiy would love to hear your thoughts on this - since I think you were working on it - please correct me if I'm wrong.

**Comment by liyiy** [comment]
The option should be available, it's hidden beneath an existing feature flag `'save-cohort-on-modal'`, seems to work for me when I test it out locally

**Comment by mariusandra** [comment]
I guess this can be closed then @neilkakkar :D
