### ISSUE TITLE
Loading state for Persons modal

### ISSUE THREAD

**Issue by corywatilo** [PostHog/posthog#5087]
## Bug description

When clicking a point on a graph to view the Persons modal, it can take more a few seconds for the data to load. Until it finishes loading, it appears there are 0 matching users.

![image](https://user-images.githubusercontent.com/154479/125331782-6fd5cb80-e316-11eb-9dfc-6372f1b56e2d.png)

Once the data finishes loading, the correct values pop in.

![image](https://user-images.githubusercontent.com/154479/125331882-9431a800-e316-11eb-9da4-661f45463f44.png)

## Expected behavior

At minimum, a loading spinner would indicate _something_ is happening and that patience is required.

## How to reproduce

1. View a graph
2. Click a plot to view users
3. See modal

## Environment

- [X] PostHog Cloud

**Comment by paolodamico** [comment]
@liyiy let me know if you want me to pick this up

**Comment by liyiy** [comment]
> @liyiy let me know if you want me to pick this up

I can grab it unless you have a very specific design in mind 😄

**Comment by paolodamico** [comment]
Go for it @liyiy! Nothing in particuar, was just thinking about a simple loading skeleton.
