### ISSUE TITLE
Explain how identical funnel steps work in the UI

### ISSUE THREAD

**Issue by Twixes** [PostHog/posthog#5088]
## Is your feature request related to a problem?

Currently users get confused by the way identical funnel steps work. When two or more steps are identical _one after another_, they sometimes expect there to be no dropoff from identical step 1 to identical step 2.

But the way it really works (shown below) is much more practical:
What PostHog does instead, is that out of the set of people who performed the step once (making up step 1), for step 2 it counts people who performed that step for a second time in the funnel window. This way it's possible to construct funnels requiring a user to perform a specific action _n_ times before carrying on with the rest of the funnel.

<img width="1196" alt="Funnel" src="https://user-images.githubusercontent.com/4550621/125333292-5b132b00-e34a-11eb-8efb-bf80e15a9343.png">

## Describe the solution you'd like

If a step is identical to the previous one, it should have a tooltip (over an ℹ️ icon maybe) explaining why there's a dropoff.

## Additional context

See #5046 or https://posthog.slack.com/archives/C0113360FFV/p1626110518064100.

**Comment by mariusandra** [comment]
Somehow I've always seen this as "first pageview", "second pageview", "third pageview" and it all just makes sense. E.g. people who only do two pageviews drop of after that.

Instead of a "ℹ️", what about just numbering them? E.g. "Pageview #1", "Pageview #2", etc. Would this clear it up enough?

**Comment by Twixes** [comment]
We'd have to see with users, but that does sound like a sensible and simple solution.

**Comment by paolodamico** [comment]
Love @mariusandra's idea, though I would still add a tooltip (probably a `title` instead of Ant's full tooltip) in the name, in case you really need more context on this. We've gotten very positive feedback across the board on having these tooltips with very explicit information.

**Comment by paolodamico** [comment]
I'll pick this up if no one else can

**Comment by samwinslow** [comment]
Flyby comment: there is also a difference in returned data depending on whether you're running the query on psql or Clickhouse — am I correct @EDsCODE ?

**Comment by EDsCODE** [comment]
Yeah, iirc our postgres implementation doesnt support identical event differentiation like clickhouse does

**Comment by clarkus** [comment]
This is a pretty verbose tooltip, but here's a quick stab at showing a clearer representation of repeated steps in funnels. 

<img width="748" alt="Screen Shot 2021-07-19 at 11 47 27 AM" src="https://user-images.githubusercontent.com/254612/126211321-396bcf33-9884-4105-92d6-bde92ccf1199.png">
