### ISSUE TITLE
X-axis should start at 0

### ISSUE THREAD

**Issue by timgl** [PostHog/posthog#510]
**Describe the bug**

It's weird looking at a graph when you think a datapoint is zero but it's actually not.
![image](https://user-images.githubusercontent.com/1727427/78830158-6c4ee880-79df-11ea-9a04-a480dc435fb7.png)

**To Reproduce**
1. Find a graph where none of the datapoints are actually 0

**Expected behavior**
The graph should always start at 0

**Additional context**
I'm open to discussion if people feel strongly the other way

**Comment by 03difoha** [comment]
heres  a fix in this pull request https://github.com/PostHog/posthog/pull/563
