### ISSUE TITLE
Anynonymous ID isn't associated when calling `identify`

### ISSUE THREAD

**Issue by baptisteArno** [PostHog/posthog#5102]
## Bug description

Whenever I'm calling the `identify` method:
```ts
posthog.identify(user.id, {
      email: user.email,
      name: `${user.firstName}, ${user.lastName}`,
      plan: user.plan,
    });
```
It doesn't associate the anynonymous ID to the new id given:
![CleanShot 2021-07-13 at 15 48 58](https://user-images.githubusercontent.com/16015833/125464382-e1a59644-2020-4163-82e1-439cb8f544bb.png)

As described [in the doc](https://posthog.com/docs/libraries/js#multiple-ids), it is supposed to merge the two IDs. What could be wrong here?

## Environment

- [x] PostHog Cloud

**Comment by respectTheCode** [comment]
I am seeing this same thing. Is this functionality not working or am I doing something wrong?
