### ISSUE TITLE
/trends breaks if you navigate to a url from dashboard

### ISSUE THREAD

**Issue by timgl** [PostHog/posthog#511]
**Describe the bug**

The filters in the DashboardItems don't have type: set historically. With the new changes those break.

![image](https://user-images.githubusercontent.com/1727427/78840639-33207380-79f3-11ea-9028-066e8837d56d.png)

**To Reproduce**
1. Click on the link in one of the dashboard items
2. It breaks.

**Comment by EDsCODE** [comment]
I believe this error only exists on the initially set pageview item. let me know if the bug is more widespread than that

**Comment by timgl** [comment]
@EDsCODE This happens for all existing dashboard items so that PR didn't fix it unfortunately.

We could either have a migration that adds the type (see `0030_migrate_dashboard_days.py`) or just handle this case in the frontend.
