### ISSUE TITLE
Export Sessions as CSV

### ISSUE THREAD

**Issue by samwinslow** [PostHog/posthog#5114]
Users would like to be able to export a list of all Sessions for a given timeframe as CSV. Currently, the closest way to do something similar would be to get JSON back from the API.

## Describe the solution you'd like

- Export button like we have on a few other tables.
- Really nice to have: Generic way to add CSV exports to _any_ place in the app where we have data in a table.

## Additional context

Other issues around CSV export UX and bugs:

- https://github.com/PostHog/posthog/issues/755
- https://github.com/PostHog/posthog/issues/4624

**Comment by paolodamico** [comment]
We no longer have sessions.
