### ISSUE TITLE
Negative funnel time conversion bin times

### ISSUE THREAD

**Issue by alexkim205** [PostHog/posthog#5116]
## Bug description

The new funnels time conversion endpoint sometimes returns bins with negative time values. This makes it difficult to reflect accurate time conversion funnels data on the frontend. @Twixes @neilkakkar 

<img width="379" alt="Screen Shot 2021-07-13 at 9 14 42 PM" src="https://user-images.githubusercontent.com/13460330/125560350-3ef2eb03-5fc5-4c89-a0ab-988c945d7d87.png">

Example CH localhost [link ](http://localhost:8000/insights?insight=FUNNELS&properties=%5B%5D&filter_test_accounts=false&interval=day&events=%5B%7B%22id%22%3A%22%24pageview%22%2C%22name%22%3A%22%24pageview%22%2C%22type%22%3A%22events%22%2C%22order%22%3A0%7D%2C%7B%22id%22%3A%22%24pageview%22%2C%22name%22%3A%22%24pageview%22%2C%22type%22%3A%22events%22%2C%22order%22%3A1%7D%2C%7B%22id%22%3A%22%24pageview%22%2C%22name%22%3A%22%24pageview%22%2C%22type%22%3A%22events%22%2C%22order%22%3A2%7D%5D&display=FunnelsTimeToConvert&actions=%5B%5D&new_entity=%5B%5D) to reproduce bug.

Request Payload

<img width="612" alt="Screen Shot 2021-07-13 at 9 19 06 PM" src="https://user-images.githubusercontent.com/13460330/125560592-9e2a0670-606c-485a-a102-7e085c72f225.png">

## Expected behavior

No negative time bin values. 

## How to reproduce

1. Navigate to new funnels time conversion page. Make sure to turn on this FF: `4535-funnel-bar-viz`
2. Add a few identical actions/events
3. Open up network requests to see the response to `api/funnels`

## Environment

- [X] PostHog Cloud
- [ ] self-hosted PostHog, version/commit: _please provide_

**Comment by liyiy** [comment]
This is a graph that had those negative time values

<img width="979" alt="Screen Shot 2021-07-15 at 3 35 34 PM" src="https://user-images.githubusercontent.com/25164963/125847970-c057d3bb-89ac-426f-9ab0-b1d83a754408.png">

**Comment by neilkakkar** [comment]
Very interesting: Not an issue with time to convert, but the underlying time averages. And it turns out, this happens sporadically: sometimes, the time conversion values are borked, (and in your unfortunate case, cached), so the graph appears like this^.

I tried clearing the cache, and making the request again, and it worked fine.

Sigh, now to figure out *why* event duplicates are flakey O.o

**Comment by neilkakkar** [comment]
Partially because of: https://github.com/ClickHouse/ClickHouse/issues/26580 . And from what my experiments tell me, only happens when dealing with duplicate events. If the steps are not both `$pageview`, never happens. If the steps are both `$pageview`, happens _sometimes_.
