### ISSUE TITLE
Standardize filters on Sessions to be more aligned with elsewhere in the app

### ISSUE THREAD

**Issue by samwinslow** [PostHog/posthog#5121]
## Is your feature request related to a problem?

The sessions filter only allows you to group filter criteria by AND.

## Describe the solution you'd like

We should support OR.

## Describe alternatives you've considered

Telling users to create a cohort with the OR criteria and filtering based on that.

**Comment by liyiy** [comment]
relevant #5035

**Comment by samwinslow** [comment]
Agreed @liyiy that's definitely relevant — I think best approach would be to (eventually) tackle that first and then bring in the newly implemented property filters to replace what we have on Sessions. It's pretty inconsistent right now.

**Comment by samwinslow** [comment]
Closing as Sessions page is to be deprecated
