### ISSUE TITLE
Bug: Identifying incorrect users in trends

### ISSUE THREAD

**Issue by joethreepwood** [PostHog/posthog#5122]
## Bug description

Stumbled across this in an attempt to identify and research which users are using which data warehouse plug-ins. 

I started with [this chart](https://app.posthog.com/insights?insight=TRENDS&events=%5B%7B%22id%22%3A%22plugin%20enabled%22%2C%22math%22%3Anull%2C%22name%22%3A%22plugin%20enabled%22%2C%22type%22%3A%22events%22%2C%22order%22%3A0%2C%22properties%22%3A%5B%5D%2C%22math_property%22%3Anull%7D%5D&interval=day&breakdown=plugin_name&date_from=all&breakdown_type=event&funnel_window_days=14&filter_test_accounts=true&compare=false&properties=%5B%5D&display=ActionsPie) simply:: Plugin enabled total count broken down by name, displayed as a pie chart. 

When I clicked through to the size of a segment to inspect the users, I started seeing odd numbers. Then I realised that no matter which segment I clicked on, I was seeing the same 18 users identified repeatedly. 

Discussed with @neilkakkar who created [an alternate chart ](https://app.posthog.com/insights?insight=TRENDS&events=%5B%7B%22id%22%3A%22plugin%20enabled%22%2C%22math%22%3A%22dau%22%2C%22name%22%3A%22plugin%20enabled%22%2C%22type%22%3A%22events%22%2C%22order%22%3A0%2C%22properties%22%3A%5B%5D%7D%5D&interval=day&breakdown=plugin_name&date_from=all&breakdown_type=event&funnel_window_days=14&filter_test_accounts=true&compare=false&properties=%5B%5D&display=ActionsPie&actions=%5B%5D&new_entity=%5B%5D) to investigate the data. I clicked through to the segments and saw the same 18 users identified, over and over again. 

## Expected behavior

I expected to see a pie chart breaking down plugin use by name, then to be able to click through to a segment and inspect the correct users for that plugin. 

## How to reproduce

1. Visit one of the charts linked above
2. Click a segment to inspect users
3. Click another segment after

## Environment

- [ ] PostHog Cloud
- [x] self-hosted PostHog, version/commit: _please provide_

## Additional context

I won't share a screenshot here as it includes personal information, but have supplied them to @neilkakkar (who was kind enough to help) and can share on Slack if needed.

**Comment by joethreepwood** [comment]
May be worth adding: I had this bug in Brave, on Mac. I then retested it in Chrome, on Mac, after logging out and in again. Same results.

**Comment by paolodamico** [comment]
This was originally assigned to Core Experience but the scope seems quite related to Core Analytics, @liyiy are you okay picking this up? Looks like you assigned yourself, but feel free to tag the secondary on call too.

**Comment by liyiy** [comment]
I actually just took another look at this and the users seem to be different now! Looks like it might've been resolved by something else, happy to close this unless you spot something obviously wrong still
