### ISSUE TITLE
Bug: Inspect users tooltip not working correct

### ISSUE THREAD

**Issue by joethreepwood** [PostHog/posthog#5124]
## Bug description

Using [this chart from the plugins dashboard](https://app.posthog.com/insights?insight=TRENDS&events=%5B%7B%22id%22%3A%22plugin%20enabled%22%2C%22math%22%3Anull%2C%22name%22%3A%22plugin%20enabled%22%2C%22type%22%3A%22events%22%2C%22order%22%3A0%2C%22properties%22%3A%5B%5D%2C%22math_property%22%3Anull%7D%5D&display=ActionsBarValue&interval=day&breakdown=plugin_name&date_from=all&properties=%5B%7B%22key%22%3A%22realm%22%2C%22type%22%3A%22person%22%2C%22value%22%3A%5B%22cloud%22%5D%2C%22operator%22%3A%22exact%22%7D%5D&breakdown_type=event&funnel_window_days=14&filter_test_accounts=true&compare=false#fromItem=147913&fromItemName=Cloud%20-%20Plugins%20enabled&fromDashboard=1865), I wanted to start drilling down to inspect users of each plugin. 

However, the hover tool-tip began to work unreliably. Sometimes I would click to inspect users near the bottom of the chart (e.g. Hubspot) and nothing would happen. Double clicking would end up highlighting the 'For readability, not all breakdown values are displayed') text. 

Others, higher on the chart, (e.g. GeoIP) work as expected, but only if I click at the right edge of the bar. Clicking at the left end of the bar, does nothing. 

Sometimes, I would click on a bar (e.g. property flattener) at the left edge and get no result. I'd click it in the middle and get the correct result. And I'd click it on the right edge and get the results for another element (e.g. Event Sequence Timer Plugin). 

## Expected behavior

Click on each bar, anywhere on the bar, and get the relevant pop-up to inspect users in that group. 

## How to reproduce

1. Visit a chart such as the link above
2. Click to inspect users on a bar (works most reliably on elements near the bottom of a long chart)
3. Click again, somewhere else on the bar

## Environment

- [ ] PostHog Cloud
- [x] self-hosted PostHog, version/commit: _please provide_

## Additional context

Happened in Brave, on Mac. Reproducible in Chrome.

**Comment by paolodamico** [comment]
I believe this has been addressed recently, can you confirm @joethreepwood ?

**Comment by joethreepwood** [comment]
Nope, still affecting me. Captured a quick video of it. Obviously it's not capturing the clicks very clearly, but assume I am just constantly clicking. 

https://drive.google.com/file/d/18OAQaDJg3EhPJvcCqz9jTiwSJTQvPuv9/view?usp=sharing

**Comment by paolodamico** [comment]
Indeed this is still quite problematic but we now have #7370 to track this.

**Comment by paolodamico** [comment]
I believe the new tooltips (@alexkim205) fixes this, can you confirm @joethreepwood ?

**Comment by joethreepwood** [comment]
Yep, solved! <3 Thanks
