### ISSUE TITLE
Support graphing the difference between conversion steps of a funnel via a line graph

### ISSUE THREAD

**Issue by samwinslow** [PostHog/posthog#5125]
## Is your feature request related to a problem?

A user is asking about graphing the difference from one funnel step to the next, most likely as a line graph.

<img width="372" alt="839d2416943d45be89441a42a673a4f0-Captura-de-Tela-2021-07-09-às-14 15 17 (2)" src="https://user-images.githubusercontent.com/4645779/125620502-e595be9a-0280-4dab-ac70-c9d87dff3e02.png">

Presumably the advantage of this is to identify very highly negative values (dropoffs) as "problem" steps of the funnel, but I am possibly not interpreting the use case correctly.

**Comment by cheesepaulo** [comment]
Sorry, I wasn't very clear on my request.

- It would be really nice to get to see the dropoff list for each step ( like the stable version ( with link at '34 dropped off' )) 
_The stable versions has this feature but is limited to show only the 100 first events_
 
 With this information I can activate the CX team and catch those users who got lost along the steps and recover them.
