### ISSUE TITLE
Visualization Change - Time Bars in Insights

### ISSUE THREAD

**Issue by clarkus** [PostHog/posthog#5130]
## Is your feature request related to a problem?

When using bar visualization types for insights, the default layout is a stacked bar. As the number of distinct series increases, or as the delta between series values increases, it becomes increasingly difficult to compare series visually by area. 

<img width="231" alt="Screen Shot 2021-07-14 at 8 23 20 AM" src="https://user-images.githubusercontent.com/254612/125648311-b5cc086f-a141-4ee3-b912-a9937c0513b7.png">

## Describe the solution you'd like

Change the Bar visualization from a vertical stacked bar to a grouping of bars for each point on the axis. This matches the current funnels visualization work really well. See https://github.com/PostHog/posthog/issues/4535# for more context. 

## Describe alternatives you've considered

The current alternative is a stacked bar. We could also consider small multiples, but given the layout of the chart and the data we're visualizing, this seems like the most straightforward solution.

**Comment by macobo** [comment]
Related https://github.com/PostHog/posthog/issues/4654

**Comment by clarkus** [comment]
Related and possibly encompassing this issue: https://github.com/PostHog/posthog/issues/4654

**Comment by clarkus** [comment]
I think this can actually be closed in favor of https://github.com/PostHog/posthog/issues/4654
