### ISSUE TITLE
Funnels empty state: Make copy more friendly

### ISSUE THREAD

**Issue by samwinslow** [PostHog/posthog#5139]
IMO, the perceived tone of voice for this copy is aggressive. Additionally, the red text suggests an error, when it's really just the default state before adding another step. This could've been a PR but I can't think of how to reword it right now.

<img width="574" alt="Screen Shot 2021-07-14 at 6 13 06 PM" src="https://user-images.githubusercontent.com/4645779/125699909-2cce56c7-47c1-4e44-9c8a-b45be668a7a8.png">

**Comment by paolodamico** [comment]
Will go ahead and close this as the new empty state is already implemented in #5138
