### ISSUE TITLE
Clicking on a datapoint in /trends shows people for an entire day

### ISSUE THREAD

**Issue by Tmunayyer** [PostHog/posthog#514]
**Describe the bug**
On the /trends tab, when minutes or hours are selected as the interval, the people shown for a given datapoint are still for an entire day.

**To Reproduce**
1. go to /trends
2. set an interval filter to hourly, set the date range to today
3. click on a data point

**Expected behavior**
It should only show people who are responsible for the events firing in that hour

**Additional context**
This is a followup issue from PR #504. @timgl mentioned that PR is growing a bit so Im recording the issue here and will start a new branch to wrap it up.

Im fairly certain the problem here is that the request to `/api/actions/people` is at the day level and its not accounting for the granularity of the hour or minute. Changes on the front end would be to include the timestamp on the date_from date_to parameters. On the backend I believe the data just needs to be filtered one more time to exclude data that isn't within the range.

**Comment by EDsCODE** [comment]
looks like #527 closed this!
