### ISSUE TITLE
Funnels time conversion new all steps api returns null time bins

### ISSUE THREAD

**Issue by alexkim205** [PostHog/posthog#5143]
## Bug description

I'm trying out the new time to convert API deployed with this PR #5110, but I'm getting back null time bins when I don't pass in the `funnel_from_step` and `funnel_to_step` parameters. This happens inconsistently, so I captured the exact request I sent in this [gist](https://gist.github.com/alexkim205/aa9d5eb276efdb1bc50b724e46d3d242).

CC @Twixes 

```
{"result":[[null,0],[null,0],[null,0],[null,0]]}
```

## Expected behavior

Time bins aren't null

## How to reproduce

You can send a curl request that looks like the gist above, or checkout my branch in this PR #5142 to visually confirm.

<img width="793" alt="Screen Shot 2021-07-14 at 7 10 39 PM" src="https://user-images.githubusercontent.com/13460330/125717378-abf5c5bc-ba86-4aff-b406-9889a26003ed.png">

## Environment

- [ ] PostHog Cloud
- [ ] self-hosted PostHog, version/commit: _please provide_

**Comment by EDsCODE** [comment]
What do you mean inconsistent? Also, are you seeing any errors in logs since you're running this locally?
