### ISSUE TITLE
Move `merge_people` code to under plugin server

### ISSUE THREAD

**Issue by macobo** [PostHog/posthog#5145]
## Is your feature request related to a problem?

/api/person/merge currently performs a merge of two people. This logic is duplicated between app and plugin-server, badly.

## Describe the solution you'd like

Avoid duplicating, send a message to plugin-server

## Describe alternatives you've considered

Duplicating tricky and race-condition-heavy logic.

## Additional context

cc @yakkomajuri this is worth adding to team extensibility backlog - pretty sure this will cause bad correctness issues.

**Comment by macobo** [comment]
Adding this as a bug - this can lead to duplicated person_distinct_ids in clickhouse as work in `Person.merge_people` does not update clickhouse `person_distinct_ids` properly.

**Comment by macobo** [comment]
@paolodamico @marcushyett-ph When I was looking at the server logs it seemed like this endpoint was called 2x in 3 weeks. Perhaps worth temporarily removing the feature instead?

**Comment by marcushyett-ph** [comment]
Do you know who called it? Was it someone internal to PostHog? If so - probably yes - if not lets speak to the user first if we can.

**Comment by macobo** [comment]
Here's the action in posthog: https://app.posthog.com/action/9005

Seems to be much more than what I saw from logs. I think worth fixing this instead asap!

**Comment by Twixes** [comment]
Agreed that this logic definitely should not be duplicated. What is the blocker preventing us from just removing that endpoint right away?

**Comment by yakkomajuri** [comment]
I believe the blocker here was me being on vacation :D

I take it we'd want a call to that endpoint to notify the plugin server (via something like Redis) and merge the people there?
