### ISSUE TITLE
Funnel persons table not showing correct data

### ISSUE THREAD

**Issue by samwinslow** [PostHog/posthog#5161]
## Bug description

A valued EE user has pointed out that the funnel persons table seems to be showing inaccurate data. Missing persons or showing them as not having completed steps.

With no filter applied, see user `514eede4` in the funnel (and other users):

<img width="1147" alt="Screen Shot 2021-07-16 at 1 48 45 AM" src="https://user-images.githubusercontent.com/4645779/125899089-8f01d355-3eb3-4c88-b546-75b41478e7db.png">

Filtering to user `2cc6bfea` (who should be in the funnel per their event activity) — no results, table shows 1 random entry for user `514eede4` as having not completed the steps:

<img width="1275" alt="Screen Shot 2021-07-16 at 1 48 23 AM" src="https://user-images.githubusercontent.com/4645779/125898977-8ea1b6cc-a3e6-4a09-b09e-95c269a44a05.png">

Removing the filter and adding it again — more results, all showing not completed:

<img width="1240" alt="Screen Shot 2021-07-16 at 1 56 27 AM" src="https://user-images.githubusercontent.com/4645779/125899225-29f22de5-da4b-4ae0-bf6b-3bfcf3d0d906.png">

Could it be some weirdness with request caching or the funnel persons query?

## How to reproduce

1. Add some filters on user ID (ask me if you want to get on the user's instance and filter for `2cc6bfea`)
2. Notice missing data / visible data with zeros

## Environment

Self-hosted Clickhouse, PH 1.26.0

**Comment by samwinslow** [comment]
@EDsCODE would this have anything to do with person_distinct_ids?

**Comment by EDsCODE** [comment]
1. I think there is some caching issue happening so those inaccurate results that are popping up happen somehow when the funnel data returned is empty
2. I tried the exact funnel on their instance and it does seem to work with all the correct data showing up

**Comment by samwinslow** [comment]
One more user reporting a similar bug. I think this might be a case of stale data persisting in the Redux store.

**Comment by paolodamico** [comment]
@samwinslow could you add more context on the Redux stale caching you noticed?

**Comment by paolodamico** [comment]
Thanks for picking this up @Twixes! I'll move this to your board

**Comment by macobo** [comment]
cc @Twixes is this in progress or free to pick up?

**Comment by Twixes** [comment]
Sorry, I didn't notice this notification before! Wasn't in progress at the time, but when I saw this in emails I gave it a quick go. Since
1. We've moved to a people modal instead of a table since this issue was filed
2. This seems to be inconsistencies caused by the funnel itself and its people being calculated and cached at slightly different times.

I added manual people refresh capabilities in #5537. It's not super _smart_, but it does offer users a simple lever over stale data.

**Comment by Twixes** [comment]
These inconsistencies shouldn't be a real problem anymore after #5560.
