### ISSUE TITLE
Sprint 1.27.0 4/2 - Jul 19 to Jul 30 (Funnels #3)

### ISSUE THREAD

**Issue by EDsCODE** [PostHog/posthog#5168]
Last sprint: #4968

**Comment by EDsCODE** [comment]
### Core Analytics

Michael off

**Priority:**

- better people pagination (if we drop users in our 100 count the pagination doesn’t work) (#5178)
- Median time (#5203)
- Funnel trend breakdown (#5232)
- Add more flexibility to the conversion time window. right now it’s just days (#5329)
- Bug squashing
- Performance Optimization:
     - person_id + properties on events table (#5167)
     - Property denormalization (#5166)

**Secondary priority:**

- count repeated funnel attempts (don’t dedup based on person)
- Where did users go on a dropoff? (paths) (Vendasta power user) (https://github.com/PostHog/posthog/issues/4806)
- funnel sessions? (https://github.com/PostHog/posthog/issues/5173)
- holding property constant

**Comment by mariusandra** [comment]
### Core Experience

- Marius
  - only 1 week, then off
  - high fidelity filters (event, property and other dropdowns) https://github.com/PostHog/posthog/issues/4802 https://github.com/PostHog/posthog/pull/5098 
  - logic tests https://github.com/PostHog/posthog/pull/4689
  - bugs and quality improvements across the board; code reviews and unblocking others
- Paolo: 
  - improvements to funnels, finding the edge cases, UX bugs, etc
  - work with Marcus to figure out what to work on next
  - https://github.com/PostHog/posthog/issues/4821
- Chris: 
  - continue with the funnels work https://github.com/PostHog/posthog/issues/4535 & composition  https://github.com/PostHog/posthog/issues/4979 ; few improvements for visualisations, chart colors https://github.com/PostHog/posthog/issues/4076, consolidating changing chart options, and whatever we will do next
- Alex: 
  - time conversion analysis view https://github.com/PostHog/posthog/issues/4855
- Li: 
  - saved reports https://github.com/PostHog/posthog/issues/3408 
  - persons modal session recording stuff
- Sam: 
  - implement the design from Chris for breakdowns
  - implement funnels info table (& csv) https://github.com/PostHog/posthog/issues/4979#issuecomment-879430034
  - participate in user testing and get hard data

**Comment by fuziontech** [comment]
# Deployment UND Infrastructure 

@tiina303 , @macobo , @fuziontech 

## Priorities
- Helm charts and Marketplaces (GCP & DO)
- Clickhouse Performance Collaboration with team `Core-Analytics`
- Infra cleanup and maintenance - Keep the lights on

#### Clickhouse deployments for everyone

- [ ] P0: charts-clickhouse readme Docs for standing up helm chart on various platforms (Tiina, target: 19.July)
- [ ] P0: Email blast about Clickhouse self-hosted deployments being available (collaborating with Charles, Tim? ; target: 21. July)
- [ ] P0: Support customers using Posthog w Clickhouse
- [ ] P0: GCP marketplace 1-click deploy (James, blocked on Google atm)
- [ ] P1: DigitalOcean deployment follow-ups: dynamic versioning, tracker for 1-click installs, migrations allocation problem (Tiina)
- [ ] P1: Clickhouse password to not be hardcoded and public (Tiina)
- [ ] P1: Digital-Ocean post-install docs + config changes (Tiina)
- [ ] P2: Update posthog.com Self-Host section (Tiina, collaborating with Phil)

#### Performance for Core Analytics

- [ ] P0: Perceived slowness: Make person and person_distinct_id deletion efficient (Karl)
- [ ] P0: Cloud performance improvements (James)
- [ ] P2: Experiment with extracting common props to materialized columns, do measurements (Karl)
- [ ] P2: Experiment with distinct_ids on persons table (Karl)

#### Misc

- [ ] P0: Migrate Kafka from Heroku to AWS (James)
- [ ] P0: AWS costs analysis (James)
- [ ] P1: "Too many connections" clickhouse pool error (Karl)
- [ ] P1: SOC2 Requirements
- [ ] P2: Set up NAT Gateway for posthog cloud (James)

More details and more on our [board](https://github.com/orgs/PostHog/projects/10)!
![image](https://user-images.githubusercontent.com/391319/125963395-af4ba050-6762-48d6-a5dd-6dc8f7ba2c20.png)

**Comment by yakkomajuri** [comment]
# Extensibility

## This sprint

I'm off the whole sprint. From an Engineering perspective (excluding all my non-eng responsibilities), this means:

- Someone needs to keep an eye on the plugin server (and other extensibility-related things)
- Someone needs to do the release (if we do one)

## Next sprint

I'll come back after the next planning session, so here's the plan:
- I'm support hero the first week back
- I'll work on "export from the beginning" and import plugins the week after.

**Comment by Twixes** [comment]
Sprint over.
