### ISSUE TITLE
Filter for people with session recordings on persons modal

### ISSUE THREAD

**Issue by liyiy** [PostHog/posthog#5173]
## Is your feature request related to a problem?

*Please describe.*

Users would like to see why persons are churning, etc. when looking at the persons modal for an insight. Allowing them to quickly filter for persons who have valid session recordings or only look at persons with session recordings could help them figure things out easier.

This will involve backend filtering for sessions with recordings for a specific person at that event and time, and then joining that with the person, which might make the persons query even slower? That is my understanding of how to make it work, but perhaps we have a better way I'm unaware of :D 

BUT before that even, we should consider this in relation to #4884 first ! !

**Comment by clarkus** [comment]
This is the most recent design for the persons modal. The filters available are a keyword search that matches against names, email addresses, and IDs. Basically if you know a portion of the string you're looking for, this will help you find it that way. Secondarily there is a filter that reduces the set to only those entries with corresponding recordings. 

<img width="684" alt="Screen Shot 2021-07-16 at 11 13 35 AM" src="https://user-images.githubusercontent.com/254612/125991309-97284c8d-0c1a-4ae3-b257-ceb26193976f.png">

**Comment by paolodamico** [comment]
I think this is independent of #4884 as the goal here is to take the user straight to a relevant session recording (session player page), so whatever we do with the sessions page won't affect this.

From what you said @liyiy, it sounds like we need some help from Core Analytics Team first, so transferring this issue to them. CC @EDsCODE

**Comment by macobo** [comment]
Thanks for writing this up!

Some considerations/questions:
- @clarkus where would the show details lead?
- How the back button should behave if user navigates off the page and back again is worth considering and writing down - whatever we do that's something users are gonna do a _lot_ and determine the usefulness of this feature.
- For this to work in e.g. funnels, we need to know "date" + "person" before filtering the session recording. This is slightly tricky in funnels:
  - If showing modal of dropped off, probably want to show recordings of step N-1 that they completed successfully!
  - If user completed steps multiple times, probably want to fetch the first date.
- Technically the joining is not done in the same query but the same way recordings & sessions are joined - recordings are fetched second.

> I think this is independent of #4884 as the goal here is to take the user straight to a relevant session recording (session player page), so whatever we do with the sessions page won't affect this.

Not sure that's the case (structural changes will affect this in large ways) but it's not necessarily a blocker. However things like session page being one-date only can affect this feature in very practical ways.

**Comment by clarkus** [comment]
>     * @clarkus where would the show details lead?

The intent is to show the corresponding session and recording (if it exists). "View details" might not be the best label for the button here. Maybe "view session details" is more descriptive of the target?

>     * How the back button should behave if user navigates off the page and back again is worth considering and writing down - whatever we do that's something users are gonna do a _lot_ and determine the usefulness of this feature.

Given that there's a lot of analysis on each view, maybe we should consider opening in a new context. This is shown in a modal, so persisting that when we navigate back could feel cumbersome to users. This is a great point... I will spend more time thinking about ways to improve this. 

> However things like session page being one-date only can affect this feature in very practical ways.

Agree... any reason we're limited to a single date there?

**Comment by macobo** [comment]
> Agree... any reason we're limited to a single date there?

No real product reason, but two pieces are missing:
- Product/Design re whether/what date filter component to show
- Performance-related work which is slightly tricky, see https://github.com/PostHog/posthog/issues/3471 for more context

Issue: https://github.com/PostHog/posthog/issues/3471

**Comment by liyiy** [comment]
Currently blocked by #5447

**Comment by macobo** [comment]
I don't think it is, the joining here would work in a different way :thinking: 

Also just noticed @clarkus' new design does not include a link to sessions page for _all_ sessions anymore. Was that intentional?

Since this is a two-teamer (:disappointed:) and the communication barrier here is real, how about next sprint:

1. Building out the UI under a flag (core-experience)
2. Building out the backend support after that (core-analytics), removing the flag

**Comment by clarkus** [comment]
> Also just noticed @clarkus' new design does not include a link to sessions page for all sessions anymore. Was that intentional?

Unintentionally removed.

**Comment by pauldambra** [comment]
you can do this
