### ISSUE TITLE
Avg time to convert showing as 0 for funnels

### ISSUE THREAD

**Issue by kpthatsme** [PostHog/posthog#5199]
## Bug description
Looks like time to convert is broken. It's showing 0s for all funnels I'm creating.

## Expected behavior
The avg time should be a value between 0 and the conversion window specific for the funnel.

## How to reproduce

1. Create a funnel and view the conversion over time ([example](https://app.posthog.com/insights?insight=FUNNELS&events=%5B%7B%22id%22%3A%22%24pageview%22%2C%22name%22%3A%22%24pageview%22%2C%22type%22%3A%22events%22%2C%22order%22%3A0%7D%2C%7B%22id%22%3A%22%24pageview%22%2C%22name%22%3A%22%24pageview%22%2C%22type%22%3A%22events%22%2C%22order%22%3A1%7D%5D&actions=%5B%5D&interval=week&date_from=yStart&funnel_viz_type=trends&filter_test_accounts=true&display=ActionsLineGraph&new_entity=%5B%5D))
2. View the Avg time to convert - observe it's 0.
3.

## Environment

- [ ] PostHog Cloud
- [ ] self-hosted PostHog, version/commit: _please provide_

**Comment by alexkim205** [comment]
This might be fixed with conversion metric logic changes in #5142. I'll make a note to test it once it's deployed.

**Comment by marcushyett-ph** [comment]
We should fix this as part of our funnels quality sprint

**Comment by alexkim205** [comment]
This one's already been fixed during our most recent funnels push.
