### ISSUE TITLE
Property breakdown returning unexpected results

### ISSUE THREAD

**Issue by kpthatsme** [PostHog/posthog#5200]
## Bug description

I am doing a property filter breakdown and I expect to see some values broken down for UTM source, however I'm seeing no results returned.

## Expected behavior

I expect the breakdown based on the same events and properties to produce the values that I can query in the chart.

## How to reproduce
1) [Pageviews broken by specific filters](https://app.posthog.com/insights?insight=TRENDS&interval=day&display=ActionsLineGraph&actions=%5B%5D&events=%5B%7B%22id%22%3A%22%24pageview%22%2C%22name%22%3A%22%24pageview%22%2C%22type%22%3A%22events%22%2C%22order%22%3A0%2C%22properties%22%3A%5B%7B%22key%22%3A%22utm_source%22%2C%22value%22%3A%22is_set%22%2C%22operator%22%3A%22is_set%22%2C%22type%22%3A%22event%22%7D%5D%2C%22math%22%3A%22dau%22%7D%2C%7B%22id%22%3A%22%24pageview%22%2C%22name%22%3A%22%24pageview%22%2C%22type%22%3A%22events%22%2C%22order%22%3A1%2C%22properties%22%3A%5B%7B%22key%22%3A%22utm_source%22%2C%22value%22%3A%22is_not_set%22%2C%22operator%22%3A%22is_not_set%22%2C%22type%22%3A%22event%22%7D%5D%2C%22math%22%3A%22dau%22%7D%2C%7B%22id%22%3A%22%24pageview%22%2C%22name%22%3A%22%24pageview%22%2C%22type%22%3A%22events%22%2C%22order%22%3A2%2C%22properties%22%3A%5B%7B%22key%22%3A%22utm_source%22%2C%22value%22%3A%5B%22redditads%22%5D%2C%22operator%22%3A%22exact%22%2C%22type%22%3A%22event%22%7D%5D%2C%22math%22%3A%22dau%22%7D%5D&properties=%5B%5D&filter_test_accounts=true&new_entity=%5B%5D)
2) Now [this chart](https://app.posthog.com/insights?insight=TRENDS&interval=day&display=ActionsLineGraph&actions=%5B%5D&events=%5B%7B%22id%22%3A%22%24pageview%22%2C%22name%22%3A%22%24pageview%22%2C%22type%22%3A%22events%22%2C%22order%22%3A0%2C%22properties%22%3A%5B%7B%22key%22%3A%22utm_source%22%2C%22value%22%3A%22is_set%22%2C%22operator%22%3A%22is_set%22%2C%22type%22%3A%22event%22%7D%5D%2C%22math%22%3A%22dau%22%7D%2C%7B%22id%22%3A%22%24pageview%22%2C%22name%22%3A%22%24pageview%22%2C%22type%22%3A%22events%22%2C%22order%22%3A1%2C%22properties%22%3A%5B%7B%22key%22%3A%22utm_source%22%2C%22value%22%3A%22is_not_set%22%2C%22operator%22%3A%22is_not_set%22%2C%22type%22%3A%22event%22%7D%5D%2C%22math%22%3A%22dau%22%7D%5D&properties=%5B%5D&filter_test_accounts=true&new_entity=%5B%5D&breakdown=utm_source&breakdown_type=person) with the same events as above, but broken down by the `utm_source` event property indicates that there are no values for this property.
## Environment

- [ ] PostHog Cloud
- [ ] self-hosted PostHog, version/commit: _please provide_

**Comment by EDsCODE** [comment]
I think this is working now?

**Comment by kpthatsme** [comment]
Yessir - that seems to be the case. Will close.
