### ISSUE TITLE
Allow custom naming in tables / graph series

### ISSUE THREAD

**Issue by joesaunderson** [PostHog/posthog#5207]
## Is your feature request related to a problem?

In trends, when I create a graph / table, PostHog tries to be clever and come up with names for me.

I.e 'Event name (Active feature flags = some-feature)'

This can be confusing, as there are often some weirdities in these names I.e the symbols for contains / does not contain are so similar, and when in the dashboard, users ask me what they mean.

## Describe the solution you'd like

By default, use the name PostHog suggests, but allow the user to rename the series as they require.

## Describe alternatives you've considered

Don't allow renaming and stick with the name PostHog suggests?

## Additional context

n/a

#### *Thank you* for your feature request – we love each and every one!

**Comment by paolodamico** [comment]
Designs originally from https://github.com/PostHog/posthog/issues/1148#issuecomment-888580010

![Edit Insight](https://user-images.githubusercontent.com/254612/127387112-71afa1bb-77da-4aaf-b24d-99f36bfe4935.png)
![Rename Query Step](https://user-images.githubusercontent.com/254612/127387114-5365ff23-ae62-4e83-b647-7fcf37df58b6.png)

**Comment by charlescook-ph** [comment]
Another example of why this would be useful - in this graph I'm trying to track conversions based on which ad campaign the user visited from, but the series names mean I need to remember what A-F stand for. 

<img width="278" alt="Screenshot 2021-09-17 at 10 50 45" src="https://user-images.githubusercontent.com/70321811/133765777-236ec4c8-7212-49c5-881d-124a8cf54f3f.png">
