### ISSUE TITLE
Support / document Clickhouse deployment without K8’s

### ISSUE THREAD

**Issue by joesaunderson** [PostHog/posthog#5208]
## Is your feature request related to a problem?

Extension of this thread: https://posthogusers.slack.com/archives/CT7HXDEG3/p1626382201047700

We are using PostHog, self hosted, and converted your CloudFormation template to Terraform, having services in RDS, ECS and others.

## Describe the solution you'd like

We want to move to the self hosted Clickhouse option, however we don't want to migrate the whole stack to EKS as per the helm charts.

We'd like the option to host only Clickhouse somewhere, and integrate with our existing stack (via env vars maybe?).

## Describe alternatives you've considered

Stick with Postgres

## Additional context

https://posthogusers.slack.com/archives/CT7HXDEG3/p1626382201047700

#### *Thank you* for your feature request – we love each and every one!

**Comment by tiina303** [comment]
This is a great idea, however sadly we currently don't have any time to work on it. That said the code is open source so you're welcome to try to give it a go.
