### ISSUE TITLE
Allow for non-insight panels in dashboard

### ISSUE THREAD

**Issue by joesaunderson** [PostHog/posthog#5209]
## Is your feature request related to a problem?

We have built dashboards for various areas of our product teams goals and milestones.

Sometimes, it's not obvious what sections of the dashboard are doing.

## Describe the solution you'd like

It would be great to add text panels in editor mode, that allow for titles / subtitles, paragraphs of text or even images to be added.

This would enrich the dashboard even further so it makes sense to everyone without explanation.

## Describe alternatives you've considered

Field questions from everyone who visits our dashboard on what things mean.

## Additional context

N/A

#### *Thank you* for your feature request – we love each and every one!

**Comment by paolodamico** [comment]
This is something we're considering in dashboard taxonomy, but haven't been able to reprioritise. Another collaboration feature that will be quite useful for our focus customers too.
