### ISSUE TITLE
Funnel Time Distribution fails to load

### ISSUE THREAD

**Issue by marcushyett-ph** [PostHog/posthog#5210]
## Bug description

Time distributions for my funnel fail to load: https://app.posthog.com/insights?insight=FUNNELS&properties=%5B%5D&filter_test_accounts=true&interval=day&events=%5B%7B%22id%22%3A%22first%20team%20event%20ingested%22%2C%22name%22%3A%22first%20team%20event%20ingested%22%2C%22type%22%3A%22events%22%2C%22order%22%3A1%7D%2C%7B%22id%22%3A%22insight%20loaded%22%2C%22name%22%3A%22insight%20loaded%22%2C%22type%22%3A%22events%22%2C%22order%22%3A2%7D%5D&actions=%5B%7B%22id%22%3A2674%2C%22name%22%3A%22User%20Signed%20Up%20(Comprehensive)%22%2C%22type%22%3A%22actions%22%2C%22order%22%3A0%7D%2C%7B%22id%22%3A4912%2C%22name%22%3A%22Discovered%20Learning%22%2C%22type%22%3A%22actions%22%2C%22order%22%3A3%7D%5D&new_entity=%5B%5D&display=FunnelsTimeToConvert

## Expected behavior

I would expect to see a graph with distribution of time between steps

## How to reproduce

1. https://app.posthog.com/insights?insight=FUNNELS&properties=%5B%5D&filter_test_accounts=true&interval=day&events=%5B%7B%22id%22%3A%22first%20team%20event%20ingested%22%2C%22name%22%3A%22first%20team%20event%20ingested%22%2C%22type%22%3A%22events%22%2C%22order%22%3A1%7D%2C%7B%22id%22%3A%22insight%20loaded%22%2C%22name%22%3A%22insight%20loaded%22%2C%22type%22%3A%22events%22%2C%22order%22%3A2%7D%5D&actions=%5B%7B%22id%22%3A2674%2C%22name%22%3A%22User%20Signed%20Up%20(Comprehensive)%22%2C%22type%22%3A%22actions%22%2C%22order%22%3A0%7D%2C%7B%22id%22%3A4912%2C%22name%22%3A%22Discovered%20Learning%22%2C%22type%22%3A%22actions%22%2C%22order%22%3A3%7D%5D&new_entity=%5B%5D&display=FunnelsTimeToConvert
2. 

## Environment

- [x] PostHog Cloud

**Comment by liyiy** [comment]
Hey marcus! There were some updates merged and this chart should load properly now. (Though it is looking not so hot right now 😢 )

<img width="1258" alt="Screen Shot 2021-07-20 at 10 13 32 PM" src="https://user-images.githubusercontent.com/25164963/126419813-d588b2e6-0d8e-4f7b-976b-241dd445b426.png">

**Comment by macobo** [comment]
@liyiy @marcushyett-ph  can this be closed?

**Comment by mariusandra** [comment]
@macobo it still looks like this to me: 
![image](https://user-images.githubusercontent.com/53387/126471443-4c060903-3740-45aa-a92d-dc502295e14f.png)

Was it working for you?

**Comment by macobo** [comment]
Ah - didn't look deeply at the screenshot. I guess this transitioned from "X does not load" to "X is not visualized properly"

**Comment by mariusandra** [comment]
Yeah, I'd still keep the issue open to track the visual bug as well.

**Comment by mariusandra** [comment]
Tracking the visual bug here now: https://github.com/PostHog/posthog/issues/5249#issuecomment-884180568
