### ISSUE TITLE
Breakdown on funnel fails to load

### ISSUE THREAD

**Issue by marcushyett-ph** [PostHog/posthog#5211]
## Bug description

Tried to breakdown funnel by browser, country and a few other attributes none return any results, an example: https://app.posthog.com/insights?insight=FUNNELS&properties=%5B%5D&filter_test_accounts=true&interval=day&events=%5B%7B%22id%22%3A%22insight%20loaded%22%2C%22name%22%3A%22insight%20loaded%22%2C%22type%22%3A%22events%22%2C%22order%22%3A1%7D%5D&actions=%5B%7B%22id%22%3A2674%2C%22name%22%3A%22User%20Signed%20Up%20(Comprehensive)%22%2C%22type%22%3A%22actions%22%2C%22order%22%3A0%7D%2C%7B%22id%22%3A4912%2C%22name%22%3A%22Discovered%20Learning%22%2C%22type%22%3A%22actions%22%2C%22order%22%3A2%7D%5D&new_entity=%5B%5D&breakdown=%24geoip_country_name&breakdown_type=person&display=FunnelViz

## Expected behavior
Return a breakdown of the funnel based on this property

## How to reproduce

1. https://app.posthog.com/insights?insight=FUNNELS&properties=%5B%5D&filter_test_accounts=true&interval=day&events=%5B%7B%22id%22%3A%22insight%20loaded%22%2C%22name%22%3A%22insight%20loaded%22%2C%22type%22%3A%22events%22%2C%22order%22%3A1%7D%5D&actions=%5B%7B%22id%22%3A2674%2C%22name%22%3A%22User%20Signed%20Up%20(Comprehensive)%22%2C%22type%22%3A%22actions%22%2C%22order%22%3A0%7D%2C%7B%22id%22%3A4912%2C%22name%22%3A%22Discovered%20Learning%22%2C%22type%22%3A%22actions%22%2C%22order%22%3A2%7D%5D&new_entity=%5B%5D&breakdown=%24geoip_country_name&breakdown_type=person&display=FunnelViz

## Environment

- [x] PostHog Cloud
- [ ] self-hosted PostHog, version/commit: _please provide_

**Comment by marcushyett-ph** [comment]
I'm still getting this issue:
https://app.posthog.com/insights?events=%5B%7B%22id%22%3A%22first%20team%20event%20ingested%22%2C%22math%22%3Anull%2C%22name%22%3A%22first%20team%20event%20ingested%22%2C%22type%22%3A%22events%22%2C%22order%22%3A1%2C%22properties%22%3A%5B%5D%2C%22math_property%22%3Anull%7D%5D&actions=%5B%7B%22id%22%3A%222674%22%2C%22math%22%3Anull%2C%22name%22%3A%22User%20Signed%20Up%20(Comprehensive)%22%2C%22type%22%3A%22actions%22%2C%22order%22%3A0%2C%22properties%22%3A%5B%5D%2C%22math_property%22%3Anull%7D%2C%7B%22id%22%3A4912%2C%22math%22%3Anull%2C%22name%22%3A%22Discovered%20Learning%22%2C%22type%22%3A%22actions%22%2C%22order%22%3A2%2C%22properties%22%3A%5B%5D%2C%22math_property%22%3Anull%7D%5D&insight=FUNNELS&interval=day&filter_test_accounts=true&new_entity=%5B%5D&date_from=-7d&display=FunnelViz&breakdown=%24os&breakdown_type=person

<img width="880" alt="image" src="https://user-images.githubusercontent.com/85295485/126302937-84c94ef0-4823-4193-a214-d222548679cb.png">

There's no clear indication why it's failing either - doesn't look like an error state on the UI.

**Comment by mariusandra** [comment]
Same reported by Kunal here: https://github.com/PostHog/posthog/issues/5200

I tried disabling the new filter feature flag and still could not break down the results by a property. So it seems like a backend/query issue, as the `breakdown` and `breakdown_type` params seem to be set on the request. 🤔

@EDsCODE @neilkakkar any ideas?

**Comment by EDsCODE** [comment]
@marcushyett-ph for the specific filters and actions you're looking for, interestingly enough,[ there's no](https://metabase.posthog.net/question#eyJkYXRhc2V0X3F1ZXJ5Ijp7InR5cGUiOiJuYXRpdmUiLCJuYXRpdmUiOnsicXVlcnkiOiJTRUxFQ1QgdHJpbShCT1RIICdcIicgRlJPTSBKU09ORXh0cmFjdFJhdyhwcm9wZXJ0aWVzLCAnJG9zJykpIGFzIHZhbHVlLFxuICAgICAgICAgICAgICAgY291bnQoKikgYXMgY291bnRcbiAgICAgICAgICBGUk9NIGV2ZW50cyBlXG4gICAgICAgICBXSEVSRSB0ZWFtX2lkID0gMlxuICAgICAgICAgICBBTkQgKCgobWF0Y2goZWxlbWVudHNfY2hhaW4sICdidXR0b24uKj90eXBlPVwic3VibWl0XCIuKj8oWy1fYS16QS1aMC05XFxcXC5dKj8pPygkfDt8OihbXjteXFxcXHNdKig7fCR8XFxcXHMpKSknKSkgQU5EIEpTT05FeHRyYWN0U3RyaW5nKHByb3BlcnRpZXMsICckY3VycmVudF91cmwnKSBMSUtFICclL3ByZWZsaWdodCUnIEFORCBldmVudCA9ICckYXV0b2NhcHR1cmUnKSBPUiAoKG1hdGNoKGVsZW1lbnRzX2NoYWluLCAnYnV0dG9uLio_dHlwZT1cInN1Ym1pdFwiLio_KFstX2EtekEtWjAtOVxcXFwuXSo_KT8oJHw7fDooW147XlxcXFxzXSooO3wkfFxcXFxzKSkpJykpIEFORCBKU09ORXh0cmFjdFN0cmluZyhwcm9wZXJ0aWVzLCAnJGN1cnJlbnRfdXJsJykgTElLRSAnJS9zZXR1cF9hZG1pbiUnIEFORCBldmVudCA9ICckYXV0b2NhcHR1cmUnKSBPUiAoZXZlbnQgPSAndXNlciBzaWduZWQgdXAnKSlcbiAgICAgICAgICAgQU5EIHRpbWVzdGFtcCA-PSAnMjAyMS0wNy0xMyAwMDowMDowMCdcbiAgICAgICAgICAgQU5EIHRpbWVzdGFtcCA8PSAnMjAyMS0wNy0yMCAyMzo1OTo1OSdcbiAgICAgICAgICAgQU5EIGUuZGlzdGluY3RfaWQgSU4gKFxuICAgICAgICAgICAgICAgIFNFTEVDVCBkaXN0aW5jdF9pZFxuICAgICAgICAgICAgICAgICAgRlJPTSAoXG4gICAgICAgICAgICAgICAgICAgICAgICBTRUxFQ1QgcGVyc29uX2lkLFxuICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIGRpc3RpbmN0X2lkXG4gICAgICAgICAgICAgICAgICAgICAgICAgIEZST00gcGVyc29uX2Rpc3RpbmN0X2lkXG4gICAgICAgICAgICAgICAgICAgICAgICAgV0hFUkUgdGVhbV9pZCA9IDJcbiAgICAgICAgICAgICAgICAgICAgICAgICBHUk9VUCBCWSBwZXJzb25faWQsXG4gICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgZGlzdGluY3RfaWQsXG4gICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgdGVhbV9pZFxuICAgICAgICAgICAgICAgICAgICAgICAgSEFWSU5HIG1heChpc19kZWxldGVkKSA9IDBcbiAgICAgICAgICAgICAgICAgICAgICAgKVxuICAgICAgICAgICAgICAgICBXSEVSRSBwZXJzb25faWQgSU4gKFxuICAgICAgICAgICAgICAgICAgICAgICAgU0VMRUNUIGlkXG4gICAgICAgICAgICAgICAgICAgICAgICAgIEZST00gKFxuICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICBTRUxFQ1QgaWQsXG4gICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICBhcmdNYXgocHJvcGVydGllcywgcGVyc29uLl90aW1lc3RhbXApIGFzIHByb3BlcnRpZXMsXG4gICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICBtYXgoaXNfZGVsZXRlZCkgYXMgaXNfZGVsZXRlZFxuICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIEZST00gcGVyc29uXG4gICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICBXSEVSRSB0ZWFtX2lkID0gMlxuICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgR1JPVVAgQlkgaWRcbiAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgSEFWSU5HIGlzX2RlbGV0ZWQgPSAwXG4gICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgKVxuICAgICAgICAgICAgICAgICAgICAgICAgIFdIRVJFIDEgPSAxXG4gICAgICAgICAgICAgICAgICAgICAgICAgICBBTkQgTk9UICh0cmltKEJPVEggJ1wiJyBGUk9NIEpTT05FeHRyYWN0UmF3KHByb3BlcnRpZXMsICdlbWFpbCcpKSBMSUtFICclcG9zdGhvZy5jb20lJylcbiAgICAgICAgICAgICAgICAgICAgICAgKVxuICAgICAgICAgICAgICAgKVxuICAgICAgICAgICBBTkQgTk9UIGhhcyhbJzEyNy4wLjAuMTozMDAwJywgJzEyNy4wLjAuMTo1MDAwJywgJ2xvY2FsaG9zdDo1MDAwJywgJ2xvY2FsaG9zdDo4MDAwJ10sIHRyaW0oQk9USCAnXCInIEZST00gSlNPTkV4dHJhY3RSYXcoZS5wcm9wZXJ0aWVzLCAnJGhvc3QnKSkpXG4gICAgICAgICAgIEFORCBlLnRlYW1faWQgPSAyXG4gICAgICAgICAgIEFORCBOT1QgKHRyaW0oQk9USCAnXCInIEZST00gSlNPTkV4dHJhY3RSYXcoZS5wcm9wZXJ0aWVzLCAnZGlzdGluY3RfaWQnKSkgTElLRSAnJXBvc3Rob2cuY29tJScpXG4gICAgICAgICAgIEFORCBlLnRlYW1faWQgPSAyXG4gICAgICAgICAgIEFORCBKU09OSGFzKHByb3BlcnRpZXMsICckb3MnKVxuICAgICAgICAgICBHUk9VUCBCWSB2YWx1ZSIsInRlbXBsYXRlLXRhZ3MiOnt9fSwiZGF0YWJhc2UiOjJ9LCJkaXNwbGF5IjoidGFibGUiLCJ2aXN1YWxpemF0aW9uX3NldHRpbmdzIjp7fX0=) `User Signed Up (Comprehensive)` actions that have accompanying OS properties in the last 7 days. Going to try some other configurations 

Also, there is some UI flickering going on. I think any empty result is being cached but occasionally Ill get a result for 1 second and then it flips back to empty result

**Comment by marcushyett-ph** [comment]
Ah okay - it seems to be pretty hard to find an event or property which returns any results for a breakdown - is there any easy way to work out which ones are likely to return a breakdown?

Also yeah I see some weird UI issue where it sometimes says this:
<img width="850" alt="image" src="https://user-images.githubusercontent.com/85295485/126335960-c84e44e7-6b56-47a3-b7ce-239e0b2bd6a7.png">

And sometimes returns a graph.

I've only managed to get it to work for event property country so far.

**Comment by neilkakkar** [comment]
Think both of you faced this: https://sentry.io/organizations/posthog/issues/2522528189/?project=1899813&referrer=slack - definitely a backend bug. The real issue seems to be: Filtering out test / internal users (which does a cohort join, which _seems_ to be broken?). When I flipped that off, your breakdowns started working for me.

Can you please confirm the same? (i.e. switching off internal filtering made things work?)

![image](https://user-images.githubusercontent.com/7115141/126340934-5c440e4d-5452-4eab-9820-3cfaf4d4c07b.png)

**Comment by marcushyett-ph** [comment]
Yep that seems to make it better - but there's still an intermittent UI caching issue where I just keep getting this:
<img width="896" alt="image" src="https://user-images.githubusercontent.com/85295485/126341469-41e73cae-50c2-4302-832e-c2e07f05dafc.png">

Unless I refresh

**Comment by neilkakkar** [comment]
This was fixed in https://github.com/PostHog/posthog/pull/5225

But now, seems like there's something new happening with breakdown on actions, they're not working anymore, for any query O.o

**Comment by neilkakkar** [comment]
Huh, a bit more investigation reveals: Breakdown on Person properties is also what seems borked. If I breakdown on $browser with type `events`, it works fine, while breakdown on $browser with type `persons` returns NADA.

**Comment by EDsCODE** [comment]
@marcus [this type](https://app.posthog.com/insights?insight=FUNNELS&properties=%5B%5D&filter_test_accounts=true&events=%5B%7B%22id%22%3A%22insight%20loaded%22%2C%22name%22%3A%22insight%20loaded%22%2C%22type%22%3A%22events%22%2C%22order%22%3A1%7D%5D&actions=%5B%7B%22id%22%3A2674%2C%22name%22%3A%22User%20Signed%20Up%20(Comprehensive)%22%2C%22type%22%3A%22actions%22%2C%22order%22%3A0%7D%2C%7B%22id%22%3A4912%2C%22name%22%3A%22Discovered%20Learning%22%2C%22type%22%3A%22actions%22%2C%22order%22%3A2%7D%5D&funnel_viz_type=steps&display=FunnelViz&interval=day&breakdown=%24geoip_country_name&breakdown_type=person&new_entity=%5B%5D) of breakdown with test account filters is working now

**Comment by marcushyett-ph** [comment]
Awesome thanks @EDsCODE!
