### ISSUE TITLE
Funnel drop off user list title is confusing (/buggy?)

### ISSUE THREAD

**Issue by jamesefhawkins** [PostHog/posthog#5218]
## Bug description

1 - create a funnel
<img width="755" alt="Screenshot 2021-07-20 at 10 39 24" src="https://user-images.githubusercontent.com/47497682/126300179-651cbae7-8bf4-4968-be0d-689f3625876d.png">

2 - click '6 (54.55%)' (ie the *drop off*)

<img width="631" alt="Screenshot 2021-07-20 at 10 40 52" src="https://user-images.githubusercontent.com/47497682/126300292-dac77c30-08eb-4e2f-8ad7-986fc629be58.png">

3. Title is "Persons who completed Step #-2 - "Discovered Learning".

Yes, they completed it but this implies they succeeded.

## Expected behavior

Title to say "Persons who dropped off at Step #-2 - "Discovered Learning".

**Comment by neilkakkar** [comment]
To add: On the backend, "-2" means dropoff, "2" means success.

I think the step copy here should remove the minus as well,  so, "Step#2"

**Comment by paolodamico** [comment]
Thanks for reporting @jamesefhawkins and the extra context @neilkakkar, fix already under way.

**Comment by Patil2099** [comment]
I would love to work on this
