### ISSUE TITLE
Show line with dots for incomplete time periods

### ISSUE THREAD

**Issue by timgl** [PostHog/posthog#522]
**Describe the bug**

When a time period (like a day) isn't finished yet the numbers look much lower than previous days, which causes me a heart attack every time until I remember.

![image](https://user-images.githubusercontent.com/1727427/78898997-a914f100-7a6c-11ea-958e-0d73e6e9d10b.png)

Instead, the line from the last day to today should be dotted, indicating that day isn't finished yet.

**Additional context**

Annoyingly this isn't a standard feature in Chart.js. There is a feature called 'spanGaps' that spans missing data points, which we might be able to abuse.

I also found [this](https://plnkr.co/edit/Lu0yCh8Imfpw9joxyjnv?p=preview&preview) example for d3.js. That at least shows what I mean with this.

**Comment by EDsCODE** [comment]
If we're willing to give up the curves, we can double up the lines and make one of them dashed one of them filled without the last data point. If not, I'll have to think

<img width="861" alt="Screen Shot 2020-04-13 at 2 26 45 PM" src="https://user-images.githubusercontent.com/13127476/79148010-d75b3f00-7d92-11ea-805e-01d0946b5a8d.png">

**Comment by timgl** [comment]
Could we keep the original lines curved and just make the last one straight? Or is that ugly?

**Comment by timgl** [comment]
I'm actually not against getting rid of the curves as it's prettier but less accurate, so if we can't do above let's just get rid of curves.

**Comment by EDsCODE** [comment]
it looks slightly funny but it'll definitely bring your attention to the fact that the data is incomplete. I'm okay with it. also, i think i'm going to do #510 too. the shifted range is another panic inducer haha

<img width="856" alt="Screen Shot 2020-04-13 at 2 50 17 PM" src="https://user-images.githubusercontent.com/13127476/79150063-1fc82c00-7d96-11ea-9890-c1f920a34f14.png">

**Comment by jamesefhawkins** [comment]
I think the disconnected look here intuitively is what it needs.
