### ISSUE TITLE
Persist Person modals in the URL

### ISSUE THREAD

**Issue by mariusandra** [PostHog/posthog#5223]
## Is your feature request related to a problem?

- If I open a point on a graph and click "back" in the browser (super common on phones where you don't know if it's a modal or a new screen), I'm taken out of insights. Instead the modal should just close.
- If I open a person modal, click onto the person, click back, the modal is closed. It should still stay open.

## Describe the solution you'd like

Add `#personModal=true` or similar with some more data into the `hashParams` of the URL via the `actionToUrl` and `urlToAction` [kea-router](https://kea.js.org/docs/plugins/router) features.

## Describe alternatives you've considered

I guess I just need to open the modal and/or move forward in history to get back to where I was.

## Additional context

We used to have this a long long time ago in a company far far away.

**Comment by macobo** [comment]
Perhaps links should open in a new tab instead? See also @clarkus comment under https://github.com/PostHog/posthog/issues/5173
