### ISSUE TITLE
Better tooltips for filtered trends

### ISSUE THREAD

**Issue by jamesefhawkins** [PostHog/posthog#5229]
## Is your feature request related to a problem?

Dashboard trends are impossible to understand when they have a breakdown applied.

<img width="589" alt="Screenshot 2021-07-20 at 17 23 04" src="https://user-images.githubusercontent.com/47497682/126360311-700e9e96-246b-4e39-90ce-d7088d7dd166.png">

This is from an [internal marketing dashboard](https://app.posthog.com/dashboard/7040) - with the [full insight trend here](https://app.posthog.com/insights?insight=TRENDS&events=%5B%7B%22id%22%3A%22%24pageview%22%2C%22math%22%3A%22dau%22%2C%22name%22%3A%22%24pageview%22%2C%22type%22%3A%22events%22%2C%22order%22%3A0%2C%22properties%22%3A%5B%7B%22key%22%3A%22%24current_url%22%2C%22type%22%3A%22event%22%2C%22value%22%3A%22posthog.com%2Fblog%2F%22%2C%22operator%22%3A%22icontains%22%7D%5D%2C%22math_property%22%3Anull%7D%2C%7B%22id%22%3A%22%24pageview%22%2C%22math%22%3A%22dau%22%2C%22name%22%3A%22%24pageview%22%2C%22type%22%3A%22events%22%2C%22order%22%3A1%2C%22properties%22%3A%5B%7B%22key%22%3A%22%24current_url%22%2C%22type%22%3A%22event%22%2C%22value%22%3A%5B%22https%3A%2F%2Fposthog.com%2F%22%5D%2C%22operator%22%3A%22exact%22%7D%5D%2C%22math_property%22%3Anull%7D%2C%7B%22id%22%3A%22%24pageview%22%2C%22math%22%3A%22dau%22%2C%22name%22%3A%22%24pageview%22%2C%22type%22%3A%22events%22%2C%22order%22%3A2%2C%22properties%22%3A%5B%7B%22key%22%3A%22%24current_url%22%2C%22type%22%3A%22event%22%2C%22value%22%3A%22posthog.com%2Fcareers%2F%22%2C%22operator%22%3A%22icontains%22%7D%5D%2C%22math_property%22%3Anull%7D%2C%7B%22id%22%3A%22%24pageview%22%2C%22math%22%3A%22dau%22%2C%22name%22%3A%22%24pageview%22%2C%22type%22%3A%22events%22%2C%22order%22%3A3%2C%22properties%22%3A%5B%7B%22key%22%3A%22%24current_url%22%2C%22type%22%3A%22event%22%2C%22value%22%3A%22posthog.com%2Fhandbook%2F%22%2C%22operator%22%3A%22icontains%22%7D%5D%2C%22math_property%22%3Anull%7D%2C%7B%22id%22%3A%22%24pageview%22%2C%22math%22%3A%22dau%22%2C%22name%22%3A%22%24pageview%22%2C%22type%22%3A%22events%22%2C%22order%22%3A4%2C%22properties%22%3A%5B%7B%22key%22%3A%22%24current_url%22%2C%22type%22%3A%22event%22%2C%22value%22%3A%22posthog.com%2Fdocs%2F%22%2C%22operator%22%3A%22icontains%22%7D%5D%2C%22math_property%22%3Anull%7D%5D&display=ActionsLineGraph&interval=week&date_from=yStart&properties=%5B%7B%22key%22%3A%22%24current_url%22%2C%22type%22%3A%22event%22%2C%22value%22%3A%22https%3A%2F%2Fapp.posthog.com%2F%22%2C%22operator%22%3A%22not_icontains%22%7D%5D&filter_test_accounts=true#fromItem=271130&fromItemName=Site%20Visitors%20-%20Weekly%20Uniques&fromDashboard=7040). 

I can't tell what the meaning of the different lines is.
 
## Describe the solution you'd like

The tooltip to make clearer what the different lines are - when there are multiple graph series that are differentiated based on the filter applied, then add text to explain the filter to the tooltip, _or_ a legend to appear when there are multiple lines on a trend in the dashboard.

## Describe alternatives you've considered

Click into the dashboard item to look at the chart. The tooltips aren't perfect for this - they still don't expand at all, BUT you can use them to figure out which line is which by looking at the letters in front of the graph series:

<img width="668" alt="Screenshot 2021-07-20 at 17 27 21" src="https://user-images.githubusercontent.com/47497682/126360901-ed481b2c-3b9c-48b0-a906-9da31afce080.png">

**Comment by clarkus** [comment]
Related: https://github.com/PostHog/posthog/issues/1148

This is taken from the work supporting https://github.com/PostHog/posthog/issues/3408. In the revised design for query building, there is affordance for a rename action. Clicking that action would trigger a modal that represents the current property name with an option for providing a new name value. Once submitted, both values are shown in the builder, but only the renamed value is shown in the corresponding visualization. This is shown specific to funnels. Other insight types would have different label values based on their corresponding labels. Please let me know if you have any feedback on these proposed changes. 

![Edit Insight](https://user-images.githubusercontent.com/254612/127387112-71afa1bb-77da-4aaf-b24d-99f36bfe4935.png)
![Rename Query Step](https://user-images.githubusercontent.com/254612/127387114-5365ff23-ae62-4e83-b647-7fcf37df58b6.png)

_Originally posted by @clarkus in https://github.com/PostHog/posthog/issues/1148#issuecomment-888580010_

**Comment by paolodamico** [comment]
So the naming series is a great improvement for this, I think we can close this issue and rely on that for better information in the tooltips. Alternatively we can add some extra logic to tooltips so we show some extra information when needed, but I think this doesn't lead to as good experience as naming series, so I'd be in favour of closing this and just working on naming series.

Thoughts?

**Comment by clarkus** [comment]
@paolodamico I think renaming is a good solution to pursue. The one thing I'm thinking about is how critical it is to having succinct, meaningful insight labels. Right now the user would do this manually by clicking rename, but should we always prompt for a meaningful name? It seems contrary to the exploratory side of insight creation, but absolutely important for creating an approachable saved insight you plan to share with others.

**Comment by paolodamico** [comment]
I think we could suggest to users to set a custom name whenever they save or share an insight, but I think there are a lot of contexts where having a custom name is not particularly needed.

**Comment by clarkus** [comment]
Just bumping this as we heard from a user [in slack today](https://posthogusers.slack.com/archives/C01GLBKHKQT/p1631217046033100) expressing the same problem.

**Comment by alexkim205** [comment]
Gotcha, finally got some time today and can start working on this

**Comment by alexkim205** [comment]
@clarkus - Thanks this is all really helpful. I had a few quick q's about different edge cases which will help me out with the implementation side.

- Are these custom names scoped to the insight/dashboard item type? Or do name changes apply app-wide? For example if I'm renaming an action filter to "Email Sign Ups" will this change the action name permanently or only for that insight/dashboard item?
- Should exclusion events (only available for funnels atm) be renamable as well? My gut instinct is no...

Here are some assumptions I'm making, but definitely feel free to point out any incorrect ones:

- Persistent renamed filters is only applicable to saved insights (in /saved_insights or /dashboards)
- In terms of priority of displaying (in tables, legends, etc): Custom names > filter name
- If renamed, always show secondary name (id for events, name for actions) in parentheses

**Comment by clarkus** [comment]
@alexkim205 Renames are specific to the insight and should not affect anything outside the scope of that insight (note an insight's presence on a dashboard is considered part of that scope). We don't need to rename anything unless it's shown on the visualization. The purpose here is to give a friendly / more approachable label value when looking at the visualization. Exclusions should not be able to be renamed. Your assumptions align with my understanding of how this solution would work.
