### ISSUE TITLE
Funnels next - breakdowns, comparison ranges, and more

### ISSUE THREAD

**Issue by clarkus** [PostHog/posthog#5230]
## Is your feature request related to a problem?

This is a continuation of https://github.com/PostHog/posthog/issues/4535. We still need to evaluate the reception of the upcoming funnels work, but also know there are outstanding workflows to solve for. There is also an alternate layout with the Mega Legend™ table to consider as longer-term solution.

## Describe the solution you'd like

Scalable funnels that support
- Breakdowns
- Comparison ranges
- Alternate layouts based on the reception of the work in #4535

**Comment by clarkus** [comment]
The next iteration of work on funnels is focused on breakdowns, comparison ranges, and **scale**. This is an updated left-to-right layout I've been working on. I'm calling it the MegaLegend™ layout 😬 . The table does most of the heavy lifting by describing the completion count, completion rate, drop count, drop rate, and average time to complete for each step. When breakdowns are applied, the table describes each breakdown options for each step. 

<img width="979" alt="Screen Shot 2021-07-20 at 9 57 12 AM" src="https://user-images.githubusercontent.com/254612/126364866-820c1818-74c6-4a5b-9cee-c05e451c8ac3.png">

To address scale, I've taken this visualization to be the full width of the content area of insights. This aligns with other insight layouts, but introduces some complications with step definitions displacing the visualization down the page. More steps = more height = push the viz down the page. This design could work in the current insights layout, but we'd be very limited on the number of steps shown without scrolling. 

Comparison ranges are the other area of focus. I think the design above would also serve this case, but we'd have to reduce the number of breakdown options selected at any given time. This is purely a limitation of space in the visualization. When comparison ranges are applied, each breakdown option results in two bars for each step in the funnel. You can see some explorations around contrast, differentiation, and sizing below. 

<img width="887" alt="Screen Shot 2021-07-20 at 10 01 09 AM" src="https://user-images.githubusercontent.com/254612/126365345-be8a7218-1569-4632-baa9-6513034b13fd.png">

**Comment by samwinslow** [comment]
Looks great! Some thoughts:

- What does "Baseline" mean? Weighted average of all values? It sort of looks like just another breakdown series. I think more differentiation of the bar and row style could be justified to distinguish it. Even just indenting the row titles would help.
- I think it would be cool to somehow incorporate the red and green continuity / dropoff arrows from other design iterations into the table.

**Comment by clarkus** [comment]
Thanks for the input, @samwinslow! I really tried hard to find a good word for this, but baseline is the funnel conversion performance without any breakdowns applied. It's just there as a comparison point so that any breakdown can be compared to the overall funnel performance. I am 1000% open to other ideas for that label. It might also benefit from a tooltip that clarifies exactly what it is. 

I'll take a stab at including the icons into the table. It could be a way to more succinctly label each column in the table, too?

**Comment by corywatilo** [comment]
Loving the breakdown!

My main feedback is that the top of this screen feels like it’s starting to resemble the kitchen sink. (This section wasn’t the focus of this exercise, but I’ll leave the feedback here regardless, and maybe it eventually deserves its own issue?)

- Time selector
- “Compare to”
- Configure
- Layout option
- Timezone

_All_ these options are essentially configuration options. Some may make sense to surface here (like time selector). But visually they’re currently split (some anchored left, some anchored right).

I know the UTC callout has been there historically, but does it deserve this much prominence, especially if it can’t be changed?

In previous wires/mocks, we’ve (I’ve) played with trying to split _querying options_ (in the workspace editor) from _display options_ (in the results area).

**Query-related options:** Things that affect how the query is being run
**Display options:** Settings that change how the data is surfaced, usually front-end options

(There are some caveats. For example, it still makes sense to show the time selector in the result area, even though it’s technically modifying the query.)

**Comment by clarkus** [comment]
> I know the UTC callout has been there historically, but does it deserve this much prominence, especially if it can’t be changed?

I have played around with putting this into the header given it's a global context. It's not in the concepts at https://github.com/PostHog/posthog/issues/5346, but I can incorporate that. 

> **Query-related options:** Things that affect how the query is being run
> **Display options:** Settings that change how the data is surfaced, usually front-end options
> 
> (There are some caveats. For example, it still makes sense to show the time selector in the result area, even though it’s technically modifying the query.)

I've been trying to adhere to this same model. Here's my current grouping and reasoning:

- Insight query - this varies across insight types, but it's the core definition we use to represent the data. 
- Insight filters - filters that affect the entire query and take affect before step filters
- Breakdowns - this is really just a group by clause
- Formulas - conditionally applicable, but generally this is a means of deriving information across graph series

These are the things that form the core structure of the data and set the frame of what is and isn't configurable within that. Said another way, this stuff sets the bounds for the other options we provide in the graph container.

Display options - things a user might want to tweak to answer a specific aspect of a question. These are also options we might make available on standalone insights to make it easier to explore data without having start editing. 

- UTC - see comment above -agree we should move it
- Time range & comparison ranges - this is directly related to the comparison view and should respect whatever data filters are applied to the broader context. For example, if we're filtering the insight query to have a unicode time stamp of less than a certain date, we'd want to restrict that from the selection range in the time and comparison controls.
- Configure - might not be needed depending on the insight type. This is literally a means of toggling the legend on and off to facilitate the display of metrics. This is probably not needed for the visualization shown. 
- Layout option - not always needed, but applicable to funnels.

**Comment by paolodamico** [comment]
I think this conversation has evolved to other issues? Should we close this?
