### ISSUE TITLE
Add note explaining why session recordings don't work with segment

### ISSUE THREAD

**Issue by macobo** [PostHog/posthog#5242]
## Is your feature request related to a problem?

Some users use posthog via segment and are confused why they don't see session recordings. We should add a note along the lines of "session recording only works with posthog-js" to the feature.

**Comment by Twixes** [comment]
This is already noted in project settings (has been for a long time).

<img width="532" alt="Session Recording Project Settings" src="https://user-images.githubusercontent.com/4550621/127859318-67698153-9e81-42f3-992e-d408e9feb065.png">

I'm not sure if there's a stronger way to emphasize this. Where do you think this extra note should be put?
