### ISSUE TITLE
Multiple cohorts in taxonomic breakdown filter

### ISSUE THREAD

**Issue by mariusandra** [PostHog/posthog#5247]
## Is your feature request related to a problem?

The old filter supported multiple cohorts in a breakdown:

![image](https://user-images.githubusercontent.com/53387/126456138-637bd12a-2ec1-4b6a-9fef-90740ed2249a.png)

The new taxonomic filter does not. I don't think we can release this flag before this support is added. I'm not sure how many people use this feature, but it's definitely in the "more than 0 people have built something that depends on it and we can't remove it ever" zone.

## Describe the solution you'd like

Multiple select/tags in the taxonomic filter. It's not that hard to add TBH.

## Describe alternatives you've considered

"+ add another cohort" button.

## Additional context

[Don't click here](https://www.youtube.com/watch?v=gfkts0u-m6w).

**Comment by paolodamico** [comment]
There's an important consideration here. From our own dogfooding & consistent user feedback, the breakdown by multiple cohorts is not clear and it's even less discoverable. The goal of this feature is to let you compare behavior across different cohorts, but when thinking about how to build this query is not intuitive to jump to breakdown. Think it's worth rethinking this behavior. CC @clarkus

**Comment by clarkus** [comment]
I'm on board with rethinking it, but short term we could ensure parity with the old filter. Allowing for multiple selections there makes sense. Is there anything blocking that from our current release? 

@paolodamico I am currently working on breakdowns and comparison ranges, so I could spend some time on this today. Are there any specific details about what was problematic with the current workflow?

**Comment by clarkus** [comment]
One other thought - breakdown properties are very much a single select use case within the query builder. Cohort breakdowns are a multiple select case. Do we have any understanding of cohort usage patterns in breakdowns? How many cohorts are usually selected? How big is the list that users are generally picking from? That would help inform how we summarize selected items in the multiple selection scenario.

**Comment by mariusandra** [comment]
I ended up going for an easier implementation that IMO has better UX as well.

![2021-07-22 00 42 14](https://user-images.githubusercontent.com/53387/126569138-f44dbe25-e2d9-468b-92e6-000fef645fc7.gif)
