### ISSUE TITLE
Funnels functional bugs

### ISSUE THREAD

**Issue by paolodamico** [PostHog/posthog#5249]
Fairly blocking functional bugs on funnels.

~1. This state comes in unexpectedly when building funnels. [Initially reported](https://posthog.slack.com/archives/C01G8S5T08Z/p1626867931020700) as a problem with having no breakdown values that match a query, you can see in this recording that this funnel should have results, `$pageview` is the first event with no filters, there's always a Pageview. Further, if you refresh, the funnel renders.~
    ![image](https://user-images.githubusercontent.com/5864173/126488337-69800503-1da8-4250-b62a-463adee0363a.gif)

~2. There's some strange bug where the bars don't get properly rendered.~

![image](https://user-images.githubusercontent.com/5864173/126488462-74133a84-d798-424e-94eb-b1343f393073.gif)

3. Time to convert doesn’t “height: 100%”
![image](https://user-images.githubusercontent.com/5864173/126488581-1598395a-2abb-4db9-8d63-9e4f08752342.png)

~4. The historical conversion should be a line chart~

CC @mariusandra

**Comment by mariusandra** [comment]
I think 1 and 2 are fixed with https://github.com/PostHog/posthog/pull/5248

**Comment by mariusandra** [comment]
Point 4 is also fixed in that PR, though it adds a bit of a scrollbar.

**Comment by mariusandra** [comment]
5. Clicking the modal to open people doesn't work on dashboards. The error is silently swallowed, so not a blocker though.  Not sure if https://github.com/PostHog/posthog/pull/5236 would fix or not.

**Comment by mariusandra** [comment]
6. "All steps" are merged together here: 
![image](https://user-images.githubusercontent.com/53387/126494542-e7cb6d53-b1ea-49e6-b85a-13d4160559db.png)

Individual steps are fine:
![image](https://user-images.githubusercontent.com/53387/126494566-458603fe-488a-41e9-8c0e-dae801c68883.png)

**Comment by paolodamico** [comment]
~7. Conversion trends does not render on Postgres~
<img width="1313" alt="" src="https://user-images.githubusercontent.com/5864173/126494921-3c370212-7199-46c4-ab57-37f4673c3001.png">

**Comment by alexkim205** [comment]
> 1. Conversion trends does not render on Postgres
> 
> <img alt="" width="1313" src="https://user-images.githubusercontent.com/5864173/126494921-3c370212-7199-46c4-ab57-37f4673c3001.png">

This is intentional as conversion trends is a CH only feature. Do you suggest we have a more user friendly omission?

> 3. Time to convert doesn’t “height: 100%”

I'll take point on this!

**Comment by EDsCODE** [comment]
8. funnel steps left to right can't handle more than 4 steps
9. when clicking persons modal load more, it always says "Showing 99 of X" no matter how big X is. I also think it only shows the top 99 even if you load up more than 99

**Comment by mariusandra** [comment]
Fix for 3 and 4 here: https://github.com/PostHog/posthog/pull/5253

**Comment by paolodamico** [comment]
10. Can't reproduce yet but #5251 is not rendering the 100% funnel bars properly

**Comment by paolodamico** [comment]
Started crossing out issues that have been fixed. Issue no. 3 is still happening but now differently. Let me get CH running to fix.

![image](https://user-images.githubusercontent.com/5864173/126517536-5cf296e1-55c8-42e8-83aa-4ddfc0c4f9eb.gif)

**Comment by EDsCODE** [comment]
11. clicking on a breakdown segment for funnel step should only return the subset not all the persons for that step. (seems like a backend issue)

**Comment by neilkakkar** [comment]
> 11. clicking on a breakdown segment for funnel step should only return the subset not all the persons for that step. (seems like a backend issue)

Just checked, not a backend issue. We aren't sending the `funnel_step_breakdown` parameter to the Persons query, which only returns the persons for that breakdown. (The value for this is the breakdown value returned by the API on the funnel query)

**Comment by alexkim205** [comment]
@paolodamico 

> Started crossing out issues that have been fixed. Issue no. 3 is still happening but now differently. Let me get CH running to fix.

3. This should :sparkjoy: - https://github.com/PostHog/posthog/pull/5259

**Comment by alexkim205** [comment]
6. Seems like a backend bug where bin sizes aren't equal.

Example response (see last bin)

<img width="640" alt="Screen Shot 2021-07-21 at 9 31 13 AM" src="https://user-images.githubusercontent.com/13460330/126525455-c0ec0313-53b3-46fa-b75d-76bd046359a3.png">

Only seems to be happening in all steps responses

**Comment by paolodamico** [comment]
Re @EDsCODE, can you elaborate? Can't seem to reproduce. Maybe the problem is that it's not obvious that you can scroll to the right?
> 8. funnel steps left to right can't handle more than 4 steps

**Comment by mariusandra** [comment]
#### Status update

Pending review:
- ~~Time to convert doesn’t “height: 100%”: https://github.com/PostHog/posthog/pull/5259~~
- ~~"Showing 99 of X" no matter how big X is: https://github.com/PostHog/posthog/pull/5271~~
- ~~Fix z-index issue inside drawers: https://github.com/PostHog/posthog/pull/5270~~
- ~~Fix breakdown filter multiple cohorts: https://github.com/PostHog/posthog/pull/5270~~
- ~~Persist feature flags in the release: https://github.com/PostHog/posthog/pull/5273~~

Still to do:
- Persist the specific feature flags we want to: https://github.com/PostHog/posthog/pull/5282

Experience not started:
- Eric: "clicking on a breakdown segment for funnel step should only return the subset not all the persons for that step. (seems like a backend issue)" --> Neil: "Just checked, not a backend issue. We aren't sending the `funnel_step_breakdown` parameter to the Persons query" --> ... ?
- ~~Clicking dashboard items won't open person modals:~~ https://github.com/PostHog/posthog/pull/5286
![2021-07-22 01 23 37](https://user-images.githubusercontent.com/53387/126572088-e9f85f6d-42e6-4324-92bf-841f826f5389.gif)
- ~~Automatically set default funnelVizType for [queries like this](https://app.posthog.com/insights?events=%5B%7B%22id%22%3A%22first%20team%20event%20ingested%22%2C%22math%22%3Anull%2C%22name%22%3A%22first%20team%20event%20ingested%22%2C%22type%22%3A%22events%22%2C%22order%22%3A1%2C%22properties%22%3A%5B%5D%2C%22math_property%22%3Anull%7D%5D&actions=%5B%7B%22id%22%3A%222674%22%2C%22math%22%3Anull%2C%22name%22%3A%22User%20Signed%20Up%20(Comprehensive)%22%2C%22type%22%3A%22actions%22%2C%22order%22%3A0%2C%22properties%22%3A%5B%5D%2C%22math_property%22%3Anull%7D%2C%7B%22id%22%3A4912%2C%22math%22%3Anull%2C%22name%22%3A%22Discovered%20Learning%22%2C%22type%22%3A%22actions%22%2C%22order%22%3A2%2C%22properties%22%3A%5B%5D%2C%22math_property%22%3Anull%7D%5D&insight=FUNNELS&interval=day&filter_test_accounts=true&new_entity=%5B%5D&date_from=-7d&display=FunnelViz&breakdown=%24os&breakdown_type=person) (e.g. old saved insights). Without it currently the breakdown filter doesn't show up.~~ https://github.com/PostHog/posthog/pull/5280
- https://github.com/PostHog/posthog/issues/5262 <-- oh god what's this now? 😨 

Query blockers... or fixed?
- ~~[All steps are merged](https://github.com/PostHog/posthog/issues/5249#issuecomment-884180568) -> "Seems like a backend bug" --> what's the status? @alexkim205 @neilkakkar ?~~ https://github.com/PostHog/posthog/pull/5283
- Fix [the issue here](https://github.com/PostHog/posthog/issues/5211) where you need to turn off "filter out internal users" before the breakdown is applied. @neilkakkar ? 

Bonus if we can get it in:
- https://github.com/PostHog/posthog/pull/5233

Next release:
- https://github.com/PostHog/posthog/pull/5216

**Comment by neilkakkar** [comment]
> All steps are merged -> "Seems like a backend bug" --> what's the status? @alexkim205 @neilkakkar ?

Can you give me a link to an example where this still happens? Can't seem to reproduce.

---

> Eric: "clicking on a breakdown segment for funnel step should only return the subset not all the persons for that step. (seems like a backend issue)" --> Neil: "Just checked, not a backend issue. We aren't sending the funnel_step_breakdown parameter to the Persons query" --> ... ?

Haven't done anything about this yet! If anyone else has the bandwidth, please feel free to pick up.

---

> Fix the issue here where you need to turn off "filter out internal users" before the breakdown is applied. @neilkakkar ?

On this! Original issue seems to be fixed, but looks like there's a new one with breakdowns not working on actions.

**Comment by mariusandra** [comment]
A. Here's an [example](https://app.posthog.com/insights?events=%5B%7B%22id%22%3A%22%24pageview%22%2C%22math%22%3Anull%2C%22name%22%3A%22%24pageview%22%2C%22type%22%3A%22events%22%2C%22order%22%3A0%2C%22properties%22%3A%5B%5D%2C%22math_property%22%3Anull%7D%2C%7B%22id%22%3A%22viewed%20dashboard%22%2C%22math%22%3Anull%2C%22name%22%3A%22viewed%20dashboard%22%2C%22type%22%3A%22events%22%2C%22order%22%3A1%2C%22properties%22%3A%5B%5D%2C%22math_property%22%3Anull%7D%2C%7B%22id%22%3A%22saved%20insight%20to%20dashboard%22%2C%22math%22%3Anull%2C%22name%22%3A%22saved%20insight%20to%20dashboard%22%2C%22type%22%3A%22events%22%2C%22order%22%3A2%2C%22properties%22%3A%5B%5D%2C%22math_property%22%3Anull%7D%5D&display=FunnelViz&insight=FUNNELS&interval=day&funnel_viz_type=time_to_convert&filter_test_accounts=true) where all the funnel bins are still merged together.

B. I should be able to pick this up soon.

C. Great!

**Comment by neilkakkar** [comment]
Is this how the example above is supposed to look? 👀 

![image](https://user-images.githubusercontent.com/7115141/126613664-71cf00f9-1add-45b5-9e2c-ce5f398764a8.png)

**Comment by mariusandra** [comment]
@neilkakkar apologies, [this is the broken example](https://app.posthog.com/insights?insight=FUNNELS&properties=%5B%5D&filter_test_accounts=true&interval=day&events=%5B%7B%22id%22%3A%22first%20team%20event%20ingested%22%2C%22name%22%3A%22first%20team%20event%20ingested%22%2C%22type%22%3A%22events%22%2C%22order%22%3A1%7D%2C%7B%22id%22%3A%22insight%20loaded%22%2C%22name%22%3A%22insight%20loaded%22%2C%22type%22%3A%22events%22%2C%22order%22%3A2%7D%5D&actions=%5B%7B%22id%22%3A2674%2C%22name%22%3A%22User%20Signed%20Up%20(Comprehensive)%22%2C%22type%22%3A%22actions%22%2C%22order%22%3A0%7D%2C%7B%22id%22%3A4912%2C%22name%22%3A%22Discovered%20Learning%22%2C%22type%22%3A%22actions%22%2C%22order%22%3A3%7D%5D&new_entity=%5B%5D&funnel_viz_type=time_to_convert&display=FunnelViz)

I'm not sure if it's a backend or a frontend bug to be honest. Does this data look legit to you?

![image](https://user-images.githubusercontent.com/53387/126618638-8fd10149-4ba7-45c3-97b0-6d15656b495d.png)

**Comment by neilkakkar** [comment]
The `null` in the end seems wrong, so looks like a backend issue to me as well. Looking 👀 .

**Comment by neilkakkar** [comment]
> @neilkakkar apologies, this is the broken example

Ok, this one is looking good now, can you confirm as well please?

**Comment by mariusandra** [comment]
Much better, thank you! :)

**Comment by mariusandra** [comment]
#### Another summary.

Ready to merge:
- ~~https://github.com/PostHog/posthog/pull/5282 (ultimately blocked behind #5293, but could already be reviewed)~~
- ~~https://github.com/PostHog/posthog/pull/5269~~
- ~~https://github.com/PostHog/posthog/pull/5285~~

Frontend todo:
- Eric: "clicking on a breakdown segment for funnel step should only return the subset not all the persons for that step. (seems like a backend issue)" --> Neil: "Just checked, not a backend issue. We aren't sending the funnel_step_breakdown parameter to the Persons query" --> ... ? https://github.com/PostHog/posthog/pull/5289
- Add "All Users" option into cohort breakdown https://github.com/PostHog/posthog/pull/5293

Backend todo:
-  ~~https://github.com/PostHog/posthog/issues/5211 / https://github.com/PostHog/posthog/pull/5288~~

Bonus:
- ~~Can we still get this in? https://github.com/PostHog/posthog/pull/5233~~
- Bug that was there before: https://github.com/PostHog/posthog/issues/5262
- Are there any more filters or dropdowns that could be converted to the new one? All property filters got converted, but there are other on-off dropdowns. The "event" selector under "events" is for sure one such case. We should list them and then convert to the taxonomic one.
- Even with the new taxonomic filter, the event & person properties are still loaded in the background. E.g. for usage under the "event stats" page... or in the "event name" filter under events. Can we not load them, even if in the background?

**Comment by liyiy** [comment]
@EDsCODE I'm adding that `funnel_step_breakdown` param now according to @neilkakkar but it still returns me the same results, can you confirm this too? I did it on both local CH and prod, on prod I just compared this one [with](https://app.posthog.com/api/person/funnel/?insight=FUNNELS&properties=%5B%5D&filter_test_accounts=false&events=%5B%7B%22id%22%3A%22%24pageview%22%2C%22name%22%3A%22%24pageview%22%2C%22type%22%3A%22events%22%2C%22order%22%3A0%7D%2C%7B%22id%22%3A%22%24pageview%22%2C%22name%22%3A%22%24pageview%22%2C%22type%22%3A%22events%22%2C%22order%22%3A1%7D%5D&actions=%5B%5D&funnel_viz_type=steps&display=FunnelViz&interval=day&breakdown=%24geoip_continent_name&breakdown_type=event&new_entity=%5B%5D&funnel_step=2&funnel_to_step=2&funnel_step_breakdown=Asia) the funnel step breakdown param and this one [without ](https://app.posthog.com/api/person/funnel/?insight=FUNNELS&properties=%5B%5D&filter_test_accounts=false&events=%5B%7B%22id%22%3A%22%24pageview%22%2C%22name%22%3A%22%24pageview%22%2C%22type%22%3A%22events%22%2C%22order%22%3A0%7D%2C%7B%22id%22%3A%22%24pageview%22%2C%22name%22%3A%22%24pageview%22%2C%22type%22%3A%22events%22%2C%22order%22%3A1%7D%5D&actions=%5B%5D&funnel_viz_type=steps&display=FunnelViz&interval=day&breakdown=%24geoip_continent_name&breakdown_type=event&new_entity=%5B%5D&funnel_step=2&funnel_to_step=2)

**Comment by mariusandra** [comment]
Last blocking things:
- ~~Finish & Merge: https://github.com/PostHog/posthog/pull/5289~~
- ~~Review & Merge: https://github.com/PostHog/posthog/pull/5293~~
- ~~Fix bugs with Postgres & calculate button: https://github.com/PostHog/posthog/issues/5298~~
   - ~~PR - #5304~~
- ~~https://github.com/PostHog/posthog/pull/5265~~
- ~~Remove breakdown table checkboxes https://github.com/PostHog/posthog/pull/5300#event-5058347404~~
- ~~Funnel histogram labels are often on top of each other https://github.com/PostHog/posthog/pull/5301~~

**Comment by paolodamico** [comment]
Looks like this is actually done, so closing.
