### ISSUE TITLE
100% funnel chart not taking up 100% height

### ISSUE THREAD

**Issue by marcushyett-ph** [PostHog/posthog#5251]
## Bug description

The first funnel step is saying 100% but not taking up 100% of the bar.

<img width="219" alt="image" src="https://user-images.githubusercontent.com/85295485/126504041-d2984d4f-18b5-4f03-a5a1-16b5e6c0d298.png">

## Expected behavior

Bar to fill 100%

## How to reproduce

1. https://app.posthog.com/insights?events=%5B%7B%22id%22%3A%22%24pageview%22%2C%22math%22%3Anull%2C%22name%22%3A%22%24pageview%22%2C%22type%22%3A%22events%22%2C%22order%22%3A0%2C%22properties%22%3A%5B%7B%22key%22%3A%22%24current_url%22%2C%22type%22%3A%22event%22%2C%22value%22%3A%22https%3A%2F%2Fapp.posthog.com%2Fsignup%22%2C%22operator%22%3A%22icontains%22%7D%5D%2C%22math_property%22%3Anull%7D%2C%7B%22id%22%3A%22user%20signed%20up%22%2C%22math%22%3Anull%2C%22name%22%3A%22user%20signed%20up%22%2C%22type%22%3A%22events%22%2C%22order%22%3A1%2C%22properties%22%3A%5B%5D%2C%22math_property%22%3Anull%7D%5D&display=FunnelViz&insight=FUNNELS&interval=day&date_from=-7d&funnel_viz_type=steps

## Environment

- [x] PostHog Cloud
- [ ] self-hosted PostHog, version/commit: _please provide_

**Comment by paolodamico** [comment]
It shows the full bar for me, think this was inadvertently fixed in one of our PR fixes, can you confirm @marcushyett-ph ?

**Comment by marcushyett-ph** [comment]
Nope I still get it on app after a hard refresh...

**Comment by samwinslow** [comment]
On my end, I can't even load this page (`400 Bad Request: Error parsing headers: 'limit request headers fields size'`).

I think it's a combination of our `Cookie` and `:path:` headers both being huge. Cookie alone is 8KB, and a standard limit of either 8 or 16KB for header fields may be imposed.

Somewhat of a separate issue for infrastructure, but I'll see if I can reproduce this UI bug on another funnels query.

**Comment by samwinslow** [comment]
Can repro on Safari. Working on a solution now.
