### ISSUE TITLE
BUG: Selecting Filter auto scroll to top 

### ISSUE THREAD

**Issue by merrcury** [PostHog/posthog#5261]
## Bug description
In Project Settings, Whenever go to add a new filter in "Filter Out Internal and Test Users", it takes me to the top the page. It's annoying while adding multiple filters. 

Refer Below GIF:
![filter](https://user-images.githubusercontent.com/35988194/126524958-799c5878-a682-4d57-9911-195c056a277c.gif)

## Expected behavior
It should not take the user to the top of the page and remain there till the filter loads. 

## How to reproduce

1. Go to Project Settings
2. Scroll Down to `Filter Out Internal and Test Users`. 
3. Click 'Add filter' and this should happen

## Environment

- [X] PostHog Cloud
- [ ] self-hosted PostHog, version/commit: _please provide_

## Additional context
Browser: Google Chrome 
Browser Version: 91.0.4472.164 (Official Build) (arm64)

**Comment by paolodamico** [comment]
I think this will be fixed with the new taxonomic filter @mariusandra ?

**Comment by mariusandra** [comment]
Yeah, this will be a better experience very soon:

![image](https://user-images.githubusercontent.com/53387/126556628-bcee858e-8a5c-4647-b898-33c2461cf1b7.png)

**Comment by paolodamico** [comment]
This has been addressed with the last improvements to the taxonomic filter, thanks for reporting @merrcury!
