### ISSUE TITLE
Permalink's to insights with short urls

### ISSUE THREAD

**Issue by marcushyett-ph** [PostHog/posthog#5274]
## Is your feature request related to a problem?

When I find an exciting insight using PostHog - all I want to do is tell the world (specifically the world of people who are interested and should have the appropriate access to the data). Right now it's quite tricky to share an insight for two reasons:

- The URLS are enormous and messy
- The URL links to a query and not the specific result I saw (for example if I wanted to link someone to something really cool I saw that happened in our funnel today, specifically, and they happened to open the link I sent next week - they would see totally different data - because they query would show the results of that day and not the results from when I sent it)

## Describe the solution you'd like
Permalink's with short urls for insights

I would love to be able to get these Permanent URLS form anywhere (e.g. on any insight I have but also directly from a dashboard without opening up the insight itself)

## Describe alternatives you've considered
I just copy paste the long URL right now

## Additional context
This was also requested by a customer.

**Comment by paolodamico** [comment]
Aha I built this feature a couple of weeks ago but haven't been able to finish the PR that makes it discoverable. I think with the work around #3308 it'll get addressed.

**Comment by marcushyett-ph** [comment]
Brilliant!

**Comment by marcushyett-ph** [comment]
One thing that came up from a client was that we need permanent urls for insights within projects..

If I have two projects and I send a link to an insight from one, the url will link to that insight ONLY if they already have that project open.

@paolodamico did you make any progress on this since #3308 was closed?

**Comment by paolodamico** [comment]
Definitely a super important point! For that we'll need to figure out #5363 first, but I'm thinking we can convert the short ID attribute to unique across the entire Insight model and that way the ID will indirectly include the project ID.

Actually no, from #3308 I only extracted satellite helpful code, but  @liyiy has already made some progress on that on #5416. From the standup today, we'll make more progress on this after we address the most critical bugs 😉

**Comment by paolodamico** [comment]
Just cross-posting some context here with some user feedback on the importance of reliable permalinks (include the project ID), [full context here](https://posthog.slack.com/archives/C02VD4F8JP4/p1644000576027469).

> This really impedes the ability to collaborate across PostHog.

**Comment by mariusandra** [comment]
Discussed this with @Twixes today, and came to the conclusion that we can scope this down 10x and implement a simple backend layer. 

Right now, whenever we hit an endpoint like `http://localhost:8000/insights/QBaridVR`, this is resolved by [a view called `home`](https://github.com/PostHog/posthog/blob/3604c72e3a53a875332b58959979e3b02d942ce2/posthog/urls.py#L29-L30), that just renders the `index.html` template and gives the reign to React.

Instead, let's add a separate view that: 
1. parses the URL in the backend and gets the insight `short_id`
2. checks if that insight belongs to the current team
3. if not checks if it belongs to any team the user is part of
4. if so, it changes the team silently in the background 
5. renders `index.html` like normally

There will be no redirect, no popup and no project ID in the URL. The simple realisation is that we don't need to put the project ID into the URL if the URL already contains a globally unique ID in it.

I tried to quickly build this (PRs over issues), but got stuck behind some django and will defer for now. If anyone feels like it, please pick it up.

We'll still need to do work to fully enable different projects being open in different tabs (most things work, some don't), but implementing this as described above only for insights, dashboards and feature flags will already unlock so much.

**Comment by clarkus** [comment]
Would that backend layer also translate URLs with the `shared_dashboard` parameter? Just hoping we can keep those backwards compatible, but use a single project URL for all purposes going forward.

**Comment by mariusandra** [comment]
We can. The shared dashboard parameter is a unique token just like an `id` or a `uuid` is, so we just need to make sure we cover this case.

**Comment by timgl** [comment]
I solved this problem for dashboards: https://github.com/PostHog/posthog/pull/8262, which is a pattern that we can also apply to feature flags, actions etc.

**Comment by mariusandra** [comment]
That's a legit solution, and can definitely be implemented for other object types. However we could simplify it down further to 0 clicks and 0 redirects, if we detect and silently swap the active project even before the frontend loads. This requires some backend handling *outside* the `/api` paths, but can't be more code than #8262.

**Comment by clarkus** [comment]
I'm in favor of the 0 clicks / 0 redirects. This is linking to a new context, so I don't see a need to prompt. If we were moving from one context to a new context (changing to a new project within the same browser instance) then I could see prompting to notify of the context change.

**Comment by Twixes** [comment]
This is now solved with https://github.com/PostHog/posthog/pull/8681.

**Comment by marcushyett-ph** [comment]
Can you reach out to the customer who requested this, they'll be so excited. If you're not sure of the name, please DM me
