### ISSUE TITLE
Security Proposal: Block admin access by IP

### ISSUE THREAD

**Issue by dazbradbury** [PostHog/posthog#528]
**Is your feature request related to a problem? Please describe.**

PostHog instances need to be publicly accessible to accept incoming events from JS - other than ensuring requests come from the correct domain (https://github.com/PostHog/posthog/issues/262) endpoints need to be publicly accessible for a public website.

However, the PostHog dashboard is likely only used by the data owners. It would be good to restrict access to that dashboard by IP as additional security over email/password (or even 2-factor https://github.com/PostHog/posthog/issues/256) 

**Describe alternatives you've considered**

Splitting the capture workers (publicly accessible) from the admin workers (could be in a VPC / local network). But this doesn't seem as neat and adds unnecessary complexity.

**Comment by timgl** [comment]
Agree this would be good. There is a genuine question here whether this belongs in our Growth or Ultimate plan as I don't see individual devs needing this. @jamesefhawkins thoughts on that?

In terms of implementation [there are packages that can do this](https://django-iprestrict.readthedocs.io/en/latest/) but I think we could go for something fairly simple here. I think just a [simple middleware function](https://stackoverflow.com/questions/12383540/authenticate-by-ip-address-in-django) that checks against an ENV variable. 

There are only a few paths that should be publicly available: `/e`, `/decide`, `/track`, `/capture`, `/batch`, `/engage` and `/static/array.js`.

**Comment by jamesefhawkins** [comment]
Thanks for the suggestion @dazbradbury.

Confirming what Tim said, we'd think of this as a permissions item as we could see it being a lot more important for companies than individual developers. I hope that's ok - the paid version is how we'll support the project.

Our paid product is currently in beta mode, and not released yet. It would also come with a lot of other functionality (a/b tesitng, for example). If you really need this urgently let us know (sales@posthog.com) and we can work out some way of getting it into your team's hands.

**Comment by dazbradbury** [comment]
Of course - totally up to you and your team. I'm not sure security is something individual developers wouldn't care about though, especially for something as standard as IP restrictions for a data store.

Most similar example I can think of, Metabase, is out of the box deployed onto an elastic beanstalk environment, with security groups by default (and thus IP restrictions by default). Every data store I can think of would do the same. But every company needs to draw it's lines between enterprise value and core.

If you have guidance on how the project will be divided in terms of open source vs. closed source features I think that would be interesting to flesh out and make clear to developers up front - and it's interesting to hear your stance on this issue as a guide to future forks. 

Totally appreciate you're moving fast, making decisions quickly, and focusing on product (as you should be!) - but for those exploring or investing time any / all guidance you can provide on that would be super helpful. 

Appreciate the speedy response as always!

**Comment by jamesefhawkins** [comment]
That sounds reasonable. If you're exploring - we just published a high level roadmap [here](https://docs.posthog.com/#/roadmap).

As a todo, I've made an [issue](https://github.com/PostHog/docs/issues/7) to explicitly cover this in more depth so we can get good at being upfront about it.

We're trying to think of it as you suggest to match free versus paid where the value is, and to get as much adoption-encouraging functionality into the free version as well - it'll be more important ultimately that we become universally adopted.

**Comment by dazbradbury** [comment]
I missed out in my response why the decision came as a surprise, which may be of interest to you so I'll post it. My intention isn't to change your mind, merely to show the assumptions garnered from your current sales / marketing pages.

Firstly, one of the main selling points of an open source event tracking solution, and in fact on your homepage, is that it's privacy first. In order to be privacy first, it must be secure by design, otherwise it's not really privacy first - the data is effectively public if you can:

- Find a posthog script in the wild
- Find the public endpoint
- Get around the username / password login screen

Security is key to this software being privacy first, so deciding it's an enterprise-only solution contradicts this messaging, in my opinion. 

Secondly, you talk about control over data. Security is key to control, as if the software isn't secure, anyone can go and delete the data.

Finally, you talk about GDPR and first party tracking. I agree with that whole-heartedly, however, it's also a matter of trust. One could proxy requests to GA / Mixpanel / Amplitude and make it appear first party. So the question becomes is it safer 
for users to use a proxy + secure solution, or PostHog, or PostHog enterprise?

Right now, GA / Mixpanel / Amplitude have you beat on functionality + reliability and most likely trust. What they aren't competing on is the ability to self host, and self hosting is only an option if it's easily secured by design. 

It felt like a bit of an oxymoron to both design an open source alternative to these solutions, whilst having standard security features as an enterprise only option. 

Of course, I'm only one opinion. :-)

**Comment by timgl** [comment]
I've thought about this quite a bit and have changed my mind. I think this should be in the core open source version, for the very reasons you outlined. 

You're running PostHog on Heroku right? Heroku does have a native way of [achieving what you want](https://devcenter.heroku.com/articles/private-spaces). It's also easy to allow/disallow [ip addresses in Nginx](https://support.hypernode.com/knowledgebase/blocking-allowing-ip-addresses-in-nginx/)

I'm in favour of adding instructions on how to do this to docs, rather than supporting more configuration in our main app for now (which we'd have to support and might end up breaking in weird and wonderful ways).

**Comment by dazbradbury** [comment]
@timgl - Yep, I thought about essentially proxying all traffic to enforce these restrictions, and usually that's quite straight forward to set up. Alternatively yes, heroku has private spaces and AWS has security groups that could enforce IP restrictions neatly. 

However, in this case though you'd need one instance that can **only** collect data, from any IP, for the front-end JS code, and a separate instance that can view the data / do the analysis. 

It's possible, but would require essentially splitting the app in two - which I don't think you'd want to do!

In our world we'd generally enforce every action / endpoint to be either public or private (which you do for security anyway), and within that logic would add the IP restrictions if the action is private and IP restrictions are enabled. 

**Edit:** In hindsight we could proxy the JS traffic (thus ensuring it's only collection endpoints being allowed publicly), and IP restrict the app itself via Heroku/AWS/etc. The downside would be if you changed the collection endpoints / naming this would all break so there'd be a dependency there along with the proxying itself which could get complicated for distributed workers. 

If I'm missing something obvious though, and you have a solution in mind that works (ie. nginx config), happy to give it a go!

**Comment by timgl** [comment]
Agree, anything I can come up with would be more complicated than putting this into PostHog itself. I've created a PR for this that'll allow you to define IPs with regex. It's a little simplistic but should do the trick.

**Comment by timgl** [comment]
@dazbradbury This is now done [and documented](https://docs.posthog.com/#/deployment?id=restrict-access-by-ip)

**Comment by dazbradbury** [comment]
Awesome - thanks! Just to confirm, `ALLOWED_IP_BLOCKS `is an environment variable?

**Comment by timgl** [comment]
Yep!

**Comment by dazbradbury** [comment]
I just had a quick test, but seem to be getting blocked even from the single whitelisted IP configured. 

I just had a quick look at the diff, and am wondering if you need to look at the `X-Forwarded-For` / `HTTP_X_FORWARDED_FOR` header? Unless that is set to `REMOTE_ADDR` somewhere else in the stack? 

If it's not, then on a web environment where SSL is terminated at the load balancer the originating IP is put into the `X-Forwarded-For` header, and the load balancer IP is probably what is being caught by `REMOTE_ADDR`. Generally, the way this is handled is that the load balancer *always* writes to the X-Forwarded-For header, and so if that value is set it can be prioritised. 

In most web services I've dealt with, the IP getters / values are normally overwritten by this value to ensure all calls are correct even if `REMOTE_ADDR` is used.

**Comment by dazbradbury** [comment]
@timgl - Any chance you were able to double check my findings above? Or did I just get a config setting wrong?

**Comment by timgl** [comment]
@dazbradbury Yep, we've merged a fix for that. You'll need to set either `TRUSTED_PROXIES=ip1,ip2` or `TRUST_ALL_PROXIES`. If the latter, you need to make sure nginx (or something else) is overriding the x-forwarded-for, otherwise people will be able to spoof the ip address.

**Comment by dazbradbury** [comment]
Awesome thanks - potentially worth pointing out in your docs that by default, Heroku will overwrite anyone attempting to spoof the X-Forwarded-For header: 

https://devcenter.heroku.com/articles/http-routing#heroku-headers

As such, using TRUST_ALL_PROXIES is presumably perfectly safe, if this is all that flag is checking. 

I know it's in the following section of the docs, but it seems you need to also enable: IS_BEHIND_PROXY for this to work. I missed that at first.

Thanks again!

**Comment by timgl** [comment]
Thanks, added!

**Comment by dazbradbury** [comment]
After re-deploying posthog, it seems the endpoint:

`/static/array.js`

Isn't returning due to the IP restriction. But that js is needed for posthog to run on all clients.

**Comment by timgl** [comment]
Doh, of course. That's fixed now
