### ISSUE TITLE
Start writing tests for feature-flagged code

### ISSUE THREAD

**Issue by mariusandra** [PostHog/posthog#5295]
(There might be another issue for this, but I couldn't find it now)

We're the taxonomic filter into the release, and as I implemented code to effectively remove the feature flag (by [forcefully enabling](https://github.com/PostHog/posthog/pull/5273) it for everyone), I also had to quickly [write tests](https://github.com/PostHog/posthog/pull/5282) for cases where the taxonomic filter replaced the old one. 

I also had to adjust a few funnel tests since things had changed now that this flag is also enabled.

The root cause is that there is currently no way to hardcode feature flags into E2E tests. This [`PERSIST_FEATURE_FLAGS`](https://github.com/PostHog/posthog/pull/5273) approach provides a solution:

I propose that when `TEST=1`, we can pass `?__PERSISTED_FEATURE_FLAGS=a,b,c` to any URL, and those will be added to the [`posthog_app_context`](https://github.com/PostHog/posthog/blob/19d9fcc9ed401e1d52ecef5a01566aca63c65c1b/posthog/utils.py#L226) and passed to the frontend like all the other flags.

Then we can use this `?__` via `cy.visit` and enable whatever flags we want for whichever test.

Then when it comes time to merge feature flagged code, we don't have to start with writing tests.

**Comment by macobo** [comment]
Alternatively, we could `cy.intercept` /decide endpoint response and inject the right flags that way. It would make for a nice `given2` variable as well. For example:

```js
describe('with flags turned on', () => {
  given('featureFlags', () => ['foo', 'bar'])

  it('can navigate within trends')`
})
```

 I think this minimizes the app-level changes whilst providing a nice test structure. Win-win?

**Comment by mariusandra** [comment]
That might work as well... however I think we need to get any `/decide` API response then. IIRC, it actually just gave errors when looking at the network tab while running cypress. Maybe I'm mistaken.

For completion, here's one more approach. We could also just try to patch `window.POSTHOG_APP_CONTEXT` on the frontend before any of the other code loads. The app's index.html contains the following:

```
<script>
window.POSTHOG_APP_CONTEXT = {..., "persisted_feature_flags": ["4267-taxonomic-property-filter", "4535-funnel-bar-viz"]}
</script>
```

Though this might be flakey.
