### ISSUE TITLE
Clean up histogram y-axis labels

### ISSUE THREAD

**Issue by alexkim205** [PostHog/posthog#5302]
## Bug description

Clean up y-labels so that gridlines are aligned and long numbers are abbreviated e.g. 5,000 -> 5K

<img width="98" alt="Screen Shot 2021-07-22 at 4 28 05 PM" src="https://user-images.githubusercontent.com/13460330/126721247-07c6374a-2790-41cd-a4c1-8ee25a9726c9.png">

## Expected behavior

Expect y labels to be aligned, not cut off, and abbreviated.

## How to reproduce

1. The new time conversion funnel viz

## Environment

- [X] PostHog Cloud
- [ ] self-hosted PostHog, version/commit: _please provide_

**Comment by marcushyett-ph** [comment]
Micro-nit: if you're making any changes here - can we use the came color scheme (e.g. 
![image](https://user-images.githubusercontent.com/85295485/127199195-099fd547-aa3b-4f74-99ec-7583c1c74b34.png)
)

As we use on the funnels page :)

**Comment by alexkim205** [comment]
Hey Marcus, thanks for the suggestion! there was a discussion on my previous PR [here](https://github.com/PostHog/posthog/pull/5265) where we decided to keep this color different to communicate that these bars weren't actionable. I think it'd be best to change the color to $primary once that functionality is implemented

**Comment by marcushyett-ph** [comment]
Ah great I did not see this discussion... Seems to be well reasoned to keep it the same - thanks for sharing the context :)
