### ISSUE TITLE
Enable `use_uncompressed_cache` clickhouse setting

### ISSUE THREAD

**Issue by macobo** [PostHog/posthog#5307]
## Is your feature request related to a problem?

We should enable `use_uncompressed_cache` clickhouse setting both in cloud and in chart.

From https://clickhouse.tech/docs/en/operations/settings/settings/#setting-use_uncompressed_cache

> Whether to use a cache of uncompressed blocks. Accepts 0 or 1. By default, 0 (disabled).
> Using the uncompressed cache (only for tables in the MergeTree family) can significantly reduce latency and increase throughput when working with a large number of short queries. Enable this setting for users who send frequent short requests. Also pay attention to the uncompressed_cache_size configuration parameter (only set in the config file) – the size of uncompressed cache blocks. By default, it is 8 GiB. The uncompressed cache is filled in as needed and the least-used data is automatically deleted.

> For queries that read at least a somewhat large volume of data (one million rows or more), the uncompressed cache is disabled automatically to save space for truly small queries. This means that you can keep the ‘use_uncompressed_cache’ setting always set to 1.

This seems like a cheap and easy performance win, it's currently disabled in production

## Additional context

Related: #5112 #5244

cc @tiina303 and @fuziontech

**Comment by tiina303** [comment]
Seems like a good idea to me. I did a quick google search to see if there could be any problems with that, seems like there were some in earlier versions but they got fixed & it's been around for a while now, so seems pretty safe too.
