### ISSUE TITLE
Sort infinite list events & properties by popularity

### ISSUE THREAD

**Issue by mariusandra** [PostHog/posthog#5309]
## Is your feature request related to a problem?

We have this new filter:
![image](https://user-images.githubusercontent.com/53387/126775818-c547bec0-626d-439b-8084-f5c8e826cd92.png)

Yet it's complicated to find fields that have meaningful data. 

## Describe the solution you'd like

I'd like the results in the dropdown returned by popularity, at least when no other search filter is in place. So "$browser" and other fields that are sent with most events would be clickable without scrolling through 11365 other properties.

## Describe alternatives you've considered

- Scrolling a lot
- Creating a "all" or "suggested" tab, but what to show there?

## Additional context

One caveat if using popularity-based sorting also when searching (we probably should) is that we should be able to prioritise direct matches. So if you have an event name "a" that has only 3 events, searching for "a" should show that first and "$p**a**geview" with 3 million events only after. Probably. :)

**Comment by paolodamico** [comment]
Recently we added sorting in the backend relying on number of times used in a query and event volume, but a) we need to support this in the frontend too and b) we probably need a stronger heuristic here. For instance, when I type URL in the search box, I get some important results (e.g. PostHog properties or custom-set properties) buried with other system properties or flattened array properties that most of the time are not as relevant.

<img width="584" alt="" src="https://user-images.githubusercontent.com/5864173/127530485-1f242ad7-0704-4c33-8ad9-0af1ec19cb33.png">
