### ISSUE TITLE
Convert various select components to Taxonomic Filter

### ISSUE THREAD

**Issue by mariusandra** [PostHog/posthog#5311]
## Is your feature request related to a problem?

Even though the taxonomic filter is now enabled for most cases, there are still various one-off dropdowns that should be migrated to it. 

For example this events list will surely cause problems for some clients without autocomplete:

![image](https://user-images.githubusercontent.com/53387/126776603-c724a046-4368-453c-bd92-941763cbc65c.png)

## Describe the solution you'd like

1. Map where we are still using the event and property definitions
2. Rewrite all of them to use the taxonomic component
3. Rewrite the event/properties stats pages to support server-side pagination
4. Delete all the old code
5. Remove the code that loads all events/properties, so we don't ever load megabytes of JSON anymore.
6. ???
7. Profit!

## Describe alternatives you've considered

Leaving things as is as it's already better than what was.

**Comment by paolodamico** [comment]
Duplicated
