### ISSUE TITLE
Funnel query cancellation

### ISSUE THREAD

**Issue by mariusandra** [PostHog/posthog#5313]
## Is your feature request related to a problem?

We now have query cancellation on trends. That means if you start a new query when the old one was running, we cancel the `fetch` request, hence, hopefully, triggering Django to abandon the query/connection.

## Describe the solution you'd like

1. Figure out if the cancellation also works well in the backend. Seems to if I look at my debug log, though I haven't checked e.g. if CPU for clickhouse goes down to 0.
2. Figure out a way to add query cancellation also to trends.

## Additional context

Having real funnel query cancellation unlocks:

- Removing the "calculate" button on postgres, as you'll be only running one query at a time.
- Longer running queries (you can say "ok, this time, I know what I'm doing and wait 5 minutes"

The tricky bit is that for trends we make one API request and read its response. For funnels, for historic/performance reasons, we make one request for celery to start calculating the funnel, and then poll periodically to fetch the results. This makes it impossible to implement cancellation as it was done for trends. We'd need to implement some `query_id` system (done), and some way to cancel running celery tasks (ugh?). 

Should we instead switch funnels back to the direct API request <-> response interface?

**Comment by paolodamico** [comment]
This seems like an issue more for Core Analytics Team right? @EDsCODE @neilkakkar

**Comment by neilkakkar** [comment]
It sounds like two separate issues to me:

(1) Cancelling an API request should cancel the query (we don't know yet if this is the case - for both trends & funnels)
(2) Add cancelling support for Funnels.

(1) definitely makes sense for us.
(2): Unsure. With either proposed solution, there will probably be both backend and frontend work to do.

**Comment by paolodamico** [comment]
Makes sense! Though I think the work on the frontend for (2) will be super lightweight, probably just implementing the same logic that we already have for trends, so keeping this as a Core Analytics issue for now and we can work out the frontend part once the backend is ready. Thanks @neilkakkar !

**Comment by Twixes** [comment]
BTW is #4756 now solved (as looks like this is a subset of that)?

**Comment by paolodamico** [comment]
I think #4756 is solved from the frontend perspective? (i.e. we have no confirmation that Django and particularly CH too stop computation if the connection drops) for everything but funnels.
