### ISSUE TITLE
Ant Design Trends Page

### ISSUE THREAD

**Issue by EDsCODE** [PostHog/posthog#532]
**Is your feature request related to a problem? Please describe.**
#531 Trends Page

**Describe the solution you'd like**
Consider the mockups below and decide which to implement for trends page. B will improve readability and viewing of chart by bringing it within screen. Filters may get crowded

**Additional context**
Letters for referencing in conversation

**A**
<img width="1440" alt="Light_Trends_Toolbar_Original" src="https://user-images.githubusercontent.com/13127476/78931762-69ea9e00-7a74-11ea-826e-dde4ed2caea4.png">

**B**
<img width="1440" alt="Light_Trends_Toolbar_Joined" src="https://user-images.githubusercontent.com/13127476/78931846-8c7cb700-7a74-11ea-90b0-5fa86ac079c3.png">

***Thank*** you for your feature request - we love each and every one!

**Comment by timgl** [comment]
I think I much prefer B, both look but also functional: you can change params on the left and see the output on the right, rather than having to scroll down.

This is so so good!

**Comment by jamesefhawkins** [comment]
I also prefer B. I think it feels more intuitive that the controls you're adjusting are editing the graph given it's "in the same block", compared to A where it's in a different visual section of the page.

**Comment by EDsCODE** [comment]
Last bit of redesigning that needs to be done to make this format of trends page work. I'm thinking of wrapping the filters into a token like below and clicking one/clicking add new will provide a dropdown of the current option selectors. This way they'll fit properly along the column. @timgl @jamesefhawkins lmk thoughts and I can go through with the entire page!

**The filters**
<img width="723" alt="Screen Shot 2020-04-13 at 1 36 51 PM" src="https://user-images.githubusercontent.com/13127476/79143837-e8ed1880-7d8b-11ea-8e76-6e3024e66411.png">

**The dropdown upon clicking**
<img width="689" alt="Screen Shot 2020-04-13 at 1 36 58 PM" src="https://user-images.githubusercontent.com/13127476/79143838-e985af00-7d8b-11ea-90e9-46b6c3270421.png">
