### ISSUE TITLE
UX issues with funnel uncalculated state

### ISSUE THREAD

**Issue by paolodamico** [PostHog/posthog#5322]
We have a new "uncalculated"/outdated state to show when a funnel state has changed in Postgres. Some UX issues I found with this implementation:

1. Banner doesn't have great positioning and has confusing copy when on the funnel empty state.

<img width="1296" alt="" src="https://user-images.githubusercontent.com/5864173/126845196-481233c2-3ac3-4a34-acdd-1197120f90ca.png">

2. On a regular state, banner also feels strange. The warning state makes it feel like something is wrong, but this is part of a regular workflow. You can also interact with the elements of the graph (see tooltip). 

<img width="915" alt="" src="https://user-images.githubusercontent.com/5864173/126845467-cb9872af-ad79-4cd1-b13a-3fbc2f77ec9c.png">

Something like what Metabase does could maybe work better? Tagging @clarkus for input too.

<img width="1413" alt="" src="https://user-images.githubusercontent.com/5864173/126845474-2cea7aaa-fb62-4f70-a4bc-9b74b0eef4ec.png">

**Comment by clarkus** [comment]
We shouldn't show the calculation alert when the funnel is invalid. In those cases we should direct the user to configure a valid funnel first. 

I see the need for communicating that the query definition doesn't match the visualization shown, but I don't know how critical the need is. If it is critical, then let's move towards blocking out the visualization area with a prompt to to recalculate. If it is less critical, maybe we can layer this into a broader rework of insight creation as part of https://github.com/PostHog/posthog/issues/3408

In the mockup below I am working on clarifying editing / creation states versus read states. To achieve this I've consolidated the actions that modify the state of the insight into the group at the top. These are all page-level actions. Below that I am communicating if the insight has unsaved changes. In the query builder area, I've made some changes to align insight creation across types. Part of that is a prominent "calculate changes" action. That label can update to reflect the state of the query as well. I am still working on these ideas, but wanted to share another idea for how we could communicate this in a less intrusive way.

![insight-ia-idea](https://user-images.githubusercontent.com/254612/126846508-cd2a24df-a79e-43ae-9c73-e130feab80b0.png)

**Comment by alexkim205** [comment]
> I see the need for communicating that the query definition doesn't match the visualization shown, but I don't know how critical the need is. If it is critical, then let's move towards blocking out the visualization area with a prompt to to recalculate. If it is less critical, maybe we can layer this into a broader rework of insight creation as part of #3408

I really like the non-intrusive "calculate changes" action button in your mockup and it'd be great if we integrate it with the major redesign of insight creation. For now, I think it'll be an easy win to block out the area with a recalculate prompt! I'll put out a PR for this soon—

**Comment by alexkim205** [comment]
Took care of bug 1 already in #5422

https://user-images.githubusercontent.com/13460330/129109144-08ea45fe-6906-4496-8619-07830a1f9ee3.mov

**Comment by alexkim205** [comment]
And bug 2 should be addressed once #5554 is merged
