### ISSUE TITLE
Bug when jumping to sessions from funnel person modal

### ISSUE THREAD

**Issue by paolodamico** [PostHog/posthog#5326]
## Bug description

I have [this funnel](https://app.posthog.com/insights?insight=FUNNELS&date_from=-90d&display=FunnelViz&events=%5B%7B%22id%22%3A%22user%20signed%20up%22%2C%22type%22%3A%22events%22%2C%22order%22%3A0%2C%22name%22%3A%22user%20signed%20up%22%2C%22math%22%3Anull%2C%22math_property%22%3Anull%2C%22properties%22%3A%5B%7B%22key%22%3A%22is_organization_first_user%22%2C%22value%22%3A%5B%22true%22%5D%2C%22operator%22%3A%22exact%22%2C%22type%22%3A%22event%22%7D%5D%7D%2C%7B%22id%22%3A%22first%20team%20event%20ingested%22%2C%22type%22%3A%22events%22%2C%22order%22%3A1%2C%22name%22%3A%22first%20team%20event%20ingested%22%2C%22math%22%3Anull%2C%22math_property%22%3Anull%2C%22properties%22%3A%5B%5D%7D%5D&actions=%5B%7B%22id%22%3A4912%2C%22type%22%3A%22actions%22%2C%22order%22%3A2%2C%22name%22%3A%22Discover%20Learning%20-%20core%20analytics%22%2C%22math%22%3Anull%2C%22math_property%22%3Anull%2C%22properties%22%3A%5B%5D%7D%5D&funnel_window_days=14&interval=day&properties=%5B%7B%22key%22%3A%22id%22%2C%22value%22%3A71%2C%22operator%22%3Anull%2C%22type%22%3A%22cohort%22%7D%5D&date_to&funnel_viz_type=steps#fromItem=130084&fromItemName=Activation%20Funnel&fromDashboard=2298) which is filtered out by our Real Users cohort (ID = 71). When I click on "View details" in the person modal at any given step, these filters are shown (note the incorrect ID filter on the action).

<img width="876" alt="" src="https://user-images.githubusercontent.com/5864173/127006646-5a76b48f-e4e9-4390-ac4b-2cafd3336d53.png">

## Expected behavior

Get the correct filters that lead to the right session list.

## How to reproduce

See above

## Environment

- [X] PostHog Cloud
- [X] self-hosted PostHog, version/commit: _please provide_

## Additional context

Not sure if this should be Core Experience instead of Core Analytics.

**Comment by macobo** [comment]
This bug is not valid at this moment - https://github.com/PostHog/posthog/pull/5040 removed the interconnected feature from people modals completely.

cc @paolodamico @clarkus @liyiy

**Comment by marcushyett-ph** [comment]
Does this feature - (when its working) also link to the correct date from the funnel? Or just filter by the events?

**Comment by paolodamico** [comment]
Actually this bug is still valid. This happens when you click on "View details" in the modal. @clarkus I think the copy of "View details" is causing confusion, might be worth changing.

**Comment by clarkus** [comment]
Any suggestions for a more accurate word to use? You're viewing the specific details of a person and the corresponding sessions (if they exist). Would "view person" be more accurate?

**Comment by paolodamico** [comment]
Hmm well if we let users click on the person name or ID too I think that makes it obvious that clicking there gets you to the person page, and then the button could say View sessions.

**Comment by clarkus** [comment]
Here's an update that addresses that feedback. Also restores the view sessions link. Thoughts?

![person modal - original](https://user-images.githubusercontent.com/254612/128965309-5f29c5e5-b270-41c4-96ee-9aa1a9059f79.png)

**Comment by paolodamico** [comment]
Visually I really like it, but I would challenge us to wait to bring this back until we make some more progress deciding what to do about the sessions page, it might not make sense to have this in the end.
