### ISSUE TITLE
Histogram should show percentages

### ISSUE THREAD

**Issue by paolodamico** [PostHog/posthog#5327]
Our current histogram shows absolute numbers in the y-axis, yet the most important thing you probably want to look at is percentages to get a useful sense of distribution.

<img width="877" alt="" src="https://user-images.githubusercontent.com/5864173/127008470-9011694d-77b5-433e-b177-dc87f994c457.png">

Keeping the absolute numbers might still be helpful, but secondary to percentages.

**Comment by marcushyett-ph** [comment]
I think we probably want to show absolute and %age perhaps we can add %age to the columns?

**Comment by alexkim205** [comment]
Agreed, I think it'd look nice if the way we show absolute and percentages were analogous to our funnel steps graph.

**Comment by alexkim205** [comment]
Related to https://github.com/PostHog/posthog/issues/5302
