### ISSUE TITLE
PostHog using local device time, rather than server time

### ISSUE THREAD

**Issue by dazbradbury** [PostHog/posthog#533]
**Describe the bug**

![image](https://user-images.githubusercontent.com/1332601/78979680-4119e580-7b14-11ea-86fa-644774d07cd2.png)

![image](https://user-images.githubusercontent.com/1332601/78979725-53941f00-7b14-11ea-9535-e67ca37a74bd.png)

**To Reproduce (unconfirmed)**
1. Presumably setting device time to the future
2. Interacting with page
3. Looking at event

**Expected behavior**

An event should never have happened in the future. Using the server time should resolve that.

**Comment by timgl** [comment]
Good find, this happened because [we switched to batching requests in the frontend](https://github.com/PostHog/posthog-js/pull/3) and took users' timestamp at face value.

I think the solution would be instead of sending a full timestamp from the user, just send an offset to when it makes the batching request. On the server, we can then subtract that offset from current server time, with a sensible limit (15 seconds?).

**Comment by timgl** [comment]
That's fixed!

**Comment by dazbradbury** [comment]
@timgl - Seems we're still getting events with timestamps in the future:

![image](https://user-images.githubusercontent.com/1332601/80597528-e2af9b00-8a1f-11ea-8dca-f28355542024.png)

Any idea what the issue could be?

Oddly - it seems to be happen even for a single user. They have recent events intertwined with future dated ones.

**Comment by dazbradbury** [comment]
@timgl - We now have hundreds of future dated events in the event list. Am I best off disabling posthog for now and resetting the DB, or do you think you'd be able to fix the incorrect event data after-the-fact?

**Comment by timgl** [comment]
@dazbradbury It's fairly easy to run a query deleting events in the future, though you'd have to do it continuously. Something like `from posthog.models import Event;from django.utils import timezone;Event.objects.filter(timestamp__gt=timezone.now()).delete()` using Heroku scheduler to run every minute

It is surprising this is still happening. Is it possible there's some aggressive caching somewhere (maybe cloudflare?) that means people still have the old version of the script?

Edit: I've just had a look on your website, caching doesn't seem to be the problem. I will investigate a little further and see if I can find anything

**Comment by dazbradbury** [comment]
Which script being cached would cause a problem here? The inline script tag on the page, or array.js that posthog delivers?

If the former, I don't think so - as the app had stopped receiving events completely before deploying the changes. It was removed from the website for 2 weeks. If we wanted to be sure though we'd need to add some versioning to the API calls into the backend, right?

If the latter, does it make sense to have some cache-busting mechanism on `/static/array.js` to ensure this isn't being cached somewhere along the line?

> Edit: I've just had a look on your website, caching doesn't seem to be the problem. I will investigate a little further and see if I can find anything

Cool ok, thanks!

**Comment by mariusandra** [comment]
@timgl could it be that [this change](https://github.com/PostHog/posthog-js/commit/e48c880ce51631715ee1b6a677bf595abd299081) in posthog-js only covered some of the events the library sends? I think you missed `_handle_unload` for example.

Probably moving the `offset` code to the `_format_event_queue_data` function itself can help... yet I see `_send_request` called from multiple cases around the code.

@dazbradbury is there any pattern you can tell from the types of events that are sent properly and those that aren't? Something like autocapture vs manually defined for example?

**Comment by mariusandra** [comment]
I investigated this more (changed my clock) and it seems that $pageleave and autocaptured events are all sent in the future... and $pageview and other custom events are sent in the present. I'll try to find a solution.

**Comment by dazbradbury** [comment]
> @dazbradbury is there any pattern you can tell from the types of events that are sent properly and those that aren't? Something like autocapture vs manually defined for example?

They are mostly pageleave and autocapture events, as you say. I do have a few examples of $pageview coming up as "in 19 hours",  "in 5 hours", and "in 33 minutes" though. 

I would have thought the only real solution is to never trust the client time and always use the server time (with events passing offsets if they're batched), but am sure you guys will work out a solution! Thanks again!

**Comment by timgl** [comment]
@dazbradbury This is now fixed on master!

**Comment by dazbradbury** [comment]
Awesome thanks - will let some data run in and see how it looks. Appreciate the speedy fix!
