### ISSUE TITLE
Conversion time distribution squished vertically

### ISSUE THREAD

**Issue by marcushyett-ph** [PostHog/posthog#5339]
## Bug description

![image](https://user-images.githubusercontent.com/85295485/127162589-00ab40b5-2694-4b47-9aa0-9d41db7f17b0.png)

Conversion time distribution graph is very short vertically.

## Expected behavior
It should be easy to read, maybe 500px high or something.

## How to reproduce

1. Using safari ![image](https://user-images.githubusercontent.com/85295485/127162589-00ab40b5-2694-4b47-9aa0-9d41db7f17b0.png)
2. Go to any funnel and hit time to convert

## Environment

- [x] PostHog Cloud
- [ ] self-hosted PostHog, version/commit: _please provide_

**Comment by alexkim205** [comment]
Interesting this only happens on Safari. 👀 now
