### ISSUE TITLE
Helpful error state when funnel query fails

### ISSUE THREAD

**Issue by marcushyett-ph** [PostHog/posthog#5340]
## Bug description

When I create a funnel breakdown query that doesn't work for some reason, I see the empty state rather than an error explaining what happened and what I can do to fix it:

![image](https://user-images.githubusercontent.com/85295485/127162928-c8a86158-2615-4fa1-a4c5-ef468686265a.png)

## Expected behavior

I would expect to see an error that says "You cannot break down by this property" or event "An unexpected error occurred", this empty state is really confusing.

## How to reproduce

1. https://app.posthog.com/insights?insight=FUNNELS&properties=%5B%5D&filter_test_accounts=true&events=%5B%7B%22id%22%3A%22%24pageview%22%2C%22name%22%3A%22%24pageview%22%2C%22type%22%3A%22events%22%2C%22order%22%3A0%7D%2C%7B%22id%22%3A%22%24pageview%22%2C%22name%22%3A%22%24pageview%22%2C%22type%22%3A%22events%22%2C%22order%22%3A1%7D%2C%7B%22id%22%3A%22%24pageview%22%2C%22name%22%3A%22%24pageview%22%2C%22type%22%3A%22events%22%2C%22order%22%3A2%7D%5D&actions=%5B%5D&interval=day&new_entity=%5B%5D&funnel_viz_type=steps&display=FunnelViz&breakdown=action_name&breakdown_type=event

## Environment

- [x] PostHog Cloud
- [ ] self-hosted PostHog, version/commit: _please provide_

**Comment by alexkim205** [comment]
Looked into this a bit more, it looks like there is no error being thrown up by the backend here, just an empty result. ~~@neilkakkar or @Twixes do you have an idea why this might be happening?~~ Sorry for the false alarm, this just seems to mean that there're no matching events.

<img width="226" alt="Screen Shot 2021-08-02 at 5 08 55 PM" src="https://user-images.githubusercontent.com/13460330/127938343-6c60eaf7-b8e6-413b-862d-f1d24f03b1e2.png">


This still requires a fix on the frontend, so I'll put out a PR soon. Once we have skeletons (#5411), this empty state should be updated too.
