### ISSUE TITLE
New Plugin: Export person properties as event properties

### ISSUE THREAD

**Issue by neilkakkar** [PostHog/posthog#5343]
## Is your feature request related to a problem?

Some export plugins (like BigQuery) are popular for further querying the data (vs. storing a backup).

For these kinds of export plugins, it makes sense to provide an option for all additional information for querying. Specifically, the `person_id` and `created_at` fields.

Internally, our `person_distinct_id` join solves for this, but this isn't possible externally.

This enables people to run their querying much more simply than trying to join on `$identify` calls / trying to recreate this information using the event stream.

## Describe the solution you'd like

I think this should be a separate plugin that can be run before the actual export (and somehow not modify the event going into PostHog. See open question 3)

## Describe alternatives you've considered

Each export plugin does it on their own

## Additional context

Some open questions:
1. What's the performance impact for gathering this information during ingestion async?
2. Do we actually want to expose this information?
3.  Does it make sense to do it in each export plugin? vs another plugin? There's trade-offs for both, one is an infra/plugin server improvement to allow mix&matching plugins vs continuing existing paradigm and doing it in each export plugin)

### More Context

https://posthog.slack.com/archives/C01F31E9PRD/p1627388867087300

**Comment by neilkakkar** [comment]
There are more complications: What if we have `anonymous` users right now. When the "merge" happens in PostHog, how do you retroactively update this information in the export? (you can't, so need a better solution for it)

Also unsure if every distinct id always has a person_id attached to it from the beginning? That resolves the above issue, since merges append distinct ids, but don't modify the person_id.

**Comment by neilkakkar** [comment]
Also related: Improving how quickly you get meaningful information out of data when exporting. Part of https://github.com/PostHog/product-internal/issues/109

**Comment by andrewm4894** [comment]
> When the "merge" happens in PostHog, how do you retroactively update this information in the export?

Hmm - almost feels like being able to 'hook' into such events in some way via a similar BQ plugin could be cool. So when the "merge" happens in posthog - stream that to BQ as a new event type maybe.

Might all be getting a bit complicated though - I might go back to the drawing board a little on our ETL in BQ to see if i can basically just wrangle it all in BQ.

**Comment by mariusandra** [comment]
Perhaps the simplest solution would be to emit an event whenever a user is merged. This would go to the end of the queue and then be exported as any other event. For example:

```
{ event: "$user_merged", properties: { distinct_id: "bla", "person_id": "xyz", distinct_ids: ["asd", "wr", "sdger", ..., "bla"] } }
```

Alternatively, instead of a new event, we could add these properties to existing `$identify` or `$alias` events. This is actually preferable as it makes it easier to replicate events from one server to another. Otherwise e.g. when using [the replicator plugin](https://github.com/PostHog/posthog-plugin-replicator), you'd get two `$user_merged` events in the target posthog instance (one replicated from the main instance, the other created again on $identify).
