### ISSUE TITLE
Funnel filter text box a little too tight

### ISSUE THREAD

**Issue by marcushyett-ph** [PostHog/posthog#5349]
## Bug description

When I try and add an email filter to the box a reasonably normal length email will force the box to scroll - this is a bit of an frustration when you're typing an email and might have made a mistake earlier on:

![image](https://user-images.githubusercontent.com/85295485/127289131-c74552ed-ee4b-4262-8a89-64dcbbce3043.png)

The same for longish URLs

![image](https://user-images.githubusercontent.com/85295485/127289408-8977fc6f-ffc4-4282-9aed-a202a2677a70.png)

## Expected behavior
Make the text entry box wider to made it easier to use with URLs and emails.

## How to reproduce

1. Go to funnels
2. Select filter
3. Pick a property
4. Start adding text to the final box

## Environment

- [x] PostHog Cloud
- [ ] self-hosted PostHog, version/commit: _please provide_

## Additional context
I'll try and fix this one myself.

**Comment by paolodamico** [comment]
@marcushyett-ph I guess we can close this thanks to your PR?

**Comment by marcushyett-ph** [comment]
Ah yes...I thought there was some kind of auto-close...

**Comment by paolodamico** [comment]
You have to add the word close or fix (pluralised works too) and the issue number in your PR 😉

**Comment by marcushyett-ph** [comment]
Great - thanks for the feedback :)
