### ISSUE TITLE
Session recording deletion settings not working

### ISSUE THREAD

**Issue by liyiy** [PostHog/posthog#5360]
## Bug description

*Please describe.*  
*If this affects the front-end, screenshots would be of great help.*  

Auto retention settings not working on self-hosted postgresql

![image](https://user-images.githubusercontent.com/25164963/127364883-47d7ef57-9ae1-4715-ac91-c3452b67e18b.png)

Additional potential bug:

When session recording is turned off, the data continues to come in until the user reloads

## Expected behavior

Session recordings should delete based on auto-retention settings

## How to reproduce

1. Go to project settings from the left side nav
2. Scroll down to session recordings
3. Change auto-retention settings and wait to see if it deletes after x time

## Environment

- [ ] PostHog Cloud
- [x] self-hosted PostHog, version/commit: _please provide_

**Comment by macobo** [comment]
The bug template is incomplete and context on this is really important here: Is this cloud or self-hosted postgresql?

**Comment by liyiy** [comment]
@joesaunderson Hi Joe! Are you self-hosted postgresql?

**Comment by joesaunderson** [comment]
We are self hosted, Postgres, 1.27.0

**Comment by kappa90** [comment]
Same here, self hosted, Postgres, 1.27.0, just upgraded to the last commit.

We enabled this > 2 weeks ago with autodeletion after 7 days, but we still have sessions months old, and definitely older than 7 days from now.

I can give access to our dashboard and to our sentry, if needed.

**Comment by clarkus** [comment]
Bumping this to see if we can make time for it in an upcoming sprint. It's come up in our [users slack](https://posthogusers.slack.com/archives/C01PPBY3G6Q/p1633352357064500) again today.

**Comment by mariusandra** [comment]
This was merged 18 days ago and should be out in 1.28.1: https://github.com/PostHog/posthog/pull/6006

**Comment by benjackwhite** [comment]
Closing as this is quite outdated
