### ISSUE TITLE
Reconcile Backend and Frontend features for Funnels

### ISSUE THREAD

**Issue by neilkakkar** [PostHog/posthog#5367]
There's some functionality that's available in the backend, but not in the frontend yet. Documenting all obscure / pending things here:

- [ ] #5552
- [ ] #5553
- [x] Custom conversion window sizes
- [ ] ??

cc: @EDsCODE & @macobo if I'm missing something?

**Comment by paolodamico** [comment]
This seems quite important to implement as it's part of our Nailing Funnels and the legwork has been done. @neilkakkar are there docs on this? Happy to pick it up, or @alexkim205 if you can

**Comment by neilkakkar** [comment]
@paolodamico no docs, but happy to write down what params to use inside this issue, if that helps? (or point you to the corresponding `mixins`)

## Orderings

https://github.com/PostHog/posthog/blob/master/posthog/constants.py#L106 - "ordered" (the usual) is the default, and the key is: `funnel_order_type`.

**Important to note**: Orderings can be mixed and matched with visualizations (like trends, time to convert, and steps)

## Excluding events

Just like `actions` and `events`, exclusions introduce the `exclusions` key. Here's an API test demonstrating how this works: https://github.com/PostHog/posthog/blob/master/ee/clickhouse/views/test/test_clickhouse_insights.py#L391

Apart from the regular fields, it accepts `funnel_from_step` and `funnel_to_step` which determines which steps to exclude between. Note that all of these are required params.

For full window exclusion, `funnel_from_step = 0` and `funnel_to_step = <last step>`.

Note that, this allows for exclusions between any two random steps. Up to you if you want to expose this, or consecutive steps only.

## Conversion Window Size

`funnel_window_interval` = size of window. Example: `10`, `7`, `2`
`funnel_window_interval_unit` = unit of window. Example: `minute`, `hour`, `week`.

All possible values: https://github.com/PostHog/posthog/blob/master/posthog/models/filters/mixins/funnel.py#L100

An Example usage: https://github.com/PostHog/posthog/blob/master/ee/clickhouse/queries/funnels/test/test_funnel.py#L238

**Comment by neilkakkar** [comment]
Excluding events isn't possible in some orderings (like `strict`) and only makes sense as full window exclusion (between first and last step) in `unordered`.

**Comment by alexkim205** [comment]
Been meaning to cut something like this, so thanks for making this issue. @paolodamico Do you know if there are mockups for event exclusions? 

In the meantime, I can take on implementing funnel orderings and custom conversion window sizes.

**Comment by clarkus** [comment]
I don't think we have any designs for event exclusions. How do we see this manifesting? Is this literally a new kind of exclusion filter that can apply to a step or an entire query? "Don't show users who did event XYZ between all steps, steps 1 & 2, steps 1 & 4, etc"? Is this exclusion case applicable to any other insight types right now?

**Comment by paolodamico** [comment]
Excellent @alexkim205! Let's figure out the UX for this. FYI for the other tasks in this issue, the latest mockups do show how to display this (e.g. the max time to convert)

Re @clarkus we'll have to test how often users utilize this feature but it's only adding a filter exclusion for the entire funnel, i.e. user didn't do step X at all within step 1 and step n for the funnel. Maybe it makes sense for this to live in the filters section? Wdyt?

**Comment by clarkus** [comment]
@paolodamico agreed on placement. I can put something together for this.

**Comment by clarkus** [comment]
Here's a quick concept for exclusions based on consecutive and non-consecutive steps. Here are my notes on exclusions for this example:

- A funnel can have multiple exclusions. 
- Exclusions can be duplicated or deleted. 
- Exclusions are input in the form of an event parameter and a step range parameter
- A valid step range consists of two step values. The first value must occur earlier in the funnel than the second value. The last step of the funnel cannot be selected for value one. Likewise, step one can't be selected for value two. 

The image below is a quick illustration of how we could collect this information. In one case the user is always selecting a contiguous, 2-step range or the entire funnel.  In the other, the user can select arbitrary steps. I need to think through the validation cases here, but as long as it's a valid range either case should work. 

<img width="880" alt="Screen Shot 2021-07-30 at 3 05 43 PM" src="https://user-images.githubusercontent.com/254612/127716164-9877adf9-5778-4937-807a-4040fd2c48cc.png">

**Comment by Twixes** [comment]
I think this can be closed since there are now separate issues for each specific point here, and they're already being addressed.
