### ISSUE TITLE
Make action text non-case sensitive

### ISSUE THREAD

**Issue by marcushyett-ph** [PostHog/posthog#5369]
## Is your feature request related to a problem?

Action text appears to be case sensitive, which is confusing to some of our users

![image](https://user-images.githubusercontent.com/85295485/127492790-c0661fe2-d9b5-49c5-b5ef-97439ffb724d.png)

## Describe the solution you'd like

Can we make this be made insensitive or be able to toggle it on or off

## Describe alternatives you've considered
Highlight in the UI that this field is case sensitive, to reduce confusion.

**Comment by samwinslow** [comment]
Flyby comment: one good way to implement this would be to use our existing operators, some of which are case-insensitive (`icontains`).
