### ISSUE TITLE
User paths to go beyond three steps

### ISSUE THREAD

**Issue by marcushyett-ph** [PostHog/posthog#5370]
## Is your feature request related to a problem?

When we want to look at a user's behavior beyond the first three steps (to understand why an issue occurred), we're stuck as the diagram only goes this far today.

## Describe the solution you'd like

Can user path data be expanded to more than three steps, or can we click on a step to go further / make it the starting element? 

(Additionally, we've had a request to export the user path data to CSV, but this may be a unique use case.)

## Describe alternatives you've considered
None

**Comment by paolodamico** [comment]
Duplicate of #4933. Closing this as there's already a discussion in the original issue.
