### ISSUE TITLE
Interactive list items (without anchors) cannot be tagged as actions

### ISSUE THREAD

**Issue by marcushyett-ph** [PostHog/posthog#5371]
## Bug description

 <li> tags aren't picked up by the Action toolbar (if you have an anchor inside this is picked up, but without an anchor it doesn't work). We have li-based menus, which is how we noticed. 

## Expected behavior

We should be able to tag interactive list items as actions.

## How to reproduce

1. Open the action toolbar
2. Select an interactive element which has a list item but not an anchor
3. Save action
4. Action is not persisted

## Environment

- [ ] PostHog Cloud
- [ ] self-hosted PostHog, version/commit: _please provide_

**Comment by macobo** [comment]
Q: What is `Select an interactive element which has a list item but not an anchor`? Do you have a concrete example?

Note I think you technically _can_ - it's that the toolbar does not autosuggest the right selectors.

**Comment by marcushyett-ph** [comment]
Sure I should've given an example:

<img width="952" alt="image" src="https://user-images.githubusercontent.com/85295485/127623142-f770c1c1-089e-4b1d-a00a-4221b218ff4a.png">

This interaction opens another menu (in the same page), but its reasonable that it's something you might want to track as part of a funnel.

<img width="851" alt="image" src="https://user-images.githubusercontent.com/85295485/127623324-d40cd2ae-24b1-4d28-ae00-5a16ad170847.png">

e.g. how many people clicked on services and support but didn't find a suitable option to get them the help the require.
