### ISSUE TITLE
Don't enable feature flags by default

### ISSUE THREAD

**Issue by kpthatsme** [PostHog/posthog#5378]
## Is your feature request related to a problem?

When we create a feature flag, it's enabled at 100% by default. Most of the time people create feature flags to do a slow rollout. This default behavior feels conflicting and doesn't encourage the slow rollout use case. 

## Describe the solution you'd like

When a new feature flag is created, default it to off.

## Describe alternatives you've considered

When a new flag is created, default it to on with a 0% roll-out. I think this might be more confusing than the default off setting.

## Additional context

Want to get thoughts before making this change

**Comment by paolodamico** [comment]
I actually had it like this before but it was changed. I believe there was some user context from this. Not sure if it's worth reverting.

**Comment by joesaunderson** [comment]
Hah, I actually did this PR. From https://github.com/PostHog/posthog/issues/4431
