### ISSUE TITLE
Changelog images are rendered way too wide.

### ISSUE THREAD

**Issue by timgl** [PostHog/posthog#538]
**Describe the bug**

It also still links to the old docs

**To Reproduce**
1. 
2. 
3. 

**Expected behavior**

**Screenshots**

**Desktop (optional: please complete the following information):**
 - OS:
 - Browser: 
 - Version: 

**Smartphone (optional: please complete the following information):**
 - Device: 
 - OS: 
 - Browser 
 - Version 

**Additional context**

**Comment by Tannergoods** [comment]
Could this be solved by just saving the sizes of images smaller in media library?

**Comment by timgl** [comment]
Just in the HTML we should set the max image width to 100%

**Comment by timgl** [comment]
This was fixed.
