### ISSUE TITLE
Standardized error formatting for form elements

### ISSUE THREAD

**Issue by clarkus** [PostHog/posthog#5380]
## Is your feature request related to a problem?

Errors happen. We need to put a basic system in place to highlight errors where they occur and to communicate how to recover from them. We do this in a few other patterns (empty states for example) but this one is specific to form elements. 

## Describe the solution you'd like

When an input contains an invalid value or is otherwise preventing the user from progressing, highlight that field and append a meaningful message adjacent to the input describing how to recover. 

## Describe alternatives you've considered

Leaving this alone until more users request a fix

## Additional context

- https://github.com/PostHog/posthog/issues/5066
- https://github.com/PostHog/posthog/issues/3375
- https://github.com/PostHog/posthog/issues/4680

**Comment by marcushyett-ph** [comment]
I know errors are not usually the most thrilling topic, but I'm really excited about this - I feel we don't show errors when we should sometimes and others the errors are there but not obvious.

**Comment by clarkus** [comment]
Here is a basic component pattern for a simple text input. This illustrates multiple parameters for form inputs, but let's focus on the validation portion for this issue. 

When the text input contains a value that doesn't conform to requirements, we will highlight that input via a change to the border color, appending an icon to the input, and a validation message adjacent to the element it describes. 

![Input Pattern](https://user-images.githubusercontent.com/254612/128081538-8266d3cf-1f57-48ae-8a6d-521575a85f6b.png)

This pattern is generally applicable to any form element. The placement of the validation message could vary based on context. Generally, validation messages should indicate why an element doesn't conform and how the user can recover from that state. In the example above, I am illustrating a simple "can't be empty" case.

**Comment by macobo** [comment]
Q: When do the error states get added and removed?

I.e. the error could show up when:
1. User loads the page
2. User focuses the input
3. User types into the input but it's still invalid
4. User has not typed for the past N ms
5. User has defocused the input

This becomes really important yet tricky with something like regex validation: https://github.com/PostHog/posthog/issues/4680

Feedback: For some inputs putting a green border around it when it's mandatory and correct has always warmed my heart. Perhaps we should do the same in e.g. signup?

**Comment by clarkus** [comment]
@macobo great questions. Those are the kind of event triggers that should be more contextual to the value being entered. This issue is mostly to show how we highlight and inform of errors via components and visual hints.

Generally for any validation for forms, we should:
- inform users of requirements up front
- as much as possible, validate before the form is submitted as a request - rely on client side validation to guide correction instead of a server response
- Generally, trigger validation on blur / de-focus is a safe default. It's a clear exit from the field and is generally not disruptive to completing values. 

That said, regex is it's own special thing, so I think the validation solution for that will be more involved and tailored to that scenario. I am going to document that in #4680.
