### ISSUE TITLE
Default to a category with results when filtering by event or property type

### ISSUE THREAD

**Issue by kpthatsme** [PostHog/posthog#5381]
## Is your feature request related to a problem?

Event + property categorization is great (events vs actions, event props vs user props) and a huge improvement over the old behavior of everything being in one list.

## Describe the solution you'd like

If I am typing a property or event name that only exists in one category, surface that one first. Currently you need to notice the property exists in a different category and switch into it.

<img width="757" alt="Screen Shot 2021-07-29 at 12 10 56 PM" src="https://user-images.githubusercontent.com/5965891/127552156-fc767872-cd53-4db9-9f17-da3c1c7976c1.png">

In the above screenshot, it would be preferred to have "Actions" be the active panel.

**Comment by paolodamico** [comment]
Related to #5312, probably worth tackling together.
#4791 is also related, could be done together too.
