### ISSUE TITLE
Funnel breakdown yields empty state

### ISSUE THREAD

**Issue by kpthatsme** [PostHog/posthog#5382]
## Bug description

I have a 2 step funnel that produces data. I applied a breakdown on the current_url event property and was shown the funnel empty state instead of data.

## Expected behavior
I'd expect to see the breakdown data -or- an error message explaining that something went wrong.

## How to reproduce

1. Go to this [chart](https://app.posthog.com/insights?insight=FUNNELS&properties=%5B%5D&filter_test_accounts=true&events=%5B%7B%22id%22%3A%22%24pageview%22%2C%22name%22%3A%22%24pageview%22%2C%22type%22%3A%22events%22%2C%22order%22%3A0%2C%22properties%22%3A%5B%7B%22key%22%3A%22%24current_url%22%2C%22value%22%3A%22https%3A%2F%2Fposthog.com%2Fdocs%22%2C%22operator%22%3A%22icontains%22%2C%22type%22%3A%22event%22%7D%5D%7D%5D&actions=%5B%7B%22id%22%3A%224912%22%2C%22name%22%3A%22Discovered%20Learning%22%2C%22type%22%3A%22actions%22%2C%22order%22%3A1%2C%22properties%22%3A%5B%5D%7D%5D&funnel_viz_type=steps&display=FunnelViz&interval=day&breakdown=%24current_url&breakdown_type=event&new_entity=%5B%5D)

## Environment

- [ ] PostHog Cloud
- [ ] self-hosted PostHog, version/commit: _please provide_

## Additional context

<img width="1375" alt="Screen Shot 2021-07-29 at 2 18 56 PM" src="https://user-images.githubusercontent.com/5965891/127567549-cb624deb-d7f0-49af-bb58-5556d53379ea.png">

**Comment by neilkakkar** [comment]
Looks like UI part is what copy to show on empty results, 

and core analytics part bug: filter inside the step on `current_url` + breakdown on `current_url` borks things.

**Comment by macobo** [comment]
@Twixes are you working on this?

**Comment by Twixes** [comment]
Yup, fix in #5496.
