### ISSUE TITLE
Tables values seemingly unordered

### ISSUE THREAD

**Issue by kpthatsme** [PostHog/posthog#5383]
## Bug description
Looking at a chart of values broken down in a table, the results look to be unordered.

## Expected behavior
I'd expect a table breakdown to have similar behavior to a values breakdown - i.e. they are shown in order of highest to lowest. 

At the very least, a way to sort the results so the maximum values show up first. 

## How to reproduce

1. Go to this [table chart](https://app.posthog.com/insights?insight=TRENDS&interval=day&actions=%5B%5D&events=%5B%7B%22id%22%3A%22%24pageview%22%2C%22name%22%3A%22%24pageview%22%2C%22type%22%3A%22events%22%2C%22order%22%3A0%2C%22properties%22%3A%5B%7B%22key%22%3A%22%24current_url%22%2C%22value%22%3A%22https%3A%2F%2Fposthog.com%2Fdocs%2F%22%2C%22operator%22%3A%22icontains%22%2C%22type%22%3A%22event%22%7D%5D%2C%22math%22%3A%22total%22%7D%5D&filter_test_accounts=true&new_entity=%5B%5D&breakdown=%24current_url&breakdown_type=event&properties=%5B%7B%22key%22%3A%22%24current_url%22%2C%22value%22%3A%22https%3A%2F%2Fposthog.com%2Fdocs%22%2C%22operator%22%3A%22icontains%22%2C%22type%22%3A%22event%22%7D%5D&display=ActionsTable) - observe the total counts aren't ordered in anyway.
2. View the [same chart by values](https://app.posthog.com/insights?insight=TRENDS&interval=day&actions=%5B%5D&events=%5B%7B%22id%22%3A%22%24pageview%22%2C%22name%22%3A%22%24pageview%22%2C%22type%22%3A%22events%22%2C%22order%22%3A0%2C%22properties%22%3A%5B%7B%22key%22%3A%22%24current_url%22%2C%22value%22%3A%22https%3A%2F%2Fposthog.com%2Fdocs%2F%22%2C%22operator%22%3A%22icontains%22%2C%22type%22%3A%22event%22%7D%5D%2C%22math%22%3A%22total%22%7D%5D&filter_test_accounts=true&new_entity=%5B%5D&breakdown=%24current_url&breakdown_type=event&properties=%5B%7B%22key%22%3A%22%24current_url%22%2C%22value%22%3A%22https%3A%2F%2Fposthog.com%2Fdocs%22%2C%22operator%22%3A%22icontains%22%2C%22type%22%3A%22event%22%7D%5D&display=ActionsBarValue) and the results are ordered 

## Environment

- [ ] PostHog Cloud
- [ ] self-hosted PostHog, version/commit: _please provide_

**Comment by macobo** [comment]
cc @paolodamico something for core-experience?

**Comment by paolodamico** [comment]
Indeed I do think it makes a ton of sense to have these sorted descending.
