### ISSUE TITLE
Funnel dragging doesn't work anymore

### ISSUE THREAD

**Issue by timgl** [PostHog/posthog#539]
**Describe the bug**

**To Reproduce**
1. 
2. 
3. 

**Expected behavior**

**Screenshots**

**Desktop (optional: please complete the following information):**
 - OS:
 - Browser: 
 - Version: 

**Smartphone (optional: please complete the following information):**
 - Device: 
 - OS: 
 - Browser 
 - Version 

**Additional context**

**Comment by timgl** [comment]
In fairness, I did remove this as it was super buggy....

**Comment by EDsCODE** [comment]
closing in favor of #1237
