### ISSUE TITLE
PostHog toolbar doesn't make AND / OR clear

### ISSUE THREAD

**Issue by jamesefhawkins** [PostHog/posthog#54]
The toolbar for defining Actions doesn't make two things clear:

* When you create multiple inputs (Text / Selector / Only match if URL contains) in one Action - they are AND statements
* When you combine multiple match groups to one Action - they are OR statements.

I think the easiest way to do this quickly for now is to put an 'info' icon, that pops up and provides this information for more detail.

**Comment by timgl** [comment]
![image](https://user-images.githubusercontent.com/1727427/75820987-43896280-5d52-11ea-8079-aa765c15e09c.png)
I like the way we do this in Cohorts. Just a subtle OR between the two
