### ISSUE TITLE
Add DAUs as a default DashboardItem

### ISSUE THREAD

**Issue by timgl** [PostHog/posthog#540]

**Comment by BElluu** [comment]
@timgl Hi Tim,
I'm newbie here, so  could you expand on the DAU abbreviation?
Thank you! :)

**Comment by jamesefhawkins** [comment]
Daily Active Users. For example, when it’s applied to the trends graphs, it is the unique number of visitors that carried out that action. In this case, we would show the number of unique visitors over time as a default graph on the homepage of the app.

**Comment by timgl** [comment]
This was done^
