### ISSUE TITLE
Sprint 1.28.0 1/2 - July 30 to Aug 13

### ISSUE THREAD

**Issue by fuziontech** [PostHog/posthog#5401]
Support hero: Neil + Yakko

Last Sprint: https://github.com/PostHog/posthog/issues/5168

**Comment by macobo** [comment]
# Core-analytics

Eric is out on friday - we'll do in-depth planning Monday. 

We tenatively agreed on focusing on:

1. Solve data issues that have been pointed out:
2. Get failure rates down significantly for funnels.
3. Get failure rates down everywhere else
4. Improve performance

See more info on why/first thoughts here: https://github.com/PostHog/product-internal/issues/122

@macobo 
- Get materialized columns live

@neilkakkar 
- #5341 

@EDsCODE 
- figure out root of this problem and if it's still occurring https://github.com/PostHog/product-internal/issues/114
- make some grafana dashboards around out of sync persons or multiple merged persons
- funnel breakdown cohort bugs

@Twixes 
- #5161 
- #5382 

All:
- Work through list of bugs on the core analytics project

Updating later in the day

**Comment by fuziontech** [comment]
# Infra & Deployments

team: @fuziontech @tiina303
Please see guidelines in PostHog/posthog#4589

All issues with more details on our [board](https://github.com/orgs/PostHog/projects/10)

## Priorities

#### Clickhouse deployments for everyone

- [ ] P0: Email blast about Clickhouse self-hosted deployments being available (collaborating with Charles, Tim? ; target: 21. July)
- [ ] P0: GCP marketplace 1-click deploy (James, blocked on Google atm)
- [ ] P1: Clickhouse password to not be hardcoded and public (Tiina)
- [ ] P1: Update posthog.com Self-Host section (Tiina)

#### Performance for Core Analytics

- [ ] P0: Cloud performance improvements (James)

#### Misc

- [ ] P0: Migrate Kafka from Heroku to AWS (James)
- [ ] P0: Split ingress for chart two services App and Events (Tiina)
- [ ] P1: "Too many connections" clickhouse pool error (Tiina)
- [ ] P1: SOC2 Requirements (Tiina)
- [ ] P2: Set up NAT Gateway for posthog cloud (James)

**Comment by paolodamico** [comment]
### Core Experience

Board is up-to-date https://github.com/orgs/PostHog/projects/9. For context, this is the epic with all the context on why focus on nailing quality and what sort of issues we're focusing on, #5375 
<img width="964" alt="" src="https://user-images.githubusercontent.com/5864173/127675760-a84aecbf-41e8-41c1-801e-3ecc8eee3db9.png">

**Comment by yakkomajuri** [comment]
## Extensibility Retro

I was support hero the second week. Still managed to get quite a bit done.

### Highlights

From the updated list, everything got done:

- Figured out CH duplicate distinct IDs (the bulk of my time was spent doing this)
- Updated the Snowflake plugin to a point that it is now fully ready for usage by T*S* (+ support to them and other users of the plugin)
- Started talks with Snowplow about an integration

And some additional tasks got accomplished:

- https://github.com/PostHog/plugin-server/pull/519 ⭐ 
- https://github.com/PostHog/posthog/pull/5452
- https://github.com/PostHog/plugin-server/pull/524
- https://github.com/PostHog/posthog/pull/5448 
- https://github.com/PostHog/posthog-js/pull/264
- https://github.com/PostHog/plugin-server/pull/523
- https://github.com/PostHog/plugin-server/pull/527
- https://github.com/PostHog/posthog-js/pull/263

**Comment by samwinslow** [comment]
Growth
===

Joe on holiday, Phil + Kunal out today.

This is all copied from https://github.com/PostHog/product-internal/issues/133. We were going to focus on:

Sam
- Launching email gate signup experience
- Launching MVP of multi variant feature flags; looks like this is something we may build out further.

Phil
- Try 1-click Digital Ocean deploy and provide feedback
- Help hire a developer educator

Eli
- Finish up handbook
- Hopefully close the external link ticket with everyone happy at the end
- Tackle some of our glaring SEO problems using ScreamingFrog
- Get a PR in for allowing multiple author links on blog posts

Cory
- Finish dropdown designs in new, simplified aesthetic
- Wire up new website section for case studies, other types of content
- First draft of product feature detail page template (stretch)

**Comment by Twixes** [comment]
Completed.
