### ISSUE TITLE
Top level saved insights - all insights page

### ISSUE THREAD

**Issue by liyiy** [PostHog/posthog#5402]
Implementation of all/your insights display for #3408 

![image](https://user-images.githubusercontent.com/25164963/127694172-2ad92936-4474-466e-bd5a-d10ed3333841.png)

![image](https://user-images.githubusercontent.com/25164963/127694149-55740ac6-6cdd-4aba-9081-2d4bc226c94c.png)

**Comment by paolodamico** [comment]
This is done, iterated and shipped!
