### ISSUE TITLE
UX bugs in time to convert view

### ISSUE THREAD

**Issue by paolodamico** [PostHog/posthog#5405]
While working on the time to convert graph I found three bugs/improvements to address.

1. When you have a number of bins that exceeds the available width, it's not clear that you can scroll to see more results. Any suggestions @clarkus ?

![image](https://user-images.githubusercontent.com/5864173/127705185-f3da7db9-d4f7-41e9-bc01-4564087b8bc7.gif)

2. For some reason, when I added a ton of bins, the first axis ticks are not painted.

<img width="705" alt="" src="https://user-images.githubusercontent.com/5864173/127705257-825627ac-f245-489a-ad5a-3d1ee4cd60b0.png">

**Comment by clarkus** [comment]
Scrollbars would be one of the best and easiest ways to indicate scrolling. This treatment can vary based on the user's browser and operating system, so generally deferring to that standard is best (go with default scroll bars). 

Depending on the width of the chart, we might also consider some kind of jump link or action that would take you to the next area. This would work as long as the action doesn't bypass other information in the chart. It's almost like a pagination scenario. I tried to illustrate the idea here... imagine the bordered area as a viewport for the full chart and the semi-opaque area as the histogram chart. 

<img width="651" alt="Screen Shot 2021-07-30 at 1 05 55 PM" src="https://user-images.githubusercontent.com/254612/127706254-b82d53f2-6a4f-4d2e-89d3-8471930f1da8.png">

The illustration above is an extreme case. If a user has to scroll excessively to see the full histogram, that's just not going to be a great experience. If there are multiple "viewport" areas worth of histogram, we will need to change the visualization to show more bars in the available area, or expand the area to reveal more of the chart. Did that make sense? Happy to jump on a call if it helps clarify.

**Comment by paolodamico** [comment]
100% on the scrollbars, think it's just a matter of enabling it for macOS when not on by default. I think adding that indicator can be quite helpful too, we can add it and measure how much usage we get out of it.

**Comment by paolodamico** [comment]
Based on priority, I think it's worth moving this to the backlog. @alexkim205 please do let me know if you disagree.

**Comment by paolodamico** [comment]
Not prioritizing for 1.31.0 2/2 due to the very low volume usage of this feature ([source](https://app.posthog.com/insights/NSul0zKU/edit?insight=TRENDS&actions=%5B%7B%22id%22%3A%2210784%22%2C%22name%22%3A%22Discoveries%22%2C%22type%22%3A%22actions%22%2C%22order%22%3A0%7D%2C%7B%22id%22%3A%2210784%22%2C%22name%22%3A%22Discoveries%22%2C%22type%22%3A%22actions%22%2C%22order%22%3A1%2C%22properties%22%3A%5B%7B%22key%22%3A%22funnel_viz_type%22%2C%22value%22%3A%5B%22time_to_convert%22%5D%2C%22operator%22%3A%22exact%22%2C%22type%22%3A%22event%22%7D%5D%7D%5D&events=%5B%5D&display=ActionsLineGraph&funnel_to_step=1&funnel_viz_type=time_to_convert&exclusions=%5B%5D&funnel_from_step=0&new_entity=%5B%5D&properties=%5B%7B%22key%22%3A%22insight%22%2C%22value%22%3A%5B%22FUNNELS%22%5D%2C%22operator%22%3A%22exact%22%2C%22type%22%3A%22event%22%7D%5D&date_from=-30d&interval=week))
