### ISSUE TITLE
Frontend build slow

### ISSUE THREAD

**Issue by marcushyett-ph** [PostHog/posthog#5409]
## Problem description

It takes a long time to build and rebuild the frontend, which I found a bit frustrating but probably also hurts developer productivity.

Setup:
- Digital Ocean Droplet Ubuntu
- 4v CPU, 8GB memory
- Running docker-compose.dev.yml - for all services

Initial build:
`General output time took 3 mins, 28.77 secs`

Incremental build (1 character change):
`General output time took 21.74 secs`

## Solutions proposed

I'm going to test out a few solutions and report-back on this issue.

1. Run on local environment or speed up docker - I feel there's probably some potential to speed up the build here - by not using docker or by speeding up the build in docker

2. Upgrade to Webpack 5 (and enable persistent caching) - I gave this a brief test and it seems to be much faster - will investigate further

3. Apply Webpack optimizations - we can run parallel threads and other optimizations to speed up the build

**Comment by mariusandra** [comment]
@marcushyett-ph - is this turbo enough now?

**Comment by marcushyett-ph** [comment]
Unbeatable!
