### ISSUE TITLE
Allow removing / adding breakdown values in Funnels UI

### ISSUE THREAD

**Issue by neilkakkar** [PostHog/posthog#5428]
## Bug description

Now that we're consistent with breakdown values: https://github.com/PostHog/posthog/issues/5341, 

A new weirdness appears: https://app.posthog.com/insights?insight=FUNNELS&properties=%5B%5D&filter_test_accounts=true&events=%5B%7B%22id%22%3A%22%24pageview%22%2C%22name%22%3A%22%24pageview%22%2C%22type%22%3A%22events%22%2C%22order%22%3A0%7D%2C%7B%22id%22%3A%22%24pageview%22%2C%22name%22%3A%22%24pageview%22%2C%22type%22%3A%22events%22%2C%22order%22%3A1%7D%5D&actions=%5B%5D&interval=day&new_entity=%5B%5D&funnel_viz_type=steps&display=FunnelViz&date_from=dStart&breakdown=%24device&breakdown_type=event

Say, I want to analyse breakdowns, but most of these values are `None`:

![image](https://user-images.githubusercontent.com/7115141/128006821-8879e3b0-f478-4b9f-a5ff-50222079015c.png)

Would be nice if I can just remove this from the graph to focus on the rest, like we allow in Trends.

**Comment by paolodamico** [comment]
An intermediate option could be to enable to hide the "None"/null option, but definitely think is worth having this. CC @alexkim205 in case is something that's aligned with what you're currently working on

**Comment by neilkakkar** [comment]
I don't think that quite solves the problem: Since it may be "Chrome" that has the biggest slice, and not "None".

Also, judging by the code, since we already have this functionality for trends, the work required for either option seems equivalent?

**Comment by clarkus** [comment]
The solution documented at https://github.com/PostHog/posthog/issues/5230 has metric toggling built into the table below the funnel. This could be a simple way to disable less-valuable breakdown options.

**Comment by alexkim205** [comment]
Thanks everyone for the discussion. I can take this on under the "nail the rest of funnels" initiative this week.
