### ISSUE TITLE
Experiment - Send people to funnels by default?

### ISSUE THREAD

**Issue by kpthatsme** [PostHog/posthog#5437]
#### Idea
Now that we're just about finished nailing funnels, should we start funneling (heh) users to the funnel chart instead of trends by default when they click Insights?

#### Concerns:
- This might get annoying for experienced users that are used to today's behavior.
  - it's quite nice to be able to add events to a chart directly and then hop over to the funnel view 
- Right now trends loads with an event auto-populated if you have event data - we probably wouldn't autoload anything for funnels. 

#### Pros:
- We've invested a ton in funnels and it's a more friendly and polished experience than trends.
- I feel like people _may_ grasp the concept and see the value of a funnel conversion rate more easily than a trends chart.

Thoughts on this @paolodamico @marcushyett-ph ?

**Comment by paolodamico** [comment]
Think it's worth a shot! I'm a bit concerned that funnels are not as useful when you're a new user as trends might be, but let's see.

I would also like to avoid running this experiment for a lot of existing users as I do think it can be alienating.

**Comment by kpthatsme** [comment]
> I would also like to avoid running this experiment for a lot of existing users as I do think it can be alienating.

Yea - this is the biggest drawback IMO -  I think it would be more odd to start training some users that funnel are first and not the others. 

Maybe we should just keep as-is...if we shipped something, we'd basically be trying to address the drop-off from 
the [last two steps in this funnel](https://app.posthog.com/insights?insight=FUNNELS&properties=%5B%5D&filter_test_accounts=true&events=%5B%7B%22id%22%3A%22first%20team%20event%20ingested%22%2C%22name%22%3A%22first%20team%20event%20ingested%22%2C%22type%22%3A%22events%22%2C%22order%22%3A1%7D%2C%7B%22id%22%3A%22insight%20viewed%22%2C%22name%22%3A%22insight%20viewed%22%2C%22type%22%3A%22events%22%2C%22order%22%3A2%2C%22properties%22%3A%5B%7B%22key%22%3A%22insight%22%2C%22value%22%3A%5B%22TRENDS%22%5D%2C%22operator%22%3A%22exact%22%2C%22type%22%3A%22event%22%7D%5D%7D%2C%7B%22id%22%3A%22insight%20viewed%22%2C%22name%22%3A%22insight%20viewed%22%2C%22type%22%3A%22events%22%2C%22order%22%3A3%2C%22properties%22%3A%5B%7B%22key%22%3A%22insight%22%2C%22value%22%3A%5B%22FUNNELS%22%5D%2C%22operator%22%3A%22exact%22%2C%22type%22%3A%22event%22%7D%5D%7D%5D&actions=%5B%7B%22id%22%3A2671%2C%22name%22%3A%22User%20Signed%20Up%22%2C%22type%22%3A%22actions%22%2C%22order%22%3A0%7D%5D&funnel_viz_type=steps&display=FunnelViz&interval=day&new_entity=%5B%5D) – if we want everyone to use funnels

**Comment by paolodamico** [comment]
Hmm yeah, seeing it in this light I think we can do other things to better optimize conversion here. For instance, having some prompts that take you from trends to funnels at the right moment.

**Comment by kpthatsme** [comment]
> Hmm yeah, seeing it in this light I think we can do other things to better optimize conversion here. For instance, having some prompts that take you from trends to funnels at the right moment.

Right that's a good idea and I think probably more of the approach we should take here than something as big as changing the default - closing this out!

**Comment by marcushyett-ph** [comment]
I know this is now closed, but I think it would be valuable if we could drive people who haven't tried out the new funnels experience yet to give it a go... something like https://www.appcues.com

Where we have a new icon and a message that explains what we've done with funnels, could help ensure we're funneling people to at least be aware of what we've done with funnels.

**Comment by paolodamico** [comment]
Yeah! I've scheduled some time next week to take a look at this and think about how we can showcase these new features better.

**Comment by paolodamico** [comment]
Yeah! I've scheduled some time next week to take a look at this and think about how we can showcase these new features better.

**Comment by marcushyett-ph** [comment]
Sounds great - excited for this.
