### ISSUE TITLE
Funnel trends has duplicate date on X-Axis

### ISSUE THREAD

**Issue by kpthatsme** [PostHog/posthog#5455]
## Bug description

If you go to [this chart](https://app.posthog.com/insights?insight=FUNNELS&date_from=2021-01-01&date_to=2021-08-04&display=ActionsLineGraph&events=%5B%7B%22id%22%3A%22user%20signed%20up%22%2C%22type%22%3A%22events%22%2C%22order%22%3A0%2C%22name%22%3A%22user%20signed%20up%22%2C%22math%22%3A%22dau%22%2C%22math_property%22%3Anull%2C%22properties%22%3A%5B%5D%7D%5D&actions=%5B%7B%22id%22%3A4912%2C%22type%22%3A%22actions%22%2C%22order%22%3A1%2C%22name%22%3A%22Discovered%20Learning%22%2C%22math%22%3A%22dau%22%2C%22math_property%22%3Anull%2C%22properties%22%3A%5B%5D%7D%5D&filter_test_accounts=true&funnel_viz_type=trends&interval=month#fromItem=191545&fromItemName=Activation%20Rate%3A%20Sign%20Up%20to%20Discover%20Learning&fromDashboard=3020) - you'll see two entries for Jan 2021 and May 2021 on the X-axis.

## Expected behavior

The x-axis should only contain unique dates.

## How to reproduce

1. Go to [this chart](https://app.posthog.com/insights?insight=FUNNELS&date_from=2021-01-01&date_to=2021-08-04&display=ActionsLineGraph&events=%5B%7B%22id%22%3A%22user%20signed%20up%22%2C%22type%22%3A%22events%22%2C%22order%22%3A0%2C%22name%22%3A%22user%20signed%20up%22%2C%22math%22%3A%22dau%22%2C%22math_property%22%3Anull%2C%22properties%22%3A%5B%5D%7D%5D&actions=%5B%7B%22id%22%3A4912%2C%22type%22%3A%22actions%22%2C%22order%22%3A1%2C%22name%22%3A%22Discovered%20Learning%22%2C%22math%22%3A%22dau%22%2C%22math_property%22%3Anull%2C%22properties%22%3A%5B%5D%7D%5D&filter_test_accounts=true&funnel_viz_type=trends&interval=month#fromItem=191545&fromItemName=Activation%20Rate%3A%20Sign%20Up%20to%20Discover%20Learning&fromDashboard=3020) - observe two instances of 1-Jan-2021 and 1-May-2021
2.
3.

## Environment

- [ ] PostHog Cloud
- [ ] self-hosted PostHog, version/commit: _please provide_

## Additional context

This is blocking some slides we want to present at the next board meeting (next week) - so would appreciate a quick fix!

**Comment by neilkakkar** [comment]
Ouch assumptions: https://github.com/PostHog/posthog/blob/master/posthog/queries/base.py#L91

**Comment by Twixes** [comment]
Fixing this rn (sorry I forgot to assign myself).

**Comment by kpthatsme** [comment]
@neilkakkar 🤯 good find
