### ISSUE TITLE
Filter/Breakdown Funnels by User/Event Properties (like Trends)

### ISSUE THREAD

**Issue by jeremynevans** [PostHog/posthog#546]
**Is your feature request related to a problem? Please describe.**
I can only view funnels across all users, but I need to segment to only certain users.

**Describe the solution you'd like**
"Filters" and "Break down by" dropdowns on the Funnels page, just like on the Trends page.

**Describe alternatives you've considered**
Defining filters on the Actions themselves but it seems this isn't possible.

**Additional context**
Unlike trends, this may need to focus more on user properties than event properties? Unsure...

***Thank*** you for your feature request - we love each and every one!

**Comment by Tannergoods** [comment]
This could be aligned with #169 if we can create cohorts from funnels (this is how Amplitude does this) by directly clicking the funnel - creating a cohort that matches the logic.) In the screenshot example this would create a cohort of users who have followed the action order homepage view - sign up - paid all time. this would also need #565 to be able to select order which we can't currently do in cohorts. 

![Posthog](https://user-images.githubusercontent.com/60791437/79215793-067db900-7e44-11ea-95b0-36f7c95f2692.png)

**Comment by jamesefhawkins** [comment]
I think the intention here is the reverse so I'd argue the above is a separate ticket. Being able to add a filter to the funnel that just shows users from a (pre-made) cohort, NOT to create a cohort from the funnel.

That said, it's obviously a nice intuitive way to create a cohort from the visualization.

**Comment by Tannergoods** [comment]
Agreed I will create a separate ticket

**Comment by EDsCODE** [comment]
After this, the funnels page and the trends page will have very similar editors. However, the one major difference UX wise is the `save funnels` button you need to press on the funnels page vs the automatic reload on trends page. Thoughts on whether we should keep them distinct or raise a ticket to change this?

**Comment by timgl** [comment]
Are you suggesting making Funnels a part of /trends? So you'd have "Actions & Events", "Sessions" and "Funnels"?

I'd definitely be in favour of that. We now already store the definition of a funnel as a "Filter" object as well so that should be an easy change.

I guess the big difference between funnels and the rest is that you can permanently store funnels so we would need to be able to do that "and give the 'funnel' a name.

The reason for the save button is that funnels load so slowly, it's kind of annoying to change 1 thing and then feel like you have to wait 10 seconds for it to load before you can change another thing

**Comment by EDsCODE** [comment]
Yeah, let me think about if we should merge it and if so, how to do this smoothly. One more clarification is that on a breakdown of funnels, should we display x number of funnels depending on the property values so if we were to breakdown by browser, the user would receive funnelviz and funnelpeople for chrome, safari, firefox, etc side by side?

**Comment by timgl** [comment]
[The library we use for the funnel visualisation](https://github.com/greghub/funnel-graph-js) allows you to have multiple properties, which would be a cool way of visualising that. This might push this PR to be a little chunky so could be worth splitting this out into separate PRs/tickets
