### ISSUE TITLE
Inspect users in Lifecycle not working with filters

### ISSUE THREAD

**Issue by himanshu-sikaria** [PostHog/posthog#5466]
## Bug description

In the Lifecycle view, if a filter is applied, clicking on the graph to see the user list gives 0 results. The same works if no filter is applied.
![image](https://user-images.githubusercontent.com/29571087/128355792-bd3de294-fba3-454a-afaf-21314760df8b.png)

## Expected behavior
Get the list of users on clicking on the graph

## How to reproduce

1. Go to the lifecycle view
2. Apply a filter on host
3. Click on the bar graph to get the user list

## Environment

- [ ] self-hosted PostHog, version/commit: release-1.27.0

**Comment by macobo** [comment]
@himanshu-sikaria thanks for the bug report!

Another clarifying question: Are you using clickhouse or postgres?

**Comment by himanshu-sikaria** [comment]
Hi @macobo -  this is postgres

**Comment by thomasgrastein** [comment]
I'm having the same issue for all insights. If I add a filter based on the event properties (such as Path Name), the graph will successfully show the correct amount, but upon inspecting no users will be returned.

Steps to reproduce
Create new Trend based on Pageview > Add filter > Path Name = "/" > Click at any point on the graph (where there should be users)

**Comment by EDsCODE** [comment]
Internal [link](https://app.posthog.com/insights?insight=TRENDS&interval=day&events=%5B%7B%22id%22%3A%22user%20signed%20up%22%2C%22name%22%3A%22user%20signed%20up%22%2C%22type%22%3A%22events%22%2C%22order%22%3A0%2C%22math%22%3A%22dau%22%2C%22properties%22%3A%5B%7B%22key%22%3A%22%24geoip_country_name%22%2C%22value%22%3A%5B%22Russia%22%5D%2C%22operator%22%3A%22exact%22%2C%22type%22%3A%22event%22%7D%5D%7D%5D&filter_test_accounts=false&display=ActionsBarValue&compare=false&actions=%5B%5D&new_entity=%5B%5D&properties=%5B%5D&date_from=-14d) example for trends

**Comment by EDsCODE** [comment]
This seems to work fine now on clickhouse backed queries. However, there's currently a high risk of memory erroring on the query if too many filters are applied. (For internal users, try applying our test account filter)
