### ISSUE TITLE
Time to Convert Query Failing

### ISSUE THREAD

**Issue by marcushyett-ph** [PostHog/posthog#5471]
## Bug description

I'm trying to find out the time between signup and discovered learnings

https://app.posthog.com/insights?insight=FUNNELS&properties=%5B%5D&filter_test_accounts=true&events=%5B%7B%22id%22%3A%22first%20team%20event%20ingested%22%2C%22name%22%3A%22first%20team%20event%20ingested%22%2C%22type%22%3A%22events%22%2C%22order%22%3A1%7D%5D&actions=%5B%7B%22id%22%3A2674%2C%22name%22%3A%22User%20Signed%20Up%20(Comprehensive)%22%2C%22type%22%3A%22actions%22%2C%22order%22%3A0%7D%2C%7B%22id%22%3A4912%2C%22name%22%3A%22Discovered%20Learning%22%2C%22type%22%3A%22actions%22%2C%22order%22%3A2%7D%5D&interval=day&new_entity=%5B%5D&date_from=-30d&funnel_viz_type=time_to_convert&display=FunnelViz

But the query is failing to complete

## Expected behavior

I would expect to see the time to convert graph

## How to reproduce

1. https://app.posthog.com/insights?insight=FUNNELS&properties=%5B%5D&filter_test_accounts=true&events=%5B%7B%22id%22%3A%22first%20team%20event%20ingested%22%2C%22name%22%3A%22first%20team%20event%20ingested%22%2C%22type%22%3A%22events%22%2C%22order%22%3A1%7D%5D&actions=%5B%7B%22id%22%3A2674%2C%22name%22%3A%22User%20Signed%20Up%20(Comprehensive)%22%2C%22type%22%3A%22actions%22%2C%22order%22%3A0%7D%2C%7B%22id%22%3A4912%2C%22name%22%3A%22Discovered%20Learning%22%2C%22type%22%3A%22actions%22%2C%22order%22%3A2%7D%5D&interval=day&new_entity=%5B%5D&date_from=-30d&funnel_viz_type=time_to_convert&display=FunnelViz

## Environment

- [x] PostHog Cloud
- [ ] self-hosted PostHog, version/commit: _please provide_

## Additional context

cc: @neilkakkar @alexkim205

**Comment by neilkakkar** [comment]
Yes, our bad with a recent unrelated change, will check again if this happens once [the fix for that one](https://github.com/PostHog/posthog/runs/3253023228) is in.

**Comment by neilkakkar** [comment]
Is ok now :) (still slow though - but doesn't error out like before)

**Comment by marcushyett-ph** [comment]
Thanks for sorting @neilkakkar  :)
