### ISSUE TITLE
Average time to convert is Zero on Funnel breakdowns

### ISSUE THREAD

**Issue by marcushyett-ph** [PostHog/posthog#5472]
## Bug description

When I breakdown a funnel the average time to convert becomes Zero.

<img width="494" alt="image" src="https://user-images.githubusercontent.com/85295485/128362707-a1fee16d-0ff3-4689-abc3-9c2557ca3ec0.png">

## Expected behavior

I would expect it to be the same as before it was broken down.

## How to reproduce

1. https://app.posthog.com/insights?insight=FUNNELS&properties=%5B%5D&filter_test_accounts=true&events=%5B%7B%22id%22%3A%22first%20team%20event%20ingested%22%2C%22name%22%3A%22first%20team%20event%20ingested%22%2C%22type%22%3A%22events%22%2C%22order%22%3A1%7D%5D&actions=%5B%7B%22id%22%3A2674%2C%22name%22%3A%22User%20Signed%20Up%20(Comprehensive)%22%2C%22type%22%3A%22actions%22%2C%22order%22%3A0%7D%2C%7B%22id%22%3A4912%2C%22name%22%3A%22Discovered%20Learning%22%2C%22type%22%3A%22actions%22%2C%22order%22%3A2%7D%5D&interval=day&new_entity=%5B%5D&date_from=-30d&funnel_viz_type=steps&display=FunnelViz&breakdown=%24browser&breakdown_type=person
## Environment

- [x] PostHog Cloud
- [ ] self-hosted PostHog, version/commit: _please provide_

## Additional context
cc: @neilkakkar  @liyiy

**Comment by macobo** [comment]
@neilkakkar what are your thoughts on hiding it vs fixing it?

**Comment by marcushyett-ph** [comment]
I'm cool with hiding it btw - it's just confusing being 0 - the time conversion is not super relevant to the breakdown.

**Comment by neilkakkar** [comment]
Just checked, the backend does send conversion times for each of the steps within the breakdown (which I guess powers the tooltip's details on conversion time per breakdown).

There's no one right value to choose for overall conversion time here, cool with hiding it as well!

**Comment by paolodamico** [comment]
Alright so this is actually a frontend issue, I'll pick this up

**Comment by macobo** [comment]
@paolodamico there's already a linked PR for hiding this :)

**Comment by paolodamico** [comment]
Oops, missed it! Thanks @macobo
