### ISSUE TITLE
Time range bug in stickiness graph

### ISSUE THREAD

**Issue by paolodamico** [PostHog/posthog#5481]
## Bug description

Check out [this graph](https://app.posthog.com/insights?insight=STICKINESS&date_from=2021-05-10T00%3A00%3A00%2B00%3A00&events=%5B%7B%22id%22%3A%22%24pageview%22%2C%22type%22%3A%22events%22%2C%22order%22%3A0%2C%22name%22%3A%22%24pageview%22%2C%22math%22%3Anull%2C%22math_property%22%3Anull%2C%22properties%22%3A%5B%5D%7D%5D&interval=day&properties=%5B%7B%22key%22%3A%22id%22%2C%22value%22%3A71%2C%22operator%22%3Anull%2C%22type%22%3A%22cohort%22%7D%2C%7B%22key%22%3A%22%24current_url%22%2C%22value%22%3A%22www.posthog.com%22%2C%22operator%22%3A%22not_icontains%22%2C%22type%22%3A%22event%22%7D%2C%7B%22key%22%3A%22%24current_url%22%2C%22value%22%3A%22https%3A%2F%2Fposthog.com%22%2C%22operator%22%3A%22not_icontains%22%2C%22type%22%3A%22event%22%7D%2C%7B%22key%22%3A%22%24current_url%22%2C%22value%22%3A%22localhost%22%2C%22operator%22%3A%22not_icontains%22%2C%22type%22%3A%22event%22%7D%2C%7B%22key%22%3A%22%24current_url%22%2C%22value%22%3A%22127.0.0.1%22%2C%22operator%22%3A%22not_icontains%22%2C%22type%22%3A%22event%22%7D%2C%7B%22key%22%3A%22%24current_url%22%2C%22value%22%3A%220.0.0.1%22%2C%22operator%22%3A%22not_icontains%22%2C%22type%22%3A%22event%22%7D%5D&shown_as=Stickiness&display=ActionsLineGraph#fromItem=181606&fromItemName=Test%20stickiness&fromDashboard=2320) saved on a dashboard. According to the graph, the time range it's being shown is for 7 days, yet the graph is showing 90 days.

![image](https://user-images.githubusercontent.com/5864173/128438863-81b3b2cd-d3e0-48e5-adbb-dc2d85946a84.jpeg)

## Expected behavior

The graph's actual time range and the configured time range should match.

## How to reproduce

1. Open the graph linked above.

## Environment

- [X] PostHog Cloud
- [ ] self-hosted PostHog, version/commit: _please provide_

#### *Thank you* for your bug report – we love squashing them!

**Comment by liyiy** [comment]
How did you get to that page btw? I can see there's a param in there `date_from=05/...` which is probably why it shows 90 days

**Comment by mariusandra** [comment]
This is fixed, the graph show to me: 
![image](https://user-images.githubusercontent.com/53387/136956109-a798fc5d-588c-4840-abe7-cadd15855c01.png)

It had a hardcoded date in the filter.
