### ISSUE TITLE
Cohort breakdown queries either fail or return no results

### ISSUE THREAD

**Issue by marcushyett-ph** [PostHog/posthog#5487]
## Bug description

I've been trying to breakdown by funnel by cohorts but I either get no results:
https://app.posthog.com/insights?insight=FUNNELS&properties=%5B%5D&filter_test_accounts=true&events=%5B%7B%22id%22%3A%22first%20team%20event%20ingested%22%2C%22type%22%3A%22events%22%2C%22order%22%3A1%2C%22name%22%3A%22first%20team%20event%20ingested%22%7D%5D&actions=%5B%7B%22id%22%3A2674%2C%22type%22%3A%22actions%22%2C%22order%22%3A0%2C%22name%22%3A%22User%20Signed%20Up%20(Comprehensive)%22%7D%2C%7B%22id%22%3A4912%2C%22type%22%3A%22actions%22%2C%22order%22%3A2%2C%22name%22%3A%22Discovered%20Learning%22%7D%5D&funnel_viz_type=steps&display=FunnelViz&interval=day&breakdown=%5B238%5D&breakdown_type=cohort&new_entity=%5B%5D

Or the query Errors:
https://app.posthog.com/insights?insight=FUNNELS&properties=%5B%5D&filter_test_accounts=true&events=%5B%7B%22id%22%3A%22first%20team%20event%20ingested%22%2C%22type%22%3A%22events%22%2C%22order%22%3A1%2C%22name%22%3A%22first%20team%20event%20ingested%22%7D%5D&actions=%5B%7B%22id%22%3A2674%2C%22type%22%3A%22actions%22%2C%22order%22%3A0%2C%22name%22%3A%22User%20Signed%20Up%20(Comprehensive)%22%7D%2C%7B%22id%22%3A4912%2C%22type%22%3A%22actions%22%2C%22order%22%3A2%2C%22name%22%3A%22Discovered%20Learning%22%7D%5D&funnel_viz_type=steps&display=FunnelViz&interval=day&breakdown=%5B33%5D&breakdown_type=cohort&new_entity=%5B%5D

## Expected behavior
This is an awesome feature - so would love it if we were returning results more often and not failing - would be great to just understand why this is failing and whether or not we could filter out certain cohorts that are likely to not work - so people don't waste their time trying breakdowns which cannot work.

## How to reproduce

Links above

## Environment

- [x] PostHog Cloud
- [ ] self-hosted PostHog, version/commit: _please provide_

**Comment by neilkakkar** [comment]
For (1): I see that we return the data, so sounds like a frontend bug:

![image](https://user-images.githubusercontent.com/7115141/128510817-9e008f62-7c7c-4e01-aec3-63bacbd7d649.png)

(2) is definitely on us!

**Comment by neilkakkar** [comment]
(2): Looks like the cohort is empty, now to figure out why that borks things up for us 👀

**Comment by marcushyett-ph** [comment]
Also might make sense to filter/grey-out empty cohorts in the list as well
as fixing the backend.

**Comment by EDsCODE** [comment]
found the issue. working on a fix

**Comment by EDsCODE** [comment]
The second query should work now. It's returning empty but that's because there's no one in that cohort

**Comment by marcushyett-ph** [comment]
Great thanks

**Comment by marcushyett-ph** [comment]
@alexkim205 @liyiy @paolodamico would be awesome if someone could take a look at the front-end bug for this issue? Data is coming through but not rendering.

Also it would be amazing if we could prevent people from trying to do breakdowns on empty cohorts (perhaps we can give the size of the cohort in the dropdown - or just filter out) @clarkus any thoughts?

**Comment by paolodamico** [comment]
Definitely, adding this to our list! Will pick it up if no one else can.

Re empty cohorts, I think hiding them will lead to confusion. How about visually marking these cohorts (maybe grayed out and/or a warning icon) and not letting them filter on it.

**Comment by neilkakkar** [comment]
I think Eric's latest PR is for this^: https://github.com/PostHog/posthog/pull/5495

**Comment by clarkus** [comment]
I think communicating cohort counts make sense. Is there any concern about dynamic cohorts? Those counts are calculated as they're used, so a zero-count cohort might not always be available? I think it's a good idea, but I'd need a better understanding of how those counts are calculated and specifically when they're calculated.
