### ISSUE TITLE
Cohort Save and Download Not showing up on funnels

### ISSUE THREAD

**Issue by marcushyett-ph** [PostHog/posthog#5488]
## Bug description

When I use trends, on the persons modal I get the mega-cool feature to download the data and or create a cohort:

<img width="627" alt="image" src="https://user-images.githubusercontent.com/85295485/128510004-7fa002e3-bae9-40e4-96f6-0442928e9d9d.png">

However I do not get these awesome features on Funnels (where they'd be even more valuable):
<img width="603" alt="image" src="https://user-images.githubusercontent.com/85295485/128510119-5ca29005-50cf-4edd-b317-7138fb2eb8d6.png">

## Expected behavior
I would expect to see the save as CSV and create cohort button on every persons modal

## How to reproduce

1. Go to funnels
2. Click on the number next to where it says dropped off on a step
3. See persons modal without these capabilities

## Environment

- [x] PostHog Cloud
- [ ] self-hosted PostHog, version/commit: _please provide_

**Comment by macobo** [comment]
Converting this to `enhancement` - this purposefully doesn't work yet, good thing to be building out in "diagnosing causes". :)

**Comment by marcushyett-ph** [comment]
Ah cool - we should definitely prioritize for our next milestone...

@macobo is there any context in another ticket about the effort required to solve this?

**Comment by macobo** [comment]
Don't think so - I think it's not more complicated than existing work, if just _different_ :) Let's put it in the spotlight and execute!

**Comment by camerondeleone** [comment]
+1 for this, [this](https://app.hubspot.com/contacts/6958578/deal/5299227476/) potential enterprise client called this feature out.
