### ISSUE TITLE
API: /event/ can take properties for filter, but this info missed in doc

### ISSUE THREAD

**Issue by maximmarakov** [PostHog/posthog#550]
This request return valid list of events.
```python
resp = s.get(url, verify=False, auth=HTTPBasicAuth('my@login.ru', '123'),
        params = {'properties': '{"group":"a"}'}
)
```
But in https://app.posthog.com/redoc/#operation/event_list param "properties" not exist
![image](https://user-images.githubusercontent.com/36736392/79101778-b985de00-7d82-11ea-9d9e-3d89c3f92c74.png)

**Comment by Twixes** [comment]
We now have entirely different docs, so closing.
