### ISSUE TITLE
Improve behavior in "empty" (array) filters

### ISSUE THREAD

**Issue by macobo** [PostHog/posthog#5503]
## Is your feature request related to a problem?

Throughout Posthog, users can filter datasets in the relatively same way everywhere - you select a property and set a value.

However underneath, the values are (mostly) treated as arrays. Users can add and remove them, which leads to weird and behavior bugs when users remove values from filters or breakdowns.

Some of these issues are:

1. It looks broken
![image](https://user-images.githubusercontent.com/148820/128612089-e755afc5-281d-4c1d-a37e-94d9afd3ce01.png)
![image](https://user-images.githubusercontent.com/148820/128612209-7c575bb4-d134-4eba-a6da-57a1d4c34758.png)

2. It behaves inconsistently: In trends/funels, when filtering by empty event/person removing the last value no results are returned
3. It behaves inconsistently: In trends/funnels, when filtering by "Element" removing the last value a 500 is returned https://github.com/PostHog/posthog/issues/5501

## Describe the solution you'd like

One consistent behavior that makes sense for the user.

IMO removing the last value (unless user adds another) should behave as if user removed the filter. If the user re-adds the value before closing the popover the filter gets re-added.

This is more in-line with how I think about this filter, and removes both the inconsistent and buggy-seeming behavior

## Describe alternatives you've considered

Always returning no results.

## Additional context

cc @clarkus @paolodamico Mind adding it to your teams backlog? :)

**Comment by macobo** [comment]
Moving comments from https://github.com/PostHog/posthog/issues/5501

@paolodamico wrote:

> Thanks for raising this @macobo! Definitely a quick fix is having this follow the already existing behavior, but do agree that rethinking the UX here makes a lot of sense. So first of all, I think having empty values makes sense in certain contexts, e.g. `my_prop = ""` could be something you want to filter for, so we should properly support this (one thing to consider is we might actually want to treat empty strings and nil values as matches here. Even when this happens, I think we could add a small info/warning icon next to the filter where we explain what's going on and suggest alternative approaches (e.g. the user might actually be looking for "is set" option).

> For the cases when an empty filter makes no sense (i.e. particularly when selecting a list of options), we could show a clear warning that this filter is invalid and completely ignore it (i.e. don't send it to the BE). 

<img width="858" alt="" src="https://user-images.githubusercontent.com/5864173/128648274-d2c9a571-730a-43b3-9e60-dc15f54d4ae7.png">

> Thoughts? @macobo @clarkus

**Comment by macobo** [comment]
> So first of all, I think having empty values makes sense in certain contexts, e.g. my_prop = "" could be something you want to filter for, so we should properly support this (one thing to consider is we might actually want to treat empty strings and nil values as matches here.

So there's empty strings and there's empty (value arrays). All equals/not equals etc filters use arrays and this issue is talking about the array-based ones, we can disregard this case.

> For the cases when an empty filter makes no sense (i.e. particularly when selecting a list of options), we could show a clear warning that this filter is invalid and completely ignore it (i.e. don't send it to the BE).

This wouldn't work with the current filters UX - IMO it's very confusing when a auto-running system switches to suddenly not running things - user might not notice a tiny warning icon.

But based on the screenshot you'd solve this after we've completely revamped the filtering UX?

**Comment by clarkus** [comment]
This feels like an extension of https://github.com/PostHog/posthog/issues/5380 to me. We want to show meaningful errors for the current context. If a user has selected a property and operator that support / expect an array value, we should show an error state when that value field is empty. 

The messaging is going to be the difficult part in this context because it is difficult to know user intent. How would we direct this user to recover? They might be wanting to filter based on an array value, or they might have just used the wrong operator. They could select at least one value for the filter, or they might be better served with a "not set" operator.

**Comment by paolodamico** [comment]
Agreed, a clear error message in that case sounds like the way to go. Maybe just something like you need to enter a value for this type of filter? If we have more space, we can add something like change the filter type if you're looking for something else.

**Comment by clarkus** [comment]
I think guiding completion for the operator that was selected is probably the best course of action. "Value cannot be empty" would be sufficient. I was also working on an alternate error pattern for these tighter, rule-building forms. I think we can still use the placement of the icon we have for other forms, but show the error message on hover instead. That would keep the form tight and still highlight the element where the error occurred. 

<img width="445" alt="Screen Shot 2021-08-10 at 8 18 33 AM" src="https://user-images.githubusercontent.com/254612/128893690-b49367a1-09b9-4968-a490-efe5bd6b246c.png">
