### ISSUE TITLE
Session recording engagement improvements

### ISSUE THREAD

**Issue by paolodamico** [PostHog/posthog#5507]
This (and relevant context) was initially brought up by @joethreepwood on https://github.com/PostHog/product-internal/issues/127.

We've had feedback that session recording is an attractive feature to new users, but also that **the experience isn't keeping users engaged**. Feedback from a specific user: "Anything that summarizes is good. There's not enough time to watch them all."

**This issue is intended as discussion for potential solutions on how to improve engagement for this feature. How can we enable users to keep coming back?**

Part of "Shore-up Session Recording" theme from Diagnosing causes milestone (#5506)

**Comment by paolodamico** [comment]
Potential approach suggestion by @joethreepwood:

> Notifications. The feedback I've heard around session recording is that users like the idea of it, but they engage with it less and less over time. Why? They don't want to trawl through all videos and they don't otherwise know when an event worth looking at has occurred. Alerting users that noteworthy events have occurred (e.g. an event was repeated X time, a rageclick occurred, etc.) would bring them back to the specific content they want and show them a specific cause.

**Comment by macobo** [comment]
I think the answer needs to be more "first-principles" here - our sessions page (which drives session recordings) bad and we don't know the proper use-case for it. Essentially https://github.com/PostHog/posthog/issues/4884

While we can improve engagement here by "polishing" and adding features, unless we know what and for whom we're building we're kind of polishing a turd and making it harder to make large changes. :) Focussing on auxilary features just makes it seem like we're making progress when we're not.

**Comment by paolodamico** [comment]
100% agreed! I just wanted to open this issue to document the discussion we have around this, but we definitely need to figure out the role of session recordings first. Will update once I have more context on that.
