### ISSUE TITLE
Can we set up branched funnels with optional steps?

### ISSUE THREAD

**Issue by marcushyett-ph** [PostHog/posthog#5515]
## Is your feature request related to a problem?

Imagine I have a simple e-commerce funnel:
- View Product
- Add to Cart
- Checkout

However for certain products e.g. alcohol we have an additional step so our funnel will look like this
- View Product
- Add to Cart
- Age Verification
- Checkout

Since, age verification is only required for a subset of products, I don't want checkout to always require age verification to be counted as a conversion, essentially I want it to operate a bit like this pseudo query / code:

`Successful Checkout Out Users = SUM(DISTINCT IF(product_type = Alcohol AND age_verificatied = true, user_id, null)) + SUM(DISTINCT IF(product_type != Alcohol, user_id, null)))`

## Describe the solution you'd like
Super-flexible on the solution - perhaps there's a way we can do something using unordered steps and our existing funnels without building anything new, I'm just not quite sure how.

@neilkakkar @macobo would love to hear your thoughts.

## Describe alternatives you've considered
Having multiple funnels - but this can get complicated and confusing quite quickly if you have more than one optional step.

**Comment by neilkakkar** [comment]
Trying to grasp the problem better: What question does this analysis solve?

Initial impression for the problem feels to me like: I'm the e-commerce site owner, and I expect conversion for alcohol to be lower apriori, so this is me trying to encode the information into the funnel beforehand - which feels kindof wrong, since you should be using the funnels to discover things, not to seek 101 ways to confirm what you already believe.

**Comment by jredl-va** [comment]
@neilkakkar while that is a true statement, if I can't measure the conversion rate accurately of the funnel that requires age verification how can I explore making tweaks adjustments to it?

Note that as a user I'm not trying to confirm what I already believe (and know to be true). I'm trying to accurately measure the optional funnel steps and make improvements to it within the context of the entire funnel that doesn't negatively impact both pathways.

**Comment by Twixes** [comment]
Based on this example only, I would say this would work better if the branching was already handled instrumentation-side, e.g. by replacing condition-based "Checkout" / "Age Verification"+"Checkout" with a single "Verified Checkout". Ex post facto analysis-side branching would pretty quickly get messy UX-side, regarding both setup and understanding results. What do you think?

**Comment by jredl-va** [comment]
Some thoughts from mixpanel that from a competitive analysis may be worth while to review: 

- https://help.mixpanel.com/hc/en-us/articles/360057520772
- https://community.mixpanel.com/ideas/be-able-to-capture-two-funnels-in-one-3484

**Comment by paolodamico** [comment]
@Twixes while your approach can indeed be one way to solve the problem (or alternatively creating two separate funnels), I think we could potentially explore coming up with a better solution for this. This seems like a strong part of figuring out different types of funnels. UX can definitely be tricky but I'm sure we can figure it out. Perhaps you mark this step as optional, and then in addition to giving you overall conversion for the funnel, we give you conversion based on this optional step.

**Comment by neilkakkar** [comment]
Hmm, @jredl-va - thanks for responding!

So, to rephrase, you want to measure conversion rate of the funnel that requires age verification, right? This is the second funnel Marcus mentioned. The problem becomes how do you reconcile this with the first funnel, or make changes to the second funnel without negatively impacting the first.

We know that we can create both funnels separately today. So then, the specific problem that this feature solves, is visualising both of these together? Is this correct?

---

Judging by @paolodamico 's comment, there seems to be a bit more to it. But I'm not quite clear what that is yet? Thoughts?

**Comment by paolodamico** [comment]
I believe you're right @neilkakkar. We can technically build both funnels today separately, the proposal is consider optimising to be able to show it as a single funnel. 

I think one important consideration is how this affects our work on diagnosing causes. It could be that it potentially helps you optimise your funnel with optional steps swiftly or it could also be the case that this will be just too complex / confusing or even lead to extrapolated and wrong conclusions.

**Comment by neilkakkar** [comment]
If we're looking for visualising different paths between steps, maybe this ties better into https://github.com/PostHog/posthog/issues/5342 and https://github.com/PostHog/posthog/issues/4806 ?

Specific to the example in this issue, if we want to visualise what's going on in between steps, perhaps it makes sense to look at everything then? That is, something like a sankey diagram between funnel steps, showing how people make it from "Add to Cart" to "Checkout". A part of this would then be "Age verification".

This sidesteps the problem I mentioned earlier about knowing apriori what you want to see. 

The above is just an example of how we might solve the visualisation challenge. Where I'm getting to is: If it's a visualization challenge, then we shouldn't try to solve it by adding functionality to the base funnel. It's a _different_ kind of problem.

**Comment by marcushyett-ph** [comment]
Great call @neilkakkar... I can definitely see a more comprehensive Sankey diagram being an effective way to visualize this - we should keep this context in mind during our next milestones when we invest in this area.

**Comment by paolodamico** [comment]
Some context from another focus customer [in this thread](https://posthog.slack.com/archives/C01F31E9PRD/p1629207219034800). This intuitively comes up again as initially suggested by @jredl-va, having a funnel where user can take steps 1 -> 2 -> 3 -> 4 or 1 -> 2 -> 4, but step 4 shows few or no results because most users didn't complete step 3. 

Another interesting idea would be if we can detect these optional steps when users are unaware of them and suggest marking them as optional?

@neilkakkar as a next step I think it's worth deciding if this is something we want to prioritize and work with @clarkus to figure out the solution for this as a lot of the details will come from how we implement the UI here. Thoughts? CC @marcushyett-ph

**Comment by marcushyett-ph** [comment]
Pondering on this a little, I wonder if a good solution here might be leveraging paths but fixing the start and end (and possibly intermediate steps), this will filter down to only the relevant funnel - but will highlight any "optional steps" and their performance, without them being explicitly defined.

**Comment by clarkus** [comment]
> Another interesting idea would be if we can detect these optional steps when users are unaware of them and suggest marking them as optional?

I was working on this a bit yesterday in https://github.com/PostHog/posthog/issues/5552#issuecomment-899846995. I had a question about mixed modes where each step could be evaluated as sequential, strict, or any. This might be a way to introduce optional steps? There would still be more work to be done to update the visualization to clarify which steps are optional to the funnel.

**Comment by fluidsonic** [comment]
Hey everyone,

What's the status of this? Having a funnel with optional steps is so common and crucial to understanding drop-offs.

**Comment by PrinceCarter** [comment]
> Hey everyone,
> 
> What's the status of this? Having a funnel with optional steps is so common and crucial to understanding drop-offs.

+1

**Comment by brandonmcconnell** [comment]
we too could really benefit for first-class support for branched conversion funnels 🙏🏼
