### ISSUE TITLE
Significant performance issues with funnels on Postgres

### ISSUE THREAD

**Issue by paolodamico** [PostHog/posthog#5519]
## In what situation are you experiencing subpar performance?

An incredibly helpful user today, shared this experience on funnels taking way too much time and resources (exact numbers TBC) to execute with me after upgrading to 1.27 (**Postgres**). User reported event volume is pretty small (exact numbers coming soon).

- Even at a 7-day time range leads to quite a few timeouts.
- After the funnel effectively times out (client seems to stop polling), we show the empty state message ("Enter your funnel details and click 'calculate' to create a funnel visualization"). _Unsure if this is an error we fixed recently for Postgres too._
- Postgres memory usage starts hovering at around 20%
    ![image](https://user-images.githubusercontent.com/5864173/128773220-5e99d3e5-2f81-4302-b50d-60c611f3a5a0.png)
- Deep diving into the funnel queries reveals that query takes 12 minutes to complete.
- Seems like the bottleneck is CPU usage on the instance.
- Had similar issues since 1.24 but 1.27 made it more frequent and more evident.

## How to reproduce

See above.

## Environment

- [ ] PostHog Cloud
- [X] self-hosted PostHog, version/commit: 1.27 on Postgres

## Additional context

This seems like a huge blocker on Postgres, even if we start considering deprecating Postgres usage, this might be one of those things to actually address. Thoughts? @macobo @neilkakkar @EDsCODE

**Comment by macobo** [comment]
@paolodamico mind putting me in touch with the user in users slack? Would love to take a look and debug this, but this might require a bigger dataset or access I don't have :)

**Comment by paolodamico** [comment]
Done!

**Comment by paolodamico** [comment]
Problem reported by [another user](https://posthogusers.slack.com/archives/CT7HXDEG3/p1628586998045600), funnels not loading in the insights page.
