### ISSUE TITLE
Who are the top users of $feature

### ISSUE THREAD

**Issue by macobo** [PostHog/posthog#5524]
## Is your feature request related to a problem?

When diagnosing causes or figuring out what to do with a $feature it's important to understand who and why are they using it. 

One way to gain an understanding is to go and reach out to users who are using a feature actively - it probably fits well within their workflow and they likely have good insights to share.

(It's also worthwhile to reach out to users who _don't_ use a feature for a full perspective)

## Describe the solution you'd like

Allow to take an insight/trend and output who are the top users for it.

Note: We could also add this as something we show under toolbar or actions creation flow :)

## Describe alternatives you've considered

Going through people modal and counting manually.

## Additional context

We could use this internally for figuring out who to reach out to.

cc @paolodamico @marcushyett-ph - There might be a fit for "diagnose causes" here.

**Comment by Twixes** [comment]
So basically making the people modal an insight of its own?

**Comment by macobo** [comment]
Person modal does not answer this question since usage count is not a property we show there :)

Not sure what the right solution is, it _might_ be adding it to the modal or it might be something else.

EDIT: I realized you can kind of do this by breaking down by e.g. user email and then selecting "by value" - leaving this up though, maybe we can expose this better?
