### ISSUE TITLE
Crash analysis

### ISSUE THREAD

**Issue by fire** [PostHog/posthog#554]
**Is your feature request related to a problem? Please describe.**
When my game engine app crashes I want to run a pipeline that gets the c++ / scripting language stack trace and aggregate it for analysis. 

**Describe the solution you'd like**

I personally want something like sentry, but was wondering if using posthog to build this "rest upload api" would be doable.

**Describe alternatives you've considered**

* https://github.com/getsentry/sentry
* https://registry.gitlab.com/glitchtip/glitchtip-frontend:master
* https://github.com/acrisci/simple-breakpad-server

**Additional context**

https://github.com/godotengine/godot/pull/22778

**Comment by timgl** [comment]
Interesting!

Is the problem you're trying to solve something like "I want to know which users have had errors, and what they did after that"? In that case, you could send an event (`error` or something) to PostHog, with the stacktrace as JSON in the properties. This will obviously be much less detailed than Sentry so you'd still want to have that installed as well.

I can also definitely see an integration with Sentry here. When Sentry fires, you also send an event to PostHog with the Sentry ID that we can then link to.

**Comment by fire** [comment]
The problem is that the application is for example a few hundred megabytes, the data needed to generate the stack trace is like 1 gigabyte uncompressed debug files aka symbols from less than 512 kilobyte dump.

(Edited) There's also a stack similarity between events. You can probably run text similarity or a row based comparison. Each row is a stack frame. Functionality for comparing events may already exist.

The second problem is I'm trying to see where PostHog fits, because trying to do everything mediocre is a bad direction too and doing crash analytics is a pivot.

The third problem is Sentry is not opensource.

**Comment by timgl** [comment]
Thanks for the context. I think you're right, we're probably not willing to go quite as deep as what you're looking for. I'll leave this ticket open as I do think there's some interesting stuff to be done here, of combining what users are doing with whether they're getting any errors or not.

**Comment by paolodamico** [comment]
We now have a Sentry integration
