### ISSUE TITLE
PostHog toolbar continually asks for domains to be authorized

### ISSUE THREAD

**Issue by jredl-va** [PostHog/posthog#5541]
## Bug description

After sometime away from a page the posthog toolbar will continually ask for users to authorize the page. However, the page is already authorized.

![image](https://user-images.githubusercontent.com/2300103/129045577-aef0e13d-be93-4cc8-ad62-880742a61f5e.png)

![image](https://user-images.githubusercontent.com/2300103/129046020-beedb99d-f8f9-45b0-b5e8-e59e64f46173.png)

This is leading to many different and unwanted urls being added to our projects. 

## Expected behavior

- The toolbar doesn't prompt users to authorize pages when the domain is already authorized. 
- The toolbar doesn't prompt users to authorize pages when the url is not recognized (we have a white labeled platform and the posthog toolbar is disrupting normal navigation)

OR

- As we have a white labeled platform start with the toolbar open a permitted domain
- Switch contexts to a different customer that has a different domain and the toolbar will prompt you to add it

Both are completely undesired as the user loses context of the entire page as the posthog toolbar has completely taken over the browser session!

## How to reproduce

1. Have the posthog toolbar open on a previously authorized page
2. Leave the tab idle for some period of time
3. Resume navigation of the application and the tool bar incorrectly prompts for authorization again

## Environment

self-hosted PostHog, version/commit: sha256:872d9429f19d7a297384c47f633e683f2b46e412cac2b83c5b1b2f50fdbd2ca6

**Comment by yakkomajuri** [comment]
As per Slack, is this only happening when you switch projects?
