### ISSUE TITLE
The toolbar popup and the tool bar panel within project settings are malformed with many domains

### ISSUE THREAD

**Issue by jredl-va** [PostHog/posthog#5542]
## Bug description

When there are many domains added to the toolbar settings the domains that exceed the page size are malformed in the panel. Only the "add new" url link is displayed. 

![image](https://user-images.githubusercontent.com/2300103/129047285-6f57420e-83cf-437c-a097-156fb3f5dd5d.png)

In order to display the edit / delete buttons one must click the panel to left off the "add new" icon to have those icons correctly displayed. 

![image](https://user-images.githubusercontent.com/2300103/129047710-3a3d00d0-06a2-415e-a6ba-f91de0e61532.png)

## Expected behavior

The toolbar popup and panel within project settings correctly renders when there are many domains or when you load more  domains.

## How to reproduce

1. Add domains until the panel stops rendering correctly
2. We are seeing this behaviour in many projects

## Environment

- [ x ] self-hosted PostHog, version/commit: sha256:872d9429f19d7a297384c47f633e683f2b46e412cac2b83c5b1b2f50fdbd2ca6

**Comment by yakkomajuri** [comment]
Thanks for reporting!
