### ISSUE TITLE
Improve UX for opening the floating Action window

### ISSUE THREAD

**Issue by dknowles-vsk** [PostHog/posthog#5544]
## Is your feature request related to a problem?
We train many teams within our organization on how to use PostHog. One of the most consistent stumbling blocks is that it isn't clear how to open and close the Action window:

![Screen Shot 2021-08-11 at 9 22 06 AM](https://user-images.githubusercontent.com/74929925/129057235-076e3f80-3ef5-4424-a436-1cfc42ad96c5.png)

Our trainees keep forgetting how to do this (and I forget how to do it!) as the floating number has different behaviour elsewhere on the page.

Closing "Action mode" (I don't know the correct term -- when you click the green flag said mode is "on" and the numbers appear, and clicking it again turns it "off" and the numbers disappear) is similarly confusing. People exit the Action window and expect the floating numbers to all disappear, but they don't.

## Describe the solution you'd like

It may be as simple as when the green flag is clicked the Action window pops up, and when the ✖️  is clicked to close the Action window **and** "Action mode" is turned off.

![Screen Shot 2021-08-11 at 9 24 04 AM](https://user-images.githubusercontent.com/74929925/129057515-54df8ca7-c108-4f7a-b620-7ea8d07bc70d.png)

## Describe alternatives you've considered
More training, but people quickly forget this.

## Additional context
N/A

**Comment by yakkomajuri** [comment]
Thanks for opening this up! It does make sense to improve this UX

**Comment by paolodamico** [comment]
Related to #2370

**Comment by macobo** [comment]
@paolodamico did you link the wrong issue?

**Comment by clarkus** [comment]
Yeah I think that was meant to be https://github.com/PostHog/posthog/issues/2370

**Comment by paolodamico** [comment]
Thanks @clarkus & @macobo! Indeed that's the issue I meant, apologies.
