### ISSUE TITLE
Enable SSO with OneLogin

### ISSUE THREAD

**Issue by paolodamico** [PostHog/posthog#5547]
Requested by a focus customer. Title says it all. Probably worth doing something around OpenID Connect ([OneLogin docs](https://developers.onelogin.com/openid-connect/connect-to-onelogin)) as it'll be easier than full SAML.

**Comment by paolodamico** [comment]
Was going to be addressed in #5606 but focus customer can no longer make use of OIDC, so we'll have to consider full SAML support.

**Comment by jamesefhawkins** [comment]
@paolodamico  For SSO - [this potential large customer](https://app.hubspot.com/contacts/6958578/deal/6032693071) said they'd want okta as the best solution. Just a small piece of feedback - not a current blocker, but I need to confirm if we could support it or not.

**Comment by paolodamico** [comment]
I can confirm support for Okta (through SAML) will be ready tomorrow and available on the next release. **Only on self- hosted**. 

I'm actually starting the process to get added directly to their catalog too.

**Comment by paolodamico** [comment]
This is now fully supported
