### ISSUE TITLE
Excluding events in between funnel steps

### ISSUE THREAD

**Issue by alexkim205** [PostHog/posthog#5553]
## Context
Shamelessly copied over from [Nail Funnel Ordering Section Specs](https://docs.google.com/document/d/1S7fwha7cph-79YaPADfFKHILCnPmBgk4rqaMu-gPZ3g/edit#heading=h.nwp8ynw69xae)

### Event exclusions
Part of building a funnel is being able to exclude users who performed a certain event. An example of this is users who upgraded their account in their activation funnel, or who received a promotion in their upgrade funnel. The functionality entails determining a specific event you want to exclude within two specific steps. So users, who performed that specific event within the steps will be automatically dropped from the funnel altogether. Note this means that they will be fully removed from consideration on the entire funnel.

### Exclusion filters
This is roughly the same as above (“Event exclusions”) except that instead of allowing users to exclude a particular event at a particular point in the funnel (i.e. between certain steps), we allow them to exclude users who did a certain event at any point in the entire funnel range (e.g. Last 7 days). 

- Master Ticket - #5367 
- Backend Specs - [Comment](https://github.com/PostHog/posthog/issues/5367#issuecomment-889860866)

@clarkus's mockup taken from [#5367](https://github.com/PostHog/posthog/issues/5367#issuecomment-890204318)

![image](https://user-images.githubusercontent.com/13460330/129104943-804e169c-c534-46cd-bd6a-470df0d3feca.png)

## A few questions/discussion topics

CC'ing @clarkus @paolodamico for some guidance

1. Are exclusions available for unordered steps? If so what would a valid step range look like for unordered steps?
2. It seems like this exclusion problem is two fold: event exclusions and user exclusions. I'm imagining user exclusion filters would best belong as another section in the 'Filters' card below. What are your thoughts on placement for exclusion features? Are they better grouped by exclusion in its separate card, by functionality, or something else?

<img width="437" alt="Screen Shot 2021-08-11 at 2 36 59 PM" src="https://user-images.githubusercontent.com/13460330/129107368-871d9191-7606-4281-8ef9-431e205ab869.png">

**Comment by neilkakkar** [comment]
Context over what we decided to implement and why: https://github.com/PostHog/posthog/issues/5074 ( I guess my PR closed it, oops!)
