### ISSUE TITLE
Hide "person count" in person modal

### ISSUE THREAD

**Issue by macobo** [PostHog/posthog#5559]
## Is your feature request related to a problem?

We show a person count in our person modals:

![image](https://user-images.githubusercontent.com/148820/129159425-ec3cf2a0-c8d4-4d54-a812-fb8380eff3b4.png)

I think it's problematic 
1. It causes confusion when the numbers don't line up
1. We don't display the count beyond 100 anyways

Why would it cause confusion? Mainly due to caching. If you load a chart it's a good chance the chart is cached and a few hours old. But as we load persons, we load the most recent ones. So users inevitably wonder why the numbers don't match up when going from chart -> person modal.

## Describe the solution you'd like

I propose we hide it.

## Describe alternatives you've considered

Always caching persons together with the chart - but we're then doubling (or more) our load.

## Additional context

cc @Twixes - His PR in https://github.com/PostHog/posthog/pull/5537 made me think of this. Adding a "refresh" button may or may not be needed if we remove this.
cc @paolodamico - wdyt? Let's kill it?

**Comment by clarkus** [comment]
I agree we should hide / remove it if the count isn't accurate.

**Comment by paolodamico** [comment]
Fixed in #5560. We may want to consider bringing this back in the future when we figure out what to do about caching.
