### ISSUE TITLE
White screen of ☠️ when flipping from Sessions to Trends

### ISSUE THREAD

**Issue by yakkomajuri** [PostHog/posthog#5562]
## Bug description

Flipping from the Sessions tab (in Insights) set to "Distribution of session lengths" to Trends brings gets me a white screen with this error:

<img width="626" alt="Screenshot 2021-08-12 at 09 37 28" src="https://user-images.githubusercontent.com/38760734/129175200-3c77900a-e95d-4220-b530-2b9a41c38258.png">

**Comment by alexkim205** [comment]
Reopening bc we had to revert the fix

**Comment by macobo** [comment]
Given that @liyiy moved teams, unassigning her. Sorry if that's wrong!

cc @alexkim205 / @mariusandra

**Comment by alexkim205** [comment]
Thanks Karl, I think I remember fixing this bug in one of my PR's some time ago. I can't seem to reproduce the bug in prod so this one might be resolvable. @rcmarron do you think you can help me confirm if this is still a bug?

**Comment by liyiy** [comment]
These were fixed in https://github.com/PostHog/posthog/pull/5620 and https://github.com/PostHog/posthog/pull/5908
