### ISSUE TITLE
Can't break down by "All users" cohort in funnels

### ISSUE THREAD

**Issue by marcushyett-ph** [PostHog/posthog#5566]
## Bug description

The UI lets me add multiple cohorts which I believe is not supported since the query errors

<img width="324" alt="image" src="https://user-images.githubusercontent.com/85295485/129185178-035fea01-c022-4e81-af18-6e4dc2e2dac7.png">

<img width="866" alt="image" src="https://user-images.githubusercontent.com/85295485/129185313-f075d22a-ab04-473c-93be-698375b11bd4.png">

## Expected behavior
Only allow me to select one co-hort at a time or support breaking down by multiple cohorts

## How to reproduce

1. https://app.posthog.com/insights?insight=FUNNELS&properties=%5B%5D&filter_test_accounts=true&events=%5B%7B%22id%22%3A%22first%20team%20event%20ingested%22%2C%22name%22%3A%22first%20team%20event%20ingested%22%2C%22type%22%3A%22events%22%2C%22order%22%3A1%7D%5D&actions=%5B%7B%22id%22%3A%222674%22%2C%22name%22%3A%22User%20Signed%20Up%20(Comprehensive)%22%2C%22type%22%3A%22actions%22%2C%22order%22%3A0%7D%5D&funnel_viz_type=steps&display=FunnelViz&interval=day&breakdown=%5B320%2C%22all%22%5D&breakdown_type=cohort&new_entity=%5B%5D&date_from=-90d

## Environment

- [x] PostHog Cloud
- [ ] self-hosted PostHog, version/commit: _please provide_

**Comment by macobo** [comment]
cc @EDsCODE

**Comment by paolodamico** [comment]
I think we should accept multiple cohorts otherwise the breakdown doesn't make sense, it's just a filter.

**Comment by macobo** [comment]
I think breaking down by multiple does work, the real issue here is that the `All users` cohort (not a real cohort) is not handled properly by this query :)
