### ISSUE TITLE
Scale over multiple server instances (Data layer)

### ISSUE THREAD

**Issue by fire** [PostHog/posthog#557]
**Is your feature request related to a problem? Please describe.**

When traffic exceeds a certain amount the data layer will be too slow. Alternatively the data layer may exceed the performance of a single computer. Thirdly, providing a high availability data layer.

This issue describes only the data layer, the web layer and the ingestion API are other issues.

**Describe the solution you'd like**

In a web panel, I can move a slider and PostHog isn't bottle-necked. (Imagine Kubernetes scaling and changing a number and adding 5 to that number)

I can run interactive analytics over the PostHog database.

**Describe alternatives you've considered**

Use CockroachDB as PostHog database. In theory, Cockroachdb is Postgresql compatible. In practice, there may be a lot of unsupported features that fail.

***Thank*** you for your feature request - we love each and every one!

**Comment by timgl** [comment]
We haven't seen Postgres being a problem for many of our users yet. Postgres tends to scale surprisingly well. We also do allow horizontal scaling of the web layer and ingestion API.

We are looking at alternatives for super high scale (#458). What kind of volume are you looking at for your PostHog deployment?

**Comment by fire** [comment]
I don't have any volume, so I was thinking towards the high availability capabilities of cockroach db.

Yes, PostgreSQL HA is fairly well understood. However, I don't have experience when that PostgreSQL database will bottleneck. How do you do load testing?

**Comment by Twixes** [comment]
We moved to ClickHouse for high-load deployments! 🚀 https://posthog.com/blog/the-posthog-array-1-15-0#clickhouse
