### ISSUE TITLE
Extra request when switching from Left to right / top bottom funnel

### ISSUE THREAD

**Issue by kpthatsme** [PostHog/posthog#5570]
## In what situation are you experiencing subpar performance?
When looking at a funnel from left to right, if I switch the view to top to bottom – we make a second request and recalculate the funnel.

I don't think any information changes between what we show for both of these visualizations, so we shouldn't need to send a request to the backend when switching these views.

## How to reproduce

1. Create a funnel 
2. Open network tab
3. Switch funnel to top-bottom, observe a request to /funnels

## Environment

- [ ] PostHog Cloud
- [ ] self-hosted PostHog, version/commit: _please provide_

## Additional context
There might be a good reason we need to do this, but ideally we don't send an extra request. I think we should have all the data on the client already.

**Comment by alexkim205** [comment]
I think this bug was brought in when we moved the layout param into the filters object to bake it into the URL. Fix incoming 🚀
