### ISSUE TITLE
"Matches n elements" in Actions toolbar is misleading

### ISSUE THREAD

**Issue by dknowles-vsk** [PostHog/posthog#5581]
## Is your feature request related to a problem?
During our PostHog training sessions the "matches n elements" text in the Action toolbar only applies to the CSS selector. Short-term selectors often include the Text field, but this field doesn't update the "matches n elements" count.

![Screen Shot 2021-08-13 at 10 23 43 AM](https://user-images.githubusercontent.com/74929925/129389908-c6c71b26-5a87-4743-bd75-aec6ef07f421.png)

## Describe the solution you'd like
Make it so "matches n elements" includes all fields in the Action toolbar.

## Describe alternatives you've considered
Using more specific CSS selectors. We do this for long-term tracking, but the current behaviour causes confusion in training sessions and makes short-term investigations harder.

## Additional context
Our organization has a lot of teams and individuals to train, and often when we're experimenting we use CSS + text to temporarily match elements.

**Comment by macobo** [comment]
cc @mariusandra something for core-experience backlog?

**Comment by pauldambra** [comment]
it's located against the selector and not something we're looking to change in the short term

will close this since it's been open for so long
