### ISSUE TITLE
Labels for funnel steps / graph series

### ISSUE THREAD

**Issue by dknowles-vsk** [PostHog/posthog#5582]
## Describe the solution you'd like
When I create insights I often create a filtered pageview rather than create an Action (e.g. visited Settings page), or I add an insight-appropriate filter to an Action (e.g. to look at a specific product entering a cart). I lose the meaning of funnel steps, trend lines, etc. when I do this. I would like an optional text box for labeling these steps (much like how you can click the Filter icon to add filters, but otherwise the empty list is hidden to avoid visual clutter).

## Describe alternatives you've considered
Make a specific Action for every breakdown of interest. I do this sometimes, but it can add clutter and maintenance costs.

## Additional context
This is particularly useful for rapid prototyping, or for times where unique Actions don't make sense.

**Comment by clarkus** [comment]
Thanks for creating this, @dknowles-vsk. We're already tracking a solution for this problem at https://github.com/PostHog/posthog/issues/5229. Feel free to add any feedback you have in that issue. Thank you for your feature request!
