### ISSUE TITLE
Action window creates a custom event Action instead of an autocapture event

### ISSUE THREAD

**Issue by dknowles-vsk** [PostHog/posthog#5583]
## Bug description
Sometimes when I create an Action using the Action window it creates a custom event Action. Since no event is selected this breaks the Action and means no events are associated with it.

![Screen Shot 2021-08-13 at 10 30 27 AM](https://user-images.githubusercontent.com/74929925/129390660-46586c0a-c0b2-4f96-8d47-803388b76795.png)

## Expected behavior
Always create an autocapture event when using the Action window

## How to reproduce
This is seemingly random, so here's my debugging steps:

1. Create an Action using the Action window
2. Spot a funnel that has a step with zero events despite being a very simple selector
3. Check the Action; notice that it's a custom event Action
4. Click `autocapture` to fix the Action; the CSS and text starts being used

## Frequency
I have seen this occur in roughly three training sessions (we've had about 10-20 team sessions so far).

## Environment

- [ ] PostHog Cloud
- [x] self-hosted PostHog

**Comment by macobo** [comment]
Thanks for reporting! This certainly looks odd!

> Create an Action using the Action window

Just to confirm: Do you mean defining it via the posthog toolbar here? https://posthog.com/docs/user-guides/toolbar
