### ISSUE TITLE
"There are no matching events for this query" message for a slow-loading funnel is confusing

### ISSUE THREAD

**Issue by dknowles-vsk** [PostHog/posthog#5584]
## Bug description
When a funnel is taking a long time to load (1+ minute), it shows the following contents:

1. A spinner
2. A screen that says "There are no matching events for this query"
3. A screen that says "Looks like things are a little slow"

![Screen Shot 2021-08-16 at 1 56 13 PM](https://user-images.githubusercontent.com/74929925/129625161-1547293c-db7f-4065-984a-3cadbab53615.png)
![Screen Shot 2021-08-16 at 2 12 22 PM](https://user-images.githubusercontent.com/74929925/129625168-2faa551a-34fe-4e18-9fd4-34eba663732e.png)

Since Step #2 can hang around a long time, it's caused confusion for many of our internal users.

## Expected behavior
Don't show step #2.

## How to reproduce
1. Create an extremely slow query in a funnel (1+ minutes to load)
2. Wait & watch

## Environment

- [ ] PostHog Cloud
- [x] self-hosted PostHog

## Additional context
Our deployment has recently seen its resources upgraded; this may not appear anymore if the deployment is sufficiently quick.

**Comment by macobo** [comment]
cc @clarkus and @paolodamico  :)

**Comment by clarkus** [comment]
- Let's move towards a skeleton loader state for this insight chart type
 - I think the flashing of the "no matching events" state is probably a bug here. Are we referencing the wrong empty state or is something else triggering this state prematurely?
 - When things are slow, should we show an additional empty state, or just append messaging to the current empty state. This problem is actually broader than funnels, so it might be better to solve it in a more centralized way.

**Comment by paolodamico** [comment]
I actually think that our current "things are going slow" loader is pretty on point. The skeleton loader would make sense if it was the regular loading state, but this is shown when things are taking longer than usual. It's definitely a bug that we're showing the empty state while things are loading and then showing the things are slow view. @alexkim205 think it's related to what you're working on so maybe you can pick it up?

**Comment by alexkim205** [comment]
The no matching events flashing is definitely a bug that was introduced by nested state checking in our funnels components. #5607 should address the problems raised in this issue
