### ISSUE TITLE
Stickiness chart shows wrong dates when selecting date range

### ISSUE THREAD

**Issue by dknowles-vsk** [PostHog/posthog#5585]
## Bug description
When you select "last 48 hours, last 30 days, last 90 days, etc." in the stickiness chart it shows 31 December as the date

![Screen Shot 2021-08-13 at 10 43 06 AM](https://user-images.githubusercontent.com/74929925/129392472-eca84d92-a9c4-4fdc-9268-ee049aa5f292.png)

## Expected behavior
Show the correct date

## How to reproduce

1. Select any other date range in a Stickiness chart
2. Hover over any part of the chart

## Environment

- [ ] PostHog Cloud
- [x] self-hosted PostHog, version/commit: 
 
posthog-web: Image: posthog/posthog@sha256:872d9429f19d7a297384c47f633e683f2b46e412cac2b83c5b1b2f50fdbd2ca6

**Comment by macobo** [comment]
Thanks for the report.

I think in this case we should instead show nothing on the tooltip or the day count - the date is not valid here. :)
