### ISSUE TITLE
Graph series filters ignored in Stickiness chart

### ISSUE THREAD

**Issue by dknowles-vsk** [PostHog/posthog#5586]
## Bug description
Graph series added to the Stickiness chart ignore any applied filters.

![Screen Shot 2021-08-13 at 10 49 58 AM](https://user-images.githubusercontent.com/74929925/129393005-e813e4f2-c776-45c0-9b9f-357146afe870.png)

![Screen Shot 2021-08-13 at 10 49 53 AM](https://user-images.githubusercontent.com/74929925/129393006-9ee50f12-9639-470f-bb76-50b5084f08fb.png)

## Expected behavior
When querying the graph series, include the filters in the series.

## How to reproduce

1. Create a Stickiness insight
2. Add multiple graph series with filters

## Environment

- [ ] PostHog Cloud
- [x] self-hosted PostHog, version/commit: 
   posthog-web:
    Image:      posthog/posthog@sha256:872d9429f19d7a297384c47f633e683f2b46e412cac2b83c5b1b2f50fdbd2ca6

**Comment by macobo** [comment]
See also: https://github.com/PostHog/posthog/issues/5639

This will fix the issue: https://github.com/PostHog/posthog/pull/5641

**Comment by macobo** [comment]
Thanks for the report! This will be fixed with the next release (or on master if you upgrade now).
