### ISSUE TITLE
Loading state for graph table data

### ISSUE THREAD

**Issue by corywatilo** [PostHog/posthog#5587]
When loading a table with a _ton_ of data, there is a lag. For the few seconds no data appears, it feels like a bug. In reality, the page is working, but there's no indication of it.

If you update the time range, you'll see a significant delay between choosing the new range and seeing data update.

**[Example query](https://app.posthog.com/insights?insight=TRENDS&interval=day&events=%5B%7B%22id%22%3A%22%24pageview%22%2C%22name%22%3A%22%24pageview%22%2C%22type%22%3A%22events%22%2C%22order%22%3A0%7D%5D&filter_test_accounts=true&properties=%5B%7B%22key%22%3A%22%24current_url%22%2C%22value%22%3A%22https%3A%2F%2Fposthog.com%22%2C%22operator%22%3A%22icontains%22%2C%22type%22%3A%22event%22%7D%5D&display=ActionsTable&date_from=-30d&breakdown=%24current_url&breakdown_type=event)**

It's far more obvious on a new query where there is no data in the `Current URL` column, as it will be blank, then populate after a while. (I thought I had accidentally selected a field with no data.) On subsequent queries, the stale results remain in place until the new data is loaded. (In this case, maybe a fade on the data to indicate something is happening would be useful?

![image](https://user-images.githubusercontent.com/154479/129393290-29947efd-f81d-49be-8018-34f187cd9785.png)

**Comment by jamesefhawkins** [comment]
Plus one. I often worry this is because a field is filtering out anything when in fact it's just slow.

**Comment by clarkus** [comment]
Related https://github.com/PostHog/posthog/issues/5411
