### ISSUE TITLE
Avoid reading materialized columns the query does not need

### ISSUE THREAD

**Issue by macobo** [PostHog/posthog#5593]
## Is your feature request related to a problem?

Currently, most queries read all of our denormalized columns. This makes writing queries that use denormalized queries easier.

The hidden assumption is that clickhouse query optimizer optimizes these reads away.

This is not the case:
- `EXPLAIN AST` shows that the columns are read even if query does not need them
- Asked in clickhouse users chat: They confirmed it's best to assume the columns will be read from disk.

This means that adding new denormalized columns might slow down instead of speed up our queries

## Describe the solution you'd like

Update queries in a way that we only read columns (including properties) if they will be used by e.g. parent query.

## Describe alternatives you've considered

Not using materialized columns.

## Additional context

cc @neilkakkar @EDsCODE - this affects how we'll be writing queries going forward :sweat_smile: 

Related:
- https://github.com/PostHog/posthog/issues/5463
- https://github.com/PostHog/posthog/issues/5475
- https://github.com/PostHog/posthog/issues/5461

**Comment by macobo** [comment]
Did some measurements on a query like:

```sql
SELECT count(1)
FROM (
    SELECT properties, mat__browser
    FROM events
    WHERE team_id = X AND timestamp > '2021-08-05' AND mat__browser = 'Chrome'
)
```

This behaves in interesting ways:
- For larger teams, if the time range is all materialized, then the query is ~instant (<300ms) :)
- For larger teams, if the time range is _not_ materialized, the query is _faster_ selecting properties as well (40k vs 20k ms). 
- For smaller teams, if the time range is _not_ materialized, the query is _slower_ selecting properties as well (2x difference)

**Comment by neilkakkar** [comment]
This makes sense. I'm guessing the issue is not just for going forward, but for existing funnel queries as well?

I don't think it will be a problem for the basic funnel, but edge cases probably exist, for when the query creates person step filters + cohort breakdown etc. etc.

**Comment by macobo** [comment]
> I'm guessing the issue is not just for going forward, but for existing funnel queries as well?

Absolutely. Reason I cc'd you both was just to draw attention to that this area of query building is changing and it might affect how we do things in e.g. paths. :)

**Comment by macobo** [comment]
Done for most insights queries
