### ISSUE TITLE
Filtering element `href` by regex does not work

### ISSUE THREAD

**Issue by rhy** [PostHog/posthog#5598]
Trying to add an href filter containing URL path (/admin/sites/*/courses/42400-example-course), but it’s returning 0 results, when I use a wildcard (% or *), but when I search a specific path (/admin/sites/56306/courses/42400-example-course), it returns results. What am I doing wrong?

**Comment by macobo** [comment]
Can you add a screenshot of the specific filter? Are you using `equals` or `matches regex` or something else?

In this case you want regexes - see an example in the image below.

![image](https://user-images.githubusercontent.com/148820/129593641-7e93a3ec-b54d-49ff-bfd7-eabca203cc6b.png)

**Comment by rhy** [comment]
![Screen Shot 2021-08-17 at 10 07 49 AM](https://user-images.githubusercontent.com/91264/129741051-c298fcbf-b125-4551-97bb-cf1c3bee1b57.png)

Still returning 0 results. 

This is the string I'm using: https://regex101.com/r/su1hbC/1

**Comment by macobo** [comment]
I haven't tested this, but you might not need the \ escaping here. See also the screenshot I linked above :)

**Comment by rhy** [comment]
I'e tried both ways and still no success. Really weird!

**Comment by macobo** [comment]
Note: We did a quick call, the original intent was to track certain links via actions. I suggested using `data-attributes` for identifying links. More info on this here: https://posthog.com/docs/user-guides/actions#matching-selectors

Follow-up action for me: check if regexes behave as intended on actions page :sweat_smile:

**Comment by macobo** [comment]
So this is a real bug.

## Description

When searching based on `href` element property based on a regex, the regex is incorrectly escaped.

## How to reproduce

- Go to events
- Filter by href, select regex, choose one href it autosuggests. See events
- Replace part of the URL with `.*` 
- See no results

## Expected outcome

Same results

## Additional context

Same occurs on `actions` page.

Here's an example clickhouse query demonstrating the escaping. See escaped `.*` at the end

```sql
SELECT uuid,
       event,
       properties,
       timestamp,
       team_id,
       distinct_id,
       elements_chain,
       created_at
  FROM events
 WHERE team_id = 1
   AND timestamp < '2021-08-19 07:46:19.016569'
   AND ((event = '$autocapture' AND (match(elements_chain, '.*?(href="/action/1\\#backTo=Actions\\&backToURL=/events/\\.\\*").*?'))))
 ORDER BY toDate(timestamp) DESC, timestamp DESC
 LIMIT 101
```

**Comment by Twixes** [comment]
Hey @rhy! Thanks for bringing this to our attention. This filtering now works on PostHog Cloud. :)
