### ISSUE TITLE
Add branding info to setup page

### ISSUE THREAD

**Issue by SanketDG** [PostHog/posthog#560]
**Is your feature request related to a problem? Please describe.**
Right now, there seems to be no branding info on the setup page of PostHog.
This could be bundled up with https://github.com/PostHog/posthog/issues/531

**Describe the solution you'd like**
Ideally a logo at the top and some relevant information in a footer.

**Describe alternatives you've considered**

**Additional context**

***Thank*** you for your feature request - we love each and every one!

**Comment by jamesefhawkins** [comment]
Hey @SanketDG, to clarify - is this request to be able to upload your own company logo?

**Comment by SanketDG** [comment]
@jamesefhawkins No, for Posthog itself. Once someone launches the self hosted instance, they are shown the signup page only.

Maybe adding a bit more information would help here.

**Comment by paolodamico** [comment]
Closing this as it has been addressed.
