### ISSUE TITLE
Clarify Distinction Between Two Buttons

### ISSUE THREAD

**Issue by dknowles-vsk** [PostHog/posthog#5604]
## Bug description
There appears to be two ways to save a funnel:
![Screen Shot 2021-08-16 at 2 50 16 PM](https://user-images.githubusercontent.com/74929925/129628531-d86d761b-d0a9-4844-ad54-165a5f7f7288.png)
![Screen Shot 2021-08-16 at 2 50 13 PM](https://user-images.githubusercontent.com/74929925/129628532-c5049cae-a571-44e2-9269-466ffd99f1e9.png)

It's not clear if these accomplish the same thing or not.

## Expected behavior
One button, or two buttons with the same text.

## How to reproduce
Look at a funnel insight

## Environment

- [ ] PostHog Cloud
- [x] self-hosted PostHog, version/commit:

**Comment by paolodamico** [comment]
@clarkus I believe we already addressed this with #3408?

**Comment by clarkus** [comment]
@paolodamico yes this should be addressed as part of #3408. @dknowles-vsk, thanks for creating this issue. If you get a chance, check out the related issue and share any feedback you have on those changes. Thanks again!
