### ISSUE TITLE
Creating Annotations for specific chart items errors out

### ISSUE THREAD

**Issue by neilkakkar** [PostHog/posthog#5615]
## Bug description

Creating an annotation for a specific dashboard item: 
![image](https://user-images.githubusercontent.com/7115141/129717509-ec1d2f5e-c951-4f6c-bbfe-bf6f3283394d.png)

returns in an error like so:
![image](https://user-images.githubusercontent.com/7115141/129717430-6b9845bd-1e9e-4b59-bb14-9fbd715f31f1.png)

## Expected behavior

There's no error.

## How to reproduce

1. Refresh dashboard items (important for reproducing!)
2. Create annotation (like above screenshot)
3. See error

## Environment

- [x] PostHog Cloud
- [ ] self-hosted PostHog, version/commit: _please provide_

## Additional context

https://posthog.slack.com/archives/C01LNUMT022/p1627899060000700

**Comment by neilkakkar** [comment]
The issue is probably bigger than this, but this was the smallest reproducible change I could find so far

**Comment by Twixes** [comment]
This should be fixed now.
