### ISSUE TITLE
Should sessions be max 30 minutes long?

### ISSUE THREAD

**Issue by neilkakkar** [PostHog/posthog#5617]
Investigating Path queries, and I noticed this quirk of sessions where they can't be longer than 30 minutes. (more in point #3 here: https://github.com/PostHog/posthog/issues/4884#issuecomment-896826621 )

This has implications for the new work we want to do on Paths, particularly:

(1) Infinite path expansion for a user becomes impossible if their sessions lasted longer than 30 minutes (split into multiple sessions, new session starts at a point "in the middle" of the path.
(2) With steps between funnels, conversion times > 30 minutes imply we would get a _wrong_ picture of what went on with the user. This is dangerous, if not downright wrong.
(3) All Path visualisations where a person did things over a longer timeframe get broken out.

I think this reduces the efficacy of what we want to achieve with Paths.

On the flipside, I do get that a new day is a new session, and depending on what question you want to answer, you might want to consider this as a separate user.

Raising this issue to (1) Understand the historical context for 30 minute sessions. and (2) Hear your thoughts on doing away with this constraint (maybe just for paths, if valid historical context).

Thoughts? @macobo @EDsCODE @Twixes  @paolodamico  @marcushyett-ph

**Comment by macobo** [comment]
> Investigating Path queries, and I noticed this quirk of sessions where they can't be longer than 30 minutes

That isn't the case. The definition of an event in sessions page is:
- Two events belong to same session if < 30m between them 
- Same distinct_id (see https://github.com/PostHog/posthog/issues/4884 for why this is probably a bad idea), not sure if other pages follow this logic

Meaning if you did events at minutes 5, 25, 45 and 65 and 99 it would result in 2 sessions - [5,25,45,65] and [99].

**Comment by neilkakkar** [comment]
That makes a lot more sense, sounds like just a borked query assumption then! (or maybe I'm reading the query wrong). But thanks, that clears things out for me :)
