### ISSUE TITLE
Full SAML login support

### ISSUE THREAD

**Issue by paolodamico** [PostHog/posthog#5647]
**EDIT: Option A below is implemented. When it makes sense to prioritize we should consider multi-tenancy SAML (Option B below).**

------- 

## Option B. Organization-based. Self-hosted + Cloud.
- You configure SAML login on an organization-basis. Up to one SAML provider per organization.
- The login process could then look something like this:
    1. We'd have to refactor the login page so you enter your email first and based on your email we show you the appropriate login options.
    2. The above could raise a security concern about potentially exposing an endpoint you could use to find out if a certain user has an account on our system.
    3.  After the user enters their email address (from [1]), if they only have a single SSO login option, we take them to the respective login page.
    4. If the user has multiple login options (e.g. password + SSO), we let them choose which option they want (like we currently do in our login page).
- This option also brings up a few more edge cases.
    - As an org admin I probably want to restrict my users to only have my SAML login option (otherwise the purpose of SAML would be defeated), but a user can belong to multiple organizations, so we need to give the option for either a) users in your org can only login with your SSO and/or b) users in your org can only belong to your org.
    - On self-hosted we would want to still take the users to their login page automatically if they have a single org and a single authentication mechanism.
    - Because a user can technically belong to many orgs each with its own auth mechanism, we could technically end up with users with multiple SAML authentication paths, we would have to support each path.

-------

## Additional context from original issue

<details>
 <summary>Expand for additional context</summary>
 Addresses #5547. Some focus customers and a few other users have requested support for SAML. This is a compliance feature that a lot of large-scale organizations require for full widespread rollout. When working at a large org, having a centralized place for provisioning and managing users can make the onboarding/offboarding process smoother and help reduce security risks. There's a great [Slack thread](https://posthogusers.slack.com/archives/CT7HXDEG3/p1628859965082200) by a community member about the importance of SAML and [this study](https://www.onelogin.com/press-center/press-releases/97-percent-of-saas-vendors-backing-saml-based-single-sign-on) by OneLogin in which they find that up to 97% of SaaS support have support (or plans) for SAML.

Aside from the implementation complexities of SAML (it's a more robust standard, so it's not as straightforward as our current social auth providers), there's some conceptual difficulties of implementing SAML.

## Option A. Instance-based. Only Self-hosted.
- We enable instance-based configuration for SAML. You can have only one SAML provider.
- We give users the option to only allow SAML login to their instance (and restrict password creation & access), in this case the default login screen fully disappears and we always redirect to their login page.
- As a fallback when something breaks down, admins could simply disable SAML for their instance (we could even consider giving automatic Django admin access to allow them to reset passwords).

## Final notes

**Which option to choose?** Prioritizing this solely for solving for our focus customers I would go with Option A, not only based on our current customers but based on our persona profile (probably all of these will self-host). It's important to consider that based on the referenced study above and how other SaaS operate, it seems we will eventually require this on Cloud, but I would argue we might be better off pushing this down the line until it's actually needed (opportunity cost of other stuff with more immediate impact), but let's not forget this will require a loan from our tech debt bank.

</details>

**Comment by mariusandra** [comment]
Hey, something this app-specific should fall on the core experience team (how's your experience logging in today?). The platform and analytics teams are the ones you call when the complexity is around scale or scaling. This is a login screen :).

As option A seems like the MVP for option B, and as it solves the focus customers' needs, let's obviously go for it first.

How much work would you [estimate](https://jacobian.org/2021/may/20/estimation/) implementing this to actually take? Are there any edge cases we need to consider regarding e.g. deleting inactive users?

**Comment by paolodamico** [comment]
Thanks for the input @mariusandra! Makes sense on the scope and doing Option A. My best estimate**** would be around 2 days of solid work (not counting meetings, PR reviews, ...), particularly because we'll want to have functional tests for all edge cases and we'll want to test the flow with at least a couple of SAML identity providers.

I think for the MVP we can handle only authentication and automatic user provisioning (through the already existing whitelisted domains feature), but we'll probably want to explore the standard further to understand how to deal with permissions, removing users, etc. Tbh I don't have enough context on the standard yet to comment on more edge cases other than the ones already mentioned.

Now re prioritization (per https://github.com/PostHog/product-internal/issues/142) I think it makes sense to **pick this up now** (particularly now that with https://github.com/PostHog/posthog.com/pull/1819 Paths goes fully to Core Analytics) and I could certainly do it, but I don't think that's the right move. Currently there are other things where I can provide more value and that no one else is picking up, and I believe there are other engineers in our team that could do a solid, even better, job than me here.

**Comment by Twixes** [comment]
Option A as the first step sounds good. Estimation-wise I think it's important what implementation route we go here. Do we have an eye on a library we could use (with a quick search I found https://github.com/onelogin/python3-saml)?

**Comment by paolodamico** [comment]
That was the library I had on the radar too as it already has a wrapper directly in Python social, so looks like the user association and creation can be handled by existing code.

**Comment by paolodamico** [comment]
Alright Option A is ready. Keeping this around as I think at some point it'll make sense to implement Option B, but moving to backlog until it makes sense to prioritize.

**Comment by timgl** [comment]
Looks like Paolo will be getting this done by Friday, Marius will own this after. 

#9158
