### ISSUE TITLE
Improved cohort building logic - optional counts

### ISSUE THREAD

**Issue by Tannergoods** [PostHog/posthog#565]
**Is your feature request related to a problem? Please describe.**
When building a cohort I can only look at the total users who have performed an action or have a property - this is prevents me from defining a cohort of super users who may have logged in 30 times in the last 30 days. 

**Describe the solution you'd like**
I would like to have optional counts when building a cohort with multiple count or relative counts as they relate to Actions. We have similar logic built into Properties - i.e. equals, does not equal, greater than etc

example 1 Count - User has done "action" - "sign in" [count] > X in last Y days
example 2 Relative Count - User has done "action" - "sign in"  > than "action" - "docs view" in last X days

**Describe alternatives you've considered**
SQL querying the data you have collected yourself?

**Additional context**
Part of Parity Roadmap Project

***Thank*** you for your feature request - we love each and every one!

**Comment by Twixes** [comment]
This is now possible.
