### ISSUE TITLE
Color coding disagrees between chart tooltip and tables when cohorts are applied

### ISSUE THREAD

**Issue by clarkus** [PostHog/posthog#5659]
## Bug description

When using an insight trend with a cohort applied, the chart tooltip and table disagree on color coding and mapping. 

## Expected behavior

I expect the same color to be used for each breakdown property in each component. 

## How to reproduce

1. Go to insights
2. Apply a breakdown using multiple cohorts
3. Compare the table to the  trend

<img width="2354" alt="Screen Shot 2021-08-19 at 9 12 43 AM" src="https://user-images.githubusercontent.com/254612/130104400-1cd44be9-8958-4917-ac7e-c837c671857d.png">

## Environment

- [ ] PostHog Cloud

## Additional context

This might be specific to including the "all users" cohort, but I couldn't reproduce sufficiently to be sure of this.

**Comment by paolodamico** [comment]
From the screenshot, the tooltip also shows the cohort ID instead of the cohort name

**Comment by paolodamico** [comment]
This has been addressed
