### ISSUE TITLE
Type and font changes to align with marketing updates

### ISSUE THREAD

**Issue by clarkus** [PostHog/posthog#5661]
## Is your feature request related to a problem?

There are some [upcoming changes](https://github.com/PostHog/posthog.com/pull/1824) to our marketing website that we can roll into the product to better align the two assets. Specifically, the text styles for posthog.com are changing substantially. While we can't host these fonts as part of the product, we can replicate the styling with some other updates.

## Describe the solution you'd like

Remove GoshaSans and replace it with a font similar to Matter. Make some other updates to better align the two assets (background colors and other updates in the branding guidelines). 

## Describe alternatives you've considered

Leaving things alone until we make broader changes to the product [information architecture.](https://github.com/PostHog/posthog/issues/5346).

**Comment by corywatilo** [comment]
[Plus Jakarta Sans](https://tokotype.github.io/plusjakarta-sans/) is open source and looks _similar enough_ to Matter that most users wouldn't notice.

I haven't fully read the [license](https://scripts.sil.org/cms/scripts/page.php?site_id=nrsi&id=OFL) for it, but if it would be an ideal solution if we can use it in both hosted and self-hosted options.

**Comment by clarkus** [comment]
This is a quick change made locally - I swapped the `main` container background color to `#EEEFE9` and dropped the gosha reference in the font stack (which would make this screenshot show the SF pro / text front)  

<img width="1550" alt="Screen Shot 2021-09-10 at 9 33 43 AM" src="https://user-images.githubusercontent.com/254612/132887195-0ade298d-889e-422e-8627-df214ab41c92.png">

**Comment by clarkus** [comment]
I did a comparison between the most common system fonts and the font we're using on the marketing website. None of the fonts really approach the exact character of the marketing font. For that reason, I am going to recommend we drop any reference to non-system fonts in our css stack and instead rely on system defaults in the product. 

If this is too much variation, then we could specify a font and ship it along with the rest of the product. We've previously considered https://github.com/tokotype/PlusJakartaSans as a reasonable choice here. Based on the [license](https://github.com/tokotype/PlusJakartaSans/blob/master/LICENSE.md), this seems like a feasible option. If we choose to go with this font, we should invest back into the project if possible. 

> The OFL allows the licensed fonts to be used, studied, modified and redistributed freely as long as they are not sold by themselves. The fonts, including any derivative works, can be bundled, embedded, redistributed and/or sold with any software provided that any reserved names are not used by derivative works. The fonts and derivatives, however, cannot be released under any other type of license. The requirement for fonts to remain under this license does not apply to any document created using the fonts or their derivatives.

Updated type rules that would better align the type in product with that in marketing
![Type](https://user-images.githubusercontent.com/254612/133169018-62dafbf9-5f56-4eef-9b07-d93b7080fddc.png)

Click through to see comparisons of popular system fonts. You're encouraged to leave feedback in figma as much as possible!
https://www.figma.com/file/9yWtngNb1AIuf6KmXaEPJA/App-doodles?node-id=1238%3A138073

**Comment by corywatilo** [comment]
Hm, now that I'm seeing it in-app, +Jakarta really doesn't look _great_ IMO.

The mock with Inter looks nice, and would be good for cross-platform consistency, but does it feel a _little_ too much like TailwindUI?

Since Inter and SF Pro are so close, my thinking would be:

- Let Macs (that use SF Pro by default) use their OS font
- Older Macs, PCs and ~Karl~ Linux can use Inter

This way, it will feel _a lot snappier_ for our hardcore users on Macs, and the app will still look consistent for everyone else.

Something like:

```
  font-family: -apple-system, BlinkMacSystemFont, "Inter", "Segoe UI", Roboto, Helvetica, Arial, sans-serif, "Apple Color Emoji", "Segoe UI Emoji", "Segoe UI Symbol";
```

Since Inter is [available on Google Fonts](https://fonts.google.com/specimen/Inter), we wouldn't have to package it with our app, and we can selectively load it for the OSes we need and not new Macs that will use SF Pro.

**Comment by corywatilo** [comment]
MVP: system stack
Stretch: throw Inter into the mix

**Comment by clarkus** [comment]
That sounds like a good direction. I think this is ready to hand over to an engineer once there's capacity.

**Comment by paolodamico** [comment]
Alright PR is out! For context, we can't pull the fonts from Google Fonts because of the OSS package. It particularly wouldn't work for airgapped instances.

**Comment by clarkus** [comment]
Thanks for making this happen, @paolodamico.
