### ISSUE TITLE
Saving a bar chart to dashboard fails

### ISSUE THREAD

**Issue by kappa90** [PostHog/posthog#5680]
## Bug description

Saving any kind of chart to a dashboard triggers a server error 500.

## Expected behavior

Save the chart to dashboard.

## How to reproduce

1. Create a chart
2. Save chart to any dashboard
3. Server error 500

## Environment

Self hosted Postgres
![image](https://user-images.githubusercontent.com/7335343/130361344-7c5f3a44-7335-4ab1-a384-3b0b0e43de0b.png)

## Additional context

Sentry Issue Logs: https://sentry.io/share/issue/edb1c4ef74304935a9aa06b67be56476/

**Comment by Twixes** [comment]
Hey! Looks like your PostHog server version is outdated in relation to database schema version. This can occur for example if PostHog is upgraded and the newer version's migrations run, but then the server is rolled back. In this situation your database schema was created with a version of PostHog that included new field `DashboardItem.favorited` that we recently added to support a coming feature, but your running PostHog version is from before that addition.
The way to remedy this depends on your deployment environment – how is your PostHog instance deployed?

**Comment by samwinslow** [comment]
Is this still relevant?

**Comment by Twixes** [comment]
I'll close this for now @kappa90 but definitely feel free to reopen if you're still experiencing this on a newer PostHog version!
