### ISSUE TITLE
Create Cohorts from Funnels

### ISSUE THREAD

**Issue by Tannergoods** [PostHog/posthog#569]
**Is your feature request related to a problem? Please describe.**
If I create a funnel tracking conversion I would like to be able to save this as a cohort in order to a) revisit the performance over different time periods, compare against other cohorts. 

**Describe the solution you'd like**
I would like to be able to select a step of a funnel and create a cohort

![Posthog](https://user-images.githubusercontent.com/60791437/79216636-6de83880-7e45-11ea-9a26-3f2f0ed378fb.png)

In the screenshot example this would create a cohort of users who have followed the action order homepage view - sign up - paid all time. 

Would need #169 and #565 finished for this to be most valuable

**Describe alternatives you've considered**
I could get some of the way there by filtering funnels from a pre made cohort but I might miss something.

**Additional context**

***Thank*** you for your feature request - we love each and every one!

**Comment by theonlyjohnny** [comment]
Hello! Is this feature still planned?

**Comment by paolodamico** [comment]
We're already considering using the default person modal in funnels, which would solve this.
