### ISSUE TITLE
Card alignment issue when deleted from "My Dashboard"

### ISSUE THREAD

**Issue by sankalpdomore** [PostHog/posthog#5690]
## Bug description

When deleting cards from "My Dashboard" the alignment of remaining cards are right-aligned.

## Expected behavior

Should be left-aligned or centred.

## How to reproduce

1. Go to any dashboard
2. Try deleting the first few cards in the view

## Environment

- [x] PostHog Cloud
- [ ] self-hosted PostHog, version/commit: _please provide_

## Additional context

The last one here is right-aligned
<img width="2477" alt="CleanShot 2021-08-23 at 20 23 39@2x" src="https://user-images.githubusercontent.com/18334593/130469404-0e87db0b-7999-4a81-97f4-a6446857221b.png">

The one deleted from the middle didn't adjust the cards on its right:
<img width="1238" alt="CleanShot 2021-08-23 at 20 30 51@2x" src="https://user-images.githubusercontent.com/18334593/130470271-ec9a7ab8-eb0c-4361-9f89-a2015088a7f5.png">

**Comment by paolodamico** [comment]
Will be addressed with #4312
