### ISSUE TITLE
Option to reset resizing changes done to a card in "My Dashboard"

### ISSUE THREAD

**Issue by sankalpdomore** [PostHog/posthog#5691]
## Is your feature request related to a problem?

I am playing around with the card's resizing option in the "My Dashboard" and didn't like the sizing on some. 

## Describe the solution you'd like

I'd have loved an option reset the card to its original sizing. 

![CleanShot 2021-08-23 at 20 44 20@2x](https://user-images.githubusercontent.com/18334593/130472600-733aed4b-c567-4830-82fc-69aa2bded41c.png)

## Describe alternatives you've considered

Current workaround is to delete the card/graph and go to insights and add it again.

**Comment by Twixes** [comment]
We've now significantly simplified the grid (https://github.com/PostHog/posthog/pull/7567), which makes the described situation less of a concern, so I'll close this particular issue. Any feedback on the current experience after changes appreciated!
