### ISSUE TITLE
Data isn't being displayed properly in trends pie charts

### ISSUE THREAD

**Issue by clim-va** [PostHog/posthog#5695]
## Bug description

Data isn't being displayed properly in trends pie charts.

Pie chart colours don't always match the colour of the letter it corresponds to in the Query Definition. See this screenshot here has "Combined Platform: Clicked Businesses" as brown in the query definition but dark blue in the pie chart.

![image](https://user-images.githubusercontent.com/46305442/130481086-abf2bc8d-d269-494c-8359-35a34a32b246.png)

Also, if we scroll down to the details table, "Combined Platform: Clicked Businesses" doesn't even show up and it seems "Combined Platform: Clicked Home" was duplicated.

![image](https://user-images.githubusercontent.com/46305442/130481774-811fa1ff-5ff2-428d-8bc6-8c2c3a75cee3.png)

This seems to only be happening when the event/action that has the highest _total sum_ is not the first one added to the query.

## Expected behavior
We expect to see the graph colours matching the query definition colours, as well as the details table having one row for each set of data

## How to reproduce
1. Create a trends pie chart
2. Add multiple events/actions but order them so that the highest total is _not first_

2. Look at the data in the Query Definition, Graph, and Details Table and see if they match

## Environment

- [ ] PostHog Cloud
- [x] self-hosted PostHog, version/commit: _please provide_

## Additional context
Seems to be happening to multiple graphs
![image](https://user-images.githubusercontent.com/46305442/130483499-bb45172c-5c03-4a3a-a625-3d8a511396c7.png)

**Comment by paolodamico** [comment]
Related #5696
