### ISSUE TITLE
Insights pie chart totals display only the total of the shown breakdown values

### ISSUE THREAD

**Issue by clim-va** [PostHog/posthog#5696]
## Bug description

When insights pie charts don't show all of the breakdown values (because there are a lot of them), **Total: x** should still display the _actual total_, and not the total of _just_ the shown breakdown values.

![image](https://user-images.githubusercontent.com/46305442/130485847-f7bd5fea-d317-4df2-9624-38af918fbb93.png)

![image](https://user-images.githubusercontent.com/46305442/130485856-854d538b-aed4-4983-bb4e-710160f9abec.png)

Especially when the pie charts are part of a larger dashboard, we can't tell that there are breakdown values missing, and it's confusing to see a large disparity between two charts that should have the same if not similar totals
![image](https://user-images.githubusercontent.com/46305442/130486059-3877cfae-5750-40ac-be0e-cb6440ae95d3.png)

## Expected behavior

We expect the Total amount to be the actual total and not the total of the shown breakdown values.

## How to reproduce
1. Create a trends pie chart
2. Query for Pageview counted by Total count
3. Add breakdown by an event property that will result in many unique values (country or browser are the two I have)

## Environment

- [ ] PostHog Cloud
- [x] self-hosted PostHog, version/commit: _please provide_

**Comment by paolodamico** [comment]
Thanks for reporting @clim-va! We definitely need to improve the experience on the pie chart here

**Comment by mariusandra** [comment]
This is now possible if you also add the "other" breakdown.
