### ISSUE TITLE
WIP External integration - push notifications to users

### ISSUE THREAD

**Issue by Tannergoods** [PostHog/posthog#570]
**Is your feature request related to a problem? Please describe.**
If I have segmented users in cohorts from a funnel (see #169 #569) I would like to integrate PostHog with a push notification system / customer engagement platform like Airship or even my CRM like Salesforce or Hubspot to be able to automate messaging to users who perform a series of actions

**Describe the solution you'd like**
If I was an ecommerce app where a user got to checkout and did not complete a funnel with an end action of "purchase" I would like to create a cohort of those users and then push them a message asking them to reconsider or offer a discount (via my own messaging system) I would like PostHog to integrate with that messaging system so I can easily send the users in the cohort to my CRM or Customer engagement platform.

**Describe alternatives you've considered**
If I could download the users in that cohort I can just import them into the other system and do that messaging myself - this might be the easiest option first? 

**Additional context**

***Thank*** you for your feature request - we love each and every one!

**Comment by timgl** [comment]
@EDsCODE Did you close this by accident? I don't think this has happend yet?

**Comment by EDsCODE** [comment]
Yeah sorry about that! Was trying to close the trends page issue somehow closed this

**Comment by jamesefhawkins** [comment]
#657 feels like a better starting point than this issue, since it'd mean complete extensibility faster.

We could then write out a list of integrations we'd need, prioritized by customer demand to pre-make some of them.

The download however does seem like a sensible starting point (as many pieces of software let you upload a CSV of users / emails), so I'd suggest we relabel to this.

**Comment by jamesefhawkins** [comment]
On digging further, it also looks like #411 provides the download, so I'd suggest closing this for now.

**Comment by timgl** [comment]
agree
