### ISSUE TITLE
Improve session recording seekbar

### ISSUE THREAD

**Issue by sankalpdomore** [PostHog/posthog#5710]
## Is your feature request related to a problem?

Make it easy to understand user activity on recordings. Right now, it's really hard to know when the user activity starts.

![CleanShot 2021-08-24 at 13 36 46@2x](https://user-images.githubusercontent.com/18334593/130590403-6d916f73-76dd-4bc4-876c-3ee2400cee22.png)

## Describe the solution you'd like

I like the activity centred seek bar from SmartLook. They denote clicks by green dot, mouse activity by a blue seek bar, and a blank seek bar for inactivity. Makes it easier for me to pick the activity points on seekbar to review.

![CleanShot 2021-08-24 at 14 43 34@2x](https://user-images.githubusercontent.com/18334593/130590850-8c855f1c-1ff1-4685-9594-bda4ebf78204.png)

**Comment by macobo** [comment]
Related: https://github.com/PostHog/posthog/issues/2384

**Comment by paolodamico** [comment]
The new recordings playback experience implements this, so closing!
