### ISSUE TITLE
/api/person times out on full text search

### ISSUE THREAD

**Issue by macobo** [PostHog/posthog#5717]
## Bug description

Sentry issue: https://sentry.io/organizations/posthog/issues/1724065650/?project=1899813&referrer=github_integration

Context from @Twixes:

> This issue is still present, as evidenced in the linked Sentry issue's history. [Just reported by a large scale Cloud user.](https://posthogusers.slack.com/archives/G01JXEDAL22/p1629799619462400)

> It seems that the breaking point for Cloud is a bit above 1 million persons in a project. The cause are now sequential scans in the course of `LIKE` queries on `posthog_person.properties::text` and `posthog_persondistinctid.distinct_id::text`, which are used by our persons search (as defined in `filter_persons()`).

> I'm not sure how to do this without these timeouts. GiST trigram indexes on these two always searched fields may help, but they are pretty expensive to build (initially and on person updates) plus aren't useful for other types of filtering.
ClickHouse though is significantly faster without indexes for all filters. I think it makes sense to override `list()` in `ClickhousePersonViewSet` to do primary filtering in CH instead of Postgres.

In this case we're dealing with an endpoint doing full text search on the postgres database. The expected behavior is to migrate this search to clickhouse.

**Comment by fuziontech** [comment]
ClickHouse++

**Comment by Twixes** [comment]
We're now using ClickHouse here.
