### ISSUE TITLE
WIP Group products / applications together

### ISSUE THREAD

**Issue by Tannergoods** [PostHog/posthog#573]
**Is your feature request related to a problem? Please describe.**
If I have several applications and products that form my business it isn't easy to understand the the way users may move from one product to another or the differences in how users retain or engage across applications

**Describe the solution you'd like**
I would like to be able to group certain actions by product - this is somewhat possible to do with page views already but then to take those grouped actions and then apply cohorts, trends, funnels functionality to a "product" and compare this to another product.

**Describe alternatives you've considered**
This is possible with multiple domains and actions allowing you to set the trend graph of one "product" and then compare it to another but it is time consuming.

**Additional context**

***Thank*** you for your feature request - we love each and every one!

**Comment by paolodamico** [comment]
We now have Group Analytics
