### ISSUE TITLE
Allow choosing own "Last n {hours,days,weeks,etc.)" timeframe in Insights

### ISSUE THREAD

**Issue by Twixes** [PostHog/posthog#5737]
## Is your feature request related to a problem?

Sometimes as as a user I'd like to be able to choose my own relative timeframe for analysis. Currently we have a few shortcuts, but that's not much. The date picker on the other hand seems really rigid.

## Describe the solution you'd like

It should be pretty straightforward to support setting a custom relative timeframe: Last <number> <unit>s. Our date parsing system already supports anything with the notation `-3h`, `-14d`, `mStart` etc.

**Comment by macobo** [comment]
Q: Do you have an example of an analysis you needed or wanted to do with this?

**Comment by Twixes** [comment]
Frankly not, because personally I mostly use Trends in PostHog, which is the one place where this is easily worked around with just setting a slightly larger timeframe and only looking at the data points I'm interested in. However for Funnels, Paths, Stickiness and other insights I can see how someone may want to put e.g. funnel conversion from the last 3 days in a dashboard, which just isn't possible currently.

**Comment by paolodamico** [comment]
Not 100% sure there's a use case for this, haven't heard any problems from users that would be addressed by this. Further, we actually just simplified and removed some options with very low usage.
