### ISSUE TITLE
Dig deeper into data points in /trends

### ISSUE THREAD

**Issue by Tannergoods** [PostHog/posthog#576]
**Is your feature request related to a problem? Please describe.**
When I click on a data point in /trends I see a list of the users that performed that action or event on that day. However I don't know anything else about their usage without investigating further

**Describe the solution you'd like**
From user list I would like to be able to create:
- Cohorts
- View Session information
- Show the user Paths from this group
- Download the users (to csv) 

![Posthog](https://user-images.githubusercontent.com/60791437/79234313-fc6ab300-7e61-11ea-9532-fd799ba46da8.png)

**Describe alternatives you've considered**
It is possible to recreate these in separate parts of PostHog or we have issues for that functionality (#334, #448)  

**Additional context**

***Thank*** you for your feature request - we love each and every one!

**Comment by Twixes** [comment]
The most important feature here, cohorts, are in.
