### ISSUE TITLE
Flash of error when reloading funnels

### ISSUE THREAD

**Issue by mariusandra** [PostHog/posthog#5762]
## Bug description

~~Three~~Four scenarios when reloading, all seem to have a common cause and momentarily display some bad data:

![2021-08-27 10 13 50](https://user-images.githubusercontent.com/53387/131096304-309413bb-a492-4831-869f-a382c2f465f6.gif)

![2021-08-27 10 16 20](https://user-images.githubusercontent.com/53387/131096316-e981cdf6-3ba2-4a28-91ae-b81bbed76576.gif)

![2021-08-27 10 18 41](https://user-images.githubusercontent.com/53387/131096357-d725f245-9342-4aad-b240-c1df4e08cee3.gif)

![2021-08-27 10 24 21](https://user-images.githubusercontent.com/53387/131097030-d8fa4e09-44b4-4d14-a2bf-57a3cd428580.gif)

## Expected behavior

I'd just like to see a loading screen without an error message.

## Environment

- [ ] PostHog Cloud
- [ ] self-hosted PostHog, version/commit: _please provide_

**Comment by paolodamico** [comment]
Couldn't reproduce anymore, but feel free to reopen if this still an issue.
