### ISSUE TITLE
Repeat filter overwriting initial filter math

### ISSUE THREAD

**Issue by EDsCODE** [PostHog/posthog#577]
**Describe the bug**
Filter setting for a copy of initial element causes a forced reset repeat

**To Reproduce**
1. Go to trends page
2. Click add element and add the exact same element as the initial element
3. Change the second 

**Expected behavior**
The above steps will cause the first filter to also set its math to DAU (presentationally, the graph still shows the correct data)

**Additional context**
Might have something to do with the first filter not having a math explicitly set

**Comment by timgl** [comment]
I can't reproduce anymore so I think this was fixed along the way
