### ISSUE TITLE
Insight filter search - error on remote items

### ISSUE THREAD

**Issue by jamesefhawkins** [PostHog/posthog#5775]
## Bug description

<img width="810" alt="Screenshot 2021-09-01 at 13 11 19" src="https://user-images.githubusercontent.com/47497682/131669002-34ed94b4-731b-4003-9439-193e4b94c775.png">

## Expected behavior

No error to appear

## How to reproduce

1. Go to insights -> trends
2. Search event properties
3. Sometimes see an error ?

## Environment

- [x] PostHog Cloud
- [ ] self-hosted PostHog, version/commit: _please provide_

**Comment by Twixes** [comment]
Does this still appear? I can't see a relevant event in Sentry, so maybe this can be closed?
