### ISSUE TITLE
Multiple autocapture properties are broken

### ISSUE THREAD

**Issue by jamesefhawkins** [PostHog/posthog#5778]
## Bug description

The `host` autocapture property became empty for our own tracking (at least) sometime on 27th August. We're still autocapturing pageviews but this field is now always empty - [see this graph](https://app.posthog.com/insights?insight=TRENDS&interval=day&display=ActionsLineGraph&events=%5B%7B%22id%22%3A%22%24pageview%22%2C%22name%22%3A%22%24pageview%22%2C%22type%22%3A%22events%22%2C%22order%22%3A0%2C%22properties%22%3A%5B%5D%7D%5D&properties=%5B%5D&filter_test_accounts=false&actions=%5B%5D&new_entity=%5B%5D&date_from=-30d&breakdown=%24host&breakdown_type=event).

Edit: `initial_referring_domain` has [the same problem](https://app.posthog.com/insights?insight=TRENDS&events=%5B%7B%22id%22%3A%22%24pageview%22%2C%22math%22%3A%22dau%22%2C%22name%22%3A%22%24pageview%22%2C%22type%22%3A%22events%22%2C%22order%22%3A0%2C%22properties%22%3A%5B%7B%22key%22%3A%22%24host%22%2C%22type%22%3A%22event%22%2C%22value%22%3A%5B%22posthog.com%22%5D%2C%22operator%22%3A%22exact%22%7D%5D%2C%22math_property%22%3Anull%7D%5D&display=ActionsLineGraph&interval=day&breakdown=%24initial_referring_domain&breakdown_type=event&filter_test_accounts=true&properties=%5B%5D&date_from=-90d).

It seems inconsistent for some but not all data (materialized columns issue?), ie [see this view](https://app.posthog.com/insights?insight=TRENDS&events=%5B%7B%22id%22%3A%22%24pageview%22%2C%22math%22%3A%22dau%22%2C%22name%22%3A%22%24pageview%22%2C%22type%22%3A%22events%22%2C%22order%22%3A0%2C%22properties%22%3A%5B%7B%22key%22%3A%22%24host%22%2C%22value%22%3A%22posthog.com%22%2C%22operator%22%3A%22icontains%22%2C%22type%22%3A%22event%22%7D%2C%7B%22key%22%3A%22%24host%22%2C%22value%22%3A%22app.posthog.com%22%2C%22operator%22%3A%22not_icontains%22%2C%22type%22%3A%22event%22%7D%5D%2C%22math_property%22%3Anull%7D%5D&display=ActionsLineGraph&interval=day&breakdown=%24initial_referring_domain&breakdown_type=event&filter_test_accounts=true&properties=%5B%5D&actions=%5B%5D&new_entity=%5B%5D&date_from=yStart).

## Expected behavior

Host should still be working.

## Environment

- [x] PostHog Cloud
- [ ] self-hosted PostHog, version/commit: _please provide_

**Comment by macobo** [comment]
This was indeed caused by the experimental materialized columns work - when testing out queries to backfill manually I fat-fingered `host` instead of `$host` in some queries (cc #5463).

This was a cloud-specific bug. 

Verifying/fixing any other properties that were affected, will close afterwards :)

**Comment by macobo** [comment]
Verified all other materialized columns were not fat-fingered.

@jamesefhawkins initial referring domain query you linked looks good to me - what's wrong with it? :)
