### ISSUE TITLE
Don't allow impossible combinations of time ranges on Trends

### ISSUE THREAD

**Issue by jamesefhawkins** [PostHog/posthog#5780]
## Bug description

Why this was so confusing:

I went from a 30 day window on a dashboard to the underlying Trend [page here](https://app.posthog.com/insights?insight=TRENDS&date_to=2021-01-31&display=ActionsLineGraph&actions=%5B%7B%22id%22%3A%222671%22%2C%22type%22%3A%22actions%22%2C%22order%22%3A0%2C%22name%22%3A%22User%20Signed%20Up%22%2C%22math%22%3A%22dau%22%2C%22math_property%22%3Anull%2C%22properties%22%3A%5B%7B%22key%22%3A%22is_organization_first_user%22%2C%22value%22%3A%5B%22true%22%5D%2C%22operator%22%3A%22is_not%22%2C%22type%22%3A%22person%22%7D%5D%7D%5D&filter_test_accounts=true&properties=%5B%5D&date_from=-30d&interval=week)

This automatically changed the time period to 'last 7 days'

I then switched it to 'weekly'. The week wasn't done so I got the error:

<img width="743" alt="Screenshot 2021-09-01 at 15 09 12" src="https://user-images.githubusercontent.com/47497682/131686347-bd420b4f-daa6-47e8-8180-315509c404c6.png">

My first reaction was "posthog is failing to return the data, I know there is event data in this time period". However, this is in fact because last 7 days + weekly is an impossible combination to return a datapoint for in a way we can display with this visualization type.

## Expected behavior

We shouldn't let users choose an impossible combination of filters like  weekly and last seven days. We should just grey one out in this case.

## How to reproduce

1. Apply filters [like this](https://app.posthog.com/insights?insight=TRENDS&date_to=2021-01-31&display=ActionsLineGraph&actions=%5B%7B%22id%22%3A%222671%22%2C%22type%22%3A%22actions%22%2C%22order%22%3A0%2C%22name%22%3A%22User%20Signed%20Up%22%2C%22math%22%3A%22dau%22%2C%22math_property%22%3Anull%2C%22properties%22%3A%5B%7B%22key%22%3A%22is_organization_first_user%22%2C%22value%22%3A%5B%22true%22%5D%2C%22operator%22%3A%22is_not%22%2C%22type%22%3A%22person%22%7D%5D%7D%5D&filter_test_accounts=true&properties=%5B%5D&date_from=-30d&interval=week)

**Comment by clarkus** [comment]
Somewhat related https://github.com/PostHog/posthog/issues/5557
