### ISSUE TITLE
Add instructions to the preview docker image for configuring the tool on /demo/ 

### ISSUE THREAD

**Issue by jamesefhawkins** [PostHog/posthog#58]
This should be bottlenecked until we get some people to start download the docker image and is here as a placeholder.

Currently, the docker image looks very empty. Since it is hosted locally, it is hard to configure or set up.

We have a nice /demo, with an example HogFlix website. This is bundled with the image. However, there are no instructions for how to do this in the UX (we should create a separate documentation ticket for that too).

**Comment by timgl** [comment]
Done
