### ISSUE TITLE
Measuring “Paths” success

### ISSUE THREAD

**Issue by paolodamico** [PostHog/posthog#5834]
As we prepare to build and then launch the new Paths feature (#5665) it's important to consider how we'll measure success for this feature, and any other metrics that can later help us improve the feature.

Aside from defining the key metrics it'll be important to set up instrumentation properly and dashboard for tracking.

**Comment by EDsCODE** [comment]
Some overarching questions to answer after deploying the featureset

(1) `insight viewed` paths before and after releasing new UI/feature set. Total Volume and Unique Users
(2) Measure how people are getting to paths. Are more coming directly from funnels now? Where do they go after?
(3) Does path usage predict retention?
(4) Is path usage more sticky now than before?

Given our focus on paths being useful in contributing to a user's ability to understand causes (https://github.com/PostHog/posthog/issues/5545), the strongest signal of success would be seeing users consistently going from funnels to paths (2). 

Next steps: 
- define what metric determines "consistently"
- Add current metrics

**Comment by paolodamico** [comment]
Important to remember that we dropped a key use case from Paths (exploration), and are focusing on new ones. I've also seen some confusion around solving these problems with Paths. Let's make sure first we're solving for those use cases.

### Proposal
1. Find 3-4 users with the problems we want to address, and get **qualitative data points** on whether Paths is actually providing useful insights and solving their problem. _We should do this as soon as we have something functional. Based on recent feedback, I'm not sure Paths will actually solve for our users._
2. Assuming (1) goes well, we'll want to have a **quant measure of usage**. I think we can simplify this: What's the equivalent of our "discovered learning"? What's the most straightforward signal of value?
3. If Paths is successful (_still a big if_) (1) & (2), we'll want more data points around **behavioral usage** to know how to improve it. My suggestion would be to spend 30 mins before shipping just making sure we have some basic tracking (i.e. main actions and relevant `data-attr`s).
