### ISSUE TITLE
Improve self-hosted onboarding

### ISSUE THREAD

**Issue by mariusandra** [PostHog/posthog#5836]
## Is your feature request related to a problem?

The self-hosted onboarding experience is currently weird. From getting a HTTP connection on your instance... to making insights, you are taken through three visually different pages. 

![2021-09-07 10 06 10](https://user-images.githubusercontent.com/53387/132308451-a59d3e3f-0f37-4468-94f4-4276d590ada2.gif)

View them in the storybook here: https://storybook.posthog.net/?path=/story/posthog-onboarding-1-preflight--initial

## Describe the solution you'd like

These could be combined to one signup screen.

## Describe alternatives you've considered

I think the "ingestion" screen should be redone to take into account import plugins. For example, on a new posthog instance I set up I just enabled the "github star sync" plugin as my data source.

**Comment by paolodamico** [comment]
Closing in favor of #5860

**Comment by paolodamico** [comment]
Re-opening this as we're tackling only signup/login on #5860. The scope of this issue would then be the preflight screen and the ingestion wizard process.

**Comment by kappa90** [comment]
Closing as this is outdated.
