### ISSUE TITLE
Godot Engine Plugin

### ISSUE THREAD

**Issue by fire** [PostHog/posthog#585]
**Is your feature request related to a problem? Please describe.**
Posthog support in Godot Engine for game analytics.

**Describe the solution you'd like**
Need help testing posthog server-side. Is there a test organization I can use on posthog?

A demo using posthog. I can do the game engine changes, but don't have a posthog account in the datacenter.

**Describe alternatives you've considered**
Not sure how to test.

**Additional context**
https://github.com/WolfgangSenff/KylesGodotPlugins/tree/PostHot-Plugin/PostHogPlugin

Based on https://docs.posthog.com/#/integrations/api api.

***Thank*** you for your feature request - we love each and every one!

**Comment by timgl** [comment]
This is great! We always love having more libraries.

In terms of testing, we don't have a formal test suite for libraries. Luckily the api is pretty simple. If you don't want to host PostHog you could sign up to a hosted account on [app.posthog.com](app.posthog.com).

**Comment by erlend-sh** [comment]
Updated link for the Godot example: https://github.com/WolfgangSenff/KylesGodotPlugins/tree/master/PostHogPlugin

There is a dedicated solution for this in the games space called [Backtrace](https://backtrace.io/).

https://github.com/backtrace-labs/backtrace-unity

**Comment by fire** [comment]
@erlend-sh I don't see a Github repo to run my own BackTrace? Is Backtrace opensource?

**Comment by erlend-sh** [comment]
Nope, it’s closed source. Was just sharing it as a point of reference.

[Sentry](https://sentry.io/for/gaming/) on the other hand is a mix of open and shared source, and they also have a Unity plugin:

https://github.com/getsentry/sentry-unity

**Comment by fire** [comment]
https://gitlab.com/glitchtip is an implementation of a Sentry compatible api.
