### ISSUE TITLE
Create cohort form does not preserve data properly

### ISSUE THREAD

**Issue by paolodamico** [PostHog/posthog#5852]
## Bug description

When creating a cohort, if I change a property, the name I previously set is lost (see recording).

![image](https://user-images.githubusercontent.com/5864173/132471198-b70f4716-46ec-44b7-921f-5c9cdc404dbe.gif)

## Expected behavior

Name should be preserved when editing properties.

## How to reproduce

See attached recording.

## Environment

- [X] PostHog Cloud
- [X] self-hosted PostHog, version/commit: `master`

## Additional context

This feature was previously made by @EDsCODE but not sure if it should still be Core Analytics or Core Experience. @mariusandra ?

**Comment by timgl** [comment]
This was fixed by #5851
