### ISSUE TITLE
Sort project list by name

### ISSUE THREAD

**Issue by dknowles-vsk** [PostHog/posthog#5858]
## Is your feature request related to a problem?
In the project dropdown list, projects are not sorted. This is annoying when I need to find a project or when I need to go through the projects one by one (e.g. to update a shared setting, like the list of test users to exclude).

## Describe the solution you'd like
Sort the project list alphabetically.

## Describe alternatives you've considered
Manually scanning the list.

## Additional context
Our organization uses a lot of projects, so this may be unique to us or a small number of users.

**Comment by Twixes** [comment]
Great point, resolved this in https://github.com/PostHog/posthog/pull/5861, now things are orderly.
