### ISSUE TITLE
Update Login and Cloud registration pages

### ISSUE THREAD

**Issue by corywatilo** [PostHog/posthog#5860]
Now that we have a [new website look and feel](https://posthog.com), we should update the login page and Cloud registration page to match.

## [Login page](https://www.figma.com/file/g1UCTW9ZX21GU85hLsWB31/Website-concepts?node-id=1064%3A30629)

Assuming this page will be used for both Cloud and self-hosted customers, the only difference we'd want to make is to show/hide the "Cloud" portion of the title.

![image](https://user-images.githubusercontent.com/154479/132546310-990ad81b-ce70-44be-98d0-06801a1c849a.png)

### [Initial state](https://www.figma.com/file/g1UCTW9ZX21GU85hLsWB31/Website-concepts?node-id=1064%3A30691)

![image](https://user-images.githubusercontent.com/154479/132547739-ce6a1b1b-9831-440c-87a9-2db565a35280.png)

### [Fields filled in](https://www.figma.com/file/g1UCTW9ZX21GU85hLsWB31/Website-concepts?node-id=1066%3A31083)

As we do today, we should show the tooltip when the field is focused (not when validation fails). We can have @lottiecoxon create a SecurityHog character, possibly with a bobby hat and nightstick.

![image](https://user-images.githubusercontent.com/154479/132547769-3ed54960-c938-4dcc-8450-2bff1f4ac53e.png)

## Fonts

We want the look and feel to be consistent with the new website, but since we use a licensed font that can't be distributed in an open source package, @clarkus and I found a very similar open source font, [+Jakarta Sans](https://tokotype.github.io/plusjakarta-sans/) that can be used on these pages.

The eventual goal would be to also use this font for titles/subtitles within the app, to bring more visual consistency between website and app.

**Comment by paolodamico** [comment]
Absolutely love this @corywatilo, looks great ❤️! (thanks for providing the font info too). Now that we're working on this could you also help us with a design for [the preflight page](https://storybook.posthog.net/?path=/story/posthog-onboarding-1-preflight--initial) and the [ingestion modal](https://storybook.posthog.net/?path=/story/posthog-onboarding-3-ingestion--initial)?

In addition, we should consider the invite signup page that needs to be updated too.

<img width="600" alt="" src="https://user-images.githubusercontent.com/5864173/132641851-a6a3e2bd-85b3-40aa-84d2-88f639784000.png">
<img width="600" alt="" src="https://user-images.githubusercontent.com/5864173/132641863-2dcbab21-41b8-448b-bf95-721634fea5c9.png">
<img width="600" alt="" src="https://user-images.githubusercontent.com/5864173/132641868-96070e5b-2468-41ee-b690-d49daa6a6881.png">


Also minor comments on the current design:
- We should also have a button for Single sign-on login (as this can be with any provider, we can't really use a brand logo).
- We should implement an error state for when the signup fails (e.g. there's already an account with your email address).
- We should show how this should look on mobile

**Comment by corywatilo** [comment]
[Here's an artboard](https://www.figma.com/file/g1UCTW9ZX21GU85hLsWB31/Website-concepts?node-id=1085%3A29906) with all of the invite screens and mobile template.

Let's tackle the onboarding stuff in a separate issue?

**Comment by clarkus** [comment]
Looking at this again, I wonder if it'd be worth aligning the form inputs and submission button to the styles used within the product. We're typically using 40–48px tall containers with 4px border radius. It's a small thing, but it might help returning users a bit?

**Comment by corywatilo** [comment]
Assuming the PostHog Cloud signup page is unique to us*, I'd be down for just using `Matter SQ` there and having the auth (and app-related) flow using whatever font stack we decide to use in-app.

*Just need to get our fonts loaded on that page and make sure CORS is set up to accept hits from `app.posthog.com`

**Comment by clarkus** [comment]
Howdy! I am working through some changes for alignment at https://www.figma.com/file/gQBj9YnNgD8YW4nBwCVLZf/?node-id=3558%3A32653. Edit - I just wrapped up changes to align the workflows. This is ready for a review and comments have been added to figma for @corywatilo and @paolodamico 

**Notable changes**
- Uses form fields that align more with product
- Retains branding assets from marketing - branding assets, bg color, header treatments and font-sizing, CTA colors, etc.
- Changes color palettes to align with those used in product - note that this does not apply to decorative assets like hedgehogs. It's purely so components match other instances in the product. 

![Register (filled in)](https://user-images.githubusercontent.com/254612/134077420-a31d3f02-493e-4321-bb89-7883518e3266.png)

**Comment by paolodamico** [comment]
Added some final comments on the Figma, nothing major, thanks @clarkus!

**Comment by clarkus** [comment]
The most recent round of feedback has been resolved - the screens shown here should be representative of the final solution barring any other feedback. https://www.figma.com/file/gQBj9YnNgD8YW4nBwCVLZf/?node-id=3558%3A32653

**Comment by paolodamico** [comment]
Indeed, this is fully to be implemented!

**Comment by paolodamico** [comment]
We still have the invite signup pages to update, but out of the scope of this issue, so closing.
