### ISSUE TITLE
PostHog doesn't build on Heroku because of `xmlsec`

### ISSUE THREAD

**Issue by Twixes** [PostHog/posthog#5862]
## Bug description

Since https://github.com/PostHog/posthog/pull/5681 added Python package [`xmlsec`](https://pypi.org/project/xmlsec/) as a dependency, PostHog doesn't build on Heroku, because that package is bindings for a C library that needs to be installed on the system.

See this build log from a review app:
<img width="1212" alt="Screen Shot 2021-09-08 at 19 46 50" src="https://user-images.githubusercontent.com/4550621/132558941-8ad96652-dac7-4a7f-b259-edc30452bb95.png">

@paolodamico 

## How to reproduce

1. Try to launch PostHog on Heroku from `master`.

**Comment by macobo** [comment]
Since this affects dev environments as well: How about we make this requirement conditional via env vars somehow? :)

**Comment by paolodamico** [comment]
Yes, I'm not sure how to fix this in Heroku without using a community buildpack. Should we fork a buildpack ?

In any case, I'll work the env vars route.
