### ISSUE TITLE
Calculate funnels sync via API, and not through Celery

### ISSUE THREAD

**Issue by mariusandra** [PostHog/posthog#5873]
## Is your feature request related to a problem?

When fetching data for insights, we treat funnels as a special case, and calculate them through a Celery background task. The frontend then periodically polls for the result. All other insights are calculated inside the standard API request-response cycle. 

This used to be necessary since postgres funnels would be really slow to calculate, but is such a split still needed for Clickhouse funnels? On the frontend it makes a lot of things more complicated, including solving https://github.com/PostHog/posthog/issues/5865 (sequential dashboard reloads) and https://github.com/PostHog/posthog/issues/5134 (query cancellation). 

Hence: is it still necessary to calculate funnels through a celery task?

CC @macobo 

## Describe the solution you'd like

Get rid of the celery task and a lot of other code

## Describe alternatives you've considered

Keep writing more code and workarounds, e.g. to solve the sequential dashboard reload issue. https://github.com/PostHog/posthog/issues/5865

## Additional context

It's also really easy to make bugs, such as this polling happening indefinitely due to an error of sorts:

![2021-09-09 12 54 02](https://user-images.githubusercontent.com/53387/132674001-2ade0a9a-537b-44ec-a4e7-bf5b7f765efa.gif)

**Comment by macobo** [comment]
> Hence: is it still necessary to calculate funnels through a celery task?
> CC @macobo

At minimum for postgres-based installations this is a yes. 

For clickhouse though we can safely get rid of this.

**Comment by neilkakkar** [comment]
mission sorted
