### ISSUE TITLE
Merge funnel API queries

### ISSUE THREAD

**Issue by mariusandra** [PostHog/posthog#5878]
## Is your feature request related to a problem?

We currently load the "time conversion bins" funnel view [in two steps](https://github.com/PostHog/posthog/blob/cfd7e586ac144a0fb6c18f90a1657db9897d033a/frontend/src/scenes/funnels/funnelLogic.ts#L164):

```js
const result = await pollFunnel<FunnelStep[] | FunnelStep[][]>({
    ...apiParams,
    refresh,
    // Time to convert requires steps funnel api to be called for now. Remove once two api's are functionally separated
    funnel_viz_type:
        filters.funnel_viz_type === FunnelVizType.TimeToConvert
            ? FunnelVizType.Steps
            : apiParams.funnel_viz_type,
})

if (filters.funnel_viz_type === FunnelVizType.TimeToConvert) {
    const binsResult = await pollFunnel<FunnelsTimeConversionBins>({
        ...apiParams,
        ...(refresh ? { refresh } : {}),
    })
}
```

## Describe the solution you'd like

I'd like to make just one query. This makes caching dashboard results much easier.

**Comment by neilkakkar** [comment]
Curious: Why does this happen? Is it something to do with the API design?

**Comment by mariusandra** [comment]
I think @alexkim205 has most context on this. From what I remember, when showing the time conversion bits there is some data regarding steps that's not in the `FunnelVizType.TimeToConvert ` query, warranting the regular `FunnelVizType.Steps` query as well. I didn't go deeper into the issue, so I'm not sure what exactly is missing.

**Comment by alexkim205** [comment]
Yeah that's correct. `FunnelVizType.TimeToConvert` uses data in the `steps` key returned from the original `FunnelVizType.Steps` query to calculate some conversion metrics shown in the time conversion header. The solution requiring minimal frontend refactoring (and overall effort) would be to also return the same steps data in the time to convert query, although I'm not sure if that's difficult to do. Another solution could be to figure out what metrics we're calculating on the frontend, and just calculate those on the backend. @neilkakkar what are your thoughts?

**Comment by mariusandra** [comment]
Not mentioned in the issue, but time to convert funnels are actually broken on shared dashboards because of this. It would be good to see if there's an easy solution we can adopt here.

**Comment by neilkakkar** [comment]
It doesn't make sense to query the backend again to get these values, since we're already doing it in the main time to convert query. Sounds like it also approximately doubles query time.

If I understand correctly, all we need is the total average conversion time, right? Could you give me an example of what extra information the "steps" provide? ( I tried looking at the UI code, but can't seem to get this 😅 ) 

cc: @alexkim205 . Happy to fix, once I understand what the issue is here^

**Comment by mariusandra** [comment]
@neilkakkar I think the issue here was fixed with https://github.com/PostHog/posthog/pull/6002 ?

**Comment by neilkakkar** [comment]
I did see that, but I guess my question is: I don't get what extra information steps give you there? (except running the same query 2x, and slowing down the API call). We're already sending the conversion time between steps, which is the only extra information displayed in the header?

**Comment by mariusandra** [comment]
I need to dig in the code enough to answer that. @alexkim205 might know off the top of his head. You may be right and we could eliminate some big inefficiency here.

**Comment by neilkakkar** [comment]
Aye, agreed. I dug a bit but couldn't figure it out, hence will just wait for Alex to answer super quickly vs either of us spending longer digging into this :)

**Comment by alexkim205** [comment]
This is a really confusing part of our code that was introduced during the fork so thanks for looking into it. The only information that is deduced from steps that we also need in time to convert is average time to convert. Here is where we calculate that on the frontend from `steps`. https://github.com/PostHog/posthog/blob/d6e410b3a9a2dbf64384177ee2bdcc6832346b70/frontend/src/scenes/funnels/funnelLogic.ts#L416-L416

**Comment by neilkakkar** [comment]
I see! We're already sending this in the time to convert response, aren't we?

https://github.com/PostHog/posthog/blob/master/ee/clickhouse/queries/funnels/funnel_time_to_convert.py#L23

This one takes into account both the from and to steps chosen in the dropdown.

**Comment by alexkim205** [comment]
Oh awesome, I guess we didn't cleanup the logic here when this was added. I'll clean this up in a separate PR 

Update: #6046
