### ISSUE TITLE
Funnels don't seem to have their name saved

### ISSUE THREAD

**Issue by jamesefhawkins** [PostHog/posthog#59]
The funnel naming for james@posthog.com at app.posthog.com just doesn't seem to save names.

I can't see any errors appearing in the Console.

Do I need to click 'save' somewhere and the button isn't appearing?

![Screenshot 2020-02-10 at 13 08 49](https://user-images.githubusercontent.com/47497682/74190080-88642280-4c06-11ea-91bc-9301f0153905.png)

**Comment by timgl** [comment]
@jamesefhawkins I'm pretty sure this is fixed now, though wasn't able to recreate your exact issue. Would you mind retrying on app?

**Comment by timgl** [comment]
@jamesefhawkins closing this as I assume no response means it works? Let me know if not?
