### ISSUE TITLE
Breakdown insight by `data-` attributes

### ISSUE THREAD

**Issue by mariusandra** [PostHog/posthog#5914]
## Is your feature request related to a problem?

`posthog-js` autocaptures clicks on links, along with some related attributes:

![image](https://user-images.githubusercontent.com/53387/133070304-84d81727-35aa-49db-bc40-bfb6e7cb3065.png)

However it's hard to use this data in the interface.

## Describe the solution you'd like

I'd like to breakdown an insight by a data-attribute.

## Describe alternatives you've considered

- Exporting a list of events as CSV, and getting the data from there (bad news: elements are missing for postgres)
- Running a SQL query to get the attributes and get the breakdown that way
```sql
select
    event.*,
    element.attributes->'attr_data-attr' as report_id
from posthog_event event
    left join posthog_elementgroup elementgroup on elementgroup.hash = event.elements_hash
    left join posthog_element element on element.group_id = elementgroup.id
where
    event.event = '$autocapture'
```

## Additional context

The need came from a customer who wanted to breakdown clicked links by a `data-report-id` attribute.

**Comment by EDsCODE** [comment]
The breaking down on a data-attr is possible. To clarify, in what context is the breakdown being applied? Would the use case be specifically for $autocapture events/actions defined with $autocapture events and breaking those insights down by the `data-attr`?

**Comment by paolodamico** [comment]
+1 on understanding the full context here of the problems they're trying to solve. For instance, would breaking down on other attributes be useful? Depends on the problems they're solving.

**Comment by neilkakkar** [comment]
Usecases being solved: https://posthogusers.slack.com/archives/C01GLBKHKQT/p1637927087148700
