### ISSUE TITLE
Events CSV export does not show Elements in Postgres

### ISSUE THREAD

**Issue by mariusandra** [PostHog/posthog#5915]
## Bug description

The CSV you get when clicking this button is different in postgres vs clickhouse.

<img width="1274" alt="Screenshot 2021-09-13 at 12 53 18" src="https://user-images.githubusercontent.com/53387/133071577-76c2ac64-d824-465c-a1f3-3dcb9c98c285.png">

- Postgres CSV export doesn't contain elements
- Clickhouse contains

## Expected behavior

Both exports should contain elements

## Environment

- [ ] PostHog Cloud
- [x] self-hosted PostHog (ClickHouse-based), version/commit: _please provide_
- [x] self-hosted PostHog (Postgres-based, legacy), version/commit: _please provide_

**Comment by Twixes** [comment]
Closing as Postgres is out.
