### ISSUE TITLE
Reset button doesn't clear Compare Previous

### ISSUE THREAD

**Issue by joethreepwood** [PostHog/posthog#5916]
## Bug description

I built a graph with 'compare previous' engaged to compare the previous 30 days. I pressed reset to clear all filters. The compare previous button didn't untick, but the information for the previous period did disappear from the graph. As a result, 'compare previous' seemed to be enabled but the information wasn't accurate. In order to get the correct information from the previous period I needed to disengage the 'compare previous' toggle, then re-engage.  

<img width="2560" alt="Screenshot 2021-09-13 at 13 17 38" src="https://user-images.githubusercontent.com/84011561/133082150-7f87ac75-cb76-4f90-970d-30e2018ccb0f.png">
<img width="2560" alt="Screenshot 2021-09-13 at 13 17 46" src="https://user-images.githubusercontent.com/84011561/133082163-c769f59f-fb61-46a2-824a-94c0cbfeeffa.png">
<img width="2560" alt="Screenshot 2021-09-13 at 13 17 51" src="https://user-images.githubusercontent.com/84011561/133082169-7628f45c-22a4-48bf-8f08-71aa8862641c.png">

## Expected behavior

Pressing 'Reset' should either untick the compare previous box, or leave it check and include the relevant information. 

## How to reproduce

1. Build a query comparing a previous period.
2. Reset it. 

## Environment

- [ ] PostHog Cloud
- [x ] self-hosted PostHog (ClickHouse-based), version/commit: _please provide_
- [ ] self-hosted PostHog (Postgres-based, legacy), version/commit: _please provide_

**Comment by samwinslow** [comment]
Not to hijack the issue, but for anyone looking at this — there's an additional minor issue related to Compare Previous right here: https://github.com/PostHog/posthog/issues/5918

**Comment by pauldambra** [comment]
The UI has changed since this report. But also this seems to have been fixed in the nearly a year since it was reported

![2022-08-24 08 02 54](https://user-images.githubusercontent.com/984817/186352815-313be840-67a0-4bea-8a01-b9b59951d7de.gif)
