### ISSUE TITLE
Compare Previous table view has incorrect day indexing

### ISSUE THREAD

**Issue by samwinslow** [PostHog/posthog#5918]
## Bug description

As you can see here, choosing "Compare previous" causes the main graph to switch to `Day 0, 1, 2...` indexing, but the table is still indexed by dates.

<img width="598" alt="Screen Shot 2021-09-13 at 8 25 00 AM" src="https://user-images.githubusercontent.com/4645779/133083107-8eeb7628-2149-4cc5-a3d2-643b6fc72640.png">

## Expected behavior

The table headers should either use `Day #` indexing, OR show multiple dates that indicate 1. the date from current period and 2. the date from previous period. Whichever makes the most sense and looks best from a design perspective.

## How to reproduce

1. "Compare previous" on any time series insight

## Environment

- [ ] PostHog Cloud
- [ ] self-hosted PostHog (ClickHouse-based), version/commit: _please provide_
- [ ] self-hosted PostHog (Postgres-based, legacy), version/commit: _please provide_

**Comment by mariusandra** [comment]
Related: https://github.com/PostHog/posthog/issues/4705
