### ISSUE TITLE
Person modal users misaligned

### ISSUE THREAD

**Issue by mariusandra** [PostHog/posthog#5922]
## Bug description

The users here are strangely right-aligned:

![image](https://user-images.githubusercontent.com/53387/133107300-9be12751-0f5b-4b7a-82d1-34d2a8496c21.png)

## Expected behavior

I'd expect them to be left-aligned

## How to reproduce

1. Identify some users
2. Click on trends
3. See some problems

## Environment

- [ ] PostHog Cloud
- [x] self-hosted PostHog (ClickHouse-based), version/commit: _please provide_
- [x] self-hosted PostHog (Postgres-based, legacy), version/commit: _please provide_

## Additional context

1. Long distinct IDs get cut correctly:

![image](https://user-images.githubusercontent.com/53387/133107433-e5ea36f3-2f6f-4a6e-ad52-fc45d9a27693.png)

2. This is also off:
![image](https://user-images.githubusercontent.com/53387/133107614-a90cfc39-70ab-44df-8e1a-1dd7ecb5a47a.png)

**Comment by liyiy** [comment]
Also this:

<img width="368" alt="Screen Shot 2021-09-13 at 11 12 35 AM" src="https://user-images.githubusercontent.com/25164963/133109813-72accb94-24ff-41ae-9161-1b489b796b74.png">
