### ISSUE TITLE
Inconsistent options for Viewing / Configuring dashboard items

### ISSUE THREAD

**Issue by samwinslow** [PostHog/posthog#5924]
Funnels are currently the only dashboard item type with this large "Configure" banner. It pops up on hover, which in my opinion is a bit annoying as it blocks content behind it. In the example below, if you're using a mouse which doesn't support horizontal scroll, it's impossible to view the whole funnel because the scrollbar is covered.

<img width="874" alt="Screen Shot 2021-09-13 at 11 01 53 AM" src="https://user-images.githubusercontent.com/4645779/133108008-7c5fb05a-e622-4be5-853c-340b1fa3dc83.png">

I think we should have a standard way to indicate common actions on dashboard items. One way I explored this during the hackathon was this:

<img width="442" alt="Screen Shot 2021-09-13 at 10 57 23 AM" src="https://user-images.githubusercontent.com/4645779/133108327-fa167c81-ac2f-404c-81a3-32ef64959f2c.png">

... which looks better to me than:

<img width="438" alt="Screen Shot 2021-09-13 at 10 55 45 AM" src="https://user-images.githubusercontent.com/4645779/133108669-a5a620fb-90f7-4f26-a30c-dfab0b53d870.png">

But my solution still isn't perfect as it causes the title to truncate.

Cc'ing @clarkus as this is most of all a design question.

**Comment by mariusandra** [comment]
Hmm... This is honestly the first time I see this black box. How do you get it to open?

**Comment by samwinslow** [comment]
> Hmm... This is honestly the first time I see this black box. How do you get it to open?

I can't remember exactly how I found it but I do know it was demo data. These lines seem to be the cause — a year old:

frontend/src/scenes/dashboard/DashboardItem.tsx:290:

```jsx
{item.is_sample && (
                <div className="sample-dasbhoard-overlay">
                    <Button onClick={() => router.actions.push(link)}>Configure</Button>
                </div>
            )}
```

**Comment by paolodamico** [comment]
This is a super old thing that we were testing out for showcasing different types of insights in a sample prebuilt dashboard. The reason to have this thing was that funnels rely on users "configuring" them as opposed to simple trends graphs that can just work on top of page views. Great that we're getting rid of it!
