### ISSUE TITLE
Changing a cohort filter doesn't update cohort people

### ISSUE THREAD

**Issue by yakkomajuri** [PostHog/posthog#5927]
## Bug description

When I change the filters on the cohort, the filters change but the people in the cohort don't update (even if the interface tells me they do).

https://user-images.githubusercontent.com/38760734/133126491-59f0fb1f-0cf2-43ee-a7ed-ea33853c65c6.mov

## How to reproduce

1.
2.
3.

## Environment

- [ ] PostHog Cloud
- [ ] self-hosted PostHog (ClickHouse-based), version/commit: _please provide_
- [ ] self-hosted PostHog (Postgres-based, legacy), version/commit: _please provide_

**Comment by liyiy** [comment]
I wonder if this has anything to do with clickhouse test data? Tried to repro this in prod but other than the merging persons issue, it works as expected.

**Comment by EDsCODE** [comment]
@yakkomajuri I think you may have caught some lag in the updating. That cohort that you updated seems to be correct now

**Comment by rcmarron** [comment]
I can repro it pretty consistently on prod. Here is a quick video of it. And the results still seem to be wrong ~ 5 min later.

https://user-images.githubusercontent.com/4813045/133137378-5fbf2bec-a1e7-46a3-8279-cf0c71d7949d.mov

If it is lag in the cohort query results being updated, I wonder if we need to make that clearer in the UI? Or recalculate it on save?

**Comment by EDsCODE** [comment]
Ah I see, I can pick this up right now since it's time sensitive
