### ISSUE TITLE
Including actions in paths

### ISSUE THREAD

**Issue by EDsCODE** [PostHog/posthog#5928]
## Is your feature request related to a problem?

*Please describe.*
Paths currently only tracks events with no ability to determine whether events are actions or not.  

## Describe the solution you'd like
Actions should be a category/included somehow into the paths tracking.

## Describe alternatives you've considered
We currently allow autocaptured events

## Additional context
This feature will require some architectural changes/performance enhancements (#4625) before being achievable. Currently, our clickhouse solution determines actions at query-time but this is infeasible for paths since it would require labelling all events with their respective actions.

**Comment by macobo** [comment]
This came up as feedback in users slack: https://posthogusers.slack.com/archives/C01GLBKHKQT/p1642456694015700
