### ISSUE TITLE
Filtering events on the events page doesn't work as I'd expect it to.

### ISSUE THREAD

**Issue by rcmarron** [PostHog/posthog#5952]
## Is your feature request related to a problem?

It isn't clear that the filters on the events page only query against recent events. It could lead a user to loose trust in the product as they're getting started.

My path:
* Went to the events page
* Saw events with a source='web'
* Made a filter to see only those events
* After applying the filter the events were no longer there

![image](https://user-images.githubusercontent.com/4813045/133358056-ef6944c4-2132-42fe-8ff0-a18629c7c7ca.png)

## Describe the solution you'd like
Be very clear that the list is only showing 'real-time' events, and that I should not expect old events after filtering. I could imagine something like a loading animation that says "waiting for new events to arrive"

## Describe alternatives you've considered
Do client side filtering, so events existing in the list that match the filter are still there after the filter.

**Comment by clarkus** [comment]
Related #5546

**Comment by mariusandra** [comment]
Hey, you should expect old events after filtering, going back until the beginning. The `source` column is actually not a property on the event, but it's taken from the `$library` property instead.

There is a bug here: the "There are new events" is not reset when changing filters, but that's now [fixed here](https://github.com/PostHog/posthog/pull/5957).

Also, I had to edit your post and remove a png with some personal/client data on them. Watch out for this kind of stuff! :)
