### ISSUE TITLE
Filter sessions by start/end point

### ISSUE THREAD

**Issue by mariusandra** [PostHog/posthog#5958]
## Is your feature request related to a problem?

Requested by a user to solve their need.

## Describe the solution you'd like

I'd like to also filter by the start/end point. Filtering by duration is already possible.

![image](https://user-images.githubusercontent.com/53387/133394693-940ee831-cc7f-42e0-8bae-2b72b3dc43f8.png)

## Describe alternatives you've considered

- Going through this list page by page and manually filtering it.
- Developing a greasemonkey script that gives me a button that uses checks for the nth column in the table and hides it if its contents don't match, saving human power in the process.

## Additional context

Requested via papercups.

**Comment by paolodamico** [comment]
With the resolution from #4884, this is now a moot point. Closing.
