### ISSUE TITLE
Endlessly scrolling property filter

### ISSUE THREAD

**Issue by mariusandra** [PostHog/posthog#5962]
## Is your feature request related to a problem?

This tool is great:

![image](https://user-images.githubusercontent.com/53387/133401206-98d2fb3b-402f-43d7-a377-c220c1a06061.png)

But with a lot of tabs and a few scattered results, it can get hard to find things:

![image](https://user-images.githubusercontent.com/53387/133401370-dcee419e-8792-4528-8a91-e0456f8472b6.png)

![image](https://user-images.githubusercontent.com/53387/133401392-be3fc8e9-2f9e-4202-8722-48a4bdc41d56.png)

## Describe the solution you'd like

I'd like an endless list, which would dynamically update the tabs. Basically the four infinitely scrolling lists should be combined into one, with one extra item between sets to denote a new category.

![image](https://user-images.githubusercontent.com/53387/133401756-6f8b84c9-819b-40a9-8900-6cbbdcc716f5.png)

If I click the tabs, the list just scrolls to the right location. Clicking tabs with "0" does nothing.

## Describe alternatives you've considered

Clicking though all the tabs to find what I want.

## Additional context

This will get more needed when we add other tabs to the filter. For example to [separate posthog and other events](https://github.com/PostHog/posthog/issues/5960), or when adding support for groups.

**Comment by Twixes** [comment]
This used to be the case, right? But we moved to tabs to make handling lots of options easier, while clarifying different filtering types. I don't think it's a good idea to keep tabs AND combine them in the search list at the same time, as then the separation becomes really confusing.

**Comment by paolodamico** [comment]
I think the right solution is #5381 and allowing users to switch with "tab" hotkey (or other simple key), thoughts? CC @clarkus

**Comment by clarkus** [comment]
There are other considerations here - group analytics is adding 1–5 extra items to this component. I think we're reaching the limit of tabs and need to explore other options here. Being able to switch easily makes this a bit less painful, but the component needs to be updated to account for the higher volume of events and the higher volume of categories / tabs. 

Related discussion at https://github.com/PostHog/posthog/issues/7073#issuecomment-978125031

**Comment by clarkus** [comment]
Here's a concept for a flattened property list. The thing that's missing is the tab navigation that lets you quickly jump to a category. 

This idea be very reliant on, related to:
- https://github.com/PostHog/posthog/issues/7315
- https://github.com/PostHog/posthog/issues/5351
- https://github.com/PostHog/posthog/issues/5312

![Property list - flat](https://user-images.githubusercontent.com/254612/144130823-ce96cfd3-a75f-4eb5-bf77-0c520f58270c.png)

https://www.figma.com/file/gQBj9YnNgD8YW4nBwCVLZf/PostHog-App?node-id=5573%3A33304

**Comment by clarkus** [comment]
@mariusandra here's an alternative to tabs. As we discussed, it's a multi-line set of pills that summarizes the matching result count for each category. When there are 0 matching results, the category is grayed out and isn't actionable. When there is a matching result, the category can be clicked on to jump to that specific area of the list. 

<img width="324" alt="Screen Shot 2021-12-01 at 2 50 01 PM" src="https://user-images.githubusercontent.com/254612/144326828-dd2dd69f-c670-46ca-bebc-7f1469b63581.png">

https://www.figma.com/file/gQBj9YnNgD8YW4nBwCVLZf?node-id=5597:35546#129608055

**Comment by mariusandra** [comment]
Beautiful! Assuming implementing a good multi-category vertical scroll will take a bit of effort, is there a quick change we can do to highlight one pill and show one scrolling list below?

**Comment by clarkus** [comment]
> Beautiful! Assuming implementing a good multi-category vertical scroll will take a bit of effort, is there a quick change we can do to highlight one pill and show one scrolling list below?

Sure here are two ideas - I prefer the first option, but would want to balance the prominence of the pills with any inline actions shown in the list. Also updated in figma. 

<img width="826" alt="Screen Shot 2021-12-01 at 3 51 37 PM" src="https://user-images.githubusercontent.com/254612/144332711-1421d16d-3b2b-4389-86a2-770b4f1c315a.png">

**Comment by paolodamico** [comment]
Love this approach!!! As a follow-up (separate issue), can we add the taxonomy (description, tags, ...) to events where available? I imagine it would appear when hovering as we have for PostHog events and actions?

**Comment by paolodamico** [comment]
With the new pills design, and implementation, can we close this @mariusandra @clarkus ?

**Comment by mariusandra** [comment]
The idea was still to have the list scroll endlessly as well. The pills already solve a big discoverability problem, but it'd still be faster to scroll through all the lists in one big list, especially if you have < 50 items overall.

**Comment by mariusandra** [comment]
@paolodamico @clarkus do you think the current implementation with pills + tabs is good enough? 

![2021-12-14 10 57 59](https://user-images.githubusercontent.com/53387/145976028-2816c604-c839-4c74-bf03-5b85be30f2c1.gif)

We don't have the infinite scroll through all tabs. This means when you scroll to the end of "event properties" you won't automatically see a new list for "person properties", and so on. 

We could add that, but it'll require a significant refactor (read: day of work?). Do we:

a) prioritise this now
b) pause until next year
c) close this issue, consider the current implementation good enough, and revisit once someone feels like we need an upgrade (e.g. users complain)

I'd go for C personally, though see some value in A.

**Comment by clarkus** [comment]
I agree we should go for C. I think this is a substantial enough improvement to close out for now and watch usage.

**Comment by paolodamico** [comment]
Perfect, let's do it!
