### ISSUE TITLE
Allow feature flags be decided without distinct id but based on properties

### ISSUE THREAD

**Issue by weyert** [PostHog/posthog#5969]
## Is your feature request related to a problem?

Yes, I am having the problem that I want to use operation or kill switch feature flags. For example, I am developing a new feature `special_flag_for_store1and3` for my Webstore and we  have multiple e.g. Store ID 1, Store ID ...5 etc. I would like to be able to query if a feature flag is enabled for a specific store but not a specific distinct user.  

Another example, would be a kill switch feature flag were I am doing some long data fetching job for each store which I want to temporary disable when the error rate of the underlying third party API is too high. In this case I would like to be able to disable the feature flag `refresh_store_stock_info` but only for Store ID 2 and Store ID 5 but not all them. 

Before I have been thinking of using the `distinctId` for this and prefix it with `store:1` (`store:3`, `store:5` etc) but then I would need to first. I think it would be nice to optionally able to pass the user properties as part of `isFeatureEnabled` and let PostHog check the feature flag against. 

An example of usage:

```javascript
const storeIdentifiers = [
'83ac031d-088b-4b85-8d83-fee2ce5c64cf'
'b98411d3-984a-4ef3-a156-e6567b7b5355'
'0c5948fa-aa48-4957-8c15-915b45655e71'
'e36ad386-2cf0-4d5f-b319-9f71c2e06fcd'
'0e720c2c-23d0-4686-b86a-17235a03a00c'
]

for (const storeId of storeIdentifiers) {
//   const shouldRefreshStockInformation = isFeatureEnabled('refresh_store_stock_info', { store_id: 'eeabd426-8e10-4926-b5f3-b103f9258c91' } )
    const shouldRefreshStockInformation = isFeatureEnabled('refresh_store_stock_info', { store_id: storeIdentifier } )
    if (! shouldRefreshStockInformation) { 
         continue
    }
    
    const stockHoldingInformation = await getStockInformation(storeIdentifier)
    // Do more stuff
}
```

## Describe the solution you'd like
I think it would be nice to be able to determine whether flag is on or off based on given properties and not by the distinctId or it's current defined user properties.

## Describe alternatives you've considered
I have considered the following:
 - Prefix distinct ids e.g. `store:eeabd426-8e10-4926-b5f3-b103f9258c91` and use filters 
 - Creating unique feature flags for each store that would require kill switch flags * number of stores and gets easily unmaintainable.

## Additional context
@mariusandra @marcushyett-ph

**Comment by weyert** [comment]
@mariusandra as mentioned to @marcushyett-ph I am happy to attempt to develop this feature request but prefer to talk in through first :) Hence this ticket

**Comment by jamesefhawkins** [comment]
@Twixes if we can discuss the above today, Weyert has time tomorrow

**Comment by Twixes** [comment]
Hey @weyert! This is a really interesting proposal, but also a pretty significant change to feature flags, so let me first ask a couple of people with more feature flags context than me to steer our direction in the best way here. :)

**Comment by samwinslow** [comment]
I think the value of this feature is quite obvious; it makes sense to want to roll out a feature to everyone who has a given property, like everyone at a company, etc.

But in terms of implementation, wouldn't something like the below example cover 99% of what you need to do? Set `store_id` as a user property or something like that, and specify one or more `store_ids` that you want to activate the flag for.

<img width="945" alt="Screen Shot 2021-09-22 at 11 39 18 AM" src="https://user-images.githubusercontent.com/4645779/134375736-cfe84de1-c6b4-4475-98d4-3a4f6155c44a.png">

In terms of how distinct ids are used in calculation, it really only has an impact on whether a user is decided to be within the rollout group percentage or not — e.g. if you roll out to 50% of users, we use the distinct id to decide if the user is in the group with the flag or without the flag.

> Before I have been thinking of using the distinctId for this and prefix it with store:1 (store:3, store:5 etc)

This would unfortunately not work as we use a hashing function based on SHA, and the plaintext value of the distinct id does not matter. The distinct id is hashed into bytes and then converted into a float between 0 and 1.

**Comment by samwinslow** [comment]
As for the other case:

> Another example, would be a kill switch feature flag were I am doing some long data fetching job for each store which I want to temporary disable when the error rate of the underlying third party API is too high

It's less clear if we reliably support this right now — so thanks for opening this issue. It's always interesting to see various ways feature flags are used.

One thing to try: [use `$set`](https://posthog.com/docs/integrate/client/js#set) to store the latest API error rate as a person property, and then as a rollout condition, specify `your_error_rate < 100` or `api_errors_last_5_min < 10` or similar. Fairly sure the `decide` endpoint _shouldn't_ be cached but you might still run into stale data problems with this approach. Please let me know if you try this!

**Comment by marcushyett-ph** [comment]
It feels like this scenario could potentially be supported by leveraging the concept of groups (when we get them to a releasable state) @Twixes?

@weyert whats the level of urgency around this from your perspective?

**Comment by weyert** [comment]
> I think the value of this feature is quite obvious; it makes sense to want to roll out a feature to everyone who has a given property, like everyone at a company, etc.
>
> But in terms of implementation, wouldn't something like the below example cover 99% of what you need to do? Set store_id as a user property or something like that, and specify one or more store_ids that you want to activate the flag for.

Yes, I think most of it's there. I have the feeling that for these kind of flags the relation to distinctId might not be necessary. 
My main problem I am having which could totally be a misunderstanding how to use the feature flags. Is that these flags don't really worry about a specific user of the store. It's an operations/deployment flag to enable functionality easily without needing to redeploy a running web-service (e.g. think API service layer) to disable one specific outgoing http request call.

For example, how would you deal with feature flags targeting the PostHog plugin server only? For example, for some reason you want to stop the logging of plugin executions for plugin. This is not something that's typically bound to a user, what would you use as the distinctId? Would that be `posthog-plugin-server`? That's basically the problem I am having.  

I would like to ask PostHog's Feature Flags API, if I have these properties, would this flag be `true` or `false`? I imagined that the filters would check against the properties I pass while ignoring any rollout percentages.

I think the code could look like something like this (fictional didn't check code how its working real life):

```javascript
let enablePluginLogging = true
const { currentPluginId } = getExecutionContext() // get plugin id from the plugin execution context
try {
   // Needed to be able to target a feature flag against the user
  posthog.identify({
        distinctId: 'posthog-plugin-server',
        properties: {
            email: `plugin-server@ops.posthog.com` // fake email address to make it easier to find the user 'posthog-plugin-server' in the Persons list 
            // this gets reset each time we are checking whether feature flag is enabled, so the user property is set
            // and can be filtered against in the feature flag filters
            activePluginId: currentPluginId,             
        }, 
  })
 enablePluginLogging = await posthog.isFeatureEnabled('enablePluginLogging', 'posthog-plugin-server', true)
} catch (error: unknown) {
  // Ignore errors fetching feature flag, fallback to always on
}

// do stuff
if (enablePluginLogging) {
   await triggerSavePluginLogsMessage({pluginId: currentPluginId, logs: ['blah', 'blah']})
}
```

In app.posthog.com you would have two feature flags like:

*General feature flag to enable plugin-server*:

```json
{
    "id": 1234567,
    "name": "Kill switch to enable saving plugin logs",
    "key": "enablePluginServer",
    "filters": {
        "groups": [
            {
                "properties": [
                ],
                "rollout_percentage": null
            }
        ]
    },
    "deleted": false,
    "active": true,
    "created_by": {
        "id": xxx,
        "uuid": "xxx",
        "distinct_id": "xxx",
        "first_name": "Weyert de Boer",
        "email": "xxxx"
    },
    "created_at": "2021-08-19T22:10:39.389474Z",
    "is_simple_flag": false,
    "rollout_percentage": null
}
```

*Kill switch which disables plugin logging for a specific plugin posthog-plugin-geoip*

```json
{
    "id": 878,
    "name": "Kill switch to enable saving plugin logs",
    "key": "enablePluginLogging",
    "filters": {
        "groups": [
            {
                "properties": [
                    {
                        "key": "activePluginId",
                        "type": "person",
                        "value": [
                            "posthog-plugin-geoip"
                        ],
                        "operator": "exact"
                    }
                ],
                "rollout_percentage": null
            }
        ]
    },
    "deleted": false,
    "active": true,
    "created_by": {
        "id": xxx,
        "uuid": "xxx",
        "distinct_id": "xxx",
        "first_name": "Weyert de Boer",
        "email": "xxxx"
    },
    "created_at": "2021-08-19T22:10:39.389474Z",
    "is_simple_flag": false,
    "rollout_percentage": null
}
```

Does the above code example make sense? This is basically what I am trying to do at the moment and identifying person part feels wrong to me also not 100% convinced is always working.

> One thing to try: use $set to store the latest API error rate as a person property, and then as a rollout condition, specify your_error_rate < 100 or api_errors_last_5_min < 10 or similar. Fairly sure the decide endpoint shouldn't be cached but you might still run into stale data problems with this approach. Please let me know if you try this!

I would prefer not to mix monitoring metrics with the feature flags, if possible. Idea is to manually  turn on/off the flag when necessary when underlying services get high traffic (e.g. for a shop think Cyber Monday). 

Personally, in such case, I would go for a different approach, I would set an alert trigger (in the monitoring service) which could call out to PostHog to turn off the feature flag (below is the dreamed goal solution) but more simple solution to start with would be to admire the Grafana dashboard or Alertmanager alerts and based on that log into PostHog and turn off the feature flag :)

E.g.:
```yaml
apiVersion: openslo/v1alpha
kind: AlertPolicy
metadata:
  name: Error rate of XYZ server
  displayName: Automatic trigger for disabling XYZ server 
spec:
  when: breaching
  alertIf: true
  conditions: # list of alert conditions
     - description: If the error rate is too high  for given period then it should alert 
       severity: page
       condition: 
         kind: burnrate
         threshold: 0.9
         lookbackWindow: 1h
         alertAfter: 5m
  notificationTargets:
      -   description: Disable feature flag in PostHog
          target: posthog
          parameters:
            - name: featureFlag
               type: string
               value: enableLogging
            - name: featureFlagEnabled
               type: boolean
               value: false
```

> In terms of how distinct ids are used in calculation, it really only has an impact on whether a user is decided to be within the rollout group percentage or not — e.g. if you roll out to 50% of users, we use the distinct id to decide if the user is in the group with the flag or without the flag.
> 
> Before I have been thinking of using the distinctId for this and prefix it with store:1 (store:3, store:5 etc)
This would unfortunately not work as we use a hashing function based on SHA, and the plaintext value of the distinct id does not matter. The distinct id is hashed into bytes and then converted into a float between 0 and 1.

I didn't think about how distinctId would work. Does that mean if my flags always have 100% rollout percentage it's not really a concern or did I misunderstand you?

> It feels like this scenario could potentially be supported by leveraging the concept of groups (when we get them to a releasable state) @Twixes?

Yes, I have tried it this it appears to work but it feels a bit clunky  because of the need of identifying the user with the needed properties at each call. See the code example (for a 'plugin-server') listed above. Maybe I am misunderstanding things regarding identifying and feature flags.

Happy to reach out tomorrow on Slack discuss it in more detail?

**Comment by weyert** [comment]
The above example also shows why I would like to have the ability to hide some feature flags from client libraries as the flags mentioned above don't need to be exposed to `posthog-js` and similar libraries (see https://github.com/PostHog/posthog/issues/4849#issuecomment-904527827)

**Comment by mariusandra** [comment]
If I understand correctly, your use case would also be solved if we just add an API endpoint `api/feature_flag/test`, where you could POST your own `distinct_id` and `person_properties`, and get a list of matching flags as a result? This would be behind a personal API key the I guess.

The problem is this will [require some uprooting](https://github.com/PostHog/posthog/blob/cdd43b908d32f0edfce040f6a82089fb4fc550b1/posthog/models/feature_flag.py#L157), as we're running all the matching via a database query. That's so we could also match things like cohorts, etc. So it'll be quite a bit of work to adapt to properties from a param.

There legit alternative I see now is to just do the matching yourself. Your backend asks the API for all feature flags (including match groups), and runs the property matching internally. It would also discard any kind of filters you don't care about (e.g. cohorts).

Eventually we could move this logic into a plugin. If we add support for [webhook plugins](https://github.com/PostHog/plugin-server/issues/8) that can also return data. Basically opening `http://app/pluginwebook/PLUGINID/SECRETKEY` --> JS that reads the properties from a param, makes an API call to posthog to get all feature flags and matches them -> returns the matched flags. But this is still further away :).

**Comment by weyert** [comment]
> If I understand correctly, your use case would also be solved if we just add an API endpoint `api/feature_flag/test`, where you could POST your own `distinct_id` and `person_properties`, and get a list of matching flags as a result? This would be behind a personal API key the I guess.

Yeah, I can see this work. Requesting multiple matching flags is probably more efficient.

> The problem is this will [require some uprooting](https://github.com/PostHog/posthog/blob/cdd43b908d32f0edfce040f6a82089fb4fc550b1/posthog/models/feature_flag.py#L157), as we're running all the matching via a database query. That's so we could also match things like cohorts, etc. So it'll be quite a bit of work to adapt to properties from a param.

Ah yeah, I can see there would be difficulties with this. I always had the idea the filters were being interpreted outside the database system. 
 
> There legit alternative I see now is to just do the matching yourself. Your backend asks the API for all feature flags (including match groups), and runs the property matching internally. It would also discard any kind of filters you don't care about (e.g. cohorts).

Good idea, probably, I can reuse the existing feature flag polling of the node library for this.  Do you have any documentation or code snippets were I can find out the expected logic of the (group) filters? Would this be worth open-sourcing or raising a PR for Node library?
 
> Eventually we could move this logic into a plugin. If we add support for [webhook plugins](https://github.com/PostHog/plugin-server/issues/8) that can also return data. Basically opening `http://app/pluginwebook/PLUGINID/SECRETKEY` --> JS that reads the properties from a param, makes an API call to posthog to get all feature flags and matches them -> returns the matched flags. But this is still further away :).

You lost me here. I am not fully following how the webhook plugins would help with this? I would prefer it to be part of the product without the need to self-host things.

**Comment by marcushyett-ph** [comment]
cc: @macobo for your thoughts on whether this might relate to how we're thinking about groups?

**Comment by weyert** [comment]
Closing this issue as my problem has been solved by using groups + feature flags 💯
