### ISSUE TITLE
CH terraform and ansible

### ISSUE THREAD

**Issue by fuziontech** [PostHog/posthog#5978]

**Comment by joesaunderson** [comment]
+1 for this, we will hold of writing our own if this is in the pipeline

**Comment by lharress** [comment]
@fuziontech Out of curiosity, which cloud provider will this be written for?

**Comment by guidoiaquinti** [comment]
I'm closing this for the moment as our short and mid-term roadmap doesn't include a plan to support new self-hosted deployment options (click [here](https://posthog.com/docs/self-host) to see the one currently supported).
