### ISSUE TITLE
Allow filtering of arrays of properties

### ISSUE THREAD

**Issue by timgl** [PostHog/posthog#598]
**Is your feature request related to a problem? Please describe.**
My users can belong to multiple groups, and I'd like to filter on that

**Describe the solution you'd like**
You can theoretically pass through something like
`posthog.people.set({group_ids: [1, 2, 3]})`

Then in cohorts (or anywhere else as this also applies to events) I want to be able to say "group_ids (is a list and) contains 1". We somehow need to find a way to make this 'typecasting' that we're implicitly doing clear.

**Comment by wundo** [comment]
I'd love it as well, any plans to implement it?

**Comment by paolodamico** [comment]
I believe this issue is duplicated.

**Comment by alexpresthus** [comment]
@paolodamico Can't seem to find any similar open issues. Do have the ref to the duplicate?
