### ISSUE TITLE
EventsTable: Easily allow me to see first events/sort by timestamp

### ISSUE THREAD

**Issue by timgl** [PostHog/posthog#599]
**Is your feature request related to a problem? Please describe.**
I want to be able to see the first events that happened, especially if I'm filtering for something

**Describe the solution you'd like**
Either allow me to 'skip to the end' in the table, or (probably easier) allow me to sort the EventsTable in reverse.

**Describe alternatives you've considered**
Clicking "Load more events" a lot.

**Additional context**

***Thank*** you for your feature request - we love each and every one!

**Comment by solnsubuga** [comment]
@timgl I would love to work on this issue. I have managed to setup posthog for development.

**Comment by timgl** [comment]
@solnsubuga Go for it! I've assigned it to you, let me know if you need any help getting started?

**Comment by solnsubuga** [comment]
@timgl thanks for assigning this to me. I need help getting started. I am thinking about approaching this by adding an onclick on timestamp the table header (when). By toggling it, we sort the events in reverse order.

**Comment by timgl** [comment]
Yep, I think that makes sense as an approach! You can then pass a variable to the backend, and add some sorting logic to (I think) get_queryset

**Comment by timgl** [comment]
Fixed in #626
