### ISSUE TITLE
Toolbar crashes when heatmap finds "a case with 0 elements"

### ISSUE THREAD

**Issue by samwinslow** [PostHog/posthog#5993]
## Bug description

On some pages ([Company docs ](https://posthog.com/handbook/company/story)for instance), the toolbar crashes shortly after trying to open the heatmap.

JS console output looks like:

```
[err] Found a case with 0 elements
[log] Found empty selector
[err] Found a case with 0 elements
[log] Found empty selector
[err] Found a case with 0 elements
[log] Found empty selector
...
[err] Invalid selector!  > * > * > * > * > * > * > span.algolia-docsearch-suggestion--highlight:nth-child(2):nth-of-type(2)
[err] Found a case with 0 elements
[log] Found empty selector
[err] Found a case with 0 elements
[log] Found empty selector
...
[err] TypeError: Cannot set property message of  which has only a getter
    at useSelector.js:35
    at useSelector.js:106
    at Object.get (index.esm.js:1965)
    at V_ (ToolbarButton.tsx:59)
    at Ko (react-dom.production.min.js:153)
    at Ii (react-dom.production.min.js:175)
    at gl (react-dom.production.min.js:263)
    at cs (react-dom.production.min.js:246)
    at ls (react-dom.production.min.js:246)
    at Jl (react-dom.production.min.js:239)
```

Apologies for the minified output. Lines marked `...` indicate repeated instances of the same 2 log entries (may happen 30+ times). Additionally the `Invalid selector! algolia-docsearch-...` error happens 7+ times.

## Expected behavior

Toolbar does not crash, but steps over, empty/invalid selectors

## How to reproduce

1. Visit https://posthog.com/handbook/company/story while signed in to App + Website project
2. Open the heatmap
3. Witness the same failure

## Environment

- [x] PostHog Cloud
- [ ] self-hosted PostHog (ClickHouse-based), version/commit: _please provide_
- [ ] self-hosted PostHog (Postgres-based, legacy), version/commit: _please provide_

**Comment by j-ochs** [comment]
Any updates on this? 
We are experiencing this same crash on our self-hosted PostHog instance, running version `1.30.0`.

**Comment by NorhanMostafa94** [comment]
I have the same issue now
<img width="457" alt="image" src="https://user-images.githubusercontent.com/46131227/212531208-e34ebc65-2ca7-40fe-8a0f-87758c02d668.png">
