### ISSUE TITLE
Lifecycles are failing to load

### ISSUE THREAD

**Issue by marcushyett-ph** [PostHog/posthog#5995]
## Bug description

The query times out for lifecycles 

## Expected behavior
Return lifecycle data

## How to reproduce

https://app.posthog.com/insights?insight=LIFECYCLE&properties=%5B%5D&filter_test_accounts=true&events=%5B%7B%22id%22%3A%22insight%20viewed%22%2C%22name%22%3A%22insight%20viewed%22%2C%22type%22%3A%22events%22%2C%22order%22%3A0%2C%22math%22%3A%22total%22%7D%5D&actions=%5B%5D&display=ActionsLineGraph&shown_as=Lifecycle&compare=false&new_entity=%5B%5D&date_from=-90d&interval=month

## Environment

- [x] PostHog Cloud
- [ ] self-hosted PostHog (ClickHouse-based), version/commit: _please provide_
- [ ] self-hosted PostHog (Postgres-based, legacy), version/commit: _please provide_

**Comment by marcushyett-ph** [comment]
cc: @EDsCODE

**Comment by joethreepwood** [comment]
I'm experiencing this too. I can load the query, but not any of the persons information within any of the stages.

**Comment by neilkakkar** [comment]
Is this still happening @joethreepwood @marcushyett-ph ?

**Comment by marcushyett-ph** [comment]
This query works instantly for me + it's generally way better - so closing.
