### ISSUE TITLE
EventsTable: Allow filtering by name of the event.

### ISSUE THREAD

**Issue by timgl** [PostHog/posthog#600]
**Is your feature request related to a problem? Please describe.**
Sometimes I only care about pageviews when going through the events table for example. There is no way for me to filter by that at the moment.

**Describe the solution you'd like**
We've already done the backend of this (#553) so we just need to add this to the frontend somehow. I think it makes sense if this goes into property filter, despite not technically being a property. 

the alternative solution (maybe cleaner) is to store the event in the property object.

**Describe alternatives you've considered**

**Additional context**

***Thank*** you for your feature request - we love each and every one!

**Comment by Twixes** [comment]
We have this, though the UX is not super discoverable. I think we're addressing that separately though, so this is closable.
