### ISSUE TITLE
Build a "PostHog Workshop" setting or page

### ISSUE THREAD

**Issue by kpthatsme** [PostHog/posthog#6003]
## Is your feature request related to a problem?

Build a section of the app dedicated to allowing users to self-select into experiments we're running. For example, multivariate feature flags.

## Describe the solution you'd like

A section in settings or a modal linked from there that shows features that are behind feature flags with optional descriptions. Users can toggle themselves on or off into the feature. 

Maybe one additional setting in creating feature flags– an optional checkbox to allow this feature to show up in PostHog labs.

## Describe alternatives you've considered
We could utilize a notification system for this instead of a dedicated page, but they're not really mutually exclusive approaches.

**Comment by kpthatsme** [comment]
Another benefit: this would allow us to get community signal on which of our experiments we should invest more in - ship small versions of the concept and see what people gravitate towards.

**Comment by paolodamico** [comment]
A potential simpler approach is just letting users opt-in/opt-out of beta features. We have a "Beta Users" cohort to which we release all experimental features at the same time as the PostHog Team.
