### ISSUE TITLE
Group funnel data by events or properties, not only by persons

### ISSUE THREAD

**Issue by mariusandra** [PostHog/posthog#6007]
## Is your feature request related to a problem?

- I have events "open X" and "close X", and a bunch of persons
- Each person can perform multiple sequences of these events
- I would like to see how long does it usually take between the open and close events, and how often the "close" event even happens. 

## Describe the solution you'd like

This feels like a natural fit for funnels, but funnels are grouped by people. In this case one person can do multiple "open" and "close" events, and the "time to conversion" can show anything between the first and the last event of any of the user's sequences.

Thus I'd need to be able to group the events by nothing.

## Describe alternatives you've considered

- Creating a plugin that calculates a "time_spent_open" property and stores it on the "close X" event, letting me graph those. The problem is I'm not sure which open/close pairs I want to look at, as there may be many steps. Also this is running on cloud.
- Adding a random ID to each sequence of events, doing a breakdown by this ID, and manually averaging the data.

## Additional context

- Requested by a customer.
- We could probably also implement the "follow a event property value" feature, which would lock steps 2, 3, 4 to have the same "sequence ID"  or "session ID" property, if it makes things easier.

**Comment by Twixes** [comment]
I believe this would be solved by #4972.
