### ISSUE TITLE
More detailed paths node 

### ISSUE THREAD

**Issue by EDsCODE** [PostHog/posthog#6031]
## Is your feature request related to a problem?

*Please describe.*
Currently, our path visualization displays text/count inline with the visualization. We need to support a better visualization that will allow us to add more information and interaction with the information at each node.

## Describe the solution you'd like
Add a distinct element/box where we can add more functionality as needed at each node

<img width="510" alt="Screen Shot 2021-09-20 at 9 57 05 AM" src="https://user-images.githubusercontent.com/13127476/134014808-f334a821-a135-4a02-a9b5-dfeaee441095.png">

**Comment by clarkus** [comment]
Note that these boxes will also have an inline menu toggle that shows the actions available for a given path item. Updated the example at https://www.figma.com/file/gQBj9YnNgD8YW4nBwCVLZf/PostHog-App?node-id=3471%3A29287

**Comment by clarkus** [comment]
I could use some technical guidance on the sankey portion of this work. We've [decided to leave the visualization alone for now](https://github.com/PostHog/product-internal/issues/161), but there might be limitations with the current solution in terms of adding cards to each path item node. It'd be good to get some understanding of the constraints with the current sankey so I can adjust that portion of the design to ensure we're aligned. This can probably happen later, but I wanted to put it out there for consideration. I also added this topic to the current decision log.

**Comment by EDsCODE** [comment]
We are for sure limited by the current sankey. I think there's some way we can work around them though and still get the UI currently designed onto the visualization. For general guidance, I would suggest staying somewhere along the lines of what you have designed now, where each node has a card above it and some info/interactive items. Beyond that I wouldn't be so confident we could implement with the library we're using. 

i've been brainstorming with @liyiy some routes we could go with this

**Comment by clarkus** [comment]
There's a prototype that demonstrates the proposed changes to the visualization at https://www.figma.com/file/PA3RZmpBykvBW1du69Kk0A/Prototypes?node-id=138%3A2902. This is purely for internal use to help us discuss the changes.

**Comment by thmsobrmlr** [comment]
Closing as this has been implemented.
