### ISSUE TITLE
Paths dropoff clarity

### ISSUE THREAD

**Issue by EDsCODE** [PostHog/posthog#6032]
## Is your feature request related to a problem?

*Please describe.*
Our paths dropoff numbers are hard to understand. We display the number of people at each node and then the subsequent nodes but provide no reference for the number of people dropping off

## Describe the solution you'd like
Make the number of dropoffs explicit like we do with the people who don't dropoff

**Comment by clarkus** [comment]
This is taken from the recent work in figma. To improve this we would give both completed steps and dropoff the same content structure. We would differentiate dropoff from completion via clear labeling, and secondarily color. This color pattern aligns to those used in funnels. 

<img width="245" alt="Screen Shot 2021-09-20 at 11 53 10 AM" src="https://user-images.githubusercontent.com/254612/134058257-e4a2f973-b606-4cd6-a461-66e6c794c5c3.png">

https://www.figma.com/file/gQBj9YnNgD8YW4nBwCVLZf/PostHog-App?node-id=3471%3A29287
