### ISSUE TITLE
Make it easier to search the break down on Trends

### ISSUE THREAD

**Issue by jamesefhawkins** [PostHog/posthog#608]
**Is your feature request related to a problem? Please describe.**
There is a huge list in the 'break down by' filters, which is cool.

However, we can't currently search with typing, you have to wade through the dropdown, whereas we had that ability before.

**Describe the solution you'd like**

When you click break down by on the events page, it's possible to start typing and it'll filter the drop down

**Describe alternatives you've considered**

Using the mouse

**Comment by timgl** [comment]
Yep this should be fixed in #690
