### ISSUE TITLE
Posthog filters don’t work correctly

### ISSUE THREAD

**Issue by Enrique-Hermida** [PostHog/posthog#6094]
## Bug description
Posthog filters don’t work correctly on a custom properly 
![bug](https://user-images.githubusercontent.com/50220559/134587898-70882640-bd5c-4609-91a9-f05d3b9cc261.png)

## Expected behavior
when I filter a property it should show me the property I select

## How to reproduce

1. On insights generate a new query
2. select a custom properly, like 
![image](https://user-images.githubusercontent.com/50220559/134588504-3dfe2561-8323-435a-98e1-b0094cd3208f.png)
3. add a breakdown like Pathname, Posthog gonna show another information are not related to the query 
![filter](https://user-images.githubusercontent.com/50220559/134589006-0b98efab-e071-471d-9465-1792b1c054ed.png)

## Environment

- [ ] PostHog Cloud
- [ ] self-hosted PostHog (ClickHouse-based), version/commit: _please provide_
- [ ] self-hosted PostHog (Postgres-based, legacy), version/commit: _please provide_

**Comment by macobo** [comment]
Hi @Enrique-Hermida - is this on cloud or self-hosted, what version and which database are you using?

**Comment by Enrique-Hermida** [comment]
Self-hosted (AWS)
DataBase: Postgresql

**Comment by paolodamico** [comment]
Postgres is no longer supported with PostHog and it looks this is not happening in Clickhouse.
