### ISSUE TITLE
Can build *but not run* the clickhouse arm64 docker image on an M1 mac

### ISSUE THREAD

**Issue by pauldambra** [PostHog/posthog#6103]
## Bug description

I've followed the instructions here: https://github.com/PostHog/posthog/pull/5215#issuecomment-917242765

First running `yarn arm64:build:clickhouse` (after assigning more RAM and storage to Docker) and then `yarn arm64:ch-dev:start`

and I get:

`runError response from daemon: pull access denied for clickhouse-dev-arm64, repository does not exist or may require 'docker login': denied: requested access to the resource is denied`

If I run `docker run clickhouse-dev-arm64:latest` then I see the container start and immediately exit with the output `Configuration file '/etc/clickhouse-server/config.xml' isn't readable by user with id '101'`

If I run for e.g. `docker run --user 1000:1000 clickhouse-dev-arm64:latest` I get the same error but for user 1000

**Comment by pauldambra** [comment]
error comes from [this line](https://github.com/PostHog/posthog/blob/master/docker/clickhouse-builder/assets/entrypoint.sh#L38)

```
if ! $gosu test -f "$CLICKHOUSE_CONFIG" -a -r "$CLICKHOUSE_CONFIG"; then
    echo "Configuration file '$CLICKHOUSE_CONFIG' isn't readable by user with id '$USER'"
    exit 1
fi
```

**Comment by hazzadous** [comment]
Yeah looks like it needs the config.xml to be mounted as docker-compose does.

You can remove docker-compose pull from the yarn command and it should work, as a workaround.

**Comment by mariusandra** [comment]
`docker run` on its own won't work, as we also add some volumes/files inside the `docker-compose.ch.arm64.yml` file to clickhouse. 

If you run the other `arm64:services:*` scripts, does anything happen? I personally don't use the `ch-dev:start` command, so not sure what's the case here.

**Comment by pauldambra** [comment]
Yep, removing the `pull` looks right @hazzadous  

Just running running as `concurrently -n DOCKER,WEBPACK,TYPEGEN -c red,blue,green \"docker-compose -f ee/docker-compose.ch.arm64.yml && CH_WEB_SCRIPT=./ee/bin/docker-ch-dev-backend docker-compose -f ee/docker-compose.ch.arm64.yml up\" \"yarn run start-http --host 0.0.0.0\" \"yarn run typegen:watch\""` looks like it is starting
<img width="343" alt="Screenshot 2021-09-24 at 16 56 45" src="https://user-images.githubusercontent.com/984817/134705299-25298f79-e810-4855-b5ca-f6ccb715ddc6.png">
