### ISSUE TITLE
Anonymous user does not get merged after person properties have been updated

### ISSUE THREAD

**Issue by macobo** [PostHog/posthog#6116]
## Bug description

A user reported that after September 20th, their anonymous users don't get merged with new created users.

## Expected behavior

Merging occurs

## How to reproduce

Locally, involved:
1. Open local copy of posthog.com in an incognito window
2. See an engage request being made
3. Note down result of `posthog.get_distinct_id()` result (XXX)
4. Incognito, log in to posthog on localhost
4. Open http://localhost:8000/person/XXX in non-incognito
6. See that future events don't show up under there

## Environment

- [x] PostHog Cloud
- [ ] self-hosted PostHog (ClickHouse-based), version/commit: _please provide_
- [ ] self-hosted PostHog (Postgres-based, legacy), version/commit: _please provide_

## Additional context

This seems to be caused by https://github.com/PostHog/plugin-server/pull/576. What seems to be occurring is:
1. We set a user property on an anonymous user https://github.com/PostHog/posthog.com/blob/87964af5cb1bcb7908a90bbfda35280c63cad2e6/src/components/DarkModeToggle/index.js#L18
1. posthog-js does an /engage request to set person properties
2. posthog capture sees a request without event, sets event to $identify
3. plugin-server updates properties and sets user as identified (but does no merge since no anonymous id)
4. In the future we don't do any merges since user is marked as identified

cc @yakkomajuri

**Comment by yakkomajuri** [comment]
The solution here should be to not infer that calls to `/engage` are identify events, but this could have consequences.

**Comment by macobo** [comment]
I think that wouldn't work as we'd like - other libraries (e.g. [posthog-js-lite](https://github.com/PostHog/posthog-js-lite/blob/master/src/index.ts#L63-L79)) allow you to call identify to update user properties.

I propose we instead only mark users identified if there's an anonymous id attached and it's different from the distinctid?

Will open a PR tomorrow
