### ISSUE TITLE
Unstable insight logics

### ISSUE THREAD

**Issue by mariusandra** [PostHog/posthog#6118]
## Bug description

There are many complicated loops in the relationships between logics such as: `insightLogic` (no props/key) and the four logics of `funnelLogic`,  `retentionTableLogic`, `pathsLogic`, `trendsLogic` (with or without props/key, depending where they're called from). The complication extends into `DashboardItem.tsx`, and the code to display the various insights, either on the scene or as individual items.

## Issues

- [x] There's a lot of duplicated code between the 4 insight logics regarding fetching results, setting cached results, etc. There are probably unexpected inconsistencies.
- [ ] `DashboardItem.tsx` has some [very funny code](https://github.com/PostHog/posthog/blob/208517983ffb00171887d49db90eb887b2070061/frontend/src/scenes/dashboard/DashboardItem.tsx#L231-L237), which loads a) the insight scene logic (though we're in a dashboard item), b) a specific logic for the insight, c) the `funnelLogic` regardless if the item is a funnel or not
- [x] The timeouts are tracked inside a global insightLogic, resulting in issues like this: https://github.com/PostHog/posthog/issues/6105
- [x] There's a unused `setMaybeShowTimeoutMessage` in insight logic
- [x] When does a insight come from a `dashboarditem.results` json, when does it have to load data on its own? The API for that with the 4 logics is rather ambiguous. 
- [x] How do saved reports fit into this? How do they pass data? An insight is now keyed by `dashboardItemId`, is there another relevant prop on the way?
- [ ] There are different ways in which different insights store various filters, e.g. https://github.com/PostHog/posthog/issues/6102
- [ ] Very few tests for any of this.

All of the above is causing a buggy experience with insights, dashboards, etc, especially as any new changes seem to break old code.

**Comment by paolodamico** [comment]
Related to https://github.com/PostHog/posthog/issues/4264 but this is definitely more detailed

**Comment by clarkus** [comment]
I would also like to consider issues like https://github.com/PostHog/posthog/issues/6101 as part of this. It makes sense that a user would want to modify some aspects of an insight without actually changing the insight definition. Do you think that is part of this scope, or should this be something we track separately?

**Comment by mariusandra** [comment]
@clarkus I'd separate the two. With this issue I had in mind purely technical refactoring that doesn't change anything about how the product works, other than increased stability.

**Comment by paolodamico** [comment]
@mariusandra @Twixes I believe we've made a ton of progress on this.
1. Is this still an issue, should we keep around?
2. If so, should we prioritize it for next sprint? Will addressing this bring immediate user value?

**Comment by mariusandra** [comment]
There's just this point remaining: https://github.com/PostHog/posthog/issues/7376

For the rest, the issue can be closed.
