### ISSUE TITLE
Heatmaps don't work on websites with dynamic attributes

### ISSUE THREAD

**Issue by rcmarron** [PostHog/posthog#6135]
## Bug description

Today, heatmaps work by grouping elements by their entire element chains: https://github.com/PostHog/posthog/blob/master/ee/clickhouse/sql/element.py#L12. This element chain includes element attributes along the path. 

Some web frameworks (including Angular), generate attributes for elements to help with styling (https://angular.io/api/core/ViewEncapsulation). These attributes can change between builds. As a result, there isn't consistency on element paths between builds, and the heatmap feature is essentially broken.

One of our large customers hits this issue today, and it's likely that most Angular customers hit it too.

## Expected behavior

I'd expect either we:
1. Don't use the entire element path when grouping elements for the heatmap (I'm not sure what this would look like)
2. Warn users that there isn't consistency in their element path, so the feature doesn't work.

## Environment

- [ ] PostHog Cloud
- [ ] self-hosted PostHog (ClickHouse-based), version/commit: _please provide_
- [ ] self-hosted PostHog (Postgres-based, legacy), version/commit: _please provide_

**Comment by rcmarron** [comment]
Filtering out all `_ngcontent*` attributes from autocapture events in posthog-js could be a quick way to get this working for angular customers. 

@mariusandra @yakkomajuri any qualms with an approach like this? (My posthog-js dev env is still giving me issues, otherwise, I'd just make the PR)

**Comment by mariusandra** [comment]
I'm all for removing angular's noise. Seeing https://github.com/PostHog/posthog-js/pull/298 merged, can this be closed?

However for added context, the toolbar also does [its own merging/grouping of elements](https://github.com/PostHog/posthog/blob/cd94d2d46437939ea37e09504896a8000e66b57f/frontend/src/toolbar/elements/heatmapLogic.ts#L93-L164). Even if the backend returns multiple selectors that match the same element, this should clean things up somewhat. The caveat is of course if the click was registered with `_ngcontent-random=4` and now all elements on the page have this prop `=5`. To get around this we could also strip out the `_ng*` attributes from old events in `heatmapLogic`.

The other problem is of course if each click has a unique selector, the the query will only return 100 clicks...

**Comment by rcmarron** [comment]
Yup, closing this issue now.

> The other problem is of course if each click has a unique selector, the the query will only return 100 clicks...

Yeah, I think this is the issue that the one customer is hitting. Basically, each build they made created random attributes, so all of the element chains would be brand new. As a result, there are tons of element chains, and the `LIMIT 100` makes it so the front-end logic never gets a chance to fix it.
