### ISSUE TITLE
Remove unused feature flags

### ISSUE THREAD

**Issue by mariusandra** [PostHog/posthog#6140]
## Is your feature request related to a problem?

Locally when developing and running `python manage.py sync_feature_flags` a lot of features get enabled, many of which we have abandoned a while ago.

## Describe the solution you'd like

- Go through each flag and figure out if we still need it. And if not, delete the relevant code. 
- `test-environment-3149` is one such flag, but there are others at first glance.

## Describe alternatives you've considered

Keep adding features until we run out of disk space.

**Comment by mariusandra** [comment]
`test-environment-3149` is now deleted.

**Comment by paolodamico** [comment]
Did a pass today for #6401 and seems the remaining feature flags are needed. Posting an update here,

- `3638-trailing-wau-mau` & `5898-split-persons` are waiting on some UX improvements.
- `ingestion-grid-exp-3` need input from @kpthatsme 
- I'm getting rid of `project-home-exp-5` & releasing `112-ingestion-help-button`
- After this release I believe we can remove the feature flags for: ~`4267-event-property-taxonomy` (@liyiy can you confirm),~ `4871-plugin-metrics` & `5720-plugins-ui-jobs` (@yakkomajuri  can you confirm).
- What do we want to do with horizontal funnels @alexkim205 @clarkus? `5730-funnel-horizontal-ui`
- In active use, everything else: cloud flags (Papercups, NPS, announcements), `3408-saved-insights`, `5440-multivariate-support`, `hackathon-dive-dashboards`, `new-paths-ui`, `new-paths-ui-edge-weights`, `posthog-toolbar-feature-flags`, `6050-remove-sessions`, `5733-funnel-vertical-breakdown`, `6063-rename-filters`, `correlation-analysis`, `sigma-analysis`, `4141-event-columns`

**Comment by pauldambra** [comment]
`4141-event-columns` is still used. It's a relatively safe feature IMHO but still wrapped in the feature flag.

**Comment by alexkim205** [comment]
`5730-funnel-horizontal-ui` is a FF that was blocked on new work around insight query building, but I feel like with the introduction of vertical breakdowns calling for more horizontal space, this feature became more relevant. I think there's still some validation to do here. Can we roll it out to a few users to get some feedback on this? Definitely happy to roll it back if there's user pushback

**Comment by yakkomajuri** [comment]
Yeah we can get rid of `4871-plugin-metrics` and `5720-plugins-ui-jobs`

**Comment by paolodamico** [comment]
I'll let @mariusandra pick the `5730-funnel-horizontal-ui` flag as he'll be working on saved insights next sprint. Personally I'm an advocate of keeping the current vertical layout, but your approach of showing to some users and getting feedback seems reasonable. We can also do a proper A/B test where we track discoveries.

**Comment by Twixes** [comment]
Looks like `new-paths-ui` is now rolled out to everyone (Cloud + self-hosted) – candidate for removal.

**Comment by alexkim205** [comment]
`new-sessions-player` is also out to 100% of PostHog users so also be a candidate for removal

**Comment by mariusandra** [comment]
I think we're all living the `turbo-mode` by now.

**Comment by paolodamico** [comment]
Alright, I've removed Paths, new session player & correlation analysis. @mariusandra I think you can remove `turbo-mode` if it's ready. Here are the FFs we should decide what to do with:
1. Horizontal funnels (`5730-funnel-horizontal-ui`) - @alexkim205 @clarkus what are we thinking? standardized horizontal layout in funnels or more convenient but not standardized vertical view? should we support both and let the user choose? change it based on screen width?
2. Dive dashboards (`hackathon-dive-dashboards`) - @tiina303 what's the status of this? do we want to move forward? As it is today, the UX seems to be causing some confusion to users, so we might need to adjust first.
3. Funnel vertical breakdown (`5733-funnel-vertical-breakdown`) - I believe this was a solid improvement but it had some bug, @alexkim205 @mariusandra what do we want to do with that one?
4. Trailing WAU/MAU - it's released for everyone but we wanted to adjust the UI/UX before removing it. @clarkus any thoughts? One option was just to have a link in the docs that generates the graph automatically.
5. Ingestion grid (`ingestion-grid-exp-3`) - I believe this was a successful experiment and while we may want to improve it, we could release it already. @kpthatsme ?

**Comment by tiina303** [comment]
> Dive dashboards (`hackathon-dive-dashboards`) - @tiina303 what's the status of this? do we want to move forward? As it is today, the UX seems to be causing some confusion to users, so we might need to adjust first. 

Please see this issue: https://github.com/PostHog/posthog/issues/5946 I was hoping core experience team could work on this as none of us who were on the team during the hackathon have expertise in this area.

**Comment by mariusandra** [comment]
We should probably remove unused or released feature flags... 🤔

**Comment by neilkakkar** [comment]
indeed. An automated way is coming next month most probably! :)
