### ISSUE TITLE
Benchmarking suite for query performance

### ISSUE THREAD

**Issue by macobo** [PostHog/posthog#6144]
## Is your feature request related to a problem?

Currently knowledge on query optimization in clickhouse is pretty centralized. This means that when rewriting queries a lot of manual work needs to be made by a select few to ensure we don't lose performance in our wide product.

## Describe the solution you'd like

Have a benchmarking suite.

## Describe alternatives you've considered

Winging it

## Additional context

Some requirements:
- Run benchmark against master + labeled branches, indicate when performance changes
- Use database time over runtime for more accurate measurements
- Use dedicated server (over CI) for running the clickhouse node
- Have a good and representative dataset that we can filter in various ways as we improve performance. Generated datasets require a lot of maintanence and will invalidate previous measurements.

Initial proposal:
- Use [Airspeed velocity](https://asv.readthedocs.io/en/stable/using.html) library to do the benchmarks
- Set up a clickhouse installation with a copy of some of our teams data (or anonymized data) to run against
- Set up tests. Use fixed time-frames in benchmarks when possible.
- Integrate it with PRs, e.g. as with https://github.com/sympy/sympy/pull/21757/files, also run against master. Set concurrency=1
- Publish results somewhere

**Comment by hazzadous** [comment]
This would be good for spotting if something degrades performance. I would also love to be able to play easily with seeing what performance improvements we can get with:

 1. creating JOIN tables e.g. for events and persons
 2. restructuring e.g. how properties are stored. (for instance storing as key, value array with appropriate indexes as described by this [instana blog post](https://www.instana.com/blog/improve-query-performance-with-clickhouse-data-skipping-index/))

Do you have any advise on how best to do this type of exploration at the moment @macobo

**Comment by macobo** [comment]
Played around with this. 

Blocked by our old clickhouse version (cc @fuziontech / @tiina303). 21.7 made it possible for clickhouse-copier to work properly with materialized columns, currently I'm stuck when trying to copy data due to it. 

UPDATE: Found a workaround

> Do you have any advise on how best to do this type of exploration at the moment @macobo

Regarding exploring data layouts we don't have a story currently due to not having a safe environment to test these in. I'd use the benchmarking clickhouse node for this once it's ready - we can copy data to temporary tables there and experiment as needed on it.
