### ISSUE TITLE
Infinite loading in sessions page

### ISSUE THREAD

**Issue by macobo** [PostHog/posthog#6150]
## Bug description

Slack thread: https://posthogusers.slack.com/archives/C01PPBY3G6Q/p1632837105060000

> Here is a [video](https://www.loom.com/share/d1e19a20fb40493fa2ee5b4d78779101) of a bug in the sessions (with recordings) page that I can reproduce every time.
> At the end of the video, after a few more minutes, I get the error as in the screenshot below, the CPU usage goes to 100%, and finally the instance becomes unreachable.

## Expected behavior

No crash

## How to reproduce

See video above

## Environment

- [ ] PostHog Cloud
- [x] self-hosted PostHog (ClickHouse-based), version/commit: 1.28.0
- [ ] self-hosted PostHog (Postgres-based, legacy), version/commit: _please provide_

## Additional context

Suspect is the sessions query loading infinitely, would be fixed by #4884

**Comment by mariusandra** [comment]
I guess as we're removing this entire page, this is no longer relevant?
