### ISSUE TITLE
Exporting large number of users causes a crash

### ISSUE THREAD

**Issue by jamesefhawkins** [PostHog/posthog#6151]
## Bug description

* I wanted to get a list of all users who have an email address in PostHog (so that I could check which of these are at large companies)
* So I went to the persons page and ran this filter:

<img width="1348" alt="Screenshot 2021-09-28 at 16 52 27" src="https://user-images.githubusercontent.com/47497682/135122010-09a66665-2164-48ff-8960-3c2661df6911.png">

* I think clicked 'export' to download the CSV

## Expected behavior

* It to produce a CSV _or_ it to limit the CSV size and let me download in chunks.

## Environment

- [x] PostHog Cloud
- [ ] self-hosted PostHog (ClickHouse-based), version/commit: _please provide_
- [ ] self-hosted PostHog (Postgres-based, legacy), version/commit: _please provide_

**Comment by macobo** [comment]
@jamesefhawkins so what happened when you clicked this? Did it show a 500 or...?

**Comment by jamesefhawkins** [comment]
> what happened

A 502:

<img width="1153" alt="Screenshot 2021-10-02 at 00 40 44" src="https://user-images.githubusercontent.com/47497682/135696236-ed7237f0-a59e-4e51-b0cf-19f36f1ca5a3.png">

**Comment by pauldambra** [comment]
This has been fixed either in recent CSV work or before that

Checked by visiting `persons` searching for `@gmail.com` and clicking export
