### ISSUE TITLE
As a user, I want to add custom properties to persons based on other properties

### ISSUE THREAD

**Issue by romj** [PostHog/posthog#6164]
## Is your feature request related to a problem?

A typical use case, is that I want my persons to have a dynamic property "attribution channel". Here's an overly simple case (real life is more messy):
- If the user has a property "invited_by_another_user", then his channel will be "Team Invite"
- If the UTMs of the page on which the user registered has some adwords properties, then his channel will be "Paid"
- If not, then the user is "Organic"

## Describe the solution you'd like

Like I can create an "Action" that is a group of events, or "cohorts" that are a group of users who meet certain criteria, I would like to be able to create, in the UI, a custom property, that is a set of AND / OR conditions on properties.

## Describe alternatives you've considered

- Write a plugin that does it. Not cool, because only coders can do it, and it takes time.
- Use cohorts instead, but it's clunky and cohorts are missing some features to make it a worthwhile workaround
- Enrich user properties with data from my warehouse, but it wouldn't be live

## Additional context

We are migrating from Heap and they had this feature, and it turns out to be the main cause for internal resistance to make the switch in my company.
Feel free to reach out (jean@stonly.com) for details.

**Comment by macobo** [comment]
Some additional context: the feature is called 'Conditional Properties', docs: https://help.heap.io/define-analyze/data-management/creating-and-managing-properties/#conditional-properties

cc @clarkus @paolodamico :thinking:

**Comment by mariusandra** [comment]
I couldn't find it from the docs, but are these calculated dynamically in sql when querying, or at event ingestion time?
