### ISSUE TITLE
In the Trends chart, I want to see my event counts as moving averages

### ISSUE THREAD

**Issue by romj** [PostHog/posthog#6165]
## Is your feature request related to a problem?

The marketing guy of my team wants to see how his daily acquisition volumes are moving. These are noisy, so he needs to average them out over the last, say, 7 days to have a better sense of the trend.

## Describe the solution you'd like

In the customisation options on top of the chart, I would like to have an option to average out the line, and choose how many periods (last 2, 7, n days if my chart is daily, last n weeks if weekly).

A nice to have would be to have the choice to display both daily value and moving average, to be able to compare how the daily values are doing vs average.

![Insights_•_PostHog](https://user-images.githubusercontent.com/44766458/135228927-97395fe2-a017-4a26-aca7-a20eecfbc4d0.png)

## Describe alternatives you've considered

- We _could_ average out daily by changing the setting to weekly. But if on a Friday, you want to see how your acquisition is doing, then the current week's value has no meaning: you need to stay daily and see the average
- I tried to use formulas, but couldn't find a workaround

## Additional context

This is a Heap feature, that is making it a bit harder for my team to make the switch to posthog

Feel free to contact me at jean@stonly.com

**Comment by paolodamico** [comment]
CC @marcushyett-ph

**Comment by marcushyett-ph** [comment]
@romj nice to meet you earlier - I have this on my personal roadmap as a feature I'd like to build - but it'd be great to understand how urgent this is for your team - e.g. is it preventing you from getting the answers you really need from PostHog? Or is it having a smaller effect?

**Comment by romj** [comment]
This is not preventing us from using posthog, but making our life harder
