### ISSUE TITLE
New insight type: big bold number

### ISSUE THREAD

**Issue by timgl** [PostHog/posthog#6172]
## Is your feature request related to a problem?

I want to see a big number on my dashboard for one of my key metrics (like total sign ups for example)

## Describe the solution you'd like

Right now the only way to do this is to have a pie chart. This is okay, but it'd be nice to just have the number without the pie chart.
![image](https://user-images.githubusercontent.com/1727427/135251081-9b553585-c616-4fdd-9c8e-b46bf7d7bd18.png)

For extra credit, it'd be cool if this automatically had compare=previous set, so we could have a "+25.4% compared to previous period".

## Describe alternatives you've considered

Use pie chart.

**Comment by clarkus** [comment]
Quick idea for how we might represent this KPI visualization type - targeted towards simplicity we'll show a metric name, a prominent value, and optionally a rate of change with the comparison time included. 

<img width="465" alt="Screen Shot 2021-09-29 at 7 48 01 AM" src="https://user-images.githubusercontent.com/254612/135292853-7026c2d3-6419-4396-8a13-4235dead9d4a.png">

**Comment by Yahyakiani** [comment]
@timgl  If this issue is available. I would like to contribute to this issue . 
 Could you please point me to where I should look to work on this issue ?
Thanks

**Comment by lantzleiweke** [comment]
Would love to see something like this - is there a plan to move this into an active epic?

**Comment by Twixes** [comment]
Hey all! This is now available on PostHog Cloud as chart type "Number":

<img width="144" alt="Screen Shot 2022-08-10 at 11 21 14" src="https://user-images.githubusercontent.com/4550621/183865386-2670eb6a-8e65-4f69-bf37-aea352d1986f.png">

Coming to self-hosted in 1.39.

**Comment by lantzleiweke** [comment]
HELL yeah - nice work ya'll, tanks for this!

**Comment by lantzleiweke** [comment]
Hey @Twixes - any plan to scale this to show the output of more than one graph series?

For instance: the number we really care about is not the sum of a singular graph series `a`, it's the output of the formula on the insight of (a/b) over the week.
