### ISSUE TITLE
UX around saving insights to dashboard feels clunky

### ISSUE THREAD

**Issue by samwinslow** [PostHog/posthog#6176]
- It would be nice for the dashboard panel name to auto-populate with the insight name.
  - The modal hogs focus, meaning I have to close it in order to copy-paste
  - _Really_ nice to have: Auto-suggest an insight name if one isn't specified manually, e.g. "Pageviews (Browser = Chrome)". I believe we already have a few utility functions to turn an insight and its filters into a human readable string, such as with the old tooltips.

![Screen Cast 2021-09-28 at 4 50 17 PM](https://user-images.githubusercontent.com/4645779/135270964-6c6481dc-eaf6-42d7-91b7-2a36b7ca13e4.gif)

- After "saving & adding to dashboard", that button is still there, making it ambiguous as to whether it has actually saved, or if pressing it again will cause a duplicate dashboard item to be created

![Screen Cast 2021-09-28 at 4 51 11 PM](https://user-images.githubusercontent.com/4645779/135271196-5c9ae842-e9a2-4761-bd15-98aba017958a.gif)

Misc

- Save button says something like "Saved insight updated - click here to view it" — clicking then takes me to my saved insights, when what I'd actually like to see is its position on my dashboard.
  - Perhaps once you save an insight to a dashboard, the "save and add to dashboard" button should become "view on dashboard", and the "save" button should become "update"

Depending on interest from the Core Experience team I can pick these up... should be simple changes and high UX value

**Comment by samwinslow** [comment]
@alexkim205 this is pretty related to the demo you showed today! Let me know if you'd like to chat synchronously about this

**Comment by paolodamico** [comment]
This is addressed with the latest implementation of saved insights.
