### ISSUE TITLE
Showing people on sessions

### ISSUE THREAD

**Issue by EDsCODE** [PostHog/posthog#618]
**Is your feature request related to a problem? Please describe.**
Sessions should have more viewing options

**Describe the solution you'd like**
We should be able to see sessions on a barchart and be able to click into datapoints to see who the sessions are referring to

**Additional context**
#334 isn't merged yet

***Thank*** you for your feature request - we love each and every one!

**Comment by Twixes** [comment]
I believe we have this now.
