### ISSUE TITLE
Can not sort trends "table" insight

### ISSUE THREAD

**Issue by mariusandra** [PostHog/posthog#6180]
## Bug description

This doesn't work when the insight type is "trends" -> "table".

![2021-09-29 15 54 32](https://user-images.githubusercontent.com/53387/135294398-4d4f7c05-77e9-4f8b-936d-d21f00783f3a.gif)

## Expected behavior

It should sort

## How to reproduce

1. Open insights/trends
2. Break down by something
3. Look at the table graph
4. Try to sort
5. See that it doesn't work

## Environment

- [ ] PostHog Cloud
- [ ] self-hosted PostHog (ClickHouse-based), version/commit: _please provide_
- [ ] self-hosted PostHog (Postgres-based, legacy), version/commit: _please provide_

## Additional context

This works on the table under a normal ("linear" chart) trends insight.

**Comment by macobo** [comment]
Note: There's pagination involved here as well, sorting should probably work with that! :)

**Comment by mariusandra** [comment]
I'm actually not sure we should worry about pagination. The "line chart -> linear" view has a table that can be sorted, and a similar issue with pagination. 

The main point here is that while the "line chart -> linear" view automatically sorts all values in descending order, the "table" view shows all breakdown values randomly. Not sorted by count and not sorted alphabetically. The original request was to just see a descending list, which would also work without pagination. For an "ascending" sort, we could just add a "showing only the highest X breakdown values" warning and a suggestion to click "load more" to get more.

**Comment by pauldambra** [comment]
OK, I can reproduce this by switching to and from Clickhouse as a backend.

The table relies on a count property, but when the backend is Clickhouse that is always 0 and the result is actually in `aggregated_value`

# with clickhouse as the backend
![running with clickhouse](https://user-images.githubusercontent.com/984817/135875727-62ae967c-d97c-4489-802b-6c67d461bd01.png)

# with postgres as the backend
![running with postgres](https://user-images.githubusercontent.com/984817/135875965-e6ef70b4-941e-4733-8bf3-968b0ce8feb3.png)
