### ISSUE TITLE
Group Analytics Questions

### ISSUE THREAD

**Issue by marcushyett-ph** [PostHog/posthog#6189]
We're trying to understand how organizations use group analytics, this are the questions we aim to answer to understand how group analytics are used / required in order to ensure we build an effective solution.

**Selection Criteria**
* Are you a B2B company, who are your clients, how many people from each organization use the product?
* How do you measure success?
* What do you want to measure about your groups - that you cannot measure (easily) today?

**Needs for Group Analytics**
* What sort of groups do you have using your product (e.g. organizations, companies, users)?
* Can users be in multiple groups?
* Can users switch between groups? (If so, how are they switched between groups?)
* How are events aggregated to groups when a user has switched between groups (e.g. purchase from one user, which group is the event assigned to)?
* Do your internal staff login as organizations to help (how do you consider these events?)
* Do you have relationships between certain groups (what are the consequences of these relationships?)
* How would you want to use groups in your PostHog workflow?

**Specific to feature flags**
* Would you want to use feature flags together with groups?
* What happens if someone is in multiple groups?
* How do you launch features, e.g. consistency between members of the same group? What happens when there is a conflict in group membership?

**Comment by macobo** [comment]
![image](https://user-images.githubusercontent.com/148820/135648135-ee10c3df-a34d-40bc-ab4a-2ba66a12d050.png)
![image](https://user-images.githubusercontent.com/148820/135648182-5fabe17b-744f-4953-b739-8440db44dae5.png)

**Comment by joethreepwood** [comment]
@marcushyett-ph I just had a call with a company, which is experiencing this issue very acutely and _seem_ to have a hack set up to track group/org analytics as well as user analytics at the moment. The CEO is deeply technical and very willing to share data - including sharing his screen during the call to show this. 

He's super interested in contributing to our work around this (he had previously build the self-hosted to cloud migration script). I advised someone looking at this issue may want to reach out to him and discuss in detail. 

[Here's a link to the call recording.](https://drive.google.com/drive/folders/18beq9i4U4_niZISYf0KKCr0pysfNkmP9?usp=sharing). This is a public repo, so let me know if you'd like me to intro?
