### ISSUE TITLE
Simple export for insights data tables

### ISSUE THREAD

**Issue by paolodamico** [PostHog/posthog#6224]
## Is your feature request related to a problem?

Data tables already contain a ton of useful information on my insights. Yet I might want to take this outside for some reporting.

## Describe the solution you'd like

I'd like to be able to do CSV exports from the data tables in insights.

## Describe alternatives you've considered

Other types of exports? Manually copying the numbers?

## Additional context

Requested by a user particularly interested in exporting funnel data with breakdowns.

**Comment by pauldambra** [comment]
You have been able to do this for a while
