### ISSUE TITLE
Persons modal showing data inconsistent with expected count

### ISSUE THREAD

**Issue by samwinslow** [PostHog/posthog#6234]
## Bug description

Please see [this insight](https://app.posthog.com/insights?insight=TRENDS&events=%5B%7B%22id%22%3A%22%24pageview%22%2C%22math%22%3A%22total%22%2C%22name%22%3A%22%24pageview%22%2C%22type%22%3A%22events%22%2C%22order%22%3A0%2C%22properties%22%3A%5B%5D%2C%22custom_name%22%3Anull%2C%22math_property%22%3Anull%7D%5D&display=ActionsLineGraph&interval=day&breakdown=%24feature%2Fkunal-test-mv&date_from=-7d&properties=%5B%7B%22key%22%3A%22%24current_url%22%2C%22type%22%3A%22event%22%2C%22value%22%3A%22%5Ehttps%3A%2F%2Fposthog.com%22%2C%22operator%22%3A%22regex%22%7D%2C%7B%22key%22%3A%22%24active_feature_flags%22%2C%22type%22%3A%22event%22%2C%22value%22%3A%22kunal-test-mv%22%2C%22operator%22%3A%22icontains%22%7D%5D&breakdown_type=event&date_to#fromItem=423230&fromItemName=Web%20Pageviews%20breakdown%20by%20mv&fromDashboard=10317) — pageviews, with a filter applied, broken down by multivariate flag value.

Using Fri Oct 1 as an example, I would expect to see 117 users in the persons modal, but there are 200 rows in the modal (exported as CSV).

Using another example where the total number should be _above_ 200, the persons modal returns exactly 200 rows. It seems truncated.

## Expected behavior

Less than 200 rows when the result count is less than 200; no arbitrary truncation when the result count is more than 200.

## How to reproduce

See above description

## Environment

- [ ] PostHog Cloud
- [ ] self-hosted PostHog (ClickHouse-based), version/commit: _please provide_
- [ ] self-hosted PostHog (Postgres-based, legacy), version/commit: _please provide_

**Comment by samwinslow** [comment]
@marcushyett-ph Here's more detail regarding a data trust issue you had asked about.

Related to: https://github.com/PostHog/product-internal/pull/175

**Comment by EDsCODE** [comment]
> Using another example where the total number should be above 200, the persons modal returns exactly 200 rows. It seems truncated.

Working on this

I'm not seeing the rest of the problem described. The CSV number of people matches

**Comment by Twixes** [comment]
This should be alleviated now.
