### ISSUE TITLE
Clean up UX for DAU/WAU/MAU

### ISSUE THREAD

**Issue by paolodamico** [PostHog/posthog#6254]
## Is your feature request related to a problem?

Several months ago we introduced the DAU/WAU/MAU graph support. A common use case is wanting to understand the **ratio** of DAUs vs. WAUs or MAUs as this is a good signal of engagement. This feature is functionally ready, but I think we can improve the UX a bit here to a) make it clear what's going on, and b) make it particularly discoverable. 

**Current flow:**
<img width="1348" alt="" src="https://user-images.githubusercontent.com/5864173/136031280-4b7295d4-ff40-4da5-ac5c-a7e761d3ffb4.png">

## Describe the solution you'd like

@clarkus I'm wondering if there's some quick win here we can do to improve this experience. FYI this [blog post](https://andrewchen.com/dau-mau-is-an-important-metric-but-heres-where-it-fails/) provides some context on how this metric is used. I almost wonder if we should have an easier way to access this metric directly.

## Describe alternatives you've considered

Keeping as it is. Writing docs to cover this use case (interested users will probably Google it).

## Additional context

Lower priority based on our current focus, but there might be some low hanging fruit. Though requested by a focus customer, we can just explain them how to use it ad-hoc.

**Comment by clarkus** [comment]
This workflow aligns with those I found in other competing products, but I agree it is a bit clunky. I think most of the problem relates to that formula component - it results in an additional graph series, but it's composed in a completely different area from the rest of the graph series. I think what would be most approachable is the ability to define a formula graph series directly in the query builder. It just feels out of place adjacent to filters and breakdowns. It's fundamentally different in how it affects the visualization. 

I am going to spend a little time thinking about how this could be improved. I'll post back here with any quick wins that come to mind.

**Comment by paolodamico** [comment]
Maybe we can create a user guide explaining this and then with a simple "one-button click" to generate that graph in your own project (perhaps the only difficulty is with self-hosted instances). Thoughts?

**Comment by clarkus** [comment]
A user guide will be great for this regardless of the changes we make to the UI. It's a complex enough topic that providing a walkthrough feels valuable to me. Short of reworking the workflow for specifying a formula, we might also use overlays or some modular walkthrough injected into the product to help guide usage. Both solutions are focused on support content, just delivered via different mechanisms.

**Comment by paolodamico** [comment]
@clarkus would you be okay taking this on during next sprint so we can ship it in our effort to "nail insights experience"? Happy to help implement it afterwards

**Comment by clarkus** [comment]
> @clarkus would you be okay taking this on during next sprint so we can ship it in our effort to "nail insights experience"? Happy to help implement it afterwards

Sure I think there are some closely related issues that might be able to be solved along with this one. Thoughts? 
- https://github.com/PostHog/posthog/issues/3375
- https://github.com/PostHog/posthog/issues/2594
- https://github.com/PostHog/posthog/issues/2273
- https://github.com/PostHog/posthog/issues/7289

**Comment by clarkus** [comment]
This is a work in progress but wanted to share some concepts for how formulas could fold into the query builder. The idea is that there is an alternate graph series row component with a subset of variables. The variables would be referenced in a formula field that also allows for custom names. The tricky part here is filtering on each variable. Thoughts on this approach?

<img width="676" alt="Screen Shot 2021-12-02 at 3 04 32 PM" src="https://user-images.githubusercontent.com/254612/144517051-e3489680-b0c1-46ed-b245-de05830d6df8.png">

https://www.figma.com/file/gQBj9YnNgD8YW4nBwCVLZf/PostHog-App?node-id=5626%3A44519

**Comment by paolodamico** [comment]
I like the idea of rethinking this from scratch. I have some concerns as it introduces a very different way of building insights. Some concrete points,
* I don’t think we currently support either multiple formulas on a graph nor a mix of a formula series and regular series (unsure how technically complex this would be, but we may want to avoid building this).
* When trying out new designs for the insight builder we overwhelmingly got the feedback that having the math selector (e.g. Total count) before the event/action name was very unintuitive. 
* With this design it would be hard to switch between a formula and a regular series, probably an edge case, but still if you have multiple filters it’d be annoying to have to redo them.

**Comment by mariusandra** [comment]
The last point can be solved by making it possible to drag the "x" and "y" rows as well. You'd then drag one in or out of the formula.

There's definitely an unspecified amount of backend work that needs to accompany this.

**Comment by clarkus** [comment]
> There's definitely an unspecified amount of backend work that needs to accompany this.

@timgl had the same feedback. I think it's primarily based on being able to support multiple formula graph series, but we could limit to just one formula per query for now?

**Comment by clarkus** [comment]
> When trying out new designs for the insight builder we overwhelmingly got the feedback that having the math selector (e.g. Total count) before the event/action name was very unintuitive.

Is there anything else documented to validate or elaborate on this feedback? How many users did we talk to? I tried searching but didn't see anything that stood out as being obviously related. The reason I ask is that there's more and more justification for having an intermediate selection step before picking events or properties or otherwise spelunking through what might be a really huge list of stuff. If we know what kind of aggregation we're doing, we can optimize for finding the right kinds of things. This is also going to be reiterated in filters when we need logical operators on cohort membership, users who did events within a certain time range, etc.

**Comment by paolodamico** [comment]
I'm sorry, can't seem to find where we documented this user feedback. You can see the design we tried [here](https://github.com/PostHog/posthog/issues/4050#issuecomment-823563641). IIRC we interviewed 4-6 users and all but one got confused with this layout. Of course it could've been this is just what they were used to, but users consistently were expecting to select the event/action first.

We can run more usability tests on this, but to maximize our value out of them, I'd suggest testing with the whole thing fully final draft. We could do this right after getting back from holidays. Thoughts?

**Comment by Twixes** [comment]
This should be clearer now with formula mode. Haven't seen this really brought up since.
