### ISSUE TITLE
Unexpectedly high incidence of "Capture Failed Requests"

### ISSUE THREAD

**Issue by pauldambra** [PostHog/posthog#6263]
## Bug description

In [this slack discussion](https://posthog.slack.com/archives/C02E3BKC78F/p1633441025137900) it was noted that all of the events page was "capture failed requests" events

![image](https://user-images.githubusercontent.com/984817/136049348-501386a7-42ee-4cfc-9dd7-0789cf7a67ec.png)

These events are logged from the `CaptureMetrics` class in posthog-js https://github.com/PostHog/posthog-js/blob/f9a6fb9446e886740dc73276523ec95e08abd913/src/capture-metrics.js#L47

If capture metrics requests are unsent at page unload (i.e. a browser window being closed) then capture failed requests attempts to notify the server of them

if there is an error when sending events or snapshot data to the API then capture failed requests notifies the server

-------

Looking at those events in posthog insights

👉  by day over the last 90 days
![Screenshot 2021-10-05 at 14 50 29](https://user-images.githubusercontent.com/984817/136048281-b82924cd-4595-4a9c-a57b-d81c286f25cd.png)

👉  and by minute over the last day
![Screenshot 2021-10-05 at 14 57 08](https://user-images.githubusercontent.com/984817/136048290-3ac15da3-54ab-49c9-8d2b-97ea9d4f6bcb.png)

capture failed requests seems very intermittently bursty

👉  looking at the graph by minute over the last day broken down by URL
![Screenshot 2021-10-05 at 15 01 12](https://user-images.githubusercontent.com/984817/136048294-363271bc-a744-4994-8096-9e0fba68c093.png)

the bursts of activity are primarily large bursts for one URL

👉 comparing failed requests to page views (or to capture metrics)
![Screenshot 2021-10-05 at 15 07 14](https://user-images.githubusercontent.com/984817/136048299-05676962-336f-412d-abec-86c20829a4d6.png)

doesn't show an increase in page views/capture metrics when there is an increase in failed requests

e.g. [this insight](https://app.posthog.com/insights?insight=TRENDS&events=%5B%7B%22id%22%3A%22%24capture_failed_request%22%2C%22math%22%3Anull%2C%22name%22%3A%22%24capture_failed_request%22%2C%22type%22%3A%22events%22%2C%22order%22%3A0%2C%22properties%22%3A%5B%5D%2C%22custom_name%22%3Anull%2C%22math_property%22%3Anull%7D%2C%7B%22id%22%3A%22%24capture_metrics%22%2C%22math%22%3Anull%2C%22name%22%3A%22%24capture_metrics%22%2C%22type%22%3A%22events%22%2C%22order%22%3A1%2C%22properties%22%3A%5B%5D%2C%22custom_name%22%3Anull%2C%22math_property%22%3Anull%7D%5D&display=ActionsLineGraph&interval=hour&date_from=dStart&filter_test_accounts=true&properties=%5B%5D#fromItem=430980&fromItemName=ratio%20of%20capture%20failed%20to%20capture%20metrics&fromDashboard) or [this one](https://app.posthog.com/insights?insight=TRENDS&events=%5B%7B%22id%22%3A%22%24capture_failed_request%22%2C%22math%22%3Anull%2C%22name%22%3A%22%24capture_failed_request%22%2C%22type%22%3A%22events%22%2C%22order%22%3A0%2C%22properties%22%3A%5B%5D%2C%22custom_name%22%3Anull%2C%22math_property%22%3Anull%7D%5D&display=ActionsLineGraph&interval=hour&breakdown=status&date_from=dStart&breakdown_type=event&filter_test_accounts=true&properties=%5B%5D#fromItem=431003&fromItemName=capture%20failed%20request%20by%20status%20code&fromDashboard)

**Comment by pauldambra** [comment]
cc @leggetter in case you want to amend or add to this

**Comment by timgl** [comment]
I highly suspect this has something to do with https://github.com/PostHog/posthog.com/pull/2138 given this is only happening on posthog.com
