### ISSUE TITLE
Support multiple webhooks

### ISSUE THREAD

**Issue by alexkim205** [PostHog/posthog#6265]
## Is your feature request related to a problem?

If practically possible, we should support multiple webhooks. Several people reached out about having different webhooks for different channels. 

## Describe the solution you'd like

Adding several rows of webhooks here. Maybe have a limit to how many each project can have to 5 to reduce server load.

<img width="1156" alt="Screen Shot 2021-10-05 at 10 28 25 AM" src="https://user-images.githubusercontent.com/13460330/136073082-af178095-047a-4cf1-b319-92310238deda.png">

## Describe alternatives you've considered

Not having multiple webhooks.

**Comment by antoremin** [comment]
would love this one
