### ISSUE TITLE
Tracking OS version

### ISSUE THREAD

**Issue by lowe0292** [PostHog/posthog#6268]
## Is your feature request related to a problem?

We've been debugging with a few users around the recent SSL cert changes with Let's Encrypt, and we were surprised to find OS version missing.

## Describe the solution you'd like

We'd love to see OS version alongside OS–similar to Browser & Browser version.

## Describe alternatives you've considered

Google Analytics has OS version 😸 

## Additional context

Big PostHog fans over here at Gather ❤️

**Comment by macobo** [comment]
cc @yakkomajuri - great small task for the libraries backlog?

**Comment by yakkomajuri** [comment]
I could pick this up but opening it up as a good first issue first. Seems like a great task for new contributors.

The relevant change would be made to https://github.com/PostHog/posthog-js and it's a matter of pulling this from the `navigator` object

**Comment by imskr** [comment]
Can I work on this? @yakkomajuri

**Comment by neilkakkar** [comment]
Hey @imskr ! Yes, go for it! Happy to answer any questions you have :)

**Comment by imskr** [comment]
@neilkakkar so i have to create a function that returns os version similar to here https://github.com/PostHog/posthog-js/blob/master/src/utils.js#L732 right?

**Comment by neilkakkar** [comment]
Precisely

**Comment by okellogabrielinnocent** [comment]
From my investigation on where the data for os_version is coming from, the navigator browser function does not pick the os_version as of recent years and this can can only be done at node level e.g os.release() function will give you the version or release of the OS.

**Comment by Narcos101** [comment]
@neilkakkar is this issue still open?

**Comment by neilkakkar** [comment]
yes
