### ISSUE TITLE
Bug: Search prompts not working

### ISSUE THREAD

**Issue by joethreepwood** [PostHog/posthog#6281]
## Bug description

Search prompts aren't working. I use the search bar in the top left of app.posthog.com, get a prompt for potential results, click them, nothing happens except the modal closes. 

## Expected behavior

Expect to be taken to relevant result. 

## How to reproduce

1. Open search modal. 
2. Click suggested result. 
3. Nothing happens. 

## Environment

- [x] PostHog Cloud
- [ ] self-hosted PostHog (ClickHouse-based), version/commit: _please provide_
- [ ] self-hosted PostHog (Postgres-based, legacy), version/commit: _please provide_

## Additional context

<img width="1195" alt="Screenshot 2021-10-06 at 13 40 12" src="https://user-images.githubusercontent.com/84011561/136203992-171f4360-80a7-4bd7-8a67-ca108ff28b97.png">

**Comment by Twixes** [comment]
Hm, can't reproduce. Does this still happen? If so, could you check if anything (an error) appears in the Chrome dev tools console?

**Comment by joethreepwood** [comment]
Still happening in Brave. Only error was 'Incorrectly formatted colour string'.

Grabbed a quick video of it happening [here](https://drive.google.com/file/d/1eOYNO-EvG1cpXueDpy4R3-Xy-GRe1L-B/view?usp=sharing), with console visible.

**Comment by joethreepwood** [comment]
Tested and get the same issue still occuring in both Chrome and Safari.

**Comment by Twixes** [comment]
Turns out it was only a problem with _clicking_ on the result, and I didn't reproduce it initially because I was hung up the Enter button. Now this is fixed!
