### ISSUE TITLE
Feedback: Pinned Dashboards

### ISSUE THREAD

**Issue by joethreepwood** [PostHog/posthog#6283]
A minor suggestion/bit of feedback. Short version is: should we consider removing the 'All Dashboards' results from the pinned dashboards tooltips and should items be pinned at an individual level?

<img width="408" alt="Screenshot 2021-10-06 at 13 59 52" src="https://user-images.githubusercontent.com/84011561/136207120-1cfddd09-24bb-41d6-ad0d-d79c59f25e3e.png">

**Size of tooltip**
With the pinned dashboards alone our list of dashboards is already disappearing off the end of a 4K screen and we're having to lengthen pages to accommodate the size of the list. We then exacerbate that by having all remaining dashboards listed underneath. 

In my experience, that makes it harder to find the correct dashboard, rather than easier because I now have a huge list I need to scroll through. 

**Items pinned at an individual level**
My understanding at the moment is that pinning a dashboard pins it for _everyone_ in an organization. There are probably some dashboards organizations want universally pinned (e.g. PostHog News), but as an individual I don't want _everyone's_ pinned dashboards to be pinned for me. The _AARRR -PostHog News_ and _Marketing_ dashboards are useful for me, but _Marcus Sandbox_ and _Marcus Test_ and _TestDash_ and _UX Experiment - May 2021_ are not, but still sit between me 

Normally, I'd expect that when I see Pinned items I'm seeing items which are pinned either by the org owner (James) or by me, rather than having to see what _everyone_ has pinned.

**Comment by Twixes** [comment]
Agreed! This will be redesigned to accommodate situations like this in our UI refresh (https://github.com/PostHog/posthog/issues/5346), so closing. Stay tuned.
