### ISSUE TITLE
Dashboard (or insight) fails to load

### ISSUE THREAD

**Issue by leggetter** [PostHog/posthog#6285]
## Bug description

I quite frequently have problems where either an Insight or Dashboard does not load. In this case, the dashboard does not load.

## Expected behavior

The Dashboard or Insight should load.

If the error is caused by a network issue of some sort (but, as mentioned, this happens a lot) then a different message in the center of the screen may be better.

## How to reproduce

The following video shows the Dashboard as empty. However, it should not be empty.

https://user-images.githubusercontent.com/328367/136211017-d9c85863-f8f9-4fda-a727-0ad2054b0c9b.mp4

## Environment

- [x] PostHog Cloud
- [ ] self-hosted PostHog (ClickHouse-based), version/commit: _please provide_
- [ ] self-hosted PostHog (Postgres-based, legacy), version/commit: _please provide_

**Comment by macobo** [comment]
I haven't watched the video. Couple of clarifications though: Is this consistent? How to repro? Mind sharing a link?

**Comment by leggetter** [comment]
> Is this consistent?

No. You can perform the same action and sometimes it loads fine. Other times it fails.

> How to repro?

See video. If you click around enough it'll eventually happen.

> Mind sharing a link?

See video. Any dashboard should do.

**Comment by mariusandra** [comment]
A bit of refactor went into insights recently. This may help with some of the issues, however it probably won't solve the "error on all items" error. 

Can you open the Chrome devtools network tabs and share what "Fetch/XHR" type requests fail and with what kind of response?

**Comment by paolodamico** [comment]
Ping @leggetter for help here. Are you still experiencing this?

**Comment by pauldambra** [comment]
I can't repro specifically this right now... but I'm tethered to my phone and on a slow connection so the dashboard insights were showing as having no matching events and suggesting I make edits while still loading

So currently distinguishing the difference between a dashboard/insight before it has finished loading and when it has finished and is empty is confusing...

![slowloiading](https://user-images.githubusercontent.com/984817/144016455-3f60e022-e783-41d1-8d6a-9e86259c888d.gif)
