### ISSUE TITLE
Editing an Insight without explicitly saving unexpectedly saves the Insight

### ISSUE THREAD

**Issue by leggetter** [PostHog/posthog#6286]
## Bug description

Insights have a "Save" button to allow a user to explicitly save an Insight. However, Insights appear to save without the need to click "Save". This is confusing and also results in unwanted changes being saved.

## Expected behavior

Do not save an Insight until "Save" is explicitly clicked.

## How to reproduce

https://user-images.githubusercontent.com/328367/136211993-2c25d420-e4b5-4910-bccc-f24e38958a6d.mp4

## Environment

- [x] PostHog Cloud
- [ ] self-hosted PostHog (ClickHouse-based), version/commit: _please provide_
- [ ] self-hosted PostHog (Postgres-based, legacy), version/commit: _please provide_

**Comment by mariusandra** [comment]
@leggetter This should be solved now, can you confirm if it is for you

**Comment by leggetter** [comment]
@mariusandra the graph in the dashboard is now showing as expected, yes.

But the behaviour of clicking "View" for a graph in a dashboard has changed. It used to take you to a view mode and there would be an Edit button. Now it takes you directly into Edit mode and there are only "Reset" and "Add to Dashboard" actions. Is that expected?

**Comment by mariusandra** [comment]
Do you also see the "explore" button in the menu? If not, you might have gotten to a situation where you don't have the "saved insights" feature flag enabled due to some merged user or other issue (see in #core-analytics).

**Comment by leggetter** [comment]
> Do you also see the "explore" button in the menu?

No, I don't. So I don't have the feature flag enabled.

**Comment by mariusandra** [comment]
This should have been resolved by now. Feel free to reopen if that's not the case.
