### ISSUE TITLE
Design Bug: Tables & Table Background Resizing

### ISSUE THREAD

**Issue by joethreepwood** [PostHog/posthog#6294]
## Bug description

Some app.posthog.com pages with tables in have broken formatting when the window is shrunk down to half a screen or so. 

For example, in the screenshot below you can see the table frame is now a different size to the table contents and occludes through the 'actions' header. 

<img width="1057" alt="Screenshot 2021-10-06 at 18 13 49" src="https://user-images.githubusercontent.com/84011561/136251959-353579ff-d40e-4d3e-94c4-c380c233a220.png">

## Expected behavior

Table frame should stay same size as table contents. 

## How to reproduce

1. Go to a page with a table. 
2. Resize the window smaller. 
3. Observe the table madness. 

## Environment

- [ ] PostHog Cloud
- [ ] self-hosted PostHog (ClickHouse-based), version/commit: _please provide_
- [ ] self-hosted PostHog (Postgres-based, legacy), version/commit: _please provide_

**Comment by paolodamico** [comment]
This seems addressed with the new `LemonTable`, @joethreepwood you can see it in dashboards & feature flags lists, please ping if yoou still see something wonky happening.
