### ISSUE TITLE
Insight filters have scollbars

### ISSUE THREAD

**Issue by macobo** [PostHog/posthog#6301]
## Bug description

![image](https://user-images.githubusercontent.com/148820/136332394-bb5570a7-c6b4-4571-b5a4-c0a3ace1c98b.png)

## Expected behavior

No scrollbars

## How to reproduce

0. Don't use a mac
1. Go to insights
2. Open filters
3. See scrollbars

## Environment

- [x] PostHog Cloud
- [ ] self-hosted PostHog (ClickHouse-based), version/commit: _please provide_
- [ ] self-hosted PostHog (Postgres-based, legacy), version/commit: _please provide_

## Additional context

cc @paolodamico @mariusandra

**Comment by mariusandra** [comment]
I think it came from https://github.com/PostHog/posthog/pull/6257 , will make a fix. 

This is the reason why I tell all Mac users working on frontend to always enable all scrollbars! :D
