### ISSUE TITLE
Integrations Library

### ISSUE THREAD

**Issue by joethreepwood** [PostHog/posthog#6316]
## Is your feature request related to a problem?

We have some users who have made some integrations and plugins for us, which we aren't celebrating anywhere. We also draw a distinction between plugins and integrations which isn't 100% clear to me, personally so maybe that should be factored in?

## Describe the solution you'd like

List third party integrations alongside first party ones. 
Potentially combine integrations and plugins into one central library. 

## Describe alternatives you've considered

Letting @yakkomajuri and @smallbrownbike come up with an actually good solution based on their [Slack thread](https://posthog.slack.com/archives/C01NWR6F58F/p1633619706031200). 

## Additional context

[List of all the integrations I could find quickly. 
](https://docs.google.com/spreadsheets/d/1Rg4aF-lkbPzcD2gbAoSoPz4SNjISMCvSachx9ePMCX8/edit?usp=sharing)

**Comment by yakkomajuri** [comment]
Could you give me edit access to the doc?

Zapier integration was built by us, and also there's an n8n integration that they built

**Comment by joethreepwood** [comment]
Done!

**Comment by kpthatsme** [comment]
Is the plan for this page to replace https://posthog.com/docs/integrate or to live alongside of it?

What about this page https://posthog.com/plugins?


2c from me:
- From customers calls, notes I've read, and general intuition I think the primary thing clients have questions around is whether PostHog can get data in/out of whichever system they are using
  - Whether something is a plugin, an SDK, or a first/third party integration is not a primary motivator
- We should design a page where it's easy to get to whichever integration you want, and whether it's a plugin/sdk/something else is a secondary piece of info
  - We should try to consolidate all ways to get data in / out of PostHog into a single page

I think Sentry does a great job at showing a great breadth of integrations while making it very easy to search and see the integration you care for (see attached).

  
<img width="1101" alt="Screen Shot 2021-10-18 at 10 29 30 AM" src="https://user-images.githubusercontent.com/5965891/137779517-c0b2cfba-d851-487b-948e-968376dd18ec.png">
<img width="1121" alt="Screen Shot 2021-10-18 at 10 30 02 AM" src="https://user-images.githubusercontent.com/5965891/137779528-e588e19e-166c-49a3-be30-2c1bccf23380.png">
