### ISSUE TITLE
Plugin-server swallows errors related to geoip

### ISSUE THREAD

**Issue by macobo** [PostHog/posthog#6332]
## Bug description

We have a user struggling with getting geoip plugin working on self-hosted clickhouse. $ip is sent and there's no errors for the plugin, but geodata does not appear.

There's nothing interesting in plugin server logs or in the geoip plugin logs

## Expected behavior

Some errors in any logs

## How to reproduce

? Unsure of the root cause

## Environment

- [ ] PostHog Cloud
- [x] self-hosted PostHog (ClickHouse-based), version/commit: 1.28
- [ ] self-hosted PostHog (Postgres-based, legacy), version/commit: _please provide_

## Additional context

cc @Twixes, @guidoiaquinti and @yakkomajuri - there's probably something we can do to expose issues here.

My assumption is that either connectivity or memory might mess things up?

**Comment by yakkomajuri** [comment]
What version are they running? We used to swallow errors on `setupPlugin` but that was recently (21 days ago) fixed:

https://github.com/PostHog/plugin-server/pull/579

**Comment by macobo** [comment]
1.28.1 

This issue is geoip specific since the code handling it is in the plugin server and we seem to be swallowing all errors related to it: https://github.com/PostHog/plugin-server/blob/master/src/worker/mmdb.ts https://github.com/PostHog/plugin-server/blob/master/src/worker/vm/extensions/geoip.ts

Not 100% confident though.

**Comment by macobo** [comment]
The issue was https://github.com/PostHog/posthog/issues/6334 - though I think we could still log something re this :)

**Comment by Twixes** [comment]
I don't _think_ the plugin server can do much here. It's kind of a garbage in, garbage out situation. The only thing we could do is log "this IP address couldn't be matched to a location"… but that'd be a flood and barely useful at all in case of something like #6334.
