### ISSUE TITLE
Complete typing for `FilterType`

### ISSUE THREAD

**Issue by mariusandra** [PostHog/posthog#6345]
All our insight queries are typed through `FilterType`, yet [this type itself](https://github.com/PostHog/posthog/blob/007db2c88499b63cd97e412ba19cfd20a162a3a8/frontend/src/types.ts#L713) isn't really well typed. It has come a long way, but still has a few `any`s:

```ts
export interface FilterType {
    events?: Record<string, any>[]
    actions?: Record<string, any>[]
    new_entity?: Record<string, any>[]
    returning_entity?: Record<string, any>
    target_entity?: Record<string, any>
    funnel_filter?: Record<string, any>
}
```

These should be updated to match reality, as they are causing some friction while developing. Yet this is a big enough refactor to be isolated into its own PR.

## Additional context

Documented technical debt gets solved faster!

**Comment by pauldambra** [comment]
HogQL ftw
