### ISSUE TITLE
Existing Insights broken by unexpected exclusion filters

### ISSUE THREAD

**Issue by leggetter** [PostHog/posthog#6349]
## Bug description

Existing Insights are currently showing with the message:

> There was an error completing this query

When investigating and editing the existing insights the filter is unexpectedly populated with a number of exclusions that look to have come from the global exclusion filter.

![image](https://user-images.githubusercontent.com/328367/136768101-14ccdeb1-db00-4927-b9f9-dade3ebe5e31.png)

## Expected behavior

The Insights were not edited so should have continued to load/work and the filters should not be present as were not defined when creating the Insight.

## How to reproduce

This shows how to see one example of the problem.

1. Go to https://app.posthog.com/dashboard/13064
2. Click "view" for the "Tutorials" graph
3. Click "Edit" and you'll see the unexpected filters

I've seen this twice today and fixed the other Insight. I had to **reset** the Insight and recreate the query to fix.

## Environment

- [x] PostHog Cloud
- [ ] self-hosted PostHog (ClickHouse-based), version/commit: _please provide_
- [ ] self-hosted PostHog (Postgres-based, legacy), version/commit: _please provide_

**Comment by macobo** [comment]
This should now be fixed! Some queries might not be cached anymore though.
