### ISSUE TITLE
Code quality issues with new sessions query

### ISSUE THREAD

**Issue by macobo** [PostHog/posthog#6382]
## Is your feature request related to a problem?

As part of https://github.com/PostHog/posthog/pull/6346 I needed to touch and modify session recording queries.

This pointed out some pretty big issues with the query, documenting them here for sake of async communication.

## Example clickhouse query

For the following filters, here's what the query looks like

![image](https://user-images.githubusercontent.com/148820/136928847-730e73d1-6759-4d61-aaf6-9145a89ab9ad.png)

```sql
SELECT *
  FROM (
        SELECT session_recordings.session_id,
               any(session_recordings.start_time) as start_time,
               any(session_recordings.end_time) as end_time,
               any(session_recordings.duration) as duration,
               any(filtered_events.distinct_id) as distinct_id ,
               sum(event_match_0) as count_event_match_0,
               sum(event_match_1) as count_event_match_1
          FROM (
                SELECT timestamp,
                       distinct_id ,
                       if(event = '$pageview' AND distinct_id IN (SELECT distinct_id FROM (SELECT distinct_id, argMax(person_id, _timestamp) as person_id FROM (SELECT distinct_id, person_id, max(_timestamp) as _timestamp FROM person_distinct_id WHERE team_id = 1 GROUP BY person_id, distinct_id, team_id HAVING max(is_deleted) = 0) GROUP BY distinct_id) WHERE person_id IN (SELECT id FROM (SELECT id, argMax(properties, person._timestamp) as properties, max(is_deleted) as is_deleted FROM person WHERE team_id = 1 GROUP BY id HAVING is_deleted = 0) WHERE 1 = 1 AND has(['Chrome'], trim(BOTH '"' FROM JSONExtractRaw(properties, '$browser'))) ) ), 1, 0) as event_match_0,
                       if(event = '$pageview' AND distinct_id IN (SELECT distinct_id FROM (SELECT distinct_id, argMax(person_id, _timestamp) as person_id FROM (SELECT distinct_id, person_id, max(_timestamp) as _timestamp FROM person_distinct_id WHERE team_id = 1 GROUP BY person_id, distinct_id, team_id HAVING max(is_deleted) = 0) GROUP BY distinct_id) WHERE person_id IN (SELECT id FROM (SELECT id, argMax(properties, person._timestamp) as properties, max(is_deleted) as is_deleted FROM person WHERE team_id = 1 GROUP BY id HAVING is_deleted = 0) WHERE 1 = 1 AND has(['94'], trim(BOTH '"' FROM JSONExtractRaw(properties, '$browser_version'))) ) ), 1, 0) as event_match_1
                  FROM events
                 WHERE team_id = 1
                   AND timestamp >= '2021-09-11 12:00:00'
                   AND timestamp <= '2021-10-12 21:13:49'
                   AND (
                     event = '$pageview' AND distinct_id IN (SELECT distinct_id FROM (SELECT distinct_id, argMax(person_id, _timestamp) as person_id FROM (SELECT distinct_id, person_id, max(_timestamp) as _timestamp FROM person_distinct_id WHERE team_id = 1 GROUP BY person_id, distinct_id, team_id HAVING max(is_deleted) = 0) GROUP BY distinct_id) WHERE person_id IN (SELECT id FROM (SELECT id, argMax(properties, person._timestamp) as properties, max(is_deleted) as is_deleted FROM person WHERE team_id = 1 GROUP BY id HAVING is_deleted = 0) WHERE 1 = 1 AND has(['Chrome'], trim(BOTH '"' FROM JSONExtractRaw(properties, '$browser'))) ) ) 
                     OR event = '$pageview' AND distinct_id IN (SELECT distinct_id FROM (SELECT distinct_id, argMax(person_id, _timestamp) as person_id FROM (SELECT distinct_id, person_id, max(_timestamp) as _timestamp FROM person_distinct_id WHERE team_id = 1 GROUP BY person_id, distinct_id, team_id HAVING max(is_deleted) = 0) GROUP BY distinct_id) WHERE person_id IN (SELECT id FROM (SELECT id, argMax(properties, person._timestamp) as properties, max(is_deleted) as is_deleted FROM person WHERE team_id = 1 GROUP BY id HAVING is_deleted = 0) WHERE 1 = 1 AND has(['94'], trim(BOTH '"' FROM JSONExtractRaw(properties, '$browser_version'))) ) ))
               ) AS filtered_events
          JOIN (
                SELECT all_recordings.session_id,
                       all_recordings.start_time,
                       all_recordings.end_time,
                       all_recordings.duration,
                       all_recordings.distinct_id
                  FROM (
                        SELECT session_id,
                               distinct_id,
                               MIN(timestamp) AS start_time,
                               MAX(timestamp) AS end_time,
                               dateDiff('second', toDateTime(MIN(timestamp)), toDateTime(MAX(timestamp))) as duration,
                               COUNT((JSONExtractInt(snapshot_data, 'type') = 2 OR JSONExtractBool(snapshot_data, 'has_full_snapshot')) ? 1 : NULL) as full_snapshots
                          FROM session_recording_events
                         WHERE team_id = 1
                           AND timestamp >= '2021-09-11 12:00:00'
                           AND timestamp <= '2021-10-12 21:13:49'
                         GROUP BY session_id,
                                  distinct_id
                       ) as all_recordings
                 WHERE full_snapshots > 0
                   AND start_time >= '2021-09-12 00:00:00'
                   AND start_time <= '2021-10-12 09:13:49'
                   AND duration > 60
               ) AS session_recordings
            ON session_recordings.distinct_id = filtered_events.distinct_id
         WHERE filtered_events.timestamp >= session_recordings.start_time
           AND filtered_events.timestamp <= session_recordings.end_time
         GROUP BY session_recordings.session_id
       ) as session_recordings
 WHERE count_event_match_0 > 0
   AND count_event_match_1 > 0
 ORDER BY start_time DESC
 LIMIT 51
OFFSET 0
```

## What are the issues.

1. The query building code for postgres and clickhouse are shared.
    - This is a bad idea since the "shape" of the query will need to be different for postgres and clickhouse to make various features work. Treating them the same makes following the code harder and makes refactoring harder.
2. Inefficient subqueries for properties
    - In the query above, for 2 filters 4 subqueries for person properties are made. This causes issues since we query the persons table multiple times in unneeded ways.
    - Instead we should be joining with `person` table. 
    - There's no reason to OR person properties given that session is done by a single person. This means we can push all person property filters into the joined person query. See how it's done in https://github.com/PostHog/posthog/pull/6346
    - If you do this you can probably extend this to start grouping by session_id only as well and roll distinct_id changed sessions into one :)
3. Minor: Instead of serializing each entity and ORing them together, I suggest using `and event in %(list)` - this will be more efficient due to how we've set up the events table. See ee/clickhouse/queries/funnels/funnel_event_query.py for an example of this.
4. Typing responses should use TypedDict. See recent examples from @hazzadous through the codebase

## Additional context

cc @rcmarron 

This likely doesn't need to be actioned immediately but I expect you'll be working on this query anyways and finding times to sync is hard so documenting :shrug:

**Comment by rcmarron** [comment]
Thanks for the review + explanation @macobo! This is very helpful!

> The query building code for postgres and clickhouse are shared.

I went back and forth on this as I was working on it - will definitely split them out before adding more to this query.

> Inefficient subqueries for properties

This generally makes sense to me. I'm sure I'll have some questions as I'm working on it. It'd be great to close this out #6319 and make the query faster!

> Minor: Instead of serializing each entity and ORing them together, I suggest using and event in %(list) - this will be more efficient due to how we've set up the events table. See ee/clickhouse/queries/funnels/funnel_event_query.py for an example of this.

✅ Makes sense

> Typing responses should use TypedDict. See recent examples from @hazzadous through the codebase

✅ Makes sense

**Comment by macobo** [comment]
One extra thing I noticed - the query is not making any use of materialized columns either, which it should :)

**Comment by rcmarron** [comment]
https://github.com/PostHog/posthog/pull/7006
