### ISSUE TITLE
Long feature flag keys expose two defects

### ISSUE THREAD

**Issue by pauldambra** [PostHog/posthog#6396]
## Bug description

There is no max length when creating a feature flag key. The table that displays feature flags at `/feature_flags` does not handle that well

<img width="1327" alt="Screenshot 2021-10-12 at 20 57 14" src="https://user-images.githubusercontent.com/984817/137025362-4045e551-59fe-4696-9a31-6251df191781.png">

This also shows that the `PropertyKeyInfo` component displays long values incorrectly
when showing details on hover:
<img width="792" alt="Screenshot 2021-10-12 at 21 03 28" src="https://user-images.githubusercontent.com/984817/137025506-070b87a8-95f0-41db-a1e1-a0f282413826.png">

or in a list row
<img width="330" alt="Screenshot 2021-10-12 at 21 37 22" src="https://user-images.githubusercontent.com/984817/137025746-9349e254-6b03-4294-b903-822fa3143222.png">

## Expected behavior

either text is cut off by its container and shows an ellipsis or its container grows to contain it

## How to reproduce

1. create a feature flag with a very long key
2. view it in any propertykey container

## Environment

- [x] PostHog Cloud
- [ ] self-hosted PostHog (ClickHouse-based), version/commit: _please provide_
- [ ] self-hosted PostHog (Postgres-based, legacy), version/commit: _please provide_

**Comment by leirons** [comment]
Here you just need to add max_length to the field in the model

**Comment by pauldambra** [comment]
Thanks @leirons. I'd worry that fixes it for any new keys but risks leaving any existing keys that are longer than that max length in an impossible state.

I think we need to accommodate whatever the current effective max length is
