### ISSUE TITLE
DAU selection in trends is confusing

### ISSUE THREAD

**Issue by jamesefhawkins** [PostHog/posthog#640]
**Is your feature request related to a problem? Please describe.**
We currently have two types of filter for Total versus DAU on trends.

![Screenshot 2020-04-22 at 12 05 55](https://user-images.githubusercontent.com/47497682/79974796-d365a600-8491-11ea-9fd2-1507a4dbbc1b.png)

DAU can be a little confusing when you graph it over time.

If you set the chart frequency to be weekly, it sums up all the DAUs for every day in that week, so it's not the unique volume of users within the timeframe.

**Describe the solution you'd like**

Open to other suggestions, how about:

* Instead of DAU have "Unique Users" or "Uniques".
* This means then if you look at a daily, weekly or monthly chart, you could choose to see the trend in DAUs, WAUs or MAUs
* We could have both DAUs and Uniques in the filter, but I think this adds more confusion.

**Comment by timgl** [comment]
There is a genuine case for having WAU shown per day.

For example, showing a day interval
- 22 April: uniques show all unique users that day, WAU show the unique number of users for Apr 16 - Apr 22
- 21 April: ...., WAU show unique users for Apr 15 - Apr 21

Either way, if "weekly" is selected both Unique and WAU should show the exact same number.

I do agree Uniques are a lot easier to grok over any time period, and avoid us having to block certain intervals for certain combinations of selections etc, so happy to do whatever is easier. I will have a look at this

**Comment by jamesefhawkins** [comment]
Your solution is better, as it’s more powerful and less confusing.

**Comment by timgl** [comment]
OK so turns out what we call 'DAU' is actually 'Uniques'. I suggest we just update that naming everywhere to make it less confusing. We can always add DAU/WAU/MAU.

**Comment by EDsCODE** [comment]
> OK so turns out what we call 'DAU' is actually 'Uniques'. I suggest we just update that naming everywhere to make it less confusing. We can always add DAU/WAU/MAU.

Agree with the 'uniques' term. I remember being puzzled by what DAUs meant in the case described above when working on my first ticket. Unfortunately, I wasn't in the write everything down mindset at that point!

**Comment by Twixes** [comment]
This is now explained in the UI.
