### ISSUE TITLE
[EPIC] Aggregated data trust query issues

### ISSUE THREAD

**Issue by marcushyett-ph** [PostHog/posthog#6400]
I'm using this ticket to aggregate together issues affecting data trust - specifically around inconsistent results coming from querying. Some are existing issues others are just comments or quotes from customers.

**Persons Modal**
* https://github.com/PostHog/posthog/issues/6331
* https://github.com/PostHog/posthog/issues/6306
* https://github.com/PostHog/posthog/issues/6234
* https://github.com/PostHog/posthog/issues/1649
~~* [This chart](https://app.posthog.com/insights?insight=TRENDS&interval=day&display=ActionsLineGraph&events=%5B%7B%22id%22%3A%22insight%20viewed%22%2C%22name%22%3A%22insight%20viewed%22%2C%22type%22%3A%22events%22%2C%22order%22%3A0%2C%22properties%22%3A%5B%7B%22key%22%3A%22email%22%2C%22value%22%3A%22%40posthog.com%22%2C%22operator%22%3A%22icontains%22%2C%22type%22%3A%22person%22%7D%5D%2C%22math%22%3A%22dau%22%7D%5D&properties=%5B%5D&filter_test_accounts=false&actions=%5B%5D&new_entity=%5B%5D&date_from=-90d#fromItem=455532) – observe the July 29th data point shows 4 users but when clicking in 5 actually appear.~~
* https://github.com/PostHog/posthog/issues/6485

**Filters Inconsistency**
* [Filter out internal /test users is missing in come places](https://app.papercups.io/conversations/closed/3aca3efe-820b-40f9-97ff-7b5b5f3bbd92)

**Lifecycle**
* https://github.com/PostHog/posthog/issues/5466

**General Feedback**
* "I would like to see the raw SQL to be confident that the query is doing what I expect"
* "I kept getting the wrong results because the test filters behave opposite to how I would expect them to"

**Proposed Solutions**
* https://github.com/PostHog/product-internal/issues/154

@tiina303 suggested we use a project - we can migrate there after. I just wanted to bring everything I have together initially for @EDsCODE's context.

**Comment by tiina303** [comment]
Everything closed or tracked separately
