### ISSUE TITLE
Hide Toolbar when not called on

### ISSUE THREAD

**Issue by corywatilo** [PostHog/posthog#6420]
## Problem

The Toolbar seems to follow me around on a lot of pages when I don't want it. It feels like more of a nuisance than help, since I'm rarely in definition mode, even though I'm still signed in to PostHog in the background.

## Examples

![image](https://user-images.githubusercontent.com/154479/137199502-bbc94fe9-4e89-4f18-a108-4afba6edf4ad.png)
![image](https://user-images.githubusercontent.com/154479/137199519-48ed222e-6626-4ae0-adea-1f95250c2ad9.png)

## Feature request

Cookie its state, so if I X it out on a domain, it doesn't relaunch unless I specifically visit the PostHog app and launch it again via the Toolbar nav menu option.

![image](https://user-images.githubusercontent.com/154479/137199860-3dddcaab-5734-4aa2-aa87-bbeeb22e7866.png)

**Comment by clarkus** [comment]
Related https://github.com/PostHog/posthog/issues/2777

**Comment by pauldambra** [comment]
If you click the X to close the toolhog it doesn't load again for that site until you re-launch it

![2022-08-24 20 33 02](https://user-images.githubusercontent.com/984817/186507348-18e6c59a-f38a-4035-a5fa-5312389a7316.gif)

The toolbar on app.posthog.com and that on posthog.com are separate. So you have to close it on both.

I think that means this is a duplicate of #2777, and we need to decide if and how we let people dismiss the toolbar everywhere they are using it as well as on the current site. Is that right?

**Comment by corywatilo** [comment]
This must have been a bug then, as it used to pop up _all the time_ on the same site even after closing. Going to close since it seems resolved.
