### ISSUE TITLE
DashboardItems saved with blank filters

### ISSUE THREAD

**Issue by macobo** [PostHog/posthog#6439]
## Bug description

Users reported that some dashboard items have "lost their data". Looking at the db, some `DashboardItem` model instances have blank or near-blank `filters`.

## Expected behavior

No blank filters

## How to reproduce

Don't know how to repro.

Measuring code from the db:

```
def is_broken(item):
    filters = dict(item.filters)
    if 'from_dashboard' in filters:
        del filters['from_dashboard']
    return len(filters) == 0

BATCH_SIZE = 10000
items = DashboardItem.objects.all().order_by('-id').exclude(dashboard_id=None)
count = items.count()
broken_items = []
for batch_start in range(0, count, BATCH_SIZE):
    batch_items = items[batch_start:min(count, batch_start + BATCH_SIZE)]
    matching = [item for item in batch_items if is_broken(item)]
    broken_items.extend(matching)
    if matching:
        min_item = min(matching, key=lambda item: item.created_at)
        print(len(matching), min_item.created_at, min_item.updated_at)

for item in broken_items:
    print(item.filters)
    print([item.team.id, item.team.name, item.name, item.dashboard.name, item.created_at, item.updated_at, item.created_by])
```

Some of these seem to be created as early as August.

## Environment

- [x] PostHog Cloud
- [ ] self-hosted PostHog (ClickHouse-based), version/commit: _please provide_
- [x] #6451

**Comment by macobo** [comment]
@mariusandra I assume an accidental close?

**Comment by mariusandra** [comment]
Yup, must verify if it's actually fixed. Github took "Possibly fixes" as "Fixes" and closed it.

**Comment by Twixes** [comment]
Was this fixed? @mariusandra
