### ISSUE TITLE
Events page render loop

### ISSUE THREAD

**Issue by samwinslow** [PostHog/posthog#6449]
## Bug description

The Events page gets into a render loop race condition for one particular user. In the below GIF, note that almost every element in the body is rendering constantly before crashing React with a white screen.

The user states they may have deleted the persons associated with these events (causing each event's Person to show up as `Unidentified with no ids` in the table.

![Screen Cast 2021-10-14 at 3 14 28 PM](https://user-images.githubusercontent.com/4645779/137381737-868fda6a-3db4-4e7c-8aa9-064be8c7a61a.gif)

React interrupts this render loop and throws:

```
Too many re-renders. React limits the number of renders to prevent an infinite loop.
```

## Expected behavior

No render loop; handle missing persons safely if that is indeed the cause

## How to reproduce

1. Impersonate user and see events page

## Environment

- [ ] PostHog Cloud
- [ ] self-hosted PostHog (ClickHouse-based), version/commit: _please provide_
- [ ] self-hosted PostHog (Postgres-based, legacy), version/commit: _please provide_

**Comment by mariusandra** [comment]
If I replicate this and trace the error, it comes from `ResizableTable` calling `setHeaderShouldRender(false)`, which seem to throw things in a loop.

![image](https://user-images.githubusercontent.com/53387/137448544-a6dd53f4-07db-45e9-bb3e-07a4cb1c0109.png)
