### ISSUE TITLE
Trend chart with custom date range errors while loading on dashboard

### ISSUE THREAD

**Issue by rhvrabec** [PostHog/posthog#645]
**Describe the bug**
Create a trend chart with a custom date range. It looks fine under trends
But adding it to the dashboard produces the error in the attached image and endless 'loading spinner'. 

**To Reproduce**
1. click trend 
2. create chart
3. set custom date (03-01-2020 to 04-20-2020)
4. add to the dashboard
5. click to view dashboard
6. error pops up

**Expected behavior**
the chart loads fine on the dashboard

**Screenshots**
<img width="652" alt="Screen Shot 2020-04-21 at 6 29 21 PM" src="https://user-images.githubusercontent.com/22860224/80012580-22600b00-8493-11ea-9312-61d6df091c09.png">

**Desktop (optional: please complete the following information):**
 - OS: mac
 - Browser: chrome
 - Version: 

**Smartphone (optional: please complete the following information):**
 - Device: 
 - OS: 
 - Browser 
 - Version 

**Additional context**

**Comment by timgl** [comment]
@rhvrabec Fixed!
