### ISSUE TITLE
should_update_person_prop should update same timestamp set calls if last_op was set_once

### ISSUE THREAD

**Issue by tiina303** [PostHog/posthog#6458]
It's generally a waste of resourced to do updates when we see equal timestamps, but I think in this specific edge case we should. Since this is data integrity/trust edge cases are important.

Assume the current state is
```
val = 1
last_op = set_once
ts = THE_SAME
```
And we get a set request
```
val = 2
op = set
ts = THE_SAME
```

Currently we don't override it, but I think we should 
https://github.com/PostHog/posthog/blob/78edefe1531a3a1fd7e334b910b8bee873b5211f/posthog/migrations/0175_should_update_person_props_function.py#L27

There are two options: we can either make one of the conditions also include an equal sign (I suspect it's rare for us to see equal timestamps so I'm not really worried about wasted resources) or we can add the third explicit condition for this case:
```
(operation='set' AND last_operation='set_once' AND _timestamp == stored_timestamp)
```
We should add a test for this case also.

To illustrate with a table for equal timestamps
```
   | last_op   |  op        |  
1  | set_once  |  set_once  | we don't care, so better to not waste resources with a write 
2  | set_once  |  set       | override
3  | set       |  set_once  | don't override 
4  | set       |  set       | we don't care, so better to not waste resources with a write 
```

**Comment by tiina303** [comment]
Think about a case where we later see a set_once with an earlier timestamp. If we leave it as is we end up in an unexpected value. 

Example:
set_once(a=1, ts=5)
set(a=2, ts=5)
set_once(a=3, ts=4)

Currently we get a=3 in the end.

**Comment by yakkomajuri** [comment]
I mean, the argument makes sense. However, ultimately a user is sending us **equal** timestamps and in my view we should be able to pick how to behave. Your argument infers what the user might want, but if you do a `set` and `set_once` literally at the same time, how can I reasonably infer and generealize?

**Comment by tiina303** [comment]
They might end up with the same timestamp if they have multithreaded applications for example, so we can't necessarily assume they are doing something wrong.

Let me elaborate on my example: The primary reason why we want to override for set (if previously it was an equal ts set_once) is so that we operate reasonably on other calls with different timestamps:

Imagine we get the events in this order (as the timestamps are)
```
set_once(a=3, ts=4)
set_once(a=1, ts=5)
set(a=2, ts=5)
```
It's obvious that we end up with `a=2` in the end, the second `set_once` would never write anything. Now due to network we might see them in the other order
```
set_once(a=1, ts=5)
set(a=2, ts=5)
set_once(a=3, ts=4)
```
In which case if with equal timestamps we use the first call only we would
1st have (a=1,ts=5, last_op=set_once) ; 2. ignore (a=2,ts=5, last_op=set_once) ; 3 override as it's set_once with older ts (a=3,ts=4, last_op=set_once). Resulting with `a=3` in the end. I'm not sure how we order events in our UI, but if we use timestamps there to order them, then this would look like we messed up to the user.

However if set overrides set_once if the ts is equal, then 
1st have (a=1,ts=5, last_op=set_once) ; 2. override (a=2,ts=5, last_op=set) ; 3 ignore as older ts (a=2,ts=5, last_op=set). Resulting with `a=2` in the end.
