### ISSUE TITLE
Show timestamp information in recording player on hover

### ISSUE THREAD

**Issue by macobo** [PostHog/posthog#6473]
## Is your feature request related to a problem?

I've been trying to use the session recording player to debug some issues today. I've noticed finding the exact time user did $thing is hard.

## Describe the solution you'd like

- Show timestamp when hovering progress bar and events on the side
- Also: Highlight events I'm looking for on the side 

## Additional context

cc @clarkus @alexkim205 @paolodamico For the ongoing project :)

**Comment by clarkus** [comment]
Thanks for filing this, @macobo. We are definitely tracking changes for exposing timestamps in the player. The most recent version capture this at https://www.figma.com/file/gQBj9YnNgD8YW4nBwCVLZf/PostHog-App?node-id=4194%3A28924. 

> Also: Highlight events I'm looking for on the side

This is a recurring topic but I've been struggling to figure out how a user specifies this. Some ideas arose around inheriting filters from the list view into the player view, but that feels a little too buried to me. There's an event search on the on events list, but that is more for finding than highlighting important stuff. Would some means of specifying a list of important events to highlight be useful? We need some criteria for promoting events to the seek bar annotations position, so this could be a good starting point for that concept. 

related https://github.com/PostHog/posthog/issues/6077

**Comment by macobo** [comment]
I think highlighting events that match the search is a good starting point.

Usecase: I want to track down $problem user ran into (bug, unexpected behaviour, etc). I go to sessions and search for that event and for that user. Opening the session I want to have an easy way to skip to this event.

**Comment by paolodamico** [comment]
Ping @rcmarron in case we want to tackle it during this last recordings sprint
