### ISSUE TITLE
Saved Insights "save" button not showing up

### ISSUE THREAD

**Issue by liyiy** [PostHog/posthog#6490]
## Bug description

*Please describe.*  
*If this affects the front-end, screenshots would be of great help.*  

A user was confused about their empty saved insights page, but they were unable to save their insights because the header does not render the button for it

<img width="1577" alt="81b2835c36da4e8390ec91d2408190f0-posthog-no-save-insights" src="https://user-images.githubusercontent.com/25164963/137543763-f024ecc6-7e17-4ef8-894b-26a521e00717.png">

## Expected behavior

- Be able to save insights if the `saved insights` nav is available

## How to reproduce

1.
2.
3.

## Environment

- [ ] PostHog Cloud
- [ ] self-hosted PostHog (ClickHouse-based), version/commit: _please provide_
- [ ] self-hosted PostHog (Postgres-based, legacy), version/commit: _please provide_

**Comment by mariusandra** [comment]
Is the "saved insights" nav available? The screenshot just exactly cuts this out. To me this looks like how the page should look like if the feature flag is turned off.

**Comment by liyiy** [comment]
Yes, the user was asking why the "saved insights" nav was always returning an empty list and how they could get it to not be empty, and then they sent me that screenshot

**Comment by Twixes** [comment]
This should be fixed now.
