### ISSUE TITLE
Recording playback - Seekbar/Player

### ISSUE THREAD

**Issue by rcmarron** [PostHog/posthog#6491]
For a great playback experience, we need a player that supports some base-level functionality (e.g. buffering, seeking, etc)

This task outlines the work we (@clarkus @alexkim205 @rcmarron) discussed to get that there.

https://www.figma.com/file/gQBj9YnNgD8YW4nBwCVLZf/PostHog-App?node-id=3753%3A28483
![image](https://user-images.githubusercontent.com/4813045/137535642-a855bd33-6792-48eb-ad11-e462b0cc0763.png)

## Details

- Hovering over the seekbar will show the timestamp at that location. Unless you're over an event marker
- Bar "types"
    - Elapsed bar (red)
    - Loaded or ready to be played bar (light gray)
    - Total duration bar (dark gray)
- Duration
    - Use server duration until a locally calculated duration is available (after full buffering), and then flip to the local one.
- If the scrubber (red dot) is in the unloaded period, then move the player into a buffering state. And continue buffering from where the buffer currently is? (don't do the fancy thing)
- Player states
    - Buffering
        - On buffer finish, fall back to the user set playing/paused state
    - Playing/Paused
    - Error (potentially)
        - Potentially expose RRweb player warnings/errors
- Controls
    - Play and pause buttons
    - Skip forward and back
        - 10 seconds at 1x and then it adjusts with the playback speed. Maybe we just multiply them.
    - Playback speed
        - Keep them as is
    - Skip inactivity

**Comment by alexkim205** [comment]
Closing out bc of work started with #6529 and #6505
