### ISSUE TITLE
Recording playback - UX refresh

### ISSUE THREAD

**Issue by rcmarron** [PostHog/posthog#6492]
This is an issue to track a few UX changes related to the new player.

- Update the nav bar
- Update the parson card
    - Scale value and resolution are available from rrweb
- Other changes accounted for in: 
    - #6487 
    - #6491

https://www.figma.com/file/gQBj9YnNgD8YW4nBwCVLZf/PostHog-App?node-id=3753%3A28483
![image](https://user-images.githubusercontent.com/4813045/137535642-a855bd33-6792-48eb-ad11-e462b0cc0763.png)

**Comment by alexkim205** [comment]
Closing out bc of work started with #6529 and #6505
