### ISSUE TITLE
Checking dashboard "auto refresh" option doesn't stick

### ISSUE THREAD

**Issue by liyiy** [PostHog/posthog#6495]
## Bug description

*Please describe.*  
*If this affects the front-end, screenshots would be of great help.*  

Checking this option and then leaving the page will leave it unchecked

<img width="568" alt="Screen Shot 2021-10-15 at 8 19 06 PM" src="https://user-images.githubusercontent.com/25164963/137566308-434429b3-cd26-447a-881a-f6292185d248.png">

## Expected behavior
- enabling the auto refresh option on dashboard should preserve

## How to reproduce

1.
2.
3.

## Environment

- [ ] PostHog Cloud
- [ ] self-hosted PostHog (ClickHouse-based), version/commit: _please provide_
- [ ] self-hosted PostHog (Postgres-based, legacy), version/commit: _please provide_

**Comment by paolodamico** [comment]
I'm not sure if we should actually preserve this, it sounds more of a one-off use case.

**Comment by Twixes** [comment]
I kind of agree with Paolo, considering that auto-refresh only works as long as you're on the page (and not somewhere in the background in the backend), I think it's more intuitive for it to not be persisted. I'll close this for now.
