### ISSUE TITLE
Filters showing incorrect titles

### ISSUE THREAD

**Issue by liyiy** [PostHog/posthog#6496]
## Bug description

*Please describe.*  
*If this affects the front-end, screenshots would be of great help.*  

It looks like these property names are showing the ID instead of the title itself, in our filters

<img width="784" alt="Screen Shot 2021-10-15 at 8 21 54 PM" src="https://user-images.githubusercontent.com/25164963/137566383-0421e6bd-054c-419e-a35e-80eead799605.png">

## Expected behavior
Should show the name, not the ID of the filter

## How to reproduce

1.
2.
3.

## Environment

- [ ] PostHog Cloud
- [ ] self-hosted PostHog (ClickHouse-based), version/commit: _please provide_
- [ ] self-hosted PostHog (Postgres-based, legacy), version/commit: _please provide_

**Comment by mariusandra** [comment]
These look like deleted actions for me.

**Comment by paolodamico** [comment]
That would make sense, in which case we should handle how deleted actions are shown in the app.

**Comment by paolodamico** [comment]
I don't think it's worth prioritizing this spring, thoughts @mariusandra?
