### ISSUE TITLE
Documentation for deployment behind CDN

### ISSUE THREAD

**Issue by Immortalin** [PostHog/posthog#650]
If the user's CDN e.g. Cloudflare has redirect http to https enabled, this may cause redirect loops:
```
SECURE_SSL_REDIRECT = True
```

Suggestion: perhaps a UI config to turn it off if using CDNs?

**Comment by timgl** [comment]
@Immortalin Thanks for raising. [This is documented here](https://docs.posthog.com/#/deployment?id=running-behind-a-proxy), or is that not what you meant?
