### ISSUE TITLE
Cohort creation type dropdown not clickable

### ISSUE THREAD

**Issue by liyiy** [PostHog/posthog#6514]
## Bug description

*Please describe.*  
*If this affects the front-end, screenshots would be of great help.*  

Clicking "dynamic" doesn't open a dropdown or do anything as indicated by the down arrow

<img width="868" alt="Screen Shot 2021-10-18 at 8 55 20 AM" src="https://user-images.githubusercontent.com/25164963/137735175-d9114900-1ac8-40ac-946d-29ca134c2ebf.png">

## Expected behavior

Clicking on dynamic option does something

## How to reproduce

1.
2.
3.

## Environment

- [x] PostHog Cloud
- [ ] self-hosted PostHog (ClickHouse-based), version/commit: _please provide_
- [ ] self-hosted PostHog (Postgres-based, legacy), version/commit: _please provide_

**Comment by santoshkpatro** [comment]
I guess this issue is fixed??
Locallly it is opening

![cohert_error](https://user-images.githubusercontent.com/60396045/137751471-59ee8012-c17c-4d03-bda0-40d923e61024.png)

**Comment by liyiy** [comment]
Doesn't work for me still :/

**Comment by liyiy** [comment]
Seems like it's working now
