### ISSUE TITLE
Make sure all `health` check endpoints are leveraged

### ISSUE THREAD

**Issue by guidoiaquinti** [PostHog/posthog#6517]
## Is your feature request related to a problem?

We had at least a couple of reports where a functioning _service health_ endpoint could have helped to mitigate some service reliability issues. We should make sure we have a structured way to detect if a running service instance cannot handle requests. 

The API endpoint handler performs various checks, such as:

* the status of the connections to the infrastructure services used by the service instance

* the status of the host, e.g. disk space

* application specific logic

A health check client - a monitoring service, service registry or load balancer - periodically invokes the endpoint to check the health of the service instance.

## Describe the solution you’d like

All our services should expose a _service health_ endpoint (possibly via HTTP as it’s the best supported protocol) 

## Additional context

See more info about this pattern [here](https://microservices.io/patterns/observability/health-check-api.html). See also the related issue https://github.com/PostHog/posthog/issues/4278

**Comment by fuziontech** [comment]
Just to be clear here - we do have this pattern in PostHog
https://github.com/PostHog/posthog/blob/6c2444db0aa50f82875d74a34e0c9d2a4634f31b/posthog/views.py#L59

I imagine what you want here is for that endpoint to be a bit more full featured?

We do need this in Plugin Server:
https://github.com/PostHog/posthog/issues/7003

I think we should make auditing and scoping out what to build out in `/health` endpoints concretely a `P0`

**Comment by guidoiaquinti** [comment]
> I imagine what you want here is for that endpoint to be a bit more full featured?

Correct. This issue is to make sure we audit our current setup and we align it (if necessary) to follow the best practices linked [here](https://microservices.io/patterns/observability/health-check-api.html)
