### ISSUE TITLE
Selected Property Filters stack in a column

### ISSUE THREAD

**Issue by pauldambra** [PostHog/posthog#6518]
## Is your feature request related to a problem?

When selecting property filters they stack in a column. So on a large screen you have a lot of whitespace

### in a wide container

<img width="1328" alt="Screenshot 2021-10-18 at 15 53 55" src="https://user-images.githubusercontent.com/984817/137759464-328c0ca4-984e-4168-862c-a3c82da391e0.png">

### in a narrow container

<img width="471" alt="Screenshot 2021-10-18 at 16 12 36" src="https://user-images.githubusercontent.com/984817/137759476-28dcccca-be5c-44f2-be82-5867598a6810.png">

## Describe the solution you'd like

When the container is wide enough the selected filters should wrap and use all of the space.

## Describe alternatives you've considered

not changing it

**Comment by clarkus** [comment]
Strong 👍 on this. As part of the changes, we should also move those inline remove icons into the container for each item. That will more closely associate the action with the things it affects and give us a bit more room for this left-to-right sentence-like layout. BTW this same approach has been used in settings and a few other areas of upcoming work... there might be an existing implementation somewhere already.

**Comment by clarkus** [comment]
This same component layout is used in the upcoming "merge settings" work at https://github.com/PostHog/posthog/issues/4268.

**Comment by pauldambra** [comment]
this was already fixed at some point in the past
