### ISSUE TITLE
Funnel: switch from "Conversion Steps" to "Historical Trend" mode leads to empty state when "minutes" is selected in the conversion window

### ISSUE THREAD

**Issue by romj** [PostHog/posthog#6534]
## Bug description

I am in the funnel view, and I have a 2-step funnel, with some events and a working funnel
![Insights_•_PostHog](https://user-images.githubusercontent.com/44766458/137878843-a25e5b48-e968-42fe-9673-2678e183c723.png)

When I switch to historical trend, I reach an empty state
![Insights_•_PostHog](https://user-images.githubusercontent.com/44766458/137878897-ff403f3d-57ce-4092-a6a6-f3e19ee33c44.png)

If I focus on the conversion window, moving it back to 1 day showe the chart again

![Insights_•_PostHog](https://user-images.githubusercontent.com/44766458/137879245-5ccc0338-f4c6-46d1-9edb-4c3521cb8cb5.png)

Switching back to 90 minutes, or any value with minutes, fails. Note that the average time to convert, shown in the first screenshot, is 37 seconds, so the window should now affect the chart (or at least no remove 100% of events).

![Insights_•_PostHog](https://user-images.githubusercontent.com/44766458/137879348-e6e642f8-3460-47cd-a69d-de3eea6225ac.png)

## Expected behavior

Historical trands works with a conversion window in minutes

## How to reproduce

1. build a funnel
2. make a conversion window in minutes
3. switch to historical trend

## Environment

- [ ] PostHog Cloud
- [X] self-hosted PostHog (ClickHouse-based), version/commit: 1.28.1 // 5810c8a61623f128a5963d89d655ae88ada8eb19
- [ ] self-hosted PostHog (Postgres-based, legacy), version/commit: _please provide_

**Comment by neilkakkar** [comment]
Thanks Jean! What version of PostHog are you on?

**Comment by romj** [comment]
1.28.1. I updated the comment

**Comment by neilkakkar** [comment]
Thanks! Definitely a bug, I could reproduce.

https://sentry.io/organizations/posthog/issues/2730751148/?project=1899813&referrer=slack

For whoever picks it up:

`relativedelta` possibly converts date to datetime when the delta < 24 hours:

https://github.com/PostHog/posthog/blob/master/ee/clickhouse/queries/funnels/funnel_trends.py#L231
