### ISSUE TITLE
Ability to version lock the posthog-foss docker image

### ISSUE THREAD

**Issue by Roensby** [PostHog/posthog#6551]
## Is your feature request related to a problem?

As a developer, I would like to ensure that my docker image of posthog-foss is locked to a specific version, so I can control upgrades better and ensure sameness across dev, test and production environments.

## Describe the solution you'd like

Version locking as docker tags, preferably with semantic versioning like the posthog image has (maybe it can even use the same versions?)

## Describe alternatives you've considered

I could use the image build hash to lock my docker image to a specific version, but that's not a very good solution.

## Additional context

Currently, only the 'latest' tag is available: https://hub.docker.com/r/posthog/posthog-foss/tags

**Comment by Twixes** [comment]
That's obviously a great suggestion! We're releasing PostHog 1.29.0 this week and we'll make sure it gets tag `release-1.29.0` on `posthog-foss`, and that future versions will be tagged too. Will close this issue when that happens.
