### ISSUE TITLE
Trigger webhook on Action

### ISSUE THREAD

**Issue by viperfx** [PostHog/posthog#657]
**Is your feature request related to a problem? Please describe.**
Get alerted on when filters, funnels and actions happen.

**Describe the solution you'd like**
I believe this works already for Actions and pushing to Slack. But expanding this to other supported steps in posthog.

Has this been considered? I am wondering if it's worth having a discussion of whats possible right now and what can be extended.

**Comment by timgl** [comment]
I'm slightly struggling to understand the use case here.

I guess for funnels you could take the last step's Action and alert on that?

For filters, you're right in that we can't filter on event properties within actions at the moment, so that could be a good thing to add.

**Comment by viperfx** [comment]
For example, let's say posthog could have Slack as a destination, but also a webhook as a destination.

With a webhook, the customer's system could use to send emails or make an action on the app etc.

Use cases:

Event performed with a filter 
- Event - "User signed up"
   - Property "company_size" greater than 100.

- Event - "Event 1" and "Event 2" performed within the last 3 days.

**Comment by timgl** [comment]
Yes, very much agree. Webhooks are a great way to make posthog more extensible. Once we also have property filtering on actions you'll be able to do your example

 I'll change the title of this issue to make it a bit more obvious.

**Comment by paolodamico** [comment]
Closing this as it's now possible with our [Zapier integration](https://zapier.com/apps/posthog/integrations).
