### ISSUE TITLE
Supported Node.js version

### ISSUE THREAD

**Issue by guidoiaquinti** [PostHog/posthog#6570]
The recent Node.js v17 release broke our app because of an upstream breaking change (see more context here https://github.com/PostHog/posthog/pull/6569).

After discussing with @Twixes I found out we technically only support a single NodeJS version (14) across the board. We should make sure we accurately reflect this information in our requirements files as we currently imply version support `>=14 <17`.

**Comment by yakkomajuri** [comment]
Yeah so I'd advocate for Node v14 for now. We should soon migrate to Node 16 though on the plugin server.

**Comment by weyert** [comment]
Based on the versions discussed it appears only the most recent LTS version of Node.js will be supported? Which currently is v14 but from next week will be v16

**Comment by guidoiaquinti** [comment]
@yakkomajuri do you think we can now close this as we've upgraded to v16 recently? Do we enforce NodeJS version everywhere now?
