### ISSUE TITLE
Funnel conversion time window setting not updating on graph

### ISSUE THREAD

**Issue by liyiy** [PostHog/posthog#6581]
## Bug description

*Please describe.*  
*If this affects the front-end, screenshots would be of great help.* 

Go to funnels -> change the time conversion window -> save -> the graph doesn't reflect the correct time conversion window setting 

<img width="665" alt="Screen Shot 2021-10-20 at 2 33 58 PM" src="https://user-images.githubusercontent.com/25164963/138151366-9b6bec44-13bd-479f-afd5-1bcaf76a9715.png">

## Expected behavior

Time conversion window on funnels should be updated appropriately

## How to reproduce

1. Go to a funnel
2. Change the time conversion window + save
3. Notice that the time conversion window didn't save correctly 

## Environment

- [ ] PostHog Cloud
- [ ] self-hosted PostHog (ClickHouse-based), version/commit: _please provide_
- [ ] self-hosted PostHog (Postgres-based, legacy), version/commit: _please provide_

**Comment by desa** [comment]
![window-limit-not-saved](https://user-images.githubusercontent.com/1477539/138175127-c8fe144b-bc1b-41d8-ae5b-ae0119e31096.gif)

**Comment by mariusandra** [comment]
I think this was closed by https://github.com/PostHog/posthog/pull/6717
