### ISSUE TITLE
Unable to get any results from Lifecycle tool

### ISSUE THREAD

**Issue by joethreepwood** [PostHog/posthog#6606]
## In what situation are you experiencing subpar performance?

Not sure if it's a performance issue or a bug. So why not both?

I'm not able to get _any_ results out of the lifecycle tool. 

I've tried the following views:
- [Users who did (any) pageviews, last 30 days, monthly](https://app.posthog.com/insights?insight=LIFECYCLE&target_entity=%7B%22id%22%3A%22%24pageview%22%2C%22name%22%3A%22%24pageview%22%2C%22type%22%3A%22events%22%7D&returning_entity=%7B%22id%22%3A%22%24pageview%22%2C%22type%22%3A%22events%22%2C%22name%22%3A%22%24pageview%22%7D&period=Day&retention_type=retention_first_time&display=ActionsLineGraph&properties=%5B%5D&filter_test_accounts=true&actions=%5B%5D&events=%5B%7B%22id%22%3A%22%24pageview%22%2C%22name%22%3A%22%24pageview%22%2C%22type%22%3A%22events%22%2C%22order%22%3A0%2C%22math%22%3A%22total%22%7D%5D&shown_as=Lifecycle&compare=false&interval=month&date_from=-30d#fromItem=468122)
- [Users who did (any) pageviews, last 90s days, monthly](https://app.posthog.com/insights?insight=LIFECYCLE&target_entity=%7B%22id%22%3A%22%24pageview%22%2C%22name%22%3A%22%24pageview%22%2C%22type%22%3A%22events%22%7D&returning_entity=%7B%22id%22%3A%22%24pageview%22%2C%22type%22%3A%22events%22%2C%22name%22%3A%22%24pageview%22%7D&period=Day&retention_type=retention_first_time&display=ActionsLineGraph&properties=%5B%5D&filter_test_accounts=true&actions=%5B%5D&events=%5B%7B%22id%22%3A%22%24pageview%22%2C%22name%22%3A%22%24pageview%22%2C%22type%22%3A%22events%22%2C%22order%22%3A0%2C%22math%22%3A%22total%22%7D%5D&shown_as=Lifecycle&compare=false&interval=month&date_from=-90d#fromItem=468122)
- [Users who did (any) pageviews, last 30 days, weekly](https://app.posthog.com/insights?insight=LIFECYCLE&target_entity=%7B%22id%22%3A%22%24pageview%22%2C%22name%22%3A%22%24pageview%22%2C%22type%22%3A%22events%22%7D&returning_entity=%7B%22id%22%3A%22%24pageview%22%2C%22type%22%3A%22events%22%2C%22name%22%3A%22%24pageview%22%7D&period=Day&retention_type=retention_first_time&display=ActionsLineGraph&properties=%5B%5D&filter_test_accounts=true&actions=%5B%5D&events=%5B%7B%22id%22%3A%22%24pageview%22%2C%22name%22%3A%22%24pageview%22%2C%22type%22%3A%22events%22%2C%22order%22%3A0%2C%22math%22%3A%22total%22%7D%5D&shown_as=Lifecycle&compare=false&date_from=-30d&interval=week#fromItem=468122)
- [Users who did Insights Pageview, last 30 days, weekly](https://app.posthog.com/insights?insight=LIFECYCLE&target_entity=%7B%22id%22%3A%22%24pageview%22%2C%22name%22%3A%22%24pageview%22%2C%22type%22%3A%22events%22%7D&returning_entity=%7B%22id%22%3A%22%24pageview%22%2C%22type%22%3A%22events%22%2C%22name%22%3A%22%24pageview%22%7D&period=Day&retention_type=retention_first_time&display=ActionsLineGraph&properties=%5B%5D&filter_test_accounts=true&actions=%5B%7B%22id%22%3A%222426%22%2C%22name%22%3A%22Insights%20Pageview%22%2C%22type%22%3A%22actions%22%2C%22order%22%3A0%2C%22math%22%3A%22total%22%7D%5D&events=%5B%5D&shown_as=Lifecycle&compare=false&date_from=-30d&interval=week&new_entity=%5B%5D#fromItem=468122)
- [Users who Used PostHog, last 14 days, daily](https://app.posthog.com/insights?insight=LIFECYCLE&target_entity=%7B%22id%22%3A%22%24pageview%22%2C%22name%22%3A%22%24pageview%22%2C%22type%22%3A%22events%22%7D&returning_entity=%7B%22id%22%3A%22%24pageview%22%2C%22type%22%3A%22events%22%2C%22name%22%3A%22%24pageview%22%7D&period=Day&retention_type=retention_first_time&display=ActionsLineGraph&properties=%5B%5D&filter_test_accounts=true&actions=%5B%7B%22id%22%3A%222428%22%2C%22name%22%3A%22Used%20PostHog%22%2C%22type%22%3A%22actions%22%2C%22order%22%3A0%2C%22math%22%3A%22total%22%7D%5D&events=%5B%5D&shown_as=Lifecycle&compare=false&new_entity=%5B%5D&interval=day&date_from=-14d#fromItem=468122)
- Many more. 

Sometimes I get a 'Things are looking a little slow' message as it takes a minute to load. Always I end up with a 'We couldn't find any matching events.' message. 

## How to reproduce

1. Run any of the Lifecycle queries above
2. Try a different one
3. Nope, neither work, better file a bug report. 

## Environment

- [x] PostHog Cloud
- [ ] self-hosted PostHog, version/commit: _please provide_

## Additional context

<img width="1200" alt="Screenshot 2021-10-22 at 10 40 36" src="https://user-images.githubusercontent.com/84011561/138432207-6858566c-c309-49be-b70a-e376dd4011b4.png">

**Comment by joethreepwood** [comment]
Probably worth saying that I didn't get any additional errors or performance warnings beyond what is described above. 

When I first load the Lifecycle too, I can still see the initial default view correctly, with data. But anything else? De nada.

**Comment by samwinslow** [comment]
<img width="823" alt="Screen Shot 2021-10-22 at 11 53 30 AM" src="https://user-images.githubusercontent.com/4645779/138485825-a07e31a8-4108-4f62-96ec-3380a77f7750.png">

Additional context: seeing a cancelled request, and then the response to the second request looks like:

```js
{"result":[],"last_refresh":"2021-10-22T15:52:22.474597Z","is_cached":false,"next":null}
```

**Comment by joethreepwood** [comment]
Just had a call with Marcus where he found a temporary solve for this. 

Basically: Disabling 'Filter internal and test users' will enable the Lifecycle tool to work as normal. When it's turned on, I can't get any results out at all.

**Comment by mariusandra** [comment]
Just tested, and this is still happening: with "Filter out internal and test users" enabled, the lifecycle graph returns zero results.

**Comment by mariusandra** [comment]
This seems to work now?

**Comment by joethreepwood** [comment]
Works for me, yeah
