### ISSUE TITLE
Copy to clipboard feature for scripts/docs

### ISSUE THREAD

**Issue by sac0** [PostHog/posthog#661]
**Is your feature request related to a problem? Please describe.**
There is no copy to clipboard feature. This can be used to copy scripts etc.

**Describe the solution you'd like**
I want to contribute this feature. I am able to run posthog locally.
https://ant.design/docs/react/recommendation
Ant Design recommends  in [docs](https://ant.design/docs/react/recommendation)
to use [react-copy-to-clipboard](https://www.npmjs.com/package/react-copy-to-clipboard)

Since this involves a pull request with adding a library. Wanted your approval.

**Describe alternatives you've considered**

<img width="729" alt="Screenshot 2020-04-26 at 03 49 58" src="https://user-images.githubusercontent.com/20946852/80292103-19ac5500-8771-11ea-866b-171263539761.png">

**Additional context**

Also should i add code highlighting to it using or not using a library?
Thank you for reviewing this. I can commit this in a day or two once approved.

***Thank*** you for your feature request - we love each and every one!

**Comment by timgl** [comment]
@sac0 That'd be awesome! We already have some code in `InviteTeam.js` that copies to clipboard, it's only 5 lines of code so might be worth copying that?

For the code highlighting, it might just be worth using something like [hilite.me](http://hilite.me/) to do the highlighting instead of using a library?

**Comment by sacgov** [comment]
Sure, Thanks for the quick reply @timgl . I will do that. Do you think moving it to utils.js makes sense?
In the meantime i'll do it by copying that.

**Comment by EDsCODE** [comment]
#662 Closed this. Thanks!
