### ISSUE TITLE
Supported PostgreSQL version

### ISSUE THREAD

**Issue by guidoiaquinti** [PostHog/posthog#6624]
## Bug description
Similarly to #6570, we don't have a clear PostgreSQL version support. 

* `docker-compose.yml`  uses `postgres:13`
* `docker-compose.e2e.yml`  uses `postgres:alpine` (currently version 14)
* `docker-compose.dev.yml`  uses `postgres:12-alpine`
* CI tests are running with a mix of versions
* PostHog cloud uses `11.13`.
* Helm chart uses `bitnami/postgresql:11.7.0-debian-10-r9`

## Expected behavior
PostHog has a fixed (set of) PostgreSQL version(s).

**Comment by fuziontech** [comment]
Let's settle on `11.13` since that's what Heroku has us running on PostHog Cloud.

**Comment by guidoiaquinti** [comment]
> Let's settle on `11.13` since that's what Heroku has us running on PostHog Cloud.

If we don't consider `docker-compose.yml` a supported setup I agree, otherwise we will try to downgrade a `postgres:13` dataset to a `postgres:11` and this will fail.

**Comment by tiina303** [comment]
Don't we need the docker-compose setup for the 20$/month deployment option?

**Comment by guidoiaquinti** [comment]
> Don't we need the docker-compose setup for the 20$/month deployment option?

Yes but as we don't publicly advertise it yet I think we should still consider it as a non-supported-platform (aka: expect breaking changes like this one)
