### ISSUE TITLE
Use all available whitespace in tooltips

### ISSUE THREAD

**Issue by kpthatsme** [PostHog/posthog#6668]
## Is your feature request related to a problem?

We can show more info on dashboards (such as the property being shown) if we utilize the whitespace better.

## Describe the solution you'd like

Surface the property value when hovering a chart with property breakdowns.

## Additional context
We have a lot of space here, I think we can fit some of the property in here. 
Maybe if the property is too long, we cut it off and have it hoverable to get the entire name.

<img width="379" alt="Screen Shot 2021-10-26 at 12 02 02 PM" src="https://user-images.githubusercontent.com/5965891/138944241-fd2236c7-8e8b-4765-a46b-bd7f7a51ce78.png">

**Comment by clarkus** [comment]
Related concept for a longer term improvement to tooltips - https://github.com/PostHog/posthog/issues/4705#issuecomment-895453452

**Comment by paolodamico** [comment]
Won't be relevant anymore with #7370
