### ISSUE TITLE
Incorrect user count on persons modal

### ISSUE THREAD

**Issue by paolodamico** [PostHog/posthog#6672]
## Bug description

The count on persons modal is wrong. It only shows the pagination limit instead of the actual number of records. This is a backend problem. The common pattern API pattern is to send the total count of objects in the `count` attribute of the response metadata (not the count of objects being sent in the response). 

See example with this recording.

![image](https://user-images.githubusercontent.com/5864173/138973030-21e27b60-f3fc-4a99-b2dd-47e05fd929f6.gif)

## Expected behavior

The total count should reflect the total count of users available, not the users loaded (per pagination). Also worth considering in this scope, could we expand the limit to 1,000 users? Evaluate the performance impact of this.

## How to reproduce

1. Open the person modal at any point that has more than 100 users.

## Environment

- [X] PostHog Cloud
- [X] self-hosted PostHog (ClickHouse-based), version/commit: _please provide_
- [X] self-hosted PostHog (Postgres-based, legacy), version/commit: _please provide_

## Additional context

I would prioritize this during this sprint's effort of improving the overall UX of the app. CC @mariusandra

**Comment by EDsCODE** [comment]
There's an extra element to the problem. We limit the number of edges that are returned to trim all the small edges so it's visualizable but when you query for persons it doesn't account for the edge limiting so the numbers could be unaligned atm

**Comment by paolodamico** [comment]
For the particular case you mentioned @EDsCODE I think it's fine to show a warning that explains the discrepancy if applicable. In any case, the numbers in the person modal should be larger, right?

**Comment by paolodamico** [comment]
This was originally assigned to Core Experience but the scope seems quite related to Core Analytics, @EDsCODE as secondary on call are you okay picking this up?

**Comment by Twixes** [comment]
I believe this is solved now.
