### ISSUE TITLE
Consolidate and reorganize trends logic

### ISSUE THREAD

**Issue by EDsCODE** [PostHog/posthog#668]
**Is your feature request related to a problem? Please describe.**
Trends page is working great functionally. Logic-wise it is starting to become strange to work with because of various spot additions (if/elseing magic strings throughout the components and throughout the backend endpoints)

**Describe the solution you'd like**
Stronger typing and better organization of logic. Reduce magic string usage by defining enums that will organize the state of the components better

**Describe alternatives you've considered**
Leaving it as is

**Additional context**
Just a matter of refactoring which we have to find time at some point to cleanup

***Thank*** you for your feature request - we love each and every one!

**Comment by Twixes** [comment]
Looks like we've improved on this front.
