### ISSUE TITLE
Reduce unnecessary calculations

### ISSUE THREAD

**Issue by EDsCODE** [PostHog/posthog#669]
**Is your feature request related to a problem? Please describe.**
Right now, trends page has several queries that retrieve data which might not be immediately used. For instance, when the table is displayed either for action/event trends or sessions, the time series data is still calculated/has been calculated to determine a total count. This applies when calculating breakdown too.

**Describe the solution you'd like**
Keeping the returned data very explicit. If time series data is needed, retrieve just the time series data. If an aggregate is needed, retrieve just the aggregate. 

**Note that there is an optimization that's working now where the aggregate counts can be determined directly from the time series data, but if we needed to just retrieve the count we shouldn't determine the time series.

**Describe alternatives you've considered**
Keeping the endpoints coupled together like right now. This will be fine for most cases but when the queries become high-load we'll want to keep them as light as possible. Although, there's probably a case to be made for a system deployed for millions of users, a lot of the data should be precomputed/kept up-to-date with background workers/caches and not repeatedly queried anyway.

***Thank*** you for your feature request - we love each and every one!

**Comment by Twixes** [comment]
This is from BC (Before ClickHouse) times, is it still relevant in any way these days?

**Comment by paolodamico** [comment]
I'll assume no but feel free to reopen if something changes.
