### ISSUE TITLE
WIP: Running Clickhouse Posthog in Docker for $5/month instance

### ISSUE THREAD

**Issue by marcushyett-ph** [PostHog/posthog#6691]
# Background

To validate whether or not it would be possible to run a small **Production Ready** ClickHouse instance for $5 / month I'm giving it a go on Digital Ocean (based on our dev docker image)

# Findings

- Insufficient resources to build webpack
    -  Workaround - build locally and copy across the files
- Next step building the docker images... in progress
   - grpcio wheel build getting stuck - upping the machine resources to build and will drop after
   - Okay got everything built and running with a higher spec instance
- Resizing to $5/month again and see how it goes
![image](https://user-images.githubusercontent.com/85295485/139063101-b81d620c-22f7-4cbe-b515-8227103e530b.png) (not exploded yet)
- Kafka was the first thing to die:
```
kafka_1       | [Configuring] 'port' in '/opt/kafka/config/server.properties'
kafka_1       | [Configuring] 'advertised.host.name' in '/opt/kafka/config/server.properties'
kafka_1       | Excluding KAFKA_HOME from broker config
kafka_1       | [Configuring] 'log.dirs' in '/opt/kafka/config/server.properties'
kafka_1       | Excluding KAFKA_VERSION from broker config
kafka_1       | [Configuring] 'zookeeper.connect' in '/opt/kafka/config/server.properties'
kafka_1       | [Configuring] 'broker.id' in '/opt/kafka/config/server.properties'
kafka_1       | OpenJDK 64-Bit Server VM warning: INFO: os::commit_memory(0x00000000c0000000, 1073741824, 0) failed; error='Out of memory' (errno=12)
kafka_1       | #
kafka_1       | # There is insufficient memory for the Java Runtime Environment to continue.
kafka_1       | # Native memory allocation (mmap) failed to map 1073741824 bytes for committing reserved memory.
kafka_1       | # An error report file with more information is saved as:
kafka_1       | # /tmp/hs_err_pid1.log
```
- We need 1GB Ram just for Kafka, so will upgrade the droplet to the next tier: 2GB Memory ($10/month)
- Up and running: 
![image](https://user-images.githubusercontent.com/85295485/139067657-b10dba5f-c9c2-48c3-8260-7cc636cdbadb.png)
- Seems that clickhouse is not working though
```
Include not found: clickhouse_remote_servers
Include not found: clickhouse_compression
Logging trace to /var/log/clickhouse-server/clickhouse-server.log
Logging errors to /var/log/clickhouse-server/clickhouse-server.err.log
```
- From clickhouse server error logs
` <Error> ServerErrorHandler: Code: 101, e.displayText() = DB::NetException: Unexpected packet from client, Stack trace (when copying this message, always include the lines below):

0. DB::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int, bool) @ 0x8b6cbba in /usr/bin/clickhouse
1. DB::TCPHandler::receiveHello() @ 0x10434e3f in /usr/bin/clickhouse
2. DB::TCPHandler::runImpl() @ 0x1042de74 in /usr/bin/clickhouse
3. DB::TCPHandler::run() @ 0x10441839 in /usr/bin/clickhouse
4. Poco::Net::TCPServerConnection::start() @ 0x12a3fd4f in /usr/bin/clickhouse
5. Poco::Net::TCPServerDispatcher::run() @ 0x12a417da in /usr/bin/clickhouse
6. Poco::PooledThread::run() @ 0x12b7ab39 in /usr/bin/clickhouse
7. Poco::ThreadImpl::runnableEntry(void*) @ 0x12b76b2a in /usr/bin/clickhouse
8. start_thread @ 0x9609 in /usr/lib/x86_64-linux-gnu/libpthread-2.31.so
9. __clone @ 0x122293 in /usr/lib/x86_64-linux-gnu/libc-2.31.so
 (version 21.6.5.37 (official build))
`
`<Warning> StorageKafka (kafka_groups): Can't get assignment. It can be caused by some issue with consumer group (not enough partitions?). Will keep trying.`
`2021.10.27 12:55:05.569748 [ 188 ] {} <Error> StorageKafka (kafka_groups): Consumer error: Broker: Unknown topic or partition
2021.10.27 12:55:05.569781 [ 188 ] {} <Error> StorageKafka (kafka_groups): There were 1 messages with an error
2021.10.27 12:55:05.569801 [ 188 ] {} <Error> StorageKafka (kafka_groups): Only errors left
2021.10.27 12:55:05.575894 [ 194 ] {} <Error> StorageKafka (kafka_person): Consumer error: Broker: Coordinator load in progress
2021.10.27 12:55:05.575921 [ 194 ] {} <Error> StorageKafka (kafka_person): There were 1 messages with an error
2021.10.27 12:55:05.575940 [ 194 ] {} <Error> StorageKafka (kafka_person): Only errors left
2021.10.27 12:55:05.601810 [ 163 ] {} <Error> StorageKafka (kafka_events_dead_letter_queue): Consumer error: Broker: Unknown topic or partition
2021.10.27 12:55:05.601863 [ 163 ] {} <Error> StorageKafka (kafka_events_dead_letter_queue): There were 1 messages with an error
2021.10.27 12:55:05.601884 [ 163 ] {} <Error> StorageKafka (kafka_events_dead_letter_queue): Only errors left
2021.10.27 12:55:05.602359 [ 185 ] {} <Error> StorageKafka (kafka_events): Consumer error: Broker: Coordinator load in progress
2021.10.27 12:55:05.602379 [ 185 ] {} <Error> StorageKafka (kafka_events): There were 1 messages with an error
2021.10.27 12:55:05.602396 [ 185 ] {} <Error> StorageKafka (kafka_events): Only errors left
2021.10.27 12:55:05.625743 [ 193 ] {} <Error> StorageKafka (kafka_person_distinct_id): Consumer error: Broker: Coordinator load in progress
2021.10.27 12:55:05.625852 [ 193 ] {} <Error> StorageKafka (kafka_person_distinct_id): There were 1 messages with an error
2021.10.27 12:55:05.625876 [ 193 ] {} <Error> StorageKafka (kafka_person_distinct_id): Only errors left
2021.10.27 12:55:05.725732 [ 197 ] {} <Error> StorageKafka (kafka_session_recording_events): Consumer error: Broker: Unknown topic or partition
2021.10.27 12:55:05.725775 [ 197 ] {} <Error> StorageKafka (kafka_session_recording_events): There were 1 messages with an error
2021.10.27 12:55:05.725803 [ 197 ] {} <Error> StorageKafka (kafka_session_recording_events): Only errors left
2021.10.27 12:55:05.727076 [ 184 ] {} <Error> StorageKafka (kafka_plugin_log_entries): Consumer error: Broker: Unknown topic or partition
2021.10.27 12:55:05.727101 [ 184 ] {} <Error> StorageKafka (kafka_plugin_log_entries): There were 1 messages with an error
2021.10.27 12:55:05.727121 [ 184 ] {} <Error> StorageKafka (kafka_plugin_log_entries): Only errors left`

```
2021.10.27 12:24:15.558150 [ 108 ] {} <Error> TCPHandler: Code: 81, e.displayText() = DB::Exception: Database `posthog` doesn't exist, Stack trace:

0. DB::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int, bool) @ 0x8b6cbba in /usr/bin/clickhouse
1. DB::TCPHandler::runImpl() @ 0x104305e4 in /usr/bin/clickhouse
2. DB::TCPHandler::run() @ 0x10441839 in /usr/bin/clickhouse
3. Poco::Net::TCPServerConnection::start() @ 0x12a3fd4f in /usr/bin/clickhouse
4. Poco::Net::TCPServerDispatcher::run() @ 0x12a417da in /usr/bin/clickhouse
5. Poco::PooledThread::run() @ 0x12b7ab39 in /usr/bin/clickhouse
6. Poco::ThreadImpl::runnableEntry(void*) @ 0x12b76b2a in /usr/bin/clickhouse
7. start_thread @ 0x9609 in /usr/lib/x86_64-linux-gnu/libpthread-2.31.so
8. __clone @ 0x122293 in /usr/lib/x86_64-linux-gnu/libc-2.31.so
```

**Comment by guidoiaquinti** [comment]
> Insufficient resources to build webpack

Can you post the error logs? I think there's a flag to throttle webpack build resources if necessary

**Comment by marcushyett-ph** [comment]
> Can you post the error logs?

It didn't crash or anything - I just left it running for 60mins and it hadn't finished and was using up every drop of resources on the machine - so not sure throttling would help. It's probably also not necessary to test this on this micromachine.

**Comment by marcushyett-ph** [comment]
@guidoiaquinti 1GB memory committed to Kafka feels like it might not be necessary for such a small instance - are there any vars I can change to limit the memory allocated to Kafka?

**Comment by tiina303** [comment]
ClickHouse also recommends 4GB minimum of RAM https://clickhouse.com/docs/en/operations/requirements/

What are the prices if we tried to do docker-compose on Heroku?

**Comment by marcushyett-ph** [comment]
Unfortunately you need to be paying: $500/month to get on a tier with enough RAM (>4GB) for Clickhouse

https://www.heroku.com/pricing

**Comment by marcushyett-ph** [comment]
I saw this on the ClickHouse docs and thought of you @mariusandra 
![image](https://user-images.githubusercontent.com/85295485/139210013-520555b6-1a65-4679-b944-3e707c6390d6.png)

**Comment by mariusandra** [comment]
I take all my branding advice from engineers at intel.

**Comment by marcushyett-ph** [comment]
@tiina303 "The ClickHouse server can run with a much smaller amount of RAM, but it requires memory for processing queries."

I've got it running I appear to have a weird issue with ClickHouse on my $10 instance - which is - the 'posthog' table is somehow missing - otherwise it seems to be okay with resources. I'll start over and see where we get to.

**Comment by marcushyett-ph** [comment]
Seems to be running pretty well with a 4GB ($20/month) droplet on DO.

I'm just load testing it - aiming for roughly 100K events to put it near the top end of what we see today for these small  / hobbyist instances.

One side note - `webpack serve` keeps falling over - but this shouldn't be an issue since will just use the production image for web - in practice.

**Comment by mariusandra** [comment]
Webpack serve takes about 2GB of RAM. To get around it, run `yarn build` and then `python manage.py collectstatic`.

**Comment by marcushyett-ph** [comment]
`yarn build` requires 4GB of ram unfortunately. Can I not just use this prebuilt image instead?

```
web:
        container_name: posthog_web
        image: posthog/posthog:latest
```

**Comment by mariusandra** [comment]
That's an even better approach.

**Comment by tiina303** [comment]
>  which is - the 'posthog' table is somehow missing - otherwise it seems to be okay with resources. I'll start over and see where we get to.

Maybe it gets created, when you send the first event?

**Comment by marcushyett-ph** [comment]
Unfortunately doesn't seem to be the case.

Any ideas @tiina303  @yakkomajuri 

`web_1         | $ posthog-plugin-server
web_1         | [MAIN] 13:36:56 ⚡ @posthog/plugin-server v1.10.5
web_1         | [MAIN] 13:36:56 ℹ️ 8 workers, 10 tasks per worker
web_1         | [MAIN] 13:36:56 💥 Launchpad failure! Error: Database posthog doesn't exist (version 21.6.5.37 (official build))
web_1         |     at parseError (/home/posthog/code/plugins/node_modules/@posthog/clickhouse/src/parse-error.js:2:15)
web_1         |     at errorHandler (/home/posthog/code/plugins/node_modules/@posthog/clickhouse/src/clickhouse.js:27:13)
web_1         |     at IncomingMessage.<anonymous> (/home/posthog/code/plugins/node_modules/@posthog/clickhouse/src/clickhouse.js:95:11)
web_1         |     at IncomingMessage.emit (events.js:412:35)
web_1         |     at IncomingMessage.emit (domain.js:475:12)
web_1         |     at endReadableNT (internal/streams/readable.js:1334:12)
web_1         |     at processTicksAndRejections (internal/process/task_queues.js:82:21) {
web_1         |   code: 81,
web_1         |   scope: 'DB::Exception:'
web_1         | }`

**Comment by marcushyett-ph** [comment]
This error was caused by `python manage.py migrate_clickhouse` not being executed.

Moving discussion to PR:

https://github.com/PostHog/posthog/pull/6783#issuecomment-958114548
