### ISSUE TITLE
Report when the rr-web player has warnings.

### ISSUE THREAD

**Issue by rcmarron** [PostHog/posthog#6704]
## Is your feature request related to a problem?

Right now, we don't know how often the session recording player goes "wonky" (e.g. screen goes white, css is messed up, etc.). If we want to improve this, we should have a way to identify it and measure it.

## Describe the solution you'd like

Right now, rr-web sends warnings to the console when it detects issues in the session recording. We should capture these events and summarize them in a `session recording warning` event.

## Describe alternatives you've considered

Measuring this via other indications of a "bad recording". One considered was adding an auto-incrementing value to each event, and then ensuring that every recording has every expected event in the expected sequence. This has the disadvantage of being a messy query to detect this is occurring, and it does not detect all the issues that rr-web would.

## Additional context

https://github.com/PostHog/posthog/issues/5478

**Comment by rcmarron** [comment]
cc @alexkim205 just making this issue to track this work.

**Comment by pauldambra** [comment]
we do now count and report the count in recording analyzed events
