### ISSUE TITLE
Unify tables and "new" buttons

### ISSUE THREAD

**Issue by mariusandra** [PostHog/posthog#6710]
## Is your feature request related to a problem?

- As part of the [ongoing IA Rework](https://github.com/PostHog/posthog/issues/5346), a quick win we could do is to unify the different table layouts on our various scenes. Most links from the sidebar show a table of some sort, yet there are many competing styles. We should pick one and stick to it.
- Same for the "new something" buttons, filters for the tables, tabs on pages, headings, etc. I think we should clean this up as well.

## Describe the solution you'd like

- Glorious unity

## Describe alternatives you've considered

Keep it like it is:

- Saved insights:
![image](https://user-images.githubusercontent.com/53387/139228925-8f613271-0a88-4de4-9fb3-3a9a2271b708.png)

- Dashboards:
![image](https://user-images.githubusercontent.com/53387/139228984-63f357f4-73d2-4853-a8a0-81b19217295c.png)

- Events:
![image](https://user-images.githubusercontent.com/53387/139229032-d368a552-5e24-4e17-ad8c-24abf57ac634.png)

- Actions
![image](https://user-images.githubusercontent.com/53387/139229062-85e26541-1b2f-4b72-ba83-b0e517dc6520.png)

- Events stats
![image](https://user-images.githubusercontent.com/53387/139229120-0339d70e-c41f-4ef1-afa1-3e9b7aab376f.png)

- Properties stats
![image](https://user-images.githubusercontent.com/53387/139229163-6a768541-aad0-417d-ade4-fec5843cd0a7.png)

- Recordings
![image](https://user-images.githubusercontent.com/53387/139229197-3444c3cf-b22c-40a5-ac4e-7a4ec04fbd7d.png)

- Persons
![image](https://user-images.githubusercontent.com/53387/139229243-bb448665-8a92-4344-ae5f-a0f1378a9996.png)

- Cohorts
![image](https://user-images.githubusercontent.com/53387/139229273-2c2d3fbc-d7c1-4c7e-af23-db95610d69f1.png)

- Annotations
![image](https://user-images.githubusercontent.com/53387/139229416-0b1d4967-a40b-4d63-a8cd-c4c49dfb330c.png)

- Feature flags
![image](https://user-images.githubusercontent.com/53387/139229463-b47a07a7-408d-48ba-b171-77ddea67271b.png)

## Additional context

- **This is not** about redoing the logic behind the resizable tables, but just giving them a unified look.
- Epic: https://github.com/PostHog/posthog/issues/6513

**Comment by clarkus** [comment]
I have an initial draft for this solution at https://www.figma.com/file/gQBj9YnNgD8YW4nBwCVLZf/PostHog-App?node-id=4874%3A28876. 

![data table](https://user-images.githubusercontent.com/254612/139330925-080940d3-c26c-4ee2-9a24-6e896fe24a58.png)

**Comment by paolodamico** [comment]
@Twixes can we close this or is there outstanding work?
