### ISSUE TITLE
Can we add password reveal button in the login page?

### ISSUE THREAD

**Issue by Nishant-Sagar** [PostHog/posthog#6721]
## Is your feature request related to a problem?

Not actually, just little tweaking can do the work

*Please describe.*

I think we need a password reveal (eye) button in the login page as after filling login with wrong credentials it throws the error as "Invalid email or password" so in this case a user might need to see his/her password in order to know whether his password is wrong or he just simply is trying to login with wrong email address.

## Describe the solution you'd like

I don't think anything is there to describe the solution as it is quiet straight forward.

## Additional context
If everything is okay, i'm willing to work on this

**Comment by Nishant-Sagar** [comment]
Can I take this issue?

**Comment by paolodamico** [comment]
Go for it @Nishant-Sagar!
