### ISSUE TITLE
Allow filtering plugin logs by log level

### ISSUE THREAD

**Issue by taobojlen** [PostHog/posthog#6743]
## Is your feature request related to a problem?

For some plugins with particularly verbose logging, it's difficult to find the most important log output.

## Describe the solution you'd like

If you could filter the logs by log level (info/warn/error etc.), it'd be easy to find any potential errors. At the moment they're easy to miss for plugins using e.g. the `Export historical events` job which is very noisy.

## Describe alternatives you've considered

The search bar could also query the log level, that way you could just search for "error" or "warn" or whatever.

## Additional context

Noticed this when testing out https://github.com/PostHog/posthog-plugin-migrator3000.

**Comment by pauldambra** [comment]
@taobojlen this will be available on cloud shortly and self hosted in the next release.

I'll close the issue but feel free to reopen it if this doesn't match your needs
