### ISSUE TITLE
Make subscription success page more on-brand

### ISSUE THREAD

**Issue by yakkomajuri** [PostHog/posthog#6744]
Let's make this spark a bit more joy about me having just subscribed to an awesome platform by being a bit more on brand.

<img width="1438" alt="Screenshot 2021-10-29 at 11 03 59" src="https://user-images.githubusercontent.com/38760734/139424220-47cb3d33-cb34-4ecb-ba86-031d013b1dfe.png">

**Comment by clarkus** [comment]
Put together a quick concept at https://www.figma.com/file/gQBj9YnNgD8YW4nBwCVLZf/PostHog-App?node-id=4938%3A27542 that extends our onboarding / ingestion workflow styles. 

![successt - post billing](https://user-images.githubusercontent.com/254612/139476518-7023c071-453e-4fc3-98e3-b4597ebf8719.png)
