### ISSUE TITLE
AntD component icons slightly misaligned

### ISSUE THREAD

**Issue by EDsCODE** [PostHog/posthog#675]
**Describe the bug**
Many of the accompanying icons within buttons/dropdowns provided by ant design are not aligned correctly

**To Reproduce**
1. Go to setup page and look at the icons within textfields and dropdowns
2. Or, go to trends page and go to apply a custom date range. The calendar icon is misaligned

**Expected behavior**
Should be centered

**Comment by SanketDG** [comment]
I have seen this too, and I am pretty sure this is just a conflict between PostHog's existing CSS and Ant's styling.

The property `vertical-align` on `.anticons` has a value of `-0.125 em`, which is causing this to happen. Setting it to `0` vertically aligns the icon.

This is not replicable on Ant though.
