### ISSUE TITLE
Taxonomic Property Filter pop-up  URL dropdown can be misleading

### ISSUE THREAD

**Issue by pauldambra** [PostHog/posthog#6762]
## Bug description

A customer reported they were trying to setup a filter for "current URL contains checkout" when creating a funnel

Their events page showed events with URLs matching that query

The dropdown for URL did not show those URLs either to scroll to, or when typing into the textbox. But when created the funnel did correctly load data

It is not clear if the URLs available in the drop down are a full set for the selected time range, a full set for all time, or an example of URLs in your events

![propoertyfilter-dropdown](https://user-images.githubusercontent.com/984817/139666801-ecbda7b7-89e9-4146-84cc-0d354c7210e8.gif)

## Expected behavior

When you type into the box it searches the available data and shows matches *or* shows text so that the user knows there is more data than shown

e.g. "3 matches outside this time range" or "change time range to check for more matches"

## How to reproduce

1.  open a new funnel with a short time range
2. search for a URL contains you know exists outside of that time range
3. see that it is not shown in the dropdown of URLs
4. save the filter
5. change the time range to one that includes the data
6. see that you have results in the funnel
7. edit the filter
8. see that the dropdown still does not show the available URLs

## Environment

- [ ] PostHog Cloud
- [ ] self-hosted PostHog (ClickHouse-based), version/commit: _please provide_
- [ ] self-hosted PostHog (Postgres-based, legacy), version/commit: _please provide_

**Comment by pauldambra** [comment]
The endpoint that returns results for this samples the event table in the interest of speed. https://github.com/PostHog/posthog/blob/master/posthog/api/event.py#L262

**Comment by pauldambra** [comment]
The dropdown lets you type in the box (without debouncing) and sends API calls to `https://app.posthog.com/api/event/values/?key=$current_url` before you type and (for example)`ttps://app.posthog.com/api/event/values/?key=$current_url&value=blog` as you type

But it appears that the dropdown doesn't populate with new values

Here is an API call showing 9 results but the dropdown showing only one

<img width="1436" alt="Screenshot 2021-11-15 at 08 08 04" src="https://user-images.githubusercontent.com/984817/141737951-f94594bb-7344-43b6-81b9-c1011ba73550.png">

**Comment by mariusandra** [comment]
Isn't the issue that we only query the last 7 days in these queries?

https://github.com/PostHog/posthog/blob/master/posthog/api/event.py#L257-L258

**Comment by mariusandra** [comment]
That linked query is only run on Postgres. However it's exactly the same thing on ClickHouse: https://github.com/PostHog/posthog/blob/master/ee/clickhouse/models/property.py#L280-L281

**Comment by pauldambra** [comment]
That's _another_ thing that makes the results surprising.

Here overwriting the options in the front end makes the results differently surprising

**Comment by mariusandra** [comment]
@pauldambra is this closed now that https://github.com/PostHog/posthog/pull/7112 is in?

**Comment by pauldambra** [comment]
The specific example searching for blog definitely is 👍
