### ISSUE TITLE
Tech debt? Duplicated `yarn.lock` for plugins

### ISSUE THREAD

**Issue by paolodamico** [PostHog/posthog#6775]
With the migration of the `plugin-server` to this monorepo, we now have a `plugins/package.json` just to load the plugin server, which has it's own `yarn.lock` for dependencies. To avoid duplicated stuff that needs to be maintained separately, plus having to push updates to the plugin server to npm and then updating the repo again with the version bump, is there a way we can load the plugin server directly?

**Comment by yakkomajuri** [comment]
npm will no longer be needed. We'll just run everything directly. See #6784

**Comment by paolodamico** [comment]
With the migration to `plugin-server` can we remove the `plugins` folder now? @yakkomajuri

**Comment by yakkomajuri** [comment]
It was removed!
