### ISSUE TITLE
Proposal - Funnels simple mode

### ISSUE THREAD

**Issue by paolodamico** [PostHog/posthog#6776]
## Proposal
Introduce a simple mode for funnels, and lower prominence of advanced features.

## Context
With all the changes and improvements we did to funnels, we ended up with a product that can be complex to understand for new users, particularly non-technical and/or new to product analytics.

## Approach
Implement the [following proposal](https://www.figma.com/file/gQBj9YnNgD8YW4nBwCVLZf/PostHog-App?node-id=4989%3A28013) (screenshots below, **very much open to feedback**) as an A/B test.

**Simple mode (default)**
![image](https://user-images.githubusercontent.com/5864173/139722381-061d4630-ed7e-4918-be63-2edf77cd45cc.png)

**Advanced mode**
![image](https://user-images.githubusercontent.com/5864173/139722431-d28a3bf1-f786-4057-bdd2-79ddeaffa930.png)

**Simple mode when advanced customization has been applied**
![image](https://user-images.githubusercontent.com/5864173/139722480-f072693b-49de-4cd7-a13c-05eed492fde5.png)

## Goal
Proposed approach should increase Discoveries on funnels (segmenting particularly on new vs. existing users). In addition, we need to make sure only an acceptable drop on usage for advanced features is seen. 

Looking for feedback @marcushyett-ph @kpthatsme @clarkus @mariusandra @Twixes

**Comment by marcushyett-ph** [comment]
Looks good to me - however I wonder if simple mode could be even simpler?

e.g. no breakdowns, no graph type option

Also not sure what happened to "step order" in these mocks - but think it should be considered advanced

**Comment by kpthatsme** [comment]
It looks like this is also a bit of a general re-design? Moving some things into a new "advanced" section?

I like the general attempt at grouping controls together and think it's a positive that probably doesn't need to be tested.

What I don't like as much:
- For funnels, I feel like conversion windows a pretty central concept and not necessarily "advanced" – though I will agree it's not something the user always needs to interact with if we can set smart defaults
- I'm generally not in favor of designs that hide information behind a counter. It's really tedious to look at a chart and need to click into various areas to see the filters applied and advanced settings etc, the friction makes me less inquisitive.

**Comment by clarkus** [comment]
I think it could be fine to place less frequently used items behind advanced options, but I don't think this really solves for the core problem. It'd make it easier for a user to initially focus on the core required fields to build a funnel, but there would be more work to describe and make those features learnable / approachable. I'd like to recommend some component changes if we decide to take this on. I also think the ordering of parameters is a bit off based on the latest changes. 

Is there any supporting user feedback for these changes or is this more based on our own dogfooding of the feature? Just wondering if there's more context to the core problem.

**Comment by paolodamico** [comment]
Sorry seems I missed this discussion, I've put together a PR proposal for this that we can test drive (very open to adjusting it if it makes sense),
- Re @marcushyett-ph, I think the graph type is pretty necessary as at least the conversion over time seems pretty basic. I opted to keep breakdowns on the grounds of consistency with other insights, but open to moving it to advanced too.
- Re @kpthatsme, indeed the proposal is basically moving things to advanced. I agree that conversion window is basic, but I was under the impression that users seldom adjust this. Less than [0.5%](https://app.posthog.com/insights?insight=TRENDS&display=ActionsLineGraph&actions=%5B%5D&events=%5B%7B%22id%22%3A%22insight%20analyzed%22%2C%22name%22%3A%22insight%20analyzed%22%2C%22type%22%3A%22events%22%2C%22order%22%3A0%2C%22properties%22%3A%5B%7B%22key%22%3A%22insight%22%2C%22value%22%3A%5B%22FUNNELS%22%5D%2C%22operator%22%3A%22exact%22%2C%22type%22%3A%22event%22%7D%5D%7D%5D&properties=%5B%5D&filter_test_accounts=true&new_entity=%5B%5D&breakdown=changed_funnel_window_interval&breakdown_type=event&date_from=-90d&interval=month#fromItem=519860&edit=true) of users move the default.
- Re @kpthatsme (2), I've changed the design/implementation so that we remember whether the additional options are open. We also default to opening them when advanced options are applied, plus we make it extra obvious when an advanced option is applied.
- Re @clarkus really keen on hearing that proposal! Indeed we would want advanced features to be learnable in a way that it doesn't become daunting to create your first funnels.

Please share feedback on the implementation too!
