### ISSUE TITLE
[insights] Formula persons are wrong

### ISSUE THREAD

**Issue by EDsCODE** [PostHog/posthog#6797]
## Bug description

*Please describe.*  
- when a formula is applied, clicking on a data point only returns the values for one of the entities used in the formula, not the new total being displayed
*If this affects the front-end, screenshots would be of great help.*  

## Expected behavior
the correct modal of persons should be shown and match the numbers resulting from the formula

## How to reproduce

1. Go to trends
2. apply a formula
3. click on a data point

## Environment

- [x] PostHog Cloud
- [x] self-hosted PostHog (ClickHouse-based), version/commit: _please provide_
- [ ] self-hosted PostHog (Postgres-based, legacy), version/commit: _please provide_

## Additional context
There are no person related tests for formula so this functionality was never guaranteed

**Comment by hazzadous** [comment]
@EDsCODE do you have a link to an example you can provide?
