### ISSUE TITLE
Make session line graph metric readable

### ISSUE THREAD

**Issue by EDsCODE** [PostHog/posthog#680]
**Is your feature request related to a problem? Please describe.**
Session line graph with show seconds for datapoints but this will be hard to read when there's values such as "623 seconds"

**Describe the solution you'd like**
Scale the graph data points to the most readable format

**Additional context**
This is somewhat annoying because if we have datapoints scattered such as some are 5 seconds, some are 5 minutes, the seconds will have to be converted to minutes which will be equally difficult to read (0.08 seconds)

***Thank*** you for your feature request - we love each and every one!

**Comment by Twixes** [comment]
Done.
