### ISSUE TITLE
OpenID Connect support

### ISSUE THREAD

**Issue by tirorex** [PostHog/posthog#6818]
I checked issued

https://github.com/PostHog/posthog/pull/5606
https://github.com/PostHog/posthog/issues/5547

but still have no clear answer. Do you have support for OpenID Connect Identity Providers? Any plans for the future updates?

**Comment by paolodamico** [comment]
Hey @tirorex! We decided to support SAML instead of OIDC for now as it has a wider adoption. We already have this feature available in our Enterprise plan on self-hosted. Let me know if this doesn't solve your issue.
