### ISSUE TITLE
Funnels showing no steps defined in dashboard. Refresh required after click-through to successfully load.

### ISSUE THREAD

**Issue by leggetter** [PostHog/posthog#6828]
## Bug description

A number of funnels were defined and showing within the [Developer Relations dashboard](https://app.posthog.com/dashboard/13064). However, at present, the funnels are showing as having no steps defined within the dashboard. They also show as having no steps defined when you click through. Refreshing the Funnel results in the Funnel showing as expected on the standalone view. Refreshing a Dashboard occasionally fixes the broken view within the dashboard, but not always.

No errors in JS console.

## Expected behavior

Funnels that have been defined to have multiple steps should show the steps and the results.

## How to reproduce

1. Go to https://app.posthog.com/dashboard/13064

https://user-images.githubusercontent.com/328367/140119685-9ce48116-3282-45b1-8ea2-9cf7d14f3766.mp4

## Environment

PostHog Cloud on 3rd Nov at 5pm UK time

**Comment by pauldambra** [comment]
We believe this is fixed by #6900

**Comment by leggetter** [comment]
I can no longer replicate the problem 👍
