### ISSUE TITLE
Ingest events backwards

### ISSUE THREAD

**Issue by mariusandra** [PostHog/posthog#6834]
Whenever we ingest events, we end up with entries in 3 tables: `events`, `persons` and `person_distinct_ids`.

Excluding plugins for now, if we ingest the same events again in the same order, we will (most likely) end up with the same entries in those tables.

However, I think we should also get exactly the same entries in those tables if we ingest events... backwards. If we do, it would make ingestion, retries and exports a lot simpler. For example, we could export multiple months in parallel from one posthog instance to another and know that all persons were transferred as they are.

This task touches two things: 
- Store person property updated_at timestamps... and then compare them before making any changes (in [denormalized properties](https://github.com/PostHog/posthog/issues/4272)?). We need this anyway for $set_once issues, but this could also be added to $set (if a property has been set by an event in the future, don't reset it to something if this event is in the past).
- Store some metadata on when users were merged and use that to prevent past changes from overriding future changes (e.g. somehow prevent renaming the new user to the old user)

The details and feasability of the above points need to be specced out.

**Comment by tiina303** [comment]
https://github.com/PostHog/posthog/issues/7454 Person Created At needs to also handle ingestion in any order

**Comment by marcushyett-ph** [comment]
Curious what the status of this is? Anything I can to do help at all (e.g. manual testing, etc)?

**Comment by tiina303** [comment]
Potentially ... here's how I'm thinking about doing the testing:
I have a DigitalOcean instance already (do-lon1-tiina-testing-2021-11-30-2054 with hostname/user/pass here: https://posthog.slack.com/archives/C01MM7VT7MG/p1638494244381100?thread_ts=1638494082.380800&cid=C01MM7VT7MG).
The plan is: 
1. migrate the old way in-order into a new project from hogflix demo app  - user props data should match hogflix, but wanted to use this as the base to avoid confusion.
1. migrate the old way backwards into a new project (haven't fully figured this out, but thinking of edit/fork migrator plugin) - user props data shouldn't match, verify seeing some differences
1. update the instance to use an image on top of https://github.com/PostHog/posthog/pull/7109 (needs some changes) on top of https://github.com/PostHog/posthog/pull/7472 & set `NEW_PERSON_PROPERTIES_UPDATE_ENABLED_TEAMS` to be all the appropriate project IDs, my network was too bad for image push 🙄 
1. migrate new way in-order into a new project  - user props data should probably match with (1), but could not
1. migrate new way reverse order into a new project  - user props data should probably match with (3)

I suspect we'll see some differences that we'll need to ignore, e.g. maybe geoIP or maybe turning that off before is better.

**Comment by tiina303** [comment]
Relevant recent conversation (tied to person properties updates): https://posthog.slack.com/archives/C0374DA782U/p1660840149534569

We have `properties_last_operation` and `properties_last_updated_at` but they aren't always updated properly. 
Given how our js lib sends browser etc every time we would increase the number of writes to postgres if we updated those fields (specifically timestamp for `properties_last_updated_at`) properly.
