### ISSUE TITLE
Add onAction function

### ISSUE THREAD

**Issue by yakkomajuri** [PostHog/posthog#6835]
We have an `onEvent` function that gives devs read-only access to an event after it's been processed.

We should also introduce `onAction`, so that devs can access actions once there's a match and perform operations from there. This is like a step-up from the current webhooks that can be super powerful. 

Essentially, once we've gotten all the matched actions for a given event, let's trigger `onAction` with maybe both the event and the action name. The function shouldn't return anything.

**Comment by samwinslow** [comment]
I'm happy to work on this as well! It will unblock some marketing automation-focused plugins which currently have less than elegant architectures.

**Comment by tiina303** [comment]
Go for it, I'm unlikely to pick this up in the near future. Happy to help with reviews though Yakko would probably be better at that.

**Comment by yakkomajuri** [comment]
#7232
