### ISSUE TITLE
Plugins lose connectivity on restart

### ISSUE THREAD

**Issue by neilkakkar** [PostHog/posthog#6849]
Plugins connecting out of PostHog in `setup` seem to lose connectivity on restart.

This problem is made less serious thanks to https://github.com/PostHog/plugin-server/issues/516

But even on PostHog Cloud: (specific plugins: Customerio, salesforce, bigquery)
![image](https://user-images.githubusercontent.com/7115141/128151698-be540966-87c5-4a24-abdd-1651d15c7dc7.png)

Lots of plugins doing things in `setup` get disabled.

While it's better now:

![image](https://user-images.githubusercontent.com/7115141/128152430-179fe809-27e8-4315-b650-932d9aaed73f.png)

It's worth looking into why this happens.

**Comment by Twixes** [comment]
I don't think this is a problem now.
