### ISSUE TITLE
Webpack-dev doesn't reload on change

### ISSUE THREAD

**Issue by sacgov** [PostHog/posthog#686]
I improved the config to reload to refresh the browser on frontend change/ webpack build.
@timgl Was the reload left out intentionally or could i raise a request to live reload on build.

Or is there any other thing needed in webpack. I could do my changes accordingly.

**Comment by timgl** [comment]
Please raise a PR! I think we just didn't get to that (cc @mariusandra)

**Comment by mariusandra** [comment]
@sac0 absolutely! This was more of a thing we never got around to. Please raise a PR!

**Comment by sacgov** [comment]
https://github.com/PostHog/posthog/pull/691 - it is raised here.

**Comment by Twixes** [comment]
Autoreload works pretty well now (though we ditched hot component reload due to some issues).
