### ISSUE TITLE
Add "faker" and create "make random events" plugin

### ISSUE THREAD

**Issue by mariusandra** [PostHog/posthog#6869]
This library would be great to have in the list of things you can import: https://github.com/marak/Faker.js/

Then, assuming PostHog/plugin-server#414 is done, we should make a plugin to seed a database with random test events. Just click a button, follow logs, and what a bunch of random events come in.

**Comment by neilkakkar** [comment]
this now exists :) https://github.com/PostHog/make-some-noise-plugin
