### ISSUE TITLE
Integrate with Snowplow

### ISSUE THREAD

**Issue by yakkomajuri** [PostHog/posthog#6873]
Putting here even though it's extensibility, not plugins.

People can use Segment and RudderStack with us but not Snowplow. Given Snowplow is heavily used by data warehouse users, we should reach out and try to get this done. 

They do know who we are:

https://snowplowanalytics.com/blog/2021/01/05/the-top-14-open-source-analytics-tools-in-2021/

**Comment by marcushyett-ph** [comment]
@carabaestlein we have another customer interested in integrating SnowPlow with PostHog - would love to chat about how we can make this happen?

**Comment by rfortmann-ewolff** [comment]
We would also be interested!

**Comment by carabaestlein** [comment]
@marcushyett-ph I am afraid I am no longer at Snowplow but maybe @paulboocock can help?

**Comment by r-4tmann** [comment]
@marcushyett-ph @carabaestlein 
Any news or feedback in this regard ?
PostHog + Snowplow would be great also to visualise historical data.
dbt already has a package to build sessions : https://hub.getdbt.com/dbt-labs/snowplow/latest/
Any chance you might use that as basis for a Snowplow Integration in PostHog ?

**Comment by paulboocock** [comment]
We've been thinking about building a Snowplow -> ssGTM -> Posthog integration as that'd be a quick win from Snowplows side. There's some other tech in the works too, but we're not quite ready to talk about that yet ;-)

If building on top of a warehouse table, I'd recommend using the official Snowplow dbt package - https://hub.getdbt.com/snowplow/snowplow_web/latest/

**Comment by r-4tmann** [comment]
That sounds great for a new setup but I thought more of a connector/adapter for the PostHog UI/Engine based on the historical Snowplow data (in order to present Snowplow data in the PostHog UI).

**Comment by ottman** [comment]
> We've been thinking about building a Snowplow -> ssGTM -> Posthog integration as that'd be a quick win from Snowplows side. There's some other tech in the works too, but we're not quite ready to talk about that yet ;-)
> 
> If building on top of a warehouse table, I'd recommend using the official Snowplow dbt package - https://hub.getdbt.com/snowplow/snowplow_web/latest/

Hey @paulboocock any updates here?
