### ISSUE TITLE
Plugin installation step

### ISSUE THREAD

**Issue by mariusandra** [PostHog/posthog#6875]
Currently plugins are installed from Django. The main posthog app in [`plugin.py`](https://github.com/PostHog/posthog/blob/master/posthog/api/plugin.py). The code there either 1) gets a github repo URL, parses it, fetches a `.zip` file with the plugin code, does basic validation (version check) and stores the archive in postgres, or 2) Opens a source editor and stores its contents in postgres.

In both cases, we won't know if the plugin actually works before we try it out for real.

Instead, I'd like there to be a separate "install plugin" step and "installing..."/"updating..." states. This might mean pushing some of the logic away from Python into NodeJS (e.g. downloading the archives?) and just dispatching tasks from the plugin server, and awaiting their responses.

Eventually we the plugin server would spin up a VM for the "to install" plugin, capture its capabilities, and if all loaded well, mark the plugin as installed and ready to use. I'd argue the VM should be spin up in a separate worker pool (with just one thread) for isolation. Either via piscina or some other system. This could be the basis for plugin testing as well https://github.com/PostHog/plugin-server/issues/165

**Comment by neilkakkar** [comment]
I understand, that was the missing bit: I assumed installation would test that things work before actually enabling things. That clears some things out, thanks!

.. And if there's no extra information to relay back, we don't need an extra tab/section. 

Your initial points make a lot more sense now. Thanks!
