### ISSUE TITLE
Can not go back from event searches

### ISSUE THREAD

**Issue by mariusandra** [PostHog/posthog#688]
**Describe the bug**

Clicking on a path in "all events" and then clicking back doesn't take me back:

![screencast 2020-04-29 22-38-11](https://user-images.githubusercontent.com/53387/80644639-42cb2f00-8a6a-11ea-8f15-9f0891b95b90.gif)

**To Reproduce**
1. Open "All Events"
2. Click on the "Path" for any "$pageview" event to filter by this path
3. Click back

**Expected behavior**
I should be back under "all events", but the filter doesn't change. There are related issues when just adding other filters and changing the url after. The back button behaves weird.

**Desktop:**
 - OS: macOS
 - Browser: Chrome
 - Version:  N - 1

**Additional context**
Possibly connected to #687 and the "additional context" I wrote there

**Comment by timgl** [comment]
(I think you've linked the wrong PR there)

**Comment by mariusandra** [comment]
(Thanks, edited and fixed from 678 to 687)
