### ISSUE TITLE
Data loss with kafka producer during network issues

### ISSUE THREAD

**Issue by mariusandra** [PostHog/posthog#6885]
Documenting / rubber ducking below.

We sometimes have cases when the plugin server just stops and needs to be restarted:

<img width="964" alt="Screenshot 2021-04-29 at 10 52 55" src="https://user-images.githubusercontent.com/53387/116525777-2827d200-a8d9-11eb-867e-ae9395e37f9d.png">

We have a script that automatically detects these cases and throws [errors like these](https://sentry.io/organizations/posthog/issues/2366305734/?project=5592816&query=is%3Aunresolved). I'm going to implement an auto-restart feature because I don't like being paged. But that won't solve the root cause.

The logs leading up to the crash basically tell of network issues and our inability to recover from them:

![image](https://user-images.githubusercontent.com/53387/116526066-7b9a2000-a8d9-11eb-9bb1-b49ac3470628.png)

Now, while I could and will increase the retry timeouts in the producer (I already did, but reverted when debugging the big slowdown from a few days ago), there's a complex system that's running out of control here with potential for data loss.

It's best explained with a diagram:

![image](https://user-images.githubusercontent.com/53387/116530793-b6528700-a8de-11eb-9e12-335700058026.png)

This has the potential for data loss, so it should be treated with some urgency :).

**Comment by Twixes** [comment]
I'll close this since I suppose the Platform team is now in charge of this
