### ISSUE TITLE
I want to create actions for specific $screen events

### ISSUE THREAD

**Issue by mariusandra** [PostHog/posthog#689]
**Is your feature request related to a problem? Please describe.**
I have $screen events for when users open screens in my mobile app:

![image](https://user-images.githubusercontent.com/53387/80644936-c08f3a80-8a6a-11ea-9c0f-3d0789327fe6.png)

**Describe the solution you'd like**
I'd like to create an action "Opened screen PostHog Sample". When I select the "$screen" event, I can't search for the screen itself:

![image](https://user-images.githubusercontent.com/53387/80645139-021fe580-8a6b-11ea-858b-eef7c749300c.png)

Right now the only property I can filter when creating actions is $pageview -> $current_url:

![screencast 2020-04-29 22-45-31](https://user-images.githubusercontent.com/53387/80645293-3398b100-8a6b-11ea-9eac-20fee2117121.gif)

**Describe alternatives you've considered**
Not creating an action or submitting a custom event when opening

**Additional context**
There could be other properties I'd like to create actions with in the future.

***Thank*** you for your feature request - we love each and every one!

**Comment by Twixes** [comment]
Not relevant for a long time, since actions can have filters applied.
