### ISSUE TITLE
[insight—persons] reshape insight result payloads to promote clear person endpoints

### ISSUE THREAD

**Issue by EDsCODE** [PostHog/posthog#6935]
## Is your feature request related to a problem?

*Please describe.*
Many issues could be prevented if there was a clear indication of how to retrieve persons given the data. Some examples in recent history
- https://github.com/PostHog/posthog/pull/6830 (persons shouldve been turned off for formulas)
- https://github.com/PostHog/posthog/issues/6796 (compare persons was returning random default persons)
- https://github.com/PostHog/posthog/issues/6804 (wrong date parameters for total aggregate on trends)

Overall,
- person endpoint usage isn't clear because they usually require extra parameters that the original insight was missing so all the parameters are parsed and the URL is rebuilt which is prone to errors
- backend queries to guarantee a match between numbers and persons are often overlooked because the current pattern doesn't encourage coupling of persons to insight numbers
- frontend has specific handling for gathering and parsing the parameters to call a person endpoint
- Not always clear if person endpoint is available for a specific insight

## Describe the solution you'd like

When retrieving result data from an endpoint, also return all the necessary links to retrieve people associated with a data point, property grouping, etc. Similar to how we prebuild pagination endpoints, we can prebuild the endpoints for retrieving persons since everything can be predetermined. This pattern will resolve the points above and simplify much of the frontend handling to retrieve persons related to an insight result payload. 

## Describe alternatives you've considered
- continue the current pattern with more aggressive testing and typing

## Additional context

The issue we're trying to tackle is inconsistency between the aggregate numbers we're providing to the user and the drill down breakdown of these numbers. To be completely consistent we could return this drill down detail along with aggregate numbers, but these can be large numbers with large breakdowns. Do we care about returning all the people? Probably not, so we could possibly get away with returning a subset with the values. However, we probably further want to allow exploring the people associated with an aggregation, so let's say we go with a separate request to retrieve specific people for an aggregation.

In its simplest for we can provide a url within the response that can be used to make a GET people request. This will just leave handling auth and other responsibilities to the calling code. We should consider that this is to be used within browser so we should consider the constraint e.g. of browser url length and restrictions that may be in place on the server side.

Considering we are already storing the majority of the same GET params we'd be using to power our current navigation state and linking, I'm making the assumption that we'll also be fine on url length, although we should check that this assumption is valid.

Considering we are going to be increasing the size of the initial aggregation request, we will be adding a not inconsiderable in size url to each aggregate number we're returning. However, we are only talking about say 20 points so I'm assuming this will not cause problems, although again worth checking. At any rate the risk shouldn't be high, we can optimise response size if needed.

If we need to optimise we can for instance rather than returning the url, rather return a partial filter object such that we're only returning the additional filtering that is required to be applied in conjunction with the "base" filtering to retrieve the people/events.

**Comment by hazzadous** [comment]
Some tasks I'm working through pairing with @macobo 

1. Define what we need to return in the event correlation endpoint to simplify as much as possible that interaction the client needs to handle to retrieve persons
2. Add additional response parts to correlation endpoint
3. Add get support to persons endpoint such that we can pull data from the query string instead of the request body
4.0. Add feature flag for new persons functionality for the frontend 
4.1. Update the frontend correlations table to check for the existence of the persons url for success and failure cases for each correlated event

**Comment by hazzadous** [comment]
Places we're using persons:

1. trends
   2. breakdown
   3. no breakdown
   4. other combinations
2. funnels
3. sessions
4. lifecycle
5. paths
6. retention
7. stickiness

**Comment by Twixes** [comment]
I believe we're going to stab at this in the form of https://github.com/PostHog/meta/pull/66.
