### ISSUE TITLE
Session recording does not capture elements inside data-viz library.

### ISSUE THREAD

**Issue by michaeltroya** [PostHog/posthog#6953]
## Bug description

Currently using a data-viz library called ReGraph(https://cambridge-intelligence.com/regraph/) to render a graph. 
After setting up PostHog and turning on session recording I can see everything but the graph rendered inside a <canvas> by ReGraph.

## Expected behavior

Entire page including ReGraph elements to be captured. 

## How to reproduce

1. Render ReGraph component.
2. View session recording. 
3. Graph elements inside <canvas> will be empty.

## Environment

- [x] PostHog Cloud
- [ ] self-hosted PostHog (ClickHouse-based), version/commit: _please provide_
- [ ] self-hosted PostHog (Postgres-based, legacy), version/commit: _please provide_

## Additional context

ReGraph is a private library.

**Comment by macobo** [comment]
Looking at the library, it is using webgl or canvas under the hood. Closing as a duplicate of https://github.com/PostHog/posthog/issues/2798 (let's track this under there!)

cc @rcmarron
