### ISSUE TITLE
Help utility menu out of place in new designs

### ISSUE THREAD

**Issue by clarkus** [PostHog/posthog#6954]
## Bug description

The help utility menu is using a different placement than other items in the component. 

<img width="410" alt="Screen Shot 2021-11-08 at 9 08 12 AM" src="https://user-images.githubusercontent.com/254612/140787478-7f5c4848-1f9e-45ae-9bbd-e4585f57673b.png">

## Expected behavior

All items in the component should use the same vertical offset and alignement. 

## How to reproduce

1. Log into cloud using chrome
2. Toggle on the new UI
3. Observe the icon placement

## Environment

- [x] PostHog Cloud

**Comment by paolodamico** [comment]
This was me sorry, issues with merge conflicts, will fix in a bit.
