### ISSUE TITLE
Insight tabs do not extend to the full width of the content area

### ISSUE THREAD

**Issue by clarkus** [PostHog/posthog#6964]
## Bug description

The tabs are only wide enough to contain the available options. The intended behavior is for the tabs to take up the full width of the content area. In this example the tab bar should be the same width as the subsequent content. 

<img width="1303" alt="Screen Shot 2021-11-08 at 2 01 06 PM" src="https://user-images.githubusercontent.com/254612/140825261-7a0a49d5-11d7-4e47-82e1-3d730918a7c9.png">

## Environment

- [x] PostHog Cloud

**Comment by mariusandra** [comment]
These tabs have another issue if the screen is less wide than the content:

![image](https://user-images.githubusercontent.com/53387/140891795-f6db7b82-6225-4c78-9a48-f1fd32eaca24.png)
