### ISSUE TITLE
Unnecessary hover state in table?

### ISSUE THREAD

**Issue by corywatilo** [PostHog/posthog#6970]
Been loving using lemonade! 😍 

### Hovering a cell in the table shows the cursor pointer, but clicking on it doesn't do anything.

I had minor heart palpitations trying to highlight and copy some text to my clipboard and hoping it wouldn't trigger a click. (Fortunately in my case it didn't end up doing anything, heh.)

tl;dr: Don't use row hover state and cursor pointer if I can't click it? ;) 

![image](https://user-images.githubusercontent.com/154479/140839320-aec7d3f8-cc7c-42f5-bc8c-a2b76867bfd4.png)

**Comment by Twixes** [comment]
We're working on making all the tables nicer (see https://github.com/PostHog/posthog/pull/7103#issuecomment-973996445) so I'll definitely take this into account. Thanks!
