### ISSUE TITLE
Create `/health` endpoint for Plugin Server

### ISSUE THREAD

**Issue by fuziontech** [PostHog/posthog#7003]
We recently had an [outage on Plugin Server](https://github.com/PostHog/status/issues/18) that could have been mitigated if we had a `/health` endpoint that would have prevented the service from going live considering it was failing to start.

The `/health` endpoint should check for a few things:
1) That the service is ready to start consuming events from Kafka
2) Is able to produce to Kafka
3) That the service is _not_ started with `DEV` environment variable set to true
4) Scheduling lock (redlock) is not deadlocked?
5) More? TBD - This list is probably a solid enough of a start.

**Comment by tiina303** [comment]
Another example issue: https://github.com/PostHog/posthog/issues/7064

**Comment by fuziontech** [comment]
https://github.com/PostHog/posthog/pull/7146 <- Add endpoint for health check

Next up will be adding better health checking for plugin server health and dependency status
