### ISSUE TITLE
1 click Docker-compose version of PostHog on Digital Ocean for $20/month or less

### ISSUE THREAD

**Issue by fuziontech** [PostHog/posthog#7004]
Pretty self explanatory but we should have a stack available that people can test PostHog with that costs $20/month or less.

**Comment by fuziontech** [comment]
Ok have a really nice, straightforward way for people to install PostHog stack on things to test.

Point users to our magic curl [here](https://github.com/PostHog/deployment)
```bash
/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/posthog/deployment/HEAD/compose/deploy.sh)"
```

We could also have this on https://github.com/posthog/posthog readme as well.

Candidate locations are basically anywhere an Ubuntu VM can run. Tested on these:
| location | type | $ / month|
|---------|-----|-----|
|DigitalOcean Droplet  | basic 2cpu 4gb mem | $20|
|AWS EC2 instance |  i3a.medium | $27 |
|GCP VM | e2-medium | $26 |

Stack boots in a reasonable amount of time, provides feedback, and is parametrizable. The stack also emits an event on attempted start of it.

Go ahead and give it a try on a new VM somewhere. You'll want to have a DNS record pointing to the exposed IP. We can make this run locally on a node without TLS.

**Comment by tiina303** [comment]
This is awesome 🙌 

Do we want to call out it's possible with the 10$ instance on DO, how bad was it (I suspect it will only get worse as we collectively write more code)?

How would upgrades work (& how would migrations run or upgrades) & related to this should we pin a PostHog app version?

If you `docker-compose down` do you lose all the data? Should we use external volumes (which the script could create beforehand)?

Could you update these docs (I'm sure you were planning to already, just helping out with a list):
- [ ] posthog readme
- [ ] docs dropdown (replace source?)
- [ ] https://posthog.com/docs/self-host  
- [ ] separate doc for it under self-host (potentially the content from https://github.com/PostHog/deployment should live in posthog.com for the same reasons as we moved all the other docs + there's some other enhancements that might come to posthog.com we'll not be getting on plain github readmes)
- [ ] https://posthog.com/docs/self-host/deploy/hosting-costs (is that the full cost here, do we still need to pay for the ip being able to be exposed or ingress/egress / ... you listed the compute cost only atm it seems)

**Comment by tiina303** [comment]
Mind answering my questions above?
Did you already update docs, I didn't see any PRs yet?
