### ISSUE TITLE
Bug: Plugin Icon Missing Pub/Sub

### ISSUE THREAD

**Issue by joethreepwood** [PostHog/posthog#7012]
## Bug description

Missing an icon for one of the plugins. Pub/Sub. I couldn't see this in the Posthog.com repo, so assuming it's on this repo. 

<img width="1471" alt="Screenshot 2021-11-10 at 10 06 23" src="https://user-images.githubusercontent.com/84011561/141093716-75a1fefb-0544-419c-961e-b5854650cf06.png">

<img width="698" alt="Screenshot 2021-11-10 at 10 09 47" src="https://user-images.githubusercontent.com/84011561/141093761-07425f29-23ae-40f4-ac9e-df5a2764a41d.png">

## Expected behavior

Image included.

## How to reproduce

Goto plugin library, browse. 

## Environment

- [ ] PostHog Cloud
- [ ] self-hosted PostHog (ClickHouse-based), version/commit: _please provide_
- [ ] self-hosted PostHog (Postgres-based, legacy), version/commit: _please provide_

**Comment by pauldambra** [comment]
The issue here is that [the code looks for the logo on the `main` branch](https://github.com/PostHog/posthog/blob/master/frontend/src/scenes/plugins/plugin/PluginImage.tsx#L22) but this plugin is in Vendasta's organization and uses the `master` branch

https://raw.githubusercontent.com/vendasta/pubsub-plugin/master/logo.png

**Comment by neilkakkar** [comment]
We should fork-and-control it, so vendasta still owns it, but we control updates to cloud

**Comment by pauldambra** [comment]
![Screenshot 2022-08-24 at 13 28 37](https://user-images.githubusercontent.com/984817/186418541-fed634dd-559a-4f60-a796-c07d03ae1661.png)

This is now at https://github.com/PostHog/pubsub-plugin and the logo shows correctly in app.posthog.com

and at https://posthog.com/apps

![Screenshot 2022-08-24 at 13 31 33](https://user-images.githubusercontent.com/984817/186418975-7074fee4-6903-48e3-b852-f6509d8dc84d.png)

**Comment by joethreepwood** [comment]
Some missed link updates here: https://github.com/PostHog/posthog.com/pull/4058
