### ISSUE TITLE
`/api/event.csv` default settings are making pods OOMing

### ISSUE THREAD

**Issue by guidoiaquinti** [PostHog/posthog#7015]
## Bug description

With #1580 we introduced a new API endpoint in order to export events in CSV format. #3503 increased the default result size to 100k events, while with #5959 we reduced it to 10k because of performance issues.

We are unfortunately still getting reports from our customer that this is still a problem (HTTP 500 due to pod OOMing).

* short-term solution (aka quick and dirty fix): limit the result size of this endpoint to something tiny (50/100?) so that it does not return an error, breaking the user experience

* make sure memory usage and result size are not scaling linearly (can we make some optimisation in the serialisation library? should we make smaller parallel requests, batch them together and return them to the client?)  

## Expected behavior

Exporting events as CSV always work.

## How to reproduce

1. call `/api/event.csv?limit=10000000000`

**Comment by mariusandra** [comment]
A true solution is async backend exports that send a mail when they're done. We'll be forever adjusting this limit otherwise :).

I guess lower the `limit` to what still works, and we'll build a better export system whenever someone asks for it.

**Comment by guidoiaquinti** [comment]
> A true solution is async backend exports that send a mail when they’re done. We’ll be forever adjusting this limit otherwise :).

Yes and no: if we decide to split this call into smaller serialised subcalls (each taking a fixed amount of memory, buffering the results to disk), we could probably still make this work in a _synchronous world_ (note: I think the problem we will hit after that is when the sum of all of those calls will take >= max request timeout in the web server/worker or anything else downstream, but that’s another story 😁)

I like the idea of implementing something async, but in our current setup this will also add quite a lot of overhead. If we don’t send the CSV as attachment (and we shouldn’t) we will need to provide a _stable_ download link. Where are we going to store the CSV generated file so that we can fetch it async? ClickHouse, PostgreSQL or Redis are not valid answers 😛
