### ISSUE TITLE
how to change project API key

### ISSUE THREAD

**Issue by Doflatango** [PostHog/posthog#7027]
It is possible to change the project API key to a old one manually?

**Comment by Twixes** [comment]
We only allow self-serve **random** reset for data integrity/security purposes (reusing a key that used to belong to someone else could have adverse consequences), but we can help out and make a manual change on PostHog Cloud if needed, while on self-hosted this can be done a PostHog deployment administrator.

**Comment by Doflatango** [comment]
> We only allow self-serve **random** reset for data integrity/security purposes (reusing a key that used to belong to someone else could have adverse consequences), but we can help out and make a manual change on PostHog Cloud if needed, while on self-hosted this can be done a PostHog deployment administrator.

@Twixes Thanks for your reply!
I'm using a self-hosted Posthog, i have administrator permissions, please tell me what should i do.

**Comment by Twixes** [comment]
You need to connect to your Postgres database backing PostHog and update the relevant `posthog_team` row's `api_token` value (`posthog_team` = projects, `api_token` = project API key) with a query like this:
```SQL
UPDATE posthog_team SET api_token = $NEW_API_KEY WHERE name = $PROJECT_NAME
```

**Comment by Doflatango** [comment]
> You need to connect to your Postgres database backing PostHog and update the relevant `posthog_team` row's `api_token` value (`posthog_team` = projects, `api_token` = project API key) with a query like this:
> 
> ```sql
> UPDATE posthog_team SET api_token = $NEW_API_KEY WHERE name = $PROJECT_NAME
> ```

@Twixes Thank you!
