### ISSUE TITLE
Discrepancies between person property correlation numbers and people drill down lists

### ISSUE THREAD

**Issue by hazzadous** [PostHog/posthog#7036]
## Bug description

When looking at [this](https://app.posthog.com/insights?insight=FUNNELS&date_from=2021-11-02&date_to=2021-11-09&actions=%5B%5D&events=%5B%7B%22id%22%3A%22%24pageview%22%2C%22name%22%3A%22%24pageview%22%2C%22type%22%3A%22events%22%2C%22order%22%3A0%7D%2C%7B%22id%22%3A%22%24pageview%22%2C%22type%22%3A%22events%22%2C%22order%22%3A1%2C%22name%22%3A%22%24pageview%22%7D%5D&display=FunnelViz&interval=day&properties=%5B%5D&funnel_viz_type=steps&exclusions=%5B%5D&funnel_from_step=0&funnel_to_step=1#fromItem=502307&edit=true&personModal=%7B%22action%22%3A%7B%22id%22%3A%22viewed%20dashboard%22%2C%22type%22%3A%22events%22%7D%2C%22label%22%3A%22viewed%20dashboard%22%2C%22date_from%22%3A%22%22%2C%22date_to%22%3A%22%22%2C%22filters%22%3A%7B%22insight%22%3A%22FUNNELS%22%2C%22date_from%22%3A%222021-11-02%22%2C%22date_to%22%3A%222021-11-09%22%2C%22actions%22%3A%5B%5D%2C%22events%22%3A%5B%7B%22id%22%3A%22%24pageview%22%2C%22name%22%3A%22%24pageview%22%2C%22type%22%3A%22events%22%2C%22order%22%3A0%7D%2C%7B%22id%22%3A%22%24pageview%22%2C%22type%22%3A%22events%22%2C%22order%22%3A1%2C%22name%22%3A%22%24pageview%22%7D%5D%2C%22display%22%3A%22FunnelViz%22%2C%22interval%22%3A%22day%22%2C%22properties%22%3A%5B%5D%2C%22funnel_viz_type%22%3A%22steps%22%2C%22exclusions%22%3A%5B%5D%2C%22funnel_correlation_person_entity%22%3A%7B%22id%22%3A%22viewed%20dashboard%22%2C%22type%22%3A%22events%22%7D%2C%22funnel_correlation_person_converted%22%3A%22true%22%2C%22funnel_from_step%22%3A0%2C%22funnel_to_step%22%3A1%7D%7D) funnel, specifically at the correlations, most of the time the aggregate numbers match what it returned from the people endpoint. But not always, specifically I have noticed that sometime people property correlation numbers do not match the people list on drill down.

Example discrepancies:

For $initial_current_url we are always(?) returning no people. ~~I suspect this is due to $initial_current_url being a materialize column, although I'm yet to pin that idea down~~. That may be a red herring as [this appears to be the clause](https://github.com/PostHog/posthog/blob/cd1055560790419b9aa5e3c2c2b02bf70bcaee79/ee/clickhouse/queries/funnels/base.py#L511:L511) that is resulting in the person misses

Looking further into this issue, I suspect that it is an issue specifically with funnel people property correlations on high cardinality fields. There are some assumptions in the code around retrieval of the top N breakdown values, replacing the remaining values with "Other".  As a solution I would suggest that we move to using the same correlation query we're using to generate the aggregate values, to ensure that we have parity. All we're doing for the correlations is aggregating person_ids. This should be a simple task to instead return these person ids instead.

## Expected behavior

People aggregates should match actual people list size

## How to reproduce

Go to above link and click on correlation people drill down for $initial_current_url

## Environment

- [x] PostHog Cloud
- [x] self-hosted PostHog (ClickHouse-based), version/commit: _please provide_
- [ ] self-hosted PostHog (Postgres-based, legacy), version/commit: _please provide_

**Comment by hazzadous** [comment]
cc @neilkakkar

**Comment by neilkakkar** [comment]
Ahh, good catch! This makes sense
