### ISSUE TITLE
Add e2e tests for capturing

### ISSUE THREAD

**Issue by timgl** [PostHog/posthog#705]
**Is your feature request related to a problem? Please describe.**
See [post-mortem](https://github.com/PostHog/post-mortem/blob/master/2020-04-30%20captured%20event%20sent_at%20timezone%20issue.md), we didn't catch some issues in this critical part of our app partly due to not having a full e2e test.

**Describe the solution you'd like**
E2E test that tests calling the API all the way to storing the event.

**Describe alternatives you've considered**

**Additional context**

***Thank*** you for your feature request - we love each and every one!

**Comment by Twixes** [comment]
We now have something on this level. [Slack thread](https://posthog.slack.com/archives/C01MM7VT7MG/p1642003640143400)
