### ISSUE TITLE
Funnel persons drill down does not consider ordering

### ISSUE THREAD

**Issue by hazzadous** [PostHog/posthog#7058]
## Bug description

Whilst implementing [person urls](https://github.com/PostHog/posthog/issues/6935) for the funnels endpoint, I noticed that the funnel persons endpoint appears to not consider the order strictness parameter.  You can see this on [this funnel](https://app.posthog.com/insights?insight=FUNNELS&date_from=2021-11-09&date_to=2021-11-09&actions=%5B%7B%22id%22%3A%2212007%22%2C%22type%22%3A%22actions%22%2C%22order%22%3A1%2C%22name%22%3A%22Demo%20----%20Get%20started%20click%22%7D%5D&events=%5B%7B%22id%22%3A%22clicked_announcement%22%2C%22name%22%3A%22clicked_announcement%22%2C%22type%22%3A%22events%22%2C%22order%22%3A0%7D%5D&display=FunnelViz&interval=day&properties=%5B%5D&funnel_viz_type=steps&funnel_order_type=unordered&exclusions=%5B%5D&funnel_from_step=0&funnel_to_step=1#fromItem=504142&edit=true) where we have 50 people complete, but clicking through we have 0.

Note that I picked this up as a result of [this test case](https://github.com/PostHog/posthog/pull/7057/files#diff-ec9b9a41b3f39dada13bb3c935acbec8bc4954420530f8f567e5da90d0e19533R242)

Note this also affects the strict ordering setting

## Expected behavior

I'm unsure about what the correct behaviour is here tbh, but the numbers I would at least expect to match.

## How to reproduce

1. Create an unordered funnel, with counts < 100
2. click through on any non-zero count

## Environment

- [x] PostHog Cloud
- [x] self-hosted PostHog (ClickHouse-based), version/commit: _please provide_
- [ ] self-hosted PostHog (Postgres-based, legacy), version/commit: _please provide_

**Comment by hazzadous** [comment]
cc @EDsCODE @neilkakkar

**Comment by neilkakkar** [comment]
Nice catch! Looks like we never updated this: https://github.com/PostHog/posthog/blob/master/ee/clickhouse/views/person.py#L68

to look like: https://github.com/PostHog/posthog/blob/master/ee/clickhouse/views/insights.py#L96
