### ISSUE TITLE
Plugin server: Fail loudly if kafka topics are missing

### ISSUE THREAD

**Issue by macobo** [PostHog/posthog#7064]
## Is your feature request related to a problem?

In https://github.com/PostHog/posthog/pull/6462, I introduced a new kafka topic to be used in ingestion, but did not manually create the topic until later. Messages in between were dropped.

## Describe the solution you'd like

Loud errors from plugin server when topics are missing.

## Additional context

cc @tiina303 and @yakkomajuri as this is plugins/metrics related :)

**Comment by guidoiaquinti** [comment]
This is semi-related to the `/health` endpoint discussion we had in the team meeting yesterday. For all our services we need to make sure all the downstream dependencies are met before returning an HTTP 200.

**Comment by yakkomajuri** [comment]
This is _bad_, and I need to dig in to understand what the hell is up

**Comment by yakkomajuri** [comment]
Also shouldn't swallow these errors
