### ISSUE TITLE
Group Analytics - first impressions and feedback

### ISSUE THREAD

**Issue by clarkus** [PostHog/posthog#7073]
I gave our fledgling group analytics features a trial run a bit ago. This is a super exciting change to our product! I think it's looking great and I only found a few things I'd like to surface as questions / discussion topics. Most of these are existing issues that are just exacerbated by additional aggregation options. 

1. The aggregation methods available generally make sense, but the use of `unique instances` caused me to pause a bit. It wasn't immediately obvious to me what an instance was referring to in this context. We have some related work to do here to [clarify aggregation methods](https://github.com/PostHog/posthog/issues/6254), so this really isn't an issue specific to group analytics.
2. Are y'all tracking improvements to person modals and other click-through actions that cross-link insights? For example, in trends I typically can click on a data point to see all persons in that data point. There are parallels for groups, but we might still be in a scenario where we need some interstitial step to describe a data point. 
3. Does aggregating by groups preclude us from using any other insight options long-term? For example, if I am aggregating by group, does that limit my ability to compare time ranges or any other adjacent functionality?
4. I think there are ongoing PRs out there for this, but the metrics are tagging incorrectly in the chart tooltip. Both unique instances and unique groups are tagged as `unique_group`. Related to the aggregation methods I mentioned above, we should clean up our chart tooltips to scale a bit better with these new aggregation methods. There are some ideas in a related issue at https://github.com/PostHog/posthog/issues/4705#issuecomment-889344301 that would improve our ability to describe these items in each context. 
<img width="221" alt="Screen Shot 2021-11-11 at 9 07 53 AM" src="https://user-images.githubusercontent.com/254612/141339653-d2930414-d171-4c2d-942e-052064966e75.png">

cc @macobo @liyiy

**Comment by macobo** [comment]
5. Sharing one extra piece of feedback from Michael:

> For me this doesn't seem obvious if it just says "$GROUP_TYPE". How bout "$GROUP_TYPE properties" like other tabs?

![image](https://user-images.githubusercontent.com/148820/141462824-43937fe4-c6d5-4bf8-a31b-81914d808a49.png)

**Comment by macobo** [comment]
Thanks for the feedback. I've numbered each one and responding.

> 1. The aggregation methods available generally make sense, but the use of unique instances caused me to pause a bit. It wasn't immediately obvious to me what an instance was referring to in this context. We have some related work to do here to clarify aggregation methods, so this really isn't an issue specific to group analytics.

In our case `instance` is a group type we send from the backend representing a site or instance of posthog that's been set up. :)

Agreed regarding cleaning up aggregation methods. I'm not really happy how it's represented in funnels, I think this needs some design-level thinking:
![image](https://user-images.githubusercontent.com/148820/141463028-187d1879-9923-4aa0-b478-81c184fce6eb.png)

> 2. Are y'all tracking improvements to person modals and other click-through actions that cross-link insights? For example, in trends I typically can click on a data point to see all persons in that data point. There are parallels for groups, but we might still be in a scenario where we need some interstitial step to describe a data point.

Person modals indeed don't currently work and it's logged [in the board](https://github.com/orgs/PostHog/projects/19/views/1).

However I don't think a "person" modal when aggregating by groups even makes sense - instead showing (and linking) groups would make more sense here. So there's both technical and design work here on how these should look!

> 3. Does aggregating by groups preclude us from using any other insight options long-term? For example, if I am aggregating by group, does that limit my ability to compare time ranges or any other adjacent functionality?

I don't think so. The one exception being perhaps linking insights to paths (or other user-only based insights).

Paths are inherently user-based so linking from say a funnel to it doesn't really make sense.

> 4. I think there are ongoing PRs out there for this, but the metrics are tagging incorrectly in the chart tooltip. Both unique instances and unique groups are tagged as unique_group. Related to the aggregation methods I mentioned above, we should clean up our chart tooltips to scale a bit better with these new aggregation methods. There are some ideas in a related issue at Compare previous functionality is confusing #4705 (comment) that would improve our ability to describe these items in each context.

The tooltips were in review when you wrote the feedback, but are now fixed at least wording-wise. 

![image](https://user-images.githubusercontent.com/148820/141463545-3a02a0a8-efc4-41cf-a235-db5cccc1a58c.png)

However the larger problem here is that not all UI handles different wordings gracefully. E.g. funnels:

![image](https://user-images.githubusercontent.com/148820/141463642-166622a5-eb11-4911-b202-089f02648a8c.png)

We should figure out what these issues are and I think it's :+1: to systematically solve these under this project.

Related: Should we use custom icons for groups? If so, what mechanism should that live by?

> 5. For me this doesn't seem obvious if it just says "$GROUP_TYPE". How bout "$GROUP_TYPE properties" like other tabs?

There's a problem here in that the dropdown for selecting properties is quite narrow and you need to scroll to see all tabs with groups. @clarkus penny for your thoughts. 

Some options:
1. Increase the width
2. Remove "properties" from every tab name
... or something else here design-wise?

**Comment by clarkus** [comment]
> There's a problem here in that the dropdown for selecting properties is quite narrow and you need to scroll to see all tabs with groups. @clarkus penny for your thoughts.

I think we might consider a consolidated list of options grouped by their type. When we have a sufficiently high volume of sections, we'll be more reliant on search to find the target option. We can help focus attention to specific sections by making sections collapsible. This might be less optimal in projects where groups aren't instrumented or where there is a low volume of group entities. I need to put time into fixing these scale issues in a few other places, so I will put something together for this as well. Note that this feels very related to https://github.com/PostHog/posthog/issues/6254.
