### ISSUE TITLE
Toolbar launch page

### ISSUE THREAD

**Issue by paolodamico** [PostHog/posthog#7084]
Discussion started somewhere by @mariusandra. Proposal for what to do about the Toolbar menu item so it feels more in line with the rest of the app behavior.

When you click on the "Toolbar" menu item in the sidebar you are taken to this page where you can easily manage authorized domains/URLs and launch the toolbar.

We also add a secondary icon to the sidebar that automatically opens the toolbar in the first authorized URL/domain.

<img width="1280" alt="image" src="https://user-images.githubusercontent.com/5864173/141393079-94ea82df-cf3e-4756-a91b-4ff2b02f9041.png">

Original [Figma design](https://www.figma.com/file/gQBj9YnNgD8YW4nBwCVLZf/PostHog-App?node-id=5212%3A28639)

Thoughts @mariusandra @clarkus @Twixes ?

**Comment by clarkus** [comment]
Nailed it. Looks great and makes total sense to me. One thing to clarify would be the inline actions available for each domain / url. Assuming it's just edit and remove, but I could see other actions there, too. Not a blocker, just something to clarify. Nice job!
