### ISSUE TITLE
Correlation analysis property dropdown does not handle long property names well

### ISSUE THREAD

**Issue by macobo** [PostHog/posthog#7086]
## Bug description

![image](https://user-images.githubusercontent.com/148820/141428553-8b90763a-0f70-440d-9c8f-86d34285482d.png)

## Expected behavior

Better handling

## How to reproduce

1. Open correlation analysis
2. Open properties dropdown w/ a long property name

## Environment

- [x] PostHog Cloud
- [ ] self-hosted PostHog (ClickHouse-based), version/commit: _please provide_
- [ ] self-hosted PostHog (Postgres-based, legacy), version/commit: _please provide_

## Additional context

cc @clarkus @neilkakkar

**Comment by clarkus** [comment]
We could increase the width of the menu (upper bound of 320px) or we could truncate values and fully describe them on hover with a tooltip. I'd be more in favor of increasing the container width to fully show the character values, but we're going to see scenarios were truncation might be a better option. These also look like strings that won't wrap naturally, so we might force line wraps for longer values if truncation isn't an option.
