### ISSUE TITLE
Some paths don't work

### ISSUE THREAD

**Issue by mariusandra** [PostHog/posthog#7089]
## Bug description

- Opening [this path](https://app.posthog.com/insights?insight=PATHS&properties=%5B%5D&step_limit=5&include_event_types=%5B%22%24pageview%22%2C%22custom_event%22%5D&path_groupings=%5B%5D&exclude_events=%5B%5D&funnel_filter=%7B%22events%22%3A%5B%7B%22id%22%3A%22plugin%20enabled%22%2C%22math%22%3Anull%2C%22name%22%3A%22plugin%20enabled%22%2C%22type%22%3A%22events%22%2C%22order%22%3A2%2C%22properties%22%3A%5B%5D%2C%22custom_name%22%3Anull%2C%22math_property%22%3Anull%7D%5D%2C%22actions%22%3A%5B%7B%22id%22%3A136%2C%22math%22%3Anull%2C%22name%22%3A%22User%20Logged%20In%22%2C%22type%22%3A%22actions%22%2C%22order%22%3A0%2C%22properties%22%3A%5B%5D%2C%22custom_name%22%3Anull%2C%22math_property%22%3Anull%7D%2C%7B%22id%22%3A6222%2C%22math%22%3Anull%2C%22name%22%3A%22User%20viewed%20plugins%20page%22%2C%22type%22%3A%22actions%22%2C%22order%22%3A1%2C%22properties%22%3A%5B%5D%2C%22custom_name%22%3Anull%2C%22math_property%22%3Anull%7D%5D%2C%22display%22%3A%22FunnelViz%22%2C%22insight%22%3A%22FUNNELS%22%2C%22interval%22%3A%22day%22%2C%22exclusions%22%3A%5B%5D%2C%22properties%22%3A%5B%7B%22key%22%3A%22realm%22%2C%22type%22%3A%22person%22%2C%22value%22%3A%5B%22cloud%22%5D%2C%22operator%22%3A%22exact%22%7D%5D%2C%22funnel_step%22%3A-2%2C%22funnel_to_step%22%3A2%2C%22funnel_viz_type%22%3A%22steps%22%2C%22funnel_from_step%22%3A0%2C%22filter_test_accounts%22%3Atrue%7D&funnel_paths=funnel_path_after_step&local_path_cleaning_filters=%5B%5D#fromItem=145665&fromItemName=Cloud%20funnel&fromDashboard=1865) from the saved insights page (new window or not, doesn't matter), leads to an error
- [This path](https://app.posthog.com/insights?insight=PATHS&step_limit=5&funnel_filter=%7B%7D&exclude_events=%5B%5D&path_groupings=%5B%5D&include_event_types=%5B%22%24pageview%22%5D#fromItem=456956&fromItemName=p1&fromDashboard=9965) works though

## Expected behavior

The path should open and not do this

![image](https://user-images.githubusercontent.com/53387/141435768-1117323c-a968-407a-bacc-b48023fcb870.png)

## How to reproduce

1.
2.
3.

## Environment

- [ ] PostHog Cloud
- [ ] self-hosted PostHog (ClickHouse-based), version/commit: _please provide_
- [ ] self-hosted PostHog (Postgres-based, legacy), version/commit: _please provide_

**Comment by neilkakkar** [comment]
Associated Sentry error: https://sentry.io/organizations/posthog/issues/2761122888/?project=1899813&query=is%3Aunresolved+insights%2Fpath&statsPeriod=14d
