### ISSUE TITLE
Lemonade sidebar different open/closed states depending on resolution

### ISSUE THREAD

**Issue by mariusandra** [PostHog/posthog#7091]
## Is your feature request related to a problem?

If I have the sidebar open, and make my screen smaller, the menu appears weirdly.

![2021-11-12 10 22 15](https://user-images.githubusercontent.com/53387/141443136-5443e6f3-084b-4ac8-a6f5-3a3ea89712e4.gif)

The opposite happens if I reload and make the screen bigger:

![2021-11-12 10 23 02](https://user-images.githubusercontent.com/53387/141443275-83c874c4-a138-4a6a-9c44-6b04224655a2.gif)

## Describe the solution you'd like

I think we should have two separate open/closed states for the sidebar, for the two different layouts.

## Describe alternatives you've considered

Closing the sidebar manually each time I resize my window.

**Comment by Twixes** [comment]
The menu appears as intended, however I see the problem in that the menu should probably just autohide when going into mobile screen size territory (since at a small size the sidebar necessarily needs to be laid out very differently).

**Comment by mariusandra** [comment]
As intended, but not as expected. I'm fine with either explicitly hiding it when the screen goes below a certain resolution, or, having two separate open/closed states for the different resolutions, as that makes it easier to get things just right (e.g. persist the state for desktop, always keep mobile closed initially, etc).
