### ISSUE TITLE
"Person" modal for group analytics

### ISSUE THREAD

**Issue by macobo** [PostHog/posthog#7096]
## Is your feature request related to a problem?

In https://github.com/PostHog/posthog/pull/7022 we disabled person modals when aggregating by groups. (Example: Show me $pageviews by unique organizations)

It would be worthwhile to bring this feature back though.

## Describe the solution you'd like

Rather than showing "people" I think it makes more sense to instead have a separate "groups" modal, showing all groups that were involved and linking to their profile pages.

Open questions:
- [ ] Should we still link to recordings from it? 
- [ ] What exactly to display in it
- [ ] Should we make it possible to get at the list of people?

## Describe alternatives you've considered

Disabling the modal.

## Additional context

cc @EDsCODE @liyiy @clarkus @paolodamico  Penny for your thoughts

This might also be an opportunity to:
1. Finish backend refactors to do with person modals 
2. Refresh design of the modals if we're interested in that

**Comment by clarkus** [comment]
I put together a quick idea for a groups modal at https://www.figma.com/file/gQBj9YnNgD8YW4nBwCVLZf/PostHog-App?node-id=5376%3A33913

**Comment by macobo** [comment]
@EDsCODE since you're leaving for the week - mind documenting the current state of this and what's to do?

**Comment by EDsCODE** [comment]
Updates:

- trend and funnels #7298 #7144 #7194 
- paths actors api #7437 
- retention actors api #7495 
- funnel correlation API #7456 

TODO:

- expose frontend for (funnel correlation, retention)
- Insight cohorting for all insights using actor pattern
     - should be able to extend `insert_cohort_from_query`/`INSERT_COHORT_ALL_PEOPLE_THROUGH_PERSON_ID`
- Download CSV for all insights using actor pattern

**Comment by macobo** [comment]
To add to that: Person modal FE code needs a rethink as all loading states, empty states and buttons refer to persons, not the group type. Solving the empty state is also tricky because it relies on the first person being returned.

**Comment by macobo** [comment]
Another area which needs investigating: The following funnel when clicking on the bars shows persons, not organizations:

https://app.posthog.com/insights/YaNmxUGc/edit?insight=FUNNELS&date_from=-14d&actions=%5B%7B%22id%22%3A4912%2C%22math%22%3Anull%2C%22name%22%3A%22Discover%20Learning%20-%20core%20analytics%22%2C%22type%22%3A%22actions%22%2C%22order%22%3A1%2C%22properties%22%3A%5B%5D%2C%22custom_name%22%3Anull%2C%22math_property%22%3Anull%7D%5D&events=%5B%7B%22id%22%3A%22user%20signed%20up%22%2C%22math%22%3Anull%2C%22name%22%3A%22user%20signed%20up%22%2C%22type%22%3A%22events%22%2C%22order%22%3A0%2C%22properties%22%3A%5B%5D%2C%22custom_name%22%3A%22User%20signed%20up%22%2C%22math_property%22%3Anull%7D%5D&display=FunnelViz&interval=day&properties=%5B%5D&filter_test_accounts=true&funnel_to_step=1&funnel_viz_type=steps&exclusions=%5B%5D&aggregation_group_type_index=0&funnel_from_step=0

Also also, the tooltip needs updating:
![image](https://user-images.githubusercontent.com/148820/144882080-262cc868-3339-4f4e-bde1-74f7303ba96b.png)

Edit: One more issue:

https://app.posthog.com/insights/YaNmxUGc/edit?insight=FUNNELS&date_from=-14d&actions=%5B%7B%22id%22%3A4912%2C%22math%22%3Anull%2C%22name%22%3A%22Discover%20Learning%20-%20core%20analytics%22%2C%22type%22%3A%22actions%22%2C%22order%22%3A1%2C%22properties%22%3A%5B%5D%2C%22custom_name%22%3Anull%2C%22math_property%22%3Anull%7D%5D&events=%5B%7B%22id%22%3A%22user%20signed%20up%22%2C%22math%22%3Anull%2C%22name%22%3A%22user%20signed%20up%22%2C%22type%22%3A%22events%22%2C%22order%22%3A0%2C%22properties%22%3A%5B%5D%2C%22custom_name%22%3A%22User%20signed%20up%22%2C%22math_property%22%3Anull%7D%5D&display=FunnelViz&interval=day&properties=%5B%5D&filter_test_accounts=true&funnel_to_step=1&funnel_viz_type=trends&exclusions=%5B%5D&aggregation_group_type_index=0&funnel_from_step=0#personModal=%7B%22action%22%3A%7B%22id%22%3A8%2C%22name%22%3A%2230-Nov-2021%22%2C%22properties%22%3A%5B%5D%2C%22type%22%3A%22actions%22%7D%2C%22label%22%3A%22Persons%20converted%20on%2030-Nov-2021%22%2C%22date_from%22%3A%222021-11-30%22%2C%22date_to%22%3A%222021-11-30%22%2C%22filters%22%3A%7B%22insight%22%3A%22FUNNELS%22%2C%22date_from%22%3A%22-14d%22%2C%22actions%22%3A%5B%7B%22id%22%3A4912%2C%22math%22%3Anull%2C%22name%22%3A%22Discover%20Learning%20-%20core%20analytics%22%2C%22type%22%3A%22actions%22%2C%22order%22%3A1%2C%22properties%22%3A%5B%5D%2C%22custom_name%22%3Anull%2C%22math_property%22%3Anull%7D%5D%2C%22events%22%3A%5B%7B%22id%22%3A%22user%20signed%20up%22%2C%22math%22%3Anull%2C%22name%22%3A%22user%20signed%20up%22%2C%22type%22%3A%22events%22%2C%22order%22%3A0%2C%22properties%22%3A%5B%5D%2C%22custom_name%22%3A%22User%20signed%20up%22%2C%22math_property%22%3Anull%7D%5D%2C%22display%22%3A%22FunnelViz%22%2C%22interval%22%3A%22day%22%2C%22properties%22%3A%5B%5D%2C%22filter_test_accounts%22%3Atrue%2C%22funnel_to_step%22%3A1%2C%22funnel_viz_type%22%3A%22trends%22%2C%22exclusions%22%3A%5B%5D%2C%22aggregation_group_type_index%22%3A0%2C%22funnel_from_step%22%3A0%7D%2C%22saveOriginal%22%3Atrue%2C%22pointValue%22%3A33.33%7D

![image](https://user-images.githubusercontent.com/148820/144887791-bf58ed3c-c898-4c8d-8d57-ebd29f3e28a1.png)

Missing:
- Title is off
- 6 unique WHO?
- 33.33 total times?

----

Notes from todays session, potential duplicates:
- [x]  On funnels, shows x “users” in modal even when another group is used
- [x] Button says “Load more people”
- [ ] “100 unique organizations” when clicking on a data point. Should be 100+?
- [x] Says loading persons when loading
- [x] Tooltip copy when hovering in trends is wrong - says "show persons" even if aggregating by groups

**Comment by EDsCODE** [comment]
- funnel correlation should have right copy too now

**Comment by macobo** [comment]
@EDsCODE can this be closed now?
