### ISSUE TITLE
Trends graph type selector shows as "Steps" when changing from Funnels

### ISSUE THREAD

**Issue by joesaunderson** [PostHog/posthog#7118]
## Bug description

This is a small UI bug. When you go from funnels to trends, the "chart type" dropdown still shows steps.

## Expected behavior

The "chart type" dropdown shows "Linear"

## How to reproduce

1. Insights
2. New insight -> Funnels (in dropdown)
3. Change to trends
4. Shows as "Steps" in the graph header:
![image](https://user-images.githubusercontent.com/11272509/141787042-c5daebb7-e4a4-4ab6-9d09-1c1dab7554f5.png)

## Environment

- [x] PostHog Cloud
- [ ] self-hosted PostHog (ClickHouse-based), version/commit: _please provide_
- [x] self-hosted PostHog (Postgres-based, legacy), version/commit: e0fe499a0544a9a6ba914efcb1e58ed1fe1e3422

**Comment by macobo** [comment]
Also present on current master/on cloud.
