### ISSUE TITLE
Edit dashboard items

### ISSUE THREAD

**Issue by timgl** [PostHog/posthog#712]
**Is your feature request related to a problem? Please describe.**
At the moment you can only delete a dashboard item (unless it's a funnel). I want to be able to edit it

**Describe the solution you'd like**
When linking to /trends from a dashboard item, it should pass dashboarditem_id and visually show that somewhere on the trends page. Then when editing filters you should be able to save that against the dashboard item.

**Describe alternatives you've considered**
Deleting and re-creating

**Additional context**
I also think this could tie in to some kind of history, where we store each iteration of changes to /trends, then we store one of those iterations against dashboard item. However, I think that will probably be too complicated/not necessary for now

**Comment by mariusandra** [comment]
This is already fixed and in master.
