### ISSUE TITLE
Changing dashboard item name and hitting back shows old insight name

### ISSUE THREAD

**Issue by macobo** [PostHog/posthog#7122]
## Bug description

https://user-images.githubusercontent.com/148820/141799514-a4e4b86c-4664-4468-ab70-1270ed597864.mp4

## Expected behavior

Item name changes

## How to reproduce

1. Add an item to dashboard
2. Click on item
3. Change name
4. Hit back
5. See old name on dashboard

## Environment

- [x] PostHog Cloud
- [ ] self-hosted PostHog (ClickHouse-based), version/commit: _please provide_
- [ ] self-hosted PostHog (Postgres-based, legacy), version/commit: _please provide_

## Additional context

cc @mariusandra

**Comment by Twixes** [comment]
Was fixed by #7161.
