### ISSUE TITLE
"Add graph" from dashboard does not work properly

### ISSUE THREAD

**Issue by macobo** [PostHog/posthog#7123]
## Bug description

There's the following button on dashboards:

![image](https://user-images.githubusercontent.com/148820/141800051-558bd1d5-a8e3-4a64-a33d-332194f7a3f3.png)

After hitting it you see a screen similar to below:

![image](https://user-images.githubusercontent.com/148820/141800147-51dd4e5c-20ac-4dee-9125-ac2030d4ebd2.png)

Clicking save and going back to the dashboard does not display the just-edited insight, even after a refresh.

## Expected behavior

Item is added to dashboard

## How to reproduce

1. Go to a dashboard
2. Hit add graph
3. Save insight
4. Go back

## Environment

- [x] PostHog Cloud
- [ ] self-hosted PostHog (ClickHouse-based), version/commit: _please provide_
- [ ] self-hosted PostHog (Postgres-based, legacy), version/commit: _please provide_

## Additional context

cc @mariusandra for prioritization

**Comment by Twixes** [comment]
The button is now accurately named "New insight". This closes the issue, though surely isn't the smoothest UX – that I'll sort out with an actual "Add insight" flow as part of #7517.
