### ISSUE TITLE
Hubspot plugin isn't working

### ISSUE THREAD

**Issue by oneshot-engineering** [PostHog/posthog#7128]
## Bug description
Posthog identify events aren't being created as Hubspot contacts anymore

TypeError: Cannot read property 'split' of undefined
    at onEvent (vm.js:25:52)
    at __inBindMeta__PluginConfig_1240_db74f44efc0bb5975136234f00ddf263 (vm.js:33:141)
    at __innerAsyncGuard__PluginConfig_1240_db74f44efc0bb5975136234f00ddf263 (vm.js:23:141)
    at Object.base.apply (/code/plugin-server/node_modules/vm2/lib/contextify.js:246:34)
    at /code/plugin-server/dist/worker/plugins/run.js:18:23
    at async Promise.all (index 0)
    at async runOnEvent (/code/plugin-server/dist/worker/plugins/run.js:13:5)
    at async /code/plugin-server/dist/worker/worker.js:49:49
    at async /code/plugin-server/node_modules/@posthog/piscina/dist/src/worker.js:149:26

*Please describe.*  
*If this affects the front-end, screenshots would be of great help.*  

## Expected behavior
Identify events should create as Hubspot contacts

## How to reproduce

1. I am using cloud version of Posthog and had configured Hubspot plugin long back and it stopped working from Nov 10th
2.
3.

## Environment

- [ Y] PostHog Cloud
- [ ] self-hosted PostHog (ClickHouse-based), version/commit: _please provide_
- [ ] self-hosted PostHog (Postgres-based, legacy), version/commit: _please provide_

**Comment by yakkomajuri** [comment]
Hey! I've pushed a fix and updated the plugin on Cloud: https://github.com/PostHog/hubspot-plugin/commit/416c19ab4dab407c4c24f1487fe1cbd985325957

See if it works now!

cc @kpthatsme

**Comment by oneshot-engineering** [comment]
@yakkomajuri  - Although i don't see errors in the Posthog plugin console now but i don't think it is creating contacts in Hubspot. 

Can you confirm if the posthog identify events are indeed creating contacts in Hubspot?

**Comment by kpthatsme** [comment]
@oneshot-engineering can you take take look at your config screen in the plugin? 

You may need to manually add the `$identify` event in the config.

**Comment by oneshot-engineering** [comment]
Yup. It started working now after configuring $identify.

Oh nice, i didn't notice you guys pushed some enhancements to plugin like
to map custom posthog person properties to hubspot properties. I was
looking for that feature. Good addition.

Just a small feedback to send out product updates email so we know whats
new coming out.

**Comment by kpthatsme** [comment]
Yup @oneshot-engineering, sorry about that! Should have made sure this was backwards compatible - I'll add in $identify as a default.

We did add a ton of more functionality including support for multiple custom event triggers as well as custom property mappings, hope it's useful :)
