### ISSUE TITLE
So many $identify events are being created for the same user

### ISSUE THREAD

**Issue by oneshot-engineering** [PostHog/posthog#7138]
## Bug [description]
I am seeing so many identify events for the same user.
*Please describe.*  
<img width="380" alt="Screen Shot 2021-11-15 at 9 54 53 AM" src="https://user-images.githubusercontent.com/64449719/141831061-2713c769-0d26-4d7f-ab65-69215cdaff57.png">

*If this affects the front-end, screenshots would be of great help.*  

This is affecting hubspot integration of creating contacts. I am seeing so many errors in the plugin due to this.

## Expected behavior
If the same user is identified already and may be Posthog client SDK don't trigger identify events 

## How to reproduce

1. Just call this method in the client side on page load "posthog.identify". Every time the user reloads the page, it will yield so many identify events in the posthog

## Environment

- [ ] PostHog Cloud
- [ ] self-hosted PostHog (ClickHouse-based), version/commit: _please provide_
- [ ] self-hosted PostHog (Postgres-based, legacy), version/commit: _please provide_

**Comment by mariusandra** [comment]
Hi @oneshot-engineering , the identify event is sent every time you call `posthog.identify`, which will then happen on each reload. However you should see just one event, not a lot of them, unless you call the function multiple times.

**Comment by Berhart** [comment]
Hi @mariusandra
It would still be nice during the same session, which should be persisted between reloads, only one `identify` event would actually be sent to the server. Is there a way to do something like: `if (!posthog.isUserIdentified) { posthog.identify(...) }` ?  Maybe this logic could even be part of the `identify` API itself

Thanks in advance
