### ISSUE TITLE
Epic: Feature Flags

### ISSUE THREAD

**Issue by clarkus** [PostHog/posthog#7143]
## Is your feature request related to a problem?

Several ongoing and upcoming projects are going to affect the feature flags feature. We can still implement these changes as the timing makes sense, but we should design a cohesive solution that aligns the problems identified. Note that the scope of this is subject to change based on feedback around feature flags and outstanding problems. 

- Group analytics - updates needed to find and select groups for composing release conditions
- Experimentation - experimentation is very much an additional layer of control for release conditions within feature flags
- Navigation & IA updates - feature flags uses a page hierarchy that diverges a bit from our other features. This would be a good opportunity to clean this up to align with other features.

## Describe the solution you'd like

A cohesive design for feature flags that balances group analytics, experimentation, the recent IA changes, table improvements, etc. 

## Describe alternatives you've considered

Doing this ad-hoc and then coming back to clean things up in the future. 

## Additional context

TBD

**Comment by paolodamico** [comment]
This makes a lot of sense, we should have better context on what we're doing with Experimentation this week or next week at the latest. I also think we may want to scope this only to Core Analytics Team to avoid any cross dependencies, and as they're probably going to be the ones working on Experimentation (plus groups already).

**Comment by clarkus** [comment]
Related https://github.com/PostHog/posthog/issues/7394 - @macobo I know you're going to be touching this area of the product for group analytics, so might be a quick win to represent more code types here.
