### ISSUE TITLE
Insight charts render with wrong data when changing chart type.

### ISSUE THREAD

**Issue by mariusandra** [PostHog/posthog#7153]
## Is your feature request related to a problem?

When changing the chart's type, we briefly render the new chart with the old data. This causes problems if the data is actually incompatible, as seen here:

![2021-11-16 10 43 30](https://user-images.githubusercontent.com/53387/141961449-46067b9f-3df4-443b-a420-54ff921ab9cc.gif)

## Describe the solution you'd like

Clear the results when swapping the chart.

## Describe alternatives you've considered

Don't swap out the chart type before the data loads. I'm not sure if this is better, but we can try. I fear this might feel laggy though, and we might still change the elemets around the graph that will be showing the old type of data, so... not sure.

**Comment by Twixes** [comment]
Fixed by #7429.
