### ISSUE TITLE
Fix or replace dayjs

### ISSUE THREAD

**Issue by mariusandra** [PostHog/posthog#7155]
## Bug description

We periodically get errors, at least in development (which should be just unminified production), that `.utc` is not a function. This comes from code like 

```ts
// in sessionRecordingLogic.ts
return {
    person_id: sessionPlayerData.person.id,
    after: dayjs.utc(sessionPlayerData.session_recording.start_time).subtract(buffer_ms, 'ms').format(),
    before: dayjs.utc(sessionPlayerData.session_recording.end_time).add(buffer_ms, 'ms').format(),
    orderBy: ['timestamp'],
}
```

The problem is `utc` is a plugin that's added to dayjs via such a system:

```ts
// AT THE TOP of sessionRecordingLogic.ts
import utc from 'dayjs/plugin/utc'
dayjs.extend(utc)
```

With esbuild's chunking, we can never be sure if an imported global is there at the time or if it's still undefined. Mutating imported objects via side-effects via the method above is really non-deterministic, and should be removed.

I'm sure this happens in production as well, for some people, somewhere, some of the time.

## What we should do instead

Let's replace `dayjs` with `moment`. We won't be getting rid of it any time soon anyway (it's a dependency for antd), so whatever.

**Comment by macobo** [comment]
:+1: 

cc @paolodamico who was working on the timezone support which I think motivated using this library? https://github.com/PostHog/posthog/pull/3698

**Comment by paolodamico** [comment]
IIRC we fully got rid of `moment` in production. I believe there was a way to replace the Ant dep with `dayjs` too (@timgl may have better context here). Not sure if this would solve it (https://day.js.org/docs/en/parse/string), where adding the `Z` is used to indicate the timezone. It does look however we'll need to load `dayjs` plugins, perhaps there's a way to load them globally at runtime?

**Comment by timgl** [comment]
We did get rid of it entirely but had to use [antd-dayjs-webpack-plugin](https://www.npmjs.com/package/antd-dayjs-webpack-plugin) to do it. It is a fairly substantial saving in bundle size so not sure how easy it would be to do this using esbuild?

**Comment by mariusandra** [comment]
- There are five different plugins we inject to dayjs in various files
  - dayjs.extend(relativeTime)
  - dayjs.extend(isSameOrAfter)
  - dayjs.extend(isSameOrBefore)
  - dayjs.extend(LocalizedFormat)
  - dayjs.extend(utc)

- One solution that can work is if we have our own, `frontend/scenes/dayjs.ts` file, which makes sure to only `export` one properly configured `dayjs` export, with all the plugins attached.

**Comment by paolodamico** [comment]
I can make a PR for that
