### ISSUE TITLE
Persons tab retains static cohort list

### ISSUE THREAD

**Issue by joesaunderson** [PostHog/posthog#7157]
## Bug description

We use a static cohort to define beta users, if I click into this cohort, then go to the persons tab, the persons tab will only show users from that static cohort (even if I search).

## Expected behavior

The persons tab shows all persons, and I can search for users outside the static cohort.

## How to reproduce

1. Create a static cohort
2. View the static cohort matched users
3. Click the persons tab
4. Only users in the static cohort are shown, even when you search

## Environment

- [x] PostHog Cloud
- [ ] self-hosted PostHog (ClickHouse-based), version/commit: _please provide_
- [x] self-hosted PostHog (Postgres-based, legacy), version/commit: e0fe499a0544a9a6ba914efcb1e58ed1fe1e3422

## Additional context

This caused confusion for users searching for users and they thought PostHog was broken and questioned the integrity of our data.

**Comment by mariusandra** [comment]
Thanks for reporting @joesaunderson - This is now fixed.
