### ISSUE TITLE
Make GeoIP native functionality

### ISSUE THREAD

**Issue by yakkomajuri** [PostHog/posthog#7169]
Currently the way the plugin server architecture is setup is such that each team creates a new "instance of a plugin" (called a plugin config). We then make a VM per config in each of the worker threads.

This makes sense for a _ton_ of reasons. However, it also means we load 2000+ GeoIP VMs per thread on Cloud. 

Thus, we should probably make this core functionality. 

There's a discussion to be had in the future about architecture and if we can reasonably determine that a single config can handle multiple teams at once (if the plugin doesn't accept any configuration for example), but for now I think it's worth cutting down on the resources used by the biggest offender - GeoIP - and bake its functionality in natively.

**Comment by yakkomajuri** [comment]
cc @fuziontech @mariusandra @Twixes

**Comment by Twixes** [comment]
What's the cost of the current state of things? The ingestion service takes very little resources compared to the ClickHouse or Postgres, so I wouldn't have thought this kind of refactor would be worth it.

**Comment by yakkomajuri** [comment]
It's not about resources as much as it is about startup time (more like "time until ready to start ingestion"). We need to load all these VMs in the worker and when an event comes through and needs to be piped through GeoIP's `processEvent`, we need to wait until the VM is ready to do so.

**Comment by yakkomajuri** [comment]
And conceptually, if we have something that we default to on for everyone, we might as well make it native.

**Comment by Twixes** [comment]
Interesting. What's the proportion of MMDB load time (the MaxMind database needs to be downloaded, unpacked, parsed) to VM load time (as VMs initiate only after the MMDB layer is ready)?

**Comment by yakkomajuri** [comment]
We don't have great metrics here (would be nice to!), but this was just something that we started thinking about over a quick debugging session. It's not a pressing issue but even if things were to be fine right now, they will just logically get worse as we get more and more signups, so this would make sense as it shouldn't come with any downsides to users?

**Comment by Twixes** [comment]
Looking at the logs, I agree. The MMDB server is ready within just 3 seconds of service start, but it takes almost 90 ! seconds for all the VMs to load following that – not great.

**Comment by yakkomajuri** [comment]
Yeah that's what we were looking at - I didn't want to present logs as evidence though also because ECS collapses some.

But indeed, that's what triggered this thought. We were investigating why back pressure spikes for a few minutes after deploys (a problem that's been getting worse)

**Comment by Twixes** [comment]
I think we are good with GeoIP from a performance perspective for now – the app is now stateless so there's only one global VM + there have been uncorrelated improvements to loading VMs since.
