### ISSUE TITLE
Local dev: No "main" config key or "index.js" file found for plugin

### ISSUE THREAD

**Issue by samwinslow** [PostHog/posthog#7170]
## Bug description

When locally developing a plugin, after adding it via Advanced > Install Local Plugin, sometimes the plugin errors out with `No "main" config key or "index.js" file found for plugin`, even though plugin.json is valid and index.js exists.

Sometimes restarting the plugin server seems to fix this, sometimes not.

A current workaround is just to code in the source editor rather than load local plugins, but it's a sharp UX papercut.

## Expected behavior

Reads config file and index.js correctly

## How to reproduce

1. Create or clone a known working plugin
2. Install via file path

**Comment by samwinslow** [comment]
Worth noting: the plugin sometimes will load correctly by itself after 6-7 minutes. My local dev setup is a well-equipped DigitalOcean box with ports forwarded to my local machine, although I don't think this could be network latency.

**Comment by paolodamico** [comment]
+1 this keeps happening to me too when developing locally, using the plugin from GH fixed it but it's not a great dev experience
