### ISSUE TITLE
Make feature flags overrides logic perform better

### ISSUE THREAD

**Issue by macobo** [PostHog/posthog#7182]
## Is your feature request related to a problem?

We query active feature flags every time for a /decide endpoint call as well as for every event ingested. This means it's critical we're able to calculate this in an efficient manner.

Currently, calculating feature flags works something like this:
1. We query the flag + persons (or upcoming, groups) which flags and variants are active. This includes a distinct_id => person lookup
2. After every flag has been queried, we do a distinct_id => person query (in a subquery) query all FeatureFlagOverrides related to the user and load all the flags all over again

Related problem is that this is these two steps are done separately and step 2 is not covered with in-depth tests. Also exported functions from feature flags module are confusing as you have feature_flag.match, `get_active_feature_flags` and `get_overridden_feature_flags` functions which all do subtly different things.

## Describe the solution you'd like

1. Integrate the overrides logic into the main loop
2. Load overrides alongside feature flags, avoid unneeded second distinct_id => person_id lookup
3. Add tests checking the amount of DB queries done when loading feature flags
4. Unify the API for the module in a more clear - have a single external entrypoint
5. Maybe figure out a way to query Persons once instead of per-flag?

## Describe alternatives you've considered

Not doing this.

## Additional context

Related to #7115 and experimentation milestones. We should clean this up.

cc @rcmarron for context - not worth tackling right now due to groups changes occurring within the module.

**Comment by macobo** [comment]
After playing with the logic a bit more: It'd be even better to just do the matching in python for person/group property filters, though this adds complications for cohort filters. This way in some cases we only do 3 queries: flags + 1 person query + 1 overrides query.

Matching in python is doable if we were to match an instance against a Q object, which is a bit tricky but not overtly hard. :)

cc @paolodamico for other feature-flag related thoughts.

**Comment by paolodamico** [comment]
This makes sense to me, but probably @mariusandra or @rcmarron will have better context here. I don't think this would be affected by Experimentation, as the allocation to a flag/experiment would work the same way.

**Comment by paolodamico** [comment]
This makes sense to me, but probably @mariusandra or @rcmarron will have better context here. I don't think this would be affected by Experimentation, as the allocation to a flag/experiment would work the same way.

**Comment by macobo** [comment]
The reason I'm bringing this up alongside experimentation is that we're revisiting feature flags for the first time fundamentally.

Related to that, I believe it's worth considering allocating time to make them usable in cases they aren't yet, one of which is performance, especially outside posthog-js. As we accumulate complexity, it will only become harder to solve these issues without killing features.

Not saying we need to solve this asap, but it's another product area to consider. :)

**Comment by paolodamico** [comment]
I'll schedule a sync discussion for this, we can chat about the best path forward.
