### ISSUE TITLE
Missing page headers

### ISSUE THREAD

**Issue by clarkus** [PostHog/posthog#7189]
## Bug description

The persons and events features are missing their page headers.

<img width="1579" alt="Screen Shot 2021-11-17 at 11 13 38 AM" src="https://user-images.githubusercontent.com/254612/142267589-6cec1f28-df46-4d57-b282-04e2131d4d14.png">

## Expected behavior

These pages should have headers like our other feature pages.

## How to reproduce

1. Navigate to persons or events
2. Note the missing header

## Environment

- [x] PostHog Cloud

**Comment by paolodamico** [comment]
Even your screenshots look super nice 😉

**Comment by Twixes** [comment]
⌘+Shift+4 FTW

**Comment by clarkus** [comment]
⌘+Shift+5 for video capture, too :)

**Comment by mariusandra** [comment]
Let's not forget ⌘+Shift+6 with [gifox](https://gifox.io/)

![2021-11-18 21 00 10](https://user-images.githubusercontent.com/53387/142488143-62f696ed-c777-4d92-85ca-80d7665716ba.gif)
