### ISSUE TITLE
Allow filtering Persons in the API by multiple `distinct_id`s

### ISSUE THREAD

**Issue by samwinslow** [PostHog/posthog#7192]
## Is your feature request related to a problem?

Would be great to be able to surface multiple results from the persons API by `distinct_id` in one request.

I know what it'd look like in Postgres/Django (`distinct_id__in`) and raw SQL `distinct_id in ['foo', 'bar']` but not in our Clickhouse filter logic.

@liyiy added similar filters for `id` and `uuid` to `queries.base.filter_persons`, maybe we can pair on this?

## Additional context

Building a plugin and not trying to `await` a bunch of person calls

**Comment by macobo** [comment]
Q: What's the plugin you're trying to build/problem you're solving? Is this perhaps better solved by exposing Person to plugins in a better way?

**Comment by samwinslow** [comment]
@macobo My plugin currently calls `/api/event?action_id=` on a set interval, and if certain person properties are not available on the event, a lookup to `/api/person?distinct_id=` is performed in order to find what those properties may be.

It's conditionally enriching a set of events with person properties, which may or may not have been present at the time of the event.

**Comment by macobo** [comment]
This might not be a dealbreaker depending on the application, but this approach would run into all kinds of consistency troubles. cc @tiina303 and @yakkomajuri for those.

Also honorary mention to #6690

**Comment by samwinslow** [comment]
That's an interesting thread, and in some cases, I'd find it useful to have a chain of person property state changes and be able to step forward/back through them. But I think Tiina's comment captures the essence of what this plugin implementation needs:

> timeless properties - for which I don't care about the older values, e.g. email, initial referring site

In my current case I'm looking for an advertising identifier, `gclid`, which for most users is only set once, because most users won't go back and click on ads again & again. It could change, yes, but it's unlikely, especially because Google will tend to assign me the same `gclid` for the same ad.

Because the plugin will run these queries on a schedule, e.g. every hour, there's a theoretical possibility of missing an intermediate state if the property is overwritten within that time.

From tests [plugin-server/tests/shared/process-event.ts:330](https://github.com/PostHog/posthog/blob/master/plugin-server/tests/shared/process-event.ts#L330) it seems clear that a delay (e.g. 1-2 minutes) is needed between setting and getting person properties. So, I wonder what the result would be of this sequence:

1. Event comes in from `posthog.com` with `event.properties.gclid` -> begins to ingest, triggers an update of person property
2. 30 seconds later, event comes in from `app.posthog.com/signup`, same user, NO `event.properties.gclid`* -> begins to ingest

_* because gclid is stored in LocalStorage on `posthog.com`, it will only be sent as an event property while on that domain._

When event 2 is ingested, I can't count on `event.person.properties.gclid` being set, right? So if event 2 is the conversion event, and there's no `gclid` set either on that event or the person properties at the time of the event, I'll have to be less picky about the timing or I will miss the conversion.

Some parts of the case above may provide support for this feature request, some parts may suggest a different approach. I can see https://github.com/PostHog/posthog/issues/2594 being useful, too. If the plugin ran every hour, it could ask for "Users who have done $conversion in the last hour, who have person property `gclid` set."

**Comment by samwinslow** [comment]
(The `gclid` problem may also be solved via a cookie accessible by multiple subdomains, but that's a bit out of scope here)

**Comment by tiina303** [comment]
You're correct about the timing problem, furthermore due to network or anything else the event that set person properties could be arriving to Posthog after the signup event. Which means even if we populated event properties we'd need to populate them backwards sometimes if we wanted them to be there ingestion order independently. As we know edits are expensive on ClickHouse, so we're not going to do that.
