### ISSUE TITLE
Enhance top bar Search

### ISSUE THREAD

**Issue by Twixes** [PostHog/posthog#7210]
## Is your feature request related to a problem?

We now have a search bar in the top bar.

![Search](https://user-images.githubusercontent.com/4550621/142455678-8f2ffcf4-c8d6-482b-a58f-0b042160756e.png)

That's cool, but the command palette it opens isn't that good at search just yet.

## Describe the solution you'd like

We discussed this with @clarkus and came to the conclusion that there isn't really anything else that works in the top bar as well as the current search bar. So perhaps the best solution is to just make the palette better at search.

Currently full-fledged search only works for:
- dashboards

There's rudimentary support for:
- persons (but it takes a while, there's no indication of loading, and needs an exact match)

What we should _add_:
- insights
- feature flags
- cohorts
- plugins
- annotations

If we had all of this, the possibilities would be fantastic.
Though my worry is that maybe it would be a bit _too_ wide-ranging search for the command palette. An alternative option might be search _page_? TBD.

**Comment by neilkakkar** [comment]
I'll say universal search sort of addresses this

<img width="596" alt="image" src="https://user-images.githubusercontent.com/7115141/163979175-99d021d0-823b-4f15-b0aa-955437734202.png">


So closing this issue, and will raise separate issues for bugs that come up with universal search!
