### ISSUE TITLE
Add entry/exit animation to  `Popup`

### ISSUE THREAD

**Issue by Twixes** [PostHog/posthog#7212]
## Is your feature request related to a problem?

It's a tiny thing: Our `Popup` overlay doesn't have an animation when it appears and disappears.

## Describe the solution you'd like

We've been using `Popup` for a while, but now that it's used by lemon UI (i.e. all of the navigation) it's pretty exposed and could use an slide in/out animation to make its experience a bit smoother, particularly as AntD does have that – we should probably use a similar style for this for cohesiveness.
![2021-11-18 17 48 23](https://user-images.githubusercontent.com/4550621/142460370-56fceda4-44a9-4ee2-ac23-5329312c4196.gif)

**Comment by mariusandra** [comment]
The pragmatist in me wonders if we could use ant's dropdown here as well, at least for consistent modal/popover/etc logic.
