### ISSUE TITLE
Inconsistent UI state, better renaming, action selector not working

### ISSUE THREAD

**Issue by alexkreidler** [PostHog/posthog#7213]
I'll report a few issues I had on my first real experience with Posthog Cloud:

Lots of values in the UI are in an inconsistent state after an update. For example, I renamed an Insight from main list view, and then went to the detail view and it has the old name. Also, I think there should be a way to rename the Insight/chart directly from the detail page.

Also, when creating an action from this selector: `nav a`, no events show up. The selector has elements that are nested but not directly, and it is only based on element types.

(I know you all released a new interface recently so I understand it may be buggy. Also sorry this is a condensed issue for multiple bugs/feature reqs, and it isn't more detailed - I don't have much time today)

Thanks for the project!

**Comment by paolodamico** [comment]
Thanks for taking the time to write this @alexkreidler, we'll take a look to improve/fix it.

**Comment by Twixes** [comment]
Hey! Most of this should be resolved now, but feel free to report issues if there's still something.
