### ISSUE TITLE
BackTo element in the new design

### ISSUE THREAD

**Issue by mariusandra** [PostHog/posthog#7221]
## Bug description

We have this "BackTo" component. It's used in a lot of places:

- In the actions table when going to an insight (screencast above)
![2021-11-19 09 42 17](https://user-images.githubusercontent.com/53387/142592747-2de9cd93-391b-414a-bb9a-fa01b44796cc.gif)

- Clicking into an action in the taxonomic filter
![2021-11-19 09 45 33](https://user-images.githubusercontent.com/53387/142593028-509b9232-7fc9-4e8d-9645-4610e5bac7ef.gif)

- Cohorts table
![2021-11-19 09 46 46](https://user-images.githubusercontent.com/53387/142593289-914a9a89-f156-4065-898d-5a22ccb8a3f2.gif)

- Events table
![2021-11-19 09 47 28](https://user-images.githubusercontent.com/53387/142593263-c58ae329-a7aa-4ff5-9c48-34ee251465aa.gif)

- The persons table when going into a person
![2021-11-19 09 48 58](https://user-images.githubusercontent.com/53387/142593502-b71bbb47-8ede-4290-98e2-0c1d83db070a.gif)

- The persons table under cohorts
![2021-11-19 09 50 12](https://user-images.githubusercontent.com/53387/142593687-6c1cb0e9-05a3-43a6-b1b2-bf74c72cf1bf.gif)

- The persons table in the retention insights's line graph (now that's an obscure place!)
![2021-11-19 09 51 58](https://user-images.githubusercontent.com/53387/142593932-54d755be-4335-4456-a7ea-d3cd733af251.gif)

- Few places in the old `scenes/sessions`
- Few other action dropdowns (`ActionInfo`)

## Usage

Excluding "Back to recordings/sessions" clicks from within recordings, a "Back to" link is clicked on average by [5% of users](https://app.posthog.com/insights?insight=TRENDS&interval=day&display=ActionsLineGraph&actions=%5B%7B%22id%22%3A12253%2C%22name%22%3A%22Clicked%20%5C%22Back%20To%5C%22%22%2C%22type%22%3A%22actions%22%2C%22order%22%3A0%2C%22math%22%3A%22dau%22%7D%5D&events=%5B%7B%22id%22%3A%22%24pageview%22%2C%22type%22%3A%22events%22%2C%22order%22%3A1%2C%22name%22%3A%22%24pageview%22%2C%22math%22%3A%22dau%22%7D%5D&new_entity=%5B%5D&properties=%5B%7B%22key%22%3A%22%24current_url%22%2C%22value%22%3A%22https%3A%2F%2Fapp.posthog.com%2F%22%2C%22operator%22%3A%22icontains%22%2C%22type%22%3A%22event%22%7D%5D&formula=(A%20%2F%20B)%20*%20100) on cloud:

![image](https://user-images.githubusercontent.com/53387/142597434-dead7f31-9da0-4ad5-98d0-ab55afcd08e6.png)

## Questions / issues

- Do we need this link?
- Normally the browser's "back" button is made to perform this function. We should strive to have that button working well on all pages. It usually does, not like in one of the screencasts above (link to old sessions page from the cohorts table).
- If we need this, is the element correctly designed/implemented/positioned now?
- Currently this BackTo component shows sooner than the next scene, leading to weird effects. This should be fixed if we decide to keep it.

Any strong feelings for keeping or removing? @clarkus @Twixes @paolodamico @timgl ?

**Comment by Twixes** [comment]
If we do keep it, I think it should be a part of breadcrumbs (kind of like the "Back to the previous app" button in iOS's status bar). Though IMO it only clutters up the URL and is error-prone in a situation where the browser's back button should be the reliable and default way of navigating backwards/forwards, so I'm in favor of removing.

**Comment by clarkus** [comment]
I think we can rely on browser navigation features here. The breadcrumbs give you a sense of place and the browser manages history. Let's remove this link.
