### ISSUE TITLE
Remove Sessions page entirely

### ISSUE THREAD

**Issue by Twixes** [PostHog/posthog#7231]
We've decided to remove Sessions in their current form, so the Sessions page is no longer accessible from the sidebar in the navigation redesign. Before this, it was also replaced by Recordings with feature flag `6050-remove-sessions`, which I believe is rolled out to all Cloud users, _but_ no self-hosted instances. This feature flag additionally controls some other places outside of the sidebar where we linked to Sessions, so self-hosted users may still see some mentions of Sessions.

The flag has been added 7 weeks ago so I propose going forward fully with this and removing code of the Sessions page, along with all links to it and with the flag.

Related: https://github.com/PostHog/posthog/issues/6140
CC @paolodamico

**Comment by paolodamico** [comment]
We also rolled it out to self-hosted users in 1.30.0 (you no longer see the sessions page), but we've had some recent reports of bugs with the recordings page. I would hold off on this for a couple of weeks just in case. We would also have some time to get feedback from self-hosted users. We can remove it before the next release. Thoughts?

**Comment by Twixes** [comment]
There's no rush, though I don't see the old code really coming in useful if we're now all-in on replacing Sessions with Recordings. In any case I'll let you handle this when you think it makes sense, as you've got some more context.

**Comment by macobo** [comment]
Note that the flag is enabled for all cloud users already.

I think this is causing technical churn and it's worth removing - less code, more incentive to fix things ASAP.

**Comment by paolodamico** [comment]
Looks like this is starting to create more complications for us that outweigh the benefits of keeping it around so put a PR to remove it already.
