### ISSUE TITLE
Export events as CSV

### ISSUE THREAD

**Issue by timgl** [PostHog/posthog#724]
**Is your feature request related to a problem? Please describe.**

I want to export a list of events as CSV.

**Describe the solution you'd like**
Whenever there's an EventTable, I'd like a button to export the currently filtered list by CSV.

**Additional context**
This should be pretty easy, see #441. It is worth putting in a sensible limit (10k?) to avoid exporting the entire database.

***Thank*** you for your feature request - we love each and every one!

**Comment by thedeveloperr** [comment]
Can I work on this ?

**Comment by timgl** [comment]
Go for it!

**Comment by thedeveloperr** [comment]
10k limit will be for latest 10k events. What will happen if a user needs older than 10k ? Shall I add some kind of pagination filter that will allow user to at once download 10k events but can do it for 1st 10k or 2nd 20k and so on ?

**Comment by timgl** [comment]
Sure! If you have a good idea on how to achieve this go ahead :)

**Comment by HassanAarzoo** [comment]
@thedeveloperr Are you still working on it?

**Comment by thedeveloperr** [comment]
Yes. Sorry for delay. Had a personal problem due to which it got delayed. I
will be pushing first version soon.

**Comment by timgl** [comment]
@thedeveloperr Hey! did you get anywhere with this? Happy to help finish this if you have a basic version?

**Comment by eikooc** [comment]
I'm also happy to chime in if you didn't get anywhere @thedeveloperr :)

**Comment by timgl** [comment]
@eikooc If you fancy taking this over I think that'd be great! Let me know if you need any help getting started or you want to do a pairing session

**Comment by eikooc** [comment]
@timgl I'd be happy to. Do you have time in the weekends for pairing? And in which timezone are you?

**Comment by timgl** [comment]
@eikooc Could you send me an email at tim@posthog.com so we can schedule something? Looking forward to it!

**Comment by wundo** [comment]
I'm looking forward for having this :)

**Comment by thedeveloperr** [comment]
@timgl Is this issue resolved ? Sorry for the absence. Had some personal issues going on. I wanted to take again go at it if no one is working at it.

**Comment by Ronihe** [comment]
@timgl Hi Tim is this still open? would love to take this one?

**Comment by timgl** [comment]
@Ronihe Go for it!

**Comment by timgl** [comment]
Essentially done.
