### ISSUE TITLE
View recordings relevant to an insight from the persons modal

### ISSUE THREAD

**Issue by rcmarron** [PostHog/posthog#7246]
Starting a new issue for (https://github.com/PostHog/posthog/issues/5664) because the conversation there is outdated.

**Summary:** To allow customers to understand "why" a user did something (churned from a funnel, performed a specific event etc.), we should link to recordings from insights. Specifically, in the persons modal on an insight, we should link to the specific recording where the event happened.

For the UX, we have these mock-ups from @clarkus 

https://www.figma.com/file/9yWtngNb1AIuf6KmXaEPJA/App-doodles?node-id=1085%3A137286
![image](https://user-images.githubusercontent.com/4813045/142686527-4557ac01-1ac8-4606-a31e-62c783cb5953.png)

Now that both `events` and `session_recording_events` are tagged with a `session_id`, we can definitively say this event occurred in this recording, and that should make this work much simpler. It will only work for customers who have upgraded posthog-js, but I think that's OK.

For most of the insights, it's pretty obvious which recordings should be shown in the modal. For example, on the trends page, when you open the modal, we should show the recordings when the event from the trend-line occurred. (Note: there could be multiple recordings that include that event)

**Open questions**
* What should we show for funnel drop off steps? Because a drop off is the absence of an event, we don't have a recording to show. Maybe it makes sense to show the recording that shows the previous step? Or show no recording?
* Speaking with @EDsCODE, it sounds like it might be tricky to show multiple recordings for a funnel step (if the user did the thing multiple times). We might end up limiting this to just one recording for a completed funnel step.
* Once we get the link to the proper recording, it would be awesome to highlight the specific event in the recording itself. Probably a v2 feature, but it would be so cool!

cc @EDsCODE @alexkim205 @paolodamico @macobo @neilkakkar

**Comment by macobo** [comment]
Important: Please also consider using _timestamps_ with the recording - i.e. direct users to _when_ something occurred if possible.

> What should we show for funnel drop off steps? Because a drop off is the absence of an event, we don't have a recording to show. Maybe it makes sense to show the recording that shows the previous step? Or show no recording?

If I'm diagnosing a funnel dropoffs, I'd like to know why users dropped off. So show me the previous successful step and onwards.

**Comment by rcmarron** [comment]
> Important: Please also consider using _timestamps_ with the recording - i.e. direct users to _when_ something occurred if possible.

Ah, yeah that'd be super useful when showing the recording itself. I think to be certain about the position in a recording, we need `session_id`, `window_id` and `timestamp`.

@EDsCODE worth noting ^ if you're looking at the funnel stuff.

**Comment by paolodamico** [comment]
I would prioritize this as soon as possible, critical for Diagnosing Causes, seeing recordings is the prime way to get qualitative insights (CC @mariusandra)

**Comment by clarkus** [comment]
> Speaking with @EDsCODE, it sounds like it might be tricky to show multiple recordings for a funnel step (if the user did the thing multiple times). We might end up limiting this to just one recording for a completed funnel step.

The mockups here are a bit out of date - ideally we'd show only the applicable session recording for the funnel. There generally shouldn't be multiple recordings unless it's a really broad conversion window, right?

**Comment by rcmarron** [comment]
> The mockups here are a bit out of date - ideally we'd show only the applicable session recording for the funnel. There generally shouldn't be multiple recordings unless it's a really broad conversion window, right?

I think in funnels it's generally true that multiple matching recordings would be rare, but in other insights, it will probably be more common that a user has multiple recordings of them performing a specific event.

**Comment by benjackwhite** [comment]
Closing this as it is definitely covered in the new PersonsModal
