### ISSUE TITLE
Add users and groups to search

### ISSUE THREAD

**Issue by jamesefhawkins** [PostHog/posthog#7265]
## Is your feature request related to a problem?

I want to know how company X is using my product.

## Describe the solution you'd like

I use the search bar (which is _much_ more prominent after the redesign)
It then let's me click to see an org or individual's profile (with some easy way to see their usage from there)

## Describe alternatives you've considered

Create an insight and filter manually

**Comment by Twixes** [comment]
That's a great suggestion. Related:
- #7210

**Comment by jamesefhawkins** [comment]
Anecdote; I use this feature in Stripe constantly (I actually often search stripe -> find a subscription -> see customer usage, as it's so fiddly to do this with PostHog at the moment)

**Comment by benjackwhite** [comment]
Closing as completed
