### ISSUE TITLE
Average session length chart behaves funny

### ISSUE THREAD

**Issue by mariusandra** [PostHog/posthog#727]
**Describe the bug**

The "average session length" chart behaves weird. Locally it throws a bunch of errors. In production (app.posthog.com) all those are caught [in Sentry](https://sentry.io/organizations/posthog/issues/1646850085/?project=1899813&query=is%3Aunresolved).

![screencast 2020-05-06 09-54-56](https://user-images.githubusercontent.com/53387/81150271-e8593380-8f7f-11ea-9279-175b5644f9e7.gif)

**To Reproduce**
1. Open Trends
2. Click "Sessions"
3. Choose "Average Session Length" and "Line chart" 

**Expected behavior**
I should see a tooltip, but instead the page crashes

**Additional context**
Clicking on the points also shows "undefined" in the modal:
![image](https://user-images.githubusercontent.com/53387/81150428-2c4c3880-8f80-11ea-9193-8221f84aeb8e.png)

**Comment by Jujhar** [comment]
This seems to be a browser issue maybe I think with no issue for me on Firefox with it includes with tooltips.
