### ISSUE TITLE
Funnels - person modal can't be opened

### ISSUE THREAD

**Issue by paolodamico** [PostHog/posthog#7275]
## Bug description

On funnels (vertical), I can no longer click on the bar or label (e.g. “44 users”) to open the person modal. See user frustrated by this: [recording](https://app.posthog.com/recordings?sessionRecordingId=17d47134204ef1-04db7fe774d47f-3c700c58-1fa400-17d471342051070&filters=%7B%22actions%22%3A%5B%5D%2C%22events%22%3A%5B%7B%22id%22%3A%22%24pageview%22%2C%22type%22%3A%22events%22%2C%22order%22%3A0%2C%22name%22%3A%22%24pageview%22%2C%22properties%22%3A%5B%7B%22key%22%3A%22%24host%22%2C%22value%22%3A%5B%22posthog.com%22%5D%2C%22operator%22%3A%22is_not%22%2C%22type%22%3A%22event%22%7D%5D%7D%2C%7B%22id%22%3A%22%24rageclick%22%2C%22type%22%3A%22events%22%2C%22order%22%3A1%2C%22name%22%3A%22%24rageclick%22%7D%5D%2C%22properties%22%3A%5B%5D%2C%22date_from%22%3A%222021-10-23%22%2C%22date_to%22%3Anull%2C%22offset%22%3A50%2C%22session_recording_duration%22%3A%7B%22type%22%3A%22recording%22%2C%22key%22%3A%22duration%22%2C%22value%22%3A60%2C%22operator%22%3A%22gt%22%7D%7D&source=recordings_list); **01:09**.

<img width="461" alt="" src="https://user-images.githubusercontent.com/5864173/142942729-7a358603-2408-4283-a51b-100dca80cf8f.png">

## Expected behavior
Clicking on any of the red boxes above, should open the person modal.

## How to reproduce

1. Create a funnel.
2. Disable the vertical funnel FF (if enabled).
3. Try clicking within the redboxes shown above.

## Environment

- [x] PostHog Cloud
- [ ] self-hosted PostHog (ClickHouse-based), version/commit: _please provide_
- [ ] self-hosted PostHog (Postgres-based, legacy), version/commit: _please provide_

**Comment by alexkim205** [comment]
I think this happens because we're no longer able to differentiate dashboard items from insights which is how we determine if the modal is enabled. Fix incoming soon
