### ISSUE TITLE
Can't select different time to convert between steps

### ISSUE THREAD

**Issue by paolodamico** [PostHog/posthog#7276]
## Bug description

When trying to select different steps to see the time to convert distribution in a funnel, the dropdowns don't change (see [this recording](https://app.posthog.com/recordings?sessionRecordingId=17d4884e10e79f-0a645ad51a22de8-4c3e217e-4b9600-17d4884e10f52c&filters=%7B%22actions%22%3A%5B%7B%22id%22%3A%2210784%22%2C%22type%22%3A%22actions%22%2C%22order%22%3A1%2C%22name%22%3A%22Discoveries%22%7D%5D%2C%22events%22%3A%5B%7B%22id%22%3A%22%24pageview%22%2C%22type%22%3A%22events%22%2C%22order%22%3A0%2C%22name%22%3A%22%24pageview%22%2C%22properties%22%3A%5B%7B%22key%22%3A%22%24host%22%2C%22value%22%3A%5B%22posthog.com%22%5D%2C%22operator%22%3A%22is_not%22%2C%22type%22%3A%22event%22%7D%5D%7D%5D%2C%22properties%22%3A%5B%5D%2C%22date_from%22%3A%222021-10-23%22%2C%22date_to%22%3Anull%2C%22offset%22%3A0%2C%22session_recording_duration%22%3A%7B%22type%22%3A%22recording%22%2C%22key%22%3A%22duration%22%2C%22value%22%3A60%2C%22operator%22%3A%22gt%22%7D%7D&source=recordings_list) @ **00:53**. Further, the graph seems to be timing out frequently (at least in the last hour).

## Expected behavior

I should be able to view the time to convert distribution between any two steps in a funnel within 5-6 seconds. 

## How to reproduce

See recording above.

## Environment

- [x] PostHog Cloud
- [ ] self-hosted PostHog (ClickHouse-based), version/commit: _please provide_
- [ ] self-hosted PostHog (Postgres-based, legacy), version/commit: _please provide_

**Comment by paolodamico** [comment]
@EDsCODE as Li is off this week and she was the one on call for bugs of Core Analytics, is there someone who can help out with this?

**Comment by neilkakkar** [comment]
Guess it's me then! Looking 👀
