### ISSUE TITLE
Loading state persists on insight after loading heavy query

### ISSUE THREAD

**Issue by paolodamico** [PostHog/posthog#7277]
## Bug description

See [this recording](https://app.posthog.com/recordings?sessionRecordingId=17d48acf803f4-0e068265f2731c-192b1d0f-1fa400-17d48acf804a71&filters=%7B%22actions%22%3A%5B%7B%22id%22%3A%2210784%22%2C%22type%22%3A%22actions%22%2C%22order%22%3A1%2C%22name%22%3A%22Discoveries%22%7D%5D%2C%22events%22%3A%5B%7B%22id%22%3A%22%24pageview%22%2C%22type%22%3A%22events%22%2C%22order%22%3A0%2C%22name%22%3A%22%24pageview%22%2C%22properties%22%3A%5B%7B%22key%22%3A%22%24host%22%2C%22value%22%3A%5B%22posthog.com%22%5D%2C%22operator%22%3A%22is_not%22%2C%22type%22%3A%22event%22%7D%5D%7D%5D%2C%22properties%22%3A%5B%5D%2C%22date_from%22%3A%222021-10-23%22%2C%22date_to%22%3Anull%2C%22offset%22%3A0%2C%22session_recording_duration%22%3A%7B%22type%22%3A%22recording%22%2C%22key%22%3A%22duration%22%2C%22value%22%3A60%2C%22operator%22%3A%22gt%22%7D%7D&source=recordings_list) where a user loads a heavy query, we show the timeout in progress warning and afterwards the graph loads, yet we keep displaying the skeleton loader for the Details table and the spinner in the graph.

## Expected behavior

After the query loads, the loaders should disappear.

## How to reproduce

See recording above.

## Environment

- [x] PostHog Cloud
- [ ] self-hosted PostHog (ClickHouse-based), version/commit: _please provide_
- [ ] self-hosted PostHog (Postgres-based, legacy), version/commit: _please provide_

**Comment by pauldambra** [comment]
It used to be that loading was a separate state on top of the other states of the insight

In #7429 that was changed so that loading shows _instead of_ the other blocking or loaded states. So this should be accidentally fixed

I've played with a very heavy query and can no longer reproduce.

**Comment by Twixes** [comment]
I also can't reproduce, so I think we should be good, though of course to be reopened if this does come up.
