### ISSUE TITLE
Notes on recordings dogfooding

### ISSUE THREAD

**Issue by paolodamico** [PostHog/posthog#7278]
For @alexkim205 & @rcmarron. Spent quite a bit of time dogfooding recordings today. Some potential improvements/suggestions (and a couple of bugs):

- @clarkus should the redacted boxes have rounded corners to better match the rest of the UI? Further, perhaps having them a bit less dark?
    - What happens when the app has a dark theme?
- Filtered events are not highlighted as per design.
- Filtering UI in the recordings list is not consistent with the rest of the app.
- Can we do a nicer buffering state ? Even just changing the font would go a long way. CC @clarkus 
- When buffering it seems we have to load everything in sequence instead of the point I care about. See [this recording](https://app.posthog.com/recordings?sessionRecordingId=17d482417022cc-081301ff05ac6f-1f396452-13c680-17d48241703317&filters=%7B%22actions%22%3A%5B%5D%2C%22events%22%3A%5B%7B%22id%22%3A%22%24pageview%22%2C%22type%22%3A%22events%22%2C%22order%22%3A0%2C%22name%22%3A%22%24pageview%22%2C%22properties%22%3A%5B%7B%22key%22%3A%22%24host%22%2C%22value%22%3A%5B%22posthog.com%22%5D%2C%22operator%22%3A%22is_not%22%2C%22type%22%3A%22event%22%7D%5D%7D%2C%7B%22id%22%3A%22%24rageclick%22%2C%22type%22%3A%22events%22%2C%22order%22%3A1%2C%22name%22%3A%22%24rageclick%22%7D%5D%2C%22properties%22%3A%5B%5D%2C%22date_from%22%3A%222021-10-23%22%2C%22date_to%22%3Anull%2C%22offset%22%3A0%2C%22session_recording_duration%22%3A%7B%22type%22%3A%22recording%22%2C%22key%22%3A%22duration%22%2C%22value%22%3A60%2C%22operator%22%3A%22gt%22%7D%7D&source=recordings_list) where I wanted to look at a rage click at ~1:00:00.
- Happened a couple of times, app will continue skipping inactivity while the user is still very clearly moving. Further, if you click on the pin and jump directly, the recording playbacks properly. Try watching [this recording](https://app.posthog.com/recordings?sessionRecordingId=17d493e0ba4691-03a1ede3cfed73-1f396452-13c680-17d493e0ba5299&filters=%7B%22actions%22%3A%5B%7B%22id%22%3A%2210784%22%2C%22type%22%3A%22actions%22%2C%22order%22%3A1%2C%22name%22%3A%22Discoveries%22%7D%5D%2C%22events%22%3A%5B%7B%22id%22%3A%22%24pageview%22%2C%22type%22%3A%22events%22%2C%22order%22%3A0%2C%22name%22%3A%22%24pageview%22%2C%22properties%22%3A%5B%7B%22key%22%3A%22%24host%22%2C%22value%22%3A%5B%22posthog.com%22%5D%2C%22operator%22%3A%22is_not%22%2C%22type%22%3A%22event%22%7D%5D%7D%5D%2C%22properties%22%3A%5B%5D%2C%22date_from%22%3A%222021-10-23%22%2C%22date_to%22%3Anull%2C%22offset%22%3A0%2C%22session_recording_duration%22%3A%7B%22type%22%3A%22recording%22%2C%22key%22%3A%22duration%22%2C%22value%22%3A60%2C%22operator%22%3A%22gt%22%7D%7D&source=recordings_list) without skipping anything and you'll see this.
- Pagination in recordings list is inconsistent with the rest of the app. Further the experience is painful, the entire table freezes and scroll position stays at the bottom.
- Searching “rage” in the event list at a recording yields no rage click events but a bunch of page views, searching “ragec” works.
- Should we allow users to hide certain events that will always be useless for them in recordings? e.g. `$feature_flag_called` for us. My concern would be with an extra configuration that can add confusion. CC @clarkus 
- Related to the above, should we always hide certain PostHog events that are probably going to add very little value? e.g. `$identify`, `$groupidentify`, ...
- Redacted box doesn't seem to be showing up every time it should. For instance, watch a recording on a `/person/{id}` page and you'll see the right side table of properties not showing the property values, yet the box is also not shown.

**Comment by alexkim205** [comment]
Hey @paolodamico do you mind bringing these points over here https://github.com/PostHog/posthog/issues/6483? We'll try to squash these all in one place

Thanks :)

**Comment by paolodamico** [comment]
Perfect, let's continue the conversation there.
