### ISSUE TITLE
Show all events of a certain type

### ISSUE THREAD

**Issue by mariusandra** [PostHog/posthog#728]
**Describe the solution you'd like**
I would like to see all events of a certain type, e.g. $pageview

**Additional context**
In the Funnels page, if I have an action in the funnel, I can click the title and see all events that make up this action. I'd like to do the same with just the events:

![image](https://user-images.githubusercontent.com/53387/81183569-97613380-8faf-11ea-90ea-b147cdf659c4.png)

**Comment by Twixes** [comment]
Hey @mariusandra, thank you, we appreciate feature requests a lot! Could you clarify a bit what this UX would look like?

**Comment by mariusandra** [comment]
![image](https://user-images.githubusercontent.com/53387/116552330-338af580-a8f9-11eb-9102-e09c36191f88.png)

I think it's done
