### ISSUE TITLE
Support "Completed User %" for action in trends

### ISSUE THREAD

**Issue by joesaunderson** [PostHog/posthog#7289]
## Is your feature request related to a problem?

I have tagged a few actions on my site, I want to easily analyse what % of users have made these actions. 

## Describe the solution you'd like

An option in the "counted by" dropdown that defines what % of users made the action / event during the time period you have selected. 

I would say that you should get a separate % for the breakdown period you select (daily, weekly, monthly etc).

## Describe alternatives you've considered

A separate trend for each insight, using formulas to work out the %.

**Comment by macobo** [comment]
Related: https://github.com/PostHog/posthog/issues/4344

**Comment by macobo** [comment]
@joesaunderson some follow-up questions: who is considered a 'user' in your usecase?

Some considerations:
1) Is it everyone with an account in your app?
2) would you include users who visited the marketing site once and bounced?
3) what about churned users?
4) are there users who are not in PostHog, e.g. due to cookie opt out or not having visited the site since PostHog was installed?
5) is there a common identifier between the users to count, e.g. a specific property?

**Comment by joesaunderson** [comment]
> @joesaunderson some follow-up questions: who is considered a 'user' in your usecase?
> 
> Some considerations:
> 1) Is it everyone with an account in your app?
> 2) would you include users who visited the marketing site once and bounced?
> 3) what about churned users?
> 4) are there users who are not in PostHog, e.g. due to cookie opt out or not having visited the site since PostHog was installed?
> 5) is there a common identifier between the users to count, e.g. a specific property?

1) Yes, a user for us is someone who has an account on our app.
2) We don't run PostHog on our marketing site, as it's not a traditional flow. But if we did it would be good to define a 'user' somewhere I.e has X properties
3) When a merchant churns or a user account is locked, we (plan to) delete their users PostHog data via the API
4) We don't offer a cookie opt out (not consumer facing) and we did a mass identification of all users who weren't in PostHog
5) All users have a role, created date, name etc

**Comment by macobo** [comment]
Thanks for the feedback @joesaunderson - this does clear things up!

I think we have _almost_ all of the building blocks we need. How I'd build this graph:

1. Allow specifying unique users without selecting an event to aggregate on
2. Leverage formulas to build a trend line
3. (Nice-to-have) Supporting % unit on the Y axis

How would this work?

Our query building UI looks something like this currently

![image](https://user-images.githubusercontent.com/148820/146501254-0afd9d58-df83-4c2e-b73d-505047161632.png)

I have discussed with @clarkus before reversing the order of the counted by and showing. 

This would allow us to "build" a query like `Counting [Unique Users] who [have done] event [some event] (additional filters)`.

But we could also form a query like `Counting [Unique Users] who [exist] (additional filters)` which would allow to query total users or total users with some specific properties.

If you have that as trend A and your "unique users who have done pageview" as trend B you can then get the percentage you're looking for by formula `B / A`

While it's not the most direct way of solving this problem, it avoids issues around defining what a "user" is long-term and generally makes our query-building more powerful.

cc @EDsCODE and @clarkus for query-building thoughts.

**Comment by joesaunderson** [comment]
@macobo thanks for the detailed write up here. It makes perfect sense to me, and I think reversing the event / actor selectors would make perfect sense in this instance.

**Comment by clarkus** [comment]
This is from a [related issue](https://github.com/PostHog/posthog/issues/6254#issuecomment-985072765), but it does illustrate how we could reorder inputs to collect query parameters in this format. This is in the context of formula, but you can see how the variables are formatted the same as any other graph series. 

<img width="676" alt="Screen Shot 2021-12-02 at 3 04 32 PM" src="https://user-images.githubusercontent.com/254612/144517051-e3489680-b0c1-46ed-b245-de05830d6df8.png">

https://www.figma.com/file/gQBj9YnNgD8YW4nBwCVLZf/PostHog-App?node-id=5626%3A44519
