### ISSUE TITLE
Feature flag variants are not implemented in all client libraries

### ISSUE THREAD

**Issue by macobo** [PostHog/posthog#7290]
## Is your feature request related to a problem?

Feature flag variants are not implemented in all client libraries - method signatures indicate they still return booleans

## Describe the solution you'd like

Support feature flag variants

## Additional context

cc @samwinslow for initial implementor of the feature
cc @paolodamico for general flags context

**Comment by neilkakkar** [comment]
Should be sorted now (except for any new libs added, but tracking this on the library repo for specific libs instead)
