### ISSUE TITLE
Request: Better tooltips on insight tabs

### ISSUE THREAD

**Issue by joethreepwood** [PostHog/posthog#7292]
## Is your feature request related to a problem?

It has always bothered me that tooltips are inconsistently used in the Insights section. I think tooltips are great and that consistency is even better. Once a user discovers the tooltips we _do_ have, I think it's natural that they'd expect them to be consistent -- and they may expect this before hand. 

Currently, our tooltips look like this: 

```
Trends: (no tooltip)
Funnels: (no tooltip)
Retention: (no tooltip)
User Paths: (no tooltip)
Stickiness: Stickiness shows you how many days users performed an action within a timeframe. Example: If a user performed an action on Monday and again on Friday, it would be shown as "2 days".
Lifecycle: Understand growth by breaking down new, resurrected, returning and dormant users. 
Sessions: View average and distribution of session durations. 
```

## Describe the solution you'd like

Tooltips should be short, explanatory, consistent and optional. We shouldn't bury essential information there about how to use a tool (e.g. examples). I'd propose changing them to: 

```
Trends: Visualize and breakdown how actions or events vary over time.
Funnels: Discover how many users complete or drop out of a sequence of actions.
Retention: See how many users return on subsequent days after an intial action. 
User Paths: Trace the journeys users take within your product and where they drop off.
Stickiness: See what keeps users coming back by viewing the interval between repeated actions.
Lifecycle: Understand growth by breaking down new, resurrected, returning and dormant users. 
Sessions: View the average and distribution of session durations. 
```

## Describe alternatives you've considered

We could delete them all. Or leave as-is. 

## Additional context

I have had a look at trying this myself (Marcus and I were discussing as an example a few weeks ago during a coding tutorial) but implementing _new_ tooltips seemed very difficult. So here we are.

**Comment by paolodamico** [comment]
We already have the text in the "New Insight" button, so should be fairly straightforward. Adding to this sprint's plans.
