### ISSUE TITLE
Offload save action to worker

### ISSUE THREAD

**Issue by timgl** [PostHog/posthog#731]
**Is your feature request related to a problem? Please describe.**
Saving actions is super slow, with no feedback so you have no idea whether something is happening or not

**Describe the solution you'd like**
Do the calculating of the action in a worker

**Describe alternatives you've considered**
Wait

**Additional context**

***Thank*** you for your feature request - we love each and every one!

**Comment by sladyn98** [comment]
@timgl Hey I would love to take this up could you point me to a place to start ?

**Comment by flickz** [comment]
If no one is working on this issue, I'd like to be assigned.

**Comment by Twixes** [comment]
Hi @flickz! Sure, this is all yours. If you have questions, technical or otherwise, feel free to ask here.

**Comment by flickz** [comment]
@timgl I assume the workers run in the background? What immediate feedback would best for the user? Also, does this apply to updating existing actions?

**Comment by Twixes** [comment]
I think the system has changed enough that this can be closed.
