### ISSUE TITLE
Allow cleaning up events and properties

### ISSUE THREAD

**Issue by macobo** [PostHog/posthog#7315]
## Is your feature request related to a problem?

As a team accumulates data, they will have events/properties that are no longer in use that clutter their app.

Example from our team:
![image](https://user-images.githubusercontent.com/148820/143202334-42d73ab6-13be-4661-ba7a-83c86788b9e8.png)

## Describe the solution you'd like

Under event/properties stats allow 'hiding' events/properties from view.

## Describe alternatives you've considered

Alternatively, go the route of "verified" events/properties (as He@p) does - show those first. See also https://help.heap.io/category/heap-administration/data-governance/

## Additional context

Note: Existing reports, etc should still work well even with 'removed' events/properties.

Related: https://github.com/PostHog/posthog/issues/7126

**Comment by paolodamico** [comment]
@mariusandra @clarkus  wdyt about prioritizing this as we work on improving the taxonomic filter?

**Comment by mariusandra** [comment]
Seems very related

**Comment by timgl** [comment]
Make sure this is a paid feature by default please!

Also +1 for having 'verified' properties, would probably be more helpful

**Comment by joethreepwood** [comment]
[I'll link to my feedback on this topic here.](https://posthog.slack.com/archives/C011L071P8U/p1638368249068300)

Part of the issue for me is that there are SO many properties and they basically all lack descriptions and there's no way to easily jump from a query to the event list. 

A solution which would go some way to addressing my issue would be to have a way to make that jump easily, or else to surface some event property details (e.g. the description) as a tooltip or on hover.

**Comment by paolodamico** [comment]
- Thanks @joethreepwood, I'll reply in the main issue (#7448)
- @timgl I'm particularly curious about the `verified` concept, any reason in particular you thought of it? In theory you could easily achieve this using tags, initially I thought we could nudge users to do this via placeholders & suggestions, but now I'm thinking users are not finding this use case very organically.

**Comment by macobo** [comment]
Re verification, this came up as a usecase at Heap: https://help.heap.io/define-analyze/data-management/creating-and-managing-event.

Note that for this feature it would be great if we didn't distinguish between actions and events :)

**Comment by macobo** [comment]
Note: This came up as feedback from a paying client. https://posthogusers.slack.com/archives/G01J29T1F6W/p1641986184005100

cc @alexkim205 @paolodamico - is this in scope for the upcoming taxonomy refactor?

**Comment by alexkim205** [comment]
Yup this is definitely in the scope of taxonomy. We're tracking this somewhere else too, but assigning to myself so I dont lose it later
