### ISSUE TITLE
Unclear path result based on root

### ISSUE THREAD

**Issue by EDsCODE** [PostHog/posthog#732]
**Describe the bug**

**Subsequent Paths**
With the new path query, there are certain paths that are accounted for which previously were not found. For example, there might be a path where someone goes from `1_posthog.com => 2_posthog.com => 3_posthog.com/pricing` which would not have been accounted for by our old path query because at the first level `posthog.com => posthog.com` would be filtered out. The current query finds every sequence in a session. 

Right now, I've filtered out the relationships that are redundant like `posthog.com => posthog.com`. As a result, the later order sequence from `2_posthog.com => 3_posthog.com/pricing` is retained  but it produces a confusing redundant path that skips a level.

**Root Path**
We're currently filtering out one-off events so it looks like there's no dropoff from the initial event. The events shown in paths query represent sequences of actions if the user makes it to atleast one event from the root action. If we included one-off events (where a user just lands on posthog.com but doesn't have a subsequent action), there could be a red dropoff visual on the first layer to show how many people fall off from the onset.

**To Reproduce Subsequent path**
1. If you have copy of production data use master and query paths
2. set date filter to last 30 days

**Expected behavior**
Should be more clear whether to completely drop the entire sequence or include the entire sequence to prevent weird rendering of a redundant action that skips the 2nd layer

**Screenshots**
<img width="1423" alt="Screen Shot 2020-05-06 at 3 55 28 PM" src="https://user-images.githubusercontent.com/13127476/81222372-2f601c80-8fb2-11ea-8945-679cc4045c8e.png">

**Comment by Twixes** [comment]
There is a new paths query builder since then.
