### ISSUE TITLE
Allow "zooming" into paths

### ISSUE THREAD

**Issue by macobo** [PostHog/posthog#7337]
## Is your feature request related to a problem?

I would love if the paths feature was more interactive and I could explore the data in an interactive way

## Describe the solution you'd like

Allow clicking on any nodes and vertices. When clicking on it, we "zoom in" - meaning that that the originating node becomes the new start point and we show paths originating from there.

If you e.g. click on "other pages" node then we show you the next top N pages at that level.

You can then use this to go as deep and wide you want in the graph

## Additional context

cc @EDsCODE @clarkus Thoughts regarding paths

**Comment by clarkus** [comment]
Very related to this somewhat stale PR https://github.com/PostHog/posthog/pull/6909
