### ISSUE TITLE
Incorrect reporting on Insights

### ISSUE THREAD

**Issue by paolodamico** [PostHog/posthog#7347]
## Bug description / Expected behavior

While exploring the app today, I found some important issues with reporting on insights:
1. When an insight is viewed from the "View mode" (i.e. when accessed by clicking on a saved insight) we don't trigger "insight viewed" or "insight analyzed". In the event, we should include an attribute that indicates the view mode too.
2. When opening an insight (funnel or otherwise) from saved insights into "View mode" we trigger `correlation viewed` & `correlation properties viewed` automatically even though correlation isn't actually viewed. CC @neilkakkar 
3. We don't report when a user has "compare previous" enabled

## How to reproduce

1. Open an insight from the saved insights list with the JS console open. See events triggered.

## Environment

- [x] PostHog Cloud
- [x] self-hosted PostHog (ClickHouse-based), version/commit: 1.30.0
- [ ] self-hosted PostHog (Postgres-based, legacy), version/commit: _please provide_

**Comment by neilkakkar** [comment]
For point 2, is this happening all the time for you? I can't seem to reproduce O.o
