### ISSUE TITLE
Event Stats => Show number of users who performed

### ISSUE THREAD

**Issue by oneshot-engineering** [PostHog/posthog#7348]
## Is your feature request related to a problem?

Yes, To be honest its becoming very hard to derive insights out of events data. For example, i was looking for how many users did a particular event to know hottest feature amongst our product. 

## Describe the solution you'd like
Insights => I would expect a breakdown by Event Name when i chose an Action assume that my action has dozens of events.
Event Stats => Today i see how many volume of events performed but its also helpful to show number of people performed

## Describe alternatives you've considered
Adding Manually each event to Insights and add breakdown by UserName. The results table gets very messy to process though

**Comment by neilkakkar** [comment]
Hey Venki! Trying to understand this a bit better: In the alternative, do you do the breakdown by UserName to get the specific users doing the event?

Would something like this work:

![image](https://user-images.githubusercontent.com/7115141/143418216-d4ef2aaf-af6b-4bd9-8ae4-adda65d31125.png)

(You can see here events sorted by number of users, and if you click on the bars, it tells you about all the people who did this event). If you then save this insight, you wouldn't have to recreate it every time.

**Comment by macobo** [comment]
Related: https://github.com/PostHog/posthog/issues/4332

**Comment by oneshot-engineering** [comment]
Yes i do breakdown by username. The bars you showed might work but it would show number of times that event occurred. I also wanted to see across how many unique users those events are spread across. 

Kind of 2 dimensional insights

**Comment by neilkakkar** [comment]
We had a chat offline, and it seems like having a Trends graph with *multiple bars* aggregated differently (by total count & unique users) seems to solve Venki's use case.

@oneshot-engineering let me know if there are still things missing, and we can re-open this?
