### ISSUE TITLE
Users are never Identified

### ISSUE THREAD

**Issue by peterjgrainger** [PostHog/posthog#7351]
## Bug description

I have an API in nodejs (without a single UI). I send events from the api on key actions and identify the user on sign up. With identify I set the `email` and `name` user properties. However, on the persons page the user is marked as unidentified, though I've sent the identify message (using node). The email is updated correct.

<img width="361" alt="Screenshot 2021-11-24 at 21 22 28" src="https://user-images.githubusercontent.com/1332395/143314794-1cdd0981-ced5-41f9-8133-71440f23b9b4.png">

## Expected behavior

User is marked as identified

## How to reproduce

1. Send a capture event from nodejs
2. identify using `identify` with nodejs using the distinct id.

## Environment

- [ ] PostHog Cloud
- [x] self-hosted PostHog (ClickHouse-based), version/commit:1.29
- [ ] self-hosted PostHog (Postgres-based, legacy), version/commit: _please provide_

**Comment by neilkakkar** [comment]
Hey Peter! Thanks, we're aware about this regression, and just got rid of it in the newest version (whenever you upgrade to latest - (or wait for the official patch release coming soon) - this would sort itself. There's no loss of data though, and you can continue identifying users as you have been.

**Comment by yakkomajuri** [comment]
For context, the PR that removed this was #7325

**Comment by peterjgrainger** [comment]
Thanks @neilkakkar sounds like my issue
