### ISSUE TITLE
Breakdown by action

### ISSUE THREAD

**Issue by jamesefhawkins** [PostHog/posthog#7357]
## Is your feature request related to a problem?

Twice on demo calls this week I've been asked:

"I want to see which features are the most popular"

## Describe the solution you'd like

We currently let you pick a given feature and plot its usage over time.

However, users are asking for "I don't know which features I want to see".

Perhaps this is something like in this filter:

<img width="892" alt="Screenshot 2021-11-25 at 11 36 27" src="https://user-images.githubusercontent.com/47497682/143434724-c243b51d-198b-454b-9889-d6f201b1baba.png">

Not having to select a specific event or action - maybe an additional "all" option for actions, then we tell users to use actions to "label" what they consider a feature being used as through the actions ux.

I suspect a basic tutorial would also then make sense on how to use this.

## Describe alternatives you've considered

Manually add all actions as individual series one at a time.

**Comment by macobo** [comment]
Related (duplicate?) of https://github.com/PostHog/posthog/issues/7348

Potential solution which needs scoping out: https://github.com/PostHog/posthog/issues/4332
