### ISSUE TITLE
Insight tooltips are painful

### ISSUE THREAD

**Issue by paolodamico** [PostHog/posthog#7370]
## Bug description

When hovering over a data point in an insight graph, tooltips are clunky. They don't show up unless you move the mouse around and are laggy.

## Expected behavior

Tooltips should feel very natural and intuitive.

## How to reproduce

1. Create any graph and play around with hovering near data points.

## Environment

- [x] PostHog Cloud
- [x] self-hosted PostHog (ClickHouse-based), version/commit: _please provide_
- [x] self-hosted PostHog (Postgres-based, legacy), version/commit: _please provide_

## Additional context
- Should be tackled together with #5473, #5698 & #7369.

**Comment by clarkus** [comment]
Related solution documented at https://github.com/PostHog/posthog/issues/4705

**Comment by alexkim205** [comment]
Closing issue in favor of #4705

**Comment by paolodamico** [comment]
I think it's worth having this issue around as the scope of #4705 is different (it encompasses different things). Though it does seem like they should be tackled together so will make a note in the main tracking issue #7412

**Comment by clarkus** [comment]
I put together a quick illustration of how tooltips can adjust to describe specific contexts in charts. 

![Tooltip specification](https://user-images.githubusercontent.com/254612/144331638-a4d11d13-ca7e-4e43-8cb5-2f9ace62682c.png)

https://www.figma.com/file/gQBj9YnNgD8YW4nBwCVLZf/PostHog-App?node-id=5597%3A36107

**Comment by paolodamico** [comment]
Love this! I think one key behavior here to consider (@alexkim205 FYI) is that we would now support both hovering over a specific point and moving over the time series.

**Comment by clarkus** [comment]
When the volume of distinct graph series becomes sufficiently high, we might consider disabling scrubbing a point in time and instead rely on the user scrubbing individual data points. Secondarily if breakdowns or groupings are applied, we can try to represent data always in that context. 

Imagine a scenario where you have three distinct graph series:
- Pageviews (a)
- Autocapture (b)
- Some action (c).

Apply a comparison time range:
- Pageviews (current) (a.1)
- Pageviews (previous) (a.2)
- Autocapture (current) (b.1)
- Autocapture (previous) (b.2)
- Some action (current) (c.1)
- Some action (previous) (c.2)

Apply a multi-cohort breakdown:
- Weekly active users
  - Pageviews (current) (a.1)
  - Pageviews (previous) (a.2)
  - Autocapture (current) (b.1)
  - Autocapture (previous) (b.2)
  - Some action (current) (c.1)
  - Some action (previous) (c.2)
- Monthly active users
  - Pageviews (current) (a.1)
  - Pageviews (previous) (a.2)
  - Autocapture (current) (b.1)
  - Autocapture (previous) (b.2)
  - Some action (current) (c.1)
  - Some action (previous) (c.2)

You can see how the scale of distinct graph series can easily balloon into a dense, difficult to parse chart. The difficulty comes when trying to describe all these items in the tooltip for a single point in time - 12 distinct data points. My question is how do we handle this? Some competitors disallow group by and comparison ranges. Others never let you scrub multiple groups simultaneously - you're always looking at a single dataset in the tooltip even though multiple are charted.

**Comment by alexkim205** [comment]
I agree I think we need to set an upper limit on this. For example, a breakdown of $current_url gives us an insane amount of rows that would be hard to fit into the tooltip. There's also a technical constraint where chartjs tooltips don't allow the cursor to enter the tooltip at all (tooltip will repaint on whichever vertical line the mouse intersects), which makes it hard to implement any scrolling container or "click to load more series" for tables that contain a lot of rows. 

I wonder if we can get around these constraints by showing only the most important pieces of information in the tooltips (i.e. first 10 rows?) and offloading the rest of the series information to the persons modal.

There's also @paolodamico's PR [here](https://github.com/PostHog/posthog/pull/7590) (below image) that gives you single/multi point resolution in the persons modal, which might mean we can be more lax with the tooltip data we display.

<img width="623" alt="Screen Shot 2021-12-16 at 11 14 08 AM" src="https://user-images.githubusercontent.com/13460330/146434111-7cabc5a1-0468-4681-bb49-f644c7ea55a9.png">
