### ISSUE TITLE
Significantly revamp the card view of insights

### ISSUE THREAD

**Issue by paolodamico** [PostHog/posthog#7374]
The card view of saved insights is pretty joyless.

- Insight axes show too small.
- Funnels are just a mess.
![image](https://user-images.githubusercontent.com/5864173/143502350-a8141d9d-f8e6-42c9-a3dc-910070058f7f.gif)
- Tooltips are shown.
- In general all graphs looked too zoomed-out to be readable.
- Empty/error states are shown weird.

**Comment by Twixes** [comment]
Re: funnels in your gif, it's not a general issue with the card view, but specifically with feature flag `5733-funnel-vertical-breakdown` (it's the same in dashboards) – we need to either fix it up or scrap it. See https://github.com/PostHog/posthog/issues/6140#issuecomment-974346823.

**Comment by clarkus** [comment]
This solution overlaps with #7517 a bit. There are updated insight card designs at https://www.figma.com/file/gQBj9YnNgD8YW4nBwCVLZf/PostHog-App?node-id=5931%3A32209. The main difference between insight cards and dashboard items is that dashboard items are customizable (size, personalization color). In the context of the insight list card view, we'd use the base 4x grid item size (316px) for each item in the list. 

![Dashboard Items SLASH Insight Cards](https://user-images.githubusercontent.com/254612/146059085-8203e34b-cd45-429c-8b42-e4a0782a271a.png)
