### ISSUE TITLE
Remove `funnelLogic` mounting from all `DashboardItem`s.

### ISSUE THREAD

**Issue by mariusandra** [PostHog/posthog#7376]
## Bug description

The `<DashboardItem>` component is explicitly connected to `funnelLogic`, just to display a different empty state:

https://github.com/PostHog/posthog/blob/fbba78718cf97f3f611c457a5ec9b29d860dbf84/frontend/src/scenes/dashboard/DashboardItem.tsx#L222

This means we mount a new `funnelLogic` for every dashboard item, no matter what type. This has caused some problems in the past (funnelLogic's afterMount did too many things), and is just wasteful.

## Expected behavior

We should only mount `insightLogic` with a dashboard item. Only when it's actually a funnel, should we mount `funnelLogic`.

## Additional context

This is the last undocumented point from the issue https://github.com/PostHog/posthog/issues/6118#issuecomment-979455195

**Comment by paolodamico** [comment]
Should this be part of the "General insights" theme on this sprint (1.31.0 2/2)?

**Comment by mariusandra** [comment]
I think it could be. Added to the list.
