### ISSUE TITLE
The funnel logic exposes too many versions of its data structure

### ISSUE THREAD

**Issue by pauldambra** [PostHog/posthog#7385]
## Bug description

The funnel logic has a single input from the API and then generates several different pieces of data from it. The "final" shape of data it produces is a superset of all the data it holds. 

It exposes all the interstitial data shapes it creates and so its consumers are very tightly coupled to its implementation.

Adding tests for it in #7353 had to be backed out as a result because they added 1000s of lines of test code.

We should expose one data structure for funnels (or at least one per type of funnel)

### This is a subset of the selectors that expose data 

![image](https://user-images.githubusercontent.com/984817/143591788-4923e4df-5eec-4b0f-a161-585a01d1b6a0.png)

**Comment by neilkakkar** [comment]
+1! I think a mistake we made early on was to try and smush the funnel results, as well as funnel breakdown results. Even if they use the same API call, the result shape is very different.

Separating them out means we then get: `stepsWithConversionMetrics` as the main selector, and then `breakdownStepsWithConversionMetrics` for a breakdown funnel, and can get rid of most intermediaries trying to convert between the two :$

**Comment by pauldambra** [comment]
> a mistake we made early 

Much easier to look at the finished thing and review it than to make it. Wouldn't be worth improving if it wasn't valuable 💖
