### ISSUE TITLE
Funnel Breakdown should only allow selectable properties

### ISSUE THREAD

**Issue by pauldambra** [PostHog/posthog#7392]
## Bug description

If you have a funnel where the entities for each step do not have the same type and you try to add a break down by a property from an entity not at step 1. You get a single breakdown with the empty string as its value

### a funnel with sequential order breaking down by a property on entity 2

<img width="1503" alt="breakdown-issue-sequential" src="https://user-images.githubusercontent.com/984817/143657276-73658b5b-c6cc-429e-a7e1-8b65ac3e2413.png">

### the result for that query

<img width="463" alt="breakdown-issue-bad-result" src="https://user-images.githubusercontent.com/984817/143657273-e82ba8ed-3f1c-4f4b-9162-7a3ec4ccc61f.png">

### a funnel with any order moving the second entity into position 1 and breaking down by its property 

<img width="1496" alt="breakdown-issue-any-order" src="https://user-images.githubusercontent.com/984817/143657269-65fb9c51-c786-4c66-8cf8-a75ede7e449b.png">

### and its result

<img width="473" alt="breakdown-issue-good-result" src="https://user-images.githubusercontent.com/984817/143657274-ef223692-45e0-4abd-ab53-7078dda10f86.png">

## Expected behavior

The taxonomic filter only shows properties from the first entity or that are common to all entities in the filter

## How to reproduce

1. do a page view
2. send an event with a custom name and property
2. create a funnel for pageview sequentially followed by the custom event
3. set the funnel to breakdown by the custom property
4. see the result is empty
5. change the funnel to any order
6. flip the position of the two events
7. see the result is not empty

## Environment

- [ ] PostHog Cloud
- [ ] self-hosted PostHog (ClickHouse-based), version/commit: _please provide_
- [ ] self-hosted PostHog (Postgres-based, legacy), version/commit: _please provide_

## Additional context

The code that sends only one entity is here: https://github.com/PostHog/posthog/blob/master/ee/clickhouse/queries/funnels/base.py#L542

The SQL generated is like

```
SELECT groupArray(value) FROM (
    SELECT
        array(trim(BOTH '"' FROM JSONExtractRaw(properties, 'custom property'))) AS value,
        count(*) as count
    FROM events e


    WHERE
        team_id = 1 AND event = '$pageview' AND timestamp >= '2021-11-19 00:00:00' AND timestamp <= '2021-11-26 23:59:59'
    GROUP BY value
    ORDER BY count DESC
)
```

when `custom property` is not on `$pageview`

**Comment by neilkakkar** [comment]
Hey Paul! This was actually by conscious design: It didn't make sense to breakdown by properties that aren't common to all the things in the funnel.

Happy to revisit though if there's a valid usecase?

**Comment by pauldambra** [comment]
It was the first thing I wanted to do. :) https://app.posthog.com/insights/moAf5ved?insight=FUNNELS&date_from=-30d&actions=%5B%7B%22id%22%3A%228529%22%2C%22name%22%3A%22404%20Not%20Found%20on%20posthog.com%22%2C%22type%22%3A%22actions%22%2C%22order%22%3A0%7D%5D&events=%5B%7B%22id%22%3A%22pineapple_on_pizza_survey%22%2C%22name%22%3A%22pineapple_on_pizza_survey%22%2C%22type%22%3A%22events%22%2C%22order%22%3A1%7D%5D&display=FunnelViz&interval=day&properties=%5B%5D&filter_test_accounts=true&funnel_to_step=1&funnel_viz_type=steps&funnel_window_interval_unit=hour&funnel_window_interval=3&hiddenLegendKeys=%7B%22events%2Fpineapple_on_pizza_survey%2F1%2FSwitzerland%22%3Atrue%7D&exclusions=%5B%5D&breakdowns=%5B%7B%22type%22%3A%22event%22%2C%22property%22%3A%22does_pineapple_go_on_pizza%22%7D%5D&breakdown_type=event&funnel_from_step=0

**Comment by neilkakkar** [comment]
Interesting, why not try [this on a Trend graph](https://app.posthog.com/insights/moAf5ved/edit?insight=TRENDS&date_from=-30d&actions=%5B%5D&events=%5B%7B%22id%22%3A%22pineapple_on_pizza_survey%22%2C%22name%22%3A%22pineapple_on_pizza_survey%22%2C%22type%22%3A%22events%22%2C%22order%22%3A0%7D%5D&interval=day&properties=%5B%5D&filter_test_accounts=true&funnel_to_step=1&funnel_window_interval_unit=hour&funnel_window_interval=3&hiddenLegendKeys=%7B%22events%2Fpineapple_on_pizza_survey%2F1%2FSwitzerland%22%3Atrue%7D&exclusions=%5B%5D&breakdown=does_pineapple_go_on_pizza&breakdown_type=event&funnel_from_step=0&new_entity=%5B%5D&display=ActionsBarValue)?

or, put another way, what question is that insight answering?

**Comment by pauldambra** [comment]
> Interesting, why not try this on a Trend graph?

I started trying to do a multi breakdown :)

Maybe this is similar to #5381 and the confusion is I was presented with options to select which couldn't provide me with useful results

**Comment by neilkakkar** [comment]
Ahhh, I see how we got here now!

That point definitely makes sense: it's confusing when presented with options that don't make sense.

---

re: supporting this, are we on the same page about there not being a meaningful question that's answered by breakdowns on properties that aren't common to all entities?

**Comment by pauldambra** [comment]
> re: supporting this, are we on the same page about there not being a meaningful question that's answered by breakdowns on properties that aren't common to all entities?

I can't phrase what I would make so I'll assume I don't have a full thought and bow to your expertise...

Particularly as "only show properties that _should_ be selectable" is IMO much easier to implement!
