### ISSUE TITLE
Update feature flag library code snippets in the app

### ISSUE THREAD

**Issue by jamesefhawkins** [PostHog/posthog#7394]
## Is your feature request related to a problem?

In the app, we make it look like we have Javascript, Python and an API support for feature flags. From looking at this, I'd assume there are no other options...

<img width="1325" alt="Screenshot 2021-11-27 at 11 43 59" src="https://user-images.githubusercontent.com/47497682/143679850-64cb0426-e94f-4444-99b6-8a45a0abf72b.png">

However, we have a lot more libraries for feature flags. From our docs we declare:

* Javascript
* NodeJS
* Python
* PHP
* Ruby
* Golang

## Describe the solution you'd like

For a mini-language select button in the app that then provides the code snippet in the right language, for all of the above + API.

## Describe alternatives you've considered

Read the docs instead of the app. I think currently this is just poor UX.

## Additional context

It'd be nice to also clarify how to deal with feature flag variants within the code snippet, if multivariate feature flags are chosen.

**Comment by clarkus** [comment]
This overlaps a ton with ongoing work for group analytics. I put together an updated code component that solves for this scenario. cc @macobo 

![code sample](https://user-images.githubusercontent.com/254612/143936202-5c343262-1a26-4bd3-bc9e-b6d30989f426.png)

https://www.figma.com/file/gQBj9YnNgD8YW4nBwCVLZf/PostHog-App?node-id=5545%3A30469

**Comment by kefranabg** [comment]
I just submitted a PR for that one 👍 

https://github.com/PostHog/posthog/pull/10621

**Comment by asadath1395** [comment]
@jamesefhawkins I believe this is already implemented, can we close this?
