### ISSUE TITLE
Discussion - Adjust naming of events & actions tabs

### ISSUE THREAD

**Issue by clarkus** [PostHog/posthog#7416]
**Context**
![Screen Shot 2021-11-29 at 5 21 1](https://user-images.githubusercontent.com/254612/143968638-31ac2cca-4dcf-44d5-8d37-e2b24abe2454.png)

While working on events for a related issue, it struck me that these tabs aren't named as meaningfully as they could be. This feature is divided into `events`, `actions`, `event stats`, and `property stats`. Of these four categories, `actions`, `event stats`, and `property stats` are most alike in that they are a distinct list of items. They are not sorted by time and there is only one instance of each item in the list. `events` is actually performing much more like a somewhat-live event log. Likewise `stats` is not really a meaningful name - it just distinguishes the event log from the distinct list of events. 

**The proposal I'd like to discuss** 
Let's rename these tabs to be more meaningful for the context, and double down the event log as a semi-live list of events being ingested into posthog. This naming change would make it more obvious how the event log differs from the other sections, and will give us a bit more freedom to diverge from other listing patterns there. 

<img width="394" alt="Screen Shot 2021-11-29 at 5 33 39 PM" src="https://user-images.githubusercontent.com/254612/143969593-74176673-c68c-4e92-aac6-6e7f4728935a.png">

**More context and a longer term goal** 
Recording event lists are very related to this context change. In that feature we have scenario where you can look at a portion of a list that is "out of date" or somehow differing in time context from other items in the list. To get around this, we implemented a "jump to current time" action that makes it easy to get back to the current context of the recording. The parallel in events is that new events can be ingested and inserted above your current context in the list. We could use a similar pattern to "jump to" the latest / current context if this feature felt more live. 

<img width="646" alt="Screen Shot 2021-11-29 at 5 43 52 PM" src="https://user-images.githubusercontent.com/254612/143970449-6841b989-055f-4ddc-af5d-59321a134b25.png">

We already insert these events in a semi-live fashion. What if we continue doing this, but drop the prompt to add them to the table. Instead we'll insert them above the most recent event on some recurring interval and prompt the user to jump to the most recent context. It's a small but meaningful change. It sets a more accurate expectations with our naming, should result in less prompts to the user, and provides multiple events that lead to viewing the latest events (now I can click the prompt, or just scroll up to see new stuff). Thoughts?

**Comment by macobo** [comment]
One other suggestion is combining event stats + actions page. While the creation flow is different they both represent similar things for the end user.

> What if we continue doing this, but drop the prompt to add them to the table. Instead we'll insert them above the most recent event on some recurring interval and prompt the user to jump to the most recent context.

Note we used to have this but it kind of sucked. The problem you run into is interacting with the table - if stuff is constantly jumping around it looks beautiful but becomes impossible to use. Adding extra buttons to pause etc doesn't make for a great UX either.

**Comment by pauldambra** [comment]
+1 for better labels here!

> One other suggestion is combining event stats + actions page. While the creation flow is different they both represent similar things for the end user.

This makes a lot of sense if our users see them as one (or very similar) thing!

**Comment by mariusandra** [comment]
Agree with the cleanup, yet I'm not sure moving a core feature of PostHog ("tagged events" aka "actions") into the 3rd tab of a 2nd level menu is the best thing we can do to aide its discovery.

There's a lot that can be done to clean up these four pages, documented in various issues, and I won't pretend to know the right answer here.

- https://github.com/PostHog/posthog/issues/5240
- https://github.com/PostHog/posthog/issues/5546

**Comment by Twixes** [comment]
I agree that the tabs as-is aren't living up to their potential! One thing that I'm worried about though actually is exposing Events stats and Properties stats the way they are now – they are very rough UI-wise and don't have the basic feature of definition deletion yet. Basically what Marius mentions.
Re Karl: It also seems to me that Events stats (called just Events here) have a significantly different purpose from Actions and it may be _more_ confusing to combine them into one. Events are registered automatically (defined in API usage and only assigned metadata in the app), while Actions are built _on top_ of Events (defined in the app). They're used very similarly in the end, sure, but at the definition level they differ fundamentally.

**Comment by Twixes** [comment]
@clarkus Did you maybe get to mocking up the Event log page in Figma?

**Comment by macobo** [comment]
Sorry for the side-tracking!

> Re Karl: It also seems to me that Events stats (called just Events here) have a significantly different purpose from Actions and it may be more confusing to combine them into one. Events are registered automatically (defined in API usage and only assigned metadata in the app), while Actions are built on top of Events (defined in the app). They're used very similarly in the end, sure, but at the definition level they differ fundamentally.

Agreed that this will not be a trivial change! However them being used similarly _is_ the reason to merge them as users need a proper way to do data management and having a unified interface for it is the way to go. 

Think of features like verified events, hiding events, merging events, statistics etc. The need from users for events and actions are identical there. Actions are functionally events but with more bells and whistles attached which helps support more complicated flows.

**Comment by clarkus** [comment]
> @clarkus Did you maybe get to mocking up the Event log page in Figma?

<img width="855" alt="Screen Shot 2021-11-30 at 8 33 06 AM" src="https://user-images.githubusercontent.com/254612/144088194-d01c8922-b036-4893-afee-5557ab4e5a74.png">

I have https://www.figma.com/file/gQBj9YnNgD8YW4nBwCVLZf/PostHog-App?node-id=5562%3A32047 but this doesn't account for the alternate loading concept. I am still reading through the feedback here to better understand the concerns. I will circle back with the loading state next.

**Comment by clarkus** [comment]
> Note we used to have this but it kind of sucked. The problem you run into is interacting with the table - if stuff is constantly jumping around it looks beautiful but becomes impossible to use. Adding extra buttons to pause etc doesn't make for a great UX either.

@macobo the experience I had in mind wouldn't trigger jumping or kind of offset changes. It also wouldn't have any secondary pausing actions or anything. It's literally a list of events that appends new items to the top. We'd always maintain the user's current vertical offset such that they don't lose context for the event they're looking at. They would see the indicator show when there are new events - clicking this would scroll to the top of the list. Otherwise the user could just scroll manually to see the new events. It'd come down to implementation details to really make the experience great, but I think it could work. 

> Agree with the cleanup, yet I'm not sure moving a core feature of PostHog ("tagged events" aka "actions") into the 3rd tab of a 2nd level menu is the best thing we can do to aide its discovery.

@mariusandra I think it's just as discoverable, just lower priority. We can definitely reorder to something more meaningful. There is a stale, but mostly complete design for refactoring events at https://www.figma.com/file/9yWtngNb1AIuf6KmXaEPJA/?node-id=1084%3A136531. This is a direct response #5546

**Comment by macobo** [comment]
> It'd come down to implementation details to really make the experience great, but I think it could work.

Important technical constraint here is that currently these event tables queries account for 85% of all the queries that reach the backend (https://metrics.posthog.com/d/vo7oCVZ7z/clickhouse-queries-by-endpoint) and while relatively cheap, we should:

1. Pause this after a while
2. Pause when the tab is inactive

Before committing though - what are the usecases for the table, what is the usecase that the live-ler table solves better?

**Comment by clarkus** [comment]
> Important technical constraint here is that currently these event tables queries account for 85% of all the queries that reach the backend (https://metrics.posthog.com/d/vo7oCVZ7z/clickhouse-queries-by-endpoint) and while relatively cheap, we should:

This is important context that I didn't have. There's a secondary usage concern that isn't really driven by the user experience as much as it is the need for performance / reasonable usage. My idea is purely to give the tabs more meaningful names, distinguish the tables and simplify the experience for that event log. I wasn't accounting for those technical constraints. 🙃

**Comment by Twixes** [comment]
Not relevant as we have Data Management and Live Events now.
