### ISSUE TITLE
Billing page is going out of view-port

### ISSUE THREAD

**Issue by sankalpdomore** [PostHog/posthog#7419]
## Bug description

The billing page's "Current event usage" section goes out of viewport horizontally. Rounding off the % will fix this. 

![CleanShot 2021-11-30 at 13 27 46@2x](https://user-images.githubusercontent.com/18334593/144007948-f13a247e-da9a-40df-8ef1-a31292241c16.png)

## Expected behavior

Shouldn't go out of viewport.

## How to reproduce

1. Go to https://app.posthog.com/organization/billing on desktop

## Environment

- [x] PostHog Cloud
- [ ] self-hosted PostHog (ClickHouse-based), version/commit: _please provide_
- [ ] self-hosted PostHog (Postgres-based, legacy), version/commit: _please provide_

**Comment by macobo** [comment]
Thanks for the report! Created a quick PR to fix the issue: https://github.com/PostHog/posthog/pull/7420
