### ISSUE TITLE
Pie chart values should be on top of the graphic

### ISSUE THREAD

**Issue by jamesefhawkins** [PostHog/posthog#745]
**Describe the bug**

<img width="588" alt="Screenshot 2020-05-12 at 11 12 25" src="https://user-images.githubusercontent.com/47497682/81672073-8a29c600-9441-11ea-9334-a3e36c5b5fd7.png">

**To Reproduce**
1.  Create a pie chart with no breakdown (ie just 1 category)
2.  Look at the numbers

**Expected behavior**
The number should appear on top of the graphic so it's readable.

**Screenshots**
See above

**Desktop (optional: please complete the following information):**
 - OS:
 - Browser: 
 - Version: 

**Smartphone (optional: please complete the following information):**
 - Device: 
 - OS: 
 - Browser 
 - Version 

**Additional context*

**Comment by mariusandra** [comment]
The fix for this went in when Tim merged #746
