### ISSUE TITLE
Person created_at / first seen handling

### ISSUE THREAD

**Issue by tiina303** [PostHog/posthog#7454]
Currently created_at is used either as event timestamp or as current timestamp, this is confusing and wouldn't work well when we do migrations for example.

See https://github.com/PostHog/posthog/pull/7109#discussion_r758363070

Ideally upon ingestion we update this value always to the oldest timestamp we see tied to this person, this would make things work properly for out of order ingestion too. This likely won't increase the number of updates/complexity by much, but should be taken into account.

**Comment by macobo** [comment]
We now also have groups as well, which shares logic with persons. Don't let them drift apart.
