### ISSUE TITLE
Chunk loading issues causing white page of death on cloud

### ISSUE THREAD

**Issue by timgl** [PostHog/posthog#7463]
## Bug description

When we deploy our loadbalancers hit different versions of our app, causing chunks to be missing and 404'ing.

## Expected behavior

We should not 404

## How to reproduce

1. Deploy
2. Reload the page
3. Sometimes you'll get stuck here

## Environment

- [ ] PostHog Cloud

## Additional context

From slack:

Not sure if the right channel or this should go in #dev, but just wrapped up a call with Karl where we talked through esbuild and our 404 caching issues. Few thoughts:
We couldn’t figure it out, but it seems that caching under /static cloudflare is now disabled, even though it’s enabled in the interface. curl --head doesn’t show any overridden cache headers.
Our collectstatic approach is broken, as it takes a files such as chunk-12HASH34.js, and chunk-12HASH34.map.js… and then adds a chunk on top, resulting in the screenshot.
A solution for #2 cold be a true solution for #1 as well, as Karl found this project, which replaces collectstatic and can also upload the static assets to S3. However instead of putting a CDN in front of S3, this collectfast itself can make a request to S3 and serve a previously generated asset, if it’s not found locally.

- [Link to the above discussion in slack](https://posthog.slack.com/archives/C01MM7VT7MG/p1636535363460900)
- [Discussion regarding using sticky sessions on the AWS load balancer target group as a quick fix](https://posthog.slack.com/archives/C01MM7VT7MG/p1637057341134000?thread_ts=1636993808.117100&cid=C01MM7VT7MG) , although this comes with its own risks. It's also noted that status codes are perhaps not ideal for static file misses.
-

**Comment by macobo** [comment]
cc @mariusandra - I believe this is now fixed? :crossed_fingers:

**Comment by mariusandra** [comment]
I think it is. If it appears again, we know what button to click.

**Comment by guidoiaquinti** [comment]
I confirm this issue should be now fixed since we introduced `app-static.posthog.com`
