### ISSUE TITLE
ALLOWED_IP_BLOCKS: Forbidden accessing endpoint for capturing session recordings (/s route).

### ISSUE THREAD

**Issue by rameshlohala** [PostHog/posthog#7481]
## Bug description
When restricted access to posthog by IP, the endpoint for capturing session recordings (/s) throws 403 (Forbidden) http response when accessing from IPs other than IPs in `ALLOWED_IP_BLOCKS` 

http response:
```
Your IP is not allowed. Check your ALLOWED_IP_BLOCKS settings. If you are behind a proxy, you need to set TRUSTED_PROXIES. See https://posthog.com/docs/deployment/running-behind-proxy
```

## Expected behavior
`/s` endpoint should return 200 status

## How to reproduce

1. Make sure you have secured posthog by Restrict access by IP
2. Enable user session recording on project settings page
3. send post request to `https://<POSTHOG-HOST>/s/` endpoint 

## Environment

- [ ] PostHog Cloud
- [x] self-hosted PostHog (ClickHouse-based), version: 1.30.0 (hosted in AWS managed k8s)
- [ ] self-hosted PostHog (Postgres-based, legacy), version/commit: _please provide_

**Comment by macobo** [comment]
That is expected behavior - `ALLOWED_IP_BLOCKS` is useful when you're proxying data to posthog through another service. Can you elaborate what's your usecase for `ALLOWED_IP_BLOCKS` and sending data directly?

**Comment by rameshlohala** [comment]
@macobo As per the list of public endpoints here https://posthog.com/docs/self-host/configure/running-behind-proxy#public-endpoints, the session recording endpoint(/s) should not be restricted even if the posthog UI is secured by IP address. It is working fine for other endpoint like /decide, /e, /capture etc.

I just wanted to say that, the session recording endpoint should not be blocked even when the restriction by IP is enabled. may be `/s` had forgotten. similar to this comment in the issue: https://github.com/PostHog/posthog/issues/528#issuecomment-621082972
