### ISSUE TITLE
Organization (Groups) modal click through is confusing

### ISSUE THREAD

**Issue by jamesefhawkins** [PostHog/posthog#7503]
## Is your feature request related to a problem?

When you click the link (rather than the expand icon) here:
<img width="830" alt="Screenshot 2021-12-03 at 13 14 29" src="https://user-images.githubusercontent.com/47497682/144608492-2c89793f-7d56-4ecc-9c00-a9c35e14e7fb.png">

I'd expect it to take me to a page for that specific organization (in the same way it does for persons). Whereas it takes me to a big list instead.

**Comment by macobo** [comment]
Related: https://github.com/PostHog/posthog/issues/7096

Possibly fixed in https://github.com/PostHog/posthog/pull/7523

**Comment by macobo** [comment]
Closing for now - re-open if this is still the case!
