### ISSUE TITLE
Clarify 10K events/month limit when a billing plan is active (Cloud)

### ISSUE THREAD

**Issue by samwinslow** [PostHog/posthog#7511]
## Bug description

Support requests come in fairly often where users are confused by the below UI. I think a lot of users get paranoid and assume ingestion will stop when they hit 10K, or that their license is not working properly.

![image](https://user-images.githubusercontent.com/4645779/144653349-ef7ebe6e-c335-403b-8a09-08a88e2539c1.png)

## Expected behavior

- Event-based pricing model described in the help text below the colored bar
- Upper bound of the bar increases to 1M when a billing plan is active, and the language changes to say that they won't be charged until 1M events

### Pricing / credit card requirement model

I believe our current model is this (please correct me if I'm wrong @timgl @jamesefhawkins)

_First 1M events free, no credit card required below 10,000 events. Credit card required between 10,000 - 999,999 events, but not charged until 1M._

## Environment

- [x] PostHog Cloud
- [ ] self-hosted PostHog (ClickHouse-based), version/commit: _please provide_
- [ ] self-hosted PostHog (Postgres-based, legacy), version/commit: _please provide_

**Comment by RubenVot** [comment]
I'm testing Posthog in my company. I arrived to this issue trying to understand why credit card was required if 1M events should be free.
So from user perspective yes, a bit more of information would be appreciated :)
Thanks!

**Comment by timgl** [comment]
@kappa90

**Comment by pauldambra** [comment]
had this request about this too https://posthoghelp.zendesk.com/agent/tickets/407 (moved to PostHog: https://us.posthog.com/project/2/support/tickets/3707)

Would be great to clarify that page
