### ISSUE TITLE
Trigger onAction only for specific action -> plugin mappings

### ISSUE THREAD

**Issue by yakkomajuri** [PostHog/posthog#7528]
Currently, if a plugin implements the `onAction` function, it will receive every action triggered.

However, a more optimal approach would be to receive only actions that the user specifies they want the plugin to run on, as is the case with webhooks.

Hence, here's the rough solution I'm envisioning:

On the action page, around where the webhook stuff is, add a section allowing the user to specify what plugins to run on this action. The options here have to pull from plugin capabilities, such that only plugins that have `onAction` appear.

The user would then specify these, and they could probably be stored in an array of plugin IDs as a new column on the action.

Then, on the plugin server side, when running `onAction`, we only run it on plugins that are specified in that column. 

@weyert was considering picking this up

**Comment by weyert** [comment]
Yeah, happy to pick this one up after I completed my `tags` PR :)
