### ISSUE TITLE
Properties Stats don't seem to be reporting

### ISSUE THREAD

**Issue by MarkBennett** [PostHog/posthog#7529]
## Bug description

For the last 30+ days, I've not been seeing any Properties Stats in my application. As far as I can tell the PostHog JS is up to date and valid, so I'm confused as to what's going on as nothing I'm aware of would have changed, and no data seems to be coming in regardless of browser or platform.

This is what it looks like for me...

![Screen Shot 2021-12-06 at 10 39 31 AM](https://user-images.githubusercontent.com/61872/144894655-209e4d60-af4a-4306-88a5-be67bbffd8e9.png)

## Expected behavior

I'd expect to see properties that help me determine what browsers and platforms people are using.

## How to reproduce

1. Visit the website (clhbid.com) in a browser
2. See visit and events appear as expected
3. Visit https://app.posthog.com/events/properties
4. See all properties report 0, or empty

## Environment

- [X] PostHog Cloud
- [ ] self-hosted PostHog (ClickHouse-based), version/commit: _please provide_
- [ ] self-hosted PostHog (Postgres-based, legacy), version/commit: _please provide_

## Additional context
This did work in the past, but I'm not sure what's breaking.

**Comment by weyert** [comment]
Yes, I am seeing the same issue
