### ISSUE TITLE
Bring back proper error messages when queries error

### ISSUE THREAD

**Issue by timgl** [PostHog/posthog#7530]
## Bug description

Right now we say 'There are no matching events for this query' which is super misleading as in reality the query has errored

## Expected behavior

We used to have a big red error message that showed up, which would at least be more informative and could help users optimise their queries (smaller timeframes etc)

## How to reproduce

1.
2.
3.

## Environment

- [ ] PostHog Cloud
- [ ] self-hosted PostHog (ClickHouse-based), version/commit: _please provide_
- [ ] self-hosted PostHog (Postgres-based, legacy), version/commit: _please provide_

**Comment by macobo** [comment]
Is this trends-specific? We do swallow errors in trends explicitly: https://github.com/PostHog/posthog/blob/master/ee/clickhouse/queries/trends/clickhouse_trends.py#L47-L53

**Comment by timgl** [comment]
Yep I think trend specific. I'm working on a fix now. Not sure why we started swallowing those exceptions
