### ISSUE TITLE
Export Funnel CSV

### ISSUE THREAD

**Issue by EDsCODE** [PostHog/posthog#755]
**Is your feature request related to a problem? Please describe.**
Currently, funnel export csv doesn't do anything except redirect. After #751 the actual button will be removed. There should be csv functionality.

**Describe the solution you'd like**
1. Add the action button back and export funnel with nicely formatted people information. This will require some organization of columns inside the csv because there are three separate sets of people.
2. Only allow exporting people when viewing the specific funnel page so users can export a set of people per step within the funnel rather than all 3 steps.

**Describe alternatives you've considered**
Considered above

**Additional context**

***Thank*** you for your feature request - we love each and every one!

**Comment by paolodamico** [comment]
We no longer have this functionality and it doesn't seem to be requested by users, closing for now.
