### ISSUE TITLE
Sorting on events table

### ISSUE THREAD

**Issue by paolodamico** [PostHog/posthog#7568]
## Is your feature request related to a problem?

I'd like to understand what a certain user did first when using my app.

## Describe the solution you'd like

On the person page, I'd like to be able to sort the events or recordings table based on the date. Important to note this is not just client-side sorting based on the loaded results, but sorting based on all the information available in the DB.

## Describe alternatives you've considered

- Should we expand the scope of this to enable sorting on any column with the new LemonTable?
- I could find out this information (at least for events) doing some witchery with trends, but it'd be quite hard to get all the context anyways.

## Additional context
- Originally requested by focus customer [here](https://posthog.slack.com/archives/C01F31E9PRD/p1638830650071400).

**Comment by neilkakkar** [comment]
More context:
I think the focus customer said the "First Time Event Tracker" plugin was good enough [for this usecase](https://posthog.slack.com/archives/C01F31E9PRD/p1638883498080900?thread_ts=1638883330.079200&cid=C01F31E9PRD)

**Comment by paolodamico** [comment]
Related to this, a user has expressed the need for filtering events based on a date range. Context: they use this list to debug events coming in, some events happen sporadically and even weeks ago, therefore a date range filter is critical.
