### ISSUE TITLE
Impossible to understand funnels on pre-saved Insight without editing

### ISSUE THREAD

**Issue by jamesefhawkins** [PostHog/posthog#7585]
## Bug description

[Try this.](https://app.posthog.com/insights/ZVN0dJrj?insight=FUNNELS&actions=%5B%5D&events=%5B%7B%22id%22%3A%22%24pageview%22%2C%22name%22%3A%22%24pageview%22%2C%22type%22%3A%22events%22%2C%22order%22%3A0%7D%2C%7B%22id%22%3A%22%24pageview%22%2C%22name%22%3A%22%24pageview%22%2C%22type%22%3A%22events%22%2C%22order%22%3A1%7D%2C%7B%22id%22%3A%22%24pageview%22%2C%22name%22%3A%22%24pageview%22%2C%22type%22%3A%22events%22%2C%22order%22%3A2%7D%2C%7B%22id%22%3A%22%24pageview%22%2C%22name%22%3A%22%24pageview%22%2C%22type%22%3A%22events%22%2C%22order%22%3A3%7D%5D&display=FunnelViz&interval=day&properties=%5B%5D&funnel_to_step=1&funnel_viz_type=steps&exclusions=%5B%5D&funnel_from_step=0)

[Or this](https://app.posthog.com/insights/TFYSTVSg?events=%5B%7B%22id%22%3A%22user%20signed%20up%22%2C%22math%22%3Anull%2C%22name%22%3A%22user%20signed%20up%22%2C%22type%22%3A%22events%22%2C%22order%22%3A0%2C%22properties%22%3A%5B%5D%2C%22custom_name%22%3A%22User%20signed%20up%22%2C%22math_property%22%3Anull%7D%5D&actions=%5B%7B%22id%22%3A4912%2C%22math%22%3Anull%2C%22name%22%3A%22Discover%20Learning%20-%20core%20analytics%22%2C%22type%22%3A%22actions%22%2C%22order%22%3A1%2C%22properties%22%3A%5B%5D%2C%22custom_name%22%3Anull%2C%22math_property%22%3Anull%7D%5D&display=ActionsLineGraph&insight=FUNNELS&interval=week&date_from=yStart&exclusions=%5B%5D&properties=%5B%5D&funnel_to_step=1&funnel_viz_type=trends&funnel_from_step=0&filter_test_accounts=true&date_to).

I can't tell what the exact events in each step are without editing these insights.

<img width="1963" alt="Screenshot 2021-12-08 at 17 46 46" src="https://user-images.githubusercontent.com/47497682/145257699-004eb56d-f640-4a61-8454-e94682408f7b.png">
<img width="841" alt="Screenshot 2021-12-08 at 17 49 37" src="https://user-images.githubusercontent.com/47497682/145258090-db94f020-a0d9-4266-823e-5a1f9b7545cd.png">
(the latter I can guess from the title, but it's still not easy to look up what the filter settings are)

I know if the graph series were labeled very precisely this would be easy, but I bet the usage of these labels is relatively low, so users will be getting confused. Maybe we should default to autogenerating the title from the event selection?

## Expected behavior

I can tell what the steps mean without having to 'Edit' it.
Perhaps some way of expanding something to show me which events/filters are applied without editing?

**Comment by clarkus** [comment]
Related https://github.com/PostHog/posthog/issues/5052

**Comment by clarkus** [comment]
I've been thinking about this a bit while working on improvements for dashboards. I think there are a lot of attributes we can summarize easily, but translating filters, especially series filters and formula, could be challenging. We're also working on improving taxonomy which got me thinking about our summary cards. I put together some concept insight summary cards just to see how much could be succinctly described. Not exactly targeted at the specific instances you mentioned, but definitely the same problem area. I could see this also being applied to insight page headers in some way. Feel free to leave feedback in figma if you have any. 

![Insight Summary Cards](https://user-images.githubusercontent.com/254612/145316064-42a4825f-938c-47a3-b682-4406ef6f1080.png)

https://www.figma.com/file/gQBj9YnNgD8YW4nBwCVLZf?node-id=5788:46748#131668458

**Comment by jamesefhawkins** [comment]
Feedback as a user myself: I've found the insights search very useful, and these cards would enable better searching too (given the extra information in them compared to just titles).

**Comment by paolodamico** [comment]
I would consider prioritizing this next sprint (and dropping something like the card view revamp). Thoughts @mariusandra ?
