### ISSUE TITLE
Move backend code from ee/ to posthog/ directory

### ISSUE THREAD

**Issue by macobo** [PostHog/posthog#7591]
## Is your feature request related to a problem?

We're removing postgres from the code base and moving things from ee to MIT licensed code.

## Describe the solution you'd like

Moving code is going to cause major code conflicts. 

To disrupt peoples work minimally, I'd do this in a few stages:
1. First, create "dummy" modules in posthog/clickhouse/ that are blank files containing `from ee.clickhouse.mymodule import *`. 
    - Ex: For `ee/clickhouse/client.py` we'd create `posthog/clickhouse/client.py` with `import * from ee/clickhouse/client.py` as its content.
    - Note: Only do this for non-paid features, so excluding things like correlation analysis and groups.
2. Update imports in existing code.
3. Ask people to get their branches in in a week. New and changed files should go under `posthog/clickhouse`.
4. Move code over as well in chunks, avoiding touching files currently moved in PRs.
5. Start removing unneeded code - `is_clickhouse_enabled()`, queries, api endpoints, etc.
6. Profit

Note that this would likely break foss repo in-between steps 1-3 and 

## Describe alternatives you've considered

Do it in one go and create conflicts for all PRs.

## Additional context

cc @timgl who was advocating for this.

We should start this _after_ the next release.

**Comment by guidoiaquinti** [comment]
I think this will be part of https://github.com/PostHog/posthog/issues/6662

**Comment by EDsCODE** [comment]
I started with removing the is_clickhouse_enabled, PRIMARY_DB checks first for minimal collisions. Also, update docker configs. All here (https://github.com/PostHog/posthog/pull/7830). The remaining item is still that FOSS gets broken. 

Seems like FOSS will only make sense once we have the settings work above and the file reorganization done. Any thoughts on how to side step this so we don't have to do everything at once or do we just need to go through all the steps?
