### ISSUE TITLE
New InsightDisplayConfig has scroll bars in smaller screens

### ISSUE THREAD

**Issue by macobo** [PostHog/posthog#7593]
## Bug description

![image](https://user-images.githubusercontent.com/148820/145363400-e8adf824-d310-4c6f-81ae-312c6bc1b8e9.png)

## Expected behavior

Multi-row

## How to reproduce

1. Go to insights
2. Resize screen

## Environment

- [x] PostHog Cloud
- [ ] self-hosted PostHog (ClickHouse-based), version/commit: _please provide_
- [ ] self-hosted PostHog (Postgres-based, legacy), version/commit: _please provide_

## Additional context

cc @mariusandra / @paolodamico for prioritization

cc @alexkim205 who implemented the feature

**Comment by macobo** [comment]
Also - grouped by is inconsistent with its casing from the rest of the options there.

**Comment by alexkim205** [comment]
Thanks for cutting the bug. I believe grouped by is supposed to be part of the sentence "Date range ... grouped by ... " but this might not be too clear especially with "Compare to previous" following directly. @clarkus do you see any way we can make this grammar clear?

re: scrollbar - cutting a pr now
