### ISSUE TITLE
Retention insights loading can be slow

### ISSUE THREAD

**Issue by hazzadous** [PostHog/posthog#7595]
## In what situation are you experiencing subpar performance?

For example:

 * Viewing retention insights
 * With breakdowns on high cardinality fields

I haven't looked in detail on the exact scenarios. This is more a placeholder to ensure we consider this case. 

 - [ ] add stats on real queries to get an understanding of how much an issue this is

## How to reproduce

[This one](https://app.posthog.com/insights/USh8zzAW/edit?insight=RETENTION&target_entity=%7B%22id%22%3A%22%24pageview%22%2C%22name%22%3A%22%24pageview%22%2C%22type%22%3A%22events%22%7D&returning_entity=%7B%22id%22%3A%22%24pageview%22%2C%22type%22%3A%22events%22%2C%22name%22%3A%22%24pageview%22%7D&period=Day&retention_type=retention_first_time&breakdowns=%5B%7B%22property%22%3A%22%24initial_browser_version%22%2C%22type%22%3A%22person%22%7D%5D&breakdown_type=person&display=ActionsTable&properties=%5B%5D) for instance

## Environment

- [x] PostHog Cloud
- [x] self-hosted PostHog, version/commit: _please provide_

**Comment by macobo** [comment]
Should measure this after we have the events table migration done - the new sort key will help here quite a bit :)
