### ISSUE TITLE
New dates UX is confusing

### ISSUE THREAD

**Issue by paolodamico** [PostHog/posthog#7617]
## Bug description

While the new ways to display dates does provide value, I think it introduced some confusion worth addressing. In particular, the way we display dates when collapsed.

<img width="346" alt="" src="https://user-images.githubusercontent.com/5864173/145492803-07316fd7-fe43-41f1-b472-d1754fda733f.png">

## Expected behavior

IMHO should still display the relative time information (e.g. "Last 7 days") because:
a) It's generally easier to parse than a date range (at least for quick analysis, you may want to understand the specific range later).
b) It's confusing to select "Last 7 days" and then see a date range which is a different text (don't make me think).
c) The default date range is now a random date range which immediately makes me think something is outdated.

## How to reproduce

Create an insight.

## Environment

- [x] PostHog Cloud
- [ ] self-hosted PostHog (ClickHouse-based), version/commit: _please provide_
- [ ] self-hosted PostHog (Postgres-based, legacy), version/commit: _please provide_

## Additional context
CC @clarkus @corywatilo for input.

**Comment by corywatilo** [comment]
Feedback about what's inside the dropdown (not specific to the bug report):

### Suggestions

- Add contrast and hierarchy between range description and definition
    _Bold text shows the range, dates below show the details to validate it_
- US date format (month, date, year)
- Abbreviate year when start/end range are in the same year

### Wireframe

![image](https://user-images.githubusercontent.com/154479/145517862-2e19a93c-ab09-4716-8bcc-0a0722968af8.png)

**Comment by paolodamico** [comment]
Love that @corywatilo! Only thing I'm not sure is on the date format, "Jan 21, 2020" does seem more natural to me but I'm not sure if that's the case for most people as usually you do dd/mm/yyyy (but not sure when you use the month's short name instead of just a number).

**Comment by corywatilo** [comment]
Ultimately this should be a user preference, but given our [handbook](https://posthog.com/handbook/company/communication#writing-style) specifies American English, date formats would be month first, then date, then year.

**Comment by paolodamico** [comment]
User preference makes sense (we may want to pull the browser's config as default)

**Comment by clarkus** [comment]
I don't think we need to show the translated ranges in the menu. The approach breaks down in non-day cases (last 24 hours, all time) and it really clutters up the menu. I agree some hierarchy helps, but I think the relative ranges are sufficient for selecting things. If we want to show absolute ranges, I think that would be better as output in some form. Agree on user preferences, but could also see a formatting option being available somewhere in the query builder. Sometimes it's easier to do advanced queries different formats.
