### ISSUE TITLE
Replace random insight names with intelligent ad-hoc naming

### ISSUE THREAD

**Issue by corywatilo** [PostHog/posthog#7622]
I like cute animal names more than the next PostHog user, but these random names don't add a ton of value:

![image](https://user-images.githubusercontent.com/154479/145518200-a31cac5a-d8d9-4d89-95eb-4ebf95db5af7.png)

It works for randomly-generated servers and subdomains, but _as a user_ in an analytics tool, I'm confused as to why I get some random name at the top of a new insight before I've even run anything. (There is no information explaining what this random assemblage of words means.)

Digest as to how we ended up here (from [a Slack thread](https://posthog.slack.com/archives/C01G8S5T08Z/p1639053221315500)):

- We wanted a better default name than "new insight" or "insight #624142"
- It was previously a unique number, but the consensus that was too revealing of usage. Providing a unique default lets us avoid prompting for a unique on save.

## Context

At Heep, we assembled a label automatically that could be used as a basis for setting a custom name if you wanted to save a report. (This was also helpful for the purposes of screenshotting a graph, so you have a label that explains what you're looking at.)

Example in mockup below: _Sessions_ (graphed property) _where_ (indicator that filters coming next) _UTM source is defined_ (filters)_, by UTM source_ (grouping)

![image](https://user-images.githubusercontent.com/154479/145519314-b40da419-88cc-42f0-bf8e-4f9d6d24ba5c.png)

Since my former glory days, they've actually removed this label from displaying in ad-hoc reports. It sort of makes sense - you don't really need to see a name unless you decide to save it (though I'd argue the displaying of a relevant summary of the query in the graph area makes sense for screenshotting purposes).

![image](https://user-images.githubusercontent.com/154479/145518687-04b7b5d8-5920-4dc2-8217-d47a64dffd33.png)

However, these ad-hoc labels live on when viewing history, which is a super handy way to eyeball something recent you want to reference:

![image](https://user-images.githubusercontent.com/154479/145519707-b63ab452-d647-450e-95fd-370bc958088b.png)

## Suggestions

1. Do something similar to above
2. Just hide name and description until the Save button is pressed, as they don't provide much value and it's hard to mentally map a two word animal-themed name with a specific insight.

Related: Personally I think it feels weird you can set a name/description before clicking Save. Thoughts that happen as I type a name/description:

1. Will this save this report automatically?
2. Now that I've typed a name/description/tags, can I click away? Why is the save button still blue? Do I still have to click it?
3. If I don't click save, do I lose all this stuff I just typed in?

Seems like we should hide name/description/tags until the Save button is clicked, then allow for adding those. But tying back to the original point of this issue, if the field is pre-filled with _useful_ information about the query, it will only help reduce the amount of work you have to do to explain the insight*, as it would basically already be filled out for you.**

\* Could drop the name in the description field, since they may be longer
\** Yes, there's potential for duplicate names. Incrementing these, or allowing duplicate names seems fine. (What if we have folders and you want the same report name in different folders?) We should decouple unique naming on the backend from what the user wants to name something.

**Comment by corywatilo** [comment]
Bump

**Comment by Twixes** [comment]
These are super valuable points, we may be able to tackle this for 1.33.
