### ISSUE TITLE
Large date ranges are not handled well with small intervals

### ISSUE THREAD

**Issue by macobo** [PostHog/posthog#7625]
## Is your feature request related to a problem?

1. Group by 'minute' almost never works
2. It's possible create a lot of noise/make a dashboard/insights unusable by sending us 1 pageview event from 1970 and then selecting "All of time" with interval daily
3. Choosing a large time range and a very small interval always loads slowly and doesn't look nice.
4. Choosing "minute" interval almost never works
5. Similar to 2, it's possible to override date ranges in dashboards so that the previously hourly/daily graph becomes slow and unreadable if "all of time" is selected.

## Describe the solution you'd like

Given a time range, we should have business logic in both FE/BE for what intervals are allowed and if the current one is not allowed, choose the minimum one.

Proposal:
- Kill `minute` interval - it doesn't work well with any date ranges, it leads to a broken experience. We can always bring it back once we have improved it.
- If date range > 2 weeks, minimum interval is day
- If date range > 365 days, minimum interval is week
- If date range > 4 years, minimum interval is month

## Describe alternatives you've considered

Improve trend graph response format - only solves (2) though.

## Additional context

cc @paolodamico, @mariusandra, @EDsCODE - This caused a breaking issue for a key client today. I think we should prioritize this given the focus on insights experience. Would also like a :+1: for the proposal logic.

cc @clarkus - perhaps you have thoughts on what's the maximum number of ticks that we can reasonably fit on a graph?

**Comment by mariusandra** [comment]
I think this proposal makes sense, however I'd relax the requirements just a bit, and change the second to "2 years"

> If date range > 2 years, minimum interval is week

I've had the opportunity to compare 2 years on a daily chart to notice patterns between years. When fullscreen, there's enough space for 365*2 pixels. I wouldn't want to send `chart_width` as a parameter to the API though, so it makes sense to have a hard limit in the API, thus the more relaxed limit.

**Comment by paolodamico** [comment]
This sounds good to me to test out. Two things,

- Do we have some basic metrics on how many insights are currently active that would be "no longer allowed"? What are our plans for existing insights, will we get rid of them or allow them to stay around?
- We should work with @clarkus to figure out the right UI here to communicate clearly to users the disallowed ranges and why.

**Comment by clarkus** [comment]
> cc @clarkus - perhaps you have thoughts on what's the maximum number of ticks that we can reasonably fit on a graph?

This depends on context. The label format and character length must be sufficient to describe the point in time, but it must also fit into a variable-width container. Dashboard items can have multiple sizes, insight types use different visualizations and each requires a variable amount of space. In the past, I have left some points on the axis unlabeled when a tooltip is in play. 

I don't think disabled options are a good idea. They're always a dead end. When a time range limits the available units, we can just show the available set.

**Comment by kappa90** [comment]
Incorrectly closed after #10462, which is meant to run as an experiment
