### ISSUE TITLE
Legend on insights doesn't work well with long urls

### ISSUE THREAD

**Issue by jamesefhawkins** [PostHog/posthog#7644]
## Is your feature request related to a problem?

<img width="1450" alt="Screenshot 2021-12-10 at 17 37 10" src="https://user-images.githubusercontent.com/47497682/145617397-81c639b5-f10e-4cc0-bc6a-0496876bd042.png">

This, [from an internal insight](https://app.posthog.com/insights/txF0B3gq?insight=TRENDS&display=ActionsLineGraph&interval=day&actions=%5B%5D&events=%5B%7B%22id%22%3A%22%24pageview%22%2C%22name%22%3A%22%24pageview%22%2C%22type%22%3A%22events%22%2C%22order%22%3A0%2C%22properties%22%3A%5B%7B%22key%22%3A%22%24current_url%22%2C%22value%22%3A%22posthog.com%22%2C%22operator%22%3A%22icontains%22%2C%22type%22%3A%22event%22%7D%2C%7B%22key%22%3A%22%24current_url%22%2C%22value%22%3A%22self-host%22%2C%22operator%22%3A%22icontains%22%2C%22type%22%3A%22event%22%7D%5D%7D%5D&properties=%5B%5D&filter_test_accounts=true&breakdown=%24current_url&breakdown_type=event&new_entity=%5B%5D), is a bit messy - I wish I could scroll inside the legend to the right to see which URL is which on the graph.

As a workaround, I can use the breakdown table underneath, so it's not a critical problem.

**Comment by mariusandra** [comment]
One more wish for the legend: make the elements clickable:

![2021-12-13 17 13 39](https://user-images.githubusercontent.com/53387/145847915-8882fd46-f201-42ea-8c9b-643c0327a572.gif)

**Comment by mariusandra** [comment]
@alexkim205 found a few more issues with labels:

1. The legend is weird by default on trend charts:
![2021-12-14 11 04 02](https://user-images.githubusercontent.com/53387/145976997-d0df0dd4-baf5-4c6c-a307-fd6d16a484ba.gif)

2. The checkboxes do nothing for bar charts:
![2021-12-14 11 05 05](https://user-images.githubusercontent.com/53387/145977227-091d46d8-9854-419f-9ccc-646e6e86342d.gif)

3. Same for tables:
![2021-12-14 11 06 12](https://user-images.githubusercontent.com/53387/145977334-0220a2df-b46f-4576-bb1e-7f025f638d0b.gif)

**Comment by clarkus** [comment]
> The legend is weird by default on trend charts:

Agree that we shouldn't show legends by default. Once we have improved tooltips, legends will mostly be for setting a more readable state for dashboards, screenshots, etc.

**Comment by alexkim205** [comment]
Putting this in my backlog for cleanup work after tooltips is out.
