### ISSUE TITLE
Funnel trends broken

### ISSUE THREAD

**Issue by kpthatsme** [PostHog/posthog#7645]
## Bug description

- Date range not applied
- Conversion windows not respected

## Expected behavior
- Data points before the conversion window is completed should be incomplete data points
- The chart should contain the dates that the query says it contains

## How to reproduce

1. View this [funnel](https://app.posthog.com/insights/Y1k2Wbh9/edit?insight=FUNNELS&actions=%5B%7B%22id%22%3A%222674%22%2C%22type%22%3A%22actions%22%2C%22order%22%3A1%2C%22name%22%3A%22User%20Signed%20Up%20(Comprehensive)%22%2C%22math%22%3A%22dau%22%7D%5D&events=%5B%7B%22id%22%3A%22%24pageview%22%2C%22name%22%3A%22%24pageview%22%2C%22type%22%3A%22events%22%2C%22order%22%3A0%2C%22math%22%3A%22dau%22%2C%22properties%22%3A%5B%7B%22key%22%3A%22email%22%2C%22value%22%3A%22is_not_set%22%2C%22operator%22%3A%22is_not_set%22%2C%22type%22%3A%22event%22%7D%5D%7D%5D&display=FunnelViz&layout=horizontal&interval=day&properties=%5B%5D&filter_test_accounts=true&funnel_to_step=1&funnel_viz_type=trends&exclusions=%5B%5D&funnel_from_step=0) or this [Slack thread](https://posthog.slack.com/archives/C02283301EK/p1639160785465300)
2.
3.

## Environment

- [ ] PostHog Cloud
- [ ] self-hosted PostHog (ClickHouse-based), version/commit: _please provide_
- [ ] self-hosted PostHog (Postgres-based, legacy), version/commit: _please provide_

**Comment by macobo** [comment]
@alexkim205 can this be now closed?

(Protip: Add `fixes #xxxx` to your PR and it will autoclose related issues.

**Comment by alexkim205** [comment]
Nope there's still an outstanding task for the conversion window bug that I haven't gotten to yet. Planning on getting to it this morning
