### ISSUE TITLE
Funnel step reordering is broken

### ISSUE THREAD

**Issue by yakkomajuri** [PostHog/posthog#7646]
## Bug description

Reordering funnel steps doesn't work

## Expected behavior

Steps switch places

## How to reproduce

1. Try to reorder funnel steps

## Environment

- [x] PostHog Cloud
- [ ] self-hosted PostHog (ClickHouse-based), version/commit: _please provide_
- [ ] self-hosted PostHog (Postgres-based, legacy), version/commit: _please provide_

**Comment by Twixes** [comment]
Weirdly I don't think I can reproduce this. Could you send over a gif of what's going on?

**Comment by Twixes** [comment]
I'll close this since I haven't heard anything about it, but reopen if I'm wrong.
