### ISSUE TITLE
Group Analytics or Group analytics?

### ISSUE THREAD

**Issue by paolodamico** [PostHog/posthog#7648]
Looks like we have some inconsistency in different places (or at least the confusion) of how to write this. @corywatilo IIRC you were the one who championed conventions here?

For context, we call it "Correlation analysis" (https://posthog.com/docs/user-guides/correlation)

CC @macobo @clarkus

**Comment by clarkus** [comment]
Sentence case is our standard. We should go with that.

**Comment by paolodamico** [comment]
Say no more, let's go.

**Comment by corywatilo** [comment]
Sentence case unless it's an official feature name (proper noun). But we don't use it very consistently.

Ex: Is feature flags a common term or an actual feature in our app?

It sort of feels weird to have a random capital letter in the middle of a sentence like Correlation analysis, which also doesn't make sense in sentence casing either. We could consider them to be features and therefore would be Correlation Analysis. (Definitely looks better this way.)

**Comment by macobo** [comment]
Seems like @corywatilo and @clarkus are in disagreement here then as `Group Analytics` is a feature name.

Can you confirm we should go with `Group Analytics`?

**Comment by corywatilo** [comment]
That would be my vote, yes. But we should also do a once-over on everything else (especially Docs).

Example:

If _feature flags_ is an actual feature in our app (it is), we need to make sure it's correctly referred to as _Feature Flags_, but not when we're describing the generic term of _feature flags_.

Correct examples of both uses:

_"PostHog comes with Feature Flags."_
_"Creating a new feature flag..."_

English is fun, isn't it?

In either case, a feature like this should be `Group Analytics` as it's a proper noun (which is largely my fault for inconsistencies on the website, as there are a-plenty).

**Comment by clarkus** [comment]
So the consensus is sentence case everywhere except feature names which we'll treat as proper nouns (title case)? I think whatever we choose is fine, just want it to be documented and communicated out to everyone producing content.

**Comment by paolodamico** [comment]
Alright sounds good! Feature names should be considered a proper noun and all words are capitalized. Let's keep this issue to remember to update FFs, correlation analysis, ....

**Comment by joethreepwood** [comment]
Putting this in the style guide and adding to the checklist so we can minimize inconsistencies in the future.

**Comment by paolodamico** [comment]
@Twixes has addressed this in #7780, closing.
