### ISSUE TITLE
Cache dashboard items

### ISSUE THREAD

**Issue by timgl** [PostHog/posthog#765]
**Is your feature request related to a problem? Please describe.**
If there's a lot of dashboard items with heavy queries, it takes a while to load the page.

**Describe the solution you'd like**
Pre-calculate the data created.

**Describe alternatives you've considered**
Wait a while

**Additional context**
This should be reasonably trivial as we have the filters for each of the dashboard items. Probably just add a field called `cache` to DashboardItems that we calculate every 15 minutes or so.

***Thank*** you for your feature request - we love each and every one!

**Comment by EDsCODE** [comment]
related #940
