### ISSUE TITLE
Unclear event date sort

### ISSUE THREAD

**Issue by mariusandra** [PostHog/posthog#766]
**Describe the bug**

I'm clicking on "When" to see what my user did, but I have no idea if I'm looking at the start or at the end of the list. It's always "8 hours ago"

![image](https://user-images.githubusercontent.com/53387/81872257-b8122600-9579-11ea-87c0-695f4d702b42.png)

**To Reproduce**
1. Explore the $pageview event and click on yesterday's dot
2. Click a random user
3. Try to figure out which way the table goes

**Expected behavior**
It should be clear what are the earliest and what are the latest events

**Comment by Twixes** [comment]
This table is much clearer now.
