### ISSUE TITLE
Add last 180 days dropdown

### ISSUE THREAD

**Issue by andrewm4894** [PostHog/posthog#7660]
## Is your feature request related to a problem?

Not really, more of a nice to have or improvement.

## Describe the solution you'd like

Add a 180 days option in the dropdown

<img width="494" alt="image" src="https://user-images.githubusercontent.com/2178292/145674778-041b9f9e-9520-43e1-b83e-f118a6745175.png">

## Describe alternatives you've considered

Tried to see if i could make the custom time frame be some relative auto logic like today minus 180 but dont think thats possible.

**Comment by mariusandra** [comment]
Hey @andrewm4894 , this is [finally there](https://github.com/PostHog/posthog/pull/7950).
