### ISSUE TITLE
Deploy `person_distinct_id2` table to everyone

### ISSUE THREAD

**Issue by macobo** [PostHog/posthog#7663]
## Is your feature request related to a problem?

As part of https://github.com/PostHog/posthog/issues/7548, we implemented a new `person_distinct_id` table which can be queried >10x faster for users with >10M persons.

This table is currently rolled out only on cloud and for only 2 customers. 

## Describe the solution you'd like

Implement a big migration to get this live for cloud users and eventually self-hosted users as well. cc @yakkomajuri 

The code to write to the table should look something like the following:

```sql
INSERT INTO person_distinct_id2(team_id, distinct_id, person_id, is_deleted, version)
SELECT
    any(team_id) as team_id,
    distinct_id,
    argMax(person_id, _timestamp) as person_id,
    0 as is_deleted,
    0 as version
FROM
    (
        SELECT
            distinct_id,
            person_id,
            any(team_id) as team_id,
            max(_timestamp) as _timestamp
        FROM
            person_distinct_id
        WHERE
            person_distinct_id.team_id = 2635
        GROUP BY
            person_id,
            distinct_id
        HAVING
            max(is_deleted) = 0
    )
GROUP BY
    distinct_id
```

Also update person_distinct_id insertion logic in-app.

## Open questions

- How to implement the big migration
- How can we implement the query switchover (when do we know when the migration has run?)
- When can we drop old query and ingestion code

## Additional context

I've checked and the two distinct_id tables are also in sync between each other.

cc @yakkomajuri let's work together to get this live

**Comment by yakkomajuri** [comment]
@macobo are we ready to do this? If so, could be worth working hard and getting this out tomorrow as a great way to test special migrations in prod. Given this is Cloud-only (and async migrations can account for that), we don't need to worry about self-hosted users

**Comment by macobo** [comment]
This ticket is for getting the new table out for everyone, including self-hosted users in 1.32.0 so we need to solve with that in mind. There are however additional semantics that need to be clarified, see the original comment.

@hazzadous showed interest in this, I assume us 3 will schedule a call once all are ready.

**Comment by hazzadous** [comment]
Yes I'm keen to get involved here. Unless there's some urgency would tomorrow morning work for a call?

**Comment by yakkomajuri** [comment]
Just read this: "eventually self-hosted users as well", sorry. 

I was reading fast and got caught up on "rolled out only on cloud"

**Comment by macobo** [comment]
Note: found other teams where implementing this:
- took a trends DAU query from 8s to 600ms :) (team 2109)
- Took funnel from 17s to 6s (team 572)

**Comment by macobo** [comment]
This is now live for everyone
