### ISSUE TITLE
Impossible to create PostHog Cloud account

### ISSUE THREAD

**Issue by joethreepwood** [PostHog/posthog#7666]
## Bug description

This was originally reported by a user, via Hubspot: "I would like to signup for PostHog Cloud but I always get redirected to the login page. Is it currently not possible to sign up for PostHog Cloud?"

I was able to replicate this by visiting Posthog.com, clicking 'Get Started' (either CTA), choosing PostHog Cloud and arriving at a login screen. 

The login screen doesn't give any information about creating new accounts, only logging in. I initially thought this could be a messaging issue and that entering new information would lead to a sign-up process. I tried this with a few different test email addresses that don't have existing and each time only got 'Invalid password' responses. 

<img width="477" alt="Screenshot 2021-12-13 at 11 23 16" src="https://user-images.githubusercontent.com/84011561/145803809-b00119c7-9c41-48d1-9783-9eb6b22e7ad3.png">

## Expected behavior

Sign-up flow. 

## How to reproduce

1. PostHog.com
2. Click get started
3. Try to create new account

## Environment

- [x] PostHog Cloud
- [ ] self-hosted PostHog (ClickHouse-based), version/commit: _please provide_
- [ ] self-hosted PostHog (Postgres-based, legacy), version/commit: _please provide_

**Comment by joethreepwood** [comment]
This is now being reported by a second user: 

"I’m trying to sign up for a Posthog Cloud account but when I click the link I get redirected to login page - is it not available for new users?"

**Comment by Twixes** [comment]
Should be resolved with #7668.
