### ISSUE TITLE
Too many failed login attempts error

### ISSUE THREAD

**Issue by joethreepwood** [PostHog/posthog#7667]
## Bug description

It seems like error itself is breaking. 

In the process of creating https://github.com/PostHog/posthog/issues/7666 I tried signing up under a few different email addresses. Eventually I hit this error, which is what I assume we want the error to appear as:

<img width="498" alt="Screenshot 2021-12-13 at 11 10 03" src="https://user-images.githubusercontent.com/84011561/145802098-3a642833-622b-4ba4-9f55-da7372d9c7e0.png">

A few minutes later, I retried to see if 15 minutes had passed - because I'm an optimistic sod who things time is just an abstract concept. This time I got the following error:

<img width="735" alt="Screenshot 2021-12-13 at 11 11 18" src="https://user-images.githubusercontent.com/84011561/145802253-53987cf4-a752-4fc2-b611-cc417819a208.png">

Retrying the process on a different computer and on mobile (not on Wifi) gave the same error as above. 

## Expected behavior

I'd expect the first error to persist, rather than the second to appear.

## How to reproduce

1. Signup. 
2. Signup. 
3. Signup. 

## Environment

- [x] PostHog Cloud
- [ ] self-hosted PostHog (ClickHouse-based), version/commit: _please provide_
- [ ] self-hosted PostHog (Postgres-based, legacy), version/commit: _please provide_

## Additional context

Error text: `{"type": "authentication_error", "code": "too_many_failed_attempts", "detail": "Too many failed login attempts. Please try again in 15 minutes.", "attr": null}`

**Comment by macobo** [comment]
Duplicate of https://github.com/PostHog/posthog/issues/4885

**Comment by clarkus** [comment]
Closing as duplicate
