### ISSUE TITLE
Plugin tests are flaky

### ISSUE THREAD

**Issue by paolodamico** [PostHog/posthog#7679]
## Bug description

Plugin tests fail fairly frequently due to unrelated changes (e.g. integrity error inserting rows to plugin log entry). It's not been a huge pain because we don't run plugin tests very often (only when a change to the plugin server is introduced).

Example: https://github.com/PostHog/posthog/runs/4508678373?check_suite_focus=true

## Expected behavior

Tests should pass or fail deterministically.

## How to reproduce

1. Push a change to the plugin-server (through a PR), wait for test suite to fail.

## Environment

- CI (development).

**Comment by yakkomajuri** [comment]
Indeed, it's a problem that's been around for a while.

The issue stems from all the async stuff we do.
