### ISSUE TITLE
Run e2e tests with Clickhouse backend

### ISSUE THREAD

**Issue by timgl** [PostHog/posthog#7682]
## Is your feature request related to a problem?

we currently run e2e tests with postgres backend, potentially causing us to miss bugs as we are deprecating Postgres (#6662)

## Describe the solution you'd like

Run e2e tests with clickhouse

## Additional context

I'll pick this up tomorrow

**Comment by macobo** [comment]
Related: https://github.com/PostHog/posthog/issues/6662
