### ISSUE TITLE
Insight tooltip "Click to view" overflows

### ISSUE THREAD

**Issue by Twixes** [PostHog/posthog#7684]
## Is your feature request related to a problem?

Because of groups being added to the product, the insight tooltip's "Click to view persons" message now is too long and wraps into a second line. This looks a bit sloppy.

<img src="https://user-images.githubusercontent.com/4550621/145848853-4c578a7c-cf52-49e0-a8cd-3528cfeafbeb.png" width="351">

## Describe the solution you'd like

We should drop something from the sentence, and for the user experience probably the best thing would be to say "persons" or "groups" based on the query – we already know what it's aggregated by, it's only confusing for the user when we say "or".

**Comment by clarkus** [comment]
Related https://github.com/PostHog/posthog/issues/7370#issuecomment-984157607. We're already conditionally showing "[users](https://github.com/PostHog/posthog/issues/7643)" or "groups" in other areas. Couldn't we do the same in the tooltips? If we're aggregating by unique organizations, we could show "view organizations" in the tooltip.
