### ISSUE TITLE
"Any order" funnel labels are wrong

### ISSUE THREAD

**Issue by macobo** [PostHog/posthog#7725]
## Bug description

I have the following funnel:

![image](https://user-images.githubusercontent.com/148820/146151472-aa710242-22e8-4ba4-b1aa-e87cbc029e94.png)

This is incorrect - pageviews are done much more frequently than user views. If you switch back to "Sequential" the number of "person page views" drops dramatically.  

## Expected behavior

Show correct labels

## How to reproduce

1. See screenshot

## Environment

- [x] PostHog Cloud
- [ ] self-hosted PostHog (ClickHouse-based), version/commit: _please provide_
- [ ] self-hosted PostHog (Postgres-based, legacy), version/commit: _please provide_

**Comment by neilkakkar** [comment]
Sounds like a bug introduced by the vertical breakdown FF?

I remember with Any Orders we used to have: Completed 1 steps, Completed 2 steps as the headers. Need to bring those back, instead of selecting one of the events as step names
