### ISSUE TITLE
Open dashboards by default

### ISSUE THREAD

**Issue by timgl** [PostHog/posthog#773]
**Is your feature request related to a problem? Please describe.**
(Pedantic alert): I look at dashboards quite a lot, and it takes me 2 clicks to go from app.posthog.com to looking at my dashboard. I'd like my pinned dashboards to be super easily accessible at all times with one click

**Describe the solution you'd like**
Have the dashboard menu be default open. If you're not on a dashboard we could hide "All Dashboards" to make it less cluttered.

**Describe alternatives you've considered**
Clicking twice

**Additional context**

***Thank*** you for your feature request - we love each and every one!

**Comment by EDsCODE** [comment]
I think #775 closed this

**Comment by mariusandra** [comment]
Nope, /trends is still the default page that opens.

**Comment by EDsCODE** [comment]
ah I thought it was just the dashboard pinning

**Comment by mariusandra** [comment]
@EDsCODE ah, my apologies, you were right. This task was indeed about just keeping the sidebar menu open, not redirecting to the dashboards from `/` when you open the app.
