### ISSUE TITLE
Holiday Hack Ideas

### ISSUE THREAD

**Issue by marcushyett-ph** [PostHog/posthog#7731]
This holiday season we're planning to have a Hackathon. Please edit the issue with the idea you're planning on working on - so everyone can see and offer to help out.

- @marcushyett-ph: (Around 20th - 23rd Dec) Ingestion Alert Plugin + Cookie Banner 
- @jamesefhawkins: Doc score widget
- @joethreepwood: Insight Randomizer (20th - 23rd Dec)
- @corywatilo + @smallbrownbike: Templatized, auto-generated open graph images for posthog.com
- @tiina303: testing person properties in order ingestion AND/OR troubleshooting/diagnosing curl for self-hosted
- @liyiy: posthog portugal offsite youtube video 
- @macobo:
- @pauldambra : capture page performance
- @rcmarron : Ingest events from blockchains
- @EDsCODE :
    - deep dive of product data (explore different conversion criteria, get metrics on churn, habit moments)
- ~~@mariusandra : support hero~~
- @fuziontech :
- @yakkomajuri : 
    - posthog-bot /remind ✅ 
- @lottiecoxon : ~~some kind of animated hedgehog~~  catching up on team images
- @guidoiaquinti :
- @kpthatsme :
- @Twixes: demo.posthog.com

We'll have a demo day on 5th Jan.

Anyone from the community is welcome to join us too!

**Comment by neilkakkar** [comment]
> Ingest events from blockchains

Sounds like a plugin to connect to the blockchain? xD This is epic fun! Now I want to not go on vacation 😂

**Comment by rcmarron** [comment]
> Sounds like a plugin to connect to the blockchain? xD This is epic fun! Now I want to not go on vacation 😂

🤣 Exactly! Probably going to build it using [the graph](https://thegraph.com/)

**Comment by yakkomajuri** [comment]
@posthog-bot remind @marcushyett-ph to organize the demo session at 12pm UTC on 05/01/2022

**Comment by yakkomajuri** [comment]
@posthog-bot remind @marcushyett-ph to organize the demo session at 12pm UTC on the 5th of January 2022

**Comment by yakkomajuri** [comment]
@posthog-bot remind @marcushyett-ph to organize the demo session at 12pm UTC on 01/05/2022

**Comment by yakkomajuri** [comment]
@posthog-bot remind @marcushyett-ph to organize the demo session at 12pm UTC on 01/05/2022

**Comment by yakkomajuri** [comment]
@posthog-bot remind me to mark my project as complete in 10 seconds

**Comment by yakkomajuri** [comment]
@posthog-bot remind me to mark my project as complete in 10 seconds

**Comment by joethreepwood** [comment]
Managed to get v1.0 of ShuffleHog running. It's a Twitterbot which suggests possible queries and ideas randomly every three hours, based on our list of actions and events. It isn't integrated into PostHog, but it could be!

[Follow it here. ](https://twitter.com/TheHogBot)
[Source code here. ](https://cheapbotsdonequick.com/source/TheHogBot)

**Comment by marcushyett-ph** [comment]
## My 3.5 Holiday Hacks Shipped

1. GDPR compliant [open source cookie banner](https://github.com/PostHog/cookie-banner) that's designed to work with PostHog and other tools
2. Make preflight screen look prettier and match our current branding: https://github.com/PostHog/posthog/pull/7827
3. Ship a plugin to [alert people when their instance has stopped ingesting events](https://github.com/PostHog/ingestion-alert-plugin)
3.5. Ship a [heartbeat plugin](https://github.com/PostHog/posthog-heartbeat-plugin) to send events to an instance at regular intervals (incase they want to monitor ingestion and don't have a lot of users)

**Comment by jamesefhawkins** [comment]
@marcushyett-ph I've done a few things: (went a bit off piste)

* Went on a PR mergefest. Got us from 45 ish open to 25 on posthog.com
* On our pricing page, I added links from all the features listed to their relevant documentation :)
* Created [an internallinker](https://github.com/PostHog/internallinker) - put keywords into a page of our docs or blog that it should rank for in google, then it'll go through every other markdown page and will insert internal links to the first page
