### ISSUE TITLE
Inconsistent capitalization for button name

### ISSUE THREAD

**Issue by iprithvitharun** [PostHog/posthog#7733]
## Issue description

**+ Invite team member** button name uses sentence case while most other button names use title case. 

<img width="856" alt="Screenshot 2021-12-15 at 9 40 44 PM copy" src="https://user-images.githubusercontent.com/58725708/146229596-5f816097-d11f-4e27-bc80-346815560948.png">

## Solution

Use title case. Like, **+ Invite Team Member** 

## Rationale

I couldn't find any official content style guide so I am using the commonly used capitalization pattern. Plus, I prefer title case since it helps screen reader to read the words with depth.

**Comment by clarkus** [comment]
Hi, @iprithvitharun our writing style is documented at https://posthog.com/handbook/company/communication#writing-style. We've settled on using sentence case for titles and labels. Thanks for filing, but this button is labeled accurately per our guidelines.

**Comment by iprithvitharun** [comment]
@clarkus Thanks for sharing the link. This means that we'll have to update the other title case instances.
