### ISSUE TITLE
Allow renaming group types

### ISSUE THREAD

**Issue by macobo** [PostHog/posthog#7763]
## Is your feature request related to a problem?

We use the group type name you've set up in tracking to be the thing you see in UI throughout insights, feature flags and group pages.

This can cause issues as:
- The code name might be somewhat ugly (e.g. `client_account`)
- We can't pluralize it in a way that always looks natural (e.g. `client_account(s)`)

## Describe the solution you'd like

Allow giving custom singular and plural names in the UI.

Not sure where to place this:

I'd add a cog icon next to each of the group name in people & groups page here:

![image](https://user-images.githubusercontent.com/148820/146505566-bd058f3c-8177-4f9a-a714-e8f6a7dd9211.png)

Opening it opens a modal showing:
1. The name in code (uneditable)
2. Singular name (with a default to the name in code)
3. Plural name (with a default to `code_name(s)`
4. Link to the documentation

You can then change group settings that way.

Permissions-wise, the settings option would only be shown to administrators of the organization.

## Describe alternatives you've considered

Allowing deleting and re-adding group types - will cause issues since deletion is an expensive operation!

## Additional context

cc @clarkus for alternate design ideas

Was discussing this with @joesaunderson in slack

**Comment by clarkus** [comment]
Why not open this up to [rename persons](https://github.com/PostHog/posthog/issues/7643), too? While you're very tactically renaming a thing, it feels more like a management-level action or configuration. Some considerations - who all should be able to perform this action? Does it make sense to put it front and center here? It doesn't seem like something that will need to happen often, so I'd push for some centralized placement in project settings. Thoughts?

**Comment by macobo** [comment]
Sure, makes sense! Regarding settings: it needs a bit of structural rethinking though (information architecture and tabs) so was bit wary of pushing more there or gating this on those improvements. Can decide when we pick this up though
