### ISSUE TITLE
Opt-in usage and system telemetry for self-hosted installations

### ISSUE THREAD

**Issue by guidoiaquinti** [PostHog/posthog#7764]
## Is your feature request related to a problem?
As part of 2022 planning, we are evaluating how we can de-risk the path to handing billions of events per month and enable our biggest customers having a wonderful experience using PostHog.

We can (and we will) tackle the problem via different angles by providing the best hardware, systems, data schemas, software (…), but one problem that will remain is how to reduce the round trip time between a customer experiencing an issue and having that fixed. This problem is even more complex for self-hosted PostHog installations where we don’t have direct access to logs, metrics and telemetry.

The feedback cycle is currently something like:
1. a customer is experiencing an issue
2. the issue gets reported (via GitHub, Slack, customer support)
3. (optional) we ask for more telemetry data
4. we analyse the telemetry and the bug
5. we push a fix
6. customer is happy

## Describe the solution you’d like

I’m opening this issue to discuss adding an opt-in setting for our on-prem installations where PostHog admin can decide if they want to automatically send us crash reports, slow queries stats and other data points in order to improve the product (note: this is not a novel approach, there are plenty of other products already doing it).

Additionally, we could also add a “manual button” that makes a worker automagically collect all informations we think might help to debug a PostHog installation and send it back to us.

By using those approaches, we will probably cut the feedback cycle above to points 4,5,6

## Describe alternatives you’ve considered

Do nothing.

**Comment by marcushyett-ph** [comment]
Sounds great, two small questions to think about?

1. What can we do for the ([up to 75%](https://metabase.posthog.net/question#eyJkYXRhc2V0X3F1ZXJ5Ijp7InR5cGUiOiJuYXRpdmUiLCJuYXRpdmUiOnsicXVlcnkiOiJXSVRIIGVtYWlsc19wZXJfZG9tYWluIEFTIChcblNFTEVDVCBcbiAgICBkb21haW4oSlNPTkV4dHJhY3RTdHJpbmcocHJvcGVydGllcywgJ3NpdGVfdXJsJykpIGFzIHNpdGVfZG9tYWluLFxuICAgIGFycmF5TWFwKHggLT4gSlNPTkV4dHJhY3RTdHJpbmcoeCwgJ2VtYWlsJyksIEpTT05FeHRyYWN0QXJyYXlSYXcocHJvcGVydGllcywgJ3VzZXJzX3dob19sb2dnZWRfaW4nKSkgYXMgZW1haWxzXG5GUk9NIGV2ZW50cyBcbldIRVJFIFxuICAgIGV2ZW50ID0gJ2luc3RhbmNlIHN0YXR1cyByZXBvcnQnXG4gICAgQU5EIHRlYW1faWQgPSAyXG4gICAgQU5EIGNyZWF0ZWRfYXQgPiAodG9kYXkoKSAtIDkwKVxuICAgIC0tIEFORCBKU09ORXh0cmFjdFN0cmluZyhwcm9wZXJ0aWVzLCAncmVhbG0nKSA9ICdjbG91ZCdcbiksIHBlb3BsZV9vbl91bmdhcHBlZF9pbnN0YW5jZXMgQVMgKFxuICAgIFNFTEVDVCBcbiAgICAgICAgc2l0ZV9kb21haW4sIFxuICAgICAgICBlbWFpbHMgYXMgZW1haWxcbiAgICBGUk9NIGVtYWlsc19wZXJfZG9tYWluIFxuICAgIEFSUkFZIEpPSU4gZW1haWxzIFxuICAgIEdST1VQIEJZIHNpdGVfZG9tYWluLCBlbWFpbFxuKSwgcGVvcGxlX29uX2FsbF9pbnN0YW5jZXMgQVMgKFxuICAgIFNFTEVDVCBcbiAgICAgICAgSUYoZG9tYWluKEpTT05FeHRyYWN0U3RyaW5nKHByb3BlcnRpZXMsICckaW5pdGlhbF9jdXJyZW50X3VybCcpKSA9ICcnLCBKU09ORXh0cmFjdFN0cmluZyhwcm9wZXJ0aWVzLCAnJGluaXRpYWxfY3VycmVudF91cmwnKSwgZG9tYWluKEpTT05FeHRyYWN0U3RyaW5nKHByb3BlcnRpZXMsICckaW5pdGlhbF9jdXJyZW50X3VybCcpKSkgYXMgaW5zdGFuY2VfZG9tYWluLFxuICAgICAgICBKU09ORXh0cmFjdFN0cmluZyhwcm9wZXJ0aWVzLCAnZW1haWwnKSBhcyBlbWFpbFxuICAgIEZST00gcGVyc29uIFxuICAgIFdIRVJFIHRlYW1faWQgPSAyIFxuICAgICAgICBBTkQgSlNPTkV4dHJhY3RTdHJpbmcocHJvcGVydGllcywgJ3JlYWxtJykgIT0gJ2Nsb3VkJ1xuICAgICAgICBBTkQgaW5zdGFuY2VfZG9tYWluIE5PVCBMSUtFICclaGVyb2t1JSdcbiAgICAgICAgQU5EIGNyZWF0ZWRfYXQgPiAodG9kYXkoKSAtIDkwKVxuICAgIEdST1VQIEJZIGluc3RhbmNlX2RvbWFpbiwgZW1haWxcbilcblxuU0VMRUNUXG5zdGF0dXMsXG5DT1VOVChESVNUSU5DVCBpbnN0YW5jZV9kb21haW4pXG5GUk9NXG4oU0VMRUNUIFxuaW5zdGFuY2VfZG9tYWluLFxuSUYoU1VNKElGKHBlb3BsZV9vbl91bmdhcHBlZF9pbnN0YW5jZXMuZW1haWwgPSAnJywgMCwgMSkpID0gMCwgJ2dhcHBlZCcsICd1bmdhcHBlZCcpIGFzIHN0YXR1c1xuRlJPTSBwZW9wbGVfb25fYWxsX2luc3RhbmNlcyBcbkxFRlQgT1VURVIgSk9JTiBwZW9wbGVfb25fdW5nYXBwZWRfaW5zdGFuY2VzIFxuT04gcGVvcGxlX29uX2FsbF9pbnN0YW5jZXMuZW1haWwgPSBwZW9wbGVfb25fdW5nYXBwZWRfaW5zdGFuY2VzLmVtYWlsXG5HUk9VUCBCWSBpbnN0YW5jZV9kb21haW4pXG5HUk9VUCBCWSBzdGF0dXMiLCJ0ZW1wbGF0ZS10YWdzIjp7fX0sImRhdGFiYXNlIjoyfSwiZGlzcGxheSI6InRhYmxlIiwiZGlzcGxheUlzTG9ja2VkIjp0cnVlLCJ2aXN1YWxpemF0aW9uX3NldHRpbmdzIjp7InRhYmxlLnBpdm90X2NvbHVtbiI6InN0YXR1cyIsInRhYmxlLmNlbGxfY29sdW1uIjoiaW5zdGFuY2VfZG9tYWluIn0sIm9yaWdpbmFsX2NhcmRfaWQiOjE5OX0=) of instances) that are gapped?
2. How can we make as much of this self-service as possible - so they don't even need to speak to us?

**Comment by guidoiaquinti** [comment]
> What can we do for the (up to 75% of instances) that are gapped?

I think in this case the only viable option is the “manual button” that instead of automatically send everything we need, it will generate a `.zip` file that the customer will forward us.

> How can we make as much of this self-service as possible - so they don’t even need to speak to us?

The industry standard is to set up a stat service exposed to the internet (e.g. telemetry.posthog.com) where self-hosted installation that opted-in can share anonymous data. This will be 100% transparent and automated.

**Comment by marcushyett-ph** [comment]
> I think in this case the only viable option is the “manual button” that instead of automatically send everything we need, it will generate a .zip file that the customer will forward us.

We might be able to do something more automated - if they opt-in we could send the data via some background JS in the UI every time they log in etc.

> The industry standard is to set up a stat service exposed to the internet (e.g. telemetry.posthog.com) where self-hosted installation that opted-in can share anonymous data. This will be 100% transparent and automated

I kind-of meant them getting the telemetry (and maybe some automated / standard advice on what to do in this situation) and taking actions themselves?

**Comment by guidoiaquinti** [comment]
I think it depends on the data we want to collect. 

> I kind-of meant them getting the telemetry (and maybe some automated / standard advice on what to do in this situation) and taking actions themselves?

This scenario should be covered by our default monitoring/alerting system we are planning to implement.  Example:

* we shouldn't get a notification when a ClickHouse or Kafka installation is running low on disk (but our customer should!)
* we should get a notification when a query is constantly failing/constantly slow on a specific dataset
