### ISSUE TITLE
Improvements to the Person & Group detail pages

### ISSUE THREAD

**Issue by clarkus** [PostHog/posthog#7776]
## Is your feature request related to a problem?

The person page does a pretty great job of listing recordings and events. However, the person property table is pretty difficult to use in its current position. Property names are often unbreakable strings that don't wrap naturally. There are also multiple tabs of data here that are difficult to navigate due to space constraints.

<img width="344" alt="Screen Shot 2021-12-17 at 9 19 20 AM" src="https://user-images.githubusercontent.com/254612/146583128-805aba69-1cec-491a-b7c5-db20ab1ae01e.png">

## Describe the solution you'd like

I'd like us to update the layout of this page to give the property table the pace it needs to fully describe the list. It could show up as an additional top level tab, or could be listed below the other tables.

## Describe alternatives you've considered

None - I think we should improve this. 

## Additional context

Reported via our [community slack](https://posthogusers.slack.com/archives/C01GLBKHKQT/p1639737513250100)

**Comment by macobo** [comment]
Note to keep design of group page in sync if editing this :)

**Comment by clarkus** [comment]
Proposed layout changes for persons. 
![persons and groups](https://user-images.githubusercontent.com/254612/146586371-27701cfb-ef8e-47af-ace3-1584647c688e.png)

https://www.figma.com/file/gQBj9YnNgD8YW4nBwCVLZf/PostHog-App?node-id=6132%3A33445

Groups will use the same layout, minus the page-level actions, recordings, and cohorts tabes. https://www.figma.com/file/gQBj9YnNgD8YW4nBwCVLZf/PostHog-App?node-id=6132%3A34595

![persons and groups](https://user-images.githubusercontent.com/254612/146588119-2a95f6a0-eb85-4bb0-9d9d-fd776976407d.png)

**Comment by Twixes** [comment]
Resolved by #7988.
