### ISSUE TITLE
Opening the person's modal from the retention line graph crashes the page

### ISSUE THREAD

**Issue by rcmarron** [PostHog/posthog#7787]
## Bug description

When you click a datapoint in the retention line graph, the person modal starts to load, but then it crashes.

![image](https://user-images.githubusercontent.com/4813045/146599239-2754ecd5-2f26-4b68-a04d-250f488f17b8.png)

## Expected behavior

To not crash, but instead, show the same modal as clicking the table below.

## Environment

- [ ] PostHog Cloud
- [ ] self-hosted PostHog (ClickHouse-based), version/commit: _please provide_
- [ ] self-hosted PostHog (Postgres-based, legacy), version/commit: _please provide_

**Comment by rcmarron** [comment]
cc @EDsCODE

**Comment by hazzadous** [comment]
Further context: [user reports in slack](https://posthogusers.slack.com/archives/C01PPBY3G6Q/p1639739060182100)
