### ISSUE TITLE
Incompleteness trend UI doesn't apply on custom date range

### ISSUE THREAD

**Issue by EDsCODE** [PostHog/posthog#7789]
## Bug description

*Please describe.*  
- If you apply a specified time range (using the calendar select) in a trend graph, the in progress UI doesn't apply
*If this affects the front-end, screenshots would be of great help.*  
<img width="390" alt="Screen Shot 2021-12-17 at 6 50 37 PM" src="https://user-images.githubusercontent.com/13127476/146625117-420c67f5-974f-4b0a-b2af-d535ec5a247b.png">

## Expected behavior
- should still show progress UI

## How to reproduce

1. Go to a graph
2. specify a custom time that should still be in progress
3.

## Environment

- [ ] PostHog Cloud
- [ ] self-hosted PostHog (ClickHouse-based), version/commit: _please provide_
- [ ] self-hosted PostHog (Postgres-based, legacy), version/commit: _please provide_

**Comment by alexkim205** [comment]
Hey @EDsCODE isn't this behavior expected since the end date of the specified date range has already passed?

**Comment by EDsCODE** [comment]
I mean you can even specify the end date as a future date and it still shows complete. Like if I were to do a weekly interval from december 20 into january 10, it'll give a solid line

**Comment by alexkim205** [comment]
Ah got it, just realized that this only happens when choosing a date in the calendar picker. On a fix now
