### ISSUE TITLE
Referrer URL column is hard to read (due to wrapping)

### ISSUE THREAD

**Issue by corywatilo** [PostHog/posthog#7797]
When there are columns with longer strings, it would be great if we allowed more space for them, instead of forcing them to split into multiple lines.

In this table view where I'm viewing Pageviews, broken down by _Referrer URL,_ a lot of space seems to be given to other columns that don't need it, while the table key gets split into 2-3 lines.

![image](https://user-images.githubusercontent.com/154479/146665941-6a2d312e-19b2-4443-aa6b-83d2f0f95f52.png)

**Comment by Twixes** [comment]
This seems improved now.
