### ISSUE TITLE
Date filter on dashboards

### ISSUE THREAD

**Issue by mariusandra** [PostHog/posthog#780]
**Is your feature request related to a problem? Please describe.**

I have a dashboard that shows me the stats for this week:

![image](https://user-images.githubusercontent.com/53387/82057046-1b5b9f80-96c3-11ea-90ae-92fde53ce77e.png)

Now if I want to drill down to see the stats for the last day (e.g. to see what referring domains and browsers are trending), I have to open each graph/table in a new tab and change the date filter.

**Describe the solution you'd like**

I'd like there to be a global date filter on top of the dashboard, which updates the date filter for all the graphs. For example I could select "last 30 days" and have all the graphs on my dashboard show data for the last 30 days instead of the last 7 days.

**Describe alternatives you've considered**

Create multiple dashboards for different time periods.

**Comment by paolodamico** [comment]
+1 from customer call on Oct 29.

**Comment by Twixes** [comment]
This is a thing now.
