### ISSUE TITLE
Webhooks send to MS Teams but PostHog returns an error despite successful message

### ISSUE THREAD

**Issue by CaseGuide** [PostHog/posthog#781]
# Issue 
The Slack message Webhook for conversion events is particularly exciting. I want my sales team to get those messages. We’re using MS Teams. It seems like **PostHog can already send MS Teams messages via webhook,** but the dashboard kicks it out saying invalid message.

![Capture](https://user-images.githubusercontent.com/33905722/82067616-f7866280-969e-11ea-9291-49cb4c68edc0.PNG)

If I put in a Teams Webhook which is URL formatted like: https://outlook.office.com/webhook/{{uniquestring}}/IncomingWebhook/{{uniquestring2}}/{{uniquestring3}}

I get a message in Teams:
 ![image](https://user-images.githubusercontent.com/33905722/82067575-e89fb000-969e-11ea-8923-2d73bdc59faa.png)

...but the dashboard kicks out invalid URLs.

Can you guys make it work with Teams and not kick out the URL?

### Proposed solution
There are several open source ms teams wrappers as already.
For example we use [pymsteams](https://github.com/rveachkc/pymsteams/blob/master/pymsteams/__init__.py) that checks for message success like this in Python:
```
    def send(self):
        headers = {"Content-Type":"application/json"}
        r = requests.post(
            self.hookurl,
            json=self.payload,
            headers=headers,
            proxies=self.proxies,
            timeout=self.http_timeout,
            verify=self.verify,
        )

        if r.status_code == requests.codes.ok:
            return True
        else:
            raise TeamsWebhookException(r.text)
```
I see you guys do something similar by checking the response text to precisely equal ok, what you could do instead is see if the response is == 200 or if that creates a failure scenario in Slack, make a conditional check based on the webhook URL format. 

```
@require_http_methods(['POST'])
def test_slack_webhook(request):
    """Change the password of a regular User."""
    if not request.user.is_authenticated:
        return JsonResponse({}, status=401)

    try:
        body = json.loads(request.body)
    except (TypeError, json.decoder.JSONDecodeError):
        return JsonResponse({'error': 'Cannot parse request body'}, status=400)

    webhook = body.get('webhook')

    if not webhook:
        return JsonResponse({'error': 'no webhook'})
    message = {
        "text": "Greetings from PostHog!"
    }
    try:
        response = requests.post(webhook, verify=False, json=message)

        if response.ok:
            if response.text == 'ok':
                return JsonResponse({'success': True})
            else:
                return JsonResponse({'error': 'invalid webhook url'})
        else:
            return JsonResponse({'error': response.text})
    except:
        return JsonResponse({'error': 'invalid webhook url'})
```

**Comment by timgl** [comment]
@CaseGuide Thanks for raising this! I've created a branch to fix these issues. If you built from source, you could checkout the `781-teams-webhook-url` branch. If not we'll test it ourselves and merge into master early next week

**Comment by CaseGuide** [comment]
I am lazy and clicked "Deploy to Heroku"

**Comment by timgl** [comment]
That's the best way 😉

**Comment by CaseGuide** [comment]
## Deployed the branch and sent a message to teams, it works!

"Deploy to Heroku" and the JS snippet went a long way in getting me on the platform.

I gave pushing to heroku a try since I'll have to do it to update in the future anyway. Mostly following your [upgrade instructions](https://posthog.com/docs/deployment/upgrading-posthog)   worked fine although [heroku docs](https://devcenter.heroku.com/articles/git#creating-a-heroku-remote) recommend using the heroku CLI to add the remote. 

As a heads up, there's a typo here:
![image](https://user-images.githubusercontent.com/33905722/82086485-92da0080-96bc-11ea-8f19-71f341f3686c.png)

Unrelated:

May I suggest more prominently featuring your YouTube videos in docs? I spent maybe an hour or more clicking around before stumbling on them. It'd be great if on the actual doc page there was the option to watch the video and/or read the text.

**Comment by timgl** [comment]
Thanks for testing this out! I've merged this into master now.

Re the videos, very much agree. We've only just switched to our new website so will add this to the list of things to improve.

**Comment by mariusandra** [comment]
Hi @CaseGuide , could you confirm how well the Teams webhooks work with real actions?

I was already surprised to hear they worked as well as they did with the test "Greetings from PostHog!" message, but its [payload](https://github.com/PostHog/posthog/blob/fd6c6c7082e33a7f388db518677f14c9b18ce5b9/posthog/api/user.py#L126-L128) is really simple: `{ text: "Greetings from PostHog!" }`
 
However we're sending a [more complex payload](https://github.com/PostHog/posthog/blob/fd6c6c7082e33a7f388db518677f14c9b18ce5b9/posthog/tasks/slack.py#L33-L44) in a very slack-specific format for the actual actions. 

Thus any of the three cases can be true:
1. Everything works well, you get action messages in Teams together with links to the actions
2. You get only the plain text part of the action message in Teams
3. Nothing is transmitted and the webhook gives an error when seeing the "blocks" block

Could you clarify what's happening for you? Unfortunately we don't use Teams here so it's hard to test this quickly.

**Comment by CaseGuide** [comment]
Yea here’s a screenshot from mobile. When we want to send formatted text to msteams we use HTML. Not sure if it supports markdown, though when I tried it once with pymsteams it didn’t work. We don't get links to the actions, though that'd be nice. 

![60579E37-7E54-4CC4-BA79-BA602F5A53E8](https://user-images.githubusercontent.com/33905722/82120132-fcf0b500-9751-11ea-9343-beb18de91ea7.jpeg)

Funny you asked because as soon as this worked I looked at slack.py to see if I could customize the message. Though customizing is prob not a critical feature.

Other Edit Thought:
Getting the message is the biggest part, so if you don't want to implement other functionality until you have more than 1 user on msteams using this feature that makes total sense to me.

**Comment by mariusandra** [comment]
Hi @CaseGuide , so it's option 2 then ("You get only the plain text part of the action message in Teams"). It would still be cool to have full Teams support, including HTML or other rich messages with links. 

Reading the [docs for the (legacy) teams cards](https://docs.microsoft.com/en-us/outlook/actionable-messages/message-card-reference), the `text` field actually does support markdown:

![image](https://user-images.githubusercontent.com/53387/82211264-e3499c00-9910-11ea-8540-e2432626344d.png)

So I created PR #796 (branch `781-teams-markdown`) with code that tries to add rich formatting to MS Teams webhooks. Unfortunately right now I have no way to test this myself. Could you have a look if this makes the links work?

**Comment by CaseGuide** [comment]
I'm switching to different tasks than analytics this week so I don't want to pull and redeploy right now but Teams is Free. We got up and running with incoming webhooks in just an hour or two. Its super duper simple.

This will take you 5 Minutes:
1. Open MS Teams
2. Click Teams in nav
3. Click Join or create team
4. Click add channel from context menu. Create a channel.
5. In your new channels context menu click connectors and search for webhooks.
6. Follow prompts and it'll spit out a URL.

**Comment by timgl** [comment]
Weirdly our Teams installation didn't allow us to add connectors, but I found a way to hack around that. Fix merged into master now!
