### ISSUE TITLE
History of an insight (and action, cohort, feature flag, etc)

### ISSUE THREAD

**Issue by mariusandra** [PostHog/posthog#7819]
## Is your feature request related to a problem?

A bug made some insights disappear for two key customers.

## Describe the solution you'd like

I'd like to see edits done to an insight. This serves multiple purposes:
- I'd like to see if a colleague purposefully edited an insight, and what changes were made (e.g. what new filter was added)
- I'd like to see if a colleague accidentally edited an insight, and then revert
- I'd like to see if a bug made the insight disappear, and roll back

Thinking a bit broader, I'd like to see this also for actions, cohorts, feature flags and potentially other objects. 

## Describe alternatives you've considered

Hourly database backups so I could roll back if something is changed wrongly. I still wouldn't be able to see what has changed in an insight

## Additional context

This fits under [collaboration](https://github.com/PostHog/posthog/issues/7282) as well.

**Comment by pauldambra** [comment]
This would be a great addition

Audit logs are always a pain to keep in synch. People can add new features without adding the audit log capture for them.

I guess everything we'd want to track is in Postgres and changed by Django? So we could add middleware to log things we're interested in

Probably simpler than leaning on Kafka and CDC or manually editing code everywhere??

**Comment by mariusandra** [comment]
Oh yes, this should be quite specific for Django, no need to involve Kafka or anything else here.

We could build one-off integrations for e.g. insights and actions, but it may be nicer to indeed have some kind of middleware that abstracts this even further, even if just for whitelisted models. I guess using a `post_save` and `post_delete` [signal](https://docs.djangoproject.com/en/4.0/topics/signals/) is what we need?

**Comment by pauldambra** [comment]
You can now view insight history at https://app.posthog.com/insights?tab=history

<img width="461" alt="Screenshot 2022-08-10 at 22 26 04" src="https://user-images.githubusercontent.com/984817/184023247-21092afb-c084-43ce-88dd-b597b3d35e83.png">
