### ISSUE TITLE
Graph shows dates too far back

### ISSUE THREAD

**Issue by corywatilo** [PostHog/posthog#7840]
## Bug description

When graphing pageviews and setting the date range to _all time_, dates are plotted that precede the age of the entire account.

![image](https://user-images.githubusercontent.com/154479/147387974-d9893464-0475-45b4-9852-29e4f471fb43.png)

## Expected behavior

The start date of the graph should be the date the matching data first appeared.

## How to reproduce

1. [Internal link to graph](https://app.posthog.com/insights/KWD9W8f7/edit?insight=TRENDS&display=ActionsLineGraph&interval=month&actions=%5B%5D&events=%5B%7B%22id%22%3A%22%24pageview%22%2C%22name%22%3A%22%24pageview%22%2C%22type%22%3A%22events%22%2C%22order%22%3A0%7D%5D&filter_test_accounts=true&properties=%5B%7B%22key%22%3A%22%24current_url%22%2C%22value%22%3A%5B%22https%3A%2F%2Fposthog.com%2Fdocs%2Fuser-guides%2Fcohorts%22%5D%2C%22operator%22%3A%22exact%22%2C%22type%22%3A%22event%22%7D%5D&date_from=all&compare=false)

## Environment

- [X] PostHog Cloud

**Comment by macobo** [comment]
Duplicate of https://github.com/PostHog/posthog/issues/7626

It does what it's currently specified to do - it's worth cleaning up the semantics under that ticket though

**Comment by charlescook-ph** [comment]
This has been brought up again [here](https://github.com/PostHog/posthog/issues/8776)

I agree with this Issue though, I would expect the graph to start from where there is actual data. From my perspective, I don't think that #7626 solves this problem. From a user experience, the function feels broken, even if the app is behaving as it's supposed to.

**Comment by clarkus** [comment]
Just to clarify, 0 values are data. An absence of data would be indicated by gaps in the line. A similar pattern is a dashed line used to indicate incomplete time periods of data. The all time semantics feel like more of the core issue here. Secondary to that, some helper interaction that prompts a user to focus their time range on a smaller set where there is non-zero data. I have some ideas for how to improve this so will try to schedule some time to work on those.
