### ISSUE TITLE
Error message in the empty invite user modal is confusing

### ISSUE THREAD

**Issue by iprithvitharun** [PostHog/posthog#7842]
The current error message is unnecessarily complex and not easy to understand for non-native English-speaking users. 

At this point in the flow, it's obvious that they have to enter the email address of the person they want to join. We don't have to stress about it and put the blame on the user.

<img width="516" alt="empty-invite-modal" src="https://user-images.githubusercontent.com/58725708/147417812-80a0d03e-6df4-462d-a18f-3829f1bcd55f.png">

**Comment by Bregge** [comment]
Maybe this could work? More straightforward I think...

**Enter the email of the person you want to invite**

**Comment by kfreda** [comment]
Since it's pretty clear that an email address is required to invite someone, I think something like either of these suggestions would be clear for a non-native English speaking user:

**Who will you invite?**

or

**Who do you want to invite?**
