### ISSUE TITLE
New async migrations are not indicated anywhere

### ISSUE THREAD

**Issue by macobo** [PostHog/posthog#7845]
## Bug description

I'm adding a new async migration as part of https://github.com/PostHog/posthog/issues/7663.

I ran into the following two issues trying to run my new async migration:

1. Async migrations are only loaded for staff users. My local user is not a staff user by default - this is documented in https://posthog.com/docs/self-host/configure/async-migrations#prerequisite
2. Even manually changing the staff user flag in the db, I don't see a flag anywhere in the UI indicating that async migrations can be run.

This leads me to the question - are async migrations set up correctly in a way where users will find and run them?

Creating an issue over slack since everyone is on vacation.

cc @tiina303, @yakkomajuri

**Comment by tiina303** [comment]
> are async migrations set up correctly in a way where users will find and run them?

We have decided to currently not display async migrations in the UI to not confuse users, we'll be testing it out with a couple of users before making it visible to everyone.
