### ISSUE TITLE
Pressing ESC analyzing an insight exits editing it

### ISSUE THREAD

**Issue by macobo** [PostHog/posthog#7857]
## Bug description

Currently, when I press X analyzing a _new_ insight it exits the edit mode and only shows me the graph. This is annoying already.

If I have the quick action menu open at the same time it becomes even more so - if I try to exit the menu via ESC it exits both the menu as well as editing the insight.

## Expected behavior

Drop the ESC behavior on insights - I don't see it being useful.

## How to reproduce

1. Click + to add insight
2. Ctrl + K to open menu (optional)
3. Press ESC
4. See editing is stopped

## Environment

- [x] PostHog Cloud
- [ ] self-hosted PostHog (ClickHouse-based), version/commit: _please provide_
- [ ] self-hosted PostHog (Postgres-based, legacy), version/commit: _please provide_

## Additional context

cc @Twixes and @mariusandra for prioritization

**Comment by Twixes** [comment]
I see, I find this behavior odd too as it doesn't "Save" nor does it "Discard changes". Made #7864 to remove Esc handling.
