### ISSUE TITLE
Keyboard opens on mobile

### ISSUE THREAD

**Issue by mariusandra** [PostHog/posthog#786]
**Describe the bug**

When opening some pages on my phone, the keyboard just pops up. 

A few input fields have autofocus set. 

![Screenshot_20200515-202814](https://user-images.githubusercontent.com/53387/82083969-d8adbd80-96ea-11ea-8af7-94dedefe847c.jpg)

**To Reproduce**
1. Use your phone and click on people
2. Keyboard opens

**Expected behavior**
Fiels should not have autofocus

**Comment by Twixes** [comment]
This should not be the case anymore.
