### ISSUE TITLE
Action doesnt work for elements with onclick attrib.

### ISSUE THREAD

**Issue by CaseGuide** [PostHog/posthog#788]
**Describe the bug**
Users book appointments with us using the calendly buttons on [our site](https://spirelawfirm.com/). We want to track those that click but dont schedule. I created an action to track using the front end element selector but wasn't able to get it to register as an Action even though an Event did register that an input was clicked. 

**To Reproduce**
1.  Attempt to create Action for a calendly button using front end element selection"SCHEDULE AN APPOINTMENT" located [here.](https://spirelawfirm.com/jesse-unruh-attorney/)
2. Action does not appear even though the click event is picked up as "clicked <input>"

**Expected behavior**
Expect creating an action to track clicks on calendly widgets to work. 

**Additional context**
Here is the calendly widget code:
```
<!-- Calendly link widget begin -->
<link href="https://assets.calendly.com/assets/external/widget.css" rel="stylesheet">
<script src="https://assets.calendly.com/assets/external/widget.js" type="text/javascript"></script>
<input type="submit" value="SCHEDULE AN APPOINTMENT" onclick="Calendly.showPopupWidget('https://calendly.com/[our-url]');return false;" class="btn btn-primary btn-block transition-hover" data-loading-text="Loading...">
<!-- Calendly link widget end -->
```

**Comment by timgl** [comment]
Thanks for raising this! I think this is the same issue as #274. We censor most attributes from `<input>`, as we could accidentally grab sensitive data (usernames/passwords/CCs). A quick fix on your side could be to replace `<input>` with:
```html
<button onclick="Calendly.showPopupWidget('https://calendly.com/jet-law-attorneys/free-consultation');return false;" class="btn btn-primary btn-block transition-hover" data-loading-text="Loading...">SCHEDULE AN APPOINTMENT</button>
```
Which I tested on your website and does work correctly.

In the mean time, I will kick #274 back up the queue to look at or at least document properly

**Comment by CaseGuide** [comment]
Yep that fixes it and makes prefect sense. Closing.
