### ISSUE TITLE
Page jumps up when persons modal opens

### ISSUE THREAD

**Issue by alexkim205** [PostHog/posthog#7888]
## Bug description

Page scroll jumps up whenever actor modal is opened. I believe this was introduced in #7590

https://user-images.githubusercontent.com/13460330/148098129-993e35d7-84f7-4122-8e15-c42fe7a60380.mov

## Expected behavior

No scrolling

## How to reproduce

1. Open an insight and trigger opening an actor modal

## Environment

- [x] PostHog Cloud
- [x] self-hosted PostHog (ClickHouse-based), version/commit: _please provide_
- [x] self-hosted PostHog (Postgres-based, legacy), version/commit: _please provide_

**Comment by Twixes** [comment]
I don't think this is an issue anymore, correct me if I'm wrong.
