### ISSUE TITLE
Properties stats is broken

### ISSUE THREAD

**Issue by paolodamico** [PostHog/posthog#7891]
## Bug description

Some users ([example](https://app.papercups.io/conversations/all/1a07e698-ca4a-4a39-82cb-cd65e6d991fe)) have reported not seeing any stats coming up in the "Properties stats" page. For us, the numbers are quite low and clearly incorrect.

## Expected behavior

Properties stats should show correctly.

## How to reproduce

1. Open the Properties Stats page. 
2. See incorrect numbers.

## Environment

- [X] PostHog Cloud
- [ ] self-hosted PostHog (ClickHouse-based), version/commit: _please provide_
- [ ] self-hosted PostHog (Postgres-based, legacy), version/commit: _please provide_

## Additional context

- Related to taxonomy. Possible work for 1.32.0 2/2
- The way we compute these properties is error prone and has performance issues on self-hosted instances. We should improve it.

**Comment by MarkBennett** [comment]
Thanks for setting this up @paolodamico. I've subscribed and can contribute more details if you need. Happy to test with my account.

**Comment by mariusandra** [comment]
We've replaced these stats pages with live queries. Closing.
