### ISSUE TITLE
Async migrations: celery_task_id is not properly handled

### ISSUE THREAD

**Issue by macobo** [PostHog/posthog#7895]
## Bug description

async migrations celery task id will always be "" through the migration

## Expected behavior

It will be set

## How to reproduce

1. Start a migration

## Environment

- [x] PostHog Cloud
- [ ] self-hosted PostHog (ClickHouse-based), version/commit: _please provide_
- [ ] self-hosted PostHog (Postgres-based, legacy), version/commit: _please provide_

## Additional context

The cause is a bad state machine: We set it in #trigger_migration but #mark_async_migration_as_running later in the chain always resets it.

cc @tiina303 and @yakkomajuri for prioritization

**Comment by yakkomajuri** [comment]
getting back today. this is weird, I remember not being a thing before. will fix
