### ISSUE TITLE
Experimentation states & available information

### ISSUE THREAD

**Issue by paolodamico** [PostHog/posthog#7898]
Documenting the different states and ways to show results for Experimentation as per @clarkus's [request](https://www.figma.com/file/gQBj9YnNgD8YW4nBwCVLZf?node-id=6237:30964#137157254).

**Status: Draft**
- Incomplete setup: no information.
- Ready to launch: baseline information, est. running time & est. # participants available.

**Status: Running**
- No results: baseline information, est. running time & est. # participants available.
- Early results: baseline information, winning variant, delta %, actual running time, actual participants exposed.
- Complete results: baseline information, winning variant, delta %, actual running time, actual participants exposed.

**Status: Completed**
- Conclusion, baseline information, winning variant, delta %, actual running time, actual participants exposed.

**Status: Terminated**
- baseline information, actual running time, actual participants exposed, reason for termination.

@neilkakkar @liyiy can you help me review the above? Feel free to edit directly.

**Comment by clarkus** [comment]
While not exactly related to state, there are **experiment types** [coming into play now](https://www.figma.com/file/gQBj9YnNgD8YW4nBwCVLZf?node-id=6360:72338#138495619). The goal type determines how progress is measured. Experiments with conversion goals measure progress by participant count, but experiments with trend goals measure progress in days.
