### ISSUE TITLE
Table rows are oversized in a top-to-bottom funnel layout

### ISSUE THREAD

**Issue by clarkus** [PostHog/posthog#7906]
## Bug description

See screenshot
<img width="1488" alt="Screen Shot 2022-01-05 at 9 27 56 AM" src="https://user-images.githubusercontent.com/254612/148262176-b545dd1b-90f5-45ec-8357-34c56a542ade.png">

## Expected behavior

Rows should size to contain their content. 

## How to reproduce

1. Create a funnel insight
2. Change the layout to top-to-bottom
3. Notice the chonky table rows

## Environment

- [x] PostHog Cloud

**Comment by Twixes** [comment]
Solved by #9360.
