### ISSUE TITLE
Improve $exception events

### ISSUE THREAD

**Issue by paolodamico** [PostHog/posthog#7907]
## Is your feature request related to a problem?

Tracking exceptions in PostHog is really powerful but the UX around it is not great.

## Describe the solution you'd like
- I'd like us to parse the `$sentry_url` so we can quickly show a link to the full Sentry issue, both in the events list and the events in the recording playback. See example below.

<img width="544" alt="" src="https://user-images.githubusercontent.com/5864173/148266399-fde945ec-a8f6-4ac8-a843-f0904f7dcfd4.png">

- Can we show more exception details in a nicer way? Tagging @clarkus for input. Here's what an exception currently looks like.

<img width="1096" alt="" src="https://user-images.githubusercontent.com/5864173/148265925-a5657ef0-a376-4dc8-b88c-91e4c46fd059.png">

## Describe alternatives you've considered

- Keep showing the current version and hoping users figure out how to jump to the Sentry error.

## Additional context

From a [user suggestion](https://app.papercups.io/conversations/all/7adb949b-5062-4735-8c3f-e616217c8a94) coming from FS.

**Comment by pauldambra** [comment]
we do now parse sentry url and show a link, and we have specific display for a $exception event in the events table with simple stack trace display

**Comment by pauldambra** [comment]
![Image](https://github.com/PostHog/posthog/assets/984817/687c846a-6a42-4323-af48-89f9dea97857)
