### ISSUE TITLE
Outstanding Tasks for Insight Tooltips

### ISSUE THREAD

**Issue by alexkim205** [PostHog/posthog#7913]
Leftover items related to https://github.com/PostHog/posthog/pull/7872. Assigning myself for now so that I can finish up if I have free time.

This issue comes out of an action item from standup to capture leftover tasks for the new insight tooltips before we release. @paolodamico 

- [x] https://github.com/PostHog/posthog/issues/7994
- [x] Standardize `dates` parameters in Stickiness and Retention line graphs so that relative date titles can be properly handled by Insight Tooltips.
- [ ] 🎨 Use new tooltips in Funnel Steps (waiting on design input here)
- [x] https://github.com/PostHog/posthog/issues/2620
- [ ] https://github.com/PostHog/posthog/issues/8163

**Comment by macobo** [comment]
- https://github.com/PostHog/posthog/issues/8014
- https://github.com/PostHog/posthog/issues/8026

The latter IMO is a breaking bug for the new feature.
