### ISSUE TITLE
dashboard 'edit mode' modal popup is in the way

### ISSUE THREAD

**Issue by camerondeleone** [PostHog/posthog#7916]
## Bug description

When in edit mode, this popup appears in the bottom right of the screen. If you are trying to rearrange by pulling from the bottom right of the screen (or in the case where you have multiple small insights), it can get in the way. Indicating edit mode might be better done another way

![image](https://user-images.githubusercontent.com/56287180/148297264-d5ab6f55-dd35-4f5e-b876-4089cbd5707f.png)

## Expected behavior

The modal should not inhibit your ability to modify dashboards in any way, but there should still be a visible callout that you are in edit mode

## How to reproduce

1. add an insight to a dashboard
2. click the pencil to enter edit mode / rearrange the dash
3. try to resize/move when edge of insight is in bottom right corner of screen

## Environment

- [x] PostHog Cloud
- [ ] self-hosted PostHog (ClickHouse-based), version/commit: _please provide_
- [ ] self-hosted PostHog (Postgres-based, legacy), version/commit: _please provide_

**Comment by Twixes** [comment]
Thanks for flagging! We're about to release a redesign of the dashboard page which won't have this toast, so I'll close.
