### ISSUE TITLE
Don't create persons for $groupidentify events

### ISSUE THREAD

**Issue by macobo** [PostHog/posthog#7921]
## Is your feature request related to a problem?

When you call $groupidentify you need to pass in distinct_id as with every other event. This causes dummy persons to get created.

## Describe the solution you'd like

Make distinct_id not mandatory and don't create dummy persons for $groupidentify

## Additional context

cc @joesaunderson who brought this out as feedback :)

**Comment by joesaunderson** [comment]
Do you know when this will be launched @macobo - I was sad not to see it in 1.32.0. For context, waiting to rollout groups properly until this can be sorted (to avoid un-identified users showing in persons).
