### ISSUE TITLE
Getting 404 Not found when navigating to user

### ISSUE THREAD

**Issue by bollerdominik** [PostHog/posthog#794]
**Describe the bug**
I identify my users using their email. On the All Events page I click on a person with the name t@t.com and it sends me to https://site.com/person/t%40t.com. On this page I get a 404 Page not found.

I expect to see the persons page with all their events.

**Additional context**
This worked previously before 1.5.0. After updating to 1.5.0 all my identified persons link are broken. Unidentified users which have the generated UUID as the distinct_Id still work

**Comment by timgl** [comment]
@mariusandra I think this is probably due to us moving to kea-router. The following url doesn't get recognised as a valid path: `http://127.0.0.1:8000/person/t%40t.com`. I had a quick look at the kea-router source code but couldn't figure out what was going on there.

**Comment by mariusandra** [comment]
@timgl indeed! PR #795 fixes this

**Comment by timgl** [comment]
@bollerdominik That's fixed, thanks for raising this issue!

**Comment by bollerdominik** [comment]
Amazing! Thanks for the quick fix and the great product
