### ISSUE TITLE
Setting for self-hosted customers to choose recordings retention

### ISSUE THREAD

**Issue by rcmarron** [PostHog/posthog#7951]
## Is your feature request related to a problem?

Today, recording retention defaults to 3-weeks. This is set by a TTL in the `session_recording_events` table.

There is a trade-off here between keeping old recordings and using up storage, so we should allow customers to set this value to their preferences

## Describe the solution you'd like

Add an option to the project settings page for self-hosted clickhouse users.

Ideally, we would have this for cloud too, but that would require more work.

## Describe alternatives you've considered

Just give customers the SQL to run on their instance - it's in the docs now.

**Comment by macobo** [comment]
> Add an option to the project settings page for self-hosted clickhouse users.

Given this would site-wide this should be somewhere else. Perhaps a command you can run and static text + link to instructions in settings?

**Comment by rcmarron** [comment]
> Given this would site-wide this should be somewhere else. Perhaps a command you can run and static text + link to instructions in settings?

Ah really good point.

The other complicating factor is the date selector on the recordings page. Ideally, the maximum allowed date in that selector is kept in sync with the customer's retention time - otherwise, it's a confusing UX. So we would want to store the value somewhere.

It seems like the 'right' solution would be to have a settings page for the organization/instance, and this could live in there. Curious if we've had any other needs for such a page (cc @Twixes)

**Comment by paolodamico** [comment]
I was thinking we could store this in the DB (as we did previously in project settings) and whenever you change it, we would execute the `ALTER TABLE` statement. That way we can have it synced with the recordings list view and also you can change it easily via the UI.

To avoid introducing another page, maybe we can just have this in the instance status page?

**Comment by rcmarron** [comment]
> To avoid introducing another page, maybe we can just have this in the instance status page?

Because it's a potentially destructive action across all teams (e.g. setting retention to 1 day), I think it would need to live somewhere where only a "super admin" would have access. Makes me think @macobo's suggestion might be best. We'd add:
* A django command that:
    * Runs the `ALTER TABLE` statement
    * Stores the new value in the DB
* A description of this command on the project settings page (making it very clear that it would apply to all teams/projects on the instance)
* Make the date filter on the recordings page respect this new value

I also like this approach because changing this value could have a pretty big impact on the amount of storage you need for your instance, so by making it a Django command, the person running it likely also understands/manages their storage etc. - decreasing the risk that someone accidentally takes down their instance by filling up their storage after changing this setting.

**Comment by macobo** [comment]
This exists under instance settings.
