### ISSUE TITLE
Querying benchmarks - event sort key, removing person joins, JSON data storage

### ISSUE THREAD

**Issue by macobo** [PostHog/posthog#7962]
# Background

In [a query performance RFC](https://github.com/PostHog/product-internal/pull/240) I proposed a high level plan for increasing query performance for high-scale users.

In this issue I'm documenting benchmarks for some of the proposed bullet points.

## Methodology

The tested optimizations are:
1. **Having `event` in the events table sort key**
2. **Removing person/person_distinct_id** joins - testing some queries aggregating on distinct_id instead
3. **Better storage of JSON data** - As the feature is not yet ready, I will be using materialized columns to emulate the behavior.

As a dataset, I'm using [Clickhouse Github Events](https://ghe.clickhouse.tech/) dataset. After transformations, this dataset contained **140M persons**/**2.7B events**. All queries try to use the full dataset where possible.

The benchmark were run on a [`i3en.3xlarge` AWS instance](https://aws.amazon.com/ec2/instance-types/i3en/) with a lot of memory and fast disk.

 ### Cadveats

1. The dataset is not representative of a 'typical' analytics usecase - there's a lack of variety in the number of events and properties. 
2. Benchmarks are only useful for relative comparisons. Sharding, different datasets and different hardware will yield different results. Please don't take the absolute numbers to heart.

## Results

| Benchmark name | Baseline | Event sort key | No JOINs | Better JSON storage | Notes | 
| --- | --- | --- | --- | --- | --- |
| Trends query | 27.810s | 21.557s | | | |
| Trends query 2 | 9.864s | 1.098s | | | When using a rare event |
| Monthly active users | 97.868s* | 93.549s* | 69.739s | |
| Trends w/ event property filter | 650.609s | 471.5s | | 9.323s | |
| Trends w/ person property filter | 103.306s* | 94.436s* | 245.773s | 32.202s | Query with JOIN and materialized columns took 79s |
| Funnel query | 240.976s* | 201.607s* | 114.260s | | Only 2 years worth of data was used in query due to timeout issues. |
| Person property breakdown - top 25 values | OOM | OOM | 304.919s | 53.364s | Both baseline and event sorting (and materialization) OOMs before removing `person` join |

Every query benefitted from the optimizations to the left of it, e.g. No JOINs also used the optimized events table, better JSON storage also avoided JOINS.

Blank cells mean that the optimization would not affect this benchmark. 

Queries which required >30GiB of memory to run marked with *. On a typical instance these queries would have failed.

### Conclusions

The optimizations generally proposed under [the RFC](https://github.com/PostHog/product-internal/pull/240) seem valid based on the results.

#### Event in sort key

Each query in the above list got faster thanks to this because every one of them was filtering on events. This allowed clickhouse to skip reading data from disk, speeding up the query.

In practice the wins from this will be larger than shown here if users have more than 10 types of events as it allows skipping reading even more data.

#### Better JSON storage

We've already [written in depth about materialized columns](https://posthog.com/blog/clickhouse-materialized-columns). Based on descriptions of the upcoming [unstructured data feature](https://github.com/ClickHouse/ClickHouse/issues/23516) this will behave very similarly to materializing a lot of columns.

#### Removing person_distinct_id and person JOINs

This generally made all queries faster as hash joins in memory are really slow and person rows need to be materialized into memory. 

In many cases queries would not run at all without increasing the available memory to 80GB and even then there were failures.

The one case it didn't speed things up was filtering/breakdown by person property without materialized columns. This is due to the excessive amount of extra properties that needed to be read and parsed. We should be careful when introducing this feature and perhaps default to the old behavior if non-materialized columns are at play.

This optimization however also has a lot of other "hidden" benefits:
- A lot of queries simply ran out of memory with JOINS at 150M users - this was not an issue with any of the person_id queries.
- Timeseries queries suddenly become cachable meaning we can further speed up frequently run queries
- Decreases load on the cluster when sharding clickhouse becomes possible

## How to reproduce this benchmark?

See shell + sql files in https://gist.github.com/macobo/6563e830a3f1e2d724313e470ae1073f

## Additional context

cc @guidoiaquinti @neilkakkar @timgl @fuziontech @EDsCODE @hazzadous @marcushyett-ph in no particular order for the results

**Comment by marcushyett-ph** [comment]
A meta-point. All of these (even speeded up) query times feel pretty much too long for interactive queries (e.g. sit and watch it run). Would we be able to use caching of previous data etc to make this a faster experience for the user?

**Comment by macobo** [comment]
> All of these (even speeded up) query times feel pretty much too long for interactive queries (e.g. sit and watch it run).

This is intentional and I touched upon this in the issue: in a realistic setting you'd want both better hardware and sharding at these scales. [The RFC](https://github.com/PostHog/product-internal/pull/240) includes points for improving on both fronts.

The intent with this issue is to show relative improvements, which wouldn't be obvious very fast queries.

In practical terms I'm also limited on time - just loading the dataset in and preparing queries took 2 workdays - repeating this would give prettier numbers but very little additional insight. :sweat_smile: 

> Would we be able to use caching of previous data etc to make this a faster experience for the user?

Yes, that was also part of [the RFC](https://github.com/PostHog/product-internal/pull/240). This wasn't didn't benchmarked here since we don't yet know what that solution looks like exactly.

However we don't need to run any benchmarks to guess the performance gains since clickhouse queries scale with the amount of data read.
