### ISSUE TITLE
Bug: New Insight button doesn't create a new insight

### ISSUE THREAD

**Issue by joethreepwood** [PostHog/posthog#7965]
## Bug description

Clicking the '+' for a New Insight while looking at an existing insight doesn't do anything other than reset the current date range. It doesn't lead to a blank unnamed insight, or enter the 'edit' state where you can tailor the existing insight. 

This doesn't happen with dashboards. 

Video: https://drive.google.com/file/d/1tiV2TJjE4xLPd_b9yC5KbGm-VuLEdBPD/view?usp=sharing

## Expected behavior

I'd expect clicking '+' while looking at an existing insight to either enter me into the blank insight state (what happens when you enter the insight list and hit the New Insight button in the top right) or, potentially, to expose the edit options for the existing insight (not preferable). 

## How to reproduce

1. View existing insight
2. Click '+'
3.

## Environment

- [ ] PostHog Cloud
- [x] self-hosted PostHog (ClickHouse-based), version/commit: _please provide_
- [ ] self-hosted PostHog (Postgres-based, legacy), version/commit: _please provide_

**Comment by joethreepwood** [comment]
Ok, this is strange. 

While testing around this bug I was also occasionally seeing new insights created under the name 'Unnamed Insight' (which shouldn't happen, as they should now have randomised animal names). And other times I'd click the '+' and get the expected blank insight. 

Not sure what's going on here or if what I was experiencing was somehow a temporary bug or has already been fixed?

**Comment by Twixes** [comment]
This should be fixed now.
