### ISSUE TITLE
Timestamp field not used for event or action time

### ISSUE THREAD

**Issue by scleriot** [PostHog/posthog#7968]
## Bug description

When sending a timestamp to PostHog, the event is not considered having happened at this timestamp. It's still showing as having happened when it was received by PostHog

![image](https://user-images.githubusercontent.com/733474/148800881-3365a426-b720-4d18-9561-16f1e69f6b64.png)

When creating a time based insight, it's also considered at the event reception time

## Expected behavior

Events with a timestamp field set should be considered as having happened at this timestamp

## How to reproduce

1. Delay sending an event with a Timestamp set (we tried `time`, `timestamp`, `$time` and `$timestamp` fields)
2. Event time is set to event reception time and not Timestamp field

## Environment

- [x] PostHog Cloud

## Additional context

We need to be able to set the Timestamp manually because sometimes we batch send event, or our analytics queue is delayed and the event is sent a few minutes later to PostHog

**Comment by clarkus** [comment]
Related https://github.com/PostHog/posthog/issues/7876
