### ISSUE TITLE
Let's make an on-call runbook

### ISSUE THREAD

**Issue by rcmarron** [PostHog/posthog#7971]
I was on-call this past week, and I was paged a couple of times. Each time, I realized that I had no clue what the appropriate course of action was besides 'message James'. 

To make life more pleasant for @fuziontech and other people on the platform team, I think we should have a [runbook](https://www.pagerduty.com/resources/learn/what-is-a-runbook/) that lists out our pager-duty alerts and the actions that the person should take to try to resolve each one.

Hopefully, this would decrease the number of alerts escalated, make the person on-call more useful, and improve response times.

Related, we should also make sure that everyone that goes on call has access to the systems needed to take the actions in the runbook.

cc @fuziontech @timgl

**Comment by fuziontech** [comment]
Step 1 is complete - there is still a lot of work to be done on a per page/alert level. That is my next top priority.
https://github.com/PostHog/product-internal/tree/main/infrastructure/runbooks
