### ISSUE TITLE
Case sensitivity in taxonomy filter

### ISSUE THREAD

**Issue by paolodamico** [PostHog/posthog#7990]
## Bug description

When searching events/props/cohorts in the taxonomy filter, we do so with case sensitivity, which I believe leads to a poor experience. For instance when I use the `insight viewed` event, and want to filter by funnels, searching `fun` yields nothing, while searching `FUN` shows me what I want to see.

## Expected behavior

Search should work case insensitive, but case sensitivity should be used as a tie breaker.

## How to reproduce

See description above.

## Environment

- [ ] PostHog Cloud
- [ ] self-hosted PostHog (ClickHouse-based), version/commit: _please provide_
- [ ] self-hosted PostHog (Postgres-based, legacy), version/commit: _please provide_

## Additional context

Related to improving client-side search.

**Comment by mariusandra** [comment]
Can you add a gif? It looks like this for me on cloud.

![2022-01-13 11 21 40](https://user-images.githubusercontent.com/53387/149312053-74989cf2-b04c-4749-9b44-93724c5c6056.gif)

**Comment by paolodamico** [comment]
This was actually happening when applying a filter to an event based on an event property but it looks like your recent changes fixed it. Thanks @mariusandra!
