### ISSUE TITLE
Lifecycle tooltips are missing key information

### ISSUE THREAD

**Issue by macobo** [PostHog/posthog#7994]
## Bug description

A lifecycle graph looks currently like follows:

![image](https://user-images.githubusercontent.com/148820/149090800-cab7eeff-797e-45d9-955b-dd72f9216375.png)

The tooltip is useless given it doesn't say which cohort the user belongs to. Also it should likely include the relevant date for the tooltip.

## Expected behavior

Tooltip says NEW/Returning/etc, includes date

## How to reproduce

Open a lifecycle graph

## Environment

- [x] PostHog Cloud
- [ ] self-hosted PostHog (ClickHouse-based), version/commit: _please provide_
- [ ] self-hosted PostHog (Postgres-based, legacy), version/commit: _please provide_

**Comment by jamesefhawkins** [comment]
I'd add that the tooltips for the actual lifecycle are pretty useless:
<img width="417" alt="Screenshot 2022-01-12 at 11 38 52" src="https://user-images.githubusercontent.com/47497682/149133651-beddd7c9-8e7c-4cd7-8fb8-5a68d8550535.png">

What does "new" mean? Within the date range selected? Something else? All of them should be more precise.

**Comment by clarkus** [comment]
Related https://github.com/PostHog/posthog/issues/7913

**Comment by clarkus** [comment]
Jumping in to say that a stacked bar visualization isn't the most effective default for this chart. I think grouped bars would be a bit easier to parse. This gives each bar the same starting offset which means it'll be easier to associate that bar with a specific value. Stacked bars would be better if we were trying to communicate a sum of each lifecycle segment. 

![Lifecycle - grouped bars + tooltip](https://user-images.githubusercontent.com/254612/149171623-03ce4fd0-6454-478f-b8a7-8f5e913d4cf8.png)

**Comment by macobo** [comment]
@clarkus moving that suggestion to a separate issue to keep this easily fixable :)

**Comment by macobo** [comment]
This is not yet fixed - tooltips james mentioned handled in https://github.com/PostHog/posthog/pull/8028
