### ISSUE TITLE
Add direct user feedback integration

### ISSUE THREAD

**Issue by lizat** [PostHog/posthog#7998]
## Is your feature request related to a problem?

We need a way to allow users to independently offer their feedback, respond to them, and add tasks to a task manager where appropriate (e.g. clickup)

## Describe the solution you'd like

add a 'contribute site feedback' item to site
user can use the link to provide unsolicited feedback
able to review and respond, flag the user in different ways
able to create a related Clickup task

## Describe alternatives you've considered
just starting to explore something better than a siimple 'contact' form combined with spreadsheet

**Comment by mariusandra** [comment]
We have surveys now 🎉
