### ISSUE TITLE
Bug: Request Line is too large (4246 > 4094)

### ISSUE THREAD

**Issue by joethreepwood** [PostHog/posthog#8000]
## Bug description

Working on an insight to [see MQLs by geo](https://app.posthog.com/insights/pzLA2GSk/edit?insight=TRENDS&events=%5B%5D&actions=%5B%7B%22id%22%3A%222671%22%2C%22math%22%3Anull%2C%22name%22%3A%22User%20Signed%20Up%22%2C%22type%22%3A%22actions%22%2C%22order%22%3A0%2C%22properties%22%3A%5B%5D%2C%22custom_name%22%3A%22TOTAL%20SIGN-UPS%22%2C%22math_property%22%3Anull%7D%2C%7B%22id%22%3A%222671%22%2C%22math%22%3Anull%2C%22name%22%3A%22User%20Signed%20Up%22%2C%22type%22%3A%22actions%22%2C%22order%22%3A1%2C%22properties%22%3A%5B%7B%22key%22%3A%22%24geoip_country_name%22%2C%22value%22%3A%5B%22France%22%5D%2C%22operator%22%3A%22exact%22%2C%22type%22%3A%22event%22%7D%5D%2C%22custom_name%22%3A%22FRANCE%22%2C%22math_property%22%3Anull%7D%2C%7B%22id%22%3A%222671%22%2C%22math%22%3Anull%2C%22name%22%3A%22User%20Signed%20Up%22%2C%22type%22%3A%22actions%22%2C%22order%22%3A2%2C%22properties%22%3A%5B%7B%22key%22%3A%22%24geoip_country_name%22%2C%22value%22%3A%5B%22United%20Kingdom%22%5D%2C%22operator%22%3A%22exact%22%2C%22type%22%3A%22event%22%7D%5D%2C%22custom_name%22%3A%22UK%22%2C%22math_property%22%3Anull%7D%2C%7B%22id%22%3A%222671%22%2C%22math%22%3Anull%2C%22name%22%3A%22User%20Signed%20Up%22%2C%22type%22%3A%22actions%22%2C%22order%22%3A3%2C%22properties%22%3A%5B%7B%22key%22%3A%22%24geoip_country_name%22%2C%22value%22%3A%5B%22USA%22%2C%22United%20States%22%5D%2C%22operator%22%3A%22exact%22%2C%22type%22%3A%22event%22%7D%5D%2C%22custom_name%22%3A%22USA%22%2C%22math_property%22%3Anull%7D%2C%7B%22id%22%3A%222671%22%2C%22math%22%3Anull%2C%22name%22%3A%22User%20Signed%20Up%22%2C%22type%22%3A%22actions%22%2C%22order%22%3A4%2C%22properties%22%3A%5B%7B%22key%22%3A%22%24geoip_country_name%22%2C%22value%22%3A%5B%22Germany%22%5D%2C%22operator%22%3A%22exact%22%2C%22type%22%3A%22event%22%7D%5D%2C%22custom_name%22%3A%22GERMANY%22%2C%22math_property%22%3Anull%7D%2C%7B%22id%22%3A%222671%22%2C%22math%22%3Anull%2C%22name%22%3A%22User%20Signed%20Up%22%2C%22type%22%3A%22actions%22%2C%22order%22%3A5%2C%22properties%22%3A%5B%7B%22key%22%3A%22%24geoip_country_name%22%2C%22value%22%3A%5B%22India%22%5D%2C%22operator%22%3A%22exact%22%2C%22type%22%3A%22event%22%7D%5D%2C%22custom_name%22%3A%22INDIA%22%2C%22math_property%22%3Anull%7D%5D&date_to&display=ActionsLineGraph&interval=day&date_from=-90d&new_entity=%5B%5D&properties=%5B%7B%22key%22%3A%22hubspot_score%22%2C%22type%22%3A%22person%22%2C%22value%22%3A%2299%22%2C%22operator%22%3A%22gt%22%7D%5D&filter_test_accounts=true). It was working fine for analyzing total sign-ups, India, US, UK, Germany and France. 

Then I decided to add a few more. Russia, Spain, China. Then the query started giving a generic error and wouldn't load. 

I figured I'd add a few more filters, then try to solve the error. Brazil, Japan. Then it started giving a complete error. 

<img width="440" alt="Screenshot 2022-01-12 at 13 55 28" src="https://user-images.githubusercontent.com/84011561/149153568-b9a66397-5fca-4423-9b79-ec9525b95cb1.png">

Refreshing hasn't worked, but the link above works as normal - albeit without most of the later filters I added.

## Expected behavior

MQLs by geo. 

## How to reproduce

1. As above
2.
3.

## Environment

- [ ] PostHog Cloud
- [ ] self-hosted PostHog (ClickHouse-based), version/commit: _please provide_
- [ ] self-hosted PostHog (Postgres-based, legacy), version/commit: _please provide_

**Comment by Twixes** [comment]
I suppose this will be solved by https://github.com/PostHog/posthog/pull/7985.

**Comment by mariusandra** [comment]
Nope, that addresses something else, but is a prerequisite for this. I'll wrap up that today, and work on this next.

For context, this specific bug will be resolved if we move the filters in the insight URL from `?bla` to `#bla`, so we don't send them to the server.

**Comment by mariusandra** [comment]
This issue has been resolved since #8228 went in a week ago. Now that #8184 is also in, it's double resolved. Closing.
