### ISSUE TITLE
Feature Flag rollout %s are not accurate

### ISSUE THREAD

**Issue by neilkakkar** [PostHog/posthog#8001]
## Bug description

(I don't know if there's a way to solve this well): When setting a rollout % on a FeatureFlag to 50%, I'd expect half the users to see it.

This isn't the case. The ratio is more like 45-55, and **gets worse with time.**.

[Here's an example](https://app.posthog.com/insights/5F7p6tHX/edit?insight=TRENDS&interval=day&display=ActionsLineGraphCumulative&actions=%5B%5D&events=%5B%7B%22id%22%3A%22%24pageview%22%2C%22name%22%3A%22%24pageview%22%2C%22type%22%3A%22events%22%2C%22order%22%3A0%2C%22math%22%3A%22dau%22%7D%5D&filter_test_accounts=false&breakdown=%24feature%2Ftest-half-rolled-out&breakdown_type=event&date_from=2022-01-08&date_to=2022-01-15&new_entity=%5B%5D&hidden_legend_keys=%7B%7D&properties=%5B%5D)

[Here's a multivariate example](https://app.posthog.com/insights/5F7p6tHX/edit?insight=TRENDS&interval=day&display=ActionsLineGraphCumulative&actions=%5B%5D&events=%5B%7B%22id%22%3A%22%24pageview%22%2C%22name%22%3A%22%24pageview%22%2C%22type%22%3A%22events%22%2C%22order%22%3A0%2C%22math%22%3A%22dau%22%7D%5D&filter_test_accounts=false&breakdown=%24feature%2Ftest-multivariate-split&breakdown_type=event&date_from=2022-01-08&date_to=2022-01-15&new_entity=%5B%5D&hidden_legend_keys=%7B%7D&properties=%5B%5D).

The cause has been explored well in: #6043 . This isn't a problem with just multivariate testing.

Now, this is fine for rolling out new things (mostly), since the numbers don't have to be precise. But for running manual experiments, this is terrible (also why our Experimentation product is built off of multivariates only) - and gives false confidence to users who want to try running experiments. Even internally. For example: [our experiment for product-cues](https://github.com/PostHog/posthog/pull/7301#issuecomment-1010371055)

## Environment

- [X] PostHog Cloud
- [X] self-hosted PostHog (ClickHouse-based), version/commit: _please provide_
- [X] self-hosted PostHog (Postgres-based, legacy), version/commit: _please provide_

## Additional context

I don't know if we can solve this at all.  But, probs need some way to tell users not to try running experiments with "normal" FFs.

**Comment by paolodamico** [comment]
Related to #1610, previously what I would do is normalize experiments by doing a ratio of the metric I care about among active users with/without the feature flag, but not ideal

**Comment by timgl** [comment]
This might just be the result of the hashing algorithm not giving a perfect distribution over smaller numbers. [See code.](https://gist.github.com/timgl/4ea5f1dad8d3b4329be77561beb7e49f)

When running over <10k identifiers it starts of with quite a big gap and then closes, which is what I suspect is what's happening here as well. 
![image](https://user-images.githubusercontent.com/1727427/149199968-16d59c8a-6555-42ba-97a2-9f192b714d99.png)

**Comment by neilkakkar** [comment]
I don't think this is the case. (As one data point, there's ~10k events in the examples above^) Take the multivariate example above: All 3 variants are very close to each other (same hashing algorithm), and then there's this pile of leftover `None`s, which get created for whatever reason: `/decide` request coming in too late / ???? / ????.

**Comment by neilkakkar** [comment]
To test the above hypothesis: [This multivariate breakdown ](https://app.posthog.com/insights/5F7p6tHX/edit?insight=TRENDS&interval=day&display=ActionsLineGraphCumulative&actions=%5B%5D&events=%5B%7B%22id%22%3A%22insight%20analyzed%22%2C%22name%22%3A%22insight%20analyzed%22%2C%22type%22%3A%22events%22%2C%22order%22%3A0%2C%22math%22%3A%22dau%22%7D%5D&filter_test_accounts=false&breakdown=%24feature%2Ftest-multivariate-split&breakdown_type=event&date_from=2022-01-08&date_to=2022-01-15&new_entity=%5B%5D&hidden_legend_keys=%7B%7D&properties=%5B%5D) on an event that happens pretty late (so hopefully not influenced by `/decide` response).

As expected, the number of Nones go down, but a few still exist, which means there's at least one more problem with giving FFs that I'm not aware of.

And, kindof interesting: `client_request_failure` has `None`s [comparable to the rest](https://app.posthog.com/insights/5F7p6tHX/edit?insight=TRENDS&interval=day&display=ActionsLineGraphCumulative&actions=%5B%5D&events=%5B%7B%22id%22%3A%22client_request_failure%22%2C%22name%22%3A%22client_request_failure%22%2C%22type%22%3A%22events%22%2C%22order%22%3A0%2C%22math%22%3A%22dau%22%7D%5D&filter_test_accounts=false&breakdown=%24feature%2Ftest-multivariate-split&breakdown_type=event&date_from=2022-01-08&date_to=2022-01-15&new_entity=%5B%5D&hidden_legend_keys=%7B%7D&properties=%5B%5D)

**Comment by neilkakkar** [comment]
Wherever precision is required, we ought to use multivariate, not simple flags.

Chalking up the None's remaining in multivariates to `/decide` being late, post people closing browsers.
