### ISSUE TITLE
Insights tooltip rendering problems

### ISSUE THREAD

**Issue by tiina303** [PostHog/posthog#8014]
## Bug description

If there's lots of lines the hover pane becomes not readable:
<img width="273" alt="Screen Shot 2022-01-12 at 23 58 27" src="https://user-images.githubusercontent.com/890921/149236765-b7447c3c-376c-417b-83e7-4f250ce39d09.png">

The ordering is hard to interpret:
<img width="424" alt="Screen Shot 2022-01-12 at 23 57 54" src="https://user-images.githubusercontent.com/890921/149237165-5bd9aa8d-173d-4bc7-9020-ed21c11b23f0.png">

^ I need to closely look at the table to know yellow is 1.29.1

## Expected behavior

For ordering we sort them based on the value or color the values if we want to keep them alphabetical as they are now so it's easily visually detectable which is which.

## How to reproduce

1. https://app.posthog.com/insights/DFGqpUoM?events=%5B%7B%22id%22%3A%22instance%20status%20report%22%2C%22math%22%3A%22dau%22%2C%22name%22%3A%22instance%20status%20report%22%2C%22type%22%3A%22events%22%2C%22order%22%3A0%2C%22properties%22%3A%5B%7B%22key%22%3A%22realm%22%2C%22type%22%3A%22event%22%2C%22value%22%3A%5B%22cloud%22%5D%2C%22operator%22%3A%22is_not%22%7D%5D%2C%22custom_name%22%3A%22self-hosted%22%7D%5D&actions=%5B%5D&display=ActionsLineGraph&insight=TRENDS&interval=week&breakdown=posthog_version&date_from=-30d&new_entity=%5B%5D&properties=%5B%7B%22key%22%3A%22realm%22%2C%22type%22%3A%22event%22%2C%22value%22%3A%5B%22cloud%22%5D%2C%22operator%22%3A%22is_not%22%7D%5D&breakdown_type=event&filter_test_accounts=true (too many items to show)
2. https://app.posthog.com/insights/QEsYvzvb?events=%5B%7B%22id%22%3A%22organization%20usage%20report%22%2C%22math%22%3A%22dau%22%2C%22name%22%3A%22organization%20usage%20report%22%2C%22type%22%3A%22events%22%2C%22order%22%3A0%2C%22properties%22%3A%5B%5D%2C%22custom_name%22%3A%22self-hosted%20unique%20users%22%7D%5D&actions=%5B%5D&display=ActionsLineGraph&insight=TRENDS&interval=day&breakdown=posthog_version&date_from=-90d&new_entity=%5B%5D&properties=%5B%7B%22key%22%3A%22realm%22%2C%22type%22%3A%22event%22%2C%22value%22%3A%5B%22cloud%22%5D%2C%22operator%22%3A%22is_not%22%7D%5D&breakdown_type=event&filter_test_accounts=true (ordering confusing to interpret)

## Environment

- [x] PostHog Cloud
- [ ] self-hosted PostHog (ClickHouse-based), version/commit: _please provide_
- [ ] self-hosted PostHog (Postgres-based, legacy), version/commit: _please provide_

**Comment by macobo** [comment]
cc @mariusandra, @paolodamico and @alexkim205 for visibility (note to tiina: I've left the team-tagging often to them)

**Comment by tiina303** [comment]
Other (related?) problems:
1. pie chart uses the original event names (not what I renamed them to)
2. value chart numbers likely wrong? Don't match the 2 unique instances we see in the pop-up, but the value is much higher on the chart

This insight: https://app.posthog.com/insights/Bw4y1Zqp?insight=TRENDS&date_from=-30d&actions=%5B%5D&events=%5B%7B%22id%22%3A%22helm_install%22%2C%22name%22%3A%22helm_install%22%2C%22type%22%3A%22events%22%2C%22order%22%3A0%2C%22math%22%3A%22unique_group%22%2C%22math_group_type_index%22%3A1%2C%22properties%22%3A%5B%7B%22key%22%3A%22operation%22%2C%22value%22%3A%5B%22install%22%5D%2C%22operator%22%3A%22exact%22%2C%22type%22%3A%22event%22%7D%5D%2C%22custom_name%22%3A%22helm%20install%22%7D%2C%7B%22id%22%3A%22helm_install%22%2C%22name%22%3A%22helm_install%22%2C%22type%22%3A%22events%22%2C%22order%22%3A1%2C%22math%22%3A%22unique_group%22%2C%22math_group_type_index%22%3A1%2C%22properties%22%3A%5B%7B%22key%22%3A%22operation%22%2C%22value%22%3A%5B%22upgrade%22%5D%2C%22operator%22%3A%22exact%22%2C%22type%22%3A%22event%22%7D%5D%2C%22custom_name%22%3A%22helm%20upgrade%22%7D%2C%7B%22id%22%3A%22organization%20usage%20report%22%2C%22type%22%3A%22events%22%2C%22order%22%3A2%2C%22name%22%3A%22organization%20usage%20report%22%2C%22properties%22%3A%5B%5D%2C%22math%22%3A%22unique_group%22%2C%22math_group_type_index%22%3A1%2C%22custom_name%22%3A%22heartbeat%22%7D%5D&display=ActionsBarValue&interval=day&funnel_to_step=1&funnel_viz_type=trends&funnel_window_interval_unit=day&funnel_window_interval=3&exclusions=%5B%5D&aggregation_group_type_index=1&funnel_from_step=0&date_to&properties=%5B%5D&new_entity=%5B%5D&show_legend=false#personModal=%7B%22action%22%3A%7B%22id%22%3A%22helm_install%22%2C%22type%22%3A%22events%22%2C%22order%22%3A0%2C%22name%22%3A%22helm_install%22%2C%22custom_name%22%3A%22helm%20install%22%2C%22math%22%3A%22unique_group%22%2C%22math_property%22%3Anull%2C%22math_group_type_index%22%3A1%2C%22properties%22%3A%5B%7B%22key%22%3A%22operation%22%2C%22value%22%3A%5B%22install%22%5D%2C%22operator%22%3A%22exact%22%2C%22type%22%3A%22event%22%7D%2C%7B%22key%22%3A%22%24group_1%22%2C%22value%22%3A%22%22%2C%22operator%22%3A%22is_not%22%2C%22type%22%3A%22event%22%7D%5D%7D%2C%22label%22%3A%22helm_install%22%2C%22date_from%22%3A%22-30d%22%2C%22date_to%22%3A%22%22%2C%22filters%22%3A%7B%22insight%22%3A%22TRENDS%22%2C%22date_from%22%3A%22-30d%22%2C%22actions%22%3A%5B%5D%2C%22events%22%3A%5B%7B%22id%22%3A%22helm_install%22%2C%22name%22%3A%22helm_install%22%2C%22type%22%3A%22events%22%2C%22order%22%3A0%2C%22math%22%3A%22unique_group%22%2C%22math_group_type_index%22%3A1%2C%22properties%22%3A%5B%7B%22key%22%3A%22operation%22%2C%22value%22%3A%5B%22install%22%5D%2C%22operator%22%3A%22exact%22%2C%22type%22%3A%22event%22%7D%5D%2C%22custom_name%22%3A%22helm%20install%22%7D%2C%7B%22id%22%3A%22helm_install%22%2C%22name%22%3A%22helm_install%22%2C%22type%22%3A%22events%22%2C%22order%22%3A1%2C%22math%22%3A%22unique_group%22%2C%22math_group_type_index%22%3A1%2C%22properties%22%3A%5B%7B%22key%22%3A%22operation%22%2C%22value%22%3A%5B%22upgrade%22%5D%2C%22operator%22%3A%22exact%22%2C%22type%22%3A%22event%22%7D%5D%2C%22custom_name%22%3A%22helm%20upgrade%22%7D%2C%7B%22id%22%3A%22organization%20usage%20report%22%2C%22type%22%3A%22events%22%2C%22order%22%3A2%2C%22name%22%3A%22organization%20usage%20report%22%2C%22properties%22%3A%5B%5D%2C%22math%22%3A%22unique_group%22%2C%22math_group_type_index%22%3A1%2C%22custom_name%22%3A%22heartbeat%22%7D%5D%2C%22display%22%3A%22ActionsBarValue%22%2C%22interval%22%3A%22day%22%2C%22funnel_to_step%22%3A1%2C%22funnel_viz_type%22%3A%22trends%22%2C%22funnel_window_interval_unit%22%3A%22day%22%2C%22funnel_window_interval%22%3A3%2C%22exclusions%22%3A%5B%5D%2C%22aggregation_group_type_index%22%3A1%2C%22funnel_from_step%22%3A0%2C%22date_to%22%3Anull%2C%22properties%22%3A%5B%5D%2C%22new_entity%22%3A%5B%5D%2C%22show_legend%22%3Afalse%7D%2C%22breakdown_value%22%3A%22%22%7D

<img width="1523" alt="Screen Shot 2022-01-14 at 18 59 16" src="https://user-images.githubusercontent.com/890921/149563002-b7c56fe0-8c01-43ea-b75e-1d0e2bb329e1.png">
