### ISSUE TITLE
New tooltips do not respect group types

### ISSUE THREAD

**Issue by macobo** [PostHog/posthog#8026]
## Bug description

When analyzing something by groups, the new tooltips look like following:

![image](https://user-images.githubusercontent.com/148820/149342253-c0230fa0-8ab7-44a2-9251-598230e03df3.png)

## Expected behavior

Tooltip should say `Click to view organization(s)`

## How to reproduce

1. Go to insights
2. Aggregate by a group type
3. Hover

## Environment

- [x] PostHog Cloud
- [ ] self-hosted PostHog (ClickHouse-based), version/commit: _please provide_
- [ ] self-hosted PostHog (Postgres-based, legacy), version/commit: _please provide_

## Additional context

cc @alexkim205, @mariusandra @paolodamico Please keep groups in mind when designing for or implementing new features.

**Comment by macobo** [comment]
This is not fixed: for funnel trends the label is still wrong. 
![image](https://user-images.githubusercontent.com/148820/149484155-a1cc54d0-7f14-43e2-830a-7f20dc6c5773.png)

It's worth doing a deep dive into _all_ analytics features when fixing this.

**Comment by macobo** [comment]
Same for retention trends.

**Comment by alexkim205** [comment]
This should address aggregation group indices for all insight types. #8095
