### ISSUE TITLE
Paths - events and page views to be mixed

### ISSUE THREAD

**Issue by jamesefhawkins** [PostHog/posthog#803]
**Is your feature request related to a problem? Please describe.**

The paths feel close to being more powerful but a little weird to use at the moment. 

The main use case is "I want to know how people are interacting with my website and app at a detailed level - which pages are they visiting, which buttons are the clicking, and what order is this all happening in.

**Describe the solution you'd like**

On the paths page, to be able to view page views and events in the same visualization.

That'd mean you could see things like "people tend to from page X to Y, then fill out form Z, but quit halfway through".

**Describe alternatives you've considered**

There isn't one at the moment.

**Comment by Twixes** [comment]
This is now possible though seems quite noisy.
