### ISSUE TITLE
Lifecycle first period is always blank

### ISSUE THREAD

**Issue by macobo** [PostHog/posthog#8031]
## Bug description

See the following lifecycle chart: 
![image](https://user-images.githubusercontent.com/148820/149353472-09ea189d-6556-4722-8484-e7a076657f51.png)

The first period should not be empty

Bug introduced in #8021 

## Expected behavior

The first item should not be blank.

As for how many items there should be - not sure. Should bucket from Dec 27th be included in this query?

## How to reproduce

1. Go to insights > Lifecycle
2. Select non-week group by
3. Play with different time ranges

## Environment

- [x] PostHog Cloud
- [ ] self-hosted PostHog (ClickHouse-based), version/commit: _please provide_
- [ ] self-hosted PostHog (Postgres-based, legacy), version/commit: _please provide_

## Additional context

cc @EDsCODE curious what you think the behavior should be for e.g. 14 days grouped by weeks if the days don't exactly line up. Including one extra period seems OK to me, except when e.g. showing 14 days grouped by months - you could end up fetching 2.5 months worth of data for that.

**Comment by liyiy** [comment]
I think we should avoid edge cases and default to less data shown than more since the user can always just extend the date range to 30 if 14 days wasn't enough

**Comment by EDsCODE** [comment]
Ideally, what would happen is that you take the date range, start with the beginning of the range, and then build intervals forward. We don't do this for any of our time series charts so to stay consistent with those for now, it would be including the extra period if the date range dips into it.

**Comment by macobo** [comment]
@EDsCODE can you clarify a bit - given a last 14 days graph on Jan 13th, what would the first and last dates be if grouping by day? By week? By month?

**Comment by EDsCODE** [comment]
By day,
Dec 31, Jan 1, Jan 2, Jan 3, ....

By week:
Dec 31 - Jan 6, Jan 7 - Jan 13

By month:
Dec 31 - Jan 31

**Comment by paolodamico** [comment]
@EDsCODE's proposal makes sense. That way we avoid the empty graph, and is intuitively what you expect. From the example above I believe by month should be: Dec 31 - Jan 13, right?

**Comment by EDsCODE** [comment]
Technically yes, but I think labelling wise it would make sense to just show a month period and somehow denote that it's not complete yet

**Comment by macobo** [comment]
The first two examples work, however for Dec 31-Jan 31 we'd in reality be fetching 14 days (the time range) + 31 days worth of data. We use the previous period we need to use to calculate whether users are dormant, returning or resurrecting.

That kind of works, but is confusing imo. How about we disable "month" option if the time range is less than 90 days?

**Comment by EDsCODE** [comment]
I'm open to that too. it'll prevent combinations that don't make intuitive sense

**Comment by paolodamico** [comment]
Makes sense but let's add a clear label that explains why the option is disabled and how to "fix" it.

**Comment by macobo** [comment]
PR coming up. Another tricky edge-case is handling "week" interval when looking at e.g. 30 days. Will get something sane-ish working, all of this needs rethinking though.

**Comment by macobo** [comment]
Another edge case worth considering is what about "week" interval over 30 days given they don't line up.

Thinking about it again with a fresh head today I am more inclined to make this all work by:
- Truncating the dates - e.g. months always start on 1st of Month, weeks on Monday
- Rounding upwards if the interval does not line up

That seems to be the behavior we have in trends as well. Kind of at least: we don't do the "rounding upwards" bit at all - so if you group by "month" and select 30 days or 90 days you will get different results for the previous months.

I'll go this way for now - PR coming up for lifecycle, will follow this up with a separate issue.
