### ISSUE TITLE
Speed up e2e workflow

### ISSUE THREAD

**Issue by EDsCODE** [PostHog/posthog#805]
**Is your feature request related to a problem? Please describe.**
E2E test is really slow

**Describe the solution you'd like**
Provide a method to reduce the runtime needed

**Describe alternatives you've considered**
leave it as is

**Additional context**

***Thank*** you for your feature request - we love each and every one!

**Comment by Twixes** [comment]
They now run somewhat faster. Their nature forces them to be not-really-fast though…
