### ISSUE TITLE
Events CSV export is flaky

### ISSUE THREAD

**Issue by Twixes** [PostHog/posthog#8051]
## Bug description

It seems that sometimes when going to the `events.csv` endpoint via the "Export events" button, there are 0 events, which results in just a white page instead of anything being downloaded. Not sure why though, in local testing I saw that the same ClickHouse query is always the same, but occasionally it returns zero rows.
[This issue was brought up in a customer channel.](https://posthog.slack.com/archives/C01HZB27BGX/p1642134541003200)

## Expected behavior

"Export events" should ALWAYS result in a CSV being downloaded.

## How to reproduce

1. Go to Events.
2. Click "Export events".
3. Usually it will work, but sometimes – especially just after the page had loaded – not. 🤔

## Environment

- [x] PostHog Cloud
- [ ] self-hosted PostHog (ClickHouse-based), version/commit: _please provide_
- [ ] self-hosted PostHog (Postgres-based, legacy), version/commit: _please provide_

**Comment by macobo** [comment]
I think the issue was introduced in https://github.com/PostHog/posthog/pull/7130, cc @pauldambra - window.location.href changing is likely being listened to in some cases.

**Comment by Twixes** [comment]
I thought window.location.href is related too so I created #8052, but closed that after I found it to not really change much. What @timgl [suggested to the customer](https://posthog.slack.com/archives/C01HZB27BGX/p1642152039004700?thread_ts=1642134541.003200&cid=C01HZB27BGX) to the customer was "Try removing the `&orderBy=%5B"-timestamp"%5D` from the URL" and that apparently somehow helped. 🤔

**Comment by pauldambra** [comment]
related -> https://github.com/PostHog/posthog/issues/7015

Feels like we need a better solution.... 🤔

**Comment by tiina303** [comment]
When I tried it the url ended with `after=2022-01-18T00%3A19%3A00.230000%2B00%3A00` (aka now) resulting in 0 events and white page, removing that `after` filter helped. The customer might have removed both the timestamp and after filter.

**Comment by timgl** [comment]
@Twixes What's the progress here? can we just remove orderBy or make sure the API can handle it?

**Comment by pauldambra** [comment]
> When I tried it the url ended with after=2022-01-18T00%3A19%3A00.230000%2B00%3A00 (aka now) resulting in 0 events and white page

Hmmm... 

There's some logic in the `eventsTableLogic` that creates that `after` which is being changed as part of #8107. If @Twixes isn't looking at this. I'm happy to revisit this after #8107 is merged to see if that happens to fix this

**Comment by tiina303** [comment]
Another user report (confirms removing `after` param works): https://posthogusers.slack.com/archives/CTLTM70RM/p1643147996023400

**Comment by pauldambra** [comment]
#8247 should have resolved this

**Comment by pauldambra** [comment]
Ah,

for PostHog team we now generate this query 

```
SELECT uuid,
       event,
       properties,
       timestamp,
       team_id,
       distinct_id,
       elements_chain,
       created_at
  FROM events
 where team_id = 2
   AND timestamp > '2021-01-25 23:36:01.158000'
   AND timestamp < '2022-01-25 23:44:21.450916'
 ORDER BY toDate(timestamp) DESC, timestamp DESC
 LIMIT 10001
```

and ClickHouse reports

```
DB::Exception: Memory limit (for query) exceeded: would use 37.26 GiB (attempt to allocate chunk of 8039792 bytes), maximum: 37.25 GiB (version 21.6.5.37 (official build))
```

#8280 is a workaround to reduce the limit so the query can succeed

**Comment by pauldambra** [comment]
This _should_ be fixed now...
