### ISSUE TITLE
Name insights automatically (but leave editable)

### ISSUE THREAD

**Issue by jamesefhawkins** [PostHog/posthog#8053]
## Is your feature request related to a problem?

We have quite funny insight names created by default, that make no sense to a team member seeing them - adding clutter / meaning you could be missing out interesting stuff:

<img width="568" alt="Screenshot 2022-01-14 at 09 45 39" src="https://user-images.githubusercontent.com/47497682/149494640-ed676297-2b69-4681-9ef3-0fef7282719e.png">

## Describe the solution you'd like

Automatically populate the name of the Insight as you edit the Insight.

For example:

Series A: Showing X counted by Y filtered by Z Breakdown by A Filtered by B
Series B: Showing D counted by E filtered by F Breakdown by G Filtered by H

Could be:

"X (Y) filtered by Y and B, by A + ..."

This would be quite wordy but it'd make everyone much more searchable.

## Describe alternatives you've considered

Click into insights to figure out what they are.

## Additional context

Think this could help collaboration.

**Comment by clarkus** [comment]
Related https://github.com/PostHog/posthog/issues/7622

**Comment by Twixes** [comment]
I will close as a duplicate of #7622, but definitely something we'll want to improve.
