### ISSUE TITLE
Insights date filtering/interval logic is confusing

### ISSUE THREAD

**Issue by macobo** [PostHog/posthog#8059]
## Is your feature request related to a problem?

In insights you can select a time range and a group by interval. Combining these can lead to unexpected results.

For example, on Jan 14th selecting "week" interval and 30 days shows dates of 9th of January, 2nd January, 26th December, 19th December and 12th December.

This has couple of issues:
- Weeks start on Sunday not Monday, which is meh
- 12th december is over 30 days ago
- Changing the timerange to 90 days, the result for 12th december increases.

Same applies for e.g. choosing month interval

One combination which is also confusing is last 14 days with month interval.

Another thing is that choosing "last 7 days" shows 8 datapoints on the graph.

## Describe the solution you'd like

???

## Additional context

This feedback is given from the perspective of trends, but general problems apply everywhere.

Related issue: https://github.com/PostHog/posthog/issues/8031

cc @paolodamico @EDsCODE

**Comment by macobo** [comment]
@kappa90 was this (plus other linked issues) intentionally closed?

**Comment by kappa90** [comment]
> @kappa90 was this (plus other linked issues) intentionally closed?

Sorry, I'm reopening the issues, the original PR was not supposed to be an experiment but rather a fix to these issues. I'm going to close these once the experiment is confirmed. Thanks for pointing this out!

**Comment by kappa90** [comment]
Incorrectly closed after #10462, which is meant to run as an experiment
