### ISSUE TITLE
/api/insight/session API is not working

### ISSUE THREAD

**Issue by agrubi** [PostHog/posthog#8069]
## Bug description

`GET /api/insight/session` API is not working any more

## Expected behavior

It should return session insights

## How to reproduce

1. `curl https://app.posthog.com/api/insight/session/ -H 'Authorization: Bearer <api token>'`

Returns: `{"type":"invalid_request","code":"not_found","detail":"Not found.","attr":null}` instead of actual result

## Environment

- [x] PostHog Cloud

**Comment by paolodamico** [comment]
Hey @agrubi! The sessions endpoint was deprecated ~2 months ago (https://posthog.com/blog/sessions-removal) and has been recently removed now.

**Comment by agrubi** [comment]
Thanks! In this case should probably update the docs here: https://posthog.com/docs/api/insights#session

**Comment by agrubi** [comment]
Is there some API I could use to get this information:
- how many times a user logged in last week
- average session time for a user

**Comment by paolodamico** [comment]
Thanks for pointing that out! Will update the API docs.
- For the first one you can use the trends API, I would recommend you create a "Trend" insight in the UI and inspect the request being sent.
- The second one unfortunately we won't have support for a while. Is there any other proxy metric that you could use to gauge usage?

**Comment by agrubi** [comment]
Thanks! We decided we should be ok without the second metric.

**Comment by paolodamico** [comment]
Great! Closing this now then. Feel free to open another issue / reach out via email if you have any further questions, and thanks for reporting the outdated API docs.
