### ISSUE TITLE
self-hosted posthog has been down right after I rebooted my vps

### ISSUE THREAD

**Issue by marcelwoo** [PostHog/posthog#8071]
## Bug description
I've installed Posthog with the hobby installation script on my vps and at first it was working fine. But right after I rebooted ubuntu and visited my self-hosted posthog site again, it would not load and just showed a blank page. It seems that something went wrong after I rebooted my vps. I've checked all the services required by Posthog with the command _docker ps_, and everything is up and running.

![screenshot](https://user-images.githubusercontent.com/1132325/149537839-f44854d7-83ed-438e-bc35-0efd37869aa8.png)

I’ve tried reinstalling the os on the vps to erase everything and reinstalling Posthog with the hobby installation script. But once I rebooted my vps, my self-hosted Posthog site was down again. The Chrome browser shows an "This page isn’t working” error, while Safari only shows a blank page.  I do not know what causes the problem and what I should do. Please shed some light on this and help me. 

## Expected behavior
The Posthog site should be available after a server reboot.

## How to reproduce

1.  Install Posthog with the hobby installation script on your vps. Visit the site and it is up and running.
2. Reboot your vps.
3. Load the self-hosted Posthog site again and the site will be down forever.

## Environment

- [x] self-hosted PostHog (ClickHouse-based), version/commit: version 1.31.1

**Comment by guidoiaquinti** [comment]
👋 Hey @marcelwoo, sorry for the late reply. Were you able to fix the issue? Can you please take a look at the error logs from the containers? Those will help us to understand better what is wrong. Thank you!

**Comment by danielthedifficult** [comment]
Hello @marcelwoo, I believe you experienced the same as issue #10792, which was fixed in a [recent PR](https://github.com/PostHog/posthog/pull/11256).

If that sounds right, would you consider closing the issue?
