### ISSUE TITLE
Can't add a funnel to a dashboard

### ISSUE THREAD

**Issue by tiina303** [PostHog/posthog#8076]
## Bug description

on this [funnel](https://app.posthog.com/insights/rqjfOxEj?insight=FUNNELS&date_from=-14d&actions=%5B%5D&events=%5B%7B%22id%22%3A%22helm_install%22%2C%22name%22%3A%22helm_install%22%2C%22type%22%3A%22events%22%2C%22order%22%3A0%2C%22properties%22%3A%5B%7B%22key%22%3A%22operation%22%2C%22value%22%3A%5B%22install%22%5D%2C%22operator%22%3A%22exact%22%2C%22type%22%3A%22event%22%7D%5D%7D%2C%7B%22id%22%3A%22organization%20usage%20report%22%2C%22type%22%3A%22events%22%2C%22order%22%3A1%2C%22name%22%3A%22organization%20usage%20report%22%7D%5D&display=FunnelViz&interval=day&properties=%5B%5D&funnel_to_step=1&funnel_viz_type=trends&funnel_window_interval_unit=day&funnel_window_interval=3&exclusions=%5B%5D&aggregation_group_type_index=1&funnel_from_step=0) 
<img width="1687" alt="Screen Shot 2022-01-14 at 19 14 53" src="https://user-images.githubusercontent.com/890921/149565989-89f9fd60-bfee-4f00-9e21-2bd312401ca7.png">

when I clicked on 'add to dashboard' or 'on dashboard'.

On the dashboard I see no data
<img width="851" alt="Screen Shot 2022-01-14 at 19 15 16" src="https://user-images.githubusercontent.com/890921/149565653-a08fc877-369d-4456-95d7-74d71c8305a1.png">
If I click on it it drops me into an insight with matching name in the URL, but it's a trend page view that I see, i.e. the default new insight except for the name and short id.
<img width="654" alt="Screen Shot 2022-01-14 at 19 16 29" src="https://user-images.githubusercontent.com/890921/149565638-92f48ddf-e277-4dd9-9beb-1bd67e952812.png">

## Expected behavior

See the same insight as I added it to the dashboard.

## How to reproduce

1. on this [funnel](https://app.posthog.com/insights/rqjfOxEj?insight=FUNNELS&date_from=-14d&actions=%5B%5D&events=%5B%7B%22id%22%3A%22helm_install%22%2C%22name%22%3A%22helm_install%22%2C%22type%22%3A%22events%22%2C%22order%22%3A0%2C%22properties%22%3A%5B%7B%22key%22%3A%22operation%22%2C%22value%22%3A%5B%22install%22%5D%2C%22operator%22%3A%22exact%22%2C%22type%22%3A%22event%22%7D%5D%7D%2C%7B%22id%22%3A%22organization%20usage%20report%22%2C%22type%22%3A%22events%22%2C%22order%22%3A1%2C%22name%22%3A%22organization%20usage%20report%22%7D%5D&display=FunnelViz&interval=day&properties=%5B%5D&funnel_to_step=1&funnel_viz_type=trends&funnel_window_interval_unit=day&funnel_window_interval=3&exclusions=%5B%5D&aggregation_group_type_index=1&funnel_from_step=0)
2. click on "on dashboard" (alternatively remove form the dashboard and try to re-add same result)
3. observe that the insight didn't load (it's later on the dashboard)

## Environment

- [x] PostHog Cloud
- [ ] self-hosted PostHog (ClickHouse-based), version/commit: _please provide_
- [ ] self-hosted PostHog (Postgres-based, legacy), version/commit: _please provide_

**Comment by tiina303** [comment]
Note that if I click on edit from the dashboard for any other insight it also redirects me to a default one page views one with the right name. Suspect the problem is tied to short links as if I pick any insight and remove anything after the short name I see pageview graph again.

**Comment by mariusandra** [comment]
This is actually 100% working for all users not in the "beta users" group. 

1. If I view with both "line-graph-v2" and "dashboard-redesign" enabled, I see what @tiina303 saw:
![image](https://user-images.githubusercontent.com/53387/150108989-d3a13a7f-73d0-4228-ba34-274e9eed4391.png)

2. If I remove "dashboard-redesign" and view with only "line-graph-v2", it looks like this:
![image](https://user-images.githubusercontent.com/53387/150109088-65717eda-fe07-4c15-987b-21c47d1b08e5.png)

3. If I remove both flags, it looks correct:
![image](https://user-images.githubusercontent.com/53387/150109183-b47ad9bf-e67b-4b6b-b839-6b7c28916349.png)

CC @Twixes @alexkim205 for the related parts.

**Comment by Twixes** [comment]
"There are no matching events" with InsightCard should be solved by https://github.com/PostHog/posthog/pull/7904.

**Comment by Twixes** [comment]
Solved.
