### ISSUE TITLE
Experiments creation flow problem

### ISSUE THREAD

**Issue by paolodamico** [PostHog/posthog#8083]
**Context**
1. Recently we got feedback in a usability test that the experiment creation screen is overwhelming. A lot of stuff going on. A wizard was even suggested.
2. With the addition of secondary metrics, we have even more stuff.
3. A user also brought up the issue of needing to create the experiment first, changing the code second, and deploying third.

**Proposal**
1. You create the experiment by setting a name, description, and key. This way anyone can create the experiment and the key can be "reserved".
2. Before launching the experiment you enter information on goals, participants, and screenshots (if applicable) of the variants.
3. You launch.

**Comment by neilkakkar** [comment]
Thanks Paolo!

re: (1), I'm not sure which interview you're referring to here, but in the latest one, I think they meant the flow with the side-by-side preview and experiment data.

re: (3), I'm not quite sure how often you'd want to track new metrics defined just for the experiment. I know one user mentioned this might be an issue, but I'll wait to hear specific usecases from them, where you're creating metrics to track just for the experiment.
(Even if they do that, it's possible with existing flow: On a draft -> Edit -> use new metric)

I'm not quite sure what "reserving" solves for, and this seems to needlessly increase the number of steps to launch an experiment.

I'd rather prefer waiting for more users complaining about (1), before making a decision here.

**Comment by paolodamico** [comment]
Thanks for challenging @neilkakkar (goal is definitely this discussion)! Do think I could be falling for confirmation bias. With so few data points, it's harder to avoid. After some thought,

### My thought process
<details>
 <summary>Read for additional context</summary>

1. I think we can focus on the more objective problem outlined: the case where you just want to create the draft experiment to have the FF and multivariate keys defined (before being ready). It's the natural approach, create FF -> code the experiment -> launch. Further, I think it will be quite common for different people who will a) create the FF / code the experiment and b) set the experiment params (typically an eng will do (a) and a PM (b)).

1.1. Do agree that draft experiments could solve for this, but then we need to make the UI clear so you know you can actually create draft experiments with minimum data and save for later. We got at least 2 users reporting they didn't understand this could be achieved.

2. I think you're right on the "overwhelming" piece. While I do think several users have brought this up, it could certainly be just the layout issue, or shadowing a different problem. As we already have something built, let's ship and iterate with a larger dataset.
</details>

### My conclusion
Please challenge.
- Let's make minor UI changes to make it clear you can draft experiments and edit later prior to launch. Require only minimum attributes to create.
- Once we have actual experiments running and more hard data, we can reevaluate if we should change something else related to the UI or layout.
