### ISSUE TITLE
Docker: Multi-stage build to reduce image size

### ISSUE THREAD

**Issue by imWildCat** [PostHog/posthog#8084]
## Is your feature request related to a problem?

Currently, the image size is pretty large.

## Describe the solution you'd like

Docker multistage build can be a good solution: <https://docs.docker.com/develop/develop-images/multistage-build/> 

## Describe alternatives you've considered

N/A

## Additional context

N/A

**Comment by imWildCat** [comment]
Nice work 😢

**Comment by Twixes** [comment]
Oh, looks like we forgot to close this earlier. We now use multi-stage builds heavily: https://github.com/PostHog/posthog/blob/master/production.Dockerfile. Is PostHog image size affecting you @imWildCat?
