### ISSUE TITLE
Property that's 'not seen' should be greyed out

### ISSUE THREAD

**Issue by timgl** [PostHog/posthog#8092]
## Bug description

When I searched for 'hubspot_score' which is a person property but not an event property (even though it does exist), despite the "not seen" label I still clicked it, and then was confused by the breakdown being empty.

![image](https://user-images.githubusercontent.com/1727427/149795990-ff4f390b-22ed-4a92-845c-babcacf54352.png)

## Expected behavior

1. If there are only "not seen" properties on events but there is a "seen" property on persons we should auto select that one
2. Grey out the text of any "not seen" properties to make it more obvious

cc @mariusandra 

## How to reproduce

1.
2.
3.

## Environment

- [ ] PostHog Cloud
- [ ] self-hosted PostHog (ClickHouse-based), version/commit: _please provide_
- [ ] self-hosted PostHog (Postgres-based, legacy), version/commit: _please provide_

**Comment by paolodamico** [comment]
CC @clarkus, this was what we originally had but you had the feedback it made it look not clickable. I'm an advocate for grayed out or some other visual indication that's more obvious than the tag. Thoughts?

**Comment by mariusandra** [comment]
Additional context, and when we made the switch from grayed out to non-grayed out: https://github.com/PostHog/posthog/pull/7718#issuecomment-996762278

I personally don't mind revisiting this decision.

**Comment by timgl** [comment]
@mariusandra the combination of the "not seen" label and greyed out text might work?

**Comment by clarkus** [comment]
The real question is if we should allow users to select options for which we know we have no data. The tag is meant to inform the user that there isn't data, but previously we made the call that we shouldn't prevent them from selecting the option. If the option is clickable, then we shouldn't make it look disabled.

**Comment by mariusandra** [comment]
Let's remove all "not seen" properties from the list altogether. 

This idea was floated when this feature was built, but we just didn't have the data to confidently show what properties were actually seen, and what weren't. We have been tracking this for [over a month](https://github.com/PostHog/posthog/pull/7770) now. Thus on cloud we can be reasonably confident that the seen/not-seen label will be correct... and tackle rare one-off issues as they come.

Not so for self hosted users who might update a pre-event-property-tracking version to a post-tracking version, and find all dropdowns half-empty for a while. We can probably get away by telling users who ask for help to just wait, and/or giving them a script to run that would populate these fields.

**Comment by timgl** [comment]
> Not so for self hosted users who might update a pre-event-property-tracking version to a post-tracking version, and find all dropdowns half-empty for a while. We can probably get away by telling users who ask for help to just wait, and/or giving them a script to run that would populate these fields.

This feels like an experience that isn't good enough for self hosted.

Maybe a better experience is a feature flag, and then we'll release this broadly the release after the next release?

**Comment by mariusandra** [comment]
That won't really work, since I imagine a lot of users skip versions just to get to the latest version. Async migration requirements could change this somewhat, but even then each version will only be installed for a short while.

The other alternatives are:

1) add an async migration that would populate all this data
2) push the complexity down to the users and put a toggle somewhere in the settings to show/hide unseen properties
3) only show the "seen" properties, followed by a "click here to see 345 other properties" link to expand the list
4) make the unseen props grey, even if you can click on them

**Comment by timgl** [comment]
> only show the "seen" properties, followed by a "click here to see 345 other properties" link to expand the list

This feels like the best solution because it still allows flexibility if something goes wrong.
