### ISSUE TITLE
Automated Insights MVP (F.k.a. Universal Taxonomy)

### ISSUE THREAD

**Issue by marcushyett-ph** [PostHog/posthog#8094]
In Q1 we want to Ship an MVP of Automated Insights to validate this as a long-term direction.

@EDsCODE and I have been talking a bit about this but I wanted to get it in a public thread so we can continue the discussion and get feedback from others.

**What is automated insights?**
Previously called "Universal Taxonomy", Automated Insights is about answering the important questions our users haven't even thought of asking yet. We'll make this possible by understanding their events, e.g. their "Add to my basket" is the same as our "Add to Cart" and we know that it's common to show use a funnel with add to cart to understand conversion rates on an e-commerce app - so we suggest this to a user. [Demo](https://www.figma.com/proto/NHPA2hVWwaKp4eTGWdigs9/Product-Concepts?page-id=128%3A437&node-id=131%3A2152&viewport=-512%2C1032%2C0.4552224576473236&scaling=min-zoom&starting-point-node-id=131%3A2152)

**What's the objective?**
The goal of this project is that we validate (or invalidate) this as a long-term direction by de-risking the following:
* Is it possible to create a taxonomy that covers >80% of events for multiple businesses (for a single vertical e.g. e-commerce)
* Can we automatically map real customers events to this taxonomy
* Can we suggest useful insights to real customers before they think of them

**Whats the scope of the MVP?**
* A single vertical (e.g. e-commerce or healthcare)
* ~5 of customers
* End-to-end experience (not just a spreadsheet or query)

**What should our next steps be?**
* Identify the best vertical to work with, based on customer coverage and ease of working with events
* Identify customers to partner with on the solution
* Create first version of taxonomy for vertical
* ...

**Aren't we avoiding building low quality partial solutions?**
* We need to take some risks for the long term to stay ahead of our competitors and stop our product from becoming stale
* If this is successful - it will enable us to create am even higher quality (easier) experience for a subset of customers
* If this fails we will not keep the code lying around, ensuring we learn from it but don't reduce overall quality

Would really appreciate your feedback and further thoughts on this.

**Comment by timgl** [comment]
I like it!

- Why are we going for an e2e experience and not a spreadsheet? Feels like the riskiest part of this is our ability to answer random question we will ask of it
- related, are we still going with the 'ask any question' approach?

**Comment by marcushyett-ph** [comment]
> Why e2e experience?

If it's not something people use unsupervised, we probably wont learn much from building it.

> Ask any questions?

IMO we should take the opposite approach for the MVP, instead of allowing people to ask anything, we suggest insights that 
are most valuable to review.

@EDsCODE  would love to hear your thoughts?

**Comment by neilkakkar** [comment]
Suggesting insights is a lot more constrained, so I like that approach for the MVP! But, I don't see an easy way to go from: Suggestions to "ask any questions". It sounds like a very different problem?

----

I might be wrong, but I think an unsupervised spreadsheet like version is possible (and **much better than MVP** for validation/de-risking). Here's how I imagine it:

1. We tell people / ask permission for suggesting insights based on their data
2. We run our algorithms on their data (probably the hard bit - figuring out what's right, tweaking this, gathering feedback)
    2.1: The last part necessitates a high-fidelity connection, where we can hear *why* something works for them / doesn't work for them, and then try to reason about how to make changes to the algorithm to promote results of that type
    2.2: (or that's how I tweaked correlation stuff). But this sounds like a much harder problem, since you have two big problems: (1) mapping what they call events to our internal representation of that event. (2) Given some events (our dictionary), generate sentences (insights) that make sense
3. Once we have the results from this algo, we go to our slack channel, and post, like 5 of these results, linked to their insights, and ask them (1) Are any of these meaningful? (2) Did you already have some of these insights set up? (3) Is any of these new/exciting/things you wouldn't have thought possible to chart?

I think being successful with (3) is the hard part? And we wouldn't hear about the answers to these questions without actually talking to them. And we'll get hints on how to do well from talking to them.

Given my limited understanding of the problem, I'd say it's much harder to "infer" feedback from how they play around with the MVP, even if we have session recordings. We need to understand what they're thinking, if we're mapping their events correctly, and why some results are surprising.

The beauty here is that *if* we get successful (by talking) at understanding what makes results surprising (in other words, what are users not thinking about), we can add this as a possible sentence to our taxonomy, and shoot for "figure it out once, have a useful insight for every new user" kind of scale-economies.

----

I think a third problem that an MVP can solve but the spreadsheet wouldn't is how/where to present this information. But this seems trivial compared to the algorithmic challenges here.

**Comment by marcushyett-ph** [comment]
Thanks for the feedback @neilkakkar 

Definitely agree the crux here is getting the data into a meaningful state and iterating on the results with our alpha testers using the highest fidelity feedback; your "spreadsheet" approach sounds great for that. If we validate that the hard part can be done, theres still a lot of value to be gained from exposing it (e.g. via a basic e2e experience) and understanding the usage, to work out what our next big milestone should be.

> I don't see an easy way to go from: Suggestions to "ask any questions"

In my mind, most suggestions will be for the most popular insights and most searches are also likely to be for the most popular insights (80:20 rule). I see the two major technical challenges moving between suggestions and search as:
1. Precision - finding the right insights form a search term
2. Recall - having enough insights to suggest

Saying that, I agree, I don't think this will be easy either.

> 3.(2) Did you already have some of these insights set up?

We should be able to automate this (with permission to access their insights)

**Comment by EDsCODE** [comment]
> > Why e2e experience?

> If it's not something people use unsupervised, we probably wont learn much from building it.

I'd +1 to Neil's approach with partnered customers mainly to reduce overhead in understanding the hardest part of the problem. Imo, the E2E experience is secondary because if the data analysis that we perform doesn't reveal any useful insights, then the interface won't be necessary. If the automated insights are very useful, users should be bothering us for them even if it's through a slack channel. 

I think it's ok if the initial way we provide these insights is supervised, we can measure how much a team ends up using the insights we generate for them which will be the "unsupervised" behavior that we can learn from. 

> > Ask any questions?

> IMO we should take the opposite approach for the MVP, instead of allowing people to ask anything, we suggest insights that 
are most valuable to review.

agreed!

---

 My current guess is that the data is a lot messier than we're hoping for. However, going through the initial steps outlined in the original post should be quite useful in understanding how messy or clean the patterns across our customers are. In one case, we can build automated insights as we're imagining and in the other case we might be able to come up with ideas around how to educate posthog users to instrument their products in a way that will eventually allow us to build/infer a taxonomy more effectively.

**Comment by marcushyett-ph** [comment]
Okay, feels like we have 3 milestones here then.

1. Validate we have good enough data to build something like this
2. Ship a supervised system for getting high fidelity feedback from alpha users

The above are essentially do-or-die for this project, then if they're successful:

3. Ship an unsupervised experience to scale feedback from beta users

**Actions (from me)**
1. @EDsCODE  are you still keen to own this goal?
2. @EDsCODE Validate this is viable and pick a focus vertical: how would you like to work together on the data validation? (N.B .I have time on Friday to give creating a universal taxonomy a go)
3. Find some Alpha customers (I can do this, but its dependent on the outcome of 2 since we need to know which vertical we're focusing on)
4. Speak to industry experts - I'm setting up a chat with an Ex-CTO from this space for us to identify some shortcuts

**Comment by neilkakkar** [comment]
Can I be a part of (4), if there are no people constraints?

**Comment by marcushyett-ph** [comment]
Hell yeah, you can be part of any of the others too :D
