### ISSUE TITLE
Clean up and document APIs

### ISSUE THREAD

**Issue by timgl** [PostHog/posthog#810]
At the moment the only way to work out what our APIs are is through opening the developer console. We need first class API documentation instead.

I've tried using something like redoc to automatically generate documentation, but it's not very configurable and misses quite a lot of variables.

I'd be in favour of just manually documenting APIs and having a standard template for it.

**Comment by nsb** [comment]
Edit: I understand that is maybe what you already tried and were not happy with. Works great in my experience though.

> Django REST Framework has good support for OpenAPI schema (formerly swagger). With this you can setup interactive documentation and generate client code.
> 
> https://www.django-rest-framework.org/topics/documenting-your-api/

**Comment by timgl** [comment]
Would be good to error a decent error message if the JSON for properties is invalid, see [this error](https://sentry.io/organizations/posthog/issues/1735411878/?project=1899813&referrer=slack)

**Comment by yakkomajuri** [comment]
I don't know about the cleanup, but the API is now documented. Can this be closed?

**Comment by Twixes** [comment]
I'm still definitely in favor of coupling documentation more tightly with code (OpenAPI perhaps) and overall doing APIs in a more consistent and documented way. Though some major cleanup is still underway and I think we shouldn't invest in that effort until we're confident that our API's architecture is future-proof and can offer API stability (some major futureproofing underway in #2445 for instance).

**Comment by kpthatsme** [comment]
Is this still a relevant issue?

How much effort would it be for our api to meet the OpenAPI spec, @Twixes maybe you have a good idea?

One issue today is we don't support all languages equally - I wonder if we could try using a service such as this https://sdkeasy.com/ to meet the gap.

**Comment by Twixes** [comment]
This is still pretty relevant. I think we should try out some options from https://www.django-rest-framework.org/topics/documenting-your-api/ as suggested by @nsb.

**Comment by paolodamico** [comment]
We now have automatically generated API docs
