### ISSUE TITLE
Disable messages Kafka batch of X events completed

### ISSUE THREAD

**Issue by aratnikovmxmgt** [PostHog/posthog#8110]
## Is your feature request related to a problem?

A lot of messages in log output like:
`[MAIN] 11:35:34 🧩 Kafka batch of X events completed in N ms`

## Describe the solution you'd like

Make an environment variable like PLUGIN_SERVER_LOG_SERVITY with different types of outputs.
`DEBUG` will show every messages
`INFO` will show only combined messages like (also make PLUGIN_SERVER_LOG_INFO_PROCESSED_TIME = 30 seconds and use it in example below):
`[MAIN] 11:39:29 🕒 Processed X events in 30.01s`
`WARNING` will show warnings like too many clients or cannot find user in users 
`ERROR` will show errors only 
 

## Describe alternatives you've considered

Make less log output for posthog with environment variable. All at least some, that will disable "Kafka batch of X events completed".

## Additional context

I'm using elasticsearch for docker log analysis and it's a lot of logs from posthog right now (~2300 per minute). Each " Kafka batch of X events completed" stores as an individual message.

**Comment by yakkomajuri** [comment]
This is a valid request, thanks for writing up this issue!

@posthog-bot please add @aratnikovmxmgt for ideas
