### ISSUE TITLE
Minor tooltip improvements / regressions

### ISSUE THREAD

**Issue by paolodamico** [PostHog/posthog#8113]
With the new tooltips implementation, I noticed a couple of quick wins to improve the experience.

1. When having a breakdown, show the series color icon next to each row's title.
2. WAUs/MAUs are not shown in human friendly text.
    <img width="273" alt="" src="https://user-images.githubusercontent.com/5864173/149952878-cec13d99-bf0a-4141-8040-493f2dcf57b4.png">
3. Maybe we should consider changing the "Click to view people" label to "Click anywhere to view people"? Intuitively I want to click on the label that says "Click".
4. Month label title should say something clearer like "January 2022"
    <img width="328" alt="" src="https://user-images.githubusercontent.com/5864173/149953268-ec4a15d8-9525-4e43-a7fc-a5c22f800569.png">

**Comment by pauldambra** [comment]
Second part of this is done already... We show month when grouped by month

<img width="774" alt="Screenshot 2022-10-07 at 21 06 01" src="https://user-images.githubusercontent.com/984817/194644721-2407a475-8a0b-489a-8899-4b948bcb4f4a.png">
