### ISSUE TITLE
Modifying a filter on events page misleadingly initially shows "No events"

### ISSUE THREAD

**Issue by tiina303** [PostHog/posthog#8121]
## Bug description

Modifying a filter on events page misleadingly initially shows "No events", then after a bit that there are new events to load.

<img width="1699" alt="Screen Shot 2022-01-18 at 21 36 02" src="https://user-images.githubusercontent.com/890921/150014913-fe9e8df6-1b23-4276-9fa5-eb319f832dc5.png">
<img width="1701" alt="Screen Shot 2022-01-18 at 21 43 36" src="https://user-images.githubusercontent.com/890921/150015559-b763e2ea-c382-4bf1-a35d-5c58245ff4bc.png">
<img width="569" alt="Screen Shot 2022-01-18 at 21 36 22" src="https://user-images.githubusercontent.com/890921/150014951-91906d0a-a8a9-4770-bf43-cf9a6bcfdb68.png">

## Expected behavior

We never get reported "No events" if that's not the case.

## How to reproduce

1. Got to Events & Actions (automatic new event loading off)
2. Add a filter for anything that has results
3. Observe that we'll initially after loading see "No events" then a bit later "there are new events"

Note that it doesn't repro rarely (potentially doesn't repro when the right events were cached earlier).

## Environment

- [x] PostHog Cloud
- [ ] self-hosted PostHog (ClickHouse-based), version/commit: _please provide_
- [ ] self-hosted PostHog (Postgres-based, legacy), version/commit: _please provide_

**Comment by camerondeleone** [comment]
This just happened on a demo I was running 😳

**Comment by mariusandra** [comment]
This should be fixed within https://github.com/PostHog/posthog/pull/7985 -- but there are other problems that prevent this from being merged. I'll split it up into smaller PRs if I can't get a handle on this within a few hours.

**Comment by pauldambra** [comment]
#8247 has fixed this
