### ISSUE TITLE
Add `--check` flag to `migrate_clickhouse` and `run_async_migrations`

### ISSUE THREAD

**Issue by guidoiaquinti** [PostHog/posthog#8136]
## Is your feature request related to a problem?
We currently support 3 different tools to run data migrations: 

- `python manage.py migrate`: sync migration for the DB data model
- `python manage.py migrate_clickhouse`: sync migration for the ClickHouse data model
- `python manage.py run_async_migrations`: async migration for the DB & ClickHouse data models  

The first exposes a `--check` flag to verify if migrations have been completed successfully while the other two don't. With https://github.com/PostHog/posthog/pull/7823 we added a check at startup for the first (covering only the DB model).

## Describe the solution you'd like
We should probably do something similar for the other two and add them at process startup.

## Describe alternatives you've considered
Do nothing.

**Comment by macobo** [comment]
Both of these already have a `--plan` flag - perhaps we can extend that to exit(1) if there is anything planned?

**Comment by guidoiaquinti** [comment]
Yeah or even better: adding a `--check` that is `--plan` + `os.exit(something)` based on the plan output so we don't break the current command interface.

**Comment by tiina303** [comment]
Related https://posthog.slack.com/archives/C01MM7VT7MG/p1642763725170600?thread_ts=1642755577.168500&cid=C01MM7VT7MG

> We shouldn't run them during helm upgrades (well definitely not yet), there's also no migration yet for which the condition POSTHOG_VERSION > Version(sm.posthog_max_version) ([here](https://github.com/PostHog/posthog/blob/master/ee/management/commands/run_async_migrations.py#L27)) would be true, so it's currently a no-op. This also doesn't work as e.g. we have the first migration, that doesn't have max_posthog_version set currently ([here](https://github.com/PostHog/posthog/blob/27ac13bb81d4a85cdbd89b29668ef1e03874bfc1/posthog/async_migrations/migrations/0001_events_sample_by.py) + [here](https://github.com/PostHog/posthog/blob/08801456c14c607c9044f1fa8d388bc8ce532e58/posthog/async_migrations/definition.py#L75)), aka it would be not necessary, but the second one at 1.34 would be necessary and fail because the dependency isn't completed ([here](https://github.com/PostHog/posthog/blob/08801456c14c607c9044f1fa8d388bc8ce532e58/posthog/async_migrations/runner.py#L75)).

**Comment by tiina303** [comment]
related https://posthog.slack.com/archives/C01MM7VT7MG/p1643015292217300?thread_ts=1643013166.214600&cid=C01MM7VT7MG

**Comment by tiina303** [comment]
Related https://github.com/PostHog/product-internal/blob/main/requests-for-comments/2022-01-04-async-migrations-improvements.md#what-should-happen-during-upgrade-vs-install & https://github.com/PostHog/product-internal/blob/main/requests-for-comments/2022-01-04-async-migrations-improvements.md#how-should-we-know-migration-is-done (& comments in the original PR) & https://github.com/PostHog/posthog/pull/7919  <- will look into all of that
