### ISSUE TITLE
Minor UX annoyance when editing feature flag cohorts

### ISSUE THREAD

**Issue by matthew-gill** [PostHog/posthog#8141]
## Bug description

We use PH feature flags a lot. Sometimes we add a selection of emails into a filter like this:
![image](https://user-images.githubusercontent.com/31350541/150172226-28f6ad11-2776-403d-b05d-afe23660f156.png)

If you then go back and remove one item from the list, it closes the whole filter, which is a pain if you have to remove multiple people (I just had to do it 10 times) - I'm sure a better way would be to make a cohort, but thought I'd mention it

## Expected behavior
When you delete a "pill" item from a filter, the filter should stay open in case the user wants to remove more.

## How to reproduce

1. Create a feature switch and add a filter for something like email
2. Add several email addresses and save the feature flag
3. Edit the filter by clicking on it, and click the `[x]` next to the email, it will close the whole filter panel instead of staying open for the user to remove more

## Environment

- [ ] PostHog Cloud
- [X] self-hosted PostHog (ClickHouse-based), version/commit: 1.31.1
- [ ] self-hosted PostHog (Postgres-based, legacy), version/commit: _please provide_

**Comment by neilkakkar** [comment]
This works fine now :)
