### ISSUE TITLE
Places to expose taxonomy

### ISSUE THREAD

**Issue by alexkim205** [PostHog/posthog#8144]
This issue aims to centralize all the places where we can expose taxonomic features to incentivize users to document events/event properties/person properties used throughout their team. Please feel free to edit this issue if you think there are spots I missed! @clarkus @rcmarron 

1. Taxonomic Filters

<img width="837" alt="Screen Shot 2022-01-19 at 11 14 58 AM" src="https://user-images.githubusercontent.com/13460330/150198761-8873e39e-8d81-456a-945f-9d7c32220644.png">

2. Event Usage + Event Properties Usage Tables

<img width="1299" alt="Screen Shot 2022-01-19 at 11 13 45 AM" src="https://user-images.githubusercontent.com/13460330/150198584-dfd34260-966e-42f2-9f52-0e09d73d2ff8.png">

3. Rename graph series modal

<img width="577" alt="Screen Shot 2022-01-19 at 11 13 04 AM" src="https://user-images.githubusercontent.com/13460330/150198495-60b6ca09-e39e-4ab2-86b9-560d826a5bdc.png">

4. Session recording events list

<img width="359" alt="Screen Shot 2022-01-19 at 11 09 45 AM" src="https://user-images.githubusercontent.com/13460330/150198017-9de2946f-5599-427a-bc62-830bccd535d3.png">

5. Person properties in actor modal

<img width="597" alt="Screen Shot 2022-01-19 at 11 09 21 AM" src="https://user-images.githubusercontent.com/13460330/150197955-21a25a8d-60ad-4015-9042-94d43ecf8c56.png">

6. Individual person page

<img width="906" alt="Screen Shot 2022-01-19 at 11 11 18 AM" src="https://user-images.githubusercontent.com/13460330/150198311-5aabfe88-2053-48db-a8a3-efc651803e8b.png">

7. Maybe Insight Legends?

**Comment by clarkus** [comment]
> 1. Taxonomic Filters

Makes sense and this is the core place to expose this. When the item is hovered, show the overlay card. 

> 2. Event Usage + Event Properties Usage Tables

We could show the overlay cards here, but it does feel kind of meta. We'll be describing the items in the list view as well as with the cards, and then the full descriptions are just a click away. It doesn't do any harm, so probably fine to show it. 

> 3. Rename graph series modal

I don't think this is the place to show the taxonomy overlay. When composing the query, we'll show overlays. In this case you just need to know which graph series or funnel step you're affecting with your rename. 

> 4. Session recording events list

Makes sense to me. On event hover, describe event. Might be some quirkiness if the recording continues to play while you're editing taxonomy details. I could see that event you're modifying scrolling out of view as you complete the changes. Maybe we pause the recording when editing?

> 5. Person properties in actor modal

👍 

> 6. Individual person page

👍 

> 7. Maybe Insight Legends?

Not sure - I think the more important thing here is to fully describe the graph series or the step, not just the event. There might be filters or other context that's more pertinent than just an event's definition.
