### ISSUE TITLE
Would like to be able to see all of a funnel in the dashboard view with no horizontal scrollbar

### ISSUE THREAD

**Issue by camjw** [PostHog/posthog#8159]
## Is your feature request related to a problem?

I'd like to be able to see all the steps of a funnel in the dashboard view so my problem is that this isn't currently possible.

## Describe the solution you'd like

To be able to see a funnel in the dashboard view without a horizontal scroll bar.

## Describe alternatives you've considered

 I tried putting the funnel on vertical view, but this didn't seem to propagate to the dashboard view.

## Additional context

This is the current situation, I can only see two steps of the funnel.
![image](https://user-images.githubusercontent.com/41902232/150345235-c4b7b955-324d-4344-a4d2-edd07d552160.png)

**Comment by macobo** [comment]
cc @paolodamico @mariusandra @Twixes for prioritization

**Comment by camerondeleone** [comment]
I'd like to +1 this issue — not sure where we're at on adoption of horizontal funnels, but it has exacerbated this issue IMO. Probably fine on a large monitor, but on a 13" macbook, it makes funnels much more difficult to use.
