### ISSUE TITLE
Person modal on dashboard doesn't appear on click

### ISSUE THREAD

**Issue by jamesefhawkins** [PostHog/posthog#8163]
## Bug description

[Video](https://www.loom.com/share/4094b29352b5465d8132c06a856a2afb) 

Voice acting by me.

## Expected behavior

I get the list of persons up that produce a data point.

## How to reproduce

1. Go to [this dashboard](https://app.posthog.com/dashboard/20464) showing our largest org signups

## Environment

- [x] PostHog Cloud

**Comment by mariusandra** [comment]
I remember we disabled the person modal on dashboards for a few technical reasons, but now the new (feature flagged via `line-graph-v2`) tooltips indicate that it's still possible. This tooltip is only enabled for us and the "Beta users" cohort, so not a big blast radius.

@alexkim205 could you add this to the tooltip backlog?

@jamesefhawkins does this loom contain publicly shareable data?
