### ISSUE TITLE
Formulas and Breakdowns don't work together

### ISSUE THREAD

**Issue by marcushyett-ph** [PostHog/posthog#8165]
## Bug description

I've created a trend with a breakdown and a formula, I get an error

## Expected behavior

I would expect to see the results of the formula broken down by the attribute I selected

## How to reproduce

1. https://app.posthog.com/insights/YbLu3MNB/edit?insight=TRENDS&interval=day&display=ActionsBarValue&actions=%5B%5D&events=%5B%7B%22id%22%3A%22insight%20analyzed%22%2C%22name%22%3A%22insight%20analyzed%22%2C%22type%22%3A%22events%22%2C%22order%22%3A0%7D%2C%7B%22id%22%3A%22insight%20analyzed%22%2C%22type%22%3A%22events%22%2C%22order%22%3A1%2C%22name%22%3A%22insight%20analyzed%22%2C%22math%22%3A%22dau%22%7D%5D&properties=%5B%5D&filter_test_accounts=true&breakdown=insight&breakdown_type=event&new_entity=%5B%5D&formula=B%2FA

## Environment

- [x] PostHog Cloud
- [ ] self-hosted PostHog (ClickHouse-based), version/commit: _please provide_
- [ ] self-hosted PostHog (Postgres-based, legacy), version/commit: _please provide_

**Comment by tiina303** [comment]
This is what the user would see, which leaves an impression that our app is broken

<img width="958" alt="Screen Shot 2022-03-04 at 15 56 07" src="https://user-images.githubusercontent.com/890921/156791585-909d5c80-d16f-4ae5-9d1b-7179855b37ee.png">
