### ISSUE TITLE
No filter for internal users on Recordings

### ISSUE THREAD

**Issue by marcushyett-ph** [PostHog/posthog#8185]
## Is your feature request related to a problem?

I cannot use the standard filter on session recordings to filter out internal users

## Describe the solution you'd like

I'd like to be able to use the standard toggle to filter out internal users on recordings

## Describe alternatives you've considered

Filtering by a cohort of people who aren't internal users.

**Comment by marandaneto** [comment]
This was done already https://github.com/PostHog/posthog/pull/16723
