### ISSUE TITLE
Events are showing as stale when they're not

### ISSUE THREAD

**Issue by marcushyett-ph** [PostHog/posthog#8186]
## Bug description

These events are not stale - but they are showing up as stale in the filter
![image](https://user-images.githubusercontent.com/85295485/150517199-6f2f7e08-e795-43a6-aa37-1d899f2c383b.png)

## Expected behavior
Only events which are not being used regularly should be stale

## How to reproduce

1. Go to trends, search for event "recording analyzed"
2. See the stale tag

## Environment

- [x] PostHog Cloud
- [ ] self-hosted PostHog (ClickHouse-based), version/commit: _please provide_
- [ ] self-hosted PostHog (Postgres-based, legacy), version/commit: _please provide_

**Comment by mariusandra** [comment]
Should be fixed https://github.com/PostHog/posthog/pull/8260
