### ISSUE TITLE
Events table is slow to load

### ISSUE THREAD

**Issue by neilkakkar** [PostHog/posthog#8187]
## Bug description

The events table is slow to load.

![2022-01-21 12 15 50](https://user-images.githubusercontent.com/7115141/150525829-1877f1fc-6483-46ac-bbb0-81ba15e0500e.gif)

## Expected behavior

Events table is not slow

## How to reproduce

1. Go to Events page
2. Wait
3.

## Environment

- [ X ] PostHog Cloud
- [ ] self-hosted PostHog (ClickHouse-based), version/commit: _please provide_
- [ ] self-hosted PostHog (Postgres-based, legacy), version/commit: _please provide_

**Comment by mariusandra** [comment]
Isn't the full URL https://app.posthog.com/api/projects/@current/property_definitions/?limit=5000&offset=5000 ?

**Comment by mariusandra** [comment]
The events table is just slow... and does two queries for some reason, but the property definitions are not related to this. They're just equally slow:
![image](https://user-images.githubusercontent.com/53387/150526486-c78c6214-5842-4a37-b07f-73ce9290cbb7.png)

**Comment by neilkakkar** [comment]
D'oh, my bad, filtering for just `events/`, yep, it's 2 queries, both of which are slow. Updating title

**Comment by pauldambra** [comment]
While watching redux dev tools for something else I noted that we call fetch events, then set properties, and then immediately again fetch events (which I guess explains the two calls)

**Comment by pauldambra** [comment]
<img width="1036" alt="Screenshot 2022-01-25 at 11 46 48" src="https://user-images.githubusercontent.com/984817/150971482-7463b239-d1d9-416d-ab71-3b38b74e8818.png">

Appear to have very long TTFB on a number of resources. 🤔

**Comment by neilkakkar** [comment]
A quick check returns that [the query itself is taking too long](https://metabase.posthog.net/question#eyJkYXRhc2V0X3F1ZXJ5Ijp7InR5cGUiOiJuYXRpdmUiLCJuYXRpdmUiOnsicXVlcnkiOiIvKiBuZWlscyB0aW1pbmcqL1xuU0VMRUNUIHV1aWQsXG4gICAgICAgZXZlbnQsXG4gICAgICAgcHJvcGVydGllcyxcbiAgICAgICB0aW1lc3RhbXAsXG4gICAgICAgdGVhbV9pZCxcbiAgICAgICBkaXN0aW5jdF9pZCxcbiAgICAgICBlbGVtZW50c19jaGFpbixcbiAgICAgICBjcmVhdGVkX2F0XG4gIEZST00gZXZlbnRzXG4gd2hlcmUgdGVhbV9pZCA9IDJcbiAgIEFORCB0aW1lc3RhbXAgPiAnMjAyMS0wMS0yNSAxMjoyMTozMy44MjkwMDAnXG4gICBBTkQgdGltZXN0YW1wIDwgJzIwMjItMDEtMjUgMTI6MjE6NDMuODU3MjczJ1xuIE9SREVSIEJZIHRvRGF0ZSh0aW1lc3RhbXApIERFU0NcbiBMSU1JVCAxMDAxXG4gIiwidGVtcGxhdGUtdGFncyI6e319LCJkYXRhYmFzZSI6Mn0sImRpc3BsYXkiOiJzY2FsYXIiLCJ2aXN1YWxpemF0aW9uX3NldHRpbmdzIjp7fX0=), not much to do with the frontend.

**Comment by pauldambra** [comment]
This page performance insight doesn't suggest a start date (we started gathering data too late)

https://app.posthog.com/insights/kg5KxrH2

**Comment by mariusandra** [comment]
If I'm not mistaken, the time tracked here is to DOMContentLoaded, meaning time to fire up React and render something. This won't take into account any additional requests React makes to e.g. populate the events table.

**Comment by pauldambra** [comment]
Yep... interesting case to see if we want to split additional properties out of the performance information (or wait until we upgrade ClickHouse and can more easily query into the stored JSON)

**Comment by neilkakkar** [comment]
Will call this done for now!
