### ISSUE TITLE
Formulas do not work if they return 0

### ISSUE THREAD

**Issue by joesaunderson** [PostHog/posthog#8190]
## Bug description

I am trying to calculate Net Promoter Score in PostHog, the formula for this is:

`% of Promoters - % of Detractors.`

I am doing this in a trend query using 3 series;

A - Total Promoters
B - Total Detractors
C - Total Responses

The formula is (A/C x 100) - (B/C x 100)

Say we have 20 promoters, 20 detractors and 50 total responses.

The graph shows:

![image](https://user-images.githubusercontent.com/11272509/150531472-e6d03b28-dd82-404c-887e-b66cd2f9e1cf.png)

## Expected behavior

This should output a `0` for this period.

## How to reproduce

It's an edge case with the data needing to be in the right state, but hopefully the above explains it.

## Environment

- [ ] PostHog Cloud
- [x] self-hosted PostHog (ClickHouse-based), version/commit: 1.31.1
- [ ] self-hosted PostHog (Postgres-based, legacy), version/commit: _please provide_

**Comment by mariusandra** [comment]
Going to close this. It's now possible to use custom HogQL aggregations in trends, including more complex ones like `countIf(event == 'responses') = 0 ? 0 : countIf(event == 'promoters') / countIf(event == 'responses')`.
