### ISSUE TITLE
Numeric properties disabled

### ISSUE THREAD

**Issue by timgl** [PostHog/posthog#8213]
## Bug description

![image](https://user-images.githubusercontent.com/1727427/150697845-7dd8834c-11e9-406d-9575-3dd42be25080.png)

## Expected behavior

I should be able to select numeric properties

## How to reproduce

1. Create insight
2. Try selecting a numeric property
3.

## Environment

- [ ] PostHog Cloud
- [ ] self-hosted PostHog (ClickHouse-based), version/commit: _please provide_
- [ ] self-hosted PostHog (Postgres-based, legacy), version/commit: _please provide_

## Additional context

Looks like the endpoint is really slow? But even when it does load it doesn't work.

Update: I think the issue is that my internet at home was really slow. Weirdly even when it did load the dropdown didn't work, so I think there's a timing issue.

**Comment by mariusandra** [comment]
Thought of this issue when trying to debug https://github.com/PostHog/posthog/pull/8255 - @neilkakkar 's timing question makes this related.

There are a too many places in the app that are still dependent on properties being fully loaded into memory. I made an issue here to track that: https://github.com/PostHog/posthog/issues/8257
