### ISSUE TITLE
Persons shows incorrect list after filter removal

### ISSUE THREAD

**Issue by lharress** [PostHog/posthog#8216]
## Bug description

After removing a search from the "Search for persons" field on the persons list the page momentarily goes back to a full list before applying the search again.

## Expected behaviour

I should see the full persons list after removing a search

## How to reproduce

1. Apply a search on the persons page
2. Once the search has loaded, remove the search using the cross
3. The page momentarily goes back to the full list before applying the search again

## Environment

- [ ] PostHog Cloud
- [x] self-hosted PostHog (ClickHouse-based), version/commit: 1.31.1 / 59bad4465ef26a313fee115de9baa4d48b87a9a3
- [ ] self-hosted PostHog (Postgres-based, legacy), version/commit: _please provide_

## Additional context

Works fine using backspace

**Comment by Twixes** [comment]
Hey! I believe this is fixed now in 1.32, but feel free to reopen if it's still an issue.
