### ISSUE TITLE
Dashboard refresh button can time-travel

### ISSUE THREAD

**Issue by joesaunderson** [PostHog/posthog#8221]
## Bug description

The dashboard refresh button has defied science and can travel to the future:

![image](https://user-images.githubusercontent.com/11272509/150778715-cc1dc577-8b79-477b-9686-20e10af7e85c.png)

## Expected behavior

It should say "A few seconds ago" (and ideally update as time goes on).

## How to reproduce

1. Go to a dashboard
2. Refresh it

## Environment

- [ ] PostHog Cloud
- [x] self-hosted PostHog (ClickHouse-based), version/commit: 1.31.1
- [ ] self-hosted PostHog (Postgres-based, legacy), version/commit: _please provide_

**Comment by neilkakkar** [comment]
Thanks Joe!

P.s: Time travel is my hackathon project, this is just a sneak peek! Let me know if you'd like to beta test that feature? Do you have a year in mind you want to go to? 😋

**Comment by Twixes** [comment]
Hey Joe, is this still an issue you're seeing?
