### ISSUE TITLE
Legend toggling not working for pie charts

### ISSUE THREAD

**Issue by alexkim205** [PostHog/posthog#8236]
## Bug description

Toggling keys in legend and table doesn't work for pie chart.

## Expected behavior

Toggling legend/table key checkboxes should show/hide corresponding sections of pie.

## Environment

- [ ] PostHog Cloud
- [ ] self-hosted PostHog (ClickHouse-based), version/commit: _please provide_
- [ ] self-hosted PostHog (Postgres-based, legacy), version/commit: _please provide_

**Comment by mariusandra** [comment]
Is this something to still fix before the release as the [flag went in](https://github.com/PostHog/posthog/pull/8214)?

**Comment by paolodamico** [comment]
It'd be great if we can fix it, but I wouldn't stop the release if we don't, only ~2% of our insights are pie charts and even less users will use the feature. I think is fine if we fix later. Alternatively we could disable the show/hide behavior of the legend.

**Comment by alexkim205** [comment]
Twas a quick fix - https://github.com/PostHog/posthog/pull/8279
