### ISSUE TITLE
Track source for recording watched/analyzed

### ISSUE THREAD

**Issue by paolodamico** [PostHog/posthog#8237]
## Is your feature request related to a problem?

Knowing when the user is coming from when watching a recording can help us understand their use case so we can improve the experience (e.g. if they came from funnels, they may be trying to understand why their users converted or dropped off).

## Describe the solution you'd like

When tracking `recording watched` (or analyzed) events, we add an attribution source (e.g. funnels, paths, trends, recordings list, ...).

## Describe alternatives you've considered
N/A

## Additional context

This is currently blocking us to measure impact of Diagnosing Causes.

**Comment by paolodamico** [comment]
CC @rcmarron

**Comment by rcmarron** [comment]
Good call - I'll add this in once I get the funnel->recordings flow working.
