### ISSUE TITLE
Get rid of `propertyDefinitionModel` and `eventDefinitionModel`

### ISSUE THREAD

**Issue by mariusandra** [PostHog/posthog#8257]
## Bug description

There are many parts of the app that still rely on all `propertyDefinition`s to be loaded into `propertyDefinitionModel` before they start to work properly.

Unfortunately the property flattener plugin makes it possible to easily have 100k+ properties, rendering parts of the app flakey for the first 10sec or even (much, much) longer, while all the properties load:

![2022-01-25 13 40 15](https://user-images.githubusercontent.com/53387/150978664-a4de6309-cfb3-4edc-b503-9630288979f6.gif)

Some recent issues where this has come up:

- https://github.com/PostHog/posthog/issues/8213
- https://github.com/PostHog/posthog/pull/8255

We have a few heavy users who could even load hundreds of megabytes of properties into memory.

## Expected behavior

Various filters and other widgets still rely on `propertyDefinitionsModel` and `eventDefinitionsModel` to be populated with data that's always there. 

We need to remove these models, and introduce paginated data loading where needed.

**Comment by pauldambra** [comment]
I don't think that #8255 is the same issue

Although I don't want that to take away from my agreement that the "maybe you can query for this thing" behaviour is confusing :)

**Comment by mariusandra** [comment]
Here are the various ways `propertyDefinitionsModel` is used. Unfortunately there's no quick "one size fits all" solution, so we're going to have to uproot it one by one. 

- [x] In the Properties table, we check for the `type` of the property and display it next to the actual property like `string`. We display the type in the database even if the actual displayed value has a different type:
![image](https://user-images.githubusercontent.com/53387/152000091-b94df1a1-314e-430a-9ee0-8500ccc0f81a.png)

- [x] In the Events table the list of property names is used to configure table
![image](https://user-images.githubusercontent.com/53387/152000356-cbf6bff6-6b7f-405f-b41e-f57eef9fe4e5.png)

- [x] The `OperatorValueSelect` component uses the property `type` from the model to limit the comparisons you can do with a property
![image](https://user-images.githubusercontent.com/53387/152000785-d0aa0c78-9873-4fc5-b5e2-9a6b9098d4e8.png)

- [x] The `PropertyValue` and `SelectGradientOverflow` components use `formatForDisplay` to format the list of values depending on the type of the property. This function currently just provides custom formatting for datetimes. Since we don't autocomplete them anymore, perhaps this can be removed. (Screenshot taken via a bug: set it to a string property, then type $time and press enter, you'll get the old "equals" filter with a list)
![image](https://user-images.githubusercontent.com/53387/152001769-3662b568-4946-461a-a7f5-45201c21d84c.png)

- [x] But even if we don't use it in the list, we use it in the `PropertyFilterButton` pill:
![image](https://user-images.githubusercontent.com/53387/152001907-7ee18292-5203-4066-9cb3-4166b0c1bba9.png)

- [x] The `MathSelector` in `ActionFilterRow` toggles the option to sum/average/etc any numerical property, if we have any numerical properties, plus presents a list of numerical properties to choose from: https://github.com/PostHog/posthog/pull/8389
![image](https://user-images.githubusercontent.com/53387/152002734-d9193d37-b159-4fd6-8229-c4c03dace639.png)

- [x] ~~The Properties stats page depends on this.~~ Doesn't exist anymore.
![image](https://user-images.githubusercontent.com/53387/152003220-c124c262-2127-4174-a255-b11a1bb2c59b.png)

Depending on the usage, we need to either  move to a universal paginated list, change to an autocomplete filter, or making bespoke queries to fetch just one property (e.g. loading a page with a filter --> find out what type it is).

**Comment by mariusandra** [comment]
The `eventDefinitionModel` is used:

- [x] ~~In the "Event stats" page~~ no longer a page we have
- [x] When using the taxonomic filter group `TaxonomicFilterGroupType.CustomEvents`, which is only done under paths. https://github.com/PostHog/posthog/pull/11463
- [x] In ActionStep when asking to select the name of the custom event https://github.com/PostHog/posthog/pull/8399
- [x] In EventTable above the property filter to show the event name filter https://github.com/PostHog/posthog/pull/8399
- [x] When choosing an event entity type for a cohort: https://github.com/PostHog/posthog/pull/8416
![image](https://user-images.githubusercontent.com/53387/152004343-6daa450c-6b40-4ede-909d-b52f9ff7ef92.png)
- [ ] `eventNames` is also used in some places. Must investigate.

**Comment by pauldambra** [comment]
excellent analysis 🙌

> (Screenshot taken via a bug: set it to a string property, then type $time and press enter, you'll get the old "equals" filter with a list)

That component is going to make me go bald even faster! e.g. #7970

**Comment by pauldambra** [comment]
I hope you've done a victory lap around the house @mariusandra
