### ISSUE TITLE
renamed labels for Pie Chart doesn't work

### ISSUE THREAD

**Issue by AninaL** [PostHog/posthog#8264]
## Bug description

I have an Insight with several Series and diffrent Filter. I renamed the Series, but it doesn't show the renamed labels on a dashboard, when having a pie chart. 

![image](https://user-images.githubusercontent.com/77632705/151002903-92982cf9-8611-4a9c-a0a9-c728041468b4.png)
![image](https://user-images.githubusercontent.com/77632705/151002931-4a455cf1-1e05-4e18-9d68-d9a8f4e15d12.png)

## Expected behavior

I would expect to the the label name on the dashboard when hovering the pie chart. 

## How to reproduce

1. create insight
2. rename serie
3. select pie chart
4. hover over pie chart

## Environment

- [X] PostHog Cloud
- [ ] self-hosted PostHog (ClickHouse-based), version/commit: _please provide_
- [ ] self-hosted PostHog (Postgres-based, legacy), version/commit: _please provide_

**Comment by pauldambra** [comment]
This was fixed at some point in the past. Sorry we didn't update when it happened 

<img width="1213" alt="Screenshot 2023-04-27 at 08 46 52" src="https://user-images.githubusercontent.com/984817/234795092-17b23879-8769-4e6a-ae8b-da46c6d8adf0.png">
