### ISSUE TITLE
Cohorts export doesn't work

### ISSUE THREAD

**Issue by liyiy** [PostHog/posthog#8267]
## Bug description

*Please describe.*  
*If this affects the front-end, screenshots would be of great help.*  

502 bad gateway at https://app.posthog.com/api/person.csv

and `https://app.posthog.com/api/person/cohorts/?person_id=undefined`

<img width="591" alt="Screen Shot 2022-01-25 at 11 00 41 AM" src="https://user-images.githubusercontent.com/25164963/151012525-c2a4a672-5cbb-414a-881b-f0837313603d.png">

## How to reproduce

1.
2.
3.

## Environment

- [ ] PostHog Cloud
- [ ] self-hosted PostHog (ClickHouse-based), version/commit: _please provide_
- [ ] self-hosted PostHog (Postgres-based, legacy), version/commit: _please provide_

**Comment by Abo7atm** [comment]
I'm facing the same issue.

**Environment**: self-hosted PostHog (ClickHouse-based), version/commit: 1.29.1

**Comment by jackiegreenfield** [comment]
Same. Nothing happens when I try to export, just a blank tab opens up.

Self-hosted Posthog, Clickhouse-based, v1.33.0

**Comment by pauldambra** [comment]
This is fixed on cloud and will be included in release 1.38 for self-hosted
