### ISSUE TITLE
Export 'Insights -> Retention' view of cohorts to spreadsheet

### ISSUE THREAD

**Issue by samtuke** [PostHog/posthog#8274]
## Is your feature request related to a problem?

I need to see the average retention of a given set of user cohorts (we are grouping by product version). Posthog doesn't seem to offer a way to do that, so we want to export the cohort retention view to a spreadsheet so that we can calculate the average manually.

## Describe the solution you'd like

I'd like a spreadsheet export button on the Insights -> Retention pages, eg with URL like this:

`https://posthogurl.com/login?next=/insights%3Ftarget_entity%3D%257B%2522id%2522%253A%2522%2524pageview%2522%252C%2522name%2522%253A%2522%2524pageview%2522%252C%2522type%2522%253A%2522events%2522%257D%26returning_entity%3D%257B%2522id%2522%253A%2522%2524pageview%2522%252C%2522type%2522%253A%2522events%2522%252C%2522name%2522%253A%2522%2524pageview%2522%257D%26period%3DDay%26retention_type%3Dretention_first_time%26display%3DActionsTable%26properties%3D%255B%255D%26filter_test_accounts%3Dtrue%26insight%3DRETENTION%26events%3D%255B%257B%2522id%2522%253A%2522%2524pageview%2522%252C%2522name%2522%253A%2522%2524pageview%2522%252C%2522type%2522%253A%2522events%2522%252C%2522order%2522%253A0%257D%255D%26actions%3D%255B%255D`

## Describe alternatives you've considered

Copy pasting the HTML page content into a spreadsheet. Formatting sucks.

**Comment by samtuke** [comment]
FYI @suelaP

**Comment by mariusandra** [comment]
This is actually done. You can now see the SQL behind a retention chart ("..." -> "Edit SQL directly"), and make any changes you wish, including exporting further or aggregating the data in other ways.
