### ISSUE TITLE
Using GeoIP without storing IP information

### ISSUE THREAD

**Issue by lsmith77** [PostHog/posthog#8284]
## Is your feature request related to a problem?

We want to optimize the balance between privacy and analytics with Posthog. 

Posthog has a project level configuration if to discard IP information.

However, right now I must collect IP data if I want to be able to collect data on the location of users.

## Describe the solution you'd like

Choose if plugins are executed before or after discarding IP data.

## Describe alternatives you've considered

A filter plugin that can be configured to discard any number of fields. This could be useful also because while we like to collect information about the country via the GeoIP plugin, we would prefer not to collect additional information like the city.

**Comment by lsmith77** [comment]
I wonder if https://www.npmjs.com/package/@posthog/schema-enforcer-plugin could already be used as a filter?

> Removes all other properties from an event except selected ones if acceptOnlySchemaProps is true

That being said, it is a bit cumbersome to list all allowed fields. Would be nice to also have a way to just remove unwanted fields explicitly.

**Comment by yakkomajuri** [comment]
Hey @lsmith77! You could very easily write a plugin to strip out IP data from your events.

```
export function processEvent(event) {
    event.ip = null
    if (event.properties) {
         event.properties['$ip'] = null
    }
}
```

You'd then have it run **after** GeoIP.

I'm happy to put this snippet out as a plugin but maybe you'd like to do it yourself to try out building a plugin? :D

**Comment by lsmith77** [comment]
we are on posthog cloud, so we cannot activate our own plugins.
it would be great to maybe have a more generic plugin that one can put at the end of the plugin chain to filter out a configurable list of properties.

**Comment by mariusandra** [comment]
@yakkomajuri I think the easiest solution is to fork the stateless [geoip plugin](https://github.com/PostHog/posthog-plugin-geoip) into a new "geo ip sans ip plugin", which would also clear the IP after setting the location.

**Comment by Twixes** [comment]
Forking sounds pretty overkill, but we can definitely add a setting to just filter it out to the existing plugin. Though @lsmith77 is probably even better – IP addresses aren't the only data some customers may want to avoid storing verbatim.

**Comment by mariusandra** [comment]
@Twixes the GeoIP plugin is a stateless plugin now, meaning it's spin up once for all teams. Hence no settings :(.

**Comment by lsmith77** [comment]
I started working on a plugin https://github.com/witty-works/posthog-property-filter-plugin

**Comment by lsmith77** [comment]
sigh .. unable to get any events send to my local setup, so I cannot test the plugin. see also https://posthogusers.slack.com/archives/C01GLBKHKQT/p1643300241432100

**Comment by lsmith77** [comment]
alright .. issue was the plugin server could not start because monterey uses port 5000 by default for airport sharing .. anyway that slack thread above is full of issues in the docs.

so https://github.com/witty-works/posthog-property-filter-plugin now works and filters properties .. all except for `$ip` .. and I don't know why

my config is `$geoip_city_name,$geoip_longitude,$geoip_latitude,$ip,$geoip_postal_code`

**Comment by lsmith77** [comment]
ah. maybe I also need to add “ip” without the $ to my config

**Comment by lsmith77** [comment]
indeed, adding `ip` did the trick.

not sure if the plugin should be default always append `$` to the property name when filtering.

also one item I have yet to be able to filter out is `$set_once`

here is my full config (note next to the IP, all we want really is the country and state info. we also do not want the full referrer URL, only the domain):
```
$geoip_city_name,$geoip_longitude,$geoip_latitude,$ip,ip,$geoip_postal_code,$current_url,$set_once,set_once,$performance_raw
```

@yakkomajuri at any rate, would you consider making https://github.com/witty-works/posthog-property-filter-plugin  an official plugin?

**Comment by lsmith77** [comment]
ah .. removing `$referrer` also removed `$initial_referrer` from `$set_once`

**Comment by lsmith77** [comment]
https://github.com/PostHog/integrations-repository/pull/3
