### ISSUE TITLE
Dashboard themes or templates that align to problem areas

### ISSUE THREAD

**Issue by clarkus** [PostHog/posthog#8300]
## Is your feature request related to a problem?

We have some default insights and dashboards now, but I wonder if we could improve the onboarding experience and time to value by offering some simple presets based on commonly available events.

## Describe the solution you'd like

When I go to create a new dashboard or insight, I see a secondary option that suggests pre-built dashboards that answer common questions in standardized ways. This would give the user the support they need where they need it (when deciding to create something) and it would avoid the issue of overloading the initial sets with a bunch of insights you might not want. 

Initial ideas - dashboards built to describe specific results - acquisition, retention, basic overviews, etc. 

## Describe alternatives you've considered

Doing nothing

## Additional context

Some competitors call these "playbooks".

**Comment by andyvan-ph** [comment]
Just lending my voice to say this is a good idea and we should totally do it.
