### ISSUE TITLE
Cannot perform math operations (sum, avg, etc) on number properties of events

### ISSUE THREAD

**Issue by TonySci** [PostHog/posthog#8308]
## Bug description
We have a "deposit_added" event that fires when a user's deposit clears. Within that event is a property called "transaction_amount" - that property is confirmed to be a number when I look at the details of individual events in the Events&Actions list

*Please describe.*  
Screenshot of posthog saying there are no matching events:
![image (1)](https://user-images.githubusercontent.com/94004058/151266464-0ac276ef-9f5e-4e10-9c26-033e372691b9.png)

if I change this to be based on TOTAL COUNT, I see events firing as expected.
Here is an example of the deposit_added event in full detail
![image](https://user-images.githubusercontent.com/94004058/151269447-a8ec32e7-8e8d-410c-994f-a02fb81bfc88.png)

## Environment

- [x] PostHog Cloud

**Comment by mariusandra** [comment]
It seems that all your transaction properties are nested inside a `records` object. Basically,

```js
posthog.capture('deposit_added', { 
    entity_type: 'customer_deposit', 
    records: { transaction_amount: 7816, ... } 
})
```

We don't support aggregations on nested properties just yet. To work around this, you can either use the "Property Flattener Plugin" that would then create a property `records__transaction_amount` that you can filter on, or just move the transaction fields to the root of the properties.
