### ISSUE TITLE
Event Auto capture(We have configured the posthog into our application but events are not capturing)

### ISSUE THREAD

**Issue by Moneshs** [PostHog/posthog#8309]
## Bug description

*Please describe.*  
*If this affects the front-end, screenshots would be of great help.*  

## Expected behavior

Events need to be captured in posthog but it is not capturing any data in the posthog UI

## How to reproduce

1. we have updated posthog with click house and even we changed the project api key, but its not working as expected

## Environment

- [ ] self-hosted PostHog (ClickHouse-based), version/commit: 1.31.1, 153b58d9f906fb6f99df942364017738b565d068

**Comment by Hassan-Mallah** [comment]
Hey,

We also have the same issue. Cheers

**Comment by liyiy** [comment]
Hey there! What does your `/instance/status` look like? Also, joining our [posthog slack](https://posthog.com/slack) will help us debug your issues faster

**Comment by Moneshs** [comment]
> Hey there! What does your `/instance/status` look like? Also, joining our [posthog slack](https://posthog.com/slack) will help us debug your issues faster

There is no problem in the instances.

**Comment by eshabarchin** [comment]
Hey. My installation has the same issue. and from first look doesn't have any issues. Could you specify what exactly can be checked?

**Comment by neilkakkar** [comment]
Hey @eshabarchin ! On the top right corner: 
![image](https://user-images.githubusercontent.com/7115141/151783358-ab0e00a1-7908-47d0-8027-6d7f5ce11638.png)

If you go to system status, does it say all services are alive or not? (Usually, when events aren't ingesting, the plugin server is down)

**Comment by eshabarchin** [comment]
@neilkakkar That is how it looks like in my installatio
![Screenshot 2022-01-31 at 11 10 47](https://user-images.githubusercontent.com/98740410/151784059-8450e619-4ce6-4fc7-8549-de8fb9f7712d.png)
n

**Comment by liyiy** [comment]
@eshabarchin Is this a fresh installation? Are you using ClickHouse?

**Comment by eshabarchin** [comment]
Yes, it is a fresh installation. I started to detail with it 2 weeks ago, seems you got some problems with the installation script, I contacted one of the Community support guys. They told me that the installation has been fixed and it was true.

**Comment by liyiy** [comment]
I think you have to use ClickHouse that might be where your events are being sent which is why you're not seeing it https://posthog.com/docs/self-host/deploy/configuration#scaling-up

**Comment by eshabarchin** [comment]
@liyiy Maybe you are right but in my case, we discussing "Hobby" self-hosted installation. 
 The link you provided to me is about the adjustment of amount of resources and scaling of the installation. In this case, even test events aren't here. 
Project documentation isn't super detailed at least for now so I would be really appreciated if you could guide me on what exactly needs to be adjusted to make the installation work.  As I see, the concept of "hobby" installation is - run installation script, put site name and it should be ready to go.

Clickhouserelated peace of docker-compose.hobby.yml

    clickhouse:
        image: yandex/clickhouse-server:21.6.5
        restart: on-failure
        depends_on:
            - kafka
            - zookeeper
        ports:
            - '8123:8123'
            - '9000:9000'
            - '9440:9440'
            - '9009:9009'
        volumes:
            - ./posthog/ee/idl:/idl
            - ./posthog/docker/clickhouse/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
            - ./posthog/docker/clickhouse/config.xml:/etc/clickhouse-server/config.xml
            - ./posthog/docker/clickhouse/users.xml:/etc/clickhouse-server/users.xml

**Comment by pauldambra** [comment]
I can see @Moneshs is getting support on this issue in [our community slack](posthog.com/slack)

That's the best place to get support for this class of issue as one step is to ask you to share your logs so we can help diagnose and you may need to redact them for GitHub.

There are two points in our documentation to start @eshabarchin @Hassan-Mallah 

https://posthog.com/handbook/engineering/deployments-support
and
https://posthog.com/docs/self-host/deploy/troubleshooting

Which may help you to self-diagnose your issues.

Other than that I think it could get confusing to try and troubleshoot three separate deployments in one GitHub issue. So I'd propose we move to [our community slack](posthog.com/slack) and close this issue...
