### ISSUE TITLE
My new router blocked our app (app.posthog.com) by default

### ISSUE THREAD

**Issue by rcmarron** [PostHog/posthog#8326]
I just set up a new router and the default settings blocked me from going to app.posthog.com. It took me a while to realize that the router had an analytics blocker running by default, and it blocked all requests to app.posthog.com.

Makes me wonder if we should have ingestion and the app on different domains? The router was an Eero, so it's a pretty common one. I could definitely see users being very confused by this.

**Comment by Twixes** [comment]
This is the case now.
