### ISSUE TITLE
Creation overlay shows when returning to dashboards

### ISSUE THREAD

**Issue by joesaunderson** [PostHog/posthog#8329]
## Bug description

When I create a dashboard, it takes me to the newly created dashboard. When I next return to 'All dashboards' via the menu item, the creation overlay shows again - I no longer want to add a dashboard. 

## Expected behavior

The creation overlay should not show.

## How to reproduce

1. Create a dashboard
2. Return the dashboards page

## Environment

- [ ] PostHog Cloud
- [x] self-hosted PostHog (ClickHouse-based), version/commit: 1.31.1
- [ ] self-hosted PostHog (Postgres-based, legacy), version/commit: _please provide_

#### *Thank you* for your bug report – we love squashing them!

**Comment by Twixes** [comment]
1.33 includes a new, much nicer modal for dashboard creation, which solves this issue.
