### ISSUE TITLE
JS Typeerror when loading setup page

### ISSUE THREAD

**Issue by nsb** [PostHog/posthog#834]
**Describe the bug**
When entering /setup page the React UI fails with a typeerror.

**To Reproduce**
1. Login to posthog
2. Click on setup
3. 

**Expected behavior**
I would expect to see the setup page

**Screenshots**
![posthog_setup](https://user-images.githubusercontent.com/16436/82724742-a26ad200-9cd8-11ea-89c2-8184e211175b.png)

**Desktop (optional: please complete the following information):**
 - OS: Ubuntu 20.04
 - Browser: Firefox and Chrome
 - Version: Firefox 76.01, Chrome 83.0

**Smartphone (optional: please complete the following information):**
 - Device: 
 - OS: 
 - Browser 
 - Version 

**Additional context**
It could be specific to my account.

**Comment by timgl** [comment]
Hey, thanks for raising this! This was fixed last night with #829, though only deployed to app.posthog.com (if you're using that) this morning. Let me know if that fixes it for you!

There's a related error message that I'm fixing in #835.

**Comment by nsb** [comment]
Thanks, it works now! I see another error when loading the setup page now.

![Screenshot from 2020-05-23 11-22-35](https://user-images.githubusercontent.com/16436/82726987-e3b6ae00-9ce7-11ea-997a-d8ba1bd1fdfc.png)

**Comment by timgl** [comment]
Yep, that should be fixed once #835 goes in :)
