### ISSUE TITLE
Experiments phase in and out of being stat sig

### ISSUE THREAD

**Issue by marcushyett-ph** [PostHog/posthog#8341]
## Bug description
When running an experiment I've seen the red and green stat-sig banners, go from red to green back to red:
![image](https://user-images.githubusercontent.com/85295485/151559694-ef2177d3-0e25-4a8a-b329-3201c6483053.png)

Surely it wasn't okay to end the experiment early if now (with more data) its no longer safe to end the experiment.

## Expected behavior
As a user I'd love more transparency around why my experiment is okay to end now, or why I need to wait longer? And I'd also want it to be consistent (e.g. if its okay now it should be theoretically okay to end the experiment at any point in the future too)

## How to reproduce
Really hard to reproduce so I can just explain what I saw
1. https://app.posthog.com/experiments/21
2. Day 1 showed red banner
2. Yesterday around afternoon UTC showed green banner
3. Today 2pm showed red again

**Comment by neilkakkar** [comment]
Hmm, this is surprising. While the above behaviour is definitely possible, it should be impossible for this specific experiment, given the volume is so low. (we have a threshold of 100 people for significance). Can you ping me when/if it turns green again?


>  consistent (e.g. if its okay now it should be theoretically okay to end the experiment at any point in the future too)

Hmm, I agree from a user point of view, but I don't actually think any kind of experiment can guarantee this. As long as an experiment keeps running, new data keeps coming in, which can be wildly different from data we've seen before. A 95% confidence interval basically implies that the chance of this is < 5%.

Do you think our user guide needs to do a better job of explaining this? Or, maybe we should somehow put this in the UI?

**Comment by marcushyett-ph** [comment]
Yeah I agree its not practical to guarantee this...but that would be my expectation as an uninformed user.

I think we should be transparent about the 100 person threshold in the product, and perhaps explain why in the docs?

**Comment by neilkakkar** [comment]
We've done some work around this to tell you exactly why experiments aren't significant
