### ISSUE TITLE
Unclear error message (on slow internet)

### ISSUE THREAD

**Issue by corywatilo** [PostHog/posthog#8351]
On an unreliable internet connection, the page can't load data and shows a message that says there's no matching data. However, in Console, the problem says `ERR_HTTP2_PING_FAILED`.

Are we able to use this error to more accurately explain the problem to the user? Ie: "There was a problem loading PostHog. Please try reloading the page."

![image](https://user-images.githubusercontent.com/154479/151709339-1cbdab52-fba0-4146-b9af-5645c1193630.png)

**Comment by pauldambra** [comment]
This hits us in a few places where we don't reliably distinguish between 

* we're still loading data
* we couldn't load any data
* we didn't load any data

related as an example: https://github.com/PostHog/posthog/pull/8055

**Comment by pauldambra** [comment]
Looking here https://confluence.atlassian.com/confkb/har-file-captures-err_http2_ping_failed-1005793334.html

The browser error in the screenshot is

```
      "startedDateTime": "2020-05-01T04:35:34.348Z",
        "time": 78.40789100003894,
        "request": {
          "method": "POST",
          "url": "http://localhost:8090/",
          "httpVersion": ""
          .
          .
        "response": {
          "status": 0,
          "statusText": "",
          "httpVersion": "",
          "headers": [],
          "cookies": [],
          "content": {
            "size": 0,
            "mimeType": "x-unknown"
          },
          "redirectURL": "",
          "headersSize": -1,
          "bodySize": -1,
          "_transferSize": 0,
          "_error": "net::ERR_HTTP2_PING_FAILED"
```

When we check if an exception is an error we check if status > 400, and to check for a timeout we check if there is an exception that is not a 500

So, if we throw an exception with http status 0 we show the query timeout view

If we have a response that has status: 0 without throwing we show the empty data view

**Comment by pauldambra** [comment]
@corywatilo I will close this as #8603 should fix it. Reopen if I'm a liar! :)
