### ISSUE TITLE
CSS served over http

### ISSUE THREAD

**Issue by zub0r** [PostHog/posthog#836]
**Describe the bug**
The page was loaded over HTTPS, but requested an insecure stylesheet static/main.css  This request has been blocked; the content must be served over HTTPS.

**To Reproduce**
1. install with docker compose and integrate with `import posthog from 'posthog-js';`
2. successfully capturing events on https site
3. Actions -> new action -> frontend element -> select element on site -> loads css over http and blocks the action editor

**Expected behavior**
stylesheet loaded over https 

**Hosted or self hosted?:**
- self-hosted
- latest docker, version not showed in poshog admin

**Comment by timgl** [comment]
@zub0r Hey! Super sorry, I completely missed this ticket.

I think this might be related to [being behind a proxy](https://posthog.com/docs/deployment/running-behind-proxy), but not having set `IS_BEHIND_PROXY`.

Let me know if that helps!
