### ISSUE TITLE
Breakdown by cohort shows cohort ID

### ISSUE THREAD

**Issue by joesaunderson** [PostHog/posthog#8368]
## Bug description

When breaking down by cohort, the tooltip shows the ID of the cohort, not the name

![image](https://user-images.githubusercontent.com/11272509/151872961-0ef5af50-b5e5-4174-827a-33f5d84565a4.png)

## Expected behavior

The tooltip shows the cohort name.

## How to reproduce

1. Create a trend insight
2. Breakdown by cohort

## Environment

- [ ] PostHog Cloud
- [x] self-hosted PostHog (ClickHouse-based), version/commit: 1.32.0 
- [ ] self-hosted PostHog (Postgres-based, legacy), version/commit: _please provide_

## Additional context

N/A

**Comment by paolodamico** [comment]
I believe this is a problem of cohorts loading async and maybe taking a long time. We should consider showing a loading state instead.
