### ISSUE TITLE
Heroku Posthog Add-On

### ISSUE THREAD

**Issue by fuziontech** [PostHog/posthog#837]
Ideally we make PostHog a turnkey solution for users using Heroku, much like Sentry on Heroku.

Following the instructions from their docs we have a bit of work to do:
https://devcenter.heroku.com/articles/building-an-add-on

Actions you must implement:
Provisioning a new instance of your add-on,
OAuth token exchange, and
Deprovisioning an add-on instance.

Optional actions that you may implement include:
Plan upgrades or downgrades,
Creating webhooks on the app associated with an add-on resource,
Implementing SSO to allow your Heroku customers to log in to a dashboard you provide, and
Requesting additional information about a customer or their app environment via the Platform API for Partners.

We will need to build out an implementation for their partner API
https://devcenter.heroku.com/articles/add-on-partner-api-reference

For the actual implementation we can either use the provisioning request to create a team on PostHog 'cloud' or we can spin up a dedicated environment for each user.

I believe using PostHog cloud is the way to go as 80+% of these environments will see little to no traffic.

**Comment by paolodamico** [comment]
No more Heroku + PostHog :(

**Comment by joaopcm** [comment]
Why?
