### ISSUE TITLE
PostgreSQL - plugin-server: `INSERT INTO posthog_persondistinctid` value too long for `character varying(400)` 

### ISSUE THREAD

**Issue by guidoiaquinti** [PostHog/posthog#8380]
## Bug description
```
2022-02-01T13:44:05.000000+00:00 app[postgres.128170]: [PINK] [148-1]  sql_error_code = 22001 ERROR:  value too long for type character varying(400)
2022-02-01T13:44:05.000000+00:00 app[postgres.128170]: [PINK] [148-2]  sql_error_code = 22001 STATEMENT:  /* plugin-server:addDistinctIdPooled */ INSERT INTO posthog_persondistinctid (distinct_id, person_id, team_id, version) VALUES ($1, $2, $3, 0) RETURNING *
```

## Expected behavior
No errors are expected.

## How to reproduce
N/A

## Environment

- [X] PostHog Cloud
- [ ] self-hosted PostHog (ClickHouse-based), version/commit: _please provide_
- [ ] self-hosted PostHog (Postgres-based, legacy), version/commit: _please provide_

**Comment by tiina303** [comment]
Investigation:
1. The problematic Insert is https://github.com/PostHog/posthog/blob/07f5f565abbc67d510bc30edc48c5f74a42f00fa/plugin-server/src/utils/db/db.ts#L717 
2. The value that is too long is `distinct_id` being the only field with 400 limit https://github.com/PostHog/posthog/blob/9939c3f6016db9d61a2775eec70e860440c511e9/posthog/models/person.py#L113
3. The distinctId can be provided by the user during identify or alias calls, where we don't have length restrictions applied.

What we could do:
1. just cut the `distinct_id` to first 400 chars always & maybe document to users.
2. error/dlq capture calls with `distinct_id` > 400 char - we don't have a good story for getting events ingested from dlq atm.
3. make the `distinct_id` col not have any length restrictions, e.g. `Text` - we likely shouldn't do this as we don't control the input and it's length in any way, which could be an attack vector?

**Comment by tiina303** [comment]
Looked into the usage or who has longer than 400 distinct_ids and there aren't that many ([thread](https://posthog.slack.com/archives/C01MM7VT7MG/p1644949938704479)).
