### ISSUE TITLE
PostgreSQL - slow query when searching people

### ISSUE THREAD

**Issue by hazzadous** [PostHog/posthog#8391]
## In what situation are you experiencing subpar performance?

[`filter_persons`](https://github.com/PostHog/posthog/blob/f6c2e84dab90772fe1e9cfd39c2687f0b1d2ded6/posthog/queries/base.py#L199), used in a few places, results in a query such as:

```
LOG:  duration: 5847.944 ms  statement: SELECT DISTINCT ON ("posthog_person"."id") "posthog_person"."id", "posthog_person"."created_at", "posthog_person"."properties_last_updated_at", "posthog_person"."properties_last_operation", "posthog_person"."team_id", "posthog_person"."properties", "posthog_person"."is_user_id", "posthog_person"."is_identified", "posthog_person"."uuid", "posthog_person"."version" FROM "posthog_person" LEFT OUTER JOIN "posthog_persondistinctid" ON ("posthog_person"."id" = "posthog_persondistinctid"."person_id") WHERE ("posthog_person"."team_id" = 2 AND (UPPER("posthog_person"."properties"::text) LIKE UPPER('%harry@posthog.com%') OR UPPER("posthog_persondistinctid"."distinct_id"::text) LIKE UPPER('%harry@posthog.com%'))) ORDER BY "posthog_person"."id" DESC LIMIT 101
```

Which can take over 5 seconds. Note that it does a cast of a `jsonb` field to text, e.g. renders it as JSON then does an icontains in this. That might be a red herring but I double it's fast.

**Comment by neilkakkar** [comment]
Not just properties filter, but the [search filter on persons](https://github.com/PostHog/posthog/blob/master/posthog/api/person.py#L134) faces the exact same issue.

Heard several users complain about it [this](https://posthogusers.slack.com/archives/G01JXEDAL22/p1646730365990129) [week](https://posthogusers.slack.com/archives/C01GLBKHKQT/p1646715553544169) (atleast 3)

which looks something like:

```
'SELECT "posthog_person"."id", "posthog_person"."created_at", "posthog_person"."properties", "posthog_person"."uuid" FROM "posthog_person" WHERE ("posthog_person"."team_id" = %s AND ("posthog_person"."properties" -> %s) IN (%s)) ORDER BY "posthog_person"."id" DESC LIMIT 101'
```

**Comment by neilkakkar** [comment]
Also linking relevant issue which might supercede this: https://github.com/PostHog/posthog/issues/7963

**Comment by neilkakkar** [comment]
Removing duplicates!
