### ISSUE TITLE
Cannot 'load more breakdown values' on table graphs

### ISSUE THREAD

**Issue by JamieHanratty** [PostHog/posthog#8400]
## When creating a simple table graph, the button to 'Load more breakdown values' doesn't work for me. We are on the Open Source version.

When I try to load 'load more breakdown values' at the bottom of a table graph, it loads the values briefly then fails. It seems to be a UI thing as I can glimpse the results for a short moment of time.
This happens on any table graph, with any type of data. Here is an example: https://www.loom.com/share/72c98c2a182f4296a176a714efb16c10

## Expected behavior
I can load more rows in the table graph.

## How to reproduce

1. From a 'Dashboard', create a table graph of a simple property - e.g. Page Views
2. Add any 'Breakdown By' property
3. Select the 'Table' view for the generated results below
4. Scroll to the bottom of the table
5. Click the button 'Load More Breakdown Values'

## Environment

- [ ] self-hosted PostHog 1.30.0

**Comment by mariusandra** [comment]
We did several changes to improve breakdown controls for trends. Closing.
