### ISSUE TITLE
Create platform runbook for supporting deployments and include a line item that if people have a ton of issues scaling or operating the helm chart that we push them towards cloud. Especially if they are not paying and don't have a compelling reason to self-host.

### ISSUE THREAD

**Issue by fuziontech** [PostHog/posthog#8406]

**Comment by tiina303** [comment]
I didn't do Create platform runbook for supporting deployments @fuziontech do you think we should still do it. The nudge towards cloud is done: https://github.com/PostHog/posthog/issues/8407

**Comment by guidoiaquinti** [comment]
+1 to what @tiina303 wrote. Since we’ve opened this issue, I think we have improved our documentation to guide users with little technical knowledge towards PostHog Cloud. I’m closing this. Feel free to reopen if we’ve missed anything.
