### ISSUE TITLE
Layout regression for persons & groups tables

### ISSUE THREAD

**Issue by clarkus** [PostHog/posthog#8428]
## Bug description
Tables are sizing in unexpected ways. Content that is usually static (icons for example) are filling the available are to displace inline text content.

<img width="615" alt="Screen Shot 2022-02-03 at 4 15 04 PM" src="https://user-images.githubusercontent.com/254612/152450893-23cc5079-57b5-4543-8fc2-2449316e9cfe.png">

## Expected behavior

Expect columns that contain static content to size to their content. 

## How to reproduce

1. View a table on the persons and groups feature

## Environment

- [x] PostHog Cloud

**Comment by Twixes** [comment]
Great case for `git bisect`. This was introduced by #8347.
<img width="669" alt="Screen Shot" src="https://user-images.githubusercontent.com/4550621/152458049-cf8f321c-1bd3-4cf3-b5db-c07c11e1692f.png">
This is a no-no @yakkomajuri @tiina303! These styles apply globally so they affect ALL tables in the app. Instead, `LemonTableColumn`'s `width` option should be used.

**Comment by mariusandra** [comment]
Tsk tsk... the frontend coding conventions event talk about exactly this... https://posthog.com/docs/contribute/coding-conventions#do-s--dont-s

**Comment by yakkomajuri** [comment]
Sorry, had been a while since I was working in the frontend - I did know this, had a brain fart here by not scoping it to that component.
