### ISSUE TITLE
Request: Duplicate actions and/or reference actions in other actions

### ISSUE THREAD

**Issue by paolodamico** [PostHog/posthog#8431]
## Is your feature request related to a problem?

Sometimes you want to extend the definition of an action to encompass more events (e.g. considering dashboards & Discoveries) without changing the original action.

## Describe the solution you'd like

1. A starting point would be allowing you to duplicate an action or create a new action based on an existing action.
2. Even better would be the ability to reference existing actions in a new action.

## Describe alternatives you've considered

Described above.

## Additional context

Approach (1) is a good first issue. Approach (2) will probably require more considerations.

**Comment by benhint** [comment]
Upvote from me!

**Comment by nizarmah** [comment]
For future reference, I believe https://github.com/PostHog/posthog/pull/15911 addresses Approach (1) by creating _copying_ actions. It's also the reason #15485 was closed.
