### ISSUE TITLE
People seem scared to create new experiments(?)

### ISSUE THREAD

**Issue by neilkakkar** [PostHog/posthog#8436]
## Bug description

Copied from a slack conversation in spirit of openness and looking for solutions from everyone.

Initial data suggests a pressing problem with Experiments: [People, for some reason, open the creation screen but don't create experiments](https://app.posthog.com/insights/GqV3RFZA).

There's a few reasons:
1. Just want to play with the MDE calculations
2. Just checking out the new feature
3. They're afraid that clicking Save would start the experiment / do things they don't know.

(3) is in our control and we should solve for it! Chris recently had this idea of a workflow checklist which can clarify steps:

![image](https://user-images.githubusercontent.com/7115141/152534104-a70b86ae-4196-4928-998b-d26fc32854f2.png)

(This also has the added benefit of reinforcing the testing phase before launching, which is the 2nd wall to cross)

Are there any other ideas? (cc: @paolodamico @rcmarron @liyiy @clarkus )

**Comment by neilkakkar** [comment]
Hmm, this might as well be true, but looking at recordings so far, doesn't seem to be the case: Most people who got to the screen didn't actually do anything with Experiments yet.  So, waiting for more data is probably prudent.

**Comment by liyiy** [comment]
If these people are anything like me they probably go to the page, see there's a lot of stuff, and then nope out because that's what I would do 😭

**Comment by clarkus** [comment]
Is this instrumented or quantified in any way? Do we have expected usage rates for each type of account? I feel like it's pretty valid that some users won't use experiments yet. They might not need it, might not really be willing to trust a new beta feature with something as precious as their analytics data, etc. We could blame it on the current layout, but I feel like there's more to it.

**Comment by corywatilo** [comment]
Stepping back: We haven't really done much product marketing for this _yet_. We mentioned it in [Array 1.33](https://posthog.com/blog/the-posthog-array-1-33-0) and have a nice [user guide](https://posthog.com/docs/user-guides/experimentation), but that's about it. (Unless @camerondeleone is actively demoing?) There's a bit of education that needs to be done to inform customers we now have this feature. (This includes having a product page for this, which is a WIP but will be up soon!)

So in summary, _"Build it and they will come"_ might not be the right expectation for an entirely "new" feature.

That said, the initial _New experiment_ screen feels overwhelming -- _but I think with some small changes, we can easily improve it!_

<img width="1496" alt="image" src="https://user-images.githubusercontent.com/154479/158665223-1f40d601-650d-4a4b-b569-91ba2c8cca96.png">

## Suggestions:

- [ ] Don't show the funnel/trend preview section by default. Force a selection under _Goal type_ which _then_ displays this block:

    <img width="579" alt="image" src="https://user-images.githubusercontent.com/154479/158666693-a115e0f9-cac9-46ba-a6a7-2cd2dbb517c1.png">

- [x] Move _Minimum acceptable improvement_ into the left column, so the _form_ is in a single column and the _preview_ is the only thing in the right column. (This will help the page feel more digestible on first load.)

I think these two things alone will really help make the page feel less like an airplane cockpit and more like filling out a tax form! =]

**Comment by neilkakkar** [comment]
I had closed this issue because conversion trend has remained reasonably consistent, and there's no good data to suggest the layout was to blame.

> We could blame it on the current layout, but I feel like there's more to it.

Yep, exactly.

Further, with the layout change PR already out, a part of this would be resolved, which is similar to what Cory is suggesting: https://github.com/PostHog/posthog/pull/9047

After launch, if we're still seeing a very low conversion, will open a new issue specifically for that.
