### ISSUE TITLE
PostHog Plugin Bounty

### ISSUE THREAD

**Issue by marcushyett-ph** [PostHog/posthog#8437]
We really appreciate our community and all of awesome plugins you've built so far, to name a few [Salesforce](https://github.com/Vinovest/posthog-salesforce), [Google Pub Sub](https://github.com/vendasta/pubsub-plugin), [Rudderstack](https://github.com/rudderlabs/rudderstack-posthog-plugin). We're keen to expand our plugin library even further and would love your help to do just that.

**What plugins would you like shipped?**

On shipping of one of these plugins (i.e. available publicly in open source repo and demoed to a PostHog team member), we'll issue the bounties below:

1. **Data Bricks** (Export Plugin) [Project Spec](https://github.com/PostHog/posthog/issues/8441): $1000
1. ~**Zendesk** (Import / Export) [Project Spec](https://github.com/PostHog/posthog/issues/8440): $750~
1. **Hubspot** (import plugin) [Project Spec](https://github.com/PostHog/posthog/issues/8438): $500
1. ~**Twilio** (SMS on event Plugin) [Project Spec](https://github.com/PostHog/posthog/issues/8439): Exclusive PostHog Merch (Hoodie and Timbuk2 backpack)~
1. **Shopify** (import plugin) [Project Spec](https://github.com/PostHog/posthog/issues/8442): Exclusive PostHog Merch (Hoodie and Timbuk2 backpack)

**How do I get started?**
1. Comment on this issue if you're interested in building one of these
2. Click through to the linked spec for the plugin you're interested in and assign it to yourself
3. Follow the getting started details and ship it!

**What if two people want to work on the same plugin?**
We can only provide one bounty for each plugin (to the first working plugin submitted), so please request to be assigned the **plugin spec issue** to yourself so others know you're working on it. If you haven't made progress in a week, please un-assign the issue so someone else has the chance to give it a go.

**What if I'd rather have merch than cash?**
Any cash prize can be swapped for merch of the equivalent value

**What if I get stuck?**
Ideally you should be able to build these plugins without any support from us, but if you do get stuck please just reach out to us in the #contributing channel of our users slack for help

**Comment by jamesefhawkins** [comment]
Suggest we add a bigquery _import_ (and perhaps imports for the other major warehouses if we don't already have them) - being asked [by a community member](https://posthog.slack.com/archives/C02E3BKC78F/p1649335524143749) for this.

**Comment by joethreepwood** [comment]
Is this still an up-to-date and active list that we're encouraging people to? If not, suggest we close this so users don't start work and expect payment for a dead initiative.

**Comment by JoseCToscano** [comment]
Hi all, I see that https://github.com/PostHog/posthog/issues/8438 is still open. Is it really open or is it just outdated?
If work is still missing, can I give it a try?

**Comment by joethreepwood** [comment]
HI @JoseCToscano - Unfortunately this bounty programme was closed mid-last year and this issue wasn't updated. We still welcome submissions of new apps and you're welcome to work on this plugins, but we're no longer offering a bounty as an incentive. Apologies for the confusion.

**Comment by gogi2811** [comment]
No more plugins required?

**Comment by joethreepwood** [comment]
Unfortunately, we're no longer running this bounty program.

**Comment by joethreepwood** [comment]
Hi Ricardo -- We're actually making substantial changes to the app system at the moment, so I'd recommend looking into other areas if you'd like to contribute. We have many other feature requests you can find, as well as a Good First Issue tag for inviting contributions. Thanks for the support!

https://github.com/PostHog/posthog/issues?q=is%3Aissue+is%3Aopen+good+first+issue+label%3A%22good+first+issue%22

**Comment by bemall** [comment]
Please update the speculative application page by Coua to reflect that the bounty program is no longer active.
https://posthog.com/careers/speculative-application

**Comment by joethreepwood** [comment]
Thank you, I will do this now.
