### ISSUE TITLE
Hubspot Import Plugin Spec

### ISSUE THREAD

**Issue by marcushyett-ph** [PostHog/posthog#8438]
**⚠️This is part of our plugin bounty if you intend to work on this issue please [read this issue](https://github.com/PostHog/posthog/issues/8437) first⚠️**

## Background

Hubspot is one of the top Customer Relationship Management systems, and has a wealth of data that could be used to enrich your customer profiles and analytics on PostHog. We already have an[ export plugin](https://github.com/PostHog/hubspot-plugin/blob/main/index.js) but an import plugin would enable our users to do much more with their hubspot integration.

Ideally you would extend our existing Hubspot plugin, it has some (undocumented) import features already - which should make this quite easy to build on top of.

## Requirements

**Features**

The plugin should be capable of doing the following:

<table>
  <tr>
   <td><strong>Feature</strong>
   </td>
   <td><strong>Description</strong>
   </td>
  </tr>
  <tr>
   <td>Enrich specified group type with company and deals information
   </td>
   <td>Enrich a user-specified group type with information about companies and deals from hubspot (e.g. size of company, status of deals, etc.)
   </td>
  </tr>
  <tr>
   <td>Enrich users 
   </td>
   <td>Enrich users on posthog with data from contacts on hubspot
   </td>
  </tr>
  <tr>
   <td>Configuration
   </td>
   <td>Users must be able to configure the plugin to use their API key and define the group type they would like to enrich with company and deal information
   </td>
  </tr>
</table>

## Reference Information

* The relevant API documentation can be found here: 
    * [https://developers.hubspot.com/docs/api/crm/deals](https://developers.hubspot.com/docs/api/crm/deals)
* You can set up a free trial account here: [https://www.hubspot.com/products/get-started](https://www.hubspot.com/products/get-started)
* The following plugins provide some similar patterns which can be used as inspiration to to build this plugin:
    * [https://github.com/PostHog/hubspot-plugin/blob/main/index.js](https://github.com/PostHog/hubspot-plugin/blob/main/index.js)
    * [https://github.com/PostHog/twitter-followers-plugin/blob/main/index.js](https://github.com/PostHog/twitter-followers-plugin/blob/main/index.js)
* Since this also requires groups functionality, please read our group analytics documentation:
    * [https://posthog.com/docs/user-guides/group-analytics](https://posthog.com/docs/user-guides/group-analytics)
    * You will also need to generate some group types and group data in order to populate these for testing and development

To start building a plugin:

* Comment on this issue so everyone knows you're picking it up and assign it to yourself
* Join our #contributing channel [on slack](https://posthog.com/slack) and let us know you're working on this task
* If you require we can provide you with login credentials to a development PostHog cluster where you can build and test your plugins, you could also run PostHog locally if you prefer to develop there
* Read through our developer reference for plugins: [https://posthog.com/docs/plugins/build/reference](https://posthog.com/docs/plugins/build/reference) and start building
* Let us know on [slack](https://posthog.com/slack) in the #contributing channel if you need any help or further information

## Getting it Shipped

* Create a public MIT Licensed repo on github, add all of your code and create a readme that explains the plugin
* Once you're done, reach out to the Posthog team in the #contributing channel and we'll take a look
* If your plugin works as expected, we’ll send you the bounty and get it live in our integrations catalog
* If you decide not to work on this after starting or don't make any progress in a week, please un-assign it so someone else can take it on

**Comment by chinmaym07** [comment]
Hey @marcushyett-ph I would like to try this. Shall I go ahead.?

**Comment by marcushyett-ph** [comment]
Hi @chinmaym07 yes, please go ahead and assign this issue to yourself.

For this one we have a hubspot plugin that already solves part of the problem, so it would be great if you could build on top of it, by creating a PR against it rather than an entirely new plugin: https://github.com/PostHog/hubspot-plugin/blob/main/index.js)

It has some undocumented import features already that you'll be able to see in the code, which should help you with this.

**Comment by Jaspreet-singh-1032** [comment]
Hey @marcushyett-ph, Is this issue still in progress? I would like to give it a try.

**Comment by marcushyett-ph** [comment]
@chinmaym07 would you be able to share an update?

**Comment by Jaspreet-singh-1032** [comment]
Hey @marcushyett-ph, Should I go ahead if @chinmaym07 is no more working on this issue?

**Comment by marcushyett-ph** [comment]
Lets give @chinmaym07 24hrs to respond. If not, assign to yourself and go ahead.

**Comment by Jaspreet-singh-1032** [comment]
Ya sure @marcushyett-ph, thanks.

**Comment by chinmaym07** [comment]
Hey @marcushyett-ph .. thankyou for your time here. 
Sorry I am occupied with some other work .. I'll not be able to complete this soon. 
I'll try my hands on some other issue soon.
I'll ask @Jaspreet-singh-1032 to go ahead with this issue. 
Happy contributing .. !!

**Comment by marcushyett-ph** [comment]
Thanks @chinmaym07 please go ahead.

@Jaspreet-singh-1032 Extra context:

For this one we have a Hubspot plugin that already solves part of the problem, so it would be great if you could build on top of it, by creating a PR against it rather than an entirely new plugin: https://github.com/PostHog/hubspot-plugin/blob/main/index.js)

It has some undocumented import features already that you'll be able to see in the code, which should help you with this.

Also, we've recently updated our docs to include more detail on writing tests for plugins: https://posthog.com/docs/plugins/build/reference

**Comment by Jaspreet-singh-1032** [comment]
Thanks, @chinmaym07 for your respone. and @marcushyett-ph thanks for these details.
Just wanted to know I have set up the posthog on local. Since this issue also requires group analytics but it is not supported on the open-source version. So how can I test this out?

**Comment by marcushyett-ph** [comment]
Sure I've set up a development instance with access to all posthog features and demo data.

If you're on our users slack, can you DM me your email and I'll invite you?

**Comment by Jaspreet-singh-1032** [comment]
Ya sure @marcushyett-ph

**Comment by jyuvaraj03** [comment]
Hey @marcushyett-ph, @Jaspreet-singh-1032 is this issue still in progress? I'd like to be assigned if it's not being actively developed.

**Comment by Jaspreet-singh-1032** [comment]
Hey @jyuvaraj03. I had opened a [PR](https://github.com/PostHog/hubspot-plugin/pull/26) implementing this feature. just waiting for review. @marcushyett-ph can you provide any update?

**Comment by webbdays** [comment]
Any progress?

**Comment by Jaspreet-singh-1032** [comment]
Hello @webbdays,
I am no more working on this issue. You may go ahead and work on it if you want,
thanks.

**Comment by webbdays** [comment]
I will start working on this.

**Comment by JoseCToscano** [comment]
Hello there @marcushyett-ph! I would like to take on the issue and be assigned if it is still open.
@webbdays Do you have any updates or could I give it a try?

**Comment by webbdays** [comment]
@JoseCToscano 
I am not on it now.
You can work on it.

**Comment by joethreepwood** [comment]
Unfortunately this bounty programme was closed mid-last year and this issue wasn't updated. We still welcome submissions of new apps and you're welcome to work on this plugins, but we're no longer offering a bounty as an incentive. Apologies for the confusion.
