### ISSUE TITLE
Twilio SMS Plugin Spec

### ISSUE THREAD

**Issue by marcushyett-ph** [PostHog/posthog#8439]
**⚠️This is part of our plugin bounty if you intend to work on this issue please [read this issue](https://github.com/PostHog/posthog/issues/8437) first⚠️**

## Background

Twilio is one of the best ways of automating telecoms, when you need to know something immediately. When an important event occurs in your app, through a plugin our users could leverage twilio to send an SMS and alert a team member to take immediate action - no matter where they are (e.g. new order requested from a priority customer).

## Requirements

**Features**

The plugin should be capable of doing the following:

<table>
  <tr>
   <td><strong>Feature</strong>
   </td>
   <td><strong>Description</strong>
   </td>
  </tr>
  <tr>
   <td>Trigger SMS on user specified events or actions
   </td>
   <td>When a specified (in configuration) event or action occurs on PostHog the plugin should send an SMS to a specified number
   </td>
  </tr>
  <tr>
   <td>Configuration
   </td>
   <td>Users must be able to configure the plugin to use their API key and specify the events and actions which SMS are sent on, they should be able to specify one or more numbers to be contacted in the case of each event
   </td>
  </tr>
</table>

**Failure cases**

The plugin should account for these issues and not fail in the following ways:

<table>
  <tr>
   <td><strong>Problem</strong>
   </td>
   <td><strong>Description</strong>
   </td>
  </tr>
  <tr>
   <td>Sending too many messages
   </td>
   <td>Since SMS messages are not free we should ensure that we limit the number of messages we send on the same topic to the same person in a set period (this could be configurable)
   </td>
  </tr>
</table>

## Reference Information

* The relevant API documentation can be found here: 
    * [https://www.twilio.com/docs/usage/api](https://www.twilio.com/docs/usage/api)
* You can set up a free account here: https://www.twilio.com/try-twilio
* The following plugins provide some similar patterns which can be used as inspiration to to build this plugin:
    * [https://github.com/PostHog/hubspot-plugin/blob/main/index.js](https://github.com/PostHog/hubspot-plugin/blob/main/index.js)

## Getting Started

To start building a plugin:

* Comment on this issue so everyone knows you're picking it up and assign it to yourself
* Join our #contributing channel [on slack](https://posthog.com/slack) and let us know you're working on this task
* If you require we can provide you with login credentials to a development PostHog cluster where you can build and test your plugins, you could also run PostHog locally if you prefer to develop there
* Read through our developer reference for plugins: [https://posthog.com/docs/plugins/build/reference](https://posthog.com/docs/plugins/build/reference) and start building
* Let us know on [slack](https://posthog.com/slack) in the #contributing channel if you need any help or further information

## Getting it Shipped

* Create a public MIT Licensed repo on github, add all of your code and create a readme that explains the plugin
* Once you're done, reach out to the Posthog team in the #contributing channel and we'll take a look
* If your plugin works as expected, we’ll send you the bounty and get it live in our integrations catalog
* If you decide not to work on this after starting or don't make any progress in a week, please un-assign it so someone else can take it on

**Comment by merrcury** [comment]
@marcushyett-ph me and @samcaspus  would like to explore/work on this shall we pick it up

**Comment by marcushyett-ph** [comment]
Awesome! please assign to yourself and go ahead

**Comment by samcaspus** [comment]
@marcushyett-ph do review this repository as well https://github.com/merrcury/posthog-twilio-plugin 🚀 🚀 🚀

**Comment by marcushyett-ph** [comment]
@samcaspus Awesome, can you send a video in the contributing channel and we'll get one of the team to review the code too.

**Comment by merrcury** [comment]
Hey, @marcushyett-ph Code is approved by Yakko. Here is the PR -> https://github.com/merrcury/posthog-twilio-plugin/pull/3

We can proceed with formalities.

**Comment by merrcury** [comment]
Hey @marcushyett-ph, Can we close this ticket?
