### ISSUE TITLE
Zendesk Import / Export Plugin Spec

### ISSUE THREAD

**Issue by marcushyett-ph** [PostHog/posthog#8440]
**⚠️This is part of our plugin bounty if you intend to work on this issue please [read this issue](https://github.com/PostHog/posthog/issues/8437) first⚠️**

## Background

Zendesk is one of the top customer service tools in the world, enabling companies to speak with their customers and resolve issues. Integrating PostHog with Zendesk creates two powerful opportunities:

* Importing support ticket information into PostHog, so PostHog users can augment their analytics of product usage with information about support tickets filed, to help understand customer problems better
* Teams using Zendesk can respond to customer support requests much more effectively with data about their usage of the product available on the customer profile

## Requirements

**Features**

The plugin should be capable of doing the following:

<table>
  <tr>
   <td><strong>Feature</strong>
   </td>
   <td><strong>Description</strong>
   </td>
  </tr>
  <tr>
   <td>Import new and historic ticket events to PostHog
   </td>
   <td>Create events in PostHog for new tickets created in Zendesk, linking the ticket to existing users if they exist or creating new users in PostHog if not. Tickets should include at least status, priority, subject and type
   </td>
  </tr>
  <tr>
   <td>Export usage data to user profiles
   </td>
   <td>As new events are ingested Update the attributes of the user profile on Zendesk (if it exists) with the last time when specific events occurred (specified in configuration) (e.g. last_logged_in: “7 June 2021 10:00AM UTC”) 
   </td>
  </tr>
  <tr>
   <td>Configuration
   </td>
   <td>Users must be able to configure the plugin to use their API key and select the events they would like to track usage of on the user profiles in zendesk
   </td>
  </tr>
</table>

**Failure cases**

The plugin should account for these issues and not fail in the following ways:

<table>
  <tr>
   <td><strong>Problem</strong>
   </td>
   <td><strong>Description</strong>
   </td>
  </tr>
  <tr>
   <td>Duplicate ticket events
   </td>
   <td>The same events should not be imported multiple times
   </td>
  </tr>
  <tr>
   <td>Timestamps 
   </td>
   <td>The ticket events should be attributed to when they took place and not the time they were imported to PostHog
   </td>
  </tr>
  <tr>
   <td>Missing data
   </td>
   <td>If the API fails to return data, we should try again to capture the missing data
   </td>
  </tr>
</table>

## Reference Information

* The relevant API documentation for can be found here: 
    * Import Tickets: [https://developer.zendesk.com/api-reference/ticketing/tickets/tickets/](https://developer.zendesk.com/api-reference/ticketing/tickets/tickets/)
    * Export Usage data to user profile:
        * [https://developer.zendesk.com/api-reference/custom-data/profiles_api/profiles_api/#create-or-update-profile-by-identifier](https://developer.zendesk.com/api-reference/custom-data/profiles_api/profiles_api/#create-or-update-profile-by-identifier)
* You can set up a free trial at: [https://www.zendesk.com/register/#step-1](https://www.zendesk.com/register/#step-1)
* The following plugins provide some similar patterns which can be used as inspiration to to build this plugin:
    * [https://github.com/PostHog/stripe-plugin](https://github.com/PostHog/stripe-plugin)
    * [https://github.com/PostHog/github-star-sync-plugin/blob/main/index.js](https://github.com/PostHog/github-star-sync-plugin/blob/main/index.js)
    * [https://github.com/PostHog/twitter-followers-plugin/blob/main/index.js](https://github.com/PostHog/twitter-followers-plugin/blob/main/index.js)
    * [https://github.com/PostHog/redshift-plugin](https://github.com/PostHog/redshift-plugin)

## Getting Started

To start building a plugin:

* Comment on this issue so everyone knows you're picking it up and assign it to yourself
* Join our #contributing channel [on slack](https://posthog.com/slack) and let us know you're working on this task
* If you require we can provide you with login credentials to a development PostHog cluster where you can build and test your plugins, you could also run PostHog locally if you prefer to develop there
* Read through our developer reference for plugins: [https://posthog.com/docs/plugins/build/reference](https://posthog.com/docs/plugins/build/reference) and start building
* Let us know on [slack](https://posthog.com/slack) in the #contributing channel if you need any help or further information

## Getting it Shipped

* Create a public MIT Licensed repo on github, add all of your code and create a readme that explains the plugin
* Once you're done, reach out to the Posthog team in the #contributing channel and we'll take a look
* If your plugin works as expected, we’ll send you the bounty and get it live in our integrations catalog
* If you decide not to work on this after starting or don't make any progress in a week, please un-assign it so someone else can take it on

**Comment by samcaspus** [comment]
@marcushyett-ph  me and @merrcury would like to explore / work on this shall we pick it up

**Comment by marcushyett-ph** [comment]
Awesome @samcaspus I've assigned this ticket to you (I couldn't find @merrcury), please reach out in the #contributing channel in our slack if you have any further questions?

**Comment by samcaspus** [comment]
Hey @marcushyett-ph  this task is almost done while doing the ```Export usage data to user profiles``` part we noticed that the parameter is read only for last_logged_in hence that cannot be modified for now we have tried by changing the users actual name (Which can be modified as per requirement). 

some context is added to slack as well https://posthogusers.slack.com/archives/C019E06QDG8/p1644598649065019

Would like to understand if you have any thoughts on that.

**Comment by marcushyett-ph** [comment]
Awesome - glad you're almost done.

Responded in slack, but for the benefit of others. It's a coincidence that there's a field with a similar name "Last_login_at". You can use user-fields to store arbitrary data: https://developer.zendesk.com/api-reference/ticketing/users/users/#user-fields.

To be clearer on the expected behavior:

Say my product has 3 different types of events we track:
* Login
* Add to Cart
* Checkout

I would like to add to the user-fields on Zendesk the last time (a specified subset) of these events occured. If I configure Add-to-cart and checkout to be updated. I would expect my zendesk user profiles to have something like this sent (if the user triggered these events):

```user data: {"Add to Cart": "%datetime last occured%", "Checkout:"%datetime last occured%"}```

**Comment by samcaspus** [comment]
Hey @marcushyett-ph ,

Here is the code 
https://github.com/samcaspus/posthog-zendesk-plugin

let us know if you would want us to present the same 

CC @merrcury
