### ISSUE TITLE
Data Bricks Export Plugin Spec

### ISSUE THREAD

**Issue by marcushyett-ph** [PostHog/posthog#8441]
**⚠️This is part of our plugin bounty if you intend to work on this issue please [read this issue](https://github.com/PostHog/posthog/issues/8437) first⚠️**

## Background

Many of our customers use Data Bricks and other Data Warehouses to perform deeper analytics and combine together multiple data sources from outside of their product data. We currently have export plugins for [Snowflake](https://github.com/PostHog/snowflake-export-plugin), [BigQuery](https://github.com/PostHog/bigquery-plugin) and [Redshift](https://github.com/PostHog/redshift-plugin). Data Bricks is one of the most popular Data Warehouses.

## Requirements

**Features**

The plugin should be capable of doing the following:

<table>
  <tr>
   <td><strong>Feature</strong>
   </td>
   <td><strong>Description</strong>
   </td>
  </tr>
  <tr>
   <td>Export new events and actions
   </td>
   <td>When new events and actions occur in PostHog export them to a single table in Data Bricks
   </td>
  </tr>
  <tr>
   <td>Event & action details
   </td>
   <td>The events must include: all properties
   </td>
  </tr>
  <tr>
   <td>Configuration
   </td>
   <td>Users must be able to configure the plugin to use their authentication key, database and table names and other necessary configuration for operation
   </td>
  </tr>
</table>

**Failure cases**

The plugin should account for these issues and not fail in the following ways:

<table>
  <tr>
   <td><strong>Problem</strong>
   </td>
   <td><strong>Description</strong>
   </td>
  </tr>
  <tr>
   <td>Missing data
   </td>
   <td>If we fail to send data to databricks for some reason we should try again to export the missing data
   </td>
  </tr>
</table>

## Reference Information

* The relevant documentation for can be found here: 
    * [https://docs.databricks.com/data/data.html](https://docs.databricks.com/data/data.html)
* You can set up a free trial here: [https://databricks.com/try-databricks](https://databricks.com/try-databricks)
* The following plugins provide some similar patterns which can be used as inspiration to to build this plugin: [Snowflake](https://github.com/PostHog/snowflake-export-plugin), [BigQuery](https://github.com/PostHog/bigquery-plugin) and [Redshift](https://github.com/PostHog/redshift-plugin)

## Getting Started

To start building a plugin:

* Comment on this issue so everyone knows you're picking it up and assign it to yourself
* Join our #contributing channel [on slack](https://posthog.com/slack) and let us know you're working on this task
* If you require we can provide you with login credentials to a development PostHog cluster where you can build and test your plugins, you could also run PostHog locally if you prefer to develop there
* Read through our developer reference for plugins: [https://posthog.com/docs/plugins/build/reference](https://posthog.com/docs/plugins/build/reference) and start building
* Let us know on [slack](https://posthog.com/slack) in the #contributing channel if you need any help or further information

## Getting it Shipped

* Create a public MIT Licensed repo on github, add all of your code and create a readme that explains the plugin
* Once you're done, reach out to the Posthog team in the #contributing channel and we'll take a look
* If your plugin works as expected, we’ll send you the bounty and get it live in our integrations catalog
* If you decide not to work on this after starting or don't make any progress in a week, please un-assign it so someone else can take it on

**Comment by marcushyett-ph** [comment]
@denim2x welcome!

**Comment by ghost** [comment]
@marcushyett-ph I'd like to be assigned

**Comment by ghost** [comment]
@marcushyett-ph thanks

**Comment by samcaspus** [comment]
Hey @denim2x just wanted to check with you if you are still working on this issue if not me and @merrcury were wondering if we could pick it up 😁😁 CC @marcushyett-ph

**Comment by marcushyett-ph** [comment]
Hey @denim2x, since you've not shared any progress in the last week and @merrcury and @samcaspus are keen to give this a go, I'm going to let them assign themselves and get started. Please let us know ASAP if you're almost ready to ship something though - so they don't go too far?

**Comment by ghost** [comment]
<details>
<summary>deleted by author</summary>
i would like to take on this bounty puck - implement Data Bricks export plugin
if this task is available at the moment - please assign to me
forked [Snowflake](https://github.com/PostHog/snowflake-export-plugin) plugin to not go astray
i will comment here once job's done</details>

**Comment by marcushyett-ph** [comment]
@Sergei-Udris this is already in progress - almost complete with @samcaspus

**Comment by ghost** [comment]
<details>
<summary>deleted by author</summary>
> i would like to take on this bounty puck - implement Data Bricks export plugin if this task is available at the moment - please assign to me forked [Snowflake](https://github.com/PostHog/snowflake-export-plugin) plugin to not go astray i will comment here once job's done

no, i'm wrong regardless
like in Game Changers - even for bounties gonna go whole foods plant based vegan - clojure, no clojudcript (as i intended fof plugin)
desktop is the way of Mandalore - like as if Jesus organized a prison break from browser

anyway  issue wasn't assigned to me and is almost done, just wanted to rectify my rushed decision to ask for assignment

:Acaster luckily, i'm a comic, i'm allowed to look silly
</details>

**Comment by merrcury** [comment]
Hey @marcushyett-ph, Can we close this ticket?

**Comment by marcushyett-ph** [comment]
Yep
