### ISSUE TITLE
Shopify Order Import Plugin Spec

### ISSUE THREAD

**Issue by marcushyett-ph** [PostHog/posthog#8442]
**⚠️This is part of our plugin bounty if you intend to work on this issue please [read this issue](https://github.com/PostHog/posthog/issues/8437) first⚠️**

## Background

Many of our customers use Shopify and other ecommerce platforms to sell their products, to augment the data that can be [captured on the front-end store](https://posthog.com/docs/integrate/third-party/shopify), we also need to bring in order data to understand who’s successfully purchasing items.

## Requirements

**Features**

The plugin should be capable of doing the following:

<table>
  <tr>
   <td><strong>Feature</strong>
   </td>
   <td><strong>Description</strong>
   </td>
  </tr>
  <tr>
   <td>Import historical orders
   </td>
   <td>Create events in Posthog for orders that happened in the past on Shopify
   </td>
  </tr>
  <tr>
   <td>Sync new orders
   </td>
   <td>When new Orders are received, add them as events in Posthog
   </td>
  </tr>
  <tr>
   <td>Event details
   </td>
   <td>The events must include: order_number, transaction_amount, currency, status, order_status_url, financial_status and description as a minimum but may include more detail where available
   </td>
  </tr>
  <tr>
   <td>Person details
   </td>
   <td>The Order events must be associated with an existing person if they exist or if not create a new person
   </td>
  </tr>
  <tr>
   <td>Configuration
   </td>
   <td>Users must be able to configure the plugin to use their API key and fetch Order data from a shopify store they own
   </td>
  </tr>
</table>

**Failure cases**

The plugin should account for these issues and not fail in the following ways:

<table>
  <tr>
   <td><strong>Problem</strong>
   </td>
   <td><strong>Description</strong>
   </td>
  </tr>
  <tr>
   <td>Duplicate charge events
   </td>
   <td>The same events should not be imported multiple times
   </td>
  </tr>
  <tr>
   <td>Timestamps 
   </td>
   <td>The Order events should be attributed to when they took place and not the time they were imported to PostHog
   </td>
  </tr>
  <tr>
   <td>Missing charge events
   </td>
   <td>If the API fails to return data, we should try again to capture the missing events
   </td>
  </tr>
</table>

## Reference Information

* The relevant API documentation for shopify can be found here: 
    * [https://shopify.dev/api/admin-rest/2022-01/resources/event#top](https://shopify.dev/api/admin-rest/2022-01/resources/event#top)
    * [https://shopify.dev/api/admin-rest/2022-01/resources/order#[get]/admin/api/2022-01/orders.json?status=any](https://shopify.dev/api/admin-rest/2022-01/resources/order#[get]/admin/api/2022-01/orders.json?status=any)
* You can set up a developer account [https://shopify.dev/](https://shopify.dev/)
* The following plugins provide some similar patterns which can be used as inspiration to to build this plugin:
    * [https://github.com/PostHog/stripe-plugin](https://github.com/PostHog/stripe-plugin)
    * [https://github.com/PostHog/github-star-sync-plugin/blob/main/index.js](https://github.com/PostHog/github-star-sync-plugin/blob/main/index.js)
    * [https://github.com/PostHog/twitter-followers-plugin/blob/main/index.js](https://github.com/PostHog/twitter-followers-plugin/blob/main/index.js)

## Getting Started

To start building a plugin:

* Comment on this issue so everyone knows you're picking it up and assign it to yourself
* Join our #contributing channel [on slack](https://posthog.com/slack) and let us know you're working on this task
* If you require we can provide you with login credentials to a development PostHog cluster where you can build and test your plugins, you could also run PostHog locally if you prefer to develop there
* Read through our developer reference for plugins: [https://posthog.com/docs/plugins/build/reference](https://posthog.com/docs/plugins/build/reference) and start building
* Let us know on [slack](https://posthog.com/slack) in the #contributing channel if you need any help or further information

## Getting it Shipped

* Create a public MIT Licensed repo on github, add all of your code and create a readme that explains the plugin
* Once you're done, reach out to the Posthog team in the #contributing channel and we'll take a look
* If your plugin works as expected, we’ll send you the bounty and get it live in our integrations catalog
* If you decide not to work on this after starting or don't make any progress in a week, please un-assign it so someone else can take it on

**Comment by sreeo** [comment]
I'd like to work on this.

**Comment by marcushyett-ph** [comment]
Sure, feel free to assign this ticket to yourself and get started.

**Comment by sreeo** [comment]
Hey, I have finished work with the plugin. https://github.com/sreeo/posthog-shopify-sync-plugin
Also, `description` and `status` attributes were not present in the order response from shopify. So I haven't added them.

**Comment by corywatilo** [comment]
Any updates on if we can get this added to the ~plugin~ app library?

**Comment by marcushyett-ph** [comment]
I think we've sorted out all the paperwork now so its on me, to transfer the repo to our ownership. @sreeo would you be able to transfer the repo to the PostHog organization?

**Comment by sreeo** [comment]
<img width="1011" alt="image" src="https://user-images.githubusercontent.com/4143788/172998324-4b6c35fc-9879-4cfe-ab72-1170a6e0fcb5.png">
Trying to do this. This is the error I get.

**Comment by marcushyett-ph** [comment]
Hmmm can you try transferring it to me? @marcushyett-ph and I'll move it to PostHog after?

**Comment by sreeo** [comment]
Hey, I have transferred it to you. You'd received a request.

**Comment by marcushyett-ph** [comment]
Perfect thanks done!
