### ISSUE TITLE
Idea: Shuffle Button for Insights

### ISSUE THREAD

**Issue by joethreepwood** [PostHog/posthog#8443]
## Is your feature request related to a problem?

[Context for this issue. ](https://github.com/PostHog/product-internal/pull/261#discussion_r799210099)

This idea is one I've proposed in hackathons a few times, usually as 'a magic 8-ball for insights', 'a shuffle button for insights' or '[HogBot](https://twitter.com/TheHogBot)'.

The idea is to encourage users to be curious about their data and give them a way to explore it in an unstructured way, with the goal of discovering something unexpected. 

PostHog is very good at giving answers to questions you know to ask, but less good at encouraging you to ask new questions. We have no real onboarding or tutorial process to show users what is possible with their data and [users view existing dashboards far more often than analysing insights](https://app.posthog.com/insights/nIMfZ6b9#filters=%7B%22insight%22%3A%22TRENDS%22%2C%22interval%22%3A%22day%22%2C%22display%22%3A%22ActionsLineGraph%22%2C%22actions%22%3A%5B%7B%22id%22%3A%2210706%22%2C%22name%22%3A%22Insight%20Analyzed%20(Trend%2C%20Funnel%20%26%20Path)%22%2C%22type%22%3A%22actions%22%2C%22order%22%3A0%2C%22math%22%3A%22dau%22%7D%5D%2C%22events%22%3A%5B%7B%22id%22%3A%22viewed%20dashboard%22%2C%22type%22%3A%22events%22%2C%22order%22%3A1%2C%22name%22%3A%22viewed%20dashboard%22%2C%22math%22%3A%22dau%22%7D%5D%2C%22properties%22%3A%5B%5D%2C%22filter_test_accounts%22%3Atrue%2C%22new_entity%22%3A%5B%5D%2C%22date_from%22%3A%22-30d%22%2C%22date_to%22%3Anull%7D). We want users to get more value from the incredibly powerful tools which are available to them. 

## Describe the solution you'd like

A shuffle button would provide an interactive means of exploration that could lead to surprising insights and offer less-experienced users a platform to delve farther. 

It would work so that, when clicked, the shuffle button would suggest a random insight generated from a list of the available tools and events/actions in a users' instance. Users can then choose to, with another button press, create this insight and begin playing with it. 

Maybe it could look like a hedgehog too, just to give it some personality?

HogBot is already demonstrating how these suggestions could look, giving [several](https://twitter.com/TheHogBot/status/1489254649412476929) [worthwhile](https://twitter.com/TheHogBot/status/1489492170239135746) [prompts](https://twitter.com/TheHogBot/status/1489021802491703300) [amid](https://twitter.com/TheHogBot/status/1489006482976743427) [the](https://twitter.com/TheHogBot/status/1488930806777016322) [noise](https://twitter.com/TheHogBot/status/1488855273947074565). It can also be used as a tool to [reinforce good behaviours](https://twitter.com/TheHogBot/status/1489565051392434177) and [best practices](https://twitter.com/TheHogBot/status/1489551414829355009). 

This tool would create a lot of noise for users, but I believe this would fit with their expectations -- if you shuffle an album you don't always expect to land on your ideal song. But when you do? Or when you discover a new song or band for the first time? Then it's worthwhile.

## Describe alternatives you've considered

There's been various ways discussed that this could work. It could not generate the insight. It could take users directly to the insight. It could exist as a tool outside the product. Etc.

**Comment by joethreepwood** [comment]
You are goddamn right we're keeping this open. Shufflehog never dies. Shufflehog is forever.

**Comment by Twixes** [comment]
ShuffleHog: merely 2x to PostHog's valuation
AIHog: almost the same thing, but 10x to PostHog's valuation
