### ISSUE TITLE
How do 'any order' funnels work with time-to-convert and conversion-trends

### ISSUE THREAD

**Issue by rcmarron** [PostHog/posthog#8448]
## Bug description

In funnels, we support any order funnels. This means if a funnel has steps A, B, and C, and a user completes C -> A, they would show in the chart as completing step 1 + 2 and dropping off at step 3.

It's not clear how this functionality translates to time-to-convert and funnel trend calculations. Both of these calculations apply for inter-step ranges. For example, a funnel trend calculation might ask "Show me how conversion over time changes from step 1 to step 2".

In this case, it's not clear what step 1 and step 2 mean. Are these the steps as the user has defined them (in this example A and B)? Or are these the first two steps that the specific user completed (in this example C and A)? 

Also, how does this work for a time-to-convert calculation if a user could complete an any order filter in multiple ways? For example, if the user goes C -> A -> C -> B, which time gap is the time to convert for the first step, C->A or A->C? Do we always take the quickest path? Or the first path? Is it the quickest/first path for just that step or the entire funnel? For example if the time to convert for step 1 to step 2 is C->A, that will make the time to convert for step 2 to step 3 longer as it would be A->B instead of C->B.

Overall, it seems like there's a level of complexity in this feature that makes it really non-trivial to use and understand. I wonder if it makes sense to remove both time-to-convert and funnel-trends for unordered funnels?

Note: I came across these questions as I was trying to link recordings to the unordered funnels, and hit the same issues described above, so what ever decision we make here will also apply there.

cc @EDsCODE @neilkakkar @paolodamico

**Comment by neilkakkar** [comment]
> Or are these the first two steps that the specific user completed (in this example C and A)?
This. For each user, time to convert is time between their respective first & second step.

We should definitely make this clearer on the UI.

> which time gap is the time to convert for the first step, C->A or A->C?

Average of both

> Do we always take the quickest path? Or the first path? Is it the quickest/first path for just that step or the entire funnel?

We aggregate all possible paths together.

---

Just wanted to dish this out quickly, will have a look tomorrow morning, but I don't think this is really used that much at all (even unordered funnels themselves are a smalll minority), so might be okay skipping recordings as well.
