### ISSUE TITLE
Idea: Internal Users Filter

### ISSUE THREAD

**Issue by joethreepwood** [PostHog/posthog#8461]
## Is your feature request related to a problem?

The ability to filter internal users is something which PostHog can do but which isn't currently mentioned in the docs and which has some friction around it. Comments about this came up in a recent case study call, but have been reported to come up regularly in other areas too. 

One other area of friction which was reported in the case study call was regarding the internal users filter toggle itself:

"_In general, it's really easy to use the insights to collect the data. I think the only struggle that I have with the insights is [that it is hard to separate the data]. We have so many people in the business using our platform to showcase, especially our sales team. Sometimes it's really hard to separate those data from the data of the real users. I try to filter it out and it gets mixed up because we have so many different product teams. If one person adds the filter, another one turns it off because they don't know what it is. I can't control it._"

## Describe the solution you'd like

Firstly, I'll write something for the docs/tutorial to help to help increase visibility of the internal filter and how it works. 

For the second part, about how to protect the filter toggle, it feels like we need someway to explain to users how internal users are decided so that they understand better what the toggle does?

## Describe alternatives you've considered

🤷 

## Additional context

Improving the way internal user filters work feels like it is rising in importance as we focus on Nailing Enterprise, since larger customers have more internal users and therefore their data may be more volatile. 

Tagging @paolodamico too in light of https://github.com/PostHog/product-internal/pull/261

**Comment by clarkus** [comment]
We have a project-level setting that explains this now. there could be an opportunity to improve this documentation, and make the cross-linking of this information more obvious in the filter itself. 

> Filter out internal and test users
> Increase the quality of your analytics results by filtering out events from internal sources, such as team members, test accounts, or development environments.
> 
> Events will still be ingested and saved (and will count towards any totals), they will however be excluded from consideration on any queries where the "Filter out internal and test users" toggle is set.
> 
> Example filters to use below: email ∌ yourcompany.com to exclude all events from your company's team members, or Host ∌ localhost to exclude all events from local development environments.
> 
> The filters you apply here are added as extra filters when the toggle is switched on. So, if you apply a Cohort filter, it means toggling filtering on will match only this specific cohort.

**Comment by joethreepwood** [comment]
Created https://github.com/PostHog/posthog.com/pull/2948 to address some of this
