### ISSUE TITLE
"This Month" Insight date range has disappeared

### ISSUE THREAD

**Issue by j-ochs** [PostHog/posthog#8469]
## Bug description

I have an existing insight which tracks unique user signups, counted by the "This Month" date range (see screenshot):

>>> ![existing-with-mtd](https://user-images.githubusercontent.com/11338019/152847846-d75e4c80-8a52-4206-82c1-1f8ccb523082.png)

However, if I attempt to create a new insight, even one that tracks the exact same action and properties, the "This Month" date range option is no longer available (see screenshot):

>>> ![new-without-mtd](https://user-images.githubusercontent.com/11338019/152847873-2e068db2-12e0-47b5-a608-ac4c599c5bd8.png)

I do not understand why the "This Month" date range would suddenly be unavailable. It may be possible that a change in our project's setting has caused this, though if so I do not understand why this would be the case. Any advice is greatly appreciated - thank you!

## Expected behavior
* The "This Month" date range is an available option for new insights.

## How to reproduce

1. Create a new insight

## Environment

- [ ] PostHog Cloud
- [ ] self-hosted PostHog (ClickHouse-based), version/commit: _please provide_
- [x] self-hosted PostHog (Postgres-based, legacy), version/commit: `1.30.0`

**Comment by Twixes** [comment]
Hey! You should instead use "Last 30 days".
