### ISSUE TITLE
Bug: Wrong insight type loading when editing from dashboard

### ISSUE THREAD

**Issue by joethreepwood** [PostHog/posthog#8478]
## Bug description

Spotted this for the first time on a call with @andyvan-ph, but he says it's happened a few times to him before so it's definitely replicable. 

If you start from a dashboard with multiple types of insight and click 'Edit' on one type (e.g. Trends), then click Back to return to the dashboard and click 'Edit' on another type (e.g. Paths) then PostHog attempts to load a Trends insight again. I _think_ it's trying and failing to load it with the same information, because the insight will never successfully load if left -- but if you click to the correct type of insight, suddenly it loads instantly. 

This is a little hard to explain, [so here's a video.](https://drive.google.com/file/d/18xpW3VMQoNtXb_66eK61fUA3L7HcLtvl/view?usp=sharing)

## Expected behavior

I'd expect it to load the correct insight. 

## How to reproduce

1. Open a dashboard. Here's what I used. 
2. Click 'Edit' on the Pageviews trends insight. Then click back to return to the dashboard. 
3. Click 'Edit' on the Paths insight. 

## Environment

- [x] PostHog Cloud
- [ ] self-hosted PostHog (ClickHouse-based), version/commit: _please provide_
- [ ] self-hosted PostHog (Postgres-based, legacy), version/commit: _please provide_

## Additional context

Taggin @andyvan-ph who can provide more examples and context, if needed.

**Comment by marcushyett-ph** [comment]
Pinging @Twixes as secondary this week.

I keep encountering this bug and it's quite disruptive. Happy to provide any more context or repro instructions.

**Comment by Twixes** [comment]
👁️ 👄 👁️
Created a PR to fix this #8613.

**Comment by marcushyett-ph** [comment]
Amazing thank you!

**Comment by Twixes** [comment]
Unfortunately gotta reopen this as both attempted fixes (#8613 and #8633) are facing reliability issues.

**Comment by Twixes** [comment]
Related: #8801

**Comment by mariusandra** [comment]
There's a different error now. The page doesn't want to open in the edit state:

https://user-images.githubusercontent.com/53387/157643812-dcbcd57a-9296-4146-bf43-b6008e7dd3c6.gif

... and then it doesn't want to open in the view state.

@Twixes something for the insight quality sprint board?

**Comment by Twixes** [comment]
Looks like this has been solved by #8967.
