### ISSUE TITLE
Put paths date filter in URL

### ISSUE THREAD

**Issue by mariusandra** [PostHog/posthog#849]
**Describe the bug**

When changing the date range in /paths, I expect clicking back/forward to go to the previous/next dates in my selection history.

![screencast 2020-05-26 14-48-43](https://user-images.githubusercontent.com/53387/82902681-1ec31680-9f60-11ea-8c94-238fbc02b146.gif)

When making the screenshots for #848 I sometimes accidentally clicked "back" expecting to go to what I had previously selected in the filter, only to lose all state and have to restart... and remember what were the days I was at.

**Comment by Twixes** [comment]
This works now.
