### ISSUE TITLE
Onboarding screen looks like it has a bit of dirt on it

### ISSUE THREAD

**Issue by rcmarron** [PostHog/posthog#8502]
## Bug description

On the "Lets get started..." page, we have a lovely picture of a hedge hog, but there's a shadow behind it that looks kind of like dirt. I just found myself wiping my screen. The file with the shadow is `surprised-hog.png` [here](https://github.com/PostHog/posthog/blob/852c68e8666255fa15205b84a88113867d71247b/frontend/public/surprised-hog.png)

![image](https://user-images.githubusercontent.com/4813045/153059069-c52d7e3d-6626-420d-88e4-0fca29cec594.png)

## Expected behavior

There to be a white background

## How to reproduce

1.
2.
3.

## Environment

- [ ] PostHog Cloud
- [ ] self-hosted PostHog (ClickHouse-based), version/commit: _please provide_
- [ ] self-hosted PostHog (Postgres-based, legacy), version/commit: _please provide_

**Comment by rcmarron** [comment]
cc @lottiecoxon mind helping remove the shadow here (I don't have an image editor, otherwise, I'd just do it)

**Comment by neilkakkar** [comment]
.. But, but, but, it's the natural habitat!

**Comment by rcmarron** [comment]
> .. But, but, but, it's the natural habitat!

😂

**Comment by jamesefhawkins** [comment]
<img width="290" alt="Screenshot 2022-02-09 at 15 27 14" src="https://user-images.githubusercontent.com/47497682/153232944-1ff4055b-2856-45d7-80bd-98e4ac7e415a.png">

**Comment by clarkus** [comment]
I grabbed a new copy of the image, cropped out the habitat, and optimized it for the loading the png in a browser.

![hedgehogpreflight](https://user-images.githubusercontent.com/254612/153237518-93e738fa-4d20-4bc3-8a98-ac174ee5d9ca.png)

**Comment by corywatilo** [comment]
something something housekeeping joke
