### ISSUE TITLE
Export Insights

### ISSUE THREAD

**Issue by inbreaks** [PostHog/posthog#8513]
## Is your feature request related to a problem?

I want to export the graphs from Insights into CSV

## Describe the solution you'd like

Adding export CVS to charts in Trends, Funnels, Retention, Stickiness, Lifecycle, I'm not sure if there is a common component that can be cost plus.

> can see Grafana how do you do something like this

## Describe alternatives you've considered

Manually pasting line by line

**Comment by inbreaks** [comment]
reference

https://help.gooddata.com/doc/enterprise/en/dashboards-and-insights/analytical-designer/export-and-embed-insights/export-insights

**Comment by timgl** [comment]
@inbreaks This exists for trends now

**Comment by inbreaks** [comment]
> @inbreaks This exists for trends now

Cheers, this is definitely a very useful feature.

**Comment by inbreaks** [comment]
I see the merge feature in #9024. It would be great if there was a common component like Grafana that could export CSV data for Trends, Funnels, Retention, Stickiness, Lifecycle.

**Comment by pauldambra** [comment]
You can now (on cloud) export all insights as CSVs. This will be in release 1.38 for self hosted

**Comment by charlescook-ph** [comment]
> You can now (on cloud) export all insights as CSVs. This will be in release 1.38 for self hosted

Not for for the Table chart type as far as I can see? (You need to switch to another chart type for the export option to show - obviously doable, but unintuitive?)

**Comment by charlescook-ph** [comment]
@thmsobrmlr

**Comment by pauldambra** [comment]
> Not for for the Table chart type as far as I can see? (You need to switch to another chart type for the export option to show - obviously doable, but unintuitive?)

This turns out to be UX feedback. 

When an insight is not a table. Then it has a details view below it which is a table. That view has an export button that only allows exporting as a CSV.

The entire insight has an export button in the kebab menu which allows exporting as a CSV or as an image.

----

That long of a description of a supposedly simple UI feature suggests it isn't actually simple when it really should be :)
