### ISSUE TITLE
Bug: Funnel insight not working L to R, but is working T to B

### ISSUE THREAD

**Issue by joethreepwood** [PostHog/posthog#8517]
## Bug description

[This insight](https://app.posthog.com/insights/aj2nqVpW/edit#filters=%7B%22insight%22%3A%22FUNNELS%22%2C%22date_from%22%3A%22-30d%22%2C%22actions%22%3A%5B%7B%22id%22%3A%222674%22%2C%22type%22%3A%22actions%22%2C%22order%22%3A1%2C%22name%22%3A%22User%20Signed%20Up%20(Comprehensive)%22%7D%5D%2C%22events%22%3A%5B%7B%22id%22%3A%22%24pageview%22%2C%22name%22%3A%22%24pageview%22%2C%22type%22%3A%22events%22%2C%22order%22%3A0%2C%22properties%22%3A%5B%7B%22key%22%3A%22%24current_url%22%2C%22value%22%3A%5B%22https%3A%2F%2Fposthog.com%2Fblog%2Fbest-open-source-analytics-tools%22%5D%2C%22operator%22%3A%22exact%22%2C%22type%22%3A%22event%22%7D%5D%7D%5D%2C%22display%22%3A%22FunnelViz%22%2C%22layout%22%3A%22horizontal%22%2C%22interval%22%3A%22day%22%2C%22properties%22%3A%5B%5D%2C%22filter_test_accounts%22%3Atrue%2C%22funnel_viz_type%22%3A%22steps%22%2C%22exclusions%22%3A%5B%5D%7D), which I was looking at with @marcushyett-ph and @andyvan-ph, doesn't work when viewed in a L to R visualization. It just displays a blank insight, with no first step of the funnel and no information visible. In top to bottom view, it displays fine. 

No error given, no timeout.  

## Expected behavior

I'd expect it to load correctly. 

## How to reproduce

1. [Load this insight. ](https://app.posthog.com/insights/aj2nqVpW/edit#filters=%7B%22insight%22%3A%22FUNNELS%22%2C%22date_from%22%3A%22-30d%22%2C%22actions%22%3A%5B%7B%22id%22%3A%222674%22%2C%22type%22%3A%22actions%22%2C%22order%22%3A1%2C%22name%22%3A%22User%20Signed%20Up%20(Comprehensive)%22%7D%5D%2C%22events%22%3A%5B%7B%22id%22%3A%22%24pageview%22%2C%22name%22%3A%22%24pageview%22%2C%22type%22%3A%22events%22%2C%22order%22%3A0%2C%22properties%22%3A%5B%7B%22key%22%3A%22%24current_url%22%2C%22value%22%3A%5B%22https%3A%2F%2Fposthog.com%2Fblog%2Fbest-open-source-analytics-tools%22%5D%2C%22operator%22%3A%22exact%22%2C%22type%22%3A%22event%22%7D%5D%7D%5D%2C%22display%22%3A%22FunnelViz%22%2C%22layout%22%3A%22horizontal%22%2C%22interval%22%3A%22day%22%2C%22properties%22%3A%5B%5D%2C%22filter_test_accounts%22%3Atrue%2C%22funnel_viz_type%22%3A%22steps%22%2C%22exclusions%22%3A%5B%5D%7D)
2. Compare the left-to-right and top-to-bottom visualization
3.

## Environment

- [x] PostHog Cloud
- [ ] self-hosted PostHog (ClickHouse-based), version/commit: _please provide_
- [ ] self-hosted PostHog (Postgres-based, legacy), version/commit: _please provide_

**Comment by neilkakkar** [comment]
The problem seems to be when any step has 0 users. Sounds like a regression - I'm sure this used to work earlier.

**Comment by pauldambra** [comment]
The beauty of not looking at bugs immediately is that we accidentally fix them

![2022-08-26 10 12 58](https://user-images.githubusercontent.com/984817/186870799-eb6d4fae-63dd-4203-b753-f439d45d29ce.gif)
