### ISSUE TITLE
Move GeoIP to fast-geoip

### ISSUE THREAD

**Issue by yakkomajuri** [PostHog/posthog#8538]
This is a @fuziontech suggestion that I took upon myself to write about.

James raised some concerns about plugin server network IO given we're communicating via TCP within the same process and has suggested we instead keep a copy of MMDB in each worker thread to avoid the overhead of communication.

This definitely will bring memory usage up. The MMDB database we use is slightly over 80mb, meaning we'd be using 80mb more memory per thread. On Cloud, this would equal 80*8=640mb more per plugin server tasks, which we can certainly handle. Self-hosted users might not have as much memory available, but with less memory one generally gets fewer cores as well, and thus fewer threads. An average self-hosted instance might then get an additional 320mb of memory or so per plugins pod.

The question here is then: is this worth it? And I'd like to toss this discussion up to @Twixes and @mariusandra who worked on this system in the first place.

Me and @mariusandra have also discussed what the future of the plugin server might look like, and it wouldn't be outrageous to consider that MMDB wouldn't be needed on all servers, if we do realize the vision of having the instances coordinate responsibilities amongst themselves, but that's a slightly more distant future.

Either way, for this discussion of having MMDB in each worker, I see the following:

**Pros**

- Removing the overhead of the TCP communication
- Faster lookups (even if marginally)
- ...

**Cons**

- Increased memory usage
- More setup necessary for each thread
- ...

**Comment by guidoiaquinti** [comment]
For more optimization ideas, take a look at https://github.com/onramper/fast-geoip

**Comment by mariusandra** [comment]
I think the actual bottleneck during Sunday's slowdown was simply that the main thread got CPU bound for some reason. This resulted in the geoip plugin suddenly taking a large amount of time, as it's running on the main thread and receiving requests from the worker threads through TCP.

As a quick fix, let's just make `createMmdbServer` run in a separate thread.

**Comment by yakkomajuri** [comment]
Just for the sake of discussion, let's put aside Sunday and quick fixes. I'm not suggesting here that this was the problem. 

Also @fuziontech has mentioned this in the past. 

Let's discuss this based on its merits. 

@guidoiaquinti has already provided an interesting alternative worth looking into.

**Comment by mariusandra** [comment]
Actually, looking at present metrics and taking the fast-geoip's `0.7ms` self-reported benchmarks as a guide, we will actually save time if we switch to it 👍 

![image](https://user-images.githubusercontent.com/53387/153423171-f23a01ba-b4c4-4876-8714-2e5de3d83289.png)

That's even better than offloading the load to a different thread.

During the outage due to the congestion it was as high as 30ms:

![image](https://user-images.githubusercontent.com/53387/153423633-a81d37a9-4397-433b-83cd-ff334a416a64.png)

**Comment by yakkomajuri** [comment]
Yup, I was thinking the same.

In fact, we get much worse timings too:

<img width="1381" alt="Screenshot 2022-02-10 at 14 34 43" src="https://user-images.githubusercontent.com/38760734/153430710-d27b64c0-8a21-49c8-8e7f-934b8c3f759f.png">

Although we time the whole operation, which contains some async ops in between, and if our suspicions about a clogged event loop are correct, these would affect the metrics too.

See e.g.

<img width="1371" alt="Screenshot 2022-02-10 at 14 40 26" src="https://user-images.githubusercontent.com/38760734/153430896-65b2dcc1-5c17-4a19-b149-edf13ce09e68.png">

**Comment by yakkomajuri** [comment]
Here's a pending question:

`fast-geoip` will not give us post code and continent name + code which MMDB gives us. This would be a breaking change and customers relying on historical data based on these properties would not have them. Depending on the differences in implementation we might also see different city names etc which would break historical data.

There are a few options here:

**1: Continue using MMDB but have each thread keep a copy of the DB**

Original suggestion on this issue, still stands.

**2: Move to fast-geoip**

This will be a breaking change, we'd need to consider it carefully and maybe do some research/talk to users before.

**3: Fetch MMDB at build time**

`fast-geoip` gave me an idea.

What they do is fetch the DB at build time and keep it in the package source code so they can read from the file using the filesystem APIs.

There's no reason we can't do the same for MMDB? 

Instead of runtime fetching like we currently do, we could fetch this at build time and then all threads can leverage the same db without all having to keep it in memory (they would ofc have a cache in memory, but that'd be a fraction of the db).

Thoughts on this approach? If we move to `fast-geoip` it will be doing this in the background _anyway_.

@mariusandra @guidoiaquinti

**Comment by guidoiaquinti** [comment]
> Instead of runtime fetching like we currently do, we could fetch this at build time and then all threads can leverage the same db without all having to keep it in memory (they would ofc have a cache in memory, but that'd be a fraction of the db).

I think it is a valid approach that we should try. Also if it is not going to give us a huge perf boost, I like that we will remove a core dependency step executed at runtime (by moving it at build time).

Other optimizations proposed in the `fast-geoip` repo looks good too

**Comment by mariusandra** [comment]
My vote still goes for option 4: move the current mmdb server into its own thread, keep the tcp communication. 

The last geoip slowdowns came from the fact that the already busy main thread was also responding to geoip requests over a TCP socket. If we just offload this to another thread, the slowdown will vanish and we'll still only have one copy of the data in memory.

Besides, `fast-geoip` works by seeking a file on disk, but our "disk" is a postgresql database, so we'll anyway need to keep it in memory somewhere, unless we dump it to a `/tmp/geoip.dat` file every time on boot.

**Comment by yakkomajuri** [comment]
> Besides, fast-geoip works by seeking a file on disk, but our "disk" is a postgresql database, so we'll anyway need to keep it in memory somewhere, unless we dump it to a /tmp/geoip.dat file every time on boot.

Yes, that's what I think we could do. Move the whole step to buildtime rather than runtime, keep the file on disk, and cache reads off of it. This way we'll keep a portion of the DB in the thread memory and the rest as a file on disk. No TCP needed, no need to keep all in memory, runtime setup is also mostly gone too.

**Comment by mariusandra** [comment]
While true, this also introduces some breaking changes and baggage:
- no automatic geoip updates
- custom path for docker containers (built images) and people running `yarn start`
- we can never be sure we can write to `/tmp` or where the code will run in the future (+1 deployment constraint)
- postcodes and other breaking changes
- all the code we need to write

Hence, I still vote for just adding a `new Thread(() => {})` around the existing code, not adding all those tradeoffs and calling it a day. Later we can add a "geoip turbo mode" that loads this same thing per thread, with clear documentation that reads "needs more memory".

**Comment by yakkomajuri** [comment]
And actually, this is incorrect:

> the already busy main thread was also responding to geoip requests over a TCP socket. 

I'm reasonably sure the busy ones were the workers who then couldn't process the network callbacks in time

**Comment by mariusandra** [comment]
... because atomics?

**Comment by yakkomajuri** [comment]
No, not because of atomics. See e.g. https://github.com/PostHog/posthog/pull/8578 - clicking "check for updates" would cause us to reload all VMs while a ton of events are coming in, jobs are running, and buffer flushes are happening. This caused everything to slow down across the board. But while that is fixed, busy workers can come about for various reasons (including atomics, now removed and in "prod testing" phase).

Anyway, I _actually_ don't feel very strongly here. But as the resident plugin server person, I end up being the one making the requests of others a reality (can you add this API, can you fix this).

Thus, I'll loop in @fuziontech again because he's really against the TCP communication.

I'd love to have a stronger opinion here, but there are already too many things for me to think about. In this particular case, I'm just a vessel for the implementation.

**Comment by mariusandra** [comment]
Ah, I misread the wish to get rid of TCP as a suggestion. If that's what we're going for, then I'm going to add one more suggestion: **5. SharedArrayBuffer**

Can we find a way to load the data in the main thread, and let all worker threads use that same physical heap of memory?

Looking at [this line here](https://github.com/runk/mmdb-lib/blob/master/src/index.ts#L36), perhaps all we need to do is to pass a `SharedArrayBuffer`? Piscina has something called [`transferList`](https://github.com/piscinajs/piscina#method-runtasktask-transferlist-filename-abortsignal) that seems to be for this. 

This could work, but I'm not sure how deep the rabbit hole goes.

**Comment by yakkomajuri** [comment]
@Twixes did apparently try that:

> Initially I looked into sharing the mmdb (ReaderModel instance) object between threads somehow. Turns out that some raw data can be shared nicely with SharedArrayBuffer, but that's way too low-level to help here, database reader instantiation would nullify this optimization completely.

https://github.com/PostHog/plugin-server/pull/304

**Comment by mariusandra** [comment]
Ah yes, this `mmdb-lib` that I'm referring to is at the end of a very long trail.
- [We use](https://github.com/posthog/posthog/blob/master/plugin-server/package.json#L57) `@maxmind/geoip2-node` 
- [Which uses](https://github.com/maxmind/GeoIP2-node/blob/main/package.json#L77) `maxmind`
- [Which uses](https://github.com/runk/node-maxmind/blob/master/package.json#L29) `mmdb-lib`

... which might require even more rework, if any of the packages between indeed load *everything* (I didn't check).

**Comment by Twixes** [comment]
`SharedArrayBuffer` would be technically perfect and _maybe_ there is a way to pull that off, but yeah, requires going lower-level for sure.

But it seems like that also applies to this idea:

> we could fetch this at build time and then all threads can leverage the same db without all having to keep it in memory

`mmdb-lib` takes a `Buffer`, so it _needs_ to keep the whole database in memory. There probably is a way to avoid keeping the DB in memory, but it will require rewriting `mmdb-lib` or using a different library (if I'm not missing something).
Also, I'm not sure what's our redistribution agreement with Maxmind, so the current solution of keeping the DB in a private repo is probably safer. Plus, committing MMDBs to this repo would bloat it a lot (in terms of amount of data pulled on `git clone` – https://github.com/PostHog/http-mmdb which serves this role currently is a whopping **1.4 GB**).
