### ISSUE TITLE
PostgreSQL - DROP `posthog_event` table

### ISSUE THREAD

**Issue by guidoiaquinti** [PostHog/posthog#8539]
## Is your feature request related to a problem?
As we don't host events into PostgreSQL anymore, we should:

1. cleanup all the code still referencing the table
2. drop the table

## Describe the solution you'd like
See above

## Describe alternatives you've considered
Do nothing

## Additional context
See internal [Slack conversation](https://posthog.slack.com/archives/C02E3BKC78F/p1644489700336279).

**Comment by sreeo** [comment]
Can I pick this up?

**Comment by guidoiaquinti** [comment]
👋 Hey @sreeo, thank you for volunteering but I think @macobo is already working on it. See:

- https://github.com/PostHog/posthog/pull/8662
- https://github.com/PostHog/posthog/pull/8638

**Comment by macobo** [comment]
Took a few PRs but the `posthog_events` table is no longer being read in any of our code.

PRs:
- https://github.com/PostHog/posthog/pull/8623
- https://github.com/PostHog/posthog/pull/8624
- https://github.com/PostHog/posthog/pull/8625
- https://github.com/PostHog/posthog/pull/8638
- https://github.com/PostHog/posthog/pull/8643
- https://github.com/PostHog/posthog/pull/8661
- https://github.com/PostHog/posthog/pull/8662
- https://github.com/PostHog/posthog/pull/8667

We still have the model in codebase (as it's referenced via some other tables) and haven't dropped the actual table. I think this is good enough for now and we can TRUNCATE this in production.

I'd avoid adding a migration to drop/truncate to avoid potential pain with postgres-users accidentally updating at some future date.

**Comment by guidoiaquinti** [comment]
Nice work 👏 Let's keep this issue open till we actually drop the table.
