### ISSUE TITLE
Insights/retention: add option to export the report as a CSV file

### ISSUE THREAD

**Issue by guidoiaquinti** [PostHog/posthog#8571]
## Is your feature request related to a problem?
No

## Describe the solution you'd like
A customer is asking if we could add an option to export a retention report as CSV file.

## Describe alternatives you've considered
Do nothing.

## Additional context
See [request in Slack](https://posthogusers.slack.com/archives/C01GLBKHKQT/p1644610692497599)

**Comment by sreeo** [comment]
Anyone working on this? Would like to give this one an attempt.

**Comment by inbreaks** [comment]
Is this the same problem ? #8513

**Comment by mariusandra** [comment]
You now can export retention reports (the triangle shaped table) as a CSV's. You can also explore the data further with SQL, modify it in any way, and export that as a CSV. Thus, closing.
