### ISSUE TITLE
Follow up to cohort recalculation improvements

### ISSUE THREAD

**Issue by EDsCODE** [PostHog/posthog#8618]
Implemented https://github.com/PostHog/posthog/pull/8610 

Now cohorts will only populate postgres cohortpeople table when it's used in a feature flag filter. This reduces any postgres recalculation excess that has been [clogging](#8376) up postgres performance.

Some important notes:
1) Feature flags will trigger a recalculation when created/updated and uses a cohort in its filter
2) There is a cached item that keeps track of all cohort ids that are used in feature flags. This is updated once an hour or anytime a feature flag is created or updated
3) The list of people on cohort page queries clickhouse now. We should monitor this closely

TODO:
- [ ] delete old versions of posthog_cohortpeople in postgres. Every time there's a recalculation for postgres, it increments a version on the cohort model and renders all previous cohortpeople useless. We aren't cleaning this up yet
- [ ] Communicate to a user who creates a feature flag that when a flag is updated or created and uses a new cohort that's never been used in a flag, it will calculate the cohort in the background so the flag might not necessarily work immediately
- [ ] Clean up index on posthog_cohortpeople table

CC @hazzadous @guidoiaquinti @fuziontech @neilkakkar @timgl

**Comment by guidoiaquinti** [comment]
Adding it for posterity but here's the impact of https://github.com/PostHog/posthog/pull/8610 on PostgreSQL. Nice work @EDsCODE 👏 

<img width="455" alt="Screenshot 2022-02-16 at 07 49 03" src="https://user-images.githubusercontent.com/4038041/154238756-55af73d5-8737-44d5-ba96-24f8bf7d910b.png">
<img width="454" alt="Screenshot 2022-02-16 at 07 49 13" src="https://user-images.githubusercontent.com/4038041/154238762-6976dcdc-83a3-4601-ad8a-4587916c9262.png">

All `TODOs` are 👍 

> Feature flags will trigger a recalculation when created/updated and uses a cohort in its filter

Do we rate-limit the number of creation/update for a team in a specific timeframe? 

> There is a cached item that keeps track of all cohort ids that are used in feature flags. This is updated once an hour or anytime a feature flag is created or updated
👍 

> The list of people on cohort page queries clickhouse now. We should monitor this closely

Do you think we have enough metrics and logs to do it? Should we add some alerting on this specific endpoint?

**Comment by guidoiaquinti** [comment]
Hey @EDsCODE, are the TODOs and other follow ups from this task completed? If yes, can we close this issue?

**Comment by EDsCODE** [comment]
These TODOs haven't been done yet. Item 2 should be done with this sprint's work

**Comment by EDsCODE** [comment]
Related: https://github.com/PostHog/posthog/issues/9584

**Comment by EDsCODE** [comment]
Working through #10130 first

**Comment by guidoiaquinti** [comment]
Sorry to bother you again @EDsCODE but can we consider this as ✅ ?

**Comment by EDsCODE** [comment]
No :( Sorry for the delay here. I've collected another cohort [loose end](https://posthog.slack.com/archives/C02E3BKC78F/p1656016043276489) that would pair well with this cleanup. Will carve out time during my support hero cycle coming up to work through them
