### ISSUE TITLE
Suggested dashboards/insights ?

### ISSUE THREAD

**Issue by paolodamico** [PostHog/posthog#8622]
## Is your feature request related to a problem?

As we're working through collaboration and based on user feedback wanted to put forward this concept to make it easier to navigate to your dashboards. **Independent from what we do with the project home.**

## Describe the solution you'd like

Introduce this concept of suggested items that can help you navigate to specifically what you may be looking for.

<img width="1280" alt="" src="https://user-images.githubusercontent.com/5864173/154221886-1bf1ed3a-ad2c-48a0-8baf-61109028a840.png">

More context on [Figma](https://www.figma.com/file/NHPA2hVWwaKp4eTGWdigs9/Product-Concepts?node-id=1371%3A4316).

## Describe alternatives you've considered

- While the project home is more about discovery and this about finding the thing you're looking for, it may be the case that the project home (depending on where we take it) covers this need.

## Additional context
- This is separate from the project home page and intended for a later sprint and a separate experiment, if it makes sense to continue.
- Unsure this works out well with pinned dashboards, we would have to figure something here.

Very related to some feedback you gave a few weeks ago @jamesefhawkins, thoughts? Also CC @clarkus @Twixes @rcmarron

**Comment by clarkus** [comment]
I think the more fundamental problem is figuring out what qualifies as a valuable recommendation or suggestion. We could place recommendations in a variety of positions and formats, but could still be recommending things that are not valuable. I would rather focus on identifying the attributes that contribute to relevancy and determine how feasible this kind of thing is given the data we have.
