### ISSUE TITLE
PostHog CloudFlare app

### ISSUE THREAD

**Issue by guidoiaquinti** [PostHog/posthog#8639]
## Is your feature request related to a problem?
Evaluate to build a PostHog CloudFlare app so that our users can install PostHog in their app without editing code.

One workaround could be to use the official [`add-html`](https://www.cloudflare.com/apps/add-html) app but one of our users reported it is no longer supported by CloudFlare.

## Describe the solution you'd like
We have a PostHog app listed at https://www.cloudflare.com/apps/

## Describe alternatives you've considered
Do nothing.

## Additional context
* See thread in our Slack [community workspace](https://posthogusers.slack.com/archives/C01GLBKHKQT/p1645015765569469)

**Comment by nthbooth-feedr** [comment]
The post that says it is no longer supported by cloudflare (add-html) can be found at the following location: https://github.com/cloudflare-apps/add-html/issues/4
