### ISSUE TITLE
DateTime property filters should allow relative dates

### ISSUE THREAD

**Issue by pauldambra** [PostHog/posthog#8640]
## Is your feature request related to a problem?

A customer using the date time filtering for #6619 asked

```
if I choose today... will this be today tomorrow as well? eg. always now.

for context I would like to check if a customer still has a subscription by checking a profile param and making sure expiration is in the future.

eg. give me all customers where subscription_expiration > today (now)
```

Currently the dates chosen in the date picker are all absolute. E.g. a selection of "today" is "yesterday" after one day

## Describe the solution you'd like

To be able to choose relative as well as absolute dates

This allows filters like `subscription_end_date > today` or `license expired > seven days ago`

## Describe alternatives you've considered

Asking people to update insights that should query after a relative date when they want to see it

**Comment by macobo** [comment]
Aside: this might have implications if we ever cache timeseries queries - this kind of filter makes past results unusable.

**Comment by pauldambra** [comment]
Fair point @macobo... I guess you could pass refresh=true when loading a graph or infer it if that filter is present... But that's not great for load... And might be confusing for users... They might not understand why insight X is fast but insight Y is slow

Tagging @clarkus too

**Comment by McKean** [comment]
I understand the complexity with timeseries. Perhaps it would make sense to restrict the dynamic functionality to the filters?
Use case would be for example to only show data from users who have been active since yesterday.
![image](https://user-images.githubusercontent.com/517851/154487357-4c01f699-175b-4895-83c8-4746cca9b49a.png)
Not sure if this would make things easier though...

**Comment by pauldambra** [comment]
You can now do this
