### ISSUE TITLE
503 error on loading dashboard on app

### ISSUE THREAD

**Issue by jamesefhawkins** [PostHog/posthog#866]
**Describe the bug**
-> DAU/Signups (our internal dashboard) on app.posthog.com seems inconsistently to load slowly with 503 errors

**To Reproduce**
1. Log in to the PostHog account
2. Go to DAU/Signups
3. Some of the dashboard items seem slow to load / don't load
![Screenshot 2020-05-27 at 12 58 38](https://user-images.githubusercontent.com/47497682/83016521-fdbefc00-a019-11ea-8ea0-6b78fbc85bf5.png)

**Comment by EDsCODE** [comment]
Can ease this problem #765
