### ISSUE TITLE
Searching on the persons page times out

### ISSUE THREAD

**Issue by rcmarron** [PostHog/posthog#8660]
## Bug description

Go to the persons page on cloud. Type an email into the search box. Wait... it times out with a 500 error

[Sentry error](https://sentry.io/organizations/posthog2/issues/1724065650/events/07f228d03a1d40a3b666aea2fdfd6182/?project=1899813)

## Expected behavior

The search would quickly complete

## Additional context

I don't have time to investigate this at the moment, but I wonder if it's related to changes in the PG indexes? 

cc @guidoiaquinti

**Comment by guidoiaquinti** [comment]
👋 Hey @rcmarron, I can confirm we didn't change any index.

I see the the query shape is something like:
```
SELECT DISTINCT ON ("posthog_person"."id") "posthog_person"."id", "posthog_person"."created_at", "posthog_person"."properties_last_updated_at", "posthog_person"."properties_last_operation", "posthog_person"."team_id", "posthog_person"."properties", "posthog_person"."is_user_id", "posthog_person"."is_identified", "posthog_person"."uuid", "posthog_person"."version" 
  FROM "posthog_person"  LEFT OUTER JOIN "posthog_persondistinctid" ON ("posthog_person"."id" = "posthog_persondistinctid"."person_id") 
 WHERE ("posthog_person"."team_id" = $1 AND (UPPER("posthog_person"."properties"::text) LIKE UPPER(?) OR UPPER("posthog_persondistinctid"."distinct_id"::text) LIKE UPPER(?))) 
 ORDER BY "posthog_person"."id" DESC LIMIT $4
 ```

and looking at the query plan it is using good indexes. The query is anyway slow as it is doing > 1GB reads from disk.

**Comment by mariusandra** [comment]
This could be moved out of postgres onto something like this: https://github.com/PostHog/posthog/pull/8414 (with [some fixes](https://github.com/PostHog/posthog/pull/8414#discussion_r807892681))

**Comment by neilkakkar** [comment]
Similar: https://github.com/PostHog/posthog/issues/8391

**Comment by Twixes** [comment]
Also related: #5717

**Comment by neilkakkar** [comment]
Removing duplicate issues
