### ISSUE TITLE
Feature flag rollout column takes up too much space

### ISSUE THREAD

**Issue by timrutter** [PostHog/posthog#8715]
## Bug description

![image](https://user-images.githubusercontent.com/51402860/155158263-0fbc3cf0-61ae-4721-b937-5f9d885cbf13.png)

see above, with a long filter in the rollout column the table is very wide and you can't see the enable button on the right hand side.

## Expected behavior

Filter should be truncated

**Comment by neilkakkar** [comment]
Hey @timrutter , are you on cloud or self-hosted? If self-hosted, what's the version?

It should be fixed on cloud, and would be coming to the next release (today).

**Comment by timrutter** [comment]
self-hosted at present

**Comment by timrutter** [comment]
version 1.31.1

**Comment by neilkakkar** [comment]
Should be sorted now :)
