### ISSUE TITLE
Annotations showing on chart timelines incorrectly.

### ISSUE THREAD

**Issue by tylerdavis** [PostHog/posthog#8719]
## Bug description

Annotations are showing up incorrectly on insight timelines.

When a dashboard first loads, the annotations are showing up in the incorrect position.  When I hit the refresh button, they show up correctly.  I've also seen a single annotation duplicated multiple times on the timeline, although I don't have a screenshot of that.  I will add one as soon as I come across it again.

<img width="715" alt="CleanShot 2022-02-22 at 19 50 03@2x" src="https://user-images.githubusercontent.com/490887/155259710-5456bddb-975e-427c-8ec3-9381f603a251.png">

## Expected behavior

I'd love to see the annotations showing accurately.

## How to reproduce

1. Load an insight

## Environment

- [ ] PostHog Cloud
- [x] self-hosted PostHog (ClickHouse-based), version/commit: 1.32.0/b5068a4381cb8a9ef50d5a67b45480e31e603252
- [ ] self-hosted PostHog (Postgres-based, legacy), version/commit: _please provide_

**Comment by Twixes** [comment]
This is fixed now!
