### ISSUE TITLE
Actions from Cross Eng Discussion

### ISSUE THREAD

**Issue by marcushyett-ph** [PostHog/posthog#8742]
* Best practices / support when working across teams
    * Ask in, ask PostHog anything for  best person to review your code
    * @mariusandra to include link to best practices in PR and ensure they're up to date
    * ✅ @fuziontech to arrange weekly brown bag session same time opposite week as sprint planning* 
* Water-cooler chats
    * @rcmarron to create a USA slack channel and make it action packed
 * Expected PR Review times
   * Any PR should aim to be merged 24hr later (this determines size) - or be pinged
   * 24hrs is the expected time when you'd ping someone
   * Everyone is empowered to ask to split a big PR
   * Update slack Bio with your preferences on pinging (or other quirks) - how to work with me
* Notion?
   * If I want to use a new tool, I can try it out myself but I'm responsible for all the work to roll it out (e.g. cost, migration, etc)
   * @pauldambra can you document this process in the handbook? Start with process around creating a ticket in company internal
* Tips and tricks for Dev
   *  @timgl is the owner for developer experience, ping if you have any issues.
   *  Harry recommends using codespaces
   * If you love your dev environment talk about it at the brown bag
   * ✅ @marcushyett-ph create tell-posthog-anything channel on slack for announcing cool tips and tricks related to Posthog
* Support hero etc
   * @timgl to cover as a topic at company offsite

**Comment by macobo** [comment]
> to arrange weekly brown bag session same time opposite week as sprint planning*

Note that that time falls far outside of at least my normal working hours, making it hard to attend any of these and retain sanity. I assume the opposite problem is true for west coast for any earlier time.

**Comment by pauldambra** [comment]
first draft of decision process at posthog/posthog.com#3093 for comments
