### ISSUE TITLE
Annotations aren't shown on time-based bar charts

### ISSUE THREAD

**Issue by simfish85** [PostHog/posthog#8745]
## Bug description

If I create a time-based trend chart, then annotations are shown at the bottom on the x-axis as per this screenshot:

<img width="1149" alt="Screenshot 2022-02-24 at 10 11 37" src="https://user-images.githubusercontent.com/11316707/155504416-737e12d0-cecd-4529-8b78-fb21c85063ee.png">

If I switch the same chart to be a time-based bar chart the annotations disappear:

<img width="1133" alt="Screenshot 2022-02-24 at 10 12 18" src="https://user-images.githubusercontent.com/11316707/155504498-7a3c5be2-06d9-4c10-9a76-aadfdbe7baf8.png">

## Expected behavior

Annotations should be visible on time-based charts regardless of whether they are line or bar, as they relate to events which happened in a specific time period.

## How to reproduce

1. Create a trend insight that uses a line chart to visualize the results
2. Switch it to the bar chart type
3. Note that annotations disappear from the x-axis

## Environment

- [x ] PostHog Cloud
- [ ] self-hosted PostHog (ClickHouse-based), version/commit: _please provide_
- [x ] self-hosted PostHog (Postgres-based, legacy), version/commit: _please provide_

## Additional context

Initial report came from a customer

**Comment by timgl** [comment]
picking this up!

**Comment by timgl** [comment]
picking this up!
