### ISSUE TITLE
Filters not applying correctly for hubspot score

### ISSUE THREAD

**Issue by marcushyett-ph** [PostHog/posthog#8746]
## Bug description

When I filter by users who do not have **hubspot_score** set, I get a list of users, however when I look at their user profiles, many of them actually seem to have hubspot score set.

## Expected behavior

I would expect filtering on a property to return consistently with the properties of that person.

## How to reproduce

1. https://app.posthog.com/insights/m66Tcsw2#filters=%7B%22insight%22%3A%22TRENDS%22%2C%22events%22%3A%5B%7B%22id%22%3A%22user%20signed%20up%22%2C%22name%22%3A%22user%20signed%20up%22%2C%22type%22%3A%22events%22%2C%22order%22%3A0%2C%22properties%22%3A%5B%7B%22key%22%3A%22hubspot_score%22%2C%22type%22%3A%22person%22%2C%22value%22%3A%22is_not_set%22%2C%22operator%22%3A%22is_not_set%22%7D%5D%2C%22custom_name%22%3A%22Hubspot%20Score%20Not%20Set%22%7D%5D%2C%22actions%22%3A%5B%5D%2C%22date_to%22%3Anull%2C%22display%22%3A%22ActionsLineGraph%22%2C%22interval%22%3A%22week%22%2C%22date_from%22%3A%22-180d%22%2C%22new_entity%22%3A%5B%5D%2C%22properties%22%3A%5B%5D%2C%22show_legend%22%3Atrue%2C%22filter_test_accounts%22%3Atrue%7D
2. Click a data point, look at the profile of one of the users, see if hubspot score is actually set.

## Environment

- [x] PostHog Cloud
- [ ] self-hosted PostHog (ClickHouse-based), version/commit: _please provide_
- [ ] self-hosted PostHog (Postgres-based, legacy), version/commit: _please provide_

**Comment by marcushyett-ph** [comment]
cc: @EDsCODE this feels like it could be a data integrity issue with the persons modal or the original query - I'm struggling to debug it further

**Comment by EDsCODE** [comment]
Just looked. Here's a user in [clickhouse](https://metabase.posthog.net/question#eyJkYXRhc2V0X3F1ZXJ5Ijp7InR5cGUiOiJuYXRpdmUiLCJuYXRpdmUiOnsicXVlcnkiOiJTRUxFQ1QgcGVyc29uX2lkIEFTIGFjdG9yX2lkICxcbiAgICAgICBncm91cFVuaXFBcnJheSgxMCkoKHRpbWVzdGFtcCwgdXVpZCwgJHNlc3Npb25faWQsICR3aW5kb3dfaWQpKSBhcyBtYXRjaGluZ19ldmVudHNcbiAgRlJPTSAoXG4gICAgICAgIFNFTEVDVCBlLnRpbWVzdGFtcCBhcyB0aW1lc3RhbXAsXG4gICAgICAgICAgICAgICBlLm1hdF9kaXN0aW5jdF9pZCBhcyBtYXRfZGlzdGluY3RfaWQsXG4gICAgICAgICAgICAgICBlLm1hdF8kaG9zdCBhcyBtYXRfJGhvc3QsXG4gICAgICAgICAgICAgICBlLiR3aW5kb3dfaWQgYXMgJHdpbmRvd19pZCxcbiAgICAgICAgICAgICAgIGUubWF0XyRzZXNzaW9uX2lkIGFzICRzZXNzaW9uX2lkLFxuICAgICAgICAgICAgICAgcGRpLnBlcnNvbl9pZCBhcyBwZXJzb25faWQsXG4gICAgICAgICAgICAgICBlLmRpc3RpbmN0X2lkIGFzIGRpc3RpbmN0X2lkLFxuICAgICAgICAgICAgICAgZS50ZWFtX2lkIGFzIHRlYW1faWQsXG4gICAgICAgICAgICAgICBlLnV1aWQgYXMgdXVpZFxuICAgICAgICAgIEZST00gZXZlbnRzIGVcbiAgICAgICAgIElOTkVSIEpPSU4gKFxuICAgICAgICAgICAgICAgIFNFTEVDVCBkaXN0aW5jdF9pZCxcbiAgICAgICAgICAgICAgICAgICAgICAgYXJnTWF4KHBlcnNvbl9pZCwgdmVyc2lvbikgYXMgcGVyc29uX2lkXG4gICAgICAgICAgICAgICAgICBGUk9NIHBlcnNvbl9kaXN0aW5jdF9pZDJcbiAgICAgICAgICAgICAgICAgV0hFUkUgdGVhbV9pZCA9IDJcbiAgICAgICAgICAgICAgICAgR1JPVVAgQlkgZGlzdGluY3RfaWRcbiAgICAgICAgICAgICAgICBIQVZJTkcgYXJnTWF4KGlzX2RlbGV0ZWQsIHZlcnNpb24pID0gMFxuICAgICAgICAgICAgICAgKSBBUyBwZGlcbiAgICAgICAgICAgIE9OIGUuZGlzdGluY3RfaWQgPSBwZGkuZGlzdGluY3RfaWRcbiAgICAgICAgIElOTkVSIEpPSU4gKFxuICAgICAgICAgICAgICAgIFNFTEVDVCBpZFxuICAgICAgICAgICAgICAgICAgRlJPTSBwZXJzb25cbiAgICAgICAgICAgICAgICAgV0hFUkUgdGVhbV9pZCA9IDJcbiAgICAgICAgICAgICAgICAgR1JPVVAgQlkgaWRcbiAgICAgICAgICAgICAgICBIQVZJTkcgbWF4KGlzX2RlbGV0ZWQpID0gMFxuICAgICAgICAgICAgICAgICAgIEFORCBOT1QgKGFyZ01heChwZXJzb24ucG1hdF9lbWFpbCwgX3RpbWVzdGFtcCkgSUxJS0UgJyVwb3N0aG9nLmNvbSUnKVxuICAgICAgICAgICAgICAgICAgIEFORCBOT1QgaGFzKFsnY2FwdHVyaUBjYXB0dXJpLmNvbSddLCBhcmdNYXgocGVyc29uLnBtYXRfZW1haWwsIF90aW1lc3RhbXApKVxuICAgICAgICAgICAgICAgICAgIEFORCBlbXB0eShhcmdNYXgocGVyc29uLnBtYXRfaHVic3BvdF9zY29yZSwgX3RpbWVzdGFtcCkpXG4gICAgICAgICAgICAgICApIHBlcnNvblxuICAgICAgICAgICAgT04gcGVyc29uLmlkID0gcGRpLnBlcnNvbl9pZFxuICAgICAgICAgV0hFUkUgdGVhbV9pZCA9IDJcbiAgICAgICAgICAgQU5EIGV2ZW50ID0gJ3VzZXIgc2lnbmVkIHVwJ1xuICAgICAgICAgICBBTkQgdG9TdGFydE9mV2Vlayh0aW1lc3RhbXApID49IHRvU3RhcnRPZldlZWsodG9EYXRlVGltZSgnMjAyMi0wMS0xNiAwMDowMDowMCcpKVxuICAgICAgICAgICBBTkQgdGltZXN0YW1wIDw9ICcyMDIyLTAxLTIyIDIzOjU5OjU5J1xuICAgICAgICAgICBBTkQgKChOT1QgaGFzKFsnMTI3LjAuMC4xOjMwMDAnLCAnMTI3LjAuMC4xOjUwMDAnLCAnbG9jYWxob3N0OjUwMDAnLCAnbG9jYWxob3N0OjgwMDAnXSwgbWF0XyRob3N0KSBBTkQgTk9UIChtYXRfZGlzdGluY3RfaWQgSUxJS0UgJyVwb3N0aG9nLmNvbSUnKSkpXG4gICAgICAgKVxuIEdST1VQIEJZIGFjdG9yX2lkXG4gTElNSVQgMjAwXG5PRkZTRVQgMFxuXG5TRUxFQ1QgSlNPTkV4dHJhY3RSYXcocHJvcGVydGllcywgJ2h1YnNwb3Rfc2NvcmUnKSBGUk9NIHBlcnNvbiB3aGVyZSBpZCBJTiAoXG4gICAgU0VMRUNUIHBlcnNvbl9pZCBBUyBhY3Rvcl9pZFxuICBGUk9NIChcbiAgICAgICAgU0VMRUNUIGUudGltZXN0YW1wIGFzIHRpbWVzdGFtcCxcbiAgICAgICAgICAgICAgIGUubWF0X2Rpc3RpbmN0X2lkIGFzIG1hdF9kaXN0aW5jdF9pZCxcbiAgICAgICAgICAgICAgIGUubWF0XyRob3N0IGFzIG1hdF8kaG9zdCxcbiAgICAgICAgICAgICAgIGUuJHdpbmRvd19pZCBhcyAkd2luZG93X2lkLFxuICAgICAgICAgICAgICAgZS5tYXRfJHNlc3Npb25faWQgYXMgJHNlc3Npb25faWQsXG4gICAgICAgICAgICAgICBwZGkucGVyc29uX2lkIGFzIHBlcnNvbl9pZCxcbiAgICAgICAgICAgICAgIGUuZGlzdGluY3RfaWQgYXMgZGlzdGluY3RfaWQsXG4gICAgICAgICAgICAgICBlLnRlYW1faWQgYXMgdGVhbV9pZCxcbiAgICAgICAgICAgICAgIGUudXVpZCBhcyB1dWlkXG4gICAgICAgICAgRlJPTSBldmVudHMgZVxuICAgICAgICAgSU5ORVIgSk9JTiAoXG4gICAgICAgICAgICAgICAgU0VMRUNUIGRpc3RpbmN0X2lkLFxuICAgICAgICAgICAgICAgICAgICAgICBhcmdNYXgocGVyc29uX2lkLCB2ZXJzaW9uKSBhcyBwZXJzb25faWRcbiAgICAgICAgICAgICAgICAgIEZST00gcGVyc29uX2Rpc3RpbmN0X2lkMlxuICAgICAgICAgICAgICAgICBXSEVSRSB0ZWFtX2lkID0gMlxuICAgICAgICAgICAgICAgICBHUk9VUCBCWSBkaXN0aW5jdF9pZFxuICAgICAgICAgICAgICAgIEhBVklORyBhcmdNYXgoaXNfZGVsZXRlZCwgdmVyc2lvbikgPSAwXG4gICAgICAgICAgICAgICApIEFTIHBkaVxuICAgICAgICAgICAgT04gZS5kaXN0aW5jdF9pZCA9IHBkaS5kaXN0aW5jdF9pZFxuICAgICAgICAgSU5ORVIgSk9JTiAoXG4gICAgICAgICAgICAgICAgU0VMRUNUIGlkXG4gICAgICAgICAgICAgICAgICBGUk9NIHBlcnNvblxuICAgICAgICAgICAgICAgICBXSEVSRSB0ZWFtX2lkID0gMlxuICAgICAgICAgICAgICAgICBHUk9VUCBCWSBpZFxuICAgICAgICAgICAgICAgIEhBVklORyBtYXgoaXNfZGVsZXRlZCkgPSAwXG4gICAgICAgICAgICAgICAgICAgQU5EIE5PVCAoYXJnTWF4KHBlcnNvbi5wbWF0X2VtYWlsLCBfdGltZXN0YW1wKSBJTElLRSAnJXBvc3Rob2cuY29tJScpXG4gICAgICAgICAgICAgICAgICAgQU5EIE5PVCBoYXMoWydjYXB0dXJpQGNhcHR1cmkuY29tJ10sIGFyZ01heChwZXJzb24ucG1hdF9lbWFpbCwgX3RpbWVzdGFtcCkpXG4gICAgICAgICAgICAgICAgICAgQU5EIGVtcHR5KGFyZ01heChwZXJzb24ucG1hdF9odWJzcG90X3Njb3JlLCBfdGltZXN0YW1wKSlcbiAgICAgICAgICAgICAgICkgcGVyc29uXG4gICAgICAgICAgICBPTiBwZXJzb24uaWQgPSBwZGkucGVyc29uX2lkXG4gICAgICAgICBXSEVSRSB0ZWFtX2lkID0gMlxuICAgICAgICAgICBBTkQgZXZlbnQgPSAndXNlciBzaWduZWQgdXAnXG4gICAgICAgICAgIEFORCB0b1N0YXJ0T2ZXZWVrKHRpbWVzdGFtcCkgPj0gdG9TdGFydE9mV2Vlayh0b0RhdGVUaW1lKCcyMDIyLTAxLTE2IDAwOjAwOjAwJykpXG4gICAgICAgICAgIEFORCB0aW1lc3RhbXAgPD0gJzIwMjItMDEtMjIgMjM6NTk6NTknXG4gICAgICAgICAgIEFORCAoKE5PVCBoYXMoWycxMjcuMC4wLjE6MzAwMCcsICcxMjcuMC4wLjE6NTAwMCcsICdsb2NhbGhvc3Q6NTAwMCcsICdsb2NhbGhvc3Q6ODAwMCddLCBtYXRfJGhvc3QpIEFORCBOT1QgKG1hdF9kaXN0aW5jdF9pZCBJTElLRSAnJXBvc3Rob2cuY29tJScpKSlcbiAgICAgICApXG4gR1JPVVAgQlkgYWN0b3JfaWRcbiBMSU1JVCAyMDBcbk9GRlNFVCAwXG4pXG5cblNFTEVDVCAqIEZST00gcGVyc29uIHdoZXJlIHBtYXRfZW1haWwgPSAnbXdhcmRAbXV4LmNvbSciLCJ0ZW1wbGF0ZS10YWdzIjp7fX0sImRhdGFiYXNlIjoyfSwiZGlzcGxheSI6InRhYmxlIiwidmlzdWFsaXphdGlvbl9zZXR0aW5ncyI6e319) and their data in [postgres](https://metabase.posthog.net/question#eyJkYXRhc2V0X3F1ZXJ5Ijp7ImRhdGFiYXNlIjozLCJuYXRpdmUiOnsicXVlcnkiOiJTRUxFQ1QgKiBGUk9NIHBvc3Rob2dfcGVyc29uIHdoZXJlIHV1aWQgPSAnMDE3ZTY1ODQtM2E2My0wMDAwLTM4Y2UtN2FhMjYxZWM3MjcxJyIsInRlbXBsYXRlLXRhZ3MiOnt9fSwidHlwZSI6Im5hdGl2ZSJ9LCJkaXNwbGF5IjoidGFibGUiLCJ2aXN1YWxpemF0aW9uX3NldHRpbmdzIjp7fX0=). The query filters on clickhouse persons which shows `hubspot_score` is empty however the postgres version of the person shows a hubspot score which is causing the confusion.

Will tag @yakkomajuri and @tiina303 here also as they're working on ingestion of persons

**Comment by yakkomajuri** [comment]
Yeah so this is a db sync issue I wrote a fix for a long time ago but it got bundled up with the out of order ingestion stuff and never got shipped.

@tiina303 - wondering if we can split up some of the work to ship the fix for this at least?

**Comment by yakkomajuri** [comment]
https://github.com/PostHog/posthog/pull/6628

**Comment by marcushyett-ph** [comment]
> wondering if we can split up some of the work to ship the fix for this at least?

+1 on getting this out sooner rather than later!

**Comment by tiina303** [comment]
Karl and I will be pairing - syncing on discussing the future on Friday, will know the plans better and prioritize this for next sprint

**Comment by lsmith77** [comment]
I stumbled over this ticket as I am exploring integration between PostHog and HubSpot. But I wonder what the `hubspot_score` is?

**Comment by joethreepwood** [comment]
> I stumbled over this ticket as I am exploring integration between PostHog and HubSpot. But I wonder what the `hubspot_score` is?

Hi Lukas! `hubspot_score` is a property we use for lead scoring and for use in some of our internal processes. You can read a bit more about it [here](https://posthog.com/handbook/growth/sales/crm#how-we-calculate-ideal-customer-profile-icp).
