### ISSUE TITLE
Instance settings, management links, and other configuration 

### ISSUE THREAD

**Issue by clarkus** [PostHog/posthog#8749]
## Is your feature request related to a problem?

The work in https://github.com/PostHog/posthog/pull/8096#discussion_r808954345 resulted in an instance management link being added to the project navigation. In order to ensure scale and consistency, I want to reserve the project navigation for only project items. We're already reaching an upper bound of how many links we can display in this area. 

## Describe the solution you'd like

We should link to these areas via the places we already communicate this information: breadcrumbs and the utility navigation. Breadcrumbs give users a sense of place. You're in this organization, in this project, looking at this insight. When we communicate that hierarchy, we facilitate switching via submenus. Within these menus we can also link to corresponding settings areas.

![Frame 9238](https://user-images.githubusercontent.com/254612/155624984-c19ea45a-2e63-4a82-b641-ebd8b669cacb.png)

This pattern is reinforced in the utility navigation. Here we can show the same patterns for getting to settings. Additionally, we can add a clear and prominent link to instance settings for any users that have access to that area.

![Utility navigation](https://user-images.githubusercontent.com/254612/155625776-d451a1bb-c3b6-41b0-bd25-3ae57f4e600b.png)

## Describe alternatives you've considered

- An idea was shared to include a footer with some management links, but didn't explore this yet. During some of the concept work for updating the app navigation, I tried a footer but the feedback was that it felt off brand. We could try this eventually, but I think it wouldn't have the same priority or ease of use as the solution above. 

## Additional context

- [Thread in slack](https://posthog.slack.com/archives/C0113360FFV/p1645633659020589)
- [Figma](https://www.figma.com/file/gQBj9YnNgD8YW4nBwCVLZf/PostHog-App?node-id=7768%3A39486)

**Comment by paolodamico** [comment]
Normally I'd take this as feature owner, but I'm swamped with support hero this week, happy to take a look the week after. Improving this definitely makes sense but I do wonder if there's something else we can do to improve discovery for this. Particularly because it's only relevant for the handful of users who manage their PostHog instance.

**Comment by clarkus** [comment]
Why can't we move the link from the project navigation to the utility menu as specified above? Then we can circle back to include settings links in the breadcrumbs.
