### ISSUE TITLE
Pinning Insights to Dashboard

### ISSUE THREAD

**Issue by rhvrabec** [PostHog/posthog#8754]
## Bug description
I cannot get a custom date range to stick on an insight graph when I pin it to a dashboard. Mine shows the custom date range when I set it on the insight but back on the dashboard it resets it to last 7 days every time. I dont see a 'save' option before going back to the dashboard.

i also think i found a bug on insights you duplicate then edit on the dashboard view. If I try to edit an insight I duplicated and changed, when I click edit, I see the original insight (not including the changes i made after editing it). But on the dashboard I do see the edits I made after copying the original insight.

*Please describe.*  
This effects front end. I would send screenshots but now the duplicated insight graph is blank and not showing anything.

## Expected behavior
That new insight should be it's own object, no longer tied to the one it was created from.

## How to reproduce

1. created an insight
2. added to dashboard
3. duplicated insight
4. updated insight funnel steps / time frame
5. saved to dashboard as new insight
6. went to edit the new insight
7. see old insight before duplication

## Environment
- [ ] PostHog Cloud

**Comment by Twixes** [comment]
Hey! I think this is fixed now, but do let us know if you see the issue in some circumstances.
