### ISSUE TITLE
Sending empty user id in identify events creates None as a distinct ID 

### ISSUE THREAD

**Issue by rushabhnagda11** [PostHog/posthog#876]
**Is your feature request related to a problem? Please describe.**
So today we noticed we had a bug on our react app (caused by us) where we weren't setting the user id correctly in our `window.posthog.identify` call

This happened a bunch of times for a different users and what we noticed is when we went to the `/person/` URL on our posthog UI, it sort of unified all these users together under the `None` disinct ID.

**Describe the solution you'd like**
Posthog should ignore or discard identify events where the user id is not set or is undefined

**Describe alternatives you've considered**

**Additional context**
We've recently moved to posthog and it's been a really great experience so far to integrate. We used to use Heap earlier. The reason I'm making this as a feature request is because we didn't see it happen with our Heap setup.

***Thank*** you for your feature request - we love each and every one!

**Comment by rushabhnagda11** [comment]
If it helps I can submit a PR for this? Let me know

**Comment by timgl** [comment]
@rushabhnagda11 A PR would be super appreciated! I think this should happen in our [posthog-js](https://github.com/PostHog/posthog-js) library, where calling `posthog.identify` just errors when you set an empty distinct ID. This is how our other libraries work too.

Let me know if you have any questions around how to contribute that :)

**Comment by rushabhnagda11** [comment]
Hey thanks for getting back so quick and pointing me in the right direction appreciate it. I've submitted a PR for this :)

**Comment by mariusandra** [comment]
Hi @rushabhnagda11 version `1.1.1` of posthog-js is out and that includes the PR. Thanks again! Closing the issue. :)
