### ISSUE TITLE
Whitespace regression on auth screens

### ISSUE THREAD

**Issue by clarkus** [PostHog/posthog#8768]
## Bug description

<img width="500" alt="Screen Shot 2022-02-28 at 8 39 16 AM" src="https://user-images.githubusercontent.com/254612/156022150-198682d3-94f7-4f12-a270-55e35571dcd8.png">

The secondary links below the primary action should be separated by white space. See the reference in figma at https://www.figma.com/file/gQBj9YnNgD8YW4nBwCVLZf/PostHog-App?node-id=3558%3A32665

## Expected behavior

There should be some space between these items.

## How to reproduce

1. Sign out
2. Sign back in

## Environment

- [x] PostHog Cloud

**Comment by akbansa** [comment]
@clarkus, I am new to the PostHog repository. I don't have the reference to the Figma file you shared.

**Comment by clarkus** [comment]
> @clarkus, I am new to the PostHog repository. I don't have the reference to the Figma file you shared.

Thanks for letting me know. Anyone with the link should be able view the changes now.

**Comment by pauldambra** [comment]
confirmed this in prod

<img width="513" alt="Screenshot 2022-03-07 at 19 12 53" src="https://user-images.githubusercontent.com/984817/157101954-a258203f-1b22-49c1-9287-f96669ab240c.png">
