### ISSUE TITLE
Why did the tags migration fail? Ongoing investigation

### ISSUE THREAD

**Issue by alexkim205** [PostHog/posthog#8771]
## Context:

Last last Friday, a migration that copies old tags into the new Tag-TaggedItem models failed silently and clogged up the deployment pipeline. @hazzadous would you be able to help us pinpoint the root cause for why this migration failed? Tagging @rcmarron for visibility.

Migration in question: https://github.com/PostHog/posthog/pull/8529/files#diff-5a2c76bcd8ca1594e353eeedc5a72c640fa7ef351a7bcc1bca9b4b1385b9fdd4R1-R44

Incident Writeup: https://github.com/PostHog/postmortem/pull/13

CI Migration run: https://github.com/PostHog/posthog/runs/5250772494?check_suite_focus=true

## Theories/Clues:

* `ee/migrations/0010_migration_definitions_tags` succeeded while `posthog/migrations/0214_migration_dashboard_insight_tags` failed
	* Essentially the same code run on different data
* Application's servers were returning 500's after previous column rename migration was run
	* Might be red herring since subsequent deployments failed.
* If `deprecated_tags` had different data types (not str), migration fails on `tagify()`
* Ran out of memory querying all Insight and Dashboard objects

## Things to fix:

* `Model.objects.exclude` is an `AND` filter that should be an `OR`
* Wrap in try catch and log errors so that migration won't block deployment
* Reverse function should delete Tags as well as TaggedItems

**Comment by macobo** [comment]
The migration in question tries to run in a single transaction. That's cause enough to cause failures as until the transaction is committed, locks are held, causing timeouts and issues elsewhere.

**Comment by macobo** [comment]
For one, the migration does silly things like renaming model columns which is a terrible idea as old application code is running while migrations are running - otherwise how could you keep uptime?

On the second migration: 
- tries to run in a single transaction. That's cause enough to cause failures as until the transaction is committed, locks are held, causing timeouts and issues elsewhere. 
- queries all of the objects at once instead of batching it up which causes memory issues. 
- It uses `get_or_create` which does SELECT + INSERT per row which is going to be slow. 

Suggestion for the future: Run your loops (without modifying any data) against large datasets in the future to test + loop in people with migrations experience if stuff seems dicy.

Meta question: Is this issue still relevant? A lot of these points were already brought up in https://github.com/PostHog/postmortem/pull/13 and we updated the handbook around writing migrations: https://posthog.com/handbook/engineering/schema-changes

cc @guidoiaquinti

**Comment by hazzadous** [comment]
As @macobo mentions I think we're pretty clear on what happened with the first migration.

This ticket looks like it's specifically about the [Figure out why the migration failed](https://github.com/PostHog/postmortem/pull/13/files#diff-3a9bdac02543daaa9e6724206773361a97a2863f01a17a7b9070e10d9a57956aR54)

I'm not sure exactly what caused the failure but it's worth noting that the logs of the specific task are configured as:

```
                "logConfiguration": {
                    "logDriver": "awslogs",
                    "options": {
                        "awslogs-group": "awslogs-posthog-production",
                        "awslogs-region": "us-east-1",
                        "awslogs-stream-prefix": "posthog-production-migration"
                    }
                }
```

Which can be viewed [here in AWS](https://console.aws.amazon.com/cloudwatch/home?region=us-east-1#logsV2:log-groups/log-group/awslogs-posthog-production$3FlogStreamNameFilter$3Dmigration)

Spoiler alert, the retention is 1 day, so I think they are done 🌬️  Aside from this I don't think there are any logs of what happened that day.

As for guessing at why it would have failed, I would suggest all of the things that @macobo has mentioned. It's worth noting that:

 1. the SQL generated from [here](https://github.com/PostHog/posthog/pull/8529/files#diff-5a2c76bcd8ca1594e353eeedc5a72c640fa7ef351a7bcc1bca9b4b1385b9fdd4R15) and [here](https://github.com/PostHog/posthog/pull/8529/files#diff-5a2c76bcd8ca1594e353eeedc5a72c640fa7ef351a7bcc1bca9b4b1385b9fdd4R24) is probably not what you were expecting. We end up with `NOT ("posthog_dashboarditem"."deprecated_tags" = ARRAY[]::varchar(32)[] AND "posthog_dashboarditem"."deprecated_tags" IS NULL)`, which means we end up not excluding anything. This could very well cause a lot of memory usage, looks like migrations may be [limited to 2048](https://github.com/PostHog/posthog/pull/2458/files#diff-c54a68a207da5d9987517c2f705598c4e456455c1d30a635381097b35a33df34R204) although that might not be a limit value. At any rate we should batch fetch these.
 2. We should be [batching the inserts here](https://github.com/PostHog/posthog/pull/8529/files#diff-5a2c76bcd8ca1594e353eeedc5a72c640fa7ef351a7bcc1bca9b4b1385b9fdd4R31) also. Bulk create supports [batch_size param](https://docs.djangoproject.com/en/4.0/ref/models/querysets/#bulk-create)
 3. We don't need the transaction. given we have made `name, team_id` unique we have some kind of natural key, and we should be able to a. specify to ignore conflicts for the bulk_create and b. specify [`atomic = False`](https://docs.djangoproject.com/en/4.0/howto/writing-migrations/#non-atomic-migrations) on the migration.

What did we end up doing in the end? I see we have some but not many Tags.

**Comment by hazzadous** [comment]
And one other thing I forgot. We essentially are doing a `SELECT *` (although django is explicitly listing out all the fields.) We only actually use two fields. As well as meaning our code now depends on all those fields being in the table schema, it means we're transferring all that data across the network, which I imagine can be large. Consider instead using `Insight.objects.values_list("deprecated_tags", "team_id")` which will just pull out those fields, making your code more resilient to changing table schemas and hopefully less taxing all round.

**Comment by guidoiaquinti** [comment]
+1 to what @hazzadous and @macobo already wrote. I don't have anything more specific to add but feel free to ping/DM me/us if something is not clear @alexkim205 !

**Comment by alexkim205** [comment]
Thank you all, this is a lot of really good insight into migrations! This issue was just to collect a fresh perspective on possible areas this could've gone wrong, and I think I have a good set of next steps to work on the next iteration of this migration. I'm going to close out this issue and will tag you in the PR review.

> What did we end up doing in the end? I see we have some but not many Tags.

The ee migration miraculously finished running but the corresponding posthog migration silently failed and didn't run to completion. There weren't any tagged items for dashboards and insights immediately after the migration ran, so that migration was essentially a noop. The Tags you see today are tags that users created with the new tagging system after the migration.
