### ISSUE TITLE
Distinguish input fields with other controls - Experiments Dashboard

### ISSUE THREAD

**Issue by sankalpdomore** [PostHog/posthog#8781]
## Is your feature request related to a problem?

Just opened the AB testing dashboard for the first time and the UI felt overwhelming - mostly because there's a lot of sections in the AB testing dashboard. For example, every section has a white background and I don't know what's important as an input for me to start creating my AB test.

<img width="2559" alt="IMG 2022-03-01 at 16 58 54@2x" src="https://user-images.githubusercontent.com/18334593/156164724-b359b4ae-6dd7-477f-b4c7-23962b96ee87.png">

## Describe the solution you'd like

- Highlight inputs with a background color

![IMG 2022-03-01 at 17 29 25@2x](https://user-images.githubusercontent.com/18334593/156165420-511e249c-b83f-43eb-83d5-f789db6713c9.png)

- Highlight non-actionable headers with background color maybe as we do in other pages of the dashboard for example.

![IMG 2022-03-01 at 17 29 46@2x](https://user-images.githubusercontent.com/18334593/156165473-a126ab06-5912-4650-8d6a-05e8340e5188.png)

**Comment by neilkakkar** [comment]
cc: @clarkus @liyiy !

**Comment by clarkus** [comment]
Thank you for the idea, but this styling closely matches rarely used style for disabled fields. Thinking about it from a system, level, this change would conflict with those patterns. I agree that this layout needs some clean up, and we have some outstanding UI tasks to attend to here to fully wrap up the feature. Thanks again for the contribution.

**Comment by neilkakkar** [comment]
Closing for now, feel free to respond / reopen though, @sankalpdomore !
