### ISSUE TITLE
Support Strict Funnel Filtering with events

### ISSUE THREAD

**Issue by neilkakkar** [PostHog/posthog#8786]
## Is your feature request related to a problem?

When creating a strict funnel, I'd like to discard certain noisy-irrelevant events, so they don't get counted in strict semantics.

For example, I want to track a funnel of people who went from Page A directly to Page B.

But often, there will be $autocapture events or random custom events on the page that I don't want to consider right now.

I _might_ create a simple Page A -> Page B funnel, but this doesn't answer my question, since it includes all random paths that people took to get from Page A to Page B.

## Describe the solution you'd like

Ability to exclude events in a strict funnel

## Describe alternatives you've considered

???

## Additional context

[Asked by a customer](https://posthog.slack.com/archives/C02LR7352SG/p1646043843536609).

**Comment by clarkus** [comment]
<img width="286" alt="Screen Shot 2022-03-01 at 7 55 12 AM" src="https://user-images.githubusercontent.com/254612/156202476-2e36a901-a639-48ca-a304-1f16ea54e8f4.png">

Short term we might update this tooltip to be more accurate? To me this reads as strict order funnels automatically exclude other events not specified in the steps directly.

**Comment by neilkakkar** [comment]
Yep, that's exactly what it does.

I guess the specification here is that instead of ignoring all events, we only want to ignore some events from strict funnels. Ha, using exclusion filters for that sounds pretty confusing, since it's... different.
