### ISSUE TITLE
Incorrect pattern used for required fields on experimentation 

### ISSUE THREAD

**Issue by clarkus** [PostHog/posthog#8789]
## Bug description

This is a dark pattern for indicating required fields. It conflicts with the patterns used elsewhere in the product. It's also injected with generated content, which feels problematic to me. 

<img width="1175" alt="Screen Shot 2022-03-01 at 8 31 09 AM" src="https://user-images.githubusercontent.com/254612/156208950-4fc55f95-8168-4e17-a1a8-03e267d39165.png">

## Expected behavior

All fields are required in the product unless indicated otherwise. We communicate things that are optional, as most often they won't make up the bulk of a form. 

<img width="737" alt="Screen Shot 2022-03-01 at 8 33 06 AM" src="https://user-images.githubusercontent.com/254612/156209252-3a90baa5-60ee-4060-8390-5ab1a4887f7a.png">

## How to reproduce

1. Create a new experiment
## Environment

- [x] PostHog Cloud
- [ ] self-hosted PostHog (ClickHouse-based), version/commit: _please provide_
- [ ] self-hosted PostHog (Postgres-based, legacy), version/commit: _please provide_

## Additional context

- [Slack thread](https://posthog.slack.com/archives/C02283301EK/p1646149337959139)
- [Figma](https://www.figma.com/file/gQBj9YnNgD8YW4nBwCVLZf/PostHog-App?node-id=7348%3A35498)

**Comment by neilkakkar** [comment]
This one's sorted!
