### ISSUE TITLE
Managing secrets from instance settings

### ISSUE THREAD

**Issue by paolodamico** [PostHog/posthog#8792]
## Is your feature request related to a problem?

As suggested by @joesaunderson [on Slack](https://posthogusers.slack.com/archives/CT7HXDEG3/p1646135450395529?thread_ts=1646090938.065319&cid=CT7HXDEG3), masking secrets (e.g. email password) on the instance settings UI could be good practice.

## Describe the solution you'd like / Describe alternatives you've considered

I see three alternatives:
1. Masking the values in the UI when in view mode and showing them in edit mode.
2. Never let those values out of the backend and just allow staff users to edit them without viewing them.
3. Store the values encrypted using the `SECRET_KEY` as the basis and never let them out of the backend.

## Additional context

Looking for feedback @tiina303 @fuziontech @yakkomajuri

**Comment by macobo** [comment]
I'd suggest doing

> Never let those values out of the backend and just allow staff users to edit them without viewing them.

Only echo them back on creation. This feels like the standard practice for e.g. API keys nowadays.

**Comment by tiina303** [comment]
+1 to option (2). Also what GH seems to be doing.
