### ISSUE TITLE
Unable to clear event filter on events page

### ISSUE THREAD

**Issue by paolodamico** [PostHog/posthog#8798]
## Bug description

With the introduction of the taxonomic filter to the events page, we now have no way of clearing the event filter when you no longer need it.

![image](https://user-images.githubusercontent.com/5864173/156264049-f4978aea-e632-42b3-a3b0-f4220b537767.png)

## Expected behavior

Previously we had an "x" button to clear the selection

## How to reproduce

1. See screenshot above.

## Environment

- [x] PostHog Cloud
- [x] self-hosted PostHog (ClickHouse-based), version/commit: 1.33.0

## Additional context
- Originally reported by a [user](https://app.papercups.io/conversations/all/f908b90e-2288-4d43-8265-1050c7314f55).
- Unsure if this falls under @mariusandra (property filters) or @alexkim205 (events)

**Comment by clarkus** [comment]
Related ongoing work - https://github.com/PostHog/posthog/pull/8588
