### ISSUE TITLE
Testing improvement: Run tests at a different date

### ISSUE THREAD

**Issue by macobo** [PostHog/posthog#8807]
## Is your feature request related to a problem?

We often break our test suite when we forget to freeze_time and someone else needs to fix them the following day.

## Describe the solution you'd like

Run test suite with a different date than local time of developers, sussing out these failures earlier. 

## Describe alternatives you've considered

Perfect code reviews

## Additional context

cc @neilkakkar as the honorary last breaker of our test suite, mind taking a 30 minute look at this?

**Comment by neilkakkar** [comment]
I'll be honoured to
