### ISSUE TITLE
Wonkiness in person's event list (can't see events past 2 days ago)

### ISSUE THREAD

**Issue by paolodamico** [PostHog/posthog#8826]
## Bug description

If I open a person page ([example](https://app.posthog.com/person/IT7Ky4s2yVGC6qfAuXOKc8NSRx7nNI8fd4XV3d2Hss0#activeTab=events)) and scroll down all the way to the bottom, I can only see events up to 2 days ago.

<img width="1227" alt="" src="https://user-images.githubusercontent.com/5864173/156475144-7e95d1c1-9692-42cf-bab0-99f5e06a145c.png">

Yet there are clearly more events (see for example when filtering for a particular event we see events from 6 days ago and further),

<img width="1211" alt="" src="https://user-images.githubusercontent.com/5864173/156475165-c4739e13-0c51-477a-893e-7b19bc85724a.png">

Bug doesn't seem to be related to a max limit on pagination because I tested with a different user (mine) who has a lot of more events.

-------

Related but unsure if it's the same bug, there's some wonkiness with dates, see these two events examples from the same day (on all timezones) yet one event is shown as 2 days ago and the other as 3 days ago,

<img width="435" alt="" src="https://user-images.githubusercontent.com/5864173/156475270-8032e2b8-cea0-40b5-98de-216184b5bd76.png">

<img width="428" alt="" src="https://user-images.githubusercontent.com/5864173/156475274-0ff26f49-46b8-4fd9-97d7-99002cd78de9.png">

## Expected behavior

I should see all relevant events.

## How to reproduce

Detailed steps above.

## Environment

- [x] PostHog Cloud
- [ ] self-hosted PostHog (ClickHouse-based), version/commit: _please provide_
- [ ] self-hosted PostHog (Postgres-based, legacy), version/commit: _please provide_

## Additional context
Originally reported by [user](https://app.papercups.io/conversations/all/bd0d78af-9a2a-444d-be7c-9a52fd41c29e)

**Comment by neilkakkar** [comment]
Fixed by https://github.com/PostHog/posthog/pull/8813. 

The date wonkiness is tracked here: https://github.com/PostHog/posthog/issues/8833
