### ISSUE TITLE
Filtering by cohort on persons page does not work

### ISSUE THREAD

**Issue by paolodamico** [PostHog/posthog#8827]
## Bug description

When I filter the persons list by cohort, I still get the same list of users (i.e. all, no filters). Request seems to be sent correctly to the API, but the API is not doing anything about it. Seems related to the introduction of the taxonomic filter in this page.

See below. With and without filters, same results

<img width="449" alt="" src="https://user-images.githubusercontent.com/5864173/156476534-2b705e9c-7638-42ca-98fc-349b413b1ce2.png">

<img width="463" alt="" src="https://user-images.githubusercontent.com/5864173/156476540-5bda8a85-9aa5-4e3d-922b-e1b7c9ef866b.png">

## Expected behavior

Filtering by cohort should only show me users on that cohort.

## How to reproduce

See above.

## Environment

- [x] PostHog Cloud
- [ ] self-hosted PostHog (ClickHouse-based), version/commit: _please provide_
- [ ] self-hosted PostHog (Postgres-based, legacy), version/commit: _please provide_

## Additional context
Originally reported by [this user](https://app.papercups.io/conversations/all/f68c6a0f-9024-4938-9456-b434f36849ce)

**Comment by EDsCODE** [comment]
Restricted filtering to properties only now
