### ISSUE TITLE
Time descriptions can be wrong when returning to the events table

### ISSUE THREAD

**Issue by pauldambra** [PostHog/posthog#8833]
## Bug description

If you open the events table the items have a human description e.g. "2 minutes ago" 

If you leave the page open and then load new events in at the top of the table (at least with auto load turned on) we don't update the humanised descriptions so the first row can be "2 minutes ago" and the second "a few seconds ago" even though their timestamps are correct

![2022-03-03 11 19 52](https://user-images.githubusercontent.com/984817/156556825-d4ab4e47-4fc3-4079-8313-90c74ec2d2ae.gif)

## Expected behavior

the description of the timestamps makes sense

## How to reproduce

1. open the events page
2. turn on auto load
3. leave it in the background for long enough to receive new events
4. view the humanized descriptions

**Comment by Twixes** [comment]
Should be pretty easy to solve by rerendering `TZLabel` with an interval.
