### ISSUE TITLE
Calculate multi-line trends in parallel

### ISSUE THREAD

**Issue by macobo** [PostHog/posthog#8834]
## Is your feature request related to a problem?

If you have a trend with multiple lines, clickhouse queries for each are run one-after-another. If each takes 10s to calculate, then user will need to wait >30s in total.

## Describe the solution you'd like

Run queries in parallel.

## Additional context

cc @EDsCODE @neilkakkar This seems like a quick win query-api wise though not 100% sure on how best implement this. Would you be up for prioritizing this _next_ sprint?

**Comment by marcushyett-ph** [comment]
Naive question: Is there a risk with potentially running lots of expensive queries running in parallel they end up causing each-other to fail (due to peak resource consumption)?

**Comment by macobo** [comment]
I don't think so - the load should be comparable to normal parallelism from users doing queries or background cache refreshes. 

But if not too hard to hard, having _some_ limitation on parallel execution on this API call (e.g. no more than 5 queries at once) wouldn't hurt and still solve the 99.9% usecase.
