### ISSUE TITLE
Don't remove items from axis in dashboard bar charts

### ISSUE THREAD

**Issue by jamesefhawkins** [PostHog/posthog#8850]
## Is your feature request related to a problem?
Here is an example [dashboard item](https://app.posthog.com/dashboard/31961)

<img width="763" alt="Screenshot 2022-03-03 at 09 45 33" src="https://user-images.githubusercontent.com/47497682/156621879-bd8d307e-5004-4cbd-ac3a-eb944dacdbc7.png">

It's very hard to read this chart - you have to hover over individual items on the chart to see what they are.

## Describe the solution you'd like

Don't remove text from the axis labels if it's a bar chart

## Describe alternatives you've considered

Hover over items to see the URL (but these are usually cut off so are impossible to read)

**Comment by clarkus** [comment]
Related to https://github.com/PostHog/posthog/issues/8363
