### ISSUE TITLE
Instance Management Navigation

### ISSUE THREAD

**Issue by clarkus** [PostHog/posthog#8852]
## Is your feature request related to a problem?

In https://github.com/PostHog/posthog/pull/8790 we tried putting together some quick wins for instance management. After some discussion, we felt that the instance management links have outgrown the utility menu and justify their own set of controls.

Instance management is isolated to a subset of users. Not every user needs to see these controls. Let's optimize for those users and not burden the rest with things they don't need to see.

## Describe the solution you'd like

A separate global menu dedicated to managing an instance of PostHog. What does instance management entail right now?

- System status - are things working or not?
- Latest version and release notes
- Pending migrations
- Instance settings
- License management

[Rough (very rough) concept for how to pull this off.](https://www.figma.com/file/gQBj9YnNgD8YW4nBwCVLZf/PostHog-App?node-id=7868%3A70114)

<img width="541" alt="Screen Shot 2022-03-03 at 10 12 37 AM" src="https://user-images.githubusercontent.com/254612/156626239-2a812b56-77cd-455d-8e80-6d3e87a93b88.png">

## Describe alternatives you've considered

We've tried them, this is the latest attempt.

**Comment by tiina303** [comment]
Awesome - I like the separate menu idea, makes it much more discoverable.

Maybe we can consider using the gear icon instead of the blue instance settings below for consistency with account etc settings. Not sure if any titles/other items etc would need to change for that.

I also assume the second image just doesn't have the icons but they would be there for version etc? Note that Async Migrations could be the thing that needs immediate action & otherwise All systems could be fine.

**Comment by paolodamico** [comment]
I really like this concept! Related, I wonder if at this point it does make sense to either integrate all the instance pages (license, settings, internal metrics, status, async migrations) into a single page with tabs or if we want to separate them. Currently license and async migrations are separate.

**Comment by clarkus** [comment]
> I really like this concept! Related, I wonder if at this point it does make sense to either integrate all the instance pages (license, settings, internal metrics, status, async migrations) into a single page with tabs or if we want to separate them. Currently license and async migrations are separate.

Great question - @fuziontech and I talked about that. I think we need to solve for each individual problem and then work inside-to-out organizing them into a hierarchy. It could take a form similar to the recent settings redesign, or it could align with other page archetypes. It's hard to say until there's a better understanding of the fuller problem. I think a good next step would be an RFC for a fuller feature set. Based on that I bet we could crank out a full design in a day or two.
