### ISSUE TITLE
Counted by insights dropdown unintuitive for finding property aggregation

### ISSUE THREAD

**Issue by tiina303** [PostHog/posthog#8865]
## Bug description

Counted by insights dropdown leaves the impression that there aren't more options.

<img width="221" alt="Screen Shot 2022-03-04 at 15 56 19" src="https://user-images.githubusercontent.com/890921/156792174-5837a9dc-666d-438a-a90b-ef8fecb3c64c.png">

but there are:
<img width="216" alt="Screen Shot 2022-03-04 at 15 56 25" src="https://user-images.githubusercontent.com/890921/156792559-3d6f075d-0529-4efe-88f5-df77104be9be.png">

## Expected behavior

It's clear to the user that there's more options in the breakdown

## How to reproduce

1. open any insight & check the counted by dropdown

## Environment

- [x] PostHog Cloud
- [ ] self-hosted PostHog (ClickHouse-based), version/commit: _please provide_
- [ ] self-hosted PostHog (Postgres-based, legacy), version/commit: _please provide_

**Comment by clarkus** [comment]
This is something that is very affected by the browser and operating system the user is using. Scroll bars are great affordance for indicating the scrollable area of the list, but short of that we can try to indicate that there are more items by showing them as partially exposed. The exact same scenario came up in another [task](https://github.com/PostHog/posthog/pull/8854#issuecomment-1059409836). Check out that comment to see how we might improve this. This will also be impacted by ongoing work for nailing trends and behavioral filters.

**Comment by tiina303** [comment]
Can you assign this to the right engineer on the app team & partially exposed seems like a great solution.

**Comment by clarkus** [comment]
To get this ready for work: this component doesn't align with the other recently updated components. Step 1 would be to base it on a pattern common with other similar components we have in use. Then the core change would be to base the menu height on a multiple of the menu item heights. So for example, if you want to show 6.5 items and each item is 40 pixels tall, assuming no space between items the menu would need to have a max-height of 260px or some other relative unit that can be used to approximate size. 

I put together a quick update for aggregation options at https://www.figma.com/file/gQBj9YnNgD8YW4nBwCVLZf/PostHog-App?node-id=7982%3A39248. 

![Aggregation Options](https://user-images.githubusercontent.com/254612/157144364-501aa72a-c0f0-402f-aa90-faadaf597e4f.png)
