### ISSUE TITLE
Hobby script not working

### ISSUE THREAD

**Issue by narzero** [PostHog/posthog#8868]
## Bug description
Running `/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/posthog/posthog/HEAD/bin/deploy-hobby)"` completed successfully but can't get Posthog to actually start.

## Expected behavior
Should be able to get Posthog working.

## How to reproduce

1. Create fresh Ubuntu 21 server on Hetzner (16 VCPU, 32 GB MEMORY)
2. SSH to server
3. Run `/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/posthog/posthog/HEAD/bin/deploy-hobby)"`
4. Wait for it to finish
5. Visit domain, not working: chrome returns `ERR_TOO_MANY_REDIRECTS`
6. Visit {SERVER_IP}:8000, working
7. Press "Live implementation" button
8. Can't continue because of Celery failure
<img width="1280" alt="Screenshot 2022-03-04 at 22 17 42" src="https://user-images.githubusercontent.com/569810/156819498-1daa81df-d1f4-46df-8a86-95b7aae181ef.png">

9. SSH to server, run `docker-compose logs -f`

Content of step 3 hobby script at time of writing:
https://gist.github.com/narzero/be55df71aeafcde603cc6a914b384ed2

Full output of step 3 after running the hobby script:
https://gist.github.com/narzero/c8a24511ae4aab99274d3b51867acbbe

Full output of step 9:
https://gist.github.com/narzero/8e4806057ea3db8e5729f8ebea2f1649

## Environment

- [ ] PostHog Cloud
- [X] self-hosted PostHog (ClickHouse-based), version/commit: _please provide_
- [ ] self-hosted PostHog (Postgres-based, legacy), version/commit: _please provide_

**Comment by fev4** [comment]
Very similar issue with the `ERR_TOO_MANY_REDIRECTS`. Except when I visit `{IP}:8000` I don't get the Celery issue, instead I'm getting a warning:
![image](https://user-images.githubusercontent.com/16828078/166865731-7f1ef19e-3bf8-47e1-99f0-a8a2cce57c53.png)

Which I assume is normal since I'm not connecting through the domain.

For context I'm using 3GB instance, although I think at the beginning it should start without problem.

**Comment by guidoiaquinti** [comment]
👋 Hi! Super sorry for the late reply but I think this issue slipped under our radar. 

Can you please confirm if the issue still happening? We've recently made quite few improvements to our hobby setup. Thank you!

**Comment by fev4** [comment]
@guidoiaquinti hi! not working yet, getting this error
![image](https://user-images.githubusercontent.com/16828078/170401368-7a8af918-9f70-4c82-a111-1d6bcfafaa34.png)

I just re-ran the hobby script

Also, getting these errors on the console:
![image](https://user-images.githubusercontent.com/16828078/170401638-c41c2b70-92ec-4ff7-84ad-3c56b5c5f67b.png)

**Comment by guidoiaquinti** [comment]
Did you run the hobby deploy script from scratch? Unfortunately I can't repro your issue. 

From the first issue looks also that your DNS are misconfigured.

**Comment by fev4** [comment]
I managed to start from scratch and correctly set up everything with the latest hobby script.

**Comment by guidoiaquinti** [comment]
@narzero I'm closing this issue as I suspect the latest hobby script should be more reliable. Feel free to ping us here again or in https://posthog.com/slack if you need more support. Thank you!
