### ISSUE TITLE
Cypress Github Action Screenshots

### ISSUE THREAD

**Issue by mariusandra** [PostHog/posthog#887]
**Is your feature request related to a problem? Please describe.**
I'd like to see failed cypress screenshots when it fails via Github Actions.

**Describe the solution you'd like**
I'd like to see a link that I can click in the build output here that I can click:
![image](https://user-images.githubusercontent.com/53387/83143520-5b267c00-a0f2-11ea-8c64-8ea2d7e410fa.png)

**Describe alternatives you've considered**
Running cypress locally to replicate the issue. That does the trick, but it's great to just get the first visual clue directly when the test fails.

**Comment by Twixes** [comment]
We have them through artifacts 🚀
