### ISSUE TITLE
Confusing ux: It's unclear how recent insights are, when you've come from a dashboard

### ISSUE THREAD

**Issue by jamesefhawkins** [PostHog/posthog#8878]
## Is your feature request related to a problem?

If you're on a dashboard, you see something that shows how recent the data is:
<img width="654" alt="Screenshot 2022-03-05 at 12 46 19" src="https://user-images.githubusercontent.com/47497682/156899515-3ffd7614-0f92-4be3-bd33-5f24f64ceaeb.png">

If you then click through to an insight (perhaps to make it easier to read or to edit it):

<img width="987" alt="Screenshot 2022-03-05 at 12 47 40" src="https://user-images.githubusercontent.com/47497682/156899511-f2a507de-d0c2-413b-9a5f-f02570e24302.png">

I don't know if this is now showing recent data.

## Describe the solution you'd like

If an insight is viewed from a dashboard, we indicate that it is up to date (as I presume this refreshes it)

## Describe alternatives you've considered

Double check the dashboard versus Insight data by using the tooltips to make sure.

**Comment by Twixes** [comment]
We now show this info.
