### ISSUE TITLE
API for elements volume

### ISSUE THREAD

**Issue by timgl** [PostHog/posthog#888]
Create an API to get volume for all elements on a page

**Comment by mariusandra** [comment]
It would be cool if this API could return for a specified time period:
- The element selector (`div > bla:nth-child(4) > etc`)
- The $event_type attribute (`click`, `change`, etc)
- Number of times this event happened

This should be enough to show a basic heatmap and a list of top interactions.

**Comment by mariusandra** [comment]
Hi, I'm not sure how #917 closes this... and is that reverted now? In the current version of [the heatmap](https://github.com/PostHog/posthog/pull/974) I'm calling `/api/event/`, getting all `$autocapture` events and their associated elements for the current page and then consolidating that data client-side. Except for a lot of bytes transferred, this works quite well and I can build pretty nice tooling around it. 

Doing this filtering and consolidation server-side could yield some boost here, though I'm not yet sure where the limits of this approach are. In any case, I'm reopening this ticket.

**Comment by timgl** [comment]
My original idea was we could re-use the trends endpoint, then you could use something like simmer to send the correct selectors for every element. That also solved #419 where people wanted to be able to filter on random element properties.

It was reverted because it massively slowed down event insertion and nearly brought app down.

However looking at your comment I think you're absolutely right, it'll be much easier to just get a list of all elements for a specific page. I'll get on this today.

**Comment by timgl** [comment]
Update, have added this endpoint (/stats/) to #981. You can filter that endpoint using properties to filter on URL
