### ISSUE TITLE
Update cloud sign up pages with new visuals

### ISSUE THREAD

**Issue by lottiecoxon** [PostHog/posthog#8886]
Linking to #8582 - I have made some progress on designing new onboarding visuals for PostHog cloud. You can find the figma file [here](https://www.figma.com/file/HwUmk7WqccLkGgNNGAs4zN/Art-board?node-id=3819%3A22263) and I'll add some images below. 

I changed some of the copy ('Let's get you started on your analytics journey!') to fit with the visual of a hiking hedgehog with a map- I think it's fun. Let me know any feedback you have and if not too much hassle, maybe I could oversee how this would be coded in- (dependant on how complicated).

**Comment by lottiecoxon** [comment]
![preflight - 01](https://user-images.githubusercontent.com/65415371/157023550-f5637f82-50ff-491e-9a92-96a713d5230f.jpg)
![preflight - 2](https://user-images.githubusercontent.com/65415371/157023568-11e4ef05-3fba-4481-9db8-6a4827da7a9c.jpg)
![preflight - 4](https://user-images.githubusercontent.com/65415371/157023571-9c8dd3df-e28f-484f-82bc-7e151a130f57.jpg)

**Comment by liyiy** [comment]
excite!

**Comment by lottiecoxon** [comment]
After some time and thought I was wondering if I could have another stab at this to make it a little less hedgehog illustrative and more on brand and spark joy-ish

**Comment by liyiy** [comment]
Yep there's definitely room for changes here. I haven't gone too far deep into these updates yet. Time wise though I do want to get most of these updates coded in by the end of next week, if you're able to get those design changes out before early next week that would be ideal 😄 But if not, happy to implement what we have now and the new changes in the next iteration of onboarding 

note:
The onboarding flow for cloud vs self hosted is a little different so those pages don't actually show up on posthog cloud, I would encourage you to try signing up on PostHog on a different account maybe and going through the flow too (and also for Amplitude, MixPanel, Pendo, etc) . And to also take a look at Onboarding 1's RFC just to gather more context on other problems we'd like to solve for the flow: bookmarklet option is not clicked on enough, there's no clear "invite teammate" step, etc, if you're up for a challenge

**Comment by corywatilo** [comment]
Is this issue part of the onboarding work? (Just want to make sure this one doesn't slip through the cracks!)

**Comment by liyiy** [comment]
@clarkus @rcmarron Lottie wanted to re-do the mocks for these and I think she did in figma but i'm not 100% sure about where we landed afterwards but I think this is in a fine state? It's definitely part of onboarding work and Rick is working on it but I'll defer to chris if he has more information on the specifics here or we can wait until Lottie gets back on Thursday 😸

**Comment by lottiecoxon** [comment]
Hey so for the moment lets go with the stripped back version with fun hedgehogs - the previous design with full colour background feels childish and we would pretty soon grow out of this I feel. My long term aim is probably to have some small animations incorporated into the hedgehogs: e.g. butterflies around the hiker hog, or test tubes smoking with the experiment hog. This won't take too much attention from the main text but still hint at some fun - aka spark joy. @liyiy I will tag you on Figma to the correct files, but I can send the static hedgehogs over to you in PNG form if that helps!
