### ISSUE TITLE
Make Person properties editable on the frontend

### ISSUE THREAD

**Issue by timgl** [PostHog/posthog#89]

**Comment by cr33dx** [comment]
Hi, i'd like to work on this enhancement.

**Comment by Twixes** [comment]
Sure, have a go at it! @cr33dx Do write if you need any info here. When done, make a pull request so that we can make your changes a reality!

**Comment by cr33dx** [comment]
Hi when i try to use the development docker-compose the ui won't show up.
using chrome it's making requests to for css.
 
http://0.0.0.0:8234/static/main.css

**Comment by Twixes** [comment]
It might be that you need to wait a minute or two for the frontend to build. Does it start showing up after a while?

**Comment by cr33dx** [comment]
How do i see if the front end has build?

**Comment by cr33dx** [comment]
Hi so i had PH working thanks to @yakkomajuri 
so i guess we want the people tab -> All users ->Person 
The details of person to be editable?

**Comment by Twixes** [comment]
That's right @cr33dx. `Person.properties` in Django ORM.

**Comment by cr33dx** [comment]
#1491

**Comment by cr33dx** [comment]
#1491
