### ISSUE TITLE
Understanding plugin server backpressure

### ISSUE THREAD

**Issue by yakkomajuri** [PostHog/posthog#8921]
This issue is a write-up of the work the ingestion team has been doing on the plugin server regarding ingestion scalability and reliability, in order to share context, provide visibility into the work, and help others understand the problem space (cc @fuziontech).

## Problem

Broadly, the problem we set out to solve was flakiness in ingestion. 

More specifically, we decided to focus on backpressure, which we've defined as the difference between the number of events sent by the django server and the events processed by the plugin server in a given range of time. 

This metric gives us an idea of how well the plugin server is keeping up with the load. If backpressure is high, the plugin servers are not being able to process all the load in a timely manner.

## Relevant factors

Given the following simplified definition:

```
backpressure = events_received_in_django_server(interval) - events_processed_by_plugin_server(interval)
```

Then we can see how for backpressure to increase, assuming the other variable remains constant, we need to either be receiving more events or processing fewer events.

Given we cannot control how many events we receive (well, we can, but we shouldn't), we need to only focus on one aspect of this equation: the plugin server ingestion rate.

<details>

<summary><b>Side note: measuring backpressure correctly</b></summary>
<br />

It's important to mention that we've been relying on a faulty backpressure metric this entire time. I'll write up a separate issue on this, but effectively:

- We were using metrics incorrectly (comparing `timing` with `increment` metrics without regard for aggregations)
- We were not taking into consideration: failed events, events dropped from plugins, and dead letter queue events 

Appropriately measuring this made the picture much better than it seemed with the previous metric.

</details>

## Addressing issues affecting ingestion rate

It's important to note that when we see spikes in graphs relating to the plugin server, it is tempting to think that there's _one thing_ we're missing - some root issue.

In reality, things are a lot more complex. So, here's a summary of fixes shipped that have a positive impact on ingestion rate and a brief explanation of why.

### Stateless plugins (#8112)

Based on today's numbers, stateless plugins reduced the number of GeoIP VMs needed on Cloud from 4172 to a constant total of 1.

Beyond **massive** memory savings, this is a fix that contributed to cutting by a factor of 3-6 the mean time for a fresh plugin server instance to be ready to ingest events.

#### Why does this affect backpressure?

Particularly prior to #8819 / #8857, we'd see backpressure spikes during deploys as ECS would kill old tasks when it had spun up the new ones, but the new ones would still be unable to ingest events for up to 5 minutes. Reducing the time to being fully ready to ingest events reduces that impact.

Additionally, on GeoIP updates, we now only have to re-launch one single VM, with almost negligible impact. Previously, re-launching (teardown + setup) thousands of VMs would slow down ingestion.

### Readiness endpoint (#8819 / #8857)

As mentioned above, deploys would always halt our ingestion for a bit while the new plugin server instances were getting ready for ingestion. By adding a readiness check, we ensure ECS (and soon helm) don't flip to the new tasks/pods until they're truly ready.

#### Why does this affect backpressure?

Only switching to the new tasks when we're actually ready ensures we reduce ingestion downtime during deploys.

### Lazy plugin reloads (#8578)

Since the beginning, the plugin server has aimed to operate "lazily" with plugin reloads. If _one_ plugin changed, we should only re-launch VMs for that _one_ plugin. However, that's not what was happening. 

Due to a bug, we were tearing down and setting up again **all** VMs (multiple thousands on Cloud) any time "check for updates" was clicked in the PostHog UI.

Now, we never reload VMs on a click of that button, and only reload plugin VMs of plugins that have absolutely changed.

#### Why does this affect backpressure?

Any time "check for updates" was clicked we would hold up ingestion while plugins were being set up.

### VM setup optimizations (#8609 / #8694 / #8596)

There were many suboptimal things we did when setting up plugin VMs. These included:

1. Loading the full plugins schedule twice on every startup
2. Loading all VMs immediately irrespective of need
3. Unnecessary operations on VM setup

By introducing checks and a sprinkle of laziness, we now only load things if we really need to.

#### Why does this affect backpressure?

Being more "lazy" ensures we have faster deploys, faster plugin reloads, use fewer resources, and spend less time blocking the event loop from doing more important work. All of these are factors that affect ingestion directly.

For example, we only set up a VM for a plugin with `processEvent` only when an event comes for it. If the team has stopped using PostHog, that VM will never be setup, whereas we used to unnecessarily set it up and have it ready at all times.

### setupPlugin retries refactor (#8900)

When #8900 lands, we fail at the `setupPlugin` function defined by the plugin, that's the only thing we'll retry again. Currently, we re-do the entire VM setup process, which can hold us back on all threads if a plugin (or its config) is permanently broken.

Immediate mitigation changes like #8526 and #8820 helped reduce the load from retries, and #8829 is the next step here.

#### Why does this affect backpressure?

Around a week ago a user was setting up the Snowflake plugin with an incorrect config, meaning the plugin would always fail on startup.

Both through our retries mechanism, and through the user consistently updating the config, we ended up using up a lot of our resources on the workers (we saw quite high CPU spikes), just trying to get this plugin set up, and thus held back ingestion.

With the naive buffer in #8820 and the upcoming #8900 we can ensure that a single broken plugin has very limited impact on the server(s) overall.

### Removing the status report (#8534 / #8778)

We used to collect metrics (that we weren't using) and send them to PostHog every hour. To do this, we triggered a job for every worker on the entire cluster at the same time to flush the metrics to PostHog. Doing so took up resources and slowed us down across the board.

We've now removed it and if a similar system is re-introduced, we should consider the load it adds, as well as ensure we add jitter to the schedule.

#### Why does this affect backpressure?

Every hour on the dot our workers would get a little extra busy flushing events to PostHog, lowering their ability to do other work (like ingesting events).

### Extra: Control mechanism for voided promises (#8573)

A lot has already been explained here: #7755.

#### Why does this affect backpressure?

Being able to control how many voided promises a worker has at once ensures we don't overload workers and can distribute work more evenly across threads.

**Comment by hazzadous** [comment]
Not too important, but would latency be a more directly user relevant metric to be focusing on? We could, for instance, be receiving the same number of events in django and plugin processing, but latency could be a day which I don't think would be desirable. Latency wouldn't pick up on if we weren't processing anything, so max age of event in the queue is probably a good catchall.

For myself if anything: I assume if we can get the required plugin server throughput then we can keep latency low. To get the throughput we can:

 * scale horizontally
 * optimize event processing
 * scale vertically

We also have the issues of:

 * throughput variance for a single instance of the plugin server is high, with all the plugin and VM reloads
 * throughput variance is high on deploy

Like I said, mainly just trying to get my head around the problem.

**Comment by yakkomajuri** [comment]
I 100% agree - I think the reason backpressure became a focus is because historically we've paged on this and it has been a good predictor of issues. 

It was a nice North star to tackle plugin server issues, but 1000% latency is the thing to focus on. Hence our 6 month and 3 year goals talk about latency. 

This sprint was valuable to evaluate our historical approach to plugin server performance and led to a nice cleanup, but I intend to not revisit this and would like to just focus on latency from now on.

We'll probably completely switch over to latency alerts etc once we have a good grasp on how we should measure it and some sensible alerts.

@hazzadous
