### ISSUE TITLE
Add same insight to multiple dashboards

### ISSUE THREAD

**Issue by rgibelli** [PostHog/posthog#8933]
## Is your feature request related to a problem?

*Please describe.*

## Describe the solution you'd like
The ability to add a given insight to multiple dashboards

## Describe alternatives you've considered
Duplicating them, but it gets out of control fast as soon as you have 3+ dashboards

## Additional context
Some times the same insight can be used on multiple dashboards, for instance an specific test dashboard, monitoring, etc.

**Comment by TonySci** [comment]
I agree! your docs actually state that insights can be used on multiple dashboards too! https://posthog.com/docs/user-guides/dashboards 
![image](https://user-images.githubusercontent.com/94004058/160680056-8430a759-7b7b-4666-8be6-5f76ca13c8c2.png)

**Comment by kprimice** [comment]
Up!

**Comment by pauldambra** [comment]
Hey, @rgibelli @TonySci @kprimice we're actually working on that right now. 

I'll tag here again when it is released

**Comment by pauldambra** [comment]
This has been released to beta users now

**Comment by pauldambra** [comment]
This was released in v1.36.0
