### ISSUE TITLE
Insights doesn't seem to support counted by device

### ISSUE THREAD

**Issue by inbreaks** [PostHog/posthog#8938]
## Is your feature request related to a problem?

In the product analysis of mobile apps, a device may have multiple accounts registered. This case helps marketers analyze the real number of registered devices. Currently counted by device doesn't seem to be supported in insights

#### *Thank you* for your feature request – we love each and every one!

**Comment by neilkakkar** [comment]
Hey @inbreaks, 

We do support this using Group Analytics: https://posthog.com/docs/user-guides/group-analytics. The basic idea is that you define what a group is (like device), and then all insights have this option to aggregate by group.
