### ISSUE TITLE
Attach notes to a user

### ISSUE THREAD

**Issue by sdgandhi** [PostHog/posthog#8949]
## Is your feature request related to a problem?

no

## Describe the solution you'd like

In the person detail view I would like a tab to enter notes/comments on a timeline so I can basically use as a CRM system, I could ditch my CRM and just use PostHog bc all the data is right there!

## Describe alternatives you've considered

Notion CRM templates

## Additional context

I ❤ PostHog

**Comment by jamesefhawkins** [comment]
Related to #2880
