### ISSUE TITLE
Recordings auto-play

### ISSUE THREAD

**Issue by sdgandhi** [PostHog/posthog#8950]
## Is your feature request related to a problem?
No

## Describe the solution you'd like

An autoplay button on the recordings page that queues up all unwatched recordings ordered from earliest. Give me keyboard shortcuts (up down to speedup/slowdown), left right to skip back forward 10 seconds, and shift left right to skip to next recording. Space to pause. N to add a note/comment.

## Describe alternatives you've considered

I thought about writing a chrome extension that does this but no time :)

## Additional context
 I ❤️ PostHog

**Comment by daibhin** [comment]
Session Replay now supports autoplay!
