### ISSUE TITLE
Use new duplication icon across app

### ISSUE THREAD

**Issue by liyiy** [PostHog/posthog#8974]
Replace current duplicate icons like 

<img width="543" alt="Screen Shot 2022-03-10 at 1 50 09 PM" src="https://user-images.githubusercontent.com/25164963/157734041-58f0392d-2b66-4197-a953-1bca8b48f9a9.png">

with

<img width="591" alt="Screen Shot 2022-03-10 at 1 47 59 PM" src="https://user-images.githubusercontent.com/25164963/157733686-d3636df6-62c6-4df8-93c5-ae0d4093a21b.png">

**Comment by clarkus** [comment]
SVG here 
![duplicate](https://user-images.githubusercontent.com/254612/157734302-8992f27f-5bab-4519-9853-df55d9fb4944.svg)

**Comment by Twixes** [comment]
For context, this is in `icons.tsx` as `IconCopy`. `IconDelete` for the trashcan. And we don't have a filter icon I think. 🤔

**Comment by liyiy** [comment]
We're just slowly reproducing material's icon library in our icons file 😁

**Comment by clarkus** [comment]
Hide and show filter icons 🎉 
![show-filters](https://user-images.githubusercontent.com/254612/157765964-65651d7b-6a91-45fb-b55d-57f2ba00b2c1.svg)
![hide-filters](https://user-images.githubusercontent.com/254612/157765967-ffaaa833-fef5-41f1-a8e5-f536bef61790.svg)

**Comment by Twixes** [comment]
That's true @liyiy! And not ideal, with `icons.tsx` getting larger and larger. I've been looking for a library that would have this all ready, but they're all deficient (either requiring a whole new Material UI library, or bad at TypeScript, or the icons are differently sized from the originals), so I'm working on a lightweight package that will just compile them all for us.

**Comment by clarkus** [comment]
I do deviate from material icons in some ways and in some cases we do have custom icons. I am in favor of building up our own set over just plugging in something else. I think it should be easy to reference and use our SVG icons, but I don't want the set dictated by an external source and I don't want icons included that we're not actively using in the product. Before we do too much here, I'd like to discuss the problem and ensure we're all aligned on a direction.
