### ISSUE TITLE
Andrew

### ISSUE THREAD

**Issue by Abesyuffcjk** [PostHog/posthog#9001]
## In what situation are you experiencing subpar performance?

*Please describe.*

## How to reproduce

1.
2.
3.

## Environment

- [ ] PostHog Cloud
- [ ] self-hosted PostHog, version/commit: _please provide_

#### *Thank you* for your performance issue report – we want PostHog to go supersonic!

**Comment by macobo** [comment]
@Abesyuffcjk this ticket does not contain any context. Can you elaborate what's the issue you're having?

**Comment by Abesyuffcjk** [comment]
My bad sorry.
