### ISSUE TITLE
Beautiful initial onboarding experience

### ISSUE THREAD

**Issue by EDsCODE** [PostHog/posthog#901]
Currently, users are learning how to use Posthog either through a customer onboarding call that we run or through personal experimentation along with the docs online. As @jamesefhawkins noted, the analytics functionality (trends/funnels/paths) are very clear and powerful, but the event and action manipulation/creation is unclear and longwinded to achieve. 
<img width="691" alt="Screen Shot 2020-06-01 at 11 50 33 AM" src="https://user-images.githubusercontent.com/13127476/83427065-2110ef00-a3fe-11ea-8f02-804f77fcec89.png">
**users may not have cared to make an action after initial sign up, but for clarity, users should be encouraged to make some sort of action to make sure the concept clicks because without actions you're pretty limited in how to use the autocaptured elements

**Goal:** Create an onboarding flow that clearly demonstrates what an action is, how to create them, and how to use them alongside everything else. We're focusing on creating actions because the other functions of the app are quite intuitive once the actions are formed

**Possibilities: (WIP mockups to come)** 

1.  Extend the current initial sign in page that guides users to installing the snippet. After the snippet is installed, there could be a follow-up landing page/tooltip that has next steps for using events/actions
2. A helper wizard on each page of posthog dashboard that's universally clickable for help. For example, if you're on the actions page, you could click this helper and select an option to show you how to create an action and then follow the guide. This is much less obstructive than a mandatory initial onboarding flow
3. Socialization: Up until now we don't really have a concept of a team/other team members viewable in the dashboard. I've never come across a socialized onboarding especially for sass tools but a possible idea to toy with his creating a standard journey onboarding (bullet points, a few tasks to fulfill, progress meter) and alongside that show how many other people on your team have completed this. The incentive might drive each other to actually make it through onboarding completely/make sure you give it a try because your teammates have

**Comment by EDsCODE** [comment]
**Conventional User Tour onboarding draft**
This would be along the lines of extending 1
<img width="998" alt="Screen Shot 2020-06-01 at 9 35 34 PM" src="https://user-images.githubusercontent.com/13127476/83470388-11ba9180-a450-11ea-8e2b-3d0936c9ed2c.png">
<img width="1008" alt="Screen Shot 2020-06-01 at 9 35 42 PM" src="https://user-images.githubusercontent.com/13127476/83470391-13845500-a450-11ea-8407-2ea6a5a4cee7.png">

**Comment by fuziontech** [comment]
I really dig the call to action for the tour and the tour being a checklist. I feel like it strikes the right balance between being helpful and being too invasive and annoying.

**Comment by jamesefhawkins** [comment]
Feedback:

i) it's definitely a good thing you're thinking about how to get this right!
ii) I think this would look better if you darkened the background behind the popup tooltips - ie the explanation of actions doesn't stand out that much.
iii) If you are going to walk someone through a tutorial, I guess it should be fairly complete - ie not just snippet then actions. Actions aren't useful by themselves but they are once you need funnels, for example.
iv) A progress bar (step x of y) on the tutorial probably helpful, although we should probably have a skip option so we don't annoy developers or power users
v) We could add a "X% setup" type notification at the top if people skip the setup process (again, needs to be dismissible)

**Comment by EDsCODE** [comment]
addressed in many other forms
