### ISSUE TITLE
Insight view/edit mode UX questions

### ISSUE THREAD

**Issue by mariusandra** [PostHog/posthog#9014]
## Bug description

Now that we're doubling down on having simple insight URLs, here are some new UX quirks that need to be looked at. There are enough quirks, that it makes sense to look for a common solution. None of the issues are what I consider urgent, though they can be annoying if you run into them. Usually a fast reload fixes everything.

- We should improve the display of "you have unsaved changes" in an insight. Here's a [rough WIP PR](https://github.com/PostHog/posthog/pull/8993). Here's the latest suggestion, still to be implemented:
<img width="1061" alt="Screen Shot 2022-03-11 at 12 06 15 PM" src="https://user-images.githubusercontent.com/254612/157951885-e2d395d3-1b46-4d70-bba5-024bb4158e2e.png">

- Changing a date filter toggles the "you have unsaved changes" mode in the "view" mode with no way to save those changes. The same happens when you toggle a legend or change the chart type.
![2022-03-14 13 53 25](https://user-images.githubusercontent.com/53387/158176223-43ec6d3d-9161-429f-8de6-a25f6d334537.gif)

- View mode -> Click edit -> Make changes -> Click back. It's surprising to find the unsaved changes still in view mode.
![2022-03-14 13 55 38](https://user-images.githubusercontent.com/53387/158176454-925b1c6e-ef14-4b8e-bb38-a046add85ace.gif)

- Going one step further, the view/edit mode doesn't jibe well with dashboards either. When you edit an insight, and go back to the dashboard with that insight, its state is uncertain.
![2022-03-14 14 12 52](https://user-images.githubusercontent.com/53387/158178955-b9dd02cd-1b97-4046-b249-789fce5283f7.gif)

## Expected behavior

We either need to move towards being more explicit about unsaved state (it should be uniformly obvious that an unsaved insight is unsaved in all the dashboard item, insight view and insight edit modes), or we need to autosave everything, together with a history of changes that lets us revert easily.

Let's not rush into a worse solution, and figure out a clean way forward @clarkus @marcushyett-ph @paolodamico @rcmarron (and whoever else is interested).

## More questions

- Should we disable the back button between insight view and edit modes, so "list -> view -> edit", clicking back will take you to the insights list instead of "view"?
- I'm not a fan of blocking the user's navigation with a "you have unsaved changes! stop?" dialog. It's actually tricky to implement well in a single page application. Can we avoid solutions that feature this? It's doable, but it'll have some tradeoffs.
- I might not want to edit an insight, but would like to play with a copy. Should we make cloning insights a first class citizen? What about locking edits? There's already a hidden clone button. CMD+click on any of the tabs, and we clone the insight and open a new one in a new tab.
- Could we design the interface in such a way that filters, and unsaved filters, are automatically obvious? E.g. surround all changes a blue border.

**Comment by marcushyett-ph** [comment]
I'd lean on @clarkus experience for the specifics here.

My 2 cents are:
1. Autosave might create a lot of side-effects (when people are just tweaking or testing out some variations on an insight)
2. Cloning when you make an edit is a common pattern I've seen elsewhere (e.g in Metabase), to protect the original insight, however - metabase also persists some metadata in the URL so you can share an unsaved insight. Although their UI for highlighting an insight is unsaved is probably a little too subtle for me personally

<img width="788" alt="image" src="https://user-images.githubusercontent.com/85295485/158354938-de1666e7-31f0-480d-a230-2ace3efda196.png">

**Comment by clarkus** [comment]
I am still working on this, but wanted to stress that a dialogue prompt is one of our most effective tools for ensuring users don't lose work. Even with the other affordance, if a user tries to navigate away from a "page" we should be able to prompt them to ensure they don't lose work. This is a super established pattern across product interfaces, it's disruptive but that's the intent. It's forcing a decision when we can't infer one otherwise. I am still working on improvements for this, but I don't think we should remove a dialogue from the scope of solutions.

**Comment by clarkus** [comment]
I have a concept in figma for discussion at https://www.figma.com/file/gQBj9YnNgD8YW4nBwCVLZf?node-id=8302:73359#166721504. The change is to focus the communication of page state via the primary page action. When no changes are available to save, the button will reflect that state. This pattern uses a disabled component which is a very tricky area usability-wise. I think it's critical that we communicate immediately why the button is disabled and have it update as soon as changes are able to be saved. 

<img width="986" alt="Screen Shot 2022-03-17 at 12 59 58 PM" src="https://user-images.githubusercontent.com/254612/158885636-aeaed755-ebbb-4655-81a4-d10971f5f95d.png">

> Should we disable the back button between insight view and edit modes, so "list -> view -> edit", clicking back will take you to the insights list instead of "view"?

I think we can avoid this. I'm not a fan of overriding a user's browser controls in general. 

> I'm not a fan of blocking the user's navigation with a "you have unsaved changes! stop?" dialog. It's actually tricky to implement well in a single page application. Can we avoid solutions that feature this? It's doable, but it'll have some tradeoffs.

I see the technical constraints here. An undo action might work, but it feels too passive to me. Toasts are meant to be very low priority notifications and this is potentially a lot of effort that could be discarded. I think it'd be good to dig into the constraints and identify a path forward. We have to work with what we have, so it's mostly a matter of really understanding this constraint. 

> I might not want to edit an insight, but would like to play with a copy. Should we make cloning insights a first class citizen? What about locking edits? There's already a hidden clone button. CMD+click on any of the tabs, and we clone the insight and open a new one in a new tab.

We have duplication actions on the list view. We should bring that into the read only view as well. Duplicating before you make an edit is a safe way to create a version that doesn't interfere with dashboard usage or anything else. 

> Could we design the interface in such a way that filters, and unsaved filters, are automatically obvious? E.g. surround all changes a blue border.

We use blue borders to communicate focus now. I think the state of the page needs to be communicate at a page level. If we were saving each section of attributes separately, we could communicate state there, but it feels off target to me based on how this is working now.

**Comment by mariusandra** [comment]
To be clear, this header with the changed buttons should be there for both the view and edit mode? Correct me if I'm wrong, but according to this, if I'm on the view mode and change the date range, the header will also switch to the "cancel / save" buttons? Then "save" -> back to normal view mode buttons... and "cancel" -> discard changes and back to normal view mode buttons.

**Comment by clarkus** [comment]
Those are distinct states above. I'll itemize to clarify

- **Read only view**
  - Primary action: Edit
  - Secondary action: Add to dashboard / on dashboard / etc
  - Tertiary menu of actions: duplicate, add to favorites, copy url, delete. This is a subset of the inline menus used in the list view

- **Editing - no unsaved changes**
  - Primary action: Disabled with a clarifying message "No changes to save"
  - Secondary action: Cancel - cancels edit action and returns to the previous context
  - Tertiary: nothing

- **Editing - unsaved changes**
  - Primary action: Enabled with a "save" label. This could be amended for the https://github.com/PostHog/posthog/pull/9045 case - "Save & add to dashboard"
  - Secondary action: Cancel - cancels edit action, discards changes, and returns to the previous context
  - Tertiary: nothing

> If I'm on the view mode and change the date range, the header will also switch to the "cancel / save" buttons? Then "save" -> back to normal view mode buttons... and "cancel" -> discard changes and back to normal view mode buttons.

I don't think a date range change should qualify as an edit action from the read only view. It's a temporary exploratory change that doesn't really modify the underlying insight definition. It's the case where a user just needs to see a broader or narrower time frame to answer a question. If the user wants to make this change permanent to the insight, that needs to happen via editing. This is a pretty common pattern in other analytics tools, so I think users will expect some ability to explore time ranges without having to edit. Does that make sense? 

I get that there are some technical constraints here, so maybe offering date controls on the read view is the core problem? If those are only usable in an editing context, they shouldn't be on the read view until we can support that temporary time adjustment.

**Comment by mariusandra** [comment]
> It's a temporary exploratory change that doesn't really modify the underlying insight definition.

That's the problem: it does. Same with changing a line chart into a bar chart in trends editing mode or using any of the other filters here:

<img width="1192" alt="Screenshot 2022-03-18 at 16 42 07" src="https://user-images.githubusercontent.com/53387/159035181-7d5516e8-a16f-4182-a06e-a7fb17df841b.png">

These and the other things you can change in edit mode all change new properties in one `filters` object. That is then not persisted until you click "save". The view mode now also supports unsaved changes to filters. 

This has implications for when update any of the filters, and then switch to edit mode.

**Comment by clarkus** [comment]
Can we make is such that these are just temporary filters applied to this saved insight? I'm trying to avoid having a user create an entire new insight just to see an expanded range of time. The power is in the query definition - which events, properties, filters etc are used to structure my data. I see the time attributes as secondary... they have to exist for the core isnight, but they could be adjusted in a non-permanent way to facilitate exploration. If a user needs to edit and save the insight every time for quick analysis, we're going to have a lot of unused insights laying around. Part of the value of saved insights is that I don't have to go rebuild every time I want to see a slightly different range. Maybe I just don't understand how saved insights are working.

**Comment by marcushyett-ph** [comment]
From my own personal experience. I often want to explore an existing insight and I feel nervous over whether I've "Messed up someone else's important insight", it would be great if I could tweak the date range without kicking off those nerves (by going into edit mode).

It looks like date ranges are changed slightly more frequently from view mode than edit mode, so this [pattern seems pretty common amongst our users too](https://app.posthog.com/insights/jAAybqnE).

Also +1 to @clarkus on creating lots more insights. Ideally an organization would have the least possible number of insights - one of our customers mentioned having a small vocabulary (of insights / events) meant everyone was super confident what the "truth" and "most important" thing is.

**Comment by mariusandra** [comment]
> Maybe I just don't understand how saved insights are working.

What you describe sounds reasonable, yet the current technical limitations want us to consider something slightly different. Let's try to figure out what changes are needed. I have some proposals below, and will go deep in explaining the constraints before. Some of this might need to be worked on as part of the "[Dates, insights, dashboards](https://github.com/PostHog/product-internal/pull/290/files#diff-9ca4651fbd230df512bf2b742648af0c5399eb81bd65b01ff8f16bfff9d99e18R30)" section in the RFC.

Currently an `insight` is an object stored in the database with the following fields:
- an `id` and a `short_id` (what you see in the URL)
- `name`, `description`, and other metadata
- a set of `filters`, which include things like the insight type, the date range, global property filters, funnel steps, etc

Here's an insight from app with the relevant parts masked out:

<img width="573" alt="Screenshot 2022-03-18 at 20 43 56" src="https://user-images.githubusercontent.com/53387/159073389-d6fb2a33-1927-47e0-8ece-7dd593be98ca.png">

Pay attention to the `filters`, they contain `date_from` and `date_to`. Also `interval`, but it's probably not as relevant for the discussion below.

Every time these dates change, it's a new set of `filters` and a new `result`. 

> Can we make is such that these are just temporary filters applied to this saved insight? 

Yes, but with a caveat that they might still be accidentally saved. For example:

- Open an insight in view mode, it loads with saved filters of "last 30 days".
- Change the date range to "February 2022". Now the `filters` object changed and is unsaved.
- Click "edit", make unrelated change X.
- Click "save".

Your change X is saved, but so is the date filter change to "February 2022". 

If this insight is on any dashboard, the range will have changed there as well. Conversely, somebody updating the global date filter on a dashboard will change the date filter back on this individual insight again.

Pretty crappy if you ask me.

What if we instead completely removed date filters from all insights? Could we do it, or do we still need to save some default?

In this scenario, both the `date_from` and `date_to` filters would be saved in your browser session, and always sent as part of the API requests when fetching insight results. Dashboards would have their own global date ranges that also apply when fetching results. This simplifies some things, but brings other questions, like a) what about overrides or special cases like a funnel that's too slow to calculate for the last year and needs to be set at 30days?, b) what happens to the browser's stored date range if you click on an insight on a dashboard that has a different date range, c) will everyone see something slightly different, and how will this affect caching/performance?

Regarding these points:

> I often want to explore an existing insight and I feel nervous over whether I've "Messed up someone else's important insight", it would be great if I could tweak the date range without kicking off those nerves (by going into edit mode).
> If a user needs to edit and save the insight every time for quick analysis, we're going to have a lot of unused insights laying around.
> Also +1 to @clarkus on creating lots more insights. Ideally an organization would have the least possible number of insights

What about an "edit copy" or "edit as new" or "duplicate" or "new from" button?

Currently if you click "new insight", we literally create a new insight in the database, and let you edit it. Only when you save, it'll show up in the saved insights list, but it'll already be in the database.

If you edit an existing insight, you have three options. 1) Edit and be really careful, 2) Edit, "save as", and then edit the clone to be sure you won't make mistakes. Then delete the clone. 3) CMD+click on any of the tabs (trends, funnels), and we will open a cloned new but unsaved insight with those filters applied. You can play with this as much as you want without fear of saving the old insight. Quite quirky and undocumented, I know. 

Exposing an "edit copy" button would expose cmd+click trick to everyone.

As an additional suggestion, what if when you click "new insight", we do not actually save a new insight in the database, but leave the user on a `/insights/new` page, much like we don't also create and redirect you to a new feature flag when we open `/feature_flags/new`? This way, "edit as new" will actually keep the page on `/insights/new`, and without saving again you'll feel safe you're not messing up someone else's insight.

The old behaviour (`/insights/new` -> `/insights/actually_new_short_id`) was there to address some technical limitations that we don't really have anymore. We could get rid of this and have an actually unsaved new state if we want to.

...

Plenty of ramblings above. Hopefully some idea in there is worth implementing, and the extra technical context helps with design.

**Comment by clarkus** [comment]
Thanks for the super thorough summary of things. I think duplication is part of the solution in some cases, but I don't think we should make users do this every time they want to see an expanded date range or temporarily adjust the format of a chart. 

Here are the attributes I think that could be temporarily adjusted while not changing that underlying, core insight definition: `date_from`, `date_to`, `display (chart type)`, `interval`, and possibly more based on type. If we allow those "formatting" attributes to be overridden or inherited from another context, it won't change the underlying core structure of that insight - the events, properties, filters, etc are all still preserved and should return as the original author intended. The user is just formatting those results differently or applying them to a broader time range. They're still answering the same basic question, just adjusting the output to be more or less specific to the things they care about. 

I'm trying to find a better way to describe this, but coming up short. I think there's more to it, so I will keep thinking and respond here if I find a better way to describe the idea.

**Comment by mariusandra** [comment]
What should happen in this scenario: 
1) open insight in view mode
2) change the date filter and the interval
3) click reload 

Should we 
1) display a "you have unsaved changes" dialog and prevent the user from reloading
2) reload and show the same insight with the saved filters
3) reload and show the same insight with the updated filters

My vote goes to option 2. Option 3 is unexpected (autosave that doesn't really save and is not indicated), and option 1 can get annoying since you might just be changing some date filters.

----

Then this scenario:
1) open insight in view mode
2) change the date filter and the interval
3) click "edit"
4) ???
5) click "save" 

I propose that during step 4, we show something like the grey line here (ignore the top two buttons):

<img width="1061" alt="157951885-e2d395d3-1b46-4d70-bba5-024bb4158e2e" src="https://user-images.githubusercontent.com/53387/159226183-fc4d5d12-3ba8-4dad-95d4-4688e4e0e260.png">

If you hover the underlined "unsaved changes", you see a popover with a list of changes that will be saved if you click the big blue button, possibly with the option to remove each change individually. Right now you would simply see that you would overwrite the dates saved on this insight... and can make an informed decision.

**Comment by marcushyett-ph** [comment]
I think option 2 makes the most sense to me, by "reload". You mean refresh the page?

Your second scenario also makes sense to me too.

**Comment by clarkus** [comment]
> reload and show the same insight with the saved filters

Unless we find reasons to persist filters, then on manual reload I would expect to show the saved insight definition (including the baked in date parameters). I think this would be expected because we're setting the expectation that this change doesn't qualify as an "edit". 

> I propose that during step 4, we show something like the grey line here (ignore the top two buttons):

If a user makes these changes and then clicks edit, I think we should still load the saved insight definition (including the baked in date parameters). It makes extra work, but it makes it very clear that the changes that happen in view mode do not persist into edit modes. I'm not sure we need to itemize the changes unless we allow for version control or something like that... really the core thing to communicate here is that you need to go to edit mode to make permanent changes to an insight's definition. There could be exceptions for this eventually, but right now I think we should aim for simple and powerful, not flexible. Thoughts?

**Comment by mariusandra** [comment]
Resetting all filters when toggling between the save or edit state in any which way is definitely worth trying. It might work quite well in practice.

**Comment by Twixes** [comment]
I believe a lot of this has been sorted out with my recent PRs (revamped Cancel / Save buttons). What specific problems discussed here still need addressing?

**Comment by mariusandra** [comment]
The idea that we reset all filters when changing modes. Meaning your view mode changes to the date filters are reset when you click edit and vice versa

**Comment by Twixes** [comment]
If I understood this correctly, it already is the case when exiting edit mode – you can only do so with Cancel (which resets) or with Save now. It's not the case when _entering_ edit mode, but that TBH seems intuitive to me. I'd be annoyed if the insight changed back just because I went into Edit mode, forcing me to select that new date range again.

**Comment by mariusandra** [comment]
Indeed, it works like that when exiting edit mode using those two buttons. The browser's back button is the tricky one. Right now it'll open the view mode with the unsaved changes (e.g. extra funnel step) still there. What will [this PR](https://github.com/PostHog/posthog/pull/9091) add: will there be an alert to revert changes when going from view->date change->edit->back, and what changes will be reverted? 

There's another bug. Open a dashboard, click into an insight, change the time range, click back to the dashboard. What should it show there? Right now it'll show the item with the unsaved updated changes. There is no indication that anything changed, or what precisely are you looking at. The "last 180 days" text will even be wrong.

That's misleading UX and we should either: 
1. Reset the filters whenever you enter/exit all view and edit states so that you always know what you're looking at (conclusion we came to with @clarkus above)
2. Clearly show what are you seeing, including what unsaved filters are applied, and having some way to reset the state in the view mode and on a dashboard item.

Option 1 seems easier to get right, even if some things are a little bit worse. A case can be made for option 2, but we'll have to address the "dashboard dates/filters" question at the same time.

**Comment by clarkus** [comment]
> Reset the filters whenever you enter/exit all view and edit states so that you always know what you're looking at (conclusion we came to with @clarkus above)

Yeah I realize this makes more work in some scenarios, but it comes with the benefit of having a super obvious editing model. It would give users more confidence that their actions aren't changing definitions and could make a saved insight much more valuable. I think it's the right approach for now, but agree we can do more to itemize pending changes or even support versioning in some form.

**Comment by clarkus** [comment]
Related - non-date parameters that could be overriding insight filters in a dashboard context https://github.com/PostHog/posthog/issues/2587

**Comment by mariusandra** [comment]
This was basically closed with the "you have unsaved changes" popup. 

There's basically one loosely related issue remaining, which is hinted at in [this internal thread](https://posthog.slack.com/archives/C0368RPHLQH/p1650546303127309?thread_ts=1650545201.555789&cid=C0368RPHLQH). When you change date ranges on dashboards, and open insights while doing this, and/or change their own date ranges, and click back, it's all a mess. 

However I'd fix this as part of [the RFC](https://github.com/PostHog/product-internal/pull/290) (the part about dates, and `insightStorageLogic`) and [this issue](https://github.com/PostHog/posthog/issues/6712)... and close `this` one.
