### ISSUE TITLE
Click on property in PropertyTable to filter

### ISSUE THREAD

**Issue by timgl** [PostHog/posthog#902]
**Is your feature request related to a problem? Please describe.**

When browsing /events I want to be able to click a property to filter the entire view.

**Describe the solution you'd like**
When browsing /events I want to be able to click a property to filter the entire view.

**Describe alternatives you've considered**
Manually add a filter.

**Additional context**

***Thank*** you for your feature request - we love each and every one!

**Comment by paolodamico** [comment]
You can already do this with props in the events table.
