### ISSUE TITLE
Improve the date picker in Insights

### ISSUE THREAD

**Issue by charlescook-ph** [PostHog/posthog#9027]
## Is your feature request related to a problem?

The date picker in an Insight used to select a specific date range could be improved in a couple of ways to make using it a much more pleasant experience for looking at historic data between a set point and 'today'. 

<img width="697" alt="Screenshot 2022-03-15 at 11 34 52" src="https://user-images.githubusercontent.com/70321811/158370470-ac88c3af-a6d6-45d8-b3dc-3e166b95b95b.png">

## Describe the solution you'd like

1. It feels like it would be more intuitive for the two halves to move independently (at least that's what I'm used to in other products). Currently if you move the 'from' calendar back, the 'to' calendar comes back with it. 
2. Given the above, it would be really useful to have a 'today' shortcut in the 'to' calendar somewhere, otherwise you end up scrolling back several months, than forwards again to select today's date.

## Describe alternatives you've considered

Just do what I already do, which works but is a bit annoying.

**Comment by clarkus** [comment]
Related https://github.com/PostHog/posthog/issues/6619

**Comment by clarkus** [comment]
> It feels like it would be more intuitive for the two halves to move independently (at least that's what I'm used to in other products). Currently if you move the 'from' calendar back, the 'to' calendar comes back with it.

I have a design for this somewhere but I can't find it. I will put this on my follow up list to provide some examples. 

> Given the above, it would be really useful to have a 'today' shortcut in the 'to' calendar somewhere, otherwise you end up scrolling back several months, than forwards again to select today's date.

This could be a bug - by default these ranges are meant to be relative to the current date. When selecting a custom range, it's feasible to pick an arbitrary range of dates, but initially that range should be based on the a value relative to today. 

This end date value should probably default to the current date. It's easier to override the second parameter than the first and would prevent pogo-sticking between sets as you're describing. 

<img width="436" alt="Screen Shot 2022-03-15 at 8 48 00 AM" src="https://user-images.githubusercontent.com/254612/158417084-2b932a02-88c7-405a-aa5e-d493f8f405f4.png">

**Comment by kappa90** [comment]
Incorrectly closed after #10462, which is meant to run as an experiment

**Comment by Twixes** [comment]
It's much better now!
