### ISSUE TITLE
Toolbar URLS aren't truncated and displace launch actions

### ISSUE THREAD

**Issue by clarkus** [PostHog/posthog#9046]
## Bug description

A sufficiently verbose URL will displace the launch and authorize actions for the PostHog toolbar

## Expected behavior

Truncate values such that they are identifiable, but don't displace inline actions for each item. 

## How to reproduce

1. Go to the toolbar feature on cloud
2. Note that some URLS are super long
OR
1. Create a new action via the toolbar
2. Note that the modal list for launching URLs is even more constrained. 

## Environment

- [x] PostHog Cloud

**Comment by clarkus** [comment]
This came up again. [Slack thread](https://posthog.slack.com/archives/C02E3BKC78F/p1654634733251229)

**Comment by brunorabelo** [comment]
Could I take this issue? (I am new to PostHog)

**Comment by naquiuddin** [comment]
I tried testing this on latest pull of master at urls `/toolbar` and `/project/settings`. 
Seems like this is fixed, I can't replicate it on my side.

<img width="394" alt="Screenshot 2023-01-12 at 10 44 06 AM" src="https://user-images.githubusercontent.com/1978381/211982955-82e6fe49-e882-4a7d-a0fe-ed6a7682d069.png">

<img width="382" alt="Screenshot 2023-01-12 at 10 45 40 AM" src="https://user-images.githubusercontent.com/1978381/211983170-34c4261b-99fe-46eb-9bc6-88862cfe8e9d.png">
