### ISSUE TITLE
Feedback: language in Data Management is confusing

### ISSUE THREAD

**Issue by jamesefhawkins** [PostHog/posthog#9050]
## Is your feature request related to a problem?

Playing with the data management feature, twice I found the terminology confusing...

## '30 day queries'

<img width="1299" alt="Screenshot 2022-03-16 at 00 57 29" src="https://user-images.githubusercontent.com/47497682/158496028-ffd38c25-b784-4477-b436-ef623589787d.png">

I don't understand what '30 day queries' means?

## 'verified event'

<img width="159" alt="Screenshot 2022-03-16 at 01 00 18" src="https://user-images.githubusercontent.com/47497682/158496233-e66e3eb1-341a-494c-b612-b613a7cf7415.png">

What does 'verified' mean? Is this event from an approved domain? Is the event description only editable by admins? Is the event being filtered so that it's in the right format?

## Describe the solution you'd like

Words I understand or perhaps a "further information" icon that I can click to get explanatory text

**Comment by clarkus** [comment]
I agree that it needs to be more prominent in the non-editing case, but if you click edit on a taxonomy card you see the component and details that describe the attribute. It's really just a signal to other project members that this event should be used in favor of similar events. We are also using targeted language - very tactically "verify" means that this has been identified as accurate. Maybe there is a better word to use but that's where we landed for the first iteration on the idea. 

<img width="366" alt="Screen Shot 2022-03-16 at 7 47 42 AM" src="https://user-images.githubusercontent.com/254612/158620772-b93e97d4-a028-4ad5-83ce-7457bc6cadd4.png">

I agree on the "30 day queries", but it was like that previously for quite a while. They're meant to communicate usage in insights and other features. Maybe there's another value to display here that would be more useful.

We would benefit from some updates to our documentation for this.
