### ISSUE TITLE
Jest tests keep running out of memory

### ISSUE THREAD

**Issue by mariusandra** [PostHog/posthog#9057]
## Bug description

Jest tests started to frequently fail with:

```
FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory
 1: 0xb09980 node::Abort() [/opt/hostedtoolcache/node/16.14.0/x64/bin/node]
 2: 0xa1c235 node::FatalError(char const*, char const*) [/opt/hostedtoolcache/node/16.14.0/x64/bin/node]
 3: 0xcf77be v8::Utils::ReportOOMFailure(v8::internal::Isolate*, char const*, bool) [/opt/hostedtoolcache/node/16.14.0/x64/bin/node]
 4: 0xcf7b37 v8::internal::V8::FatalProcessOutOfMemory(v8::internal::Isolate*, char const*, bool) [/opt/hostedtoolcache/node/16.14.0/x64/bin/node]
 5: 0xeaf3d5  [/opt/hostedtoolcache/node/16.14.0/x64/bin/node]
 6: 0xeafeb6  [/opt/hostedtoolcache/node/16.14.0/x64/bin/node]
 7: 0xebe3de  [/opt/hostedtoolcache/node/16.14.0/x64/bin/node]
```

## Expected behavior

We don't explicitly clear a lot of the mounted logics in jest. It's possible some or all of them are still using up memory after tests finish. We may have reached a breaking point.

This should either be fixed, or we could split the jest tests between multiple github actions, lessening the load per machine and overall runtime.

## How to reproduce

Create a new PR and see if jest tests pass or not.

## Additional context

Might be connected to the move to node 16.

**Comment by jyuvaraj03** [comment]
Hey, this issue seemed interesting. And I think I've figured out the reason for the high heap usage. 

The `msw` package that posthog is [dependent on during tests](https://github.com/PostHog/posthog/blob/master/frontend/src/mocks/jest.ts) has a memory leak. And it happens only with node `16`. I've created an [issue](https://github.com/mswjs/msw/issues/1194) in the upstream repository. You might need to upgrade the package to the latest version if/when the issue gets resolved. 😄
