### ISSUE TITLE
Experiments UI polish

### ISSUE THREAD

**Issue by corywatilo** [PostHog/posthog#9064]
I know we're iterating and this will likely be fixed soon anyway, but I wanted to call out a few bits that may help this section feel more polished.
- [x] Nav link says _Experimentation_, but the breadcrumb says _Experiments_
  While the official name is _Experimentation Suite_, it might sound cleaner to just call it _Experiments_ in-app, as _Experimentation_ on its own just sounds like it uses a few extra letters, and _Experimentation_ isn't the full name

- [x] Missing a space in the _Ran for X days_ line

    <img width="1228" alt="image" src="https://user-images.githubusercontent.com/154479/158643326-57ef68ad-9376-4e38-b640-1344703db54e.png">

- [x] [Mock](https://www.figma.com/file/gQBj9YnNgD8YW4nBwCVLZf/PostHog-App?node-id=6679%3A32112) shows the goal as number of participants, but above screenshot shows length of time experiment was run?
- [ ] The control / test blocks feel a bit out of place as they're just sort of floating in mid-air and not encapsulated by anything
- [x] Progress bar has rounded corners but mock shows a small border radius (which would match our funnels style)
- [ ] Not limited to this section, but we have three conflicting date formats on this one screen alone: 26 Jan 2022 (start/end dates), 26-Jan-2022 (axis label), and [WE] JAN 26 in the breakdown

    <img width="1229" alt="image" src="https://user-images.githubusercontent.com/154479/158644169-1ba795a9-6566-4b77-b43b-774fb0f6e19c.png">

- [x] Chips that are touching, and they look like they're supposed to be clickable but don't do anything (don't know if the `400` and `502` errors I'm seeing in console are related [on this experiment](https://app.posthog.com/experiments/17)?)

    <img width="685" alt="image" src="https://user-images.githubusercontent.com/154479/158644390-3eea982f-a378-456d-af1a-20b97cf2c1e3.png">

- [x] Should there be a recommended run time value in above?
- [ ] Just as a viewer of above screenshot, I'm unclear of what _Trend goal_ is trying to say, given how it's formatted
- [x] Title is much closer to the breadcrumb than on other pages

    <img width="713" alt="image" src="https://user-images.githubusercontent.com/154479/158650778-ca162ac2-945f-4340-9d47-8d4705b67984.png">

- [x] New experiment screen loses nav active state (should be highlighted)

    <img width="502" alt="image" src="https://user-images.githubusercontent.com/154479/158662033-7ac8c5ae-a044-456e-a432-becb8e2eaf3c.png">

- [x] Use sentence casing

    <img width="685" alt="image" src="https://user-images.githubusercontent.com/154479/158662843-9ba005b1-094b-48fd-97c3-b8a1254e069a.png">

    <img width="631" alt="image" src="https://user-images.githubusercontent.com/154479/158662872-e5aa2e18-cb95-4052-8b38-6a52769d992d.png">

    <img width="672" alt="image" src="https://user-images.githubusercontent.com/154479/158663252-e041e26b-deac-444b-935b-ee3343e2504e.png">

- [x] Format numerical values

    <img width="511" alt="image" src="https://user-images.githubusercontent.com/154479/158663756-f73c6b46-40bd-4027-848a-4f75cb03088c.png">

- [x] Save button should be duplicated in top right? Do we need floppy disk icon? =] (Also missing cancel button to go back without using Back button)

    <img width="699" alt="image" src="https://user-images.githubusercontent.com/154479/158664420-ad0ac394-7005-4299-90cd-d3f270ec756a.png">

Otherwise this is really coming along - overall super cool!

**Comment by neilkakkar** [comment]
Much appreciated, thanks Cory! :D - will get on these tomorrow.

> Should there be a recommended run time value in above?

Yes, but this experiment is too old which is why its not there.

> [Mock](https://www.figma.com/file/gQBj9YnNgD8YW4nBwCVLZf/PostHog-App?node-id=6679%3A32112) shows the goal as number of participants, but above screenshot shows length of time experiment was run?

Actually depends on the kind of experiment you have. Trends have days, funnels have participants seen.

**Comment by neilkakkar** [comment]
Thanks a lot for doing this Cory! My schlep-blindness was getting in the way of polishing this.

Would love a review here: https://github.com/PostHog/posthog/pull/9081

What still remains:

> The control / test blocks feel a bit out of place as they're just sort of floating in mid-air and not encapsulated by anything

Any idea how to solve this? (cc: @clarkus )

> Just as a viewer of above screenshot, I'm unclear of what Trend goal is trying to say, given how it's formatted

I'm not sure how to fix this 🤔 . 

> Not limited to this section, but we have three conflicting date formats on this one screen alone: 26 Jan 2022 (start/end dates), 26-Jan-2022 (axis label), and [WE] JAN 26 in the breakdown

Any suggestions I can scope only to this page?
