### ISSUE TITLE
Multiple, separate projects per installation

### ISSUE THREAD

**Issue by shafy** [PostHog/posthog#907]
**Is your feature request related to a problem? Please describe.**
We use the events API with our mobile apps, and since there's only one API key per PostHog installation, we need to have separate installations for each app (and staging and prod versions thereof).

**Describe the solution you'd like**
I'd like to add multiple apps/projects to one PostHog deployment that get assigned separate API keys (e.g., the way Mixpanel does it work well). 

**Describe alternatives you've considered**
Only alternative is having multiple deployments of PostHog.

**Comment by timgl** [comment]
Hey! This is already possible though not well documented as it's mostly something we use for our own multi-tenancy cloud offering

We have this concept of Teams that can have multiple users. Each team has its own API key.

To create teams, you can do something like:
```bash
python manage.py shell
```
```python
from posthog.models import *
user = User.objects.create_user('email', 'password')
Team.objects.create_with_data(name='app name', users=[user])
```

**Comment by shafy** [comment]
Hey @timgl thanks for replying so quickly. Interesting, let me try this out. Is this more of a workaround, or will you graduate this to a full feature and make it accessible in the GUI, too?

**Comment by timgl** [comment]
We use this internally for our multi-tenancy stuff so it's well supported in that sense. It's likely that if we make this more accessible (in the GUI or whatever) for self-hosted instances it'd be an enterprise feature, [given this is likely to appeal to larger orgs.](https://posthog.com/handbook/strategy/business-model)

**Comment by janbaykara** [comment]
Would you accept PRs to surface this for the open source version?

**Comment by shafy** [comment]
Ok thanks... Although I think that this is something smaller teams also would want (even if it's only for staging and production).

I created at a second team and assigned the same user that is also in the default team, and now I get a 500 error (nothing more in my Heroku logs). Can one user be only in one team or is there another reason?

**Comment by timgl** [comment]
@shafy Enterprise might be the wrong word but certainly in our 'paid'/teams sphere, as it's not [individual developers](https://posthog.com/handbook/strategy/business-model) who would use this.

In terms of the error, users can only be assigned to a single team and that is pretty ingrained throughout. Does that still makes for your use case? An alternative might just be adding a property on every capture call with the app name, then being able to filter by that.

**Comment by shafy** [comment]
Thanks @timgl! Let me see and get back to this mid next week.

**Comment by shafy** [comment]
Hey @timgl had some time to test and think about it. Unfortunately, it doesn't really solve the issue. While it would allow to have only one deployment, we still need to have different user accounts to log in and they have to be created painfully through the console for each new user.

Therefore, it's easier to just have separate deployments. Although far from ideal.

The feature to switch between projects is there in every analytics tool I've ever used (Google Analytics, Mixpanel, Simple Analytics). And I disagree with you that it's not useful for smaller teams.

So, maybe you might want to reconsider adding it your roadmap? I didn't look into the code, but if it's possible to build such a feature with your current database and model architecture, I woud be happy to do it and create a PR if you're open to it?

**Comment by pedybr** [comment]
I would second @shafy . The functionality to have different products/projects in one analytics tool is a very basic requirement for us, since we are running many different services that are all part of the same product suite. To separate by team with excluding groups of users seems very awkward and not very transparent/useful. And even for stage/prod it would be super helpful.
Adding a property on every capture sounds promising as well...

**Comment by timgl** [comment]
We now support this functionality in the enterprise tier.

**Comment by shafy** [comment]
I still disagree. I think having mutiple API keys in one deployment is absolutely something individual developers need, be it for staging / production environments or just having multiple apps and websites that use PostHog.
As I understand it you suggest that this feature would go into your $2k/month tier, right?

I think the misunderstanding comes from what you think a team is and your future plans for teams. Maybe I need to reframe: It's more about having multiple projects per deployment, not mulitple teams. So maybe we can have a new model `Project,` that has the attribute `api_token` (move it over from the `Team` model). This would allow users to be associated with multiple projects within only one team. You can then leave the Teams feature for bigger enterprises that need other team-related features such as admin, permissions, etc.

This, of course, complicates things a bit. The solution you suggested is quicker and would solve my problem, but I just think there absolutely must be a way to have multiple projects per deployment and solving this correctly will help improve PostHog by a lot!

I know you have probably discussed this internally and in the end you know best how to build PostHog. So let me know if you want to stop discussing this and I'm happy to implement the solution you suggested for now :-)

**Comment by pedybr** [comment]
Hi there! We are revisiting PostHog and I was hoping for some progress on this topic. Are there any news? This is still the most important feature for us to use PostHog.

**Comment by timgl** [comment]
@pedybr Yep, this is now a PR #1468, that'll allow you to run multiple teams. We will likely make the management of this functionality a paid functionality as discussed above, but you'll manually be able to go into the shell and create teams if you wish.

**Comment by shafy** [comment]
@timgl I still think my above propsed solution to decouple API key from teams is better, but this will do for me for now. Two questions:
1) Will you add adding teams manually to the docs?
2) Will switching (not creating) teams from GUI be part of the core, non-paid functionalities? If not, how would we switch teams?

**Comment by timgl** [comment]
@shafy Teams are now slightly unfortunately named, they will be more like "projects" with an overarching "organization" that the users are a member of. Dashboards, funnels etc will be specific to each team(/project)

To answer your questions
1. Unsure, but I'm happy to walk you through it once ready :)
2. Yes

**Comment by shafy** [comment]
Amazing, so in the end it does result in something similar like my proposition (with different naming). This really is an important feature I think, great stuff! Looking forward to trying it out!

**Comment by shafy** [comment]
Hi @timgl do you have any news here how we can add projects (i.e. API keys) without using the enterprise version?

**Comment by timgl** [comment]
Hey, you should be able to do this by adding another row to the "posthog_team" table in your DB. Make sure you set "organization_id" to the correct ID (there will only be one organization on your instance), and an api_token.

**Comment by shafy** [comment]
Works like a charm, thanks so much. For anyone else that might see this in the future and is not fluent in Django, just do this:

Log into the Django shell:
```
python manage.py shell
```

Find out what our `organization_id` is:
```
Organization.objects.all()
```

Copy paste the `organization_id` from the previous result:
```
o = Organization.objects.get(id="<id_from_before>")
```

Create a new Team that belongs to that Organization:
```
t = Team(name="My new project", organization = o)
t.save()
```

Refresh PostHog and voila, you can switch to the newly created Project (yes, Teams are Projects).

**Comment by nextlogic-ono** [comment]
Hello.

Can this feature be implemented in the community edition?

Enterprise edition seems quite pricey just for this and the workaround is to install an instance for every project, so it's doable except it'll take up on server resource and management burden.

Otherwise it's hard to think about using it on multiple projects.

**Comment by jamesefhawkins** [comment]
Hey!

We are about to release pure usage based pricing as a VPC deployment. This will mean you can get multiple projects from a starting price of $0.000225/event ingested (and getting much less expensive at higher volumes), with no minimum, rather than our previous $2k/month minimum. Hope that makes it a little easier to consider.
