### ISSUE TITLE
The New Storybook (status update)

### ISSUE THREAD

**Issue by mariusandra** [PostHog/posthog#9079]
What's this? [A New storybook!](https://storybook.posthog.net/) <-- seriously, open this in a new tab and then look through the gifs below. 

![2022-03-17 12 12 34](https://user-images.githubusercontent.com/53387/158797512-c359c070-ed2e-47b8-966e-a8ac30e84dd7.gif)

Some of the new features include:

- Automatically generate docs for all components, including **source code** you can copy from the browser.
- Automatically generated list of props for each component. Just look at [this list for LemonTable](https://storybook.posthog.net/?path=/docs/components-lemon-table--lemon-table). It's darned practical.
- Simple API mocking, shared system with jest. **No backend required to run anything!**
- Includes technical HowTo guides for [using components](https://storybook.posthog.net/?path=/docs/components-how-to-use-components--page), [creating forms](https://storybook.posthog.net/?path=/docs/forms-how-to-build-a-form--page) and [building scenes](https://storybook.posthog.net/?path=/docs/scenes-how-to-build-a-scene--page). Basically code you can copy when performing a task, such as setting up a new scene or building a form.
- Oh, and all components and scenes work.

The aim is for storybook to be a tool we all actually use and contribute to. We're a big enough team that not everyone knows if you add a new component to the codebase. To make sure it gets usage, also add it to storybook. Then whenever you need a component yourself, check storybook if there isn't already one that you can use.

As always, all of this is just available via https://storybook.posthog.net/ or `yarn storybook`.

The storybook already has many components, **together with code you can just copy paste**, but many more are still missing:

![2022-03-17 12 04 26](https://user-images.githubusercontent.com/53387/158796110-a1663f6d-8467-447f-8213-ab6ddd75961c.gif)

You can browse through insight types:

![2022-03-17 12 06 27](https://user-images.githubusercontent.com/53387/158796256-93b21015-0563-48ed-a745-392c30fa3780.gif)

... and other scenes:

![2022-03-17 12 08 07](https://user-images.githubusercontent.com/53387/158796516-ef9982dc-b218-4276-a5e6-5b3b38147d2c.gif)

(did you spot the toolbar?)

Plus there are new docs:
- [How to create stories](https://storybook.posthog.net/?path=/docs/how-to-create-stories--page)
- [How to mock requests](https://storybook.posthog.net/?path=/docs/how-to-mock-requests--page)
- [How to use components](https://storybook.posthog.net/?path=/docs/components-how-to-use-components--page) (largely TODO)
- [How to build a form](https://storybook.posthog.net/?path=/docs/forms-how-to-build-a-form--page)
- [How to build a scene](https://storybook.posthog.net/?path=/docs/scenes-how-to-build-a-scene--page)

Next steps:

- Get everybody aware of storybook and on page with the component-based approach to designing and building products (this issue)
- Get everyone to actually start using storybook, and contributing new stories
- Develop a cohesive **form** strategy for the app (will work on next personally).
- Make a CI test that fails if a storybook story can't be built to avoid hidden regressions.
- Enable visual regression testing (without breaking the bank).
- Talk through [the regression that happened here](https://github.com/PostHog/posthog/pull/9049#discussion_r827867076) (will do so in a new comment)
- Write the missing "how to use components" docs (@Twixes perhaps?)

Any feedback thus far?

**Comment by mariusandra** [comment]
Regarding [the new system for API mocks](https://storybook.posthog.net/?path=/docs/how-to-mock-requests--page), @hazzadous had a few comments:

> Something I liked about the other solution was:
> 
>  1. we had both request and response type safety, tied specifically to the same types used for the api client. If we change something in the api client for the boundary types, we will be sure that any fixtures will be updated by the dev also, thereby avoiding stale stories/tests.

I agree, we lose some typing safety with the new approach and with some of my refactors. Is there a way we can add it back? Should we bother? 

The lack of strict or somewhat automatic typing between out python API and JS consumer has been bothering me for a while. I'd love for all the mock data we use to conform to a schema, and any changes to either the mocks or the app or the database to throw a linting error somewhere. I still don't know what's a truly good system here, and don't have the capacity to build one now, yet I'd argue that a few less types here won't really make a difference without an overwhelming system.

We are free to use whatever abstractions when building the API mocks, which internally can be as typed as needed. Here's a [bunch of shared mocks](https://github.com/PostHog/posthog/blob/20ebfd6b7535900795866eb5efb54309ad768263/frontend/src/lib/components/TaxonomicFilter/TaxonomicFilter.stories.tsx#L11) for the taxonomic filter for example.

>  2. we reuse the express handler interface and avoid creating our own, which will need maintenance, documenting etc. It seems like an unnecessary abstraction.

The benefit of an abstraction is that it can be changed. I'd argue that the new syntax brings a lot of clarity expressed in much less code that you had to write before, while keeping everything neatly contained next to each other. This makes it so much more likely someone's going to actually write these stories, which is goal number one. Everything else is secondary 😅 

>  3. we couple the url path and the handler (types etc), here we decouple them which I don't think is ever relevant

True, I'm not 100% convinced with this approach either. However, if it's one standard approach, protected by typescript, we can easily change it, even if it means 40 changed files. 

One though I had was to change the `get: {}` approach into a flat list:

```ts
mswDecorator({
    '/api/person/properties': [], // GET: is optional
    'GET:/api/person/properties2': [],
    'POST:/api/person/properties3': () => [{}]
})
```

This would allow code such as:

```ts
mswDecorator({
    ...mockTeam(mockTeam),
    ...mockPersonProperties([]),
})
```

leading to even more composability (save for key conflicts). I'm not sure this is the right direction either, but having method-independent mocks has lead to errors before, as some the `/insights/` endpoint have a differently shaped response depending on the method.

> Just my 2c

Keep them coming, and happy to accept PRs or brainstorm more ideas.

**Comment by hazzadous** [comment]
> I still don't know what's a truly good system here, and don't have the capacity to build one now

What I've seen work well here is using e.g. the OpenApi schema to validate e.g. the requests that are produced by tests. That might go some way to checking that backend/frontend are in sync.

> The benefit of an abstraction is that it can be changed

You mean the implementation can be changed right? The abstraction is used in quite some number of places so will likely be quite stable.

> I'd argue that the new syntax brings a lot of clarity expressed in much less code that you had to write before

Fair enough, although I now have to learn these different interfaces whereas I only had to consider one before.

> This would allow code such as:
> 
> mswDecorator({
>     ...mockTeam(mockTeam),
>     ...mockPersonProperties([]),
> })
> leading to even more composability (save for key conflicts).

I like it, we can add some overloading to support the different signatures you've introduced. This way we get the typing advantages in addition.

>  I'm not sure this is the right direction either, but having method-independent mocks has lead to errors before, as some the /insights/ endpoint have a differently shaped response depending on the method.

We don't have to assume they are the same endpoint, we can have `mockGetTeam`, `mockUpdateTeam` just like we might have `getTeam` and `updateTeam` API client functions with different signatures.

> Keep them coming, and happy to accept PRs or brainstorm more ideas.

no PR's yet I'm afraid but more 2c

**Comment by mariusandra** [comment]
> > The benefit of an abstraction is that it can be changed
> 
> You mean the implementation can be changed right? The abstraction is used in quite some number of places so will likely be quite stable.

Not sure where we're drawing a line with the definitions, but I do think I mean changing the abstraction. The fact that we're using some type of abstraction means we can change the entire codebase from using mocks in the current style:

```ts
mswDecorator({
  get: { '/api': response }
})
```

... to forcing: 

```ts
mswDecorator({
  `get:/api`: () => [200, response]
})
```

and then change that to 

```ts
mswDecorator({
   ...apiAbstraction(response)
})
```

and beyond more easily than if we would have no abstraction, and the code would just look like this:

```ts
function decorator (state) {
  worker.doSomething()
  worker.doSomethingElse(long => chain(of(functions))))
  return <state />
}
```

Granted, a "change" means a 2h PR with 60 changed files, but as long each PR is nothing more than a `chore(codemod)`, 🤷 .

**Comment by weyert** [comment]
We also have upcoming package at `msw` which adds support for mocking OpenAPI or  leverage HAR files. Would that be of interest?

**Comment by hazzadous** [comment]
@weyert sounds interesting yes would love to have a look, do you have a link?
