### ISSUE TITLE
Request: Item count on CSV export

### ISSUE THREAD

**Issue by joethreepwood** [PostHog/posthog#9084]
## Is your feature request related to a problem?

Currently, if I want to export a CSV of persons, I get the following warning: 

<img width="542" alt="Screenshot 2022-03-17 at 13 35 53" src="https://user-images.githubusercontent.com/84011561/158820059-89dcf1fb-7334-44d9-b662-795eff644c9b.png">

But I have no idea how many items I'm currently trying to export, because there's no count on the page and the pagination only says:

<img width="296" alt="Screenshot 2022-03-17 at 13 36 49" src="https://user-images.githubusercontent.com/84011561/158820247-a5e77ba2-eec5-42fc-8baa-7f1a858d5f7c.png">

So I have no idea how many pages there are either, in order to do some quick math. 

This is a problem in two ways: 

1) The API warning is worded unclearly. Am I above 10,000 and this warning is telling me I _need_ to use the API? Or is it just a best practice? 
2) If I push ahead and export my CSV, I can easily end up with a CSV which is too long to export into the other tools I need it to work in (Google Sheets, Numbers) which have limits on the number of items or columns they can import. But I don't know how big the export will be until it's already done. 

## Describe the solution you'd like

It would be nice to make the export give a simple confirmation: 

"This export contains X users. Would you like to continue?"

and if the number is over 10,000: 

"This export contains X users. Exporting by .CSV is limited to 10,000 users.
To return more, please use [the API](https://posthog.com/docs/api/persons)."

It would be handy to have better Page 1 of 10 pagination too.  

## Additional context

Tagging @clarkus as this seems most relevant to you?

**Comment by clarkus** [comment]
Yup this is definitely something that is coming up more often. A more-capable export menu could be really powerful. It's worth noting that the use case can overlap with sharing scenarios, too. 

Questions to inform this work:
- Are there any other formats that should be supported for export? Would a PDF make sense?
- Are there permission limitations on who should be able to export data?
- Which tables would benefit from exporting? I kind of feel like this should be baked into [all our data tables](https://github.com/PostHog/posthog/issues/9035). 
- There are limits in places within the UI to ensure performance standards - for example the events page is limited to a set time frame to prevent long page loads. We might need to consider a project or org level feature that lets you export your data back out of PostHog without the limitations present in features. Given our stance on data ownership, a feature that lets you export whatever you want with limits, configuration, etc could be really trust-building. 
- This feels pretty powerful in the context of insight results tables

Thanks for filing, @joethreepwood. This is a good idea! /cc @marcushyett-ph for product considerations.
