### ISSUE TITLE
Request: Let me choose which columns to export as CSV

### ISSUE THREAD

**Issue by joethreepwood** [PostHog/posthog#9086]
## Is your feature request related to a problem?

When you export a CSV of events or persons, you currently export every table column on that item. Which can be a lot. And most isn't needed. 

Trying to export a list of all self-hosted users, for example, returns a CSV with over 9,000 columns. That's too long to open in common tools such as Sheets or Numbers. And I only need a small number of columns anyway - really, just ```name```. So, 8999 columns get deleted. 

This is a problem for users because of the above, but load-wise means we're also exporting a lot of information for no reason.

## Describe the solution you'd like

Somehow let me choose which columns to export!

## Describe alternatives you've considered

...

## Additional context

@tiina303 suggested I raise this

https://posthog.slack.com/archives/C02E3BKC78F/p1647525504544399

**Comment by clarkus** [comment]
I think this is closely related to configurable table columns. If the table supports configuration, that same structure or ordering should apply to any exports, embeds, shares, etc. So to make this happen we'd need to:

1. Ensure that exports respect the table configuration and structure
2. Make it possible to configure all the data tables. 
3. Ensure consistent, predictable filtering for all the data tables.

Worth noting that filters should also apply here. With filters, configuration, you're creating a data set that you find valuable. Exporting should match whatever you see after taking those steps.
