### ISSUE TITLE
Insights don't load on mobile

### ISSUE THREAD

**Issue by rcmarron** [PostHog/posthog#9090]
## Bug description

When I try to open our company dashboard on mobile chrome it fails with an error. I can't quite see the error in the viewport, but it's a `XYZ is not an object (evaluating 'n.measureText(s).width)`. I'm guessing `n.measureText(s)` isn't available on mobile or something.

I couldn't find the errror in Sentry or exactly where this is coming from, but I think it's somewhere in chart-js based on the console logs seen in [this recording](https://app.posthog.com/recordings?filters=%7B%22actions%22%3A%5B%5D%2C%22events%22%3A%5B%5D%2C%22properties%22%3A%5B%7B%22key%22%3A%22email%22%2C%22value%22%3A%5B%22rick%40posthog.com%22%5D%2C%22operator%22%3A%22exact%22%2C%22type%22%3A%22person%22%7D%5D%2C%22date_from%22%3A%222022-03-10%22%2C%22date_to%22%3Anull%2C%22offset%22%3A0%2C%22session_recording_duration%22%3A%7B%22type%22%3A%22recording%22%2C%22key%22%3A%22duration%22%2C%22value%22%3A60%2C%22operator%22%3A%22gt%22%7D%7D&source=recordings_list#sessionRecordingId=17f98f0bbc3f2a-064e32f58b3a77-2a6d4f35-5a900-17f98f0bbc412a0)

## Expected behavior

I can see the insights

(filling this part of bug reports always feels so sarcastic 😂)

## How to reproduce

1.
2.
3.

## Environment

- [ ] PostHog Cloud
- [ ] self-hosted PostHog (ClickHouse-based), version/commit: _please provide_
- [ ] self-hosted PostHog (Postgres-based, legacy), version/commit: _please provide_

## Additional context

@alexkim205 or @Twixes any chance either of you has thoughts on this one?

**Comment by alexkim205** [comment]
That's weird, it works on my phone when I'm looking at the same dashboard. Are you on IOS? This is my recording

https://app.posthog.com/recordings?filters=%7B%22actions%22%3A%5B%5D%2C%22events%22%3A%5B%5D%2C%22properties%22%3A%5B%5D%2C%22date_from%22%3A%22-24h%22%2C%22date_to%22%3Anull%2C%22offset%22%3A0%2C%22session_recording_duration%22%3A%7B%22type%22%3A%22recording%22%2C%22key%22%3A%22duration%22%2C%22value%22%3A60%2C%22operator%22%3A%22gt%22%7D%7D&source=recordings_list#sessionRecordingId=17f990c88c21991-06eba18882374a-6b0e5213-4a574-17f990c88c329a4

**Comment by alexkim205** [comment]
`measureText` definitely seems to be something chartjs uses under the hood to measure text for axis labels. But not sure why we're seeing different results here.

**Comment by rcmarron** [comment]
Oh weird, it works for me now....idk
