### ISSUE TITLE
"Filter out internal and test users" splits filter logic on insights

### ISSUE THREAD

**Issue by camerondeleone** [PostHog/posthog#9093]
## Is your feature request related to a problem?

I find the layout of having the 'filter out internal and test users' selector splitting the 'add filter group' logic to be jarring. 
This filter logic is applied once in a binary fashion and you don't really need to think about how it stacks with other logic you apply. If I'm building some logic for different conditions, I want those conditions, along with the option to add any new conditions, to be contiguous so I can make sense of them easily, rather than having to mentally escape the internal user logic in the middle of that.

<img width="1210" alt="image" src="https://user-images.githubusercontent.com/56287180/158872386-6f6ac321-b05a-46e9-aa3b-a21c99b08b68.png">

## Describe the solution you'd like

Pin the 'filter out internal and test users' to the bottom or top of the filter area,

**Comment by clarkus** [comment]
Agreed - I [updated the designs](https://www.figma.com/file/gQBj9YnNgD8YW4nBwCVLZf/PostHog-App?node-id=8088%3A60421) to match this, but we'll need a code change to reposition. The internal / test filters function as logical AND, so placing them above the content makes sense.

![filter group states](https://user-images.githubusercontent.com/254612/158873188-c312c209-f108-4c13-8059-6789407bf381.png)
