### ISSUE TITLE
Users aren't displaying

### ISSUE THREAD

**Issue by jamesefhawkins** [PostHog/posthog#91]
![Screenshot 2020-02-12 at 21 52 20](https://user-images.githubusercontent.com/47497682/74405467-fadd2a00-4de1-11ea-8f5c-46054343c9da.png)
https://app.posthog.com/person/1703cf9694ad64-0ff5c7c62bfe94-396e7606-1aeaa0-1703cf9694baa4

* This is an example user, that if I view their behaviour, the page is blank

**Comment by timgl** [comment]
Fixed
