### ISSUE TITLE
After Inspecting element on page to define action. Save does not redirect back to posthog

### ISSUE THREAD

**Issue by fuziontech** [PostHog/posthog#911]
**Describe the bug**
After Inspecting element on page to define action. Save hangs and does not redirect back to app.posthog.com

**To Reproduce**
1. Open app.posthog.com
2. Go to Actions -> New Action -> Inspect element on your site
3. Inspect and select an item on site.
4. Give action a name and press save -> it will not redirect back to app.posthog.com

**Expected behavior**

Redirect back to app.posthog.com

**Screenshots**

**Hosted or self hosted?:**

both

**Additional context**
Might be desirable not to redirect. Might want to stay on page and add to list of added actions.

**Comment by mariusandra** [comment]
I guess this issue got deprecated in favor of https://github.com/PostHog/posthog/projects/7
