### ISSUE TITLE
[Funnels] Reduce query builder width on new funnel?

### ISSUE THREAD

**Issue by corywatilo** [PostHog/posthog#9114]
When building a new funnel, I want to be able to clearly see the results.

## Current

The query builder takes up 50% of the available width, limiting how much data I can see without scrolling horizontally. It's also hard to get value from the funnel preview since the bars are so wide, making it hard to get a glimpse of the full picture.

<img width="1376" alt="image" src="https://user-images.githubusercontent.com/154479/159034599-102f9c98-057e-403f-a900-fffa520cd7a0.png">

## Proposed

By reducing the width of the query builder (or at least setting a smaller max-width), we can see more data without having to scroll. (None of the form elements in the query builder seem like they need any more space than this.)

<img width="1374" alt="image" src="https://user-images.githubusercontent.com/154479/159035339-823b555f-4983-4341-8175-df658be47e20.png">

**Comment by Twixes** [comment]
Yep, this'll be a good immediate improvement.

**Comment by clarkus** [comment]
Just linking the [slack thread](https://posthog.slack.com/archives/C0368RPHLQH/p1647277703625059) where a lot of this context was shared.
