### ISSUE TITLE
How to determine PostHog version?

### ISSUE THREAD

**Issue by samtuke** [PostHog/posthog#9117]
Hey does it say somewhere in the UI, menus etc. what version I'm running? Can't see it. Received the manual migration notification via email this morning and need to check compatibility.

**Comment by timgl** [comment]
Hey, it should say it if you go to /instance/status

**Comment by samtuke** [comment]
Works! Thanks. An easy to find link to that in the UI would be good.

**Comment by neilkakkar** [comment]
For future reference, you can find this link in the UI here: (The "Instance settings" or "Instance status" links)

<img width="350" alt="image" src="https://user-images.githubusercontent.com/7115141/159245034-faa02c82-9ddc-47fd-8832-bcc9d7a37736.png">

**Comment by samtuke** [comment]
Thanks 👍
