### ISSUE TITLE
Recordings spend a long time buffering

### ISSUE THREAD

**Issue by aantn** [PostHog/posthog#9122]
## Bug description
I need to wait about 13 seconds for each recording to buffer. This is very long compared to other products on the market. For example, Matomo records play instantly.

I'd love to move entirely away from Matomo recordings but can't do so because the buffering time on PostHog is very long. 13 seconds might not sound like a lot, but if you watch 100 recordings its 21 minutes of waiting.

## Expected behavior
Recordings should play instantly.

## Environment

- [X ] PostHog Cloud

**Comment by neilkakkar** [comment]
Hey Natan!

That's surprising, it shouldn't be that slow. Could you please link to a recording or two that are this slow, and we'll look into it?

cc: @rcmarron

**Comment by aantn** [comment]
Yes, here is an example:

https://app.posthog.com/recordings?source=recordings_list#sessionRecordingId=17faacad9c294d-031b3e5dc816928-3e63464a-1fa400-17faacad9c311ce

**Comment by rcmarron** [comment]
Hey @aantn! Thanks for sharing this recording. You're absolutely right that they should be fast. (our mean buffer time is 700ms, so this is definitely an outlier)

I just spent some time looking into it, and it looks like your hitting this issue: https://github.com/rrweb-io/rrweb/issues/790. It's an issue I've only seen in the data before, but have never had an environment that I could reproduce it in (so I'm selfishly excited to see your report!).

Could you share a URL to the website that these slow recordings happen on? The issue has to do with how the site is recorded, so if I can get to the website and reproduce it, I'm hoping I can debug and fix it.

**Comment by aantn** [comment]
@rcmarron gladly. I'll probably have to create an account for you. What's the next way to contact you privately?

**Comment by rcmarron** [comment]
Great, I'm rick[at]posthog.com or @Rick Marron in our [slack channel](https://posthog.com/slack).

**Comment by pauldambra** [comment]
we've completely rewritten ingestion and playback APIs since this report so even if it's still being experienced it'll be a different issue 😅
