### ISSUE TITLE
Export button on Trends messes with dashboard view

### ISSUE THREAD

**Issue by neilkakkar** [PostHog/posthog#9135]
## Bug description

A Trend on a dashboard looks like:

<img width="634" alt="image" src="https://user-images.githubusercontent.com/7115141/159272616-08b32989-d1f0-48a5-b065-8b2d58a9ad0d.png">

*Please describe.*  
*If this affects the front-end, screenshots would be of great help.*  

## Expected behavior

Export minds its place

## How to reproduce

1. Go to a dashboard with trend table
2.
3.

## Environment

- [ ] PostHog Cloud
- [ ] self-hosted PostHog (ClickHouse-based), version/commit: _please provide_
- [ ] self-hosted PostHog (Postgres-based, legacy), version/commit: _please provide_

**Comment by Twixes** [comment]
CC @timgl

**Comment by timgl** [comment]
Oops, on it
