### ISSUE TITLE
Toolbar for users outside of PostHog doesn't do anything

### ISSUE THREAD

**Issue by liyiy** [PostHog/posthog#9137]
## Bug description

Users are seeing the PostHog toolbar but it doesn't do anything for them, especially during ingestion/onboarding.

https://user-images.githubusercontent.com/25164963/159283085-103fc585-c742-40e0-9876-a3025359d810.mov

*Please describe.*  
*If this affects the front-end, screenshots would be of great help.*  

## How to reproduce

1.
2.
3.

## Environment

- [ ] PostHog Cloud
- [ ] self-hosted PostHog (ClickHouse-based), version/commit: _please provide_
- [ ] self-hosted PostHog (Postgres-based, legacy), version/commit: _please provide_

**Comment by kappa90** [comment]
Closing as now the toolbar needs to be explicitly triggered from within the app.
