### ISSUE TITLE
Creating an action based on auto-captured events (using inspect) does not produce new events

### ISSUE THREAD

**Issue by fuziontech** [PostHog/posthog#914]
**Describe the bug**
During demo today we walked through creating an action based on auto-captured events. When we navigated back to the activity page there were no events matching the inspected element. 

**To Reproduce**
 Events -> Actions -> New Action -> Element -> choose button on site -> back to actions page

**Expected behavior**
Events to be filtered out based on the element interactions in events in history

There were no events in the response

**Hosted or self hosted?:**
App

**Additional context**
Could have been something to do with this specific site configuration. We will probably need to work with customer to resolve issue.

**Comment by EDsCODE** [comment]
Was this maybe due to the issue with the long running queries that were clogging up workers that we reverted and fixed?

**Comment by timgl** [comment]
Yeah reasonably sure it was
