### ISSUE TITLE
Make PostHog bookmarklet more visible

### ISSUE THREAD

**Issue by liyiy** [PostHog/posthog#9141]
Our bookmarklet right now is enclosed in a collapsible with a lot of text so it's easy to miss/ignore

<img width="971" alt="Screen Shot 2022-03-21 at 11 01 54 AM" src="https://user-images.githubusercontent.com/25164963/159289399-c8cc7271-b908-46df-b491-17d93f1171f1.png">

Expose this option a bit more so users can try it out

**Comment by leggetter** [comment]
Definitely useful in scenarios where you work for a company where there's a reasonable process involved in even getting a trial in place. The bookmarklet allows you to create a quick demo for your internal stakeholders.

Some notes on using in single-page apps vs. multi-page apps would also be useful. For example, emphasise (even more) that I need to click the bookmarklet in every page within a multi-page app? And call out that it's great for single-page apps.

**Comment by clarkus** [comment]
This feature also exists in project settings. I feel like anything we do should consider that other case as well. 

<img width="684" alt="Screen Shot 2022-03-23 at 9 51 53 AM" src="https://user-images.githubusercontent.com/254612/159753248-6f1a118c-561a-4a1b-86a0-2db966da03b1.png">

**Comment by liyiy** [comment]
yes!!! agree!!

**Comment by liyiy** [comment]
good thing i own that too!!
