### ISSUE TITLE
Sprint 1.35.0 1/2 - Mar 28 to Apr 15

### ISSUE THREAD

**Issue by marcushyett-ph** [PostHog/posthog#9144]
# Global Sprint Planning

- Next sprint will be 3 weeks long - covering offsite. 
- Expect some reduced capacity the week after the offsite too as a fair few people are off. 
- Major sprint goals should ideally have a thought through, and well scoped RFC before sprint planning

## Retro: Status of Outcomes from Previous Sprint

1. Team West: Clean up Launch week features and prepare for release (Respective owners for each feature @EDsCODE) (Status: ❓
Experiments: polished. This week got secondary metrics polished
And/Or Filtering: Released to 75%. No chaos. Added instrumentation
Data Management: No bugs. Some performance work like loading event and prop def pages
Home page: polished + live. List work is WIP
)
2. @Twixes - Project Quality Launch Week (insights, dashboards, annotations) (Status: A lot of stuff visibly improved! The list was ambitious, so a few items will remain, but that's the less important and urgent ones.)
3. @pauldambra - Project "the only thing we learn from history" (audit log, history of objects, reducing WIP) (Status: should have feature flags and persons out to Beta users by Fri (cloud users at a stretch))
4. @mariusandra - Project "stop talking about development guidelines" (incl. fixing storybook and other tests, introducing kea-forms, writing basic guidelines and rearranging components for use) (Status: will finish, and will [keep talking](https://storybook.posthog.net/))
5. ClickHouse repeatable infrastructure as code w/ CH5 re-provisioned @fuziontech @hazzadous (Status:In Progress ETA end of Week)
6. ClickHouse upgraded to 21.11.11.1.111.1 @guidoiaquinti @hazzadous (Status: Complications mean we've not been able to do this)
7. Devising a plan for the ingestion pipeline to handle person properties on events and get started on its implementation @yakkomajuri (Status: We have a clear plan for going forward and have gotten started on the implementation.)

## Plan: Proposed Goals for Next Sprint 

Each goal should have a single owner. Owner can only be an engineer.

1. **Ingestion:** Have an MVP ready for persons data on new events (completed up to step 6 of [the project](https://github.com/orgs/PostHog/projects/41/views/1?visibleFields=%5B%22Title%22%2C%22Assignees%22%2C2635782%2C%22Status%22%2C2619643%2C2619894%5D)) @yakkomajuri
2. **Team East: Nail Insights** https://github.com/PostHog/product-internal/pull/290 - @mariusandra @pauldambra
3. **Team East: ~Nail~ Great Demo Data** https://github.com/PostHog/product-internal/pull/298 - @Twixes
3. **Team West: Cohort filtering** https://github.com/PostHog/product-internal/pull/286/files @EDsCODE 
4. **Infrastructure:** ClickHouse upgraded to 21.11.11.1.111.1, provision a new cluster and migrate over @guidoiaquinti 

# Team sprint planning

For your team sprint planning copy this template into a comment below for each team.

```
Team ___

## Retro

<!-- Talk about what went well, what didn't go well and any actions to improve next time -->

- 

## Hang over items from previous sprint

<!-- For each item, decide to re-prioritise (and add below) or deprioritise -->

- Item 1. prioritised/deprioritise

## Planning

<!-- Each item should have a single owner. Owner can only be an engineer. -->

### High priority

-

### Low priority / side quests

-

```

**Comment by mariusandra** [comment]
Team ~~East~~ The One on the Right Side of the ...

## Retro

- @clarkus - Lots of good deeply technical discussions.
- @pauldambra - Quite a bit of sync time. Enjoyed the couple of weeks.
- @Twixes - pretty good. Getting a lot of useful stuff out. Cooperated well.
- @mariusandra - good sprint, happy with stuff that got done and everyone else as well

## Hang over items from previous sprint

- @Twixes - some items left over from [the project](https://github.com/PostHog/posthog/projects/15), but will be wrapped into insights quality.
- @mariusandra - same
- @pauldambra - possibly: feature flag view mode

## Planning

- [RFC: Nail Insights Quality Again](https://github.com/PostHog/product-internal/pull/290) - @mariusandra @pauldambra 
- [RFC: Great Demo Data](https://github.com/PostHog/product-internal/pull/298) - @Twixes

**Comment by yakkomajuri** [comment]
# Team Ingestion

## Retro

- @tiina303: we could have planned more efficiently
    - would a stricter process be useful?
- @yakkomajuri: fully supporting others as a priority is demotivating
- @marcushyett-ph: sprint was inefficient yet very effective/impactful

Overall a great yet very draining sprint.

## Hang over items from previous sprint

n/a

## Planning

**Goal:** Have an MVP ready for persons data on new events (completed up to step 6 of [the project](https://github.com/orgs/PostHog/projects/41/views/1?visibleFields=%5B%22Title%22%2C%22Assignees%22%2C2635782%2C%22Status%22%2C2619643%2C2619894%5D)).

### Priorities

https://github.com/orgs/PostHog/projects/41

**Comment by EDsCODE** [comment]
### Priorities (they've shifted a bit after offsite and support hero schedule)

Focus on billion scale event querying — With the work done by the ingestion team, it makes sense to double down on making these improvements sooner rather than later to unlock better querying
- Async query dispatch (part of the hackathon that was necessary for direct sql querying)
- Refactor queries in a backwards compatible way to utilize person on events
Cohort Filtering Interface
- Designs get completed
- Designs are implemented

Stretch goals:
Onboarding
- Get this RFC ready for work for next sprint

Data management
- Use the new live events table
