### ISSUE TITLE
Weird results when using monthly active + grouped by month

### ISSUE THREAD

**Issue by timgl** [PostHog/posthog#9160]
## Bug description

This happens when grouped by date:
<img width="1121" alt="image" src="https://user-images.githubusercontent.com/1727427/159365052-45bed4e7-250f-4371-bc28-ca5506b50e6d.png">

This happens when grouped by month:
<img width="1105" alt="image" src="https://user-images.githubusercontent.com/1727427/159365119-cbeabb3e-2a9c-478d-bda8-a887bf37edd5.png">

## Expected behavior

I think we should disable the option to pick grouped by if any of the graph series are weekly active or monthly active users, and in the API forcefully revert to showing by day?

I don't fully understand the current behaviour.

## How to reproduce

1.
2.
3.

## Environment

- [ ] PostHog Cloud
- [ ] self-hosted PostHog (ClickHouse-based), version/commit: _please provide_
- [ ] self-hosted PostHog (Postgres-based, legacy), version/commit: _please provide_

## Additional context

cc @EDsCODE

**Comment by EDsCODE** [comment]
The monthly active/weekly active ideally should respect the time ranges and intervals. Right now, there's inconsistency with how the dates are handled when the math is applied. I picked this up earlier today will fix it and update here.

**Comment by Twixes** [comment]
This is solved.
