### ISSUE TITLE
Lifecycle showing events count, not users count

### ISSUE THREAD

**Issue by timgl** [PostHog/posthog#9164]
## Bug description

When creating a lifecycle insight it shows the count of # of events, not users. 

## Expected behavior

I would expect it to show # of users.

## How to reproduce

1. Create insight
2.
3.

## Environment

- [ ] PostHog Cloud
- [ ] self-hosted PostHog (ClickHouse-based), version/commit: _please provide_
- [ ] self-hosted PostHog (Postgres-based, legacy), version/commit: _please provide_

## Additional context

cc @EDsCODE. Requested by a non-paying cloud user so lower priority.

**Comment by mariusandra** [comment]
The bug is actually something else. Filters don't do anything on the lifecycle page:

![2022-03-31 17 20 09](https://user-images.githubusercontent.com/53387/161091011-5e7ae680-f67e-45a1-93ee-a4db1040d5dd.gif)
