### ISSUE TITLE
Cache layer for person ID and properties

### ISSUE THREAD

**Issue by yakkomajuri** [PostHog/posthog#9179]
We'll need a cache layer for person ID and person properties. Maybe also for groups, but we can toss that up for later.

We'll be using Redis for this (unless a very strong reason comes up down the line to not do so). 

What needs to be done:

- [ ] Create a separate database in Redis to host this data for logical separation
- [ ] Implement the usage of this cache on the plugin server (getting, setting, TTLs)

The cache needs to account for:

- Person properties
- Person ID
- Person created_at
- Group properties

**Comment by neilkakkar** [comment]
Curious how this cache is populated when, say, redis restarts?

Or, what are our invariants, if any, with events that have already been ingested with properties? How far back would we need to go to get all properties?

**Comment by yakkomajuri** [comment]
The source of truth for person data will continue being Postgres. Currently we don't depend on ClickHouse for ingestion (given Kafka).

Thus, the flow is:

1. Event comes in 
2. Look up cache for distinct ID
3. No cache found, hit Postgres for the data
4. Update the cache

It truly is _just a cache_, used to prevent us from overloading Postgres with calls. So it's perfectly fine if Redis restarts.

**Comment by tiina303** [comment]
> Create a separate database in Redis to host this data for logical separation

* There's logical databases 0-14, however they can't be used with redis cluster (only 0 available there, [ref](https://redis.io/commands/select/)), which self hosted users could be using?
* Having a separate Redis setup seems to add complexity to  setup/infra

=> so I'd propose we don't do this (at least for now)

Looked into TTL and expiry. The problem we need to avoid is Redis running out of memory.
* Looked into key expiry and we'd likely want to configure our Redis to be "volatile-lru" (the default is "noexpire" but I haven't looked into if we change or set it anywhere in our code)
* so the existing keys that don't have expiry won't be expired on running out of memory
* to take advantage of the expiry we need to have the keys at the top level, e.g. distinct_id_to_person_id_<distinct_id>: <person_id> or potentially for less memory pid_<distinct_id>:<person_id>  etc ([cant_expire_hash_entries](https://github.com/redis/redis/issues/6620), [could_do_top_level](https://stackoverflow.com/a/55584571/1189132))

**Comment by tiina303** [comment]
What's needed to close this:

- [x] code to write to redis
- [ ] verifying redis configs are set up properly on cloud & self hosted for expiring keys if we're running out of space
- [ ] roll out to cloud fully
