### ISSUE TITLE
Start writing events with person data

### ISSUE THREAD

**Issue by yakkomajuri** [PostHog/posthog#9180]
We'll need to update the plugin server code to send event messages to Kafka with the new columns.

This requires leveraging the cache, adding the update logic, and sending the right data to Kafka. 

The flow should be:

1. Event is about to be processed
2. Check the cache
3. Update Postgres and the cache if necessary
4. Produce the event to Kafka

**Comment by tiina303** [comment]
We might want to roll this out gradually on cloud, i.e. gate by team_id < ENV
