### ISSUE TITLE
Create the live events table

### ISSUE THREAD

**Issue by yakkomajuri** [PostHog/posthog#9183]
This is a pretty cool concept that will allow us to give users immediate feedback about events coming into the platform, which will significantly help things like debugging and onboarding. 

On Cloud, it's quite feasible that users will see events in the UI within a second. 

## How it works

We set up a separate table that reads from the `events_plugin_ingestion` topic (the topic we use to send events from Django to the plugin server). This table will only hold data temporarily.

Then, to display the live events table, a merged table consisting of `events` and `live_events`, which will allow us to deduplicate events. Querying it will look something like this:

```sql
SELECT 
    uuid, 
    event, 
    team_id, 
    distinct_id,
    argMax(properties, _timestamp) as properties, 
    argMax(elements_chain, _timestamp) as elements_chain, 
    max(timestamp) as timestamp,
    max(created_at) as created_at,
    argMax(_table, _timestamp) as source_table
FROM merge('posthog', '^(events|live_events)$')
GROUP BY uuid, event, team_id, distinct_id, _timestamp
```

We can then use the `source_table` field to display to users in the UI somehow (maybe some light shading) that an event is still being processed, to set expectations correctly.

**Note** that `_timestamp` is the Kafka timestamp of the message, so `_timestamp` for a given UUID on `events` will always be higher than the `_timestamp` for the same UUID on `live_events`

**Comment by neilkakkar** [comment]
This is a part of persons on events because ingestion is going to slow down? Do we have an idea of how much slower yet?
Is this purely a nice to have, or a more unlocking-onboarding feature?

**Comment by yakkomajuri** [comment]
Great questions.

------

> This is a part of persons on events because ingestion is going to slow down?

Correct.

> Do we have an idea of how much slower yet?

The overall impact of all our changes (except the buffer) might be negligible, but either way, we don't know yet.

As for the buffer, we need to try different windows to strike a balance, but the magic number being thrown around currently is 60 seconds for $identify events and events from identified users within a few minutes of the first $identify.

> Is this purely a nice to have, or a more unlocking-onboarding feature?

It's part of achieving the [Ingestion team's goals](https://posthog.com/handbook/people/team-structure/platform#ingestion), as we've determined that what we really care about is some immediate feedback about events coming in, they don't need to be fully processed within seconds.

It's not an **absolutely essential** part of this project but it becomes more important given we'll be slowing ingestion down for some events.

The other arguments for doing this now are:

a) We should do it at some point, but there will always be things that are more "on fire"
b) Given we're collaborating across Ingestion <> App this is a good time to work on small changes to the API/UI components owned by the app team.

The infra side is mostly done as well. #9138

**Comment by yakkomajuri** [comment]
cc @liyiy

**Comment by liyiy** [comment]
What idea did you have in mind in how you wanted to incorporate this during onboarding? For `onboarding 1` we're already scoped on what we're going to plan and execute for next sprint (mostly changes to the ingestion wizard screen), so happy to take any ideas and suggestions from this into `onboarding 2` 🤗

**Comment by yakkomajuri** [comment]
So effectively this project will enable events to show up in the UI within around a second. That makes onboarding _much_ faster at the "waiting for events" step.

I have all the infrastructure effectively ready to go, someone just needs to tell me they're interested and I'll ship that and they need to then implement a query like the one in the description to use for the onboarding events check

**Comment by clarkus** [comment]
That does sound like something that could improve our target metric. How much effort would it take to incorporate this and could it happen within the timeframe for the current scope of onboarding? I think it sounds like a good change, but I also know y'all's team is pretty booked this sprint. Worst case scenario - we can proceed with the current plan and then loop back to swap the queries to improve performance.

**Comment by yakkomajuri** [comment]
Well so our side of things is mostly done in #9138. This is also on our roadmap so I'd gladly prioritize if it means we get to both work together to get this over the line. 

The API is owned by the App team anyway so I'd have had to loop your side in for it sooner or later and this just seems like the right opportunity.
