### ISSUE TITLE
Add the async migration to populate the events table

### ISSUE THREAD

**Issue by yakkomajuri** [PostHog/posthog#9186]
Once we have all the ingestion setup in place, we need to populate the events table with the right data.

To do so, we'll write an async migration.

Here's one suggested approach:

Emit duplicate events and optimize partition by partition.

That's just one suggestion. We should think about this more deeply when we get here.

**Comment by yakkomajuri** [comment]
I've been doing some testing with this today. Nothing yet at scale to get a time estimate, but I have a working approach:


```sql
-- Set up a dictionary for each table we will query, this will issue queries to the underlying table if the 
-- value doesn't exist yet, and will update the cache accordingly

-- Dictionary for `groups` - we get the properties using the existing $group_N materialized columns
CREATE DICTIONARY group_dict ON CLUSTER 'posthog' ( group_key String, group_properties String) 
PRIMARY KEY group_key 
SOURCE(CLICKHOUSE(TABLE groups DB 'default' USER 'default')) 
LAYOUT(complex_key_cache(size_in_cells 10000)) -- currently arbitrary, need to consider this value more carefully
Lifetime(60000) -- same as above

-- Dictionary for `person_distinct_id` - we get the person_id using the distinct_id in the event
CREATE DICTIONARY pdi_dict ON CLUSTER 'posthog' (distinct_id String, person_id UUID) 
PRIMARY KEY distinct_id 
SOURCE(CLICKHOUSE(TABLE person_distinct_id DB 'default' USER 'default')) 
LAYOUT(complex_key_cache(size_in_cells 10000)) 
Lifetime(60000)


-- Dictionary for `person` - we get the properties using the value we 
-- get from fetching the person_id from the distinct_id
CREATE DICTIONARY person_dict ON CLUSTER 'posthog' (id UUID, properties String) 
PRIMARY KEY id 
SOURCE(CLICKHOUSE(TABLE person DB 'default' USER 'default')) 
LAYOUT(complex_key_cache(size_in_cells 10000)) 
Lifetime(60000)

-- This is needed because `dictGet` operations are not deterministic
-- We need to ensure ourselves that the dictionary exists in every node in the cluster (`ON CLUSTER` should do it)
SET allow_nondeterministic_mutations=1

ALTER TABLE sharded_events 
ON CLUSTER 'posthog'
UPDATE 
    person_id=toUUID(dictGet('pdi_dict', 'person_id', distinct_id)),
    -- for person properties we need to do 2 lookups
    person_properties=dictGetString('person_dict', 'properties', toUUID(dictGet('pdi_dict', 'person_id', distinct_id))),
    group0_properties=dictGetString('group_dict', 'group_properties', $group_0),
    group1_properties=dictGetString('group_dict', 'group_properties', $group_1),
    group2_properties=dictGetString('group_dict', 'group_properties', $group_2),
    group3_properties=dictGetString('group_dict', 'group_properties', $group_3),
    group4_properties=dictGetString('group_dict', 'group_properties', $group_4)
WHERE 1
```

The beauty of this approach is that it should be much faster than other methods using inserts etc.

### Considerations

#### Inconsistency around conversions

The main consideration is how the tables might change during the migration. Note that this would be a problem with any approach essentially.

For properties this is something we could _potentially_ ignore, but it gets tricky with `person_id`.

Consider what might happen if during the migration an `$identify` event comes in - the events we've migrated so far will get `person_id == old_id` and the others will get `person_id == new_id`.

We can mitigate this by e.g. detaching `person_distinct_id_mv` temporarily, which will ensure that the all past events get the same ID. The problem here is that the conversion might then be lost.

The best thing we could do to ensure consistency is completely stop ingestion. This sounds outrageous but might be doable if we carefully consider it (think "do things that don't scale). Some considerations:

1. How long will the migration take? If it will cause e.g. 3 hours of ingestion delay for our largest self-hosted user, might be worth it?
2. We can do this team-by-team on Cloud and maybe ignore the problem with Suprdaily?
3. How big of a problem is this really? How many events would actually have this problem? Can we test it? It is a niche case? 

Honestly, it **might be that we can just ignore it.** Provided we've been producing _new_ events for a week or so with these properties, the problem should be minimal. How can we control this on self-hosted though? Maybe add a precheck to the async migration that ensures it's been at least a week since events have been getting the new columns populated? This is easily doable. 

#### Memory usage

Need to consider each instance and how the dictionary should be set up.

#### Sharding

How will this work with our sharded setup?

### Next steps

1. Get a better sense of the problem outlined above
2. Get a better sense of how much time this will take to run
3. Get a better sense of memory usage
4. Get a better sense of how this will work with our sharding setup

**Comment by yakkomajuri** [comment]
cc @EDsCODE @tiina303

**Comment by yakkomajuri** [comment]
Note that the good thing about this is that it provides us a working mechanism for backfilling data such that we can run this locally and in the playground in order to start writing queries.

**Comment by tiina303** [comment]
> Consider what might happen if during the migration an $identify event comes in - the events we've migrated so far will get person_id == old_id and the others will get person_id == new_id.

As we discussed in the meeting yesterday `$identify` shouldn't change the identified person's id otherwise we'd have problems with every later login. However alias could do that. Considering other corners we're cutting this one seems fine to cut too.

**Comment by macobo** [comment]
We can close this for now - any follow-up work is going to be handled separately anyways.
