### ISSUE TITLE
Nuke protobuf

### ISSUE THREAD

**Issue by yakkomajuri** [PostHog/posthog#9207]
The persons on events changes we're about to start making require sending new bits of data over through Kafka. These would require changes in the protobuf schema but honestly we might be better off just dropping it at this stage.

@macobo has done some on the initial legwork to support non-protobuf messages on https://github.com/PostHog/posthog/pull/8333 but I suggest we make the move now.

This would require:

1. Setting up a new Kafka topic (manually on Cloud, self-hosted topics are auto-created)
2. Setting up a new set of Kafka + MV tables to consume from the topic into `writable_events` 
3. Begin sending all new events in a JSON encoded format to the new JSON topic
4. Keep the protobuf topic and tables around for a release and then nuke it on the following one, so we ensure all events from that path are correctly processed
5. Remove all the related code

A gotcha here is at step 2. What if the user isn't sharded but becomes sharded during this transition? We probably need to retroactively update the sharding async migration to drop and recreate the MV for the JSON topic as well in order to do this so that we write to the correct table.

**Comment by guidoiaquinti** [comment]
More context at https://github.com/PostHog/posthog/issues/8334

**Comment by yakkomajuri** [comment]
Did I miss anything @macobo @guidoiaquinti @hazzadous @fuziontech

**Comment by yakkomajuri** [comment]
I'll take the thumbs up as "no I didn't miss anything" rather than a "yes" response to the question and move on :D

**Comment by guidoiaquinti** [comment]
You didn't miss anything 👍 😉 (I think)

**Comment by yakkomajuri** [comment]
Well so this was done but now #9368 became a part of this work as well
