### ISSUE TITLE
Allow creating a new dashboard from the add insight to dashboard modal

### ISSUE THREAD

**Issue by u-ashish** [PostHog/posthog#9221]
## Is your feature request related to a problem?

- I make an insight, and want to save it and add to a dashboard.
- I click add to dashboard.
- I then have an epiphany about grouping this insight into a new dashboard.
- I can only add to an existing dashboard.

## Describe the solution you'd like

Allow creating a new dashboard from the add insight to dashboard modal.
<img width="1215" alt="Screen Shot 2022-03-23 at 2 48 48 PM" src="https://user-images.githubusercontent.com/14264791/159783914-9d9906b2-8ba5-41ed-a4f2-c0b5796ec889.png">

## Describe alternatives you've considered

Open a new tab, create a new dashboard, go back to original tab, add insight to dashboard

## Additional context

n/a

**Comment by u-ashish** [comment]
Ahhhh you can do this

**Comment by u-ashish** [comment]
<img width="1185" alt="Screen Shot 2022-03-23 at 2 52 13 PM" src="https://user-images.githubusercontent.com/14264791/159784185-098280b1-2310-4986-9e8a-169bd62b80d7.png">

It's at the bottom of the dropdown 🙈 -- maybe nice to make that more obvious by making it the first item in the list (or not haha)

**Comment by clarkus** [comment]
I think there's still value to the issue! We could definitely make that action more obvious and easier to find.

**Comment by clarkus** [comment]
@Twixes here's a [quick sketch](https://www.figma.com/file/gQBj9YnNgD8YW4nBwCVLZf/PostHog-App?node-id=8513%3A49745) based on the work @rcmarron recently did for selecting a default dashboard. The key differences are that we are describing dashboards with multiple attributes (name, description, sharing) but more could be considered like tags or the list of users with access. The goal is just to make it easier to identify the dashboard you're looking for. Secondary to that it adds a type-ahead search to filter the list of dashboards. Lastly it adds a tertiary action to leave this flow and instead create a new dashboard which will contain this insight as the only item. On completion the user should be taken to the newly created dashboard. so they can adjust layout, add more insights, share it, etc. Happy to make revisions based on your guidance. 👍 

![Add to dashboard](https://user-images.githubusercontent.com/254612/159787855-8f3c45f5-c3b1-40b7-83c1-e2bf0fd1dcd5.png)

Thanks for filing this, @u-ashish

**Comment by Twixes** [comment]
This should be fully resolved soon as the above UI is now implemented behind a feature flag!
