### ISSUE TITLE
Dashboard descriptions can extend to page-level actions

### ISSUE THREAD

**Issue by clarkus** [PostHog/posthog#9241]
## Bug description

A sufficiently long description will reach all the way to the page actions and create an unclear hierarchy - specifically the edit description link feels a bit orphaned and detached form the thing it modifies.

<img width="717" alt="Screen Shot 2022-03-24 at 9 18 35 AM" src="https://user-images.githubusercontent.com/254612/159962244-dcf2d098-097d-407d-accb-e29db9eded53.png">

## Expected behavior

Constrain the description width such that it doesn't overlap with page level actions. Try to ensure that line lengths are optimized for easy reading. 

## How to reproduce

1. View a dashboard with a lengthy description

## Environment

- [x] PostHog Cloud

**Comment by Twixes** [comment]
This'd also be pretty good because button wrapping would be more sensible then. 🤔 Currently on narrow viewports they go between the title and caption, but below the caption would probably be better.

**Comment by corywatilo** [comment]
There's also some weirdness in Experiments when a description is too long - pushes the buttons to the next row

<img width="1376" alt="image" src="https://user-images.githubusercontent.com/154479/187477033-f6e33eca-0096-4a0e-8b08-47317ed05887.png">
