### ISSUE TITLE
Add the ability to set custom timestamp fields on person properties

### ISSUE THREAD

**Issue by dylanlarrivee** [PostHog/posthog#9245]
## Is your feature request related to a problem?

I would like the ability to filter an Insight report based off of a `joinDate` timestamp field I would set for the user. Currently, when I set a field with a date time format it is set as a string and I am unable to filter it as a date the way I am with the posthog Time field which pulls up a date picker.

## Describe the solution you'd like
I would a way to set a custom person field as a date time format in the same way that the posthog Time field is formatted.

**Comment by pauldambra** [comment]
@alexkim205 It's this code that handles the date _querying_ https://github.com/PostHog/posthog/blob/master/ee/clickhouse/models/property.py#L276

And I think that's used for person properties as well as event properties

So I think if we introduced detection on ingestion in the plugin server everything else would "just work"™️ (famous last words)
