### ISSUE TITLE
Rename breakdown items

### ISSUE THREAD

**Issue by lnhrdt** [PostHog/posthog#9261]
## Is your feature request related to a problem?

The breakdowns feature is very useful but sometimes the values in the breakdowns are not very intuitive for our whole team to understand. For example, we have a chart that has a breakdown on `utm_content` which we've setup to be the ID of an Ad in Facebook Ad Manger (i.e. a long numeric string). I'd like to rename it to something that our team recognizes (e.g. "march 2022 advert 3"). Another scenario is when `utm_content` isn't populated it gets aggregated into a category called `(empty string)`. I'd like to edit that one to something easier to understand by non-technical folks.

## Describe the solution you'd like

I have 2 ideas that I think could work from my perspective:
1. Rename breakdown categories within a chart. Similar to how we can rename Funnel Steps.
2. Define translations for property values in Data Management.

## Additional context

This is a followup from the community support channel.
https://posthogusers.slack.com/archives/C01GLBKHKQT/p1647985397959249

**Comment by MarconLP** [comment]
This would be possible using the following HogQL breakdown:
```
multiIf(
    properties.facebook_ad_manager == 'id_2839723984', 'Winter campaign',
    properties.facebook_ad_manager == 'id_4728943243', 'Some other campaign', 
    'other facebook campaigns'
)
```

**Comment by lnhrdt** [comment]
Good to know HogQL is an option. However that raises the technical bar for my team (not all engineers). Is there any way to do this in the UI?

**Comment by lnhrdt** [comment]
Good question. Sometimes campaigns are renamed for clarity, but IDs never change.

I understand that's a tradeoff here. Perhaps we'll reconsider the practice if we continue tracking in Posthog. Thank you for chiming in!
