### ISSUE TITLE
$set field is detected as a boolean whereas it's sent as a string

### ISSUE THREAD

**Issue by scleriot** [PostHog/posthog#9269]
## Bug description

When we `identify` a user, we use `$set` to set a person email address. It lets us create cohorts based on email domains.

This `email` field is detected as a boolean, whereas we send a string. This means that we cannot use "includes" when creating a cohort

Example of identify event from Live Events view:
![image](https://user-images.githubusercontent.com/733474/160430890-18ece5b7-609d-4542-923b-6cef815b7fb6.png)

![image](https://user-images.githubusercontent.com/733474/160441025-6da4986b-8477-4e14-9794-3a8a3e58c709.png)

## Expected behavior

The field should be detected as a `string` type

## Environment

- [x] PostHog Cloud
- [ ] self-hosted PostHog (ClickHouse-based), version/commit: _please provide_
- [ ] self-hosted PostHog (Postgres-based, legacy), version/commit: _please provide_

**Comment by pauldambra** [comment]
Hey @scleriot, thanks for the report! Are you on PostHog cloud or self hosted?

**Comment by scleriot** [comment]
Hello @pauldambra, we're on PostHog Cloud

**Comment by pauldambra** [comment]
Hey @scleriot I've set it to String for you. I _think_ it's a UI bug since we don't currently detect types on person properties. But didn't want you to have to wait for a fix for that

**Comment by pauldambra** [comment]
Yes! It is a UI bug. We show the properties table in multiple contexts and show person properties inside the events properties table. #9278 fixes that confusing display. Thanks for reporting @scleriot
