### ISSUE TITLE
Can't delete blank filters

### ISSUE THREAD

**Issue by jamesefhawkins** [PostHog/posthog#928]
**Describe the bug**
If you click out of a blank filter on the /trends page, you can't remove the filter.

This came up a couple of times during user onboarding.

**To Reproduce**
1. Do this: ![Screenshot 2020-06-05 at 10 25 36](https://user-images.githubusercontent.com/47497682/83860240-f0d79200-a716-11ea-8b1f-1c34f370a144.png) 
2. Click out of it
3. See the blank filter is still there - no way to remove it: 
![Screenshot 2020-06-05 at 10 25 40](https://user-images.githubusercontent.com/47497682/83860291-fe8d1780-a716-11ea-927d-07dfdd65e646.png)

**Expected behavior**
It should either be impossible to save a blank filter and clicking "out" of the filter doesn't add it, or it should be possible to delete filters with an x icon.

**Comment by jamesefhawkins** [comment]
@EDsCODE FYI from yesterday's onboarding

**Comment by timgl** [comment]
Fixed in #993
