### ISSUE TITLE
Easily switch the time span for all insights on a dashboard

### ISSUE THREAD

**Issue by lsmith77** [PostHog/posthog#9284]
## Is your feature request related to a problem?

I have a dashboard that currently looks at almost a dozen insights over a 7 day span, would be cool to be able to easily see those same insights on a different time span.

## Describe the solution you'd like

A single selector change the time span for all insights on the dashboard

## Describe alternatives you've considered

A copy all insights with different time span.

**Comment by Twixes** [comment]
Hi @lsmith77, have you tried using this selector on the dashboard?
<img width="222" alt="Screen Shot 2022-03-31 at 10 10 54" src="https://user-images.githubusercontent.com/4550621/161031837-ad75e6b1-a917-49c3-8bec-337765f8e2ff.png">
This should allow you to switch the timespan for all insights on the dashboard at once.

**Comment by lsmith77** [comment]
ah thx .. because the label was “Custom” on the dropdown, I didn’t realize this is where I could adjust the time span. thx for the screenshot.
