### ISSUE TITLE
Console error when defining an action with toolbar

### ISSUE THREAD

**Issue by corywatilo** [PostHog/posthog#9286]
## Bug description

When inspecting an element on posthog.com with the toolbar and defining an action, the action saves but the UI breaks and there's a console error.

https://www.loom.com/share/164f35075c114111b1d7cfe28a604b0b

## Expected behavior

Don't do what happens in the video.

## How to reproduce

1. Navigate to posthog.com with the toolbar enabled
2. Inspect a feature in the hero and define it with a name, text, and URL
3. Save it and watch the console

## Environment

- [X] PostHog Cloud

**Comment by pauldambra** [comment]
we don't have the text "can not use selector" in our projects let's assume this is accidentally fixed
