### ISSUE TITLE
Segment integration

### ISSUE THREAD

**Issue by timgl** [PostHog/posthog#929]
**Is your feature request related to a problem? Please describe.**
I want to send events to posthog from segment

**Describe the solution you'd like**
We've been approved to the segment developer console, so we can start building this integrations.

In Segment, there's two types of integrations. One is Segment just sends you events using a webhook, the other allows you to inject your javascript on the clients' website. If we want autocapture/toolbar etc, we'll need the latter, but I think it's not yet public. Will need to dig into this.

**Describe alternatives you've considered**

**Additional context**

***Thank*** you for your feature request - we love each and every one!

**Comment by Twixes** [comment]
Can this be considered done?

**Comment by yakkomajuri** [comment]
Yes it can, I'm closing this.

**Comment by yakkomajuri** [comment]
This does raise a great point though, that our Segment page is not on the sidebar. WIll fix it now.

https://posthog.com/docs/integrations/segment-integration
