### ISSUE TITLE
Event api pagination

### ISSUE THREAD

**Issue by EDsCODE** [PostHog/posthog#930]
**Describe the solution you'd like**
Use the "next" url when event logic clicks load more

**Describe alternatives you've considered**
Leave it as is 

**Additional context**
There's a very slight edge case the way the pagination is done right now in the event logic. if there's ever a gap in events for a period of weeks, the event table will be empty with a load more b utton that won't do anything until you click it enough times to go back in time. This is much less a legitimate issue but more a code quality consideration

***Thank*** you for your feature request - we love each and every one!

**Comment by safwanrahman** [comment]
I would like to work on this. Can anyone assign it to me?

**Comment by Twixes** [comment]
Sure, have a go at it and make a PR when ready! @safwanrahman

**Comment by timgl** [comment]
@safwanrahman Hey, just checking whether you're still interested in working on this?

**Comment by safwanrahman** [comment]
@timgl Sorry I almost lost it! I will work on this this weekend! 😁

**Comment by timgl** [comment]
Awesome!

**Comment by EDsCODE** [comment]
I don't recall how to reproduce the issue as I checked and the logic does seem sound. There still is a code cleanliness issue where we pass back a well-formed [next request url](https://github.com/PostHog/posthog/blob/master/posthog/api/event.py#L206) but then the frontend [doesn't utilize it ](https://github.com/PostHog/posthog/blob/master/frontend/src/scenes/events/eventsTableLogic.js#L202)

Feel free to scope this ticket down to that issue!

**Comment by paolodamico** [comment]
@alexkim205 for you to review if we still want to do this

**Comment by alexkim205** [comment]
Not sure if this is relevant anymore with the live events loading logic. Closing this issue.
