### ISSUE TITLE
Pie chart graph series labels not populating

### ISSUE THREAD

**Issue by sdilsner-va** [PostHog/posthog#9303]
When creating a Trend with the Chart type "Pie" the customized labels for the pageviews aren't populating in the graph when hovering. It's instead showing "$pageview: 000".
![image](https://user-images.githubusercontent.com/19272940/160917037-da8f26e6-eb81-4651-b72b-cd1b489249cf.png)

## Expected behavior
Show customized labels on hover in the chart

## How to reproduce

1. create a trend with "pageview" as the graph series
2. click edit icon to "rename graph series"
3. set chart type to "pie"
4. hover chart to see label is showing as "$pageview: 000"

## Environment

- self-hosted clickhouse PostHog, version 1.33.0

**Comment by Twixes** [comment]
This should work properly now.
