### ISSUE TITLE
Bar Chart showing different/incorrect results

### ISSUE THREAD

**Issue by mrzmyr** [PostHog/posthog#9305]
## Bug description

When using Chart Type `Value` the chart shows different data on a single view vs. embedded in a dashboard.

<img width="575" alt="CleanShot 2022-03-30 at 22 17 06@2x" src="https://user-images.githubusercontent.com/746429/160923407-4149a10c-9644-493a-a8c0-36a020f14a31.png">

<img width="1168" alt="CleanShot 2022-03-30 at 22 16 58@2x" src="https://user-images.githubusercontent.com/746429/160923419-f114533b-c162-4aa5-9415-dc1f44d0b62c.png">

## Expected behavior

- Show same results on single and dashboard view

## How to reproduce

1. Select `Trend`
2. Breakdown by X
3. Use Chart Type `Value`
4. Check on preview page
5. Compare when added to a Dashboard

## Environment

- [x] PostHog Cloud
- [ ] self-hosted PostHog (ClickHouse-based), version/commit: _please provide_
- [ ] self-hosted PostHog (Postgres-based, legacy), version/commit: _please provide_

**Comment by BillCarsonFr** [comment]
I have a similar issue when I click on a chart from the dashboard it's showing me the insight view but with a mix of data. The title is the good one but the data/query are from another similar chart. Work around is to refresh before starting any editing/saving (that are modifying the wrong chart)
