### ISSUE TITLE
Resume experiments functionality

### ISSUE THREAD

**Issue by liyiy** [PostHog/posthog#9332]
## Is your feature request related to a problem?

User reported accidentally clicking and completing an experiment. It might be annoying to create a new experiment again if the experiment has been running for a while. The "finish experiment" button could either be more shielded from accidental clicks OR we could have a pause experiment functionality? Not 100% sure about the effects on statistical significance if we do that @neilkakkar 

*Please describe.*

**Comment by neilkakkar** [comment]
Hey Li, do you have a link to this conversation?

Pausing an experiment doesn't yet make sense to me. When would you want to do that?

Makes sense about accidentally finishing an experiment though. Could also make this reversible, as in 'undo finishing experiment'.
