### ISSUE TITLE
Show legends on graphs

### ISSUE THREAD

**Issue by prawnsalad** [PostHog/posthog#935]
**Is your feature request related to a problem? Please describe.**
It is difficult to know what data actually means on a dashboard

**Describe the solution you'd like**
To show legends on graphs so that people know what they are looking at

**Describe alternatives you've considered**

**Additional context**
Looking at these graphs, you have no idea what each series is referencing.

![image](https://user-images.githubusercontent.com/725880/83951930-1eaefa80-a82d-11ea-846b-610edb5389a0.png)

***Thank*** you for your feature request - we love each and every one!

**Comment by hgezim** [comment]
I want to add +1 to this.

One graph I got even shows same colors for 2 different lines:
![CleanShot 2020-11-18 at 12 54 12](https://user-images.githubusercontent.com/124675/99580936-53f37300-299d-11eb-86ba-6abf367786b8.png)

**Comment by macobo** [comment]
cc @EDsCODE, cc https://github.com/PostHog/posthog/issues/3338

How mixp@nel does this:

![2021-02-19_17-25](https://user-images.githubusercontent.com/148820/108524223-79af5180-72d7-11eb-9ebf-4b580ecca9e4.png)

I think it makes sense to:
1. Show it outside the graph (either on the left or as a button on the graph)
2. Allow toggling values on-off

**Comment by paolodamico** [comment]
We now show legends on graphs!
