### ISSUE TITLE
Python ClickHouse Client work required for Async Querying in Production

### ISSUE THREAD

**Issue by fuziontech** [PostHog/posthog#9350]
What we need to do to get async querying (from Metahog hackathon project) into production! 🚢 

- [ ] Split out feature changes from hackathon branch
- [ ] Gzip results in Redis to reduce payload footprint
- [ ] Tests Tests Tests
- [ ] Support for any tweaking required for frontend work

Feel free to edit this with any other work that may be required or suggestions!

**Comment by rcmarron** [comment]
This is great, a few things I think we should consider that might impact things:
* How this cache related to the existing results cache (maybe they should be the same?)
* Can we make it so the query_id is derived from the insight/filters being submitted, so if a user refreshes a page, they don't have to restart the query
    * If we do the above, we should probably have a mechanism for 'restarting' the query, and when the status/results are retrieved only retrieving the most recent.
