### ISSUE TITLE
Support funnel step reordering

### ISSUE THREAD

**Issue by prawnsalad** [PostHog/posthog#936]
**Is your feature request related to a problem? Please describe.**
I need to add a new step at the start of my funnel but I can't just insert a new one or move one to the start. I have to delete all existing actions+filters and start again.

**Describe the solution you'd like**
To click + drag actions to reorder them in the list.

**Describe alternatives you've considered**

**Additional context**

***Thank*** you for your feature request - we love each and every one!

**Comment by glmaljkovich** [comment]
Hey guys, I would like to work on this (this time hopefully with a faster response time 😁 )
For this feature would you be open to incorporating [third-party libraries](https://github.com/clauderic/react-sortable-hoc) or rather have the drag-and-drop behaviour implemented from scratch?

**Comment by timgl** [comment]
@glmaljkovich Awesome! We already have react-grid-layout so we should be able to re-use that for this I think?

**Comment by glmaljkovich** [comment]
Excellent! Yup, that should work.

**Comment by paolodamico** [comment]
+1 from [customer call](https://docs.google.com/document/d/1gJlsUDrlW7ur8zT5scqRvXZhapm_0JdvKGiw68Iyx9E/edit#heading=h.vb4sunjp4iyb) last week.
