### ISSUE TITLE
Add ability to download recordings

### ISSUE THREAD

**Issue by jackiegreenfield** [PostHog/posthog#9369]
## Is your feature request related to a problem?

We'd like the ability to reference a specific video after the 3 week period. 

## Describe the solution you'd like

We'd like to be able to download the videos. We currently use MouseFlow, and they allow that functionality. It makes it easier to share videos as well.

## Describe alternatives you've considered

Another option could be to mark the video as "keep", and that would prevent it from being wiped with all of the others. Similar to how zoom auto-deletes recordings after 30 days, but you can mark them as not for auto-deletion. 

## Additional context
We plan to use recordings for the follow reasons:
- Auditing/compliance
- Usability / how a feature is used
- Customer troubleshooting

In any of these use cases, there will be times when we want to keep a specific video longer.

**Comment by pauldambra** [comment]
posthog bot was keen to close as not planned.

you _can_ export recordings and play them back later, and pinning a recording stores it for 1 year
