### ISSUE TITLE
Person Name/Email are case sensitive

### ISSUE THREAD

**Issue by SimeonC** [PostHog/posthog#9378]
## Bug description

When Identifying the `name` and `email` user attributes, I've used `Start Case` to make it easier for less technical users to read. eg `posthog.identify('id', { Name: 'Full Name', Email: 'xxx@yyy.com' })`.

In the posthog UI this shows up as `User XY38` or similar rather than detecting the name/email.

Could this be changed so that `name` and `email` detection are 

## How to reproduce

1. Send an identify command with capitalised name/email. `posthog.identify('id', { Name: 'Full Name', Email: 'xxx@yyy.com' })`
2. In posthog UI find the person, note that the values are recorded but the name is still the auto-generated name and not the name or email fields.

## Environment

- PostHog Cloud

**Comment by SimeonC** [comment]
I guess an alternative could be to have the UI automatically convert to `Start Case` and make sure the docs say to send params in snake_case or similar.

**Comment by Twixes** [comment]
Hey! Thanks for flagging this, `Email` (along with `Name`) is now supported by default. Though you can also further customize this in Project Settings: https://app.posthog.com/project/settings#person-display-name (for instance, add `Full Name` there).
