### ISSUE TITLE
s3 export plugin files missing timestamp field

### ISSUE THREAD

**Issue by dylanlarrivee** [PostHog/posthog#9386]
## Bug description
Files exported using the `s3 export plugin` do not always have the `timestamp` field from the event.

## How to reproduce

1. Install s3 export plugin 
2. Check files in s3 bucket
3. Not all have timestamp field as expected

## Environment

- [x] PostHog Cloud
- [ ] self-hosted PostHog (ClickHouse-based), version/commit: _please provide_
- [ ] self-hosted PostHog (Postgres-based, legacy), version/commit: _please provide_

## Additional context
Slack thread: https://posthogusers.slack.com/archives/C01GLBKHKQT/p1649350947077839

**Comment by yakkomajuri** [comment]
What's needed here is for us to run `handleTimestamp` before passing the event to `onEvent`/`ingestEvent`
