### ISSUE TITLE
"Export historical events" not found for plugin "Migrator 3000 (Beta)"

### ISSUE THREAD

**Issue by burrowfdn** [PostHog/posthog#9389]
## Bug description

The Migrator 3000 (Beta) errors when trying to migrate events from cloud to hobby instance.

## Environment

- [x] PostHog Cloud
- [x] self-hosted PostHog (ClickHouse-based), 1.34.2/commit: 4f7fe06d258eca726a62ab482a98a5bf1575bb4c

![Screenshot 2022-04-12 at 08 40 48](https://user-images.githubusercontent.com/101738886/162908060-e09b59d0-c210-4f81-9964-b0442f92d190.png)

**Comment by yakkomajuri** [comment]
Hey @burrowfdn! Historical exports are currently disabled on Cloud. What's the use case you have for this migration?

**Comment by burrowfdn** [comment]
We tried the free cloud version and the 10k limit was hit quite early. A hosted hobby version is much better option at this stage. We want to migrate the events captured with the cloud into the hosted instance.

**Comment by burrowfdn** [comment]
the docs says:

> This plugin allows you to migrate events from one PostHog instance to another. You can migrate between self-hosted instances, or from a self-hosted instance to PostHog Cloud (and vice-versa).

@yakkomajuri why is it not possible to migrate the events?

**Comment by yakkomajuri** [comment]
Got it. For now I'd recommend using [our API](https://posthog.com/docs/api/events) to pull events. Historical exports are possible but are in Beta and currently disabled while we improve the functionality.

**Comment by burrowfdn** [comment]
Thank you. Any ETA for when the plugin will be GA?

**Comment by tiina303** [comment]
We have deprecated Migrator 3000, Replicator should be used instead
