### ISSUE TITLE
Fix AWS Fargate for non us-east-1 regions

### ISSUE THREAD

**Issue by timgl** [PostHog/posthog#939]
**Describe the bug**

We've had reports of people struggling to get fargate to work in other regions.

![image](https://user-images.githubusercontent.com/1727427/83956105-6ac06600-a852-11ea-94cd-870fee910df8.png)

As reported by a user

> Ah, I got it working on the command line. I needed to pass `--capabilities CAPABILITY_IAM`; the web console doesn't return this for some reason.

> (Also, oddly, passing in the body of the template as a string doesn't work either. But uploading it to an S3 bucket and using that URL seems to have worked.)

**To Reproduce**
1. 
2. 
3. 

**Expected behavior**

**Screenshots**

**Hosted or self hosted?:**
- hosted/self-hosted
- (if self-hosted) what version?

**Additional context**

**Comment by fuziontech** [comment]
ah, it was because I never merged https://github.com/PostHog/posthog.com/pull/115

merged now. Updated instructions will work in all regions.
