### ISSUE TITLE
Feature Request: Search, for Orgs

### ISSUE THREAD

**Issue by joethreepwood** [PostHog/posthog#9390]
## Is your feature request related to a problem?

I was just discussing a potential client with @charlescook-ph. We wanted to have a look at the info we have on them, but only knew the company name. 

So, I head to the Organizations view in Persons & Groups and...there's no way to search. I can search for Persons, but not Organizations. Or Instances. Or Projects. 

In the end, I had to go to Hubspot, look up the company there and then look for the identified Person in PostHog. 

(Turns out we hadn't id'd the user there either, but that's neither here nor there. Would have been good to just search for the company name in PostHog's organization view.)

## Describe the solution you'd like

Search. 

## Describe alternatives you've considered

Keeping stonily silent and communicating this need to the engineering team through _sheer force of will_ and the _tremendous power of my furrowed brow_. 

Also, adding it to the universal search at the top of the product. Occasionally it strikes me as weird that we have so many search bars.

**Comment by neilkakkar** [comment]
search-everything hackathon project covers this already! Not in prod yet because I was away last week, but good things are coming xD

**Comment by joethreepwood** [comment]
You're the best, Neil.
