### ISSUE TITLE
When saving an insight I get a warning asking if I should discard it

### ISSUE THREAD

**Issue by marcushyett-ph** [PostHog/posthog#9392]
## Bug description

<img width="1183" alt="image" src="https://user-images.githubusercontent.com/85295485/162939840-8d48e786-85ad-41c1-bf71-a31b4123e9e7.png">

## How to reproduce

1. Create a new insight
2. Click Save
3. You see the warning above asking if you'd like to discard it

## Environment

- [x] PostHog Cloud
- [ ] self-hosted PostHog (ClickHouse-based), version/commit: _please provide_
- [ ] self-hosted PostHog (Postgres-based, legacy), version/commit: _please provide_

**Comment by Twixes** [comment]
I haven't been able to reproduce this – seems like very much an edge case. Do you know what _exact_ steps you took that led to this?

**Comment by marcushyett-ph** [comment]
Good shout - it's not a small edge-case though - adding a filter seems to trigger it, this is a video of me starting from a completely fresh insight.

https://user-images.githubusercontent.com/85295485/162983956-433eb61c-4a0a-4411-9bb4-e284b646c440.mov

**Comment by Twixes** [comment]
Ohh, I see, this only happens with the `and-or-filtering` feature flag. Filters are handled slightly different there.

**Comment by neilkakkar** [comment]
@Twixes we released and-or for everyone, you're not seeing it on your account? 🤔 .

**Comment by Twixes** [comment]
I had it off locally. @neilkakkar BTW it's not in `PERSISTED_FEATURE_FLAGS` so it's not released for self-hosted.
