### ISSUE TITLE
Add custom clickhouse port support

### ISSUE THREAD

**Issue by mojerro** [PostHog/posthog#9399]
## Describe the solution you'd like

Support custom clickhouse port.

1. add CLICKHOUSE_PORT and CLICKHOUSE_HTTP_PORT env vars in .env file.
2. change files that hard-coded the ports number, such as 9000, 8123, 8443, or omit the port number.

**Comment by gajus** [comment]
Related https://github.com/PostHog/charts-clickhouse/issues/414

**Comment by macobo** [comment]
Is this for self-hosted hobby deployments?

**Comment by mojerro** [comment]
> Is this for self-hosted hobby deployments?

@macobo yes, and then we can test it with outer clickhouse server more convenient

**Comment by macobo** [comment]
We're trying to keep self-hosted hobby deployments as simple as possible, meaning external clickhouse isn't a use-case we're supporting.

Our [helm chart](https://posthog.com/docs/self-host) is much more versatile and scalable in that regard and now supports configuring external clickhouse ports.

**Comment by mojerro** [comment]
I agree with you
