### ISSUE TITLE
Cohort not being updated automatically

### ISSUE THREAD

**Issue by aantn** [PostHog/posthog#9428]
## Bug description
Cohort number 7808 on the PostHog cloud instance is not being updated automatically. 

1. I open a list of recordings which is filtered by this cohort.
2. There are recordings missing from users who should be in the cohort
3. I open the cohort and see that it was last updated many hours ago
4. I save the cohort again and not it updates
5. I go back to the recordings page and new recordings appear.

The cohort is definitely not updating every 15 minutes like the website says it should. This is annoying because I want to see new users in the cohort relatively soon (e.g. within an hour of them appearing). Instead I am forced to manually refresh the dynamic cohort each time.

## Environment

- [ X] PostHog Cloud
- [ ] self-hosted PostHog (ClickHouse-based), version/commit: _please provide_
- [ ] self-hosted PostHog (Postgres-based, legacy), version/commit: _please provide_

**Comment by Twixes** [comment]
Hey! I believe this should be fixed now, but do let us know if there's still an issue.
