### ISSUE TITLE
Custom events not found when creating an action

### ISSUE THREAD

**Issue by prawnsalad** [PostHog/posthog#943]
**Describe the bug**
When creating a new action from a custom event, it gives me the message `You haven't sent any custom events`. I do have several trends built upon custom events so they do exist.

**To Reproduce**
1. 
2. 
3. 

**Expected behavior**
To be able to select an event from the events I have sent.

**Screenshots**
![image](https://user-images.githubusercontent.com/725880/83970123-de528980-a8cb-11ea-85a9-4e4ac0a6d526.png)

Events listed elsewhere:
![image](https://user-images.githubusercontent.com/725880/83970148-f924fe00-a8cb-11ea-8d5e-02c8e3e797f2.png)

**Hosted or self hosted?:**
Self-hosted, 1.8.0

**Additional context**

**Comment by timgl** [comment]
@prawnsalad That's fixed!
