### ISSUE TITLE
Chart/table preview when creating insights is not showing up

### ISSUE THREAD

**Issue by albtsantos** [PostHog/posthog#9436]
Hey folks 👋

When creating insights, I keep getting presented the “Your query took too long to complete” message, instead of the chart/table preview -- even after clicking the “refresh” button.

I noticed that if I _actually_ refresh the page (or open it in a new tab), sometimes everything works and I can see the data.

Here's the interesting part: when inspecting the network tab of the failing site, I don't see any requests made to `https://app.posthog.com/api/projects/:id/insights/trend` at all, even after changing the filters, breakdowns etc. 

## How to reproduce

1. Open PostHog in a new tab.
2. Go to Insights.
3. Click on “New insight”.
3. Notice that the chart/table preview doesn't show up.

## Environment

- [X] PostHog Cloud
- [ ] Self-hosted PostHog

## Additional context

This doesn't happen all the time, but when it does, I'm seeing the same error a bunch of times in the console: 

<img width="1218" alt="Screen Shot 2022-04-16 at 09 13 53" src="https://user-images.githubusercontent.com/1762338/163674518-c25144fc-4026-49fd-821b-9a57696722b3.png">

**Comment by Twixes** [comment]
Hey Alberto, does this reoccur if you hard-refresh the page (Ctrl/Cmd+Shift+R)?

**Comment by albtsantos** [comment]
@Twixes:

With a hard refresh, it works! I honestly don't understand what's going on -- sometimes it works, sometimes it doesn't (even in a new tab) -- and again, there's no network request _at all_. 

Can I help you folks debug this, somehow?
