### ISSUE TITLE
Is DAU working for funnels?

### ISSUE THREAD

**Issue by prawnsalad** [PostHog/posthog#944]
**Describe the bug**
I have 2 funnels, both identical other than one uses totals and the other DAU. Both funnels report the exact same numbers despite many people I know first-hand use the service several times a day, including myself.

**To Reproduce**
1. 
2. 
3. 

**Expected behavior**
I would expect that the DAU funnel to report lower numbers than the total count funnel.

**Screenshots**
![image](https://user-images.githubusercontent.com/725880/83970283-d7784680-a8cc-11ea-88db-3fd084c5dd79.png)

![image](https://user-images.githubusercontent.com/725880/83970341-2aea9480-a8cd-11ea-8bd1-e2d2af6b0cb6.png)

**Hosted or self hosted?:**
Self-hosted, 1.8.0

**Additional context**

**Comment by prawnsalad** [comment]
Just for a comparison, here is a trend for the `$apphit` event that the funnels are using, both total and DAU. This shows that there is a difference. All screenshots in this issue are using the 'today' timeframe.

However, it is **very** suspicious that both total and DAU have almost identical differences for every hour... (edit: I've compared with a secondary stats source, these differences are correct)

![image](https://user-images.githubusercontent.com/725880/83970502-eb707800-a8cd-11ea-9f88-02565db90f14.png)

**Comment by timgl** [comment]
@prawnsalad Thanks for raising this! We never built funnels to be anything but DAUs, so that button doesn't do anything. The only reason it's there is it's a shared component with the trends page, which does use it.

Agree this is worth fixing though!

**Comment by timgl** [comment]
In the mean time, I've hidden the button as even if we do allow you to select 'uniques/totals' in the future, it'd be over the entire funnel instead of per entity

**Comment by prawnsalad** [comment]
Ahh that explains it, just some UI confusion then! Thanks for explaining
