### ISSUE TITLE
bin/plugin-server doesn't propagate signals

### ISSUE THREAD

**Issue by joetrollo** [PostHog/posthog#9440]
## Bug description

Although `pluginServer.ts` has a mechanism to terminate gracefully, when run from `bin/plugin-server` it doesn't receive signals from the parent process.

## How to reproduce

1. `kubectl logs -f` any plugin server pod
2. `kubectl delete pod` that same pod
3. Notice that the plugin server terminates abruptly after ~30 seconds without ever indicating a graceful shutdown (i.e. "Shutting down gracefully..." doesn't appear in the log output)

## Environment

- [ ] PostHog Cloud
- [X] self-hosted PostHog (ClickHouse-based), version/commit: [3a78572](https://github.com/PostHog/posthog/pull/9348/commits/3a78572254f91f19bc3601e57dd26baebff3d0b8) (head of #9348)
- [ ] self-hosted PostHog (Postgres-based, legacy), version/commit: _please provide_

## Additional context

If I `kubectl exec` into a plugin server container to inspect the processes, I see

```bash-5.1$ ps
PID   USER     TIME  COMMAND
    1 posthog   0:00 /bin/sh -c ./bin/plugin-server --no-restart-loop
    8 posthog   0:00 {plugin-server} /bin/bash ./bin/plugin-server --no-restart-loop
   18 posthog   0:00 node /usr/local/bin/yarn start:dist
   29 posthog   1:36 /usr/bin/node dist/index.js
```

If I `kill -s SIGTERM` either 1 or 8, the plugin server does not shutdown gracefully. Only by killing 18 will the server shutdown gracefully and show "Shutting down gracefully..." in the log output.

**Comment by Twixes** [comment]
The core issue seems to be that we're using this intermediary script in `plugins-deployment.yaml` when we could be running `node dist/index.js` directly. Can we just bypass the script? @tiina303

**Comment by tiina303** [comment]
I do think we want to keep using `bin/plugin-server` script, in that script we could pass the signal down (e.g. https://unix.stackexchange.com/questions/146756/forward-sigterm-to-child-in-bash). 
For the command in [`plugins-deployment.yaml`](https://github.com/PostHog/charts-clickhouse/blob/main/charts/posthog/templates/plugins-deployment.yaml#L62-L66) we can probably change that to be the script directly instead of via `bin/sh`, but I'm not sure if there's any value of doing it the way we have now. Infra folks, e.g. @guidoiaquinti  might know better all of this.

**Comment by joetrollo** [comment]
I looked into this some more and was able to adjust `bin/plugin-server` to trap and propagate the signal. However, no matter what I did, I still couldn't get a graceful shutdown in Kubernetes until I changed the container command from `/bin/sh -c ./bin/plugin-server --no-restart-loop` to just `./bin/plugin-server --no-restart-loop`. I don't fully understand why this is, because I'm able to get signals to propagate through `/bin/sh -c` when running short test scripts.

I could make a PR with my changes to `bin/plugin-server` as well as a PR to the Helm charts to remove the `/bin/sh -c`, but I'm not sure what direction you all want to take this and I don't know the original reasons for using `/bin/sh -c`. I'll wait for some input before proceeding with any particular solution.

**Comment by Twixes** [comment]
I'm fairly sure just `./bin/plugin-server --no-restart-loop` but would be perfect, but I'll let @tiina303 confirm/debunk.

**Comment by tiina303** [comment]
A PR would be lovely & just `./bin/plugin-server --no-restart-loop` is good 👍  Thank you.

For why the `/bin/sh -c ...` didn't propagate, I suspect we're missing `set -e`, you can see a problem described in the description here: https://github.com/PostHog/charts-clickhouse/pull/321

**Comment by joetrollo** [comment]
PRs are ready for review at https://github.com/PostHog/charts-clickhouse/pull/366 and https://github.com/PostHog/posthog/pull/9641. Thanks!

**Comment by joetrollo** [comment]
Closed by https://github.com/PostHog/charts-clickhouse/pull/366 and https://github.com/PostHog/posthog/pull/9641
