### ISSUE TITLE
Save "Customize columns" settings

### ISSUE THREAD

**Issue by fluidsonic** [PostHog/posthog#9444]
## Is your feature request related to a problem?

Every time I look at live events or person events I have to re-configure the columns I need.

## Describe the solution you'd like

The settings in "Customize columns" should be persisted.

## Describe alternatives you've considered

-

**Comment by macobo** [comment]
@tiina303 / @mariusandra  did https://github.com/PostHog/posthog/pull/10547 solve this? If so, please close this ticket :pray:
