### ISSUE TITLE
Materialize tables

### ISSUE THREAD

**Issue by EDsCODE** [PostHog/posthog#945]
**Is your feature request related to a problem? Please describe.**
improve speed on long runnig queries

**Describe the solution you'd like**
use materialized tables for queries that rarely change

**Describe alternatives you've considered**
actually cache results with redis/memcache

**Additional context**

***Thank*** you for your feature request - we love each and every one!

**Comment by paolodamico** [comment]
I believe we can close this with CH @EDsCODE ?
