### ISSUE TITLE
Onboarding design - project easy

### ISSUE THREAD

**Issue by lottiecoxon** [PostHog/posthog#9452]
## AIM-  Make onboarding super easy to ingest. How? Design. 
Figma file is [here](https://www.figma.com/file/HwUmk7WqccLkGgNNGAs4zN/Art-board?node-id=3524%3A21693).
### 1. Side Menu 
- allows the user to identify how many steps there are 
- see what other steps they will need to fill out
- have continuous access to the 'visit support' section in the bottom left corner. 
- introduction of blue menu indicator 

### 2. Visual 
- friendly hedgehog visual 
- also allows for a small indicator of time that onboarding will take 

![Welcome - side menu onboarding](https://user-images.githubusercontent.com/65415371/163996632-3905fa8e-3477-4598-9711-8db65799fe6c.jpg)

### 3. Simplified connect options
- boxing up both options allows the user not to get overwhelmed with long pages of info
- small descriptions of both (indicating which one is recommended)  
- easy drop down options 

![Connect- side menu-1](https://user-images.githubusercontent.com/65415371/164002518-1f338e15-a205-45ad-9bdb-6ab1dfd1a110.jpg)

![Connect- side menu-7](https://user-images.githubusercontent.com/65415371/164003316-e799dc0f-53d1-40ff-841c-6f2d7c4e1a3c.jpg)

(ignore the seemingly short menu - it's a Figma thing)

### 4. Light plugins overlay
- (below) A fresh and light background blur paired with a simple overlay for the configuration. 
- I have a cool idea for the menu transition - blue indicator will wash right over 'Plugins' and allow 'configuration' to appear next to it. When deselected it will wash left, turning 'Plugins' back to black while 'configuration' disappears.

![Plugins- side menu](https://user-images.githubusercontent.com/65415371/164003653-4134467f-0d77-4a2e-a14c-92003374e32a.jpg)

![Configuration- side menu](https://user-images.githubusercontent.com/65415371/164004793-1139a785-d61d-4402-aeb6-28dbdb811ffe.jpg)

![What's next_ - side menu](https://user-images.githubusercontent.com/65415371/164005355-4b4b0086-8259-49d2-b490-f5ebff797643.jpg)

**Comment by lottiecoxon** [comment]
### Updates (sparked mainly from suggestions from Li) : 
- Moved 'invite a team member' to the left menu so it's there all the time 
- Removed the payment 'nudge' on the success page (not needed yet)
- added in a tutorials link for those still unsure about where to go from here  

![What's next_ - side menu](https://user-images.githubusercontent.com/65415371/164031903-62b8d807-077c-4428-8419-919ea3241b1c.jpg)

**Comment by clarkus** [comment]
I responded to feedback in figma for now. Not sure if we need a gitub issue for this or if we should use the core issues from eng work.

**Comment by lottiecoxon** [comment]
Good point - will close this and use Figma for feedback sessions
