### ISSUE TITLE
Adjust times to local timezone

### ISSUE THREAD

**Issue by prawnsalad** [PostHog/posthog#946]
**Is your feature request related to a problem? Please describe.**
My local timezone is not currently UTC so the graphs I see are always out of sync to my local time

**Describe the solution you'd like**
Adjust displayed timezones to use my browser timezone so it makes clearer sense

**Describe alternatives you've considered**

**Additional context**

***Thank*** you for your feature request - we love each and every one!

**Comment by timgl** [comment]
Duplicate of #747
