### ISSUE TITLE
Project settings snippet not working

### ISSUE THREAD

**Issue by yakkomajuri** [PostHog/posthog#9460]
## Bug description

I just tried to use the project settings snippet and that gave me the error:

```
VM28:1 Uncaught TypeError: Cannot read properties of undefined (reading 'parentNode')
    at Array.e.__SV.e.init (<anonymous>:1:467)
    at <anonymous>:2:13
```

Bookmarklet ofc fails too. 

## How to reproduce

1. Copy the snippet
2. Try to use it
3. Fails

## Environment

- [ ] PostHog Cloud
- [ ] self-hosted PostHog (ClickHouse-based), version/commit: _please provide_
- [ ] self-hosted PostHog (Postgres-based, legacy), version/commit: _please provide_

**Comment by timgl** [comment]
I think this happens if there are no other script tags on the page.
