### ISSUE TITLE
Enable discarding of IP address data

### ISSUE THREAD

**Issue by shafy** [PostHog/posthog#947]
**Is your feature request related to a problem? Please describe.**
When submitting events through the API, IP addresses of clients are automatically stored. I'm guessing this is also the case for other integrations and libraries you provide.

**Describe the solution you'd like**
I'd like a setting to disable storing of IP addresses. When this setting is enabled, IP addresses are still sent to the server and are used to determine the geolocation (e.g., city and country). Then they are discarded and never stored. This makes using PostHog more privacy-friendly and easier to comply with GDPR. A lot of people don't really need the IP address, just the approximate geolocation.

**Comment by timgl** [comment]
Thanks for raising this! I think it's super relevant. The way I'd solve this is

- Add a `anonymize_ips` boolean field on the Team
- In `process_event.py`, don't store the ip if that field is set to true.
- Allow users to set the field in the /setup page, and change it in the `api/user.py` endpoint

**Comment by glmaljkovich** [comment]
Hey guys, if no one's working on it already, I'm eager to implement the solution.

**Comment by timgl** [comment]
@glmaljkovich Go for it! Let me know if you have any questions or want to do some pairing :)

**Comment by timgl** [comment]
@shafy This is merged! We don't have support for GeoIP yet as there are no free open source databases for it, but it's something we're trying to find a way of delivering.

Let us know if this works.

@glmaljkovich Looks like Karl beat you to it but if there's anything else you'd like to work on please go ahead and let me know if there's anything I can do to help :)

**Comment by shafy** [comment]
Awesome, works! Thanks!
