### ISSUE TITLE
Invalidate license key after one year if status ping cannot get out

### ISSUE THREAD

**Issue by camerondeleone** [PostHog/posthog#9473]
## Is your feature request related to a problem?

We have no way to charge for usage if our status report cannot get out. Thus, it's possible to use PostHog for free. 

## Describe the solution you'd like

Ideal:

- We generate different types of license keys with different invalidation parameters, depending on the payment plan of a user (annual fixed, monthly metered) 
- Then, invalidate the license key ad the end of the month if the service ping doesn't get out and it's a metered plan, or at the end of the year if it's a yearly/fixed plan

MVP: 

- handle the first case above, ie invalidate all licenses on self-hosted instances after one year if status ping can't get out

## Describe alternatives you've considered

having users send screenshots of usage

## Additional context

https://posthog.slack.com/archives/C02E3BKC78F/p1650456805069109

**Comment by jamesefhawkins** [comment]
> at the end of the year if it's a yearly/fixed plan

Not sure about this as we're likely to have some usage limit, so they could end up way way over then never paying. Suggest we do the same as your suggestion for monhtly clients.

I think we could enable them to send you a screenshot that you manually enter as a workaround to air gapped deployments too. Maybe that's an enterprise feature (ie it's annoying to do this for $3/month but not annoying for a higher minimum fee)

**Comment by camerondeleone** [comment]
> > at the end of the year if it's a yearly/fixed plan
> 
> Not sure about this as we're likely to have some usage limit, so they could end up way way over then never paying. Suggest we do the same as your suggestion for monhtly clients.
> 
> I think we could enable them to send you a screenshot that you manually enter as a workaround to air gapped deployments too. Maybe that's an enterprise feature (ie it's annoying to do this for $3/month but not annoying for a higher minimum fee)

I think greenlighting airgapped environments on enterprise only makes the most sense, and then we can manage as needed.  It does make sense that we could push it back onto customers to do the work of sending us this.

**Comment by Twixes** [comment]
Unlikely to be an issue now that we don't support K8s deployment, as far as I can tell!
