### ISSUE TITLE
Update onboarding hog

### ISSUE THREAD

**Issue by joethreepwood** [PostHog/posthog#9481]
## Bug description

Well, I spent the last 45 minutes following [these instructions](https://posthog.com/handbook/engineering/developing-locally) to try and do this myself, but without success. So, I'm hoping I can just put this in as bug report. 

<img width="903" alt="Screenshot 2022-04-21 at 13 11 14" src="https://user-images.githubusercontent.com/84011561/164455496-c04b9e15-bc57-4696-8a22-d44919c8ba4c.png">

There's an off-brand hog at `/signup`

## How to reproduce

1. Go to https://app.posthog.com/signup
2.
3.

## Environment

- [ ] PostHog Cloud
- [ ] self-hosted PostHog (ClickHouse-based), version/commit: _please provide_
- [ ] self-hosted PostHog (Postgres-based, legacy), version/commit: _please provide_

## Additional context

Tagging @clarkus and @lottiecoxon

**Comment by clarkus** [comment]
We're reworking onboarding now and that's very related to sign up. @lottiecoxon can we include swapping out the hogs as part of our onboarding effort?

**Comment by lottiecoxon** [comment]
yes we can - actually debating having a hedgehog on the page at all - with new menus and such may get too crowded?

**Comment by joethreepwood** [comment]
<img width="749" alt="Screenshot 2022-08-17 at 13 09 06" src="https://user-images.githubusercontent.com/84011561/185114897-e8dceba3-bb8f-4475-af0a-fab2e57ebc23.png">

We can close this, as it got solved at some point. Thanks, disappearing hedgehog!
