### ISSUE TITLE
Last event ingested in /instance/status is UTC but looks like localtime

### ISSUE THREAD

**Issue by tiina303** [PostHog/posthog#9505]
## Bug description

Last event ingested in /instance/status in system overview tab is UTC but looks like local time
Could be confusing to user to see UTC time there with no indication it's UTC.

Would be great if it showed up similar to time in live events https://app.posthog.com/events

## How to reproduce

1. Go to https://app.posthog.com/instance/status system overview tab (being in non UTC timezone) & check the "Last event ingested"

## Environment

- [x] PostHog Cloud
- [x] self-hosted PostHog (ClickHouse-based), version/commit: _please provide_
- [ ] self-hosted PostHog (Postgres-based, legacy), version/commit: _please provide_

**Comment by Aashish-Upadhyay-101** [comment]
Hello, @tiina303 I want to work on this issue, 
I haven't contributed to posthog before, so it will be awesome if you give me a little assistance.

**Comment by tiina303** [comment]
hi @Aashish-Upadhyay-101  you can check out our developing locally guide https://posthog.com/handbook/engineering/developing-locally let me know if you have any questions
