### ISSUE TITLE
The format of overview on dockerhub is kinda mess

### ISSUE THREAD

**Issue by happy15** [PostHog/posthog#9507]
as of 2022-04-23: https://hub.docker.com/r/posthog/posthog

![image](https://user-images.githubusercontent.com/983570/164885007-6112bb92-c19e-4f47-9ac2-188fe20b7475.png)

**Comment by pauldambra** [comment]
<img width="900" alt="Screenshot 2024-05-07 at 08 34 37" src="https://github.com/PostHog/posthog/assets/984817/5043299c-bc91-4165-9b44-8500421400b2">

was accidentally or purposefully fixed at some point in the past 😊
