### ISSUE TITLE
Feature Request: Ability to link to feature

### ISSUE THREAD

**Issue by joethreepwood** [PostHog/posthog#9509]
## Is your feature request related to a problem?

There's some context on this .com PR: https://github.com/PostHog/posthog.com/pull/3350

But the short version is that it would be a useful improvement to the docs, content, site CTAs, etc. if we could link users to specific features or areas of the product. Currently, from discussion in Iceland with @pauldambra I believe we can  do this for Cloud users, but because self-hosted users have more unpredictable domain names. 

This would be helpful for CTAs in the docs, links in product announcements and Array posts, as well as for use by Support Hero. 

## Describe the solution you'd like

`"Interested in Funnels? [Give it a go!](link to funnels in app]"`
`"Want to try this plugin? [Install it now.](link to specific plugin)"`

Existing, logged in users would click the linsk above and be taken to the relevant feature on their instance (and probably their most recent project, if multiple). Users who do not have an account or who are not logged in would be directed to /signup to start creating an account. 

## Describe alternatives you've considered

As per the PR above, we've discussed other ways of working useful CTAs into Docs, but concluded this may be the best.

#### *Thank you* for your feature request – we love each and every one!

No, thank _you_, team!

**Comment by pauldambra** [comment]
In the discussion in Iceland I suggested you could let someone set what their PostHog URL was through to (an admittedly very complex implementation of) doing the oAuth dance to log into posthog.com with their PostHog account so we can detect the URL to use

**Comment by joethreepwood** [comment]
> In the discussion in Iceland I suggested you could let someone set what their PostHog URL was through to (an admittedly very complex implementation of) doing the oAuth dance to log into posthog.com with their PostHog account so we can detect the URL to use

You did, but IIRC we ended on that not being a great solution because it wouldn't work well if someone wasn't logged? Though I may have misunderstood (and wouldn't know how to ship that myself anyway).

**Comment by pauldambra** [comment]
Yep, I think it's a tricky thing however you cut it...

But letting someone  set a desired PostHog URL and rendering links differently if they have is **relatively** straight-forward.

TBH The tricky bit would be detecting drift if PostHog URLs changed... e.g. when we changed insight URLs to use short ids instead of long filter params
