### ISSUE TITLE
Cohorts should be a filter on the trends page

### ISSUE THREAD

**Issue by jamesefhawkins** [PostHog/posthog#952]
**Is your feature request related to a problem? Please describe.**

If a cohort is applied to filter the /trends page, it gets added as a breakdown.

Since you then can't add another breakdown, you can't see any further breakdown in the information.

![Screenshot 2020-06-08 at 14 15 28](https://user-images.githubusercontent.com/47497682/84034656-892d7b00-a992-11ea-8ed3-38ca45e30511.png)

My specific use case was that I wanted on app.posthog.com to work out if more of our users were using hosted or self-hosted, and can't do that whilst applying the "Real users" breakdown.

**Describe the solution you'd like**

Either to be able to add multiple breakdowns OR to be able to add a cohort as a filter.

**Describe alternatives you've considered**

I need to replicate the cohort filters as filters against the user in the /trends page, making cohorts redundant in this case.

**Comment by timgl** [comment]
Donezo
