### ISSUE TITLE
Updated placement of register and sign in links for authentication

### ISSUE THREAD

**Issue by clarkus** [PostHog/posthog#9520]
## Is your feature request related to a problem?

We updated the authentication screens a bit ago, but the placement of registration and authentication links shipped with some inconsistencies. Sometimes links are shown in the form header, sometimes as tertiary actions adjacent to primary buttons. This is possibly intentional, but the SAML/SSO workflow for authentication lacks a link back to registration entirely. 

## Describe the solution you'd like

Consistent placement and verbiage for these links. These links will move into a consistent position adjacent to the primary actions for the form. To achieve this, the password recovery action and password strength indicator will move into a consistent position opposite the password input label. 

I updated the [authentication and registration flows in figma](https://www.figma.com/file/gQBj9YnNgD8YW4nBwCVLZf/?node-id=3558%3A32653) to illustrate this change.

![Login](https://user-images.githubusercontent.com/254612/165120591-4c09e2ea-52d3-4322-8b8c-807cf630588e.png)
![Register (default)](https://user-images.githubusercontent.com/254612/165120596-854f57d8-9f8b-4785-b7ce-55e169f7bc73.png)

**Comment by joethreepwood** [comment]
Thanks Chris!

**Comment by andresmc98** [comment]
Hi, is someone working on this issue?
i'd like to take it

**Comment by mariusandra** [comment]
@andresmc98 to for it!

**Comment by jaysoni-ash42** [comment]
@clarkus  i am new to this repo. One question about this issue do i have to change to all the form of authentication for just the login form according to the design

**Comment by clarkus** [comment]
> @clarkus i am new to this repo. One question about this issue do i have to change to all the form of authentication for just the login form according to the design

This affects the registration and sign in screens. The changes are multi-part, so be sure to reference the figma designs if you're going to work on this. The core changes are the placement of secondary actions that facilitate moving between registration and sign in screens. This affects any screen where the primary action is sign up or sign in. Secondary to this, the forgot password link has moved to be opposite the password label on sign in screens.

**Comment by LuisChiej** [comment]
Hello @clarkus, Need some clarification, Attached below is a loom video
[https://www.loom.com/share/a61c46f4b35b4835bae2150d7632cfda](https://www.loom.com/share/a61c46f4b35b4835bae2150d7632cfda)

**Comment by LuisChiej** [comment]
Hello @clarkus, Please we are presently working on this and we will need clarification ASAP

Thank you

**Comment by clarkus** [comment]
@LuisChiej this issue is just for the placement of the actions that allow a user to navigate between signing in and signing up. Specifically the placement of the content "Already have an account? Sign in" and "Don't have an account? Create one". In each case, the content should follow the primary action. 

**Signing up** - affected area is just after the "create account" button
![Cloud register](https://user-images.githubusercontent.com/254612/185260846-58de5196-51e6-42e9-8028-e5242da43cdf.png)

**Signing in** - affected area is just after the "continue" button
![Cloud login](https://user-images.githubusercontent.com/254612/185260830-31984b21-1d71-4a9f-a3a3-00e64040d797.png)

**Comment by raquelmsmith** [comment]
Hi @clarkus  - I just opened #12227 for this 👍
