### ISSUE TITLE
Tech debt, low hanging fruit - 6 monthly review

### ISSUE THREAD

**Issue by timgl** [PostHog/posthog#9531]
One action from the BCN offsite was to document tech debt with low hanging fruit to solve. Here's my (purposfully short) list:

- Finish moving all clickhouse related code from `ee` to `posthog`
- Generate a single spec for server side libraries (or at least pull in latest changes from analytics)
- Strongly type the [filters object](https://github.com/PostHog/posthog/blob/master/frontend/src/types.ts#L932) across frontend and backend based on insight. Right now it's a kitchen sink
  - ​​Related: autogenerate types from backend

If there's anything you think that's higher priority/easier to do let me know. I want to schedule at least the first one in the next sprint.

**Comment by pauldambra** [comment]
I'm going to signal boost #7385 which i'd forgotten about. But made working on funnels more complex than it needed to be
