### ISSUE TITLE
Data management events are hard to use

### ISSUE THREAD

**Issue by timgl** [PostHog/posthog#9534]
## Bug description

- To edit an event description you have to hover over a name which is unclear and frustrating
- You can't copy the event name because of this hover
- I want to see some example values for each property on an event
- I want to see some live events to debug what's going on. A direct link to Live Events filtered on the event would be great

See loom:
https://www.loom.com/share/8256d10fd66e4bce9a8fbb44293b01a1

## How to reproduce

1.
2.
3.

## Environment

- [ ] PostHog Cloud
- [ ] self-hosted PostHog (ClickHouse-based), version/commit: _please provide_
- [ ] self-hosted PostHog (Postgres-based, legacy), version/commit: _please provide_

**Comment by alexkim205** [comment]
All points here have been addressed with this PR https://github.com/PostHog/posthog/pull/10025
