### ISSUE TITLE
Funnels and correlation analysis breaks when adding exclusion steps

### ISSUE THREAD

**Issue by liyiy** [PostHog/posthog#9537]
## Bug description

*Please describe.*  
*If this affects the front-end, screenshots would be of great help.*  

## How to reproduce

1. Go to any funnel
2. Add exclusion step
3. Funnel and correlation analysis breaks

## Environment

- [ ] PostHog Cloud
- [ ] self-hosted PostHog (ClickHouse-based), version/commit: _please provide_
- [ ] self-hosted PostHog (Postgres-based, legacy), version/commit: _please provide_

**Comment by neilkakkar** [comment]
Looks like the selector isn't working on the UI? It sends a `[{}]` for exclusions, which breaks both query and correlation result

**Comment by pauldambra** [comment]
fixed by #9762
