### ISSUE TITLE
Consolidate Elements logic

### ISSUE THREAD

**Issue by EDsCODE** [PostHog/posthog#954]
**Is your feature request related to a problem? Please describe.**
Elements logic exists in a few places (new element endpoint and paths logic(

**Describe the solution you'd like**
DRY the logic

**Describe alternatives you've considered**

**Additional context**

***Thank*** you for your feature request - we love each and every one!

**Comment by Twixes** [comment]
I think this has undergone some refactors, so I'm going to go ahead and close.
