### ISSUE TITLE
Feature request: Sticky first column in breakdown views

### ISSUE THREAD

**Issue by joethreepwood** [PostHog/posthog#9567]
## Is your feature request related to a problem?

So, I was working on the insight I mentioned in [this related feature request](https://github.com/PostHog/posthog/issues/9566) and I finally got to the part of the breakdown table that I wanted to see -- midnight, 27th April. 

<img width="1407" alt="Screenshot 2022-04-28 at 10 03 47" src="https://user-images.githubusercontent.com/84011561/165717783-dbce2df5-dba4-476c-b319-18ca276bc8e6.png">

So, now I'm thinking: "Yep, we definitely had some big spikes on particular URLs!"

But I looked at the breakdown table to try and see _which_ URLs we had spikes on and, because I've had to scroll horizontally along to the middle of the table, I now can't see the first column of the table (which is where the breakdown values, in this case URLs, are listed. 

As a result, after dealing with the fact that the horizontal scroll bar is at the bottom of a table which is larger than the viewport, I now need to remember which rows I want to look at and scroll all the way back to the first column to see what those rows represent. 

Again, on a 4K screen that's probably bigger than that used by most users. 

## Describe the solution you'd like

It would be good if the first column was sticky, so that it stayed in frame as I scrolled horizontally along the table. 

## Describe alternatives you've considered

Exporting the table. But that's laaaaame. 

## Additional context

UI issue, tagging @clarkus and @lottiecoxon

**Comment by clarkus** [comment]
Related solution at https://github.com/PostHog/posthog/issues/10194

**Comment by mariusandra** [comment]
This was implemented thanks to a community contributor: https://github.com/PostHog/posthog/pull/16825

Now we're [getting requests](https://posthoghelp.zendesk.com/agent/tickets/6636) to also make the second column sticky.
