### ISSUE TITLE
View experiments on dashboards

### ISSUE THREAD

**Issue by camerondeleone** [PostHog/posthog#9572]
## Is your feature request related to a problem?

If you're running a number of experiments, it would be nice to be able to view them on a single dashboard, rather than having to load them individually. 

## Describe the solution you'd like

Experiment results (including metadata around significance, not just the trend/funnel) can live on dashboards next to existing insights or other experiments

## Describe alternatives you've considered

View experiments progress/results one at a time at `/experiments`

## Additional context

This feature was asked for by a [potential customer](https://app.hubspot.com/contacts/6958578/company/8438377779)

**Comment by clarkus** [comment]
Project home page has [a concept](https://www.figma.com/file/gQBj9YnNgD8YW4nBwCVLZf/PostHog-App?node-id=8573%3A50924) for a list of recently viewed experiments. It's based on what you've viewed recently, but could also be based on the set of actively running experiments. It's still in idea phase, but feels like it could partially address this problem.
