### ISSUE TITLE
Allow selecting multiple dates when adding a Time filter in events

### ISSUE THREAD

**Issue by djindal03** [PostHog/posthog#9587]
## Is your feature request related to a problem?

*Please describe.*
There can be cases where we just want see the data for the weekends or see the data for a particular date range(I know this can be done by adding two filters of "before" and "after" but still it would be simpler to do it from the calendar).
## Describe the solution you'd like
Build the functionality to select multiple dates from the calendar irrespective of whether the selected dates are continuous or random.

**Comment by pauldambra** [comment]
pinging @clarkus who I think has been thinking about this

**Comment by clarkus** [comment]
Related https://github.com/PostHog/posthog/issues/9027

**Comment by clarkus** [comment]
Related https://github.com/PostHog/posthog/issues/9453

**Comment by clarkus** [comment]
Related https://github.com/PostHog/posthog/issues/2779

**Comment by clarkus** [comment]
I put together a [concept workflow in figma](https://www.figma.com/file/gQBj9YnNgD8YW4nBwCVLZf?node-id=9825:49629#187839291) with an idea for how we might address this. Each step is annotated with comments that describe the process. 

<img width="1146" alt="Screen Shot 2022-04-29 at 3 54 50 PM" src="https://user-images.githubusercontent.com/254612/166078323-44167ff8-c256-403b-ba62-e0fd0891d75c.png">

**Comment by djindal03** [comment]
@clarkus correct me if I'm wrong, but according to this workflow we can only select a range of date, right? Can we also not have an option of selecting random dates? For example if I just want to select the weekends in the calendar.

**Comment by clarkus** [comment]
> @clarkus correct me if I'm wrong, but according to this workflow we can only select a range of date, right? Can we also not have an option of selecting random dates? For example if I just want to select the weekends in the calendar.

A single date would be a valid custom date range. Ranges must be contiguous for this to work, so you couldn't select arbitrary, non-contiguous values.
