### ISSUE TITLE
Toolbar is not showing for a URL, working for other URLs

### ISSUE THREAD

**Issue by shriniket73** [PostHog/posthog#9589]
## Bug description

Toolbar is not working for a Retool URL. Toolbar is enabled in the project and it's working for other URLs added.
This is the console error
![image](https://user-images.githubusercontent.com/54532343/165957797-a587dde4-b49a-4691-9558-9f9b4f6d9f79.png)

## Environment

- Self hosted Posthog

**Comment by pauldambra** [comment]
I hope you've not been patiently waiting 2 years for a response - sorry this never received one!
