### ISSUE TITLE
ClickHouse failes to use Materialized View to fill destination table from Kafka table

### ISSUE THREAD

**Issue by fuziontech** [PostHog/posthog#9597]
From slack https://posthog.slack.com/archives/C01MM7VT7MG/p1651238702185679

So after 1h30 debugging me and Harry stumbled upon some more CH craziness.
Essentially the names we use for our Kafka + MV tables (both or one or the other) are now “reserved” in the sense that creating tables with those names will work but ingestion won’t. Absolute 🤯 

So currently on prod we’re running kafka_events_json_reykjavik_roasters and events_json_mv_reykjavik_roasters . The names are based on the cafe I’m working from and this was essentially a joke - me and Harry had exhausted all our hypotheses so we decided to try creating the same tables but with a different name. To our surprise, that’s the only thing that worked.

Given the hardcoded names we have in our codebase simply don’t work, the follow up steps are:
Enlist Altinity’s help
Update the codebase to allow us to set the names of those tables while the problem isn’t solved.

Deets:
We ran things both ON CLUSTER and on specific nodes (effects are impacting entire cluster)
Essentially the `kafka_events_json` + `events_json_mv`  tables just didn’t consume

Investigate steps:
```sql
show create table kafka_events_json_reykjavik_roasters

show create table events_json_mv_reykjavik_roasters

-- use the results from above to create tables with the same exact schema just using the names kafka_events_json and events_json_mv

create table kafka_events_json ...

create table events_json_mv ...

-- at this point ingestion will still be working because of the other tables, so:

detach table events_json_mv_reykjavik_roasters on cluster 'posthog'

-- now the only ingestion path is events_json_mv, check if events are coming in
```
This error is distracting - it can definitely connect to kafka and read.
```
2022.04.29 19:26:57.833400 [ 1618400 ] {} <Error> StorageKafka (kafka_events_json): [rdk:FAIL] [thrd:ssl://
			ec2-REDACTED.com:9096/bootst]: ssl://
			ec2-REDACTED.com:9096/bootstrap: Failed to resolve '
			ec2-REDACTED.com:9096': Name or service not known (after 0ms in state CONNECT)
2022.04.29 19:27:31.403667 [ 1617272 ] {3600a910-c978-4ec1-9b24-966c17c4abc8} <Error> StorageKafka (kafka_events_json): [rdk:ERROR] [thrd:app]: ClickHouse-ip-172-31-79-5.ec2.internal-posthog-kafka_events_json#consumer-22: ssl://
			ec2-REDACTED.com:9096/bootstrap: Failed to resolve '
			ec2-REDACTED.com:9096': Name or service not known (after 0ms in state CONNECT)
```

This error is also a distraction.
```
2022.04.29 19:35:44.909980 [ 756082 ] {} <Warning> ConnectionPoolWithFailover: Connection failed at try №1, reason: Code: 32, e.displayText() = DB::Exception: Attempt to read after eof (version 21.6.5.37 (official build))
2022.04.29 19:35:45.014881 [ 1533292 ] {9fd994ab-9865-42c2-8b0d-b718bc42d112} <Warning> ConnectionPoolWithFailover: Connection failed at try №1, reason: Code: 32, e.displayText() = DB::Exception: Attempt to read after eof (version 21.6.5.37 (official build))
2022.04.29 19:35:45.015202 [ 1533292 ] {9fd994ab-9865-42c2-8b0d-b718bc42d112} <Warning> ConnectionPoolWithFailover: Connection failed at try №1, reason: Code: 32, e.displayText() = DB::Exception: Attempt to read after eof (version 21.6.5.37 (official build))
2022.04.29 19:35:53.622884 [ 1314292 ] {56d436f7-faa4-44d4-a037-44f88b498fb7} <Warning> ConnectionPoolWithFailover: Connection failed at try №1, reason: Code: 32, e.displayText() = DB::Exception: Attempt to read after eof (version 21.6.5.37 (official build)
```

This was silently failing. Absolutely no logs were getting published about the failure to consume from kafka or insert into the destination table..

In order to get this to run again after doing a ton of debugging:
- Removed `events_json_mv` and all other similar tables off the cluster
- Removed `kafka_events_json` and all similar tables off the cluster
- Chose two instances on different shards with no replication queue and restarted them (patiently and carefully)
- Attempted to attach kafka table and drop if it existed
- Attempted to attach mv table and drop if existed
- You have to do these because there were instances where the table showed back up (orphan detach?)
- Created `kafka_events_json` just as it was defined prior
- Created `events_json_mv` just as it was defined prior
- Check events are getting consumed ✅

**Comment by yakkomajuri** [comment]
Thank you so much for debugging and documenting!

cc @hazzadous

**Comment by yakkomajuri** [comment]
Follow-up: what does restarting "patiently and carefully" mean?

```
sudo systemctl restart clickhouse-server --patiently --carefully
```
:D

**Comment by yakkomajuri** [comment]
Resolved, closing.

Would love a comment on the above though @fuziontech
