### ISSUE TITLE
Drill Deeper and more specifically with selector when creating action from event feed

### ISSUE THREAD

**Issue by EDsCODE** [PostHog/posthog#963]
**Is your feature request related to a problem? Please describe.**
Right now if there's no href, id, or text, the create action from event button will default to tag names which can lead to very generic actions

**Describe the solution you'd like**
use class names also or as we discussed use a ordered child selector `:nth child`

**Describe alternatives you've considered**
leave as is

**Additional context**

***Thank*** you for your feature request - we love each and every one!

**Comment by paolodamico** [comment]
We now prioritize custom data attributes.
