### ISSUE TITLE
Some clickhouse-postgres drift with persons

### ISSUE THREAD

**Issue by timgl** [PostHog/posthog#9640]
## Bug description

Following persons have email properties in postgres but not in clickhouse.

```
017ffb8f-3f95-0000-00b7-8135b4ac22bc
01807f1e-28d7-0000-9b0b-7fe3487e32a3
01801d5a-69b5-0000-01d8-837cc1fd66f5
01804df0-9c0b-0000-010a-5237b6ac197e
```

which are all persons in cohort `7757`

## How to reproduce

1.
2.
3.

## Environment

- [ ] PostHog Cloud
- [ ] self-hosted PostHog (ClickHouse-based), version/commit: _please provide_
- [ ] self-hosted PostHog (Postgres-based, legacy), version/commit: _please provide_

**Comment by tiina303** [comment]
Addressed within https://github.com/orgs/PostHog/projects/50/
