### ISSUE TITLE
Funnels won't load on app

### ISSUE THREAD

**Issue by jamesefhawkins** [PostHog/posthog#965]
**Describe the bug**
PostHog's own funnels don't finish loading

**To Reproduce**
1. Visit https://app.posthog.com/funnel/100 or https://app.posthog.com/funnel/36 or https://app.posthog.com/funnel/158

**Expected behavior**
Funnel should load.

**Screenshots**
<img width="370" alt="Screenshot 2020-06-09 at 14 30 27" src="https://user-images.githubusercontent.com/47497682/84153634-08d44c00-aa5e-11ea-9fda-c562ae1169d0.png">
<img width="1375" alt="Screenshot 2020-06-09 at 14 31 08" src="https://user-images.githubusercontent.com/47497682/84153641-0a057900-aa5e-11ea-8be2-91661f3b51a5.png">

**Hosted or self hosted?:**
- app.posthog.com

**Comment by fuziontech** [comment]
Was this resolved? These look super snappy to me now 2-3 seconds

**Comment by timgl** [comment]
Definitely related to all the other issues we were having on app, so closing this now
