### ISSUE TITLE
[EPIC] Make the ingestion pipeline spark more joy

### ISSUE THREAD

**Issue by yakkomajuri** [PostHog/posthog#9652]
## Description

Our ingestion pipeline is very impressive. It reliably ingests hundreds of millions of events per day, with a sophisticated plugin runner sitting in between allowing for all sorts of cool stuff - like my website's newsletter.

However, it needs a bit more love. We've been building out features but reliability and maintainability are suffering. The pipeline requires some reasonably active babysitting (from myself and others), to nudge things back into the right track, and that's far from optimal.

Thus, here's an initial rough plan of things to work on over the next 2 or so sprints. More context will be added here as it comes along. This will also become a project at some point.

## 1. High impact, high effort

Given we'll have some more resources for the next sprints, I suggest we actually go in and tackle the hard problems that will really pay off dividends. Some of these include:

### a) Splitting the plugin server into ingestion and runner servers

A lot of the work is done on #9314. However, there's still a good chunk of work needed to get this over the line, including some follow-ups to that PR, like rewriting the `onAction` path (Phase I of the split keeps `onAction` in the ingestion server).

#### Why

- Increased reliability and robustness for both servers (most importantly: things like historical exports don't affect ingestion at all)
- Ability to scale independently
- Easier to debug

### b) Yeetcode - Plugin Server Edition!

Essentially https://github.com/PostHog/posthog/pull/7830 (and all the follow up PRs) for the plugin server.

We keep around a lot of effectively dead code for Postgres ingestion on the plugin server. Getting rid of this will reduce complexity, make the server simpler and easier to understand/debug/onboard into. It will also make future changes easier.

#### Why

While this won't really change anything functionality-wise, it is really important as it pertains to tech debt management.

#### Further considerations

- Postgres tests?
- Get public jobs out of Celery and nuke the whole Celery client

### c) Tests Refactor

Our tests are slow and flaky. They also could use some standardization at places. Let's make them better.

#### Why 

Bad tests slow everyone down and increase the risk of merging problematic code.

### a) Kafka connectivity

Investigate why we lose connectivity to Kafka often, why ingestion goes down completely when (supposedly) only one broker goes down. + improve all this.

Some work started in #9581.

#### Why

This has bit us quite a few times already and often requires help from a human. No bueno.

### b) Allowing horizontal scaling for ingestion on self-hosted

Self-hosted instances can't really scale ingestion horizontally very well. 

One can run multiple plugin servers, and the may all pick up some jobs etc, but currently only one of them can consume and produce events.

Essentially getting this work over the line: https://github.com/PostHog/charts-clickhouse/pull/243 

And/or writing up a mechanism for updating Kafka topic definitions on self-hosted (this is tricky).

#### Why

Self-hosted users are currently limited at scale.

### c) Define plugin server retries policy https://github.com/PostHog/posthog/issues/8829

Define a reasonable retries policy, communicate it effectively, and implement a robust system to enforce it.

#### Why

Plugin devs and users are unsure of the guarantees offered to them in terms of e.g. deliverability. Poor policies (and/or poor implementation of them) has also bit us in the past. 

### d) Runbooks and alerts

Better monitoring and alerting systems. Descriptions on all dashboard, runbooks with every alert.

If an alert can be mitigated with automated action, we should prefer that over a runbook.

#### Why

Makes it easier to debug and fix issues. Enables everyone to fix ingestion issues, not just yours truly.

### e) Healthchecks

Our healthchecks are currently very limited. We should expand them to really paint a good picture of instance health. We should also make sure both ECS and self-hosted are actually using these checks to trigger actions. Some work has started in this area.

#### Why

In order to trigger automated actions or alerts for human intervention, we should have a good picture of what's actually wrong.

### a) Improve alive check

We currently have a check that tests for the plugin server being "alive", but in reality it isn't extremely useful when one runs multiple servers. It helps indicate that there is one server alive and well so probably things will be fine, but this might also just be 1/32 servers. 

#### Why

Paint a full picture to help users understand their overall cluster's health.

### b) Plugin server job management #7133

Allow plugins to cancel jobs, effectively.

#### Why

If plugin devs have the tools to build more robust plugins, we win. This would also allow devs to be less reckless and cancel jobs, thus reducing load for us.

### c) Improve Postgres queries (fix errors)

https://github.com/PostHog/posthog/issues/8343
https://github.com/PostHog/posthog/issues/8377
https://github.com/PostHog/posthog/issues/8379

We can reduce load by rewriting some queries that rely on the database throwing an error.

#### Why

Fewer errors means less noise and less work. Both help make a system more reliable and maintainable.

**Comment by yakkomajuri** [comment]
cc @tiina303 @timgl @fuziontech @Twixes @marcushyett-ph

**Comment by marcushyett-ph** [comment]
Thanks for putting this together @yakkomajuri seems like a great list to me, couple of questions:

* You mention "active babysitting (from myself and others), to nudge things back into the right track", it's not super clear to me which of these will remove the need for active babysitting? I'm also intrigued why we're not going one step beyond "Runbooks and alerts" with some kind of automated remediations?
* These all sound like they're stopping immediate bleeding (which definitely feels like the urgent priority), was wondering if there's any projects that make sense to do since we're focusing on this area that would have a longer-term impact on ingestion reliability (that aren't on this list)?

**Comment by yakkomajuri** [comment]
Note to self. Other tangential things include: 

* A memory queue to reduce round trips to Postgres for `runNow` jobs (although the `graphile-worker` maintainer seemed interested in making this a baked in thing when I mentioned it - much slower timeline though)
* https://github.com/PostHog/posthog/issues/8538
* https://github.com/PostHog/posthog/issues/8266
* reduce processEvent timeout (and move to isolated-vm)?

**Comment by yakkomajuri** [comment]
Great questions @marcushyett-ph!

> You mention "active babysitting (from myself and others), to nudge things back into the right track", it's not super clear to me which of these will remove the need for active babysitting? I'm also intrigued why we're not going one step beyond "Runbooks and alerts" with some kind of automated remediations?

1a (server split), 2a (Kafka connectivity), 2c (retries policy), and 3c (query errors) are perhaps the best examples here.

Take 2a for instance. Currently when we have these issues on Cloud someone or something needs to restart the servers. This would end.

2c for example has also caused us to have to jump in manually to update the policy during outages, because we never gave it extensive thought in the first place.

And then the server split will both reduce outages related to the interaction between "async plugins" and ingestion, as well as allow us to have better automated scaling policies.

Lastly, about automated remediations, that's indeed part of this work, the healthchecks mentioned will enable more of this.

I didn't exactly know where to fit it in, but indeed, if an alert can be mitigated with automated action rather than a runbook, we'll take that route. I'll update that section and add a healthcheck section as well.

> These all sound like they're stopping immediate bleeding (which definitely feels like the urgent priority), was wondering if there's any projects that make sense to do since we're focusing on this area that would have a longer-term impact on ingestion reliability (that aren't on this list)?

While a lot of these projects might seem to be "stop immediate bleeding" projects, they're actually all coming from a long-term view.

Things like splitting the plugin server, refactoring tests, and yeetcode are all things that by themselves don't necessarily fix any problem, but will have a **huge** long term effect in making the server more robust and easier to manage.

Overall the plugin server split taken all the way is probably the highest impact thing we can do overall. 

From a self-hosted impact an example here is also the horizontal scaling.

And then some even more long-term ideas live here:

https://github.com/PostHog/posthog/issues/8957

**Comment by marcushyett-ph** [comment]
@yakkomajuri thanks for all the details - excited to see these changes shipped!

**Comment by tiina303** [comment]
Regarding the alerting and runbooks and healthchecks and babysitting I'd love if we could get to a state where we don't need to monitor graphs when we land PRs (think of this as a metric that shows we've achieved it there are other benefits obviously if we're in that good of a state monitoring wise) and get alerted instead.

**Comment by fuziontech** [comment]
@yakkomajuri This is _exactly_ what we needed here. I'm particularly excited for the YEETCODE cleanup. There is so much tech debt we can pay off here. Thank you so much for doing this.

Can you add a _super rough_ estimate of how much time each item will take in terms/units of sprints and whether they can be split up for multiple people in your opinion? Either at the (high effort, medium effort, low effort) levels, or at the line items themselves.

**Comment by yakkomajuri** [comment]
We did the vast majority of these! Pending items were less important and fall under other tasks now, so closing this!
