### ISSUE TITLE
Filter incoming capture data

### ISSUE THREAD

**Issue by steveshiny** [PostHog/posthog#966]
**Is your feature request related to a problem? Please describe.**
In our scenario, we have data coming from a single distinct id that we'd like to avoid even capturing at all. It's from an older version of the software and we believe illegally distributed (being out of date messes up analytics because it doesn't reflect current changes, etc.).

**Describe the solution you'd like**
Ideally, we could provide a set of distinct ids (or even more broadly, other custom properties for an event, but in our current case just the distinct id would suffice) - if an incoming request matches any of those ids, they'd be skipped entirely - not getting written to the database at all.

**Describe alternatives you've considered**
In the short term, we're probably just going to hardcode a rule in the code and deploy the change ourselves. Alternatively, we can exclude data in the backend queries wer're running off the database, but that still incurs the storage costs of course.

**Additional context**

***Thank*** you for your feature request - we love each and every one!

**Comment by Twixes** [comment]
I agree, also an IP filter might be useful for excluding e.g. internal company traffic. This is something Google Analytics has (https://support.google.com/analytics/answer/1034840).

**Comment by paolodamico** [comment]
This can now be easily accomplished with a custom plugin.
