### ISSUE TITLE
Tooltip overflow or truncation

### ISSUE THREAD

**Issue by corywatilo** [PostHog/posthog#9662]
It seems like insights tooltips with long action names could be improved...

[via](https://app.posthog.com/insights/oVHjTLUD)

<img width="622" alt="image" src="https://user-images.githubusercontent.com/154479/166955101-d179c525-a9a6-4a31-ab82-9ffd4eab3107.png">

**Comment by benjackwhite** [comment]
I think this got solved at some point
<img width="286" alt="Screenshot 2022-08-31 at 10 23 48" src="https://user-images.githubusercontent.com/2536520/187631324-5a9c748a-2b1f-4dcd-94df-88e70fa84813.png">
