### ISSUE TITLE
Graph shows inaccurate data when using a grouping that exceeds the selected date range

### ISSUE THREAD

**Issue by corywatilo** [PostHog/posthog#9663]
I understand this is a weird one, and is likely to happen when using a date range that has a grouping that exceeds the range, but...

Note the date on the tooltip and graph (Jan 1, 2022) despite the fact my date range is explicitly set to start on Jan 31. ([source](https://app.posthog.com/insights/oVHjTLUD))

This graph really doesn't provide much value, so I'd almost suggest PostHog automatically change the grouping to something more granular when the grouping exceeds the date range and has < X data points.

<img width="985" alt="image" src="https://user-images.githubusercontent.com/154479/166955563-cae5510f-6828-429a-8041-ebeac0fd412b.png">

**Comment by marcushyett-ph** [comment]
Related: https://github.com/PostHog/product-internal/pull/305
