### ISSUE TITLE
Weekly active + weekly interval doesn't work

### ISSUE THREAD

**Issue by timgl** [PostHog/posthog#9668]
## Bug description

If you set weekly active + grouped by interval, if there's no data it'll correctly bucket by week, but if there is data it'll bucket by day
https://app.posthog.com/insights/wTV8gHqF

<img width="1177" alt="image" src="https://user-images.githubusercontent.com/1727427/166977153-8d990d54-7488-4046-a3eb-6ec938e48f1e.png">

## How to reproduce

1. Create insight, counted by weekly active and week interval
2. Verify data points are per day instead of per week
3.

## Environment

- [ ] PostHog Cloud
- [ ] self-hosted PostHog (ClickHouse-based), version/commit: _please provide_
- [ ] self-hosted PostHog (Postgres-based, legacy), version/commit: _please provide_

**Comment by Twixes** [comment]
Fixed by #12302.
