### ISSUE TITLE
Error when using Toolbar in Next.js app

### ISSUE THREAD

**Issue by hmbrg** [PostHog/posthog#9671]
## Bug description

When opening the toolbar from withing PostHog, I'm getting the following error on my Next.js app:

```javascript
main-5ccab6262f53e71b.js:1 
        
       Invalid href passed to next/router: /#__posthog=%7B%22action%22%3A%20%22ph_authorize%22%2C%20%22token%<READACTED>22actionId%22%3A%20null%2C%20%22userIntent%22%3A%20null%2C%20%22toolbarVersion%22%3A%20%22toolbar%22%2C%20%22dataAttributes%22%3A%20%5B%22data-attr%22%5D%2C%20%22jsURL%22%3A%20%22https%3A//app-static.posthog.com%22%2C%20%22instrument%22%3A%20true%2C%20%22userEmail%22%3A%<READACTED>0%22distinctId%22<READACTED>, repeated forward-slashes (//) or backslashes \ are not valid in the href
```

According to the error, the query parameters don't seem to be encoded in a way that's compatible with the next/router.

Thanks for looking into this!

## How to reproduce

1. Goto "https://app.posthog.com/toolbar"
2. Click "Open with Toolbar"
3. Error shows up in console on frontend

## Environment

- [x] PostHog Cloud
- [ ] self-hosted PostHog (ClickHouse-based), version/commit: _please provide_
- [ ] self-hosted PostHog (Postgres-based, legacy), version/commit: _please provide_

## Additional context
-

**Comment by pauldambra** [comment]
I can see that the backend is receiving a properly encoded URL in the request... but it generates a URL param with `//`

**Comment by pauldambra** [comment]
@hmbrg that fix is deployed to cloud now... Can you check if it has resolved for you?

**Comment by hmbrg** [comment]
@pauldambra Works great! Thanks for the quick response!
