### ISSUE TITLE
Ability to add multiple events with a regular expression while creating insight.

### ISSUE THREAD

**Issue by o1lab** [PostHog/posthog#9680]
## Is your feature request related to a problem?

- Creating an insight by adding event one by one takes a lot of time.

## Describe the solution you'd like

- Allow adding events based on regular expression like if there are 
- Example : user should be able to add events `a:1`, `a:2` with `a:*`

**Comment by o1lab** [comment]
This is really needed feature for building insights quickly. Currently we've tens of categories of events and each category has  20-30 events. This makes the process of building insights really slow. Please do consider this enhancement soon.

**Comment by neilkakkar** [comment]
Hey @o1lab , have you considered using actions to aggregate events? That way, you only have to do it once, and use the action everywhere else in the app
