### ISSUE TITLE
Add first seen date to user properties

### ISSUE THREAD

**Issue by sdgandhi** [PostHog/posthog#9683]
## Describe the solution you'd like

When building insights, I would like to filter on a person's first seen date.

## Describe alternatives you've considered

Can't find alternative.

## Additional context

The first seen date exists on person because I can see that in the person detail page. However this is not an official property, so it's not exposed in insight filters.

**Comment by macobo** [comment]
Duplicate: https://github.com/PostHog/posthog/issues/3031

**Comment by mariusandra** [comment]
You can now do `select created_at from persons`
