### ISSUE TITLE
Cannot track users across multiple domains

### ISSUE THREAD

**Issue by mteterel** [PostHog/posthog#9684]
## Bug description

We have multiple domains for our project which are linked to the same PostHog instance and project. However we cannot, at the moment, track users across different domains, PostHog always create a different user ID.

## How to reproduce

1. Go on domain1.some.site
2. Click on a button that brings you to domain2.some.site
3. In PostHog, 2 different users are now created

## Environment

- [x] self-hosted PostHog (ClickHouse-based), version/commit: 1.31.1

**Comment by neilkakkar** [comment]
Hey @mteterel , if you have a way to identify users (for example, if both domains have a login page), you can use `posthog.identify()` to connect these users.

**Comment by id6tm-mteterel** [comment]
One of our domains does not have a login page, but it is using the same instance and PostHog project than another domain that do. It does not appear to reconciliate data.

What I expect from PostHog was that : 

- you go on Domain A
- access Domain B from Domain A
- login on Domain B and identify with DB ID
- all previous events with the random ID are transformed to use the distinct DB ID
- if you go back to Domain A, it uses the distinct DB ID since the Posthog instance is the one and the same

**Comment by mariusandra** [comment]
Hey there, what you're describing requires the use of third party cookies to track a user across the web. Such cookies are becoming more and more penalized by browsers, and if we would enable this, it would hurt our ability to simply track visits within one domain.

If your domains are all related (both are subdomains), you may use cross-domain cookies to pass around a unique ID that your users will be identified with. If you're using completely separate domains, you'll need to pass the ID dynamically in a link from one domain to another, the same way that Google Analytics does.

**Comment by peteygao** [comment]
@mariusandra Okay, that makes sense about 3rd party cookies. Does that mean if we use `posthog.identify(UUID)` across two different subdomains (where we generate the UUID and store it in cross-domain a cookie), internally Posthog will merge them as the same user even if the `identify` call is from two different subdomain?

Context: We're running into the same issue as @mteterel and was expecting the user merging across domains to be automatic, but I can understand why it isn't after your explanation. Thanks.

**Comment by mariusandra** [comment]
@peteygao that's right. If you're tracking events from different domains onto the same project, as is common practice, then using the same distinct ID will link the session to the same user, no matter the domain.
