### ISSUE TITLE
Support clickhouse 22.3 LTS (or later)

### ISSUE THREAD

**Issue by macobo** [PostHog/posthog#9685]
## Is your feature request related to a problem?

Clickhouse 22.3 released native JSON datatype support. This can speed up queries significantly.

See https://github.com/PostHog/posthog/issues/7962 for outdated benchmarks.

## Additional context

TBD: More benchmarks.

**Comment by fuziontech** [comment]
Was wondering if there would be any change to the query syntax and details are here:
https://github.com/ClickHouse/ClickHouse/pull/23932

Looks like new query pattern will be
`data.key1.key2::Int64` as an example

I haven't seen any documentation in docs yet for this, but very excited to give this a try :)

**Comment by macobo** [comment]
Ran the tests yesterday, everything now passes (single ordering-related test needed fixing).

About JSON columns: Actually using these is a separate task _after_ we are on 22.3 - it will require a big async migration to make use of it that rewrites all properties (yikes).

**Comment by fuziontech** [comment]
>Ran the tests yesterday, everything now passes (single ordering-related test needed fixing).

😎 awesome

>About JSON columns: Actually using these is a separate task after we are on 22.3 - it will require a big async migration to make use of it that rewrites all properties (yikes).

💯 Totally. I am just happy that it is in this LTS cut and we can work towards it. I also hadn't looked into how the query patterns changed so I was just throwing that in here in case anyone was wondering. The work to get this in will be totally worth it, but I agree (yikes 👻 )
