### ISSUE TITLE
Give more info in piechart tooltips

### ISSUE THREAD

**Issue by jamesefhawkins** [PostHog/posthog#969]
**Is your feature request related to a problem? Please describe.**
If you create a pie chat, with two events with different filters, the tooltips only display the event name, which means you don't know which part of the pie chart is which.

**Describe the solution you'd like**
Tooltips for piecharts should display filters (if we can make the UX work?)

**Describe alternatives you've considered**
Don't use pie charts.

**Additional context**
Was requested in PH Users Slack by a user.

**Comment by Twixes** [comment]
This is now improved.
