### ISSUE TITLE
EditorPanels WIP is too cramped for Aggregated Trends steps

### ISSUE THREAD

**Issue by benjackwhite** [PostHog/posthog#9701]
## Bug description

Trends steps with aggregations are too cramped to work with:

<img width="446" alt="Screenshot 2022-05-09 at 19 11 40" src="https://user-images.githubusercontent.com/2536520/167462280-37fc32a8-b12e-41e1-8484-df0705815210.png">

## How to reproduce

1. With the new Editor Panels on Insights...
2. Select `Trends` and then add a step with an aggregation
3. The UI will look so cramped it is almost unusable

## Environment

- [x] PostHog Cloud (feature flagged)

Related to https://github.com/PostHog/posthog/issues/8929

**Comment by clarkus** [comment]
It looks like there's more to do here - the icons are spaced pretty far apart, they're sized to be much smaller than all the other icon buttons, and the inputs in there look pretty different. It looks like the query builder was wrapped in a collapsible container, but nothing else was done to align the form elements and icons. 

<img width="598" alt="Screen Shot 2022-05-10 at 8 16 19 AM" src="https://user-images.githubusercontent.com/254612/167663515-2b10c393-672b-4b1c-92b7-e42cb4a4e098.png">

figma link https://www.figma.com/file/NHPA2hVWwaKp4eTGWdigs9/Product-Concepts?node-id=1489%3A9597
