### ISSUE TITLE
Updated date range selection workflow

### ISSUE THREAD

**Issue by clarkus** [PostHog/posthog#9727]
## Is your feature request related to a problem?

Selecting a date range in PostHog can be pretty tedious depending on what you're trying to accomplish. Select a starting date for a fixed time range requires three clicks / actions just to pick the first range parameter. Our list of preset rolling time ranges use days as the most common time unit, but research shows that users use a broader range of units. 

## Describe the solution you'd like

**Prioritize selecting rolling / relative date ranges using a list of preset values.** Reduce the number of options and provide a semi-custom rolling range via a numeric input and a time units. The core change here is to provide a semi-custom rolling time range option. These are always relative to the current date and are formatted as a numeric value and a time unit option. For example, the last [3] [days], the last [1] [quarter], the last [18] [weeks]. A custom option would reduce the need for specific presets. We could also increase user confidence if we translated relative ranges to actual time frames using tooltips. 

![Group 8966](https://user-images.githubusercontent.com/254612/167720548-5f98ae3d-c915-487d-967a-2618f22c977d.png)

**Relative dates are represented as relative ranges in the summary state for the picker.** Likewise, fixed / absolute range are more specific and show the actual range selected. 
![relative date summary](https://user-images.githubusercontent.com/254612/167718661-8b72bf86-b77d-49e5-b1d5-4b2c3a65c419.png)
![absolute date summary](https://user-images.githubusercontent.com/254612/167718791-6c5d12df-f1bb-47f3-9ac8-52c0f87a835c.png)

**Separate selecting a fixed / absolute range and provide reasonable defaults to reduce the number of actions it takes to submit a value.** When selecting a custom fixed range, ditch the start and end date inputs and instead directly show the calendar immediately. A user would just need to select a start date to have a valid time range if the end date defaults to the current date.

![Frame 8390](https://user-images.githubusercontent.com/254612/167719731-45d5c6ec-994d-4b03-83fa-35289bd5af07.png)

**Changes to consider based on the research @marcushyett-ph did for https://github.com/PostHog/product-internal/pull/305**
1. Change the default rolling time range to 30 days for insights
2. Automatically adjust time grouping units to the range selected. For example if you select the last 24 hours, today, yesterday, it doesn't make sense to group by any unit larger than a day. Hours would be the most approachable unit for this scenario.
3. When selecting a fixed time range, disallow selection beyond the current date. It doesn't make sense to look at future dates in this scenario. We don't have data for the future as we don't do predictions. Our default end date for a custom time range should be the current date. 
4. When selecting fixed ranges, reduce the number of clicks / actions it takes to get to the calendar interface. Right now this takes three clicks just to pick a starting date. We also make users select an end date when we could have a reasonable default of the current date here. 
5.  Add a quarterly option to the relative range picker
6. Make it more obvious when a fixed range is applied to an insight. 
7. Consider expanding our preferences / project settings for time. For example, starting the week on Monday instead of Sunday, time value formatting (12 versus 24 hour clocks), timezones, etc. 

## Additional context

- https://github.com/PostHog/product-internal/pull/305
- https://github.com/PostHog/posthog/issues/9664
- https://github.com/PostHog/posthog/issues/9453
- https://github.com/PostHog/posthog/issues/9027
- https://github.com/PostHog/posthog/issues/6619
- https://github.com/PostHog/posthog/issues/8640
- https://github.com/PostHog/posthog/issues/8460
- https://github.com/PostHog/posthog/issues/8059
- https://github.com/PostHog/posthog/issues/7625

- Figma - https://www.figma.com/file/NHPA2hVWwaKp4eTGWdigs9/?node-id=1768%3A6935

**Comment by clarkus** [comment]
Related but somewhat separate are time ranges for dashboards. Dashboards can override an insight's time range temporarily. The same considerations for picking a time range could apply to the dashboards feature.

**Comment by joethreepwood** [comment]
This looks like it addresses my feedback perfectly - thanks Chris!

**Comment by marcushyett-ph** [comment]
This is super-solid, thanks @clarkus!

**Comment by kappa90** [comment]
Incorrectly closed after #10462, which is meant to run as an experiment
