### ISSUE TITLE
Ingestion pipeline refactor and onEvent/onAction breaking changes

### ISSUE THREAD

**Issue by yakkomajuri** [PostHog/posthog#9737]
## Motivation

We're approaching a spot where we want to do some event-level processing separately from the main pipeline. Either due to buffering, separating ingestion and async jobs, so onEvent/onAction load doesn't affect main process, consuming from CH, name it.

## Problem

We currently expose the PluginEvent interface to plugins everywhere - for `onEvent`, `onAction` functions specifically. However internally we don't have access to it once we do the split.

## Solution

Minor breaking changes to the payload `onEvent` & `onAction`  receive.

These changes are:

- `timestamp` will be always set
- `now`, `sent_at` will be removed
- `offset` and `kafka_offset` will be removed
- `site_url` is uncertain - @yakkomajuri  will research and see if any plugins are using it
- `properties` will be a different shape than in `processEvent`  - we add/overwrite in case of conflicts some properties. Some examples of changes:
    - group_X properties for group analytics
    - $set, $set_once is always set
    - Initial utm properties are set

With this, the explicit user contract becomes:

`processEvent` will receive raw event payloads (no change)
`onEvent` will receive the same event payload as we store in our database (instead of a "third" type in between the raw payload and the final event)

## Next steps

- [ ] @yakkomajuri to map out `now`, `sent_at`, and `site_url` usage
- [ ] Make this clear in Docs and release notes

**Comment by yakkomajuri** [comment]
## Plugins usage

✅  = not impacted by breaking changes
❌  = impacted by breaking changes

### sent_at / now

- [Redshift Export](https://github.com/yakkomajuri/redshift-plugin/blob/main/index.ts) ✅ 
- [GCS Export](https://github.com/PostHog/posthog-gcs-plugin/blob/fb18120a574a9ddad02942a4e993be95368c9a81/index.ts#L45) ✅ 
- [Hubspot Plugin](https://github.com/PostHog/hubspot-plugin/blob/28742a3ba2b9f38773d6d9dbaa7b41f4e755e977/index.js#L178) ❌
    - I can update it to use `timestamp`
- [Postgres Export](https://github.com/PostHog/postgres-plugin/blob/8eedfc8d088228bdecf1737163f9e56dc5761048/index.ts#L136) ✅
- [Rudderstack](https://github.com/rudderlabs/rudderstack-posthog-plugin/blob/6b82a2671651c85e6782d68fd56d495de5d35edd/index.js#L58) ❌
    - We can: a) submit a PR b) pass `timestamp` as `sent_at` c) fork it and use the fork (we should anyway do this for community plugins)
- [S3 Plugin](https://github.com/PostHog/s3-export-plugin/blob/main/index.ts) ❌
    - Unlike GCS, the S3 plugin is not explicit about what it exports, so it just sends everything in the event payload over

### site_url

- [Redshift Export](https://github.com/yakkomajuri/redshift-plugin/blob/75cf0e5a8a224b13ddef44020d9c718de373bc4e/index.ts#L171) ❌ 
- [GCS Export](https://github.com/PostHog/posthog-gcs-plugin/blob/fb18120a574a9ddad02942a4e993be95368c9a81/index.ts#L105) ❌ 
- [Postgres Export](https://github.com/PostHog/postgres-plugin/blob/8eedfc8d088228bdecf1737163f9e56dc5761048/index.ts#L99) ❌ 
- [S3 Plugin](https://github.com/PostHog/s3-export-plugin/blob/main/index.ts) ❌

## Decisions

- `now` / `sent_at`: I'll update the plugins to use `timestamp` going forward. This will still be a breaking change for S3, so I'll update it to continue sending the values, either as `null` or as `timestamp`. I'll also make a note about this on the plugin, bump a major version, and add a log + description explaining this.
- `site_url`: We should still pass it with the payload. If we can easily use the Django-set site url we should do it, else it's fine to use the env var. This information should not have much importance for someone's warehouse analysis and can easily be backfilled if necessary (as it's not something that should change often if ever)

**Comment by macobo** [comment]
We discussed `site_url` async - given it's not actually being used by users I believe this can be removed without bigger hassle.

**Comment by macobo** [comment]
This has been merged, monitoring...

**Comment by yakkomajuri** [comment]
https://github.com/PostHog/hubspot-plugin/commit/35b13b8ee7e5862bb946a709f83552775d544da6
https://github.com/rudderlabs/rudderstack-posthog-plugin/pull/4

**Comment by yakkomajuri** [comment]
`site_url` plugins all destructure the event, so `site_url` will be sent but will be `undefined`. This is fine according to the users of those plugins
