### ISSUE TITLE
Cohorts not updating automatically

### ISSUE THREAD

**Issue by asavoy** [PostHog/posthog#9747]
## Bug description

We've created 8 cohorts that were initially calculated correctly, but don't automatically update unless we manually save them again. The first 2 we created hadn't recalculated since they were created 2 months ago. This looks similar to the bug reported in: https://github.com/PostHog/posthog/issues/1693 

> ![Screen Shot 2022-05-12 at 2 39 00 pm](https://user-images.githubusercontent.com/235466/167993416-67aba253-3861-4a71-afb0-84902fce648f.png)

These cohorts are setup using the "Dynamic" type with matching criteria of "Match users who have properties", example:

> ![Screen Shot 2022-05-12 at 2 43 03 pm](https://user-images.githubusercontent.com/235466/167993587-fcdf3c0c-ad4b-4e21-ad51-a1aa2d79977b.png)

## How to reproduce

1. Create a dynamic cohort, with "Match users who have properties" and some property condition
2. It will be populated correctly initially
3. Check again after 30 mins, or a day, and the cohort will have "Last calculated" still match the "Created" timestamp. We expect this to have been recalculated automatically since then, because it's a dynamic cohort and the "Last calculated" tooltip says it will update every 15 mins.

To check that the cohort doesn't break when recalculating, we can try to force an update:

5. Edit the cohort and hit save, and the cohort does successfully recalculate. The "Users in cohort" number and "Last calculated" timestamp update as expected.

## Environment

- [ ] PostHog Cloud
- [x] self-hosted PostHog (ClickHouse-based), version/commit: 1.35.0 ef5d2dbe7c6c00c1b7ccaff52ecb84fc4b2292a2
- [ ] self-hosted PostHog (Postgres-based, legacy), version/commit: N/A

**Comment by voarsh2** [comment]
I'm getting this issue too

**Comment by voarsh2** [comment]
Just thought I'd mention that I scaled up worker, events plugins and web to 2 instances each and it seems to updating more frequently now.......

**Comment by luc-vocab** [comment]
I'm experiencing this as well on posthog cloud, as a trial user.

**Comment by neilkakkar** [comment]
Hey folks, I'm pushing a fix to update the tooltip, they're now supposed to update every 24 hours, not 15 minutes.
