### ISSUE TITLE
The percentage values for the 'time to convert' type funnels is not visible on the dashboard

### ISSUE THREAD

**Issue by djindal03** [PostHog/posthog#9749]
## Bug description
The percentages for 'time to convert' type funnels are not visible on the dashboard.
The first snippet is of dashboard view and the second snippet is when we view the insight in the 'Insights' tab.

*Please describe.*  

*If this affects the front-end, screenshots would be of great help.*  
![image](https://user-images.githubusercontent.com/77572848/168026661-d655ade7-db65-473a-a12c-56947f37d21c.png)
![image](https://user-images.githubusercontent.com/77572848/168026765-e57e4da7-bc68-45e9-9353-baf042c8a124.png)

## How to reproduce

1. Create a 'time to convert' type funnel in the Insights.
2. See that the corresponding percentages are visible over each bar.
3. Add the funnel to the dashboard and you'll see that the percentages are not visible.4.

## Environment

- [x] PostHog Cloud
- [ ] self-hosted PostHog (ClickHouse-based), version/commit: _please provide_
- [ ] self-hosted PostHog (Postgres-based, legacy), version/commit: _please provide_

**Comment by liyiy** [comment]
hi @djindal03 :) 

This issue should be resolved now so I'm going to close the ticket out but feel free to open it back up if it isn't!
