### ISSUE TITLE
ClickHouse - KafkaEngine - failure scenarios

### ISSUE THREAD

**Issue by guidoiaquinti** [PostHog/posthog#9752]
## Bug description

We should make sure the ClickHouse Kafka engine is configured correctly to don't DDOS Kafka in case of issues. We should make sure we have a way to configure:

* error retries, exponential backoff with jitter
* insert rate (as by going at full speed it can melt both CH and Kafka) 

## Environment

- [X] PostHog Cloud
- [X] self-hosted PostHog (ClickHouse-based), version/commit: _please provide_

**Comment by yakkomajuri** [comment]
So there isn't too much we can do in terms of configuration here. We've set `kafka_skip_broken_messages` but it seems that for some serialization errors this isn't respected. 

Things to consider:

1.  Increasing`kafka_num_consumers`
2. Seeing if 22.3 fixes this issue
3. Trying a different format for the data 
4. Keep fixing each individual problem as it comes about

If we keep having problems we might just need to write our own service to insert into ClickHouse.

**Comment by yakkomajuri** [comment]
Although looking at this again it seems `kafka_skip_broken_messages` is not set on the DLQ. I'll configure that and it should handle errors like these.

It's a terrible pattern though that CH has that if it isn't set to skip broken messages it keeps coming back for the same message batch indefinitely.

**Comment by guidoiaquinti** [comment]
Once we verify those issues are not available in the latest CH version, what do you think about opening an issue upstream to keep track of the enhancements?

**Comment by tiina303** [comment]
Here's what we currently have in code & cloud (via `SHOW CREATE TABLE kafka_...`):

| Table | cloud | code 
|----|----|----
| events_json | 100 | 100  - [code](https://github.com/PostHog/posthog/blob/801c2a5f7e44bcab75b69a241342a64b84a6d993/ee/clickhouse/sql/events.py#L115)
| events proto | already nuked | 100  - [code](https://github.com/PostHog/posthog/blob/dc7f2f93be0db080109cf292b621e129cf3c5ae4/ee/clickhouse/sql/clickhouse.py#L43)
| session recordings | 0 | 0  - [code](https://github.com/PostHog/posthog/blob/c3649f91c91526a0036826c5ca9c66fb975fe65f/ee/clickhouse/sql/session_recording_events.py#L65) 
| person | 0 | 0 -- [code](https://github.com/PostHog/posthog/blob/5887bd214377e9991447cdf362c6d8a9e4195fcf/ee/clickhouse/sql/person.py#L45)
| DLQ | 0 | 1000 - in Yakko's PR
| groups | 10 | 0 -- [code](https://github.com/PostHog/posthog/blob/717ee74cdf98602530663b0d6cb52241b839f58c/ee/clickhouse/sql/groups.py#L37)
| plugin log entries | 0 | 0 -- [code](https://github.com/PostHog/posthog/blob/717ee74cdf98602530663b0d6cb52241b839f58c/ee/clickhouse/sql/plugin_log_entries.py#L43)

Note that for groups the code is out of sync from reality in cloud.
Should we set the `skip_broken_messages` everywhere to 100 (except DLQ which we set to 1000)?

**Comment by yakkomajuri** [comment]
Yeah let's set 100 everywhere. DLQ can be more as it is less important.

Could you write that up for us @tiina303?
