### ISSUE TITLE
Allow license downgrades

### ISSUE THREAD

**Issue by simfish85** [PostHog/posthog#9753]
## Is your feature request related to a problem?

Sometimes customers want to move from Enterprise to Scale and Scale to Open Source, we should allow this self-serve license key deactivation in the platform.

## Describe the solution you'd like

Users can select to remove their license key and have the aligned features removed too.  Ideally this would update Subscriptions in Stripe too but that's a nice to have for now.

**Comment by Twixes** [comment]
Closed by #9760.
