### ISSUE TITLE
RFC: Exporting of Dashboards / Insights

### ISSUE THREAD

**Issue by benjackwhite** [PostHog/posthog#9759]
# What are we talking about?

As part of [the current sprint](https://github.com/PostHog/posthog/issues/9711) we will be looking at exporting of Insights and Dashboards to Image / PDF. 

## Sprint scope
* Just **Exporting** with a manual trigger (i.e. from the App interface)
* Ensuring the "exporter" is able to reach the main application to render the needed assets (something like the [shared dashboard custom render](https://github.com/PostHog/posthog/blob/master/frontend/src/shared_dashboard.ejs) )

### Technical Challenges

- [x] Rendering the various components server-side
  * Some tools exist for doing "straightforward" renders like [node-canvas](https://github.com/Automattic/node-canvas) but realistically for anything complex / react component based we need to use a headless browser like [puppeteer](https://github.com/puppeteer/puppeteer) ( or [pyppeteer??](https://github.com/pyppeteer/pyppeteer) )
     * 🚫 Ruling out p**y**ppeteer - stable version runs a very old chromium and the repo has a lot of internal conflict...
  * We need a solution that supports Cloud and self-hosted - e.g. no lambda or 3rd party services
  * ✅ **Decision** Going with Selenium as it seems to still be the most stable option and allows us to have one method for rendering insights (client-side HTML/JS)
- [x] Supporting future use cases - async rendering
  * For this scope we will take a frontend request, trigger the render and return the image. For the upcoming extensions we will likely want this to be triggered by backend automation so we may as well make this solution agnostic of caller
  * ✅ **Decision** Exporting is done in the worker using celery tasks. Output is written to PG entry currently as BinaryData - S3 alternative for the future
- [x] Storage of generated assets
  * A single Insight is _probably_ small enough to be stored as a data string in Postgres next to the Insight _(thumbnail previews of Insights anyone??)_ but larger images like Dashboards and certainly PDFs might not work so well
  * [Some work is in progress](https://github.com/PostHog/posthog/pull/9294) which will add S3 support but we should consider this a stretch / optional
  * ✅ **Decision** PG is good enough for storage of screenshots (dashboards are < 1Mb). Once we have S3 we should use it and store a `content_url` to the s3 asset instead of the BinaryData
  - [ ] **Future Issue**: Support Blob storage for Exported Assets 
- [x] Waiting for the query(ies) to settle
  * If we are rendering a Dashboard with multiple Insights we likely need to ensure that all running queries have settled. 
  * 🤔 This will need to be investigated with some much longer running queries to see what happens

### Design Challenges
@lottiecoxon @clarkus 
- [ ] Manual Export
  * This is probably _(famous last words)_ the most straightforward element. We already have Export button for CSV data in some areas. We could extend this to be a dropdown with multiple options etc.
  * When viewing an Insight, elements can be changed without being persisted like the visualisation type.
- [x] Export / Printable View for Insights/Dashboards
   * We need a dedicated view for Insights and Dashboards meant for printing / read-only viewing. 
   * What sort of branding / auxiliary info should be there - I/D name? Posthog logo? Link to actual item - QR code vs real link? 
   * What are the sensible dimensions for Dashboard prints? Are Insights dimensions fixed or scaled?
   * What to do with info that is normally discovered on hover such as Legend, counts?
- [ ] Scheduling (implementation - next sprint) [Figma](https://www.figma.com/file/gQBj9YnNgD8YW4nBwCVLZf/PostHog-App?node-id=10317%3A49341#196430419)
  * Once we have the ability to do exports, the next steps will be to allow the User (or Organisation?) to schedule Reports which are **automated exporting and sending** to different channels (Slack, email).
  * This definitely needs some thinking:
    * are these schedules configured per user? per org?
    * are they configured on the Dashboard? the Insight? a dedicated "Reporting" screen? all of these?
    * permissions - who can configure schedules, who can modify created schedules?

### API Design
* `POST api/projects/:projectId/exports -d { "export_type": "image/png", "dashboard_id": 123 }` 
  - Create a new export for the given insight / dashboard
* `GET api/projects/:projectId/exports?dashboardId=foo&insightId=bar`
  - May make sense to see previous "snapshots" of the same insight?? (obviously out of scope for right now)
* `GET api/projects/:projectId/exports/:exportId` 
  - Retrieve the asset information
* `GET api/projects/:projectId/exports/:exportId/content`
  - Retrieve the asset itself

**Comment by marcushyett-ph** [comment]
This is looking awesome so far @benjackwhite 

A few of thoughts:
* Storage of assets definitely reach out to @guidoiaquinti @hazzadous, if we spend an extra couple of days getting blob storage up and running and use it for this - it will probably save us a lot of time dealing technical debt in the future of taking a suboptimal approach
* Export availability, one thing thats probably a reasonable amount of work is ensuring we have consistent support for export throughout the product, some insights and tables have it others don't - if we're adding more options to export we should ensure we're offering it everywhere its needed
* Branding, if we can nicely squeeze in a PostHog logo into these assets it could really help our brand if these images are being shared heavily outside of our platform


Regarding Scheduling:
- are these schedules configured per user? per org?
    -  I think they should probably be per project since thats the container we use for data, we may want to have multiple people on a single schedule (e.g. company dashboard), so per user could get messy
- are they configured on the Dashboard? the Insight? a dedicated "Reporting" screen? all of these?
    - I'd leave design to give input here, but I think we should make it as easy to subscribe as possible (going deep in a reporting screen feels like adding quite a lot of friction) - we will need some way to manage subscriptions though - but perhaps the best place to do this is in the email (e.g. click to unsubscribe opts you out - rather than a whole new settings page in the app)
- permissions - who can configure schedules, who can modify created schedules?
    - My general feeling is we should make it open to anyone who is a memeber of that project to create and modify schedules so we can enable as many people as possible to set these up
    - In the future we may want to restrict to project admins - but I'm not convinced there's a permissions risk given they already have access to the data if they're a member

One final note:
- These should probably be paid features initially, so we should consider how we do that and if we can upsell people to enable them

**Comment by clarkus** [comment]
My biggest question is what all is exportable and in what formats. It makes sense that charts are exported in in some static format, but there's more to insights than charts. There are detail tables, funnels offer correlation analysis, etc. Exporting those data sets in CSV makes sense, but if we're pushing content to users via a channel, it might make sense to also export in some structured (markup) format. 

Regarding scheduling / subscribing:
- Who can subscribe who? Are we relying on users to only set this for themselves, or is it feasible to schedule exports / subscriptions for users who rarely log in and prefer to use an alternate interface to receive updates (email, slack, etc). 
- What all can be subscribed to? Insights, dashboards, anything else? In the project home feature we have some specialized sets of data that could also be useful to export (recent recordings for example). 
- What preferences are needed to ensure things are sent at a sensible rate? 
- Who can be subscribed? Must the recipient have a posthog account? Can we push content to email addresses outside the organization? If we're pushing to slack, are the limitations on what data can be shared? 

> These should probably be paid features initially, so we should consider how we do that and if we can upsell people to enable them

I feel like subscriptions could be a paid feature, but basic exporting seems like it should be included for free. Being able to do a basic export of your data is a trust-building feature just feels aligned to our values.

**Comment by marcushyett-ph** [comment]
> I feel like subscriptions could be a paid feature, but basic exporting seems like it should be included for free. Being able to do a basic export of your data is a trust-building feature just feels aligned to our values.

I definitely agree with CSV export being free for all because of our values and especially since we support it to varying degrees today and it would not be okay to take it away. Exporting to PNG or PDF doesn't feel like it's going to be the feature that drives someone to pay (given they can just screenshot today), I'd be interested in @timgl's thoughts on this? 

Subscriptions and alerts make sense as premium features initially.

> My biggest question is what all is exportable and in what formats. It makes sense that charts are exported in in some static format, but there's more to insights than charts.

The detail matters a lot here - I'll create a spreadsheet at the start of next week to enumerate the potential insights and metadata that could be exported, so we can prioritize.

> Regarding scheduling / subscribing:

My 2 cents on these @benjackwhite may have other feedback / opinions

- **Who can subscribe who? Are we relying on users to only set this for themselves, or is it feasible to schedule exports / subscriptions for users who rarely log in and prefer to use an alternate interface to receive updates (email, slack, etc).**
    - I would keep this open to start with, i.e. anyone with access to the project can subscribe anyone else. This solves for the use-case of the exec who rarely logs in and can't remember / doesn't want PostHog credentials but wants to see the daily company dashboard
- **What all can be subscribed to? Insights, dashboards, anything else? In the project home feature we have some specialized sets of data that could also be useful to export (recent recordings for example).**
     - I would suggest limiting the scope initially to insights and dashboards as these are the most common ways of sharing findings and then iterating based on user feedback, I can imagine people might want to subscribe to: (A subset of) recent recordings, ongoing experiments
- **What preferences are needed to ensure things are sent at a sensible rate?**
    -  For subscriptions, I would suggest keeping this super simple initially, only supporting daily, weekly & monthly (this seems to be the standard from our competitors too)
    - For alerting this is much trickier, probably worth a deeper discussion and thought, but we will likely need to "debounce" the alert if it's triggered in quick succession and only send one alert to avoid spamming. We could offer the option to send maximum 1 alert per x hours or minutes and only send another alert for the same issue if it has gone back to normal in between. But like I said this needs a bit more thought.
- **Who can be subscribed? Must the recipient have a posthog account? Can we push content to email addresses outside the organization? If we're pushing to slack, are the limitations on what data can be shared?**
    - Personally I think you should be able to subscribe anyone from outside the organization, but we should probably warn a user if they're adding an email address they are not part of the organization. People will want to share certain dashboards or insights with external partners as for collaborative projects (e.g. us and our marketing agency) (this is a great way to give them access to a very controlled subset of data) - e.g. giving them access to PostHog itself will allow them access to much more granular data which is a risk. (This seems like common practice from most of our competitors too)
    - Sharing via slack, I think everything in an insight should be okay to share, e.g. data points, metadata about who created it and how its constructed, annotations. The main risk comes with sharing more granular / personal information (e.g. list of persons who did event) - which insights should only include in the case where it's explicitly queried for.

**Comment by marcushyett-ph** [comment]
> The detail matters a lot here - I'll create a spreadsheet at the start of next week to enumerate the potential insights and metadata that could be exported, so we can prioritize.

[This is an overview of where and how we support subscribing today](https://docs.google.com/spreadsheets/d/11MmoGzCK1aX5DSswMDFAeDYWbzst0ANP43fHny6_1Ws/edit#gid=0) across the app and where I think we should focus, i.e. Highest and High priority features (many of which already support CSV export)

**Comment by pauldambra** [comment]
You can export from the live events view...

So do we swap the API around so that

API Design

* POST `api/projects/:projectId/exports`
   * takes a body with something like `{type: 'insight', insight_short_id: 'blah', dashboard_id: 3}`
    * returns 201 with a location that export will be available when processing has completed
    * which allows for `{type: 'events', filters: {}, limit: x, date_after: 'blah'}` which would take longer to export
    * saves adding an exports sub_path in multiple places (and I wish I'd done similar for activity_log)

* GET `api/projects/:projectId/exports`
   your exports and their status

* GET `api/projects/:projectId/exports/:exportId`
   returns the export status, not the export

* GET api/projects/:projectId/exports/:exportId(.png|.pdf|.csv|.etc)
   Retrieve the asset itself

**Comment by benjackwhite** [comment]
@pauldambra this is great thinking. So much so that its what I had started to change around this morning anyways 😅  I updated the Description to reflect your points 👍

**Comment by benjackwhite** [comment]
See https://github.com/PostHog/meta/pull/57
