### ISSUE TITLE
Label y-axis for trend-based insights

### ISSUE THREAD

**Issue by clarkus** [PostHog/posthog#9765]
## Is your feature request related to a problem?

It can be hard to know what exactly is being measured on complex insights. A simple restatement of the event / aggregation on the y-axis could make insights more approachable and easier to understand without digging into the underlying query.

## Describe the solution you'd like

For the top value on the y-axis, append the units. This doesn't need to repeat for every value. Charts never intersect this top line, so there shouldn't be any conflicts or overlapping. For example, `500 pageviews` or `24 weekly active users`. 

<img width="868" alt="Screen Shot 2022-05-12 at 8 37 48 AM" src="https://user-images.githubusercontent.com/254612/168114101-1c0b9b54-ab84-4c30-84cf-4c2e37c91b96.png">

## Describe alternatives you've considered

None at this time. 

## Additional context

-[Reported via slack!](https://posthog.slack.com/archives/C01F31E9PRD/p1652361770924599)

**Comment by timgl** [comment]
Chart-js has a default way of doing this which'll be a lot easier to implement: https://www.chartjs.org/docs/latest/axes/labelling.html

**Comment by EDsCODE** [comment]
I think we can conditionally render the tick marks based on the index. But, not immediately sure how to get it to be grafted into the horizontal lines
<img width="335" alt="Screen Shot 2022-05-12 at 11 47 48 AM" src="https://user-images.githubusercontent.com/13127476/168116073-6f4426aa-53ec-43af-907a-d5e014ac1006.png">

**Comment by EDsCODE** [comment]
Also, what should we display if there's a mix of types so if one line is showing total volume of pageviews and another line is displaying "unique users"

**Comment by clarkus** [comment]
> Also, what should we display if there's a mix of types so if one line is showing total volume of pageviews and another line is displaying "unique users"

Ah good point... that's a case where we'd have to rely on the tooltip and legend to label lines of different units. Maybe this is only applicable when using consistent aggregation across things?

**Comment by andrewm4894** [comment]
One question is if I as the user can just type in the label. Eg I might just type in some easy name that my boss will understand even it that's not quite the actual units as PostHog might understand them.
