### ISSUE TITLE
Filtering for some properties results in weirdness

### ISSUE THREAD

**Issue by clarkus** [PostHog/posthog#9768]
## Bug description

Discovered in cohort creation, but also reproducible when filtering insights: when filtering using an `equals` operator, it's possible to select multiple values and then to specify the whole selected set as an appended group... this is really hard to describe so I made a video. 

## How to reproduce

https://user-images.githubusercontent.com/254612/168126487-9af2008f-1b27-41b6-ac87-b120b1e3dc68.mov

## Environment

- [x] PostHog Cloud

**Comment by pauldambra** [comment]
Are you saying that's not expected behaviour 🤣 ?

**Comment by clarkus** [comment]
Appears to be impacting recordings as well, but in a different way.

<img width="881" alt="Screen Shot 2022-05-12 at 9 55 32 AM" src="https://user-images.githubusercontent.com/254612/168128563-10841fbb-81ef-44da-a0a6-8ff2ea52cb43.png">

**Comment by pauldambra** [comment]
Oh, I bet this is https://github.com/PostHog/posthog/pull/9736#issuecomment-1124005327

**Comment by pauldambra** [comment]
I'll take a look shortly
