### ISSUE TITLE
Action and Heatmap with the same query give different results

### ISSUE THREAD

**Issue by pauldambra** [PostHog/posthog#9770]
## Bug description

In [this thread in the community slack](https://posthogusers.slack.com/archives/C01GLBKHKQT/p1651763788188849) it is reported that an action that exactly matches the toolbar's heatmap query doesn't match.

They're often the same scale ( i.e. 3 clicks vs 5 clicks, or 250 clicks vs 300 clicks. Action is always higher than heatmap.)

### Action definition

![image (1)](https://user-images.githubusercontent.com/984817/168153700-05682488-a9ec-417f-bcd4-203812210497.png)

### Heatmap query

![image](https://user-images.githubusercontent.com/984817/168153755-b3e7ff04-504f-4c59-adfe-242592039112.png)

## How to reproduce

1.
2.
3.

## Environment

- [ ] PostHog Cloud
- [ ] self-hosted PostHog (ClickHouse-based), version/commit: _please provide_
- [ ] self-hosted PostHog (Postgres-based, legacy), version/commit: _please provide_

**Comment by mariusandra** [comment]
@pauldambra can be closed?

**Comment by pauldambra** [comment]
It's a report from a self-hosted customer so I'd like to leave it open until we confirm that #9827 did or didn't help in 1.36.0

(we're not expecting it to completely resolve the issue but 🤞

**Comment by neilkakkar** [comment]
> we're not expecting it to completely resolve the issue

Why is that? 🤔

**Comment by pauldambra** [comment]
I think one resolution _might_ be via documentation...

E.g. in this test case there isn't an API response with a count of 558

![Screenshot 2022-05-23 at 13 56 07](https://user-images.githubusercontent.com/984817/169824377-5c276a5f-da5b-4c61-8010-8294cae16ea8.png)

![Screenshot 2022-05-23 at 13 56 18](https://user-images.githubusercontent.com/984817/169824373-6e0bc989-719d-4f1d-b7c0-758b4adb8fc2.png)

presumably multiple things from the API are matching against that HTML element and it needs to be clearer to the user why the numbers might differ

**Comment by pauldambra** [comment]
@neilkakkar the customer reports in Slack

> When I look at 90 days, I'm seeing 4,198 total sum on the trend map vs 3,846 on the heatmap. We're averaging 46 clicks a day, so doubtful that a few hours accounts for the hundreds of click discrepancy.

(sharing numbers here since the customer isn't identified :))
