### ISSUE TITLE
Adding a slight curvature to Graphs

### ISSUE THREAD

**Issue by lottiecoxon** [PostHog/posthog#9775]
## Is your feature request related to a problem?

Our graph lines are very sharp and I feel that they aren't consistent to our friendly branding.

## Describe the solution you'd like

Employ the use of a corner radius of 1. 
Example belows:

![Frame 9258](https://user-images.githubusercontent.com/65415371/168252222-f244c9b5-3d83-40c4-a202-b06e019b8e36.png)

![Frame 9259](https://user-images.githubusercontent.com/65415371/168252232-b93ca0d5-90a0-4890-9cda-1ef246db6cad.png)

## Describe alternatives you've considered

Not changing anything. I understand that the change potentially could feel pointless but it's the small details like these that together will influence the overall use of the app. aka push for quality even in the minor changes.

**Comment by clarkus** [comment]
I think this is a cool change but we should also consider the "[smoothing](https://app.posthog.com/feature_flags/1872)" feature that achieves a similar result but also impacts that actual values shown. It's feature flagged and I'm unsure how broadly it's released, but some default rounding here might make that feature less obvious when it's applied.

**Comment by neilkakkar** [comment]
I think that's very much a case of unfortunate naming: The rolling aggregation reduces angle between subsequent data points, which makes them look less sharp than they are, hence smoothing.

I think Lottie's idea makes sense, as it then also forces us to explain better what the smoothing feature is (as you rightly point out, the smoothing is more about the data, not the visualisation. It _appears_ to smooth things out though, hence the unfortunate-imo name 😅 )
