### ISSUE TITLE
How to talk to the app from the toolbar on a customer's site?

### ISSUE THREAD

**Issue by mariusandra** [PostHog/posthog#978]
Hi all, here's one open question with the toolbar.

How to talk to the API in a secure way? 

Currently posthog-js calls the `/decide` API endpoint, which replies "you're logged in, show the toolbar". This endpoint is fetched in posthog-js with `credentials: 'include' / withCredentials: true` and it responds with `response["Access-Control-Allow-Credentials"] = 'true'`. [Plainly](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Access-Control-Allow-Credentials), whenever any script on any site (doesn't have to be a friendly one) calls `app.posthog.com/decide`, it gets an answer if you're logged in or not.

I'm not sure what the potential attack is that can use this information. Perhaps an attacker could use a XSS hole in a popular site to inject code that figures out which site users also use posthog... and then sends them to a fake posthog login page either directly or later in a phishing mail?

I'm not sure if that's what we want. Minimising attack vectors seems like a smart choice.

In any case we can't use the `/decide` endpoint to send a "secret/jwt/csrf/etc token" that could be used to make API requests, as we don't know who's asking.

The current `temporary_token` system used by `editor.js` and `actions.py` is activated by selecting the site in app.posthog.com and then loading that URL with `#token=in&the=hash`. This token is then used to add actions.

The downside of this system is that you need to click an action in the app to go to your site and only in subsequent visits the toolbar can show up automatically, assuming the `temporary_token` hasn't expired. Not the most seamless experience, but at least it works.

If the token has expired, we can just show a locked toolbar button, that, when clicked, redirects you to a consent page on app, which then redirects back to the site with a token in the URL... and everything works normally afterward.

Thoughts? In short:

1. Should we keep the `/decide` and `isAuthenticated` system that we use to show the toolbar automatically or kill it as it leaks some anonymous, yet potentially useful information?
2. If killing it, how then to figure out if we should show the toolbar or not? We could have the site itself call `posthog.init('asdf', { iAmAdminShowToolbar: true } )` if the user is an admin that should see the toolbar? Too complicated?
3. How to get a token when initiating the request in posthog-js? Redirect with a consent page that uses the same `temporary_token` system from actions? Or even sends a regular JWT? How often to renew? Other thoughts?

**Comment by timgl** [comment]
1. I do not believe this to be a major risk, b/c as you mention the fact you're logged in to posthog on it's own is not very useful, and you tend to be able to see this when you go to someone's website anyway.
2. -
3. Agree we should show the toolbar even if you don't have a token, and then redirect you to a consent page. I think once consent is given, it doesn't have to be renewed for a while (couple of months, year?).

**Comment by EDsCODE** [comment]
3. The redirecting to verify seems reasonable. Like James G mentioned before this part will feel like a MFA redirect so it shouldn't be that jarring.

as for the /decide endpoint in figuring out to render the toolbar, quite frankly, I'm also shallow on the consequences of that information. it seems pretty trivial knowing the login status

**Comment by mariusandra** [comment]
Ok, then fine for keeping /decide as is for me as well!

Regarding the token exchange, anyone willing/free to pick that up? Otherwise I'll get to it eventually...

I think we just need a page like https://app.posthog.com/give_me_the_token?redirect=https://mysite.com

... which checks if you're logged in and if your team's urls include this redirect. If so, ask for consent and then redirect back with a token, similar to how it's done now. 

Should this token then be used to make any API request? Or should we whitelist some endpoints?

**Comment by timgl** [comment]
We should definitely scope where you can use a temporary token as small as possible.

**Comment by mariusandra** [comment]
Thank you @timgl for #992 and #888 ! 
One question remains: how to grant access through the temporaryToken in all the endpoints that should allow it? For now I just copied the same code from `actions.py` into `elements.py` 

https://github.com/PostHog/posthog/pull/974/files#diff-94b39f618e75711e8d0083866441d41dR15-R32

It gets the job done for testing, but there should be a clean and djangoesque way to abstract this.

Again, I'll get to it eventually... but I wouldn't mind someone else picking this up. :)

**Comment by timgl** [comment]
Should be pretty simple! Just put `TemporaryAuthentication` in utils, then on any endpoint you want to give access do
```python
authentication_classes = [TemporaryTokenAuthentication, authentication.SessionAuthentication, authentication.BasicAuthentication]
```

**Comment by mariusandra** [comment]
Ok, that's done: https://github.com/PostHog/posthog/pull/974/commits/ab335abaa8090b80b846a8e4dd893eeced9ac592

Still stuff to do before that PR is ready though.

However we'll run into a new problem very soon. This temporary token can only be used on one device at a time. It's regenerated every time `redirect_to_site` is called. Thus you must constantly reauthenticate if you're browsing your own site on your phone and your laptop.

That plus token expiration, which should also be implemented.

**Comment by mariusandra** [comment]
Closing this. I created separate notes in the [toolbar project](https://github.com/PostHog/posthog/projects/7) regarding token expiration and multiple tokens.
