### ISSUE TITLE
Retention number input broken (displays NaN)

### ISSUE THREAD

**Issue by yakkomajuri** [PostHog/posthog#9799]
## Bug description

Note that in the video I'm trying to type the whole time

https://user-images.githubusercontent.com/38760734/168616129-3eca7209-329d-4fb5-aecf-5ebb7c9019ae.mov

## Environment

- [x] PostHog Cloud
- [x] self-hosted PostHog (ClickHouse-based), version/commit: _please provide_

**Comment by benjackwhite** [comment]
Will be fixed as part of https://github.com/PostHog/posthog/pull/9830/commits/8cbe533e427a3d89115a0ad3a770ca8c7bcfbf02
