### ISSUE TITLE
Y-axis for events have decimal numbers

### ISSUE THREAD

**Issue by eikooc** [PostHog/posthog#982]
**Is your feature request related to a problem? Please describe.**
No. It is just a design improvement.

The current way events are showed are with decimals. But we cannot have half an event, so it doesn't make sense.

**Describe the solution you'd like**
Show y-axis for events as natural numbers i.e. without decimals.

**Describe alternatives you've considered**

**Additional context**
Image showing decimal numbers:
![image](https://user-images.githubusercontent.com/1305015/84366426-14954f00-abd3-11ea-8ef1-6f1dbd74d4f8.png)

***Thank*** you for your feature request - we love each and every one!

**Comment by timgl** [comment]
@eikooc Thanks for raising! that's fixed :)
