### ISSUE TITLE
Use pageview attributes in a user path insight instead of the page url

### ISSUE THREAD

**Issue by johnelbacani** [PostHog/posthog#9834]
## Is your feature request related to a problem?
Yes. We want to create a user path insight that includes pages visited. But we only want to see the types of pages visited(i.e. homepage, employer profile, job detail, search page, etc). We pass this information with every pageview to the page type attribute.

## Describe the solution you'd like
We want to be able to select a pageview attribute and break down by that attribute instead of the page url.

## Describe alternatives you've considered
We can try using the cleaning rules, but it would be too tedious as there are too many possibilities.
We can alternatively define actions for each page type. But it seems actions are not included in the user path either.

**Comment by yakkomajuri** [comment]
cc @neilkakkar
