### ISSUE TITLE
Per-project event count 

### ISSUE THREAD

**Issue by camerondeleone** [PostHog/posthog#9839]
## Is your feature request related to a problem?

Issue: As an account admin/someone responsible for finances, I have no way to attribute per-project pricing or event usage when I am billed. 

## Describe the solution you'd like

Some ability to break down the total event count by project, at minimum. 

At minimum, show raw event counts by project on the billing page (or on `/instance/status` on self-hosted). More detail would be better (eg show custom events, autocapture, and pageviews separately would be a nice to have), broken down by events and total charge, etc.

## Describe alternatives you've considered

Ask someone at PostHog to put together a custom dashboard...

## Additional context

From a customer rolling out Enterprise: 

> Ultimately the reason I need this is so I can hold the project owners accountable for the ROI. So tracking this at least from a project perspective is super necessary

**Comment by neilkakkar** [comment]
It sounds like you're looking for something like this:

https://app.posthog.com/insights/ORTF2Toc

But instead of just `$pageview` events, you want all events?

**Comment by camerondeleone** [comment]
Kind of - I want all events, but segmented by the same period we use for billing (ie from stripe, differs by customer). I can do that last bit myself in the one-off case by continually updating the date range, but the 'all events' bit is the crucial bit. No good way for a customer to understand their costs by project (eg if i'm doubling my spend because I'm sending too many events to a dev instance, or if I have to keep product owners accountable for their tracking spend).
