### ISSUE TITLE
<svg> element does not show in session recording

### ISSUE THREAD

**Issue by nxjniexiao** [PostHog/posthog#9850]
## `<svg>` element dose not show in session recording

The svg elements in my application were not showing up in session recording. 
It turns out to be the `xlink:href` attribute of the `<use>` element was modified.

![image](https://user-images.githubusercontent.com/30365414/169246157-f1481341-ef48-47ea-bc76-732b079e95a6.png)

![image](https://user-images.githubusercontent.com/30365414/169246171-5d7d00ad-8f99-4b0c-a62c-9e13e395f32a.png)

## Environment

self-hosted PostHog (ClickHouse-based), version/commit: Version 1.33.0

**Comment by timgl** [comment]
@rcmarron

**Comment by rcmarron** [comment]
Hey @nxjniexiao, thanks for reporting this (and for the investigation into the cause!).

I'm going to look into it further - hoping to get to it later this week. Is the site where this happens something I could access?

**Comment by nxjniexiao** [comment]
Hey @rcmarron , I created and shared a file without access rights: https://www.lynkage.cn/share/wDscBd7RtSGtkd8 . Hope it is useful。

**Comment by pauldambra** [comment]
Can't investigate this without recordings/source
