### ISSUE TITLE
Bug + Feedback: Billing prompt in Paths

### ISSUE THREAD

**Issue by joethreepwood** [PostHog/posthog#9886]
## Bug description

I just logged in to PostHog on PostHog, headed over to Paths, spotted the `Advanced Options` box out, opened it and...

<img width="480" alt="Screenshot 2022-05-20 at 14 40 12" src="https://user-images.githubusercontent.com/84011561/169540396-42c10134-6385-4110-808f-62ebf247d1e4.png">

Pretty sure that we don't give ourselves a billing limit, so this is either a bug or a feature flag.

Also have some feedback on this message which should be addressed.

UPDATE: Confirmed by @benjackwhite that it's behind a FF. _PHEW!_

## How to reproduce

1. Log in. 
2. Paths. 
3. Advanced Options

## Feedback & Context

There are a few issues with this message, even if it isn't a bug. 

1. Opinion: Having a link within a clickable box feels like a UI no-no. The whole box is clickable, but there's a hyperlink in the middle of it. I'm not sure what the arrow is meant to mean.
2. The docs which the hyperlink directs to (`/docs/users-guides/paths`) doesn't actually contain any of the information the message alludes to. There's no info on wildcarding, exclusions or funnels. 
3. We're missing a full stop after 'Learn more'. 
4. Dismissing the message with the `X` gets rid of the message (obviously)...but then the `Advanced Options` box is left with no content in it? Feels weird. Seems better to leave it and just let people close the `Advanced Options` box. 
5. From a marketing POV I think we can do better with the copy as a whole by tying the headline to the intent: `Add billing info to get more features`

Obviously feel free to discard feedback as you wish!

## Environment

- [ ] PostHog Cloud
- [ ] self-hosted PostHog (ClickHouse-based), version/commit: _please provide_
- [ ] self-hosted PostHog (Postgres-based, legacy), version/commit: _please provide_

**Comment by clarkus** [comment]
It appears this is tied to this [feature flag](https://app.posthog.com/feature_flags/1194). Agree that it's not really optimal especially when enclosed in an editor panel. The change originated in https://github.com/PostHog/posthog/pull/7301

**Comment by benjackwhite** [comment]
https://github.com/PostHog/posthog/pull/9896 Fixed the general bug as to when this should be shown as well as getting rid of the option to close it for this case.

The more general question of the choices of text and interaction is not solved though
