### ISSUE TITLE
Unable to re-invite a user that has been deleted  

### ISSUE THREAD

**Issue by guidoiaquinti** [PostHog/posthog#9899]
## Bug description
I'm unable to re-invite a user that has been deleted from a project.

## How to reproduce

1. invite user `user@example.com`
2. `user@example.com` completes the registration 
3. `user@example.com` gets deleted by a project admin
4. `user@example.com` gets re-invited by a project admin
5. `user@example.com` can't complete the registration

## Additional context
See Slack [thread](https://posthogusers.slack.com/archives/C01GLBKHKQT/p1653283459373119).

**Comment by Twixes** [comment]
I'm pretty sure they can be re-added, they just need to log in with their existing account to accept the invite. I can see how this may not be the most intuitive on single-organization self-hosted instances, but deleting the user then would for instance cause "created by" fields to go blank, which wouldn't be a great user experience for the remaining user. Perhaps the fix here should be just to make it clear that when a user is removed from an org, their PostHog account is NOT removed altogether.

**Comment by guidoiaquinti** [comment]
Thank you for the additional context @Twixes. I agree with you the current behaviour is not very intuitive. In this case, what would be the suggested user flow for a self-hosted instance without email configured and with a user that can't recover the password of the account? Deleting and re-creating the user will not work.
