### ISSUE TITLE
Bug: Inconsistent abbreviation of property names in global filters

### ISSUE THREAD

**Issue by joethreepwood** [PostHog/posthog#9900]
## Bug description

Building on @andyvan-ph's feedback in Slack that [global filters are now harder to use](https://posthog.slack.com/archives/C011L071P8U/p1653298412107269), I went to have a look this issue myself. And found a bug!

That is, we seem to be inconsistent in turning overflowing property names to ellipsis `...` and in using the PostHog logo (which I think is meant to be used just on autocapture events, normally). 

Here's an example...

<img width="462" alt="Screenshot 2022-05-23 at 10 57 29" src="https://user-images.githubusercontent.com/84011561/169794669-bd98191d-8717-4d91-930a-9eb6b9d71f08.png">

Here, from top to bottom, I'm trying to track some properties which I chose based on them having long names. 

```
$active_feature_flags_1
Initial referring domain
Feature: filter_by_session_props_link
onboarding 1 test users ingested
Library Version
event_count_new_in_period
$enables_feature_flags_4267-event-property-taxonomy
```
In the screenshot above, some of those with the _shortest_ names get reduced to ellipsis (e.g. `Initial referring domain`, `Library Version`) while the longest (`$enables_feature_flags_4267-event-property-taxonomy`) do not. 

Others which I don't believe are autocaptured events, such as `Feature: filter_by_session_props_link`, are also accompanied by the PostHog logo. I always thought we only used this logo on autocaptured events?

Regardless, this is at full size on a 4K screen. It actually looks better if you shrink the window size dramatically. Then, it looks like this and the size of the filter modal increases because it now stacks on top of other elements, not side by side. 

<img width="659" alt="Screenshot 2022-05-23 at 10 55 43" src="https://user-images.githubusercontent.com/84011561/169794332-5c8ed8dc-8453-4e6c-8ca0-3300b5638d3e.png">

## How to reproduce

1. Filters
2.
3.

## Environment

- [ ] PostHog Cloud
- [ ] self-hosted PostHog (ClickHouse-based), version/commit: _please provide_
- [ ] self-hosted PostHog (Postgres-based, legacy), version/commit: _please provide_

**Comment by charlescook-ph** [comment]
Not sure if what I'm seeing is necessarily a bug, but similarly the way property names are now presented makes it more difficult to view them:

<img width="428" alt="Screenshot 2022-05-23 at 10 57 21" src="https://user-images.githubusercontent.com/70321811/169795424-eeec4ae0-d169-4be3-9b9e-16f519bb56ca.png">

**Comment by benjackwhite** [comment]
I think this is somewhat easily solved. The TaxonomicFilter is changing shape based on the page width rather than the component but we can probably move over to a flex-style css that accomplishes the same goal
