### ISSUE TITLE
Trends tooltips are broken due to timezones support

### ISSUE THREAD

**Issue by Twixes** [PostHog/posthog#9903]
## Bug description

There no longer is a tooltip in Trends graphs:

<img width="264" alt="trends" src="https://user-images.githubusercontent.com/4550621/169812354-a4683870-d4a0-4b4a-9611-db81441afbe5.png">

CC @timgl 

## How to reproduce

1. Go to a Trends insight.
2. Hover over the graph and see there's no tooltip.
3. Go to the browser console and see this error popping up constantly when hovering over the graph:
    <img width="227" alt="err" src="https://user-images.githubusercontent.com/4550621/169812604-ddf6f6c0-9344-46e7-a3e5-a3476b8aae9f.png">
4. ???
5. No profit.

## Environment

- [x] PostHog Cloud, PostHog App + Website project

**Comment by timgl** [comment]
Should be fixed with https://github.com/PostHog/posthog/pull/9882
