### ISSUE TITLE
Bug: My dashboard has gone missing and I didn't delete it

### ISSUE THREAD

**Issue by andyvan-ph** [PostHog/posthog#9906]
## Bug description

A dashboard called "Website & SEO" has gone missing. It's not visible in any searches, but I know it's there somewhere...

When I view insights I know are on the dashboard, I get this message but the dashboard isn't visible to select. 

![Screenshot 2022-05-23 at 13 53 29](https://user-images.githubusercontent.com/92976667/169825520-8360a6b6-0028-4077-abdc-4f75299bde4d.png)

## How to reproduce

Honestly not 100% sure, but this happened when I clicked on an insight on the dashboard, edited the insight and saved it. After that, the dashboard has been inaccesible to me. 

## Environment

- [x] PostHog Cloud
- [ ] self-hosted PostHog (ClickHouse-based), version/commit: _please provide_
- [ ] self-hosted PostHog (Postgres-based, legacy), version/commit: _please provide_

## Additional context
n/a

**Comment by pauldambra** [comment]
@andyvan-ph I'll take a look

**Comment by timgl** [comment]
Still accessible directly weirdly: https://app.posthog.com/dashboard/28987

**Comment by pauldambra** [comment]
Hmmm, I think it might be paging...

There's no paging available in the UI but we're returning a "next" url in the dashboards API response

**Comment by pauldambra** [comment]
Yep, @andyvan-ph you should be able to access your dashboard again now

There's a hard limit on how many dashboards we can handle. I had some test dashboard I could delete. Will need to add pagination to the dashboards `LemonTable`
