### ISSUE TITLE
Allow switching between projects without modifying user's `current_team`

### ISSUE THREAD

**Issue by samwinslow** [PostHog/posthog#9907]
## Is your feature request related to a problem?

Hello friends. I'm integrating PostHog at a new company, and have noticed it is not possible to switch back and forth between projects without causing a backend change to the user's current team. In our case, we have two separate projects for staging and production and want to replicate/compare dashboards across these projects.

## Describe the solution you'd like

Manage the user's current team via some sort of client-side persistence, like a cookie, rather than a global, account-level setting. I could then sign in and access two separate projects by using a different browser or an incognito window.

## Describe alternatives you've considered

- Use staging project, screenshot an insight, switch to production project, replicate that insight (currently doing this — lots of clicking)
- Use a single project and set the environment in event properties (UX problem: every insight would filters applied)
- Use two separate organizations (separate logins, separate billing... impractical)

#### *Thank you* for your feature request – we love each and every one!

Thanks for continuing to build an awesome product.

**Comment by paolodamico** [comment]
+1 from our side, it has caused significant confusion to some users newer to PostHog when they receive a link to a specific person and they just see a "Person not found" message because they're on a different project. Having the project ID encoded on the URL seems like a great solution for this.

**Comment by timgl** [comment]
Thanks both! This is a duplicate of #5363 so closing, but thanks for bumping the priority.
