### ISSUE TITLE
Bug: Mouseover on Insights in Dashboards not working

### ISSUE THREAD

**Issue by andyvan-ph** [PostHog/posthog#9908]
## Bug description

Mousing over on Insights on Dashboards doesn't show the values on those insights.

## How to reproduce

1. Load a dashboard
2. Mouseover an insight
3. Sad noises

https://user-images.githubusercontent.com/92976667/169831196-2581ebf0-2d32-4833-83e5-0db4196590a2.mov

## Environment

- [x] PostHog Cloud
- [ ] self-hosted PostHog (ClickHouse-based), version/commit: _please provide_
- [ ] self-hosted PostHog (Postgres-based, legacy), version/commit: _please provide_

## Additional context
n/a

#### *Thank you* for your bug report – we love squashing them!

**Comment by clarkus** [comment]
Think this is related to https://github.com/PostHog/posthog/issues/9903#issuecomment-1134576039

**Comment by Twixes** [comment]
Should be fixed too.
