### ISSUE TITLE
Legend labels don't match chart

### ISSUE THREAD

**Issue by jackiegreenfield** [PostHog/posthog#9916]
## Bug description

The labels on the legend don't match the chart for Chart Type: Value

The colors are accurate, and checking/unchecking works just fine. But it's very confusing to have the wrong labels in the legend.

![image](https://user-images.githubusercontent.com/96656004/169867549-ec10c3ea-20fd-4578-855d-1c7dd91e4a61.png)

Lines showing how the labels actually match up:
![image](https://user-images.githubusercontent.com/96656004/169867125-b51c0133-23a6-4ae5-9b89-16ccddfaf508.png)

## How to reproduce
Make an Insight Trend with multiple series. Use chart type: value. Show legend. Note that the labels on the legend do not match what's on the graph for each color. 

## Environment
Self-hosted Posthog (Clickhouse-based), v1.35

**Comment by timgl** [comment]
@alexkim205 could you have a look?

**Comment by timgl** [comment]
@jackiegreenfield This'll be fixed in the next release for you
