### ISSUE TITLE
Somewhere in the App show the ProjectID for API usage

### ISSUE THREAD

**Issue by benjackwhite** [PostHog/posthog#9992]
## Is your feature request related to a problem?

In the API Docs we refer to `:project_id` for most endpoints but we don't really give people an easy way to know what their project ID is. We mention that you can use the [project api key ](https://posthog.com/docs/api#specifying-a-project-when-using-the-api) and I think falsely state that if omitted we will use the last selected project. 

The only ways currently to know are to inspect your network traffic in Posthog or to call the `/projects` endpoint (which is overkill for most teams with one project)

## Describe the solution you'd like

I would propose we add a section to the Project Settings detailing the current Project ID with a link to the API docs about it and then vice versa update the Docs to link to where the person can find their project ID.

## Additional context

Particularly interested if @Twixes or anyone knows of something I am missing which might already exist documentation-wise

**Comment by pauldambra** [comment]
OMG YES!

**Comment by clarkus** [comment]
Could this also be exposed in the URL so that people don't get confused when project switching happens? I think it'd be good to show it in the project settings, but baking it into the URL would also make it easier to find. Related https://github.com/PostHog/posthog/issues/5363
