### ISSUE TITLE
Cumulative trends total sum doesn't make sense

### ISSUE THREAD

**Issue by erinbester** [PostHog/posthog#9994]
## Bug description

*Please describe.*  
*If this affects the front-end, screenshots would be of great help.*  
The main table at the bottom on the experiment is not showing the correct total. It is showing the same numbers as the last day in the experiment. See screenshot.
![image](https://user-images.githubusercontent.com/106265386/170309544-36e7c34a-ce3c-4615-8305-4672be013320.png)

## How to reproduce

1. Start an experiment
2. let it run at least 2 days
3. check the total column in the table

## Environment

**- [ ] PostHog Cloud**
- [ ] self-hosted PostHog (ClickHouse-based), version/commit: _please provide_
- [ ] self-hosted PostHog (Postgres-based, legacy), version/commit: _please provide_

**Comment by neilkakkar** [comment]
Thanks @erinbester !

Just FYI: Since the table is cumulative, the total is indeed what's seen in the last column. 

We could definitely do a better job of explaining this in the table though. I'll edit your description to reflect this :)
